### ISSUE TITLE
Improve cloudup reconciliation test coverage

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#10006]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
I've noticed a few gaps in how the cloudup tasks reconcile their state with the cloud provider. Sometimes a certain transition from one state to another isn't covered, other times it results in repeated changes being reported by subsequent `update cluster`s. [This](https://github.com/kubernetes/kops/pull/9996) is one example, where the removal of an `additionalNetworkCIDRs` item didnt actually remove the CIDR.

I think we could improve test coverage to catch these types of issues. Our [lifecycle_integration_test.go](https://github.com/kubernetes/kops/blob/master/cmd/kops/lifecycle_integration_test.go) runs two `update cluster`s in a row and confirms the second one does not report any changes. I think we could do something similar while also making various changes to the cluster and instance groups

**2. Feel free to provide a design supporting your feature request.**
One idea I had was to include a new "cluster overrides" file in the integration test directories. The file could be a list of overrides that use kops' new `--set` reflection-based syntax. For each item in the list, the test would apply the override, then `update cluster` twice and confirm no changes reported, then update back to the original manifest twice and ensure no changes are reported.

example overrides file:
```
spec.additionalNetworkCIDRs[0]=10.0.0.0/16
spec.cloudConfig.elbSecurityGroup=foo
spec.access.loadbalancer.sslCertificate=foo
``` 

Thoughts on this, or any alternative ideas?

**Comment by olemarkus** [comment]
The reconciliation logic is largely `ApplyClusterCmd.Run()`. So it is also possible to use `BuildMinimalCluster` to build a cluster spec, then do a number of modifications to it and then apply it a couple of times. The benefit of building the clusterspec in code is that it would be simpler to run many smaller variations vs having many files that one would have to maintain for input.

OpenStack's [servergroup_test.go](https://github.com/kubernetes/kops/blob/master/pkg/model/openstackmodel/servergroup_test.go) also runs quite a bit of reconciliation logic using specs in code and golden outputs. This one doesn't run the test twice though, but one can quite easily ensure there are no unexpected regressions.
