### ISSUE TITLE
Rolling update ignore unready nodes in inapplicable instance groups

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#10009]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Currently when a rolling update is performing cluster validation and an unrelated nodes instancegroup scales up, the rolling update will wait for that node to pass validation. It would be desirable if the rolling update could proceed even when nodes in unrelated instance groups are unhealthy.

The exception is that failures in instance groups of role "master" should probably block the progression of rolling update in other instance groups.

**2. Feel free to provide a design supporting your feature request.**

The cluster validation API will need to be changed such that failures that are specific to a node are associated with that node. Examples of such failures would be node readiness and unready pods with system-node-critical priority. The "not enough nodes in instance group" failure would need to be associated with the group. Rolling update would then need to ignore validation failures that are in irrelevant groups.

**Comment by bharath-123** [comment]
Hey @johngmyers ! I would like to pick this issue up and submit a PR. 
Any steps to reproduce this issue or any suggestions for me before setting out to resolve this issue would be highly appreciated :)

**Comment by johngmyers** [comment]
@bharath-123 to reproduce this, start with a cluster that has at least two instance groups of role "Nodes". Perform a rolling update on one of the instance groups, using `--force` if necessary to get it to update the group's nodes. While the a new node is coming up and rolling update is validating, terminate a node in the other instance group. You will notice that the validation phase will wait for the other instance group to become completely ready before proceeding to drain another node in the instance group it is updating.

A PR for this will have at least two commits. One commit will update the `validation.ClusterValidator` interface so that a caller will be able to tell when a returned `ValidationError` is specific to a node or group and be able to determine which instance group that applies to. I'm being a bit nonspecific on how it should return this information as that is part of designing the change, but I can give suggestions if needed.

The change will also have to correspondingly mark the group-specific `ValidationError`s as such. Those failures are:

* In `collectPodFailures`, any of the `Kind: "Pod"` failures when the priority is `"system-node-critical"`. These are things like CNI DaemonSet pods. (When the priority is "system-cluster-critical", that is a cluster-wide failure that should always block a rolling update.)
* All of the failures returned by `validateNodes`.

My view is that an unhealthy control plane should block a rolling update, so the `masterWithoutPod` failures could be considered to be cluster-wide. It would be acceptable to consider them specific to their instance group.

A subsequent commit would change `validateClusterWithTimeout` to ignore returned validation failures that apply to instance groups that are both of role `InstanceGroupRoleNode` and not the instance group being updated. I usually start such changes by first updating the unit tests to assert the new behavior, verifying they fail, then implementing the change. The commit would then change both the tests and the implementation.

**Comment by bharath-123** [comment]
@johngmyers thanks for these suggestions! Super helpful! I ll begin work on this and think on my own too :) I ll get acquainted with the codebase and begin work. Please feel free to assign me to this. 

I hope I can catch you and the rest of the kops people on the slack channel! :D 

I will make sure to notify you if I am unable to pursue this issue for any reason.
