### ISSUE TITLE
Cleanup cloudformation lint warnings

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#10015]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
AWS provides this tool for linting cloudformation files: 

https://github.com/aws-cloudformation/cfn-python-lint

Running it against our integration test outputs in `tests/integration/update_cluster/*/cloudformation.json` reports quite a few warnings including mismatched types. It would be great to fix those and address any other issues.

Once they're fixed we could create a `hack/verify-cloudformation.sh` script similar to `hack/verify-terraform.sh` that ensures we dont introduce any new linting errors.
 
**2. Feel free to provide a design supporting your feature request.**

Theres [no official image](https://github.com/aws-cloudformation/cfn-python-lint/issues/1025) so we'd probably have to build a local docker image if a local one doesn't already exist. an example output:
```
docker run --rm -v `pwd`:/data cfn-python-lint:latest /data/tests/integration/update_cluster/complex/cloudformation.json

E3012 Property Resources/AWSAutoScalingAutoScalingGroupmasterustest1amasterscomplexexamplecom/Properties/MaxSize should be of type String
/data/tests/integration/update_cluster/complex/cloudformation.json:18:9

E3012 Property Resources/AWSAutoScalingAutoScalingGroupmasterustest1amasterscomplexexamplecom/Properties/MinSize should be of type String
/data/tests/integration/update_cluster/complex/cloudformation.json:19:9

E3012 Property Resources/AWSAutoScalingAutoScalingGroupnodescomplexexamplecom/Properties/MaxSize should be of type String
/data/tests/integration/update_cluster/complex/cloudformation.json:99:9

E3012 Property Resources/AWSAutoScalingAutoScalingGroupnodescomplexexamplecom/Properties/MinSize should be of type String
/data/tests/integration/update_cluster/complex/cloudformation.json:100:9

E3031 CidrIp contains invalid characters (Pattern: x.x.x.x/y) at Resources/AWSEC2SecurityGroupIngresshttpsapielb20010850040/Properties/CidrIp
/data/tests/integration/update_cluster/complex/cloudformation.json:591:9

E3031 CidrIp contains invalid characters (Pattern: x.x.x.x/y) at Resources/AWSEC2SecurityGroupIngressicmppmtuapielb20010850040/Properties/CidrIp
/data/tests/integration/update_cluster/complex/cloudformation.json:629:9

E3031 CidrIp contains invalid characters (Pattern: x.x.x.x/y) at Resources/AWSEC2SecurityGroupIngresssshexternaltomaster2001085a348/Properties/CidrIp
/data/tests/integration/update_cluster/complex/cloudformation.json:757:9

E3031 CidrIp contains invalid characters (Pattern: x.x.x.x/y) at Resources/AWSEC2SecurityGroupIngresssshexternaltonode2001085a348/Properties/CidrIp
/data/tests/integration/update_cluster/complex/cloudformation.json:781:9

E2510 Not a valid Availbility Zone us-test-1a at Resources/AWSEC2Subnetustest1acomplexexamplecom/Properties/AvailabilityZone
/data/tests/integration/update_cluster/complex/cloudformation.json:895:9

W3010 Don't hardcode us-test-1a for AvailabilityZones
/data/tests/integration/update_cluster/complex/cloudformation.json:895:9

W3010 Don't hardcode us-test-1a for AvailabilityZones
/data/tests/integration/update_cluster/complex/cloudformation.json:992:9

W3010 Don't hardcode us-test-1a for AvailabilityZones
/data/tests/integration/update_cluster/complex/cloudformation.json:1031:9

E3012 Property Resources/AWSElasticLoadBalancingLoadBalancerapicomplexexamplecom/Properties/Listeners/0/InstancePort should be of type String
/data/tests/integration/update_cluster/complex/cloudformation.json:1073:13

E3012 Property Resources/AWSElasticLoadBalancingLoadBalancerapicomplexexamplecom/Properties/Listeners/0/LoadBalancerPort should be of type String
/data/tests/integration/update_cluster/complex/cloudformation.json:1075:13

E3012 Property Resources/AWSElasticLoadBalancingLoadBalancerapicomplexexamplecom/Properties/HealthCheck/HealthyThreshold should be of type String
/data/tests/integration/update_cluster/complex/cloudformation.json:1093:11

E3012 Property Resources/AWSElasticLoadBalancingLoadBalancerapicomplexexamplecom/Properties/HealthCheck/UnhealthyThreshold should be of type String
/data/tests/integration/update_cluster/complex/cloudformation.json:1094:11

E3012 Property Resources/AWSElasticLoadBalancingLoadBalancerapicomplexexamplecom/Properties/HealthCheck/Interval should be of type String
/data/tests/integration/update_cluster/complex/cloudformation.json:1095:11

E3012 Property Resources/AWSElasticLoadBalancingLoadBalancerapicomplexexamplecom/Properties/HealthCheck/Timeout should be of type String
/data/tests/integration/update_cluster/complex/cloudformation.json:1096:11
```

We can ignore `E2510` and `W3010` but we should fix the others. The `hack/verify-cloudformation.sh` script would be added to the `ci` make target, just like `verify-terraform`.

**Comment by Anu-9518** [comment]
I would like to take it up.

**Comment by rifelpet** [comment]
@Anu9518 do you need any assistance with this?

**Comment by binkkatal** [comment]
@rifelpet , are the json files auto generated ? and is it fine if it gets updated manually ?

**Comment by hakman** [comment]
@binkkatal Json files are updated via `hack/update-expected`. It is not ok to update manually.

**Comment by rifelpet** [comment]
The json is generated from go struct types defined in `upup/pkg/fi/cloudup/awstasks` package.

For example, the autoscaling group min size and max size fields are integers but should be strings. We could update the field types [here](https://github.com/kubernetes/kops/blob/d105c9299e7e9f451c9d36876ddb6b3d62f1f6d4/upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go#L865-L866), update where they're being set a few lines below that, and run `./hack/update-expected.sh` and that should change the types in the cloudformation.json files.

**Comment by binkkatal** [comment]
@rifelpet , @hakman ,
I raised a [PR#1066](https://github.com/kubernetes/kops/pull/10066) on this, rest of the lint errors were fixed.
There is one pending lint error which states as

```
E3031 CidrIp contains invalid characters (Pattern: x.x.x.x/y) at Resources/AWSEC2SecurityGroupIngressicmppmtuapielb20010850040/Properties/CidrIp
tests/integration/update_cluster/complex/cloudformation.json:629:9
```

need help with the format

**Comment by rifelpet** [comment]
The CidrIp error sounds like an actual bug. That json line number is an IPv6 cidr block, and the [cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule-1.html) show a separate `CidrIpv6` field. I think we should create that second field in our cloudformation type [here](https://github.com/kubernetes/kops/blob/18ffb493bf2c796b122879b9ef6489f6aaf0793f/upup/pkg/fi/cloudup/awstasks/securitygrouprule.go#L342-L351) and then down [here](https://github.com/kubernetes/kops/blob/18ffb493bf2c796b122879b9ef6489f6aaf0793f/upup/pkg/fi/cloudup/awstasks/securitygrouprule.go#L385-L387) detect whether the CIDR field is ipv4 or ipv6 and set whichever cloudformation field is appropriate.

**Comment by binkkatal** [comment]
> The CidrIp error sounds like an actual bug. That json line number is an IPv6 cidr block, and the [cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule-1.html) show a separate `CidrIpv6` field. I think we should create that second field in our cloudformation type [here](https://github.com/kubernetes/kops/blob/18ffb493bf2c796b122879b9ef6489f6aaf0793f/upup/pkg/fi/cloudup/awstasks/securitygrouprule.go#L342-L351) and then down [here](https://github.com/kubernetes/kops/blob/18ffb493bf2c796b122879b9ef6489f6aaf0793f/upup/pkg/fi/cloudup/awstasks/securitygrouprule.go#L385-L387) detect whether the CIDR field is ipv4 or ipv6 and set whichever cloudformation field is appropriate.

@rifelpet , can we have another github issue on this

**Comment by rifelpet** [comment]
the remaining issues have been addressed and a new presubmit job has been added to ensure the generated cloudformation json remains valid

/close
