### ISSUE TITLE
Add Calico implementation for disabling AWS source/destination checks

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#10014]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Calico 3.16 adds a new option to disable source/destination checks: https://github.com/projectcalico/felix/pull/2381.
https://docs.projectcalico.org/reference/resources/felixconfig#spec

This can replace the current implementation that uses https://github.com/ottoyiu/k8s-ec2-srcdst.

**2. Feel free to provide a design supporting your feature request.**

At the moment, this is enabled automatically when `spec.networking.calico.crossSubnet: true`.
https://kops.sigs.k8s.io/networking/calico/#enable-cross-subnet-mode-in-calico-aws-only

The manifest flag that can be used to enable/disable this feature in Calico is `FELIX_AWSSRCDSTCHECK`. It should be added as a separate option, but also keep the previous setting for backwards compatibility.

IAM Policies may need updating also to allow this to be set from any node.

**Comment by monicagangwar** [comment]
@hakman I'd like to give this a try, can you please assign this issue to me ?

**Comment by hakman** [comment]
Thanks for giving this a try @monicagangwar ! 😄 
/assign @monicagangwar

**Comment by monicagangwar** [comment]
@hakman a question here, if the option to provide the manifest flag `FELIX_AWSSRCDSTCHECK` is added along with the existing option `spec.networking.calico.crossSubnet` 
what should be the behaviour if the options are conflicting. eg: FELIX_AWSSRCDSTCHECK is set to `Disable` or `DoNothing` but `spec.networking.calico.crossSubnet` is set to true ?

**Comment by hakman** [comment]
I think the behaviour should be to enable the deployment for `k8s-ec2-srcdst`, but set the number of replicas to 0.
Unfortunately, kops cannot remove `k8s-ec2-srcdst` once it's deployed, so best to just to the above and document that if one wants to switch to `AwsSrcDstCheck`, should delete the `k8s-ec2-srcdst` deployment manually.

**Comment by monicagangwar** [comment]
@hakman correct me if i am wrong but why do we need to deploy k8s-ec2-srcdst altogether ? if `spec.networking.calico.crossSubnet` is set to true we can simply add the flag `FELIX_AWSSRCDSTCHECK` to `Disable` source destination checks, right ?

**Comment by hakman** [comment]
Consider the case where a user already has k8s-ec2-srcdst enabled. Even if disabled in `spec.networking.calico.crossSubnet`, it won't be removed. I will just stay hung in the cluster until manually deleted.
In this case the safe way would be to set the replicas to 0 for it if FELIX_AWSSRCDSTCHECK is not "DoNothing", otherwise, they may conflict.

**Comment by monicagangwar** [comment]
@hakman got it, as for backward compatibility i understood that along with the option `spec.networking.calico.crossSubnet` we need to provide another option like `spec.networking.calico.awsSrcDestCheck` which will correspond directly to the flag `FELIX_AWSSRCDSTCHECK`. what to do if these two settings are contradictory ?

**Comment by hakman** [comment]
With `spec.networking.calico.crossSubnet` you don't really have enable/disable. Once it is enabled, you cannot disable it anymore unless manually deleted.

Behaviour:
| crossSubnet | awsSrcDestCheck | Result |
| --- | --- | --- |
| false | Enabled/Disabled/DoNothing | k8s-ec2-srcdst deployment doesn't exist |
| true | Enabled/Disabled | k8s-ec2-srcdst deployment has 0 replicas, to effectively disable it |
| true | DoNothing | k8s-ec2-srcdst deployment has 1 replica |

New setting takes priority. Old setting will be deprecated soon.

**Comment by monicagangwar** [comment]
@hakman understood, thank you

**Comment by hakman** [comment]
Thanks also for the patience. If you have more Q, don't hesitate.
