### ISSUE TITLE
Install docker-ce via yum repositories instead of binary. Centos 7

### ISSUE THREAD

**Issue by dignajar** [kubernetes/kops#10028]
Hi,
there is some way to install docker-ce via `yum` repositories instead of the binary files ?

I have some packages installed via `yum` that have as dependency `docker-ce`, for example, the `nvidia-docker2` which depends on `docker-ce`.

I'm trying to use the docker version 18.09.9, but looks like was removed as rpm from the `docker.go`.
https://github.com/kubernetes/kops/blob/v1.18.1/nodeup/pkg/model/docker.go#L297

Environment:
- AWS
- Kops 1.18.1
- Centos 7
- Kubernetes 1.16.15
- Docker 18.09.9

**Comment by hakman** [comment]
@dignajar Unfortunately we went full .tgz to avoid all the packaging quirks. Any ideas on how to provide a fake `docker-ce` dependency?

**Comment by dignajar** [comment]
@hakman ok, no idea, I'm still looking for it, because `yum` doesn't provide a way to skip dependencies (which is quite strange).
You can close this issue if I found the way I will post it.

**Comment by dignajar** [comment]
I made fake RPM and works fine.

## The issue
```
--> Running transaction check
---> Package libnvidia-container1.x86_64 0:1.3.0-1 will be installed
---> Package nvidia-docker2.noarch 0:2.5.0-1 will be installed
--> Processing Dependency: docker-ce >= 18.06.3.ce-3.el7 for package: nvidia-docker2-2.5.0-1.noarch
--> Finished Dependency Resolution
Error: Package: nvidia-docker2-2.5.0-1.noarch (nvidia-docker)
           Requires: docker-ce >= 18.06.3.ce-3.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

## The solution

docker-ce.spec
```
Summary: Docker CE fake
Name: docker-ce
Version: 18.06.3.ce
Release: 3.el7
License: Public
Group: Applications/System
%description
Docker CE fake
%files
```

```
# Build and install the fake rpm
$ rpmbuild -bb docker-ce.spec
$ rpm -i ~/rpmbuild/RPMS/x86_64/docker-ce-18.06.3.ce-3.el7.x86_64.rpm

# Install nvidia-docker runtime
$ yum install -y nvidia-docker2
```

**Comment by hakman** [comment]
Thanks for posting the solution @dignajar .
