### ISSUE TITLE
Ability to set the DesiredCapacity for ASG.

### ISSUE THREAD

**Issue by jsonmp-k8** [kubernetes/kops#10029]
AWS provides the capability to add the desired capacity to the ASG, This feature is missing in KOPS. KOPS allows only minSize and maxSize to be set for the ASG. It will be really good if there is an option to set the desired capacity for the ASG while bringing up the KOPS cluster.

https://github.com/kubernetes/kops/blob/v1.18.1/pkg/apis/kops/instancegroup.go#L94-L96

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.18.1`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`v1.18.8`

**3. What cloud provider are you using?**

`AWS`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops update cluster`

**5. What happened after the commands executed?**
NA
**6. What did you expect to happen?**

Adding DesiredCapacity the the cluster spec should set the desired capacity in the ASG as per the configuration in cluster spec

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

A sample spec to add desired capacity would look like this

```yaml
  maxSize: 100
  minSize: 1
  desiredCapacity: 10
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

https://github.com/kubernetes/kops/blob/v1.18.1/pkg/apis/kops/instancegroup.go#L94-L96

**9. Anything else do we need to know?**
None

**Comment by hakman** [comment]
@jsonmp-k8 Min and Max are used in the context of Cluster Autoscaler, which dynamically sets Desired. What would be the use case for setting Desired in kops config?

**Comment by jsonmp-k8** [comment]
We have a cluster where we wanted to install istio and argocd as soon as the cluster is ready and wanted to manage cluster autoscaler using argocd. But when the minsize is set 1 there is no enough room for istio and argocd to get deployed. The idea behind having `desiredCapacity` to a higher number is that there will be enough room for doing these deployments and CA can shrink the cluster if there is no need for these additional nodes.

**Comment by hakman** [comment]
OK, thanks for explaining.

**Comment by rifelpet** [comment]
Wouldn't it be easier to set minSize to 2 so that istio and argocd can be deployed and deploy cluster-autoscaler? Perhaps I'm not understanding why in your situation you would still want minSize to be 1.

**Comment by jsonmp-k8** [comment]
There are some enterprise controls that wants all ASG minsize to  be set to 0 or 1 to save on the cloud cost and then scale the cluster based on the load. That prevents us from setting the minsize to a higher number.

**Comment by olemarkus** [comment]
If desired flag is set by kops, kops would reconcile that property every time you run `kops update cluster`. That is probably not what you want. It may be easier for you to just do a one-time change of the desired flag using e.g aws cli after the cluster has been created.

**Comment by jsonmp-k8** [comment]
`kops update cluster` should ignore the `desiredCapacity` flag, if it is not an ASG creation event. I am not sure how this can be done with KOPS. 
For example terraform has this feature `ignore_changes` which will ignore the desired capacity on any terraform updates other than the initial creation
```  
  lifecycle {
    ignore_changes = [
      "desired_capacity",
    ]

**Comment by olemarkus** [comment]
Kops can technically do the same by ignoring the flag when the ASG already exists. But it still sounds like a niche issue that is better solved outside of kops to me. Adding this may be very confusing for others that later on try to use this flag to adjust the desired node count on existing ASGs.

**Comment by jsonmp-k8** [comment]
I feel doing it outside seems like a hacky solution. We can do it from outside using AWS cli/ AWS console
