### ISSUE TITLE
Backport the backport

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1002]
Regarding private topologies, we are overriding the struct initiation in the `validation.go` file.. we need to get that out of there

CC @justinsb 

More info https://github.com/kubernetes/kops/pull/965

**Comment by chrislovecnm** [comment]
I am looking through issues to test against #1183

**Comment by chrislovecnm** [comment]
See https://github.com/kubernetes/kops/issues/1206 ~ The PR is in.  Who can test?
