### ISSUE TITLE
kops cluster using etcd2 mistakenly updated to etcd3, now down

### ISSUE THREAD

**Issue by schollii** [kubernetes/kops#10053]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

I initially just wanted to change the machine type of cluster nodes (not masters), using kops 1.13 on a kubernetes 1.11 cluster. Have not had issue doing this on a kubernetes 1.13 cluster. The cluster has 3 master nodes. However for some reason, kops wanted to update the master images from k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17 to k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-01-17 and I thought that should not be a problem. 

However after first master updated the usual way (kops update cluster, terraform apply, kops rolling-update), the master would not rejoin the cluster. Upon inspecting the etcd logs of the master, it seems to be trying to run etcd 3.2, whereas it appears that cluster was actually running etcd2. So I'm guessing this cluster was actually created pre-kops-1.11, maybe kops 1.10 or 1.9. 

So I'm thinking of installing older version of kops to see if I can get it back to etcd2, but what do you think is the best way to fix this? 

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

**3. What cloud provider are you using?**

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by schollii** [comment]
I was able to "update" back to the original kops cluster yaml and it now all works again.

**Comment by olemarkus** [comment]
FYI it looks like you hit the etc2 -> etcd3 upgrade. Make sure you read the release notes on how to proceed with that.
