### ISSUE TITLE
kubernetes version 1.18.9 and kops 1.18.1 kbcfg config is getting generated without user credentails

### ISSUE THREAD

**Issue by sacoefrancis** [kubernetes/kops#10071]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.18.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", ", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", , GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops export kubecfg --name "cluster.com" --state=s3://bucketname
**5. What happened after the commands executed?**
config file is getting created .kube path with user crdentials
**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: dstest.com
spec:
  api:
    loadBalancer:
      additionalSecurityGroups:
      - sg-0831943d05868d470
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://dstest/dstest.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: dev-master-0
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: dev-master-0
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesVersion: 1.18.9
  masterPublicName: api.dstest.com
  networkCIDR: 10.0.0.0/16
  networkID: vpc-0f2697482a161f800
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  - id: subnet-062e704412dab888a
    name: utility-ap-south-1a
    type: Utility
    zone: ap-south-1a
  - id: subnet-0bb1288bc5402e020
    name: utility-ap-south-1b
    type: Utility
    zone: ap-south-1b
  - id: subnet-042fe7d5469bb0687
    name: utility-ap-south-1c
    type: Utility
    zone: ap-south-1c
  - egress: nat-09026cb6854354418
    id: subnet-0cb46e33576953cb0
    name: ap-south-1a
    type: Private
    zone: ap-south-1a
  - egress: nat-09026cb6854354418
    id: subnet-0417608e32638a796
    name: ap-south-1b
    type: Private
    zone: ap-south-1b
  - egress: nat-09026cb6854354418
    id: subnet-0450db3d3b209c55c
    name: ap-south-1c
    type: Private
    zone: ap-south-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-10-18T13:35:55Z"
  labels:
    kops.k8s.io/cluster: dstest.com
  name: dev-master-0
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeType: gp2
  subnets:
  - ap-south-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-10-18T13:35:55Z"
  labels:
    kops.k8s.io/cluster: dstest.com
  name: dev-nodes-0
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  machineType: t3a.medium
  maxSize: 3
  minSize: 1
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  subnets:
  - ap-south-1a
  - ap-south-1b
  - ap-south-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-10-18T13:35:55Z"
  labels:
    kops.k8s.io/cluster: dstest.com
  name: dev-nodes-1
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  machineType: t3a.medium
  maxSize: 3
  minSize: 1
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  subnets:
  - ap-south-1a
  - ap-south-1b
  - ap-south-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-10-18T13:35:56Z"
  labels:
    kops.k8s.io/cluster: dstest.com
  name: dev-nodes-2
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  machineType: t3a.medium
  maxSize: 3
  minSize: 1
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  subnets:
  - ap-south-1a
  - ap-south-1b
  - ap-south-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-10-18T13:35:56Z"
  labels:
    kops.k8s.io/cluster: dstest.com
  name: dev-nodes-3
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  machineType: t3a.medium
  maxSize: 3
  minSize: 1
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  subnets:
  - ap-south-1a
  - ap-south-1b
  - ap-south-1c

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

  kops export kubecfg --name "dbtest.com" --state=s3://bucketname 
  kubectl config set-cluster "dbtest.com" --server=https://api.dbtest.com
**9. Anything else do we need to know?**
kubernetes version 1.18.9 and kops 1.18.1 kbcfg config is getting generated without user credentails, due to this we are hitting https://api.dbtest.com is throwing error

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

**Comment by sacoefrancis** [comment]
Above is  being fixed by  adding
spec:
  kubeAPIServer:
    disableBasicAuth: false

this is for kops version 1.18.1

**Comment by olemarkus** [comment]
Note that basic auth is completely removed in 1.19, so you need to move away from that if you are using it.
