### ISSUE TITLE
AWS - Never delete root volumes from instances

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1010]
Kops needs to have an ability to preserve root volumes for **all** instances deployed via kops.

**Comment by justinsb** [comment]
What does "preserve root volumes" mean?

**Comment by kris-nova** [comment]
Changed the title, basically we want to be able to tell kops "Please make sure AWS knows that we will be deleting our root volumes ourselves, and not to delete them when we destroy an instance"

**Comment by justinsb** [comment]
Still not sure I get it.  Is this so that you have a second chance at the data?

**Comment by chrislovecnm** [comment]
We should probably punt this to the next release.
