### ISSUE TITLE
include in Docker configuration a Runtime option

### ISSUE THREAD

**Issue by ikropotov** [kubernetes/kops#10127]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
I am working on having an alternative OCI runtime on the machines, and currently I can't configure it out of the box with `kops` so I would need to create an images with dockerd running with alternative runtime and skip docker installation on kops.

There is no runtime configuration for Docker:
https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#DockerConfig

And here is a reference to dockerd runtimes configuration:
https://docs.docker.com/engine/reference/commandline/dockerd/#docker-runtime-execution-options

**2. Feel free to provide a design supporting your feature request.**

**Comment by hakman** [comment]
Hi @ikropotov. Could you be more specific about what OCI runtime you want to use, what extra flags you would need and the use case or using something other than `runc` (I guess this is the piece that you are trying to replace)?

**Comment by ikropotov** [comment]
@hakman Yeah I am looking for a more isolated runtime to run DIND(docker-in-docker) and KIND(kubernetes-in-docker) without compromising nodes/hosts at scale, specifically https://github.com/nestybox/sysbox

**Comment by bharath-123** [comment]
Hi, I would like to pick this up.

**Comment by hakman** [comment]
@bharath-123 Thanks for taking this. At first glance, this would mean adding 2 new flags for Docker daemon:
```
      --add-runtime runtime                   Register an additional OCI compatible runtime (default [])
      --default-runtime string                Default OCI runtime for containers (default "runc")
```

Example of how to add these flags: https://github.com/kubernetes/kops/pull/7460/files.

**Comment by bharath-123** [comment]
Thanks for the suggestions!

**Comment by bharath-123** [comment]
@hakman hmm add-runtime seems a bit tricky.
`dockerd --add-runtime runc=runc --add-runtime custom=/usr/local/bin/my-runc-replacement`

I initially thought this would be a map[string][string] but map[string][string] would parse as --add-runtime=runc=runc, custom=/usr/local/bin/my-runc-replacement according to https://github.com/kubernetes/kops/blob/master/pkg/flagbuilder/build_flags.go#L99 

We could use repeatFlags but repeatFlags is only for []string options. I don't think passing the add-runtime configs as "runc=runc" for a string is good practice. Should we extend repeatFlags to support this?
