### ISSUE TITLE
Documentation: missing information on configuring NodeLocal DNSCache

### ISSUE THREAD

**Issue by azkore** [kubernetes/kops#10136]
The [current documentation on NodeLocal DNSCache](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#node-local-dns-cache) is missing a crucial part about changing clusterDNS to 169.254.20.10, which was present in the initial implementation, see [here](https://github.com/kubernetes/kops/pull/8780/files#diff-2983fab4084c9924c5b2b08ee707eb513c749db933e7b3481b8a746ddf033875R556) 

Without this change NodeLocal DNSCache doesn't work (at least with kuberouter as CNI), so I think it would be good to add additional clarifications

**Comment by olemarkus** [comment]
We recently released a change that will force clusterDNS to be 169.254.20.10 regardless of CNI. Do you experience the same problem on 1.18.2?

**Comment by azkore** [comment]
Thank you @olemarkus, I just tested 1.18.2 and I can confirm that the kubelet `--cluster-dns` option is now set correctly  automatically
