### ISSUE TITLE
Allow overriding image versions and repositories

### ISSUE THREAD

**Issue by lsowen** [kubernetes/kops#10148]
For various reasons, including the imminent introduction of pull limits for Docker hub (https://docs.docker.com/docker-hub/download-rate-limit/), it can be useful to be able to override the version and location for various components, including:

* Node local DNS: https://github.com/kubernetes/kops/blob/999ae2593236372c72faca7b33d33b0d8ed13585/upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template#L143
* Cilium: https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template#L446

**Comment by olemarkus** [comment]
For the docker hub rate limit case, I suggest using a docker hub mirror. See https://kops.sigs.k8s.io/cluster_spec/#registrymirrors

**Comment by lsowen** [comment]
Good suggestion, and not something I was aware of.  Unfortunately, doesn't work in my case, because the image names are changed when "vendored" to our private repo.

**Comment by olemarkus** [comment]
You can have a look at this one as well then https://kops.sigs.k8s.io/cluster_spec/#containerregistry (and the proxy below). That may fit more your use case.

**Comment by d-m** [comment]
> You can have a look at this one as well then https://kops.sigs.k8s.io/cluster_spec/#containerregistry (and the proxy below). That may fit more your use case.

@olemarkus My org proxies each approved Docker repository via Artifactory to different URLs (dockerhub -> dockerhub.my-internal-repo.local, k8s.gcr.io -> k8s-gcr-io.my-internal.repo.local, etc). I looked at using the `containerRegistry` but it seems to map all images, regardless of original repo, to the one `containerRegistry` value. Do you have any suggestions for how we would be able to proxy images used for kops to different internal repos based on their original repo?

**Comment by olemarkus** [comment]
At the moment there is no such feature. But https://github.com/kubernetes/kops/pull/10204#issuecomment-727754299 does suggest a feature that may be used to map arbitrary images to arbitrary repositories in the future.
