### ISSUE TITLE
Allow Calico to use VXLAN backend (instead of BIRD)

### ISSUE THREAD

**Issue by seh** [kubernetes/kops#10168]
Calico—in particular, its "calico-node" daemon—has a configurable "networking backend" that accepts one of three values:
- _bird_  
  Run the BIRD BGP daemon, for use with IP-in-IP or VXLAN encapsulation.
- _vxlan_  
  Disable BIRD, and allow use of VXLAN encapsulation.
- _none_  
  Disable BIRD, and use Calico only for network policy enforcement.

We can specify this value via [the "calico_backend" field in the "calico-node" _ConfigMap_](https://docs.projectcalico.org/getting-started/kubernetes/installation/config-options#other-configuration-options) or [the "CALICO_NETWORKING_BACKEND" environment variable](https://docs.projectcalico.org/reference/node/configuration#other-environment-variables).

At present, _kops_ forces Calico to use the BIRD backend unconditionally. When using only VXLAN encapsulation in our IP pools, though, we don't need BGP, and so we don't need BIRD. It would be helpful if we could customize Calico via the _Cluster_ manifest's "networking.calico" field to designate use of the VXLAN backend instead. _kops_ would then need to amend the "calico-node" _DaemonSet_ manifest to [remove the `-bird-live` and `-bird-ready` command-line flags from the "calico-node" pod's liveness and readiness probes](https://docs.projectcalico.org/getting-started/kubernetes/installation/config-options#switching-from-ip-in-ip-to-vxlan), respectively.

Note that I tried using _kubectl patch_ to adjust this configuration myself in a _kops_-managed cluster. While that works to a point, it's a fragile arrangement; any subsequent invocation of _kops update cluster_ will apply _kops_'s manifests again, updating the Calico configuration back to using the BIRD backend.

**Comment by seh** [comment]
See the following Slack threads for background:
- ["kops-users" channel](https://kubernetes.slack.com/archives/C3QUFP0QM/p1604460525290400) in the "Kubernetes" workspace
- ["networking" channel](https://calicousers.slack.com/archives/CPEPF833L/p1604348149472500) in the "Calico Users" Slack workspace
- ["kubernetes" channel](https://calicousers.slack.com/archives/C0BCA117T/p1604458813203100) in the "Calico Users" Slack workspace

**Comment by seh** [comment]
@hakman, would you entertain a patch for this? I've reviewed the current code, and I don't think this looks like much of an intrusion.

We could introduce a field for Calico such as "backend," and use "bird" as the default value. We'd validate that a present value is either "bird" or "vxlan." Calico also accepts "none" as a value, but I'm not sure that we should try to allow using Calico in policy-only mode.

In "vxlan" mode there's no need to allow BGP traffic (UDP port 179) between nodes, but the security rules are already so liberal that they don't address BGP specifically now.

**Comment by hakman** [comment]
@seh That would be nice. I don't mind at all adding a new backend field, which should default to "bird" if not set.

**Comment by seh** [comment]
I implemented most of this, but got stuck on how to handle the existing [`CalicoNetworkingSpec.IPIPMode` field](https://github.com/kubernetes/kops/blob/84495481e4e1f8adb7774c3101ee5a5740479518/pkg/apis/kops/networking.go#L127-L128).

If someone sets the new `CalicoNetworkingSpec.Backend` field to "vxlan," then they can't use IP-in-IP encapsulation, so setting a value for `IPIPMode` to anything but "Never" should be invalid. However, if we're not going to set up the default IP pool to use IP-in-IP encapsulation, we should instead set it up to use VXLAN, but we have no `VXLANMode` field in `CalicoNetworkingSpec`.

I'm trying to update this portion of the _DaemonSet_ manifest:
https://github.com/kubernetes/kops/blob/0f9c0c03efdd43e8096598c6f04b4947e3044d82/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template#L3866-L3871

I'd like to take `CrossSubnet` and `Backend` into account to set up the default IP pool to use either IP-in-IP or VXLAN encapsulation. If `Backend` is "vxlan," then the "CALICO_IPV4POOL_VXLAN" environment variable's value should be either "CrossSubnet" or "Always." Conversely, if `Backend` is "bird," then the "CALICO_IPV4POOL_IPIP" environment variable's value should be either "CrossSubnet" or "Always," even though it's possible with the BIRD backend to use VXLAN as well.

How do you think I should proceed here?

**Comment by seh** [comment]
See #10404 for my implementation of this idea.
