### ISSUE TITLE
kops 1.18.2 with spotinst elastic groups: Instance group stuck in "NeedsUpdate"

### ISSUE THREAD

**Issue by MeirP-3** [kubernetes/kops#10166]
*Kops version 1.18.2 (git-84495481e4)*

*Kubernetes version 1.14.2*

*Cloud provider: aws*

*Using "+Spotinst" feature flag*

**Behavior**
`kops rolling-update cluster --instance-group nodes`
kops reported 0 ready, 10 needupdate
`kops rolling-update cluster --instance-group nodes --yes`
Kops reported rolling update is completed
`kops rolling-update cluster --instance-group nodes`
kops reported 0 ready, 10 needupdate

**Relevant parts from verbose logging:**
```
Attempting to fetch all instances of instance group: "nodes.***.****.com" (id: "sig-*******")
<spotinst request/response details>
```
This line repeats 10 times
```
Adding instance "i-*****************" (created at: ...) to instance group: "nodes.****.***.com"
```
| NAME	 | STATUS		| NEEDUPDATE	| READY	| MIN	| TARGET	| MAX	| NODES |
| ----------- | ------------------------- | ---------------------- | ------------- | ----------- | ---------------- | ----------- | ----------- |
| nodes	| NeedsUpdate | 10	| 0 | 0 | 0	| 17	| 10 |

**Comment by hakman** [comment]
@MeirP-3 please attach a full log, with -v10 and a cluster spec that can be used to reproduce this. Thanks!

**Comment by MeirP-3** [comment]
[Link to cluster spec](https://gist.github.com/MeirP-3/006b9975cef1f8d548f9eab08b8ecc50)
[log of rolling-update without --yes](https://gist.github.com/MeirP-3/11e8c32408c10ab9c0b29109d27f31df)
[log of rolling update process](https://gist.github.com/MeirP-3/f91ca9d5f382ecff1c2c327c9f4ddf01)
[log rolling-update without --yes, after the rolling update succeeded](https://gist.github.com/MeirP-3/1291e826875e272f79601e17d9a6a567)

**Comment by MeirP-3** [comment]
Do anyone knows somthing about this?
