### ISSUE TITLE
Implement libopenssh into kops for SSH functionality and validation

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1016]
# SSH Security and stability in kops

Right now kops uses SSH conventions, but there is nothing in place to validate the actual SSH suite is behaving as it should. 

For instance, kops could find a (presumed) key in `~/.ssh/id_rsa`and will use that to create a cluster. We have ran into issues with the `ssh-agent` daemon having no concept of the key, and kops still creating the cluster. This causes problems downstream https://github.com/kubernetes/kops/issues/981 https://github.com/kubernetes/kops/pull/1015

# OpenSSH

Being that SSH is a critical component of kops security, I would like to give it a little more respect. I propose we implement the OpenSSH library [libopenssh](https://github.com/openssh/libopenssh) directly into kops via a new go package. This package could live in this repository, or another. The new package would provide an interface for kops to interact with good ol` OpenSSH directly.

# Features

Support for SSH alias 
Agent validation 
Key validation 

# Notes

I was raised on C, and am happy to code this in if we think this is something we could use. 

# Caution

 - OpenSSH moves quickly, and requires constant updating for latest patches. We need to make sure we don't implement security features with a stale/static package
 - This introduces a lot more overhead in the make process, dependencies, CGO, etc

**Comment by justinsb** [comment]
There is a pretty good SSH package in the `x` library: https://godoc.org/golang.org/x/crypto/ssh

I think we even use it, or used to...  grep through the commented out code!

**Comment by kris-nova** [comment]
Ah - I didn't realize the library was this mature, looks like there is an `agent` derivative! Which is just what we need https://godoc.org/golang.org/x/crypto/ssh/agent, okay moving this to a normal issue. Thanks
