### ISSUE TITLE
Is there a way to set the node-image once the cluster is created?

### ISSUE THREAD

**Issue by sharoncr1** [kubernetes/kops#10177]
While creating a cluster, kops gives us a set of arguments to configure the images to be used for the master instances and the node instances like the following as mentioned in the kops documentation for create cluster command : 
[](https://github.com/kubernetes/kops/blob/master/docs/cli/kops_create_cluster.md)

`--image string                     Set image for all instances.
--master-image string              Set image for masters. Takes precedence over --image
--node-image string                Set image for nodes. Takes precedence over --image`

Suppose I forgot to add these parameters when I created the cluster, how can I edit the cluster and update these things?

While running kops edit cluster the cluster configuration opens up as a yaml.. but where should I add these things in there?

Or is it somewhere else that I can modify it?

kops version I am using : Version 1.15.0 (git-9992b4055)

**Comment by olemarkus** [comment]
run `kops get <cluster name> -o yaml > cluster.yaml` edit it there, then run `kops replace -f cluster.yaml`

**Comment by sharoncr1** [comment]
@olemarkus Thanks a lot.. it's kinda solution when compared to the thing I was doing earlier... 

I can do a search and replace in a single place instead of going to each instance group definition separately using `kops edit ig ig_name`

But my actual question I had was, whether we have a way to modify it in the cluster level so the change is in only one line and we can override if wanted in the instancegroup definitions.

Anyway, having received a cool solution to my problem, I am closing it..
