### ISSUE TITLE
Kops upgrade 1.17.x to 1.18.x dry run diff shows wrong version numbers

### ISSUE THREAD

**Issue by kciredor** [kubernetes/kops#10174]
Upgrading a cluster with kops 1.17.2 to 1.18.2 and setting the target kubernetes version (kops edit cluster) to 1.18.9, the end result will be a cluster running kubernetes 1.18.9. That's good.

But the initial dry run of kops update cluster shows a diff which claims images like api-server will be set to 1.18.2, which is false, they end up being the targeted 1.18.9.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Upgrading from 1.17.2 to 1.18.2.

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.17.9 to 1.18.9

**3. What cloud provider are you using?**
OpenStack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update cluster

**5. What happened after the commands executed?**
The diff shows an image (e.g. kube-apiserver) being image version bumped from 1.17.9 to 1.18.2. In the end it will run 1.18.9 which is good, it matches the targeted kubernetesVersion in kops edit cluster.

**6. What did you expect to happen?**
The diff should reflect the targeted kubernetesVersion so it should say 1.17.9 to 1.18.9.

**Comment by olemarkus** [comment]
Are you sure you are not mixing kops components (protokube, dns-controller) with the k8s ones? The kops components should be the same as the kops version, which I suspect is is kops 1.18.2

**Comment by kciredor** [comment]
Thanks, you are correct. Got a hint from my colleague which reminded me to create this issue. But I verified again by upgrading a cluster and it's the apiserver health check, not the apiserver itself being bumped to 1.18.2.

Closing this one!
