### ISSUE TITLE
Identify associated instance group for all validation error during cluster validation

### ISSUE THREAD

**Issue by bharath-123** [kubernetes/kops#10183]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
In validate_cluster, ValidationError describes any sort of failures that have occured during cluster validation. A recent PR was merged where we don't wait on rolling update due to validation errors in an unrelated instance group. This feature requires us to know the instance group of the validation error. 

Currently, it is not a straightforward task to know the instance group in which certain failures occur. Work would need to be done to identify the instance groups for the remaining validation errors in validate_cluster.

**2. Feel free to provide a design supporting your feature request.**

Would need to explore the code more myself to see if there are any cases where a mapping of Nodes to Instancegroup is already being done. and also pods to instance group.

**Comment by bharath-123** [comment]
@johngmyers @hakman @justinsb Any suggestions or ideas which I can use here will be super helpful.

**Comment by johngmyers** [comment]
`validateNodes` could construct and return a map of nodes to groups. `collectPodFailures` already constructs a map of IP address to node, so it could then use that map of nodes to groups to go from pod to group.
