### ISSUE TITLE
Reduce boilerplate in AWS LaunchTemplate

### ISSUE THREAD

**Issue by djablonski-moia** [kubernetes/kops#10202]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

In Kops 1.19.0-alpha.5, we can't start a new cluster anymore because of the size limitation of user data in AWS launch templates, which is 16k. We have approximately 3k of our own user data, and for the master nodes, deployment fails with

```
error running task "LaunchTemplate/master-eu-central-1b.masters.cluster.<domain>" (26s remaining to succeed): error creating LaunchTemplate: InvalidUserData.Malformed: User data is limited to 16384 bytes.
```

Looking into the Launch templates for the non-master instance groups, I see that Kops own part already takes up 10k for them, and most likely even more than 13k for masters, since our own user data is the same for them.

I'd like to see the boilerplate in the user data being reduces as much as possible, leaving more space for custom user data. For example, just the license header in the embedded `nodeup.sh` is taking up 607 bytes.
Additionally, the documentation should warn about the limited space for custom user data, so users can mitigate before running into this issue.

**2. Feel free to provide a design supporting your feature request.**

E.g. remove the license header from the embedded `nodeup.sh` script, and also other comments, unccessary blank lines etc.

**Comment by djablonski-moia** [comment]
After removing most of our custom user data, I can confirm that Kops already uses up 15k of the user data on master nodes! 😳

**Comment by olemarkus** [comment]
The typical master user data should be around 12-13k. But since user data contains the cluster spec and the spec also contains additionalUserData, 3k will result in 6k added data.

3k of additional user data is quite sizeable though. Maybe some of this could be moved to a hook instead?

**Comment by djablonski-moia** [comment]
@olemarkus Sorry, I was talking about just the userData in the cluster spec, there is no duplication of our userData I can see (after reducing it significantly). But our list of `fileAssets` is also adding 1.5k.
I'll try to reduce our userData and fileAssets as much as possible by shifting stuff into the AMI, but I still think the Kops part should also be minimized.

**Comment by DOboznyi** [comment]
We also can't update kops in clusters from 1.18 to 1.19 because of file assets. Can it be decreased?

**Comment by Nilubkal** [comment]
We are experiencing the same issues trying to create a new cluster via `kops-1.21-alpha-3`.

**Comment by d-m** [comment]
I'm also running into this updating a cluster from 1.19 to 1.20

**Comment by Nilubkal** [comment]
> We are experiencing the same issues trying to create a new cluster via `kops-1.21-alpha-3`.

just applying exactly the same template ( the same size/length ) with `kops-1.20.0` and `KOPS_RUN_TOO_NEW_VERSION=1` creates a `kubernetes 1.21.0` cluster without any complains about "User data is limited to 16384 bytes"

**Comment by Nilubkal** [comment]
Another workaround is using the setting for the `InstanceGroup`: 
```YAML
spec:
  compressUserData: true
```
introduced by this [PR](https://github.com/kubernetes/kops/pull/10357)

**Comment by olemarkus** [comment]
This isn't a workaround. This is the solution for those who depend on extending the user data.
Often, hooks is a better mechanism for manipulating the instance during boot. But it depends on what you are putting into user data.
