### ISSUE TITLE
Generated Terraform should be a module so it integrates better with external Terraform projects

### ISSUE THREAD

**Issue by chriskilding** [kubernetes/kops#1026]
Hello

We have a requirement to merge any TF scripts generated by kops (or any tool for that matter) into an external Terraform Amazon account provisioning project. Essentially no individual tool we deploy is allowed to 'plough its own furrow' - it needs to be managed from our external Terraform project.

With that in mind it would be much easier to integrate the kops-generated TF scripts if they met the following conditions:

- They were a TF *module* rather than an entrypoint script, so they could be included with TF's module syntax from our external main.tf.
- They exposed certain key variables in the module definition so we can pass the Kubernetes module variables which we have already defined in our tfvars, eg Amazon VPC IDs, rather than redefining them through kops + generated Kubernetes TF.

To maintain compatibility for users of the current Terraform workflow, a very minimal main.tf could be generated which just invokes the module.

**Comment by chrislovecnm** [comment]
We are happy to take on contributions! We can asses refactoring. Thanks

**Comment by kris-nova** [comment]
This could be a use case for the terraform path described in https://github.com/kubernetes/kops/issues/1055

**Comment by justinsb** [comment]
So I did this...

I generated two clusters (in two different regions) with two different terraform directories.  I then created "parent" terraform module references to bind them into one terraform "world" (not sure what the correct terminology is)


```
kops create cluster useast1.example.com --zones us-east-1c --networking kopeio-vxlan --target terraform --out=out/terraform/useast1.example.com
kops create cluster uswest2.example.com --zones us-west-2b --networking weave --target terraform --out=out/terraform/uswest2.example.com
```

`out/terraform/useast1.example.com.tf`
```
module "useast1" {
  source  = "./useast1.example.com"
}
```


`out/terraform/uswest2.example.com.tf`
```
module "uswest2" {
  source  = "./uswest2.example.com"
}
```

Once I terraform plan & terraform apply, it works.

Each one does have a minimal aws block that defines the region.  I don't know of an alternative.

So I guess the remaining request is that we are able to tweak certain variables, so that we could create a template and then instantiate it multiple times.  TBH the intent was that we would drive this through kops (is there anything we can do in kops to make this better?).  We do want to make this possible though, but it's likely blocked on e.g. generating keys as part of terraform apply.  There was an interesting suggestion to call-out from terraform to kops, which is a possibility.

**Comment by FutureSharks** [comment]
I made a terraform module for use with kops:
https://github.com/FutureSharks/tf-kops-cluster
It should make it easier to run multiple clusters in a single VPC and also just make the code a bit more manageable :slightly_smiling_face:

**Comment by chrislovecnm** [comment]
@FutureSharks looks awesome.  With some work I am doing with phases I need to make some tweaks to the TF.  Here is my first stab at breaking up the tf https://github.com/kubernetes/kops/tree/master/tests/integration/update_cluster/lifecycle_phases

1. we need to have the outputs in the phases that own the output
2. we need to have defaults.tf with the duplicated TF such as cluster name

Any other recommendations?

**Comment by FutureSharks** [comment]
@chrislovecnm looks good.

Is this just for an integration test? Or would it later be copied for general use by kops? You're not passing any data into the module so its use as a module is limited but I guess for a test you want everything hardcoded?

**Comment by gobengo** [comment]
Folks interested in this should have a look at the tf module in https://github.com/poseidon/typhoon

**Comment by max-rocket-internet** [comment]
@gobengo looks interesting but I don't think project is designed to be used in a live environment?
For example they are using `aws_instance` resource:
https://github.com/poseidon/typhoon/blob/master/aws/container-linux/kubernetes/controllers.tf#L17

Instances that exist outside of ASGs will not be replaced automatically so can't really be considered resilient.

**Comment by dghubble** [comment]
@max-rocket-internet I'm biased (author), but don't think that's a fair conclusion. Typhoon is explicitly [for real](https://typhoon.psdn.io/) environments. Controller ASGs were used in the past, but we've switched to instances as part of moving away from self-hosted etcd (i.e. atop k8s) and collocating etcd's across controllers (trades heterogeneity/statefulness for cost savings). For stateful nodes, ASGs can be a liability and we've favored individual replacement/repair. https://github.com/poseidon/typhoon/pull/53

Anyway, I don't wanna inject design discussion here, just couldn't leave that unanswered. Let's agree distros have reasons for their decisions.

**Comment by 007** [comment]
@chrislovecnm @kris-nova @justinsb This ticket has been open for more than 2 years as a `P1` and is tagged for a milestone closed a year and a half ago - can someone triage this properly and/or close it? #1055 closed with nary a comment, so it seems that the community doesn't care to change how this works.
