### ISSUE TITLE
Clusters created with k8s v1.20 don't start

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#10279]
e2e tests for k8s v1.20 fail to start:
https://testgrid.k8s.io/kops-versions#kops-aws-k8s-latest

Me and @rifelpet tracked this to https://github.com/kubernetes/kubernetes/pull/95896, which introduces some new mandatory flags:
```
TokenRequest and TokenRequestProjection are now GA features. The following flags are required by the API server:
- `--service-account-issuer`, should be set to a URL identifying the API server that will be stable over the cluster lifetime.
- `--service-account-key-file`, set to one or more files containing one or more public keys used to verify tokens.
- `--service-account-signing-key-file`, set to a file containing a private key to use to sign service account tokens. Can be the same file given to `kube-controller-manager` with `--service-account-private-key-file`.
```

/cc @justinsb @johngmyers @olemarkus

**Comment by johngmyers** [comment]
kube-apiserver is crashlooping. The log is not terribly informative:

https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-k8s-latest/1334602405844619264/artifacts/46.51.235.194/kube-apiserver.log

/reopen

**Comment by johngmyers** [comment]
Oh, it hasn't run since the merge.

**Comment by johngmyers** [comment]
The testgrid summary says it's passing, but the details don't show the new runs.
/close
