### ISSUE TITLE
Support new AWS instance types

### ISSUE THREAD

**Issue by fedenusy** [kubernetes/kops#1027]
AWS recently released T2 and R4 instances.

kops currently fails to provision these new instance types -- for example, editing an instance group to use `r4.2xlarge` fails with the following error:

```
W1201 10:38:32.232140   15970 executor.go:84] error running task "launchConfiguration/igname.clustername": instance type not handled: "r4.2xlarge"
```

I'd love to start using these new machines, especially the R4s since they're significantly cheaper than R3s.

**Comment by chrislovecnm** [comment]
R4 OMG ... what are you going to do with 400 GB of ram.  SGTM.

It is a super easy code fix.  You code in go?

**Comment by fedenusy** [comment]
Not yet, but now that I'm using k8s I should probably learn. Will run through tutorials this weekend.

**Comment by razic** [comment]
i fixed this here https://github.com/kubernetes/kops/pull/1029

**Comment by chrislovecnm** [comment]
@fedenusy can u test ... r4.16xlarge right ;) Just kidding, but if u could validate and then close that would be awesome!

**Comment by fedenusy** [comment]
Sure, I'll try it out tomorrow morning!

**Comment by fedenusy** [comment]
👍  works! Thank you @razic @chrislovecnm 

Advise for anyone else switching to R4s: make sure the new instance type is available in your zone(s). For me, r4.2xlarge failed to provision in us-east-1c, so I had to switch to us-east-1b.
