### ISSUE TITLE
Further improvements to private topology when bastion will not be needed

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#1030]
This builds on [PR906](https://github.com/kubernetes/kops/pull/906) once it has been finalized and merged. This issue concerns kube-clusters that are generated via kops with private topology and the bastion infrastructure created. #906 introduces new configuration options for the bastion server  `--bastion=true`  and `--bastion=false` . In general, both options create the same infrastructure as the original private topology code, but `false` sets the size of the bastion ASG to 0. 

**Problem:**
In certain use cases, we can be sure that the bastion server(s) will not be needed or used- for example where we intend to configure VPN access to the cluster after kops-installation. 

Scaling the bastion group to 0 is a start, but the ELB is permanent regardless of whether the bastion is turned on or off and this ELB has a cost associated with it. 

**Proposal:** 
I would like to code a complete "opt-out" for bastion support.  I propose that we maintain the functionality from #906 and create additional functionality to address our case where the bastion is never used. Setting this flag would skip ALL bastion related allocations.
I really like @kris-nova’s [Plan B](https://github.com/kubernetes/kops/pull/906#issuecomment-264214092).  

> Plan B
> --bastion=N
> Create the underlying bastion infrastructure, and set the ASG=N
> Where `N` > `-1` 
> --bastion=-1
> Create no bastion, and no underlying infrastructure 

It allows us to preserve useful existing functionality while extending the tool for our case. I personally prefer the semantics of Plan B to Plan A because then the bastion flag would always take an integer value. Then we could do something like create aliases for  `--bastion=true` to `--bastion=1` and `--bastion=false` to `--bastion=0` .

**Comment by chrislovecnm** [comment]
How about the capability to create a dynamic bastion?  Only have it up as needed :)

**Comment by kris-nova** [comment]
@geojaz this sounds like a great starting point to the feature.

@chrislovecnm I think the features support having the bastion turned from `0` -> `1+` which to me sounds like a dynamic bastion..?

**Comment by geojaz** [comment]
It looks like #906 provides everything I need for turning the bastion off. I've been experimenting with this over the weekend in a number of different configurations. And other than the very minor Launch Configuration deletion issue in #1051, this looks great! Thanks for all your hard work getting this one done!

I'm happy to close this issue for now.
