### ISSUE TITLE
Restore the advisory workaround in etcd-manager-certificate-expiration.md for cert renewal

### ISSUE THREAD

**Issue by schollii** [kubernetes/kops#10314]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.13

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

n/a

**5. What happened?**

Nodes started appearing as unhealthy. Investigation eventually led to kops advisory about etcd certs not being automatically renewed. This advisory at https://github.com/kubernetes/kops/blob/9283f4c778f5206c816346675fb6e4ab8502fd8b/docs/advisories/etcd-manager-certificate-expiration.md had 2 solutions: upgrade kops or renew the certs. Upgrading was not possible for us so we renewed. Same thing happened on another cluster and this time when I went to the advisory, the instructions were gone. Please be careful, there are serious consequences to removing such important workarounds. The workaround is not wrong, it's possibly just one you would rather not encourage that's understandable but not every cluster can be upgraded. 

**6. What did you expect to happen?**

The advisory should have an additional warning about kops version deprecation or whatever led to the decision to remove the cert renewal workaround. Thank god we had found that workaround prior to Oct 25!

**Comment by olemarkus** [comment]
The workaround was removed because it frequently led to broken clusters. So we don't want to lead people down that path anymore.
This issue is also fixed on supported versions of kOps so those who are affected by this need to upgrade anyway.

/close
