### ISSUE TITLE
Undrain after Drain/Uncordon

### ISSUE THREAD

**Issue by vinnie-kaboom** [kubernetes/kops#10313]
Is there some thing similar to an undrain in Kubernetes. In other words, after you go through the process of a drain and cordon of the node. Then after maintenance is done, uncordon and **drainback**, meaning all pods that were evicted from the node returns to the node where it was drained from; so the nodes drained won't remain empty.

**Comment by johngmyers** [comment]
In Kubernetes you can uncordon a node, but draining results in the pods being deleted. There's no concept of undeleting a pod.

In any case, this is not a kops issue.
