### ISSUE TITLE
CentOS 8: as base dist

### ISSUE THREAD

**Issue by sergey-safarov** [kubernetes/kops#10327]
could you add CenOS8 support for AWS installation?
Base AMI now [available](https://aws.amazon.com/marketplace/pp/B08KYLN2CG?qid=1606550294161&sr=0-6&ref_=srh_res_product_title#pdp-pricing).

**Comment by sergey-safarov** [comment]
Also available images from CentOS
You can check the output of the command:
```
aws ec2 describe-images \
--region us-east-1 \
--output table \
--owners 679593333241 \
--query "sort_by(Images, &CreationDate)[*].[CreationDate,Name,ImageId]" \
--filters "Name=name,Values=CentOS-8.*x86_64*"
```

**Comment by hakman** [comment]
Very good news. Thanks @sergey-safarov!
/assign
