### ISSUE TITLE
[Question] Docker proxy fallback

### ISSUE THREAD

**Issue by dene14** [kubernetes/kops#10325]
Is there a recommended way to use 2nd docker proxy as a fallback?

What I'm willing to do is to have NexusRM caching proxy clustered across multiple K8S clusters, each cluster should normally use cluster.local mirror, but in case it's down (or more likely not running yet) it use internet mirror (most likely another NexusRM in the ensemble but in another cluster).

I've seen #5475, but it wasn't merged and there some concerns from people.

Thanks in advance!

**Comment by olemarkus** [comment]
Is this what you were looking for?
https://kops.sigs.k8s.io/cluster_spec/#registry-mirrors
