### ISSUE TITLE
[Docs] Metric-server deployment

### ISSUE THREAD

**Issue by sachincool** [kubernetes/kops#10331]
**1. Add supporting docs for [metric-server](https://github.com/kubernetes-sigs/metrics-server) deployment in kops docs**
**2. [this comment](https://github.com/kubernetes-sigs/metrics-server/issues/212#issuecomment-459321884) Really helped me, I spent a long time searching why my kops nodes gave API-auth fails or even IP missing in SAN's of certificate**

**Comment by olemarkus** [comment]
As of kops 1.19 (currently in beta), metrics server can be installed as an addon by setting `spec.metricsServer.enabled: true`. The correct flags will then be passed on.

If you want to install through other means, the docs should be added there, I think.

**Comment by sachincool** [comment]
@olemarkus Great to know! makes things easier. saw https://github.com/kubernetes/kops/pull/10022 Thanks for your hard work!  🔥 ⭐ 😄
