### ISSUE TITLE
Support new gp3 ebs volume type on AWS

### ISSUE THREAD

**Issue by MichaelJDrK** [kubernetes/kops#10349]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

AWS launched a new ebs volume type "gp3": https://aws.amazon.com/blogs/aws/new-amazon-ebs-gp3-volume-lets-you-provision-performance-separate-from-capacity-and-offers-20-lower-price/

When adding a "rootVolumeType: gp3" to the InstanceGroup, "kops update" fails:

W1202 17:17:08.384141   45347 executor.go:128] error running task "LaunchConfiguration/<edited>.de" (9m57s remaining to succeed): error creating AutoscalingLaunchConfiguration: ValidationError: gp3 is invalid. Valid volume types are standard, io1, gp2, st1 and sc1.

**2. Feel free to provide a design supporting your feature request.**

"rootVolumeType: gp3"
should be valid, additional to the currently supported types. 

Since gp3 looks like a direct upgrade to gp3 at lower costs, it could be considered to use "gp3" as the new default instead of "gp2"

**Comment by olemarkus** [comment]
#10345 already takes care of adding gp3 to supported types.

gp3 may indeed become default in kops 1.20.

**Comment by MichaelJDrK** [comment]
Oh nice, thanks!
