### ISSUE TITLE
protokube --channels with local file is confusing

### ISSUE THREAD

**Issue by pmahoney** [kubernetes/kops#1035]
I'm running protokube and would like to add a local file as a channel.

By reading the code, my teammate and I discovered that passing a channel as `--f=/path/to-file` does work. Full commandline: `protokube --channels=s3://path/to/s3,--f=/path/to/file`

However, this is non-obvious and undocumented. I would have expected (and tried) either of the following to also work: `/path/to/file`, `file:///path/to/file`

**Comment by kris-nova** [comment]
@pmahoney would you like to add a note in the documentation about this? We would love help on getting it documented.

**Comment by justinsb** [comment]
The channels tool is definitely something I need to circle back on when we get kops 1.5 out the door - been delayed by some of the k8s 1.5 surprises.   I agree that one or both of the syntaxes you have should work.  The `--f` is a very clever but evil hack, so I'd rather we didn't document it, but hopefully it's good enough until we have a chance to get back to it.

I think the `file:///` handling would just need to be added in VFSContext, if you're so inclined.

**Comment by justinsb** [comment]
Partially addressed in https://github.com/kubernetes/kops/pull/1633

**Comment by chrislovecnm** [comment]
Closing as we have addon manager issues
