### ISSUE TITLE
Docker should not be the default runtime

### ISSUE THREAD

**Issue by AngerM-DD** [kubernetes/kops#10356]
With k8s 1.20 Docker support as the CRI is being deprecated. The default should probably be changed to containerd and a warning placed for users creating clusters with docker that it will not be supported in the future.

see: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#deprecation

**Comment by hakman** [comment]
Thanks for the news. We will discuss how to notify the users and switch to containerd by default in the near future.
