### ISSUE TITLE
Use systemd as the cgroup driver for kubelet and CRI

### ISSUE THREAD

**Issue by bharath-123** [kubernetes/kops#10372]
Currently in kops, kubelet and the container runtimes use cgroupfs driver as the cgroup-manager. Kubernetes recommends using systemd as the default cgroup-manager for kubelet and the container runtimes. Some projects like kubeadm and minikube have moved to set systemd as the default cgroup-driver.

https://kubernetes.io/docs/setup/production-environment/container-runtimes/

https://github.com/kubernetes/minikube/pull/6651
https://github.com/freenas/freenas/pull/5263
https://github.com/kubernetes/kubernetes/pull/73837

**Comment by bharath-123** [comment]
Was having a discussion with @bmelbourne on this referring to PR [9879](https://github.com/kubernetes/kops/pull/9879). It seems like there was a consensus that moving to systemd cgroup driver would be a big breaking change for users. 

I do agree that this can be a breaking change. Defaulting to systemd for kubelet and container runtimes is pretty straightforward, we only have to set a couple of default options nothing too much. 

@hakman @olemarkus @bmelbourne would love to know your thoughts on this.

**Comment by olemarkus** [comment]
One can already set systemd as driver for kubelet, right? So what is missing is setting the appropriate driver for containerd.
For me that sounds straightforward enough.

I am not sure what the breaking change would be. From what I can tell, there are mostly benefits from this change.

Compared to the change done for docker, I would really like to see some validation logic ensuring that the containerd and kubelet config match.

**Comment by hakman** [comment]
I would like to not have so much logic for a setting that most people won't notice or change. Defaulting to this for 1.20+ should be ok. Validating the kubelet and container runtime match seems overkill to me. Documentation should be good enough.
Don't remember the discussion about the breaking changes, but may be related to old Debian image.

**Comment by hakman** [comment]
Had a more detailed discussion with @olemarkus and agreed on to do here:
1. doc explaining how to set the cgroup driver and that needs to be done in both k8s and cri
2. doc note for contained configOverride that using it has to be done with care, as the default config may change between releases and can lead to incompatibilities
3. print a warning when configOverride is used that the cluster is using non default containerd config
4. set default to systemd only for k8s >= 1.20 for kubelet, docker and containerd

**Comment by bharath-123** [comment]
alright got these points. Will raise a PR with code keeping all of these in mind. Thanks!

**Comment by hakman** [comment]
Thanks also for doing this.

**Comment by hakman** [comment]
@bmelbourne from what I know, kOps just replaces each node, so should not matter much. There won's be any mismatch between kubelet and runtime on any one the nodes, even if some will use cgroupfs or and others systemd.

**Comment by bmelbourne** [comment]
> @bmelbourne from what I know, kOps just replaces each node, so should not matter much. There won's be any mismatch between kubelet and runtime on any one the nodes, even if some will use cgroupfs or and others systemd.

That's good to know. I'll be happy to test whatever the final solution might be once the PR has been raised.

**Comment by hakman** [comment]
And I will be happy to review it 😁

**Comment by bharath-123** [comment]
Working on it. Ran into a bunch of issues with nodeup and containerd configs. mostly resolved now :)
