### ISSUE TITLE
kops should record history of cluster config

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#1037]
`kops edit <blah>` mutates the state of things within $KOPS_STATE_STORE.

Kops should keep a record of the changes made within $KOPS_STATE_STORE s3 bucket.

Proposal: for any cluster directory, make a second level 'history' directory.  Any time a change is made to cluster.spec, or instancegroup/*, a copy of the previous version, named with a date/time stamp should be cloned over to history/cluster.spec.<timestamp> or history/instancegroup/nodes.<timestamp>.

technically, enabling s3 bucket versioning would give you the same net effect, but having something more discoverable might be preferred.

This might also give kops a rollback feature which could be useful as well.

**Comment by chrislovecnm** [comment]
@zapman449 interesting idea, we are always happy to accept PRs

**Comment by kris-nova** [comment]
This is another huge use case for versioning IMHO https://github.com/kubernetes/kops/issues/1123
