### ISSUE TITLE
Service Account IAM Role names are too long 

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#10382]
The service account IAM roles created by the PublicJWKS feature flag can exceed the IAM role name length limit. See the failing job logs [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-scenario-public-jwks/1335447225534255104).

`W1206 04:58:15.902425    1067 executor.go:131] error running task "IAMRole/dns-controller.kube-system.sa.e2e-kops-scenario-public-jwks.test-cncf-aws.k8s.io" (5m52s remaining to succeed): error getting role: ValidationError: 1 validation error detected: Value 'dns-controller.kube-system.sa.e2e-kops-scenario-public-jwks.test-cncf-aws.k8s.io' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64` 

A reasonable solution would be to hash a portion of the name:

https://github.com/kubernetes/kops/blob/2f6c67e92ce97f4513b199c03081a12ff4367613/pkg/model/iam/types.go#L51

but I'm wondering if others have opinions about which portion(s) to hash. We still don't tag IAM roles even though they support tagging, so to maintain discoverability to users we could add the service account name and namespace as tags in addition to the usual cloud tags.

**Comment by justinsb** [comment]
I implemented a workaround for the failing test in #10437.

I really like the idea of tagging these roles now that they support tagging - it would make cleanup easier, and we could detect collisions (unlikely as they are)

**Comment by rifelpet** [comment]
confirmed this is no longer an issue
/close
