### ISSUE TITLE
Set up end-to-end testing for DigitalOcean

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/kops#10386]
In #10312 we discussed that it'd be great to have some end-to-end test coverage validating proper functioning of the DigitalOcean support in kops. This ticket is to track work needed to build initial DO testing.

TODOs:

- [ ] Set up a sponsored DO account that kops can use for testing purposes (owner: myself and @rifelpet who [offered assistance](https://github.com/kubernetes/kops/pull/10312#pullrequestreview-538096303) in this regard)
- [ ] Build out the initial set of end-to-end testing (owner: @srikiz)

**Comment by timoreimann** [comment]
@rifelpet being able to share the DO account that was set up for Cluster API DigitalOcean ([CAPDO](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean)) some time ago would be ideal from my perspective. 

One thing we should look into then is whether we limits / quotas set on that account are still set up appropriately if we also start having kops use DigitalOcean cloud resources regularly. Do we have any feel for how many resources the future kops tests may need (in terms of droplets, volumes, load balancers, firewalls, etc.) or how often we expect tests to run? Having some starting point would be great, but if not then that's okay as well -- we can also tune things as we go.

(Happy to discuss here or chat on Slack if that's easier.)

**Comment by rifelpet** [comment]
I think starting with a basic test that runs weekly would be sufficient. When doing the initial development of the e2e job we can have it run more often to reduce the feedback loop but once its in good shape we can back it off to weekly. The AWS jobs take about 40 minutes to run so we can probably expect timing to be similar depending on provisioning and teardown time in DO.

Regarding resource usage, I think that's up to both of you. We can start with a basic cluster that uses defaults for most settings and if there are additional configurations that you think are worth testing we can add jobs for them as well. For example: an HA control plane, different networking plugins, etc.

**Comment by rifelpet** [comment]
@srikiz with our initial job in place I think we can close this. If you have other cluster configurations you'd like to test we can certainly setup additional jobs, including running the existing job less frequently to avoid cost increases.

**Comment by srikiz** [comment]
@rifelpet - Sure. I think we should be good to close this. Thanks !!
