### ISSUE TITLE
Refactor bastion to use an instance group approach

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1039]
An idea for bastion is to use an instance group approach

1. Capability for crud on the bastion
2. Updates during rolling updates with other nodes
3. Control DNS 
4. Control dynamic availablility
5. Create and destroy elb

I think if we use the same pattern for the bastion that would be awesome. We need another for of instance group that will stop the install if k8s on the bastion, but will allow for the other requirements to work.

Thoughts @kris-nova?

**Comment by chrislovecnm** [comment]
#1183 should close this

**Comment by chrislovecnm** [comment]
This work is completed and needs to be tested, umbrella issue: https://github.com/kubernetes/kops/issues/1206

**Comment by chrislovecnm** [comment]
Who can test?

**Comment by justinsb** [comment]
Bastions now use instance groups.  Closing.
