### ISSUE TITLE
Need a timeout option for kops rolling-update

### ISSUE THREAD

**Issue by jsonmp-k8** [kubernetes/kops#10400]
Currently kops rolling-update does not have an option to pass a time-out to specify how long the rolling update should wait for the pods on the nodes to be evicted. Sometimes when a node has an invalid or a strict PDB, the rolling update loops on the node for ever. This impedes/slows down the ability to do a rolling-update on large clusters with strict PDB's  set.

For example:We have tenants that have deployments that have a PDB that doesn't allow any pods to be disrupted. This causes the rolling-update to loop for ever without being able to evict the pods and drain the node. 

With the timeout option for rolling-update, I should be able to specify how long should the rolling update wait on each node before moving on to the next node. This will help us do a rolling update of large cluster where strict PDB's are set. An option like this `--drain-timeout` would be helpful

**Comment by jsonmp-k8** [comment]
Will this enhancement be considered for any of the upcoming releases ?

**Comment by olemarkus** [comment]
It is an interesting feature. I would certainly be happy to review a pull request.

**Comment by johngmyers** [comment]
I believe this would need to be added to `drain.Helper` in the upstream go-client.

One might want two timeouts: one on the PDB and another on `terminationGracePeriodSeconds` (once one has decided to involuntarily evict).

Another useful feature would be to first involuntarily evict the unready pods that are under PDB and give time before involuntarily evicting the ready pods.

**Comment by jsonmp-k8** [comment]
can this be reopened ?

**Comment by johngmyers** [comment]
/reopen

This would require the feature first be added to the upstream `drain.Helper`.
