### ISSUE TITLE
Support generating TOML files

### ISSUE THREAD

**Issue by bharath-123** [kubernetes/kops#10454]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Currently in kOps, there is no easy way to generate TOML files. Containerd uses a TOML file for configuration. This makes it an important use case for kOps as we will be moving away from docker soon enough :) 

**2. Feel free to provide a design supporting your feature request.**

https://github.com/pelletier/go-toml seems like a good library for this use case.

**Comment by balibebas** [comment]
I believe OP is suggesting that because Kubernetes is dropping support for Docker as a CRI a change will be necessary in order to use kOps to specify containerd Config when bootstrapping a cluster. Is that correct logic on my part @bharath-123? Also, can you provide an example use case for analysis/testing?

**Comment by bharath-123** [comment]
@balibebas that is true to an extent. Configuring containerd in kOps is pretty difficult https://github.com/kubernetes/kops/blob/master/pkg/model/components/containerd.go#L70 

Quite a few container runtimes are using TOML files to configure like cri-o etc. So adding a way of configuring TOML file will be useful.

**Comment by olemarkus** [comment]
Also relevant for the bottlerocket support, @rifelpet

**Comment by rifelpet** [comment]
I'm actually using that same library to generate the bottlerocket userdata:

https://github.com/kubernetes/kops/pull/9855/files#diff-c1c852aea92883d3117fae99c1610c5cdcbc217f5aa3b340f23b5dd02e971d99R442

I think using it for generating other TOML files would be appropriate.

**Comment by hakman** [comment]
This is done as part of #10507, including adding the https://github.com/pelletier/go-toml lib.
