### ISSUE TITLE
kops-configuration not starting on ARM processors

### ISSUE THREAD

**Issue by Moshem123** [kubernetes/kops#10480]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.19.0-beta.2 (git-c006d97e5596024f9b9a5681c97300165156319e)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-13T18:42:23Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

```

**3. What cloud provider are you using?**
`AWS`

Trying `kOps 1.19.0-beta2` to run with ARM processor on worker nodes using this image and instance type:
```
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20201210
  machineType: c6g.2xlarge
```
Servers won't join the cluster. After SSHing I can see on `/var/log/cloud-init-output.log`:

```
I1220 10:48:52.726951    1468 executor.go:103] Tasks: 0 done / 1 total; 1 can run
I1220 10:48:52.726977    1468 executor.go:178] Executing task "Service/kops-configuration.service": Service: kops-configuration.service
I1220 10:48:52.727078    1468 changes.go:81] Field changed "Definition" actual="<nil>" expected="[Unit]\nDescription=Run kops bootstrap (nodeup)\nDocumentation=https://github.com/kubernetes/kops\n\n[Service]\nEnvironment=\"AWS_REGION=us-east-1\" \nEnvironmentFile=/etc/environment\nExecStart=/opt/kops/bin/nodeup --conf=/opt/kops/conf/kube_env.yaml --v=8\nType=oneshot\n\n[Install]\nWantedBy=multi-user.target\n"
I1220 10:48:52.727104    1468 changes.go:81] Field changed "Running" actual="false" expected="true"
I1220 10:48:52.727114    1468 changes.go:81] Field changed "Enabled" actual="<nil>" expected="true"
I1220 10:48:52.727124    1468 changes.go:81] Field changed "ManageState" actual="<nil>" expected="true"
I1220 10:48:52.727133    1468 changes.go:81] Field changed "SmartRestart" actual="<nil>" expected="true"
I1220 10:48:52.727247    1468 files.go:50] Writing file "/lib/systemd/system/kops-configuration.service"
I1220 10:48:52.727302    1468 service.go:286] Reloading systemd configuration
I1220 10:48:52.871496    1468 service.go:349] Restarting service "kops-configuration.service"
```

Then, running `systemctl status kops-configuration`:
```
● kops-configuration.service - Run kops bootstrap (nodeup)
     Loaded: loaded (/lib/systemd/system/kops-configuration.service; disabled; vendor preset: enabled)
     Active: activating (start) since Sun 2020-12-20 10:48:52 UTC; 1min 57s ago
       Docs: https://github.com/kubernetes/kops
   Main PID: 1508 (nodeup)
      Tasks: 20 (limit: 18805)
     Memory: 1.0G
     CGroup: /system.slice/kops-configuration.service
             ├─1508 /opt/kops/bin/nodeup --conf=/opt/kops/conf/kube_env.yaml --v=8
             ├─4669 systemctl restart protokube.service
             └─4699 systemctl restart docker-healthcheck.service

Dec 20 10:49:47 ip-10-28-231-209 nodeup[1508]: I1220 10:49:47.968771    1508 service.go:349] Restarting service "logrotate.service"
Dec 20 10:49:48 ip-10-28-231-209 nodeup[1508]: I1220 10:49:48.169576    1508 service.go:123] querying state of service "logrotate.timer"
Dec 20 10:49:48 ip-10-28-231-209 nodeup[1508]: W1220 10:49:48.177272    1508 service.go:331] service was running, but did not have ExecMainStartTimestamp: "logrotate.timer"
Dec 20 10:49:48 ip-10-28-231-209 nodeup[1508]: I1220 10:49:48.177291    1508 service.go:360] Enabling service "logrotate.timer"
Dec 20 10:49:48 ip-10-28-231-209 nodeup[1508]: I1220 10:49:48.183078    1508 service.go:360] Enabling service "docker-healthcheck.timer"
Dec 20 10:49:48 ip-10-28-231-209 nodeup[1508]: I1220 10:49:48.193220    1508 service.go:360] Enabling service "logrotate.service"
Dec 20 10:49:48 ip-10-28-231-209 nodeup[1508]: I1220 10:49:48.206865    1508 service.go:360] Enabling service "docker.socket"
Dec 20 10:49:48 ip-10-28-231-209 nodeup[1508]: I1220 10:49:48.389155    1508 service.go:360] Enabling service "kubernetes-iptables-setup.service"
Dec 20 10:49:49 ip-10-28-231-209 nodeup[1508]: I1220 10:49:49.243900    1508 service.go:360] Enabling service "systemd-timesyncd"
Dec 20 10:50:49 ip-10-28-231-209 nodeup[1508]: I1220 10:50:49.211099    1508 service.go:360] Enabling service "kubelet.service"
```

And nothing happens.
Do I need some special configuration for kOps to be able to start on ARM-based instance types?
Thanks.

**Comment by hakman** [comment]
Thanks for reporting this @Moshem123. Should be fixed in beta 3 that will be released next week.
Until then, you can try using AMD64 control plane with ARM64 worker nodes.

**Comment by Moshem123** [comment]
> Thanks for reporting this @Moshem123. Should be fixed in beta 3 that will be released next week.
> Until then, you can try using AMD64 control plane with ARM64 worker nodes.

Thanks @hakman but I changed only worker nodes, not masters. As I understand, worker nodes should already support ARM64 no? Is there anything else I need to change in order for the worker nodes to work with ARM64?

**Comment by hakman** [comment]
By any chance you are using a `.local` cluster name? Also, what k8s version did you use?
Can you check the logs for the `kops-configuration` service using journalctl? Should tell you what exactly fails.

**Comment by Moshem123** [comment]
> By any chance you are using a `.local` cluster name? Also, what k8s version did you use?
> Can you check the logs for the `kops-configuration` service using journalctl? Should tell you what exactly fails.

Yeah, my cluster name is `clustername.k8s.local`.
Logs I'll try to provide asap as we reverted to AMD64 processors.

**Comment by hakman** [comment]
Thanks. No need for logs. I am familiar with the issue, see https://github.com/kubernetes/kops/pull/10396. 
A workaround may be to create an empty `/lib64` dir on the host (maybe with a hook).

**Comment by Moshem123** [comment]
Thanks, will it be introduced in beta3?
I didn't see an option in the hooks to create an empty dir, mind giving an example?
Thanks kindly.

**Comment by hakman** [comment]
Try using with execContainer and run a shell command `mkdir -p /lib64`.
Or create a file in that dir with fileAssets: https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#fileassets.
Or use additionalUserData to create the dir: https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#optional-step-add-root-certificates-to-instancegroups-root-ca-bundle.

**Comment by hakman** [comment]
Any luck @Moshem123 ?

**Comment by Moshem123** [comment]
> Any luck @Moshem123 ?

Got rejects from management :) Let's call it for now and close.
Thanks for all the help.

**Comment by hakman** [comment]
Sorry to hear that. :)
