### ISSUE TITLE
Launch Configurations not getting deleted on deleting cluster

### ISSUE THREAD

**Issue by alok87** [kubernetes/kops#1051]
`kops delte cluster` does not delete launch configurations.

**Comment by kris-nova** [comment]
I think we are only missing the `bastion` launch configurations on delete..

Here is where I would start looking https://github.com/kubernetes/kops/blob/master/upup/pkg/kutil/delete_cluster.go#L1413

**Comment by geojaz** [comment]
Also see #1070

**Comment by chrislovecnm** [comment]
closed the duplicate

**Comment by alok87** [comment]
👍
