### ISSUE TITLE
Remove copyright year from generated go files

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#10515]
The copyright year being in the file header causes issues every new year requiring us to regenerate the apimachinery files for all active branches. This issue was raised and determined the year is not necessary: https://github.com/kubernetes/gengo/issues/24

> Legal guidance is that the year is literally meaningless on these files. My proposal is that we simply omit the year field, and fix the kubernetes linter(s) to accept boilerplate with or without year.

See also the linked PRs to that issue that are removing it from various kubernetes repos. We should update ours to do the same. One issue we might run into is that the header file we pass to apimachinery is shared by our hack/update-header.sh script which touches nearly _every_ file in the repo. We could remove the year from every file but that would increase the likelihood of merge conflicts. Or I think we could use a separate header file just for apimachinery that doesn't have the year in it, thereby only touching the apimachinery-generated files.

**Comment by bmelbourne** [comment]
@rifelpet 
I'd already started looking into this issue as a result of the failed `make quick-ci` test in one of my PRs, so I can take this one.

/assign @bmelbourne
