### ISSUE TITLE
Does KOPS cluster is setup with IAM Roles

### ISSUE THREAD

**Issue by ashwinbasavaraja** [kubernetes/kops#10531]
Hi All,

I am new user to KOPS & seeing documentation to setup kops in AWS. As per the initial step it is asking us to create IAM User with privileges mentioned - https://kops.sigs.k8s.io/getting_started/aws/#setup-iam-user

Instead of IAM User, can we setup the kops cluster using IAM roles with same privileges. Please give us steps to configure if we need to setup kops by IAM Role.

Thanks,
Ashwin

**Comment by olemarkus** [comment]
You can reuse that entire guide. Just assign the policies to your role instead of the iam user/group.

**Comment by olemarkus** [comment]
NP. Assume this can be closed
/close
