### ISSUE TITLE
Kops Generate (Terraform Refactor)

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1055]
# Terraform Configuration in Kops - The saga begins

Right now kops supports generating Terraform configuration files instead of actually applying changes to your defined cloud. In other words, instead of using kops to make changes in AWS/GCE, a user could opt-out and actually generate raw Terraform configuration files. 

More information on the feature [here](https://github.com/kubernetes/kops/blob/master/docs/terraform.md)
More information on us deciding to support the feature https://github.com/kubernetes/kops/issues/793

# Terraform logic in AWS - Attack of the cloned Render() method

Right now our `cloudup` engine uses a smart methodology for applying deltas in AWS. These are called `awstask`'s. The engine has a concept of `a` (actual), and `e` (expected) resources at time of application.

We store the AWS Terraform configuration logic in the same place. I think we could separate our concerns a little better here. While I think **yes** we need AWS specific Terraform logic, I also think it should be supported outside the concerns of the AWS API application logic.

Example of AWS and Terraform logic in the same place can be found in the VPC `awstask` [here](https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awstasks/vpc.go#L199)

# Confusion around targets - Revenge of the --yes

I think `--target=terraform` might be a round about way of saying "Do not apply my changes, but rather generate Terraform configuration for me". Which is fine, and we need the support to be open like this to further support other targets like `CloudFormation`

But as it stands, there is some confusion around the best way to handle this.

Examples of confusion : 
https://github.com/kubernetes/kops/issues/352
https://github.com/kubernetes/kops/issues/354
https://github.com/kubernetes/kops/issues/536

# kops generate - A new hope

I propose we implement a **NEW** kops command that would fall under the `kops generate $target` guise.

An example of a user generating terraform config could look something like :

```
export KOPS_STATE_STORE=s3://<somes3bucket>
export CLUSTER_NAME=<kubernetes.mydomain.com>
kops create cluster ${CLUSTER_NAME} --zones us-east-1c
kops generate terraform ${CLUSTER_NAME} --no-provider --module-only

cd out/terraform
terraform plan
terraform apply
```

Proposed example to generate module code only for https://github.com/kubernetes/kops/issues/1026 above with `--module-only`
Proposed example to neglect provider for https://github.com/kubernetes/kops/issues/386 with `--no-provider`

#### What we gain
* A unique workflow for generating configuration of any kind, terraform being our first option.
* Flexibility in customizing use cases for configurations, as we obviously have many use cases for one-offs
* We can get Terraform code out of `awstask`'s 
* We can work on cloud code, and generation code independently of each other.
* We can eliminate confusion around `--yes` and `--target`
* This makes the code easier to test, which makes it easier to maintain

#### How to make this happen

1. We need unit tests around our terraform logic, bottom line. If we can harden and flesh these tests out in a PR (or series of PRs) in the near future, it should help us when it comes time for a switch
2. Flip the core over to the new command `kops generate`. This is it's own PR.
3. Deprecate the `--target` flag, with a warning message about `kops generate`
4. Profit

**Comment by lsowen** [comment]
@kris-nova are you still thinking this is the proper path forward?  If so, any suggestions for bite sized pieces I could work on to help start pushing towards it?

**Comment by chrislovecnm** [comment]
What questions do you have? With my work on phases and lifecycles we could do some cool stuff
