### ISSUE TITLE
Terraform bug with API load balancer with NLB and sslCertificate

### ISSUE THREAD

**Issue by hoepfnerj** [kubernetes/kops#10562]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.19.0-beta.3 (git-e43f1cc6e3c77d093935d1706042861095d75eb7)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I configured the API load balancer with class: Network and sslCertificate. When I let kops generate Terraform from this manifest and apply it, Terraform eventually quits with:

Error: error creating ELBv2 Listener: IncompatibleProtocols: The listener and the following target groups have incompatible protocols: arn:aws:elasticloadbalancing:XXX:XXX:targetgroup/tls-XXX/XXX
        status code: 400, request id: XXX.

**5. What happened after the commands executed?**

Terraform cannot be successfully applied. See error above.

**6. What did you expect to happen?**

The listeners and the target groups that are instantiated should be compatible and Terraform can be applied successfully.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: mycluster
spec:
  api:
    loadBalancer:
      type: Internal
      sslCertificate: arn:aws:acm:XXX:XXX:certificate/XXX
      class: Network
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

The connection between the two listeners and the two target groups seem to be mixed up. When I manually connect the TLS listener with port 443 to the "tls-" target group and the TCP listener with port 8443 to the "tcp-" target group it seems to work. The generated terraform code is the other way around:

```terraform
resource "aws_lb_listener" "api-XXXXX-443" {
  certificate_arn = "arn:aws:acm:XXX:XXX:certificate/XXX"
  default_action {
    target_group_arn = aws_lb_target_group.tcp-XXX.id
    type             = "forward"
  }
  load_balancer_arn = aws_lb.api-XXX.id
  port              = 443
  protocol          = "TLS"
}

resource "aws_lb_listener" "api-XXX-8443" {
  default_action {
    target_group_arn = aws_lb_target_group.tls-XXX.id
    type             = "forward"
  }
  load_balancer_arn = aws_lb.api-XXX.id
  port              = 8443
  protocol          = "TCP"
}```

**Comment by rifelpet** [comment]
Thanks for the report! This is a bug specific to terraform and cloudformation in how we generate the listener definitions. I have a fix in #10567 and we'll be sure to include it in the 1.19.0 release.
