### ISSUE TITLE
Support for AWS m5zn.xlarge instances in kops Version 1.18.2.

### ISSUE THREAD

**Issue by kazekin94** [kubernetes/kops#10580]
Trying to create an IG in a cluster deployed on aws, my use case requires me to use very high clock speed cpu's hence the m5zn.xlarge instances. 

On running kops update cluster name --yes encounter this error.

ERROR --> 
[ec2-user@ip-xxx-x-xx-xx ~]$ kops update cluster
Using cluster from kubectl context: some.domian.name
cpunodes.spec.machineType: Invalid value: "m5zn.xlarge": machine type specified is invalid
[ec2-user@ip-xxx-x-xx-xx ~]$ kops version
Version 1.18.2 (git-84495481e4)

**Comment by hakman** [comment]
Thanks for reminding us about this.
Fixed in #10587.
/close
