### ISSUE TITLE
kOps deletes AWS Launch Templates with multiple (>3) versions

### ISSUE THREAD

**Issue by cameronattard** [kubernetes/kops#10611]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.18.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.18.14

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops update cluster --name="${KOPS_CLUSTER_NAME}"

**5. What happened after the commands executed?**

kOps deletes launch templates that have >3 versions, leaving instance groups / autoscaling groups unable to launch instances.

```
Will modify resources:
  LaunchTemplate/nodes-us-west-2a.$KOPS_CLUSTER_NAME
  	ImageID             	 $OLD_AMI_ID -> $NEW_AMI_ID
  LaunchTemplate/nodes-us-west-2b.$KOPS_CLUSTER_NAME
  	ImageID             	 $OLD_AMI_ID -> $NEW_AMI_ID
  LaunchTemplate/nodes-us-west-2c.$KOPS_CLUSTER_NAME
  	ImageID             	 $OLD_AMI_ID -> $NEW_AMI_ID
Will delete items:
  LaunchTemplate       nodes-us-west-2b.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2b.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2b.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2b.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2b.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2b.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2b.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2c.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2c.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2c.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2c.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2c.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2c.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2c.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2a.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2a.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2a.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2a.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2a.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2a.$KOPS_CLUSTER_NAME-20210111234429
  LaunchTemplate       nodes-us-west-2a.$KOPS_CLUSTER_NAME-20210111234429
```
**6. What did you expect to happen?**

I'd expect kops to delete launch template versions older than the last 3, rather than deleting the entire launch template. We have an out-of-band process that replaces the AMI id in the launch templates by adding a new launch template version, so at the moment we have to run `kops update cluster` twice in order to recreate the launch template.

Related: https://github.com/kubernetes/kops/issues/6501

**Comment by hakman** [comment]
Thanks for reporting this @cameronattard. Launch Templates were heavily modified in 1.19 and use versioning instead of new named templates. Would it be possible for you to give a try to the latest kOps 1.19 beta?

**Comment by cameronattard** [comment]
> Thanks for reporting this @cameronattard. Launch Templates were heavily modified in 1.19 and use versioning instead of new named templates. Would it be possible for you to give a try to the latest kOps 1.19 beta?

Sure, will give it a try. Thanks!

**Comment by hakman** [comment]
I will take the lack of complaints as confirmation that this is fixed 😄

**Comment by cameronattard** [comment]
All fixed, thanks again @hakman!
