### ISSUE TITLE
Feature request: compatibility with gVisor

### ISSUE THREAD

**Issue by jecnua** [kubernetes/kops#10625]
I would love to be able to spin up a cluster with kops that has support for gVisor for security.

gVisor's kubernetes integration page shows that the only production mode option is as a plugin to containerd.

I know that the only supported container runtime right now is Docker, and Docker runs against some version of containerd. So theoretically maybe I can go through the steps of the gVisor installation and set up gvisor-containerd-shim and runsc as they describe? Perhaps using some of the techniques in the Docker runtime execution options docs.

Please correct me if I'm wrong, but it seems like the next step would be to create an image based on these modifications and start a cluster with it.

Or is it necessary to wait for explicit support for alternative runtimes in #5524 before this is likely to work? Thanks!

==

COPY of https://github.com/kubernetes/kops/issues/7342
Reopening due to stale bot.

**Comment by olemarkus** [comment]
Master branch defaults to using containerd, so in order to implement support for gvisor you only need to install gvisor's runtime+config and configure containerd to use it
