### ISSUE TITLE
Leftover launch configurations when using kops 1.19-beta.3

### ISSUE THREAD

**Issue by mtb-xt** [kubernetes/kops#10623]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.19.0-beta.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.18.14

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I have a cluster created by kops 1.18.0, I needed to perform some maintenance on the instancegroups, and because there's a ELB bug in 1.18.2, I've downloaded kops 1.19.-beta.3. After making changes with `kops edit cluster`, I ran `kops update cluster --out ../terraform/prod-hk/ --target terraform` and then `terraform apply`

**5. What happened after the commands executed?**
I've got an error about autoscaling group launch configs:
```
Error: error deleting Autoscaling Launch Configuration (master-ap-east-1a.masters.k8s.hk.prod.*.*-2020100703565463040000000a): ResourceInUse: Cannot delete launch configuration master-ap-east-1a.masters.k8s.hk.prod.*.*2020100703565463040000000a because it is attached to AutoScalingGroup master-ap-east-1a.masters.k8s.hk.prod.*.*
```
I have several similar errors like this - about all 3 masters and some instance groups, not all of them.

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

https://gist.github.com/mtb-xt/f88bcc24418f3374529bb20065b9496b

**Comment by mtb-xt** [comment]
Update: This problem is solved by just deleting the launch configurations from the state file.

`terraform state rm aws_launch_configuration.master-ap-east-1a-masters-k8s-hk-prod-*-*`
and so on...

**Comment by hakman** [comment]
Hey @mtb-xt. Please check the release notes for more info on this topic:
https://kops.sigs.k8s.io/releases/1.19-notes/#required-actions

**Comment by mtb-xt** [comment]
> Hey @mtb-xt. Please check the release notes for more info on this topic:
> https://kops.sigs.k8s.io/releases/1.19-notes/#required-actions

🤦 Thank you.
