### ISSUE TITLE
Don't allow invalid paths in `set cluster`

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#10647]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Currently `kops set cluster` accepts paths that aren't valid. 

`kops set cluster foo.k8s.local spec.foo=invalid`

This can lead to confusion when paths contain typos. We should return an error when a path doesn't match an actual field in the cluster spec.

**2. Feel free to provide a design supporting your feature request.**

**Comment by bharath-123** [comment]
Have been a victim of this many a times, especially when setting kubernetes versions :( I think this would require messing around with stuff in reflect utils. Will take this up.
