### ISSUE TITLE
Allow the server signing key to be obtained via a VFS when configuring the kubeAPIServer in the cluster spec

### ISSUE THREAD

**Issue by mmerrill3** [kubernetes/kops#10640]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Allow the server signing key to be accessible via a VFS when configuring the kubeAPIServer in the cluster spec

When defining kubeAPIServer.serverSigningKey, we still set the location on the master node where the private key should be stored to sign JWT tokens.
In addition, define where that key can be obtained, via the VFS.  

For instance, if the key should be obtained from an s3 location, or from vault, we should have the ability to say where to go to get this key, in addition to the final destination for the API server.

This new configuration could be kubeAPIServer.keyStore, 

If this is defined, then kubeAPIServer.serverSigningKey must also be defined.

We can look for the key name in kubeAPIServer.serverSigningKey within the VFS provided by kubeAPIServer.keyStore.

**2. Feel free to provide a design supporting your feature request.**

**Comment by olemarkus** [comment]
Thanks for the time making this issue.

I was thinking that we perhaps define something like `spec.PublicDataStore`. There may be other things that one can put in a store that one expects is world readable. E.g if the public key of the cluster CA was there, users could build kubeconfig without having access to the secretStore.

**Comment by mmerrill3** [comment]
Thanks for the feedback @olemarkus .
I'm focusing on the ability to just set the private signing key used by the API server, so I can set this key if I decide to create an new OIDC issuer for the cluster.  The key would be stored at a VFS location somewhere, and not publicly accessible, but only accessible to kOps.  The public key could go in the spec.PublicDataStore though, along with all the other public keys we used to make JWT tokens from the controller manager and the API server.  The problem I'm trying to solve exactly is that I am trying to avoid having the cluster spec contain a literal key in the yaml when I define the kubeAPIServer.serverSigningKey.  This parameter, kubeAPIServer.serverSigningKey, points to a file location on the master.  So, the file needs to be there before the APIServer is started.  One way to do this is to use fileAssets, which is bad, b/c we have to put the literal contents of the file (the key) into the yaml.  

Another way is to script it out, where we can register a webhook call to happens before the kubelet service starts.  Kubelet starts the API Server through a static manifest.  This is ok, but kinda hacky.  

I was looking for a graceful way to tell kOps where the private key is when setting kubeAPIServer.serverSigningKey.

**Comment by olemarkus** [comment]
Yep. Slightly different problems. I think that when we create a "managed" signing key, we should put the private bit in SecretStore and just let nodeup fetch it from there. fields like ServiceAccountSigningKeyFile should be managed by kOps and not set by users.

The challenging bit we have been talking about on slack is how to expose the resulting JWKS document somewhere world-readable.

**Comment by olemarkus** [comment]
/remove-lifecycle stale

Does the recent IRSA PRs solve this one?
