### ISSUE TITLE
Allow specifying annotations for addons clusterAutoscaler and nodeTerminationHandler

### ISSUE THREAD

**Issue by trondhindenes** [kubernetes/kops#10659]
We use kiam to manage aws permissions in our cluster. Kiam is configured via pod annotations, such as `iam.amazonaws.com/role: {{ cluster_name }}-cluster-autoscaler`. It would be awesome if kops allowed adding extra annotations to the cluster-autoscaler and node termination handler addons. Since these interact with the aws api we prefer explicit roles (via kiam) for them, which would be easy to add if we had access to the annotations dict via kops' config

**Comment by olemarkus** [comment]
Right now cluster autoscaler runs on the control plane. Do you run kiam agents also on the control plane? That can have some unintended consequences.

Going forward, the plan is to support Instance Roles for Service Accounts (IRSA) for the addons that talk to the AWS API. kOpx will then also provision the IAM Roles needed for the addons.

**Comment by trondhindenes** [comment]
Ah, gotcha. We currently run cluster-autoscaler on workers.
Nice, then there is a plan for it. That's all I need to know :-)

Feel free to close this.

**Comment by olemarkus** [comment]
Closing then :)

/close
