### ISSUE TITLE
Creating cluster using KOPS in DigitalOcean never validates

### ISSUE THREAD

**Issue by superfly-git** [kubernetes/kops#10678]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.19.0-beta.1 (git-6fa37fc5bdc2eedd7f0c696dd8155ac267b310fd)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.19.0

**3. What cloud provider are you using?**
digital ocean

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create -f cluster.yaml --name ${CLUSTER_NAME}
kops create secret --name cluster.k8s.local sshpublickey admin -i ~/.ssh/do_instance_rsa.pub
kops update cluster --name $CLUSTER_NAME --yes

**5. What happened after the commands executed?**
W0129 08:38:45.192002 1577711 validate_cluster.go:173] (will retry): unexpected error during validation: error listing nodes: an error on the server ("") has prevented the request from succeeding (get nodes)

**6. What did you expect to happen?**
be able to validate the cluster

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  kubernetesApiAccess:
  - {specificip}/32
  sshAccess:
  - {specificip}/32
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: digitalocean
  configBase: s3://kops-bucket/cluster.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-sfo2-1
      name: "1"
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-sfo2-1
      name: "1"
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: false
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesVersion: 1.19.0
  masterPublicName: api.cluster.k8s.local
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  - name: sfo2
    region: sfo2
    type: Private
    zone: sfo2
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: master-sfo2-1
spec:
  image: ubuntu-20-04-x64
  machineType: s-2vcpu-4gb
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-sfo2-1
  role: Master
  rootVolumeSize: 20
  subnets:
  - sfo2

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: nodes-sfo2
spec:
  image: ubuntu-20-04-x64
  machineType: s-2vcpu-2gb
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-sfo2
  role: Node
  rootVolumeSize: 20
  subnets:
  - sfo2


```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
`telnet {specificip} 443 `returns a result that suggests that the api LB is accessible and the port is open 
I can also verify that the LB was created and get its IP using `doctl compute load-balancer list` and then verify further by checking the ~/.kube/config the server field contain the same IP address for the k8s API.

And finally as shown above i manually generated the kops yaml config from exporting a previewsly created cluster and i run it by giving it as input to kops create -f cluster.yaml ... because i wanted be able to edit the kubernetesApiAccess field to restrict access to the API to specific IP.

Some additional findings after i got on the master node, it looks like the kops config on the master node thinks its on AWS EC2. Is this related to   configBase: s3://kops-bucket/cluster.k8s.local that i used for KOPS state?
```
root@master-sfo2-1:~# systemctl status kops-configuration.service 
● kops-configuration.service - Run kops bootstrap (nodeup)
     Loaded: loaded (/lib/systemd/system/kops-configuration.service; disabled; vendor preset: enabled)
     Active: activating (start) since Fri 2021-01-29 07:39:14 UTC; 1h 34min ago
       Docs: https://github.com/kubernetes/kops
   Main PID: 1855 (nodeup)
      Tasks: 6 (limit: 4683)
     Memory: 9.4M
     CGroup: /system.slice/kops-configuration.service
             └─1855 /opt/kops/bin/nodeup --conf=/opt/kops/conf/kube_env.yaml --v=8

Jan 29 09:13:40 master-sfo2-1 nodeup[1855]: caused by: EC2MetadataError: failed to make EC2Metadata request
Jan 29 09:13:40 master-sfo2-1 nodeup[1855]:         status code: 404, request id:
Jan 29 09:13:40 master-sfo2-1 nodeup[1855]: caused by: not found
Jan 29 09:13:40 master-sfo2-1 nodeup[1855]: W0129 09:13:40.748780    1855 main.go:133] got error running nodeup (will retry in 30s): error loading Cluster "s3://kops/cluster-kops>
Jan 29 09:13:40 master-sfo2-1 nodeup[1855]: caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
Jan 29 09:13:40 master-sfo2-1 nodeup[1855]: SharedCredsLoad: failed to load profile, .
Jan 29 09:13:40 master-sfo2-1 nodeup[1855]: EC2RoleRequestError: no EC2 instance role found
Jan 29 09:13:40 master-sfo2-1 nodeup[1855]: caused by: EC2MetadataError: failed to make EC2Metadata request
Jan 29 09:13:40 master-sfo2-1 nodeup[1855]:         status code: 404, request id:
Jan 29 09:13:40 master-sfo2-1 nodeup[1855]: caused by: not found
```

**Comment by zetaab** [comment]
when you are using do you should export s3 credentials first, and if I remember correctly you need use `do://` in state store instead of `s3://`

You need to have following variables exported before running kops commands:
`S3_ENDPOINT`
`S3_ACCESS_KEY_ID`
`S3_SECRET_ACCESS_KEY`

like the docs https://github.com/kubernetes/kops/blob/3d039680839933ca93ca03e392d6a20d46897a54/docs/getting_started/digitalocean.md#environment-variables says.. Now you are using s3:// at least which will not work

**Comment by superfly-git** [comment]
Yes, correct. I changed to a DO bucket and the issue is fixed. After some trial and error i remembered that credentials are needed in order to access an S3 bucket. Something which is not available on a droplet unless you manually add them. 

After switching to a DO spaces bucket for the state the problem is fixed. Issue can be closed, its not a bug
