### ISSUE TITLE
Check the env variable AWS_DEFAULT_REGION is not configured

### ISSUE THREAD

**Issue by aledbf** [kubernetes/kops#1068]
the value was `us-west-2`

Error in k8s event log: `AuthFailure: AWS was not able to validate the provided access credentials`

*Edit:* solution taken from https://github.com/kubernetes/kubernetes/issues/17395#issuecomment-170295968

**Comment by justinsb** [comment]
Hmmm... this shouldn't matter.  Where did you hit this error message @aledbf ?

**Comment by aledbf** [comment]
If that variable exists no elb is created (kops stable 1.4.2 - k8s 1.4.6)

**Comment by chrislovecnm** [comment]
Well, that is interesting. I assume the IAM profile is preventing that?  Do you have an example of the profile with and without?

**Comment by justinsb** [comment]
I'm confused here.  If k8s logs `AuthFailure: AWS was not able to validate the provided access credentials`, that means that `AWS_DEFAULT_REGION` is being passed to kube-controller-manager (I presume?)  I'm pretty sure we don't do that.

Some more details would be helpful:

* Are we talking about an ELB created by k8s for (for a service with Type=LoadBalancer), or an ELB that kops is creating?
* Which process has `AWS_DEFAULT_REGION` set - kops or kube-controller-manager
* If it isn't kops that gets the env var, do you have any idea how it is being set?
