### ISSUE TITLE
Backport PR 10221 in next 1.18 and/or 1.19 ?

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/kops#10687]
Hello,

Would it be possible to get https://github.com/kubernetes/kops/pull/10221 backported in next 1.18 and/or 1.19 release ?

Nothing really important but that would allow me to use the implementation coming from the kops package directly.

**Comment by olemarkus** [comment]
I think this is more a feature than a bugfix. It is also behavior change, although a small one. I would prefer to not backport this one.

**Comment by eddycharly** [comment]
Ok, thanks @olemarkus. Closing the issue.

**Comment by hakman** [comment]
@eddycharly The plan is to have 1.20 out by end of Feb. So shouldn't be long.
