### ISSUE TITLE
Route53 instructions doesn't work . 

### ISSUE THREAD

**Issue by fii** [kubernetes/kops#1069]
Unable to connect to the server: dial tcp: lookup api.k8s.example  on 0.0.0.0:53: no such host

Guys - Unless we're missing something , instructions provided with DNS doesn't work. We're getting the above if we run kubectl get nodes after the cluster is up. 

Can you help ?

**Comment by chrislovecnm** [comment]
`api.k8s.example` will only work if you own `k8s.example` domain.  You need an actual domain to run kops.

Here is the documentation: http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-register.html
Here is a tutorial: https://www.siteleaf.com/blog/using-aws-s3-and-route-53/

**Comment by chrislovecnm** [comment]
Don't like the tutorial much ... looking for a better on.

**Comment by plombardi89** [comment]
Might be worthwhile to indicate that the DNS zone needs to be a public zone and not a private zone. I just made this mistake figuring it wasn't important because it was going to be internal to the cluster.

**Comment by kris-nova** [comment]
+1 on @plombardi89's comment - can we get this in the documentation please? this has burned a few people :(

**Comment by kris-nova** [comment]
Also there is an example [here](https://www.nivenly.com/k8s-aws-private-networking/#setting-up-dns-for-your-cluster) on how to do it from the command line - we really need this in the docs though :)

**Comment by kris-nova** [comment]
Also more information here https://github.com/kubernetes/kops/issues/781

**Comment by chrislovecnm** [comment]
This is now document in aws.md. @fii can you review?

**Comment by chrislovecnm** [comment]
Closing as we have docs
