### ISSUE TITLE
Masters should finish updating before applying changes to other instance groups

### ISSUE THREAD

**Issue by ari-becker** [kubernetes/kops#10703]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.18.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.18.15

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops update cluster --yes`, when upgrading Kubernetes versions i.e. from `1.17.x` to `1.18.x`

**5. What happened after the commands executed?**
When updating a cluster, the `update cluster` command applies the changes in launch configuration/launch template to both the masters and the worker instance groups at the same time. This causes a race condition that is particularly apparent in large production clusters that use cluster autoscaler and spot instances:

1. Run `kops update cluster` to begin the upgrade from Kubernetes `1.17` to `1.18`.
2. All launch configurations/templates are upgraded to point to running kubelet, kube-proxy, etc. from `1.18`.
3. Before being able to execute `kops rolling-update cluster`, the cluster autoscaler attempts to scale up an instance group, or a spot instance is terminated by AWS and replaced, starting a new EC2 worker instance
4. The new EC2 worker instance, running `1.18`, attempts to connect to the master instance (still running `1.17`) and fails.
5. Minor availability issues ensue due to the inability to schedule new pods (for lack of available resources), until a) at least one master has been upgraded to `1.18` and b) the problematic worker is terminated and replaced.

**6. What did you expect to happen?**
If `kops update cluster` would result in changes to both masters and workers, `kops update cluster` should only apply the changes to the masters and not to workers. `kops update cluster` should warn the user that changes were only partially applied, and that `kops update cluster` should be run again once there are no other changes to be applied to the masters.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
N/A

**9. Anything else do we need to know?**
N/A

**Comment by edsonmarquezani** [comment]
Just ran into the same issue for the first time after quite a few upgrades. Ideally, `kubernetesVersion` should be allowed to be set/overridden per *Instance Group*. This way we could easily upgrade masters securely before nodes.

As a workaround, as we don't apply anything in AWS with *KOPS*, but rather with *Terraform*, we are going to apply masters *Launch Templates* separately first.

**Comment by johngmyers** [comment]
The converse is just as, if not more, likely. Old-spec nodes aren't necessarily able to bootstrap with a newer control plane.

A change might not necessarily belong to just the control plane (or just to not-control-plane).

**Comment by ari-becker** [comment]
@johngmyers what do you have in mind?
my understanding is that Kubernetes always permits a skew of at least one version: https://kubernetes.io/releases/version-skew-policy/

**Comment by johngmyers** [comment]
For some transitions, new-spec instances won't bootstrap until they talk to a new-spec kops-controller.
