### ISSUE TITLE
Route53 entry for kops-controller stays after cluster is deleted

### ISSUE THREAD

**Issue by MichaelJDrK** [kubernetes/kops#10709]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.19.0 (git-04d36d7d92c72601efd918877fc180c846129ffb)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.19.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

1. Create a random cluster (use existing DNS zone, not a .local)
2. Wait until the cluster is up
3. Delete the cluster

**5. What happened after the commands executed?**

The cluster gets created.  
Route53 entry for kops-controller.internal.<clustername> gets created. 
Cluster gets deleted and cloud resources removed.

Route53 entry for kops-controller stays after the cluster is gone.

**6. What did you expect to happen?**

All cloud resources, including Route53 entrys, should be gone after a cluster has been deleted.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Does affect EVERY cluster, so no manifest required. 

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
-/-

**9. Anything else do we need to know?**
-/-

**Comment by bharath-123** [comment]
I can confirm this. I just checked my route53 entries and saw a whole list of kops-controller dns records. Not sure why these records are not deleted.

**Comment by rifelpet** [comment]
@MichaelJDrK this should be fixed for an upcoming 1.19.1 release.

If you're able to confirm this that would be great. There is a linux amd64 kops build [here](https://storage.googleapis.com/kops-ci/pulls/pull-kops-e2e-kubernetes-aws-1-19/pull-0b761467f2/linux/amd64/kops) you could use, or you could build the kops CLI yourself from the release-1.19 branch.

**Comment by MichaelJDrK** [comment]
I did a quick test and the route53 record got deleted this time, so it seems to work now. Thanks!
