### ISSUE TITLE
Problem listing ssh admin keys on S3

### ISSUE THREAD

**Issue by Vlatombe** [kubernetes/kops#10716]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.19.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops update cluster -v=10`

**5. What happened after the commands executed?**

```
I0203 10:36:02.806706   40247 s3fs.go:327] Listing objects in S3 bucket "[BUCKET-NAME]" with prefix "[CLUSTER-NAME]/pki/ssh/public/admin/"

error retrieving SSH public key "admin": error listing s3://[BUCKET-NAME]/[CLUSTER-NAME]/pki/ssh/public/admin: RequestError: send request failed
caused by: Get "https://[BUCKET-NAME].s3.amazonaws.com/?delimiter=%2F&prefix=[CLUSTER-NAME]%2Fpki%2Fssh%2Fpublic%2Fadmin%2F": EOF
```

**6. What did you expect to happen?**
This is the output with 1.18.3
```
I0203 10:32:22.367110   40158 s3fs.go:327] Listing objects in S3 bucket "[BUCKET-NAME]" with prefix "[CLUSTER-NAME]/pki/ssh/public/admin/"
I0203 10:32:22.468568   40158 s3fs.go:355] Listed files in s3://[BUCKET-NAME]/[CLUSTER-NAME]/pki/ssh/public/admin: [s3://[BUCKET-NAME]/[CLUSTER-NAME]/pki/ssh/public/admin/[key-id]]
I0203 10:32:22.468591   40158 s3fs.go:290] Reading file "s3://[BUCKET-NAME]/[CLUSTER-NAME]/pki/ssh/public/admin/[key-id]"
```

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by bharath-123** [comment]
Hi @Vlatombe. I am not able to reproduce this error :( Does this error occur intermittently or are you able to consistently reproduce this error?

**Comment by Vlatombe** [comment]
@bharath-123 I can reproduce it every time with 1.19.0, and it always works with 1.18.3.

FWIW, I'm using temporary credentials obtained through sts assume role in case that could matter.

**Comment by bharath-123** [comment]
Thank you for your reply. Is it possible to share the cluster spec you used? I ll try to reproduce the failure and see if its a bug in kOps.

**Comment by Vlatombe** [comment]
I've tried this again today and it is timing out somewhere else, even on other versions. Not sure what is going wrong here but it looks related to my connection rather than kops.
