### ISSUE TITLE
Getting certificate error while running kops update cluster

### ISSUE THREAD

**Issue by nambyats** [kubernetes/kops#10714]
Version 1.19.0 (git-04d36d7d92c72601efd918877fc180c846129ffb)

/home/ubuntu# kops update cluster --name sajeer.dev.k8s.sajeer.in --yes --admin
I0202 19:53:30.048678    2898 dns.go:96] Private DNS: skipping DNS validation
I0202 19:53:30.338228    2898 executor.go:111] Tasks: 0 done / 79 total; 44 can run
W0202 19:53:30.439775    2898 vfs_castore.go:604] CA private key was not found
I0202 19:53:30.466380    2898 keypair.go:195] Issuing new certificate: "etcd-manager-ca-events"
I0202 19:53:30.510242    2898 keypair.go:195] Issuing new certificate: "etcd-clients-ca"
W0202 19:53:30.529367    2898 vfs_castore.go:604] CA private key was not found
I0202 19:53:30.529478    2898 keypair.go:195] Issuing new certificate: "ca"
I0202 19:53:30.549903    2898 keypair.go:195] Issuing new certificate: "apiserver-aggregator-ca"
I0202 19:53:30.651344    2898 keypair.go:195] Issuing new certificate: "etcd-peers-ca-main"
I0202 19:53:30.672308    2898 keypair.go:195] Issuing new certificate: "etcd-manager-ca-main"
I0202 19:53:30.793247    2898 keypair.go:195] Issuing new certificate: "master"
I0202 19:53:30.935434    2898 keypair.go:195] Issuing new certificate: "etcd-peers-ca-events"
I0202 19:53:32.895889    2898 executor.go:111] Tasks: 44 done / 79 total; 15 can run
I0202 19:53:33.685074    2898 executor.go:111] Tasks: 59 done / 79 total; 18 can run
I0202 19:53:34.171323    2898 executor.go:111] Tasks: 77 done / 79 total; 2 can run
I0202 19:53:34.987759    2898 executor.go:137] Task "AutoscalingGroup/master-us-east-2c.masters.sajeer.dev.k8s.sajeer.in" not ready: waiting for the IAM Instance Profile to be propagated
I0202 19:53:34.987971    2898 executor.go:137] Task "AutoscalingGroup/nodes-us-east-2c.sajeer.dev.k8s.sajeer.in" not ready: waiting for the IAM Instance Profile to be propagated
I0202 19:53:34.988091    2898 executor.go:155] No progress made, sleeping before retrying 2 task(s)
I0202 19:53:44.988409    2898 executor.go:111] Tasks: 77 done / 79 total; 2 can run
I0202 19:53:46.328253    2898 executor.go:111] Tasks: 79 done / 79 total; 0 can run
I0202 19:53:46.328444    2898 dns.go:156] Pre-creating DNS records
I0202 19:53:46.970185    2898 update_cluster.go:313] Exporting kubecfg for cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2c56de4]

goroutine 1 [running]:
k8s.io/kops/upup/pkg/fi/cloudup/awstasks.FindElasticLoadBalancerByNameTag(0x476a180, 0xc000d5e780, 0xc00061db00, 0xc000e0e660, 0x18, 0xc000e0f9c0, 0x1c)
        upup/pkg/fi/cloudup/awstasks/dnsname.go:156 +0x84
k8s.io/kops/upup/pkg/fi/cloudup/awstasks.FindDNSName(0x476a180, 0xc000d5e780, 0xc00061db00, 0x476a180, 0xc000d5e780, 0x38501, 0xc000bbd6c8)
        upup/pkg/fi/cloudup/awstasks/dnsname.go:135 +0x90
k8s.io/kops/pkg/commands.(*CloudDiscoveryStatusStore).GetApiIngressStatus(0x660ae18, 0xc00061db00, 0xa, 0xc000e0e700, 0x15, 0xc000bbd790, 0x16)
        pkg/commands/status_discovery.go:56 +0x10e
k8s.io/kops/pkg/kubeconfig.BuildKubecfg(0xc00061db00, 0x46d3c80, 0xc000e133b0, 0x472d8e0, 0xc000e156e0, 0x469a980, 0x660ae18, 0x3aef6cfb4000, 0x0, 0x0, ...)
        pkg/kubeconfig/create_kubecfg.go:74 +0x258
main.RunUpdateCluster(0x46e69c0, 0xc0000540d0, 0xc000585080, 0x7fff5e4927e7, 0x18, 0x4695560, 0xc00000e020, 0xc0003e25a0, 0x5, 0x4131974, ...)
        cmd/kops/update_cluster.go:317 +0x17d8
main.NewCmdUpdateCluster.func1(0xc0003f22c0, 0xc0000a1a80, 0x0, 0x4)
        cmd/kops/update_cluster.go:113 +0x109
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc0003f22c0, 0xc0000a1a40, 0x4, 0x4, 0xc0003f22c0, 0xc0000a1a40)
        vendor/github.com/spf13/cobra/command.go:846 +0x2c2
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x65bfe40, 0x660ae18, 0x0, 0x0)
        vendor/github.com/spf13/cobra/command.go:950 +0x375
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:887
main.Execute()
        cmd/kops/root.go:97 +0x8f
main.main()
        cmd/kops/main.go:24 +0x25

root@ip-:/home/ubuntu# kops validate cluster
Validating cluster dev.k8s.sajeer.in

Validation failed: cannot load kubecfg settings for "dev.k8s.sajeer.in": context "dev.k8s.sajeer.in" does not exist

**Comment by bharath-123** [comment]
How did you create the cluster? Could you share the cluster and instance group spec?

**Comment by bharath-123** [comment]
Please follow this template when raising issues for kOps [issue-template](https://github.com/kubernetes/kops/issues/new?assignees=&labels=&template=bug_report.md)
