### ISSUE TITLE
InstanceGroup name being prepended to externalLoadBalancer name

### ISSUE THREAD

**Issue by kxesd** [kubernetes/kops#10715]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.19.0 (git-04d36d7d92c72601efd918877fc180c846129ffb)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-15T11:35:50Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
a. Add an externalLoadBalancer to an InstanceGroup
b. `kops update cluster mycluster.tld`

**5. What happened after the commands executed?**
```
Will modify resources:
  AutoscalingGroup/nodes-a.mycluster.tld
        LoadBalancers            [] -> [name:nodes-a.mycluster.tld-my-loadbalancer id:nodes-a.mycluster.tld-my-loadbalancer]

4739 executor.go:139] error running task "AutoscalingGroup/nodes-a.mycluster.tld" (9m59s remaining to succeed): error attaching LoadBalancers: ValidationError: Provided Load Balancers may not be valid. Please ensure they exist and try again.
        status code: 400, request id: 792b0944-adf0-4a28-a1cd-eea4c0f2c9e2
```

**6. What did you expect to happen?**
The externalLoadBalancer to be added to the InstanceGroup using the correct name (kOps v1.19.0-beta.3 has the correct name but suffers the bug in #10664)
```
Will modify resources:
  AutoscalingGroup/nodes-a.mycluster.tld
        LoadBalancers            [] -> [name:my-loadbalancer id:my-loadbalancer]
```

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I'm assuming that the fix in #10666 has caused the InstanceGroup name to be prepended to the externalLoadBalancer name.

**Comment by alexandrst88** [comment]
I had the same issue while rolling upgrade, on the bastion instance group 

```
error running tasks: deadline exceeded executing task AutoscalingGroup/bastions.*******.k8s.example.com. Example error: error detatching LoadBalancers: ValidationError: Trying to remove Load Balancers that are not part of the group: AccessPoint(accessPointName=bastions.*******.k8s.example.com-bastion-*******, vpcId=null, accessPointType=LEGACY_ELB)
	status code: 400, request id: 1822ed17-04d2-40e3-83fa-f09d30506a21
```

When I detached LB manually, I got the same error as @kxesd.

```error attaching LoadBalancers: ValidationError: Provided Load Balancers may not be valid. Please ensure they exist and try again```
