### ISSUE TITLE
please enter username

### ISSUE THREAD

**Issue by Maduflavins** [kubernetes/kops#10723]
each time i run any kubectl command i get please enter username this has been happening for the past one week

**Comment by bharath-123** [comment]
Please follow this template when raising issues for kOps so that we can help you better! :) [issue-template](https://github.com/kubernetes/kops/issues/new?assignees=&labels=&template=bug_report.md)

**Comment by h3poteto** [comment]
This is my guess, have you forgotten `--admin` or `--user` flag in commands such as `kops update cluster` ? In 1.19.0, you have to add these flags to export kubernetes config.
https://github.com/kubernetes/kops/releases/tag/v1.19.0

**Comment by Maduflavins** [comment]
@h3poteto thank you it fixed it
