### ISSUE TITLE
New KopsApiServer Config Option: 

### ISSUE THREAD

**Issue by vjm** [kubernetes/kops#1074]
To make setting Kubelet Preferred Address Types for API Server an option. This will pass `--kubelet-preferred-address-types=<option1>,<option2>` to `kube-apiserver`.

This will allow for environments that have a hostname that does not resolve (such as AWS using custom DHCP options) to properly use features such as `kubectl logs` or `kubectl exec`

We'll do this by adding to:
* https://github.com/kubernetes/kops/blob/master/upup/models/config/components/kube-apiserver/kube-apiserver.options
* https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/options/options.go#L111

Original issue that notes this new option in k8s version 1.5: https://github.com/kubernetes/kubernetes/issues/22063#issuecomment-265263414

**Comment by chrislovecnm** [comment]
@vjm we follow a practice of opening a PR with a short paragraph of what you want to do.  From there look at https://github.com/kubernetes/kops/blob/master/docs/development/adding_a_feature.md

Questions?  We have developer office hours this Friday as well.

**Comment by vjm** [comment]
@chrislovecnm I have done some digging and I believe that changes need to be made to:
* https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L370

I made an initial PR that adds the flag, but I'm not seeing it reflected when testing locally. I may be doing something wrong in my tests. Any help?
