### ISSUE TITLE
Deprecate LaunchConfigurations in favour of LaunchTemplates

### ISSUE THREAD

**Issue by bharath-123** [kubernetes/kops#10745]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
AWS strongly recommends to use LaunchTemplates instead of LaunchConfigurations.
xRef: https://docs.aws.amazon.com/autoscaling/ec2/userguide/LaunchConfiguration.html. 

**2. Feel free to provide a design supporting your feature request.**

**Comment by bharath-123** [comment]
cc: @rifelpet

**Comment by hakman** [comment]
We waited for 1.19 release before doing this and see if there are any major issues with LaunchTemplates.

**Comment by bharath-123** [comment]
That's great. Should we discuss this in office hours before beginning work on this?

**Comment by hakman** [comment]
Done as part of #10937
