### ISSUE TITLE
Failure to remove tags from subnets when cluster is deleted, hits AWS tag limit eventually

### ISSUE THREAD

**Issue by UncleEricB** [kubernetes/kops#10769]
1. What kops version are you running? The command kops version, will display this information.
$ kops version
Version 1.19.0-beta.3 (git-e43f1cc6e3c77d093935d1706042861095d75eb7)

2. What Kubernetes version are you running? kubectl version will print the version if a cluster is running or provide the Kubernetes version specified as a kops flag.
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:13:35Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run? What is the simplest way to reproduce this issue?
$ kops delete cluster {cluster name} --yes
Happens on all k8s cluster deletions.

5. What happened after the commands executed?
A large listing of resources was printed out and identified as deleted.  This list did not include subnet tags and possibly other resources that I haven't discovered yet . We recently hit our limit on AWS tags on a subnet shared by our production cluster (3 active) because we spin up and tear down clusters, leaving behind subnet tags.

TYPE			NAME													ID
autoscaling-config	master-us-east-1a.masters.{cluster name}					lt-07b6c003baa78d4d3
autoscaling-config	master-us-east-1b.masters.{cluster name}					lt-01057bcc4279f4edf
autoscaling-config	master-us-east-1d.masters.{cluster name}					lt-031d737f4ce1e56ab
autoscaling-config	nodes-us-east-1a.{cluster name}							lt-01502816929948868
autoscaling-config	nodes-us-east-1b.{cluster name}							lt-06ac1c3bc7a1b5e39
autoscaling-config	nodes-us-east-1d.{cluster name}							lt-059fc63b62346cfd6
autoscaling-group	master-us-east-1a.masters.{cluster name}					master-us-east-1a.masters.{cluster name}
autoscaling-group	master-us-east-1b.masters.{cluster name}					master-us-east-1b.masters.{cluster name}
autoscaling-group	master-us-east-1d.masters.{cluster name}					master-us-east-1d.masters.{cluster name}
autoscaling-group	nodes-us-east-1a.{cluster name}							nodes-us-east-1a.{cluster name}
autoscaling-group	nodes-us-east-1b.{cluster name}							nodes-us-east-1b.{cluster name}
autoscaling-group	nodes-us-east-1d.{cluster name}							nodes-us-east-1d.{cluster name}
iam-instance-profile	masters.{cluster name}								masters.{cluster name}
iam-instance-profile	nodes.{cluster name}								nodes.{cluster name}
iam-role		masters.{cluster name}								masters.{cluster name}
iam-role		nodes.{cluster name}								nodes.{cluster name}
instance		master-us-east-1a.masters.{cluster name}					i-024a0a344ae6f7acb
instance		master-us-east-1b.masters.{cluster name}					i-0b5e6a927ae28a3cc
instance		master-us-east-1d.masters.{cluster name}					i-0ed8e55d3ea0ea88f
instance		nodes-us-east-1a.{cluster name}							i-0f15bce50f130aa4d
instance		nodes-us-east-1b.{cluster name}							i-0cff55fadfff2833a
instance		nodes-us-east-1d.{cluster name}							i-0630361534cc2cc2e
instance		nodes-us-east-1d.{cluster name}							i-085881157bec5e179
keypair			kubernetes.{cluster name}-24:6a:83:b6:e3:e8:d4:27:b2:6c:b7:13:b1:a6:75:19	key-039b54ab4ed97669e
load-balancer		api.{cluster name}								api-stage-119-ephemeral-s-v07rje
route53-record		api.internal.{cluster name}.							Z02210003QXQM5RCJZ0F6/api.internal.{cluster name}.
route53-record		api.{cluster name}.								Z02210003QXQM5RCJZ0F6/api.{cluster name}.
security-group		api-elb.{cluster name}								sg-029a24cdc136eefc1
security-group		masters.{cluster name}								sg-0f06688ae43dd1731
security-group		nodes.{cluster name}								sg-0b9794c60a74311e7
volume			a.etcd-events.{cluster name}							vol-01d38275b52e58d7a
volume			a.etcd-main.{cluster name}							vol-04d394fa0bedaf844
volume			b.etcd-events.{cluster name}							vol-00b3406547187b98d
volume			b.etcd-main.{cluster name}							vol-05722215958ee6c53
volume			d.etcd-events.{cluster name}							vol-0117926f91c09df86
volume			d.etcd-main.{cluster name}							vol-011d4d02575f31d1d
volume			master-us-east-1a.masters.{cluster name}					vol-0741f695eb3df85ac
volume			master-us-east-1b.masters.{cluster name}					vol-0a83425d7b29aeea9
volume			master-us-east-1d.masters.{cluster name}					vol-000f3afcf30b61587
volume			nodes-us-east-1a.{cluster name}							vol-059985914b509f243
volume			nodes-us-east-1b.{cluster name}							vol-0f8b4a719c7d2ec4e
volume			nodes-us-east-1d.{cluster name}							vol-0044d14e7cff0848c
volume			nodes-us-east-1d.{cluster name}							vol-024985e31e21d6836

load-balancer:api-stage-119-ephemeral-s-v07rje	ok
route53-record:Z02210003QXQM5RCJZ0F6/api.internal.{cluster name}.	ok
instance:i-024a0a344ae6f7acb	ok
autoscaling-group:nodes-us-east-1b.{cluster name}	ok
iam-instance-profile:nodes.{cluster name}	ok
iam-instance-profile:masters.{cluster name}	ok
instance:i-0630361534cc2cc2e	ok
autoscaling-config:lt-031d737f4ce1e56ab	ok
autoscaling-config:lt-07b6c003baa78d4d3	ok
autoscaling-config:lt-059fc63b62346cfd6	ok
autoscaling-config:lt-01502816929948868	ok
autoscaling-config:lt-01057bcc4279f4edf	ok
instance:i-085881157bec5e179	ok
autoscaling-config:lt-06ac1c3bc7a1b5e39	ok
volume:vol-04d394fa0bedaf844	ok
volume:vol-011d4d02575f31d1d	ok
instance:i-0b5e6a927ae28a3cc	ok
instance:i-0cff55fadfff2833a	ok
instance:i-0f15bce50f130aa4d	ok
volume:vol-0117926f91c09df86	ok
volume:vol-05722215958ee6c53	ok
instance:i-0ed8e55d3ea0ea88f	ok
volume:vol-00b3406547187b98d	ok
volume:vol-01d38275b52e58d7a	ok
autoscaling-group:nodes-us-east-1d.{cluster name}	ok
autoscaling-group:master-us-east-1a.masters.{cluster name}	ok
autoscaling-group:nodes-us-east-1a.{cluster name}	ok
autoscaling-group:master-us-east-1b.masters.{cluster name}	ok
autoscaling-group:master-us-east-1d.masters.{cluster name}	ok
keypair:key-039b54ab4ed97669e	ok
iam-role:nodes.{cluster name}	ok
iam-role:masters.{cluster name}	ok
volume:vol-024985e31e21d6836	still has dependencies, will retry
volume:vol-0f8b4a719c7d2ec4e	still has dependencies, will retry
volume:vol-000f3afcf30b61587	still has dependencies, will retry
volume:vol-059985914b509f243	still has dependencies, will retry
volume:vol-0044d14e7cff0848c	still has dependencies, will retry
volume:vol-0a83425d7b29aeea9	still has dependencies, will retry
volume:vol-0741f695eb3df85ac	still has dependencies, will retry
security-group:sg-029a24cdc136eefc1	still has dependencies, will retry
security-group:sg-0f06688ae43dd1731	still has dependencies, will retry
security-group:sg-0b9794c60a74311e7	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	volume:vol-059985914b509f243
	volume:vol-0f8b4a719c7d2ec4e
	volume:vol-000f3afcf30b61587
	volume:vol-0a83425d7b29aeea9
	volume:vol-024985e31e21d6836
	volume:vol-0044d14e7cff0848c
	security-group:sg-029a24cdc136eefc1
	security-group:sg-0b9794c60a74311e7
	security-group:sg-0f06688ae43dd1731
	volume:vol-0741f695eb3df85ac
volume:vol-0044d14e7cff0848c	ok
volume:vol-0f8b4a719c7d2ec4e	still has dependencies, will retry
volume:vol-059985914b509f243	still has dependencies, will retry
volume:vol-0741f695eb3df85ac	still has dependencies, will retry
volume:vol-0a83425d7b29aeea9	still has dependencies, will retry
security-group:sg-029a24cdc136eefc1	still has dependencies, will retry
security-group:sg-0f06688ae43dd1731	still has dependencies, will retry
security-group:sg-0b9794c60a74311e7	still has dependencies, will retry
volume:vol-000f3afcf30b61587	still has dependencies, will retry
volume:vol-024985e31e21d6836	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	volume:vol-059985914b509f243
	volume:vol-0f8b4a719c7d2ec4e
	volume:vol-000f3afcf30b61587
	volume:vol-0a83425d7b29aeea9
	volume:vol-024985e31e21d6836
	security-group:sg-029a24cdc136eefc1
	security-group:sg-0b9794c60a74311e7
	security-group:sg-0f06688ae43dd1731
	volume:vol-0741f695eb3df85ac
volume:vol-0a83425d7b29aeea9	ok
volume:vol-024985e31e21d6836	still has dependencies, will retry
volume:vol-0741f695eb3df85ac	still has dependencies, will retry
volume:vol-000f3afcf30b61587	still has dependencies, will retry
volume:vol-059985914b509f243	still has dependencies, will retry
volume:vol-0f8b4a719c7d2ec4e	still has dependencies, will retry
security-group:sg-0f06688ae43dd1731	still has dependencies, will retry
security-group:sg-029a24cdc136eefc1	still has dependencies, will retry
security-group:sg-0b9794c60a74311e7	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	volume:vol-0f8b4a719c7d2ec4e
	volume:vol-000f3afcf30b61587
	volume:vol-024985e31e21d6836
	security-group:sg-029a24cdc136eefc1
	security-group:sg-0f06688ae43dd1731
	security-group:sg-0b9794c60a74311e7
	volume:vol-0741f695eb3df85ac
	volume:vol-059985914b509f243
volume:vol-059985914b509f243	ok
volume:vol-0f8b4a719c7d2ec4e	ok
volume:vol-024985e31e21d6836	still has dependencies, will retry
volume:vol-000f3afcf30b61587	still has dependencies, will retry
volume:vol-0741f695eb3df85ac	still has dependencies, will retry
security-group:sg-0b9794c60a74311e7	still has dependencies, will retry
security-group:sg-0f06688ae43dd1731	still has dependencies, will retry
security-group:sg-029a24cdc136eefc1	ok
Not all resources deleted; waiting before reattempting deletion
	security-group:sg-0b9794c60a74311e7
	security-group:sg-0f06688ae43dd1731
	volume:vol-0741f695eb3df85ac
	volume:vol-000f3afcf30b61587
	volume:vol-024985e31e21d6836
volume:vol-024985e31e21d6836	still has dependencies, will retry
volume:vol-0741f695eb3df85ac	ok
volume:vol-000f3afcf30b61587	ok
security-group:sg-0f06688ae43dd1731	still has dependencies, will retry
security-group:sg-0b9794c60a74311e7	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	volume:vol-024985e31e21d6836
	security-group:sg-0f06688ae43dd1731
	security-group:sg-0b9794c60a74311e7
volume:vol-024985e31e21d6836	ok
security-group:sg-0f06688ae43dd1731	ok
security-group:sg-0b9794c60a74311e7	ok

6. What did you expect to happen?
I expected that **all** resources created by kOps during kops create cluster could be deleted on kops delete cluster.  This includes all subnet tags.  I don't see a reference in the documentation that subnet tags are not cleaned up on cluster deleteion.  https://kops.sigs.k8s.io/run_in_existing_vpc/#subnet-tags

7. Please provide your cluster manifest. Execute kops get --name my.example.com -o yaml to display your cluster manifest.
You may want to remove your cluster name and other sensitive information.

$ kops get --name {cluster name} -o yaml --state=s3://{our kOps state bucket}

Cluster.kops.k8s.io "{cluster name}" not found

This further indicates to me that everything related to this cluster was deleted.

8.  Anything else we need to know?
I had a brief conversation in slack with someone who indicated I have to manually clean up subnet tags myself.  This matches what I'm seeing.  I don't understand the logic presented here.  If kOps is able to add tags to a shared subnet then it should be able to remove those same tags.

Eric Blumenau Feb 5th at 8:37 AM
We just reached our AWS tag limit for a bunch of VPC subnets when I tried to create a new cluster.  The limit is 50.  Looking at the tags, they've been accruing for maybe two years.  Why aren't they deleted when we take down the cluster with kops delete cluster {cluster name} --yes?  The accrual of tags spans a few versions of kops so I can't limit it to only 1.19 or 1.18.  Has anyone else seen this?

Ole Markus  3 days ago
Shared subnet?

Eric Blumenau  3 days ago
Ah, yes.  We have a 1a-subnet, 1b-subnet and 1d-subnet and they are used by all clusters.
I guess we could spin up new subnets for each cluster but isn't that just kicking the can down the road?  We'll hit 50 tags eventually either way.

Ole Markus  3 days ago
Reason I asked is that cleaning up stuff on shared subnets is something you have to do yourself. Kops won't do it for safety reasons

**Comment by jamal-superbet** [comment]
We hit this issue. The fix for us is related to the clusterSpec changes here https://github.com/kubernetes/kops/commit/6fb2cd5aa3fed6474838716231d0cd1d03c2c62f

We needed to add an additional field to 
DisableSubnetTags: true as shown below - in a later version this field changes to TagSubnets: false
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: 
spec:
  DisableSubnetTags: true
 ...
```
