### ISSUE TITLE
Linux AMD64 binary is missing from release v1.20.0-alpha.2 

### ISSUE THREAD

**Issue by rochacon** [kubernetes/kops#10773]
Basically the title. The release for v1.20.0-alpha.2 seems to not include the `kops-linux-amd64` binary. 

Corresponding SHA256 file: https://github.com/kubernetes/kops/releases/download/v1.20.0-alpha.2/kops-linux-amd64.sha256
Missing binary: https://github.com/kubernetes/kops/releases/download/v1.20.0-alpha.2/kops-linux-amd64

**Comment by hakman** [comment]
Sorry for that. Please give it a try now.

**Comment by rochacon** [comment]
LGTM, thanks!

```
% wget -O kops-1.20.0-alpha.2 https://github.com/kubernetes/kops/releases/download/v1.20.0-alpha.2/kops-linux-amd64
chmod +x kops-1.20.0-alpha.2
% ./kops-1.20.0-alpha.2 version
Version 1.20.0-alpha.2 (git-3673b6e7f8f85311333c4a9fa65ccba3fe1ad251)
```
