### ISSUE TITLE
Kops poll objects / AWS Objects & IDs Manifest

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1077]
After a call with @kris-nova @justinsb @zmerlynn @chrislovecnm 

We have a use case to poll objects and their IDs out of the AWS API based on a **cluster name** 

The poll should produce some manifest at time of polling that offers AWS objects and their IDs found by cluster name tags, and associated cluster name tags.

This feature can be used in a separate feature to validate that a cluster has been successfully deleted.

**Comment by chrislovecnm** [comment]
A example of data that we require.

1. `kubectl describe po` <- determine node
2. ssh to node
3. sudo df -h <- determine if drive is mounted
4. collect all logs off of node
5. determine which controller is active, the master is annotate with which controller is active
6. collect all logs off of the master
7. cloud trail from system as well

**Comment by justinsb** [comment]
First step in #1274 

@chrislovecnm what you're asking for feels like a separate thing, and I think is already part of e2e

**Comment by kris-nova** [comment]
@chrislovecnm  @justinsb 

I agree with Justin, my original thought here was to have an accurate manifest of meta information about kops objects and how they map to cloud resources and nothing more. Not saying that having monitoring something or other with kops is necessarily out of the picture, just don't want to get it confused with what we are thinking here.
