### ISSUE TITLE
Kops fail to start cluster if Nvidia hook is used

### ISSUE THREAD

**Issue by atam003** [kubernetes/kops#10783]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
kops1.19

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Kubernetes 1.16

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Mentioned Nvidia hook as follows -
 hooks:
  - execContainer:
      image: atagrawal/nvidia-device-plugin:0.1.0-cuda10.1

More detail for hook can be seen https://github.com/kubernetes/kops/tree/master/hooks/nvidia-device-plugin 

**5. What happened after the commands executed?**
Nvidia hook try to install Nvidia docker as follows -
apt-get install -y --allow-downgrades -o Dpkg::Options::="--force-confold" \
  nvidia-docker2=2.0.3+docker18.09.4-1 \
  nvidia-container-runtime=2.0.0+docker18.09.4-1 \
  docker-ce=5:18.09.4~3-0~debian-stretch

**6. What did you expect to happen?**
Cluster should start successfully

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2020-09-27T23:41:29Z
  labels:
    kops.k8s.io/cluster: atam-cluster.k8s.local
  name: nodes
spec:
  cloudLabels:
  # add user configured labels to the nodes
    "Test Tag3": "@yahoo.com"
    "TestTag4": "1234567890"
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2021-02-05
  hooks:
  - execContainer:
      image: atagrawal/nvidia-device-plugin:0.1.0-cuda10.1
  machineType: g4dn.2xlarge
  maxSize: 2
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-west-1b
  - us-west-1c
  
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
kubedns pod fail to start due to docker issue with an error 
Warning  FailedCreatePodSandBox  2m (x13 over 2m)  kubelet, ip-172-20-32-188.ec2.internal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-dns-56b4d4fc4-zzvv7": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:334: running prestart hook 0 caused \"fork/exec /usr/bin/dockerd (deleted): no such file or directory\""

![image](https://user-images.githubusercontent.com/38551619/107567971-38ae9300-6b9b-11eb-96ea-7a4f39f886c8.png)

**9. Anything else do we need to know?**

**Comment by atam003** [comment]
@hakman 
This issue can be related with recent change for docker. Can you please help with proposed solution for it.

**Comment by olemarkus** [comment]
The nvidia hook isn't maintained anymore. Try the GPU operator https://kops.sigs.k8s.io/gpu/

**Comment by atam003** [comment]
I understand, Though replacing to GPU operator is really a challenge for us as it will require helm.
I want to classify this issue as very generic level. it can fail when any hook or user script try to install docker.
What is the suggestion in that case.

**Comment by hakman** [comment]
@atam003 main thing would be NOT to use the kope.io image. Use the generic/official [Debian N image](https://kops.sigs.k8s.io/operations/images/#debian-9-stretch).
If you don't want kOps to install Docker, set the (skipInstall flag)[https://kops.sigs.k8s.io/cluster_spec/#skip-install].

**Comment by atam003** [comment]
@hakman Thanks, will try that. 
@olemarkus  I have one more question. I see we have marked
