### ISSUE TITLE
Once cluster autoscaler enabled in spec.clusterAutoscaler, there is not way to disable it.

### ISSUE THREAD

**Issue by shamil** [kubernetes/kops#10792]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Version 1.19.0 (git-04d36d7d92c72601efd918877fc180c846129ffb)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

`aws`

**4. What happened?**

I've enabled cluster autoscaler in `spec.clusterAutoscaler`, which caused for autoscaler to be provisioned by `kops`.
Later I decided to disable it, again in `spec.clusterAutoscaler`. But `kops` kept it running, and I needed to manually remove all the cluster-autoscaler related resources.

Obviously I ran `kops update cluster` each time after I made a change in the cluster spec.

**5. What did you expect to happen?**

I expected that when I disable cluster autoscaler in cluster spec, it will be un-provisioned by `kops`

**6. Anything else do we need to know?**

Unrelated, but seems like `kops` configures autoscaler for all instance groups, regardless if I need that or not. Couldn't find a documentation which explains how to avoid this. I'd like instead to use `--node-group-auto-discovery` option.

**Comment by olemarkus** [comment]
For the main issue: kOps does not uninstall addons. It is a missing feature as such

For the unrelated issue: auto-discovery is an AWS-only feature so kops will not be using that. Making it possible to disable CAS for some IGs is possible though. Would be happy to review a PR for that.

**Comment by shamil** [comment]
Thanks @olemarkus for quick response.
I'm aware that auto discovery works in AWS only. But since `kops` allows me to pass arguments as part of the spec, I can do it without having `kops` to support it natively. 

The fact that I can't disable `kops` from adding the arguments of the IGs, is what preventing me from using `auto-discovery`. My current solution is just use a manually installed cluster autoscaler from helm chart.

**Comment by olemarkus** [comment]
/remove-lifecycle rotten

I am working on a way to get addons uninstalled. First step is tracking resources and deleting dangling resources when we e.g rename something. Second step is to uninstall addons. Both things may make it into 1.22.
