### ISSUE TITLE
Kops diagnostics 

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1079]
New kops feature.. we need to get diagnostics information from a running (and potentially broken/buggy) cluster

**This feature needs to work when the API is down**

### Details

- Node detail
- Master detail
- IGs in general
- Full log dump 

Others?

### Features

- Remote dumping in state store
- Pulling data over SSH not over HTTPs (solves broken API problems)

CC @kris-nova @chrislovecnm @justinsb @zmerlynn

**Comment by chrislovecnm** [comment]
Kubectl cluster info
Syslogs
Kubectl logs
Versions of components
Kops version
Profile of servers - mem, CPU, disk
docker info
kernel version
Network info

Master
- all logs for components

**Comment by justinsb** [comment]
1.5.0, but I suspect we'll punt to 1.5.1

**Comment by justinsb** [comment]
We do have the terribly named `kops toolbox dump`, but this feels much deeper...

**Comment by kenden** [comment]
Would `kops validate cluster` be enough?
