### ISSUE TITLE
Weave manifest version `1.8.1.20161130` is invalid?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1081]
Seeing this...

```
W1207 02:01:39.194050    1163 channel_version.go:100] error parsing version "1.8.1.20161130"; will ignore this version
No update required
```

**Comment by justinsb** [comment]
cc @chrislovecnm

**Comment by chrislovecnm** [comment]
I am using it... Will check... Hrm

**Comment by chrislovecnm** [comment]
So what format of version is this expecting?? 
```
// Parse parses version string and returns a validated Version or error
func Parse(s string) (Version, error) {
```

semver.go line 227

I will dig into the semver package....

**Comment by chrislovecnm** [comment]
So semver is expecting a version like k8s.  We need to not have the date in the filename.  We will need to update the manifests.  Can our system rename the file before it uploads it up?

**Comment by itsmrwave** [comment]
@justinsb Feel free to close this, https://github.com/kubernetes/kops/pull/1250 has been merged in.
