### ISSUE TITLE
Can I add calicoctl installs to the kops LaunchConfigurations directly?

### ISSUE THREAD

**Issue by karenin-overseas** [kubernetes/kops#10889]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
We recently changed our networking provider from `kubenet` to `calico`, following the docs: https://kops.sigs.k8s.io/networking/calico/

Calico has a monitoring tool called `calicoctl` that I'd like to be able to use on kops-managed nodes: https://docs.projectcalico.org/getting-started/clis/calicoctl/install. 

When I ssh onto a kops-managed k8s node or master and invoke calicoctl, it doesn't seem to be installed or in the user's PATH by default.

**2. Feel free to provide a design supporting your feature request.**
I see a couple of options:
0. kops could add a `calicoctl` install to the default LaunchConfiguration for nodes/masters if the networking provider is calico.

As a workaround, I could
1. Mutate the LaunchConfiguration for nodes myself
2. Use the calicoctl k8s deployment instead -- trying this naively leads me to the same error as https://github.com/kubernetes/kops/issues/7140 though

**Comment by hakman** [comment]
To answer the title question, you cannot add calicoctl to LC directly.
You could though this to download it easily:
https://kops.sigs.k8s.io/instance_groups/#additionaluserdata
https://kops.sigs.k8s.io/cluster_spec/#hooks

**Comment by karenin-overseas** [comment]
Thanks! I'll give that a shot

**Comment by hamedsol** [comment]
> Thanks! I'll give that a shot

Hi couls you get through that ?
