### ISSUE TITLE
Issue creating cluster using existing VPC and subnets

### ISSUE THREAD

**Issue by danfinn** [kubernetes/kops#10901]
```
/Applications/kops version
Version 1.18.2 (git-84495481e4)
```

The team that is in charge of our AWS environment setup would prefer that we use kOps with an existing VPC and subnets if possible.  They created a VPC and 2 subnets.  I used the following command to try and create a cluster with kOps:

```
/Applications/kops create cluster --node-count=3 --node-size=t2.medium --zones=us-east-2a --name=${KOPS_CLUSTER_NAME} --vpc=vpc-00fba0867673b3a64 --topology private --networking weave --subnets=subnet-03619f55905b3f435,subnet-03b211bd659379a1f
```

And I get the following output:
```
I0222 14:20:39.034491    7551 create_cluster.go:555] Inferred --cloud=aws from zone "us-east-2a"
I0222 14:20:40.305243    7551 subnets.go:198] Assigned CIDR 10.160.32.0/22 to subnet utility-us-east-2a

spec.subnets[1].id: Forbidden: cannot mix subnets with specified ID and unspecified ID
```

I've found a few other people reporting this but there doesn't seem to be any suggested fixes or workarounds.

**Comment by olemarkus** [comment]
You need to specify `--utility-subnets` as well.

`kops create cluster` should probably require this when `--topology=private`

**Comment by danfinn** [comment]
Thanks @olemarkus.  It's not entirely clear to me how to setup these subnets when trying to create a private cluster.  Is there a good break down of how subnets vs utility subnets are used or should be laid out?

**Comment by danfinn** [comment]
I tried splitting up the subnets, one for --subnets and one for --utility-subnets and I still get the same error

```
/Applications/kops create cluster --node-count=3 --node-size=t2.medium --zones=us-east-2a --name=${KOPS_CLUSTER_NAME} --vpc=vpc-00fba0867673b3a64 --topology private --networking weave --subnets=subnet-03619f55905b3f435 --utility-subnets=subnet-03b211bd659379a1f
I0223 10:37:45.069000   53936 create_cluster.go:555] Inferred --cloud=aws from zone "us-east-2a"
I0223 10:37:46.469583   53936 subnets.go:198] Assigned CIDR 10.160.32.0/22 to subnet utility-us-east-2a

spec.subnets[1].id: Forbidden: cannot mix subnets with specified ID and unspecified ID
```

**Comment by olemarkus** [comment]
I recommend using a cluster spec file for creating the cluster rather than using `kops create cluster`. See https://kops.sigs.k8s.io/manifests_and_customizing_via_api/

Kops and k8s need some specific tagging on various resources. Easiest is to provision everything with kops first, then copy what kops did.

**Comment by danfinn** [comment]
I actually was just doing some work on this and ended up getting it working using exactly that.  The biggest issue we were having at first when letting kOps create the subnets is that it was trying to use huge subnets, /19 and /22 if I remember correctly.

So what we did was create a cluster like so:
```
/Applications/kops create cluster --node-count=3 --node-size=t2.medium --zones=us-east-2a --name=${KOPS_CLUSTER_NAME} --vpc=vpc-00fba0867673b3a64 --topology private --networking weave
```

then edit the cluster:
```
/Applications/kops edit cluster ${CLUSTER_NAME}
```

And change both subnets to use a /24 instead.  kOps then successfully created the new subnets at a more reasonable size and things are looking good.

It does seem redundant to me to have to run 2 commands, 1 to create the cluster config and 1 to then modify that config.  I'd prefer to just be able to do this with 1 command on the CLI.

**Comment by olemarkus** [comment]
`kops create cluster` is more just for getting a working cluster up and running.

For real use, you should only use the yaml resources. You can use `kops create -f <yaml>` to create clusters based on those.

That way you can check in those yamls into version control.

**Comment by danfinn** [comment]
ok, thank you very much for all the help.

**Comment by olemarkus** [comment]
I'll close this for now. Let me know if you run into more issues.
