### ISSUE TITLE
Why does kops create two scaling groups?

### ISSUE THREAD

**Issue by sujeet-agrahari** [kubernetes/kops#10916]
I have a cluster with two worker nodes and one master node in only one availability zone on AWS.

By default, kops created two auto scaling groups: one for master node and one for worker nodes.

Why does it need two auto scaling group if cluster is running inside on zone only?

Can I somehow merge them into one auto scaling group?

Also, will AWS charge for these separate scaling groups?

One more thing, It also create a load balancer, what is the use of this load balancer? Is it publicly accessible?

**Comment by hakman** [comment]
I think most of these questions are answered in the docs.

#### Why does it need two auto scaling group if cluster is running inside on zone only?
https://kops.sigs.k8s.io/instance_groups/#the-instancegroup-resource
> The InstanceGroup resource represents a group of similar machines typically provisioned in the same availability zone. On AWS, instance groups map directly to an autoscaling group.

#### Can I somehow merge them into one auto scaling group?
No

#### Also, will AWS charge for these separate scaling groups?
https://aws.amazon.com/autoscaling/pricing/

#### One more thing, It also create a load balancer, what is the use of this load balancer? Is it publicly accessible?
Depends on how you created the cluster: https://kops.sigs.k8s.io/cluster_spec/#api

**Comment by sujeet-agrahari** [comment]
Thanks @hakman 
You answer for _Why does it need two auto scaling group if cluster is running inside one zone only?_  doesnt actually explains the why part.
_Also, will AWS charge for these separate scaling groups?_ So it doesn't charge! Correct me here if I am wrong.

_One more thing, It also create a load balancer, what is the use of this load balancer? Is it publicly accessible?_

So kops create load balancer inside VPC so that it can communicate to master node?

**Comment by sujeet-agrahari** [comment]
Thanks @hakman 
You answer for _Why does it need two auto scaling group if cluster is running inside one zone only?_  doesnt actually explains the why part.
_Also, will AWS charge for these separate scaling groups?_ So it doesn't charge! Correct me here if I am wrong.

_One more thing, It also create a load balancer, what is the use of this load balancer? Is it publicly accessible?_

So kops create load balancer inside VPC so that it can communicate to master node?

**Comment by hakman** [comment]
> ... doesnt actually explains the why part.

Masters and nodes are different things, running different services, with different IAM permissions so require different ASGs.
Masters use fixes size ASG of 1, to be recreated in case of failure, nodes can be scaled as much as you want.

> So kops create load balancer inside VPC so that it can communicate to master node?

kOps creates a load balancer for HA user access to the nodes. It is a preference if you want to use LB or DNS, internal or not, both depending on your cluster architecture.
