### ISSUE TITLE
error updating "storage-aws.addons.k8s.io"

### ISSUE THREAD

**Issue by 7echno** [kubernetes/kops#10917]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.18.2 (git-84495481e4)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.17.11

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Error is logged in journald. It happened during storage AWS add-on update.
Seems that if your gp2 storage class policy is set to Retain like in our case 'reclaimPolicy: Retain', updating from storage aws addon **v1.7.0** to **v.1.15.0** is not passing (seems only gp2 part) as it's trying to update from '**Retain**' back to '**Delete**', I guess.
Which is **forbidden**.
This seems to be a specific case, as we just discovered it recently on one of our clusters that has '**Retain**' policy on gp2.
 
Not sure if there is a easy way to workaround this, as this update seems to be running in loop and we keep getting this error in our log. What we are afraid is that at one point there could be a important change pushed through this add-on to gp2 and this will be a blocker.
Can you suggest workaround to fix this ? 

**Additionally from journald:
`Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: I0224 10:56:12.065390    2344 addon.go:140] Applying update from "s3://839997660733.eu-central-1/kops/red.dev.k8s.tda.link/addons/storage-aws.addons.k8s.io/v1.15.0.yaml"
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: I0224 10:56:12.065440    2344 s3fs.go:290] Reading file "s3://839997660733.eu-central-1/kops/red.dev.k8s.tda.link/addons/storage-aws.addons.k8s.io/v1.15.0.yaml"
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: I0224 10:56:12.076847    2344 apply.go:67] Running command: kubectl apply -f /tmp/channel150594244/manifest.yaml
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: I0224 10:56:12.321534    2344 apply.go:70] error running kubectl apply -f /tmp/channel150594244/manifest.yaml
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: I0224 10:56:12.321552    2344 apply.go:71] storageclass.storage.k8s.io/default unchanged
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: storageclass.storage.k8s.io/kops-ssd-1-17 unchanged
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: clusterrole.rbac.authorization.k8s.io/system:aws-cloud-provider unchanged
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: clusterrolebinding.rbac.authorization.k8s.io/system:aws-cloud-provider unchanged
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: The StorageClass "gp2" is invalid: reclaimPolicy: Forbidden: updates to reclaimPolicy are forbidden.
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: Error: error updating "storage-aws.addons.k8s.io": error applying update from "s3://839997660733.eu-central-1/kops/red.dev.k8s.tda.link/addons/storage-aws.addons.k8s.io/v1.15.0.yaml": error running kubectl
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: Usage:
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:   channels apply channel [flags]
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: Flags:
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:   -f, --filename strings   Apply from a local file
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:   -h, --help               help for channel
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --yes                Apply update
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: Global Flags:
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --add_dir_header                   If true, adds the file directory to the header
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --alsologtostderr                  log to standard error as well as files
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --config string                    config file (default is $HOME/.channels.yaml)
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --log_dir string                   If non-empty, write log files in this directory
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --log_file string                  If non-empty, use this log file
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --log_file_max_size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --logtostderr                      log to standard error instead of files (default true)
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --skip_headers                     If true, avoid header prefixes in the log messages
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --skip_log_headers                 If true, avoid headers when opening log files
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:   -v, --v Level                          number for the log level verbosity (default 0)
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]:       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: error updating "storage-aws.addons.k8s.io": error applying update from "s3://839997660733.eu-central-1/kops/red.dev.k8s.tda.link/addons/storage-aws.addons.k8s.io/v1.15.0.yaml": error running kubectl
Feb 24 10:56:12 ip-10-80-0-170 docker[3118]: W0224 10:56:12.323870    3155 kube_boot.go:173] error applying channel "s3://839997660733.eu-central-1/kops/red.dev.k8s.tda.link/addons/bootstrap-channel.yaml": error running channels: exit status 1`

**Comment by olemarkus** [comment]
The easiest way to solve this is to remove the storageclass and then kops will readd it shortly after. Pods using the storage class won't be able to start meanwhile, but should fix itself after a about a minute.

**Comment by 7echno** [comment]
@olemarkus This is something that we kind of planned to do. But there are few things I need to be sure.

**Comment by 7echno** [comment]
As suggested I removed "gp2 storageclass", and it this 'issue' is gone after update. Still we switched everything to our "custom" storage class just to be safe in future.
