### ISSUE TITLE
Scheduler addon needs updated yaml policy when using k8s 1.20

### ISSUE THREAD

**Issue by kesor** [kubernetes/kops#10927]
**1. What `kops` version are you running?**
`Version 1.20.0-beta.1`

**2. What Kubernetes version are you running?**
`Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}`

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?**
Created a cluster with the following cluster spec snippet:
```
spec:
  kubeScheduler:
    usePolicyconfigMap: true
```

**5. What happened after the commands executed?**
`scheduler` addon was used, and created the `scheduler-policy` configmap according to the contents of https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/scheduler.addons.k8s.io/v1.7.0.yaml

The `kube-scheduler` crashed and panicked, since the content of that YAML does not work in Kubernetes anymore. https://github.com/kubernetes/kubernetes/issues/99306

**6. What did you expect to happen?**
Kops to apply an appropriate `scheduler-policy`, or even better, to have a way to configure the content of this policy via the kops cluster spec so that it could be fixed to correct values.

**Comment by bharath-123** [comment]
I think allowing users to provide the scheduler-policy is a better option rather than depending on add-ons in this case. I can see that the scheduler policy is constantly evolving, it maybe hard for us to keep up. What do you think @olemarkus ?

**Comment by bharath-123** [comment]
Looks like kOps had support for this but was changed to add it as a dynamic add on. Will discuss this in office hours

/kind office-hours
