### ISSUE TITLE
Error reading cluster configuration "kops.samdevopsinuse.ml": error reading s3://kops.samdevopsinuse.ml/kops.samdevopsinuse.ml/config: Unable to list AWS regions: AuthFailure: AWS was not able to validate the provided access credentials         status code: 401, request id: b80890d3-535c-4f18-81e8-00945c8d26c7

### ISSUE THREAD

**Issue by samturton2** [kubernetes/kops#10930]
**1.** `kops ` version - 1.19.0

**2.** `kubectl` version - 1.19.3

**3.** I am new to kubernetes and trying to launch a simple terraform file that will create 2 nodes with a master node. I have set up a DNS with route53, and an s3 bucket, along with my IAM user container most of the `FullAccess` permissions.

Kops seems to not be able to locate the region, and has authentication errors, which confuses me because when i run `aws s3 ls` it lists my s3 bucket fine, so its definately configured correctly.

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```bash
kops create cluster \
--name=kops.samdevopsinuse.ml \
--state=s3://kops.samdevopsinuse.ml \
--authorization RBAC \
--zones=eu-west-1b \
--node-count=2 \
--master-count=1 \
--node-size=t2.micro \
--master-size=t2.micro \
--dns-zone=kops.samdevopsinuse.ml \
--out=samdevopsinuse_terraform \
--target=terraform \
--ssh-public-key=~/.ssh/samdevopsinuse.pub
```

**5. What happened after the commands executed?**
```
I0225 17:02:30.400979    5300 create_cluster.go:717] Using SSH public key: C:\Users\Sam Turton/.ssh/samdevopsinuse.pub

error reading cluster configuration "kops.samdevopsinuse.ml": error reading s3://kops.samdevopsinuse.ml/kops.samdevopsinuse.ml/config: Unable to list AWS regions: AuthFailure: AWS was not able to validate the provided access credentials
        status code: 401, request id: b80890d3-535c-4f18-81e8-00945c8d26c7
```

**9. Anything else do we need to know?**
It may not be a bug, i may be just doing something wrong.

**Comment by msidwell** [comment]
Hey there! Did you make sure to export your access key ID and secret key as environment variables? kOps is only able to leverage your configured IAM user through this method (https://kops.sigs.k8s.io/getting_started/aws/):

# Because "aws configure" doesn't export these vars for kops to use, we export them now
export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)

**Comment by samturton2** [comment]
Thankyou, that fixes it. I had environment variables but they were labelled differently

Unfortunately now i am getting problems with my DNS name i have in a route53 group, with the name servers added to the domain host. 

```bash
I0302 17:37:53.391915   28452 create_cluster.go:717] Using SSH public key: C:\Users\Sam Turton/.ssh/samdevopsinuse.pub
I0302 17:37:54.343554   28452 new_cluster.go:231] Inferred "aws" cloud provider from zone "us-west-2a"
I0302 17:37:55.174676   28452 subnets.go:180] Assigned CIDR 172.20.32.0/19 to subnet us-west-2a

error doing DNS lookup for NS records for "kops.samdevopsinuse.ml": lookup kops.samdevopsinuse.ml: dnsquery: DNS name does not exist.
```

**Comment by msidwell** [comment]
kops.samdevopsinuse.ml doesn't appear to be a public DNS zone. If you wish to use public DNS, you'll have to create a public route53 hosted zone by purchasing the samdevopsinuse.ml domain. If you just want to try out kOps without dealing with buying a domain name, you can leverage gossip DNS by using a domain name that ends with .k8s.local instead.

https://kops.sigs.k8s.io/gossip
