### ISSUE TITLE
sysctlParameters isn't working

### ISSUE THREAD

**Issue by revandarth** [kubernetes/kops#10933]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.18.2 (git-84495481e4)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

k8s: "v1.18.10"

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops edit ig nodes-us-east-1a`

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-11-19T20:55:19Z"
  generation: 7
  labels:
    kops.k8s.io/cluster: k8s.revan.com
  name: nodes-us-east-1a
spec:
  image: ami-006c88b6ca69f7811
  machineType: m5.2xlarge
  maxSize: 50
  minSize: 1
  nodeLabels:
    Platform: MESH
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  subnets:
  - us-east-1a
  sysctlParameters:
  - net.ipv4.tcp_fin_timeout=30
  - net.core.netdev_budget=600
  - net.core.dev_weight=128
  - net.ipv4.tcp_rmem='4096 1048576 16777216'
```

```
./kops-linux-amd64 update cluster k8s.revan.com

*********************************************************************************

A new kubernetes version is available: 1.18.15
Upgrading is recommended (try kops upgrade cluster)

More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_k8s.md#1.18.15

*********************************************************************************
I0225 21:17:01.108649   10509 executor.go:103] Tasks: 0 done / 107 total; 49 can run
I0225 21:17:01.552869   10509 executor.go:103] Tasks: 49 done / 107 total; 26 can run
I0225 21:17:01.844494   10509 executor.go:103] Tasks: 75 done / 107 total; 22 can run
I0225 21:17:03.051955   10509 executor.go:103] Tasks: 97 done / 107 total; 10 can run
I0225 21:17:03.363589   10509 executor.go:103] Tasks: 107 done / 107 total; 0 can run
No changes need to be applied
```

**5. What happened after the commands executed?**

  changes in ig have not been detected

**6. What did you expect to happen?**
Should show change details and allow to rollout changes to instancegroup

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
OS: flatcar

**Comment by olemarkus** [comment]
unfortunately not all changes to the cluster spec will be detected by kops CLI. You can add `--force` to push the change through.
