### ISSUE TITLE
SSL certificate get expired after some amount of time

### ISSUE THREAD

**Issue by disapointmntPanda** [kubernetes/kops#10947]
I am running latest stable version of kops.

I have two worker and one master node setup in the cluster.

After some amount of time my access to kubectl and the cluster context gets expired.
I get below error

```
[ec2-user@ip-172-31-some-89 ~]$ kubectl get pods
error: You must be logged in to the server (Unauthorized)
```

At his poin I had do again this to access the cluster with kubectl again.

```
 kops update cluster --name some.k8s.local --yes --admin
```

**Comment by olemarkus** [comment]
Yes. Certificates are only valid for 18h by default for security reasons. See https://kops.sigs.k8s.io/releases/1.19-notes/#changes-to-kubernetes-config-export

**Comment by disapointmntPanda** [comment]
> Yes. Certificates are only valid for 18h by default for security reasons. See https://kops.sigs.k8s.io/releases/1.19-notes/#changes-to-kubernetes-config-export

Is there any workaround? And also, is there any side effect of running
```
kops update cluster --name some.k8s.local --yes
```
What is the right way to make it working again?

**Comment by olemarkus** [comment]
Both of those questions are answered in the link above I guess. `kops export kubecfg` is probably the most appropriate command.

Note that using the admin credentials is discouraged

**Comment by disapointmntPanda** [comment]
I did run the below command but I still get the same error.
```
kops export kubecfg --state=s3://kops-state-store
```

**Comment by olemarkus** [comment]
You need to add `--admin`

**Comment by JhwuGit** [comment]
> Yes. Certificates are only valid for 18h by default for security reasons. See https://kops.sigs.k8s.io/releases/1.19-notes/#changes-to-kubernetes-config-export

I tried to set the duration to longer but failed, is the duration fixed to 18h? :

kops export kubecfg --admin duration=48h0m0s

error reading cluster configuration: Cluster.kops.k8s.io "duration=48h0m0s" not found

**Comment by rifelpet** [comment]
@JhwuGit the syntax is `kops export kubecfg --admin=48h`
