### ISSUE TITLE
e2e tests aren't working due to broken link

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kops#1094]
The link below return 404 error
https://raw.githubusercontent.com/kubernetes/kubernetes/master/hack/jenkins/e2e-runner.sh

**Comment by chrislovecnm** [comment]
Need more info please :)

cc: @zmerlynn

**Comment by zmerlynn** [comment]
I think this is referring to https://github.com/kubernetes/kops/blob/master/e2e/runtests.sh#L96, but this is where one of us needs to provide more documentation on how to actually run them the "sanctioned" way using `hack/e2e.go`. This script is bit-rotting.

**Comment by vendrov** [comment]
@zmerlynn - Exactly :+1:

**Comment by justinsb** [comment]
@zmerlynn wrote much better docs for how to run e2e in #1300, and removed this folder.

@vendrov can you please have a look at those docs, and open a new issue (preferred) or comment/reopen here if this is not resolved - thank you :-)
