### ISSUE TITLE
Cannot build kops using documented instructions

### ISSUE THREAD

**Issue by neilg** [kubernetes/kops#10941]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Building kops 1.19.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"archive", BuildDate:"2021-01-13T22:07:54Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

N/A

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I was following the instructions at https://github.com/kubernetes/kops/blob/v1.19.1/docs/development/building.md
```
[neil@pinot ~]$ mkdir kops
[neil@pinot ~]$ cd kops
[neil@pinot kops]$ export GOPATH=`pwd`
[neil@pinot kops]$ echo $GOPATH
/home/neil/kops
[neil@pinot kops]$ go get -d k8s.io/kops
go: downloading k8s.io/kops v1.19.1
go get: k8s.io/kops@v1.11.0 updating to
	k8s.io/kops@v1.19.1 requires
	k8s.io/kubectl@v0.0.0: reading k8s.io/kubectl/go.mod at revision v0.0.0: unknown revision v0.0.0
[neil@pinot kops]$ echo $?
1
[neil@pinot kops]$ cd ${GOPATH}/src/k8s.io/kops/
bash: cd: /home/neil/kops/src/k8s.io/kops/: No such file or directory
[neil@pinot kops]$
```

**5. What happened after the commands executed?**

I was not able to build kops.

**6. What did you expect to happen?**

I expected to be able to build kops

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

N/A

**Comment by olemarkus** [comment]
Which go version are you using?

**Comment by neilg** [comment]
```
[neil@pinot kops]$ go version
go version go1.16 linux/amd64
```

**Comment by olemarkus** [comment]
Try go1.15.x instead. That should work.

**Comment by neilg** [comment]
Yes, that worked. It builds fine with ``` go1.15.8 linux/amd64```

**Comment by JanSurft** [comment]
Is there any workaround other than downgrading the go version on my system?

**Comment by olemarkus** [comment]
Master branch should not be bult with 1.16.

Note that it is possible to have multliple versions of go installed.

**Comment by olemarkus** [comment]
I think I will close this one.

And for those who want, anyone in need of assistance  to build kOps is welcome to ask for help in #kops-dev in the kubernetes slack.

**Comment by yspro** [comment]
It doesn't work for `go version go1.15.10 darwin/amd64`

**Comment by olemarkus** [comment]
> It doesn't work for `go version go1.15.10 darwin/amd64`

As mentioned above, the master branch requires golang 1.16

**Comment by yspro** [comment]
> > It doesn't work for `go version go1.15.10 darwin/amd64`
> 
> As mentioned above, the master branch requires golang 1.16

It was mentioned that:
> Master branch should not be bult with 1.16.

🤷‍♂️ 
And yes, I tried 1.16 as well, no luck

**Comment by olemarkus** [comment]
Ah. My mistake. `master` _should_ be built with 1.16.

If you cannot build with 1.16 _and_ you are sure that you have checked out the repos in `GOPATH`, I suggest reaching out to the slack channel mentioned above.
