### ISSUE TITLE
Managing networking pods resource requests/limits

### ISSUE THREAD

**Issue by daenney** [kubernetes/kops#10973]
I'd like to be able to configure CPU and memory requests and limits for the networking pods. I want the ability to set them in such a way that it can result in a QoS class of Guaranteed, to minimise the chance of networking pods getting evicted due to resource pressure. This has been implemented for Weave in #8216 but is missing for Calico and most other networking options.

**Comment by daenney** [comment]
One other thing I'm wondering about; if I add resource requests/limits directly into the generated k8s.yaml (the one in the state store), will that persist across upgrades, and is that a feasible/recommendable way of managing these values until kOps natively supports it?

**Comment by olemarkus** [comment]
Setting limits on networking pods is not a good idea. Networking components need to consume whatever they need.
Networking pods are also marked with node/cluster critical and will not easily get evicted.

**Comment by daenney** [comment]
We’re regularly seeing eviction issues on Calico’s node pod which is rather disruptive. As shown by the Weave related PR, there’s already precedent for doing it exactly for this reason.

Node/cluster critical doesn’t help as that’s just a scheduling priority. When k8s evicts based on resource pressure, resource usage weighs more heavily. Not having requests/limits means it ends up being an early candidate for eviction when the node comes under memory pressure


> The kubelet ranks Pods for eviction first by whether or not their usage of the starved resource exceeds requests, then by Priority, and then by the consumption of the starved compute resource relative to the Pods' scheduling requests.

https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods

**Comment by daenney** [comment]
On the limits thing, I don't know whether it would matter much in this particular case. But not being able to set requests, and the pods not having a minimum for memory, appears to be problematic.

**Comment by olemarkus** [comment]
Agreed. That CNI at least set some requirements is good. that it should be configurable ... not sure. My guess is that we would accept a PR.
