### ISSUE TITLE
api.internal Not Updated after Master shutdown

### ISSUE THREAD

**Issue by atze234** [kubernetes/kops#10993]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.18.3 (git-11ec695516)
`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
We are shutting down our dev Clusters every night to save some money. With AWS Api Commands we are updating the Autoscaling groups to have a Demand of "0" instances for every Instance Group.  

**5. What happened after the commands executed?**

On next Cluster activation `kubectl get no` looks like this:
```
NAME                                            STATUS     ROLES                AGE    VERSION
ip-10-20-21-126.eu-central-1.compute.internal   NotReady   node,spot-worker     12d    v1.18.15
ip-10-20-21-209.eu-central-1.compute.internal   Ready      master,spot-worker   167m   v1.18.15
ip-10-20-21-26.eu-central-1.compute.internal    NotReady   master,spot-worker   12d    v1.18.15

```
With a kubectl get pods -nkube-system:
```
dns-controller-675fb847b-98c5f                                          1/1     Running             0          12d
```
So the dns-controller pod is running on the 12d old (NotReady) Master that was shut down 12 Days ago. Its not gonna be rescheduled and (of course) not really running.
The DNS Record for api.internal is still at old Master 10.20.21.26, so the newly created Nodes cannot connect. 
The Cluster stays in this state until i update the A Record in Route53 to the IP of the newly created master (10.20.21.209). After this everything is starting up and working fine. 

**6. What did you expect to happen?**
The dns-controller must start anyhow so that it can update the A Record for api.internal. Replication maybe?

**Comment by olemarkus** [comment]
When you tear fown the CP nodes and start them up again, it will take a while for the cluster to figure out what nodes exists and reschedule pods. So this should sort itself out after 5 minutes or so.

**Comment by atze234** [comment]
No its in this state forever. As you can see above the Ready master is running 167m in this example. Problem is that the dns-controller is in Running State on the old not ready master. 
maybe there should be an automatic cleanup of the old master that is not happening here?

**Comment by olemarkus** [comment]
If you scaled your ASGs to 0, I don't see how you can have 12d nodes. Further, you should have 3 fresh nodes as the other CP nodes join the cluster too. I suspect your control plane doesn't correctly recover.

If you upgrade to kops 1.19, can you run `kops get instances`?

**Comment by atze234** [comment]
Ok, 12days before i scaled Master and Nodes ASG to "0". So no time for k8s api to get a node deleted or so. 
Then after those 12 days im switching it on again (Master to "1" and Nodes to "2").
Then the Master CP is recovering and new Master transitions to "Ready" state.

The Problem now is, that the k8s api is not cleaning up the old master and nodes in its etcd store *and* that the dns-controller pod, that was running on the 12d old master, is considered "Running".

So it seems to be more a problem with garbage collection, that is not cleaning up the old master. But its related to the dns-controller api.internal entry. After fixing the dns-controller pod, or the api.internal dns, garbage collection is pickin up the old nodes and master.    
Maybe replicating the dns-controller to all masters as a daemon set can fix this? 

I will update to 1.19 later this week.

**Comment by olemarkus** [comment]
It would be interesting to see what the kubelet log says on the other CP nodes.

**Comment by atze234** [comment]
There are no other CP nodes? They were terminated 12 days ago. They exist only in the etcd of the ApiServer and are not cleaned up until the api.internal dns change.

**Comment by olemarkus** [comment]
The cloud provider is supposed to delete nodes k8s resources that have been terminated in AWS. I think it checks for the terminated state. Not sure why your nodes are not being deleted. But that is a kubernetes issue, not a kops one. There have been issues with this in the past: e.g https://github.com/kubernetes/kubernetes/pull/79436

**Comment by atze234** [comment]
Thank you. As the Problem persists with v1.19 i opened up another bugreport there: https://github.com/kubernetes/kubernetes/issues/101526
