### ISSUE TITLE
Modifying cloudLabels gives "Ignoring tag changes until we have #241"

### ISSUE THREAD

**Issue by FrederikNS** [kubernetes/kops#1099]
kops version: 1.4.1

I just tried to update the cloudLabels and nodeLabels on some of my instances. But the update told me that the tag changes were ignored, and I can also see that the Auto Scaling Group has not had the new tags applied.

First I ran an update to see what would change:

    > kops update cluster k8s.example.com
    I1208 14:40:26.202385    5837 populate_cluster_spec.go:196] Defaulting DNS zone to: Z3E6RP0Q59CGJN
    I1208 14:40:27.412810    5837 executor.go:68] Tasks: 0 done / 63 total; 30 can run
    I1208 14:40:28.085793    5837 executor.go:68] Tasks: 30 done / 63 total; 12 can run
    I1208 14:40:28.493765    5837 executor.go:68] Tasks: 42 done / 63 total; 17 can run
    I1208 14:40:29.251172    5837 executor.go:68] Tasks: 59 done / 63 total; 4 can run
    I1208 14:40:29.450190    5837 executor.go:68] Tasks: 63 done / 63 total; 0 can run
    Will modify resources:
      AutoscalingGroup    	autoscalingGroup/master-eu-west-1a.masters.k8s.example.com
      	Tags                	 {KubernetesCluster: k8s.example.com, Name: master-eu-west-1a.masters.k8s.example.com, k8s.io/role/master: 1} -> {k8s.io/role/master: 1, team: site-reliability-enginering-cph, Name: master-eu-west-1a.masters.k8s.example.com, KubernetesCluster: k8s.example.com, environment: prod}

      AutoscalingGroup    	autoscalingGroup/master-eu-west-1c.masters.k8s.example.com
      	Tags                	 {k8s.io/role/master: 1, KubernetesCluster: k8s.example.com, Name: master-eu-west-1c.masters.k8s.example.com} -> {Name: master-eu-west-1c.masters.k8s.example.com, KubernetesCluster: k8s.example.com, environment: prod, k8s.io/role/master: 1, team: site-reliability-enginering-cph}

      AutoscalingGroup    	autoscalingGroup/nodes.k8s.example.com
      	Tags                	 {KubernetesCluster: k8s.example.com, Name: nodes.k8s.example.com, k8s.io/role/node: 1} -> {environment: prod, k8s.io/role/node: 1, team: site-reliability-enginering-cph, Name: nodes.k8s.example.com, KubernetesCluster: k8s.example.com}

      AutoscalingGroup    	autoscalingGroup/master-eu-west-1b.masters.k8s.example.com
      	Tags                	 {KubernetesCluster: k8s.example.com, Name: master-eu-west-1b.masters.k8s.example.com, k8s.io/role/master: 1} -> {k8s.io/role/master: 1, team: site-reliability-enginering-cph, Name: master-eu-west-1b.masters.k8s.example.com, KubernetesCluster: k8s.example.com, environment: prod}

    Must specify --yes to apply changes

Then I actually applied the update:

    > kops update cluster k8s.example.com --yes
    I1208 14:41:12.434633    5975 populate_cluster_spec.go:196] Defaulting DNS zone to: Z3E6RP0Q59CGJN
    I1208 14:41:13.390210    5975 executor.go:68] Tasks: 0 done / 63 total; 30 can run
    I1208 14:41:13.876981    5975 executor.go:68] Tasks: 30 done / 63 total; 12 can run
    I1208 14:41:15.037965    5975 executor.go:68] Tasks: 42 done / 63 total; 17 can run
    I1208 14:41:15.819645    5975 executor.go:68] Tasks: 59 done / 63 total; 4 can run
    W1208 14:41:15.884933    5975 autoscalinggroup.go:192] Ignoring tag changes until we have #241: %vmap[team:site-reliability-enginering-cph Name:master-eu-west-1c.masters.k8s.example.com KubernetesCluster:k8s.example.com environment:prod k8s.io/role/master:1]
    W1208 14:41:15.888828    5975 autoscalinggroup.go:192] Ignoring tag changes until we have #241: %vmap[Name:master-eu-west-1b.masters.k8s.example.com KubernetesCluster:k8s.example.com environment:prod k8s.io/role/master:1 team:site-reliability-enginering-cph]
    W1208 14:41:15.959747    5975 autoscalinggroup.go:192] Ignoring tag changes until we have #241: %vmap[environment:prod k8s.io/role/master:1 team:site-reliability-enginering-cph Name:master-eu-west-1a.masters.k8s.example.com KubernetesCluster:k8s.example.com]
    W1208 14:41:15.975720    5975 autoscalinggroup.go:192] Ignoring tag changes until we have #241: %vmap[team:site-reliability-enginering-cph Name:nodes.k8s.example.com KubernetesCluster:k8s.example.com environment:prod k8s.io/role/node:1]
    I1208 14:41:16.045292    5975 executor.go:68] Tasks: 63 done / 63 total; 0 can run
    I1208 14:41:16.201218    5975 update_cluster.go:150] Exporting kubecfg for cluster
    Wrote config for k8s.example.com to "/home/frederiknjs/.kube/config"

    Cluster is starting.  It should be ready in a few minutes.

    Suggestions:
     * list nodes: kubectl get nodes --show-labels
     * ssh to the master: ssh -i ~/.ssh/id_rsa admin@api.k8s.example.com
     * read about installing addons: https://github.com/kubernetes/kops/blob/master/docs/addons.md

It seems that the mentioned issue (#241) has already been closed before kops 1.4.1 was released. So shouldn't this have been fixed?

**Comment by kris-nova** [comment]
This is a one liner - I just opened a PR that addresses it - thanks @FrederikNS
