### ISSUE TITLE
kOps doesn't update LaunchTemplate version in AWS AutoScaling Group when it's been previously updated out-of-band

### ISSUE THREAD

**Issue by cameronattard** [kubernetes/kops#11008]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.19.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.19.8

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops update cluster --yes`

**5. What happened after the commands executed?**

kOps provisions a new LaunchTemplate version with the latest configuration but the AutoScaling Group still refers to the old version.

**6. What did you expect to happen?**

kOps provisions the new LaunchTemplate version and updates the AutoScaling Group to refer to the new version.

**9. Anything else do we need to know?**

We have a scheduled job outside of kOps that creates new LaunchTemplate versions with our latest AMI and updates the ASG to use that version. I am guessing this is what is causing kOps to get confused.

**Comment by hakman** [comment]
Hey @cameronattard. As you can imagine, it is pretty hard to deduce what happens without some more detailed info. Would appreciate if you can provide some simple steps to reproduce the issue.

Other than this, kOps uses its own config as the source of truth and it generates new launch templates from that. Values from previous launch template are not kept as a base.
If you want to update AMIs easier with scripts, you could also use templates:
https://kops.sigs.k8s.io/operations/cluster_template/

**Comment by cameronattard** [comment]
Sorry @hakman, should have included that!

Steps to reproduce:

1. Create new Launch Template version (can be done via console) with some arbitrary change e.g. updating AMI
2. Update AutoScaling Group to refer to the template created in step 1 (can be done via console)
3. Run kops with some arbitrary change that will generate a new Launch Template (e.g. updating AMI, changing container runtime, etc).
4. Check for new Launch Template version - it should exist
5. Check AutoScaling Group - it will still refer to the Launch Template version created in step 1, rather than what we expect which is the one created in step 3

**Comment by hakman** [comment]
Thanks @cameronattard. The behavior you noticed is the expected one. As I mentioned before, kOps generates new LTs every time the update cluster runs based on its config and doesn't preserve any manual changes.

To get what you want, you will need to do 3 doing kOps. You can either use templates, the 'set' command, or the replace command.

**Comment by cameronattard** [comment]
Understood @hakman, but shouldn't kops always update the LT version referred to by the ASG to the latest one (i.e. the one just provisioned by kops)? I am not referring to preserving manual changes, but failing to overwrite them.

**Comment by hakman** [comment]
I think I solved the mystery. When you are doing step 2 you are breaking the ASG settings. It is configured by kOps to use the latest available LT version and you are (most likely) changing it to a fixed one.

**Comment by cameronattard** [comment]
Interesting, I'll investigate our tooling to check for this. Thanks!

**Comment by hakman** [comment]
Any conclusion @cameronattard ?

**Comment by cameronattard** [comment]
Sorry for the delayed response @hakman - I think that was indeed the problem. Thanks again for your help on this.
