### ISSUE TITLE
kops delete cluster command throws error "unknown file found: kops-version.txt"

### ISSUE THREAD

**Issue by sagarkal** [kubernetes/kops#11012]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.19.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.19.8

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops delete cluster --name <cluster_name> --state <s3_bucket_name_where_state_is_stored> --yes

**5. What happened after the commands executed?**
All the resources assigned to the cluster get deleted, but the command throws this error:
`error removing cluster from state store: refusing to delete: unknown file found: s3://<s3_bucket_name_where_state_is_stored>/<cluster_name>/kops-version.txt`

**6. What did you expect to happen?**
Since all the resources assigned to the cluster got deleted, I expected kops delete command to not throw any error

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Sorry, the organization where I work does not allow me to share this info

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
If this is needed, I can provide this info

**9. Anything else do we need to know?**
No

**Comment by rifelpet** [comment]
Hi @sagarkal can you confirm that the kops binary used to delete the cluster is in fact version 1.19.1 ? This error should only be happening if you used an older kops version to delete a cluster that was created or updated with kops >= 1.19.0

**Comment by sagarkal** [comment]
@rifelpet Thanks, turned out that my cluster creation job was using kops 1.19.1, but my cluster deletion was still using kops 1.16
Sorry for the delayed response!
