### ISSUE TITLE
Create IAM User

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1103]
Request for a new good feature to have kops auto create a user for a cluster.

**Comment by azell** [comment]
Some notes from a new cluster with a manual IAM group and user:

* Navigate to the **IAM home page** after logging onto the console
* Click the `Groups` link on the left tab and then click `Create New Group`
* Set `Group Name:` to kops and then click `Next Step`
* Attach the following policies and then click `Next Step`:
  * AmazonEC2FullAccess
  * AmazonRoute53FullAccess
  * AmazonS3FullAccess
  * IAMFullAccess
  * AmazonVPCFullAccess
* Click `Create Group`
* Click the `Users` link on the left tab and then click `Add user`
* Set `User name` to kops
* Select `Access type` **Programmatic access**
* Click `Next: Permissions`
* Select the `kops` Group and click `Next: Review`
* Click `Create user`
* Click on `Download .csv`
* Run `aws configure`
* Run `aws iam list-users`

**Comment by jasondewitt** [comment]
would be great to add this to the Getting Started docs. Currently the "More Information" link [here](https://github.com/kubernetes/kops/blob/master/docs/aws.md#setting-up-a-kops-iam-user) about the IAM user to set up takes to you a page about SQS for some reason

**Comment by chrislovecnm** [comment]
I am wondering if we should do:

```
$ kops create user installer
$ kops create user node
$ kops create user master
```

Then you can reuse those roles, and also we can test them.

Thoughts?

**Comment by chrislovecnm** [comment]
One note on this - we need to allow kops to use an existing bucket, which at this point I do not think kops will allow for.
