### ISSUE TITLE
Upgraded kubernetes from 1.19 to 1.20 and enabled cert manager at same time.  Cert manager missing 

### ISSUE THREAD

**Issue by loibucket** [kubernetes/kops#11053]
1. What kops version are you running? The command kops version, will display
this information.

1.20 kops 1.20 kubectl 

2. What Kubernetes version are you running? kubectl version will print the
version if a cluster is running or provide the Kubernetes version specified as
a kops flag.

1.20

3. What cloud provider are you using?

aws

I used kops upgrade to upgrade from 1.19 to 1.20 .  At the same time I had kops edited my config by adding spec cert manger enabled true.  After upgrade and restarted, cert manger is not installed, but it is listed in my config as enabled true.  I tried to remove it with kops edit and delete the cert manager spec, update, and reinstall by kops edit and update.  I still can’t get cert mange to appear. 

I can still install and remove cert manager from yml file fine

Looking for some way to do a clean uninstall and reinstall of certmanager addon.

**Comment by olemarkus** [comment]
Hi, there is some missing info missing in this bug report. Can you paste the redacted cluster spec `kops get -o yaml`?

**Comment by loibucket** [comment]
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-03-10T20:57:32Z"
  generation: 18
  name: redact.ed
spec:
  additionalSans:
  - redact.ed
  api:
    dns: {}
  authorization:
    rbac: {}
  certManager:
    enabled: true
  channel: stable
  cloudProvider: aws
  configBase: s3://redact.ed
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.2
  masterInternalName: redact.ed
  masterPublicName: redact.ed
  metricsServer:
    enabled: true
    insecure: true
  networkCIDR: redact.ed
  networking:
    kubenet: {}
  nonMasqueradeCIDR: redact.ed
  sshAccess:
  - redact.ed
  subnets:
  - cidr: redact.ed
    name: us-east-1a
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-03-10T20:57:32Z"
  generation: 6
  labels:
    kops.k8s.io/cluster: redact.ed
  name: master-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3a.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-03-10T20:57:32Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: redact.ed
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3a.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  subnets:
  - us-east-1a

**Comment by olemarkus** [comment]
Would be easier if you put this in a code block. The indentations look a bit random now.

Do you remember if `kops update cluster` dry run said the addon would be added? Should be visible in the diff output.

Can you also list the annotations in `kops get -o yaml ns kube-system`?

Could you also list a couple of minutes output of `journalctl -u protokube` from one of the master nodes? Between two outputs of `No update required`

**Comment by loibucket** [comment]
I a yml of the certmanager in the addons folder in my s3 bucket.  I was able to apply that and got cert-manager installed.

I remembered the dry run said the addon would be added.

```
(base) ➜  kops kops get -o yaml ns kube-system
Cluster.kops.k8s.io "ns" not found
```

```
Mar 15 06:15:02 ip-172-20-41-201 docker[5841]: No update required
Mar 15 06:16:02 ip-172-20-41-201 docker[5841]: I0315 06:16:02.935484    5869 kube_boot.go:141] protokube management of etcd not enabled; won't scan for volumes
Mar 15 06:16:02 ip-172-20-41-201 docker[5841]: I0315 06:16:02.935540    5869 labeler.go:36] Querying k8s for node "ip-172-20-41-201.ec2.internal"
Mar 15 06:16:02 ip-172-20-41-201 docker[5841]: W0315 06:16:02.959599    5869 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use r>
Mar 15 06:16:02 ip-172-20-41-201 docker[5841]: W0315 06:16:02.963299    5869 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use r>
Mar 15 06:16:02 ip-172-20-41-201 docker[5841]: I0315 06:16:02.963563    5869 channels.go:31] checking channel: "s3://onestepc-kops-store/onestepc.tk/addons/bootstrap-channel.yaml"
Mar 15 06:16:02 ip-172-20-41-201 docker[5841]: I0315 06:16:02.963619    5869 channels.go:45] Running command: /channels apply channel s3://onestepc-kops-store/onestepc.tk/addons/bootstrap-channel.yam>
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.242954    5869 channels.go:34] apply channel output was: I0315 06:16:03.033678   10183 addons.go:38] Loading addons channel from "s3://on>
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.142428   10183 s3context.go:213] found bucket in region "us-east-1"
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.142490   10183 s3fs.go:290] Reading file "s3://onestepc-kops-store/onestepc.tk/addons/bootstrap-channel.yaml"
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.186825   10183 addons.go:127] Skipping version range "<1.15.0" that does not match current version 1.20.2
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.202540   10183 channel_version.go:108] Checking existing channel: Version=1.17.0 Channel=s3://onestepc-kops-store/onestepc.tk/addons/boot>
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.202664   10183 channel_version.go:135] Manifest Match
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.209813   10183 channel_version.go:108] Checking existing channel: Version=1.20.0-beta.2 Channel=s3://onestepc-kops-store/onestepc.tk/addo>
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.209879   10183 channel_version.go:135] Manifest Match
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.214081   10183 channel_version.go:108] Checking existing channel: Version=v0.0.1 Channel=s3://onestepc-kops-store/onestepc.tk/addons/boot>
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.214127   10183 channel_version.go:135] Manifest Match
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.218348   10183 channel_version.go:108] Checking existing channel: Version=1.7.0-kops.3 Channel=s3://onestepc-kops-store/onestepc.tk/addon>
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.218431   10183 channel_version.go:135] Manifest Match
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.222983   10183 channel_version.go:108] Checking existing channel: Version=1.20.0-beta.2 Channel=s3://onestepc-kops-store/onestepc.tk/addo>
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.223042   10183 channel_version.go:135] Manifest Match
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.227288   10183 channel_version.go:108] Checking existing channel: Version=1.5.0 Channel=s3://onestepc-kops-store/onestepc.tk/addons/boots>
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.227330   10183 channel_version.go:135] Manifest Match
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.230928   10183 channel_version.go:108] Checking existing channel: Version=0.3.7 Channel=s3://onestepc-kops-store/onestepc.tk/addons/boots>
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.230984   10183 channel_version.go:135] Manifest Match
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.235991   10183 channel_version.go:108] Checking existing channel: Version=1.1.0 Channel=s3://onestepc-kops-store/onestepc.tk/addons/boots>
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.236316   10183 channel_version.go:135] Manifest Match
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.240739   10183 channel_version.go:108] Checking existing channel: Version=1.4.0 Channel=s3://onestepc-kops-store/onestepc.tk/addons/boots>
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: I0315 06:16:03.240793   10183 channel_version.go:135] Manifest Match
Mar 15 06:16:03 ip-172-20-41-201 docker[5841]: No update required
```
