### ISSUE TITLE
Improve time to resolve API DNS record of new clusters

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#11050]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.18 though the behavior happens on various minor versions

**3. What cloud provider are you using?**

aws

This is happening on various e2e prow jobs. I'm going to use [this](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920) one as an example. The cluster takes 5m16s to have its DNS record updated from the placeholder IP to the control plane hosts.

A timeline of events:
* [23:15:47](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920#1:build-log.txt%3A127) - the DNS placeholder records are created w/ a 10s TTL as a part of `kops create cluster`
* [23:15:48](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920#1:build-log.txt%3A140) - `validate cluster` is invoked with 15 minute timeout
* [23:15:59](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920#1:build-log.txt%3A161) - validation resolves the DNS record to the placeholder IP
* [23:21:03](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920#1:build-log.txt%3A630) - DNS record now points to apiserver, **this is the time i'd like to see if we can reduce**

On the control plane host we see this timeline:

* [23:16:20](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920/artifacts/ip-172-20-48-213.eu-west-1.compute.internal/journal.log) - nodeup starts for the first time
* [23:17:20](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920/artifacts/ip-172-20-48-213.eu-west-1.compute.internal/journal.log) - protokube starts for the first time
* [23:17:21](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920/artifacts/ip-172-20-48-213.eu-west-1.compute.internal/journal.log) - kubelet starts for the first time
* [23:18:34](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920/artifacts/ip-172-20-48-213.eu-west-1.compute.internal/kubelet.log) - the last "connection refused" error from kubelet, this is when [kube-apiserver started](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920/artifacts/cluster-info/kube-system/kube-apiserver-ip-172-20-48-213.eu-west-1.compute.internal/logs.txt)
* [23:19:23](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920/artifacts/ip-172-20-48-213.eu-west-1.compute.internal/protokube.log) - protokube applies the dns-controller addon
* [23:19:39](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920/artifacts/ip-172-20-48-213.eu-west-1.compute.internal/kube-scheduler.log) - scheduler can't schedule dns-controller onto control plane instance because it is missing the `node-role.kubernetes.io/master` label
* [23:20:26](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920/artifacts/ip-172-20-48-213.eu-west-1.compute.internal/protokube.log) - protokube adds the `node-role.kubernetes.io/master` label to the control plane node
* [23:20:26](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920/artifacts/ip-172-20-48-213.eu-west-1.compute.internal/kube-scheduler.log) - scheduler schedules dns-controller to the control plane node
* [23:20:27](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920/artifacts/cluster-info/kube-system/dns-controller-5577ddf578-mvdm6/logs.txt) - dns-controller container starts
* [23:20:46](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920/artifacts/cluster-info/kube-system/dns-controller-5577ddf578-mvdm6/logs.txt) - dns-controller updates DNS record

From a quick glance, I'm wondering if we can have protokube apply the addons and the control plane labels sooner. Theres also a minute between nodeup and protokube/kubelet starting, I'm wondering if that can be reduced or if that time is spent installing dependencies like containerd. Any other ideas would be appreciated

**Comment by rifelpet** [comment]
Ideas from office hours:

* Convert etcd-manager-ctl to a systemd unit
* Add a kube-apiserver initContainer that waits for etcd to be healthy (retrying more aggressively than standard crash loop backoffs)
* Have protokube apply channels immediately after adding node labels, rather than waiting for the next cycle 1 minute later

**Comment by olemarkus** [comment]
I don't quite get why labels and channels aren't applied at the same time. This already should happen in the same iteration.

**Comment by rifelpet** [comment]
@olemarkus pointed out another delay in slack, between the DNS record existing and nodes joining the cluster.

Using [this](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/11093/pull-kops-e2e-kubernetes-aws/1373648269804048384/artifacts/ip-172-20-49-145.ap-northeast-1.compute.internal/journal.log) node's journal log as an example.

* [14:56:37](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/11093/pull-kops-e2e-kubernetes-aws/1373648269804048384/artifacts/ip-172-20-49-145.ap-northeast-1.compute.internal/journal.log) nodeup begins `Executing task "BootstrapClientTask/BootstrapClient"`
* [14:58:49](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/11093/pull-kops-e2e-kubernetes-aws/1373648269804048384/artifacts/ip-172-20-49-145.ap-northeast-1.compute.internal/journal.log) nodeup experiences `error running task "BootstrapClientTask/BootstrapClient"`, timing out trying to connect to kops-controller endpoint. retries immediately
* [14:59:00](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/11093/pull-kops-e2e-kubernetes-aws/1373648269804048384/artifacts/ip-172-20-63-12.ap-northeast-1.compute.internal/dns-controller-67fc9d8ddb-gwnr6.log) dns-controller adds A record for kops-controller dns name
* [14:59:01](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/11093/pull-kops-e2e-kubernetes-aws/1373648269804048384/artifacts/ip-172-20-63-12.ap-northeast-1.compute.internal/kops-controller-kf9gg.log) kops-controller starts up (presumably listens on its address though its not clear - maybe we should add a log line for that?)
* [15:01:00](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/11093/pull-kops-e2e-kubernetes-aws/1373648269804048384/artifacts/ip-172-20-49-145.ap-northeast-1.compute.internal/journal.log) nodeup again times out trying to connect to kops-controller endpoint. retries immediately, no log indicating when it succeeded (likely immediately)


Having not looked at the code, I'm guessing there is a ~2min timeout on making that request. We should consider shortening that considerably.

**Comment by olemarkus** [comment]
Wonder if we should just fail the task if dns resolved to the placeholder ip

**Comment by olemarkus** [comment]
We have done number of fixes, and I believe this is no longer a problem
/close
/remove-lifecycle stale
