### ISSUE TITLE
Register (and deregister) A record value in Route53 when instance group nodes come up (and down)

### ISSUE THREAD

**Issue by cjheppell** [kubernetes/kops#11055]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

When my master node comes up, it registers its ip address in an A record value in the corresponding route 53 hosted zone.

I'd like the same thing to happen for my instance group nodes.

For example, if I have a cluster with a hosted zone name of `mycluster.example.com` then when a node comes up in my instance group `myig1`, I'd like a route53 `A` record to appear in `mycluster.example.com` with the value containing the private (and/or public) ip address of the new node.

Likewise, when the node is scaled down I'd like that value removed.

As a concerete example, suppose `myig1` contains 3 nodes. I'd like a route 53 `A` record in `mycluster.example.com` to be:

`myig1.mycluster.example.com    A     10.0.0.5, 10.0.0.6, 10.0.0.7`

where my 3 nodes have private ip's 10.0.0.5, 10.0.0.6 and 10.0.0.7 respectively.

### Why?

I have some TCP NodePort services to run, and I'm running a load balancer in front of them that does DNS service discovery.

I'd like to set that load balancer to autodiscover nodes when they come up/down and update its routing table appropriately. Because nodes in instance groups don't register their ip addresses in a route 53 zone I'm unable to get this service discovery to work.

### Alternatives?

I've considered looking into "hooks" which I could use to run a docker container and register the new nodes ip address when it starts up in a route 53 zone. This works for registering the target, but I'd need a corresponding change to happen when the node is removed (and I can't see a way to run a hook "on deletion" of the node).

**Comment by olemarkus** [comment]
This is done by dns controller. You can easily use this behavior yourself by setting node labels on the instance group. See https://github.com/kubernetes/kops/tree/master/dns-controller

**Comment by cjheppell** [comment]
Looks like the relevant code for this is commented out? https://github.com/kubernetes/kops/blob/master/dns-controller/pkg/watchers/node.go#L145-L193

I just tried adding the annotation to an existing node, but didn't see a new dns A record get registered.

Is there some additional config necessary?

**Comment by olemarkus** [comment]
This should happen automatically. This is how the api dns entries work.

But ofc it needs to have permissions to add the entries too. It won't have by default if the entry is a different zone than the cluster domain.

**Comment by cjheppell** [comment]
That's strange...

My API dns entries are getting set just fine. But adding the annotation does not result in a new record for the node. As far as I understand, I haven't changed any of the hosted zone configuration.

I'm getting these in the dns-controller logs:

```
I0315 19:21:44.528015       1 dnscontroller.go:660] Update desired state: node/<nodename>.internal: [{A node/<nodename>.internal/internal <internal_ip> true} {A node/<nodename>/external <external_ip> true} {A node/role=node/internal <internal_ip> true} {A node/role=node/external <external_ip> true} {A node/role=node/ <node_hostname_internal>.internal true} {A node/role=node/ <node_hostname_internal>.internal true} {A node/role=node/ <node_hostname_external> true}]
```

But absolutely no entries in the hosted zone other than the API.

Something isn't quite right here

**Comment by cjheppell** [comment]
So it seems that `AliasTarget` is set to `true` for all Nodes (other than the masters?): https://github.com/kubernetes/kops/blob/11ec695516cc64759da9200493e41e8a2bcce8b1/dns-controller/pkg/dns/record.go#L37-L40

And assuming this comment is true, then it seems that alias targets won't ever be actually set in DNS (Route 53). Which would explain why I'm not seeing it.

With that in mind... it seems like this is _not possible_ with the DNS controller. Or am I misunderstanding?

**Comment by olemarkus** [comment]
You are right. Something is not quite right.

kOps actually set the labels on pods, not the nodes themselves. So you could try that. See e.g the label being set on `kube-apiserver-ip.****`

**Comment by cjheppell** [comment]
Ok, some more investigation...

It seems the docs are very unclear on this.

Evidently, I can "abuse" the fact that registering a **service** with the `dns.alpha.kubernetes.io/internal` set to something will cause an entry to be created in my hosted zone with the ip address of _all_ internal nodes. That means I can register a single "dummy service" of type NodePort with the annotation set to get my node ip addresses in DNS.

That's not exactly what I want (as I wanted this to apply to **only the instance group in question**) but it will do for now.

---

Going forwards, I'd love to be able to stick an annotation on a **node** and have that produce the relevant values in the recordset specified.

**Comment by cjheppell** [comment]
Might I suggest correcting the docs so this offending line is removed, as it's not true?: https://github.com/kubernetes/kops/blob/11ec695516cc64759da9200493e41e8a2bcce8b1/dns-controller/README.md#L15-L20

**Comment by olemarkus** [comment]
Long-term goal is to replace dns-controller with external-dns, but meanwhile I'll see if I can dig into this.

Again I'd try labelling pods and see what happens.

**Comment by olemarkus** [comment]
I started to dig into what dns-controller actually does.

The node label stuff is all lies! The code around this has been commented out.

You can add _annotations_ to pods, not labels, and it will work as expected (but not documented). 

The alias stuff is not related to route53 aliases. dns-controller will create internal records for each node. Then each pod will "alias" to the node it is assigned to for external IPs.

Also, for this to work for pods, the pod must have hostnetworking on. This makes sense, I suppose.

Now, another fun part. dns-controller also supports these _annotations_ on services. It looks like nodeport is supported and will work as expected. I have not yet dug too much into the code for that yet though.

**Comment by cjheppell** [comment]
Thanks for looking into this @olemarkus!

I can confirm node port is working for services. That's the current workaround I'm relying on.

It'd still be great to have support at the node level (since this would allow me to only register nodes in instancegroups I care about). Though I'm conscious you said the goal is to replace `dns-contoller` with `external-dns` so I suppose changes to `dns-controller` are currently trying to be avoided?

**Comment by olemarkus** [comment]
I think what you want then is to run the pods with hostNetwork true and annotate the pods.

If we were to add all nodes in an IG to a hostname and a pod is not running there, all clients that resolve to nodes without the pod would fail.

Without nodePort service and without hostNetworking, there would be nothing that routed traffic from the node to the pod either. So you need one of these.

**Comment by cjheppell** [comment]
> If we were to add all nodes in an IG to a hostname and a pod is not running there, all clients that resolve to nodes without the pod would fail.

But `kube-proxy` would pass that on to the node where the corresponding pod resides, surely?

Also, I think things may be getting a little muddled. Let's imagine we don't have any services and the only thing I care about is having a single `A` record in my route 53 hosted zone with values that point to all the IPs of the nodes.

It'd be nice to annotate a node with something like `dns.alpha.kubernetes.io/internal: "nodes.mycluster.mydomain.com"` and have all nodes that come up with that annotation have their private IP registered in the values for the recordset `nodes.mycluster.mydomain.com`. Services/pods aren't of concern in this workflow. All I want is the node ip's registered in a recordset.

This is ideal, because then I can point a load balancer that does service discovery at `nodes.mycluster.mydomain.com` and then traffic will be load-distributed across all the known IP's in that recordset entry. Handling actual routing to pods can be handed off to `kube-proxy` which will pass between nodes accordingly, as is the default behaviour for node ports.

**Comment by olemarkus** [comment]
kube-proxy will not forward any traffic without a nodePort service. Nor will the nodes have any ports open on external-facing interfaces.

**Comment by cjheppell** [comment]
> kube-proxy will not forward any traffic without a nodePort service. Nor will the nodes have any ports open on external-facing interfaces.

Agreed.

But what I'm discussing here has nothing to do with node ports/pods/etc.

The proposal is to support having an annotation on a node such that its IP address will be registered in Route 53.

Services/nodeports/pods/etc are important further down the line once you've actually managed to route traffic to a node. But that's not the point I'm concerned about in this issue.

**Comment by olemarkus** [comment]
I am at loss trying to underhand what your usecase for this actually is.

**Comment by cjheppell** [comment]
I described this in https://github.com/kubernetes/kops/issues/11055#issuecomment-801186429

But to rephrase:

- I've got an autoscaling instance group
- I'm running some services on those nodes in the instance group
- I have a load balancer sat in front of my nodes
- I want that load balancer to route to the nodes in my instance group (I don't care about routing to a specific node, I just want it to load-distribute it across all nodes and let kube-proxy do the routing when it gets to one)
- I don't want to hard-code node ip's as they could change (either because of node death, or scale ups/downs)
- Therefore, I'd like to have an `A` record in a route 53 zone (just like my api server) so that I can point my external load balancer at that `A` record to auto-discover the ip's representing the nodes in my instance group

**Comment by cjheppell** [comment]
> If the annotation was on all nodes instead, and the api server was misbehaving on a node, all clients that resolve the dns to that node would fail.

One of us must be misunderstanding this (and it's highly likely its me, so apologies to keep this going around). 

My intention is _just_ to be able to have a DNS `A` record resolve to a list of IP's associated with nodes in an instance group **by way of an annotation on a node**. Nothing to do with pods, nothing to do with services. **Purely an `A` record in DNS for every node in an instance group**. Afterall, an `A` record in a DNS server **simply resolves a name to an IP**. It **shouldn't care about the services running on that node** at the level of abstraction of DNS servers.

That's what I'm trying to capture in this issue. And it's also what is _suggested_ by the `dns-controller` readme right now - which is to support annotations on a _node_ resource to register its ip so that it can be accessed internally

![image](https://user-images.githubusercontent.com/12884767/111512002-2c43ca00-8747-11eb-8fce-c59cd8d24c20.png)


If being able to add an annotation to a node in order for its IP address to be registered as an `A` record in DNS (route 53 in this case) is _not_ something the dns-controller can/should support then I propose we just close this issue.

**Comment by olemarkus** [comment]
Yeah the readme is definitely false on this. There is no code that supports the functionality described there.

If this is something that it should support... I don't know. Just for the sake of listing instances in the ASG without exposing anything meaningful behind it... Probably not. Using the AWS sdk to list instances seems like a better method for that.

**Comment by cjheppell** [comment]
Understood. It's odd for the code to be there but to be commented out. There was obviously a reason for it existing in the first place but I can't trace the reasoning for it being commented out in the git history. (It seems like it was pulled from elsewhere _with the commented out code already_ https://github.com/kubernetes/kops/pull/26/files#diff-aa90dc0963dbbef72270aa0a0a4ad6a33afb3e05f42531784146eb674ee47ce3R124-R172)

Anyway - thanks for your patience with this issue @olemarkus.

The best approach here seems to be to implement the behaviour myself and run it as a pod in the cluster. In the future if someone else expresses interest for this feature then this issue can be referenced/reopened.

As such, I'm closing it.
