### ISSUE TITLE
no way for kops to use aws sso creds to authenticate cross account s3 state bucket

### ISSUE THREAD

**Issue by vadivkanag** [kubernetes/kops#11068]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`kops-1.18.3`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`v1.17.11`

**3. What cloud provider are you using?**

`aws`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops get clusters`

**5. What happened after the commands executed?**

`error reading cluster configuration "internal.xxxx.domain.com": error reading s3://<state-bucket-name>/kops/internal.xxxx.domain.com/config: Could not retrieve location for AWS bucket <state-bucket-name>`

**6. What did you expect to happen?**

`should return the cluster details.`

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

`due to this above error can't connect to the cluster to get this output`

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

`the s3 state bucket is in another aws account, it was all working with IAM roles by setting this env variable
export KOPS_STATE_S3_ACL=bucket-owner-full-control.
We are now moving towards aws sso from IAM roles, is there any way to let kOps know about the state store aws credentials so it can authenticate?.
`

**Comment by olemarkus** [comment]
Are you able to access the s3 bucket through AWS CLI?

**Comment by vadivkanag** [comment]
Thanks for the reply. So we have named profiles in our aws/config and both works just fine via aws cli.
our ~/.aws/credentials be like
[development]
....aws secrets...
[dev_kops_state_store]
....aws secrets...

I also set this env variable `AWS_PROFILE=development` so kOps know which aws creds to use and interact with the cluster. I think this works fine.

Now the issue is how can we let kOps know to use `[dev_kops_state_store]` so it can access the bucket in another aws account.

**Comment by olemarkus** [comment]
This is probably related to kops not properly picking up `~/.aws/credentials`. Our assumption is that we can just rely on the AWS SDK to do the right thing, but based on #8481 that doesn't seem to be the case.

If you are able to, it would be nice if you can figure out what happens here.

If not, I will have access to an AWS organisation with SSO enabled in a few months, so I can take a look at this.

**Comment by olemarkus** [comment]
Can you try to run `export AWS_SDK_LOAD_CONFIG=1` and re-run the `kops` commands?

**Comment by codablock** [comment]
We had exactly the same problem with our SSO setup. Using `export AWS_SDK_LOAD_CONFIG=1` solved the issue. It's however important to know that access tokens might still expire and then lead to other issues, which kops won't solve (no token refresh?). The solution is to perform a re-login with aws-cli so that you have a fresh access token.

**Comment by olemarkus** [comment]
Not sure what it takes to refresh the tokens from SSO. If that is just `Credentials.Get()` or if this actually has to be managed outside of the application.

**Comment by johngmyers** [comment]
It is no longer necessary to set `AWS_SDK_LOAD_CONFIG=1` when using kOps 1.22 or later.
