### ISSUE TITLE
nodeup creates invalid systemd config file

### ISSUE THREAD

**Issue by HenningCash** [kubernetes/kops#11113]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.21.0-alpha.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

**3. What cloud provider are you using?**
openstack + minio for testing

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Set `S3_ACCESS_KEY_ID` + some other provider specific variables.

```
kops create cluster
kops update cluster --yes --admin
```

**5. What happened after the commands executed?**
`nodeup` creates a systemd unit file similar to this
```
[Unit]
Description=Run kops bootstrap (nodeup)
Documentation=https://github.com/kubernetes/kops

[Service]
Environment=OS_REGION_NAME=RegionOne
OS_APPLICATION_CREDENTIAL_SECRET=secret
OS_TENANT_ID=
OS_PROJECT_ID=
OS_DOMAIN_ID=
S3_ACCESS_KEY_ID=key
...

```

The problem is `Environment`. Each line has to be prefixed by `Environment=…`. Otherwise systemd ignores these lines and logs `Unknown key name 'XXXX' in section 'Service', ignoring.`

**6. What did you expect to happen?**
See above. Either prefix each line with `Environment=…` or create a dedicated `EnvironmentFile` with these values.
I'm not sure if this issue was introduced by #11042

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by hakman** [comment]
Thanks for reporting this @HenningCash.
