### ISSUE TITLE
Kops can't create same name cluster even if VPC is different due to RouteTable/Subnet clash

### ISSUE THREAD

**Issue by tomekit** [kubernetes/kops#11116]
I am creating new cluster, in a different AWS VPC, however I am using same cluster configuration details, including name. 
It seems that `kops` doesn't care if different VPC is used and instead of creating new `RouteTable` and `Subnet`, it finds existing `RouteTable` and `Subnet` by name, instead of by name and VPC (together) as a filter.

Because of that issue, I will proably change cluster name or set it up in a different AZ, so the collision doesn't happen.
The reason I've used the same parameters, it's because I am migrating existing cluster, simply by recreating it from zero.

I've raised this as a bug, as it seem to me strange that there is any issue even if separate `VPC` is used, which should technically isolate any changes. Correct me if it's not a bug, but intended behaviour. 

Version: `Version 1.19.1 (git-8589b4d157a9cb05c54e320c77b0724c4dd094b2)`
Cloud: AWS

Cluster create: `kops create cluster --master-count 1 --node-count 1 --zones eu-west-1a --master-size t4g.small --node-size t4g.large --master-zones eu-west-1a --topology private  --networking calico v2.k8s.local --vpc=${VPC_ID}`

```
I0323 11:48:41.952213  312751 executor.go:111] Tasks: 84 done / 91 total; 2 can run
W0323 11:48:42.711710  312751 executor.go:139] error running task "RouteTable/v2.k8s.local" (9m56s remaining to succeed): Field cannot be changed: VPC
W0323 11:48:42.711735  312751 executor.go:139] error running task "Subnet/eu-west-1a.v2.k8s.local" (9m56s remaining to succeed): Subnet.VPC: Forbidden: field is immutable: old="vpc-<redacted>" new="vpc-<redacted2>"
I0323 11:48:42.711750  312751 executor.go:155] No progress made, sleeping before retrying 2 task(s)
```

**Comment by timothyclarke** [comment]
This is intended after cashes were encountered with what you are describing

The root cause is that you're trying to have 2 DNS domains / zones with different info. eg `cluster.example.com`. 
If `cluster.example.com` is a public domain then you can only have one cluster. If `cluster.example.com` is an internal zone then you can only have one per AWS account.
In short if you want another cluster give it a different name, or put it in a different account

**Comment by tomekit** [comment]
Thanks for clarification, in which case I am closing this issue.
