### ISSUE TITLE
cluster-autoscaler addon: allow specifying scaleDownDelayAfterAdd parameter

### ISSUE THREAD

**Issue by jurriaanpro** [kubernetes/kops#11117]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
After the upgrade to kOps 1.19 we’ve switched over to the cluster-autoscaler addon instead of the Helm chart, however we currently have a need to adjust the `scale-down-delay-after-add` parameter, but the configuration options for the addon don’t allow that.

I'd like to see the possibility to change this (and possibly other relevant) parameter(s) of the cluster-autoscaler addon.

**Comment by olemarkus** [comment]
A PR for this would be most welcomed.

/milestone v1.21
