### ISSUE TITLE
DefaultDeltaRunMethod should delegate deletion to the target

### ISSUE THREAD

**Issue by jmcarp** [kubernetes/kops#1113]
At the moment, `DefaultDeltaRunMethod` delegates rendering to the appropriate method (`RenderAWS`, `RenderTerraform`) via `Context.Render`. But it applies deletions the same way regardless of target, unless the target is a `DryRunTarget`: https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/default_methods.go#L62-L78. It seems like deletions should be handled differently depending on target--for example, deletions should be a no-op for terraform, since all we have to do is update and apply the terraform configuration.

Maybe this will be resolved by #1055; wdyt @kris-nova? Also, I'm very possibly just misunderstanding something--lmk if so!

cc @icereval

**Comment by justinsb** [comment]
Hmmm ... I think you might be right here - we shouldn't be deleting things in terraform mode.

**Comment by justinsb** [comment]
You're absolutely right - and I implemented something exactly like this in #1572  Sorry if you were planning on doing this - I was addressing another issue at the time, but no doubt this is what gave me the idea for a nice way to solve the problem.  Thanks!
