### ISSUE TITLE
Protokube gossip DNS seeds not filtered on cluster name

### ISSUE THREAD

**Issue by hugoboos** [kubernetes/kops#11162]
The protokube gossip DNS will use all the VMs beloning to a kOPS cluster, even if those VMs are from a different cluster.
There is no filtering on the name of the cluster.

This results in `No route to host` errors, because the 2 clusters are in a different OpenStack network.

I've not encountered problems with resolving DNS or anything like that. Only the logs flooding with connection errors to other VM's/members of the other clusters 

The code at https://github.com/kubernetes/kops/blob/master/protokube/pkg/gossip/openstack/seeds.go#L51 is only checking if the VM has a tag, not the value of the tag.

I've patched our installation with a custom protokube image. Patch can be found here: https://gitlab.com/commonground/haven/kops-images/-/blob/master/patches/001-protokube-openstack.patch

I can create a PR if you want. 

Kops version: `1.18.2 (git-84495481e4)`
Kubernetes version: `1.18.9`

**Comment by olemarkus** [comment]
Thanks for this. A PR would be much appreciated. 

/cc @zetaab

**Comment by zetaab** [comment]
Please do the pr, looks valid issue. We are not hitting this because we use one cluster per openstack project

**Comment by hugoboos** [comment]
I'm having problems siging the CLA. I rather not disclose my personal information, address etc.

**Comment by olemarkus** [comment]
The CLA is a requirement from the kubernetes organisation. There isn't any way around that, I'm afraid.

**Comment by kciredor** [comment]
Could perhaps one of you with a signed CLA re-create @hugoboos PR? It's a minor change with major outcome ;-)

**Comment by kciredor** [comment]
Thanks!
