### ISSUE TITLE
Kops create multiple igs for nodes instead of just one (one per AZ in AWS)

### ISSUE THREAD

**Issue by jmhostalet** [kubernetes/kops#11205]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.19.1 (git-8589b4d157a9cb05c54e320c77b0724c4dd094b2)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create cluster \
  --node-size t2.micro \
  --node-count 3 \
  --zones eu-west-2a,eu-west-2b \
  --master-size t2.medium \
  --master-zones eu-west-2a \
  --state s3://my-bucket \
  --cloud aws \
  --name=my-cluster \
  --vpc=vpc-bf435bbebe0c24e02 \
  --topology public \
  --networking kubenet

**5. What happened after the commands executed?**

A cluster is created with 3 igs

    NAME                    ROLE    MACHINETYPE     MIN     MAX     ZONES
    master-eu-west-2a       Master  t2.medium       1       1       eu-west-2a
    nodes-eu-west-2a        Node    t2.micro        2       2       eu-west-2a
    nodes-eu-west-2b        Node    t2.micro        1       1       eu-west-2b

**6. What did you expect to happen?**

A cluster is created with only 2 igs, for example:

    NAME                    ROLE    MACHINETYPE     MIN     MAX     ZONES
    master-eu-west-2a       Master  t2.medium       1       1       eu-west-2a
    nodes                   Node    t2.medium       0       10      eu-west-2a,eu-west-2b

as described in documentation https://kops.sigs.k8s.io/tutorial/working-with-instancegroups/

_By default, a cluster has: An instance group called nodes spanning all the zones; these instances are your workers_

**Comment by hakman** [comment]
@jmhostalet I think this works as expected at the moment, but docs were not updated. Please see: https://github.com/kubernetes/kops/issues/8152.
