### ISSUE TITLE
v1.19.1 SHA sum has changed

### ISSUE THREAD

**Issue by JD557** [kubernetes/kops#11214]
Issue similar to: #8973

Downloading kops from https://github.com/kubernetes/kops/archive/v1.19.1.tar.gz is returning a file with the shasum `046e5a88eb07b29538baa6f3913c13b0449a9c88e8c80631ad27fb22e33cf8b6`

According to https://github.com/Homebrew/homebrew-core/blob/ecd9108516d6ae41a42ca3ebc880378c19f3b9e8/Formula/kops.rb, that shasum was previously `c7b1c362712d75119e25e4ec06dc44ddc810808c0ae3ed24fb1ca47ebc2d6b7b`.

Any idea on what might have happened?

**Comment by bmelbourne** [comment]
@JD557 
I've verified the checksum is indeed incorrect, and it appears that the wrong checksum was applied during this commit.
https://github.com/Homebrew/homebrew-core/commit/9c0491b6848835dca7730b97542cd9c4d1a53d50

Feel feel to raise a PR in the `homecrew-core` project to fix the issue, or bump the kops version to `v1.20.0`.
