### ISSUE TITLE
Missing client certificate information: kubeadm certs check-expiration

### ISSUE THREAD

**Issue by KlavsKlavsen** [kubernetes/kops#11224]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
kops 1.19.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.19.9

**3. What cloud provider are you using?**
aws

I have an alert on the api-server metric apiserver_client_certificate_expiration_seconds_count{endpoint="https", instance="10.2.44.16:443", job="apiserver", namespace="default", service="kubernetes"}	472272

This metric is issued by api-server and shows a client certificate is within 7 days of needing renewal (according to f.ex. https://docs.kubermatic.com/kubermatic/v2.13/monitoring/runbook/ )

According to the official docs ( https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/ ) I should run: kubeadm certs check-expiration 
to figure out which cert has the issue.

This was raised in https://github.com/kubernetes/kops/issues/8773  - and possibly this is related to #8774  ?

When using kops to manage my cluster - HOW do I find the client certs that has a very short lifetime and is appearently nearing expiry?

**Comment by olemarkus** [comment]
Sounds like https://github.com/kubernetes/kops/issues/11211

You can manually check the certs mentioned there. I am pretty certain there is something wrong with these checks.

**Comment by KlavsKlavsen** [comment]
its a metric output by api-server.. either metric was misunderstood or api-server is outputting a bad metric ? I'll go verify manually on all nodes, using the openssl command.

**Comment by KlavsKlavsen** [comment]
It seems prometheus guys believe the alert to be correct: https://github.com/prometheus-operator/kube-prometheus/issues/1089 (which was created by same author who created #11211 )

I'm trying to find some docs on api-server as this metric is generated by api-server - based on the client certificates that authenticates against it..  found https://github.com/kubernetes/kubernetes/commit/f90bbc3d6bfba992831eb216161990eae1098ae5
kops isn't setting up some cert using the new rotate options? that might very well cause this exact alarm (and in such case alert should be set to alert differently)

**Comment by KlavsKlavsen** [comment]
I have also noiticed that ever since updating to 1.19 - setup by KOPS - our kubectl config goes bad after ~1 day.. which is "fixed" by updating it using: kops export kubecfg --name=mycluster --admin - and I can see that the client cert is indeed a new one every day.
I checked that cert:
        Issuer: CN = kubernetes
        Validity
            Not Before: Apr 11 07:12:42 2021 GMT
            Not After : Apr 14 01:12:42 2021 GMT
        Subject: O = system:masters, CN = kubecfg-Klavs Klavsen

So it seems KOPS 1.19 uses rotating admin certs.. and since we talk to the API-server all the time.. thats whats triggering the alarm.

**Comment by hakman** [comment]
@KlavsKlavsen I think you missed the release notes for 1.19:
https://kops.sigs.k8s.io/releases/1.19-notes/#changes-to-kubernetes-config-export
> To get the previous behavior, specify --admin=87600h

**Comment by hakman** [comment]
More details in case someone gets to this discussion someday:
https://github.com/prometheus-operator/kube-prometheus/issues/1089#issuecomment-818854038

**Comment by johngmyers** [comment]
@KlavsKlavsen I believe the metric to be misunderstood. Per the commit you mention, that measures the remaining lifetime of certificates used to authenticate to apiserver, not of any certificates that are necessarily on the node.

"Fixing" it by making clients use certificates that are valid for 10 years seems to be a bad security tradeoff.
