### ISSUE TITLE
Version S3 for state store

### ISSUE THREAD

**Issue by krisnova** [kubernetes/kops#1123]
This is critical, if a user nukes their state store accidentally (which I have totally done), this will give us the ability to get it back to another version..

Furthermore we really should be versioning our state store **anyway**, as users might want to see who/what was changed - and possibly revert back to a previous button.

This is a **must** in kops IMHO

More information on versioning in S3 [here in the official AWS docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html)

**Comment by kris-nova** [comment]
@justinsb @chrislovecnm 

I almost feel like kops should just do this automatically and not give the user another choice - what are your thoughts?

**Comment by chrislovecnm** [comment]
Automatically with override cability in the API

**Comment by KernelPanicAUS** [comment]
👋 I would like to take a stab at this, if no one is working on it..

**Comment by ms4720** [comment]
@KernelPanicAUS still yours?
