### ISSUE TITLE
error populating cluster spec: error building complete spec: options did not converge after 10 iterations

### ISSUE THREAD

**Issue by eluricharter** [kubernetes/kops#11244]
I am trying to add the container proxy in my cluster configuration and getting the below error after adding below assets

**assets:
containerProxy: example.com/css-devops**

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# error populating cluster spec: error building complete spec: options did not converge after 10 iterations
#
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  generation: 5
  name: k8s.1.17.6.shared.engprod-spectrum.net
spec:
  api:
    loadBalancer:
      type: Internal
  assets:
    containerProxy: css-devops.artifactory.se-charter.net/css-devops
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://k8s.1.17.6.shared.engprod-spectrum.net/k8s.1.17.6.shared.engprod-spectrum.net
  dnsZone: shared.engprod-spectrum.net
  docker:
    version: 19.03.11
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1d
      name: d
    - encryptedVolume: true
      instanceGroup: master-us-east-1e

**Comment by hakman** [comment]
As I said before, there is a template when creating the issue. Please use it.
