### ISSUE TITLE
Hubble Relay cannot reach Cilium agents

### ISSUE THREAD

**Issue by joulaud** [kubernetes/kops#11246]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** 

`Version 1.19.1 (git-8589b4d157a9cb05c54e320c77b0724c4dd094b2)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Make a cluster using cilium and enabling hubble. e.g.
```yaml
  networking:
    cilium:
      enablePrometheusMetrics: true
      hubble:
        enabled: true
        metrics:
          - dns
```
`kops create` then `kops update cluster`

Trying to use hubble-relay.

**5. What happened after the commands executed?**

```
$ kubectl port-forward -n kube-system svc/hubble-relay 4245:80 &
[1] 2561012
Forwarding from 127.0.0.1:4245 -> 4245
Forwarding from [::1]:4245 -> 4245
$ export HUBBLE_DEFAULT_SOCKET_PATH=localhost:4245
$ hubble status
Handling connection for 4245
Healthcheck (via localhost:4245): Ok
Current/Max Flows: 0/0
Flows/s: N/A
Connected Nodes: 0/12
Unavailable Nodes: 12
  - ip-10-XX-XX-XXX.eu-west-3.compute.internal
  - ip-10-XX-XX-XXX.eu-west-3.compute.internal
  - ip-10-XX-XX-XX.eu-west-3.compute.internal
  - ip-10-XX-XX-XXX.eu-west-3.compute.internal
  - ip-10-XX-XX-XX.eu-west-3.compute.internal
  - ip-10-XX-XX-XXX.eu-west-3.compute.internal
  - ip-10-XX-XX-XX.eu-west-3.compute.internal
  - ip-10-XX-XX-XX.eu-west-3.compute.internal
  - ip-10-XX-XX-XX.eu-west-3.compute.internal
  - ip-10-XX-XX-XX.eu-west-3.compute.internal
  - and 2 more...
```

We can see no Cilium node is reachable.

**6. What did you expect to happen?**

Either no hubble-relay deployed or a working one.

**9. Anything else do we need to know?**

The problem is that hubble-relay needs Cilium agent to listen to hubble on TCP port 4244.

As stated in [cilium documentation](https://docs.cilium.io/en/v1.8/operations/troubleshooting/#observing-flows-with-hubble-relay) there is security implications of activating this by default.

Best course of action would be to add a RelayEnabled (or other better name) key to Hubble spec.
Value of this key should be false by default.
On the addon template, RelayEnabled would condition the deployment of hubble-relay related resources (Deployment, ConfigMap...)  and when enabled it would add `hubble-listen-address: ":4244"` to the Cilium ConfigMap.

**Comment by joulaud** [comment]
Note that the security implications are quite different in Cilium 1.8 and Cilium 1.9 as [mTLS between cilium-agent and hubble-relay][mTLS] was [added in the meantime][PR12906].

[mTLS]: https://docs.cilium.io/en/v1.9/concepts/observability/hubble-configuration/#use-custom-tls-certificates
[PR12906]: https://github.com/cilium/cilium/pull/12906

**Comment by olemarkus** [comment]
kOps doesn't use mTLS yet unfortunately, as it doesn't have any good way of provisioning the TLS cert. We do have a new feature that can use cert-manager for provisioning certs, but scheduling cert-manager itself depends on cilium running.

**Comment by joulaud** [comment]
If hubble-relay deployment is optional then it will be at the discretion of the admin to choose what he wants (mTLS or not).

**Comment by olemarkus** [comment]
I'll dig into this a bit. I plan on doing an e2e test with more advanced kops configuration and that can also include hubble.

I am not sure relay or not really matters when it comes to mTLS. Without relay, the UI or whatever you use to talk to agents just talk directly to the agents. The result is similar, but with less scalability. That was why I didn't make relay configurable. The benefits of not using relay is unclear, but the downsides are obvious.

**Comment by joulaud** [comment]
1. With Hubble activated without relay we can yet generate specific hubble metrics and use `hubble observe` on each individual Cilium pod (using `kubectl exec` to the pod).

2. With Hubble relay activated you gain a way to aggregate information cluster-wide and to use the UI, at the cost of wide-opening port to each Cilium agent (possibly protected by mTLS).

At this point kOps makes believe it support relay by deploying the hubble-relay in the cluster but it does not work as the port is not open on the agent. I still support making this configurable as at the moment I want at least 1 and am not sure about 2 (at least without mTLS).

Thanks for digging this anyway.

**Comment by johngmyers** [comment]
Can't we provision the mTLS client certs out of kops-controller?

**Comment by olemarkus** [comment]
It's something like that I had in mind. Do you think it is necessary to have a dedicated CA?

**Comment by johngmyers** [comment]
A separate PKI would be more secure. No sense allowing things to authenticate to places they don't need to.

**Comment by olemarkus** [comment]
Cilium 1.10 will be out the coming weeks, and my focus for 1.21 will be on getting that one in. I can probably do template changes and such (e.g fix the hubble port), but PKI probably has to wait for 1.22 unless someone else is interested in looking at this.

**Comment by joulaud** [comment]
Seems fixed with https://github.com/kubernetes/kops/pull/11314#discussion_r620869953 which makes Hubble depends on cert-manager and forces mTLS activation.

**Comment by olemarkus** [comment]
Yep.

/close
