### ISSUE TITLE
unable to determine machine architecture for InstanceGroup "master-us-west-2a": unsupported architecture for instance type "t2.micro": i386

### ISSUE THREAD

**Issue by leiw324** [kubernetes/kops#11268]
Hello,

Please help:
![image](https://user-images.githubusercontent.com/33790160/115420570-d4a8ea80-a22d-11eb-9320-b1cff42b4a30.png)

**Comment by hakman** [comment]
Hello, please create a new issue using the template.

**Comment by olemarkus** [comment]
Hello. Don't use t2.micro. It is not supported. You havet to use amd64 or arm instances
