### ISSUE TITLE
Cannot create cluster

### ISSUE THREAD

**Issue by leiw324** [kubernetes/kops#11279]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.20.0 (git-8ea83c6d233a15dacfcc769d4d82bea3f530cf72)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
 
Not install yet

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create cluster --name=kops.marvelconnect.com --state=s3://wilson-testing --zones=us-east-1a --master-size=t2.micro --master-count=3 --node-size=t2.micro --node-count=3 --dns-zone=kops.marvelconnect.com

**5. What happened after the commands executed?**

I0421 13:12:23.507859   27328 new_cluster.go:238] Inferred "aws" cloud provider from zone "us-east-1a"
W0421 13:12:23.508006   27328 new_cluster.go:700] Running with masters in the same AZs; redundancy will be reduced
I0421 13:12:23.508049   27328 new_cluster.go:962]  Cloud Provider ID = aws
I0421 13:12:23.568226   27328 subnets.go:180] Assigned CIDR 172.20.32.0/19 to subnet us-east-1a

unable to determine machine architecture for InstanceGroup "master-us-east-1a-1": unsupported architecture for instance type "t2.micro": i386

**6. What did you expect to happen?**

Create k8s cluster

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```
Not install k8s yet

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by olemarkus** [comment]
We do not build binaries for i386. You have to use either arm64 or amd64 instances. You also need to use sufficiently large instances. t3.small may work for very small clusters, but t3.medium is recommended.

**Comment by rifelpet** [comment]
We could probably make the error message clearer and mention that the instance type isn't supported and to use a different one.

**Comment by hakman** [comment]
@rifelpet Maybe validation should catch this corner case.

**Comment by ironytr** [comment]
> downloaded Version 1.21.0-alpha.1 and can create cluster. waiting for results

working
