### ISSUE TITLE
Understand (and rename?) RBAC and service account for AWS storage addon

### ISSUE THREAD

**Issue by nckturner** [kubernetes/kops#11283]
Currently `storage-aws.addons.k8s.io` includes [a ClusterRole and ClusterRoleBinding](https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.15.0.yaml.template#L46-L85) with the name `system:aws-cloud-provider`.  These were added to the storage addon in https://github.com/kubernetes/kops/pull/6899, because it was removed from upstream in https://github.com/kubernetes/kubernetes/pull/66635.  The new external cloud controller manager addon for aws (`aws-cloud-controller.addons.k8s.io`) uses the name: `system:cloud-controller-manager` for its service account and RBAC, but one difference is that the service account `aws-cloud-controller.addons.k8s.io` is managed in the addon yaml, whereas the service account for `storage-aws.addons.k8s.io` is created elsewhere (I haven't found it yet).  

To better understand the use of the `aws-cloud-provider` service account referenced in the RBAC, I'd like to answer the following questions:
1. When and how is the aws-cloud-provider service account created?
   According to a comment in the PR, perhaps by the client builder code.
2. What is it used for?  
   According to the comment by @gnufied in the linked PR, its used for "tainting the nodes when volumes are stuck in Attaching state for too long."
3. What cluster configurations require this RBAC and service account?
   Here I'm assuming its clusters with kube-controller-manager, with `--cloud-provider=aws` (no external cloud provider).

Perhaps we should do one or more of the following: 
1. rename the `aws-cloud-provider` service account and RBAC to something more specific, 
2. separate it from the storage classes, (which are probably shared with CSI and still useful) and 
3. deprecate it (on the same timeline as the in-tree provider).

**Comment by olemarkus** [comment]
The `aws-cloud-provider` service account was created by the legacy aws cloud provider, I believe. Good question if the external cloudprovider also creates them or if kOps should in this case. Or if it is indeed needed. 

In the mix here, there is also the aws-ebs-csi-driver.addons.k8s.io addon that also provisions its own SA.

My guess is that we should not install those roles if the external CSI driver is enabled, and deprecate it with the in-tree provider as you say.
