### ISSUE TITLE
Using ETCD_LISTEN_METRICS_URLS

### ISSUE THREAD

**Issue by jankosecki** [kubernetes/kops#11280]
Hi,
I tried to use ETCD_LISTEN_METRICS_URLS with our existing cluster, but after applying and rolling master it still didn't work and the metrics are available only on `https://:4001`. After a bit of digiig I've found the line from `etcd-manager`

```
2021-04-21 12:05:42.741968 W | pkg/flags: unrecognized environment variable ETCD_LISTEN_METRICS_URLS=http://0.0.0.0:2456
2021-04-21 12:05:42.742123 I | etcdmain: etcd Version: 3.2.18
```
Our cluster is quite old hence the version of `etcd` set in `kops edit cluster` is very old. I understand that ETCD_LISTEN_METRICS_URLS is available since v3.3.

I couldn't find any docs about ETCD upgrades - is it safe to simply change the version via `kops edit cluster` to from `3.2.18` to latest `3.4` or are there any steps that I should be aware of?

@olemarkus sorry, got focused on an issues and didn't realise my question was submitted without finishing. I've updated it now

**Comment by olemarkus** [comment]
https://kops.sigs.k8s.io/cluster_spec/#etcd-metrics
