### ISSUE TITLE
not able to rolling update cluster from 1.20.x -> 1.21.0

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#11298]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master 

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.21.0

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops rolling-update...

**5. What happened after the commands executed?**

the new kops-controllers in 1.21.0 nodes are going to crashloopbackoff

```
% kubectl logs kops-controller-n9qmq
E0423 14:10:24.603458       1 cluster.go:160] controller-runtime/manager "msg"="Failed to get API Group-Resources" "error"="Unauthorized"
E0423 14:10:24.603514       1 deleg.go:144] setup "msg"="unable to start manager" "error"="Unauthorized"
%
```

and then the rolling update fails.

**Comment by johngmyers** [comment]
This appears to be an issue with kops-controller permissions, not rolling update.

**Comment by zetaab** [comment]
I can reproduce this problem in both: AWS and OpenStack

**Comment by zetaab** [comment]
error is coming from here https://github.com/kubernetes/kops/blob/master/vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go#L158

**Comment by zetaab** [comment]
I think I found the api call that is failing

```
% kubectl logs kops-controller-85mf6
E0503 16:21:01.854064       1 cluster.go:160] controller-runtime/manager "msg"="Failed to get API Group-Resources" "error"="Unauthorized"
E0503 16:21:01.854232       1 deleg.go:144] setup "msg"="unable to start manager" "error"="Unauthorized"
```

and then in apiserver

```
E0503 16:21:01.851874       1 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
I0503 16:21:01.852134       1 httplog.go:89] "HTTP" verb="GET" URI="/api?timeout=32s" latency="582.668µs" userAgent="kops-controller/v0.0.0 (linux/amd64) kubernetes/$Format" srcIP="127.0.0.1:53370" resp=401
```

**Comment by zetaab** [comment]
it looks like the problem is that `/src/kubernetes/service-account.key` is regenerated somehow. That private key should be same in all masters, but when upgrading from older kops to kops master - the key is regenerated. The private key value does not match to old masters. I do have 3 masters, and 2 old masters have the same private key and the newer one has different (which is failing).

**Comment by johngmyers** [comment]
That commit has code to copy the old `master` key to `service-account`. It could be that when the `service-account` key doesn't exist the VFS implementation is incorrectly returning an error where `os.IsNotExist()` returns false. The VFS API does appear to require `os.IsNotExist()` for such cases.
