### ISSUE TITLE
Feature: Support Graceful Node Shutdown

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#11292]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Add support for Graceful Node Shutdown.

**2. Feel free to provide a design supporting your feature request.**
 
Add `ShutdownGracePeriod` and `ShutdownGracePeriodCriticalPods` fields to `KubeletConfigSpec`.

As Kubernetes appears to not have added kubelet flags for these settings, this will mean we need to refactor kubelet configuration to use a `KubeletConfiguration`.

**Comment by dmitrievav** [comment]
Thank you @hakman

While it is not implemented we have to deal with kops hooks and file assets as a workaround.
