### ISSUE TITLE
kops 1.21 in AWS requires SQS but its not documented

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#11299]
I tried to install new clean cluster with 1.21 kops alpha 3. Everything went almost fine. However, when I tried to delete the cluster I got 

```
error listing SQS queues: AccessDenied: Access to the resource https://sqs.eu-west-1.amazonaws.com/ is denied.
```

Access need to SQS should be documented in release-notes.

**Comment by danports** [comment]
I ran into this when deploying and then deleting a test cluster today. I found this issue, but what's still missing is a description of the SQS permissions needed on the [Getting Started page](https://kops.sigs.k8s.io/getting_started/aws/#setup-iam-user), e.g.:
`aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonSQSFullAccess --group-name kops`
`aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess --group-name kops`

**Comment by yeus** [comment]
I don't understand..   this issue still exists and is not in the descriptions? would vote for reopening this until there is something in the documentation...

**Comment by olemarkus** [comment]
This is missing from `docs/getting_started/aws.md`?
Would you be able to do a PR?

**Comment by yeus** [comment]
@olemarkus there you go ;).
