### ISSUE TITLE
instancegroup resize is not graceful

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#113]
When shrinking an instancegroup, we should probably:
- set min to new min
- gracefully evict work from 'victim' nodes
- gradually scale down to target size

Or similar!

**Comment by chrislovecnm** [comment]
/lifecycle frozen
/remove-lifecycle rotten

This is a great starter issue

**Comment by olemarkus** [comment]
This can technically be achieved by both NTH (which will hook into the ASG lifecycle) and by graceful shutdowns. I don't think we need to do more here. And we have not had users complaining about this.

/close
