### ISSUE TITLE
Question: Why do utility subnets get more addresses than private subnets?

### ISSUE THREAD

**Issue by jmcarp** [kubernetes/kops#1131]
As far as I can tell, in the private topology, utility subnets get 1/8 of the range specified in the VPC CIDR, and private subnets get 1/64. I'm wondering why the subnet CIDRs are set like this, since the utility subnets have very little in them (NAT gateways and bastions), and the private subnets hold the masters and nodes. It seems like we'd be more likely to run out of addresses in the private subnets than in the utility subnets.

cc @icereval

**Comment by justinsb** [comment]
I think this was just a bug - sorry!  The ratio for newly created clusters should now be the other way round - big private subnets, small utility subnets.

Going to close, but reopen if this isn't the case.
