### ISSUE TITLE
OpenStack: etcd-manager does not always mount volumes resulting in invalid cluster creation

### ISSUE THREAD

**Issue by kciredor** [kubernetes/kops#11323]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.19.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.19.9

**3. What cloud provider are you using?**
OpenStack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster, kops update cluster --yes

**5. What happened after the commands executed?**
One out of two times one (only one) of the masters does not become healthy. It appears one of the two etcd volumes is not being formatted and mounted to the master node by etcd-manager.

**6. What did you expect to happen?**
Every cluster creation should result in every master having two etcd volumes resulting in a valid cluster.

**9. Anything else do we need to know?**
This issue started with kops 1.19, with kops 1.18 it was neverthere. By hardcoding other etcd-manager versions into my kops binary and hosting etcd-manager docker images myself, I was able to pinpoint the start of the issue between etcd-manager versions 3.0.20200531 (kops 1.18) and 3.0.20210122 (kops 1.19) to exact version 3.0.20201117 which starts creating failed clusters.

I'm having a hard time finding out which exact commit in etcd-manager 3.0.20201117 introduced the problem though. I've reverted some commits and did some testing, these are the ones I was suspecting but ended up not being the troublemakers:
- https://github.com/kopeio/etcd-manager/pull/347
- https://github.com/kopeio/etcd-manager/pull/351
- https://github.com/kopeio/etcd-manager/pull/358

It's quite a big list of changes between 3.0.20200531 and 3.0.20201117 ;-) Anyone got an idea what's going on here?

Cheers,
kciredor

**Comment by rifelpet** [comment]
Can you post etcd-manager logs from a host in which the issue occurs?

**Comment by kciredor** [comment]
Ofcourse, here you go. This is etcd.log. Same thing can happen with etcd-events.log. It's either etcd, or etcd-events getting in trouble.

`etcd-manager
I0426 13:18:09.656532    6229 volumes.go:206] Found project="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
I0426 13:18:09.656658    6229 volumes.go:215] Found instanceName="master-amsterdam1-7-1-dv-dev-k8s-local"
I0426 13:18:09.955072    6229 volumes.go:235] Found internalIP="10.0.32.64" and zone="amsterdam1"
I0426 13:18:09.955126    6229 main.go:291] Mounting available etcd volumes matching tags [KubernetesCluster=dv-dev.k8s.local k8s.io/etcd/main k8s.io/role/master=1]; nameTag=k8s.io/etcd/main
I0426 13:18:09.955162    6229 volumes.go:309] Listing Openstack disks in xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/amsterdam1
I0426 13:18:10.381018    6229 mounter.go:294] Trying to mount master volume: "d024da28-4963-40d6-9b69-1ed7cdb6a669"
W0426 13:18:10.902020    6229 mounter.go:299] Error attaching volume "d024da28-4963-40d6-9b69-1ed7cdb6a669": error attaching volume d024da28-4963-40d6-9b69-1ed7cdb6a669 to server ea1c063d-3512-4f0f-b584-1da32ec33505: Bad request with: [POST https://xxxxx:8774/v2.1/servers/ea1c063d-3512-4f0f-b584-1da32ec33505/os-volume_attachments], error message: {"badRequest": {"code": 400, "message": "Invalid input received: Invalid volume: Volume d024da28-4963-40d6-9b69-1ed7cdb6a669 status must be available or downloading to reserve, but the current status is in-use. (HTTP 400) (Request-ID: req-f5bd664a-a8b3-4fdb-a7aa-f74aa6c19658)"}}
I0426 13:18:10.902165    6229 mounter.go:294] Trying to mount master volume: "36f07f1c-f3e7-461a-89eb-d45bf39240c3"
I0426 13:18:11.379120    6229 mounter.go:308] Currently attached volumes: [0xc0006d2480]
I0426 13:18:11.379507    6229 mounter.go:72] Master volume "36f07f1c-f3e7-461a-89eb-d45bf39240c3" is attached at "/dev/vdd"
I0426 13:18:11.379617    6229 mounter.go:86] Doing safe-format-and-mount of /dev/vdd to /mnt/master-etcd-6.etcd-main.dv-dev.k8s.local
I0426 13:18:11.379893    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:18:11.698782    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:18:17.699193    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:18:18.026724    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:18:24.027130    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:18:24.354981    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:18:30.355463    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:18:30.682683    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:18:36.683407    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:18:37.018652    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:18:43.019156    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:18:43.346802    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:18:49.347489    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:18:49.670824    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:18:55.671283    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:18:55.998525    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:19:01.999139    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:19:02.336105    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:19:08.336694    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:19:08.672517    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:19:14.673101    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:19:14.994942    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:19:20.995327    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:19:21.343629    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:19:27.344021    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:19:27.662865    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:19:33.663280    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:19:33.982831    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:19:39.983366    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:19:40.316346    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:19:46.316810    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:19:46.634795    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:19:52.635202    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:19:52.963100    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:19:58.963559    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:19:59.310110    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:20:05.310743    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:20:05.638669    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:20:11.640356    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:20:11.973164    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:20:17.973595    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:20:18.323111    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:20:24.323493    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:20:24.646817    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:20:30.647255    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:20:30.972878    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:20:36.973414    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:20:37.298783    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:20:43.299199    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:20:43.631661    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:20:43.631747    6229 mounter.go:121] Waiting for volume "36f07f1c-f3e7-461a-89eb-d45bf39240c3" to be mounted
I0426 13:20:44.632066    6229 volumes.go:408] Could not find device path for volume; scanning buses
I0426 13:20:44.958943    6229 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0426 13:20:50.959496    6229 volumes.go:408] Could not find device path for volume; scanning buses

<cut: from there the scanning buses / waiting to be mounted keeps repeating itself>`

'executable not found in path' I think points to udevadm (from openstack/volumes.go 'probeVolume') which works fine logging in to the server with SSH (/usr/bin).

I do see the executable file not found in every single etcd log btw, including the succeeded ones, but for one node it repeats only once and for the other 20 times and starts working. For a failing node it never stops repeating.

**Comment by hakman** [comment]
@kciredor I can create an etcd-manager image that may fix the issue if you want to try.
Probably `udev` needs to be added to this list:
https://github.com/kubernetes-sigs/etcdadm/blob/c09b9e2d7cca67372328772f483c1f3249f25247/etcd-manager/images/base/BUILD#L11-L24.

**Comment by hakman** [comment]
@kciredor If you don't mind, could you test using this image?
```
gcr.io/k8s-staging-etcdadm/etcd-manager:v20210428-v0.1.3-729-g7530bcea
```

**Comment by kciredor** [comment]
Thanks @hakman! My first test run is fine, I'll try again a couple of times today.

**Comment by hakman** [comment]
Great, thanks :).

**Comment by kciredor** [comment]
I'm afraid the second attempt resulted in another scanning busses issue:

```
I0428 09:14:39.928221    5379 volumes.go:419] Error scanning buses: exit status 127
I0428 09:14:45.929438    5379 volumes.go:417] Could not find device path for volume; scanning buses
```

Manually running sudo udevadm trigger on the 2 out of 7 master nodes running into this problem gives me exit 0. Not sure how to debug this.

**Comment by hakman** [comment]
If you exec from the pod `/sbin/udevadm` does it do anything?

**Comment by kciredor** [comment]
Good one ;-)

```
/sbin/udevadm: error while loading shared libraries: libkmod.so.2: cannot open shared object file: No such file or directory
```

**Comment by hakman** [comment]
> Still interesting to me how one etcd-manager pod becomes healthy, and the other etcd-manager pod is missing a binary or library.

Same here, but no idea how to reproduce and check that.

One more:
`gcr.io/k8s-staging-etcdadm/etcd-backup:v20210429-v0.1.3-733-g4703d502`

**Comment by kciredor** [comment]
From the pod:

```
# /sbin/udevadm trigger
Running in chroot, ignoring request.
```

/var/log/etcd.log now runs into a loop:

```
I0429 11:12:04.081904    5665 volumes.go:417] Could not find device path for volume; scanning buses
I0429 11:12:10.411634    5665 volumes.go:417] Could not find device path for volume; scanning buses
I0429 11:12:16.748487    5665 volumes.go:417] Could not find device path for volume; scanning buses
I0429 11:12:23.084319    5665 volumes.go:417] Could not find device path for volume; scanning buses
I0429 11:12:29.417736    5665 volumes.go:417] Could not find device path for volume; scanning buses
I0429 11:12:29.756037    5665 mounter.go:121] Waiting for volume "b5162d3c-e1f6-45c9-b5bd-14ea4ba485d2" to be mounted
I0429 11:12:30.756964    5665 volumes.go:417] Could not find device path for volume; scanning buses
I0429 11:12:37.096833    5665 volumes.go:417] Could not find device path for volume; scanning buses
I0429 11:12:43.445428    5665 volumes.go:417] Could not find device path for volume; scanning buses
I0429 11:12:49.789934    5665 volumes.go:417] Could not find device path for volume; scanning buses
I0429 11:12:56.118686    5665 volumes.go:417] Could not find device path for volume; scanning buses
I0429 11:13:02.464056    5665 volumes.go:417] Could not find device path for volume; scanning buses
I0429 11:13:08.796976    5665 volumes.go:417] Could not find device path for volume; scanning buses
```

**Comment by hakman** [comment]
etcd-manager runs this with `nsenter` so you would not see the "Running in chroot, ignoring request.".
```
nsenter --mount=/rootfs/proc/1/ns/mnt -- /sbin/udevadm trigger
```

**Comment by kciredor** [comment]
Using that command it gives me exit 0 (loop is still active though, keeps "Waiting for volume").

**Comment by kciredor** [comment]
```
openstack volume list

| b5162d3c-e1f6-45c9-b5bd-14ea4ba485d2 | etcd-1.etcd-main.dv-dev.k8s.local   | in-use |   20 | Attached to master-amsterdam1-6-1-dv-dev-k8s-local on /dev/vdd  |

<cut>

| 055c15f8-45ec-4b48-aa79-c37b81e2156b | etcd-1.etcd-events.dv-dev.k8s.local | in-use |   20 | Attached to master-amsterdam1-3-1-dv-dev-k8s-local on /dev/vdd  |
```

The first one is etcd1-main which is having trouble getting mounted on the master node. The second one is etcd1-events, which is mounted on _another node_. Is that 'normal'?

**Comment by hakman** [comment]
I don't think so, but I am not that familiar with the openstack implementation. Maybe @olemarkus has some thoughts.

**Comment by olemarkus** [comment]
Sorry, I am not that familiar. My guess is that there is a mismatch with tags. I think perhaps @zetaab is the one with the most knowledge of how this works now.

**Comment by zetaab** [comment]
https://github.com/kopeio/etcd-manager/blob/e6cc5c083a951d119c1aee44d379322e2f9ce08e/pkg/volumes/openstack/volumes.go#L285

if you have only availability zone in computes + volumes, this is possible and normal. In case of many availability zones in computes + volumes this is not normal and should not happen. Which case matches to your setup?

**Comment by kciredor** [comment]
This is single availability zone indeed.

Here's the output of all volume show's:

```
$ openstack volume show cb2bef34-e09c-42fa-9822-7b9f87477860 | grep properties
| properties                   | KubernetesCluster='dv-dev.k8s.local', k8s.io/etcd/main='etcd-2/etcd-1,etcd-2,etcd-3', k8s.io/role/master='1'                                                                                                                                                                                                  

$ openstack volume show 5f6b611a-6688-4357-9adb-176f15f131ef | grep properties
| properties                   | KubernetesCluster='dv-dev.k8s.local', k8s.io/etcd/main='etcd-3/etcd-1,etcd-2,etcd-3', k8s.io/role/master='1'                                                                                                                                                                                                 

$ openstack volume show 5c44493d-525e-4b07-b078-6e258e3c858d | grep properties
| properties                   | KubernetesCluster='dv-dev.k8s.local', k8s.io/etcd/main='etcd-1/etcd-1,etcd-2,etcd-3', k8s.io/role/master='1'                                                                                                                                                                                                  

$ openstack volume show bd8d6578-82e6-4680-9109-064cbc7c5bdf | grep properties
| properties                   | KubernetesCluster='dv-dev.k8s.local', k8s.io/etcd/events='etcd-3/etcd-1,etcd-2,etcd-3', k8s.io/role/master='1'                                                                                                                                                                                                

$ openstack volume show afac5a39-f068-407a-bcdf-eedbd5e0d108 | grep properties
| properties                   | KubernetesCluster='dv-dev.k8s.local', k8s.io/etcd/events='etcd-2/etcd-1,etcd-2,etcd-3', k8s.io/role/master='1'                                                                                                                                                                                               

$ openstack volume show abf662ac-bdd3-4d61-af0a-c8bccbe0f2a0 | grep properties
| properties                   | KubernetesCluster='dv-dev.k8s.local', k8s.io/etcd/events='etcd-1/etcd-1,etcd-2,etcd-3', k8s.io/role/master='1'
```

(The issue started with kops 1.19 coming from 1.18)

**Comment by zetaab** [comment]
I am sorry, I do not have idea what is wrong. Anyways, etcd-manager is not using volumes from /dev/vd* it is using those under /dev/disk/by-id. Can you check code https://github.com/kopeio/etcd-manager/blob/e6cc5c083a951d119c1aee44d379322e2f9ce08e/pkg/volumes/openstack/volumes.go#L346-L373 and check can you find volumes from that path? `ls -l /dev/disk/by-id/` and then check does any candidateDeviceNodes match to your use-case.

**Comment by hakman** [comment]
@kciredor There's a new etcd-manager version that was released last week. Could you use that for further debugging, as it has various updates that may help?
https://github.com/kubernetes/kops/pull/11098

**Comment by kciredor** [comment]
Interesting. Using the new image now. But this time, on the master node, there was no /dev/vdc only /dev/vdd (and the corresponding /dev/disk/by-id/virtio-xxx symlinks). Running udevadm trigger on the master node itself, made /dev/vdd and the by-id symlink appear resulting in an immediately mounted etcd-events volume next to the existing etcd-main.

Logs reflect this after a long loop of scanning busses as well:
```
I0510 13:53:10.175364    6041 mounter.go:121] Waiting for volume "3def81ce-becc-430f-a3bf-a65ce95b823f" to be mounted
I0510 13:53:11.176163    6041 volumes.go:417] Could not find device path for volume; scanning buses
I0510 13:53:17.507287    6041 volumes.go:417] Could not find device path for volume; scanning buses
I0510 13:53:23.845494    6041 volumes.go:417] Could not find device path for volume; scanning buses
I0510 13:53:30.188972    6041 volumes.go:417] Could not find device path for volume; scanning buses
I0510 13:53:36.523191    6041 volumes.go:366] Found disk attached as "virtio-3def81ce-becc-430f-a"; full devicepath: /rootfs/dev/disk/by-id/virtio-3def81ce-becc-430f-a
```

On the etcd-events container udevadm is available as well. Kind of looks like udevadm trigger from the container, which is actually what happens from the code, should have done the trick but did not.

So with the 'old' image I'm having a does-not-mkfs.ext4 problem and with the new image I'm having a udevadm-does-not-work problem, it appears ;-)

**Comment by kciredor** [comment]
Just a heads up now that lifecycle/stale was applied, this is still an issue for us upgrading to Kops 1.20.2 and etcd-manager 1.20.2.

**Comment by hakman** [comment]
@kciredor Maybe you are more lucky with the latest etcd-manager image:
https://github.com/kubernetes/kops/commit/78f136705e247cf250208fe722f967b0273ed03d
