### ISSUE TITLE
Ability to renew etcd-client certificates issued for the apiserver without having to restart the control plane nodes.

### ISSUE THREAD

**Issue by semoac** [kubernetes/kops#11355]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Right now `etcd-manager` takes care of renewing certificates located on `/etc/kubernetes/pki/etcd-*` but only nodeup generates client certificates for `/etc/kubernetes/pki/kube-apiserver`.

There is a way to renew those certificates without having to recreate the master nodes? Any plans on having a controller + reloader to take care of this?

Any plans on making the `validHours` customizable?

**2. Feel free to provide a design supporting your feature request.**

No idea but this seems to be the code generating the code.

https://github.com/kubernetes/kops/blob/8f0aa3313189f0956d7a3efc5ed0ef868071549e/nodeup/pkg/model/etcd_manager_tls.go#L78

https://github.com/kubernetes/kops/blob/97869057129b30ea284c3ed1bdf1db36e752701d/upup/pkg/fi/nodeup/nodetasks/issue_cert.go#L145

**Comment by olemarkus** [comment]
Could you explain what you need this for?

**Comment by olemarkus** [comment]
Can we close this one?
