### ISSUE TITLE
Error listing nodes when passing the custom subnets and utility subnet

### ISSUE THREAD

**Issue by taragurung** [kubernetes/kops#11380]
**1. kops version .**
Version 1.19.0

**2. Trying to install kubernetes version.**
1.19.0

**3. What cloud provider are you using?**
AWS
**4. This is my kops create with private hosted zone**
```
#export KOPS_CLUSTER_NAME=mysite-stage.k8s.com
#export KOPS_STATE_STORE=s3://cluster.mysite-stage.k8s.com

kops create cluster \
--state=${KOPS_STATE_STORE} \
--node-count=3 \
--kubernetes-version=1.19.0 \
--master-size=t2.small \
--node-size=t2.small \
--zones=eu-west-1a,eu-west-1b,eu-west-1c \
--master-zones=eu-west-1a,eu-west-1b,eu-west-1c \
--name=${KOPS_CLUSTER_NAME} \
--dns private \
--master-count 3 \
--vpc vpc-0764987f79a45e522 \
--subnets=subnet-08f4525d6ec6e8218,subnet-09b344af164178e51,subnet-0d58df14320463ed8 \
--utility-subnets=subnet-07113ad2ab8162aac,subnet-0cf952e3459e67d5a,subnet-0df471cadbbec4841 \
--networking calico \
--topology private \
--api-loadbalancer-type=internal #to make loadblancer private
```
**5. The cluster is not validated**
`W0504 13:15:09.736617    2535 validate_cluster.go:173] (will retry): unexpected error during validation: error listing nodes: an error on the server ("") has prevented the request from succeeding (get nodes)`
**6. What did you expect to happen?**
`kubectl get nodes` working & validation to pass

**Details: **
I am trying to set it up on the existing VPC, which also has some subnets already being used. So if I just pass the VPC-ID it will have the conflict issue in the subnet so I created 6 subnets and passed them as --subnets and --utility-subnets. 

**Issues **
1. It is not able to assume non-conflicting subnets so I have to pass the subnet. I have tested on VPC where there are no subnets in such a scenario it will create a subnet and work as expected. But as I gave the custom subnets to mitigate conflicts I am having issues with server validations. Waited more than 10 minute

2. It successfully creates the IG even though the validation won't pass which will show all nodes when I do 
`kops get ig` BUT

`kubectl get nodes won't work`

**7. Anything else do we need to know?**
What might have gone wrong? Did I pass the wrong subnets. Do I have to make the utility subnets public before passing it as I just created all the subnet without associating with any Route-table.

**Comment by hakman** [comment]
> Do I have to make the utility subnets public before passing it as I just created all the subnet without associating with any Route-table.

Once you use your own subnets, you also own the routing. Should work ok after that.

**Comment by taragurung** [comment]
Hoping that to be expected behavior but not working. @hakman

**Comment by hakman** [comment]
You are the only person that can debug what's wrong. Maybe SSH to the nodes and check if internet connectivity works.
This may help too: https://kops.sigs.k8s.io/operations/troubleshoot/.

**Comment by taragurung** [comment]
This is the only thing I get to see on logs. not sure where are the issues. 

```W0504 15:21:03.110535    3296 validate_cluster.go:173] (will retry): unexpected error during validation: error listing nodes: an error on the server ("") has prevented the request from succeeding (get nodes)```

**Comment by taragurung** [comment]
And i am not able to ssh as well to the nodes,to debug further

**Comment by hakman** [comment]
If you are not able to ssh to the nodes, then routing settings are not correct.
