### ISSUE TITLE
Is KOPS_REGISTRY a better name than KOPS_STATE_STORE?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#114]
"registry" seems to convey the idea a lot more clearly.

We could accept the old name for a while, but we should only switch once!

**Comment by justinsb** [comment]
It is a better name, but I think maybe we should address this when/if we figure out how to do multiple clouds - that will likely entail splitting the state store, and thus more naming.

**Comment by chrislovecnm** [comment]
Too late to change now :P Close??

**Comment by chrislovecnm** [comment]
I am closing this, too late to change now :)
