### ISSUE TITLE
We should print a message when we are using `~/.ssh/id_rsa.pub`

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1140]
Just to make it clear that we are defaulting to it

**Comment by yissachar** [comment]
FWIW, when a cluster is created the following message is already printed:

```
Suggestions:
 * list nodes: kubectl get nodes --show-labels
 * ssh to the master: ssh -i ~/.ssh/id_rsa admin@api.foo.bar.com
 * read about installing addons: https://github.com/kubernetes/kops/blob/master/docs/addons.md
```

Note that `~/.ssh/id_rsa` is currently hardcoded into the message (https://github.com/kubernetes/kops/blob/c4b258351fb066cc91fa656aea503ec62c75461c/cmd/kops/update_cluster.go#L134). We should really print out the SSH key that is actually being used.

**Comment by chrislovecnm** [comment]
@yissachar we have a `kops validate cluster` as well :)  Also we have to think about the bastion as well.  We cannot always ssh into a master.  A nice blurb at the end I think would be really nice.  Let's keep it simple at first.  Print out the ssh key.  Then we can look at be fancier :)

**Comment by yissachar** [comment]
@chrislovecnm Looks like the simple fix of printing the SSH key was already [merged](https://github.com/kubernetes/kops/pull/1151). So this issue should probably be closed. I can open a new one for the improvements to the suggestions printed at the end of a cluster start.

**Comment by chrislovecnm** [comment]
👍  thanks @yissachar!
