### ISSUE TITLE
Fully support AWS Load Balancer Controller addon

### ISSUE THREAD

**Issue by peter-svensson** [kubernetes/kops#11446]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```shell
Version 1.20.0
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.20.6

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Create a new kops cluster with the AWS Load Balance Controller enabled.

**5. What happened after the commands executed?**

Failure to use certificates in ALB

**6. What did you expect to happen?**

All features on the AWS ALB supported

When enabling the [AWS Load Balancer Controller](https://kops.sigs.k8s.io/addons/#aws-load-balancer-controller) today there are some limitations due to lack of permissions. The IAM role (for kops 1.20) does not have enough permissions on the AWS account to support all the [features](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/) (annotations).
When enabling the add-on with:
```yaml 
spec:
  awsLoadBalancerController:
    enabled: true
```

The "default" IAM policy [document](https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.1.2/docs/install/iam_policy.json) mentioned in the deployment [guide](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/#setup-iam-role-for-service-accounts) for the ALB contains a lot of permissions that are needed to support for example [TLS](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/#ssl) termination in the ALB.

If I for example enable HTTP->HTTPS redirect with:

```yaml
alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
```

in my ingress I will get errors:

```json
{"level":"error","ts":1620292987.8541718,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"default-ingress","namespace":"","error":"ingress: default/buildtools-examples: AccessDeniedException: User: arn:aws:sts::292662267961:assumed-role/masters.stc-test2.k8s.local/i-06abbb3bfb1fc5667 is not authorized to perform: acm:ListCertificates\n\tstatus code: 400, request id: 720a5427-bbe0-4203-b500-7ed1dca9106f"}
```

Had some discussions in the kops-dev slack channel regarding a different missing policy https://github.com/kubernetes/kops/pull/11393 with @olemarkus so decided to create an issue for this. 

When testing I found that I (at least) need the following permissions to use TLS and to modify rules:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "acm:DescribeCertificate",
                "elasticloadbalancing:ModifyRule",
                "elasticloadbalancing:DeleteRule"
            ],
            "Resource": [
                "arn:aws:elasticloadbalancing:*:<account>:listener-rule/app/*/*/*/*",
                "arn:aws:elasticloadbalancing:*:<account>:listener-rule/net/*/*/*/*",
                "arn:aws:acm:*:<account>:certificate/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "acm:ListCertificates",
            "Resource": "*"
        }
    ]
}
```

But a better way would probably be to look at the policy document linked above.

**Comment by olemarkus** [comment]
/remove-lifecycle stale

Sorry this issue slipped passed me. 
The trick is how to ensure that not any loadbalancer can use any cert. This can probably be solved by adding a tag to certs that LBC can use.

Will this work for you?

**Comment by peter-svensson** [comment]
> /remove-lifecycle stale
> 
> Sorry this issue slipped passed me.
> The trick is how to ensure that not any loadbalancer can use any cert. This can probably be solved by adding a tag to certs that LBC can use.
> 
> Will this work for you?

Worth a try at least 😊
