### ISSUE TITLE
Feature: support for kubectl drain pod selector in rolling update

### ISSUE THREAD

**Issue by jdomag** [kubernetes/kops#11478]
Would be great to have a --pod-selector flag in kops rolling update - it means that during the drain process only selected pods are evicted from the node (already supported by kubectl drain command).

Use case:
We use a lot of jobs in the cluster and doing an upgrade is a manual process at the moment - we can't use kops rolling update because jobs don't have PDB defined and are evicted during rolling update process - scheduling a job on another node means that the job needs to start doing its work from the beginning. So best approach in this case is to drain a node using --pod-selector that allows us to evict everything, but not jobs. We leave a cordoned node with a job/jobs in old cluster version and once the jobs are completed and node is empty it will be terminated by the cluster autoscaler automatically

**Comment by olemarkus** [comment]
I am not sure this will do what you think it will.

If you set a pod selector on `kubectl drain`, those will be evicted. All well and good. But then kOps will terminate the instance and your Jobs are killed anywhere. Maybe even less graceful than if it was drained.

If you are using CAS, your best bet is to do something like `kops rolling-update --instance-group-roles=master`, then cordon/taint all nodes. CAS will start spinning up new nodes for new jobs. These new nodes will be up to date. Eventually it would be safe to roll the remaining nodes (or CAS will terminate them).

**Comment by johngmyers** [comment]
I would say you should put a PDB on your jobs.

**Comment by jdomag** [comment]
> I would say you should put a PDB on your jobs.

That's kind of difficult. Jobs are not a good candidate for packing it into the helm chart, we run them as fire and forget - apply k8s manifest and waits until the job is done - then it's automatically removed by k8s once TTL expires. If we added PDB to it I can image that PDB would be hanging there forever. 

@olemarkus 
Fair point, I forgot that rolling-update terminate instance at the end. What I need is a feature that will run cordon/drain on each node with pod selector and leave a node termination to CAS - but that may be too complex to implement.

**Comment by olemarkus** [comment]
Do you actually need kOps to do anything to implement this? It seems like `kubectl drain` has everything you need

**Comment by jdomag** [comment]
Well I like the kops logic and how it handel rolling upgrade e.g. I use surge (https://kops.sigs.k8s.io/operations/rolling-update/#maxsurge)  that speed up whole process very well

**Comment by olemarkus** [comment]
What you need isn't really a rolling-update. You could maybe call the AWS API directly to scale up the amount of nodes in the cluster rather than draining and then have CAS scale up.

**Comment by johngmyers** [comment]
@jdomag you could have a single, permanent PDB with a `minAvailable` of, say, `2147483647` and a `selector` that matches the Pods from all those Jobs you submit.

Or perhaps you could set `spec.rollingUpdate.dranAndTerminate` to `false`.

**Comment by jdomag** [comment]
@johngmyers 
We can't have minAvaliable as each job is unique. I can set common label for all the jobs and attach PDB, but it means that if I have 10 jobs and minAvaliable=1 then 9 jobs will be terminated. I would have to update PDB each time I schedule a job and increase / decrease minAvaliable. 

But thanks for  `spec.rollingUpdate.dranAndTerminate` I was not aware of this. I can then use `maxSurge` and ` spec.rollingUpdate.dranAndTerminate=false` and run  in the loop 'kubectl drain --pod-selector=job=true`, which simplify whole process! I'm performing an update next month, so I will provide a feedback in case of any issues.

**Comment by johngmyers** [comment]
@jdomag my suggestion was to set `minAvailable` to `2147483647`, not `1`. That way, none of your unique jobs would be evicted.

**Comment by jdomag** [comment]
oh ok - that make sense :) I will try that out, thanks!
