### ISSUE TITLE
e2e-kops-gce-stable is consistently failing

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kops#11471]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/e2e-kops-gce-stable

This was noticed in the sig-auth meeting because of the noise it's causing in gubernator. It looks like kops isn't passing a few conformance tests.

**Comment by olemarkus** [comment]
There has been work lately on cutting down on these errors. Looks like it is only one remaining: https://testgrid.k8s.io/kops-gce#kops-gce-latest

/cc @rifelpet

**Comment by rifelpet** [comment]
Thanks for the report. We've finished up some kubetest2 migrations on our GCE jobs and the job is now consistently passing.

/close
