### ISSUE TITLE
support for new r4 class instances

### ISSUE THREAD

**Issue by oO-Zam** [kubernetes/kops#1149]
Can the api-2.json file be updated to support the new instance classes? I was trying to spin up some of the new r4.large ( better performance, less $$ than the equivalent r3 ) and getting failures.

**Comment by elliot** [comment]
This is in master as of #1029 .

**Comment by chrislovecnm** [comment]
We good? Can we close?

**Comment by chrislovecnm** [comment]
Closing this ;)
