### ISSUE TITLE
Discover which version of `kops` manages a given cluster

### ISSUE THREAD

**Issue by object88** [kubernetes/kops#11505]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I have a collection of clusters which were created by `kops` at different times, and they get upgraded to different versions of Kubernetes at different times.  At any given time, they may be a minor version apart (i.e., we've moved _some_, but not _all_, from `1.x` to `1.[x+1]`, or maybe even two.

Given this, I want to be able to automate something like SSH public key replacement, which involves a `kops update`.  If I use a mismatched version of `kops`, my automation will change more than just the public key.

I would like to see either:
1) documentation that says "you can access _some kubernetes resource_ to programmatically determine the version of `kops` running".
2) a `kops` subcommand that works across a wide matrix of versions to report the version of kops just invoked, and the version of kops that was used on the target cluster, akin to `kubectl version`.

Regarding the first method, I know that I can invoke:
```
$ kubectl --namespace kube-system get daemonset kops-controller --output json | jq -r '.metadata.labels.version'
1.17.2
``` 
... but I don't know if this accidentally happens to work right now, or if it's a supported label that I can count on.

Thanks for any feedback or direction!

**Comment by johngmyers** [comment]
There's a file `kops-version.txt` in the state store. That got added in 1.19.

We do build and release kops-controller in the same process as kops and thus give it the same version number.

I wouldn't say either of these are part of the defined API.

**Comment by object88** [comment]
That's helpful, thanks.  We _just_ got to `1.18` for most deployments, so in lieu of something more official, I will check for the `kops-version.txt` file first, and then fall back.
