### ISSUE TITLE
Unable to connect 

### ISSUE THREAD

**Issue by xpepermint** [kubernetes/kops#11503]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.20.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**

AWS 

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```sh
kops create cluster \
    --master-count 1 \
    --master-size=t2.micro \
    --node-count 2 \
    --node-size=t2.micro \
    --zones eu-central-1a \
    --master-zones eu-central-1a \
    --networking calico \
    ${NAME}
```

**5. What happened after the commands executed?**

The cluster is successfully created but I'm unable to connect to it using `kubectl`.

**6. What did you expect to happen?**

I used the command above to create clusters before and I was able to connect to the cluster. After upgrading kops to `1.20.1` using `--networking calico` flag(s) makes my cluster inaccessible.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

/

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

/

**9. Anything else do we need to know?**

/

**Comment by johngmyers** [comment]
"unable to connect" and "inaccessible" are vague descriptions of what happened. A better bug report would describe precisely the output you got.

I suspect you didn't read [the release note on changes to kubernetes config export](https://kops.sigs.k8s.io/releases/1.19-notes/#changes-to-kubernetes-config-export).

**Comment by xpepermint** [comment]
Yeah, sorry. I think it's required to have 3 nodes and I had 2.
