### ISSUE TITLE
Unable to provide evictionHard to kubelet using kops 1.20

### ISSUE THREAD

**Issue by xoxbet** [kubernetes/kops#11515]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** 
1.20.0 (upgraded from 1.19 series)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.20.6

**3. What cloud provider are you using?**
aws

Cluster spec related with kubelet:
```
<..>
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    evictionHard: memory.available<900Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
<..>
```

I've bumped into a a problem that kubelet deprecated `--eviction-hard ` flag. Pods are no longer evicted when nodes are short on resources. I'm seeing the following in the node logs:

```
May 18, 2021 @ 10:39:38.000	E0518 07:39:38.420545 4230 eviction_manager.go:260] eviction manager: failed to get summary stats: failed to get node info: node "ip-10-0-151-85.eu-west-1.compute.internal" not found
May 18, 2021 @ 10:39:37.000	Flag --eviction-hard has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 18, 2021 @ 10:39:37.000	I0518 07:39:37.525370 4230 flags.go:59] FLAG: --eviction-hard="imagefs.available<10%,imagefs.inodesFree<5%,memory.available<900Mi,nodefs.available<10%,nodefs.inodesFree<5%"
May 18, 2021 @ 10:39:37.000	I0518 07:39:37.525394 4230 flags.go:59] FLAG: --eviction-max-pod-grace-period="0"
May 18, 2021 @ 10:39:37.000	I0518 07:39:37.525403 4230 flags.go:59] FLAG: --eviction-minimum-reclaim=""
May 18, 2021 @ 10:39:37.000	I0518 07:39:37.525411 4230 flags.go:59] FLAG: --eviction-pressure-transition-period="5m0s"
May 18, 2021 @ 10:39:37.000	I0518 07:39:37.525416 4230 flags.go:59] FLAG: --eviction-soft=""
May 18, 2021 @ 10:39:37.000	I0518 07:39:37.525421 4230 flags.go:59] FLAG: --eviction-soft-grace-period=""
May 18, 2021 @ 10:39:37.000	I0518 07:39:37.525431 4230 flags.go:59] FLAG: --experimental-allocatable-ignore-eviction="false"
```

I believe this [5070](https://github.com/kubernetes/kops/issues/5070) is related but corresponding [MR](https://github.com/kubernetes/kops/pull/9749) was closed. 

I didn't manage to find any kops docs on the new approach. I would be really thankful if anyone could tell what is the proper way to set `evictionHard` using kops 1.20?

**Comment by olemarkus** [comment]
Never mind those deprecation warnings. While k8s claim they are deprecated, the replacement are in perpetual beta. Which is why kOps still use the flags. Have not used the evictionHard feature, but I would assume if it is configured correctly, it should work.
