### ISSUE TITLE
Etcd certificate renewing progress is not working properly  

### ISSUE THREAD

**Issue by WoodProgrammer** [kubernetes/kops#11527]
Hi there is only one instance is returning certificate-expiration error , I've tried this solution at this link 
https://github.com/kubernetes/kops/issues/8959#issuecomment-618629976 

into only one master-node with the name MASTER-A (cluster has 3 master-node) so etcd was not coming back up and  `tls certificate error still returning referring to "serverName: other-master-address" `

```
etcdmain: rejected connection from "MASTER-B-ADDRESS:64762" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid
etcdmain: rejected connection from "MASTER-C-ADDRESS:64762" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid
```
Do you have any idea about that ? 

Thanks

**Comment by hakman** [comment]
There is an advisory about this, please follow the recommendations:
https://kops.sigs.k8s.io/advisories/etcd-manager-certificate-expiration/

**Comment by WoodProgrammer** [comment]
Hi it's done we have tried it in all instances.
Thank you @hakman

**Comment by a1198457636** [comment]
> 您好，我们已经在所有情况下都尝试过了。 谢谢@hakman



> Hi it's done we have tried it in all instances. Thank you @hakman

Excuse me, so solved?

**Comment by olemarkus** [comment]
Yes. As long as you keep upgrading kops.
