### ISSUE TITLE
kubectl logs doesn't work with k8s 1.5.1

### ISSUE THREAD

**Issue by stonith** [kubernetes/kops#1153]
Created 1.5.1 k8s cluster via: `kops create cluster --cloud=aws --master-zones=us-east-2a,us-east-2b,us-east-2c --zones=us-east-2a,us-east-2b,us-east-2c --master-size=t2.large --ssh-public-key=~/.ssh/id_rsa --kubernetes-version=1.5.1  mgmt-k8s.example.com`

kubectl logs:
```
kubectl logs -n kube-system kube-dns-v20-3531996453-klc63
Error from server (BadRequest): the server rejected our request for an unknown reason (get pods kube-dns-v20-3531996453-klc63)
```

@chrislovecnm

**Comment by chrislovecnm** [comment]
Wondering if the pods did not start cause of headroom. Will test in the am. Much thanks

**Comment by stonith** [comment]
Looks like it started working for me now which is strange. For multi-container pods, specifying the container is required. I think in 1.4.x it `kubectl logs` would respond with the containers and ask you to specify.

**Comment by jeffknupp** [comment]
IIRC, for multi-container pods specifying the container is not _required_, it just defaults to the first container in the pod.

**Comment by stonith** [comment]
@jeffknupp you're right. I also tracked this down to the version of `kubectl client`. If I switch back to version 1.4.6 client `kubectl logs` works as expected.

**Comment by justinsb** [comment]
Moving to https://github.com/kubernetes/kubernetes/issues/38774, closing here

**Comment by justinsb** [comment]
PS nice find @stonith !
