### ISSUE TITLE
Remove `--cloud-provider` flag

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#11546]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Kubelet `--cloud-provider` and `--cloud-config` flags are being deprecated and will be removed in Kubernetes 1.23.
https://github.com/kubernetes/kubernetes/pull/90408

**2. Feel free to provide a design supporting your feature request.**

Probably we need to discuss and plan how to handle this in 1.22 and 1.23

/cc @justinsb @nckturner @olemarkus @rifelpet

**Comment by olemarkus** [comment]
Is external the default value? Or should this issue be more "force the value to external"?

**Comment by hakman** [comment]
Not quite sure exactly. There should be at least another value like "none", but not exactly sure how k8s deals with that.

**Comment by olemarkus** [comment]
I think the `external` value is needed for kubelet to taint nodes with `uninitialized`

**Comment by hakman** [comment]
Yes, I think we went to defaulting with external cloud provider in 1.23, probably this should be considered fixed when the in-tree is removed.

**Comment by olemarkus** [comment]
In 1.24 I hope... The migration path requires some steps that @johngmyers already has taken care of

**Comment by hakman** [comment]
Yes, 1.24 will be a pretty nice cleanup release. Looking forward to it.
