### ISSUE TITLE
Support structured logging ('--logging-format=json')

### ISSUE THREAD

**Issue by ari-becker** [kubernetes/kops#11576]
As part of [KEP 1602 - Structured Logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging) the `--logging-format=json` flag was added to Kubernetes 1.19 in the following PRs:

* [kubelet](https://github.com/kubernetes/kubernetes/pull/91532)
* [kube-controller-manager](https://github.com/kubernetes/kubernetes/pull/91521)
* [kube-scheduler](https://github.com/kubernetes/kubernetes/pull/91522)

We would like the ability (disabled by default) to specify this flag so that we can test it on our clusters.

**Comment by hakman** [comment]
Thanks for the suggestion @ari-becker. Seems like an easy change, so anyone that wants to add thin new flag is welcome to do it.
