### ISSUE TITLE
kops update cluster mycluster --yes hangs if issued 2nd time

### ISSUE THREAD

**Issue by vinayagg** [kubernetes/kops#1160]
easy to reproduce using following sets of commands

1. create a cluster
kops create cluster --cloud=aws --dns-zone=k8s.mycluster.com --master-size=t2.nano --node-size=t2.nano --zones=us-east-1a,us-east-1c,us-east-1e --master-zones=us-east-1a --node-count=1 --kubernetes-version=v1.4.6 k8s.mycluster.com

2. launch cluster 
kops update cluster k8s.mycluster.com --yes

3. find and update master node (I am not sure if this step is relevant)
kops get instancegroups
kops edit <master> - now edit instance type

4. update cluster again, I know I should do rolling update but I mistakenly issued this command and it was hanging for ever.
kops update cluster k8s.mycluster.com --yes

**Comment by chrislovecnm** [comment]
Kops version?

**Comment by vinayagg** [comment]
$ kops version
Version 1.4.1

**Comment by kris-nova** [comment]
@vinayagg -

Assuming this is happening on step 4 right?

Also do you mind adding `-v 10` to the end of the command that is hanging and dumping the entire output here please?

**Comment by vinayagg** [comment]
unfortunately I lost access to that environment, so I wont be able to reproduce it now.
If you cannot reproduce it, you may close it for now. If I get access to env again, I will try to get more details. thanks

**Comment by chrislovecnm** [comment]
Let's close for now
