### ISSUE TITLE
We should have a doc for HA

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1163]
We make it so easy that we forgot to describe how to use it :-)

**Comment by chrislovecnm** [comment]
K8s should have it ... Oh wait https://github.com/kubernetes/kubernetes.github.io/issues/1733

**Comment by jszczepkowski** [comment]
CC @jszczepkowski

**Comment by vendrov** [comment]
I've just created one:
#1239

**Comment by kris-nova** [comment]
@evildandelions this is a good one

We have a concept of running Kubernetes in "HA" or "Highly Available" in kops.. and the documentation is scattered throughout the `/docs` directory.. we need to amalgamate the HA documentation into a new file in `/docs` and remove/add links where necessary in the other documentation pieces.

A good example is the bastion documentation https://github.com/kubernetes/kops/blob/master/docs/bastion.md

**Comment by chrislovecnm** [comment]
Closing
