### ISSUE TITLE
Implement WarmPool on Terraform

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#11633]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Implement `WarmPool.RenderTerraform()`

**2. Feel free to provide a design supporting your feature request.**

/kind feature
/area terraform
/lifecycle frozen

**Comment by Patil2099** [comment]
I am new to this project and would love to help in implementing this feature. Can you guide me a little? @johngmyers

**Comment by johngmyers** [comment]
The task is to implement `WarmPool.RenderTerraform`.

I would suggest looking at other `RenderTerraform` receivers to see how they work. You'll need to create an annotated struct corresponding to the Terraform configuration syntax.

Adding an integration test for warmpool would also be good. The integration tests are in kops/cmd/kops/integration_test.go.

**Comment by johngmyers** [comment]
It looks like Terraform puts this inside the ASG definition, so you'll probably have to put this in `AutoscalingGroup.RenderTerraform` instead.

**Comment by JacekDuszenko** [comment]
If others are not working on the task I'd like to look into it now, so am assigning myself.

**Comment by rifelpet** [comment]
The WarmPool task has an AutoScalingGroup reference field yet doesn't use it in any of its methods, I'm assuming this is for dependency purposes @olemarkus ? We likely can't add a WarmPool task reference in the ASG task because of the dependency loop, so we may need to wait for https://github.com/hashicorp/terraform-provider-aws/issues/19229 unless anyone has other ideas on how this could be implemented.

**Comment by johngmyers** [comment]
I believe for the Terraform target, the `WarmPool` task would do nothing. `AutoscalingGroupModelBuilder` would put the warmpool config into both the `WarmPool` and `AutoscalingGroup` tasks.

The trick would then be to keep the warmpool config in the `AutoscalingGroup` task from showing up in dryrun output.

**Comment by SD-13** [comment]
Seems like [this PR](https://github.com/kubernetes/kops/pull/15153) addressed this issue.
/close
