### ISSUE TITLE
Upgrade usage of deprecated APIs removed in k8s 1.22

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#11689]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

In order to support k8s 1.22, kops will need to update its usage of deprecated APIs that have been removed in k8s 1.22.

[We first discovered this in testing the aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2050).

Most of the changes would be in addon manifests, but dns-controller (Ingress v1beta1) and protokube (RBAC v1beta1) will need updates as well. There may be other areas of the code base that I missed in my quick scan.

A few challenges we'll run into:
*  Many of the replacement APIs were introduced in k8s versions newer than what is planned to be supported by kops 1.22. We'll have to decide whether to handle both API versions or narrow the support window for kops 1.22. 
* Many of the addon manifests come from upstream, so we should work with them to get their manifests updated, but we'll also need to decide what to do if their manifests and/or client code arent updated by the time we intend to release kops 1.22.

**Comment by rifelpet** [comment]
Occurrences of API versions removed in 1.22:

#### `apiextensions.k8s.io/v1beta1`
* [AWS VPC CNI](https://github.com/kubernetes/kops/blob/ce821a614fb36eaa28de297ba5c593eff80d1798/upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template#L57)
* [AWS IAM Authenticator](https://github.com/kubernetes/kops/blob/ce821a614fb36eaa28de297ba5c593eff80d1798/upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template#L2)
* [Canal](https://github.com/kubernetes/kops/blob/ce821a614fb36eaa28de297ba5c593eff80d1798/upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template#L78)
* [CoreDNS](https://github.com/kubernetes/kops/blob/ce821a614fb36eaa28de297ba5c593eff80d1798/channels/operators/coredns.addons.x-k8s.io/0.1.0-kops.1/manifest.yaml#L1)

#### `extensions/v1beta1`
* [dns-controller](https://github.com/kubernetes/kops/blob/ce821a614fb36eaa28de297ba5c593eff80d1798/dns-controller/pkg/watchers/ingress.go#L76)

#### `rbac.authorization.k8s.io/v1beta1`
* [kopeio](https://github.com/kubernetes/kops/blob/ce821a614fb36eaa28de297ba5c593eff80d1798/upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.12.yaml#L67)
* [AWS IAM Authenticator](https://github.com/kubernetes/kops/blob/ce821a614fb36eaa28de297ba5c593eff80d1798/upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template#L37)

**Comment by johngmyers** [comment]
We've added validation for those components which use APIs removed in k8s 1.22. When any of those update, we can remove the corresponding validation and cherry-pick to release-1.22.

Nothing else to track here.
/close

**Comment by gtorre** [comment]
@johngmyers @rifelpet I believe aws load balancer controller has been updated, see https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2433 

Are there plans to remove the validation? Is there a way to get around this if I'm currently using aws load balancer controller but want to upgrade to v1.22?

**Comment by olemarkus** [comment]
We're still waiting for a release with that fix. should arrive in the near future. We'll remove the validation then.

**Comment by gtorre** [comment]
Thank you @olemarkus !
