### ISSUE TITLE
Using --networking=cni does not work with k8s v1.5.1

### ISSUE THREAD

**Issue by sekka1** [kubernetes/kops#1169]
Built kops from master trying to run with the `--networking=cni` option.  Looks like kublet fails to start because of an unrecognized flag.

```
$ kops version
Version git-fbe62f0
```

```
Dec 15 04:50:46 ip-172-30-75-186 kubelet[1467]: unknown flag: --configure-cbr0
```

**Comment by sekka1** [comment]
@chrislovecnm tagged

**Comment by chrislovecnm** [comment]
Did this work on master?

**Comment by snarlysodboxer** [comment]
Same as [856](https://github.com/kubernetes/kops/issues/856)

**Comment by justinsb** [comment]
Closing as a dup of #1208 (even though this was opened first!)
