### ISSUE TITLE
aws launch configurations are not deleted

### ISSUE THREAD

**Issue by oO-Zam** [kubernetes/kops#1174]
When I modify an ig in kops, a new launch configuration is created in AWS, but the old one is not deleted. Overtime, old launch configurations accumulate and create confusion.

**Comment by chrislovecnm** [comment]
Yep ... known bug.  We are refactoring the bastion to be an instance group ... and this will be fixed.

**Comment by kris-nova** [comment]
I think this is different than https://github.com/kubernetes/kops/issues/1051

@oO-Zam says it's happening when he modifies an `ig` in kops 

Either way - working on a fix for this now - assuming it's the same issue, but wanted to call out that this issue has nothing to do with bastions :)
