### ISSUE TITLE
Supporting component configuration

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kops#11765]
/kind feature

More and more features are only available in component configs, for example https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/ and #10977

I think both @justinsb and I are of the opinion that we should not extend our Cluster resources with all these options, but rather support these resources directly.

My suggestion is that we provide the mechanisms to write this to the confgStore VFS path.
Before storage, we should implement validation that prevents users from setting things that kOps "owns" such as the path to the kubeconfig for the component. Those configs will be exposed to users when they edit existing resources, so kOps then just has to validate it is set to the one valid configuration.

I.e the user provides a partial component config file, and kOps fills in the missing details.
I think a consequence of this is that a lot more will happen on the cloudup side, but that is probably a good thing.

A problem with componentconfig right now is that ObjectMeta is not supported, so `kops replace/create` will have some issues with figuring out what cluster the resource belongs to. There is a KEP that aims to resolve this https://github.com/kubernetes/enhancements/issues/1815. For the first iteration of this feature, we may work around this by maybe only allowing modification through `kops edit`, which assumes a specific context.

The above definitely needs to be gated by a feature flag.

**Comment by johngmyers** [comment]
Step one is to change our nodeup code from using `flagbuilder.BuildFlagsList()` to instead converting from our componentconfig to k/k's componentconfig and passing it using a `--config` flag.

A later kops API version (which would be 1.23 at the earliest) could then change from our componentconfig to k/k's componentconfig. We could then separate them from `Cluster` and `InstanceGroup` at that point if necessary.

**Comment by johngmyers** [comment]
I think we're going to find some impedance mismatches with the k/k componentconfigurations. For example, we have three levels of `KubeletConfigSpec`, one at the instancegroup level, one for control plane nodes, and a default. We merge these, allowing overrides at each level. In the k/k `KubeletConfiguration`, the `ReadOnlyPort` field is an `int32`, not a `*int32`. The value `0` means to disable the read-only port. So there is no way to express the difference between "I want to disable the read-only port" and "I don't want to override the setting for the read-only port".

**Comment by olemarkus** [comment]
A goal should be to have componentconfig API and kops API live independently with independent lifecycles. We should not be populating one with the value of the other. We can, however, validate across both where there may be incompatibilities. And cloudup can fill in missing pieces where needed.

When `--config` is set, the components will ignore/resolve conflicts between flags and configuration, so there is no particular need to do much about current logic. Where there may be problems, we should rather filter what we pass to `BuildFlagsList`.

When `ObjectMeta` is available for componentconfig, we can use name and/or labels to allow users to use a specific componentconfig resource for a given IG. But cloudup/users will have to provide full configuration for each.

If we were to put k/k componentconfig into our APIs we'd be locking ourselves to a specific version of each componentconfig resource. There is no unversioned componentconfig that can be used.

**Comment by johngmyers** [comment]
So how would you propose we handle an independent `KubeletConfigSpec` with our three-level-merging semantics?

**Comment by olemarkus** [comment]
The three-level merging is an aspect of the `kops.k8s.io` API. If users provide `KubeletConfiguration` from `kubelet.config.k8s.io/v1beta1` then that merging functionality is "lost". Since these resources do not use pointers, it is not feasible to implement merging either. These resources also use a fair degree of nesting, which makes merging a bit tricky (override vs append).

The alternative, which probably works just as well for most users given that they don't actually need IG-specific configurations, is to provide a full configuration per IG rather than trying to merge.

**Comment by johngmyers** [comment]
Office hours decisions:
* Start with replacing flagbuilder.BuildFlagsList() code with conversion to k/k configuration objects. 
* The first subsystem to do is kube-scheduler.

**Comment by olemarkus** [comment]
Fair enough. How do we want to approach this?

* we already build a config for kube-scheduler, but we have our own structs for this. Do we want to keep using that approach (and thus be backwards compatible with 1.18)?
* I assume we won't support profiles and plugin configs or any other new features (e.g #10977) anytime soon.
* I am quite interested in https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/, but I assume this will also not be possible anytime soon.
* `BuildFlagsList` happens in nodeup. I assume we keep this logic on the nodeup side then.

Anyone planning to work on this? I would be happy to once I am done with the IRSA stuff, but I would need to understand more of the reasoning behind the above.

**Comment by johngmyers** [comment]
@olemarkus we'll have to get you the recording of today's Office Hours soon. It will give context.

We need the mechanism to do the copying. It would most probably be reflection-based, like flagbuilder.BuildFlagsList(). I was wondering what we could take from apimachinery's code for copying from versioned APIs to unversioned APIs.

The main decision is that we're going to focus first on using the k/k structs for passing config to the components and deal with exposing them as APIs later. There's a loose action item on me to take my inheritance concerns to k/k.

Not mentioned in the call, but we can keep extending our componentconfig.

**Comment by uthark** [comment]
I know that kops is opinionated about how things are configured, but I'm also wondering why you don't provide escape hatch to allow specify any custom flags that underlying components support? For example, kubelet flag `--pod-max-pids` is not supported by kops and it seems there is no official way of configuring it nicely. I guess it is possible to add a hook that would override kubelet.service in systemd but this idea scares me from a maintenance perspective.

**Comment by olemarkus** [comment]
This comes from how kops currently configures kubelet. Kops need to know about it in order to pass it along. component configs will change that. Kops may still be opinionated, but we could let people set a "unsafe.kops.k8s.io/disable-validation" annotation to component config that would make kops just skip the validation step. Given that https://github.com/kubernetes/enhancements/issues/1815 has been implemented, that is.

**Comment by danquack** [comment]
similar issue: https://github.com/kubernetes/kops/issues/11292
