### ISSUE TITLE
Enable Cluster Switching - Map kops clusters to aws buckets and profiles

### ISSUE THREAD

**Issue by efranford** [kubernetes/kops#1177]
Managing multiple clusters from the command line currently involves a few things.

1. `kops` uses `kubectl` to pull context when it performs an edit
2. `kops` uses the variable `AWS_PROFILE` variable when it performs operations
3. `kops` uses the `S3_STATE_STORE` variable when it performs operations
4. `kubectl` uses the `current-context` attribute to know where it is pointing

It would be useful to find a way to combine the above things into s command that enables `kops` users to "switch clusters".  This would make it easier to manage multiple clusters in the wild.

The below script illustrates the desired outcome of a "switch" operation.  If `kops` could store information about the Bucket and Profile that were used to create it that would make life more awesome!  

***Note***: The below script updates `kubectl`'s `current-context` to make working with it easier, but that is not part of the request for this issue.  Managing this separately would be fine if `kops` were to no longer rely on `kubectl`'s `current-context` 

```sh
#!/usr/bin/env bash -l
contexts=("development" "production")
export development_context="dev.redacted.com"
export development_store="s3://devbucket/"
export production_context="prod.redacted.com"
export production_store="s3://prodbucket/"
environment=$1
if [[ ! " ${contexts[@]} " =~ " ${environment} " ]]; then
   echo "Unknown context ${environment}. We only know about: ${contexts[@]}"
   exit 1
fi
echo "Switching context to ${environment}"
case ${environment} in
"development")
  export AWS_DEFAULT_PROFILE=default
  export AWS_PROFILE=default
  export KOPS_STATE_STORE=${development_store}
  sed -i '' "s|\(current-context: *\)[^ ]*|\1${development_context}|" ~/.kube/config
  alias kops="AWS_PROFILE=default kops"
  ;;
"production")
  export AWS_DEFAULT_PROFILE=production
  export AWS_PROFILE=production
  export KOPS_STATE_STORE=${production_store}
  sed -i '' "s|\(current-context: *\)[^ ]*|\1${production_context}|" ~/.kube/config
  alias kops="AWS_PROFILE=production kops"
  ;;
esac
```

Perhaps `kops` could adapt a similar kind of configuration style to what `kubectl config` does off the `~/.kube/config` file.

- [kubectl config set-cluster](http://kubernetes.io/docs/user-guide/kubectl/kubectl_config_set-cluster/)
- [kubectl config set-context](http://kubernetes.io/docs/user-guide/kubectl/kubectl_config_set-context/)
- [kubectl config set-credentials](http://kubernetes.io/docs/user-guide/kubectl/kubectl_config_set-credentials/)
- [kubectl config view](http://kubernetes.io/docs/user-guide/kubectl/kubectl_config_view/)

Thanks!

**Comment by chrislovecnm** [comment]
I like this idea, we always welcome contributions! We have a config file that we use already, and this could be utilized.

**Comment by juliaaano** [comment]
This is a nice idea and it reminds me of how docker-machine handles well multiple machines:

``
eval "$(docker-machine env default)"
``
