### ISSUE TITLE
Lack of ICMP causes cilium to think the cluster isn't doing well, prevents cilium start up with --enable-host-reachable-services=true

### ISSUE THREAD

**Issue by jmcdonagh** [kubernetes/kops#11787]
/kind bug

I've brought this issue up before. Since ICMP is not allowed in the SGs, cilium status reports 0/0 hosts reachable. I was told this is cosmetic, which made me nauseous kind of, but I just went with it. Now we are trying to run cilium with --enable-host-reachable-services=true, we rolled the DS and the logs indicate that the inability to ping other nodes is preventing cilium from starting. As soon as we enabled ICMP on the master and node SGs from master and node SGs, cilium came right up.

I honestly don't understand why ICMP is not enabled by default anyways. It's a powerful diagnostic tool. I highly doubt there's a legitimate security reason here to disable it by default.

**Comment by jmcdonagh** [comment]
Log output from when cilium refused to start:

level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="regenerating all endpoints" reason= subsys=endpoint-manager
level=error msg="arping failed" error=timeout interface=ens5 ipAddr=172.20.38.109 subsys=node-neigh
level=error msg="arping failed" error=timeout interface=ens5 ipAddr=172.20.51.147 subsys=node-neigh
level=error msg="arping failed" error=timeout interface=ens5 ipAddr=172.20.53.20 subsys=node-neigh
level=error msg="arping failed" error=timeout interface=ens5 ipAddr=172.20.56.49 subsys=node-neigh
level=error msg="arping failed" error=timeout interface=ens5 ipAddr=172.20.50.156 subsys=node-neigh
level=error msg="arping failed" error=timeout interface=ens5 ipAddr=172.20.54.145 subsys=node-neigh
level=error msg="arping failed" error=timeout interface=ens5 ipAddr=172.20.49.102 subsys=node-neigh
level=error msg="arping failed" error=timeout interface=ens5 ipAddr=172.20.41.87 subsys=node-neigh

**Comment by jmcdonagh** [comment]
Closing this because it appears the first time cilium hung on boot was for something else, regardless of how awkward it is to not have ICMP it is not the bug I thought it was.

**Comment by olemarkus** [comment]
We use host-reachable-services without any such issue, so I don't think that is what is causing the problems.

That being said I don't mind allowing ICMP traffic. But others might.

**Comment by jmcdonagh** [comment]
> We use host-reachable-services without any such issue, so I don't think that is what is causing the problems.
> 
> That being said I don't mind allowing ICMP traffic. But others might.

Yes ended up being a red herring- btw THANK YOU for cluing us into this option for cilium in a slack msg when a colleague was troubleshooting recently. It has fixed a really annoying issue for us.
