### ISSUE TITLE
[Feature] Should we add node-problem-detector installation flag into kops

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kops#1179]
Should we add a flag to kops installation to automatically install the node-problem-detector? Is there a real reason why it shouldn't be installed by default?
It is already enabled by default as an addon in GCE

**Comment by chrislovecnm** [comment]
This goes to the question of where does the lifecycle of kops end?

If we decide to have a package management component, then we could define this in that type of strategy.

Do you feel that this is a required component like DNS? Or is this a component like autoscaling?

**Comment by chrislovecnm** [comment]
@kris-nova can we get this item scheduled to talk about next office hours? I think our next one is in the new year

**Comment by kris-nova** [comment]
@chrislovecnm - I think we decided to keep office hours open ended, if someone want's to bring it up they are welcome to join the call and mention it then

**Comment by vjm** [comment]
@kris-nova @chrislovecnm is this compatible with kops?

**Comment by julianvmodesto** [comment]
+1 here! It's automatically installed on GKE.

**Comment by julianvmodesto** [comment]
+1 to update this milestone
