### ISSUE TITLE
InstanceGroup "bastions" did not have enough nodes 0 vs 1 on kops 1.20.1

### ISSUE THREAD

**Issue by texpert** [kubernetes/kops#11807]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.20.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client: 1.21.1, Server: 1.13.12

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops validate cluster

**5. What happened after the commands executed?**

`InstanceGroup "bastions" did not have enough nodes 0 vs 1 `

**6. What did you expect to happen?**

`Your cluster is ready`

**9. Anything else do we need to know?**

Removed kops 1.20.1, installed 1.18.2 as on my colleague's machine - and everything's OK - `Your cluster is ready`

**Comment by johngmyers** [comment]
Unable to reproduce. Did you indeed have a bastion? Did you perhaps recently start a rolling update?

**Comment by texpert** [comment]
> Unable to reproduce. Did you indeed have a bastion? Did you perhaps recently start a rolling update?

Yes, I have a bastion. I've run `validate cluster` before starting the update - that's how I have discvovered this issue.

**Comment by alok87** [comment]
I am facing this issue in kops 1.18.x and 1.20.2 also.

Node is ready!
```
$ k get nodes -l kops.k8s.io/instancegroup=stagingx
NAME                                            STATUS   ROLES              AGE     VERSION
ip-172-31-102-199.ap-south-1.compute.internal   Ready    node,spot-worker   5d20h   v1.20.8
```

Kops says its not, but it is!

```
$ kops validate cluster
Using cluster from kubectl context: k8sx.example.com

Validating cluster k8sx.example.com

INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-ap-south-1a-1	Master	r5.large	1	1	k8s-ap-south-1a.example.com
nodes			Node	m5.xlarge	1	50	k8s-ap-south-1a.example.com
prometheus		Node	r5.xlarge	1	1	k8s-ap-south-1a.example.com

NODE STATUS
NAME						ROLE	READY
ip-172-31-102-154.ap-south-1.compute.internal	node	True
ip-172-31-102-199.ap-south-1.compute.internal	node	True
ip-172-31-102-29.ap-south-1.compute.internal	master	True

VALIDATION ERRORS
KIND		NAME	MESSAGE
InstanceGroup	nodes	InstanceGroup "nodes" did not have enough nodes 0 vs 4

Validation Failed

Validation failed: cluster not yet healthy
```

This is happening after the AMI was updated and rolling update was triggered using `kops rolling-update cluster --instance-group nodes  --yes --force --validation-timeout 120m`

**Comment by alok87** [comment]
I had the similar issue, then i saw in the Autoscaling group activity in AWS that my instance was not launching due to volume device mapping issue. But the case might be different for you and there could be a bug also.
