### ISSUE TITLE
[Discussion] Restore K8S cluster using kops

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kops#1180]
The motivation:
According to this [issue 24229](https://github.com/kubernetes/kubernetes/issues/24229) the best way to recover K8S from disaster recovery is by creating a new K8S cluster and apply yamls from VC.

Since currently kops is responsible to setup only the K8S basic infrastructure we need some kind of way to wrap kops or integrate in some integration with external installers such as Helm in order to complete the infrastructure implementation such as logging,monitoring etc.
I would like us to be able to create alternative cluster ready for deployment as easy as possible.

WDYT?

**Comment by chrislovecnm** [comment]
This is quite a big discussion that encompasses many different open issues.

Let me ask you first. What requirements do you have? 

Also, we have not come to an accord on what the boundaries of kops are. What I mean by that, is that knowing what your software does not do and where the boundaries of your software exists is just as important as what does your software do.

I kinda sway that we deploy a base cluster, then other deployment tools handle deploying components on top of the cluster. Base cluster is defined by my thoughts as DNS and networking is up.

Other folks have a different approach which is great!  They see that we need a cluster with components such as monitoring and centralized logging installed.

Again what are your requirements?
