### ISSUE TITLE
Stop users from using instances that are too small

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1185]
So we can get into weird edge cases if users attempt to use instance types that are just too small.

For instance https://github.com/kubernetes/kops/issues/1161

I would recommend determining the smallest ec2 instance type for master and node, and not allowing the user to use instance types that won't work.

**Comment by cyberious** [comment]
I think warning the user would be a better bet than to outright stop them from deploying.

**Comment by chrislovecnm** [comment]
Closing
