### ISSUE TITLE
error running task IAMRolePolicy/{nodes,masters}.xxxx path is not cluster readable when using local-file state

### ISSUE THREAD

**Issue by trajakovic** [kubernetes/kops#11850]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.20.2 (git-e6ca69f55e91f87080c897216115efb811673718)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`N/A`

**3. What cloud provider are you using?**

`AWS`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
export KOPS_STATE_STORE="file://kops-state"
export KOPS_CLUSTER_NAME="xxx.k8s.local"

kops create cluster \
  --cloud aws \
  --zones eu-central-1a,eu-central-1b,eu-central-1c \
  --topology private \
  --networking calico \
  --master-count 3 \
  --master-size t3a.small \
  --node-count 1 \
  --node-size t3a.micro \
  --encrypt-etcd-storage \
  --vpc vpc-xxx \
  --bastion=true \
  --output yaml
```

**5. What happened after the commands executed?**

```
W0622 09:42:14.541096   15605 executor.go:139] error running task "IAMRolePolicy/nodes.xxx.k8s.local" (9m59s remaining to succeed): error rendering PolicyDocument: error opening resource: error building IAM policy: failed to generate AWS IAM Policy: failed to generate AWS IAM S3 access statements: path is not cluster readable: kops-state/xxx.k8s.local/
W0622 09:42:14.541142   15605 executor.go:139] error running task "IAMRolePolicy/masters.xxxk8s.local" (9m59s remaining to succeed): error rendering PolicyDocument: error opening resource: error building IAM policy: failed to generate AWS IAM Policy: failed to generate AWS IAM S3 access statements: path is not cluster readable: kops-state/xxx.k8s.local/
```

**6. What did you expect to happen?**

Probably skipping this tasks when using local-state if possible. That way, we could use `kops create` to create all relevant resources from CI, then fetching `kind: Cluster` and patch it and create/apply full version to real target.

**Comment by elgamal2020** [comment]
Same error here 

error running tasks: deadline exceeded executing task IAMRolePolicy/masters.test.nn.k8s.local. Example error: error rendering PolicyDocument: error opening resource: error                    building IAM policy: failed to generate AWS IAM Policy: failed to generate AWS IAM S3 access statements: path is not cluster readable: test-nn-k8s-cluster-1/test.nn.k8s.local

**Comment by olemarkus** [comment]
There are a couple of more issues in this one. But I am chasing them down.

/assign
