### ISSUE TITLE
Containerd Metrics Configuration

### ISSUE THREAD

**Issue by rlandesman** [kubernetes/kops#11896]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Containerd surfaces metrics via an endpoint configured in the `config.toml` file. It would be great if kOps featured a way for end-users to enable and configure containerd metrics without overwriting the entire config file using the `containerRuntime.containerd.configOverride` field.

**2. Feel free to provide a design supporting your feature request.**
Not sure what an implementation would look like but am open to ideas!

**Comment by olemarkus** [comment]
Can you link to something that describes what functionality/containerd config you are looking to append to the kops managed containerd config?

**Comment by rlandesman** [comment]
I'm not too familiar with kOps architecture but what I'm hoping to get at here is the implementation of metrics (which are by default disabled) on the containerd daemon. To that extent a setting such as `spec.containerd.metrics` would be fantastic, to set the metrics field in the `config.toml` as such:

```yaml
[metrics]
        address = "127.0.0.1:1338"
```

The ultimate goal would be to surface metrics from containerd to be surfaced by Prometheus which can't be done at the moment unless using a full configOverride file (which is overkill for this use case imo).

Thanks for the help!

**Comment by olemarkus** [comment]
Getting that into the configuration is should be pretty easy. The config is generated in `upup/pkg/fi/cloudup/apply_cluster.go` in `buildContainerdConfig`.

It is a question how you will get the metrics from localhost to prometheus though. I would guess you actually need to listen on the instance internal IP.
