### ISSUE TITLE
Feature request: dump all objects to one yaml file

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1189]
Ideally separated by `---`

Would be handy both for diagnostics, and for integration testing.

**Comment by kris-nova** [comment]
Did we already talk about this https://github.com/kubernetes/kops/issues/1077

**Comment by justinsb** [comment]
Ah - this is all the "kops" objects.  So we would do `kops get --all -oyaml` (or something) and we would get a big file with all the kops objects.  We actually now have an example of what I mean in https://github.com/justinsb/kops/commit/9a3b96f853697c293a08f785ecb05d1d44e8aefd

#1077 is more AWS objects, IIUC.  Thought we might well put the kops objects in there as well, for completeness.

**Comment by chrislovecnm** [comment]
This is supported now ... closing

`kops get --name my.example.com -oyaml`
