### ISSUE TITLE
kOps clusters will not start with ci/latest version of Kubernetes

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#11911]
Me, @olemarkus and @rifelpet tried to find the root cause, but couldn't:
https://testgrid.k8s.io/kops-misc#kops-aws-misc-amd64-conformance

/kind bug

**Comment by justinsb** [comment]
One problem I think is that kube-controller-manager is crash looping because of removal of insecure health checking:
https://github.com/kubernetes/kubernetes/pull/96216/files

It looks like there's also a bug of some sort in the kubelet where it doesn't start the kube-scheduler; I haven't got to the bottom of that one yet.  It might be that a crash-looping pod triggers the bug (?)

**Comment by justinsb** [comment]
Actually, the 10257 problem has been fixed at HEAD (I was testing with kops 1.22.0), so that's not the root cause.

**Comment by justinsb** [comment]
Latest diagnostics: it looks like some sort of bug where kubelet tries to start the container, but containerd doesn't start it.

e.g. `curl https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-misc-amd64-conformance/1410922231181086720/artifacts/15.237.95.126/journal.log | grep ube-contr`

shows that kube-controller-manager is stuck in pending:

```
Jul 02 11:28:43.393899 ip-172-20-35-239 kubelet[4001]: I0702 11:28:43.393838    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:29:43.395056 ip-172-20-35-239 kubelet[4001]: I0702 11:29:43.394998    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:30:43.396150 ip-172-20-35-239 kubelet[4001]: I0702 11:30:43.396034    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:31:43.396766 ip-172-20-35-239 kubelet[4001]: I0702 11:31:43.396688    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:32:43.397316 ip-172-20-35-239 kubelet[4001]: I0702 11:32:43.397297    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:33:43.397975 ip-172-20-35-239 kubelet[4001]: I0702 11:33:43.397927    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:34:43.398938 ip-172-20-35-239 kubelet[4001]: I0702 11:34:43.398896    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:35:43.399935 ip-172-20-35-239 kubelet[4001]: I0702 11:35:43.399922    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:36:43.400603 ip-172-20-35-239 kubelet[4001]: I0702 11:36:43.400516    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:37:43.401084 ip-172-20-35-239 kubelet[4001]: I0702 11:37:43.401032    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:38:43.401461 ip-172-20-35-239 kubelet[4001]: I0702 11:38:43.401306    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:39:43.402155 ip-172-20-35-239 kubelet[4001]: I0702 11:39:43.402034    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:40:43.402679 ip-172-20-35-239 kubelet[4001]: I0702 11:40:43.402614    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
Jul 02 11:41:43.403098 ip-172-20-35-239 kubelet[4001]: I0702 11:41:43.403006    4001 kubelet_getters.go:176] "Pod status updated" pod="kube-system/kube-controller-manager-ip-172-20-35-239.eu-west-3.compute.internal" status=Pending
```

Because when I tried it I saw kube-scheduler stuck in the same loop (and kube-controller-manager happy), I'm _guessing_ it's a bug in either kubelet or our version of containerd.

**Comment by justinsb** [comment]
Speculative, but I'm wondering if we should update containerd version: https://github.com/kubernetes/kops/pull/11913

**Comment by hakman** [comment]
By using the famous **trial and error** technique, managed to track the commit that introduced this issue: https://github.com/kubernetes/kubernetes/commit/4748bb04b61f8717641913a0ff3a183ad28e64c9.

https://storage.googleapis.com/kubernetes-release-dev/ci/v1.22.0-beta.0.307+c206af0367f76f - works as before
https://storage.googleapis.com/kubernetes-release-dev/ci/v1.22.0-beta.0.310+4748bb04b61f87 - static pods fail to start

**Comment by hakman** [comment]
Together with @rifelpet did some more experiments and I think the root cause is an issue with the `systemd` cgoupd driver.
Once the cgroup driver changed to the `cgroupfs` default value, clusters start again.

**Comment by hakman** [comment]
Jobs are back to green after merging https://github.com/kubernetes/kubernetes/pull/103483.
