### ISSUE TITLE
Implement render managed files with CloudFormation

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#11928]
Implement the CloudFormation equivalent of #9621 so that managed files don't get updated too soon.

/kind feature
/area cloudformation
/lifecycle frozen

**Comment by rifelpet** [comment]
For reference: CloudFormation doesn't support defining S3 Objects so this will likely require the use of a custom resource or macro, for example: https://github.com/awslabs/aws-cloudformation-templates/tree/a11722d/aws/services/CloudFormation/MacrosExamples/S3Objects
