### ISSUE TITLE
Allow Cluster Resources To Be More Discernable

### ISSUE THREAD

**Issue by brandoncole** [kubernetes/kops#1192]
Once a cluster is created, there are dozens of resources that result:

1. EC2 Instances
2. VPCs
3. Subnets
4. ELBs
5. Volumes
6. Security Groups
7. Auto Scaling Groups, etc.

When you're running dozens of clusters in the same account it can become challenging from within the AWS Console to see which resources are associated with which K8s clusters created by Kops.  One thought was to perhaps organize things during creation into Resource Groups:

* http://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/supported-resources.html

@faraazkhan @chrislovecnm @kris-nova

**Comment by chrislovecnm** [comment]
Looking at the docs are these the only things supported by a resource group

Instance
Load balancer
Security group
Snapshot
Volume

**Comment by chrislovecnm** [comment]
I think this applies as well

https://github.com/kubernetes/kops/issues/1189

**Comment by chrislovecnm** [comment]
Here is a start of the lost used by public clusters. This is a janitor script that cleans up after test runs - https://github.com/kubernetes/test-infra/blob/master/jenkins/aws-janitor/main.go

**Comment by kris-nova** [comment]
This also is relevant https://github.com/kubernetes/kops/issues/1077

**Comment by kris-nova** [comment]
But yes - the idea of having a way to pull a **master list** out of kops is sounding more and more important. 

We talked about using the master list in a few ways, but with one of the biggest ways being a cluster clean up audit something or other.

Using Amazon resource groups here is frankly pretty genius, why is this in kops yet? This seems like a must have.

**Comment by chrislovecnm** [comment]
Can resource groups cover all the bells and whistles we use? Also can a resource group have resource groups?

We have a bit of a Russian doll

Cluster -> 2+ instance groups

**Comment by yissachar** [comment]
I tried setting up a ResourceGroup manually for an existing Kubernetes cluster, using the `KubernetesCluster` tag as the discriminator. This is what I saw:

Instances
Load Balancers
Security Groups
Volumes
VPC

The various VPC details (subnets, route tables, gateways, etc.) are not visible from the ResourceGroup. I'm not sure that ResourceGroups have enough detail to be useful for this feature.

**Comment by chrislovecnm** [comment]
We have:

- IAM roles
- ASG
- ASG templates
- ELBs
- Bastions with private networking (now an instancegroup)
- SSH keys
- The ami used
- S3 bucket -> state_store

^ that is just off the top of my head.

**Comment by justinsb** [comment]
So are we agreed that #1077 is the way to go?

We have a first step in #1274 if so

**Comment by sstarcher** [comment]
@justinsb with #1077 closed and #1274 merged what's the state of this.

**Comment by chrislovecnm** [comment]
@sstartcher close?

**Comment by sstarcher** [comment]
feel free to close it
