### ISSUE TITLE
Nonsensical error message when requesting multiple Digital Ocean zones

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#11931]
/kind bug
/area provider/digitalocean
/cc @srikiz 

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Master branch

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

N/A

**3. What cloud provider are you using?**

Digital Ocean

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops create cluster k8s.example.com --zones NYC1,NYC2,NYC3 --cloud digitalocean`

**5. What happened after the commands executed?**

`digitalocean cloud provider currently only supports 1 region, expect multi-region support when digitalocean support is in beta`

**6. What did you expect to happen?**

Digital Ocean support *is* in beta. I expect the error message to not promise something by a past event.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

**Comment by srikiz** [comment]
Thanks @johngmyers - I'll fix this.
