### ISSUE TITLE
using custom sshkey in secret or as cli arg, kops can't find private ssh key

### ISSUE THREAD

**Issue by TristanB1994** [kubernetes/kops#11942]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.20.1 (git-5a27dad40a703f646433595a2a40cf94a0c43cd5)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops create secret --name sub.domain.tld sshpublickey admin -i ~/.ssh/custom_key.pub`
`kops update cluster --name sub.domain.tld --yes`

**5. What happened after the commands executed?**

When I try to use kubectl I'm returned a login request, fill username fill password, since a password was never set the request hangs

**6. What did you expect to happen?**

I expected kops to find the private key in ~/.ssh/custom_key and auto authenticate.

**7. Please provide your cluster manifest. Execute
  
`apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-07-06T19:11:51Z"
  name: sub.domain.tld
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-cluster-state-fl/sub.domain.tld
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.8
  masterPublicName: sub.domain.tld
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - vpn.cidr.block.address/24
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 172.20.96.0/19
    name: us-east-1c
    type: Public
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-07-06T19:11:52Z"
  labels:
    kops.k8s.io/cluster: sub.domain.tld
  name: master-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210503
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-07-06T19:11:52Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: sub.domain.tld
  name: nodes-us-east-1a
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/sub.domain.tld: "1"
    k8s.io/cluster-autoscaler/enabled: "1"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210503
  machineType: t3.medium
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - c3.2xlarge
    - c3.xlarge
    - c4.2xlarge
    - c4.xlarge
    - c5.2xlarge
    - c5.large
    - c5.xlarge
    - c5a.2xlarge
    - c5a.large
    - c5a.xlarge
    - t2.medium
    - t3.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-07-06T19:11:52Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: sub.domain.tld
  name: nodes-us-east-1b
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/sub.domain.tld: "1"
    k8s.io/cluster-autoscaler/enabled: "1"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210503
  machineType: t3.medium
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - c3.2xlarge
    - c3.xlarge
    - c4.2xlarge
    - c4.xlarge
    - c5.2xlarge
    - c5.large
    - c5.xlarge
    - c5a.2xlarge
    - c5a.large
    - c5a.xlarge
    - t2.medium
    - t3.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1b
  role: Node
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-07-06T19:11:52Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: sub.domain.tld
  name: nodes-us-east-1c
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/sub.domain.tld: "1"
    k8s.io/cluster-autoscaler/enabled: "1"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210503
  machineType: t3.medium
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - c3.2xlarge
    - c3.xlarge
    - c4.2xlarge
    - c4.xlarge
    - c5.2xlarge
    - c5.large
    - c5.xlarge
    - c5a.2xlarge
    - c5a.large
    - c5a.xlarge
    - t2.medium
    - t3.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1c
  role: Node
  subnets:
  - us-east-1c`
  

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by johngmyers** [comment]
The sshpublickey is used for SSH to the nodes, not for access to the Kubernetes API.

**Comment by TristanB1994** [comment]
> The sshpublickey is used for SSH to the nodes, not for access to the Kubernetes API.

Right, well thanks for reviewing this issue but I don't see how that's relevant for the can't find private key error.

**Comment by johngmyers** [comment]
The initial report said "When I try to use kubectl", which, although vague, means you were trying to access the Kubernetes API.

But perhaps you could report the commands you ran, like the form requests?

**Comment by TristanB1994** [comment]
> The initial report said "When I try to use kubectl", which, although vague, means you were trying to access the Kubernetes API.
> 
> But perhaps you could report the commands you ran, like the form requests?

I was attempting to ssh into the nodes with the custom ssh key and something I've changed is working now. Thanks for looking at this
