### ISSUE TITLE
Use different user

### ISSUE THREAD

**Issue by Silvanoc** [kubernetes/kops#11959]
/kind feature

In my company we have an IAM system that can be used in parallel to the AWS one and provides additional functionality. But I'm not free to select whatever user I want.

Is there a technical reason why I cannot use the username that I like and I'm being forced to create a `kops` user? Or is it simply a missing feature?

In my case I can use different roles to specify different policies and that's what I'd do for kOps.
I'd simply need an optional argument like `--username`.

**Comment by olemarkus** [comment]
I don't quite follow what you want from this request. Where does kOps require a user called `kops`? Are you referring to the IAM user from the example docs? If so, that is just an example. You can run kOps from any environment that has the sufficient privileges.

**Comment by Silvanoc** [comment]
When I've seen "The `kops` user", I've interpreted that the users name HAS to be `kops`. I mean, you have a bit afterwards the sentence "... the kOps IAM user", what is obvious enough not to be a username.

If whatever user with the right permissions works, then the origin of my error must be something else :slightly_smiling_face: and this issue can be closed. I was wondering anyway, why you need a specific user. But I didn't know how to ask it otherwise since there's no Slack, Google Groups or similar.

May I then propose to add an explanation sentence like "Whatever user with the required permissions will suffice, we will use `kops` in the following code snippets."? Or replacing the sample user with `kops_user`, `john_doe`,...

**Comment by olemarkus** [comment]
#kops-user channel on the k8s slack :)

**Comment by Silvanoc** [comment]
Having the discussion now here, I won't reopen it in Slack :slightly_smiling_face: 

Since I assume that my previous comment is correct (whatever user with specified permissions will suffice) because you didn't correct it, I'm closing this issue.

Thanks for your quick reaction and great tool.

**Comment by Silvanoc** [comment]
BTW @olemarkus just a heads-up regarding the Slack channel and contribution documentation.

The document [CONTRIBUTING.md](https://github.com/kubernetes/kops/blob/master/CONTRIBUTING.md) doesn't report neither the Slack channel nor the contribution documentation.

The [contribution documentation](https://kops.sigs.k8s.io/welcome/contributing/) is returning me 404.

I've only be able to confirm that you provide the Slack channel in the contribution documentation doing a GitHub search on your repo.

**Comment by MoShitrit** [comment]
> BTW @olemarkus just a heads-up regarding the Slack channel and contribution documentation.
> 
> The document [CONTRIBUTING.md](https://github.com/kubernetes/kops/blob/master/CONTRIBUTING.md) doesn't report neither the Slack channel nor the contribution documentation.
> 
> The [contribution documentation](https://kops.sigs.k8s.io/welcome/contributing/) is returning me 404.
> 
> I've only be able to confirm that you provide the Slack channel in the contribution documentation doing a GitHub search on your repo.

@Silvanoc thanks for raising the flag on that!
Regarding the Slack channels, you can see their info [here](https://kops.sigs.k8s.io/contributing/#other-ways-to-communicate-with-the-contributors).
And regarding the broken link, I have created PR #11979 to fix it, it should be pointing [here](https://kops.sigs.k8s.io/contributing/) instead.

**Comment by Silvanoc** [comment]
> Regarding the Slack channels, you can see their info [here](https://kops.sigs.k8s.io/contributing/#other-ways-to-communicate-with-the-contributors).

I found the info looking searching for it in the code of this repo, but I nevertheless would expect CONTRIBUTING.md to provide the link https://kops.sigs.k8s.io/contributing/ or to mention it (if no link is desired to a possibly changing documentation page) like "look at the docs to contact the community".

> And regarding the broken link, I have created PR #11979 to fix it, it should be pointing [here](https://kops.sigs.k8s.io/contributing/) instead.

It appears to be working now.
