### ISSUE TITLE
Add the ability to specify an existing Azure Virtual Network

### ISSUE THREAD

**Issue by alexivanoff** [kubernetes/kops#11950]
/kind feature

Currently, we can specify AWS VPC, this flag: 
--vpc string                         Set to use a shared VPC

But there is no option to specify Azure Virtual Network. We can't specify it even through the config file.
So I offer to add the following abilities:
1. specify Azure VNET via flag:
--azure-vnet                         Set to use a shared Virtual Network.
2. use "networkID:" for Virtual Network in the kops config file.

**Comment by rifelpet** [comment]
Have you tried specifying the `cluster.spec.networkID` as you suggest? From my preliminary glancing at the code it appears that it should work. If it doesn't cant you provide any error messages? That would be the approach that we would use to suppose existing virtual networks. It would also work with the `kops create cluster --vpc` flag automatically.

**Comment by alexivanoff** [comment]
No, I tried `--vpc` flag only and got:
```
error populating configuration: FindVPCInfo not implemented on azureCloud
```
But yes, it works via `cluster.spec.networkID`. I've checked on my side. Thank you!

**Comment by Prashanth-M** [comment]
Kops Azure -  cluster create with vpc/networkID for using shared existing Vnet throwing below error:

Error: error populating configuration: unable to find Network ID

kops create cluster \
  --cloud azure \
  --name abc.com \
  --zones uswest-1 \
  --vpc /subscriptions/fsjjj-ssss-ssss/resourceGroups/abc-rg/providers/Microsoft.Network/virtualNetworks/vnet1t \
  --networking calico \
  --azure-subscription-id "${AZURE_SUBSCRIPTION_ID}" \
  --azure-tenant-id "${AZURE_TENANT_ID}" \
  --azure-resource-group-name platform-services-rg \
  --azure-route-table-name platform-services-rt \
  --azure-admin-user ubuntu

**Comment by Prashanth-M** [comment]
Kops Azure -  cluster create with vpc/networkID for using shared existing Vnet throwing below error:

Error: error populating configuration: unable to find Network ID

kops create cluster \
  --cloud azure \
  --name abc.com \
  --zones uswest-1 \
  --vpc /subscriptions/fsjjj-ssss-ssss/resourceGroups/abc-rg/providers/Microsoft.Network/virtualNetworks/vnet1t \
  --networking calico \
  --azure-subscription-id "${AZURE_SUBSCRIPTION_ID}" \
  --azure-tenant-id "${AZURE_TENANT_ID}" \
  --azure-resource-group-name abc-rg \
  --azure-route-table-name abc-rt \
  --azure-admin-user ubuntu

Any suggestions?
