### ISSUE TITLE
--node-security-groups and --master-security-groups flags  don't work now with Azure NSG

### ISSUE THREAD

**Issue by alexivanoff** [kubernetes/kops#11954]
/kind bug
/area provider/azure

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
I0708 12:43:49.773057 15022 featureflag.go:165] FeatureFlag "Azure"=true
Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
Azure

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
a. Create Azure Resource group: test-rg
b. Create Network Security Group: test
c. kops create cluster --cloud azure --name test-1.k8s.local --zones eastus-1 --networking calico --azure-subscription-id "${AZURE_SUBSCRIPTION_ID}" --azure-tenant-id "${AZURE_TENANT_ID}" --azure-resource-group-name test-rg --azure-route-table-name test-route-table --azure-admin-user testadmin  --network-cidr 10.0.0.0/16 --node-security-groups test --master-security-groups test
d. kops update cluster --name test-1.k8s.local --yes --admin

**5. What happened after the commands executed?**
A new k8s cluster was created without any issue. But "test" NSG wasn't attached to the new instances of master and node Scale Sets.

**6. What did you expect to happen?**
test NSG should be attached to the new instances of master and node Scale Sets.

**Comment by rifelpet** [comment]
Kops doesn't manage any Azure NSGs yet so we'll need to add support for recognizing and managing them first.
