### ISSUE TITLE
AuthorizationPermissionMismatch during kOps bootstrap using Azure provider

### ISSUE THREAD

**Issue by alexivanoff** [kubernetes/kops#11965]
/kind bug
/area provider/azure

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
I0708 12:43:49.773057 15022 featureflag.go:165] FeatureFlag "Azure"=true
Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
Azure

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
$ kops create cluster --cloud azure --name my-azure.k8s.local --zones eastus-1 --network-cidr 172.16.0.0/16 --networking calico --azure-subscription-id "${AZURE_SUBSCRIPTION_ID}" --azure-tenant-id "${AZURE_TENANT_ID}" --azure-resource-group-name kops-test --azure-route-table-name kops-test --azure-admin-user ubuntu
$ kops update cluster --name my-azure.k8s.local --yes --admin

**5. What happened after the commands executed?**
kOps bootstrap process fails on master and node Scale Set VMs:
$ cat /var/log/syslog
```
Jul  9 10:37:41 master-eastus-1000001 systemd[1]: Starting Run kOps bootstrap (nodeup)...
Jul  9 10:37:41 master-eastus-1000001 nodeup[1696]: nodeup version 1.21.0
Jul  9 10:37:41 master-eastus-1000001 nodeup[1696]: I0709 10:37:41.158985    1696 azureclient.go:82] Creating a token credential from Instance Metadata Service.
Jul  9 10:37:43 master-eastus-1000001 /opt/kops/bin/nodeup[1696]: 2021/07/09 10:37:43 ==> REQUEST/RESPONSE (Try=1/1.4028635s, OpTime=1.4028996s) -- REQUEST ERROR#012   GET https://kopseaststatestore01.blob.core.windows.net/cluster-configs/my-azure.k8s.local/cluster.spec?timeout=61>Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]: W0709 10:37:43.261896    1696 main.go:133] got error running nodeup (will retry in 30s): error loading Cluster &{%!q(*vfs.azureClient=&{0xc00052e640 kopseaststatestore01}) "cluster-configs" "my-azure.k8s.local/cluster.spec" ""}: >Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]: ===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]: Description=This request is not authorized to perform this operation using this permission.
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]: RequestId:da0c860a-e01e-0046-0dae-74a3e1000000
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]: Time:2021-07-09T10:37:43.2590114Z, Details:
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    Code: AuthorizationPermissionMismatch
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    GET https://kopseaststatestore01.blob.core.windows.net/cluster-configs/my-azure.k8s.local/cluster.spec?timeout=61
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    Authorization: REDACTED
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    User-Agent: [Azure-Storage/0.13 (go1.16.5; linux)]
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    X-Ms-Client-Request-Id: [247b0f14-c0c7-4f14-6a07-485e4f37770a]
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    X-Ms-Version: [2019-12-12]
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    --------------------------------------------------------------------------------
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    Content-Length: [279]
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    Content-Type: [application/xml]
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    Date: [Fri, 09 Jul 2021 10:37:42 GMT]
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    X-Ms-Client-Request-Id: [247b0f14-c0c7-4f14-6a07-485e4f37770a]
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    X-Ms-Error-Code: [AuthorizationPermissionMismatch]
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    X-Ms-Request-Id: [da0c860a-e01e-0046-0dae-74a3e1000000]
Jul  9 10:37:43 master-eastus-1000001 nodeup[1696]:    X-Ms-Version: [2019-12-12]
```

**6. What did you expect to happen?**
kOps bootstrap process should be finished without issues on master and node VMs.

**7. Anything else do we need to know?**
I just tried to go through the doc: https://kops.sigs.k8s.io/getting_started/azure/

And judging by the doc some Role assignments have to be created during kOps cluster creation, but I see only one role assignment in Access control (IAM) which I created using this command:
```
$ az ad sp create-for-rbac --name kops-test --role owner --sdk-auth
```
So I think there should be more role assignments.

**Comment by rifelpet** [comment]
kops should create a role assignment for the scale set giving it access to the blob store:

https://github.com/kubernetes/kops/blob/db9dff6f78843691990e82d13536bcfde7ec5b4f/pkg/model/azuremodel/vmscaleset.go#L52-L63

Can you confirm whether those role definition IDs have assignments for the scale set?

Perhaps @kenji-cloudnatix may be able to help here.

**Comment by kenji-cloudnatix** [comment]
Yes, what @rifelpet pointed out is correct. 

I'm not sure if this is the case, but I sometimes see a long delay until the role assignment becomes effective in Azure VMs. @alexivanoff , it would be great if you could check if this issue can be consistently reproduced or not.

**Comment by alexivanoff** [comment]
I haven't managed to reproduce it, tried several times using different accounts and subscriptions.
So yes. can be related to "long delay". 
Not sure, but I guess we can close the issue.
