### ISSUE TITLE
Node Termination Handler requires more rights then listed in doc

### ISSUE THREAD

**Issue by todd-berger** [kubernetes/kops#11968]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
 
 1.21.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
 N/a
 
**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Following https://kops.sigs.k8s.io/addons/#queue-processor-mode
Applied the IAM policy provided..

Then applying the cluster spec 
spec:
  nodeTerminationHandler:
    enabled: true
    enableSpotInterruptionDraining: true
    enableSQSTerminationDraining: true
    enableScheduledEventDraining: true
    enablePrometheusMetrics: true
    managedASGTag: "aws-node-termination-handler/managed"
applying that template and running kops update cluster xxxxx --yes --state=s3://xxxx --target=direct --create-kube-config=true

**5. What happened after the commands executed?**
I0710 00:39:12.626461      24 executor.go:111] Tasks: 168 done / 174 total; 3 can run
W0710 00:39:12.873597      24 executor.go:139] error running task "EventBridgeRule/ak8s-xxx.aws.local-SpotInterruption" (9m55s remaining to succeed): error creating EventBridge rule: AccessDeniedException: User: arn:aws:sts::xxxxx:assumed-role/xxxxx is not authorized to perform: events:PutRule on resource: arn:aws:events:xxx:rule/xxx-SpotInterruption

and events:TagResource failures on update.

**6. What did you expect to happen?**
It to work without adding
        "events:TagResource",
        "events:PutRule",
        
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
(not sure necessary, happy to edit and provide if needed)
```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Adding 
        "events:TagResource",
        "events:PutRule",
resolved the issue

**Comment by olemarkus** [comment]
Thanks for reporting this. we'll update the documentation accordingly.
