### ISSUE TITLE
Sublime does not seem to work on edit

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1197]
It has been reported that sublime works with `kubectl edit` but does not work with `kops` edit functions.  Need to determine why.

**Comment by justinsb** [comment]
Seems to work

```
ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" ~/bin/subl
export EDITOR="subl --wait"
```

What does "not work" mean?

**Comment by chrislovecnm** [comment]
Closing, as you have the solution

**Comment by engmsaleh** [comment]
It didn't work for me 
`error: unable to launch the editor "subl --wait"`
