### ISSUE TITLE
Allow specifying dns-name separately?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#12]
Maybe we should allow the ClusterName to be different from the DNS name.  Users will likely want to specify a shorter name, for example.  And this means we're less bound to DNS at the schema level.

On the flip side, it means cluster names are no longer globally unique.

**Comment by yissachar** [comment]
`On the flip side, it means cluster names are no longer globally unique.`

Why does this matter? Or does globally here mean within the same AWS account?

**Comment by mrichmon** [comment]
What

**Comment by blakebarnett** [comment]
Seems like maybe there should be a `clusterUid` and things like the AWS tags should just combine `$clusterUid-$clusterName`.  Should probably set max-length on `clusterName` then to be in line with AWS tag length limits.
