### ISSUE TITLE
Bump aws-ebs-csi-driver to version 1.1.1

### ISSUE THREAD

**Issue by AljoschaP** [kubernetes/kops#12026]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Because a new version of the aws-ebs-csi-driver has been released ([1.1.1](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/tag/v1.1.1)), kops should follow :-). This [commit](https://github.com/kubernetes/kops/commit/14fb35d0d001bddd929f46bf68f6f0a152d9c4d6) could provide guidance.

**2. Feel free to provide a design supporting your feature request.**
\-

Thank you :+1: :heart:

**Comment by olemarkus** [comment]
I don't think at least this patch version will be backported to 1.21. And we'll wait a bit with bumping the addons for 1.22, so we may target a later release here.

**Comment by olemarkus** [comment]
/close

This was bumped to 1.2.0 in #12129
