### ISSUE TITLE
Instance Group externalLoadBalancers opt-out

### ISSUE THREAD

**Issue by Artiax** [kubernetes/kops#12033]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

After the change was made (for right/obvious reasons) to remove externally created ELB/NLB attachments if they're not present in the externalLoadBalancers list, each time we run an update to the cluster the attachments for load balancers we have created (and attached) outside of the KOPS code are getting removed thus potentially causing an unavailability to some of the services until the load balancers are re-attached via the outside process.

We run a hybrid mode whereby part of the code is applied through KOPS and part of it is in Terraform, currently to work around it we're having to declare the attachments in both areas which doesn't feel neat.

We would like a feature, a bit like the lifecycle-overrides to disable the attachment/detachment of externally created load balancers, or at least an ability to return the previous functionality whereby this used to operate in a kind of "one-way street" fashion.

**2. Feel free to provide a design supporting your feature request.**

**Comment by olemarkus** [comment]
This isn't an unreasonable feature request, and I would be happy to review a PR.
