### ISSUE TITLE
Empty updates to _vendor in PRs

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1203]
Any idea what is going on here? Or more importantly why `_vendor` is still hanging out in our repository?

<img width="909" alt="screen shot 2016-12-19 at 12 07 49 am" src="https://cloud.githubusercontent.com/assets/13757818/21303980/60346204-c57f-11e6-8b8d-bbbbe1937f6e.png">

**Comment by justinsb** [comment]
_vendor is where we store the submodules; we rsync them to vendor.  Documented here https://github.com/kubernetes/kops/blob/master/docs/development/dependencies.md

If you're updating the submodules and adding them to your commit (it looks like you are), they will be added.

You shouldn't be adding them.  You also shouldn't really be updating them unless you are actually updating dependencies, I don't think.
