### ISSUE TITLE
volumeIops to volumeSize ratio must be lower than 50. For 1.etcd-main ratio is 50.00

### ISSUE THREAD

**Issue by ValeriiVozniuk** [kubernetes/kops#12038]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
` kubectl v1.21.0`
Last working versions are 1.20.0/1.21.0-alpha.2, first affected versions are 1.20.1 and 1.21.0-alpha.3

**3. What cloud provider are you using?**
`aws`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops replace --force -f cluster.yaml --name $CLUSTER_NAME`

**5. What happened after the commands executed?**
`error building tasks: volumeIops to volumeSize ratio must be lower than 50. For 1.etcd-main ratio is 50.00`

**6. What did you expect to happen?**
Cluster successfully created as was with kops 1.19.2

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
Relevant part is
```
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-north-1a-1
      name: "1"
      volumeIops: 1000
      volumeSize: 20
      volumeType: io1
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
Nothing relevant there, unfortunately, I just see the values in spec, and then a failure
```
I0722 14:09:55.972668   31923 spec_builder.go:46] options: {
...
  "etcdClusters": [
    {
      "name": "main",
      "provider": "Manager",
      "etcdMembers": [
        {
          "name": "1",
          "instanceGroup": "master-eu-north-1a-1",
          "volumeType": "io1",
          "volumeIops": 1000,
          "volumeSize": 20
        },
...
I0722 14:10:10.839268   31923 task.go:108] testing task "ManagedFile"
I0722 14:10:10.839337   31923 task.go:108] testing task "ManagedFile"
I0722 14:10:10.839346   31923 task.go:108] testing task "Keypair"
I0722 14:10:10.839372   31923 task.go:108] testing task "Keypair"
I0722 14:10:10.839398   31923 task.go:108] testing task "Keypair"
I0722 14:10:10.839650   31923 build_flags.go:49] ignoring non-field:
I0722 14:10:10.839682   31923 build_flags.go:49] ignoring non-field:
I0722 14:10:10.840158   31923 task.go:108] testing task "ManagedFile"
I0722 14:10:10.840201   31923 task.go:108] testing task "ManagedFile"
I0722 14:10:10.840207   31923 task.go:108] testing task "Keypair"
I0722 14:10:10.840211   31923 task.go:108] testing task "Keypair"
I0722 14:10:10.840214   31923 task.go:108] testing task "Keypair"
I0722 14:10:10.840231   31923 task.go:81] EnsureTask ignoring identical

error building tasks: volumeIops to volumeSize ratio must be lower than 50. For 1.etcd-main.208.k8s.wixprod.net ratio is 50.00
```

**9. Anything else do we need to know?**
Reviewing changelog for 1.21.0-alpha.3 it seems this pull is the source of the issue
https://github.com/kubernetes/kops/pull/11225/files
Looks like rounding is needed somewhere starting from this block
https://github.com/kubernetes/kops/blob/master/pkg/model/master_volumes.go#L146
But upon quick research it looks like Go doesn't support proper rounding for float64. Looking on the old code, I have a guess that previous calls to int64() maybe were helping there, but not sure. Also I've checked the smallest possible value for that relation, which should overflow, it is 50,0002, so a dirty hack here would be to multiply the relation by 10000, converting to int32, and compare it to 50000 )).

**Comment by ValeriiVozniuk** [comment]
While reading one topic on one of the internet forums, I've found this article explaining issues with float/double comparisons
https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/
So it seems that code before was working on edge cases by sheer luck, and the current one needs to be adjusted to work properly on the edge cases

**Comment by olemarkus** [comment]
I do not think it is that sinister. According to AWS docs, the max ratio is 50:1, but we test for "higher or _equal_" to 50.0 when we test for failure. Removing that equal fixes this. I'll do a PR shortly.
