### ISSUE TITLE
Assign a single IP for all outgoing request from the cluster

### ISSUE THREAD

**Issue by sujeet-agrahari** [kubernetes/kops#12034]
I have setup a cluster using kops on AWS. It has created a `internet gateway` for incoming request to cluster to only one ip.

What can I do to assign a single IP for all outgoing reuqest?

I have created a `NAT` gateway and allocated a elastic IP address. But it's not using that gateway IP instead request from pods are assigned source IP of the node.

**Comment by hakman** [comment]
To use the Nat GW, nodes must be in a private subnet.
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html#public-nat-internet-access

**Comment by sujeet-agrahari** [comment]
What can I do here? The nodes are in public subnet. I want to unified IP for outgoing  requests.

**Comment by hakman** [comment]
You can use private subnet and assign public IPs to the nodes. There is no way to route nodes from public subnets through a Nat GW (to my knowledge).
