### ISSUE TITLE
Set sysctl for kernel.softlock_panic

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1204]
The equivalent of https://github.com/kubernetes/kubernetes/pull/38001

```
+/etc/sysctl.conf:
+  file.append:
+    - text:
+      - "kernel.softlockup_panic = 1"
+      - "kernel.softlockup_all_cpu_backtrace = 1"
```

**Comment by chrislovecnm** [comment]
We going to do this in `kops` or the image?  I would recommend this in kops

**Comment by justinsb** [comment]
kops, yes.  There are also some nginx tweaks which should be good across the board.

**Comment by justinsb** [comment]
nginx sysctls https://github.com/kubernetes/kube-deploy/issues/261

By putting them into kops, we have more control, and it works even if they aren't in the base image (e.g. if you're running a stock ubuntu image)

**Comment by justinsb** [comment]
Implemented
