### ISSUE TITLE
 CNCF Kubernetes Conformance for kOps 1.21

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#12054]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
 We should be conformant for 1.21

**2. Feel free to provide a design supporting your feature request.**

ref: https://github.com/kubernetes/kops/issues/11492

**Comment by mikesplain** [comment]
Yep, I'll take care of it!

**Comment by mikesplain** [comment]
This is complete!
