### ISSUE TITLE
rolling-update cluster. The --fail-on-validate-error="false" flag isn't having an effect.

### ISSUE THREAD

**Issue by jim-barber-he** [kubernetes/kops#12057]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)

Although I'm reasonably certain I've seen the problem in kops 1.20 as well.

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.21.3

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops rolling-update cluster --fail-on-validate-error="false" --instance-group master-ap-southeast-2a --yes
```

**5. What happened after the commands executed?**

On a cluster that was failing to pass validation because more coredns pods were not coming ready (because our custom config didn't add the `ready` plugin that kops 1.21 added), the nodes would not role even when `--fail-on-validate-error="false"` was used.
Instead the command kept showing that the cluster failed validation and kept waiting for it to become valid.

**6. What did you expect to happen?**

Ignore the validation errors and role the node anyway.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Not really applicable.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by olemarkus** [comment]
Sorry for taking so long to respond to this.
kOps will continue to validate the cluster until timeout has reached. The actual failure happens when kOps have tried to validate for that long and it is still not valid.
If you want kOps to immediately move on, you need to also pass in `--validation-timeout=0`.

/remove-lifecycle rotten
/remove-kind bug
/kind support

**Comment by jim-barber-he** [comment]
I had need of using this again today.
The use of `--validation-timeout=0` was what was required.
Closing this issue.
