### ISSUE TITLE
Scale up and down instance group size on a schedule

### ISSUE THREAD

**Issue by superfly-git** [kubernetes/kops#12053]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
I would like to have the ability to schedule a scale up on one of the instance groups for a large machine that i use for a specific purpose. I have a corresponding K8s cron job that i only want it to run on that node that has a specific label. I only want to run this job on a specific time of day and then scale down the instance group back to 0. The job takes around 1 hour to complete and  i want to allocate a whole node to it as it is a very resource intensive operation.

**Comment by johngmyers** [comment]
That's a bit outside the scope of kOps. It's more in the scope of cluster-autoscaler.

**Comment by hakman** [comment]
I think you can create an instance group with min=0 and max=1, with a taint tolerated only by your cron job.
Autoscaler should notice that it's unschedulable on other nodes and scale-up that instance group. Later, when job is done, should be able to notice and scale-down.

**Comment by superfly-git** [comment]
Thanks a lot for the idea @hakman . Indeed that is something that is not in scope of KOPS.

**Comment by hakman** [comment]
👍
