### ISSUE TITLE
Flag registry-qps not supported in Kubelet

### ISSUE THREAD

**Issue by arindosCredible** [kubernetes/kops#12068]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

version 1.18.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.18.17

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops edit cluster, then try to add the registryQps option to the kubelet section.

**5. What happened after the commands executed?**

"Found fields that are not recognized", config is not accepted.

**6. What did you expect to happen?**

Config would update

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

...
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    readOnlyPort: 0
...
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

I0729 10:58:12.875129    7118 s3fs.go:290] Reading file "s3://foobarfoobarfoobar"
I0729 10:58:13.073476    7118 editor.go:128] Opening file with editor [vi /var/folders/t2/x_jvg_8n2r97zd0ns6t_ht100000gp/T/kops-edit-xxvi7yaml]

**9. Anything else do we need to know?**

also tried registryQPS to no avail, registryBurst is accepted

**Comment by johngmyers** [comment]
The field is `registryPullQPS`.
/close
