### ISSUE TITLE
Show the right SSH key in the suggestions after cluster bring-up

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#1207]
After bringing up a cluster I get the following message:

```
Cluster is starting.  It should be ready in a few minutes.

Suggestions:
 * list nodes: kubectl get nodes --show-labels
 * ssh to the master: ssh -i ~/.ssh/id_rsa admin@api.foo.bar.com
 * read about installing addons: https://github.com/kubernetes/kops/blob/master/docs/addons.md
```

The SSH message currently [hardcodes](https://github.com/kubernetes/kops/blob/c4b258351fb066cc91fa656aea503ec62c75461c/cmd/kops/update_cluster.go#L212) `~/.ssh/id_rsa`, but it should really show the SSH key being used.

**Comment by justinsb** [comment]
This is actually surprisingly difficult.

A few options:

* We could store more metadata which is the path to the key.  But it might vary across multiple machines.
* We could compare keys to find one that matches.  This is work and some users might not appreciate our scanning their keys (although scanning your public keys should be OK).
* We could simply not include the hard-coded value.

Punting to 1.5.1

**Comment by chrislovecnm** [comment]
Yah this need to be text in ux ... this is not trivial
