### ISSUE TITLE
Flatcar AWS AMI OwnerID Changed

### ISSUE THREAD

**Issue by J-Ha** [kubernetes/kops#12086]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.20.2 (git-e6ca69f55e91f87080c897216115efb811673718)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.20.8

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
AutoScaling

**5. What happened after the commands executed?**
OwnerID could not be referenced 

**6. What did you expect to happen?**
scaleup

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

The AMI Owner ID of FlatcarImages has been changed. 
so the image could not be found and no new node could be added.

`[apps-eu-west-1a-mixed.spec.image: Invalid value: "flatcar/Flatcar-stable-2765.2.6-hvm": image specified is invalid: "flatcar/Flatcar-stable-2765.2.6-hvm", spec.mixedInstancesPolicy.image: Invalid value: "flatcar/Flatcar-stable-2765.2.6-hvm": image specified is invalid: "flatcar/Flatcar-stable-2765.2.6-hvm"]`

the old OwnerID is: 075585003325
the new OwnerID is: 679593333241 

by editing the Image in the IG Spec from

`flatcar/Flatcar-stable-2765.2.6-hvm` 

to
`679593333241/Flatcar-stable-2765.2.6-hvm-1716ad1c-deff-42e5-86bc-228658463d0e`

the node scaled up.

**Comment by J-Ha** [comment]
https://twitter.com/kinvolkio/status/1421853914652188673

**Comment by rifelpet** [comment]
ref: https://github.com/kinvolk/Flatcar/issues/456

It looks like AMIs have been restored to the original account ID and it sounds like they intend for future AMIs to be published to the same account ID, so there is no work to be done at this point.

/close
