### ISSUE TITLE
"Error getting node" on master node using Azure provider

### ISSUE THREAD

**Issue by alexivanoff** [kubernetes/kops#12094]
/kind bug
/area provider/azure

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
I0803 10:25:04.953512    2283 featureflag.go:165] FeatureFlag "Azure"=true
Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
Azure

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
$ kops create cluster --cloud azure --name my-azure.k8s.local --zones eastus-1 --network-cidr 172.16.0.0/16 --networking calico --azure-subscription-id "${AZURE_SUBSCRIPTION_ID}" --azure-tenant-id "${AZURE_TENANT_ID}" --azure-resource-group-name kops-test-3 --azure-route-table-name kops-test-3 --azure-admin-user ubuntu
$ kops update cluster    --name my-azure.k8s.local   --yes -v 10

**5. What happened after the commands executed?**
I didn't manage to connect to the cluster.

When I connected to the master node I noticed that 443 port was down and a lot of following error in syslog file:
```
5441 kubelet.go:2291] "Error getting node" err="node \"master-eastus-1000001\" not found"
```

**6. What did you expect to happen?**
A Succefully connection to Kubernetes cluster.

**7. Anything else do we need to know?**
I just tried to go through the doc: https://kops.sigs.k8s.io/getting_started/azure/
I made several attempts but still facing the same errors.
The full log: [master_syslog.zip](https://github.com/kubernetes/kops/files/6924927/master_syslog.zip)

**Comment by thg-adamdean** [comment]
Seeing the same symptoms using the OpenStack provider. Still debugging.
