### ISSUE TITLE
Enable Cluster Autoscaler Addon Prometheus Metrics

### ISSUE THREAD

**Issue by stewbernetes** [kubernetes/kops#12095]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

The cluster-autoscaler is capable of emitting a number of useful prometheus metrics.

It would be really useful to be able to enable the metrics endpoint for the autoscaler via configuration through the cluster spec, something like:

`spec:
  clusterAutoscaler:
    metrics: true
`

Alternatively, any guidance on how to go about doing this would be equally valuable.

Thank you!

**Comment by olemarkus** [comment]
Metrics are available on port 8085 already. There is no config needed to switch this on.
