### ISSUE TITLE
Should we use the helm install script

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1210]
https://github.com/kubernetes/helm/blob/master/scripts/get

**Comment by chrislovecnm** [comment]
We need to make our installs easier.  The above script may help

**Comment by justinsb** [comment]
Which install BTW?  The install of kops?

**Comment by chrislovecnm** [comment]
Yah install kops from it, just another option.

**Comment by kenden** [comment]
Dou you think Helm itself be used to template cluster.yml file or instancegroups.yaml files ?
https://github.com/kubernetes/kops/issues/2404
