### ISSUE TITLE
Cluster Autoscaler AddOn Spec to pass extra argument to command line

### ISSUE THREAD

**Issue by amitpd** [kubernetes/kops#12100]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Cluster Autoscaler, since v1.17.0, automatic discovery of EC2 instance types is enabled by default. To change it to static list, an additional command line flag `--aws-use-static-instance-list=true` need to be set as per below documentation.

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#use-static-instance-list

**2. Feel free to provide a design supporting your feature request.**

An additional spec in cluster spec.clusterAutoscaler.awsUseStaticInstanceList can be added to control this additional command line flags.

**Comment by olemarkus** [comment]
If you are able to contribute a PR for this, I am happy to review.

**Comment by amitpd** [comment]
@olemarkus Raised below PR for this feature
https://github.com/kubernetes/kops/pull/12187

**Comment by amitpd** [comment]
@olemarkus What is the process to merge these changes into an active release branch, say release-1.21

**Comment by amitpd** [comment]
> @olemarkus What is the process to merge these changes into an active release branch, say release-1.21

I raised below PR for merging to release-1.21. Hope I followed the right process
https://github.com/kubernetes/kops/pull/12190

**Comment by amitpd** [comment]
KOPS v1.21.1 is released today and this feature is working with this new release.
