### ISSUE TITLE
Unable to start metrics server

### ISSUE THREAD

**Issue by SadmiB** [kubernetes/kops#12113]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
$ kops version
Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)

```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13", GitCommit:"53c7b65d4531a749cd3a7004c5212d23daa044a9", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:11Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13", GitCommit:"53c7b65d4531a749cd3a7004c5212d23daa044a9", GitTreeState:"clean", BuildDate:"2021-07-15T20:53:19Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

```

**3. What cloud provider are you using?**
`AWS`
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I tried enabling metrics server in the cluster by adding this to the cluster:
```
spec:
  certManager:
    enabled: true
  metricsServer:
    enabled: true
    insecure: false
```
**5. What happened after the commands executed?**
Metrics server is unable to start properly:

```
Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    10m                    default-scheduler  Successfully assigned kube-system/metrics-server-65f64df9dd-pdq7g to ip-172-20-48-205.eu-west-1.compute.internal
  Warning  FailedMount  5m59s (x2 over 8m14s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[certs], unattached volumes=[metrics-server-token-jlvfd certs tmp-dir]: timed out waiting for the condition
  Warning  FailedMount  3m44s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[certs], unattached volumes=[tmp-dir metrics-server-token-jlvfd certs]: timed out waiting for the condition
  Warning  FailedMount  87s                    kubelet            Unable to attach or mount volumes: unmounted volumes=[certs], unattached volumes=[certs tmp-dir metrics-server-token-jlvfd]: timed out waiting for the condition
  Warning  FailedMount  1s (x13 over 10m)      kubelet            MountVolume.SetUp failed for volume "certs" : secret "metrics-server-tls" not found

```

**6. What did you expect to happen?**

Metrics up and running with `kubectl top nodes && kubectl top pods`

**Comment by olemarkus** [comment]
As it happens, I am working working on a fix for this right now.

**Comment by robinverduijn** [comment]
This is affecting us as well, when trying to update from kOps 1.20.1 to 1.20.2. Are there any plans to cherry-pick a backport to the 1.20 release?

**Comment by olemarkus** [comment]
There aren't any plans for another 1.20 release. There will be a 1.21 shortly, and then the focus will be on 1.22.

**Comment by object88** [comment]
I have just run into this today, upgrading to kops 1.20.3.  If there isn't a going to be another release (which is perfectly reasonable), then what is the workaround going ahead?  I don't plan on going to kops 1.21.X until we can smoothly upgrade to 1.20 across our clusters.

**Comment by johngmyers** [comment]
kOps 1.21 and 1.22 support running Kubernetes 1.19 and 1.20.

**Comment by object88** [comment]
No, it doesn't work with 1.21.4 either.  The problem seems to be that the cert-manager Issuer, `metrics-server.addons.k8s.io` does not exist:
```
$ kubectl --namespace kube-system get certificaterequests metrics-server-sstj8 --output yaml
apiVersion: cert-manager.io/v1
kind: CertificateRequest
metadata:
  annotations:
    cert-manager.io/certificate-name: metrics-server
    cert-manager.io/certificate-revision: "1"
    cert-manager.io/private-key-secret-name: metrics-server-scd4v
[SNIP]
  labels:
    addon.kops.k8s.io/name: metrics-server.addons.k8s.io
    addon.kops.k8s.io/version: 0.4.4
    app.kubernetes.io/managed-by: kops
    k8s-app: metrics-server
  name: metrics-server-sstj8
  namespace: kube-system
  ownerReferences:
  - apiVersion: cert-manager.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Certificate
    name: metrics-server
spec:
  duration: 2160h0m0s
  groups:
  - system:serviceaccounts
  - system:serviceaccounts:cert-manager
  - system:authenticated
  issuerRef:
    kind: Issuer
    name: metrics-server.addons.k8s.io
  request: [REDACTED]
  uid: 73dfaaa3-735b-4410-ade1-d3dfe2860705
  usages:
  - server auth
  username: system:serviceaccount:cert-manager:cert-manager
status:
  conditions:
  - lastTransitionTime: "2021-12-31T04:43:42Z"
    message: Certificate request has been approved by cert-manager.io
    reason: cert-manager.io
    status: "True"
    type: Approved
  - lastTransitionTime: "2021-12-31T04:43:42Z"
    message: 'Referenced "Issuer" not found: issuer.cert-manager.io "metrics-server.addons.k8s.io"
      not found'
    reason: Pending
    status: "False"
    type: Ready
```
No issuers...
```
$ kubectl get issuers --all-namespaces
No resources found
```
Only the cluster issuer...
```
$ kubectl get clusterissuers                 
NAME               READY   AGE
letsencrypt-prod   True    290d
```
... that we created for our independently installed cert-manager (from before upgrading kops)
```
$ helm --namespace cert-manager list 
NAME        	NAMESPACE   	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
cert-manager	cert-manager	32      	2021-12-19 12:44:40.454365208 +0000 UTC	deployed	cert-manager-v1.3.1	v1.3.1     
```
I can't find anything in the `kops` repo that refers to such an issuer; where is it expected to come from?

**Comment by olemarkus** [comment]
The issuer is created by channels. You need to have at least one new master node running for it to be installed. 
There are some paths where the cluster won't validate because metrics-server isn't starting, and the cluster won't validate at least one master node has been able to install the certificate.
I recommend running metrics-server with `insecure: true` until you have upgraded, then switch that flag off.

**Comment by object88** [comment]
Ah!  That explains why the last time that I did this, it worked; I had used the default `insecure: false` briefly, then switched to `insecure: true`.  I appreciate the clear path forward; thanks!
