### ISSUE TITLE
Advisory notification system/RSS feed

### ISSUE THREAD

**Issue by basilnsage** [kubernetes/kops#12110]
/kind feature

Hello,

Is there a way to receive notifications when new advisories are published? I did some cluster maintenance recently and ran into an issue that was covered by an advisory. Hooray that it was covered! But, during the post mortem, the idea of subscribing to future advisories surfaced. I didn't see such a mechanism in the kOps docs and wanted to check/request it here as a result.

Apologies if `/kind feature` is the wrong label.

Thanks much

**Comment by olemarkus** [comment]
These have been highlighted in the release notifications for a long, long time. Would it not be enough to watch releases?

**Comment by basilnsage** [comment]
Oh, yes, that will work. Thanks for pointing that out.
