### ISSUE TITLE
Addon updates for 1.22

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kops#12128]
We should bump at least the following addons before 1.22

- [x] AWS EBS CSI driver
- [x] snapshot controller
- [x] cluster autoscaler
- [x] cert-manager
- [ ] ~~AWS LB controller~~
- [x] metrics-server
- [x] cilium
- [x] node local dns cache
- [x] node termination handler
- [x] coredns
- [x] AWS cloud controller
- [ ] Digital Ocean cloud controller
- [ ] Openstack cloud controller

**Comment by hakman** [comment]
This should be updated to reflect current state. Also, I don't think Cilium should be on the list.
CoreDNS should be already at the recommended version for 1.22:
https://github.com/kubernetes/kops/pull/12062

**Comment by olemarkus** [comment]
It's just a copy/paste of the last one. Haven't ticked off anything yet.

**Comment by rifelpet** [comment]
we should make a best-effort pass at all of the external cloud controllers too

**Comment by olemarkus** [comment]
Agreed. Add those that we support to the list above.

**Comment by olemarkus** [comment]
Only the CCMs are really missing now according to the list above. There are other updates incoming, but I don't see them critical for 1.22.

**Comment by hakman** [comment]
Very nice. Thanks for the update @olemarkus.

**Comment by olemarkus** [comment]
Closing this one since I think we are good for 1.22 now.

/close
