### ISSUE TITLE
Flag --api-loadbalancer-type internal still creates a public loadbalancer on OpenStack

### ISSUE THREAD

**Issue by MartLTB** [kubernetes/kops#12179]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
OpenStack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster \
  --cloud openstack \
  --name my-testcluster.k8s.local \
  --state ${KOPS_STATE_STORE} \
  --zones 1a,1b,1c \
  --network-cidr 10.23.0.0/16 \
  --image "Ubuntu 21.04 (Hirsute Hippo)" \
  --master-count=3 \
  --node-count=3 \
  --node-size ECS.UC1.2-2 \
  --master-size ECS.UC1.2-2 \
  --etcd-storage-type My-Storage \
  --api-loadbalancer-type internal \
  --os-octavia=true \
  --topology private \
  --bastion \
  --ssh-public-key ~/.ssh/id_rsa.pub \
  --networking calico \
  --os-ext-net ext01 \
  -v 10

kops update cluster --name my-testcluster.k8s.local --yes --admin

**5. What happened after the commands executed?**
The loadbalancer for the api was created with an associated Floating IP which made it publicly accessible.
```
...
Will create resources:
  FloatingIP/fip-api.my-testcluster.k8s.local
  	LB                  	name:api.my-testcluster.k8s.local
  	ForAPIServer        	true
...
```

**6. What did you expect to happen?**
Due to the "--api-loadbalancer-type internal" flag I expected the loadbalancer to not get a Floating IP which would make it accessible only from within the cluster network.

**Comment by zetaab** [comment]
there is no thing called "internal" setup in kops openstack.

**Comment by MartLTB** [comment]
> there is no thing called "internal" setup in kops openstack.

This would of course explain it, if this is mentioned somewhere in the documentation I must have missed it. As the "--api-loadbalancer-type" option is explicitly set to "public" in the Openstack getting started tutorial I just assumed it is possible to set it to "internal".
