### ISSUE TITLE
Should we warn when using spot with e.g. t2 family?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#122]
The t2 family doesn't seem to support spot instances, but nothing in the API seems to stop us creating the requests - they just won't be fulfilled.  We should probably warn the user about this if they try to do it!

**Comment by chrislovecnm** [comment]
Can we even run on T2?

**Comment by justinsb** [comment]
Of course :-)  I believe it's still the default for our nodes

**Comment by chrislovecnm** [comment]
Lmao

**Comment by chrislovecnm** [comment]
Closing ... Issue open to remove support for instance that won't work
