### ISSUE TITLE
Support configuring aws-iam-authenticator using a file instead of a ConfigMap

### ISSUE THREAD

**Issue by akloss-cibo** [kubernetes/kops#12205]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

As documented [here](https://github.com/kubernetes/kops/blob/master/docs/authentication.md#creating-a-new-cluster-with-iam-authenticator-on), a new cluster cannot be bootstrapped with a working aws-iam-authenticator configuration.  This creates a challenge for automation which would like to boot a cluster with a working authentication system out-of-the-box.  

**2. Feel free to provide a design supporting your feature request.**

Adding configuration to the `authentication.aws` section of the cluster spec which allows reading the aws-iam-authenticator configuration from a file on the control plane nodes would greatly simplify rolling out new clusters.  The configuration file can be injected using the existing `fileAssets` support.

**Comment by rifelpet** [comment]
The above PR has been merged and will be in kOps 1.23
/close
