### ISSUE TITLE
get instances is inconsistent with --help

### ISSUE THREAD

**Issue by yurrriq** [kubernetes/kops#12200]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

> Version 1.21.0 (git-1.21.0)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: v1.21.2
Server Version: v1.21.3
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```bash
kops get instances -o yaml
```

**5. What happened after the commands executed?**

```
Using cluster from kubectl context: my-cluster.example.com


unsupported output format: "yaml"
```

**6. What did you expect to happen?**

YAML output.

**7. Please provide your cluster manifest.**

Not relevant.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

```
λ kops get instances --help
Display cluster instances.

Usage:
  kops get instances [flags]

Examples:
  # Display all instances.
  kops get instances

Flags:
  -h, --help   help for instances

Global Flags:
...
  -o, --output string                    output format.  One of: table, yaml, json (default "table")
...
```

**Comment by yurrriq** [comment]
`-o json` fails similarly

**Comment by olemarkus** [comment]
Thanks for reporting. I'll look into fixing the documentation.

**Comment by johngmyers** [comment]
It wouldn't be that hard to add support for YAML/JSON.

**Comment by hierynomus** [comment]
@yurrriq The PR I've submitted has been merge to master. The issue can be closed I think.
