### ISSUE TITLE
ListHostedZones hangs and then fails with go1.8

### ISSUE THREAD

**Issue by mastercactapus** [kubernetes/kops#1221]
This is actually a bug with the vendor-ed version of `github.com/aws/aws-sdk-go`
See here: https://github.com/aws/aws-sdk-go/issues/984

When master is compiled with go 1.8beta2 and running `update cluster`, the following error is returned after a long hang:

```
error listing DNS zones: RequestError: send request failed
caused by: Get https://route53.amazonaws.com/2013-04-01/hostedzone: EOF
```

Updating the sdk (and rebuilding) resolved the issue for me locally.

**Comment by justinsb** [comment]
Are you from the future? :-)

We'll bump the aws-sdk-go!
