### ISSUE TITLE
kops create secret fails with "Cannot specify cluster via --name and positional argument"

### ISSUE THREAD

**Issue by rlmcpherson** [kubernetes/kops#1222]
Running 

`kops create secret --name=<cluster-name> sshpublickey admin -i <path-to-key>` fails with 
`Cannot specify cluster via --name and positional argument`

This use case is instead of using `--ssh-public-key` with `kops update` as recommended by the `kops update` command help, since that flag is deprecated.

**Comment by rlmcpherson** [comment]
The issue seems to be in `cmd/kops/root.go` where secret is being parsed as a cluster name.

**Comment by kris-nova** [comment]
The preferred syntax here should be

```
kops create secret sshpublickey admin -i <path-to-key> --name=<cluster-name>
```

or better yet, kops will assume name at the end

```
kops create secret sshpublickey admin -i <path-to-key> <cluster-name>
```

I think that error message could use some work, so I opened https://github.com/kubernetes/kops/pull/1255 in the hopes of preventing this in the future.

**Comment by justinsb** [comment]
Should be fixed in #1236

**Comment by rlmcpherson** [comment]
Confirming #1236 fixes the issue for me.

**Comment by chrislovecnm** [comment]
Closing
