### ISSUE TITLE
kops-controller 1.21.1 frequent pod SuccessfulCreate and SuccessfulDelete Events.

### ISSUE THREAD

**Issue by prudhvigodithi** [kubernetes/kops#12225]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
 1.21.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.21.4
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:21Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops  update cluster --lifecycle-overrides InternetGateway=Ignore,IAMRole=ExistsAndWarnIfChanges,IAMRolePolicy=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges --yes

**5. What happened after the commands executed?**
Once the command is executed kops-controller pod gets terminated and starts again, and gets the following error
`I0830 20:43:51.296712       1 deleg.go:130] controller-runtime/metrics "msg"="metrics server is starting to listen"  "addr"=":0"
I0830 20:43:51.301348       1 deleg.go:130] setup "msg"="starting manager"  
I0830 20:43:51.301530       1 leaderelection.go:243] attempting to acquire leader lease kube-system/kops-controller-leader...
I0830 20:43:51.302007       1 internal.go:393] controller-runtime/manager "msg"="starting metrics server"  "path"="/metrics"
E0830 20:44:08.718499       1 event.go:329] Could not construct reference to: '&v1.Lease{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kops-controller-leader", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"15c5dadd-e29c-47d3-9b2c-89f250fd7960", ResourceVersion:"21097", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63765946237, loc:(*time.Location)(0x45ea8c0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"kops-controller", Operation:"Update", APIVersion:"coordination.k8s.io/v1", Time:(*v1.Time)(0xc0006ae978), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc0006ae990)}}}, Spec:v1.LeaseSpec{HolderIdentity:(*string)(nil), LeaseDurationSeconds:(*int32)(nil), AcquireTime:(*v1.MicroTime)(nil), RenewTime:(*v1.MicroTime)(nil), LeaseTransitions:(*int32)(nil)}}' due to: 'no kind is registered for the type v1.Lease in scheme "cmd/kops-controller/main.go:48"'. Will not report event: 'Normal' 'LeaderElection' 'ip-10-35-6-164.ec2.internal_f6251051-4b0b-4c72-82be-dfb5f16f7ad8 became leader'
I0830 20:44:08.718569       1 leaderelection.go:253] successfully acquired lease kube-system/kops-controller-leader
I0830 20:44:08.720357       1 recorder.go:104] controller-runtime/manager/events "msg"="Normal"  "message"="ip-10-35-6-164.ec2.internal_f6251051-4b0b-4c72-82be-dfb5f16f7ad8 became leader" "object"={"kind":"ConfigMap","namespace":"kube-system","name":"kops-controller-leader","uid":"22fdb9d2-e000-49d0-ab84-1d61f9b6c9bd","apiVersion":"v1","resourceVersion":"21096"} "reason"="LeaderElection"
I0830 20:44:08.721269       1 controller.go:165] controller-runtime/manager/controller/node "msg"="Starting EventSource" "reconciler group"="" "reconciler kind"="Node" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"daemonEndpoints":{"kubeletEndpoint":{"Port":0}},"nodeInfo":{"machineID":"","systemUUID":"","bootID":"","kernelVersion":"","osImage":"","containerRuntimeVersion":"","kubeletVersion":"","kubeProxyVersion":"","operatingSystem":"","architecture":""}}}}
I0830 20:44:08.721302       1 controller.go:173] controller-runtime/manager/controller/node "msg"="Starting Controller" "reconciler group"="" "reconciler kind"="Node" 
I0830 20:44:08.724016       1 reflector.go:219] Starting reflector *v1.Node (9h7m52.586538365s) from pkg/cache/internal/informers_map.go:241
I0830 20:44:08.822506       1 controller.go:207] controller-runtime/manager/controller/node "msg"="Starting workers" "reconciler group"="" "reconciler kind"="Node" "worker count"=1
I0830 20:44:09.104747       1 node_controller.go:142] sending patch for node "ip-10-35-6-164.ec2.internal": "{\"metadata\":{\"labels\":{\"kops.k8s.io/kops-controller-pki\":\"defVal\",\"node-role.kubernetes.io/control-plane\":\"defVal\",\"node-role.kubernetes.io/master\":\"defVal\",\"node.kubernetes.io/exclude-from-external-load-balancers\":\"defVal\"}}}"
I0830 20:44:09.160492       1 reflector.go:225] Stopping reflector *v1.Node (9h7m52.586538365s) from pkg/cache/internal/informers_map.go:241
I0830 20:44:09.160563       1 controller.go:227] controller-runtime/manager/controller/node "msg"="Shutdown signal received, waiting for all workers to finish" "reconciler group"="" "reconciler kind"="Node" 
I0830 20:44:09.165767       1 controller.go:229] controller-runtime/manager/controller/node "msg"="All workers finished" "reconciler group"="" "reconciler kind"="Node" 
rpc error: code = NotFound desc = an error occurred when try to find container "5986612569c9ad10e20f141b9b6535b78e617f5aafe1e70339879e97f140a1e6": not found`

**6. What did you expect to happen?**
Initially, the first time when the cluster is created kops-controller pods continues to run fine without any termination or immediate SuccessfulDelete and SuccessfulCreate events.

**7. Anything else do we need to know?**
I have tested this with both single and multiple masters.
with the single master I see initially the kops-controller pods run fine, but when we update the cluster for example making a change of an AMI and run kops cluster update command, the cluster comes up fine but kops controller pods keep on restarting 
```  Type    Reason            Age                  From                  Message
  ----    ------            ----                 ----                  -------
  Normal  SuccessfulCreate  23m                  daemonset-controller  Created pod: kops-controller-mc9lp
  Normal  SuccessfulCreate  23m                  daemonset-controller  Created pod: kops-controller-mlfxd
  Normal  SuccessfulCreate  23m                  daemonset-controller  Created pod: kops-controller-k4rvj
  Normal  SuccessfulCreate  10m                  daemonset-controller  Created pod: kops-controller-hwz9x
  Normal  SuccessfulCreate  9m38s                daemonset-controller  Created pod: kops-controller-b4jr2
  Normal  SuccessfulDelete  9m32s                daemonset-controller  Deleted pod: kops-controller-b4jr2
  Normal  SuccessfulCreate  9m4s                 daemonset-controller  Created pod: kops-controller-vw9m9
  Normal  SuccessfulDelete  9m4s                 daemonset-controller  Deleted pod: kops-controller-vw9m9
  Normal  SuccessfulCreate  8m38s                daemonset-controller  Created pod: kops-controller-gt9tr
  Normal  SuccessfulDelete  8m37s                daemonset-controller  Deleted pod: kops-controller-gt9tr
  Normal  SuccessfulCreate  8m4s                 daemonset-controller  Created pod: kops-controller-n7hqj
  Normal  SuccessfulDelete  8m3s                 daemonset-controller  Deleted pod: kops-controller-n7hqj
  Normal  SuccessfulCreate  7m37s                daemonset-controller  Created pod: kops-controller-hzszx
  Normal  SuccessfulDelete  7m37s                daemonset-controller  Deleted pod: kops-controller-hzszx
  Normal  SuccessfulCreate  7m3s                 daemonset-controller  Created pod: kops-controller-wpnbg
  Normal  SuccessfulDelete  7m3s                 daemonset-controller  Deleted pod: kops-controller-wpnbg
  Normal  SuccessfulCreate  6m37s                daemonset-controller  Created pod: kops-controller-cchpv
  Normal  SuccessfulDelete  6m37s                daemonset-controller  Deleted pod: kops-controller-cchpv
  Normal  SuccessfulCreate  6m3s                 daemonset-controller  Created pod: kops-controller-mw6ml
  Normal  SuccessfulDelete  6m3s                 daemonset-controller  Deleted pod: kops-controller-mw6ml
  Normal  SuccessfulDelete  5m36s                daemonset-controller  Deleted pod: kops-controller-wqrzb
  Normal  SuccessfulDelete  4m2s (x3 over 5m3s)  daemonset-controller  (combined from similar events): Deleted pod: kops-controller-fnnll
  ```

With 3 masters initially, it runs fine, out 3 kops-controller pods one is active and I can see the controller.go logs, even after kops cluster upgrade with an AMI change, same behavior but this time out of 3, one pod always keeps on running and other 2 kops-controller pods keeps coming up and terminating.

I see the https://github.com/kubernetes/kops/pull/10871
Is this the expected behavior for the kops-controller or is there something we are missing with the upgrade? Also the cluster works perfectly fine with no issues its just the controller pod behaves this way.

Cluster Spec:
```apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-08-30T20:49:57Z"
  generation: 1
  name: test10.k8s.local
spec:
  additionalNetworkCIDRs:
  - 10.38.24.0/22
  api:
    loadBalancer:
      class: Network
      type: Internal
  assets:
    containerProxy: testdocker.com
  authorization:
    rbac: {}
  channel: https://nexus.com/repository/kops-channels/stable
  cloudLabels:
    ClusterName: test10.k8s.local
    Department: test
    NonStop: "True"
    Platform: test
  cloudProvider: aws
  configBase: s3://developer-s3-bucket/kops-1.21.1/test10.k8s.local
  containerRuntime: containerd
  containerd:
    packages:
      hashAmd64: ff97dbd16a1345e532fff3829f813fe24df69e3d
      urlAmd64: https://nexus.com/repository/kops-hosted/containerd/v1.4.4/cri-containerd-cni-1.4.4-linux-amd64.tar.gz
    registryMirrors:
      '*':
      - https://testdocker.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-1
      name: a-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1b-1
      name: b-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-2
      name: a-2
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-1
      name: a-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1b-1
      name: b-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-2
      name: a-2
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeControllerManager:
    clusterCIDR: 172.22.128.0/17
  kubeProxy:
    clusterCIDR: 172.22.128.0/17
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: https://nexus.com/repository/kubernetes-releases/release/v1.21.4
  masterPublicName: api.test10.k8s.local
  networkCIDR: 10.35.3.0/24
  networkID: vpc-0716
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 172.28.0.0/16
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: testkey
  subnets:
  - cidr: 10.35.6.0/25
    id: subnet-02dc9
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.38.6.128/25
    id: subnet-02cc8
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.38.24.0/24
    id: subnet-03707
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.38.24.0/24
    id: subnet-03707
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 10.38.6.0/25
    id: subnet-02dc9
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```

**Comment by AnubhavSabharwa** [comment]
@prudhvigodithi  Did you manually updated kops-controller addon yaml?
By default it picks up 1.21.0 yaml file (K8s16.yaml)

**Comment by prudhvigodithi** [comment]
Hey, just wanted to follow up on this, I have seen another issue happening because of this kops controller getting recreated every-time upon kops update cluster command
`NAME                          STATUS   ROLES                              AGE   VERSION
ip-10-38-4-13.ec2.internal    Ready    control-plane,master               16m   v1.21.4
ip-10-38-4-137.ec2.internal   Ready    node                               10m   v1.21.4
ip-10-38-4-215.ec2.internal   Ready    control-plane,master,spot-worker   29m   v1.21.4
ip-10-38-4-243.ec2.internal   Ready    <none>                             12m   v1.21.4
ip-10-38-4-64.ec2.internal    Ready    control-plane,master,spot-worker   22m   v1.21.4
ip-10-38-4-98.ec2.internal    Ready    node                               16m   v1.21.4`

when kubectl get nodes, above output is observed, since the kops-controller is down for that time, the role node was not assigned to the node ip-10-38-4-243.ec2.internal, after few mins the kops controller started then added the label and then go terminated again, this gap in adding the label node is making few pods especially deamon sets to not to start on the node and other pods that have no restrictions are being started, this is causing few security steps to skip and start the pod as deamon sets are skipped initially because of kops controller not assigning the node labels. 

```
kubectl get ds -n kube-system 
NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                                      AGE
kops-controller             0         0         0       0            0           kops.k8s.io/kops-controller-pki=,node-role.kubernetes.io/master= 
```
When ran describe kops-controller daemon set 
`Name:           kops-controller
Selector:       k8s-app=kops-controller
Node-Selector:  kops.k8s.io/kops-controller-pki=,node-role.kubernetes.io/master=
Labels:         addon.kops.k8s.io/name=kops-controller.addons.k8s.io
                addon.kops.k8s.io/version=1.21.1
                app.kubernetes.io/managed-by=kops
                k8s-addon=kops-controller.addons.k8s.io
                k8s-app=kops-controller
                version=v1.21.1
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 1
Current Number of Nodes Scheduled: 1
Number of Nodes Scheduled with Up-to-date Pods: 1
Number of Nodes Scheduled with Available Pods: 1
Number of Nodes Misscheduled: 0
Pods Status:  1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           k8s-addon=kops-controller.addons.k8s.io
                    k8s-app=kops-controller
                    version=v1.21.1
  Annotations:      dns.alpha.kubernetes.io/internal: kops-controller.internal.infratest.k8s.local
  Service Account:  kops-controller
  Containers:
   kops-controller:
    Image:      test.com/kops/kops-controller:1.21.1
    Port:       <none>
    Host Port:  <none>
    Command:
      /kops-controller
      --v=2
      --conf=/etc/kubernetes/kops-controller/config/config.yaml
    Requests:
      cpu:     50m
      memory:  50Mi
    Environment:
      KUBERNETES_SERVICE_HOST:  127.0.0.1
    Mounts:
      /etc/kubernetes/kops-controller/config/ from kops-controller-config (rw)
      /etc/kubernetes/kops-controller/pki/ from kops-controller-pki (rw)
  Volumes:
   kops-controller-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kops-controller
    Optional:  false
   kops-controller-pki:
    Type:               HostPath (bare host directory volume)
    Path:               /etc/kubernetes/kops-controller/
    HostPathType:       Directory
  Priority Class Name:  system-node-critical
Events:
  Type    Reason            Age                   From                  Message
  ----    ------            ----                  ----                  -------
  Normal  SuccessfulCreate  53m                   daemonset-controller  Created pod: kops-controller-wj598
  Normal  SuccessfulDelete  53m                   daemonset-controller  Deleted pod: kops-controller-wj598
  Normal  SuccessfulCreate  52m                   daemonset-controller  Created pod: kops-controller-7n7bt
  Normal  SuccessfulDelete  52m                   daemonset-controller  Deleted pod: kops-controller-7n7bt
  Normal  SuccessfulCreate  51m                   daemonset-controller  Created pod: kops-controller-qhqfk
  Normal  SuccessfulDelete  51m                   daemonset-controller  Deleted pod: kops-controller-qhqfk
  Normal  SuccessfulCreate  50m                   daemonset-controller  Created pod: kops-controller-9mwtf
  Normal  SuccessfulDelete  50m                   daemonset-controller  Deleted pod: kops-controller-9mwtf
  Normal  SuccessfulCreate  49m                   daemonset-controller  Created pod: kops-controller-689xf
  Normal  SuccessfulDelete  49m                   daemonset-controller  Deleted pod: kops-controller-689xf
  Normal  SuccessfulCreate  48m                   daemonset-controller  Created pod: kops-controller-7cpsr
  Normal  SuccessfulDelete  48m                   daemonset-controller  Deleted pod: kops-controller-7cpsr
  Normal  SuccessfulCreate  47m                   daemonset-controller  Created pod: kops-controller-b2z7s
  Normal  SuccessfulDelete  47m                   daemonset-controller  Deleted pod: kops-controller-b2z7s
  Normal  SuccessfulCreate  46m                   daemonset-controller  Created pod: kops-controller-8fdl5
  Normal  SuccessfulDelete  46m                   daemonset-controller  Deleted pod: kops-controller-8fdl5
  Normal  SuccessfulCreate  44m                   daemonset-controller  Created pod: kops-controller-z4dtz
  Normal  SuccessfulDelete  44m                   daemonset-controller  Deleted pod: kops-controller-z4dtz
  Normal  SuccessfulCreate  44m                   daemonset-controller  Created pod: kops-controller-s84ck
  Normal  SuccessfulCreate  44m                   daemonset-controller  Created pod: kops-controller-bmg5z
  Normal  SuccessfulDelete  43m                   daemonset-controller  Deleted pod: kops-controller-bmg5z
  Normal  SuccessfulDelete  43m                   daemonset-controller  Deleted pod: kops-controller-s84ck
  Normal  SuccessfulCreate  43m                   daemonset-controller  Created pod: kops-controller-5s6hj
  Normal  SuccessfulCreate  43m                   daemonset-controller  Created pod: kops-controller-j68vx
  Normal  SuccessfulDelete  42m                   daemonset-controller  Deleted pod: kops-controller-5s6hj
  Normal  SuccessfulDelete  42m                   daemonset-controller  Deleted pod: kops-controller-j68vx
  Normal  SuccessfulCreate  42m                   daemonset-controller  Created pod: kops-controller-v528m
  Normal  SuccessfulCreate  42m                   daemonset-controller  Created pod: kops-controller-56vxq
  Normal  SuccessfulDelete  41m                   daemonset-controller  Deleted pod: kops-controller-v528m
  Normal  SuccessfulDelete  41m                   daemonset-controller  Deleted pod: kops-controller-56vxq
  Normal  SuccessfulCreate  41m                   daemonset-controller  Created pod: kops-controller-v9wsr
  Normal  SuccessfulCreate  41m                   daemonset-controller  Created pod: kops-controller-5znm7
  Normal  SuccessfulDelete  40m                   daemonset-controller  Deleted pod: kops-controller-5znm7
  Normal  SuccessfulDelete  40m                   daemonset-controller  Deleted pod: kops-controller-v9wsr
  Normal  SuccessfulDelete  19m (x62 over 39m)    daemonset-controller  (combined from similar events): Deleted pod: kops-controller-rc9kw
  Normal  SuccessfulCreate  4m8s (x109 over 40m)  daemonset-controller  (combined from similar events): Created pod: kops-controller-2pn6t `

**Comment by olemarkus** [comment]
Sorry for taking some time to respond on this one. Do you see this problem on 1.22 too?
I am not sure what causes the recreate events, but I suspect it is the master nodes deploying different versions of the kops-controller continuously. 

/remove-lifecycle rotten
