### ISSUE TITLE
NTP not installed

### ISSUE THREAD

**Issue by xpepermint** [kubernetes/kops#12241]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.21.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I created a fresh cluster, later upgraded to `m3.medium` instances, and that's all. No special configuration or smth.

**5. What happened after the commands executed?**

I saw that some services report clock not being synced so I went and check if NTP works on nodes/master and found out that NTP service is not installed.

**6. What did you expect to happen?**

After reading the docs, I would assume the NTP service should be installed and configured on each server.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

The default. No changes were made.

**Comment by hakman** [comment]
Please check if `systemd-timesyncd` is installed and running. If you use the default image, this is ubuntu and it is installed instead of NTP.

**Comment by xpepermint** [comment]
Thanks for the info @hakman . Yes, I see `Active: active (running)`.
