### ISSUE TITLE
VolumeSnapshotClass support

### ISSUE THREAD

**Issue by xpepermint** [kubernetes/kops#12261]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I read that kops 1.22 will have `ebs.csi.aws.com` enabled by default. Does that mean that `VolumeSnapshotClass` and related resources will be enabled by default as well? It's not clear what's the preferred way of adding this support to k8s today.

**2. Feel free to provide a design supporting your feature request.**

https://kubernetes.io/docs/concepts/storage/volume-snapshots/

**Comment by olemarkus** [comment]
snapshotcontroller is a standalone plugin. See https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#SnapshotControllerConfig

**Comment by xpepermint** [comment]
Thank you @olemarkus . I didn't see that plugin before. Thank you.

https://kops.sigs.k8s.io/addons/#snapshot-controller
