### ISSUE TITLE
k8s-app labels

### ISSUE THREAD

**Issue by brancz** [kubernetes/kops#1226]
kubernetes/kubernetes upstream manifests suggest the use of `k8s-app=<component-name>` labelling for all kubernetes components, that way they are easily distinguishable when listing/querying/discovering. I noticed [`kube-dns`](https://github.com/kubernetes/kops/blob/8470034dc56362b04fed7ac6e0ea3d9980f6c06f/upup/models/nodeup/_kubernetes_master/kube-dns/files/etc/kubernetes/addons/dns/kubedns-rc.yaml.template#L22-L25) has them, but the [`apiserver`](https://github.com/kubernetes/kops/blob/8470034dc56362b04fed7ac6e0ea3d9980f6c06f/upup/models/nodeup/_kubernetes_master/kube-apiserver/files/etc/kubernetes/manifests/kube-apiserver.manifest.template), [`kube-scheduler`](https://github.com/kubernetes/kops/blob/8470034dc56362b04fed7ac6e0ea3d9980f6c06f/upup/models/nodeup/_kubernetes_master/kube-scheduler/files/etc/kubernetes/manifests/kube-scheduler.template) and [`kube-controller-manager`](https://github.com/kubernetes/kops/blob/8470034dc56362b04fed7ac6e0ea3d9980f6c06f/upup/models/nodeup/_kubernetes_master/kube-controller-manager/files/etc/kubernetes/manifests/kube-controller-manager.template) don't yet.

I would like to open a PR to fix this, but I have a few questions beforehand.

* Are those the correct places to add the labels? (I am unfamiliar with kops code base and those seemed like they were the templates the objects end up being created with, so if those are the incorrect ones, please point me to the correct place)
* Do I entirely replace the manifests with the upstream manifests or do I only add the labels?

**Comment by justinsb** [comment]
Hi - nice find.

So, we try to be as close as possible to the "official" configuration.  AFAIK that is https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest

I don't see a k8s-app label in there.  That said, it seems like we probably should have one.  My only concern is that we call it `apiserver` and then k8s decides to call it `kube-apiserver` or something

In general, it's not practical to just bulk-copy the templated manifests, but we try to make the same changes.  If you notice any changes that "upstream" makes that we don't, please do open an issue or PR :-)

**Comment by brancz** [comment]
I'm not super opinionated about which labelling to use. It seems that upstream templates actually use `component=<component-name>` as you mentioned. I don't have a problem with calling it `kube-apiserver` as long as it is unique, correct and consistent across the components 🙂 

It seems that at least in the salt templates the `component` key is consistently used for [kube-scheduler](https://github.com/kubernetes/kubernetes/blob/ad47a181ee3e1cc9fb17fc828888b3418ec6edba/cluster/saltbase/salt/kube-scheduler/kube-scheduler.manifest) and [kube-controller-manager](https://github.com/kubernetes/kubernetes/blob/ad47a181ee3e1cc9fb17fc828888b3418ec6edba/cluster/saltbase/salt/kube-controller-manager/kube-controller-manager.manifest).

Unfortunately [kube-dns](https://github.com/kubernetes/kubernetes/blob/ad47a181ee3e1cc9fb17fc828888b3418ec6edba/cluster/addons/dns/kubedns-controller.yaml.base) falls out of line here, which is what I basing my argument around 🙂 . I say we should be consistent with the labelling and either carry a patch for the `kube-dns` template to change `k8s-app` to `component` or add `k8s-app` to the components that don't have any of the two yet. What is your preferred way @justinsb ?

**Comment by brancz** [comment]
Thanks @dmcnaught for taking care of this! 🎉
