### ISSUE TITLE
Inconsistent output of `kops get clusters -o json`

### ISSUE THREAD

**Issue by Szymongib** [kubernetes/kops#12293]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.20.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

N/A

**3. What cloud provider are you using?**

N/A

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Run `kops get clusters -o json` on a state bucket with one cluster and on bucket with multiple clusters. 

**5. What happened after the commands executed?**

- If there is single cluster state in bucket the printed JSON is an object:
```json
{
  "kind":"Cluster",
  "apiVersion":"kops.k8s.io/v1alpha2",
  ...
}
```
- If there are multiple clusters the output is an array:
```json
[
  {
    "kind":"Cluster",
    "apiVersion":"kops.k8s.io/v1alpha2",
    ...
  },
  {
    "kind":"Cluster",
    "apiVersion":"kops.k8s.io/v1alpha2",
    ...
  }
]
``` 

**6. What did you expect to happen?**

When running the command with a bucket with a single cluster I have expected to get a JSON array with one object:
```json
[
  {
    "kind":"Cluster",
    "apiVersion":"kops.k8s.io/v1alpha2",
    ...
  }
]
```

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

Not sure if that is expected behavior or if by that point it is breaking change but such behavior makes it hard to work with automated workflows.

**Comment by Szymongib** [comment]
Thanks for taking a look.

I do not think kubectl works this way. When you are listing objects, for example, `kubectl get pods -ojson` it will return a single `List` object with an array of `items` regardless if there is one Pod or multiple.

It does return one object if you run `kubectl get po my-pod -ojson` which in my mind would be equivalent of `kops get clusters --name my-cluster -ojosn` which also returns one cluster and I think is completely fine (because I expect to get only one cluster).

**Comment by olemarkus** [comment]
This is indeed considered a bug. The intention should be similar to `kubectl get pod`
/assign @justinsb

**Comment by hierynomus** [comment]
@olemarkus For implementing this, `kubectl` uses a `v1.List` object which has an `Items` field containing the listed items (for both json and yaml output). So contrary to what kops now does it doesn't return a plain array. Is it the intention to mimic this behaviour?
And should that behaviour be consistent across all other `kops get <X>` calls?
