### ISSUE TITLE
dnscontroller needs better docs

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1230]
We need to document if this is correct:

- route53-kubernetes creates a CNAME for Service of type=LoadBalancer to point to the auto-generated hostname of the ELB.
- dns-controller creates multiple A records, one for each node on which the given Service has a Pod running, which is useful for a Service of type=NodePort.

**Comment by deitch** [comment]
I found myself struggling for some time to understand (and still do not fully):

* how k8s knows that `type=LoadBalancer` means AWS ELB, and what to do, how it is configured
* how I can get a useful name (eventually figured out it means "ExternalIP", which really is just the generated hostname)
* what the best path is - or at least my options are - for exposing ports
* how I would set up a classic AWS VPC private/public structure with nodes controlled by k8s. E.g. I might want all k8s worker nodes in private subnet, but the ELB should be in the public. It is not at all clear how k8s does all of this (and how kops plays into it)

I know, I know... we need to remain focused. But the "coming from the outside in" use of k8s and much around it left me hanging in a lot of places.

More than happy to help here however possible.

**Comment by yissachar** [comment]
@deitch 
>how k8s knows that type=LoadBalancer means AWS ELB, and what to do, how it is configured

From the [AWS cloud provider](https://github.com/kubernetes/kubernetes/tree/ae1a7784af95f13218a94068ae451f19897562ed/pkg/cloudprovider/providers/aws)

**Comment by deitch** [comment]
Yep but go find in the docs what it is, how it works or interacts with your AWS account, what the options are and how to configure it.

**Comment by yissachar** [comment]
Linking https://github.com/kubernetes/kops/issues/972 which dupes this.

**Comment by chrislovecnm** [comment]
Hey all.  I opened an issue to document how to diagnosis problem such as these, please comment on #3888
