### ISSUE TITLE
Support for AWS m6i instances

### ISSUE THREAD

**Issue by antoinedeschenes** [kubernetes/kops#12323]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
New m6i instances were announced https://aws.amazon.com/ec2/instance-types/m6i/
kops currently states it's an invalid instance type
https://aws.amazon.com/ec2/instance-types/m6i/

**2. Feel free to provide a design supporting your feature request.**

**Comment by olemarkus** [comment]
Which kops version and which region did you try?
Latest kops should work in regions that support those instances

**Comment by jaredstehler** [comment]
i was able to successfully deploy instance groups for m6i with kops 1.21.1 on 13 Sep 21.

**Comment by olemarkus** [comment]
Good to know

/close
