### ISSUE TITLE
Should we prevent creation of a bastion when running topology=public

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1233]
And do we?  Test coverage needed also :-)

**Comment by chrislovecnm** [comment]
More information please, don't quite get what you are meaning.

**Comment by justinsb** [comment]
Oops... I think I meant "should we prevent creation of a bastion when running with topology=public"...

I'm not actually sure we should anyway.  Because - for example - what happens if you have bastions, but then you convert your cluster to be topology=public.

Closing.
