### ISSUE TITLE
Question: Is it possible to scale down the kube masters/nodes to 0 and still retain the kubernetes data?

### ISSUE THREAD

**Issue by noahjd** [kubernetes/kops#12338]
I would like to know if I can safely scale down the k8s masters/nodes to 0 and still retain the data stored in etcd when I scale things back up. The reason I ask is we have a performance testing cluster that we only need during certain periods of perf testing, and would like to spin down the infrastructure as needed when we do not need it. Thank you!

**Comment by olemarkus** [comment]
Yeah. That should be fairly safe. I've done this to my own clusters and not had any particular problems with it.
