### ISSUE TITLE
"kops delete cluster" does not work without the AmazonSQSReadOnlyAccess and AmazonEventBridgeReadOnlyAccess permissions of the kops IAM user or group

### ISSUE THREAD

**Issue by victor-sudakov** [kubernetes/kops#12332]
/kind bug

kops Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)

Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

Cloud provider: AWS

`kops delete cluster --name=yyy.my.domain.net --yes` produced the following error instead of deleting the cluster: "error listing SQS queues: AccessDenied: Access to the resource https://sqs.us-east-2.amazonaws.com/ is denied." and later a similar error about EventBridge listing access denied.

Adding the  AmazonSQSReadOnlyAccess and AmazonEventBridgeReadOnlyAccess  permissions to the kops IAM group fixed the issue and the cluster was eventually deleted, but it is not documented in https://kops.sigs.k8s.io/getting_started/aws/ that these permissions are required.

**Comment by victor-sudakov** [comment]
Here is the recent screenshot from the docs
![image](https://user-images.githubusercontent.com/12457866/133567103-97c0db7d-81bb-4aea-a4a9-abfd0db7409f.png)

**Comment by victor-sudakov** [comment]
The documentation at https://kops.sigs.k8s.io/getting_started/aws/ still remains half-updated. It requires just adding 2 lines to the docs to fix the issue.

/remove-lifecycle stale

**Comment by victor-sudakov** [comment]
Thank you!

**Comment by taufiqpsumarna** [comment]
Thank You, I Hope This Image Useful 

![image](https://user-images.githubusercontent.com/35789663/166916244-b7e17364-f9e1-4dab-9a42-3de77b8058ec.png)

**Comment by Tejeswarreddy-3i** [comment]
Cloud provider: AWS

kops delete cluster --name ${NAME} --yes
Error: error listing SQS queues: AccessDenied: Access to the resource https://sqs.ap-southeast-1.amazonaws.com/ is denied.
	status code: 403, request id: eaa5402b-097e-52f6-8803-1c2153c63d70
$ kops delete cluster --name=**********.com --state=s3://k8s.********.local --yes
Error: error listing SQS queues: AccessDenied: Access to the resource https://sqs.ap-southeast-1.amazonaws.com/ is denied.
	status code: 403, request id: cc47d2b1-b0f2-5702-ab7d-8eb65bd6afe1

Even after adding the AmazonSQSFullAccess and AmazonEventBridgeFullAccess permissions to the kops IAM group unable to fix the issue and the cluster is not getting deleted.
![Screenshot from 2022-12-08 11-57-06](https://user-images.githubusercontent.com/109336274/206374056-2da2abc1-1737-4c95-9eba-ecd4c9de993f.png)

**Comment by olemarkus** [comment]
@Tejeswarreddy-3i could you please create a new issue?

**Comment by Tejeswarreddy-3i** [comment]
okay
