### ISSUE TITLE
How to get VPC ID from Kops

### ISSUE THREAD

**Issue by alexw23** [kubernetes/kops#1234]
I'm having an issue with Kubernetes Core ELB (https://github.com/kubernetes/kubernetes/issues/36845#issuecomment-268467241) so I need to bring up my own ELB and route it using NodePort.

I wanted to run my own scripts to create and assign this ELB to the ASGs as a target group.

Is it possible to get the VPC ID of a cluster from Kops CLI?

**Comment by chrislovecnm** [comment]
No it is not, good idea though!

**Comment by yissachar** [comment]
You can get the cluster details and parse it with a tool such as jq:

`kops get cluster --name=<name> --state=<state> -ojson | jq '.spec.networkID`

@chrislovecnm If we add jsonpath output support we could do this without relying on third-party tools.

**Comment by chrislovecnm** [comment]
@yissachar nice ... thanks.  I Love to be wrong.  I am filing an issue for jsonpath support!

**Comment by kris-nova** [comment]
We have been talking about a way to get a manifest of resources/ID's out of kops.. for a few reasons..

This has my personal attention - and will probably drive this once the HTTP server is out..

More information on the larger issue https://github.com/kubernetes/kops/issues/1077
