### ISSUE TITLE
Stopping `rolling-update --interactive` leaves nodes tainted with kops.k8s.io/scheduled-for-update

### ISSUE THREAD

**Issue by vitaliyf** [kubernetes/kops#12383]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.20.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.20.11

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

- Make some changes to an instance-group and `kops update`
- Run `kops rolling-update cluster --yes --interactive`
- After one node is updated, answer (N)o to "Continue?" prompt

**5. What happened after the commands executed?**

When rolling-update starts all nodes are tainted with `kops.k8s.io/scheduled-for-update=undefined:PreferNoSchedule`. If rolling update is cancelled this taint is left behind on all nodes that were not yet upgraded.

**6. What did you expect to happen?**

Taint should be removed when kops exits without an error. My use case was to do a partial cluster upgrade to allow some A/B testing, so I used --interactive and purposely stopped the rolling process after 1st node. It was a surprise to find the taint on all remaining nodes.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by olemarkus** [comment]
I am not sure this is a bug. You still have a partial update with this change, and new nodes will have the new config.
A better way of doing this would anyways be two independent IGs as the taint is applied IG by IG.

**Comment by vitaliyf** [comment]
Right, that's fair, and I wasn't too certain about full intent behind scheduled-for-update taint.

If you leave my edge-case of "I used interactive so I can purpose interrupt" aside and just think about "a rolling update got interrupted due to error or other external factor" then is it expected that remaining nodes are left tainted?

**Comment by olemarkus** [comment]
Correct. The idea being that it is better to schedule on new nodes than on nodes that are soon to be terminated.
