### ISSUE TITLE
unable to use -api-ssl-certificate while creating cluster using kops

### ISSUE THREAD

**Issue by patelsaheb29** [kubernetes/kops#12380]
HI,

When i am going to create cluster with command I got error as below,

unknown flag: --api-ssl-certificate

command I used for create kops cluster is 

kops create cluster --zones=us-east-1a,us-east-1b,us-east-1c --node-count=2 --node-size=t3.small --master-size=t3.micro --master-count=1 --api-ssl-certificate arn:aws:acm:us-east-1:xxxxxxx:certificate/7xxxxxx-xxxxxxx-xxxx4bb1e4e --name xxxxxx.com

Kops version is 

Version 1.21.1

cloud provider i am using is aws.

**Comment by olemarkus** [comment]
It doesn't look like the output from kops 1.21.1. You should have seen an error that looks like:

```
spec: Forbidden: sslCertificate requires network loadbalancer for K8s 1.19+ see https://github.com/kubernetes/kops/blob/master/permalinks/acm_nlb.md
```

Can you please run `kops version` as suggested by the issue template?

**Comment by patelsaheb29** [comment]
Version 1.21.1 (git-ffabc3bf682bfc25ffdce99e54005345df94b467)

**Comment by olemarkus** [comment]
Yeah, that version will not emit the error message you have above, but it will omit an error because you have not defined set the load balancer type to be network.

**Comment by patelsaheb29** [comment]
Ohk so that must be defined.

Thx
