### ISSUE TITLE
Get cluster doesn't respect name flag

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#1238]
`kops get cluster --name=<name> --state=<state>`

Will ignore the cluster passed in the name flag and instead return all clusters that exist in the S3 state bucket.

**Comment by chrislovecnm** [comment]
Ouch ... we need more testing :(  That should work ...

**Comment by yissachar** [comment]
Note that it works when you pass the name as first arg, but we should be consistent with how the name flag works elsewhere.

`kops get cluster <name> --state=<state>`

**Comment by chrislovecnm** [comment]
It should work as advertised :)
