### ISSUE TITLE
Behave better if validation fails

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#124]
Currently we just reject the update and discard the user's changes.  This could be frustrating.  Better to do the same loop that I think kubectl does.

**Comment by justinsb** [comment]
This _might_ be a good starter issue, in that we modelled this code after `kubectl edit`, but obviously kubectl edit is doing some things better than we do.  OTOH, it requires digging into `kubectl edit`, which is not trivial code.  But if someone wants to read a lot of go code first, this isn't a bad place to begin!

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/edit.go Edit code
