### ISSUE TITLE
volumeMounts logic running after scripts that are supplied through AdditionalUserData

### ISSUE THREAD

**Issue by gabron** [kubernetes/kops#12401]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.21.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.21.4

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

The problem has to do with the `volumeMounts` feature and `additionalUserData` and the order they run in.
I ran the the `kops create -f file.yaml` using a template that was generated from the toolbox feature.  I then ran the update command to instantiate the cluster.  The following is a snippet from the instance group that was part of the template:
```...
spec:
  securityGroupOverride: xx-xxxxxxxxxxxxx
  additionalUserData:
    - name: dbs.sh
      type: text/x-shellscript
      content: |
        #!/bin/bash
        sudo mkdir -p /dbs/postgres/data
        sudo mkdir -p /dbs/mysql/data
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210825
  machineType: i3en.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: node-storage-optimized
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  volumeMounts:
  - device: /dev/nvme1n1
    filesystem: ext4
    path: /dbs```

I am trying to leverage the volumeMounts feature mount the nvme drive and use the additionalUserData to manipulate the drive. 

**5. What happened after the commands executed?**

The issue I encountered is that when the node spun up the additionalUserData had run before the volumeMount command, I have not seen this happen in the past.  Here is a snippet from the journalctl on the node:

```
Sep 22 21:40:12 ip-10-0-154-190 sudo[1229]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/mkdir -p /dbs/postgres/data
Sep 22 21:40:12 ip-10-0-154-190 sudo[1231]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/mkdir -p /dbs/mysql/data
Sep 22 21:40:22 ip-10-0-154-190 nodeup[1287]: I0922 21:40:22.083106    1287 volumes.go:65] Attempting to format and mount device: /dev/nvme1n1, path: /dbs
Sep 22 21:40:36 ip-10-0-154-190 nodeup[1287]: I0922 21:40:36.160243    1287 mount_linux.go:418] Disk successfully formatted (mkfs): ext4 - /dev/nvme1n1 /dbs
Sep 22 21:40:36 ip-10-0-154-190 nodeup[1287]: I0922 21:40:36.160271    1287 mount_linux.go:436] Attempting to mount disk /dev/nvme1n1 in ext4 format at /dbs
```
showing by timestamp the volume mounts happening after the mkdir commands from user data.

**6. What did you expect to happen?**

I expected the additionalUserData scripts to execute much later, because that has been my previous experience, although maybe it coincidentally worked.  

However here is the kicker, if I were to alter the additionalUserData portion of the yaml to resemble the following:

```
additionalUserData:
    - name: postgres.sh
      type: text/x-shellscript
      content: |
        #!/bin/bash
        sudo mkdir -p /dbs/postgres/data
    - name: mysql.sh
      type: text/x-shellscript
      content: |
        #!/bin/bash
        sudo mkdir -p /dbs/mysql/data
```
where there are two line items, the postgres.sh script would always execute minutes later, that is minutes after the volumeMounts command, while the mysql.sh script would still execute before it.  That was weird behavior, I reproduced that one three times and it consistently fired off the two additionalUserData scripts minutes a part.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-09-03T14:56:00Z"
  generation: 1
  name: xxxxx.k8s.local
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
  channel: stable
  cloudProvider: aws
  configBase: s3://state-location/xxx.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ig
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ig
      name: a
    memoryRequest: 100Mi
    name: events
  externalPolicies:
    node:
    - arn:xxxxxxrIAMPolicy
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.21.4
  masterInternalName: api.internal.xxx.k8s.local
  masterPublicName: api.xxx.k8s.local
  metricsServer:
    enabled: true
    insecure: true
  networkCIDR: 10.0.0.0/16
  networkID: vpc-xxx-id
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 10.0.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.128.0/20
    id: subnet-xxx-id
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 10.0.144.0/20
    id: subnet-xxx-id2
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: 10.0.0.0/19
    id: subnet-xxx-id
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 10.0.32.0/19
    id: subnet-xxx-id
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-03T14:56:00Z"
  labels:
    kops.k8s.io/cluster: xxx.k8s.local
  name: master-ig
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210825
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ig
  role: Master
  securityGroupOverride: sg-id-overirde
  subnets:
  - us-west-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-09T17:35:14Z"
  labels:
    kops.k8s.io/cluster: xxx.k8s.local
  name: node-ig
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo mkdir -p /dbs/postgres/data
      sudo mkdir -p /dbs/mysql/data
    name: dbs.sh
    type: text/x-shellscript
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210825
  machineType: i3en.large
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - i3en.large
    onDemandAboveBase: 0
    onDemandBase: 1
    spotAllocationStrategy: lowest-price
  nodeLabels:
    kops.k8s.io/instancegroup: node-ig
  role: Node
  securityGroupOverride: sg-id-override
  subnets:
  - us-west-2a
  - us-west-2b
  volumeMounts:
  - device: /dev/nvme1n1
    filesystem: ext4
    path: /dbs
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I've been unable to find anything in the documentation that would suggest ordering of additionalUserData scripts.  It may be a documentation change, that or I'm blind.

**Comment by olemarkus** [comment]
The kops configuration script part of userdata is called nodeup. The userdata files ordering is alphabetical.

mysql nodeup postgres ...

**Comment by gabron** [comment]
That makes sense, I didn't find it in the docs but that does seem like necessary information.  I don't know all the use cases but does it make sense that volume mount logic run before additionalUserData.  In my case it does.  I guess the additionalUserData portion always felt like a bolt on where volumeMounts seems like part of a core flow so I must have assumed it would run before any additional data.

**Comment by gabron** [comment]
It would also appear that the further down the alphabet a script gets named the later it runs, I named the script `z_setup.sh` to ensure it would run last and it is now running six minutes after the `nodeup` (volumeMounts) script

```
Sep 23 16:54:08 ip-10-0-153-65 nodeup[1271]: I0923 16:54:08.644402    1271 volumes.go:65] Attempting to format and mount device: /dev/nvme1n1, path: /dbs
Sep 23 16:54:22 ip-10-0-153-65 nodeup[1271]: I0923 16:54:22.550093    1271 mount_linux.go:418] Disk successfully formatted (mkfs): ext4 - /dev/nvme1n1 /dbs
Sep 23 16:54:22 ip-10-0-153-65 nodeup[1271]: I0923 16:54:22.550123    1271 mount_linux.go:436] Attempting to mount disk /dev/nvme1n1 in ext4 format at /dbs
Sep 23 16:54:22 ip-10-0-153-65 nodeup[1271]: I0923 16:54:22.550143    1271 mount_linux.go:175] Mounting cmd (systemd-run) with arguments (--description=Kubernetes transient mount for /dbs --scope -- mount -t ext4 -o defaults /dev/nvme1n1 /dbs)
Sep 23 16:54:22 ip-10-0-153-65 systemd[1]: Started Kubernetes transient mount for /dbs.
Sep 23 17:00:29 ip-10-0-153-65 sudo[4436]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/mkdir -p /dbs/postgres/data
Sep 23 17:00:29 ip-10-0-153-65 sudo[4438]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/mkdir -p /dbs/mysql/data
```
