### ISSUE TITLE
Cilium broken on Amazon Linux 2 and RHEL8

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#12429]
/kind bug

copied from https://github.com/kubernetes/kops/pull/12141#discussion_r714415257

https://testgrid.k8s.io/kops-grid#kops-grid-cilium-rhel8-k22-containerd

[kubelet logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-cilium-rhel8-k22-containerd/1438294568381452288/artifacts/ip-172-20-39-12.us-east-2.compute.internal/kubelet.log) report:

`E0916 00:19:04.290207 18754 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/host-path/23431797-5c17-4404-b61b-33d2e8ec3d54-cilium-cgroup podName:23431797-5c17-4404-b61b-33d2e8ec3d54 nodeName:}" failed. No retries permitted until 2021-09-16 00:19:36.290185341 +0000 UTC m=+151.386939478 (durationBeforeRetry 32s). Error: MountVolume.SetUp failed for volume "cilium-cgroup" (UniqueName: "kubernetes.io/host-path/23431797-5c17-4404-b61b-33d2e8ec3d54-cilium-cgroup") pod "cilium-8rdpr" (UID: "23431797-5c17-4404-b61b-33d2e8ec3d54") : mkdir /sys/fs/cgroup/unified: read-only file system`

> We could mount cgroup2 explicitly somewhere else as well, like we used to with bpffs. Or we could drop support for not-that-modern-distros.

In https://github.com/kubernetes/kops/pull/11696 we deprecated CentOS 8 but not RHEL 8. AL2 is still the most modern version of Amazon Linux so I dont think we should be deprecating it. I think it would be best if we mount cgroup2 elsewhere.

**Comment by rifelpet** [comment]
Also we may want to consider this blocking 1.22 given the breaking change was introduced in 1.22 and is breaking clusters for supported distros.

**Comment by olemarkus** [comment]
I agree. I'll revive the mount functionality and have it mount cgroup2 on the default cilium location (/run/cilium/cgroupv2)

**Comment by olemarkus** [comment]
RHEL8's kernel is too old for cilium. But #12431 should take care of AL2 5.10 kernel

**Comment by olemarkus** [comment]
I am not sure I'd say this is an "advanced feature" anymore as it has been the default in cilium for quite some time, and for kOps as well. But "Kubernetes Without kube-proxy" is enabled by default (on new clusters).

**Comment by rifelpet** [comment]
In that case maybe we add a 1.22 release note mentioning that cilium + RHEL8 is not supported. We can skip those grid jobs too (and add AL2)

**Comment by johngmyers** [comment]
@rifelpet is the current release note sufficient?
