### ISSUE TITLE
Use private registy/storage for external resources

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kops#1242]
We need to be able to use external resources (such as pause-amd64 which is hosted on gcr registry or protokube that is hosted on DockerHub, or even to host the nodeup binary in the user's bucket) .

The reason is for security, some clusters are blocked for egress and can only use internal private registry.
Someone knows if it is possible to access resources on other accounts thru AWS S3 customer-endpoint? 

WDYT? How this should be implemented?

**Comment by chrislovecnm** [comment]
Already an open issue. See self hosting. Would love some help to identify the components!

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/issues/715 <- closing as a duplicate
