### ISSUE TITLE
Implementing kubelet GC settings in kops

### ISSUE THREAD

**Issue by markine** [kubernetes/kops#1243]
I'm looking to experiment with garbage collection on a cluster created by kops. I need to specify custom flags for kubelet (/etc/sysconfig/kubelet). Two issues:

How do I edit the Kubelet part of the cluster spec? I tried manually downloading cluster.spec from S3, editing it, and uploading it back. 'kube update' did not recognize any changes made to the kubelet stanza.

What needs to happen for kops to process the GC flags? The GC config flags are here: http://kubernetes.io/docs/admin/garbage-collection/. These settings are commented out of the kubelet spec in kops:

ImageGCHighThresholdPercent : https://github.com/kubernetes/kops/blob/9e79acaec60d5381197ebfc9279fea7e2d4dbb76/pkg/apis/kops/componentconfig.go#L152

ImageGCLowThresholdPercent: https://github.com/kubernetes/kops/blob/9e79acaec60d5381197ebfc9279fea7e2d4dbb76/pkg/apis/kops/componentconfig.go#L156

Thank you.

**Comment by chrislovecnm** [comment]
Take a look at https://github.com/kubernetes/kops/pull/1083

Also take a look at

**Comment by chrislovecnm** [comment]
The API docs under developer, also I cannot find the issue for the process that we are working on how to contribute

**Comment by chrislovecnm** [comment]
Docs on API https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/issues/1194 <- start on a howto contribute.

Also we have dev office hours tomorrow, see the readme

**Comment by markine** [comment]
@chrislovecnm Thank you for a fast reply and the info! 

Could you please answer the question re: expected method of modifying the full cluster.spec? I could not get 'kops update cluster' to pick up changes to existing fields in the spec, albeit I only tried one or two fields.

**Comment by chrislovecnm** [comment]
@markine you are trying to update the api, need api values, and need to regenerate the api.  Feel free to push a PR and we can comment on the code!
