### ISSUE TITLE
We should document the state of our federation support

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1244]
We have early federation support, but we need to document it better!

**Comment by tslater** [comment]
That would be great. Could anyone provide a quick summary here? I can't find anything on Kops federation.

**Comment by alexw23** [comment]
@tslater there's somewhat of an example in #2056

**Comment by izakp** [comment]
It's hard to determine the current state of federation support from the existing docs.  Any chance to add a `federation.md` [here](https://github.com/kubernetes/kops/tree/master/docs)?

**Comment by chrislovecnm** [comment]
We removed support
