### ISSUE TITLE
kops controller - continuously create kube-proxy SA

### ISSUE THREAD

**Issue by ltagliamonte-dd** [kubernetes/kops#12458]
/kind bug

I've notice that my API servers have a constant 409 error code.
using the audit log I narrowed down the source of the 409s to the kops controller.
It looks like the controller tries to re-create the kube-proxy SA over and over.

```
{
   "stream":"stdout",
   "time":"2021-10-01T16:06:39.691171033Z",
   "kind":"Event",
   "apiVersion":"audit.k8s.io/v1",
   "level":"Request",
   "auditID":"2b5845b0-186f-4a8d-be84-6fabd37af4e8",
   "stage":"ResponseComplete",
   "requestURI":"/api/v1/namespaces/kube-system/serviceaccounts",
   "verb":"create",
   "user":{
      "username":"kops",
      "groups":[
         "system:masters",
         "system:authenticated"
      ]
   },
   "sourceIPs":[
      "127.0.0.1"
   ],
   "userAgent":"protokube/v0.0.0 (linux/amd64) kubernetes/$Format",
   "objectRef":{
      "resource":"serviceaccounts",
      "namespace":"kube-system",
      "name":"kube-proxy",
      "apiVersion":"v1"
   },
   "responseStatus":{
      "metadata":{
         
      },
      "status":"Failure",
      "reason":"AlreadyExists",
      "code":409
   },
   "requestObject":{
      "kind":"ServiceAccount",
      "apiVersion":"v1",
      "metadata":{
         "name":"kube-proxy",
         "namespace":"kube-system",
         "creationTimestamp":null
      }
   },
   "requestReceivedTimestamp":"2021-10-01T16:06:39.685818Z",
   "stageTimestamp":"2021-10-01T16:06:39.691068Z",
   "annotations":{
      "authorization.k8s.io/decision":"allow",
      "authorization.k8s.io/reason":""
   },
   "kubernetes":{
      "pod_name":"kube-apiserver-ip-172-30-31-102.us-west-2.compute.internal",
      "namespace_name":"kube-system",
      "labels":{
         "k8s-app":"kube-apiserver"
      },
      "host":"ip-172-30-31-102.us-west-2.compute.internal",
      "container_name":"kube-apiserver",
      "container_image":"k8s.gcr.io/kube-apiserver:v1.18.9"
   }
}
```

**Comment by johngmyers** [comment]
That's probably channels, installing a bootstrap addon.

**Comment by olemarkus** [comment]
Channels use kubectl, so user agent wouldn't show as protokube.

**Comment by ltagliamonte-dd** [comment]
@johngmyers @olemarkus i'd like to work on this issue but i'm not familiar with the codebase can you please give me some hints on where to look?
thanks!

**Comment by olemarkus** [comment]
I think perhaps this already is removed in master. have you seen if the same behaviour happens there?

**Comment by ltagliamonte-dd** [comment]
@olemarkus sorry for the late reply, the most updated cluster I have running runs k8s `v1.19.12` using `kops 1.21.1`
I still see the behavior in my splunk audit logs. it is trying to create the following resources over and over receiving 409:

<img width="582" alt="Screen Shot 2021-11-17 at 4 32 20 PM" src="https://user-images.githubusercontent.com/51684360/142314811-ba6437d3-19b1-4ab3-8b3e-779b6a52de29.png">

Do you have a specific kops version i should try?

**Comment by olemarkus** [comment]
We'll cut a new alpha in the coming days.

**Comment by danports** [comment]
Was this resolved in a more recent release? I'm running kops 1.22.3 and I'm seeing similar behavior, regular `409 AlreadyExists` errors from both ServiceAccounts and ClusterRoleBindings requests kops is making to the API server.

**Comment by olemarkus** [comment]
The code was removed entirely from 1.23. But we did not do any changes in the 1.22 branch.

**Comment by danports** [comment]
Thanks for clarifying - I'll give the next 1.23 release a try.

**Comment by olemarkus** [comment]
@danports did you see any changes with 1.23?

**Comment by danports** [comment]
I haven't seen the issue on 1.23, so I think we can close this.

**Comment by olemarkus** [comment]
Thanks for confirming.
/close
