### ISSUE TITLE
kops saying vpc and subnet do not exist when trying to build cluster with existing vpc and subnets

### ISSUE THREAD

**Issue by danfinn** [kubernetes/kops#12453]
/kind bug

I've had previous success with this method before and I'm now attempting to build a 2nd cluster (in another AWS account) with kops.  If I specify a vpc (or if I don't specify a vpc but I do specify subnets) kops says that they don't exist however they most certainly do and I can confirm that in the same shell by running the aws cli commands to describe them.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
/Applications/kops create cluster --node-count=3 --node-size=t2.large --zones=us-east-2a,us-east-2b --name=${KOPS_CLUSTER_NAME} --vpc=vpc-09668f9b4a3ae047f --subnets=subnet-086ba6af64bd719a9,subnet-0004e27188c35b0b9 --utility-subnets=subnet-086ba6af64bd719a9,subnet-0004e27188c35b0b9 --topology private --networking weave --ssh-public-key=Downloads/AWS_devops.pub

and here is the output from the same shell/terminal describing the vpc:
aws ec2 describe-vpcs
VPCS    10.112.0.0/16   dopt-09a17cf0639d5a71f  default False   356559873691    available       vpc-09668f9b4a3ae047f
CIDRBLOCKASSOCIATIONSET vpc-cidr-assoc-05237d83306dc67a7        10.112.0.0/16
CIDRBLOCKSTATE  associated
IPV6CIDRBLOCKASSOCIATIONSET     vpc-cidr-assoc-0e9896d28286296e7        2600:1f18:12ce:3000::/56        Amazon  us-east-1
IPV6CIDRBLOCKSTATE      associated
TAGS    Name    Company-VPC

**5. What happened after the commands executed?**
error describing VPC: error listing VPCs: InvalidVpcID.NotFound: The vpc ID 'vpc-09668f9b4a3ae047f' does not exist
	status code: 400, request id: 2742f974-9ef9-4517-8bd3-b25893bd5bf0

**6. What did you expect to happen?**
The cluster to get created

**Comment by rifelpet** [comment]
The zones you provide in the `create cluster` command are in us-east-2 but your `describe-vpcs` output mentions us-east-1. You'll need to create the cluster in zones from the same region as where the VPC is located.

**Comment by danfinn** [comment]
Thank you @rifelpet, that did it.  I figured it was something dumb on my part.

**Comment by rifelpet** [comment]
Glad to hear it

/close
