### ISSUE TITLE
Allow external server to join the cluster

### ISSUE THREAD

**Issue by xpepermint** [kubernetes/kops#12457]
/kind feature

I'm searching for documentation on how to have a custom instance group where I would put external nodes. By external nodes I mean servers not deployed by kops - that could be a locally hosted server, a server hoster by other cloud providers, and such. It's not clear how to do this in "kops" way.

So basically I would expect to have a command-line feature `kops join $SERVER $INSTANCEGROUP` that would allow me to add my own server to the existing kops cluster. Is something like this already possible?

**Comment by olemarkus** [comment]
Local or other cloud vendor is not really possible. All control plane components take cloud provider as argument and expects all nodes to be located in the same cloud.
Even further, e.g AWS expects all nodes to be in the same VPC. 
Within the same cloud provider, it is technically possible to provision other nodes, but there is no value in doing that.

**Comment by xpepermint** [comment]
@olemarkus Thanks for the comment. I'd like to run specific services "privately" to secure data and to save costs. You might not see the value in it but it's important for me and the clients I work for. Also, AWS and cloud providers will always have limits and rules, but as far as I know, at k8s level, no limits are really applied regarding node location. Please reconsider my proposal/request.

**Comment by olemarkus** [comment]
By control plane, I mean specifically k8s components. K8s itself has no support for what you are asking for.

**Comment by xpepermint** [comment]
I didn't know that. Hum, I had in my memory that I was joining nodes by external IPs.

**Comment by olemarkus** [comment]
It is perhaps technically possible to join nodes across clouds/environments when using something like kubeadm. How functional that cluster is is dubious. You could also implement your own Cloud Controller Manager that may be more multi-cloud. 

But the whole purpose of kOps is to be cloud aware and work through all layers of the infrastructure, so it doesn't make sense for kOps to support something like this. There may be other installers that are more appropriate.

**Comment by xpepermint** [comment]
Got it. Thanks anyway. Closing.
