### ISSUE TITLE
We need .github PR and ISSUE templates

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1248]
Can we update the repo with templates on how to open an issue and now to open a PR?

https://github.com/kubernetes/kubernetes/tree/master/.github

cc: @smwebber can you ping me on this item?  Not sure what you expertise with git it btw.

**Comment by aledbf** [comment]
@chrislovecnm maybe also add a reference to run https://github.com/kubernetes-incubator/spartakus in order to standarize the k8s context information?

**Comment by chrislovecnm** [comment]
@aledbf that would need to be optional :) 

We are trying to keep `kops` lean to the point of where the cluster is up and running as well.  We have issues in for a package manager type plugin, that could install stuff like spartakus and a dashboard.

**Comment by aledbf** [comment]
> that would need to be optional :)

off course :)

**Comment by chrislovecnm** [comment]
Closing we have issue form
