### ISSUE TITLE
Possible race condition with cni 

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1251]
We are installing CNI provider, and kube-dns at pretty much the exact same time. We should have the cni provider start and the. Install kube-dns. The other option is to address the problem in kube-dns. One of the components in kubr-dns goes into a crashloop and does not recover even if the network comes up. 

We need steps to recreate and more info.

**Comment by justinsb** [comment]
Moving to 1.5.1 pending repro steps

**Comment by chrislovecnm** [comment]
Steps to reproduce are dead simple

1. Install kops in ha (only run ha)
2. Check kube-dns

Quite often you will find kube-dns in a crash loop

**Comment by chrislovecnm** [comment]
Closing ... damn ethtool

**Comment by chrislovecnm** [comment]
Make sure your node has ethtool
