### ISSUE TITLE
Publish binaries to S3 for kOps v1.20.3 and v1.21.2

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#12515]
/kind bug

Binaries for stable releases < 1.22 should be copied to the legacy S3 location:

```bash
aws s3 sync --acl public-read k8s-staging-kops/kops/releases/${VERSION}/ s3://kubeupv2/kops/${VERSION}/
```

Refs:
https://github.com/kubernetes/kops/releases/tag/v1.20.3
https://github.com/kubernetes/kops/releases/tag/v1.21.2

**Comment by justinsb** [comment]
Done!
