### ISSUE TITLE
Unable to change load balancer to type internal

### ISSUE THREAD

**Issue by ajsalow** [kubernetes/kops#12530]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.21.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.21.4
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I'm trying to edit the cluster to turn loadbalancer to internal shown here - 
https://kops.sigs.k8s.io/topology/#steps-to-change-the-elb-from-internet-facing-to-internal

**5. What happened after the commands executed?**
```

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# Found fields that are not recognized
# ...
#     api:
#       loadBalancer:
# -       class: Classic
#         type: Internal
#     authorization:
# ...
```

**Comment by olemarkus** [comment]
The way kOps detects unrecognized fields has its flaws, unfortunately. I'll look into this.

**Comment by olemarkus** [comment]
Unfortunately I cannot reproduce this using 1.21.2. I can change from public to internal just fine.
Can you provide more the before/after cluster spec? And verify that you are actually using kops 1.21.2.

Can you also try a newer version of kops?
