### ISSUE TITLE
Provide opportunity for review on tricky defaults?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#126]
Some defaults are sort of tricky (e.g. --dns-zone)  Maybe when we default them we should print what we're doing and ask the user to confirm (and then we can have a `--yes` flag for non-interactive mode)

**Comment by blakebarnett** [comment]
Hard to maintain a list of things that are "tricky", but maybe all changes for edits should prompt?  What happens when multiple "tricky" things change during the same edit?
