### ISSUE TITLE
Ability to customize commands run on instancegroup nodes during startup

### ISSUE THREAD

**Issue by dnavre** [kubernetes/kops#1260]
I run an elasticsearch cluster on kubernetes created with kops on AWS. The new version of elasticsearch requires me to do "sudo sysctl -w vm.max_map_count=262144" on each of the nodes to be able to run ES on them. It would be great if I could add this as an initialization script to an instance group to make sure that the command was executed on all nodes.

Another scenario when this may be helpful is if one needs to modify the configurations files of docker(using insecure registry) or a similar scenario.

Is this something to consider or in each such case one should create a new AMI?

**Comment by kris-nova** [comment]
Hey @dnavre 

So we have been talking about running arbitrary logic on a cluster at different stages in the deployment. There isn't too much controversy around the matter. But you can find more information on a similar thread [here](https://github.com/kubernetes/kops/issues/387).

My approach to this was to solve the issue on a slightly more complicated, but over all more robust scale. Using a cooky idea I had around offering a plugin library for kops. More information on this issue [here](https://github.com/kubernetes/kops/issues/958)

**Comment by kris-nova** [comment]
I am going to close the issue since it seems like a duplicate, feel free to re-open and comment if that is not the case and we can explore this more! Cheers! Thanks for using kops.

**Comment by justinsb** [comment]
Although... if you wanted to open an issue for the default for `sudo sysctl -w vm.max_map_count=262144`, we can _also_ set that up for everyone.  My understanding is that there is an overhead, but it's negligible, so we should probably set it up by default.

I expect eventually k8s will configure this as part of pod resources, but in the meantime...

(There's also some recommended sysctls for nginx which are similar...)
