### ISSUE TITLE
Kops External-Dns addon fails on k8s v1.22 with source=Ingress

### ISSUE THREAD

**Issue by Paragon1970** [kubernetes/kops#12613]
/kind bug

**1. Versions:**

``` 
Kops Version: v1.22.0
Kubernetes Version: v1.22.2
Cloud Provider: AWS
Kops ExternalDns Addon Version: v0.9.0
```

**2. What commands did you run?  What is the simplest way to reproduce this issue?**

Add external-dns addon to cluster.config.spec:
```yaml
  externalDns:
    provider: external-dns
    watchIngress: true
```

```shell
$ kops replace -f cluster-config.yam
$ kops update cluster --name ${NAME} --yes --admin --v 1
```

**3. What happened after the commands executed?**

(a) This deploys:
 ``` yaml
 externalDns:
    provider: external-dns
 ```   
 (b) This does not:
 ```yaml
  externalDns:
    watchIngress: true
    provider: external-dns
```
Deploying with (a) and then adding (b) redeploys with --source=ingress but the pod enters a crash loop with 
`failed to sync cache: timed out waiting for the condition` 

**4. The Issue, Investigation, thoughts on fix / workaround, show the work:**

Kops installs `external-dns v0.9.0` this version internally references deprecated `networking.k8s.io/v1beta1` which is not supported in k8s v1.22.

**Partial Fix:** employ externel-dns image => v0.10.0

The above resolves `crash loop backoff` issue due to `failed to sync cache: timed out waiting for the condition` and the pod status settles 'running'

However, it introduces another issue described below, which does not appear to be resolved in External-Dns => v0.10.0.

- K8s v1.22 employs `networking.k8s.io/v1` 
- `ingress` no longer employs the annotation `kubernetes.io/ingress.class: "some-class `
- Instead it employs `spec.ingressClassName: "ingress-nginx"` 
- From investigation, `spec.ingressClassName`  is not supported in `external-dns` , it still relies on `kubernetes.io/ingress.class: "some-class" ` .

Further more, k8s in-built validation prevents adding `kubernetes.io/ingress.class` alongside the newer `spec.ingressClassName` this has major implications if employing declarative, gitops, build pipelines, deployment workflows.

**5. The Fix / Workaround with External-DNS => v0.10.0:**

External-Dns supports the arg `--annotation-filter` this enables user defined annotations.

Ingress annotation: `kubernetes.io/external-dns-class: "kops-external-dns"`

External-dns args: `--annotation-filter=kubernetes.io/external-dns-class=kops-external-dns`

I confess I am not at all familiar with Kops code base but while digging into it I found the following areas of code that grabbed my attention. 
The question here I guess is if we want to conditionally set  `--annotation-filter` when `watchIngress` is true: 
https://github.com/kubernetes/kops/blob/695fa39bfb9df8164bcbf297bec2504f2a42712a/upup/pkg/fi/cloudup/template_functions.go#L397-L405

Or, hardcode the --annotation-filter :
`argv = append(argv, "--annotation-filter=kubernetes.io/external-dns-class=kops-external-dns")`
https://github.com/kubernetes/kops/blob/695fa39bfb9df8164bcbf297bec2504f2a42712a/upup/pkg/fi/cloudup/template_functions.go#L618-L630

I'll leave this to the Kops to decide ;-)

***References:*** 
ExternalDNS does not support K8s 1.22 #2168:
The reliance on deprecated annotation causes Kubernetes validation issues #2386
Updated FAQ for usage of annotation-filter: https://github.com/kubernetes-sigs/external-dns/commit/4291995765c88dd69a9209be3210ebd9e8975168

**Comment by johngmyers** [comment]
Fixed by #12740 
/close
