### ISSUE TITLE
Coding for Docs

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1262]
In an effort to keep our coding standards high, and our docs effective I would like everyone to review an example GoDoc that we already have in place.

The link to the documentation is [here](https://godoc.org/k8s.io/kops/pkg/apis/kops/install)

The example of how to implement the documentation in code is [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/install/install.go#L17)

Note the comment matches the description of the package.

```
Package install installs the kops API group, making it available as an option to all of the API encoding/decoding machinery.
````

### Guidelines

1. Use complete sentences. Use punctuation. 
2. Put a meaningful description directly above the `package mypackage` declaration. It should say what the package does, and what it could be used for.

**Comment by chrislovecnm** [comment]
@kris-nova how do I code review for this better?

**Comment by kris-nova** [comment]
@chrislovecnm 

Follow my two tips to start. Package names are going to be a big one, and since most of our packages already exist, and don't have descriptions we might just have to add a PR that defines a lot of this stuff. 

Also, in my eyes every `Exported()` function should come with a full description. My preferred formula here is for the function to have full sentences, and name itself in the first word of the description. 

```
// Exported is a function that is exported. A user can tell it's exported because the first letter is capitalized. You should never use this function.
func Exported() {}
```

of course with us caring slightly less about functions like 

```
func unexported(){}
```

because typically user's won't be interacting with them anyway.

The official documentation on how to write awesome documentation inline with go code is [here](https://blog.golang.org/godoc-documenting-go-code)

Maybe open up a PR that has all of this data in it? And then we can start code reviewing for the items in listed in the PR?

**Comment by chrislovecnm** [comment]
Structs need documentation as well?

**Comment by kris-nova** [comment]
On my phone.. but if I had to come up with a convention..

ExportedStructs required 
unexportedStructs encouraged

**Comment by chrislovecnm** [comment]
Closing as this is in progress
