### ISSUE TITLE
Partition "aws" is not valid for resource "arn:aws:ec2:*:*:volume/*".

### ISSUE THREAD

**Issue by gavangleeson** [kubernetes/kops#12633]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.22.1 (git-da710c931fbfe0fc8fe7bb3e2d41ba6e09c899f9)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.19.10

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update cluster --name "${CLUSTER}" --yes

**5. What happened after the commands executed?**
W1029 09:12:44.231840   50788 executor.go:139] error running task "IAMRolePolicy/masters.admin.us-gov-west-1.gov.xxx.us.k8s.local" (9m58s remaining to succeed): error creating/updating IAMRolePolicy: MalformedPolicyDocument: Partition "aws" is not valid for resource "arn:aws:ec2:*:*:volume/*".

**6. What did you expect to happen?**
The cluster to be updated.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
The error appears to come from iamrolepolicy.go (line 282)
I can see the arn referenced in iam_builder.go (line 978)

Line 979 would need changing too as it references "arn:aws:ec2:*:*:snapshot/*"
Line 999 and 1000 also require changing as there are references to:
"arn:aws:ec2:*:*:volume/*",
"arn:aws:ec2:*:*:snapshot/*"

**Comment by timeswind** [comment]
Same issue caused by hard-coded partition name on my side
`
 {
      "Action": "ec2:CreateTags",
      "Condition": {
        "StringEquals": {
          "ec2:CreateAction": [
            "CreateVolume",
            "CreateSnapshot"
          ]
        }
      },
      "Effect": "Allow",
      "Resource": [
        "arn:aws:ec2:*:*:volume/*",
        "arn:aws:ec2:*:*:snapshot/*"
      ]
    },
    {
      "Action": "ec2:CreateTags",
      "Condition": {
        "StringEquals": {
          "ec2:CreateAction": [
            "CreateVolume",
            "CreateSnapshot"
          ]
        }
      },
      "Effect": "Allow",
      "Resource": [
        "arn:aws:ec2:*:*:volume/*",
        "arn:aws:ec2:*:*:snapshot/*"
      ]
    },
    {
      "Action": "ec2:DeleteTags",
      "Condition": {
        "StringEquals": {
          "aws:ResourceTag/KubernetesCluster": "aws-k8s.chunhuizk.com"
        }
      },
      "Effect": "Allow",
      "Resource": [
        "arn:aws:ec2:*:*:volume/*",
        "arn:aws:ec2:*:*:snapshot/*"
      ]
    },
`
