### ISSUE TITLE
Immediate addon update causes upgrade tests to fail

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#12653]
/kind bug

- We recently introduced a new flag into the dns-controller: `--internal-ipv4`.
- During an upgrade test, we make use of KOPS_BASE_URL and image sideloading.
- Because we apply the manifests before rolling the VMs, this means that the image sideload doesn't happen (with the newer version).
- This means that the dns-controller will run with whatever image happens to be tagged publicly, instead of the sideloaded version, and as that version doesn't have the flag, it will go into crash loop backoff.
- This is recoverable, we just need to restart the control-plane VMs so they sideload the image.
- However, we won't automatically do a rolling-update, because the first thing rolling-update does is check that the cluster is healthy, and dns-controller is not healthy.

cc @rifelpet I came across this while looking into the update test.  I think I also found an issue with concurrent etcd restores, in that etcd-events fails to come up and this is actually sort of subtle to detect (unlike when etcd-main fails to come up), so I'm poking around that area, but I imagine you will also hit this soon!

**Comment by johngmyers** [comment]
I'll cut a 1.23.0-alpha.2 for this.

**Comment by olemarkus** [comment]
I feel we get hit with this somewhat regularly. Maybe channels should follow kops version (don't think we set the channel version) and some addons should set a minimum channels version (i.e kops version) before being applied.
