### ISSUE TITLE
TF output not working

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1266]
When I run `kops update cluster ${CLUSTER_NAME} --model=cloudup --target=terraform` I get:
 
        W1226 10:59:24.221641   66930 securitygrouprule.go:153] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"api-elb.<redacted>","ID":null,"Description":"Security group for api ELB","VPC":{"Name":"<redacted>","ID":"vpc-b3639ad7","CIDR":"10.33.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=443"]}
        W1226 10:59:24.236059   66930 executor.go:109] error running task "SecurityGroup/masters.<redacted>" (9m49s remaining to succeed): unexpected target type for deletion: *terraform.TerraformTarget

The cluster was created using: `kops create cluster     --node-count 10     --zones us-west-2a,us-west-2b,us-west-2c     --master-zones us-west-2a,us-west-2b,us-west-2c      --node-size m4.large    --master-size m4.large     --topology private     --networking calico --name ${CLUSTER_NAME}  --vpc vpc-xxxxxxxx  --network-cidr 10.33.0.0/16`

**Comment by chrislovecnm** [comment]
@blakebarnett can you get us a kops version, and a log output with v 10?

**Comment by blakebarnett** [comment]
`$ kops version`
`Version git-789bfcf0`

debug output: https://gist.github.com/blakebarnett/71225200925fda6a6ae2224544d661d1

**Comment by blakebarnett** [comment]
I was pretty surprised to see the `kubernetesVersion: v1.4.6` in that output in the channel spec, maybe that's related to another bug I filed :)

**Comment by justinsb** [comment]
This should be fixed now as of #1572, which was in alpha4 & beta1

Please comment/reopen if you still see problems with kops 1.5.0 beta1 (or later!)

**Comment by blakebarnett** [comment]
Worked great for our production cluster, sorry forgot to update here!
