### ISSUE TITLE
Remove deprecated klog flag usage

### ISSUE THREAD

**Issue by serathius** [kubernetes/kops#12663]
/kind feature

Hey, in K8s 1.23 we are planning to deprecate multiple klog flags. [KEP-2845](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md)

Deprecated flags: `--log-dir`, `--log-file`, `--log-flush-frequency`, `--logtostderr`, `--alsologtostderr`, `--one-output`, `--stderrthreshold`, `--log-file-max-size`, `--skip-log-headers`, `--add-dir-header`, `--skip-headers`, `--log-backtrace-at`

One of the alpha milestones is requires us to remove usage of deprecated flags within K8s repo. Using [search](https://cs.k8s.io/?q=%22log-dir%7Clog-file%7Clog-flush-frequency%7Cone-output%7Cstderrthreshold%7Clog-file-max-size%7Cskip-log-headers%7Cadd-dir-header%7Cskip-headers%7Clog-backtrace-at%22&i=nope&files=&excludeFiles=%5C.md%24%7C.*vendor%2F&repos=kubernetes/kops) I have found multiple cases where kops uses deprecated flags (list created from search, some cases are already marked as fixed as they don't need to be fixed):

* [x] [addons/cluster-autoscaler/v1.10.0.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/addons/cluster-autoscaler/v1.10.0.yaml) - old manifess
* [x] [addons/cluster-autoscaler/v1.8.0.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/addons/cluster-autoscaler/v1.8.0.yaml) - old manifests
* [x] [nodeup/pkg/model/kube_apiserver.go](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/kube_apiserver.go) - uses go-runner
* [x] [nodeup/pkg/model/kube_controller_manager.go](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/kube_controller_manager.go) - uses go-runner
* [ ] [nodeup/pkg/model/kube_proxy.go](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/kube_proxy.go) 
* [x] [nodeup/pkg/model/kube_scheduler.go](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/kube_scheduler.go) - uses go-runner
* [x] [nodeup/pkg/model/tests/golden/awsiam/tasks-kube-apiserver.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/awsiam/tasks-kube-apiserver.yaml) - uses k8s 1.18
* [x] [nodeup/pkg/model/tests/golden/dedicated-apiserver/tasks-kube-apiserver.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/dedicated-apiserver/tasks-kube-apiserver.yaml) - uses k8s 1.18
* [x] [nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml) - uses go-runner
* [x] [nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml)- uses go-runner
* [ ] [nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml)
* [x] [nodeup/pkg/model/tests/golden/minimal/tasks-kube-scheduler.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/minimal/tasks-kube-scheduler.yaml) - uses go-runner
* [x] [nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-amd64.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-amd64.yaml) - uses k8s 1.18
* [x] [nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-arm64.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-arm64.yaml) - uses k8s 1.18
* [x] [nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-amd64.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-amd64.yaml) - uses k8s 1.18
* [x] [nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-arm64.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-arm64.yaml) - uses k8s 1.18
* [x] [nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-amd64.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-amd64.yaml)  - uses k8s 1.18
* [x] [nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-arm64.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-arm64.yaml) - uses k8s 1.18
* [x] [nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-arm64.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-arm64.yaml) - uses k8s 1.18
* [x] [nodeup/pkg/model/tests/golden/side-loading/tasks-kube-scheduler-amd64.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/side-loading/tasks-kube-scheduler-amd64.yaml) - uses k8s 1.18
* [x] [nodeup/pkg/model/tests/golden/side-loading/tasks-kube-scheduler-arm64.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/side-loading/tasks-kube-scheduler-arm64.yaml) - uses k8s 1.18
* [x] [nodeup/pkg/model/tests/golden/without-etcd-events/tasks-kube-apiserver.yaml](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/without-etcd-events/tasks-kube-apiserver.yaml) - uses k8s 1.18
* [x] [tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content) - old k8s version
* [x] [tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content) - old k8s version
* [x] [tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content) - old k8s version
* [x] [upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template](https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template) - old k8s version

In cases where --log-file is used directly on binary we would like to use go-runner binary, migration would require changing
```
/usr/local/bin/kube-scheduler --log-file=/var/log/kube-scheduler.log <other flags>
```
should be replaced with 
```
/go-runner --log-file=/var/log/kube-scheduler.log /usr/local/bin/kube-scheduler  <other flags>
```
assuming that "/go-runner" is available in container image.

Examples that are already migrated https://github.com/kubernetes/kops/blob/b73c2ac0bd9bb422c3a233978f87073048db163f/nodeup/pkg/model/tests/golden/minimal/tasks-kube-scheduler.yaml#L12-L23

/wg structured-logging

**Comment by serathius** [comment]
@kubernetes/wg-structured-logging-members

**Comment by rifelpet** [comment]
Hi @serathius, we discovered that the kube-proxy images don't have /go-runner, is that intentional? One of the items in your list was for kube-proxy so I was under the impression that it should be migrated to use /go-runner.

Looking at a recent CI build:

```
gsutil cp gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-ubuntu-containerd/v1.23.0-alpha.3.712+25faeb2311e68b/bin/linux/amd64/kube-proxy.tar .

cat kube-proxy.tar | docker load

docker run -it --rm --entrypoint=sh k8s.gcr.io/kube-proxy-amd64:v1.23.0-alpha.3.712_25faeb2311e68b
# ls -l
total 64
drwxr-xr-x   2 root root 4096 Sep 14 23:14 bin
drwxr-xr-x   2 root root 4096 Apr 10  2021 boot
drwxr-xr-x   5 root root  360 Nov  2 11:47 dev
drwxr-xr-x   1 root root 4096 Nov  2 11:47 etc
drwxr-xr-x   2 root root 4096 Apr 10  2021 home
drwxr-xr-x   6 root root 4096 Sep 14 23:14 lib
drwxr-xr-x   2 root root 4096 Aug 16 14:39 lib64
drwxr-xr-x   2 root root 4096 Jul 21 00:00 media
drwxr-xr-x   2 root root 4096 Jul 21 00:00 mnt
drwxr-xr-x   2 root root 4096 Jul 21 00:00 opt
dr-xr-xr-x 193 root root    0 Nov  2 11:47 proc
drwx------   2 root root 4096 Aug 16 14:39 root
drwxr-xr-x   3 root root 4096 Jul 21 00:00 run
drwxr-xr-x   2 root root 4096 Sep 14 23:14 sbin
drwxr-xr-x   2 root root 4096 Jul 21 00:00 srv
dr-xr-xr-x  13 root root    0 Nov  2 11:47 sys
drwxrwxrwt   2 root root 4096 Sep 14 23:14 tmp
drwxr-xr-x   1 root root 4096 Jul 21 00:00 usr
drwxr-xr-x  11 root root 4096 Jul 21 00:00 var

**Comment by serathius** [comment]
@rifelpet, no created https://github.com/kubernetes/kubernetes/issues/106086

**Comment by serathius** [comment]
Looked through all files, looks like kops already migrated! 
We just need to fix kube-proxy

**Comment by pohly** [comment]
> We just need to fix kube-proxy

Fix it where?

https://github.com/kubernetes/kubernetes/pull/106123 will be done soon (I'm just waiting for https://github.com/kubernetes/kubernetes/pull/106301 to be reviewed and merged). I was under the impression that having go-runner in the kube-proxy image would be needed for kops, but looking at this issue in more detail that doesn't seem to be the case (anymore)?

**Comment by rifelpet** [comment]
@pohly kops does need go-runner in the kube-proxy image. We attempted to use it in https://github.com/kubernetes/kops/pull/12664 but needed to revert because it was missing. Once https://github.com/kubernetes/kubernetes/issues/106086 is closed I'll attempt the migration to go-runner again.

**Comment by pohly** [comment]
Okay, I just got confused by "looks like kops already migrated".

The PR was merged and kube-proxy image on current k/k master has `/go-runner`:
```
$ docker run --rm k8s.gcr.io/kube-proxy-amd64:v1.23.0-alpha.4.255_3cfef611122484-dirty /go-runner -help
Usage of /go-runner:
  -also-stdout
    	useful with log-file, log to standard output as well as the log file
  -log-file string
    	If non-empty, save stdout to this file
  -redirect-stderr
    	treat stderr same as stdout (default true)
```

**Comment by rifelpet** [comment]
Thanks for the heads up, we need to wait for the next k8s pre-release to be cut so that our prow jobs that test with the latest k8s 1.23 tags will continue to pass. Once beta.0 is created next week we will merge https://github.com/kubernetes/kops/pull/12712
