### ISSUE TITLE
Unrecognized environment variable for etcd backups retention

### ISSUE THREAD

**Issue by chrism417** [kubernetes/kops#12670]
/kind bug

**1. What `kops` version are you running? 1.22.1

**2. What Kubernetes version are you running? 1.22.2

**3. What cloud provider are you using?** AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
We have the environment variables set as follows:

      - name: ETCD_MANAGER_HOURLY_BACKUPS_RETENTION
        value: 7d
      - name: ETCD_MANAGER_DAILY_BACKUPS_RETENTION
        value: 1y

Inside the etcd-cilium, etcd-main, and etcd-events containers we see:

{"level":"warn","ts":1635871248.4712045,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_MANAGER_DAILY_BACKUPS_RETENTION=1y"}
{"level":"warn","ts":1635871248.4712203,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_MANAGER_HOURLY_BACKUPS_RETENTION=7d"}

**Comment by rifelpet** [comment]
Are you experiencing any issues with the operation of etcd due to this? It looks like we're incorrectly passing the `ETCD_MANAGER_*` env vars to the child etcd process, but etcd should just ignore it:

https://github.com/etcd-io/etcd/blob/e2d67f2e3bfa6f72178e26557bb22cc1482c418c/pkg/flags/flag.go#L91-L94

**Comment by chrism417** [comment]
@rifelpet we're not experiencing issues but we'd like to set these env variables.

**Comment by rifelpet** [comment]
Are the backups being retained according to the values you're specifying?

**Comment by chrism417** [comment]
@rifelpet sorry for the delay. Yes, they are being retained according to the values. So this is just an error in the logs that can be ignored
