### ISSUE TITLE
kops does not clean GCE resources correcly

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#12683]
/kind bug

I am creating new kops cluster to GCP and then creating service with type "loadbalancer" and making pvcs.

After I execute kops delete cluster, I can see that following resources are not cleaned:
- loadbalancers (created by k8s)
- healthchecks (created by k8s) 
- disks (created by k8s)
- firewalls (created by k8s)

because of these missing cleanups its impossible to delete the existing cluster currently. However, it is also quite difficult to code cleanup for these resources because google cloud cloud controller does not add any tags to some resources. For instance, loadbalancer is just random hash without any tag or anything. Same applies to disk name, I could not find the algorithm how the name is structured.

**Comment by zetaab** [comment]
also there is firewall object that needs to be deleted as well

E1104 09:06:30.159113    6969 op.go:136] GCE operation failed: googleapi: Error 400: The network resource 'projects/xxxe-5737/global/networks/clustergcppr-47d437-k8s-local' is already being used by 'projects/xxx/global/firewalls/k8s-a3f759423696647d1b93509070ee43e6-http-hc'

**Comment by zetaab** [comment]
<img width="692" alt="Screenshot 2021-11-14 at 16 30 36" src="https://user-images.githubusercontent.com/22482503/141685499-1c20473b-99da-4f94-ae3d-956a1e06083a.png">

this is using new GCE CSI driver, no way to see from which cluster this resource is coming from

**Comment by rifelpet** [comment]
the GCE CSI driver has support for adding labels to its PDs:

https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/bc88549c3cdc1f5881af5992d04a1e13ae314def/cmd/gce-pd-csi-driver/main.go#L42

We could include that flag with the normal cloud labels in your https://github.com/kubernetes/kops/pull/12736

**Comment by zetaab** [comment]
@rifelpet see https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/867

**Comment by zetaab** [comment]
got it working https://github.com/kubernetes/kops/pull/12736/commits/7b019a91535c67e7e078663fbf30be75eea8bc64

now when executing delete cluster after that:

```
Disk			pvc-ddfa338e-a813-434d-a3ae-e4acca3fe542		pvc-ddfa338e-a813-434d-a3ae-e4acca3fe542
```

so still the loadbalancer is the issue.
