### ISSUE TITLE
failed to copy image: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws"

### ISSUE THREAD

**Issue by estahn** [kubernetes/kops#12704]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.22.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops get assets --copy
```

**5. What happened after the commands executed?**

```
W1109 22:24:06.038704   48618 copy.go:94] xxx.dkr.ecr.ap-southeast-2.amazonaws.com/coreos/flannel:v0.11.0: failed to copy image: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377
```

**6. What did you expect to happen?**

The images should have been copied.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
spec:
  assets:
    containerProxy: xxx.dkr.ecr.ap-southeast-2.amazonaws.com
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

see 5.

**9. Anything else do we need to know?**

I resolved it by using skopeo:

```
    assets=$($KOPS get assets "$CLUSTER_FQDN" -o json)
    echo "$assets" | jq -r '.images[] | .download | split(":") | first | split("/") | del(.[0]) | join("/")' | xargs -n1 -I% aws ecr create-repository --repository-name % --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=true 2>&1

    echo "$assets" | jq -r '.images[] | ["docker://\(.canonical)", "docker://\(.download)"] | join(" ")' | xargs -n2 skopeo copy
```

**Comment by rifelpet** [comment]
Can you try `kops get assets --copy` with the latest kOps 1.23 prerelease?

https://github.com/kubernetes/kops/releases/tag/v1.23.0-alpha.2

If it works, it will likely be a simple cherry-pick to get this into the next kOps 1.22 release.

**Comment by estahn** [comment]
@rifelpet Same issue:


```
# ~/Downloads/kops-darwin-amd64 version
Version 1.23.0-alpha.2 (git-3a97dbaa8d754d6f3318890c3e9159bd5ea1282c)

# ~/Downloads/kops-darwin-amd64 get assets --copy -v 1000000000
...
I1110 01:06:51.193918   56302 copyimage.go:81] copying image from quay.io/coreos/flannel:v0.11.0 to 855460960717.dkr.ecr.ap-southeast-2.amazonaws.com/coreos/flannel:v0.11.0
W1110 01:06:51.193988   56302 copy.go:94] 855460960717.dkr.ecr.ap-southeast-2.amazonaws.com/coreos/flannel:v0.11.0: failed to copy image: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377
...
```
