### ISSUE TITLE
issues with addon template image value when using containerRegistry

### ISSUE THREAD

**Issue by slimm609** [kubernetes/kops#12705]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
 Confirmed with 
 Version 1.19.1
 Version 1.20.2
 Version 1.22.1  

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
 1.19.2
 1.20.11
 1.21.3

**3. What cloud provider are you using?**
AWS

When setting the value for the containerRegistry (https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#containerregistry)
```yaml
spec:
  assets:
    containerRegistry: example.com/registry
```

It messes with some of the addons container names and converts them instead of handling them similar to the container name in the template (https://github.com/kubernetes/kops/blob/559b57ea4c85931987da2bb1de85f7d9cd81f880/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template)

If we look at this container from the calico template
```
image: {{ or .Networking.Calico.Registry "docker.io" }}/calico/typha:{{ or .Networking.Calico.Version "v3.19.1" }}
```
it renders to `docker.io/calico/typha:v.3.19.1`

However, if you copy these image to a private repo and then try to set the container registry, it updates them and modifies the name which now has a different name and path.
```
example.com/registry/docker.io-calico-typha:v3.19.1
```

If you try to override the calico registry and you have a top level containerRegistry set, it layers them together
```
  networking:
    calico:
      registry: example.com/registry
```

where the final image name would be 
```
example.com/registry/example.com-registry-calico-typha:v3.19.1
```

This causes issues when using private registries with copied images as each one now has to be renamed to a specific format and looking at the templates in the addons it is hard to determine what the image would be when copying in images to rename them.

Ideally when adding a custom registry, it would keep the standard format and just replace the first part (docker.io) and the resulting image would be 
```
example.com/registry/calico/typha:v.3.19.1
```

**Comment by hakman** [comment]
Hi @slimm609. Could you try using `containerProxy` instead?
https://kops.sigs.k8s.io/cluster_spec/#containerproxy

**Comment by slimm609** [comment]
We haven’t fully moved over to containerd but I should be able to test and see if this has the same issue

**Comment by slimm609** [comment]
@hakman I did try the `containerProxy` option and it did fix the issue with some of the images, others it did not.   

it was very mixed results and it seems like several addons are still missing the ability to override the image (tag or image) and both `containerRegistry` and `containerProxy` functioned very differently and wouldn't correct it in all cases.

**Comment by hakman** [comment]
Could you try `kops get assets` and see what it says, maybe provide some details on what it works and what not?
