### ISSUE TITLE
Master nodes are getting created under separate Autoscaling groups, Launch configurations

### ISSUE THREAD

**Issue by sandeepveldi** [kubernetes/kops#1272]
```
kops create cluster \
    --node-count 3 \
    --zones us-east-1a,us-east-1c,us-east-1d \
    --master-zones us-east-1a,us-east-1c,us-east-1d \
    --node-size t2.medium \
    --master-size t2.medium \
    ${NAME}
```

When the node-count is mentioned as 3, the minion nodes are created in three availability zones mentioned under the same autoscaling group. Where as the 3 master nodes are created under three different Auto scaling groups each per availability zone. 

This may not be a bug but I think it may be :)

**Comment by chrislovecnm** [comment]
@sandeepveldi it is as designed.  Would you recommend a better design?  We choose to force each master into a unique AZ and facilitate that through asg's that are tied to a zone.  There is an open issue to have 3 masters in one AZ.

**Comment by sandeepveldi** [comment]
@chrislovecnm usually when I try to create 3 EC2 instances using one ASG that can span across multiple AZs, the instances are evenly distributed across the AZs by the ASG itself unless there are not enough IP addresses available in the subnets corresponding to specific AZs. This is similar to what's being done for the minion nodes. Attached screenshot of the corresponding setup. 

Is there a restriction from Kubernetes standpoint that there cannot be more than one master node in an availability zone or subnet? Or this restriction is purely to ensure high availability of master across AZs.

Also, I'll raise a separate feature request to have independent flags for the master node count and the minion node count. 

![masterminionmultiazsetup](https://cloud.githubusercontent.com/assets/8190547/21510586/3a0c835a-cc63-11e6-8c3d-9bafdcf7e48d.png)

**Comment by chrislovecnm** [comment]
@justinsb when you have a chance can you chime in here?  

@sandeepveldi the main concern is to have a master in each az, to ensure HA across the zones.  Also if you restart and loose your storage because it is in a different AZ, that is a big issue for a master.

**Comment by sandeepveldi** [comment]
@chrislovecnm Thanks for the clarifications. 
I think it should be possible to take snapshots of the existing volumes, create new volumes out of those snapshots in the availability zone in which the new node will be coming up and attach those new volumes to this new node. 
But again, without having the implementation level details of kube master node recovery, I may be talking about something that does not make sense from kops implementation standpoint.

**Comment by justinsb** [comment]
The case of most concern is that if an AZ is down, your ASG will launch replacement instances into an existing AZ.  And then (I believe) when the AZ comes back, it won't rebalance.  Further, we can't expect to be able to snapshot the volume to move it, because the time when it is most needed is when the AZ is down.  In short, we do this to force instances into the various AZs.  For an HA configuration, we would rather run the etcd cluster degraded than with two instances in the same zone when a third zone is available.

I am sure more advanced strategies are possible - PRs are very welcome if you think it's worth it!

**Comment by sandeepveldi** [comment]
@justinsb thanks for the detailed explanation on this. It makes sense with current setup for HA distribution of nodes across the AZs.
