### ISSUE TITLE
Failing test: [sig-apps] Deployment should not disrupt a cloud load-balancer's connectivity during rollout

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#12723]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.23.0-alpha.2 (git-v1.23.0-alpha.2-60-g7fe3d21c24)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.23.0-alpha.4

**3. What cloud provider are you using?**
AWS, using ARM64 nodes

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
https://testgrid.k8s.io/kops-misc#kops-aws-misc-arm64-ci

**5. What happened after the commands executed?**
Test `[sig-apps] Deployment should not disrupt a cloud load-balancer's connectivity during rollout` fails on ARM64.

**9. Anything else do we need to know?**
This has started happening since https://github.com/kubernetes/kops/pull/12676 was merged and is triggered by enabling leader migration for Kubernetes controller manager:
https://github.com/kubernetes/kops/blob/e230cc95aaa5b782f3ede4de09bf45037357224d/pkg/model/components/kubecontrollermanager.go#L108-L111

**Comment by hakman** [comment]
CC @johngmyers @olemarkus

**Comment by johngmyers** [comment]
Reading the documentation again, it seems we have to patch the `system::leader-locking-kube-controller-manager` Role. Why did k/k design this to be so hard to automate?

So do we need to do this in protokube?

**Comment by hakman** [comment]
Or maybe we can do it in kOps controller. Seems better equipped to watch and patch the role.

**Comment by johngmyers** [comment]
I don't think in needs to watch. It just needs a one-time patch on new cluster or k8s upgrade.

**Comment by olemarkus** [comment]
This one was fixed with the leader migration addon? I see the test is still failing though.

**Comment by olemarkus** [comment]
This bug is caused by KCM running with migration enabled even after CCM has been installed.
