### ISSUE TITLE
Using dns-controller with Google Container Engine

### ISSUE THREAD

**Issue by ruippeixotog** [kubernetes/kops#1273]
Hi! I'm new to Kubernetes and I'm playing around with the APIs and the concepts. I launched a cluster in Google Cloud (in which I am a newbie too) via Container Engine and one in AWS using kops.

Having known DNS names automatically assigned to my load balancers is very important to me. dns-controller does a pretty good job in my AWS cluster and because of that I am trying to launch it in Google Cloud too, as I saw that it also supports Cloud DNS.

I tried to use [this](https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/dns-controller/v1.4.0.yaml) definition, removing the `nodeSelector` constraint and changing the command-line arg. However, I'm getting this log message when I try to add a service with `dns.alpha.kubernetes.io/external`:

```
Unexpected error in DNS controller, will retry: error querying for zones: googleapi: Error 403: Insufficient Permission, insufficientPermissions
```

How can I pass the correct credentials in Google Cloud? Is there an IAM-like concept which I must change? Is there any way I can pass credentials directly to dns-controller?

**Comment by geojaz** [comment]
Hey @ruippeixotog this is a blast from the past :) Are you still thinking about this? Google does have cloud IAM which may or may not help what was bothering you last year. 

Closing because out of kops scope.

**Comment by ruippeixotog** [comment]
I forgot about this too :) I was trying to design a deployment process that was as cloud-agnostic as possible and the dns-controller fit well into it as a way to assign DNS names. I ended up staying AWS-only for the moment, taking full advantage of kops for that.
