### ISSUE TITLE
Container runtime configuration should be per instanceGroup

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#12750]
/kind feature

There are a number of use cases that require a different configuration for the container runtime per instance group. Currently it is only possible configure containerd or docker in the cluster_spec. This can cause issues especially for masters which have extremely different requirements for the runtime. As an example, GPU instances currently are supported but can only be configured/enabled cluster-wide.

I'd like to propose moving the container runtime configuration into the InstanceGroup spec.

**Comment by olemarkus** [comment]
I don't disagree. the GPU config was supposed to be per IG, but then was moved into the containerd config.
But for GPU, note that the config is ignored on non-GPU instance types.

**Comment by blakebarnett** [comment]
Yeah the problem I'm hitting is I need a different containerd config (currently because of registry auth, but there are other future scenarios as well). So the only way to achieve that is to override the containerd config cluster-wide, which then means we need to manually install/configure Nvidia stuff via cloud-init on all instance groups... etc. etc.

**Comment by blakebarnett** [comment]
I settled on this as a work-around, perhaps we could do something similar as the default until there's a better option?

in the cluster spec (note the `imports`):
```
  containerd:
    configOverride: |
      version = 2
      imports = ["/etc/containerd/runtime_*.toml"]

      [plugins]
        [plugins."io.containerd.grpc.v1.cri"]
          [plugins."io.containerd.grpc.v1.cri".containerd]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                runtime_type = "io.containerd.runc.v2"

                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  SystemdCgroup = true

          [plugins."io.containerd.grpc.v1.cri".registry]
            [plugins."io.containerd.grpc.v1.cri".registry.configs]
              [plugins."io.containerd.grpc.v1.cri".registry.configs."<REGISTRY_NAME>"]
                [plugins."io.containerd.grpc.v1.cri".registry.configs."<REGISTRY_NAME>".auth]
                  password = "<REGISTRY_PW>"
                  username = "<REGISTRY_USER>"

Then in an instanceGroup spec (leaving out all the other cloud-init bits):
```
      write_files:
      - path: /etc/containerd/runtime_nvidia.toml
        content: |
          [plugins]
            [plugins."io.containerd.grpc.v1.cri"]
              [plugins."io.containerd.grpc.v1.cri".containerd]
                default_runtime_name = "nvidia"
    
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
    
                  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
                    runtime_type = "io.containerd.runc.v2"
    
                    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
                      BinaryName = "/usr/bin/nvidia-container-runtime"
                      SystemdCgroup = true
```

Until (or if) a way to configure containerd specifically for an instanceGroup exists this at least lets us avoid installing the nvidia packages/drivers on all nodes. Perhaps the default could be something like this and if `nvidiaGPU: true` wrote a file that would get dynamically loaded if present rather than writing a complete containerd config that would satisfy most use-cases.
