### ISSUE TITLE
Add --dns to DOCKER_OPTS

### ISSUE THREAD

**Issue by jwolski2** [kubernetes/kops#12755]
/kind feature

Hey there, I'd like to contribute a feature that adds support for the `--dns` flag to be set in [DOCKER_OPTS](https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/docker.go#L396-L399). The need for us is to set this flag at the daemon-level because we have an internal service that invokes `docker build` directly. The Docker-build cannot properly resolve addresses without us supplying a DNS resolver. I understand the change required to Kops is akin to this commit: https://github.com/kubernetes/kops/commit/c294e3df585fe7dcdff9e85fae8c87f49470c23a where a `Runtimes` flag was introduced.

Following the [contribution](https://github.com/kubernetes/kops/blob/master/CONTRIBUTING.md) guidelines in this repo: upon acceptance of this proposal, I'll sign the CLA and get working on a fix.

**Comment by hakman** [comment]
Hi @jwolski2. Sure, happy to accept the contribution.
Docker args are a bit odd when it comes to lists, so maybe take a look at https://github.com/kubernetes/kops/issues/11024 and its fix. Probably `repeat` is needed, but should be tested first if arg should be passed multiple times.

**Comment by jwolski2** [comment]
@hakman thx for the quick response and the advice on the fix. I'll start taking the next steps.
