### ISSUE TITLE
hostNetwork pods still cannot access kube-dns

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1277]
They should be able to with k8s 1.5 (now that the hacks are gone)

**Comment by justinsb** [comment]
They can in theory, except that kubernetes seems not to honor ClusterFirst: https://github.com/kubernetes/kubernetes/issues/17406

We are able to `dig @100.64.0.10 <name>`, but /etc/resolv.conf still has the host's DNS configuration

**Comment by justinsb** [comment]
I don't think there's anything we can do in 1.5.0

**Comment by chrislovecnm** [comment]
This is an upstream issue that has been resolved. Please reopen if needed
