### ISSUE TITLE
Kops e2e failing after #36004

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#1278]
kubernetes/kubernetes#36004 broke the `kops-aws{,-updown}` jobs. Investigating.

The first problem is that apparently the kops jobs are picking up the CloudSDK `kubectl`, which isn't normally a big deal. I've got a fix for that, but the cluster isn't coming up, still.

**Comment by chrislovecnm** [comment]
@zmerlynn all fixed?

**Comment by zmerlynn** [comment]
`Up` is fixed, the remaining issues are tracked in https://github.com/kubernetes/kubernetes/issues/39256

**Comment by justinsb** [comment]
Thanks - sounds like remaining issues are elsewhere, so closing.  Please reopen / comment if that's not right.
