### ISSUE TITLE
Improve Kops validation, make sure dns-controller is running

### ISSUE THREAD

**Issue by ltagliamonte-dd** [kubernetes/kops#12781]
/kind feature

The other day we bounced our dev cluster and after the bounce completed we lost connectivity between the control plane nodes and the workers node.
After a bit of investigation we realized that the DNS name (api.internal.<clustername>.<domain>) used by the worker nodes was not updated with the new IPs associated with the master nodes. We fixed by manually updating the DNS entries.

Our understanding is that dns-controller is in charge of keeping updated this entry by looking at pod annotation: `dns.alpha.kubernetes.io/internal`
This is what we believe happened in our case:

- the first control-plane node rebooting, runs dns-controller
- dns-controller can’t start because of the linkerd blocking validation webhook (linkerd was not healthy on this dev cluster, and the fail policy was `Fail`)
- kops doesn’t validate that dns-controller is running and continues the bounce hence all the IPs change and we lost the internal DNS entry, this cause the entire cluster to fail

I understand this is a very uncommon corner-case, but during a bounce a lot of things can go wrong.

I'd like to propose to add as validation step to check the readiness/healthiness  of the dns-controller pod.
Looking forward to hear from the community.

**Comment by johngmyers** [comment]
It's better for webhooks to select on a label when they can.

The cluster could be using external-dns instead of dns-controller, so it wouldn't be correct to always require a dns-controller pod be present.

If the pod existed but was pending or some other non-ready state, then validation would have failed. The only other thing I can think of is look for Deployments with system-cluster-critical pods which do not have enough matching pods.

**Comment by ltagliamonte-dd** [comment]
> the pod existed but was pending or some other non-ready state, then validation would have failed.

Thank you for the reply @johngmyers.

> It's better for webhooks to select on a label when they can.

Unfortunately most of the time operator install this "intrusive" tools via 3rd party CLI or helm charts and they don't know the whole picture, that's why i'm proposing to improve cluster validation.


> The cluster could be using external-dns instead of dns-controller, so it wouldn't be correct to always require a dns-controller pod be present.
> 

yes, the kops should know about it, isn't it? in case of in cluster dns-controller apply more validation.

> If the pod existed but was pending or some other non-ready state, then validation would have failed. The only other thing I can think of is look for Deployments with system-cluster-critical pods which do not have enough matching pods.

The replicaset couldn’t create the pod because the webhoook was failing. That's why maybe a good course of action would be to check that the pod is in `Ready` status.
