### ISSUE TITLE
Move protokube to somewhere other that b.gcr.io

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#1280]
The `gcr.io` "bring your own bucket" support is being deprecated, so we'll need to house the protokube image somewhere else where some multiple of us can push to it. (c.f. https://cloud.google.com/container-registry/docs/support/deprecation-notices)

**Comment by chrislovecnm** [comment]
@justinsb we talked about moving stuff up to S3, should we do that and move out of gcr.io?

**Comment by zmerlynn** [comment]
I can move it to ECR, if that's what you mean.

**Comment by chrislovecnm** [comment]
I think we can actually have http docker repo.  We could look at ECR, but @justinsb was saying that pure http pull may be faster.

**Comment by chrislovecnm** [comment]
Closing because of the release issue. We are working on a fix. Not fixed yet, but this is a dup.
