### ISSUE TITLE
Addon NodeProblemDetector missing privileges

### ISSUE THREAD

**Issue by GMartinez-Sisti** [kubernetes/kops#12817]
/kind bug

**1. What `kops` version are you running?* Kops 1.22.2

**2. What Kubernetes version are you running?* 1.18.20

**3. What cloud provider are you using?** AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Install addon using the documentation steps -> https://kops.sigs.k8s.io/addons/#node-problem-detector

**5. What happened after the commands executed?**
Pods log show the follower error:
```
E1122 21:46:22.131359       1 manager.go:162] failed to update node conditions: nodes "ip-10-200-20-18.eu-west-1.compute.internal" is forbidden: User "system:serviceaccount:kube-system:default" cannot patch resource "nodes/status" in API group "" at the cluster scope
```
**6. What did you expect to happen?**
Node Problem Detector pod would be able to update node status.

**7. Please provide your cluster manifest.** N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.** N/A

**9. Anything else do we need to know?**
According to some digging, the current [configuration](https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/node-problem-detector.addons.k8s.io/k8s-1.17.yaml.template) is missing the `ServiceAccount ` and `ClusterRoleBinding` resources.

An example is available here -> https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/node-problem-detector/npd.yaml.

Related issue: https://github.com/kubernetes/node-problem-detector/issues/149

Happy to send a PR. Please let me know.

Regards

**Comment by zhengtianbao** [comment]
Got it, thanks, I'd like to fix this. :smiley_cat: 
/assign

**Comment by GMartinez-Sisti** [comment]
Thank you @zhengtianbao. We're just missing the link between the serviceAccount and the daemonSet -> https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/node-problem-detector/npd.yaml#L83.

**Comment by zhengtianbao** [comment]
Sorry, I missed it, thanks for pointing this out. @GMartinez-Sisti
