### ISSUE TITLE
Add Capacity Rebalance feature to IG

### ISSUE THREAD

**Issue by aslobodskoy-fiksu** [kubernetes/kops#12827]
/kind feature

Capacity rebalance option is missing in Instance Group configuration

https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-capacity-rebalancing.html#enable-capacity-rebalancing

**Comment by olemarkus** [comment]
The default is enabled. Could you perhaps elaborate on why you want this disabled?

**Comment by aslobodskoy-fiksu** [comment]
@olemarkus Are you sure? I've several ASGs created by kops with capacity rebalance disabled. They are capacity optimized but capacity rebalance is off.

**Comment by olemarkus** [comment]
According to the docs it should be. If that is not the case we definitely need to enable this. I'll look into it

**Comment by aslobodskoy-fiksu** [comment]
I've check go SDK and looks like it has no default value

**Comment by olemarkus** [comment]
I looked at the ASG configuration that kOps generate, and the flag has _no value_, which means the default is used, and according to the docs that is _enabled_. If you look at the web console, you will see just `-` as value, again indicating no value set. You can toggle the checkbox, at which point it will be set to `on`, and the next untoggle will set the flag to `off`. Doesn't look like the console supports unsetting the value altogether.
