### ISSUE TITLE
unable to find snapshot CRDs

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#12825]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.22.2

**3. What cloud provider are you using?**

openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I am installing kops cluster to openstack and after that:

```
kubectl logs csi-cinder-controllerplugin-0 -c csi-snapshotter
```

**5. What happened after the commands executed?**

```
kubectl logs csi-cinder-controllerplugin-0 -c csi-snapshotter
...
E1124 07:51:46.654924       1 reflector.go:138] github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/factory.go:117: Failed to watch *v1.VolumeSnapshotContent: failed to list *v1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
E1124 07:52:14.774644       1 reflector.go:138] github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/factory.go:117: Failed to watch *v1.VolumeSnapshotClass: failed to list *v1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
```

However, I do see these crds - but is something misconfigured?

```
% kubectl get crd|grep volumesnapsho
volumesnapshotclasses.snapshot.storage.k8s.io         2021-02-02T15:58:21Z
volumesnapshotcontents.snapshot.storage.k8s.io        2021-02-02T15:58:21Z
volumesnapshots.snapshot.storage.k8s.io               2021-02-02T15:58:21Z
```

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

cc @olemarkus ideas?

**Comment by olemarkus** [comment]
Did you install the snapshot addon? https://kops.sigs.k8s.io/addons/#snapshot-controller

**Comment by zetaab** [comment]
@olemarkus no?

**Comment by olemarkus** [comment]
You need that one for snapshotter. The CRDs are here:
https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/snapshot-controller.addons.k8s.io/k8s-1.20.yaml.template#L10

**Comment by zetaab** [comment]
@olemarkus is that common for all cloudproviders?

**Comment by olemarkus** [comment]
Yes. Or more correctly, it is common across all CSI providers.

**Comment by zetaab** [comment]
great to learn new
