### ISSUE TITLE
brew install head seems to produce broken installation

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1283]
Install from head on brew seems to produce a kops tool that is still passing `configure-cbr0`, despite apparently having a version of `Version git-789bfcf0`.  That shouldn't be possible, AFAICT

**Comment by blakebarnett** [comment]
This was also an upgrade from k8s 1.4.6 to 1.5.1, a rolling-update was used to push out the change.

**Comment by justinsb** [comment]
I actually think this was #1287 ... some lingering cases where we do pass ConfigureCBR0!  Sorry & hopefully that'll fix it when it merges (if not, we can reopen)
