### ISSUE TITLE
e2e-kops-do-calico e2e test is failing

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#12841]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master branch

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.21.7

**3. What cloud provider are you using?**

digitalocean

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Examine results of the e2e-kops-do-calico periodic test

**5. What happened after the commands executed?**

It appears to be having problems creating loadbalancers.

**6. What did you expect to happen?**

test should pass

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-do-calico/1464216058628935680

/area provider/digitalocean
/cc @srikiz

**Comment by johngmyers** [comment]
Also, any particular reason this test is pinned on k8s 1.21?

**Comment by srikiz** [comment]
> est is pinned on k8s 1.

Thanks. I don't think it's needed. I'll go ahead and remove that.
