### ISSUE TITLE
Update build to use Bazel

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1285]
@grillz are you able to assist with this??  I know you love some bazel :)

**Comment by Grillz** [comment]
@chrislovecnm I would love nothing more, if I wasn't totally swamped this week. If it can wait a bit I'll get into it

**Comment by chrislovecnm** [comment]
That is why I pinged you amigo.  I know you are slammed.  When you can.

**Comment by kris-nova** [comment]
Why are we switching to bazel?

What are we hoping to gain/fix from the move?

How will we know when the move is done?

What will we do if the move breaks?

**Comment by chrislovecnm** [comment]
> Why are we switching to bazel?

Core is switching, and it has advantages.

> What are we hoping to gain/fix from the move?

Speed for builds, conformatity with core, smaller containers for protokube and dnscontroller

> How will we know when the move is done?

Will have alternative build targets

> What will we do if the move breaks?

We are going to start by providing alternative build targets for bazel.  Then let that mature, then switch.

**Comment by chrislovecnm** [comment]
@stealthybox can you assist with this?

**Comment by stealthybox** [comment]
I can attempt this. 
It's a new domain for me.

**Comment by chrislovecnm** [comment]
@zmerlynn do we have any info how we setup bazel in core?  Is bazel ready for kops?

**Comment by chrislovecnm** [comment]
@stealthybox your call :)  Let me know what you want to take on.

**Comment by chrislovecnm** [comment]
This is pending until they get this implemented: https://github.com/bazelbuild/rules_go/issues/70

**Comment by chrislovecnm** [comment]
Closing as this is in flight
