### ISSUE TITLE
Determine supported topologies for IPv6

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#12886]
Per a discussion of IPv6 and subnets, I have created a taxonomy of topologies that appear to make sense.

From here we should decide which of these we want to support with managed subnets. The more specialized or obscure ones can be declared as only supportable through using shared subnets.

# IPv4 topologies (NonMasqueradeCIDR is IPv4)

## 1. "public"

IPv4-only subnets, type "public"
Instances get public IPv4 addresses
Instances get private IPv4 addresses
Load balancers placed in subnet
Egress to Internet Gateway

Use cases:
- Test clusters
- Other low-security environments
- Don't want to pay for NAT Gateway

## 2. "private"

IPv4-only subnets, two types:

- "utility"
  Contain load balancers and NAT Gateway
  Do not contain nodes
  Egress to Internet Gateway
- "private"
  Contain nodes
  Instances get private IPv4 addresses
  Egress to NAT Gateway in utility subnet for AZ

Advantages over (1):
- No direct ingress to nodes from public internet

Disadvantages over (1):
- More complicated
- Pay for NAT Gateway

Use cases:
- Don't want nodes to be directly exposed to public internet

## 3.

Same as (2) except no utility subnets
No NAT Gateway

Advantages over (2):
- Simpler
- No need to pay for NAT Gateway

Use cases:
- No need for ingress from or egress to public internet

## 4. What EKS supports

IPv4-only subnets, types "public" and "private"
Like (2), but nodes can be created in the "public" subnet
NAT Gateway and load balancers are placed in the "public" subnet

Use cases:
- Some workloads need direct ingress from public internet
- Only some workloads need public internet egress, in which case NAT
gateway can be omitted

# IPv6 topologies (NonMasqueradeCIDR is IPv6)

## 10. IPv6 analogue to "public"

Subnets are dual-stack, type "public"
Instances get IPv6 addresses
Instances get public IPv4 addresses
Instances get private IPv4 addresses
Load balancers and NAT Gateway placed in subnet
Egress to Internet Gateway
Route NAT64 prefix to NAT Gateway

Use cases:
- Test clusters
- Other low-security environments

## 11.

Same as (10) but without NAT Gateway

Use cases:
- No need for pods to egress to IPv4

## 12.

Two types of subnets:

- "utility" subnets
  Dual-stack
  Contain load balancers and NAT Gateway
  Do not contain nodes
  Egress to Internet Gateway
- "private"? subnets
  IPv6-only
  Contain nodes
  Instances get IPv6 addresses only
  NAT64 egress to NAT Gateway in utility subnet for AZ
  Other IPv6 egress to Egress-only Internet Gateway

Advantages over (10):
- No direct ingress to nodes from public internet
- No need to assign IPv4 addresses to nodes

Advantages over (2):
- No need to assign IPv4 addresses to pods or nodes
- Allows IPv6 ingress and egress

Use cases:
- Private IPv4 space is exceedingly scarce

## 13.

Same as (12) except private subnets are dual-stack

Private subnets egress IPv4 and NAT64 to NAT Gateway in utility subnet for AZ

Advantages over (12):
- Traffic from nodes or host-network pods to private IPv4 addresses
doesn't have to go through NAT

Advantages over (2):
- Don't need IPv4 addresses for pods, which greatly outnumber nodes

Disadvantages over (12):
- Need to assign an IPv4 addresss per node

Use cases:
- Private-IPv4-only container registry, file repository, or other services accessed from nodes

## 14.

Same as (12) except no NAT Gateway

Use cases:
- No need for IPv4 egress

## 15.

Same as (12) except utility subnet is IPv6-only

No NAT Gateway

Use cases:
- No need for IPv4 ingress or egress

## 16.

Dual-stack "public" subnet and IPv6-only "private" subnet
Like (4) but IPv6
Like (12) but nodes can be created in the "public" subnet

Use cases:
- Some workloads need direct ingress from public internet

## 17.

IPv6-only "public" and "private" subnets

No NAT Gateway

Use cases:
- Some workloads need direct ingress from public internet, no need for IPv4 ingress or egress

## 18.

(12) but with an additional type of subnet:

- "private-dualstack"? subnets
  Dual-stack
  Contain nodes
  IPv4 and NAT64 egress to NAT Gateway in utility subnet for AZ
  Other IPv6 egress to Egress-only Internet Gateway

Use cases:
- NLB doesn't support instance targets with ipv6 addresses, so we cannot attach a target group to ASGs. So nodes, such as control plane nodes, needing NLBs in front go in the dual-stack subnet.

**Comment by johngmyers** [comment]
I will say that I'm most interested in (13), but that's because our container registry is IPv4-only and we have enough net-10 space such that assigning IPv4 addresses to nodes is not a problem. Longer term, (12) makes more sense.

We create shared subnets, so wouldn't mind if managed subnets don't support (13).

**Comment by olemarkus** [comment]
I am wondering if we can do a KEP-like PR for the document above. This discussion may become very threaded and it would be easier to comment line by line rather than as plain comments.

That being said:
* 12 is the big one for me. Not only because we may exhaust the private range, but also because the private range needs management across VPCs, accounts etc. If one does an acquisition one tends to be out of luck trying to get things to talk on the private range.
* 13 I agree this is more feasible short-term. Going from 13 to 12 should also be possible as the cluster config itself can be the same. I argue that for 13, we should try to get etcd, (internal) api server and all other aspects of the cluster itself to be on IPv6. I plan on doing some PRs for that already.

For 16 and 17 one has to keep in mind that not only are the nodes available publicly. The pods are too. SGs probably does not handle the granularity of the rules needed for such a setup and would probably need an AWS Network Firewall VPC ingress. I suggest we do not support this as managed.

**Comment by olemarkus** [comment]
For 12, we need three types of subnets for the time being
* utility as above
* private (or really, ipv6-only)
* dualstack, but with nodes (and behind egress-only gateway): ELBv2 doesn't support instance targets with ipv6 addresses, so we cannot attach a target group to ASGs. This makes API ingress hard for us.

I think we should support a managed case where master nodes are in dualstack subnets, while nodes are in ipv6-only.

**Comment by johngmyers** [comment]
I assigned (18) to the both-ipv6only-and-dualstack-private topology.

**Comment by johngmyers** [comment]
I think we can take as a design simplification that, in the context of IPv6 clusters, public and utility subnets are dual-stack.

The cases for v6-only public and utility subnets seem pretty niche. To be useful, one would have to be able to have all external clients be v6-capable and the cloud would have to charge for the first public IPv4 per instance.

Does anyone disagree?

**Comment by olemarkus** [comment]
I agree. As long as there is a need for NAT64, utility/public has to be dualstack and that will be needed for a long, long time.

**Comment by hakman** [comment]
I agree also.

**Comment by johngmyers** [comment]
I believe the cases where various types of egress aren't needed are essentially about fine-tuning the routing. I think we can defer that question.

That leaves the issue of needing both IPv6-only and dual-stack private subnets. The primary need for dual-stack private subnets appears to be because NLB doesn't support IPv6-only instance targets. I wasn't able to find this limitation documented, so I'm concerned the need might go away if AWS later adds this support.

I think the `SubnetType` `private` should be IPv6-only and there should be a new `SubnetType` for dual-stack private subnets. I propose the name `dualstack`, though `private-dualstack` is another option. Any other suggestions?

**Comment by olemarkus** [comment]
The limitation is here: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html
See under IP address type -> considerations.

You will have difficulties running control plane with ipv6-only subnets.
