### ISSUE TITLE
Files required to run kops toolbox template

### ISSUE THREAD

**Issue by pgouda89** [kubernetes/kops#12903]
We are trying to use the **kops toolbox template** in one of our cloud solutions. We want to package only dependencies required to run the kops toolbox template command as we are not using Kops for Kubernetes cluster creation. 

Do you know how to achieve the same? Packaging entire Kops libraries is an issue for us as it increases our cloud package size. 

Has anyone used the kops toolbox template command standalone? If yes can you please share the dependency list?

**Comment by olemarkus** [comment]
The kops-specific template functions require a good portion of those libraries. If you do not want all those you can just use plain go template instead.

**Comment by olemarkus** [comment]
/kind support

You can use any template rendering. jinja or quicktemplate or twig or whatever. The cluster spec is in the end just a yaml file.
