### ISSUE TITLE
Define more secure roles to machines in GCE

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#12912]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Currently we insert serviceaccount by default to kOps. This means that each instance is going to have "full access" to everything inside GCE.

Lets imagine that we have application running in node that has vulnerability. Currently in theory it is possible that attacker will get "full-access" to GCE itself using serviceaccount which is attached by default to node.

**2. Feel free to provide a design supporting your feature request.**

 Instead of having full access, I would like to see similar roles that AWS has if possible. So in masters and nodes we should have own different serviceaccounts(?). By that way we could make the setup much more secure.

cc @justinsb

**Comment by zetaab** [comment]
looks like justin doing it in https://github.com/kubernetes/kops/pull/12949

**Comment by justinsb** [comment]
Thanks for raising this @zetaab ... we now have separate roles per instancegroup role, so control-plane and nodes are separate service accounts.   

Currently control-plane gets the GKE role: roles/container.serviceAgent, and nodes get roles/compute.viewer.

https://github.com/kubernetes/kops/blob/43027b999863a0ad0cee65b2b2d34a01da8d5982/pkg/model/gcemodel/service_accounts.go#L92-L128

It is possible that we need to give the control-plane a more powerful role, and the GKE role is technically a node role I believe.  We'll see how the e2e tests go!

We do additionally grant permissions to some GCS buckets, but if we run with the kops-controller as bootstrap I believe the nodes should not need any additional permissions: https://github.com/kubernetes/kops/blob/43027b999863a0ad0cee65b2b2d34a01da8d5982/pkg/model/gcemodel/storageacl.go
