### ISSUE TITLE
Use a 1.23-based AWS CCM with k8s 1.23.x

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#12940]
After AWS CCM cuts a release for use with k8s 1.23 (kubernetes/cloud-provider-aws#294), use that instead of the `latest` tag for k8s 1.23.x

**Comment by zetaab** [comment]
same applies to other cloudproviders like OpenStack, usually there is 2-3 weeks delay after k8s release when they will publish release

**Comment by johngmyers** [comment]
Fixed by #13144 
/close
