### ISSUE TITLE
Add support for using a pre-existing AWS routing table when networking mode is NOT kubenet

### ISSUE THREAD

**Issue by relaxdiego** [kubernetes/kops#1301]
It'd be useful for some users to be able to specify a pre-existing routing table in addition to the VPC and network CIDR when using a networking mode other than kubenet. For example:

```
kops create cluster --zones us-west-2a \
  --networking calico \
  --vpc vpc-296a8456 \
  --network-cidr 172.29.0.0/16 \
  --routing-table rtb-6600c123 \
  --name mycluster.mydomain.com
```

This will be very useful for AWS accounts where the permissions need to be kept under tight control (e.g. not allowed to create/delete routing tables, among other things, on the fly).

**Comment by chrislovecnm** [comment]
@justinsb are we able to specify this in the API now?

**Comment by chrislovecnm** [comment]
@relaxdiego I like the idea.  I would recommend that it not be yet another flag :)  We could specify this with an edit to the cluster, or use yaml with a `create -f`.  If you are able to contribute this feature please reach out!

**Comment by relaxdiego** [comment]
Thanks, @chrislovecnm! It looks like our need for this is no longer as high-priority as originally thought. However, I'd love to work on it anyway if only to familiarize myself with the codebase. Will definitely ping you on Slack once I'm ready!

**Comment by chrislovecnm** [comment]
@relaxdiego we have open office hours as well, please swing by!  We also have labels on help wanted.  Do you want to close this out?

**Comment by relaxdiego** [comment]
@chrislovecnm Thanks again! I'll close this in the meantime.
