### ISSUE TITLE
require --yes flag before auto-deleting a ig (feature req)

### ISSUE THREAD

**Issue by gladiatr72** [kubernetes/kops#1302]
/sigh

It would be splendid if `kops delete ig ..` would give the user the "here's what will happen--please use `--yes` to make it so" like the other things.

Then ... erm... idiots like me would not inadvertently delete their cluster master node group while trying to do too many things at once.

**Comment by chrislovecnm** [comment]
Yikes!  Yes, we should have that....  If you are able to contribute, we would welcome the help!

**Comment by frodopwns** [comment]
I can take a crack at this.

**Comment by frodopwns** [comment]
@kris-nova @chrislovecnm 

While adding this functionality should I go ahead and add confirmations to the `delete cluster` and `delete service` subcommands as well?

**Comment by kris-nova** [comment]
@frodopwns yes please :)

**Comment by chrislovecnm** [comment]
@frodopwns for extra credit unit tests would be AMAZING

**Comment by jaygorrell** [comment]
@frodopwns Quick question about the implementation path. Is it not possible to roll the delete into a standard `kops update --yes`? The main reason I ask is that Terraform users will still want to delete the IG to update the cluster state information and then do a `kops update --out=terraform` to get updated TF files... expecting to do the actual delete when applying there.
