### ISSUE TITLE
etcd manager ETC_LOG_LEVEL  env variable not working as expected

### ISSUE THREAD

**Issue by bharathnoddy** [kubernetes/kops#13058]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 1.20.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
v1.16.14

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

` ``   - encryptedVolume: true
      instanceGroup: XXXxxxxxx
      kmsKeyId: xxxxxxxxxxxxxxxxxxxxxxxxxx
      name: c
    manager:
      env:
      - name: ETCD_LOGGER
        value: zap
      - name: ETCD_LOG_LEVEL
        value: error
    name: main
    version: 3.4.13```

Added this config to restrict etcd log level to error 

**5. What happened after the commands executed?**
No change in the log level and etc-manager-events and etc-manager-main are still logging all INFO logs

**6. What did you expect to happen?**
etc-manage-events and etc-manager-main   should log only errors and above

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
Kop upgrade did show me this
```
W1230 10:41:39.896945    3898 model.go:507] overloading ENV var in manifest (embedded etcd manifest) with ETCD_LOGGER=zap
W1230 10:41:39.896968    3898 model.go:507] overloading ENV var in manifest (embedded etcd manifest) with ETCD_LOG_LEVEL=error
W1230 10:41:39.897780    3898 model.go:507] overloading ENV var in manifest (embedded etcd manifest) with ETCD_LOGGER=zap
W1230 10:41:39.897798    3898 model.go:507] overloading ENV var in manifest (embedded etcd manifest) with ETCD_LOG_LEVEL=error
```

**9. Anything else do we need to know?**

**Comment by olemarkus** [comment]
Kops doesn't do anything with that variable. You need to file that bug with https://github.com/kubernetes-sigs/etcdadm/

**Comment by bharathnoddy** [comment]
https://github.com/kubernetes/kops/issues/7946 
this issue was closed with the mentioned solution which apparently does not work. I will raise a bug with etcdadm as well

**Comment by bharathnoddy** [comment]
the comments in the other issue[ #7946](https://github.com/kubernetes/kops/issues/7946) was misleading. I have managed to solve the issie with the blow kops config
```` `` - encryptedVolume: true
instanceGroup: XXXxxxxxx
kmsKeyId: xxxxxxxxxxxxxxxxxxxxxxxxxx
name: c
manager:
      logLevel: 1
value: error
name: main
version: 3.4.13``````

Closing it
