### ISSUE TITLE
kOps 1.22 delete secret regression

### ISSUE THREAD

**Issue by yurrriq** [kubernetes/kops#13077]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

> 1.22.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

> 1.22.3

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops delete secret sshpublickey admin
kops delete secret sshpublickey admin --name my-cluster.example.com
env KOPS_CLUSTER_NAME=my-cluster.example.com kops delete secret sshpublickey admin
````

**5. What happened after the commands executed?**

> Error: clusterName: Required value: Cluster name is required

**6. What did you expect to happen?**

Delete the secret.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: my-cluster.example.com
spec:
  sshKeyName: ""
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
I0103 09:14:53.753181  262083 factory.go:68] state store s3://my-state-store
Error: clusterName: Required value: Cluster name is required
```

**9. Anything else do we need to know?**
It works on 1.21.2, for example.

**Comment by johngmyers** [comment]
The command is `kops delete sshpublickey`. Public keys are not secrets.

**Comment by yurrriq** [comment]
I see, thanks. Looks like that happened in https://github.com/kubernetes/kops/pull/12045, yeah? I've confirmed `kops delete sshpublickey` works as expected with 1.22.2.
