### ISSUE TITLE
kops1.23 cluster autoscaler and nothing can connect to API server

### ISSUE THREAD

**Issue by alok87** [kubernetes/kops#13080]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
$ kopsb version
Version 1.23.0-beta.1 (git-473018f64ffd2e368d31d608479355d15cddb0d3)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.23.1

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster
kops edit cluster (change OIDC credential)
kops rolling update cluster
(the cluster could not validate as CA, metrics, server, cert manager stopped connecting to API server)
```
I0105 08:56:00.160261       1 main.go:401] Cluster Autoscaler 1.23.0
F0105 08:56:03.220707       1 main.go:430] Failed to get nodes from apiserver: Get "https://100.64.0.1:443/api/v1/nodes": dial tcp 100.64.0.1:443: connect: no route to host
goroutine 1 [running]:
```

## Debugging I did:
I am able to to do telnet to 100.64.0.1 443 from
- other pods in the cluster
- from the kubernetes master node

But somehow these components are not able to connect to API server after the rolling update of cluster.
Please suggest.

**Comment by olemarkus** [comment]
Hey. Can you follow the bug template and provide necessary details such as the cluster spec?
