### ISSUE TITLE
Segmentation Violation with 'kops get instances -o json'

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#13105]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.22.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.22.4

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops get instances --name cluster.example.com -o json

**5. What happened after the commands executed?**
Segmentation Violation

**6. What did you expect to happen?**
Output in JSON

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

https://gist.github.com/blakebarnett/5b6abd3be5b2f63bdf11699b3a136b03

**9. Anything else do we need to know?**
This only happens with `get instances -o json|yaml`

**Comment by blakebarnett** [comment]
I suspect this is because I have `warmPool` enabled with instances in the `stopped` state. It has complained about this during cluster validation also.

**Comment by olemarkus** [comment]
Thanks for finding this. Problem is that the function populating the json object assumed all instances have a node. Those that are booting up, or that are in the warm pool do not have one yet, so it errors out.
