### ISSUE TITLE
Port requirements for calico & weave

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1311]
We are locking down security groups in 1.5.  In particular, from nodes to masters.

Which ports does calico need open?

Which ports does weave need open?

Do you know @chrislovecnm ?

**Comment by elliot** [comment]
For Weave:

  - TCP 6783 
  - UDP 6783 + 6784

Source: [FAQ](https://www.weave.works/docs/net/latest/faq/)

**Comment by chrislovecnm** [comment]
Already fix in master - closing
