### ISSUE TITLE
Upgrade cluster

### ISSUE THREAD

**Issue by Sg-23** [kubernetes/kops#13122]
I have a pre-prod cluster running on v1.8.4 , I need to upgrade to 1.16.x for now, what should be the approach? 
I tried setting up cluster for test on v1.8 but it fails due to docker error related to fetching from apt.docker.org which has been removed. I am able to setup cluster with v1.11.10 for test. Should I upgrade pre-prod to 1.9.x first and then similarly one minor version at a time or directly to v1.11.10 and then one minor version at a time from v1.8.4 ?

**Comment by olemarkus** [comment]
For kops you can use the latest version that supports 1.9, but for k8s, you need to go one by one.

**Comment by Sg-23** [comment]
okay thanks,
