### ISSUE TITLE
Should we lock down bastion -> master ports?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1312]
Should a bastion we able to access the master freely, or is it expected that we should SSH from the bastion to the master?

In particular, thinking about etcd access.

**Comment by chrislovecnm** [comment]
We need lock down etcd.

**Comment by kris-nova** [comment]
Agree.

This issue involves the security group between the bastion ASG and the master's ASG, we need to only allow one way TCP on 22 for SSH
