### ISSUE TITLE
upgrading cluster using kops

### ISSUE THREAD

**Issue by Sg-23** [kubernetes/kops#13140]
I had provisioned a cluster using kops terraform on v1.8
Now when I am trying to update to v1.9.11 and I'm getting the below warning on rolling-update and nothing to update:

W0121 17:20:33.440836   68583 aws_cloud.go:395] Found ASG with no corresponding instance group "applications-nodes"
NAME    STATUS  NEEDUPDATE      READY   MIN     MAX     NODES

No rolling-update required.

----
What can be the possible problem?

**Comment by olemarkus** [comment]
Sorry this one slipped. Do you still face problems?
