### ISSUE TITLE
Outdated etcdctl certs path in Docs

### ISSUE THREAD

**Issue by jozefhalgas** [kubernetes/kops#13170]
Current documentation at https://kops.sigs.k8s.io/operations/etcd_administration/ and https://kops.sigs.k8s.io/operations/troubleshoot/ contains outdated path for etcdctl certs and key. 
 e.g.
 
 ```bash
ETCDCTL_API=3 $DIRNAME/etcdctl --cacert=/rootfs/etc/kubernetes/pki/kube-apiserver/etcd-ca.crt --cert=/rootfs/etc/kubernetes/pki/kube-apiserver/etcd-client.crt --key=/rootfs/etc/kubernetes/pki/kube-apiserver/etcd-client.key --endpoints=https://127.0.0.1:4001 get --prefix / | tee output.txt
```

**fix**

`/rootfs/etc/kubernetes/pki/kube-apiserver/` > `/rootfs/srv/kubernetes/kube-apiserver/`

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.22.3 (git-241bfeba5931838fd32f2260aff41dd89a585fba)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:41:19Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**Comment by trondhindenes** [comment]
thanks for this @jozefhalgas , you just saved me from excessive head-scratching

**Comment by olemarkus** [comment]
/reopen

Are you back on kops @trondhindenes ?
I'll get those documents fixed and verified asap

**Comment by olemarkus** [comment]
Look at the docs preview at https://github.com/kubernetes/kops/pull/14158 if this looks better.
Moved some docs around, removed some duplication, removed some parts that have not been supported for a long time.

**Comment by trondhindenes** [comment]
Thanks @olemarkus  ! I'm helping out a customer that is using kops for some of their clusters :-)
