### ISSUE TITLE
Unable to start the kubernetes cluster

### ISSUE THREAD

**Issue by PrashantGSIN** [kubernetes/kops#13179]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
When executing kops update cluster --name example.com --yes --admin getting below

I0202 05:30:29.440673    1998 executor.go:111] Tasks: 0 done / 117 total; 51 can run
W0202 05:30:29.509783    1998 vfs_castore.go:379] CA private key was not found
I0202 05:30:29.520114    1998 keypair.go:225] Issuing new certificate: "etcd-peers-ca-main"
I0202 05:30:29.525264    1998 keypair.go:225] Issuing new certificate: "etcd-manager-ca-events"
I0202 05:30:29.538340    1998 keypair.go:225] Issuing new certificate: "etcd-peers-ca-events"
I0202 05:30:29.541035    1998 keypair.go:225] Issuing new certificate: "etcd-clients-ca"
I0202 05:30:29.582053    1998 keypair.go:225] Issuing new certificate: "apiserver-aggregator-ca"
I0202 05:30:29.601713    1998 keypair.go:225] Issuing new certificate: "etcd-manager-ca-main"
W0202 05:30:29.611741    1998 vfs_castore.go:379] CA private key was not found
I0202 05:30:29.654821    1998 keypair.go:225] Issuing new certificate: "service-account"
I0202 05:30:29.704326    1998 keypair.go:225] Issuing new certificate: "kubernetes-ca"
I0202 05:30:31.401511    1998 executor.go:111] Tasks: 51 done / 117 total; 24 can run
I0202 05:30:32.419330    1998 executor.go:111] Tasks: 75 done / 117 total; 36 can run
I0202 05:30:33.666924    1998 executor.go:111] Tasks: 111 done / 117 total; 6 can run
I0202 05:30:35.457873    1998 executor.go:155] No progress made, sleeping before retrying 6 task(s)
I0202 05:30:45.458837    1998 executor.go:111] Tasks: 111 done / 117 total; 6 can run
I0202 05:30:47.968064    1998 executor.go:111] Tasks: 117 done / 117 total; 0 can run
I0202 05:30:48.328523    1998 dns.go:233] Pre-creating DNS records
I0202 05:30:48.475158    1998 update_cluster.go:326] Exporting kubeconfig for cluster
W0202 05:30:48.475230    1998 create_kubecfg.go:91] Did not find API endpoint for gossip hostname; may not be able to reach cluster
kOps has set your kubectl context to example.com

**2. Feel free to provide a design supporting your feature request.**
The DNS is internal and cloud provider is AWS. Creating the cluster over ec2 instance and the master/nodes instance type is m4.large.

**Comment by olemarkus** [comment]
Most likely, the problem is that you cannot resolve `external.com` domains from where you run the kops client. Can you check that `api.example.com` dns entry points to a valid address and that you can resolve it locally?
