### ISSUE TITLE
Kube API LB monitors missing in GCE

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#13182]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

![Screenshot 2022-02-02 at 13 27 15](https://user-images.githubusercontent.com/22482503/152145317-510c1e9b-4bb3-4dc4-a912-57b2adb2d2ea.png)

**2. Feel free to provide a design supporting your feature request.**

I would like to see similar API healthchecks than we have in another vendors like AWS

**Comment by zetaab** [comment]
it seems that GCP does not support https / tcp healthchecks for targetpools. https://cloud.google.com/compute/docs/reference/rest/v1/targetPools/addHealthCheck

![Screenshot 2022-02-03 at 11 40 52](https://user-images.githubusercontent.com/22482503/152318549-c12b17cb-6f64-4a8a-b88c-a12184838e5f.png)

only HTTP healthcheck is available and AFAIK kOps apiserver does not have any http healthcheck port?

**Comment by rifelpet** [comment]
That's the purpose of the kube-apiserver healthcheck container

https://github.com/kubernetes/kops/blob/master/cmd/kube-apiserver-healthcheck/README.md

It exposes the kube-apiserver health checks via http for load balancer health checking.

**Comment by zetaab** [comment]
@rifelpet yeah but the problem is that its not open towards internet aka to the loadbalancer? 3990 is bind to localhost only, so its not usable outside of single master
