### ISSUE TITLE
How to know which version of kops binary was used to bootstrap k8s cluster?

### ISSUE THREAD

**Issue by s0rl0v** [kubernetes/kops#13193]
Hello team,

I kind of happened to maintain k8s cluster that don't have much of documentation and want to upgrade AMIs on worker nodes. However, nobody knows which version of kops was used to bootstrap it.

Are there any options to find that? I checked state files and they don't shed any light on that...

**Comment by olemarkus** [comment]
If you need to know the kops version, look at the version of the `dns-controller` pod. It should match.
But in general, we strongly recommend using the latest kOps version (for any k8s version that is supported by latest kops version).

**Comment by s0rl0v** [comment]
@olemarkus Thank you very much!
