### ISSUE TITLE
does it support new region ap-southeast-3

### ISSUE THREAD

**Issue by YiGene** [kubernetes/kops#13214]
i got below error when i run kops on region ap-southeast-3, does the latest kops support this region?

Error: error reading cluster configuration "k8scluster.dev.example.com": error reading s3://dev-example-com-k8s-state-store/k8scluster.dev.example.com/config: ap-southeast-3 is not a valid region
Please check that your region is formatted correctly (e.g. us-east-1)

how go check which region kops support?

**Comment by dorabhai** [comment]
Even I got the same error, please provide a fix

**Comment by jinhong-** [comment]
It does not support ap-southeast-3, at least not out of the box. I already submitted PR #13132 that hopefully will resolve this but it will be for release v1.24. In the meantime, this is what you can try to have it work. The technique is to try to bypass the validation, which means to provide a "custom" S3 endpoint. I personally used ap-southeast-1 to house the kops configuration files, feel free to change it to whichever region of your choice (ap-southeast-3) may or may not work (did not test this)

Using "custom" S3 endpoints will bypass validation, thus successfully loading your cluster. Hope this helps

```
export S3_ENDPOINT=s3.ap-southeast-1.amazonaws.com
export S3_REGION=ap-southeast-1
export S3_ACCESS_KEY_ID=
export S3_SECRET_ACCESS_KEY=
```

**Comment by dorabhai** [comment]
Thank you @jinhong- The above solution works well...

**Comment by akhmadfld** [comment]
> Thank you @jinhong- The above solution works well...
Do you have any issues for creating cluster on ap-southeast-3 region?
