### ISSUE TITLE
Default bastion public DNS name should be generated from dns zone

### ISSUE THREAD

**Issue by itskingori** [kubernetes/kops#1322]
**Some context:**

We now [have this][1] 👇🏽 ... which builds the DNS entry name for the bastion ...

```
// Default to a DNS name for the bastion
cluster.Spec.Topology.Bastion = &api.BastionSpec{
    BastionPublicName: "bastion-" + clusterName,
}
```

... but with kops, [if you don't specify a dns-zone, kops will][2] ...

> ... list all your hosted zones, and choose the longest that is a a suffix of your cluster name. So for `dev.kubernetes.example.com`, if you have `kubernetes.example.com`, `example.com` and `somethingelse.example.com`, it would choose `kubernetes.example.com`. `example.com` matches but is shorter; `somethingelse.example.com` is not a suffix-match.

... so we can see that with kops the expectation is that the pattern is something like `--name=dev.kubernetes.example.com` and `--dns-zone=kubernetes.example.com`. Or at least that's what the docs say and probably what most people will follow.

**The problem I'm having:**

I kinda deviated a bit. My cluster name is not a subdomain of `dns-zone`. So ... let's say I want to have a cluster set to `kubernetes.example.com` and set my DNS zone to `kubernetes.example.com` ... then I do something like this:

```
$ kops create cluster \
  --name=kubernetes.example.com \
  --bastion=true \
  --cloud=aws \
  --dns-zone=kubernetes.example.com \
  --out=. \
  --target=terraform \
  --topology=private \
  ...
$ terraform apply
```

... then I get this error ...

```
[ERR]: Error building changeset: InvalidChangeBatch: RRSet with DNS
name bastion-kubernetes.example.com. is not permitted in zone
kubernetes.example.com.
```

**What I think:**

1. I'm wondering if we should be building the DNS entry from `dns-zone` which is really the name of the hosted zone that kops will use?
2. The cluster name could be anything really, the only part of it we are guaranteed of is it's suffix i.e. `dns-zone`.
2. And ... this i.e. the hosted zone, is probably where most people would like the bastion's DNS entry to be in?
3. Seems more appropriate for the bastion DNS entry to be a subdomain in the `dns-zone` hosted zone.

IMHO.

[1]: https://github.com/kubernetes/kops/blob/8b21ace32dd0871b4d085b3120283e69d4d3a1df/cmd/kops/create_cluster.go#L477-L479
[2]: https://github.com/kubernetes/kops/blob/8b21ace32dd0871b4d085b3120283e69d4d3a1df/docs/arguments.md#dns-zone

**Comment by itskingori** [comment]
Created [a PR with a potential fix][1].

[1]: https://github.com/kubernetes/kops/pull/1323

**Comment by justinsb** [comment]
What do you think @kris-nova?  `bastion.<clustername>` actually feels more natural to me - just like we have `api.<clustername>`

**Comment by itskingori** [comment]
> ... `bastion.<clustername>` actually feels more natural to me - just like we have `api.<clustername>`

I'd like to take it a step further and suggest we use `<dns-zone>` as the suffix instead of `<clustername>`.

`<clustername>` is by default assumed to be a sub-domain in `<dns-zone>` (unless you override that behaviour by setting `--dns-zone`) since kops chooses the longest that is a suffix of your cluster name.

I [haven't got that working quite yet though][1] but I think I can figure it out with some help.

[1]: https://github.com/kubernetes/kops/pull/1323#pullrequestreview-14984179

**Comment by justinsb** [comment]
> I'd like to take it a step further and suggest we use <dns-zone> as the suffix instead of <clustername>.

I don't really understand why?  dns-zone is an identifier for your hosted zone, so it could be example.com or even an ID like ABCDEFG123 or maybe in future something like `dyndns://accountid/zoneid`.  We don't want to use dns-zone when it is an ID.  But we also don't want to use it when it is a suffix, or else if we have two clusters `cluster1.example.com` and `cluster2.example.com`, we might end up with both bastions as `bastion.example.com`

**Comment by itskingori** [comment]
@justinsb ...

> We don't want to use dns-zone when it is an ID. But we also don't want to use it when it is a suffix, or else if we have two clusters `cluster1.example.com` and `cluster2.example.com`, we might end up with both bastions as `bastion.example.com`.

Ok. I see your point. 🤔

**Comment by itskingori** [comment]
https://github.com/kubernetes/kops/pull/1364 by @kris-nova fixes the error I was getting here and [new docs on bastion][1] show you how to change it to `bastion.<clustername>` ... which is what I wanted so no longer an issue.

[1]: https://github.com/kubernetes/kops/blob/dfed37e44c12a7390c7aba6d9e2175508ac41453/docs/bastion.md
