### ISSUE TITLE
Difference between README and Website about the supported Cloud providers

### ISSUE THREAD

**Issue by sfenman** [kubernetes/kops#13226]
/kind documentation

There is a discrepancy between kops website and README.md about which Cloud providers are supported. Quoted from website:

> [AWS](https://kops.sigs.k8s.io/getting_started/aws/) (Amazon Web Services) is currently officially supported, with [DigitalOcean](https://kops.sigs.k8s.io/getting_started/digitalocean/) and [OpenStack](https://kops.sigs.k8s.io/getting_started/openstack/) in beta support, and [Azure](https://kops.sigs.k8s.io/getting_started/azure/), and [GCE](https://kops.sigs.k8s.io/getting_started/gce/) in alpha.

While on README:

> AWS (Amazon Web Services) is currently officially supported, with DigitalOcean, GCE, and OpenStack in beta support, and Azure and AliCloud in alpha.

**Comment by wangli1030** [comment]
Hi, if I want to update it, which one I should follow?

**Comment by olemarkus** [comment]
Hey. The docs is the correct one.

**Comment by sxt90128** [comment]
Hi, I can work on this.
