### ISSUE TITLE
kops get instances segFaults 

### ISSUE THREAD

**Issue by heybronson** [kubernetes/kops#13250]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`kops 1.22.3`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`kubectl 1.23.3`

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops get instances`

**5. What happened after the commands executed?**
```
I0214 18:20:41.949503    3245 featureflag.go:166] FeatureFlag "ExperimentalClusterDNS"=true
W0214 18:20:46.123556    3245 aws_cloud.go:893] ignoring instance as it is terminating: i-0777a40becdf80584 in autoscaling group: <REDACTED>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x3be1c03]
goroutine 1 [running]:
main.asRenderable(0xc001430a00, 0x1b, 0x20, 0x0, 0x0, 0x0)
    cmd/kops/get_instances.go:220 +0xc3
main.RunGetInstances(0x555cb30, 0xc00005c080, 0xc00000d938, 0x5508920, 0xc00000e018, 0xc000ae4240, 0x0, 0x0)
    cmd/kops/get_instances.go:149 +0xa32
main.NewCmdGetInstances.func1(0xc000b0fb80, 0xc000ac5800, 0x0, 0x4, 0x0, 0x0)
    cmd/kops/get_instances.go:76 +0x5d
[k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute](http://k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute)(0xc000b0fb80, 0xc000ac57c0, 0x4, 0x4, 0xc000b0fb80, 0xc000ac57c0)
    vendor/github.com/spf13/cobra/command.go:856 +0x472
[k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x77d3c20](http://k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x77d3c20), 0x7823340, 0x0, 0x0)
    vendor/github.com/spf13/cobra/command.go:974 +0x375
[k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(...)](http://k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(...))
    vendor/github.com/spf13/cobra/command.go:902
main.Execute()
    cmd/kops/root.go:95 +0x8f
main.main()
    cmd/kops/main.go:20 +0x25
```

**6. What did you expect to happen?**
The usual output of `kops get instances`

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

N/A

**Comment by olemarkus** [comment]
This isn't a duplicate of https://github.com/kubernetes/kops/issues/13105?

**Comment by heybronson** [comment]
Yeah this seems to be a duplicate. Closing
