### ISSUE TITLE
kops rolling-update aborts with a cluster validation error despite cluster validation succeeding

### ISSUE THREAD

**Issue by danports** [kubernetes/kops#13297]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.22.4 (haven't seen this behavior on 1.22.3 and earlier versions)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.21.9 & 1.22.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops rolling-update cluster --validation-timeout 30m --yes`

**5. What happened after the commands executed?**

At the end of the rolling update, kops barfed:
```
I0221 22:11:49.983293    2851 instancegroups.go:435] waiting for 15s after terminating instance
I0221 22:12:04.984296    2851 instancegroups.go:468] Validating the cluster.
I0221 22:12:08.003422    2851 instancegroups.go:504] Cluster validated; revalidating in 10s to make sure it does not flap.
I0221 22:12:20.493033    2851 instancegroups.go:501] Cluster validated.
Error: error validating cluster after detaching instance: cluster did not validate within a duration of "30m0s"
```
When I reran `kops rolling-update cluster`, it picked up where it left off. This happened on two different rolling updates today, which is why I suspect this might be a bug and not a flake.

**6. What did you expect to happen?**

I expected kops to complete without barfing. The error message doesn't make sense to me since the output doesn't show any validation errors before the abort.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Will add later if needed.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Will add later if needed.

**9. Anything else do we need to know?**

Nothing else that occurs to me.

**Comment by olemarkus** [comment]
This doesn't show up on e2e or when I have been testing upgrades.
Can you share which kops version you upgraded from?
Also the from/to cluster specs (if there are changes besides the k8s version).

That the kops first validates the cluster, then fails validation sounds strange. Wondering if there is another error being swallowed in there.

**Comment by heybronson** [comment]
+1 seeing the same issue here with long running kops rolling-update operations.

```
I0228 22:32:52.653529    1021 instancegroups.go:505] Cluster validated; revalidating in 10s to make sure it does not flap.
I0228 22:33:15.191430    1021 instancegroups.go:502] Cluster validated.
I0228 22:33:15.191484    1021 instancegroups.go:399] Draining the node: "ip-172-28-128-80.us-west-2.compute.internal".
Error: error validating cluster after terminating instance: cluster did not validate within a duration of "15m0s"
```

**Comment by danports** [comment]
My guess (with really no evidence yet) is that this may have something to do with `rollingUpdate.maxSurge` being set to a value > 1 on some of my instance groups. I've seen bizarre output from kops in the past (including on versions earlier than 1.22.4) where validation messages were being output at unexpected times (I'll see if I can track down the runs I saw this in), so I suspect some kind of multithreading/race condition here. Do the e2e tests check `rollingUpdate.maxSurge > 1`?

To be clear, this error does not appear only when doing a rolling update for a kops upgrade - it's happened on other rolling updates too. I haven't been able to reproduce it on kops 1.23.x yet, but I also haven't done that many rolling updates with the newer version yet.

**Comment by danports** [comment]
I have been unable to reproduce this on 1.23.x after 10-20 rolling updates. Not sure yet if the problem was fixed in 1.23.x or if it's just more rare than I thought. @heybronson Have you seen this on 1.23.x?

**Comment by danports** [comment]
Haven't seen this on 1.23.x or 1.24.x after a few dozen rolling updates, so I'm content to close this unless @heybronson thinks the bug is still alive.

**Comment by danports** [comment]
Can't reproduce this issue anymore - will reopen if I see it again.
