### ISSUE TITLE
ability to provide alternate path for public key

### ISSUE THREAD

**Issue by goblain** [kubernetes/kops#133]
`F0713 14:34:32.724976    1387 create_cluster.go:50] error reading SSH key file "/home/goblin/.ssh/id_rsa.pub": open /home/goblin/.ssh/id_rsa.pub: no such file or directory
`
I use ssh agent and have no key in default path, so it would be nice to have a flag for it like `--ssh-public-key`. Not a big deal though :)

**Comment by justinsb** [comment]
There actually is a flag `--ssh-public-key` on the create command :-)

I _think_ it should be working - can you let me know if there are any issues.

I think technically we could also get the public key from the SSH agent (https://godoc.org/golang.org/x/crypto/ssh/agent), except that if you have multiple keys it's going to be hard to specify which one you want.  It is probably going to be easier just to make sure you have the public key in a file and pass the location in.

**Comment by goblain** [comment]
ok, so I guess it's just not mentioned in the readme :)

**Comment by scottstensland** [comment]
beautiful thing about kube-up.sh  is that once a successful login to AWS has happened using 

```
export             AWS_ACCESS_KEY_ID=$(cat ${AWS_ACCOUNT_CONFIGDIR}/id)
export  AWS_SECRET_ACCESS_KEY=$(cat ${AWS_ACCOUNT_CONFIGDIR}/key)

aws ecr get-login --region ${AWS_REGION} 
```

later when calling kube-up.sh it will automatically deal with public/private ssh keys as per

```
kube-up.sh
...
STATEMENT   sts:AssumeRole  Allow
PRINCIPAL   ec2.amazonaws.com
INSTANCEPROFILE arn:aws:iam::064066309977:instance-profile/kubernetes-minion    2016-07-06T15:46:02Z    AIPAJY6ROOGM4OX4MIBUC                               kubernetes-minion   /
ROLES   arn:aws:iam::064066309977:role/kubernetes-minion    2016-07-06T15:46:01Z    /   AROAJJSIGFI2UHIZBUL5S   kubernetes-minion
ASSUMEROLEPOLICYDOCUMENT    2012-10-17
STATEMENT   sts:AssumeRole  Allow
PRINCIPAL   ec2.amazonaws.com
Generating public/private rsa key pair.
Your identification has been saved in /home/stens/.ssh/kube_aws_rsa.
Your public key has been saved in /home/stens/.ssh/kube_aws_rsa.pub.
The key fingerprint is:
SHA256:vMrnyJe4B6Hf9p/uvqxD521pVs4cB2zYOgRPljt7M4Q stens@mail.emptyadjacentpossible.com
The key's randomart image is:
+---[RSA 2048]----+
|             .   |
|          . +    |
|           = *   |
|      ..    E *  |
|     . .S  . * . |
|    . .  .. = +.o|
|     . +.o o + Oo|
|     oooB ....* +|
|      *B..oBO=   |
+----[SHA256]-----+
Using SSH key with (AWS) fingerprint: SHA256:vMrnyJe4B6Hf9p/uvqxD521pVs4cB2zYOgRPljt7M4Q
Creating vpc.

```

It would be very nice if as people migrate off kube-up.sh and onto kops  this leveraging of as successful AWS login to dynamically spin up necessary ssh public/private keys was again the default behaviour.  In the past we did not have to mention anything about  ssh public/private keys when spinning up an AWS cluster using kube-up.sh
