### ISSUE TITLE
Calico CNI failure

### ISSUE THREAD

**Issue by Prashanth-M** [kubernetes/kops#13300]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
kops version 1.21.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
k8s version 1.18.9

**3. What cloud provider are you using?**
aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
When creating new node with calico CNI kops nodes are in NOT READT state due to KubeletNotReady            
**5. What happened after the commands executed?**
KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

**6. What did you expect to happen?**
it was supposed to create entry in /etc/cni/net.d/

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Due to this issue cluster is unstable:
calico pods run into crashloopbak:
  Warning  Failed     39m (x5 over 40m)    kubelet            Error: failed to start container "install-cni": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/opt/cni/bin/install\": stat /opt/cni/bin/install: no such file or directory": unknown

**Comment by olemarkus** [comment]
Can you add your cluster spec as per point 7 above?

**Comment by linuxoid69** [comment]
I have some problem.

**Comment by olemarkus** [comment]
@linuxoid69 for us to provide support, I think you at least need to convert your configuration to using containerd. We do not have the capacity to support docker anymore given that it's has been removed from Kubernetes 1.24.

**Comment by linuxoid69** [comment]
I have  /etc/cni/net.d/ is empty
I think that cause in it.

**Comment by olemarkus** [comment]
Usually that happens if the CNI daemonset isn't working properly.
