### ISSUE TITLE
Reducing instance group AZ may cause etcd to fail

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1330]
Not sure how I did this one...

Create HA cluster 

```
      NODE_ZONES="eu-west-1a,eu-west-1b,eu-west-1c" \
        MASTER_ZONES="eu-west-1a" \
        KOPS_STATE_STORE="s3://oscar-ai-k8s-dev" \
        CLUSTER_NAME="liea-ginny.dev.datapipe.io" \
        NODEUP_BUCKET="kops-devel" \
        NODE_COUNT=2 \
        NODE_SIZE=m3.large \
        MASTER_SIZE=m3.large \
        TOPOLOGY=private \
        NETWORKING=weave \
        VERBOSITY=1 \
        IMAGE=k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-11-16 \
        hack/dev-build.sh |& tee /tmp/clove.out
```

The edit the instance group for the nodes, and reduce the AZ to just a single AZ.  For some reason etcd on the master gets hosed.

**Comment by sergejjevsejev-home24** [comment]
I just experienced the same issue

**Comment by chrislovecnm** [comment]
It is an edge case that needs to be supported.

**Comment by justinsb** [comment]
I wasn't able to reproduce when I tried.

@sergejjevsejev-home24 were you also running weave?

**Comment by sergejjevsejev-home24** [comment]
@justinsb , no it was default networking.

**Comment by justinsb** [comment]
I've tried a few times but I haven't been able to reproduce this.

I'm going to move to 1.5.1.  I don't think we're going to be able to reproduce without more details, in particular:

1) please capture logs during the kops commands, ideally at `--v=8`
2) we need more information about how "etcd is hosed".  Is it up but unresponsive?  Crash-looping? etc.

**Comment by chrislovecnm** [comment]
@justinsb etcd does not start properly.  Will see if I have a chance to recreate.

**Comment by chrislovecnm** [comment]
Closing as I have not seen this again
