### ISSUE TITLE
mixedInstancesPolicy - machine type specified is invalid m5.4xlarge

### ISSUE THREAD

**Issue by barakseri1** [kubernetes/kops#13321]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.22.4 (git-d892bdc3f0cac39f2dbc9d90758208bf79200a6e)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.21.3

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

update cluster <cluster> --yes --out <output dir>  --target=terraform --admin=48h --state <location>

**5. What happened after the commands executed?**

`Error: [spec.mixedInstancesPolicy.instances[2]: Invalid value: "c6a.2xlarge": machine type specified is invalid: "c6a.2xlarge", spec.machineType: Invalid value: "m5.4xlarge": machine type specified is invalid: "m5.4xlarge"]`

**6. What did you expect to happen?**

generate terraform config

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: <name>
  name: <name>
spec:
  additionalSecurityGroups:
  - sg-12324
  - sg-1234
  cloudLabels:

  image: ami-xxx
  machineType: m5.4xlarge
  maxPrice: "10.0"
  maxSize: 600
  minSize: 0
  mixedInstancesPolicy:
    instances:
    - c5n.2xlarge
    - m5.2xlarge
    - c6a.2xlarge
    - m5.4xlarge
    - m6a.2xlarge
    - c5.4xlarge
    onDemandAboveBase: 0
    spotInstancePools: 6
  nodeLabels:
  
  role: Node
  rollingUpdate:
    maxSurge: 100%
  rootVolumeEncryption: true
  rootVolumeOptimization: true
  rootVolumeSize: 100
  rootVolumeThroughput: 250
  rootVolumeType: gp3
  subnets:
  - xxx
  taints:
  - xxx
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

c6a is a new type so I guess wasnt added yet. m5.4xlarge should be supported

**Comment by olemarkus** [comment]
We need to bump the AWS SDK to support this one.
The error with m5.4xlarge may be regional. not all regions may have this instance type.

**Comment by barakseri1** [comment]
Thanks @olemarkus 
The thing is, when i use kops version 1.22.4 I get the error regarding the unsupported instances for c6a.2xlarge and m5.4xlarge

However when I use version 1.21.0 I don't get the error on m5.4xlarge, only on c6a and m6a (which is expected)

**Comment by olemarkus** [comment]
We are pushing out 1.23.0 now, which should have an updated SDK. If you can wait a few hours for that one and test again ...

**Comment by barakseri1** [comment]
@olemarkus, results with 1.23.0:

Error: [spec.mixedInstancesPolicy.instances[2]: Invalid value: "c6a.2xlarge": machine type specified is invalid: "c6a.2xlarge", spec.machineType: Invalid value: "m5.4xlarge": machine type specified is invalid: "m5.4xlarge"]

**Comment by olemarkus** [comment]
Which region are you testing?

**Comment by barakseri1** [comment]
tested on 1.23.0 in eu-west-1

**Comment by olemarkus** [comment]
I cannot really reproduce this. The validation also calls `DescribeInstanceTypes` for the given region. And this also returns a proper type when specifying eu-west-1 as region.
