### ISSUE TITLE
dedicated=master:PreferNoSchedule

### ISSUE THREAD

**Issue by tcf909** [kubernetes/kops#1332]
Using AWS how can we setup a master to be used as a worker node if no other nodes exist to schedule?

The cluster.spec masterKubelet:registerSchedulable doesn't seem to work at this point and since nodes dynamically update name (based on @aws) using kubectl doesn't seem to be an option to manually specify the taint (and have it persist).

What would be the best way to accomplish this? (dedicated=master:PreferNoSchedule)

(currently using kops version git-f7a7d4c [head])

**Comment by justinsb** [comment]
I think we'll need to add something like nodeLabels / cloudLabels, but for taints, probably `nodeTaints`.

@davidopp I've misunderstood the tao of taints before.  Can I run this by you?...

kops has a notion of an instance group, which maps to an Auto-Scaling-Group in AWS, and will map to a Managed Instance Group in GCE.  They are a homogenous group of instances, and we typically have one InstanceGroup for nodes, and another for the master.  Users can add more InstanceGroups, if for example they want to mix GPU and non-GPU instances.  (We also create more for HA master, but that's less important).

We currently allow users to define `nodeLabels` - labels that will be applied to all nodes in that InstanceGroup (implemented via the kubelet `--node-labels` flag).  Does it make sense to do the same thing for taints (implemented via the kubelet `--register-with-taints` flag)?

**Comment by ese** [comment]
There is a bunch of issues related with this: https://github.com/kubernetes/kops/issues/1497 https://github.com/kubernetes/kops/issues/803 https://github.com/kubernetes/kops/issues/481

I think we should allow `nodeTaints` to map `--register-with-taints` but I think https://github.com/kubernetes/kubernetes/pull/31647 is not yet included in any releases

**Comment by robinpercy** [comment]
I'd like to take this one, if others haven't already started. 

@ese looks like 31647 is in the [1.6.0 alpha](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#downloads-for-v160-alpha1)

**Comment by geojaz** [comment]
Should be closed by #1812
