### ISSUE TITLE
InstanceGroup Documentation enhancement for onDemandAllocationStrategy

### ISSUE THREAD

**Issue by gabron** [kubernetes/kops#13323]
I've been looking over the docs for InstanceGroups and I come across this feature:
`onDemandAllocationStrategy`
In all the Internet I can only find this information:
`Indicates how to allocate instance types to fulfill On-Demand capacity`

This sounds like it would be a very useful but I really can't understand how to use it and what the options are.  

It would seem that it should supply more information like the `spotAllocationStrategy` does where it lists options and what they do.  But as it stands the documentation across a couple different sources doesn't tell me much about this feature, other than it exists.

**Comment by olemarkus** [comment]
Hey. Sorry for taking so long to respond to this. I agree this could be done better and would be happy to review a PR.

/remove-lifecycle stale
/kind documentation

**Comment by gabron** [comment]
I would love to issue a PR on this however I really have no clue what `onDemandAllocationStrategy ` is even used for or how to use it.  I guess my noting the documentation was weak was dual purposed in that I was trying to figure out if it was useful for me at that time.

**Comment by olemarkus** [comment]
You can see the docs for it here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-allocation-strategy.html
