### ISSUE TITLE
add ability for kops to talk to AWS govcloud using fips endpoints.

### ISSUE THREAD

**Issue by slimm609** [kubernetes/kops#13331]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
The AWS sdk config supports a flag to enforce using the fips endpoints `UseFIPSEndpoint`
https://github.com/aws/aws-sdk-go/blob/v1.43.11/aws/config.go#L224.  It would be nice if there was a kops setting to enable this in the go sdk so that it talks to AWS using the AWS FIPS endpoints. 

**2. Feel free to provide a design supporting your feature request.**

**Comment by olemarkus** [comment]
We would be happy to review a PR for this feature.
