### ISSUE TITLE
HPA docs are outdated

### ISSUE THREAD

**Issue by ddelange** [kubernetes/kops#13345]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.22.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.22.6

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

- I read the docs: https://github.com/kubernetes/kops/blob/v1.22.2/docs/horizontal_pod_autoscaling.md
- I found that the `--horizontal-pod-autoscaler-use-rest-clients` flag (docs mention it as configured) was missing from my `kube-controller-manager` manifest
- I explicitly passed the option to kOps to enable it and did a rolling update of my cluster

**5. What happened after the commands executed?**

- I got a Crashloopbackoff for `kube-controller-manager`
  - Logs show `Error: unknown flag: --horizontal-pod-autoscaler-use-rest-clients`
  - Turns out kube-controller-manager no longer supports this flag as of v1.21
- Reverted the cluster
- Turns out kOps already configured HPA correctly out of the box

**6. What did you expect to happen?**

- I would like to see more clearly in the docs that HPA is ready to go out of the box
- This deprecated flag could be removed from the docs
- Update the docs concerning k8s 1.23: `autoscaling/v2` and deprecation of `autoscaling/v2beta2` ref https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/#horizontalpodautoscaler-v2-graduates-to-ga

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

N/A

**Comment by ddelange** [comment]
It would also be nice to refer to [HPA customization](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#kubecontrollermanager) in the doc

**Comment by olemarkus** [comment]
Thanks for reporting this. Would you be able to contribute an update?

**Comment by ddelange** [comment]
@olemarkus done :)
