### ISSUE TITLE
Perform aws warm pool api calls only when warm-pool enabled 

### ISSUE THREAD

**Issue by vsamidurai** [kubernetes/kops#13346]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.22.4 

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.21.8

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops update cluster 

**5. What did you expect to happen?**
Perform warm pool AWS API calls only when the warm pool is enabled.  

Even though the warm pool is not enabled, kops makes warm pool API calls. 

AccessDenied: User: arn:aws:somearn  is not authorized to perform: autoscaling:DescribeWarmPool with an explicit deny in an identity-based policy

**Comment by olemarkus** [comment]
That is not possible. Warmpools can be disabled, and kops need to run this to determine if the ASG has it enabled and need to remove it.

**Comment by olemarkus** [comment]
Sounds good to me. Would be happy to review a PR
