### ISSUE TITLE
InstanceGroup taints validation doesn't accept same taint key

### ISSUE THREAD

**Issue by philimonoff** [kubernetes/kops#13351]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`1.22.4`
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`1.21.4`
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops update cluster`
**5. What happened after the commands executed?**
`Error: spec.taints[1]: Forbidden: cannot add multiple taints with key <my_taint_key>`
**6. What did you expect to happen?**
Successful dry-run of cluster update
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Will provide later if needed.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Will provide later if needed.

**9. Anything else do we need to know?**
Looks like there is a bug in function [ValidateInstanceGroup](https://github.com/kubernetes/kops/blob/release-1.22/pkg/apis/kops/validation/instancegroup.go#L36). A new [code](https://github.com/kubernetes/kops/blob/release-1.22/pkg/apis/kops/validation/instancegroup.go#L149) that validates taints of ig appeared in 1.22. The problem is in logic of validation: two taints - `<my_taint_key>=<my_taint_value>:NoSchedule` and `<my_taint_key>=<my_taint_value>:NoExecute`, which are valid in terms of kubernetes - will never pass the validation, because `ValidateInstanceGroup` checks uniqueness of only taint keys, but should check uniqueness of triplets `key,value,effect`.

**Comment by olemarkus** [comment]
Thanks for reporting this. I'll do a PR to fix this soon.
