### ISSUE TITLE
Private topology with kubenet networking

### ISSUE THREAD

**Issue by jonchiu** [kubernetes/kops#1335]
I noticed that during cluster creation, `kubenet` is not supported if a `private` topology is specified. (https://github.com/kubernetes/kops/blob/master/cmd/kops/create_cluster.go#L645)

Can you enlighten me as to why this isn't allowed. I'm happy to add this to the documentation.

Thanks!

**Comment by chrislovecnm** [comment]
@jonchiu internal services do not work with `kubenet` routing.  I am not certain exactly why, but it is probably because of routing between AZ.

@justinsb / @kris-nova can you shed more light?

**Comment by justinsb** [comment]
It's because:

* we expect most people running private are the more advanced users that will also be running multi AZ
* NAT gateways are single AZ
* You need to wire up a routing table per AZ to use NAT gateways
* kubenet with VPC networking requires a single routing table

**Comment by chrislovecnm** [comment]
@jonchiu would love you to document the above!

**Comment by chrislovecnm** [comment]
Closing
