### ISSUE TITLE
cluster validate failed with core-dns pending

### ISSUE THREAD

**Issue by thinksabin** [kubernetes/kops#13360]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.22.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:43:55Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops validate cluster

**5. What happened after the commands executed?**
VALIDATION ERRORS
KIND	NAME						MESSAGE
Machine	i-024435f64				machine "i-024435f64" has not yet joined cluster
Machine	i-061056067				machine "i-061056067" has not yet joined cluster
Machine	i-0fe4de596				machine "i-0fe4de596" has not yet joined cluster
Pod	kube-system/coredns-5dc785954d-zvqsx		system-cluster-critical pod "coredns-5dc785954d-zvqsx" is pending
Pod	kube-system/coredns-autoscaler-84d4cfd89c-j7nqt	system-cluster-critical pod "coredns-autoscaler-84d4cfd89c-j7nqt" is pending

Validation Failed
Error: Validation failed: cluster not yet healthy

**6. What did you expect to happen?**
successful cluster validation

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
this is the fresh setup created on the fresh vpc with subnet auto defined by the kops

**Comment by olemarkus** [comment]
The pending DNS pods are due those machines not joining. So the question is why that doesn't happen.
Are you able to ssh into one of the failing nodes and look at the journal?

**Comment by thinksabin** [comment]
Thanks for reply @olemarkus 
I spinned up the new cluster today and still got the same issue.
unfortunately I couldnt ssh into any of the failing nodes. Is there another way to figure out the cause of this issue?

**Comment by olemarkus** [comment]
Can you please answer question 7 above?
