### ISSUE TITLE
export kubectl should not default to the cluster in kubeconfig

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1338]
Run

```console
$ KOPS_STATE_STORE="s3://oscar-ai-k8s-dev" kops export kubecfg
Using cluster from kubectl context: kops-test-phineas-malfoy.dev.datapipe.io


cluster "kops-test-phineas-malfoy.dev.datapipe.io" not found
```

Running `kops export kubecfg` without a cluster name, just does not make sense

**Comment by asim42** [comment]
Please update if there is any solution to this. I have also faced this issue. I have setup a kubernetes cluster on aws. I am able access it using kubectl. State store is maintained in s3 bucket as terraform statefiles. I want to use `kops validate cluster` for testing. kop is unable to find my cluster.

I provide following envvars:
```export REGION=
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export KOPS_STATE_STORE=```
`kops validate cluster` output is:
```Using cluster from kubectl context: my-cluster


cluster "my-cluster" not found```

**Comment by chrislovecnm** [comment]
Add --name to validate ;)
