### ISSUE TITLE
Support AWS Nitro Enclave settings

### ISSUE THREAD

**Issue by wmiller848** [kubernetes/kops#13393]
/kind feature

### 1. Describe IN DETAIL the feature/behavior/change you would like to see.
Support for [AWS Nitro Enclaves](https://docs.aws.amazon.com/enclaves/latest/user/nitro-enclave.html) in kops

#### MVP
* Necessary [template](https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awstasks/launchtemplate.go#L30) support for aws instance options. Namely `enclave_support: true`

#### Extra/Prescriptive
* Auto UserData injecting for enclave configuration
* Kubernetes config for wiring up enclaves. The example below makes use of https://gitlab.com/arm-research/smarter/smarter-device-manager to provide device mapping for interaction with k8s
* Best way to interact with https://docs.aws.amazon.com/enclaves/latest/user/nitro-enclave-cli.html

This is useful because this enables some powerful use cases for working with very sensitive data.

### 2. Feel free to provide a design supporting your feature request.

Example of using terraform and AWS EKS to do this https://superorbital.io/journal/aws-nitro-enclaves-in-k8s-pods/

**Comment by olemarkus** [comment]
This sounds like an interesting feature. I would be happy to review a PR.
