### ISSUE TITLE
kops add 'list' command

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#134]
kops should have a 'list' command which evaluates the s3 bucket in question, and shows all clusters in the s3 bucket.

**Comment by justinsb** [comment]
It does have `kops get clusters` - is that what you're looking for?

I'm trying to follow kubectl, which uses `kubectl get <type>` even for a list.

If `kops get` was what you wanted I suggest we keep this open for two things:

1) `kubectl list` says "Did you mean this?  get"
2) I think I need a doc listing all the commands now that there are enough of them to warrant it!

**Comment by RichardBronosky** [comment]
It would be nice if the messaging where more helpful

    $ kops get
    
    clusterName is required

could add a 2nd line of output (or put in parenthesis on a single line

    (use "clusters" to list all)
