### ISSUE TITLE
More sysctls: vm.max_map_count

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1340]
Elasticsearch recommends `vm.max_map_count`:

https://www.elastic.co/guide/en/elasticsearch/reference/2.1/setup-configuration.html#vm-max-map-count

**Comment by chrislovecnm** [comment]
This is tough call.  Need to talk on zoom about this one :)

**Comment by chrislovecnm** [comment]
Also the version of es that is being used it old ....

**Comment by justinsb** [comment]
ES recommendations appear unchanged.  But it's much more than just ES ... check out the PR

**Comment by justinsb** [comment]
PR https://github.com/kubernetes/kops/pull/1344
