### ISSUE TITLE
Use golang docker image for building protokube

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1341]
Not sure why we are using Debian.  We should look at dynamically setting golang version and kubectl version in the build.

**Comment by justinsb** [comment]
What do you propose instead of debian?

**Comment by chrislovecnm** [comment]
use the same golang docker we are using to build it.  We need to look at moving to alpine or a smaller container anyways.  The apt-get on the build is nasty.

**Comment by aledbf** [comment]
@chrislovecnm is a reduction of ~20% enough? (without switching to alpine or busybox)

**Comment by chrislovecnm** [comment]
@aledbf it is build time for development that would be improved....

**Comment by chrislovecnm** [comment]
closing because of @aledbf improvements
