### ISSUE TITLE
Additional user data does not work for GCE

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#13427]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.23.5

**3. What cloud provider are you using?**

GCE

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I have following in instance group spec

```
  additionalUserData:
  - name: audit.sh
    type: text/x-shellscript
    content: |
      #!/bin/bash -ex
      mkdir -p /srv/kubernetes/kube-apiserver
      while ! ping -c 1 -W 1 8.8.8.8; do
        echo "Waiting for 8.8.8.8 - network interface might be down..."
        sleep 1
      done
      apt-get update && apt-get install -y curl
      curl -v --retry 5 --retry-delay 1 --retry-max-time 40 -o /srv/kubernetes/kube-apiserver/policy.yaml https://toosecret/policy.yaml
      curl -v --retry 5 --retry-delay 1 --retry-max-time 40 -o /srv/kubernetes/kube-apiserver/audit.yaml https://toosecret/audit.yaml
```

When I create the instance, executing this script will fail.

**5. What happened after the commands executed?**

The only thing that I can see in logs is

<img width="1264" alt="Screenshot 2022-03-28 at 11 35 21" src="https://user-images.githubusercontent.com/22482503/160359466-9ae223ef-9e75-4f57-be6d-4b89db70e969.png">

After that I do not see anything else, so startup-script format is not compatible with GCE?

**6. What did you expect to happen?**

I expect that I could inject additional boot scripts to instance

**Comment by zetaab** [comment]
actually when checking logs again I can see following

```
Mar 28 08:30:12 master-europe-north1-a-1hx1 GCEMetadataScripts[1282]: 2022/03/28 08:30:12 GCEMetadataScripts: startup-script: service installed== nodeup node config done ==
Mar 28 08:30:12 master-europe-north1-a-1hx1 GCEMetadataScripts[1282]: 2022/03/28 08:30:12 GCEMetadataScripts: startup-script: /tmp/metadata-scripts196021825/startup-script: line 302: $'\r': command not found
Mar 28 08:30:12 master-europe-north1-a-1hx1 GCEMetadataScripts[1282]: 2022/03/28 08:30:12 GCEMetadataScripts: startup-script exit status 127
Mar 28 08:30:12 master-europe-north1-a-1hx1 GCEMetadataScripts[1282]: 2022/03/28 08:30:12 GCEMetadataScripts: Finished running startup scripts.
```

**Comment by volade** [comment]
I'm having the same issue. Was there ever any resolution to this. I'm getting the same "command not found" error. It's because the startup script has the MIME headers in there and it's trying to execute those as a shell command. How dow we avoid the MIME headers from being kept in the startup script?

For example this is how it begins:

```
Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
MIME-Version: 1.0

--MIMEBOUNDARY
Content-Disposition: attachment; filename="nodeup.sh"
Content-Transfer-Encoding: 7bit
Content-Type: text/x-shellscript
Mime-Version: 1.0
```

That needs to be removed from the startup script so it can work.

**Comment by zetaab** [comment]
I have not continued using kOps in google cloud. I think it is still broken
