### ISSUE TITLE
env variable name

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1342]
https://github.com/kubernetes/kops/pull/1318/files#diff-3a2215d8a99fe31ed61b86261ae550ecR68

^ shouldn't this be the new base URL environment var `KOPS_BASE_URL`?

**Comment by chrislovecnm** [comment]
@justinsb question for you

**Comment by justinsb** [comment]
If you set NODEUP_URL, we will continue to honor it.

**Comment by chrislovecnm** [comment]
The syntax has changed with the variable ;) you have to set the path to the binary, use to be the path to the folder.

**Comment by chrislovecnm** [comment]
We need to document this ;)

**Comment by justinsb** [comment]
If something has changed, it is a mistake/bug.  Which one has changed?  NODEUP_URL?

**Comment by chrislovecnm** [comment]
Yep `NODEUP_URL` changed :(  You now have to do the full path to the binary.  Not just the directory.

https://github.com/kubernetes/kops/pull/1318/files#diff-3a2215d8a99fe31ed61b86261ae550ecR70

```
	nodeUpLocation = os.Getenv("NODEUP_URL")
	if nodeUpLocation == "" {
		nodeUpLocation = BaseUrl() + "linux/amd64/nodeup"
		glog.V(4).Infof("Using default nodeup location: %q", nodeUpLocation)
	} else {
		glog.Warningf("Using nodeup location from NODEUP_URL env var: %q", nodeUpLocation)
	}
```

Use to function like, could be wrong, but that dev script broke last night.

```
	nodeUpLocation = os.Getenv("NODEUP_URL")
	if nodeUpLocation == "" {
		nodeUpLocation = BaseUrl() + "linux/amd64/nodeup"
		glog.V(4).Infof("Using default nodeup location: %q", nodeUpLocation)
	} else {
                // we seemed to append the path to the binary.
                nodeUpLocation = nodeUpLocation + "linux/amd64/nodeup"
		glog.Warningf("Using nodeup location from NODEUP_URL env var: %q", nodeUpLocation)
	}
```

**Comment by justinsb** [comment]
AFAICT you always had to specify the full path to the binary.    You were doing so as far back as 5be3f4881eb51e8e3f2d930ed0912f9976e65d58  I'm going to close, reopen if you disagree.
