### ISSUE TITLE
Unable to mount PVC to kubernetes nodes in AWS

### ISSUE THREAD

**Issue by sanjaysingatalur** [kubernetes/kops#13440]
/kind bug

**1. What `kops` version are you running? : 1.20

**2. What Kubernetes version are you running? : 1.20 (server version) and 1.18(client version)

**3. What cloud provider are you using?** : AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?** : Create a pod with PVC , upon multiple restarts , pod goes in to crashloopbackoff 

**5. What happened after the commands executed?** : pod went into crashloopbackoff with following error
 Warning  FailedMount  33s    kubelet, ip-xx-xx-xx-xx.eu-central-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[xxxxdir], unattached volumes=[xxxx default-token-m59mj]: timed out waiting for the condition

**6. What did you expect to happen?** : pod should be running after restart.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

``
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
creationTimestamp: "2022-03-29T10:34:06Z"
name: xxxx.devops
spec:
api:
loadBalancer:
class: Classic
type: Internal
authorization:
rbac: {}
channel: stable
cloudProvider: aws
clusterAutoscaler:
cpuRequest: 100m
enabled: true
memoryRequest: 300Mi
skipNodesWithLocalStorage: true
skipNodesWithSystemPods: true
configBase: s3://clusters.xxxx.devops/xxxx.devops
containerRuntime: docker
dnsZone: xxxx
etcdClusters:
- cpuRequest: 200m
etcdMembers:
- encryptedVolume: true
instanceGroup: master-eu-central-1a
name: a
memoryRequest: 100Mi
name: main
- cpuRequest: 100m
etcdMembers:
- encryptedVolume: true
instanceGroup: master-eu-central-1a
name: a
memoryRequest: 100Mi
name: events
iam:
allowContainerRegistry: true
legacy: false
kubelet:
anonymousAuth: false
authenticationTokenWebhook: true
authorizationMode: Webhook
kubernetesApiAccess:
- 0.0.0.0/0
kubernetesVersion: 1.20.13
masterPublicName: api.xxxx.devops
metricsServer:
enabled: true
insecure: true
networkCIDR: 10.0.0.0/16
networkID: vpc-xxxx
networking:
weave:
mtu: 8912
nonMasqueradeCIDR: 100.64.0.0/10
sshAccess:
- 10.0.0.0/16
subnets:
- cidr: 10.0.64.0/18
id: subnet-xxxx
name: Public-xxxx-eu-central-1a
type: Public
zone: eu-central-1a
- cidr: 10.0.192.0/18
id: subnet-xxxx
name: Private-xxxx-eu-central-1a
type: Private
zone: eu-central-1a
topology:
dns:
type: Private
masters: private
nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
creationTimestamp: "2022-03-29T10:34:07Z"
labels:
kops.k8s.io/cluster: xxxx.devops
name: master-eu-central-1a
spec:
image: xxxx
machineType: t2.medium
maxSize: 1
minSize: 1
nodeLabels:
kops.k8s.io/instancegroup: master-eu-central-1a
role: Master
rootVolumeEncryption: true
rootVolumeEncryptionKey: xxxx
subnets:
- Private-xxxx-eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
creationTimestamp: "2022-03-29T10:34:07Z"
labels:
kops.k8s.io/cluster: xxxx.devops
name: nodes
spec:
image: xxxx
machineType: t2.xlarge
maxSize: 11
minSize: 3
nodeLabels:
kops.k8s.io/instancegroup: nodes
role: Node
rootVolumeEncryption: true
rootVolumeEncryptionKey: xxxx
subnets:
- Private-xxxx-eu-central-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
    It is a blocker for our production

**Comment by sanjaysingatalur** [comment]
what is the supported kops version?

**Comment by olemarkus** [comment]
1.23.0 and 1.22.4

**Comment by sanjaysingatalur** [comment]
this is what i get in the log

I0331 12:17:11.973113 1 aws_util.go:62] Error deleting EBS Disk volume aws://eu-central-1a/vol-xxxxxxx: error deleting EBS volume "vol-xxxxxx" since volume is currently attached to "i-xxxxxxxxx"
E0331 12:17:11.973296 1 goroutinemap.go:150] Operation for "delete-pvc-xxxxx-xxxx-4ab3-8b00-ad3993a2cc74[901717f9-e84c-4a18-bb05-489f59598246]" failed. No retries permitted until 2022-03-31 12:17:13.973271817 +0000 UTC m=+26204.570337504 (durationBeforeRetry 2s). Error: "error deleting EBS volume \"vol-xxxxxx\" since volume is currently attached to \"i-xxxxxxxx\""

**Comment by olemarkus** [comment]
is i-xxxxxxxx a node in the cluster? Looks like you anyway need to detatch the disk or delete that instance.

**Comment by olemarkus** [comment]
As far as I know, there is no kops configuration that would cause this. Maybe you are hitting a kubernetes bug? There may be more logs that you need to look at from KubeControllerManager.

**Comment by kg6zgj** [comment]
My team is experiencing this as well. we are going to upgrade from 1.20.1 to 1.22.5.

**Comment by olemarkus** [comment]
See the comments above. Without more details, we can't help.
