### ISSUE TITLE
Figure out what's going on during explosive test failures

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#1346]
There's been a few in `kops-aws`, but kubernetes/kubernetes#39330 has a recent example from the PR builder: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39330/pull-kubernetes-e2e-kops-aws/5960/

**Comment by foolusion** [comment]
Let me know if there is anything I can do to help.

**Comment by justinsb** [comment]
I think we've looked at a few and they look like docker just hanging.  We do have a health checker, but it was using `docker version`, whereas the latest GCI one uses `docker ps`.  We switched that in https://github.com/kubernetes/kops/pull/1350 so we'll see what happens now

**Comment by zmerlynn** [comment]
Another example: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/1988 .. looks post-#1350?

**Comment by zmerlynn** [comment]
And https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/1987 . Fascinating that it came in a pair of builds, I wonder if AWS was being slow.

**Comment by justinsb** [comment]
I actually think AWS itself is unhealthy right now.  Brace for impact.

**Comment by justinsb** [comment]
So a few cases we have identifier so far:

* docker crashes, mostly cleaned up by the docker healthchecker now that it uses `docker ps` (?)
* HTTP fetch retries, per #1441 
* After a crash, we seem to clear out the images, which of course includes the images we `docker load`-ed #1429  (kinda surprised this one doesn't hit kube-up ... or maybe it does!)

**Comment by chrislovecnm** [comment]
Where are we at on this?

**Comment by chrislovecnm** [comment]
Closing, I think we are good now
