### ISSUE TITLE
Issue using protokube url

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1351]
`nodeup` is downloading the `protokube` docker, from a valid URL.  But I believe it is looking for the incorrect tag.

```
root@ip-172-20-39-152:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
protokube           git-fbbfa98         f0b6b2620a62        14 hours ago        292.1 MB
```

```
Jan  4 18:58:59 ip-172-20-39-152 docker[977]: time="2017-01-04T18:58:59.751201325Z" level=error msg="Handler for POST /v1.23/containers/create returned error: No such image: protokube:git-ff44956"
Jan  4 18:58:59 ip-172-20-39-152 docker[3632]: Unable to find image 'protokube:git-ff44956' locally
Jan  4 18:59:00 ip-172-20-39-152 docker[977]: time="2017-01-04T18:59:00.734227077Z" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
Jan  4 18:59:00 ip-172-20-39-152 docker[3632]: Pulling repository docker.io/library/protokube
Jan  4 18:59:01 ip-172-20-39-152 docker[977]: time="2017-01-04T18:59:01.054003825Z" level=error msg="Not continuing with pull after error: Error: image library/protokube not found"
Jan  4 18:59:01 ip-172-20-39-152 docker[3632]: /usr/bin/docker: Error: image library/protokube not found.
```

I am running one version of `kops` to develop on, and another version to use protokube with.  My upload speed stinks, and doing a full build every time is brutal.  Do I need to override another env variable?  Digging through the code now.

**Comment by chrislovecnm** [comment]
So https://github.com/kubernetes/kops/blob/master/upup/models/nodeup/_protokube/services/protokube.service.template#L9

`ProtokubeImageName`

Is resolving to the git version of my `kops` build, and not the version of `protokube` that is being deployed.  This is a valid use case, since we may need a different version of `protokube` vs the version of `kops` being used.

**Comment by justinsb** [comment]
> This is a valid use case, since we may need a different version of protokube vs the version of kops being used.

That's what I propose we end... the kops version is paired with a version of nodeup & protokube.

**Comment by justinsb** [comment]
I believe this is fixed by the tied-versioning model we have now adopted.  Closing, but please reopen/comment if not!
