### ISSUE TITLE
pod annotation for AWS csi driver when using kube2iam

### ISSUE THREAD

**Issue by ashish1099** [kubernetes/kops#13541]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Currently a new cluster with 1.22 works fine, when requesting for a PVC from the `ebs.csi.aws.com` provisioner.
The problem comes when we deploy the kube2iam and it runs with a `namespace-restrictor` flag, which create two problem for us.

a. We cannot add the required annotation on the aws-ebs-csi pod 
b. we have to add the annotation in the kube-system ns (which I would like to avoid, although not IMP, but still)

**2. Feel free to provide a design supporting your feature request.**
Can we allow to add the annotation in the clusterspec `cloudConfig.awsEBSCSIDriver.controller.annotation` or something, I don't whatever key we use, just able to add it.

Also I have seen many requesting the same feature not exactly for the CSI, but for external-dns or some other app.
and the change is quite simple too, if you guys are fine, I can spend sometime to raise a PR

**Comment by olemarkus** [comment]
Hey. There is precedence for adding `podAnnotations` to our addons, so go right ahead. Thanks.

**Comment by ashish1099** [comment]
hmm,

I can see this `aws-ebs-csi-driver.addons.k8s.io` as an addon name, buts whats the spec and I see no example for any other addon where we can add it.

I dont see anywhere in here as well https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template

any pointer would be helpful :)

Thanks

**Comment by rifelpet** [comment]
You can use these two PRs as reference:

https://github.com/kubernetes/kops/pull/13511
https://github.com/kubernetes/kops/pull/13536

**Comment by ashish1099** [comment]
great, I did saw these two PRs, but again these PR has added an ability to add the annotation for nodelocaldns and [cluster-autoscaler](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/componentconfig.go#L995) and I guess I have to raise a PR to add support for aws-csi-driver here https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/componentconfig.go#L901 and relevant files as well.

Let me know, If I'm on right track, I can find some time to raise the PR

**Comment by rifelpet** [comment]
Correct, you'd make an equivalent addition to that struct, run `make apimachinery crds`, and update the manifest template here: https://github.com/heybronson/kops/blob/master/upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template

**Comment by ashish1099** [comment]
Thanks, will raise a PR for this one. :)

**Comment by mozz-lx** [comment]
I have the same issue with our clusters. but I was wondering, why wasn't added independent podAnnotations for the controller and the nodes?

something like:
```
spec.cloudConfig.properties.awsEBSCSIDriver.properties.controller.podAnnotations
spec.cloudConfig.properties.awsEBSCSIDriver.properties.nodes.podAnnotations
```

can I open a new feature request for it?

**Comment by ashish1099** [comment]
The PR is merged, so should be available in next release.
For now we have disabled the cis driver from kops and install it via argocd (helm)

**Comment by mozz-lx** [comment]
@ashish1099  just to share.

found this option in kube2iam 2.6.0.
```
--auto-discover-default-role            Queries EC2 Metadata to determine the default IAM Role and base ARN, cannot be used with --default-role, overwrites any previous setting for --base-role-arn
```
After adding it to my kube2iam deployment, we were able to enable the csi driver in kops and seems to work fine without the need for the kube2iam annotations.
