### ISSUE TITLE
Weave without --networking=public does not seem to create the weave ds

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1360]
`kops create cluster weave.exa,mple.com --networking weave --zones us-east-1c`

did not seem to create a weave DS

**Comment by kris-nova** [comment]
1. Did you mean `weave.exa,mple.com`?
2. What do you mean by DS?
3. Why is this bad?

**Comment by justinsb** [comment]
I think this is fixed by #1361 - my bad!

**Comment by justinsb** [comment]
(We should still support weave even with public networking, so we can support > 50 nodes)

**Comment by justinsb** [comment]
And no, the comma was a typo.  But DS=daemonset :-)
