### ISSUE TITLE
kops cannot delete all resources

### ISSUE THREAD

**Issue by bennythejudge** [kubernetes/kops#13612]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
kops version
Version 1.23.0
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

I need to check

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops delete cluster`

The issue is a failed delete, I don't know how to reproduce it

**5. What happened after the commands executed?**

The command, issued multiple time, was unable to delete all resources and was stuck with several remaining resources:

```
Not all resources deleted; waiting before reattempting deletion
	vpc:vpc-xxxxxx
	dhcp-options:dopt-xxxxx
	internet-gateway:igw-xxxxx
	route-table:rtb-xxxx
	subnet:subnet-xxxxx
subnet:subnet-xxxxx	still has dependencies, will retry
internet-gateway:igw-xxxxx	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	vpc:vpc-xxxx
	dhcp-options:dopt-xxxx
	internet-gateway:igw-xxxx
	route-table:rtb-xxxxx
	subnet:subnet-xxxxx
subnet:subnet-xxxxx	ok
internet-gateway:igw-xxxx	ok
route-table:rtb-xxxx	ok
vpc:vpc-xxxxxxx	still has dependencies, will retry
```

Checking the "chain" of resources I ended up discovering that it was an ELB keeping the rest hostage, and by deleting this ELB,
several of the resources were deleted:

```
Not all resources deleted; waiting before reattempting deletion
	dhcp-options:dopt-xxxx
	vpc:vpc-xxxxx
vpc:vpc-xxxxx	still has dependencies, will retry
```

**6. What did you expect to happen?**

I expected `kops` to be aware of the ELB that was holding two `Network Interfaces` busy so that they couldn't be deleted.
In general I expect `kops` to cleanup its resources.
Orphaned resources in AWS can incur extra costs.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by olemarkus** [comment]
kOps may only delete resources that it owns. What tags did the ELB have?

**Comment by bennythejudge** [comment]
Thanks @olemarkus it's a good question. Someone else also suggested that maybe the ELB didn't belong to the kops cluster. Unfortunately I made a (bad) assumption that it was and I didn't check before deleting it. 
I'll close this issue as I do not have supporting evidence that the issue was `kops` related. Apologies for the noise.
