### ISSUE TITLE
After upgrading a cluster using Calico to kOps 1.23.1, kube-controller-manager shows a lot of error logs

### ISSUE THREAD

**Issue by DingGGu** [kubernetes/kops#13611]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.23.1 (git-83ccae81a636b8e870e430b6faaeeb5d10d9b832)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`v1.22.8`

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kubectl -n kube-system logs kube-controller-manager

**5. What happened after the commands executed?**
A lot of recurring logs come from kube-controller-manager
```
E0425 07:14:36.573615       1 plugins.go:752] "Error dynamically probing plugins" err="error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: unexpected end of JSON input"
E0425 07:14:36.674744       1 driver-call.go:262] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input
W0425 07:14:36.674764       1 driver-call.go:149] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds: no such file or directory, output: ""
```

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

debian 10, calico

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Maybe related with https://github.com/projectcalico/calico/issues/5356

**Comment by jhohertz** [comment]
Also seeing this message on the same version.

**Comment by stewbernetes** [comment]
I was also seeing this exact same issue.

Running the `channels` binary had no impact, but as of kOps release 1.24.1, these errors have stopped.

I suspect this issue was in fact related to the upstream calico bug and has now been resolved.

**Comment by ScOut3R** [comment]
Yes, I think the issue was resolved in https://github.com/projectcalico/calico/pull/6605

**Comment by DingGGu** [comment]
Restart appears in kOps 1.26.5, Kubernetes 1.24.16

```
Aug 10 09:56:27 ip-x-x-x-x kubelet[2687]: W0810 09:56:27.645876    2687 driver-call.go:149] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds: no such file or directory, output: ""
Aug 10 09:56:28 ip-x-x-x-x kubelet[2687]: E0810 09:56:28.653319    2687 plugins.go:740] "Error dynamically probing plugins" err="error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: unexpected end of JSON input"
Aug 10 09:56:28 ip-x-x-x-x kubelet[2687]: E0810 09:56:28.655167    2687 driver-call.go:262] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input 

```
