### ISSUE TITLE
Provide Cluster-Wide CA Cert option for Statestore

### ISSUE THREAD

**Issue by MarkusBauerBE** [kubernetes/kops#13615]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Currently - at least as far as I am aware - it isn't possible to provide services deployed by kOps with a CA cert to verify the certificate of a custom S3 store. If it is, it definitely isn't made very clear in the documentation. 

What this means is, that environments that are limited to private PKIs and private S3 stores (e.g. MinIO) run into trouble deploying a cluster using kOps as etcd-manager utilizes the state-store but kOps provides no way of adding a CA certificate to it. 
This results in etcd-manager failing to startup properly as it doesn't trust the state-store, halting the cluster deployment.

The best solution for this would probably be to add a key to the etcd cluster configuration that allows setting a path to a CA certificate on the node akin to the options in the kubeAPIServer section of the cluster config that for example allow setting a client cert and a CA cert for interactions between kube-api-server and etcd cluster.

**2. Feel free to provide a design supporting your feature request.**

**Comment by olemarkus** [comment]
Does etcd-manager support custom CA for the state store? If not, you'd have to start there. Then later on, kOps can feed in a custom CA.
