### ISSUE TITLE
Digital Ocean: Field cannot be changed: Image error while scaling up instance group

### ISSUE THREAD

**Issue by zak905** [kubernetes/kops#13627]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.23.0 (git-a067cd7742a497a5c512762b9880664d865289f1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

K8 version is not revelant in this context
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.23.5

**3. What cloud provider are you using?**

Digital Ocean

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

first editing an instance group to increase the number of instances: `kops edit instancegroup nodes-fra1`
and then upgrating the cluster: `kops update cluster mycluster.domain.com`

It is not possible to reproduce this immediately. One need to create a cluster in DO, and then wait until the Droplet images go to "retired" status (check the response schema here: https://docs.digitalocean.com/reference/api/api-reference/#operation/get_images_list)

DO update their images every now and then (not sure about the frequency), and even if the distribution and the version stay the same for some images, DO tend to make the old one "retired". The newer image will have the status "available". This does not affect  the functioning of the existing droplets, but the droplet stays attached to the id of the image which was used when it got created. 

So if I get the droplet info using the API: 

```
curl -X GET   -H "Content-Type: application/json"   -H "Authorization: Bearer $DIGITALOCEAN_TOKEN"   "https://api.digitalocean.com/v2/droplets
```

The droplet in question has this, in the image field:
```
"image": {
        "id": 101537412,
        "name": "11 x64",
        "distribution": "Debian",
        "slug": null,
        "public": false,
        "regions": [],
        "created_at": "2022-02-07T20:36:17Z",
        "min_disk_size": 15,
        "type": "base",
        "size_gigabytes": 0.38,
        "description": "Debian 11 Image",
        "tags": [],
        "status": "retired"
      }

```

You can see here than slug is null, because somehow the image is marked as retired by DO. However , if the same call is made on a droplet whose image is still available, the slug will not be null. This by design from DO: https://docs.digitalocean.com/products/platform/image-deprecation/#image-deprecation

**5. What happened after the commands executed?**

`Field cannot be changed: Image` error is thrown here https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/dotasks/droplet.go#L195

and kops keeps on retrying to run the task. The update fails eventually. 

This is because the slug of the "retired" image is null, so the current image is relplaced by null (or pointer to empty string) here: https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/dotasks/droplet.go#L87

If I execute the command with `-v 8` I see this when it comes to the droplet image:

```
I0509 16:45:52.582531 2042445 changes.go:81] Field changed "Image" actual="" expected="debian-11-x64"
```

I did not change the image myself, but this comes from DO side. 

**6. What did you expect to happen?**

The command to be successful

**7. Please provide your cluster manifest. Execute**

Not relevant in this context

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.**

```
I0509 16:45:52.287584 2042445 executor.go:186] Executing task "Droplet/nodes-fra1.mycluster.domain": *dotasks.Droplet {"Name":"nodes-fra1.mycluster.domain","Lifecycle":"Sync","Region":"fra1","Size":"s-2vcpu-4gb","Image":"debian-11-x64","SSHKey":"my-key","VPCUUID":null,"NetworkCIDR":null,"VPCName":null,"Tags":["KubernetesCluster:my-cluster","kops-instancegroup:nodes-fra1"],"Count":3,"UserData":{"resource":{},"task":{"Name":"nodes-fra1","Lifecycle":"Sync"}}}
I0509 16:45:52.582531 2042445 changes.go:81] Field changed "Image" actual="" expected="debian-11-x64"
I0509 16:45:52.582583 2042445 changes.go:81] Field changed "Count" actual="2" expected="3"
I0509 16:45:52.684985 2042445 changes.go:81] Field changed "Image" actual="" expected="debian-11-x64"
I0509 16:45:52.740714 2042445 changes.go:81] Field changed "Image" actual="" expected="debian-11-x64"
I0509 16:45:52.745429 2042445 changes.go:81] Field changed "Image" actual="" expected="debian-11-x64"
W0509 16:45:52.748048 2042445 executor.go:139] error running task "Droplet/master-fra1-2.masters.mycluster.domain" (9m59s remaining to succeed): Field cannot be changed: Image
W0509 16:45:52.748109 2042445 executor.go:139] error running task "Droplet/master-fra1-3.masters.mycluster.domain" (9m59s remaining to succeed): Field cannot be changed: Image
W0509 16:45:52.748131 2042445 executor.go:139] error running task "Droplet/master-fra1-1.masters.mycluster.domain" (9m59s remaining to succeed): Field cannot be changed: Image
W0509 16:45:52.748149 2042445 executor.go:139] error running task "Droplet/nodes-fra1.mycluster.domain" (9m59s remaining to succeed): Field cannot be changed: Image
I0509 16:45:52.748170 2042445 executor.go:111] Tasks: 53 done / 57 total; 4 can run
```

**9. Anything else do we need to know?**

The fix of this would be simple. Because a Droplet's image is not supposed to change, we can just keep the same values in between updates, and not replace the Image with one got from the API.

**Comment by hakman** [comment]
@srikiz @timoreimann any thoughts on this one?
