### ISSUE TITLE
iam.serviceAccountExternalPermissions does not work when using own spec.KubeAPIServer.serviceAccountIssuer

### ISSUE THREAD

**Issue by jhohertz** [kubernetes/kops#13667]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.23.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.23.6

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Maybe not simple. The issue, is when using your own non-managed OIDC IAM for IRSA, you are explicitly disallowed from using. `serviceAccountExternalPermissions`. This was surprising because `useServiceAccountExternalPermissions` to allow IRSA for the kops provisioned bits works just wonderfully.

So I: `kops replace -f cluster_spec.yaml --force`

**5. What happened after the commands executed?**

`Error: error creating cluster: spec.iam.serviceAccountExternalPermissions: Forbidden: serviceAccountExternalPermissions requires AWS OIDC Provider to be enabled`

**6. What did you expect to happen?**

As the spec works with `useServiceAccountExternalPermissions`, and also with externally setup IRSA roles, w/ the annotations, this validation seems to be overzealous.

**7. Please provide your cluster manifest. Execute

I can share it if needed, but the gist of it is setting `serviceAccountExternalPermissions` while NOT setting `serviceAccountIssuerDiscovery`, but rather managing it one's self (keys, kubeapi. the aws oidc provision, etc.)

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Will follow up if needed.

**9. Anything else do we need to know?**

This is the validation causing the issue: https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/validation/validation.go#L275-L280

It does not appear the same check is done for `useServiceAccountExternalPermissions`, which is why that works.

Perhaps an additional check could be, if the spec is setting `spec.KubeAPIServer.serviceAccountIssuer`, that should be sufficient evidence that the user is setting up IRSA via some other means?

**Comment by olemarkus** [comment]
I agree this validation is somewhat overeager. But kOps will also always set `serviceAccountIssuer` and other related flags, so their presence may not be enough. By default these will point to the API server, which AWS often cannot reach. Happy to review a PR on this though, if you have any idea of what may work.

**Comment by jhohertz** [comment]
@olemarkus I may try to make a PR on this, but to run the idea by you.... when checking if the configuration is valid, simply check if something has enabled the pod identity webhook. Either kops did via the setup it was doing, or someone obviously has enabled it, and the support would be there. Would that be acceptable?

**Comment by jhohertz** [comment]
But are we not controlling the config of the webhook here, or rather it's configmap?

**Comment by olemarkus** [comment]
If the addon is enabled, yes. But the addon is optional. You can have IRSA enabled by kops, but self-manage the env vars and volumes.

**Comment by jhohertz** [comment]
I understand that, but the flag in question is specific to using the webhook, no?

**Comment by olemarkus** [comment]
Sorry, you lost me there. Which flag? `useServiceAccountExternalPermissions`?

**Comment by jhohertz** [comment]
That one funny enough works, the problem is when adding my own roles with `iam.serviceAccountExternalPermissions`

**Comment by olemarkus** [comment]
`iam.serviceAccountExternalPermissions` requires the kops-provisioned identity provider because kOps creates trust between the IAM role and the ServiceAccount. See https://github.com/kubernetes/kops/blob/master/tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_iam_role_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy for an example.

**Comment by jhohertz** [comment]
How is it that `useServiceAccountExternalPermissions` works then? I don't get what the fundamental difference is here.

**Comment by olemarkus** [comment]
You are quire right that these are fundamentally doing the same thing. Only with addons vs user-defined roles. So `useServiceAccountExternalPermissions` should also require having a kops-provisioned identity provider. The linked policy is actually generated from `useServiceAccountExternalPermissions`. Setting this flag without the identity provider will result in roles that cannot be assumed otherwise.

**Comment by jhohertz** [comment]
This is very much the opposite from where I was trying to go.... The feature works great with the add-on roles, I simply wanted to add some local ones too, and it sounds like by bringing it up I may now lose that in the future.

**Comment by olemarkus** [comment]
Do you manually manipulate the roles? Or manually create them? If not, I don't quite understand how the trust relationship is established.

**Comment by jhohertz** [comment]
Neither. I'll pull out the flags I set, but I am telling Kops about an
existing oidc endpoint that was setup, enabling the
useServiceAccountExternalPermissions, and everything works great. It's only
when I attempt to add other roles that I encounter an issue.

Part of my desire to do this is so I can shed an in-house tool for setting
up roles so I can do it with Kops directly.

**Comment by olemarkus** [comment]
Can you paste the `AssumeRolePolicyDocument` for the roles kOps creates? These should refer to the OIDC provider that kOps should have created, but didn't.

**Comment by olemarkus** [comment]
Sorry it took some time to get back to this.

Does https://github.com/kubernetes/kops/pull/14243 match your expectations?

/remove-lifecycle stale
