### ISSUE TITLE
Unable to update cluster after manually adding ipv6 on AWS

### ISSUE THREAD

**Issue by IgalSc** [kubernetes/kops#13660]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`kops version
Version 1.23.2 (git-4125bbbe975ca104c609ceaa625a9a5ff3ac19f4)
`
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
` kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.20) exceeds the supported minor version skew of +/-1`
**3. What cloud provider are you using?**

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I have manually added ipv6 addressing on the VPC/subnets and assigned instances (master and node) with ipv6
Now I'm trying to update the cluster with downgraded master node (c5.large --> t3a.medium), but it fails
Running `kops update cluster` I get the following at the end:
`Will delete items:
  SubnetIPv6CIDRBlock  vpc-b60475d3: ipv6cidr=2600:1f18:14a:9010::/64`

**5. What happened after the commands executed?**
Running `kops update cluster --yes` I get error 
`*********************************************************************************

A new kubernetes version is available: 1.20.15
Upgrading is recommended (try kops upgrade cluster)

More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_k8s.md#1.20.15

*********************************************************************************

I0517 15:01:40.719870     442 apply_cluster.go:483] Gossip DNS: skipping DNS validation
W0517 15:01:40.743629     442 yaml.go:57] unexpected type for object metadata: map[interface {}]interface {}
W0517 15:01:40.744163     442 yaml.go:57] unexpected type for object metadata: map[interface {}]interface {}
I0517 15:01:41.047237     442 executor.go:111] Tasks: 0 done / 90 total; 42 can run
I0517 15:01:41.348121     442 executor.go:111] Tasks: 42 done / 90 total; 17 can run
W0517 15:01:41.840420     442 executor.go:139] error running task "Subnet/us-east-1a.clustername.dev1.k8s.local" (9m59s remaining to succeed): InvalidCidrBlock.InUse: The subnet subnet-0c5b1ef703baf2ff3 currently has an interface within CIDR block 2600:1f18:14a:9010::/64
        status code: 400, request id: c0c45bad-1ed4-40c5-9c3d-7c74cbcd8567
W0517 15:01:41.840476     442 executor.go:139] error running task "Subnet/us-east-1a1.clustername.dev1.k8s.local" (9m59s remaining to succeed): error creating subnet: InvalidParameterValue: Value (2600:1f18:14a:9010::/64) for parameter cidrBlock is invalid. This is not a valid CIDR block.
        status code: 400, request id: 3e2ce6bb-e42b-44e4-a108-40020a3e2004
I0517 15:01:41.840570     442 executor.go:111] Tasks: 57 done / 90 total; 22 can run
W0517 15:01:42.193960     442 executor.go:139] error running task "Subnet/us-east-1a.clustername.dev1.k8s.local" (9m59s remaining to succeed): InvalidCidrBlock.InUse: The subnet subnet-0c5b1ef703baf2ff3 currently has an interface within CIDR block 2600:1f18:14a:9010::/64
        status code: 400, request id: 28b37965-5637-4265-9626-53eeea4d93a0
W0517 15:01:42.194029     442 executor.go:139] error running task "Subnet/us-east-1a1.clustername.dev1.k8s.local" (9m59s remaining to succeed): error creating subnet: InvalidParameterValue: Value (2600:1f18:14a:9010::/64) for parameter cidrBlock is invalid. This is not a valid CIDR block.
        status code: 400, request id: ada39aed-54b2-4ae8-9222-09ed9c19d183
I0517 15:01:42.194069     442 executor.go:111] Tasks: 77 done / 90 total; 2 can run
W0517 15:01:42.453972     442 executor.go:139] error running task "Subnet/us-east-1a.clustername.dev1.k8s.local" (9m58s remaining to succeed): InvalidCidrBlock.InUse: The subnet subnet-0c5b1ef703baf2ff3 currently has an interface within CIDR block 2600:1f18:14a:9010::/64
        status code: 400, request id: e949885a-7118-4722-979c-f6d3115e125f
W0517 15:01:42.454021     442 executor.go:139] error running task "Subnet/us-east-1a1.clustername.dev1.k8s.local" (9m58s remaining to succeed): error creating subnet: InvalidParameterValue: Value (2600:1f18:14a:9010::/64) for parameter cidrBlock is invalid. This is not a valid CIDR block.
        status code: 400, request id: de47b870-9d4f-430e-801e-8f32b884d267
I0517 15:01:42.454051     442 executor.go:155] No progress made, sleeping before retrying 2 task(s)
I0517 15:01:52.456700     442 executor.go:111] Tasks: 77 done / 90 total; 2 can run
W0517 15:01:52.743189     442 executor.go:139] error running task "Subnet/us-east-1a.clustername.dev1.k8s.local" (9m48s remaining to succeed): InvalidCidrBlock.InUse: The subnet subnet-0c5b1ef703baf2ff3 currently has an interface within CIDR block 2600:1f18:14a:9010::/64
        status code: 400, request id: f12897ee-85b1-483e-86c4-d7d2fce4a0ac
W0517 15:01:52.743242     442 executor.go:139] error running task "Subnet/us-east-1a1.clustername.dev1.k8s.local" (9m48s remaining to succeed): error creating subnet: InvalidParameterValue: Value (2600:1f18:14a:9010::/64) for parameter cidrBlock is invalid. This is not a valid CIDR block.
        status code: 400, request id: 9144b69b-bb39-4563-9c37-340758349d13
I0517 15:01:52.743343     442 executor.go:155] No progress made, sleeping before retrying 2 task(s)
`

**6. What did you expect to happen?**
I was expecting the new t3a.medium instance to be rolled out and the c5.large instance to be removed

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-04-08T09:55:55Z"
  generation: 5
  name: clustername.dev1.k8s.local
spec:
  additionalNetworkCIDRs:
  - 2600:1f18:14a:9000::/56
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://clustername-imesh-kops-state-store/clustername.dev1.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.8
  masterInternalName: api.internal.clustername.dev1.k8s.local
  masterPublicName: api.clustername.dev1.k8s.local
  networkCIDR: 172.30.0.0/16
  networkID: vpc-b60475d3
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.30.5.0/24
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 2600:1f18:14a:9010::/64
    name: us-east-1a1
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-08T09:55:55Z"
  generation: 8
  labels:
    kops.k8s.io/cluster: clustername.dev1.k8s.local
  name: master-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210503
  machineType: t3a.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-08T09:55:55Z"
  generation: 6
  labels:
    kops.k8s.io/cluster: clustername.dev1.k8s.local
  name: nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210503
  machineType: r5.large
  maxSize: 20
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
` kops update cluster --yes --admin

*********************************************************************************

A new kubernetes version is available: 1.20.15
Upgrading is recommended (try kops upgrade cluster)

More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_k8s.md#1.20.15

*********************************************************************************

I0517 15:57:31.294034     473 apply_cluster.go:483] Gossip DNS: skipping DNS validation
W0517 15:57:31.316386     473 yaml.go:57] unexpected type for object metadata: map[interface {}]interface {}
W0517 15:57:31.316710     473 yaml.go:57] unexpected type for object metadata: map[interface {}]interface {}
I0517 15:57:31.579052     473 executor.go:111] Tasks: 0 done / 90 total; 42 can run
I0517 15:57:31.926960     473 executor.go:111] Tasks: 42 done / 90 total; 17 can run
W0517 15:57:32.468708     473 executor.go:139] error running task "Subnet/us-east-1a1.clustername.dev1.k8s.local" (9m59s remaining to succeed): error creating subnet: InvalidParameterValue: Value (2600:1f18:14a:9010::/64) for parameter cidrBlock is invalid. This is not a valid CIDR block.
        status code: 400, request id: a987499f-8353-4fbf-9a6b-9227266d1f4e
W0517 15:57:32.468793     473 executor.go:139] error running task "Subnet/us-east-1a.clustername.dev1.k8s.local" (9m59s remaining to succeed): InvalidCidrBlock.InUse: The subnet subnet-0c5b1ef703baf2ff3 currently has an interface within CIDR block 2600:1f18:14a:9010::/64
        status code: 400, request id: d7e982bb-2202-46a4-98f8-9c9c2aa60f01
I0517 15:57:32.469037     473 executor.go:111] Tasks: 57 done / 90 total; 22 can run
W0517 15:57:32.791793     473 executor.go:139] error running task "Subnet/us-east-1a.clustername.dev1.k8s.local" (9m59s remaining to succeed): InvalidCidrBlock.InUse: The subnet subnet-0c5b1ef703baf2ff3 currently has an interface within CIDR block 2600:1f18:14a:9010::/64
        status code: 400, request id: ca2f86e7-b444-4eba-8aa0-9a018b92ec7e
W0517 15:57:32.791847     473 executor.go:139] error running task "Subnet/us-east-1a1.clustername.dev1.k8s.local" (9m59s remaining to succeed): error creating subnet: InvalidParameterValue: Value (2600:1f18:14a:9010::/64) for parameter cidrBlock is invalid. This is not a valid CIDR block.
        status code: 400, request id: 0cbe7c05-1d41-44a9-83d7-e17aa2e12bc9
I0517 15:57:32.791891     473 executor.go:111] Tasks: 77 done / 90 total; 2 can run
W0517 15:57:33.087676     473 executor.go:139] error running task "Subnet/us-east-1a1.clustername.dev1.k8s.local" (9m58s remaining to succeed): error creating subnet: InvalidParameterValue: Value (2600:1f18:14a:9010::/64) for parameter cidrBlock is invalid. This is not a valid CIDR block.
        status code: 400, request id: 1ad169e5-64ad-4cb5-95ba-80b24de2a4cd
W0517 15:57:33.087757     473 executor.go:139] error running task "Subnet/us-east-1a.clustername.dev1.k8s.local" (9m58s remaining to succeed): InvalidCidrBlock.InUse: The subnet subnet-0c5b1ef703baf2ff3 currently has an interface within CIDR block 2600:1f18:14a:9010::/64
        status code: 400, request id: 62b6980d-68da-4bae-9b42-6d35de10f3e3
I0517 15:57:33.087795     473 executor.go:155] No progress made, sleeping before retrying 2 task(s)
`
**9. Anything else do we need to know?**

**Comment by IgalSc** [comment]
To fix the issue, I tried running  **kops edit cluster**, and added the ipv6 CIDR to the VPC and added the subnet CIDR as well

```# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-04-08T09:55:55Z"
  generation: 5
  name: clustername.dev1.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://clustername-imesh-kops-state-store/clustername.dev1.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.8
  masterInternalName: api.internal.clustername.dev1.k8s.local
  masterPublicName: api.clustername.dev1.k8s.local
  networkCIDR: 172.30.0.0/16
  additionalNetworkCIDRs:
  - 2600:1f18:14a:9000::/56
  networkID: vpc-b60475d3
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.30.5.0/24
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 2600:1f18:14a:9010::/64
    name: us-east-1a1
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public```

**Comment by hakman** [comment]
@IgalSc IPv6 requires kOps 1.23 as mention in the [docs]. (https://kops.sigs.k8s.io/networking/ipv6). Migration of existing clusters to IPv6 is not supported.
I would suggest starting with a fresh IPv6 cluster and experiment.

**Comment by IgalSc** [comment]
the issue was resolved here 
https://github.com/kubernetes/kops/issues/13949
