### ISSUE TITLE
Private Topology - Are NGW, EIPs, and Subnets a 1:1:1 relationship?

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1368]
So..

Rumor has it that we can share NGWs and EIPs between certain resources in AWS.

Right now in private topology we create 1 EIP for 1 NGW per private Subnet.. there might be some sharing that can happen here - which would be a **huge** win

We need to explore, and possibly code this in

**Comment by justinsb** [comment]
It would also be good to know if it is possible to have 2 NAT gateways (in different AZs) both as the default route for a single route table.

**Comment by itskingori** [comment]
Just chipping in on the discussion bout NATs. [According to the docs][1] ...

> Each NAT gateway is created in a specific Availability Zone and implemented with redundancy in that zone.

So it's probably best to have a NAT/AZ at a minimum? So that we are not routing traffic from a private subnet in one AZ through a NAT in another AZ (of course, assuming that's possible in the first place).

I presume, routing traffic across AZs (even though they are connected by low-latency links), doesn't beat routing traffic to physically co-located devices. Even if possible, I'm not sure when this would be preferred.

[1]: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-gateway.html#nat-gateway-basics

**Comment by justinsb** [comment]
Yes, I think our current settings are the right ones.  The open is whether we could allow some compromise (for example running two NAT gateways for 3 AZs, instead of 3...) for costs or because there are some pretty low default limits for elastic ips etc.

**Comment by cwhenderson20** [comment]
I just wanted to chime in quickly that, while one NAT gateway per AZ is the standard and preferable for HA, it is quite cost-prohibitive (at least for smaller companies). Each gateway costs around $30/mo minimum, so it'd be great to allow sharing between one or two gateways total.

I understand that this is possible via manual setup, but at this current juncture, it defeats much of the purpose of using kops (given that you'd have to create and set up the VPC, all of the subnets, the routing tables, and the NAT Gateways before even running a kops create cluster command).

**Comment by justinsb** [comment]
@cwhenderson20 the private topology is definitely a more-expensive, more specialized option.  The public topology remains much cheaper, very much supported, and something I typically run myself.  Private topologies will let us get to HIPAA-compatible clusters (and the like), but public topologies are still very much secure.

I guess the question is what can we do to make the private option cheaper:

* We could reimplement NAT gateways, by having an instance perform the role.  It think the cost would be more like $10 / month than $30 / month if we were able to use t2.micros, so it is potentially worthwhile.  It also bypasses the per GB charge.
* For sharing a NAT gateway, I think the difference only arises in practice with 3 AZs.  With 1 AZ, you need 1 NAT gateway.  If you're running multi-AZ HA, you probably don't want to make the NAT gateway a single point of failure, so you probably need 2 NAT gateways in different AZs (?).  So with 3 AZs, we could run 2 NAT gateways.  It's a savings, but it isn't a huge one (sadly).

That said, I think we'll be working to allow this, probably in conjunction with the proposal to export the network configuration separately from cluster configuration, which I think also increases our flexibility.

Am I overlooking a trick in terms of potential savings @cwhenderson20 ?

**Comment by cwhenderson20** [comment]
@justinsb I definitely like the idea of having a NAT instance as an available option as many times the power of a NAT gateway (and thus the increased cost of ownership) isn't necessary for smaller distributions. I believe that AWS does provide a premade AMI exactly for this purpose.

I guess the point I'm making is that if it's configurable, it should be left up to the user to define the HA tolerance. In other words, if a user setting up a cluster wants to have only one NAT gateway despite having instances in three AZs, that can be an explicit choice. But I believe the default of having one NAT gateway per AZ is definitely sane (just not always the preferred option).
