### ISSUE TITLE
kops create command fails with "path xyz must be of a type that can render in Terraform"

### ISSUE THREAD

**Issue by mdbr000** [kubernetes/kops#13688]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.23.2 (git-4125bbbe975ca104c609ceaa625a9a5ff3ac19f4)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
```

**3. What cloud provider are you using?**
`aws`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create cluster \
  --name=k8s-testing-dev.k8s.local \
  --cloud=aws \
  --state=${PWD}/kops_state_store \
  --target=terraform \
  --zones=us-west-2b \
  --out=.
```

**5. What happened after the commands executed?**
Received a bunch of error messages that all followed the same pattern: `path XXXXX must be of a type that can render in Terraform`.  This appears to be coming from [`upup/pkg/fi/fitasks/managedfile.go` on line 130.](https://github.com/kubernetes/kops/blob/288d205bbd688b1344c8ee1cf7afe2e3f77dbd5d/upup/pkg/fi/fitasks/managedfile.go#L215)

More examples of the error msg:
```
W0527 12:00:27.936034  763634 executor.go:139] error running task "ManagedFile/k8s-testing-dev.k8s.local-addons-limit-range.addons.k8s.io" (9m59s remaining to succeed): path "/home/abcdefg/Downloads/temp/kops_state_store/k8s-testing-dev.k8s.local/addons/limit-range.addons.k8s.io/v1.5.0.yaml" must be of a type that can render in Terraform
W0527 12:00:27.936045  763634 executor.go:139] error running task "ManagedFile/manifests-static-kube-apiserver-healthcheck" (9m59s remaining to succeed): path "/home/abcdefg/Downloads/temp/kops_state_store/k8s-testing-dev.k8s.local/manifests/static/kube-apiserver-healthcheck.yaml" must be of a type that can render in Terraform
W0527 12:00:27.936061  763634 executor.go:139] error running task "ManagedFile/etcd-cluster-spec-events" (9m59s remaining to succeed): path "/home/abcdefg/Downloads/temp/kops_state_store/k8s-testing-dev.k8s.local/backups/etcd/events/control/etcd-cluster-spec" must be of a type that can render in Terraform
W0527 12:00:27.936075  763634 executor.go:139] error running task "ManagedFile/kops-version.txt" (9m59s remaining to succeed): path "/home/abcdefg/Downloads/temp/kops_state_store/k8s-testing-dev.k8s.local/kops-version.txt" must be of a type that can render in Terraform
W0527 12:00:27.936080  763634 executor.go:139] error running task "ManagedFile/k8s-testing-dev.k8s.local-addons-bootstrap" (9m59s remaining to succeed): path "/home/abcdefg/Downloads/temp/kops_state_store/k8s-testing-dev.k8s.local/addons/bootstrap-channel.yaml" must be of a type that can render in Terraform
W0527 12:00:27.936097  763634 executor.go:139] error running task "ManagedFile/k8s-testing-dev.k8s.local-addons-coredns.addons.k8s.io-k8s-1.12" (9m59s remaining to succeed): path "/home/abcdefg/Downloads/temp/kops_state_store/k8s-testing-dev.k8s.local/addons/coredns.addons.k8s.io/k8s-1.12.yaml" must be of a type that can render in Terraform
```

**6. What did you expect to happen?**
For the .tf file(s) to be written to the file system location specified by `--out` with no errors.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
I don't have a cluster yet.  I am trying to use this command to create .tf definitions to build a cluster.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
[gist log](https://gist.github.com/mdbr000/0fde2ac1852175a728bbd13c7efced0f)

**9. Anything else do we need to know?**
It looks like the error is being thrown because the .yaml files simply don't exist.

**Comment by hakman** [comment]
`--state=...` must be a cloud path, most commonly S3. Instances need to be able to read that state store.

**Comment by mdbr000** [comment]
@hakman Thank you for the response, you are right, setting the `--state` flag to an S3 bucket fixes the issue.

The documentation on [Building Kubernetes clusters with Terraform](https://kops.sigs.k8s.io/terraform/#building-kubernetes-clusters-with-terraform) states the following: `You could keep your Terraform state locally, but we strongly recommend saving it on S3 with versioning turned on that bucket. Configure a remote S3 store with a setting like below:`

This is a bit confusing and led to the filing of this bug.  The implication is that a local state store is possible, but 
1. It sounds like S3 or similar cloud storage is required if using the `--target=terraform` arg?
2. It's not totally clear that kops state is required to have cloud storage and terraform state is not

**Comment by hakman** [comment]
Exactly! 😄 
The confusion comes from the similarly named Terraform state store and kOps state store.
You can have a local state store for Terraform, but kOps has its own that needs to be accessible from the kOps master nodes. https://github.com/kubernetes/kops/blob/master/docs/state.md
Docs can be improved for sure. Will try to make things more clear there.

**Comment by wabkia** [comment]
a note in the getting started pages that explicitly says a remote kops store is required would be helpful in avoiding this issue.
