### ISSUE TITLE
Classic LB is created with irrelevant AZs

### ISSUE THREAD

**Issue by aberenshtein** [kubernetes/kops#13695]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.22.0
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
1.22.3
 a `kops` flag.**

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
create LB service type
Add the "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true" annotation

**5. What happened after the commands were executed?**
A classic LB was created with 3 AZs. 
Only one of the subnets is relevant (master and worker nodes run on a single AZ)

![Screen Shot 2022-05-29 at 14 33 14](https://user-images.githubusercontent.com/12783883/170866713-ac625531-1f42-4dff-a233-676b1ad9a700.png)

When you run `dig` to resolve the IPs, the application would something get the IP of the irrelevant subnet and could pass traffic to the pods.

**6. What did you expect to happen?**
Only one AZ should be set 

**9. Anything else do we need to know?**
This is a staging cluster, so to save money:
Master nodes are configured to run on a single AZ
Worker nodes are configured to run on a single AZ

Didn't happen on every LB

**Comment by olemarkus** [comment]
It's not the kOps components that creates load balancers from service objects, but the cloud controller manager. In 1.22, that is a part of kubernetes itself. As of kOps 1.24, it is this project: https://github.com/kubernetes/cloud-provider-aws

/remove-kind bug
/kind support

**Comment by aberenshtein** [comment]
Thanks
