### ISSUE TITLE
kubelet: unknown flag: --configure-cbr0

### ISSUE THREAD

**Issue by airstand** [kubernetes/kops#1369]
Hi,

I am trying to spin up whole kubernetes cluster with kops in AWS.
Using it with or without --target=terraform works fine while creates needed resources in AWS.
The issue is while maters and nodes are running - there is only one docker container - Protokube .. and kubelet is not able to start due to:
kubelet: unknown flag: --configure-cbr0

This option is defined in /etc/sysconfig/kubelet
in my file is: --configure-cbr0=false

In cluster.spec file:
    configureCbr0: false

If I remove the whole option "--configure-cbr0=false" .. kubelet starts normally and spins up all other containers for kubernetes services like api server, controller manager and etc.

I am using:
kubelet - v1.5.1
kops - git-8470034

I am creating the cluster with kops create...:
--kubernetes-version=1.5.1
--image=ami-73813513
--topology=private
--bastion=true
--networking=cni

I saw that while using --target=terraform .. nodeup version stays to version 1.4.2 in user data files. (is not changed to version 1.5.0 ) - I am not sure if that should be changed by using different version of kubernetes.

**Comment by chrislovecnm** [comment]
Can u try with another networking option such as kopeio-vxlan or weave? We may have an edge case with cni.

**Comment by airstand** [comment]
@chrislovecnm there is no difference which network type will be used. I have tested all of them.

**Comment by airstand** [comment]
@chrislovecnm Now .. using latest master release .. kubelet is working fine with network mode weave.

**Comment by OwainPerry** [comment]
I have been having this issue , tried using kops released versions and kops compiled from master (a46f1109cee)  as above removing  "--configure-cbr0=false"  from /etc/sysconfig/kubelet fixes the issue. not sure what else to tell you?

**Comment by airstand** [comment]
@OwainPerry as I know .. kubernetes does not support cni networking in the new versions. Dont know which version you are trying to deploy with kops .., but try to use networking=weave

**Comment by OwainPerry** [comment]
so when I built this cluster I had specified weave. and looking at the kops yaml I have (and always had) 
networking:
    weave: {}

However this seems to have been ignored. with various version of kops 1.5.x , at present all my nodes are back with pods running, but the networking is broken 
running  _cat /etc/sysconfig/kubelet_ on a node has --network-plugin=cni  in the args list....

**Comment by justinsb** [comment]
@OwainPerry since 3aae164d806dc9c43832f87c045c1073dcd655f3 this should have been fixed on the master branch (which will become kops 1.5).  However, that version that you are running is pretty old, and looks like it predates 3aae164d806dc9c43832f87c045c1073dcd655f3.  I would hope that pulling latest and rebuilding from source will fix this, as will running alpha4 when it is released.

I'll take a second look though for any edge cases we may have missed!

**Comment by justinsb** [comment]
Going to close ... pushing for the kops 1.5.0 release.

Please comment / reopen if you continue to see problems with kops 1.5.0 beta1 or later.
