### ISSUE TITLE
Document how to use bastion (i.e. SSH agent usage)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1371]
We should have docs that make it easy to understand how to use the bastion

**Comment by justinsb** [comment]
Keeping open as I want to work on step-by-step docs, and this a hot-button issue

**Comment by chrislovecnm** [comment]
https://sanctum.geek.nz/arabesque/tag/ssh-agent/ Good resource

**Comment by kris-nova** [comment]
CC @evildandelions
