### ISSUE TITLE
found duplicate tasks with name "DNSZone/ZGQJ6GJOGZN3"

### ISSUE THREAD

**Issue by airstand** [kubernetes/kops#1374]
@kris-nova Hello :)

Version 1.5.0-alpha1
On kops update cluster ...
I0106 15:24:37.166259    3763 populate_cluster_spec.go:243] Defaulting DNS zone to: ZGQJ6GJOGZN3
I0106 15:24:43.197000    3772 populate_cluster_spec.go:243] Defaulting DNS zone to: ZGQJ6GJOGZN3
I0106 15:24:49.582558    3781 populate_cluster_spec.go:243] Defaulting DNS zone to: ZGQJ6GJOGZN3
I0106 15:24:55.426915    3790 populate_cluster_spec.go:243] Defaulting DNS zone to: ZGQJ6GJOGZN3
I0106 15:25:02.043926    3799 populate_cluster_spec.go:243] Defaulting DNS zone to: ZGQJ6GJOGZN3
I0106 15:25:05.631680    3807 populate_cluster_spec.go:243] Defaulting DNS zone to: ZGQJ6GJOGZN3
F0106 15:25:06.194288    3807 task.go:55] found duplicate tasks with name "DNSZone/ZGQJ6GJOGZN3": *awstasks.DNSZone {"Name":"ZGQJ6GJOGZN3","ID":null,"Private":true,"PrivateVPC":{"Name":"kube-test.idbs-dev.com","ID":null,"CIDR":null,"EnableDNSHostnames":null,"EnableDNSSupport":null,"Shared":null}} and *awstasks.DNSZone {"Name":"ZGQJ6GJOGZN3","ID":null,"Private":false,"PrivateVPC":null}

**Comment by kris-nova** [comment]
Thanks for the report here. Will take a look and see what I can find.

**Comment by airstand** [comment]
Ok .. I will take a look forward.
