### ISSUE TITLE
karpenter error

### ISSUE THREAD

**Issue by HHongSeungWoo** [kubernetes/kops#13754]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Client version: 1.24.0-beta.1 (git-v1.24.0-beta.1)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```shell
kops create cluster --name=${NAME} \
--cloud=aws \
--zones=${AWS_ZONE} \
--discovery-store=${KOPS_OIDC_STORE}/${NAME}/discovery \
--networking=calico \
--topology=private \
--instance-manager=karpenter
```

**5. What happened after the commands executed?**

karpenter is not installed.

**6. What did you expect to happen?**

karpenter controller would be provisioned

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

journalctl log

```
Jun 09 06:19:28 ip-172-20-45-155 protokube[3803]: I0609 06:19:26.843940    5115 addon.go:169] Applying update from "s3://k8s-bucket/cluster.example.com/addons/karpenter.sh/k8s-1.19.yaml"
Jun 09 06:19:28 ip-172-20-45-155 protokube[3803]: I0609 06:19:26.843966    5115 s3fs.go:329] Reading file "s3://k8s-bucket/cluster.example.com/addons/karpenter.sh/k8s-1.19.yaml"
Jun 09 06:19:28 ip-172-20-45-155 protokube[3803]: I0609 06:19:26.872540    5115 apply.go:60] Running command: kubectl replace -f /tmp/channel2741225462/manifest.yaml --force --field-manager=kops
Jun 09 06:19:28 ip-172-20-45-155 protokube[3803]: I0609 06:19:27.262620    5115 apply.go:63] error running kubectl replace -f /tmp/channel2741225462/manifest.yaml --force --field-manager=kops
Jun 09 06:19:28 ip-172-20-45-155 protokube[3803]: I0609 06:19:27.262640    5115 apply.go:64] Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
Jun 09 06:19:28 ip-172-20-45-155 protokube[3803]: unable to recognize "/tmp/channel2741225462/manifest.yaml": no matches for kind "Provisioner" in version "karpenter.sh/v1alpha5"
```

**Comment by hakman** [comment]
By any chance, did you set also the feature flag?
https://kops.sigs.k8s.io/operations/karpenter/
```
export KOPS_FEATURE_FLAGS="Karpenter"
```

**Comment by hakman** [comment]
Sorry, just checked and seems it also reproduces in our karpenter periodic [tests](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-misc-karpenter/1534694976955355136/artifacts/i-0971be8dc15206f07/protokube.log).
@olemarkus If you have some time maybe you can take a look.

**Comment by hakman** [comment]
We checked and we think this is an issue introduced in the version you are using. Could you give it a try on new cluster with [v1.24.0-alpha.5](https://github.com/kubernetes/kops/releases/tag/v1.24.0-alpha.5)?

**Comment by HHongSeungWoo** [comment]
@hakman good, it works
