### ISSUE TITLE
kubectl logs timeout for all pods on some nodes

### ISSUE THREAD

**Issue by MeirP-3** [kubernetes/kops#13752]
/kind bug

**Kops version:** 1.23.2
**Kubernetes version:** 1.23.6
**Cloud provider:** AWS, external cloud controller manager (`spec.cloudControllerManager.cloudProvider: aws`), AWS VPC CNI  (`spec.networking.amazonvpc: {}`)
[See the full cluster spec here](https://gist.github.com/MeirP-3/386e40f0659839799e3819c8acc37598)
**Command:** `kubectl logs -c <container-name> <pod-name>`

For pods that belong to some nodes in the cluster, kubectl logs fails with error message `Error from server: Get "https://<IPV4-address>:10250/containerLogs/<namespace-name>/<pod-name>/<container-name>": dial tcp <IPV4-address>:10250: i/o timeout`.

With kubectl verbose logging, here is the full error message from the API server:
```
server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Get "https://<IPV4-address>:10250/containerLogs/<namespace-name>/<pod-name>/<container-name>": dial tcp <IPV4-address>:10250: i/o timeout",
  "code": 500
}]

```

Looks like the API server tries to connect to kubelet via `<IPV4-address>:10250` and gets timeout.

I observe an inconsistency about the IP of the node:
- **The IP address in the error message:**
  - Is the primary IP of **one** of the nodes' associated network interfaces
  - Its network interface description is in the form of `aws-K8S-<instance-id>` (`aws ec2 describe-network-interfaces --network-interface-ids <id> --query 'NetworkInterfaces[*].Description'`)
  - Is the first address in `.status.addresses` when running `kubectl get node -o yaml <node-name>`.
  - Is shown in `.status.hostIP` in the pod.
  - Is shown as the node IP when running `kubectl get node -o wide <node-name>`.
  - SSH to the node via this IP fails.

- **Another IP address:**
  - Is the primary IP of another node's associated network interface
  - Its network interface description is `eth0` (`aws ec2 describe-network-interfaces --network-interface-ids <id> --query 'NetworkInterfaces[*].Description'`)
  - Is the value of the node annotation `alpha.kubernetes.io/provided-node-ip`
  - SSH to the node with this IP is successful

Questions:
* Is SSH blocking on the other primary IPs intended? I remember being able to SSH with all the primary IPs, in a previous version.
* What possibly can cause the inconsistency of the IP address that belongs to the node, and how can I work around this?

Thanks in advance!

**Comment by olemarkus** [comment]
This looks like https://github.com/kubernetes/cloud-provider-aws/issues/349

This has been fixed in kops 1.24 using k8s 1.24. I think the 1.23 image with this fix has not been published yet.

**Comment by olemarkus** [comment]
Actually, setting the image to the 1.24 version should work just fine. there is nothing in 1.24 that should break a 1.23 cluster.

kOps 1.24 is also expected in the near future though.

**Comment by MeirP-3** [comment]
I've set the image of cloud controller manager to `1.24.0` and now the problem is solved. Thanks!

Closing.
