### ISSUE TITLE
Unable to validate my cluster using kops

### ISSUE THREAD

**Issue by dhinesh2287** [kubernetes/kops#13778]
I have created the cluster using kops method while validating iam getting connection refused error i have open the ports in the security group also can anyone help in this to solve the issue and also sometime getting Handshake timeout also
<img width="960" alt="timeout" src="https://user-images.githubusercontent.com/99251741/173197610-ce46626e-e80e-4d78-84e3-74b071d98e07.png">

<img width="960" alt="issues" src="https://user-images.githubusercontent.com/99251741/173197141-14927d59-8338-47a3-886c-64a3d121c322.png">

**Comment by olemarkus** [comment]
Can you please follow the bug template?

By the looks of it, you are using an ELB for the API and none of the API servers are responding.

**Comment by dhinesh2287** [comment]
By using the below one i have created my cluster need to modify anything in this?
kops create cluster  --cloud aws --node-size t2.micro --master-size t2.micro --state s3://kubernetes.suitemanage.xyz --networking calico --zones us-west-1a --name kubernetes.suitemanage.xyz --dns-zone kubernetes.suitemanage.xyz --dns public

**Comment by olemarkus** [comment]
Most likely t2.micro is too small to run the control plane. Try t3.medium instead.
