### ISSUE TITLE
terraform: validate we can have two clusters in one "mega-directory"

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1381]
I believe this is a common request, and we should make sure it works.

**Comment by kris-nova** [comment]
Directory in what? The state store?

**Comment by kris-nova** [comment]
Oops - nevermind - terraform

**Comment by justinsb** [comment]
It seems like terraform recommends using modules instead.  Closing.

**Comment by justinsb** [comment]
(We could ensure everything is named uniquely, but the provider block must be configured with a region, and it doesn't look like you can have more than one block if you're in a different module)
