### ISSUE TITLE
Periods in S3 Bucket Name Break IRSA

### ISSUE THREAD

**Issue by ReillyBrogan** [kubernetes/kops#13817]
/kind bug

IRSA is broken when the bucket used for the IRSA OIDC discovery store contains at least one period. This is because the discovery store is registered as a federated identity provider with IAM having the domain https://bucket_name.s3.region.amazonaws.com, which is covered with a wildcard SSL certificate for *.s3.region.amazonaws.com. Having a period in that name causes the wildcard certificate to no longer be valid for the bucket as wildcard certificates do not protect subdomains beyond the level of the wildcard (IE they are valid for *.example.com, not *.*.example.com). 

I looked into whether S3 access points could be an option but it appears that they do not support unauthenticated access like is needed for this. It is likely possible to cobble something together using cloudfront but that's probably far too much added complexity. 

I think the best solution is to just add a validation rule to reject configurations that have a period in  `.spec.serviceAccountIssuerDiscovery.discoveryStore` with a error message to that effect. This would prevent administrators from using an invalid configuration in the first place.

**Comment by olemarkus** [comment]
That sounds reasonable. Are you able to do a PR adressing this?
