### ISSUE TITLE
maximum instance lifetime setting for AWS ASG

### ISSUE THREAD

**Issue by sterchelen** [kubernetes/kops#13820]
👋🏼 
I didn't find any settings related to [maximum instance lifetime](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-ec2-auto-scaling-supports-max-instance-lifetime/) in kops code. That is why I propose to implement this feature in kops.

Maximum instance lifetime can help to introduce ephemerality in a Kubernetes environment. 
From the AWS documentation:
> it helps you ensure that instances are recycled before reaching the specified lifetime, giving you an automated way to adhere to your security, compliance, and performance requirements.

I would be happy to implement this new feature.

**Comment by olemarkus** [comment]
This is something I've been wanting as well. I would be happy to review your PR.

/kind feature
