### ISSUE TITLE
kops does not remove the ASG's MixedSpotMaxPrice when maxPrice is removed from the instance group manifest

### ISSUE THREAD

**Issue by danports** [kubernetes/kops#13849]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.23.2 (haven't tested on any 1.24.x prerelease versions)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.23.8

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Modify an instance group manifest to remove the `maxPrice` setting, run `kops replace -f my-instance-group.yaml`, and then run `kops update cluster`.

**5. What happened after the commands executed?**

The `kops update cluster` dry run output shows no changes to the instance group's ASG.

**6. What did you expect to happen?**

The dry run output should include something like this under the ASG for the instance group:
```
  	MixedSpotMaxPrice   	 0.01 -> <nil>
```

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Can provide later if needed

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Can provide later if needed

**9. Anything else we need to know?**

If you make an unrelated change to the instance group, then kops will finally realize that the ASG's `MixedSpotMaxPrice` field needs to be updated...but even then, it doesn't actually update the ASG's `MixedSpotMaxPrice` field.

**Comment by olemarkus** [comment]
Looks like this field is not reconciling when set to nil. That's indeed a bug.

**Comment by olemarkus** [comment]
There are CI binaries. Easiest is probably to look at the build log and see where they are uploaded.
The script at https://kops.sigs.k8s.io/contributing/test_versions/#testing-a-pull-request unfortunately doesn't work .. I can see if I can also fix that tomorrow.

**Comment by danports** [comment]
I browsed the build logs and didn't see the place in the output where the binaries are uploaded - perhaps I wasn't looking for the right thing or in the right place. If you could point me in the right direction, I'll give the CI build a try, or eventually I'll get around to building the branch myself and testing. In the meantime, the workaround of just setting `maxPrice` arbitrarily large works fine.
