### ISSUE TITLE
RBAC update for AWS EBS CSI

### ISSUE THREAD

**Issue by dmytronasyrov** [kubernetes/kops#13887]
I'm deploying a cluster with KOPS into AWS and I'm using aws-ebs-csi-driver, v1.7.0.
Everything works pretty well in eu-central-1. But once I deployed into us-east-1 the issue arrived. The master node is hanging on RBAC for EBS CSI. The error is:

> Failed to contact API server when waiting for CSINode publishing: csinodes.storage.k8s.io "ip-172-0-0-17.ec2.internal" is forbidden: User "system:node:ip-172-0-0-17.us-east-1.compute.internal" cannot get resource "csinodes" in API group "storage.k8s.io" at the cluster scope: can only access CSINode with the same name as the requesting node

Meaning I should add the rule like this one:

> - apiGroups: ["storage.k8s.io"]
>     resources: ["csinodes"]
>     verbs: ["get", "list", "watch"]

to _ClusterRole ebs-external-attacher-role_

I tried to add it on top of the existing ClusterRole, but not lucky to get rid of the issue even after master IGs restarted.
Please advise how to inject additional rules to CSI addon during cluster deployment.

**Comment by olemarkus** [comment]
Where do you see those errors?

**Comment by dmytronasyrov** [comment]
> Where do you see those errors?

/var/log/syslog

**Comment by olemarkus** [comment]
So its not related to RBAC for EBS CSI driver then. Looks like your node is not registering properly. Can you attach more of the kubelet logs?

**Comment by dmytronasyrov** [comment]
> Jun 27 07:55:46 ip-172-0-0-17 kubelet[4820]: E0627 07:55:46.270589    4820 kubelet.go:2466] "Error getting node" err="node \"ip-172-0-0-17.ec2.internal\" not found"
> Jun 27 07:55:46 ip-172-0-0-17 kubelet[4820]: I0627 07:55:46.286896    4820 csi_plugin.go:1063] Failed to contact API server when waiting for CSINode publishing: csinodes.storage.k8s.io "ip-172-0-0-17.ec2.internal" is forbidden: User "system:node:ip-172-0-0-17.us-east-1.compute.internal" cannot get resource "csinodes" in API group "storage.k8s.io" at the cluster scope: can only access CSINode with the same name as the requesting node

These 2 messages repeat in an endless loop. I don't get why it's ok in Frankfurt and not good in N.Virginia.

**Comment by olemarkus** [comment]
I think something else is up with your cluster configuration. Note how your node name is `ip-172-0-0-17.ec2.internal` while your node user is `ip-172-0-0-17.us-east-1.compute.internal`. Could it be your DHCP options is missing `ec2.`?

**Comment by dmytronasyrov** [comment]
Thank you. us-east-1 VPC domain name should be **ec2.internal**, all other regions **region.compute.internal**
