### ISSUE TITLE
Add --wait argument to `cluster create`

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#139]
Could be optional, but could wait for machines to be started, DNS to resolve etc

**Comment by blakebarnett** [comment]
Would this just loop on the `kops validate` logic?

**Comment by kenden** [comment]
@blakebarnett Yes.
I think we should close this ticket as duplicate (of https://github.com/kubernetes/kops/issues/1517). This one is older but the other has more info/comments.
