### ISSUE TITLE
Image protokube-linux-arm64 not found for 1.21.5

### ISSUE THREAD

**Issue by fals** [kubernetes/kops#13900]
/kind bug

The link to the image https://artifacts.k8s.io/binaries/kops/1.21.5/images/protokube-linux-arm64 is broken.

The link was originally added in this commit: https://github.com/kubernetes/kops/pull/12800/files#diff-6c2c162676392ea6cd5bf7ea1e52df8f63113dfbd78a5fd1fdac39bf32459e7d

**Comment by hakman** [comment]
I think the correct path is https://artifacts.k8s.io/binaries/kops/1.21.5/linux/amd64/protokube.
That test needs an update 😄.

**Comment by fals** [comment]
> I think the correct path is https://artifacts.k8s.io/binaries/kops/1.21.5/linux/amd64/protokube. That test needs an update 😄.

Do you have any reference I could follow, other links are also broken, and for version 1.22.5, all of them are broken.

**Comment by fals** [comment]
@hakman OK I got it know. I'm going to push a PR updating both 1.21.5 and 1.22.5.

**Comment by hakman** [comment]
Not quite sure what you want to update. Those should be removed. It is just a unit test that is no longer relevant.
