### ISSUE TITLE
AWS AMI life cycle

### ISSUE THREAD

**Issue by nealtsai1981** [kubernetes/kops#13906]
Hi there,

Do you have the policy to maintain the KOPS AMI life cycle on AWS? Currently we are using the one, k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17 on AWS, but not sure how the life cycle it is and when should we update it in case we can't use it in the future. Do you have any idea on it? 

Thank you very much,
Neal

**Comment by nealtsai1981** [comment]
Hakman, 

Thank you for the prompt feedback!!!  Sure, we are always good at following the latest version, however, some production env. we used still stuck at older version like k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17 and need time to upgrade, we are afraid that it would be serious impact if it's taken down soon. So I'd like to ask if there's any policy to remove the AMI.

Thanks,
Neal

**Comment by hakman** [comment]
Not sure what is unclear or you mean by policy.
`k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17` is just a offical Debian Strech AMI with some tweaks and some packages installed. All that is checked and adjusted by kOps during bootstrap also when using the offical Debian Strech AMI, just that it takes about 1 min longer.

**Comment by nealtsai1981** [comment]
Got it, but as this Debian Strectch AMI is tweaked by kOps and the maintained owner is also kOps, will it be considered to be removed from AWS AMI, if it's too old? If so, will it have the timeline to be removed?

**Comment by nealtsai1981** [comment]
Got it, thank you for your time replying this, it helps a lot. :)
