### ISSUE TITLE
Unable to update load balancer type on AWS (dual stack cluster)

### ISSUE THREAD

**Issue by IgalSc** [kubernetes/kops#13949]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.23.2 (git-4125bbbe975ca104c609ceaa625a9a5ff3ac19f4)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update cluster --yes

**5. What happened after the commands executed?**
I get an error 

When I change the spec.api.loadBalancer.class: Classic to Network and run `kops update cluster`, I get the list of changes to be done
When I run  `kops update cluster --yes`  I get the following error

`W0707 14:17:12.973685    4433 executor.go:139] error running task "SecurityGroupRule/https-lb-to-master-2600:abcd:efg:9000::/56" (9m59s remaining to succeed): error creating SecurityGroupIngress: InvalidParameterValue: CIDR block 2600:abcd:efg:9000::/56 is malformed`

**6. What did you expect to happen?**
Replace the Classic load balancer with Network load balancer

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```kops get --name clustername.k8s.local -o yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-07-06T20:17:52Z"
  generation: 3
  name: clustername.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://clustername1-kops-state-store/clustername.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-1
      name: a-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1b-1
      name: b-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-2
      name: a-2
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-1
      name: a-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1b-1
      name: b-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-2
      name: a-2
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.23.8
  masterInternalName: api.internal.clustername.k8s.local
  masterPublicName: api.clustername.k8s.local
  networkCIDR: 172.30.0.0/16
  additionalNetworkCIDRs:
  - 2600:abcd:efg:9000::/56
  networkID: vpc-b60475d3
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.30.32.0/19
    ipv6CIDR: 2600:abcd:efg:9020::/64
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 172.30.64.0/19
    ipv6CIDR: 2600:abcd:efg:9030::/64
    name: us-east-1b
    type: Public
    zone: us-east-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-07-06T20:17:52Z"
  labels:
    kops.k8s.io/cluster: clustername.k8s.local
  name: master-us-east-1a-1
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220615
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a-1
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-07-06T20:17:53Z"
  labels:
    kops.k8s.io/cluster: clustername.k8s.local
  name: master-us-east-1a-2
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220615
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a-2
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-07-06T20:17:52Z"
  labels:
    kops.k8s.io/cluster: clustername.k8s.local
  name: master-us-east-1b-1
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220615
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b-1
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-07-06T20:17:53Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: clustername.k8s.local
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220615
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: c6a.large
  maxSize: 3
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-07-06T20:17:53Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: clustername.k8s.local
  name: nodes-us-east-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220615
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: c6a.large
  maxSize: 3
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1b
  role: Node
  subnets:
  - us-east-1b
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I replaced the actual IPv6 CIDR with 2600:abcd:efg:9000::/56
I believe I'm doing something wrong, but the cluster works with spec.api.loadBalancer.class: Classic (without IPv6 support on the ELB)

Please help
Thanks
Igal

**Comment by olemarkus** [comment]
I think you went abit overboard with your alphabet there, mate. Hex sort of stops at `f`.

**Comment by IgalSc** [comment]
@olemarkus that's just lol
But as for the `kops update cluster`  - it doesn't work

**Comment by IgalSc** [comment]
Following my previous update, I tried deleting the cluster, running the `kops create cluster` , then `kops edit cluster`, update the ipv6CIDRs for the subnets, and change the loadbalancer type to Network. 
then I run `kops edit cluster --yes`, the cluster validates after a while.
Then I setup the gateway and the dashboard, but when I try to get the endpoints for the clustername-system namestapace, I get IPs, not LB DNS name like with the classic LB
`NAME          ENDPOINTS                         AGE
svc-gateway   100.96.3.7:5000                   13m
svc-nginx     100.96.4.5:5002,100.96.4.5:5001   13m`

If I try to access it associating my Route53 entry for the dashboard with the DNS name of the NLB that runs in front of the master nodes, i get "not secure" message and if I choose to proceed, the following error is displayed

`{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}`

**Comment by IgalSc** [comment]
Hi @olemarkus  I actually figured out how to set up the cluster with Network LB and IPv6
Following my previous update, I was wrong with associating the Dashboard with the NLB, I need to see what external endpoint is setup for the nginx service, then it works. 
However, there's another issue. 
The nodes LB is being created as Classic, and this is the one that the nginx service uses and all the rest of the deployments in our cluster are being accessed through it. So, if I need to have my nodes being behind NLB with IPv6 support, I need to specify this in the nodes specs after I update cluster, where I have to specify the TargetGroupARN
`spec:
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:us-east-1:ACCOUNTNAME:targetgroup/TG_NAME/TG_ID`

This leads to the following issues: 
* Need to setup the NLB and the Target Group(s) ahead of time 
* health check  ports on the Classical LB/Nodes are random and change every deployment 
* I need to manually allow health check on the nodes security group from the NLB **after** the nodes are updated 

Is there a way to overcome the issues described above?

**Comment by IgalSc** [comment]
This problem was resolved by not touching the Master loadbalncer, but introducing the following 
`metadata:
  name: svc-nginx1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "dualstack"
`
under the nginx service deployment
