### ISSUE TITLE
Bastion DNS Error

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1394]
error building tasks: unexpected error resolving task "DNSName/bastion-clove-k8s-1-6-1.alpha.trebuchet.ai": Unable to find task "DNSZone/Z1J8MO4IA1T0GC", referenced from DNSName/bastion-clove-k8s-1-6-1.alpha.trebuchet.ai:.Zone

^ unable to create cluster with bastion in private topo.  I am using 3 masters with 6 nodes in three AZ.

**Comment by kris-nova** [comment]
Looking at this now
