### ISSUE TITLE
too many arguments  in azureblob.go

### ISSUE THREAD

**Issue by devuser** [kubernetes/kops#13948]
# k8s.io/kops/util/pkg/vfs
../../../../../pkg/mod/k8s.io/kops@v1.23.2/util/pkg/vfs/azureblob.go:187:3: too many arguments in call to cURL.NewBlockBlobURL(p.key).Upload
	have (context.Context, io.ReadSeeker, azblob.BlobHTTPHeaders, azblob.Metadata, azblob.BlobAccessConditions, azblob.AccessTierType, azblob.BlobTagsMap, azblob.ClientProvidedKeyOptions, <T>)
	want (context.Context, io.ReadSeeker, azblob.BlobHTTPHeaders, azblob.Metadata, azblob.BlobAccessConditions, azblob.AccessTierType, azblob.BlobTagsMap, azblob.ClientProvidedKeyOptions)
../../../../../pkg/mod/k8s.io/kops@v1.23.2/util/pkg/vfs/azureblob.go:187:10: undefined: azblob.ImmutabilityPolicyOptions

Find bug when I test some package which imported k8s.io/kops/util/pkg/vfs

**Comment by olemarkus** [comment]
This looks like a mismatch in your dependencies vs kops dependencies.
Can you try upgrading your `github.com/Azure/azure-storage-blob-go`?
