### ISSUE TITLE
Release date for 1.24.0

### ISSUE THREAD

**Issue by yurrriq** [kubernetes/kops#13958]
Is there a timeline for the release of 1.24.0? I notice [50 commits to release-1.24 since beta.3](https://github.com/kubernetes/kops/compare/v1.24.0-beta.3...release-1.24). We're eager to adopt Cilium 1.11 and some other features, but hesitant to use the beta.

**Comment by olemarkus** [comment]
https://github.com/kubernetes/kops/pull/13957
