### ISSUE TITLE
Support for adding Load Balancer Flags - deletion protection - drop invalid header

### ISSUE THREAD

**Issue by razorsk8jz** [kubernetes/kops#13976]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

**2. Feel free to provide a design supporting your feature request.**

I would like to request having the ability for kops to set some flags when creating the elb/nlb for the Kubernetes api

We currently use ScoutSuite to scan our aws accounts and the network load balancers we are using consistently get flagged for not enabling deletion protection on the load balancer and for not setting the drop invalid headers field

It may be possible to enable these manually but i have not found a way to enable them via the cluster spec.

Here is an image to backup my use case and of what Scoutsuite considers critical/warning for elbv2 network load balancers 

<img width="496" alt="image" src="https://user-images.githubusercontent.com/12674178/179052097-b2b044b8-21f9-4070-893d-2795b826299e.png">

**Comment by hakman** [comment]
Any idea why deletion protection is being flagged? Seems more of a personal choice rather than a requirement.
Also, I don't think kOps protects any other component from deletion.

**Comment by hakman** [comment]
Also, based on [AWS docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html), `routing.http.drop_invalid_header_fields.enabled` can only be enabled for ALB, not NLB.
