### ISSUE TITLE
IRSA not working for kops 1.22.4

### ISSUE THREAD

**Issue by jakebyrd** [kubernetes/kops#13973]
/kind support

**1. What kops version are you running? The command kops version, will display
this information.**

1.22.4

**2. What Kubernetes version are you running? kubectl version will print the
version if a cluster is running or provide the Kubernetes version specified as
a kops flag.**

1.21.9

**3. What cloud provider are you using?**

AWS

**4. What commands did you run? What is the simplest way to reproduce this issue?**

```
serviceAccountIssuerDiscovery:
    discoveryStore: s3://bucket-name
    enableAWSOIDCProvider: true
```
was added to cluster spec as well as 

 `useServiceAccountExternalPermissions: true`

Service account and deployment were created through kubectl. 

Pod is running with the correct env variables for default region, region, role ARN, web-identity-token-file, and sts-regional-endpoints.

However, when running `kubectl exec -it -n default pod-identity-webhook-test -- aws sts get-caller-identity` or any other aws command I get the error:

`Unable to locate credentials. You can configure credentials by running "aws configure".`

**5. Anything else do we need to know?**

Not sure if this is an issue with just not having `pod-identity-webhook` but using newer version of `useServiceAccountExternalPermissions: true` .

Can share specific lines of cluster manifest or deployment if needed. 

AWS Role is also essentially the same as https://github.com/kubernetes/kops/blob/master/tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_iam_role_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy as well

**Comment by ReillyBrogan** [comment]
I don't believe that Kops 1.22.x is currently supported. You should upgrade to at least 1.23.2 and test there (Kops 1.23.x is compatible with Kubernetes 1.22.x).

Note also that the bucket you use for this cannot have any periods in the bucket name or it won't work. Note also that you need to use a different bucket than your state bucket and make sure that after you do a `kops update` that files are actually created in the oidc bucket.

> Kubernetes 1.22.1
Not that I think this is the culprit or anything but you should probably upgrade to the latest 1.22 release (1.22.11 I believe) just because there are a few known vulnerabilities in that version.

**Comment by jakebyrd** [comment]
So I was actually wrong about kubernetes version. We are running kubernetes 1.21.9. As far as the bucket, we have tried multiple buckets and none of them have periods in them. We can upgrade kops but how can we know that that will fix the issue? Also let me know if you need more info to troubleshoot this better.

**Comment by ReillyBrogan** [comment]
> We can upgrade kops but how can we know that that will fix the issue?

How do you know it won't? There have been a huge amount of bugfixes between Kops 1.22 and Kops 1.23/1.24 and IRSA has seen a number of them as the feature has continued to mature. Kops 1.23/1.24 does still support Kubernetes 1.21.

> We are running kubernetes 1.21.9

Kubernetes 1.21 is end of life. You should strongly consider upgrading.

> Also let me know if you need more info to troubleshoot this better.

Like I said in my previous comment you should check that `kops update cluster` is actually populating your OIDC bucket with the appropriate files and that the bucket has the right permissions on it (the bucket MUST be world-readable).

**Comment by h3poteto** [comment]
Did you install [pod-identity-webhook](https://github.com/aws/amazon-eks-pod-identity-webhook) manually? And is it working fine?

**Comment by ReillyBrogan** [comment]
You may be able to see the error in the pod-identity-webhook logs as well.

**Comment by jakebyrd** [comment]
So we have updated kops up to 1.23.2, however when using our pipeline we run into the following issue.
```
│ The plugin returned an unexpected error from
│ plugin.(*GRPCProvider).PlanResourceChange: rpc error: code =
│ ResourceExhausted desc = grpc: received message larger than max (4304578
│ vs. 4194304)
```
This error is with a certmanager-addons bucket object. This seems to be an issue with terraform, but wanted to reach out to see if you all thought it could be something else?

**Comment by olemarkus** [comment]
Are you manually installing the webhook? Or custom static pods? It seems like the webhook blocks pods that the webhook shouldn't care about.

**Comment by jakebyrd** [comment]
We installed using the default installation method that kops provides

**Comment by olemarkus** [comment]
Can you get the mutating webhook object and paste it here? It looks like it is matching things it never should. I am also confused about the webhook being installed before kops 1.23.

I also suggest updating to kops 1.24.
