### ISSUE TITLE
Additional CiliumNetworkingSpec Parameter "ToFQDNsMaxIPsPerHost"

### ISSUE THREAD

**Issue by hoepfnerj** [kubernetes/kops#14012]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I would like to set the Cilium parameter "tofqdns-endpoint-max-ip-per-hostname". Currently there seems to be no support for this in the kops spec. A way to set this parameter would be helpful.

**2. Feel free to provide a design supporting your feature request.**

The CiliumNetworkingSpec could be extended to support the (int) parameter "ToFQDNsMaxIPsPerHost". 

Generally Cilium offers a lot of parameters:
https://pkg.go.dev/github.com/cilium/cilium/pkg/option
Maybe kops could offer a more generic way to support all parameters so it does not have to mirror the developments of Cilium. Maybe a parameter of type "map[string]string"?

**Comment by olemarkus** [comment]
Happy to review a PR for this feature. An example to follow would be https://github.com/kubernetes/kops/pull/13684

**Comment by hoepfnerj** [comment]
Thanks, I will have look.
