### ISSUE TITLE
Able to export config of additional domain set by additionalSans

### ISSUE THREAD

**Issue by SCLogo** [kubernetes/kops#14013]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Currently we can set additional domains to access apiserver using proxy or with different domain. The original one (what we set during clustre create is immutable as I know), so when we have issue with cert renew or access that domain to change things, it would be good if we could export the config using the alternative domain we set

**2. Feel free to provide a design supporting your feature request.**
E.g. Select domain with --api-domain

**Comment by olemarkus** [comment]
You can change the exported domain by settings `spec.masterPublicName` in the cluster spec. Does this satisfy your needs?

**Comment by SCLogo** [comment]
So only spec.masterInternalName is immutable and PublicName is changeable ? That would solve my issue yes. Going to test it in the comming weeks.

**Comment by hakman** [comment]
Seems pretty much fixed. If there's anything else please reopen.
