### ISSUE TITLE
Protokube unable to apply policy/v1beta1 resources against k8s 1.21

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#14011]
/kind bug

The [k8s 1.21 -> k8s 1.22 upgrade prow job](https://testgrid.k8s.io/kops-upgrades#kops-aws-upgrade-k121-kolatest-to-k122-kolatest) is currently failing because [protokube is failing to apply some resources in the addon manifests](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-upgrade-k121-kolatest-to-k122-kolatest/1549542952282361856/artifacts/ip-172-20-46-89.sa-east-1.compute.internal/journal.log).

`Jul 19 23:59:34.874882 ip-172-20-46-89 protokube[3990]: I0719 23:59:34.671039    5838 apply.go:123] creating policy/v1, Resource=poddisruptionbudgets kube-system/calico-kube-controllers`

`Jul 19 23:59:34.874882 ip-172-20-46-89 protokube[3990]: I0719 23:59:34.869309    5838 request.go:533] Waited for 198.180194ms due to client-side throttling, not priority and fairness, request: POST:https://127.0.0.1/apis/policy/v1/namespaces/kube-system/poddisruptionbudgets`

`Jul 19 23:59:34.874882 ip-172-20-46-89 protokube[3990]: updating "coredns.addons.k8s.io": error applying update from "s3://k8s-kops-prow/e2e-ba4161b3c2-a27ab.test-cncf-aws.k8s.io/addons/coredns.addons.k8s.io/k8s-1.12.yaml": failed to apply objects of kind PodDisruptionBudget.policy: failed to create kube-system/kube-dns: the API version in the data (policy/v1beta1) does not match the expected API version (policy/v1); updating "networking.projectcalico.org": error applying update from "s3://k8s-kops-prow/e2e-ba4161b3c2-a27ab.test-cncf-aws.k8s.io/addons/networking.projectcalico.org/k8s-1.16.yaml": failed to apply objects of kind PodDisruptionBudget.policy: failed to create kube-system/calico-kube-controllers: the API version in the data (policy/v1beta1) does not match the expected API version (policy/v1)`

There are multiple failures in that log line but to focus on the calico manifest, the above log line confirms that it is trying to apply the k8s-1.16.yaml version which [uses policy/v1beta1 for kube-system/calico-kube-controllers](https://github.com/kubernetes/kops/blob/ea32e12ce780ab1a20e77c9eab909e0acce02b46/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template#L4695-L4706).

Protokube seems to be using the policy/v1 URL (see the URL in the second log line) even though the manifest has an apiVersion of policy/v1beta1. I noticed protokube uses the [DeferredDiscoveryRESTMapper](https://github.com/kubernetes/kops/blob/ea32e12ce780ab1a20e77c9eab909e0acce02b46/channels/pkg/channels/apply.go#L35) which has the concept of "group priorities", of which [v1 groups seem to always be highest priority](https://github.com/kubernetes/kops/blob/ea32e12ce780ab1a20e77c9eab909e0acce02b46/vendor/k8s.io/client-go/restmapper/discovery.go#L46-L49). It seems like protokube should always use the API version that is in the manifest rather than utilizing any discovery logic, otherwise kube-apiserver will return this `the API version in the data does not match the expected API version` error.

**Comment by justinsb** [comment]
Thanks for spotting this @rifelpet ..   @hakman pointed me to it.  I think this should be fixed by #13963 and so we are merging that.

**Comment by rifelpet** [comment]
I confirmed this fixed the issue. It was likely introduced by https://github.com/kubernetes/kops/pull/13753 which is only in the master branch, so no cherrypicks needed

/close
