### ISSUE TITLE
Running KOPS against LocalStack

### ISSUE THREAD

**Issue by MatthewStuart1994** [kubernetes/kops#14023]
/kind feature

Good day,

Please can I request some assistance on running Kops against LocalStack. 
I think this might be a great feature to have when testing against an AWS emulator. 

Could there maybe be some feature that allows a `cloudProvider` config to the list of options

In order to run awscli on LocalStack you can change the `endpoint-url` 

e.g: `aws --endpoint-url http://localhost:4566`

**Comment by olemarkus** [comment]
That would be a fairly big job right now. Most likely a feasible implementation would be based on the outcome of https://github.com/aws/aws-sdk/pull/230

If someone wants to implement this, I'm happy to review though
