### ISSUE TITLE
 NoCredentialProviders: no valid providers in chain

### ISSUE THREAD

**Issue by denis-singh** [kubernetes/kops#1402]
Is there anyway to build a cluster from a host using its IAM role rather than having explicit AWS credentials?

**Comment by justinsb** [comment]
Yes, that should work as long as the host you are building from has adequate permissions.  Can you post the error?  It sounds like the host doesn't have an IAM instance role at all, but maybe we aren't picking up the IAM role.

**Comment by denis-singh** [comment]
error reading cluster configuration "xxxxxxxxxx": error reading configuration file s3://xxxxx/config: error getting location for S3 bucket "xxxxx": NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors


The instance has an IAM role which has full S3 access

**Comment by denis-singh** [comment]
So this was related to my proxy settings. Had to export no_proxy=169.254.169.254

**Comment by justinsb** [comment]
Thanks for following up @denis-singh and happy that you solved it!  Hopefully this will come up in github search next time someone hits this!
