### ISSUE TITLE
could not find Image

### ISSUE THREAD

**Issue by alexeyvoren** [kubernetes/kops#14027]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
$ kops version
Version 1.18.2 (git-84495481e4)
```
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
k8s version: 1.11

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```kops update cluster```

**5. What happened after the commands executed?**
```error running task "LaunchConfiguration/xxxxx" (9m45s remaining to succeed): could not find Image for "kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-07-20"```

**6. What did you expect to happen?**
to find needed image

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**LTDR**
image `kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-07-20` is not available in the us-east-1 (aws) AMIs.

Image ID: ami-0f293df54ee95c693

**Comment by olemarkus** [comment]
/remove-kind bug
/kind support

AWS no longer supports searching for these images due to their age. You can manually search and replace with the ami id, which will still work. 

Note that this kops version is also no longer supported.

**Comment by hakman** [comment]
Also, keep in mind that as of kOps & Kubernetes 1.18 the default images used by kOps are the [official Ubuntu 20.04](https://github.com/kubernetes/kops/issues/14027#ubuntu-2004-focal) images and not the old `kope.io/*` ones.
https://github.com/kubernetes/kops/blob/master/docs/operations/images.md#images

**Comment by alexeyvoren** [comment]
@olemarkus @hakman thank you for your answers. It turned out, that **On March 31, 2022, EC2 announced that all public AMIs will have the deprecation time set to two years after their creation date**

BTW, at the same time we still see images that were created more than 2 years ago, like k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17 or k8s-1.11-debian-stretch-amd64-hvm-ebs-2019-09-26

**Comment by olemarkus** [comment]
You probably want to plan for some upgrading so you can use supported images.

Any more we can do in this issue, or can we close it?

**Comment by alexeyvoren** [comment]
@olemarkus thank you. closing the issue.

**Comment by rajk1000** [comment]
I have a similar issue. I am using kops version 1.16 (and also I tried with kopsversion 1.19 it still fails), to create a K8S cluster of v1.12. I get the following image not found : http://kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2021-02-05.

Can you please tell me which is the next version of kops that I can use without any image issue, that will successfully create a k8s cluster of version 1.12 for me? Thanks (Obviously, it may be that I have to upgrade our stack to use k8s 1.13 but that may cause other disruptions for us, hence am (ideally) wanting (atleast for now) on k8s 1.12.
Thanks in advance

**Comment by hakman** [comment]
@rajk1000 Best guess, use some Debian Stretch image that AWS still supports. It's hard to do more, as 1.12 has been obsolete for such a long time.

**Comment by rajk1000** [comment]
Thanks for swift reply. Much appreciated. . If we wanted to go with k8s1.13 , or a version not too far from v1.12, would a kops version still have images that would support that. If so, which kops version please? Thanks

**Comment by hakman** [comment]
Maybe try Ubuntu 18.04, should be ok and still find images for it:
https://cloud-images.ubuntu.com/locator/ec2/
Unfortunately, it's trial and error at the moment.

**Comment by rajk1000** [comment]
Ok thanks. if we find the AMI Id of a suitable image, can you please tell me how I instruct the kops create cluster command to use that particular AMI id? thanks

**Comment by hakman** [comment]
Something like:
```
kops get ig
kops edit ig 1
kops edit ig 2
kops edit ig ...
kops update cluster
kops update cluster --yes
kops rolling-update cluster
kops rolling-update cluster --yes
```

**Comment by rajk1000** [comment]
Thanks, but I'm sorry not completely understanding that part. In truth the kops cluster was setup before my time. It has been an area of code I haven't had to touch for a long while until now. (I am more familiar with EKS, and this kops setup, as you can see is using very old versions of both kops and also k8s). So , anyways, the error is that when we call 'kops create cluster', we get the missing Image error (Can't find Image http://kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2021-02-05).
StackOverflow articles, and even this reply seems to indicate that the images no longer exist because of the 2 year window, and to recommend searching for another AMI. So, once we find the AMI, where do we update any config files etc, so that the 'kops create cluster' command will then know it has to use this AMI (that we specified) rather than the default one (that doesn't exist). Thanks again.

**Comment by rajk1000** [comment]
I think what I'm not understanding , is if we can edit an 'ig' for a brand new kops cluster. In other words, our scripts call 'kops create cluster'. It fails on that, so no nodes are created. Hence I am not sure if we can edit the ig? Or can we? If so, i guess we do this, before we call 'kops create cluster'? Thanks

**Comment by hakman** [comment]
In your issue you said `kops update cluster`.
To fix `create cluster`, add `--image <AMI_ID>` you will have to test a little to find the right one.
