### ISSUE TITLE
Kops calling a lot of list requests (250k requests/hr) for state store s3 bucket

### ISSUE THREAD

**Issue by Sawaphob** [kubernetes/kops#14031]
Kops version: 1.21.4
Kubernetes version: 1.21.8
Cloud Provider: AWS

We are using S3 as a state store for our kops cluster. We found out that the cost of using S3 as a state store is around $1000 per month. The cost mainly come from `APS1-Requests-Tier1 ` which cost us around $950 a month

After turn on request metrics on that S3 bucket for a few hours, we found out that kops calling a lot of list request to the S3 bucket. It is calling around 250k request per hour.

Do kops provide the way to reduce the list request to state store S3 bucket?

**Comment by olemarkus** [comment]
That amount sounds abnormal.

First step would be to upgrade kops to latest version. There are some improvements both on kops and etcd manager side.

If the amount of requests remains high after that, we need more info in order to replicate the behavior.

**Comment by Sawaphob** [comment]
After investigate further, we found out that etcd-manager clean-up backup jobs doesn't work properly.

In etcd-manager leaders logs show that it already remove the backup as shown in pic below but once I check on S3 console, the directory and file still there.
After clean-up job completed, etcd-manager will redo the clean-up again since the backup directory and file still there so it cause the loop. That's the reason why we got a lot of list and delete requests.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/31118545/181220087-408e7b70-4132-4d3b-bd97-aff9f8d67017.png">

<img width="250" alt="image" src="https://user-images.githubusercontent.com/31118545/181226246-08082f3b-82ba-41d0-8e30-0e7705abdbac.png">


Is there a way we can check further?

Can we update the etcd-manager without updating kops versions since 1.22 will be a major breaking change for us?
Current etcd-manager version: k8s.gcr.io/etcdadm/etcd-manager:v3.0.20211117

**Comment by olemarkus** [comment]
Why is kops 1.22 a breaking change? I don't believe we introduced any. Note that kops 1.24 works with k8s 1.21.

**Comment by hakman** [comment]
I think there is a permission for List/DeleteVersions missing.

**Comment by Sawaphob** [comment]
We are missing `s3:DeleteObjectVersion` permission. After added, the clean up jobs work as expected. The list,delete requests dropped significantly.

Thank you everyone!
