### ISSUE TITLE
cilium-operator crashes due to eni-tags upgrading from 1.23.2 to 1.24.3

### ISSUE THREAD

**Issue by chrism417** [kubernetes/kops#14033]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.24.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.24.3

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Our tags are being added as an arg to cilium-operator:

`- --eni-tags=Environment=Staging,JiraProject=redacted,KubernetesCluster=k8s.redacted.redacted,Product=redacted`

**5. What happened after the commands executed?**

cilium-operator crashed with the following error causing kOps not to proceed with the upgrade:

`level=info msg="Started gops server" address="127.0.0.1:9891" subsys=cilium-operator
level=fatal msg="unable to parse eni-tags: 'Environment=Staging,JiraProject=redacted,KubernetesCluster=k8s.redacted.redacted,Product=redacted' is not formatted as key=value,key1=value1" subsys=option`

**6. What did you expect to happen?**

cilium-operator would accept the tags

**7. Please provide your cluster manifest. Execute

This will take awhile to redact everything, is this needed for this bug?

**9. Anything else do we need to know?**

The cilium-operator deployment is running v1.11.6

**Comment by chrism417** [comment]
Fix here: https://github.com/cilium/cilium/issues/20666

**Comment by olemarkus** [comment]
Cilium 1.11.8 has now been released, including the mentioned fix.
I'll bump this soon, but I want to include another fix in this first too that needs some more testing.

**Comment by olemarkus** [comment]
/close

Fixed by #14137
