### ISSUE TITLE
unable to do ssh to my master and node machine in kubernetes

### ISSUE THREAD

**Issue by dhinesh2287** [kubernetes/kops#14060]
Hi all
I have created the k8s setup using kops mechanism for me cluster got created iam having 1 master and 1 node server i couldn't able to ssh my master and node i have done the ssh-key gen steps also and give the read ,write permissions also ..can anyone help in this case
Thanks
<img width="960" alt="ssh-issue" src="https://user-images.githubusercontent.com/99251741/181738356-84466d86-dc30-42ca-8a6e-5d6f08661992.png">

**Comment by hakman** [comment]
Hi, the instance should be visible in AWS Console and also show which SSH key was used to create it. That should give you a hint about any mismatch.
