### ISSUE TITLE
Upgrade Clilium to v1.12

### ISSUE THREAD

**Issue by avdhoot** [kubernetes/kops#14097]
Cilium released version [1.12 ](https://isovalent.com/blog/post/cilium-release-112/).

**Comment by olemarkus** [comment]
How's this progressing? This should be added fairly soon now if it is to make it into 1.25.

**Comment by thylong** [comment]
It's worth mentioning that Cilium 1.12 includes Cilium Service Mesh feature, this will interest a lot of Cilium adopters

**Comment by olemarkus** [comment]
Service Mesh feature probably need a lot of modifications to the addon beyond a plain upgrade. Would really welcome any contribution towards sporting those.

**Comment by youwalther65** [comment]
I need Cilium 1.12.x for AWS IP prefix delegation in Cilium!

**Comment by olemarkus** [comment]
Happy to review a PR.
