### ISSUE TITLE
We probably need a minimumKopsVersion in the stable channel

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1409]
So that we don't recommend a k8s version that doesn't work with an older version of kops.

Not a problem yet, but we need to add it _before_ it becomes a problem.

**Comment by kris-nova** [comment]
Good call - I agree - could we get this into 1.5.0 beta?

**Comment by justinsb** [comment]
This was added in https://github.com/kubernetes/kops/pull/1625
