### ISSUE TITLE
kube-controller-manager and kube-scheduler crash after setting "logFormat: json" (need the same patch as in #13245)

### ISSUE THREAD

**Issue by aryabchenko** [kubernetes/kops#14100]
/kind bug

It's basically the same issue as in bug #13245.
It was fixed in https://github.com/kubernetes/kops/pull/13264 by @h3poteto by checking if logformat is set to json.
But the fix was provided for the api-server only, kube-controller-manager and kube-proxy and kube-scheduler were not fixed.
For some reason json logging was not enabled in my cluster for kube-proxy, so it's running. But kube-scheduler and kube-controller-manager stuck in CrashLoopBackOff state after upgrade to 1.22.12 using kops 1.22.6

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Client/Server Version 1.22.6

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client/Server Version 1.21.13

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Edit cluster
Add parameter
```
spec:
  kubeAPIServer:
    logFormat: json
```
kops update cluster
kops rolling-update cluster --instance-group <one of the masters>

**5. What happened after the commands executed?**
kube-controller-manager and [kube-proxy] and kube-scheduler crash with error:
```
Error: [non-default logging format doesn't honor flag: alsologtostderr, non-default logging format doesn't honor flag: log_file, non-default logging format doesn't honor flag: logtostderr]
```

**6. What did you expect to happen?**
Cluster work properly with all pods alive

**7. Please provide your cluster manifest. Execute
too much sensitive information, no need to provide for a clone of already fixed issue

**Comment by aryabchenko** [comment]
@h3poteto can you please take a look here?

**Comment by h3poteto** [comment]
OK, I will check.

**Comment by h3poteto** [comment]
I can't confirm this bug with the master branch, probably I need to use release-1.22.

**Comment by olemarkus** [comment]
I think it's getting more and more unlikely we'll do another 1.22

**Comment by aryabchenko** [comment]
Yes, it's bug for  <1.22, cause starting from 1.23 you use not klog, but some go-runner, so there is no such issue. But this if check https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/kube_apiserver.go#L661 is implemented for kube_apiserver only.

**Comment by aryabchenko** [comment]
Yes, we have `logFormat: json` for `kubelet`, `kubeAPIServer`, `kubeControllerManager` and `kubeScheduler`.
