### ISSUE TITLE
Channels server-side apply leads to failing addon upgrades

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kops#14117]
Basically #13712 again, but with the applier library.

Now that we have our own client, we can inspect existing objects and check if any fields are owned by "kubectl-client-side-apply" and then do something with those. First attempt was to try to just patch the managedField itself, but turns out that is not allowed :stuck_out_tongue: 

So I think we maybe need to try to claim ownership over any field owned by kubectl by explicitly setting those values to `nil` in our patch if it has not been set. However, I am struggling a little bit with navigating the `managedField` entry.

/kind bug
/kind office-hours

**Comment by justinsb** [comment]
We have some code to fix this; I'm going to try to get that code OSSed here (or into #14030 if/when that merges)

**Comment by olemarkus** [comment]
It would be nice if there is something for navigating through an unstructured using a `fieldset.Path`. But if you have something more sophisticated, that would be most welcomed
