### ISSUE TITLE
Request that KOPS be able to find AMI with "private images" label

### ISSUE THREAD

**Issue by agomez-infoblox** [kubernetes/kops#14133]
I am working with a custom AMI that i am sharing across several accounts, and when I try to provide this under the  image: parameter, it fails

example:
AMI is in account 77777777 and shared with account 88888888

I can launch the shared AMI in account 88888888 manually with no problem

But when I tried to point KOPS to use I see this error

```aws_cloud.go:1691] Calling DescribeImages to resolve name "myami"
1 request_logger.go:45] AWS request: ec2/DescribeImages
Error: node.spec.image: Invalid value: "myami": image specified is invalid: "myami"
make: *** [deploy] Error 1```

kops version
Client version: 1.24.1

Base AMI is AL2

**Comment by hakman** [comment]
Thanks for reporting this @agomez-infoblox.
Would you mind saying what "myami" looks like, it may help update the validation function?

**Comment by agomez-infoblox** [comment]
When you say "looks like" I am hoping this answers your question. So i am authenticated to account 88888888

```{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2022-08-09T14:19:40.000Z",
            "ImageId": "ami-someid",
            "ImageLocation": "77777777/myami",
            "ImageType": "machine",
            "Public": false,
            "OwnerId": "77777777",
            "PlatformDetails": "Linux/UNIX",
            "UsageOperation": "RunInstances",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/xvda",
                    "Ebs": {
                        "DeleteOnTermination": true,
                        "SnapshotId": "snap-myami",
                        "VolumeSize": 64,
                        "VolumeType": "standard",
                        "Encrypted": true
                    }
                }
            ],
            "EnaSupport": true,
            "Hypervisor": "xen",
            "Name": "myami",
            "RootDeviceName": "/dev/xvda",
            "RootDeviceType": "ebs",
            "SriovNetSupport": "simple",
            "VirtualizationType": "hvm"
        }
    ]
}
```
So because the Image source/location is a different account. It seems that KOPS is using this operation (based on the error output)

```
aws ec2 describe-images --region us-east-1 --owner self \
--filters "Name=name,Values=*myami*"
```

as when you specify "self" or "public" it does not look at images tagged as "private"  Btw it shows private in the AWS dashboard. 

Hope this helps

**Comment by agomez-infoblox** [comment]
Adding for context
I have specified the AMI as this on the manifest.yaml file
7777777 is the account where the AMI is built and shared with 88888888

this manifest file is they tried against 88888888

```
image: 77777777/myami
```

**Comment by agomez-infoblox** [comment]
@hakman any updates?

**Comment by hakman** [comment]
Could you try using version [1.25.0-beta.1](https://github.com/kubernetes/kops/releases/tag/v1.25.0-beta.1)?
This should give a better idea about the issue.

**Comment by agomez-infoblox** [comment]
@hakman can you indicate the proper command to install from that link?  I don't see a downloadable binary and substitution of the command below does not download the proper context.  (after the download, I am making executable)

```curl -Lo kops https://github.com/kubernetes/kops/releases/download/v1.25.0-beta.1/kops-darwin-amd64```

**Comment by hakman** [comment]
Maybe check that the binary is not corrupted:
```sh
% shasum -a 256 kops 
1f3ba0ed2e611ad6128696d03bdef1b1e7f05b4a0572a646db3f4f7eac162997  kops
% curl -L https://github.com/kubernetes/kops/releases/download/v1.25.0-beta.1/kops-darwin-amd64.sha256
1f3ba0ed2e611ad6128696d03bdef1b1e7f05b4a0572a646db3f4f7eac162997
```
or that you are downloading it for the correct OS and ARCH.

**Comment by agomez-infoblox** [comment]
@hakman it was operator error.  I got it to work and I am still not able to build the cluster. The instances terminate as soon as they try to start. I have used ways to name the AMI
With the AMI name I get this error in the logs
```Invalid value: "sdp-base-amazonlinux-2-202208.09.108": specified image "sdp-base-amazonlinux-2-202208.09.108" is invalid: could not find Image for "sdp-base-amazonlinux-2-202208.09.108"```

When specify AMI-ID, I see in the logs that it identifies the AMI, but again the cluster has the same behavior of the instances terminate as soon as they try to launch.  All I see is an internal error in the AWS side

**Comment by hakman** [comment]
Using the AMI-ID, could you check the generated LaunchTemplate and see if there is any obvious problem with the image? Can you try to edit it to correct it?
There should be an error in the ASG that tells the reason why the instance failed to start also.

**Comment by agomez-infoblox** [comment]
I have validated that the AMI-ID in the launch config and under the AMI store is the the same.
<img width="481" alt="Screen Shot 2022-09-15 at 12 33 09 PM" src="https://user-images.githubusercontent.com/87830311/190459382-eb0e1698-1328-4911-a1d9-63a0fcb7a9b6.png">
<img width="304" alt="Screen Shot 2022-09-15 at 12 32 31 PM" src="https://user-images.githubusercontent.com/87830311/190459416-21a3d3e4-1f94-491a-ae9e-0a7b0a387241.png">

This is the error coming from the ASG group that spins up the new instances
```Launching a new EC2 instance: i-0865016bb4eb9fd1a. Status Reason: Instance became unhealthy while waiting for instance to be in InService state. Termination Reason: Client.InternalError: Client error on launch```

**Comment by hakman** [comment]
Is the AMI encrypted?

**Comment by agomez-infoblox** [comment]
@hakman  Yes the AMI is encrypted
It is also shared from another account
this account and my user has permissions to decrypt and re-encrypt
I am able to pass this same AMI-ID to terraform and using the same Role (permissions), it is able to launch successfully. 

so it seems kops just can't find images that are shared (private images)
It seems to only find images owned by the same account and public

**Comment by hakman** [comment]
Do you use an ASG with Terraform or just a plain instance?
Maybe you need something like this:
https://docs.aws.amazon.com/autoscaling/ec2/userguide/key-policy-requirements-EBS-encryption.html

**Comment by agomez-infoblox** [comment]
@hakman I do have a ASG as kops creates it. And to the second questions the answe is yes. I am launching just a single instance. 

But I see you are saying that maybe the ASG service doesn’t have the permission to decrypt be volume. 

I am actually more concerned with the fact that kops can’t find the image when I supply the name as that is the real use case we have. We want to use the same name as we deploy in multiple regions and they all will have a different ami-id 

Is there a reason kops won’t find it by name?

**Comment by hakman** [comment]
> I am actually more concerned with the fact that kops can’t find the image when I supply the name as that is the real use case we have. We want to use the same name as we deploy in multiple regions and they all will have a different ami-id
>
> Is there a reason kops won’t find it by name?

Based on the error pasted above, the name of the image in the IG config is "sdp-base-amazonlinux-2-202208.09.108" and  kOps assumes owner is `self`, instead of "77777777/sdp-base-amazonlinux-2-202208.09.108".

**Comment by agomez-infoblox** [comment]
@hakman I went ahead and to avoid the above isssue, I passed the account number as in the documentation it says it allows it.

I am replacing the account number but I am setting up the image as 
```
image: 777777777/sdp-base-amazonlinux-2-202208.09.108
```
As you can see it finds it, it resolves it to the correct AMI-ID yet it seems to not be able to use or something.
```
I0916 11:16:51.618041   18003 aws_cloud.go:1979] Calling DescribeImages to resolve name "7777777777/sdp-base-amazonlinux-2-202208.09.108"
I0916 11:16:51.618339   18003 request_logger.go:45] AWS request: ec2/DescribeImages
I0916 11:16:51.874522   18003 aws_cloud.go:2043] Resolved image "ami-0099263fc26be61fa"
```

On the AWS side the ASG activity shows this 
```Termination Reason: Client.InternalError: Client error on launch```

**Comment by hakman** [comment]
@agomez-infoblox I guess the main concern was addressed and the AMI-ID is resolved.

kOps creates the ASGs correctly, but they need permission to decrypt the image (for the account that was used to create the ASGs). These should be similar to the article I linked above. kOps cannot give access to the managed key. You have to do that yourself separately or switch to using an unencrypted AMI.

**Comment by hakman** [comment]
Thanks for the update @agomez-infoblox.
If you don't mind, could you paste the final role/permissions, in case anyone else needs this? Thanks!

**Comment by agomez-infoblox** [comment]
Command used was 
The following is an example [create-grant](https://docs.aws.amazon.com/cli/latest/reference/kms/create-grant.html) CLI command that gives the service-linked role named AWSServiceRoleForAutoScaling in account 111122223333 permissions to use the customer managed key in account 444455556666.
```
aws kms create-grant \
  --region us-west-2 \
  --key-id arn:aws:kms:us-west-2:444455556666:key/1a2b3c4d-5e6f-1a2b-3c4d-5e6f1a2b3c4d \
  --grantee-principal arn:aws:iam::111122223333:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling \
  --operations "Encrypt" "Decrypt" "ReEncryptFrom" "ReEncryptTo" "GenerateDataKey" "GenerateDataKeyWithoutPlaintext" "DescribeKey" "CreateGrant"
  ```
