### ISSUE TITLE
Dns controller is failing to set proper ips

### ISSUE THREAD

**Issue by pritamfocal** [kubernetes/kops#14145]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

I have used version 1.23, 1.24.1, 1.25.aplha1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.22.5

**3. What cloud provider are you using?**
Digital Ocean

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create cluster --cloud=digitalocean --name=${ROUTE53_KOPS_DNS} --image=debian-9-x64 --networking=calico --zones=ams3 --ssh-public-key=/Users/pbss/test@sss.pub --node-size=c-4 --node-count=1
kops update cluster --name ${ROUTE53_KOPS_DNS}  --yes --admin
kops validate cluster --wait 10m

**5. What happened after the commands executed?**
The droplets got created and state got store in the space. DNS entries added but the IP address is  203.0.123.223

**6. What did you expect to happen?**

I expect the the kops validation should be successfull

**Comment by hakman** [comment]
@pritamfocal Could you check the logs of dns-controller for any clues?
/cc @srikiz

**Comment by pritamfocal** [comment]
How can I check the logs ?....are there any commands  ?...I have getting this logs

The dns-controller Kubernetes deployment has not updated the Kubernetes cluster’s API DNS entry to the correct IP address. The API DNS IP address is the placeholder address that kops creates: 203.0.113.123. Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate. The protokube container and dns-controller deployment logs may contain more diagnostic information. Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to start.

**Comment by hakman** [comment]
SSH to a master node and should be able to use `kubectl` there.

**Comment by pritamfocal** [comment]
Hi, I did ssh to master node but kubectl was not found there so I tried to install kubectl and then tried to check get deployment or get pods but getting some errors like connection to server refused localhost:8080

**Comment by hakman** [comment]
Probably you need to go through https://kops.sigs.k8s.io/operations/troubleshoot. Seems thate Nodeup did not manage to finish the bootstrap process.

**Comment by pritamfocal** [comment]
Hi hakman...No its not helpful for me :(

**Comment by olemarkus** [comment]
You need to run `kubectl` as non-root in order to use a default config that will connect successfully. Using `kubectl` as root will not work.

**Comment by srikiz** [comment]
Can you also check if the control-plane droplets are associated to the volumes? You can check that from the DigitalOcean's user interface.

**Comment by pcgeek86** [comment]
Same problem here. I provisioned a new cluster on AWS, with an AWS registered and hosted DNS zone, and the A records never get updated properly, after creation. Even after 20 minutes, they still just resolve to `203.0.113.123`. 

I can't SSH to the master node, because there is no public key associated with the EC2 virtual machine.

**Comment by olemarkus** [comment]
@pcgeek86 this bug is DO-specific. I suggest you file a new bug with the exact commands you are using.
