### ISSUE TITLE
kops validate cluster fails with ebs-csi controller pending

### ISSUE THREAD

**Issue by arnabaws15** [kubernetes/kops#14143]
My first time using kops on AWS
Version: 1.24.0

### kops validate cluster returns:
VALIDATION ERRORS
KIND    NAME                                            MESSAGE
Pod     kube-system/ebs-csi-controller-7446576c4b-svhw9 system-cluster-critical pod "ebs-csi-controller-7446576c4b-svhw9" is pending

### Running kubectl get pods -n kube-system:
ebs-csi-controller-7446576c4b-ghs7q           5/5     Running   0               6h17m
ebs-csi-controller-7446576c4b-svhw9           0/5     Pending   0               9m25s

I tried deleting the pending pod, but the new pod created has the same issue.

I have searched this issue all over but nothing points to a solution or something that I have missed.

Any help to resolve this will be appreciated.

**Comment by olemarkus** [comment]
Please follow the issue template when filing bugs. My guess is that you have specified only 1 worker node, and since two controllers cannot be scheduled on the same node, it's stuck pending. Try adding another node.

/kind support

**Comment by arnabaws15** [comment]
> Please follow the issue template when filing bugs. My guess is that you have specified only 1 worker node, and since two controllers cannot be scheduled on the same node, it's stuck pending. Try adding another node.
> 
> /kind support

Thank you so much olemarkus. That was it! Interestingly the configuration for auto-scaling-groups (ASG) for nodes defaults to 1. May be we can update the configuration for default ASG size for nodes to 2.
