### ISSUE TITLE
Error: unknown flag: --ipv6

### ISSUE THREAD

**Issue by IgalSc** [kubernetes/kops#14146]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
kops version
Version 1.23.2 (git-4125bbbe975ca104c609ceaa625a9a5ff3ac19f4)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2"
kubernetesVersion: 1.23.9

**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
export KOPS_CLUSTER_NAME=clustername.k8s.local
export KOPS_STATE_STORE=s3://clustername-kops-state-store
export MASTER_SIZE="t3a.medium"
export NODE_SIZE="c6a.large"
kops create cluster --vpc vpcID \
                    --node-count 2 \
                    --zones us-east-1a,us-east-1b \
                    --master-zones us-east-1a,us-east-1b \
                    --node-size $NODE_SIZE  \
                    --master-count 3 \
                    --master-size $MASTER_SIZE  \
                    --networking calico \
                    --ipv6
**5. What happened after the commands executed?**
Error: unknown flag: --ipv6

**6. What did you expect to happen?**
Deploy a cluster with ipv6 support
Based on, https://kops.sigs.k8s.io/networking/ipv6/  kops 1.23 should support this flag 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
I don't believe this is relevant

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

N/A

**Comment by hakman** [comment]
For kOps 1.23, the IPv6 feature is feature-flagged.
Please use kOps 1.24.1 and `--ipv6` should work as expected.

**Comment by IgalSc** [comment]
@hakman thank you so much!
