### ISSUE TITLE
nodeAffinity for coredns-autoscaler 

### ISSUE THREAD

**Issue by aramhakobyan** [kubernetes/kops#14165]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

It's possible to change nodeAfinity/tolarations for CoreDNS to schedule deployment on decide node group, 
but for coredns-autoscaler there is no option in [API to define nodeAfinity/tolarations see code  ](https://github.com/kubernetes/kops/blob/v1.24.1/pkg/apis/kops/cluster.go#L525)  or [see docs](https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#KubeDNSConfig)
 
**2. Feel free to provide a design supporting your feature request.**

**Comment by MoShitrit** [comment]
I can take a look soon.
/assign

**Comment by MoShitrit** [comment]
@aramhakobyan thanks for reporting this!
Issue has been fixed via #14503 and is also being cherry-picked into the 1.24 (via #14505) and 1.25 (via #14506) release branches to be included in the next patch releases of these minor versions.
