### ISSUE TITLE
Tune volume attach detach settings in k-c-m

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1417]
In kubernetes 1.4.8 and 1.5.2 there will be a setting that we will need to tune.  

We will need to add to the model versions for 1.4.8+ and 1.5.2+.  https://github.com/kubernetes/kops/tree/master/upup/models/config/components/kube-controller-manager/_aws

The current flag name is `reconcile-sync-loop-period` and a period of 1m is probably what we want to roll with.  This flag is important enough that I would recommend pulling it into the api.  I will update if the flag name changes.

**Comment by chrislovecnm** [comment]
The flag name has changed

**Comment by kris-nova** [comment]
Thank you! Will code first thing tomorrow

**Comment by chrislovecnm** [comment]
attach-detach-reconcile-sync-period Is the droid you are looking for, and set to one minute
