### ISSUE TITLE
ClusterAutoscaler addon: Add support to cordonNodeBeforeTerminating flag

### ISSUE THREAD

**Issue by dcfranca** [kubernetes/kops#14171]
`Cluster Autoscaler` since at least version 1.19.3 has added support to a flag to indicate whether it should cordon a node before scaling down or not.

This can be seen on the list of parameters [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca)

> cordon-node-before-terminating | Should CA cordon nodes before terminating during downscale process | false

This flag is not supported by kops, is that possible for it to be added?

 I guess it needed to be added at some parts of the code
 
 https://github.com/kubernetes/kops/blob/master/k8s/crds/kops.k8s.io_clusters.yaml#L716
 
 https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L1000 and `v1apha2/3` as well?
 
https://github.com/kubernetes/kops/blob/master/pkg/model/components/clusterautoscaler.go#L89

And here add a conditional to include the flag in case it was set: https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template#L332

In case it is planned to add it I can submit a PR, just probably need some guidance on the codebase and tests

**Comment by olemarkus** [comment]
We tend to accept features such as these. Happy to review a PR.

All the API versions you mention above must be updated.
