### ISSUE TITLE
api server elb not created in private topo

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1418]
For some reason, I am not getting an ELB for the API servers in private topo mode.  Thoughts?  This is off of the master branch.

**Comment by chrislovecnm** [comment]
I need to validate this, as it may be a red herring.

**Comment by kris-nova** [comment]
Hrmm interesting - let me know

**Comment by justinsb** [comment]
I suspect this was fixed in #1421.  `kops create cluster` with `--target terraform` produced the same result - no ELB

**Comment by chrislovecnm** [comment]
Will test

**Comment by kris-nova** [comment]
@chrislovecnm wondering how you managed to pull this off?

There is some new API work around access policies for kops, and if for some reason the new access policy isn't defined, no ELB will be created

**Comment by chrislovecnm** [comment]
Pretty sure this is fixed ;) Aws was also having a bad hair day, and I was runnning off of master.

**Comment by kris-nova** [comment]
Can we close?

**Comment by chrislovecnm** [comment]
Yup
