### ISSUE TITLE
Instance groups NeedsUpdate after running rolling-update

### ISSUE THREAD

**Issue by yuzhouliu9** [kubernetes/kops#14195]
/kind bug

**1. `kops` version.**
v1.24.0

**2. Kubernetes version.**
v1.21.14

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
After running `kops rolling-update`, my bastion and the first master that was rolled are still reporting "NeedsUpdate".

This has happened 3 times now, the bastion and the first master to roll are always marked as "NeedsUpdate" immediately after rollout. If I do the rolling-update command again, the master becomes Ready, but bastion stays at "NeedsUpdate".

```
NAME                STATUS      NEEDUPDATE  READY  MIN  TARGET  MAX  NODES
bastion             NeedsUpdate	1           0      1    1       1    0
master-us-east-1b   NeedsUpdate	1           0      1    1       1    1
master-us-east-1c   Ready       0           1      1    1       1    1
master-us-east-1f   Ready       0           1      1    1       1    1
```

I noticed the master-us-east-1b node had the annotation `kops.k8s.io/needs-update` which is used by kops as a [criteria](https://kops.sigs.k8s.io/operations/rolling-update/#instance-selection) for updating.

Why did kops leave this annotation even after rolling the node the first time?
Is there a way to find out why the bastion is marked as NeedsUpdate?

**5. What happened after the commands executed?**
Instance groups still marked as `NeedsUpdate`.

**6. What did you expect to happen?**
All Instance groups should report `Ready` since rolling-update just ran.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

[kops_cluster_spec.txt](https://github.com/kubernetes/kops/files/9434319/kops_cluster_spec.txt)

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
I don't have this.

**9. Anything else do we need to know?**

**Comment by olemarkus** [comment]
There only way bastion can need update is if the lASG aunch template version is higher than the launch template used to launch the bastion instance.

`kops.k8s.io/needs-update` are applied when updating certain addons. If you roll before addons are applied, you may need to roll one extra time.

**Comment by seh** [comment]
This [came up in the "kops-users" channel](https://kubernetes.slack.com/archives/C3QUFP0QM/p1663882128868069) of the "Kubernetes" Slack team, specifically concerning the bastion machines, but not the control plane machines.
