### ISSUE TITLE
Provide default StorageClass?

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1419]
I realized that some of my pods were using stateless storage because a PV couldn't be created to satisfy a PVC.  The root cause was that there were no storage classes, so it just skipped binding them. 

Maybe Kops should provide a default storage class on each provider using the most general-purpose provider options?

**Comment by aledbf** [comment]
@blakebarnett this https://github.com/kubernetes/kops/pull/1304 ?

**Comment by blakebarnett** [comment]
Yes! I'm not sure why I didn't show up in my search, thanks

**Comment by justinsb** [comment]
Well it hasn't shipped ... yet... but not long now ;-)
