### ISSUE TITLE
Q before fix: Why are subnet forced to be the same as zones?

### ISSUE THREAD

**Issue by pnegahdar** [kubernetes/kops#1420]
https://github.com/kubernetes/kops/blob/ded1b164effaff916c6e093b0b01dcc31639c89b/pkg/apis/kops/v1alpha1/conversion.go#L128

How do you go about making two subnets in the same zone?

**Comment by justinsb** [comment]
This is a limitation of the v1alpha1 API, but is not a limitation of v1alpha2.

The v1alpha2 API is about to ship in 1.5.0-alpha.  Soon!

**Comment by pnegahdar** [comment]
Ah cool. Thanks! will reopen/revisit later then.
