### ISSUE TITLE
cert-manager 1.8.2 is needed to allow working with ZeroSSL issuer

### ISSUE THREAD

**Issue by minkimipt** [kubernetes/kops#14211]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

We are using cert-manager deployed by kops 1.24. Cert-manager that is bundled with this kops version is 1.8.0. This release has a bug when it comes to working with ZeroSSL ACME provider. According to [cert-manager release notes](https://cert-manager.io/docs/release-notes/release-notes-1.8#v182) 1.8.2 version of cert-manager fixes that bug.

**2. Feel free to provide a design supporting your feature request.**

What I'm requesting here is either to provide a way to set an image for cert-manager addon. Or at least to bump cert-manager to 1.8.2.

**Comment by hakman** [comment]
Fixed in https://github.com/kubernetes/kops/pull/14212. Should be available in the next kOps 1.24.x release.
