### ISSUE TITLE
Target downscaling nodes

### ISSUE THREAD

**Issue by geldmon** [kubernetes/kops#14277]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

When we are manually downscaling an instance group (reducing the min/max number) on a unused capacity scenario, we often see nodes being removed from the cluster with actual load and processes, causing undesired downtime. My question is if I can target which nodes to remove by using kops or natively with k8s annotations? I couldn't find anything related in the kops docs but If this is already possible, please point me to the right direction.

**2. Feel free to provide a design supporting your feature request.**

I'd like to specify which nodes should be scaled down - ideally as part of the downscaling process with kops.

**Comment by olemarkus** [comment]
I would use the Cluster Autoscaler addon to do this automatically. It will do the right thing.

How it does it is a bit tricky to do manually. But essentially it detaches the instance it wants to remove from the ASG, then reduces ASG size before the replacement instance is scheduled. Then it drains and terminates.
