### ISSUE TITLE
Don't allow configuration of kubeAPIServer.targetRamMb in the cluster spec on Kubernetes 1.24+

### ISSUE THREAD

**Issue by danports** [kubernetes/kops#14276]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
kOps will allow you to configure `kubeAPIServer.targetRamMb` in your cluster spec on Kubernetes 1.24+, but then when you try to deploy your cluster, you get this in your api-server logs:
```
Error: unknown flag: --target-ram-mb
```
This is due to the removal of this flag in 1.24+: https://github.com/kubernetes/kubernetes/pull/108457

**2. Feel free to provide a design supporting your feature request.**

Probably best to reject this cluster configuration based on the Kubernetes version and add a note to the docs.

**Comment by olemarkus** [comment]
Thanks for catching this. Would you be able to do a PR?

**Comment by danports** [comment]
Perhaps eventually, but probably not in the near future.
