### ISSUE TITLE
K8s KOPS 1.17 Debian based AMI not found in account 383156758163

### ISSUE THREAD

**Issue by sandeep-jaiswal** [kubernetes/kops#14275]
/kind feature

Help Wanted

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

We have been using  this AMI  **`k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17`**  from account number **`383156758163`** as the base AMI while building images for our Kops 1.17 cluster. Since 22nd August, we've started getting 
`No AMI was found matching filters` errors. 

We wanted to know if this AMI has been deleted and whether there is any other AMI we can use. 

Thanks.

**2. Feel free to provide a design supporting your feature request.**

Query regarding Missing AMI from account `383156758163`

**Comment by olemarkus** [comment]
Is this a duplicate of https://github.com/kubernetes/kops/issues/14027 ?

**Comment by sandeep-jaiswal** [comment]
yes it is. Thanks @olemarkus 

I'll close this issue
