### ISSUE TITLE
Unowned NAT gateways may be deleted

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1428]
Split out from https://github.com/kubernetes/kops/issues/1376#issuecomment-271551426

```
also i got real issue when deleting the cluster using the 1.5.0-alpha2.
This version delete all my NAT instances, at least i can confirm old version was not deleting any such things.

autoscaling-group:master-us-west-2c.masters.kubetnets.us-west-2.test.mycomp.com	ok
nat-gateway:nat-04f6e95d3e75265d8	ok
nat-gateway:nat-06b6add1aaf5a738d	ok
nat-gateway:nat-0d1cc880def78c447	ok
nat-gateway:nat-06de87090d3ec73d3	ok
nat-gateway:nat-0bd70454040cca579	ok
nat-gateway:nat-0591234fb69d0fb06	ok
nat-gateway:nat-09848f1451db8f1c0	ok
0110 16:25:14.157268 82226 delete_cluster.go:1872] Deleting IAM role policy "nodes.kubetnets.us-west-2.test.mycomp.com" "nodes.kubetnets.us-west-2.test.mycomp.com"
I0110 16:25:14.157413 82226 request_logger.go:45] AWS request: iam/DeleteRolePolicy
instance:i-094432b26ac96b6ce	ok
nat-gateway:nat-0decf602a5f364086	ok
instance:i-06bcf57a907bdf21c	ok

even through I was using my own VPC, why new version is deleting the nats gateway?
```

**Comment by tsupertramp** [comment]
Same happening for me - It deletes nat gateways even in a different vpc then the one in cluster spec configured.

**Comment by paweloczadly** [comment]
I had the same result. All EIPs have been deleted as well.

**Comment by justinsb** [comment]
@tsupertramp @paweloczadly sorry about the problems as well!  Is this with `kops version`  == `Version 1.5.0-alpha2` ?

The logic is that if we are deleting the route table, we delete any nat gateways in that route table.  Is your route table or NAT gateway somehow shared?

I am not yet able to reproduce - here is what I did:

* I set up two private clusters both in us-west-2a e.g. (`kops create cluster  --topology private --bastion --networking weave --zones us-west-2a ubuntu.example.com --channel alpha --image ami-b2d463d2`)
* They have separate nat gateways (and routing tables)
* When I go to delete the clusters (without --yes), it proposes deleting just the correct routing-table and nat-gateway in each case

Can anyone help me to reproduce the issue / tell me what I am doing wrong?

**Comment by paweloczadly** [comment]
In my case the version was the same as in the alpha channel: v1.5.1. 
https://github.com/kubernetes/kops/blob/master/channels/alpha#L6

**Comment by justinsb** [comment]
That is your kubernetes version @paweloczadly .  If you type `kops version` you can see the version of kops you are running.

**Comment by paweloczadly** [comment]
Ah sorry, kops version is 1.5.0-alpha2.

**Comment by tsupertramp** [comment]
My kops version: Version 1.5.0-alpha2
"kops create cluster  --zones eu-west-1a --name=infra.k8s.test.test --admin-access someip/32 --master-zones eu-west-1a --vpc=vpc-someid --network-cidr=10.0.0.0/16 --node-count 1"- This was my command to create the cluster. The VPC id of the deleted nat gateways was another.

**Comment by tsupertramp** [comment]
Found the bug @justinsb - Bug is triggered if no nat gateway is found attached to any routing table. We do not check the input which is used to filter the natgateways (https://github.com/kubernetes/kops/blob/master/upup/pkg/kutil/delete_cluster.go#L1476)

I tested with and it fixed the output.
```
 if len(request.NatGatewayIds) == 0 {
  return nil, fmt.Errorf("no natgatewayids found")
} else {
...
```

Greetings Thomas

**Comment by justinsb** [comment]
GAH!  Thank you @tsupertramp.  That sounds very likely.

I will apply the fix and credit you with finding it.  If you want to send a PR let me know and I will hold off!

**Comment by virusdave** [comment]
This is deadly and actually caused me a production outage to an unrelated unowned service in a different VPC :(.  Risk of alpha, i know.  Any idea when a new prerelease version will be cut? @justinsb

**Comment by hridyeshpant** [comment]
yeah same here but luckily i ran on test environment but even through all our test env. services went out of service because for NAT deletion. 
It raise some question about the test cases which team are running before merging the code. luckily it just delete the NATS not other important infrastructure (VPC,routetable,etc).
