### ISSUE TITLE
Terraform Support for Version >=1.3 

### ISSUE THREAD

**Issue by ecda909** [kubernetes/kops#14334]
/kind feature

1. I would like to know if Terraform versions 1.3 or higher are supported using —terraform. If it’s not supported. Then I would like to add this as a feature request.

**Comment by hakman** [comment]
@ecda909 We are running regularly tests that validate kOps Terraform output against newer versions of Terraform:
https://testgrid.k8s.io/kops-presubmits#verify-terraform

I updated the test this morning to run against Terraform 1.3.0 in #14335 and I don't see any error. I suggest you give it a try and, if you find specific issues, please report them.

**Comment by ecda909** [comment]
Okay, I will. Thank you very much!

**Comment by ecda909** [comment]
Okay, thank you very much!
