### ISSUE TITLE
Bump Default Calico Version for Kubernetes 1.23 to 3.22.4

### ISSUE THREAD

**Issue by xgt001** [kubernetes/kops#14363]
/kind bug

KOPS ships version 3.21.4 of Calico CNI by default in kops 1.23.4 for Kubernetes. Calico doesn't support ipset protocol 7 introduced in Kubernetes 1.23 until version 3.22.4. This causes the master's to be never validated if you use Calico CNI from KOPS and the downgrade path before you realise you need to update the `version` on Calico is quite harrowing :( 

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.23.4 (git-824158f51fcf68a7fb2af36cd765034d5023f425)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.23.12

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Tried upgrading from Kubernetes 1.22 to 1.23 with the following commands:

```
kops replace -f cluster.yaml --state $KOPS_STATE_STORE
kops update cluster $K8S_CLUSTER --target terraform --out 1.23-terraform-config/ --state $KOPS_STATE_STORE
cd 1.23-terraform-config/ ; terraform init; terraform plan; terraform apply
kops rolling-update --state $KOPS_STATE_STORE cluster --instance-group node-group --yes
```

Please see: 
https://github.com/projectcalico/calico/issues/5011
https://github.com/projectcalico/calico/issues/5717

Workaround:
Update your cluster.yaml with an updated version of Calico

```
  networking:
    calico:
      version: v3.22.4
```

**Comment by olemarkus** [comment]
Please see https://kops.sigs.k8s.io/welcome/releases/
We do not support kOps 1.23 anymore.
