### ISSUE TITLE
Default to NLB instead of CLB for AWS clusters

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#14376]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

AWS is retiring EC2 Classic support and one of the listed components is Classic Load Balancer (CLB).
https://aws.amazon.com/blogs/aws/ec2-classic-is-retiring-heres-how-to-prepare/

With this in mind, we may want to default to Network Load Balancer (NLB) soon instead of CLB.
Existing clusters with CLB should not be automatically switched to NLB (yet).
We may also want to:
* automate removal of CLB, when load balancer type is manually changed
* consider not allowing the creation of new clusters with CLB

**2. Feel free to provide a design supporting your feature request.**

n/a

@olemarkus @rifelpet @justinsb @zetaab What do you think?

**Comment by olemarkus** [comment]
It's a bit misleading. It's Classic Load Balancer's in EC2 Classic networks that must be migrated. One of the options is to migrate it to Classic Load Balancer in a VPC: https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/migrate-classic-load-balancer.html#migrate-step-by-step-ec2-classic

That being said, a discussion on the defaults is welcomed. Perhaps also if LB should be the default over DNS.

**Comment by hakman** [comment]
I agree that CLB in VPC is an option, though the AWS UI is pretty much hiding CLB.

<img width="1009" alt="CLB" src="https://user-images.githubusercontent.com/2759402/193752845-33326daa-b8fc-4e2c-a571-4f50128e1213.png">

**Comment by rifelpet** [comment]
I'm onboard with switching the default to NLB 👍🏻

**Comment by olemarkus** [comment]
Let's do it!
