### ISSUE TITLE
Export CreateClusterOptions

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1442]
Right now the `CreateClusterOptions` struct is defined in a main package..

```
package main

import (...)

type CreateClusterOptions struct {
...
}

```

It would be meaningful for users calling the kops library directly if they could reference the struct as part of another package and call `RunCreateCluster` directly from another package..

Suggested package name: `package cmdOptions`

**Comment by kris-nova** [comment]
This is design and a feature for later

**Comment by justinsb** [comment]
Ugh... good point.  It's not _entirely_ by design, more "I didn't think it through".

**Comment by kris-nova** [comment]
So I think we should pull the options out into their own package of sorts.. so we can pass them into the cobra run commands.. and maybe even one day version them.. the options are in themselves an API 😄
