### ISSUE TITLE
Allow aws-ebs-csi-controller to be configured to run as non-root

### ISSUE THREAD

**Issue by djablonski-moia** [kubernetes/kops#14441]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

In order to minimize workloads running as `root`, it would be nice to allow a configuration setting for the `AWSEBSCSIDriver` to enable running as non-root user, or alternatively, run as non-root by default.

**2. Feel free to provide a design supporting your feature request.**

The [Helm chart provided by upstream is already setting a non-root `securityContext` by default](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L208), so the config struct `AWSEBSCSIDriver` could be enhanced by an block to configure this, or the default could be changed to always use the settings also used in the Helm chart.

**Comment by olemarkus** [comment]
Isn't this already the case?
https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template#L458

**Comment by djablonski-moia** [comment]
🤦 You're right, but yet only in 1.25, and we're still using 1.24, that's why I missed it. Sorry, I will close this FR
