### ISSUE TITLE
Add support for IBM Cloud

### ISSUE THREAD

**Issue by rgschmitz1** [kubernetes/kops#14469]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Any chance kops will add support for IBM Cloud?  My company is testing out IBM Cloud for running bioinformatics workflows.  Thanks!

**2. Feel free to provide a design supporting your feature request.**

**Comment by olemarkus** [comment]
This would definitely require extra contributors. Supporting additional cloud providers bring in a lot of new code that needs maintaining by other people than current active contributors. And in most cases also requires more than one contributor or commitment from the cloud vendor itself.

But if you or someone else is willing to give it a try, we are happy to support. Recent additions of Scaleway and Hetzner serves as good examples.

**Comment by AnirudhMohanKumar** [comment]
Was the effort already started to support IBM Cloud? I would like to contribute/initiate.

**Comment by olemarkus** [comment]
No. We have no PRs or similar in that area.

**Comment by AnirudhMohanKumar** [comment]
@olemarkus Thanks for responding.

I'm planning to attend the office hours this Friday to discuss on this feature. Do I have to contact anyone prior to let me in?
Also, added this item to agenda.

**Comment by olemarkus** [comment]
Hi no. The office hours are completely open to the public.
