### ISSUE TITLE
AWS: Allow shell access to instances via SSM Session Manager

### ISSUE THREAD

**Issue by pascal-hofmann** [kubernetes/kops#14462]
/kind feature

Allow shell access to EC2 instances via SSM Session Manager via `aws ssm start-session --target <instance-id>`

Required permissions for the instance are:
```
      "ssm:UpdateInstanceInformation",
      "ssmmessages:CreateControlChannel",
      "ssmmessages:CreateDataChannel",
      "ssmmessages:OpenControlChannel",
      "ssmmessages:OpenDataChannel",
```
on `"Resource": "*"`

*Note:* On slack there was [a discussion](https://kubernetes.slack.com/archives/C8MKE2G5P/p1664646111473329) about adding AWS default policy `AmazonSSMManagedInstanceCore`. This policy also allows the instance to read **all** SSM parameters, which is a security nightmare.

**Comment by johngmyers** [comment]
Could we not narrow `ssm:UpdateInstanceInformation` down to instances tagged to the cluster?

**Comment by pascal-hofmann** [comment]
The condition key `[ssm:SourceInstanceARN](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssystemsmanager.html#awssystemsmanager-ssm_SourceInstanceARN) is available for ssm:UpdateInstanceInformation. I guess this can be used to limit the instance to only update info for itself.
