### ISSUE TITLE
error reading cluster configuration

### ISSUE THREAD

**Issue by Marklon** [kubernetes/kops#1446]
HI All,

Not entirely sure if this is a bug or a configuration error on my part. I’m currently in the process of creating a cluster config.  My setup is, I’m ssh’d into a CentOS Linux 7 VM (Kernel: Linux 3.10.0-327.el7.x86_64). 

I’ve already installed the kops Version 1.4.4 and kubectl binaries and Exported my  various env variables for AWS.

When I try to create my cluster with  kops create cluster I get the below error

'error reading cluster configuration "demo.k8s.flowlog-stats.com": error reading configuration file s3://gar-kop-store/demo.k8s.flowlog-stats.com/config: error getting location for S3 bucket "gar-kop-store": NoSuchBucket: The specified bucket does not exist'

From what the error is stating "NoSuchBucket: The specified bucket does not exist"  I've verified this on the AWS console,  the s3 bucket of gar-kop-store does NOT exist. The simple thing to do is just create that bucket, but I thought  the point of kops was to be able to create these services for you automagically?

<img width="1277" alt="screen shot 2017-01-11 at 12 15 01 am" src="https://cloud.githubusercontent.com/assets/20350400/21856118/a473dd6a-d7d5-11e6-8af2-244796469a66.png">

@kris-nova

**Comment by kris-nova** [comment]
Hey @Marklon thanks for the issue

So as it stands the user needs to manually create the S3 bucket for the kops state store. There is a walk through you can read that has an example of doing it from the command line https://github.com/kubernetes/kops/blob/master/docs/aws.md#setting-up-a-state-store-for-your-cluster

So it would be possible to tether the commands together if you were trying to automate the process.

I also have talked about coming up with a clever way for having kops do this.. but as it stands this is one of the few manual steps that are needed to get a cluster off the ground.

**Comment by Marklon** [comment]
Perfect, I'll go ahead and create the bucket now. I have no problem doing it manually I was just uncertain of all of what kops can currently do. Having kops to be able to do that automagically would be great for any future features. 
Thank you again this is a big help!
