### ISSUE TITLE
Replace GCE with GCP

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#14474]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

As discussed during Office Hours, the GCE (Google Cloud Engine) name for the Google Cloud provider is not quite appropriate.
We should switch to the more correct GCP (Google Cloud Platform) naming, while still keeping the compatibility with older names.

**2. Feel free to provide a design supporting your feature request.**

As we are moving to v1alpha3 soon, this is a good opportunity to do this switch.

**Comment by johngmyers** [comment]
I could take a crack at this after #14443 merges.
