### ISSUE TITLE
Add Support for AWS G5 Instances

### ISSUE THREAD

**Issue by sekasara** [kubernetes/kops#14481]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
AWS recently announced the G5 instance type (https://aws.amazon.com/about-aws/whats-new/2021/11/announcing-general-availability-amazon-ec2-g5-instances). 
This is currently not a supported instance type, and it would be useful to be able to use these in our cluster, particularly for GPU-accelerated workloads.

**Comment by olemarkus** [comment]
kOps should support this as long as the given region supports it. Are you seeing any errors when trying to use it?

**Comment by sekasara** [comment]
@olemarkus Can you please help us with which version of kops is supporting G5 instance type ?  
getting below error.  
`spec.machineType: Invalid value: "g5.4xlarge": machine type specified is invalid`

**Comment by olemarkus** [comment]
In which region are you trying to use these?

**Comment by sekasara** [comment]
@olemarkus ap-south-1 region

**Comment by olemarkus** [comment]
Right. I don't think the instance type exists there. Only exists in Oregon, North Virginia, and Ireland.

**Comment by sekasara** [comment]
its available @olemarkus 
<img width="742" alt="image" src="https://user-images.githubusercontent.com/63733959/200287382-bf0e03d0-df15-4d65-b9c9-1e9b17e1b81e.png">
https://aws.amazon.com/ec2/pricing/on-demand/

**Comment by olemarkus** [comment]
The error specifically comes from the ec2 `DescribeInstanceType` API endpoint not returning any values.

**Comment by MinliangLin** [comment]
Hi @olemarkus. Not sure if this could help your debugging, I just tired the `DescribeInstanceType` api. It seems working well on my EC2 machine. The aws cli version I am using is `aws-cli/1.18.107 Python/2.7.18 Linux/4.14.192-147.314.amzn2.x86_64 botocore/1.17.31`

```
➜  ~ aws ec2 describe-instance-types --region ap-south-1 --instance-types g5.xlarge
{
    "InstanceTypes": [
        {
            "FreeTierEligible": false,
            "InstanceStorageSupported": true,
            "Hypervisor": "nitro",
            "PlacementGroupInfo": {
                "SupportedStrategies": [
                    "cluster",
                    "partition",
                    "spread"
                ]
            },
            "CurrentGeneration": true,
            "MemoryInfo": {
                "SizeInMiB": 16384
            },
            "SupportedVirtualizationTypes": [
                "hvm"
            ],
            "GpuInfo": {
                "Gpus": [
                    {
                        "Count": 1,
                        "MemoryInfo": {
                            "SizeInMiB": 24576
                        },
                        "Name": "A10G",
                        "Manufacturer": "NVIDIA"
                    }
                ],
                "TotalGpuMemoryInMiB": 24576
            },
            "VCpuInfo": {
                "DefaultCores": 2,
                "DefaultVCpus": 4,
                "DefaultThreadsPerCore": 2
            },
            "ProcessorInfo": {
                "SupportedArchitectures": [
                    "x86_64"
                ],
                "SustainedClockSpeedInGhz": 3.3
            },
            "BareMetal": false,
            "AutoRecoverySupported": false,
            "SupportedUsageClasses": [
                "on-demand",
                "spot"
            ],
            "NetworkInfo": {
                "EfaSupported": false,
                "NetworkPerformance": "Up to 10 Gigabit",
                "MaximumNetworkInterfaces": 4,
                "Ipv6Supported": true,
                "Ipv6AddressesPerInterface": 15,
                "EnaSupport": "required",
                "Ipv4AddressesPerInterface": 15
            },
            "SupportedRootDeviceTypes": [
                "ebs"
            ],
            "EbsInfo": {
                "NvmeSupport": "required",
                "EbsOptimizedSupport": "default",
                "EncryptionSupport": "supported",
                "EbsOptimizedInfo": {
                    "BaselineIops": 3000,
                    "MaximumThroughputInMBps": 437.5,
                    "MaximumIops": 15000,
                    "MaximumBandwidthInMbps": 3500,
                    "BaselineThroughputInMBps": 87.5,
                    "BaselineBandwidthInMbps": 700
                }
            },
            "HibernationSupported": false,
            "DedicatedHostsSupported": false,
            "BurstablePerformanceSupported": false,
            "InstanceType": "g5.xlarge",
            "InstanceStorageInfo": {
                "TotalSizeInGB": 250,
                "Disks": [
                    {
                        "Count": 1,
                        "Type": "ssd",
                        "SizeInGB": 250
                    }
                ]
            }
        }
    ]
}
```

**Comment by sekasara** [comment]
@olemarkus will check with latest version of kops and will update.

**Comment by justinsb** [comment]
So I am proposing some more self-descriptive error messages in #14544, in particular printing the region in the error message.

However, it looks like our logic is correct (at least in the latest version of kOps).  kops 1.11 is really old, so I'm not quite sure of the logic there.  Was that maybe a typo?

The behaviour is that we look up the region in the region that corresponds to the cluster `--zones`.  (We could have fixed that at some stage in the past though, which is why it would be good to know the kOps version).  If you specify `--zones=us-east-2a` (for example, where g5 is _not_ yet available), you would get the error message.  That's why I'm proposing to print the region, to highlight the problem.

If this is still a problem, can you include the failing command?  If it's `kops create cluster`, at least the `--zones` flag and the `--node-size` and `--master-size` flags!

**Comment by sekasara** [comment]
Hey @olemarkus @justinsb, Thanks for your time and effort on this issue. 
I tested with newer kops version 1.19.0. its working in 1.19.0

**Cause:**
When I checking in kops repo, it looks, only few defined instance types are supported until 1.18.3. (https://github.com/kubernetes/kops/blob/v1.18.3/upup/pkg/fi/cloudup/awsup/machine_types.go#L72)

From 1.19.0 only kops supporting all the aws supported instance types

Once again thank you so much for all you support. Thanks.

**Comment by ddelange** [comment]
Hi 👋

On kOps 1.26.3 (k8s 1.26.6), we're getting an error creating a new IG in aws eu-central-1c:
```
ondemand-arm-16GiB-4vCPU-1GPU-eu-central-1a.spec.machineType: Invalid value: "g5.xlarge": machine type architecture "x86_64" does not match image architecture "arm64", spec.mixedInstancesPolicy.instances[0]: Invalid value: "g5.xlarge": machine type architecture "x86_64" does not match image architecture "arm64"
```

There is only this one machine type in the IG, and it looks like kOps correctly assigns it an arm64 AMI.

But is Amazon mistakenly thinking this machine type is x86_64?

Any suggestions?
