### ISSUE TITLE
Node level autoscaling not working in KOPS

### ISSUE THREAD

**Issue by dhinesh2287** [kubernetes/kops#14493]
Hi All,
I have done the kubernetes setup with kops method i have deployed my applications on the servers all are working fine and also done the setup for HPA also it also working perfectly  i need to achieve the autoscaling on node level also can anyone help in this while increasing the load my pod got autoscaled but node instance didn't scaled please find the screenshots 
<img width="375" alt="k8-1" src="https://user-images.githubusercontent.com/99251741/199778168-c1c7530e-9d35-48a4-8718-6e613da01abd.png">
<img width="709" alt="k8-hpa" src="https://user-images.githubusercontent.com/99251741/199778187-82bb7e21-52d9-40c4-886c-797048b145b8.png">

**Comment by olemarkus** [comment]
You probably want this addon: https://kops.sigs.k8s.io/addons/#cluster-autoscaler

**Comment by dhinesh2287** [comment]
@olemarkus will check and try the site which you shared for addons and let you know

**Comment by dhinesh2287** [comment]
while adding the below fields into my cluster configuration i couldn't update the cluster iam getting the below errors can anyone kindly advise
spec:
  clusterAutoscaler:
    enabled: true
    expander: least-waste
    balanceSimilarNodeGroups: false
    awsUseStaticInstanceList: false
    scaleDownUtilizationThreshold: 1
    skipNodesWithLocalStorage: true
    skipNodesWithSystemPods: true
    newPodScaleUpDelay: 0s
    scaleDownDelayAfterAdd: 10m0s
    scaleDownUnneededTime: 10m0s
    scaleDownUnreadyTime: 20m0s
    image: <the latest supported image for the specified kubernetes version>
    cpuRequest: "100m"
    memoryRequest: "300Mi"
<img width="960" alt="CA" src="https://user-images.githubusercontent.com/99251741/200366056-f9cbac08-7af0-491a-a0ee-80246c5cedcc.png">
<img width="771" alt="CA-1" src="https://user-images.githubusercontent.com/99251741/200366086-744e1c9e-566f-432a-90b5-ff0cbd9b5586.png">

**Comment by olemarkus** [comment]
Try quoting the numeric values.

**Comment by dhinesh2287** [comment]
Still getting the same error can someone help in this case i want to do autoscale my nodes when no space left on the nodes

**Comment by olemarkus** [comment]
What error are you seeing? The one about passing a number to a string field? If so, did you try adding quotes?

**Comment by dhinesh2287** [comment]
I tried with the addons updated the details on my cluster configuration along with  quotes while doing cluster validation iam getting this below error @olemarkus 
<img width="776" alt="kops-validation" src="https://user-images.githubusercontent.com/99251741/206239233-e4d95ce7-477d-45d6-978c-830212d13ec3.png">
<img width="585" alt="kops-addon" src="https://user-images.githubusercontent.com/99251741/206239245-f47a8b0e-381e-49e9-976e-48043ae84803.png">

**Comment by olemarkus** [comment]
Firstly, you need to increase the max of your Node instance group. If you have min = max = 1, autoscaler cannot do anything at all.

That your cluster-autoscaler pod is pending is most likely due to lack of capacity. You may need to start off with a larger instance type.

**Comment by dhinesh2287** [comment]
@olemarkus Yes i tried with what you mentioned i.e min and max of my node instance i set min-1 & max-3 and deployed the application with 30 replica set in my case only 12 pods are up and running there is no space left on that instance at that time i didn't get any autoscaled instance i want to achieve this can you help
![image](https://user-images.githubusercontent.com/99251741/206415266-2dd77516-4512-433c-900a-b8301e7d965d.png)

![image](https://user-images.githubusercontent.com/99251741/206415047-b2740ba9-e1f6-4c7b-a28c-fccd69da20e5.png)

**Comment by olemarkus** [comment]
You need to describe those pending pods. There should be events explaining what CAS is doing (or not doing).

**Comment by ak2766** [comment]
Don't you hate it when someone reports an issue and then when they resolve they can't be bothered to return and report what they did to resolve the issue.  They want help but cannot help others who may be in the same predicament and need a solution.  Pity!

**Comment by ak2766** [comment]
On the contrary.  My normal process when starting up on something new - like adding node auto-scaling to my cluster, is to first investigate to see the history of the feature.  I also believe in `no pain no gain` so I prefer to read, then embark on trial and error until it works.
