### ISSUE TITLE
kubectl asks "Please enter Username:" over and over and gives bad results

### ISSUE THREAD

**Issue by vinayagg** [kubernetes/kops#1449]
I have 2 clusters and hence config file has two entries. First cluster is for everyone to use while second cluster is for my own experiments. I had deleted 2nd cluster about 6 weeks back but entries in config files stayed for some reason.

First cluster has 3 master nodes in 3 AZ on AWS and 2 slave nodes. It has been running idle for 3 weeks. At the end, I was neither able to use kubectl commands nor dashboard. Command log is attached below. Note that

1. for "cluster-info" it asked for uid/pwd, printed one line, asked uid/pwd 2 more times then printed rest of results
2. for "get pods" it asked for uid/pwd 2 times and still did not give pod listing. This command has also asked for uid/pwd 4 times, so it seems like
3. When I try to get to dashboard, I was getting following error in browser window (this happened 3 weeks ago as well)
   Error: 'dial tcp 10.123.45.2:9090: getsockopt: connection refused'
   Trying to reach: 'http://10.123.45.2:9090/'
4. Not knowing correct solution, I updated node sizes and forced a rolling update, it fixed all the issues. However this is not a usable solution in production env. 
5. Unfortunately I do not know exact steps to reproduce this issue. If/when it happens again, I can work with someone to debug it.

-----------------------------------------------------------------------------------
root@ip-x-x-x-x:~# kubectl cluster-info
Please enter Username: admin
Please enter Password: ********************************
Kubernetes master is running at https://api.k8s.example.com
Please enter Username: admin
Please enter Password: ********************************
Please enter Username: admin
Please enter Password: ********************************
Elasticsearch is running at https://api.k8s.example.com/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at https://api.k8s.example.com/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at https://api.k8s.example.com/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at https://api.k8s.example.com/api/v1/proxy/namespaces/kube-system/services/kube-dns
Grafana is running at https://api.k8s.example.com/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://api.k8s.example.com/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
root@ip-x-x-x-x:~# kubectl get pods
Please enter Username: admin
Please enter Password: ********************************
Please enter Username: admin
Please enter Password: ********************************
No resources found.

**Comment by vinayagg** [comment]
error no 3 is happening again. My dashboard is giving error. If someone wants to follow up, I can help debug

**Comment by justinsb** [comment]
@vinayagg from the IP address, I'm guessing this is a 1.4 cluster.  There are some big fixes in kubernetes 1.5 around the addressing modes on the master.  We should be releasing kops 1.5.0 this week, which will support the kubernetes 1.5 series (although kops 1.4.4 also supports it).

Can I ask therefore that you provide some more details if this happens with kops 1.5.0 and kubernetes 1.5 once we release kops 1.5.0?

In particular, the output from `kubectl get pods --all-namespaces` and `kubectl get services --all-namespaces` would be very helpful!

**Comment by vinayagg** [comment]
sure. You can close it for now. I will reopen it if it happens with 1.5
thanks

**Comment by VladimirTambovtsev** [comment]
Got the same issue in Ubuntu 20 
kubectl version: v1.20.4
```bash
helm version
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Error: Unauthorized
```
```bash
kops version
Version 1.19.1 (git-8589b4d157a9cb05c54e320c77b0724c4dd094b2)
```

**Comment by olemarkus** [comment]
Can you try to run `kops export kubecfg --admin`?

**Comment by aneeshpanoli** [comment]
I can confirm that I was able to get past `Please enter Username:` using `1.19.9`
```
kops export kubecfg --admin
Using cluster from kubectl context: ***.k8s.local
kops has set your kubectl context to ***.k8s.local
```
