### ISSUE TITLE
Missing ability to add patch permission for awscni if ANNOTATE_POD_IP enabled

### ISSUE THREAD

**Issue by kuzaxak** [kubernetes/kops#14495]
Kops [allows][3] configuring a list of env variables for `aws-cni`. But some of them require [additional permissions][1] for the cluster role.

Can we add the same [condition][2] to the addon template? 

[1]: https://github.com/aws/amazon-vpc-cni-k8s/tree/master#annotate_pod_ip-v193
[2]: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-vpc-cni/templates/clusterrole.yaml#L17-L22
[3]: https://kops.sigs.k8s.io/networking/aws-vpc/#configuration

/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.25.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.21.10

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by olemarkus** [comment]
/remove-kind bug
/kind feature

Happy to review a PR.

**Comment by MoShitrit** [comment]
I can take a look at that one
/assign
