### ISSUE TITLE
GCE Networking does not work for Kubernetes 1.24+ or containerd

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#14510]
/kind bug
/provider gcp

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.24+

**3. What cloud provider are you using?**

gce

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

https://testgrid.k8s.io/kops-gce#kops-grid-gce-gce-u2004-k22
https://testgrid.k8s.io/kops-gce#kops-grid-gce-gce-u2004-k23
https://testgrid.k8s.io/kops-gce#kops-grid-gce-gce-u2004-k24
https://testgrid.k8s.io/kops-gce#kops-grid-gce-gce-u2004-k25

**5. What happened after the commands executed?**

Nodeup fails:

`W1107 22:54:29.446705    1550 main.go:133] got error running nodeup (will retry in 30s): error building loader: building *model.ContainerdBuilder: NonMasqueradeCIDR is not set`

**6. What did you expect to happen?**

Working cluster

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

See definitions of above e2e tests

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

`ContainerdBuilder` is trying to configure ipmasq rules for gce because gce is `UsesKubenet()`. But building the ipmasq rules requires a `NonMasqueradeCIDR`, which in gce networking is never set. I suspect the builder should not build the ipmasq rules for gce networking.

**Comment by johngmyers** [comment]
GCE networking is not even mentioned in [`docs/networking.md`](https://kops.sigs.k8s.io/networking/). What is its support status? Should we fix it, deprecate it as of k8s 1.24, or remove it entirely?

**Comment by justinsb** [comment]
Looking into this - I think we need to set up the rules as here: https://github.com/kubernetes/cloud-provider-gcp/blob/043a2d5bab9959aa503806a099637049fe78d436/cluster/gce/gci/configure-helper.sh#L160-L175

**Comment by justinsb** [comment]
I also came across this issue: https://github.com/kubernetes/cloud-provider-gcp/pull/393

**Comment by brandonbell** [comment]
Any updates or workarounds for this?  We're currently running 1.21 using the `gce` networking so we can route directly to the pod IPs.
