### ISSUE TITLE
systemd unit hooks are not run on reboot

### ISSUE THREAD

**Issue by mwoodson-coinbasecloud** [kubernetes/kops#14527]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

We are running kops 1.24.2.  
We are running on flatcar linux.

We are creating some systemd unit via the "hooks" section. These hooks run on first boot, but if a node is rebooted, the hooks do not run.

In this particular scenario we are running a "oneshot" systemd unit file to disable a network setting (from another bug).  This works on the initial boot.  The network setting is applied.  On reboot (we don't want the node to reboot, but it happens), the network setting is not applied.  In the case of this bug, it cause the node to be even more unstable.

I've noticed that when the node reboots, the systemd unit goes into a "dead" state:

```
# systemctl status disable-generic-receive-offload.service
○ disable-generic-receive-offload.service - Disable generic receive offload on primary Ethernet interface
     Loaded: loaded (/etc/systemd/system/disable-generic-receive-offload.service; static)
     Active: inactive (dead)
```

Then I notice this unit file is NOT enabled:

```
# systemctl enable disable-generic-receive-offload.service
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.

Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
```

I would like to be able to have a systemd unit file start on reboot of the nodes.

**2. Feel free to provide a design supporting your feature request.**

**Comment by olemarkus** [comment]
The easiest fix for this is to supply your own raw manifest: https://kops.sigs.k8s.io/cluster_spec/#hooks
