### ISSUE TITLE
rolling update may result in downtime

### ISSUE THREAD

**Issue by vinayagg** [kubernetes/kops#1452]
if I edit kops instancegroups to add nodes or change size of nodes, when I do a rolling update, kops first shuts down an existing node and then starts a new node. This has bunch of issues:
- what if all remaining nodes do not have enough capacity to handle evacuated pods? It will lead to downtime
- pods need double migration - first to another existing node and then to a new node.

Instead, kops should first start a new node, then migrate the pods. This will lead to less risk and less downtime.

**Comment by chrislovecnm** [comment]
So we would need to figure out how to tweak the asg. I have a pr in progress for rolling update improvements. Can you make any recommendations on the design that you thinking about?

**Comment by vinayagg** [comment]
I am thinking of following algorithm

while (there are old nodes) {
  start a new node outside of ASG
  add new node to k8s
  evacuate the old node
  remove old node from ASG
  add new node to ASG
  terminate old node
}

This way manipulation of ASG will not be required.

**Comment by chrislovecnm** [comment]
Basically start a single node in a temp asg to serve for overflow. I would want to put it in an asg, but I do like it

**Comment by ese** [comment]
I think it would be great be able to indicate maxsurge  and maxunavailable like in kubernetes deployments (maybe 1 as default for both) https://kubernetes.io/docs/user-guide/deployments/#rolling-update-deployment.
A temp asg can be overkill I should be enough changing max parameter in asg to be able to launch more instances at the same time.

You can do some like this:

SetMax and desire with `desire instances + maxsurge`

While old_instances.lenght > maxsurge
  Wait for new instances
  Set new instances with scale-in protection
  drain old_nodes
  terminate old instances

drain old_nodes
SetMax and desire with `desire instances`
Wait for scale-in
Unset new instances with scale-in protection

**Comment by chrislovecnm** [comment]
Great idea, but let's crawl then walk then run ;)

**Comment by vinayagg** [comment]
I realized that my algorithm will take forever in case number of nodes are more than a handful.
So an alternate and easier implementation, at least to begin with, can be as follows

Start new nodes = as many as old nodes
issue pods evict from old nodes (I am assuming that k8s will continue to try to find nodes to move pods to, once new nodes are ready, all pods will be evicted)
as nodes eviction is completed, remove them from ASG and shut them down

Advantages of this algorithm are
- simpler, quicker to implement, at least for first cut
- will not take hours or days even if someone has 100s or 1000s of nodes
- can be easily enhanced with min/max surge algorithm afterwards

**Comment by nsauro** [comment]
Does the temp node need to be a temp asg?  Couldn't we just modify the existing asg to have +1 size? Then, perform the rolling restart, and then reduce the ASG size again?

**Comment by chrislovecnm** [comment]
With the new feature flag:

Use KOPS_FEATURE_FLAGS="+DrainAndValidateRollingUpdate" to use beta code that drains the nodes and validates the cluster. New flags for Drain and Validation operations will be shown when the environment variable is set. 

This should be addressed.  More work to do ... closing as we have https://github.com/kubernetes/kops/issues/1718 open.
