### ISSUE TITLE
Is it possible to have 1 NAT gateway?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1453]
Is it possible (even if not advisable for HA reasons) to have a single NAT gateway that serves a subnet in a different AZ?  Also I believe I have tried this before, but is it possible to have 2 NAT gateways (in different AZs) both as the default route for a single route table.

I think I know the answer here, but it would be good to get a link to confirm it as it keeps coming up.  Splitting off from #1448

cc @kris-nova

**Comment by kris-nova** [comment]
Maybe a dupe? https://github.com/kubernetes/kops/issues/1368

**Comment by chrislovecnm** [comment]
Yep a dup... closing for yah
