### ISSUE TITLE
node-termination-handler addon: webhookURL

### ISSUE THREAD

**Issue by voriol** [kubernetes/kops#14561]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

The "aws-node-termination-handler" have a "webhookURL" options to send notifications for, ie: slack:

https://github.com/aws/aws-node-termination-handler/blob/main/config/helm//README.md

```
webhookURL: Posts event data to URL upon instance interruption action. 
webhookURLSecretName: Pass the webhook URL as a Secret using the key webhookurl. 
```

But configuring the kops addon, i don't finde that option:

https://kops.sigs.k8s.io/addons/#node-termination-handler

It exists?

Thanks!

**2. Feel free to provide a design supporting your feature request.**

https://github.com/kubernetes/kops/issues/14561#tasklist-block-31f6bfb1-463d-47ac-ad24-6e9ff722886e

**Comment by olemarkus** [comment]
This feature currently does not exist, but shouldn't be too hard to add. Happy to review a PR

**Comment by voriol** [comment]
New try

https://github.com/kubernetes/kops/pull/14562
