### ISSUE TITLE
 got error running nodeup (will retry in 30s): error loading Cluster

### ISSUE THREAD

**Issue by InTheCage** [kubernetes/kops#14570]
/kind bug

**1. What `kops` version are you running? `1.25.2`

**2. What Kubernetes version are you running? `v1.25.4`

**3. What cloud provider are you using?** `Openstack`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```yaml
kops create cluster \
  --cloud openstack \
  --name my-cluster.k8s.local \
  --state ${KOPS_STATE_STORE} \
  --api-loadbalancer-type="" \
  --zones nova \
  --network-cidr 10.0.0.0/24 \
  --image "Ubuntu Server 22 NKVM" \
  --master-count=1 \
  --node-count=1 \
  --node-size "t.large" \
  --master-size "t.large" \
  --topology public \
  --ssh-public-key ~/.ssh/id_rsa.pub \
  --networking calico \
  --os-ext-net internet \
  --os-ext-subnet public \
  --yes
```

**5. What happened after the commands executed?**
Cluster creates, but node not start.
Log of kops-configuration.service
```
Nov 16 nodeup[1412]:         status code: 404, request id:
Nov 16 nodeup[1412]: W1116 14:11:12.596420    1412 main.go:133] got error running nodeup (will retry in 30s): error loading Cluster "s3://heres3address" Unable to list AWS regions: NoCredentialProviders: no valid providers in chain
Nov 16 nodeup[1412]: caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
Nov 16 nodeup[1412]: SharedCredsLoad: failed to load profile, .
Nov 16 nodeup[1412]: EC2RoleRequestError: no EC2 instance role found
Nov 16 nodeup[1412]: caused by: EC2MetadataError: failed to make EC2Metadata request
Nov 16 nodeup[1412]: 404 Not Found
Nov 16 nodeup[1412]: The resource could not be found.
Nov 16 nodeup[1412]:    
Nov 16 nodeup[1412]:         status code: 404, request id:
```

**6. What did you expect to happen?**
nodes sucessefuly start

**9. Anything else do we need to know?**
aws credentials:
config:

```
[default]
region = eu-central-1
output = json
```

creds:

```
aws_access_key_id = idkey
aws_secret_access_key = keyofkey
```

**Comment by hakman** [comment]
@InTheCage Is the AWS part for the S3 storage?

**Comment by InTheCage** [comment]
@hakman 

yep. 

Also in env configured KOPS_STATE_STORE=s3://storage...

**Comment by hakman** [comment]
In this case, I think you need to set the S3 related env vars instead:
```
export S3_REGION=<region>
export S3_ENDPOINT=<endpoint>
export S3_ACCESS_KEY_ID=<acces-key>
export S3_SECRET_ACCESS_KEY=<secret-key>
```

**Comment by InTheCage** [comment]
@hakman 

if i setup export S3_ENDPOINT it conflicts with KOPS_STATE_STORE

export S3_ENDPOINT=s3bucket

export KOPS_STATE_STORE=s3bucket

And state-store trying access s3://s3bucket/s3bucket/my-cluster.k8s.local/config

Also i noticed here is no config file located by $HOME/.kops.yaml

Im using macOS Ventura 13.0.1

**Comment by hakman** [comment]
See more about S3 endpoints: https://docs.aws.amazon.com/general/latest/gr/s3.html.
Should be something like: `s3.eu-central-1.amazonaws.com`.
