### ISSUE TITLE
How to find ca.crt and ca.key in gcp cloud storage bucket

### ISSUE THREAD

**Issue by learningcloudk8** [kubernetes/kops#14627]
I have created kubernetes cluster with kops with below command. I couldn't see ca.crt and ca.key in bucket. May i know where i can get it? Am i missing anything here?

kops create cluster gcpcloud44.xyz --zones us-central1-b,us-central1-a --state ${KOPS_STATE_STORE}/ --project=${PROJECT} --node-count=2 --master-count=1 --node-size=e2-medium --master-size=e2-medium --dns-zone=gcpcloud44.xyz --ssh-public-key=/root/.ssh/id_rsa.pub --yes

I could pki object folder inside bucket but couldn't see any key or crt related files.

**Comment by johngmyers** [comment]
Look for `keyset.yaml`

**Comment by hakman** [comment]
I guess the question was addressed. Please reopen if you think more info is required.
