### ISSUE TITLE
Executable perms on download

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kops#1463]
Using `kops-darwin-amd64` for 1.5.0-alpha3

The download had to be explicitly given executable perms using `chmod +x kops-darwin-amd64`.

It would be great if this could be the default behavior

**Comment by chrislovecnm** [comment]
We have tossed around the idea of having an install script like https://github.com/kubernetes/kops/issues/1210 ...

With brew you get an executable install if you are on osx.  Any idea how to do it without an install script?

**Comment by arun-gupta** [comment]
`brew install` would be nice. Although a simple fix where `chmod +x` is not required would be sufficient to begin with.

**Comment by chrislovecnm** [comment]
we have brew install :)

**Comment by arun-gupta** [comment]
Ah ok, didn't know that. Then I guess `chmod +x` would be really good!

On a separate note, I find `kops` usage a bit cumbersome. Ping me in slack channel and then we can talk more.

**Comment by chrislovecnm** [comment]
If you can add product requests via issues that would be awesome.  Happy to set up a time to have a zoom call as well.  You are not online right now ;)

**Comment by arun-gupta** [comment]
Setup a zoom call next Tuesday afternoon? I can submit the request after we discuss.
