### ISSUE TITLE
Overcome a limit on target groups

### ISSUE THREAD

**Issue by dmytronasyrov** [kubernetes/kops#14646]
There is an AWS limitation on updates of no more than 10 target groups of load balancers at once. I have > 10 instance groups in the cluster, all of which are linked to the single LB. When I try to update any instance group, I get the error:
`Error: error running tasks: deadline exceeded executing task AutoscalingGroup/TGname. Example error: error detaching TargetGroups: ValidationError: Trying to update too many Load Balancers/Target Groups at once. The limit is 10`
I assume the issue can be solved by adding more LBs. But there is no such requirement for now. Any idea how to overcome the limitation?

**Comment by hakman** [comment]
Thanks for reporting this @dmytronasyrov.
Any chance you have a test system on which you could test the proposed fix?

**Comment by dmytronasyrov** [comment]
> Thanks for reporting this @dmytronasyrov. Any chance you have a test system on which you could test the proposed fix?

Unfortunately, it's our production env with a lot of different things and it's super-complex to cut the demo out.
Here are 2 pages related to ALB and NLB quotas. I'm not sure why it says 10 TGs because in quotas I see 5 TGs per ALB and 1 TG per NLB per action. And these limits are not adjustable in the console.
[](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-limits.html)
[](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html)

**Comment by hakman** [comment]
My problem is that I don't have a setup where it's easy to test such thing.
It would be helpful to see if there's a way to test the patch I made before merging it. Technically, you just need a new `kops` binary that contains the fix.

**Comment by hakman** [comment]
The possible fix for the issue should be part of today's releases:
https://github.com/kubernetes/kops/releases/tag/v1.24.5
https://github.com/kubernetes/kops/releases/tag/v1.25.3
