### ISSUE TITLE
Add support for recently available new AWS region "eu-south-2"

### ISSUE THREAD

**Issue by nineunderground** [kubernetes/kops#14679]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Basically, I'd like that new aws region (*eu-south-2*) is included in next kops version. So, then nodeup process will not fail when starting on _kops create cluster_ if that region manages the state in a AWS S3 bucket located there.

**2. Feel free to provide a design supporting your feature request.**
I imagine this just a simple value to include the new region into a SET variable type in nodeup script.
Furthermore, it will be nice if there is a a feature that allows end user to skip such validation like in other tools like terraform. So, adding something to _kops create cluster_ like _--skip-region-validation_.
I feel it should be global scope flag because all public clouds are scaling to regions once in a while, not just affecting AWS platform

**Comment by johngmyers** [comment]
You should be able to give `kops create cluster` the `--cloud aws` flag so it doesn't have to rely on its table mapping regions to cloud providers.

**Comment by olemarkus** [comment]
A new region also requires updated AWS SDK, so usually a new version is required anyway. But kOps latest should have a new enough SDK.

**Comment by nineunderground** [comment]
> You should be able to give `kops create cluster` the `--cloud aws` flag so it doesn't have to rely on its table mapping regions to cloud providers.

Well, I feel it does. I tried that and running with latest tools (kops 1.25.2 and aws-cli 2.9.1) and dns-controller never runs, and nodeup log gives errors about the region not valid. So, I assume there is a validation blocking. (_I know there is kops 1.25.3 out there, but I don't see a reference about the new region in changelog, so I guess that won't solve the problem_)
Anyway, this was more like a suggestion to skip the region validation because it doesn't block end users to use new regions from day one.

**Comment by johngmyers** [comment]
There is no validation in kOps proper, just code that guesses cloud provider from region name upon creation. There well might be in the AWS SDK, but that is not in our power to remove. We don't replicate their release notes.

**Comment by johngmyers** [comment]
We probably should add some validation of the region so that the failure happens sooner. The error message should refer to "supported by the <cloud-provider> SDK".

**Comment by nineunderground** [comment]
No problem. Thus AWS SDK should fix that eventually.
Thanks for clarification
