### ISSUE TITLE
needs more documentation about ha

### ISSUE THREAD

**Issue by ghost** [kubernetes/kops#14677]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

**2. Feel free to provide a design supporting your feature request.**

needs more documentation about ha

**Comment by tanshilingithub** [comment]
kops is a nice project, but it has some different with our behavior, maybe i will describe it and implement it to push

**Comment by johngmyers** [comment]
The current documentation on HA is https://kops.sigs.k8s.io/operations/high_availability/

If that is insufficient, then it would be helpful to state what information is missing.

**Comment by tanshilingithub** [comment]
Sorry, I feel that the above document lacks more professional explanations, such as how the `kube-master` component group (`apiserver`, etc.) forms a cluster, and how components such as `kubelet` are connected to the master cluster

**Comment by tanshilingithub** [comment]
Yes, I am looking at the source code too, it is really good, but it will take some time

**Comment by johngmyers** [comment]
Ah, that document is intended for operators, giving them information on how to create and operate an HA cluster.

`contributing/how_it_works.md` is closer for those who want to know how things work. There's also `boot-sequence.md`.

**Comment by tanshilingithub** [comment]
ok, maybe it just called cloud's api interface to create a k8s cluster? but it maybe don't feel like this?

**Comment by johngmyers** [comment]
See `terraform.md` if you want to use Terraform instead of directly calling the cloud provider's API.

**Comment by tanshilingithub** [comment]
ok, thanks
