### ISSUE TITLE
Question. How to enable custom metrics.

### ISSUE THREAD

**Issue by katsika** [kubernetes/kops#1467]
I am trying to use custom metrics to scale our cluster upon.
Came across this document which describes how to achieve that.

https://github.com/mwielgus/kubernetes.github.io/blob/custom-metrics/docs/user-guide/horizontal-pod-autoscaling/index.md#support-for-custom-metrics

My question is how how to start/edit cluster with `ENABLE_CUSTOM_METRICS` variable set to `true`.

**Comment by justinsb** [comment]
This needs us to map a flag (--enable-custom-metrics I believe).  I'll mark it as such and circle back and add the requested flags en-masse.

**Comment by kwinczek** [comment]
Thank you @justinsb.

**Comment by kwinczek** [comment]
Hey @justinsb, now with 1.5.1 released, how can one enable custom metrics? It seems there is no documentation whatsoever.

I tried to set enableCustomMetrics to true in cluster configuration but it gets erased, same for nodes ig.

Thanks!

**Comment by lamchakchan** [comment]
@justinsb I'm also needing to understand how to use this new flag?  is it something along the lines of `kops create cluster --enableCustomMetrics` ?

**Comment by 23doors** [comment]
Any news on that? Lots of things changed in 1.6 regarding custom metrics but still, docs on this topic are fuzzy at best.

**Comment by kenden** [comment]
This continues in https://github.com/kubernetes/kops/issues/2652

**Comment by chrislovecnm** [comment]
This is an API value that needs to be added to the kubelet section. The new yaml docs that were added should help. Here is the PR that was added for the flag.

https://github.com/kubernetes/kops/commit/db54ecf23de0de7ef15b4bd453365fa7290309f4

This doc talks about using and editing the yaml API of a cluster https://github.com/kubernetes/kops/blob/master/docs/manifests_and_customizing_via_api.md

**Comment by itskingori** [comment]
@kwinczek this is probably a late answer to your question but an answer nonetheless. You need something like this in your cluster spec ...

```yaml
spec:
  kubelet:
    enableCustomMetrics: true
    resolvConf: ""
```

This was enabled/added in https://github.com/kubernetes/kops/commit/db54ecf23de0de7ef15b4bd453365fa7290309f4. The reason you need `resolvConf: ""` is [explained here][1] i.e.

```
NOTE: Where the corresponding configuration value can be empty,
fields can be set to empty in the spec, and an empty string will be
passed as the configuration value.
```
If you don't set it, you won't be able to save the change as kops will complain of invalid value (or something like that ... don't quite remember what the error was).

By, _"Where the corresponding configuration value can be empty"_ ... they mean [this part of the cluster component][2]. 

[1]: https://github.com/kubernetes/kops/blob/98ae12a1520bcc8460f074b041d13e12749395e2/docs/cluster_spec.md#kubelet
[2]: https://github.com/kubernetes/kops/blob/9668b0fe8a65f1a4e0ae8204f2be7e5fd3b81082/pkg/apis/kops/componentconfig.go#L243-L245

**Comment by RahulMahale** [comment]
I am getting the same error on adding it to my cluster spec in both the ways.
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
 # and an empty file will abort the edit. If an error occurs while saving this file will
# reopened with the relevant failures.
# Found fields that are not recognized
#  kubelet:
#       enableCustomMetrics: true
# +     resolvConf: /etc/resolv.conf
```

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
   # and an empty file will abort the edit. If an error occurs while saving this file will be
   # reopened with the relevant failures.
   #
   # Found fields that are not recognized
   # ...
   #     kubelet:
   #       enableCustomMetrics: true
   # +     resolvConf: ""
```

**Comment by moos3** [comment]
Any updates on this?

**Comment by RahulMahale** [comment]
@moos3  I got it working using
```kops edit cluster
spec:
  kubelet:
    enableCustomMetrics: true
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2alpha1: "true"
```
and then 
```
kops update cluster --yes
kops rolling-update cluster --yes --force
```

But not able to get autoscaling based on QPS working.

**Comment by moos3** [comment]
Awesome, trying now.

**Comment by chrislovecnm** [comment]
Re-opening.

Does someone mind documenting once we figure this out?

**Comment by itskingori** [comment]
@chrislovecnm I don't mind doing it ... I can give this a stab this week and report back.

**Comment by RahulMahale** [comment]
@chrislovecnm @itskingori  I can document it can you point me where to document that ? I will create a PR. Thanks.

**Comment by chrislovecnm** [comment]
@RahulMahale https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md is probably best :)

**Comment by RahulMahale** [comment]
Thank @chrislovecnm here we go https://github.com/kubernetes/kops/pull/3570

**Comment by itskingori** [comment]
@RahulMahale awesome! Keen to give it a spin.

**Comment by itskingori** [comment]
This is safe to close. Added [horizontal_pod_autoscaling.md](https://github.com/kubernetes/kops/blob/master/docs/horizontal_pod_autoscaling.md) in https://github.com/kubernetes/kops/pull/3942 which explains the how. If not clear, lemme know and I can clarify/assist.

**Comment by alrf** [comment]
How to use `enable-custom-metrics` from command line?
kops returned the error:
unknown flag: --enable-custom-metrics

**Comment by itskingori** [comment]
@alrf I think you might have been confused by https://github.com/kubernetes/kops/issues/1467#issuecomment-273027105. There's no `--enable-custom-metrics` on the `kops` command. What Justin was referring to is the mapping of the config that the user will provide to the flag that needs to be set on the respective Kubernetes component.

So if you set this ...

```yaml
spec:
  kubelet:
    enableCustomMetrics: true
```

... in your kops cluster state, the flag will be set where it needs to be set.

**Comment by jsenon** [comment]
does this command deprecated?  
`Sep 27 07:52:00 ip-1xxxx kubelet[10434]: F0927 07:52:00.304903   10434 server.go:148] unknown flag: --enable-custom-metrics`

**Comment by jsenon** [comment]
It seems yes [52564](https://github.com/kubernetes/kubernetes/issues/52564)
