### ISSUE TITLE
Support split-horizon DNS on Route 53

### ISSUE THREAD

**Issue by dosullivan** [kubernetes/kops#1468]
In certain situations, it may be desirable to use split horizon DNS in your environment. When attempting to create a cluster with kops on AWS in an environment with split horizon DNS, kops will error out during the cluster creation process. Here's the gist of what I was running when I ran into this:

>kops create cluster \
>--master-zones=us-east-2a,us-east-2b,us-east-2c \
>--zones=us-east-2a,us-east-2b,us-east-2c \
>--node-count=3 \
>--node-size=t2.medium \
>--master-size=t2.micro \
>--topology=private \
>--networking=weave \
>--vpc=(my-test-vpc) \
>--ssh-public-key=(my-pub-key) \
>--state=s3://(my-s3-bucket) \
>--name=staging-k8s.(mytestzone.net) \
>--dns-zone=(mytestzone.net) \
>--dns=private 

I had set up a public and private zone for the domain I was using in this environment. On the last few options, selecting `--dns=private` and specifying the dns zone name should seemingly imply that I want kops to work with the private zone specifically, but kops doesn't interpret it that way. Instead, it reports back that multiple zones have the same name and fails:

`W0113 12:19:21.845768   63796 executor.go:109] error running task "DNSZone/(mytestzone).net" (9m59s remaining to succeed): found multiple hosted zones matched name "(mytestzone).net."`

I can see ways in which I could change my setup to work around this issue, but would it be possible to make kops work specifically with the zone specified in the `--dns` option (either public or private)?

**Comment by justinsb** [comment]
Thanks for the report @dosullivan 

So kops should have also printed a suggestion that you provide the `--dns-zone` flag with an id, but I can't find the code to do that!  I am adding that back in #1500.

That said, we could also make this choice for you.  If you say --dns=private, I think we should look only for private hosted zones (is that right?)

But another question: do you expect kops would publish records into both zones?  For example for the API?  Any clarification on how you use this in practice would be greatly appreciated!

**Comment by dosullivan** [comment]
For me personally, when a public and private zone both of the same `mytestzone.net` name are present in route 53, I am ok with kops making the choice for me on which zone it's working with, as long as I am specifying `--dns-zone=mytestzone.net` and also `dns=private`, as I see that second option as implying that it should pick the private zone.

However, having kops return a printed suggestion (and the ability) to provide a specific zone ID for the `--dns-zone` flag is definitely useful as well. 

In my use case, I have a VPC that has a default domain name set up with split-horizon DNS, which is pretty much so that we can segment specific services to be private or public, but maintain the same domain for TLS certification purposes. For example, when using Let’s Encrypt with DNS txt record verification, you can use a public zone to publish the txt record necessary for verification, but then actually use your certificates for private services under the same domain name.
