### ISSUE TITLE
Use private S3 bucket for ServiceAccountIssuerDiscovery

### ISSUE THREAD

**Issue by chubchubsancho** [kubernetes/kops#14699]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Configure `ServiceAccount IssuerDiscovery` in a non-public S3 bucket. Some company prevents the `public-read` ACL from being used.

```
error running task "ManagedFile/keys.json" (6m19s remaining to succeed): error creating ManagedFile "openid/v1/jwks": error writing s3://my_bucket/v1/jwks (with ACL="public-read"): AccessDenied: Access Denied
```

**2. Feel free to provide a design supporting your feature request.**

We propose to add a cloudfront upstream of the private S3 bucket and to use this cloudfront as a provider.
We propose to leave the possibility to define the PriceClass for this cloudfront as well as to enable or disable logs for this distribution.

 eg for API struct
```go
type ServiceAccountIssuerDiscoveryConfig struct {
	// DiscoveryStore is the VFS path to where OIDC Issuer Discovery metadata is stored.
	DiscoveryStore string `json:"discoveryStore,omitempty"`
	// EnableAWSOIDCProvider will provision an AWS OIDC provider that trusts the ServiceAccount Issuer
	EnableAWSOIDCProvider bool `json:"enableAWSOIDCProvider,omitempty"`
	// AdditionalAudiences adds user defined audiences to the provisioned AWS OIDC provider
	AdditionalAudiences []string `json:"additionalAudiences,omitempty"`
	//
	PrivateDiscoveryStore PrivateDiscoveryStore `json:"privateDiscoveryStore,omitempty"`
}

type PrivateDiscoveryStore struct {
	Enabled              bool              `json:"enabled,omitempty"`
	CloudfrontPriceClass string            `json:"cloudfrontPriceClass,omitempty"`
	CloudfrontLogging    CloudfrontLogging `json:"cloudfrontLogging,omitempty"`
}

type CloudfrontLogging struct {
	Enabled bool    `json:"enabled,omitempty"`
	Bucket  *string `json:"bucket:omitempty"`
	Prefix  *string `json:"prefix,omitempty"`
}
```

We are waiting your approval for start developpement

**Comment by chubchubsancho** [comment]
I understand your point of view.
We currently provide the url of our OIDC provider to kube-apiserver. This requires us to maintain this stack.
As kOps allowed the implementation of IRSA in a simple way we wanted to use this capability and not have to maintain the stack.

**Comment by johngmyers** [comment]
I would say if you want to use this capability, your company needs a more reasonable policy.

**Comment by olemarkus** [comment]
and FWIW that one bucket with two files containing public information is _significantly_ safer than exposing any aspect of the API server on the public internet.

**Comment by chubchubsancho** [comment]
Another approach could be to permit user to overide endpointURL used when creating OIDCProvider.

 ```yaml
type ServiceAccountIssuerDiscoveryConfig struct {
	// DiscoveryStore is the VFS path to where OIDC Issuer Discovery metadata is stored.
	DiscoveryStore string `json:"discoveryStore,omitempty"`
	// EnableAWSOIDCProvider will provision an AWS OIDC provider that trusts the ServiceAccount Issuer
	EnableAWSOIDCProvider bool `json:"enableAWSOIDCProvider,omitempty"`
	// AdditionalAudiences adds user defined audiences to the provisioned AWS OIDC provider
	AdditionalAudiences []string `json:"additionalAudiences,omitempty"`
	//
	PrivateDiscoveryStore bool `json:"privateDiscoveryStore,omitempty"`
        OverdideEndpointURL string `json:"overideEndpointURL,omitempty"`
}
```

`PrivateDiscoveryStore` will allow kOps to upload `.well-known/openid-configuration` and `jwks.json` without `public-read-acl`
`OverideEndpointURL` will allow user to provide URL of  `cloudfront` or any web server self managed with read access to bucket.

WYT

**Comment by chubchubsancho** [comment]
It's a security best practice to disable `ACLs` on S3 buckets. As all team in our organization can create S3 buckets and to ensure none of them as public access we define `block public access` at account level. So we cannot make per bucket exception as this setting take precedence on other.

I understand you point of view. We will ask AWS their recommendation on that point.

**Comment by johngmyers** [comment]
It might be possible to put the bucket in a different account.

**Comment by johngmyers** [comment]
Omitting per-object ACLs when the whole bucket permits public read is what another PR is doing for GCS. It would make sense to extend that logic to AWS.

**Comment by chubchubsancho** [comment]
@vgrudenic Hi, we still continue to deploy `IRSA` on our side without doing it from `kOps`.
We create `private S3 buckets`  behind a `Cloudfront` distribution.
I've no time for now but i still looking for another implementation on kOps.
Regarding what is done on `EKS`, `oidc provider` target an `API Gateway` to handle request. Maybe `kOps` can do the same :man_shrugging:
