### ISSUE TITLE
Concerns about the MPL-2.0 of Hashicorp deps

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#14690]
/kind office-hours

CNCF did a license scan as part of https://github.com/kubernetes/community/issues/6992 and kOps is mentioned with the as using deps under the MPL-2.0 license which is weak copyleft (**Be sure that it is used only as dynamic libraries, to be safe if it's not required remove it from your repo.**):
```
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/errwrap/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-cleanhttp/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-immutable-radix/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-multierror/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-plugin/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-retryablehttp/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-rootcerts/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-secure-stdlib/mlock/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-secure-stdlib/parseutil/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-secure-stdlib/strutil/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-sockaddr/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-uuid/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/go-version/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/golang-lru/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/hcl/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/hcl/v2/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/memberlist/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/vault/api/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/vault/sdk/LICENSE
kubernetes-2022-10-13.zip/kops/vendor/github.com/hashicorp/yamux/LICENSE
```

**Comment by hakman** [comment]
We need to file for license exceptions: https://github.com/cncf/foundation/tree/main/license-exceptions.
Example: https://github.com/cncf/foundation/issues/294.

**Comment by johngmyers** [comment]
Okay, I'll bite: why don't we remove that code from our repo?

We really don't need a fancy parsing library in order to generate Terraform code.

The cert-manager client for its CRDs lists those licenses, though doesn't include any of that code. If it causes problems for our scanner, we might be able to generate those clients ourselves.

We'd probably have to drop support for Vault. Seems a logical consequence to HashiCorp of their licensing their libraries that way.

**Comment by olemarkus** [comment]
I am for removing the vault support. It never reached stable and I've not seen a single feature/support request around this. No idea if it even works anymore.

**Comment by hakman** [comment]
+1 for vault support removal.
I have no idea why we are using the fancy library to generate Terraform code. I was wondering the same last time I touched that code. We could try removing this one too and lighten our deps load.

**Comment by johngmyers** [comment]
I'll take on refactoring the Terraform generation code.

**Comment by mrbobbytables** [comment]
If it helps, some of the hashicorp libraries have [exceptions](https://github.com/cncf/foundation/blob/ae2f009a1295646a9c9b01561e86358495758160/license-exceptions/cncf-exceptions-2019-11-01.json) already and can be ignored from the report:

- hashicorp/hcl
- hashicorp/golang-lru
- hashicorp/errwrap
- hashicorp/go-cleanhttp
- hashicorp/go-multierror

**Comment by johngmyers** [comment]
We're still getting hashicorp/hcl coming in through spf13/viper. Fortunately, it's got an exception.

It doesn't look like the scanner is looking at cert-manager's LICENSES file.

**Comment by johngmyers** [comment]
I think we're good for now.
