### ISSUE TITLE
[Bug] kops create and kops delete behave in strange ways when there are resources with the same $CLUSTER_NAME in an AWS account/region 

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#1473]
This is an edge case that may seem improbable, but it does pop up and beyond being confusing, it has the potential to cause serious problems if the user is not paying close attention. 

**Problem Setting:** I am working in an AWS region with a number of VPCs and an assortment of existing resources, some generated by `kops`, others not. I am preparing to create new cluster in an existing- but so far- "unused/fresh" cluster. By "unused/fresh", I mean this VPC was generated by Terraform and it has a number of public and private subnets, NAT gateways, routing tables, etc. But no EC2 instances, nor any Kubernetes/kops-generated resources. 

I chose a `$CLUSTER_NAME` that I believed was likely to be unique at the time (within my AWS account region), but it turned out that the `$CLUSTER_NAME` had already been used by `kops` in another VPC owned by my account in the same region. These other resources had been created at some earlier point. For my work today, they are existing assets. 

At this point, I configured my settings and ran `kops create cluster`. It immediately began to exhibit some peculiar behavior, so I stopped it, wondering what had gone wrong. Basically, `kops` looked like it had skipped the `create` stage and skipped right to `update`. That was confusing, but it didn't blow anything up. 

I figured I had done something wrong, so I tried to `kops delete cluster`, and I was quite surprised to see a whole list of resources that `kops` was ready to delete. I did some digging and I was very surprised that these resources were in a VPC that I hadn't provided to `kops` and hadn't even looked into yet. If I had quickly run `kops delete cluster $CLUSTER_NAME --yes`, these resources would have been systematically removed by `kops`. I think this is confusing for users, at best, and likely dangerous. I don't think it's likely to happen frequently, but the impact could be very severe.

**Proposal:** I now understand that `kops` determines which resources it has at it's disposal solely via tags. I assumed that my VPC created a wall beyond which `kops` knew nothing. Not only does it know about the other resources, it can inadvertently delete them if you do something silly like try to reuse `$CLUSTER_NAME`.

I think it is in our interest to do everything that we can to verify that the cluster we are "working on" is "our cluster". For me, that means tagging a bit more explicitly than a `$CLUSTER_NAME` and then- especially before deleting resources- double checking that we're operating on the correct leg! I think this might be useful in terms of cluster creation as well, but I'd like to hear others' ideas. 

@justinsb and I batted around a couple ideas like generating a UUID or a cluster-specific (more-so than `$CLUSTER_NAME` and the tagging the cluster resources with them. Then we could check against each item before deleting. Or maybe we could just filter in or out the stuff that we did or not want.

**Comment by yissachar** [comment]
Related: https://github.com/kubernetes/features/issues/173

**Comment by geojaz** [comment]
This will be closed by #2429
