### ISSUE TITLE
Support the new AWS Hyderabad region (ap-south-2)

### ISSUE THREAD

**Issue by ravids** [kubernetes/kops#14739]
/kind feature

**1. AWS announced the availability of the Hyderabad region on Nov 21. The updated AWS SDK is in the main branch and in v1.26.0-alpha.2 preview release. However, the [etcd-manager](https://github.com/kubernetes-sigs/etcdadm) dependency artifact is still not using the updated AWS SDK**

**2. Troubleshooting already performed**
***kops client***
v1.26.0-alpha.2 preview release contains the updated kops client. I built from master also and verified that the kops client supports ap-south-2. 
***nodeup***
[v1.26.0-alpha.2  release artifacts](https://kops-artifacts.s3.ap-south-2.amazonaws.com/kops/1.26.0-alpha.2) has support for ap-south-2. I also built the artifacts from master and pushed them to a custom s3 bucket, and confirmed support for ap-south-2. On a different aspect, cluster creation looks for arm artifacts even when the node architecture is set to amd64 (export NODE_ARCHITECTURE=amd64). I had to copy arm artifacts to the custom s3 bucket.
***etcd-manager***
I can build the etcd-manager. However, not sure where the nodes are pulling the binary from. I am trying to figure out and use the updated binary with support for ap-south-2.

Meantime, I would appreciate your plan to support ap-south-2 end to end with a stable release. When is it planned for?

**Comment by hakman** [comment]
Already updated `aws-sdk-go` as part of https://github.com/kubernetes-sigs/etcdadm/pull/346.
There should be a new `etcd-manager` release soon.
Try `KOPS_ARCH=amd64` instead of using `NODE_ARCHITECTURE `.

**Comment by ravids** [comment]
Thanks @hakman. For the moment, I used an S3 state bucket in a different region by exporting the following env variables.
```
export S3_ENDPOINT
export S3_REGION
export S3_ACCESS_KEY_ID
export S3_SECRET_ACCESS_KEY
```

**Comment by hakman** [comment]
Thanks for the update. Let me know if `KOPS_ARCH=amd64` helps.

**Comment by hakman** [comment]
New `etcd-manager` release today https://github.com/kubernetes-sigs/etcdadm/pull/351.
Should be available to pull from `registry.k8s.io/etcdadm/etcd-manager:v3.0.20221209`.
