### ISSUE TITLE
Kops should validate if etcd has quorum or the config doesn't make sense

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1474]
For example 2 or 4 nodes would end up with a useless master node (won't join the cluster either)

**Comment by chrislovecnm** [comment]
Indeed

**Comment by justinsb** [comment]
So we do validate this on `kops create cluster`

```
> kops create cluster even.example.com --zones=us-east-1b,us-east-1c --master-zones=us-east-1b,us-east-1c
...

There should be an odd number of master-zones, for etcd's quorum.  Hint: Use --zones and --master-zones to declare node zones and master zones separately.
```

We don't perform validation on update though - and we should: https://github.com/kubernetes/kops/issues/1496 

Is that what you mean @blakebarnett ?

**Comment by blakebarnett** [comment]
Ah, yes because if you use `kops create -f` it doesn't do a validation (since you have to create instancegroups separately, etc.)  So probably update is the proper place for it, especially given that it's where the destructive operations happen.

**Comment by chrislovecnm** [comment]
@blakebarnett I think what you said actually may be a bug, specifically about 

> it doesn't do a validation

**Comment by blakebarnett** [comment]
Yeah I suppose each type (cluster / ig / etc.) should do validation independently, though I can imagine there are quite a few things that aren't present in each individual type at creation (like via `create -f` that is available to the `update` action)

**Comment by kris-nova** [comment]
@blakebarnett I agree that we need to be doing better validation on a `create -f` or an `update`..

@justinsb is the validation you are talking about in the normal validation file? Or is that specific to `kops create cluster`?

**Comment by blakebarnett** [comment]
We definitely need this one now that enabling TLS on the etcd cluster can break things in a bad way.

**Comment by olemarkus** [comment]
`kops replace` now validates the cluster.
Master nodes _have_ to run etcd. Master IGs won't be added unless they are referenced in the etcd spec.

/close
