### ISSUE TITLE
kops delete cluster --name ${NAME} --yes error

### ISSUE THREAD

**Issue by Tejeswarreddy-3i** [kubernetes/kops#14741]
Cloud provider: AWS

![Screenshot from 2022-12-08 11-57-06](https://user-images.githubusercontent.com/109336274/206406929-294bbf85-a788-4ce6-9d15-363df06c4b75.png)
Error: error listing SQS queues: AccessDenied: Access to the resource https://sqs.ap-southeast-1.amazonaws.com/ is denied.
status code: 403, request id: eaa5402b-097e-52f6-8803-1c2153c63d70
$ kops delete cluster --name=**********.com --state=s3://k8s.********.local --yes
Error: error listing SQS queues: AccessDenied: Access to the resource https://sqs.ap-southeast-1.amazonaws.com/ is denied.
status code: 403, request id: cc47d2b1-b0f2-5702-ab7d-8eb65bd6afe1

Even after adding the AmazonSQSFullAccess and AmazonEventBridgeFullAccess permissions to the kops IAM group unable to fix the issue and the cluster is not getting deleted.

**Comment by olemarkus** [comment]
There are no permission boundaries or SCPs associated with your account or user?

Given that you have added the full access policy, but still cannot list SQS queues, you probably want to contact AWS support. This isn't an issue with kOps.

**Comment by Tejeswarreddy-3i** [comment]
There are no permission boundaries or SCPs associated with your account or user?

How to check and if there are, then how to remove them?

**Comment by Tejeswarreddy-3i** [comment]
Just now, when i tried the command kops delete cluster ********.com --state=s3://k8s.******.local --yes with the root user it worked. The cluster was successfully deleted.

Okay! Thank you so much for your support.
