### ISSUE TITLE
Unable to get an HA cluster in a single AZ

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1475]
kops version: 1.5.0-alpha3
k8s version: 1.5.2
channel: alpha

I tried 2 nodes in us-west-1a and 1 in us-west-1b, that's when I discovered that the two nodes in us-west-1a had mixed up DNS records.  The IPs were the same in the DNS records, so the etcd name didn't match on the 2nd one and it refused to start.

It appears that for multiple masters in an AZ, all the DNS records match the first master.

**Comment by blakebarnett** [comment]
I suspect it's related to this old/modified code: https://github.com/kubernetes/kops/blob/master/protokube/cmd/protokube/main.go#L110-L117

The 2nd/3rd masters in an AZ do not mount the voulmes for etcd, but reading through the rest of the code I don't see a smoking gun yet.  The aws_volumes describeInstances() method seems like it could be the culprit since it just returns the first array index, but I can't see how the instanceId would get mixed up.

**Comment by justinsb** [comment]
Will be partially addressed by #1536 (that _should_ fix it so it can run multiple masters in the same AZ, but does not address the UX around `kops create`)

**Comment by chrislovecnm** [comment]
@blakebarnett can we close?

**Comment by blakebarnett** [comment]
Will try to verify tonight

**Comment by kris-nova** [comment]
Similar to my note in https://github.com/kubernetes/kops/issues/732

But depending on what we find, do we need to take an action item to open a PR and document our findings?

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by blakebarnett** [comment]
Yes sorry, this works fine since 1.5.1 I believe
