### ISSUE TITLE
kops-controller manifest failed to apply

### ISSUE THREAD

**Issue by barber-k** [kubernetes/kops#14759]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Client version: 1.25.2 (git-v1.25.2)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
v1.21.14
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
# Apply kops update after version upgrade from 1.19
kops update cluster --yes
```

**5. What happened after the commands executed?**

Protokube is attempting to apply the manifest but the label has too many characters
```
protokube[24899]: The Service "kops-controller-internal" is invalid: metadata.labels: Invalid value: "kops-controller.internal.k8s-cluster-us-east-1-012345678912.k8s.local": must be no more than 63 characters
protokube[24899]: E1201 21:28:30.548198  190243 kubectlapplier.go:64] failed to replace manifest: error running kubectl: exit status 1
protokube[24899]: I1201 21:28:30.548240  190243 kubectlapplier.go:86] Running command: kubectl apply -f /tmp/channel3303059132/manifest.yaml --server-side --force-conflicts --field-manager=kops
protokube[24899]: I1201 21:28:31.079152  190243 kubectlapplier.go:89] error running kubectl apply -f /tmp/channel3303059132/manifest.yaml --server-side --force-conflicts --field-manager=kops
```

**6. What did you expect to happen?**

Expect for kops to truncate the cluster name to be a valid label under 63 characters. Alternatively if there was a cluster spec option available to specify an alternative name it could be used as a workaround for clusters with a name greater than 39 characters.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: k8s-cluster-us-east-1-012345678912.k8s.local
...
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

See relevant thread from another user https://kubernetes.slack.com/archives/C3QUFP0QM/p1665614648016699
This issue has caused the number of secrets from the kops-controller-token to increase significantly due to it not properly removing the secret after a failed attempt.

```
$ kubectl get secret | grep -c kops-controller-token
61099
```

Can you provide any assistance with finding a solution? There does not seem to be a supported method of renaming a cluster and we are having this issue across several different kops clusters.

Thank you

**Comment by hakman** [comment]
Thanks for reporting this @barber-k.
There may be some solutions, but I don't have any idea about a fix without code changes.

**Comment by olemarkus** [comment]
@justinsb the feature from https://github.com/kubernetes/kops/pull/12792 has caused a number of challenges. The host controller is very noisy and very active as it reacts to endpoint changes in the entire cluster, and the use of labels doesn't work with long (or even medium-sized) cluster name. This should have used annotations.

/kind office-hours
