### ISSUE TITLE
Calico Flatcar e2e fails SCTP tests

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#14765]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master branch

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.27.0-alpha.0.240+b1d98bd7b34da7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-calico-flatcar

/home/prow/go/src/k8s.io/kops/_rundir/3a1d6f2e-78c4-11ed-816c-b2f8c1d6e169/kops create cluster --name e2e-e2e-kops-aws-cni-calico-ipv6-flatcar.test-cncf-aws.k8s.io --cloud aws --kubernetes-version https://storage.googleapis.com/k8s-release-dev/ci/v1.27.0-alpha.0.240+b1d98bd7b34da7 --ssh-public-key /tmp/kops/e2e-e2e-kops-aws-cni-calico-ipv6-flatcar.test-cncf-aws.k8s.io/id_ed25519.pub --override cluster.spec.nodePortAccess=0.0.0.0/0 --image=075585003325/Flatcar-beta-3417.1.0-arm64-hvm --channel=alpha --networking=calico --container-runtime=containerd --ipv6 --topology=private --bastion --discovery-store=s3://k8s-kops-prow/discovery --admin-access 104.197.22.3/32 --master-count 1 --master-volume-size 48 --node-count 4 --node-volume-size 48 --zones us-west-1a --master-size c6g.large

**5. What happened after the commands executed?**

Two tests consistently fail:

[It] [sig-network] SCTP [LinuxOnly] should create a ClusterIP Service with SCTP ports
[It] [sig-network] SCTP [LinuxOnly] should create a Pod with SCTP HostPort

**6. What did you expect to happen?**

e2e tests to pass

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

See test logs

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

See test logs

**9. Anything else do we need to know?**

Cilium skips the SCTP HostPort test for k8s >= 1.22, I don't know how relevant that is.

The test log has a log line showing an issue with `/usr/sbin/iptables`:

```
    Dec 10 07:16:02.492: INFO: At 2022-12-10 07:11:04 +0000 UTC - event for hostport: {kubelet i-0987de21abfb3ad3a} FailedCreatePodSandBox: Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "0311caf234ea62aa01c981a2a1a1c7cee4c06460ec9d0c66849a678c8a666c38": plugin type="portmap" failed (add): unable to setup DNAT: running [/usr/sbin/iptables -t nat -C CNI-DN-dbe0b93e6875139b453a6 -p sctp --dport 5060 -s 100.115.58.167/32 -j CNI-HOSTPORT-SETMARK --wait]: exit status 2: iptables v1.8.7 (nf_tables): unknown option "--dport"
    Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by olemarkus** [comment]
Cilium didn't support SCTP until recently, and even now only to a certain extent: https://github.com/cilium/cilium/issues/20490

But IIRC, there are also issues with the SCTP tests themselves.

I see we are frequently hitting flatcar issues, so this distro may need some more love. Maybe we should have some presubmits for this one as well?

**Comment by johngmyers** [comment]
Those SCTP tests appear to no longer exist.
/close
