### ISSUE TITLE
AWS: Bastion server will not SSH into the cluster machines in a private subnet

### ISSUE THREAD

**Issue by gopinatht** [kubernetes/kops#1478]
I created a cluster (with `--ssh-public-key` setting) in a private subnet in the VPC with the bastion server in a public subnet. While I am able to SSH into the bastion server, I am not able to SSH into the kubernetes master or nodes. The PEM file (the public key for which is supplied with the `--ssh-public-key` option) is not available on the bastion server and no other auth file is available on the bastion server that will work in SSHing into master or nodes.

If I manually `scp` my PEM file into bastion machine and use that to SSH into the master and nodes, it works but I don't think that is a secure/recommended approach.

**Comment by chrislovecnm** [comment]
You need to use ssh-agent with you ssh key. From there you can use

ssh -A

That will forward your pem to the masters

**Comment by chrislovecnm** [comment]
https://sanctum.geek.nz/arabesque/tag/ssh-agent/ Good blog post

**Comment by gopinatht** [comment]
@chrislovecnm Thanks for the info! I will close this issue.

**Comment by neverfox** [comment]
I used -A but still no luck. FWIW, I can specified a pre-existing key pair using `sshKeyName` when creating the cluster.
