### ISSUE TITLE
Security: any pod can grant itself cluster-admin privileges.

### ISSUE THREAD

**Issue by abourget** [kubernetes/kops#1479]
In a kops cluster, any pod can `s3cmd --no-check-certificate get s3://your-state-store/your-cluster.k8s.your.domain.example.com/pki/private/ca/23456789.....key`, and sign itself a cluster admin keypair.

I find this to be a pretty high risk security issue. It defeats most of the security measures put in place, like RBAC and such, since escalation to cluster-admin is literally 2 well-known commands away.

Ref: https://github.com/kubernetes/kops/issues/363

**Comment by justinsb** [comment]
This is true - in general k8s is not safe for "untrusted" pods.  We should probably install kube2iam by default (or in a "recommended" configuration, particularly in conjunction with RBAC), particularly as k8s evolves to support fully locked down configurations.

**Comment by chrislovecnm** [comment]
This I think is a duplicate. Will let bot close
