### ISSUE TITLE
NodeLocal DNS and rolling update on DaemonSet produce downtime for DNS

### ISSUE THREAD

**Issue by dignajar** [kubernetes/kops#14812]
/kind support

When we do a Kubernetes upgrade via kOps we face a small downtime (5-10 seconds, per node) for the workloads deployed because the workloads can not resolve DNS.

We found that the issue is related to nodeLocalDNS, the small downtime per node occurs when there is a rolling update of the node-local-dns daemon-set; This happens when we do a `kops cluster update` because is when kOps applies the changes to the daemonset.

We are looking for a solution for this, one solution can be to move out node-local-dns from kOps and manage ourselves or create a PullRequest to kOps to manage the daemon-set update strategy and set it to OnDelete.

Any ideas?

**Comment by johngmyers** [comment]
What changes to the daemonset cause it to do a rolling update?

**Comment by olemarkus** [comment]
It's probably not unreasonable to tie the DS to the node lifecycle though.

**Comment by dignajar** [comment]
@johngmyers the docker image changed from `k8s.gcr.io/dns/k8s-dns-node-cache:1.17.4` to `k8s.gcr.io/dns/k8s-dns-node-cache:1.20.0`

**Comment by johngmyers** [comment]
`OnDelete` might be the right approach. We'd need to ensure that the old nodes are selected for rolling update.
