### ISSUE TITLE
DO e2e tests failing

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#14820]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master branch

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.27 alpha

**3. What cloud provider are you using?**

/area provider/digitalocean

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

https://testgrid.k8s.io/kops-misc#e2e-kops-do-calico-gossip
https://testgrid.k8s.io/kops-misc#e2e-kops-do-calico-fqdn

**5. What happened after the commands executed?**

Tests failing as new clusters fail to validate. csi-do-controller-0 fails with:

```
==== START logs for container csi-do-plugin of pod kube-system/csi-do-controller-0 ====
time="2022-12-16T13:16:09Z" level=info msg="removing socket" host_id=331518848 region=nyc1 socket=/var/lib/csi/sockets/pluginproxy/csi.sock version=v4.2.0
2022/12/16 13:16:19 failed to check volumes limits on startup: failed to get account information: Get "https://api.digitalocean.com/v2/account": dial tcp: lookup api.digitalocean.com on 100.64.0.10:53: read udp 100.125.100.130:49742->100.64.0.10:53: read: connection refused
```

**6. What did you expect to happen?**

Tests to pass

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Started failing December 16.

**Comment by hakman** [comment]
Working OK now, back to green.
