### ISSUE TITLE
v1alpha3: move away from the "kops.k8s.io/cluster" label

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#14928]
`InstanceGroup` and `SSHCredential` use the `kops.k8s.io/cluster` label to specify the cluster that the resource belongs to. This is read by `kops replace` and `kops create -f` to determine which cluster owns the resource.

This seems to me to be an abuse of a label. We're treating it sort-of like namespace, but we're shoehorning it into a magic label because ObjectMeta doesn't have a Cluster field. The value truly works like `namespace`, in that the tuple `<name,cluster>` is what has to be unique within the state store.

The v1alpha2 APIVersion of these resources is fixed, but we should consider a different strategy to use with v1alpha3 and later.

**Comment by johngmyers** [comment]
@justinsb commented in #14911 

> Agreed on the label; I don't really like it looking at it again a few years later.
> 
> I was thinking that by introducing the cluster name flag we can basically force "one invocation per cluster", and then we can work towards making the cluster-name argument mandatory / strongly encouraged. If you pass the cluster-name, the label can be omitted; if you specify the label it has to match. I think that'll nudge people towards not using the label.
>
> I think if these were real cluster objects we would have a spec.clusterRef on the InstanceGroup etc. That's a bit awkward for KubeSchedulerConfig (where we don't control the schema, and where it doesn't even have a metadata yet, though I think consensus is that was likely a mistake). But we would probably wrap "additional objects" anyway, because we don't want them to actually do anything on a "management cluster".
>
> That wrapper would probably look something like the "ClusterPackage" type that is currently only used for internal book-keeping inside kOps. but maybe with some objects embedded. If we did that, we could add spec.clusterRef to our objects.
> 
> cluster-api did spec.clusterName, which would also work as we do know the type: https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/machinedeployment_types.go#L68
> 
> I think though that for back-compatibility we can't drop the multi-cluster functionality enabled here. But how about if I don't recognize the label on additional objects, then we effectively force anyone using additional objects to explicitly pass the cluster name?

**Comment by johngmyers** [comment]
The issue with `spec.clusterName` is that the objects' names are truly namespaced by cluster. Objects with the same `name` field are separate objects when they are for different clusters and are expected to coexist in the same state store.

Unless we can add a `clusterName` field to `objectMeta`, I think we might have to use `namespace` for this.

**Comment by olemarkus** [comment]
Heh. https://github.com/kubernetes/kubernetes/pull/108717 and https://github.com/kubernetes-sigs/cluster-api/issues/6305
I am guessing kOps objects as K8s objects will never happen even if we generate the CRDs. But using namespace is as much of an abuse in my head (if not more) than labels.

If we drop the K8s state store logic, we can do our own ObjectMeta-type struct.
