### ISSUE TITLE
kops tried to change VPC CIDR when --network-cidr does not match

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/kops#1492]
I came across this bug trying to create a cluster inside in an existing VPC. It's unclear how `--network-cidr` relates to what `kops` will use it for. I expected `kops` to divide the CIDR block across all the `--zones` (3 in my case). However this is not the case. Kops requires the `--network-cidr` to equal the configure CIDR for the `--vpc` argument. This is strange UX for the following reasons:

1. AWS VPC CIDR blocks cannot be changed.
2. The `--network-cidr` option is required then `--vpc` is given
3. The CLI docs (unsure about online documentation) does not indicate how the value is used at all.
4. Kops tries to create subnets per AZ by dividing the CIDR block according, so passing a block outside the configured VPC CIDR block should work as expected.

I propose that `--network-cidr` is not be specified when `--cloud AWS` and `--vpc` is given. Kops should fetch the configured VPC CIDR and use that. The current model results in a confusing error message of "Cannot change CIDR". This is confusing because why would kops try to change the VPC's CIDR (because it cannot). My proposal may sort out this strange UX issue.

My second proposal is to fail with a more informative error message in this scenario. If the provided `--network-cidr` does not match the configure CIDR for `--vpc` and `--cloud aws`, then the user should see an error message along the lines of "provided CIDR does not match existing VPC's CIDR". 

I understand that `--vpc` and `--network-cidr` semantics vary per GCE & AWS. This is why I've proposed two solutions.

**Comment by Miyurz** [comment]
@ahawkins I think the first one would be a better solution. @kris-nova what do you say ?

**Comment by kris-nova** [comment]
### I think we should do both. 

We need to fix the logic here, or at least provide documentation on how we expect users to expect kops to behave in this situation.. 

Also while we are at it, we should always be improving error messages.. It looks like @justinsb has already noticed this issue.. I will touch base with him to see who plans on coding this.

Cheers - and thanks again @Miyurz and @ahawkins

**Comment by justinsb** [comment]
I really like these suggestions.  I'm unsure about redefining an existing flag, but I think the spirit of the issue is 100% correct.

**Comment by chrislovecnm** [comment]
Yah I would not encourage redefining an existing flag. Users could get a tad confused
