### ISSUE TITLE
kOps docs do not correctly report etcd-manager default backup retention period 

### ISSUE THREAD

**Issue by danports** [kubernetes/kops#14949]
/kind bug

[kOps docs](https://kops.sigs.k8s.io/operations/etcd_backup_restore_encryption/#taking-backups): "Hourly backups are kept for 1 week and daily backups are kept for 1 year, before being automatically removed."

[etcd-manager source](https://github.com/kubernetes-sigs/etcdadm/blob/acb9ff27d72c4dc658c38b013867af21099f3a7c/etcd-manager/pkg/backupcontroller/cleanup.go#L36): Defaults to retaining daily backups for 2 years. (Was 7 years until [July 2022](https://github.com/kubernetes-sigs/etcdadm/commit/addf757f53a347c6ab50729bc10ec24cad416241)!)

At a minimum, it would be nice to correct our docs, but @hakman and I were chatting about this and wondering if it would also make sense to shorten the default retention period, perhaps just for new clusters. If the purpose of the backups is to protect against accidental deletions and the like, a retention period of a month or two would be sufficient, I'd think. (Are there other purposes people retain backups longer for?)

**Comment by danports** [comment]
@hakman I think #14988 has closed this, right?

**Comment by justinsb** [comment]
Thank you for reporting @danports and thank you for fixing @hakman 
/close
