### ISSUE TITLE
Swap Support

### ISSUE THREAD

**Issue by ReillyBrogan** [kubernetes/kops#14950]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Kubernetes 1.22 introduced support for enabling swap on nodes. There are many usecases that benefit from this, so it would be great if Kops supported enabling this. 

Unfortunately while it appears that the `NodeSwap` feature gate and `failSwapOn: false` work as expected it appears that there is no way to modify the `MemorySwapConfiguration` in the kubelet config to change the default setting from `LimitedSwap` to `UnlimitedSwap`. This means that it is still not possible to actually use swap for Kubernetes workloads, only that it can be used for non-kubernetes processes running on the host.

**2. Feel free to provide a design supporting your feature request.**
Perhaps `kubelet` and `masterKubelet` could be extended with the following:
```
kubelet:
  memorySwapConfiguration:
    swapBehavior: "", "LimitedSwap", or "UnlimitedSwap"
```

Reference: 
- https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-MemorySwapConfiguration
- https://kubernetes.io/blog/2021/08/09/run-nodes-with-swap-alpha/

**Comment by olemarkus** [comment]
This sounds like a good feature to support and an easy thing to add. Happy to review a PR.

**Comment by tomesm** [comment]
Hi @olemarkus I am a returning newbie in Kops project (2 PRs 3 years ago :)) looking for a refresher task. This one looks promising. Before I submit the PR I just want to make sure my understanding is correct. The following is my idea:

I'd modify pkg/api/kops/componentconfig.go and pkg/apis/kops/v1alpha2 by adding the following struct:

```
// MemorySwapConfiguration is used to configure the swap behavior of a node
type MemorySwapConfiguration struct {
	// SwapBehavior is used to specify the swap behavior of the node.
	// It can be set to "", "LimitedSwap", or "UnlimitedSwap"
	SwapBehavior string `json:"swapBehavior,omitempty"`
}
```

And than simply add the option into _KubeletConfigSpec_ struct:

```
// KubeletConfigSpec defines the kubelet configuration
type KubeletConfigSpec struct {
	....
	// MemorySwapConfiguration is used to configure the swap behavior of a node
	MemorySwapConfiguration *MemorySwapConfiguration `json:"memorySwapConfiguration,omitempty"`
}
```

What do you think? Are my thoughts going in the right direction?

**Comment by olemarkus** [comment]
`LimitedSwap` probably doesn't make much sense for kOps since we always use cgroupv2.
You also need to pass this info into the kubelet component config that's built by nodeup.

**Comment by johngmyers** [comment]
You'll also need to add it to v1alpha3.

**Comment by johngmyers** [comment]
The field should be a custom type `type SwapBehavior string`. You should add API validation for it. You should document the default value in the field comment. There's no need to document the ability to leave it unset.

**Comment by ReillyBrogan** [comment]
> Why setting UnlimitedSwap as default option if memory swap is not supported at all?

I'm not sure where you're getting this but it's incorrect. Memory swap *is* supported with cgroups v2 however the only supported options are `""` where swap is not allowed for Kubernetes workloads but is otherwise unconstrained (IE system daemons and other services are allowed to use swap) or `UnlimitedSwap` which allows Kubernetes workloads to use swap.

**Comment by tomesm** [comment]
> I'm not sure where you're getting this but it's incorrect.

I deduced it from the reference [doc](https://kubernetes.io/blog/2021/08/09/run-nodes-with-swap-alpha/) :)
```
UnlimitedSwap: Kubernetes workloads can use as much swap memory as they request, up to the system limit.
```

vs

```
cgroups v2: Kubernetes workloads cannot use swap memory.
```

**Comment by ReillyBrogan** [comment]
> > I'm not sure where you're getting this but it's incorrect.
> 
> I deduced it from the reference [doc](https://kubernetes.io/blog/2021/08/09/run-nodes-with-swap-alpha/) :)
> ```
> cgroups v2: Kubernetes workloads cannot use swap memory.
> ```

That section is only for the behavior of `LimitedSwap`. There is no such restriction for `UnlimitedSwap`.

**Comment by tomesm** [comment]
@ReillyBrogan got it. One more thing, the default value should be "" or "UnlimitedSwap"?

**Comment by jabdoa2** [comment]
/remove-lifecycle stale

We would like this option as well. Makes a lot of sense to have it in kops.

**Comment by olemarkus** [comment]
As mentioned above, we're happy to review a PR.

**Comment by tomesm** [comment]
/assign

Omg, I totally shadowed this! Sorry. PR is on a way.

**Comment by jan-kantert** [comment]
@tomesm any update? can we help/test something?

**Comment by tomesm** [comment]
> @tomesm any update? can we help/test something?

I have opened the PR 2 months ago have been waiting for any feedback since than. Is there anything more I can do?

**Comment by jan-kantert** [comment]
@olemarkus are you still available to review the PR?
