### ISSUE TITLE
AL-2022 not supported

### ISSUE THREAD

**Issue by heybronson** [kubernetes/kops#14973]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops 1.25.3

```
0111 00:21:36.354989    2076 main.go:133] got error running nodeup (will retry in 30s): error determining OS distribution: unsupported distro: amzn-2022
I0111 00:22:06.355264    2076 identify.go:86] Contents of /etc/os-release:
NAME="Amazon Linux"
VERSION="2022"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2022"
PLATFORM_ID="platform:al2022"
PRETTY_NAME="Amazon Linux 2022"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2022"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2022"
SUPPORT_END="2027-11-01"
```

https://github.com/kubernetes/kops/blob/master/util/pkg/distributions/distributions.go#L39 AL2022 not supported here

**Comment by olemarkus** [comment]
/remove-kind bug
/kind feature

As far as I know we never added support for amzn-2022. Not sure there is much interest in it either.
I suggest adding the info required for a feature request to this issue.
