### ISSUE TITLE
Add a documentation about the format of the kops configuration file

### ISSUE THREAD

**Issue by remyleone** [kubernetes/kops#15027]
/kind feature

I would like to have a documentation about all the variable that I can put inside a kops configuration file. As there is a lot of potential variables https://github.com/kubernetes/kops/search?q=os.Getenv

**2. Feel free to provide a design supporting your feature request.**

One way that could be done is to define all the environment variable into a single place and then use a data structure to document it and maintain it

**Comment by mausch** [comment]
There are also env vars implicitly used by kops e.g. `KUBECONFIG` and the usual AWS ones, which seem to overlap with the `S3_*` env vars [documented here](https://kops.sigs.k8s.io/state/#custom-s3-compatible-store), causing confusion.
