### ISSUE TITLE
Backups for etcd (AWS)

### ISSUE THREAD

**Issue by foxylion** [kubernetes/kops#1506]
Hi,
I've currently set up a non HA Kubernetes master and I want to do regularly backups of etcd to be able to restore the cluster in case of a volume failure at AWS.

This seems currently not possible. There should be either an integrated backup/restore solution. Or is should be able to restore a etcd volume snapshot and change the volume ids inside of Kubernetes.

Related issue at kubernetes: kubernetes/kubernetes#40027

**Comment by chrislovecnm** [comment]
I think we have another open issue like this one.

**Comment by foxylion** [comment]
@chrislovecnm I couldn't find any issue and @justinsb advised me to create issues.
Would you mind linking the issue? :)

**Comment by foxylion** [comment]
@justinsb said it would be a good idea to add some documentation about backups of etcd in the current state. I added a document describing the backup/restore procedure.

**Comment by justinsb** [comment]
Thanks for docs.  Moving to 1.5.1 to revisit automation / etcd level backups.  CoreOS have also promised something, so we'll see if that has materialized when we circle back to it.

**Comment by foxylion** [comment]
We tested the documented recovery process (etcd volume snapshots) and it works really good.
The cluster recovers and restores the previous state (e.g. removing running deployments when the were not created previously).

So I'm not sure if there is really an urgent need to automate that.

**Comment by mfornasa** [comment]
Is a disk snapshot a safe backup?
Etcd documentation does not mention a snapshot method, it provides instead a CLI utility.

**Comment by foxylion** [comment]
@mfornasa As far as I can see now this is not 100% safe. The snapshot could be taken in a moment of inconsistent disk state (not everything is immediately flushed to disk).
For us it works for the moment, our cluster has a low load so I think hitting a moment with consistent data is not that unlikely (we tried to restore snapshots, worked good).

Some more details about backups are in the related issue: kubernetes/kubernetes#40027

**Comment by mfornasa** [comment]
@foxylion thanks. In fact, an etcd maintainer pointed out in that ticket that taking EBS snapshots **is not safe** (https://github.com/kubernetes/kubernetes/issues/40027#issuecomment-283512123).

**Comment by mfornasa** [comment]
@foxylion Correct me if I'm wrong, but it seems that the current backup documentation is severely misleading, as the reader is going to assume that the procedure is safe, while etcd maintainers do not deem it safe. At the very minimum this should be mentioned in the doc.

**Comment by foxylion** [comment]
@mfornasa Yes you're right this should be mentioned.

**Comment by chrislovecnm** [comment]
Three choices

1. Remove - do not like 
2. Redo so it is good documentation 
3. Put in notes that there are limitations

You guys understand this better than me... don't wait on us ;) What should we do??

**Comment by philipbjorge** [comment]
I would love it if someone could figure out option 2 for our team :).

**Comment by chrislovecnm** [comment]
This is a duplicate.  Closing

https://github.com/kubernetes/kops/issues/1896
