### ISSUE TITLE
IPv6 e2e tests failing

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#15075]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Master branch

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.27 branch

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

https://testgrid.k8s.io/kops-ipv6#kops-aws-cni-calico-ipv6

**5. What happened after the commands executed?**

Worker nodes don't provision.

**6. What did you expect to happen?**

Working cluster.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Appears to be an issue with AWS. Worker instances are stuck in Provisioning state.

**Comment by johngmyers** [comment]
I've opened a case with AWS Support.

**Comment by johngmyers** [comment]
A test run in https://testgrid.k8s.io/kops-ipv6#kops-aws-cni-calico-ipv6 was able to provision a cluster. We'll have to see if things are reliably working again.

**Comment by hakman** [comment]
Look OK now.
