### ISSUE TITLE
kops GPU support not working due to broken nvidia apt repo

### ISSUE THREAD

**Issue by darintay** [kubernetes/kops#15094]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Client version: 1.25.2 (git-v1.25.2)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Created a cluster with default image (ubuntu 20.04) using the kops gpu support (https://github.com/kubernetes/kops/blob/master/docs/gpu.md) and tried to bring up a node

**5. What happened after the commands executed?**
Node never joined cluster
It is stuck in nodeup trying to install nvidia-container-runtime and failing, due to https://github.com/NVIDIA/libnvidia-container/issues/202

**6. What did you expect to happen?**
Node joins cluster

**9. Anything else do we need to know?**

I can fix the problem manually by ssh'ing into the node and editing /etc/apt/sources.list.d/nvidia-container-runtime.list to point at the 18.04 link, which still works.  I'm not sure there's a way I can do that automatically with cloud-init or hooks - I tried a bit but it seems like the nodeup process is getting stuck on the package install before anything I can script in my cluster config.

Reverting to an 18.04 base image also works, as expected.

I'm not sure there's anything to be done on the kops side without nvidia fixing their repo, but thought I'd file for visibility and in case there are workarounds I haven't thought of.

**Comment by elezar** [comment]
@darintay do you have a link to the `Dockerfile` used to build the image being used?

The non-`ubuntu18.04` repo should not be used directly if possible and I would like to validate how the repo lists are set up in the image.

**Comment by hakman** [comment]
@elezar Is this what you were looking for?
https://github.com/kubernetes/kops/blob/741ca8faa24e4e1722237b81872d772733db64f4/nodeup/pkg/model/nvidia.go#L33-L57

**Comment by elezar** [comment]
@hakman I have created https://github.com/kubernetes/kops/pull/15096 to fix the URLs and the packages that install the components of the NVIDIA Container Toolkit.

**Comment by hakman** [comment]
Fixed in https://github.com/kubernetes/kops/pull/15096.
