### ISSUE TITLE
Feature Request:  Multiple KOPS_STATE_STORE via CSV

### ISSUE THREAD

**Issue by etotheipi** [kubernetes/kops#1509]
I currently have two kops-created clusters, which have different users and security sensitivity.  So I used a different bucket for each.  However `kops` requires me to set the `$KOPS_STATE_STORE` variable to just one value, requiring me to re-export that env if I want to switch clusters.   For instance.

```
$ kops get cluster
NAME			CLOUD	ZONES
clusterA.domain.com	aws	us-east-1d
$ export KOPS_STATE_STORE="s3://clusterB-state-store"
$ kops get cluster
NAME			CLOUD	ZONES
clusterB.domain.com	aws	us-east-1d
```

It would be nice to be able to use comma-separated list of s3 buckets.  The desired behavior would look like:

```
$ export KOPS_STATE_STORE="s3://clusterA-state-store,s3://clusterB-state-store"
$ kops get cluster
NAME			CLOUD	ZONES
clusterA.domain.com	aws	us-east-1d
clusterB.domain.com	aws	us-east-1d
```

**Comment by yissachar** [comment]
You can also pass state to kops through the `--state` flag:

`kops get cluster --state s3://clusterA-state-store`
`kops get cluster --state s3://clusterB-state-store`

This is more convenient than switching out the env variable each time, if you are interacting with multiple clusters.

I can see the value in merging state from multiple buckets. We would have to handle the case where there are identically named clusters in the different buckets.

**Comment by etotheipi** [comment]
Thanks, I didn't know about the `--state` flag.  

As for identical cluster names across buckets, any listings could include a bucket name column to distinguish them.  If another command is used that refers to a duplicated name, you can return an error message indicating that they must provide a `--state` flag to continue.
