### ISSUE TITLE
Protokube continues to run after bootstrap is complete

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1510]
I discovered this while trying to debug #1475, If you attempt to make changes, especially to the etcd cluster, protokube will happily undo what you change, including fixes to make the cluster work properly. 

I looked through the code and don't see anything that requires that protokube keep running after bootstrap.  And @justinsb had this to say on slack about it:

> I think I had a thought also that if we wanted to do dynamic reconfiguration, either protokube or nodeup or both would need to keep running
> But (1) we don't do dynamic reconfiguration to keep our surface area smaller
> and (2) this could also be done with a scheduled systemd job

**Comment by chrislovecnm** [comment]
@blakebarnett yah it is as designed :)  Would you recommend a run once? Protokube also ensures that kubelet is running, but I think we can do this via systemd unit.

**Comment by blakebarnett** [comment]
Yeah I think systemd is the appropriate mechanism to keep kubelet running.  I couldn't see any other reason for protokube to keep running and it was quite surprising to find it undoing my changes.

**Comment by chrislovecnm** [comment]
Channels and updates are also provided by protokube. Thoughts?

**Comment by chrislovecnm** [comment]
Not entirely correct. You can run a kops update, for example, and it will update kube-dns :)  `channels` will see the change in the addons, and it will update it.

**Comment by blakebarnett** [comment]
right... I didn't say that very clearly, but I think it's pretty unclear what that flow is from a user perspective, I'm guessing there hasn't been a lot of use of this feature purely because it requires a kops release to make it stick right?

**Comment by blakebarnett** [comment]
I think this might be addressed with the new kops-server changes?  Or maybe the decision to keep protokube as-is.

**Comment by olemarkus** [comment]
Most of this issue isn't relevant anymore. Kubelet is kept alive by systemd, and we want to let channels do updates from the control plane. 

/close
