### ISSUE TITLE
multiple asset containerProxys

### ISSUE THREAD

**Issue by benedikt-bartscher** [kubernetes/kops#15103]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
To overcome dockerhub rate limits, speed up pull times and increase availability we just started configuring registry mirros as a pull-trough cache. We setup clusterspec.containerd.registryMirrors for 5 different registries.
However we noticed that kops assets won't get pulled trough the containerd registry mirrors. We then discovered clusterspec.assets.containerProxy but you can only define one containerProxy, not multiple for multiple registrys.

**2. Feel free to provide a design supporting your feature request.**
Either just pull kops container assets trough the registrymirrors defined for containerd or allow configuring multiple asset containerProxys.

**Comment by hakman** [comment]
Could you try https://kops.sigs.k8s.io/cluster_spec/#containerregistry and see if that helps?

**Comment by benedikt-bartscher** [comment]
Hi @hakman, how would that help defining multiple servers?

**Comment by hakman** [comment]
There is no way to define multiple servers. It just normalises the paths to have mirror to a single ECR.

**Comment by olemarkus** [comment]
Which container assets aren't pulled through containerd-configured mirrors? Aren't they pulled as any other container through CRI?
