### ISSUE TITLE
[Action Required] Update references from k8s.gcr.io to registry.k8s.io

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/kops#15118]
With the [change to defaulting](https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/) to registry.k8s.io as our image registry and the [planned freeze in April](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/), projects within the Kubernetes orgs should update their image references to point to the new address.

**NOTE:** We can ignore references to staging-k8s.gcr.io, but any other references to k8s.gcr.io should be updated to registry.k8s.io

[k8s.gcr.io search results](https://cs.k8s.io/?q=k8s.gcr.io&i=nope&files=&excludeFiles=vendor%2F&repos=kubernetes/kops) 

ref: [[Umbrella Issue] Migrate K8s projects from k8s.gcr.io -> registry.k8s.io](https://github.com/kubernetes/k8s.io/issues/4738)

/kind cleanup
/sig cluster-lifecycle
/priority important-soon

**Comment by nbs-jeanpierrefouche** [comment]
What do we do about legacy deployments of kops (we are using 1.19.3) --> there does not appear to be a way to switch the registries used?  Many Thanks.

**Comment by Dennissaminathan** [comment]
We use version 1.21 . I tried using containerProxy to point to our private repo where i pushed all the images required but the problem is when i use like this ,Registry for addons also updated with private repo which was not required to be changed.

**Comment by alexandresavicki** [comment]
Hi folks, can we cherry pick to 1.24?
