### ISSUE TITLE
Change cluster master from non-HA to HA

### ISSUE THREAD

**Issue by tanner-bruce** [kubernetes/kops#1512]
I'm interested in modifying my cluster which has a non-HA master to have masters in multiple AZs

**Comment by chrislovecnm** [comment]
There should be docs.  Or a PR in for docs.  Please let me know if you cannot find them and I will attempt to dig it up

**Comment by ulysseses** [comment]
> Currently it is not possible to change the etcd cluster size (i.e. we cannot change an HA cluster to be non-HA, or a non-HA cluster to be HA.)

Just to be clear, can we still add/remove etcd members via [runtime configuration](https://github.com/coreos/etcd/blob/master/Documentation/v2/runtime-configuration.md) under HA mode?

**Comment by chrislovecnm** [comment]
Not sure what you are asking

**Comment by yissachar** [comment]
Closing this out in favour of https://github.com/kubernetes/kops/issues/1566.
