### ISSUE TITLE
Master instance doesn't survive reboot

### ISSUE THREAD

**Issue by snarlysodboxer** [kubernetes/kops#1513]
Reproduce:
* Create a single master cluster with kops, wait for everything to be working
* SSH into the master
* Run `sudo docker ps | grep etcd` = results
* Run `sudo reboot`

Observed problem:
* SSH back into master, give a few minutes to be sure everything had a chance to start
* Run `sudo docker ps | grep etcd` = no results
* Last message in `/var/log/kube-etcd.log` is `Terminated`

Terminate the instance and let the ASG recreate it and everything's fine again.

I had trouble finding any error messages as to why this happens. I'll update if/when I find more time to investigate.

This is kops v1.4.4, k8s v1.5x, and I tried almost all the AMI's created by @justinsb

**Comment by justinsb** [comment]
Found the issue: https://github.com/kubernetes/kubernetes/issues/40123

**Comment by justinsb** [comment]
I actually think this might be fixed (accidentally) in kops 1.5, because protokube starts the kubelet in 1.5.

**Comment by justinsb** [comment]
This does appear to accidentally be fixed in 1.5 alpha4

**Comment by snarlysodboxer** [comment]
@justinsb Fixed for me in kops 1.5.0-alpha3. Thanks!

**Comment by kris-nova** [comment]
Can we close? Do we need a test here? @justinsb I noticed you added a release blocker label.. are we intentionally keeping this open?

**Comment by chrislovecnm** [comment]
I am closing since it is reported as fixed by openner ;)
