### ISSUE TITLE
AWS: Unable to use weave network with pre-existing private subnet

### ISSUE THREAD

**Issue by gopinatht** [kubernetes/kops#1514]
I am trying to get weave networking to work with my kops based cluster, and I keep getting this error: `Network 10.32.0.0/12 overlaps with existing route 10.44.76.0/25 on host`
  
I followed the instructions here to install weave: https://github.com/kubernetes/kops/blob/master/docs/networking.md

My command looks like this: `${KOPSPATH}/kops create --v=8 cluster --channel "alpha" --topology private --image ami-6d1c2007 --vpc vpc-xxxxxxxx --network-cidr "10.44.76.0/23" --networking cni --bastion --ssh-public-key "~/.ssh/MyKey.pub" --zones us-east-1e ${EXPNAME}`.

I then edit it to use my pre-existing private and public subnets. I can provide the configs if necessary.

From the slack discussion, it looks like the weave manifest assumes it will always use `10.32.0.0/12`. I could be wrong. 

@justinsb suggested I log a bug so here it is.

**Comment by justinsb** [comment]
It seems that tweaking the weave configuration is not trivial for us to do.  As a workaround, can I suggest trying `networking: kopeio: {}` instead of `networking: weave: {}` ?  (or passing `--networking kopeio-vxlan` to kops create)

**Comment by gopinatht** [comment]
@justinsb I am using calico and that seems to be working for us. So I am happy with it for now. Is kopeio similar to weave?

**Comment by justinsb** [comment]
Yes, they're all pretty similar, though I am most familiar with kopeio-networking as I wrote it!

I'm going to move reconfiguration of weave to 1.5.1, and I think we'll recommend people that need to run in the weave CIDRs to use calico / kopeio-networking until this is resolved.

**Comment by gopinatht** [comment]
@justinsb Sure, I am OK with that.

**Comment by chrislovecnm** [comment]
Closing as we have the fix in
