### ISSUE TITLE
configure EC2 instance storage

### ISSUE THREAD

**Issue by daniejstriata** [kubernetes/kops#15174]
I've setup a new cluster using kops 1.25.3 and found that the instances have a lot of unallocated storage. Unless this is by design? What are the 2 x 20G drives for? Why is root 64G? What would happen if my install requires more storage? How can I configure kops to allocate more drives or bigger volumes?

```
# lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0          7:0    0 55.6M  1 loop /snap/core18/2667
loop1          7:1    0 63.3M  1 loop /snap/core20/1778
loop2          7:2    0 24.4M  1 loop /snap/amazon-ssm-agent/6312
loop3          7:3    0 49.6M  1 loop /snap/snapd/17883
loop4          7:4    0 91.9M  1 loop /snap/lxd/24061
nvme0n1      259:0    0   64G  0 disk
├─nvme0n1p1  259:1    0 63.9G  0 part /
├─nvme0n1p14 259:2    0    4M  0 part
└─nvme0n1p15 259:3    0  106M  0 part /boot/efi
nvme1n1      259:4    0   20G  0 disk /mnt/master-vol-07e25427af5fb1390
nvme2n1      259:5    0   20G  0 disk /mnt/master-vol-0f0dff8185a740066
```

**Comment by zetaab** [comment]
kops deploys 2 etcd clusters by default. Those volumes are for etcd cluster members. One for etcd-events and one for etcd-main. You can change the volume size in kops config for etcd clusters. 

64G root volume is perhaps coming from AWS(?) instance type, which kops cannot change. Use different flavor type if you want smaller disk.
