### ISSUE TITLE
Creating kops cluster with --name fails with the error "Cannot specify cluster via --name and positional argument"

### ISSUE THREAD

**Issue by Miyurz** [kubernetes/kops#1518]
As I try to create the k8s cluster with kops, passin `--name=<cluster_name>` as well as just the <cluster name> at the end as @kris-nova suggested in https://github.com/kubernetes/kops/issues/1222 doesn't work well and fails with the error _Cannot specify cluster via —name and positional argument_

Probable work around was to add an "=" to all the assigned values like zones, dns etc.

To be precise, kops doesn't like the below in my ansible playbook

```
command: >
        kops create cluster
          --yes
          --bastion
          --topology private
          --networking weave
          --associate-public-ip false
          --vpc {{ item.stack_outputs.K8sVpc }}
          --network-cidr {{ item.stack_outputs.K8sCidrBlock }}
          --node-count 3
          --cloud aws 
          --zones {{ item.item.zones }}
          --ssh-public-key ~/my_key.pub
          --dns private
          --dns-zone production.saltside.net
          --name='{{ item.item.geo}}.k8s.environment.myorg.org'
```

but add an "=" to all the assigned values and it works like a charm. The former one should work with positional arguments and not necessarily keyword ones.

This was observed in kops 1.5 alpha2

**Comment by kris-nova** [comment]
Name is a special flag.. I would suggest doing this

```
kops create cluster
          --yes
          --bastion
          --topology private
          --networking weave
          --associate-public-ip false
          --vpc {{ item.stack_outputs.K8sVpc }}
          --network-cidr {{ item.stack_outputs.K8sCidrBlock }}
          --node-count 3
          --cloud aws 
          --zones {{ item.item.zones }}
          --ssh-public-key ~/my_key.pub
          --dns private
          --dns-zone production.saltside.net
          '{{ item.item.geo}}.k8s.environment.myorg.org'
```

**Comment by kamilhristov** [comment]
This is caused by ` --associate-public-ip false` flag.

Cobra takes "false" as an argument which is being assigned as Cluster Name. The boolean variables are supposed to be parsed when their value has to be set to true, like `--bastion`.

Same happens with kubectl:

```
kubectl --match-server-version false
Error: unknown command "false" for "kubectl"
Run 'kubectl --help' for usage.
```

**Comment by justinsb** [comment]
It's an easy mistake to make - I've made it a few times myself!  I am proppsing expanding the error message in #1693.

**Comment by justinsb** [comment]
Error message looks like this now:

```
kops create cluster --bastion false simple.example.com --zones us-east-1c

Found multiple arguments which look like a cluster name
        "false" (as argument)
        "simple.example.com" (as argument)

This often happens if you specify an argument to a boolean flag without using =
For example: use `--bastion=true` or `--bastion`, not `--bastion true`


expected a single <clustername> to be passed as an argument
```

**Comment by Miyurz** [comment]
Many thanks @justinsb

**Comment by regev-agabi** [comment]
Hey have a basically the same problem can't understand how to fix it tried for few hours 
@Miyurz 
@justinsb 
kops version:git-9992b4055
kubectl version GitVersion:"v1.18.0"
kubernetes: version: 1.18.0

ansible-parameters:
- name: Configure the cluster 
  shell: >
    kops --v=3 create cluster
    --cloud={{ vendor }}
    --image={{ base_image }}
    --zones={{ aws_zones }}
    --node-count={{ node_count }}
    --node-size={{ node_size }}
    --node-volume-size={{ node_volume_size }}
    --master-size={{ master_size }}
    --master-zones={{ master_zones }}
    --master-volume-size={{ master_volume_size }}
    --dns-zone={{ dns_zone }}
    --dns=private
    --ssh-public-key={{ ssh_public_key }}
    --networking={{ kubernetes_networking }}
    --subnets={{ subnet_id }}
    --network-cidr={{ network_cidr }}
    --topology={{ topology }}
    --zones={{ aws_zones }}
    --vpc={{ vpc_id }}
    --state={{ state_store }}
    --authorization=rbac
    --encrypt-etcd-storage
    --disable-subnet-tags
    --kubernetes-version={{ kubernetes_version }}
    --name={{ cluster_name }}

command output: 
`fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "kops --v=3 create cluster --cloud=aws --image={'architecture': 'x86_64', 'creation_date': '2020-05-11T18:44:13.000Z', 'image_id': 'ami-01d154624d9b5b274', 'image_location': '136693071363/debian-10-amd64-20200511-260', 'image_type': 'machine', 'public': True, 'owner_id': '136693071363', 'platform_details': 'Linux/UNIX', 'usage_operation': 'RunInstances', 'state': 'available', 'block_device_mappings': [{'device_name': '/dev/xvda', 'ebs': {'delete_on_termination': True, 'snapshot_id': 'snap-0ca8c03b14e6c6b61', 'volume_size': 8, 'volume_type': 'gp2', 'encrypted': False}}], 'description': 'Debian 10 (20200511-260)', 'ena_support': True, 'hypervisor': 'xen', 'name': 'debian-10-amd64-20200511-260', 'root_device_name': '/dev/xvda', 'root_device_type': 'ebs', 'sriov_net_support': 'simple', 'virtualization_type': 'hvm', 'tags': {}} --zones=eu-central-1a --node-count=2 --node-size=t2.medium --node-volume-size=50 --master-size=t2.medium --master-zones=eu-central-1a --master-volume-size=50 --dns-zone=Z01153191Q4MG8188W19 --dns=private --ssh-public-key=files/k8s_KP.pem --networking=kubenet --subnets=subnet-0a3830037d96f7102 --network-cidr=172.30.0.0/16 --topology=public --zones=eu-central-1a --vpc=vpc-03e5fa34b8bd3566c --state=s3://eu-central-1.cyberark-kubernetes --authorization=rbac --encrypt-etcd-storage --disable-subnet-tags --kubernetes-version=1.18.0 --name=test.kops.com\n",
    "delta": "0:00:00.048059",
    "end": "2020-05-27 13:01:41.552170",
    "invocation": {
        "module_args": {
            "_raw_params": "kops --v=3 create cluster --cloud=aws --image={'architecture': 'x86_64', 'creation_date': '2020-05-11T18:44:13.000Z', 'image_id': 'ami-01d154624d9b5b274', 'image_location': '136693071363/debian-10-amd64-20200511-260', 'image_type': 'machine', 'public': True, 'owner_id': '136693071363', 'platform_details': 'Linux/UNIX', 'usage_operation': 'RunInstances', 'state': 'available', 'block_device_mappings': [{'device_name': '/dev/xvda', 'ebs': {'delete_on_termination': True, 'snapshot_id': 'snap-0ca8c03b14e6c6b61', 'volume_size': 8, 'volume_type': 'gp2', 'encrypted': False}}], 'description': 'Debian 10 (20200511-260)', 'ena_support': True, 'hypervisor': 'xen', 'name': 'debian-10-amd64-20200511-260', 'root_device_name': '/dev/xvda', 'root_device_type': 'ebs', 'sriov_net_support': 'simple', 'virtualization_type': 'hvm', 'tags': {}} --zones=eu-central-1a --node-count=2 --node-size=t2.medium --node-volume-size=50 --master-size=t2.medium --master-zones=eu-central-1a --master-volume-size=50 --dns-zone=Z01153191Q4MG8188W19 --dns=private --ssh-public-key=files/k8s_KP.pem --networking=kubenet --subnets=subnet-0a3830037d96f7102 --network-cidr=172.30.0.0/16 --topology=public --zones=eu-central-1a --vpc=vpc-03e5fa34b8bd3566c --state=s3://eu-central-1.cyberark-kubernetes --authorization=rbac --encrypt-etcd-storage --disable-subnet-tags --kubernetes-version=1.18.0 --name=test.kops.com\n",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2020-05-27 13:01:41.504111",
    "stderr": "\nexpected a single <clustername> to be passed as an argument",
    "stderr_lines": [
        "",
        "expected a single <clustername> to be passed as an argument"
    ],
    "stdout": "\nFound multiple arguments which look like a cluster name\n\t\"test.kops.com\" (via flag)\n\t\"x86_64,\" (as argument)\n\t\"creation_date:\" (as argument)\n\t\"2020-05-11T18:44:13.000Z,\" (as argument)\n\t\"image_id:\" (as argument)\n\t\"ami-01d154624d9b5b274,\" (as argument)\n\t\"image_location:\" (as argument)\n\t\"136693071363/debian-10-amd64-20200511-260,\" (as argument)\n\t\"image_type:\" (as argument)\n\t\"machine,\" (as argument)\n\t\"public:\" (as argument)\n\t\"True,\" (as argument)\n\t\"owner_id:\" (as argument)\n\t\"136693071363,\" (as argument)\n\t\"platform_details:\" (as argument)\n\t\"Linux/UNIX,\" (as argument)\n\t\"usage_operation:\" (as argument)\n\t\"RunInstances,\" (as argument)\n\t\"state:\" (as argument)\n\t\"available,\" (as argument)\n\t\"block_device_mappings:\" (as argument)\n\t\"[{device_name:\" (as argument)\n\t\"/dev/xvda,\" (as argument)\n\t\"ebs:\" (as argument)\n\t\"{delete_on_termination:\" (as argument)\n\t\"True,\" (as argument)\n\t\"snapshot_id:\" (as argument)\n\t\"snap-0ca8c03b14e6c6b61,\" (as argument)\n\t\"volume_size:\" (as argument)\n\t\"8,\" (as argument)\n\t\"volume_type:\" (as argument)\n\t\"gp2,\" (as argument)\n\t\"encrypted:\" (as argument)\n\t\"False}}],\" (as argument)\n\t\"description:\" (as argument)\n\t\"Debian 10 (20200511-260),\" (as argument)\n\t\"ena_support:\" (as argument)\n\t\"True,\" (as argument)\n\t\"hypervisor:\" (as argument)\n\t\"xen,\" (as argument)\n\t\"name:\" (as argument)\n\t\"debian-10-amd64-20200511-260,\" (as argument)\n\t\"root_device_name:\" (as argument)\n\t\"/dev/xvda,\" (as argument)\n\t\"root_device_type:\" (as argument)\n\t\"ebs,\" (as argument)\n\t\"sriov_net_support:\" (as argument)\n\t\"simple,\" (as argument)\n\t\"virtualization_type:\" (as argument)\n\t\"hvm,\" (as argument)\n\t\"tags:\" (as argument)\n\t\"{}}\" (as argument)\n\nThis often happens if you specify an argument to a boolean flag without using =\nFor example: use `--bastion=true` or `--bastion`, not `--bastion true`",
    "stdout_lines": [
        "",
        "Found multiple arguments which look like a cluster name",
        "\t\"test.kops.com\" (via flag)",
        "\t\"x86_64,\" (as argument)",
        "\t\"creation_date:\" (as argument)",
        "\t\"2020-05-11T18:44:13.000Z,\" (as argument)",
        "\t\"image_id:\" (as argument)",
        "\t\"ami-01d154624d9b5b274,\" (as argument)",
        "\t\"image_location:\" (as argument)",
        "\t\"136693071363/debian-10-amd64-20200511-260,\" (as argument)",
        "\t\"image_type:\" (as argument)",
        "\t\"machine,\" (as argument)",
        "\t\"public:\" (as argument)",
        "\t\"True,\" (as argument)",
        "\t\"owner_id:\" (as argument)",
        "\t\"136693071363,\" (as argument)",
        "\t\"platform_details:\" (as argument)",
        "\t\"Linux/UNIX,\" (as argument)",
        "\t\"usage_operation:\" (as argument)",
        "\t\"RunInstances,\" (as argument)",
        "\t\"state:\" (as argument)",
        "\t\"available,\" (as argument)",
        "\t\"block_device_mappings:\" (as argument)",
        "\t\"[{device_name:\" (as argument)",
        "\t\"/dev/xvda,\" (as argument)",
        "\t\"ebs:\" (as argument)",
        "\t\"{delete_on_termination:\" (as argument)",
        "\t\"True,\" (as argument)",
        "\t\"snapshot_id:\" (as argument)",
        "\t\"snap-0ca8c03b14e6c6b61,\" (as argument)",
        "\t\"volume_size:\" (as argument)",
        "\t\"8,\" (as argument)",
        "\t\"volume_type:\" (as argument)",
        "\t\"gp2,\" (as argument)",
        "\t\"encrypted:\" (as argument)",
        "\t\"False}}],\" (as argument)",
        "\t\"description:\" (as argument)",
        "\t\"Debian 10 (20200511-260),\" (as argument)",
        "\t\"ena_support:\" (as argument)",
        "\t\"True,\" (as argument)",
        "\t\"hypervisor:\" (as argument)",
        "\t\"xen,\" (as argument)",
        "\t\"name:\" (as argument)",
        "\t\"debian-10-amd64-20200511-260,\" (as argument)",
        "\t\"root_device_name:\" (as argument)",
        "\t\"/dev/xvda,\" (as argument)",
        "\t\"root_device_type:\" (as argument)",
        "\t\"ebs,\" (as argument)",
        "\t\"sriov_net_support:\" (as argument)",
        "\t\"simple,\" (as argument)",
        "\t\"virtualization_type:\" (as argument)",
        "\t\"hvm,\" (as argument)",
        "\t\"tags:\" (as argument)",
        "\t\"{}}\" (as argument)",
        "",
        "This often happens if you specify an argument to a boolean flag without using =",
        "For example: use `--bastion=true` or `--bastion`, not `--bastion true`"
    ]
}`

**Comment by olemarkus** [comment]
This tends to happen if you have a space too many somewhere. Be on the lookout for that.
