### ISSUE TITLE
Apply after `delete ig nodes` gives error

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#152]
Once we have the new 'apply' for cluster changes, we should verify that applying after deleting all nodes no longer gives an error; right now it does if you delete the primary nodeset.

**Comment by justinsb** [comment]
It now gives a sensible error message: `must configure at least one Node InstanceGroup`

I think that is reasonable for now; we should support sizing to size 0, and we can always reopen if need be.  But a cluster with no node instance groups is otherwise quite likely to be a mistake.

**Comment by jedateach** [comment]
Does zero size Node InstanceGroup work now?
