### ISSUE TITLE
[QUESTION] Issue with kops 1.25

### ISSUE THREAD

**Issue by kannamr** [kubernetes/kops#15205]
Is there a way still I can use aws hostname instead of instance id when upgrading to kops 1.25.3 from 1.24.4 & kubernetes from 1.23.8 to 1.25.3

**Comment by hakman** [comment]
Please try using kOps 1.25.4.

**Comment by MadudaP** [comment]
Is this naming convention change mentioned somewhere in the kOps release notes ? I haven't seen it anywhere.
