### ISSUE TITLE
Unable to create cluster using kops 1.25.3

### ISSUE THREAD

**Issue by ravindrai** [kubernetes/kops#15211]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.25.3
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.***2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create cluster --name=indurik8s.xyz --state=s3://indurik8s.xyz --zones=ap-south-1b --node-count=2 --node-size=t2.micro --master-size=t2.small --node-volume-size 10 --master-volume-size 20 --dns-zone=indurik8s.xyz

**5. What happened after the commands executed?**

![image](https://user-images.githubusercontent.com/107991579/223937877-7554bba0-dfde-4581-9161-30b8cc802a83.png)

**6. What did you expect to happen?**

To create a  cluster using KOPS.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by jim-barber-he** [comment]
We've hit this as well. The newest AMI we can find is `099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302` (`02` at the end instead of `03`)

**Comment by jim-barber-he** [comment]
Probably can be closed. Looks like it was fixed in https://github.com/kubernetes/kops/pull/15213

**Comment by ravindrai** [comment]
@jim-barber-he  did you mean that i can go ahead and create the cluster , this time it will not give any error.

Could you please kindly make the work around a bit clear.

**Comment by jim-barber-he** [comment]
Yeah. It should work if you try again since the kops team have merged a fix for it already so that their channel returns a valid AMI.

**Comment by hakman** [comment]
Thanks for reporting. Let's keep this open. I hope to add a proper fix that will prevent such issues in the future.
