### ISSUE TITLE
--dns private with public hosted zone results in confusing error message

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/kops#1522]
**Kops Version**: 1.5.0-alpha3

We found this through a user error on our part. We were delayed in fixing the issue because of a confusing error. Here's the snippet:

```
error running task "DNSZone/Z2GZTFG75BO7J2" (3s remaining to succeed): error associating VPC with hosted zone "production.saltside.net": PublicZoneVPCAssociation: Attempting to associate public zone: 1227516 with vpc: vpc-d1f8deb5
```

The issue is that we set `--dns private` (although uncertain to what that _actually_ does), but the provided `--dns-zone` is set to public. 

My proposal is that `kops` should check these prereqs and error with an informative message such as "cannot use --dns private when --dns-zone is public." This gives users a clear failure that they can address. It clarifies it is a _user error_ and not a `kops` error.

**Comment by justinsb** [comment]
We have a fix, but unfortunately it relies on some upstream kubernetes changes in the DNS provider code.  I'm going to bump this to 1.5.1.

**Comment by WebSpider** [comment]
Im running into this with 1.12.1 as well
