### ISSUE TITLE
cluster_spec.md documentation is quite out of date

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1528]
What is the best way to document out API?  Once we have swagger spec, I think we can get some documentation for free.  In the mean time: https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md <- out of date

**Comment by kris-nova** [comment]
This needs to be pulled from code..

Also this brings up the question of versioning our documentation https://github.com/kubernetes/kops/issues/1583

**Comment by kris-nova** [comment]
Follow up thought..

what if the API machinery could generate docs based on API versions..

**Comment by chrislovecnm** [comment]
K8s is generating this https://kubernetes.io/docs/api-reference/v1.5/ <- we need to figure out how to

**Comment by chrislovecnm** [comment]
Closing this and opening another issue about using the API server to generate docs.
