### ISSUE TITLE
Instance groups with warmpools hangs forever on creation

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kops#15289]
/kind bug

#15153 introduced a bug where ASG tasks becomes dependent on warmpool tasks. This works for terraform where the warmpool task is noop, but otherwise fails since ASGs need to be in place before warmpool can be used.

This fails on kOps 1.26 versions.

**Comment by rsafonseca** [comment]
Damn, terrible timing as I'm currently travelling.. I can take a look next week when i'm back @olemarkus, if it's not fixed until then :)

**Comment by olemarkus** [comment]
Thanks. I suspect there won't be a nice fix to this. You probably have to flatten the warmpool properties (i.e use Int pointers) into the ASG task rather than setting the WarmPool task directly.

**Comment by rsafonseca** [comment]
@olemarkus sorry for the delay, just got back from vacation :)
Can you take a look at the proposed implementation in the linked PR? Seemed slightly better, but I'd like to hear your opinion.

**Comment by jim-barber-he** [comment]
With the release of kops 1.27.1 I see that the following pull request was cherry picked.
https://github.com/kubernetes/kops/pull/15722
I've tested with the new version and the WarmPool problems I had before have been resolved, so this issue can probably be closed?
