### ISSUE TITLE
Support for price-capacity-optimized allocation strategy

### ISSUE THREAD

**Issue by raxod502-plaid** [kubernetes/kops#15285]
/kind feature

Feature: https://aws.amazon.com/blogs/compute/introducing-price-capacity-optimized-allocation-strategy-for-ec2-spot-instances/

Error when we try to use it in kops:

```
15:06:31  spec.mixedInstancesPolicy.spotAllocationStrategy: Unsupported value: "price-capacity-optimized": supported values: "lowest-price", "diversified", "capacity-optimized"
```

Actually, it seems like it would be better for kops to simply allow setting an arbitrary spot allocation strategy for the launch template. It's not clear to me why the values need to be restricted.

**Comment by ngraef** [comment]
What version of kOps were you using? This was added in 1.26 via https://github.com/kubernetes/kops/pull/14573 and 1.25.3 via https://github.com/kubernetes/kops/pull/14574.

**Comment by raxod502-plaid** [comment]
I'm not sure what we were using when I filed this issue, but we are currently using 1.25.3 so this can be closed. Thanks!
