### ISSUE TITLE
GCE e2e prow jobs are failing

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#15298]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Example: https://testgrid.k8s.io/kops-gce#kops-grid-gce-kubenet-u2004-k25

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

**3. What cloud provider are you using?**

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

**5. What happened after the commands executed?**

`W0406 12:06:51.425440    6453 executor.go:139] error running task "FirewallRule/pod-cidrs-to-node-ipv6-e2e-e2e-kops-grid-gce-kubenet-u20-26rlkk" (9m19s remaining to succeed): error creating FirewallRule: googleapi: Error 400: Invalid value for field 'resource.allowed[2].IPProtocol': 'icmp'. IPv6 is not compatible with the ICMP protocol. Use the ICMPv6 protocol instead., invalid`

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

It looks like the additional Firewall Rules for kubenet and gce networking modes need updating after https://github.com/kubernetes/kops/pull/15281

**Comment by pavel-odintsov** [comment]
I was able to replicate same issue manually when I tried creating firewall rule for GCE VPC to allow ICMP for IPv6 traffic. It returns error  where it recommends using "ICMPv6" rule for IPv6 traffic.

Sadly it does not accept "ICMPv6" as protocol name. I managed to trick it by using protocol number for ICMPv6 which is 58. After that I was able to create such firewall rule.

**Comment by pavel-odintsov** [comment]
I was able to replicate exactly this issue using GCE command line:
```
odintsov@station1:~$ gcloud compute --project=formal-folder-234712 firewall-rules create allow-icmp-ipv6-test --direction=INGRESS --priority=1000 --network=default-ipv6-enabled --action=ALLOW --rules=ICMP --source-ranges=::0/0
Creating firewall...failed.                                                                                                                            
ERROR: (gcloud.compute.firewall-rules.create) Could not fetch resource:
 - Invalid value for field 'resource.allowed[0].IPProtocol': 'ICMP'. IPv6 is not compatible with the ICMP protocol. Use the ICMPv6 protocol instead.

odintsov@station1:~$ gcloud compute --project=formal-folder-234712 firewall-rules create allow-icmp-ipv6-test --direction=INGRESS --priority=1000 --network=default-ipv6-enabled --action=ALLOW --rules=ICMPv6 --source-ranges=::0/0
Creating firewall...failed.                                                                                                                            
ERROR: (gcloud.compute.firewall-rules.create) Could not fetch resource:
 - Invalid value for field 'resource.allowed[0].IPProtocol': 'ICMPv6'. Must be one of ["ah", "all", "esp", "icmp", "ipip", "sctp", "tcp", "udp"] or an IP protocol number between 0 and 255.

odintsov@station1:~$ gcloud compute --project=formal-folder-234712 firewall-rules create allow-icmp-ipv6-test --direction=INGRESS --priority=1000 --network=default-ipv6-enabled --action=ALLOW --rules=58 --source-ranges=::0/0
Creating firewall...⠹Created [https://www.googleapis.com/compute/v1/projects/formal-folder-234712/global/firewalls/allow-icmp-ipv6-test].              
Creating firewall...done.                                                                                                                              
NAME                  NETWORK               DIRECTION  PRIORITY  ALLOW  DENY  DISABLED
allow-icmp-ipv6-test  default-ipv6-enabled  INGRESS    1000      58           False

```
