### ISSUE TITLE
CPU/Memory Accounting is not enabled for kubelet.service or docker.service

### ISSUE THREAD

**Issue by snarlysodboxer** [kubernetes/kops#1529]
@justinsb 
I'm not sure whether it's the AMIs, or protokube, or what, but CPU/Memory Accounting is not enabled when starting a fresh cluster, using kops 1.4.4, and k8s 1.5.x, (and I tried `k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09`, `k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21`, and some others.)

It's easiest to demo:
Create a cluster, then SSH into one of the nodes, then:
```shell
admin@ip-10-0-58-195:~$ sudo grep -Ri accounting /etc/systemd/
/etc/systemd/system.conf:#DefaultCPUAccounting=no
/etc/systemd/system.conf:#DefaultBlockIOAccounting=no
/etc/systemd/system.conf:#DefaultMemoryAccounting=no
admin@ip-10-0-58-195:~$ cat /var/log/daemon.log | grep -E '(CPUAccounting|MemoryAccounting)' | tail
Jan 18 20:39:27 ip-10-0-58-195 kubelet[18534]: W0118 20:39:27.748323   18534 container_manager_linux.go:728] CPUAccounting not enabled for pid: 18534
Jan 18 20:39:27 ip-10-0-58-195 kubelet[18534]: W0118 20:39:27.748328   18534 container_manager_linux.go:731] MemoryAccounting not enabled for pid: 18534
Jan 18 20:44:27 ip-10-0-58-195 kubelet[18534]: W0118 20:44:27.748593   18534 container_manager_linux.go:728] CPUAccounting not enabled for pid: 19710
Jan 18 20:44:27 ip-10-0-58-195 kubelet[18534]: W0118 20:44:27.748610   18534 container_manager_linux.go:731] MemoryAccounting not enabled for pid: 19710
Jan 18 20:44:27 ip-10-0-58-195 kubelet[18534]: W0118 20:44:27.748660   18534 container_manager_linux.go:728] CPUAccounting not enabled for pid: 18534
Jan 18 20:44:27 ip-10-0-58-195 kubelet[18534]: W0118 20:44:27.748665   18534 container_manager_linux.go:731] MemoryAccounting not enabled for pid: 18534
Jan 18 20:49:27 ip-10-0-58-195 kubelet[18534]: W0118 20:49:27.748947   18534 container_manager_linux.go:728] CPUAccounting not enabled for pid: 19710
Jan 18 20:49:27 ip-10-0-58-195 kubelet[18534]: W0118 20:49:27.748965   18534 container_manager_linux.go:731] MemoryAccounting not enabled for pid: 19710
Jan 18 20:49:27 ip-10-0-58-195 kubelet[18534]: W0118 20:49:27.749016   18534 container_manager_linux.go:728] CPUAccounting not enabled for pid: 18534
Jan 18 20:49:27 ip-10-0-58-195 kubelet[18534]: W0118 20:49:27.749021   18534 container_manager_linux.go:731] MemoryAccounting not enabled for pid: 18534
admin@ip-10-0-58-195:~$
admin@ip-10-0-58-195:~$ ps -a 18534
  PID TTY      STAT   TIME COMMAND
 5134 pts/0    R+     0:00 ps -a 18534
18534 ?        Ssl    0:33 /usr/local/bin/kubelet --allow-privileged=true --api-servers=https://api.internal.dev.k8s.compligo.com --babysit-daemons=true --cgroup-root=docker --cloud-provider=aws --cluster
admin@ip-10-0-58-195:~$
admin@ip-10-0-58-195:~$ ps -a 19710
  PID TTY      STAT   TIME COMMAND
 5242 pts/0    R+     0:00 ps -a 19710
19710 ?        Ssl    0:10 /usr/bin/docker daemon -H fd:// --ip-masq=false --iptables=false --log-level=warn --storage-driver=overlay
admin@ip-10-0-58-195:~$
admin@ip-10-0-58-195:~$ sudo systemctl show docker | grep Accounting
CPUAccounting=no
BlockIOAccounting=no
MemoryAccounting=no
admin@ip-10-0-58-195:~$
admin@ip-10-0-58-195:~$ sudo systemctl set-property docker.service MemoryAccounting=yes
admin@ip-10-0-58-195:~$ sudo systemctl set-property docker.service CPUAccounting=yes
admin@ip-10-0-58-195:~$ sudo systemctl show docker | grep Accounting
CPUAccounting=yes
BlockIOAccounting=no
MemoryAccounting=yes
admin@ip-10-0-58-195:~$
admin@ip-10-0-58-195:~$ sudo grep -Ri accounting /etc/systemd/
/etc/systemd/system.conf:#DefaultCPUAccounting=no
/etc/systemd/system.conf:#DefaultBlockIOAccounting=no
/etc/systemd/system.conf:#DefaultMemoryAccounting=no
/etc/systemd/system/docker.service.d/50-MemoryAccounting.conf:MemoryAccounting=yes
/etc/systemd/system/docker.service.d/50-CPUAccounting.conf:CPUAccounting=yes
admin@ip-10-0-58-195:~$
```

**Comment by chrislovecnm** [comment]
> CPU/Memory Accounting is not enabled when starting a fresh cluster

Is this recommended for K8s?  Also, I assume it is systemd settings that we need to add, or is it kernel changes.

**Comment by justinsb** [comment]
I think that the error message is misleading.

I set a memory limit on a container (`1Gi`), and then I did a `docker ps` to identify the container, then did   `cd /sys/fs/cgroup/memory/docker/a26c2d03c5*` to get into the directory.  Then 

```
> cat memory.limit_in_bytes 
1073741824
```

The error message in my case was saying that the docker & kubelet processes don't have a memory limit.  I think if this is correct, the error message is pretty misleading.

I think we could promote this to an issue in kubernetes/kubernetes, to validate that the error is in fact misleading.

**Comment by snarlysodboxer** [comment]
@justinsb FYI, I discovered this because several times a day some node in my cluster gets a `SystemOOM` k8s Condition, and from that point on I can't SSH into the machine to troubleshoot, and a reboot in AWS console doesn't work. (Only fix is terminating the machine for the ASG to recreate.)

I saw that CPU/Mem accounting weren't enabled for docker, I assumed it was because pods' resource limits weren't working and one of my apps has a memory leak. I'm still a noob to cgroups, but from what I saw [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_linux.go#L717), I thought that if the parent docker process didn't have accounting enabled, then it's child processes wouldn't either.

I SSHed into one of my nodes and ran `ls /sys/fs/cgroup/memory/docker` - there are only 2 directories and they are not any of the 4 Docker containers that should have k8s resource limits set (as seen from `kubectl describe node/<node>` and viewing pod limits.) Furthermore, when I cat `memory.limit_in_bytes` in those 2 directories, the answer is `9223372036854771712` for both. One of those directories is for the protokube container, the other is for a container that doesn't exist.

When you set your `1G` mem limit on your container, was that directly with docker or through k8s?

**Comment by snarlysodboxer** [comment]
Again, my apologies for the false alarm guys. I still don't understand why Accounting isn't enabled for docker and kubelet, but as far as I'm concerned, we can close this issue, whatever is causing my `SystemOOM` condition must be separate. Thanks.

**Comment by chrislovecnm** [comment]
👍 

Thanks @snarlysodboxer no need to apologize :)

**Comment by SupLinux** [comment]
It is very useful for my
