### ISSUE TITLE
Support Cilium Operator pod annotations

### ISSUE THREAD

**Issue by maximumG** [kubernetes/kops#15310]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Kops `1.23` introduced the possibility to add some custom annotation on every Cilium agent pods using the `cilium.agentPodAnnotations` key in the cluster definition (https://github.com/kubernetes/kops/pull/12414). 

Annotations are pretty useful when you need third-party tool to add additional behavior for a k8s resource.
Lots of auto-discovery tools are based on this annotations.

I would expect the same feature but for the Cilium operator pods which is installed along with the Cilium agents on any K8S cluster backed by Cilium CNI.

**2. Feel free to provide a design supporting your feature request.**

I would propose to mimic the PR #12414 and introduce the `cilium.operatorPodAnnotations` key. This specific key will then support adding annotation on the Cilium operator pod.

**Comment by moshevayner** [comment]
I can take that one
/assign
