### ISSUE TITLE
AWS AutoScalingGroup Won't Shrink

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/kops#1532]
The instance group yaml spec has both a `minSize` and `maxSize`. When the k8s cluster gets created, an AWS AutoScalingGroup is created, and the `minSize` is used for both the `Min` and `Desired` sizes for the ASG. 

If you change the `minSize` and then update the cluster, the behavior is not consistent. If the new `minSize` is larger then the original value, both the AWS `Min` and `Desired` values are changed to the specified `minSize`. However if the new `minSize` is smaller then the original value only the AWS `Min` value is changed. I'm guessing this is intentional, however it means that we can't use `kops` to update the size of the cluster.

I wonder if a new value should be added to the instance group yaml spec, perhaps `targetSize`, which controls the ASG's `Desired` value.

**Comment by justinsb** [comment]
We do want to integrate the autoscaler, which is why we're setting the bounds.

If you change both minSize and maxSize, doesn't that change the number of instances deterministically?

**Comment by pluttrell** [comment]
After thinking about this more and clarifying with AWS support, I think that my original suggestion is wrong and that perhaps the wisest thing for `kops` to do is to never set the `Desired` field.

Here's an example of what I observed `kops` do yesterday:

| Config  | kops `minSize` | kops `maxSize`|  | AWS `Min`  | AWS `Desired `  | AWS `Max` |  | Actual Node Count |
|:--:|--:|--:|--:|--:|--:|--:|--:|--:|
| Initial | 2 | 10 | sets | 2 | 2 | 10 | yields | 2 |
| Update1 | 5 | 10 | sets | 5 | 5 | 10 | yields | 5 |
| Update2 | 2 | 10 | sets | 2 | 5 | 10 | yields | 5 |

This felt odd, because I was exercising config changes and expected that reducing the `minSize` to shrink the actual number of instances, which is controlled by AWS's `Desired` value. 

But after thinking about it more, I wondered if other things such as the scaling policies also change the `Desired` value. And sure enough AWS support confirmed that this is exactly how the scaling policies work. The ASG will work hard to maintain the `Desired` number of instances, but the `Desired` field is designed to be fluid.

Furthermore adding a `targetSize` which directly updates the `Desired` field, might cause a situation, that I think we really want to avoid: 
1. Someone builds a new cluster with `kops` setting the `targetSize` to X, which directly sets `Desired` to X. 
1. Then the cluster is hit with enough load to trigger a scaling policy to change the `Desired` value to X + 5, which in turn triggers AWS to bring the ASG up to X + 5 instances. 
1. Then, before that load subsides, `kops` is used to update the cluster, which has the stored configuration in S3 of the original `targetSize` of X, which if directly sets `Desired` to X, would instruct the ASG to immediately terminate the oldest 5 instances. Definitely not what we'd want to happen.

**Comment by hustshawn** [comment]
Actually, what I find is there is no exactly mapping from kops to AWS ASG `desired`, kops only increase when the minSize is over the desired size in ASG.
