### ISSUE TITLE
Delete Cluster doesn't kubectl config unset current-context

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/kops#1533]
`kops delete cluster` doesn't remove the references to the deleted cluster from the `~/.kube/config`.

**Comment by justinsb** [comment]
So this should be fixed in kops 1.5.0 alpha4.    It does leave the `current-context` set, but all the other values are removed.

**Comment by pluttrell** [comment]
I just noticed that `gcloud container clusters delete` blanks out the `current-context`, which might be a better option than leaving it set to a deleted context.

**Comment by pluttrell** [comment]
This does it from a terminal: `kubectl config unset current-context`.

**Comment by chrislovecnm** [comment]
Going to change the name of this issue to the above

**Comment by justinsb** [comment]
Going to punt the remaining issue to 1.5.1.  Also marking as "good-starter-issue" as we have a number of people wanting good places to start contributing to kops.

**Comment by justinsb** [comment]
This should be fixed by #1663, which is now released; closing
