### ISSUE TITLE
Use released images for cloud-provider-gcp

### ISSUE THREAD

**Issue by aojea** [kubernetes/kops#15383]
https://github.com/kubernetes/kops/blob/68bf1870f91f453fb6371827dec959b4e37bcdf8/pkg/model/components/gcpcloudcontrollermanager.go#LL84C23-L84C42

The project started to publish images `registry.k8s.io/cloud-provider-gcp/cloud-controller-manager:v26.2.4`

Ref: https://github.com/kubernetes/cloud-provider-gcp/issues/289

/cc @justinsb

**Comment by zetaab** [comment]
@aojea what is that tag format in this image? does v26 mean kubernetes 1.26 or what is purpose of that? Just thinking is that ccm backwards/upwards compatible to which kubernetes versions

**Comment by aojea** [comment]
> @aojea what is that tag format in this image? does v26 mean kubernetes 1.26 or what is purpose of that?

good question, reopened https://github.com/kubernetes/cloud-provider-gcp/issues/289 with that question
