### ISSUE TITLE
ebs-csi addon resources not removed once they are provisioned by kops

### ISSUE THREAD

**Issue by mzeeshan1** [kubernetes/kops#15409]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.26.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.23.17

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
disable ebs-csi addon in cluster spec after provisioning the cluster (ebs-csi-node and controller already installed in cluster via kops addon) with following config 
```
spec:
  cloudConfig:
    awsEBSCSIDriver:
      enabled: false
```

**5. What happened after the commands executed?**
ebs-csi related resources i.e. ebs-csi controller and ebs-csi node did not get removed from cluster

**6. What did you expect to happen?**
ebs-csi-node and ebs-csi-controller to get removed from cluster

**Comment by olemarkus** [comment]
Removing addons isn't supported. See #13962 

Also, those addons are mandatory as of 1.24 anyway, so best to keep them around.
