### ISSUE TITLE
Feature - Attach LoadBalancer/TargetGroups through instancegroup spec

### ISSUE THREAD

**Issue by tsupertramp** [kubernetes/kops#1543]
Hey Ho,

i would like to implement the following new command line parameters on create:
```
      --master-target-groups string     Associate masters with self-managed target groups
      --master-load-balancers string    Associate masters with self-managed load balancers
      --node-target-groups string       Associate nodes with self-managed target groups
      --node-load-balancers string      Associate nodes with self-managed load balancers
```

This would allow me to create LoadBalancer/TargetGroups without using kops or kubernetes.

The CLI Parameters would populate the following Instancegroup spec
```
additionalLoadBalancerNames:
- thomas-test
additionalTargetGroupARNs:
- arn:aws:elasticloadbalancing:eu-west-1:someid:targetgroup/test2/someid
```

The change would allow to attach/detach the LoadBalancers/TargetGroups to Node/Master AutoscalingGroups.

My feature is almost ready - It shows differences like that:
```
Will modify resources:
  AutoscalingGroup/nodes.infra.k8s.SOMEDOMAIN
  	LoadBalancerNames   	 [thomas-test] -> []
  	TargetGroupARNs     	 [] -> [arn:aws:elasticloadbalancing:eu-west-1:someid:targetgroup/test2/someid]
```

And attaches/detaches LoadBalancers/TargetGroups idempotent but i have problems to get it working with enabled api load balancer. I have some Ideas how to implement it but would like to discuss it first. Especially as i am afraid to work in a wrong direction.

```
spec:
  api:
    loadBalancer:
      type: Public
```

Maybe some of the you could look over my code and discuss with me how to go on? Should i create a "WIP" Pull Request? Or what is best practise to work together with you on the feature? :)

Greetings, Thomas

**Comment by gopinatht** [comment]
This would be an awesome feature for us and pretty much solve https://github.com/kubernetes/kops/issues/1551 if security groups are taken care of.

**Comment by justinsb** [comment]
By all means create a WIP PR if you have one!  We likely won't get to it in 1.5.0, but we'll be doing a faster release cadence post 1.5.0.

Some thoughts:

Is there a reason not to use k8s support for ELBs?  Can you describe the underlying use case a bit more please?  For example, given we're creating a master ELB (sometimes), I'm wondering if we could just add something there.

**Comment by tsupertramp** [comment]
Sorry should have explained it: We are not using k8s support for elbs as we want to separate kubernetes cluster from ELBs. If the cluster dies or we roll over to a new one (we switch from one cluster to another instead of upgrading) we have to recreate load balancers => new dns records. If we use predefined load balancers we can easily switch one service after another to the new cluster. Another possibility would be to switch dns records and use the newly generated svc from kubernetes but dns means always to wait until everyone has the new entries and it does not allow fast roll-backs on errors. Beside that k8s does not allow to use all features which elbs allow and it does not allow albs which have a lot more features then elbs. https://github.com/kubernetes/kubernetes/issues/30518

Will add my WIP PR in the near future :) Thanks

**Comment by tsupertramp** [comment]
This is not a Problem any more.

We use an nginx ingress controller and are pretty happy with it.

**Comment by zifot** [comment]
@tsupertramp Could you share an outline of your solution with ingress controller? How exactly does it address the problem of elb reusage?

**Comment by tsupertramp** [comment]
@zifot - yeah of course. We just do not reuse elbs. - We switch traffic by switching dns and pointing it to new elbs of new cluster. This is a lot better than reusage of them as we can switch partly traffic for some domains to the new cluster. So for some time we have two clusters running. This allow us to switch traffic back if cluster makes problem.

There are some problems with this as well (e.g. DNS lazy clients, so we keep for about four hours two clusters running.) - Jenkins has to deploy on two clusters (we solved this through wrapper scripts which deploys to two clusters in this time) / Still cronjobs are migrated manually.

There is a slack user group by the way http://slack.k8s.io/ and in there a kops user channel where you can ask things.

Greetings, Thomas

**Comment by skamchiline** [comment]
@thomaspeitz Hi Tomas, 
I ran into an issue with this feature - we manage NLBs ourselves too, but I don't want kops to touch the preconfigured TGs in the ASes. Is there a parameter I can use, so kops ignores the preconfigured TGs? Currently it bluntly removes them which I don't want
