### ISSUE TITLE
etcd manager fails to start during cluster creation in ap-southeast-4(Melbourne)

### ISSUE THREAD

**Issue by kiamco** [kubernetes/kops#15435]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
 kops version
Client version: 1.26.3 (git-v1.26.3)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
 
v1.27.1

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster \
    --kubernetes-version ${KUBERNETES_VER} \
    --zones ${ARR[1]},${ARR[2]} \
    --cloud aws \
    --node-count 2 \
    --node-size m5.large \
    --master-size m5.large \
    --ssh-access <cidr> \
    --admin-access <cidr> \
    --dry-run \
    -o yaml ${NAME} > ${FILE}

**5. What happened after the commands executed?**
etcd fails to start due to this errror

I0519 23:03:14.333552    3507 s3context.go:169] got region from metadata: "ap-southeast-4"
W0519 23:03:14.333586    3507 controller.go:161] unexpected error running etcd cluster reconciliation loop: error refreshing control store after leadership change: error reading s3://<state_bucket>/<location>/backups/etcd/events/control: ap-southeast-4 is not a valid region
Please check that your region is formatted correctly (e.g. us-east-1)

**6. What did you expect to happen?**
I expect that ap-southeast-4 is a valid region

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
im assuming its similar to this https://github.com/kubernetes/kops/issues/6998

**Comment by kiamco** [comment]
just fyi, not sure if this is the reason why but  I looked at the manifest for etcd-manager and the version of etcdadm that running is registry.k8s.io/etcdadm/etcd-manager:v3.0.20230201 so I looked into
https://github.com/kubernetes-sigs/etcdadm/blob/etcd-manager/v3.0.20230201/etcd-manager/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go and it doesn't include ap-southeast-4

**Comment by hakman** [comment]
@kiamco https://github.com/kubernetes-sigs/etcdadm/pull/374 should remove that check, that was removed from kOps in https://github.com/kubernetes/kops/pull/15105.

**Comment by kiamco** [comment]
Is there any update on this. Still seeing the issue while using the kops version 1.26.3 (git-v1.26.3) any advice on how to workaround this problem

**Comment by hakman** [comment]
@kiamco Could you give kOps 1.27.0-beta.3 a try?
https://github.com/kubernetes/kops/releases/tag/v1.27.0-beta.3

**Comment by kiamco** [comment]
@hakman  https://github.com/kubernetes/kops/releases/tag/v1.27.0-beta.3 worked like a charm. Thanks!

**Comment by hakman** [comment]
Happy to hear that. 🎉
1.27.0 should be out in a 1-2 weeks, but you can use the beta until then.
