### ISSUE TITLE
Reduce the list of skipped e2e test for Cilium

### ISSUE THREAD

**Issue by aojea** [kubernetes/kops#15448]
https://github.com/kubernetes/kops/blob/f2fe04438f322b0b248ed8ab49b5105cf20ae106/tests/e2e/pkg/tester/skip_regex.go#L60-L85

Some of them got fixed in 
https://github.com/cilium/cilium/pull/24202
https://github.com/cilium/cilium/pull/24174

you can compare against the regex in cilium repo 
https://github.com/cilium/cilium/pull/25258/files#diff-01b72d17856efb38bd2914aec50791eef6b9bc8238b6975d12f87b39cb24b008R214

Feel free to tag me to review the PR

**Comment by hakman** [comment]
Thanks @aojea. I checked ing https://github.com/kubernetes/kops/pull/15449 and, for now, there's not much we can do with Cilium 1.12.x.

**Comment by johngmyers** [comment]
Office hours: after we upgrade Cilium

**Comment by johngmyers** [comment]
Now we've upgraded to Cilium 1.13, I've submitted kubernetes/test-infra#30300 to see which skips we can remove.

We are still seeing failures for "Services should fallback to local terminating endpoints when there are no ready endpoints with externalTrafficPolicy=Local": https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-cilium-k8s-ci

**Comment by aojea** [comment]
is this aws specific or do we have any other jobs we can compare with?

cilium seems to have a lot of knobs per platform ...

**Comment by johngmyers** [comment]
I'm adding a GCP variant of the test in kubernetes/test-infra#30324
