### ISSUE TITLE
More docs about gossip dns

### ISSUE THREAD

**Issue by guettli** [kubernetes/kops#15455]
/kind feature

Thank you for the current docs:

https://kops.sigs.k8s.io/gossip/

But please extend them.

How can I configure my local laptop to resolve the DNS name?

**Comment by olemarkus** [comment]
> How can I configure my local laptop to resolve the DNS name?

This isn't really feasible. The gossip DNS names are entirely internal to the cluster, so to resolve it externally you need a DNS resolver in the cluster that you use locally.
