### ISSUE TITLE
Customize updateStrategy for Cilium daemonset

### ISSUE THREAD

**Issue by raxod502-plaid** [kubernetes/kops#15465]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
We are upgrading from kops 1.20.3 (k8s 1.20.15) to kops 1.26.3 (k8s 1.25.10) and migrating from managing our own Cilium deployment to using the one provisioned by kops. However, we had previously configured Cilium with `updateStrategy.type: RollingUpdate` which did not cause downtime as we had an eBPF HostPath mount to preserve the networking configuration while the Cilium pod was restarting. Looking at the kops-managed Cilium it seems that it also has this configuration and would be safe to set `updateStrategy.type: RollingUpdate`, but as far as I can tell there is no way to customize the update strategy that kops sets for Cilium, it is hardcoded to `OnDelete`. This is a minor inconvenience because when changing parameters of the Cilium deployment one must manually roll it.

**2. Feel free to provide a design supporting your feature request.**
Ideally there would be some key in the Cluster spec that would allow setting parameter(s) of the Cilium deployment including its `updateStrategy`.

Here's what I think are the currently supported keys (most of them not documented):

https://github.com/kubernetes/kops/blob/6995b12559257e37a05aee54939222c97d0f3c8f/pkg/apis/kops/networking.go#L261-L505

**Comment by olemarkus** [comment]
There are various configuration changes that require nodes to be rolled in order to work. So setting `RollingUpdate` is not a good idea. If you are sure it is safe to roll, just roll manually.
