### ISSUE TITLE
Review docs/development/release.md when we cut next release

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1546]
docs/development/release.md is theory; we should update it with practice

**Comment by kris-nova** [comment]
Can't agree more here..

Can we please update

1. https://github.com/kubernetes/kops/blob/master/docs/development/release.md
2. https://github.com/kubernetes/kops/blob/master/docs/releases.md

We **MUST** start amalgamating these pieces of documentation.. we really need density here (for the entire project)

**Comment by geojaz** [comment]
@justinsb @kris-nova @chrislovecnm @yissachar 
As we approach our latest release, let's make sure we revisit this!

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by chrislovecnm** [comment]
closing
