### ISSUE TITLE
Upgrade AWS LBC to v2.5.x

### ISSUE THREAD

**Issue by danports** [kubernetes/kops#15473]
See: https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.5.0

> We've updated the controller manifests, so either use helm upgrade or apply the new manifest. The new controller image is not compatible with manifests from earlier releases, so we don't recommend editing existing deployment and updating the image tag.

Also this, but I don't think it's a problem for us since the latest kOps versions wouldn't still support Kubernetes 1.21:
> We have made the LBC the default controller for service type LoadBalancer by adding a mutating webhook. Therefore, from v2.5.0, it is required to use k8s 1.22 or later to support the `spec.loadBalancerClass`.

**Comment by yurrriq** [comment]
I'll take a stab at upgrading to v2.7.0... h/t @danports for motivating me on Slack :fist_right: :fist_left:

**Comment by danports** [comment]
Ah, I didn't see that LBC v2.6.2 PR, thanks @yurrriq!
