### ISSUE TITLE
Amalgamate documentation on the PR process

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1549]
Right now we have some bits and pieces of documentation floating around on onboarding, and getting ramped up.

Can we please amalgamate all of the documentation into one place that has a step-by-step guide on getting a PR through the door?

Some **great** feedback we received recently was some unclarity around the PR process.

1. How does the PR process work?
2. What tests get ran? How do I run them?
3. CLA?
4. What happens in a code review?
5. Who will review my code?
6. How do I close an issue from my PR?

### PR Requirements 

1. What do I need in my PR?
2. Do I need documentation?
3. What about tests?

CC @evildandelions

**Comment by chrislovecnm** [comment]
@scottmwebber ping

**Comment by chrislovecnm** [comment]
Closing as this is upstream and contribex work
