### ISSUE TITLE
Improve command descriptions

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1550]
### Example kops command:

```
Kris-Nova:~ kris$ kops
kops is kubernetes ops.
It allows you to create, destroy, upgrade and maintain clusters.

Usage:
  kops [command]

Available Commands:
  completion     Output shell completion code for the given shell (bash)
  create         Create a resource by filename or stdin
  delete         delete clusters
  describe       describe objects
  edit           edit items
  export         export clusters/kubecfg
  get            list or get objects
  import         import clusters
  replace        Replace a resource by filename or stdin
  rolling-update rolling update clusters
  secrets        Manage secrets & keys
  toolbox        Misc infrequently used commands
  update         update clusters
  upgrade        upgrade clusters
  validate       Validate Cluster
  version        Print the client version information
```

Some example descriptions I wanted to point out:
```
..
  edit           edit items
..
  update         update clusters
  upgrade        upgrade clusters
..
```

Check out [this line](https://github.com/kubernetes/kops/blob/master/cmd/kops/edit.go#L28) for an example.

### Improvements

Can we please open a PR that changes the verbage around our cobra commands? The descriptions should be short and sweet. No longer than one sentence, and use proper sentence structure (Capitalization, punctuation, etc)

**Comment by frodopwns** [comment]
I can take this on. @kris-nova could you assign this to me?

**Comment by kris-nova** [comment]
Trying too - it actually looks like I might only be able to assign to members.. hrmm.. weird.. will ask around and see what I can come up with

**Comment by chrislovecnm** [comment]
@kris-nova you can only assign issues to people that are a member of the kubernetes GitHub organization.  Kinda odd, I know.
