### ISSUE TITLE
AWS: Need a way to specify ingress rules or assign security group to nodes

### ISSUE THREAD

**Issue by gopinatht** [kubernetes/kops#1551]
This is building off the (https://github.com/kubernetes/kops/issues/748) issue but I have a concrete use case and @kris-nova suggested I log a new bug so here it is.

Right now, the nodes security group only allows inbound connections to the master (all protocols, all ports), itself (all protocols, all ports) and bastion (TCP, 22). 

This is not enough because we will create a bunch of additional ELBs that represent some kubernetes services on node ports and we will need the nodes to be able to receive traffic (via its Auto Scaling Groups) from these ELBs.

We need a way to specify a predefined AWS security group as the source of inbound traffic so I can use that SG with my custom ELBs. Alternatively, if we can suggest ingress/egress rules through API or command line and a SG is created for us, we can then use it for our ELBs.

**Comment by justinsb** [comment]
Was this addressed by our discussion of Type=LoadBalancer / ELBs on Slack @gopinatht ?

**Comment by gopinatht** [comment]
@justinsb Partially. I still need a way to enable Ingress for custom ELBs not generated by k8s or kops

**Comment by vendrov** [comment]
We are working on adding predefined security groups in addition to the "default" one, So in your case you will have to create one security group for the ELB, and another one with a ingress rule using the previous security group as a source. When you will setup the cluster you will add the second security group to your instance group

**Comment by tsupertramp** [comment]
@vendrov Did you see? - https://github.com/kubernetes/kops/pull/1444 it is solving the issue https://github.com/kubernetes/kops/issues/224 and this one - I made this pull request in preparation to do the second one (https://github.com/kubernetes/kops/issues/1543) which would fullfill the use case of this pull request (and my companies use case).

Greetings, Thomas

**Comment by vendrov** [comment]
@tsupertramp Your PR looks great! I've closed mine, Thanks

**Comment by justinsb** [comment]
@gopinatht would #1444 solve your use case also?  Would #1543?

**Comment by gopinatht** [comment]
@justinsb I suppose so. It looks like #1444 and #1543 do slightly different things. If I had to choose one, I would choose 1444. If we can get both, that would be awesome.

**Comment by justinsb** [comment]
So we have #1444 in 1.5.0, we'll hopefully get #1543 into 1.5.1

**Comment by chrislovecnm** [comment]
Closing
