### ISSUE TITLE
Custom errors in kops

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1554]
We are `fmt.Errorf()`ing all the things right now..

I would suggest that we start looking into package level custom errors for slighty more advanced error handling and error types.

**Comment by justinsb** [comment]
Can we start with an example of where this would be useful?  Is this only when using kops as a library?

**Comment by kris-nova** [comment]
> Can we start with an example of where this would be useful?

Yes. I will PR one in one of the next bug/feature PRs as an example. 

> Is this only when using kops as a library?

No. These would (potentially) be used **in place of** any `fmt.Errorf()` or `error.New()` we have floating around the code base.

**Comment by chrislovecnm** [comment]
Also we are outputting errors like

```
W0128 23:07:37.463320   55844 executor.go:109] error running task "LaunchConfiguration/nodes.liea-ginny.dev.datapipe.io" (9m56s remaining to succeed): IAM instance profile not yet created/propagated (original error: You are not authorized to perform this operation.)
W0128 23:07:37.463378   55844 executor.go:109] error running task "LaunchConfiguration/master-eu-west-1a.masters.liea-ginny.dev.datapipe.io" (9m56s remaining to succeed): IAM instance profile not yet created/propagated (original error: You are not authorized to perform this operation.)
```

Which are not "errors" .... just running in async
