### ISSUE TITLE
Add `BuildRestConfig` back

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/kops#15556]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Since https://github.com/kubernetes/kops/pull/15494 the `BuildRestConfig` method was removed.
I was using it in the [terraform-provider-kops](https://github.com/eddycharly/terraform-provider-kops/blob/c9c6b0685324a1f3bdbf9a6cbfa7f4a47f984464/pkg/api/utils/cluster_validate.go#L43) project.

I moved the code in the provider but it would be nice if it can be added back.

**Comment by hakman** [comment]
@eddycharly If you still need this and want it added back, please do so and /cc me for review.
