### ISSUE TITLE
Kube-Proxy doesn't start

### ISSUE THREAD

**Issue by JJotah** [kubernetes/kops#15555]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.** v1.26.5

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.** v1.26.5

**3. What cloud provider are you using?** AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?** Autoscale with karpenter from 0 nodes to 3 nodes

**5. What happened after the commands executed?** Some of nodes can't start kube-proxy

**6. What did you expect to happen?** Start automatically kube-proxy

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

The issue is random, a lot of times kops start correctly but when a high autoscalation from 0 to 3 at the same time is running, seems like one of them, kubelet forgot to start the kube-proxy.manifest in the path /etc/kubernetes/manifest 
To solve the issue are 2 options:
1.- Restart kubelet
2.- move the file in other folder and copy in the same /etc/kubernetes/manifest folder

Kops should check if kube-proxy is starting and if not restart again kubelet after nodeup finish

**Comment by hakman** [comment]
@JJotah This looks more like a Kubernetes bug than kOps. Did you open an issue in k/k also? If so, could you reference it?
Is there anything interesting in kubelet logs?

**Comment by JJotah** [comment]
> @JJotah This looks more like a Kubernetes bug than kOps. Did you open an issue in k/k also? If so, could you reference it? Is there anything interesting in kubelet logs?

Yeah I thought but kops is in charge to start kubelet and when autoscaling is too elevate kops didn't noticed that kube-proxy doesn't start and kops as tool (from my opinion) I think that kops should check if kube-proxy in the nodes are working if not restart kubelet. All nodes with this issue stay at NotReady status and kops didn't noticed even karpenter.

**Comment by hakman** [comment]
I suggest to try https://github.com/kubernetes/kops/releases/tag/v1.27.0-beta.3 with a newer Karpenter and see if you can still reproduce the issue.
