### ISSUE TITLE
containerd/runc assets are still downloaded if skipInstall is true

### ISSUE THREAD

**Issue by ReillyBrogan** [kubernetes/kops#15558]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.26.4

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.26.6

**3. What cloud provider are you using?**
AWS/Spotinst

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Have a cluster with `.spec.containerd.skipInstall = true`.

**5. What happened after the commands executed?**
The node logs indicate that containerd and runc assets are downloaded and extracted. They are never used.

**6. What did you expect to happen?**
For this to not happen

**Comment by hakman** [comment]
More of a feature than a bug. SkipInstall behaviour is not optimal, but the end result is the desired one.
/remove-kind bug
/kind feature
