### ISSUE TITLE
A newer version of kOps is going to remove encryption from EBS volumes

### ISSUE THREAD

**Issue by victor-sudakov** [kubernetes/kops#15560]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.23.0 to create a cluster and 1.26.4 to update it

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.23.17

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Created a cluster with kops 1.23.0 with the attached manifest (DNS domains redacted)
`./kops-linux-amd64-v1.23.0 create -f test3-cluster.yaml`

Later tried to update the cluster with a new version of kops, namely 1.26.4
`./kops-linux-amd64-v1.26.4 update cluster`

**5. What happened after the commands executed?**

kOps printed numerous messages about removing KmsKeyId from EBS volumes, like
```
    EBSVolume/a.etcd-events.test3.XXXX
    KmsKeyId               arn:aws:kms:us-west-2:156145528543:key/f264b5c8-c23b-41cf-b375-ecde77a6fe45 -> <nil>
    Tags                   {k8s.io/etcd/events: a/a,b,c, KubernetesCluster: test3.XXXX, Name: a.etcd-events.test3.XXXX, k8s.io/role/master: 1, kubernetes.io/cluster/test3.XXXX: owned} -> {KubernetesCluster: test3.XXXX, k8s.io/etcd/events: a/a,b,c, k8s.io/role/control-plane: 1, k8s.io/role/master: 1, kubernetes.io/cluster/test3.XXXX: owned, Name: a.etcd-events.test3.XXXX}
    
  EBSVolume/a.etcd-main.test3.XXXX
    KmsKeyId               arn:aws:kms:us-west-2:156145528543:key/f264b5c8-c23b-41cf-b375-ecde77a6fe45 -> <nil>
    Tags                   {Name: a.etcd-main.test3.XXXX, KubernetesCluster: test3.XXXX, k8s.io/etcd/main: a/a,b,c, k8s.io/role/master: 1, kubernetes.io/cluster/test3.XXXX: owned} -> {k8s.io/role/master: 1, kubernetes.io/cluster/test3.XXXX: owned, Name: a.etcd-main.test3.XXXX, KubernetesCluster: test3.XXXX, k8s.io/etcd/main: a/a,b,c, k8s.io/role/control-plane: 1}
    
  EBSVolume/b.etcd-events.test3.XXXX
    KmsKeyId               arn:aws:kms:us-west-2:156145528543:key/f264b5c8-c23b-41cf-b375-ecde77a6fe45 -> <nil>
    Tags                   {k8s.io/etcd/events: b/a,b,c, k8s.io/role/master: 1, KubernetesCluster: test3.XXXX, Name: b.etcd-events.test3.XXXX, kubernetes.io/cluster/test3.XXXX: owned} -> {k8s.io/role/master: 1, kubernetes.io/cluster/test3.XXXX: owned, Name: b.etcd-events.test3.XXXX, KubernetesCluster: test3.XXXX, k8s.io/etcd/events: b/a,b,c, k8s.io/role/control-plane: 1}


```
**6. What did you expect to happen?**
I did not expect a newer version of kOps try to remove KMS Keys from EBS volumes. Is it even safe, will it break the cluster destroying the etcd volumes?

**7. Please provide your cluster manifest. 

It's very vanilla actually:
[test3-cluster.yaml.txt](https://github.com/kubernetes/kops/files/11913332/test3-cluster.yaml.txt)

**9. Anything else do we need to know?**

I would like to know how safe it is to update this cluster with the newer version of kOps.

**Comment by justinsb** [comment]
/office-hours

I _hope_ this is only an error in our "preview" output, I agree this is not the correct/desired behaviour.

**Comment by victor-sudakov** [comment]
Has anyone been able to reproduce it?

**Comment by hakman** [comment]
@victor-sudakov As @justinsb hoped, this is just a display error. By adding a new tag `k8s.io/role/control-plane: 1`, the change will no longer appear.

In general, EBS encryption cannot be turned on/off easily for existing volumes. It involves considerable manual effort and kOps cannot do it:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#migrate-data-encrypted-unencrypted

**Comment by victor-sudakov** [comment]
By adding a new tag k8s.io/role/control-plane: 1, the change will no longer appear.

@hakman Thanks for the positive heads up! How/where do I add a tag, or should I just ignore the message?

**Comment by hakman** [comment]
Ignoring the message is the easiest.
