### ISSUE TITLE
Invalid details from https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#AWSSpec

### ISSUE THREAD

**Issue by s3than** [kubernetes/kops#15669]
When attempting to update a cluster with the API details from here 

https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#AWSSpec

The following error is returned when attempting to replace

```
no kind "Cluster" is registered for version "kops.k8s.io/v1alpha3" 
```

Or if switching to `kops.k8s.io/v1alpha2` 

```
json: cannot unmarshal object into Go struct field ClusterSpec.spec.cloudProvider of type string
```

Is there a method of using the updated Spec as yet?

**Comment by johngmyers** [comment]
The v1alpha3 apiversion is not released yet.

**Comment by johngmyers** [comment]
And the pkg.go.dev link you gave is for the internal API, which is different than v1alpha2. You want https://pkg.go.dev/k8s.io/kops/pkg/apis/kops/v1alpha2#AWSSpec

**Comment by s3than** [comment]
Clicking on the link in this doc page

https://kops.sigs.k8s.io/cluster_spec/

Goes straight to https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#ClusterSpec

From there clicking CloudProvider -> AWSSpec gives the details above..

If appropriate I'm happy to provide a PR to change that link to https://pkg.go.dev/k8s.io/kops/pkg/apis/kops/v1alpha2#ClusterSpec

So that clarifies the docs side.

@johngmyers Thanks for the update

**Comment by johngmyers** [comment]
One possible reference would be https://github.com/kubernetes/kops/tree/master/k8s/crds

I don't know if that's published anywhere that makes it pretty. The pkg.go.dev link does have that same information, but it also has a bunch of noise.
