### ISSUE TITLE
Documentation - Migrating from a single to a multi-master setup

### ISSUE THREAD

**Issue by MrTrustor** [kubernetes/kops#1566]
I expect most people will first try out kops with a single-master setup. Kubernetes being Kubernetes, a lot of things will soon be hosted on the cluster. The documentation needs to detail how to go from a single-master setup to a multi-master setup to allow people to "consolidate" their cluster.

With trial and (a lot of) errors, this is what I ended up following. This is a very manual process, and I think I made a lot of mistakes. I will be happy to contribute the changes to the documentation.

## Context

- AWS Region: eu-west-1 (3 AZs)
- 1 master
- 3 nodes (one on each region)
- kops 1.4.4
- Kubernetes 1.4.8

## Procedure

1. [Backup](https://github.com/coreos/etcd/blob/v2.2.1/Documentation/admin_guide.md#disaster-recovery) both etcds on master
2. Stop kubelet, protokube and both etcds on master
3. Create 2 new instance groups for the masters on the other AZs
4. edit the cluster to add them in the "etcdClusters" section
5. Apply the changes with a "kops update cluster <mycluster> --yes"
6. Once the 2 new masters have started, terminate the old one, it will be restarted.
7. When restarting the original master, it should join the two others and serve its data, if not follow the "Disaster recovery" [procedure](https://github.com/coreos/etcd/blob/v2.2.1/Documentation/admin_guide.md#disaster-recovery) of etcd.

**Comment by justinsb** [comment]
Wow - thanks @MrTrustor .  I'm going to try your procedure.  If we can get docs on how to do it, it will really help people IMO, and is probably the first step towards automating it!

**Comment by chrislovecnm** [comment]
@MrTrustor are you able to update the docs?

**Comment by MrTrustor** [comment]
@chrislovecnm I will to try and reproduce what I did to be sure I am writing something somewhat coherent.

**Comment by MrTrustor** [comment]
Closed by #1657

**Comment by prime421** [comment]
Apologize for the potentially dumb question, but in this scenario, are we to just clone the existing master node into 2 more master nodes for a total of 3 and then proceed with the document you provided?

**Comment by MrTrustor** [comment]
No, no need to do anything prior to following this documentation. The new masters will be created by the instance groups when you reach those steps in the documentation.

**Comment by prime421** [comment]
Thank you, Theo!  In going through the documentation (which is detailed and concise well done!), it looks like I need kops to achieve this and that kops is only available on AWS?

I ask because we have a local K8S deployment (1 master, 3 nodes) that we have been doing testing on before rolling out to production.  In production, we want 3 masters for redundancy, but we are all new to K8S so the learning curve has been a bit steep.  If we do not utilize AWS, does this document still apply?

Thanks again!

**Comment by MrTrustor** [comment]
Yes, you are on the kops repository, so this documentation is intended to be used on a cluster created by kops. For now kops is mainly targeted at AWS, but some GCP support also exists and VMware is working on a VSphere adaptation.

If you did not use kops to create your cluster, this documentation will not apply. However, you can still follow the underlying principles (i.e creating new masters and having them join the initial etcd cluster) to achieve the same goal. What exact path you will follow to do that will depend entirely on how your cluster was initially set up.

**Comment by prime421** [comment]
So I am and so it is haha, fail on my part!  I saw a guide that looked promising and did not realize where I was, my apologies.  Thanks for taking time out to explain, I appreciate it.

**Comment by neverfox** [comment]
Very nice. Is the process the same going from 3 to 4 and 4 to 5? For example, I have a 3-master cluster in us-east-1a, 1b, and 1c. I would like to add 1d and 1e.
