### ISSUE TITLE
How to set memory/cpu limit for containerd(docker) process on EC2

### ISSUE THREAD

**Issue by kutsyk** [kubernetes/kops#15697]
/kind feature

We had an issue where out kube-apiserver was bombarded with requests and because of the it consumed max memory available for it.
As it is running as container in docker, it by default has max memory limit of the node. So when we where hitting the issue, we were not able to login to the node or access it's log.

Is there a way to set a memory limit for docker - https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory

I'm checking the official API - https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#ContainerdConfig, but I can't find anything pointing to that. 

Maybe there is a way to add additional params for docker or some default top level params?

As result we want not to have our EC2 overloaded and not accessible with limiting max memory that can be used by kube-apiserver

**Comment by johngmyers** [comment]
There is a cluster setting `spec.kubeAPIServer.memoryLimit`

**Comment by kutsyk** [comment]
@johngmyers , thanks, works fine. Can I use same for other control plane services, like kube-controller-manager and kube-scheduler?

**Comment by johngmyers** [comment]
Yes, they have equivalent settings.

**Comment by kutsyk** [comment]
@johngmyers , could you point me to this config, please?
I can't find anything in the doc, on how to define it

**Comment by kutsyk** [comment]
Checking API and don't see it there - https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#KubeControllerManagerConfig

**Comment by johngmyers** [comment]
Yeah, KCM doesn't appear to have those fields. PRs welcome!
