### ISSUE TITLE
Validate instance type earlier

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#157]
Same type thing as #76:

`F0717 10:37:36.182421   59916 create_cluster.go:52] error running tasks: did not make any progress executing task.  Example error: instance type not handled: "c2.xlarge"`

**Comment by zapman449** [comment]
I did something dumb.  My mistake.

**Comment by justinsb** [comment]
Typo in instance type name?  I should validate those earlier!

Will reopen to track that improvement.

**Comment by chrislovecnm** [comment]
@kris-nova do you know if "c2.xlarge" instance is supported?

**Comment by kris-nova** [comment]
`c3.xlarge` is a valid instance size.. archiving..

**Comment by justinsb** [comment]
The idea would be to validate this earlier.

We should also validate that e.g. you're not trying to use `maxPrice` with a `t2` instance type.  I make that mistake at least once a week.

**Comment by chrislovecnm** [comment]
Stability

**Comment by chrislovecnm** [comment]
Closing
