### ISSUE TITLE
e2e-kops-aws-updown flakes due to t6g unavailability

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#15732]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master branch

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.27.4

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

https://testgrid.k8s.io/kops-k8s-stable#kops-aws-updown

**5. What happened after the commands executed?**

Tests are flaking due to being assigned to AWS zones without any t6g.medium availability. Such zones I've found are `us-east-1e` and `ap-northeast-2d`

**6. What did you expect to happen?**

Tests to pass

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I suspect but cannot confirm that those zones don't have any ARM instance types. I suspect we want
to remove those zones from the default set in https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_e2e.py#L39

/cc @justinsb

**Comment by hakman** [comment]
@johngmyers Is it by any chance t4g?

**Comment by johngmyers** [comment]
Yeah, t4g
/close
