### ISSUE TITLE
TagLimitExceeded when creating multiple clusters with more than a combined total of 50 instance-groups 

### ISSUE THREAD

**Issue by allenmunC1** [kubernetes/kops#15738]
/kind bug

Currently we are running into an issue where our subnets are being tagged with over 50 tags when `kops update cluster` is ran.  We believe this is caused from a change from kops1.25 where the subnets are being tagged with the instance-group name here
https://github.com/kubernetes/kops/blob/master/pkg/model/awsmodel/network.go#L267

We currently have over 50 instance-groups in our cluster and are unable to update our clusters when moving from kops1.23.2 -> kops1.26.3.  

Since this change seems to come from this [PR](https://github.com/kubernetes/kops/commit/8bcc640452dba5c58691f13e54adb98317b91ed7), a solution may just be to have an `if b.Cluster.Spec.Karpenter.Enabled {` surrounding the tagging block as this seems to only be required from karpenter. 

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Client version: 1.26.3
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:40:59Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
**3. What cloud provider are you using?**
aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update cluster.  This issue can be reproduced by spinning up a kops cluster with 50+ instance-groups
**5. What happened after the commands executed?**
We get an error 
```
error adding tags to resource "subnet-<subnet_id>": error creating tags on subnet-<subnet_id>: TagLimitExceeded: The resultant tag set must not have more than 50 user tags.
```

This error seems to be caused from here: https://github.com/kubernetes/kops/blob/master/pkg/model/awsmodel/network.go#L267
```
			for _, ig := range b.InstanceGroups {
				for _, igSubnetName := range ig.Spec.Subnets {
					if subnetSpec.Name == igSubnetName {
						tags["kops.k8s.io/instance-group/"+ig.GetName()] = "true"
					}
				}
			}
```
where the instance-groups are being added to the subnet, but since we have a multitude of instance-groups too many tags are being added passing the hard-limit of 50 tags on one subnet.
**6. What did you expect to happen?**
I expected the cluster to spin up with all instance-groups
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

This should just be a standard kops cluster, our configuration is quite large as it has over 50 instance-groups

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
  These logs are from our jenkins pipeline used to spin up kops clusters
```
09:27:09  I0803 13:27:09.001553     565 executor.go:111] Tasks: 161 done / 602 total; 10 can run
09:27:09  W0803 13:27:09.402509     565 aws_cloud.go:1316] Uncategorized error in isTagsEventualConsistencyError: TagLimitExceeded
09:27:09  W0803 13:27:09.402590     565 executor.go:139] error running task "Subnet/us-east-1d.<cluster_name>" (9m59s remaining to succeed): error adding tags to resource "subnet-<subnet_id>": error creating tags on subnet-<subnet_id>: TagLimitExceeded: The resultant tag set must not have more than 50 user tags.
09:27:09  	status code: 400, request id: <request_id>
```
**9. Anything else do we need to know?**

**Comment by johngmyers** [comment]
I think I'd be in favor of only tagging subnets with IGs when using Karpenter. The tagging does have some interesting implications for shared subnets, as the cluster name is not in the tag key.

A workaround would be to disable `TagSubnets`.
