### ISSUE TITLE
split out network creation in kops

### ISSUE THREAD

**Issue by hollowimage** [kubernetes/kops#1576]
feature idea:

`kops create network  --flags`

will create the underlying network, similar to initial stages of `kops create cluster`

with all terraform outputs, and the such. this will allow for more flexible management of cluster vs resources at a low level, allow for security/network auditing, and other forms of special use-cases where groundwork needs to be separately from actual cluster up.

**Comment by chrislovecnm** [comment]
@justinsb why the P0 flag? Do we have something broken?

**Comment by chrislovecnm** [comment]
I am torn about this. We are not terraform ;( We provide a recommended configuration. If you specialized network layout, I would recommend deploying to a preconfigured vpc

**Comment by hollowimage** [comment]
kops does this anyway: cops create cluster 1 creates network, 2 creates cluster.

i am just saying split this out into its own step so that you could pre-create the networking layer first alone, and then have it be audited, for instance, for design issues. as it stands now, deploying with kops into a preconfigured vpc is a nightmare especially if you're subject to security audits, which lock down a lot of things that kops assumes by default.

having this be its own step, 1. allows you to create and validate the network design, allows to easier figure out the actual networking architecture the cluster needs so that you can make it work with yours.

in reverse, this will make deleting clusters from a shared environment much much easier: `delete cluster --name name --preserve-network true` or something like that, and can potentially remove tagging pressure :)

**Comment by chrislovecnm** [comment]
Phases and lifecycles will help with this.  Working out those details now.

/assign

**Comment by rifelpet** [comment]
This can be achieved with phases.

`kops update cluster --phase network ${CLUSTER_NAME}` will only manage the network related cloud resources.

/close
