### ISSUE TITLE
Deleled the load balancing for master node by accident

### ISSUE THREAD

**Issue by songoten28** [kubernetes/kops#15771]
/kind feature

Hello everyone

I accidentally deleted the LoadBalancer for the master node due to an accident. After that, when I used the command:

```kops export kubecfg --admin --name $NAME```

and using `kubectl get pods -A`
it resulted in an error:

Unable to connect to the server: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local ..., not api-k8s-xx-xx-k8s-loc-xxxxxxx-xxxxxxxxxx.ap-southeast-1.elb.amazonaws.com.

Upon checking the load balancing, I found that Kops had recreated a new load balancer for me that matches the address mentioned above. (api-k8s-xx-xx-k8s-loc-xxxxxxx-xxxxxxxxxx.ap-southeast-1.elb.amazonaws.com.)

Currently, I am using the `--insecure-skip-tls-verify=true` flag to access my cluster, which is quite risky.

I'm not sure if there is any way to fix this issue.

**Comment by johngmyers** [comment]
To fix this, do a rolling update of your control plane.

**Comment by songoten28** [comment]
@johngmyers 
 it's working
thank you so much
