### ISSUE TITLE
KOPS 1.5 creates title cased taints where KOPS 1.4 creates lowercased taints

### ISSUE THREAD

**Issue by rcoh** [kubernetes/kops#1579]
KOPS version:
https://github.com/kubernetes/kops/releases/tag/1.5.0-alpha3

Steps to reproduce:
1. Deploy a cluster with dedicated master taints

Old behavior:
Taint keys are lowercase: `{"key": "...", "value": "...", "effect": "..."}`
New behavior:
Taint keys are uppercase: `{"Key": "...", "Value": "...", "Effect": "..."}`

The taint keys should be lower case to maintain backwards compatibility and to be consistent with other JSON with k8s.

This comes because of a change to remove the JSON serializers from the kube internal classes. https://github.com/kubernetes/kubernetes/issues/39847 describes the fix to fix the issue for kubectl on master.

**Comment by justinsb** [comment]
Thanks @rcoh - we'll make sure this is fixed

**Comment by justinsb** [comment]
Indeed, we need to get alpha4 out asap (cc @kris-nova )

It should be fixed ... with the branch that will likely be alpha4:

```
scheduler.alpha.kubernetes.io/taints: '[{"key":"dedicated","value":"master","effect":"NoSchedule"}]'
```

**Comment by justinsb** [comment]
Closing - verified fixed in beta1.  Thank you for finding this @rcoh!
