### ISSUE TITLE
Wrong subnet for DNS #aws

### ISSUE THREAD

**Issue by noose** [kubernetes/kops#158]
Hi! 
I used kops to create cluster
```bash
kops create cluster --v=1 --cloud=aws --zones=us-west-1c,us-west-1b --master-zones=us-west-1c --state $KOPS_STATE_STORE --name $NAME
```
Cluster is ready and I can use it. But…
Containers subnets: `100.​*96*​.x.x/16` (default from kops)
Containers /etc/resolv.conf: `100.​*64*​.x.x/16` (default from kubernetes? kops?)

So my cluster is dead, because containers doesn’t have proper dns config. What should I do now? :)
I believe that's related to https://github.com/kubernetes/kubernetes/issues/28139
(x-post from slack)

**Comment by justinsb** [comment]
I believe we discussed this and determined the setup you had was actually correct.  If not, please reopen / ping me!
