### ISSUE TITLE
Version documentation with release

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1583]
I have been waiting to drop this issue for a while.. but I think we will be there **after** `1.5.0` ships..

But we **probably** should start thinking about this now..

Right now we have have documentation that lives in `/docs` (which is great, don't get me wrong) but it might be meaningful to start versioning our documentation.. either with [godoc](https://godoc.org/k8s.io/kops) or even in the repo.. or maybe even a **website**! 

This would probably be very meaningful as we could dump our current docs into the `1.5.0` bucket, and cherry pick documentation for the next release.. 

Also.. this will prevent things like `--topology` not found.. from being reported anymore (hopefully)

Thoughts? Design input please!

CC @frodopwns @justinsb @chrislovecnm @evildandelions @geojaz

**Comment by justinsb** [comment]
Agreed - we should figure out what we want to do about the current "release" branch - does it become release-1.4 (like k8s).  I think with kops we can encourage people much more strongly than k8s does to update to the latest version; I don't know if we would encourage anyone to run the kops 1.4 series once kops 1.5 is out.  There is a challenge in the fact that the "stable channel" yaml doesn't currently have per-k8s-version recommendations, and we would ideally the 1.4 image for k8s 1.4.  

But then that commits us to building both 1.4 and 1.5 images, which is _ok_ but not great.

**Comment by geojaz** [comment]
I think Justin has a really good point and as a team we need to seriously consider our plans. I personally think that there's no real compelling reason to maintain 1.4.x once 1.5 is out. Even if you are interested in deploying and managing 1.4 series kube clusters, I would still recommend using kops 1.5 to do it. Maybe we can 

Justin's comment is related to @kris-nova's issue, but I think her point is really important and it needs to be discussed. Regardless of versioning, we have a perpetual need for real docs and I would be very interested to consider having an actual docs website. It doesn't need to be as fancy as kubernetes.github.io, but as this project grows, having docs hidden in github gets more difficult.

For versioning docs, I think I generally support it, if it's relatively easy to just freeze our docs on a version and say that's it. I think if we had docs for a version at one point, if that user really feels the need to run an old version and at one point we had those docs, it's a pain for them to not have the docs that used to exist. Maybe it's not important. I think most important is developing docs and creating better visibility around them- and for me that's a website.

**Comment by zytek** [comment]
+1 on improving docs visibility/discoverability, but with minimum maintenance overhead.

maybe something along https://readthedocs.org/ ?

**Comment by chrislovecnm** [comment]
I think released docs should by up on the k8s web site, and we need a notice that can be munged out to look at the tag in github... something like that ... don't want to mess with them on master.

**Comment by kris-nova** [comment]
So we are planning a formal discussion on documentation next week on the kops office hour call.. I would really like this issue to be one of the things we discuss!

**Comment by justinsb** [comment]
Cool - labeling as documentation!

**Comment by geojaz** [comment]
/close

closing because this issue is not visible due to being last active so long ago and referring to meetings that happened more than 6 months ago with no obvious action items. 

I will open issues for actionable docs work as I see it.
