### ISSUE TITLE
Allow k8s version to be set per InstanceGroup

### ISSUE THREAD

**Issue by timstoop** [kubernetes/kops#15840]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

We would love to be able to set a Kubernetes version per instance group. The control plane itself supports workers from up to three minors lower than the control plane themselves (and as of 1.28, four minors lower). Being able to set (or override) the version per instance group would allow us to upgrade the control planes without bouncing the workers and to set up an additional IG using the newer k8s version. Users of the cluster would then be able to use a nodeSelector and a toleration to move specific Pods to the IG using the newer version to test if it runs into issues. Once everything passes QA, the workers can then either be bounced or their IGs can be changed to use the new version, so they get slowly replaced over time.

This feature would enhance the upgrade experience for users of the cluster, as the Kubernetes API resources do change pretty frequently and although the changelog is generally well kept, the additional step of testing would improve confidence in upgrades.

For control planes this would be less of an issue, as one generally does not have workloads running on the control plane except for the, well, control plane Pods.

The alternative solution would be to set up a new cluster (which admittedly is easy with kops), but this is often a burden for developers, as they would have to migrate data and/or redeploy their applications. Making it easy for them to test on the same cluster would ensure testing is less of a chore.

It would also save some infrastructure cost if this would be possible.

**2. Feel free to provide a design supporting your feature request.**

I expect a simple `spec.kubernetesVersion`, similar to the Cluster resource, would suffice for this.

**Comment by johngmyers** [comment]
This seems unlikely to be that helpful. As soon as the control plane is upgraded, workloads will be affected by Kubernetes API removals. This would only help if a workload depended on being on an older version of kubelet, which seems quite unlikely.

**Comment by rifelpet** [comment]
Allowing the control plane hosts to be rotated before updating the node LaunchTemplates would avoid help kops' race condition that breaks the [kubelet version skew policy](https://kubernetes.io/releases/version-skew-policy/#kubelet).

After `kops update cluster --yes` but before _all_ control plane hosts are rotated, newer kubelets can be connecting to older kube-apiservers which violates the policy. [KEP-4020](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/4020-unknown-version-interoperability-proxy) will reduce but not eliminate this race condition.
