### ISSUE TITLE
Restrict access between instance groups

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kops#1586]
Currently all the Nodes share the same security group which holds a default security-group rule allowing all traffic to itself, meaning that all the nodes from all instance groups are open on all ports to all the other nodes.
IMO it seems like a security risk.
Since we are about to add support for additional security groups (#1585)  and since we can't pass the default security group, I find that we should add a flag specifying if we will create the "self traffic" rule.

WDYT?

**Comment by chrislovecnm** [comment]
Would restricting traffic between nodes stop pod -> service communitcation and pod to pod communication?

**Comment by chrislovecnm** [comment]
I am wondering if you are looking for network policies instead of security groups

**Comment by vendrov** [comment]
Network policies is a great solution, But it's less "strong" and Sec will insist on good old SG isolation.

**Comment by chrislovecnm** [comment]
Yah with services this would be interesting. I think that network policies are the way to go. Ideas?
