### ISSUE TITLE
Kop delete cluster fails in deleting root volume

### ISSUE THREAD

**Issue by KaiyuWei** [kubernetes/kops#15867]
I ran `kops delete cluster --name=kubevpro.quickesh.com --state=s3://ky-bucket-kops --yes` and I got some message like:
```
volume:vol-09f983a5b5901523d	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	volume:vol-09f983a5b5901523d
```
Then I checked by the volume Id and found that this volume is a root cluster of the EC2 instance. 

**What I have tried**
Detach the volume and it failed: **vol-09f983a5b5901523d: Unable to detach root volume 'vol-09f983a5b5901523d' from instance 'i-033fc4bd0222716a3'**

**Comment by KaiyuWei** [comment]
> Your problem is that the instance is still not deleted.

@hakman But the EC2 instance is what I used for launching the cluster, and I still want to keep the instance. If I delete the instance the cluster will definitely be deleted as well. But how can I solve the problem, deleting the cluster, while keep the instance?

**Comment by justinsb** [comment]
Deleting the cluster will delete all the resources, including the instances, so this isn't really something that is supported by `kops delete cluster`.

Can you describe why you want to keep the instance (while deleting the cluster)?
