### ISSUE TITLE
Ability to change version of container images deployed by kops e.g. amazon-k8s-cni

### ISSUE THREAD

**Issue by wlawton** [kubernetes/kops#15883]
/kind feature

I recently upgraded a dev k8s cluster to kubernetes v1.27.4 using kops 1.27.0. Since then i'm facing an issue with aws-node pods crash looping due to some compatibility with promethus-adapter as described here https://github.com/aws/amazon-vpc-cni-k8s/issues/2393. The issue is resolved in amazon-k8s-cni version 1.13.2 and above, but KOPS has installed amazon-k8s-cni v1.12.6. Is it possible to change the version of amazon-k8s-cni that KOPS installs?

**Comment by hakman** [comment]
You should be able to use `image` and `initImage` to set a different version:
https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#AmazonVPCNetworkingSpec
/kind support
