### ISSUE TITLE
Any way of disabling "UseInstanceIDForNodeName"?

### ISSUE THREAD

**Issue by shapirus** [kubernetes/kops#15891]
**Environment:**

- AWS
- fresh cluster install
- cluster built via eddycharly/terraform-provider-kops v1.26.0-alpha1, using (as far as I can tell) kops 1.26.3
- k8s 1.26.8

**Actual behavior:**

nodes' `metadata.name` fields are set to to the EC2 instance ID (`i-xxxxxxxxxxxxxxxxx`).

**Expected behavior** (which I observe in my older clusters, running k8s 1.21 with kops 1.21, under the same AWS account):

nodes' `metadata.name` fields are set to to the EC2 instance's `PrivateDnsName` attribute, which can also be seen in the output of the respective host's `hostname -f` command.

There seem to be no entries that could affect this in the cluster definition when viewed by the `kops` CLI utility.

I believe this is the commit that broke the original behavior: https://github.com/kubernetes/kops/commit/73f164e229b16610768aa48221a65eb889891488

Is there any way to restore the original behavior with kops 1.26.3? Having instance ids as node names is rather inconvenient to say the least.

**Comment by hakman** [comment]
Duplicate of https://github.com/kubernetes/kops/issues/14035

**Comment by shapirus** [comment]
Closed for being duplicate.
