### ISSUE TITLE
Don't try to change names for VPC / IGW on upgrade

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#159]
It's confusing (and I don't think we actually do it, anyway)

**Comment by chrislovecnm** [comment]
Is this fixed?

**Comment by yissachar** [comment]
@justinsb I assume this is related to https://github.com/kubernetes/kops/issues/476?

**Comment by justinsb** [comment]
Thanks @yissachar - #476 is a much better description of the issue.  Closing this one.
