### ISSUE TITLE
Kube controller manager flag `--experimental-cluster-signing-duration` is removed in Kubernetes 1.25+

### ISSUE THREAD

**Issue by mmckeen** [kubernetes/kops#15909]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`1.25.3`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`1.25.13`

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops rolling-update`

**5. What happened after the commands executed?**

New `kube-controller-manager` pods are crashing with an error:

```
kube-controller-manager-i-0bbd36ac2c0e8173d kube-controller-manager Error: unknown flag: --experimental-cluster-signing-duration
```

**6. What did you expect to happen?**

The new `kube-controller-manager` pod comes up healthy.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Kubernetes has removed the `--experimental-cluster-signing-duration` flag post version 1.25, kops still references the old flag (https://github.com/kubernetes/kops/blob/e31bf381abe96d7cb7e47b9afe6873e549abc1c9/pkg/apis/kops/componentconfig.go#L618) and doesn't support configuring the new version.

The new version is `--cluster-signing-duration` https://github.com/kubernetes/kubernetes/commit/a444eb60d7fef4388644ed03a1fa20a94fbb3a3a.

**Comment by mmckeen** [comment]
Any update on this? 🙇

**Comment by hakman** [comment]
Hi @mmckeen. `--cluster-signing-duration` was added to kOps 1.27 and 1.28 and should be available in the next releases.
Leaving this open for @justinsb in case he wants to add more validation.

**Comment by mmckeen** [comment]
@hakman thank you!

**Comment by justinsb** [comment]
I also proposed some best-effort validation for this in #16062.  We don't really want to do full validation of these "custom options", but it feels like it's relatively easy to provide a pointer to the new flag name here.  I don't know if we think it's worth backporting, but it's nice to have the validation mechanism here at least (IMO)
