### ISSUE TITLE
When using useServiceAccountExternalPermissions, dns-controller can only edit one zone

### ISSUE THREAD

**Issue by dobesv** [kubernetes/kops#15905]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

v1.27.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.27.4

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Configure a kops managed cluster on AWS with `useServiceAccountExternalPermissions` enabled

**5. What happened after the commands executed?**

After the cluster was all set up, it created a role for `dns-controller` like this:

```
{
    "Statement": [
        {
            "Action": [
                "route53:ChangeResourceRecordSets",
                "route53:ListResourceRecordSets",
                "route53:GetHostedZone"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:route53:::hostedzone/Z2Q5ZKR79RGMO"
            ]
        },
        {
            "Action": [
                "route53:GetChange"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:route53:::change/*"
            ]
        },
        {
            "Action": [
                "route53:ListHostedZones",
                "route53:ListTagsForResource"
            ],
            "Effect": "Allow",
            "Resource": [
                "*"
            ]
        }
    ],
    "Version": "2012-10-17"
}
```

This only allows `dns-controller` to edit a single zone.  However, I want `dns-controller` to be able to edit several zones.

**6. What did you expect to happen?**

Prior to using `useServiceAccountExternalPermissions` I had set the policy for the nodes' role to allow changes to all DNS entries in Route 53.

I would either want `dns-controller` to have access to all zones, or be able to specify which zones it can access.

Or if there's already a way to work around this, I would want that to be mentioned in the documentation.

**Comment by mzeeshan1** [comment]
I am facing same issue. The policy specifies a single resource and dns-controller does not have permission to ListResourceRecordSets in another hosted zone. I tried using `serviceAccountExternalPermissions` for this but it fails as same policy has already been created before.

**Comment by dobesv** [comment]
My workaround was to manually attach another inline policy to the role.  It seems like `kops` does not remove the additional policy from the role, so this works OK.
