### ISSUE TITLE
unknown flag: --attach-detach-reconcile-sync-period

### ISSUE THREAD

**Issue by airstand** [kubernetes/kops#1591]
Hi,
@kris-nova & @justinsb :)
I have spin up new cluster with kops 1.5.0-alpha4.
I saw that nodes are not join the cluster.
The issue is with kube-controller-manager : unknown flag: --attach-detach-reconcile-sync-period
You can see more details in the attached output below:

kubectl -n kube-system get pods
NAME                                                                 READY     STATUS             RESTARTS   AGE
etcd-server-events-ip-10-0-122-238.us-west-2.compute.internal        1/1       Running            0          15m
etcd-server-events-ip-10-0-52-236.us-west-2.compute.internal         1/1       Running            0          13m
etcd-server-events-ip-10-0-88-38.us-west-2.compute.internal          1/1       Running            0          14m
etcd-server-ip-10-0-122-238.us-west-2.compute.internal               1/1       Running            0          15m
etcd-server-ip-10-0-52-236.us-west-2.compute.internal                1/1       Running            0          13m
etcd-server-ip-10-0-88-38.us-west-2.compute.internal                 1/1       Running            0          14m
kube-apiserver-ip-10-0-122-238.us-west-2.compute.internal            1/1       Running            2          13m
kube-apiserver-ip-10-0-52-236.us-west-2.compute.internal             1/1       Running            2          13m
kube-apiserver-ip-10-0-88-38.us-west-2.compute.internal              1/1       Running            0          15m
kube-controller-manager-ip-10-0-122-238.us-west-2.compute.internal   0/1       CrashLoopBackOff   8          15m
kube-controller-manager-ip-10-0-52-236.us-west-2.compute.internal    0/1       CrashLoopBackOff   7          14m
kube-controller-manager-ip-10-0-88-38.us-west-2.compute.internal     0/1       CrashLoopBackOff   7          15m
kube-proxy-ip-10-0-122-238.us-west-2.compute.internal                1/1       Running            0          14m
kube-proxy-ip-10-0-52-236.us-west-2.compute.internal                 1/1       Running            0          13m
kube-proxy-ip-10-0-88-38.us-west-2.compute.internal                  1/1       Running            0          15m
kube-scheduler-ip-10-0-122-238.us-west-2.compute.internal            1/1       Running            0          14m
kube-scheduler-ip-10-0-52-236.us-west-2.compute.internal             1/1       Running            0          13m
kube-scheduler-ip-10-0-88-38.us-west-2.compute.internal              1/1       Running            0          15m

kubectl get nodes
NAME                                         STATUS         AGE
ip-10-0-122-238.us-west-2.compute.internal   Ready,master   19m
ip-10-0-52-236.us-west-2.compute.internal    Ready,master   19m
ip-10-0-88-38.us-west-2.compute.internal     Ready,master   19m

root@ip-10-0-122-238:~# cat /var/log/kube-controller-manager.log | grep -i unknown
unknown flag: --attach-detach-reconcile-sync-period

**Comment by kris-nova** [comment]
Thanks for the report - I will start looking into this ASAP!

**Comment by kris-nova** [comment]
Can you share your create command?

**Comment by chrislovecnm** [comment]
I have a logic bug https://github.com/kubernetes/kops/blob/master/pkg/model/components/kubecontrollermanager.go#L76

1.5.1 is gte 1.4.8 ... I need to test the minor version
