### ISSUE TITLE
KubeDNS version is too old

### ISSUE THREAD

**Issue by upodroid** [kubernetes/kops#15918]
/kind bug

KubeDNS version is too old. We are running `registry.k8s.io/k8s-dns-kube-dns:1.15.13` when upstream is using `registry.k8s.io/dns/k8s-dns-kube-dns:1.22.23`

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kube-dns/kube-dns.yaml.base

**Comment by hakman** [comment]
Is kube-dns still maintained?

**Comment by upodroid** [comment]
yes

https://github.com/kubernetes/kubernetes/commits/master/cluster/addons/dns/kube-dns/kube-dns.yaml.base
https://github.com/kubernetes/dns/releases
