### ISSUE TITLE
Kops  cluster "ImagePullBack Issue"

### ISSUE THREAD

**Issue by TheDevrajDas** [kubernetes/kops#15942]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.21.0 

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: 1.18.9
Server Version: 1.21

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops edit cluster my-cluster #added the version i want to upgrade to
kops update cluster --name=my-cluster
kops update cluster --name=my-cluster --yes
kops rolling-update cluster --name=my-cluster --yes
kops cluster validate

**5. What happened after the commands executed?**
kops cluster upgraded successfully. But the pods when getting assigned to the new nodes, i am getting image pull back error.
error:
`Failed to pull image "harbor.xyz.com/xyz-service/xyz-service:0.0.133": rpc error: code = Unknown desc = failed to pull and unpack image "harbor.xyz.com/xyz-service/xyz-service:0.0.133": failed to resolve reference "harbor.xyz.com/xyz-service/xyz-service:0.0.133": failed to authorize: failed to fetch oauth token: unexpected status: 403 Forbidden`
On the older nodes everything is working fine.
i also did `kops create secret dockerconfig ` and mentioned the json file with the creds.

**6. What did you expect to happen?**
The cluster should have pulled the images from the repo without any error as the images are already present on the machines and cluster.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-10-22T05:46:42Z"
  generation: 5
  name: my-solar-service.treo.com
spec:
  additionalPolicies:
    node: |
      [
        {
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "ec2:DescribeLaunchTemplateVersions",
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:DescribeKey"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
      ]
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://my-solar-service-kops-state-store/my-solar-service.treo.com
  dnsZone: my-solar-service.treo.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-southeast-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-southeast-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.21.14
  masterInternalName: api.internal.my-solar-service.treo.com
  masterPublicName: api.my-solar-service.treo.com
  networkCIDR: x.x.x.x
  networkID: vpc-x.x.x
    calico: {}
  nonMasqueradeCIDR: x.x.x.x
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: x.x.x.x
    id: subnet-x.x.x
    name: ap-southeast-1a
    type: Private
    zone: ap-southeast-1a
  - cidr: x.x.x.x
    id: subnet-x.x.x
    name: ap-southeast-1b
    type: Private
    zone: ap-southeast-1b
  - cidr: x.x.x.x
    id: subnet-x.x.x.x
    name: ap-southeast-1c
    type: Private
    zone: ap-southeast-1c
  - cidr: x.x.x.x
    id: subnet-x.x.x.x
    name: utility-ap-southeast-1a
    type: Utility
    zone: ap-southeast-1a
  - cidr: x.x.x.x
    id: subnet-x.x.x.x
    name: utility-ap-southeast-1b
    type: Utility
    zone: ap-southeast-1b
  - cidr: x.x.x.x
    id: subnet-x.x.x.x
    name: utility-ap-southeast-1c
    type: Utility
    zone: ap-southeast-1c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-10-22T05:46:42Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: my-solar-service.treo.com
  name: master-ap-southeast-1a
spec:
  image: ami-x.x.x.x
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    Team: solar
    kops.k8s.io/instancegroup: master-ap-southeast-1a
  role: Master
  rootVolumeSize: 70
  subnets:
  - ap-southeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-10-22T05:46:42Z"
  generation: 5
  labels:
    kops.k8s.io/cluster: my-solar-service.treo.com
  name: my-solar-nodes
spec:
  cloudLabels:
    Team: solar
    product: my-solar-service
  image: ami-x.x.x.x
  machineType: t3a.xlarge
  maxSize: 10
  minSize: 1
  nodeLabels:
    Team: solar
    kops.k8s.io/instancegroup: my-solar-nodes
  role: Node
  rootVolumeSize: 70
  subnets:
  - ap-southeast-1a
  - ap-southeast-1b
  - ap-southeast-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-10-22T05:46:42Z"
  generation: 5
  labels:
    kops.k8s.io/cluster: my-solar-service.treo.com
  name: solar-sg-shared
spec:
  cloudLabels:
    Team: solar
    product: my-solar-service
  image: ami-x.x.x.x
  machineType: t3a.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    Team: solar
    kops.k8s.io/instancegroup: solar-sg-shared
  role: Node
  rootVolumeSize: 70
  subnets:
  - ap-southeast-1a

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by SCLogo** [comment]
we are facing with the same issue. What we see is on the good instance the docker config file exists and can see in the log that nodeup downloaded that file. 
on wrong instance, the file does not exits and cannot find any lines related to the docker config.

**Comment by SCLogo** [comment]
with additional script we could solve temporary the issue:

```

  - content: |
      #!/bin/sh
      while [ ! -f /root/.docker/config.json ]
      do
        systemctl restart kops-configuration
        sleep 2
      done
      systemctl restart containerd
      systemctl restart kubelet
    name: sfinalcheck.sh
    type: text/x-shellscript
    
    ```

**Comment by TheDevrajDas** [comment]
thanks...let me try that out

**Comment by TheDevrajDas** [comment]
@SCLogo i checked, in my case the docker config file exists in all the nodes. 
i even tried comenting out the  
```
imagePullSecrets:
 - name: harbor-secret
``` 
as its a public repo.
but stll same

**Comment by SCLogo** [comment]
> @SCLogo i checked, in my case the docker config file exists in all the nodes. i even tried comenting out the
> 
> ```
> imagePullSecrets:
>  - name: harbor-secret
> ```
> 
> as its a public repo. but stll same

DId you create the folder and the extra config ?
