### ISSUE TITLE
Enhance message when improper CIDR given (or default /32 if appropriate)

### ISSUE THREAD

**Issue by matthewadams** [kubernetes/kops#1595]
Enhance the error messaging when a user does not give a proper CIDR where expected.

In my case, it was during execution of `kops create cluster ... --admin-access 12.34.56.78 ...`.  I inadvertently gave just an IP address, instead of a CIDR.  Message was
```
SSHAccess rule "12.34.56.78" could not be parsed (invalid CIDR)
```
Alternatively, if appropriate, the default suffix `/32` could be inferred.

**Comment by chrislovecnm** [comment]
You able to help out with this?

**Comment by justinsb** [comment]
Once #1601 merges, I have a PR waiting to implement this...
