### ISSUE TITLE
Incorrect `topologySpreadConstraints` label selector for Karpenter controller deployment

### ISSUE THREAD

**Issue by danports** [kubernetes/kops#15959]
Follow up from #15046 since #15916 didn't address this issue:

> Additionally the controller deployment is using the wrong `topologySpreadConstraint` key (`webhook` instead of `controller`):
> 
> https://github.com/kubernetes/kops/blob/3bafdc414288b7525bbdf67e93d6ccfa5bde091d/upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template#L948-L960

I suspect this is an issue with the upstream Helm chart since the kOps manifest is just generated with `helm template`, probably with the [relatively complex Helm template helper](https://github.com/aws/karpenter/pull/3559) used to generate the `topologySpreadConstraints`.

**Comment by hakman** [comment]
Should be pretty easy to fix on the kOps side, but I would also recommend to raise an issue with Karpenter.
