### ISSUE TITLE
Install crictl/nerdctl on kops nodes

### ISSUE THREAD

**Issue by upodroid** [kubernetes/kops#15969]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
crictl/nerdctl allow you to debug containerd easily

**2. Feel free to provide a design supporting your feature request.**

**Comment by hakman** [comment]
Seems like a good idea. Not very hard to do.

**Comment by hakman** [comment]
Most of the work was done by @h3poteto. Thank you!
/remove-lifecycle rotten
