### ISSUE TITLE
doc(docs/cluster_spec): fix url reference

### ISSUE THREAD

**Issue by ana-aguilar7** [kubernetes/kops#15966]
/kind documentation

On the Release Notes page at https://github.com/kubernetes/kops/releases/tag/v1.28.0, the link for "hooks" is incorrect. It currently points to https://github.com/kubernetes/kops/blob/v1.28.0/cluster_spec/#hooks.

The correct link should be https://github.com/kubernetes/kops/blob/v1.28.0/docs/cluster_spec.md#hooks.

**Comment by hakman** [comment]
Thanks for letting us know about this. I updated the link to point to https://kops.sigs.k8s.io/cluster_spec/#hooks.
