### ISSUE TITLE
Improve time for new cluster to pass validation

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#15961]
/kind feature

Using [this](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/) prow job as reference.

I'm looking into the time for a new cluster to pass validation and there are a few slow spots that we might be able to improve:

* Depending on the region, containerd can be slow to download ([example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/journal.log)) 

  `Sep 23 16:20:45.953374 i-04cb3757a26791415 nodeup[1377]: I0923 16:20:45.953327    1377 http.go:121] Copying "https://github.com/containerd/containerd/releases/download/v1.7.2/containerd-1.7.2-linux-arm64.tar.gz" to "/var/cache/nodeup/sha256:d75a4ca53d9addd0b2c50172d168b12957e18b2d8b802db2658f2767f15889a6_containerd-1_7_2-linux-arm64_tar_gz" took "1m8.974354228s"`
  1m8s to download a 30MB binary is slower than expected, especially for these `c6g.xlarge` control plane instances. I wonder if these could be hosted on one of the new k8s infra CDNs?

* etcd-manager container restarts at least 5 times ([example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/kubelet.log))
  `I0923 16:23:54.336165    3381 kubelet.go:2421] "SyncLoop (PLEG): event for pod" pod="kube-system/etcd-manager-main-i-04cb3757a26791415" event={"ID":"7043601e95c4de0ec81dc6ffc084ff71","Type":"ContainerDied","Data":"0829eecb3f90b1d6e8a395a7ca4b649cea20f0b9c47f30a2daa2897c3eb7c542"}`
  which delays apiserver by at least 20 seconds (and apiserver is already in CLB so theres likely additional time before both are healthy) though whats interesting is that `k get pods` [doesn't report any restarts](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/cluster-info/kube-system/pods.yaml) for any of the etcd-manager pods' containers. Unfortunately we only have [logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/etcd.log) from the most recent process, so why it died isn't in the prow artifacts.

* dns-controller doesn't get scheduled until 45s after apiserver is running ([example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/kube-apiserver.log) and [example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/kubelet.log))

  ```
  # apiserver
  I0923 16:24:46.429300      11 server.go:148] Version: v1.28.2`

  #kubelet  
  I0923 16:25:13.376595    3381 kubelet.go:2389] "SyncLoop ADD" source="api" pods=["kube-system/dns-controller-745fb5dd6f-jljzp"]
  ```
  While protokube applies the addon manifests within 10s of apiserver being up, KCM and scheduler are in their own crash loop backoffs until 16:25:13. The earlier we can get dns records updated, the sooner `kops validate cluster` gets more detailed feedback on the status of the cluster.

* When using karpenter, no nodes are launched until after karpenter is running, almost 10 minutes after the control plane's nodeup starts ([example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/journal.log) and [example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/cluster-info/kube-system/karpenter-57d9c455f-ww6nx/logs.txt))
  ```
  # journal
  Sep 23 16:18:08.327805 i-04cb3757a26791415 cloud-init[1319]: == nodeup node config starting ==

  # karpenter
  2023-09-23T16:27:53.496Z	INFO	controller.machine.lifecycle	launched machine	{"commit": "30fa8f3-dirty", "machine": "nodes-2rmqg", "provisioner": "nodes", "provider-id": "aws:///eu-west-3b/i-057a7a2a3e375d659", "instance-type": "t4g.small", "zone": "eu-west-3b", "capacity-type": "spot", "allocatable": {"cpu":"1930m","ephemeral-storage":"17Gi","memory":"1359Mi","pods":"11"}}
  ```

* Something odd is happening with nodeup's task execution ([example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/kops-configuration.log)). nodeup should execute [all unblocked tasks concurrently](https://github.com/kubernetes/kops/blob/b9d0eed797b519919f350d5341fb34b3c363ceff/upup/pkg/fi/executor.go#L192-L201), yet there are `File` tasks that aren't ran until after the slower package installs, even though those File tasks have no other dependencies:
  ```
  I0923 16:21:42.680546    1377 topological_sort.go:79] Dependencies:
  I0923 16:21:42.680976    1377 topological_sort.go:81] 	File//srv/kubernetes/kube-apiserver:	[File//srv/kubernetes]
  I0923 16:21:42.681124    1377 topological_sort.go:81] 	File//srv/kubernetes:	[]
  I0923 16:21:42.681290    1377 topological_sort.go:81] 	File//srv/kubernetes/kube-apiserver/etcd-ca.crt:	[File//srv/kubernetes/kube-apiserver File//srv/kubernetes]
  ...
  I0923 16:21:52.932620    1377 executor.go:112] Tasks: 104 done / 189 total; 43 can run
  ...
  I0923 16:22:31.623294    1377 package.go:281] Installing package "libapparmor1" (dependencies: [])
  I0923 16:22:31.623320    1377 package.go:339] running command [apt-get install --yes --no-install-recommends libapparmor1]
  I0923 16:22:32.162866    1377 executor.go:112] Tasks: 147 done / 189 total; 26 can run
  I0923 16:22:32.162919    1377 executor.go:210] Executing task "File//srv/kubernetes/kube-apiserver/etcd-ca.crt": File: "/srv/kubernetes/kube-apiserver/etcd-ca.crt"
  ```
  I dont understand why it waited until after package installs to execute the File tasks but we may be able to save time if we can get those to run earlier.

* Package installs take at least 40 seconds on Ubuntu 22.04:
  ```
  I0923 16:21:53.545187    1377 package.go:281] Installing package "socat" (dependencies: [])
  I0923 16:21:53.545215    1377 package.go:339] running command [apt-get install --yes --no-install-recommends socat]
  I0923 16:21:59.672246    1377 package.go:281] Installing package "iptables" (dependencies: [])
  I0923 16:21:59.672272    1377 package.go:339] running command [apt-get install --yes --no-install-recommends iptables]
  I0923 16:22:00.230581    1377 package.go:281] Installing package "logrotate" (dependencies: [])
  I0923 16:22:00.230607    1377 package.go:339] running command [apt-get install --yes --no-install-recommends logrotate]
  I0923 16:22:00.785106    1377 package.go:281] Installing package "cgroupfs-mount" (dependencies: [])
  I0923 16:22:00.785131    1377 package.go:339] running command [apt-get install --yes --no-install-recommends cgroupfs-mount]
  I0923 16:22:05.726235    1377 package.go:281] Installing package "bridge-utils" (dependencies: [])
  I0923 16:22:05.726261    1377 package.go:339] running command [apt-get install --yes --no-install-recommends bridge-utils]
  I0923 16:22:10.473171    1377 package.go:281] Installing package "unattended-upgrades" (dependencies: [])
  I0923 16:22:10.473197    1377 package.go:339] running command [apt-get install --yes --no-install-recommends unattended-upgrades]
  I0923 16:22:11.027250    1377 package.go:281] Installing package "chrony" (dependencies: [])
  I0923 16:22:11.027275    1377 package.go:339] running command [apt-get install --yes --no-install-recommends chrony]
  I0923 16:22:11.560120    1377 package.go:281] Installing package "libseccomp2" (dependencies: [])
  I0923 16:22:11.560144    1377 package.go:339] running command [apt-get install --yes --no-install-recommends libseccomp2]
  I0923 16:22:12.108927    1377 package.go:281] Installing package "ebtables" (dependencies: [])
  I0923 16:22:12.108951    1377 package.go:339] running command [apt-get install --yes --no-install-recommends ebtables]
  I0923 16:22:17.100247    1377 package.go:281] Installing package "pigz" (dependencies: [])
  I0923 16:22:17.100279    1377 package.go:339] running command [apt-get install --yes --no-install-recommends pigz]
  I0923 16:22:21.715831    1377 package.go:281] Installing package "util-linux" (dependencies: [])
  I0923 16:22:21.715859    1377 package.go:339] running command [apt-get install --yes --no-install-recommends util-linux]
  I0923 16:22:22.265425    1377 package.go:281] Installing package "libltdl7" (dependencies: [])
  I0923 16:22:22.265450    1377 package.go:339] running command [apt-get install --yes --no-install-recommends libltdl7]
  I0923 16:22:26.996559    1377 package.go:281] Installing package "conntrack" (dependencies: [])
  I0923 16:22:26.996586    1377 package.go:339] running command [apt-get install --yes --no-install-recommends conntrack]
  I0923 16:22:31.623294    1377 package.go:281] Installing package "libapparmor1" (dependencies: [])
  I0923 16:22:31.623320    1377 package.go:339] running command [apt-get install --yes --no-install-recommends libapparmor1]
  ```
  I wonder if it would be faster to merge these into one `apt-get install` command.

**Comment by johngmyers** [comment]
The `Task` scheduler sorts `Task`s into tranches according to the depth of their transitive dependencies. So tasks with no dependencies go into the first tranche. Those depending only on tasks in the first tranche go into the second tranche. Those depending only on tasks in the first and second tranche go into the third tranche, and so on.

The scheduler waits for all tasks in a tranche to complete before starting any tasks in the next tranche. So a slow task will delay the start of all tasks in later tranches.

I have thought of rewriting the scheduler to start a task as soon as all of its dependencies complete, but that increases the risk from missing dependencies.

**Comment by hakman** [comment]
> Depending on the region, containerd can be slow to download ([example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/journal.log))
1m8s to download a 30MB binary is slower than expected, especially for these c6g.xlarge control plane instances. I wonder if these could be hosted on one of the new k8s infra CDNs?

I remember a discussion but not sure how it ended. For sure k/k needs containerd for tests all the time.

> etcd-manager container restarts at least 5 times ([example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/kubelet.log))

I think some smarter task for /etcd/kubernetes/manifests would be nice. We could add some dependenices on etcd-manager(s) -> apiserver -> remaining static pods.

> dns-controller doesn't get scheduled until 45s after apiserver is running ([example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/kube-apiserver.log) and [example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/kubelet.log))

Maybe we should use `--dns=none` more.

> When using karpenter, no nodes are launched until after karpenter is running, almost 10 minutes after the control plane's nodeup starts ([example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/journal.log) and [example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/cluster-info/kube-system/karpenter-57d9c455f-ww6nx/logs.txt))

Not sure what can be done about Karpenter, except using `--dns=none`.

> Something odd is happening with nodeup's task execution ([example](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/kops-configuration.log)). nodeup should execute [all unblocked tasks concurrently](https://github.com/kubernetes/kops/blob/b9d0eed797b519919f350d5341fb34b3c363ceff/upup/pkg/fi/executor.go#L192-L201), yet there are File tasks that aren't ran until after the slower package installs, even though those File tasks have no other dependencies:

Files need to update packages configs in some cases, so they have to run after (IIRC).

> Package installs take at least 40 seconds on Ubuntu 22.04:

I think more of those packages can be removed.
Tests need to be run for all supported distros and all supported k8s versions.

> I wonder if it would be faster to merge these into one apt-get install command.

Tested a while ago, no benefits. Also task would become very complicated.

**Comment by rifelpet** [comment]
> Not sure what can be done about Karpenter, except using `--dns=none`.

We could create the Karpenter pod earlier somehow, rather than waiting for addon manifests to be applied.  I'm not sure how much time we could save here though without running Karpenter as a static pod.

I did notice that because the Karpenter addon manifest includes both a CRD and a CR of that CRD, [the first apply fails and protokube waits 1 minute until the next apply](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1705616628923764736/artifacts/i-04cb3757a26791415/protokube.log). protokube also needs the Karpenter pod to be running because of the CRD webhook. Maybe protokube could be more aggressive with retries when applies fail due to specific errors

```
I0923 16:24:55.662730    5113 addon.go:192] Applying update from "s3://k8s-kops-prow/e2e-e2e-kops-aws-karpenter.test-cncf-aws.k8s.io/addons/karpenter.sh/k8s-1.19.yaml"
I0923 16:24:55.662751    5113 s3fs.go:371] Reading file "s3://k8s-kops-prow/e2e-e2e-kops-aws-karpenter.test-cncf-aws.k8s.io/addons/karpenter.sh/k8s-1.19.yaml"
W0923 16:24:57.951711    5113 results.go:63] error from apply on karpenter.k8s.aws/v1alpha1, Kind=AWSNodeTemplate /nodes: error getting rest mapping for karpenter.k8s.aws/v1alpha1, Kind=AWSNodeTemplate: no matches for kind "AWSNodeTemplate" in version "karpenter.k8s.aws/v1alpha1"
W0923 16:24:57.951739    5113 results.go:63] error from apply on karpenter.sh/v1alpha5, Kind=Provisioner /nodes: error getting rest mapping for karpenter.sh/v1alpha5, Kind=Provisioner: no matches for kind "Provisioner" in version "karpenter.sh/v1alpha5"
...
I0923 16:26:01.610504    5896 addon.go:192] Applying update from "s3://k8s-kops-prow/e2e-e2e-kops-aws-karpenter.test-cncf-aws.k8s.io/addons/karpenter.sh/k8s-1.19.yaml"
I0923 16:26:01.610524    5896 s3fs.go:371] Reading file "s3://k8s-kops-prow/e2e-e2e-kops-aws-karpenter.test-cncf-aws.k8s.io/addons/karpenter.sh/k8s-1.19.yaml"
W0923 16:26:12.242237    5896 results.go:63] error from apply on karpenter.k8s.aws/v1alpha1, Kind=AWSNodeTemplate /nodes: error from apply: error patching object: Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.kube-system.svc:443/?timeout=10s": context deadline exceeded
W0923 16:26:22.248409    5896 results.go:63] error from apply on karpenter.sh/v1alpha5, Kind=Provisioner /nodes: error from apply: error patching object: Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.kube-system.svc:443/?timeout=10s": context deadline exceeded
...
NAME		CURRENT	UPDATE									PKI
karpenter.sh	-	d8a7cfc0aad0429b88d35c4483e233a8bad6c3c418f3af7341ddce6012bfbdd1	no
I0923 16:27:43.554602    7196 addon.go:192] Applying update from "s3://k8s-kops-prow/e2e-e2e-kops-aws-karpenter.test-cncf-aws.k8s.io/addons/karpenter.sh/k8s-1.19.yaml"
I0923 16:27:43.554623    7196 s3fs.go:371] Reading file "s3://k8s-kops-prow/e2e-e2e-kops-aws-karpenter.test-cncf-aws.k8s.io/addons/karpenter.sh/k8s-1.19.yaml"
# finally succeeds (no logged errors)
```

> Files need to update packages configs in some cases, so they have to run after (IIRC).

These particular File tasks don't have any dependencies, which the topological_sort.go log output shows.

> I think more of those packages can be removed. Tests need to be run for all supported distros and all supported k8s versions.

I also wonder if we can be more precise with each Service task's dependencies. Right now nodeup assumes [every Service depends on every Package](https://github.com/kubernetes/kops/blob/b9d0eed797b519919f350d5341fb34b3c363ceff/upup/pkg/fi/nodeup/nodetasks/service.go#L86-L92), though this would likely only improve overall timing with John's scheduler rewrite idea.
