### ISSUE TITLE
Expose port 22 on the API Server's Loadbalancer

### ISSUE THREAD

**Issue by upodroid** [kubernetes/kops#15985]
Some e2e tests SSH to the control plane instance to execute commands and this is currently failing on kops clusters because the API Server IP is the loadbalancer and it doesn't include port 22.

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-cos-gce-slow-canary/1708891985160441856

```
Kubernetes e2e suite: [It] [sig-cloud-provider-gcp] Addon update should propagate add-on file changes [Slow] expand_less	2m13s
{ failed [FAILED] Failed to get the master SSH client.: error getting SSH client to host 34.125.202.85:22: dial tcp 34.125.202.85:22: connect: connection timed out
In [BeforeEach] at: test/e2e/cloud/gcp/addon_update.go:235 @ 10/02/23 17:30:18.558
}
```

**Comment by hakman** [comment]
You could say it's a kOps bug, but this is more of a tests bug.
Assuming that SSH access is available on the same IP as the API server is quite an assumption.

**Comment by upodroid** [comment]
This can be resolved by rewriting kubernetes e2e test to use hostexec pod instead.

Like this https://github.com/kubernetes/kubernetes/pull/121007
