### ISSUE TITLE
IRSA catch-22 when rebooting cluster with masters only

### ISSUE THREAD

**Issue by andsens** [kubernetes/kops#15991]
The [`pod-identity-webhook` deployment](https://github.com/kubernetes/kops/blob/ed6edaf193efd9339a576112cd38d2bbd4aadd67/upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template#L64-L127) does not specify a control-plane toleration.

This is rather unfortunate when a cluster for some reason needs to start up and only has the master nodes available (e.g. `--cloudonly`), because karpenter will be unable to contact AWS to spin up new nodes so the pods can actually run. I suspect that there may be other workloads that run into the same problem and result in (non-critical but) unneccessary errors.

I suggest the control-plane toleration be added to said deployment.

**Comment by hakman** [comment]
@johngmyers @olemarkus any thoughts?

**Comment by olemarkus** [comment]
kOps addons like Karpenter does not depend on the pod identity webhook. kOps patches in the necessary changes to the manifests on its own.

**Comment by andsens** [comment]
@olemarkus ok, in that case I have no explanation for why nodes only started spinning up once I added that toleration. There was a 100% correlation with this. I must admit that the troubleshooting was rather hectic though, since the priority was getting things running again and not determining the exact cause. Any other idea as to why I observed what I did?

**Comment by johngmyers** [comment]
The pod-identity-webhook MutatingWebhookConfiguration has an objectSelector of

```yaml
    matchExpressions:
    - key: kops.k8s.io/managed-by
      operator: NotIn
      values:
      - kops
    - key: k8s-app
      operator: NotIn
      values:
      - kube-apiserver
```

The Karpenter Pods should be excluded from this because of the `kops.k8s.io/managed-by: kops` label on them.

Very few addons have a `kops.k8s.io/managed-by` label

**Comment by andsens** [comment]
You're right! Closing. This was a timing issue, I just reproduced it. For some reason coredns is really slow to become properly ready, it says running, but karpenter at least gets permission denied:

![Screenshot from 2023-12-14 10-43-56](https://github.com/kubernetes/kops/assets/342823/8af50829-78f0-4335-9d6e-a712d3a71d8b)
