### ISSUE TITLE
Rolling update with openstack.kops.io/serverGroupName fails

### ISSUE THREAD

**Issue by Wieneo** [kubernetes/kops#16015]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
v1.28.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.26.9

**3. What cloud provider are you using?**
OpenStack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
- Created cluster
```
kops create cluster \
          --cloud openstack \
          --name ${CLUSTER} \
          --state s3://kops \
          --zones az1 \
          --master-zones az1 \
          --network-cidr 10.10.0.0/16 \
          --image "Ubuntu 22.04" \
          --master-count=3 \
          --node-count=3 \
          --node-size SCS-16V:32:100 \
          --master-size SCS-8V:8:100 \
          --etcd-storage-type __DEFAULT__ \
          --api-loadbalancer-type public \
          --topology private \
          --ssh-public-key /tmp/id_rsa.pub \
          --networking calico \
          --os-ext-net ext01 \
          --os-octavia=true \
          --os-octavia-provider="amphora"
```
- Added openstack.kops.io/serverGroupName annotation to InstanceGroup
- `kops update cluster --name ${CLUSTER} --yes --admin`
- `kops validate cluster --wait 15m --name ${CLUSTER}`
- `kops rolling-update cluster --name ${CLUSTER} --yes --force`

**5. What happened after the commands executed?**
Rolling Update fails with error: `InstanceGroup "control-plane-az1-1" did not have enough nodes 0 vs 1`

**6. What did you expect to happen?**
Rolling Update succeeds and OpenStack instances get added to the server group.

**Comment by fchiacchiaretta** [comment]
I'm also hitting this issue.
First control plane is properly deleted and recreated in the new server group, it joined the cluster successfully and still validation fails.

If I run `kops get instances`, the new instance does not show up .

**Comment by zetaab** [comment]
I will try to remember fix this in start of next week

**Comment by zetaab** [comment]
https://github.com/kubernetes/kops/pull/16023 cherry-pick to release-1.28
