### ISSUE TITLE
Kops attempts to delete elastic ip on a managed NAT.

### ISSUE THREAD

**Issue by ajohnstone** [kubernetes/kops#1604]
Kops attempts to delete elastic ip on a managed NAT when running ```kops delete```.

```
stdout: elastic-ip:eipalloc-f5c9c491	error deleting resource, will retry: error deleting elastic ip "34.248.125.45": AuthFailure: You do not have permission to access the specified resource.
```

**Comment by justinsb** [comment]
To clarify, is the problem that

* we try to delete the ElasticIP before we delete the NAT gateway?

or

* that we should not be deleting the ElasticIP at all?

(or something else!)

I'm going to fix the first case, but if it is the latter if you can provide hints as to how you got here and I'll see if I can reproduce.

**Comment by ajohnstone** [comment]
@justinsb In my current case I would just like ti dis-associate the EIP and not physically delete it. However I think I would need to update my config to mark the NAT as a shared gateway?

**Comment by kris-nova** [comment]
@ajohnstone 

Just to be clear, you are running an existing NGW (as in one that was created outside of kops).. and kops is trying to delete the associated ELB for this NGW when you run `kops delete`? Is that correct?

**Comment by ajohnstone** [comment]
I created the NAT gateway with Kops and have been looking to move it to a shared NAT gateway. Therefore I want to disassociate it from Kops. The correct action is the patch that @justinsb applied. :)

**Comment by chrislovecnm** [comment]
Is this still the case?

**Comment by chrislovecnm** [comment]
Is this still the case?

**Comment by chrislovecnm** [comment]
Closed as it seems his answer was that it is fixed
