### ISSUE TITLE
cluster-autoscaler addon should have a setting for "skip-nodes-with-custom-controller-pods"

### ISSUE THREAD

**Issue by shapirus** [kubernetes/kops#16057]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
kOps `cluster-autoscaler` addon's [configuration spec](https://pkg.go.dev/k8s.io/kops@v1.28.0/pkg/apis/kops#ClusterAutoscalerConfig) does not have any attribute to set the `skip-nodes-with-custom-controller-pods` [cluster-autoscaler parameter](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca).

It should be supported along with the `skip-nodes-with-system-pods` and `skip-nodes-with-local-storage` parameters.

**2. Feel free to provide a design supporting your feature request.**
Seems to be a trivial copy&paste job.

**Comment by hakman** [comment]
> Seems to be a trivial copy&paste job.

It is indeed pretty simple to add. If you have the time, would you like to try?

**Comment by shapirus** [comment]
@hakman possibly, but the problem is that I'm not sure what part of the code is auto-generated. I don't want to edit the wrong place(s). Is there any contributor documentation describing this?

**Comment by hakman** [comment]
@shapirus @prashantrewar The 3 `componentconfig.go`, `clusterautoscaler.go`, and `cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template` files must be modified.
The auto-generated files will be generated by running `make apimachinery crds` and `hack/update-expected.sh`.

**Comment by shapirus** [comment]
@hakman ok here's a PR. I committed changes to the generated files as well (since they're versioned), please let me know if it wasn't necessary. Also updated docs/addons.md, again, not sure if it was necessary or these docs are auto-generated at a later stage.
