### ISSUE TITLE
Dashboard inaccessible on private cluster 

### ISSUE THREAD

**Issue by caarlos0** [kubernetes/kops#1606]
I created a cluster with:

```console
$ kops create cluster \
  --kubernetes-version=1.5.2 \
  --topology=private \
  --networking=cni \ # required by topology=private
  --dns=private \
  --vpc=vpc-id  \
  --zones=us-east-1a \
  --name=dev.company.local
```

Then I created the weaver, heapster and dashboard services:

```console
$ kubectl create -f https://git.io/weave-kube
$ kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/monitoring-standalone/v1.2.0.yaml
$ kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
```

It was working all right, until I created one of our services with an internal ELB. The service is working and is accessible through the private ELB, but when I try to access the kubernetes-dashboard, I get:

```
Error: 'dial tcp 10.40.0.2:9090: getsockopt: no route to host'
Trying to reach: 'http://10.40.0.2:9090/'
```

`10.40.0.2:9090` is the dashboard endpoint:

```console
$ kubectl describe service kubernetes-dashboard --namespace kube-system
Name:			kubernetes-dashboard
Namespace:		kube-system
Labels:			app=kubernetes-dashboard
Selector:		app=kubernetes-dashboard
Type:			NodePort
IP:			100.68.60.66
Port:			<unset>	80/TCP
NodePort:		<unset>	32366/TCP
Endpoints:		10.40.0.2:9090
Session Affinity:	None
No events.
```

Doesn't matter if I access it by `api.dev.company.local/ui` or by proxying it, the error is always the same. It asks for login and password, then shows that message (after some time).

What I tried:

- delete our service (and deployments and etc)
- re-create the dashboard service
- restart docker service on master and all nodes

None of this worked.

What can I do?

FWIW:

```console
$ kops version
Version 1.5.0-alpha4

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by caarlos0** [comment]
Actually, all services are inaccessible through the `api.dev.company.local/api` URLs, for example, `https://api.dev.contaazul.local/api/v1/proxy/namespaces/default/services/that-internal-elb-service/` shows:

```
Error: 'dial tcp 10.40.0.3:3000: getsockopt: no route to host'
Trying to reach: 'http://10.40.0.3:3000/'
```

So it's not just the dashboard...

**Comment by caarlos0** [comment]
I terminated both nodes (so the auto scaling group created 2 more), and now it's working.

But, why did it started to fail in the first place?

**Comment by justinsb** [comment]
@caarlos0 it sounds like you might have hit https://github.com/kubernetes/kops/issues/1251 ?  I haven't been able to reproduce it myself though (yet!)

Is there a reason to do networking=cni and then install weave, rather than just networking=weave ?

**Comment by caarlos0** [comment]
I guess not, `kube-dns` was up at the time. So was the `weaver` pods...

**Comment by jokeyrhyme** [comment]
I'm experiencing similar issues, and I've been experimenting with different combinations of certain variables:
-   whether the VPC existed already, or `kops` created it
-   whether the subnets existed already, or `kops` created them

Results:
-   `kops` creates VPC, `kops` creates subnets = SUCCESS
-   existing VPC, existing subnets = TIMEOUT
-   existing VPC (brand new, CIDR: 172.20.0.0/16, attached new IGW), `kops` creates subnets = SUCCESS

When I inspect the successful VPC, I notice that it has a Route Table (main=no, subnets=3) with a bunch of entries like this:
-   100.96.0.0/24 eni-123 / i-123
-   100.96.1.0/24 eni-456 / i-456
-   etc...
-   These entries look related to the `spec.nonMasqueradeCIDR` found via `kops edit cluster ...`

When I inspect the broken VPC, I notice that it has the pre-existing Route Table (main=yes, subnets=3) without those nonMasqueradeCIDR-related entries

I would guess that `kops` does not modify pre-existing Route Tables, probably as a safety mechanism. Unfortunately, this means manually mapping nonMasqueradeCIDR-related entries in the Route Table to the ENIs for the EC2s, especially for new / replaced / deleted EC2s.

**Comment by jokeyrhyme** [comment]
I just tried to manually add these mappings in, but either I did this incorrectly or there's more broken here than missing Route Table entries. I didn't know which entry was supposed to map to which ENI (I'm sure kops / kubernetes has a system for this) so my mappings are likely to be incorrect.

**Comment by rmrbest** [comment]
Hi @jokeyrhyme,

How did you solved this issue?

**Comment by jokeyrhyme** [comment]
@rmrbest I avoid using existing subnets with kops for now. This wasn't too inconvenient for my use case.

**Comment by caedev** [comment]
Also experiencing this issue - can't get any routing from outside to work after deploying into an existing VPC.  Any update on how to resolve?

**Comment by rmrbest** [comment]
@caedev can you provide more info? have you tried deploy a nginx container, for example? It doesn't make an ELB?

**Comment by caedev** [comment]
Hey @rmrbest.   I was trying to get an ingress controller working (having done it on many clusters before), and it did everything as expected:  created nginx deployment, created Load Balancer service in K8s, and created an ELB in AWS pointing to my nodes.  The only issue is that the ELB fails the health check for all nodes as it appears to be unable to access them.

I also deployed the kubernetes dashboard/service and it times out trying to reach the pod, which again points at a networking issues.

**Comment by chrislovecnm** [comment]
Any update on this?

**Comment by glesperance** [comment]
Not sure if this can help but I was able to solve this issue by using the `calico` networking option st:

**Comment by glesperance** [comment]
Not sure if this can help but I was able to solve this issue by using the `calico` networking option st: 

```
kops create cluster \
  --name=$MY_KUBE_DOMAIN \
  --state=$S3_BUCKET \
  --dns-zone=$MY_KUBEZONE \
  --zones us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1e \
  --topology private \
  --networking calico \
  --network-cidr 10.0.0.0/16 \
  --out=. \
  --target=terraform &&

terraform apply
```

**Comment by chrislovecnm** [comment]
I am having the problem with weave reusing subnets, with weave.

**Comment by dennis-bell** [comment]
Also seeing the same problem when using public networking and reusing existing VPC and subnets.
Required routing tables are not being created.
