### ISSUE TITLE
CodeDeploy on the Bastion

### ISSUE THREAD

**Issue by apenney** [kubernetes/kops#1609]
Hi,

We're looking for a workflow along the lines of:

* Travis-CI builds a git tag.
* Travis-CI does $thing to cause a deployment in Kubernetes.

We want to use a private cluster with a Bastion to achieve this and we don't want to have Travis SSH into the bastion to issue commands as that's fairly error prone.  We're considering integrating CodeDeploy into the AWS AMI for the bastion.

It's written in ruby so it would drag those dependencies in, but otherwise is relatively harmless.  It listens for connections from the AWS CodeDeploy service and then orchestrates deployment actions for a given repository.

We would use this to automatically run kubectl deploy, or helm, etc, for a given service without having to add SSH keys to Travis-CI and have it ssh in and try to remotely run commands.

We're open to suggestions of a better way to do this if people feel CodeDeploy is too large a dependency to add.

**Comment by justinsb** [comment]
Had an idea:  Could we run CodeDeploy in a kubernetes pod?  Looking at the docs, it looks like it might poll S3 (?), which would be simple.  If CodeDeploy sends a notification to it, we could also expose CodeDeploy through ingress or service with Type=LoadBalancer, though then we would have to be careful to secure it correctly.

**Comment by chrislovecnm** [comment]
So let k8s manage itself. This is a design concern for an app, for more idea I would recommend stackoverflow. May we close?

**Comment by brainstorm** [comment]
IMHO this is not just a desing concern for an app, this is a general and very relevant CI/CD pattern that many users of Kubernetes would like to implement as a "best practice", @chrislovecnm .

How did you end up implementing this, @justinsb and @apenney?

**Comment by brainstorm** [comment]
Something like this, perhaps?: https://kumorilabs.com/blog/k8s-8-continuous-deployment-travis-ci-kubernetes/
