### ISSUE TITLE
Kubernetes cluster totally down after running Kops rolling-update with a different version Kops.

### ISSUE THREAD

**Issue by ymhzsu** [kubernetes/kops#1612]
Hi, our team has a up running single-master Kubernetes cluster managed by Kops 1.4.4. Today we accidentally run a "Kops rolling-update" with a Kops 1.4.1. And after that the entire cluster is down.

The rolling-update seems normal, all instances are terminated and new instances are created. But after that, I noticed that including apiserver and etcd, non of the kubernetes related containers are running when checking "docker ps". The only container that is running is "protokube".

I wonder if this is because of we performed rolling-update with a different version of Kops?

**Comment by justinsb** [comment]
I would probably try a `kops update` with the 1.4.4 version of kops, just so you pick up the latest bug fixes.  If you `kops edit` and change the created timestamp, that is a trick that can force an update even if kops thinks none is needed.

**Comment by ymhzsu** [comment]
Hi Justin, thanks for the quick reply.
Yes we did tried kops update/rolling-update with 1.4.4, unfortunately nothing worked.
Another pain in the neck is that we cannot find any Kops logs and therefore unable to target the problem. I wonder where are the Kops logs located?

**Comment by justinsb** [comment]
Can you ssh to the master, and get the docker logs from protokube?  It
sounds like that is failing.

On Jan 24, 2017 5:49 PM, "ymhzsu" <notifications@github.com> wrote:

Hi Justin, thanks for the quick reply.
Yes we did tried kops update/rolling-update with 1.4.4, unfortunately
nothing worked.
Another pain in the neck is that we cannot find any Kops logs and therefore
unable to target the problem. I wonder where are the Kops logs located?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kops/issues/1612#issuecomment-274964723>,
or mute
the thread

**Comment by ymhzsu** [comment]
Yes I've checked the log of protokube, and yes it is failing. The log shows that protokube keeps trying to connect to namespace "kube-system" and keep failing(Because it does not even exist).

**Comment by justinsb** [comment]
Are you on the kubernetes slack ( https://kubernetes.slack.com/messages )  If so, maybe DM me - I am justinsb.

The kube-system log is normal - that just means the apiserver is not up.

What we're looking for is it trying to mount volumes, and then starting etcd.

You might also try `sudo systemctl restart kubelet` - it can't hurt at this stage.

**Comment by justinsb** [comment]
The sequence we are looking for:

* protokube mounts volumes /dev/xvdu and /dev/xvdv I believe.  These should be visible in `mount`
* protokube sets the DNS names in route53 for etcd
/etc/kubernetes/manifests/etcd.manifest exists and is non-empty
* kubelet launches etcd, per the manifest
* etcd is visible in `sudo docker ps` or `sudo docker ps -a` if it is crashing
* etcd stays up for a few minutes (check logs in /var/log/etcd.log)
* apiserver comes up and stays up (in `docker ps`, logs in /var/log/apiserver.log)
* kube-controller-manager goes healthy (in /var/log/kube-controller-manager.log)
* kube-scheduler goes healthy (in /var/log/kube-scheduler.log)
* dns-controller comes up and registers internal DNS names for the API
* the other nodes register and are visible in `kubectl get nodes`

(protokube actually runs 2 etcd clusters: etcd and etcd-events, but the main one is the one we care about)

If it isn't working, then a useful procedure is to see how far along it got.  I can provide more details as needed.

**Comment by anguslees** [comment]
We just had this same issue.  Somehow /etc/sysconfig/kubelet was missing `--pod-manifest-path /etc/kubernetes/manifests` - editing the file to include that, and getting systemd to restart kubelet.service brought everything back up.  Still investigating exactly how that happened.  Fwiw we used kops 1.5.0-beta1 for the upgrade that went wrong.

(What worked well: justinsb, your description of the expected boot sequence above was invaluable - I suggest putting that somewhere prominently in some recovery docs)

**Comment by ntrvic** [comment]
+1 Just had the same issue. I updated the cluster spec with 1.5.3 when I originally provisioned the cluster with 1.5.0-alpha4. Updating the spec with  1.5.0-alpha4 fixed the issue. Thank you for this post.
