### ISSUE TITLE
Change the default exposure method from DNS to LoadBalancer in v1.5

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/kops#1613]
The current default way that the `api-server` is exposed is through DNS. I understand that coming with KOPS v1.5 is support for it to be exposed via an ELB and the ELB's address to be setup in DNS. 

I propose that the default used in v1.5, to be exposing via an ELB, not directly through DNS. I believe that this is a better approach for the following reasons:

1) If a Master instance is replaced, Route53 will need to be manually changed... Or some automation built to automatically update it.
2) If a Master instance changes, any caching of the DNS values anywhere on the net will potentially result in errors, until the update propagates. Trusting all intermediate servers to honor TTL should be avoided, especially when there are solid alternatives.
3) Using an ELB is the standard way of exposing services/endpoints in AWS. This will fit better with what people expect and AWS has nice support for monitoring ELBs through CloudWatch.

**Comment by chrislovecnm** [comment]
@pluttrell what about etcd?  We need the nodes to find each other :(  You have a solution for that one?  We already have a ELB in private topo btw.

**Comment by justinsb** [comment]
We do have the automation to update Route53, BTW.  (protokube & dns-controller).

The caching is indeed an issue.  It is not my experience that many people are still running broken caching resolvers, but they are out there.

I also take your point on ELB being the more "normal" approach.

I think it's definitely something we should consider, and we should definitely have a flag.  I really want to get 1.5.0 out the door, so I'm inclined to revisit in 1.5.1 (which starts immediately post 1.5.0).

Ulterior motive here though: I actually want to get the API server working using LetsEncrypt and/or ingress.  So I'd like to figure that out at the same time.

I propose as a course of action:

* Create a flag so people can choose
* Figure out ingress / letsencrypt, and hopefully add another flag option
* Revisit the default for the flag in kops 1.6 (around March)?

**Comment by pluttrell** [comment]
That sounds like a reasonable course of action to me. And I'm a huge fan of getting LetsEncrypt integrated. The polish of having SSL out of the box without the nasty browser warning when the dashboard first launches, will subtly improve people's first impression..and likely adoption.

Regarding @chrislovecnm's question about etcd instances needing to find each other.. First I've not dug into etcd at all, so don't know how it works, or it's requirements for bootstrapping nodes. Bootstrapping nodes in a leaderless architecture is usually a challenge. Here's an [etcd doc on clustering](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/clustering.md), which mentions three ways...none of which involves using DNS A records. Perhaps the etcd team might have some suggestions on how best to bootstrap on AWS. If your only need is to find all of the instances in an ELB, the AWS CLI tools do have a [command to retrieve](http://docs.aws.amazon.com/cli/latest/reference/elb/describe-load-balancers.html) these.

One of the reasons I started looking at kops is it's "support for HA masters." But I've never seen an HA deployment at AWS that uses instance IPs directly in DNS A records. The standard that I've always seen is that the DNS points to the ELB, and the instances in the ELB are controlled by some other means, usually an ASG. I see that kops has already created ASGs for each zone of Masters, so [assigning those instances](http://docs.aws.amazon.com/autoscaling/latest/userguide/attach-load-balancer-asg.html) to an ELB shouldn't be hard. Nor should pointing [Route53 at the ELB](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer.html).

**Comment by kris-nova** [comment]
I would really like to see ELB's becoming the public facing resource for kops moving forward, but also agree that it makes sense to punt until 1.5.1

Nothing but +1's from me all around.

**Comment by rifelpet** [comment]
ELBs are default for AWS clusters so this should be safe to close.

/close
