### ISSUE TITLE
Update of kops addon fails because of incorrect HPA health check

### ISSUE THREAD

**Issue by Nick-Triller** [kubernetes/kops#16148]
/kind bug

The following function `isHealthy` checks if a resource that was applied for a kops addon install / update is healthy. However, the check equates health with all conditions being `true`:
https://github.com/kubernetes/kops/blob/ec9dbe4b999027fc2c2d598233797f858ceef5d5/pkg/applylib/applyset/health.go#L99-L118

This assumption doesn't hold for horizontal pod autoscalers. An HPA can have condition `ScalingLimited=false` which means that the desired number of replicas for the HPA hasn't been capped by the HPA minimum or maximum. The condition doesn't imply that the HPA resource is unhealthy or not ready.

`updateAddon` exits early because `isHealthy` returned `false` which means protokube doesn't update the `manifestHash` annotation on kube-system namespace to the new `manifestHash`. In short, protokube considers the addon apply to have failed because of the health check:
https://github.com/kubernetes/kops/blob/0d1c6371d6b4239d4e375ab90878c1932f5205fd/channels/pkg/channels/addon.go#L221-L223

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.26.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.25.10

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

1. Install a static kops addon that includes an HPA.
2. Wait for the HPA to receive the following condition that is added when the HPA stabilises between min and max:
```
  - lastTransitionTime: "2023-11-27T18:19:35Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
```
3. Make any change to the kops addon (`manifestHash` for the addon changes).
4. Protokube attempts to apply the addon manifest.
5. Applying channel fails with the following log lines in protokube:
```
I1201 13:21:52.595088  917900 health.go:107] status.conditions indicates object HorizontalPodAutoscaler.autoscaling:argocd/argocd-server-hpa is not ready: {"lastTransitionTime":"2023-11-27T18:19:35Z","message":"the desired count is within the acceptable range","reason":"DesiredWithinRange","status":"False","type":"ScalingLimited"}
```
and
```
W1201 13:21:54.265204    2302 kube_boot.go:89] error applying channel "s3://kops-addons-plaid-staging-io/bootstrap/addons/addons.yaml": error running channels: exit status 1
updating "argo-cd.bootstrap.plaid.io": error applying update from "s3://kops-addons-plaid-staging-io/bootstrap/addons/argo-cd.bootstrap.plaid.io/v5.42.0-staging.yaml": not all objects were healthy
```

**5. What did you expect to happen?**

The addon update should have succeeded.

**Comment by ntriller-plaid** [comment]
Hi @rifelpet, thanks for the fast resolution!
