### ISSUE TITLE
Possibility to create cluster on prem

### ISSUE THREAD

**Issue by DevOpsJazz** [kubernetes/kops#16161]
Hi

Is it or will it be possible to create an on prem cluster like kubespray?

**Comment by zetaab** [comment]
kops supports openstack which can be installed on prem. Otherwise there is no support

**Comment by JCzz** [comment]
Is it possible to write a custom "installer", and thereby maybe reuse some existing code?

**Comment by zetaab** [comment]
of course it is. Also it is possible to add support for new providers in kOps if these are some standard vendors that exists in more than one datacenter in world.

**Comment by JCzz** [comment]
Any ideas where to start?

It would be cool to make something like k3sup:

https://github.com/alexellis/k3sup
