### ISSUE TITLE
SSH keys are not added to nodes in GCE

### ISSUE THREAD

**Issue by marseel** [kubernetes/kops#16175]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.29.0-alpha.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.28.4, but probably doesn't matter

**3. What cloud provider are you using?**
GCE

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create cluster --ssh-public-key id_ed25519.pub ...
```

**9. Anything else do we need to know?**

Currently, kops adds SSH keys to GCE metadata [here](https://github.com/kubernetes/kops/blob/ecf212d736ebbbe0d490a36ceb303908725cd821/pkg/model/gcemodel/autoscalinggroup.go#L159)
However, key used `SecretNameSSHPrimary = "admin"` makes GCE VM GuestAgent fail to add these keys:
```
Creating user admin.
Error creating user: useradd: group admin exists - if you want to add this user to that group, use -g
```

I rebuilt kops with `SecretNameSSHPrimary = "marseel"`  and after that I was able to ssh to machine with a command:
```
ssh -o "IdentitiesOnly=yes" -i ./id_ed25519 marseel@IP
```
Also GuestAgent stopped complaining:
```
Creating user marseel.
Updating keys for user marseel.
```

**Comment by marseel** [comment]
/cc @hakman 
just FYI as this is something I stumbled upon when trying to run sig-scalability scale-test on GCE using kops.

**Comment by nevdullcode** [comment]
I'm still encountering this issue with kops on GCE. Is there a plan to fix it soon? Thank you!

**Comment by nevdullcode** [comment]
Bumping this issue and hoping that a kops maintainer can deliver a tenable solution.
