### ISSUE TITLE
Help with debugging kops 1.13 cluster intermittent issues in AWS - Ubuntu 18

### ISSUE THREAD

**Issue by annapurnam** [kubernetes/kops#16185]
Hello
We are running kops 1.13 version (I know it old) with flannel
These days all of a sudden we started noticing the nodes go bad and most times on us-east-1b AZ
Whenever a pod goes onto this node, we just no network traffic and pods can't reach any other pod on k8s
If I run standalone docker in the same node it works, but only the networking inside the k8s is cut off.

Any pointers is appreciated , I'm happy to jump on call and debug.
This doesn't happen all the time, but at this most the pattern is repeatitive.
This week, our whoe cluster went down and I couldn't figure out.
We created new cluster, some nodes are fine but some has this issue.

netstat, ifconfig and logs all appear to be same in good and bad node.

Pleas help

**Comment by hakman** [comment]
Having clusters that old, many things can happen. Most likely some of the certs are expired. 
There is no easy fix. See for example: https://github.com/kubernetes/kops/issues/8959.
