### ISSUE TITLE
Use and keep existing floating IP

### ISSUE THREAD

**Issue by happycouak** [kubernetes/kops#16226]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

In Openstack, floating IP (FIP) are provided randomly by the cloud provider, thus provided addresses cannot be re-used later when the FIP is deleted. But the FIP can be retained when de-associated from the instance to be removed, then it can be re-used later, allowing the keep the same public address.

It would be great if kops can provide:

1) a way to specify existing floating IP address to use for deployment, maybe under the form of lists of IPs for instance groups (bastion,control,node)
2) then when existing floating IPs are specified, to not delete them when the cluster is deleted

This would provide an easiest way to redeploy a cluster by keeping the same public addresses.

**2. Feel free to provide a design supporting your feature request.**

**Comment by zetaab** [comment]
which topology you are using in your cluster? public? As I see it, people should not use public topologies in openstack if there is not specific reason. You can achieve better security using private topology. Also in private topology it does not use that much floating ips.

I must admit that I do not have much experience of using public topology in kOps. What is the use-case to keep floating ips static between instance rotations?
