### ISSUE TITLE
Cluster_spec.md Subnet keys Docs are confusing

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#1623]
[Cluster Spec Subnet Keys](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#clusterspec-subnet-keys)

Need to clarify that it is correct to list egress (which seem to be public resources) in the private subnets.

**Comment by chrislovecnm** [comment]
We want to move this to a rest swagger API format. What is confusing? How do we rewrite?

**Comment by geojaz** [comment]
Oops, I left this as a note to myself and forgot that I hadn't done it. Swagger sounds awesome!

I'll PR my minor changes on this one today!
