### ISSUE TITLE
AWS VPC CNI Ubuntu 22.04 MACAddressPolicy

### ISSUE THREAD

**Issue by Deshke** [kubernetes/kops#16255]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

via 
* https://github.com/aws/amazon-vpc-cni-k8s/issues/2103
* https://github.com/kubernetes/kops/issues/15720

until https://github.com/aws/amazon-vpc-cni-k8s/pull/2118 is working the following Policy should be applied to get 22.04 working with aws vpc cni 

https://github.com/awslabs/amazon-eks-ami/blob/master/scripts/install-worker.sh#L104
```bash
# Temporary fix for https://github.com/aws/amazon-vpc-cni-k8s/pull/2118
sudo sed -i "s/^MACAddressPolicy=.*/MACAddressPolicy=none/" /usr/lib/systemd/network/99-default.link || true
```

or from https://github.com/aws/amazon-vpc-cni-k8s/issues/2103#issuecomment-1321698870 which may be used with [fileAssets](https://kops.sigs.k8s.io/cluster_spec/#fileassets)

**Comment by moshevayner** [comment]
Hey @hakman !
I can take that as part of my open PR (#16191 ), or alternatively- as a separate PR and then I can rebase my PR's branch to get the fix into it.

I looked around in the code, and from what I could see, the best place to add this would probably be in the launch template of an instance [here](https://github.com/kubernetes/kops/blob/7c3e32369a4f6feab701203d3c973d92416f9ce6/upup/pkg/fi/cloudup/awstasks/launchtemplate.go), probably wrapped inside an `if` block to only apply that if the CNI is AWS VPC CNI.
WDYT?
Would you say there a better approach for this?
Thanks!

**Comment by hakman** [comment]
@moshevayner To my knowledge, all AWS VPC CNI tests run on Ubuntu 20.04, so they should not be affected by this issue. I would suggest to try and move https://github.com/kubernetes/kops/pull/16191 to v1.16.2 and see what happens.

If you want to try to fix this in a separate PR, I think it would be a good idea.
The change needs to happen in nodeup code, similar to the code below, and run `systemctl restart systemd-networkd` on change:
https://github.com/kubernetes/kops/blob/a55614910d4480c013b7bdd95aa689932bbefac1/nodeup/pkg/model/sysctls.go#L191-L196
