### ISSUE TITLE
Add an 'All done' message to after creation/updates are complete

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/kops#1626]
Currently, there is no friendly 'All done' message after a cluster is created or updated with `kops update cluster ${NAME} --yes`. This leaves new users to wonder when their cluster is created or an update is complete. Not the best user experience. I'm seen people on Slack waiting an hour long, without any indication of completion or failure.

**Comment by kris-nova** [comment]
Can we get a suggestion here? Any thing other than a static log line we would be interested in?
