### ISSUE TITLE
Set MTU for kubenet

### ISSUE THREAD

**Issue by mbranyon** [kubernetes/kops#1627]
I am having some network latency issues in AWS. In an effort to track it down, I'd like to easily throughout the cluster be able to set the MTU as specified on this page: https://kubernetes.io/docs/admin/network-plugins/#customizing-the-mtu-with-kubenet.

**Comment by chrislovecnm** [comment]
I may need this as well.  Working on rolling updates and PV storage.  Help is always appreciated!

**Comment by justinsb** [comment]
So we do automatically pass `--network-plugin-mtu=9001` to kubelet, at least with `kubenet`.  Unfortunately it is then up to each networking plugin.  I opened https://github.com/kopeio/networking/issues/3 for kopeio/networking (aka `kopeio-vxlan`)

I don't think there's more we should do in kops other than get fixes into the various providers.  Moving to 1.5.1 therefore.

**Comment by chrislovecnm** [comment]
Closing as what we can do was answered. Please reopen if needed
