### ISSUE TITLE
Attach additional security group rules to node security group?

### ISSUE THREAD

**Issue by plombardi89** [kubernetes/kops#1628]
Is is possible to attach additional security groups to the rules for the node security group? Our use case is that we want to deploy Kubernetes into an existing VPC. The Kubernetes VPC is peered with another VPC that holds things like RDS instances and long-lived EC2 sysstems and want the Kubernetes nodes to be able to communicate with these systems by basically creating an `ALLOW ALL` set of ingress and egress rules.

**Comment by chrislovecnm** [comment]
We have a bunch of issues open on this topic. We here yah. 1.5.x timeframe

**Comment by justinsb** [comment]
This should work in 1.5.0, there are two new flags in `kops create cluster`:

```
      --master-security-groups stringSlice   Add precreated additional security groups to masters.
      --node-security-groups stringSlice     Add precreated additional security groups to nodes.
```

This populates a new field `additionalSecurityGroups` on each instance group.
