### ISSUE TITLE
I wish for Dualstack support on Openstack

### ISSUE THREAD

**Issue by zadjadr** [kubernetes/kops#16314]
/kind feature

I have a dual-stack Openstack Infrastructure ready and could test the feature, but I have not enough expertise to implement myself. Could help on stuff if someone is willing to tell me what needs to be done.

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I want to be able to deploy a ~~dual-stack (IPv6 + IPv4)~~ IPv6 Kubernetes Cluster on the Openstack provider. 

**2. Feel free to provide a design supporting your feature request.**

**Comment by zetaab** [comment]
kops itself does not support dualstack installation. It supports either ipv4 or ipv6 clusters.

**Comment by zadjadr** [comment]
Then I’d be super happy about IPv6 support in Openstack.
