### ISSUE TITLE
Unable to configure disruption controls for karpenter

### ISSUE THREAD

**Issue by clayrisser** [kubernetes/kops#16311]
I am unable to figure out how to add a disruption consolidationPolicy and expireAfter in my karpenter node pools for kops. Where do I configure this?

The karpenter docs discuss this here.

https://karpenter.sh/v0.32/concepts/nodepools/#specdisruption

I'm not even able to see a CRD for karpenter NodePools, so I'm guessing kops has another way of managing the disruption controls?

```
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h
```

**Comment by moshevayner** [comment]
From what I can tell right now, kOps installs karpenter version `0.31.3` by default which didn't support the nodePools concept yet, according to what I'm seeing in the docs (I hope I'm not wrong there), ref: https://github.com/kubernetes/kops/blob/d489024714013523bb1df74a58eaa9b99f6805b2/pkg/model/components/karpenter.go#L38-L40.
This brings me to believe that it's not supported in kOps right now, and thus, we might need to put in some effort to add this.

I don't mind taking a stab at this one, wdyt @hakman @rifelpet @olemarkus ?

**Comment by hakman** [comment]
> I don't mind taking a stab at this one, wdyt @hakman @rifelpet @olemarkus ?

My impression is that, if we want to move Karpenter support to a newer version, we would need to move from providing the LaunchTemplates to doing everything via Karpenter objects.

**Comment by moshevayner** [comment]
> My impression is that, if we want to move Karpenter support to a newer version, we would need to move from providing the LaunchTemplates to doing everything via Karpenter objects.


Yeah, that makes sense to me.
So, would that be (theoretically) a somewhat similar process to any other cloudup add-on such as aws-cni, in which we'll update the template (and potentially supporting resources such as template functions etc.) according to the vendor chart?

**Comment by moshevayner** [comment]
Sounds good! I'll give that a try. Thanks!

/assign

**Comment by teocns** [comment]
From my understanding it's unlikely possible but doesn't hurt to ask if there is any workaround for getting upstream _Karpenter_ to manage current kOps's release  InstanceGroups?
