### ISSUE TITLE
Try golang/dep for dependencies

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1634]
I think we should study, test drive, and discuss using [https://github.com/golang/dep](dep) for `kops`. We haven't visited our dependency management in a while, and it might be a good opportunity to do so. Especially after `kops v1.5.0` drops. 

This new tool looks like it will be a meaningful candidate for an officially adopted `Go` dependency manager! It's still very much in Alpha so getting involved now would give us a little bit of wiggle room to help grow with the project.. 

Anyway just a thought, maybe we could improve `kops` while simultaneously contributing to the `Go` community.. thoughts?

**Comment by justinsb** [comment]
Agreed, but let's try it on the external-dns project first?

**Comment by kris-nova** [comment]
@justinsb can't agree more! Once we get a repo up and going for `external-dns` we can drop this issue in / cross reference! But still think we should keep it open for `kops` 🚔

**Comment by chrislovecnm** [comment]
I think we are going to asess bazel as well

**Comment by KashifSaadat** [comment]
This is implemented and in master branch now.

/close
