### ISSUE TITLE
Treatment of overlapping ServiceCIDR and PodCIDRs

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#16340]
We may have introduced a regression, where previously overlapping ServiceCIDR and PodCIDRs were allowed, and now they are blocked by validation.

It does seem that the node-podCIDR allocation logic in kube-controller-manager automatically excludes the ServiceCIDR, so that an overlap should not give a conflict in practice (though we probably still want to discourage it).  For example:
 https://github.com/kubernetes/kubernetes/blob/98b589a76d57a137d91afc487304d0f699c23288/pkg/controller/nodeipam/ipam/range_allocator.go#L103

/kind bug

(Edited to change "should yield a conflict" to "should not give a conflict" - doh!)

**Comment by minkimipt** [comment]
Thanks @justinsb for creating the issue.
