### ISSUE TITLE
Don't pre-create A record for the API when using an ELB

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1635]
Or at least verify that we can replace the A record with the ELB alias.

**Comment by kris-nova** [comment]
Why wouldn't we be able to `s/reserved/elb-alias`? I think that should work just fine shouldn't it?

**Comment by justinsb** [comment]
You're right @kris-nova - it actually works fine.  The reason why is sort of subtle though - we create the DNS name (`api.<clustername>`) for the ELB in kops ("client side") and then precreation skips the record because it sees it exists.  It would be cleaner to skip precreating if it's an ELB, but it's not particularly important.  Bumping to 1.5.1
