### ISSUE TITLE
apiserver / k-c-m logs through `kubectl logs` ?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1637]
It would be nice if we could get k-c-m, kube-apiserver and kube-scheduler logs through `kubectl logs`.  Otherwise we have to SSH in.

One way to do this might be to pipe to tee.

**Comment by chrislovecnm** [comment]
huh ... interesting.  Great point.

**Comment by chrislovecnm** [comment]
We need
- kcm
- scheduler
- kubectl??
- kube-proxy
- kube-api

**Comment by rifelpet** [comment]
This has already been implemented.
/close
