### ISSUE TITLE
Terraform output should be formatted correctly

### ISSUE THREAD

**Issue by tazjin** [kubernetes/kops#1638]
Terraform, like Go, provides a `terraform fmt` command. The Terraform output currently produced by kops always has a few details that get picked up by terraform fmt.

We should format the output correctly before writing the Terraform files (this should make diffing and such easier).

**Comment by chrislovecnm** [comment]
Well, that would require tf. Can we format without tf?

**Comment by tazjin** [comment]
We don't need anything other than Hashicorp's HCL library that's currently vendored in, it contains the format command implementation! :)

**Comment by kris-nova** [comment]
I think we might even already have it vendored.. @tazjin you want to take a PR for this?

**Comment by tazjin** [comment]
@kris-nova Yes, I'll try to find time over the weekend.

**Comment by tazjin** [comment]
@kris-nova see above :)

**Comment by justinsb** [comment]
Thanks for the PR - the output looks much better.

The downside seems to be that (1) as a one-off we now introduce spurious diffs into everyone's output and (2) our TF output is no longer stable, because it is aligned to the longest variable name (like adding a field to a structure in go)

I'm not sure whether we should force this on users, particularly as they can TF format it themselves if they want to.  I'll ponder...

**Comment by tazjin** [comment]
Hmm. (1) is true and unfortunate, but people probably expect different output after upgrading `kops` anyways.

Regarding (2) - I'm not sure I see how this is a problem. If there's logic that conditionally adds more properties to a TF resource you'd expect the output to change either way (because the resource has changed). Multiple runs of identical configuration still produce stable output.

**Comment by justinsb** [comment]
As a workaround for 1, we can suggest to people that they run `tf fmt` first if they're doing the multi-branch tricks.

I think I'm inclined I agree with you on 2 - that it won't happen much in practice, and when it does it is probably no bad thing to highlight the whole block.

**Comment by tazjin** [comment]
The Travis checks will also catch (1) for all conflicting PRs. Is there a way we could retrigger that for open PRs?
