### ISSUE TITLE
Cert-manager 12.x is not recommended by developers

### ISSUE THREAD

**Issue by minkimipt** [kubernetes/kops#16427]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

The newest cert-manager version kops can install now is 12.7, while the newest major is 13.x. Releasenotes for 12.6 mentions that 12.x are not recommended because of a bug, that was fixed in 13.x and will not be backported:
https://github.com/cert-manager/cert-manager/releases/tag/v1.12.6

**2. Feel free to provide a design supporting your feature request.**

Cert-manager version needs to be bumped to avoid creating problems

**Comment by hakman** [comment]
Thank you for reporting this. We are preparing some releases soon.

**Comment by hakman** [comment]
@idealhack already bumped the version, thanks a lot for that! 😄
