### ISSUE TITLE
Attach an existing managed policy to node.<cluster> IAM role.

### ISSUE THREAD

**Issue by ajohnstone** [kubernetes/kops#1645]
It would be ideal to add an existing managed policy to instance groups.

With that said would additionalPolicies be better as a managed policy?

Also relates to #1644 

@yissachar @chrislovecnm

**Comment by chrislovecnm** [comment]
@ajohnstone absolutely.  We are creating an interesting house of cards with identity management, auth and authz.  Would be great to understand use cases and community needs.

**Comment by justinsb** [comment]
I think this is a good idea.  @yissachar and I actually discussed this alternative, and we could certainly add it in the model,

It is also our hope to get kube2iam up and running, and to encourage that instead.  @ajohnstone if we had kube2iam integration, would you still want to attach additional policies?

**Comment by ajohnstone** [comment]
@justinsb Kube2iam would solve one set of scenarios.

I still think applying a managed policy is a better solution for managing iam policies, rather than attaching inline (assume this is what happens with additional policies presently).

Currently I have a number of requirements that require cross account policies to be set. So it's not just the policy that needs to be attached, but also configuring the trust relationship too.

**Comment by yissachar** [comment]
@ajohnstone The policy attached is a managed policy. So theoretically you could probably achieve what you want under the current system. That being said, I can see it being easier for some workflows to bring your own managed policy to kops, rather than using the one kops creates.

**Comment by chrislovecnm** [comment]
We have a PR in for some of this.  https://github.com/kubernetes/kops/pull/2139

**Comment by rifelpet** [comment]
This has been implemented in #7837 and will be included in Kops 1.18
/close
