### ISSUE TITLE
kops 1.6 themes

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1649]
1. Cloud providers: GCE, bare metal, arm, Azure. vSphere
2. Operations - log dump, rolling update, system dump
3. Security

What other themes shall we cover?

**Comment by chrislovecnm** [comment]
Operations - backup
Security - sec groups

**Comment by chrislovecnm** [comment]
Move docs to the website

**Comment by yissachar** [comment]
I think docs is a big one. We spend a lot of time on Slack handholding, which could be minimized by having a solid docs website.

**Comment by chrislovecnm** [comment]
I agree about docs ;)

@yissachar we could use some good feedback on what we need.  @scottmwebber was mentioning short video may be helpful.

**Comment by yissachar** [comment]
On security we should discuss kube2iam.

**Comment by chrislovecnm** [comment]
@yissachar yes, and I think #sig-aws is talking about including some form of that in core

**Comment by Marklon** [comment]
How can I help? @chrislovecnm . I've created a write up on How to create a production kubernetes cluster with full CI/CD. As @yissachar mentioned about spending a lot of time in the  Slack channels. I was one of those members jumping into the slack channel requesting help, I agree having a well documented process will help to mitigate the slack channel request at least for those who are new to Kubernetes and Kubectl.

**Comment by chrislovecnm** [comment]
Take a look at the help wanted items, and any doc updates are always appreciated.

**Comment by chrislovecnm** [comment]
Also thanks ;)

**Comment by Marklon** [comment]
Hi again @chrislovecnm  forgive me, but where can I locate the help wanted items?

**Comment by chrislovecnm** [comment]
@Marklon no worries.  I should have provided a link 😀 

https://github.com/kubernetes/kops/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%21%22

It is a label that we use with issues.

**Comment by chrislovecnm** [comment]
Closing
