### ISSUE TITLE
(re) validate upgrade from kube-up

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1650]
As part of 1.5.0 release, we should (re) validate upgrade from kube-up.  User fearphage on slack asked and was running 1.2.0 - might as well test that :-)

**Comment by justinsb** [comment]
Validate instructions in https://github.com/kubernetes/kops/pull/889/files

**Comment by justinsb** [comment]
A few issues that need fixing: #1699 but we'll get this fixed for the next release.

**Comment by justinsb** [comment]
Was (hopefully) fixed in #1699

**Comment by fearphage** [comment]
It makes more sense to me to close this when it is *verified* fixed instead of relying on hope. Thoughts?

**Comment by justinsb** [comment]
As part of #1699 I tested upgrading from 1.2 and 1.3.

**Comment by fearphage** [comment]
Excellent! It sounded a little less concrete before.
