### ISSUE TITLE
UX for HA creation in <N zones

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1653]
User hollow reported on slack that we should have a separate `master instance count` flag, and then we round-robin around the specified master-zones.

This makes sense.  We can show warnings if we think the configuration is questionable, but also advanced users can `kops edit cluster` before doing `kops update` if they care about e.g. which zone gets 2 masters.

**Comment by hollowimage** [comment]
i would suggest putting the config settings for instance count -- zone parity inside `kops edit ig master-<zone>` as its more of a fine-tuning our master configuration, and keeping just generic zone list and master count in the main `edit cluster`

**Comment by airstand** [comment]
That makes sense. I think that master-count flag is the best solution for that one .. and if somebody want to edit randomly generated options by kops - editing cluster is the right place to do such things :)

**Comment by justinsb** [comment]
PR in #1710 .  Comments welcome of course :-)
