### ISSUE TITLE
kops fails to properly detect image size

### ISSUE THREAD

**Issue by weaseal** [kubernetes/kops#1655]
If you specify a custom image that does not have a 20 GB root volume, kops fails to properly create the autoscaling groups, with AWS ASG reporting this error: Launching a new EC2 instance. Status Reason: Volume of size 20GB is smaller than snapshot 'snap-xxxxxxxx', expect size >= 50GB. Launching EC2 instance failed.

@justinsb has provided a nice workaround to this issue via https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#changing-the-root-volume-size-or-type

However it would be nice if this worked out-of-the-box without having to manually specify the volume size.

kops-1.5.0-beta1

**Comment by justinsb** [comment]
This is not trivial to fix, and there's a workaround (though it it tedious) in setting each instance group volume size.  So I've pushed it to 1.5.1, rather than 1.5.0.
