### ISSUE TITLE
Bump nvidia driver for CUDA 12.1 support

### ISSUE THREAD

**Issue by ddelange** [kubernetes/kops#16557]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Bump the nvidia driver for CUDA 12.1 support.

- [kops source](https://github.com/kubernetes/kops/blob/v1.29.0-beta.1/pkg/apis/kops/containerdconfig.go#L25) currently on `nvidia-headless-515-server` 
- [ubuntu repo](https://packages.ubuntu.com/search?section=all&arch=any&keywords=nvidia-driver&searchon=names) latest available version currently 550

We are currently running our 1.26 cluster configured with DriverPackage `nvidia-driver-535` (with CUDA 12.0 support).

Note that we moved away from `nvidia-headless-XXX-server` because it does not install `nvidia-smi` and some other binaries on the host system, which caused issues for us with some cuda docker images that rely on the host having them available. It's barely any additional disk space used, so that was a quick and effective fix.

When we tried bumping to `nvidia-driver-550` on EC2, the nodes stopped registering in the cluster. It was reverted before I could pull logs from the host system I'm afraid. I hope that your CI catches this.

**2. Feel free to provide a design supporting your feature request.**

**Comment by hakman** [comment]
Unfortunately, our CI does not run on GPU nodes. We don't have credits to run such tests at the moment...

**Comment by ddelange** [comment]
just [double-checked](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility): 535 already supports CUDA 12.1, which runs stable in our cluster

**Comment by ddelange** [comment]
Opened https://github.com/kubernetes/kops/pull/16560
