### ISSUE TITLE
Volumes available in multiple zones

### ISSUE THREAD

**Issue by 524c** [kubernetes/kops#16612]
I have a cluster on AWS with multiple control-planes and workers in different zones. I'm trying to find a storage solution with replication so that deployments/pods can run in multiple zones. I thought about using rook/ceph, but there are some challenges in getting it to work with KOPS on AWS.

Does anyone have any ideas on how I can resolve this? it doesn't necessarily have to be with rook/ceph. I just want my pods to be able to transit in any zone and continue to access the PVCS.

**Comment by 524c** [comment]
One of the problems I face is that I cannot configure, for example, the path that rook/ceph needs because the instances are volatile and after an update I will lose all manual configuration I make.

**Comment by zetaab** [comment]
If you need volume that works in multiple zones you need to use like EFS volume type.

**Comment by 524c** [comment]
> If you need volume that works in multiple zones you need to use like EFS volume type.

thanks!
