### ISSUE TITLE
Missing release assets on v1.30.0-beta.1 release

### ISSUE THREAD

**Issue by Lerentis** [kubernetes/kops#16643]
/kind bug

[latest beta release](https://github.com/kubernetes/kops/releases/tag/v1.30.0-beta.1 ) is missing all build assets and hashsums. Probably a new release would make sense or to recreate this one.

pinging @justinsb who created the release

**Comment by rifelpet** [comment]
Binary assets for have been added to the 1.30.0-beta.1 GitHub release 

/close
