### ISSUE TITLE
Add custom permission on cert-manager addon

### ISSUE THREAD

**Issue by nsagnett** [kubernetes/kops#16677]
/kind feature

Hello,

We currently use cert-manager addon combined with IRSA pod-identity-webhook with KOPS 1.28.4.
When we setup the cluster, cert-manager provisionned automatically an IAM role and it works.
But, I would like to add custom permission on existing role and I don't find any documentation on this.

Do you have some sample or a workaround if it's not possible?

**Comment by pipsi33** [comment]
nice
