### ISSUE TITLE
Update manifests with kops & kubernetes version info

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1667]
We need to start populating version information in the channel manifest:

```
W0128 22:37:49.905440    6245 apply_cluster.go:633] unable to find version information for kops version "1.5.0-beta1" in channel
W0128 22:37:49.905471    6245 apply_cluster.go:700] unable to find version information for kubernetes version "1.4.7" in channel
```

**Comment by MilanDasek** [comment]
Hi,

I have exact same problem. Is there any workaround? I would like to spin up the cluster asap.

thank you

M

**Comment by chrislovecnm** [comment]
@MilanDasek please provide more context :)

**Comment by MilanDasek** [comment]
I am trying to spin new cluster - config attached
[create-cluster-template.yaml.txt](https://github.com/kubernetes/kops/files/737405/create-cluster-template.yaml.txt)

When run: kops update cluster %NAME% --yes
I got

W0129 10:09:16.817497     194 apply_cluster.go:635] unable to find version information for kops version "1.5.0-beta1" in channel
W0129 10:09:16.818513     194 apply_cluster.go:702] unable to find version information for kubernetes version "1.4.7" in channel

**Comment by chrislovecnm** [comment]
Can we get a full `-v 10` log output?

Your config shows some odd things

```
   name: %NAME%
spec:
  channel: stable
  cloudProvider: aws
  configBase: s3://%S3%/%NAME%
  dnsZone: %ZONE%
```

Did you redact that information?  Why is there %NAME% for instance.

Also yo will want to run k8s version 1.4.8 as 1.4.7 has a nasty PVC bug.

**Comment by MilanDasek** [comment]
Hi,
[kops.log.txt](https://github.com/kubernetes/kops/files/737436/kops.log.txt)

yes, config is redacted - there are real names of course in the one I am running, log redacted as well.
1.4.8 - same error

W0129 11:18:02.987765     719 apply_cluster.go:635] unable to find version information for kops version "1.5.0-beta1" in channel
W0129 11:18:02.991604     719 apply_cluster.go:702] unable to find version information for kubernetes version "1.4.8" in channel
must configure at least one InstanceGroup

**Comment by justinsb** [comment]
This particular message is just a warning that the channels haven't been updated with the full information yet.  But just a warning, nothing to worry about.

@MilanDasek can you maybe open a separate issue including how you created your cluster, and the kops version you are running (`kops version`).  That should help us to reproduce more easily!

**Comment by MilanDasek** [comment]
@justinsb - I have tried create the cluster using yaml attached in my previous post. create-cluster-template.yaml.txt

Unfortunately the cluster is not created. It basically stops with the error.

kops version is also in my previous post - Version 1.5.0-beta1 (git-b419f20)
[create-cluster-template.yaml.txt](https://github.com/kubernetes/kops/files/737777/create-cluster-template.yaml.txt)
