### ISSUE TITLE
Update to new etcd-manager image

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#16724]
/kind blocks-next

This is a reminder to update the etcd-manager image back to a tagged release. We're currently using a staging image from https://github.com/kubernetes/kops/pull/16722

**Comment by rsafonseca** [comment]
It seems like @hakman already nailed this one
https://github.com/kubernetes/kops/commit/049ed0c56b573e5edc92d795d24ba3f1997c0b98
https://github.com/kubernetes/kops/commit/55911f34b7acea7f902e152dce8cf90a8a0ba04f

**Comment by hakman** [comment]
Yes, I think we are good. We will discuss tomorrow about the releases during the Office Hours call.
