### ISSUE TITLE
kops delete cluster fails with VPC peering

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1675]
According to https://github.com/kubernetes/kops/issues/1370#issuecomment-270973233, kops delete cluster fails if you have (manually) set up VPC peering.

**Comment by chrislovecnm** [comment]
It will :)  For instance, if you set up an RBS instance in your VPC.  Kops will not be able to delete the VPC.

**Comment by so0k** [comment]
isn't this expected behaviour?

**Comment by chrislovecnm** [comment]
Yah it is ..  @justinsb I am going to close this. Please re open if you need to
