### ISSUE TITLE
kops update cluster output confusing are we updating kubectl config?

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1676]
1. kops create cluster
2. kops edit cluster
3. downgraded version
3. kops update cluster --yes

console output

```console
I0128 23:19:00.642179   56789 update_cluster.go:202] Exporting kubecfg for cluster
Wrote config for liea-ginny.dev.datapipe.io to "/Users/clove/.kube/config"
Kops has changed your kubectl context to liea-ginny.dev.datapipe.io
```

Are we actually updating the config when the cluster exists?

**Comment by yissachar** [comment]
Not sure about the config part, but we may want to use `set` instead of `changed` since it won't always be changing.

**Comment by justinsb** [comment]
Yes, we are writing the potentially updated config.  Would be good to optimize that.

Agree @yissachar - that phrasing is much better.

**Comment by justinsb** [comment]
Better phrasing in #1690.

@chrislovecnm can you clarify what the issue is e.g. what are we doing wrong & why does it matter.

**Comment by chrislovecnm** [comment]
It does not make sense as a user that we are writing a config.  Are we?  Probably a misunderstanding of mine.

**Comment by chrislovecnm** [comment]
Closing because of the pr
