### ISSUE TITLE
No confirmation message for edit cluster

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1680]
```
$ kops edit cluster
Using cluster from kubectl context: liea-ginny.dev.datapipe.io

I0129 00:28:14.909656   61886 populate_cluster_spec.go:235] Defaulting DNS zone to: Z2PKVP3BDFE581
```

We give out "Defaulting DNS zone" message but nothing about the fact we edited the cluster.

**Comment by kamilhristov** [comment]
Created PR #1697 

Note that the message will still be displayed if validation fails. There is separate issue about this #124

**Comment by yissachar** [comment]
I'm not sure how much sense it makes to add this until #124 is dealt with. It is already confusing enough for users when they edit and the edit doesn't stick; having a positive message from kops telling them that the edit was successful (when it wasn't!) will make things worse.

**Comment by chrislovecnm** [comment]
Closing due to #1697
