### ISSUE TITLE
You cannot downgrade cluster 1.5.2 alpha -> 1.4.8 alpha

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1682]
May not be supported but you cannot downgrade a cluster from 1.5.2 using alpha channel to 1.4.8, but using the alpha channel.

1. `kops create cluster liea-ginny.dev.datapipe.io --yes --zones eu-west-1a --channel alpha`
1. `kops edit cluster` down-grade to 1.4.8
1. `kops update cluster --yes`

May be an edge case.  I am going to test 1.4.8 -> 1.4.7

**Comment by justinsb** [comment]
What happens - what is the error message?

**Comment by chrislovecnm** [comment]
Docker does not start.  1.4.8 -> 1.4.7 on stable works.  Let me do it again, and get a dump from the deamon.log

**Comment by chrislovecnm** [comment]
stable 1.4.8 -> stable 1.4.7 works like a champ.

testing 1.4.7 -> 1.5.2

**Comment by chrislovecnm** [comment]
stable channel 1.4.7 server -> alpha channel 1.5.2 server works ;)

will finish update and downgrade to 1.4.7 alpha

**Comment by chrislovecnm** [comment]
Cannot reproduce .... maybe I was too impatient
