### ISSUE TITLE
Odd error draining dnscontroller

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1685]
Need to figure out what this is:

```
W0129 01:00:51.186936   64210 drain.go:470] Error attempting to evict pod, will delete pod - err: error when evicting pod "dns-controller-1528204154-bjkhf": Eviction in version "v1beta1" cannot be handled as a Eviction: no kind "Eviction" is registered for version "policy/v1beta1"
```

1. `kops create cluster`
1. `kops edit cluster`
1. `kops update cluster --yes`
1. `kops rolling-update cluster --yes`

You will get the above error message.

**Comment by chrislovecnm** [comment]
Same message with 

```
W0129 01:11:14.072875   64210 drain.go:470] Error attempting to evict pod, will delete pod - err: error when evicting pod "kube-dns-782804071-xwwkm": Eviction in version "v1beta1" cannot be handled as a Eviction: no kind "Eviction" is registered for version "policy/v1beta1"
```

**Comment by justinsb** [comment]
Is this in your WIP PR?  I tried but could not reproduce this.

**Comment by chrislovecnm** [comment]
Yep... in my pr when you do a drain

**Comment by rlmcpherson** [comment]
I'm seeing this too when trying to do a `kubectl drain $node` on a 1.4.5 cluster.  I haven't found a solution for this yet either and this issue is about the only useful google search result that came up.

**Comment by chrislovecnm** [comment]
This was an upstream issue. Closing
