### ISSUE TITLE
Default timeout on create seems a bit long

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1686]
Ran out of quota on VPCs and create cluster ran for 8 min.  Seems kinda long.  What do you think .. 5min for default timeout on the create run?

**Comment by justinsb** [comment]
There are a number of timeouts and retry loops.  If you want to change one, I think sending a PR with the change is the way to go.

**Comment by chrislovecnm** [comment]
Closing, as this is fine
