### ISSUE TITLE
Check behaviour from concurrent `kops delete cluster`

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1695]
We should verify we handle the AWS errors when we run `kops delete cluster` twice concurrently on the same cluster.

cf #1614

**Comment by justinsb** [comment]
Running 3 deletes against a topology=private setup seems a rich source of races.

**Comment by kris-nova** [comment]
I think each of the resources should have a status that each of the goroutines can update.. each concurrent process should check the status (potentially reported back from other goroutines) before attempting to execute.. 

We could track each resource in a data structure that has the new status, and holds the old value as well

But yes +1 to making concurrent deletes smarter/faster/better

**Comment by chrislovecnm** [comment]
wow ... just leaving that there
