### ISSUE TITLE
Seeing timeouts finding location of S3 bucket

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1703]
I think we should do one of:

1) feature-flag it, so it doesn't affect everyone
2) try the "old way" first, and then try the broadcast

cc @tazjin @kris-nova

**Comment by tazjin** [comment]
3. Do a non-timeouted call first, then attempt the broadcast.

**Comment by justinsb** [comment]
An example error, just in case:

`error reading cluster configuration: error reading cluster configuration "simple.example.com": error reading s3://clusters.example.com/simple.example.com/config: Could not retrieve location for AWS bucket clusters.example.com`

**Comment by tazjin** [comment]
@justinsb I'm thinking this: https://github.com/tazjin/kops/commit/8c85935f1f2cf2c4c44b2a7569bcdef08a972f17

(not tested yet, have to run and get a bus first :))

**Comment by justinsb** [comment]
That method feels much safer to me - thanks @tazjin 

But ... does this introduce a long timeout for you (i.e. do you have to wait while the "old way" goes through a retry/backoff loop)?  Or does AWS return an error in your use-case?

**Comment by tazjin** [comment]
It returns an error immediately, the problem is that we can't distinguish the error of my usecase from any other error due to how S3 works.

Tested this now, opening a PR ...

**Comment by tazjin** [comment]
https://github.com/kubernetes/kops/pull/1705

**Comment by tazjin** [comment]
The PR fixes this issue for the "normal use-case", i.e. bucket owners using their own buckets - which is good!

I'd still like to know what caused actual timeouts here, in my testing the AWS APIs were never slow enough to cause one (it's set to 5 seconds). Will investigate that further but we probably don't need to keep this particular issue around.

**Comment by justinsb** [comment]
In my case it seems to happen when the bucket is "cold".  i.e. if you haven't accessed it in e.g. an hour

**Comment by natemurthy** [comment]
I'm using `kops 1.5.3` so I know this change in, but I still see this error message:

```
$ kops create cluster 
  --name=<my-domain> \ 
  --state=s3://<my-bucket> \
  --zones=us-west-2b \ 
  --node-count=2 \
  --node-size=t2.nano \
  --master-size=t2.nano \ 
  --dns-zone=<my-domain>

error reading cluster configuration "<my-domain>": error reading s3://<my-bucket>/<my-domain>/config: Could not retrieve location for AWS bucket <my-bucket>
```

**Comment by tazjin** [comment]
@natemurthy Are you using a cross-account policy?

**Comment by natemurthy** [comment]
@tazjin No, using only one account. Not granting permissions to any other account.

**Comment by natemurthy** [comment]
I've resolved my issue. I had misspelled the bucket name by one character *facepalm*

**Comment by tazjin** [comment]
@natemurthy Good to know, but I'll probably investigate again whether we can get better error messages out of AWS!
