### ISSUE TITLE
ebtables missing?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1711]
User revacuate on slack reported:

> i'm seeing this many times in my kubelet logs on my kops-created cluster using the default AMI: `810 kubenet_linux.go:808] Failed to get ebtables version. Skip syncing ebtables dedup rules: executable file not found in $PATH`

**Comment by snarlysodboxer** [comment]
revacuate on slack is me. let me know if you have any questions.

**Comment by justinsb** [comment]
Actually I haven't been able to reproduce this (yet!)  Can you let me know the `kops create` command you used, along with `kops version`.  You can also send the `kops get cluster -oyaml` if that's easier - feel free to DM it me on slack if your prefer.

**Comment by snarlysodboxer** [comment]
Here's my create command:
`kops create cluster --name dev.k8s.example.com --cloud aws --kubernetes-version 1.5.2 --master-size m3.medium --network-cidr 10.0.0.0/16 --node-count 3 --node-size t2.medium --vpc <vpc ID> --zones us-west-2a`
kops version is `Version 1.5.0-alpha3`.

**Comment by snarlysodboxer** [comment]
@justinsb I'm sorry, it suddenly dawned on me this morning that I had edited the InstanceGroups and set the most recent AMI built buy your AWS user: `image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09`. Maybe the problem is with that image.

**Comment by justinsb** [comment]
No problem at all - thanks for the report!

I can confirm ebtables is not on the image, and kubelet does log that message, at least on 1.5. 

I'll get it added to the 1.5 image!

**Comment by justinsb** [comment]
We added ebtables to nodeup in #1745, so it will be installed on boot (if it isn't already there).  We'll get it into the next image also, to skip the need to download it
