### ISSUE TITLE
Output additional security groups shows always changes

### ISSUE THREAD

**Issue by tsupertramp** [kubernetes/kops#1721]
Hey @justinsb 

the bug i mentioned yesterday is still occurring :(

The output of kops update cluster shows differences (even if the change is already applied):
```
  LaunchConfiguration/nodes.infra.k8s.somedomain
  	SecurityGroups      	 [id:sg-8b49, id:sg-ceba, id:sg-c789] -> [name:nodes.infra.k8s.somedomain id:sg-c789]
  	AdditionalSecurityGroupIDs	 <nil> -> [sg-8b49, sg-ceba]
```

Actual AdditionalSecurityGroupIDs is always returning nil which shows a change every time.

And SecurityGroups contains only the one security group which was created through kops but the launch config has two additional (the one i attached through additionalSecurityGroups).

This is the problem i tried to solve with merging both to one in autoscaling group.

I am unsure how to solve this without merging both. Maybe you have an idea. I would try to implement it then.

Greetings, Thomas

**Comment by chrislovecnm** [comment]
@justinsb moving into 1.5.0 - please move out if it is not a bug

**Comment by justinsb** [comment]
I think we're going to have to merge both.  Given timings, I'm going to move this to 1.5.1 though.
