### ISSUE TITLE
Use non-beta version of Heapster

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#173]
The [Heapster addon](https://github.com/kubernetes/kops/tree/master/upup/addons/monitoring-standalone) currently uses a beta image of Heapster. I was not able to deploy it to my cluster until I switched the image from `gcr.io/google_containers/heapster:v1.1.0-beta2` to `gcr.io/google_containers/heapster:v1.1.0`.

**Comment by yissachar** [comment]
Actually, it seems that even with the non-beta version I have the same problem, where Heapster starts and then dies after a short while. I'll leave this issue open anyway, since it's probably good to use non-beta versions.

**Comment by Skilgarriff** [comment]
Are you using HA master, and or just trying to run Heapster from the files defined in the link you listed? I learned that the way Kubernetes handles addons, is that they must be copied onto the master file system. Any service/pod with the annotation ```kubernetes.io/cluster-service: "true"``` that doesn't exit in the master file system, will be deleted about 5 minutes after it is started. A simple solution is just to remove that annotation and Heapster will still work just fine. Hope that helps!

**Comment by yissachar** [comment]
Thanks, I should have mentioned that I resolved the issue after reading https://github.com/kubernetes/kops/issues/13, which echoes what you're saying.

**Comment by justinsb** [comment]
I've started curating some addons without the problematic annotation and documenting them here: https://github.com/kubernetes/kops/blob/master/docs/addons.md

Going to close, but do reopen if not solved!
