### ISSUE TITLE
Move rolling_update functionality into a service acessible via the api

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1733]
Right now the code for rolling update can only be fired by the cli, we need to move this into the api

**Comment by justinsb** [comment]
Not sure I get it.  You're saying that if we build a kops server that implements an API, we will need to move more of the rolling-update logic out of cmd and into pkg?

**Comment by chrislovecnm** [comment]
Maybe it is my misunderstanding, but if you use the api directly you can run into vendoring problems with k8s api calls.

@kris-nova can you comment on this?
