### ISSUE TITLE
Adopt official componentconfig

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1734]
@mtaufen has said / implied that we should now use the official componentconfig from our versioned copy of kubernetes (possibly after updating).

@mtaufen can you confirm that it is reasonably stable?  And if we can start e.g. kubelet using a componentconfig yaml file instead of marshalling to flags?

Changes that I can see:

1) We currently have to add omitempty and/or convert some fields to pointers, so users don't see default values in the YAML
2) We currently add flags annotations.  We could either write componentconfig yaml files, convert to code, or use an external mapping file
3) I think we could convert any existing schemas using the apimachinery i.e. create `v1alpha3` of the kops API and write conversion functions.  But I'm not sure we should do that if componentconfig is still in `alpha` itself.

**Comment by mtaufen** [comment]
Close, but not quite. It's in my roadmap for this quarter, so maybe that's why it sounded like it was ready?

**Comment by mtaufen** [comment]
Specifically, a yaml file for KubeletConfiguration is in my roadmap. `componentconfig` as a whole still needs some work (see e.g. @ncdc's kube-proxy refactoring https://github.com/kubernetes/kubernetes/pull/34727, I'm also planning some restructuring of the KubeletConfiguration type to make it more readable, etc.), and I'm not sure if that API group will be able to move out of `alpha` in 1.6.

**Comment by ncdc** [comment]
I sure hope it doesn't leave alpha in 1.6. If the community agrees with my refactoring goals, I'd like them to be implemented before the api moves to beta. And that will take time...
