### ISSUE TITLE
kops create -f examples

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1735]
Example kops 1.5.x cluster spec: https://gist.github.com/blakebarnett/bee3b0f57745cd6984c5214c14b71217

HA Instance groups:
https://gist.github.com/blakebarnett/eb95e197a649e1d4000e965e91b2d4f5
https://gist.github.com/blakebarnett/ba59ddb909e23e32ced587f714f31739
https://gist.github.com/blakebarnett/15869404892ccfb835b66d9777fc70a6

Nodes instance group
https://gist.github.com/blakebarnett/228423c14668375895f1ece03a28fc6c

**Comment by yissachar** [comment]
Related: https://github.com/kubernetes/kops/issues/267

**Comment by chrislovecnm** [comment]
Thanks Blake
