### ISSUE TITLE
Changing nonMasqueradeCIDR: in cluster spec doesn't flag for rolling-update

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1737]
I changed our `nonMasqueradeCIDR` to a new subnet (within the previous one if that matters) but after doing `kops update cluster --yes` it didn't think a rolling-update was required, everything is still running on the old CIDR.

**Comment by chrislovecnm** [comment]
See https://github.com/kubernetes/kops/issues/1738

**Comment by justinsb** [comment]
#1738 is prioritized for 1.5.1 now.  I am closing this because it won't be possible after #1738.  But reopen/comment if I'm missing something.
