### ISSUE TITLE
Kops output encoding

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1742]
It would be great if we could start pushing towards a globalized `-o` flag

Something like what `kubectl` has with `-oyaml` and `-ojson`

A lot of what kops generates is valuable data, that could be a bit better in terms on querying.

Thoughts?

**Comment by chrislovecnm** [comment]
There is a issue or a request in a issue to have the capability to do Jain path queries as well. Especially since kubectl has that capability.

My though is that we have to have this ;) This is a must..

**Comment by kris-nova** [comment]
> There is a issue or a request in a issue to have the capability to do json path queries as well. 

How is that different than my original note?

**Comment by chrislovecnm** [comment]
-o json vs https://kubernetes.io/docs/user-guide/jsonpath/

**Comment by chrislovecnm** [comment]
Also go templates are nice as well ... it is another option

**Comment by yissachar** [comment]
The jsonpath issue: https://github.com/kubernetes/kops/issues/1240

**Comment by justinsb** [comment]
No objection to this - it would be great.  But I suggest you attack it in chunks (i.e. one or two commands at a time) if you're going to do it.  Up to you if you want to create individual issues, I don't see how anyone could object to structured output though!

One interesting option could be to have the structured output be the default, and have plaintext be a rendering of it.  But that is probably hard.
