### ISSUE TITLE
Conversion code tracking 

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1744]
Can we (or more importantly SHOULD we) be tracking API members and any necessary conversion code on the testing level?

The concrete example question "What if we define a new API member and there is no conversion code for it? Will the build pass?"

There is a few ways to do this, and this is probably a question for the API-machinery team more than anything.. but it would at least be nice to know where the risks were in kops

**Comment by justinsb** [comment]
We should have:
1) a "did you run `make apimachinery` test" like our govet validation
2) some round trip tests.  We already have some for integration tests for clusters in `tests/integration/conversion`.  More are welcome

**Comment by chrislovecnm** [comment]
I have broken the build on master twice because of last of lack of "did you run `make apimachinery` test".

**Comment by chrislovecnm** [comment]
The incubator project service catalog has an example of how to do this check.

**Comment by robinpercy** [comment]
Going to take a crack at this after discussing with @chrislovecnm 

/assign
/remove-lifecycle rotten

**Comment by justinsb** [comment]
We now have the `verify-apimachinery` target in the makefile, which runs as part of CI

/close fixed
