### ISSUE TITLE
Bastion DNS route53 entries not deleted

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1751]
Beta1 code using API  - we are going to test with cli 

1. Creat cluster with ha and bastion
2. Delete cluster

The bastion dns entry is not removed from route53

**Comment by chrislovecnm** [comment]
@sstarcher I created a ticket here for deletes as they seem to not be fixed by the PR mentioned in this ticket https://github.com/kubernetes/kops/issues/1751

**Comment by sstarcher** [comment]
It looks like the current code likely does not work due to we are setting
bastionPublicName to bastion-CLUSTER
and the code is expecting bastion.CLUSTER which is the default

**Comment by kris-nova** [comment]
^ That was intentional because of SSL reasons

**Comment by sstarcher** [comment]
@kris-nova understandable I think the issue is that the dns cleanup code needs to take that into account instead of assuming `bastion.`

**Comment by sstarcher** [comment]
Taking a look at the code the default is now actually `+			BastionPublicName: "bastion-" + clusterName,
`

**Comment by chrislovecnm** [comment]
@sstarcher I am going to downgrade an move to 1.5.1

**Comment by chrislovecnm** [comment]
Closing this, as I think this is an internal issue.

**Comment by sstarcher** [comment]
@chrislovecnm This should be an issue for anyone who changes the Bastion name from the default.
