### ISSUE TITLE
kops signal handler 

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1752]
I wanted to propose a signal handler for kops.

The use case is a user sending `SIGINT` aka `^C` or `control c` to a kops process

Right now if a user (or a tool) sends an interrupt to kops mid-deploy the cluster resources could end up only being partially created.. We could implement a concept of `die nice` which would clean up resources during an interrupt..

It's a big refactor and requires a lot of thought - but just dropping this in as a placeholder

**Comment by justinsb** [comment]
I don't think we should try to roll-back, but I think we should never leak.  I think this overlaps a lot with #1431
