### ISSUE TITLE
HTTP retries

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1757]
`I0201 15:30:52.287095   42718 apply_cluster.go:589] error reading hash file "https://storage.googleapis.com/kubernetes-release/release/v1.5.2/bin/linux/amd64/kubelet.sha1": error fetching "https://storage.googleapis.com/kubernetes-release/release/v1.5.2/bin/linux/amd64/kubelet.sha1": Get https://storage.googleapis.com/kubernetes-release/release/v1.5.2/bin/linux/amd64/kubelet.sha1: x509: certificate signed by unknown authority`

We had the previous HTTP retry issue, but maybe the SHA reading is not going through this codepath?

**Comment by justinsb** [comment]
AFAICT we are retrying.  It might be that we are reusing the same HTTP connection or something along those lines.  Cannot reproduce at the moment, so punting to 1.5.1 until we have a reproduction.

**Comment by justinsb** [comment]
Going to close until we see this again.  Please comment if you observe it.

**Comment by rajholla** [comment]
Hello @justinsb 
I hit the very same problem today . This happens 100% of the time 

_I0724 14:37:02.938402   31968 utils.go:148] Found matching hosted zone ".ctkube.com", but it was "Private" and we require "Public"
I0724 14:37:12.190493   31968 apply_cluster.go:753] error reading hash file "https://storage.googleapis.com/kubernetes-release/release/v1.6.2/bin/linux/amd64/kubelet.sha1": error fetching "https://storage.googleapis.com/kubernetes-release/release/v1.6.2/bin/linux/amd64/kubelet.sha1": Get https://storage.googleapis.com/kubernetes-release/release/v1.6.2/bin/linux/amd64/kubelet.sha1: x509: certificate signed by unknown authority

cannot determine hash for https://storage.googleapis.com/kubernetes-release/release/v1.6.2/bin/linux/amd64/kubelet (have you specified a valid KubernetesVersion?)_

**Comment by puppetbabu** [comment]
Even i am getting the same problem, any idea how to resolve this issue
vagrant@ubuntu-xenial:~$ kops create cluster --name=kubernetes.babuacadamy.win --state=s3://kops-state-babu99 --zones=ap-south-1a --node-count=2 --node-size=t2.micro -
-master-size=t2.micro --dns-zone=kubernetes.babuacadamy.win
I0122 01:01:09.339514    1831 create_cluster.go:439] Inferred --cloud=aws from zone "ap-south-1a"
I0122 01:01:09.340179    1831 create_cluster.go:971] Using SSH public key: /home/vagrant/.ssh/id_rsa.pub
I0122 01:01:10.793960    1831 subnets.go:184] Assigned CIDR 172.20.32.0/19 to subnet ap-south-1a
Previewing changes that will be made:

I0122 01:01:20.039428    1831 apply_cluster.go:880] error reading hash file "https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1": error fetching "https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1": Get https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1: x509: certificate signed by unknown authority

cannot determine hash for https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet (have you specified a valid KubernetesVersion?)

**Comment by noqcks** [comment]
```
(env) ➜  k8s git:(canadian-kubernetes) ✗ kops create cluster --zones ca-central-1a,ca-central-1b --dns-zone <zone> --ssh-public-key ~/.ssh/<key>.pub <cluster>
I0206 14:03:08.761405   57984 create_cluster.go:439] Inferred --cloud=aws from zone "ca-central-1a"
I0206 14:03:08.762860   57984 create_cluster.go:971] Using SSH public key: /Users/benji/.ssh/ca.alba.support.pub
I0206 14:03:09.056069   57984 subnets.go:184] Assigned CIDR 172.20.32.0/19 to subnet ca-central-1a
I0206 14:03:09.056094   57984 subnets.go:184] Assigned CIDR 172.20.64.0/19 to subnet ca-central-1b
Previewing changes that will be made:

I0206 14:03:10.470285   57984 apply_cluster.go:880] error reading hash file "https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1": unexpected response code "403 Forbidden" for "https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1": <?xml version='1.0' encoding='UTF-8'?><Error><Code>SecurityPolicyViolated</Code><Message>Request violates OrgPolicy constraint.</Message><Details>Request is prohibited by organization's policy</Details></Error>

cannot determine hash for https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet (have you specified a valid KubernetesVersion?)
```

**Comment by alfonsol** [comment]
I also seeing this.  This worked as of friday, so it seems something might have changed:

➜  ~ kops create cluster alfonso-dev.k8s.local --zones us-west-2a   --authorization "RBAC" --networking "weave" --yes 
I0206 11:32:31.005402   37392 create_cluster.go:439] Inferred --cloud=aws from zone "us-west-2a"
I0206 11:32:31.005721   37392 create_cluster.go:971] Using SSH public key: /Users/alfonsolopez/.ssh/id_rsa.pub
I0206 11:32:31.667848   37392 subnets.go:184] Assigned CIDR 172.20.32.0/19 to subnet us-west-2a
I0206 11:32:32.738128   37392 apply_cluster.go:880] error reading hash file "https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1": unexpected response code "403 Forbidden" for "https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1": <?xml version='1.0' encoding='UTF-8'?><Error><Code>SecurityPolicyViolated</Code><Message>Request violates OrgPolicy constraint.</Message><Details>Request is prohibited by organization's policy</Details></Error>

cannot determine hash for https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet (have you specified a valid KubernetesVersion?)
➜  ~ brew update kops

**Comment by noqcks** [comment]
I think perhaps some config on google's side changed

**Comment by noqcks** [comment]
Yep, seems to be working now

```
https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1
```

Thanks google! :)

**Comment by agray-ctm** [comment]
This has reemerged as an issue.. 1.8.6 still.
