### ISSUE TITLE
Kops should have a one-liner to export .yaml for cluster and instance group specs

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#1758]
This would be great to export your configuration and then use  `kubectl create -f` to recreate your cluster at a later time/date.

I don't think that this exists yet, and if it does, we could provide better documentation visibility for a feature that should be useful.

If others like the idea and we can come up with syntax that folks would be happy with, I will take a crack at this for 1.5.1. Re: syntax, `kops export` seems so far to be only related to exporting kube_config files. I think this may be a good place to start, perhaps with flags to choose to export just the cluster spec, one or more igs, or cluster spec and one or more igs, or export all.

**Comment by chrislovecnm** [comment]
`kop get cluster --full -o yaml` is the cluster.  Same for ig.  Once command would be nice.  Kinda like a cluster-info with kubectl

**Comment by ringods** [comment]
The following commands work to get the cluster spec and the concatenated intancegroup specs:
```
kops get cluster --name <cluster-name> --output yaml
kops get ig --name <cluster-name> --output yaml
```

I would expect this to work to get the full spec, but *not* specifying the subcommand:
```
kops get --name <cluster-name> --output yaml
```

**Comment by andyp1per** [comment]
For what it's worth there are a few issues with what is there currently:
- get cluster does not put a yaml separator between the cluster definition and the master instance group
- get ig does not support --full
- get secrets does not support yaml.
Without the secrets you cannot boot the cluster, so seems far from working right now.

**Comment by chrislovecnm** [comment]
> get cluster does not put a yaml separator between the cluster definition and the master instance group

Please provide more details

> get ig does not support --full

`--full` is only used for debugging.  This is a feature you would need.

> get secrets does not support yaml

Not sure what would be the purpose of exporting the secrets.  Are you trying to back up the full configuration of a cluster?

**Comment by andyp1per** [comment]
Hmmn, weird. I can't repro (1) on my windows machine. I'll check tomorrow on my mac, maybe I was mistaken or it is a version thing.

What I'm trying to do is export a configuration like the OP is that I can deploy at a later date. Rather than go through the rigmarole of create cluster/edit cluster/edit ig/update cluster each time. But it seems that's not possible and it seems I can't apply a partial update to a created configuration either. So this manual laborious process is the only way?

**Comment by chrislovecnm** [comment]
We have kops get -o yaml now ;) Closing

**Comment by schollii** [comment]
@chrislovecnm: 
> `kop get cluster --full -o yaml` is the cluster. Same for ig. Once command would be nice. Kinda like a cluster-info with kubectl

Not the same: --full includes all sorts of things that you cannot leave in a cluster YAML that you want to create a cluster with.

**Comment by ozbillwang** [comment]
`kops get cluster -o yaml` doesn't export all configurations.

Seems `edit cluster` has extra details.
```
➤ diff edit.output get.output
40,45d39
<   masterInternalName: api.internal.sydney.team.ahead.guru
<   masterPublicName: api.sydney.team.ahead.guru
<   networkCIDR: 172.20.0.0/16
<   networking:
<     kubenet: {}
<   nonMasqueradeCIDR: 100.64.0.0/10
```

**Comment by ozbillwang** [comment]
`kops get cluster -o yaml` doesn't export all configurations.

Seems `edit cluster` has extra details.
```
➤ diff edit.output get.output
40,45d39
<   masterInternalName: api.internal.example.com
<   masterPublicName: api.example.com
<   networkCIDR: 172.20.0.0/16
<   networking:
<     kubenet: {}
<   nonMasqueradeCIDR: 100.64.0.0/10
```
