### ISSUE TITLE
DNS record for .api not being updated to ELB

### ISSUE THREAD

**Issue by apenney** [kubernetes/kops#1759]
Hi,

In my first usage of kops I managed to bring up a cluster that had a DNS record for api. that pointed directly at the masters.  When attempting to upgrade using 1.5.X (a HEAD build) the rolling upgrade replaced all my masters/nodes but didn't touch the DNS record, leaving it pointing at terminated masters.

At this point I was unable to fix the cluster and ended up destroying it.

**Comment by chrislovecnm** [comment]
@apenney I will test, but the dns-controller container on the master should have updated the masters.  I am working on a big refactor for rollling-updates, as it validates the clusters after each node.  You open to testing?

**Comment by apenney** [comment]
I'll test anything, any time, no problem!

**Comment by justinsb** [comment]
I suspect this is the issue:

```
W0202 02:54:44.668441       1 dnscontroller.go:118] Unexpected error in DNS controller, will retry: error applying DNS changeset: InvalidChangeBatch: RRSet of type CNAME with DNS name logs.useast1.k8s.example.com. is not permitted as it conflicts with other records with the same DNS name in zone example.com.
        status code: 400, request id: f380e821-e8f2-11e6-9752-39814199c4de
```

**Comment by justinsb** [comment]
That happens when I have an A record, but try to add a CNAME to the ELB.

**Comment by apenney** [comment]
I think this is long resolved now.
