### ISSUE TITLE
Cannot do 1.5.2 alpha to 1.4.8 alpha rolling update

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1760]
I don't there you should be able to :)  But it would be good to validate it

**Comment by justinsb** [comment]
Tried a downgrade from 1.5.2 to 1.4.8, (not HA & with the 1.4 image).  Running kops 1.5.0 beta2.  No problems were observed.

Can you post the issue you are seeing?

**Comment by chrislovecnm** [comment]
```
	KOPS_STATE_STORE="s3://my-state-store" \
	kops create cluster foo.dev.datapipe.io \
	--yes \
	--zones eu-west-1a,eu-west-1b,eu-west-1c \
	--master-zones eu-west-1a,eu-west-1b,eu-west-1c \
       	--channel alpha \
	--bastion \
	-t private \
	--networking weave \
	-v 10 |& \
	tee /tmp/kops.out
```

`kops edit cluster` <- change version to 1.4.8
`kops upgrade --yes`
`kops rolling-update --yes` <- I am on my PR, but I am 80% certain it is not my PR

Docker does not install on the master

**Comment by geojaz** [comment]
I think we can close this stale issue that relates to very old alpha versions
