### ISSUE TITLE
improve Rolling Updates for PetSets / Stateful Sets and other upgrades

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1773]
We need a story on how we are going to handle PetSets / StatefulSets and other API versioning challenges.

PetSet and Stateful sets are special, as only on Pet / Set Member per PetSet or Stateful set can be deleted at one time.  @bprashanth mentioned:

>  i think the idea was to achieve it through PDB (pod disruption budget), so your normal deletes/drains would work the same way always, and respect PDB, which would probably default to "never delete more than 1 pod at a time" for petset. Suggest asking for status on https://github.com/kubernetes/kubernetes/issues/33727, since it's on the kubectl team to finish that up.

Technically you should only delete one pet at a time and let the petset normalize.  A well designed petset deployment utilized anti-affinity rule to ensure that multiple pets are on the same node.  Again this is complicated and needs to mature over time.  I appreciate @justinsb having me put it in a feature flag.  I am making a note to put this into an issue

> I think @foxish and/or @ymqytw might have context on the status of drain and petset

I believe it is a valid use case to Drain and move pets. Customers will be using 1.4 for a while.  Moreover 1.5 we have StatefulSets, which are now supported by drain.

We also have the transition of APIs between version.

I am uncertain of the need driving this at this point, and it would be good to get some community feedback.

We also have a need to have a story within rolling-update for how to handle k8s contract changes.  At this point kubectl has some support for backwards compatibility, but the go library may be more compatibie.  These stories need to be developed and designed.

**Comment by justinsb** [comment]
Who _does_ drain correctly - kubectl or X?  We should reuse whatever code works.

**Comment by chrislovecnm** [comment]
@justinsb nobody does yet ... :rimshot

**Comment by justinsb** [comment]
Who does it best?
