### ISSUE TITLE
should we have a pre-commit hook for users

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1778]
We as developers sometimes we forget to run `make ci` before with commit code.  Can we get a pre-commit hook example.

**Comment by justinsb** [comment]
kubernetes has a pre-commit hook.

**Comment by chrislovecnm** [comment]
@justinsb yes it does, and it is pretty brutal to use ... aka long long time

**Comment by justinsb** [comment]
Implemented in #2561 - thanks @WillemMali
