### ISSUE TITLE
Install gluster in the base image

### ISSUE THREAD

**Issue by apenney** [kubernetes/kops#1780]
As mentioned in the last comment in https://github.com/kubernetes/kops/issues/387, gluster is a supported volume type in Kubernetes but you need the base gluster packages installed on the node AMI.

I'm happy to help add this, but I could do with help finding the right place.

**Comment by owenhaynes** [comment]
If we adding gluster should  cephfs  be added as well?

**Comment by FrederikNS** [comment]
We're currently looking at rolling out Ceph as our cluster filesystem, so ceph packages on the nodes would be very helpful indeed.

**Comment by FrederikNS** [comment]
@apenney: As a workaround we have successfully added the require Ceph package to our cluster using the newly released "hooks" in kops.

To make it work we simply added this snippet to our cluster spec:

    hooks:
    - execContainer:
        command:
        - sh
        - -c
        - chroot /rootfs apt-get update && chroot /rootfs apt-get install -y ceph-common
        image: busybox

I'm sure this can be modified to accommodate Gluster as well

**Comment by chrislovecnm** [comment]
Can we close as we have hooks that can do this?

**Comment by chrislovecnm** [comment]
Closing since we have hooks
