### ISSUE TITLE
Add support for timezones / user data

### ISSUE THREAD

**Issue by dlutsch** [kubernetes/kops#1794]
We have a need to create our kops nodes in PST rather than UTC. It would be helpful if kops either had an option to set the instance timezone via the ig config, or if ec2 user data could be passed in order to set that.

**Comment by justinsb** [comment]
Hmmm... that's an unusual request :-)  Do you mind if I ask why?

(I'm wondering if the pods inherit the node timezone, and whether they should).

Also I presume this would be a cluster-wide setting, or do you really mean per-instancegroup?

I'm torn between a label/annotation on the cluster, vs allowing you to run a custom script at bootup.  We could also just do a property, as I guess most people won't even see it unless they need it.

**Comment by chrislovecnm** [comment]
I have worked in IT groups where they want to run their servers in a certain TZ.  @dlutsch I would recommend modifying the base ami to set your TZ.  Admittedly I never recommend running servers in non-UTC tz, but I understand you may have other requirements.

**Comment by mirague** [comment]
I agree, having an ability to pass in EC2 user data would be extremely helpful.

**Comment by igoratencompass** [comment]
+1 on user-data

**Comment by justinsb** [comment]
We're discussing different approaches to this:
https://github.com/kubernetes/kops/pull/1766
https://github.com/kubernetes/kops/pull/2260

"User-Data" can be a lot of things - if you have specific use cases that would be handy to help figure out what we need to support.

I have noted:

* setting the timezone
* install extra packages

The problem with "just use cloud-init" is that some distros support different versions of cloud-init (CoreOS) and some don't support cloud-init at all (Container-Optimized OS).  Also kops itself uses cloud-init on OSes where it is supported, and it isn't necessarily trivial to just combine two operations.

**Comment by swestcott** [comment]
@justinsb We're using CoreOS/Container Linux. I've listed some of our use cases below. I realise we could achieve some of these by rolling our own AMI, but we're keen stick with CoreOS's AMI to take full advantage of Container Linux's "[auto update](https://coreos.com/os/docs/latest/update-strategies.html)" feature. Even with a custom AMI, we'd need to provide some environment config for prod vs non-prod clusters.

* Configure SSSD/Kerberos
* Load additional systemd services/units e.g. forward SSHD denys to our corporate SIEM platform, register nodes with our CMDB
* Apply relevant recommendations from [CIS docker benchmarks](https://benchmarks.cisecurity.org/downloads/show-single/index.cfm?file=docker13.100)
* A custom MOTD :)

**Comment by venth** [comment]
How can I adjust timezone for kops 1.7? Is there any workaround for now?

**Comment by chrislovecnm** [comment]
@venth I typically run the image in UTC.  If you really need to, you could use a hook to change the TZ, which is NOT tested :)  Here is more information on hooks https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#hooks

**Comment by venth** [comment]
Thanks :+1:

**Comment by mayrbenjamin92** [comment]
/reopen

We would also love to have support for this!
