### ISSUE TITLE
Possibility to activate EBS-optimized flag on nodes

### ISSUE THREAD

**Issue by spiddy** [kubernetes/kops#1808]
Is there a way to activate "EBS-optimized" flag on the worker nodes?

I've started m4.2xlarge instances which should be [EBS-optimized by default](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html), but kops gives me instances with EBS-optimized set to false.

**Comment by chrislovecnm** [comment]
Thanks for your report!  We would have improve our API calls to be smart enough to specify EBS optimized.  Contributions are always appreciated!

**Comment by tcf909** [comment]
Was this ever implemented? Maybe as an IG flag? Noticed that on 1.5.6 it still doesn't create an ebs optimized instance by default (without an additional flag). Wondered if there was a manual flag to force this for now?

**Comment by ahawkins** [comment]
In theory you may be able to modify the launch configuration outside of Kops to set this flag in the mean time.

**Comment by ahawkins** [comment]
Is there a scenario why we should _not_ use EBS optimization? Kops is production grade stuff. Should this be hard coded to true or supported via a flag?

**Comment by tcf909** [comment]
Definitely think it should be a flag. Some instances offer ebs but at an
additional cost. Others offer ebs with the cost included. There will be
plenty of scenarios that ebs isn't a requirement.

**Comment by tavispaquette** [comment]
+1

**Comment by zachaller** [comment]
I agree it would be nice to control for the instances that are not on by default however i did find this

https://forums.aws.amazon.com/message.jspa?messageID=648952

```
I have confirmed that the EbsOptimized setting is ignored for instance types that are EBS-optimized by default; the instance is always EBS-optimized.

I have also submitted a request that the API always return that this setting is enabled.
```

I don't think his request every went through about the getting the API to always return true

**Comment by sjbeskur** [comment]
Is this a setting that can be accessed via the cli ( eg kops create cluster ..... --node-volume-optimize=true ) or is this configured somewhere else?  What am I missing?

**Comment by sjbeskur** [comment]
I have managed to figure this out by editing the nodes instance group, however, you must make sure that your instance types support EBS optimization.   (note t2.medium instances do not support EBS optimization)   If you try to set rootVolumeOptimization: true with and machineType that does not support EBS optimization nodes will be stuck in the pending state and kops cluster validation continues to fail.  

`kops edit ig nodes --name <your-cluster-name> `

```
spec:
   machineType: t3.medium
   rootVolumeOptimization: true
   ...
   ...

```

t3.medium instances actually support this by default so adding the rootVolumeOptimization attribute is likely redundant

hope this helps someone
