### ISSUE TITLE
weave dashboard service defaults as nodeport 

### ISSUE THREAD

**Issue by hollowimage** [kubernetes/kops#1818]
https://www.weave.works/documentation/scope-latest-installing/#k8s

should probably be load balancer, no ? :) 

but since weave is an official networking provider with kops, adding this into addons list with a few proper changes for aws might make it much easier to get up from first princples.

**Comment by errordeveloper** [comment]
@hollowimage you can use `https://cloud.weave.works/k8s/scope.yaml?k8s-service-type=LoadBalancer` 👍
