### ISSUE TITLE
Kops and changes from github master

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/kops#1820]
An existing kops binary can be broken due to changes to github master.  Kops channels are pulled from github master and if a bad commit or made or just an incorrect change it can affect all existing kops binaries that have been released.

**Comment by justinsb** [comment]
Somewhere we have an issue to support an alternative vfs base path, so you could have your own mirror.  We're now pretty close - see `BaseUrl` in urls.go - I think we just need to move remaining files to the kops base dir and then make it easy to mirror it.

Is there something additional you had in mind though @sstarcher ?

**Comment by sstarcher** [comment]
I would like to see the channels embedded into the kops binary.  Or at least have a flag to use a channel embedded into the binary.

**Comment by chrislovecnm** [comment]
Can we close as you can use your own channels file
