### ISSUE TITLE
Create a docs style guide

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#1829]
As the kops documentation continues to grow (quickly!) and there are more and more folks helping write them, it gets more difficult to keep things consistent. I realized this while looking at a PR that had cluster names in it. What should we call these example clusters?

I don't think we need anything as extensive as [kubernetes.github.io](https://kubernetes.io/docs/contribute/style-guide/), but I think a really quick and simple style guide with some clarification may make life easier for both authors and reviewers and our big push for documentation.

**Comment by chrislovecnm** [comment]
Well we are planning on moving our docs to kubernetes.io.  Can we use there style guid?

**Comment by kris-nova** [comment]
@geojaz this is a great topic!  Thank you so much for bringing this up.

Can you please PR this per our discussion? This is a critical path for the bigger docs push. 

### Notes from talk :
1. Glossary
2. Specification on when to use which headers
3. Explicit specification of *tense* when writing docs
4. Explicit specification of *keyword* usage when writing docs

Remember we want to keep this simple, neat, and clean. Cheers!

**Comment by chrislovecnm** [comment]
Already started. Closing
