### ISSUE TITLE
Install any additional requirements in nodeup

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1830]
Just like ebtables, we should put ethtool in the base image (the 1.4 image is currently missing it), but we should also make sure we install it in nodeup for people that might not have it in their image anyway.

**Comment by chrislovecnm** [comment]
should we install all the prereqs for kubectl?  I don't know the issue, but there are a bunch.

**Comment by justinsb** [comment]
@chrislovecnm if they are hard requirements, yes.

**Comment by chrislovecnm** [comment]
@luxas I remember reading an issue that you had commented on.  Do we have a list of pre-reqs that K8s requires to run?  Such as docker version x and ethtool version y?

**Comment by itskingori** [comment]
For future reference sake, @chrislovecnm this is probably the list you were referring to ... https://github.com/kubernetes/kubernetes/issues/26093. There's also this discussion about the requirement of `ethtool` as a dependency (https://github.com/kubernetes/kubernetes/pull/30356).

I can't find any mention of an `ethtool` version requirement anywhere.

**Comment by chrislovecnm** [comment]
I think the image is stable, can we close?

**Comment by itskingori** [comment]
@chrislovecnm yes (not sure if the question was directed to me).

**Comment by chrislovecnm** [comment]
@justinsb can reopen if we need to...
