### ISSUE TITLE
Use an existing route table for an existing VPC (private topology)

### ISSUE THREAD

**Issue by ketzacoatl** [kubernetes/kops#1832]
If you tell kops to use an existing VPC, it will create new route tables for the new subnets. If you have an existing route table in the VPC, which is already setup to connect the VPC with a corporate network, you would need to reassign the tables for kube's subnets. It would be nice to be able to kops to use the VPC's route table.

From @justinsb:

> If you open an issue, I can make it so that we use the existing route table for an existing VPC in the case that you are not using kubenet

**Comment by chrislovecnm** [comment]
Need to check if we can do shared tag now. But we should be able to bypass this with phases

**Comment by ketzacoatl** [comment]
It's hard to keep up with the bot closing issues, sorry for missing the messages, I don't think this issue should be closed.

**Comment by shaunokeefe** [comment]
Would be keen for this one to be re-opened. 

Very much need this to run Kubes in our existing VPC to make it work our VPN.

**Comment by olemarkus** [comment]
Just in case you aren't aware, if you can also live with shared subnets, not only shared route tables, you can specify an existing subnet like this: https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md#advanced-options-for-creating-clusters-in-existing-vpcs

This allowed us to run multiple cluster without having to add all the VPN/VPC Peers/DirectConnect routes for each cluster.

**Comment by olemarkus** [comment]
It is not that easy to create and configure all the networking pieces that kops/K8s require. What we did was to let kops create the subnet by specifying CIDR as normal. When first cluster has been provisioned, switch the CIDRs with the subnet IDs instead. This cause kops to change tags from owned to shared, allowing it to be used by other clusters.

**Comment by shaunokeefe** [comment]
Excellent idea. Thanks heaps @olemarkus!
