### ISSUE TITLE
Create Master Plan to Improve and Re-Factor Existing & Missing Documentation

### ISSUE THREAD

**Issue by scottmwebber** [kubernetes/kops#1833]
Develop plan to 
a) Discover, Refactor, Create High Level Documentation for KOPS
b) Refactor existing end user documentation to organize and consolidate for improved end user experience

**High Level documents** - _Publish on kuberenets.io_
1. KOPS Value Proposition
2. Roadmap 

**End User Documentation** - _Publish on kuberenets.io_
1. Guides - Publish user guides on a project website (kuberenets.io or anything other than source code)
 - Installing and configuring kops (e.g. configuring the state store and all that)
 - Deploying a new cluster to new infrastructure. See outline below:
- Configuring DNS
- Deciding a topology
- Deciding on DNS (public vs private)
- Adding a bastion
- Sharing access to the cluster
- Making changes to the cluster
- Adding multi-masters
- Deploying a cluster to exiting infrastructure. 
- Prerequites: deciding what topologies and other things are supported for your deployment scenarios
- Which information to pass to kops
3. Tutorials - _Publish on kuberenets.io_
4. Concepts - Not sure about target 
- Document all infrastructural difference between topologies and their implementation detail
5. Reference _- In https://github.com/kubernetes/kops_
6. Tools - - _In https://github.com/kubernetes/kops_
7. Samples - - _In https://github.com/kubernetes/kops_

Previous Contributors
@chrislovecnm @kris-nova @justinsb @ahawkins @blakebarnett @apenney @yissachar 

#1754 
#1829 
#1735 
#1649 
#223

**Comment by chrislovecnm** [comment]
1. Document GCE
2. Document all env variables.
