### ISSUE TITLE
Allow opt-in to etcd3

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1836]
If etcd3 in 1.6 continues to look like a "go" on GCE, we should allow kops users to opt-in  (we probably should let people opt-in anyway, but we might need an "IAmDoingThisAtMyOwnRisk" FeatureFlag!)

One option is to do the same thing we do for networking:

```
storage:
  etcd2: {}
```

and 

```
storage:
  etcd3: {}
```

This would also allow further customization in future - for example running with encryption etc.

**Comment by chrislovecnm** [comment]
So how the heck do we upgrade :)  🙊

**Comment by mad01** [comment]
One option can be to add a opt in to create with etcd3 and leave upgrade unsupported as a start to allow new cluster to be created with etcd3. 

what is your new of that?

**Comment by zioalex** [comment]
I like this idea and looking how to migrate to etcd3 . Any concrete plan here?

**Comment by chrislovecnm** [comment]
We have this in place now
