### ISSUE TITLE
make NAT/EIP optional in private network topology

### ISSUE THREAD

**Issue by ketzacoatl** [kubernetes/kops#1839]
1.5.x introduced some great work on the "private network topology". ATM, when you tell `kops` to create a cluster in the "private network topology", with private DNS and all that, `kops` assumes you want EIP and NAT to provide egress for the cluster. I believe that's a great default for the private topology.

It would add a lot of flexibility if `kops` would let you "bring your own network", where the VPC, subnets, route tables, and gateways are setup and `kops` brings the ELBs, ASG, user data, etc. #1832 is a step towards that, and this ticket is about "making NAT and EIP" optional. EG, if I can tell `kops` to ignore the NAT/egress for this network, I've got it already setup in the existing VPC.

In a general sense, my use case is to "deploy a kubernetes cluster to a private VPC on AWS that is connected to a corporate network". How the network is connected doesn't matter - I can create the VPC/subnets/etc if that is needed. To do this, I use `kops edit cluster ...` to tell kops which subnets to use, which is a little cumbersome, but works well enough.

**Comment by chrislovecnm** [comment]
@ketzacoatl kops allows for `kops create cluster -f` - what would you need beyond that?  You can look at a full cluster spec with `kops get cluster mycluster.name.com -o wide --full` you feed that and the instance groups specs in, and it is a single command to create a cluster with you vpc and subnets info.

**Comment by ketzacoatl** [comment]
Maybe I am not seeing what you are referring to. Sorry, I'm not clear on your suggestions.

I will try to explain my request more clearly: if you use `kops create cluster --dns private --topology private --networking weave --dns-zone my.domain.net ...` to create a cluster. `kops` will include NAT, IGW, and EIP resources for the cluster to use. I believe it would be useful if `kops` made the NAT/IGW/EIP optional, so if "private network" means something different from what `kops` will provide by default, we have the option to provide that network to kops.

**Comment by sidewinder12s** [comment]
Agreed, I've got full public/private networking setup in most of our VPCs with Direct Connect/VPNs so I wouldn't want/need the EIPs or NAT Gateway's setup.

@ketzacoatl Did you find a way to do this?

**Comment by ketzacoatl** [comment]
@sidewinder12s, As Chris eludes to, you can use Terraform/etc to build out your VPC as you wish, and then use `-f` to feed in a spec that has the right references to the subnets (and/or security groups/etc). I don't remember if you can skip the NAT in there, or if kops complains about that. ATM I have the NAT included for a different requirement, but I expect that to change in the future.

**Comment by sidewinder12s** [comment]
@ketzacoatl Ya, as I looked into more of the docs that seemed like a possible option. I'll see if I can try that out and set the proper networking & remove the NAT instance from the template and see what happens.

**Comment by chrislovecnm** [comment]
Phases will actually assist with this

/assign

**Comment by BobbyJohansen** [comment]
I also need to be able to not create NATs as I would like to stand up a cluster attached to already existing infrastructure and EIPs are limited per aws account.
