### ISSUE TITLE
Add NIC (maybe with a homegrown proxy) to AccessSpec

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1840]
So as it stands the main AccessSpec avenues are

1. DNS
2. ELB

https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/cluster.go#L242

```go
type AccessSpec struct {
	DNS          *DNSAccessSpec          `json:"dns,omitempty"`
	LoadBalancer *LoadBalancerAccessSpec `json:"loadBalancer,omitempty"`
}
```

Can we investigate the use of using AWS NICs (with our without some sort of proxy) as a potential third access type?

**Comment by fejta** [comment]
Testing...
/close

**Comment by fejta** [comment]
Woo!
/reopen
