### ISSUE TITLE
Kops generate Cloud Formation code for AWS

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1841]
This is an issue to track the progress of generating [official AWS Cloud Formation](https://aws.amazon.com/cloudformation/) code with kops.

### Success Criteria

1. Generate Cloud Formation code for all permutations of clusters.
2. Support for JSON and YAML encoding ([link](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#aws-resource-cloudformation-init-syntax))
3. Comparable UX and flow as `--target terraform`

##### Output

1. Output to `STDOUT`
2. Output to file system
3. Output to AWS API

CC @jbeda @justinsb

**Comment by ahawkins** [comment]
What's the use case? Also I guess why not use CloudFormation for all AWS operations instead of the internal homegrown thing? I see this being useful as means to replace the internal implementation.

**Comment by kris-nova** [comment]
So @jbeda had a great suggestion (that we will probably need to get in for this feature 😉)

But we would like to include meaningful comments for each of the resources that explain what they do. An example of doing this can be found [here](https://github.com/DualSpark/kops/blob/07eb92fd436b445cc37d02aa26030676bc1b251a/upup/models/cloudup/_aws/topologies/_topology_private/network.yaml)

**Comment by kris-nova** [comment]
@ahawkins the use cases are providing an AWS native approach to defining and deploying k8s clusters. Something that is going to be necessary as we start to tell the "What does an official AWS k8s cluster look like" story.

**Comment by scribnar** [comment]
Does Kops create CloudFormation configuration? or does it provision the resources as needed such that any major failure is unlikely to be restored like in case that can happen if we use CloudFormation in conjunction?

**Comment by chrislovecnm** [comment]
Yes kops now supports basic cf.

Closing as we have basic support.

**Comment by srflaxu40** [comment]
So with the cloudformation option / target could I generate the template and then just upload it to AWS?  How would this effect an already-existing cluster?

**Comment by Raffo** [comment]
@chrislovecnm What does "basic" mean here?
