### ISSUE TITLE
Support API via ingress

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1849]
We should implement support for API via ingress - including when the ingress runs on a hostPort.

**Comment by kris-nova** [comment]
Would this be another addition to the `AccessSpec` data structure?

If so, another proposal for an addition is here https://github.com/kubernetes/kops/issues/1840

Regardless,

Shipping k8s native ingress here is hands down a requirement!

**Comment by hjacobs** [comment]
Shameless plug: we are running our [Kube AWS Ingress Controller](https://github.com/zalando-incubator/kube-ingress-aws-controller) + [Skipper with Kubernetes client](https://github.com/zalando/skipper) + [Mate](https://github.com/zalando-incubator/mate) (External DNS) for Ingress with ALB/ELBv2 on AWS in production.

See https://github.com/zalando-incubator/kubernetes-on-aws/issues/169 for a big picture.

NOTE: support for HTTP (non-SSL) still needs to be implemented.
