### ISSUE TITLE
Kops route53 record update... is it possible to know when it happens?

### ISSUE THREAD

**Issue by brunoriscado** [kubernetes/kops#1850]
I'm trying to automate the cluster creation with KOPS, however after the master gets created and the A record inserted into route53, there's a window of time during which I cannot communicate with the master using kubectl... I'm assuming this is due to DNS propagation, ttl, etc.

I know from the AWS cli we can wait for changes to records, how can I do this, is there a way to do this with KOPS, so that we know when the master is ready to had addons, such as the dashboard, installed?

thanks

**Comment by zytek** [comment]
if I were you I would implement simple `kubectl cluster-info`loop and wait till it `returns 0`and then proceed with installing addons.

**Comment by brunoriscado** [comment]
@zytek - funny, that exactly how I ended up doing it...

`
pollMaster() {
    kubectl --kubeconfig=${KUBECONFIG} cluster-info
    if [ $? == 1 ]; then
       pollMaster;
    else
        echo "Kubernetes master is running";
    fi
}
`
