### ISSUE TITLE
RFC: Kops Webinar Outline

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/kops#1855]
This issue is an RFC on my outline for a kops webinar I'm doing. You can find more details on my [blog](http://blog.slashdeploy.com/2017/02/11/real-world-kubernetes-webinar-series/). I'd like some feedback on my outline and to make sure the maintainers (@justinsb, @chrislovecnm, @kris-nova) have input into how their project is marketed and things they think prospective users should know/understand.

Webinar Date: First half of April

## Abstract

_kops_ is "the way" (tm) to provision, manage, and maintain Kubernetes clusters on GCP and AWS. You should use kops if you're not using a hosted solution._

## Outline

* Introducing `kops` & cluster ops
    - What is "cluster ops"
    - What kops is; official Kubernetes project
    - What it can do; high level infrastructure provisioning and maintenance
    - Use cases; best fit use cases; known limitations; potential red flags
*  Provisioning
   - Creating clusters
   - Public vs private topologies
   - Deploying to an existing VPC
   - Multi masters
   - Bastion servers
   - Network managers
   - Extra configuration (k8s versioning etc)
   - `.kubecfg` sharing
* Demos
   - Create a cluster
   - Update it in some way
   - Deploy nginx
   - Export and share the `.kubecfg`

I submit this outline to you to be transparent with you, and with an open heart and mind. Thank you for all you hard work on such an important project. I hope my webinar can introduce `kops` to more people and help them in your work. Thank you lovely kops maintainers ❤️

**Comment by kris-nova** [comment]
@ahawkins this is so great. Thank you so much for doing this! This hits me right in the feels.

A few notes on what you have so far.

1. The `kops` project spawned out of the community. I think it would be super valuable to call out how `kops` is not only a representation of community needs on a software level, but the project itself encapsulates and is our best snapshot of the deployment/operational community within k8s.

2. A note on scope. The `kops` project is a feature rich provisioner, **as well** as a k8s bootstrapper (nodeup). It might be important to call out the fact that `kops` has a decidedly larger scope than other tools.

3. HA (Highly Available) clusters. This (hands down) is one of the biggest attractions to the project. The native support for running HA k8s clusters with kops is huge. Maybe call that out somewhere?

**Comment by ahawkins** [comment]
> A note on scope. The kops project is a feature rich provisioner, as well as a k8s bootstrapper (nodeup). It might be important to call out the fact that kops has a decidedly larger scope than other tools.

@kris-nova can you tell me a bit more about this?

**Comment by ahawkins** [comment]
@kris-nova The session has been recorded! You can find it here: https://cloudacademy.com/webinars/cluster-ops-kops-49/

Thank you all Kops maintainers ❤️
