### ISSUE TITLE
CoreOS is #NoSocat

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1861]
So for some reason coreos hates socat :-)

@philk pointed this out in https://github.com/kubernetes/kops/pull/1813#issuecomment-278822176 , referencing https://github.com/coreos/bugs/issues/1114  It looks like one workaround would be to install socat.

@aledbf suggested we could also use hyperkube

If socat isn't easily available for coreos, we could also write our own just-enough-socat implementation in go, and avoid the binary problems ( `gocat` ).  But I need to check how we are using socat...

**Comment by aledbf** [comment]
@justinsb just in case I am not suggesting hyperkube :)

**Comment by aledbf** [comment]
@justinsb this can be closed now.

**Comment by chrislovecnm** [comment]
Closing
