### ISSUE TITLE
Map Docker 1.12.6

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1865]
Let's define the package mappings for docker 1.12.6 - or figure out if we can avoid having to map them.

It looks like 1.12.6 is going to be validated: https://github.com/kubernetes/kubernetes/issues/40061

**Comment by robinmonjo** [comment]
Any progress on this ? We are currently stuck with docker 1.12.3 which is known for its deadlock issues.

**Comment by alex88** [comment]
Now that 1.6 is almost released I think it'll be safe to move on 1.12.6

**Comment by Steniaz** [comment]
This PR has been merged: https://github.com/kubernetes/kops/pull/2283
So I guess this issue can be closed?

**Comment by robinmonjo** [comment]
Yes probably. Will we be able to install docker 1.12.6 on a kubernetes 1.5.6 cluster ?

**Comment by Steniaz** [comment]
If you upgrade to the latest kops version when it gets released with this PR. Then I guess you should be able to.

**Comment by ebbeelsborg** [comment]
@robinmonjo , we installed Docker 1.12.6 (via kops 1.6.0-alpha.2) on several k8s 1.5.2 clusters last week and have had no issues with it (so far).

**Comment by robinmonjo** [comment]
Thank you @ebbeelsborg for your feedback, I guess this + https://github.com/kubernetes/kops/issues/2279 should fix docker deadlocks issues for good. Still using docker 1.12.3 but with the "docker nany" script and had no issue. I'll plan to update to docker 1.12.6 when kops 1.6 get released

**Comment by chrislovecnm** [comment]
@justinsb is this work done?

**Comment by chrislovecnm** [comment]
Closing as 1.12.6 is in the docker model
