### ISSUE TITLE
Canal Networking: Pod Gets Evicted First

### ISSUE THREAD

**Issue by brandoncole** [kubernetes/kops#1874]
I was super excited to try out the Canal networking this weekend on Kubernetes 1.4.8.  I gave this commit a spin:

* Kops https://github.com/kubernetes/kops/commit/991fc5b

Ran it on a pretty heavily loaded cluster over 48 hours.  When the nodes started to face some significant resource pressure, Canal was the first thing to be evicted from the cluster with the error: `The node was low on compute resources.`

```
kube-system   canal-2hptv   3/3       Running            0          1d
kube-system   canal-8fq9v   0/3       Evicted            0          1d
kube-system   canal-96l0x   3/3       Running            0          1d
kube-system   canal-sstou   3/3       Running            0          1d
kube-system   canal-uvi2a   0/3       Evicted            0          1d
kube-system   canal-vm621   3/3       Running            0          1d
```

Without networking, this had a cascading effect on other things of course.  Thoughts on whether we can configure Canal to prevent eviction?

@heschlie @justinsb @chrislovecnm @sstarcher

**Comment by brandoncole** [comment]
After talking to @sstarcher he referred me to this which I thought I'd add here as a technical implementation note: 

* https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-qos.md 

We need to configure this as a `Guaranteed` pod rather than a `Best Effort` pod which gets killed first.

**Comment by kris-nova** [comment]
Completely agree.. Notes from link above that summarize the concern here:

> Memory is an incompressible resource and so let's discuss the semantics of memory management a bit.

- Best-Effort

 > pods will be treated as lowest priority. Processes in these pods are the first to get killed if the system runs out of memory. These containers can use any amount of free memory in the node though.

- Guaranteed

 > pods are considered top-priority and are guaranteed to not be killed until they exceed their limits, or if the system is under memory pressure and there are no lower priority containers that can be evicted.

This doesn't seem like a configuration option, this seems like a hard requirement we need for something as critical as an overlay network. +1 Just adding it in where @brandoncole suggested.

**Comment by sstarcher** [comment]
Agreed I know the Weave setup has the same issue. This should be the default setting and a user should not be able to configure it.

**Comment by chrislovecnm** [comment]
Cc @bboreham

**Comment by chrislovecnm** [comment]
cc @heschlie

**Comment by chrislovecnm** [comment]
So to be clear this will help with memory eviction, and we are guessing we are seeing disk eviction with weave.

**Comment by chrislovecnm** [comment]
@mihok adding you hear as well, since we should have resource limits on flannel as well

**Comment by bboreham** [comment]
PR #1894 for Weave Net

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by sstarcher** [comment]
#1894 is not sufficient, but if you consider #1908 to cover the rest of the work I guess you can close this.

```ExperimentalCriticalPodAnnotation``` still needs supported

**Comment by chrislovecnm** [comment]
I am working on `ExperimentalCriticalPodAnnotation` so closing this.
