### ISSUE TITLE
Unable to ssh to cluster using key provided while creating cluster

### ISSUE THREAD

**Issue by csarora** [kubernetes/kops#1876]
Issue : Unable to ssh to cluster using key provided while creating cluster
I tried steps as mentioned in : https://github.com/kubernetes/kops/blob/master/docs/security.md#ssh-access  but no luck, infact i see the sshpublickey remained same before or after the steps. Please help what can i do?

**kops version**
Version 1.5.0-alpha4
 **kubectl version**
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
_**Unable to connect to the server: dial tcp 203.0.113.123:443: i/o timeout**_

kops create cluster --cloud=aws \
  --dns-zone=k8s.test --master-size=t2.2xlarge \
  --master-zones=eu-west-1c \
  --network-cidr=172.31.0.0/16 --node-count=2 \
  --node-size=t2.2xlarge \
  --zones=eu-west-1c \
  --ssh-public-key=/root/.ssh/key.pub\
  --name=sak.k8s.tes

root@ip-172-31-26-62:~/.ssh# **kops get secrets --type sshpublickey admin**
Using cluster from kubectl context: sak.k8s.test

TYPE            NAME    ID
SSHPublicKey    admin   c2:bc:96:21:e3:24:93:1f:f1:a0:a5:7f:2f:85:f7:23

root@ip-172-31-26-62:~/.ssh#  **kops delete secret --name sak.k8s.test sshpublickey admin**

root@ip-172-31-26-62:~/.ssh#  **kops create secret --name sak.k8s.test sshpublickey admin -i ~/.ssh/key.pub**

root@ip-172-31-26-62:~/.ssh# **kops update cluster --yes**
Using cluster from kubectl context: sak.k8s.test

I0213 14:37:08.498203   31618 executor.go:91] Tasks: 0 done / 53 total; 27 can run
I0213 14:37:08.856602   31618 executor.go:91] Tasks: 27 done / 53 total; 10 can run
I0213 14:37:09.076125   31618 executor.go:91] Tasks: 37 done / 53 total; 14 can run
I0213 14:37:09.577543   31618 executor.go:91] Tasks: 51 done / 53 total; 2 can run
I0213 14:37:09.614871   31618 executor.go:91] Tasks: 53 done / 53 total; 0 can run
I0213 14:37:09.614903   31618 dns.go:140] Pre-creating DNS records
I0213 14:37:09.908267   31618 update_cluster.go:202] Exporting kubecfg for cluster
Wrote config for sak.k8s.test to "/root/.kube/config"
Kops has changed your kubectl context to sak.k8s.test
root@ip-172-31-26-62:~/.ssh# **kops get secrets --type sshpublickey admin**
Using cluster from kubectl context: sak.k8s.test

TYPE            NAME    ID
SSHPublicKey    admin   c2:bc:96:21:e3:24:93:1f:f1:a0:a5:7f:2f:85:f7:23

root@ip-172-31-26-62:~/.ssh# **kops rolling-update cluster --name sak.k8s.test --yes**
Unable to reach the kubernetes API.
Use --cloudonly to do a rolling-update without confirming progress with the k8s API

error listing nodes in cluster: Get https://api.sak.k8s.test/api/v1/nodes: dial tcp 203.0.113.123:443: i/o timeout
root@ip-172-31-26-62:~/.ssh# **kops rolling-update cluster --name sak.k8s.test --yes --cloudonly**
NAME                    STATUS  NEEDUPDATE      READY   MIN     MAX
master-eu-west-1c       Ready   0               1       1       1
nodes                   Ready   0               2       2       2

No rolling-update required

root@ip-172-31-26-62:~/.ssh# **ssh -i key.pub admin@54.194.220.151**
The authenticity of host '54.194.220.151 (54.194.220.151)' can't be established.
ECDSA key fingerprint is SHA256:mh1nUmwm1mUt78F9zK9iNwk+oP6SHmIIVdrQ9ragTcU.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '54.194.220.151' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for 'key.pub' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "key.pub": bad permissions
Permission denied (publickey).

**Comment by justinsb** [comment]
Hi - sorry for the delay.  Yeah, this is just an SSH thing - you need to `chmod 600 key.pub`, or similar.  I presume you figured that out & therefore closed this :-)

**Comment by csarora** [comment]
yes figured it out . thanks
