### ISSUE TITLE
add --network-encrypt true when setting up --networking weave option

### ISSUE THREAD

**Issue by hollowimage** [kubernetes/kops#1880]
allow to specify encryption of the networking at create time when using kops and a network provider.

right now
` kops create cluster {options} --networking weave` creates an unecnrypted mode. 

we should add an option to make it encrypted from the get-go 
https://github.com/weaveworks-experiments/weave-kube/issues/38#issuecomment-253855874

by having kops create a password and add that line into the weave-net DS so we dont have to manually touch it and reroll the DS across the cluster.

**Comment by chrislovecnm** [comment]
We can have that as an option, but would rather not have that as default. does it use more resources and is it possibly slower?

**Comment by hollowimage** [comment]
Oh definitely make it as an option.

**Comment by bboreham** [comment]
Doing encryption is inevitably slower than not doing it; as of 1.9.0 Weave Net can do it in the kernel which vastly reduces the overhead.

**Comment by hollowimage** [comment]
I believe there was just a PR submitted to pull 1.9 into the kops branch here https://github.com/kubernetes/kops/pull/1893#issuecomment-279725222

**Comment by pronix** [comment]
hello
just for avoid collision: i working in it.
thanks
