### ISSUE TITLE
kops update detects changes for EBSVolume tags

### ISSUE THREAD

**Issue by foxylion** [kubernetes/kops#1891]
When running `kops update cluster` there are changes detected for our EBSVolume tags.
This is caused because we added a Tag to identify volumes which should be backed up.

`kops` is considering that the tags for these volumes should be changed. In fact it does not modify the tags (I think only the diff is failing because it does not ignore non-relevant tags on the volume).

The current behavior is in my opinion okay, but it should not display any changes. Another solution could be that the tags get actually removed. But then I would suggest that there should be a feature to add custom tags to those etcd volumes.

This is the output generated by kops:

```
kops update cluster --name ci.k8s.domain.example
I0214 11:20:30.629827   24590 populate_cluster_spec.go:196] Defaulting DNS zone to: Z3NBEPAZEV0AGK
I0214 11:20:31.031204   24590 executor.go:68] Tasks: 0 done / 53 total; 26 can run
I0214 11:20:32.241117   24590 executor.go:68] Tasks: 26 done / 53 total; 11 can run
I0214 11:20:32.556086   24590 executor.go:68] Tasks: 37 done / 53 total; 14 can run
I0214 11:20:32.812171   24590 executor.go:68] Tasks: 51 done / 53 total; 2 can run
I0214 11:20:32.867637   24590 executor.go:68] Tasks: 53 done / 53 total; 0 can run
Will modify resources:
  EBSVolume           	ebsVolume/eu-central-1a.etcd-main.ci.k8s.domain.example
  	Tags                	 {KubernetesCluster: ci.k8s.domain.example, Name: eu-central-1a.etcd-main.ci.k8s.domain.example, k8s.io/role/master: 1, k8s.io/etcd/main: eu-central-1a/eu-central-1a, Backup: true} -> {k8s.io/etcd/main: eu-central-1a/eu-central-1a, k8s.io/role/master: 1, Name: eu-central-1a.etcd-main.ci.k8s.domain.example, KubernetesCluster: ci.k8s.domain.example}

  EBSVolume           	ebsVolume/eu-central-1a.etcd-events.ci.k8s.domain.example
  	Tags                	 {KubernetesCluster: ci.k8s.domain.example, Backup: true, k8s.io/etcd/events: eu-central-1a/eu-central-1a, Name: eu-central-1a.etcd-events.ci.k8s.domain.example, k8s.io/role/master: 1} -> {Name: eu-central-1a.etcd-events.ci.k8s.domain.example, KubernetesCluster: ci.k8s.domain.example, k8s.io/etcd/events: eu-central-1a/eu-central-1a, k8s.io/role/master: 1}

Must specify --yes to apply changes
```

**Comment by dmcnaught** [comment]
+1

**Comment by chrislovecnm** [comment]
What about a tag item that we use to label that kops ignores it? Or should we ignore tags we do not recognize? Need more info from contributors if this is a bug or is as designed.

This needs to be changed regardless ;) But also we need the tags for kops too.

**Comment by OranShuster** [comment]
so there is no solution for this?

**Comment by olemarkus** [comment]
This issue is more than 4 years old. Can you create a new issue with the challenge you are facing?

**Comment by OranShuster** [comment]
Honestly I would, but the version we are using is quite old (1.16, we are in the process of upgrading) so i should probably test that this is happening with a newer version before opening new issues
