### ISSUE TITLE
Unable to access api after rolling-update

### ISSUE THREAD

**Issue by cdelpinogeo** [kubernetes/kops#1898]
I was trying to install the `batch/v2alpha1` api on our 1.5.1 cluster. I used the following to install it: https://github.com/kubernetes/kops/issues/618

The rolling-update was able to go through and perform its steps, but I can no longer run kubectl commands. I get the following:

`cdelpino@merc1:~$ kubectl --context=dev.boundlessgeo.com get pods --all-namespaces | grep kube-apiserver
Unable to connect to the server: dial tcp 52.87.197.246:443: i/o timeout
cdelpino@merc1:~$ kubectl --context=dev.boundlessgeo.com proxy
Unable to connect to the server: dial tcp 54.196.135.89:443: i/o timeout`

I can provide further info if needed. Thanks.

**Comment by ipedrazas** [comment]
I guess that your API Server is down. Could you log in into your master and check how many containers are up?

**Comment by cdelpinogeo** [comment]
I ran the following per @justinsb:

```
admin@ip-172-20-98-102:~$ kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?
admin@ip-172-20-98-102:~$ sudo docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS               NAMES
fc2a9ede5af3        kope/protokube:1.4   "/usr/bin/protokube -"   17 hours ago        Up 17 hours                             admiring_mahavira
```

and there is nothing in `/var/log/kube-apiserver.log`.

Not sure if I should close this since @justinsb is providing help via slack or keep this open?

Thanks!
