### ISSUE TITLE
Brought up a cluster on AWS with kops and cannot attach ELB PersistentVolume to Pods

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kops#19]
Pod fails to create with

`FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod ...`

Every time I try to mount a pod with a elb attached.

Kops is using kubernetes 1.3.0

Any hints?

**Comment by justinsb** [comment]
This is because we aren't setting the hostname_override on AWS.  Working on the fix now.

**Comment by justinsb** [comment]
Should be fixed in the latest code.  I think you'll have to bounce the servers in your cluster, but "there's a tool for that'.  Writing up the docs for that now!

**Comment by felipejfc** [comment]
thanks!
