### ISSUE TITLE
Kops create cluster --image does not affect bastions

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/kops#1901]
When doing a ```kops create cluster --image=ami-xxxx --bastion ...```
The AMI gets correctly set for the nodes and the masters, but the bastion is using the default AMI
```  "image": "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21",```

**Comment by justinsb** [comment]
Nice spot @sstarcher - should be fixed in #1906
