### ISSUE TITLE
Missing build docs link in readme

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#1902]
Readme.md has the line:

> See [building notes](https://github.com/kubernetes/kops/blob/master/docs/build.md) for more information.

This file doesn't exist and I'm not sure where this is supposed to point to.

**Comment by hollowimage** [comment]
I think this went here https://github.com/kubernetes/kops/commit/2a770229484975e5df1487d3c43a518bfc7a891c#diff-e3e2a9bfd88566b05001b02a3f51d286

**Comment by yissachar** [comment]
Yes, good call 👍
