### ISSUE TITLE
Allow individual kops object updates

### ISSUE THREAD

**Issue by hubt** [kubernetes/kops#1912]
`kops update cluster` should have a mechanism to specify individual objects to update instead of updating the whole cluster at once.

In my production cluster, I want to be careful about updating objects(especially the masters) I only want to edit an instance group right now, but cluster update is an all or nothing proposition.

I'd like to have an option like `kops update cluster --object AutoscalingGroup/nodes.kube.domain.name` so that I can just touch one thing at time without worrying about other changes.

I will work around this by generating terraform output and then cherrypicking and applying objects I want, but that's a bit ugly.

**Comment by hollowimage** [comment]
+1

with the custom network topology in place and launch group configs kops becomes a little 1-time use, this would make it much more flexible.

**Comment by chrislovecnm** [comment]
You can always use kops replace with a manifest.
