### ISSUE TITLE
Create a MAINTAINERS.md

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#1913]
A place to document common maintainer practices:

- How we use tags, milestones
- PR review/merging guidelines
- Issue triage?

This issue is a reminder to the maintainers to think about and start documenting how we would like this experience/community to look- not for a final polished document- this likely will/should never exist.

**Comment by chrislovecnm** [comment]
Interesting core does not have this ... that is a problem

**Comment by chrislovecnm** [comment]
This is part of sig-contribx need to coordinate with them
