### ISSUE TITLE
Add Kubernetes 1.4.9 and 1.5.3

### ISSUE THREAD

**Issue by itskingori** [kubernetes/kops#1914]
We have new Kubernetes versions:

* https://github.com/kubernetes/kubernetes/releases/tag/v1.4.9
* https://github.com/kubernetes/kubernetes/releases/tag/v1.5.3

**Comment by chrislovecnm** [comment]
Not sure what u mean. We do not bump the channel, which is the recommended version, until we validate that the release is stable. You are able to use those version via the Kubernetes-version flag.

**Comment by itskingori** [comment]
@chrislovecnm Oh, I see. If I can use the straight away then that's fine.

**Comment by justinsb** [comment]
We should add them to the alpha channel though, and eventually to the stable channel.  @itskingori (and others) can you let us know if you encounter any issues if you try them out!

**Comment by itskingori** [comment]
@justinsb ...

> ... can you let us know if you encounter any issues if you try them out!

Absolutely!

> We should add them to the alpha channel though ...

I've created a PR for that. See https://github.com/kubernetes/kops/pull/1930.

**Comment by chrislovecnm** [comment]
Closing as PRs are merged
