### ISSUE TITLE
Improve error message when the API is still set to the placeholder IP

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#1915]
If you try to access the API shortly after your cluster is created, kops will attempt to access the placeholder IP and eventually timeout:

```
$ kubectl get node
Unable to connect to the server: dial tcp 203.0.113.123:443: i/o timeout
```

If you're not familiar with the fact that 203.0.113.123 is just a placeholder IP that will be replaced eventually, then this looks like your cluster is broken.

We should hijack any requests that go to 203.0.113.123 and instead return a better error message:

```
$ kubectl get node

The server DNS is still resolving to 203.0.113.123. This is a placeholder IP that will be
replaced once the cluster comes online. If you have recently created the cluster please 
wait a few minutes for cluster setup to complete. If you continue to receive this error, 
your cluster may be misconfigured.
```

**Comment by justinsb** [comment]
Yes in theory.  In practice, not sure how we would do that :-)

I think adding a `--wait` flag / verb would achieve the same thing.  It could poll `validate` until the cluster was ready.

**Comment by neilhwatson** [comment]
Or how long to wait for the proper IP settings, or how to check progress. Very vague.
