### ISSUE TITLE
Don't require e2e tests for doc changes

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#1916]
There's no advantage to running e2e on pure doc change PRs and it slows things down.

**Comment by chrislovecnm** [comment]
@zmerlynn I know that core has a label for this, does our bot that runs e2e respect that label?

**Comment by zmerlynn** [comment]
@chrislovecnm: There's a label that indicates it's a doc change only, but I'm not sure the label has any impact in core now that batch merges are enabled. Even in core, doc changes go through one round of e2e tests. I don't think we've done the work for totally conditional PR building.

cc @rmmh @spxtr for corrections

**Comment by spxtr** [comment]
We can currently skip testing a PR if its changed files don't match a regex. For instance, we only run the cross build if it touches a file matching `(Makefile|\.sh|_(windows|linux|osx|unsupported)(_test)?\.go)$`.

This isn't great. Once we get a good Bazel cache working, then we will be able to skip docs PRs in the proper way. We only need to run tests if the release-tars target is changed.

**Comment by zmerlynn** [comment]
@chrislovecnm: Didn't you have someone that was going to work on Bazel for `kops`? If that's the case, this might be easier to wait on.

**Comment by chrislovecnm** [comment]
@spxtr is bazel ready for this project?

**Comment by chrislovecnm** [comment]
@zmerlynn yes we have https://github.com/kubernetes/kops/issues/1285 open

**Comment by chrislovecnm** [comment]
We have the label now
