### ISSUE TITLE
It should be possible to have separate public/internal DNS zones

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1919]
We're using `--topology private`, so we want most of our DNS names to be in a private hosted zone.  We'd like `masterPublicName` to be an actual public name.  Currently you can't have both because it will operate on a single DNS zone.

**Comment by justinsb** [comment]
I think this is "just" a bug fix, I don't know of any reason why we couldn't do "split" DNS.  I think the biggest challenge is probably that we have a dnsZone field in the spec, which is probably the root of the "one zone" assumption.

**Comment by blakebarnett** [comment]
I tried with and without it specified, I assume it's inferring the zone from the domain name currently?

**Comment by bernielomax** [comment]
I would be keen on this feature also.

**Comment by darron** [comment]
@justinsb This is the split dns issue I was talking about during today's office hours.

if it's "just a bug fix" then that would be awesome - but we'll look at some of the alternatives in the meantime - I haven't looked through the code yet that touches this area.

**Comment by blakebarnett** [comment]
@justinsb I'm thinking of taking a stab at this.  How hard should I try to keep backwards compat?  Ideally we could specify:

```
dnsZones:
  public: <zone name or ID>
  private: <zone name or ID>
```

And I assume we'd want to pick a default for each one depending on topology?  So for a private topology the default would be `private: $clusterName` and vice-versa for public.

Should it just convert existing `dnsZone:` keys to this scheme?  Or should I use a new key like:

```
dns:
  privateZone: <>
  publicZone: <>
```

And populate the new structure with the old `dnsZone:` if it's specified?

**Comment by blakebarnett** [comment]
This is still needed, we are using a nasty hack for it.
