### ISSUE TITLE
Tag model needs fixing

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#192]
- We should apply tag changes even if there are no other changes
- We should allow tasks to override their tags (e.g. a shared VPC)

**Comment by yissachar** [comment]
Related to https://github.com/kubernetes/kops/issues/476

**Comment by kris-nova** [comment]
Before merging, we need to make sure we address the concerns in the documentation [here](https://github.com/kubernetes/kops/pull/1022#discussion_r90386792)

**Comment by blakebarnett** [comment]
seems resolved, please re-open if needed
