### ISSUE TITLE
Add ability to specify additional SANs for master TLS certs?

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1922]
It would be nice if there were an option in the cluster spec to add addtional SANs to the certs so that we can work around issues like https://github.com/kubernetes/kops/issues/1919 manually without having it break everytime we use `kops update`

**Comment by blakebarnett** [comment]
closed via PR #2063

**Comment by chrislovecnm** [comment]
/close

BTW that bot command should work for you @blakebarnett
