### ISSUE TITLE
Don't require sha1sum for simply building kops

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#1924]
We currently [require](https://github.com/kubernetes/kops/blob/master/Makefile#L67-L71) that sha1sum exist or we error out on any attempt to make.

As far as I can see it is only used by a few commands, and we should only require it for those commands, and let the rest run even if sha1sum doesn't exist.

**Comment by justinsb** [comment]
I think this would be a good and not too hard fix.

In the PR for building a static socat, I compute the sha1 value inside a docker container.  I think we're building everything in a docker container now, so we could just move the calculation into the docker container: https://github.com/kubernetes/kops/pull/1909/files#diff-8de97ff7eccd97a854a02fb65bbc9b06

**Comment by ljnelson** [comment]
A side note: for anyone looking to build `kops` from source on a Mac without using `homebrew` in any way, you can write a simple shell script like this:

    #!/bin/sh
    if [ "--help" == "$1" ]; then
      echo hello!
      exit 0
    fi
    md5 -r "$@"

…and name it `sha1sum` and put it on your path.  Then the build works fine.

The (stupid, hacky—I'm no shell programmer) script above simply spits out _something_ when the `--help` option is invoked, which is [how the `Makefile` decides whether `sha1sum` exists or not](https://github.com/kubernetes/kops/blob/master/Makefile#L72).  Then, for "real" invocations, it simply uses the built-in `md5` program (located in `/sbin`) with the `-r` option (which makes the command behave basically exactly like `sha1sum`).  Hope this helps.

**Comment by geojaz** [comment]
/close
fixed in #2097
