### ISSUE TITLE
Default disk size to small

### ISSUE THREAD

**Issue by apenney** [kubernetes/kops#1929]
Hi,

After a few days of playing with Kubernetes we started having "Weird issues", with weave being evicted.  Turns out we're running out of disk space as the default is 25G.  I propose we look to at least double that for real world usage.  We just moved to 100G.

**Comment by blakebarnett** [comment]
We did the same, I can understand the default being low but maybe an entry in a "Production settings" guide or something would be good.

**Comment by chrislovecnm** [comment]
I think we need to raise the disk size up.  Hard Disk size is pretty cheap, and chasing evictions is a PAIN.  Any recommendations?  We are setting around 256, but I think that is large for the default.

**Comment by ese** [comment]
I think 100G is good number for nodes. 50 for masters can be good

**Comment by chrislovecnm** [comment]
@apenney hope you don't mind, but I renamed the issue.

**Comment by chrislovecnm** [comment]
Closing as this is fixed
