### ISSUE TITLE
dns-controller can keep unused ips around in Route53

### ISSUE THREAD

**Issue by olvesh** [kubernetes/kops#1938]
I demonstrated how a termination of all master nodes did not stop the cluster functioning. Upon restart of all masters there was an extra ip address in the route-53, probably from the old master.

This is kept around, and not removed by dns-controller as it should.

Showing only internal dns, but same for external.
```
# kubectl get node -l kubernetes.io/role=master
NAME                                           STATUS         AGE
ip-172-20-120-133.eu-west-1.compute.internal   Ready,master   1d
ip-172-20-44-19.eu-west-1.compute.internal     Ready,master   1d
ip-172-20-84-25.eu-west-1.compute.internal     Ready,master   1d
```
![image](https://cloud.githubusercontent.com/assets/220643/23071613/403f77e2-f52f-11e6-9b0d-a508b890a5d2.png)

**Comment by justinsb** [comment]
Hmm... thanks for reporting!  I'll take a look!

**Comment by jgmize** [comment]
related, possibly duplicate issue: https://github.com/kubernetes/kops/issues/1986

**Comment by geojaz** [comment]
This seems to be an out of date issue and I haven't seen it reported with latest kops release 1.7.1. 

I'll close this and if you're still having trouble with latest version, please @ or create a new issue. Thanks!
