### ISSUE TITLE
Design Spike - vSphere support in kops

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1940]
Please disagree with me if I am incorrect, but this is probably a big enough endeavor that we need a short one page design on how we want to accomplish this task.

cc: @sandeeppissay @stealthybox

**Comment by justinsb** [comment]
We don't _require_ design docs.  But I am happy to assist however works best for people - let me know if that is code review of early PRs, regular hangouts for questions, a design doc... whatever works best :-)

**Comment by SandeepPissay** [comment]
I just want to mention here that we are still evaluating kops to see how big an effort it is going to be to make it work for vSphere and should we choose kops etc. I'll probably have a answer to this after few weeks.

**Comment by kris-nova** [comment]
This issue was opened inappropriately. Sorry about that @SandeepPissay, please let us know if there is anything else we can help with.
