### ISSUE TITLE
Is it possible to add ssh users other than the default (admin)?

### ISSUE THREAD

**Issue by rdtr** [kubernetes/kops#1945]
Hi,

I tried to add a new SSH user by running
`
kops create secret --name [cluster] sshpublickey rdtr -i mykey
`
and the secret is stored, but it seems neither the key is not stored actually in EC2 instance nor a new user is created on a server after `rolling-update` complete.

Is this a expected behavior? I'd like to avoid sharing the same SSH key among all developers if possible.

**Comment by chrislovecnm** [comment]
At this point only one ssh key is support. Couple work around:

We have a PR in for pre and post scripts, or you can use your own image.

**Comment by rdtr** [comment]
@chrislovecnm thank you for the clarification, the workarounds are sufficient for me now:)
