### ISSUE TITLE
New Route53 RolePolicy has incorrectly generated hosted zone arn for `Resource`

### ISSUE THREAD

**Issue by Shrugs** [kubernetes/kops#1949]
## Issue

The new Route53 RolePolicy for masters, added in [this PR](https://github.com/kubernetes/kops/pull/1871/files) uses `"arn:aws:route53:::hostedzone/" + b.Cluster.Spec.DNSZone` as the value for the `Resource` property in the policy.

If `dnsZone:` (`Spec.DNSZone`) is the hosted zone's name (like `cluster.example.com`), the correct hosted zone id isn't looked up and the generated `Resource` is an invalid arn.

`dns-controller` then attempts to `ListResourceRecordSets` against the valid arn for that hosted zone (something like `arn:aws:route53:::hostedzone/ABCDEFGHIJKL`) and is denied. 

## Fix

The fix is to, if `dnsZone` is a hosted zone name, use the HostedZoneId in the arn generation, otherwise use the provided `dnsZone` property.

There's a function [`findZone`](https://github.com/kubernetes/kops/blob/master/dns-controller/pkg/dns/dnscontroller.go#L361) that already uses the correct logic to return the zone's id.

## Workaround

If you run into this issue and find this page via google, simply use the hosted zone's id instead of the name for `dnsZone` in the cluster state file.

**Comment by zytek** [comment]
I believe Spec should be consistent, either always point to Hosted Zone ID (so, maybe the value should be renamed to something along `Route53HostID`?) or it should always carry DNS name (so it will be portable across different cloud providers) and then `iam_builder` should use `findZone`

Can some maintainer advice which route should we go with? I'm happy to try to fix that then.

**Comment by Shrugs** [comment]
I'd also support a single-accepted value in the state file. Instead of looking up the hosted zone id at runtime, should we look it up once at `kops create cluster` time and store that in the state file instead of the name?

Only issue is 1) naming 2) backwards compatibility.

**Comment by zytek** [comment]
BTW @Shrugs how did you end up with cluster spec having dns name rather than hosted zone id? The way I am creating my clusters it's alway hosted zone ID.

**Comment by Shrugs** [comment]
@zytek it's a documented feature that the dnsZone can be either the name of the zone or the id: https://github.com/kubernetes/kops/blob/master/docs/arguments.md#dns-zone

**Comment by Shrugs** [comment]
Most logical course of action is probably to continue translating the name to the id at runtime to get a fix into master and then potentially refactor the state like you've suggested if one of the maintainers agrees.

**Comment by zytek** [comment]
Oh, didn't know that about the spec! 
I'm happy to fix that issue once maintainers advise on the course of action.

**Comment by justinsb** [comment]
I think my personal preference would be to tolerate a name, and call findZone to translate.  The hosted zone id is more precise, but much less user-friendly.  It's probably an error anyway - I expect we'll have to clean this up when we do the next revision of the API (things I am aware of: separate internal & public zones, the fact that telling an id from a name is a hack, and the idea that we might want to run in different dnsproviders in theory).

One thing I do want to check is that we haven't broken internal hosted zones.  I don't think we have, but we probably need to resolve the name to an id as late as possible.

(This might also be an argument for supporting the name, in that the zone might not exist until we run update...)

Also - this might get really tricky with terraform/cloudformation output.  Feel free to punt that issue / ping me on it if it proves tricky!
