### ISSUE TITLE
kops create -f should provide some command line feedback

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#1953]
A successful run of `kops create -f cluster_spec.yml`, kops is 100% silent. 

I propose that if the cluster spec is good, say something to that effect:

```
cluster $CLUSTER_NAME imported. 
SSH public key must be specified when running with AWS (for example, create with `kops create secret --name $CLUSTER_NAME sshpublickey admin -i ~/.ssh/id_rsa.pub`)
type `kops update cluster $CLUSTER_NAME` and then `kops update cluster $CLUSTER_NAME --yes` to deploy these resources.
```

I'm writing a blog post about `kops create -f` right now and was caught off guard by no response. I don't really care the exact words that we say after successful or unsuccessful import but I do care that we say something! I'll get the basics coded up and we can talk about the wording and what we want to say.

**Comment by hridyeshpant** [comment]
@geojaz i am also trying to create cluster based on yml file but could not find any documentation for correct yml file format? currently i am creating cluster based on command line and updating subnet CIDR range manually. 
kops create cluster --v=3 --state=s3://kubernetes --cloud=aws \
    --name=kubetnets.us-west-2.dev.xyz.com \
    --ssh-public-key=~/.ssh/test.pub \
    --master-size=t2.medium \
    --cloud-labels="Role=k8" \
    --master-zones=us-west-2c,us-west-2a,us-west-2b \
    --network-cidr=10.0.0.0/16 \
    --vpc=vpc-030g8f62 \
    --node-count=3 \
    --node-size=t2.micro \
    --topology private \
    --networking weave \
    --zones=us-west-2c,us-west-2a,us-west-2b \
    --channel=alpha 

is there any example of yml file format to create cluster based on own subnet CIDR?

**Comment by geojaz** [comment]
@hridyeshpant I keep saying the same thing which means that we as a team are not doing a good job documenting this process. 

Until we get this coordinated, you can follow these directions which are pretty spot on: https://github.com/kubernetes/kops/issues/1732#issuecomment-277399137

Once you pull out any of your business specific stuff, if you're feeling up to it, please submit your raw cluster spec and some documentation explaining how to use it as a docs PR. Please let me know if I can do anything to help you get it into a PR.

**Comment by geojaz** [comment]
closed in 2052 :)
