### ISSUE TITLE
SSH not working with Mac extended attributes

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1961]
Given a public key with Mac extended attributes (notice the `@` sign) :

```
$ ls -l@
-rw-------@ 1 user  staff        400 Nov  6  2014 id_rsa.pub
    com.apple.ResourceFork         1338
    com.apple.LaunchServices.OpenWith          141
```

`kops` will create a cluster, and AWS will accept the secret. Everything works as expected until a user tries to gain access to a resource via SSH. The OpenSSH daemon denies the key. Output of `ssh -vvv`:

```
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/melvin/.ssh/id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey).
```

Thanks to @mirague for finding this unique story!

**Comment by zytek** [comment]
Nice find.
But is this a `kops` issue or rather OpenSSH issue?

**Comment by kris-nova** [comment]
Well I think regardless of who or what might need to be fixed here... the issue at hand is a kops issue.

If OpenSSH isn't using a key (regardless of feature vs bug) kops still should not allow the user to use an invalid key.

**Comment by zytek** [comment]
Well, then we should also check if the key has proper permissions (ssh refused to use publicly readable keys). Check if the key wasn't generated using weak algorithms and keep up to date with changes in that regard. Or check for obscure issues like 'debian weak key' incident (https://certlogik.com/debian-weak-key-check/). You get my point. ;-) 

For me this is strictly user environment issue and possibly an OpenSSH issue that should/could be reported upstream (at least for better debug msg output).

We might put that into some kind of Troubleshooting FAQ.

The real question here is how the user ended up with key with such permissions? @mirague could you provide some details on that?
