### ISSUE TITLE
Automatically apply CloudFormation to AWS

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1964]
Right now the user is instructed to manually add the CloudFormation to to AWS. Which is great and I think we should keep this workflow as is:

```
export KOPS_NAME=demo.nivenly.com
kops create cluster --zones us-west-2a --target cloudformation --name $KOPS_NAME
aws cloudformation create-stack --capabilities CAPABILITY_NAMED_IAM --stack-name kubernetes-demo-nivenly-com --template-body file://out/cloudformation/kubernetes.json
kops delete cluster --name $KOPS_NAME --yes
```

I am wondering if it would be useful to add an **optional** flag that would automatically apply the CloudFormation straight to the AWS for the user? For instance, we could use the `--yes` flag here to keep with existing `kops` workflow.

```
export KOPS_NAME=demo.nivenly.com
kops create cluster --zones us-west-2a --target cloudformation --name $KOPS_NAME --yes
kops delete cluster --name $KOPS_NAME --yes
```

@justinsb @jbeda thoughts?

**Comment by chrislovecnm** [comment]
At this point we do not have any user requests.

**Comment by nburn42** [comment]
Where is the documentation and example cloud formation for this?

**Comment by chrislovecnm** [comment]
@nburn42 there really is not much documentation for this, not sure how many users are using CF and kops.  Set `--target=cloudformation` with a `kop create cluster`.

**Comment by luisRubiera** [comment]
@chrislovecnm i think documentation would help, but i understand that if you dont have any use-case you wont know what to do with CF template. 

lets say i want to deploy my app automatically with CF, something like exporting my app for people to use it in the Marketplace. (this exists for the most of resources in Azure  using ARM template + Managed application ). for the moment what i can do is just deploy the cluster K8s with the CF and then install my app manually, is there anyway to do this with your generated CF template ?
