### ISSUE TITLE
Make sure we are randomizing internal API hosts

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1965]
We're seeing behaviour with uneven distribution of loads that suggest we might not be, in particular for kube-proxy connections.

**Comment by justinsb** [comment]
We are randomizing the values.  So I don't think this is the cause (though it is not impossible that the DNS server actually serves a new ordering every second, and the clients are all in time-sync because they all disconnect and reconnect shortly thereafter, so I'm not closing).

**Comment by zhangxiaoyu-zidif** [comment]
+1

**Comment by zhangxiaoyu-zidif** [comment]
one situation plus：
The master acts as node also, and a dpdk daemonset's pod runs on the master-node. I am not sure does that concern
