### ISSUE TITLE
Cluster internal network slow - Network time out between cluster components

### ISSUE THREAD

**Issue by aachuthan** [kubernetes/kops#1967]
We have an issue with a Kops cluster described below. 

We have been using kube-up.sh script to set up kubernetes cluster on aws and things have been working very well

Now we are setting up a cluster using kops  using the below command

kops version 1.4.4
kubernetes version 1.4.8

kops create cluster --cloud=aws --node-count 4 --zones us-east-1a,us-east-1c,us-east-1d,us-east-1e --master-zones us-east-1a,us-east-1c,us-east-1d --dns-zone k8s.mydomain.com --node-size m3.2xlarge --master-size m3.medium --image 293135079892/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-11-16

The cluster has come up. Within the  cluster we are running Rabbitmq , Cassandra  and  Spark.

We are  getting streaming data into Rabbitmq from external source. Spark connects to Rabbitmq on SSL port with in cluster and also connects to Cassandra (non-ssl). All the endpoints are accessed through the service name (not loadbalancer urls) within the cluster. 

However we find the Spark process to be significantly slow as compared to a cluster setup with kube-up script. Spark UI shows that Spark is getting streaming data from Rabbitmq  but the entire processing within Spark and Cassandra is slow. Other than kops there is no difference between the kube-up created cluster.

Any suggestions on how to debug this issue is welcome.

**Comment by justinsb** [comment]
Was your kube-up cluster running in multiple zones?  Inter-zone networking will be slower.

Also, you probably should try run kops 1.5.X - it can also install k8s 1.4.  (The restriction is the other way: kops 1.4 might not be able to install k8s 1.5)

**Comment by aachuthan** [comment]
The last Kops cluster was actually running on a single zone. We had the same issue on multi-zone and single zone Kops clusters. We also tried 1.5.2 with Calico with the same result.

**Comment by mtrofimm** [comment]
@aachuthan have you found any solution or workaround the timeouts?

**Comment by chrislovecnm** [comment]
The instance sizing is your first problem, as they may be way too small. This is a kubernetes operational issue not really a kops issue. Can we close?

**Comment by rroopreddy** [comment]
Hi @chrislovecnm,  we have been using Kubernetes with exactly same number/size nodes on new Kubernetes/kops as before (Kubernetes 1.4.12). I do not see how this is  resource sizing problem given nothing changed.  This is kind of blocking issue, as we are trying to upgrade from Kubernetes 1.4.12 to new version of Kubernates/kops with significant slowdown.

Please do not close this, any guidance on how to debug this would be appreciated. We can provide any needed information for debugging. Appreciate it

**Comment by AndresPineros** [comment]
We are experiencing the same issue right now. Kops 1.9.1 internal network is very slow. I will try kubeup.sh because this is too blocking to continue using. Kafka is basically useless with this setup.

**Comment by aachuthan** [comment]
Issue resolved by removing cpu limits in the controller files.The same cpu limits worked without issues in kubernetes 1.4.x. We have tested without cpu limits on kubernetes 1.9 as well as 1,10 and not seeing any issues.

**Comment by AndresPineros** [comment]
@aachuthan CPU limits of which controller files?

**Comment by aachuthan** [comment]
we had set cpu limits in our cassandra controller files initially. Now we have removed it.

**Comment by aachuthan** [comment]
also had cpu limits  in our spark  worker controller files too. This is also removed now
