### ISSUE TITLE
Terraform output for additional security groups is broken

### ISSUE THREAD

**Issue by jhedev** [kubernetes/kops#1977]
I want to attach additional security groups to my nodes. Therefore I did a `kops edit ig nodes` and added the following:

```yaml
 spec:
   additionalSecurityGroups:
   - sg-abcd1234
```

When running version 1.5.1 of kops the terraform output is not updated correctly, which seems to be fixed with PR #1854. So I tried the same with the current master version. However, the corresponding terraform output looks like this:

```
security_groups             = ["${aws_security_group.nodes-staging-k8s-gridx-de.id}", "${aws_security_group.sg-abcd1234.id}"]
```

As expected terraform fails because the `aws_security_group.sg-abcd1234` does not exist in the terraform config. 

I think this might be caused by commit 5bba483a611e05adaf4bd92daaaa611bbe9af3a6, which removes the part introduced by the PR:

```
 -     for _, sg := range e.AdditionalSecurityGroupIDs {
 -		tf.SecurityGroups = append(tf.SecurityGroups, terraform.LiteralFromStringValue(sg))
 -	}
```

and instead creates a `awstasks.SecurityGroup` for every additional security group like this:

```
+                    for _, id := range ig.Spec.AdditionalSecurityGroups {
 +				sgTask := &awstasks.SecurityGroup{
 +					Name:   fi.String(id),
 +					ID:     fi.String(id),
 +					Shared: fi.Bool(true),
 +				}
 +				if err := c.EnsureTask(sgTask); err != nil {
 +					return err
 +				}
 +				t.SecurityGroups = append(t.SecurityGroups, sgTask)
 +			}
```

And an `awstasks.SecurityGroup` itself is rendered using `aws_security_group.<name>.id`.

I would sent a PR myself, however, I'm not sure how to fix this the best way...

**Comment by justinsb** [comment]
Thanks for the heads up :-)  The fix itself if you want to have a look at it is in securitygroup.go, though I added a test as well.  Essentially if the security group is shared we don't output it to terraform, so when we reference it we can't reference a terraform block (as you pointed out).  Instead we just output the ID as a literal string.
