### ISSUE TITLE
Multiple regions

### ISSUE THREAD

**Issue by clanstyles** [kubernetes/kops#198]
The recommended domain is k8s.domain.com and then it generates nodes: nodes.us-east .. etc. If you spin up two or three zones then the k8s.domain.com is no longer available, how should we folllow convention but have multiple regions?

**Comment by justinsb** [comment]
Not sure I follow, but one convention that should work is to put all your clusters under `k8s.mydomain.com`, and then have `<name>.<region>.k8s.mydomain.com`

So e.g. `prod.us-west-2.k8s.mydomain.com`

Does that make sense?  If so I should update the docs!

**Comment by clanstyles** [comment]
Yes, that was my solution. The next issue is that we have multiple providers coming soon. So <name>.<proivder>.<region>.k8s.mydomain.com

Just a few ideas.

**Comment by chrislovecnm** [comment]
We should check that this is documented
