### ISSUE TITLE
kops init: create a fully documented cluster and instance group spec file

### ISSUE THREAD

**Issue by ringods** [kubernetes/kops#1984]
I would like kops to be driven more by the cluster and instance group spec files in yaml, rather than with cli arguments. 

My main driver for this is to generate a cluster spec file feeding Terraform outputs as inputs in the cluster spec. It took me quite to understand what sections were available, what the possible values are and how to interpret them.

kops is in flux a lot (which is good), but that results in documentation that becomes outdated quite fast. To resolve this, I would suggest to have a short peek at the `kube-aws` tool and take a similar approach: when running `kube-aws init <args>`, it spits out a 700+ spec file. This file contains all possible configuration sections, most commented out, some not, marking them obligatory. But all sections are documented and very understandable.

While the 700+ line spec file is a bit overkill for kops, taking a similar approach by introducing a `kops init` command would be helpful. Every version of kops will spit out the spec file which it understands. 

With a proper versioning scheme, you are able to make breaking changes. How can we as users detect the differences? Run `kops init` with the kops binary of 2 different versions, and then compare the spec files. A good diff tools goes a long way.

One thing: don't look too good at the `kube-aws` tool: I want to run the `init` command without any arguments to get an default template file. :-)

Related: #752, #1732, #1735, #1907

**Comment by kenden** [comment]
There is *some* doc [here](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md).

**Comment by chrislovecnm** [comment]
We have create with dry-run now. Does that help?

**Comment by ringods** [comment]
Didn't test it yet, but reading the documentation I think it's a good start. I will create a more detailed change request when I would still be missing out on something.
