### ISSUE TITLE
The image id parameter not work for bastion server

### ISSUE THREAD

**Issue by ffjia** [kubernetes/kops#1985]
Hi there,

When I used `--image ami-b2d463d2` parameter together with `--bastion`, the bastion server is still using the default Debian Jessie image.

The kops version is `Version 1.5.1 (git-7ba643e2b)`.

**Comment by yissachar** [comment]
This was fixed in #1906. It should work if you build from master, or when 1.5.2 is released.

Sorry for the inconvenience!
