### ISSUE TITLE
Old API Internal A record not deleted after rolling update

### ISSUE THREAD

**Issue by ffjia** [kubernetes/kops#1986]
Hello,

I setup HA cluster like this [doc](https://github.com/kubernetes/kops/blob/master/docs/high_availability.md) described. After doing kubernetes version upgrade, from 1.5.2 to 1.5.3, I found that there 4 values in api.internal A record, which should be 3 master private IPs.

`api.internal.demo.tld
A
172.20.121.29
172.20.35.12
172.20.57.176
172.20.91.54
`

The kops version `Version 1.5.1 (git-7ba643e2b)`.

Could you help look at it? Thanks.

**Comment by justinsb** [comment]
@ffjia were there 4 apiserver pods running?  (`kubectl get pods --all-namespaces`)

This is controlled by the     `dns.alpha.kubernetes.io/internal: api.internal.example.com` annotation on the pods, so I'm thinking that either a pod stuck around for some reason, or something went wrong with the dns-controller.

I tried the upgrade and it didn't happen to me, so I'm hoping to get some clues!

**Comment by ffjia** [comment]
@justinsb 

I'm running 3 apiserver pods:

`➜  kubectl get pods --all-namespaces | grep apiserver`
kube-system   kube-apiserver-ip-172-20-121-29.us-west-2.compute.internal            1/1       Running   3          6d

kube-system   kube-apiserver-ip-172-20-35-12.us-west-2.compute.internal             1/1       Running   0          6d

kube-system   kube-apiserver-ip-172-20-91-54.us-west-2.compute.internal             1/1       Running   0          6d

Anything else I can provide?

**Comment by ffjia** [comment]
Just upgraded to v1.5.4 with `kops` version `1.5.2-beta.2`, now I only see 3 working A records, I guess we could close it?

**Comment by bcorijn** [comment]
@chrislovecnm @justinsb I'm on kops v1.5.4 and I still see this btw, so this hasn't been solved.. I assume rolling another upgrade corrected the problem for the original poster. 
I only had three API pods either, so that can't really be it.
