### ISSUE TITLE
Toolbox dump -> kops describe

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#1988]
Can we port the functionality from `kops toolbox dump` into `kops describe`?

It would increase visibility into a valuable command, as well as offer a few avenues of dumping relevant cluster information for the user.

**Comment by justinsb** [comment]
In theory yes, except kops toolbox dump is not really ready to face the world yet.

**Comment by justinsb** [comment]
(And once we expose it "properly", we're committing to the output format)

**Comment by kris-nova** [comment]
> yet

..being the keyword there.. I was wondering if we could harden it.. and add it as a base level kops command

**Comment by kris-nova** [comment]
committing to the output format?

We should be able to define that at runtime `-o yaml`, `-o json`, `-f $file` right?

Or are you suggesting that we have a whole batch of concerns with standardizing a **kops output API**?
