### ISSUE TITLE
Timeout on attaching EBS volumes when using multiple Zones

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kops#199]
The cause is that the pods are being scheduled to run  on nodes that are running not on the same AZ as the EBS volume specified, kube-controller-manager logs this:

`
E0724 14:13:48.361895       9 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-7071af77" failed. No retries permitted until 2016-07-24 14:14:20.361890549 +0000 UTC (durationBeforeRetry 32s). error: AttachVolume.Attach failed for volume "kubernetes.io/aws-ebs/vol-7071afdd" (spec.Name: "redis-data") from node "ip-177-27-177-177.ec2.internal" with: Error attaching EBS volume: InvalidVolume.ZoneMismatch: The volume 'vol-7071af77' is not in the same availability zone as instance 'i-bde69f77'
`

I wonder if this error is caused by kops messing up the cluster creation somehow or kubernetes problem, I don't remember seeing this problem when I brought up the cluster with kube-up...

Any thoughts @justinsb ?

**Comment by justinsb** [comment]
Sorry for delay!  I believe we chatted about this on slack and it's because you have to use PVs and PVCs for multizone automatic scheduling to work.  We talked about a potential workaround that involved using a nodeSelector if you do want to specify the EBS volume directly at the pod level.

**Comment by justinsb** [comment]
Going to close this - I think we resolved this on slack.  If you use PV & PVC it should work; it won't work if you awsElasticBlockStore volumes directly.  Do reopen if not solved!
