### ISSUE TITLE
Running kops toolbox dump to output in json format throws non-json lines before it dumps the actual json 

### ISSUE THREAD

**Issue by Miyurz** [kubernetes/kops#1991]
I hit a bug when I try to jsonize the output of` kops toolbox dump --name  <clustername> -o json` .
It yielded some non-json lines/output as shown below which failed  jq processor I ran on the output.

> inserting nat-022649781e7da5cb6 to be deleted
> inserting nat-0d337addd415f6a93 to be deleted
> inserting nat-07e86df5af77af2b2 to be deleted

This may be a corner case and may not be happening always(as I didn't see it before).

**Comment by Miyurz** [comment]
@justinsb So this is fixed now  since printf that was echoing the nat ids have been removed from the code and merged ?

**Comment by chrislovecnm** [comment]
@Miyurz can you test and report back?

**Comment by Miyurz** [comment]
@chrislovecnm works good now! Thank you. good to close.
