### ISSUE TITLE
rolling-update: Found ASG with no corresponding instance group

### ISSUE THREAD

**Issue by davidguttman** [kubernetes/kops#2000]
Got a warning when running `kops rolling-update cluster` with the `--instance-group` option. Guessing it's not a big deal, just that it noticed the nodes ASG that didn't match the specified IG:

```
kops rolling-update cluster  --instance-group=master-us-east-1e --master-interval 10m --yes
Using cluster from kubectl context: us-east-1.domain.com

W0226 00:48:57.209824   27209 rollingupdate_cluster.go:90] Found ASG with no corresponding instance group: "nodes.us-east-1.domain.com"
NAME                    STATUS          NEEDUPDATE      READY   MIN     MAX     NODES
master-us-east-1e       NeedsUpdate     1               0       1       1       1
```

```
kops version
Version 1.5.1 (git-01deca8)
```

**Comment by chrislovecnm** [comment]
To add some context.  We got an error as well.  @davidguttman has an ig with a max of 4 and a min of 2.  Two of the nodes are on standby, and he is getting an error when kops calls the API to delete an ec2 instance that is on standby.
