### ISSUE TITLE
We should automatically remove failed nodes within a few hours

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2002]
(I think this is a dup, but can't find it).

We should remove nodes that got NotReady after a "it's not coming back" delay.  @aronchick suggested that we could do this with a health check.  A controller might also be an option, or we could integrate it into the autoscaler (as that deals with instance creation & termination already).

This should be optional, but probably default true I think.

**Comment by mirague** [comment]
Yes I agree! Either a full *Terminate* or trying a *Reboot*? Perhaps a combination?

**Comment by geojaz** [comment]
This is a good one. 
I think we should take a look at the autoscaler and I think we could default to Reboot, perhaps configurable in the manifest to AllowTermination.

**Comment by chrislovecnm** [comment]
@justinsb this is probably akin to the issue that I put in with core about STONITH.

**Comment by justinsb** [comment]
Thanks @chrislovecnm - closed that issue (as it was drifting off-topic) in favor of this one.

**Comment by GTB3NW** [comment]
/reopen

For certain network topologies, it's feasible that a cluster could get split-brained. STONITH is not just about "fixing" unresponsive nodes, it's important for fixing split brains too. Consider a situation where control-plane to kubelet communication is severed, but OOB is feasible through cloud API's or a separate switch dedicated to on board OOB's. The kubelet's last instructions were "advertise this IP and run this service". If a kubelet doesn't gracefully signout before we lose communication, much like pacemaker clusters we should fence it where possible.
