### ISSUE TITLE
Kops deleted AWS resources it shouldn't like Cloudformation Stacks

### ISSUE THREAD

**Issue by leandrocr** [kubernetes/kops#2003]
Version: 1.5.2-beta.1 (git-d84c8fc)

I managed to create my cluster successfully using Kops with the following parameters:
`kops create cluster --network-cidr 172.18.0.0/16 --networking weave --topology private --master-count 1 --node-count 2 --zones ap-southeast-2a --bastion --name lrepolho.mydomain.com`

Everything was working smoothly for a few days, it was running in parallel with other resources (staging AWS account) like Cloudformation, VPCs, Instances... Until I run the command:
`kops delete cluster lrepolho.mydomain.com --yes`

I noticed that the command was taking too long to finish, so I manually canceled it. When I looked into the AWS Console a lot of my Cloudformation Stacks were deleted by Kops. I was using my personal AWS credentials, not using a specific Kops user with the proper IAM permissions like suggest by the docs :-(

There were lots of API commands in CloudTrail such as DeleteSubnet, DeleteAutoScalingGroup, DeleteRolePolicy, DeleteSecurityGroup, DeleteStack, etc...

**Comment by chrislovecnm** [comment]
> Everything was working smoothly for a few days, it was running in parallel with other resources (staging AWS account) like Cloudformation, VPCs, Instances...

Can you give us an example of how to create some of this stuff, so we can test?

**Comment by andrewsykim** [comment]
I deleted my kops cluster the other day and my cloudformation stacks was deleted with it :(

**Comment by kris-nova** [comment]
Hey @andrewsykim which version of kops are you running?

That problem should have been fixed here https://github.com/kubernetes/kops/pull/1992

**Comment by kris-nova** [comment]
But if we want to disable the CloudFormation delete (again) let's go ahead and do that before 1.5.2

**Comment by andrewsykim** [comment]
I was definitely running an earlier version, thanks @kris-nova :)

**Comment by chrislovecnm** [comment]
Currently disabled. Removing p0
