### ISSUE TITLE
rebuilding cluster info after accidental delete of kubectl config

### ISSUE THREAD

**Issue by justechn** [kubernetes/kops#2008]
I am following the [tutorial](https://github.com/kubernetes/kops/blob/master/docs/aws.md) and during the process I acidently deleted my kubectl config file with the cluster info. Now I am stuck in a strange state where I cannot update the cluster. How can I rebuild the config data that was in the kubectl config file?

Because this is just a tutorial I can easily delete the cluster and then create it again. But once I start doing this on production I don't want to have to resort this deleting the cluster. Is there a better way? Do I just need to make sure I have 10 copies of the config file at various locations so it does not get deleted? Am I making a bigger deal out of this than it needs to be?

As a follow up. There are other people who also will need to manage the cluster. How can I give them access?

**Comment by tanner-bruce** [comment]
https://github.com/kubernetes/kops/blob/master/docs/tips.md#create-kubecfg-settings-for-kubectl

To give other people access have them set the appropriate KOPS_STATE_STORE and then they can run the same command.

**Comment by justechn** [comment]
thanks,

I also discovered `kops export kubecfg ${NAME}` will write the config to the kubectl file
