### ISSUE TITLE
Internal load balancers should prefer private subnets

### ISSUE THREAD

**Issue by zacblazic** [kubernetes/kops#2011]
**Problem**

I'm using the following [magical (and undocumented) annotation](https://github.com/kubernetes/kubernetes/issues/17620#issuecomment-223718021) to tell the kubernetes cloud provider to provision an internal load balancer instead of a public one:
```yaml
service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```
My expectation was that internal load balancers would be associated only with private subnets (if they were available of course).

However, even in a cluster with private subnets available, internal load balancers don't always land in availability zones that are associated with these private subnets.

**Suggested Solution**

After a bit of digging, it looks like the [code that chooses subnets for load balancers](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L2345) has a requirement on the following tags being present on the respective subnets:
```go
// The tag name used on a subnet to designate that it should be used for internal ELBs
const TagNameSubnetInternalELB = "kubernetes.io/role/internal-elb"

// The tag name used on a subnet to designate that it should be used for internet ELBs
const TagNameSubnetPublicELB = "kubernetes.io/role/elb"
```
Without these, there is no guarantee you will get private subnets at all (which is what happened to one of our clusters).

I think this can be fixed in two ways:
1. Add the above tags to the respective private or public subnets via kops
2. Change the kubernetes cloud provider code to not have to rely on tags and instead use heuristics such as [presence of an internet gateway](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L2415) to determine if a subnet is public.

**Comment by CharlieSu** [comment]
This happened to me as well when deploying `kops` against an existing VPC.  Tags were not applied to my subnets, even new ones created just for `kops`.  The `kops` tool should at least notify the user that these tags are needed when creating infrastructure resources.

**Comment by mikelorant** [comment]
This is impacting our cluster as well. The documentation needs to be updated to clarify these tags are necessary when managing your own subnets.

**Comment by philipbjorge** [comment]
For anyone wondering, it is my understanding that internal ELBs do not _need_ to be in private subnets to function.

Whichever subnets an ELB is in, it will not have a public IP and only be accessible with its private/internal IP.

**Comment by chrislovecnm** [comment]
@zacblazic is this actually an upstream issue with the Kubernetes AWS cloud provider?  I am wondering if this issue is in the correct GitHub repository.

**Comment by chrislovecnm** [comment]
@zacblazic the kops owners need to talk about design, but I agree it may be a good idea to add more tags tag management in kops.

@justinsb / @blakebarnett / @geojaz any ideas on which networks should be tagged which?  Private is is simple, but do we use utlity or Public for public?

**Comment by geojaz** [comment]
It looks like upstream has what we need to get kops to do what we need. 

This issue is on my radar too- 

@chrislovecnm: I think you're proposing that when we create a private subnet or designated it as shared, we tag it `"kubernetes.io/role/internal-elb"`. Likewise, I think we can tag the utility subnets `"kubernetes.io/role/elb"`. What do you mean by Public? 

Dropping tags on any subnets that we touch seems like a fairly straightforward way to go. What am I missing? :)

**Comment by geojaz** [comment]
Sorry, I'm silly. I figured out what Public is.

**Comment by owenmorgan** [comment]
any update on this?
