### ISSUE TITLE
EBS Volumes on Nodes/Masters

### ISSUE THREAD

**Issue by AlexLast** [kubernetes/kops#2018]
Recently I've been doing some DR testing of nodes and masters and checking what happens when storage such as EBS volumes are lost.

One thing I've come to notice is that volumes for nodes aren't named or tagged, obviously they're creating by the ASG launch configuration, but would there be some way to tag these similarly to the etcd volumes?

My use case would be automating some snapshots of EBS volumes for potentially recovering PV's, etcd in a region failure unless there's some better way I'm unaware of? Thanks.

**Comment by justinsb** [comment]
So for nodes, the volumes are ephemeral.  If you want persistent storage on your pods, you can attach a PV (or dynamically create a PVC), in which case that storage is persistent.  Each PV is its own EBS volume, and will not go away if a node crashes / is terminated.

Can you explain more about your use-case though?  I'm not sure I fully understand...
