### ISSUE TITLE
Document how to create dashboard & other key components

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#202]

**Comment by azell** [comment]
I installed a fresh k8s 1.3.4 cluster on AWS and find that the dashboard has been installed automatically.  However the dashboard pod has errors:

```
Starting HTTP server on port 9090
Creating API server client for https://100.64.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: the server has asked for the client to provide credentials
```

I can hit the master over HTTPS though the /ui URL shows:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

**Comment by azell** [comment]
This error might disappear when I `rm -fr $HOME/.terraform.d/`.

**Comment by justinsb** [comment]
I've written up how to install addons: https://github.com/kubernetes/kops/blob/master/docs/addons.md

@azell I think the problem is that the disks are persisting, I think because if you use the terraform workaround you need to `kops delete cluster` to delete the disks.  With terraform 0.7 released, I'm going to see if we can get rid of the workaround, or document the need to `kops delete cluster`: https://github.com/kubernetes/kops/issues/256

Going to close this issue in favor of #256.  And if problems persist with the dashboard, please do open an issue for that also (or ping me directly!)

**Comment by azell** [comment]
Great, will use `kops delete cluster`.
