### ISSUE TITLE
Support for specifying parameters to the api server

### ISSUE THREAD

**Issue by ivansoban** [kubernetes/kops#203]
In order to specify the [authorization mode](http://kubernetes.io/docs/admin/authorization/) for a Kubernetes master, the `--authorization-mode` command line parameter needs to be able to be set via `kops edit cluster` or some similar method.

**Comment by chrislovecnm** [comment]
@justinsb / @ivansoban is this still open?

**Comment by zapman449** [comment]
@chrislovecnm would an approach like https://github.com/kubernetes/kops/issues/618#issuecomment-252804973 allow you to specify the arguments needed?

This ignores how to actually retrieve the --authorization-policy-file (presumably from KOPS_STATE_STORE)... but that's probably solvable.

**Comment by justinsb** [comment]
We actually have now mapped the `authorization-mode` flag.

You can set it like this (IIRC) in `kops edit cluster`, if you are using kops 1.5.0 beta1 or above:

```
...
spec:
  kubeAPIServer:
    authorizationMode: rbac
```

We still hope / intend to create a full example or drop-in for auth, particularly with rbac leaving alpha in 1.6, but in the meantime we are exposing the flags so kops is not the blocker any more!

Closing, but do comment/reopen (or open a new issue) if this doesn't work for you!
