### ISSUE TITLE
Fix addons doc - correct the route53 command

### ISSUE THREAD

**Issue by netflash** [kubernetes/kops#2035]
Current page [https://github.com/kubernetes/kops/blob/master/docs/addons.md] refers twice to `kubectl apply -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/monitoring-standalone/v1.2.0.yaml` both for `Monitoring with Heapster - Standalone` and for `Route53 Mapper`

**Comment by yissachar** [comment]
This was fixed [here](https://github.com/kubernetes/kops/commit/b1d5ad4664b155d49a3e655b8b299b2892d32b92)
