### ISSUE TITLE
Allow running pods on the master

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#204]
Particularly daemonset nodes

Will need to boost the CIDR, and likely set up kube-proxy

**Comment by justinsb** [comment]
We probably want two options:

1) Don't register the master at all (the old kube-up AWS behaviour, where everything was simple)
2) Register the master but make it work

"Make it work" probably means:

* expand the pod cidr / auto-allocate it
* run kube-proxy
* enable debugging handlers on the kubelet
* add labels / taints so that we can _not_ run things on the master

**Comment by zapman449** [comment]
How would this manifest?  Changes to the User Data Script to make these tweaks?

**Comment by crohling** [comment]
Allowing pods on the master would be awesome for allowing daemonsets to work on the nodes as well as the master.

**Comment by zapman449** [comment]
1. Expand the pod cidr / auto-allocate it:

    * change `--pod-cidr=10.123.45.0/30` to `--pod-cidr=10.123.45.0/28` in /etc/sysconfig/kubelet and run `sudo systemctl restart kubelet`

2. run kube-proxy:

    * in `/etc/systemd/system/kube-proxy.service`, put this content:

    ```
    [Unit]
    Description=Kubernetes Kube Proxy
    Documentation=https://github.com/GoogleCloudPlatform/kubernetes
    
    [Service]
    ExecStart=/usr/local/bin/kube-proxy \
      --master=https://127.0.0.1:8080 \
      --kubeconfig=/var/lib/kubelet/kubeconfig \
      --proxy-mode=iptables \
      --v=2
    
    Restart=on-failure
    RestartSec=5
    
    [Install]
    WantedBy=multi-user.target
    ```

    * run: `(cd /usr/local/bin ; sudo wget https://storage.googleapis.com/kubernetes-release/release/v1.3.2/bin/linux/amd64/kube-proxy ; sudo chmod 755 kube-proxy)`

    * run `sudo systemctl start kube-proxy`

3. Enable debugging handlers on the kubelet: not sure.

4. Add labels / taints:

    * run `kubectl taint nodes MASTER_NODE_NAME dedicated=master:NoSchedule`

And everything seems to work.

**Comment by zapman449** [comment]
And, it missed at least one thing.  The master needs to update the route table to point 10.123.45.0/28 (in this example) back to it's ENI

**Comment by zapman449** [comment]
one other piece: kubelet on master needs to not use `--hairpin-mode=none`.  

Full 'DAEMON_ARGS' for kubelet:

```
DAEMON_ARGS="--allow-privileged=true --api-servers=https://MASTER_NAME_HERE --babysit-daemons=true --cgroup-root=docker --cloud-provider=aws --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --config=/etc/kubernetes/manifests --configure-cbr0=true --enable-debugging-handlers=false --non-masquerade-cidr=100.64.0.0/10 --pod-cidr=10.123.45.0/28 --reconcile-cidr=false --register-schedulable=false --v=2"
```

Note the MASTER_NAME_HERE bit.
