### ISSUE TITLE
Support for --cors-allowed-origins with kube-apiserver

### ISSUE THREAD

**Issue by jonjomckay** [kubernetes/kops#2045]
Hello - is there a way to specify the `--cors-allowed-origins` option to `kube-apiserver`? I can't find any docs that reference how to do this and it'd be great if it were possible!

**Comment by etwillbefine** [comment]
Can this be reopened please?

**Comment by rifelpet** [comment]
/reopen

This should be fairly trivial to add if someone is interested in tackling it. Instructions are [here](https://kops.sigs.k8s.io/development/api_updates/) and [this](https://github.com/kubernetes/kops/blob/3f079cd1d9ed4411a11616290212bf70042d113e/pkg/apis/kops/componentconfig.go#L255) is the relevant struct, as well as the equivalent struct in the v1alpha2 subdirectory.
