### ISSUE TITLE
documentation on creation of federated clusters

### ISSUE THREAD

**Issue by mbranyon** [kubernetes/kops#2046]
Something seems to be missing on this. You can get a list of federated clusters, and even update a federation, but I don't see a way to create a federated cluster.

**Comment by arthurlm44** [comment]
In trying to build a cloud-provider-level-disaster resistant cluster, using kops to create a federated cluster would make my organization's workflow way smoother! This would be great.

**Comment by chrislovecnm** [comment]
Yes that is one area that we need to document better! 

@justinsb you have deverloped this, did you use the federation core tool to enable federation in the servers?

**Comment by exul** [comment]
This is probably a duplicate of https://github.com/kubernetes/kops/issues/1244

**Comment by alexw23** [comment]
Looking forward to this as it might solve my question #2056

**Comment by chrislovecnm** [comment]
Yes this seems to be a duplicate. @alex23 do you want to close?

**Comment by chrislovecnm** [comment]
Closing as duplicate
