### ISSUE TITLE
cloudLabels for API ELB

### ISSUE THREAD

**Issue by hridyeshpant** [kubernetes/kops#2048]
It seems cloudLabels is not putting TAG on API ELB's.
kops create cluster --v=3 --state=s3://ewe-kubernetes-dev --cloud=aws \
    --name=kubetnets.us-west-2.dev.expedia.com \
    --ssh-public-key=~/.ssh/kube_aws_rsa.pub \
    --master-size=t2.medium \
    --cloud-labels="Team=CAT" \
    --master-zones=us-west-2c,us-west-2a,us-west-2b \
    --network-cidr=10.4.0.0/16 \
    --vpc=vpc-030e8f64 \
    --node-count=3 \
    --node-size=t2.micro \
    --topology private \
    --networking weave \
    --zones=us-west-2c,us-west-2a,us-west-2b \
    --channel=alpha

Result : k8 API ELB's dont have AWS TAG mentioned in cloud-labels.

**Comment by richarvey** [comment]
I can confirm this is the case, labels are not applied to the ELB, so if you have a AWS janitor to clear up untagged resources this is an issue.

**Comment by estebancrw** [comment]
I'm also having this issue. Any way to work around it at the moment? or any plans into adding this use case in the future?

**Comment by geojaz** [comment]
My understanding is that cloud labels are associated with InstanceGroups, not all AWS resources. In this case, I think kops is acting as intending. 

It looks like you'd like to be able to assign a "global" tag to all resources in your cluster? This sounds like a reasonable thing to do and I would be open to thinking about implementation.

**Comment by chrislovecnm** [comment]
So we already have global tags, KubernetesCluster for instance. But not sure if we should use it in the elb, as I am not certain how the cloud provider will react ;)

Let me know Eric

**Comment by estebancrw** [comment]
@geojaz That is exactly my use-case. Some organizations have created "janitors" that delete AWS resources not tagged as they specify. This "janitors" tend to be for enforcing their tagging policies so they can bill correctly their own business units and budget accordingly.

@chrislovecnm would be an awesome feature to be able to extend the CloudLabels into global tags.

**Comment by brantburnett** [comment]
/remove-lifecycle stale

This is also an issue for my company, for the same reasons as mentioned above surrounding billing

**Comment by jcardoso-bv** [comment]
Also an issue for my company (billing).

**Comment by flamingspaz** [comment]
Has anyone found a workaround for this, other than manually applying the tags?

**Comment by wingyplus** [comment]
I just sent a patch to fix this problem. Needs someone to help me test this patch. Suggestions are welcome. :)

**Comment by chrisz100** [comment]
/reopen 

Fix seems to have gotten reverted
