### ISSUE TITLE
Instance Group Scaling Priorities

### ISSUE THREAD

**Issue by stevenpall** [kubernetes/kops#2053]
Hi there,

I'm looking to set up a couple of instance groups: one comprised of standard EC2 instances, another of spot instances (as per https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#converting-an-instance-group-to-use-spot-instances) . I'm also looking at utilizing the cluster autoscaler feature (https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler). I was wondering if there is currently a way to prefer scaling up one instance group before another. Ideally I would like to have the autoscaler scale up or down the number of instances in the spot instance group before the standard instance group to utilize spot instances as much as possible.

Thanks!

**Comment by stevenpall** [comment]
I was looking into this and came across https://github.com/kubernetes/contrib/pull/2348. I think this will satisfy my use case if/when it's merged in. Hopefully kops can eventually expose this as a configuration option to the cluster autoscaler.

**Comment by chrislovecnm** [comment]
It is merged. Closing
