### ISSUE TITLE
Multi Region Layout

### ISSUE THREAD

**Issue by alexw23** [kubernetes/kops#2056]
Is it possible to run kops in a multi-AZ multi-region mode?

I wanted to have the following structure:

AWS ap-southeast-2
- masters (a/b/c)
- nodes (a/b/c)

AWS eu-west-2
- nodes (a/b)

**Comment by thaniyarasu** [comment]
yes you can create and manage multi cloud multi-region cluster in kops, 
that is called Federation with High Availablity. 
you can have different cluster under different providers like GKE,AWS,On-premise,etc,

here are my setup 

user@ubuntu:~$ kops get clusters
us-east-1.dev.example.com
us-west-2.dev.example.com
ap-south-1.dev.example.com
user@ubuntu:~$ kubectl config current-context
us-east-1.dev.example.com
user@ubuntu:~$ kops export kubecfg us-west-2.dev.example.com
Kops has set your kubectl context to us-west-2.dev.example.com
user@ubuntu:~$ kubectl config current-context
us-west-2.dev.example.com

**Comment by alexw23** [comment]
Thanks @thaniyarasu, however I don't get how can do this? 

It seems like you've just setup multiple clusters with Kops and then linked them using federation? Did you read any documentation on how do to this?

**Comment by thaniyarasu** [comment]
here is the federated demo nginx service  explained by one of the core member
https://www.youtube.com/watch?v=pq9lbkmxpS8&t=37s

also go through this https://github.com/kubernetes/kops/tree/master/docs

**Comment by alexw23** [comment]
Closed for #1244
