### ISSUE TITLE
Domain name kubernetes.com mentioned instead of example.com

### ISSUE THREAD

**Issue by checkaayush** [kubernetes/kops#2058]
In Scenario 3 under section _Configuring DNS_ at [https://github.com/kubernetes/kops/blob/master/docs/aws.md](url), shouldn't _subdomain.kubernetes.com_ be _subdomain.example.com_?

**Comment by justinsb** [comment]
Thanks @checkaayush - I proposed #2114 which uses example.com throughout (that's what we should be using for docs), and also switched the kubernetes.kubernetes.com -> subdomain.example.com.  Thanks!
