### ISSUE TITLE
Drive kops-aws-slow to green

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#2060]
Help wanted: We need to drive [kops-aws-serial](https://k8s-testgrid.appspot.com/google-aws#kops-aws-slow) to green. It looks like there's a variety of different failures, so feel free to use this as an umbrella bug, or fork off bugs.

The failures here could just be `NodePort` related; c.f. kubernetes/kops#775 & kubernetes/test-infra#2143

**Comment by chrislovecnm** [comment]
Duplicate
