### ISSUE TITLE
1.5.2 upgrade causes kube-dns selector conflict

### ISSUE THREAD

**Issue by rrichardson** [kubernetes/kops#2061]
I just noticed this on my cluster (a bit late :) ) 

```
kubectl --namespace=kube-system get events
LASTSEEN    FIRSTSEEN   COUNT     NAME                 KIND         SUBOBJECT   TYPE      REASON                       SOURCE                     MESSAGE
<invalid>   22h         2692      kube-dns             Deployment               Warning   SelectorOverlap              {deployment-controller }   found deployment kube-system/kube-dns has overlapping selector with an older deployment kube-system/kube-dns-v20, skip syncing it
```

It would appear that kube-dns-v20 deployment (what was installed by 1.4* and prior)  has the same label selector as the current kube-dns deployment.   

I am also assuming that  kube-dns is intended to replace kube-dns-v20,  so I guess the upgrade process needs to seek and destroy kube-dns-v20 if it is present.  I'm going to attempt to delete it on my dev cluster and see what happens.

**Comment by rrichardson** [comment]
Deleting the deployment worked (although my cluster was without DNS for a minute or so)   I am happy to make a PR for this.  Although I guess it won't effect that many people going forward.  Thoughts?

**Comment by skymeyer** [comment]
Same happened here after upgrade. Manual removal of ```kube-dns-v20``` deployment worked.

**Comment by mamoit** [comment]
I somehow survived too much time without noticing this.
Thanks @rrichardson, deleting it worked.
