### ISSUE TITLE
Success Story of Kops on Production

### ISSUE THREAD

**Issue by leoblanc** [kubernetes/kops#2065]
Hi, this is not really an issue, sorry :)

But, just in case you are interested on collect success stories about Kops, this is a sample of how the easy multi-az support of Kops helped a company to survive to the Amazon's outage last week:

https://thenewstack.io/kubernetes-credited-saving-spire-service-s3-outage

> He credits the use of kops, Kubernetes’ command line tool for automating the deployment of entire clusters — including on EC2 — as critical to the resilience of Spire’s services during S3’s downtime.
> 
> “Kops makes it remarkably straightforward to provision multiple availability zones,” Scott told The New Stack. “As part of the create cluster command, you can simply choose the availability zones you’d like your instances provisioned in.”

Please close this issue whenever you want.

Thanks for your work!

**Comment by imsky** [comment]
maybe kops needs a "who's using kops" section - as a prospective user i'd be interested in seeing that

as an actual user, i'd be interested in contributing :)

**Comment by kris-nova** [comment]
This is great! Thank you @leoblanc!

**Comment by chrislovecnm** [comment]
Closing - thanks
