### ISSUE TITLE
Travis is not building channels folder

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2070]
So we have code in the channels folder that does not have unit tests, and is not being built by travis.  e2e caught it, but maybe we should do more of the builds with travis as well.   I do not think we are actually building kops ...

- channels
- protokube
- dnscontroller

All not built with travis.

**Comment by justinsb** [comment]
We run the protokube & dns-controller tests as part of the `test` target.

**Comment by chrislovecnm** [comment]
channels tests are not being run ...

**Comment by chrislovecnm** [comment]
I seem to be wrong ... but oddness that this was found: https://github.com/kubernetes/kops/pull/2953

**Comment by justinsb** [comment]
Fixed in #2958
