### ISSUE TITLE
kops delete -f

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2071]
We have `create -f` ... you know we should have `delete -f` as well!

**Comment by kris-nova** [comment]
So in order for `kops` to look up a cluster all we need is

 1. Cluster Name

(See how `kops delete cluster` uses `ListResources()` [here](https://github.com/kubernetes/kops/blob/master/cmd/kops/delete_cluster.go#L124-L126))

Literally, the only thing `kops delete cluster -f` (assuming that is what you mean) would offer would be a shorthand for `kops delete cluster $NAME` where `kops` just pulled the name out of the `.yml` file... Is this what we want?

**Comment by chrislovecnm** [comment]
> Literally, the only thing kops delete cluster -f (assuming that is what you mean) would offer would be a shorthand for kops delete cluster $NAME where kops just pulled the name out of the .yml file.

Yep pretty much.

I run `kubectl delete -f myds.yaml` all the time and having that parity with kubectl I think is important.

**Comment by geojaz** [comment]
@chrislovecnm @kris-nova I see where tall clove is coming from. It's not a lot of work (famoust words) and it just helps our software feel "complete".

I vote this us worth bringing into 1.6

**Comment by MrTrustor** [comment]
I'm going to take a shot at this if it's okay :-)
