### ISSUE TITLE
Leaking Launch Configurations w/ Spot Instances

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2072]
kops seems to be leaving launch configuration around when using spot instance prices.

1. create cluster via create -f, I have not recreated the other routes - created basic cluster, public, weave
1. set the spot price too low to get an instance
1. edit the instance group with a new max
1. kops update

You should have two different launch configs now.  One with the old price, and one with the new price.

**Comment by Sprinkle** [comment]
Just hit the same issue on 1.6 beta 1 too

**Comment by chrislovecnm** [comment]
Yep it is not fixed yet ;)

**Comment by cdobbyn** [comment]
This exists in v1.13.0. Just noticed it myself, kinda annoying but not a game changer unless you're changing spot prices all the time.

**Comment by rifelpet** [comment]
kOps has migrated to LaunchTemplates which use a different versioning strategy, so this issue is no longer applicable

/close
