### ISSUE TITLE
Improve Documentation for GCE

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2081]
We need to improve our documentation for setting up GCE with kops.  A couple of areas include

1. docs on how to setup cloud DNS
1. docs in general/example howto
1. information on instance names - the instances names that you use are very specific for instance "--image "ubuntu-os-cloud/ubuntu-1604-xenial-v20170202"
1. document what the differences / limitations are between GCE and AWS

**Comment by techmaniack** [comment]
Can you provide link to current documentation for GCE. I could find [this](https://github.com/kubernetes/kops/blob/master/vendor/k8s.io/kubernetes/docs/getting-started-guides/gce.md) which isn't helpful at all.

**Comment by chrislovecnm** [comment]
We have zero docs currently :(

This is an alias that I use.

```
function kops-gce() {
        export KOPS_STATE_STORE="gs://mykops-kops"
        export NODE_SIZE=${NODE_SIZE:-n1.highmem-2}
        export NODE_COUNT=${NODE_COUNT:-3}
        export ZONES=${MASTER_ZONES:-"us-east1-b,us-east1-c,us-east1-d"}
        export MASTER_SIZE=${MASTER_SIZE:-n1.standard}
        export KOPS_FEATURE_FLAGS=AlphaAllowGCE

        kops delete cluster $KOPS_SERVER --yes

        kops create cluster $KOPS_SERVER \
                --zones $ZONES \
                --master-zones $ZONES \
                --node-count $NODE_COUNT \
                --project $MY_PROJECT \
                --image "ubuntu-os-cloud/ubuntu-1604-xenial-v20170202" 
}

```

rolling-updates do not work at this point, but you can do that manually.  Also if you use a domain name of mycluster.k8s.local you can get around dns if you want.  But I would setup DNS personally.

There are definitely gaps in the support, and it is in alpha.

**Comment by mashayev** [comment]
Hi,
Is there any update here? I want to test KOPS in GCE but I don't find any Docs about it :(

**Comment by chrislovecnm** [comment]
No docs still. I pretty much run the above with dns configured and it works.

Rolling updates and a couple of other things are not supported yet.

**Comment by chrislovecnm** [comment]
We have docs now. See tutorials.

Closing
