### ISSUE TITLE
Weave manifest should honor NonMasqueradeCIDR

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2085]
@chrislovecnm can you comment as to the env var that must be set?

**Comment by chrislovecnm** [comment]
IPALLOC_RANGE 

Here are the options we can tweak:

> CHECKPOINT_DISABLE – if set to 1, disable checking for new Weave Net versions (default is blank, i.e. check is enabled)
> IPALLOC_RANGE – the range of IP addresses used by Weave Net and the subnet they are placed in (CIDR format; default 10.32.0.0/12)
> EXPECT_NPC – set to 0 to disable Network Policy Controller (default is on)
> KUBE_PEERS – list of addresses of peers in the Kubernetes cluster (default is to fetch the list from the api-server)
> IPALLOC_INIT – set the initialization mode of the IP Address Manager (defaults to consensus amongst the KUBE_PEERS)
> WEAVE_EXPOSE_IP – set the IP address used as a gateway from the Weave network to the host network – this is useful if you are configuring the addon as a static pod.
> WEAVE_MTU – Weave Net defaults to 1376 bytes, but you can set a smaller size if your underlying network has a tighter limit, or set a larger size for better performance if your network supports jumbo frames – see here for more details.

From here https://www.weave.works/documentation/net-latest-kube-addon/

**Comment by chrislovecnm** [comment]
The fix is laid out in https://github.com/kubernetes/kops/issues/2085

**Comment by chrislovecnm** [comment]
Closing as we have the pr in and tested

**Comment by chrislovecnm** [comment]
Closing fixed in master
