### ISSUE TITLE
GCE Leaking resource on cluster delete

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2086]
- leaking fw rules on delete
- leaking dns entries on delete

**Comment by chrislovecnm** [comment]
@justinsb we are still leaking fw rules.

**Comment by chrislovecnm** [comment]
This seems to becfixed

**Comment by geojaz** [comment]
We are currently (1.17-alpha.1) leaking DNS records (`api.*`/`api.internal.*`) on cluster delete in GCE.
We do not appear to be leaking firewall rules.
