### ISSUE TITLE
Allow the user to configure the docker storage

### ISSUE THREAD

**Issue by exul** [kubernetes/kops#209]
When using `kube-up.sh` one can configure the docker storage by [setting the environment variable](https://github.com/kubernetes/kubernetes/blob/master/docs/design/aws_under_the_hood.md#storage) `DOCKER_STORAGE`  (e.g. `DOCKER_STORAGE=btrfs`).

It would be nice to be able to configure the docker storage with kops too.

**Comment by chrislovecnm** [comment]
Well this is an interesting one.  We are seeing multiple bugs with different docker storage options. I would recommend that we use the most tested option for docker.  You can bring your own ami, and may be able to overide the docker settings.  Would need to test.

@exul thoughts?

**Comment by exul** [comment]
Yes, that sounds like a reasonable decision.

Actually when I created the issue, it was because we had problems when using k8s with aufs. So I'm fine with whatever the most tested/stable storage is.

**Comment by chrislovecnm** [comment]
Closing
