### ISSUE TITLE
kops create -f filename throwing region is not a recognized EC2 region issue.

### ISSUE THREAD

**Issue by chandanpal** [kubernetes/kops#2092]
I0310 05:20:36.105033   19188 aws_utils.go:39] Querying EC2 for all valid regions
F0310 05:20:36.745124   19188 helpers.go:118] error: error populating configuration: Region is not a recognized EC2 region: "" (check you have specified valid zones?)

 region name is empty
How to provide AWS region Name??

kops create cluster working fine but kops create -f < filename> throwing error.

[ha.txt](https://github.com/kubernetes/kops/files/833652/ha.txt)

**Comment by geojaz** [comment]
@chandanpal I think your diagnosis that the regions isn't sent on your side is pretty spot on. There are a number of environment variables that AWS may look for. In this case, try setting the region that you want to use before you run anything: 

`export AWS_DEFAULT_REGION=us-east-1` or similar

**Comment by kustuntas** [comment]
Similarly you need to set some others as well:
```
AWS_SECRET_ACCESS_KEY
AWS_ACCESS_KEY_ID
```
Also I believe Kops derive the region name from the zones you pass to the `kops create` command.

**Comment by chandanpal** [comment]
thanks for your reply @geojaz and @kustuntas.

I have set below mentioned environment variable,
DNS_ZONE_PRIVATE_ID, AWS_SECRET_ACCESS_KEY, AWS_ACCESS_KEY_ID, KOPS_STATE_STORE, VPC_ID
NAME, AWS_DEFAULT_REGION.

Things are working fine with kops create cluster but kops create -f < filename> throwing error.

even i have given the correct zone to ha.yaml(Attached earlier comment) file.

**Comment by kustuntas** [comment]
Hmm. I looked into the code. In some cases, it is also looking for AWS_REGION also. Not sure if that applies to your case, but just in case, please set that as well.

If you are confident of the content in your yaml file, you can set SKIP_REGION_CHECK to any value, e.g. "true", and you can bypass the check. Not sure if this will cause another issue afterwards though.

Did you hand craft the yaml file? Although I cannot spot anything wrong with it, you might have done something wrong. I would suggest creating a sample cluster using `kops create cluster` command and then execute `kops get cluster --name=<cluster name here> -o yaml --full` to get the correct yaml and edit details.

**Comment by tiadobatima** [comment]
Had a similar problem. I added "zones" to the cluster spec:
```
    zones:
      - name: us-west-2a
```

**Comment by justinsb** [comment]
So in the file you attached, you have specified the version as v1alpha1, but you are using v1alpha2 features.  I changed v1alpha1 to v1alpha2 and `kops create -f` did then work.

Also, did you obfuscate the name of the cluster?  Because typically you want to name the cluster `cluster.example.com`, not `example.com`.  `example.com` should work, but means you can only have one cluster in your domain :-)

As a tip, it is often easier to start with `kops create cluster ...`, and then get the yaml files from `kops get cluster -oyaml` and `kops get ig <name> -oyaml`.  Or if you did this, I guess we have a bug!

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by WillemMali** [comment]
I got the same errors after removing this section from my `cluster.yaml`:

```
subnets:
- cidr: 172.20.32.0/19
  name: eu-west-1a
  type: Public
  zone: eu-west-1a
```

I don't understand why I need to explicitly set this and why `kops` doesn't catch this before sending it off to AWS. It seems reasonable to me to derive this from the other parts of the spec, but it seems like `kops` "autofill" for specs isn't used when applying .yaml files.

**Comment by chrislovecnm** [comment]
The subnet section is required ;)

Closing as I think this is resolved. Please reopen if needed
