### ISSUE TITLE
More release process improvements needed

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2093]
I think our release process is still a little too hard.

I am thinking that instead of tagging a version, building it and publishing it, we instead tag an existing SHA.

TODO:

* [ ] Check how kubernetes / other projects do it
* [ ] Make sure we have test results for the release-1.X branch (presuming we want to release from that)
* [ ] Make sure we have the complete releasable build artifacts for the release 1.X branches
* [ ] Get the cherry-picking process figured out

(Every time I mess up the release we have to skip a number, depending on how far through the process I got.  Hence 1.5.3 instead of 1.5.2.  In that case it was because I cherry-pick an extra commit, so really root cause there is that we need to explicitly cherry pick to the release branches, rather than doing a fast-forward).

**Comment by chrislovecnm** [comment]
Great stuff!!!

Here is more:

- binary / docker / vm images - all of these are updated in a release, and we need three+ people with proper access
- automated release process, push a button, we have a new release
- sha for the big Mary release
- container for kops release
- brew update for kops release 


I know I am missing a couple of items.

**Comment by chrislovecnm** [comment]
cc: @denniswebb @zmerlynn 

@denniswebb adding you since you just contributed the docker container.  
@zmerlynn adding you since you have probably the most knowledge around our testing process, besides @justinsb 

@justinsb you mentioned that the retrospective for 1.6 had some ideas around how we can automate our release process more?  Who was the person driving it?

**Comment by chrislovecnm** [comment]
Just added https://github.com/kubernetes/kops/issues/2412 - I am pretty much done with babysitting travis ...

**Comment by chrislovecnm** [comment]
Closing as duplicate
