### ISSUE TITLE
route53-kubernetes addon needs extra permissions for kops 1.5.2 and 1.5.3

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/kops#2100]
master nodes previously had route53:* iam permissions in kops 1.5.2 this was changed to specific permissions.  For the route53 pod to function it requires `ListHostedZonesByName`

**Comment by sstarcher** [comment]
@chrislovecnm

**Comment by brandoncole** [comment]
Oh noes!  Seeing the same thing.  Good catch @sstarcher

**Comment by chrislovecnm** [comment]
@justinsb this is kinda a breaking change. Was this meant to happen?

**Comment by sstarcher** [comment]
Looks like it was changed here - https://github.com/kubernetes/kops/commit/cd795d0c8cf0e7f7d95963f9f9219db5196a8db5

**Comment by sstarcher** [comment]
The changes were to project the cluster from changing other hosted zones which is good, but the route53 pod attempts to find the correct zone by using ListHostedZonesByName

**Comment by chrislovecnm** [comment]
@justinsb I am making this a P0 till we figure out if this was a braking change that we meant to happen.

**Comment by chrislovecnm** [comment]
Here is the PR. https://github.com/kubernetes/kops/pull/1969

@zytek was there a reason that the IAM perm was removed?

**Comment by justinsb** [comment]
@sstarcher can you confirm the error message you are seeing, and the component you are seeing it from?

**Comment by sstarcher** [comment]
component is `route53` and it was a lack of permissions on `ListHostedZonesByName`
I reverted back to kops 1.5.1 so I don't have the log atm.

**Comment by chrislovecnm** [comment]
I think that perm was removed in error. Thoughts @justinsb?

**Comment by chrislovecnm** [comment]
Also, we do not have route53 interact with another hosted zone, only the zone that the cluster owns.

**Comment by justinsb** [comment]
Do you mean `dns-controller`?  I'm just try to find where we call `ListHostedZonesByName`.  The only place I can see where we call it is in `upup/pkg/fi/cloudup/awstasks/dnszone.go` which I think is `kops`-side only, i.e. not this IAM role

**Comment by chrislovecnm** [comment]
This is impacting https://github.com/wearemolecule/route53-kubernetes that we run.  Not an internal kops component.

**Comment by chrislovecnm** [comment]
So talking with @justinsb this was expected, but we probably needed to call out the role removal more clearly in the release notes.

Users have two options:

1. Use kops edit and add the IAM role
2. Use kops create -f with a yaml manifest with the IAM roles defined.

It is a known issue that create -f is not well documented.

**Comment by chrislovecnm** [comment]
Closing as this is documented and addressed
