### ISSUE TITLE
terraform variable output without terraform management

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2101]
We have some terraform variables that work well (for me at least).  It would be nice to also be able to get these variables without using terraform for management.

**Comment by mikesplain** [comment]
I would certainly be interested in this too. We have alot of other dependencies in aws that need to be configured for each environment.  We generally spin up one cluster per environment and would love to tie cluster changes to other infrastructure changes that are dependent.

**Comment by mikesplain** [comment]
@justinsb This doesn't seem too hard.  I'm assuming the use case is something like:
```
kops create cluster foo
kops update cluster foo --yes
kops toolbox terraform-variables -o vars.tfvars
### In our own private tf, we can interact with kops resources
terraform apply -var-file=vars.tfvars
```
We could do something similar like `kops toolbox dump`.  We could either dump it to a standard variables file or a simple tfvars file that users can import.  Seems like the harder part would be formatting the data to be useful (e.g. not keyed off id's).  

Something like:
```
#tfvars file
kops_sg_api_elb = {
   GroupId = "sg-b692c1df"
   VpcId = "vpc-d6dc4cbf"
   ...
}
```

We're looking to switch from homegrown to kops soon, so I may take a swing at this. Any recommendations or requirements you'd like to see?
