### ISSUE TITLE
Is it possible to customize kube-scheduler start command?

### ISSUE THREAD

**Issue by zfy0701** [kubernetes/kops#2107]
Hi,

I want to customize the --failure-domain flag so I could do more customized scheduling policy, which need to modify the scheduler command, what is the correct way to do that in kops? Can we add some docs?

**Comment by chrislovecnm** [comment]
Currently, the API does not allow for failure-domain configurations.  The API can be updated here https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L588 - contributions are always appreciated!
