### ISSUE TITLE
InvalidArgument writing cluster configuration file

### ISSUE THREAD

**Issue by der** [kubernetes/kops#2108]
Apologies if, as seems likely, this is just user error.

Attempting to create my first AWS cluster. Using kops 1.5.3 then from the initial `kops create cluster` command I get:

```
error writing updated configuration: error writing Cluster "mycluster.net": error writing configuration file s3://clusters.mycluster.net/config: error writing s3://clusters.mycluster.net/mycluster.net/config: InvalidArgument: 
	status code: 400, request id: 252C851DA42534EF
```
[`mycluster` is abbreviation for the actual name]

The identical command and environment settings works (or at least gets further) with kops 1.4.1 but I'm trying to use instance type i3.large which is only supported by 1.5.3.

The S3 bucket exists, the IAM user has full permissions, I'm exporting AWS_ACCESS_KEY_ID,  AWS_SECRET_ACCESS_KEY, KOPS_STATE_STORE correctly. Manual tests of bucket update work using identical credentials but in any case since old kops versions work it seems unlikely to be a permissions problem.

The precise options to kops create cluster doesn't seem to matter. The real command is:

```
kops create cluster \
    --node-count 2 \
    --master-zones=eu-west-1b \
    --zones ${ZONES} \
    --dns-zone mycluster.net \
    --node-size i3.large \
    --vpc=${VPC_ID} --network-cidr ${NETWORK_CIDR} \
    --master-size t2.medium \
    --ssh-public-key=~/.ssh/my.pem \
    ${CLUSTER_NAME}
```

But  a minimal test version fails identically:

```
kops create cluster --zones=eu-west-1b mycluster.net
```

**Comment by justinsb** [comment]
I'm guessing that `s3://clusters.mycluster.net/config` is a typo and it should be `s3://clusters.mycluster.net/mycluster.net/config`?

I'm not entirely sure what is happening, but one thing it could be is that the go SDK (which we are using) is stricter that the aws cli tools about the arguments it accepts.  Also the go sdk does _not_ support two factor auth and other advanced IAM functions.  That said, I would expect a permissions error in that case, not "InvalidArgument" (which is weird)

Could you possibly (1) double check your AWS credentials and then (2) try again with `--v=8` just in case we get some more information logged?

**Comment by der** [comment]
Thanks and sorry for not spotting the advice on use of `--v` flag.

As it says in the report the same credentials (running in the same shell session with the same environment variables) worked with kops 1.4.1 so I don't see how it can have been a permissions error. There's no two factor authentication involved.

However, have now tried on a different machine, installed everything from fresh and using `--v` flag then it gets further but fails later on. I'm wondering if there's some state from using 1.4.1 and then switching to 1.5.3 that caused this, though I did clean out the S3 bucket after the 1.4.1 attempt.

Closing this report as invalid. Apologies for the noise.

**Comment by justinsb** [comment]
Thanks for following up, and sorry that it isn't really solved.  I agree that if the same env vars worked in 1.4 and awscli, then it does seem unlikely to be permissions, but it just seemed like the most obvious thing.

I dig into the code and added logging around the s3-write code paths, so if you do hit this again going up to `--v=8` might help.

I did find one thing: we recognize an env var of `KOPS_STATE_S3_ACL`, which we use for the ACLs for writing to S3.  It's useful for cross-account bucket access.  But I think if that had been invalid (or even whitespace) that would have resulted in invalid error.  #2125 adds explicit logging of the ACL in the error case as well, just in case this was it.

The other possibility is a bad AWS_REGION - again there's some new code in 1.5 around bucket region detection -  but I don't think that would have manifested in this way.

If it happens again, if you can get those `--v=8` logs and ping me with them I'll take a look right away.

**Comment by der** [comment]
Thanks for the active follow up. The suggestion of `KOPS_STATE_S3_ACL` might explain it. I had done some experimentation with different configs under 1.4.1 before I tried for real (under 1.5.2). I do remember seeing mention of that variable and it's possible that env var would have been set (probably to blank). That feels like a likely explanation and so my error for incomplete env var cleaning. 

Lesson: try again in a clean shell environment before reporting problems!
