### ISSUE TITLE
create error: LaunchConfiguration kops 1.5.1 - able to call node-security-groups without value

### ISSUE THREAD

**Issue by dorsegal** [kubernetes/kops#2110]
This is the task

```
 LaunchConfiguration/nodes.k8s.dns.com
  	ImageID             	kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  	InstanceType        	t2.medium
  	SecurityGroups      	[name:nodes.k8s.dns.com id:sg-82da2bfb]
  	AdditionalSecurityGroupIDs	[--master-security-groups]
  	AssociatePublicIP   	true
  	IAMInstanceProfile  	name:nodes.k8s.dns.com id:nodes.k8s.dns.com
  	RootVolumeSize      	20
  	RootVolumeType      	gp2
  	SpotPrice
```

and this is the error:
```
W0312 17:28:00.367534   45150 executor.go:109] error running task "LaunchConfiguration/nodes.k8s.dns.com" (9m56s remaining to succeed): error creating AutoscalingLaunchConfiguration: ValidationError: Must use either use group-id or group-name for all the security groups, not both at the same time
	status code: 400, request id: 79e2d059-0738-11e7-8c81-1dbde3edea63
```

as you can see the task using name and id for the same security group
is there anyway to edit the task manually so i could create it?

**Comment by dorsegal** [comment]
@ori-stoliar

**Comment by chrislovecnm** [comment]
Are you out of launch configs? Have you hit your quota number? Does your account have perms to create a launch config in IAM?

I do not know of a way to have kops use a launch config that you create.

What kops version? Can we get a debug log  with -v 10 switch. With the commands you are usInc.

Thanks!

**Comment by dorsegal** [comment]
Well the version of kops is 1.5.1 like i mentioned in the title.

the task is taken from the command kops update cluster "clustername" (you get a list of all the resources that will be created)
then i added the "--yes" flag to run it.

this is the v10 output : [kops.txt](https://github.com/kubernetes/kops/files/836968/kops.txt)

this is the command i used to create this cluster config:
```
kops create cluster \
    --node-count 2 \
    --zones eu-west-1a,eu-west-1b \
    --master-zones eu-west-1b \
    --dns-zone dns.com \
    --node-size t2.medium \
    --master-size t2.medium \
    --node-security-groups \
    --master-security-groups \
    ${NAME}
```

I didn't hit the quota this is a fresh account and the master autoscaling group and LC was created.

**Comment by chrislovecnm** [comment]
So this is a bug ... But you exposed it by doing something interesting :)

```
W0313 00:45:43.876155   45622 executor.go:109] error running task "LaunchConfiguration/nodes.k8s.dns.com" (9m55s remaining to succeed): error creating AutoscalingLaunchConfiguration: ValidationError: Must use either use group-id or group-name for all the security groups, not both at the same time
```

Your command:

```
kops create cluster \
    --node-count 2 \
    --zones eu-west-1a,eu-west-1b \
    --master-zones eu-west-1b \
    --dns-zone dns.com \
    --node-size t2.medium \
    --master-size t2.medium \
    --node-security-groups \
    --master-security-groups \
    ${NAME}
```

The security group flags are meant to accept extra sec group ids.

```
    --node-security-groups \
    --master-security-groups \
```

What are you trying to do?  You can leave the off if you do not have extra sec group ids to add.

**Comment by dorsegal** [comment]
well at first i created it with values but then i decided to leave it empty.

after creating the cluster without those 2 line it worked

thanks!

**Comment by chrislovecnm** [comment]
I am going to change the name of this issue, and keep it open.

**Comment by chrislovecnm** [comment]
We need to determine if you are still able to use 

```
    --node-security-groups \
    --master-security-groups \
```

flags w/o values.

**Comment by dorsegal** [comment]
well after i run the command
```
kops create cluster \
    --node-count 2 \
    --zones eu-west-1a,eu-west-1b \
    --master-zones eu-west-1b \
    --dns-zone dns.com \
    --node-size t2.medium \
    --master-size t2.medium \
    --node-security-groups \
    --master-security-groups \
    ${NAME}
```

upgraded to kops 1.5.3 and then ran the  kops update cluster "clustername" --yes but the result was the same.

however i didn't use the kops create cluster with 1.5.3

**Comment by justinsb** [comment]
The problem is that the CLI is parsing this as `--node-security-groups=--master-security-groups`

So we see this in the instance group spec: 
```
  additionalSecurityGroups:
  - --master-security-groups
```

That's actually really difficult to fix at the CLI level.  But instead, we can validate that the security group names match the expected format.  I opened a PR #2112 , and with that we get this error:

```
> kops create cluster a.example.com --zones us-east-1c --node-security-groups --master-security-groups

spec.additionalSecurityGroups[0]: Invalid value: "--master-security-groups": security group does not match the expected AWS format
``
