### ISSUE TITLE
Add support to special char "-" for command kops create -f "-"

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kops#2116]
We need to add support for the special char "-" as we currently use it in kubectl:

kexpand expand deployment.yaml -f values.yaml | kubectl create -f -

**Comment by dennis-bell** [comment]
Could somebody explain the benefit of this? saw it before with Kubectl but dont fully understand the benefit.

**Comment by chrislovecnm** [comment]
You able to contribute this?

**Comment by olemarkus** [comment]
This works just fine now.

/close
