### ISSUE TITLE
Rolling Update with validate need to be able to tweak validate more

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2119]
1. kops edit ig - change the number of nodes
2. kops edit cluster
3. kops update cluster
4. kops rolling-update

This causes the cluster to get into a state where you cannot validate the cluster.  We need to fine tune this more, provide more flexibility

**Comment by chrislovecnm** [comment]
This should be addressed in HEAD as validate was fixed.  Need to test.

**Comment by johngmyers** [comment]
@chrislovecnm You've kept this issue frozen for over three years in "need to test" state. Are you going to test this or can the issue be closed?

**Comment by johngmyers** [comment]
Author isn't responding. I see little value in keeping this frozen.
/remove-lifecycle frozen
