### ISSUE TITLE
We should treat "too many LaunchConfigurations" as a hard-error

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2130]
When a user's AWS account has too many Launch Configurations (cf #2129), we just keep retrying

**Comment by justinsb** [comment]
Also check the retry behaviour here!  We were hitting AWS rate limits...

**Comment by tmeisel** [comment]
Just found this issue as I run into the same error. Since I'm using kops for the first time, it took me a moment to figure out that

`I0628 12:30:45.615054   47740 logging_retryer.go:59] Retryable error (Throttling: Rate exceeded
	status code: 400, request id: d881bcd7-5bec-11e7-83bc-fb6d303dd2f9) from autoscaling/CreateLaunchConfiguration - will retry after delay of 562ms`

actually means my account hit the launch configuration limit.

**Comment by zfy0701** [comment]
we have this issue as well, couldn't we delete the old launch configuration after creating the new one?

**Comment by chrislovecnm** [comment]
We are not garbage collecting launch config correctly. This is a known and open bug.

**Comment by rifelpet** [comment]
As of 1.10, Kops is now cleaning up old launch configurations so we can probably close this out
/close
