### ISSUE TITLE
Restrict IAM Roles resources

### ISSUE THREAD

**Issue by bfallik** [kubernetes/kops#2133]
This relates to https://github.com/kubernetes/kops/issues/1873 but it would also be nice to restrict the resources that the nodes can access via IAM. For example, the ec2 IAM master policy:
```
    {
      "Effect": "Allow",
      "Action": [
        "ec2:*"
      ],
      "Resource": [
        "*"
      ]
    }
```
gives the master nodes access to *any* ec2 resources, even those completely unrelated to Kubernetes. It seems like the master should, at most, only have access to other Kubernetes masters and nodes.

Similarly I would think that kubernetes only needs to modify load balancers that it created, so maybe those tagged "KubernetesCluster"?

I could potentially try and submit a patch for this if the idea is reasonable and the PR would be welcomed. But I'm not sure if I'm missing some reason why Kubernetes needs the wide access.

**Comment by chrislovecnm** [comment]
I am going to close this as a duplicate. https://github.com/kubernetes/kops/issues/1873 we have this open.  Please let me know if that issue is not covering this.
