### ISSUE TITLE
When using an existing VPC, enableDNSHostnames check doesn't happen

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#2135]
https://github.com/kubernetes/kops/blame/70fc4c4425fa8de481e5c0a987fa7c9f636f8769/docs/run_in_existing_vpc.md#L63

This isn't happening when an existing VPC is used, if you forget to change it on the VPC the cluster just silently fails to come up.

**Comment by yissachar** [comment]
We specifically [turned this off](https://github.com/kubernetes/kops/pull/1673) for existing VPC and Kubernetes versions later than 1.5, as this shouldn't be required anymore.

Can you add some additional info about your cluster?

**Comment by blakebarnett** [comment]
kops version: 1.5.3, stable channel
k8s version: 1.5.3

It's a private topology, with private DNS.  The cluster launched properly, DNS records were created, but logging into the nodes revealed resolution wasn't working via the AWS resolver at all.  Enabling DNS hostnames fixed it.

**Comment by yissachar** [comment]
If you are using your own DNS and not Amazon DNS, and your instances have resolvable hostnames, then you should not need to enable DNS hostnames. If you are using Amazon DNS, then you need to enable DNS hostnames.

I think this is mainly a docs issue.

**Comment by blakebarnett** [comment]
Agreed, it worked automatically before, but doesn't now.  It should probably just output a warning if it's not enabled and it's a private topology / private dns.
