### ISSUE TITLE
Option to disable overwriting ~/.kube/config changes on kops update

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#2136]
Kops conveniently exports the configuration for kubectl for the cluster when doing a `kops update cluster --yes`, but if you've made local changes it would be great if this was optional.

Something like `kops update cluster --no-kubecfg --yes` or something.

**Comment by kris-nova** [comment]
The logic was already built in, just the flag wasn't exposed. PR to expose the flag: https://github.com/kubernetes/kops/pull/2138

**Comment by blakebarnett** [comment]
Great! I thought I saw something about it.
