### ISSUE TITLE
kops can't assume roles in ~/.aws/config profiles by default

### ISSUE THREAD

**Issue by tiadobatima** [kubernetes/kops#2142]
Not sure this is a documentation issue, a small bug, or even a feature request:

By default, kops will not assume roles defined in profiles in *~/.aws/config*.
[Golang's AWS SDK](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/) says that by defining the environment variable AWS_SDK_LOAD_CONFIG, the sessions will be created with the ability to assume roles, set default regions.

I don't quite understand the reason Golang SDK devs decided to go this route, but folks used to CLI/boto will find the current behavior weird, and will likely file bugs or ask questions in Slack.

```
#### using a profile that the user assumes a role
# export AWS_PROFILE=subaccount-profile-with-role

# aws ec2 describe-availability-zones --output text
AVAILABILITYZONES       us-west-2       available       us-west-2a
AVAILABILITYZONES       us-west-2       available       us-west-2b
AVAILABILITYZONES       us-west-2       available       us-west-2c

# kops create -f /tmp/my-config --state --state s3://my-bucket/subfolder/kops   ## doesn't work
error: error populating configuration: Got an error while querying for valid regions (verify your AWS credentials?)

# export AWS_SDK_LOAD_CONFIG=1

# kops create -f /tmp/my-config --state --state s3://my-bucket/subfolder/kops  ## works!



#### using a profile that has access keys associated with the user
# export AWS_PROFILE=subaccount-profile-with-access-keys

# kops create -f /tmp/my-config --state --state s3://my-bucket/subfolder/kops   ## works!
````

**Comment by ahawkins** [comment]
I agree on the golang SDK's decision. It's out of line with other common software people use. I suggest `kops` exports this environment variable or updates internal config objects to set this value.

**Comment by qrevel** [comment]
/remove-lifecycle stale
agree with @ahawkins

**Comment by qrevel** [comment]
/remove-lifecycle stale
still not solved

**Comment by Skarzee** [comment]
I must agree on this, it's really frustrating and disjointed to work with environment variables when you are used to just using profiles. The AWS configuration in INI format supports this, it would be really nice to just define a profile within CLI. Please considering reopening.

**Comment by electroneumdevs** [comment]
please reopen, still having issues with this

**Comment by demisx** [comment]
Please reopen. We need to be able to use CLI profiles.

**Comment by szeitlin** [comment]
IIRC, I found a way to work around this, but I don't have it on my current laptop. I'll write myself a note to dig this up and post it here.

**Comment by demisx** [comment]
I am using this for now to avoid setting persistent env vars:

```ts
export AWS_SDK_LOAD_CONFIG=1 \
export AWS_PROFILE=dl-infra-stg; \
export ZONES=(terraform output -json availability_zones | jq -r '.|join(",")'); \
export NAME=(terraform output cluster_name); \
export KOPS_STATE_STORE=(terraform output state_store); \
kops create cluster \
    --master-zones $ZONES \
    --zones $ZONES \
    --topology private \
    --dns-zone (terraform output public_zone_id) \
    --networking calico \
    --vpc (terraform output vpc_id) \
    --target=terraform \
    --out=. \
    {$NAME}
```
