### ISSUE TITLE
Rolling-update with the validate feature conflicts with the cluster autoscaler

### ISSUE THREAD

**Issue by MrTrustor** [kubernetes/kops#2145]
If you are using the cluster-autoscaler, doing a ``kops rolling-update`` (with the ``DrainAndValidateRollingUpdate`` feature flag enabled) will fail.

One of the steps that kops goes through to validate the cluster is to check the number of nodes ([here](https://github.com/kubernetes/kops/blob/master/pkg/validation/validate_cluster.go#L185)). But the cluster autoscaler will add nodes during the operation to compensate for the one you are loosing. With 3 nodes, the timeline looks like this:

- kops drains node 1,
- cluster-autoscaler creates a new node to compensate the loss of resources,
- the autoscaling group recreates node 1,
- when both nodes are ready, we end up with 4 nodes,
- kops can't validate the cluster because it does not have the expected number of nodes.

I ended up disabling the cluster-autoscaler and terminating one of the 2 new instances during the rolling-update operation.

My first instinct on this issue would be to change the way that kops validates the cluster to check if we have _enough_ nodes, and not _just the right number_, but I am not sure of the side effects elsewhere in kops.

**Comment by chrislovecnm** [comment]
This may be fixed in head now.  We have the tweak that allows for more nodes in the validate code.  Let me know if you can test it in the next kops-1.6 release.

**Comment by chrislovecnm** [comment]
This should be fixed. Closing. Please reopen if needed
