### ISSUE TITLE
kops + digital ocean

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#2150]
Personally I think this would be big win, but I am wondering if anyone else has any interest in running kubernetes on Digital Ocean with `kops`?

I just want to get a feel for people interested to gauge how valuable this work would be. Cheers.

**Comment by kris-nova** [comment]
So after reaching out to a few people on Twitter on the manner, it looks like we have have a small amount of interested parties here. Thanks everyone for helping connect me!

I am going to reach out to the open source team at digital ocean and will follow up with more info as soon as I have it.

**Comment by voyalab** [comment]
+1

**Comment by kris-nova** [comment]
Looking at getting this into a future version of kops, but looking for volunteers to help code with me.

I can manage the DO account and give everyone access (they were nice enough to give us a budget, and I am happy to "eat" any remaining costs) but we just need to make sure we aren't throwing money away 😄 

If you are interested ping me and I will add you to the list, I have a really solid idea of everything that needs to be done, just looking for Go hackers to help code them. I can do it all myself too, but that might take a little longer 😉 

Cheers

**Comment by andrewsykim** [comment]
@kris-nova I've been doing some work on kops + GCE and have noticed that a lot of the kops code  assumes AWS. I would love to help refactor/generalize kops so it can be more pluggable with other cloud providers. 

This sounds like fun, I would be interested in helping in my free time :)

**Comment by chrislovecnm** [comment]
@andrewsykim I agree that we need to start refactoring into interfaces so we can start abstracting code paths.  It is going to be tricky :P

I need to take a look at what the vSphere folks did as well.

**Comment by andrewsykim** [comment]
I opened an umbrella issue re: better compatibility with cloud providers other than AWS: https://github.com/kubernetes/kops/issues/2646

**Comment by andrewsykim** [comment]
I have not forgotten about this, just haven't had much bandwidth lately :)

**Comment by xech3l0nx** [comment]
We are developing a cli for automated production ready k8s clusters provisioning and configuration 
‘kubedo ’ started the project yesterday and looking for contributors have a look at the dev branch and let me know. We will keep the project on because we at SNAPUP LABS LLC are DO customers. 
https://github.com/snapup-labs/kubedo

**Comment by wingyplus** [comment]
@andrewsykim I interesting in DO provider. Could you provide some information to me?

**Comment by andrewsykim** [comment]
@wingyplus sorry for the late reply! 

So far kops + digitalocean support does:
* creates volumes for etcd 
* creates droplets using the default user data
* creates DNS entries for apiservers 

What's left to do is:
* add spaces support for VFS backend 
* modify the default user data + nodeup to work with DigitalOcean
* Add DigitalOcean support to dns controller 

Happy to answer anymore questions you might have :).

**Comment by JorgeCeja** [comment]
Any updates on the current status? What is need to be production ready? I'll like to contribute, I just need more info on where the integration stands. Thanks!

**Comment by andrewsykim** [comment]
Hi @JorgeCeja! I expect that in the next release you should be able to stand up a working version of a kubernetes cluster. 

Some features that are missing are:
* support for multiple masters (currently only supports 1)
* support for multiple regions - this is a debatable feature since I think generally you should have 1 cluster per region anyways.
* rolling update support
* lots of testing :)

Happy to help you tackle any of those.

**Comment by andrewsykim** [comment]
For anyone interested, on kops 1.9 you should be able to build a working Kubernetes cluster on DigitalOcean with kops. More details here https://github.com/kubernetes/kops/blob/master/docs/tutorial/digitalocean.md#getting-started-with-kops-on-digitalocean

**Comment by JorgeCeja** [comment]
Awesome work! This made my day! I will initially help by testing it. I am ok with go, but if you have any resources or help on how to approach one of these problems, in general, it will be very helpful. From there I can go ahead and give them one of them a shot (I am looking into tacking support for multiple masters). Thanks!

**Comment by andrewsykim** [comment]
/remove-lifecycle rotten

(will close once a beta is out)
