### ISSUE TITLE
Cluster validation fails due to completed job in kube-system

### ISSUE THREAD

**Issue by thlacroix** [kubernetes/kops#2152]
When a pod from a job is in a "Completed" status in kube-system, the cluster validation fails during the rolling update of nodes with the "DrainAndValidateRollingUpdate" flag.

I guess this happens because the pod does not have the "Running" status, but I don't consider that as a reason to fail the validation.

In my case, the "configure-calico" job was the problem, deleting it fixed fixed the validation.

**Comment by ryane** [comment]
looks like this might be a dupe of #2137

**Comment by thlacroix** [comment]
Indeed, I'll close this one, thanks.
