### ISSUE TITLE
Make sure we expose Accelerators feature flag

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2159]
We need to support this for 1.6

From the changelog:

`--experimental-nvidia-gpus` flag is **replaced** by `Accelerators` alpha feature gate along with  support for multiple Nvidia GPUs.  ([#42116](https://github.com/kubernetes/kubernetes/pull/42116), [@vishh](https://github.com/vishh))`

**Comment by anurag** [comment]
Is there a workaround in the meantime?

**Comment by justinsb** [comment]
Do check out https://github.com/kubernetes/kops/pull/2298 which is starting to put the pieces together...

**Comment by anurag** [comment]
Just successfully tested this flag and GPU access on a p2.xlarge instance with `HEAD` on kops `master` and k8s 1.6.1. Thanks to @chrislovecnm for pointing out the need to build a custom `nodeup`.

**Comment by anurag** [comment]
I should add that I used a custom AMI with NVIDIA's driver pre-installed. But the hook looks like it could make everything simpler.
