### ISSUE TITLE
kube-dns not deployed on CoreOS cluster

### ISSUE THREAD

**Issue by trmiller** [kubernetes/kops#2170]
Testing out the experimental CoreOS support - not seeing kube-dns deployed.

```
kubectl get svc --all-namespaces | grep dns
kubectl get po --all-namespaces | grep dns
```

Both returning empty.   Also following the [dns testing instructions](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) looks to confirm that it's not there as well, as resolving kubernetes.default fails.

**Comment by chrislovecnm** [comment]
You actually may be missing another container as well :( dnscontroller ...  Can you provide and logs / more information?

**Comment by chrislovecnm** [comment]
This is working now, as I know we have coreos users. Closing. Plesss reopen if needed
