### ISSUE TITLE
Provide the ability to set AWS cloudConfig Options

### ISSUE THREAD

**Issue by waldman** [kubernetes/kops#2171]
Hi,

There are cases where, if using more than 50 external services there will the be need to set the following parameter on the `--cloud-config=<path>` file that is used by the kube-controller-manager:
`DisableSecurityGroupIngress: true`

I already have some ideas on where/how to set  it so I will probably try to open a PR in the next few days (unless there are already some way to set this that I'm unaware of :P )

Thanks a lot! :)

**Comment by chrislovecnm** [comment]
Closing
