### ISSUE TITLE
No option for elasticsearch logging

### ISSUE THREAD

**Issue by bregtcoenen** [kubernetes/kops#2174]
I am trying to figure out how to use elasticsearch logging on kops with the AWS provider.
`export KUBE_LOGGING_DESTINATION=elasticsearch` 
before running my kops cluster update does not work.

Creating my stack from scratch also does not seem to work when I have the ENV variable exported.
Is there any documentation available on how to accomplish this?

Thanks
Bregt

**Comment by Steniaz** [comment]
Kops does not yet support elasticsearch logging out of the box. An experimental addon has just been merged into master though: https://github.com/kubernetes/kops/pull/1305

**Comment by chrislovecnm** [comment]
Closing, please reopen if needed
