### ISSUE TITLE
Update Weave Net for Kubernetes 1.6

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kops#2180]
Pretty sure you need to update the [toleration](https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.weave/v1.9.3.yaml#L15) from an annotation to a field.

You may want the plugin to obey CNI spec 0.3.0, which is in the Weave Net 1.9.4 release.

Does Kops turn on RBAC?

**Comment by chrislovecnm** [comment]
We are working that out. We may need to implement both rbac and non-rbac. Kops office hours is this Friday, swing by ;)

**Comment by chrislovecnm** [comment]
closing this!
