### ISSUE TITLE
Cannot supply configuration file and certificates for webhook authentication

### ISSUE THREAD

**Issue by carpenterm** [kubernetes/kops#2194]
I'm looking to setup authentication using a remote webhook service. I have this working on a kubernetes-anywhere cluster and am looking to deploy the same thing using kops.

It looks like the flags are now supported as part of [this commit](https://github.com/kubernetes/kops/blob/58db07050fd0070830bed0369670c47bfff55d30/pkg/apis/kops/v1alpha2/componentconfig.go#L212-L215) by @sethpollack but I'm struggling to see how I can provide the yaml file required by the `--authentication-token-webhook-config-file` argument described [here](https://kubernetes.io/docs/admin/authentication/#webhook-token-authentication)

Is there any way of doing this today using kops that doesn't involve building a custom AMI each time I want to update the configuration or the certificates?

I'd also like to add a custom volume mount to the API server so that it can access my config files and certificates, as I would like to avoid putting the certs in a kops/k8s system directory if possible. Can I some how add this to the cluster spec?

**Comment by negz** [comment]
I'm running into the same issue today.

Seconding what (I think) you are suggesting. It would be great if we could specify additional configMap volumes to be used by the api-server. That way we could just throw any extra config in a configMap and expose it to the api server as a volume.

**Comment by justinsb** [comment]
We talked about this briefly on the slack channel:

> So configmap is absolutely the right way once we have a functional API.  The problem is that for the bootstrap components (API, etcd, kube-controller-manager, kube-scheduler) it's easy to get into chicken and egg problems, as you say.   I think we can put the config file into the kops cluster spec, effectively.  And then kops (technically nodeup) would create the file for you

So we would probably have an authorization section of the kube cluster spec:

e.g.

```
spec:
  authentication:
    custom:
      url: http://server
      certificate: <base64>
```

I'd rather not have the certificate in there, but if we need it we could do it

**Comment by zanhsieh** [comment]
Put the comment from @sethpollack in Slack channel to ease visitors search related syntax:  

```
spec:
  kubeAPIServer:
    authenticationTokenWebhookConfigFile: /path/to/file
```

**Comment by rajatjindal83** [comment]
@justinsb 

(first of all, thanks to you and all the awesome contributors for this awesome project).

we are able to start kubernetes api service with additional parameter for authenticationTokenWebhookConfigFile. and using kops-hook, we are able to drop the webhook.yaml file into the file system too.

The webhook.yaml file refers to the certificates which we do not want to add to the kops-hook.

one way we have been exploring is to make the http call to an external end point from the kops-hook to get certificate and place it on file system.

is there any better way to put the certs on the file system for consumption by API server

**Comment by rajatjindal83** [comment]
@sethpollack @zanhsieh @justinsb 

any recommendations?

**Comment by bhutkovskyysos** [comment]
Hi,

Was this issue ever resolved? How does KOPS generate `/etc/kubernetes/manifests/kube-apiserver.manifest` file? I am trying to specify: `authenticationTokenWebhookConfigFile: /etc/kubernetes/aws-iam-authenticator/kubeconfig.yaml`, in the cluster spec, which is shown in the cluster spec after update and kops logs but the manifest that gets generated still has the old default path:
`--authentication-token-webhook-config-file=/etc/kubernetes/authn.config`. 

I am using kops v1.12.1 and k8s v1.12.7.  

/reopen
