### ISSUE TITLE
Be able to create/import/export secrets as yaml 

### ISSUE THREAD

**Issue by PhilippeDupont** [kubernetes/kops#2195]
I would like to create a cluster the same way `kops create --ssh-public-key=<path-to-pub-key>` does using only yaml files (to version it in git).

It would be great if we could import/export secrets as yaml using something like :
- `kops create -f secrets.yaml` for import/creation
- `kops get secrets -o yaml` for export

cc @justinsb

**Comment by chrislovecnm** [comment]
We are talking about the same stuff over here https://github.com/kubernetes/kops/issues/1995

**Comment by mad01** [comment]
@chrislovecnm since we have the possibility create secrets directly from files in kubernetes don't you think it would also be okay to do it in kops?

**Comment by mad01** [comment]
@chrislovecnm can we close this? or is there anything more that we need to do so?

**Comment by chrislovecnm** [comment]
Closing :)
