### ISSUE TITLE
support for private subnets

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#220]
kops needs the capability to create subnets which are both public and private. This should do three things:

1) Create an ASG spread across the private subnets
2) Create an ASG on the public subnets (with EIPs ideally)
3) Label the instances distinctly between the ASGs (external / internal or similar)

(migrated from https://github.com/kubernetes/kube-deploy/issues/157)

**Comment by ProTip** [comment]
We need private subnets to meet our security obligations.

**Comment by ProTip** [comment]
@justinsb Is there something we can do to help expedite this? I can help with implementation if I had an idea of where to start. Might worth considering https://github.com/kubernetes/kops/issues/232 at the same time?

**Comment by billyshambrook** [comment]
Hey @justinsb, would you be able to expand on point 3 and what the labels would need to be for kubernetes to work?

I am happy to contribute with this feature.

**Comment by chrislovecnm** [comment]
@billyshambrook please reach out, we are having a planning meeting, and would love your help!!

@kris-nova How does this fold into https://github.com/kubernetes/kops/issues/428

**Comment by kris-nova** [comment]
Finished with #428
