### ISSUE TITLE
kops and kubernetes versions must match

### ISSUE THREAD

**Issue by arthurlm44** [kubernetes/kops#2229]
I attempted to upgrade a cluster from 1.5.3 to 1.6.0 via Kops without knowing that the Kubernetes and Kops versions need to be aligned.
I was unaware of this when upgrading and it caused a few issues for me.
Here's the proposed documentation change that would have prevented this issue in my case: https://github.com/kubernetes/kops/pull/2228

**Comment by chrislovecnm** [comment]
Closing as PR is merged
