### ISSUE TITLE
document necessary iam permissions

### ISSUE THREAD

**Issue by clofresh** [kubernetes/kops#223]
It would be nice to know which particular iam permissions the commands will need before running. Maybe even have a command that could export a minimal policy you can use.

**Comment by ProTip** [comment]
Further, kops creates IAM policies. It would be great if these roles could be provided into kops and allow it to pass them. 

It is extremely difficult(impossible?) to allow something access to IAM without creating loopholes that would allow it to acquire full access. https://github.com/kubernetes/kops/issues/226 may largely mitigate this risk in regards to keys going missing.

**Comment by chrislovecnm** [comment]
Hey all PRs are welcome!!!!  Please let us know if you are able to help out documenting this awesome tool!!!

**Comment by yissachar** [comment]
We have some [docs](https://github.com/kubernetes/kops/blob/master/docs/aws.md) on this now. Further discussion on minimizing the permissions is taking place in #1100.
