### ISSUE TITLE
Adding kubeAPIServer entry to spec doesn't cause a rolling update

### ISSUE THREAD

**Issue by apenney** [kubernetes/kops#2231]
I added:

```
kubeAPIServer:
    runtimeConfig:
      batch/v2alpha1: "true"
```

After doing an update and attempted rolling-upgrade I realized it believed it had no changes to make.  I used --force in the end, but this might be a trivial bugfix!

**Comment by KashifSaadat** [comment]
@apenney a fix was issued for this recently and merged into kops master (currently only available in the kops v1.8.0 alpha release). Can we close this issue?

FYI @chrislovecnm
