### ISSUE TITLE
Allow extra security groups

### ISSUE THREAD

**Issue by ProTip** [kubernetes/kops#224]
It would be great if we could apply extra security groups to the `InstanceGroups`. This would allow layering in access to other AWS resources such as RDS, elasticache, etc.

Applying these changes to an autoscale group would require a rolling update unless they are manually applied to running servers...

**Comment by chrislovecnm** [comment]
👍

**Comment by chrislovecnm** [comment]
We need to determine if we able to edit, create, update, delete sec groups.

**Comment by keglevich3** [comment]
+1

**Comment by ccp-ccollins** [comment]
Another use case: we run stateful pods that we expose via HostPort.  You might argue that we're bending the rules of what k8s is supposed to do, but it works well when set up manually.  With kops we have an extra manual step where we need to open up those ports on the node instances with application of another security group.

**Comment by tsupertramp** [comment]
I would like to prepare the pull request for this.

I thought of two parameters for create --add-sg-masters and --add-sg-nodes which allows to add extra security groups which will be attached to masters/nodes.

To allow vendrov's use case i would prepare a third command line parameter --skip-create-sg which  would skip creation/attaching of default security groups.

**Comment by stepanstipl** [comment]
It would be great if you can specify desired SG(s) as parameter of InstanceGroup, so that you can have different set of SGs per different InstanceGroup.

**Comment by justinsb** [comment]
I believe this is addressed by #1444 - please comment if not!

**Comment by chrislovecnm** [comment]
Closing - please reopen if needed

**Comment by Hermain** [comment]
What about creating additional security groups directly in kops? I use kafka to stream a lot of data from iot devices. The best way to receive that data is through host port as kafka takes care of load balancing itself.

It would be lovely to be able to define a portrange/port to be open on the InstanceGroup kafka-nodes

**Comment by bzuelke** [comment]
So this is in at the very least kops 1.11-beta, this would essentially solve this issue and in my testing in my sandbox cluster it works for all of the instance groups I tested on. We also have a split out of specific nodes that need specific SG's for each and this seemed to do the trick. https://github.com/kubernetes/kops/blob/master/docs/security_groups.md

The lifecycle override business I've not needed to do personally, but thought I'd chime in here.
