### ISSUE TITLE
Autoscaling for masters

### ISSUE THREAD

**Issue by DenKolesnik** [kubernetes/kops#2242]
When I increase master from 1 to 2 on each zone, running update cluster and rolling-update all looked like fine: new master was created and running. But:
 - kubectl get nodes show that only 3 masters in the cluster and allowed on api.k8sv1.example.com
 - etcd still has only 3 registered masters, and if one master goes down - the second master from this zone didn't connect.
- kops validate cluster show:
Validation Failed
Ready Master(s) 3 out of 6.
Ready Node(s) 1 out of 1.

 Looks like etcd settings for master making only on creation step for the new cluster and didn't change in autoscaling.

**Comment by pastjean** [comment]
Sadly you cant scale a cluster up by adding a node to the autoscaling group. The autoscaling group for masters is used to ensure there is always 1 machine machine up for that configuration in the event it crashes.

The way to do that is to create more "instanceGroup" of type "master".

Masters also have additional features that gets attached to them like EBS drive to store etcd data. The instance group name manages the link of the node and that ebs at boot time.

**Comment by RahulMahale** [comment]
> The way to do that is to create more "instanceGroup" of type "master".

@pastjean If I create a one new  master IG and bring that up, will that automatically be synced with cluster and etcd ?

**Comment by Globegitter** [comment]
I am just running into the same issue. We are looking at autoscaling for our test clusters to save money. For the nodes it is easy, but it would also be nice to have something for masters. For our use-case I could imagine some linking to the nodes. If there is only one node, then scale down to one master. If there are more than one node scale up to 3 masters in 3 AZs. As sometimes we want to simulate the prod infrastructure more closely.
