### ISSUE TITLE
Allow internal bastion ELB

### ISSUE THREAD

**Issue by prachetasp** [kubernetes/kops#2250]
I work in a very security-conscious environment where we access the VPC via a VPN. We would like to secure SSH access through a single bastion server. kops already has great support for adding and configuring the bastion server via an ASG. However, the ELB can only be internet-facing currently. I would like to add the ability to specify this ELB to be internal. I imagine it wouldn't be too difficult given the existing support for an internal API ELB.

**Comment by dmourati** [comment]
We have the same requirement for our deployment. We have direct connect and/or Transit VPC to connect from our on premises network to RFC 1918 address space for the VPCs. All our topologies are private. Currently, kops provisions ELBs in public IP address space. We would instead like to create the ELBs in the RFC 1918 address space currently allocated to the utility subnets.

I have done so manually and verified it works.

```
mbp-008767:~ dmourati$ host internal-spinnaker-internal-lb-906598698.us-west-2.elb.amazonaws.com
internal-spinnaker-internal-lb-906598698.us-west-2.elb.amazonaws.com has address 10.84.41.197
internal-spinnaker-internal-lb-906598698.us-west-2.elb.amazonaws.com has address 10.84.25.205
internal-spinnaker-internal-lb-906598698.us-west-2.elb.amazonaws.com has address 10.84.33.204
```

**Comment by chrislovecnm** [comment]
This is an enhancement that will be needed with private topology by me as well. Going to assign this to myself, but happy to guide anyone who wants to call contribute as well!!
