### ISSUE TITLE
kops blue-green-update

### ISSUE THREAD

**Issue by foobarto** [kubernetes/kops#2252]
I'd like to suggest a new way of doing cluster upgrades as an alternative to the rolling-update.

In `rolling-update` kops performs potentially dangerous set of operations which if something goes not as planned may leave the cluster in an unusable state with no clear way to undo the changes.

The proposed `blue-gree-update` command would instead create a completely new cluster (in same VPC, subnet, using same keys, etc) then recreate all namespaces, deployments, pods etc on the new cluster. And lastly reuse any persistent volumes/EBS, ELB and DNS entries - it would be great if this last part could be done as a separate step giving chance for manual validation that the new cluster is working properly.

This is just a high level concept right now but it would be a great alternative way to doing cluster upgrades in a safer manner as rolling back to previous version should be much easier.

**Comment by kenden** [comment]
"reuse any persistent volumes/EBS".
An EBS volume can only be attached to one EC2 instance, so the volume would have to be copied.

Depending of the size of the cluster, copying it could be pretty long and expensive. Kubernetes 1.6 supports up to 5000 nodes!

Anything that makes upgrading safer would be a plus though!

**Comment by mapdegree** [comment]
Excellent suggestion for the feature. Experienced issues in K8S upgrade using KOPS 1.8.4 to 1.9.9 upgrade. No response yet front he community, not much I can really learn from other users pain.
