### ISSUE TITLE
Unable to set ASG monitoring flag in clusterspec file.

### ISSUE THREAD

**Issue by argais** [kubernetes/kops#2254]
I was unable to find a way to enable ASG monitoring (for cloudwatch ASG metrics) in a cluster spec yaml file or cli flag.

I looked through the docs and /pkg/model/awsmodel/autoscalinggroup.go , I'm not well versed in Go so I might have missed it.

Is it possible right now (besides outputting to terraform and modifying that manually)? Or could be a feature for a next version?

**Comment by chrislovecnm** [comment]
This would be a new feature, if you are interested in taking it on please reach out on here or slack

**Comment by thomasjungblut** [comment]
hey @chrislovecnm, I'd like to work on this. Any suggestion where to start?

**Comment by chrislovecnm** [comment]
What change needs to occur with how we setup k8s?

**Comment by johanneswuerbach** [comment]
Assumably there should be a field/annotation within the instance group spec to toggle https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#AutoScaling.EnableMetricsCollection

**Comment by chrislovecnm** [comment]
Is there a harm in always enabling the service

**Comment by johanneswuerbach** [comment]
@chrislovecnm I think its mainly a minor cost increase due to the new cloudwatch metrics but shouldn’t cause anything else

**Comment by thomasjungblut** [comment]
can't this be feature flagged?

**Comment by chrislovecnm** [comment]
If we can verify that there is cost that would be awesome. If there is a cost then we need an api value, if not might as well enable by default.

**Comment by johanneswuerbach** [comment]
@chrislovecnm researching a bit it seems those metrics are actually free https://aws.amazon.com/about-aws/whats-new/2016/08/free-auto-scaling-group-metrics-with-graphs/ and could be opt-in by default.
