### ISSUE TITLE
Don't use the server keypair for signing service accounts

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2256]
We inherited this from kube-up but it isn't the best approach.

The problem is that changing it will likely break all our service account tokens.

**Comment by justinsb** [comment]
@liggitt suggested that "if you want to change the server key, and you don’t have a service account key, copy the server key to serviceaccount key"

Also we can have multiple authorized public keys I believe.

**Comment by liggitt** [comment]
> Also we can have multiple authorized public keys I believe.

controller manager takes a single signing key. api server can take multiple verifying keys.
