### ISSUE TITLE
error: cloudformation Member must have length less than or equal to 51200

### ISSUE THREAD

**Issue by kenden** [kubernetes/kops#2259]
I created a cloudformation template with:
```
kops create cluster \
    --zones eu-west-1a,eu-west-1b,eu-west-1c \
    --master-zones eu-west-1a,eu-west-1b,eu-west-1c \
    --name k8s.test.test.testqbi.example.net \
    --node-size t2.medium \
    --master-size t2.medium \
    --cloud aws \
    --cloud-labels "Owner=Me,Stack=K8s" \
    --networking calico \
    --target cloudformation \
    --state s3://cf-templates
```

When running the cloudformation stack generated by kops with:
```
$ aws cloudformation create-stack --capabilities CAPABILITY_NAMED_IAM --stack-name kubernetes-k8s-test-test-testqbi-example-net --template-body file://out/cloudformation/kubernetes.json

An error occurred (ValidationError) when calling the CreateStack operation: 1 validation error detected: Value '<the json cloudformation template is printed>' at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200
```

I saw that kube-aws had the issue and added output explaining how to work around this:
https://github.com/kubernetes-incubator/kube-aws/issues/38

After uploading the template to s3 and changing the command to the following, it works:
```
aws cloudformation create-stack --capabilities CAPABILITY_NAMED_IAM --stack-name kubernetes-k8s-test-test-testqbi-example-net --template-url https://s3-eu-west-1.amazonaws.com/cf-templates/kubernetes.json
```

Suggestion:
Check the size of the file in "out/cloudformation/kubernetes.json".

If it is bigger than 51200, 
- display an error message, 
- ask the user to add a param, for ex `--s3-uri` to write the template to S3
- output the proper command to type, with `--template-url` instead of `--template-body`

If it is bigger than 460,800,
- display an error message: the template is too big.

**Comment by mumoshu** [comment]
FYI kube-aws as of today uploads 3 types of stack templates - root, control-plane(=master in kops?), worker node pool(=instance pool in kops?) - to S3 and then utilizes nested stacks to glue them.
This seems to be working very well to work-around the cloudformation limit so far.
Relevant issues are https://github.com/kubernetes-incubator/kube-aws/pull/45 and https://github.com/kubernetes-incubator/kube-aws/pull/315

**Comment by chrislovecnm** [comment]
@kris-nova any ideas?
