### ISSUE TITLE
Route 53 Add-on with subdomain

### ISSUE THREAD

**Issue by Doron-offir** [kubernetes/kops#2264]
Hi Guys,

I am not sure if this is the place the ask this, if not, please point me at the right direction :).

I've created a k8s cluster in AWS using KOPS 1.5.3, works great.

The cluster I've created is in a seprated staging account, so the parent DNS zone, lets say EXAMPLE.COM is in one AWS account, and I've created a subdomain called STAGE.EXAMPLE.COM in the second AWS account, pointing the NS of it to an NS record in the parent DNS zone.

Now, I've installed the route 53 add-on, and tried to set an alias to an ELB according to the documents, let say - MYAPI.STAGE.EXAMPLE.COM
nothing happened.
When I checked the logs, I notice I got many 403, access denied errors, and from the logs it seems that the API call are been made to the parent route 53 account (EXAMPLE.COM instead of STAGE.EXAMPLE.COM), and not to one hosted at the staging account, to which I granted permissions.

Considering the topology I described above, should the add-on work as expected? I couldn't find any place to state the exact zone ID for the addon to interact with, and it seems it paste only the main zone, and ignore subdomains.

Thank you in advance! 
All of the best,

**Comment by a1dutch** [comment]
@Doron-offir you need to use v1.3.0 of route53-kubernetes, i have created #2269 which add the required version.

**Comment by Doron-offir** [comment]
Hi Andrew,

Thank you for your update, I've checked it, it seems to work now :)

I would like to ask, or point out, about another issue.
Now that the service seems to work, I've noticed that the addon logs is
repeating the same entries every log update.
See below, those entries continue endlessy, I would excpet it to notify
upon completion and be silence unutl next time...

I0404 18:27:19.519179       1 service_listener.go:163] Created dns record
set: domain=foobar.staging.foo.bar, zoneID=############

I0404 18:27:49.523091       1 service_listener.go:123] Found 2 DNS services
in all namespaces with selector "dns=route53"

I0404 18:27:49.523330       1 service_listener.go:142] Creating DNS for
data-api service: XXXXXXXXXXXXXX-XXXXXXXX.eu-west-1.elb.amazonaws.com ->
barfoo-api.staging.foo.bar

Any suggestions?
Thanks again and all of the best,

-Doron

**Comment by a1dutch** [comment]
Seems to be an open issue about this https://github.com/wearemolecule/route53-kubernetes/issues/41

**Comment by Doron-offir** [comment]
​I see, I'll follow it, thanks again!​

-Doron

**Comment by chrislovecnm** [comment]
closing ... please re-open if needed
