### ISSUE TITLE
error reading cluster configuration, error reading s3://name/domain/config: Could not retrieve location for AWS bucket

### ISSUE THREAD

**Issue by AnthonyWC** [kubernetes/kops#2265]
Is there some steps that I am missing or am I running into a bug?

```
kops version
Version 1.5.3 (git-46364f6)
```

```
#aws s3 mb s3://test_test_test_test
make_bucket: test_test_test_test

aws s3api list-buckets --query 'Buckets[].Name' | grep test_test_test_test
    "test_test_test_test", 

#kops create cluster --zones us-east-1a --name test.net -v 3 --state s3://test_test_test_test
I0402 20:48:04.178011   25878 s3context.go:143] Querying S3 for bucket location for test_test_test_test

error reading cluster configuration "test.net": error reading s3://test_test_test_test/test.net/config: Could not retrieve location for AWS bucket test_test_test_test
```

**Comment by prachetasp** [comment]
The code [here](https://github.com/kubernetes/kops/blob/1.5.3/util/pkg/vfs/s3context.go#L123-L163) gets the bucket location. As mentioned in the comments you need to be the bucket owner and if the S3 bucket is shared across accounts you must specify the region.

Seems the user executing kops will also need to have permissions to execute GetBucketLocation and EC2::DescribeRegions.

See https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html for more details on the request.

**Comment by AnthonyWC** [comment]
I created & listed the bucket prior to running 'kops create cluster'.  I actually just tried using go-sdk and was able to list the s3 bucket.

(I do have multiple aws profile; not sure if that makes any difference)

**Comment by prachetasp** [comment]
It does. Try using putting AWS_PROFILE before the command like AWS_PROFILE=xxx kops ...

**Comment by AnthonyWC** [comment]
I probably didn't word it correctly but I meant if have multiple profiles somehow mess up kops (seem unlikely) but I was already in the right profile.

**Comment by AnthonyWC** [comment]
Ok I figured it; solution is to explicitly export AWS_ACCESS_KEY_ID & AWS_ACCESS_KEY_ID.

(Since I have multiple profiles; I used export AWS_PROFILE for aws cli but it is not enough for kops)

**Comment by karunasoft** [comment]
> Ok I figured it; solution is to explicitly export AWS_ACCESS_KEY_ID & AWS_ACCESS_KEY_ID.
> 
> (Since I have multiple profiles; I used export AWS_PROFILE for aws cli but it is not enough for kops)

I used **aws configure** I then entered my AWS Access Key and Secret Access Key and voila, kops worked!
