### ISSUE TITLE
kubelet NetworkPluginDir hardcode causes kube-dns to fail

### ISSUE THREAD

**Issue by prachetasp** [kubernetes/kops#2267]
To reproduce: Use master branch of kops to boot a 1.5.x cluster in AWS with private network topology and private DNS (specifically 1.5.2 or 1.5.6).

I attempted to use the master branch of kops to boot a 1.5.x cluster but constantly got an error similar to:

```
Failed to "SetupNetwork" for pod
"kube-dns-xxx(xxx)"
using network plugins "cni": cni config unintialized; Skipping pod xxx
```

This would happen for the `kube-dns` and `kube-dns-autoscaler` pods as well as any added (I tried to add busybox).

Looking through the kubelet journalctl logs I noticed: `No valid networks found in /opt/cni/bin`.

I tracked that down to this code here: https://github.com/kubernetes/kubernetes/blob/v1.5.6/pkg/kubelet/network/cni/cni.go#L87-L115

Tracking the pluginDir back into kops I noticed this commit: https://github.com/kubernetes/kops/pull/2104/files#diff-ab83e0ac9b64394afcd89d05d8f4d0c6

specifically this line which hardcodes the --network-plugin-dir to `/opt/cni/bin`: https://github.com/justinsb/kops/blob/9e7c0506f8b79468288d0c5d5d9b8913ca53255d/nodeup/pkg/model/kubelet.go#L60

This is an issue because the network plugin configs are actually written to `/etc/cni/net.d` in most of the CNI installations (and the ones bundled with kops). Therefore the containers can't find them and fail to start.

Not sure what the original reason was for the change but it would be solvable by making `NetworkPluginDir` settable in the `KubeletConfigSpec` like here: https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha1/componentconfig.go#L170

Otherwise might be good to remove the hardcode so the default of `/etc/cni/net.d` can be set: https://github.com/kubernetes/kubernetes/blob/v1.5.2/pkg/kubelet/network/cni/cni.go#L38

Is kops intended to be backwards compatible for creating clusters with older versions of k8s?

**Comment by justinsb** [comment]
So I think this is just a bug I introduced.  I believe we should be using the cni-bin-dir and cni-conf-dir flags, but I'll verify that now.

We really need to get e2e running with CNI plugins.  I'm working towards it!

In general, kops 1.6 will be able to install 1.6, 1.5 and 1.4.  kops 1.5 _should_ be able to install 1.6, but it might not yet have full support.  We try to keep the master branch working at all times, but with the push to release kops 1.6 I think I've let some mistakes (like this one) creep in.  The release branches should be much more stable if you're able to use those.

Thanks for the excellent bug report!
