### ISSUE TITLE
Offer Architecture Diagrams

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#2268]
As it stands we don't offer any **visual** representation of what a user gets when they deploy certain architecture. After some feedback in slack about this, I think it would be meaningful to offer some technical diagrams of what a user can expect to get with certain "baseline" `kops` architecture. 

##### How do we version the diagrams, and what tool do we use?

I honestly have no idea what the best way to do this is. I don't know if there is a community standard, or a "kubernetes" way of drawing up diagrams. I use draw.io because it's easy and works with google docs.. but wondering what everyone else thinks?

Also `kops` will naturally grow and change. We will need to offer diagrmas that match the change, as well as keep old diagrams on hand for folks using the non-latest version of `kops`

##### How do we handle multiple clouds?

This is a big one. We have some familiar commands and flags that mean totally different things in different clouds. Do we approach diagrams from commands down? Or from the cloud up?

##### How do we keep them up to date?

We can't ask devs to add a diagram to each PR, but the folks making changes in architecture should be aware that diagrams can get stale. Obviously not a deal breaker, but a heads up for engineers writing core `kops` code.

##### Examples

I put together a small repo I use for speaking on `kops`. I have some diagrams there that might be useful, or at least a starting place. These are 100% okay to copy/paste/use in kops. I even think I have the original files floating around somewhere. If anyone wants them just hit me up.

https://github.com/kris-nova/kops-demo

![image](https://cloud.githubusercontent.com/assets/13757818/24599247/7cb1c7e8-180c-11e7-908e-dfa32d3b0c98.png)

**Comment by chrislovecnm** [comment]
@kris-nova do you have examples?  I am starting working on diagrams on Monday :)

**Comment by mstump** [comment]
@kris-nova @chrislovecnm in the diagram posted above why is the VPN bridging the instance groups? Wouldn't it also be a different subnet per AZ?

**Comment by mstump** [comment]
Also in the diagram above I think you would want to break out etcd as it's own tier across multiple AZs correct?

**Comment by chrislovecnm** [comment]
@mstump you looking at my diagram in lucid?

**Comment by chrislovecnm** [comment]
We have these now. Closing, as it appears solved. Please reopen if needed
