### ISSUE TITLE
Create gossip based discovery mechanism, you do not need DNS

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2272]
(Tracking issue)

The reliance on route53/DNS for discovery slows down bringup of a new cloud or bare metal, and also can make e2e testing more complicated.  We should merge the gossip-discovery mode, even if it just for e2e.

**Comment by chrislovecnm** [comment]
So this functionality is now implemented and will be released in 1.6. ... but @justinsb can we get a HOWTO documentation, please.

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/issues/172 closed because of this implementation.

**Comment by chrislovecnm** [comment]
Closing as this is a duplicate. Please reopen if needed
