### ISSUE TITLE
hack/verify-boilerplate.sh does not work on linux

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2275]
**Problem**

I am getting the following error on Linux (Centos with GNU bash, version 4.2.46)

```
sh -c hack/verify-boilerplate.sh
Boilerplate header is wrong for: /u01/clove/src/k8s.io/kops/federation/model/bindata.go
Boilerplate header is wrong for: /u01/clove/src/k8s.io/kops/upup/models/bindata.go
Execute hack/update-header.sh to update headers
make: *** [verify-boilerplate] Error 1
```

Both go files should be excluded by the hack script and they are not :(  

**Steps to recreate**
- run `make ci` on a Linux system

**Comment by justinsb** [comment]
Can you add an `echo TO_REMOVE=${TO_REMOVE[@]}` after the `TO_REMOVE=...`  line, and see what it says?

Also, what is your shell?  Does the problem go away if you use `bash -c hack/verify-boilerplate.sh` ?

**Comment by chrislovecnm** [comment]
Now I am getting

```
$ sh -c hack/verify-boilerplate.sh
hack/verify-boilerplate.sh: line 37: files_need_boilerplate[@]: unbound variable
```

OSX

**Comment by chrislovecnm** [comment]
This is fixed on debian at least
