### ISSUE TITLE
Deleting instancegroup and immediately recreating gives error

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#228]
If you:
- kops delete ig nodes
- kope create ig nodes
- kops update --yes --v=8

The following error is probable, I believe while the LaunchConfiguration is being deleted:

`error running task "autoscalingGroup/nodes.<domain>": autoscaling Group "nodes.<domain>" had no LaunchConfiguration`

**Comment by chrislovecnm** [comment]
Can we confirm this?
