### ISSUE TITLE
bug: calico installation failure due to lack of ENV variables

### ISSUE THREAD

**Issue by zytek** [kubernetes/kops#2287]
Related to https://github.com/projectcalico/cni-plugin/issues/284

Just provisioned cluster using kops 1.5.3 + kubernetes 1.5.6 and 1 out of 3 nodes had wrong config file. 
```
         "k8s_api_root": "https://:",
```

Can we solve that in kops somehow ? Upstream devs can make calico-install fail when envs are not set, but we should retry or do some other workaround.

**Comment by chrislovecnm** [comment]
@zytek which version of `kops`?  Updates are in master, we may have another release out this weekend, but no promises :)  Can you test with the alpha release, by downloading the release from Github?

**Comment by lokesh-shekar** [comment]
@chrislovecnm Is there a fix intended for this in upcoming kops release?

**Comment by chrislovecnm** [comment]
Need more information on how to recreate before we can address the problem.

**Comment by chrislovecnm** [comment]
Any updates on this? We have multiple calico users ;)
