### ISSUE TITLE
Improve etcd hardening in clustered setup

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#230]
Determine what improvements with our install process will allow us to follow the guidelines laid out here: https://coreos.com/etcd/docs/latest/security.html

@justinsb mentioned that we can probably improve some of the security with the HA installation of etcd

**Comment by chrislovecnm** [comment]
@JuJu227 did this get resolved?

**Comment by chrislovecnm** [comment]
Duplicate of https://github.com/kubernetes/kops/issues/230

**Comment by justinsb** [comment]
I think you mean #822 is a dup of this one.  I'm going to close in favor of 822, as 822 has more discussion.
