### ISSUE TITLE
Limitations of Security Groups for Service of type LoadBalancer (ELB)

### ISSUE THREAD

**Issue by foobarto** [kubernetes/kops#2300]
Currently when creating a Serice of type LoadBalancer an ELB is created and a Security Group Ingress rule is added to `node.<cluster domain>` Security Group allowing the ELB to have access to nodes.

The limit on amount of ingress rules in any Security Group is 50 and there's already three rules there to allow masters, nodes and SSH access. This limit can be increased to 250 maximum but there's also a limit on ingress rules per network interface on any EC2 instance - which is also 250. Meaning there can be up to 5 Security Groups per net interface or one with increased limit to 250. 

This also means that there can ever be up to 247 Services of type LoadBalancer on a Kubernetes cluster in AWS and most likely less if you have custom ingress rules there too, regardless how big the cluster is (ie. 5k nodes).

In a real life scenario it's very easy to imagine a cluster with more than 47 deployed services.

I'm not sure at this time of a suggestion for a better solution other than perhaps looking at Ingress?

**Comment by chrislovecnm** [comment]
This is more a k8s issue than kops. You also have various ingress options.

Can we close?

**Comment by foobarto** [comment]
I'd say ingress is the way to go. Sure, close it off.
