### ISSUE TITLE
Autoscaling of Nodes

### ISSUE THREAD

**Issue by fluidjeel** [kubernetes/kops#2306]
I tried the cluster autoscaler from the README section on my aws account. So it created a deployment and the instance got an IP 100.96.0.2 (looks like non AWS IP). I believe this happened at POD level based on the screenshot attached. 

However, is there a way to perform node level autoscaling and not at PODS.

![cluster](https://cloud.githubusercontent.com/assets/10943776/24775901/59ff76d6-1b3c-11e7-9f12-2a84a6221929.PNG)

**Comment by tuananh** [comment]
@fluidjeel cluster-autoscaler IS for scaling nodes. However, I believe you have to attach ASG IAM permisison  for it to make it works.

**Comment by fluidjeel** [comment]
@tuananh Well the IAM account from which KOPS is being triggered is an admin account and has the required permissions. 

I have a K8s cluster with 1 master and 3 workers. I performed cluster autoscaler deployment within the cluster. I haven't increased the load to notice the autoscale feature. But my concern how do i pin the Autoscaling policy to a specific node or the cluster.

**Comment by id0827502** [comment]
@fluidjeel I imagine the ASG policy would be defined in the cluster deployment. If you do: `kops edit cluster <cluster-name>` and have a look at the cluster config you should be able to spot something.
