### ISSUE TITLE
Cluster resource deletion code should be in its own package pkg/resources

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kops#2310]
Any objections to putting the cluster deletion code into `upup/pkg/fi` instead of `upup/pkg/kutil`? I see that it contradicts a bit since `fi` stands for "fast install" and we're actually uninstalling but the parent directory is `upup` which is already contradicting. My reasoning for doing this is because I'd like to [generalize the cluster deletion code for any cloud provider](https://github.com/kubernetes/kops/blob/master/upup/pkg/kutil/cluster_resources.go#L46-L61) and don't mind doing some extra work to get this code into the right package.

**Comment by andrewsykim** [comment]
cc @kris-nova @justinsb

**Comment by kris-nova** [comment]
I honestly think we should get the delete code into `/pkg/resources` to match the interface here https://github.com/kubernetes/kops/blob/master/upup/pkg/kutil/cluster_resources.go#L35

I am not a huge fan of the `/upup` directory, and an even less excited about anything that uses **util** in the name.

+1 to moving it, happy to talk about where :)

**Comment by andrewsykim** [comment]
Works for me! Hope to get a PR out soon :)

**Comment by chrislovecnm** [comment]
Closing this

**Comment by andrewsykim** [comment]
related: https://github.com/kubernetes/kops/issues/2646
