### ISSUE TITLE
Failing to build a new cluster using Centos/ default ubuntu AMI in AWS

### ISSUE THREAD

**Issue by UlaganathanNamachivayam** [kubernetes/kops#2312]
Hi,
I am trying to bring up a cluster using kops by specifying a centos / default ubuntu image both in an existing VPC or by creating a new VPC. But kops  is failing now which was working a few days before.

After debugging the master i can clearly see kubeapi server & etcd cluster didn't started.

Errors are something like the below one.

apiserver received an error that is not an unversioned.Status: client: etcd member http://127.0.0.1:4001 has no leader

network is unreachable error in etcd logs.

Any help is much appreciated.

**Comment by UlaganathanNamachivayam** [comment]
Also would like to update this is happening only with respect to version 1.5.2 and i can bring up the cluster with the prior version 1.5.1. Strange was there any recent change to 1.5.2 docker images which is causing this issue.!

**Comment by chrislovecnm** [comment]
What was the resolution?

**Comment by chrislovecnm** [comment]
Closing, as it appears solved. Please reopen if needed
