### ISSUE TITLE
Follow up issues for ELK addon

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2313]
Follow up for https://github.com/kubernetes/kops/pull/1305

- [ ] Consider more pods
- [ ] Use elasticsearch operator?
- [ ] Use Curator or CronJob to clean up storage
    - [ ] https://github.com/Skillshare/kubernetes-efk/blob/master/configs/elasticsearch.yml#L94
    - [ ] https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-curator.yaml

- [ ] See also:
    - [ ] https://github.com/samsung-cnct/k2-charts/tree/master/elasticsearch
    - [ ] https://github.com/jetstack/elasticsearch-pet
    - [ ] https://github.com/kubernetes/charts

**Comment by chrislovecnm** [comment]
cc: @mstump 

Matt who do you want me to tag on issues like this, where Vorstella can assist?

**Comment by chrislovecnm** [comment]
> Consider more pods

We need to determine what a recommended starting point is.  I think with the default shard and replica setup we need a min of 3 masters.

**Comment by stevenpall** [comment]
Can anyone speak to what would need to be done to expose the Kibana service? I tried setting `type: LoadBalancer` to the `kibana-logging` service and then hitting http://<ELB>:5601 from which I got:
```
{"statusCode":404,"error":"Not Found"}
```
Is there something else that needs to be done?

**Comment by chrislovecnm** [comment]
@stevenpall I believe you need to make this an ELB 

https://github.com/kubernetes/kops/pull/1305/files#diff-bf860510903250a71687764c780c99aaR168

Or use kubectl proxy to get to the port.

I have not done it myself, but if I am reading the service correctly, that is where you want to tweak it.

**Comment by Steniaz** [comment]
A standard index in elasticsearch is created with 5 shards and a replication factor of 2. So If you use 3 nodes that means for an index with replication factor 2 that you can lose one node and the cluster will still work. So starting with 3 masters is a good starting point.

**Comment by jiuchongxiao** [comment]
@chrislovecnm  did you had soled it?
