### ISSUE TITLE
Running `kops update` without `--yes` should never make changes to cluster.spec

### ISSUE THREAD

**Issue by jaygorrell** [kubernetes/kops#2319]
We should not make any changes to the cluster.spec in S3 from running `kops update` without `--yes` provided.

In a common scenario, running a `kops update --target terraform` usually means changes will be applied later and externally by Terraform. This means that making immediate changes to the spec can have breaking consequences when, for example, #1708 altered a field name that would prevent new nodes from being able to discover the manifest location. 

This occurs when `kops update` is run (modifying the cluster spec) but Terraform has not yet been run to upgrade the userdata scripts. In order to truly resolve this, support should be added for exporting the cluster spec file to Terraform using the s3_bucket_object resource. 

https://www.terraform.io/docs/providers/aws/r/s3_bucket_object.html

This issue partially relates to #2318.

**Comment by foobarto** [comment]
I've bumped into this recently as well. While preparing to add another instance group I've ran `kops update --target cloudformation` and noticed that this resulted in `dns-controller` to be upgraded from `1.5.2` to `1.6.1`. Fortunately this didn't affect the cluster negatively but there should be more care to not make changes to the cluster like that.

**Comment by denniswebb** [comment]
/reopen
Just hit this again when changing to `CoreDNS`. Kops was ran with `--target terraform` and did not include a `--yes` flag, yet it updated something that triggered an immediate deployment of CoreDNS to my cluster.
I would've expected it to require `--yes` to do that.
