### ISSUE TITLE
Support for existing subnets and route tables on AWS

### ISSUE THREAD

**Issue by ProTip** [kubernetes/kops#232]
For a simple setup it may be suitable for kops/kubernetes to setup subnets and route tables. More complicated setups may require custom routes, ingress/egress rules, etc

Support for private subnets will require specifying a custom default route. We use the managed GW service now but many will be using NAT boxes, direct connects, VPN's, etc.

In any case it may be desirable, and certainly is in our case, to have the all VPC networking managed in the same place.

**Comment by kevin-cantwell** [comment]
It would be greatly improve our likelihood of adopting kubernetes if we could create a cluster in existing subnets. Not being able to specify existing subnets in a VPC means that our kubernetes cluster is completely cut off from existing infrastructure and the only path for adoption is a big-bang switch from not using it anywhere to using it _everywhere_, which is a risky enough path to cause us not to adopt k8s at all.

**Comment by chrislovecnm** [comment]
@kris-nova assigning this to you :)  How does this fold into our new networking stuff.  I am not sure if it does, or it is more a networking plugin module??

**Comment by yissachar** [comment]
This is actually supported already, see https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md#running-in-a-shared-subnet

**Comment by robinpercy** [comment]
@yissachar Those docs state that shared subnets are only supported when external networking is used. Today I tried spinning up a few clusters using shared subnets with default (kubenet) networking. The problem was that the Routing Table created and populated by kops was not associated with the shared subnet.

**Comment by chrislovecnm** [comment]
/assign

This will be supported by tweaking phases. And may be supported now with labels

**Comment by joelittlejohn** [comment]
@chrislovecnm could you elaborate on what you mean by, "may be supported now with labels"? Thanks!

**Comment by chrislovecnm** [comment]
@joelittlejohn we have support for existing subnets, and vpc.  It is documented here: https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md

We do not have support yet for not having an IGW, and I have a PR in for supporting alternative egress solutions.

**Comment by khanhtruong** [comment]
> @joelittlejohn we have support for existing subnets, and vpc. It is documented here: https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md
> 

It supports existing VPCs but looks like it's trying to carve out new subnets or something... I got error following the example there: error populating configuration: could not find any non-overlapping CIDRs in parent NetworkCIDR; cannot automatically assign CIDR to subnet

**Comment by Ralnoc** [comment]
That documentation is either wrong for shared subnets or the arguments for shared subnets are broken. If you attempt to specify just `--subnets` it fails saying you must specify the VPC. But if you specify the VPC, it tries to use the subnets from `--subnets` and also hack in it's own subnets and the process fails because you can't specify both specified subnets and unspecified ones.

**Comment by opensean** [comment]
In the documentation for shared subnets (https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md#shared-subnets), it is unclear to me what is meant by "Doing so is not recommended unless you are using external networking".  Do CNI providers such as Calico classify as external networking? Or is it a reference to the line in the networking documentation "external networking is done via a Daemonset. This is used in some custom implementations." found here https://github.com/kubernetes/kops/blob/master/docs/networking.md?

**Comment by johngmyers** [comment]
We create subnets, etc. externally from kops so we can divide the IP space more efficiently. Works fine with Cilium.

From 200d7e20e6839b6738f1f8a5c259a6798ea59c09 I suspect that "external networking" means "something other than Classic".
