### ISSUE TITLE
kops-1.6.0-alpha.1 + K8s 1.6.0 Private Topology(Weave or Flannel) Not Viable Cluster

### ISSUE THREAD

**Issue by bobhenkel** [kubernetes/kops#2320]
I'm spinning up a cluster with private topology and my masters are never going to ready state and the worker nodes never join the cluster.  This works fine with kops 1.5.3 with a 1.5 K8s cluster.

I did get this to work when using a public topology though with kops-1.6.0-alpha.1 + K8s 1.6.0 + weave, didn't try other networking CNIs.

I spun up a cluster with this:

kops-1.6.0-alpha.1 create cluster \
    --channel alpha \
    --kubernetes-version 1.6.0 \
    --ssh-public-key ~/.ssh/kops-alpha-1-6.pub \
    --node-count 3 \
    --zones us-east-1c,us-east-1d,us-east-1e \
    --master-zones us-east-1c,us-east-1d,us-east-1e \
    --dns-zone kops-alpha-1-6.xyz.io \
    --node-size m4.large \
    --master-size m4.large \
    --topology private \
    --networking weave \
    --bastion \
    --state s3://xyz-kops-state-store \
    --name kops-alpha-1-6.xyz.io

kops validate cluster:
Validating cluster kops-alpha-1-6.xyz.io

INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
bastions		Bastion	t2.micro	1	1	utility-us-east-1c,utility-us-east-1d,utility-us-east-1e
master-us-east-1c	Master	m4.large	1	1	us-east-1c
master-us-east-1d	Master	m4.large	1	1	us-east-1d
master-us-east-1e	Master	m4.large	1	1	us-east-1e
nodes			Node	m4.large	3	3	us-east-1c,us-east-1d,us-east-1e

NODE STATUS
NAME				ROLE	READY
ip-172-20-58-182.ec2.internal	master	False
ip-172-20-78-168.ec2.internal	master	False
ip-172-20-96-147.ec2.internal	master	False

Validation Failed
Ready Master(s) 0 out of 3.
Ready Node(s) 0 out of 3.

your masters are NOT ready kops-alpha-1-6.xyz.io

kubectl get nodes:
NAME                            STATUS            AGE       VERSION
ip-172-20-58-182.ec2.internal   NotReady,master   26m       v1.6.0
ip-172-20-78-168.ec2.internal   NotReady,master   26m       v1.6.0
ip-172-20-96-147.ec2.internal   NotReady,master   25m       v1.6.0

Thanks
Bob

**Comment by keiths-osc** [comment]
I get the same result when creating a private topology cluster using weave networking with kops 1.6.0-alpha.1 and the alpha channel (Kuberentes 1.6.0).

**Comment by keiths-osc** [comment]
I just tried the same test again with kops 1.6.0-alpha.2 and the cluster appears to have come up normally.

**Comment by bobhenkel** [comment]
I just tried with kops-1.6.0-alpha.2 and the cluster validation returns back with cluster is ready.
