### ISSUE TITLE
Support for DNS prefixing

### ISSUE THREAD

**Issue by ProTip** [kubernetes/kops#233]
We use valid wildcard SSL certificates for our environments and apps; one for production and one for everything else. We prefix the DNS record with the environment:

```
staging-my-app.mydomain.com
bobs-my-app.mydomain.com
```

I would like the ability to do the same with any records created by kops. Using the api as an example instead of:

```
api.kubernetes.mydomain.com
```

We would have:

```
kubernetes-api.mydomain.com
```

This would allow us to utilize the few wildcard SSL certificates we have across many different environments/clusters.

**Comment by justinsb** [comment]
This (and custom certificates in general) isn't going to make kops 1.5.0 I'm afraid, but I'm marking it as a priority for 1.5.1

**Comment by justinsb** [comment]
Although if you have a throwaway cluster,  I _think_ if you `kops edit cluster` and change 

`masterPublicName: api.k8s.example.com` to something else, it should work.

Mostly a note-to-self unless someone is brave enough to try it!

**Comment by justinsb** [comment]
Just tested it - it does work if you do it _before_ the first `kops update`.

i.e.

`kops create cluster`
`kops edit cluster` (change masterPublicName)
`kops update cluster --yes`

However, I do think that the current security settings of kubernetes won't let you insert an SSL-terminating load-balancer in between.  We'll have to work on that in 1.5.1

**Comment by chrislovecnm** [comment]
Closing as this works
