### ISSUE TITLE
Terminate API TLS with an ELB

### ISSUE THREAD

**Issue by ProTip** [kubernetes/kops#234]
It would be great if we could allow the API's TLS to be terminated by an ELB. This would allow us to reuse certificates we have and avoid distributing the certs/keys around to the nodes. It's likely we would want to be going through an ELB when everything is deployed into private subnets as well.

**Comment by justinsb** [comment]
I'm pretty sure we use client certificates and ELB doesn't support them.  But I'll check!

**Comment by ProTip** [comment]
It wouldn't. I guess I was just not aware of how authentication and encryption were handled.

If token or basic auth were used would we need TLS termination?

**Comment by lattwood** [comment]
Could do it in TCP mode instead of actually terminating things.

**Comment by zytek** [comment]
Does this relate to https://github.com/kubernetes/kops/issues/834 ?

**Comment by justinsb** [comment]
We now have ELB support for the API (and some refinements in #1268).

Moving this particular issue (TLS offload / custom certs) to 1.5.1 though.

**Comment by blakebarnett** [comment]
Is this actually needed?  We do this by simply creating a separate "External" service record with a cert via the annotation in TCP mode and let dns-controller create the DNS for it.
