### ISSUE TITLE
dns-controller failing in kops 1.5.3

### ISSUE THREAD

**Issue by mikelorant** [kubernetes/kops#2347]
Getting the following panic with the dns-controller tries to update with kops 1.5.3.

```
I0412 01:48:12.977925       1 dnscontroller.go:283] applying DNS changeset for zone ffxblue.com.au.::ZX6G0BU7RWU1R
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c719d]

goroutine 35 [running]:
panic(0x14337e0, 0xc420018040)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kops/vendor/k8s.io/kubernetes/federation/pkg/dnsprovider/providers/aws/route53.(*ResourceRecordSet).Ttl(0xc42039efa0, 0xc4202fd148)
    <autogenerated>:12 +0x4d
k8s.io/kops/vendor/k8s.io/kubernetes/federation/pkg/dnsprovider/providers/aws/route53.buildChange(0x15f28cf, 0x6, 0x1e661e0, 0xc42039efa0, 0x9)
    /go/src/k8s.io/kops/vendor/k8s.io/kubernetes/federation/pkg/dnsprovider/providers/aws/route53/rrchangeset.go:53 +0x152
k8s.io/kops/vendor/k8s.io/kubernetes/federation/pkg/dnsprovider/providers/aws/route53.(*ResourceRecordChangeset).Apply(0xc420701640, 0x1616190, 0x22)
    /go/src/k8s.io/kops/vendor/k8s.io/kubernetes/federation/pkg/dnsprovider/providers/aws/route53/rrchangeset.go:72 +0xaf
k8s.io/kops/dns-controller/pkg/dns.(*DNSController).runOnce(0xc4200850e0, 0x0, 0x0)
    /go/src/k8s.io/kops/dns-controller/pkg/dns/dnscontroller.go:284 +0x144d
k8s.io/kops/dns-controller/pkg/dns.(*DNSController).runWatcher(0xc4200850e0, 0xc42007bb00)
    /go/src/k8s.io/kops/dns-controller/pkg/dns/dnscontroller.go:111 +0x37
created by k8s.io/kops/dns-controller/pkg/dns.(*DNSController).Run
    /go/src/k8s.io/kops/dns-controller/pkg/dns/dnscontroller.go:103 +0x9a
```

**Comment by justinsb** [comment]
So there's an upstream issue which I've sent a PR in for.

I think you have a record without a TTL value.  It seems that ALIAS records will have nil TTL. 

I think what could be happening is that you're replacing / updating an ALIAS record?  If so a workaround while we work the PR through the process might be to simply delete the ALIAS record, if you know what it is.

Otherwise I'll do a dns-controller build off a forked version of dnsprovider with this PR.

**Comment by ketzacoatl** [comment]
This is a problem, in particular, if you run the `route53-mapper`, and then run `dns-controller` without the `--watch-ingress=false` cli flag. EG, if you have run, or are running `route53-mapper`, read up on `--watch-ingress=false` and consider whether you want to use it (depends on whether or not you want to use `dns-controller` _and_ `route53-mapper` or not). I believe `kops` have changed their use of this flag between 1.6.2 and 1.6.4 or so, though I'm not 100% sure about that.

**Comment by ketzacoatl** [comment]
For anyone who stumbles on this later, see https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#externaldns for some helpful info..

**Comment by chrislovecnm** [comment]
Can we close?
