### ISSUE TITLE
Changing min/max autoscaling counts for nodes?

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kops#2357]
I just followed the tutorial at https://github.com/kubernetes/kops/blob/master/docs/aws.md to setup a cluster. Everything seemed to work find but I now want to change the size of my autoscaling group for my k8s nodes. I tried `kops edit cluster` but there's nothing about auto scaling or node counts. There's something about node count [here](https://github.com/kubernetes/kops/blob/master/docs/advanced_create.md) but when I run that command it's telling me:

```bash
$ kops create cluster --node-count 3 $NAME

cluster "staging.mydomain.com" already exists; use 'kops update cluster' to apply changes
```

I then tried:

```bash
$ kops update cluster --node-count 3 $NAME
Error: unknown flag: --node-count
Usage:
  kops update cluster [flags]
...
```

I also tried `nodeCount: 3` in `kops edit cluster` under the `spec` key.

My question would be: how do I edit my cluster config to change the min/max autoscaling values? How would I have found this information by myself without asking here? Is there any documentation aside from that tutorial and the `docs/` directory?

**Comment by olalonde** [comment]
I just found the [relevant documentation](https://github.com/kubernetes/kops/blob/master/docs/aws.md):

```bash
 kops edit ig nodes 
```

I'm going to leave this open and suggest that a link be added under "What's next" in the AWS tutorial because it wasn't easy to find.

**Comment by andyp1per** [comment]
This is quite an irritating bug. WIthout editing this configuration you cannot actually use cluster autoscaling on AWS, you get the error:
E0612 15:39:41.297563       1 static_autoscaler.go:222] Failed to scale up: failed to increase node group size: ValidationError: New SetDesiredCapacity value 3 is above max value 2 for the AutoScalingGroup.
But figuring out how to change this, or indeed that this is the problem is quite hard. 
Any chance some documentation can be added? I do not see any reference to `kops edit ig nodes` in the above link.

**Comment by nnvema** [comment]
Once KOPS is installed, there is an add-on need to be deployed on the cops cluster for the autoscaling.  This will handle the AWS autoscaling of nodes. 
https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler

**Comment by andyp1per** [comment]
My comment is in relation to using this plugin, so unless a bug has been fixed the problem still stands.

**Comment by kachkaev** [comment]
@nnvema could you please paste your commands here? I'm not sure if your link is applicable to AWS or GKE.

**Comment by ryanlevell** [comment]
Those values also tripped me up. `GROUP_NAME` is the name of the autoscaling group in AWS. `SSL_CERT_PATH` I left as-is and it seems fine, I think.
