### ISSUE TITLE
Keeping cluster state in git instead of S3?

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kops#2358]
Is it possible to tell `kops` not to use s3 for cluster state? I would instead like to keep the state in files in a git repository.

**Comment by michaelajr** [comment]
You can write the cluster files in yaml and then use `kops create -f` to create the cluster. Changes to the yaml can be applied by using `kops replace -f`. This will allow you to keep your cluster code in git.

**Comment by michaelajr** [comment]
To seed your repo - you can get your current cluster yaml using `kops get cluster CLUSTER_NAME -o yaml`. You can do the same with your instance groups.

**Comment by chrislovecnm** [comment]
It is not possible at this time to point the state store at git. I have talked about this in the past. As mentioned previously you can do version control for the server using yaml.

**Comment by olalonde** [comment]
@michaelajr is there a way to get a `kops appy -f` that is either creates or updates?

**Comment by michaelajr** [comment]
@olalonde you can use `kops replace -f` for an update, I believe?

**Comment by Globegitter** [comment]
I think this is an interesting topic and would be nice to have kops support git. As a lot of people already store all they kubernetes yaml files in git it would imo add to review-ability of changes to support git as a state store.

I tested the way mentioned above, but that only gives the cluster yaml and not the all the other yamls. It does seem like it would be quite a lot of effort having to manage all files manually this way.
