### ISSUE TITLE
Using cloudflare instead of Amazon route 53

### ISSUE THREAD

**Issue by cheburakshu** [kubernetes/kops#2363]
I am trying to get Kubernetes on AWS free tier. I want to use Cloudflare for DNS and not Amazon route 53, since route 53 isn't free. Can kops support it? 

Does the kops process have hard dependency on Amazon S3 bucket and Amazon Rotute 53?

That is what I inferred from the installation guide. Pls let me know.

**Comment by neverfox** [comment]
From what I can tell, yes you can, but you would still need a hosted zone in Route 53 and put the NS values in Cloudflare.
