### ISSUE TITLE
Wrong SSH username using CentOS AMI

### ISSUE THREAD

**Issue by Cisneiros** [kubernetes/kops#2367]
If I create a Cluster using the CentOS AMI, when I apply the `update`, the final output of the command is:

```
Cluster is starting.  It should be ready in a few minutes.

Suggestions:
 * validate cluster: kops validate cluster
 * list nodes: kubectl get nodes --show-labels
 * ssh to the bastion: ssh -i ~/.ssh/id_rsa admin@bastion.<my cluster domain>
 * read about installing addons: https://github.com/kubernetes/kops/blob/master/docs/addons.md
```

But if I try to SSH to my bastion, it won't accept my SSH key. It will prompt me for a password instead. After sometime wondering what could be wrong, I remembered the default CentOS user is `centos`. SSHing with `ssh -i ~/.ssh/id_rsa centos@bastion.<my cluster domain>` works like a charm.

Taking a look at https://github.com/kubernetes/kops/blob/1cba0bd27f6ac845125262a931551f0d1004b5fd/cmd/kops/update_cluster.go#L269 one can see it `admin` is baked into the template string, so it does not consider what AMI you're using.

Not sure if this it is feasible to fix this, but at least a warning somewhere that the username might not be `admin` would be nice.

**Comment by chrislovecnm** [comment]
Well hrmmmm. Interesting. We could do a lookup on the ami, but I wonder if the os is actually there.

**Comment by mad01** [comment]
This is the case if you are using coreOS to. The username is admin and should be `core`

**Comment by chrislovecnm** [comment]
We have a kops output that the username is Debian specific. Would be happy for someone to take this on, but we need to figure out how to move this into probably apply cloud. We could have multiple different usernames per instance group as well. Nothing is stopping a user from running Debian masters with centos nodes.

**Comment by chrislovecnm** [comment]
We provide ux feedback for this, now closing

**Comment by jeremyjh** [comment]
On debian stretch `admin` won't work, the account is `root`.
