### ISSUE TITLE
Support 3rd party S3 compatible storage applications for Kops state store

### ISSUE THREAD

**Issue by luomiao** [kubernetes/kops#2368]
Current Kops supports AWS S3 service only.
If the users want to use 3rd party s3 compatible storage application services such as [Minio](https://github.com/minio/minio) or [Scality S3 Server](https://github.com/scality/S3), the users cannot set their own S3 endpoint.

Proposed solution:
Add "S3_ENDPOINT" environment variable for users to specify the endpoint of S3-compatible storage service; Add "S3_ACCESS_KEY_ID" and "S3_SECRET_ACCESS_KEY" for the authentication credentials of the S3-compatible storage service.

Example:
1. Starts a Minio server at IP address [minio_server_ip] at port number [endpoint_port] with access key ID [access_key_id] and secret access key [secret_access_key]
2. Create a bucket with Minio server
3. Set three new environment variables:
```
export S3_ENDPOINT=http://[minio_server_ip]:[endpoint_port]
export S3_ACCESS_KEY_ID= [access_key_id]
export S3_SECRET_ACCESS_KEY=[secret_access_key]
```
4. Start Kubernetes cluster with kops create and kops apply commands.

**Comment by robinpercy** [comment]
@justinsb @geojaz looks like this one can be closed.

**Comment by luomiao** [comment]
@robinpercy Thanks for reminding. This can be closed.
