### ISSUE TITLE
AWS EBS Volumes are untagged

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/kops#2371]
`1.5.x` does not tag EBS volumes with appropriate tags. Tagging EBS volumes would make it easier to work with cloudwatch metrics and other collection systems. They should be tagged with the same tags as the EC2 instances themselves.

**Comment by gauravarora** [comment]
This would really help to manage cost reports also.

**Comment by chrislovecnm** [comment]
With asgs we are not able to tag all of the volumes. You can use lambda functions if needed. This is a duplicate issue as well. Closing
