### ISSUE TITLE
Easy way to issue new master cert?

### ISSUE THREAD

**Issue by deitch** [kubernetes/kops#2375]
Is there an easy way to issue a new master cert? The default expiry must be a few months, cert expired last week. Is there any easier way than:

1. Download the CA key and cert and master key and cert from S3
2. Create a new CSR, careful to not mess up the CN
3. Sign the new cert
4. Upload the files back to S3

And do the filenames need to be identical to the long string of digits there now?

**Comment by kenden** [comment]
Related: https://github.com/kubernetes/kops/issues/1020
