### ISSUE TITLE
Add --kubeconfig flag to `kops export kubecfg`, to set the location of the kubeconfig file to create

### ISSUE THREAD

**Issue by kenden** [kubernetes/kops#2378]
Without setting environment variable `KUBECONFIG`,  
`kops export kubecfg` does not allow to export to a different file than ~/.kube/config

Please add a parameter `--kubeconfig` to set the location of the kubeconfig file to create.

`--kubeconfig` should take priority over the environment variable `KUBECONFIG` if both are set.
And if none are set, the default location should be `~/.kube/config`.

## Example usage

```
$ kops export kubecfg --name k8s.test.eu-west-1.aws.redacted.net --state s3://k8s/kops/  --kubeconfig $HOME/test-kubeconfig.yaml
# ---> creates a file kubeconfig at the location $HOME/test-kubeconfig.yaml
```

## Current workaround
When setting the environment variable `KUBECONFIG`, it is possible to set the location of the config file to be created.
```
$ export KUBECONFIG=$HOME/test-kubeconfig.yaml
$ kops export kubecfg --name k8s.test.eu-west-1.aws.redacted.net --state s3://k8s/kops/
$ cat $HOME/test-kubeconfig.yaml
apiVersion: v1
clusters:
- cluster:
...
```

Related to https://github.com/kubernetes/kops/issues/165 and https://github.com/kubernetes/kops/issues/1676

**Comment by chrislovecnm** [comment]
As far as I understand this is as designed and models kubectl. Would more documentation help, or do we have a flag that is not working??

**Comment by chrislovecnm** [comment]
Oh ... --config is actually not for kubeconfig. It is for the viper config file config... we need to fix the help section on that.

**Comment by kenden** [comment]
@chrislovecnm Thanks!
kubectl has the parameters `--kubeconfig` to indicate where to find the kubeconfig file.
More documentation about the `kops export --config` parameter would be good, yes!

Is there a param to set the location of the kubeconfig file then? 
If not, this ticket is a request to add one.

**Comment by chrislovecnm** [comment]
Nope no `--kubeconfig` flag here https://github.com/kubernetes/kops/blob/master/cmd/kops/export_kubecfg.go

Great idea... I am going to update the title of the issue if you do not mind.  This is a great starter level issue for someone to address!

**Comment by chrislovecnm** [comment]
Please edit the title if I am not understanding the feature request clearly.

**Comment by kenden** [comment]
@chrislovecnm that's great thanks!

**Comment by rajatjindal** [comment]
if no one is working on it yet, can i take this. as a first time contributor, it really do look like 'good-starter-issue'

**Comment by pandeybk** [comment]
We can use one liner this 

`
KUBECONFIG=$HOME/test-kubeconfig.yaml kops export kubecfg --name k8s.test.eu-west-1.aws.redacted.net --state s3://k8s/kops/
`

**Comment by jsenon** [comment]
Is is take ? @rajatchopra do you handle this?

**Comment by awbacker** [comment]
Surprisingly not fixed yet (not the documentation about --config).  

Still have to use the `export KUBECONFIG` workaround.  Pretty bad when you need to share a kubeconfig with someone.

**Comment by ms4720** [comment]
Is this a good place for a bad programmer with the go book to start?

**Comment by justinsb** [comment]
So we have a PR for this now - #5955.  I guess I'm wondering why we don't just use the KUBECONFIG env var?

We use kubeconfig in a few places:
* delete (when removing the configuration after a cluster delete)
* update/export (when writing the configuration)
* generally, to get the "current cluster", which makes specify the cluster optional in most places.

I think we'd have to add the `kubeconfig` flag essentially to all our commands.

**Comment by jacob-betmatic** [comment]
For anyone who comes here, I confirm it works now with v1.23.2 (although it is not in the kops help)
```
kops export kubecfg --kubeconfig kubeconfig.yaml
```
If `kubeconfig.yaml` does not exist, it is created.
