### ISSUE TITLE
How to update dockerd configuration when spinning a cluster?

### ISSUE THREAD

**Issue by jaipradeesh** [kubernetes/kops#2383]
Apparently, the docker daemon runs only on unix socket. Is there a way to configure dockerd options when spinning a cluster via kubernetes?

**Comment by chrislovecnm** [comment]
Only specific ones such as logging. Which option?

**Comment by dolftax** [comment]
`commit` and `push`. Don't find it on `kubectl run`

**Comment by justinsb** [comment]
I'm sorry @dolftax, I'm not clear which options you're trying to set.  commit and push aren't `dockerd` options.

I think your question might actually be a kubernetes question.  You can't easily `commit` or `push` kubernetes pods, AFAIK.

**Comment by dolftax** [comment]
I think I misunderstood your question. I would like to connect to the node's dockerd from outside the cluster and run `commit` and `tag` operations. Since the daemon listens only on unix socket, only way I see it to forward socket to tcp via `socat`. But that isn't the right way to do it as this should be executed whenever a new node is added to a cluster. 

My question is, is there a way to let docker daemon listen on 2375 (or) 2376 ports on the nodes so that I can access from outside the cluster?

**Comment by rdtr** [comment]
https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option

so you want to set `-H` option..?

**Comment by dolftax** [comment]
@rdtr Yes

**Comment by emilhdiaz** [comment]
Bump. Running into this same requirement. Need to be able to run dockerd on a TCP port instead of the unix socket. Has there been any progress in supporting the `-H` option? Or can you point me in the right direction of how I might be able to do this myself?

**Comment by jaipradeesh** [comment]
@emilhdiaz AFAIK, no. I ended up creating ssh sessions (programatically) to the host and executing `docker` commands on the host.

**Comment by chrislovecnm** [comment]
@jaipradeesh if you are interested in implementing this let me know.

**Comment by jaipradeesh** [comment]
@chrislovecnm Will take a look at the feasibility and let you know.

**Comment by jaipradeesh** [comment]
@chrislovecnm https://github.com/kubernetes/kops/pull/4497

**Comment by justinsb** [comment]
Associated PR looks good.  I am wondering what the use case is here though.  Is this for CI builds?

**Comment by jaipradeesh** [comment]
By running dockerd with custom `host` options, the daemon could be accessed from other nodes in the network.

Requirements:
- https://github.com/kubernetes/kops/issues/2383#issuecomment-356727293
- https://github.com/kubernetes/kops/issues/2383#issuecomment-295574330
- https://github.com/kubernetes/kops/issues/3061
