### ISSUE TITLE
Master not starting

### ISSUE THREAD

**Issue by richburdon** [kubernetes/kops#2384]
I'm setting up a new cluster but not seeing the master node in the EC2 dashboard and kubectl commands are failing with what looks like the common "placeholder IP" address error.

~~~~
$ kubectl get nodes
Unable to connect to the server: dial tcp 203.0.113.123:443: i/o timeout
~~~~

I've double checked that my 4 DNS NS entries (`dig ns MY_DOMAIN`) match the 4 entries provided by my Route53 Hosted Zone (`aws route53 get-hosted-zone --id MY_ZONE_ID`) and it's been several hours, so DNS should have replicated.

Again, I can see the 2 nodes (Running) in the EC2 console (`nodes.MY_CLUSTER`), which correspond to my config (`kops edit ig --name=MY_CLUSTER name`), but I was expecting to find an instance for 'master-us-east-1a.masters.MY_CLUSTER'.

I'm Following this using kops 1.5.3
https://kubernetes.io/docs/getting-started-guides/kops

**Comment by richburdon** [comment]
It seems that although "us-east-1a" shows up for `aws ec2 describe-availability-zones --region us-east-1`, it doesn't actually work. "us-east-1d" did. I don't understand why.

**Comment by logosity** [comment]
FWIW, I ran into this same problem while working thru: https://github.com/kubernetes/kops/blob/master/docs/aws.md 

Following @richburdon 's lead, I switched from `us-east-1a` to `us-east-1d` and things came up fine in a few minutes (I gave it an hour after trying with `us-east-1a` and the default IP's still hadn't changed). 

The only other thing I noticed is that the master EC2 instance was not there before (I just had the two node instances) but now I have 3 EC2 instances. The one that was missing before is a c4-large with the name: `master-us-east-1d.masters.<my-domain-name>`. 

Also, if it helps, I am using a sub-domain where the main domain is hosted elsewhere (i.e. the NS records were created in my domain host but point to the AWS name servers provided from the `aws route53 create-hosted-zone...` command as per the documentation).

**Comment by jwilander** [comment]
I recently ran into the same issue trying to use `us-west-2a`, per [the guide](https://github.com/kubernetes/kops/blob/master/docs/aws.md). The nodes EC2 instance would spin up but the `master` would not. `kops validate cluster` would fail every time, complaining about the DNS. Waiting over an hour made no difference.

I switched to `us-east-1d` and it worked fine after a few minutes of waiting.

**Comment by tadgh** [comment]
I am experiencing this issue as well! Except in `ca-central-1a` Will try 1b and report back..
