### ISSUE TITLE
Empty `sshAccess` field is not accepted

### ISSUE THREAD

**Issue by MohamedBassem** [kubernetes/kops#2386]
Hi,

I'm trying to block SSH access to all the nodes of the cluster. The way I'm trying to do it is :
1- `kops edit cluster`.
2- Changing the default `0.0.0.0/0` to an empty array `[]`.

On save and exit I'm getting this error : 

```
# Found fields that are not recognized
# ...
#       kubenet: {}
#     nonMasqueradeCIDR: 100.64.0.0/10
# +   sshAccess: []
#     subnets:
#     - cidr: 172.20.32.0/19
# ...
```

Am I doing something wrong?

**Comment by kenden** [comment]
Does it work if you just remove this line?
`sshAccess: []`

**Comment by MohamedBassem** [comment]
No it doesn't : 
```
# error populating cluster spec: Completed cluster failed validation: SSHAccess not configured
```
