### ISSUE TITLE
Missing documentation for 'upgrade' command

### ISSUE THREAD

**Issue by argusua** [kubernetes/kops#239]
Hi. I'm trying to upgrade my cluster v1.3.3 to v.1.3.4. In help of kops, I see command 'upgrade'. But when I trying to run it, I get error:

```
% kops upgrade cluster --newname test2.k8s.mydomain.net                                                                                                                                                      - вівторок, серпень 02, 2016
I0802 16:22:54.850879   30841 populate_cluster_spec.go:233] Using kubernetes latest stable version: v1.3.4
W0802 16:22:54.850906   30841 populate_cluster_spec.go:245] Normalizing kubernetes version: "v1.3.4" -> "1.3.4"
I0802 16:22:56.902051   30841 populate_cluster_spec.go:295] Defaulting DNS zone to: ***************
F0802 16:22:58.733972   30841 upgrade_cluster.go:26] could not find masters
```

kops version  git-132a84e
Thanks for any help.

**Comment by vreon** [comment]
I ran into this too. `kops` is looking for a `Role: <cluster-name>-master` tag to locate the master instances ([link](https://github.com/kubernetes/kops/blob/94653bd8fce600c797fad06e3eb8f93590a8ff3d/upup/pkg/kutil/upgrade_cluster.go#L101-L104)), but those tags aren't applied when a cluster is created with `kops`.

**Comment by argusua** [comment]
My workaround for upgrade from 1.3.3 -> 1.3.4
1. If you have more than 1 cluster, backup your $HOME/.kube/config file and remove all cluster except cluster what you want an upgrade. (some kops commands incorrect works when clusters > 1)
2. Run `kops edit cluster` and add or update line 
kubernetesVersion: 1.3.4 for like this:
  ```
  kubernetesVersion: 1.3.4
  masterPublicName: api.yourdomain.name
  networkCIDR: 172.20.0.0/16
```
3. Run `kops update cluster test.k8s.gelato.tech` and check that now kubelet 1.3.4 will be used.
4. Run `kops update cluster test.k8s.gelato.tech --yes` for apply changes.
5. Then restart your master nodes and minions by `kops rolling-update cluster your.domain.name --yes`
or manually.
Rolling-update has a bug. It does not wait when a master node will be ready in kubernetes cluster.

**Comment by justinsb** [comment]
Ah - this is confusing!!  upgrade is only intended for use during the cluster upgrade procedure from kube-up to kops, not from kops -> kops.

It is documented here, but you shouldn't be using it:
https://github.com/kubernetes/kops/blob/master/docs/upgrade_from_k8s_12.md

I'll add docs on how to upgrade kops -> kops!

**Comment by justinsb** [comment]
I'm going to keep this open to remind me to clean up the UX/docs if that is OK!

**Comment by kris-nova** [comment]
Done
