### ISSUE TITLE
Use Charts to install addons

### ISSUE THREAD

**Issue by kenden** [kubernetes/kops#2391]
Isn't [addon_manager](https://github.com/kubernetes/kops/blob/master/docs/addon_manager.md)  just a light version of [helm](https://github.com/kubernetes/helm)?

Instead of managing [addons](https://github.com/kubernetes/kops/blob/master/docs/addons.md)  like the [cluster-autoscaller](https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler) addon, for example, which then requires to maintain its [configuration](https://github.com/kubernetes/kops/blob/master/addons/cluster-autoscaler/v1.4.0.yaml), why not just use the [aws-cluster-autoscaler chart](https://github.com/kubernetes/charts/tree/master/stable/aws-cluster-autoscaler) ?
 
We could keep addons as a thin wrapper for helm charts. 
They would basically just call helm, for ex:
`helm upgrade --install latest  stable/aws-cluster-autoscaler --values config.yaml`

Where `config.yml` would contain kops specific configuration.

**Comment by fhemberger** [comment]
See: https://github.com/kubernetes/kops/issues/2399#issuecomment-296227004

I think it would make sense to move all addons to the **Helm** project, also for all addons provided in [`kubernetes/kubernetes`](https://github.com/kubernetes/kubernets/cluster/addons) to avoid the effort of managing the same addons in different locations. As helm also offers versioning of packages, it would help to provide the correct addon version for the Kubernetes version in question.

**Comment by kenden** [comment]
This is related:
https://github.com/kubernetes/kops/issues/1180

**Comment by archSeer** [comment]
To add to the discussion, I agree that helm would be preferable since helm charts have more maintainers and a wider community adoption (instead of kops specific packaging). At the time of writing, heapster is 3 major versions behind, ingress-nginx is 0.8.3, whereas the latest is 0.9.0-beta.5, cluster-autoscaler is 2 versions behind, etc.

**Comment by chrislovecnm** [comment]
@justinsb ... your take on this?

**Comment by StevenACoffman** [comment]
@justinsb What are your thoughts here?

**Comment by justinsb** [comment]
There's a lot of progress on deciding on an addon manager for the kubernetes project, which might end up being helm, but it's more likely to be something lower level which helm would then leverage IMO.  See bgrant's "Declarative Application Management" presentations.

For the core addons (kube-dns) we don't want to & probably can't use helm - this is low level bootstrapping.  Then some people have asked for standalone manifests for things like dashboard, and so we maintain those in `addons/`.  Those are purely optional however.

I hope we'll get a kubernetes-wide addon approach agreed, and then we can indeed have a standard manifest for all addons in the source repos.  We'll probably still have to vendor our core addons (e.g. kube-dns), but then hopefully there will no need to `addons/`

**Comment by chrislovecnm** [comment]
I may be working on extending our addons functionality that we have in core. For bootstrapping the cluster is works very well. For instance installing Jenkins or another ci tool that would build the cluster services for you.

We have the channels tool, and do not see it going away in the future. We need to keep kops bootstrapping dead simple IMO. 

Helm is a great tool, but installing a cni provide needs to be simple ;)

**Comment by StevenACoffman** [comment]
Thanks! Brian Grant was involved in this [Declarative application management in Kubernetes](https://docs.google.com/document/d/1cLPGweVEYrVqQvBLJg6sxV-TrE5Rm2MNOBA_cxZP2WU/edit) document which may be what your are referring to.

**Comment by chrislovecnm** [comment]
I am going to close this as work will start on the addon manager, which will probably not use charts.
