### ISSUE TITLE
Can't change instance type for slave nodes from t2.medium to m3/c3.medium 

### ISSUE THREAD

**Issue by Miyurz** [kubernetes/kops#2392]
We were trying to change instance type for nodes(slave) from t2.medium to m3.medium and it failed. it looks like we can move from t2 family to c4 or m4 family but not c3 or m3.  Tried changing types from a `t2.medium` to `c4.large` or `m4.large`, it works fine and also vice-versa. The changes are applied and cluster is back up in some time with pods running fine.
But if we try doing a `t2.medium>>m3.medium` or `t2.medium>>c3.large`, then the nodes die and then never come back.

Not sure if its kops thing or aws but I thought it was good to bring this to your notice

**Comment by Miyurz** [comment]
@justinsb @kris-nova @chrislovecnm ^

**Comment by hubt** [comment]
What happened when you did this? Why didn't the c3/m3 work? Was it related to local ssds? That should really be the only difference.

**Comment by chrislovecnm** [comment]
Do you have those instance types in the region?

**Comment by ahawkins** [comment]
> Do you have those instance types in the region?

I'm guessing not. I know `ap-south-1` was used. This makes sense because the previous C/M3 series would never be available in that region. I suggest we close this one.

**Comment by chrislovecnm** [comment]
Closing
