### ISSUE TITLE
Use subnet ids when creating clusters when existing VPC is used

### ISSUE THREAD

**Issue by ashic** [kubernetes/kops#2394]
If we do kops create cluster specifying vpc and network cidr, then the next step is to kops edit cluster, and replace the subnet cidrs with ids (at the least... we could also edit the subnet cidrs to the exact matching values, and also specify the ids). We need to do this for each AZ, and when using --topology=private, we need to do it twice (once for the private subnet, once for utility). 

It'd be great if this were auto-detected when an existing VPC is used.

**Comment by pronix** [comment]
i working on it. hope today will PR

**Comment by gbmpgb** [comment]
kops edit cluster cluster-name --state= s3://bucket-name
Edit cidr with your custom subnets.

![image](https://user-images.githubusercontent.com/30672259/31245543-51b14f0e-a9d0-11e7-94cc-fa79eca04daf.png)
