### ISSUE TITLE
User report: no EBS volumes on nodes

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#24]
kops didn't create an EBS volume for the nodes, instead relying on the default 8gb volume to store data.

It would be nice if:

* It created an EBS volume
* It was easy to specify the desired size of the EBS volume

**Comment by g--** [comment]
What's the use case for EBS volumes?

**Comment by felipejfc** [comment]
yesterday I was migrating a cluster and suddenly kubernetes was not able to download images anymore because it filled up the docker tmp folder

**Comment by justinsb** [comment]
This should now work, docs here: https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#changing-the-root-volume-size-or-type

Please reopen or open new issues for any problems / improvements needed  :-)
