### ISSUE TITLE
Consider supporting "hot" reconfiguration

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#240]
We currently upgrade only by terminating an instance and replacing it.  Particularly for the master, it might be more convenient to allow a reconfiguration without killing the machine.

**Comment by justinsb** [comment]
Another reason: for the masters, we don't want to reduce quorum size by one.

**Comment by dnascimento** [comment]
Self-Hosted Kubernetes by CoreOS seems a good approach. Would be good to have a convergence on deployment and update methods

**Comment by chrislovecnm** [comment]
One word ... immutable.  I have serious problems with this design.  Please someone tell me I am wrong.  @dnascimento CoreOS does not do that either.  I replaces itself inline.

@justinsb lets chat about this some time.

**Comment by blakebarnett** [comment]
I also think this is a can of worms and this issue is ancient so I'll close for now, if anyone wants to revisit the discussion please re-open it.
