### ISSUE TITLE
Add templating functionality for kops cluster.yaml files

### ISSUE THREAD

**Issue by kenden** [kubernetes/kops#2404]
Allow to generate/apply kops config.yaml files from template files with Kops.

If we want to create almost the same cluster in different VPCs, Regions, AWS accounts, it would be nice to be able to generate cluster.yaml files with just some differences, like region/vpc/ec2 instance size/subnets...

Basically, create "helm-kops".

kubectl could have allowed creating configurations based on templates, but after taking a long time to decide what the proper templating format would look like etc, helm was born and took over.
IMHO, it would have been easier to just have one tool instead of two. Helm is great, though.

So maybe this templating functionality could be integrated inside Kops before some helm-kops tool does it?

**Comment by chrislovecnm** [comment]
So #1210 is an item about installing the kops binary and is out of the context of this discussion.

Making it easier to create and maintain kops YAML files would be a _major_ win for kops.  We are on the same page [btw](https://twitter.com/chrislovecnm/status/854838558816956417).  

So my questions:

1. Can you provide some bullets for business reqs?
2. What would an MVP look like.  Where should we start?
3. How can you help?

Again awesome idea!!!

**Comment by chrislovecnm** [comment]
Adding @dkaplan-pivotal @weaseal @ringods to this discussion.  BTW @ringods I also like the kops init idea.

**Comment by chrislovecnm** [comment]
@mad01 can we close this? Btw I would love a demo of how this works ;)

**Comment by kenden** [comment]
@mad01 Missed this before, this is great, thanks!
This is in 1.8.0-alpha.1 at the moment, will be in 1.8.0, then.

**Comment by kenden** [comment]
@chrislovecnm I made a PR for this: https://github.com/kubernetes/kops/pull/3655

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by afirth** [comment]
I think [this doc](https://github.com/kubernetes/kops/blob/master/docs/manifests_and_customizing_via_api.md#exporting-a-cluster) is out of date with these changes? Stoked, this is a big step towards sharing fully featured setups.

**Comment by chrislovecnm** [comment]
@afirth yes that doc is out of date. Contributions are always appreciated.

@kenden closing this issue
