### ISSUE TITLE
Support a set of tags at the cluster level

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#241]
e.g. billing tags

We should then apply these tags to the launch configuration etc so that AWS billing works nicely.

**Comment by justinsb** [comment]
We should support:
* AWS tags
* k8s labels
* both on the cluster & instance group level.

**Comment by mrichmon** [comment]
Auto-tagging at the instance level to support AWS billing and automation such as scripts that people use to automatically shutdown AWS instances unless tagged appropriately.

**Comment by ajohnstone** [comment]
this still seems to be an issue.

```
kops version
Version git-e1a9aad

W1107 16:32:14.488208   16122 autoscalinggroup.go:192] Ignoring tag changes until we have #241: %vmap[k8s.io/role/master:1 Name:master-eu-west-1c.masters.production-a-cluster.k8s-production.photobox.com KubernetesCluster:production-a-cluster.k8s-production.photobox.com AwsType:k8s Department:web Owner:web-operations-team@photobox.com Project:k8s]
```
