### ISSUE TITLE
Fix our CI build - Fix Travis or move to another provider.

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2412]
I am personally fed up a bit with Travis.  I like how simple it is, but we are constantly wasting time, restarting travis builds. Here are some options:

1. Jenkins
2. CircleCI
3. Travis

*Problem*

We are continuously having Travis jobs not report back, or just not start.  We have to close the PR, and then reopen it.  We are also having cases where one of the Travis jobs fails.  It is a waste of time for the maintainers of this project.

**Jenkins**

We can build a Jenkins job that reuses the build and test environment that is maintained by Google.  The downfall is that Jenkins is Jenkins.  But the upside is that we would be supported.

**CircleCI**

I have heard that lots of people like it, but I know little about it.

**TravisCI**

Does anyone know how to get Travis happier?

**Other Options**

Any ideas?

**Comment by denniswebb** [comment]
I've done a lot with circle actually. It works well, but can have random failures and need the cache cleared also, but not an issue typically.

**Comment by chrislovecnm** [comment]
@kris-nova mentioned that she loves Travis, so I am open to getting Travis to work.  But I have zero idea how to fix it.  I have googled it six ways sideway, and have not been able to find anything.

**Comment by joshk** [comment]
Hey, my name is Josh and I'm from Travis, how can I help?

**Comment by chrislovecnm** [comment]
@joshk thanks for reaching out!!!!!

We are having PRs in kops where the build in Travis that do not seem to be starting, or a Travis build just seems to run forever (have rarely seen this).  The big problem is that the job does not start in Travis, when a PR is created.  I cannot recreate easily, but a PR will just say that it is waiting on status from Travis, and I cannot see the job running in Travis, for that PR.

Closing and opening the PR, 90% of the time, fixes the problem.

What information would be helpful?  Next PR we see, that does no run in Travis, holler?

The problem may be on GitHubs side of the house as well.  I do not have enough information.

Again ... so awesome that you reached out!!!!

**Comment by joshk** [comment]
@chrislovecnm thank you so much for this information!

I'm one of the founders at Travis, with my main focus on Product Management for the team, but I'll  follow up on this with the team on Monday so we can dive a little deeper into what might be going on.

I am sorry about these issues, and would love to get to the bottom of this ASAP.

Also, I came across this by accident as I was investigating Kubernetes, which I've kinda fallen in love with :)

Thank you for all your amazing work on Kops!

**Comment by joshk** [comment]
Wow, I just saw that you only opened this issue 3 hours ago, and yet I've have the Kops repo sitting in a tab for the past week, but only decided to check out the open Issues today, what serendipitous timing!

**Comment by joshk** [comment]
One bit of information which would be super useful is pointing to a Branch Push or PR which we should have be notified about but we didn't build. Eg. date and time that we should have run a build, and what the build should have been for. Then we can focus on this one event and see if we can find a pattern of events which we aren't processing.

**Comment by chrislovecnm** [comment]
Actually thinking about it ... I think I can find something....

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/pull/1727 <- had had to close and re-open.
https://travis-ci.org/kubernetes/kops/builds/224944827 <- had to restart the build and tip failed to run.  This is the build number after I restarted
https://github.com/kubernetes/kops/pull/2381 <- had to close and re-open

Oh, and your timing was fabulous.  We also have developer office hours on Friday morning ... See the README ... if someone could swing by if we cannot work it out here.

**Comment by chrislovecnm** [comment]
@joshk GOLD - https://github.com/kubernetes/kops/pull/2167 <- this is not building :(  This is exactly what I see

**Comment by joshk** [comment]
Using #2381 as the example, as it is within our log retention threshold, I see we did process a build for the PR when it was opened, and it failed https://travis-ci.org/kubernetes/kops/builds/223414087

So the question now becomes, why isn't GitHub commit status updates not going through.

Well, the mystery deepens as it looks like we are sending them, as least that is what the logs say:

```
Apr 18 21:11:07 travis-org-tasks-production app/tasks.2:  I [task] type=github_status build=223414087 repo=kubernetes/kops state=pending commit=69c89d7f9fe7c8223f6c681959868d3e825a01f9 
Apr 18 21:11:07 travis-org-tasks-production app/tasks.2:  I queue=github_status notifier=github_status build=223414087 repo=kubernetes/kops  time=0.136 jid=441215663d9409014d661aef event=pull_request pull_request_number=2381 
Apr 18 21:11:08 travis-org-tasks-production app/tasks.3:  I queue=github_status notifier=github_status build=223414087 repo=kubernetes/kops  time=0.244 jid=72c7fbf657c73e06e19d0ff2 event=pull_request pull_request_number=2381 
Apr 18 21:11:08 travis-org-tasks-production app/tasks.3:  I [task] type=github_status build=223414087 repo=kubernetes/kops state=pending commit=69c89d7f9fe7c8223f6c681959868d3e825a01f9 
Apr 18 21:11:09 travis-org-tasks-production app/tasks.3:  I [task] type=github_status build=223414087 repo=kubernetes/kops state=pending commit=69c89d7f9fe7c8223f6c681959868d3e825a01f9 
Apr 18 21:11:09 travis-org-tasks-production app/tasks.3:  I queue=github_status notifier=github_status build=223414087 repo=kubernetes/kops  time=0.148 jid=85db5dd9cdc9e6cdb3ace444 event=pull_request pull_request_number=2381 
Apr 18 21:27:33 travis-org-tasks-production app/tasks.3:  I [task] type=github_status build=223414087 repo=kubernetes/kops state=failure commit=69c89d7f9fe7c8223f6c681959868d3e825a01f9 
Apr 18 21:27:33 travis-org-tasks-production app/tasks.3:  I queue=github_status notifier=github_status build=223414087 repo=kubernetes/kops  time=0.122 jid=054914b7d578386dedb89655 event=pull_request pull_request_number=2381 
```

We sent three `pending` updates (we sent one when the Build Request was received, sending the two extra when the jobs started is possibly a bug we should look into), and one `failed` update, for when the Build finished.

And I think I might have found a lead!

This is the commit we send the commit status updates for: https://github.com/kubernetes/kops/commit/69c89d7f9fe7c8223f6c681959868d3e825a01f9

But this is the actual commit from the PR: https://github.com/kubernetes/kops/pull/2381/commits/456a4635d559b8bcf241e42ce154df8103eb6ae0

From what I can see, 6 seconds after the PR was opened, we received a new event from GitHub saying the PR was edited. Is it possible that the PR received a force push, essentially updating the whole PR, and wiping away the previous commit?

Also, that said, I see the event from GitHub saying the PR was `edited` was rejected by us as we don't recognize that event. I think that might be a mistake on our end.

I will follow up with the team on Monday about the `edited` event and why we are rejecting it.

If you could help confirm the PR force push theory that would help a lot as well.

As for new instances of this issue cropping up, if you could let me know within a day or two of them happening it will make it a lot easier for me to dive into the data behind the issue.

**Comment by chrislovecnm** [comment]
It is the bot that edits the pr. We have a bit that adds the reviewable icon in the PR... so the PR is edited, but the Git sha does not change.

**Comment by joshk** [comment]
Thanks for the clarification @chrislovecnm 

So then the question hot on my mind is why we have the commit ref for the old commit, but not the new one? 

Did GitHub not send an event? 

We will have to dive a bit deeper and see what is going on... watch this space.

**Comment by joshk** [comment]
I just checked the webhook payload we received from GitHub and can confirm that the SHA sent in the payload was 69c89d7f9fe7c8223f6c681959868d3e825a01f9

It's starting to look like GitHub didn't send us an event for the force pushed commit to the PR.

**Comment by joshk** [comment]
I've pinged our friends at GitHub for some help in understanding what happened. I'll update this issue with more info soon.

**Comment by chrislovecnm** [comment]
This one is stuck https://github.com/kubernetes/kops/pull/2418 - Travis is not happy 😿

**Comment by joshk** [comment]
Just as a general update, regarding https://github.com/kubernetes/kops/pull/2418, I have escalated this to our engineering team to dig into why GitHub couldn't confirm the merge commit with us. 

I've also yet to hear back from GitHub about the other PR merge commit issue.

Thank you for your patience while we dig into this.

**Comment by chrislovecnm** [comment]
@joshk any update on this?

**Comment by chrislovecnm** [comment]
@joshk not sure what you did, but we are seeing far less of problems.  I think I had a couple of hiccups on a PR but cannot recreate.  

I am having challenges getting kops to deploy with the Travis s3 plugin.  Where can I file a trouble ticket?

**Comment by chrislovecnm** [comment]
Travis is happy now.  Closing
