### ISSUE TITLE
Question: Add flag "--ssh-access" optional to "--admin-access"?

### ISSUE THREAD

**Issue by fhemberger** [kubernetes/kops#2415]
In version v1alpha2, "AdminAccess" was split up into "SSHAccess" and "APIAccess". Are there plans to reflect this change by introducing a separate command line switch as well? There are scenarios where it would make sense to treat rights differently, e.g. CI/CD pipeline with API access (secured through RBAC) should not have SSH access.

Would be nice if this was possible on cluster creation, without the extra step to modify the config manually.

**Comment by BradErz** [comment]
Was addressed: in https://github.com/kubernetes/kops/pull/3014

Can be closed @chrislovecnm

**Comment by fhemberger** [comment]
Awesome, thanks!
