### ISSUE TITLE
Kubernetes cluster why exactly is public hosted domain needed on AWS

### ISSUE THREAD

**Issue by vivekaundkar** [kubernetes/kops#2416]
I am new to kubernetes. Using Kops I am able to create cluster using both public and private topologies on AWS . However trying to under why is it essential to have an public hosted domain for kubernetes cluster? Is there a way we can just use route 53(with no need of public hosted domain on external site like GoDaddy etc) and create a fully functional high availability kubernetes cluster? If do please point to some documentation or working example

**Comment by kris-nova** [comment]
Hi @vivekaundkar,

So this has been brought up many times already. There is more information on duplicate issues
 - https://github.com/kubernetes/kops/issues/2340
 - https://github.com/kubernetes/kops/issues/172

We already have a PR in place that is actively being worked on to solve this issue 
 - https://github.com/kubernetes/kops/pull/2327

Closing if that is okay with you?

**Comment by vivekaundkar** [comment]
Thanks a lot for sharing details.
Sure you can mark this as closed
btw do you know timeline about PR mentioned above?
