### ISSUE TITLE
Route53 mapper should add `listHostedZones` for master node

### ISSUE THREAD

**Issue by jaipradeesh** [kubernetes/kops#2427]
Route53 mapper doesn't add this policy to master node and throws error `Access denied. No permission to listHostedZones`.

**Comment by chrislovecnm** [comment]
More details, please. I need more context.  You are able to add custom IAM roles to your nodes and masters btw ... if I understand your question.  But I really need a lot more detail here :(

**Comment by dolftax** [comment]
Sure. Will update more info in few hours.

**Comment by Tibingeo** [comment]
Kops creates roles in IAM for master and nodes by default, these roles dosen't have any policies attached to it, `Route53 mapper` requires `listHostedZones` to be enabled. which is not added by `Route53 mapper` (kops).

**Comment by dolftax** [comment]
@chrislovecnm Label this issue else it might get lost.

**Comment by chrislovecnm** [comment]
I have a PR in for perms. Let me double check that it is included.

**Comment by chrislovecnm** [comment]
We do not have hosted zone stuff in https://github.com/kubernetes/kops/pull/2497 need to add them
