### ISSUE TITLE
Cluster on dedicated tenancy/host in aws using kops

### ISSUE THREAD

**Issue by UlaganathanNamachivayam** [kubernetes/kops#2433]
Hi Folks
Is it possible to spin up a cluster on a dedicated tenancy/host. Please share your views on this model.We would be requiring such options when we prefer any compliance/certifications.

**Comment by chrislovecnm** [comment]
Please provide more context and details

**Comment by UlaganathanNamachivayam** [comment]
@chrislovecnm Thanks for your response. Below is more details on the requirement.
lets assume we are building an environment which has to adhere HIPPA/PCI or any other compliance in the market. So in that case PCI mandates the underlying machines to be separated and secured.

In AWS today we have tenancy models like shared/dedicated instance/dedicated host.So is that possible for me to enforce today using kops like annotations in the cluster space before i actually provision the cluster. Currently its all shared instance when kops provisioning the cluster.

Also is it possible to utilize my own custom AWS-AMI to provision the cluster which has all the customization i required including EBS encryption etc etc.

**Comment by UlaganathanNamachivayam** [comment]
@chrislovecnm Can you help with above queries and also the below.

1) How do anyone use their customized AMI to provision the cluster. I have tried creating an AMI and kept that AMI ID to provision the cluster but the instances were not provisioned at all.

2) I have used kops 1.6 version and tried it on kubernetes 1.6.1 version. It works fine with the default CentOS AMI ID.

Thanks in advance.

**Comment by chrislovecnm** [comment]
We have a API value that can be set to select tenancy. Please let me know if you require more help
