### ISSUE TITLE
Fix TestCreateClusterCustomIamRole

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2438]
I need to determine how to fix TestCreateClusterCustomIamRole in create_cluster_integration_test.go.

It is using a featureflag, and I am uncertain how to enable the FeatureFlag during a go test.  Opening this issue to track work.

**Comment by justinsb** [comment]
`ParseFlags("FlagName")` - see the feature flag tests.

We don't have a nice wrapper for setting the flag and restoring it afterwards.  But we haven't needed that yet...

**Comment by chrislovecnm** [comment]
Closing as I am able to add to my PR
