### ISSUE TITLE
unclear how to create / delete addons

### ISSUE THREAD

**Issue by RXminuS** [kubernetes/kops#244]
The documentation on how to create addons is really vague. As a result of this I managed to stuff things up at which point I was surprised to find that there is no `kops addons delete` command to undo my incompetence...HELP!

Two suggestions / questions...documentation on how to properly add things like dashboard & monitoring addons to kops; and how to remove them from the cluster if needed

**Comment by chrislovecnm** [comment]
You can always use `kubectl` to add those btw, as a workaround.  

@justinsb do we want to tie those into `kops`?  Maybe a folder of manifests to install??

**Comment by justinsb** [comment]
`kops addons` was a vestigial appendage of kops, left over while we figured out how to deal with addons in a world that includes HA master.  The consensus seems to be use kubectl instead, as @chrislovecnm suggested.  Sorry for leaving it around in a confusing state.

I've started a doc here:  https://github.com/kubernetes/kops/blob/master/docs/addons.md

I've started collating addons into an addons directory, removing the `cluster-service` tag which causes it to be deleted, and adding a `k8s-addon` label which should allow us to upgrade or remove addons in future.  There will likely be more tooling around this in future.

If your addons are really in a bad state, you can SSH in to the master and delete the addons from `/etc/kubernetes/addons` (but leave kube-dns!).  They will be removed within 5 minutes or so.

Going to close this, but do reopen (or open a new issue) if there are still issues.
