### ISSUE TITLE
Allow specifying AMI name for cluster-create and edit ig

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#245]
I've got a requirement to harden my OS image.  KOPS deploys on the latest AMI with a specific name (specifically 282335181503/k8s-1.3-debian-jessie-amd64-hvm-ebs-2016-06-18)

I realize that I'd have to probably start from the above image (or it's later analogs), or fill some (probably unspecified list of) requirements.  But it would give companies a shim into the build system to do OS hardening, before Autoscaling kicks in.

Ideally this could be expressed as:

```
kops create cluster [...] --aminame="zapman_special_ami_20160802"

kops edit ig <name>
(replace AMI name in YAML)

kops update cluster --yes
```

**Comment by ProTip** [comment]
We need the ability to use custom AMI's as well. I was under the impression that the ```--image string``` flag allowed setting the AMI. I have not tried it though and I don't see the option on ```kops create instancegroup```. It would definitely be nice to set the AMI per instance group as well.

**Comment by justinsb** [comment]
Definitely agree - I think this is mostly a docs issue, but there are some improvements needed also.

For the record, the image is built using this script & tool: https://github.com/kubernetes/kube-deploy/tree/master/imagebuilder

- You can build it in your own account.
- It is set per instance group, and you should be able to override it using `kops edit instancegroup`.
- I agree we should have a flag in `kops create ig`
- It would be nice to have a default or a way to change it at the cluster level, but I'm not entirely sure what that looks like yet.
- If you specify an `ami-...` it will use that: https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awsup/aws_cloud.go#L387
- I am trying to make this more of a "matcher", so it would pick the latest image matching some tags you specify.  Again not there yet.
- Any improvements to harden or improve the image itself would be very welcome.

**Comment by noose** [comment]
Hi @justinsb 
Do you have some ETA for that?

**Comment by chrislovecnm** [comment]
@justinsb this is supported ... correct?

**Comment by justinsb** [comment]
I believe this is supported now - not entirely sure why I didn't close this previously.

Going to err on the side of closing, but if there's something that isn't addressed, please do comment / reopen (or open another issue) and we'll address it!

**Comment by UlaganathanNamachivayam** [comment]
This one doesn't seem to accept the custom AMI created using centos 7. I have provisioned a 1.6.1 cluster using kops latest release ( 1.6 ). But the nodes are not recognizing the custom AMI value i have mentioned in the spec and eventually the nodes are not provisioned at all. 

How do i debug further or is there a way i can execute a  set of commands during the instance provisioning or later from a public centos 7 AMI.

Any pointers will be helpful.

**Comment by UlaganathanNamachivayam** [comment]
Hi Folks,
Do we have an update on this request. Does anyone tried this with Custom AMI. Please let me know as its little urgent requirement.

**Comment by zapman449** [comment]
@UlaganathanNamachivayam Yes, it works with debian and we're using it in production.

Edit the instancegroup spec with `kops edit ig <your IG>`

Replace the following snippit:

```
spec:
  associatePublicIp: true
  image: {{ KOPS_AMI }}
```

in our case, the KOPS_AMI looks like `776332878189/csp_kops_ami_1480337246`

**Comment by UlaganathanNamachivayam** [comment]
@zapman449 I tried it using CentOS AMI after adding custom commands to the default centOS AMI.
But kops was unable to provision the instances by using the custom AMI.

Would be helpful if anyone could share a procedure which works for CentOS.

**Comment by UlaganathanNamachivayam** [comment]
Hi Folks,
Can anyone update on this request.

**Comment by UlaganathanNamachivayam** [comment]
@justinsb Seeking your guidance on this below request.

"This one doesn't seem to accept the custom AMI created using centos 7. I have provisioned a 1.6.1 cluster using kops latest release ( 1.6 ). But the nodes are not recognizing the custom AMI value i have mentioned in the spec and eventually the nodes are not provisioned at all.

How do i debug further or is there a way i can execute a set of commands during the instance provisioning or later from a public centos 7 AMI.

Any pointers will be helpful."

**Comment by markbooch** [comment]
Same question as @UlaganathanNamachivayam, Could we customize centos images for KOPS?
