### ISSUE TITLE
Networking CNI or weave?

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kops#2450]
Reading the [networking docs](https://github.com/kubernetes/kops/blob/master/docs/networking.md), it is not clear whether I should have 

```yaml
  networking:
    weave: {}
```

in my cluster.yml file or

```yaml
  networking:
    cni: {}
```

and then run `kubectl create -f https://git.io/weave-kube`. Anyone mind explaining the difference between both approaches?

**Comment by ahawkins** [comment]
I spoke with @chrislovecnm about this yesterday. `cni` is a placeholder where you can add your own on the node itself. Thus you should have `weave` if you want something automatically setup.

**Comment by geojaz** [comment]
Let's clarify how this works in docs.

**Comment by milescrabill** [comment]
Looking at the [networking docs](https://github.com/kubernetes/kops/blob/master/docs/networking.md) the example @olalonde gave is no longer present. Presumably `cni` was replaced with `classic` in the example. Unless I'm mistaken, this can be resolved.
