### ISSUE TITLE
Garbage collection threshold clashes with eviction threshold

### ISSUE THREAD

**Issue by mikelorant** [kubernetes/kops#2454]
Evictions are occurring at the same time as garbage collection. Garbage collection should be attempted before evictions begin.

evictionHard: memory.available<100Mi,**nodefs.available<10%**,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%

image-gc-high-threshold, the percent of disk usage which triggers image garbage collection. Default is **90%**.
image-gc-low-threshold, the percent of disk usage to which image garbage collection attempts to free. Default is 80%.

90% seems too high considering kops builds a cluster with 20GB default.

Suggestion would be to start running GC at 70% and try to get back to 50% if possible.

**Comment by egeland** [comment]
This would be a very useful change!
