### ISSUE TITLE
Add KOPS_EDITOR env variable

### ISSUE THREAD

**Issue by dolftax** [kubernetes/kops#2455]
https://github.com/kubernetes/kops/blob/master/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/editor/editor.go#L40

Let me know if this is fine. If yes, will send a PR.

**Comment by dolftax** [comment]
Such thing exists. $EDITOR is the variable.

**Comment by chrislovecnm** [comment]
don't we have `EDITOR` already?  Not sure how this is different.

**Comment by dolftax** [comment]
Yeah. Found it somewhere in the docs after I reported this issue. :D
