### ISSUE TITLE
Add an argument to choose between flannel backends

### ISSUE THREAD

**Issue by prat0318** [kubernetes/kops#2460]
As per [the doc](https://github.com/coreos/flannel/blob/master/Documentation/backends.md#backends), there are different backends to choose from. This should be an option to choose when choosing `--networking flannel`.

**Comment by chrislovecnm** [comment]
@prat0318 more information please

**Comment by prat0318** [comment]
While creating k8s cluster using kops, one can provide [different networking modes](https://github.com/kubernetes/kops/blob/master/docs/networking.md#supported-cni-networking). My use case was to try `flannel` as the networking mode.

`flannel` also [provide configurations](https://github.com/coreos/flannel/blob/master/Documentation/configuration.md#example-configuration-json) which one can tweak with.

There is an [empty dict](https://github.com/kubernetes/kops/blob/bceed6dfafd5ae7014208153c3d4c9d5a2d52694/tests/integration/privateflannel/in-v1alpha1.yaml#L26) which gets created against `flannel` key in `kops edit cluster` config:

```yaml
  networking:
    flannel: {}
```

But when i tried to edit `{}` with `{"Backends": {"type": "host-gw"}}`, kops threw back parsing error saying fields were unrecognized.

So, there should be a way to provide network configuration while creating up the cluster.

**Comment by chrislovecnm** [comment]
This should be in kops 1.7 if not then it is in 1.8

Need to check 

/assign

**Comment by chrislovecnm** [comment]
This is in, closing - fixed in master
