### ISSUE TITLE
owner incorrectly set on ~/.kube folder

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2466]
root is the owner of the ~/.kube folder on the master.  admin or the base user for the image type should be the owner.

You get the following error when installing a manifest from the master:

```
error: error validating "STDIN": error validating data: mkdir /home/admin/.kube/schema: permission denied; if you choose to ignore
```

kops version:
```
$ kops version
Version 1.6.0-alpha.2 (git-083b78939)
```

k8s version:
```
admin@ip-172-20-20-7:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T10:00:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

I believe this is a nodeup issue, as we need to `chown admin: ~admin/kube`.

**Comment by dolftax** [comment]
`kops/nodeup/pkg/model/kubectl.go` has the following code

```
case distros.DistributionJessie:
	c.AddTask(&nodetasks.File{
		Path:     "/home/admin/.kube/config",
		Contents: fi.NewStringResource(kubeconfig),
		Type:     nodetasks.FileType_File,
		Mode:     s("0400"),
		Owner:    s("admin"),
		Group:    s("admin"),
	})
```

Looks like the group and owner is `admin`. I am not aware of the kops directory hierarchy. Am I looking at the wrong file?

**Comment by chrislovecnm** [comment]
The .kube folder is being owned by root. It needs to be owned by admin.

You also reached out on another issue that I cannot find, which issue was that?

**Comment by chrislovecnm** [comment]
To be clear:

sudo chown -R admin: /home/admin/.kube fixed the problem 

We probably want to create the directory first and then the file, would need to test.
