### ISSUE TITLE
kops rolling release doesn't work well with few nodes

### ISSUE THREAD

**Issue by caarlos0** [kubernetes/kops#2471]
In a cluster with few nodes (1 master + 2 nodes), the rolling release process is not optimal right now.

![image](https://cloud.githubusercontent.com/assets/245435/25598563/1b9d5240-2eac-11e7-82b9-11f3f5b4e9f4.png)

It shut down one node, launched a new one, waited a little, shut down the other node and launched one more.

The problem is that by the time the first new node was up, both old node were already down.
It also seemed like k8s drain the node and didn't check if the pods could be scheduled on the remaining nodes.

Either way, this process end up with ~5min downtime.

------

Suggestions:

- when there are too few nodes (I don't know how many is too few, but 2 seem to be), launch all the new nodes first, than terminate the old ones;
- launch more nodes first, wait for them to became available, then drain and shutdown an old node

**Comment by chrislovecnm** [comment]
This may be a duplicate issue ;)

https://github.com/kubernetes/kops/issues/1718

1. did you use the new feature flag to enable drain and validate?
2. did you increase the wait time for nodes?

**Comment by caarlos0** [comment]
> did you use the new feature flag to enable drain and validate?

no, I didn't know it existed. How do I enable that?

> did you increase the wait time for nodes?

didn't know it was configurable. Is it just a matter of setting `--node-interval`, I presume?

**Comment by caarlos0** [comment]
Since this seems to be a dupe, I'll close it. Thanks
