### ISSUE TITLE
update recommends an upgrade, upgrade says no upgrade required

### ISSUE THREAD

**Issue by BenAbineriBubble** [kubernetes/kops#2499]
> $ kops update cluster
> Using cluster from kubectl context: example.com
> 
> 
> *********************************************************************************
> 
> A new kubernetes version is available: 1.5.4
> Upgrading is recommended (try kops upgrade cluster)
> 
> More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_k8s.md#1.5.4
> 
> *********************************************************************************

> $ kops upgrade cluster
> Using cluster from kubectl context: example.com
> 
> 
> No upgrade required

kops 1.5.1

**Comment by danopia** [comment]
A year later, latest kops, and this is still a thing :-1:

```~ $ kops update cluster

*********************************************************************************

A new kubernetes version is available: 1.10.5
Upgrading is recommended (try kops upgrade cluster)

More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_k8s.md#1.10.5

*********************************************************************************

I0831 14:13:48.533743   17516 executor.go:103] Tasks: 0 done / 82 total; 31 can run
I0831 14:13:49.037539   17516 executor.go:103] Tasks: 31 done / 82 total; 25 can run
I0831 14:13:49.475836   17516 executor.go:103] Tasks: 56 done / 82 total; 24 can run
I0831 14:13:50.449140   17516 executor.go:103] Tasks: 80 done / 82 total; 2 can run
I0831 14:13:50.651388   17516 executor.go:103] Tasks: 82 done / 82 total; 0 can run
No changes need to be applied
~ $ kops upgrade cluster
Using cluster from kubectl context: use1.sat2.k8s.adev.scopely.io


No upgrade required
~ $ 
```
