### ISSUE TITLE
Flannel failed on 1.6 upgrade

### ISSUE THREAD

**Issue by apenney** [kubernetes/kops#2500]
Hi guys,

I updated another cluster to 1.6 today, switching from weave to flannel at the same time, after my bad experience yesterday.  Weirdly 1 master (out of 3) failed to come up, with /etc/cni/net.d/10-flannel.conf being missing.  A reboot did not fix it.  I ended up copying the file from a working master.

@justinsb said it may just be a race condition on directory create, which makes sense!

**Comment by chrislovecnm** [comment]
@apenney kops version?  I assume beta 1.6.0

k8s version ... to and from

**Comment by chrislovecnm** [comment]
Can we close?

**Comment by chrislovecnm** [comment]
Closing please let us know if you need help
