### ISSUE TITLE
Odd message when a cluster is deleted

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2501]
## kops version

```console
$ kops version
Version 1.6.0-beta.1 (git-77f222d)
```

## recreate

Create a cluster and then delete it:

```console
$ kops delete -f $DIR/kops/cluster.yaml --yes
```

We are outputing:

```
subnet:subnet-9fb94ec5	ok
internet-gateway:igw-6f77af09	ok
security-group:sg-16e23868	ok
route-table:rtb-40fb0f38	ok
vpc:vpc-5bdb3922	ok
dhcp-options:dopt-44b24022	ok
Deleted kubectl config for us-east-1.aws.k8spro.com

Cluster deleted

cluster "us-east-1.aws.k8spro.com" not found
```

The last message is kinda odd in my mind.  We somehow are getting back to here - https://github.com/kubernetes/kops/blob/master/cmd/kops/root.go#L258

I would think that last statement should be:

```
Cluster "us-east-1.aws.k8spro.com" deleted
```

**Comment by dolftax** [comment]
I'm unable to replicate the `cluster not found` issue.

I added the following in `GetCluster` method
```
	_, file, no, ok := runtime.Caller(1)
	if ok {
		fmt.Printf("called from %s#%d\n", file, no)
	}
```

.. and ran,

```
➜  kops git:(fix-cluster-delete-message) ✗ ./kops delete cluster $NAME --yes
called from /home/jai/gospace/src/k8s.io/kops/cmd/kops/delete_cluster.go#117
..
..
..
Deleted kubectl config for foo.bar

Cluster "foo.bar" deleted
```

// Is this happening on multiple cluster deletion?

**Comment by chrislovecnm** [comment]
`kops delete -f mycluster.yaml --yes`

```
Cluster deleted

cluster "private-ha.aws.k8spro.com" not found**
```

**Comment by chrislovecnm** [comment]
It is being reported that the wrong error code is being returned as well. Somehow we are doing a get on the cluster.

**Comment by dolftax** [comment]
I will look into it in ~8-10 hours.

**Comment by chrislovecnm** [comment]
thanks!

**Comment by dolftax** [comment]
@chrislovecnm I am unable to replicate this. Without replicating, I'm not sure what has to be fixed. Please try to get detailed replication steps. Will look into it then.

As per your comment https://github.com/kubernetes/kops/issues/2501#issuecomment-299955936 , I tried deleting with a `cluster yaml` file as well. Below are the logs.

```
~/loco/gospace/src/k8s.io/kops/cmd/kops(fix-cluster-delete-message ✗) ./kops delete -f ~/cluster.yaml --yes
..
..
Deleted kubectl config for foo

Cluster foo deleted

Deleted cluster/foo
```

**Comment by chrislovecnm** [comment]
So the problem is that we need to track if we deleted the cluster already before we delete an ig. Technically you could delete multiple clusters with this command, or just instance groups.

The switch statement does not check if the cluster that owns the ig has already been deleted. The first case deleted a cluster, then the next case runs and tries to delete a cluster that already has been deleted.
