### ISSUE TITLE
Unset KOPS_STATE_STORE when generating docs

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2502]
We had unset the KOPS_STATE_STORE in the Makefile, and that got pulled out.  

It would be good to have the KOPS_STATE_STORE unset in the actual command to ensure that the KOPS_STATE_STORE is not included in generating docs.

https://github.com/kubernetes/kops/blob/master/cmd/kops/gen_help_docs.go is the source file
https://github.com/kubernetes/kops/blob/master/cmd/kops/util/factory.go#L31 is the value that holds our KOPS_STATE_STORE.

**Comment by chrislovecnm** [comment]
Updated the makefile, but we need to unset it in the code.

**Comment by rdtr** [comment]
Doesn't this line already reset the value?
https://github.com/kubernetes/kops/blob/master/cmd/kops/gen_help_docs.go#L53

**Comment by chrislovecnm** [comment]
It does not seem to be working :(

**Comment by rdtr** [comment]
`RegistryPath` holds a value that a CLI user actually passes as a flag.
What printed out in docs are default values of all commands which loaded from `KOPS_STATE_STORE` in `init()` function of `root.go`.

Therefore, I needed to delete all command's default flag before running the docs generation func.
