### ISSUE TITLE
Cannot create dashboard on a multi-node cluster

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kops#2507]
Using 0.18.0, created a multi-master cluster on AWS:

```
kops-darwin-amd64 \
    create cluster \
    --name=kubernetes.arungupta.me \
    --cloud=aws \
    --zones=us-west-2a,us-west-2b,us-west-2c \
    --master-zones=us-west-2a,us-west-2b,us-west-2c \
    --master-size=m4.large \
    --node-count=3 \
    --node-size=m4.2xlarge \
    --state=s3://my-kops \
    --yes
```

Trying to setup Dashboard as explained at:

https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

The following command:

```
kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
```

fails with the following error:

```
serviceaccount "kubernetes-dashboard" created
error: error validating "https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by arun-gupta** [comment]
FWIW, the following command works:

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.5.0.yaml
```

Seems like the documentation needs to be reconciled.

**Comment by geojaz** [comment]
@arun-gupta Nice to meet you on the call yesterday!

Sorry, I'm a little confused. What is 0.18.0 the version of? 
It looks like you have a mismatch in versions. Using kops as of today, I assume that your kubernetes cluster is of version 1.5.*.  It looks like you have a mismatch in version between the yaml of the dashboard in the official docs and your cluster. Another option is that your kubectl is behind your cluster version (which may also be true, but in this case, I think it's a dashboard versioning issue). 

That's a long way of saying that as a group, we likely need to do better to inform users of which versions work best- or at all- together.

**Comment by geojaz** [comment]
I'm marking to close because I think this is a documentation issue but for the main docs repo. https://github.com/kubernetes/kubernetes.github.io

**Comment by geojaz** [comment]
/close 

done!
