### ISSUE TITLE
kops update cluster with --ssh-public-key does nothing

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kops#251]
It shows the diff in the update plan, like:

    KeyFingerprint yy:80:a9:6d:ca:yy:yy:35:4e:30:84:yy:66:yy:72:1d -> xx:1c:ca:89:3a:xx:c4:3e:xx:f1:e9:94:bf:1d:e4:xx

but then when I do  kops update cluster --ssh-public-key ... --yes

The key is not updated into aws and the new machines are brought up using same old key

@justinsb I think we talked about that today, maybe it is defaulting to always use ~/.ssh/id_rsa in update ops? or maybe it is ignoring the change at all...

**Comment by philipn** [comment]
@justinsb I see your comment on #221 -- is there a 'right way' to do this right now?  Even if it's just a hacky one-liner, it'd help because I need to update an SSH key across a bunch of nodes :P

**Comment by justinsb** [comment]
This should now be fixed:

* We store SSH public keys in the secrets
* When we first create a cluster, we import the specified public key (defaulting to ~/.ssh/id_rsa.pub)
* The SSH key can be changed using the secret management function - see https://github.com/kubernetes/kops/blob/master/docs/security.md#ssh-access

If you have an existing cluster, you can simply add your key using `kops create secret --name <clustername> sshpublickey admin -i ~/.ssh/newkey.pub` - and you will be hinted to do so when kops detects there is no key.
