### ISSUE TITLE
SSH to nodes?

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kops#2511]
Is it possible to get kops to setup my ssh public key on the nodes as it does for the master?

**Comment by justinsb** [comment]
They should be :-)  What are you seeing?

**Comment by olalonde** [comment]
I was seeing

```bash
ssh ubuntu@<node-public-ip>
Permission denied (publickey).
```

but I just realized the username is `admin` :D

**Comment by chrissound** [comment]
Thanks @olalonde admin worked for me too.

Can this be highlighted somewhere in the docs?

**Comment by abhyuditjain** [comment]
@olalonde In my case, username was `ubuntu`. Dunno why.

**Comment by tuananh** [comment]
@abhyuditjain it depends on the base image i think
