### ISSUE TITLE
kopeio vs kopeio-vxlan

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kops#2514]
When creating a cluster, the following works:

```
		--networking "kopeio-vxlan" \
```

However when editing the cluster yaml file, the following won't work (it reverts back to kubenet):

```yaml
  networking:
    kopeio-vxlan: {}
```

This works however:

```yaml
  networking:
    kopeio: {}
```

It would be less confusing if we stuck to one name, either `kopeio` OR `kopeio-vxlan`.

**Comment by geojaz** [comment]
@olalonde You're probably right. Consistency is useful.

Assuming @justinsb is cool with this- the easiest way that I see to change this is to edit command line flag and the CLI instructions in `cmd/kops/create_cluster.go`. Checkin in with Justin because it's his networking baby.

**Comment by dolftax** [comment]
@chrislovecnm don't want to change the clusterspec, which sounds fair to me as well. Updating the docs should be good enough for now. @geojaz ?

https://github.com/kubernetes/kops/pull/2525#issuecomment-299917526

**Comment by olalonde** [comment]
Ideally, there should be some warning when some config key is wrong/ignored.

**Comment by rdtr** [comment]
Sent a pull request so that kops accepts both `kopeio` AND `kopeio-vxlan` not to break existing API.
