### ISSUE TITLE
kops delete cluster deletes non-cluster resources

### ISSUE THREAD

**Issue by callum-p** [kubernetes/kops#2517]
I use custom DNS names to deploy my cluster into a pre-existing VPC.  E.g. this is what part of my cluster.config looks like:
`masterPublicName: k8sapi.contoso.internal`

I already have a DNS record api.contoso.internal.

When I run kops delete cluster, this line https://github.com/kubernetes/kops/blob/30361eef68b45c4a5dfb9fda363328ab16cd49e0/pkg/resources/delete_cluster.go#L1793 deletes the api record even though it wasn't created by kops in the first place.  It should really get the resource records to delete from the config.

**Comment by dolftax** [comment]
Aren't the DNS resources tagged?

**Comment by callum-p** [comment]
No, you can't tag DNS records

**Comment by dolftax** [comment]
@callum-p Namespacing your cluster would give you better isolation `*.foo.contoso.internal`

@geojaz Instead of validating the records by checking prefixes, how about storing the created records in the state store and delete them?

**Comment by kzap** [comment]
/reopen
this is still an issue even up to now
