### ISSUE TITLE
Remove deprecated commands

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2519]
We have various "secrets" commands.  We should remove them.

For instance https://github.com/kubernetes/kops/blob/master/cmd/kops/secrets_create.go

secrets* in that directory

**Comment by WillemMali** [comment]
#2521

**Comment by WillemMali** [comment]
The current implementing PR doesn't work because `master` is broken: #2521

Once it's rebased onto a working `master` this issue can be closed.

**Comment by chrislovecnm** [comment]
Master is happy again.
