### ISSUE TITLE
monitoring-standalone install error

### ISSUE THREAD

**Issue by Datamaker1** [kubernetes/kops#2522]
Hello. v1.3.0 is installed but v1.6.0 is not installed.

**[Error Messge]**

[ec2-user@ip-10-10-1-90 ~]$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/monitoring-standalone/v1.3.0.yaml
deployment "heapster" created
service "heapster" created

[ec2-user@ip-10-10-1-90 ~]$ kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/monitoring-standalone/v1.6.0.yaml
deployment "heapster" created
service "heapster" created
**error: error converting YAML to JSON: yaml: line 1: mapping values are not allowed in this context**

**Comment by four43** [comment]
I got this same error on a kops deployed 1.6.2 cluster. Let me know if I can provide additional details.

**Comment by BradErz** [comment]
Seems the indentation of the service account was messed up I fixed in #2533 just need someone to approve it, for now if you want it working take the one from my branch 

https://github.com/BradErz/kops/blob/2dab7b8c8988f2bfb81fe8e57c103128c16b2686/addons/monitoring-standalone/v1.6.0.yaml
