### ISSUE TITLE
Documentation discoverability, new contributor

### ISSUE THREAD

**Issue by WillemMali** [kubernetes/kops#2528]
I'm looking for a full specification of the "cluster spec" as mentioned in the CLI docs of `kops create cluster`. I found [this](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md) but it doesn't purport to be complete and it would be nice if it was linked to wherever it is mentioned.

Then, on the homepage there's a mention of CloudFormation; I have not been able to find documentation regarding this and the homepage links to AWS itself; I think a link to the `kops` docs would be more helpful than linking to AWS.

Perhaps it would be nice to have a centralized index of documentation, I think the homepage is very incomplete. A link on the Github wiki to this index would make things easier to find.

Regarding CloudFormation, I think it might be helpful to have a CloudFormation template to set up kops, so you can enter a few parameters, make a CF stack and semi-instantly deploy `kops` onto it. I'm offering to write that.

I'd like `kops` to be more polished so I want to become a contributor. I've set up my Go toolchain (1.8.1, from the official site) and I've tried to remove the `secrets` command subtree, but I can't find it in `kops:master/cmd/kops*`. It seems to already be gone from the source code, but it still generates the Markdown docs for the `kops secret ...` command subtree. I haven't been able to trace that to the source, as it's my first 24 hours with Go. I mainly used `grep` and I looked at `/cmd/kops/root.go`, but it didn't seem to add a `secrets` command to the root (in the section with a list of `cmd.AddCommand(NewCmd*(f, out))`).

The homepage also mentions it's possible to contact the maintainers, but no contact information is provided. I tried joining `kubernetes#kops@slack` but it's a closed group, so this is my attempt at contacting the maintainers.

**Comment by WillemMali** [comment]
The link on the homepage for the Slack channel is out of date, it only lands you at the root of the Kubernetes contribution guide. (This link)[http://slack.k8s.io/] can be used to sign up directly, or (this one)[https://github.com/kubernetes/community/blob/master/communication.md] which is one step removed and which resides in the Kubernetes docs.

The issue I'm trying to fix regarding the docs is (here)[https://github.com/kubernetes/kops/issues/2519].

**Comment by WillemMali** [comment]
I also think it would be nice to describe the process of changing and building the generated docs [here in the installation documentation](https://github.com/kubernetes/kops/blob/master/docs/install.md); while they are not (currently) part of *the* build process (and I understand why that might be useful), they are *a* build process and I think it is good to document and formalize those.

**Comment by WillemMali** [comment]
As these are all fairly minor issues with the docs I've abstained from making issues in the tracker for them, but if an existing contributor could read through them and OK them (partially) as one big or a few small issues I'll flesh them out further.

**Comment by chrislovecnm** [comment]
@WillemMali if you are working on this, it is your call on how to track the work.   Any ideas on auto generating the cluster spec documentation?

> but if an existing contributor could read through them and OK them (partially) as one big or a few small issues I'll flesh them out further.

Not sure what feedback you want, but I would just say PR.  Do it, iterate, make them better.  Start with a smaller issue, and get a PR in. 

> I'm looking for a full specification of the "cluster spec" as mentioned in the CLI docs of kops create cluster. I found this but it doesn't purport to be complete and it would be nice if it was linked to wherever it is mentioned.

I would love to see these docs generated.

> Then, on the homepage there's a mention of CloudFormation; I have not been able to find documentation regarding this and the homepage links to AWS itself; I think a link to the kops docs would be more helpful than linking to AWS.

That, GCE and VMware are not documented.

> and I've tried to remove the secrets command subtree, but I can't find it in kops:master/cmd/kops*

There is a PR in too remove the commands ... need more context.

> The homepage also mentions it's possible to contact the maintainers, but no contact information is provided. I tried joining kubernetes#kops@slack but it's a closed group, so this is my attempt at contacting the maintainers.

Can contact via kops channel in slack, office hours, issues or PRs.  kops slack channel is not a closed group, as I saw you on there :)

**Comment by chrislovecnm** [comment]
can we close?
