### ISSUE TITLE
Terraform documentation is out of date remote state

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2535]
Our TF instructions for how to initializing a remote terraform state in s3 are out of date. 

The documentation is here: https://github.com/kubernetes/kops/blob/master/docs/terraform.md#set-up-remote-state

`terraform init` is now used, and I was unable to figure out the syntax.

```console
$ terraform version
Terraform v0.9.4
```

**Comment by rdtr** [comment]
While searching through terraform Github repo, it looks many people now use a file for remote backend configuration while we can still pass them as arguments.
https://www.terraform.io/docs/backends/types/s3.html
