### ISSUE TITLE
StatefulSet Pods sometimes lose network connectivity (Calico) -- upgrade to Calico 2.1.5?

### ISSUE THREAD

**Issue by tudor** [kubernetes/kops#2538]
We're running a Kubernetes 1.6.2 cluster created with kops 1.6.0-beta.1, and pods occasionally lose network connectivity.

Calico route tables and logs seem to show that we're hitting this Calico bug: https://github.com/projectcalico/calicoctl/issues/1592, which is fixed in calico/cni:v1.7.0, which is part of Calico 2.1.4.

(kops still uses Calico 2.1.1: https://github.com/kubernetes/kops/pull/2286/commits)

Calico 2.1.5 has since been released, so perhaps upgrade to 2.1.5 instead of 2.1.4?

**Comment by ottoyiu** [comment]
I believe Calico 2.1.5 was merged in with:
https://github.com/kubernetes/kops/pull/2536
