### ISSUE TITLE
DNS behaving oddly when using split-horizon nameservers in /etc/resolv.conf

### ISSUE THREAD

**Issue by jkinkead** [kubernetes/kops#2546]
We have a 1.6 cluster set up using [the newest `kube-dns` configuration](https://github.com/kubernetes/kops/blob/6201e924c7559148cdd10e54a11c6479a9e95a60/upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template).

When we run this in AWS, we see occasional DNS failures when looking up internal domains. I have traced this to our `/etc/resolv.conf` file, which looks something like:

```
nameserver 10.16.0.4
nameserver 8.8.8.8
search internal-name us-west-2.compute.internal
```
This is configured via DCHP in our subnet  (we're using a shared subnet for our cluster).

The problem we're having is that `dnsmasq` by default uses a nondeterministic `/etc/resolv.conf` server to perform lookups - which is NOT the behavior used in `libc`. Because of this, we'll get occasional failures when looking up internal-only URLs - and worse yet, `dnsmasq` will *also* cache the negative responses from `8.8.8.8`, meaning we'll eventually get into a state where our DNS mostly won't resolve.

`dnsmasq` has a flag (`-o`) that makes it behave more like `libc`, in that it will try the nameservers in-order, instead of randomly. I have a patch for this I'll submit in a moment.

(I first reported this issue as https://github.com/kubernetes/dns/issues/85, before I realized this was related to the configuration used).

**Comment by justinsb** [comment]
Commented on the PR, but will comment here also:

According to https://github.com/kubernetes/dns/issues/85#issuecomment-301224997 , the recommended fix is simply not to have both DNS servers.  Most likely you just want the AWS VPC DNS server (.4 in your case)

**Comment by jkinkead** [comment]
I think this is generally correct. I really don't like the failure behavior here, though: Inconsistent / unpredictable failures are not fun . . . although they might be expected with our DNS setup. We've been running with this setup for years without issue, though, so it seems like *most* systems handle DNS sequentially.

As I mentioned in the related PR, maybe `kops` should configure `kube-dns` via the ConfigMap?
