### ISSUE TITLE
allow adding custom data to userdata

### ISSUE THREAD

**Issue by vinayagg** [kubernetes/kops#2553]
It seems that multiple people on slack have looked for a way to append to default userdata being generated. 
We also have the same need. It would be good if we can supply a file that gets appended to userdata.

**Comment by chrislovecnm** [comment]
Have you looked at the hooks functionality? Examples are in the cluster spec documentation under docs.

It is not custom user data, but gives capability to run a container to do customizations.

**Comment by kaazoo** [comment]
The hooks functionality might not always suit for bre-baked AMIs. If your instance bootstrapping runs in cloud-init and requires specific user-data, then trying to achive that from a container after cloud-init is completed probably won't work.
