### ISSUE TITLE
Buildsystem tweak proposal: Make "help" the default Makefile target

### ISSUE THREAD

**Issue by WillemMali** [kubernetes/kops#2557]
Hey, I have a proposal for changing the default Makefile target from `kops` (build and install `kops`) to a the Makefile's help. My reasons for this are:

* Although it is reasonable and expected for a Makefile to build something, it's not standard to install something.
* `make install` or `make kops` aren't significantly harder to type than `make` (especially seeing how build times are 10+ seconds and thus you probably won't have to type this more often than every 10 seconds)
* It would make the Makefile easier to use; it would literally explain itself when you call it.
* It would make the build system friendlier to new contributors.
* It would make the new `help` target natural to discover for existing contributors.

I'm currently writing a PR to add the `help` target, which lists all targets and formats them nicely. Should I also change the default target in that PR, or should I do that in a separate PR?

**Comment by WillemMali** [comment]
We now have a decent `help` command implementation [implemented](https://github.com/kubernetes/kops/pull/2558), so if we decide to go with `help` as the default target it's a 1-line PR.

**Comment by chrislovecnm** [comment]
@WillemMali admittedly changing the default target would drive me nuts, this dog is trained on using the default target.  Any other options?

**Comment by WillemMali** [comment]
@chrislovecnm The other option is "No.", it doesn't really matter, it's just my preference to design interfaces (like those exposed by Makefiles) very explicitly and with a proclivity for safety and inaction.
