### ISSUE TITLE
AWS pod to pod communication with 100.96.x.x/24

### ISSUE THREAD

**Issue by AnthonyWC** [kubernetes/kops#2564]
I see from here https://github.com/kubernetes/kops/issues/1458 that the 100.64.0.0/10 is a network range that k8 uses and in one of my pod setup with a non-default namespace, I got two 100.96.x.x/24.

According to https://github.com/kubernetes/community/blob/master/contributors/design-proposals/networking.md, should I not have pod to pod communication within this namespace between the 2 different subnets?

Also why was 100.96.x.x/24 chosen and is this documented anywhere?  Does the cloud provider backend matters?  In my case it is AWS, would things be different /w say, GCP?

**Comment by caseydavenport** [comment]
@AnthonyWC there isn't a default "k8s" range - the value is configurable on the controller-manager using `--cluster-cidr`.  

My guess is that your cluster is configured to use `100.96.0.0/16` for pods which is why you're seeing the two `/24s` within that range.

**Comment by kenden** [comment]
Related https://github.com/kubernetes/kops/issues/1738
