### ISSUE TITLE
Kops should not create multiple ASGs for master nodes when using single AZ

### ISSUE THREAD

**Issue by milosradovanovic** [kubernetes/kops#2568]
Currently if I specify that I want 3 master nodes in 1a AZ. Kops will create three ASG's. Ideally it should create one with 3 nodes inside it. 

Current logic is good when we want to deploy to multi AZ's.

**Comment by lbrictson** [comment]
Question:  Why not use 3 ASG's?  They will recover faster and also I believe they are needed to specify the EBS volume to mount to the specific instance inside the launch config, so they are most likely required.
