### ISSUE TITLE
Missing `socat` from fresh CentOS cluster

### ISSUE THREAD

**Issue by Cisneiros** [kubernetes/kops#2577]
Hi people.

I've created a few Kubernetes clusters using `kops`, based on the CentOS 7 AMI. I've come to notice all my clusters are missing `socat` and, as a consequence, I cannot do `kubectl port-forward`.

I've had to manually install `socat` on my existing instances. Since I have a tool that does some configuration on every new EC2 instance I create, I've configured it to install `socat` on them as well. But I do believe this to be a bug (or feature absence).

For the record, this is the [relevant part of the] command I'm using to create clusters:

```kops create cluster \
    --cloud aws \
    --image ami-6d1c2007 \
    --kubernetes-version 1.5.4
```

Any thoughts?
Thanks!

**Comment by chrislovecnm** [comment]
We had the same problem with CoreOS, so this is a problem on Centos as well.

Thanks for the report!

**Comment by raghu67** [comment]
Is there a preference on how the missing socat should be added? Should it simply be added to the list of pre-reqs kops installs (kops/nodeup/pkg/model/packages.go) or should this be done by running kubelet in a container (https://github.com/kubernetes/helm/issues/1371)?

**Comment by chrislovecnm** [comment]
kops/nodeup/pkg/model/packages.go or use the custom version we have for CoreOS if there is not a package.

**Comment by chrislovecnm** [comment]
This should be fixed now in master.  Closing
