### ISSUE TITLE
rolling update when changing instance type in a group

### ISSUE THREAD

**Issue by pierreozoux** [kubernetes/kops#2578]
The rolling update could be a bit smarter.

My use case: I changed the instance type from a small to a larger on.
The roling update did the following:
 - deleting a node
 - adding a node

I think, it would be better if it first add nodes, and then delete them (one by one is fine).
This way there is less risk of a downtime due to lack of resources.

**Comment by chrislovecnm** [comment]
This is a duplicate issue, see https://github.com/kubernetes/kops/issues/1718

Can we close?
