### ISSUE TITLE
Unable to add additional master nodes to existing cluster

### ISSUE THREAD

**Issue by AlexeyAtIgloo** [kubernetes/kops#2579]
kops version `Version 1.6.0-beta.1 (git-77f222d)`

Following this guide to increate number of master nodes:
https://github.com/kubernetes/kops/blob/release-1.6/docs/single-to-multi-master.md

On step 2.b. when I update cluster config to reference new etcd member and upon saving getting this error:
`error populating cluster spec: There should be an odd number of master-zones, for etcd's quorum.  Hint: Use --zones and --master-zones to declare node zones and master zones separately.`

I believe this check is should not happen when I'm in process of adding new etcd nodes. Is these a way to force save configuration ignoring validation?

Thanks!

**Comment by chrislovecnm** [comment]
We have updated docs for this. Is this resolved?

**Comment by unixhat** [comment]
Is this resolved?

**Comment by AlexeyAtIgloo** [comment]
Thanks! Sorry missed 1st reply. I see the change where 3rd non existing member added to the config to avoid the error. I will re-try this process bit later, closing for now.
