### ISSUE TITLE
/home/admin/.kube directory is missing executable and write perms

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2580]
We had a PR come in recently for setting the .kube folder, and we missed wx perm on ~admin/.kube

I have recreated this problem on head.

**Comment by justinsb** [comment]
Can you provide more details?

On my machine:

```
> mv ~/.kube ~/.cube
> kops export kubecfg <mycluster>
> ls -la ~/ | grep kube
drwxr-xr-x 1 justinsb justinsb        12 May 16 18:02 .kube
```

**Comment by justinsb** [comment]
Oh ... this is https://github.com/kubernetes/kops/pull/2523/files ?

**Comment by chrislovecnm** [comment]
Yep

**Comment by chrislovecnm** [comment]
@dolftax if you have a chance to address?

**Comment by chrislovecnm** [comment]
@dolftax have a PR in already.

**Comment by dolftax** [comment]
https://github.com/kubernetes/kops/pull/2587/files LGTM.
