### ISSUE TITLE
AWS: --hostname-override used with kubelet, but not kube-proxy (isLocal check fails)

### ISSUE THREAD

**Issue by blueyed** [kubernetes/kops#2584]
With the AWS provider, kubelet uses `--hostname-override` with the hostname from the meta-data service (http://169.254.169.254/latest/meta-data/local-hostname) ([source](https://github.com/kubernetes/kops/blob/c7e2aa1b062b88c097a7b8e11b03ff4dfd9c9d58/pkg/model/components/kubelet.go#L140-L152)).

This uses the fully qualified hostname, e.g.: ip-172-X-Y-Z.REGION.compute.internal, while running `hostname` itself will only return `ip-172-X-Y-Z`.

`kube-proxy` compares the NodeName to the hostname for the `isLocal` property (https://github.com/kubernetes/kubernetes/blob/b353700bfc1ee95b8f9f827c9cc818cf2ab3f943/pkg/proxy/iptables/proxier.go#L794), which is used with `service.beta.kubernetes.io/external-traffic: "OnlyLocal"`.

Changing the hostname to be fully qualified via the `hostname` command and restarting `kube-proxy` (by killing it) fixes the isLocal detection.

It seems like the `isLocal` change should get changed/improved in Kubernetes itself maybe, but for the current state and in general `kube-proxy` should use the same hostname, which means to use `--hostname-override` there also, if it is used for `kubelet`.

**Comment by blueyed** [comment]
Using hostname-override was added in https://github.com/kubernetes/kops/commit/9c2f92f289cc7ebbd8f4506f0410a34715bb04e7.

The commit message sounds like it might not be necessary anymore at all maybe?! /cc @justinsb

**Comment by justinsb** [comment]
cc @thockin for questionable kube-proxy logic: the hostname is not the NodeName.

Does kube-proxy have that flag today?  If so I agree that we should pass it in kops.

**Comment by blueyed** [comment]
> Does kube-proxy have that flag today?

IIRC, yes.
See also the commented code in componentconfig: https://github.com/kubernetes/kops/blob/c7e2aa1b062b88c097a7b8e11b03ff4dfd9c9d58/pkg/apis/kops/componentconfig.go#L352-L353

**Comment by justinsb** [comment]
That's good news :-)

**Comment by blueyed** [comment]
btw: this is where kube-proxy ends up when finding no local endpoints: https://github.com/kubernetes/kubernetes/blob/b353700bfc1ee95b8f9f827c9cc818cf2ab3f943/pkg/proxy/iptables/proxier.go#L1399-L1409 - adding a blackhole iptables rule ("has no local endpoints").

**Comment by murali-reddy** [comment]
So whats possible fix here, are we going to use --hostname-override for both kubelet and kube-proxy? Also is there a  workaround. I just can not get the kube-proxy to work 

± kubectl get nodes
NAME                                          STATUS         AGE       VERSION
ip-172-20-51-2.us-west-2.compute.internal     Ready,node     1h        v1.6.2
ip-172-20-55-216.us-west-2.compute.internal   Ready,node     1h        v1.6.2
ip-172-20-61-204.us-west-2.compute.internal   Ready,master   1h        v1.6.2
===================Kube-proxy logs =======================
W0528 22:32:42.648040       6 server.go:469] Failed to retrieve node info: Get https://api.internal.mycluster.aws.cloudnativelabs.net/api/v1/nodes/ip-172-20-51-2: dial tcp 203.0.113.123:443: i/o timeout
W0528 22:32:42.648160       6 proxier.go:293] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP
I0528 22:32:42.648182       6 server.go:249] Tearing down userspace rules.
E0528 22:33:12.657763       6 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:46: Failed to list *api.Service: Get https://api.internal.mycluster.aws.cloudnativelabs.net/api/v1/services?resourceVersion=0: dial tcp 203.0.113.123:443: i/o timeout
E0528 22:33:12.657829       6 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: Get https://api.internal.mycluster.aws.cloudnativelabs.net/api/v1/endpoints?resourceVersion=0: dial tcp 203.0.113.123:443: i/o timeout
E0528 22:33:43.658428       6 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:46: Failed to list *api.Service: Get https://api.internal.mycluster.aws.cloudnativelabs.net/api/v1/services?resourceVersion=0: dial tcp 203.0.113.123:443: i/o timeout
E0528 22:33:43.659878       6 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: Get https://api.internal.mycluster.aws.cloudnativelabs.net/api/v1/endpoints?resourceVersion=0: dial tcp 203.0.113.123:443: i/o timeout

**Comment by thockin** [comment]
Sounds like a reasonable change - can someone get me a PR in the next 3 days?

**Comment by chrislovecnm** [comment]
Super simple coding, will need to be tested.

Does the kube-proxy flag need to be on by default.

**Comment by chrislovecnm** [comment]
To be clear simple changes with kops. Changing core, have not scoped.
