### ISSUE TITLE
RBAC error when applying ingress-nginx/v1.6.0.yaml

### ISSUE THREAD

**Issue by waltisfrozen** [kubernetes/kops#2591]
When I try to install the ingress-nginx on a new cluster that doesn't have RBAC configured, I get the following error : 

> namespace "kube-ingress" created
> service "nginx-default-backend" created
> deployment "nginx-default-backend" created
> configmap "ingress-nginx" created
> service "ingress-nginx" created
> deployment "ingress-nginx" created
> serviceaccount "nginx-ingress-controller" created
> clusterrolebinding "nginx-ingress-controller" created
> Error from server (Forbidden): error when creating "v1.6.0.yaml": clusterroles.rbac.authorization.k8s.io "nginx-ingress-controller" is forbidden: attempt to grant extra privileges: [{[get] [] [nodes] [] []} {[list] [] [nodes] [] []} {[watch] [] [nodes] [] []} {[get] [] [pods] [] []} {[list] [] [pods] [] []} {[watch] [] [pods] [] []} {[get] [] [endpoints] [] []} {[list] [] [endpoints] [] []} {[watch] [] [endpoints] [] []} {[get] [] [services] [] []} {[list] [] [services] [] []} {[watch] [] [services] [] []} {[get] [] [secrets] [] []} {[list] [] [secrets] [] []} {[watch] [] [secrets] [] []} {[get] [] [configmaps] [] []} {[list] [] [configmaps] [] []} {[watch] [] [configmaps] [] []} {[create] [] [events] [] []} {[create] [] [endpoints] [] []} {[update] [] [endpoints] [] []} {[update] [] [services] [] []} {[get] [extensions] [ingresses] [] []} {[list] [extensions] [ingresses] [] []} {[watch] [extensions] [ingresses] [] []} {[update] [extensions] [ingresses/status] [] []}] user=&{admin admin [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
>

**Comment by jurgenweber** [comment]
yeah, I get this also.

**Comment by BradErz** [comment]
This was fixed by: https://github.com/kubernetes/kops/pull/2896 

Can be closed @chrislovecnm
