### ISSUE TITLE
Better error message on bad state store

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kops#2593]
When the user supplies an invalid `KOPS_STATE_STORE`, kops should mention this.

Currently, kops simply remarks that the "cluster" cannot be found.

**Comment by chrislovecnm** [comment]
What command is giving you this?  The command is not using the code path that gives a good message :)

**Comment by olemarkus** [comment]
To my knowledge, kops will give appropriate errors in all cases when the state store is set incorrectly.

/close
