### ISSUE TITLE
Test new Calico versions

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2598]
Someone needs to test this https://github.com/kubernetes/kops/pull/2590

cc: @blakebarnett

**Comment by mad01** [comment]
@chrislovecnm i have tested to create a cluster with that merge included using this command from #2589

**Comment by chrislovecnm** [comment]
Thanks!

**Comment by blakebarnett** [comment]
Our clusters came up cleanly with this as well, sorry for being slow :)
