### ISSUE TITLE
add kube-router support

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kops#2606]
Reading [this](https://cloudnativelabs.github.io/post/2017-05-10-kube-network-service-proxy/) article, kube-router seems a better choise than kube-proxy in many situations, specially if you have a kube with lots of services deployed (we have one at TFG Co)

I guess adding support for using it in Kops would be very valuable.

[kube-router](https://github.com/cloudnativelabs/kube-router)

**Comment by murali-reddy** [comment]
Authour of [kube-router](https://github.com/cloudnativelabs/kube-router) here. If there is enough interest for IPVS backed alternative of Kube-proxy I am willing to add support in Kops.

**Comment by murali-reddy** [comment]
Kube-router author here. If there are no objection i would like to get this option of IPVS based service proxy alternative to Kube-proxy into Kops.

Like @felipejfc mentioned there are advantages using IPVS, and community gets a chance to try alernative.

**Comment by felipejfc** [comment]
that would be very nice @murali-reddy

**Comment by michaelajr** [comment]
Interesting. We definitely have had lots of issues (and problems debugging) with all the moving parts of K8s networking. We currently use Weave with kube-proxy. Really interested in this.

**Comment by murali-reddy** [comment]
@felipejfc @michaelajr I have intergration with Kops ready. I will raise a PR to get the changes merged in kops. Just in case you want to try patched version of kops please see the instructions

https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/kops.md

**Comment by michaelajr** [comment]
Oh wow. We'll dig in. Thanks!
