### ISSUE TITLE
No support for configuring with existing AWS Subnets in a VPC?

### ISSUE THREAD

**Issue by kevin-cantwell** [kubernetes/kops#261]
I initially commented on this subject here: https://github.com/kubernetes/kops/issues/232#issuecomment-237261983

> It would greatly improve our likelihood of adopting kubernetes if we could create a cluster in existing subnets. Not being able to specify existing subnets in a VPC means that our kubernetes cluster is completely cut off from existing infrastructure and the only path for adoption is a big-bang switch from not using it anywhere to using it everywhere, which is a risky enough path to cause us not to adopt k8s at all.

If there _is_ a way to specify existing subnets, great! Otherwise, this is a deal-breaker for us @timehop. We need our k8s clusters to be able to speak to legacy infrastructure that is not managed by k8s and that means subnet-reuse.

Also of concern is that we noticed existing resources (such as VPCs) would be renamed. This might seem innocuous, but it's rather alarming to us as we are very wary of any tool that modifies existing resources, even if it's just their tags.

**Comment by chrislovecnm** [comment]
@kevin-cantwell yes there are ways to do this.  Sorry we have taken so long to get back to you, but let me know ...  Otherwise we can close this.

**Comment by kevin-cantwell** [comment]
Feel free to close. And although I'm not actively pursuing k8s atm, I would certainly be interested in learning how to specify existing subnets.

**Comment by justinsb** [comment]
Docs are here: https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md

Running in the same subnet is high risk with VPC routing, less so with weave.  And I think we're tracking the tagging issues elsewhere.
