### ISSUE TITLE
Master nodes missing /etc/cni/net.d/10-weave.conf

### ISSUE THREAD

**Issue by jwhitcraft** [kubernetes/kops#2619]
I recently did an upgrade from 1.5.7 to 1.6.2 using kops 1.6.0 and one of my three masters came up just fine, but the other two were reporting: 

```
runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

after some digging, i found that the file `/etc/cni/net.d/10-weave.conf` was missing and when i added it with 
```
{
    "name": "weave",
    "type": "weave-net"
}
```

and restarted docker, then master came online just fine.

The commands I ran to upgrade the cluster were

```sh
kops upgrade cluster
kops upgrade cluster --yes
kops update cluster
kops update cluster --yes
kops rolling-update cluster
kops rolling-update cluster --yes
```

And the rolling update completed just fine.

**Comment by chrislovecnm** [comment]
Did you file an issue with weave? Which version of weave was not starting?

@bboreham ideas?

**Comment by jwhitcraft** [comment]
@chrislovecnm I was on K8S 1.5.7 which i'm assuming has weave 1.9.4 already so, it didn't run the upgrade for weave when i upgraded the cluster to 1.6.2

**Comment by bboreham** [comment]
> the file /etc/cni/net.d/10-weave.conf was missing

This is supposed to be written out when the Weave Net pod first runs.  So to diagnose that, look at the logs from the `weave` container within that pod.

**Comment by jwhitcraft** [comment]
So, that may have been the problem, since Weave never got updated, the pods never got scheduled on that host because of the taints for it being a master, Once i updated the DaemonSet for Weave to include the tolerance for the master nodes, the Weave pods were places, but I had already created that file and restarted docker.

**Comment by gugahoi** [comment]
Ran into the same problem here. The solution for me was to delete and recreate the Weave-net daemon set. I don't understand why kops didn't update weave to the latest version (stayed at 1.9.4 instead of 1.9.7) and why it failed to "reschedule" it after updating Kubernetes to 1.6.4. Is there documentation on how to update/upgrade things?
