### ISSUE TITLE
Master Disk size

### ISSUE THREAD

**Issue by nottix** [kubernetes/kops#2631]
Hi,

we have a problem with Master node on AWS cluster.
Is it possibile to increase disk size of running master node? And how?

Thank you.

**Comment by jwhitcraft** [comment]
You should be able to follow this doc and just substitute `nodes` with the name of your master

https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#changing-the-root-volume-size-or-type

**Comment by nottix** [comment]
Thank you @jwhitcraft, this procedure mantains the previous data or erases it?

**Comment by jwhitcraft** [comment]
@nottix yes, the rolling upgrade will only take on master offline at a time.

**Comment by chrislovecnm** [comment]
To add some clarity, rolling update destroys masters / nodes. You will need to increase your disk size manually or backup the data.

**Comment by nottix** [comment]
Ok thank you guys
