### ISSUE TITLE
+DrainAndValidateRollingUpdate possibly broken with flannel

### ISSUE THREAD

**Issue by apenney** [kubernetes/kops#2633]
I'm not sure if this is related but I just did a rolling-update of a cluster and 0 nodes worked afterwards.  This was the first time I've used +DrainAndValidateRollingUpdate and it failed to put down `/etc/cni/net.d/10-flannel.conf` on ANY box.  My cluster was completely broken after the update.

**Comment by apenney** [comment]
Kops 1.6.0 and kubernetes 1.6.4 btw.

**Comment by chrislovecnm** [comment]
Does a rolling update without the feature flag change the behavior?

The new nodes are being created via the launch config of the asg, and the cordon and drain functionality is far away from that code. 

Have you been able to recreate?

**Comment by chrislovecnm** [comment]
@apenney can we close this?
