### ISSUE TITLE
Reflect release notes in docs

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2637]
e.g. https://github.com/kubernetes/kops/blob/master/docs/releases/1.6.0-alpha.1.md

Feedback from jaygorrell on slack was that this was a good thing.

The majority of the work here is compiling the release notes, and we're doing that in the github release notes anyway.  We might as well put that into the docs folder also.

**Comment by justinsb** [comment]
Also rationalize with CHANGES.md etc

**Comment by chrislovecnm** [comment]
Can we close?

**Comment by chrislovecnm** [comment]
Closing as we have fixed the docs
