### ISSUE TITLE
Look into switching calico to use kubernetes backend by default.

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#2639]
This would remove the requirement to open up etcd to all nodes.

**Comment by chrislovecnm** [comment]
cc @caseydavenport

**Comment by caseydavenport** [comment]
Yep! This was intended from the beginning of the integration.

At the moment, switching to the kubernetes datastore driver (kdd) would give some limitations compared to the etcd datastore.  Namely:
- Missing support for some of Calico's advanced policy functions (egress, cidrs, ordering).
- Missing support for some of Calico's advanced BGP functions (topology configuration, RRs).

We're actively working on closing those gaps, but I wouldn't want to remove etcd-based Calico until that was done.  Perhaps this can be done in a way where it's opt-in for users who don't mind the above limitations?

CC @ozdanborne @heschlie

**Comment by heschlie** [comment]
I recall reading there was some talk about cleaning up or redoing some of the work related to passing in CLI flags (I could be remembering wrong having trouble finding where I read it) but we could take advantage of that and add an additional flag related to `--networking calico` that would let you select the datastore to use, something like `--networking calico --calico-datastore kubernetes`?

**Comment by blakebarnett** [comment]
It would be interesting to find out if any kops users are making use of the advanced features, if not it would make sense to me to switch the default to the kubernetes backend, and have the etcd back-end be the more advanced opt-in option.  Unless people are aware that any pod can access etcd unrestricted it might be an unpleasant surprise after they've deployed workloads.

**Comment by chrislovecnm** [comment]
Initially, lets have the option to use it.  If we default to a new option, we have to test how upgrades and downgrades work.  Which can be a lot of work.

@heschlie I would like to see flags for this functionality in a cluster spec API object rather yet another CLI flag.  We have sooooo many now.

**Comment by heschlie** [comment]
@chrislovecnm That seems like a good plan, I'll see what I can do!

**Comment by blakebarnett** [comment]
@heschlie are you working on this already?  If not I may take a stab at it (probably not until next week though)

**Comment by heschlie** [comment]
@blakebarnett I have not made any real progress on it, please feel free to have a go at it and if you could keep myself and @ozdanborne in the loop?

**Comment by chrislovecnm** [comment]
@caseydavenport what is the status of the support using API?

**Comment by caseydavenport** [comment]
@chrislovecnm the feature set that's supported in the k8s datastore driver vs etcd is changing pretty quickly.  In the next Calico release we're adding BGP configuration feature parity.  Beyond that there are still some policy features, ipam, configuration knobs, etc that haven't been ported yet (but may or may not be worth holding off adding to kops for).

**Comment by edlee2121** [comment]
"At the moment, switching to the kubernetes datastore driver (kdd) would give some limitations compared to the etcd datastore."

Looks like all feature are supported now.
https://github.com/projectcalico/calico/issues/458

**Comment by caseydavenport** [comment]
@edlee2121 There's still one more bit of work, tracked here: https://github.com/projectcalico/calico/issues/355

The issue you linked was tracking full policy feature parity.

**Comment by edlee2121** [comment]
Thanks, it will be good not to expose etcd more than needed.

**Comment by mauilion** [comment]
@caseydavenport the remaining calico_ipam thing is really just support for ippools? or am I missing something?

So excited to see this integrated as it greatly simplifies the model!

**Comment by caseydavenport** [comment]
> So excited to see this integrated as it greatly simplifies the model!

Agreed :)

It's not just IP pools - it's the full IP allocation schema supported by Calico with etcd. It gives more flexible IP allocation capabilities than the host-local plugin supports.

I will think some more, it might be that this is an OK limitation for kops, but I haven't thought about it enough yet.
