### ISSUE TITLE
AWS uses AWS_PROFILE

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#264]
AWS switched their env variables in a non backwards compatible way:
https://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs

We should probably warn if AWS_DEFAULT_PROFILE is set but not AWS_PROFILE, or something along those lines.

**Comment by chrislovecnm** [comment]
Documentation??

**Comment by kris-nova** [comment]
What would a warning look like? Should it break?

**Comment by justinsb** [comment]
It's in the docs, but it's an easy mistake to make, hence the desire for a warning

pseudocode:

```
if os.Getenv("AWS_DEFAULT_PROFILE") != "" && os.Getenv("AWS_PROFILE") == "" {
  fmt.Fprintf(os.Stderr, "You have AWS_DEFAULT_PROFILE set, but not AWS_PROFILE.  kops will only use the AWS_PROFILE environment variable\n")
}
```

**Comment by juliaaano** [comment]
It would be nice to update the README file to let the reader know he can use AWS_PROFILE in addition to:

```
export AWS_ACCESS_KEY_ID=<access key>
export AWS_SECRET_ACCESS_KEY=<secret key>
```
