### ISSUE TITLE
Calico no longer spins up with NAT outgoing enabled.

### ISSUE THREAD

**Issue by ottoyiu** [kubernetes/kops#2647]
PR #2590 removed the `configure-calico` job which set `nat-outgoing` to true. Without that, pods will not have external internet access. This behaviour is not desired nor expected as part of the change.

**Comment by lsjostro** [comment]
@ottoyiu with calico >2.1 nat-outgoing is enabled by default. 
see https://github.com/projectcalico/calicoctl/issues/1579#issuecomment-289000461

**Comment by ottoyiu** [comment]
@lsjostro thanks for the link :+1: it's weird that my ip pool's nat was set to false. I will double check by spinning up a new cluster to see if that's the case.

**Comment by ottoyiu** [comment]
Going to close this for now, as nat-outgoing does seem to be enabled. Going to open a ticket in Calico's project instead.
