### ISSUE TITLE
Create instance group inside public subnet when using private topology

### ISSUE THREAD

**Issue by mattdonnelly** [kubernetes/kops#2648]
I'm working with a few services that make a lot of requests to the internet. At the moment because our cluster was created using a private topolgy these services are scheduled onto worker nodes which live in the private subnet and all of this traffic will go through the NAT gateway. NAT gateway traffic is extremely expensive so we'd ideally we like to schedule these services on nodes inside a public subnet and use an Internet Gateway. I'm not sure what the best way to go about this is though – Would this be a case where we should create the VPC and subnets ourselves and manually select which subnets each instance group uses? Or is there alternative approach I'm missing?

Sidenote: Thanks for all the work on this amazing tool. It's been a massive help to us 😃

**Comment by mattdonnelly** [comment]
Has anyone looked at this?

**Comment by chrislovecnm** [comment]
I am not sure I have a solution for you with the current kops options. We have undocumented support for mixed private and public nodes, but I do not think that helps you. We need some form of a nat regardless.

@hubt any ideas?

**Comment by hubt** [comment]
I think it should be possible. If you have a cluster with a NAT and public and private subnets, then you can create a new instance group within the utility subnet. Then you can taint the public instance group with a key, put a toleration on the pods with the same key, finally use a `nodeSelector` on the pods selecting the utility subnet to force the pods onto the utility subnet.

Never done it, but should work in theory.

**Comment by mattdonnelly** [comment]
@hubt That sounds perfect - thanks for your help. I'll let you know how it goes
