### ISSUE TITLE
master should be labeled

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#265]
Now that master nodes are schedulable (yay! thank you!), they should have a label on them that is stable across autoscale events.

This allows things like EIP controllers to be scheduled on the master only in fairly obvious way.

Currently, if the master is labeled, and it autoscales, the label does not persist.

**Comment by justinsb** [comment]
The master is now labelled.  The label is currently `kubernetes.io/role=master`, but note that this might change to be something like `node-role.kubernetes.io/master=true` in https://github.com/kubernetes/kubernetes/pull/39112

We'll likely continue to have both labels for the foreseeable future in kops.
