### ISSUE TITLE
no such host on cluster validation

### ISSUE THREAD

**Issue by WillemMali** [kubernetes/kops#2651]
`cannot get nodes for "development.edly.biz": Get https://api.development.edly.biz/api/v1/nodes: dial tcp: lookup api.development.edly.biz on 192.168.1.1:53: no such host`

I routinely spin up/tear down my clusters, and often cluster creation fails with the above error message.

If cluster creation does succeed it only takes about 5 minutes from to go through `delete -> create -> replace -> update -> upgrade -> rolling-update`, like here:

```
Start date:   Mon May 29 12:18:51 CEST 2017
Current date: Mon May 29 12:23:24 CEST 2017
```

**Comment by WillemMali** [comment]
My clusters also go down randomly during `kubectl apply` actions:

```
cannot get nodes for "development.edly.biz": Get https://api.development.edly.biz/api/v1/nodes: net/http: TLS handshake timeout
```

I'm on kops `Version 1.6.0 (git-f69a313)` and kubectl:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by robinpercy** [comment]
@WillemMali can you please share the full command/params you're using to create the cluster? It would be helpful to see instance sizes, network provider, topology, etc.

**Comment by chrislovecnm** [comment]
bump

**Comment by chrislovecnm** [comment]
Closing, please let us know if you still need help
