### ISSUE TITLE
Custom metrics support

### ISSUE THREAD

**Issue by 23doors** [kubernetes/kops#2652]
Is there any way to enable 1.6 custom metrics with kops?

As it is specified on: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
> In order to use custom metrics in the Horizontal Pod Autoscaler, you must deploy your cluster with the --horizontal-pod-autoscaler-use-rest-clients flag on the controller manager set to true.

Any way to make this happen with kops? Or is it preferable to edit kube-controller pod directly? Or maybe even install kubeadm after creating cluster?

**Comment by chrislovecnm** [comment]
We do not have this out of the box. It would need to be added here

https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go

How to update the apis is in our developer docs if you are interested at all.

**Comment by Cisneiros** [comment]
I see there is mention to this flag on componentconfig.go:
https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L284

But when I try to add that to my ClusterSpec, I get:

```
# Found fields that are not recognized
# ...
#     cloudProvider: aws
#     configBase: s3://<redacted>
# +   enableCustomMetrics: true
#     etcdClusters:
#     - etcdMembers:
# ...
```

(Running kubernetes 1.6.4 and cops 1.6.2)

Is this supposed to work?

**Comment by chrislovecnm** [comment]
You might need to add it to the kubelet sections in the cluster manifest.

Do a get cluster -o yaml --full to view the sections. I have a PR open that talk more about editing and using the yaml btw.

kops get cluster -oyaml --full 

Should print out what I need.

**Comment by Cisneiros** [comment]
@chrislovecnm Thanks, I see the kubelet section! But how would I edit that section? Passing `--full` to `jobs edit cluster` gives me an error.

Should I just go to S3 and edit something by hand?

**Comment by chrislovecnm** [comment]
`--full` is purely a diagnostic option

See https://github.com/kubernetes/kops/pull/2795 for more information. May be easier moving to pure YAML.

**Comment by chrislovecnm** [comment]
We should probably add this to the clusterspec document since this is asked twice. I am going to close this as we have #1467 open.

**Comment by itskingori** [comment]
@23doors yes there's a way ... and @Cisneiros your config looks wrong (`enableCustomMetrics` should be under `kubelet`). I've included a caveats and an example in https://github.com/kubernetes/kops/issues/1467#issuecomment-318410867.

@chrislovecnm I think the issue people are having the one in the linked comment ☝️... which is an issue with the `resolvConf` attribute being set to `null` when undefined.

**Comment by antran89** [comment]
A LATE TO THE PARTY: (Hope it helps for new comers like me) I think there is a tutorial to do it:
https://github.com/kubernetes/kops/blob/master/docs/horizontal_pod_autoscaling.md#support-for-multiple-metrics
