### ISSUE TITLE
make test should unset env variables such as KOPS_BASE_URL

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2657]
running `make test` with certain variable set can cause failures.  We should unset all kops specific env variables before we test.

```
PROTOKUBE_IMAGE
NODEUP_URL
KOPS_BASE_URL
DNSCONTROLLER_IMAGE
KOPS_RUN_OBSOLETE_VERSION
ENV_VAR_CNI_VERSION_URL
```

To name a few. `os.Getenv` should be search for in the code base.

**Comment by rifelpet** [comment]
@chrislovecnm how would you suggest solving this? unexporting all of these variables in the `make test` ?

**Comment by chrislovecnm** [comment]
@rifelpet I think trying to unset the variables in the Makefile is a good start.  Also ran into `AWS_REGION` today as well.  We probably want to unset the general AWS evn variables.  The good news is that bazel does not have this problem, as it does not inherit the environment variables.  The plan is to eventually convert to bazel, but at this point, we are not quite there.
