### ISSUE TITLE
After recreating one of the masters cert is not valid any more

### ISSUE THREAD

**Issue by foobarto** [kubernetes/kops#2665]
Not sure if this is fixed in more recent versions. I've encountered this in v1.5.2

What happened: One of three master servers had to be terminated, ASG then created a replacement. The etcd EBS volumes were re-attached to the new instance and `kubectl get nodes` are reporting new master as Ready.

Every few requests to Kubernetes via kubectl (as the DNS does a round robin) when the fresh master instance responds kubectl returns following error:

```
Unable to connect to the server: x509: certificate is valid for kubernetes.default.svc, kubernetes.default, kubernetes, localhost, not api.<mydomain>.com
```
Where `<mydomain>` is the domain I'm using.

Also looking at the kube-apiserver logs on that instance I can see similar error:
```
I0531 00:17:15.368477       5 logs.go:41] http: TLS handshake error from 172.30.32.114:47128: remote error: tls: unknown certificate authority
```

**Comment by foobarto** [comment]
Somehow `/srv/kubernetes/server.cert` and `/srv/kubernetes/server.key` ended up being different than on other two master servers.

**Comment by foobarto** [comment]
Also when I've inspected the `cloud.spec` file I've noticed that the kube-apiserver is missing few entries comparing to older version on s3.

Things missing that I've noticed at a glance:
```
    clientCAFile: /srv/kubernetes/ca.crt
    tlsCertFile: /srv/kubernetes/server.cert
    tlsPrivateKeyFile: /srv/kubernetes/server.key
```

**Comment by foobarto** [comment]
Restoring older version of `cluster.spec` and rebooting affected instance fixed the issue!

**Comment by chrislovecnm** [comment]
Did you grab any logs off of the server?  Do you have versioning on in s3?

**Comment by foobarto** [comment]
Yes versioning is enabled on S3 bucket for kops state - rolling back to older version solved the issue after rebooting affected servers.

As for logs on the affected master only error visible in the logs was the one mentioned in OP. Master itself was reporting as Ready when querying `kubectl get nodes` (given kubectl didn't send that request to affected master that is). 

One more thing worth mentioning: rebooting one of the nodes caused it to never connect back to the cluster and logs were full of same error message as seen when using kubectl. 

I suspect that last time I've used `kops update --target=cloudformation` I may have used different version of kops than when the cluster was initially created. Even though I didn't run `kops update --yes` it did save some changes to S3. I remember this as this resulted in dns-controller updating itself soon after as mentioned here: https://github.com/kubernetes/kops/issues/2319

**Comment by chrislovecnm** [comment]
> Yes versioning is enabled on S3 bucket for kops state - rolling back to older version solved the issue after rebooting affected servers.

We need to turn that on automatically :)

Good information, no idea how to recreate :(  Lets keep this open and see if we can break it again.

So glad you are up and running again!

**Comment by dabdine-r7** [comment]
This just happened to me when upgrading from 1.5.2 to 1.7.5:

```
$ kubectl get pods
Unable to connect to the server: x509: certificate is valid for kubernetes.default.svc, kubernetes.default, kubernetes, localhost, not api.<mydomain>
```

 I ran `kops upgrade cluster` and it spit out a rather large diff.

Then ran:
```
$ kops update  cluster --yes
Using cluster from kubectl context: <mydomain>

I0906 13:54:01.320277   28186 executor.go:91] Tasks: 0 done / 72 total; 34 can run
I0906 13:54:01.954064   28186 vfs_castore.go:422] Issuing new certificate: "kube-proxy"
I0906 13:54:02.148013   28186 vfs_castore.go:422] Issuing new certificate: "master"
I0906 13:54:02.167864   28186 vfs_castore.go:422] Issuing new certificate: "kubecfg"
I0906 13:54:02.258196   28186 vfs_castore.go:422] Issuing new certificate: "kube-controller-manager"
I0906 13:54:02.272163   28186 vfs_castore.go:422] Issuing new certificate: "kubelet"
I0906 13:54:02.439030   28186 vfs_castore.go:422] Issuing new certificate: "kops"
I0906 13:54:02.849046   28186 vfs_castore.go:422] Issuing new certificate: "kube-scheduler"
I0906 13:54:03.093177   28186 executor.go:91] Tasks: 34 done / 72 total; 12 can run
I0906 13:54:03.556281   28186 executor.go:91] Tasks: 46 done / 72 total; 24 can run
I0906 13:54:05.054115   28186 executor.go:91] Tasks: 70 done / 72 total; 2 can run
I0906 13:54:05.302173   28186 executor.go:91] Tasks: 72 done / 72 total; 0 can run
I0906 13:54:05.302237   28186 dns.go:152] Pre-creating DNS records
I0906 13:54:05.875820   28186 update_cluster.go:247] Exporting kubecfg for cluster
```

So seems to be the same issue (certificate). Cluster is currently rebooting. One thought is that this may be timing related (cluster is still bootstrapping) though it had been about 25 minutes since I ran the upgrade with the same error.
