### ISSUE TITLE
Logic to extract kubernetes version from URL is fragile

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2676]
We currently recognize URLs that "look like" a kubernetes release URL and extract the kubernetes version here:
https://github.com/kubernetes/kops/blob/178f790942c4b8fc41da344d795610f96e776f47/pkg/apis/kops/util/versions.go#L27

However, this breaks whenever there is a version that we haven't yet hard-coded.

We should address this.   Ideas:

* Make the URL parsing logic generic
* Work with kubernetes/kubernetes to include a version-information file in releases
* Have our tests explicitly specify the kubernetes version (though I think this just punts the problem to test-infra)
* Others?

cf
https://github.com/kubernetes/kubernetes/issues/46853
https://github.com/kubernetes/kops/pull/2675

Thanks @liggitt for the heads up!

**Comment by ixdy** [comment]
The `kubernetes.tar.gz` tarball contains a `version` file which is just the semver, though you'd need to download it and extract it.

Maybe use a regex to look for semver-like things in the URL, e.g. `v([0-9]+)\.([0-9]+)\.`?
