### ISSUE TITLE
FR: Cli options to set root volume size on cluster creation

### ISSUE THREAD

**Issue by matthew-marchetti** [kubernetes/kops#2678]
Following up on this issue: https://github.com/kubernetes/kops/issues/924

Why would we not provide a cli option with something like this? 
kops create cluster --master-volume-size=200

Assuming a production setup, the 20gb default is way too small. I've seen multiple people bring up this opinion, and it seem's like this feature would provide a lot of flexibility and value. Having to edit after creation is error prone and manual. Creating the cluster from a pre-made yaml file removes a lot of the benefits to using KOPS in the first place.

Is there a reason we would not want the option to be configurable at creation time?

**Comment by chrislovecnm** [comment]
This may be one of the few new cli options that I would agree with adding. We are trying to limit new options as we have so many already. As you mentioned this option is accessible via using yaml, which many of our users utilize. 

We are always happy to have new contributions, if you want to take stab at adding these.

**Comment by chrislovecnm** [comment]
Closing as https://github.com/kubernetes/kops/pull/2680 implemented
