### ISSUE TITLE
kops validate has bad UX during cluster launch

### ISSUE THREAD

**Issue by danopia** [kubernetes/kops#2679]
Originally from https://github.com/kubernetes/kops/issues/1386#issuecomment-293413269

kops initially assigns a placeholder IP `203.0.113.123` for the api DNS record. The masters update this record once they are ready. The problem is that `kops validate`, the next command you're told to run after launching a cluster, doesn't know this and waits for a response timeout before erroring.

```
$ kops validate cluster
Using cluster from kubectl context: test-cluster.example.com

Validating cluster test-cluster.example.com


cannot get nodes for "test-cluster.example.com": Get https://api.test-cluster.example.com/api/v1/nodes: dial tcp 203.0.113.123:443: i/o timeout
```

As a first-time user I googled that IP and ended up on #1386 writing a comment. It would be much nicer UX if kops immediately noticed the placeholder IP and informed the user that a master has not come up yet.

**Comment by chrislovecnm** [comment]
One improvement that was thought of was to make a dns lookup call before calling the k8s client. That way we could gracefully handle the above mentioned error message.

**Comment by jvalencia** [comment]
Just landed here after scratching my head for a while -> there's no notice that there's a dummy ip.  It would be nice to add a note in the documentation as well.

**Comment by shavo007** [comment]
I got stuck on this aswell. How long do you have to wait for!?

**Comment by chrislovecnm** [comment]
@shavo007 `dnscontroller` deployment on the master updates the DNS records.  So usually the wait time is under 5 minutes.

**Comment by shavo007** [comment]
Good to know. What logfile can I inspect to monitor this activity?

**Comment by chrislovecnm** [comment]
@shavo007 dnscontroller container log or deamon.log

**Comment by chrislovecnm** [comment]
@alrs this was the issue that I mentioned

**Comment by danopia** [comment]
I just created another cluster for the first time since I created this issue.

>The dns-controller Kubernetes deployment has not updated the Kubernetes cluster's API DNS entry to the correct IP address.  The API DNS IP address is the placeholder address that kops creates: 203.0.113.123.  Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate.  The protokube container and dns-controller deployment logs may contain more diagnostic information.  Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to start.

Looks like this issue is actually fixed! It's a bit of a wall of text now, but says what's going on.

:+1:
