### ISSUE TITLE
aws-iam: Add autoscaling:DescribeTags

### ISSUE THREAD

**Issue by magnusboman** [kubernetes/kops#2681]
Latest versions of the cluster-autoscaler can automatically detect the ASG used by the nodes, but it requires that  `autoscaling:DescribeTags` rights are added to the AWS IAM policy.

**Comment by felipejfc** [comment]
+1

**Comment by chrislovecnm** [comment]
I think we have this fixed. Need to check

/assign

**Comment by johanneswuerbach** [comment]
Looking into kops v1.8.0, `autoscaling:DescribeTags` seems not be included yet:
Legacy:
https://github.com/kubernetes/kops/blob/fbfe24afd96790b8470cf370dbe452353074a8b7/pkg/model/iam/tests/iam_builder_master_legacy.json#L17-L25
Strict:
https://github.com/kubernetes/kops/blob/fbfe24afd96790b8470cf370dbe452353074a8b7/pkg/model/iam/tests/iam_builder_master_strict_ecr.json#L53-L81

**Comment by robinpercy** [comment]
> I think we have this fixed. Need to check

@chrislovecnm I just hit this as well with kops 1.8.0. Do we want to fix it in kops? There's a case to be made for using something like kube2iam instead.

**Comment by chrislovecnm** [comment]
Yes we need this in kops. We may be missing another perms as well. Really we should have a use autoscalig flag to enable / disable in the api.

**Comment by robinpercy** [comment]
sounds good. Will open a PR.

/assign
