### ISSUE TITLE
dns-controller flags document missing several options.

### ISSUE THREAD

**Issue by rk295** [kubernetes/kops#2687]
Hi, I just noticed that [this](https://github.com/kubernetes/kops/blob/master/dns-controller/docs/flags.md) doc is missing most of the permissable options. I've picked the options out of the source and updated the doc. I've raised #2686 for this.

**Comment by BradErz** [comment]
can be closed? https://github.com/kubernetes/kops/pull/2686 is merged

**Comment by rk295** [comment]
Fine with me!
