### ISSUE TITLE
Proposal: APIServer fields for authenticating proxy

### ISSUE THREAD

**Issue by mtolan** [kubernetes/kops#2691]
Kubernetes supports configuration of user accounts based on headers specified in some authenticating proxy. See: https://kubernetes.io/docs/admin/authentication/#authenticating-proxy

If I understand the intended usage correctly, in order for kops clusters to use this properly, kops cluster definitions will need to pass the following flags to apiserver containers that it spawns.

      --requestheader-group-headers
      --requestheader-username-headers
      --requestheader-extra-headers

It seems like adding these as fields of a KubeAPIServerConfig is a reasonable course of action. Probably something like

	RequestheaderExtraHeaders    *string `json:"requestheaderExtraHeaders,omitempty" flag:"requestheader-extra-headers"`
	RequestheaderGroupHeaders    *string `json:"requestheaderGroupHeaders,omitempty" flag:"requestheader-group-headers"`
	RequestheaderUsernameHeaders *string `json:"requestheaderUsernameHeaders,omitempty" flag:"requestheader-username-headers"`

My understanding is that this is likely a straightforward change to a suitably versioned ```componentconfig.go``` file, but I'm not clear on what other supporting changes need to come along with it. Thanks for any feedback and recommendations.

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md outlines how to makes the changes.
