### ISSUE TITLE
Request: Create a new release

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kops#2692]
I'm specially interested on merging this two changes in our clusters:

https://github.com/kubernetes/kops/commit/c7168937a3e44728ca2ea5837c59fc3caefe4d70
https://github.com/kubernetes/kops/pull/2640/commits/2e1a024b9f64c2dcee53d9c5d6e78c3daad50060

regards

**Comment by WillemMali** [comment]
You could run kops from the `master` branch? Most of the work is in setting up Go, and then it's `git clone`, `make` and `sudo cp kops /usr/local/bin/kops`.

I can't find documentation on the release process so I don't think there is an "official" release process yet.

**Comment by felipejfc** [comment]
I could but I've already had problems running master, @justinsb says it's not stable

**Comment by justinsb** [comment]
Working on 1.6.1 now.  In general it's not a good idea to run from master, but in this case you could also just `kubectl edit` the calico resources I believe?

**Comment by kenden** [comment]
1.6.1 release. Can this be closed?

**Comment by felipejfc** [comment]
closing, thanks @justinsb
