### ISSUE TITLE
Can't ssh into bastion host: SSH Timeout

### ISSUE THREAD

**Issue by chapati23** [kubernetes/kops#2696]
I've created a cluster with a custom ssh key via `--ssh-public-key`.
I'm not able to ssh into the cluster. ssh logs:

```
$ ssh -i /path/to/my/private/key.rsa admin@public-dns-of-bastion-ec2-instance -vvv
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/my-name/.ssh/config
debug1: /Users/my-name/.ssh/config line 17: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "public-dns-of-bastion-ec2-instance" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to public-dns-of-bastion-ec2-instance [public.bastion.ip] port 22.
debug1: connect to address public.bastion.ip port 22: Operation timed out
ssh: connect to host public-dns-of-bastion-ec2-instance port 22: Operation timed out
```

• I have also tried my default ssh key `id_rsa` => same result
• I have also created a new EC2 instance just to test => could ssh into it without a problem.
• I re-applied my ssh key via `kops create secret --name cluster-name sshpublickey admin -i path/to/my/public/key.pub` => same result, ssh timeout
• Bastion EC2 instance shows as healthy in AWS console and has an inbound rule for port 22

any idea what's going wrong or how to debug?

**Comment by chrislovecnm** [comment]
>  I re-applied my ssh key via kops create secret --name cluster-name sshpublickey admin -i path/to/my/public/key.pub => same result, ssh timeout

You need to do a rolling-update for that to work btw.  Did not see that step.

What OS are you using?

**Comment by chapati23** [comment]
@chrislovecnm latest macOS (Sierra)
You're right, i only did `kops update cluster --yes` after re-applying the ssh key. will try with rolling update.

Can I see somewhere which Key is used on the Cluster? Is there a fingerprint or sth that I could compare my public Key against?

**Comment by chrislovecnm** [comment]
@chapati23 the fingerprint is being created by kops in a http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html

**Comment by chapati23** [comment]
yeah, something's not working there. fingerprints don't match. even after rolling update.
what inside kops can i check to see whether the ssh key update actually worked?

**Comment by chapati23** [comment]
just verified again with a fresh cluster. either `--ssh-public-key` is definitely not working or I'm doing it wrong. Here are the exact steps I took on macOS 10.12.5 with kops 1.6.1:

* Generated fresh ssh key
  * `ssh-keygen -t rsa -f my-new-key`
  * `export PUBLIC_SSH_KEY=my-new-key.pub`
* Create cluster
    ```sh
    kops create cluster \
  --state s3://${KOPS_CONFIG_BUCKET} \
  --ssh-public-key $PUBLIC_SSH_KEY \
  --cloud aws \
  --zones ${AWS_REGION}a \
  --topology private \
  --networking calico \
  --network-cidr=10.0.0.0/16 \
  --bastion \
  --master-size m3.medium \
  --node-size m3.medium \
  --node-count 4 \
  --yes \
  k8.my-cluster.com
* Go to AWS EC2 and select Public DNS from the bastion host
* Try ssh-ing into the bastion host
  * `ssh -i my-new-key admin@dns-of-my.bastion-host.com` => times out
* Get fingerprint from ssh key on kops
  * `kops get secrets --type sshpublickey admin`
* Get fingerprint from `my-new-key` on my local machine
  * `openssl rsa -in thor-dev -pubout -outform DER | openssl md5 -c`
* => Fingerprints don't match
* Get fingerprint from my default key
  * `openssl rsa -in ~/.ssh/id_rsa -pubout -outform DER | openssl md5 -c`
* => Fingerprints also don't match

So I'm at a loss here which ssh key kops is really using at the end.

Any further debugging hints?

**Comment by chrislovecnm** [comment]
Is it using your default key?

**Comment by chrislovecnm** [comment]
Dumb question - is the bastion being created?

**Comment by chapati23** [comment]
@chrislovecnm yeah, bastion is there. i can see it in the EC2 console. it's not using my default key i tried both the default one (`~/.ssh/id_rsa`)  as well as the one i specified in `kops create`. the fingerprints are different as well

**Comment by chrislovecnm** [comment]
I am a bit stumped. Ping me on slack if you want

**Comment by chapati23** [comment]
ok, it was very stupid in the end.
`ssh admin@bastion.k8.my-cluster.com` => works
`ssh admin@public-dns-of-elb.amazonaws.com` => doesn't work

so i think these docs should be updated: https://github.com/kubernetes/kops/blob/master/docs/bastion.md

from `ssh -A admin@<bastion_elb_a_record>` to `ssh -A admin@<bastion_cname>`

**Comment by chrislovecnm** [comment]
Well yah figure it out ... woop!

**Comment by costa** [comment]
@chapati23 Hey, we seem to have exactly the same issue you had, but I don't seem to understand your conclusion, I've tried connecting to the bastion's instance public IP and to its associated elastic public IP, but the port just won't open, nevermind the DNS or the keys.

Could you elaborate on your solution please?

**Comment by chapati23** [comment]
sry @costa, we've since moved on to GKE and I don't have context anymore…
