### ISSUE TITLE
Cannot create HA multi-master cluster in ca-central

### ISSUE THREAD

**Issue by tanner-bruce** [kubernetes/kops#2697]
Kops fails to create a multi-master HA cluster in ca-central due to there only being two availability zones.

Specifying `--master-zones=ca-central-1a,ca-central-1b` returns a notification about the # of masters being an odd #.

Attempting to double up one of the zones leads to errors about duplicate zones

Kops v.1.6.0 built from master @ 286daa739

**Comment by chrislovecnm** [comment]
you need to do `--master-zones=ca-central-1a,ca-central-1a,ca-central-1a`

Etcd requires 3 nodes min for an HA quorum.  We probably need this documented a bit better.

**Comment by tanner-bruce** [comment]
@chrislovecnm I tried doing that, except as `--master-zones=ca-central-1a,ca-central-1a,ca-central-1b` however it did not work, I'll build kops on this machine and grab the error message.

**Comment by kamalguptad** [comment]
@tanner-bruce 
like "--master-zones=ca-central-1a,ca-central-1b,ca-central-1c"  you need to give "--zones=ca-central-1a,ca-central-1b,ca-central-1c" also and later in the ig nodes you can decrease the number of nodes....but you need to specify odd number of masters in kops
