### ISSUE TITLE
KOPS can't pull from local ECR

### ISSUE THREAD

**Issue by 1e1f** [kubernetes/kops#2699]
wondering if anyone else experienced sudden loss of KOPS ECR pull. Happened to me after upgrading to 1.6.2, continuing to 1.6.4 fixed the issue for 24 hours, so I'm guessing this is a ECR login token issue and that resetting the nodes bought be an additional 12 hours. My images refuse to pull with no error message except connection closed. This is true for pulls both in region and cross region. Supplying a valid image-pull secret does not help either. happy to provide further reproducibility details as directed. thanks.

**Comment by chrislovecnm** [comment]
I have seen this with running out of disk space on a node.  This is actually a k8s problem, not a kops challenge.  If you want to tag me and @justinsb on an issue in /kubernetes/kubernetes that would be awesome.  

You mind closing the issue here?

**Comment by 1e1f** [comment]
To clarify you're saying local docker images are filling up the disk space? (I'm aware of docker's propensity to do that). Running df on a node shows only 28% usage, so it seems unlikely that is my problem. Pulling fails from ECR only, pulling public images from docker hub, and generic private registry works fine. Will try basic auth on private registry, it seems like a 'docker login' issue.

@chrislovecnm If you're pretty sure this is a k8s/ecr issue and not a kops issue I'll happily move this to kubernetes/kubernetes

**Comment by 1e1f** [comment]
ok, having loads of other issues lately as well including T2 nodes reporting NotReady for instance. given that I can point to a specific KOPS failure here, I'll close this here.
