### ISSUE TITLE
Upgrade master instance type fails 

### ISSUE THREAD

**Issue by Miyurz** [kubernetes/kops#2707]
Hello there,

I keep getting
```Kubelet NonMasqueradeCIDR did not match cluster NonMasqueradeCIDR ```
 when I try to   
``` kops edit instancegroups master-ap-south-1a```
 looks somewhat similar to  https://github.com/kubernetes/kops/issues/1831

kops version: 1.5.3

 ```$ kops get cluster np.k8s.saltside.io -o yaml --full | grep CIDR
    allocateNodeCIDRs: true
    clusterCIDR: 100.96.0.0/11
    nonMasqueradeCIDR: 100.64.0.0/10
    nonMasqueradeCIDR: 100.64.0.0/10
  networkCIDR: 172.20.0.0/16
  nonMasqueradeCIDR: 100.64.0.0/10```

This definitely looks like a bug because both the CIDRs are same

**Comment by Miyurz** [comment]
Verbose log here @justinsb @chrislovecnm @kris-nova 
>  $ kops get cluster np.k8s.saltside.io -o yaml --full
> apiVersion: kops/v1alpha2
> kind: Cluster
> metadata:
>   creationTimestamp: "2017-04-27T13:11:50Z"
>   name: np.k8s.saltside.io
> spec:
>   api:
>     loadBalancer:
>       type: Public
>   channel: stable
>   cloudProvider: aws
>   clusterDNSDomain: cluster.local
>   configBase: s3://saltside-nonproduction-kops-eu-west-1/np.k8s.saltside.io
>   configStore: s3://saltside-nonproduction-kops-eu-west-1/np.k8s.saltside.io
>   dnsZone: k8s.saltside.io
>   docker:
>     bridge: ""
>     ipMasq: false
>     ipTables: false
>     logLevel: debug
>     storage: overlay,aufs
>     version: 1.12.3
>   etcdClusters:
>   - etcdMembers:
>     - instanceGroup: master-ap-south-1a
>       name: a
>     name: main
>   - etcdMembers:
>     - instanceGroup: master-ap-south-1a
>       name: a
>     name: events
>   keyStore: s3://saltside-nonproduction-kops-eu-west-1/np.k8s.saltside.io/pki
>   kubeAPIServer:
>     address: 127.0.0.1
>     admissionControl:
>     - NamespaceLifecycle
>     - LimitRanger
>     - ServiceAccount
>     - PersistentVolumeLabel
>     - DefaultStorageClass
>     - ResourceQuota
>     allowPrivileged: true
>     anonymousAuth: false
>     apiServerCount: 1
>     basicAuthFile: /srv/kubernetes/basic_auth.csv
>     clientCAFile: /srv/kubernetes/ca.crt
>     cloudProvider: aws
>     etcdServers:
>     - http://127.0.0.1:4001
>     etcdServersOverrides:
>     - /events#http://127.0.0.1:4002
>     image: gcr.io/google_containers/kube-apiserver:v1.5.4
>     kubeletPreferredAddressTypes:
>     - InternalIP
>     - Hostname
>     - ExternalIP
>     - LegacyHostIP
>     logLevel: 2
>     pathSrvKubernetes: /srv/kubernetes
>     pathSrvSshproxy: /srv/sshproxy
>     securePort: 443
>     serviceClusterIPRange: 100.64.0.0/13
>     storageBackend: etcd2
>     tlsCertFile: /srv/kubernetes/server.cert
>     tlsPrivateKeyFile: /srv/kubernetes/server.key
>     tokenAuthFile: /srv/kubernetes/known_tokens.csv
>   kubeControllerManager:
>     allocateNodeCIDRs: true
>     attachDetachReconcileSyncPeriod: 1m0s
>     cloudProvider: aws
>     clusterCIDR: 100.96.0.0/11
>     clusterName: np.k8s.saltside.io
>     configureCloudRoutes: false
>     image: gcr.io/google_containers/kube-controller-manager:v1.5.4
>     leaderElection:
>       leaderElect: true
>     logLevel: 2
>     master: 127.0.0.1:8080
>     pathSrvKubernetes: /srv/kubernetes
>     rootCAFile: /srv/kubernetes/ca.crt
>     serviceAccountPrivateKeyFile: /srv/kubernetes/server.key
>   kubeDNS:
>     domain: cluster.local
>     image: gcr.io/google_containers/kubedns-amd64:1.3
>     replicas: 2
>     serverIP: 100.64.0.10
>   kubeProxy:
>     cpuRequest: 100m
>     image: gcr.io/google_containers/kube-proxy:v1.5.4
>     logLevel: 4
>     master: https://api.internal.np.k8s.saltside.io
>   kubeScheduler:
>     image: gcr.io/google_containers/kube-scheduler:v1.5.4
>     leaderElection:
>       leaderElect: true
>     logLevel: 2
>     master: 127.0.0.1:8080
>   kubelet:
>     allowPrivileged: true
>     apiServers: https://api.internal.np.k8s.saltside.io
>     babysitDaemons: true
>     cgroupRoot: docker
>     cloudProvider: aws
>     clusterDNS: 100.64.0.10
>     clusterDomain: cluster.local
>     enableDebuggingHandlers: true
>     evictionHard: memory.available<500Mi
>     evictionPressureTransitionPeriod: 0s
>     hostnameOverride: '@aws'
>     logLevel: 2
>     networkPluginMTU: null
>     networkPluginName: cni
>     nonMasqueradeCIDR: 100.64.0.0/10
>     podManifestPath: /etc/kubernetes/manifests
>   kubernetesApiAccess:
>   - 0.0.0.0/0
>   kubernetesVersion: 1.5.4
>   masterInternalName: api.internal.np.k8s.saltside.io
>   masterKubelet:
>     allowPrivileged: true
>     apiServers: http://127.0.0.1:8080
>     babysitDaemons: true
>     cgroupRoot: docker
>     cloudProvider: aws
>     clusterDNS: 100.64.0.10
>     clusterDomain: cluster.local
>     enableDebuggingHandlers: true
>     evictionHard: memory.available<500Mi
>     evictionPressureTransitionPeriod: 0s
>     hostnameOverride: '@aws'
>     logLevel: 2
>     networkPluginMTU: null
>     networkPluginName: cni
>     nonMasqueradeCIDR: 100.64.0.0/10
>     podManifestPath: /etc/kubernetes/manifests
>     registerSchedulable: false
>   masterPublicName: api.np.k8s.saltside.io
>   networkCIDR: 172.20.0.0/16
>   networking: {}
>   nonMasqueradeCIDR: 100.64.0.0/10
>   secretStore: s3://saltside-nonproduction-kops-eu-west-1/np.k8s.saltside.io/secrets
>   serviceClusterIPRange: 100.64.0.0/13
>   sshAccess:
>   - 0.0.0.0/0
>   subnets:
>   - cidr: 172.20.32.0/19
>     name: ap-south-1a
>     type: Private
>     zone: ap-south-1a
>   - cidr: 172.20.0.0/22
>     name: utility-ap-south-1a
>     type: Utility
>     zone: ap-south-1a
>   topology:
>     bastion:
>       bastionPublicName: bastion.np.k8s.saltside.io
>     dns:
>       type: Public
>     masters: private
>     nodes: private

**Comment by Miyurz** [comment]
@chrislovecnm @justinsb any updates ?

**Comment by WillemMali** [comment]
Do you have a specific reason for not updating to the latest kops release, 1.6.1?

**Comment by Miyurz** [comment]
If kops 1.6.1 has fixed this, we can move onto that. Its just that we don't have the bandwidth for now. Thanks @WillemMali
