### ISSUE TITLE
CoreOS logrotate

### ISSUE THREAD

**Issue by adrianchifor** [kubernetes/kops#2710]
Was just wondering why logrotate configs are not installed on CoreOS? Source: https://github.com/kubernetes/kops/blob/fea4df5868c9f679bab3aa4e1a65b5ca0b3be089/nodeup/pkg/model/logrotate.go#L38

**Comment by WillemMali** [comment]
I read the Git blame and the code, all container-centric distros don't get logrotate installed. I would assume the intention is to keep deployments on these distros as light as possible in concordance with the distros' design ethos.

@justinsb, you implemented logrotate for kops, could you confirm my suspicion?

**Comment by adrianchifor** [comment]
@WillemMali Thanks for the response, altought I just checked one of our base CoreOS v1353 nodes and there is a logrotate systemd service installed. kops 1.5.3 had logrotate configs at `/etc/logrotate.d` but since kops 1.6.0 we had to add them ourselves.

**Comment by chrislovecnm** [comment]
@adrianchifor what should we be doing? Was it getting installed in the past?  Was it in the base image in the past?  You are the user and know more than I do about CoreOS thank I do :)

**Comment by adrianchifor** [comment]
@chrislovecnm As far as I can remember, CoreOS has always had logrotate as a systemd service. We had kops 1.5.3 on our k8s clusters recently and the `/etc/logrotate.d` folder contained the k8s-related logrotate configs. When we upgraded to kops 1.6.0 the logrotate configs were gone. 

Instead of checking the OS distribution if we need to apply the logrotate configs, we should check if logrotate is installed (check systemd or check if the binary exists at `/usr/sbin/logrotate`, default location on CoreOS).
