### ISSUE TITLE
Manually validate cluster specification/config

### ISSUE THREAD

**Issue by WillemMali** [kubernetes/kops#2712]
I'd like to have a way to validate the yaml I maintain for kops, but I couldn't find a `kops validate` option to use local yaml or `--dry-run` option for `kops replace`.

I do the same thing for k8s, with `kubectl apply --dry-run=true --validate=true`. I find it useful while I'm editing yaml, I currently have a pure-CLI workflow with GNU Make for automating common tasks (like recreating my development cluster and applying sets of k8s templates).

I'm on the latest release but not a Git version.

**Comment by bhvr-fmarceau** [comment]
Upvoting this issue! I'd really like to be able to have a dry-run option to validate changes in yaml!

**Comment by chrislovecnm** [comment]
We actually just need to get validation working better internally first. Always appreciate help!

**Comment by christhomas-msm** [comment]
It's a bit dirty, and you do have to copy the config to the state store bucket before you can can do it, but we're currently using this to validate manual config changes:

`EDITOR=$(which cat) kops edit cluster`

Similar for instancegroup config:

```
for i in $(ls ./instancegroup/); do
  aws s3 cp ./instancegroup/$i $KOPS_STATE_STORE/$CLUSTER_NAME/instancegroup/$i
  EDITOR=$(which cat) kops edit instancegroup $i
done
```
