### ISSUE TITLE
Kubernetes 1.7 support in kops

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2715]
We need to make some updates for k8s 1.7.

- Docker version
- CNI provider updates for NetworkPolicy updates
- Determine if using `--feature-gates=RotateKubeletClientCertificate=true` is appropriate
- Ensure that we are not setting any depreciated flags on 1.7

**Comment by chrislovecnm** [comment]
Determine how to use: https://github.com/kubernetes/kubernetes/pull/42202

**Comment by squeed** [comment]
FYI (author of that CNI PR here), the CNI configuration is backwards-compatible, so no changes are needed. However, if you use configlists, then you can enable plugin chaining.

The only chained plugin for now is the port-mapping one, but others will start to come in to existence.

Let me know if you have any questions.

**Comment by chrislovecnm** [comment]
Closing ... as we have had support .. DOH
