### ISSUE TITLE
Secure master -> kubelet configuration

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2720]
It hasn't been as important for AWS, but as we support more clouds we should ensure that the master -> kubelet configuration is secure.

cf https://github.com/kubernetes/kubernetes/issues/11816#issuecomment-305339878

**Comment by liggitt** [comment]
See https://kubernetes.io/docs/admin/kubelet-authentication-authorization/

**Comment by gambol99** [comment]
was fixed in https://github.com/kubernetes/kops/pull/2831

**Comment by chrislovecnm** [comment]
Closing
