### ISSUE TITLE
Services are over using security groups.

### ISSUE THREAD

**Issue by Nitecon** [kubernetes/kops#2721]
Services are using too many rules per AWS security group... This needs to be adjusted to re-use common sec groups where possible.  Data below:

    FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason				Message
      ---------	--------	-----	----			-------------	--------	------				-------
      2m		2m		1	service-controller			Warning		CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service default/infrascrub-master: error authorizing security group ingress: RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.
        status code: 400, request id: cf565516-edc2-4e3e-b3bd-309ef56efa79
      1m		1m	1	service-controller		Warning	CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service default/infrascrub-master: error authorizing security group ingress: RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.
        status code: 400, request id: 0c37ad95-8289-4f94-9032-d2ccd30fc063
      1m		1m	1	service-controller		Warning	CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service default/infrascrub-master: error authorizing security group ingress: RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.
        status code: 400, request id: 4edb46de-2799-4a00-b13e-b7e1fbffd18a
      1m		1m	1	service-controller		Warning	CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service default/infrascrub-master: error authorizing security group ingress: RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.
        status code: 400, request id: 5bc04495-d8ab-48b0-bbb4-3c00fbc3aa60
      2m		43s	5	service-controller		Normal	CreatingLoadBalancer		Creating load balancer
      43s		43s	1	service-controller		Warning	CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service default/infrascrub-master: error authorizing security group ingress: RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.
        status code: 400, request id: 5a7b013a-305b-457d-a39e-78395cfcefee

**Comment by chrislovecnm** [comment]
@Nitecon can we get more details?

**Comment by gileshinchcliff** [comment]
I'm guessing he's talking about this issue in kubernetes:
https://github.com/kubernetes/kubernetes/issues/26670

The problem being that every time you create a service with load balancer type it adds  the SG rule to the SG attached to the nodes, because there's a limit on the number of rules you can have attached to a SG you have a hard limit on the amount of loadbalancer services (max 250 depending on your infrastructure.)

Solution to this is ingress, however it'd be good to hear of any other suggestions on how to fix this issue in the interim.

**Comment by Nitecon** [comment]
awhat @gileshinchcliff mentioned is correct.  WE have a large amount of services and all of them use ELB's which was fine up until this point (we have a limit of 1024 elb's in our AWS account), we will eventually work to move it to ingress but for now there should be a better way to handle the security groups, and perhaps documentation to note that there is this limitation and error and here is the workaround.

**Comment by chrislovecnm** [comment]
I thought this may be an upstream kubernetes issue. One thing that we should unventilated is to determine if https://github.com/zalando-incubator/kubernetes-on-aws/pull/390/files would be helpful

**Comment by chrislovecnm** [comment]
I just labeled the upstream issue properly

**Comment by ahawkins** [comment]
Just ran into this today. This is a k8s issue, and _not_ a kops thing correct?

**Comment by chrislovecnm** [comment]
The above statement is correct. You can re-use a single security group. Closing

**Comment by darrenhaken** [comment]
What rules does the security group need?
