### ISSUE TITLE
How to do a rolling-update without losing capacity?

### ISSUE THREAD

**Issue by WillemMali** [kubernetes/kops#2724]
I'm trying to get `kops rolling-update` to work with zero downtime (when modifying the nodes IG), and I'm using the experimental DrainAndValidateNodes flag.

It seems like that removes one node, and then adds another, but as I tend to run very close to full capacity/with large nodes that means for a while I'm down 1 node and not all of my pods can be scheduled.

Is there a `rolling-update` strategy I could specify that e.g. adds all the new nodes, validates them and only then drains the old nodes?

**Comment by chrislovecnm** [comment]
See the other issues open around rolling update, and I have a WIP pr in already

**Comment by chrislovecnm** [comment]
This is a duplicate, can we close?
