### ISSUE TITLE
Kops for vSphere is broken due to versioning problem during make

### ISSUE THREAD

**Issue by fabulous-gopher** [kubernetes/kops#2729]
_From @prashima on May 10, 2017 22:53_

Makefile has following variables defined-
KOPS_RELEASE_VERSION=1.6.0-alpha.1
KOPS_CI_VERSION=1.6.0-alpha.2

KOPS_RELEASE_VERSION(1.6.0-alpha.1) is getting picked during 'make' and same is getting populated in kube_env.yaml as protokube image name. However, the pre-build protokube image that is to be used for vSphere cloud provider- https://storage.googleapis.com/kops-vsphere/protokube.tar.gz, has tag 1.6.0-alpha.2 associated with it. So the image name in the nodeup config file- kube_env.yaml and actual image present with docker, running on the master is different. 

This is preventing protokube container from getting started, leading to failure of whole deployment.

_Copied from original issue: vmware/kops#71_

**Comment by prashima** [comment]
vSphere related changes might already be part of kops release and hence the default nodeup and protokube images. It would be worth trying out using kops with vSphere without setting up NODEUP_URL  and PROTOKUBE_IMAGE  environment variables. Ref https://github.com/kubernetes/kops/blob/master/hack/vsphere/set_env#L43

**Comment by chrislovecnm** [comment]
Closing as this should be fixed
