### ISSUE TITLE
reinstall dns-controller

### ISSUE THREAD

**Issue by nmnellis** [kubernetes/kops#2754]
I noticed that the dns-controller was no longer running on my k8s cluster in aws. Is there a way to reinstall it? I cannot seem to find a deployment yaml for it. I'm using kops 1.6.0

**Comment by cordoval** [comment]
does it happen intermittently? i happen to run into problems where dns also failed but it is very hard to troubleshoot

**Comment by nmnellis** [comment]
We had issues when upgrading and accidentally deleted the dns-controller deployment and cannot figure out how to recreate it

**Comment by cordoval** [comment]
I killed one of the nodes and kube restarted it a new node with good services, but then it failed again, so we don't know what it is really.

**Comment by chrislovecnm** [comment]
The manifest should be in your s3 bucket.  dns-controller runs on a master, so doing a force rolling-update on the master is another option as well.  Does the controller show up in kube-system namespace?

**Comment by nmnellis** [comment]
no it is no longer in the kube-system namespace. it was accidentally deleted from the dashboard.

**Comment by chrislovecnm** [comment]
I am taking an educated guess that the manifest is in the s3 bucket/state store.  As I mentioned it should be reinstalled by doing a rolling-update on the master.  This, of course, will kill the master instance, and I would backup etcd.

**Comment by chrislovecnm** [comment]
Yes, the manifest is in s3 state store bucket.  

> addons/dns-controller.addons.k8s.io/

Download and install with kubectl should get it installed.  Otherwise, you can debug if the manifest does not install.  The dns-controller does run on your master, so headroom for it is needed.

**Comment by nmnellis** [comment]
thanks, i'll give it a shot

**Comment by chrislovecnm** [comment]
What is the status on this? Can we close?

**Comment by nmnellis** [comment]
I was able to find the dns controller file in my s3 state store and apply. I first tried a rolling update `kops rolling-update cluster --name=$CLUSTER_NAME --state=$STATE_STORE --force --yes` and that did not add the missing controller back. this can now be closed
