### ISSUE TITLE
Kubernetes CNI errors with flannel on container init (network: open /run/flannel/subnet.env: no such file or directory")

### ISSUE THREAD

**Issue by justicel** [kubernetes/kops#2755]
I have an install on 1.6.4 with KOPS 1.6.1 version instantation. I am getting the following errors when trying to start pods on new auto-scaled nodes:

  19s		19s		1	default-scheduler							Normal		Scheduled	Successfully assigned stage-oryx-play-actions-oryx-play-actions-speed-3631732695mvm6g to ip-172-20-123-170.us-west-2.compute.internal
  12s		8s		2	kubelet, ip-172-20-123-170.us-west-2.compute.internal			Warning		FailedSync	Error syncing pod, skipping: failed to "CreatePodSandbox" for "stage-oryx-play-actions-oryx-play-actions-speed-3631732695mvm6g_stage(0762a78f-5227-11e7-8b8a-0aebe2b320dc)" with CreatePodSandboxError: "CreatePodSandbox for pod \"stage-oryx-play-actions-oryx-play-actions-speed-3631732695mvm6g_stage(0762a78f-5227-11e7-8b8a-0aebe2b320dc)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"stage-oryx-play-actions-oryx-play-actions-speed-3631732695mvm6g_stage\" network: open /run/flannel/subnet.env: no such file or directory"

  8s	8s	1	kubelet, ip-172-20-123-170.us-west-2.compute.internal		Normal	SandboxChanged	Pod sandbox changed, it will be killed and re-created.

This sounds like it could be related? 
https://github.com/kubernetes-incubator/kube-aws/issues/495

@justinsb

**Comment by Doron-offir** [comment]
Hi,

We are suffering from a similar issue, a k8s 1.6.2 on AWS created with KOPS 1.6.2.
Did you found a solution to it?

All of the very best,

**Comment by erez-rabih** [comment]
We also have this issue on kops 1.7.0 with kubernetes 1.7.5
It seems that kubelet tries to start pods before the CNI is configured on node.
https://github.com/kubernetes/kubernetes/issues/43014
