### ISSUE TITLE
Default AWS master instance size not available in eu-central-1c

### ISSUE THREAD

**Issue by kyrias** [kubernetes/kops#2771]
As with #1455, the eu-central-1c availability zone does not have m3.medium as an available option, so trying to have a master in all three zones silently has launching the third one failing.

**Comment by chrislovecnm** [comment]
We have an issue open to change to m4 or c4s

**Comment by jrnt30** [comment]
Additionally, there is no one `eu-central-1c`, they change per account. 

> An Availability Zone is represented by a region code followed by a letter identifier; for example, us-east-1a. To ensure that resources are distributed across the Availability Zones for a region, we independently map Availability Zones to identifiers for each account. For example, your Availability Zone us-east-1a might not be the same location as us-east-1a for another account. There's no way for you to coordinate Availability Zones between accounts.

via http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html

**Comment by kyrias** [comment]
Fixed by #2837.
