### ISSUE TITLE
Question: Variables in CloudConfig

### ISSUE THREAD

**Issue by alexandrst88** [kubernetes/kops#2776]
Hi! According to soucre https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L395. How do I set this variables in aws cloud config and in which format? I was not able to find example somewhere?

**Comment by chrislovecnm** [comment]
What are you trying to do?

**Comment by alexandrst88** [comment]
I faced with the issue "RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached", because kubernetes creates sg per elb. So to avoid this I need to set above into cloud-config

**Comment by alexandrst88** [comment]
Also, How is cloud-config can be modified?

**Comment by chrislovecnm** [comment]
Can we close this out since you opened a specific issue for supporting this configuration?  At this point, I have not had a chance to triage this issue, so I do not have an answer for you.

**Comment by alexandrst88** [comment]
I just need an answer how to modify cloud-config in kops :)

**Comment by chrislovecnm** [comment]
> At this point, I have not had a chance to triage this issue, so I do not have an answer for you

**Comment by alexandrst88** [comment]
this can be closed, I will open PR, on things that I want to achieve with KOPS.

**Comment by chrislovecnm** [comment]
See the pr, left some comments. Closing
