### ISSUE TITLE
How to customize cloud-config in KOPS for AWS?

### ISSUE THREAD

**Issue by alexandrst88** [kubernetes/kops#2779]
For example, I need to pass something like,
```  
- path: /etc/kubernetes/cloud-config.ini
    content: |
      [global]
      DisableSecurityGroupIngress = true
```
Currently I'm using nodeup bootstrap script, is there possibility to add to the node up file above?

**Comment by chrislovecnm** [comment]
Does https://github.com/kubernetes/kops/pull/3090 fit your needs?
