### ISSUE TITLE
Cluster not getting updated to 1.6.x

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kops#2780]
Using kops 1.6.1

Created a cluster as:

```
kops create cluster --name cluster2.kubernetes-aws.io --zones us-west-2a --kubernetes-version=1.5.7 --state s3://kubernetes-aws-io --yes
```

Trying to update the cluster to the latest version as:

```
kops update cluster --name cluster2.kubernetes-aws.io --state s3://kubernetes-aws-io
```

It shows the output as:

```
I0620 16:25:56.031675   36823 executor.go:91] Tasks: 0 done / 63 total; 34 can run
I0620 16:25:57.074933   36823 executor.go:91] Tasks: 34 done / 63 total; 12 can run
I0620 16:25:57.893870   36823 executor.go:91] Tasks: 46 done / 63 total; 15 can run
I0620 16:25:59.392387   36823 executor.go:91] Tasks: 61 done / 63 total; 2 can run
I0620 16:25:59.606490   36823 executor.go:91] Tasks: 63 done / 63 total; 0 can run
No changes need to be applied
```

Expected output was that cloud resources will be updated to Kubernetes 1.6.x but it shows `No changes need to be applied`.

**Comment by arun-gupta** [comment]
Same happens if a 1.4.x cluster is created:

```
kops create cluster --name cluster2.kubernetes-aws.io --zones us-west-2a --kubernetes-version=1.4.12 --state s3://kubernetes-aws-io --yes
```

**Comment by arun-gupta** [comment]
Never mind, the rolling update is a three step process:

- `kops upgrade cluster --yes`
- `kops update cluster --yes`
- `kops rolling-update cluster --yes`

**Comment by cordoval** [comment]
someone needs to add this to the docs, someone told me about this too on the chat and i did not know what it was... until now 👍

**Comment by arun-gupta** [comment]
@cordoval This information is hiding at https://github.com/kubernetes/kops/blob/master/docs/upgrade.md#automated-update. +1 that this needs to be clearly documented.
