### ISSUE TITLE
Support for Debian Stretch

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2783]
I am assuming that Stretch is not supported by kops or k8s.  

1. determine if we can support stretch, i.e. does k8s support stretch
2. have kops support stretch

I am having this issue on gce: 

```
Jun 20 19:41:43 master-us-east1-c-rlm9 startup-script: INFO startup-script: W0620 19:41:43.499170    2010 identify.go:40] unhandled lsb-release info "DISTRIB_ID=Ubuntu\nDISTRIB_RELEASE=16.10\nDISTRIB_CODENAME=yakkety\nDISTRIB_DESCRIPTION=\"Ubuntu 16.10\"\n"
Jun 20 19:41:43 master-us-east1-c-rlm9 startup-script: INFO startup-script: W0620 19:41:43.499505    2010 main.go:141] got error running nodeup (will retry in 30s): error determining OS distribution: unhandled debian version "stretch/sid"
```

` --image "ubuntu-os-cloud/ubuntu-1610-yakkety-v20170619a"`

**Comment by rata** [comment]
@chrislovecnm just in case, stretch is the name of the latest *debian* release, *not ubuntu*.

I don't know how kops handles this, but after a quick search I think there is a jessie based AMI that is used for kops (I have a test cluster that uses an AMI with this description "Kubernetes 1.5 Base Image - Debian jessie amd64").

If that is the case, it seems that creating a new AMI based on debian stretch will do the trick (and just changed in the launch configuration, as with other upgrades, and do a rolling update). It's probably quite easy to do, just be careful of the kernel version.

Am I missing something?

In any case, there is no rush to do this as jessie, the current image, will be supported for 5 years. So, it will be nice to have, but there is no rush from a security POV to do it ASAP.

I think @justinsb is managing the AMIs creating and that stuff now, is this correct?




Thanks!
Rodrigo

**Comment by nfillot** [comment]
Another advantage switching from jessie to stretch would be the fix of #1558 . 
This would allow us to use the ixgbevf in-kernel driver.

We could also probably avoid the Debian build by using [Debian cloud images](https://wiki.debian.org/Cloud/AmazonEC2Image) (new LTS kernel,
cgroup memory enabled..)
This would also give some uniformity with Ubuntu i.e, no custom build and use distribution image.

**Comment by sudermanjr** [comment]
After reading the docs/images.md and this issue, I thought I would try running on stretch.  I also need it for another project.  Changing one of my instance groups to: 

image: 379101102735/debian-stretch-hvm-x86_64-gp2-2017-10-08-48016

Results in the nodes not connecting back into the cluster.  I got that image id from here: https://wiki.debian.org/Cloud/AmazonEC2Image/Stretch. 

So, either I am doing something wrong (likely), or stretch basic AMIs don't work.  I am thinking of trying to specify this ami for the entire cluster on creation, but something tells me this won't work.

Any thoughts?

**Comment by chrislovecnm** [comment]
Stretch I think is supported in master now. Will check

/assign

**Comment by chrislovecnm** [comment]
Closing

**Comment by mikn** [comment]
I'd like this reopened as stretch is not fully supported in nodeup for k8s v1.8:
```Nov  9 01:52:35 ip-172-20-53-253 nodeup[594]: W1109 01:52:35.458923     594 docker.go:505] Did not find docker package for debian9 amd64 1.13.1
```
Looking into the code, I find that the distro is added here:
https://github.com/kubernetes/kops/blob/132b428d64422b9138b6c3e6a017df0e61d74737/nodeup/pkg/distros/distribution.go#L28
But not mapped up here for the versions required for k8s 1.8:
https://github.com/kubernetes/kops/blob/132b428d64422b9138b6c3e6a017df0e61d74737/nodeup/pkg/model/docker.go#L57
Which effectively means that you cannot install a k8s cluster with version 1.8 and Debian 9 right now.
I have a rough idea of the PR required to enable this, so I can give it a try. :)

**Comment by justinsb** [comment]
That would be great - thank you @mikn :-)   I've reopened it!
