### ISSUE TITLE
Document default cpu limits and how to change them

### ISSUE THREAD

**Issue by ferrouswheel** [kubernetes/kops#2787]
I was confused as to why and where cpu requests of `100m` per container were being set. It would be great for this to be documented or part of the kops cluster spec.

Limits were added and merged as part of #974

This issue is continued from the closed issue #471 where another user asked "Is there any way to prevent kops from creating this LimitRange?"

**Comment by chrislovecnm** [comment]
This is actually documented on the kubernetes.io site. There is not way at this point to override the limits, you have to adjust ten after install. To be clear this is the default limits.

**Comment by ferrouswheel** [comment]
Thanks Chris, do you mind pointing out where the defaults are documented on the kubernetes.io site? I've tried googling and looking in relevant sections, and while I can find everything about how to control limit ranges I can't find anything about the default CPU request limit for containers.

**Comment by chrislovecnm** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/cpu-memory-limit/#apply-a-limit-to-the-namespace

**Comment by ferrouswheel** [comment]
Those documents tell you how to set a default for a namespace. My issue is the lack of documentation around what the default is for Kops out-of-the-box.

While Kubernetes may have this as a default setting somewhere - Kops explicitly had a limit included in the referenced pull request here: https://github.com/kubernetes/kops/pull/974/files#diff-704448baec97bf365430f4c1b12d24e9

**Comment by nhooyr** [comment]
Could this please be reopened?
