### ISSUE TITLE
Persistent Volumes and Multi A-Z

### ISSUE THREAD

**Issue by clanstyles** [kubernetes/kops#279]
When a dynamic persistent claim is created by Kubernetes, it's pinned to the zone by nature. In the event that the zone is out of resources and you edit the instance group's min/max machines, which is setup for multiple zones, you don't know if the new nodes are scheduled in a zone that is in need of those machines. This can cause issues with some zones having more resources than others.

**Comment by chrislovecnm** [comment]
@clanstyles this is a k8s / aws fun thingy.  Not sure if we can help you in kops.  Ideas?

**Comment by chrislovecnm** [comment]
Closing. Please re-open if you have questions.
