### ISSUE TITLE
Kops 1.6.2 generates kubernetes 1.6.0 config that cannot be read by jq

### ISSUE THREAD

**Issue by kirkbrady** [kubernetes/kops#2794]
Hi,

I have upgraded to kops 1.6.2 (Version 1.6.2 (git-98ae12a)) and am trying to provision a kubernetes 1.6.0 cluster. Part of that provisioning process is using yq/jq to change some elements in the config yaml file - when I try and read the yaml file with yq, i get the following error:

_yq: Error while running jq: TypeError: datetime.datetime(2017, 6, 22, 3, 55, 59) is not JSON serializable._

Encapsulating the element value for **creationTimestamp** fixes the issues, and I can read the yaml using yq as expected.

Thanks!

edit - I am using the windows subsystem for linux, with python, jq, yq and the aws cli installed. This combination of tools does work, as I have been using it for other projects

**Comment by kirkbrady** [comment]
I have added a worked around to my provisioning script :

_sed 's/\([0-9][0-90][0-9][0-9].*$\)/\"\1\"/' -i config_

This wraps the creationTimestamp value in double  quotation marks, allowing yq/jq to read it.
I later save the modified file to a temp file using _yq -y_ to export in yaml - this change the double quotes to single quotes automatically, before uploading to s3 and continuing the provisioning process.

**Comment by jamesonjlee** [comment]
this is a yq issue, it uses the python yaml loader with creates datetime objects which doesn't serialize to json by default (datetime is not a json type).

**Comment by zenmaster24** [comment]
hi jameson,

thanks for the update, but i was just curious because it looks like in earlier versions of kops, it does encapsulate the datetime string in quotation marks?
