### ISSUE TITLE
Master instance name in 1.6.2 gossip-based cluster

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kops#2796]
Using kops 1.6.2, created a cluster as:

```
kops create cluster cluster.k8s.local --zones us-east-1a --yes
```

Master instance name is `master-us-east-1a.masters.cluster.k8s.local`
All node instance names are `nodes.cluster.k8s.local`

It would be consistent to change the master name to `masters.cluster.k8s.local`

**Comment by chrislovecnm** [comment]
This is as designed because of creating multiple instance groups in ha mode. I would rather have the naming consistent between ha and non-ha.
