### ISSUE TITLE
When create kubernetes cluster using kops in HA mode on AWS

### ISSUE THREAD

**Issue by padgyx** [kubernetes/kops#2797]
Each kubernetes master is corresponding to an autoscaling group: master-us-west-2a.masters.clusterdomain.com, master-us-west-2b.masters.clusterdomain.com, master-us-west-2c.masters.clusterdomain.com, with only 1 instance (MAX and MIN are both 1) in the group. 
On the other hand, all the nodes are created within one autoscaling group: nodes.clustername.com. 
Is that right? If that's the case, how do you keep all the masters in sync? How do you autoscale the master? Why not keep all the masters in one autoscaling group? 

This is the command that I used:
$kops create cluster --master-zones=us-west-2a,us-west-2b,us-west-2c \
  --zones us-west-2a,us-west-2b,us-west-2c \
  --node-count=4 ${NAME}

**Comment by padgyx** [comment]
BTW, I am using 
$ kops version
Version 1.5.1

**Comment by chrislovecnm** [comment]
This is a duplicate :) https://github.com/kubernetes/kops/issues/1272

**Comment by padgyx** [comment]
OK, thanks! How do you keep the HA masters in sync? through etcd?

**Comment by chrislovecnm** [comment]
Not sure what you mean, you may want to ask that on the kops slack channel.  The master find each other via dns, and self update dns.

**Comment by chrislovecnm** [comment]
Closing, please re-open if needed.
