### ISSUE TITLE
Should generate terraform files without AWS config

### ISSUE THREAD

**Issue by stephanlindauer** [kubernetes/kops#280]
I think it would make sense to give the user a way of exporting terraform files from kops without defining S3 bucket location or or AWS credentials and zone.
I feel like those credentials should be put manually into the provider file.
Or in other words: I want have a way of getting all the tf files without kops already doing stuff to my AWS account. The point where this should happen earliest, in my opinion, is `terraform apply`.

**Comment by justinsb** [comment]
That's fair - the challenge is that doing a lot of this stuff in terraform (like key generation) is hard.

I think we can probably produce a much smaller set of required permissions for creation - perhaps just an S3 bucket, or perhaps creating the files and having terraform upload them to S3.

**Comment by stephanlindauer** [comment]
hi justin,
ok you're right. doing key generation in terrraform would be madness.
what i am suggesting is that the keys are generated in kops and then put into a terraform folder along side all the .tf files. so from there they could be used to provision the server (either via provisioner->file or via user-data/cloud-config).
does that make sense?

**Comment by mikekap** [comment]
Second this - ideally kops generates TF files, keys & the cluster config file in an output directory, without touching any resources. Terraform should be the one uploading that config file & keys to S3 before cluster start.

An even more idiomatic way to do that may be to write a series of kops-specific terraform modules similar to https://github.com/terraform-community-modules/tf_aws_vpc . Then the terraform output is simply a single file that properly passes the arguments between modules, depending on what's requested.

Separately, not sure if it's a good idea, but it is possible to create certs via terraform: https://www.terraform.io/docs/providers/tls/r/private_key.html . As that page notes it's not for production use though.

**Comment by stephanlindauer** [comment]
@justinsb can this be closed? i lost track if the kops development and went on to building my own terraform setup.
feel free to close this. :wink:
