### ISSUE TITLE
enable-controller-attach-detach Flag Is Not Mapped

### ISSUE THREAD

**Issue by FrederikNS** [kubernetes/kops#2801]
I wanted to try out "REX-Ray" on my kubernetes cluster, but as REX-Ray needs the kubelet flag `--enable-controller-attach-detach` to be set to `false`, I wanted to change my cluster-config. Unfortunately it seems that that specific field is not mapped in kops, along with a lot of other flags: https://github.com/kubernetes/kops/blob/119a0801c9885bce0d8e7450317b6e220255539a/pkg/apis/kops/v1alpha2/componentconfig.go#L21-L152

Shouldn't all the kubelet flags be mapped in kops, or is there some reason they are not?

**Comment by teragopher** [comment]
Facing the exact same problem too.  :'(
