### ISSUE TITLE
Do not require an SSH key to be set

### ISSUE THREAD

**Issue by elliot** [kubernetes/kops#2803]
It would be great to have a flag to disable setting an SSH key when creating AWS Launch Configurations. 

Our use case is for a PCI-DSS environment. We are using pre-hardened AMI's that disabled creating default `admin` user accounts, but having a common SSH key associated with each instance raises questions for auditors as to who has access.

**Comment by jwickens** [comment]
this caught me out for a while while following the getting started guide for launching the basic cluster in aws.

**Comment by pieterlange** [comment]
I believe its an AWS (API) requirement to assign a private key to each instance.

**Comment by chrislovecnm** [comment]
We allow re-using a key now. Please let me know if that helps

**Comment by rickardrosen** [comment]
I've been working on a PR for this as we want to able to output TF code without an SSH key.

**Comment by elliot** [comment]
Possible fix in #7096

**Comment by rifelpet** [comment]
This has been implemented in Kops 1.18.0
/close
