### ISSUE TITLE
error validating "cluster-autoscaler.yml": error validating data: found invalid field tolerations for v1.PodSpec

### ISSUE THREAD

**Issue by padgyx** [kubernetes/kops#2804]
Followed steps here: https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler
After issue: $ kubectl apply -f ${addon} got the following error:

error: error validating "cluster-autoscaler.yml": error validating data: found invalid field tolerations for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false

Then tried this: $ kubectl apply -f ${addon} --validate=false
Got the following error:

deployment "cluster-autoscaler" created
serviceaccount "cluster-autoscaler" created
unable to decode "cluster-autoscaler.yml": no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "cluster-autoscaler.yml": no kind "Role" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "cluster-autoscaler.yml": no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "cluster-autoscaler.yml": no kind "RoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"

Anything wrong with the cluster-autoscaler.yml?
I am using $ kops version
Version 1.5.1

Please advice.

**Comment by chrislovecnm** [comment]
So please use kops 1.6.2, and which version of k8s are you using.  I am guessing a version of 1.5.  RBAC support with those api endpoints is only available in 1.6 k8s.

**Comment by padgyx** [comment]
This is what I am using: 
$ kops version
Version 1.5.1
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-17T20:48:54Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}

Do you mean I need to upgrade kops from 1.5.1 to 1.6.2? or upgrade kubectl? 

Please clarify. 

Thanks!

**Comment by chrislovecnm** [comment]
@padgyx the manifest is for k8s 1.6.  You can look at previously tagged versions.  kops 1.6.2 works with a k8s 1.5 cluster.  We have fixed numerous bugs, and I would recommend using kops 1.6.2.

Again take a look at the older version of the manifests in Github.  You need a version that has the tolerations that are the 1.5 version, as the API was updated between 1.5 -> 1.6.

**Comment by padgyx** [comment]
OK, I upgraded kops and got this. Is that right?
However, I don't see any autoscaling group created. Is there any way I can test this autoscaler and make sure it works?

$ kubectl apply -f ${addon}
deployment "cluster-autoscaler" created
serviceaccount "cluster-autoscaler" created
clusterrole "cluster-autoscaler" created
role "cluster-autoscaler" created
clusterrolebinding "cluster-autoscaler" created
rolebinding "cluster-autoscaler" created
