### ISSUE TITLE
upgrade from 1.5.2 to 1.6.6 failed

### ISSUE THREAD

**Issue by vinayagg** [kubernetes/kops#2806]
1. We have a cluster we created using kops 1.5.x
using kops 1.5.3, we created kubernetes 1.5.2 clusters with 3 HA masters in 3 zones on aws (kops created etcd servers too) and 2 nodes 

2. To upgrade cluster we downloaded kops 1.6.1 and followed these steps
- kops edit cluster and change kubernetes Version to 1.6.6 (kops asks us to delete apiservers at 2 places, we did that)
- kops edit ig (increase instances by 1)
- kops update cluster --yes (this starts a new node (we did this so that we have enough capacity for pods)
- kops rolling-update cluster --yes

This correctly shuts down one master and starts a new one. However the new master was never able to join the cluster. Dashboard was not accessible.
I also noticed following error:
Error from server: client: etcd member http://127.0.0.1:4001 has no leader

I did not separately create etcd servers. So maybe kops killed the master with etcd master and now they are unable to elect a leader?
I was able to repeat this 4-5x times, so it quite repeatable.

**Comment by chrislovecnm** [comment]
> kops asks us to delete apiservers at 2 places, we did that

More details please

**Comment by vinayagg** [comment]
I do not have this handy.

When you do "kops edit cluster" and change kubernetes versionb 1.6.6 and try to save the config, kops will not save and reopen the file with this error at the top. you can just follow instructions there.
