### ISSUE TITLE
Validate AWS region and zones

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2811]
In order to provide greater usability kops needs to provide user feedback that a cluster creation will be successful.

This should be a pre-flight call, and possibly a `validate` call.

1. AWS instance type is available - possibly http://aws-blog.io/2015/ec2-instance-type-availability/
1. When using an existing VPC, validate setup
1. When using existing Subnets validate setups
1. When using existing IAM roles validate that roles will function

**Comment by Sedward** [comment]
Would it be valuable to add a "dry run" mode that would perform the validations?

**Comment by chrislovecnm** [comment]
@Sedward we already have a dry-run mode, but I am uncertain that we are running #2837 during dry run for update.  Do you mind testing or opening another issue?
