### ISSUE TITLE
Docker daemon logs are not rotated properly

### ISSUE THREAD

**Issue by ianjoneill** [kubernetes/kops#2816]
The Docker `daemon.log` file for one of our nodes (running on a cluster with Kubernetes 1.6.2 created with Kops 1.6.1) has become rather large (in excess of 500MiB) and does not seem to be rotated like the `kube-proxy.log` file.

I can see that logrotate is set up to rotate logs on the node once per hour, however it would appear to be confugured for the wrong file:

```
root@ip-172-20-60-238:/# cat /etc/cron.daily/logrotate
#!/bin/sh

test -x /usr/sbin/logrotate || exit 0
/usr/sbin/logrotate /etc/logrotate.conf
root@ip-172-20-60-238:/# cat /etc/logrotate.d/docker
/var/log/docker.log{
  rotate 5
  copytruncate
  missingok
  notifempty
  compress
  maxsize 100M
  daily
  create 0644 root root
}root@ip-172-20-60-238:/#
```

Shouldn't the configuration be for `/var/log/daemon.log`?

If so, would changing the line https://github.com/kubernetes/kops/blob/fea4df5868c9f679bab3aa4e1a65b5ca0b3be089/nodeup/pkg/model/logrotate.go#L59 be the solution?

I would be happy to submit a pull-request if this is the case!

**Comment by cordoval** [comment]
related https://github.com/kubernetes/kubernetes/issues/3943#issuecomment-311333339

**Comment by chrislovecnm** [comment]
@cordoval this is something that needs to be assessed and fixed in kops.

**Comment by cordoval** [comment]
@chrislovecnm agree with you. There are two things though. One is the stability or use case when disks gets full. How to make it more robust to get out of that situation. And the other thing is the log rotating thing. Again just to make that clarification it is really 2 things that play hand in hand to make this problem happen.

**Comment by ianjoneill** [comment]
Whilst performing maintenance tasks on our cluster, I noticed that the disk usage on one of our nodes has increased rather considerably over the last week or so. Investigating further, I've found that `daemon.log` file is actually rotated, however only once a week.

```
root@ip-172-20-60-238:~# ls -la /var/log/daemon.log*
-rw-r----- 1 root adm 1152226209 Jul  5 08:11 /var/log/daemon.log
-rw-r----- 1 root adm 2741604624 Jul  4 01:17 /var/log/daemon.log.1
-rw-r----- 1 root adm   57496556 Jun 27 00:17 /var/log/daemon.log.2.gz
```

This configuration seems to be set up in `/etc/logrotate.d/rsyslog`.
```
root@ip-172-20-60-238:~# cat /etc/logrotate.d/rsyslog
/var/log/syslog
{
        rotate 7
        daily
        missingok
        notifempty
        delaycompress
        compress
        postrotate
                invoke-rc.d rsyslog rotate > /dev/null
        endscript
}

/var/log/mail.info
/var/log/mail.warn
/var/log/mail.err
/var/log/mail.log
/var/log/daemon.log
/var/log/kern.log
/var/log/auth.log
/var/log/user.log
/var/log/lpr.log
/var/log/cron.log
/var/log/debug
/var/log/messages
{
        rotate 4
        weekly
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
        postrotate
                invoke-rc.d rsyslog rotate > /dev/null
        endscript
}
```

Why is the docker daemon log only set to rotate once a week, when it can get to sizes exceeding 2.5GB, whereas the syslog is rotated daily? Also why is a logrotate rule set-up for `/var/log/docker.log` when that file won't exist?

I can't see anywhere in this repo where the `rsyslog` logrotate rule is setup. (I note that it has a different modification date to the other files, so assume it is configured somewhere else, in which case where?).

**Comment by chrislovecnm** [comment]
If it is being configured by kops, the code would be under nodeup/

**Comment by ianjoneill** [comment]
It would appear that the `rsyslog` package is installed in the base Debian Jessie image along with the above logrotate configuration (you can see it listed at https://packages.debian.org/jessie/amd64/rsyslog/filelist).

As the daemon log gets rather large, would it not be down to Kops to increase the frequency and maximum file size which determine when the `/var/log/daemon.log` file is rotated (more along the lines of the added configuration for `/var/log/docker.log`)?

I see that in Kops 1.7 (specifically #2847) you are going to increase the base node/master root volume size, but that just works around the problem, rather than solving it.

**Comment by chrislovecnm** [comment]
@ianjoneill #2847 was put in because the default image size needed to be increased.  It was not put in to address this problem, which I agree needs to be resolved.
