### ISSUE TITLE
non-interactive kops edit

### ISSUE THREAD

**Issue by hypergig** [kubernetes/kops#2819]
You can create a cluster from a file, but you can not manage an existing cluster from a file. You need to use the `kops edit` command which is interactive, then `update`. 

Being that the file I use in the `create` is templated, it would be really nice if I can just continue to manage my cluster with the same template. I would like to do:

```
kops create cluster -f cluster.1.0.0.yml
```
later down the line
```
kops edit cluster -f cluster.1.1.0.yml
kops rolling-update cluster
```

I know there is a `replace cluster -f` but it is unclear to me if this (very disruptively) deletes the existing cluster and then makes a bran new one. No options for rolling updates.

**Comment by chrislovecnm** [comment]
The replace works the same as edit.

**Comment by hypergig** [comment]
> The replace works the same as edit.
@chrislovecnm does that mean you need to do an `update` or `rolling-update` after?

**Comment by chrislovecnm** [comment]
@hypergig yes.  `kops` is atomic, meaning that if you need to replace say kube-apiserver, then you will need to roll the cluster.

**Comment by chrislovecnm** [comment]
I am opening an issue to provide user feedback after running `replace -f`, also I think I have documented it in the new yaml documents.

@hypergig do you mind if we close this?

**Comment by hypergig** [comment]
so I tested this and it is unclear to me what attributes in the config files taint the resource and consider it for update? If I force the rolling update my changes seem to go through of course. Also, is destroying the whole cluster and recreating it the only way to push changes to it? For instance, updating cloud tags shouldn't be so destructive right?

Lastly... where can I find documentation on the config files?
