### ISSUE TITLE
Unable to get an AWS test cluster running with a private hosted zone and a bastion

### ISSUE THREAD

**Issue by deinspanjer** [kubernetes/kops#2821]
My goal was to have the following setup:

1. As many AWS objects created by kops as possible: VPC, subnets, routes, gateways, NAT, ELB, instances, DNS records etc.
2. A private DNS hosted zone which is a subdomain of our private (split horizon) root domain
3. A bastion which is the only way to be able to ssh into nodes of the cluster
4. The ability to interact with the cluster via my local kubectl (either with a tunnel to the bastion or SOCKS proxy or whatever works

I attempted the following:

1. Created a private hosted domain, k8s.example.com
2. Added the NS entries for the subdomain to the private hosted domain example.com
3. Ran kops create cluster --zones us-east-1a --dns private --dns-zone <ZONEID_of_k8s.example.com> --topology private --networking calico --bastion $NAME
4. Ran kops update cluster $NAME --yes
5. Waited
6. Looked up the public IP of the bastion instance in EC2
7. Tried to ssh to that IP.

ssh and ping both time out.  I grabbed a full dump of all the describe-* output of aws-cli for the objects created by kops, but wasn't able to find anything useful about what is wrong.

Were these steps not appropriate? Did I miss something? Does kops not support this goal? Does this work for anyone else?

**Comment by trung** [comment]
Don't think you can ping, but ssh should work.
@deinspanjer can you check the bastion host security group using AWS console to see if there's an entry for SSH inbound?

**Comment by deinspanjer** [comment]
That was set up.  I've since torn down the cluster, but before I did, I run describe-* statements on all the relevant assets that kops created.  I'd be happy to share them directly if you want to look.  Didn't want to attach them directly to the issue since they contain account IDs and such.

**Comment by trung** [comment]
can you paste the output of `kops get ${NAME} -o yaml` after the cluster has been created?

I did something similar to your goal and got it working. All i need is to create a VPC beforehand and here is an example of my `kops` command:

```bash
kops create cluster ${NAME} \
 --dns private  \
 --topology private \
 --api-loadbalancer-type internal \
 --zones ${AZs} \
 --cloud aws \
 --vpc ${VPC} \
 --network-cidr ${NETWORK_CIDR} \
 --networking calico \
 --state ${KOPS_STATE_STORE} \
 --ssh-public-key ./kops-key.pub
 --bastion
```
