### ISSUE TITLE
Missing IAM role Route53 permission

### ISSUE THREAD

**Issue by igoratencompass** [kubernetes/kops#2825]
The private zone given to kops `tftest.encompasshost.internal` is a sub-zone of the master zone `encompasshost.com` meaning there is a NS record in the master pointing to the private zone and the problem is that the `route53-mapper` add-ons try to read the records in the master zone for which they don't have privileges:

```
I0606 02:36:35.740985  1 dnscontroller.go:301] applying DNS changeset for zone tftest.encompasshost.internal.::SUB_ZONE_ID
W0606 02:36:35.884586  1 dnscontroller.go:119] Unexpected error in DNS controller, will retry: error querying resource records for zone "encompasshost.com.": error querying resource records for zone "encompasshost.com.": AccessDenied: User: arn:aws:sts::xxx:assumed-role/masters.tftest.encompasshost.internal/i-xxx is not authorized to perform: route53:ListResourceRecordSets on resource: arn:aws:route53:::hostedzone/MASTER_ZONE_ID status code: 403, request id: f56063d9-4a60-11e7-ac19-63ebdaa87c27
```

so we need permissions for **both** the master and the sub zone. I think this user case needs to be at least documented in the plugin so the user are aware of it.

Also the `route53-mapper` works after I updated the masters IAM with `route53:ListHostedZonesByName`

```
I0606 02:16:31.319233 1 service_listener.go:132] Creating DNS for my-app-svc service: internal-xxx-xxx.eu-west-1.elb.amazonaws.com -> my-app.tftest.encompasshost.internal
W0606 02:16:31.421215 1 service_listener.go:153] No zone found for encompasshost.internal: AccessDenied: User: arn:aws:sts::xxx:assumed-role/masters.tftest.encompasshost.internal/i-xxx is not authorized to perform: route53:ListHostedZonesByName status code: 403, request id: 27d5495c-4a5e-11e7-994b-1daa16da547c
```

which is missing in Kops.

**Comment by chrislovecnm** [comment]
This should be documented better in the addon

**Comment by igoratencompass** [comment]
@chrislovecnm PR created as per our discussion on Slack, please let me know if this is the right place to edit the docs or any other remarks you might have.

**Comment by chrislovecnm** [comment]
Thanks! .... made a comment about the CLA.

**Comment by icicimov** [comment]
@chrislovecnm second try mate sorry for the mess

**Comment by chrislovecnm** [comment]
Closing as fixed
