### ISSUE TITLE
support etcd3

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2842]
In order to support etcd3 we need to ensure that this issue is resolved https://github.com/kubernetes/kubernetes/issues/43600

**Comment by archyufa** [comment]
@chrislovecnm It seems kubernetes/kubernetes#43600 has been fixed. Can this PR now can be considered as closed and unblock road to etcdv3 ?

**Comment by zioalex** [comment]
Hi guys, any update here?

**Comment by chrislovecnm** [comment]
We have https://github.com/kubernetes/kops/pull/3176 in the alpha release, and https://github.com/kubernetes/kops/issues/3475 open for documentation.

https://github.com/kubernetes/kubernetes/issues/43600 has been resolved in core, but I think there still are some upgrade challenges.  We have not tested a migration with our rolling update, so we are only recommending ectd3 for new clusters.

**Comment by blakebarnett** [comment]
Using the kops 1.8.0-alpha.1 build, upgrading a k8s 1.7.7 cluster built with kops 1.7.0

verified etcd v2 -> v3 upgrade is a no-go at least with 3.0.17: `2017-10-02 22:24:56.772105 E | rafthttp: request sent was ignored by peer 4bdc0ce04b3f39b5 (server version incompatible)`

It seems to know it should upgrade: `2017-10-02 22:17:02.340452 I | etcdserver: starting server... [version: 3.0.17, cluster version: 2.2]`

But it just spins with the incompatible message.

**Comment by chrislovecnm** [comment]
@blakebarnett more details please :)  I think what you are saying is that we allow a user to upgrade from etcd2 -> etcd3 and we should not.

**Comment by blakebarnett** [comment]
I think we just need to use this image: https://github.com/kubernetes/kubernetes/issues/43600#issuecomment-333760185

I'll try it later today.

**Comment by blakebarnett** [comment]
According to this doc: https://github.com/mml/kubernetes.github.io/blob/eb34336f01b7c4c710d1d7a868267510b226cb86/docs/admin/etcd_upgrade.md 

We need to make the etcd static pod manifest run `/usr/local/bin/migrate-if-needed.sh` and set the following vars:
```
TARGET_STORAGE=etcd3
ETCD_IMAGE=3.0.17
TARGET_VERSION=3.0.17
STORAGE_MEDIA_TYPE=application/json
DATA_DIRECTORY=/var/etcd/data```

I suppose we could have it conditionally do this based on a cluster spec key, but it seems like maybe it's a good candidate for an `initContainer` in our static pod manifest.

This also requires that the TLS setting match the previous cluster state, if changing to TLS is desired you need to do it separately after the cluster has been migrated.

**Comment by chrislovecnm** [comment]
Closing as we support this now
