### ISSUE TITLE
Support read-only cloud resources

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#285]
For people that want to launch into an existing VPC / subnet / route-table etc, it might be interesting to see if we could support read-only resources.  So we would notify that a setting was not the setting we wanted, but we would not change them.

Gets complicated with terraform output, which I don't think has this concept.

**Comment by OleksandrBerezianskyi** [comment]
listing hacks we've applied to achieve this with kops 1.3
1) generate terraform output, remove subnet, routetable, routetable association and routes. replace subnet with a given subnet id.
2) edit `config` on s3:
```zones:
    - cidr: YOUR_SUBNET_CIDR
```
3) edit `cluster.spec` on s3:
```zones:
    - cidr: YOUR_SUBNET_CIDR
```
4) apply terraform

**Comment by justinsb** [comment]
I believe we now have this, to a limited extent.

We can run in an existing VPC (no problem)
We can run in existing subnets

We can't currently run two k8s clusters in the same subnet, or at least they can't create ELBs for services with Type=LoadBalancer.  This is because we don't have a way to mark a subnet as shared at the kubernetes level, but we are working on it: https://github.com/kubernetes/features/issues/173

Documentation is here:
https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md

I'm going to close, but if there are further issues please either comment/reopen here, or (better I think) open a new issue for each thing we don't support reuse of!
