### ISSUE TITLE
Document recommended size/number of instance groups for Kubernetes workers

### ISSUE THREAD

**Issue by kenden** [kubernetes/kops#2851]
"If you have a cluster of 40 nodes you should not have just one instance group"

It would be nice to have recommendations/links/pointers about a good size for instance groups in the documentation.

[creating-a-new-instance-group](https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#creating-a-new-instance-group) could be a good place to add it.

This is from from https://github.com/kubernetes/kops/pull/2818#issuecomment-312067831

**Comment by chrislovecnm** [comment]
Yes would be good to have some examples

Also, if you are using ebs volumes, using a ig that spans an az can cause outages. Ebs volumes do not span az.

It is best practice to have an ig per az, locking the nodes with Ebs volumes to an az.
