### ISSUE TITLE
Private DNS zones broken?

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#2852]
kops version: 1.6.2
k8s version: 1.6.4
upgrading to  k8s version: 1.6.6

```
I0703 12:19:44.587053   99165 utils.go:148] Found matching hosted zone ".stage.us-west-2.aws.k8s", but it was "Private" and we require "Public"

error determining default DNS zone: No matching hosted zones found for ".stage.us-west-2.aws.k8s"; please create one (e.g. "aws.k8s") first
```

**Comment by justinsb** [comment]
If you specify `--dns private` does it then work?

For an existing cluster, the equivalent change is:

```
  topology:
    dns:
      type: Public
```
to

```
  topology:
    dns:
      type: Private
```

**Comment by blakebarnett** [comment]
I guess the validation is actually working now :)

We had `type: Public` before for our private zones and it working (incorrectly) it seems.  Thanks!
