### ISSUE TITLE
Docs: Create utility subnets for existing vpc per "cannot mix subnets with specified ID and unspecified ID"

### ISSUE THREAD

**Issue by StevenACoffman** [kubernetes/kops#2855]
Can you please provide documentation or a reference on how to create an appropriate type `utility` subnet in AWS in the [run in an existing vpc document](https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md)?

#### Background

I'm using kops 1.6.2, kubectl 1.6.6 and attempting to reuse existing private subnets for an existing vpc following the documentation and #1220. 

While I have the existing **private** subnets, I don't have any existing type **utility** subnets, and so when following the documented procedure I get the error:
> cannot mix subnets with specified ID and unspecified ID

I'm not sure how to create `utility` subnets using the aws cli (outside of kops).

### Existing resources:

VPC id: **vpc-xxxxxxxx**
Route table id: **rtb-xxxxxxx1**
Subnets id: **subnet-xxxxxxxa**,**subnet-xxxxxxxb**,**subnet-xxxxxxxc**

### Steps to reproduce:

1.  Create a VPC
2.  Enable DNS Hostnames as per the requirment
3.  Create a subnet in that VPC
5.  Create cluster:

```
kops create cluster \
  --name $KOPS_NAME \
  --state $KOPS_STATE_STORE \
  --node-count 3 \
  --cloud aws \
  --zones us-east-1a,us-east-1c,us-east-1d \
  --master-zones us-east-1a,us-east-1c,us-east-1d \
  --dns-zone $SUBDOMAIN \
  --node-size t2.medium \
  --master-size t2.medium \
  -v 10 \
  --node-security-groups $SECURITY_GROUPS \
  --master-security-groups $SECURITY_GROUPS \
  --network-cidr "172.28.0.0/16" \
  --topology private \
  --networking weave \
  --bastion 
```
1.  Edit cluster. Change Subnet CIDR and ID.
2.  Update cluster:
`kops edit cluster $KOPS_NAME`

**Please note**: I am not updating type: **Utility** subnets, only private ones:

```
  - cidr: 172.28.136.0/21
    name: us-east-1a
  - cidr: 172.28.144.0/21
    name: us-east-1c
  - cidr: 172.28.152.0/21
    name: us-east-1d

```

to something like this

```
  - cidr: 172.28.136.0/21
    id: subnet-xxxxxxxa
    name: us-east-1a
  - cidr: 172.28.144.0/21
    id: subnet-xxxxxxxb
    name: us-east-1c
  - cidr: 172.28.152.0/21
    id: subnet-xxxxxxxc
    name: us-east-1d
```
### Result: "cannot mix subnets with specified ID and unspecified ID"

**Comment by StevenACoffman** [comment]
A second possibility: Do we need the `utility` subnets at all? What if I also remove the `--bastion` because I already have existing bastions able to access that subnet?

**Comment by StevenACoffman** [comment]
Looks like using/creating standard aws `public` subnets works ok. Can we just put the word `public` in place of `utility` as well?

**Comment by naveenkerati** [comment]
I have VPN access to the aws. Do I really need the utility subnet at all..?
