### ISSUE TITLE
Terraform kubernetes-provider support

### ISSUE THREAD

**Issue by RobertDiebels** [kubernetes/kops#2859]
Hi guys,

I don't know if this has come to your attention yet. Though terraform now has a [Kubernetes Provider](https://www.terraform.io/docs/providers/kubernetes/index.html) 

It would be great if kops could generate the settings for a kubernetes-provider along with config to spin up a cluster.

Let me know what you think,
- Robert.

**Comment by Stelminator** [comment]
I'd like this as well.

I think it should just take a few definitions of [aws_s3_bucket_object](https://www.terraform.io/docs/providers/aws/d/s3_bucket_object.html).  However, that would also require the `Content-Type` of something like `text/*` to be set by kops*, so that terraform will actually grab the body.

Ideally, those would come with [outputs](https://www.terraform.io/docs/configuration/outputs.html) as well.

*This would be nice for inspection of the data in a browser as well.

**Comment by Stelminator** [comment]
Something like this, though it still needs to be pulled out of the json object.
```
data "aws_s3_bucket_object" "secret_kube" {
  bucket = "${aws_s3_bucket.bucket_name.bucket}"
  key    = "cluster_name/secrets/kube"
}

output "secret_kube" {
  value = "${data.aws_s3_bucket_object.secret_kube.body}"
}
```

I didn't find an easy way to get the bucket key for the crt/key files.

**Comment by Stelminator** [comment]
FWIW, I ended up scripting `KUBECONFIG=kubectl.yaml kops export kubecfg`, uploading `kubectl.yaml` via the `aws` cli, and then using a `data "aws_s3_bucket_object" "..." {` block to pull it down, followed by a bunch of regexes.

**Comment by RobertDiebels** [comment]
@Stelminator Could you provide a link/gist to/with said script? As there hasn't been any response from contributors to this repo afaik.

**Comment by Stelminator** [comment]
@RobertDiebels these are the salient bits:
```
KUBECONFIG=kubectl.yaml kops export kubecfg --state=s3://.... <cluster_name>
aws s3 cp --content-type=text/x-yaml kubectl.yaml s3://......yaml
```
```
variable "kubectl" {
  type = "string"
}

output "config" {
  value = {
    server                     = "${replace(var.kubectl, "/^(?ms)(.*)server: ((?-s)(.*)$)(.*)$/", "$2")}"
    certificate-authority-data = "${base64decode(replace(var.kubectl, "/^(?ms)(.*)certificate-authority-data: ((?-s)(.*)$)(.*)$/", "$2"))}"
    client-certificate-data    = "${base64decode(replace(var.kubectl, "/^(?ms)(.*)client-certificate-data: ((?-s)(.*)$)(.*)$/", "$2"))}"
    client-key-data            = "${base64decode(replace(var.kubectl, "/^(?ms)(.*)client-key-data: ((?-s)(.*)$)(.*)$/", "$2"))}"
    username                   = "${replace(var.kubectl, "/^(?ms)(.*)username: ((?-s)(.*)$)(.*)$/", "$2")}"
    password                   = "${replace(var.kubectl, "/^(?ms)(.*)password: ((?-s)(.*)$)(.*)$/", "$2")}"
  }
}
```
It's not that pretty, but it works.

**Comment by RobertDiebels** [comment]
@Stelminator great thanks! 👍

**Comment by RobertDiebels** [comment]
/remove-lifecycle rotten
Removing lifecycle rotten.
@fejta Would like to know if there is any interest in picking this up.
