### ISSUE TITLE
Custom Manifests

### ISSUE THREAD

**Issue by gambol99** [kubernetes/kops#2860]
I've checked issues and can't see to find anything obvious in the docs / code. Does kops provide any method of introducing custom manifests on master nodes? .. Specifically we run a image policy webhook service via manifest on the master nodes (pointing to localhost) and was looking to replicate via kops (as the current build is proprietary) ...

**Comment by chrislovecnm** [comment]
At this point kops does not have a mechanism to deploy custom manifests after the cluster is started. We stop at giving u a functioning cluster, with the install.

**Comment by aledbf** [comment]
@gambol99 why not just use a kops hook?

**Comment by chrislovecnm** [comment]
Do hooks run before k8s?

**Comment by aledbf** [comment]
> Do hooks run before k8s?

Hooks do not declare dependencies in systemd so the answer is maybe?

**Comment by gambol99** [comment]
Ar ok, i never noticed these ... so kops hooks _(defined in the cluster spec)_ provides a means of adding custom containers into the build like below ... Ok, i'll give that a go. Thank you kindly
```YAML
hooks:
- execContainer
    image: <some_image>
    command:
    - a bunch of options commands
```
