### ISSUE TITLE
Clusters created with RBAC and flannel are non-functional

### ISSUE THREAD

**Issue by deedubs** [kubernetes/kops#2863]
When you create a cluster with `--authorization=RBAC --networking=flannel` flannel will not function until you apply 

https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel-rbac.yml

**Comment by justinsb** [comment]
Blog post with the missing stuff: http://arveknudsen.com/?p=386

**Comment by chrislovecnm** [comment]
Closing as fixed in master
