### ISSUE TITLE
what triggers a rolling update?

### ISSUE THREAD

**Issue by hypergig** [kubernetes/kops#2882]
We are currently using the "manifest" way of deploying our cluster, that is, using the `-f` option when we `create`.

I have made changes to the manifest, `replace` the cluster with the new manifest, done an `update`, and when I do a `rolling-update` it says no changes. I guess not all things taint the cluster and will trigger a rolling update?

Is there a definitive list of things that do taint a cluster?

**Comment by chrislovecnm** [comment]
We do not have a definition other than how the code works.  Also, I know we have some bugs around checking if an update is required.  For instance changing the docker version will not trigger a rolling-update to be required.  Technically any change that can be made should trigger a rolling-update, as `kops` clusters are immutable in regards to updating existing instances.

**Comment by hypergig** [comment]
@chrislovecnm would you say a good work around for this might be to compare manifests (old one vs new) and if they aren't the same, 'replace', 'update', then do a 'rolling-update --force' ?

**Comment by chrislovecnm** [comment]
Yep exactly. Also you should be able to just for a certain instance group ;)

**Comment by hypergig** [comment]
> Also you should be able to just for a certain instance group ;)
Ahh, so we need to add some logic in our deployment code.. ok.. not ideal but I get it. Maybe, we will move over to the terraform process, tainting and rebuilding is a little more predictable.

I will close as my question was answered. Thanks @chrislovecnm.
