### ISSUE TITLE
Clusters created with kops suffer from fatal docker / kubernetes issue - ""Error syncing pod, skipping: rpc error: code = 2 desc = Error: No such container"

### ISSUE THREAD

**Issue by philipn** [kubernetes/kops#2886]
An apology if this isn't the right place to file this issue.  If there is a more appropriate location, please let me know!  Someone on the K8s team closed the following issue, filed against kubernetes: https://github.com/kubernetes/kubernetes/issues/45626.  I'm not sure why the issue was closed -- maybe because it has more to do with a specific combination of the linux kernel, docker + kubernetes version, rather than kubernetes itself?

You'll see that everyone talking about encountering the issue (https://github.com/kubernetes/kubernetes/issues/45626) is using `kops` to initialize their cluster.

I may attempt to produce a minimal reproducible example, but if anyone else can, that would also be great!  I see the issue intermittently with kops 1.6.1 and k8s 1.6.4.

**Comment by armandocerna** [comment]
We are seeing this issue as well.

**Comment by philipn** [comment]
FYI I didn't see this error after upgrading the kops cluster as per my comment on https://github.com/kubernetes/kubernetes/issues/45626.
