### ISSUE TITLE
name collision in the terraform output

### ISSUE THREAD

**Issue by hellupline** [kubernetes/kops#289]
the resources "aws_security_group_rule" have a "default" name, which conflicts with other clusters created with terraform

**Comment by justinsb** [comment]
I thought I understood this, but I'm now not sure I do...

The security groups are named uniquely (incorporating the cluster name).  The security group rules do not incorporate the cluster name, but these are "virtual objects" - the name does not render into the AWS API.

I guess this would cause a problem if you took two TF cluster outputs, and rendered them both in the same TF run (e.g. by merging the directories).  Is that how you are seeing the problem?  And if not, how can I reproduce it?

**Comment by chrislovecnm** [comment]
@hellupline we have not heard back from you ... bump

**Comment by chrislovecnm** [comment]
We have PR inbound thay may help with this ... I am looking through issues to test against #1183 - no promises but we need to test.

**Comment by justinsb** [comment]
Haven't heard anything here.  I believe the problem must be when you have 2 kops-generated terraform output files, in the same TF "universe".  Then the rules will have the same name.

I _think_ this is the problem that modules are supposed to solve, so I am going to close as a duplicate of #1026, and also opened #1381

Closing, but if there's something else, let's reopen.
