### ISSUE TITLE
deploying the nginx ingress addon requires permission to create config map

### ISSUE THREAD

**Issue by BradErz** [kubernetes/kops#2895]
E0710 14:44:46.059593       7 leaderelection.go:287] Failed to update lock: User "system:serviceaccount:kube-ingress:nginx-ingress-controller" cannot update configmaps in the namespace "kube-ingress". (put configmaps ingress-controller-leader-nginx)

There is also an error for creating the config map.

**Comment by aledbf** [comment]
@BradErz the addon is not up to date with the rbac requirements.
Please check https://github.com/kubernetes/ingress/tree/master/examples/rbac/nginx
