### ISSUE TITLE
Option to turn off basic auth

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#290]
This may be as simple as _not_ passing basic-auth-file to the api server, but need to understand what else this disables!

**Comment by robscott** [comment]
Thanks for adding this issue. For what it's worth, our [fork that completely removes basic auth](https://github.com/SpireTeam/kops) is working well for us. Obviously this isn't a great solution for the main project as many people actually will want basic auth enabled.

**Comment by chrislovecnm** [comment]
@robscott are you interesting in helping move support into main?

**Comment by justinsb** [comment]
We do have the flag mapped in 1.5.0, so I would close, but I hope to look more at the fork (thanks @robscott) as we look at making auth easier to use.  Moving to 1.5.1

**Comment by robscott** [comment]
@justinsb My fork is really nothing much other than just removing basic auth entirely. It was rather hacky so probably not worth looking at. I'm glad this option has made it into the main project, I'm really looking forward to upgrading to 1.5. What flag do I need to use to disable basic auth?

**Comment by chrislovecnm** [comment]
Is this fixed?

**Comment by jurgenweber** [comment]
any news on how to do this?

**Comment by chrislovecnm** [comment]
Not implemented as of yet

**Comment by jurgenweber** [comment]
I am super keen to see this happen.

**Comment by pviniciusfm** [comment]
Any updates about this issue?

**Comment by valdisrigdon** [comment]
https://github.com/kubernetes/kops/pull/4799 should fix this.
