### ISSUE TITLE
Label IG nodes with kops IG group name

### ISSUE THREAD

**Issue by mtanski** [kubernetes/kops#2904]
It would be really convenient if kops automatically applied K8 node labels indicating which kops IG the nodes belong to. This is useful when trying to analyze load / performance / placement of nodes in a IG (esp. if it's autoscaling a lot, like batch workloads).

A simple label like: "kops.kubernetes.io/instance-group: ${IG_NAME}" would be great.

There already is a k8 label for node type, but it's always node or master so it's not super useful. "kubernetes.io/role: node"

My use case: I'm building an app called "statster" for collecting metrics (higher level then heapster). Being able to collect these metrics by nodes in a IG (without the user labeling it) would make it possible to implement it.

I'm aware I can get the tags from the AWS APIs for instances, but if I want to collect stats from multiple cloud providers this would abstract it away from me.

**Comment by chrislovecnm** [comment]
/lifecycle frozen
/remove-lifecycle rotten

This may already be fixed, if not, great idea

**Comment by palmerabollo** [comment]
Using kops 1.9.x, I can see the label `kops.k8s.io/instancegroup=my-instance-group` so I guess it's fixed now.

**Comment by rifelpet** [comment]
Agreed, kops adds the `kops.k8s.io/instancegroup` node label, this should be good to close.
/close
