### ISSUE TITLE
Feature Request: Write files per instance group

### ISSUE THREAD

**Issue by ottoyiu** [kubernetes/kops#2907]
There are more and more Kubernetes features that require a static configuration file to be defined prior to the start of the API server. Several examples of this are:
- PodNodeSelector Admission Controller requires a configuration file to be defined, with an APIserver flag definining its location:
https://kubernetes.io/docs/admin/admission-controllers/#configuration-file-format-1

- Advanced Audit Log requires a Policy file to be defined:
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#advanced-audit

- Kubelet TLS bootstrapping requires a token authentication file:
https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/

kops should provide the ability for the user to define arbitrary file paths and file contents, within the InstanceGroup spec, similarly to cloud-config, and have it be written to disk, prior to Kubernetes components (eg. kubelet, API server) starting:
https://coreos.com/os/docs/latest/cloud-config.html#write_files

If this seems like a sane feature request, I'll see if I have some time to work on it.

Similar Request: #2779

**Comment by gambol99** [comment]
Hi @ottoyiu ... I raised https://github.com/kubernetes/kops/pull/3090 which might solve your issue .. assuming its merged :-)

**Comment by ottoyiu** [comment]
@gambol99 awesome!! :dancing_men: :dancing_women:  thank you very much! :)

**Comment by chrislovecnm** [comment]
Closing as fixed
