### ISSUE TITLE
Need to set higher `max_user_instances`

### ISSUE THREAD

**Issue by egeland** [kubernetes/kops#2912]
Related to https://github.com/kubernetes/kubernetes/issues/32526 we find that we're running out of inodes/watchers, as the default of `128` is too low.

We need to set this to a more reasonable value, like `8192` as mentioned in that issue.

@steelecliftonberry is working on a PR now.

**Comment by wallrj** [comment]
Maybe caused by https://github.com/kubernetes/kubernetes/issues/64315
