### ISSUE TITLE
rolling-update doesn't seem to wait until replaced master is usable

### ISSUE THREAD

**Issue by kaazoo** [kubernetes/kops#2914]
When changing something in the cluster config which affects all masters, kops replaces them one by one when running 'kops rolling-update cluster --yes'. However, it doesn't seem to wait until a replaced master is up and working (e.g. ready state in k8s) before replacing the next master.

This can lead to running out of master / etcd consensus and might causes service interruptions.

I noticed that when using my own CentOS 7 based AMI, which has some custom startup scripts in cloud-init and can take a little bit longer to boot.

**Comment by chrislovecnm** [comment]
It does not wait, this was as designed. There is a feature flag that does validate the cluster.

**Comment by kaazoo** [comment]
OK, I enabled the feature flag and it seems to work. Thanks.

Is there any plan to enable drain+validate per default?

**Comment by chrislovecnm** [comment]
Drain and validated is now enabled by default in master.  Can we close this?

**Comment by kaazoo** [comment]
Thanks!
