### ISSUE TITLE
kops create cluster having problem with IAM Role policy

### ISSUE THREAD

**Issue by bdshibly** [kubernetes/kops#2918]
While creating kubernetes cluster with kops I am getting the following error 

W0712 21:42:53.623240   23375 executor.go:109] error running task "IAMRolePolicy/nodes.ue1qa1kubernetes1.aws.shibly.com" (9m39s remaining to succeed): error rendering PolicyDocument: error opening resource: DNS ZoneID not set
W0712 21:42:53.623303   23375 executor.go:109] error running task "IAMRolePolicy/masters.ue1qa1kubernetes1.aws.shibly.com" (9m39s remaining to succeed): error rendering PolicyDocument: error opening resource: DNS ZoneID not set

my command is 

kops create cluster --cloud=aws --name=ue1qa1kubernetes1.aws.shibly.com --state=s3://ue1qa1kuberntes1 --associate-public-ip=false --topology=private --networking=weave --zones=us-east-1b --node-count=1 --node-size=m4.xlarge --master-size=m4.xlarge --dns-zone=ue1qa1kubernetes1.aws.shibly.com --vpc=vpc-id --network-cidr=cidr

how can I resolve the issue?

**Comment by chrislovecnm** [comment]
Can you try w/o the `--dns-zone` or the DNS zone may be `aws.shibly.com`, or the actual zone id in AWS.

**Comment by chrislovecnm** [comment]
Also, do you have full admin perms? You need at least https://gist.github.com/chrislovecnm/c4adac1316bd0a3b9bba4e5d5c79e856

**Comment by bdshibly** [comment]
I could deploy the cluster on different AZ.

**Comment by tehale** [comment]
I had same issue and I used AWS hosted zone ID instead hosted zone name..
