### ISSUE TITLE
Kubelet should not try to determine public DNS in private VPC setup

### ISSUE THREAD

**Issue by kaazoo** [kubernetes/kops#2920]
I have a cluster created in private VPC subnet and Kubelet is spamming my syslog **every 10 sec** with the following message:
```
kubelet[14067]: I0713 07:28:18.742245   14067 aws.go:937] Could not determine public DNS from AWS metadata.
```

Is there a way to automatically deactivate this when creating a cluster for private VPC subnet?

**Comment by chrislovecnm** [comment]
This code is actually not in this repo. This code is in kubernetes/kubernetes please open an issue in that repo ;(

**Comment by kaazoo** [comment]
kubernetes/kubernetes/pull/40763
openshift/origin/pull/12760

**Comment by chrislovecnm** [comment]
Closing
