### ISSUE TITLE
Documentation of Docker options in cluster spec

### ISSUE THREAD

**Issue by kaazoo** [kubernetes/kops#2921]
Currently, there doesn't seem to be any documentation on the possible Docker options in cluster spec. People using kops might want to switch Docker storage driver or Docker version and have a hard time finding out how to do it.

**Comment by eljefedelrodeodeljefe** [comment]
Any guidance for making a PR would be welcomed. I need that too, since running and insecure registry seems not straightforward atm.

**Comment by chrislovecnm** [comment]
Adding documentation to the clusterspec document would be awesome. We also need help getting the API server docs published to kubernetes.io
