### ISSUE TITLE
HostPort Support for CNI plugins

### ISSUE THREAD

**Issue by Arttii** [kubernetes/kops#2922]
This relates to adding the support for defining HostPorts for Kube cluster using CNI networking.

**Questions**

I was wondering if there's a plan to include a fix for the HostPort issue as seen [here](https://github.com/kubernetes/kubernetes/issues/31307). 

**Actions**
I have tested this, and basically a new verison of the cni plugins+an update to [Weave](https://github.com/weaveworks/weave/issues/3016) and [Calico](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/calico-policy-controller/calico-node-daemonset.yaml) is necessary, but it works.

Would be nice to have this in the 1.7 release.

**Comment by chrislovecnm** [comment]
@justinsb is this supported?

**Comment by dixudx** [comment]
>  is this supported?

@chrislovecnm Supported.
