### ISSUE TITLE
Not supported region:cn-north-1

### ISSUE THREAD

**Issue by wangycc** [kubernetes/kops#2933]
Now support cn-north-1 this region yet? There is no route53 dns service

**Comment by qqshfox** [comment]
You can use `gossip` to create a cluster in `cn-north-1`. See #2889 and #2947. I think you have to build `nodeup` and `kops` on your own by now.

**Comment by chrislovecnm** [comment]
Thanks @qwshfox!

**Comment by mgyong** [comment]
I am trying to provision kubernetes cluster in cn-north-1 using kops. I was hoping if anyone can provide detailed step by step on how to do this for cn-north-1. I am having trouble using the instructions at https://github.com/kubernetes/kops/pull/2889

**Comment by chrislovecnm** [comment]
@qqshfox are you able to document this? I do not have access to the CN region

**Comment by qqshfox** [comment]
@mgyong what kind problem you are facing?
@chrislovecnm I had intended to write a doc to describe the process but I'm busy with other projects these days. I'll try to write something this weekend hopefully.

**Comment by chrislovecnm** [comment]
@qqshfox that is awesome!
