### ISSUE TITLE
kops replace should behave like kubectl apply?

### ISSUE THREAD

**Issue by mjsilva** [kubernetes/kops#2941]
Hi,

I’m trying to manage kops as code so we can achieve reproducible clusters, version changes, pull requests etc… 

I want to make my ig.yaml (got it with `kops get ig -o yaml`) dynamic so people can just add and remove instance groups at will. 

This is what my template file looks like https://gist.github.com/mjsilva/ffa474f9bb6042dfbcdf5400493a187f and this is an example of what a cluster config looks like https://gist.github.com/mjsilva/9458b9fd80070deee563ddd518a13037 

I’ve hit a wall when I try to do a `kops replace -f ig.yaml` and a IG was never created before. Kops returns the the error `replacing instanceGroup: error writing InstanceGroup: cannot update configuration file s3://xxxx/k8s/xxx/instancegroup/default: does not exist`

It’s my understanding that `replace` command doesn’t really behave like `apply` in `kubectl`. Meaning it doesn't decide either to update or created based on if exists or not already. 

The workaround I'm thinking is validating if an instance group exists in the bucket and then perform an `replace` or a `create` depending on it. This is a bit of a PITA and doesn't cover deletes.

Ideally you'd have the option to do a `kops apply ig -f ig.yaml` and kops would take care of creating, updating and deleting by diffying what's in the bucket and what's in the ig.yaml file.

Thoughts?

Thanks!

**Comment by gambol99** [comment]
hi @mjsilva ... i raised https://github.com/kubernetes/kops/pull/3089 recently. Albeit the main problem with running kops as code is the fact it can't diff between spec files. Namely that is you make a change in same the kubelet options in cluster.spec, the update / rollout is completey unaware of it. This is problem due to the fact kops replace / edit updates the bucket straight away, thus nothing to diff against

**Comment by chrislovecnm** [comment]
@gambol99 we need to figure out versioning.... @justinsb how does k8s do there versioning?  etcd?

**Comment by toxeek** [comment]
I would refer you to the replace GitHub, where you find this script,

```bash
if ! kops get cluster --name "$NAME"; then
    kops create -f "kops/$CLUSTER/$REGION.yaml"
else
 kops replace -f "kops/$CLUSTER/$REGION.yaml"
fi

for ig in kops/$CLUSTER/instancegroup/*; do
  if ! kops get ig --name "$NAME" "$(basename "$ig")"; then
    kops create -f "$ig"
  else
    kops replace -f "$ig"
  fi
done
```
