### ISSUE TITLE
Not support region ap-southeast-1 (singapore)

### ISSUE THREAD

**Issue by abdidarmawan007** [kubernetes/kops#2942]
Kops not support region singapore ap-southeast-1 ?

kops create cluster --cloud aws --zones=ap-southeast-1 terminator --yes

error populating configuration: Region is not a recognized EC2 region: "ap-southeast-" (check you have specified valid zones?)

**Comment by chrislovecnm** [comment]
`--zones=ap-southeast-1` so ap-southeast-1 is a region :)

`--zones=ap-southeast-1a` would be a zone :)

We support:

```go
        "ap-southeast-1a": kops.CloudProviderAWS,
        "ap-southeast-1b": kops.CloudProviderAWS,
        "ap-southeast-1c": kops.CloudProviderAWS,
        "ap-southeast-1d": kops.CloudProviderAWS,
        "ap-southeast-1e": kops.CloudProviderAWS,
```

**Comment by abdidarmawan007** [comment]
ohh thanks,
