### ISSUE TITLE
Calico update is needed for kops 1.7

### ISSUE THREAD

**Issue by fraenkel** [kubernetes/kops#2975]
For Kubernetes 1.7, kops needs to install calico v2.3 (http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/hosted/calico.yaml)

Kube 1.7 changed the behavior of NetworkPolicy and requires a newer version of Calico. Kube itself ships a slightly modified version which uses Typha as the policy controller. kops could choose to leverage this as well which is found https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/calico-policy-controller.

**Comment by ringods** [comment]
I think this is already resolved with PR #3206 where the version is bumped to 2.4.1

**Comment by fraenkel** [comment]
I will close it out.
