### ISSUE TITLE
Support AWS new g3 instance family

### ISSUE THREAD

**Issue by stevenc81** [kubernetes/kops#2978]
Would be cool to have the support for it :D

```
instance type not handled: "g3.4xlarge"
```

**Comment by chrislovecnm** [comment]
This is a super easy fix btw ... here is when we added i3's https://github.com/kubernetes/kops/commit/84bd5aca3ad5452ccf863d73ec3b68d16b183905

**Comment by chrislovecnm** [comment]
I got bored ... so here you go.  If someone can tell me what the ECU for the g3 is ... will add that.

**Comment by stevenc81** [comment]
Thanks for jumping in @chrislovecnm ! I'm looking at this table and trying to figure out the ECUs for each type (https://aws.amazon.com/blogs/aws/new-next-generation-gpu-powered-ec2-instances-g3/)

http://hi.buffer.com/2m1J0f282f21/Image%202017-07-17%20at%206.21.41%20PM.png

I wonder where did we found the ECUs for `i3` family?
