### ISSUE TITLE
Describe how to alter kubeAPIServer runtimeConfig via manifest

### ISSUE THREAD

**Issue by StevenACoffman** [kubernetes/kops#2979]
Any tips on how to alter the kube-apiserver config? I see the runtimeConfig option: https://godoc.org/k8s.io/kops/pkg/apis/kops#KubeAPIServerConfig
And I see that there are options (`--enable-swagger-ui`) here:
https://kubernetes.io/docs/admin/kube-apiserver/
But I don't know if I should connect these wires, and if so, how.

I tried modifying the manifest via  [Manifests and Customizing Via API](https://github.com/kubernetes/kops/blob/master/docs/manifests_and_customizing_via_api.md) using a process of:

1. create the cluster
1. dump the yaml `kops get $KOPS_NAME -o yaml --state $KOPS_STATE_STORE > $KOPS_NAME.yaml`
1. edit the yaml
1. replace cluster:
  `kops replace cluster --name $KOPS_NAME --state $KOPS_STATE_STORE -f "${KOPS_NAME}.yaml"`
or edit cluster (since it supports full yaml): 
  `kops edit cluster --name $KOPS_NAME --state $KOPS_STATE_STORE`
1. update cluster `kops update cluster --name $KOPS_NAME --state $KOPS_STATE_STORE --yes`
1. rolling update `kops rolling-update cluster --name $KOPS_NAME --state $KOPS_STATE_STORE`

This is what I was trying to shove into the yaml:

```source-diff
spec:
+  kubeAPIServer:
+    runtimeConfig:
+      enable-swagger-ui: "true"
```

If I re-dump the manifest, it's just gone, with no validation errors, so I've done something incorrectly.

In a comment in #312 I see that:

```source-diff
spec:
+  kubeAPIServer:
+    authorizationMode: RBAC,AlwaysAllow
+    authorizationRbacSuperUser: admin
+    runtimeConfig:
+      rbac.authorization.k8s.io/v1alpha1: "true"
```
This is what I was modelling my manifest change on. However, that flag appears inside [the api-reference](https://github.com/kubernetes/kubernetes/tree/master/docs/api-reference). I don't know that the kubernetes api-reference allows you to alter the kube-apiserver container runtime flags.

**Comment by StevenACoffman** [comment]
So [this line](
https://github.com/nikhiljindal/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L547) leads me to believe that EnableSwaggerSupport is set to true by default.

I see that https://api.${KOPS_NAME}/swaggerapi works, but it's not the pleasant swagger-ui.

**Comment by dstokes** [comment]
I'm having a similar issue. After updating the authorization mode `kops update cluster` tells me there are no changes to be applied:

```diff
spec:
  authorization:
-  alwaysAllow: {}
+  rbac: {}
```

```shell
$ kops get cluster --full -o yaml | grep -B1 authorization
apiServerCount: 1
authorizationMode: RBAC,AlwaysAllow
authorizationRbacSuperUser: admin
--
runtimeConfig:
  rbac.authorizaiton.k8s.io/v1alpha1: "true"

$ kops update cluster
No changes need to be applied
```

**Comment by chrislovecnm** [comment]
@KashifSaadat was this addressed by a PR? I know you have done some work around this.

@dstokes which version of kops?

**Comment by dstokes** [comment]
@chrislovecnm Version 1.7.0

**Comment by KashifSaadat** [comment]
@chrislovecnm the PR I submitted includes the KubeAPIServer spec within the bootstrap scripts, so it triggers an update required for already running nodes. Will need to look into why the authorization plugin change isn't being picked up.

**Comment by KashifSaadat** [comment]
Tested these changes on kops master branch and both changes are being picked up correctly for a rolling update. @StevenACoffman @chrislovecnm can we close this issue?

**Comment by chrislovecnm** [comment]
Closing
