### ISSUE TITLE
Extend cli with cloud provider specific arguments

### ISSUE THREAD

**Issue by matyix** [kubernetes/kops#2983]
I'd like to extend the cli with cloud provider specific configs - whereas the easiest would be to just add it here - [Create Cluster](https://github.com/kubernetes/kops/blob/master/cmd/kops/create_cluster.go#L51) - this would  break the cross cloud provider functionality, as these items are provider specific, whereas this is generic. One example is AWS spot prices/bid/max arguments are different compared to Google's preemptible instances, and have no idea about VSpehere for instance. 

There are some initiatives like [Cloud abstraction #2486](https://github.com/kubernetes/kops/pull/2486) and [WIP - Cloud Implementation #2487](https://github.com/kubernetes/kops/pull/2487) the question is which way is to move forward and submit the PR? Currently the PR it's agains the [Create Cluster](https://github.com/kubernetes/kops/blob/master/cmd/kops/create_cluster.go#L51) but I don't believe its a good solution at all. What is the short term recommendation (beside maintaining a fork) and what is the long term approach where the PR should be landed.

Thanks in advance.

**Comment by matyix** [comment]
Found a workaround - closing it for now.

**Comment by kris-nova** [comment]
:smiley:
