### ISSUE TITLE
terraform: dasherize or underscoreize aws_key_pair resource names

### ISSUE THREAD

**Issue by seanknox** [kubernetes/kops#299]
Hey @justinsb, the `aws_key_pair` resource names generated via `--target=terraform` have colons in them which aren't allowed by Terraform (resource name can only contain letters, numbers, dashes, and underscores):

```
resource "aws_key_pair" "kubernetes-k8s-mycluster-com-d2:69:1f:2d:e4:77:42:9b:da:ee:0d:3d:c9:b0:e3:f3" {
  key_name = "kubernetes.k8s.mycluster.com-d2:69:1f:2d:e4:77:42:9b:da:ee:0d:3d:c9:b0:e3:f3"
  public_key = "${file("data/aws_key_pair_kubernetes.k8s.mycluster.com-d2:69:1f:2d:e4:77:42:9b:da:ee:0d:3d:c9:b0:e3:f3_public_key")}"
}
```

Think it'd be fine to just dasherize or underscorize the fingerprint for the resource name. Haven't used Go before, but if I can figure it out before you get to it I'll put up a PR. kops is a brilliant tool, thanks!

**Comment by justinsb** [comment]
Ah - that makes sense - I introduced this change recently as part of SSH key rotation, and didn't think through the terraform consequences!  I will fix!
