### ISSUE TITLE
kops should return better help message

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#30]
when I run `kops -h`, all the flags I want to use (except -v) are not listed.

`kops -h` should list all the flags (like --cloud --zones, --master-zones, --dns-zone etc)

**Comment by justinsb** [comment]
If you do `kops create cluster -h` you do get command specific help, and `kops` lists the first level commands, and `kops create` lists the second level commands.

Any suggestions for how to point people here?  Maybe `kops -h` should provide hints that you get more help on the sub-commands?

**Comment by zapman449** [comment]
turns out this is just a reading failure on my part.  you already include 'Use "kops [command] --help" for more information about a command'.
