### ISSUE TITLE
Kops fails to create IGW for private topology

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#3003]
Kops version: 1.7.0-beta.1

Steps to reproduce:
1. Create a VPC without an InternetGateway
2. Create a private toplogy cluster with a specific VPC for `spec.networkID`

You'll likely see errors like:
`W0719 18:53:11.584617   75566 executor.go:109] error running task "InternetGateway/test.k8so.ps" (5m43s remaining to succeed): InternetGateway for shared VPC was not found`

`W0719 18:49:02.605019   75566 executor.go:109] error running task "LoadBalancer/api.test.k8so.ps" (9m53s remaining to succeed): error creating ELB: InvalidSubnet: VPC vpc-9b9541fd has no internet gateway
	status code: 400, request id: 9b1bab08-6ced-11e7-8a41-bbb37402092a`

I assume this is related to the new feature to be able to use existing IGWs

**Comment by chrislovecnm** [comment]
Is it deleting the IG?

**Comment by blakebarnett** [comment]
Going to recreate the VPC fresh to find out.

**Comment by blakebarnett** [comment]
Ok I think creating IGWs for private topologies is just broken in the latest builds.  I must have created the initial cluster with version 1.6.2, I can't get it to work at all with a fresh VPC now.

**Comment by chrislovecnm** [comment]
Ping me if we need to figure this out before 1.7.0.

**Comment by blakebarnett** [comment]
Cluster spec: https://gist.github.com/blakebarnett/732309f63f2cc3658b0afbeca393d331

**Comment by chrislovecnm** [comment]
@blakebarnett I assume this is not the case in 1.6.x?  Was the bug introduced into the master in 1.7.x work?

**Comment by blakebarnett** [comment]
I think this has always been the case, and I've just never used an existing VPC that didn't already have an IGW.  Closing for now.
