### ISSUE TITLE
can kube-proxy mode flag be enabled?

### ISSUE THREAD

**Issue by imsky** [kubernetes/kops#3009]
it's currently commented out in code, would be nice to be able to set it explicitly (or at least have explicit defaults). right now trying to figure out if kube-proxy in our cluster is using iptables or userspace mode

**Comment by justinsb** [comment]
I would be shocked if it is using userspace.  iptables was introduced around k8s 1.1 IIRC.  It's not a flag that is commonly used, AFAIK.

You can double-check that you are using iptables by running `sudo iptables -t nat --list-rules` on one of your nodes - you should see a lot of rules, including two rules for each service that start with `-A KUBE-SERVICES...`

Of course if I'm wrong and there is a use for setting the flag, then do comment!

**Comment by imsky** [comment]
just checked one of our nodes and i do see those rules @justinsb - thanks for the tip!

**Comment by 2PacIsAlive** [comment]
it is possible the proxy-mode of my cluster without access to the nodes themselves?
