### ISSUE TITLE
Calico 1.7.0 migration template enables cross-subnet mode incorrectly

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#3018]
Kops version: 1.7.0-beta.1
Kubernetes version: 1.7.1

https://github.com/kubernetes/kops/blob/1.7.0-beta.1/docs/calico_cidr_migration/jobs.yaml.template#L18

Doing this without setting
```
spec:
  networking:
    calico:
      crossSubnet: true
```

And doing a `rolling-update` with `--force` means that the [Source/Destination check controller](https://github.com/kubernetes/kops/blob/master/docs/networking.md#enable-cross-subnet-mode-in-calico-aws-only) doesn't get installed and packets start disappearing.
  
This broke our staging cluster after upgrading to 1.7.1

Sadly adding `crossSubnet: true` didn't pickup the addon for k8s-ec2-srcdst either (maybe the channel didn't get updated for 1.7 for it?) I'll make a separate issue for this though.

**Comment by ottoyiu** [comment]
Thanks for the report, and apologies for the bug. I have submitted a PR for this, if you can review it :)
