### ISSUE TITLE
Cycle Nodes

### ISSUE THREAD

**Issue by owenmorgan** [kubernetes/kops#3028]
Hello, is there a way to cycle all the nodes in a cluster without applying updates? it would be good to cycle them once a week to clear out any issues

**Comment by chrislovecnm** [comment]
You can force a rolling update is you like. There is a --force flag

**Comment by owenmorgan** [comment]
any way of only updating nodes?

**Comment by zacblazic** [comment]
> any way of only updating nodes?

I think you're looking for the `--instance-group` flag.

Example:
```
kops rolling-update cluster \
  --name=[your cluster name] \
  --node-interval 8m \
  --instance-group nodes \
  --force \
  --yes
```
