### ISSUE TITLE
rename phase iam

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3029]
Need to make it more cloud gerneric
`kops update cluster --name k8s.example.com --phase iam`
maybe
`kops update cluster --name k8s.example.com --phase auth`

**Comment by justinsb** [comment]
GCE & AWS both call it IAM.  Do you have a suggestion?

**Comment by ajohnstone** [comment]
Iam seems seems sensible, it's short for "identity and access management"?

**Comment by chrislovecnm** [comment]
What does DO call it? My suggestion above was auth. I forget when vspheres user perm stuff is called.

**Comment by chrislovecnm** [comment]
Closing ... keeping iam
