### ISSUE TITLE
kops create with terraform creates cluster

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3035]
Execute:

```
$KOPS create cluster $CLUSTER_NAME \
        --zones $ZONES \
        --node-count $NODE_COUNT \
        --node-count $NODE_COUNT \
        --node-size $NODE_SIZE \
        --master-size $MASTER_SIZE \
        --kubernetes-version $K8S_VERSION \
        --networking $NETWORKING \
        --out $DIR \
        --target terraform
```

1. kops requires a ssh pem, probably should not
2. kops requires DNS, maybe
3. kops creates the cluster STATE_STORE - that is the big bug
4. exports kubecfg .. not sure if this should happen

```
kops get cluster $CLUSTER_NAME
```

Will show the cluster name.

**Comment by justinsb** [comment]
Can you break this down into specific bugs please, with more details on each.

**Comment by chrislovecnm** [comment]
Yah I can, but if you close the issue I never will
