### ISSUE TITLE
logrotate not good at log rotatation

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#3037]
logrotate often gets "stucks" when a disk is full (or near-full).

The debian issue seems to be this one:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=734688

A major contributor to full disks seems to be /var/log/fluentd.log, which is not typically rotated.

An indicator of the problem is that you have `file.log.1` and `file.log.1.gz`, with `file.log.1.gz` having zero size.  logrotate then fails to take any further action because it stops when it hits `file.log.1` and sees the already-existing `file.log.1.gz`.

Fixed in logrotate 3.11, available in stretch, but not backported to jessie.

**Comment by chrislovecnm** [comment]
Can we move to stretch? I think it fixes some cves we have as well
