### ISSUE TITLE
Support for ubuntu 17.04 with kops for nodes

### ISSUE THREAD

**Issue by sellers** [kubernetes/kops#3044]
kops version: Version 1.7.0-alpha.1 (git-d2e5d2064)

properly identify version of Ubuntu 17.04 so that nodes may start. 

**error message of relevanc**e:
`identify.go:40] unhandled lsb-release info “DISTRIB_ID=Ubuntu\nDISTRIB_RELEASE=17.04\nDISTRIB_CODENAME=zesty\nDISTRIB_DESCRIPTION=\“Ubuntu 17.04\“\n”`

**impact**:
Nodes will not start and register with controller due to non-matching LSB version. 

**priority**:
enhancement.

**Comment by chrislovecnm** [comment]
This is fixed in master, and will be released with 1.8.0 kops
