### ISSUE TITLE
Logrotate Improvements and Configurations

### ISSUE THREAD

**Issue by alok87** [kubernetes/kops#3047]
**What?**
- **Configurable logrotate:** Should we give the user the flexibility to configure log rotate values?
- **Documentation:** Is there any documentation in `kops` explaining how we are doing log rotation? Saw a couple of issues saying `docker` is managing logs and some says `logrotate` is doing it. It is very confusing going through all the chains of issues.
 
**Issue i am facing**
I am facing issues with `daemon.log`. We have to manually rotate daemon.log as it gets as huge as **`18-19 GB`**. I think something extra is getting logged(may be something in verbose mode). Or there could be an issue with log rotation/period of rotation also.
  
**System Details**
I installed kubernetes1.6.4 using `kops`(Version 1.6.0 (git-f69a313) in aws. 
Below is the os/release i have. 
```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by chrislovecnm** [comment]
Also I think we are running into https://github.com/kubernetes/kops/issues/3037

**Comment by alok87** [comment]
@chrislovecnm @justinsb my daemon.log in all the nodes are full of these errors(not really sure is this an error). most likely this is cause for such huge logs in short interval of time before the logrotation kicks in.

Do you guys know what could be causing this ?

```Jul 26 05:06:12 ip-10-0-15-7 kubelet[1697]: E0726 05:06:12.372530    1697 kuberuntime_container.go:385] ContainerStatus for XXXX error: rpc error: code = 2 desc = Error: No such container: XXXX
Jul 26 05:06:12 ip-10-0-15-7 kubelet[1697]: E0726 05:06:12.372543    1697 kuberuntime_manager.go:858] getPodContainerStatuses for pod "XXXX-20170713-112439-XXX--XXXX)" failed: rpc error: code = 2 desc = Error: No such container: XXXX```

**Comment by alok87** [comment]
@chrislovecnm @justinsb i also see `Started Kubernetes Kubelet Server.` printing in `kubelet.service` log every minute

but `systemctl status kubelet` shows that the kubelet was started at `Active: active (running) since Fri 2017-07-21 14:10:49 UTC; 4 days ago`.

**Comment by philipbjorge** [comment]
@alok87 -- Did you ever find a resolution for your issue?
We are facing the same problem now...

**Comment by alok87** [comment]
@philipbjorge which verison of kubernetes are you running it? and from which version of kops did u create it? I faced this issue with kops 1.5.X provisioned 1.6.4 kubernetes. This message of `Started` is not a restart but `kops` script actually printing that in system log.

Also these errors of log bombarding happens only when something is wrong with your node. Fixing those should reduce the log generation. We are upgrading to 1.7.4 with 1.7.0 kops on discussing with the community - log bombarment is because of some kernel fix not there.
