### ISSUE TITLE
Comment out : glog.Warningf("querying without label filter")

### ISSUE THREAD

**Issue by cohadar** [kubernetes/kops#3049]
You have multiple lines that are dead code that write to stderr creating false alarms.
glog.Warningf("querying without label filter")
glog.Warningf("querying without field filter")

These lines appear in multiple files so it looks like 'copy-paste coding' dead code.

Please comment these out.

**Comment by chrislovecnm** [comment]
Raised the logging level on them, and cleaned up the dead code.
