### ISSUE TITLE
node-count 0 sets node count = 2

### ISSUE THREAD

**Issue by vinayagg** [kubernetes/kops#3073]
When creating a cluster with kops, if i pass flag `kops create cluster --node-count=0 ...`
it creates the IG with node count = 2

node count 0 is needed for a single node clusters which are very helpful for experimentation and testing.

**Comment by chrislovecnm** [comment]
Because of the taints on the master it does not allow for the scheduling of pods, we do not have the option for a signal k8s instance. If cost is a concern use spot instances. .02 cents an hour for a m3.large

**Comment by vinayagg** [comment]
My point is that, if I create a script, I can always issue `kubectl cordon` to schedule pods on masters.
but if kops does not recognize node-count, I have to manually go into IG and make the count 0.
There should be at least one, non interactive mode to start 1 node cluster.

**Comment by vinayagg** [comment]
also, I have tried it
- kops create
- edit config to change node ig count = 0
- kops create ... --yes
- kubectl uncordon <master>

the cluster works very well. Is there a reason node count 0 is blocked?

**Comment by eedugon** [comment]
Have u tried creating the cluster with yaml manifest instead of create
cluster command?
If u can manually edit the IG then i would assume you can create your
clusters from yaml templates.

To create your first yaml template do kops get NAME -o=yaml

Regards!

**Comment by vinayagg** [comment]
Thanks eedugon. I have not tried 0 node cluster using yaml files but I will try, it could possibly work.

Though, it is much more difficult to automate creation of yaml files for cluster than it is to do `kops create`, but at least I have a path to automation.

I will still encourage to allow it on command line (why not afterall?)

**Comment by mad01** [comment]
The reason that not all options is available on command line is since the amount of option would be to many. Those option are available to you but you need to edit or create from a file

**Comment by vinayagg** [comment]
We are not talking about a new option, we are talking about existing option working in an non-intuitive and undocumented way and limiting automation.
I talked to at least one more person on slack who also ran into same issue.

**Comment by eedugon** [comment]
That's right, you want the nodes size (which is supported on create cluster
command) to allow a value of zero.

Regarding yaml files I really recommend you to try, because getting your
yaml is extremely easy and then you can really tweak it in the way you
want, for example:

RootVolumeSize: that's not supported with basic commands and you might want
bigger or smaller volumes.

Network cidrs for public topology: in my case i like having multiple
clusters on the same VPC and I prefer using /21 subnets than /19... In the
beginning I always raised the create command, then edit command and
manually updating the default subnets to my needs. But when I realized
about the yaml support it helped me a lot, and you can automate in the same
way than the kops create command, because to process the yaml you have to
raise a kops command also.

Anyway I don't know if size 0 will work with the yaml, I haven't tested, I
always set manually to 0 in AWS scaling groups... So definitely I will give
it a try too.

Regards!

**Comment by temujin9** [comment]
I have recently tested with setting the node count to zero in a YAML manifest. It does work, however it imposes several design decisions (such as managing a YAML manifest through version changes) that not all users will want. See https://github.com/kubernetes/kops/issues/4145 for my logs.

**Comment by fejta** [comment]
> Can we

Yes, the bot leaves instructions on ways to respond. I am unfamiliar with the details of this particular issue. 

What has changed to warrant reopening an issue no one will work on?

> should

Is this an offer to code up a PR that implements the desired behavior?

When issues sit around with no one stepping up to fix them, the bot flags this problem. After many months without progress/activity the bot automatically closes the issue (regardless of abstract merit it would have if someone were to willing to address it).

**Comment by temujin9** [comment]
@fejta The man was asking a simple priority question, of which you responded to exactly three words.

If you want PRs, or indeed any developer engagement, perhaps don't be so rude.

**Comment by tomekit** [comment]
Hi @vinayagg,
When I `uncordon` the only node I have, I get node/ip-xxx-xx-xx-xx.eu-west-1.compute.internal already uncordoned
However when I want to schedule a pod, it fails to be scheduled.
I get:
```
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  8m40s (x3 over 8m47s)  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
```
This is kops Version 1.11.0 (git-2c2042465) on AWS. Did you experience similar issue?

**Comment by tomekit** [comment]
Even though I've managed to run the one node (master) cluster, but the dynamic EBS provisioning doesn't work.
