### ISSUE TITLE
AWS credentials - should check ~/.aws/credentials

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#3081]
We seem to be skipping the local profile (I think)

**Comment by justinsb** [comment]
Looking into this further - the issue is that $HOME is not set by default in systemd tasks.  We should figure our where we want HOME to be!  An alternative is to explicitly set AWS_SHARED_CREDENTIALS_FILE

**Comment by rajivm** [comment]
We just set this in our environment:
```export AWS_SDK_LOAD_CONFIG=1```

If you want to use a specific profile:
```
export AWS_DEFAULT_PROFILE=staging-profile
export AWS_PROFILE=staging-profile
```

The combination of these env vars make both `kops` and `aws` cli use this profile.

**Comment by sidewinder12s** [comment]
Should probably just follow the variable precedence that the awscli uses: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#config-settings-and-precedence

Looks like AWS_SDK_LOAD_CONFIG hits both config & credentials (I've seen weird issues between the awscli/boto3/other SDK where it wasn't looking in all the usual places).
