### ISSUE TITLE
Migrate kops jobs to prow and off centralized jenkins before end of 1.9 timeframe

### ISSUE THREAD

**Issue by fejta** [kubernetes/kops#3083]
Please migrate your jobs to prow. If this is infeasible for some reason please let sig-testing know what we need to add to prow and/or plan to create and maintain your own jenkins instance if we cannot come up with a solution https://github.com/kubernetes/test-infra/issues/3778

This impacts the following jobs:

```
$ cat jobs/config.json | grep kops | grep '"ci'
  "ci-kubernetes-e2e-kops-aws": {
  "ci-kubernetes-e2e-kops-aws-canary": {
  "ci-kubernetes-e2e-kops-aws-release-1-7": {
  "ci-kubernetes-e2e-kops-aws-release-1.5": {
  "ci-kubernetes-e2e-kops-aws-release-1.6": {
  "ci-kubernetes-e2e-kops-aws-serial": {
  "ci-kubernetes-e2e-kops-aws-slow": {
  "ci-kubernetes-e2e-kops-aws-updown": {
  "ci-kubernetes-e2e-kops-aws-weave": {
```

@kubernetes/sig-cluster-lifecycle-bugs @kubernetes/sig-aws-misc

**Comment by fejta** [comment]
@kubernetes/sig-aws-misc 
@chrislovecnm @justinsb @krzyzacy 
Is this fixed?

**Comment by krzyzacy** [comment]
/assign
done
/close
