### ISSUE TITLE
broken link in aws documentation

### ISSUE THREAD

**Issue by clenimar** [kubernetes/kops#3094]
"advanced creation" link in [AWS](https://github.com/kubernetes/kops/blob/master/docs/aws.md#create-cluster-configuration) docs is broken. I couldn't find the docs elsewhere, that's why I'm filling this issue.

**Comment by chrislovecnm** [comment]
There is no advanced doc ;)

**Comment by clenimar** [comment]
#3324 fixed it. closing.
