### ISSUE TITLE
Kops should assume subnets are shared if they are not tagged as owned

### ISSUE THREAD

**Issue by StevenACoffman** [kubernetes/kops#3119]
In [this pull request](https://github.com/kubernetes/kops/pull/2960) kops assumes an untagged subnet is owned (created by kops), instead of assuming it is shared (pre-existing kops). Pre-existing subnets that are shared by kops are more likely to not have any kops tagging.

I think [this line](https://github.com/kubernetes/kops/blob/master/pkg/resources/aws.go#L2113) should be flipped to false.

**Comment by victortrac** [comment]
:+1:  This seems like a sensible default.
