### ISSUE TITLE
Fix broken link to vSphere dev docs in docs/README.md

### ISSUE THREAD

**Issue by watters** [kubernetes/kops#3122]
There are (at least) two ways to fix this. Both are trivial:

1. Move the vSphere files to the location currently in the link
1. Change the link to point to the current location of the files

The first seems best since the vSphere docs should probably be in `docs/development` instead of the root of `docs`.

(I'm happy to make either change and submit a PR, but submitted an issue first to comply with the contrib guidelines. Also, I'd expect such a change to be small/minor enough that it doesn't require a CLA. No reluctance to sign one; just high overhead for such a minor change.)

**Comment by chrislovecnm** [comment]
Closing since it is fixed
