### ISSUE TITLE
Need to use shared security groups

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3124]
Currently, Egress is completely open.  In order to pass an audit, we require fine grain control on egress.  I am proposing that we add the capability to reuse existing security groups.

**Comment by gambol99** [comment]
We were looking to raise a PR against this as well ... Namely a toggled flag in the cluster spec or potential a "shared" flag the security group (though i'm not sure if the latter would be cloud agnostic) which meant security groups rules could be completely self-managed.

**Comment by chrislovecnm** [comment]
@gambol99 I will have a PR ready tomorrow or Monday

**Comment by dcowden** [comment]
@chrislovecnm absolutely correct to relate these. Though we need to manage all of our SGs, the most egregious problem that our security team immediately noticed was the open egress rules.

It's awesome that you have a PR-- we'll be an early adopter.

**Comment by gambol99** [comment]
hi @chrislovecnm .. were you able to raise a PR on this one? .. I was hoping to take a gander :-)

**Comment by chrislovecnm** [comment]
I am super busy, and I am not certain the implementation that I have is going to fly :)  Let me find the shas for you.

**Comment by chrislovecnm** [comment]
https://github.com/k8s-for-greeks/kops/commit/814796a37f0ed339308e58b81bae249ed594a47a is the implementation on my integration branch.  We re-use a pre created security groups since those security groups are controlled by another system.  Current use-case a client has.

**Comment by chrislovecnm** [comment]
@gambol99 I am starting on this

/assign

**Comment by rifelpet** [comment]
This has been implemented in #5744 and will be released in Kops 1.11.
/close
