### ISSUE TITLE
Specify Security Groups while NOT generating the built-in ones.

### ISSUE THREAD

**Issue by dcowden** [kubernetes/kops#3126]
We are using kops to build our clusters, and it supports all of our customization needs save for one, related to security groups.

We need the ability to use our own SecurityGroups, while NOT generating the built-in ones. 

We cannot use automatically created SG's, because we use a tool called dome9, which manages all AWS security groups for security reasons.  It is like 'puppet for AWS SGs'.   If an SG is created that is not managed by dome9 it is automatically removed. Our security team requires that they are involved when new SGs are created, and they need to have a bunch of tags and naming conventions.

Today, we use the --cloudformation option, use additionalSecurityGroups to add ours (which include all of the necessary permissions), and then we manually remove the automatically generated ones.

There are several ways to implement this:

    1. A new flag,  ( for example, suppressGeneratedSecurityGroups), that operates independently from additionalSecurityGroups, and simply suppresses creating the ones it creates now
    2. a new setting  that is mutually exclusive with additionalSecurityGroups, (for example, nodeSecurityGroups and masterSecurityGroups ), which is a complete list of the sg's we want

I searched through the existing issues and PRs, and I did not see anything that meets this need. If I missed one, please let me know.

If this is of interest to someone else, and would be accepted as a PR, we would be willing to make the change and contribute.

**Comment by chrislovecnm** [comment]
Related https://github.com/kubernetes/kops/issues/3124

I already have some working code that needs a couple of tweaks, will have that in shortly as a PR.

**Comment by dcowden** [comment]
I reviewed #3124, i agree that it will end up meeting this need. We'll test once its available

**Comment by chrislovecnm** [comment]
/assign 

Will close when sec group work is done

**Comment by rifelpet** [comment]
This functionality has been merged in #5744 and will be a part of the 1.11.0 release.

[Relevant docs](https://github.com/rdrgmnzs/kops/blob/master/docs/security_groups.md)

/close
