### ISSUE TITLE
Rolling Upgrade does not work correction when cluster was created from cloudformation

### ISSUE THREAD

**Issue by dcowden** [kubernetes/kops#3129]
We are using kops with the --target=cloudformation target, so that we can customize the installation.  We create the cluster, and then apply it using aws cloudformation, and all goes well.

When we are ready to update, we do kops edit cluster, then kops update cluster --target=cloudformation, which produces a new cloudformation template, and instructs us to use rolling update. So far so good.

But then, we have problems when we perform rolling update.  

Here is a sample output of the last step:

`$ kops rolling-update cluster
Using cluster from kubectl context: elasticsearch-1.dev.colinx.com
W0803 12:05:06.937147    7287 instancegroups.go:86] Found ASG with no corresponding instance group "elasticsearch-1-AWSAutoScalingAutoScalingGroupmasteruseast1cmasterselasticsearch1devcolinxcom-M0SICVCF8PSQ"
W0803 12:05:06.937174    7287 instancegroups.go:86] Found ASG with no corresponding instance group "elasticsearch-1-AWSAutoScalingAutoScalingGroupmasteruseast1dmasterselasticsearch1devcolinxcom-1F90D5W5L5KC9"
W0803 12:05:06.937187    7287 instancegroups.go:86] Found ASG with no corresponding instance group "elasticsearch-1-AWSAutoScalingAutoScalingGroupmasteruseast1emasterselasticsearch1devcolinxcom-YBQIG78ZL5G6"
W0803 12:05:06.937197    7287 instancegroups.go:86] Found ASG with no corresponding instance group "elasticsearch-1-AWSAutoScalingAutoScalingGroupnodeselasticsearch1devcolinxcom-19DWC3YNKRIWO"
NAME			STATUS	NEEDUPDATE	READY	MIN	MAX	NODES
master-us-east-1c	Ready	0		1	1	1	0
master-us-east-1d	Ready	0		1	1	1	0
master-us-east-1e	Ready	0		1	1	1	0
nodes			Ready	0		4	4	4	3`

Note the errors in which rolling-upgrade  sees the AGS created from the CF template, but does not recognize them.  These messages are consistent with the problems we see when we proceed with the rolling upgrade, which are:

1. Rolling update launches new ASGS, just as it says it would
2. The masters in the new ASGs do not come up properly
3. The nodes do come up, but the old nodes are left running, and are not drained. The workloads are not moved to the new nodes.

We considered applying the cloudformation template generated by the cluster update command manually-- perhaps this is the correct workflow? But then of course AWS will not drain nodes or any fanciness like that.

We suspect that the problem comes from AWS cloudformation constraints on names for the ASGs. kops creates an ASG named 'nodes.<clustername>.<domainname>, but in CF this is not a legal identifer, so a different one is used. The rolling upgrade script doesnt appear to be able to find the alternate names. 

We are quite inexperienced with kops, so we feel like we must be missing something. Are we doing the correct workflow? Any help is appreciated.

**Comment by FuriKuri** [comment]
We have the same problem.

**Comment by gwkunze** [comment]
I ran into the same problem and fixed this in #4669 it should be in the 1.9 release of Kops. However as I was typing this reply I realized a potential serious problem with my fix and opened #4906
