### ISSUE TITLE
hostPort not working with CNI Plugins

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kops#3132]
Kops version: 1.7.0
Kubernetes version: 1.7.2

Related to:

https://github.com/kubernetes/kubernetes/issues/23920
https://github.com/projectcalico/k8s-policy/issues/109
https://github.com/coreos/flannel/issues/772

probably we just need to update the default calico/flannel images?

**Comment by Arttii** [comment]
It is also required to install the correct cni plugins. Kops currently only copies like 3 out of the 5 available, then updating the versions would work [related](https://github.com/kubernetes/kops/issues/2922)
