### ISSUE TITLE
Kops/Kubernetes 1.7.0 HPA not working properly 

### ISSUE THREAD

**Issue by gabrieladt** [kubernetes/kops#3135]
Hi Guy.

I was using kops 1.7 with stable channel (k8s 1.7.0).

We have a bug on HPA k8s, making the pods being killed.

Was fixed on version 1.7.2 (hpa: Prevent scaling below MinReplicas if desiredReplicas is zero (#48997, @johanneswuerbach)

Now, I updated to 1.7.3, seems working perfect. (at least the hpa)

Thanks

**Comment by chrislovecnm** [comment]
can we close this?
