### ISSUE TITLE
ContainerLinux needs a way to modify the update engine settings

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#3141]
By default it seems CoreOS (OS image) support has settings that result in nodes rebooting soon after they come up if the image is out-of-date.  While this is one of the main reasons to use ContainerLinux, it needs to be configurable, so that reboots can be controlled, especially for masters.

It might make the most sense to just change the default to never reboot and provide a way to override that (even just a hook example for now would be fine)

**Comment by gambol99** [comment]
hi @blakebarnett  .. take a look at https://github.com/kubernetes/kops/pull/3063

**Comment by blakebarnett** [comment]
I do still think we should change the defaults for masters though, I can see it causing issues during rolling-updates with etcd consensus, etc.

**Comment by gambol99** [comment]
We actually disable updates while running in an ASG. Given the AMI is fix the very moment you make a change your gonna revert all the updates anyhow.

**Comment by blakebarnett** [comment]
I haven't had time to verify this, but I assume it's working.
