### ISSUE TITLE
experimentalEncryptionProviderConfig

### ISSUE THREAD

**Issue by DerrickMartinez** [kubernetes/kops#3143]
Trying to get this working so I can have encrypted at rest secrets.

Tried adding: (via cluster edit)

spec:
   kubeAPIServer:
     experimentalEncryptionProviderConfig: /root/mykey.yaml

It returns with Found fields that are not recognized. Am I doing something wrong?

Found fields that are not recognized

 kubeAPIServer:
 experimentalEncryptionProviderConfig: /root/mykey.yaml
  kubeAPIServer: {}

** Update, looks like it is not part of the kops API config. Any plans to add it in? I guess with EBS encryption might not really be a big deal or any kind of hurry to add it in.

**Comment by zioalex** [comment]
I am looking for the same type of configuration to enable the "[Encrypting data at rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/)".

Any update here?

**Comment by schmitzcc** [comment]
+1

**Comment by chrislovecnm** [comment]
The PR for this support I think is the latest alpha release

**Comment by ameena007** [comment]
Hi,

I need to enable this in order to make my Cluster CIS Compliant.

Can we repoen this issue.

Regards
Amit Meena
