### ISSUE TITLE
Support Aggregation Layer

### ISSUE THREAD

**Issue by david92rl** [kubernetes/kops#3152]
In order to take advantage of the new [Horizontal Pod Autoscaling based on Custom Metrics](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics) we have to cover some [requisites](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-custom-metrics).

The main one is [Configure Aggregation Layer](https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/#enable-apiserver-flags). Basically set some flags on the API Server:
```
--requestheader-client-ca-file=<path to aggregator CA cert>
--requestheader-allowed-names=aggregator
--requestheader-extra-headers-prefix=X-Remote-Extra-
--requestheader-group-headers=X-Remote-Group
--requestheader-username-headers=X-Remote-User
--proxy-client-cert-file=<path to aggregator proxy cert>
--proxy-client-key-file=<path to aggregator proxy key>
```

I'm not sure if those flags must be in the [KubeAPIServerConfig](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L165) section or Kops has to take care of it without user interaction via cluster.spec

My question is: Is there any way to make it work with the current release ([1.7.0](https://github.com/kubernetes/kops/releases/tag/1.7.0))?

**Comment by kumudt** [comment]
Facing the same issue. I couldn't find these flags in the Kops documentation.

**Comment by kumudt** [comment]
`--horizontal-pod-autoscaler-use-rest-clients` has to be added on `kube-controller-manager`
and
`--requestheader-client-ca-file` on `kube-apiserver`
has to be supported as well.

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/pull/3165 will support some of this

**Comment by aponomarenko** [comment]
Hi,

Is it possible to pass the option `--requestheader-client-ca-file` (or any other custom option) to the `apiserver` currently by editing the cluster config file?

Thank you.

**Comment by bensussman** [comment]
Actually, I think https://github.com/kubernetes/kops/pull/6201 might be the fix for my issue, but there seems to be some controversy about whether or not it works with kops v1.11 (which is what i have installed, the current version available from brew). I will follow along over there cc @itskingori
