### ISSUE TITLE
Cannot create cluster in AWS

### ISSUE THREAD

**Issue by shavo007** [kubernetes/kops#3157]
Kops 1.7.0

```
kops create cluster --v=0 \
  --cloud=aws \
  --node-count 1 \
  --master-size=t2.medium \
  --master-zones=ap-southeast-2a \
  --zones ap-southeast-2a,ap-southeast-2c \
  --name= ${NAME} \
  --node-size=m4.large \
   --node-volume-size=50 \
  --ssh-public-key=~/stacks/${NAME}/credentials/id_rsa.pub \
  --dns-zone ${NAME} \
 --target=terraform \
  2> 1 | tee ~/stacks/${NAME}/create_cluster.txt

```

My first attempt was to use terraform to generate the cluster within existing VPC. But it did not create the A records in the hosted zone. When I ran kops update cluster it just created placeholder values.

I then tried to create the cluster using kops without existing VPC. 
`kops update cluster ${NAME} --yes`

I seen that the A records were created. But I still cannot validate the cluster. 

I get timeout every time when validating the cluster.
`kops validate cluster ${NAME}`

cannot get nodes for "${NAME}": Get https://${NAME}/api/v1/nodes: dial tcp: lookup ${NAME} on 127.0.1.1:53: server misbehaving

Im at a loss how to create a cluster!! 

I was able to create a cluster in the older version 1.6. Not sure what has changed.

**Comment by shavo007** [comment]
Update: Got it working with 2 worker nodes on kops 1.6.

Will try again tomorrow on 1.7 with 2 worker nodes and existing VPC

**Comment by shavo007** [comment]
i know kops creates the DNS A records. Does terraform?
`Pre-creating DNS records`

**Comment by chrislovecnm** [comment]
dnscontroller a pod in k8s and kops both update DNS A records.  We do not have calls the TF to update DNS.

**Comment by shavo007** [comment]
I think i will close this issue as I need more investigation.

I do have a question tho @chrisglass .

When you specify target of terraform and use terraform to create cluster instead of kops, will dnscontroller update DNS A records?

**Comment by chrisglass** [comment]
(I suppose that ping was for @chrislovecnm :) Hi guys!)

**Comment by shavo007** [comment]
Apologies!

**Comment by chrisglass** [comment]
None needed :)

**Comment by chrislovecnm** [comment]
Yes dns controller will create the records
