### ISSUE TITLE
Docker configuration example does not work - '-f' flag not supported 

### ISSUE THREAD

**Issue by axbaretto** [kubernetes/kops#3163]
At https://github.com/kubernetes/kops/blob/master/docs/security.md, line 28, the example references a '-f' flag as follows:

`kops create secret --name <clustername> dockerconfig -f ~/.docker/config.json`

kops Version 1.7.0 (git-e04c29d) does not support this flag. This was a PR that was approved recently ([Add `kops create secret dockerconfig` feature #3087](https://github.com/kubernetes/kops/pull/3087)). 

Please document the version/patch for which this flag will be supported.

**Comment by chrislovecnm** [comment]
@axbaretto we have an issue in to version our documentation.  Unfortunately, currently, we have features that are only in master in our documentation.

Out next release will have this feature.
