### ISSUE TITLE
protokube is failing to mount /dev/sda1 instance root volume

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3167]
## Update

This seems to be created when you add the custom tags to the root EBS volume.  It seems that something other than kops, most likely a lambda function, is adding the instance kops tags to the ebs volume.

## Information

This is running protokube from master, with RHEL instances.

In the protokube mount code, we are having protokube code return back `/dev/sda1`, which is the root volume.  The `/dev/sda1` volume is part of the launch configuration and is only on the master, which is odd.  The nodes have a typical root volume that is prefixed with 'x'.  The `/dev/sda1` device does not exist on the ec2 instance, any because of that protokube is stuck in an endless loop, where is does not mount the etcd volumes.

We seem to have tags

## Open questions

1. Should we be attempting to mount non-etcd volumes? I believe no.
2. Why are we having this problem in one account, but not another? This was caused by the tags being added external to kops.
3. The root ebs volumes have tags on them on the broken cluster, but are not tagged in the cluster that is operational.  I am uncertain why and how those volumes are getting tagged. This was caused by the tags being added external to kops.
4. do we need to return the root volume?
5. Is the problem that we have `/dev/sda1` on a master instance while having a proper `x` based device name on the node. This seems to be caused by RHEL master.

## Approaches

We are currently white listing everything.  If a volume has the tags and exists, we are returning the volume in aws_volume.go.  I recommend that only if we have an etcd volume name do we return the volume.  I am uncertain why we are returning the root volume.

**Comment by chrislovecnm** [comment]
I will have a PR inbound that updates protokube to ignore root volumes, and volumes without the etcd tags.

**Comment by justinsb** [comment]
Can we not simply not tag the master volumes?  I'm not sure the behaviour we have today is incorrect enough to fix..

**Comment by chrislovecnm** [comment]
No we cannot. It is common practice to let the tags on the ec2 instance be added to the volume for both tracking and billing purposes. Our code tries to mount the root volume, my PR addresses that. That is not the purpose of the code, the purpose is to mount the etcd drives.
