### ISSUE TITLE
Node hostnames

### ISSUE THREAD

**Issue by astanciu** [kubernetes/kops#3171]
Is there a way to either
- set the node hostname patter before cluster create (like 'node-_x_`)
or
- rename a host? it would be helpful to have friendlier names than what aws autogenerates...(esp to distinguish the masters from nodes)

**Comment by mikesplain** [comment]
@astanciu I believe you can by creating different instance groups. I've created a few recently (e.g. `monitoring` becomes nodes called `monitoring.example.com`).  Not sure about changing masters but you could likely do the same to replace `nodes` with something more useful.  Not answering all your question but some food for thought.

**Comment by bechtoldt** [comment]
I'm interested too but haven't found any docs. Is this really possible yet?
