### ISSUE TITLE
Calico Pod CIDR Migration Procedure script fails on macOS

### ISSUE THREAD

**Issue by kaazoo** [kubernetes/kops#3181]
The Calico Pod CIDR Migration Procedure script from https://github.com/kubernetes/kops/blob/master/docs//upgrade_from_kops_1.6_to_1.7_calico_cidr_migration.md fails because of differences between BSD sed and GNU sed command:

```
./create_migration_manifest.sh
ipip mode is set to 'Always'. Honouring in migration manifest.
sed: 1: "jobs.yaml": invalid command code j
```
POD_CIDR and NON_MASQUERADE_CIDR won't be replaced.

As a workaround, you can install 'gnu-sed' from homebrew and add the following line to the script:
```
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
```

This  way it works properly:
```
$ ./create_migration_manifest.sh 
ipip mode is set to 'Always'. Honouring in migration manifest.
jobs.yaml created. Please run: 
kubectl apply -f jobs.yaml
```

**Comment by jurgenweber** [comment]
for those that do not use brew but macports:

```port install gsed```

and then in create_migration_manifest.sh replace sed with gsed.

**Comment by chrislovecnm** [comment]
cc: @ottoyiu - can we get checks in the script for the binaries required?  Or if someone would like to PR a fix.  We just need to check that all binaries used exist on the system.

**Comment by ottoyiu** [comment]
I don't have a mac handy right now, but I'll take a look whenever I have the chance to get my hands on one.
