### ISSUE TITLE
Flannel overlay using not recommend UDP backend

### ISSUE THREAD

**Issue by mikelorant** [kubernetes/kops#3185]
The current config for flannel is listed as using the UDP backend.

```
  net-conf.json: |
    {
      "Network": "100.64.0.0/10",
      "Backend": {
        "Type": "udp"
      }
```

According to the Flannel documentation, this should only be used for debugging.

https://github.com/coreos/flannel/blob/master/Documentation/backends.md#udp

> Use UDP only for debugging if your network and kernel prevent you from using VXLAN or host-gw.

This should be changed to either vxlan or  host-gw.

**Comment by matthope** [comment]
For AWS environments, the Flannel AWS VPC backend may be the preferred option -
 https://github.com/coreos/flannel/blob/master/Documentation/aws-vpc-backend.md

**Comment by mikelorant** [comment]
Performance benchmark details:
http://machinezone.github.io/research/networking-solutions-for-kubernetes/

Their recommendation is host-gw.

AWS VPC backend has a limit of 50 nodes, so that is not a good option.

**Comment by smerrill** [comment]
The default kubenet networking functions identically to the `aws-vpc` backend for Flannel. If you're thinking of using that, you might as well use kubenet. `host-gw` is also likely not a good default choice since it will only work inside a single subnet, which I think won't work for private topology.

**Comment by arielkung** [comment]
Backend should be VXLAN. Is the recommended backend in the docs, it supports multiple subnets for private topology and has better performance than UDP.

**Comment by justinsb** [comment]
Related #3910.

**Comment by chrislovecnm** [comment]
Closing as fixed
