### ISSUE TITLE
kube-proxy being evicted due to inode resource

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#3194]
We need to protect kube-proxy from eviction; during low inode situations it often is evicted.

**Comment by andreychernih** [comment]
Just experienced the same problem and created https://github.com/kubernetes/kubernetes/issues/51432. I am not sure how it is possible for kubelet to evict a critical pod.

**Comment by andreychernih** [comment]
According to https://v1-6.docs.kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/ critical pod also requires `[{"key":"CriticalAddonsOnly", "operator":"Exists"}]` toleration. It looks like kops does not set this toleration for `kube-proxy`:

https://github.com/kubernetes/kops/blob/1eb9949051612e60874a815ca203f85ac8d512b7/nodeup/pkg/model/kubeproxy.go#L177

**Comment by andreychernih** [comment]
I think this is only relevant when rescheduler is deployed. I don't have it.

**Comment by dashpole** [comment]
Is the critical pod feature gate enabled for your setup?  The kubelet should not evict pods that are static and critical when this feature gate is enabled on the kubelet.

**Comment by andreychernih** [comment]
I just realized that it's not and that kops does not enable this feature gate by default. Thanks for the hint. I was pretty sure that it should have been enabled by default because so many components in kops have this critical pod annotation.
