### ISSUE TITLE
aufs support with kops 1.6/1.7

### ISSUE THREAD

**Issue by markine** [kubernetes/kops#3196]
Hello,

It looks like the node AMIs kops uses out of the box point to images released by https://github.com/kopeio/kubernetes-kernel . These images do not support aufs and kops configures Docker with the storage driver overlay. I see that kops chose overlay over aufs in Oct 2016 (https://github.com/kubernetes/kops/commit/07edc17fb67d364e8759fe736ba9b8b82a5e44fb).
 What is the rationale for excluding aufs support?

The following comes from a node brought up with kops 1.6:

```
root@ip-172-20-76-65:/home/admin# grep overlay /proc/filesystems
nodev	overlay
root@ip-172-20-76-65:/home/admin# grep aufs /proc/filesystems
root@ip-172-20-76-65:/home/admin# uname -a
Linux ip-172-20-76-65 4.4.65-k8s #1 SMP Tue May 2 15:48:24 UTC 2017 x86_64 GNU/Linux
root@ip-172-20-76-65:/home/admin# 
```

Thanks

Mikhail

**Comment by markine** [comment]
FYI the reason for inquiring about aufs is this: https://github.com/kubernetes/kops/issues/3197

**Comment by Cryptophobia** [comment]
yes, but we are hitting obscure bugs now with overlayfs and older kernels  `=< 4.13`

https://github.com/moby/moby/issues/19647
