### ISSUE TITLE
Can't install kops via source

### ISSUE THREAD

**Issue by liangrog** [kubernetes/kops#3199]
Hi there, 
I was simply trying to follow the installation instruction, immediately hit a road block:

    [vagrant@localhost kops]$ pwd
    /home/vagrant/go/src/k8s.io/kops
    [vagrant@localhost kops]$ git checkout release
    error: Updating the following directories would lose untracked files in it:
	    _vendor/github.com/grpc-ecosystem

    Aborting

System: centos 7 on vagrant. 

Cheers
Roger

**Comment by gambol99** [comment]
From what i can see 'release' branch is two months old, you probably want to checkout the tag $ git checkout 1.7.0

**Comment by mikesplain** [comment]
@liangrog looks like your system just has some vendored dependencies that aren't checked it. Clean your branch and recheckout should fix it:

```
# warning this will remove any files or modifications in the current directory and all sub directories
git reset --hard
git clean -fd
git checkout 1.7.0
```

**Comment by chrislovecnm** [comment]
@liangrog can we close this?  @mikesplain / @gambol99 should we document this?

**Comment by liangrog** [comment]
Happy to close it. Just hope the documentation can keep up with the development as it's always a pain that following the documentation doesn't work. Thanks.
