### ISSUE TITLE
IAM role statement for nodes is missing: arn:aws:s3:::bucket/dev.bucket/pki/private/ca/*

### ISSUE THREAD

**Issue by nafiux** [kubernetes/kops#3200]
**Environment**
Cloud provider: AWS
kops version: Version 1.7.0 (git-79428697)

**Problem**
After created and updated the cluster, when I was trying to check the status with: `kops validate cluster`, I got:

Validation Failed
Ready Master(s) 1 out of 1.
Ready Node(s) 0 out of 2.

I entered to the node vm and saw the log `/var/log/syslog` (I replaced the real bucket name by bucket):

Reading file “s3://bucket/dev.bucket/pki/private/ca/6454376489671718657769748126.key”
Aug 15 06:23:16 ip-172-20-52-23 nodeup[726]: W0815 06:23:16.343165     726 main.go:141] got error running nodeup (will retry in 30s): error building loader: error fetching CA certificate from keystore: error loading private key “s3://bucket/dev.bucket/pki/private/ca/6454376489671718657769748126.key”: error fetching s3://bucket/dev.bucket/pki/private/ca/6454376489671718657769748126.key: AccessDenied: Access Denied
Aug 15 06:23:16 ip-172-20-52-23 nodeup[726]: status code: 403, request id: 49C6B8076BBC5CA7

I saw the role created by kops, and the lines related to S3 are:

      “Resource”: [
        “arn:aws:s3:::bucket/dev.bucket/addons/*“,
        “arn:aws:s3:::bucket/dev.bucket/instancegroup/*“,
        “arn:aws:s3:::bucket/dev.bucket/pki/issued/*“,
        “arn:aws:s3:::bucket/dev.bucket/pki/ssh/*“,
        “arn:aws:s3:::bucket/dev.bucket/pki/private/kube-proxy/*“,
        “arn:aws:s3:::bucket/dev.bucket/pki/private/kubelet/*“,
        “arn:aws:s3:::bucket/dev.bucket/secrets/*“,
        “arn:aws:s3:::bucket/dev.bucket/cluster.spec”,
        “arn:aws:s3:::bucket/dev.bucket/config”
      ]

It seems that is missing the one specific for `arn:aws:s3:::bucket/dev.bucket/pki/private/ca/*`

I verified this trying to copy the file with aws-cli:

admin@ip-172-20-52-23:~$ aws s3 cp s3://bucket/dev.bucket/pki/private/ca/6454376489671718657769748126.key .
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

Do you know if is this a bug?

**Comment by gambol99** [comment]
@justinsb ... This is probably due to fact your running a kops binary off built off master branch but using the nodeup assets from a tagged v1.7.0 release which don't have updates from (https://github.com/kubernetes/kops/commit/fd0ce236dc15a16625c56bfb007ea6e13e5fb925)

**Comment by nafiux** [comment]
Hi @gambol99 yes, at the beginning I installed the last version of kops that is v1.7.0, and I wasn't able to run the cluster by following the getting started instructions.

What should I do?

Thanks.

**Comment by nafiux** [comment]
@ Gambol99 @justinsb @StevenACoffman, it seems that `brew install kops` is not downloading the right version, I had to download the binary version from the repository by @shadoi suggestion in #kops slack channel.
