### ISSUE TITLE
Kubelet Unable To Apply Reserved Cgroup Limits because Cgroup does not exist

### ISSUE THREAD

**Issue by ivelichkovich** [kubernetes/kops#3223]
I have been trying to reserve compute resources following https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

However, when I deploy an instance group with kops that instance group comes up as NotReady and has the following errors:

  4m		4m		1	kubelet, ip-172-20-180-67.ec2.internal			Normal		Starting				Starting kubelet.
  4m		4m		1	kubelet, ip-172-20-180-67.ec2.internal			Warning		FailedNodeAllocatableEnforcement	Failed to enforce System Reserved Cgroup Limits on "system.slice": "system.slice" cgroup does not exist
  4m		4m		1	kubelet, ip-172-20-180-67.ec2.internal			Warning		KubeletSetupFailed			Failed to start ContainerManager Failed to enforce System Reserved Cgroup Limits on "system.slice": "system.slice" cgroup does not exist
  4m		4m		1	kubelet, ip-172-20-180-67.ec2.internal			Normal		NodeAllocatableEnforced			Updated Node Allocatable limit across pods
  4m		1m		18	kubelet, ip-172-20-180-67.ec2.internal			Normal		NodeHasSufficientDisk			Node ip-172-20-180-67.ec2.internal status is now: NodeHasSufficientDisk
  4m		1m		18	kubelet, ip-172-20-180-67.ec2.internal			Normal		NodeHasSufficientMemory			Node ip-172-20-180-67.ec2.internal status is now: NodeHasSufficientMemory
  4m		1m		18	kubelet, ip-172-20-180-67.ec2.internal			Normal		NodeHasNoDiskPressure			Node ip-172-20-180-67.ec2.internal status is now: NodeHasNoDiskPressure

I can't seem to figure out how to point to the right cgroups.

Here is my instance group spec:

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: xxxxxxxxx
  name: nodes
spec:
  kubelet:
    kubeReserved:
        cpu: "200m"
        memory: "200Mi"
        storage: "2Gi"
    kubeReservedCgroup: "/kube.slice"
    systemReserved:
        cpu: "200m"
        memory: "200Mi"
        storage: "2Gi"
    systemReservedCgroup: "/system.slice"
    enforceNodeAllocatable: "pods,system-reserved,kube-reserved"
  image: coreos.com/CoreOS-stable-1409.9.0-hvm
  machineType: m3.large
  maxSize: 3
  minSize: 3
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1e
  - us-east-1d
  - us-east-1f

I've tried many different values and different operating systems. I feel like I'm missing something.

**Comment by ivelichkovich** [comment]
Sorry about the terrible formatting of my values. 

If anyone else runs into this removing: 
enforceNodeAllocatable: "pods,system-reserved,kube-reserved" 
fixed it. Correct me if I'm wrong but I believe as of 1.6 this is automatically set.

**Comment by chrislovecnm** [comment]
Do we need to change the default for 1.6.x+ k8s?

**Comment by jjo** [comment]
@ivelichkovich regarding your comment:
> If anyone else runs into this removing:
> enforceNodeAllocatable: "pods,system-reserved,kube-reserved"
> fixed it. 

confirming it fixes it, as kubelet defaults to "pods" as above value,
see also https://docs.openshift.com/container-platform/3.3/admin_guide/allocating_node_resources.html

**Comment by itskingori** [comment]
@chrislovecnm sorry, been travelling/busy quite a bit 🙈 ... catching up with all the mentions. That said, the docs do make mention of this behaviour ...

> Note that Kubelet does not create `--kube-reserved-cgroup` if it doesn’t exist. Kubelet will fail if an invalid cgroup is specified.
> ...
> Note that Kubelet does not create `--system-reserved-cgroup` if it doesn’t exist. Kubelet will fail if an invalid cgroup is specified.

See https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

@ivelichkovich was `enforceNodeAllocatable: "pods,system-reserved,kube-reserved"` applied by default or you added it in the yaml? 🤔 ...

@chrislovecnm  I was under the impression that the PR that added this feature does not enforce any defaults but purely allows one to set them if they need them (since we have the `omitempty` on `EnforceNodeAllocatable`). I could be wrong.

Let's discuss willing to make any clarification, amendments or remove it altogether.

**Comment by itskingori** [comment]
Haven't had time to look at this but hopefully soon.

/remove-lifecycle stale

**Comment by bhack** [comment]
Gently ping

**Comment by BartoszZawadzki** [comment]
We are having the exact same issue. Has anyone been able to solve this?
(KOPS Version 1.11.1;   kubernetesVersion: 1.10.13)

**Comment by integrii** [comment]
I had this issue simply because I copied the example from [the kops docs](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#compute-resources-reservation)

**Comment by BartoszZawadzki** [comment]
We've tried to enable 'system-reserved' by specyfing limits and tried to use various values for: **'systemReservedCgroup:'**; like
```
     /system.slice
     /sys/fs/cgroup/systemd
     /sys/fs/cgroup/systemd/system.slice
```

Everytime kubelet crashed with information that cgroup did not exist.

I've listed all cgroups with `systemd-cgls` and `system.slice` is present.

So now I'm wondering if I cannot use already existing Cgroup for reservations...

 Cgroup driver is set to `cgroupsfs` for both kops and docker. 

We are using CoreOS.

**Comment by TomHutter** [comment]
On my system (Centos 7) I figured out, that cgroup `system.slice` does not have as many subsystems as cgroup `kubepods` and came to the conclusion, that kubelet is maybe searching for subsystems in system.slice, which are not present:

### system.slice:
`ls -d /sys/fs/cgroup/*/system.slice/`
```
/sys/fs/cgroup/blkio/system.slice/
/sys/fs/cgroup/cpuacct/system.slice/
/sys/fs/cgroup/cpu,cpuacct/system.slice/
/sys/fs/cgroup/cpu/system.slice/
/sys/fs/cgroup/devices/system.slice/
/sys/fs/cgroup/memory/system.slice/
/sys/fs/cgroup/pids/system.slice/
/sys/fs/cgroup/systemd/system.slice/
```
### kubepods:
`ls -d /sys/fs/cgroup/*/kubepods/`
```
/sys/fs/cgroup/blkio/kubepods/
/sys/fs/cgroup/cpuacct/kubepods/
/sys/fs/cgroup/cpu,cpuacct/kubepods/
/sys/fs/cgroup/cpu/kubepods/
/sys/fs/cgroup/cpuset/kubepods/
/sys/fs/cgroup/devices/kubepods/
/sys/fs/cgroup/freezer/kubepods/
/sys/fs/cgroup/hugetlb/kubepods/
/sys/fs/cgroup/memory/kubepods/
/sys/fs/cgroup/net_cls/kubepods/
/sys/fs/cgroup/net_cls,net_prio/kubepods/
/sys/fs/cgroup/net_prio/kubepods/
/sys/fs/cgroup/perf_event/kubepods/
/sys/fs/cgroup/pids/kubepods/
/sys/fs/cgroup/systemd/kubepods/
```
I added the missing subsystems with cgconfig (`/etc/cgconfig.d/kubelet.conf`):
You need to have `libcgroup-tools`installed.

```
group system.slice {
  net_cls {
  }
  net_prio {
  }
  hugetlb {
  }
  perf_event {
  }
  freezer {
  }
  cpuset {
  }
}
```
`service cgconfig restart`

=> `ls -d /sys/fs/cgroup/*/system.slice/`

```
/sys/fs/cgroup/blkio/system.slice/
/sys/fs/cgroup/cpuacct/system.slice/
/sys/fs/cgroup/cpu,cpuacct/system.slice/
/sys/fs/cgroup/cpuset/system.slice/
/sys/fs/cgroup/cpu/system.slice/
/sys/fs/cgroup/devices/system.slice/
/sys/fs/cgroup/freezer/system.slice/
/sys/fs/cgroup/hugetlb/system.slice/
/sys/fs/cgroup/memory/system.slice/
/sys/fs/cgroup/net_cls,net_prio/system.slice/
/sys/fs/cgroup/net_cls/system.slice/
/sys/fs/cgroup/net_prio/system.slice/
/sys/fs/cgroup/perf_event/system.slice/
/sys/fs/cgroup/systemd/system.slice/
```

After that, I could start kubelet with the following parameters in `/var/lib/kubelet/kubeadm-flags.env`:

```
KUBELET_KUBEADM_ARGS=-... --runtime-cgroups=/kube.slice --cgroup-driver=cgroupfs --kube-reserved=cpu=500m,memory=500Mi,ephemeral-storage=1Gi --system-reserved=cpu=1,memory=1500Mi,ephemeral-storage=5Gi --enforce-node-allocatable=pods,kube-reserved,system-reserved --kube-reserved-cgroup=/kube.slice --kubelet-cgroups=/kube.slice --system-reserved-cgroup=/system.slice --eviction-hard=memory.available<5%
```

**Comment by GMartinez-Sisti** [comment]
I'm having the a similar issue with the `kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13` AMI, but I'm not specifying any cgroups:

I believe this is causing this error:

```
Error: failed to start container "wait-for-kafka-connect": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: 
container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 8388608 to memory.limit_in_bytes:
write /sys/fs/cgroup/memory/kubepods/pod7988a7f9-8cb4-11e9-8a1a-066c3249e6b0/wait-for-kafka-connect/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
```

**Comment by TomHutter** [comment]
@GMartinez-Sisti This maybe is a problem with setting memory.limit_in_bytes smaller than already set - which isn't possible. Check your cgroup memory `cat /sys/fs/cgroup/memory/<your.cgroup>/memory.limit_in_bytes`, if limits already are bigger than you want to set them.

**Comment by GMartinez-Sisti** [comment]
Thanks @TomHutter.

I found something online that hinted that too and increasing the limit fixed the issue. This is just an init container that tries to ping something so the limit was really low at 8mb. Had to increase to 16mb which seems a lot for a ping in a bash script.

**Comment by kh34** [comment]
`cgconfig` doesn't appear to be available on CoreOS. Anyone able to find a workaround?

**Comment by alex88** [comment]
In my case I had this problem after upgrading from 1.11.9 to 1.13.10 and I with the kubeleted reserved resources kubelet had this error:


```
kubelet_node_status.go:338] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=eu-west-1a
kubelet_node_status.go:342] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=eu-west-1
setters.go:144] replacing cloudprovider-reported hostname of ip-10-0-1-80.eu-west-1.compute.internal with overridden hostname of ip-10-0-1-80.eu-west-1.compute.internal
kubelet_node_status.go:447] Recording NodeHasSufficientMemory event message for node ip-10-0-1-80.eu-west-1.compute.internal
kubelet_node_status.go:447] Recording NodeHasNoDiskPressure event message for node ip-10-0-1-80.eu-west-1.compute.internal
kubelet_node_status.go:447] Recording NodeHasSufficientPID event message for node ip-10-0-1-80.eu-west-1.compute.internal
cpu_manager.go:155] [cpumanager] starting with none policy
cpu_manager.go:156] [cpumanager] reconciling every 10s
policy_none.go:42] [cpumanager] none policy: Start
node_container_manager_linux.go:106] Enforcing System reserved on cgroup "" with limits: map[]
kubelet.go:1384] Failed to start ContainerManager Failed to enforce System Reserved Cgroup Limits on "": [] cgroup is not config properly
```

what I can tell is that the argument `--kubelet-cgroups=""` was empty so it was trying to set resources limits on an empty cgroup

**Comment by richerve** [comment]
I think what is needed is proper docs on how to setup this depending on the OS image used. For Debian for example is also different, or at least I couldn't manage to set more than system-reserved as trying to use kube-reserved didn't crash kops but didn't do what I was intending as the cgroup hierarchy is different there.

**Comment by michalschott** [comment]
by adding `--kubelet-cgroups=/kube-reserved --runtime-cgroups=/kube-reserved` I was finally able to enforce resource allocation for kubelet.
