### ISSUE TITLE
Download from unkown bucket during node provision.

### ISSUE THREAD

**Issue by dng-dev** [kubernetes/kops#3234]
I wanted to start a new node and started it the regular way. kops create instancegroup ........

The node wasnt able to join the cluster and i investigated a bit. In /var/log/systemlog i found the following lines. I don't know this bucket and tribblechecked my configs.

`
May 30 08:53:19 ip-172-31-54-67 nodeup[731]: I0530 08:53:19.364401     731 s3context.go:157] Found bucket "clusters.dev.lucken-test.com" in region "eu-central-1"
May 30 08:53:19 ip-172-31-54-67 nodeup[731]: I0530 08:53:19.364859     731 s3fs.go:173] Reading file "s3://clusters.dev.lucken-test.com/public.cluster.lucken-test.com/cluster.spec"
May 30 08:53:19 ip-172-31-54-67 nodeup[731]: I0530 08:53:19.396864     731 s3fs.go:173] Reading file "s3://clusters.dev.lucken-test.com/public.cluster.lucken-test.com/instancegroup/nodes"
May 30 08:53:19 ip-172-31-54-67 nodeup[731]: I0530 08:53:19.406721     731 context.go:126] Performing HTTP request: GET http://169.254.169.254/latest//meta-data/local-hostname
May 30 08:53:19 ip-172-31-54-67 nodeup[731]: I0530 08:53:19.407779     731 command.go:340] Using hostname from AWS metadata service: ip-172-31-54-67.eu-central-1.compute.internal
May 30 08:53:19 ip-172-31-54-67 nodeup[731]: I0530 08:53:19.408039     731 context.go:126] Performing HTTP request: GET http://169.254.169.254/latest//meta-data/local-hostname
May 30 08:53:19 ip-172-31-54-67 nodeup[731]: I0530 08:53:19.408908     731 command.go:340] Using hostname from AWS metadata service: ip-172-31-54-67.eu-central-1.compute.internal
`

**Comment by dng-dev** [comment]
i found this inside of an file in etc:
/etc/systemd/system/multi-user.target.wants/protokube.service

grep: ./etc/cron.d: Is a directory


[Unit]
Description=Kubernetes Protokube Service
Documentation=https://github.com/kubernetes/kops

[Service]
ExecStartPre=/bin/true
ExecStart=/usr/bin/docker run -v /:/rootfs/ -v /var/run/dbus:/var/run/dbus -v /run/systemd:/run/systemd --net=host --privileged --env KUBECONFIG=/rootfs/var/lib/kops/kubeconfig  protokube:1.6.0 /usr/bin/protokube --cloud=aws --containerized=true --dns-internal-suffix=.internal.public.cluster.lucken-test.com --dns=aws-route53 --master=false --v=4 --zone=*/Z1CG8H9GTHAHXK
Restart=always
RestartSec=2s
StartLimitInterval=0

[Install]
WantedBy=multi-user.target

**Comment by chrislovecnm** [comment]
In the cluster.spec file on s3 in your s3 bucket / state store what is the value for `configBase`?  `lucken-test.com` is not yours?

**Comment by dng-dev** [comment]
Hello @chrislovecnm the cluster.spec file contains my cluster state. I am totally unsure where this comes from. Now its working i am totally confused.

**Comment by chrislovecnm** [comment]
@dng-dev two things set this, working in combination.

1. users' KOPS_STATE_STORE env variable
2. `configBase`

Can we close this, and re-open if you are able to recreate?

**Comment by dng-dev** [comment]
Hey @chrislovecnm sure, i will add a comment once this happends. But anyway i did not knew this bucket or tld.

**Comment by dng-dev** [comment]
@chrislovecnm reopen because it hapends again. 
everytime i have this issue the node is also in version 1.6.3 instead of 1.7.0

**Comment by dng-dev** [comment]
i booted the ami without user data and without integration into kops.
less /var/lib/cloud/instances/i-06e4865985ddfa38d/user-data.txt there i found the prevorious boot

**Comment by chrislovecnm** [comment]
> less /var/lib/cloud/instances/i-06e4865985ddfa38d/user-data.txt there i found the prevorious boot

more context please
