### ISSUE TITLE
launching with weave with a m3.medium

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3249]
failed to place pod on "ip-172-20-0-56.ec2.internal": Node didn't have enough resource: cpu, requested: 200, used: 850, capacity: 1000

Not sure why but I am running out of resources with k8s 1.7.4 and kops master.

**Comment by thomaschaaf** [comment]
The m3.medium only has one cpu -> 1000m. Weave uses 200m and there are a bunch of other pods running on the masters. Simply changing the instance type to a larger size should fix the problem. e.g. c4.large or m3.large

**Comment by chrislovecnm** [comment]
@thomaschaaf yes, but this is new, and I think our default instance size is a m3.medium :)

**Comment by chrislovecnm** [comment]
/close

Fixed
