### ISSUE TITLE
offline install

### ISSUE THREAD

**Issue by c4po** [kubernetes/kops#3250]
Can we add a feature to install kubernetes cluster in a VPC without IGW?
for example, add a `kops download` command to download all package to S3. and `kops apply` command will guide the nodes install it from s3

**Comment by chrislovecnm** [comment]
We have work in progress for support of hosting all asests in a custom location, and also http proxy support as well.

**Comment by ti-yoyo** [comment]
How is the progress, currently kops supports offline deployment?

**Comment by rwd5213** [comment]
Any update this as well? Looking to have all kubernetes containers and exectuables in a private docker repo or S3

**Comment by iusergii** [comment]
Raised a new one: https://github.com/kubernetes/kops/issues/9143
