### ISSUE TITLE
Kops should fail instantly when an unsupported instance type is used

### ISSUE THREAD

**Issue by wknapik** [kubernetes/kops#3252]
Currently `kops create cluster` called with an unsupported instance type, like m1.medium, for --master-size/--node-size will enter an infinite loop, with the following warning:
* Nodes:
```
W0822 12:16:20.082441    7113 executor.go:109] error running task "LaunchConfiguration/nodes.foo" (4m4s remaining to succeed): instance type not handled: "m1.medium"
```
* Masters:
```
W0822 12:16:20.082483    7113 executor.go:109] error running task "LaunchConfiguration/master-eu-west-1a.masters.foo" (4m4s remaining to succeed): instance type not handled: "m1.medium"
```
* Then:
```
I0822 12:16:30.795207    7113 executor.go:124] No progress made, sleeping before retrying 2 failed task(s)
```
That gets in the way of automation.

Fail early.

PS. Version 1.6.0 (git-f69a313)

**Comment by wknapik** [comment]
Just realized this might be a duplicate of #157.

**Comment by chrislovecnm** [comment]
We had a PR go into I think 1.7.0 that should have helped with this. Can you test?

**Comment by KashifSaadat** [comment]
This still seems to be an issue (built and tested on master, `Version 1.7.1-beta.1 (git-34473e860)`).

I've made a quick attempt at fixing this in PR #3257, which makes use of the `GetMachineTypeInfo` helper function, validating against a hard-coded list of available AWS machine types. Let me know what you think!
