### ISSUE TITLE
can we change the admin dashboard password generated by kops during cluster formation

### ISSUE THREAD

**Issue by rvishwakarma825** [kubernetes/kops#3256]
can we change or reset the admin dashboard password generated by kops during cluster formation

**Comment by chrislovecnm** [comment]
At the point it is unsupported. A workaround is documented in the secrets docs

**Comment by rvishwakarma825** [comment]
Many thanks for your response Chris.......let me know if you can share that workaround in 1-2-1 at rvishwakarma825@gmail.com .

**Comment by hugocf** [comment]
Docs are here: [Workaround for changing secrets with type "Secret"](https://github.com/kubernetes/kops/blob/master/docs/secrets.md#workaround-for-changing-secrets-with-type-secret)

**Comment by chrislovecnm** [comment]
Thanks @hugocf

**Comment by rvishwakarma825** [comment]
Thanks @hugocf & @chrislovecnm

**Comment by chrislovecnm** [comment]
closing
