### ISSUE TITLE
Configure RBAC from command line

### ISSUE THREAD

**Issue by dcodix** [kubernetes/kops#3258]
To get RBAC in place I had t manually edit the cluster and add the lines:
```
authenticationTokenWebhookConfigFile: /a/path/webhook.json
authorizationMode: RBAC
authorizationRbacSuperUser: user
```
I see in the documentation the flag "--authorization" which I suppose it will create the "authorizationMode: RBAC". But, what about the other two? Is there any way to put those on place without manually editing the cluster?
If there isn't, are there any plans to add this functionality? or is it something for what PR's would be accepted?

**Comment by chrislovecnm** [comment]
Take a look at this first, as I think a using  manifest is another option. https://github.com/kubernetes/kops/blob/master/docs/manifests_and_customizing_via_api.md

**Comment by dcodix** [comment]
Oh thanks Chris, I were not aware of that and it sounds really good. I will take a look to see if it fits our needs.

**Comment by dcodix** [comment]
I did get the time to test but for the documentation it seems we will be able to use it for our purposes. So, yes, you can close it and in any case I can open another issue.
Thanks!
