### ISSUE TITLE
give kops ability to set kubelet flags volume-stats-agg-period and --runtime-request-timeout

### ISSUE THREAD

**Issue by lindsaylandry** [kubernetes/kops#3265]
**This is a feature request**

I need to set kubelet flags --runtime-request-timeout=10h and volume-stats-agg-period=10h. This is due to the fact that we have large containers (about 2GB in size) and running du on all of them takes up a lot of cpu and memory. I was trying to see if we could run volume stats less often and not have them time out after 2m (default for runtime-request-timeout).

Currently in order to do this I have to go into every node and manually adjust /etc/sysconfig/kubelet. I would like to be able to adjust these values with `kops edit cluster <cluster-name>` under `spec.kubelet`

while i'm at it I was wondering why it's not possible to adjust all flags specified in https://kubernetes.io/docs/admin/kubelet/. The docs make it seem like it's possible, but using the cli proves otherwise.

**Comment by chrislovecnm** [comment]
Closing as bot did not
