### ISSUE TITLE
Build status unclear from documentation and tool

### ISSUE THREAD

**Issue by neilhwatson** [kubernetes/kops#3269]
Consider this:

https://github.com/kubernetes/kops/blob/master/docs/aws.md#build-the-cluster

> Now we take the final step of actually building the cluster. This'll take a
> while. Once it finishes you'll have to wait longer while the booted instances
> finish downloading Kubernetes components and reach a "ready" state.

It's unclear how long it takes to reach a ready state or how to check its progress.

**Comment by r4j4h** [comment]
For what it's worth, the output of the `update cluster --yes` command looks like:

```
I0825 19:20:32.633277    7042 dns.go:152] Pre-creating DNS records
I0825 19:20:33.720337    7042 update_cluster.go:247] Exporting kubecfg for cluster
Kops has set your kubectl context to your.cluster.com

Cluster is starting.  It should be ready in a few minutes.

Suggestions:
 * validate cluster: kops validate cluster
 * list nodes: kubectl get nodes --show-labels
 * ssh to the master: ssh -i ~/.ssh/id_rsa admin@api.your.cluster.com
The admin user is specific to Debian. If not using Debian please use the appropriate user based on your OS.
 * read about installing addons: https://github.com/kubernetes/kops/blob/master/docs/addons.md
```

While it's not ideal in showing how far it's come and what is left, the `kops validate cluster` command can be re-run multiple times and will indicate whether things are ready or not. Once the API Server is accessible and responsive then it does show the nodes that have reported in which can be used as a gauge of how much is left.

The docs could definitely use some prefacing about this.

**Comment by chrislovecnm** [comment]
It usually takes 4-5 min but there are multiple factors. We probably should state 4-10 min. Any documentation improvements are always appreciated!
