### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#327]
The `kops` files probably need the standard Kubernetes legal boilerplate prior to a real release, if they're coming under the umbrella/ownership of the k8s project.

**Comment by chrislovecnm** [comment]
Done :)  We have a challenge with the autogen stuff.  Needs to be put into the make process.

**Comment by kris-nova** [comment]
Closing in favor of https://github.com/kubernetes/kops/issues/734
