### ISSUE TITLE
Now that 1.9 is out can we remove the Go 1.5 references in the docs?

### ISSUE THREAD

**Issue by andrewwatson** [kubernetes/kops#3271]
``` kops uses the relatively new Go vendoring, so building requires Go 1.6 or later, or you must export GO15VENDOREXPERIMENT=1 when building with Go 1.5. The makefile sets GO15VENDOREXPERIMENT for you. Go code generation does not honor the env var in 1.5, so for development you should use Go 1.6 or later ```

Can we update this now?

**Comment by chrislovecnm** [comment]
@andrewwatson please PR :)

**Comment by andrewwatson** [comment]
Ok, will do!

**Comment by chrislovecnm** [comment]
Closing
