### ISSUE TITLE
AWS install does not change from place holder IPs

### ISSUE THREAD

**Issue by neilhwatson** [kubernetes/kops#3273]
After going through this, https://github.com/kubernetes/kops/blob/master/docs/aws.md, 40min later the route53 dns records for the api still have the 203.0.113.123 place holder entries.

Nothing in the doc states how to troubleshoot this.

**Comment by r4j4h** [comment]
See https://github.com/kubernetes/kops/issues/1386#issuecomment-276789799 for some more information.

A `dns-controller` pod should be starting that reconfigures things.

I would suggest using EC2 console to get the Public IP of your master node and SSH onto him and `sudo su` and then `journalctl -e` and see if there are any logs indicating what is wrong.

You may also try `kubectl get po --all-namespaces` from the master node and check the individual pod logs.

**Comment by chrislovecnm** [comment]
@neilhwatson adding documentation about how to troubleshoot DNS would be a good idea. 

1. When you have HA Etcd with HA masters, protokube sets up the DNS for the Etcd endpoints.  
2. The `dns-controller` deployment sets the DNS records for all of the masters, and the API endpoint(s).  With an ELB for the API, or a Bastion ELB, DNS is setup on the ELB.  When not using ELBs setup is setup for each of the master(s) for the API endpoint.

@neilhwatson can you provide any information from the `dns-controller` logs?

**Comment by neilhwatson** [comment]
A few sample log entries. Nothing jumps out. I've subbed my domain (a hosted domain in AWS) for example in this sample.

daemon.log:Aug 29 12:44:21 ip-172-20-37-66 docker[1510]: I0829 12:44:21.978796       1 dnscontroller.go:258] updating records for {A etcd-events-a.internal.k01.k8s.example.net}: [] -> [172.20.37.66]
./daemon.log:Aug 29 12:44:21 ip-172-20-37-66 docker[1510]: I0829 12:44:21.978816       1 dnscontroller.go:567] will replace existing dns record A etcd-events-a.internal.k01.k8s.example.net.
./daemon.log:Aug 29 12:44:21 ip-172-20-37-66 docker[1510]: I0829 12:44:21.978822       1 dnscontroller.go:571] Adding DNS changes to batch {A etcd-events-a.internal.k01.k8s.example.net} [172.20.37.66]
./daemon.log:Aug 29 12:44:21 ip-172-20-37-66 docker[1510]: I0829 12:44:21.978835       1 dnscontroller.go:301] applying DNS changeset for zone k8s.example.net.::Z3DTR6HOCGKBEK

Aug 29 13:15:11 ip-172-20-37-66 kubelet[1594]: E0829 13:15:11.922450    1594 kubelet.go:1607] Failed creating a mirror pod for "kube-apiserver-ip-172-20-37-66.ca-central-1.compute.internal_kube-system(e5ff26add6

Aug 29 13:15:19 ip-172-20-37-66 docker[1510]: I0829 13:15:19.183911       1 kube_dns.go:35] Creating DNS record: etcd-a.internal.k01.k8s.example.net => [172.20.37.66]
Aug 29 13:15:19 ip-172-20-37-66 docker[1510]: I0829 13:15:19.185183       1 kube_dns.go:35] Creating DNS record: etcd-events-a.internal.k01.k8s.example.net => [172.20.37.66]

Aug 29 13:16:11 ip-172-20-37-66 kubelet[1594]: E0829 13:16:11.222612    1594 pod_workers.go:182] Error syncing pod ac74e4b8b282a25f1479c0ad2db92955 ("etcd-server-ip-172-20-37-66.ca-central-1.compute.internal_kub
Aug 29 13:16:11 ip-172-20-37-66 kubelet[1594]: E0829 13:16:11.227127    1594 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://127.0.0.1/api/v1/nodes?fieldSelec
Aug 29 13:16:11 ip-172-20-37-66 kubelet[1594]: E0829 13:16:11.917250    1594 eviction_manager.go:238] eviction manager: unexpected err: failed GetNode: node 'ip-172-20-37-66.ca-central-1.compute.internal' not fo
Aug 29 13:16:11 ip-172-20-37-66 kubelet[1594]: E0829 13:16:11.924393    1594 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://127.0.0.1/api/v1/services?reso

**Comment by neilhwatson** [comment]
There are also some Docker containers that have exited (lines from docker ps -a below). Don't know if that's expected or an error:

11f3cf61a572        gcr.io/google_containers/etcd@sha256:19544a655157fb089b62d4dac02bbd095f82ca245dd5e31dd1684d175b109947                      "/bin/sh -c '/usr/loc"   9 seconds ago       Exited (1) 6 seconds ago                         k8s_etcd-container_etcd-server-ip-172-20-37-66.ca-central-1.compute.internal_kube-system_ac74e4b8b282a25f1479c0ad2db92955_14

4c8ae4d264fa        gcr.io/google_containers/kube-apiserver@sha256:f880371b4cee1a810d7caf4c8a2c0b8fa169879545b06a537e4ea6bcdfbbe1f6            "/bin/sh -c '/usr/loc"   23 seconds ago      Exited (255) 3 seconds ago                       k8s_kube-apiserver_kube-apiserver-ip-172-20-37-66.ca-central-1.compute.internal_kube-system_e5ff26add6a6eddfad8436321cb0e4b1_17

1212626d44a3        gcr.io/google_containers/etcd@sha256:19544a655157fb089b62d4dac02bbd095f82ca245dd5e31dd1684d175b109947                      "/bin/sh -c '/usr/loc"   4 minutes ago       Exited (1) 4 minutes ago                         k8s_etcd-container_etcd-server-events-ip-172-20-37-66.ca-central-1.compute.internal_kube-system_a8ababb172313ba64deedee1e3a3be8f_13

**Comment by neilhwatson** [comment]
It's always a fscking DNS problem. Root case was the subdomain.  An automatic sanity check or clearer DNS errors should exist.

**Comment by frankreno** [comment]
Can you share exactly what the issue was? I have this exact same problem. I am not using a subdomain and dig ns properly returns  the NS servers. I have the exact same symptoms you did.

**Comment by neilhwatson** [comment]
@frankreno In my case DNS lookups were not working. I had the wrong entries in the r53 domain and subdomain. I had AWS support help me out.

**Comment by chrislovecnm** [comment]
Hey all.  I opened an issue to document how to diagnosis problem such as these, please comment on #3888

**Comment by omarlari** [comment]
this still occurs if you have pass (--networking cni).

**Comment by thetomasz** [comment]
Lack of `enableDnsHostnames` on my VPC was the root cause of this issue for me. Already documented here: https://github.com/kubernetes/kops/issues/2135
