### ISSUE TITLE
kops installation on aws ::::: kubectl command not working after installing and creating cluster

### ISSUE THREAD

**Issue by ghoshaditya** [kubernetes/kops#3274]
when i run command : Kubectl get nodes, get this output : 
`unable to connect to the server:EOF`
when i run kubectl cluster-info : 
i just find cluster master running but no kube-dns running.
when i ssh into the master , then there is no service is running on port 443 of 8080 i.e. when i do kubectl get nodes on master , i get connection refused error

**Comment by chrislovecnm** [comment]
Need more details please

**Comment by decoursin** [comment]
I'm having the same problem, but I'm using a `kube-aws`, it seemed to happen after deleting a pod, but that might just be a coincidence.
