### ISSUE TITLE
could not find Image for "kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28"

### ISSUE THREAD

**Issue by hb404** [kubernetes/kops#3282]
I0826 02:53:52.777314    7591 executor.go:91] Tasks: 0 done / 67 total; 32 can run
I0826 02:53:53.083395    7591 executor.go:91] Tasks: 32 done / 67 total; 13 can run
I0826 02:53:53.233568    7591 executor.go:91] Tasks: 45 done / 67 total; 18 can run
W0826 02:53:53.624742    7591 executor.go:109] error running task "LaunchConfiguration/master-cn-north-1b.masters.hobocluster.k8s.local" (9m59s remaining to succeed): could not find Image for "kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28"
W0826 02:53:53.624844    7591 executor.go:109] error running task "LaunchConfiguration/nodes.hobocluster.k8s.local" (9m59s remaining to succeed): could not find Image for "kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28"
I0826 02:53:53.624920    7591 executor.go:91] Tasks: 61 done / 67 total; 3 can run
W0826 02:53:53.770954    7591 executor.go:109] error running task "LaunchConfiguration/nodes.hobocluster.k8s.local" (9m59s remaining to succeed): could not find Image for "kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28"
W0826 02:53:53.771036    7591 executor.go:109] error running task "LaunchConfiguration/master-cn-north-1b.masters.hobocluster.k8s.local" (9m59s remaining to succeed): could not find Image for "kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28"
I0826 02:53:53.771120    7591 executor.go:91] Tasks: 62 done / 67 total; 2 can run

**Comment by chrislovecnm** [comment]
@justinsb am I correct in guessing that you are unable to push the kops ami to China?
