### ISSUE TITLE
nodes fail to connect to each other with gossip discovery [CoreOS, 1.7.x, GovCloud]

### ISSUE THREAD

**Issue by ketzacoatl** [kubernetes/kops#3297]
Hello,

I have been working to get a kube cluster running on AWS GovCloud with the following combination:
* GovCloud region
* running on CoreOS
* with kube 1.7.2
* with kops 1.7.0
* gossip discovery (no Route53 on GovCloud)
* private network topology
* I've provided kops with the VPC and subnets to use, it has not created the network itself

This combination _almost_ works, I see a master, but no worker nodes:

```
kubectl get nodes
NAME                                             STATUS    AGE       VERSION
ip-a.b.c.d-us-gov-west-1.compute.internal   Ready     45m       v1.7.2
```

When I SSH to the worker nodes, I poke around and eventually find this in the `protokube` logs:

```
{"log":"I0828 05:25:19.204694       1 gossip.go:123] Seeding successful\n","stream":"stderr","time":"2017-08-28T05:25:19.20698271Z"}
{"log":"I0828 05:25:19.204761       1 glogger.go:31] -\u003e[10.120.21.28:3999] attempting connection\n","stream":"stderr","time":"2017-08-28T05:25:19.206988684Z"}
{"log":"I0828 05:25:19.204762       1 glogger.go:31] -\u003e[10.120.20.79:3999] attempting connection\n","stream":"stderr","time":"2017-08-28T05:25:19.206992548Z"}
{"log":"I0828 05:25:19.204827       1 glogger.go:31] -\u003e[10.120.20.63:3999] attempting connection\n","stream":"stderr","time":"2017-08-28T05:25:19.206995719Z"}
{"log":"I0828 05:25:19.204828       1 glogger.go:31] -\u003e[10.120.21.252:3999] attempting connection\n","stream":"stderr","time":"2017-08-28T05:25:19.206999432Z"}
{"log":"I0828 05:25:19.204873       1 glogger.go:31] -\u003e[10.120.20.142:3999] attempting connection\n","stream":"stderr","time":"2017-08-28T05:25:19.207002692Z"}
{"log":"I0828 05:25:19.204961       1 glogger.go:31] -\u003e[10.120.21.252:42815] connection accepted\n","stream":"stderr","time":"2017-08-28T05:25:19.207005822Z"}
{"log":"I0828 05:25:19.205565       1 glogger.go:31] -\u003e[10.120.21.28:3999] error during connection attempt: dial tcp4 0.0.0.0:0-\u003e10.120.21.28:3999: getsockopt: connection refused\n","stream":"stderr","time":"2017-08-28T05:25:19.207474532Z"}
{"log":"I0828 05:25:19.205888       1 glogger.go:31] -\u003e[10.120.21.252:3999|dafdd57bd2a92751317e3011faedabf3(i-0b6a24662b143a06f)]: connection shutting down due to error: cannot connect to ourself\n","stream":"stderr","time":"2017-08-28T05:25:19.207486354Z"}
{"log":"I0828 05:25:19.206044       1 glogger.go:31] -\u003e[10.120.21.252:42815|dafdd57bd2a92751317e3011faedabf3(i-0b6a24662b143a06f)]: connection shutting down due to error: cannot connect to ourself\n","stream":"stderr","time":"2017-08-28T05:25:19.207501382Z"}
{"log":"I0828 05:25:19.206141       1 glogger.go:31] -\u003e[10.120.20.63:3999] error during connection attempt: dial tcp4 0.0.0.0:0-\u003e10.120.20.63:3999: getsockopt: connection refused\n","stream":"stderr","time":"2017-08-28T05:25:19.207505258Z"}
{"log":"I0828 05:25:19.206171       1 glogger.go:31] -\u003e[10.120.20.142:3999] error during connection attempt: dial tcp4 0.0.0.0:0-\u003e10.120.20.142:3999: getsockopt: connection refused\n","stream":"stderr","time":"2017-08-28T05:25:19.207508881Z"}
{"log":"I0828 05:25:19.208034       1 glogger.go:31] -\u003e[10.120.20.79:3999|0def9472a0c4ea1fc6181c520fd410d3(i-033f0d1f4613d5e33)]: connection ready; using protocol version 2\n","stream":"stderr","time":"2017-08-28T05:25:19.208615505Z"}
{"log":"I0828 05:25:19.208068       1 glogger.go:31] -\u003e[10.120.20.79:3999|0def9472a0c4ea1fc6181c520fd410d3(i-033f0d1f4613d5e33)]: connection added (new peer)\n","stream":"stderr","time":"2017-08-28T05:25:19.208646366Z"}
{"log":"I0828 05:25:19.208091       1 peer.go:97] Gossip =\u003e complete \u0026KVState{Records:map[string]*KVStateRecord{},}\n","stream":"stderr","time":"2017-08-28T05:25:19.208653071Z"}
{"log":"I0828 05:25:19.208921       1 peer.go:115] OnGossip \u0026KVState{Records:map[string]*KVStateRecord{},} =\u003e delta empty\n","stream":"stderr","time":"2017-08-28T05:25:19.20933612Z"}
{"log":"I0828 05:25:20.255192       1 glogger.go:31] -\u003e[10.120.21.28:3999] attempting connection\n","stream":"stderr","time":"2017-08-28T05:25:20.255497428Z"}
{"log":"I0828 05:25:20.255760       1 glogger.go:31] -\u003e[10.120.21.28:3999] error during connection attempt: dial tcp4 0.0.0.0:0-\u003e10.120.21.28:3999: getsockopt: connection refused\n","stream":"stderr","time":"2017-08-28T05:25:20.255898171Z"}
```

I have let these nodes sit idle for a while to ensure it is not just an issue of waiting long enough.

I don't know a whole lot about  how kube is doing its gossip discovery, but it seems the nodes are finding one another's IP addresses, but failing to connect to weave. `connection refused` is a rather obvious error to investigate, but unfortunately, I'm not finding the reason for that failure.

I first checked the node security groups, and those look good.

On each node, I see `3999` open with `netstat`:

```
$ netstat -an | grep LISTEN | grep 3999
tcp        0      0 0.0.0.0:3999            0.0.0.0:*               LISTEN
```

and I can also connect to that port (from a non-kube node) with `nc` and see weave:

```
$ nc -v 10.120.21.252 3999
Connection to 10.120.21.252 3999 port [tcp/*] succeeded!
weave
```

CoreOS doesn't have `nc`, but testing from a kube node with an `alpine` image, I see the same (to confirm the kube nodes can reach `3999`):

```
/ # nc -v 10.120.20.63 3999
Connection to 10.120.20.63 3999 port [tcp/3999] succeeded!
weave^C
```

Hopefully this is enough info to identify the issue, but to let me know if there is any other info that I can provide. Note that, just to be sure.. I have deleted the cluster and re-created fresh with the same specs, to be sure I can reproduce the issue.

**Comment by sarphram** [comment]
I ran into very similar issues the other day but on a regular AWS account with route53 access denied at the org level.

Can you ssh into the master and check the logs output of the kope/dns-controller container? I saw lines similar to the following and wondered if the service not being available would produce the same effect:
 `dnscontroller.go:119] Unexpected error in DNS controller, will retry: error querying for zones: error querying for DNS zones: AccessDenied: User: arn:aws:sts::<redacted> is not authorized to perform: route53:ListHostedZones`

It seems that the dns controller will refuse to do anything until it has that permission; the cluster came up pretty quickly after allowing ListHostedZones on the org policy.

**Comment by chrislovecnm** [comment]
@ketzacoatl can we close this?
@sarphram do you still need to add a custom iam policy to fix this, or does the iam profile work in gov?

**Comment by ketzacoatl** [comment]
@chrislovecnm is it fixed?

**Comment by sarphram** [comment]
@chrislovecnm My issue wasn't in a govcloud account, but a regular region that had route 53 available. A [service control policy](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scp.html) was applied to my account from the org master account removing route 53 access which seemed to produce a similar effect as just not having the service at all.

My eventual workaround was to rebuild the dns-controller image and remove the listhostedzones (iirc) call made on startup.

**Comment by chrislovecnm** [comment]
@sarphram are you able to contribute a fix? Wondering if that call could be a warning rather than an error

**Comment by sarphram** [comment]
@chrislovecnm 
My fix isn't ideal...but to help at least some: I changed https://github.com/kubernetes/kops/blob/b44d894813fb583d63c7e9b2ff211747053fdc54/dns-controller/pkg/dns/dnscache.go#L82 to "continue", which worked for our setup at the time. but I didn't test it on any other setup configurations.
