### ISSUE TITLE
Don't default to HA master

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#33]
My thoughts on slack:

> I recommend `kops create cluster ... --zones us-east-1b,us-east-1c,us-east-1d --master-zones us-east-1b` to get multizone without HA master for now
> Unless you really want HA master.  And I'm probably going to change the default so it doesn't push people that aren't expecting HA master to HA master
> (single zone master is still relatively available.  HA master is slower and not as well tested/known.)

**Comment by davidopp** [comment]
cc/ @jszczepkowski @fgrzadkowski
