### ISSUE TITLE
Customizing docker config for a particular instance group

### ISSUE THREAD

**Issue by erickt** [kubernetes/kops#3311]
Kops recently grew support for configuring docker config files in #3087, and custom ulimits in #3259. As best as I can tell this configuration is applied cluster-wide, but I have a use case where I would like to customize the config for a particular instance group.

We are working through creating a [Helm chart for Hashicorp Vault](https://github.com/kubernetes/charts/pull/1397). One of the recommendations is to [run Vault on a dedicated machine with core dumps turned off](https://www.vaultproject.io/guides/production.html). It's easy enough to create a dedicated instance group for Vault, but there's no easy way to disable core dumps. While Docker has the ability to set ulimits, Kubernetes does not expose this [option](https://github.com/kubernetes/kubernetes/issues/3595). The docker-vault team also doesn't think this setting should be [baked into the image](https://github.com/hashicorp/docker-vault/issues/50).

So the two options I see are creating a wrapper Dockerfile that sets the limit (which adds operational complexity), or to set a docker config option that specifies the ulimit. I don't want to disable core dumps everywhere, so would it be possible to allow instance groups to override the global docker config setting?

**Comment by sybeck2k** [comment]
I have the same need for setting a log-group for AWS CloudWatch logs - it would be nice to have a different log-group per instance group (e.g. master and nodes)

**Comment by Cryptophobia** [comment]
It would be nice if docker version and storage driver options can be defined per instance group. It will allow people to test differences in performance of docker versions and different storage drivers.

**Comment by wlawton** [comment]
I want to specify different docker log options for different instance groups.
