### ISSUE TITLE
Change the default instance type of worker node

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kops#3312]
Created a cluster:

```
kops create cluster \
  earth.kubernetes-aws.io \
  --master-count=3 \
  --master-zones us-east-1a,us-east-1b,us-east-1c \
  --zones us-east-1a,us-east-1b,us-east-1c \
  --node-count=3 \
  --yes
```

Validating the cluster shows:

```
kops validate cluster --name=earth.kubernetes-aws.io
Validating cluster earth.kubernetes-aws.io

INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-us-east-1a-1	Master	m3.medium	1	1	us-east-1a
master-us-east-1a-2	Master	m3.medium	1	1	us-east-1a
master-us-east-1b-1	Master	m3.medium	1	1	us-east-1b
nodes			Node	t2.medium	3	3	us-east-1a,us-east-1b
```

The default worker node instance type is `t2.medium`. The instance type of the worker can be changed using `--node-size`. However, I think a slightly more powerful instance type, such as `m4.large` (2 vCPU and 8GB), may be a better choice as the default worker type. This makes the default cluster created with kops as a lot more functional.

**Comment by chrislovecnm** [comment]
I am wondering if we should print an info message with a create that is using the default node size. We run e2e testing with the t2’s btw. 

/remove-lifecycle stale
