### ISSUE TITLE
Weave network addon regression in master since release-1.7

### ISSUE THREAD

**Issue by aponomarenko** [kubernetes/kops#3315]
Hi,

I'm creating a cluster with 1 master and 2 nodes on AWS:

    kops create cluster aponomarenko.k8s.local \
    --master-count=1 \
    --node-count=2 \
    --master-size="t2.small" \
    --node-size="t2.micro" \
    --cloud=aws \
    --image="ami-0c2aba6c" \
    --networking=weave \
    --zones="us-west-2a,us-west-2b,us-west-2c" \
    --kubernetes-version="1.7.4"

All works fine with `kops` `release-1.7`.

But with the latest `kops` 155650eb82a1a7cc4e98a29e63988cd727449e97 from master there are no weave pods created:

    ~]$ kubectl get pods --all-namespaces
    NAMESPACE     NAME                                                                  READY     STATUS    RESTARTS   AGE
    kube-system   dns-controller-3497129722-hcsrw                                       0/1       Pending   0          29m
    kube-system   etcd-server-events-ip-172-20-51-124.us-west-2.compute.internal        1/1       Running   0          28m
    kube-system   etcd-server-ip-172-20-51-124.us-west-2.compute.internal               1/1       Running   0          29m
    kube-system   kube-apiserver-ip-172-20-51-124.us-west-2.compute.internal            1/1       Running   0          29m
    kube-system   kube-controller-manager-ip-172-20-51-124.us-west-2.compute.internal   1/1       Running   0          28m
    kube-system   kube-dns-479524115-n1krm                                              0/3       Pending   0          29m
    kube-system   kube-dns-autoscaler-1818915203-bc36t                                  0/1       Pending   0          29m
    kube-system   kube-proxy-ip-172-20-51-124.us-west-2.compute.internal                1/1       Running   0          29m
    kube-system   kube-scheduler-ip-172-20-51-124.us-west-2.compute.internal            1/1       Running   0          28m

Error in journal (on master node):

    ~]$ journalctl -xe
    Aug 30 08:22:13 ip-172-20-39-119 kubelet[9738]: W0830 08:22:13.251650    9738 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d/
    Aug 30 08:22:13 ip-172-20-39-119 kubelet[9738]: E0830 08:22:13.251769    9738 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

And file `/etc/cni/net.d/10-weave.conf` doesn't exist.

This can be fixed by the following command:

    kubectl -n kube-system delete -f https://git.io/weave-kube-1.6
    kubectl -n kube-system apply -f https://git.io/weave-kube-1.6

And for now all looks fine:

    ~]$ kubectl get pods --all-namespaces
    NAMESPACE     NAME                                                                  READY     STATUS    RESTARTS   AGE
    kube-system   dns-controller-3497129722-hcsrw                                       1/1       Running   0          47m
    kube-system   etcd-server-events-ip-172-20-51-124.us-west-2.compute.internal        1/1       Running   0          46m
    kube-system   etcd-server-ip-172-20-51-124.us-west-2.compute.internal               1/1       Running   0          46m
    kube-system   kube-apiserver-ip-172-20-51-124.us-west-2.compute.internal            1/1       Running   0          46m
    kube-system   kube-controller-manager-ip-172-20-51-124.us-west-2.compute.internal   1/1       Running   0          46m
    kube-system   kube-dns-479524115-n1krm                                              3/3       Running   0          47m
    kube-system   kube-dns-479524115-s1wzt                                              3/3       Running   0          15m
    kube-system   kube-dns-autoscaler-1818915203-bc36t                                  1/1       Running   0          47m
    kube-system   kube-proxy-ip-172-20-109-93.us-west-2.compute.internal                1/1       Running   0          15m
    kube-system   kube-proxy-ip-172-20-51-124.us-west-2.compute.internal                1/1       Running   0          47m
    kube-system   kube-proxy-ip-172-20-72-245.us-west-2.compute.internal                1/1       Running   0          14m
    kube-system   kube-scheduler-ip-172-20-51-124.us-west-2.compute.internal            1/1       Running   0          46m
    kube-system   weave-net-2ggqx                                                       2/2       Running   0          15m
    kube-system   weave-net-3hmv5                                                       2/2       Running   0          16m
    kube-system   weave-net-czw9b                                                       2/2       Running   0          15m

Is this a regression with the weave networking addon? Or I should fix my `kops create cluster` command somehow?

Thank you.

**Comment by chrislovecnm** [comment]
If you give the cluster a bit does weave finally install? I have not encountered this with weave. The messages you have seen are corrected eventually. The cluster is created using eventual consistency and the error messages are new for 1.7.
