### ISSUE TITLE
Better documentation for InstanceGroups

### ISSUE THREAD

**Issue by Cryptophobia** [kubernetes/kops#3316]
InstanceGroups are important and they must be defined. When there is only one availability zone in a region (eu-cental-1) and it has multiple masters, there _must_ be multiple InstanceGroups defined so that the masters will all get configured in etcd and Route53. Otherwise, you can never have more than one master in a single availability zone in a region.

https://github.com/kubernetes/kubernetes/issues/50622

We need better disclaimer/documentation for this...

I can either write some or someone else, but would like it to be peer reviewed because still don't understand kops completely.

**Comment by robinpercy** [comment]
@Cryptophobia contributions are always welcome - and also always peer reviewed :) When you have something for review, just submit a PR and preface the title with "WIP:" so folks know it's still in progress.

**Comment by Cryptophobia** [comment]
I opened a PR with some of the text of the disclaimer I want to add to the docs. Would like for other people to peer review as well.

https://github.com/kubernetes/kops/pull/3445

Thanks!
