### ISSUE TITLE
Changing network topology from public to private on AWS

### ISSUE THREAD

**Issue by krogon-dp** [kubernetes/kops#3320]
Is there such kind of modification supported?

I read about ELB public/private [hookup](https://github.com/kubernetes/kops/blob/master/docs/topology.md#changing-topology-of-the-api-server), but I currently use public DNS to access API.

What's more I will have to [change my current networking ](https://github.com/kubernetes/kops/blob/master/docs/topology.md#defining-a-topology-on-create)from kubenet to other CNI. Is there a reason to make these changes in two separate steps (networking than topology)?

Do I have to expect API downtime (creating all new masters than ELB and Route53 entry)?

**Comment by robinpercy** [comment]
@krogon-dp neither of those operations should be considered supported. Others have attempted similar changes, with varying degrees of success depending on their initial configuration. The latest example I could find is: https://kubernetes.slack.com/archives/C3QUFP0QM/p1497440013275839
