### ISSUE TITLE
Cannot create cluster with some configuration

### ISSUE THREAD

**Issue by hhuchzh** [kubernetes/kops#3326]
I used kops to create cluster on aws. 
But the default configuration of kubernetes component could not meet us, 
such as the parameter '--service-node-port-range' of kube-apiserver, i want to add it,
i have read https://github.com/kubernetes/kops/blob/master/docs/manifests_and_customizing_via_api.md,
but i did not find this parameter in cluster spec...

How can i add the parameters for kubernetes?

**Comment by chrislovecnm** [comment]
Closing as fixed
