### ISSUE TITLE
Create cluster on GCE results in an invalid instanceGroupManager value

### ISSUE THREAD

**Issue by jpaulgs** [kubernetes/kops#3334]
Hi I'm running the following command:

```
kops create cluster xxx.xxx.xxxxxxxxx.xxxx --cloud gce --zones australia-southeast1-c --node-count 3 --project xxxxxxxxx-xxx-xxx --image ubuntu-os-cloud/ubuntu-1604-xenial-v20170202 --out=. --yes
```

Which is resulting in the following error:

```
W0904 10:20:23.782545   42904 executor.go:109] error running task "InstanceGroupManager/australia-southeast1-c-master-australia-southeast1-c-dex-dev-greensync-link" (8m10s remaining to succeed): error listing InstanceGroupManagers: googleapi: Error 400: Invalid value for field 'instanceGroupManager': 'australia-southeast1-c-master-australia-southeast1-c-xxx-xxx-xxxxxxxx-xxxx'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```

Is there a way to control the name of the instance group manager?  This is coming in at 75 characters and it looks like the maximum length is 63

**Comment by chrislovecnm** [comment]
This appears to be a bug, this is an automatically generated name. We are always happy to have contributions! We probably should shorten Australia to aus?

**Comment by jpaulgs** [comment]
Shortening the name to aus could work however I was looking to create a gossip based cluster, at the moment that seems to require the cluster name being appended with .k8s.local

If I get a chance I'll  have a look into how this name is being generated.

**Comment by chrislovecnm** [comment]
This should be fixed in master. Can you test?

**Comment by chrislovecnm** [comment]
@jpaulgs I am going to close this because I am pretty sure it is fixed.
