### ISSUE TITLE
aws inspector support for debian 4.4.65

### ISSUE THREAD

**Issue by rajholla** [kubernetes/kops#3335]
The debian AMI doesn't appears to have support for AWS inspector.

AMI used : 
k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02

Message from install agent 
$bash install
Failed to find an inspector agent package for this OS:debian-4.4..
Script exited with status code MISSING_AGENT_PLATFORM debian-4.4

I am not very certain whether this issue belongs here but wanted to get some clarification.

**Comment by chrislovecnm** [comment]
The ami is built out of the kube-deploy project. But issues here are fine. Not certain what you need though

**Comment by thedarkfalcon** [comment]
I'm in a bit of a rut regarding this. I would like the default images to include inspector so we have inspector out of the box. However the kube-deploy project is environment agnostic so won't include AWS specific functionality within their images.. I don't really want to have to maintain my own kubernetes images either :-/
I could implement some sort of process that polls all of my clusters masters and nodes, and installs inspector if its not there (via ansible or something similar).. I was hoping to have never to actually access the boxes directly.
