### ISSUE TITLE
disable bastion elb when no bastions are enabled

### ISSUE THREAD

**Issue by a1dutch** [kubernetes/kops#3341]
It would be good to disable the bastion ELB in AWS when the `maxSize=0` and recreate when the maxSize>0

**Comment by macropin** [comment]
This is a documentation issue.

Try `kops delete ig bastions`.

**Comment by tushar00jain** [comment]
@macropin deleting the instance group does not delete the ELB
will be good to have this feature

/reopen
/remove-lifecycle rotten

**Comment by tushar00jain** [comment]
@a1dutch mind if i take this issue?

**Comment by a1dutch** [comment]
@tushar00jain sure, do you need me to do something?

**Comment by tushar00jain** [comment]
@a1dutch not at the moment
