### ISSUE TITLE
Kops should be able to add annotations

### ISSUE THREAD

**Issue by lucascollino** [kubernetes/kops#3344]
Hi, similar to #742 I need to add annotations to nodes (from the instance group yaml) for managing the update-operator, in the same way labels are.

Something equivalent to this, but with annotations:

```
spec:
  nodeLabels:
    kubernetes.io/role: node
```
Maybe it's already in place or planned, but didn't find it in the docs nor the code.

Thanks!

**Comment by chrislovecnm** [comment]
We are able to add node and cloud tags, I am not certain how this functionality differs.

You have to use yaml to maintain your clusters or edit the cluster. Here is an example https://github.com/kubernetes/kops/blob/master/tests/integration/complex/in-v1alpha2.yaml

Also the instance group documentation provides examples.

**Comment by greg-jaunt** [comment]
The example above *is* already possible, but the needed feature is the equivalent of the above for annotations:

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
spec:
  annotations:
    somekey: somevalue
```

Would automatically add "somekey:somevalue" to the metadata.annotation map on every launched node in that instance group.

**Comment by Z3r0Sum** [comment]
@greg-jaunt I had issues trying to use your suggestion.  I made the changes to an existing IG though.  They did not persist after saving the changes and there was no error. Using kops 1.7.1.

**Comment by lucascollino** [comment]
/reopen

for @adammw comment

**Comment by semoac** [comment]
This will be awesome to automatize thing like routeReflector on calico.
