### ISSUE TITLE
Canal should be updated to use Calico v2.5

### ISSUE THREAD

**Issue by tmjd** [kubernetes/kops#3352]
With Kubernetes deprecation of ThirdPartyResources (TPR) in favor of Custom Resource Definitions (CRD) Calico has to switch over to CRDs. The v2.5 release makes that switch and requires a migration step for deployments using the Kubernetes Datastore. A migration guide can be found https://github.com/projectcalico/calico/tree/master/upgrade/v2.5

Another thing to be aware of is that CRDs are first available in Kubernetes v1.7. This means that if Calico v2.5 is using the Kubernetes Datastore it must be used with Kubernetes 1.7+, it cannot be used with Kubernetes 1.6.x or lower.

Feel free to reach out to me (@tmjd, erik.stidham on slack) or @ozdanborne
on github, Kubernetes slack, or Calico slack to collaborate.

**Comment by chrislovecnm** [comment]
The update is quite simple.  Take a look at https://github.com/kubernetes/kops/pull/3187 

Someone would need to update bootstrap builder to test for k8s 1.7, and add a v1.7.0 manifest.  Would love to have you contribute a PR!

**Comment by tmjd** [comment]
Hi @chrislovecnm, I'm the one that submitted #3187 :smile:.
The update to v2.5 requires a Calico data migration step and requires K8s v1.7, so is not as simple as that one.  At minimum, even if it is expected that the user is expected to understand the need to manually do the migration prior to using Kops to update the Calico versions, there is also the requirement that this is only used for K8s v1.7 or higher.

**Comment by jhernandezb** [comment]
What about including it for k8s 1.8, the TPR API is removed in this version so it won't work even for older versions of calico (< 2.5)

**Comment by KashifSaadat** [comment]
Hi @tmjd, since PR #3623 has been merged in can we close this issue?

**Comment by chrislovecnm** [comment]
closing - please let us know if we need to re-open
