### ISSUE TITLE
Deleting a cluster without an s3 bucket

### ISSUE THREAD

**Issue by addisonlee** [kubernetes/kops#3353]
I mistakenly deleted the s3 bucket associated with the k8s cluster which I want to delete with the `kops delete cluster` command. Is there a way to delete a cluster without the associated s3 bucket?

**Comment by jdc0589** [comment]
I ran in to this recently too and had to just manually clean things up; which, was a much easier task since the cluster happened to be in a dedicated vpc.

**Comment by addisonlee** [comment]
> I ran in to this recently too and had to just manually clean things up; which, was a much easier task since the (lab/test) cluster happened to be in a dedicated vpc.

Any tips on doing this manually? Whenever I try to terminate ec2 instances, they keep respawning.

**Comment by chrislovecnm** [comment]
You can try importing the cluster maybe ... But the list of stuff we need is in s3.

Btw turning on versioning in s3 is a must!

**Comment by addisonlee** [comment]
> You can try importing the cluster maybe ... But the list of stuff we need is in s3.

Seems to be a chicken and egg problem - importing it without an s3 bucket gives an error because it needs the s3 bucket which doesn't exist. Simply creating an empty s3 bucket doesn't work either because it seems like the s3 bucket is what is used to do the import?

**Comment by KashifSaadat** [comment]
The below process will get somewhat through a few resources, but I think you'll still have some resources lingering such as IAM policies and maybe the VPC:
1. Set kops s3 state to your S3 bucket
2. Run `kops create cluster` with the same cluster name and settings (or `kops create -f cluster.yaml` if you have the config saved)
3. Without updating, run `kops delete cluster <cluster-name> --yes`, which should pick up some matching resources within AWS such as the ASGs, launch configurations etc

**Comment by addisonlee** [comment]
Thanks @KashifSaadat. That worked for one of my clusters but not 2 of the others (I'm guessing I modified them in some way which deviated from the default way clusters are created via kops); but I was able to delete the other 2 by first removing the auto scaling groups.

**Comment by ailtonmsj** [comment]
Thanks @KashifSaadat, It's works for me too.

**Comment by oesah** [comment]
@KashifSaadat You de boss.

**Comment by subinmt** [comment]
@KashifSaadat Thanks,Its worked for me

**Comment by utkarshns** [comment]
Delete the Auto Scaling groups created. :)
