### ISSUE TITLE
CLI native support in windows

### ISSUE THREAD

**Issue by Istar-Eldritch** [kubernetes/kops#3355]
Hi,

I would like to know if there are any plans to support the kops cli in windows.  And if so, roughly how much work it would imply and if it's feasible. I'm not experienced with go but I could give it a try if required.

(Duplicate of https://github.com/kubernetes/kops/issues/722)

**Comment by chrislovecnm** [comment]
There is another issue open for it. There are some issues with git and we are missing a couple of libraries. Happy to have support for our friends on windows!

**Comment by Istar-Eldritch** [comment]
Thank you for your fast response @chrislovecnm.
Please close as duplicate in favor of https://github.com/kubernetes/kops/issues/722

Just one comment, I got it working using the new Linux subsystem for windows 10 (under linux and using the linux binary), do you think it may be worth mentioning it somewhere in the README?

**Comment by chrislovecnm** [comment]
Yes please PR instructions how to run with WLS ;)
