### ISSUE TITLE
Support encrypting data at rest

### ISSUE THREAD

**Issue by kaazoo** [kubernetes/kops#3356]
k8s 1.7.0 adds support for encrypted secrets in etcd:
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

In order to make use of this, you need to add '--experimental-encryption-provider-config' argument to 'kube-apiserver'.

Is there an existing way to extend the arguments?
Or is another KubeAPIServerConfig option required for that? (https://godoc.org/k8s.io/kops/pkg/apis/kops#KubeAPIServerConfig)

Having this feature available with kops would be great for production use.

**Comment by zioalex** [comment]
I have exactly the same needs. Any advise here?

**Comment by zioalex** [comment]
Great. Please let me know if I can help here.
