### ISSUE TITLE
Cluster autoscaler addon cannot list statefulsets.apps at the cluster scope

### ISSUE THREAD

**Issue by johanhubens** [kubernetes/kops#3363]
After deploying the addon `https://github.com/kubernetes/kops/blob/master/addons/cluster-autoscaler/v1.6.0.yaml` to the cluster, the cluster autoscaler controller keeps logging the following:

```
E0911 09:07:02.607614       1 reflector.go:201] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72: Failed to list *v1beta1.StatefulSet: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list statefulsets.apps at the cluster scope. (get statefulsets.apps)
```

The cluster role `cluster-autoscaler` specified in the yaml file does not have any authorizations defined for reading statefulsets.

**Comment by niclic** [comment]
Just encountered this myself. Proposed [fix](https://github.com/kubernetes/kops/pull/3364) works.
