### ISSUE TITLE
Error listing images

### ISSUE THREAD

**Issue by JonahAcquah** [kubernetes/kops#3373]
Hi Guys, I am trying to deploy my public docker image using the kops create cluster command but keep getting "error listing images: InvalidUserID.Malformed: Invalid user id: "jetbrains"". I am using the image "jetbrains/teamcity-server" which I believe is public. I've tried other public images and still get the same error message. The full command is "kops create cluster myfirstcluster.k8s.local --node-count='3' --zones=eu-west-1a,eu-west-1b,eu-west-1c --master-zones=eu-west-1a,eu-west-1b,eu-west-1c --node-size=t2.micro --master-size='m3.medium' --topology=private --networking=weave --state='s3://xxxxx-state-store' --image='jetbrains/teamcity-server' --target=terraform". Any help?

**Comment by KashifSaadat** [comment]
Hi @JonahAcquah. The command you are running is to create the full Kops Kubernetes cluster, not to deploy / run a docker image on a node. The `--image` flag can be used to specify what to build the instances with (master & compute nodes), so you could provide an AWS AMI for CoreOS, Debian, etc or leave it to the default.

After fully creating the cluster, you can then communicate with it using `kubectl` and deploy pods using your docker image.

**Comment by JonahAcquah** [comment]
Thanks KashifSaadat. I knew I was doing something fundamentally wrong there.

**Comment by chrislovecnm** [comment]
Can we close?

**Comment by blakebarnett** [comment]
reopen if necessary
