### ISSUE TITLE
Manifest files with terraform/cfn output

### ISSUE THREAD

**Issue by pjoe** [kubernetes/kops#3374]
Is it possible to get terraform/cfn output when using manifest files?

Trying something like
`kops create -f myspec.yml --target=terraform --out=tf`
errors with:
`unknown flag: --target`

I'd really like to switch to using manifest with all the extra options, but need to go through terraform for setting up some extra stuff, like access to external RDS, S3 etc

**Comment by robinpercy** [comment]
@pjoe  you can do it in two steps:
```
$ kops create -f spec.yaml
$ kops update cluster kops.robinpercy.net --target terraform --out ./tf
```



```

**Comment by pjoe** [comment]
@robinpercy: doh, should have figured that out, of course `create` won't actually create any resources :)

If others end up here you also need to create the ssh secret (as shown in [docs](https://github.com/kubernetes/kops/blob/master/docs/manifests_and_customizing_via_api.md#yaml-examples) ) , so full commands would be something like:
```
$ kops create -f spec.yaml
$ kops create secret  --name $NAME sshpublickey admin -i ~/.ssh/id_rsa.pub
$ kops update cluster $NAME --target terraform --out ./tf
```

..oO(if only I could read docs properly)

closing issue

**Comment by simoneroselli** [comment]
@robinpercy, but then what "kops update cluster $NAME --target terraform --out ./tf" will exactly do? Does it just generate the terraform manifest? 
I thought "kops update" was the one which creates the actual resources on the cloud?
