### ISSUE TITLE
Using autoscaler with instancegroups, spot instances, that can go down to zero

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3388]
We should be able to have an instancegroup in kops that is set up to go down to zero.  Setup the instance group with a `maxPrice`, and have auto-scaler control the group.

https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-0.6.1

With that combination, you can have auto-scaler control a very affordable group of k8s nodes, and significantly reduce the price of the nodes.

cc: @Rishka

**Comment by Rishka** [comment]
related docs: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-scale-a-node-group-to-0

**Comment by chrislovecnm** [comment]
@andrewsykim can you comment on this?  Do we have a setup that we can reference that works?

**Comment by andrewsykim** [comment]
This is supported in GCE at the moment: https://github.com/kubernetes/autoscaler/issues/82. I believe AWS support is pending: https://github.com/kubernetes/autoscaler/issues/131. 

cc @mumoshu

**Comment by andrewsykim** [comment]
Unfortunately, I've never tried it and can't provide a setup that works :(

**Comment by Rishka** [comment]
As far as I can tell, this works. I spun up a temporary cluster to test it. It will scale the Instance Group to 0, and will allow scaling up from 0

**Comment by Rishka** [comment]
@andrewsykim AWS support is pending for price based autoscaling. Scale to 0 was added in 0.6.1

**Comment by Globegitter** [comment]
Only tangiably related and I already posted it on another issue here, but it would be great if an instancegroup of kops can work somehow with https://github.com/cristim/autospotting, further improving costs.

**Comment by mikn** [comment]
> And you need to add permissions for autoscaler to describe ASGs:
> [...]

Just want to chip in here, it turns out that this will be reset on each cluster update right now, as you can see here:
```diff
  IAMRolePolicy/masters.[...]
  	PolicyDocument      

 	                    	      {
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	          "autoscaling:DescribeAutoScalingGroups",
  	                    	          "autoscaling:DescribeAutoScalingInstances",
  	                  -               "autoscaling:DescribeAutoScalingInstances",
  	                  -               "autoscaling:DescribeTags",
  	                  - 	          "autoscaling:DescribeLaunchConfigurations",
  	                    	          "autoscaling:SetDesiredCapacity",
  	                    	          "autoscaling:TerminateInstanceInAutoScalingGroup"

  	                    	        ],

```

**Comment by stijndehaes** [comment]
In the latest version of kops 1.8.0 the autoscaling:DescribeLaunchConfigurations is added to the master permissions. autoscaling:DescribeTags is not added but according to the documentation of cluster autoscaler this is only needed when you use `--node-group-auto-discover`.

I have been testing with 0 as a min for autoscaling and it works.

**Comment by whereisaaron** [comment]
With cluster-autoscaler 1.0.2 I can get regular ASGs to scale to zero, however I can't get spot price ASGs to scale to zero, even when the min-size is set to zero. Anyone else achieved zero for spot price ASGs?

**Comment by Rishka** [comment]
It worked with 0.6.1 when I originally tested it, not sure if 1.0.* still does

**Comment by wskinner** [comment]
Has anything changed in the last 3 months? I am looking at running cluster using AWS spot instances, and the ability to scale all the way to zero is important. Based on this thread, it looks like 1.8.0 is the latest version that scaling to zero for spot ASGs works with.

**Comment by whereisaaron** [comment]
I have been able to scale down to zero with spot-price ASGs. In some cases it was working, but you have to be patient because there is a limit to how fast ASGs will change and to how fast the auto-scaler will act. You need `"autoscaling:DescribeLaunchConfigurations"` in order to scale back up from zero.

**Comment by cristim** [comment]
@Globegitter as the author of AutoSpotting I've heard of people successfully running it with kops, you just need to tag your groups to what it expects or configure it to use some tags you already have.

Please let me know if you run into any issues with it.

**Comment by bhack** [comment]
I think that also a spot rescheduler is generally useful. Check introduction and motivation sections in https://github.com/pusher/k8s-spot-rescheduler/
