### ISSUE TITLE
Documentation: 3 or more Masters into Regions with only 2 AZ

### ISSUE THREAD

**Issue by nilocbb** [kubernetes/kops#3389]
Heres my problem:
I only have a Region with **2 AZ**. When I created a cluster with **3 masters** split into **2 AZ** I ran into connection lost every now and then.

`kubectl get nodes` sometimes gets the nodes sometimes not.

I used it in a **Private** subnet.

I resolve this using **3 masters** in only one AZ and nodes split between the other two.

Maybe we should Doc this to alert when creating a cluster (best practice).

**Comment by jatan28** [comment]
I can work on this, also would it make sense to support having 3 masters balanced across 2 AZs in the regions that has only 2AZs.

**Comment by slongstreet** [comment]
I would categorize this is a "known issue", not a best practice.  Putting all 3 masters in a single AZ means it isn't highly available -- this is just a workaround until kops supports specifying only two AZs for the master zones.

**Comment by chrislovecnm** [comment]
Related: https://github.com/kubernetes/kops/issues/3503

**Comment by chrislovecnm** [comment]
We just want to make sure that we have (N-1)/2 spread across two AZ to have HA.  Creating an instancegroup type for just etcd, may be best, but I am open to other options.
