### ISSUE TITLE
Cluster Autoscaling support on AWS

### ISSUE THREAD

**Issue by apobbati** [kubernetes/kops#341]
Are there any plans to support cluster autoscaling on AWS ?

Apparently, this support is coming [soon](http://blog.kubernetes.io/2016/07/autoscaling-in-kubernetes.html) to Kubernetes.

**Comment by yissachar** [comment]
Here's the main Kubernetes issue for this: https://github.com/kubernetes/kubernetes/issues/11935

**Comment by apobbati** [comment]
Thanks!

**Comment by justinsb** [comment]
Reopening to track this as something we should document / add support for!

**Comment by andrewsykim** [comment]
I was involved in the current AWS implementation of the cluster autoscaler, the umbrella issue is https://github.com/kubernetes/contrib/issues/1311. This sounds like something I'd be interested in doing unless there's someone that has been working on it already.

**Comment by tazjin** [comment]
It seems like this has been implemented in the autoscaler already.

Is it sensible for kops to add the autoscaler as an addon or should it simply be documented here what the steps are to get it up and running?

**Comment by craigwillis85** [comment]
I'd be interested in how to set this up as well

**Comment by chrislovecnm** [comment]
@tazjin I would like to leave kops as vanilla as we can.  Provide instructions on how to use addons, but let's keep it focussed on the install.  Now if something needs to occur, during the install, to get something to work, and it is something that has valid use cases and need, then I am all for modifying kops.

**Comment by LEW21** [comment]
[Cluster-autoscaler addon](https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler) currently works, except that there is a bug in the deployment template - https://github.com/kubernetes/kops/blob/master/addons/cluster-autoscaler/v1.4.0.yaml

```
image:
name: {{IMAGE}}
```

should be:

```
image: {{IMAGE}}
name: autoscaler
```

(I would send a pull request, but I'm waiting for my company to sign CLA)

And you need to give workers IAM permissions: https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler/cloudprovider/aws#permissions

There's a problem with that last thing - I don't think it's doable with kops, and kops will override the manually-modified roles on each ```kops update cluster --yes```.

**Comment by andrewsykim** [comment]
@LEW21 did you the favour and opened a PR for the bug in the deployment template https://github.com/kubernetes/kops/pull/1167 :)

**Comment by yissachar** [comment]
You can track https://github.com/kubernetes/kops/pull/1170 for IAM permissions, which should allow you add the autoscaling permissions to your nodes through kops.

**Comment by chrislovecnm** [comment]
Can someone update this with any actionable needs?

**Comment by yissachar** [comment]
@chrislovecnm This should be close-able. In 1.5 we have an [autoscaler addon](https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler) that can be installed, and the IAM permissions on the master are already setup by kops.

We also have a [different issue](https://github.com/kubernetes/kops/issues/1771) that discusses installing the addon by default. 

So I think this can be safely closed.

**Comment by chrislovecnm** [comment]
closing, please re-open if we need to
