### ISSUE TITLE
API Container on AWS Stack never starts up successfully

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kops#3413]
Following the guide here:

https://kubernetes.io/docs/getting-started-guides/kops/

And using the following kops call (with ```kops version``` => 1.7.0):

```
kops create cluster --cloud aws --name cluster.k8stest.blenderfox.uk \
--state s3://k8sstate --node-count 3 --zones eu-west-2a,eu-west-2b \
--node-size m4.large --master-size m4.large \
--master-zones eu-west-2a \
--ssh-public-key ~/.ssh/id_rsa.pub 
```

Creates a cluster (```kops update``` was successful) , but the master node can't hold the api server container open. The container exits after a few minutes with the following:

> I0918 11:27:50.338655       5 aws.go:806] Building AWS cloudprovider
> I0918 11:27:50.338703       5 aws.go:769] Zone not specified in configuration file; querying AWS metadata service
> I0918 11:27:50.476460       5 tags.go:76] AWS cloud filtering on ClusterID: cluster.k8stest.blenderfox.uk
> I0918 11:27:50.479283       5 server.go:617] Initializing deserialization cache size based on 0MB limit
> I0918 11:27:50.479304       5 server.go:636] Initializing cache sizes based on 0MB limit
> W0918 11:27:50.716889       5 storage_codec.go:52] storage type "etcd2" does not support media type "application/vnd.kubernetes.protobuf", using "application/json"
> W0918 11:27:50.716943       5 storage_codec.go:52] storage type "etcd2" does not support media type "application/vnd.kubernetes.protobuf", using "application/json"

**Comment by chrislovecnm** [comment]
how do you have the cluster up? The above logs appear to be normal messages. After a few minutes does the API server start?

**Comment by huang-jy** [comment]
No, the box starts and it starts the containers, but apiserver will start, run for a few minutes, then terminate, then start again, and terminate again, and repeat a couple of times, and then it will give up retrying. As a result, the DNS names for api and api.internal, never get updated off their placeholder IPs. Meaning kubectl won't work.

I left it for an hour to see if it would sort itself out, but I am guessing it won't if the apiserver container isn't running.

**Comment by swapnilsm** [comment]
We are also facing the same issue.

**Comment by huang-jy** [comment]
@swapnilsm no, I never did. :(

**Comment by chrislovecnm** [comment]
@swapnilsm can I get the exact commands and kops version please. Also all logs from a master?

**Comment by huang-jy** [comment]
Here's mine:

https://blenderfox.com/2017/09/18/scribble-tinkering-with-kubernetes-and-aws-wip/

**Comment by swapnilsm** [comment]
@chrislovecnm It started automatically after leaving it for 40-50 minutes.

**Comment by huang-jy** [comment]
@swapnilsm @chrislovecnm hmmm. That's strange. Guess I'll try again on my side and see if it now works. too.

**Comment by huang-jy** [comment]
Yep, confirmed. My DNS was incorrectly setup. Found some "unable to resolve" errors in the etc container logs which led me to a bad configuration. Fixed and the containers came up. 

Closing the ticket.

**Comment by psyhomb** [comment]
@huang-jy could you please share with us what exactly did you fix, what exactly was wrong with configuration?

**Comment by huang-jy** [comment]
@psyhomb at the time I was trying to setup a cluster without actually having a publicly resolvable domain. No wonder the api wouldn't function properly since it couldn't resolve correctly. Fixed that by purchasing a domain through Amazon (something I had been wanting to do for a while) and using that in Route 53. Then it all worked.

**Comment by psyhomb** [comment]
@huang-jy thanks for the quick answer!
