### ISSUE TITLE
etcd image not push to private registry when use containerRegistry

### ISSUE THREAD

**Issue by kineta-Jiang** [kubernetes/kops#3424]
kops 1.7.1-beta.2
kubernetes 1.7.4

 set assets containerRegistry to config, copydockerimage not push gcr.io/google_containers/etcd:2.2.1 to private registry server.  the master daemon.log show it still need gcr.io/google_containers/etcd .

we are in aws china , can not access gcr.io.

`
Container {Name:etcd-container Image:gcr.io/google_containers/etcd:2.2.1 Command:[/bin/sh -c /usr/local/bin/etcd 2>&1 | /bin/
tee /var/log/etcd.log] Args:[] WorkingDir: Ports:[{Name:serverport HostPort:2381 ContainerPort:2381 Protocol:TCP HostIP:} {Name:clientport HostPort:4002 ContainerPort:4002 Protocol:TCP HostIP:}] EnvFrom:[] Env:[{Name:ETCD_NAME Valu
e:etcd-events-a ValueFrom:nil} {Name:ETCD_DATA_DIR Value:/var/etcd/data-events ValueFrom:nil} {Name:ETCD_LISTEN_PEER_URLS Value:http://0.0.0.0:2381 ValueFrom:nil} {Name:ETCD_LISTEN_CLIENT_URLS Value:http://0.0.0.0:4002 ValueFrom:ni
l} {Name:ETCD_ADVERTISE_CLIENT_URLS Value:http://etcd-events-a.internal.test.k8s.local:4002 ValueFrom:nil} {Name:ETCD_INITIAL_ADVERTISE_PEER_URLS Value:http://etcd-events-a.internal.test.k8s.local:2381 ValueFrom:nil} {Name:ETCD_INI
TIAL_CLUSTER_STATE Value:new ValueFrom:nil} {Name:ETCD_INITIAL_CLUSTER_TOKEN Value:etcd-cluster-token-etcd-events ValueFrom:nil} {Name:ETCD_INITIAL_CLUSTER Value:etcd-events-a=http://etcd-events-a.internal.test.k8s.local:2381 Value
From:nil}] Resources:{Limits:map[] Requests:map[cpu:{i:{value:200 scale:-3} d:{Dec:<nil>} s:200m Format:DecimalSI}]} VolumeMounts:[{Name:varetcdata ReadOnly:false MountPath:/var/etcd/data-events SubPath:} {Name:varlogetcd ReadOnly:
false MountPath:/var/log/etcd.log SubPath:}] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:4002,Host:127.0.0.1,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:15,TimeoutSeco
nds:15,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false

`

**Comment by chrislovecnm** [comment]
The container registry and file repository components are still a work in progress. Hopefully in the next few weeks I will have bandwidth. If anyone has bandwidth to assist please reach out!

**Comment by chrislovecnm** [comment]
This should be fixed now. File repository work is almost done

**Comment by chrislovecnm** [comment]
To be clear it is fixed in master and will be in the next 1.8.0 release
