### ISSUE TITLE
Prevent any cross-version schema issues

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#345]
On both IG & Clusters, we probably should do the defaulting as part of an update, now that nothing should change (no external dependencies).  Because otherwise we have trouble with schema changes across code versions.

We could also create a toolbox command to regenerate

**Comment by chrislovecnm** [comment]
Does this help with this ... I am looking through issues to test against #1183

**Comment by chrislovecnm** [comment]
@justinsb is this addressed #1183

**Comment by justinsb** [comment]
Going to close; we have a lot of apimachinery now and this is too broad to be actionable.
