### ISSUE TITLE
Feature Request: Kops Support for issuing shell commands to the controller plane and Instance groups.

### ISSUE THREAD

**Issue by hsyed** [kubernetes/kops#3465]
The ability to issue commands to groups of nodes that are part of a Kops cluster would be a killer feature to have. For cluster management, cluster development and simple general purpose ops utilities. 

If this infrastructure was present in Kops core it could implement a lot of use cases by direct shell interaction with the nodes. In a lot of cases it would sidesteps having to go through a node recreation loop. Kops supported command examples could be

* Restart of control plane k8s services (api-service, scheduler, controller manager).
* Easily Introducing chaos into the cluster for testing -- upstream kubernetes would benefit from this as well. 
* Maintenance tasks for the underlying os (debian, coreos etc).
* Viewing k8s logs (journalctl).

The infrastructure for executing remote commands can be repurposed from the [sup tool](https://github.com/pressly/sup). Here is a [Supfile](https://gist.github.com/hsyed/5156711bf28229882b82b45ecd184231) showing how we use it for our cluster. The Supfile should outline that all the needed abstractions will be available from the Sup repo. Kops would simply need to setup the Sup library with the 1) "network" entries (Instance groups, control plane nodes etc), 2) the commands that may be run and 3) the ssh credentials. 

User supplied commands could be stored in a custom resource in the kube-system namespace. 

I'd be up for working on this !

**Comment by chrislovecnm** [comment]
I like the idea, if you want to start with a MVP Inder toolbox
