### ISSUE TITLE
Secrets not encrypting as part of Kubernetes 1.7 upgrade with kops 1.7

### ISSUE THREAD

**Issue by prateeknayak** [kubernetes/kops#3468]
I was expecting to see encrypted data at rest as per [kubes doco](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/) but to my frustration the upgrade to `kubernetes 1.7` using `kops 1.7` did not give us this feature. Which was one of the main reasons for the upgrade.

I do understand keeping up with `kubernetes` releases is not easy but, can we expect a patch to `kops 1.7` release because we do not want to migrate to `kube 1.8` ? Or at least a upgrade path ?

Link to the PR which solves this:  https://github.com/kubernetes/kops/pull/3368

**Comment by chrislovecnm** [comment]
@prateek-1708 you can use kops 1.8.0.alpha1 with a kubernetes 1.7.x cluster.   We maintain backward compatibility with k8s versions. The release for 1.8.0 is alpha, so I would encourage you to be careful.

**Comment by chrislovecnm** [comment]
Any updates?
