### ISSUE TITLE
Document DNS tweak in Route53 to improve HA cluster creation time

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#347]
Document what TTL changes need to be made in EC2 to improve cluster creation time.

**Comment by yissachar** [comment]
@chrislovecnm @justinsb I think this is not needed anymore due to internal cluster creation time improvements?

**Comment by chrislovecnm** [comment]
Not certain. I think lowering the TTL is important in HA. @justinsb??

**Comment by chrislovecnm** [comment]
Closing
