### ISSUE TITLE
vSphere cloud - DNS Image error 

### ISSUE THREAD

**Issue by SergeySevruk** [kubernetes/kops#3489]
OVA (uploaded 04/18/2017)
https://i.gyazo.com/4e857ceaaa2697f0d2fac98a8a052251.png

**Comment by chrislovecnm** [comment]
@luomiao can you offer some advice?

@SergeySevruk is also facing 

Hi who know a password from Core DNS server, default (Username/Password: root/kubernetes) not works  https://github.com/kubernetes/kops/blob/master/docs/vsphere-dev.md
GitHub
kubernetes/kops
Kubernetes Operations (kops) - Production Grade K8s Installation, Upgrades, and Management

**Comment by luomiao** [comment]
Hi @SergeySevruk , sorry we have stopped the development of kops for vsphere for a while so haven't tried it out with latest kops since then. But I just downloaded the OVA and started it, the username/password: root/kubernetes works fine with this OVA image. Can you please double-check? Thanks.
