### ISSUE TITLE
external-dns for kops

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3502]
Owners have discussed this multiple times, but I am not finding an issue for this. I did find the issue in the external-dns project https://github.com/kubernetes-incubator/external-dns/issues/221.

The thought is that we would like to rely on external dns, so that our dns is far more flexible. Add a cloud provider and we could have dns support for it before we even have the provider, for instance. You want you dns in GCE and you cluster in aws, we can do that theoretically.

## Background 

We have two components that manage dns for our system.

1. Protokube manages etcd dns so that we can have ha
2. dns-controller manages control plane API dns for us, and people also use it for services and ingress as well.

## Todo

1. What gaps of support do we have with external dns with protokube? Can we vendor external dns and approach it that way?
2. What gaps do we have with external dns and API? We have dns records for round robin master dns, we have records for loadbalancer, API and bastions.
3. Do we have used cases that dns-controller provides that are not met by external-dns
4. How do we do upgrades and rollbacks?
5. How do we test?
6. What API changes should we make in kops to support dns in aws, but a cluster in GCE? Very real world use case.

**Comment by chrislovecnm** [comment]
@gambol99 @blakebarnett @sethpollack @geojaz @robinpercy @justinsb  et al

What am I missing here?

**Comment by blakebarnett** [comment]
Seems like it would make sense to just replace dns-controller with it first, then separately add support to protokube to use it?  Have 
all the feature gaps between this and dns-controller been filled?

**Comment by chrislovecnm** [comment]
@blakebarnett someone needs to build a feature list for both and compare them ;) I do not know which features if any we are missing

**Comment by blakebarnett** [comment]
The issue you linked in here does a pretty good job :)

**Comment by chrislovecnm** [comment]
And https://github.com/kubernetes-incubator/external-dns/blob/master/docs/legacy/kops-dns-controller.md

**Comment by chrislovecnm** [comment]
And https://github.com/kubernetes/kops/blob/master/dns-controller/README.md

**Comment by chrislovecnm** [comment]
And https://github.com/kubernetes/kops/blob/master/protokube/README.md has a section about dns and protokube

**Comment by chrislovecnm** [comment]
There are still a couple of comments on the linked issue that need to be resolved / documented. 

> support kops' internal/external annotations, find out what they do first

**Comment by sethpollack** [comment]
- multiple targets
- internal alias records (for nodes)
- node source
- pod source
- internal/external annotations
- dns-contoller backwards compatibility for service, ingress, node, pod sources.
- record caching so we don't get rate-limited

**Comment by sethpollack** [comment]
I have an open PR for multiple targets https://github.com/kubernetes-incubator/external-dns/pull/326

And I already have the code for alias records, node source, pod source, and dns-contoller backwards compatibility, they just depend on each other so I need to open the PR's one at a time.

**Comment by sethpollack** [comment]
As for internal/external annotations @justinsb do we need that support? Or can that be limited to the backwards compatibility?

**Comment by sethpollack** [comment]
Also caching would be nice, but not sure if thats a blocker.

**Comment by linki** [comment]
@sethpollack Kops compatibility is the main part of our next milestone. Sorry for the delay in reviewing the PR. We will look at at whenever there's time.

**Comment by hoshsadiq** [comment]
So does this mean this won't get done?

**Comment by chrislovecnm** [comment]
The bot stuff?

**Comment by rlees85** [comment]
If Kops moves to external-dns for internal stuff too (I think that would be great) but in my opinion there would need to be a way to support split horizon. Currently this is done by running two instances of external-dns on a cluster. Using `--annotation-filter` (I think?) you can have the public external-dns only add public records for a service that should be public and a catch-all external-dns that is limited to private zones.

I think this could be implemented by external-dns that comes with Kops in the future following the `dns: private` directive (where private could be private, public and maybe auto (equivalent to no `--aws-zone-type` flag in external-dns)

Then a further external-dns instance can be started manually outside of Kops for public / other zones.

Most of this is thinking out loud but may be worth adding to the to do. Just putting external-dns on a Kops cluster that picks up ALL hostnames by default and puts them in an auto-detected zone will break a lot of peoples setups.
