### ISSUE TITLE
Support for having multiple master distribute across AZs in regions with 2AZs

### ISSUE THREAD

**Issue by jatan28** [kubernetes/kops#3503]
Currently, when I try to deploy a cluster using kops in a AWS region with 2 Availability Zones, it will not be created when there are 2 regions in the `--master-zones` argument. A current workaround is to create all 3 masters in one zone, which actually defeats the purpose of HA. It would be nice to have support for 3 masters balanced across the 2 AZs.

**Comment by chrislovecnm** [comment]
@jatan28 you can get into some nasty split brain issues when you lose two masters in one AZ.  That is why at this point we do not support running 2 AZ.  You would need to run (N-1)/2 spread across two AZ to have HA.  Externalizing etcd, which can cause latency issues, or have multiple etcd servers on the same node the may be some other options.  Externalizing etcd is an option, but you can run into performance latency issues very quickly depend on cloud network bandwidth, and at this point, kops does not support external etcd nodes.

For two AZ's you may want to consider 2 k8s clusters.  Also, do you need 5/9's on the control plane?  What is the need that is driving an HA control plane?

We are always happy to have contributions!

**Comment by jatan28** [comment]
So currently, In production we are using etcd on a separate instancegroup dedicated just for etcd for performance reasons. We are trying to adopt kops for cluster deployment and that is one of the features we are looking for.  There is already an open issue for that, and I would be more than happy to contribute to that issue. We have tested outage of 2 masters and haven't seen an issue since the masters run in an Autoscaling Group across the AZs so when one AZ is down it will recreate the masters in the other one and when it comes back it will rebalance it. So we still get HA control plane with this setup, mainly by moving etcd to a dedicated isntancegroup

**Comment by chrislovecnm** [comment]
@jatan28 we should have an issue open for dedicated etcd instance support, and I am interested in data that you are having better performance with etcd offloaded to another instance!

Please let me know what information you need, and reach out on slack if you have questions.
