### ISSUE TITLE
Can I choose the Hosted Zone ID in a service using the route53-mapper?

### ISSUE THREAD

**Issue by carlosmkb** [kubernetes/kops#3515]
In my case I have two hosted zone with the same domain name (privates in different VPCs).
When I create a service in a private K8s cluster in a certain VPC, the route53-mapper is trying to create the DNS record in the Hosted Zone of the another VPC (because the domain names are equal).

**Comment by chrislovecnm** [comment]
route53-mapper or kops? If it is route53-mapper I would recommend openning an issue with them :)

**Comment by chrislovecnm** [comment]
Closing
