### ISSUE TITLE
Using --target makes update behave as if --yes was provided in some ways

### ISSUE THREAD

**Issue by jaygorrell** [kubernetes/kops#352]
When using `--target terraform`, the output of update acts like --yes was provided in two ways that are a little confusing:
- The ~/.kube/config file gets written, which sorta' makes sense because you won't have a chance to get it later. Due to this, maybe it should get written without --yes at all times, instead of only with Terraform?
- The output indicates that the cluster is starting up and should be ready in a few minutes. This threw me off and had me checking AWS for resources.

**Comment by shamil** [comment]
> The ~/.kube/config file gets written, which sorta' makes sense because you won't have a chance to get it later. Due to this, maybe it should get written without --yes at all times, instead of only with Terraform?

You can always export the config, by running  `kops export kubecfg --state <s3-state-store-path> --name <cluster-name>`.

In my opinion `kops cluster update` should not rewrite `~/.kube/config` **at all**. Or at least, should not change the default context. The user might use different context by default when operating multiple clusters, and having `kops cluster update` replace the context can lead to unexpected results IMHO.

My suggestion is to make it optional, so let the user decide if he wants to export the kubecfg at all and if yes, let him decide if he wants to change default context when `kops` exporting the config

Also we should let user decide if he wants the config to have internal or public Kubernetes API server url. In my case I use internal URL...
