### ISSUE TITLE
Separate CLI implementation from interface

### ISSUE THREAD

**Issue by kchugalinskiy** [kubernetes/kops#3521]
At the moment implementation of CLI is tied to arguments validation. In other words there is almost no chance to invoke kops command to create cluster programmatically.
At this moment I'm working on provider for terraform which will allow to create k8s cluster using kops in declarative way (https://www.terraform.io/docs/plugins/basics.html). And this problem with interface blocks me to be precise. Moreover I see no practical sense to remain things as they are.
My proposal is to create subdirectory /impl inside of /cmd/kops directory and move all interface-independent stuff over there. I can do this by my own in a few days.

**Comment by chrislovecnm** [comment]
Some of this work may be needed for our kops server as well. Can you give us some more details of what you are doing? @justinsb any ideas on how we need some refactoring in cmd with our inbound kops server work?

**Comment by kchugalinskiy** [comment]
I would like to help you with this job. Not quite sure how it should look like but definitely all functions related to declaration of commands using cobra should stay on their places. All remaining code should be used to some modules. Not sure if this is one module, I'm still investigating it. As a result I want anyone to be able to invoke kops commands without using application CLI, but by invocation of underlying functions instead.

**Comment by chrislovecnm** [comment]
@kchugalinskiy if you are able to make developer office hours, it may be a good venue to discuss this.

**Comment by chrislovecnm** [comment]
@kchugalinskiy bump :)
