### ISSUE TITLE
Support state storage in a different AWS account from the cluster

### ISSUE THREAD

**Issue by jaygorrell** [kubernetes/kops#353]
Currently `KOPS_STATE_STORE` and the cluster itself are driven by the `AWS_PROFILE` variable. It would be beneficial if the AWS profile for state storage could be defined separately from the main AWS profile being used for actual cluster creation.

This would allow configurations where environments are separated into their own accounts. @justinsb also mentioned this would be helpful for GCE implementation as well.

The same could be said for which AWS profile to use for DNS storage, but that's more of a sidenode. Not really in scope for this issue.

**Comment by maplelabs** [comment]
Is this supported in recent release or still it is open issue.

**Comment by tazjin** [comment]
There is currently support for using S3 buckets that have cross-account permissions set up, as per https://github.com/kubernetes/kops/pull/1247

In that case you would grant the account in which your infrastructure lives permissions to write to the S3 bucket containing the `kops`-state (you can restrict this to the keys/folders that are relevant for your cluster) using a bucket policy.

Does that work for your use-case?

**Comment by maplelabs** [comment]
My use case is I want to use the Kops with account related details in .aws/file in a one session. It is using this details and deploy the things. Now open up another session with a different aws account details and deploy a another set. 

Now if I understand the things Kops should be able to support both the deployments in 2 different sessions

Is this right ?

**Comment by kenden** [comment]
Related https://github.com/kubernetes/kops/issues/435

**Comment by chrislovecnm** [comment]
For aws this is now supported. Can we close?

**Comment by tazjin** [comment]
@maplelabs The current implementation uses cross-account bucket policies rather than two different sessions. You'll have to do that anyways as the nodes require access to the bucket when they come up.

@chrislovecnm I think it can be closed, but we should document that nodes require this bucket access.

**Comment by jaygorrell** [comment]
Is the solution documented? I'd say that should drive if this can be closed or not

**Comment by tazjin** [comment]
@jaygorrell there's a part that mentions the ACL setup: https://github.com/kubernetes/kops/blob/master/docs/aws.md#sharing-an-s3-bucket-across-multiple-accounts

It's sort of implicit that cross-account policies will work, maybe that should be explicitly added to that section.

**Comment by jaygorrell** [comment]
Nope, that's perfect - missed that in the docs. As the author of this issue, I'm cool with it being closed!

**Comment by tazjin** [comment]
@jaygorrell I've added some more docs in:  https://github.com/kubernetes/kops/pull/2462/files

If the previous docs didn't make this obvious enough I think it's good to expand on the section a bit.

@chrislovecnm Got time to check that out? :)

**Comment by chrislovecnm** [comment]
Closing this per the above comments

**Comment by StratusChris** [comment]
After much research/testing, it looks like the ability to use separate credentials for S3 was actually merged in later for an unrelated reason. Tested and it appears to be working.

Original request for other feature: #2368

Actual PR code committed: #2389

Syntax:
```
export S3_ENDPOINT=https://s3.us-east-1.amazonaws.com
export S3_ACCESS_KEY_ID= [access_key_id]
export S3_SECRET_ACCESS_KEY=[secret_access_key]
```

Endpoints for other regions can be found here: https://docs.aws.amazon.com/general/latest/gr/rande.html
