### ISSUE TITLE
Bug: Cannot update cluster: error running tasks: deadline exceeded executing task Subnet/us-east-1a.#####.org. Example error: Subnet.CIDR: Invalid value: "172.17.32.0/19": field is immutable: old="172.17.3.0/24" new="172.17.32.0/19"

### ISSUE THREAD

**Issue by AnthonyWC** [kubernetes/kops#3535]
I am trying to update a new cluster that erred out during creation due to subnet conflict, in trying to update the subnet definition I ran into this error (using kops update cluster --state s3://##-### --name #####.org --yes)

```
error running tasks: deadline exceeded executing task Subnet/us-east-1a.#####.org. 
Example error: Subnet.CIDR: Invalid value: "172.17.32.0/19": field is immutable: old="172.17.3.0/24" new="172.17.32.0/19"
```
Seem similar to error encountered here: https://github.com/kubernetes/kops/issues/2470 as I am also using calico.

**Comment by chrislovecnm** [comment]
At this point we do not support changing subnet CIDR addresses.  You can always add a new CIDR, but once the create is done, you cannot update it.  This is not a bug, but would be a new feature.

**Comment by AnthonyWC** [comment]
So with this issue (https://github.com/kubernetes/kops/issues/2294 ) and this lack of feature means you have to tear down initial cluster deployment if the issue chose an subnet that overlap with existing subnet?

**Comment by chrislovecnm** [comment]
@justinsb any ideas?
