### ISSUE TITLE
Network Connection Lost / Weave / KubeDNS issues in 1.7

### ISSUE THREAD

**Issue by genexp** [kubernetes/kops#3537]
I'm writing this ticket (and closing it) for the benefit of anyone else that had a similar problem.  We deployed KOPS in AWS using a private configuration with the following:

```
kops create cluster --dns-zone=${CLUSTER_NAME} --vpc ${VPC_NAME} --networking weave --node-count 2 --zones us-east-1a,us-east-1b,us-east-1c --dns public --node-size c4.large --master-size m4.large --master-zones us-east-1a,us-east-1b,us-east-1c --topology private --bastion ${CLUSTER_NAME}
```
We had a ton of reliability issues after a week of killing and restarting worker nodes.  We ended up determining the problem was weave, swapped to flannel, and everything has been wonderful and stable.

**Comment by ashic** [comment]
THANK YOU!!

I recall having issues with weave going from 1.5 to 1.6, and 1.6->1.7 broke my cluster. Switching to flannel seems to be working.
