### ISSUE TITLE
kops validate output yaml and json

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3539]
Would be awseom if `kops validate` would output yaml and json.  I will update the issue with a couple ideas on the format.

**Comment by jatan28** [comment]
@chrislovecnm Are you thinking about something like `kops validate cluster -o yaml`, similar to the `kubernetes get pod -o yaml`?

**Comment by chrislovecnm** [comment]
@jatan28 exactly :)  We would need an output format, but you get the idea.  Would be helpful for programmatically using validate.

**Comment by jatan28** [comment]
@chrislovecnm  Do you have a design in mind for the output format? I saw that it is using print statements, is there an object that we can leverage for the structure of the output json/yaml. Once we finalize the design and approach, I can start working on it.

**Comment by chrislovecnm** [comment]
I don't, come up with something and let's iterate

**Comment by jatan28** [comment]
What if we create a class for all the data that is getting rendered by this option, and then output it in yaml similar to `kops edit cluster` and json is fairly straightforward.

**Comment by dimitrovvlado** [comment]
I'm not sure if it would make sense, but what if `kops get cluster` includes a status field, similar to `kubectl get pods`?
