### ISSUE TITLE
Add support for 1.4 rescheduler

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#355]
Equivalent of https://github.com/kubernetes/kubernetes/pull/30870

**Comment by chrislovecnm** [comment]
Do we just need https://github.com/kubernetes/kubernetes/pull/30870/commits/1f3fdab063b2bd2972dd8b46a96af8143dcd70c6#diff-d7124bd92602ad47b1c6e15a91c60e81? I can knock this out.

**Comment by BradErz** [comment]
Any newws on this one?
