### ISSUE TITLE
s3 bucket accidentally deleted? How do i re-generate it?

### ISSUE THREAD

**Issue by tuananh** [kubernetes/kops#3574]
s3 bucket accidentally deleted? How do i re-generate it?

**Comment by chrislovecnm** [comment]
Did you have versioning on in the s3 bucket?  You may be able to import the cluster, but I have not attempted that.

**Comment by tuananh** [comment]
Unfortunately i do not. Can you show me the instruction?

**Comment by chrislovecnm** [comment]
If it is not versioned, I am not certain we have a solution for you :( 

@justinsb any ideas?

**Comment by tuananh** [comment]
ended up re-creating the cluster and migrate over.

**Comment by tuananh** [comment]
@chrislovecnm sorry to bother you again. since the bucket is deleted, i have to manually clean up the cluster. Can you take a look to see if I'm missing anything here.

Very much appreciated.

[] remove nodes, master ASG
[] remove VPC
[] remove IAM roles
[] remove elastic load balancers

**Comment by chrislovecnm** [comment]
Launchconfigs just go and remove the vpc in aws UI. It will clean house

**Comment by chrislovecnm** [comment]
Tags as well ;) if you choose a new cluster name

**Comment by tuananh** [comment]
Many thanks.
