### ISSUE TITLE
SSL/TLS generation for API

### ISSUE THREAD

**Issue by kilpatty** [kubernetes/kops#36]
As mentioned in the Slack Channel, due to the fact that Kops encourages you to build a DNS name for your server, some sort of certificate management and generation should be included. Let's Encrypt would be a great option to allow free certificates to any domain that is used. 

Let me know if there is any way for me to help work on this.

**Comment by justinsb** [comment]
This would be great.  I am hoping we can try exposing the API server externally over ingress, and we can then use kube-lego etc.

**Comment by pluttrell** [comment]
+1

**Comment by kris-nova** [comment]
+1 (especially for LE)

**Comment by chrislovecnm** [comment]
Is this a duplicate?  We have issues open for bring your own certs.  I like LE idea, but also do not want to make that the only option

**Comment by pluttrell** [comment]
I think bringing your own certs and supporting [Let's Encrypt](https://letsencrypt.org/) are two different use cases and have very different implementation requirements.

Bringing your own certs should be basically a matter of supplying the files and setting them up on the ELB (in AWS anyway) or within the `api-server` itself. [Not to spur a tangent, but my opinion is that the ELB is the way to go, however manually adding the api servers IPs to Route53 appears to be the current default].

Whereas Let's Encrypt support means utilizing the approach for manually supplying the certs and also needs the following: 1) triggering the cert creation, 2) supporting the process whereby the certs are generated and 3) automating cert renewal given that Let's Encrypt certs appear to only last 90 days as to [favor automated renewal](https://community.letsencrypt.org/t/pros-and-cons-of-90-day-certificate-lifetimes/4621).

**Comment by joejuzl** [comment]
+1

**Comment by chrislovecnm** [comment]
This is a duplicate. There is a ticket open for bring your own certs. So letsencrypt lasts for 90dsys?

**Comment by steinnes** [comment]
I'd be very interested in helping out with adding this feature.

I'm using ACM-generated certs now which I use with ELB's in front of my k8s masters, which is great but I have issues with running `kubectl exec`: `Error from server (BadRequest): Upgrade request required`.  I haven't debugged this extensively but I suspect the ELB is removing/modifying HTTP headers.

Some people in the ranger project had a similar issue which they solved using some rather obscure (to me) ProxyProtocolPolicy configuration, which I attempted but did not seem to work for me.

**Comment by olemarkus** [comment]
Given the various use cases we have for certs (API, signing tokens etc) I don't see this happening. We do support ACM for the API though. 
/remove-lifecycle frozen
