### ISSUE TITLE
Kops 1.7.1 breaks DNS (For 1/2 of all requests) when using Kubernetes 1.7.8

### ISSUE THREAD

**Issue by tavisma** [kubernetes/kops#3600]
-------------BUG REPORT --------------------
1. Fill in as much of the template below as you can. 

2. What kops version are you running? use `kops version`
$ kops version
Version 1.7.1 (git-c69b811)

3. What Kubernetes version are you running? use `kubectl version`
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:54:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:35:40Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

4. What cloud provider are you using?
Amazon

5. What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?
- Upgrade to Kops 1.7.1
- kops update cluster ${NAME} --target=terraform --out=. --yes
- terraform plan
- terraform apply
- kops rolling-update cluster $NAME --yes

6. What you expected to happen:
DNS security patch applied and working dns!

7. How can we to reproduce it (as minimally and precisely as possible):
Hoping there will be some others who have encountered this, for the time being i immediately downgraded my cluster using kops 1.7.0 and the problem was resolved.
If it isn't obvious what happened, i can follow-up with a fresh cluster to exhibit this problem

8. Anything else do we need to know:
You guys/gals are awesome, dont stop being you.

**Comment by chrislovecnm** [comment]
You do not need to roll the cluster ;) The update occurs when the new addon is moved into s3. So the problem I am guessing is with something else.  And rolling update should have not bumped the version. It should have replaced all the nodes.

How many nodes? What happened with the nodes? 

Also did you used the drain and validate feature flag?
