### ISSUE TITLE
Deploy Kubernetes on AWS Reserved instances

### ISSUE THREAD

**Issue by yngwuoso** [kubernetes/kops#3601]
I'm very new to KOPS, so I have very questions about the cluster deployment process in AWS.

Supose I have 3 reserved instances: I want to deploy one Master and two workers in my existing AWS reserved instances.

Can anyone write a step by step guide to acomplsih that?

Thanks.

**Comment by mikesplain** [comment]
Hi @yngwuoso, you shouldn't need to do anything special for reserved instances.  Simply follow a guide, but set your master and node size to your reserved instance sizes.  

https://github.com/kubernetes/kops/blob/master/docs/aws.md

Add these flags to `kops create cluster`

`--master-size m3.medium`
`--node-size m3.large`

**Comment by yngwuoso** [comment]
Hi Mike. Doesn't Kops create on demand instances in the deployment process? I say that, because when I purchase reserved instances, they are present at the "Reserved Instances" section at AWS Console. I thougth that, I have to configure that particular instances somewhere in the configuration files in Kops to use them (avoiding the creation of other instances).

**Comment by yngwuoso** [comment]
Ok, reserved instances are a "billing contract", not a virtual machine... So, you are right.

Thanks for the information.

**Comment by yngwuoso** [comment]
.

**Comment by andreppires** [comment]
Hey Guys! Sorry to bring this issue back but I have a question about this topic.

As I understood from the comments here, there is no such thing as a reserved instance in practice. As @Yngwuoso said previously, _reserved instances are a billing contract, not a virtual machine_.

My question is: supposing I already have a cluster running, if I buy a reserved instance, with the same size as one of the nodes on my cluster, that node will be priced the reserved instances from that moment? If not, then I can destroy that node and kops will bring a new instance, this one as a "reserved instance"?

**Comment by andreppires** [comment]
Nevermind. I already got the answer. 

Basically reserved instances are as a promotional code for your billing. You don't need to do anything more than buying the reserved instances in the proper zone and with the proper size.
