### ISSUE TITLE
Want to add flag to kube-controller-manager

### ISSUE THREAD

**Issue by ryuheechul** [kubernetes/kops#3602]
-------------FEATURE REQUEST --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

> 1) According to [here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/), I need to set additional flag `--horizontal-pod-autoscaler-sync-period` to **kube-controller-manager**
> 2) According to [here](https://github.com/kubernetes/kops/blob/master/docs/boot-sequence.md), **Kops** brings up stuff including **kube-controller-manger**
> 3) But unlike **kube-api-server**, it is not possible to set the flag since **kube-controller-manager** is not listed on the [spec](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md)

2. Feel free to submit an issue documentating a design supporting your feature request.
> It would be awesome to have **kube-controller-manager** onto spec so **Kops** users can set flags to **kube-controller-manager**

**Comment by chrislovecnm** [comment]
So this API definition has the flags that. And be tweaked for k-c-m
https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go

I am not seeing the flag you want, but it is a super easy thing to add.

**Comment by georgebuckerfield** [comment]
Looks like this has been added in https://github.com/kubernetes/kops/pull/3673.

**Comment by ryuheechul** [comment]
@georgebuckerfield I think so too!
Thanks everyone for the works!
