### ISSUE TITLE
Route53 Private hosted zone issue

### ISSUE THREAD

**Issue by binoopnanu** [kubernetes/kops#3603]
I'm setting up a new cluster in aws using kops/private hosted zone within a VPC. Cluster creation has been successful however the validation fails with below errors and I waited for a long time thinking it could be an issue with DNS.. Any thoughts ? Just fyi we'd recently setup a cluster using kops exactly the same way without these issues. 

VPC CIDR 10.0.0.0/16

[root@ip-10-0-0-45 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp: lookup api.sandbox.kubernetes on 10.0.0.2:53: no such host
[root@ip-10-0-0-45 ~]#
[root@ip-10-0-0-45 ~]#
[root@ip-10-0-0-45 ~]# kops validate cluster
Using cluster from kubectl context: sandbox.kubernetes

Validating cluster sandbox.kubernetes

cannot get nodes for "sandbox.kubernetes": Get https://api.sandbox.kubernetes/api/v1/nodes: dial tcp: lookup api.sandbox.kubernetes on 10.0.0.2:53: no such host
[root@ip-10-0-0-45 ~]#
 

Thanks for submitting an issue! 

-------------BUG REPORT --------------------
1. Fill in as much of the template below as you can. 

2. What kops version are you running? use `kops version`

3. What Kubernetes version are you running? use `kubectl version`

4. What cloud provider are you using?

5. What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?

6. What you expected to happen:

7. How can we to reproduce it (as minimally and precisely as possible):

8. Anything else do we need to know:

-------------FEATURE REQUEST --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to submit an issue documentating a design supporting your feature request.

**Comment by Sanjanare** [comment]
@binoopnanu is this issue resolved? if so can you please let me know the solution
