### ISSUE TITLE
Old Launch Configs not deleted

### ISSUE THREAD

**Issue by richarvey** [kubernetes/kops#3604]
-------------BUG REPORT --------------------
### Versions
kops version: 1.7.0
kubectl version: 1.7.7
cloud provider: aws

### Behaviour/Issue:
When editing InstanceGroups a new launch configuration is created and attached to the ASG. However old instance groups are not deleted leaving a lot of configuration dormant.

### Replicate Command:

```
kops edit ig master....
```

### Expected Behaviour
kops should delete old configs after a rolling-update, it would be nice to have the option to keep XX of old configs before clean up.

**Comment by prperrino** [comment]
Still occuring...

kops 1.8.1
kubectl 1.9.3
AWS

**Comment by pho-enix** [comment]
Still occuring ...

kops 1.9.0
kubectl 1.11.0
AWS

**Comment by rifelpet** [comment]
This has been fixed in Kops 1.10
/close
