### ISSUE TITLE
error reading channel

### ISSUE THREAD

**Issue by cohadar** [kubernetes/kops#3607]
Thanks for submitting an issue! 

-------------BUG REPORT --------------------
1. Fill in as much of the template below as you can. 

2. What kops version are you running? use `kops version`
Version 1.8.0-alpha.1 (git-991cd8c)

3. What Kubernetes version are you running? use `kubectl version`
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a"

4. What cloud provider are you using?
AWS   (eu-central-1)

5. What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?
kops create cluster \
    --name="$NAME" \
    --state="$STATE" \
    --ssh-public-key="~/.ssh/$NAME.pub" \
    --zones="$ZONES" \
    --node-size="$NODE_SIZE" \
    --node-count="$NODE_COUNT" \
    --master-size="$MASTER_SIZE" \
    --master-count="$MASTER_COUNT" \
    --dns-zone="$DNS_ZONE"

6. What you expected to happen:
cluster files to be created

7. How can we to reproduce it (as minimally and precisely as possible):
just run kops create with any params

8. Anything else do we need to know:
The exact error output was:
error reading channel "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable": error fetching "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable": Get https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable: dial tcp: i/o timeout

**Comment by chrislovecnm** [comment]
So the error means the cluster could not talk to github. Any updates?

**Comment by cohadar** [comment]
I think the problem is the alpha kops (1.8.0) is using the "stable list" 
https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable

but 1.8.0 is not listed there

**Comment by chrislovecnm** [comment]
Need more details, which binary was throwing the error, and debug logs that you can provide.

**Comment by cohadar** [comment]
I think the problem is neither of these files is specifying images for kubernetes >= 1.8.0
https://github.com/kubernetes/kops/blob/master/channels/alpha
https://github.com/kubernetes/kops/blob/master/channels/stable

**Comment by cohadar** [comment]
It is stuck in file: **util/pkg/vfs/context.go**
kops -v 4 upgrade cluster
Using cluster from kubectl context: foo.bar.link

I1218 14:44:09.647864   20969 s3context.go:163] Found bucket "111122223333.eu-central-1" in region "eu-central-1"
I1218 14:44:09.648166   20969 s3fs.go:176] Reading file "s3://111122223333.eu-central-1/kops/foo.bar.link/config"
I1218 14:44:09.965902   20969 s3fs.go:213] Listing objects in S3 bucket "111122223333.eu-central-1" with prefix "kops/foo.bar.link/instancegroup/"
I1218 14:44:10.042863   20969 s3fs.go:176] Reading file "s3://111122223333.eu-central-1/kops/foo.bar.link/instancegroup/ingress"
I1218 14:44:10.156750   20969 s3fs.go:176] Reading file "s3://111122223333.eu-central-1/kops/foo.bar.link/instancegroup/master-eu-central-1a"
I1218 14:44:10.285064   20969 s3fs.go:176] Reading file "s3://111122223333.eu-central-1/kops/foo.bar.link/instancegroup/nodes"
I1218 14:44:10.361292   20969 channel.go:93] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I1218 14:44:10.361333   20969 channel.go:98] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I1218 14:44:10.361356   20969 context.go:140] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I1218 14:44:40.364089   20969 context.go:208] retrying after error error fetching "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable": Get https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable: dial tcp: i/o timeout
I1218 14:44:40.864501   20969 context.go:140] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable

**Comment by cohadar** [comment]
This timeout is really strange because both my local machine and all k8s cluster machines can curl github with no problems.

**Comment by cohadar** [comment]
I think this is a problem with mac version of kops!
Using docker ubuntu image from same machine kops works fine!

**Comment by chrislovecnm** [comment]
I develop on a Mac, can you change your dns to use google? 8.8.8.8

**Comment by cohadar** [comment]
Ah, it is possible office DNS has bad config, I tried kops update from mac on home network and it works. Thanks Chris, I will close this issue once I verify it was DNS problem.

**Comment by cohadar** [comment]
In the end the bug turned out to be in my office internet.
Specifically our ISP provider had network overload and UDP packets got dropped which prevented some DNS resolutions which prevented some HTTP requests.

Sorry for wasting peoples time with this.

**Comment by iamrandys** [comment]
I was getting the same x509 issue when downloading Kops 1.8.0 from https://github.com/kubernetes/kops/releases/download/1.8.0/kops-darwin-amd64

Version 1.8.0 (git-5099bc5)  <<---- this build shows the git version

**If I did a "brew install kops" the issue was gone.**  When I did a version on kops with this installation it only showed "Version 1.8.0" and didn't have the git sha.

**Comment by chrislovecnm** [comment]
Need more context @iamrandys
