### ISSUE TITLE
KUBE_MANIFESTS_TAR_URL: unbound variable

### ISSUE THREAD

**Issue by nkhine** [kubernetes/kops#361]
I get this when running `curl -sS https://get.k8s.io | MULTIZONE=true KUBERNETES_PROVIDER=aws KUBE_AWS_ZONE=us-west-2a NUM_NODES=3 bash `

```
bernetes.default.svc.cluster.local,DNS:kubernetes-master
./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 518: KUBE_MANIFESTS_TAR_URL: unbound variable
```

**Comment by justinsb** [comment]
That isn't kops (though you should consider using kops instead!)

Can you open an issue on https://github.com/kubernetes/kubernetes instead please?
