### ISSUE TITLE
Stop pods from accessing the state store

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#363]
The pods have access to IAM and to the S3 bucket.  We should implement an IAM proxy or otherwise prevent them reading the secrets!

**Comment by justinsb** [comment]
Hat-tip to @abourget - thank you!

**Comment by chrislovecnm** [comment]
@justinsb what is the status on this?

**Comment by justinsb** [comment]
This will likely be addressed as part of integrating kube2iam (or similar).
