### ISSUE TITLE
K8S node fails during bootstrap

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kops#3631]
During a node bootstrap I receive the following error:
_Oct 15 13:13:36 ip-10-210-225-1 nodeup[1735]: W1015 13:13:36.000299    1735 executor.go:109] error running task "package/python-apt" (8759h44m22s remaining to succeed): error installing package "python-apt": exit status 100: Reading package lists...
Oct 15 13:13:36 ip-10-210-225-1 nodeup[1735]: Building dependency tree...
Oct 15 13:13:36 ip-10-210-225-1 nodeup[1735]: Reading state information...
Oct 15 13:13:36 ip-10-210-225-1 nodeup[1735]: Package python-apt is not available, but is referred to by another package.
Oct 15 13:13:36 ip-10-210-225-1 nodeup[1735]: This may mean that the package is missing, has been obsoleted, or
Oct 15 13:13:36 ip-10-210-225-1 nodeup[1735]: is only available from another source
Oct 15 13:13:36 ip-10-210-225-1 nodeup[1735]: However the following packages replace it:
Oct 15 13:13:36 ip-10-210-225-1 nodeup[1735]:   python3-apt python-apt-common
Oct 15 13:13:36 ip-10-210-225-1 nodeup[1735]: E: Package 'python-apt' has no installation candidate_

executing  `apt-get update` solves the error.
I'm using custom AMI Ubuntu 16.04.1 LTS (kernel version: 4.4.0-57-generic)
Kubernetes and Kops version: 1.6.2

Any idea what is the problem and can we solve it in kops?

**Comment by chrislovecnm** [comment]
So you need to update your image ;)

Need to check if nodeup installs python-apt directly.

**Comment by vendrov** [comment]
@chrislovecnm does kops execute "apt-get update" on bootstrap?

In addition it seems that sometime the installation is complete successfully and sometime it fails with the error above, any idea what can cause this strange sporadic behavior?

**Comment by chrislovecnm** [comment]
apt-get update does not get executed on bootstrap, at least to my knowledge

**Comment by chrislovecnm** [comment]
Can we close this?
