### ISSUE TITLE
Need help to install kops and kubectl on windows 10

### ISSUE THREAD

**Issue by exceed007** [kubernetes/kops#3635]
Hi All,
I am new here, i want to know if i can install kops and kubectl on windows 10. From where  can i get the installations ?

**Comment by chrislovecnm** [comment]
@exceed007 at this point we do not make a kops native windows binary.  I would recommend running from a container.  We have https://github.com/kubernetes/kops/blob/master/docker/Dockerfile-light

As always if you want to take a stab at getting it running, would love the help!

**Comment by chrislovecnm** [comment]
If you want to try out #3770

**Comment by chrislovecnm** [comment]
Closing this please re-open if needed

**Comment by tan-tan-kanarek** [comment]
+@chrislovecnm 

Failed for me:
> c:\opt\kops>make
FIND: Parameter format not correct
Makefile:155: warning: overriding recipe for target 'set'
Makefile:152: warning: ignoring old recipe for target 'set'
FIND: Parameter format not correct
FIND: Parameter format not correct
Makefile:209: warning: overriding recipe for target 'set'
Makefile:155: warning: ignoring old recipe for target 'set'
Makefile:223: warning: overriding recipe for target 'set'
Makefile:209: warning: ignoring old recipe for target 'set'
Makefile:228: warning: overriding recipe for target 'set'
Makefile:223: warning: ignoring old recipe for target 'set'
Makefile:233: warning: overriding recipe for target 'set'
Makefile:228: warning: ignoring old recipe for target 'set'
Makefile:353: warning: overriding recipe for target 'set'
Makefile:233: warning: ignoring old recipe for target 'set'
Makefile:388: warning: overriding recipe for target 'set'
Makefile:353: warning: ignoring old recipe for target 'set'
Makefile:524: warning: overriding recipe for target 'set'
Makefile:388: warning: ignoring old recipe for target 'set'
make: Circular upup/models/bindata.go <- set dependency dropped.
mkdir -p set GOPATH=/src/k8s.io/kops/.build/local
go build  -ldflags "" -o GOPATH=/src/k8s.io/kops/.build/local/go-bindata
k8s.io/kops/vendor/github.com/jteeuwen/go-bindata/go-bindata
can't load package: package k8s.io/kops/vendor/github.com/jteeuwen/go-bindata/go-bindata: cannot find package "k8s.io/kops/vendor/github.com/jteeuwen/go-bindata/go-bindata" in any of:
        C:\Go\src\k8s.io\kops\vendor\github.com\jteeuwen\go-bindata\go-bindata (from $GOROOT)
        ($GOPATH not set)
Makefile:155: recipe for target 'GOPATH=/src/k8s.io/kops/.build/local/go-bindata' failed
make: *** [GOPATH=/src/k8s.io/kops/.build/local/go-bindata] Error 1

Did I miss anything?

**Comment by iamakulov** [comment]
For folks on Windows 10, the easiest option would be to run `kops` in Windows Subsystem for Linux (this doesn’t require installing Docker and running containers): https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by jaskiratr** [comment]
@iamakulov I tried running kops in WSL on Windows 10 machine. Works well up till validation.

```sh
kops validate cluster

unexpected error during validation: error listing nodes: 
Get https://api-myapp-k8s-local-lhmjq5-1231241.us-east-1.elb.amazonaws.com/api/v1/nodes: 
dial tcp: lookup api-myapp-k8s-local-lhmjq5-1231241.us-east-1.elb.amazonaws.com on 10.18.0.1:53:
no such host
```
The status never updates, even after waiting for several more minutes. 
I'm able to ssh into master node from within the Linux bash. So the host should be reachable. Any clue on how to troubleshoot this?

Thank you!

**Comment by CaryJ** [comment]
@jaskiratr how are you setting KOPS_STATE_STORE, and are you in powershell or or cmd?
From powershell I do
`$env:KOPS_STATE_STORE="s3://kops-store"`
in my powershell profile, to set it as an environment variable.

**Comment by jaskiratr** [comment]
@CaryJ  I'm setting it for the session in powershell, like this `$KOPS_STATE_STORE = "s3://k8s-state-storage"`
[Reference](https://github.com/jaskiratr/k8s-sample-deployment/tree/master/k8s-manifests/aws)

**Comment by CaryJ** [comment]
@jaskiratr That sets a powershell variable, but not an environment variable.  Stick the `env:` in there, and it will work.
