### ISSUE TITLE
Expose ETCD_HEARTBEAT_INTERVAL and ETCD_ELECTION_TIMEOUT for etcd

### ISSUE THREAD

**Issue by mschurenko** [kubernetes/kops#3646]
As per the discussion in the office hours zoom meeting on Friday Oct 13th, we would like to be able to configure the following etcd environment variables by way of kops:

ETCD_HEARTBEAT_INTERVAL
ETCD_ELECTION_TIMEOUT

https://coreos.com/etcd/docs/latest/op-guide/configuration.html

I have implemented this by adding the following fields to EtcdClusterSpec:

```
// Leader election timeout
LeaderElectionTimeout string `json:"leaderElectionTimeout,omitempty"`
// Heartbeat interval timeout
HearbeatInterval string `json:"heartbeatInterval,omitempty"`
```

If these fields are set they will be picked up by nodeup and passed into protokube by way of the following cli flags:

```
flags.StringVar(&etcdElectionTimeout, "etcd-election-timeout", etcdElectionTimeout, "time in ms for an election to timeout")
flags.StringVar(&etcdHeartbeatInterval, "etcd-heartbeat-interval", etcdHeartbeatInterval, "time in ms of a heartbeat interval")
```

Since these are optional, the etcd manifest file will only change if you explicitly set LeaderElectionTimeout and HearbeatInterval  by way of ClusterSpec.

**Comment by chrislovecnm** [comment]
man we need an API for damn protokube soon.  

Do we have other durations as string in the API?

Can you start with an API pr and we can rock it from there

**Comment by chrislovecnm** [comment]
Are these specific to etcd2 or is it both etcd2 and 3?

**Comment by mschurenko** [comment]
Unless I'm looking in the wrong place it seem they should work for both v2 and v3 https://github.com/coreos/etcd/blob/release-3.0/Documentation/op-guide/configuration.md

I did my testing with v2.

**Comment by mschurenko** [comment]
I already have implemented this feature in my fork. It's not a tonne of changes. Is it ok to just create a PR with what I'm implemented (including the API change) or would you still prefer to just have the API change first?

**Comment by chrislovecnm** [comment]
@mschurenko we are trying to do APIs by themselves, and then do a PR based on that branch.  A new pattern that we are testing in the repo.  The API values are super important, and naming is tough.  Ping me on slack if you have questions.

**Comment by mschurenko** [comment]
Ok I created https://github.com/kubernetes/kops/pull/3650 and added just the api changes. As far as the type goes, I used string because it needs to be a string when it is used as a value for the environment variables in the PodSpec. But maybe it makes more sense to have it as an int in the api?
