### ISSUE TITLE
kubernetes-dashboard v1.7.0 addon not displaying anything.

### ISSUE THREAD

**Issue by whithajess** [kubernetes/kops#3651]
-------------BUG REPORT --------------------
```ruby
$ kops version
Version 1.8.0-alpha.1 (git-f63a8aacf)
```
```ruby
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider: **AWS**

Reproduce:
```ruby
$ kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.7.0.yaml
```
```ruby
$ kubectl proxy
Starting to serve on 127.0.0.1:8001
```
browse to: http://127.0.0.1:8001/ui/

Takes me to: http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy 

with nothing displayed.

**EDIT - Add Dashboard Logs**
```
$  kubectl --namespace=kube-system log kubernetes-dashboard-2323822625-m8fls
2017/10/17 02:51:26 Starting overwatch
2017/10/17 02:51:26 Using in-cluster config to connect to apiserver
2017/10/17 02:51:26 Using service account token for csrf signing
2017/10/17 02:51:26 No request provided. Skipping authorization
2017/10/17 02:51:26 Successful initial request to the apiserver, version: v1.7.7
2017/10/17 02:51:26 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2017/10/17 02:51:26 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2017/10/17 02:51:26 Initializing secret synchronizer synchronously using secret kubernetes-dashboard-key-holder from namespace kube-system
2017/10/17 02:51:26 Initializing JWE encryption key from synchronized object
2017/10/17 02:51:26 Creating in-cluster Heapster client
2017/10/17 02:51:26 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 02:51:26 Serving insecurely on HTTP port: 9090
2017/10/17 02:51:56 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 02:52:26 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
```

Looks like this was merged recently: https://github.com/kubernetes/kops/pull/3459

@zouyee Any idea if I am missing some additional setup? This is a brand new cluster.

**Comment by whithajess** [comment]
Using the official https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml It does work correctly, I am not aware of the reasoning for Kops having its own addon but I assume there is a good reason?

**Comment by carldanley** [comment]
@whithajess Have you seen the changes for 1.7 dashboard? https://github.com/kubernetes/dashboard#getting-started

You need to access the dashboard via `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/` instead of `http://127.0.0.1:8001/ui`

**Comment by whithajess** [comment]
No I haven't someone did let me know about it when suggesting the official dashboard, maybe this issue is just a documentation thing.

Will update once I have tried the Kops dashboard with the new url, and if it works make a documentation PR.

**Comment by kevinjmh** [comment]
You can access in local machine by running command `kubectl proxy`;
Or you can expose to outside by command `kubectl proxy --address='0.0.0.0'  --accept-hosts='^*$'`
