### ISSUE TITLE
Missing IAM ECR roles in master role after creating new cluster in AWS

### ISSUE THREAD

**Issue by roeera** [kubernetes/kops#3665]
Thanks for submitting an issue! 

-------------BUG REPORT --------------------
1. Fill in as much of the template below as you can. 

2. What kops version are you running? use `kops version`
Version 1.8.0-alpha.1
3. What Kubernetes version are you running? use `kubectl version`
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T17:03:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
4. What cloud provider are you using?
AWS

5. What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?
1. create cluster using the following command :
#!/bin/bash

export KOPS_STATE_STORE=s3://xxxxx
export CLUSTER_NAME=test-k8s.gett.io # Edit with your cluster name
export VPC_ID=vpc-xxxxx # Edit with your VPC id
export NETWORK_CIDR=xxxxxxxx # Edit with the cidr of your VPC

kops create cluster \
  --zones=eu-west-1a,eu-west-1b,eu-west-1c \
  --master-zones=eu-west-1a,eu-west-1b,eu-west-1c \
  --name=${CLUSTER_NAME} \
  --vpc=${VPC_ID} \
  --cloud=aws \
  --cloud-labels "Environment=\"test\",Name=\"${CLUSTER_NAME}\",Role=\"node\",Provisioner=\"kops\"" \
  --ssh-public-key=/Users/roee/.ssh/xxxxxxx.pub \
  --node-count=3 \
  --networking=flannel \
  --node-size=t2.large \
  --master-size=t2.large \
  --dns-zone=gett.io \
  --image=xxxxxxxxx \
  --topology private \

Then edit / replace cluster for existing aws infra with the following :
  subnets:
  - id: subnet-xxxxx
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
    egress: nat-xxxxxx
  - id: subnet-xxxxxxx
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
    egress: nat-xxxxxxx
  - id: subnet-xxxxxxxx
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
    egress: nat-xxxxxxx
  - id: subnet-xxxxxxx
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c

Then running to apply changes :
kops update cluster test-k8s.gett.io --yes 

The following IAM created :
**masters.test-k8s.gett.io:**
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "kopsK8sEC2MasterPermsDescribeResources",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:DescribeRouteTables",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeSubnets",
                "ec2:DescribeVolumes"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "kopsK8sEC2MasterPermsAllResources",
            "Effect": "Allow",
            "Action": [
                "ec2:CreateRoute",
                "ec2:CreateSecurityGroup",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:ModifyInstanceAttribute"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "kopsK8sEC2MasterPermsTaggedResources",
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:DeleteRoute",
                "ec2:DeleteSecurityGroup",
                "ec2:DeleteVolume",
                "ec2:DetachVolume",
                "ec2:RevokeSecurityGroupIngress"
            ],
            "Resource": [
                "*"
            ],
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/KubernetesCluster": "test-k8s.gett.io"
                }
            }
        },
        {
            "Sid": "kopsK8sASMasterPermsAllResources",
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:GetAsgForInstance"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "kopsK8sASMasterPermsTaggedResources",
            "Effect": "Allow",
            "Action": [
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "autoscaling:UpdateAutoScalingGroup"
            ],
            "Resource": [
                "*"
            ],
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/KubernetesCluster": "test-k8s.gett.io"
                }
            }
        },
        {
            "Sid": "kopsK8sELBMasterPermsRestrictive",
            "Effect": "Allow",
            "Action": [
                "elasticloadbalancing:AttachLoadBalancerToSubnets",
                "elasticloadbalancing:ApplySecurityGroupsToLoadBalancer",
                "elasticloadbalancing:CreateLoadBalancer",
                "elasticloadbalancing:CreateLoadBalancerPolicy",
                "elasticloadbalancing:CreateLoadBalancerListeners",
                "elasticloadbalancing:ConfigureHealthCheck",
                "elasticloadbalancing:DeleteLoadBalancer",
                "elasticloadbalancing:DeleteLoadBalancerListeners",
                "elasticloadbalancing:DescribeLoadBalancers",
                "elasticloadbalancing:DescribeLoadBalancerAttributes",
                "elasticloadbalancing:DetachLoadBalancerFromSubnets",
                "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
                "elasticloadbalancing:ModifyLoadBalancerAttributes",
                "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
                "elasticloadbalancing:SetLoadBalancerPoliciesForBackendServer"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "kopsMasterCertIAMPerms",
            "Effect": "Allow",
            "Action": [
                "iam:ListServerCertificates",
                "iam:GetServerCertificate"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "kopsK8sS3GetListBucket",
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::k8s.gett.io"
            ]
        },
        {
            "Sid": "kopsK8sS3MasterBucketFullGet",
            "Effect": "Allow",
            "Action": [
                "s3:Get*"
            ],
            "Resource": "arn:aws:s3:::k8s.gett.io/test-k8s.gett.io/*"
        },
        {
            "Sid": "kopsK8sRoute53Change",
            "Effect": "Allow",
            "Action": [
                "route53:ChangeResourceRecordSets",
                "route53:ListResourceRecordSets",
                "route53:GetHostedZone"
            ],
            "Resource": [
                "arn:aws:route53:::hostedzone/Z35RJUOK1NZB5G"
            ]
        },
        {
            "Sid": "kopsK8sRoute53GetChanges",
            "Effect": "Allow",
            "Action": [
                "route53:GetChange"
            ],
            "Resource": [
                "arn:aws:route53:::change/*"
            ]
        },
        {
            "Sid": "kopsK8sRoute53ListZones",
            "Effect": "Allow",
            "Action": [
                "route53:ListHostedZones"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}

**nodes.test-k8s.gett.io:**
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "kopsK8sEC2NodePerms",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "kopsK8sS3GetListBucket",
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::k8s.gett.io"
            ]
        },
        {
            "Sid": "kopsK8sS3NodeBucketSelectiveGet",
            "Effect": "Allow",
            "Action": [
                "s3:Get*"
            ],
            "Resource": [
                "arn:aws:s3:::k8s.gett.io/test-k8s.gett.io/addons/*",
                "arn:aws:s3:::k8s.gett.io/test-k8s.gett.io/cluster.spec",
                "arn:aws:s3:::k8s.gett.io/test-k8s.gett.io/config",
                "arn:aws:s3:::k8s.gett.io/test-k8s.gett.io/instancegroup/*",
                "arn:aws:s3:::k8s.gett.io/test-k8s.gett.io/pki/issued/*",
                "arn:aws:s3:::k8s.gett.io/test-k8s.gett.io/pki/private/kube-proxy/*",
                "arn:aws:s3:::k8s.gett.io/test-k8s.gett.io/pki/private/kubelet/*",
                "arn:aws:s3:::k8s.gett.io/test-k8s.gett.io/pki/ssh/*",
                "arn:aws:s3:::k8s.gett.io/test-k8s.gett.io/secrets/dockerconfig"
            ]
        }
    ]
}
6. What you expected to happen:
Created IAM rules with ECR permissions.

7. How can we to reproduce it (as minimally and precisely as possible):
Try it yourself

**Comment by chrislovecnm** [comment]
We need a bit more detail please fill out the form ;)

**Comment by roeera** [comment]
Updated bug description

**Comment by roeera** [comment]
@chrislovecnm  See my updates... tx

**Comment by chrislovecnm** [comment]
/assign @KashifSaadat 

Do you mind taking a look?

**Comment by KashifSaadat** [comment]
Hi @roeera, thanks for raising the issue. There was some refactoring work done to the IAM Builder, producing a stricter set of permissions for the Master & Compute nodes. As part of this, we wrapped the ECR permission set around a boolean flag but it was never fully implemented, so the permissions are no longer granted. In the short term you can switch to legacy IAM to get the ECR permissions back, by including the following within your Cluster Spec:
```
  iam:
    legacy: true
```

@chrislovecnm I've raised PR #3690, could you take a look please?

**Comment by roeera** [comment]
@KashifSaadat @chrislovecnm Thanks, this actually solved our problem for now.
Feel free to contact in case you need any further help ;)

**Comment by KashifSaadat** [comment]
Hi @roeera, the above PR (#3690) has been merged into the master branch now. If you're building kops from source, you can continue using the stricter IAM policies and add the ECR permissions on via use of the following IAM Spec:

```yaml
 iam:
    legacy: false
    allowContainerRegistry: true
```

Can we close this issue?

**Comment by roeera** [comment]
Hi @KashifSaadat, thanks for the update.
Actually I already created my cluster using "legacy : true" which actually solved my problem.
Is there any special difference when using my used mechanism to your PR ?
Thanks !
BTW @chrislovecnm Good luck with your presentation in TA today 👍  (Unfortunately all ticket have gone so I couldn't attend)

**Comment by KashifSaadat** [comment]
I'd recommend keeping the `legacy` flag set to false as it enforces a more restrictive IAM policy, reducing the scope of changes that kops master nodes can make.

Setting the IAMSpec to what was mentioned above should still give you the functionality you require, but if you do notice any additional issues please let me know!

**Comment by roeera** [comment]
Thank you, I think that the issue can be close now...
