### ISSUE TITLE
kops update not picking up new kubeAPIServer details added using kops edit

### ISSUE THREAD

**Issue by Parrryy** [kubernetes/kops#3666]
Kops: v1.7.1
Kubernetes: v1.8.1
Cloud Platform: AWS

I'm trying to setup kubeAPIServer for my current cluster to enable logging and OIDC authentication.

```
  kubeAPIServer:
    auditLogMaxAge: 30
    auditLogMaxBackups: 5
    auditLogPath: /var/log/kube-apiserver-audit.log
    oidcClientID: <our client-id>
    oidcIssuerURL: https://accounts.google.com
    oidcUsernameClaim: email
```

I've added these using ```kops edit cluster```, saving the changes. Running ```kops update cluster``` gives the following output, explaining there are no changes to be applied.

```
I1019 15:19:29.897501    8647 executor.go:91] Tasks: 0 done / 63 total; 34 can run
I1019 15:19:30.408632    8647 executor.go:91] Tasks: 34 done / 63 total; 12 can run
I1019 15:19:30.728247    8647 executor.go:91] Tasks: 46 done / 63 total; 15 can run
I1019 15:19:31.010653    8647 executor.go:91] Tasks: 61 done / 63 total; 2 can run
I1019 15:19:31.068242    8647 executor.go:91] Tasks: 63 done / 63 total; 0 can run
No changes need to be applied
```

I just want kops to apply the changes so that I can start using the OIDC and audit logs.

Thanks, in advance.

**Comment by mikesplain** [comment]
@Parrryy changes like that are saved right to s3 and aren't reflected in `kops update cluster` I believe. You need to force roll your masters to see the changes. `kops rolling-update cluster --force --yes --instance-group master-us-east-1a` or similar

**Comment by Parrryy** [comment]
@mikesplain I did perform `kops rolling-update --force`, didn't add the --yes or instance group. I can't seem to find a way to test if the changes that I have applied are working. I've setup the OIDC with google, but when trying to access kubectl with my client machine, I get error: couldn't read version from server: Get `https://api.cluster.aws.learnium.com/api: x509: certificate signed by unknown authority`.

For production environments do you need to setup your own certificates?

**Comment by brosander** [comment]
I had a similar issue while trying to enable audit logging. ```kops rolling-update cluster --force --yes``` did the trick for me (although it was probably a little heavy handed on my part to restart the nodes also)

**Comment by chrislovecnm** [comment]
Just specify the instance group name and only the masters can be restarted

**Comment by Parrryy** [comment]
Thanks for the responses guys, is this an issue with `kops` not being able to process the update or relay any decent feedback for changing the `kubeAPIServer` config? 

@mikesplain I'm able to access kubectl on the platform where I created the cluster using kops. I'm trying to find a decent approach for enabling our development team to access it with RBAC from their client machines. I seem to have the cluster settings correct, but when accessing with the OIDC information from my client machine. I get a certificate issue.

**Comment by chrislovecnm** [comment]
This is an open issue on how we detect changes with kops. This has been a known issue for awhile.

**Comment by mikesplain** [comment]
@Parrryy Configs like `kubeAPIServer` are only picked up when an instance boots.  Some changes (I can't remember which specifically) are also stored in the instance user-data but for the most part we recommend rolling-updates whenever possible.  Since you should be running with multiple masters, it shouldn't have any negative effect.  

As for the OIDC stuff, I haven't dipped my toes into it too much.  I would suggest asking a question on the kubernetes slack org, maybe sig-auth

**Comment by mikesplain** [comment]
@Parrryy Although this chat just happened on slack which you may find useful: https://kubernetes.slack.com/archives/C3QUFP0QM/p1508494577000197

**Comment by Parrryy** [comment]
@mikesplain I am on the slack so I will check that now, thanks. We're currently only at one master node so will have to implement another one. I will add another master node, perform the appropiate rolling-update and then if I am still having issues then I will ask on sig-auth. Thanks for the help.

**Comment by mikesplain** [comment]
@Parrryy you bet, don't forget to follow directions when moving from single to multi: https://github.com/kubernetes/kops/blob/master/docs/single-to-multi-master.md

**Comment by KashifSaadat** [comment]
@Parrryy this issue was actually fixed a month ago, and has made it into the following kops release: https://github.com/kubernetes/kops/releases/tag/1.8.0-alpha.1

With the above release, when you run an update it will attempt to add some Cluster & IG Spec data into the user-data for the nodes, marking them as requiring a rolling update.

**Comment by Yggdrasil** [comment]
@KashifSaadat Very nice. I'm wondering if that fix also works for the terraform output? I found this issue after noticing that my changes applied to `spec.kubeAPIServer` via `kops edit cluster` did not lead to any change in the terraform output.  `kops update cluster --out terraform` didn't generate a change in the kubernetes.tf file, nor show any nodes needed rolling-updates.

**Comment by KashifSaadat** [comment]
Hi @Yggdrasil, yep this fix also works for the terraform output. Making changes to the `KubeAPIServerSpec` will cause an update to the user-data. When outputting the changes to terraform, the generated user-data file will have different content and this will cause a change to the launch configuration for the Master & Compute nodes. You can then trigger a kops rolling-update so the nodes rebuild with the new user data.

**Comment by KashifSaadat** [comment]
@Parrryy have you managed to retest this recently with kops built from source? Can we close this issue?

**Comment by Parrryy** [comment]
Yeah, @KashifSaadat thanks for reminding me. It worked as expected.

**Comment by shavo007** [comment]
So....

Just to confirm. I need to update the master instance group only?

```
kops get instancegroups
 kops rolling-update cluster  --instance-group <masterName> --force --yes

```

If I do not force, it states no update needed. 

Should this be added to the doc here?
https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#audit-logging

**Comment by KashifSaadat** [comment]
Hi @shavo007. The latest version of kops has this bug fixed, so you no longer need to provide the `--force` flag when updating the KubeAPIServer Spec.

**Comment by shavo007** [comment]
Thanks @kashifsaadat still can't see the log file tho..

**Comment by KashifSaadat** [comment]
@shavo007 the issue you're experiencing is a little different from this one.

Please can you raise a new issue including your Kops ClusterSpec and images used for the master/node instances? I'll see if I can replicate and debug further.

**Comment by shavo007** [comment]
raised an issue @KashifSaadat  #4368
