### ISSUE TITLE
Use placement groups for low latency networking between nodes in an instance group

### ISSUE THREAD

**Issue by erutherford** [kubernetes/kops#367]
[Placement groups](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html) can lower the latency for network traffic between nodes and increase bandwidth between nodes.  kops should allow for a option which allows people to use placement groups in AWS when spinning up instance groups.

**Comment by zapman449** [comment]
1) Can you ASG a placement group?
2) This basically forces you into a single AZ cluster
3) As noted in slack, this does increase the blast radius of a single AWS Hardware system catastrophically failing
4) Making this a 'non-default' option is reasonable.

**Comment by erutherford** [comment]
There are definitely some limitations, but to Justin's point (in slack) people should be allowed to at least specify it as an option when spinning up an instance group (which is what you're saying in 4)

> 1) Can you ASG a placement group?

Based off the [documentation](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html#concepts-placement-groups) it appears that it is supported.  They just mention that it's ideal to add all members to the placement group when you initialize it or you may run into issues with a `not enough resources` error, but you can also run into that error when stoping and starting a node in a placement group.

**Comment by dlutsch** [comment]
Is there any update on this feature?

**Comment by genexp** [comment]
Note: I think the idea is to create a single placement group per availability zone.

**Comment by layer3switch** [comment]
As per @zapman449 questions,

> 1. Can you ASG a placement group?

Yes. ASG via Launch Template and Cloudformation supports this.

> 2. This basically forces you into a single AZ cluster

No longer this is true. AWS supports something called ```Spread Placement Groups```. This allows max 7 instances per AZ per placement group. At this time, this seems to be hard limit.

> 3. As noted in slack, this does increase the blast radius of a single AWS Hardware system catastrophically failing

Spread Placement Groups address this concern.

**Comment by jnicholls** [comment]
Can we reopen this? I think it's pertinent for kops to support placement groups for node groups (both cluster and spread variants).

**Comment by suchakjani** [comment]
/reopen
We need placement groups for things like NFT tests for certain applications.
Would appreciate if this is done

**Comment by phs** [comment]
My use case is looking at multiple clusters, each sandboxed to a single AZ.

A spread placement group would therefore be useful specifically for the masters.

**Comment by geekofalltrades** [comment]
We would like this as well. Multiple folks have expressed interest in this over time. Can it be reopened and /lifecycle frozen so it doesn't rot again?

**Comment by minkimipt** [comment]
I think it's still relevant. Can we reopen?
/reopen

**Comment by olemarkus** [comment]
I suggest opening a new issue that details what you want to achieve and how. I'd say its a fairly high chance you need to contribute the PR as well.
