### ISSUE TITLE
Implement VFS with Openstack Swift

### ISSUE THREAD

**Issue by zengchen1024** [kubernetes/kops#3676]
Add a new implementation of VFS to store the state of cluster in order to support deploying k8s on openstack(#3566)

**Comment by chrislovecnm** [comment]
Please vendor the golang depedencies that you will need. We can get them in before any code. We have instructions under the developer director howto.

**Comment by zengchen1024** [comment]
@chrislovecnm Thanks for you guidance! Did you want to say the dependencies said at here https://github.com/kubernetes/kops/blob/master/docs/development/dependencies.md ? So far, my codes just depend on the library of "https://github.com/gophercloud/gophercloud". I will commit my codes according to the rules as that doc said.

**Comment by chrislovecnm** [comment]
Please if we do not have it
