### ISSUE TITLE
Allow customizing instance names

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#368]
Currently after a kops setup I end up with node and master instances that have a `Name` tag like: `nodes.<my-cluster>` or `master-<region>.masters.<my-cluster>`.

At my organization we have a different naming convention that all instances conform to, and this breaks that. It would be great to be able to specify the instance names as part of the cluster setup.

**Comment by d-shi** [comment]
Any update on this? I am also interested in either having custom instance names.

**Comment by chrislovecnm** [comment]
Nobody that I know of is working on this
