### ISSUE TITLE
sshKeyName throws Secret Error

### ISSUE THREAD

**Issue by john-delivuk** [kubernetes/kops#3693]
Thanks for submitting an issue! 

-------------BUG REPORT --------------------
1. Fill in as much of the template below as you can. 
```---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
    name: johnd-kops.k8s.local
    creationTimestamp: 2017-10-23T21:07:46Z
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    RBAC: {}
  channel: stable
  cloudLabels:
    Team: conductor-testing
  cloudProvider: aws
  configBase: s3://conductor-testing-kops-state/johnd-kops.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1d
      name: d
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1d
      name: d
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.7.8
  masterInternalName: blue-johnd-kops.k8s.local
  masterPublicName: johnd-kops.k8s.local
  networkCIDR: 172.31.0.0/16
  networkID: omitted
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshKeyName: john-testing-key
  sshAccess:
  - omitted
  subnets:
  - cidr: 172.31.100.0/24
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 172.31.100.0/24
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
  fileAssets:
  - name: bootstrap.yaml
    # Note if not path is specificied the default path it /srv/kubernetes/assets/<name>
    path: /etc/kubernetes/manifests/boostrap.yml
    roles: [Master]
    content: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: something

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-10-23T19:15:02Z
  name: nodes
  labels:
    kops.k8s.io/cluster: johnd-kops.k8s.local  
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20170721
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  role: Node
  subnets:
  - us-east-1d

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-10-23T19:15:02Z
  name: master-us-east-1d
  labels:
    kops.k8s.io/cluster: johnd-kops.k8s.local 
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20170721
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1d
```
2. What kops version are you running? use `kops version`
1.8.0
3. What Kubernetes version are you running? use `kubectl version`
1.8
4. What cloud provider are you using?
aws
5. What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?
```kops update cluster $NAME --yes```

Output 
```SSH public key must be specified when running with AWS (create with `kops create secret --name johnd-kops.k8s.local sshpublickey admin -i ~/.ssh/id_rsa.pub`)```
6. What you expected to happen:
Cluster to be created 
7. How can we to reproduce it (as minimally and precisely as possible):
kops create -f [myspecfromabove.yml]
8. Anything else do we need to know:
I think it's just a exception that needs to be tuned. Happy to contribute any other information.

**Comment by chrislovecnm** [comment]
I have a pr in to specify a ssh name on the create, but it has not gone through.

The is not a bug, but as designed three step process to create with yaml

**Comment by keefbaker** [comment]
I'm hitting the same thing. I'm specifying sshKeyName as a key I have in aws and it seems to ignore this, force me to point it at the public key on the box and then in aws I have the usual auto-generated keyname on the nodes rather than my predefined aws key.

Also when doing a ```kops get <cluster> -o yaml``` I can see that the ```sshKeyName``` field isn't included.

**Comment by chrislovecnm** [comment]
I am guessing you are on a version that does not have ssh key name released. It was put into the code base recently, and I am not certain if it is in the 1.8 alpha

**Comment by twang-rs** [comment]
I can verify that if you run the `kops create secret --name $NAME sshpublickey admin -i ~/.ssh/id_rsa.pub` that cluster creation will complete successfully and will *not* create a new key inside AWS, but use the existing keypair defined in `sshKeyName`.

Can someone clarify whether the `kops create secret` command should be necessary, or if its simply a remnant of previous behavior and should be something that will eventually be cleaned up?

**Comment by willejs** [comment]
I am running against what is on master and get this issue too. 
```kops version
Version 1.8.0-beta.2 (git-23319a097)```

my cluster spec when i do kops get <cluster> -o yaml says
```
spec:
  ...
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: a14b50515-test-main-k8s
```

When i create a new cluster, and then run ```kops cluster update --yes``` I get the following error:
```
SSH public key must be specified when running with AWS (create with `kops create secret --name a14b50515-test-main-k8s.main.test.ri-tech.io sshpublickey admin -i ~/.ssh/id_rsa.pub`)
```

**Comment by willejs** [comment]
@chrislovecnm I know you have an issue to clear up how this should work... 
If you specify the existing aws ec2 key name in the cluster spec/cli when you create the cluster, should you still have to create the secret with the public key in?

**Comment by john-delivuk** [comment]
Just following up. I am using v1.8 as mentioned, even in the GA release this is still present. I want to only use my sshKey which is specified in my AWS Account, I shouldn't have to specify the id_rsa.pub to pass validation.

**Comment by mellena1** [comment]
Following up on the above posters' issue, I am having the same problem. Pass in sshKeyName in my yaml, go to run update, and get ```SSH public key must be specified when running with AWS```.

**Comment by michaelajr** [comment]
This is still an issue. I thought this was going to get fixed in 1.9.0.

**Comment by alkar** [comment]
This is still present in version `1.10.0`

**Comment by ChristophP** [comment]
This is still present in version `1.11.0`
