### ISSUE TITLE
Master servers in autoscale mode

### ISSUE THREAD

**Issue by rp-happiestbaby** [kubernetes/kops#3696]
Hi,
I have one general question 
Is it good idea to setup autoscale group for master and node servers in aws by editing this 2 ig
kops edit ig --name $cluster_name  --state=s3://$cluster_name nodes
kops edit ig --name=$cluster_name --state=s3://$cluster_name master-us-east-1a 
And change max to something bigger so it scales as it uses more resources? 

Thanks in advance.

**Comment by chrislovecnm** [comment]
Not advisable because of etcd. You can run into all kinds of run by specifically reducing etcd count. Not sure if kops even supports more than one instance in an ig with a master.

It is simple enough to replace a master with a new instance type. And a m4.large can run a very very large cluster.

**Comment by chrislovecnm** [comment]
From the docs

1-5 nodes: m3.medium
6-10 nodes: m3.large
11-100 nodes: m3.xlarge
101-250 nodes: m3.2xlarge
251-500 nodes: c4.4xlarge
more than 500 nodes: c4.8xlarge

I usually recommend m4s or c4s as the m3s are not in every region.

**Comment by rp-happiestbaby** [comment]
So it is better to have 3 master (You can set number for muster with --master-count=3)
And autoscale for node servers?

**Comment by chrislovecnm** [comment]
1 or 3 or some silly number that gives u quorum. 5, 9, etc. Also you need three AZs in your region, otherwise you do not get full HA

3 is fine for 90% of installs. 1 is fine if you need 3/9's for the control plane.

Going to close this issue.

**Comment by rp-happiestbaby** [comment]
Thanks

**Comment by chrislovecnm** [comment]
Closing
