### ISSUE TITLE
Publicize AWS AMI updates and include Release Notes for changes.

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [kubernetes/kops#3697]
I recently checked what AWS AMI we were using in our cluster and discovered that there have been four new versions since we initially deployed our cluster.

It would be great if 1) there were some public feed where we could be notified about such updates, and 2) if there were Release Notes for the changes in these updates.

```
k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09 | ami-aaf84aca
k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-03-07 | ami-7e69e51e
k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-05-02 | ami-885bc3e8
k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-06-16 | ami-aaa1aad3
k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-07-28 | ami-30917448
```

**Comment by chrislovecnm** [comment]
1) we need to announce on the kube lists when we do releases
2) we need release notes

**Comment by rifelpet** [comment]
Kops now defaults to the official Ubuntu 20.04 AMI. Kops will notify the user when there is a newer AMI in the channels file, but any further notification or release notes for the AMI are out of scope for Kops. 

/close
