### ISSUE TITLE
Wider toleration to calico-node daemonset

### ISSUE THREAD

**Issue by guitmz** [kubernetes/kops#3703]
As of now in kops `1.7.1`, the nice fix merged in the PR https://github.com/kubernetes/kops/pull/3097 doesn't seem to work. It was not applied to the `1.7` branch. Could you please include it? It was merged to master in August, which is quite a few months ago!

I really don't like the idea of having to edit calico add-on and applying manually. It is easy to lose track if this change if done manually.

Any other workarounds in the mean time are appreciated.

Thanks

**Comment by KashifSaadat** [comment]
Hi @guitmz, the above PR is available in the following kops release: https://github.com/kubernetes/kops/releases/tag/1.8.0-alpha.1

**Comment by chrislovecnm** [comment]
Also that release does not have the CVE patch

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by KashifSaadat** [comment]
@chrislovecnm could we issue an alpha.2 release with the CVE patch included?

**Comment by chrislovecnm** [comment]
@KashifSaadat when alpha or beta 1.8 kops is released, it will include both.

**Comment by guitmz** [comment]
@chrislovecnm yeah we can close it then, thanks
