### ISSUE TITLE
New cli docs generator

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3717]
Tracking issue here https://github.com/kubernetes-incubator/reference-docs/issues/31

See if we want to use the same new tool for generating docs.

/area documentation

**Comment by ss22ever** [comment]
@chrislovecnm will like to work on it.

**Comment by chrislovecnm** [comment]
Ping me if you need help.

**Comment by johngmyers** [comment]
If this is still an issue, need more information as to which generator is desired. The linked ticket has no information.

/remove-lifecycle frozen

**Comment by chrislovecnm** [comment]
The thought was to use the k8s documentation generation tools to generate both the cli and API documentation.  https://github.com/kubernetes-sigs/reference-docs is the set of tools.

**Comment by johngmyers** [comment]
That set of tools appears to have code that is highly specific to the Kubernetes API and kubectl. It doesn't look particularly reusable.
