### ISSUE TITLE
Support encrypted EBS volumes

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#372]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html

**Comment by yissachar** [comment]
It looks like for nodes/masters EBS boot volume it is possible to do this manually by passing an encrypted image when you create the cluster.

Steps I followed:

1. Create new image from running instance (using the default image: `282335181503 /k8s-1.2-debian-jessie-amd64-hvm-2016-03-16-ebs`).

2. Copy the image and encrypt it:

```
aws ec2 copy-image --source-region=us-east-1 --source-image-id=<my-private-ami> --name=foobar --encrypted
```

3. Create a cluster passing in the new encrypted image:

```
kops create cluster --name=blah.meh.com --image=<encrypted-ami-id> --zones=us-east-1a --state=<state>
```

It would be nice if this could be automatically done as part of the kops process though.

Additionally, the etcd volumes are still unencrypted with this approach.

**Comment by justinsb** [comment]
I think we can do this in imagebuilder when we build the image, or at least document how to enable encryption.

@yissachar do you know of any downsides to doing this?   Also, can we just encrypt the "master" AMI, or does every user need to create their own copy?

**Comment by yissachar** [comment]
The downside is that building an image is slow, so will add time to the cluster turn-up. However, so long as this opt-in and we document that enabling this will cause the process to take longer, it should be fine.

We can't just encrypt the AMI once, it is a per account process.

By the way, I think there is something not setup with the base k8s image that causes us to do the extra work of creating my own version of the image (the first step from above). According to this [AWS blog post](https://aws.amazon.com/blogs/aws/new-encrypted-ebs-boot-volumes/):

> The process of creating an encrypted EBS boot volume begins with an existing AMI (either Linux or Windows). If you own the AMI, or if it is both public and free you can use it directly. Otherwise, you will need to launch the AMI, create an image from it, and then use that image to create the encrypted EBS boot volume (this applies, for example, to Windows AMIs). The resulting encrypted AMI will be private; you cannot share it with another AWS account.

Since the k8s image appears to be both public and free, I expected to be able to copy it directly. But when I tried to do that, I got this error:

```
A client error (InvalidRequest) occurred when calling the CopyImage operation: You do not have permission to access the storage of this ami
```

So I'm wondering if there is something about the k8s image that is not "public and free".

**Comment by druidsbane** [comment]
From: https://support.bioconductor.org/p/88223/

> The owner of the account must grant read permissions on the storage that backs the AMI, whether it is an associated EBS snapshot (for an Amazon EBS-backed AMI) or an associated Amazon S3 bucket (for an instance-store-backed AMI). To allow other accounts to copy your AMIs, you must grant read permissions on your associated snapshot or bucket using the Amazon EBS or Amazon S3 access management tools.
> 
> When an AMI is copied, the owner of the source AMI is charged standard Amazon EBS or Amazon S3 transfer fees, and the owner of the target AMI is charged for storage in the destination region.

This will need to be done first before support can be added for kops.

**Comment by yissachar** [comment]
@druidsbane Thanks for pointing this out. That would work for images that kops has control over, but we want to support a wide range of images that kops doesn't have control over, that we can't assume have set this.

At this point I think it's probably best to leave this step outside of kops and have kops just deal with the passed in image - it would be up to the user to manually encrypt that first if they want to. We could add a docs page outlining the process (the steps I listed above).

@justinsb Thoughts?

**Comment by yissachar** [comment]
Oh, and regardless of what we decide to do here, whoever has control over the k8s AMI should probably grant read permissions as @druidsbane pointed out.

**Comment by chrislovecnm** [comment]
Can someone propose a design?

**Comment by cesartl** [comment]
Is there any update on this issue?

**Comment by bilalyasar** [comment]
@justinsb is there any plan for this issue?

**Comment by ryan-dyer** [comment]
https://aws.amazon.com/about-aws/whats-new/2019/05/launch-encrypted-ebs-backed-ec2-instances-from-unencrypted-amis-in-a-single-step/

Can we now get a flag to turn on encryption?

**Comment by bionicles** [comment]
Not stale

**Comment by pradeepnnv** [comment]
This would be really helpful.

**Comment by BobbyJohansen** [comment]
This would be great

**Comment by SimplicityGuy** [comment]
Is there progress on when kops will allow us to specify encrypted EBS volumes on EC2 instances?

**Comment by SimplicityGuy** [comment]
Looks like the workaround here is referenced here: https://github.com/kubernetes/kops/issues/4225#issuecomment-517789339

**Comment by ryan-dyer-sp** [comment]
This was added in 1.19 of kops: https://kops.sigs.k8s.io/tutorial/working-with-instancegroups/#encrypting-the-root-volume
