### ISSUE TITLE
Block node access to etcd peer port

### ISSUE THREAD

**Issue by brosander** [kubernetes/kops#3746]
The master node firewall rules block nodes from accessing etcd on the client port but [leave the peer port accessible.](https://github.com/kubernetes/kops/blob/1.7.1/pkg/model/firewall.go#L195)

It should probably leave ports 2380 and 2381 out of the range too to prevent pods on nodes from attempting to connect to the etcd peer ports.

**Comment by chrislovecnm** [comment]
Is etcd always on those ports? If so I agree we should shut them down, except for canal, calico and romano installs.

Contributions are always appreciated

**Comment by brosander** [comment]
I'm not positive if it is always those ports but the above linked firewall code seems to assume that the client ports will always be 4001 and 4002.

Canal seems to be functioning properly with no access to etcd on nodes (I manually changed the rule in our setup).  The [canal roadmap](https://github.com/projectcalico/canal#roadmap) also implies that it's not needed.  It looks like if Calico is the networking choice, [kops allows etcd access already](https://github.com/kubernetes/kops/blob/1.7.1/pkg/model/firewall.go#L203).  Not sure about romano.
