### ISSUE TITLE
kops create cluster subnet-id parameter

### ISSUE THREAD

**Issue by cdenneen** [kubernetes/kops#3754]
Request to add subnet-id parameter to `kubectl create cluster`.
Currently you have to create a cluster and then edit that cluster replacing `cidr:` with `id:`
Maybe if you specify zones as `us-east-1a,us-east-1b,us-east-1c` the opinionated option would be the subnet-id's passed have to be in that same order?

Just looking for a way to avoid having to `edit` cluster manually after creation.

**Comment by chrislovecnm** [comment]
Can you use a manifest instead? We have docs how to do that.

**Comment by cdenneen** [comment]
You have example? That should be fine.

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/blob/master/docs/manifests_and_customizing_via_api.md

We have docs ;)

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/issues/3753 This is really a duplicate if you use a yaml manifest

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by cdenneen** [comment]
Yes thanks
