### ISSUE TITLE
Unable to use NetworkPolicy with kops 1.7 and calico

### ISSUE THREAD

**Issue by orkaa** [kubernetes/kops#3755]
I'm running a kops cluster on top of AWS. I used terraform to start it up.

```
$ kops version
Version 1.7.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-10-05T00:40:04Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

I'm unable to apply any NetworkPolicy rules specified in kubernetes docs - https://kubernetes.io/docs/concepts/services-networking/network-policies/

For example, if I try blocking all ingress:

```
$ kubectl apply -f - <<EOF
> apiVersion: networking.k8s.io/v1
> kind: NetworkPolicy
> metadata:
>   name: default-deny
> spec:
>   podSelector: {}
>   policyTypes:
>   - Ingress
> EOF
error: error validating "STDIN": error validating data: ValidationError(NetworkPolicy.spec): unknown field "policyTypes" in io.k8s.kubernetes.pkg.apis.networking.v1.NetworkPolicySpec; if you choose to ignore these errors, turn validation off with --validate=false
```

It's no different if I try using calico directly:

```
$ kubectl exec -ti -n kube-system calicoctl -- /calicoctl apply -f - <<EOF
> apiVersion: networking.k8s.io/v1
> kind: NetworkPolicy
> metadata:
>   name: default-deny
> spec:
>   podSelector: {}
>   policyTypes:
>   - Ingress
> EOF
Unable to use a TTY - input is not a terminal or the right kind of file
Failed to execute command: Unknown resource type (NetworkPolicy) and/or version (networking.k8s.io/v1)
command terminated with exit code 1
```

I tried describing the calico pod to see which version I'm running:
```
Image:          calico/node:v1.2.1
```

This seems to be pretty old? The newest stable version is 2.6?

What am I missing here? Should this work or not? Do I need to upgrade calico and how do I do that?

I'd appreciate any info that would shed some light into this situation.

**Comment by pastjean** [comment]
It appears you are using 1.8 network policy definition for a 1.7 cluster

Here is the documentation for a 1.7 network policy:
https://v1-7.docs.kubernetes.io/docs/concepts/services-networking/network-policies/#the-networkpolicy-resource

Also those policy definition are not the same when using `calicoctl` directly:
https://docs.projectcalico.org/v2.6/reference/calicoctl/resources/policy#rule (this is for calico2.6)

Upgrading the cluster to 1.8 would ease all this.

for the Calico version, you can always upgrade, maybe some maintainer would know why the version installed by kops is that "old"

**Comment by orkaa** [comment]
I tried it again with 1.7 docs - https://v1-7.docs.kubernetes.io/docs/concepts/services-networking/network-policies/#the-networkpolicy-resource

```
$ kubectl apply -f - <<EOF
> apiVersion: networking.k8s.io/v1
> kind: NetworkPolicy
> metadata:
>   name: default-deny
> spec:
>   podSelector:
> EOF
error: error validating "STDIN": error validating data: ValidationError(NetworkPolicy.spec): missing required field "podSelector" in io.k8s.kubernetes.pkg.apis.networking.v1.NetworkPolicySpec; if you choose to ignore these errors, turn validation off with --validate=false
```

Same issue.

**Comment by tmjd** [comment]
See https://docs.projectcalico.org/v2.2/getting-started/kubernetes/tutorials/simple-policy for examples of policy.

Here is an example from that page.
```
kubectl create -f - <<EOF
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: access-nginx
  namespace: policy-demo
spec:
  podSelector:
    matchLabels:
      run: nginx
  ingress:
    - from:
      - podSelector:
          matchLabels:
            run: access
EOF
```

It looks like you are trying to use the newer syntax for the default-deny, because of the version of Calico Kops 1.7 deploys you will need to use the older style annotation for the default deny behavior.  The doc I linked above has an example of that too.

**Comment by orkaa** [comment]
@tmjd Turns out the 1.7 docs are also wrong

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector:
```

It works if I add curly braces to podSelector

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
```

Whatever. :)

The question about calico version still stands. Why is kops using such an old version?
