### ISSUE TITLE
Release 1.8.0

### ISSUE THREAD

**Issue by pierreozoux** [kubernetes/kops#3759]
We are waiting to update our underlying docker version, and this needs kubernetes 1.8.0.
We already tried the alpha version, but it didn't go that well. We saw the PR merged with calico, and it looks promising!

I checked issues, milestones, and project, looks everything is in order to ship 1.8.0? Or I missed something?

We could do one more round of testing with our setup, on our test environment?

Just would like to kick the ball to keep it rolling, and give some help if needed to release 1.8.0 \o/

**Comment by eljefedelrodeodeljefe** [comment]
I am also highly interested what the roadmap for 1.8 is. 

Support and repositories for secondary systems like logging and everything state related are all well ahead and require 1.8, which is now a little hassle to work with old versions of them.

**Comment by joan38** [comment]
Same here!

**Comment by romanchepurnyi** [comment]
+1

**Comment by brava-vinh** [comment]
I think one of the issues with 1.7 is depend on docker `1.12` which its `awslogs` log driver lag tag option. I really want to have `image-name` as part of cloudwatch log stream. 

I attempt to manually  change docker version in config file but it won't work.

I think having 1.8 with docker 17 will be very helpful and bring it more up-to-date.

**Comment by chrislovecnm** [comment]
@pierreozoux testing all of the CNI providers, and the different OS types with a full kops 1.8.0 build would be awesome.  Also testing upgrading k8s is always important.

We are still wrapping some issues and new features before 1.8.0 beta is released.  For instance, we found an IAM regression issue today.  

I do not have a date yet for kops beta 1.8.0 as of yet.

**Comment by felipejfc** [comment]
just a fyi, I've successfully upgraded my 1.7 staging cluster to 1.8 with kops 1.8 beta

**Comment by roeera** [comment]
Trying to upgrade 1.8 alpha to 1.8 beta... problem with rolling update didn't finished as expected and only manual intervention helped the cluster and nodes rollout.
We also still have problem with kube-dns and dashboard pods which are crashing all the time.

**Comment by chrislovecnm** [comment]
Rolling updatecis our code, more details please.

**Comment by StevenACoffman** [comment]
See #3821 possibly.

**Comment by joan38** [comment]
Is there any update on this?

**Comment by chrislovecnm** [comment]
@joan38 we have one blocker https://github.com/kubernetes/kops/issues/3958 not a P0, but I think @justinsb wants to address it.

**Comment by chrislovecnm** [comment]
It is out - yay

Closing
