### ISSUE TITLE
Enable AWS ECR IAM Permissions by default when creating a new cluster

### ISSUE THREAD

**Issue by KashifSaadat** [kubernetes/kops#3760]
Related to PR #3690.

When creating a new cluster with kops, the `allowContainerRegistry` flag should be set to true by default. Users can tweak and disable this as required for a more minimal set of permissions.

File: https://github.com/kubernetes/kops/blob/master/cmd/kops/create_cluster.go#L923

**Comment by chrislovecnm** [comment]
This is a critical fix we need in.
