### ISSUE TITLE
How to specify that the node should request an IPV6 address

### ISSUE THREAD

**Issue by jwickens** [kubernetes/kops#3765]
-------------BUG REPORT --------------------

2. What kops version are you running?
`1.7.0`

3. What Kubernetes version are you running?
`1.7.3`

4. What cloud provider are you using?
`AWS`

5. What commands did you execute?
 `kops rolling-update cluster --yes --force`

After the nodes came back up the ipv6 address was no longer associated.

6. What you expected to happen:

IPv6 ip addresses to stay bound
7. How can we to reproduce it (as mi
nimally and precisely as possible):

Setup cluster, add ipv6 addresses through aws console, use kops to do a rolling - restart

-------------FEATURE REQUEST --------------------

I would like there to be a way to specify an instance group attribute for the nodes so that they request an ipv6 address.

**Comment by chrislovecnm** [comment]
@caseydavenport is ipv6 supported with k8s yet?

@jwickens please use 1.7.1 as 1.7.0 has a CVE bug in it. You may be able to use a hook, but admittedly I am not certain that what you are doing is supported by k8s or kops.

**Comment by robinpercy** [comment]
@jwickens: According to https://github.com/kubernetes/kubernetes/issues/1443, ipv6 support in K8s is still a work in progress.

**Comment by jwickens** [comment]
Hey thanks for getting back.

I will update kops, thanks for the heads up. I'm aware kubernetes itself does not support ipv6 yet. What I am referring to is the specification for the amazon ec2 instance that gets created by kops.

Once k8s supports ipv6 im sure that if kops doesnt setup ec2 instances with ipv6 by default there will be lots of noise :)

For now I just edit the instance manually after updates. The reason i want this is because im using hostNetwork: true on my nginx ingress deployment so it listens to ipv6 and ipv4 even though k8s only supports ipv4 natively. Works well!

**Comment by caseydavenport** [comment]
> is ipv6 supported with k8s yet?

ipv6 support of course has a number of different pieces, some of which are done and some of which are still WIP.

The plan is to have alpha level support for ipv6 in k8s v1.9. @danehans is organizing a lot of that work.

It is possible to have ipv6 pod networking today provided your CNI provider supports it. I believe the reference plugins (bridge, ptp, host-local, etc) all support it in CNI version v0.6.0, as does Calico. Not sure about the others.

**Comment by danehans** [comment]
As @caseydavenport mentions, we are shooting to have IPv6 alpha support in 1.9. The details, caveats, etc. will be provided in the release. If you are interested in testing Kubernetes IPv6 in its current state, feel free to follow [this guide](https://github.com/leblancd/kube-v6) that @leblancd created.

**Comment by chrislovecnm** [comment]
As of now kops does not really support ipv6

**Comment by jwickens** [comment]
Hey guys, thanks for your responses. It sounds like a wont fix because its work in the pipeline. What do you want to do with this issue ? I'm happy to see it closed.
