### ISSUE TITLE
Romana networking requires additional IAM Describe permissions

### ISSUE THREAD

**Issue by cgilmour** [kubernetes/kops#3777]
A user in the kops slack channel reported problems getting Romana working with the latest pre-release build (1.8.0-alpha.1)
After a brief troubleshooting session, the problem was related to the recent change in IAM policies for master nodes.

The additional permissions required are
- `DescribeAvailabilityZones`
- `DescribeVpcs`

I'm happy to work on a PR to add those in in the correct way, and complete all the testing.
The code related to the "Describe" permissions is [here](https://github.com/kubernetes/kops/blob/df69d047f8a9034ba8855f5c6aa8febd89cb8614/pkg/model/iam/iam_builder.go#L524-L537).

They could be added to that list, or in CNI-specific policy statements. If you can suggest a specific way to implement it, I'll be happy to do the rest.

**Comment by chrislovecnm** [comment]
They needed to be added as cni specific policy. Also you can add those roles to the instance group as a work around.

**Comment by chrislovecnm** [comment]
Meaning, test for Romano as a cni provider,  in the clisterspec. then add them to the role.

**Comment by cgilmour** [comment]
Thanks Chris. I've submitted a PR based on that suggested implementation.

**Comment by cgilmour** [comment]
This is fixed from #3778 and #3782
