### ISSUE TITLE
Extensible IAM roles in AWS

### ISSUE THREAD

**Issue by tazjin** [kubernetes/kops#379]
Currently the AWS implementation of kops seems to create two IAM roles, one for the master and one for all nodes.

We are using [kube2iam](https://github.com/jtblin/kube2iam) to let pods assume IAM roles, to accomplish this we've attached an additional policy to the IAM role used by nodes that grants the necessary permissions.

I'm wondering if this is a stable way to go about it (i.e. will kops notice this change and nuke it in some future run?). Maybe `kops` should have a feature that lets users add additional policies to the roles created?

**Comment by justinsb** [comment]
I need to verify that kops won't detach the policy.  What you're doing is the right thing (vs eg editing the kops IAM policy, which would be impossible to preserve), so I want to make sure it works!

**Comment by sstarcher** [comment]
This should be closed via #1170

**Comment by chrislovecnm** [comment]
@tazjin does #1170 work for you, or are you looking for something at a pod level?

**Comment by tazjin** [comment]
@chrislovecnm It's a combination of both, the permission extensions from #1170 are necessary for supporting kube2iam correctly. This is working for us at the moment so I have no further needs. Feel free to close!

**Comment by chrislovecnm** [comment]
closing per above

**Comment by VinceMD** [comment]
Any update on this?
