### ISSUE TITLE
Import cluster from kubernetes version 1.3.5 did not work

### ISSUE THREAD

**Issue by rudaporto** [kubernetes/kops#3799]
* What kops version are you running?

Version 1.7.1 (git-c69b811)

*  What Kubernetes version are you running?

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

* What cloud provider are you using?
AWS

* What commands did you execute?

export KOPS_STATE_STORE=s3://briefy-stg-kubernetes
export OLD_NAME=briefy-kube-stg
export REGION=us-east-1

$ kops import cluster --region ${REGION} --name ${OLD_NAME} --v 10
I1108 16:27:12.459657   20563 s3context.go:159] Found bucket "briefy-stg-kubernetes" in region "us-east-1"
I1108 16:27:12.459768   20563 s3fs.go:173] Reading file "s3://briefy-stg-kubernetes/briefy-kube-stg/config"
I1108 16:27:12.502504   20563 channel.go:91] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I1108 16:27:12.502604   20563 channel.go:96] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I1108 16:27:12.502647   20563 context.go:132] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I1108 16:27:12.521568   20563 channel.go:105] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.7.0"
    - providerID: gce
      name: "cos-cloud/cos-stable-60-9592-90-0"
  cluster:
    kubernetesVersion: v1.5.7
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.7.0"
    recommendedVersion: 1.7.4
    requiredVersion: 1.7.0
  - range: ">=1.6.0"
    recommendedVersion: 1.6.7
    requiredVersion: 1.6.0
  - range: ">=1.5.0"
    recommendedVersion: 1.5.7
    requiredVersion: 1.5.1
  - range: "<1.5.0"
    recommendedVersion: 1.4.12
    requiredVersion: 1.4.2
  kopsVersions:
  - range: ">=1.7.0-alpha.1"
    recommendedVersion: 1.7.0
    #requiredVersion: 1.7.0
    kubernetesVersion: 1.7.4
  - range: ">=1.6.0-alpha.1"
    #recommendedVersion: 1.6.0
    #requiredVersion: 1.6.0
    kubernetesVersion: 1.6.7
  - range: ">=1.5.0-alpha1"
    recommendedVersion: 1.5.1
    #requiredVersion: 1.5.1
    kubernetesVersion: 1.5.7
  - range: "<1.5.0"
    recommendedVersion: 1.4.4
    #requiredVersion: 1.4.4
    kubernetesVersion: 1.4.12
I1108 16:27:12.522631   20563 import_cluster.go:631] Querying EC2 instances
I1108 16:27:12.522824   20563 request_logger.go:45] AWS request: ec2/DescribeInstances
I1108 16:27:12.700630   20563 import_cluster.go:140] Found master: "i-0ca6437e4d26cf0ca"
I1108 16:27:12.700727   20563 aws.go:968] Listing EC2 subnets
I1108 16:27:12.700883   20563 request_logger.go:45] AWS request: ec2/DescribeSubnets
W1108 16:27:12.791359   20563 import_cluster.go:169] Ignoring subnet "subnet-bd8e65f4" in which no instances were found
W1108 16:27:12.791474   20563 import_cluster.go:169] Ignoring subnet "subnet-bf8e65f6" in which no instances were found
I1108 16:27:12.791510   20563 aws_cloud.go:556] Calling DescribeVPC for VPC "vpc-8b1077ec"
I1108 16:27:12.791666   20563 request_logger.go:45] AWS request: ec2/DescribeVpcs
I1108 16:27:13.001954   20563 request_logger.go:45] AWS request: ec2/DescribeInstanceAttribute
I1108 16:27:13.058009   20563 import_cluster.go:823] gzip data detected; will decompress
I1108 16:27:13.058638   20563 import_cluster.go:800] Unknown line: #! /bin/bash
I1108 16:27:13.058678   20563 import_cluster.go:800] Unknown line: mkdir -p /var/cache/kubernetes-install
I1108 16:27:13.058709   20563 import_cluster.go:800] Unknown line: cd /var/cache/kubernetes-install
I1108 16:27:13.058737   20563 import_cluster.go:800] Unknown line: cat > kube_env.yaml << __EOF_MASTER_KUBE_ENV_YAML
I1108 16:27:13.058801   20563 import_cluster.go:800] Unknown line: __EOF_MASTER_KUBE_ENV_YAML
I1108 16:27:13.058833   20563 import_cluster.go:800] Unknown line: 
I1108 16:27:13.058861   20563 import_cluster.go:800] Unknown line: wget -O bootstrap https://s3.amazonaws.com/briefy-stg-kubernetes/devel/bootstrap-script
I1108 16:27:13.058891   20563 import_cluster.go:800] Unknown line: chmod +x bootstrap
I1108 16:27:13.058919   20563 import_cluster.go:800] Unknown line: mkdir -p /etc/kubernetes
I1108 16:27:13.058960   20563 import_cluster.go:800] Unknown line: mv kube_env.yaml /etc/kubernetes
I1108 16:27:13.058989   20563 import_cluster.go:800] Unknown line: mv bootstrap /etc/kubernetes/
I1108 16:27:13.059017   20563 import_cluster.go:800] Unknown line: cat > /etc/rc.local << EOF_RC_LOCAL
I1108 16:27:13.059044   20563 import_cluster.go:800] Unknown line: #!/bin/sh -e
I1108 16:27:13.059071   20563 import_cluster.go:800] Unknown line: /etc/kubernetes/bootstrap
I1108 16:27:13.059112   20563 import_cluster.go:800] Unknown line: exit 0
I1108 16:27:13.059140   20563 import_cluster.go:800] Unknown line: EOF_RC_LOCAL
I1108 16:27:13.059167   20563 import_cluster.go:800] Unknown line: /etc/kubernetes/bootstrap
I1108 16:27:13.059194   20563 import_cluster.go:800] Unknown line: 
I1108 16:27:13.059229   20563 aws.go:239] Listing all Autoscaling groups matching cluster tags
I1108 16:27:13.059426   20563 request_logger.go:45] AWS request: autoscaling/DescribeTags
I1108 16:27:13.104948   20563 request_logger.go:45] AWS request: autoscaling/DescribeAutoScalingGroups
W1108 16:27:13.133637   20563 import_cluster.go:302] Multiple Autoscaling groups found
I1108 16:27:13.133685   20563 aws.go:301] Retrieving Autoscaling LaunchConfigurations "briefy-kube-stg-minion-group-us-east-1b"
I1108 16:27:13.133797   20563 request_logger.go:45] AWS request: autoscaling/DescribeLaunchConfigurations
I1108 16:27:13.824437   20563 ca.go:377] Parsing pem block: "CERTIFICATE"
I1108 16:27:13.824654   20563 vfs_castore.go:473] Adding TLS certificate: "ca"
I1108 16:27:13.824732   20563 s3fs.go:110] Writing file "s3://briefy-stg-kubernetes/briefy-kube-stg/pki/issued/ca/2948652745.crt"
I1108 16:27:13.824781   20563 s3fs.go:130] Calling S3 PutObject Bucket="briefy-stg-kubernetes" Key="briefy-kube-stg/pki/issued/ca/2948652745.crt" SSE="AES256" ACL="" BodyLen=1220
I1108 16:27:13.854201   20563 s3fs.go:173] Reading file "s3://briefy-stg-kubernetes/briefy-kube-stg/pki/issued/ca/2948652745.crt"
I1108 16:27:13.872788   20563 ca.go:377] Parsing pem block: "CERTIFICATE"
I1108 16:27:13.873372   20563 populate_instancegroup_spec.go:217] Cannot set default Image for CloudProvider="aws"
I1108 16:27:13.873442   20563 populate_instancegroup_spec.go:217] Cannot set default Image for CloudProvider="aws"

Spec.KubernetesVersion: Required value

* What you expected to happen:
I would expect to import the cluster configuration following the documentation:

 - https://github.com/kubernetes/kops/blob/master/docs/cluster_upgrades_and_migrations.md

* If is not supported to migrate from 1.3 how can I migrate to 1.4 to use kops from there.

Thank you very much!

**Comment by geojaz** [comment]
@rudaporto kops 1.7.1 is intended to be used for kubernetes versions >1.6. 

I can understand why you want to upgrade- 1.3 was released over a year ago and hasn't been maintained for quite awhile. But neither has 1.4. I think your best bet to begin managing your cluster with kops is to pick a version >= 1.6 and stand it up alongside your current cluster. Then migrate your services and apps. When you have verified that it's functional- turn down the 1.3 cluster. 

I strongly recommend making the jump to at least the 1.6 series in this way. I think the time invested in migrating version to version with the risk of something going seriously wrong at any point along that journey is significantly greater than the amount of time to do update any manifests that need to be updated and make a clean break with the past. 

Closing this because we're not going back to support this. But if you want help with setting up a second cluster and updating manifests to the current versions, please visit the #kops channel in k8s slack. Thanks!

**Comment by rudaporto** [comment]
Thanks @geojaz ! I will create a new cluster and migrate all services to it.
