### ISSUE TITLE
Ability to tweak DHCP Options sets in AWS

### ISSUE THREAD

**Issue by iostat** [kubernetes/kops#3801]
Hi all!

We're running a cluster in AWS, and within that cluster we have an internal docker registry which serves most of the containers we use. We use the cluster-internal DNS to reference containers (i.e., `docker.ns.svc.cluster.local/foo/bar:baz`)  It almost works out of the box, except that we manually have to modify the DHCP options set for the VPC that Kops created so that it adds the `kube-dns` service's cluster IP address as a DNS server, in addition to `AmazonProvidedDNS`. (Otherwise, the docker instance on the hosts can't resolve the registry.) And of course, every time we run `kops update cluster`, it wants to change the DHCP options set back to the one it created when we spun up the cluster, which means we have to be a little careful around doing changes to the cluster spec to avoid newly spawned nodes being unable to resolve the registry (as they wouldn't be aware of `kube-dns` as a DNS server to resolve `.svc.cluster.local` addresses). 

It'd be great if there was a way to either specify `extraDNSServers` somewhere in the cluster spec or even just to simply disable the VPC DHCP Options check when running `kops update cluster`

Cheers!

**Comment by cdaniluk** [comment]
This issue is maddening for use cases where you need to have a custom option set..

**Comment by Danpiel** [comment]
In my use case, I need to add additional DNS server from LDAP, to allow resolution of private IP ranges in peered vpc, the reliable and fast way to do it is via DHCP options of the VPC.
