### ISSUE TITLE
How do I run custom script during host initialization 

### ISSUE THREAD

**Issue by rp-happiestbaby** [kubernetes/kops#3804]
Hi,
Im running kops k8s cluster in AWS. Node servers are in autoscale group
I need to tune sysctl etc ...
So I need to run script when host is booting up, 
How I give kops script so it will create instance with custom data script?

**Comment by justinsb** [comment]
The best way is with a daemonset or with a hook

We have two hook examples  https://github.com/kubernetes/kops/tree/master/hooks  , but we should probably put one together for sysctls.

A privileged daemonset is probably easier though, but again we probably need an example.

**Comment by alvgarvilla** [comment]
Hi would like to do something similar, but just add some entries to the hosts file in every node in the cluster. How could I achieve that? Thanks!
