### ISSUE TITLE
Bare metal / supply SSH information

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kops#381]
Any way to setup a k8s cluster through _bare-metal_, without the need of specifying a cloud-provider? Aka similar to what https://github.com/skippbox/kmachine is trying to do (although they are at the moment only able to create a single node)

Or perhaps a feature in the future ^^

**Comment by justinsb** [comment]
I want to do this, but to be honest it is going to be much more of a priority to run on GCE & AWS first.  The biggest challenge as I see it is figuring out how to run etcd reliably, though I hear CoreOS might be releasing something soon which will make etcd a bit easier to manage...

**Comment by WillemMali** [comment]
I'd like to offer one of my VPS's for testing for at least 6 months, I currently have two unused VPS's with 8GB ram and 2vCPU's at SSDNodes that are catching dust. Let me know if that would come in handy.

**Comment by kevinchiu** [comment]
I'm also curious as to how to run this on our own bare-metal datacenter.

**Comment by andrenth** [comment]
Bare metal is listed in the ROADMAP for 1.7... were there new developments in this area?

**Comment by chrislovecnm** [comment]
@andrenth we have a WIP PR, but support did not make it into 1.7.0. 

@justinsb any ideas on ETA?

**Comment by justinsb** [comment]
Going to start PRing the WIP so we can get it merged, starting with https://github.com/kubernetes/kops/pull/3291

**Comment by andrenth** [comment]
Thanks, I'll keep an eye on it.

**Comment by cdrage** [comment]
@justinsb I've been trying to use baremetal support but was unable to find any documentation, mind helping me out with the steps I can use to configure it and I could possibly contribute a bit for documentation?

**Comment by cdrage** [comment]
I have a feeling that `kubeadm` has "replaced" this bare-metal integration :+1: But `kops` is still excellent for AWS / GKE!
