### ISSUE TITLE
Improve documentation (Readme) to include version matrix

### ISSUE THREAD

**Issue by Nitecon** [kubernetes/kops#3813]
1. What kops version are you running? use `kops version`
`Version 1.6.0 (git-f69a313ce)`

2. What Kubernetes version are you running? use `kubectl version`
`GitVersion:"v1.7.8`

3. What cloud provider are you using?
AWS

4. What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?
`kops version`

5. What you expected to happen:
Documentation (readme) should show a matrix of tested / vetted / limit versions of associated kubernetes versions.  If we are to assume 1.6.0 can only properly maintain / install / upgrade 1.6.x versions then it should show it as such.  There is currently no documentation showing appropriate kops versions with the associated kubernetes versions.  Ideally `kops version` should report the version of kops including the kubernetes supported min and max versions, even if it's just 1 version.

6. How can we to reproduce it (as minimally and precisely as possible):
Ask a regular user with kops version 1.4 what version on kubernetes is appropriate, what is the minimum version it can upgrade and what is the maximum version it can upgrade to?

7. Anything else do we need to know:
Although docker versions are more tightly coupled with kubernetes having at least a mention of this would greatly increase stability at least from our testing with some services that use docker cmds inside kubernetes in our lower environments. This ask however is an absolute nice to have as it's up to the upstream service to provide that information in a more clear way.

**Comment by blakebarnett** [comment]
I think we should create a `kops channels` command that displays this info (and perhaps any other inventory/assets info that pertains to each)

**Comment by Nitecon** [comment]
@chrislovecnm i 100% agree it's very confusing when I'm trying to onboard new folks into kubernetes with kops.  Being behind the k8s project in version numbers and supported versions is not a big deal it's just really confusing when the readme shows `brew update && brew install kops`, so now as a new user you have kops but as a new user you don't know to look for...  What version you have nor do you know how that relates to k8s version.  You generally only figure this out after you've upgraded your cluster a few times.

**Comment by chrislovecnm** [comment]
> Lastly the assumption that I see from most folks is when they get kops installed they assume it's going to be the latest stable version of kubernetes which will almost never be the case, so that adds additional confusion.

Well, that is debatable.  The channels file is probably not updated enough, but stable is burned in the version of k8s in production.  Usually, @justinsb and I recommend versions that running in production.  Also never run the latest :)

**Comment by chrislovecnm** [comment]
@Nitecon / @blakebarnett how is
https://github.com/kubernetes/kops/pull/3818/files#diff-04c6e90faac2675aa89e2176d2eec7d8R62

**Comment by chrislovecnm** [comment]
Closing done
