### ISSUE TITLE
windows binary testing

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3816]
kops will now cross compile on windows, but we need TESTERS!!  I am not certain it will build on windows, but it will build in Linux container.

let me know if you are able to assist!

**Comment by justinsb** [comment]
Aren't there a few places where we path.Join ?

**Comment by chrislovecnm** [comment]
Yes ... boostrapchannelbuilder is the one area that makes me nervous, but I do not know how go bindata does the path lookup.

**Comment by prdoyle** [comment]
I'll plan to try it on Wednesday.  (Hack Night at the office.)

**Comment by chrislovecnm** [comment]
This is some of the main code I am concerned about https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/bootstrapchannelbuilder.go

All of the / instead of \ in windows.

**Comment by prdoyle** [comment]
Ok, I'd actually prefer to do it in Docker to be honest.  If that's your recommendation, I'm 100% good with that and might reneg on my offer to test it on Windows.  😅

**Comment by chrislovecnm** [comment]
Runs great in a container already ;)

**Comment by vyletpet** [comment]
I am able to help with testing but I am not able to build it. Can you provide me with binaries?

**Comment by chrislovecnm** [comment]
You have access to a Linux VM?

**Comment by vyletpet** [comment]
I have tried to build it in Docker container. But I do not have a Linux VM as such. If I do have I will probably use kops directly from there = no need for kops for win.

**Comment by RobertDiebels** [comment]
@chrislovecnm If you tell me what the steps are to build I'd be willing to test the binary.

**Comment by chrislovecnm** [comment]
The dev documentation has the instructions for building the binary, and it should be built with the base make command.

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/blob/master/docs/development/building.md is the documentation for building kops.

`make` will create the kops binaries under:
`k8s.io/kops/.build/dist/windows/amd64/kops.exe`

**Comment by chrislovecnm** [comment]
The full makefile most likely will not work on windows platform as it runs Linux containers, but just the base `make` target should run ok ... Let us know!

**Comment by RobertDiebels** [comment]
@chrislovecnm I'll try to work on this somwhere next week. Will keep you posted.

**Comment by jordansissel** [comment]
Hello! I am interested in helping test.

I made some assumptions (cross compiling by default == false assumption).

After setting GOARCH=amd64 and GOOS=windows, I found `make` invoking `go install` which fails:

```
% GOARCH=amd64 GOOS=windows make
go install  -ldflags "-X k8s.io/kops.Version=1.8.1 -X k8s.io/kops.GitVersion=94ef2027b " k8s.io/kops/cmd/kops/
go install runtime/internal/sys: mkdir /usr/lib/golang/pkg/windows_amd64: permission denied
make: *** [Makefile:102: kops-install] Error 1
```

Per [this comment](https://github.com/golang/go/issues/14213#issuecomment-179491876), a workaround is to use `go build`, so I copy/pasted the above `go install ...` and replaced `install` with `build`:

```
% GOARCH=amd64 GOOS=windows go build  -ldflags "-X k8s.io/kops.Version=1.8.1 -X k8s.io/kops.GitVersion=94ef2027b " k8s.io/kops/cmd/kops/
% file kops.exe
kops.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

Successfully built. A brief test `kops -h` (on windows) shows the help output. I'll keep testing and report back as I am able.
