### ISSUE TITLE
Kops always tries to delete the main AWS route table for a cluster

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#3828]
Kops verison: `1.8.0-beta.1`
K8s version: `1.7.x - 1.8.x`

If a routing table is tagged as `kubernetes.io/cluster/<cluster name>: shared`, kops should ignore it when deleting the cluster.  Currently if you tag all subnets and NAT gateways as shared this way it ignores the route tables associated with them but still attempts to delete the single route table with the name that matches the cluster no matter how it's tagged.

**Comment by georgebuckerfield** [comment]
I'm up for working on this unless someone else has taken it on.

**Comment by blakebarnett** [comment]
Go for it, 1st PR wins :)
