### ISSUE TITLE
Error configuring RBAC: resource already exists

### ISSUE THREAD

**Issue by pracucci** [kubernetes/kops#3852]
Hi, we just deployed a cluster with kops 1.6.2 and authentication mode RBAC, and we noticed that the masters are continuously logging the following two messages:

```
Nov 14 16:07:05 ip-x-x-x-x docker[1243]: W1114 16:07:05.410807       1 rbac.go:44] Error configuring RBAC: error creating service accounts: serviceaccounts "kube-dns" already exists
Nov 14 16:07:05 ip-x-x-x-x docker[1243]: W1114 16:07:05.410823       1 rbac.go:44] Error configuring RBAC: error creating cluster role bindings: clusterrolebindings.rbac.authorization.k8s.io "kubeadm:kubelet-bootstrap" already exists
```

Are you aware of any way to fix it, while running K8S 1.6.x?

---

- kops version: `1.6.2`
- kubernetes version: `1.6.6`
- provider: AWS

**Comment by KashifSaadat** [comment]
Hi @pracucci, please can you try with the following versions and let us know if you're still having the issue:
- kops: `v1.8.0-beta.1`
- kubernetes: `v1.6.6`

Is there any particular reason why you're running on K8s 1.6?

**Comment by pracucci** [comment]
Thanks @KashifSaadat for the reply. The only reason why we're still running on K8S 1.6 is because we run in a limited-resources team, and just need to allocate some time to upgrade it. Anyway, I understand a bug report on such an old kops version is hard to take in consideration, so I'm going to close it and I will re-open it if it will happen with the latest kops too.

**Comment by KashifSaadat** [comment]
No worries, let me know how it goes. :)
