### ISSUE TITLE
AWS Internal ELB Service with Warning msgs after upgraded kops 1.7.1 (k8s 1.7.7) -->  1.8.0-beta.1 (k8s 1.7.10)

### ISSUE THREAD

**Issue by gabrieladt** [kubernetes/kops#3861]
Thanks for submitting an issue! 

-------------BUG REPORT --------------------
1. Fill in as much of the template below as you can. 

2. What kops version are you running? use `kops version`
Version 1.8.0-beta.1 (git-9b71713)

3. What Kubernetes version are you running? use `kubectl version`
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T19:05:56Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T16:31:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

4. What cloud provider are you using?
AWS

5. What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?
N/A

6. What you expected to happen:
I don't know exactly how critical its, nothing stopped to work, but anyway.

I migrated from kops 1.7.1 (k8s 1.7.7) to 1.8.0-beta.1 (k8s 1.7.10), everything its ok except tor this Warning there its appearing on internal elb services.
```
7m         16h       193       pgadmin-ap                        Service                                                                Warning   CreatingLoadBalancerFailed   service-controller                                         (combined from similar events): Error creating load balancer (will retry): Failed to create load balancer for service default/pgadmin-ap: error detaching AWS loadbalancer from subnets: InvalidConfigurationRequest: Requested configuration change for LoadBalancer "aa6d0b12688c711e7a16d063b89fb882" is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC.
           status code: 409, request id: 3e1cf526-ca0d-11e7-8b7b-31173ef8abbb
6m         6m        1         pgadmin-ap   Service                Normal    DeletingLoadBalancer   service-controller      Deleting load balancer
5m         5m        1         pgadmin-ap   Service                Normal    DeletedLoadBalancer    service-controller      Deleted load balancer
2m         4m        3         pgadmin-ap   Service                Normal    CreatingLoadBalancer   service-controller      Creating load balancer
4m         4m        1         pgadmin-ap   Deployment             Normal    ScalingReplicaSet      deployment-controller   Scaled down replica set pgadmin-ap-4139650275 to 0
4m         4m        1         pgadmin-ap   Deployment             Normal    ScalingReplicaSet      deployment-controller   Scaled up replica set pgadmin-ap-1385320398 to 1
2m         4m        3         pgadmin-ap   Service                Normal    CreatedLoadBalancer    service-controller      Created load balancer
```
The service itself, was working properly but I decided recreate the service again to check, and after this, the warning was gone.

```
get svc
kong-admin-elb                                10.230.15.97    internal-a428...   80:32297/TCP                 90d
kops-ing-nginx-ingress-controller-metrics     10.230.2.40     internal-ae65...   9913:31472/TCP               91d
kube-proxy-eu-internal-elb                    10.230.24.56    internal-a0e5...   80:31460/TCP                 90d
```
```
get events
4m         16h       197       kong-admin-elb   Service             Warning   CreatingLoadBalancerFailed   service-controller   (combined from similar events): Error creating load balancer (will retry): Failed to create load balancer for service default/kong-admin-elb: error detaching AWS loadbalancer from subnets: InvalidConfigurationRequest: Requested configuration change for LoadBalancer "BBBBBB" is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC.
4m         16h       197       kops-ing-nginx-ingress-controller-metrics   Service             Warning   CreatingLoadBalancerFailed   service-controller   (combined from similar events): Error creating load balancer (will retry): Failed to create load balancer for service default/kops-ing-nginx-ingress-controller-metrics: error detaching AWS loadbalancer from subnets: InvalidConfigurationRequest: Requested configuration change for LoadBalancer "AAAAAA" is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC.
4m         16h       197       kube-proxy-ap-internal-elb   Service             Warning   CreatingLoadBalancerFailed   service-controller   (combined from similar events): Error creating load balancer (will retry): Failed to create load balancer for service default/kube-proxy-ap-internal-elb: error detaching AWS loadbalancer from subnets: InvalidConfigurationRequest: Requested configuration change for LoadBalancer "CCCCCCC" is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC.
```

7. How can we to reproduce it (as minimally and precisely as possible):

8. Anything else do we need to know:

**Comment by chrislovecnm** [comment]
Can you provide some more details? You migrated? What did you do?

**Comment by gabrieladt** [comment]
Hi. 
Basically I upgraded

From:
Kops 1.7.1 running k8s 1.7.7 
To: 
kops 1.8.0-beta.1 and  k8s 1.7.10.

Executing
kops edit (changing 1.7.7 to 1.7.10)
kops update
kops rolling-update 

I did it on 3 different clusters qa, staging and production, and on all of them I had the same warning message related with k8s Services using Internal Elb, also, only happen for Internal ELB SVC (for our ingress elb for example, that its External (internet facing) nothing happen), when I execute get-events.

The warning msg was:

"Error creating load balancer (will retry): Failed to create load balancer for service default/pgadmin-ap: error detaching AWS loadbalancer from subnets: InvalidConfigurationRequest: Requested configuration change for LoadBalancer "aa6d0b12688c711e7a16d063b89fb882" is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC"

'''
7m         16h       193       pgadmin-ap                        Service                                                                Warning   CreatingLoadBalancerFailed   service-controller                                         (combined from similar events): Error creating load balancer (will retry): Failed to create load balancer for service default/pgadmin-ap: error detaching AWS loadbalancer from subnets: InvalidConfigurationRequest: Requested configuration change for LoadBalancer "aa6d0b12688c711e7a16d063b89fb882" is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC. '''

As I said, nothing stopped to work, the internal elbs svc were running ok, but as a precaution and to remove the noise (k8s events), I decided remove the internal elbs svc(s) and recreate again.
After this the warning was gone.

Subnet Tags
utility-ap-southeast-1a.k8s.cluster-ap.kops
Name
utility-ap-southeast-1a.k8s.cluster-ap.kops
AssociatedNatgateway
nat-xxxxx
KubernetesCluster
k8s.cluster-ap.kops
kubernetes.io/cluster/k8s.cluster-ap.kops
owned
kubernetes.io/role/elb
1

utility-ap-southeast-1b.k8s.cluster-ap.kops
Name
utility-ap-southeast-1b.k8s.cluster-ap.kops
AssociatedNatgateway
nat-xxxxxxx
KubernetesCluster
k8s.cluster-ap.kops
kubernetes.io/cluster/k8s.cluster-ap.kops
owned
kubernetes.io/role/elb
1


ap-southeast-1a.k8s.cluster-ap.kops
Name
ap-southeast-1a.k8s.cluster-ap.kops
KubernetesCluster
k8s.cluster-ap.kops
kubernetes.io/cluster/k8s.cluster-ap.kops
owned
kubernetes.io/role/internal-elb
1

ap-southeast-1b.k8s.cluster-ap.kops
Name
ap-southeast-1b.k8s.cluster-ap.kops
KubernetesCluster
k8s.cluster-ap.kops
kubernetes.io/cluster/k8s.cluster-ap.kops
owned
kubernetes.io/role/internal-elb
1

**Comment by Shemeikka** [comment]
Hi,

I'm seeing this same warning with two of my services which internal ELB. Both of those services are working just fine.

Can confirm that after deleting and recreating these services, those warnings went away.

I didn't upgrade, I created a new kubernetes cluster using versions:

- kops: 1.7.0
- k8s: 1.7.8

I'm using private dns with private topology. I also have a public route 53 zone which has same domain name as the internal zone's domain.

```
# kubectl get events
LASTSEEN   FIRSTSEEN   COUNT     NAME          KIND      SUBOBJECT   TYPE      REASON                       SOURCE               MESSAGE
40s        18h         226       mailservice   Service               Normal    CreatingLoadBalancer         service-controller   Creating load balancer
39s        18h         217       mailservice   Service               Warning   CreatingLoadBalancerFailed   service-controller   (combined from similar events): Error creating load balancer (will retry): Failed to create load balancer for service default/mailservice: error detaching AWS loadbalancer from subnets: InvalidConfigurationRequest: Requested configuration change for LoadBalancer "xxxxxx" is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC.
           status code: 409, request id: xxxxxx
```

```
# kubectl describe service mailservice
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason				Message
  ---------	--------	-----	----			-------------	--------	------				-------
  18h		2m		226	service-controller			Normal		CreatingLoadBalancer		Creating load balancer
  18h		2m		217	service-controller			Warning		CreatingLoadBalancerFailed	(combined from similar events): Error creating load balancer (will retry): Failed to create load balancer for service default/mailservice: error detaching AWS loadbalancer from subnets: InvalidConfigurationRequest: Requested configuration change for LoadBalancer "xxxxxx" is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC.
		status code: 409, request id: xx-xx-xx-xx-xx
```

The service yaml is
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: mailservice
  name: mailservice
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    dns.alpha.kubernetes.io/internal: mailservice.internal-domain.internal
spec:
  selector:
    name: mailservice
  type: LoadBalancer
  ports:
  - protocol: TCP    
    port: 25
    targetPort: 25
    nodePort:
```

**Comment by chrislovecnm** [comment]
@justinsb is this upstream issue?

**Comment by Shemeikka** [comment]
Hi,

Any updates on this? This happens at least every time I do a rolling-update cluster and this only affects internal load balancers.

**Comment by blakebarnett** [comment]
I think this is an upstream cloud-provider issue, it's something to do with detecting all the AZs that an ELB has subnets in between 1.8 and 1.9, once all the nodes are upgraded it stops happening AFAICT.

**Comment by chrislovecnm** [comment]
@blakebarnett any ideas?  Have you found an open issue upstream?

**Comment by blakebarnett** [comment]
This started happening every time we do a rolling-update with 1.8, I haven't seen it cause any issues, it retries and works once all the masters are up.

**Comment by blakebarnett** [comment]
This shouldn't be a release blocker AFAICT
