### ISSUE TITLE
kops creates two CA certificates which breaks certificate-controller from signing certs.

### ISSUE THREAD

**Issue by zachaller** [kubernetes/kops#3875]
What kops version are you running? use `kops version`
master

What Kubernetes version are you running? use `kubectl version`
1.8.3

What cloud provider are you using?
AWS

What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?
kubectl get csr _csr_request_

What you expected to happen:
I excpected to get a certificat in .status.certificate

How can we to reproduce it (as minimally and precisely as possible):
By following the directions here https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/ 

Anything else do we need to know:

I have tracked this down to kops creating two certificates in /srv/kuberentes/ca.crt it also creates two certificate and private key files in the s3 bucket at locations /pki/issued/ca and /pki/private/ca. I have been able to get kubernetes to sign certificates by quickly deleting one of the files from the bucket while creating a new cluster so that they only get one certificate.

Here is an error from controller-manager
```
I1116 16:09:47.033806       5 controller_utils.go:1019] Waiting for caches to sync for persistent volume controller
I1116 16:09:47.284974       5 controllermanager.go:488] Started "endpoint"
I1116 16:09:47.284997       5 controllermanager.go:478] Starting "csrsigning"
I1116 16:09:47.285063       5 endpoints_controller.go:153] Starting endpoint controller
I1116 16:09:47.285077       5 controller_utils.go:1019] Waiting for caches to sync for endpoint controller
E1116 16:09:47.425756       5 certificates.go:49] Failed to start certificate controller: error parsing CA cert file "/srv/kubernetes/ca.crt": {"code":1003,"message":"the PEM file should contain only one object"}
W1116 16:09:47.425778       5 controllermanager.go:485] Skipping "csrsigning"
I1116 16:09:47.425786       5 controllermanager.go:478] Starting "service"
I1116 16:09:47.683734       5 controllermanager.go:488] Started "service"
```

```
cat /srv/kubernetes/ca.crt
-----BEGIN CERTIFICATE-----
MIIC0zCCAbugAwIBAgIMFPecowJWaxgTWcRdMA0GCSqGSIb3DQEBCwUAMBUxEzAR
BgNVBAMTCmt1YmVybmV0ZXMwHhcNMTcxMTE0MTYwNzAzWhcNMjcxMTE0MTYwNzAz
WjAVMRMwEQYDVQQDEwprdWJlcm5ldGVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAyRr0AKsEOqYCI6gHg0kgcAauus9nA+Z/pn4bVL+i21/L8q7EjxVf
yX3v3lz2627s2GBDquVoT2LG7gicKIOTUNMmMop1vMasdZ16xUauN0nB9Z9E60Oy
2g+L9xFqDXyUJ+S4A8EbY19DV5G5M0rb/XL2pzSTe+uOOEjEf2e2kQSjOnPugZpo
MLSLkHeyFTVYlCrF85HxsdAAlXglKJ3ZDT3wP1qZ5a/02TutrHhgBRoWjmWqpTr8
MPduBFAG/6b+56+XuXior7TKhT1Lsulw3wCwKrXMIXViRqdV96w6yuiolgRx1+Y6
PyhXANF8sb/t0GLgPVECpyPcxXDBozFFxQIDAQABoyMwITAOBgNVHQ8BAf8EBAMC
AQYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEASYzBLpHuMlxl
E5i3feVYZnlxyHI1mdY+pzRUEp43V7gA7amYRlmNwHfGbCv0faNZc9TXlKf2QDjx
GnQ+aPeNDbbjmviRMDX2/1JnUkeZ1Um6ZZ/CN63p9EBh+RcUa9zhqhIzTbqspNW8
SzlgnIeSbOEJ5iTCawm3x9EkGPNVIKOeqdTSPzsy0QRb9odO2RcyW1gLeiVImwPt
cH+DfyENZGQlgb8Ez23zCiXiWVthervoOaFsXiA3PK6D6mQFZphzdKJi2XmrVbuw
r6GfMmcArIzzvAnu4gXYPLO94ylYfY/gecxsKWpXx1Gw+cCVtOEv0dhluRkpi26c
lW4r0bX7EA==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIC2DCCAcCgAwIBAgIRAPDTW6ueFfuNmGemU9bsK1QwDQYJKoZIhvcNAQELBQAw
FTETMBEGA1UEAxMKa3ViZXJuZXRlczAeFw0xNzExMTQxNjA3MDNaFw0yNzExMTQx
NjA3MDNaMBUxEzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDJGvQAqwQ6pgIjqAeDSSBwBq66z2cD5n+mfhtUv6LbX8vy
rsSPFV/Jfe/eXPbrbuzYYEOq5WhPYsbuCJwog5NQ0yYyinW8xqx1nXrFRq43ScH1
n0TrQ7LaD4v3EWoNfJQn5LgDwRtjX0NXkbkzStv9cvanNJN76444SMR/Z7aRBKM6
c+6BmmgwtIuQd7IVNViUKsXzkfGx0ACVeCUondkNPfA/Wpnlr/TZO62seGAFGhaO
ZaqlOvww924EUAb/pv7nr5e5eKivtMqFPUuy6XDfALAqtcwhdWJGp1X3rDrK6KiW
BHHX5jo/KFcA0Xyxv+3QYuA9UQKnI9zFcMGjMUXFAgMBAAGjIzAhMA4GA1UdDwEB
/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAGhKKc
DpE7L1Qu/SZIdctVW4EfVJ49uxUzklDOm13yrAKLForlcwVHnGhXNDfRo//clovM
BGKhZST7O9/L3I1m+mBgPOqBJ4NW4oyr53IOZun6cv6tcIYSWV9xoOHNFX8Nw9ty
FHsXDSpNu9ogGM06XcKnVp9sfcH8TywSzPTPM2f8UpXmyhIOx5yp9PjZh038u528
+EInpZ28H1wwffz5+vAfuv85AZ9LVeZR2s2uJThE0TlX4qyCwH0PlJzXbN9YyO7/
NrR5qdbughkMlY6BweXobVQ6qwvO4JmZIpsRJmzDNwSuc85kT42fHrAvfcL3O4EM
T/02GeBfmKqMDPQG
-----END CERTIFICATE-----
```

![screen shot 2017-11-16 at 11 01 13 am](https://user-images.githubusercontent.com/201390/32905064-929f7f2c-cabe-11e7-8a57-c620c964c3fc.png)
![screen shot 2017-11-16 at 11 02 19 am](https://user-images.githubusercontent.com/201390/32905071-97dd2e4e-cabe-11e7-8255-6170b869c660.png)

**Comment by justinsb** [comment]
So we definitely have an issue here where having two CA certs shouldn't block the CSR controller.

But as to why you're triggering that issue...  There are legitimate cases where we will have multiple CA keys & certs (rotating the CA key), but it doesn't sound like we're in that case.  Do you have any idea why the second cert/key is being created @zachaller ?    There may be a hint in the logs or in `kops update`, but I'm guessing the names are changing somehow?

**Comment by zachaller** [comment]
This is happening on creating a new cluster. It dose not seem to break anything from stoping the cluster to start so what I have been doing is creating a new cluster letting it come up go into s3 bucket delete extra certs for ca then running kops update and then force a rolling update. This then allows the csr controller to start normally.

**Comment by mikn** [comment]
Can we close it with @justinsb 's commit referenced here? Or is it just part of the solution? I've tested the "fix" @zachaller mentions and it seems to work just fine. :)

**Comment by zachaller** [comment]
I also just tested the fix with a new cluster and its working great.

**Comment by justinsb** [comment]
I'm actually going to keep this open, but it's not necessarily a blocker for kops 1.8... we shouldn't have been generating two certificates (it's how we do rotation), but in theory it's a valid configuration, and we need to only expose the primary to k-c-m.

**Comment by justinsb** [comment]
But thanks for confirming that the fix worked @zachaller :+1:

**Comment by chrislovecnm** [comment]
Moving to 1.9 blocks next

**Comment by jacobrandall** [comment]
Any chance we can get a quick confirmation on the work around for those hitting this issue? From what I can tell, if you already have a cluster up you need to delete either first or second certificate, and the matching key (first or second) from the following locations leaving only one certificate and key in each.

s3://${KOPS_STATE_STORE}/${CLUSTER}/pki/issued/ca
s3://${KOPS_STATE_STORE}/${CLUSTER}/pki/private/ca

Then perform a rolling-update.

**Comment by mikn** [comment]
That's correct. But you can also go on the master(s) and delete it, then restart the controller-manager. :)

**Comment by jacobrandall** [comment]
@mikn cool thanks, btw only had this issue on the cluster I created in AWS, the one I created in GCE only had one cert / key.

**Comment by blakebarnett** [comment]
This doesn't seem like a release blocker right?  There are work-arounds and it doesn't seem to hurt anything after 1.8 (or is that not true?)

**Comment by polarbizzle** [comment]
I've just run an update with the latest and what I've noticed is that the upgrade from legacy to the new bundle cert leaves the old cert adds an identical but differently name .crt and also the new bundle that refers to both of the certs.
This causes the kube-controller-manager pods to fail:

    I0320 21:56:16.970229       1 controller_utils.go:1019] Waiting for caches to sync for persistent volume controller
    E0320 21:56:16.999562       1 controllermanager.go:486] Error starting "csrsigning"
    F0320 21:56:16.999740       1 controllermanager.go:155] error starting controllers: failed to start certificate controller: error parsing CA cert file "/srv/kubernetes/ca.crt": {"code":1003,"message":"the PEM file should contain only one object"}


 It seems to me that the new identical cert isn't necessary? or the old cert could be deleted? Here's the logs that resulted in the duplicate CAs:

    I0320 18:36:36.065362     149 s3fs.go:198] Reading file "s3://bucket/cluster/pki/private/apiserver-aggregator-ca/keyset.yaml"
    I0320 18:36:36.066252     149 vfs_castore.go:384] no certificate bundle "s3://bucket/cluster/pki/issued/ca/keyset.yaml", falling back to directory-list method
    I0320 18:36:36.066498     149 s3fs.go:235] Listing objects in S3 bucket "bucket" with prefix "cluster/pki/issued/ca/"
    I0320 18:36:36.173172     149 s3fs.go:261] Listed files in s3://bucket/cluster/pki/issued/ca: [s3://bucket/cluster/pki/issued/ca/6462752579299364592863941596.crt]
    I0320 18:36:36.173491     149 s3fs.go:198] Reading file "s3://bucket/cluster/pki/issued/ca/6462752579299364592863941596.crt"
    I0320 18:36:36.277757     149 s3fs.go:198] Reading file "s3://bucket/cluster/pki/issued/ca/keyset.yaml"
    I0320 18:36:36.390241     149 vfs_castore.go:384] no certificate bundle "s3://bucket/cluster/pki/issued/ca/keyset.yaml", falling back to directory-list method
    I0320 18:36:36.390542     149 s3fs.go:235] Listing objects in S3 bucket "bucket" with prefix "cluster/pki/issued/ca/"
    I0320 18:36:36.504816     149 s3fs.go:261] Listed files in s3://bucket/cluster/pki/issued/ca: [s3://bucket/cluster/pki/issued/ca/6462752579299364592863941596.crt]
    I0320 18:36:36.505129     149 s3fs.go:198] Reading file "s3://bucket/cluster/pki/issued/ca/6462752579299364592863941596.crt"
    I0320 18:36:36.598323     149 s3fs.go:198] Reading file "s3://bucket/cluster/pki/private/ca/keyset.yaml"
    I0320 18:36:36.686829     149 vfs_castore.go:833] no private key bundle "s3://bucket/cluster/pki/private/ca/keyset.yaml", falling back to directory-list method
    I0320 18:36:36.687169     149 s3fs.go:235] Listing objects in S3 bucket "bucket" with prefix "cluster/pki/private/ca/"
    I0320 18:36:36.777189     149 s3fs.go:261] Listed files in s3://bucket/cluster/pki/private/ca: [s3://bucket/cluster/pki/private/ca/6462752579299364592863941596.key]
    I0320 18:36:36.777529     149 s3fs.go:198] Reading file "s3://bucket/cluster/pki/private/ca/6462752579299364592863941596.key"
    I0320 18:36:36.964574     149 changes.go:81] Field changed "Format" actual="legacy" expected="v1alpha2"
    I0320 18:36:36.965036     149 keypair.go:183] creating certificate as changes are not nil
    I0320 18:36:36.965253     149 s3fs.go:198] Reading file "s3://bucket/cluster/pki/issued/ca/keyset.yaml"
    I0320 18:36:37.051591     149 vfs_castore.go:384] no certificate bundle "s3://bucket/cluster/pki/issued/ca/keyset.yaml", falling back to directory-list method
    I0320 18:36:37.051931     149 s3fs.go:235] Listing objects in S3 bucket "bucket" with prefix "cluster/pki/issued/ca/"
    I0320 18:36:37.407441     149 s3fs.go:261] Listed files in s3://bucket/cluster/pki/issued/ca: [s3://bucket/cluster/pki/issued/ca/6462752579299364592863941596.crt]
    I0320 18:36:37.407719     149 s3fs.go:198] Reading file "s3://bucket/cluster/pki/issued/ca/6462752579299364592863941596.crt"
    I0320 18:36:37.750006     149 s3fs.go:235] Listing objects in S3 bucket "bucket" with prefix "cluster/pki/private/ca/"
    I0320 18:36:37.847126     149 s3fs.go:261] Listed files in s3://bucket/cluster/pki/private/ca: [s3://bucket/cluster/pki/private/ca/6462752579299364592863941596.key]
    I0320 18:36:37.847395     149 s3fs.go:198] Reading file "s3://bucket/cluster/pki/private/ca/6462752579299364592863941596.key"
    I0320 18:36:38.531944     149 s3fs.go:118] Writing file "s3://bucket/cluster/pki/private/ca/keyset.yaml"
    I0320 18:36:38.532265     149 s3fs.go:144] Calling S3 PutObject Bucket="bucket" Key="cluster/pki/private/ca/keyset.yaml" SSE="AES256" ACL=""
    I0320 18:36:38.632169     149 s3fs.go:118] Writing file "s3://bucket/cluster/pki/private/ca/205176986633669307021451105104542018752.key"
    I0320 18:36:38.632426     149 s3fs.go:144] Calling S3 PutObject Bucket="bucket" Key="cluster/pki/private/ca/205176986633669307021451105104542018752.key" SSE="AES256" ACL=""
    I0320 18:36:38.727333     149 s3fs.go:235] Listing objects in S3 bucket "bucket" with prefix "cluster/pki/issued/ca/"
    I0320 18:36:38.820069     149 s3fs.go:261] Listed files in s3://bucket/cluster/pki/issued/ca: [s3://bucket/cluster/pki/issued/ca/6462752579299364592863941596.crt]
    I0320 18:36:38.820336     149 s3fs.go:198] Reading file "s3://bucket/cluster/pki/issued/ca/6462752579299364592863941596.crt"
    I0320 18:36:38.914959     149 s3fs.go:118] Writing file "s3://bucket/cluster/pki/issued/ca/keyset.yaml"
    I0320 18:36:38.915276     149 s3fs.go:144] Calling S3 PutObject Bucket="bucket" Key="cluster/pki/issued/ca/keyset.yaml" SSE="AES256" ACL=""
    I0320 18:36:39.009170     149 s3fs.go:118] Writing file "s3://bucket/cluster/pki/issued/ca/205176986633669307021451105104542018752.crt"
    I0320 18:36:39.009500     149 s3fs.go:144] Calling S3 PutObject Bucket="bucket" Key="cluster/pki/issued/ca/205176986633669307021451105104542018752.crt" SSE="AES256" ACL=""
    I0320 18:36:39.103711     149 keypair.go:247] updated Keypair "ca" to API format "v1alpha2"

Reading through the code, I'm thinking we should make it so that if a bundle has multiple certs listed, then we should just take the primary and put it in `/srv/kubernetes/ca.crt`

That would mean changing [this](https://github.com/kubernetes/kops/blob/173bafb6ba18d51f955351bc0de2214b58049eb9/nodeup/pkg/model/secrets.go#L53)  to :

    serialized, err := ca.Primary.AsString()

Or perhaps we could make another primary only .crt file that could be used in the controller manager something like `/srv/kubernetes/ca-primary.crt`


I'll make a PR

**Comment by blakebarnett** [comment]
Just saw this using kops 1.9.0-beta.2
