### ISSUE TITLE
kops create secret no longer required

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3882]
Thanks for submitting an issue! 

-------------BUG REPORT --------------------

1. What kops version are you running? use `kops version`

HEAD ... PR branch - but not messing with that code

2. What Kubernetes version are you running? use `kubectl version`

k8s 1.8

3. What cloud provider are you using?

Seen in aws and gce

4.  What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?

```
KOPS=kops
$KOPS create -f $KOPS_FILE
# you do not have to do this now :)
$KOPS create secret --name $CLUSTER_NAME sshpublickey admin -i ~/.ssh/id_rsa.pub
$KOPS update cluster $CLUSTER_NAME --yes
```

You do not have to do 
```
$KOPS create secret --name $CLUSTER_NAME sshpublickey admin -i ~/.ssh/id_rsa.pub
```

Anymore 

5. What you expected to happen:

You would need to explicitly set the ssh key.

6. How can we to reproduce it (as minimally and precisely as possible):

Get a YAML file, and run the above.

7. Anything else do we need to know:

**Comment by justinsb** [comment]
I don't think this would block the release - would it @chrislovecnm ?

**Comment by chrislovecnm** [comment]
We need release notes. Are we expecting this behavior now?

**Comment by metametadata** [comment]
Is it not needed anymore because by default `kops update cluster` will use the key from `~/.ssh/id_rsa.pub`? The docs still have this step specified, e.g. see https://github.com/kubernetes/kops/blob/59440bbc6832d31a31bbbcf4869967795819fd63/docs/manifests_and_customizing_via_api.md.
