### ISSUE TITLE
Warn when master instance size is too small

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/kops#3896]
------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.
When creating or modifying a cluster, a user should be warned if they select a master that is too small.  For instance in AWS t2.micro and t2.small are certainly too small for masters.  t2.mediums and up should be fine.

2. Feel free to provide a design supporting your feature request.
We should consider testing the minimum instance size, and warn users attempting to go below it. We may also want to provide a simple suggested CPU and Memory target for masters, in case instance sizes change.

We should warn the user at `kops update cluster` that a given master size is too small. Warn to stdout.  It likely should be done here in this function

https://github.com/kubernetes/kops/blob/a25b5d7364343df53d2322b1ad03ece3c7bbe27b/cmd/kops/update_cluster.go#L115

**Comment by chrislovecnm** [comment]
@mikesplain I think we can run on micros now.  Thoughts?

**Comment by chrislovecnm** [comment]
1.8 we tweaked cni providers

**Comment by mikesplain** [comment]
Cool, I'll close this then @chrislovecnm.  Thanks!

/close
