### ISSUE TITLE
Better clarification on `--state` error

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kops#390]
To be honest, there's not much docs on examples on how to get kops up and running correctly, but I believe this error should be more intuitive to the user:

```
▶ kops create cluster foo
F0830 14:52:39.569104    5751 create_cluster.go:50] --state is required (or export KOPS_STATE_STORE)
```

**Comment by justinsb** [comment]
The primary section is this one: https://github.com/kubernetes/kops#bringing-up-a-cluster-on-aws

Though this has been pushed down in the readme a bit now by other docs, and I definitely agree the message should be better.

**Comment by chrislovecnm** [comment]
@cdrage does the current error work for you?

`Please set the --state flag, or `export KOPS_STATE_STORE=s3://<bucket>`

**Comment by kris-nova** [comment]
In general our handling should be more glamorous - I have an idea or two up my sleeve for `1.4.2` PR coming next week :)

**Comment by justinsb** [comment]
I believe this is fixed; this is what we have now:

```
> KOPS_STATE_STORE= kops get cluster

State Store: Required value: Please set the --state flag or export KOPS_STATE_STORE.
A valid value follows the format s3://<bucket>.
A s3 bucket is required to store cluster state information.
```

**Comment by justinsb** [comment]
Actually on second thoughts, reopening but marking as a docs issue.

**Comment by tsupertramp** [comment]
https://github.com/kubernetes/kops/blob/master/docs/aws.md#prepare-local-environment documents state store really good

cli on wrong s3 bucket:
"Please use a valid s3 bucket uri when setting --state or KOPS_STATE_STORE evn var.
A valid value follows the format s3://<bucket>."

cli on missing env:
"State Store: Required value: Please set the --state flag or export KOPS_STATE_STORE.
A valid value follows the format s3://<bucket>.
A s3 bucket is required to store cluster state information."

So from my point of view this can be closed :)

**Comment by cdrage** [comment]
@tsupertramp seems like it can be closed!
