### ISSUE TITLE
feature request: state distributed locking / mutex via AWS Dynamodb

### ISSUE THREAD

**Issue by GeoffMillerAZ** [kubernetes/kops#3903]
It would be nice to have the added piece of mind that the KOPS state file had mutual exclusion (mutex) protection via a distributed locking mechanism. DynamoDB is capable of being used in such a way and is used in terraform. Prior to Terraform officially adopting this feature, there was  terraform wrapper called terragrunt that implemented this feature. I have included the golang source code below for understanding of how this is accomplished. This feature would be really nice for any automation and/or CI/CD use cases for using KOPS

The process would be simply, if the state locking configuration in KOPS exists, then all reads/writes to the state file would be delayed until a successful check of the state locking table in dynamodb was performed. This guarantees that only one operator is able to manipulate the state file at a time and it prevents reads to a state file that is currently being changed.

Only write operations would lock the state file. Reads will not lock the state file but reads will not occur if the state file is locked.

All operations will retry for a default period of time in foo second intervals. A flag/configuration option could be added to allow for customization of the retry max time and the retry interval time.

There would need to be a command to force the unlock of a state file. If the user is confident that the state file is erroneously locked, they can forcefully unlock the state file. This could occur if an operation locked the state but then crashed before unlock.

User interrupts and detectable crashes need to try to gracefully exit by unlocking the state file.

**Terragrunt distributed locking / state mutex for terraform**
[link](https://github.com/gruntwork-io/terragrunt/blob/master/dynamodb/dynamo_lock_table.go
)
**Amazon Distributed Locking using DynamoDB**
[link](https://aws.amazon.com/blogs/database/building-distributed-locks-with-the-dynamodb-lock-client/)

**Comment by alexppg** [comment]
I'd love this feature to!
