### ISSUE TITLE
kops 1.8.0 release notes

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3905]
## Highlights

- Kubernetes 1.8 support
- IAM changes notes
- Beta GCE support /cc @justinsb is it Beta or full release?
- CNI provider upgrades
- Templating and dry-run manifest support
- ETCD3 support
- DNS Controller improvements

## Upgrading K8s to 1.8
- Canal Upgrades /cc @KashifSaadat 

## Breaking Changes
- Calico does not support gossip clusters only with k8s 1.6 and above

## Open issues
- etcd encryption /cc @gambol99 

/cc @blakebarnett @andrewsykim 

What are we missing??  I will PR this week.

**Comment by KashifSaadat** [comment]
@chrislovecnm has the upgrade path for Calico CNI been tested when moving from calico v2.4 to v2.5? I believe the upgrade steps will be the same as what was done for Canal (just difference in using etcd as the backend).

https://github.com/projectcalico/calico/tree/master/upgrade/v2.5#12-back-up-your-configuration-data

**Comment by chrislovecnm** [comment]
Another highlight - drain and validate rolling updates.

Api documentation as well

**Comment by chrislovecnm** [comment]
Bazel in alpha

**Comment by caseydavenport** [comment]
>  has the upgrade path for Calico CNI been tested when moving from calico v2.4 to v2.5? I believe the upgrade steps will be the same as what was done for Canal (just difference in using etcd as the backend).

@KashifSaadat those steps are only required when using Calico / canal with the Kubernetes API (CRD) datastore, which IIUC is not used in kops. For the etcd datastore, nothing special is requried when upgrading to v2.5+

**Comment by chrislovecnm** [comment]
We need to document that C5's do not support PVC volumes.

**Comment by chrislovecnm** [comment]
Closing - it is out
