### ISSUE TITLE
Question: Does Hooks work on Bastion servers? 

### ISSUE THREAD

**Issue by alexandrst88** [kubernetes/kops#3907]
Hi! I was trying to apply hook on the Bastion servers, but no success, does this bug or it's expected behavior?
kops version `1.8.0-beta`

**Comment by KashifSaadat** [comment]
Hi, nodeup isn't run on the bastion hosts so Hooks won't be applied.

@chrislovecnm do you think this is something we should cover?

**Comment by chrislovecnm** [comment]
@KashifSaadat I think is it is an enhancement request ... @alexandrst88??

We should document it though.

**Comment by alexandrst88** [comment]
@chrislovecnm, it is :)

**Comment by iMartyn** [comment]
+1 for this feature - If I can't install sssd on the bastion, it's no use as a bastion.

**Comment by ocnam** [comment]
Is this also true for [fileAssets](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#fileassets)? From the documentation it is alluded to that Bastions are supported, but not seeing files placed as they are with Master and Nodes.

kops 1.8.0

+1 for this as well.

**Comment by Cryptophobia** [comment]
/reopen

This would be a nice feature to have for bastion servers. Most bastions servers will need to have some ssh, sssd, or other network tools for connectivity...

**Comment by Cryptophobia** [comment]
@chrislovecnm , can you please reopen this and I will try to make a PR for this feature?
