### ISSUE TITLE
Question: how to show BGP status ?

### ISSUE THREAD

**Issue by vietwow** [kubernetes/kops#3915]
#Hi all,

I have deployed K8S v1.7 in AWS with different AZ Subnets using Kops v.1.7 with Calico CNI Networking option. I try to do some calicoctl command for debugging like : calicoctl get node, get ipPool, workloadEndpoint. Everything is ok

As I read some documents, K8S on AWS with calico networking using BGP (source : http://zcentric.com/post/2016-01-21-kubernetes-calico-aws-setup/)

But when I try command "calicoctl get bgpPeer", it returns "[]" (seems nothing)

When I try command "calicoctl node status", it returns : "Calico process is not running."

So how can I how BGP status ?

Thank you so much.

Best Regards,
VietNC

**Comment by chrislovecnm** [comment]
/cc @caseydavenport @blakebarnett 

I have cc’ed a couple of gurus, but I am guessing this is a calico issue, maybe the way our manifest is configured?
