### ISSUE TITLE
Kops generates subtly invalid ssl certificates

### ISSUE THREAD

**Issue by vainu-arto** [kubernetes/kops#3918]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.8.0-beta.1 (git-9b71713)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

--channel alpha --kubernetes-version 1.8.3

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

kops create cluster --bastion --dns private --topology private --node-count=2 --node-size=t2.micro --master-size=t2.micro --master-zones eu-west-1a --zones eu-west-1a --channel alpha --kubernetes-version 1.8.3 --authorization RBAC --networking calico kube18.test.int
kops update cluster --yes

5. What happened after the commands executed?

Cluster is created, but trying to access the api reports that the cert is invalid:

Gnutls says "The signature in the certificate is invalid."
Openssl says "error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01"

6. What did you expect to happen?

A correctly signed cert to have been generated.

I was doing this to test the new AdditionalSANs option but could not get that far..

**Comment by vainu-arto** [comment]
The issue is not affected by Kubernetes version, deploying 1.7 instead of 1.8 using kops 1.8.0-beta.1 hits the same bug.

**Comment by vainu-arto** [comment]
The issue still exists in current git master, Version 1.8.0-beta.1 (git-0a2f949fd99a).

**Comment by justinsb** [comment]
@vainu-arto can you share the commands you're using to validate the certificate?

Or can you possibly send me the certificate on the kubernetes slack (I'm justinsb)...

I'm wondering if you are hitting https://github.com/kubernetes/kops/issues/3875, but that should have been fixed in the master (hopefully)...

**Comment by vainu-arto** [comment]
@justinsb Simply running curl against the ELB address will return that error. Also either gnutls-cli or openssl s_client will return errors.

I deleted the broken test cluster already, so don't currently have a broken cert in hand (apparently I didn't save one anywhere).

**Comment by vainu-arto** [comment]
Hum. Bisecting this comes back with "all bad", including the version I previously used to create a cluster that is ok. How does the cert issuing work, is it actually done by something external to kops?

**Comment by vainu-arto** [comment]
No, it's not done by anything external. We had a lengthy debugging session with @chrislovecnm and found several datapoints:

* Openssl version 1.1.0f and versions before that accept the certs created by kops
* Openssl version 1.1.0g does not accept them
* No tested version of gnutls would accept them
* Firefox version 57 does not accept the certs

They are probably broken in a much more subtle way than I expected, and have probably always been broken that way (not a regression).

**Comment by chrislovecnm** [comment]
I create a kops cluster off of master and recreated the problems.  Newer openssl is not liking our certs.  I am thinking this is not a p0

Thoughts @justinsb?

**Comment by vainu-arto** [comment]
Hah. After all this work, it turns out to be a local issue. The tools get confused by having the CA of a current cluster installed on the system, and report weird errors when they expect that the certs created for new clusters would verify with the CA of a previous cluster.

Sorry about wasting your time here.
