### ISSUE TITLE
Confusing state message when deleting a created but not updated cluster

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#393]
Create a cluster:

```
kops create cluster --cloud=aws --name=bar.baz --state=<foo> --yes
```

Don't update it. Now try to delete it:

```
$ kops delete cluster --name=bar.baz --state=<foo>
No resources to delete

Must specify --yes to delete
```

It would be helpful to have a better message here that clarifies that even though there are no external resources to be deleted, the cluster config itself will be deleted.

**Comment by justinsb** [comment]
Agreed :-)
