### ISSUE TITLE
Exposing additional ports on bastion host.

### ISSUE THREAD

**Issue by lleszczu** [kubernetes/kops#3937]
I would like to setup OpenVPN server on the bastion host to securely access my network with private topology, unfortunately it seems that only port 22 is allowed (although with custom CIDR subnets).

Is it possible to add custom security groups to ELB and instance to support any TCP/UDP traffic?

**Comment by krogon-dp** [comment]
Did you tried with `additionalSecurityGroups` for InstanceGroupSpec ?
https://github.com/kubernetes/kops/blob/4e284e9966298b082d7b1b1468b83b14ccd4d541/pkg/apis/kops/v1alpha2/instancegroup.go#L90

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by lleszczu** [comment]
Unfortunately additionalSecurityGroups is attaching SG to instance instead of bastion's LB. I can simply bypass LB and connect directly to bastion, but in this case what's the point of LB in front of it?
