### ISSUE TITLE
Add more visibility into what resources kops will create

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#394]
Running `kops create` or `update` without `--yes` shows you the resources that kops will create, but only at a very high level. A small snippet:

```
LaunchConfiguration	launchConfiguration/master-us-east-1b.masters.mydomain.com
LaunchConfiguration	launchConfiguration/nodes.mydomain.com
AutoscalingGroup	autoscalingGroup/nodes.mydomain.com
AutoscalingGroup	autoscalingGroup/master-us-east-1b.masters.mydomain.com
```

This is missing a lot of information that I would like to know before I hit `--yes`, for instance the size of the instances, max/min number of instances, the size of the EBS volumes, etc.

**Comment by justinsb** [comment]
Good point.  Might not make 1.3.0, but I'll put it into the milestone with low priority.
