### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by dts** [kubernetes/kops#395]
How do I build this on my own machine?  `make` doesn't do anything seemingly meaningful, and `make nodeup-build-in-docker` doesn't seem to either...

I would like to make it check whether a subnet exists already (by CIDR) before creating one, but I can't compile & test my changes.

**Comment by dts** [comment]
It looks like the build things put stuff in the /.build/ (which I missed, oops), but I haven't figured out how to use the whole pile of code yet.

**Comment by dts** [comment]
This is the commit I want to test: https://github.com/dts/kops/commit/8b36cf040ba0ca821171c23077c676e2c53d4502

**Comment by chrislovecnm** [comment]
Are you trying to a new version of nodeup?  There are various pieces of software in this repo, and yes I agree the documentation needs to be improved a tad.

`make upload S3_BUCKET=s3://${S3_BUCKET_NAME}` is probably the command you are looking for.

**Comment by dts** [comment]
I'd prefer to use the exact same tools/commands that I am familiar with at the command line (i.e. `$GOPATH/bin/kops update name --yes`), I don't actually understand how the various pieces are connected...  Does kops update <blah> call nodeup?

**Comment by justinsb** [comment]
That's a local change - i.e. it happens purely in the kops tool that you run locally.  We don't need to worry about nodeup (which installs software onto the nodes), though there are docs coming for that too.

So `make` should build kops on your machine (just as you built it in the first place), in your ${GOPATH}/bin/, and your change should apply when you run kops.

Looking at the code though, you actually just need to make sure that the `Find` method will find your existing subnet: https://github.com/kubernetes/kops/blob/f757cc9def885e84d4f0e9077d5bc491f6335add/upup/pkg/fi/cloudup/awstasks/subnet.go#L29

And it should find it if you specify an ID: https://github.com/kubernetes/kops/blob/f757cc9def885e84d4f0e9077d5bc491f6335add/upup/pkg/fi/cloudup/awstasks/subnet.go#L34

And you can specify an ID by setting ProviderID on the zone: https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/_aws/network.yaml#L42

So you should just be able to `kops create cluster`, `kops edit cluster` and set a ProviderID on the zones (which really might be better named subnets), and then `kops update cluster` and it should just work.

But do be careful ... k8s will modify the routing table on your cluster.  It won't work if you have two k8s clusters in the same subnet.  And if you want to do any custom routing in the subnet other than k8s, that might also not work well with k8s either.

**Comment by dts** [comment]
I just need everything to be in the same VPC as my RDS instance.  I'll create new subnets for the three AZs, and try your providerID setting.  Just doing make didn't link everything the way I expected, should I uninstall the one on the gopath (I have the repo cloned separately).

**Comment by dts** [comment]
That worked, specifying the ProviderID / id on the subnets caused them to be reused and not recreated!

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by dts** [comment]
Yep.  Sorry to leave it dangling.
