### ISSUE TITLE
CoreDNS for cluster DNS

### ISSUE THREAD

**Issue by johnbelamaric** [kubernetes/kops#3951]
1. Describe IN DETAIL the feature/behavior/change you would like to see.

Implement the K8s 1.9 alpha feature: https://github.com/kubernetes/features/issues/427

2. Feel free to provide a design supporting your feature request.

**Comment by johnbelamaric** [comment]
cc @rajansandeep @fturib

**Comment by johnbelamaric** [comment]
See also: https://github.com/kubernetes/community/pull/1100

**Comment by chrislovecnm** [comment]
I have to mean to drop this in.  This is actually a great starter issue, which would help a person learn kops.

1.  add manifest to upup addons - it is just like the PRs for CNI providers
2. add API changes for user to select dns
3. test test test

**Comment by johnbelamaric** [comment]
Great! @rajansandeep is going to take a look.
