### ISSUE TITLE
Cannot add more entries to basic_auth.csv (AWS)

### ISSUE THREAD

**Issue by greggilbert** [kubernetes/kops#3955]
There's no way to add more users to `basic_auth.csv` and to have it persist through rolling updates. It's possible to awkwardly do this with tokens by creating single files in `secrets/` on S3 (see [this comment](https://github.com/kubernetes/kops/issues/2354#issuecomment-307927218)), but there's no equivalent for basic auth. 

Is there another way to achieve this, or is this sort of thing semi-deprecated in favor of RBAC?

Might be related to #3473.

---

My current setup:

* kops 1.7.1
    ```
    $ kops version
    Version 1.7.1
    ```
* Kubernetes 1.7.5:
    ```
    $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-18T20:30:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
    ```
* Hosted on AWS

**Comment by johnzheng1975** [comment]
Same question
kops 1.7.1
kubernetes 1.7.10
I want to add a user with limited rights, to access dashboard.

**Comment by chrislovecnm** [comment]
/assign @KashifSaadat 

Can the new file assets stuff help?

**Comment by KashifSaadat** [comment]
@chrislovecnm I believe so.

@greggilbert could you see whether the use of FileAssets resolves your issue (set path to where the `basic_auth.csv` file is located)? You will have to deploy using the kops v1.8 release (v1.8.0-beta.2 is latest, backwards compatible with Kubernetes v1.7.x) as it contains some fixes for FileAssets.

Documentation: https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#fileassets

**Comment by greggilbert** [comment]
@KashifSaadat: sorry, I haven't had a chance to look at this in a bit. Our cluster is on 1.7 right now and we'd like to keep that 'til 1.8 is stable. I'll update when I can.

**Comment by chrislovecnm** [comment]
You can use kops 1.8 with a k8s 1.7 server. Try out the new features and let us know
