### ISSUE TITLE
Support AWS VPC CNI

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#3964]
Per discussion on sig-aws, this looks like a good high-performance option:

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/proposals/cni-proposal.md#how-many-addresses-are-available

**Comment by geojaz** [comment]
I'll jump on this for 1.9

**Comment by geojaz** [comment]
Just kidding- this is addressed in #3997. I'll work to help get this in.

**Comment by chrislovecnm** [comment]
Implemented
