### ISSUE TITLE
SSH access restrictions should not be restricted to CIDR ranges

### ISSUE THREAD

**Issue by dgreene-r7** [kubernetes/kops#3966]
Currently the only way to restrict SSH access to both the master and node instances is specifying `SSHAccess` in the cluster spec. This field is a CIDR range and misses out on a crucial use of security group rules.

Here's our use case: Our bastion instance has a security group that allows access from a few specific IP addresses. We create an ingress rule on port 22 from the bastion security group for any instance we want to have SSH access to. This allows us to handle bastion failure easier (replace the instance in the ASG), allows us to update one SG if any of the approved IP addresses change, and doesn't allow node-to-node ssh access; all ssh connections have to go through the bastion first.

The amount of work required here is pretty minimal. It requires a little bit of parsing logic in [external_access.go](https://github.com/kubernetes/kops/blob/master/pkg/model/external_access.go#L51-L71) to determine whether the provided value is an actual CIDR range.

I'd be happy to do the legwork here.

**Comment by chrislovecnm** [comment]
Please do the leg work ;) happy to help you contribute!!

**Comment by AndresPineros** [comment]
Is there any update on that legwork? :D

**Comment by dgreene-r7** [comment]
My team is moving away from kops so I don't think anyone is going to do this. Feel free to take it on if you'd like.

**Comment by johnswan** [comment]
Hi

Just for interest, why are you moving away from Kops and what will you use instead?

Thanks!

**Comment by dgreene-r7** [comment]
We've been frustrated by `another thing` that requires a state bucket and doesn't lend itself well to automation. Additionally, we want to be able to manage our own infrastructure rather than have Kops generate very obtuse Terraform templates that can't be refactored.

Basically we've found that Kops is fine for starting from scratch but doesn't lend itself very well to integrating into our existing environment.
