### ISSUE TITLE
Does kops support aws beijing region ?

### ISSUE THREAD

**Issue by johncchen** [kubernetes/kops#3970]
KOPS Version: 1.7.1
Kubernetes Version: 1.7.6
Cloud Provider: AWS
Region: beijing

I use kops to create kubernetes cluster in aws in beijing region.
the result show it was success to create cluster.
--------------------------------------------------------------------------------------------------
I1130 06:16:46.756506    2234 create_cluster.go:659] Inferred --cloud=aws from zone "cn-north-1a"
I1130 06:16:46.756574    2234 create_cluster.go:845] Using SSH public key: /root/.ssh/id_rsa.pub
I1130 06:16:46.972711    2234 subnets.go:183] Assigned CIDR 172.20.32.0/19 to subnet cn-north-1a
I1130 06:16:46.972741    2234 subnets.go:183] Assigned CIDR 172.20.64.0/19 to subnet cn-north-1b
I1130 06:19:05.113391    2234 apply_cluster.go:420] Gossip DNS: skipping DNS validation
I1130 06:19:05.213163    2234 executor.go:91] Tasks: 0 done / 69 total; 32 can run
I1130 06:19:06.114829    2234 vfs_castore.go:422] Issuing new certificate: "kubelet"
I1130 06:19:07.377093    2234 vfs_castore.go:422] Issuing new certificate: "kops"
I1130 06:19:07.440952    2234 vfs_castore.go:422] Issuing new certificate: "kube-proxy"
I1130 06:19:07.522956    2234 vfs_castore.go:422] Issuing new certificate: "kubecfg"
I1130 06:19:07.607522    2234 vfs_castore.go:422] Issuing new certificate: "kube-controller-manager"
I1130 06:19:07.775507    2234 vfs_castore.go:422] Issuing new certificate: "kube-scheduler"
I1130 06:19:08.061064    2234 executor.go:91] Tasks: 32 done / 69 total; 14 can run
I1130 06:19:08.627388    2234 executor.go:91] Tasks: 46 done / 69 total; 19 can run
I1130 06:19:10.043781    2234 launchconfiguration.go:327] waiting for IAM instance profile "nodes.china.nuwa.k8s.local" to be ready
I1130 06:19:10.867733    2234 launchconfiguration.go:327] waiting for IAM instance profile "masters.china.nuwa.k8s.local" to be ready
I1130 06:19:21.039170    2234 executor.go:91] Tasks: 65 done / 69 total; 3 can run
I1130 06:19:21.828410    2234 vfs_castore.go:422] Issuing new certificate: "master"
I1130 06:19:21.878469    2234 executor.go:91] Tasks: 68 done / 69 total; 1 can run
I1130 06:19:22.080813    2234 executor.go:91] Tasks: 69 done / 69 total; 0 can run
I1130 06:19:22.240225    2234 update_cluster.go:247] Exporting kubecfg for cluster
Kops has set your kubectl context to china.nuwa.k8s.local

Cluster is starting.  It should be ready in a few minutes.

Suggestions:
 * validate cluster: kops validate cluster
 * list nodes: kubectl get nodes --show-labels
 * ssh to the master: ssh -i ~/.ssh/id_rsa admin@api.china.nuwa.k8s.local
The admin user is specific to Debian. If not using Debian please use the appropriate user based on your OS.
 * read about installing addons: https://github.com/kubernetes/kops/blob/master/docs/addons.md
--------------------------------------------------------------------------------------------------

Then I can't get node information by using `kubectl get nodes`
I checked the status of loadbalancer created by kops "api-china-nuwa-k8s-local-ctvvrd"  was "OutofService"

Does kops support aws beijing region ?

**Comment by chrislovecnm** [comment]
It should as we have instructions how to run in China AWS

**Comment by leeeboo** [comment]
https://github.com/kubernetes/kops/blob/master/docs/aws-china.md

**Comment by johncchen** [comment]
I used kubeadm to install kubernetes on aws beijing, it was work.

https://blog.frognew.com/2017/12/kubeadm-install-kubernetes-1.9.html

**Comment by chrislovecnm** [comment]
Closing :)
