### ISSUE TITLE
instance type p3.2xlarge not handled

### ISSUE THREAD

**Issue by JoergReinhardt** [kubernetes/kops#3971]
kops version:
1.7.1
kubernetes version:
v1.8.2
cloud provider:
aws
command:
'kops update cluster --name $NAME'

with the following instance group config for the 'nodes' group:
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-11-30T09:49:49Z
  labels:
    kops.k8s.io/cluster: wpk.viorama.com
  name: nodes
spec:
  image: ami-6fc85715
  machineType: p3.2xlarge
  maxPrice: "0.9"
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1d

what happend:
kops update failed with the following error message:
'...executor.go:109] error running task "LaunchConfiguration/nodes.wpk.viorama.com" (9m59s remaining to succeed): instance type not handled: "p3.2xlarge"'

expection:
a working cluster utilizing p3.2xlarge as node type 

manifest:
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-11-30T09:49:48Z
  name: wpk.viorama.com
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-wanderpokal/wpk.viorama.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1d
      name: d
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1d
      name: d
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.7.10
  masterPublicName: api.wpk.viorama.com
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1d
    type: Public
    zone: us-east-1d
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-11-30T09:49:49Z
  labels:
    kops.k8s.io/cluster: wpk.viorama.com
  name: master-us-east-1d
spec:
  image: ami-3cc65946
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1d

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-11-30T09:49:49Z
  labels:
    kops.k8s.io/cluster: wpk.viorama.com
  name: nodes
spec:
  image: ami-6fc85715
  machineType: p3.2xlarge
  maxPrice: "0.9"
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1d

logs:
https://gist.github.com/JoergReinhardt/49cb350003eaabddf88685172c68a95b
 
more:
also failed when tryed without 'maxPrice'

**Comment by chrislovecnm** [comment]
kops 1.8.x has support, you can use the beta or wait for the release. Closing
