### ISSUE TITLE
Can kops 1.7.1 work well with istio-0.2.12?

### ISSUE THREAD

**Issue by kubebc** [kubernetes/kops#3972]
Hi, team,

Can kops 1.7.1 work well with istio-0.2.12? Any online doc? What need to be paying more attention to? especially on k8s-ingress --> istio-ingress --> service pods” model. Thanks

**Comment by chrislovecnm** [comment]
@kubebc yes, we give you k8s :)  I would reach out to the istio team and see if they have an install guide.

**Comment by chrislovecnm** [comment]
I am gong to close this
