### ISSUE TITLE
Nat Gateways are overly agressive

### ISSUE THREAD

**Issue by BobbyJohansen** [kubernetes/kops#3974]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
kops version: 1.7.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
kubernetes version: 1.7.11

3. What cloud provider are you using?
Cloud provider: AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
I build a kops private cluster with: `Kops create cluster --kubernetes-version=1.7.11 --networking=classic --zones=us-west-2a,us-west-2b,us-west-2c --node-count=6 --node-size=m3.medium --master-size=m4.large --vpc=<VPC-ID> --topology=private --dns-zone=<ZONEID> --name=<my-clustername>`

I then go to update my cluster to scale my nodes autoscaling group or (IG) through kops: 
`kops edit ig --name=<my-clustername> nodes`
`kops update cluster <my-clustername>`

5. What happened after the commands executed?
A cluster was created as expected. I noticed that it created 3 NAT gateways and route table entries to point to each AZ subnet. I removed these because they were unnecessary and expensive to keep all the NAT's and EIPS. 

When I attempted to update the cluster with the new changes in the IG it complains about the NAT gateways missing.

6. What did you expect to happen?
I expect that if it either:
A) finds the NATs are not there and continues on with just a warning. 
B) allows me to pass a flag that says just update the IG and ignore everything else.
C) On cluster creation allow specification of NAT configuration.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?
I am loving Kops

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by KashifSaadat** [comment]
Hi @BobbyJohansen, thanks for raising an issue!

When you are using the shared VPC setup (specifying VPC id in the cluster creation), you also have the ability to specify pre-existing subnets and NAT Gateways by modifying the Cluster Spec. Some documentation is provided here: https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md#shared-nat-gateways

Please could you try this out and see if it meets your requirements?

**Comment by BobbyJohansen** [comment]
I have tried this out and it works very nicely. Thank you! We can close
