### ISSUE TITLE
Bastion not working properly after 1.7 to 1.8 upgrade with flannel vxlan

### ISSUE THREAD

**Issue by arielkung** [kubernetes/kops#3975]
After upgrade to 1.8 with flannel vxlan the bastion node is not correctly configured.
Instance is created but is not recognized as node by kops.
And you cannot ssh into master from the existing bastion instance.

1. What `kops` version are you running? The command `kops version`, will display
 this information.

`Version 1.8.0-beta.2 (git-fd7acd1ce)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T19:11:02Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
3. What cloud provider are you using?

aws

4. What commands did you run?  What is the simplest way to reproduce this issue?

after upgrade with channel alpha and setting the instance groups images to the 1.8 versions run

`kops rolling-upgrade cluster`

5. What happened after the commands executed?

Bastion is shown as ready but 0 nodes are in the output.

Here is the verbose version

```
I1130 16:06:53.669930   21196 s3fs.go:176] Reading file "s3://instancegroup/bastions"
I1130 16:06:53.850572   21196 s3fs.go:176] Reading file "s3://instancegroup/master-us-east-1a"
I1130 16:06:54.069940   21196 s3fs.go:176] Reading file "s3://instancegroup/nodes"
I1130 16:06:54.479950   21196 s3fs.go:176] Reading file "s3://instancegroup/spotnodes"
I1130 16:06:54.780681   21196 aws_utils.go:39] Querying EC2 for all valid regions
I1130 16:06:55.812456   21196 aws_cloud.go:956] Querying EC2 for all valid zones in region "us-east-1"
I1130 16:06:55.812603   21196 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
I1130 16:06:56.117942   21196 aws_cloud.go:415] Listing all Autoscaling groups matching cluster tags
I1130 16:06:56.119789   21196 request_logger.go:45] AWS request: autoscaling/DescribeTags
I1130 16:06:57.142455   21196 request_logger.go:45] AWS request: autoscaling/DescribeAutoScalingGroups
I1130 16:06:57.357545   21196 cloud_instance_group.go:64] unable to find node for instance: i-071c2333b98c3f0c4
NAME			STATUS	NEEDUPDATE	READY	MIN	MAX	NODES
bastions		Ready	0		1	1	1	0
master-us-east-1a	Ready	0		1	1	1	1
nodes			Ready	0		0	0	0	0
spotnodes		Ready	0		3	3	3	3
```
6. What did you expect to happen?

Show 1 node in bastion row.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-08-17T06:52:56Z
  labels:
    kops.k8s.io/cluster: my.cluster.tld
  name: bastions
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-11-27
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - utility-us-east-1a
  - utility-us-east-1c
```

**Comment by justinsb** [comment]
The bastion is not treated as a node (in the kubernetes sense).    This is more concerning though: "And you cannot ssh into master from the existing bastion instance."  What error do you see?

**Comment by justinsb** [comment]
Idea: we could make the nodes column for a bastion a `-` or `n/a` instead.  Or just blank.

I tried the upgrade from 1.7.10 -> 1.8.4 with flannel vxlan and I was able to SSH through the bastion before and after the upgrade.

**Comment by arielkung** [comment]
About the bastion not being a node and the column you are right, it just came into my mind when I had the issue with the ssh, so it's not a big thing and it's the same in previous versions.

Yesterday I realized in the output of the rolling-update I copied here this line:

`I1130 16:06:57.357545   21196 cloud_instance_group.go:64] unable to find node for instance: i-071c2333b98c3f0c4`

I tried a new rolling-update and we are ok now.

Sorry for opening the issue, it seems everything is ok now :)

**Comment by chrislovecnm** [comment]
Closing
