### ISSUE TITLE
Default kubelet to secure

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#3998]
I think we just need to switch https://github.com/kubernetes/kops/pull/3125 to default-on

**Comment by chrislovecnm** [comment]
More context please
/cc @gambol99

**Comment by justinsb** [comment]
What are you asking @chrislovecnm ?  The kubelet should default to a secure configuration.

**Comment by audip** [comment]
@justinsb Is this a `good-stater-issue`? Can you point me to the files where this change to default-on will need to be made?
I read through #3125 and can submit a PR for this (if this is trivial). Still reading through and learning about the code base
