### ISSUE TITLE
kops: reenable GCE

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#4]
We disabled GCE because it was lagging behind AWS.  Get it back up to par!

**Comment by MichaelJCole** [comment]
Is [kube-up.sh](http://kubernetes.io/docs/getting-started-guides/gce/#starting-a-cluster) the best way to self-host a cluster on GCE?

Where does kop fit in?  I used kop to bring up an AWS cluster, but wanted to try something similar on GCE.

**Comment by chrislovecnm** [comment]
@michealjcole it is a work in progress ;)

**Comment by chrislovecnm** [comment]
Closing this ... it is alive ... aka re-enabled.
