### ISSUE TITLE
Handling addons for HA master

### ISSUE THREAD

**Issue by Skilgarriff** [kubernetes/kops#40]
As mentioned in Slack, I believe some work needs to be done with handling addons when it comes to having HA masters across different Zones.

**Comment by justinsb** [comment]
I've put up some docs: https://github.com/kubernetes/kops/blob/master/docs/addons.md

We're curating some addons in the addons directory, removing the `kubernetes-service` label which causes the addon manager to remove it, and adding a label that will hopefully let us update it in future.

Closing, but do reopen if any issues remain.
