### ISSUE TITLE
How to specify retention in elasticsearch loggin addons

### ISSUE THREAD

**Issue by mcasimir** [kubernetes/kops#4004]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

v1.7.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

v1.6.4

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

I installed the elasticsearch logging plugin with default configuration.

5. What happened after the commands executed?

Everything was fine but after a few weeks the logging stopped working since the volume was full. 

6. What did you expect to happen?

I expect some rotation of index to be in place. Maybe configurable through env vars ie. INDEX_RETENTION: 7days

**Comment by glend** [comment]
There is rotation in place, every index is named logstash-[date]. You can run a cronjob that automates the task of removing older indexes.

Also see https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html if you want to archive older logs.
