### ISSUE TITLE
Add support in cli for mixed network topology.

### ISSUE THREAD

**Issue by lleszczu** [kubernetes/kops#4011]
I would like to use mixed topology with most of the nodes available in private network only and some nodes (in separate instancegroup) associated with public IPs.
It would be nice to mark topology as mixed, so during cluster create required subnets are created and then operator just create json/yaml manifest with precreated subnets and associatePublicIp flag set to true.

**Comment by lowerzero** [comment]
Is ther any way to do this in current implementation?
