### ISSUE TITLE
kops replace --create not working

### ISSUE THREAD

**Issue by joan38** [kubernetes/kops#4012]
```
> ./kops replace --create -f cluster-benji.yml
Error: unknown flag: --create
Usage:
  kops replace -f FILENAME [flags]

Examples:
  # Replace a cluster desired configuration using a YAML file
  kops replace -f my-cluster.yaml
  
  # Note, if the resource does not exist the command will error, use --force to provision resource
  kops replace -f my-cluster.yaml --force

Flags:
  -f, --filename stringSlice   A list of one or more files separated by a comma.
      --force                  Force any changes, which will also create any non-existing resource

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --config string                    config file (default is $HOME/.kops.yaml)
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files (default false)
      --name string                      Name of cluster
      --state string                     Location of state storage (default "s3://drivetribe-kubernetes-state-store")
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging


unknown flag: --create
> ./kops version
Version 1.8.0 (git-5099bc5)
```

> kops replace --create will now replace-or-create, which is useful for CI / automated workflows

According to the release note that should have worked?

**Comment by gambol99** [comment]
hi @joan38 ... this was added in https://github.com/kubernetes/kops/pull/3089, the flag was originally ``--create`` and then after discussion changed to ``--force`` . Where's the documentation indicating the ``--create`` so we update

**Comment by joan38** [comment]
I see.
Do you know why we didn't get with `kops apply` for consistancy?

Thanks @gambol99

**Comment by gambol99** [comment]
no worries :-) .... also in regard to the 'apply' ... taken from the original PR

> apply for kubectl is much more complex logic than replace (take a peek at kubernetes/kubernetes#1702 ). Annoyingly it is all done client-side in kubectl so it isn't something we can just drop in yet. But that's why I'm wary of kops apply

**Comment by wendorf** [comment]
The [1.8.0 release notes](https://github.com/kubernetes/kops/releases/tag/1.8.0) still document `kops replace --create`. Can that be edited?

**Comment by chrislovecnm** [comment]
@wendorf I will reopen, and if you could submit a PR that would be awesome, otherwise it will go into the queue.

Thanks

Chris

**Comment by wendorf** [comment]
Unfortunately, I'm waiting on an org CLA to submit a couple PRs, but the issue is in both the [release notes markdown](https://github.com/kubernetes/kops/blob/master/docs/releases/1.8-NOTES.md) as well as the [Github release's notes](https://github.com/kubernetes/kops/releases/tag/1.8.0), which I wouldn't be able to PR.

**Comment by chrislovecnm** [comment]
No worries! Thanks, and hopefully they will sign it soon.
