### ISSUE TITLE
No error message when EC2 instance limit reached

### ISSUE THREAD

**Issue by sneako** [kubernetes/kops#4025]
------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? 
1.7.1

2. What Kubernetes version are you running?
1.7.8

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
```
kops create cluster \
  --cloud=aws \
  --node-count 3 \
  --master-size m4.large \
  --master-zones=us-east-1a \
  --zones us-east-1a,us-east-1b,us-east-1c \
  --node-size c4.2xlarge \
  --name=$NAME \
  --dns-zone $NAME  --yes
```
5. What happened after the commands executed?
The command succeeded and reported that the cluster was created successfully.  However, only one master and one node were created because my EC2 running instance limit had been reached.

6. What did you expect to happen?
A friendly error message informing me that not all nodes can be created because I have reached the limit.

**Comment by chrislovecnm** [comment]
So first please use kops 1.8

Secondly yes this is an enhancement that we need in kops validate cluster. We need to pull back errors from the asg.

**Comment by chrislovecnm** [comment]
If you have any desire to implement this change we always appreciate contributions!!

**Comment by ms4720** [comment]
I would like to take a stab at it, what is the process for claiming it?

**Comment by chrislovecnm** [comment]
@ms4720 just seeing your response now. We need to improve kops validate to pull back error messages from ASG's.  This is not really something that we can check before we create the ASG's.  Let me know if you want to take this on, and please reach out on slack if you like.

**Comment by ms4720** [comment]
@chrislovecnm I might have some time, work has been very busy and I have been focused away from k8s for now.  It would have to be a weekend project and I have now weekends for a while.

**Comment by vendrov** [comment]
@chrislovecnm We can query AWS API about EC2 instance limit, and only it the there are enough slots we will proceed with the actual creation of the cluster.
WDYT?

**Comment by chrislovecnm** [comment]
@vendrov which API ... cause I have not been able to find that one ... AWS engineer could not help me find that one 😆

**Comment by kaseyalusi** [comment]
Hi, I would like to take a look at this issue to get into contributing... looking through the AWS sdks, I think this would be possible by using `DescribeAccountAttributes` from https://raw.githubusercontent.com/aws/aws-sdk-go/master/service/ec2/api.go and comparing the `max-instances` from there with the current # of instances in the region.  Would that be a reasonable approach?  I don't quite know the `kops` codebase well enough to know where the best place to insert that logic is though.
