### ISSUE TITLE
Verify that we can resize a master ig to size 0

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#403]
Master ig resize was reported not to actually resize the ASG

**Comment by sekka1** [comment]
I can confirm this was not working on my cluster.  Edited the master and nodes.  The nodes ASG went to zero but the master didnt 

This is the ig after editing

```
NAME			ROLE	MACHINETYPE	MIN	MAX	ZONES
master-us-east-1a	Master	t2.medium	0	0	us-east-1a
nodes			Node	t2.medium	0	0	us-east-1a,us-east-1c,us-east-1d
```
