### ISSUE TITLE
Error creating DNS HostedZone in k8 (on aws)

### ISSUE THREAD

**Issue by tmikulin** [kubernetes/kops#4031]
I was in the process of creating a k8 cluster with kops on aws, and I ran into an interesting exception:

    error running task "DNSZone/foobar" (1m42s remaining to succeed): error creating DNS HostedZone "": InvalidParameter: 1 validation error(s) found.
    - missing required field, CreateHostedZoneInput.Name.

I created a hosted zone on Route 53 and set the **zone** type to **private**.

I also modified the following VPC settings to "true":

 - **enableDnsHostnames** 
 - **enableDnsSupport**

used software:

**OS: Ubuntu 14.04**

**kops - Version 1.6.1 (git-22b22cc)**

**kubectl - Client Version: version.Info{Major:"1", Minor:"8"...}**

I was basically using [this](https://medium.com/cloud-academy-inc/setup-kubernetes-on-aws-using-kops-877f02d12fc1) blog post as a guide.

I deleted the cluster and created it again, but the same exception persisted. So there must be something I did wrong.

Any advice would be helpful.

tnx,
Tom

**Comment by geojaz** [comment]
@tmikulin Thanks for the report. If we're going to debug this, I'll need some information- most specifically the exact command that you're using to create this cluster via kops. 

But I'm also interested to know, which version of k8s are you attempting to install? You're probably best off installing something more current than this tutorial uses- 1.8.x is where I would start. 

Even if you decide that 1.6.x is the right version of k8s for you this time, my recommendation is first to upgrade to kops 1.8.0. We don't follow the exact versioning of kubernetes/kubernetes, so you don't need to use kops 1.6.x to manage 1.6 clusters.

**Comment by tmikulin** [comment]
Hi, geojaz

I wrote all the details on my original post, the version etc..

I think I found a solution the original problem, but now I have a different error:

**unable to pre-create DNS records - cluster startup may be slower: Error pre-creating DNS records: InvalidChangeBatch: RRSet with DNS name api.euwest2.foo.bar.pvc. is not permitted in zone bar.vpc.**

Does that mean that there is some problem with the private DNS entry that I created?

Tnx,
Tom

**Comment by chrislovecnm** [comment]
Please use kops 1.8 as it is backwards compatible. Also you have a cve in that release
