### ISSUE TITLE
Add the ability to deploy T2 Unlimited instances on AWS

### ISSUE THREAD

**Issue by adammillerio** [kubernetes/kops#4032]
1. AWS recently announced [T2 Unlimited instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-unlimited.html), which is essentially just a setting on a t2 class instance that will make it "purchase" extra credits instead of returning to the baseline performance level once credits are exhausted. This would be ideal for a master in a low-utilization cluster, as it would allow for a cheaper instance type, while also not running the risk of baseline performance causing problems with system components. Kops should allow the user to deploy a T2 unlimited by specifying it in an instance group configuration.

2. This might be annoying to implement, since it is an additional configuration option specific to a certain class of instances.

Essentially, you either call RunInstances with CreditSpecification=unlimited if they are new, or run ModifyInstanceCreditSpecification if it is being updated. See docs [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html).

As for configuration, two possibilities that come to mind would be either including specific machineTypes for unlimited instances (e.g. t2.medium.unlimited) or adding an additional configuration option such as machineCreditSpecification.

**Comment by lawrencedudley** [comment]
This would be amazing

**Comment by lawrencedudley** [comment]
We use t2 unlimited in other areas - annoyingly it's not supported on launch configurations for autoscaling groups, just launch templates (which I think signifies that AWS is suggesting that's where the future lies).

So a prerequisite for this is to move the configuration to launch templates first. I've not dug into the kops code properly but will try and do so over the next few weeks to see what the implications might be if nobody has had a go yet.

**Comment by thedarkfalcon** [comment]
Just voicing my opinion as this thread is stale.

I still think this would be very useful. I have experienced pods/masters dying due to running out of CPU credits when running T instances. The T instances are much more cost effective for us, however sometimes if there is a sudden burst of CPU resource required, we can bottom out on CPU credit which can cause the cluster to stall. I don't want to increase the instance sizes, simply purchasing an additional hours worth of compute when required is much better (what T2 unlimited does).

However, the new T3 instances have this functionality built into them. So possibly if T3 instances become available via KOPS, this ticket would be redundant. Either way, I think KOPS urgently needs to support either T2 Unlimited, or T3 instances.

**Comment by thedarkfalcon** [comment]
I suspect the response for this would be simply to use T2 instances instead, which yes I know, is 30% less efficient per $.

**Comment by rifelpet** [comment]
LaunchConfigurations do not support credit specifications, and Kops currently uses LaunchConfigurations with its ASGs. #6277 has been opened to support LaunchTemplates which do support credit specification. Once merged it should be pretty simple to expose a credit specification field in the API, allowing the control of standard/unlimited T2s and T3s.

**Comment by bigdrum** [comment]
Hello, is there any plan on this now that #6277 is merged?

**Comment by david-in-perth** [comment]
@gambol99 : I see [reference to "CreditSpecification"][1] in the #6277 diff.
Does that mean this ticket is now implemented and can be closed (along with #6284)?

I couldn't find any reference to it in the docs.

[1]: https://github.com/kubernetes/kops/pull/6277/files#diff-65eb1c115c30266fffc624124755c422R122

**Comment by ahharu** [comment]
Any updates?

**Comment by erdii** [comment]
Ping

**Comment by lapcchan** [comment]
any update?

**Comment by constructdian** [comment]
Any updates to this?

**Comment by jkieley** [comment]
any update?

**Comment by olemarkus** [comment]
The plan is to enable LaunchTemplates by default in kops 1.18/1.19. But we Still need to make this configurable in the instance group spec.

**Comment by shapirus** [comment]
Any update? kOps is now at 1.19, LaunchTemplates come by default out of the box.

**Comment by erdii** [comment]
https://github.com/kubernetes/kops/pull/10934
