### ISSUE TITLE
Mount Volume in KubeApiServer

### ISSUE THREAD

**Issue by RaphaelHerd** [kubernetes/kops#4034]
Hey,

I would like to ask if it's possible to add a volume into the API server? I tried something like kops edit cluster .... but without any luck.

Maybe I miss something. 

Thanks for helping

**Comment by gambol99** [comment]
/assign @gambol99

Hi @RaphaelHerd, there isn't a mechanism to add an additional volume via kops at the moment. The best you could do as of now would be something hacky with a daemon and privileged container (though not a recommendation) ...

**Comment by chrislovecnm** [comment]
Hook as well would work.
