### ISSUE TITLE
Tagging all created resources in AWS with KubernetesCluster tag

### ISSUE THREAD

**Issue by lleszczu** [kubernetes/kops#4035]
I noticed that certain resources are not tagged with KubernetesCluster value (right now I see it on NatGateway), which is problematic, when running multiple kops clusters in the same region. 

I believe this should be set for any kops-created resource for easier filtering in console/API (if supported by AWS: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html).

**Comment by szwed** [comment]
Ideally, every AWS resource supporting tags should be tagged with KubernetesCluster value (tag key: "Name")

**Comment by blakebarnett** [comment]
This should probably use the new form: `kubernetes.io/<clustername>=<owned|shared>`

ref: https://github.com/kubernetes/kubernetes/issues/35052

**Comment by krogon** [comment]
linking to: https://github.com/kubernetes/kops/pull/4489

**Comment by olemarkus** [comment]
/remove-lifecycle stale

> This should probably use the new form: kubernetes.io/<clustername>=<owned|shared>

We use `KubernetesCluster` as cost allocation tag, something that is not really possible with the non-legacy tag format. So I would definitely prefer supporting both.
