### ISSUE TITLE
DNS resolution for external domains if VERY slow from within containers on CentOS hosts

### ISSUE THREAD

**Issue by kgignatyev-inspur** [kubernetes/kops#4040]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.8.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
1.8.5

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
create simple cluster with kops in us-east-2 and edit nodes and masters to use CentoOS image (AMI:  ami-e0eac385)  per
https://github.com/kubernetes/kops/blob/master/docs/images.md

5. What happened after the commands executed?
cluster is created and workload is deployed then we can run 

kubectl run busybox  -ti --image=busybox 
from within container we can run 

/ # time nslookup google.com
Server:    100.64.0.10
Address 1: 100.64.0.10 kube-dns.kube-system.svc.cluster.local

Name:      google.com
Address 1: 2607:f8b0:4004:800::200e iad30s09-in-x0e.1e100.net
Address 2: 172.217.7.238 iad23s58-in-f14.1e100.net
real	0m 5.12s
user	0m 0.00s
sys	0m 0.00s
/ # time nslookup google.com
Server:    100.64.0.10
Address 1: 100.64.0.10 kube-dns.kube-system.svc.cluster.local

Name:      google.com
Address 1: 2607:f8b0:4004:800::200e iad30s09-in-x0e.1e100.net
Address 2: 172.217.7.238 iad23s58-in-f14.1e100.net
real	0m 15.01s
user	0m 0.00s
sys	0m 0.00s
/ # 

DNS resolution takes 5-50 seconds!

when same command run on host machine itself the resolution is instantaneous.

6. What did you expect to happen?
DNS resolution to be near instantaneous, as with Ubuntu hosts

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

kops get --name k8s.qa-seattle.inspurusa.net --state s3://kops-qa-seattle-cluster-state-store -oyaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-12-11T18:54:54Z
  name: k8s.qa-seattle.inspurusa.net
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudLabels:
    Confidentiality: None
    Creator: InspurUSA
    Owner: InspurUSA
    env_name: qa-seattle
  cloudProvider: aws
  configBase: s3://kops-qa-seattle-cluster-state-store/k8s.qa-seattle.inspurusa.net
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: v1.8.5
  masterPublicName: api.k8s.qa-seattle.inspurusa.net
  networkCIDR: 10.0.0.0/16
  networkID: vpc-b75caedf
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.32.0/19
    name: us-east-2a
    type: Public
    zone: us-east-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-11T18:54:54Z
  labels:
    kops.k8s.io/cluster: k8s.qa-seattle.inspurusa.net
  name: master-us-east-2a
spec:
  additionalSecurityGroups:
  - sg-2b784a43
  - sg-a35b69cb
  associatePublicIp: true
  image: ami-e0eac385
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2a
  role: Master
  rootVolumeSize: 30
  subnets:
  - us-east-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-11T18:54:54Z
  labels:
    kops.k8s.io/cluster: k8s.qa-seattle.inspurusa.net
  name: nodes
spec:
  additionalSecurityGroups:
  - sg-2b784a43
  - sg-a35b69cb
  associatePublicIp: true
  image: ami-e0eac385
  machineType: m4.large
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 30
  subnets:
  - us-east-2a

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?
same issue was with kubernetes 1.8.4

DNS works fast when default images are used.

**Comment by kgignatyev-inspur** [comment]
Interesting observation: if I try to resolve directly agains pods then DNS resolution is quick!

time nslookup google.com 100.96.2.5:10053
Server:    100.96.2.5
Address 1: 100.96.2.5

Name:      google.com
Address 1: 2607:f8b0:4004:803::200e iad23s59-in-x0e.1e100.net
Address 2: 216.58.217.78 iad23s41-in-f78.1e100.net
real	0m 0.06s
user	0m 0.00s
sys	0m 0.00s
/ # 

but going via service is sloooowwww

/ # time nslookup google.com
Server:    100.64.0.10
Address 1: 100.64.0.10 kube-dns.kube-system.svc.cluster.local

Name:      google.com
Address 1: 2607:f8b0:4004:804::200e
Address 2: 172.217.7.238 iad23s58-in-f14.1e100.net
real	0m 25.04s
user	0m 0.00s
sys	0m 0.00s
/ # 
 there  100.64.0.10 is Cluster IP of kube-dns, and 100.96.2.5 is IP of one of kube-dns pods

**Comment by kgignatyev-inspur** [comment]
when I run alpine and try to do nslookup from within alpine container it would not resolve google.com with this output:

/ # nslookup google.com
;; reply from unexpected source: 100.96.2.10#53, expected 100.64.0.10#53
;; reply from unexpected source: 100.96.2.10#53, expected 100.64.0.10#53
;; reply from unexpected source: 100.96.2.10#53, expected 100.64.0.10#53
;; connection timed out; no servers could be reached
==========
where  100.64.0.10 is kube-dns service address and 100.96.2.10 is IP of one of kube-dns PODs

**Comment by luhkevin** [comment]
I used the default AMIs and am also noticing this. I think it might have to do with `flannel` networking, because I created two k8s clusters with kops, the only difference being the networking, and the cluster that uses the default networking mode works fine re: DNS.

**Comment by chrislovecnm** [comment]
Can someone try kubenet? Start with what is tested the most.

**Comment by luhkevin** [comment]
Yeah, in my above comment, I meant `kubenet` when I said "default networking mode". DNS lookups work fine there, but not with `flannel` networking.

**Comment by kgignatyev-inspur** [comment]
just tried, when used --networking=kubenet DNS resolution is instantaneous:

kubectl run alpine -ti --image=alpine

/ # time nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      google.com
Address 1: 172.217.3.174 sea15s11-in-f174.1e100.net
Address 2: 2607:f8b0:400a:808::200e sea15s11-in-x0e.1e100.net
real	0m 0.00s
user	0m 0.00s
sys	0m 0.00s

**Comment by chrislovecnm** [comment]
Can someone file an issue with flannel, please?

**Comment by pierreozoux** [comment]
We are also seeing slow dns queries.
We use canal as a networking (so flannel).
And the strange thing is that, this is just with cloudflare dns. The rest is fine.
(we just opened a ticket with them, wait and see.)

And also, if we nslookup with the default dns resolver from the vpc, I have issues from the pod, but not from the host.

**Comment by pierreozoux** [comment]
We found the probable root cause:
One node wasn't able to start kube-proxy, we saw this event happening:
FailedToStartNodeHealthcheck

But we think that this node wasn't evicted, and continued to receive traffic, at least, this is what we saw at the ELB level in aws.
So we guess that 5% of the network traffic, sent to this node was just dropped, affecting all other services.

Still investigating to see how to monitor this properly if it happens again.

**Comment by mingyuanzhu** [comment]
@kgignatyev-inspur Do you have some updates? I have the same issues. Deploy k8s cluster in the aws cn-north-1 and DNS resolution is very slow from the pods. But resolution is very fast from the instance. I use the `kubenet` as the networking.
