### ISSUE TITLE
Expose the Calico interface and the ipip tunnel MTU for configuration in the kops specs

### ISSUE THREAD

**Issue by igoratencompass** [kubernetes/kops#4042]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

Please expose the mtu variables for Calico, both for calico interface and the ipip tunnel, similar to what is done for weave:

```
spec:
  networking:
    weave:
      mtu: 8912
```

2. Feel free to provide a design supporting your feature request.

**Comment by juris** [comment]
Indeed, it would be great to have this feature. 

At the moment calico sets MTU to 1500 and 1440 when running on AWS, despite [recommended 
9001 and 8981](https://docs.projectcalico.org/v2.6/usage/configuration/mtu)

**Comment by juris** [comment]
Just tried to change Calico MTU on AWS. Worked without any issues.

1. Updated `calico-config` config map with `mtu: 9001`
```
cni_network_config:
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.0",
  "plugins": [
    {
      "type": "calico",
      "etcd_endpoints": "__ETCD_ENDPOINTS__",
      "log_level": "info",
      "mtu": 9001,
      "ipam": {
        "type": "calico-ipam"
      },
...
}
```
2. Updated Calico daemon set with `FELIX_IPINIPMTU: 8981`
```
{
  "name": "FELIX_IPINIPMTU",
  "value": "8981"
 }
```
Here are some before/after tests conducted between two pods on separate r4.xlarge instances in the same us-east-1a AZ.

Iperf3 tests with default MTU (1500/1480)
```
iperf3 -c 100.113.139.178 -t 30
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  16.4 GBytes  4.71 Gbits/sec  3507             sender
[  5]   0.00-30.04  sec  16.4 GBytes  4.70 Gbits/sec                  receiver
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  16.5 GBytes  4.71 Gbits/sec  2386             sender
[  5]   0.00-30.04  sec  16.5 GBytes  4.70 Gbits/sec                  receiver
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  16.4 GBytes  4.70 Gbits/sec  3217             sender
[  5]   0.00-30.04  sec  16.4 GBytes  4.69 Gbits/sec                  receiver

```

Iperf3 tests with increased MTU (9001/8981)
```
iperf3 -c 100.105.39.211 -t 30
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  17.4 GBytes  4.97 Gbits/sec  175             sender
[  5]   0.00-30.04  sec  17.4 GBytes  4.96 Gbits/sec                  receiver
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  17.4 GBytes  4.98 Gbits/sec  113             sender
[  5]   0.00-30.04  sec  17.4 GBytes  4.97 Gbits/sec                  receiver
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  17.4 GBytes  4.98 Gbits/sec  122             sender
[  5]   0.00-30.04  sec  17.4 GBytes  4.97 Gbits/sec                  receiver
```

**Comment by igoratencompass** [comment]
@juris did you get a chance to test this across AZ's?

**Comment by juris** [comment]
Not for the minion nodes, but masters are in 3 AZs and pods on them feel just fine with the new MTU.

**Comment by shrinandj** [comment]
@juris Have you tried doing a kops rolling-upgrade after making your changes? Do the changes to calico's configMap persist after the upgrade or does kops always recreate the configMap using default options?

**Comment by juris** [comment]
Settings stay in place after `kops rolling-update`. However, I have not tried updating to a new version of kops, only kubernetes updates.
