### ISSUE TITLE
Validate object schema when loading spec from file.

### ISSUE THREAD

**Issue by lleszczu** [kubernetes/kops#4058]
When objects are created/modified with kops `replace create/replace -f` kops should verify if document is compliant with schema. If it's not compliant kops should fail instead of silently ignoring fields.

Example:
After setting `spec.sshAccess` to `spec.sshAcce` (typo) kops is removing whole section from manifest. I believe it should fail in such scenario.

**Comment by chrislovecnm** [comment]
This is already an open enhancement issue. On mobile so not going to search for the issue.
