### ISSUE TITLE
kops get cluster missing fields

### ISSUE THREAD

**Issue by lleszczu** [kubernetes/kops#4059]
When running `kops get cluster -o json` `kind` and `apiVersion` fields are missing.

I'm using `kops 1.7.1`

**Comment by KashifSaadat** [comment]
Hi @lleszczu, I believe this is fixed in kops v1.8.0. Please can you retest and confirm?

FYI kops v1.8.0 is backwards compatible with older kubernetes versions so you won't need to update to Kubernetes v1.8 to test.

**Comment by lleszczu** [comment]
@KashifSaadat I checked 1.8.0 today and it looks to be working fine.
