### ISSUE TITLE
how do i use existing subnets in kops 1.7.1 Kops seems to try to create them if they are already existing

### ISSUE THREAD

**Issue by anitakumar** [kubernetes/kops#4071]
1. kops 1.71

3.cloud provider = aws

4. kops update cluster <cluster_name> --yes

5. in my config i have specified subnets which are already in aws and 

6. i expect that if they exist they should not create it but i get the  error

error running task "Subnet/<subnet name>" (8m56s remaining to succeed): error creating subnet: InvalidSubnet.Conflict: The CI
DR '' conflicts with another subnet

**Comment by gambol99** [comment]
hi @anitakumar .. you need to add the id: subnetID in the subnet definition ..

https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/cluster.go#L355-L356

**Comment by anitakumar** [comment]
Thanks I did that the cluster is up. thanks
