### ISSUE TITLE
kops get cluster exits with 1 if no clusters are found.

### ISSUE THREAD

**Issue by darron** [kubernetes/kops#4072]
1. What `kops` version are you running?  1.8.0

2. What commands did you run?  What is the simplest way to reproduce this issue?

kops 1.8.0 exits with 1 if no clusters are found.

```
dfroese@: kops version
Version 1.8.0
[build.dev][master]:~/go/src/github.com/sfdc-saws/kaas
dfroese@: kops get cluster -o json

no clusters found
[build.dev][master]:~/go/src/github.com/sfdc-saws/kaas
dfroese@: echo $?
1
```

3. What did you expect to happen?

Previous kops versions don't exit with 1 - they exit with 0:

```
dfroese@: kops version
Version 1.7.1
[build.dev][master]:~/go/src/github.com/sfdc-saws/kaas
dfroese@: kops get cluster -o json
No clusters found
[build.dev][master]:~/go/src/github.com/sfdc-saws/kaas
dfroese@: echo $?
0
```

4. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

kops 1.7.1:

```
dfroese@: kops version
Version 1.7.1
[build.dev][master]:~/go/src/github.com/sfdc-saws/kaas
dfroese@: kops get cluster -o json -v 10
I1214 09:27:26.304083   88821 s3context.go:159] Found bucket "empty-kops-state-bucket-dfroese" in region "us-west-2"
No clusters found
[build.dev][master]:~/go/src/github.com/sfdc-saws/kaas
dfroese@: echo $?
0
```

kops 1.8.0:

```
dfroese@: kops version
Version 1.8.0
[build.dev][master]:~/go/src/github.com/sfdc-saws/kaas
dfroese@: kops get cluster -o json -v 10
I1214 09:28:02.932510   88993 s3context.go:163] Found bucket "empty-kops-state-bucket-dfroese" in region "us-west-2"

no clusters found
[build.dev][master]:~/go/src/github.com/sfdc-saws/kaas
dfroese@: echo $?
1
```

5. This doesn't change if you leave off `-o json` - it still exits with 1.

This is certainly a change in behaviour.

I don't really consider an empty state bucket to be an error condition.

What do y'all think? Is this an intentional change?

**Comment by darron** [comment]
This could probably be fixed by something like this:

```diff
dfroese@: gd
diff --git a/cmd/kops/get_cluster.go b/cmd/kops/get_cluster.go
index 3de6b04a7..4ef08468c 100644
--- a/cmd/kops/get_cluster.go
+++ b/cmd/kops/get_cluster.go
@@ -106,6 +106,9 @@ func NewCmdGetCluster(f *util.Factory, out io.Writer, getOptions *GetOptions) *c

                        err := RunGetClusters(&rootCommand, os.Stdout, &options)
                        if err != nil {
+                               if err.Error() == "no clusters found" {
+                                       exitWithNoError(err)
+                               }
                                exitWithError(err)
                        }
                },
diff --git a/cmd/kops/main.go b/cmd/kops/main.go
index e130a91dd..c1176db9d 100644
--- a/cmd/kops/main.go
+++ b/cmd/kops/main.go
@@ -31,3 +31,10 @@ func exitWithError(err error) {
        fmt.Fprintf(os.Stderr, "\n%v\n", err)
        os.Exit(1)
 }
+
+// exitWithNoError will terminate execution without an error result
+// It prints the error to stderr and exits with a zero exit code
+func exitWithNoError(err error) {
+       fmt.Fprintf(os.Stderr, "\n%v\n", err)
+       os.Exit(0)
+}
```

**Comment by chrislovecnm** [comment]
Is it an error that we do not find any clusters?

**Comment by chrislovecnm** [comment]
To me it is.

kubectl get po - where there are no pods does it throw an error?

**Comment by darron** [comment]
saws cluster create --name vpc.dev.saws-dev.io \
  --vpc vpc-9de196fb \
  --network-cidr 172.25.0.0/16 \
  --nodes 3 \
  --zones us-west-2a,us-west-2b,us-west-2c \
  --kube-version 1.7.11

I don't think it should be an error if you don't find any clusters - especially if you don't have any. (It didn't operate that way before either - which is totally OK - just noting the change.)

If you can't connect to the KOPS_STATE_STORE - totally an error. If you can't read a file from S3 - totally an error.

I'm spinning up a new cluster now - to see what happens when I run kubectl get pods - a new cluster won't have anything in the default namespace:

```
[vpc.dev][master]:~/go/src/k8s.io/kops
dfroese@: kubectl get pods
No resources found.
[vpc.dev][master]:~/go/src/k8s.io/kops
dfroese@: echo $?
0
```

Not an error.

Hey - it's up to you guys to classify it as an error or not - we've actually worked around it for our own usage of kops - but it doesn't feel like not having any clusters should be an error.

**Comment by chrislovecnm** [comment]
Did I change it? On my phone tough to wade through diffs

**Comment by darron** [comment]
This is where it became an error:

https://github.com/kubernetes/kops/pull/3610

That reason for the change totally makes sense - if you're looking for a specific named cluster and it doesn't exist - it should probably throw an error. That's probably going to be the only way to figure that out given you're running from a script.

But I don't know if not having any clusters, secrets, instance groups or federations should be an error.

No stress @chrislovecnm - answer when you can - and it's almost the weekend so have a good one!

cc @erickt
