### ISSUE TITLE
Add support for Cilium CNI plugin

### ISSUE THREAD

**Issue by nebril** [kubernetes/kops#4087]
I would like for kops to be able to deploy Kubernetes clusters with Cilium [0] as the CNI plugin.

I will start working on that and send out PR when I have something working.

[0] https://github.com/cilium/cilium

**Comment by nebril** [comment]
Closing this, as #4224 added support for Cilium.

**Comment by andrewsykim** [comment]
This wasn't documented anywhere but you need to set
```
export KOPS_FEATURE_FLAGS=SpecOverrideFlag
```
for the etcd version override to work. Hopefully in v1.10 we'll be using etcd3 by default so it's not required
