### ISSUE TITLE
in kubernetes delete the cluster without deleting the s3 bucket

### ISSUE THREAD

**Issue by anitakumar** [kubernetes/kops#4089]
hi,

i would like to keep the cluster config in the bucket and spin up a new cluster from that bucket. Can i  delete the cluster without deleting the bucket.

**Comment by chrislovecnm** [comment]
@anitakumar not at this time.  Take a look at using manifests, that way they manifest is local. https://github.com/kubernetes/kops/blob/master/docs/manifests_and_customizing_via_api.md

Questions?
