### ISSUE TITLE
Could not automaticlly upgrade K8s to version 1.8.0 on Centos7 instances

### ISSUE THREAD

**Issue by jardel-lima** [kubernetes/kops#4091]
1. What `kops` version are you running? The command `kops version`, will display
 this information.  `1.8.0`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag. `1.7.11`

3. What cloud provider are you using? `aws`

4. What commands did you run?  What is the simplest way to reproduce this issue?

I tried to update a kubernetes cluster from version `1.7.11` to `1.8.0`. I changed the `kubernetesVersion` to `1.8.0` with the `kops edit cluster $CLUSTER_NAME`, ran `kops update cluster $CLUSTER_NAME --yes` and `kops rolling-update cluster $NAME --yes`.

5. What happened after the commands executed?

The first master was terminated and a new one was started. After a while I got the following message on my terminal:

```
error validating cluster after removing a node: cluster did not validate within a duration of "5m0s"
```
And the command exited.

I ssh-ed into the new master instance that was created, checking the message log I noticed the following error:

```
Dec 15 13:26:14 ip-10-0-56-111 nodeup: W1215 13:26:14.944680   11077 executor.go:109] error running task "Package/docker-engine-selinux" (8759h35m47s remaining to succeed): error installing package "docker-engine-selinux": exit status 1: warning: /var/cache/nodeup/packages/docker-engine-selinux: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Dec 15 13:26:14 ip-10-0-56-111 nodeup: error: Failed dependencies:
Dec 15 13:26:14 ip-10-0-56-111 nodeup: selinux-policy-base >= 3.13.1-102 is needed by docker-engine-selinux-1.13.1-1.el7.centos.noarch
Dec 15 13:26:14 ip-10-0-56-111 nodeup: selinux-policy-targeted >= 3.13.1-102 is needed by docker-engine-selinux-1.13.1-1.el7.centos.noarch
``` 
I manually update the  `selinux-policy-base` dependency and the `nodeup` process could finish. After that the node was recognized as part of the k8s cluster.

I had to do this to all my nodes.

6. What did you expect to happen?

I expected `kops` could update or include all necessary dependencies to automatically upgrade k8s to 1.8.0.

9. Anything else do we need to know?

I am using Centos7 as my OS.

**Comment by chrislovecnm** [comment]
This is a bug, and an easy fix. If you want to contribute I can point you in the right direction.

This needs to be updated. https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/docker.go

**Comment by jardel-lima** [comment]
Thanks for you quickly reply @chrislovecnm .

I haven't done anything specific with `go`, but  since it is a easy fix and if you give me the directions I would like to contribute to this project.

With a quickly look at the code, a guess it is just necessary to add docker 1.13.1 dependencies to the `dockerVersions` array. Am I right?

**Comment by chrislovecnm** [comment]
Correct, testing it is the fun part as you will need a full build.

**Comment by justinsb** [comment]
@jardel-lima just sent a PR that should fix this, and we'll have to get e2e testing going on this also.  Which AMI are you using?

**Comment by jardel-lima** [comment]
Hi @justinsb, unfortunately I am not able to give you that information because I don't work to the company any more. All I can tell is that it was a Centos7 AMI, I don't know what specific one. I will try to reach my ex co-workers and ask if they can give that information. Thank you for your fix.

**Comment by mikesplain** [comment]
This looks fixed to me. Since @jardel-lima is no longer running into this I'm going to close it. Feel free to comment or reopen if needed!

/close
