### ISSUE TITLE
Enable rbac as default (for new clusters) / Show warning if not enabled

### ISSUE THREAD

**Issue by tsupertramp** [kubernetes/kops#4092]
Kops Version: 1.8
Cloud Provider: AWS

Hi community,

Creation of a new Cluster currently does not enable rbac as default. I think we should change that to increase security even if it is uncomfortable.

Rolling Update / Cluster Update / Create Cluster could additionally show a warning if rbac is disabled and link to some guidelines for kops (rbac enable).

Greetings, Thomas

**Comment by chrislovecnm** [comment]
@justinsb you know eta for upstream?

**Comment by chrislovecnm** [comment]
@liggitt what are your thoughts on this?  Do gke and openshift run RBAC by default?  I am thinking it is time.

**Comment by liggitt** [comment]
> @liggitt what are your thoughts on this? Do gke and openshift run RBAC by default?

Yes, GCE, GKE, kubeadm, openshift, tectonic, etc all enable RBAC by default on new clusters. That requires them to set up permissions for addons or cluster components set up by the installation.

**Comment by tsupertramp** [comment]
Reference: https://github.com/kubernetes/kops/pull/4184 - Part to set rbac as default is fulfilled - Makes it sense to enable a warning if the cluster is still running without rbac? - Then i would prepare a PR.

**Comment by chrislovecnm** [comment]
@tsupertramp I am fine with a warning message, always feel free to PR away.

**Comment by bhack** [comment]
Need we to point to a migration doc?  See https://github.com/kubernetes/kops/issues/2047#issuecomment-369921711
