### ISSUE TITLE
Update running in existing vpc documentation

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#4093]
The document does not talk about setting shared tags on shared resources properly. The users need to set shared tags on vpc, subnets, route tables, etc.

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md

Is the document. It is also referring to the old style tag “KubernetesCluster” which has been changed.

**Comment by tsupertramp** [comment]
@chrislovecnm I would take care of that. We just migrated everything to new Tagging Format. 

Public Subnets =>
- "kubernetes.io/cluster/cluster-name"   = "shared"
- "kubernetes.io/role/elb"                         = "1")

Private Subnets => 
- "kubernetes.io/cluster/cluster-name" = "shared"
- "kubernetes.io/role/internal-elb"         = "1"

VPC
- "kubernetes.io/cluster/cluster-name" = "shared"

Anything more I should consider?

**Comment by tsupertramp** [comment]
@chrislovecnm This can be closed. Forgot to mention you after the pr was merged.
