### ISSUE TITLE
kops not not url encoding upon sha check etc

### ISSUE THREAD

**Issue by zachaller** [kubernetes/kops#4103]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
```
Version 1.8.1-beta.1+cac47e7a7 (git-cac47e7a7)
```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
1.8.5
```

3. What cloud provider are you using?
```
aws
```

4. What commands did you run?  What is the simplest way to reproduce this issue?
```
kops update cluster <clustername>
```

5. What happened after the commands executed?
```
W1218 13:48:13.437663   20811 urls.go:71] Using base url from KOPS_BASE_URL env var: "https://s3.amazonaws.com/nodeup.k8-prod.***.com/kops/1.8.1-beta.1%2Bcac47e7a7"
I1218 13:48:21.196962   20811 builder.go:242] error reading hash file "https://s3.amazonaws.com/nodeup.k8-prod.***.com/kops/1.8.1-beta.1+cac47e7a7/linux/amd64/utils.tar.gz.sha1": file does not exist

cannot determine hash for "https://s3.amazonaws.com/nodeup.k8-prod.***.com/kops/1.8.1-beta.1+cac47e7a7/linux/amd64/utils.tar.gz" (have you specified a valid file location?)
```

6. What did you expect to happen?
```
For it to update the cluster
```

9. Anything else do we need to know?

If I take the url that it said dose not exist (https://s3.amazonaws.com/nodeup.k8-prod.***.com/kops/1.8.1-beta.1+cac47e7a7/linux/amd64/utils.tar.gz.sha1) and url encode it as such (https://s3.amazonaws.com/nodeup.k8-prod.***.com/kops/1.8.1-beta.1%2bcac47e7a7/linux/amd64/utils.tar.gz.sha1) notice the change of the + to %2b I am able to download the file using curl.

**Comment by chrislovecnm** [comment]
We need to do a regex and clean the url. We always appreciate contributions, and if you are interested in helping let me know. You can set the VERSION=1.8.1 during the build to work around this.
