### ISSUE TITLE
Kubernetes 1.9 updates

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#4105]
- new cni version
- new etcd version
- Docker version?

Now sure if we need a new Docker version

/cc @justinsb

**Comment by joan38** [comment]
Is this the tracking ticket for the 1.9 series release?

**Comment by chrislovecnm** [comment]
This is a issue for the items we need to update. Gong to actually close this as these are resolved. Once we have an alpha cut we will start a tracking issue
