### ISSUE TITLE
create a user so the user can administer an existing cluster from his machine

### ISSUE THREAD

**Issue by anitakumar** [kubernetes/kops#4108]
Hi,

I have an existing cluster running on aws. The current version of kubectl is git version:"1.8.3". I will need to set up a few users that will be able to access the cluster and manage it. can you point me to the correct documentation to this please. 

Thanks

**Comment by hingstarne** [comment]
We solved this by adding them afterwards via terraform to the bucket.
You can use this as a boilerplate or maybe other people have smarter integrations.

```
variable "bucket" {
  description = "bucket for kops and or terraform"
  default     = "terraform-bucket"
}

variable "path" {
  description = "path within the bucket pointing to the kops objects"
}


variable "k8s-users" {
  type = "map"

  default = {
    myuser1         = "token1"
    myuser2         = "token2"
  }
}

resource "aws_s3_bucket_object" "secrets-known_tokens" {
  count = "${length(keys(var.k8s-users))}"

  bucket  = "${var.bucket}"
  key     = "${var.path}/secrets/${element(keys(var.k8s-users), count.index)}"
  content = "${format("{\"Data\":\"%s\"}", base64encode(var.k8s-users[element(keys(var.k8s-users), count.index)]))}"
}

```

**Comment by chrislovecnm** [comment]
@anitakumar what type of users?

**Comment by ps-aux** [comment]
Just FYI. No longer work in 1.9.1. More info https://github.com/kubernetes/kops/issues/2354#issuecomment-307927218
