### ISSUE TITLE
Kubelet and cadvisor?

### ISSUE THREAD

**Issue by stevezau** [kubernetes/kops#413]
Hi,

For some reason cadvisor and kubelet does exist on a new cluster i've deployed using kops..

Shouldn't they be auto deployed? Maybe as a manifest?

**Comment by chrislovecnm** [comment]
What is the status of this?

**Comment by kris-nova** [comment]
@stevezau - Can we get a tad more information?

Replication steps? Which cloud? How do you know they are missing?

**Comment by stevezau** [comment]
closing this issue, i thought cadvisor ran as a pod, didn't realise it's included in kubelet
