### ISSUE TITLE
Unable to provision to a VPN with 2 CIDR's in AWS

### ISSUE THREAD

**Issue by mattlawnz** [kubernetes/kops#4131]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.8.0 (git-5099bc5)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
v1.8.4

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
kops create cluster  --zones ap-southeast-2a --topology private --dns-zone aws.twg.co.nz --networking calico --name=dev-k8s.aws.twg.co.nz --vpc=${VPC_ID} --network-cidr=10.20.4.0/22 -v 10

5. What happened after the commands executed?
It failed with:
I1222 13:34:25.860663    9962 request_logger.go:45] AWS request: ec2/DescribeVpcAttribute
I1222 13:34:25.933890    9962 request_logger.go:45] AWS request: ec2/DescribeVpcAttribute
I1222 13:34:25.978788    9962 changes.go:81] Field changed "CIDR" actual="10.20.0.0/22" expected="10.20.4.0/22"
I1222 13:34:25.978832    9962 changes.go:81] Field changed "Tags" actual="map[]" expected="map[kubernetes.io/cluster/dev-k8s.aws.twg.co.nz:shared]"
W1222 13:34:25.978875    9962 executor.go:109] error running task "VPC/dev-k8s.aws.twg.co.nz" (9m48s remaining to succeed): Field cannot be changed: CIDR
I1222 13:34:25.978890    9962 executor.go:124] No progress made, sleeping before retrying 1 failed task(s)

6. What did you expect to happen?
I expected it to pick up the other CIDR

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-12-22T00:34:11Z
  name: dev-k8s.aws.twg.co.nz
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://priv-aws-twg-co-nz-state/dev-k8s.aws.twg.co.nz
  dnsZone: aws.twg.co.nz
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-ap-southeast-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-ap-southeast-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterPublicName: api.dev-k8s.aws.twg.co.nz
  networkCIDR: 10.20.4.0/22
  networkID: vpc-6982d70d
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.20.4.128/25
    name: ap-southeast-2a
    type: Private
    zone: ap-southeast-2a
  - cidr: 10.20.4.0/28
    name: utility-ap-southeast-2a
    type: Utility
    zone: ap-southeast-2a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-22T00:34:11Z
  labels:
    kops.k8s.io/cluster: dev-k8s.aws.twg.co.nz
  name: master-ap-southeast-2a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-2a
  role: Master
  subnets:
  - ap-southeast-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-22T00:34:11Z
  labels:
    kops.k8s.io/cluster: dev-k8s.aws.twg.co.nz
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-southeast-2a

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

I1222 13:34:25.860663    9962 request_logger.go:45] AWS request: ec2/DescribeVpcAttribute
I1222 13:34:25.933890    9962 request_logger.go:45] AWS request: ec2/DescribeVpcAttribute
I1222 13:34:25.978788    9962 changes.go:81] Field changed "CIDR" actual="10.20.0.0/22" expected="10.20.4.0/22"
I1222 13:34:25.978832    9962 changes.go:81] Field changed "Tags" actual="map[]" expected="map[kubernetes.io/cluster/dev-k8s.aws.twg.co.nz:shared]"
W1222 13:34:25.978875    9962 executor.go:109] error running task "VPC/dev-k8s.aws.twg.co.nz" (9m48s remaining to succeed): Field cannot be changed: CIDR
I1222 13:34:25.978890    9962 executor.go:124] No progress made, sleeping before retrying 1 failed task(s)

9. Anything else do we need to know?

Our first CIDR in our VPC is 10.20.0.0/22 
We added 10.20.4.0/22 for this deployment.

I see that people have mentioed editing the config file to insert the following:
  additionalNetworkCIDRs:
  - 10.2.0.0/16

The abbove according to
https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md

When I do that, I get this:

# Found fields that are not recognized
# ...
#     name: dev-k8s.aws.twg.co.nz
#   spec:
# +   additionalNetworkCIDR:
# +   - 10.20.0.0/22

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by chrislovecnm** [comment]
I am fairly certain we added this feature in master. Please give master a try, or you will need to wait for the 1.9 release.

**Comment by mmacfadden** [comment]
I think this is a duplicate of #3536.

**Comment by chrislovecnm** [comment]
/assign @rdrgmnzs 

@rdrgmnzs was this fixed?  Is it in kops 1.8?

**Comment by rdrgmnzs** [comment]
@chrislovecnm yeah as @mmacfadden mentioned this was landed post 1.9 as it needed an updated of the aws SDK and it was too late in the validation process of 1.8 to make those changes.

Good new is that I have an internal build of 1.8 with the patches and have been using it for a while with no issues so far.

**Comment by mmacfadden** [comment]
I have used it in master and it seems to be working there also.
