### ISSUE TITLE
Upgrade Calico to v2.6.3 or higher?

### ISSUE THREAD

**Issue by tudor** [kubernetes/kops#4139]
We are hitting this bug in Calico: https://github.com/projectcalico/confd/issues/32, which is a high-priority issue causing new nodes (added via an autoscaler) to lose connectivity to pods on old nodes.

The bug was fixed in Calico v2.6.3, see https://github.com/projectcalico/calico/issues/1420, but kops 1.8.0 is still on 2.6.2.

Is there any chance that kops could be upgraded to 2.6.3?

Thanks!

Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.8.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
1.8.0

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

5. What happened after the commands executed?

6. What did you expect to happen?

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by vietwow** [comment]
Calico v3.0.1 is released, so it would be great if kops upgrade to this version :)

**Comment by chrislovecnm** [comment]
Happy to accept PRs ...

**Comment by tsupertramp** [comment]
Just looked into it - First we have to ensure etcdv3 cluster upgrade is default. Otherwise calico v3 will not work. (source: https://docs.projectcalico.org/v3.0/getting-started/kubernetes/upgrade/) - But will dig into 2.6.x pr.

**Comment by tsupertramp** [comment]
Checked k8s config between 2.6.2 => 2.6.5, only image version updated.
```
-# Canal w/ Calico Version v2.6.2
-# https://docs.projectcalico.org/v2.6/releases#v2.6.2
+# Canal w/ Calico Version v2.6.5
+# https://docs.projectcalico.org/v2.6/releases#v2.6.5
 # This manifest includes the following component versions:
-#   calico/node:v2.6.2
-#   calico/cni:v1.11.0
+#   calico/node:v2.6.5
+#   calico/cni:v1.11.2
 #   coreos/flannel:v0.9.0 (bug with v0.9.1: https://github.com/kubernetes/kops/issues/4037)

 # This ConfigMap can be used to configure a self-hosted Canal installation.
@@ -103,7 +103,7 @@ spec:
         # container programs network policy and routes on each
         # host.
         - name: calico-node
-          image: quay.io/calico/node:v2.6.2
+          image: quay.io/calico/node:v2.6.5
           env:
             # Use Kubernetes API as the backing datastore.
             - name: DATASTORE_TYPE
@@ -183,7 +183,7 @@ spec:
         # This container installs the Calico CNI binaries
         # and CNI network config file on each node.
         - name: install-cni
-          image: quay.io/calico/cni:v1.11.0
+          image: quay.io/calico/cni:v1.11.2
           command: ["/install-cni.sh"]
           env:
             - name: CNI_CONF_NAME```

PR would be easy but how should i test this responsible.
I could spin up a cluster with 2.6.2 and then upgrade to 2.6.5 and check if everything still working / checking logs a bit + Spin up only a 2.6.5 cluster and see if this works. 3 master + 3 node clusters?

How would you do it? @chrislovecnm

**Comment by valdisrigdon** [comment]
FYI we've done a calico 2.6.2 to 2.6.6 upgrade by changing the calico `DaemonSet` to `RollingUpgrade` and then updating the image on an already created cluster. The upgrade was successful.

**Comment by thomasjungblut** [comment]
fyi, a couple of kubectl commands to ease your operational life:

```
kubectl patch ds/calico-node -p='{"spec":{"updateStrategy":{"type":"RollingUpdate"}}}' -n kube-system
kubectl set image ds/calico-node install-cni=quay.io/calico/cni:v1.11.2 -n kube-system
kubectl set image ds/calico-node calico-node=quay.io/calico/node:v2.6.5 -n kube-system
kubectl rollout status ds/calico-node -n kube-system
```
