### ISSUE TITLE
kops creates (maybe) incomplete cluster

### ISSUE THREAD

**Issue by aardelean** [kubernetes/kops#4140]
------------- BUG REPORT TEMPLATE --------------------

1. kops version 1.8.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
kubectl 1.9.0

3. What cloud provider are you using?
aws

4. What commands did you run?  What is the simplest way to reproduce this issue?
Following the aws tutorial.
https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/cluster-install#create-a-gossip-based-kubernetes-cluster-with-kops

Successfully created everything until the kubernetes cluster.

with the command: 
`kops create cluster \
  --name example.cluster.k8s.local \
  --zones eu-central-1a \
  --state s3://example-state-store-kvkljwlakipauhkbkqzqpztrqtiqnwzz \
  --yes`

5. What happened after the commands executed?
The output seemed to be all ok, but from the interface of https://eu-central-1.console.aws.amazon.com/ec2/v2/home?region=eu-central-1#Instances:sort=instanceId
I see only 2 nodes, no master, both nodes having t2.medium size.

More, waiting even 2 hours doesn't help.
Command kops validate cluster fails with 
`cannot get nodes for "example.cluster.k8s.local": Get https://api-example-cluster-k8s-l-1dt7vk-321481216.eu-central-1.elb.amazonaws.com/api/v1/nodes: EOF`

And kubectl get cluster fails with EOF as well.

6. What did you expect to happen?
Expecting to see a fully functioning cluster
7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
`kind: Cluster
metadata:
  creationTimestamp: 2017-12-23T12:09:22Z
  name: example.cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://example-state-store-kvkljwlakipauhkbkqzqpztrqtiqnwzz/example.cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterPublicName: api.example.cluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-23T12:09:22Z
  labels:
    kops.k8s.io/cluster: example.cluster.k8s.local
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-23T12:09:22Z
  labels:
    kops.k8s.io/cluster: example.cluster.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a`
8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?
Tried to uninstall awscli and kops and installed again, same issue happened

**Comment by chrislovecnm** [comment]
Logs from the master? What started?

**Comment by chrislovecnm** [comment]
Set you master to a big t2 or a c4 instance size

**Comment by qwertys-ru** [comment]
I have encountered the same issue. I use the same region (eu-central).
