### ISSUE TITLE
Change good-starter-issue label to standard Github labels

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#4141]
Apparently Github is promoting the use of the labels `help wanted` or `good first issue` as the label for what I think we're calling `good-starter-issue`. I don't think it is likely to make a ton of difference, but it's low impact/effort and if it makes it easier for someone to contribute- that's awesome. 

![image](https://user-images.githubusercontent.com/9451328/34320796-231a1fda-e7b6-11e7-92ac-f267a8e5405b.png)

**Comment by chrislovecnm** [comment]
Do if

**Comment by parispittman** [comment]
We've begun work on this with an issue against the k/community repo. Do you mind weighing in there on thoughts (or +1)? [#1959](https://github.com/kubernetes/community/issues/1959)

**Comment by rifelpet** [comment]
Kops has been using `good first issue` consistently so this is safe to close

/close
