### ISSUE TITLE
Kubernates cannot get nodes error: DNS issue

### ISSUE THREAD

**Issue by ganeshmedhekar** [kubernetes/kops#4144]
Hi,

We are deploying kubernates 1.8 setup on AWS private VPC which is having DHCP enabled with our AD running on AWS EC2 instance. We are using Route 53 subdomain.
The setup complete but when we run the below command find the issiue with the DNS resolution.
Command and error:
$ kops validate cluster
Using cluster from kubectl context: test-cluster.example.com

Validating cluster test-cluster.example.com

cannot get nodes for "test-cluster.example.com": Get https://api.test-cluster.example.com/api/v1/nodes: dial tcp xxx.xxx.xxx.xxx:443: i/o timeout

**Comment by thebadmonkeydev** [comment]
I'm seeing this same issue in a public hosted zone...it seems that no matter how long I wait, the DNS records for the api endpoint aren't getting updated.  I know that an update is happening because the etcd records are getting updated to a proper IP.

**Comment by huang-jy** [comment]
if api-internal.test-cluster.example.com is set, try setting api.test-cluster.example.com to the same IP.

**Comment by huang-jy** [comment]
IS this still happening?

**Comment by ganeshmedhekar** [comment]
Hi, 
Thanks for ur comments. We have resolved this by setting AWS route 53 private domain and make the cluster as a private domain but definitely would like to know the concrete resolution for this.

**Comment by huang-jy** [comment]
I used to have this problem, but when I re-created use private topology, (which creates the api entry as an *alias*) the problem was fixed.

**Comment by ganeshmedhekar** [comment]
Hi, 
 We do have requirement where we want to put the master and worker node into separate VPC. Does KOPS support the cluster across multiple VPC?

**Comment by huang-jy** [comment]
My suggestion would be to try. Since the cluster uses security groups to communicate, I would think it would be able to.

**Comment by chrislovecnm** [comment]
Kops does not support masters in a separate vpc.

**Comment by huang-jy** [comment]
I stand corrected :)

**Comment by ganeshmedhekar** [comment]
Thanks @Chris and @Huang. Do we have any article within KOPS which states it does not support separate VPC, this will help us to put our stand and make our decision for the deployment.

**Comment by ganeshmedhekar** [comment]
Though we have tried with changing the KOPS configure file but it does not help, still would like to confirm if we do have any article for proof if concern. I appreciate your help on this

**Comment by huang-jy** [comment]
A VPC is meant to be isolated from other VPCs. If you want to talk between them, you'd need to peer it, and that itself may result in different subnets.

Why do you have to use multiple VPCs anyway?

**Comment by ganeshmedhekar** [comment]
We have drop the idea to use multiple VPC. Thanks for the support
