### ISSUE TITLE
Support TLS between Etcd when using Calico

### ISSUE THREAD

**Issue by tgrosinger** [kubernetes/kops#4146]
1. Describe IN DETAIL the feature/behavior/change you would like to see.

The backing Etcd cluster should be able to be secured using the `enableEtcdTLS` option documented [here](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#etcdclusters-v3--tls) when using Calico. According to the resolution of https://github.com/kubernetes/kops/issues/4039 this is not possible currently.

It looks like the work to enable TLS between Etcd has been done in https://github.com/kubernetes/kops/pull/3114, however there is some incompatibility when using Calico.

**Comment by tgrosinger** [comment]
CC:
* @gambol99 - Added Etcd TLS support
* @blakebarnett - responded to my other related issue
* @caseydavenport - had an implementation suggestion on my related issue

**Comment by chrislovecnm** [comment]
Rolling updates are part of the challenge with this btw. Getting new keys to the old etcd servers.

**Comment by tgrosinger** [comment]
This commit (https://github.com/gyuho/etcd/commit/4e21f87e3d014d606bb3ba2a89731a7d24806611) actually might help with that. I was something we added because we need to reload certificates in etcd internally. Basically you just need to update the certificate files on disk and etcd will pull them in!

**Comment by rwiggins** [comment]
I believe this is also an issue for Romana. I can file a separate issue for that if needed.

**Comment by caseydavenport** [comment]
Provided the infrastructure is in place to distribute the requisite keys then enabling this is Calico should be straightforward.

The calico components all take options to configure this: https://docs.projectcalico.org/v2.6/reference/node/configuration

^ See the `ETCD_` options in the above link

**Comment by gambol99** [comment]
Taking a look at this now .. I shouldn't be too difficult to support
/assign

**Comment by gambol99** [comment]
Working on the PR in #4240

**Comment by chrislovecnm** [comment]
Migration is the fun part, you would need to check with calico to see if they have worked it out yet

**Comment by tgrosinger** [comment]
#4240 was merged. Should this be closed now?
