### ISSUE TITLE
kops replace does not like Kind=SSHCredential in kops.yaml

### ISSUE THREAD

**Issue by frittentheke** [kubernetes/kops#4149]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

> Version 1.8.0 (git-5099bc5)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

> v1.9.0

3. What cloud provider are you using?

> AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

> 
> kops create -f kops.yaml
> 
> kops update cluster \
>    --name=mylittlek8scluster \
>    --target=terraform \
>    --out=./terraform/
> 

to create the cluster, which worked just fine.

Then I changed i.e. the image name in the kops.yaml and ran

> kops replace -f kops.yaml
>  
> kops update cluster \
>    --name=mylittlek8scluster \
>    --target=terraform \
>    --out=./terraform/
> 

5. What happened after the commands executed?

An error was thrown: 
> error: Unhandled kind "kops/v1alpha2, Kind=SSHCredential" in kops.yaml

After commenting out the SSHCredentials the replace/update ran just fine.

6. What did you expect to happen?

I would like to use the kops.yaml I created the cluster with to later change certain configuration without commenting out i.e. SSHCredentials.

**Comment by 1810755jiawei** [comment]
open
