### ISSUE TITLE
After upgrading to 4.4 kernel on my nodes, prometheus is not reading correctly container_cpu_usage_seconds_total and (node_filesystem_size/node_filesystem_free)

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kops#415]
Other metrics might not be working as well, I've noticed that ones because of my monitoring dashboard.

**Comment by chrislovecnm** [comment]
Did you file an issue with the Prometheus folks?

**Comment by chrislovecnm** [comment]
@felipejfc did this get fixed with the kernel upgrade?

**Comment by justinsb** [comment]
@felipejfc can you possibly share the prometheus configuration you're using, or at least some docs you would recommend?

**Comment by ese** [comment]
To set-up prometheus i would recommend https://github.com/coreos/kube-prometheus. I don't have problems with it so far

**Comment by chrislovecnm** [comment]
Please re-open if you have not worked this out.
