### ISSUE TITLE
How to set `--live-restore=false` on nodes docker?

### ISSUE THREAD

**Issue by marciorodrigues87** [kubernetes/kops#4160]
Hi Guys!

It's more a question than a bug or a feature request (I can open another issue with the correct template later)

We've experiencing some pod restarts with the following message in our kubernetes cluster:

`Pod sandbox changed, it will be killed and re-created.`

Some people recommends to set this flag to prevent this behaviour (https://docs.google.com/document/d/1YHwzDj7jUGqnTdFoCDRE3GTaUtTWUS8ROYKPRdb9WpU/edit)

Is there a way to set this flag through kops configuration?

**Comment by rdrgmnzs** [comment]
This option is unfortunately not currently configurable with Kops https://godoc.org/k8s.io/kops/pkg/apis/kops#DockerConfig so it would have to be added.

I'm configuring it, but I'm also creating my own Linux images and so I just bake that configuration in. This however can get messy and is probably not what you'd want to do.

**Comment by marciorodrigues87** [comment]
Closed in https://github.com/kubernetes/kops/pull/4169

**Comment by tmegow** [comment]
@marciorodrigues87 our team has a production k8s cluster (GCE) which has also been experiencing nodes with `Pod sandbox changed, it will be killed and re-created.` pod errors. From inquiring about the symptom on [SO](https://stackoverflow.com/questions/49159784/container-optimized-os-k8s-nodes-losing-google-ip-forwarding-daemon-service-ips) we've discovered that removing live-restore from the docker daemon config and restarting docker resolves the symptom.

Having read the docker [live-restore docs](https://docs.docker.com/config/containers/live-restore/), can you confirm if one of the benefits gained from enabling docker's live-restore (within the kubernetes ecosystem) is preserving Running pods between instance restarts? If so, is this feature the primary benefit to enabling live-restore within the kubernetes ecosystem? We're running a few nodes with live-restore disabled as a test, however I'm trying to discover the full impact of disabling this feature.
