### ISSUE TITLE
Feature Request: Inherit Tags/Labels onto referenced resources

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kops#4162]
using `cloudLabels` allows you to tag instances/nodes, but the resources associated by that node (volumes, snapshots,etc.) are not. When tags are used for billing purposes, this is a problem, especially if/when the resources are detached.

Current workaround is to use something like Graffiti Monkey which will go through and add/update tags onto the resources associated by an instance, but it would be good to include this within kops as part of the provisioning (i.e. when provisioning the node, and putting the label onto the instance, it also puts it on the root volume, and any additional disks)

**Comment by chrislovecnm** [comment]
@huang-jy I assume that you are working in AWS.  The last time I checked this was a limitation of using ASG.  We could write something into protokube to tag the volumes as well.  Can you provide more details on what you would expect?

**Comment by huang-jy** [comment]
@chrislovecnm yes, I am using AWS, though I suspect something similar would be needed on the other supported clouds too.

Basically if I tag a node using cloudLabels with something like
```
cloudLabels:
  billing: product-team
```
Then the volumes (both the root volume and any additional volumes configured to be attached) should be tagged similarly.

**Comment by huang-jy** [comment]
Bumping as a similar issue has been raised #5129
