### ISSUE TITLE
 Clock Sync at the Node Level

### ISSUE THREAD

**Issue by naveeng68** [kubernetes/kops#4173]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1.I am using  Kops version-1.8.0
2.Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?

4. What commands did you run?  What is the simplest way to reproduce this issue?

5. What happened after the commands executed?

6. What did you expect to happen?

7. Please provide your cluster manifest. Execute
  apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-12-12T06:39:18Z
  name: *********
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["autoscaling:*"],
          "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": ["route53:*"],
            "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": ["application-autoscaling:*"],
            "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": ["iam:*"],
            "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": ["cloudwatch:*"],
            "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"],
            "Resource": ["*"]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["autoscaling:*"],
          "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": ["route53:*"],
            "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": ["iam:*"],
            "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": ["application-autoscaling:*"],
            "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"],
            "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": ["cloudwatch:*"],
            "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://*********
  dnsZone:*******
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: events
  iam:
    legacy: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.5
  masterInternalName: api.internal.********
  masterPublicName: api.*********
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  - cidr: 172.20.64.0/19
    name: us-west-2b
    type: Public
    zone: us-west-2b
  - cidr: 172.20.96.0/19
    name: us-west-2c
    type: Public
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-12T06:39:18Z
  labels:
    kops.k8s.io/cluster: ********
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxSize: 3
  minSize: 1
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-12T06:39:18Z
  labels:
    kops.k8s.io/cluster: ********
  name: master-us-west-2b
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxSize: 3
  minSize: 1
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-12T06:39:18Z
  labels:
    kops.k8s.io/cluster: ********
  name: master-us-west-2c
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxSize: 3
  minSize: 1
  role: Master
  subnets:
  - us-west-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-12T06:39:18Z
  labels:
    kops.k8s.io/cluster: ********
  name: nodes-us-west-2a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxSize: 10
  minSize: 1
  role: Node
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-12T06:39:18Z
  labels:
    kops.k8s.io/cluster: ********
  name: nodes-us-west-2b
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxSize: 10
  minSize: 1
  role: Node
  subnets:
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-12T06:39:18Z
  labels:
    kops.k8s.io/cluster: ********
  name: nodes-us-west-2c
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxSize: 10
  minSize: 1
  role: Node
  subnets:
  - us-west-2c

Recently we had an issue where one of the containers (and likely the underlying EC2 instance) suffered major clock drift. It would appear that clock syncing is not provided out of the box.
Could you please let us know how can we overcome this issue with kops or kubernetes.

**Comment by 007** [comment]
Sorry I missed your birthday #4173 - happy birthday!
