### ISSUE TITLE
can't delete cluster generated by kube-up.sh

### ISSUE THREAD

**Issue by mohanbmahajan** [kubernetes/kops#418]
I did following before trying to delete the cluster,
1. installed kubectl and configured it to point to the correct cluster (verified with kubectl cluster-info
2. Set AWS_PROFILE using - aws config
3. Set up a DNS hosted zone in Route 53, and created entry for XXX.domain.com

After this I wanted to delete the cluster,

${GOPATH}/bin/kops delete cluster XXX.domain.com

This gives me following error,

F0909 06:08:46.419987   17931 delete_cluster.go:33] cluster "XXX.domain.com" not found

**Comment by mohanbmahajan** [comment]
@justinsb is it possible using kops?

**Comment by justinsb** [comment]
It should be possible with the `--external` flag.  That says that the cluster is not registered in kops.  I believe you will then also have to specify the `--region` flag.

Do run this first _without_ `--yes` and make sure that what it is proposing to delete is correct!

And let me know here of any issues!

**Comment by mohanbmahajan** [comment]
Thanks @justinsb for your reply.
I tried it with following command,
${GOPATH}/bin/kops delete cluster XXX.domain.com  --external --region=us-west-2

and the o/p is,

No resources to delete

Cluster deleted

But k8s cluster's AWS EC2 instances are still there, "kubectl cluster-info" showing the cluster is still there.

I think, I have not configured kops rightly, when I do,
${GOPATH}/bin/kops get clusters

it gives me,
No clusters found

How to tell kops to read the clusters?

**Comment by mohanbmahajan** [comment]
I was using the wrong clustername (route53 mapping name)
Got the correct one by looking at the KubernetesCluster tag on your AWS resources.

**Comment by chrislovecnm** [comment]
What is the status on this?

**Comment by justinsb** [comment]
Sounds like it was fixed with the cluster name from the tags.

Will close, we can always reopen.
