### ISSUE TITLE
Additional IAM permission required for Romana

### ISSUE THREAD

**Issue by cgilmour** [kubernetes/kops#4183]
Version: kops v1.8.x
Cloud Provider: AWS
CNI: Romana

With a basic setup, the IAM role for masters does not have permission for ec2:ReplaceRoute
While looking for the best way to fix this, I noticed a few things:
`// Network Routing Permissions - May not be required with the CNI Networking provider` [comment](https://github.com/kubernetes/kops/blob/2fdf83454b3812c2219f18bf217e2ce9ba9aa527/pkg/model/iam/iam_builder.go#L547)

Also that the `CreateRoute` permission does not have any conditions/restrictions, but `DeleteRoute` only works on tables that have the matching `KubernetesCluster` tag.

I'm happy to do the code changes and testing to fix these bits up, but would like a bit of input first.
The "easy" way would be to put `CreateRoute`, `DeleteRoute` and `ReplaceRoute` all in the same section (`kopsK8sEC2MasterPermsTaggedResources`).
But the comment linked above seems to suggest that CNIs should be in charge of adding the network routing permissions they need, eg: in `addRomanaCNIPermissions`.

Which approach would you prefer?

**Comment by chrislovecnm** [comment]
> But the comment linked above seems to suggest that CNIs should be in charge of adding the network routing permissions they need, eg: in addRomanaCNIPermissions.

^ that is what I would rather have.  Easier to track that way.

**Comment by chrislovecnm** [comment]
@cgilmour ping me about e2e testing, we need to implement some testing to not have this happen in the future.

**Comment by chrislovecnm** [comment]
Is this fixed?

**Comment by cgilmour** [comment]
Hi @chrislovecnm , sorry I dropped the ball on this one. I have _a_ fix, but I thnk it'd be disruptive to other CNIs. I'll redo it in a different way and submit the PR after it's tested.

**Comment by cgilmour** [comment]
Fixed in #4365, closing.
