### ISSUE TITLE
Assess moving from Debian to Amazon Linux 2 for base AMI

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#4190]
They now support systemd https://aws.amazon.com/amazon-linux-2/, but I think are running the 4.9 kernel.  Filing this as a placeholder, as the AMI is not released as a stable image as of yet.

**Comment by sonaltr** [comment]
I am currently trying this out and I get the following error:

```
W0417 17:05:49.744748   32442 identify.go:103] unhandled /etc/os-release info "NAME=\"Amazon Linux\"\nVERSION=\"2 (2017.12)\"\nID=\"amzn\"\nID_LIKE=\"centos rhel fedora\"\nVERSION_ID=\"2\"\nPRETTY_NAME=\"Amazon Linux 2 (2017.12) LTS Release Candidate\"\nANSI_COLOR=\"0;33\"\nCPE_NAME=\"cpe:2.3:o:amazon:amazon_linux:2\"\nHOME_URL=\"https://amazonlinux.com/\"\n"
W0417 17:05:49.744793   32442 main.go:141] got error running nodeup (will retry in 30s): error determining OS distribution: cannot identify distro
```

**Comment by sonaltr** [comment]
@chrislovecnm I don't see Amazon Linux 2 [here](https://github.com/kubernetes/kops/blob/master/nodeup/pkg/distros/identify.go). Am I looking at the wrong place? or can I send a pull request?

I added it [here](https://github.com/sonaltr/kops/blob/5019/nodeup/pkg/distros/identify.go#L100-L102) today. Can I send this as a pull request?

**Comment by zytek** [comment]
@sonaltr any success with Amazon Linux 2 and kops? Would be interested to try it out also.

**Comment by sonaltr** [comment]
@zytek [This](https://github.com/kubernetes/kops/pull/5028) PR treats Amazon Linux 2 as CentOS 7.

Ideally, that should "just" work. I'm waiting on a KOPS release for nodeup (which should be available by Monday hopefully) to give that a spin.

**Comment by kaazoo** [comment]
+1

**Comment by chenrui333** [comment]
interested in this +1

**Comment by Pharb** [comment]
Current status for Amazon Linux 2 support in kops:
- stable LTS image is available: https://aws.amazon.com/amazon-linux-2/release-notes/
- kernel version is `4.14.47-64.38.amzn2.x86_64` in the latest AMI `amzn2-ami-hvm-2.0.20180622.1-x86_64-gp2` 
- kops supports it since 1.10.0-alpha.1
- kops documentation for it is added in #5577

**Comment by Pharb** [comment]
@chenrui333 I don't think I can help you with that question, because I don't work for Amazon.
Maybe you can find an answer here: https://aws.amazon.com/contact-us/

**Comment by olemarkus** [comment]
We just changed from Debian to Ubuntu now. So guess we can consider this assessed.
/close
