### ISSUE TITLE
kops can't create master node in AWS BJS Region

### ISSUE THREAD

**Issue by iwasnobody** [kubernetes/kops#4191]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
kops 1.8.0
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

1.7.11 and 1.8.4

3. What cloud provider are you using?
AWS
4. What commands did you run?  What is the simplest way to reproduce this issue?
kops create cluster \
  --name example.cluster.k8s.local \
  --master-size t2.medium \
  --node-count 2 \
  --master-count 1 \
  --zones $AWS_AVAILABILITY_ZONES \
  --image ami-71dd001c \
  --yes
5. What happened after the commands executed?
Only two nodes instance had been created but no master node appears 
6. What did you expect to happen?
Create master node correctly
7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by eisig** [comment]
Do your follow guides in docs/aws-china.md ?

**Comment by superzhouqi** [comment]
@eisig yes, I follow the aws-china.md, set the AWS_REGION=cn_north_1, make sure the internet can be accessed and copy the AMI from us-west-2, and then run the kops

**Comment by eisig** [comment]
Any error log?  We use terraform to build the clusters in bjs. https://github.com/kubernetes/kops/blob/master/docs/terraform.md

**Comment by superzhouqi** [comment]
@eisig 
Hi eisig:
    Thanks for your reply, I followed the below cmd to create the cluster, no exceptions show but also no master had been created. The ami-1b69bb76 is copied from the us-west-2 region, Any ideas?

export AWS_REGION=cn-north-1
export AWS_AVAILABILITY_ZONES=cn-north-1a,cn-north-1b
export S3_BUCKET=kubernetes-demo
export KOPS_STATE_STORE=s3://${S3_BUCKET} 

kops create cluster \
  --name example.cluster.k8s.local \
  --master-size t2.medium \
  --node-count 2 \
  --master-count 1 \
  --zones $AWS_AVAILABILITY_ZONES \
  --image ami-1b69bb76 \
  --yes

But the master still can't be created, and show the following the information
aws_autoscaling_group.master-cn-north-1a-masters-example-cluster-k8s-local: Still creating... (17m20s elapsed)
