### ISSUE TITLE
Bastion box does not get key added to it

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kops#4195]
When creating a box with a bastion role, I'm finding that while it does come up, and gets a public IP and is accessible, it has no private key on it, so when you attempt to SSH into the master or worker nodes, you cannot until you copy the private key you used to create the cluster into the bastion box.

**Comment by chrislovecnm** [comment]
This is as designed. You can use ssh agent forwarding to forward the key

**Comment by huang-jy** [comment]
Okay, let me try that, thank you

**Comment by huang-jy** [comment]
If anyone wants the command:

`ssh -i /path/to/cluster_rsa_key -o ProxyCommand='ssh -W %h:%p admin@bastion.$CLUSTER_NAME' admin@MASTER_IP`
