### ISSUE TITLE
elbSecurityGroup is also removed from node security group when deleted LoadBalancer type service!

### ISSUE THREAD

**Issue by lapee79** [kubernetes/kops#4197]
* kops version: 1.8.0
* kubernetes version: 1.7.11
* kubectl verison: 1.8.4
* cloud provider: AWS

I set elbSecurityGroup at kops cluster spec.
When LoadBalancer Service create Security group rule is added only elbSecurityGroup.
But elbSecurityGroup is also removed from node security group when deleted LoadBalancer type service!
It cause outage of all ELB service.
Is this problem fixed or not?

**Comment by mingyuanzhu** [comment]
Same issue. When delete the one of the services the elbSecurityGroup will be remove from the nodesSecurityGroup Inbound rule.

**Comment by tsupertramp** [comment]
This is only happening for external elbs. Internal are uneffected but experiencing the same issue here. Not 100% understood it. Digging deeper into it. Lucky it happened on the staging cluster for us...

kops: 1.8
k8s version: 1.8.5
kubectl: 1.8.2 (will upgrade and see if it happens as well)

**Comment by lapee79** [comment]
@chrislovecnm 
I set elbSecurityGroup of kops cluster spec described https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#elbsecuritygroup and I created k8s cluster on AWS.

```
spec:
  cloudConfig:
    elbSecurityGroup: sg-123445678
```

When I created first Service(type: LoadBalancer), elbSecurityGroup was added to "Inbound" rule of nodes SecurityGroup. And then that rule unchanged when I additionally create multiful Services(type: LoadBalancer).

But that rule disappear when I delete one of Services(type: LoadBalancer). And all ELB services are blocked because status of instances connected ELB turn info "OutOfService".

I took an emergency measure by adding dummy Service(type: LoadBalancer).

**Comment by piu28** [comment]
I am also facing the same issue. Has anyone found a solution to it? I am using kops1.9.1 and kubernetes1.11. The services are creating with Classic LoadBalancers having the same security group.

**Comment by jonathanbeber** [comment]
@chrislovecnm I think that you're right, the bug it's not a kops' bug. Can you help me to figure out in which project this should be reported?

**Comment by jonathanbeber** [comment]
@chrislovecnm ping!
