### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by anitakumar** [kubernetes/kops#4200]
I have a cluster running on aws and am trying to connect to it from another machine

I created a user in a namespace and then set-credentials and all that was fine

i also copied over the certificate and the pem and client.crt

i have done this before and has worked before but for some reason it is not working.
can you help me troubleshoot this problem

if i run commands like kubectl get nodes i get the connection refused error.

**Comment by anitakumar** [comment]
i used this link to create a user. and generate certificates. https://docs.bitnami.com/kubernetes/how-to/configure-rbac-in-your-kubernetes-cluster/#use-case-1-create-user-with-limited-namespace-access

**Comment by huang-jy** [comment]
```export AWS_ACCESS_KEY_ID='your key'
export AWS_SECRET_ACCESS_KEY='your secret access key'

kops export kubecfg CLUSTER_NAME --state s3://{your k8s state bucket}
```

**Comment by chrislovecnm** [comment]
@anitakumar you figure out your problem?

**Comment by huang-jy** [comment]
Suggest closing this, @anitakumar
