### ISSUE TITLE
No error generated when requesting an unavailable/non-existent instance type

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kops#4205]
I attempted to update my node config to use a t2.nano (which doesn't exist in the region I'm working in) for my nodes and the cluster took the update but never spun it up and it wasn't evident why it didn't spin up until I checked why there was no spot instance request.

**Comment by chrislovecnm** [comment]
I thought that should have been addressed.  How do you recreate this?  Can I please have more context?

**Comment by huang-jy** [comment]
During testing I attempted declared a spot instance size that wasn't available in the region I was testing in, the instance never came up and I only figured this out because the spot request could not be fulfilled.
