### ISSUE TITLE
Segmentation fault while creating new instance group using kops

### ISSUE THREAD

**Issue by abhishek181** [kubernetes/kops#4209]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

Ans. kops version is 1.8.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Ans. kubectl version displays the following:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?

Ans. Cloud provider is AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

Ans. I am running a Kubernetes cluster using gossip-dns. I created the cluster first and then I am trying to add  a bastion host as I am using private topology while launching cluster.

Following command was run to create new bastion instance group:

 kops create instancegroup bastions --role Bastion --subnet=<subnet-name> --name=<Cluster-Name> --state=s3://<bucket-name> 

5. What happened after the commands executed?

Following error displayed after running the command:

goroutine 1 [running]:
main.RunCreateInstanceGroup(0xc420a66460, 0xc420207b00, 0xc42020d780, 0x1, 0x8, 0x4a706e0, 0xc42000c018, 0xc420a56960, 0x0, 0x0)
        /go/src/k8s.io/kops/cmd/kops/create_ig.go:160 +0x2ff
main.NewCmdCreateInstanceGroup.func1(0xc420207b00, 0xc42020d780, 0x1, 0x8)
        /go/src/k8s.io/kops/cmd/kops/create_ig.go:87 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc420207b00, 0xc42020d500, 0x8, 0x8, 0xc420207b00, 0xc42020d500)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4c60000, 0x4c90700, 0x0, 0x0)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x4c60000, 0x4c90710, 0x0)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
        /go/src/k8s.io/kops/cmd/kops/root.go:95 +0x9b
main.main()
        /go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20

6. What did you expect to happen?

Ans. I expected that preview of the instance group that will be created will be displayed

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

Ans. Following is the cluster manifest:

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-01-06T17:12:54Z
  name: <cluster-name>
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://<bucket-name>/<cluster-name>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterPublicName: api.<cluster-name>
  networkCIDR: 172.18.0.0/16
  networkID: <VPC-ID>
  networking:
    kopeio: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.18.32.0/19
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.18.0.0/22
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-01-06T17:12:54Z
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: master-eu-west-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-01-06T17:12:54Z
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: nodes
spec:
  image: ami-c90195b0
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

Ans. Following is the logs after running the command with -v 10:

I0106 18:31:59.924645    8795 s3context.go:163] Found bucket "<bucket-name>" in region "eu-west-1"
I0106 18:31:59.924724    8795 s3fs.go:176] Reading file "s3://<bucket-name>/<cluster-name>/config"
I0106 18:32:00.833044    8795 channel.go:93] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I0106 18:32:00.833073    8795 channel.go:98] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I0106 18:32:00.833087    8795 context.go:140] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I0106 18:32:00.991409    8795 channel.go:107] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-12-02
      providerID: aws
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-12-02
      providerID: aws
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-12-02
      providerID: aws
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
      providerID: aws
      kubernetesVersion: ">=1.8.0 <1.9.0"
    # Moving to stretch in 1.9 (if goes well)
    # BUT... this is causing the submit queue to block, so back to jessie temporarily: https://github.com/kubernetes/kubernetes/issues/56763
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
      providerID: aws
      kubernetesVersion: ">=1.9.0 <1.10.0"
    # Need stretch as default in 1.10 (for nvme)
    # BUT... this is causing the submit queue to block, so back to jessie temporarily: https://github.com/kubernetes/kubernetes/issues/56763
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
      providerID: aws
      kubernetesVersion: ">=1.10.0"
    - providerID: gce
      name: "cos-cloud/cos-stable-60-9592-90-0"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.8.0"
    recommendedVersion: 1.8.4
    requiredVersion: 1.8.0
  - range: ">=1.7.0"
    recommendedVersion: 1.7.11
    requiredVersion: 1.7.0
  - range: ">=1.6.0"
    recommendedVersion: 1.6.13
    requiredVersion: 1.6.0
  - range: ">=1.5.0"
    recommendedVersion: 1.5.8
    requiredVersion: 1.5.1
  - range: "<1.5.0"
    recommendedVersion: 1.4.12
    requiredVersion: 1.4.2
  kopsVersions:
  - range: ">=1.8.0-alpha.1"
    recommendedVersion: 1.8.0
    #requiredVersion: 1.8.0
    kubernetesVersion: 1.8.4
  - range: ">=1.7.0-alpha.1"
    recommendedVersion: 1.7.1
    #requiredVersion: 1.7.0
    kubernetesVersion: 1.7.11
  - range: ">=1.6.0-alpha.1"
    #recommendedVersion: 1.6.0
    #requiredVersion: 1.6.0
    kubernetesVersion: 1.6.13
  - range: ">=1.5.0-alpha1"
    recommendedVersion: 1.5.1
    #requiredVersion: 1.5.1
    kubernetesVersion: 1.5.8
  - range: "<1.5.0"
    recommendedVersion: 1.4.4
    #requiredVersion: 1.4.4
    kubernetesVersion: 1.4.12
I0106 18:32:00.991507    8795 s3fs.go:176] Reading file "s3://<bucket-name>/<cluster-name>/instancegroup/bastions"
I0106 18:32:01.120232    8795 aws_utils.go:39] Querying EC2 for all valid regions
I0106 18:32:01.544115    8795 aws_cloud.go:956] Querying EC2 for all valid zones in region "eu-west-1"
I0106 18:32:01.549036    8795 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1e0 pc=0x26c154f]

goroutine 1 [running]:
main.RunCreateInstanceGroup(0xc420a5e7e0, 0xc42018f680, 0xc4200f1d00, 0x1, 0x8, 0x4a706e0, 0xc42000c018, 0xc420a56e60, 0x0, 0x0)
        /go/src/k8s.io/kops/cmd/kops/create_ig.go:160 +0x2ff
main.NewCmdCreateInstanceGroup.func1(0xc42018f680, 0xc4200f1d00, 0x1, 0x8)
        /go/src/k8s.io/kops/cmd/kops/create_ig.go:87 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc42018f680, 0xc4200f1b00, 0x8, 0x8, 0xc42018f680, 0xc4200f1b00)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4c60000, 0x4c90700, 0x0, 0x0)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x4c60000, 0x4c90710, 0x0)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
        /go/src/k8s.io/kops/cmd/kops/root.go:95 +0x9b
main.main()
        /go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20

9. Describe IN DETAIL the feature/behavior/change you would like to see.

Ans. There shoud be a way to directly add bastion host while launching Kubernetes cluster in private topology with gossip-dns. Currently while using --bastion="true" with gossip-dns , it gives the following error:

error building tasks: unexpected error resolving task "DNSName/bastion.<cluster-name>": Unable to find task "DNSZone/", referenced from DNSName/bastion.<cluster-name>:.Zone

**Comment by chrislovecnm** [comment]
kops create instancegroup bastions --role Bastion --subnet= --name= --state=s3://

are you missing the state store bucket name?

**Comment by chrislovecnm** [comment]
Admittedly this is a bug, as we should not panic

**Comment by abhishek181** [comment]
Hi,

I am not missing the bucket name. If bucket name would not be there , then there would be some error regarding state store bucket.

Any timeline, when this bug will be resolved?

**Comment by karlmutch** [comment]
Using instructions found at,https://github.com/kubernetes/kops/blob/master/docs/bastion.md a similar thing fails in that the utility subnet is missing and so the bastion cannot be created. I believe the two things are related but am not sure how to create the utility subnets manually.

**Comment by geronimoda** [comment]
I'm having exactly the same issue, with the only difference that I'm using --role=Node

Have anyone identified a workaround?

**Comment by pkaramol** [comment]
Same here with `kops 1.8`

**Comment by lsowen** [comment]
I was running into this issue.  My problem was that I was trying to create new instance group which used properly available Availability Zones for my region (`aws ec2 describe-availability-zones --region us-east-1`), but I was referencing an AZ which was not configured for the cluster (`kops --name <cluster> cluster`).

In my case, my cluster is only configured to use `us-east-1a,us-east-1c,us-east-1f`, but I was trying to create a new instance group which referenced `us-east-1b` (`kops create instancegroups <groupname> --subnet us-east-1e,us-east-1c,us-east-1f`).

```
I0404 08:40:35.485132   14364 aws_utils.go:39] Querying EC2 for all valid regions
I0404 08:40:35.770119   14364 aws_cloud.go:956] Querying EC2 for all valid zones in region "us-east-1"
I0404 08:40:35.770274   14364 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1e0 pc=0x26c197f]

goroutine 1 [running]:
main.RunCreateInstanceGroup(0xc420a69c40, 0xc4203c8fc0, 0xc420a151e0, 0x1, 0xb, 0x4a706e0, 0xc420078008, 0xc420a904b0, 0x0, 0x0)
        /go/src/k8s.io/kops/cmd/kops/create_ig.go:160 +0x2ff
main.NewCmdCreateInstanceGroup.func1(0xc4203c8fc0, 0xc420a151e0, 0x1, 0xb)
        /go/src/k8s.io/kops/cmd/kops/create_ig.go:87 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203c8fc0, 0xc420a15130, 0xb, 0xb, 0xc4203c8fc0, 0xc420a15130)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4c601e0, 0x29fc900, 0x0, 0x0)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x4c601e0, 0x4c908f0, 0x0)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
        /go/src/k8s.io/kops/cmd/kops/root.go:95 +0x9b
main.main()
        /go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```
