### ISSUE TITLE
kubectl proxy (dashboard 1.8.1)

### ISSUE THREAD

**Issue by cdenneen** [kubernetes/kops#4228]
```
Error: 'malformed HTTP response "\x15\x03\x01\x00\x02\x02"'
Trying to reach: 'http://100.125.4.66:8443/'
```

**Comment by RobertDiebels** [comment]
Getting the same issue.

**Comment by RobertDiebels** [comment]
@cdenneen I just resolved this by following the instructions from the README.md at the [dashboard project](https://github.com/kubernetes/dashboard). The instructions in the [addons.md ](https://github.com/kubernetes/kops/blob/master/docs/addons.md) were causing the error for me.

**Comment by cdenneen** [comment]
yea `/ui` was deprecated... probably should have closed this issue.

Thanks
