### ISSUE TITLE
Specify etcd version from cli

### ISSUE THREAD

**Issue by nebril** [kubernetes/kops#4236]
I would like to be able to specify etcd version from command line.

I am working on adding Cilium as a CNI plugin for k8s clusters deployed by kops. Cilium needs etcd>=3.1.0, default version in kops is much older.

This change would allow deployment of kops with Cilium as a one-liner, but is possibly beneficial for users not using Cilium, so I want to do this as separate PR.

**Comment by chrislovecnm** [comment]
We actually have this hiding in the `--override` flag.

```console
export KOPS_FEATURE_FLAGS=SpecOverrideFlag
kops create cluster --override 'cluster.spec.etcdClusters[*].version=3.1.10' 
```

You, of course, will need more flags.  This feature has already been exposed to manifest users.

Can we close?
