### ISSUE TITLE
connect to master instance 

### ISSUE THREAD

**Issue by anitakumar** [kubernetes/kops#4238]
i used kops to create a cluster in aws
. however i  did not provide the ssh-public-key in the setup. 
how do i connect to the master/node instances in aws

**Comment by chrislovecnm** [comment]
@anitakumar does ssh with the admin use work?  I assume you used the default ami.

**Comment by anitakumar** [comment]
it didnt work.  i spun up a new cluster with ssh-public-key supplied as i did not have the key
