### ISSUE TITLE
Provider problems when using kops' Terraform output as a module

### ISSUE THREAD

**Issue by jhedev** [kubernetes/kops#4249]
I'm using kops terraform output as a module in our terraform setup. 

The setup defines a provider using the `assume_role` feature to create all resources in a different account, i.e. the provider looks like this:

```hcl
provider "aws" {
  version = "~> 0.1"

  region     = "${var.region}"

  assume_role {
    role_arn     = "arn:aws:iam::${var.account_id}:role/terraform"
  }
}
```

However, since kops defines it's own provider in the generated terraform config like this:

```
provider "aws" {
     region = "eu-central-1"
}
```

the provider setting is overwritten and the main account is used.

I see that it makes sense to include the provider in the terraform config as it is required when using it as a standalone terraform config. However, I'm wondering if you guys have any suggestion how to handle this case when using the terraform config as a module. Or maybe we could add a flag which indicates that we will use the terraform output as a module and thus omits the provider setting?

**Comment by jhedev** [comment]
For anyone reading this issue: #4336 solves my problem and will hopefully get merged soon

**Comment by iMartyn** [comment]
My PR is merged so running from **master** and any releases beyond today the following should work for you -

In your kops.yaml file, you can add the following block to the cluster spec :
```yaml
  target:
    terraform:
      providerExtraConfig:
        alias: ignoreprovider
```
I wish there was a way to sensibly include HCL in the yaml (so you could include the assume_role stuff), but that would require parsing the yaml differently and that's a step beyond what I want to achieve.  At least this should work for you as is.

**Comment by jhedev** [comment]
@iMartyn Thanks so much for your efforts!

**Comment by chrislovecnm** [comment]
@iMartyn can we close this issue now?

**Comment by iMartyn** [comment]
@chrislovecnm I think so, my instinct is to close issues when a release is done that includes the fix but not sure how this project deals with issue fixes.

**Comment by iMartyn** [comment]
@jhedev have you tested the latest release?
