### ISSUE TITLE
AWS: Tests fail if user's availability zones differ

### ISSUE THREAD

**Issue by tazjin** [kubernetes/kops#425]
AWS presents different availability zones to each user with the same name, however it seems to also change the enumeration on some accounts. Example:

```
vincent@stallo ~/go/src/k8s.io/kops (git)-[master] % aws ec2 describe-availability-zones --region us-east-1 | jq '.AvailabilityZones[].ZoneName'
"us-east-1a"
"us-east-1c"
"us-east-1d"
"us-east-1e"
```

The zone `us-east-1b` is "missing" from the list of zones I get back, I suspect other people don't see a `us-east-1e` etc.

It seems like the zone `us-east-1b` is specifically used for testing so this issue causes tests to fail for me when using this specific AWS account:

```
--- FAIL: TestDeepValidate_OK (0.88s)
	validation_test.go:53: error from PopulateClusterSpec: Zone is not a recognized AZ: "us-east-1b" (check you have specified a valid zone?)
I0909 23:23:55.020135   14431 cluster.go:343] Using kubernetes latest stable version: v1.3.6
W0909 23:23:55.020247   14431 populate_cluster_spec.go:182] Normalizing kubernetes version: "v1.3.6" -> "1.3.6"
I0909 23:23:55.310738   14431 aws_cloud.go:453] Known zones: "us-east-1a,us-east-1c,us-east-1d,us-east-1e"
```

**Comment by babo** [comment]
In us-east-1 one of the availability zones is available for the very first accounts only, that was the original datacenter of AWS. Never accounts has no access to that, hence the missing zone in your list. Naming is random, depends on the account, which letter is mapped to that original availability zone.

Test should list the available zones first and select from that.

**Comment by tazjin** [comment]
Interesting to know, wonder why they haven't moved those workloads to one of the "normal" zones yet.

I see two ways to fix this issue properly:

1. Fetch available AZs as @babo said and select from those. There is a test in `deepvalidate_test.go` that relates to valid AZs that are **not** specified in the cluster configuration (`NotIncludedZone` test). This would need some kind of shared state with whatever fetches the zones, so the tests may need reorganising.

2. Mock the AWS client in all tests except explicit integration tests. This may require wrapping in interfaces unless I'm missing some Go-way of injecting mocked dependencies.

Thoughts?

**Comment by justinsb** [comment]
We really shouldn't have been querying AWS at all in tests.  In #506 I'm adding the beginnings of mocks here.  Everything else should be fine even if users have different zones; the one place we need to be careful is docs/examples (I hope) so maybe we should use e.g. us-west-2 in examples.
