### ISSUE TITLE
could not translate host name "xxx.us-east-1.rds.amazonaws.com" to address: Try again

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#4251]
1. What `kops` version are you running? 1.8.0

2. What Kubernetes version are you running? 

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using? aws

I am seeing issue like this in our kops installation in aws:

OperationalError: could not translate host name "xxx.us-east-1.rds.amazonaws.com" to address: Try again

```
  File "django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "newrelic/hooks/database_dbapi2.py", line 101, in __call__
    *args, **kwargs), self._nr_dbapi2_module, (args, kwargs))
  File "appenlight_client/timing/timing_dbapi2.py", line 154, in __call__
    self._e_object, *args, **kwargs),
  File "appenlight_client/timing/__init__.py", line 137, in _e_trace
    result = e_callable(*args, **kw)
  File "psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
```

The RDS dns is there all the time available in public dns. I cannot see any errors in kube-dns. Do anyone have idea what that "Try again" means, out of resources in some component or what? This happens like once in a week in our production - really difficult to reproduce. After this problem happens, the next request to site works again normally (it resolvs dns again).

**Comment by chrislovecnm** [comment]
This appears to be a kube-dns or kube-proxy issue, may no be related to kops. I would search the main repo for issues.

**Comment by okgolove** [comment]
@zetaab hello! Have you found any related issues in kube-dns?

**Comment by zetaab** [comment]
nah I have not tried. It does not happen so often anymore for me. No idea why

**Comment by okgolove** [comment]
Thank you for your feed back.
I've just updated to 1.11.6 and now I have some network issues include with RDS name resolving.

**Comment by zetaab** [comment]
I have two kops clusters in different regions with 1.11.6 and this dns issue with RDS happens like two times per month

**Comment by okgolove** [comment]
What CNI do you use?

If you have this case only two times per month it can work, but I have services using NATS and they need to have stable TCP connection between pods. And my service crashes ~10 times per day because of ping to NATS failures.

**Comment by zetaab** [comment]
I am using kubenet

**Comment by ngoyal16** [comment]
i am new to kubernetes i install the kops default. i run a docker image on it and make expose it throgh the loadbalancer. but we are getting the same issue.

**Comment by ngoyal16** [comment]
@zetaab @okgolove
