### ISSUE TITLE
rootVolumeType accepts only gp2 or io1

### ISSUE THREAD

**Issue by int128** [kubernetes/kops#4256]
Instance group spec `rootVolumeType` seems to accept only `gp2` or `io1` type.
https://github.com/kubernetes/kops/blob/2f3f0548c25e5b6b572bf58f9945f337beb16dd4/pkg/model/awsmodel/autoscalinggroup.go#L71-L72

A SSD volume is best for production but sometimes cheaper `standard` is convenient for experimental use.
Is there any reason to limit the volume type?

I think it is nice to support following volume types as well:
- `standard`
- ~~`st1`~~
- ~~`sc1`~~

Thanks.

**Comment by huang-jy** [comment]
See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html

*st1 and sc1 cannot be used as boot volumes* -- this isn't a restriction by kops, but by AWS.

**Comment by tsuna** [comment]
Shouldn't kops reject st1 / sc1 root volumes instead of accepting it and then failing to spin up EC2 instances?

**Comment by huang-jy** [comment]
@tsuna possible -- that would however require ongoing maintenance to keeep it in line with AWS

**Comment by iamShantanu101** [comment]
Folks, I just faced this issue while I was unaware that st1 cannot be used as a boot volume. I believe a warning message would be really nice.

**Comment by huang-jy** [comment]
@iamShantanu101 Raise a feature request ticket and link it to this one, that way those who visit this issue because they, like yourself, have encountered the problem, can +1 it

**Comment by iamShantanu101** [comment]
@huang-jy Yes, opening it now.
