### ISSUE TITLE
nodeup not being able to parse certificate from `pki/issued/ca/keyset.yaml` causes cluster to not deploy

### ISSUE THREAD

**Issue by nebril** [kubernetes/kops#4257]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.8.0 (git-64ce4835a)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

1.8

3. What cloud provider are you using?

aws

4. What commands did you run?  What is the simplest way to reproduce this issue?
As seen in https://github.com/kubernetes/kops/blob/master/docs/aws.md : 

`kops create cluster --zones us-east-1c $NAME `
`kops update cluster $NAME --yes`

5. What happened after the commands executed?

Kubectl keeps returning `Unable to connect to the server: EOF`

6. What did you expect to happen?

I expected to have a default kops k8s cluster available via kubectl deployed on AWS.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

http://tpaste.us/ZPg6

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

`kops create` output:
http://tpaste.us/lWZL

`kops update` output:
http://tpaste.us/dVkw

9. Anything else do we need to know?
After ssh-ing to master I see that `cloud-final.service` is failed. Logs indicate that it wanted to restart `kops-configuration.service`, which timed out.

`kops-configuration.sercvice` is in `activating` state.
Logs are following: 
```
Jan 11 10:18:18 ip-172-20-60-194 nodeup[702]: I0111 10:18:18.030643     702 s3fs.go:239] Listed files in s3://nebril3-kops-state-store/nebril3.k8s.local/pki/issued/ca: [s3://nebril3-kops-state-store/nebril3.k8s.local/pki/issued/ca/6509731932749428652131860851.crt s3://nebril3-kops-state-store/nebril3.k8s.local/pki/issued/ca/keyset.yaml]
Jan 11 10:18:18 ip-172-20-60-194 nodeup[702]: I0111 10:18:18.030672     702 s3fs.go:176] Reading file "s3://nebril3-kops-state-store/nebril3.k8s.local/pki/issued/ca/6509731932749428652131860851.crt"
Jan 11 10:18:18 ip-172-20-60-194 nodeup[702]: I0111 10:18:18.047543     702 certificate.go:103] Parsing pem block: "CERTIFICATE"
Jan 11 10:18:18 ip-172-20-60-194 nodeup[702]: I0111 10:18:18.047715     702 s3fs.go:176] Reading file "s3://nebril3-kops-state-store/nebril3.k8s.local/pki/issued/ca/keyset.yaml"
Jan 11 10:18:18 ip-172-20-60-194 nodeup[702]: W0111 10:18:18.065960     702 main.go:141] got error running nodeup (will retry in 30s): error building loader: error fetching CA certificate from keystore: error in 'FindCert' attempting to load cert "ca": error loading certificate "s3://nebril3-kops-state-store/nebril3.k8s.local/pki/issued/ca/keyset.yaml": could not parse certificate
```
I believe that this is the culprit, but I don't know how to debug it further. The certificate from `publicMaterial` key inside `keyset.yaml` is valid base64-encoded certificate.

**Comment by chrislovecnm** [comment]
This is a duplicate of https://github.com/kubernetes/kops/issues/4156

**Comment by chrislovecnm** [comment]
Are you working off of master or a branch of yours?

**Comment by nebril** [comment]
This happens to me on master, 1.8 binary and my cilium-specific branch.

**Comment by nebril** [comment]
Seems to be the same issue as #4156. After reading through this I think I may have updated Go to 1.9.2 just before I started seeing this.

**Comment by nebril** [comment]
Checked with kops built from master with Go 1.8.5, could replicate the bug. Closing this one and subscribing to #4156
