### ISSUE TITLE
Longer ID format

### ISSUE THREAD

**Issue by hyunchel** [kubernetes/kops#426]
AWS is fully transitioning into a [longer ID format][0] by December of this year.
Would kops be affected by this change?

[0]: https://aws.amazon.com/blogs/aws/theyre-here-longer-ec2-resource-ids-now-available/

**Comment by justinsb** [comment]
There's no theoretical reason why we should care (we just treat the IDs as strings), and kops seems to be working fine in testing.

Please open issues if you find anything, but I believe kops is fine!
