### ISSUE TITLE
AWS persistent volume issue - PVCs attaching to single node in a cluster

### ISSUE THREAD

**Issue by renuraj18** [kubernetes/kops#4262]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.8.0-alpha.1 (git-991cd8c)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

step1: Provision Storage class on ebs
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  zone: "ap-south-1a"

step2: Create PVC for different application

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

Step3: Nodes going to "Not ready due to multiple volumes attaching to same node and its not distributing the pod to other node as its bound to the volume

ip-10-3-58-187.ap-south-1.compute.internal   NotReady   node      15h       v1.8.4

5. What happened after the commands executed?

Repetitive node failures and pods going to unknown and crash loop as the volumes not detached from the failed node.

6. What did you expect to happen?

Pods should be failed over to other node along with the persistent volumenodes

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

ubuntu@ip-10-3-148-10:~$ kops get --name XXXXXXXX -o yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-01-09T05:04:49Z
  name: XXXXXXXX
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: XXXXXXXX
  dnsZone: Z9Y9PMBBACZLY
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    name: events
  iam:
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterPublicName: api.XXXXXXXX
  networkCIDR: 10.3.0.0/16
  networkID: vpc-0dfa2e65
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.3.32.0/19
    name: ap-south-1a
    type: Private
    zone: ap-south-1a
  - cidr: 10.3.0.0/22
    name: utility-ap-south-1a
    type: Utility
    zone: ap-south-1a
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-01-09T05:04:49Z
  labels:
    kops.k8s.io/cluster: XXXXXXXX
  name: master-ap-south-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - ap-south-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-01-09T05:04:49Z
  labels:
    kops.k8s.io/cluster: XXXXXXXX
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - ap-south-1a

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

**Comment by huang-jy** [comment]
ReadWriteOnce means it can only be r/w once - hence only one node.

Also, AWS defaults to ebs, and this is not read-many, unless you expose a storage service within the cluster.

If you look on AWS volumes, you'll see the volume mounted to a single node.

You might want to consider using NFS if you need something rwm across nodes.
