### ISSUE TITLE
Why have maxSize/minSize on igs?

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kops#4266]
In the instance group definitions, we can specify a max and min size of instance. Why? In AWS, kops doesn't configure autoscaling to scale up/add new instances on load (for example) so having a min of 1 and max of 10 would constantly have a count of 1.

**Comment by FrederikNS** [comment]
I'm pretty sure that the min and max are there so you have the option of adding in auto-scaling. There are already many different projects trying to implement auto-scaling for kubernetes clusters, which works with the AWS Auto-scaling Groups. Kops also offers [a cluster auto-scaler](https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler), though I haven't tried it out.

So if you don't add an auto-scaler then the `max` has no effect

**Comment by huang-jy** [comment]
Yes, I had to configure autoscaling on the ELB manually, after it was created. Is there an option in kops to configure it at the time of creation?

EDIT: https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler

Looks like I hadn't installed this addon :man_facepalming:
