### ISSUE TITLE
Can't we create SharePoint 2013 server with Visual studio 2017 and .net core installed in azure ?

### ISSUE THREAD

**Issue by Madhu788** [kubernetes/kops#4269]
Can't we create SharePoint 2013 server with Visual studio 2017 with .net core in Azure ?

**Comment by chrislovecnm** [comment]
@Madhu788 no idea my friend.  I would check on slack, and stackoverflow.  I am going to close this issue as this is a tad off topic. If you have issues with kops, and not running Sharepoint on k8s please let us know!
