### ISSUE TITLE
Map the cpu-manager-policy kubelet flag

### ISSUE THREAD

**Issue by FrederikNS** [kubernetes/kops#4274]
Kubernetes 1.8 introduced a beta feature to [change the CPU Manager Policy](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/). Some of our workloads are very CPU intensive and suffer badly when they can't keep their CPU caches primed.

In Kubernetes 1.8 the kubelet feature gate `CPUManager=true` was introduced, and `kops` maps that feature gate already, but to actually utilize the alternate CPU Manager, you also need to set the kubelet parameter `--cpu-manager-policy=static`, which is not mapped in `kops`.

Would it be possible to add the `cpu-manager-policy` parameter to the kubelet in kops?

**Comment by faheem-cliqz** [comment]
@FrederikNS Did you find a solution to this, or is the flag `--cpu-manager-policy=static` already mapped?

**Comment by FrederikNS** [comment]
@faheem-cliqz I did not. The reason for me looking for this flag was because we had some workloads that thrashed around between processors, which resulted in them taking much longer than they should. We upgraded our clusters, with a newer Docker and Kubernetes, which fixed our issues, without needing the `--cpu-manager-policy` flag.

**Comment by faheem-cliqz** [comment]
Ok cool. I just wanted the CPU manager support so we could benefit a bit by having exclusive access to CPUs to decrease context switching, and get some more performance/improved tail latencies in cassandra/scylladb. Haven't tested if the flag is mapped, just the issue.

**Comment by yancl** [comment]
@lynchc @justinsb I saw that the `--cpu-manager-policy` flag related changes has been [merged](https://github.com/kubernetes/kops/commit/345e468926abb51a0e2247ed2b77c5906de40405#diff-49042f30611970743f57b25a8a8a6560) into master, so can we have it in kops 1.12 release? If so, that will be great, thanks:)
