### ISSUE TITLE
Specify custom instance template in instance group

### ISSUE THREAD

**Issue by maingoh** [kubernetes/kops#4277]
Hi, 

I would like to deploy a GPU cluster on GCE but I don't find a way to give a predefined `instanceTemplate` to the instance group instead of the `machineType` and `image`. Is it possible ? or can we only specify the google defined machine types ? (those don't contain GPUs by default)

Thanks !

**Comment by chrislovecnm** [comment]
/cc @roberthbailey 

would you have an answer to this one in terms of the google api?

At this point @maingoh we only set a machine type in kops.

**Comment by roberthbailey** [comment]
The google api allows you to specify accelerators when creating a machine (see https://cloud.google.com/compute/docs/gpus/add-gpus#create-new-gpu-instance). The public docs don't seem to show it, but if you look at the [go client libraries](https://raw.githubusercontent.com/google/google-api-go-client/master/compute/v1/compute-gen.go) and search for `type InstanceProperties struct` you can see that you can specify `GuestAccelerators` when creating an instance template. So this is a field that kops would need to set when creating the instance template via some config exposed to the user in the kops api.

**Comment by maingoh** [comment]
I am not sure I understand if it is currenly feasible with kops ? 

If yes, how the yaml config would look like ?
If no and it is not too complicated (i am not familiar with go), I can try to make a PR.

**Comment by chrislovecnm** [comment]
@maingoh no this is not currently supported in kops and would need to be implemented.

**Comment by maingoh** [comment]
With some specifications and guidances I can try to make a PR if you want. Is it something that require a refactoring or can it be implemented "easily" ?

**Comment by chrislovecnm** [comment]
@maingoh it is not a huge change of code but does require some tweaking.

1. we need a new field in the instance group spec. Documentation https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md for how to add a field.
2. follow @roberthbailey's instructions and add the `GuestAccelerators` I think in here https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go

Let me know if you need more help

**Comment by chrislovecnm** [comment]
Oh and reach out on slack if I am around, I get a lot of issue updates, and often they sit awhile.

**Comment by harishsearce** [comment]
@chrislovecnm @roberthbailey i tried to add GuestAccelerators as suggested i.e:

* we need a new field in the instance group spec. Documentation https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md for how to add a field.
* follow @roberthbailey's instructions and add the `GuestAccelerators` I think in here https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go 

As robert mentioned "So this is a field that kops would need to set when creating the instance template via some config exposed to the user in the kops api" where does this changes needs to be done in kops api?

If you could help on this, it would be great, i can raise PR once i am through.

**Comment by harishsearce** [comment]
FYI: i had added fields to the api by following steps mentioned in 1. https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md
GuestAccelerators []*AcceleratorConfig
I could see the updates in IG spec getting reflected with the changes but nothing happening:

Steps i followed:
* Add new field in the the api
* Following changes done in kops/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go:
** Added GuestAccelerators []*AcceleratorConfig in type InstanceTemplate struct 
** And added 
   type AcceleratorConfig struct {
	// AcceleratorCount: The number of the guest accelerator cards exposed
	// to this instance.
	AcceleratorCount int64 `json:"acceleratorCount,omitempty"`

	// AcceleratorType: Full or partial URL of the accelerator type resource
	// to attach to this instance. If you are creating an instance template,
	// specify only the accelerator name.
	AcceleratorType string `json:"acceleratorType,omitempty"`
}
* make apimachinery && make
