### ISSUE TITLE
[Feature Request] make instance group unschedulable

### ISSUE THREAD

**Issue by hiberabyss** [kubernetes/kops#4279]
Sometimes, I need to mark nodes in the new created instance group as `SchedulingDisabled` with `kubectl cordon NODE`.

Is there any method to mark nodes as `SchedulingDisabled` just after creating the instance group? I searched how to implement this with `kops`, but with no luck.

Thanks!

**Comment by jordanjennings** [comment]
You can add a taint to the kops instance group under `spec.taints` to achieve something fairly similar. That will prevent most things from scheduling on there, for example on a tainted instance group I have I see only two pods running (networking and monitoring). Would that work for your use case?

**Comment by mikesplain** [comment]
@hiberabyss Check out the [Instance Group Taints](https://github.com/kubernetes/kops/blob/e42a3f1e50a95a6720d3e5fd7008499a0996cf59/docs/instance_groups.md#adding-taints-to-an-instance-group) docs as @jordanjennings pointed out. That's the best way to accomplish what you're looking for.

**Comment by jordanjennings** [comment]
@hiberabyss Awesome! (don't forget to close the issue if that meets your need)

**Comment by mikesplain** [comment]
Closing for @hiberabyss if it'll let me ;)
/close
