### ISSUE TITLE
Adding subnets requires deletion of ELBs

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kops#4280]
I have a cluster in London region which has just introduced a third AZ. Adding that into the cluster definition and then updating failed with message:

`subnet changes on LoadBalancer not yet implemented: actual=[subneta,subnetb] -> expected=[subneta,subnetb,subnetc]`

I have to delete the ELBs (bastion, api) and let kops recreate, and then do a `--force --cloudonly` rolling-update which causes downtime as it respins the master. The message indicates it is not yet implemented. Do we know if/when this is planned?

**Comment by KashifSaadat** [comment]
Hey @huang-jy, thanks for raising an issue. I've raised PR #4281 which should resolve this, please take a look and let me know if you have any concerns.

**Comment by huang-jy** [comment]
Thanks, @KashifSaadat will keep an eye on that. So far no concerns, but will definitely take a look and give it a go when it's ready for that.
