### ISSUE TITLE
`kops create --dry-run` should not require an SSH key

### ISSUE THREAD

**Issue by metametadata** [kubernetes/kops#4287]
1. What `kops` version are you running?

1.8.0

2. What Kubernetes version are you running?

1.8.0

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

I'm trying to automate cluster creation and the first step is to generate a yaml manifest (as per [manifests_and_customizing_via_api.md](https://github.com/kubernetes/kops/blob/59440bbc6832d31a31bbbcf4869967795819fd63/docs/manifests_and_customizing_via_api.md)):

```
kops create --dry-run --output yaml ...
```

5. What happened after the commands executed?

An error:

```
error reading SSH key file "/Users/yuri/.ssh/id_rsa.pub": open /Users/yuri/.ssh/id_rsa.pub: no such file or directory
```

This is correct, I really don't have this file on my system.

6. What did you expect to happen?

No error. Because dry run shouldn't need an SSH key to produce a manifest yaml.

**Comment by vvbogdanov87** [comment]
@metametadata  Is the issue still exists? I checked on my PC and --dry-run works even if ssh keys are missing. Also I checked "create cluster" code and found that if you specify "--dry-run", RunCreateCLuster function returns before it loads ssh keys.

**Comment by metametadata** [comment]
Thanks. Seems to work as expected in `v1.15.0` on macOS.
