### ISSUE TITLE
Nodes do not have permissions to list AWS R53 hosted zones

### ISSUE THREAD

**Issue by neilhwatson** [kubernetes/kops#4289]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.8.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
1.8.6

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

    kops create cluster --yes --zones ca-central-1a,ca-central-1b --kubernetes-version 1.8.6 <name>
    helm init
    helm install stable/external-dns  --namespace=kube-system --name=external-dns

Then start to deploy normal services with FQDNs

5. What happened after the commands executed?

No DNS record is created in the hosted zone. External-dns logs from k8s show:

    time="2018-01-16T20:39:59Z" level=error msg="AccessDenied: User:  
    arn:aws:sts::000000000:assumed-role/nodes.k01.k8s.example.net/i-036ca678b407648ce is not 
    authorized to perform: route53:ListHostedZones
    status code: 403, request id: 6b67bda8-fafd-11e7-bd8c-3ff3072b5c0e" 

6. What did you expect to happen?

DNS records should have been created.

**Comment by KashifSaadat** [comment]
Hey @neilhwatson, thanks for raising an issue.

Kops creates IAM roles for the Master & Node Instance Groups and grants them the access required to build successfully and operate within the Cluster. If the helm package you're attempting to install requires additional AWS API privileges on the nodes, you can extend the IAM policies generated by Kops and add these permissions in.

Please take a look at the documentation here on how to do so: https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#adding-additional-policies

Let me know how you get on!

**Comment by neilhwatson** [comment]
Do you have an docs on how to add that policy to a newly created cluster config (before actual creation) without human intervention? My goal is to automatically build the cluster and the addons without human intervention.

**Comment by jcardoso-bv** [comment]
The following works for us:

- kops create cluster --dry-run --output yaml > cluster-spec.yaml
- sed --in-place $'/  api:/{e cat spec-additionalpolicies.yaml\n}' cluster-spec.yaml

Ensure "spec-additionalpolicies.yaml" exists and contains whatever policies you need. For external-dns that would be something like this with the appropriate hosted zone replacing "ABCDEFGHIJKLMN":

```
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "route53:ChangeResourceRecordSets"
          ],
          "Resource": [
            "arn:aws:route53:::hostedzone/ABCDEFGHIJKLMN"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "route53:ListHostedZones",
            "route53:ListResourceRecordSets"
          ],
          "Resource": [
            "*"
          ]
        }
      ]
```
