### ISSUE TITLE
Support idempotent sshpublickey secret updates

### ISSUE THREAD

**Issue by wendorf** [kubernetes/kops#4291]
I am building a CD pipeline for configuring and deploying my kops cluster, and am pulling a dynamically-configured public key for the `kops create secret sshpublickey admin --name my-cluster.example.com` step. If I change the public key (which will happen as I rotate credentials), the existing public key remains and the new key is appended, so I see something like this when running `kops get secrets --type sshpublickey`:

```
TYPE		NAME	ID
SSHPublicKey	admin	aa:bb:cc:dd:ee:ff:00:11:22:33:44:55:66:77:88:99
SSHPublicKey	admin	99:88:77:66:55:44:33:22:11:00:ff:ee:dd:cc:bb:aa
```

To automate the removal of the key, I need to enumerate existing IDs (which is a bit annoying since `-o yaml` and `-o json` don't work for secrets) and `kops delete secret` IDs that don't match the new public key.

I would like to have the ability to idempotently update secrets much like `kops replace -f "$CLUSTER_CONFIG" --force` works for the cluster config itself. A possible command for this would be `kops replace secret --type sshpublickey admin --name my-cluster.example.com --force`, which would create the secret if it does not exist, and replace it if it does.

**Comment by metametadata** [comment]
I've recently stumbled upon this too. My current workaround is to first delete `admin` key (and ignore the error in case there's no key yet): `kops delete secret sshpublickey admin`. To me it looks like there's no need to enumerate the IDs if one is careful about not adding duplicate keys from the beginning.
My approach is also described in more detail in https://github.com/kubernetes/kops/issues/4288#issuecomment-358419631.

**Comment by wendorf** [comment]
@metametadata Good idea. It's definitely simpler than my approach.

**Comment by wendorf** [comment]
/remove-lifecycle stale

This would still be great to have.
