### ISSUE TITLE
[Question] Rolling upgrade per instance group

### ISSUE THREAD

**Issue by kureikain** [kubernetes/kops#4300]
Hi,

I have a cluster 1.7.11 with kops 1.7 on flannel and without RBAC. I would like to upgrade to 1.8 but I checked the issue and saw some people with issue which may or may not fixed. In some issues, the cluster was inoperable. My upgrading on a test cluster went smoothly but I feel a bit nervous to do on our production cluster.

In a hope for a better choice, I would like to see if it has anyway for me to control the process of rolling upgrade? Such as I can upgrade a single instance group, then check cluster, until I do this on all instance group.

My plan is to:

1. Upgrade each of master instance group. We have 3 master group. So if anything happen, the cluster still work with other 2 masters until I figured thing out.
2. Upgrade the rest of non master instance group. I divided our workload into multiple instance groups so this can be safer to apply.

In the `--help`, I see this:

```
  kops rolling-update cluster k8s-cluster.example.com --yes \
  --fail-on-validate-error="false" \
  --node-interval 8m \
  --instance-group nodes
```

So I think my thinking works? Just want to ask here and make sure if running ` rolling-update` on every instance group one by one are identical to run ` rolling-update` without instance group

**Comment by huang-jy** [comment]
From the man page:

`      --instance-group stringSlice   List of instance groups to update (defaults to all if not specified)
`
So, yes, if you don't specify an instance group with the rolling-update flag, it will cycle through all the groups (master first, then nodes)

**Comment by chrislovecnm** [comment]
Can we close?
