### ISSUE TITLE
Error reporting while trying to create clusters

### ISSUE THREAD

**Issue by puppetbabu** [kubernetes/kops#4311]
[issue logs.txt](https://github.com/kubernetes/kops/files/1649533/issue.logs.txt)
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
vagrant@ubuntu-xenial:~$ kops version
Version 1.8.0 (git-5099bc5)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
vagrant@ubuntu-xenial:~$ kops create cluster --name=kubernetes.babuacadamy.win --state=s3://kops-state-babu99 --zones=ap-south-1a --node-count=2 --node-size=t2.micro -
-master-size=t2.micro --dns-zone=kubernetes.babuacadamy.win

5. What happened after the commands executed?
giving the below error
I0121 04:05:57.135541   18009 create_cluster.go:439] Inferred --cloud=aws from zone "ap-south-1a"
I0121 04:05:57.137479   18009 create_cluster.go:971] Using SSH public key: /home/vagrant/.ssh/id_rsa.pub
I0121 04:06:02.462705   18009 subnets.go:184] Assigned CIDR 172.20.32.0/19 to subnet ap-south-1a
Previewing changes that will be made:

I0121 04:06:13.015807   18009 apply_cluster.go:880] error reading hash file "https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1": error fetching "https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1": Get https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1: x509: certificate signed by unknown authority

cannot determine hash for https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet (have you specified a valid KubernetesVersion?)

6. What did you expect to happen?
It needs to create the kubernetes clusters in aws

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
>>Cluster it self is not creating
8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
>> i have attaced the log file name "issue logs"
9. Anything else do we need to know?
i think this info will be enough to identify the issue

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by chrislovecnm** [comment]
Can you retry?  This seems to be an error with the hash in google storage.  More an upstream problem, as kops seems to be working fine.
