### ISSUE TITLE
Kubernetes authentication

### ISSUE THREAD

**Issue by ganeshmedhekar** [kubernetes/kops#4312]
Hi,
We are running kubernates 1.8 setup on AWS private VPC which is having DHCP enabled with our windows AD running on AWS EC2 instance. We want to authenticate kubernetes with the windows AD. Kindly suggest the best way to implement this. I have gone thru webhook, keystone, dex but not sure what should be best way and very limited resource on the implementation perspective. if possible provide the link for the approach.

Thanks,
Ganesh

**Comment by chrislovecnm** [comment]
@ganeshmedhekar I would look on stackoverflow or ask on slack.  This may not be the correct forum to get an answer.

**Comment by ganeshmedhekar** [comment]
Thanks

**Comment by DATLegendKujo** [comment]
Create a new build
