### ISSUE TITLE
"kops validate cluster" shows "your nodes are NOT ready" even though the same output shows READY=True for every node

### ISSUE THREAD

**Issue by philrz** [kubernetes/kops#4314]
1. What `kops` version are you running?

`Version 1.8.0 (git-5099bc5)`

2. What Kubernetes version are you running?

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

```
# kops create cluster \
--cloud-labels Infrastructure=xxxx \
--node-count=42 \
--zones=us-east-1b \
--node-size=c3.4xlarge \
 --master-size t2.medium \
philperf.draios.com

# kops update cluster philperf.draios.com --yes
```

5. What happened after the commands executed?

Usually when I do this, within 5-10 minutes, a `kops validate cluster` shows everything is ready. However, once in a while it will report `your nodes are NOT ready` and yet the `READY` column in the same output shows `True` for every node. Sometimes when I'm patient and wait several minutes more, the validate will eventually succeed. However, in this case it has been in this state for 30+ minutes and I am guessing it's never going to validate. If the output gave me any hints as to a particular node that's unhealthy, I'd gladly kick it and let the autoscaling recreate it, but I really have no leads at this point. I'm confident if I just delete the whole cluster and repeat, it'll work fine on a future pass. But with larger clusters of bigger instances, it gets expensive to have to scrap them and start over, so it would be great to know ways I could manually heal it in the future, or prevent this from happening in the first place.

```
# kops validate cluster
Using cluster from kubectl context: philperf.draios.com

Validating cluster philperf.draios.com

INSTANCE GROUPS
NAME                    ROLE    MACHINETYPE     MIN     MAX     SUBNETS
master-us-east-1b       Master  t2.medium       1       1       us-east-1b
nodes                   Node    c3.4xlarge      42      42      us-east-1b

NODE STATUS
NAME                            ROLE    READY
ip-172-20-33-1.ec2.internal     node    True
ip-172-20-33-11.ec2.internal    master  True
ip-172-20-33-117.ec2.internal   node    True
ip-172-20-33-159.ec2.internal   node    True
ip-172-20-34-175.ec2.internal   node    True
ip-172-20-36-153.ec2.internal   node    True
ip-172-20-36-22.ec2.internal    node    True
ip-172-20-36-240.ec2.internal   node    True
ip-172-20-37-22.ec2.internal    node    True
ip-172-20-38-220.ec2.internal   node    True
ip-172-20-38-63.ec2.internal    node    True
ip-172-20-39-119.ec2.internal   node    True
ip-172-20-44-218.ec2.internal   node    True
ip-172-20-45-58.ec2.internal    node    True
ip-172-20-46-252.ec2.internal   node    True
ip-172-20-47-139.ec2.internal   node    True
ip-172-20-47-31.ec2.internal    node    True
ip-172-20-49-15.ec2.internal    node    True
ip-172-20-49-164.ec2.internal   node    True
ip-172-20-49-245.ec2.internal   node    True
ip-172-20-50-117.ec2.internal   node    True
ip-172-20-50-19.ec2.internal    node    True
ip-172-20-50-235.ec2.internal   node    True
ip-172-20-50-99.ec2.internal    node    True
ip-172-20-51-210.ec2.internal   node    True
ip-172-20-51-82.ec2.internal    node    True
ip-172-20-52-164.ec2.internal   node    True
ip-172-20-52-55.ec2.internal    node    True
ip-172-20-53-165.ec2.internal   node    True
ip-172-20-53-51.ec2.internal    node    True
ip-172-20-54-135.ec2.internal   node    True
ip-172-20-55-247.ec2.internal   node    True
ip-172-20-56-68.ec2.internal    node    True
ip-172-20-57-128.ec2.internal   node    True
ip-172-20-57-78.ec2.internal    node    True
ip-172-20-58-130.ec2.internal   node    True
ip-172-20-59-179.ec2.internal   node    True
ip-172-20-59-43.ec2.internal    node    True
ip-172-20-61-1.ec2.internal     node    True
ip-172-20-61-41.ec2.internal    node    True
ip-172-20-62-33.ec2.internal    node    True

Validation Failed
Ready Master(s) 1 out of 1.
Ready Node(s) 40 out of 42.

your nodes are NOT ready philperf.draios.com
```

6. What did you expect to happen?

I am accustomed to it showing all nodes ready within about 10 minutes.

7. Please provide your cluster manifest.

[manifest-yaml.txt](https://github.com/kubernetes/kops/files/1650321/manifest-yaml.txt)

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

[cluster-log.txt](https://github.com/kubernetes/kops/files/1650323/cluster-log.txt)

9. Anything else do we need to know?

**Comment by huang-jy** [comment]
There are only 40 nodes in that list, but you have specified 42. The other 2 probably haven't yet registered themselves into the cluster yet. Check to see if they have shown up on AWS and if they have, check if they are showing ready. If they are, try doing a reboot (not a terminate) on the two boxes to see if they show up.

**Comment by philrz** [comment]
Ah! Thank you @huang-jy. I'm slightly embarrassed how that eluded me, but I'm glad there's such a simple explanation. I'll go ahead and close this issue and open a new one if I should ever find the hunt-&-reboot strategy doesn't work in the future. Your action plan makes perfect sense though.

**Comment by huang-jy** [comment]
Not a problem, it catches me still sometimes ^^

**Comment by philrz** [comment]
BTW @huang-jy, I found myself in this same situation this afternoon and your reboot idea worked like a charm. Got me from 96 to 97 nodes, hence saved me a lot of time & money. If anyone else should stumble onto this issue in the future, I also created a little helper script in Python to dump the set of slave nodes from my AWS that I could `diff` against the set from `kops validate`, and hence easily find the one that needs rebooting.

```
import argparse
import sys
import boto.ec2

# Pipe the output of this through "sort", then compare with the output of:
# kops validate cluster 2>&1 | grep "^ip.*node" | awk '{ print $1 }' | sort

def parse_args():
  parser = argparse.ArgumentParser(description='List AWS instances')
  parser.add_argument('--awsid', help='AWS Access Key ID', required=True)
  parser.add_argument('--awskey', help='AWS Secret Access Key', required=True)
  parser.add_argument('--region', help='AWS Region', default='us-east-1')
  parser.add_argument('--nodename', help='Name of each node to filter by', default='nodes.philperf.draios.com')
  return parser.parse_args()

args = parse_args()
a = boto.ec2.connect_to_region(args.region, aws_access_key_id=args.awsid, aws_secret_access_key=args.awskey)
reservations = a.get_all_reservations()
for reservation in reservations:
  for instance in reservation.instances:
    if instance.tags.get('Name') and instance.tags['Name'] == args.nodename:
      print instance.private_dns_name
```

**Comment by huang-jy** [comment]
I think there's some kind of race condition going on here, that a reboot fixes - though no idea what, and why it sometimes happens and doesn't.

**Comment by vippujain** [comment]
For me, it shows all 59 nodes and says "Ready Node(s) 59 out of 51." Can anyone share any good way to see the fail nodes on cluster ?
Here is the list of nodes - 
/code
ip-172-21-100-20.ap-southeast-1.compute.internal	node	True
ip-172-21-100-90.ap-southeast-1.compute.internal	node	True
ip-172-21-100-91.ap-southeast-1.compute.internal	node	True
ip-172-21-102-97.ap-southeast-1.compute.internal	node	True
ip-172-21-103-62.ap-southeast-1.compute.internal	node	True
ip-172-21-110-114.ap-southeast-1.compute.internal	node	True
ip-172-21-110-35.ap-southeast-1.compute.internal	node	True
ip-172-21-113-122.ap-southeast-1.compute.internal	node	True
ip-172-21-113-35.ap-southeast-1.compute.internal	node	True
ip-172-21-114-139.ap-southeast-1.compute.internal	node	True
ip-172-21-115-235.ap-southeast-1.compute.internal	node	True
ip-172-21-116-233.ap-southeast-1.compute.internal	node	True
ip-172-21-120-112.ap-southeast-1.compute.internal	node	True
ip-172-21-120-95.ap-southeast-1.compute.internal	node	True
ip-172-21-121-160.ap-southeast-1.compute.internal	node	True
ip-172-21-122-224.ap-southeast-1.compute.internal	node	True
ip-172-21-124-163.ap-southeast-1.compute.internal	node	True
ip-172-21-124-86.ap-southeast-1.compute.internal	node	True
ip-172-21-125-154.ap-southeast-1.compute.internal	node	True
ip-172-21-32-40.ap-southeast-1.compute.internal		node	True
ip-172-21-33-241.ap-southeast-1.compute.internal	node	True
ip-172-21-35-143.ap-southeast-1.compute.internal	node	True
ip-172-21-36-107.ap-southeast-1.compute.internal	node	True
ip-172-21-37-154.ap-southeast-1.compute.internal	node	True
ip-172-21-43-219.ap-southeast-1.compute.internal	node	True
ip-172-21-44-52.ap-southeast-1.compute.internal		node	True
ip-172-21-45-12.ap-southeast-1.compute.internal		node	True
ip-172-21-45-158.ap-southeast-1.compute.internal	node	True
ip-172-21-46-112.ap-southeast-1.compute.internal	node	True
ip-172-21-46-42.ap-southeast-1.compute.internal		node	True
ip-172-21-47-161.ap-southeast-1.compute.internal	node	True
ip-172-21-53-227.ap-southeast-1.compute.internal	node	True
ip-172-21-53-41.ap-southeast-1.compute.internal		node	True
ip-172-21-57-44.ap-southeast-1.compute.internal		node	True
ip-172-21-58-11.ap-southeast-1.compute.internal		node	True
ip-172-21-59-113.ap-southeast-1.compute.internal	node	True
ip-172-21-60-184.ap-southeast-1.compute.internal	node	True
ip-172-21-61-35.ap-southeast-1.compute.internal		node	True
ip-172-21-63-152.ap-southeast-1.compute.internal	node	True
ip-172-21-64-223.ap-southeast-1.compute.internal	node	True
ip-172-21-67-85.ap-southeast-1.compute.internal		node	True
ip-172-21-76-254.ap-southeast-1.compute.internal	node	True
ip-172-21-76-89.ap-southeast-1.compute.internal		node	True
ip-172-21-77-223.ap-southeast-1.compute.internal	node	True
ip-172-21-79-23.ap-southeast-1.compute.internal		node	True
ip-172-21-81-215.ap-southeast-1.compute.internal	node	True
ip-172-21-84-174.ap-southeast-1.compute.internal	node	True
ip-172-21-87-136.ap-southeast-1.compute.internal	node	True
ip-172-21-87-6.ap-southeast-1.compute.internal		node	True
ip-172-21-90-111.ap-southeast-1.compute.internal	node	True
ip-172-21-91-129.ap-southeast-1.compute.internal	node	True
ip-172-21-91-183.ap-southeast-1.compute.internal	node	True
ip-172-21-91-229.ap-southeast-1.compute.internal	node	True
ip-172-21-92-146.ap-southeast-1.compute.internal	node	True
ip-172-21-93-132.ap-southeast-1.compute.internal	node	True
ip-172-21-94-33.ap-southeast-1.compute.internal		node	True
ip-172-21-95-182.ap-southeast-1.compute.internal	node	True
ip-172-21-99-117.ap-southeast-1.compute.internal	node	True
ip-172-21-99-33.ap-southeast-1.compute.internal

**Comment by philrz** [comment]
@vippujain: A couple comments back in this issue I pasted a Python script that could help you.

**Comment by huang-jy** [comment]
"says "Ready Node(s) 59 out of 51.""

This means your instance group is expecting 51 good nodes. You have somehow got 59 good nodes. So either you have set a minimum of 51 and a maximum of higher, and/or you have a autoscaler enabled and have a high demand?

**Comment by apoorvakadapa** [comment]
I am unable to list the floating Ip of all the nodes present in kubernetes cluster. I am following https://github.com/larsks/heat-kubernetes

**Comment by huang-jy** [comment]
@apoorvakadapa sounds like an unrelated issue to this one, please raise as a separate issue.
