### ISSUE TITLE
Set max-request-inflight for large cluster 

### ISSUE THREAD

**Issue by charleszheng44** [kubernetes/kops#4322]
Hi,

Can I set the max-request-inflight by using kops? I have tried 

kops edite cluster

spec:
    kubeAPIServer:
        maxRequestInflight: 1000

But it does not been recognized.

Thanks,
Charles

**Comment by chrislovecnm** [comment]
We do not seem to have that exposed in https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go

Good news is that it is super easy to expose see

 https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md

Add the struct value, generate api machinery and you are good to go!

**Comment by integrii** [comment]
This has been added and the issue can be closed.
