### ISSUE TITLE
Kubernetes Dashboard never goes up again after Master Reboot.

### ISSUE THREAD

**Issue by drequena** [kubernetes/kops#4326]
Hello everybody,

I'm running kops 1.7.1 on AWS using weave and my current version of kubernetes is 1.7.2
This cluster is a simple cluster, 1 master, 3 nodes.
After rebooting the master ec2 instance (ssh in to it and rebooted), the dashboard does not start anymore.
I've tried to delete the entire deploy:

kubectl delete -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.7.1.yaml

And recreate:

kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.7.1.yaml

But I keep getting this error from dashboards POD.

kubectl logs -f kubernetes-dashboard-1251224222-29hmz --namespace=kube-system
2018/01/23 00:28:59 Starting overwatch
2018/01/23 00:28:59 Using in-cluster config to connect to apiserver
2018/01/23 00:28:59 Using service account token for csrf signing
2018/01/23 00:28:59 No request provided. Skipping authorization
2018/01/23 00:29:02 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://100.64.0.1:443/version: dial tcp 100.64.0.1:443: getsockopt: no route to host
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

I've also tried to download the dashboard YAML file and point the api server address in the args session:

--api-server-host=https://10.10.30.1:443

But that doesn't helped.
Can someone help me with that? I'm afraid that a reboot in a production cluster may cause the same problem. 

Best regards.

**Comment by griffin-oly** [comment]
I'm in a similar problem.  I have a cluster that works with the exception of the dashboard.  I'm getting same error message.  I have also tried deleting the dashboard with the kubectl delete.  I'd like to be able to figure out how to at least run the dashboard without TLS so I can see it work at least.  I don't know how to make it generate new apiserver certificates.  It appears to start dashboard each time I redeploy it with a 0 length for kubernetes-dashboard-certs.

**Comment by thomasjungblut** [comment]
I do have the same issue using Kops 1.9 and creating a brand-new cluster (calico as the network provider).

**Comment by thomasjungblut** [comment]
I haven't figured out why, but a mitigation is to delete the calico pod on the master node. When it comes back up again the dashboard is accessible.
