### ISSUE TITLE
subnets option is not available in version 1.8.0

### ISSUE THREAD

**Issue by adhadkar** [kubernetes/kops#4340]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.8.0
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
1.9.1
3. What cloud provider are you using?
AWS
4. What commands did you run?  What is the simplest way to reproduce this issue?
kops create cluster --zones=us-east-1b --name=${CLUSTER_NAME} --subnets=${SUBNET_IDS}
5. What happened after the commands executed?
unknown flag: --subnets
6. What did you expect to happen?
k8s cluster should have been created in provided subnets
7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
Doesn't reach till here as --subnets option itself says not available
8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
NA
9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.
Able to use --subnets feature with version 1.8.0 as defined in docs here
https://github.com/kubernetes/kops/blob/master/docs/cli/kops_create_cluster.md
2. Feel free to provide a design supporting your feature request.

**Comment by chrislovecnm** [comment]
That option I think is only in master. Take a look for the docs that are on the git tag.

**Comment by chrislovecnm** [comment]
If it is in master it will be released with 1.9. What does —help show?

**Comment by adhadkar** [comment]
Help doesn't show this option. Looks like it is not supported in current version 1.8.0
