### ISSUE TITLE
Broken default docker config

### ISSUE THREAD

**Issue by MrTrustor** [kubernetes/kops#436]
I have this problem on the worker nodes created by kops: Docker doesn't seem to be properly configured:

```
root@ip-172-20-57-113:~# docker info
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.23/info: read unix @->/var/run/docker.sock: read: connection reset by peer
```

The kubelet can't be launched and the node never registers.

**Comment by justinsb** [comment]
Did you specify a 1.4 version of k8s by any chance?

Can you please provide the cluster spec (feel free to redact e.g. your DNS name) - you can get it using `kops get cluster -oyaml`

**Comment by MrTrustor** [comment]
Here is the cluster spec:

```
$ kops get cluster -oyaml
metadata:
  creationTimestamp: "2016-09-13T16:45:11Z"
  name: k8s.mydomain.com
spec:
  cloudProvider: aws
  dnsZone: mydomain.com
  etcdClusters:
  - etcdMembers:
    - name: eu-central-1a
      zone: eu-central-1a
    name: main
  - etcdMembers:
    - name: eu-central-1a
      zone: eu-central-1a
    name: events
  kubernetesVersion: v1.3.7
  masterPublicName: api.k8s.mydomain.com
  networkCIDR: 172.20.0.0/16
  networking:
    classic: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  zones:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
  - cidr: 172.20.64.0/19
    name: eu-central-1b
```

Created with:

```
kops create cluster --cloud=aws --zones=eu-central-1a,eu-central-1b --master-zones=eu-central-1a --name=k8s.mydomain.com --dns-zone=mydomain.com
```

I also should point out that this occurred after I encountered #434. Not having access to Route53 on this AWS account, I created manually the different records until the master was running and answering to kubectl. After having fixed the master, I recreated the workers (by terminating the instances and letting the autoscaling group recreate them) and that's when I observed this problem. I did not see anything related to a problem with the DNS records in the logs of the workers (Docker, protokube or the kubelet).

**Comment by MrTrustor** [comment]
After some new tests, this seemed to be linked to the Route53 issue in #434. I close the issue.
