### ISSUE TITLE
Master not starting in AWS eu-west-3

### ISSUE THREAD

**Issue by aldev-web** [kubernetes/kops#4360]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
=> Version 1.8.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
=> Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}

3. What cloud provider are you using?
=> AWS eu-west-3 (Paris)

4. What commands did you run?  What is the simplest way to reproduce this issue?
=> kops create cluster \
  --name=XXXX \
  --state=s3://XXXX \
  --master-count=1 \
  --master-zones eu-west-3a \
  --node-count=2 \
  --zones=eu-west-3a,eu-west-3b,eu-west-3c \
  --authorization=rbac \
  --cloud aws \
  --yes

5. What happened after the commands executed?
=> Cluster is starting.  It should be ready in a few minutes.

6. What did you expect to happen?
=> Cluster available

Nodes are created but not master.

**Comment by schweizerbolzonello** [comment]
Hello,

Can you check in your Auto Scaling Groups what is the status of your master nodes ?
https://eu-west-3.console.aws.amazon.com/ec2/autoscaling/home?region=eu-west-3#AutoScalingGroups:

Do you use a different image (AMI) for your masters than the workers ?
For example if you use CoreOS you need to accept their Terms of Services/License in the Marketplace, then your masters will spawn (hence checking in ASG for the exact status if there is an issue of this type).

**Comment by aldev-web** [comment]
Hello,

Thanks for your messsage, I could found the solution. 
By default, kops launches master size m3.medium but this instance type doesn't exist in eu-west-3. I added --master-size in create cluster and command and it works :)
