### ISSUE TITLE
Missing internet gateway should be created in shared VPCs

### ISSUE THREAD

**Issue by eherot** [kubernetes/kops#4363]
Because of #1885 I am required to use the shared VPC option if I want to use a private DNS zone, so I created a completely plain vanilla VPC and tried to run with it and got this:

```
F0201 12:10:04.150582   19936 internetgateway.go:217] ID must be set, if InternetGateway is shared: *awstasks.InternetGateway {"Name":"kops-cluster.staging.k8s","Lifecycle":"Sync","ID":null,"VPC":{"Name":"kops-cluster.staging.k8s","Lifecycle":"Sync","ID":"vpc-b6da3bcd","CIDR":"172.98.0.0/16","EnableDNSHostnames":null,"EnableDNSSupport":true,"Shared":true,"Tags":{"kubernetes.io/cluster/kops-cluster.staging.k8s":"shared"}},"Shared":true}
```

If an internet gateway doesn't exist in a shared VPC, wouldn't it make sense for `kops create cluster` to create it?

**Comment by chrislovecnm** [comment]
This should fix this https://github.com/kubernetes/kops/pull/4489
