### ISSUE TITLE
Kubernetes Dashboard v1.8.1 is not accessible after enabling RBAC

### ISSUE THREAD

**Issue by Sturgelose** [kubernetes/kops#4369]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.8.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
aws

4. What commands did you run?  What is the simplest way to reproduce this issue?
Create a new cluster using kops with RBAC enabled `--authorization RBAC` and set the superadmin user to admin.
```
kubeAPIServer:
    authorizationRbacSuperUser: admin
```
Deploy the latest dashboard version as per the instructions in the addons directory: https://github.com/kubernetes/kops/blob/master/docs/addons.md#dashboard (now version 1.8.1)

The dashboard is accessible in : `https://my.kops.cluster/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login`

5. What happened after the commands executed?

First, dashboard asks for a basic auth, which I fetch from the instructions given in the previous link.
However, now in latest iteration 1.8.x, dashboard is asking as well for a token or kubeconfig login. The Kubeconfig login doesn't work with the default kops configuration the CLI creates. Token, I've tried with the `admin` and `kube` secrets from kops (`kops get secrets kube --type secret -oplaintext`). However, doing so, I still get that user admin and user kube have no rights to see namespaces or do anything else.

I guess that basicAuth is in the middle and breaking the connection between dashboard and kube api, but not sure. 

Also, I do not want to give cluster wide access to the dashboard service account as it is suggested to not to do so in the kubernetes/dashboard repo.

6. What did you expect to happen?

I would expect the dashboard to be accessible securely with RBAC enabled. 

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

**Comment by chrislovecnm** [comment]
@shadoi @KashifSaadat @mikesplain do any of you have instructions using the dashboard with RBAC?

**Comment by blakebarnett** [comment]
We use oath2-proxy + dex.  It's kind of complicated to setup, so I wouldn't recommend documenting it here.

**Comment by Sturgelose** [comment]
After few days I found a simple solution, so I hope this will help people in the future :)

The thing is that for some reason, the `authorizationRbacSuperUser: admin` parameter only affects when accessing from `kubetctl`. So, mostly what I did is to give `cluster-admin` permissions to user `admin`:
`kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=admin`
This allows to use the admin token to authenticate in the dashboard and with the proper permissions

Then, to add new users, I followed the instructions in this issue (https://github.com/kubernetes/kops/issues/2354) to create a new token in kubernetes using kops secrets. Mostly the steps are:
1. Create a token: `dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64 | tr -d "=+/" | dd bs=32 count=1 2>/dev/null` (kudos to sportebois: https://github.com/kubernetes/kops/issues/2354#issuecomment-316372736)
2. Add it in a file with name of the user you want to create and add the token inside with the format `{"Data":"BASE64 STRING OF THE TOKEN HERE"}`
3. Restart the master nodes to reload basic-auth users

Of course all this could be done with oidc, but seems they will be implementing it in the dashboard soon(ish) (https://github.com/kubernetes/dashboard/issues/2353), so I'd rather wait instead of setting up a compled oauth2 proxy with dex.

To give permissions (`admin`, `read` or `edit`) to a specific user (foo) in a specific namespace (bar): 
`kubectl create rolebinding bob-admin-binding --clusterrole=admin --user=foo --namespace=bar`

**Comment by chrislovecnm** [comment]
/area documentation

Going to leave this open as we should document this

**Comment by erks** [comment]
The other workaround I did was to add `--authentication-mode=basic` to `kubernetes-dashboard` container args ([default](https://github.com/kubernetes/dashboard/wiki/Dashboard-arguments) is `--authentication-mode=token`), then logging into the dashboard using either username/password (user: admin) or kops-exported kubeconfig should work.

With RBAC enabled, kops configures the basic-auth user `admin` assigned to `system:masters` group, which has cluster-wide admin access (through `cluster-admin` ClusterRole). However, kops also configures the static token auth users, which includes `admin` user without an associated group. Authenticating using the admin "token" won't pass any group information to k8s authorization, hence no access. Looking at the [source code](https://github.com/kubernetes/kops/blob/bf24a6443c270e1b4e4bc2be95ad2629c553a0bd/pkg/tokens/wellknown.go#L21), these token-auth users seem to have been deprecated.

**Comment by chrislovecnm** [comment]
@erks how should kops be configuring this?

**Comment by erks** [comment]
@chrislovecnm I think either adding `--authentication-mode=basic` to https://github.com/kubernetes/kops/tree/master/addons/kubernetes-dashboard or adding `system:masters` group to the [token auth](https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/secrets.go#L218)'s `admin` user. the latter seems less intrusive, i.e. keep kubernetes-dashboard intact and make `admin` user access the same for both basic auth and token auth.

**Comment by chrislovecnm** [comment]
I like the later, it you are able to PR have at it!

**Comment by erks** [comment]
@chrislovecnm please review https://github.com/kubernetes/kops/pull/4575.
