### ISSUE TITLE
Unable to connect to apiserver with cluster created with `--networking=cni`

### ISSUE THREAD

**Issue by natemurthy** [kubernetes/kops#4383]
-------------------- BUG REPORT --------------------

> 1. What `kops` version are you running? The command `kops version`, will display
 this information.

```
$ kops version
Version 1.8.0 (git-5099bc5)
```

> 2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

`kubectl v1.9.1, kubernetes 1.8.6`

> 3. What cloud provider are you using?

```
aws
```

> 4. What commands did you run?  What is the simplest way to reproduce this issue?

```
kops create cluster -v 10 \
  --cloud=aws \
  --name=[REDACTED] \
  --state=[REDACTED] \
  --zones=us-west-2b \
  --node-count=2 \
  --image=coreos.com/CoreOS-stable-1576.5.0-hvm \
  --node-size=t2.medium \
  --master-size=m4.large \
  --networking=cni \
  --dns=private \
  --dns-zone=[REDACTED]\
  --dns-zone=[REDACTED] \
  --yes
```

> 5. What happened after the commands executed?

After about 15 minutes to let DNS propagate, I tried to connect the apiserver but the connection timed out. I noticed that the A records for the master node had not been set to the IP assigned to the node be EC2 so I manually corrected it. I waited a few more minutes and observed:
```
$ kubectl get nodes
Unable to connect to the server: unexpected EOF
```

> 6. What did you expect to happen?

I expected to be able to connect the apiserver and view the statues of the cluster nodes. I also expected A records for DNS to be set properly.

> 7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

My cluster manifest is available here: https://pastebin.com/G7ZjpHgg (sensitive information redacted)

> 8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

Verbose logs are available here: https://pastebin.com/azbLfPG7 (sensitive information redacted)

**Comment by chrislovecnm** [comment]
@natemurthy this is working as expected.  Launching with`--networking cni` allows a user to ssh into a master and install cni on the master.  I have considered removing this option.

**Comment by natemurthy** [comment]
@chrislovecnm hm, I was able to ssh into a master without `--networking cni` enabled. Is it expected that I none of my `kubectl` commands work with this flag set?

**Comment by chrislovecnm** [comment]
@natemurthy unless you need to I recommend having kops install a CNI provider, using `--networking weave` for instance.  `--networking cni` is only if you need to install your own provider, and you have to do it with kubectl on the master.  It is an advanced feature that was put in place before we included the various CNI providers.

**Comment by nebril** [comment]
@chrisglass that's weird, when I was trying Cilium out with kops clusters, I was able to create cluster with `--networking cni`, but the master node wasn't ready until I installed the cni plugin (via daemonset). After that nodes were starting as usual. But the point is, I had access to master node via kubectl.

**Comment by chrisglass** [comment]
@chrislovecnm I suspect ^^ was meant for you :)

**Comment by natemurthy** [comment]
@nebril Yes definitely weird. And to make things weirder, you were able to access your master node via kubectl, but I cannot.

@chrislovecnm I also tried using the weaveworks CNI provider, still observing timeouts connecting to master via kubectl.

**Comment by chrislovecnm** [comment]
@nebril yah it kinda works in that weird way. The dns-controller deployment, which is part of kops, sets the DNS name of the API server, but the deployment will not launch until a CNI provider is installed.  We use k8s to setup DNS, thus until k8s starts you will not have DNS for the API endpoint. So you have to ssh on to the master and install a CNI provider.

@natemurthy if you are not able to use weave you may be running into something else.  You have to ssh into the master and then use kubectl, when you use `--networking cni`

**Comment by natemurthy** [comment]
Hi guys, my team doesn't have the means to adopt this unfortunately =/
