### ISSUE TITLE
[FEATURE REQUEST] rolling-update should grow first

### ISSUE THREAD

**Issue by timothyclarke** [kubernetes/kops#4385]
Currently when you perform a rolling update the pods are evicted, an instance is removed, and then a new instance is created. 

Request : Can we change the order so a new instance is created first. I'd prefer to pay a little more for additional capacity rather than possibly losing resiliency etc.
I'd be happy if this was a flag eg
`kops rolling-upgrade --yes --grow`
This change the order of things so that a new node be created, added to the instance group, and then pods are ejected, and the old node removed.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
`Version 1.8.0 (git-5099bc5)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-03T22:31:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?
`AWS`

4. What commands did you run?  What is the simplest way to reproduce this issue?
`kops rolling-upgrade --yes`

5. What happened after the commands executed?
Pods were ejected, nodes were terminated, new nodes were created

6. What did you expect to happen?
I would like the new nodes created first

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by chrislovecnm** [comment]
This is actually a duplicate request, and there is an open PR which should address this :)

https://github.com/kubernetes/kops/pull/4038

Can we close this?

**Comment by timothyclarke** [comment]
yes
