### ISSUE TITLE
AWS-Nodes-don't-show up

### ISSUE THREAD

**Issue by Zwordi** [kubernetes/kops#4393]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. Version 1.8.0 (git-5099bc5)

2. Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

3. AWS

4. root@kubeadm:~# /usr/local/bin/kops create cluster --state=s3://prefix-saas-toto-state-store --zones eu-west-3b ${NAME} --node-count=2 --node-size=m4.large --master-size=m4.large --dns-zone=saas.toto.be --cloud aws --yes

5. Nothing, all seems to be ok

6. After the deletion of my previous cluster i was expecting new nodes using my new requirement m4.large.

7. I can't as i delete my bucket as it's dev.

Just wanted to share this behavior.
I may have miss something...
Record have been writing on the route53 dns zones.
During 3 hours i wasn't able to get a new nodes up and with the pricing about the support i don't know what to think with that.

Thanks
Zwordi

**Comment by andrzej-jedrzejewski** [comment]
Did you check if any resources have been created, e.g. load balancer or security groups?

**Comment by Zwordi** [comment]
Hi,

In the next day of this post i was able to have it working but still i didn't be able to get an instance type like t2.medium for master nodes and another for the workers node even if i put it on the command line.

I will do more experimentation in the following days.
