### ISSUE TITLE
kops update always shows modifications to AutoScalingGroup resources

### ISSUE THREAD

**Issue by KashifSaadat** [kubernetes/kops#4394]
**kops version:** [master](https://github.com/kubernetes/kops/tree/a5374c3af62c5c6bacf52822a4ea306d2ff13852)
**Cloud provider:** AWS

**Description:**
When running a `kops update cluster`, the following changes are always shown (for all AWS AutoScaling Groups):

```
Will modify resources:
  AutoscalingGroup/<KOPS-INSTANCE-GROUP-NAME>.<KOPS-CLUSTER-NAME>
  	Granularity         	 <nil> -> 1Minute
  	Metrics             	 <nil> -> [GroupMinSize, GroupMaxSize, GroupDesiredCapacity, GroupInServiceInstances, GroupPendingInstances, GroupStandbyInstances, GroupTerminatingInstances, GroupTotalInstances]
```

Related to the AutoScalingGroup awstask, when retrieving the AutoScalingGroup the response contains a list of `EnabledMetrics`, as opposed to `Granularity` and `Metrics`, so these properties are never set on the actual object.

**Comment by chrislovecnm** [comment]
I know that we recently added https://github.com/kubernetes/kops/commit/02855fc13fab7319d6d516fa3ea631a97cc990c5#diff-3860344ecedd8a98848d9bb72b6fefb1

marking this as blocks next.

**Comment by justinsb** [comment]
Thanks for reporting @KashifSaadat .  I believe we fixed this, and the lifecycle unit test should actually test this, so I'm going to close.  Please reopen if you continue to see it in 1.9.0-alpha3 or later.
