### ISSUE TITLE
Update kubernetes-release urls to dl.k8s.io

### ISSUE THREAD

**Issue by nick4fake** [kubernetes/kops#4397]
https://github.com/kubernetes/kubernetes/issues/33726

1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.8.0 (git-5099bc5)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
aws

4. What commands did you run?  What is the simplest way to reproduce this issue?
kops update cluster --name $NAME --out kops-tf --target terraform

5. What happened after the commands executed?
````
I0206 20:55:32.170601   14318 apply_cluster.go:880] error reading hash file "https://storage.googleapis.com/kubernetes-release/release/v1.8.7/bin/linux/amd64/kubelet.sha1": unexpected response code "403 Forbidden" for "https://storage.googleapis.com/kubernetes-release/release/v1.8.7/bin/linux/amd64/kubelet.sha1": <?xml version='1.0' encoding='UTF-8'?><Error><Code>SecurityPolicyViolated</Code><Message>Request violates OrgPolicy constraint.</Message><Details>Request is prohibited by organization's policy</Details></Error>
````

6. What did you expect to happen?
Config is generated

**Comment by aaboyd** [comment]
I just came here to report the same thing, but I think there might be some problems on the other side of this equation.

If you change the URL to `dl.k8s.io`, it just gives you a redirect to the full bucket URL.  If you follow that redirect you run into the same problems.  Probably should change the URL to avoid any problems later if they do change the bucket.

```
~/source/kops
$ http --print=hbHB "https://dl.k8s.io/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1"
GET /kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: dl.k8s.io
User-Agent: HTTPie/0.9.2



HTTP/1.1 302 Moved Temporarily
Connection: keep-alive
Content-Length: 161
Content-Type: text/html
Date: Tue, 06 Feb 2018 19:09:45 GMT
Location: https://storage.googleapis.com/kubernetes-release/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1
Server: nginx/1.10.3

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>

~/source/kops
$ http --print=hbHB "https://storage.googleapis.com/kubernetes-release/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1"
GET /kubernetes-release/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubelet.sha1 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: storage.googleapis.com
User-Agent: HTTPie/0.9.2



HTTP/1.1 403 Forbidden
Alt-Svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
Cache-Control: private, max-age=0
Content-Length: 210
Content-Type: application/xml; charset=UTF-8
Date: Tue, 06 Feb 2018 19:10:04 GMT
Expires: Tue, 06 Feb 2018 19:10:04 GMT
Server: UploadServer
X-GUploader-UploadID: AEnB2Up9_rt7kx88Pcc5wfGS2T8JPhXQUzzmz_S3Zajl57NJAkhaJmqgvabPKAdeA8TBUDLHvAM1lQsfvM6FYOtyTUkGyTi1fbFOA24whxEoA3SLKbqkJiY

<?xml version='1.0' encoding='UTF-8'?>
<Error>
    <Code>SecurityPolicyViolated</Code>
    <Message>Request violates OrgPolicy constraint.</Message>
    <Details>Request is prohibited by organization's policy</Details>
</Error>
```

**Comment by fawadkhaliq** [comment]
Same problem seen with v1.7.11

`
I0206 10:54:02.370299   33839 apply_cluster.go:799] error reading hash file “https://storage.googleapis.com/kubernetes-release/release/v1.7.11/bin/linux/amd64/kubelet.sha1“: unexpected response code “403 Forbidden” for “https://storage.googleapis.com/kubernetes-release/release/v1.7.11/bin/linux/amd64/kubelet.sha1": <?xml version=‘1.0’ encoding=‘UTF-8’?><Error><Code>SecurityPolicyViolated</Code><Message>Request violates OrgPolicy constraint.</Message><Details>Request is prohibited by organization’s policy</Details></Error>
`

**Comment by mikesplain** [comment]
This is an ongoing issue with the bucket as a whole and the gcr.io registry. If you're on slack, see #sig-release for updates. They're currently working to remediate the issue.

**Comment by mikesplain** [comment]
https://status.cloud.google.com/incident/container-engine/18003

**Comment by mikesplain** [comment]
@nick4fake @fawadkhaliq @aaboyd Looks like it's fixed now.
