### ISSUE TITLE
Documentation on requirements

### ISSUE THREAD

**Issue by mitpwd** [kubernetes/kops#4399]
Environment:
KOPS Version: 1.8.0
Kubectl: latest
Cloud provider: AWS

Issue:
We require a confirmation on compatibility requirement, if users are intended to use latest KOPS stable release with the latest stable kubectl version. 

We are trying to automate KOPS & kubectl deployment and they need to 'marry' in compatibility.

We are aware of the Compatibility matrix and it seems KOPS 1.6 matches kubectl 1.6, KOPS 1.7 matches 1.7 and so on.

Source of documentation:
https://github.com/kubernetes/kops

**Comment by chrislovecnm** [comment]
@mitpwd this is actually a kubectl <> kubernetes compatibility question, so I am thinking kubernetes should document it if it is not documented already.  

kops is backward compatible with Kubernetes and requires kubectl.  kubectl is used to create and export the kubeconfig file, so there is not really a required version.  That being said when kubectl with a k8s cluster, it is recommended to use the same version.

I get where you are coming from, but I think this is a k8s documentation issue.  What do you think?

**Comment by mitpwd** [comment]
Hi Chris,
I am happy to keep matching major releases, that is sufficient.
Thanks,
Dejan

**Comment by chrislovecnm** [comment]
Can we close?

**Comment by mitpwd** [comment]
Yes
