### ISSUE TITLE
kubedns not working

### ISSUE THREAD

**Issue by mikaelfa** [kubernetes/kops#4400]
Hi,

I've just installed a kops cluster on AWS and seen that internal kubernetes dns name resolving doesn't work for me. kubernetes works ok and even when creating an AWS loadbalancer into a kubernetes server, the traffic is working fine. The problem began when trying from one pod to access another kubernetes service with its name (dns).

I'm using kops Version 1.8.0 (git-5099bc5)

I ran a simple nginx pod and ran the following in it:
/ # nslookup kubernetes
nslookup: can't resolve '(null)': Name does not resolve

/ # nslookup kubernetes.default
nslookup: can't resolve '(null)': Name does not resolve

Name:      kubernetes.default
Address 1: 100.64.0.1 kubernetes.default.svc.cluster.local
/ #

I'm getting same problem for any kubernetes service I define.

Here is my kops cluster manifest:
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-01-30T09:50:19Z
  name: yyyy-cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://yyyy-store/yyyy-cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: masters
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: masters
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - x.x.x.x/32
  kubernetesVersion: 1.8.6
  masterInternalName: api.internal.yyyy-cluster.k8s.local
  masterPublicName: api.yyyy-cluster.k8s.local
  networkCIDR: 10.0.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - x.x.x.x/32
  subnets:
  - cidr: 10.0.2.0/24
    name: master-subnet
    type: Public
    zone: eu-west-1a
  - cidr: 10.0.3.0/24
    name: dmz-subnet
    type: Public
    zone: eu-west-1a
  - cidr: 10.0.4.0/24
    name: inner-subnet
    type: Private
    zone: eu-west-1a
  - cidr: 10.0.5.0/24
    name: inner-utility-subnet
    type: Utility
    zone: eu-west-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

I'm using standard Linux images for nodes as provided by kops.
Here is one of my instancegroup:
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-01-30T11:51:11Z
  labels:
    kops.k8s.io/cluster: yyyy-cluster.k8s.local
  name: dmz-nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: dmz-nodes
  role: Node
  subnets:
  - dmz-subnet

Do you have any idea?

thnx

**Comment by mikaelfa** [comment]
After investigation I see that I can't access the Kubernetes services by using IP. This means my problem is more on Kubernetes services routing than DNS.

Not sure how to solve that.

**Comment by mikaelfa** [comment]
I found the problem.
kops defined several routing tables to the VPC. This caused conflicts on the master to find the routing table. I had to clean this a let only one.

I think it's a bug,

**Comment by chrislovecnm** [comment]
@mikaelfa we need to have two route tables when you use private topology, one for the private subnets and another for the public subnets.  Also, you seem to be mixing private and public subnets in a curious fashion.  What topology are you using?  What is the purpose of the Private subnet?  You seem to be using Public topology and defining a private subnet.  I have never done that before and would recommend just having public subnets with public topology.

**Comment by mikaelfa** [comment]
The problem was I saw 3 routing tables assigned to the same VPC. Two of them had no subnet assigned at all. So removed both and let only 1 routing table.

Yes I need mixed topology for security reasons.

**Comment by mikaelfa** [comment]
After re-building of the cluster from scratch I can identify the problem:
2 routing tables were created: one for public subnets and one for private subnet.
The routing table of private subnet is just pointing to the nat gateway of the subnet. It does not include routing to different POD subnets (100.96.x.x) as the public routing table.
So, the whole kubernetes networking as paralyzed on the private subnet.
For any reason, just updating the private routing table did not make it. I had to re-create it with nat routing + POD subnet routing and then it works.

**Comment by kyprifog** [comment]
I ran into this one, was the underlying problem ever solved?   In particular I got this when running kops to terraform.
