### ISSUE TITLE
M5 instances with kops AMI won't stop correctly

### ISSUE THREAD

**Issue by bcorijn** [kubernetes/kops#4402]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.8.0
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
1.8.6
3. What cloud provider are you using?
AWS
4. What commands did you run?  What is the simplest way to reproduce this issue?
Launch an M5.Large instance with either the latest Jessie or Stretch image. After instance is booted succesfully, do a kops rolling-update or just shutdown the instance manually in AWS.
5. What happened after the commands executed?
The instance status changes to "shutting-down", but the instance stays up and reachable for quite some time. Nothing is logged that I could find that a shutdown signal was received. After several minutes, the instance suddenly disconnects. I presume AWS pulls the plug after a certain timeout.  
Once this happens, a bunch of my nodes seem to move into NotReady for a moment or until I restart their kubelet.
6. What did you expect to happen?
Shutdown quicker and more graceful, with logging. This is the behaviour on a M4.large or a random debian stretch community AMI that I tried. So I presume it's somewhere in the combination of the kops AMI and the M5 family.

**Comment by bcorijn** [comment]
/remove-lifecycle stale
Believe this one is still relevant!

**Comment by Mapes** [comment]
I have no stake in this but, stumbled across this via a google search for M5 not shutting down.    I've figured the problem out.    AWS used something other than the ACPI userspace deamon for shutting down M4 hosts.  the ACPI userspace deamon requires  /proc/acpi/events to be present and it's  not for AWSlinux M4s and M5s.   I basically had to get the source for ACPI2  which uses the netlink communication channel and compile and run it.    Than the M5 shutdown cleanly.   Note you also have to change the /etc/acpi/events/power.conf to powerconf.  ACPI2 actually has a regex in it and it ignores conf files with a . in the name

**Comment by Mapes** [comment]
Ok even more info the M4's can support PV guests.   The HV talks to the PV kernel modules in all linux kernels.   This is why on M4 without ACPI running it the HV can shut it down.   Sorry for obsessing it just drove me cra cra

**Comment by cjbottaro** [comment]
Is there any workaround to this besides installing ACPI from source?

**Comment by willthames** [comment]
@cjbottaro `apt-get install acpi-support` seemed to work for me with the standard kops debian stretch images

I just used an `execContainer` hook to achieve this:

```
hooks:
  - execContainer:
      command:
      - sh
      - -c
      - chroot /rootfs apt-get update && chroot /rootfs apt-get install -y acpi-support
      image: busybox
    roles:
    - Node
```

**Comment by willthames** [comment]
I've raised https://github.com/kubernetes/kube-deploy/pull/710 to get acpi-support added to future AWS stretch images by default, so hopefully the hook workaround above won't be needed forever

**Comment by tcolgate** [comment]
There are a couple of variations on instance termination hook support too:
https://github.com/pusher/k8s-spot-termination-handler/blob/master/Dockerfile
