### ISSUE TITLE
Update instance groups creation documentation to match required flag

### ISSUE THREAD

**Issue by klaus993** [kubernetes/kops#4404]
Hi!

I removed all the other questions from the template because they're not relevant to this issue.

This is a documentation issue, referring to the `Creating a new instance group` section of the `instance_groups.md` doc (https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#creating-a-new-instance-group).

1. What `kops` version are you running?

```
Version 1.8.0 (git-5099bc5)
```

2. What commands did you run?  What is the simplest way to reproduce this issue?

```
kops create ig morenodes
```

3. What happened after the commands executed?

```
cannot create instance group without subnets; specify --subnet flag(s)
```

4. What did you expect to happen?

I expected what the doc said to happen, an editor to open and edit the instance group.

So the doc should specify that that's needed and provide an example with one and with various subnets (to clarify the syntax needed, which I had to try and check if the behaviour was correct). For example: `kops create ig morenodes --subnet us-east-1a` and `kops create ig morenodes --subnet us-east-1a,us-east-1b` (this is what I had to discover, how to pass multiple subnets).

I'd be glad to make the amends and the subsequent PR to fix this. Advise me what you think!

Regards,

Klaus.

**Comment by chrislovecnm** [comment]
> I'd be glad to make the amends and the subsequent PR to fix this. Advise me what you think!

Go for it... I love documentation PRs

**Comment by chrislovecnm** [comment]
Maybe we add the docs to the `--help` ux as well, or better docs on how to do this.

**Comment by klaus993** [comment]
@chrislovecnm In the `--help` ux it says this about the `--subnet` flag:

"Subnet in which to create instance group. One of Availability Zone like eu-west-1a or a comma-separated list of multiple Availability Zones."

I think it's enough, though maybe it's better to add an example as well.

**Comment by klaus993** [comment]
Oh yes, this is already fixed 😄
