### ISSUE TITLE
Please add support to detect additional CIDRs in existing VPC

### ISSUE THREAD

**Issue by ddumontatibm** [kubernetes/kops#4410]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.8.0 (git-357eadd)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using? aws

4. What commands did you run?  What is the simplest way to reproduce this issue? kops create cluster --vpc

5. What happened after the commands executed?
Failed to properly detect all CIDRs in the VPC.  Some of the subnets were outside of the first listed.

6. What did you expect to happen? It would be nice if it could find all CIDRs in the VPC

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

**Comment by mmacfadden** [comment]
Take a look at these two related issues: #4131 and #3536. This allows you to specify `additionalNetworkCIDRs` in your cluster spec. It is not automatic, per say, but it is related to what you are talking about.

**Comment by ddumontatibm** [comment]
I was encouraged to report this from the cops slack.   I did get it to work but the command errors if you specify subnets outside of the range of the first cidr it finds via vpc name.

**Comment by ddumontatibm** [comment]
Ideally it could find all the cidrs on the vpc and not error.
