### ISSUE TITLE
Some public/private config options are case-sensitive

### ISSUE THREAD

**Issue by leosunmo** [kubernetes/kops#4412]
1. What `kops` version are you running? The command `kops version`, will display this information.
`1.8.0`

2. What Kubernetes version are you running? `kubectl version` will print the version if a cluster is running or provide the Kubernetes version specified as a `kops` flag.
Somewhat irrelevant, but trying to spin up a 1.8.4 cluster.

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
`kops create -f my-cluster.yaml`

5. What happened after the commands executed?
If you title-case some values it breaks evaluation. I've got two examples I ran in to and we probably don't want to be so picky about case.
Here's the `subnets` spec from cluster `Spec.subnets`
```  subnets:
  - cidr: 172.41.32.0/19
    name: ap-southeast-2a
    type: Public
    zone: ap-southeast-2a
```

If you run `kops create -f` on that file you get
```
error: error creating cluster: Spec.Topology.Masters: Invalid value: "Public": Invalid Masters value for Topology
```
If you change it to `public` it works fine.

The second example comes from the `topology` object in the same Cluster file.
```
  topology:
    dns:
      type: Public
    masters: Public
    nodes: Public
```

This results in the following when creating the cluster from that yaml file:
```
I0209 13:50:48.245263   53876 utils.go:151] Querying for all DNS zones to find match for "cluster.ap-southeast-2.test.example.com"
I0209 13:50:48.246020   53876 route53.go:50] AWS request: route53 ListHostedZones
I0209 13:50:49.581641   53876 utils.go:182] Found matching hosted zone ".test.example.com", but it was "Public" and we require "public"
I0209 13:50:49.581709   53876 utils.go:182] Found matching hosted zone ".ap-southeast-2.test.example.com", but it was "Public" and we require "public"
I0209 13:50:49.581724   53876 utils.go:182] Found matching hosted zone ".cluster.ap-southeast-2.test.example.com", but it was "Public" and we require "public"

error determining default DNS zone: No matching hosted zones found for ".cluster.ap-southeast-2.test.example.com"; please create one (e.g. "example.com") first
```

Changing the case to match the error message fixes the issue of course.

6. What did you expect to happen?
Not sure if we really need to be that picky about case-sensitivity. We could probably normalise it when it ingests the file.

**Comment by anillingutla** [comment]
Notice Case sensitiveness for Masters & Nodes ONLY !!!.. What killed my times was investigating the HOSTED ZONES of where the  "." was coming from preceeding my Hosted zone.. !!! And it says its not found.. 
 
FAILS
--------
  topology:
    dns:
      type: Public
    masters: Public
    nodes: Public

WORKS
--------
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
