### ISSUE TITLE
Kops does not fail when hitting AWS 20 instances limit 

### ISSUE THREAD

**Issue by MosheBlumbergX** [kubernetes/kops#4414]
Current count of AWS instances: 17 

Command used: 
kops create cluster --image ami-5055cd3f --master-size t2.large --node-size t2.large --node-count 4 --zones eu-central-1b --name mydomain --state s3://k8s-systems-store --networking flannel --yes

It never fails, just complete as expected, but never changes the placeholder IP of the API endpoint to the instance public IP. 

The master node is never created as well.

**Comment by chrislovecnm** [comment]
Unfortunately, you are not the first or probably the last person to hit this.

The challenge is the way AWS API works and quotas.  Quota are not accessible via the API at all, they only appear in the console. If someone can figure out how to get to quotas via the  AWS API, and show that it works, I will buy them a cookie.  Heck, a box of cookies!

When we create an ASG with kops, the API call is pretty much blind.  Meaning that we can only fail if AWS fails, and in this case, the AWS API does not fail.  The API does not return an error if the ASG is asking for an instance that cannot be provisioned.

The solution to this is improving `kops validate cluster` to return errors from autoscale groups.  This is another open issue.
