### ISSUE TITLE
Kube-proxy running in QoS class Burstable, should be class Guaranteed

### ISSUE THREAD

**Issue by horaceheaven** [kubernetes/kops#4415]
### Context:
Deploying a Kubernetes cluster with kops version `1.8.0` will provision kube-system pods e.g. kube-proxy, api-server in QoS class Burstable. There are some disadvantages to this even though these pods have the critical annotation applied to them and are static which reduces the likelihood of it being evicted by the kubelet, they are still high on the list to be evicted by system OOM killer, given the OOM score for class Burstable. 

### Preferred behavior:
The path I’d like to take on this is getting kube-proxy running in class guaranteed, and doing so there are some advantages it provides, such as, giving the scheduler a better picture of available resources on a node to schedule subsequent pods, isolation from bursty "noisy neighbor" processes or pods on the same node. However, applying class guarantee has drawbacks, such as setting a hard limit on CPU and memory, which I am prepared to take on the overhead of monitoring those limits overtime to ensure kube-proxy pods aren’t being starved.

### Approach:
Seeing that kops exposes custom configuration via the cluster spec, it might make sense to expose the CPU and memory request and limits there as well, but I’d like others to weigh in on which approach makes the most sense for the above use case. Whichever approach used for kube-proxy should be easily extended to other kops provisioned pods as well.

**Comment by chrislovecnm** [comment]
@horaceheaven had a discussion about this recently as well, and I agree that it would be good to have this configuration accessible in the API / ClusterSpec.  I think we will need to target only specific versions of k8s for this feature if I recall correctly this will only work with K8s 1.8+.  Also, I am wondering what upstream is handling this.  We try to mirror the GCE install scripts in kubernetes/kubernetes, with settings like these.

/cc @mward29 @robinpercy 

@mward29 I know you and I had a conversation about this, what have your teams testing shown?

**Comment by argais** [comment]
Why target 1.8+ :/ ? QoS has been around for a while now, checking the k8s changelogs I found mentions of it way back in 1.3.

I guess that @horaceheaven 's request is could be read as in "can we get to set req/lim for the cluster resources?". Regardless of what comes from upstream (those should be great defaults), being able to customize some values wouldn't hurt :)

**Comment by chrislovecnm** [comment]
@argais QoS has been around for awhile but if I recall correctly the functionality has improved substantially.  Could be wrong :)  Yes I agree that we should default to what upstream has set, and allow for a user to configure req and limits but hand for kube-proxy.  A bit off topic, but CNI has this issue as well, and it would be good to handle CNI via addons manager.

**Comment by argais** [comment]
Oh definitely QoS improved with time as everything in k8s land :D
And yes CNI has this exact same issue, but that one is easier to solve even with a post deployment script to patch the manifests, but in the case of static pods there isnt much that can be done after the cluster is deployed :( (ugly hacks aside of course :D)

**Comment by argais** [comment]
If you think this is something worth implementing, I could try to whip up a PR for this, would be a good reason to study more on golang :P (and would pair with @horaceheaven if he is up to it ;). We both work with @robinpercy so we could get some guidance from him too.

**Comment by robinpercy** [comment]
/assign

I'll help @horaceheaven and @argais come up with an initial PR
