### ISSUE TITLE
Kops edit cluster will not allow me to save the config file after making changes. Found fields that are not recognized adding Kube API Server to spec

### ISSUE THREAD

**Issue by rbizzell40** [kubernetes/kops#4420]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information. 1.8.

2. What Kubernetes version are you running? `kubectl version` will print the 1.8
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

3. What cloud provider are you using? AWS

4. What commands did you run? kops edit cluster $clustername.  What is the simplest way to reproduce this issue? Issuing the same command.

5. What happened after the commands executed? File cannot be saved there is a configuration error this will be ignored.

6. What did you expect to happen? When I enabled rbac authorization months before the file was saved without any error.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-06-13T14:20:04Z
  name: sss
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://sss
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: events
  iam:
    legacy: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.6
  masterInternalName: api.ss.com
  masterPublicName: api.ss.com
  networkCIDR: 10.230.0.0/16
  networkID: vpc-93f9a3fd
  networking:
    cni: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.230.64.0/24
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.230.13.0/24
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  topology:
    bastion:
      bastionPublicName: bastion.ss.com
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-06-13T14:20:04Z
  labels:
    kops.k8s.io/cluster: ss.com
    kubernetes.io/role: master
  name: master-us-east-1a
spec:
  associatePublicIp: false
  cloudLabels:
    Appia_Environment: dev
    Appia_Product: k8s
    dtEnvironment: dev.ss.com
    dtProduct: k8s
  image: ami-55339d43
  machineType: m4.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-06-13T14:20:04Z
  labels:
    kops.k8s.io/cluster: ss.com
    kubernetes.io/role: node
  name: nodes
spec:
  associatePublicIp: false
  cloudLabels:
    Appia_Environment: dev
    Appia_Product: k8s
    dtEnvironment: ss.com
    dtProduct: k8s
  image: ami-55339d43
  machineType: m4.xlarge
  maxSize: 5
  minSize: 3
  role: Node
  subnets:
  - us-east-1a

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
  kubeAPIServer:
    oidcClientID: <our client-id>
    oidcIssuerURL: https://
    oidcUsernameClaim: sub

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by rbizzell40** [comment]
When I added rbacl authorization I was able to add 
kubeAPIServer:
    authorizationRbacSuperUser: admin also

**Comment by rbizzell40** [comment]
If I try an add it back because for some reason it is no longer there I get Found fields that are not recognized
#         name: a

#       name: events

# -   iam:

# +   iam: null

# -     legacy: true

#     kubeAPIServer:

#       authorizationRbacSuperUser: admin

# +     legacy: true

#     kubernetesApiAccess:

#     - 0.0.0.0/0

I don't get it I am lost

**Comment by rbizzell40** [comment]
No resolution to my issue I haven't seen any responses so I am just closing it.

**Comment by moonseokho85** [comment]
same error occurs to me!! where is solutions?

**Comment by olemarkus** [comment]
Can you add some more details? What is the change you are trying to make?
