### ISSUE TITLE
aws kops create cluster errors out as InvalidClientTokenId

### ISSUE THREAD

**Issue by apLD** [kubernetes/kops#4425]
Errors out while creating kubernetes cluster in aws kops. Here is the command i used for creating the cluster

$ kops create cluster --name cs.cluster.k8s.local --zones $AWS_AVAILABILITY_ZONES --yes

Here is the error i am getting,

error running tasks: deadline exceeded executing task IAMRole/nodes.cs.cluster.k8s.local. Example error: error creating IAMRole: InvalidClientTokenId: The security token included in the request is invalid
        status code: 403, request id: 30fe2a97-0fc4-11e8-8c48-0f8441e73bc3

Can anyone help me resolve this issue ?

**Comment by chrislovecnm** [comment]
> InvalidClientTokenId

This usually means that your AWS credentials are not configured or are incorrect.  See https://docs.aws.amazon.com/STS/latest/APIReference/CommonErrors.html

**Comment by apLD** [comment]
Thank you. That helped me track down the issue. 
I did not export the following 2 environment variables which is required while creating a cluster using kops

export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
