### ISSUE TITLE
Kops 1.7.0 master sg missing 443

### ISSUE THREAD

**Issue by zyounker** [kubernetes/kops#4429]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

1.7.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-12T21:07:32Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
aws

4. What commands did you run?  What is the simplest way to reproduce this issue?

	kops create cluster \
		--state=s3://$KOPS_ARG_STATE \
		--networking=weave \
		--topology=$KOPS_ARG_TOPOLOGY \
		--authorization=RBAC \
		--dns=public \
		--dns-zone=$KOPS_ARG_DNS_ZONE \
		--kubernetes-version=$KOPS_ARG_KUBE_VERSION \
		--cloud=aws \
		--vpc=${KOPS_ARG_VPC_ID} \
		--network-cidr=${KOPS_ARG_CIDR} \
		--image=${KOPS_ARG_IMAGE} \
		--zones=${KOPS_ARG_AZ_LIST} \
		--master-size=${KOPS_ARG_MASTER_SIZE} \
		--master-count=${KOPS_ARG_MASTER_COUNT} \
		--admin-access=${KOPS_ARG_ADMIN_ACCESS} \
		--node-size=${KOPS_ARG_NODE_SIZE} \
		--node-count=${KOPS_ARG_NODE_MIN_COUNT} \
		--ssh-public-key=${KOPS_ARG_SSH_PUBLIC_KEY} \
		--cloud-labels=${KOPS_ARG_CLOUD_LABELS} \
		${KOPS_ARG_CLUSTER_NAME}.${KOPS_ARG_DOMAIN}

Where KOPS_ARG_ADMIN_ACCESS is a list of comma delimited network CIDRs

5. What happened after the commands executed?

Cluster creates as expected but Security groups do not have a rule to allow 443 for every ip listed in KOPS_ARG_ADMIN_ACCESS. Only rules for SSH are getting created.

6. What did you expect to happen?

According to docs (https://github.com/kubernetes/kops/blob/master/docs/security.md) this should be creating SSH & HTTPS.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by gauravarora** [comment]
I saw this with 1.7.0 as well although rarely. I would suggest you upgrade to 1.8.1 and then try.

**Comment by gambol99** [comment]
hi @zyounker ... did you upgrade to 1.8.1? .. was the issue fixed?
