### ISSUE TITLE
Bindata should not add files that are git-ignored

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#443]
When developing on OS X I noticed that bindata had added a .DS_Store file. This file shouldn't really be included in bindata. In general, I think any file that is git-ignored should not be added to bindata.

This is not a huge deal, but if it's easy to accomplish, it's probably better to keep bindata as clean as possible.

**Comment by justinsb** [comment]
Hopefully #503 will get this... let me know if it still happens
