### ISSUE TITLE
Error creating cluster on eu-west-1a

### ISSUE THREAD

**Issue by arrkaye** [kubernetes/kops#4439]
1. 1.8.1 - KOPS

2. 1.9.0 - KUBECTL

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

kops create cluster --zones=eu-west-1a --name=kube-live.internal.xxx.com --vpc=vpc-xxxxx --topology private --networking calico --master-size t2.micro --node-size t2.micro

5. What happened after the commands executed?

I0213 18:49:02.038807    2980 create_cluster.go:439] Inferred --cloud=aws from zone "eu-west-1a"
I0213 18:49:02.038967    2980 create_cluster.go:971] Using SSH public key: /home/ec2-user/.ssh/id_rsa.pub
I0213 18:49:32.418554    2980 logging_retryer.go:60] Retryable error (RequestError: send request failed
caused by: Post https://ec2.eu-west-1.amazonaws.com/: dial tcp 10.0.1.165:443: i/o timeout) from ec2/DescribeAvailabilityZones - will retry after delay of 40ms
I0213 18:50:02.459164    2980 logging_retryer.go:60] Retryable error (RequestError: send request failed
caused by: Post https://ec2.eu-west-1.amazonaws.com/: dial tcp 10.0.3.169:443: i/o timeout) from ec2/DescribeAvailabilityZones - will retry after delay of 80ms
I0213 18:50:32.539782    2980 logging_retryer.go:60] Retryable error (RequestError: send request failed
caused by: Post https://ec2.eu-west-1.amazonaws.com/: dial tcp 10.0.1.165:443: i/o timeout) from ec2/DescribeAvailabilityZones - will retry after delay of 136ms
I0213 18:51:02.676437    2980 logging_retryer.go:60] Retryable error (RequestError: send request failed
caused by: Post https://ec2.eu-west-1.amazonaws.com/: dial tcp 10.0.3.169:443: i/o timeout) from ec2/DescribeAvailabilityZones - will retry after delay of 336ms
I0213 18:51:33.013398    2980 logging_retryer.go:60] Retryable error (RequestError: send request failed

6. What did you expect to happen?

Create cluster

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
NA
8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
NA
9. Anything else do we need to know?
It works for zone us-east-1a

**Comment by chrislovecnm** [comment]
The IP address for the HTTPS endpoint `10.0.1.165` looks like a private IP address.  Not sure how your DNS is sending you there.

```
$ curl -vv  https://ec2.eu-west-1.amazonaws.com/
*   Trying 54.239.39.130...
* Connected to ec2.eu-west-1.amazonaws.com (54.239.39.130) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
* Server certificate: ec2.eu-west-1.amazonaws.com
* Server certificate: Amazon
* Server certificate: Amazon Root CA 1
* Server certificate: Starfield Services Root Certificate Authority - G2
> GET / HTTP/1.1
> Host: ec2.eu-west-1.amazonaws.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Location: http://aws.amazon.com/ec2
< Content-Type: text/xml;charset=UTF-8
< Content-Length: 0
< Date: Tue, 13 Feb 2018 19:01:39 GMT
< Server: AmazonEC2
<
* Connection #0 to host ec2.eu-west-1.amazonaws.com left intact
```

Is what I am getting locally.

**Comment by arrkaye** [comment]
Thanks. That was it. I had an ec2 endpoint setup in my VPC.
