### ISSUE TITLE
hack directory for scripts

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#444]
Start work on various scripts that would assist developers in the development process.

For example:

```shell
#!/bin/bash

#This script is a rough first stab at allowing a developer to integration test nodeup changes

export S3_BUCKET_NAME=your-kops-bucket
export NODEUP_URL=https://${S3_BUCKET_NAME}.s3.amazonaws.com/nodeup/nodeup-1.3.tar.gz

RUN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export S3_NODEUP_BUCKET=${S3_NODEUP_BUCKET:-'your-node-up-bucket'}
export KOPS_STATE_STORE=s3://your-kops-bucket
export ZONE=us-west-2
export NAME=your-cluster-dns

echo "Building custom version"
cd $GO_PATH/src/k8s.io/kops
make upload S3_BUCKET=s3://${S3_BUCKET_NAME}

ZONES=$(aws --region $ZONE ec2 describe-availability-zones | jq '.AvailabilityZones | .[] | .ZoneName' | sed 's/"//g' | tr '\n' ',' | sed 's/,$//g')
IMAGE=$(aws ec2 describe-images --owners self | jq '.Images | .[] | select(.Name == "debian-packer") | .ImageId' | tr '"' ' ')

kops \
  --state $KOPS_STATE_STORE \
  create cluster \
  --node-count 4 \
  --zones $ZONES \
  --master-zones $ZONES \
  --master-size m3.large \
  --node-size t2.medium \
  --name $NAME $1 \
  --image $IMAGE \
  --yes
```

**Comment by kris-nova** [comment]
@chrislovecnm - When you say hack directory, are you just referring to a temporary junk-drawer to through commonly used dev scripts in?

**Comment by chrislovecnm** [comment]
Don't know if I would call this a junk drawer:

https://github.com/kubernetes/kubernetes/tree/master/hack

Even though I often call the scripts junk because I don't understand them.  Same principle.  A developer needs to do a quick and dirty e2e test. A script is in the hack dir.  Etc etc.

**Comment by kris-nova** [comment]
Where are we with this? @chrislovecnm did you get the headers script into the repo?

**Comment by chrislovecnm** [comment]
Yah that PR is in, but needs testing.

**Comment by kris-nova** [comment]
Closing

The PR is merged, and the hack directory is now in Kops. Devs can begin using it.
