### ISSUE TITLE
kops requires environment variable AWS_REGION to be set

### ISSUE THREAD

**Issue by iMartyn** [kubernetes/kops#4451]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.8.0 (git-5099bc5) but also reproduced on master

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.1", GitCommit:"4956e65d5926c02840cc0854d423ac31af29065f", GitTreeState:"clean", BuildDate:"2017-12-18T21:03:10Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
```
export KOPS_STATE_S3_ACL=bucket-owner-full-control
export KOPS_STATE_STORE=s3://some-kops-state/
export AWS_PROFILE=staging_k8s_account
export AWS_DEFAULT_PROFILE=staging_k8s_account
export AWS_SDK_LOAD_CONFIG=1
kops update cluster --target=terraform --out=some_dir/ --name thecluster.name.com
grep AWS_REGION some_dir/terraform/data/aws_launch_configuration_master-eu-west-1a.masters.thecluster.name.com_user_data
```

5. What happened after the commands executed?
There is no output from the grep

6. What did you expect to happen?
The userdata should have AWS_REGION=eu-west-1 in the config as that is default in my ~/.aws/config file.
The lack of this causes nodeup to have to brute force the region for the s3 bucket which requires the `ec2:DescribeRegion` permission.  Whilst that permission is going to default into kops, that's still inefficient and what really bugs me is that creating terraform from the cluster yaml on different machines results in different terraform (this to me is a no-no).

7. Please provide your cluster manifest. 
I don't think this is relevant to this bug as the codepath for checking the AWS_REGION env var is not related to loading the cluster yaml

**Comment by itskingori** [comment]
@iMartyn just checking, is this the same as the issue described in https://github.com/aws/aws-sdk-go/issues/1600#issuecomment-368190456 and does https://github.com/aws/aws-sdk-go/issues/1600#issuecomment-368582457 [the comment after] make sense?

**Comment by iMartyn** [comment]
hi @itskingori yes, I'm sure that is indeed the reason that the nodeup script requires the env variable set, however, having this set on the machine that is running kops is not the right solution imo.

**Comment by itskingori** [comment]
@iMartyn agreed!
