### ISSUE TITLE
Creating cluster and changing subnets causes validation failure - instance groups are configured in the old subnet

### ISSUE THREAD

**Issue by darrenhaken** [kubernetes/kops#4454]
I've tried following guides on setting up a cluster inside an existing VPC with existing Subnets.

The advice is to create the cluster and then edit the configuration with my subnets.
When I do this I get the following error:

`validation failed: InstanceGroup "master-eu-west-1a" is configured in "eu-west-1a", but this is not configured as a Subnet in the cluster`

I've tried editing the master IG first to reference the existing subnets but that also causes an error.

Anyone have any idea how to fix this?

**Comment by chrislovecnm** [comment]
@darrenhaken it is probably easiest to use a manifest, see https://github.com/kubernetes/kops/blob/master/docs/manifests_and_customizing_via_api.md

The steps without a manifest I think are
1. `kops create cluster` with the appropriate flags, and do NOT use `--yes`
2. `kops edit cluster` with the name of the cluster
3.  `kops create secret` (the create will give you the command line`
4. `kops update cluster` this will run a dry-run
4. `kops update cluster` with the `--yes` flag

I usually recommend using a manifest when you get into complex configurations.

**Comment by darrenhaken** [comment]
@chrislovecnm thanks for the answer. 

Also, I want to manage a cluster across different environments. An example is to create a kops cluster for development and then promote that as `Infrastructure as Code` to production.

Is using the manifest the best pattern to do that or is that another approach?

The docs for Kops seems to expect all config to live in S3 rather than Git which makes it trickier to promote configuration through envs.

**Comment by chrislovecnm** [comment]
@darrenhaken for more complex configs I always recommend manifests.  Also, take a look at the templating that we have under the toolbox command.

> The docs for Kops seems to expect all config to live in S3 rather than Git which makes it trickier to promote configuration through envs.

Think of S3 as a database, like Etcd, not as your source control.  Keep the manifests/templates in Git, and don't worry about the state store.

**Comment by darrenhaken** [comment]
Great I’ll take a look at templating, I’ll definitely need it.
