### ISSUE TITLE
Addon: cluster-autoscaler additional permissions required  

### ISSUE THREAD

**Issue by mikesimos** [kubernetes/kops#4455]
### Issue:
Addon [cluster-autoscaler 1.8](https://github.com/kubernetes/kops/blob/6942f1d5e3f453e4eecf81ad4706cf616a1a238b/addons/cluster-autoscaler/v1.8.0.yaml) installation using `IMAGE=gcr.io/google_containers/cluster-autoscaler:v1.1.0` (according to this [installation guide](https://github.com/kubernetes/kops/blob/6942f1d5e3f453e4eecf81ad4706cf616a1a238b/addons/cluster-autoscaler/README.md))  appears broken :
```
1 reflector.go:205] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list storageclasses.storage.k8s.io at the cluster scope
```
### Cause:
[cluster-autoscaler:v1.1.0](https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-release-1.1/cluster-autoscaler) requires some storageclasses permissions.

**Comment by chrislovecnm** [comment]
@mikesimos are you using RBAC?  We probably need a rule for that.

**Comment by mikesimos** [comment]
Yeah! Just opened a PR!
