### ISSUE TITLE
When launching cluster with HA with topology private to an existing AWS VPC some configuration errors occurs

### ISSUE THREAD

**Issue by omerh** [kubernetes/kops#4461]
When launching a cluster in with the following configuration:

```
  kops create cluster \
  --name=${NAME} \
  --vpc=${VPC_ID} \
  --node-count=${NODE_COUNT} \
  --master-size ${MASTER_SIZE} \
  --master-zones ${ZONES} \
  --zones=${ZONES} \
  --dns-zone=${ZONEID} \
  --cloud=aws \
  --networking weave \
  --topology private \
  --ssh-public-key=${PUBLICSSH}
```

Cluster launched 3 master nodes behind AWS ELB.
But the masters security groups were not set to pass inbound traffic from ELB health check.

The masters security group contains the api-elb group which contains 443:0.0.0.0/0

Only when adding to the masters security group explicitly the VPC CIDR block ELB health checks passed. 

Am I missing something ?

**Comment by chrislovecnm** [comment]
More details, please.

> some configuration errors occurs
