### ISSUE TITLE
Custom AMI

### ISSUE THREAD

**Issue by marranz** [kubernetes/kops#4464]
I'm planning to use kubernetes on aws to replace ECS. 

I've tried creating the terraform files with kops, using shared subnets and vpcs and it fits my needs, but there is one more thing.

for PCI compliance reasons I need to use my custom hardened centos AMIs. I'm using packer with CD Pipelines for creating that AMIs.

Is there any way that i use kops with my own amis?

Cheers

**Comment by 23doors** [comment]
https://github.com/kubernetes/kops/blob/master/docs/images.md

**Comment by chrislovecnm** [comment]
@marranz you can also use hooks to harden the AMI during the creation of the cluster, but @23doors has provided you the information on how to use your own image.

Can we close?

**Comment by marranz** [comment]
I'll close it. Thanks :)

**Comment by HerrmannHinz** [comment]
@chrislovecnm what hooks are these? what do i look for?

**Comment by HerrmannHinz** [comment]
found them, for reference: https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#hooks

**Comment by kitos9112** [comment]
In case someone lands here. The above IMAGES.md file has been moved --> https://github.com/kubernetes/kops/blob/master/docs/operations/images.md

**Comment by olemarkus** [comment]
Or more precisely, here https://kops.sigs.k8s.io/operations/images/
