### ISSUE TITLE
Is there a YAML/JSON schema available for Kops?

### ISSUE THREAD

**Issue by darrenhaken** [kubernetes/kops#4470]
Is there a copy of the schema you use to validate cluster manifests in YAML?

I often use the [YAML language server](https://github.com/redhat-developer/yaml-language-server) to validate YAML files as a edit them.

**Comment by chrislovecnm** [comment]
So the out API should have a swagger spec, but I am uncertain about a formal schema.  Does k8s have a schema?

**Comment by darrenhaken** [comment]
The IntelliJ and vscode plugins have auto completion for K8 manifests so I assumed there must be; unless they've rolled it themselves.
