### ISSUE TITLE
Delete doesn't remove peering connection, so can't remove vpc

### ISSUE THREAD

**Issue by caulagi** [kubernetes/kops#4471]
I created a k8s cluster with kops in AWS. I had to add a 'peering connection' (from aws web console) to the vpc created by kops so that I could talk to the database. However, when I tried to delete the cluster, it was not able to delete the vpc, because of the 'peering connection'. Should `kops delete cluster` work still? I give the details below -
 
1. What `kops` version are you running? The command `kops version`, will display
 this information.

`Version 1.8.1 (git-19e4c581f)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```bash
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
```

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

`kops delete cluster --name <redacted> --yes`

5. What happened after the commands executed?

Kops was not able to delete the vpc, because I had created a 'peering connection' for the vpc (**outside kops**). These were the last few lines, where it couldn't proceed further

```bash
volume:vol-0866862ea32cbcdd8	still has dependencies, will retry
internet-gateway:igw-0de527e37dd48e404	still has dependencies, will retry
security-group:sg-0b696f2de86b8891b	still has dependencies, will retry
security-group:sg-01a4b6f05cc35ce28	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	volume:vol-0866862ea32cbcdd8
	dhcp-options:dopt-0b276355bab052d3d
	internet-gateway:igw-0de527e37dd48e404
	subnet:subnet-0e8cb6b116b64463e
	security-group:sg-01a4b6f05cc35ce28
	security-group:sg-0b696f2de86b8891b
	vpc:vpc-005eb92ca36ff4b1b
	route-table:rtb-059297ca1e2aeed46
	volume:vol-0df441b683b187b26
subnet:subnet-0e8cb6b116b64463e	still has dependencies, will retry
volume:vol-0866862ea32cbcdd8	ok
volume:vol-0df441b683b187b26	ok
internet-gateway:igw-0de527e37dd48e404	still has dependencies, will retry
security-group:sg-01a4b6f05cc35ce28	still has dependencies, will retry
security-group:sg-0b696f2de86b8891b	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	internet-gateway:igw-0de527e37dd48e404
	subnet:subnet-0e8cb6b116b64463e
	dhcp-options:dopt-0b276355bab052d3d
	security-group:sg-01a4b6f05cc35ce28
	security-group:sg-0b696f2de86b8891b
	route-table:rtb-059297ca1e2aeed46
	vpc:vpc-005eb92ca36ff4b1b
subnet:subnet-0e8cb6b116b64463e	ok
security-group:sg-0b696f2de86b8891b	ok
security-group:sg-01a4b6f05cc35ce28	ok
internet-gateway:igw-0de527e37dd48e404	ok
route-table:rtb-059297ca1e2aeed46	ok
vpc:vpc-005eb92ca36ff4b1b	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	dhcp-options:dopt-0b276355bab052d3d
	vpc:vpc-005eb92ca36ff4b1b
vpc:vpc-005eb92ca36ff4b1b	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	vpc:vpc-005eb92ca36ff4b1b
	dhcp-options:dopt-0b276355bab052d3d
vpc:vpc-005eb92ca36ff4b1b	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	dhcp-options:dopt-0b276355bab052d3d
	vpc:vpc-005eb92ca36ff4b1b
vpc:vpc-005eb92ca36ff4b1b	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	dhcp-options:dopt-0b276355bab052d3d
	vpc:vpc-005eb92ca36ff4b1b
```

6. What did you expect to happen?

I expected the 'peering connection' to be removed and then the delete to complete.

**Comment by chrislovecnm** [comment]
> Kops was not able to delete the VPC because I had created a 'peering connection' for the VPC (outside kops). These were the last few lines, where it couldn't proceed further

kops is behaving as designed.  If we removed components in the VPC that have been added after kops, components like ec2 instances or rds database could be removed.  If you add a dependency such as a security group, kops will not know how to delete it.  I think it would be risky to add in functionality to delete AWS components that kops does not maintain.

If you need components in the VPC that are not kops managed, one option is to re-use an existing VPC.  kops then does not manage VPC level resources, and you can delete clusters, and kops will not delete the VPC itself.  You will then not fail on a cluster delete.  Here are the docs for that: https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md

**Comment by caulagi** [comment]
Fair enough, thanks @chrislovecnm!
