### ISSUE TITLE
[AWS] by default launch configuration are created with "detailed monitoring"

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kops#4482]
We need to make the "detailed monitoring" option to be configurable.
detailed monitoring cause to additional costs. We need to leave the administrator the option to enable or disable it.
This should be configurable in the instance-group level.

applies to all kops versions

**Comment by rturk** [comment]
@vagababov how did you fixed this? At least manually?

**Comment by vendrov** [comment]
The fix has been merged
