### ISSUE TITLE
Using existing AWS VPC?

### ISSUE THREAD

**Issue by eroji** [kubernetes/kops#4490]
This is more of a question as I did not expect that kops stand up a whole new AWS VPC, with its own subnets, NAT gateways and etc. I'm wondering, is it possible to have it create a K8s cluster in existing VPC we already have?

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md

**Comment by eroji** [comment]
Awesome. Thank you!
