### ISSUE TITLE
Failed to propagate VERSION environment variable to protokube

### ISSUE THREAD

**Issue by tvi** [kubernetes/kops#4491]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

8d5da313af16a4374199faf983f9742b7d72abfd
Version 1.7.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

```
time make kops-install upload S3_BUCKET=s3://${S3_BUCKET_NAME} VERSION=dev; echo $?
kops -v10 create cluster --zones us-west-1a --networking amazon-vpc-routed-eni  --kubernetes-version 1.8.0 name.k8s.local
kops update cluster name.k8s.local —yes
```

5. What happened after the commands executed?
protokube gets downloaded correctly from S3 and imported to docker.
However it fails to start on all nodes because its tagged correctly with `dev` but the system is trying to spin up version 1.7.0 for some reason.

```
Feb 22 01:23:37 ip-172-20-57-24 dockerd[1389]: time="2018-02-22T01:23:37.934691720Z" level=error msg="Handler for POST /v1.26/containers/create returned error: No such image: protokube:1.7.0"
Feb 22 01:23:37 ip-172-20-57-24 docker[17766]: Unable to find image 'protokube:1.7.0' locally
Feb 22 01:23:38 ip-172-20-57-24 dockerd[1389]: time="2018-02-22T01:23:38.747212111Z" level=error msg="Handler for POST /v1.26/images/create returned error: repository protokube not found: does not exist or no pull access"
Feb 22 01:23:38 ip-172-20-57-24 systemd[1]: protokube.service: main process exited, code=exited, status=125/n/a
```
```
$ sudo docker images
REPOSITORY                                                    TAG                  IMAGE ID            CREATED             SIZE
protokube                                                     dev                  ce7b8cdb68ea        7 hours ago         273 MB

```

6. What did you expect to happen?
Cluster should start normally.

9. Anything else do we need to know?
Nope.

I think this is root cause of #2785.

**Comment by chrislovecnm** [comment]
I have noticed that recently.  If you leave the version out it seems to run off of the copy in your uploaded bucket.

**Comment by tvi** [comment]
The problem occurs under go1.10, because -ldflags for version has changed, makefile needs to be updated to account for this.

**Comment by tvi** [comment]
We need to add `all` package in case of g1.10 to make this work.
go install  -ldflags=all="-X k8s.io/kops.Version=1.8.1" k8s.io/kops/cmd/kops/
