### ISSUE TITLE
network-cidr is easily confused with subnet-cidr

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#45]
Maybe we should support vpc-cidr as well / instead

**Comment by kris-nova** [comment]
Per @justinsb :

- Rename zones -> subnets
- Get rid of private CIDR in subnet
- Use IG for etcd instead of zones

**Comment by kris-nova** [comment]
Private CIDR moved to https://github.com/kubernetes/kops/issues/999

**Comment by chrislovecnm** [comment]
We have PR inbound thay may help with this ... I am looking through issues to test against #1183

**Comment by kris-nova** [comment]
Closed with #1183
