### ISSUE TITLE
Subnet question

### ISSUE THREAD

**Issue by eroji** [kubernetes/kops#4501]
I am attempting to deploy a cluster into a shared VPC and the default subnets that are generated are too big and collides with the subnets I have created. Is there a reason why the CIDRs are /19? Also, what exactly is the difference between subnet and utility subnet?

**Comment by gambol99** [comment]
Hi @eroji .. In regard to the /19 I can't imagine there's an implicit reason behind, it was probably just what was chosen at the time. Assuming your driving kops from configuration you can easily pick and choose your own netmask. ... In regard to utility subnets .. with a private topology kops use's these to attach the NAT gateways and bastion hosts ..

**Comment by klaus993** [comment]
Hi @eroji. The best thing to do would be to choose your own network CIDR when creating the cluster; by using the `--network-cidr` flag of the command `kops create cluster`:

```
--network-cidr string                  Set to override the default network CIDR
```

For example:

```
kops create cluster 
 # ... 
 --network-cidr 172.41.0.0/16 
 # ...
```

Kops then uses that to allocate the subnets cidrs.

Regarding why that is the default, I don't know, but being something so variable, it's logical that it might usually be a custom value.

**Comment by eroji** [comment]
Thank you guys for clarifying. If I am understanding this correctly, the subnet definitions are set so that the pods directly bridge onto the AWS VPC? However, if I go with a VXLAN overlay network like flannel-vxlan, it should not need these subnets at all (other than utility subnets)?

**Comment by gambol99** [comment]
> If I am understanding this correctly, the subnet definitions are set so that the pods directly bridge onto the AWS VPC?

No, the subnet's are simply an opinionated design for the two typologies `private` and `public`  supported; it's just how kops decided on network layout, nothing to do with pods bridging VPC network.

**Comment by klaus993** [comment]
I think this should be closed, as the issue was resolved for @eroji 

Am I wrong?
