### ISSUE TITLE
Need to default docker storage to overlay

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#451]
If we are running on a 4.4 kernel, we need to default storage to overlay (not aufs).

**Comment by justinsb** [comment]
The approach (I think) we will take is to support a comma separated list of Docker Storage options, and nodeup will pick the first supported one.  So we will specify `overlay,aufs` and nodeup will choose overlay but fall back to aufs

**Comment by chrislovecnm** [comment]
Isn't this done?

**Comment by justinsb** [comment]
This is done, yes :-)
