### ISSUE TITLE
Add terraform provider version constraints

### ISSUE THREAD

**Issue by zacblazic** [kubernetes/kops#4516]
So for some background, we run our clusters using the terraform output. We've added a bot that will output the terraform plan when a PR is opened into the repo that manages our kubernetes infrastructure. On landing a change in master, the changes will be applied.

Today I noticed that our terraform plan had something new that wasn't something that we had changed:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

~ aws_route53_record.api-sandbox-kubernetes-acme
      allow_overwrite: "" => "true"

  ~ aws_route53_record.bastion-sandbox-kubernetes-acme
      allow_overwrite: "" => "true"
Plan: 0 to add, 2 to change, 0 to destroy.
```

Upon investigation, terraform added a new option field called [`allow_overwrite`](https://www.terraform.io/docs/providers/aws/r/route53_record.html#allow_overwrite) to the route53 resource in the [latest version (1.10.0)](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018) of the AWS provider

I was confused since we lock down the version of terraform we use.

I then found out something very surprising:
> Providers are released on a separate rhythm from Terraform itself, and thus have their own version numbers.

This means that if you [don't lock down](https://www.terraform.io/docs/configuration/providers.html#provider-versions) the provider version the latest will be used (assuming you're re-installing terraform).

Terraform recommends that we lock down providers:
> For production use, it is recommended to constrain the acceptable provider versions via configuration, to ensure that new versions with breaking changes will not be automatically installed by terraform init in future.

Thoughts on locking down the provider version? I'd say at minimum we should lock down the major version.

**Comment by schollii** [comment]
@fejta This is a serious issue and should not be closed:  /reopen 

This auto closing of ticket that are more than 30d inactive is silly. I've noticed several tickets that have not been dealt with at all and are closed due to this. At least, they should not be closed, but rather set to some other state, like Inactive or Suspended.
