### ISSUE TITLE
use of tilde for homedir is not defined on windows

### ISSUE THREAD

**Issue by sroylance** [kubernetes/kops#4523]
https://github.com/kubernetes/kops/blob/580f3508dadc04cae355bb528d01c12d2384256f/cmd/kops/create_cluster.go#L223

**Comment by justinsb** [comment]
We do pass this into ExpandPath:

```

// ExpandPath replaces common path aliases: ~ -> $HOME
func ExpandPath(p string) string {
	if strings.HasPrefix(p, "~/") {
		p = os.Getenv("HOME") + p[1:]
	}

	return p
}

```

I'm guessing the bug is that we need to look at HOMEDIR on windows IIRC.  Then there's the whole question of whether we want to be using Unix-isms like `~` on windows :-)

**Comment by chrislovecnm** [comment]
There should be a go specific call to get the home dir, I am not certain HOME is always set in windows. But I could be wrong.
