### ISSUE TITLE
Masters not starting in AWS Paris region

### ISSUE THREAD

**Issue by mariomazo** [kubernetes/kops#4531]
$ kops version
Version 1.8.1

I tried to launch a cluster in aws paris and I the masters wont start
I see this error in the ASG:
```
Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
```

I tried exactly the same configuration in Ireland and Oregon and it ran without issues.

```sh
export KUBERNETES_VERSION="1.8.6"

kops create cluster \
    --name ${NAME} \
    --cloud aws \
    --kubernetes-version ${KUBERNETES_VERSION} \
    --cloud-labels "Env=parisTest" \
    --zones "${ZONES}" \
    --master-zones "${ZONES}" \
    --dns-zone "${DNS_ZONE}" \
    --node-size "${NODE_SIZE}" \
    --node-count ${NODE_COUNT} \
    --master-size "${MASTER_SIZE}" \
    --topology private \
    --networking canal \
    --bastion \
    --ssh-access "${ADMIN_ACCESS}" \
    --admin-access "${ADMIN_ACCESS}" \
    --ssh-public-key ${SSH_PUBLIC_KEY} \
    --network-cidr "${NETWORK_CIDR}" \
    --api-loadbalancer-type internal \
    --yes
```

**Comment by chrislovecnm** [comment]
We have noticed that only M5's and C5's are available in some accounts in Paris Region.  What is available in yours?  We have had multiple problems reported with our Debian image and C5's, and we are uncertain if it is the kernel or C5's.  You need to use the Stretch AMI as well if you want to try the C5's.

**Comment by sid-mario** [comment]
yup that was the issue!
this can be closed/deleted

**Comment by mariomazo** [comment]
Yes this was the problem. Thanks
I have created I cluster with M5s and C5s. I will do some testing and tell you if I see something with the C5s.
Thanks

**Comment by chrislovecnm** [comment]
Closing ;)
