### ISSUE TITLE
Feature request: create bastions without an LB

### ISSUE THREAD

**Issue by drobinson123** [kubernetes/kops#4534]
Kops supports creating a cluster [without a load balancer in front of the API (the 'dns' option)](https://github.com/kubernetes/kops/blob/84fda7ac1cc0b74d24a14b4ac9dba3105fbe2585/docs/cluster_spec.md#api), but there is no such option for [SSH bastions -- LBs are always created for bastions](https://github.com/kubernetes/kops/blob/84fda7ac1cc0b74d24a14b4ac9dba3105fbe2585/docs/bastion.md). I'd like the ability to disable LB creation, and the corresponding security group(s).

Why is this useful? SSH bastions are not usually critical services, a single instance may be good enough (kops does only create 1 instance by default), some people/companies would rather not pay extra for multiple instances and/or an LB.

**Comment by drobinson123** [comment]
It may not be critical from a HA perspective, some downtime could be tolerated, but it's critical from a security perspective. And if it's not created then users can't SSH into a cluster w/ a private network topology, at least not without resorting to a home-grown solution.

**Comment by lawgeex-deployment** [comment]
Please re-open
we would like a bastion with no external AWS LB  - that will be accessed only by users with access to the VPN - i.e. in an internal AWS IP

**Comment by azalenski-callpage** [comment]
+1 For reopening the issue. It would be amazing to have an option to not create a LB for bastion, as it also generates additional costs for the LB.

**Comment by chattarajoy** [comment]
+1 for reopening this, our elb costs are way more than the actual EC2 instances cost for the ssh bastion enabled cluster.

**Comment by gersonmdesouza** [comment]
+1 for reopening this

**Comment by kristijorgji** [comment]
+1 need this feature, doesn't make sense to have lb and pay extra just for 1 bastion instance

**Comment by olemarkus** [comment]
/reopen

It is not that likely that any regular maintainer have the time to implement this, but I am happy to review any PR.

**Comment by kristijorgji** [comment]
/reopen very important issue this one, should be addressed. The bastion should be optional whether to be in load balancer or not, there is no security risk here.

The kops tools can create proper security group public (or cidrs specified by us) only for the single bastion instance, instead of always paying the cost of lb

**Comment by Archisman-Mridha** [comment]
/reopen
This is desirable.
