### ISSUE TITLE
Add build validation/tests for addon versions in bootstrapchannelbuilder.go

### ISSUE THREAD

**Issue by robinpercy** [kubernetes/kops#4536]
1. Describe IN DETAIL the feature/behavior/change you would like to see.
We need to figure out a way, at build time, to validate whether bootstrapchannelbuilder.go versions have been updated. Contributors frequently miss this step when updating addon manifests.

2. Feel free to provide a design supporting your feature request.
TBD.

@blakebarnett @chrislovecnm @justinsb  @mikesplain any thoughts on implementation? Is there any validation happening in the broader code base?

**Comment by chrislovecnm** [comment]
I think a simple validation is if files are updated in the directories then bootstrap builder needs to be updated. Probably could do a hack with bash and git. Keep it simple and iterate. Check that bootstrap builder is updated if the other is.

We would need a lexer type test to see if the version was updated. Which would be better, but more complicated.
