### ISSUE TITLE
kube-proxy ipvs error

### ISSUE THREAD

**Issue by antimack** [kubernetes/kops#4544]
kops version: 1.8.1
kubernetes version: 1.8.6
kubectl version: 1.8.6
image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
cloud provider: AWS

Hi, I am receiving an error from kube-proxy regarding ipvs module on start:
kube-proxy:
time="2018-03-01T13:36:50Z" level=error msg="Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not work until this is fixed."

kube-proxy:
time="2018-03-01T13:36:50Z" level=warning msg="Running modprobe ip_vs failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.111-k8s/modules.dep.bin'`, error: exit status 1"

Any ideas if it will affect the cluster work and if there is fix planned?
Thanks.

**Comment by gambol99** [comment]
fixed in #4550

**Comment by chrislovecnm** [comment]
closing
