### ISSUE TITLE
Creating Bastion instancegroup after new cluster build results in "Field cannot be changed: ElasticIp"

### ISSUE THREAD

**Issue by cnuber** [kubernetes/kops#4545]
1. What `kops` version are you running? Version 1.9.0-alpha.1 (git-f799036a3)
2. What Kubernetes version are you running? 1.9.3
3. What cloud provider are you using? AWS
4. What commands did you run?  What is the simplest way to reproduce this issue?
kops create instancegroup bastions --role Bastion --subnet utility-us-east-1a --name ${NAME}
kops update cluster ${NAME}
5. What happened after the commands executed?
W0301 18:19:06.756917   54621 executor.go:109] error running task "NatGateway/us-east-1a.kubernetes-dev-2-xxxxx.k8s.local" (9m59s remaining to succeed): Field cannot be changed: ElasticIp
W0301 18:19:06.756993   54621 executor.go:109] error running task "NatGateway/us-east-1c.kubernetes-dev-2-xxxxx.k8s.local" (9m59s remaining to succeed): Field cannot be changed: ElasticIp
W0301 18:19:06.757020   54621 executor.go:109] error running task "NatGateway/us-east-1b.kubernetes-dev-2-xxxxx.k8s.local" (9m59s remaining to succeed): Field cannot be changed: ElasticIp
6. What did you expect to happen?
kops update cluster to have run successfully and prompted to follow with a --yes to apply changes

7. Please provide your cluster manifest:

The relevant network bits:

  networkCIDR: 10.166.0.0/16
  networkID: vpc-ab-123456
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.166.36.0/24
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.166.37.0/24
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.166.38.0/24
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.166.39.0/24
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
I0301 18:33:35.446327   54678 request_logger.go:45] AWS request: ec2/DescribeNatGateways
I0301 18:33:35.655544   54678 changes.go:81] Field changed "ElasticIP" actual="{<nil> <nil> 0xc4211af3a8 <nil> *awstasks.Subnet null map[] *awstasks.RouteTable null}" expected="{0xc420ebe440 0xc420a0e990 <nil> <nil> *awstasks.Subnet null map[] *awstasks.RouteTable {\"Name\":\"private-us-east-1a.kubernetes-dev-2-xxxxx.k8s.local\",\"Lifecycle\":\"Sync\",\"ID\":null,\"VPC\":{\"Name\":\"kubernetes-dev-2-xxxxx.k8s.local\",\"Lifecycle\":\"Sync\",\"ID\":\"vpc-xxxxx\",\"CIDR\":\"10.166.0.0/16\",\"AdditionalCIDR\":null,\"EnableDNSHostnames\":null,\"EnableDNSSupport\":true,\"Shared\":true,\"Tags\":{\"kubernetes.io/cluster/kubernetes-dev-2-xxxxxx.k8s.local\":\"shared\"}},\"Shared\":true,\"Tags\":{\"kubernetes.io/cluster/kubernetes-dev-2-xxxxxx.k8s.local\":\"shared\"}}}"
I0301 18:33:35.677280   54678 changes.go:81] Field changed "ElasticIP" actual="{<nil> <nil> 0xc420e482c8 <nil> *awstasks.Subnet null map[] *awstasks.RouteTable null}" expected="{0xc420ebe5e0 0xc420a0e990 <nil> <nil> *awstasks.Subnet null map[] *awstasks.RouteTable {\"Name\":\"private-us-east-1c.kubernetes-dev-2-xxxxxx.k8s.local\",\"Lifecycle\":\"Sync\",\"ID\":null,\"VPC\":{\"Name\":\"kubernetes-dev-2-xxxxxx.k8s.local\",\"Lifecycle\":\"Sync\",\"ID\":\"vpc-xxxxxx\",\"CIDR\":\"10.166.0.0/16\",\"AdditionalCIDR\":null,\"EnableDNSHostnames\":null,\"EnableDNSSupport\":true,\"Shared\":true,\"Tags\":{\"kubernetes.io/cluster/kubernetes-dev-2-xxxxx.k8s.local\":\"shared\"}},\"Shared\":true,\"Tags\":{\"kubernetes.io/cluster/kubernetes-dev-2-xxxxx.k8s.local\":\"shared\"}}}"
I0301 18:33:35.726341   54678 changes.go:81] Field changed "ElasticIP" actual="{<nil> <nil> 0xc4212264a8 <nil> *awstasks.Subnet null map[] *awstasks.RouteTable null}" expected="{0xc420ebe510 0xc420a0e990 <nil> <nil> *awstasks.Subnet null map[] *awstasks.RouteTable {\"Name\":\"private-us-east-1b.kubernetes-dev-2-xxxxx.k8s.local\",\"Lifecycle\":\"Sync\",\"ID\":null,\"VPC\":{\"Name\":\"kubernetes-dev-2-xxxxx.k8s.local\",\"Lifecycle\":\"Sync\",\"ID\":\"vpc-xxxxx\",\"CIDR\":\"10.166.0.0/16\",\"AdditionalCIDR\":null,\"EnableDNSHostnames\":null,\"EnableDNSSupport\":true,\"Shared\":true,\"Tags\":{\"kubernetes.io/cluster/kubernetes-dev-2-xxxxx.k8s.local\":\"shared\"}},\"Shared\":true,\"Tags\":{\"kubernetes.io/cluster/kubernetes-dev-2-xxxxxx.k8s.local\":\"shared\"}}}"
W0301 18:33:35.726439   54678 executor.go:118] error running task "NatGateway/us-east-1b.kubernetes-dev-2-xxxxx.k8s.local" (8m47s remaining to succeed): Field cannot be changed: ElasticIp

9. Anything else do we need to know?

We are using an existing VPC that has an associated gateway in place.  This functionality worked with kops 1.8.0 and 1.8.1 utilizing the same commands.

**Comment by cnuber** [comment]
As an update this occurs in Kops 1.9 regardless of what change is made to the cluster after an initial creation as follows:

1. kops create cluster with an existing vpc ID and network CIDR
2. kops edit cluster and modify the subnet CIDRs to ones you'd like kops to create with
3. kops update cluster --yes
4.  Make any change and run kops update cluster again and receive:

Field cannot be changed: ElasticIp

**Comment by cnuber** [comment]
#4578 seems similar

**Comment by krogon** [comment]
> We are using an existing VPC that has an associated gateway in place.

Can you provide the IDs of your existing NatGateways as `egress` parameter?
https://github.com/kubernetes/kops/blob/7b31187e9f27a87da8b5687a3697df4096e8b897/docs/run_in_existing_vpc.md#shared-nat-gateways

**Comment by cnuber** [comment]
The issue is that we are using a VirtualPrivateGateway and not a NatGateway.  vgw is not a supported egress type in the kops edit cluster apparently.  Support for VGW needs to be added in these checks looks like.

**Comment by krogon** [comment]
Did you mentioned that VirtualPrivateGateway worked in 1.8.0/1.8.1 ?

**Comment by chrislovecnm** [comment]
@krogon VirtualPrivateGateway has not been supported
