### ISSUE TITLE
Ensure the pki/issued state store directory remains viable for read-only access

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#4547]
From looking at the code, the `keyset.yaml` file will contain both public and private key material, this will cause a security problem for us as we are assuming that the `issued` directory will only contain the public certificate.  We use this all over the place to generate additional certs for the cluster, etc.  If possible can we store keyset.yaml only in the `private` directory if it contains private data?

**Comment by chrislovecnm** [comment]
@blakebarnett should we break up the private and public data?

**Comment by blakebarnett** [comment]
It seems maybe the intention was to simplify things by having it together, it would be best to store it in the private dir only though, if it will contain private data.

**Comment by blakebarnett** [comment]
Yep, I forgot to close after you mentioned it before.
