### ISSUE TITLE
kops create cluster with API lb type = internal throws error "Field is required: Subnets" 

### ISSUE THREAD

**Issue by mchodson** [kubernetes/kops#4548]
1. kops v1.8.1

2. kubernetes v1.8.4

3. cloud = aws

4. repro stuff:
`kops create cluster \
  --state $KOPS_STATE_STORE \
  --name $NAME \
  --node-count $NODECOUNT \
  --node-size $NODESIZE \
  --master-size $MASTERSIZE \
  --master-volume-size $MASTERVOLSIZE \
  --node-volume-size $NODEVOLSIZE \
  --associate-public-ip=false \
  --api-loadbalancer-type public \
  --zones $ZONES \
  --master-zones $ZONES \
  --vpc=$VPCID \
  --network-cidr $CIDR \
  --networking weave \
  --dns private \
  --dns-zone $NAME
  --admin-access $OFFICE_IP \
  --admin-access $CIDR \
  --ssh-access $OFFICE_IP \
  --ssh-access $CIDR \
  --cloud-labels Cluster=$CLUSTERNAME \
  --bastion=false \
  --topology private \
  --image $AMI \
  --ssh-public-key "~/.ssh/kubernetes-admin.pub"
`
that command fails. but if i change  api lb type from internal to public, the command works.
--api-loadbalancer-type public

Also if I manually generate the config yaml and use 
`
  api:
    loadBalancer:
      type: Internal
`
everything works as expected. it only seems to be in running kops create that there is an issue

5. The error i get looks like this:
I0301 11:31:40.852711   50547 executor.go:91] Tasks: 89 done / 94 total; 1 can run
W0301 11:31:41.024307   50547 executor.go:109] error running task "LoadBalancer/api.REDACTED" (9m39s remaining to succeed): Field is required: Subnets
I0301 11:31:41.024339   50547 executor.go:124] No progress made, sleeping before retrying 1 failed task(s)

6.  I expect the command to succeed whether i use public or internal, not just public.

7. 

8. 

9. This is being run against an existing VPC (made with terraform)

What I suspect is happening is there is some preauth step on the internal ELB during kops create that's causing some conflict with the pre-existing VPC/subnets.  When using public, however, that auth either passes or is not run. Normally when I make a new cluster i run "kops create...." then i modify the config for the VPC + subnet CIDRs to use so that it plays nice with what terraform has already created. 

my workaround is:
A. run "$kops create cluster..." and use flag for API ELB = public
B. manually edit the config to make it internal
C. run "$kops update cluster..."

I've heard rumors about making kops more friendly to vpc's made outside of kops. specifically allowing for subnet config via flags instead of requiring manual manipulation. that would probably "solve" this too.

**Comment by mmacfadden** [comment]
I am running into this same issue. I am a it confused in your description of the issue and the work around. You seem to indicate that the error comes up in `kops create`. But to my eye, the error message you provide (and the one I am getting) actually comes from `kops update` when kops actually tries to go build the cluster. I don't think `kops create` actually runs any tasks does it?

**Comment by mknapik1** [comment]
Experiencing the same issue here.
kops Version 1.9.0 (git-cccd71e67)

kops create cluster --vpc vpc-02594b9969764014f --subnets subnet-07da135706da3f972,subnet-0b8fff07cda8dd39b --api-loadbalancer-type public --ssh-public-key ~/.ssh/kops.pub --networking amazon-vpc-routed-eni --encrypt-etcd-storage --master-size t2.medium --node-size t2.large  --zones us-east-2a,us-east-2b --name ${NAME}

In my case, I I tried updating the config manually and still got the same error.

**Comment by aslobodskoy-fiksu** [comment]
The same with
$ kops version
Version 1.9.1

**Comment by ms4720** [comment]
+1 kops Version 1.10.0

**Comment by MoShitrit** [comment]
Hey everyone!
Just came across the same issue with kops v 1.10.0.
I was able to solve it by adding another flag to my command line, `utility-subnets=<SUBNET_ID>`
I used the same subnet ID for both `--subnets` and `--utility-subnets`, so no need to allocate a different subnet for that argument.
After adding that- the error message was gone.
For the record- here's the full command I used (for obvious reasons, masked out the values):

`kops create cluster --name my-cluster --zones=us-east-1a --node-count=3 --associate-public-ip=false --topology=private --networking=calico --api-loadbalancer-type=internal --subnets=<MY_SUBNET> --vpc=<MY_VPC> --utility-subnets=<MY_SUBNET>`

**Comment by ms4720** [comment]
@MoShitrit it works with `  --api-loadbalancer-type=internal ` and ` --topology=private`, it breaks with `  --api-loadbalancer-type=internal ` and ` --topology=public`

**Comment by taragurung** [comment]
> Experiencing the same issue here.
> kops Version 1.9.0 (git-cccd71e67)
> 
> kops create cluster --vpc vpc-02594b9969764014f --subnets subnet-07da135706da3f972,subnet-0b8fff07cda8dd39b --ssh-public-key ~/.ssh/kops.pub --networking amazon-vpc-routed-eni --encrypt-etcd-storage --master-size t2.medium --node-size t2.large --zones us-east-2a,us-east-2b --name ${NAME}
> 
> In my case, I I tried updating the config manually and still got the same error.
> error running task "LoadBalancer/api.REDACTED" (9m49s remaining to succeed): Field is required: Subnets

I am having same issue when trying to update from public to internal for loadbalancer during kops update .

**Comment by olemarkus** [comment]
Hi @taragurung can you post a new issue with the details requested in the issue template?
