### ISSUE TITLE
add hostPort support to kube-router

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kops#4570]
Should be easy since portmap is bundled in kubernetes 1.9

https://github.com/cloudnativelabs/kube-router/issues/168

**Comment by murali-reddy** [comment]
I am working on this issue.

**Comment by felipejfc** [comment]
cool, thanks @murali-reddy

**Comment by murali-reddy** [comment]
@felipejfc i just checked kops 1.9 it does not still install `portmap` CNI?

```
admin@ip-172-20-34-10:~$ ls -l /opt/cni/bin/
total 16220
-rwxr-xr-x 1 root root 3890407 Mar  9 06:13 bridge
-rwxr-xr-x 1 root root 2814104 Mar  9 06:13 flannel
-rwxr-xr-x 1 root root 2991965 Mar  9 06:13 host-local
-rwxr-xr-x 1 root root 3026388 Mar  9 06:13 loopback
-rwxr-xr-x 1 root root 3877986 Mar  9 06:13 ptp
```

 > Should be easy since portmap is bundled in kubernetes 1.9

can you please elobrate this statement? Whose responsibiity is to install CNI plug-ins? cluster-installer?

**Comment by felipejfc** [comment]
I am confused, take a look:

https://github.com/kubernetes/kubernetes/issues/49480

**Comment by felipejfc** [comment]
Maybe you should include portmap here somewhere
https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/network.go

**Comment by murali-reddy** [comment]
Update: In last [release](https://github.com/cloudnativelabs/kube-router/releases/tag/v0.1.0) of kube-router necessary changes are made to support hostport. So its matter of updating manifest used in Kops and some changes to installed CNI plug-ins.

**Comment by dtshepherd** [comment]
@felipejfc Did you ever resolve this issue? I'm trying to get `portmap` working with my cluster and `kops` doesn't seem to install the plugin.  This is running kube 1.10, but 1.9 had the same issue.

**Comment by murali-reddy** [comment]
portmap plugin will be installed as part of kops in 1.10 installs

https://github.com/kubernetes/kops/pull/5494

Kube-router already supports portmap functionality, however kube-router version need to be bumped (from default 0.1.0 installed through kops)
