### ISSUE TITLE
kops validate cluster bug

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#4587]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

kops 1.8.0
kops master

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

K8s 1.8.3

3. What cloud provider are you using?

aws

4. What commands did you run?  What is the simplest way to reproduce this issue?

`kops validate cluster` with kops 1.8.0 and kops maseter

5. What happened after the commands executed?

```console
$ kops-1.8.0 validate cluster
Using cluster from kubectl context: clove.test
Validating cluster clove.test

INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-us-east-1a	Master	c4.large	1	1	us-east-1a
nodes			Node	t2.medium	1	1	us-east-1a,us-east-1b,us-east-1c

NODE STATUS
NAME				ROLE	READY
ip-172-20-50-24.ec2.internal	master	True

Validation Failed
Ready Master(s) 1 out of 1.
Ready Node(s) 0 out of 1.

your nodes are NOT ready clove.e2e-kops-aws.test-cncf-aws.k8s.io

$ kops validate cluster
Using cluster from kubectl context: clove.test

Validating cluster clove.test

INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-us-east-1a	Master	c4.large	1	1	us-east-1a
nodes			Node	t2.medium	1	1	us-east-1a,us-east-1b,us-east-1c

NODE STATUS
NAME				ROLE	READY
ip-172-20-50-24.ec2.internal	master	True

Your cluster clove.test is ready
```

6. What did you expect to happen?

kops master should perform like kops 1.8.0.  kops master is passing the cluster, while kops 1.8.0 is failing the cluster.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by blakebarnett** [comment]
per conversation with @justinsb, this probably justifies a new e2e test to be sure.

**Comment by chrislovecnm** [comment]
Yah this is upstream changes i think. We could do a validate before we validate with the test runner.

**Comment by justinsb** [comment]
Do we know _why_ kops-1.8.0 considered the cluster not ready?

**Comment by johanneswuerbach** [comment]
Anything I could help with this? Just was hit by that when rolling a cluster

**Comment by sstarcher** [comment]
@johanneswuerbach did you hit this in 1.9.0-beta-2?  I thought it was fixed already.

**Comment by johanneswuerbach** [comment]
Yes, I was running beta-2. Not sure whether it was this or https://github.com/kubernetes/kops/pull/4941

**Comment by johanneswuerbach** [comment]
It could be also related to something else as we have seen some of our clusters marking a bunch of nodes as `NotReady` after a master has been rolled, but I'm still investigating the root-cause, which looks like kubelets are caching the internal master dns and won't connect anymore.

**Comment by sstarcher** [comment]
@johanneswuerbach If it was this issue it should of reported healthy and then failed healthy again and finally reported healthy.

If it was #4941 it should never become healthy.

**Comment by johanneswuerbach** [comment]
Thanks @sstarcher will continue testing and report back if I found something.
