### ISSUE TITLE
Provide a pathway for installing Device Support on kops

### ISSUE THREAD

**Issue by benjigoldberg** [kubernetes/kops#4591]
Hello Maintainers!

I would like to propose a new path for installing [Device Plugins in Kubernetes in 1.8+](https://kubernetes.io/docs/concepts/cluster-administration/device-plugins/). The reason this issue came up for me is a desire to [expose GPUs in my AWS Cluster](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/). While kops does [support GPUs via hooks](https://github.com/kubernetes/kops/tree/master/hooks/nvidia-bootstrap), it is using the soon-to-be-deprecated Accelerators API. 

I would be happy to contribute to making this effort a success, but I would like some input from more experienced maintainers on where they best see this work being placed. Currently, we use user data in our kops GPU node to [expose the NVIDIA GPUs via the instructions they outline](https://github.com/NVIDIA/k8s-device-plugin).

Here's an excerpt from the prerequisites for installing the NVIDIA Daemonset that exposes support within the cluster:

>  NVIDIA drivers ~= 361.93
    nvidia-docker version > 2.0 (see how to install and it's prerequisites)
    docker configured with nvidia as the default runtime.
    Kubernetes version = 1.9
    The DevicePlugins feature gate enabled

As you can see, this is a nontrivial set of requirements. Given that, I don't think the current hooks implementation will support the new Device Plugin architecture and this set of requirements, as it requires such heavy modification to the host OS.

**Comment by byndcivilization** [comment]
Is there any work happening on this? We are currently trying to run gpus on debian-stretch. I've baked the nvidia driver into an AMI but can rework that into an nvidia-bootstrap update. I'm having trouble with the nvidia-docker piece though. Currently if I run this as a hook, nodeup will overwrite the changes made by the hook.

**Comment by brunsgaard** [comment]
I will do PR on this later, but for now you can take a look at

https://github.com/brunsgaard/kops-nvidia-docker-installer

It works here, but need more testing and tuning.

**Comment by mindprince** [comment]
> what are GKE doing here, my guess is that nvidia-docker runtime is preinstalled on the machine images that have accelerators attached?

GKE doesn't use nvidia-docker. The shared libraries that need to be injected into the container are injected by the device plugin: https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/cmd/nvidia_gpu/README.md

**Comment by brunsgaard** [comment]
@mindprince Is your guess that the same approach would work for kops?

**Comment by mindprince** [comment]
It should.

**Comment by brunsgaard** [comment]
@strin I am working on an installer for `nvidia-docker` that uses kops hooks.

A rough but working solution can be found in my kops fork.
https://github.com/brunsgaard/kops/tree/nvidia-docker-docs/hooks/nvidia-docker

A PR will arrive some time next week :)

Let me know if you give it a go, I am available in the slack channel for questions if you need help 👍

**Comment by bhack** [comment]
There is already a PR/Thread in https://github.com/kubernetes/kops/pull/4971

**Comment by brunsgaard** [comment]
@bhack Okay, I did not know there already was people working on this. The work in the PR uses the GKE approach what I have done is using the Nvidia approach. Should I do a PR on my nvidia-docker-installer-hook or would you rather that I drop it and help finishing up #4971?

**Comment by bhack** [comment]
@brunsgaard As you know upstream has still not found a unified solution in https://github.com/kubernetes/kubernetes/issues/54011. So it is really up to us as kops community to choiche what path we want to follow.

**Comment by kaazoo** [comment]
@brunsgaard Thanks for the hook script. I forked the repo at https://github.com/kaazoo/kops-nvidia-docker-installer and replaced the comands for CentOS 7. Perhaps both can be unified to support Debian/Ubuntu + CentOS.
I also had to update the Nvidia driver version, as building the driver failed when using stable upstream kernel versions (currently using kernel 4.16.x from 'elrepo' repository).

**Comment by benjigoldberg** [comment]
I think at this point with where Kubernetes is at it seems perhaps preferable for users to make their own AMI with the drivers and then use the nvidia device plugin support?

All thats needed:
1. Kops AMI + GPU drivers + recent enough docker that it will work with nvidia device plugin + nvidia-docker/config file for the docker daemon to use nvidia-docker
2. device plugin featuregate flag to kubelet 
3. Install daemonset for nvidia device plugin 

This _could_ be built into kops, but I kind of wonder if its really necessary now. I wonder how much of this is honestly "niche" at this point.
