### ISSUE TITLE
kops on GCE error

### ISSUE THREAD

**Issue by awardsolutionsuser** [kubernetes/kops#4603]
kops Version 1.8.1 (git-94ef202)

i'm trying to create kubernetes on GCE following kops GCE tutorial https://github.com/kubernetes/kops/blob/master/docs/tutorial/gce.md

i have a DNS zone:
gcloud dns managed-zones list
NAME       DNS_NAME             DESCRIPTION
mydnszone  rnmuscentral1c.com.  A zone

when I do 'kops create cluster rnmcluster.rnmuscentral1c.com --zones us-central1-a --state gs://as-sdn-project-bucket --project=myproject'
i get this error:
**error doing DNS lookup for NS records for "rnmuscentral1c.com": lookup rnmuscentral1c.com on 127.0.1.1:53: no such host**

i get the same error when i do 'kops update cluster'

i can see that the cluster is created:
kops get cluster --state $KOPS_STATE_STORE
NAME				CLOUD	ZONES rnmcluster.rnmuscentral1c.com	 gce

i can dig the name and see that it does have an address:
dig rnmuscentral1c.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> rnmuscentral1c.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43088
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;rnmuscentral1c.com.		IN	A

;; ANSWER SECTION:
**rnmuscentral1c.com.	10	IN	A	198.105.244.228
rnmuscentral1c.com.	10	IN	A	198.105.254.228**

;; Query time: 41 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Wed Mar 07 12:04:10 CST 2018
;; MSG SIZE  rcvd: 68

i think this means i need to add a DNS record to google DNS but i don't know how to get the IP address of my cluster which is needed to add the DNS record. Any help on how to get IP address which is
needed for this record?

thanks,
[kops_dns_err.txt](https://github.com/kubernetes/kops/files/1790439/kops_dns_err.txt)

Rod

**Comment by chrislovecnm** [comment]
How is your DNS setup?  You need to host a domain and a sub-domain in Google DNS.

**Comment by awardsolutionsuser** [comment]
i was just doing 'gcloud dns managed-zones create' and then i was going to add a record but I could not find the IP address of the cluster to put in the record.

I noticed in the aws.md document that i can avoid DNS (by using gossip) by changing the cluster name to end in k8s.local.  I really don't need the domain and DNS server. is there any reason not to use the gossip solution?

**Comment by awardsolutionsuser** [comment]
i got around this problem by using gossip protocol so that i didn't need the DNS stuff.
the full solutions is documented in issue 4608 with helpful insights from 3678.
