### ISSUE TITLE
Segv when running kops create instancegroup

### ISSUE THREAD

**Issue by mkornacker** [kubernetes/kops#4607]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

1.8.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
kops create ig <> --state s3://kops.<> --name <> --subnet us-west-2a

5. What happened after the commands executed?

this is the output with -v 10
I0307 20:59:39.892057   23165 s3context.go:163] Found bucket "kops.<>" in region "us-west-2"
I0307 20:59:39.892218   23165 s3fs.go:176] Reading file "s3://kops<>/<>/config"
I0307 20:59:39.991295   23165 channel.go:93] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I0307 20:59:39.991511   23165 channel.go:98] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I0307 20:59:39.991647   23165 context.go:140] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I0307 20:59:40.061867   23165 channel.go:107] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.8.0 <1.9.0"
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.9.0 <1.10.0"
    # Need stretch as default in 1.10 (for nvme)
    # BUT... this is causing the submit queue to block, so back to jessie temporarily: https://github.com/kubernetes/kubernetes/issues/56763
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.10.0"
    - providerID: gce
      name: "cos-cloud/cos-stable-60-9592-90-0"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.9.0"
    recommendedVersion: 1.9.3
    requiredVersion: 1.9.0
  - range: ">=1.8.0"
    recommendedVersion: 1.8.6
    requiredVersion: 1.8.0
  - range: ">=1.7.0"
    recommendedVersion: 1.7.11
    requiredVersion: 1.7.0
  - range: ">=1.6.0"
    recommendedVersion: 1.6.13
    requiredVersion: 1.6.0
  - range: ">=1.5.0"
    recommendedVersion: 1.5.8
    requiredVersion: 1.5.1
  - range: "<1.5.0"
    recommendedVersion: 1.4.12
    requiredVersion: 1.4.2
  kopsVersions:
  - range: ">=1.9.0-alpha.1"
    recommendedVersion: 1.9.0-alpha.1
    #requiredVersion: 1.9.0-alpha.1
    kubernetesVersion: 1.9.3
  - range: ">=1.8.0-alpha.1"
    recommendedVersion: 1.8.0
    #requiredVersion: 1.8.0
    kubernetesVersion: 1.8.6
  - range: ">=1.7.0-alpha.1"
    recommendedVersion: 1.7.1
    #requiredVersion: 1.7.0
    kubernetesVersion: 1.7.11
  - range: ">=1.6.0-alpha.1"
    #recommendedVersion: 1.6.0
    #requiredVersion: 1.6.0
    kubernetesVersion: 1.6.13
  - range: ">=1.5.0-alpha1"
    recommendedVersion: 1.5.1
    #requiredVersion: 1.5.1
    kubernetesVersion: 1.5.8
  - range: "<1.5.0"
    recommendedVersion: 1.4.4
    #requiredVersion: 1.4.4
    kubernetesVersion: 1.4.12
I0307 20:59:40.062301   23165 s3fs.go:176] Reading file "s3://kops.<>/<>/instancegroup/<>"
I0307 20:59:40.084525   23165 aws_utils.go:39] Querying EC2 for all valid regions
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1e0 pc=0x26c154f]

goroutine 1 [running]:
main.RunCreateInstanceGroup(0xc420a66220, 0xc4201d78c0, 0xc420a787e0, 0x1, 0x9, 0x4a706e0, 0xc42000c018, 0xc420a5e500, 0x0, 0x0)
	/go/src/k8s.io/kops/cmd/kops/create_ig.go:160 +0x2ff
main.NewCmdCreateInstanceGroup.func1(0xc4201d78c0, 0xc420a787e0, 0x1, 0x9)
	/go/src/k8s.io/kops/cmd/kops/create_ig.go:87 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201d78c0, 0xc420a78630, 0x9, 0x9, 0xc4201d78c0, 0xc420a78630)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4c60000, 0x4c90700, 0x0, 0x0)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x4c60000, 0x4c90710, 0x0)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/go/src/k8s.io/kops/cmd/kops/root.go:95 +0x9b
main.main()
	/go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20

6. What did you expect to happen?

For an editor to open up and the instancegroup to get created.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-02-23T16:42:05Z
  name: <>
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["s3:*"],
          "Resource": ["arn:aws:s3:::<>/*"]
        },
        {
          "Effect": "Allow",
          "Action": ["s3:*"],
          "Resource": ["arn:aws:s3:::<>/"]
        }
      ]
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops.<>/<>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.6
  masterInternalName: api.internal.<>
  masterPublicName: api.<>
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

See above.

9. Anything else do we need to know?

I'm running this on an EC2 machine, where it fails. If I run the same from my desktop (exact same kops and kubectl version) it works.

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by chrislovecnm** [comment]
This should be fixed in 1.9.0 alpha if you want to try that.

**Comment by chrislovecnm** [comment]
Closing

**Comment by peterkuiper** [comment]
@mkornacker What permissions are needed to get this working?

**Comment by chrislovecnm** [comment]
@peterkuiper we have ima roles in the aws guide and a script under hack

**Comment by mkornacker** [comment]
I ended up adding AmazonEC2FullAccess. You can probably do this with narrower policies, but I didn't feel like playing around with it.

Prior to that, I also added Route53FullAccess and AmazonS3FullAccess.

**Comment by peterkuiper** [comment]
Thanks for the answer. I already have those permissions as stated in the guide so I was hoping it was something I did wrong. I'm also getting the same error. Permissions seem fine:

```
aws ec2 describe-availability-zones
{
    "AvailabilityZones": [
        {
            "State": "available",
            "Messages": [],
            "RegionName": "eu-central-1",
            "ZoneName": "eu-central-1a"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "eu-central-1",
            "ZoneName": "eu-central-1b"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "eu-central-1",
            "ZoneName": "eu-central-1c"
        }
    ]
}
```

```
kops version
Version 1.8.1
```

```
kops create ig nodes-eu-central-1b --subnet eu-central-1b --state s3://... -v 10
I0310 11:10:47.018875   64672 loader.go:357] Config loaded from file /.../.kube/config
Using cluster from kubectl context: ...

I0310 11:10:47.668806   64672 s3context.go:163] Found bucket "..." in region "us-east-1"
I0310 11:10:47.668891   64672 s3fs.go:176] Reading file ".../.../config"
I0310 11:10:48.243417   64672 channel.go:93] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I0310 11:10:48.243458   64672 channel.go:98] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I0310 11:10:48.243476   64672 context.go:140] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I0310 11:10:48.459092   64672 channel.go:107] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.8.0 <1.9.0"
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.9.0 <1.10.0"
    # Need stretch as default in 1.10 (for nvme)
    # BUT... this is causing the submit queue to block, so back to jessie temporarily: https://github.com/kubernetes/kubernetes/issues/56763
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.10.0"
    - providerID: gce
      name: "cos-cloud/cos-stable-60-9592-90-0"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.9.0"
    recommendedVersion: 1.9.3
    requiredVersion: 1.9.0
  - range: ">=1.8.0"
    recommendedVersion: 1.8.6
    requiredVersion: 1.8.0
  - range: ">=1.7.0"
    recommendedVersion: 1.7.11
    requiredVersion: 1.7.0
  - range: ">=1.6.0"
    recommendedVersion: 1.6.13
    requiredVersion: 1.6.0
  - range: ">=1.5.0"
    recommendedVersion: 1.5.8
    requiredVersion: 1.5.1
  - range: "<1.5.0"
    recommendedVersion: 1.4.12
    requiredVersion: 1.4.2
  kopsVersions:
  - range: ">=1.9.0-alpha.1"
    recommendedVersion: 1.9.0-alpha.1
    #requiredVersion: 1.9.0-alpha.1
    kubernetesVersion: 1.9.3
  - range: ">=1.8.0-alpha.1"
    recommendedVersion: 1.8.0
    #requiredVersion: 1.8.0
    kubernetesVersion: 1.8.6
  - range: ">=1.7.0-alpha.1"
    recommendedVersion: 1.7.1
    #requiredVersion: 1.7.0
    kubernetesVersion: 1.7.11
  - range: ">=1.6.0-alpha.1"
    #recommendedVersion: 1.6.0
    #requiredVersion: 1.6.0
    kubernetesVersion: 1.6.13
  - range: ">=1.5.0-alpha1"
    recommendedVersion: 1.5.1
    #requiredVersion: 1.5.1
    kubernetesVersion: 1.5.8
  - range: "<1.5.0"
    recommendedVersion: 1.4.4
    #requiredVersion: 1.4.4
    kubernetesVersion: 1.4.12
I0310 11:10:48.459423   64672 s3fs.go:176] Reading file "s3://.../.../instancegroup/nodes-eu-central-1b"
I0310 11:10:48.586402   64672 aws_utils.go:39] Querying EC2 for all valid regions
I0310 11:10:49.180738   64672 aws_cloud.go:956] Querying EC2 for all valid zones in region "eu-central-1"
I0310 11:10:49.180867   64672 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1e0 pc=0x31bd43f]

goroutine 1 [running]:
k8s.io/kops/pkg/apis/kops.(*InstanceGroup).AddInstanceGroupNodeLabel(...)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/pkg/apis/kops/instancegroup.go:172
main.RunCreateInstanceGroup(0xc420192b00, 0xc4202da900, 0xc42011f340, 0x1, 0x7, 0x57389e0, 0xc420094008, 0xc42061ec80, 0x0, 0x0)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/create_ig.go:160 +0x2ff
main.NewCmdCreateInstanceGroup.func1(0xc4202da900, 0xc42011f340, 0x1, 0x7)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/create_ig.go:87 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202da900, 0xc42011f2d0, 0x7, 0x7, 0xc4202da900, 0xc42011f2d0)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x234
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5930a00, 0x3507900, 0x0, 0x0)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x5930a00, 0x5964c58, 0x0)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/root.go:95 +0x91
main.main()
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```

**Comment by peterkuiper** [comment]
Using kops `Version 1.9.0-alpha.1 (git-d41d56a70)` I'm getting the following error message:

```
error assigning default machine type for nodes: error finding default machine type: cannot find subnet "eu-central-1b" (declared in instance group "nodes-eu-central-1b", not found in cluster)
```

Seems that this issie is related: https://github.com/kubernetes/kops/issues/760

I'm not sure if where to specifiy the default machine type (AWS?) and if I need to manually add the subnet. I would be more than happy to update the documentation on this.
