### ISSUE TITLE
kops on GCE network error

### ISSUE THREAD

**Issue by awardsolutionsuser** [kubernetes/kops#4608]
trying to run kops on GCE using https://github.com/kubernetes/kops/blob/master/docs/tutorial/gce.md

here's the cluster create command and some errors which follow:
KOPS_FEATURE_FLAGS=AlphaAllowGCE
+ kops create cluster simple.k8s.local --zones us-central1-c --master-zones us-central1-c --node-count 3 --project focal-dolphin-676 --image ubuntu-os-cloud/ubuntu-1604-xenial-v20170202 --yes
I0307 19:57:23.327503   12358 create_cluster.go:439] Inferred --cloud=gce from zone "us-central1-c"
I0307 19:57:23.327619   12358 create_cluster.go:971] Using SSH public key: /home/ubuntu/.ssh/id_rsa.pub
I0307 19:57:23.327644   12358 gce_cloud.go:93] Will load GOOGLE_APPLICATION_CREDENTIALS from /home/ubuntu/.config/gcloud/application_default_credentials.json
I0307 19:57:23.521327   12358 gce_cloud.go:128] running with GCE credentials: email=latenite4@gmail.com, scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/plus.me
I0307 19:57:29.255688   12358 apply_cluster.go:450] Gossip DNS: skipping DNS validation
W0307 19:57:29.274830   12358 external_access.go:36] TODO: Harmonize gcemodel ExternalAccessModelBuilder with awsmodel
W0307 19:57:29.275082   12358 firewall.go:35] TODO: Harmonize gcemodel with awsmodel for firewall - GCE model is way too open
W0307 19:57:29.275203   12358 firewall.go:63] Adding overlay network for X -> node rule - HACK
W0307 19:57:29.279262   12358 firewall.go:64] We should probably use subnets?
W0307 19:57:29.279422   12358 firewall.go:118] Adding overlay network for X -> master rule - HACK
I0307 19:57:33.041651   12358 executor.go:91] Tasks: 0 done / 54 total; 27 can run
I0307 19:57:33.209110   12358 address.go:123] GCE creating address: "api-simple-k8s-local"
I0307 19:57:33.727981   12358 vfs_castore.go:435] Issuing new certificate: "ca"
I0307 19:57:33.891031   12358 vfs_castore.go:435] Issuing new certificate: "apiserver-aggregator-ca"
W0307 19:57:41.060715   12358 executor.go:109] **error running task "Network/default" (9m51s remaining to succeed): GCE networks in legacy mode are not supported.  Please convert to auto mode or specify a different network.**
error running task "Network/default" (9m51s remaining to succeed): GCE networks in legacy mode are not supported.  Please convert to auto mode or specify a different network.
I0307 19:57:41.060871   12358 executor.go:91] Tasks: 26 done / 54 total; 14 can run
I0307 19:57:41.884985   12358 vfs_castore.go:435] Issuing new certificate: "kube-controller-manager"
I0307 19:57:41.958340   12358 vfs_castore.go:435] Issuing new certificate: "apiserver-proxy-client"
I0307 19:57:42.302142   12358 vfs_castore.go:435] Issuing new certificate: "kube-proxy"
I0307 19:57:42.427448   12358 vfs_castore.go:435] Issuing new certificate: "kubecfg"
I0307 19:57:42.492106   12358 vfs_castore.go:435] Issuing new certificate: "kube-scheduler"
I0307 19:57:42.517370   12358 vfs_castore.go:435] Issuing new certificate: "kops"
I0307 19:57:42.659749   12358 vfs_castore.go:435] Issuing new certificate: "kubelet-api"
I0307 19:57:43.189310   12358 vfs_castore.go:435] Issuing new certificate: "master"
I0307 19:57:43.264102   12358 vfs_castore.go:435] Issuing new certificate: "kubelet"
I0307 19:57:43.270496   12358 vfs_castore.go:435] Issuing new certificate: "apiserver-aggregator"
W0307 19:57:48.239796   12358 executor.go:109] e**rror running task "Network/default" (9m44s remaining to succeed): GCE networks in legacy mode are not supported.  Please convert to auto mode or specify a different network.**
I0307 19:57:48.239942   12358 executor.go:91] Tasks: 39 done / 54 total; 1 can run
W0307 19:57:48.368198   12358 executor.go:109] error running task "Network/default" (9m44s remaining to succeed): GCE networks in legacy mode are not supported.  Please convert to auto mode or specify a different network.

i tried looking at the create docs https://github.com/kubernetes/kops/blob/master/docs/cli/kops_create.md but no real help.

i know this is alpha code, but is there a way to get past these 'Network/default' errors?

**Comment by chrislovecnm** [comment]
You network appears to be setup in legacy mode. kops only support auto mode.

**Comment by awardsolutionsuser** [comment]
thanks for the help Chris. i think kops was trying to use the default network which is legacy mode.
i created a new network (auto mode) and told kops to use the new one.

here's the commands for getting kops working on GCE:

gsutil mb $GCP_DATA_STORE

export KOPS_FEATURE_FLAGS=AlphaAllowGCE 

  gcloud compute networks create $K8S_NETWORK_NAME --subnet-mode auto
  gcloud compute firewall-rules create $K8S_FIREWALL_NAME --network $K8S_NETWORK_NAME --allow tcp:22,tcp:443,icmp
  gcloud compute networks list

  kops create cluster $K8S_CLUSTER_NAME \
  --zones $COMPUTE_ZONE \
  --master-zones $COMPUTE_ZONE \
  --node-count 3 \
  --project $GCP_PROJECT_ID \
  --yes \
  --vpc $K8S_NETWORK_NAME \
  --node-count=$K8S_WORKER_COUNT

  kops get cluster --state $GCP_DATA_STORE $K8S_CLUSTER_NAME 
  kops get instancegroup --state $GCP_DATA_STORE --name $K8S_CLUSTER_NAME
