### ISSUE TITLE
unknown flag: --subnets

### ISSUE THREAD

**Issue by mustafaakin** [kubernetes/kops#4623]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.8.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

not yet

3. What cloud provider are you using?

AWS 

4. What commands did you run?  What is the simplest way to reproduce this issue?

kops create cluster --zones=us-east-1b --name=${CLUSTER_NAME} --subnets=${SUBNET_IDS}

5. What happened after the commands executed?

unknown flag: --subnets

6. What did you expect to happen?

Use my subnet, not create a new one

**Comment by huang-jy** [comment]
`kops create` does not have a --subnets flag, but it does have a `--zones` flag.

**Comment by huang-jy** [comment]
Duplicate of https://github.com/kubernetes/kops/issues/4358

**Comment by mustafaakin** [comment]
I want specific subnets, it turns out the documentation is from master and using the latest alpha works fine by existing subnets .
