### ISSUE TITLE
Segmentation fault while creating new instance group in an existing cluster

### ISSUE THREAD

**Issue by ajayaa** [kubernetes/kops#4663]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
`Version 1.8.1`
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
`Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
3. What cloud provider are you using?
`AWS`
4. What commands did you run?  What is the simplest way to reproduce this issue?
`kops create ig public-node --role node --subnet public-us-east-1a.kube.qubole.net`
5. What happened after the commands executed?
`Using cluster from kubectl context: XXX
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1e0 pc=0x31bd43f]
goroutine 1 [running]:
k8s.io/kops/pkg/apis/kops.(*InstanceGroup).AddInstanceGroupNodeLabel(...)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/pkg/apis/kops/instancegroup.go:172
main.RunCreateInstanceGroup(0xc420b3b980, 0xc420322d80, 0xc420b7e910, 0x1, 0x5, 0x57389e0, 0xc42000e018, 0xc420b7e640, 0x0, 0x0)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/create_ig.go:160 +0x2ff
main.NewCmdCreateInstanceGroup.func1(0xc420322d80, 0xc420b7e910, 0x1, 0x5)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/create_ig.go:87 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc420322d80, 0xc420b7e780, 0x5, 0x5, 0xc420322d80, 0xc420b7e780)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x234
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5930a00, 0x3507900, 0x0, 0x0)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x5930a00, 0x5964c58, 0x0)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/root.go:95 +0x91
main.main()
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/main.go:25 +0x20`

6. What did you expect to happen?
`A successful creation of a new ig or a nice error message`
7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
`https://gist.github.com/anonymous/061fbc51de3ded3fa7ead868a41dbaf3`
8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
`I0312 19:32:15.104855   65724 aws_utils.go:39] Querying EC2 for all valid regions
I0312 19:32:16.727312   65724 aws_cloud.go:956] Querying EC2 for all valid zones in region "us-east-1"
I0312 19:32:16.727449   65724 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1e0 pc=0x31bd43f]

goroutine 1 [running]:
k8s.io/kops/pkg/apis/kops.(*InstanceGroup).AddInstanceGroupNodeLabel(...)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/pkg/apis/kops/instancegroup.go:172
main.RunCreateInstanceGroup(0xc420b92040, 0xc4203578c0, 0xc420b8c840, 0x1, 0x6, 0x57389e0, 0xc42000e018, 0xc4209b0000, 0x0, 0x0)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/create_ig.go:160 +0x2ff
main.NewCmdCreateInstanceGroup.func1(0xc4203578c0, 0xc420b8c840, 0x1, 0x6)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/create_ig.go:87 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203578c0, 0xc420b8c780, 0x6, 0x6, 0xc4203578c0, 0xc420b8c780)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x234
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5930a00, 0x3507900, 0x0, 0x0)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x5930a00, 0x5964c58, 0x0)
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/root.go:95 +0x91
main.main()
        /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/main.go:25 +0x20`
9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by peterkuiper** [comment]
I'm having the same issue. When using kops `Version 1.9.0-alpha.1 (git-d41d56a70)` I'm getting a few error messages which are not really helpful at all:

```
error assigning default machine type for nodes: error finding default machine type: cannot find subnet "eu-central-1b" (declared in instance group "nodes-eu-central-1b", not found in cluster)
```

**Comment by peterkuiper** [comment]
@ajayaa Here is how I fixed it:

```
kops edit cluster <name>
```

Add your subnet, ie:

```
- cidr: 172.20.64.0/19
   name: eu-central-1b
   type: Public
   zone: eu-central-1b
```

Check your changes:

```
kops update cluster <name>
```

If all seems ok, apply:

```
kops update cluster <name> --yes
```

Now you should be able to add your `instancegroup`

```
kops create ig nodes-eu-central-1b --subnet eu-central-1b
```

Again, check your changes:

```
kops update cluster <name>
```
and apply if all is good:

```
kops update cluster <name> --yes
```

HTH

**Comment by chrislovecnm** [comment]
@petermd would this be a good section to put in the instance group documentation?  I like it!
