### ISSUE TITLE
Cluster validation incorrectly passes when only 2 masters are ready

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#4665]
Kops version: 1.9.0-alpha.1 (git-f799036a3)
K8s version: any
Provider: AWS

Command:
`kops rolling-update cluster --yes`

It drained & terminated the first master, but didn't notice that all 3 never became ready when the validation occurred, moved on to the 2nd master (I stopped it before it took the instance down)

**Comment by chrislovecnm** [comment]
Can we get a -v 10?

**Comment by huang-jy** [comment]
Also are the boxes Spot Instances?

**Comment by blakebarnett** [comment]
No, masters are m4.large, nodes are m4.2xlarge 

I think this issue is resolved with the updated API dependencies. If we don't have an issue tracking test coverage for this, we can just use this one.

**Comment by blakebarnett** [comment]
I thought this was resolved, but I just saw it say the cluster was valid while a node was in "NotReady" state.  Thankfully it was the last one in our upgrade, and no other issues were seen during the rolling-update probably due to the long default wait interval.

**Comment by justinsb** [comment]
@blakebarnett I don't suppose you have a log?  Trying to figure out whether we have a bug, or whether the node was marked as Ready, then later went NotReady.

**Comment by blakebarnett** [comment]
I don't have a log sorry.  The 2 cases I saw: 
* Only 2 masters in Ready state (3rd wasn't even listed yet) and validation passed.  
* Node in NotReady state and validation passed.

**Comment by huang-jy** [comment]
Assuming your configuration hasn't changed yet, could you copy paste what it says at the top where the table is, when you use `kops validate cluster` (it has a list of all the IGs, the max, min and zones)?

**Comment by blakebarnett** [comment]
That's the thing... `kops validation cluster` works fine.  It's the validation that happens during `kops rolling-update cluster` that fails.

**Comment by huang-jy** [comment]
If validation works, but rolling-update doesn't, then possibly your update is bad, or you've set a min/max to different values. So if, for example you have min of 2 and max of 5, and have 5 nodes in that group up, and kops respins 1, it'll still pass validation, even if that new one is showing as bad on the node list, since 4 (4 good, 1 bad) is still > 2.

So what is your configuration on your masters ig? And if you have a HA configuration (i.e. several master igs for different AZs), please also give those -- or just copy-paste the top part of the `kops validate` :)

**Comment by blakebarnett** [comment]
Nope, this is not the case and never happened before.  The masters should ALWAYS validate that there are 3/3 no matter what anyway.

**Comment by huang-jy** [comment]
Only if you have a configuration that has a total of 3 min specified.

**Comment by blakebarnett** [comment]
@huang-jy yes, I do.  I understand very well how it works.

**Comment by huang-jy** [comment]
@blakebarnett assuming you aren't going to volunteer the information, then I cannot for certain rule out that as being a contributing factor to your issue, that's all I'm saying.
