### ISSUE TITLE
Some nodes fail to register themselves into the cluster

### ISSUE THREAD

**Issue by cw75** [kubernetes/kops#4673]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

1.8.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

client: 1.9.2
server: 1.8.7

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

We tried to add 66 ec2 nodes to our cluster.

5. What happened after the commands executed?

As we add more ec2 nodes to our cluster, only 63 nodes get registered into the cluster (but all 66 nodes have successfully been created and have status "running" from the aws console). The other nodes keep trying to connect to the master but fail. We wanted to have a cluster of 66 nodes, but 3 nodes always fail to register.

6. What did you expect to happen?

We expect all 66 nodes to register.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-03-13T17:53:12Z
  name: kvs.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://1-tiered-storage-state-store/kvs.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.7
  masterPublicName: api.kvs.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-13T18:11:18Z
  labels:
    kops.k8s.io/cluster: kvs.k8s.local
  name: benchmark-instances
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: r4.16xlarge
  maxSize: 50
  minSize: 50
  nodeLabels:
    role: benchmark
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-13T17:53:12Z
  labels:
    kops.k8s.io/cluster: kvs.k8s.local
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-13T18:11:16Z
  labels:
    kops.k8s.io/cluster: kvs.k8s.local
  name: memory-instances
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: r4.2xlarge
  maxSize: 10
  minSize: 10
  nodeLabels:
    role: memory
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-13T17:53:19Z
  labels:
    kops.k8s.io/cluster: kvs.k8s.local
  name: misc-instances
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: m4.4xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    role: general
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-13T18:01:36Z
  labels:
    kops.k8s.io/cluster: kvs.k8s.local
  name: proxy-instances
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: r4.16xlarge
  maxSize: 5
  minSize: 5
  nodeLabels:
    role: proxy
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-east-1a

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by chrislovecnm** [comment]
Logs from the master api-server?  Also logs from kubelet on the nodes?

**Comment by cw75** [comment]
Hi @chrislovecnm, we believe we found the reason why it was stuck at 64 nodes. Seems like we have a connection limit enforced here: https://github.com/kubernetes/kops/blob/88984d4b477dbb59e124f0626e1cc23d9b5b0aef/protokube/pkg/gossip/mesh/gossip.go (line 45). Is there a way to increase this limit? Thanks!

**Comment by chrislovecnm** [comment]
Can you run with dns? 

@justinsb I assume you put in the limit. What was your rational?

**Comment by cw75** [comment]
Thanks @chrislovecnm for the advice. Since we are fairly new to kops, could you please tell us a bit more detail? Is there a config file that we can change from whatever we have previously to dns? Actually I thought we were using dns already... Thanks again!

**Comment by jubel-han** [comment]
Here you go:
https://github.com/kubernetes/kops/blob/944632f2e6081e66f9db0970d00c32e85f1fb07f/upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template#L127-L130

https://github.com/kubernetes/kops/blob/2b95485b89dbb784af469f1bf7351aecae378e9d/tests/integration/update_cluster/lifecycle_phases/in-v1alpha2.yaml#L25-L26
