### ISSUE TITLE
Kops doesn't export api-load-balancer alias to ~/.kube/config

### ISSUE THREAD

**Issue by shai-px** [kubernetes/kops#4675]
Kops Version: Version 1.9.0-alpha.1 (git-f799036a3)
Kubernetes Version: v1.9.3
Provider: AWS
Command ran using Terraform: 
kops create cluster \
--channel=alpha \
--api-loadbalancer-type=internal \
--node-count= 3 \
--zones=${var.availability_zones} \
--master-zones=${var.availability_zones} \
--node-size=${var.node_size} \
--master-size=${var.master_size} \
--topology=private \
--encrypt-etcd-storage \
--networking=canal \
--dns=private \
--dns-zone=${module.vpc_data.hosted_zone_id} \
--kubernetes-version=${local.kubernetes_version} \
--image=${local.kubernetes_image} \
--ssh-public-key=${var.public_key_path} \
--bastion=${var.create_bastion} \
--name=${var.env_name}.${var.realm_domain} \
--vpc=${module.vpc_data.vpc_id} \
--subnets=${comma seperateds private-subnets} \
--utility-subnets=${comma seperated db-subnets} \
--target=terraform \
--out=${var.kops_output_dir}

Expected behavior: 
The command does create a Kops cluster with the internal load balancer. 
An alias gets created in route 53 for api.{cluster-name} -> internal-api-x-x-x.us-east-1.elb.amazonaws.com

We are expecting it to export the alias (which is https://api.{var.name}) 

However, what gets exported to ~/.kube/config under clusters/cluster/server is incorrect.
 
Instead, it exports the actual server (which is internal-api-x-x-x.us-east-1.elb.amazonaws.com)
In order to then access the API, we have to replace the actual server with its alias (https://api.{cluster-name}, every time we update the cluster. 

That seems like undesired behavior

Thanks!

**Comment by polarbizzle** [comment]
This PR https://github.com/kubernetes/kops/pull/4683 addresses this issue
