### ISSUE TITLE
Feature Request: Adjust  logging level for k8s service

### ISSUE THREAD

**Issue by caraboides** [kubernetes/kops#4684]
1. Describe IN DETAIL the feature/behavior/change you would like to see.
In the Cluster.spec in the state-bucket i see values like  kubeAPIServer.logLevel=2
During a kops edit i try to set this value to 0, when i try to save i got: 
```
# Found fields that are not recognized
# ...
#     kubeAPIServer:
#       authorizationMode: RBAC
# +     logLevel: 0
#
```
2. Feel free to provide a design supporting your feature request.
I want to change the value for: kubeAPIServer, kubeControllerManager, kubeProxy, kubeScheduler,kubelet and masterKubelet.

**Comment by jurgenweber** [comment]
```
  LaunchConfiguration/nodes-mem.luke.kubernetes.hipagesgroup.com.au
  	UserData
  	                    	...
  	                    	    hostnameOverride: '@aws'
  	                    	    image: gcr.io/google_containers/kube-proxy:v1.8.6
  	                    	+   logLevel: 1
  	                    	-   logLevel: 2
  	                    	  kubelet:
  	                    	    allowPrivileged: true
  	                    	...
  	                    	    hostnameOverride: '@aws'
  	                    	    kubeconfigPath: /var/lib/kubelet/kubeconfig
  	                    	+   logLevel: 1
  	                    	-   logLevel: 2
  	                    	    networkPluginName: cni
  	                    	    nonMasqueradeCIDR: 100.64.0.0/10
  	                    	...

```

going to logLevel 1 is accepted and seems to do something. :0

**Comment by Cryptophobia** [comment]
The only trick to set logLevel 0 is to use kops hooks that edit the manifest files before the kublet starts. Ideally kops should edit the manifest files and set --v=0. Not sure why this is not working right now...
