### ISSUE TITLE
kops update hangs on AWS request: elasticloadbalancing/ModifyLoadBalancerAttributes

### ISSUE THREAD

**Issue by blainehansen** [kubernetes/kops#4693]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

`Version 1.8.1 (git-94ef202)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?`

I've included the failure to connect to a server (even though my entire problem is that I can't create one) just in case it's relevant.

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

```sh
# I've provided a manifest below
kops create -f cluster.yaml
kops create secret --name dask-cluster.k8s.local sshpublickey admin -i ~/.ssh/id_rsa.pub
kops update cluster obfuscated-project-name-cluster.k8s.local --state s3://kops-state-store.obfuscated-domain-name.com --v 10 --yes
```

5. What happened after the commands executed?

The final output was this:
`I0316 17:55:34.982391   19991 request_logger.go:45] AWS request: elasticloadbalancing/ModifyLoadBalancerAttributes`

It then hung for about a half an hour. I assume that waiting for instances to be created takes a while, but it seems it wasn't even at that step. And previous attempts have hung for over two hours.

Here's a full log:
https://gist.github.com/blainehansen/0d71a39567d8acd2ae6d3cf7d805c1cd

6. What did you expect to happen?

For the script to continue to creating instances and waiting for them to boot.

7. Please provide your cluster manifest.

```
$ kops get --name obfuscated-project-name-cluster.k8s.local --state s3://kops-state-store.obfuscated-domain-name.com -oyaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-03-16T23:55:13Z
  name: obfuscated-project-name-cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-state-store.obfuscated-domain-name.com/obfuscated-project-name-cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.7
  masterPublicName: api.obfuscated-project-name-cluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-1a
    type: Public
    zone: us-west-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-16T23:55:14Z
  labels:
    kops.k8s.io/cluster: obfuscated-project-name-cluster.k8s.local
  name: master-us-west-1a
spec:
  image: ami-4e53462e
  machineType: t2.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-1a
  role: Master
  subnets:
  - us-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-16T23:55:14Z
  labels:
    kops.k8s.io/cluster: obfuscated-project-name-cluster.k8s.local
  name: nodes
spec:
  image: ami-4e53462e
  machineType: t2.large
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-1a
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.

Done above.

**Comment by blainehansen** [comment]
Also, if I run that same update command again after the first has already hung, it consistently hangs on this line:

`apply_cluster.go:884] Found hash "0b1f26208f8f6cc02468368706d0236670fec8a2" for "https://kubeupv2.s3.amazonaws.com/kops/1.8.1/images/protokube.tar.gz"`

**Comment by chrislovecnm** [comment]
@blainehansen can we get the logs and cli switches for

`kops update` with -v 10 and no `--yes`

and then the same with `--yes`

**Comment by blainehansen** [comment]
https://gist.github.com/blainehansen/e520c9708110d42bd4b39b6a9fc76d51

**Comment by blainehansen** [comment]
https://gist.github.com/blainehansen/01a8df3393c11c7518c37a1b0e5179f6
