### ISSUE TITLE
doc error on ingress aws controller

### ISSUE THREAD

**Issue by hsinhoyeh** [kubernetes/kops#4694]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

```
Version 1.8.1
```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?
```
AWS
```

4. What commands did you run?  What is the simplest way to reproduce this issue?

```
kubectl apply -f addons/kube-ingress-aws-controller/v1.0.0.yaml
```

5. What happened after the commands executed?
```
deployment "kube-ingress-aws-controller" created
The DaemonSet "skipper-ingress" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"component":"ingress"}: `selector` does not match template `labels`
```
I found a related issue [here](https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/112). So we may need to modify v1.0.0.yaml accordingly.

I also think maybe adding a doc to link to the original yams is somehow helpful. 

6. What did you expect to happen?

both resources(`kube-ingress-aws-controller` and `skipper-ingress`) should be created.

**Comment by jhohertz** [comment]
I ran into this as well. I tried changing this:
```
spec:
  selector:
    matchLabels:
      application: skipper-ingress
```
to
```
spec:
  selector:
    matchLabels:
      component: ingress
```

Which:
* let resource get created
* is more in-line with the upstream docs here: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/skipper.yaml#L11
* didn't completely solve the issue, as the container still failed to launch

So not sure this was correct in the end.

**Comment by hsinhoyeh** [comment]
@jhohertz changing `matchlabels` did help me to resolve my issue.
Do you mind to give us more details on the issue you have now?

**Comment by jhohertz** [comment]
Sure, just resetting my test cluster and will add details here.

**Comment by Ramlaar** [comment]
@jhohertz Had the same issue that you reported. After having added the below ClusterRole and ClusterRoleBinding, my issues were gone:

`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: ingress-controler
rules:
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - patch
  - watch
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  - ingresses
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-controller
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
- kind: ServiceAccount
  name: default
  namespace: default`
