### ISSUE TITLE
goimports must be on PATH

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#4696]
Otherwise `make goimports` fails.

Workaround:

```
export PATH=$GOPATH/bin:$PATH
go get golang.org/x/tools/cmd/goimports
make goimports
```

Not sure if we want to vendor goimports - probably not, maybe bazel can help us here.

**Comment by chrislovecnm** [comment]
Tools like goimports and gofmt do not play well with bazel at this time. We can either vendor or install via sha.
