### ISSUE TITLE
etcd: volume IOPS cannot be specified for io1

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#4720]
It appears there is no way to specify the IOPS for an etcd volume of type io1.  We should mirror the configuration for InstanceGroup root volumes:

```
// If volume type is io1, then we need to specify the number of Iops.
	RootVolumeIops *int32 `json:"rootVolumeIops,omitempty"`
```

**Comment by chrislovecnm** [comment]
@rdrgmnzs you wanted this as well?

**Comment by rdrgmnzs** [comment]
Yeah, this would be great to have! I'm currently accomplishing this in a less than idea manner, so if we had it in Kops it would help me get rid of at least 1 external "hack" I currently do.

**Comment by justinsb** [comment]
This is super-important given the etcd-quorum-read stuff.  But at this stage I think we have to push it to 1.10 (for now).

The tricky bit is going to be applying the change to existing clusters.   I believe that can be done, but I'm not sure whether it's totally safe, can be done online etc.

**Comment by cnuber** [comment]
+1 on this.  I am having to make the disktype change after provisioning which is rather inconvenient and time consuming.

**Comment by tcolgate** [comment]
Also, it seems that, for AWS, this currently renders the volumeType option useless, since the AWS API seems to explicitly require IOPs in order to create the io1 volume at all:
`PersistentVolume: InvalidParameterCombination: The parameter iops must be specified for io1 volumes.`

**Comment by mikesplain** [comment]
I believe this is fixed in the above pr (https://github.com/kubernetes/kops/pull/4852).  If it's not, please re-open (trying to cleanup the milestone!)

/close
