### ISSUE TITLE
We should validate that name is not too long for IAM role

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#4729]
e.g. `masters.e2e-kops-aws-networking-kopeio-vxlan.test-cncf-aws.k8s.io' is > 64 characters, which is the limit

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-networking-kopeio-vxlan/1
> W0320 01:16:32.004] W0320 01:16:32.003432     471 executor.go:118] error running task "IAMRole/masters.e2e-kops-aws-networking-kopeio-vxlan.test-cncf-aws.k8s.io" (9m58s remaining to succeed): error getting role: ValidationError: 1 validation error detected: Value 'masters.e2e-kops-aws-networking-kopeio-vxlan.test-cncf-aws.k8s.io' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64

**Comment by chrislovecnm** [comment]
> e.g. `masters.e2e-kops-aws-networking-kopeio-vxlan.test-cncf-aws.k8s.io' is > 64 characters, which is the limit

Which limit?  IAM?
