### ISSUE TITLE
[RFC] Consider documenting when a `rolling-update` is needed when using TF

### ISSUE THREAD

**Issue by fgrehm** [kubernetes/kops#4740]
1. What `kops` version are you running? `1.8.1`

2. What Kubernetes version are you running?

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:06Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using? `aws`

4. What commands did you run?  What is the simplest way to reproduce this issue?

```sh
kops create cluster \
            --cloud aws \
            --encrypt-etcd-storage \
            --name=... \
            --state=s3://... \
            --node-count 2 \
            --node-size t2.medium \
            --master-size t2.large \
            --zones us-east-1a \
            --master-zones us-east-1a \
            --target=terraform \
            --out terraform/k8s-dev \
            --kubernetes-version=1.9.3
```

```sh
kops edit cluster ...
# Enable RBAC
kops update cluster --out=terraform/k8s-dev --target=terraform
```

```sh
terraform apply TF_OUTPUT
```

5. What happened after the commands executed and what did you expect to happen?

TF recreated the `data/aws_launch_configuration_master...` file, AWS settings got changed but RBAC did not get enabled until I ran a `kops rolling-update`

6. Anything else do we need to know?

I [asked on slack](https://kubernetes.slack.com/archives/C3QUFP0QM/p1521551692000164) about this and got an [answer](https://kubernetes.slack.com/archives/C3QUFP0QM/p1521552336000033?thread_ts=1521552042.000733&cid=C3QUFP0QM) saying that this was expected

----

My suggestion would be to document some of these scenarios when making changes and applying the TF configs are not enough to get the cluster into the desired state. Maybe adding a note to the Caveats section https://github.com/kubernetes/kops/blob/master/docs/terraform.md#caveats?

**Comment by mikesplain** [comment]
@fgrehm I think that's a great idea.  At minimum it could be documented there. I wonder if we can put up a message in the CLI when doing update cluster with the TF target.  

Either way, feel free to open up a PR against that TF doc if you're up to it! I think that's a great place to start on this!

**Comment by fgrehm** [comment]
> I wonder if we can put up a message in the CLI when doing update cluster with the TF target.

Yeah, that'd be great!

> Either way, feel free to open up a PR against that TF doc if you're up to it! I think that's a great place to start on this!

I'm up for that, can you think of other changes that would require a `rolling-update` that I should document while I'm at it? I'm kinda new to `kops` 😊

**Comment by mikesplain** [comment]
@fgrehm Great! Not that I can think of... TF doesn't roll over nodes so really anything that creates a new launch config, would require a rolling-update of the cluster.
