### ISSUE TITLE
how to find ca.crt for cluster

### ISSUE THREAD

**Issue by awardsolutionsuser** [kubernetes/kops#4741]
using kops Version 1.8.1 (git-94ef202)  ubuntu 16.04 client and server

I created a cluster on GCE with kops. It works correctly.  I want to add a new k8s user following the tutorial at https://docs.bitnami.com/kubernetes/how-to/configure-rbac-in-your-kubernetes-cluster/

In order to create new user certs, i need to have **cluster ca.crt and ca.key** (in step 2 in the howto). Can anyone tell me where I can find these files for the cluster which I just created with kops?  I thought I could find these files in my kops state storage (for me it is gs://rnmclusterkops-state) but I couldn't find them there.  I looked on the cluster controller and couldn't find them there. Any idea where to find the ca.crt and ca.key which were used when kops created the cluster?

thanks

**Comment by awardsolutionsuser** [comment]
I found the answer for kops on AWS here https://stackoverflow.com/questions/44820100/how-do-i-get-the-certificate-authority-certificate-key-from-a-cluster-created-by so i just translated it to GCP storage implementation.

**Comment by Lifang13** [comment]
how to find the client-certificate-data/client-key-data ?

**Comment by Zef1r089** [comment]
I have created a cluster on AWS using Kops v1.26.2 and I need to use ca.crt and ca.key to sign new users to join the cluster.

In older versions of Kops the ca.key and ca.cert were created automatically in the AWS S3 bucket, now we have a folder called "kubernetes-ca" with inside a keyset.yaml.

How to use this file to sign new certificates?

I need to use the command: openssl x509 -req -in file.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out file.crt -days 500

**Comment by ravindrareddysiriseni** [comment]
Hi All,
Am also facing the same issue with latest kops version 1.34. I don't see the issued/ca folders under PKI folder. Generally it will be there like xxxxxxx.crt file and keyset.yml. if they moved to some other location please let me know if any ideas.

**Comment by ravindrareddysiriseni** [comment]
Here i used the below command to generate the ca.crt and ca.key files.
openssl genrsa -out ca.key 2048
openssl genrsa -out ca.crt 2048

the files are generated.
