### ISSUE TITLE
Allow tainting nodes in an instance group

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#481]
PR #373 gave us the ability to label nodes from an instance group.  Thank you.

Could this be extended to do node taints as well?

**Comment by justinsb** [comment]
The way we're doing this relies on setting the --labels argument to kubelet.  The equivalent functionality for taints is (sadly) not yet available: https://github.com/kubernetes/kubernetes/pull/31647

We'd have to do this a different way until 1.5

**Comment by justinsb** [comment]
We will have a one-off taint for the master `dedicated=master:NoSchedule`, along with a label `kubernetes.io/role=master` (tentative for now, cf https://github.com/kubernetes/kubernetes/issues/33530 )

It's not easy to add more taints until that taint support lands.  Did you have a particular taint in mind, or was it just tainting the master?

**Comment by chrislovecnm** [comment]
What is the status on this?

**Comment by ajohnstone** [comment]
bump?

**Comment by felipejfc** [comment]
bump! any new here?

**Comment by robinpercy** [comment]
I'd like to tackle this now that kubernetes/kubernetes#31647 is in 1.6.0 alpha

**Comment by armandocerna** [comment]
I'd love to see this become possible.

**Comment by daniel-yavorovich** [comment]
I'm waiting this feature very much!
Thank you.

**Comment by chrislovecnm** [comment]
@justinsb @geojaz any status on this?

**Comment by geojaz** [comment]
I think @robinpercy took care of this in #1812. Closing!

**Comment by ctxrag** [comment]
Team, I am running 1.10 k8s clsuter. I need to taint an InstanceGroup so i was able to achieve it as below. but is there a way i push this change as kubectl apply -f taint-lb.yaml as apposed to directly tainting node?


kubectl taint nodes   100.34.3.1 kops.k8s.io/instancegroup=loadbalancer:NoSchedule
--

Can i achievel the same above in yaml file?
