### ISSUE TITLE
unable to create cluster with kops using existing subnet.

### ISSUE THREAD

**Issue by sandeeppaul-1994** [kubernetes/kops#4835]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
iam using kops Version 1.8.1 (git-94ef202) . 

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?

aws

4. What commands did you run?  What is the simplest way to reproduce this issue?
/usr/local/bin/kops create cluster --name=<cluster_name>  --vpc ${VPC_ID}   --node-count 1   --zones $ZONES   --node-size $NODE_SIZE   --master-size $MASTER_SIZE   --master-zones $ZONES  --network-cidr 10.0.0.0/16 --topology private   --networking weave   --dns private   --yes

5. What happened after the commands executed?

a: it created two subnets  a private subnet and a utility subnet keeping the default cidr range which again causes conflict with the existing cidr blocks.

6. What did you expect to happen?
i expect to give the cidr range or existing subnet id while running the creating cluster command.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyam
[cluster_manifest.txt](https://github.com/kubernetes/kops/files/1859025/cluster_manifest.txt)

l` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

i would like to make kops clusters more cluster , can you point me to the default configurations while creating cluster.

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by huang-jy** [comment]
If you want to use existing subnets (and/or VPCs) you need to edit the cluster config before you commit it to the cloud.

https://blenderfox.com/2018/01/05/guide-to-creating-a-kubernetes-cluster-in-existing-subnets-vpc-on-aws-with-kops/

**Comment by sandeeppaul-1994** [comment]
Is there any way we can dynamically assign available CIDR block even if its creating new subnets .

**Comment by huang-jy** [comment]
I haven't been able to (in fact, on more than one occasion, the CIDR it picked clashed with my currently created one.

**Comment by thejml** [comment]
I feel like we should be able to use a `--subnet-id` to just use an existing aws subnet.  I understand that we may need to make sure that we have routing rules in place for it to function properly, but it seems like this would be a valid use case in many scenarios.

**Comment by huang-jy** [comment]
@thejml looks like it's on the 1.10 milestone

**Comment by cdenneen** [comment]
I tried for this a while back and it was agreed that editing the cluster configuration was best solution (https://github.com/kubernetes/kops/issues/3754)
