### ISSUE TITLE
docker-healthcheck kills slow to reply docker daemons. Proposed change

### ISSUE THREAD

**Issue by gonfva** [kubernetes/kops#4836]
Under very heavy load, docker ps cannot respond quickly enough, so docker-healthcheck restarts the daemon.

I would suggest using docker ps -n 1 which should return faster but still check if docker daemon is running. See proposed changed

https://github.com/kubernetes/kops/commit/c3edc09d1b3e22647469f838249b7aaed4e8ef07

====

1. What `kops` version are you running? The command `kops version`, will display
 this information.

1.8.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

1.8.6

3. What cloud provider are you using?

AWS. 1 master + 3 nodes m4.large (no credits involved, so https://github.com/kubernetes/kops/issues/3876 not relevant)

4. What commands did you run?  What is the simplest way to reproduce this issue?

Launch a bunch of heavy load pods

5. What happened after the commands executed?

CPU spikes, docker daemon is forcebly restarted even if it is still running

6. What did you expect to happen?

CPU spike, docker daemon is not restarted if it is still healthy

**Comment by justinsb** [comment]
This is a little tricky - this feels like a good idea if we're killing docker by mistake, but on the other hand `docker ps` should be fast and we do have persistent problems (admittedly with older docker versions) when we don't have the health check.

A few alternatives:

* we can try a more lightweight command, as you suggest
* we could try to prioritize the docker daemon (`nice` level)
* we could check whether we still need the healthcheck at all in newer docker versions

**Comment by sergeylanzman** [comment]
You right in high load or CPU spike `docker ps` it's slow command.
Another lightweight less command for check docker daemon use `_ping` command
`echo -e "GET /_ping HTTP/1.0\r\n" | nc -U /var/run/docker.sock`
```
root@ip-1-1-1-10:/home/ubuntu# echo -e "GET /_ping HTTP/1.0\r\n" | nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Api-Version: 1.37
Docker-Experimental: false
Ostype: linux
Server: Docker/18.03.0-ce (linux)
Date: Tue, 03 Apr 2018 20:55:05 GMT
Content-Length: 2
Content-Type: text/plain; charset=utf-8
```
https://github.com/moby/moby/blob/f0b9eb8627b0bbf3cbd95edd78cc552cb3626520/api/server/router/system/system_routes.go#L27

**Comment by gonfva-bcl** [comment]
I deployed the change I had proposed initially, but I ended up facing a different issue (pleg not healthy), similar to one that can be found here
https://github.com/kubernetes/kubernetes/issues/45419
It seems even if docker-clusterhealth doesn't kill docker daemon, when docker is too slow to reply, there will be other issues.
I moved to Ubuntu 16.04 LTS images and so far the cluster seems more resilient.

**Comment by kumudt** [comment]
Same thing is happening for my kops 1.9.0 cluster running k8s 1.9.7
Some logs.
```
Apr 22 05:02:27 ip-10-10-10-172 systemdâ1ê: Starting Run docker-healthcheck once...
Apr 22 05:02:45 ip-10-10-10-172 docker-healthcheckâ7077ê: docker failed
Apr 22 05:02:45 ip-10-10-10-172 docker-healthcheckâ7077ê: Giving docker 30 seconds grace before restarting
Apr 22 05:03:30 ip-10-10-10-172 docker-healthcheckâ7077ê: docker still down; triggering docker restart
Apr 22 05:10:20 ip-10-10-10-172 docker-healthcheckâ7077ê: Waiting 60 seconds to give docker time to start
Apr 22 05:11:30 ip-10-10-10-172 docker-healthcheckâ7077ê: docker still failing
Apr 22 05:11:30 ip-10-10-10-172 systemdâ1ê: Started Run docker-healthcheck once.
```
For me this happened 2 - 3 times before the docker is healthy again. There was a downtime of about 10 minutes.
Is there any workaround for this.
I am using kops debian stretch 1.9 image with docker version 17.3.2

**Comment by gonfva** [comment]
Sorry, I missed the previous comments.
I can confirm that after changing the OS image to Ubuntu LTS we haven't had any issue. The problem seems to be related to docker ps not responding properly for some kernel versions. 
@danopia You could modify docker-healthcheck, but IMO, getting an alert is not enough if you can only watch it. 
@kumudt Upgrading the kernel (or in my case changing the image altogether) is the only workaround that I know.
The image I've been using for AWS is
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180306
(there may be others more updated)
I'm closing the issue since it is not quite a Kops problem anyway.

**Comment by tsuna** [comment]
Do you have any details on
> docker ps not responding properly for some kernel versions
I'm trying to determine whether that's the issue I'm running into but it's hard to tell without more information about the problem you referenced.

Thanks.

**Comment by gonfva** [comment]
Sorry, I remember reading something on a specific kernel version where something was fixed. But I've taken a look to my search activity and I couldn't find the reference.
