### ISSUE TITLE
Update `kube-ingress-aws-controller` addon documentation to facilitate functional load balancers

### ISSUE THREAD

**Issue by Jberlinsky** [kubernetes/kops#4838]
## Bug Report

1. What `kops` version are you running? The command `kops version`, will display
 this information.

`Version 1.9.0-alpha.3 (git-c707c82f6)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

`1.9.3` (N/A)

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

I followed the directions given in https://github.com/kubernetes/kops/blob/master/addons/kube-ingress-aws-controller/README.md regarding configuring my cluster and AWS environment for `kube-ingress-aws-controller`.

5. What happened after the commands executed?

`kube-ingress-aws-controller` exhibits the following issues:

- There is an IAM error when trying to add Kubernetes nodes to the created ALB target group. This error is due to a missing permission, `autoscaling:DescribeLoadBalancerTargetGroups`; and
- Once the missing permission is resolved, the nodes get added to the ALB target group successfully, but fail their health checks. The health check endpoints are reachable on the nodes themselves via `curl`. The health check failure is due to a request timeout, indicating a security group issue.

6. What did you expect to happen?

I expect the ALB to come up as expected, populated with healthy target hosts.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

N/A

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

N/A

9. Anything else do we need to know?

N/A

## Suggestion

I have updates to the `kube-ingress-aws-controller` addon docs ready to go. They include:

- Adding the missing IAM permission to `spec.additionalPolicies` in the cluster spec, and
- Adding the missing `awscli` command to configure egress from the ALB security group.

These documentation changes can be viewed here, in my fork of the repository:

- https://github.com/BarefootCoders/kops/commit/301b75674e5e8e79424705b30b43b8aab1c3a1c2
- https://github.com/BarefootCoders/kops/commit/72b1dd182572579cafadfc36a77a5b0546a86b2a

Pursuant to the [contribution guidelines](https://github.com/kubernetes/kops/blob/master/CONTRIBUTING.md), I am proposing that these documentation changes be merged into the `kops` repository. If this is approved, I will open a pull request.

Thanks folks!

**Comment by chrislovecnm** [comment]
thanks for asking! Please PR! 

I appreciate you being so formal, but we are all just helping out here as we can. Please just feel free to send in these kinds of PRs when you can. If it is something that is a huge change then you can ping the dev channel on slack, swing by our office hours, or file an issue.

**Comment by Jberlinsky** [comment]
You got it! Just wanted to make sure I followed the rules :)

PR is here: https://github.com/kubernetes/kops/pull/4843

**Comment by Jberlinsky** [comment]
@justinsb May I close this issue, now that the PR has been merged?

**Comment by jhohertz** [comment]
Just a note, that I found the new egress rule had to be removed in my testing, as the API rejected it as a duplicate rule. Not sure why my experience seems to differ here.

I still have issues getting any of the containers to work after addressing this and the issues raised in #4694 (I see the health check errors that prompted the egress change I had to take out, and what appears to be another IAM issue w/ the ingress controller)

**Comment by Jberlinsky** [comment]
@jhohertz Did you create the security group in the AWS console, or via the API? I noticed that when I created security groups via the console, it automatically created the `0.0.0.0/0` egress rule (and its IPv6 analogue).

**Comment by jhohertz** [comment]
I did it via the aws cli commands, using the variation in the upstream doc here (under "if you are not in the default VPC), but adding the egress line (then removing it when I saw the error)

https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/kops.md#security-group-for-ingress
