### ISSUE TITLE
Kubernetes cluster set up with AWS. 

### ISSUE THREAD

**Issue by umar-sik** [kubernetes/kops#4839]
Hey, 

I am trying to set up a kube cluster with AWS. I have bought a google domain so I created a subdomain (hosted zone) in AWS route 53. I set the NS name records in the google cloud console by creating the same zone over there as well. After I create my cluster with kops and run kops validate cluster, I get "Unable to connect to the server: dial tcp: lookup api.myfirstcluster.test.xxxx.io on 8.8.8.8:53: no such host".  Any suggestions? 

Also, when I see my amazon console, I can see my cluster nodes and master up and running in the zone I set.

**Comment by chrissnell** [comment]
Do a `dig subdomain.yourdomain.com ns` and verify that you see the proper NS records pointing to AWS.   Verify that you provided the correct subdomain in your `kops create cluster ...` command.   Also, follow the issue template that you saw when you created this issue and provide your manifests and logs.

**Comment by umar-sik** [comment]
Issue solved.
