### ISSUE TITLE
kops doesn't add VPC to private HostedZone in R53

### ISSUE THREAD

**Issue by mrichmon** [kubernetes/kops#485]
Scenario: Stand up kubernetes with kops with all machines in AWS.
1. Create private HostedZone in R53 that is only exposed to one VPC (managementVPC).
2. Launch a management VM in managementVPC.
3. Clone kops repo and build kops on management VM.
4. Run kops create allowing kops configured to create a new VPC (kopsVPC).
5. Run kops update to deploy kubernetes into kopsVPC.
6. Set up VPC peering between managementVPC and kopsVPC.

After these steps the R53 records were created and the kubernetes VMs are running in the kopsVPC. However, running kubectl with the kops generated configuration does not work on either the management VM or from the kops master or nodes.

The issue was traced to the HostedZone for kubernetes needed to be updated to serve the zone in the kopsVPC.

Suggested fix: Detect when the kubernetes HostedZone is private and automatically add the kopsVPC to the HostedZone if kops has created the kopsKPC.

**Comment by justinsb** [comment]
This should now work if you specify `--dns private` when creating the cluster.

More details in the comment here (this was probably a dup, sorry I missed it as such):
https://github.com/kubernetes/kops/issues/362#issuecomment-275893006

Please comment/reopen if not working as expected in kops 1.5.0 beta1 (or later)
