### ISSUE TITLE
volumeIops added to EBSVolume Find()

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#4855]
We need to output volumeIops in EBSVolume Find() - per https://github.com/kubernetes/kops/pull/4852#issuecomment-377829470

Note we don't necessarily want to implement changing the value in 1.9 - that feels like it needs more testing

**Comment by sergeylanzman** [comment]
@justinsb Maybe it's already done? https://github.com/kubernetes/kops/pull/4852/files#diff-28f2ed90f7519537a083ae228827cb16R105

**Comment by rajaneeshk1990** [comment]
Unsupported volume type 'iops' for volume creation
