### ISSUE TITLE
Estimated costs for smallest cluster on AWS & GCE?

### ISSUE THREAD

**Issue by Siilwyn** [kubernetes/kops#4867]
:wave: Hi there, I'm wondering what the monthly costs for a cluster of one master and two nodes would be on both available platforms using kops. (In EU west but I don't think there's a huge difference in pricing per region.)

Sorry about being a bit off-topic but I find the pricing pages of both providers hard to decipher and I'm new to kops so I'm also not sure what resources it will use. Besides that nobody on the K8 Slack channel seemed to know.

**Comment by chrislovecnm** [comment]
So you can use spot instances in aws for you nodes. Bit there are many many factors. I would cost out a cluster using the AWS calculator.

**Comment by chrislovecnm** [comment]
@arun-gupta can anyone on your team help?

**Comment by chrissnell** [comment]
How about this?

https://github.com/Bjorn248/terraform_cashier

**Comment by dalbhanj** [comment]
@chrislovecnm, please assign it to me

**Comment by dalbhanj** [comment]
Sorry about that. While I'm getting ready to enroll, here is the info on pricing

This is high level guidance on AWS pricing when you run Kubernetes cluster using kops. Please review https://aws.amazon.com/ec2/pricing/[AWS documentation] for more details

Sample pricing page is populated using http://calculator.s3.amazonaws.com/index.html[Simple Monthly Calculator]

- On-demand costs with one master (m3.medium), two nodes (t3.medium) in us-east-1 (~$6/day): https://calculator.s3.amazonaws.com/index.html#r=IAD&key=calc-2752C300-9A66-4457-B12B-4F5AF773F05F

You can lower your prices if you use https://aws.amazon.com/ec2/pricing/reserved-instances/[Reserved Instances]. To get an estimate of Reserved Instance costs, use calculator above and customize it for RI's

- One year Reserved Instance costs with all Upfront for the same configuration in us-east-1 (~1.2/day): https://calculator.s3.amazonaws.com/index.html#r=IAD&key=calc-9B721139-4727-46A1-B3E7-DA0326D480E1

**Comment by chrislovecnm** [comment]
@dalbhanj btw you need to be a k8s org member for us to assign issue to you.  Ping me if you have questions about membership, as it is actually pretty simple.  Thanks for helping out!

**Comment by Siilwyn** [comment]
Sorry about the late reply. :sweat_smile: 

Thank you for all your replies, much appreciated! <3
As this answers my question I think I can close this issue.

**Comment by dalbhanj** [comment]
Hi @chrislovecnm, looks like I'm a member now. LMK if you think sending PR on AWS costs might help for future audience
