### ISSUE TITLE
ssh public key assumption on Windows could be improved

### ISSUE THREAD

**Issue by jordansissel** [kubernetes/kops#4875]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.8.1 (git-94ef2027b)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

```
kops create cluster --name test.k8s.local --zones us-west-1a
```

5. What happened after the commands executed?

```
I0402 09:11:48.314647   29276 create_cluster.go:439] Inferred --cloud=aws from zone "us-west-1a"

error reading SSH key file "/.ssh/id_rsa.pub": open /.ssh/id_rsa.pub: The system cannot find the path specified.
```

* It appears that the $HOME env var is assumed to be present (It's not on any Windows system I've tested). 
* Additionally, I'm not sure it's common to keep one's ssh public key (on Windows) in ~/.ssh/id_rsa.pub.

In my case, I use PuTTY and Pageant for my ssh activity and do not store my ssh public key separately from the private key.

6. What did you expect to happen?

Possibly as Pageant for the public key source? Alternately, not assume $HOME is an env var.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

N/A

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

There's a workaround:

1) In Powershell, setting `$Env:HOME="C:\Users\whatever\` or setting this as an environment variable via the windows settings ui.
2) create ~\\.ssh\\id_rsa.pub with an ssh public key

Found while testing for https://github.com/kubernetes/kops/issues/3816

**Comment by chrislovecnm** [comment]
This is a duplicate ;) unable to find the other issue now.
