### ISSUE TITLE
We should support overlay2

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#4899]
Probably we should consider making it the default in 1.10 (if it's the default upstream)

cf https://github.com/kubernetes/kops/pull/4894 and discussion there

**Comment by tvi** [comment]
As I interpret website: https://docs.docker.com/storage/storagedriver/select-storage-driver/ recommends overlay2 to Stretch and newer? We run default Jessie.

**Comment by stephanlindauer** [comment]
any news/plan regarding overlay2 adoption?

**Comment by mikesplain** [comment]
/remove-lifecycle stale

This will likely be 1.11 since we haven't gotten enough stretch testing in for this release.

**Comment by justinsb** [comment]
We actually default to overlay2 on kubernetes 1.11 (and that will be in kops 1.10): 
 https://github.com/kubernetes/kops/blob/master/pkg/model/components/docker.go#L91-L97

But as @mikesplain said, we're delaying this till 1.11 in the hope of figuring out whether overlay2 is stable on jessie (and maybe making stretch or similar the default for 1.11)

**Comment by tsuna** [comment]
I'm curious: why is kops so far behind in terms of base image, Docker version, Kubernetes version?  2019 is almost here and out of the box we get k8s 1.10 / docker 17.03.2-ce (which is super obsolete and buggy) / an old Debian with an old kernel version, etc?

**Comment by ms4720** [comment]
> I'm curious: why is kops so far behind in terms of base image, Docker version, Kubernetes version? 2019 is almost here and out of the box we get k8s 1.10 / docker 17.03.2-ce (which is super obsolete and buggy) / an old Debian with an old kernel version, etc?

because it is a large complex project with a small volunteer staff that has too much to do and not enough time to do it in, just a guess.
