### ISSUE TITLE
Termination Protection for Kops clusters in AWS

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#490]
We have a use case to enable termination protection in AWS for components created with Kops. 
Primarily:
- EC2 Instances
- VPC
- ASG

We would like to have an ability to deploy a termination protected cluster. All (or as many as possible) components of the cluster should be created with termination protection on in AWS.

@justinsb what are your thoughts?
@chrislovecnm what about you?

**Comment by mrichmon** [comment]
Presumably this would be useful as some separate options:
* enable termination protection on my master nodes
* enable termination protection on my worker nodes

My thinking is that cluster size will be varied frequently based on workload. And the cluster should be able to recover loss of a few worker nodes.

**Comment by chrislovecnm** [comment]
@mrichmon exactly.  Also it is more that just the nodes, VPC, and the ASG.

**Comment by kris-nova** [comment]
So pending @mrichmon's use case (and ours as well @chrislovecnm) - I think the big decision that needs to be made here (other than this feature in general) is :

**Do we have term protection as a global flag affecting all components of the cluster?**

-or-

**Do we allow for component specific configuration, yes for this, no for that (IE: Master/Workers)**

**Comment by chrislovecnm** [comment]
In terms of doing upgrades or other General ops. It probably would make sense to break up masters vs nodes. @justinsb any opinion on this?

**Comment by kris-nova** [comment]
In the name of getting this feature through, and keeping it flexible I think we should move forward with node/master flags for term protection. @chrislovecnm can we get a priority on this - feel free to assign it to me and I can start banging it out.

**Comment by jmound** [comment]
I think EBS volume "Delete on termination" should be set to false by default. From what I see, it is currently set to true.

**Comment by kris-nova** [comment]
@jmound I think there are 2 issues here... #1 Termination protection.. and #2 Delete on termination EBS volumes

I think we might need to open up a second issue for #2 (although there might be one already)

**Comment by jmound** [comment]
* I agree that they're two different issues, I was trying to add the second here. I've opened up a separate issue here #1516

**Comment by leoskyrocker** [comment]
hmm can we reopen this?

**Comment by SCLogo** [comment]
it would be good if we could set mfa or password or something on kops side, so we could protect cluster and configs from accidental delete
