### ISSUE TITLE
Unable to create or update kops cluster

### ISSUE THREAD

**Issue by GaudamThiyagarajan** [kubernetes/kops#4955]
1. Version 1.8.1 (git-94ef202)

2. `kops create cluster --name=kubernetes.xxxxxx.xxx  --state=s3://kops-state-xxxxxxx --zones=ap-south-1a --node-count=2 --node-size=t2.micro --master-size=t2.micro --dns-zone=kubernetes.ideaboard.xyz`
```
I0410 09:33:31.281852    4077 create_cluster.go:439] Inferred --cloud=aws from zone "ap-south-1a"
I0410 09:33:31.282133    4077 create_cluster.go:971] Using SSH public key: /home/vagrant/.ssh/id_rsa.pub
I0410 09:33:33.158255    4077 subnets.go:184] Assigned CIDR 172.20.32.0/19 to subnet ap-south-1a
Previewing changes that will be made:
```

`
error doing DNS lookup for NS records for "kubernetes.xxxxxxxx.xxx": lookup kubernetes.ideaboard.xyz on 10.0.2.3:53: read udp 10.0.2.15:37721->10.0.2.3:53: i/o timeout`

**Comment by huang-jy** [comment]
Check your local DNS. I sometimes have this on my home pc which has a very crappy Sky Broadband connection.

Try setting your DNS to 8.8.8.8 (Google's one) and trying again.

**Comment by eranreshef** [comment]
@GaudamThiyagarajan still relevant?
