### ISSUE TITLE
Rethink docker-healthcheck.service ?

### ISSUE THREAD

**Issue by Cryptophobia** [kubernetes/kops#4969]
### FEATURE REQUEST 

1. Describe IN DETAIL the feature/behavior/change you would like to see.

Right now the docker-healthcheck service is terminating docker and creates uncertainty in other containers running on the system. Kops should not be affecting networking components by restarting docker daemon itself.

2. Feel free to provide a design supporting your feature request.

Symptoms of the problem can be found here: https://github.com/weaveworks/weave/issues/3275

1. What `kops` version are you running? The command `kops version`, will display
 this information.
```
$ kops version
Version 1.8.1 (git-94ef202)
```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?
```
AWS
```

6. What did you expect to happen?
Kops should not be affecting networking components by restarting docker daemon itself.

9. Anything else do we need to know?
Symptoms of the problem can be found here: https://github.com/weaveworks/weave/issues/3275

**Comment by olemarkus** [comment]
Is anyone still seeing this issue? The health check has changed a number of times since this issue was originally created.

**Comment by Cryptophobia** [comment]
We haven't had much errors from the healthcheck service in kops in a while. I'm going to close this as I am the one who opened this issue.
