### ISSUE TITLE
Use Docker Images from private repository 

### ISSUE THREAD

**Issue by bhargavpss** [kubernetes/kops#4970]
We are trying to create a k8s cluster using `kops` on AWS without any internet access for security purposes. We are now primarily looking at customizing the cluster to use the docker images from a private repository instead of `gcr.io` or `kope` repo in docker hub. 

We were wondering if the images from `gcr.io` are hard-coded in the `nodeup` binary? We are confused whether they are configurable from `protokube` or by some other means without having to modify the `nodeup` binary. It seems like the `/etc/kubernetes/manifests` folder is being generated when the `protokube` tar package is opened. We are not really sure about anything.

Can somebody tell us where we can configure the images that are needed to set up the cluster?

**Comment by StanForever** [comment]
Is there any way found to approach this scenario?
