### ISSUE TITLE
Handling Spot Instance Interruption Notices

### ISSUE THREAD

**Issue by Mikulas** [kubernetes/kops#4978]
/kind feature

1. Describe IN DETAIL the feature/behavior/change you would like to see.

Whenever AWS schedules a Spot Instance for termination, it updates the [instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) and gives instance a 2 minute graceful period.

> […] Spot Instance interruption notices, which provide a two-minute warning before Amazon EC2 must interrupt your Spot Instance.
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#spot-instance-termination-notices

I propose handling the notification by cordoning the node and making it unschedulable.

2. Feel free to provide a design supporting your feature request.

Per AWS advice, the notification should be checked quite often:

> We recommend that you check for these warnings every 5 seconds. 
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#spot-instance-termination-notices

The instance metadata is available from the respective instance only, meaning the monitoring would need to run as a daemon on each node. I'm not sure if the metadata IP (169.254.169.254) would always resolve properly inside containers. Also, for such a lightweight service, it seems unnecessary to introduce a new deployment.

I'm happy to contribute this change if it's deemed valuable, but I'm not sure on what layer it would be best.

**Comment by Globegitter** [comment]
I found this project today https://github.com/kubernetes/charts/tree/master/incubator/kube-spot-termination-notice-handler which should do exactly what you are asking for.

**Comment by Mikulas** [comment]
Thanks. Alright given that it's already implemented as a daemonset in the https://github.com/mumoshu/kube-spot-termination-notice-handler you linked, I'll close this. It would be nicer to handle this in a lower level process, but the resource usage should be minimal anyway.
