### ISSUE TITLE
cannot resolve external name services after upgrading kubernetes from 1.8.5 to 1.9.6

### ISSUE THREAD

**Issue by rajatjindal** [kubernetes/kops#4986]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.9.0 (git-cccd71e67)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

v1.9.6

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
Upgrade kubernetes from version 1.8.5 to 1.9.6

5. What happened after the commands executed?

I could not resolve external name services anymore 

6. What did you expect to happen?

Continue to be able to resolve external name services 

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

**Comment by rajatjindal** [comment]
Once i created the configmap https://gist.github.com/rajatjindal/42ef389787bc4fad1f9f506f6d0c51c0 for kube-dns, it started to work. 

But I am guessing more people will run into this issue after upgrading their clusters. and I am not sure what the root cause is, therefore reported the issue

**Comment by lheinlen** [comment]
I ran into the same issue and followed the same steps to resolve it.

**Comment by jjo** [comment]
Ditto here (upgraded 1.8.9 -> 1.9.5 using kops-1.9.0), some `externalName` service was failing to resolve for _internal_ aws DNS RR entries, after adding the `kube-dns` configMap pointing to our internal aws DNS service, it got fixed.

**Comment by FrederikNS** [comment]
The issue seems to be due to kube-dns version 1.14.9, see kubernetes/dns#224 and #4851.

I just upgraded our kube-dns to 1.14.10 using the same method mentioned in #3512, which fixed our issues with externalName.
