### ISSUE TITLE
DO: Delete cluster delete NS recrods

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes/kops#4995]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

`Version 1.9.0 (git-cccd71e67)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Not relevant

3. What cloud provider are you using?

DigitalOcean

4. What commands did you run?  What is the simplest way to reproduce this issue?

Follow the DO tutorial: https://github.com/kubernetes/kops/blob/6a3d9dc46f64d062dad6d5f2698ab686e64845d5/docs/tutorial/digitalocean.md and delete the cluster like `kops delete cluster foo.bar.com --yes`

5. What happened after the commands executed?

`kops` deleted the cluster but also all the NS record for `foo.bar.com`, so I manually need to add them again.

6. What did you expect to happen?

`kops` should clean out all the DNS records expect the NS record.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

Will do later, if relevant.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

Will do later, if relevant.

9. Anything else do we need to know?

cc @andrewsykim

**Comment by andrewsykim** [comment]
@klausenbusk the NS records shouldn't be deleted unless you've configured the NS record to contain your cluster name which I'm guessing you did in this case. It shouldn't be if you use the default NS servers created when you created your domain. Updating kops to ignore NS records for subdomains seems fine to me though.

**Comment by klausenbusk** [comment]
> @klausenbusk the NS records shouldn't be deleted unless you've configured NS records for a subdomain which matches your cluster name which I'm guessing you did in this case

Correct, I have delegated a subdomain of a Cloudflare managed domain to DigitalOcean.

**Comment by andrewsykim** [comment]
Noted, I'll open a PR soon that will ignore records of type NS to avoid this case
