### ISSUE TITLE
DO: Update machine type

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes/kops#4996]
DigitalOcean did announce new droplet plans some time ago (https://blog.digitalocean.com/new-droplet-plans/), we should update the code to use the new droplet plans:
https://github.com/kubernetes/kops/blob/7a2ff89d77a77667c556663db05557f6ada026cc/upup/pkg/fi/cloudup/populate_instancegroup_spec.go#L36
https://github.com/kubernetes/kops/blob/7a2ff89d77a77667c556663db05557f6ada026cc/upup/pkg/fi/cloudup/populate_instancegroup_spec.go#L43

The old droplet type is supported until `July 1st, 2018` according to: https://developers.digitalocean.com/documentation/changelog/api-v2/new-size-slugs-for-droplet-plan-changes/ which also list all the new slug.

I propose that we use `s-1vcpu-2gb` for masters and `s-2vcpu-4gb` for workers.

cc @andrewsykim

**Comment by andrewsykim** [comment]
Ended up using `s-2vcpu-2gb` I think at the price point it's worth having that extra vCPU ;)
