### ISSUE TITLE
Reduce default ETCD volume size and/or make it easy configurable

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes/kops#4997]
1. Describe IN DETAIL the feature/behavior/change you would like to see.

The default ETCD volume size at the moment is 20GB: https://github.com/kubernetes/kops/blob/dc4a1a35b627f699a1c515790950c117919b84ca/pkg/model/master_volumes.go#L38
Which I think is way overkill for most clusters and a waste of money (DO example: 3 masters * 20GB disk * 2 * 0,1 = 12$/month). Lets change it to something more reasonable, 5GB maybe? and make it easily configurable without changing the config files by hand.

2. Feel free to provide a design supporting your feature request.

Lets add a `kops create cluster` parameter to control `DefaultEtcdVolumeSize` instead of hardcoding it.

cc @andrewsykim

**Comment by ValeryNo** [comment]
Agreed. After 5 months our etcd volumes are <500mb

**Comment by mohammedali-kadri** [comment]
any update on this guys, ,or is there any easy solution to this.

**Comment by lpf190** [comment]
we also need this function

**Comment by mikesplain** [comment]
Hi all, this is actually already implemented, though not documented (which I've done in #5692).  Hope this helps!
