### ISSUE TITLE
DO: Drop hostname override

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes/kops#4998]
Right now according to the code, we override the hostname on DO with the private ip:
https://github.com/kubernetes/kops/blob/7b601e60d41c0d589d592af3407d2b7a96c711e7/upup/pkg/fi/nodeup/command.go#L364-L377

I assume it wasdone, as the hostname isn't resolvable? The KubeletPreferredAddressTypes was changed ~ 1 year ago, so apiserver -> node traffic should work nevertheless. https://github.com/kubernetes/kops/pull/1561

cc @andrewsykim

**Comment by klausenbusk** [comment]
Hmm, the change was done recently https://github.com/kubernetes/kops/pull/4880 .. Maybe I'm missing something?

**Comment by andrewsykim** [comment]
@klausenbusk The hostname overrides are also used because the droplets that run kubernetes nodes are assigned the same name and so by default, they all try to register with the apiserver with the same name since kubelet uses hostname as the node name by default.

**Comment by klausenbusk** [comment]
> @klausenbusk The hostname overrides are also used because the droplets that run kubernetes nodes are assigned the same name and so by default

Oh, hmm.. If you for whatever reason need to SSH to a (or multiple) node for debugging purpose you gonna get confused. Wouldn't it be more ideal to numbering them?

**Comment by andrewsykim** [comment]
Yeah that's a good point which was why originally I was thinking about naming droplets by their public IPs instead so for SSHing purposes you wouldn't need to map private IPS back to droplet's public IPs. However, this is also consistent with the way kops assigns names for AWS/GCP (naming nodes after their private IPs) so figured I'd keep things consistent. fwiw, if you run `kubectl get no -o wide` you can easily map droplet names (private IP) to public IPs for easier ssh access. Having said that, if it makes more sense to name droplets by public IPs I'm happy to make that transition :)

**Comment by klausenbusk** [comment]
> However, this is also consistent with the way kops assigns names for AWS/GCP (naming nodes after their private IPs) so figured I'd keep things consistent. fwiw, if you run kubectl get no -o wide you can easily map droplet names (private IP) to public IPs for easier ssh access.

Naming them after their private ip sounds fine to me, although I generally find it easier to track servers after a meaningful hostname (`k8s-worker-N`) instead of similar-looking IP addresses.

**Comment by andrewsykim** [comment]
Yeah that's a fair point, I avoided unique names for droplets since in the future I'd like to experiment with artificial autoscaling groups on droplets using CRDs and in the implementation I didn't want to worry about what names to give droplets 😆
