### ISSUE TITLE
DO: Setup cloud firewall

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes/kops#4999]
1. Describe IN DETAIL the feature/behavior/change you would like to see.

When creating a cluster on DO, we should setup a restricted [cloud firewall](https://www.digitalocean.com/products/cloud-firewalls/).

2. Feel free to provide a design supporting your feature request.

https://github.com/poseidon/typhoon/blob/ef18f19ec4f844689566561cc8f38edc21afed32/digital-ocean/container-linux/kubernetes/network.tf is worht a look, for inspiration.

cc @andrewsykim

**Comment by andrewsykim** [comment]
I think this should be handled by the DO CCM, just a matter of doing the work at this point :)
