### ISSUE TITLE
Deploying and Managing EKS clusters

### ISSUE THREAD

**Issue by saptak** [kubernetes/kops#5001]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.9.0
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
v1.9.6
3. What cloud provider are you using?
AWS
4. What commands did you run?  What is the simplest way to reproduce this issue?
NA
5. What happened after the commands executed?
NA
6. What did you expect to happen?
NA
7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
NA
8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
NA
9. Anything else do we need to know?
NA

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.
Are there any plans to support deploying and managing EKS clusters using kops?

2. Feel free to provide a design supporting your feature request.

**Comment by xrl** [comment]
Kops is for managing/operating kubernetes clusters. EKS is also for managing/operating kubernetes cluster. EKS does all the master management and authorization, it's a more "managed" service than Kops.

What benefit would you have for using Kops with EKS?

**Comment by bhack** [comment]
Also there are already other tools for eks like https://eksctl.io/

**Comment by bhack** [comment]
Also we already support Terraform config generation. I don't know if something could be done with https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html.

**Comment by faheem-cliqz** [comment]
It would be nice to have eksctl like functionality in kops i.e. to start an eks cluster, can be done through terraform. Also would be nice to support spawning instancegroups directly from kops and connect them back to eks rather than rely on cloudformation templates.

**Comment by cjbottaro** [comment]
I went from EKS to kops. The decision was originally because EKS is not available in all the regions we need. After making the change, I'm glad we did.

There were two pain points that I had to engineer solutions for in EKS that kops gives me for free:
1. instancegroups with tainting/labeling as nodes come online
1. Rotating the cluster (`kops rolling-update cluster`).

After a quick look at `eksctl`, it doesn't seem to be able to do either of those things.

It would be nice to use kops _just for the instancegroup feature_ with an existing EKS control plane.

**Comment by jeffmhastings** [comment]
I was able to "roll" an EKS instance group with cloudformation by tainting all the nodes and  adding a 3 minute wait between terminating nodes, but this is clunky and not at all reliable. The kops rolling update functionality is vastly superior, and is the biggest thing lacking from EKS.

I really love the managed control plane, but I do not like the networking, authentication, and node management.

Would be nice to have kops manage node groups, but even that doesn't fix what's lacking in EKS.

**Comment by roeera** [comment]
I would take kops with its functionality, and add another option to create EKS cluster, while kops could add more options related to EKS maintenance, like rolling update, add node groups and modify cluster... the problem with eksctl, that It mostly a raising up tool, which used only to create / destroy a EKS cluster. but it's not a management tool. 
Another problem is that eksctl creating a cluster using cloudformation which is horrible to maintain, so I think that kops core would be great to be used if it could be work with EKS also !

**Comment by mazzy89** [comment]
Any updates in this?
