### ISSUE TITLE
Issue configuring insecure registry access with kops

### ISSUE THREAD

**Issue by julienla** [kubernetes/kops#5011]
Hi,

1. What `kops` version are you running?
1.8.1

2. What Kubernetes version are you running?
1.10.0

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
I created an external plain HTTP docker registry following the procedure in this link:
[https://docs.docker.com/registry/deploying/#run-a-local-registry](https://docs.docker.com/registry/deploying/#run-a-local-registry)
I then create a cluster using kops and add the following lines in the cluster spec manifest:
`docker:`
`    insecureRegistry: <hostnameofregistry>`
`    logDriver: ""`

5. What happened after the commands executed?
Cluster is created but when trying to docker push to the insecure registry, it fails

6. What did you expect to happen?
Being able to push or pull images from insecure registry without having to add any configuration on the master or nodes

I also tried using hooks to give access to the insecure registry to the master and nodes (based on the following procedure [https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry](https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry)). I added the following hook to the cluster spec manifest:
`hooks:`
`  - execContainer:`
`      command:`
`      - sh`
`      - -c`
`      - echo 35.155.193.162 <hostnameofregistry> >> /rootfs/etc/hosts && echo { '"insecure-registries":["<hostnameofregistry>:5000"] } >> /rootfs/etc/docker/daemon.json && /usr/bin/systemctl daemon-reload && /usr/bin/systemctl restart docker.service`
`      image: busybox`

That hook does modify /etc/hosts and creates /etc/docker/daemon.json on the master and nodes but I still need to manually do the daemon reload and restart docker for the master and nodes to have access to the insecure registry.

I'm relatively new to Docker and Kubernetes in general so not sure what I'm missing or doing wrong.
Any help or comment would help.

Thanks

**Comment by stevefaro** [comment]
I'm having the same issue.

**Comment by shruthibhaskar** [comment]
i am facing the same issue.

How do i add --insecure-registry property for my cluster master and node automatically without manual intervention?
also how to restart docker in there?
