### ISSUE TITLE
 kops toolbox template - produces 'empty' clusterName in the output file

### ISSUE THREAD

**Issue by lambertpan** [kubernetes/kops#5015]
1. What `kops` version are you running?
    1.8.1

2. What Kubernetes version are you running? 
   "1.8.4"

3. What cloud provider are you using?
    aws

4. What commands did you run?  What is the simplest way to reproduce this issue?
   kops toolbox template --values dev.yaml --template cluster.yaml

5. What happened after the commands executed?
-  The command couldn't replace the {{.clusterName}} with value present in dev.yaml; rather it printed empty value something like 'kops.k8s.io/cluster:  .eu-west-1'
- If I replace the {{.clusterName}} to {{.klusterName}} it is able to produce the desired result.
- If ~/.kube/config presents, it omits the value in dev.yaml and uses the clusterName value present at ~/.kube/config

6. What did you expect to happen?
kops toolbox template needs to produce the output value with clusterName using the value from dev.yaml

**Comment by madeddie** [comment]
I have the same problem running kops version 1.9.0 (installing k8s 1.8.7).

**Comment by Jsmiiii** [comment]
Likewise, exactly as in the opening description; KOPs 1.9.0 with K8s 1.9.7. Although not a major issue - change {{.clusterName}} to something else and values are populated are expected.
