### ISSUE TITLE
Dangerous assumption in README.md of kube-ingress-aws-controller about the default VPC

### ISSUE THREAD

**Issue by volkertb** [kubernetes/kops#5018]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.9.0 (git-cccd71e67)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
Amazon AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
The "aws ec2" commands under [chapter "Security Group for Ingress" in the README.md of kube-ingress-aws-controller](https://github.com/kubernetes/kops/blob/master/addons/kube-ingress-aws-controller/README.md#security-group-for-ingress).

5. What happened after the commands executed?
The security group configuration settings were applied to the VPC that happened to be the default ("IsDefault": true) at the time, which in my case was **not** a VPC managed by kops. I had to carefully undo these changes to that VPC manually.

6. What did you expect to happen?
That the changes would be applied to the Kubernetes cluster managed by kops (i.e. to the VPC containing that cljuster).

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
Not necessary for this bug/issue report.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
Not necessary for this bug/issue report.

9. Anything else do we need to know?
I had already created a Gossip-based Kubernetes cluster with kops, using the [general kops tutorial on GitHub](https://github.com/kubernetes/kops/blob/master/docs/aws.md) and [this blog post by Arun Gupta](http://blog.arungupta.me/gossip-kubernetes-aws-kops/). (By the way, it would be nice if the README.md of the kube-ingress-aws-controller could clarify whether or not this addon is compatible with gossip. Gossip is currently not mentioned anywhere in that README.)

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.
A warning or additional instructions clarifying that the --vpc-id option needs to be specified (with the correct VPC ID referring to the Kubernetes Cluster managed by kops) in the "aws ec2" commands, to prevent the security group configuration from being altered in the wrong VPC.

2. Feel free to provide a design supporting your feature request.
It would be nice if some command could be thought out which owuld extract the correct VPC ID from the output of the command "aws ec2 describe-vpcs" and place that in an environment variable such as $KOPS_VPC_ID. After listing that command on top of the list of instructions, you could then just append "--vpc-id=$KOPS_VPC_ID" to the existing "aws ec2" commands beneath that. I don't know how common it is to have kops manage a cluster over multiple VPCs, but if that is a possible configuration, you might want to take that scenario into account in these instructions as well.

Thank you in advance for considering this correction/clarification.

**Comment by volkertb** [comment]
Apparently, the --vpc-id option does not work with "aws ec2 describe-security-groups". For that command, you need to provide a filter instead: --filter Name=vpc-id,Values=<filter-id>

**Comment by volkertb** [comment]
It appears that the most crucial command where --vpc-id is missing is "aws ec2 create-security-group". Some of the other "aws ec2" commands will also have to be adjusted accordingly. Using group IDs is safer than group names, since the former are unique across VPCs.

**Comment by volkertb** [comment]
Apparently the repo at Zalando does already take into account the possibility of kops not being deployed on the default VPC: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/kops.md

**Comment by HerrmannHinz** [comment]
@volkertb feel free to raise a PR and adjust the docs?

**Comment by HerrmannHinz** [comment]
will adjust the docs. already working on it.

**Comment by volkertb** [comment]
@HerrmannHinz I'm afraid that the information you added is incomplete. This issue does not only arise when you have installed kops into an existing VPC. It also arises when a default VPC already exists when you start setting up a cluster with kops, since kops will then create a non-default VPC to install the cluster on. In that scenario, the same problem will occur if the cluster-specific VPC is not explicitly specified in the relevant "aws ec2" commands.

**Comment by volkertb** [comment]
Maybe someone can review my last previous comment and clarify the README as suggested? Thanks.
