### ISSUE TITLE
kops validate cluster no longer works through SSH tunnel.

### ISSUE THREAD

**Issue by treacher** [kubernetes/kops#5035]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.8.1
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
1.8.11
3. What cloud provider are you using?
AWS
4. What commands did you run?  What is the simplest way to reproduce this issue?
kops validate cluster
5. What happened after the commands executed?
unable to resolve Kubernetes cluster API URL dns: lookup host.domain.local:3000: no such host
6. What did you expect to happen?
The cluster to validate
7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
N/A
8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
N/A
9. Anything else do we need to know?

Our current setup has our DNS in a private hosted zone within AWS. The following commit: https://github.com/kubernetes/kops/commit/c7ef856f9274defda72c8d32a460f143a8d16f39 introduced a change where a DNS lookup is performed on validation. To get access to our cluster which is using a private hosted zone and is within a private subnet in our VPC we do the following:
  * Set up an SSH tunnel with a particular port say 3001 for example.
  * Update our local `/etc/hosts` file to resolve our Kubernetes API url to `127.0.0.1`
  * Update our Kubeconfig to use the port 3001 for further API calls.
  * Then follow the normal pattern for authenticating to the cluster.

The commit mentioned above uses: `net.LookupHost(host)` which will not look at `/etc/hosts` it will do an external look up which works fine when running on the actual bastion host that we tunnel through but doesn't work for the tunnelling example which means we're unable to validate our clusters locally when hosting our cluster in a private subnet.

I wondered whether doing a check using: `net.DialTimeout` before ruling out the DNS as unreachable would be an option. Then assuming that if we can reach it but we can't resolve it using `net.LookupHost(host)` that it was "okay".

It would be great to be able to run `kops validate cluster` again as it was working prior to this change. Did you have any opinions on this @chrislovecnm ?

**Comment by iMartyn** [comment]
As reported on slack, I believe the problem is that net.LookupHost(host) is actually trying to look up *including* the port sting.  net.LookupHost(host) should work for hosts file lines, it's the fact that it's not using the default port that's the problem.

**Comment by lukeab** [comment]
I was the one experiencing this issue. When i updated ~/.kube/config to use port 9443 for my api server url, kubectl continues to work fine, but kops validate cluster or kops rolling-update failed to talk to the api.
`unexpected error during validation: unable to resolve Kubernetes cluster API URL dns: lookup api.k8s.x.y.z.net:9443: no such host`
As seems to be suggested in the error message, it is trying to resolve the hostname including the port

**Comment by lukeab** [comment]
As a cheeky workaround i dropped the 9443 port in ~/.kube/config and ran socat to forward actual 443 to 9443 locally
`sudo socat tcp-listen:443,reuseaddr,fork tcp:localhost:9443`
This works for now, but dns resolution needs to get fixed to recognise ports in the host, regardless.

**Comment by mschenk42** [comment]
Looks like there is a recent fix that hasn't been released yet https://github.com/kubernetes/kops/commit/967f1e86c63ccd55535ac682d3456e91b7b80955#diff-db6ccc12f6f9b2292b080fc8bf24e622

For now I'm using a hack to workaround.  I was surprised it even worked :).

I use host entries to map the actual domain name to 127.0.0.1
`127.0.0.1 api.my.domain.com`

The hack is to add another host entry that includes the port.
`127.0.0.1 api.my.domain.com:4431`

**Comment by finkbit** [comment]
I'm also running into this issue. I'm also using an ssh tunnel to access my api. If I manually edit my `~/.kube/config` to use the port I can run the kops/validate command. Otherwise kops just overwrites the config with the private dns server name (which isn't much use because it's not accessible outside of aws).

Is there anyway to change the address that kops uses to access the api? 

Also @mschenk42 I don't understand how that hack could work (if i'm understanding you correctly you're editing `/etc/hosts`) because `/etc/hosts` and dns in general doesn't recognize ports.

**Comment by mschenk42** [comment]
To prevent kops from overriding the config when doing a `kops update cluster` use the ` --create-kube-config=false` option.  As far as the host file hack, the kops validation process is actually using the host when checking if it can validate, which in our case includes the port, but not for the actual validation process.  I know that sounds strange but it works.  Been using it a while now with no problems.

**Comment by finkbit** [comment]
@mschenk42 Oh, wasn't aware of that flag. Thanks!
