### ISSUE TITLE
Kops always creates new master volumes unattached

### ISSUE THREAD

**Issue by davidweizheng** [kubernetes/kops#5043]
I try to make simple change to the cluster (for example, modify cloudLabels), it appears that kops always creates new ebs volumes for master nodes and leave them unattached.

1. What `kops` version are you running? The command `kops version`, will display
 this information.
`Version 1.8.1 (git-94ef202)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
`Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
Run `kops edit cluster`, modify something in `cloudLabels`, then run 
`kops update cluster`, then `kops update cluster --yes`

5. What happened after the commands executed?
It prints out the following:
```
Will create resources:
  EBSVolume/a-1.etcd-events.<mycluster>
  	AvailabilityZone    	us-east-1a
  	VolumeType          	gp2
  	SizeGB              	20
  	Tags                	{...}
```

Volumes will be created and shown as Available in AWS Console.

6. What did you expect to happen?
It should only update what was changed without creating extra ebs volumes.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
N/A

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
N/A

9. Anything else do we need to know?
N/A

**Comment by styk-tv** [comment]
may depend on type of instance, some instances are ebs only and will always create ebs volume. https://aws.amazon.com/ec2/instance-types/ terraform will simply iterate with detail over what's happening.

**Comment by davidweizheng** [comment]
My question is why it creates new/unused volumes while volumes for master nodes already exist. After kops update completes, I have to manually delete those new volumes. Am I the only one that has this issues?

**Comment by davidweizheng** [comment]
Looks like a similar issue was reported a year ago - #1339 
> Update cluster is creating EBS volumes that exist

Any idea?

**Comment by davidweizheng** [comment]
OK, I think I figured out. It appears that Kops sets the 'Name' tag for etcd volumes like this:
```
Etcd event vol:  Name=a-1.etcd-events.<cluster-name>
Etcd main vol: Name=a-1.etcd-main.<cluster-name>
```
I accidentally changed the tags to something else, therefore Kops thinks these volumes were missing and tries to create new ones. I fixed the Name tags, now kops update works as expected.
