### ISSUE TITLE
Backing up etcd with etcd-manager documentation. Kops 1.9.0

### ISSUE THREAD

**Issue by ayk33** [kubernetes/kops#5048]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- FEATURE REQUEST TEMPLATE --------------------
1. Describe IN DETAIL the feature/behavior/change you would like to see.

Hello! I am trying to figure out a good backup scheme for etcd. I noticed that with the release of kops 1.9.0 `etcd-manager` was introduced into the picture. Is there any kind of documentation already in place to use `etcd-manager` to backup the cluster, or is there already some kind of automated backup that is happening in the background for the etcd cluster?

**Comment by justinsb** [comment]
Not yet; it will be documented once we have etcd-manger integrated (in kops 1.10): https://github.com/kubernetes/kops/blob/master/docs/etcd/roadmap.md

**Comment by ayk33** [comment]
Thanks for the feedback. Is there an estimated release date for kops 1.10?

**Comment by MihaiAnei** [comment]
Is this Roadmap implemented for 1.10 which was just released?

https://github.com/kubernetes/kops/blob/master/docs/etcd/roadmap.md
