### ISSUE TITLE
kops Delete Removes New ExecCredential Configurations In Kubecfgs

### ISSUE THREAD

**Issue by christopherhein** [kubernetes/kops#5051]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

```bash
→ kops version
Version 1.9.0

```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```bash
→ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:29:03Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?
`aws`

4. What commands did you run?  What is the simplest way to reproduce this issue?
`kubectl delete cluster --name example.cluster.k8s.local --yes`

5. What happened after the commands executed?
After the delete finishes when it cleans up the `kubeconfig` if you have any users with the new 1.10 alpha`ExecCredential` flow such as:

```bash
users:
- name: kubernetes-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "example.cluster.k8s.local"
```

It will replace the `users.user` key with:

```bash
- name: kubernetes-admin
  user: {}
```

Even if it's not the cluster it is deleting. To be clear it even changes the config for any user not just the user of the cluster that was deleted.

6. What did you expect to happen?

It to not mutate any of the other users.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

Deleted the cluster but you can recreate this with any cluster made with:

```bash
kops create cluster \
    --zones us-west-1a \
    --name example.cluster.k8s.local \
    --yes
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

I'm assuming this is because of the `k8s.io/client-go/tools/clientcmd` version in - https://github.com/kubernetes/kops/blob/33136f99d69a1214d2465a7dd9edb5fad3677bb5/pkg/kubeconfig/kubecfg_builder.go and should go into the 1.10 milestone.

**Comment by christopherhein** [comment]
As far as I understand this will be an issue until we have the 1.10 `client-go` release. Need to test the 1.10.alpha release to verify that will stop this.

**Comment by xrl** [comment]
@christopherhein any word on this issue? I'm just getting started on Kops/aws-iam-authenticator and I'd like to know if I'll hit this issue as I onboard new users.

**Comment by rifelpet** [comment]
I just confirmed that Kops 1.10 does not erase the `exec` field of the user anymore, however it does add `client-certificate-data` and `client-key-data` which unfortunately appear to take precedence over the exec credential.

It would be nice for `export kubecfg` to conditionally set the client data but I'm not sure how it could automatically figure out whether you want it or not, it may have to be a CLI flag if anything.

**Comment by vincetse** [comment]
Yep, I also tested this, and can also confirm that the `kops` installed with [Homebrew](https://brew.sh) , v1.10.0, behaves correctly and does not delete the `exec` config.

It would be super-nice if we can add an `exec` config from a command line somewhere, but I'll take this.

**Comment by rifelpet** [comment]
Closing this issue out. Theres currently no way for kops to know the specified clusterID in the authenticator configmap so having `kops export kubecfg` create the `exec` block is unrealistic.
/close

**Comment by christopherhein** [comment]
> Closing this issue out. Kops 1.10 no longer wipes the exec block. Theres currently no way for kops to know the specified clusterID in the authenticator configmap so having `kops export kubecfg` create the `exec` block is unrealistic.

Isn't the `clusterID` just the cluster name? Or does `kops` do something different? If nothing else should this be in the kops manifest?

This should stay closed and we should track elsewhere anyways cause this was just to stop kops from removing any not just the current cluster `exec` credential block since hen we launched eks that patch for `client-go` wasn't merged into `kops`

**Comment by rifelpet** [comment]
@christopherhein the `clusterID` in the configmap isnt guaranteed to be the cluster name since the configmap is managed outside of kops. I use the cluster name in all of my clusters but others may not. We may be able to make that a requirement or make it known to the user that `export kubecfg` will assume the clusterID is the cluster name in the exec block it creates.

It would definitely be nice to not use the client cert in kubeconfig, but at the same time I sometimes find it handy specifically when dealing with aws-iam-authenticator issues. I can bypass the authenticator using the client certs in order to update the configmap. Perhaps a flag of some sort on `export kubecfg`? Regardless, I agree this should go in a separate issue.

**Comment by christopherhein** [comment]
Awesome, thanks for the feedback.
