### ISSUE TITLE
Cannot update weave CONN_LIMIT

### ISSUE THREAD

**Issue by wendorf** [kubernetes/kops#5055]
------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

`Version 1.9.0`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Client Version: 1.10.1
Server Version: 1.9.6

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

My cluster originally had:

```
spec:
  networking:
    weave:
      connLimit: 100
```

I changed `connLimit` to `162` and applied with `kops replace -f "$CLUSTER_CONFIG" --force`. Checking with `kops get cluster --name my-cluster.example.com -o json | jq .spec.networking.weave.connLimit` shows `162` as expected.

I then apply the change to my cluster:

```
kops update cluster my-cluster.example.com --yes
kops rolling-update cluster my-cluster.example.com --yes
```

5. What happened after the commands executed?

The weave daemonset still shows a CONN_LIMIT of 100:

```
→ kubectl -nkube-system get ds weave-net -o yaml | grep 'name: CONN_LIMIT' -C1
          value: "8912"
        - name: CONN_LIMIT
          value: "100"
```

6. What did you expect to happen?

The weave daemonset is updated to show a CONN_LIMIT of 162.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

https://gist.github.com/wendorf/788183e0690c064db3ee5ff9d16ec375

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

`kops update cluster -v10`: https://gist.github.com/wendorf/35424d675c245082c605495c10a4d5d6
I've skipped the `rolling-update` logs because I don't think they're relevant, and they have a lot to redact.

9. Anything else do we need to know?

I'm able to manually edit the weave daemonset to use a custom third CONN_LIMIT with `kubectl -nkube-system edit ds weave-net`, and when I `kops update` again, it still doesn't update (to either the original value, or the desired second value).

**Comment by jrnt30** [comment]
I had this issue in a cluster that we had created in Kops 1.8 however I have been unable to reproduce this behavior in Kops 1.9+

**Comment by wendorf** [comment]
Coming back to this issue months later, I'm pretty sure this behavior is because config changes that affect an addon don't get applied. Installed addons are tracked in the annotations for the `kube-system` namespace, and once a version has been installed, config changes are ignored. The current workaround is to remove the `addons.k8s.io/networking.weave` annotation from the `kube-system` namespace and try installing with kops again.
