### ISSUE TITLE
`kops create -f` Doesn't Handle Multiple Input Objects in an Array

### ISSUE THREAD

**Issue by daviddyball** [kubernetes/kops#5059]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

`Version 1.9.0 (git-cccd71e67)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

`1.9.3`

3. What cloud provider are you using?

Amazon AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

```
kops get --out json --state=s3://{STATE_BUCKET} {CLUSTER_NAME} > my_config.json`
kops delete cluster --state=s3://{STATE_BUCKET} {CLUSTER_NAME}
kops create -f my_config.json
```

5. What happened after the commands executed?

```
error: error parsing file "/tmp/test.json": couldn't get version/kind; json parse error: json: cannot unmarshal array into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

6. What did you expect to happen?

I expected the input to be validated by Kops and then have the required `Cluster` and `InstanceGroup` objects created correctly, but it appears that `kops create` doesn't know how to handle multiple objects wrapped in a list. I would think that any direct output from `kops get --out json` should be parse-able by `kops create` right?

7. Please provide your cluster manifest. 

I didn't get this far in the process. No cluster has been created.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

```
F0423 10:59:46.895080     198 helpers.go:119] error: error parsing file "/tmp/test.json": couldn't get version/kind; json parse error: json: cannot unmarshal array into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

9. Anything else do we need to know?

Not that I can think of.

As a work-around, will it be possible to output each object as an individual template and then run separate commands like so?

```
kops create -f cluster.config
kops create -f instancegroup-master-a.config
kops create -f instancegroup-master-b.config
kops create -f instancegroup-master-c.config
kops create -f instancegroup-nodes-a.config
```

EDIT: Just to confirm that `kops create -f cluster.config,master-a.config,nodes.config,bastions.config` syntax works fine. It'd still be nice to have support for a single JSON array in a file

**Comment by chrissound** [comment]
Is there any alternative / work around?

**Comment by Seb-Solon** [comment]
See https://github.com/kubernetes/kops/issues/5115#issuecomment-499160421 for a possible workaround
