### ISSUE TITLE
error when scale down and change machine type

### ISSUE THREAD

**Issue by lasse-kristensen** [kubernetes/kops#5060]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
`Version 1.9.0-alpha.1 (git-f799036a3)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
kops edit ig --name=k8s-cluster-name nodes
then I changed:
machineType: from m4.large to m3.medium
and
  maxSize: from 8 to 2
  minSize:  from 8 to 2

then kops update cluster --yes then kops rolling-update cluster --yes

5. What happened after the commands executed?
i got the following error and the node type didn't change in AWS.
So now i got 2 m4.large node
```
I0423 11:07:31.136040   19346 instancegroups.go:157] Draining the node: "ip-172-20-50-58.eu-west-1.compute.internal".
node "ip-172-20-50-58.eu-west-1.compute.internal" cordoned
node "ip-172-20-50-58.eu-west-1.compute.internal" cordoned
WARNING: Ignoring DaemonSet-managed pods: kube-flannel-ds-vn8tf; Deleting pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet: kube-proxy-ip-172-20-50-58.eu-west-1.compute.internal
pod "heapster-9f45d84c6-gwhn9" evicted
pod "worker-64d5bfcb89-86z6w" evicted
pod "loginserver-86bcc77cb6-gdghj" evicted
node "ip-172-20-50-58.eu-west-1.compute.internal" drained
I0423 11:53:10.459233   19451 instancegroups.go:333] Waiting for 1m30s for pods to stabilize after draining.
I0423 11:09:01.483285   19346 instancegroups.go:274] Stopping instance "i-06218d90aa238da6f", node "ip-172-20-50-58.eu-west-1.compute.internal", in group "nodes.k8s-cluster.peytz-k8s.vpc".
E0423 11:09:01.532457   19346 instancegroups.go:172] Error deleting aws instance "i-06218d90aa238da6f", node "ip-172-20-50-58.eu-west-1.compute.internal": error deleting instance "i-06218d90aa238da6f", node "ip-172-20-50-58.eu-west-1.compute.internal": error deleting instance "i-06218d90aa238da6f": ValidationError: Instance Id not found - No managed instance found for instance ID i-06218d90aa238da6f
	status code: 400, request id: ba2f14e9-46e6-11e8-82b9-cd1ba0815e92

error deleting instance "i-06218d90aa238da6f", node "ip-172-20-50-58.eu-west-1.compute.internal": error deleting instance "i-06218d90aa238da6f": ValidationError: Instance Id not found - No managed instance found for instance ID i-06218d90aa238da6f
	status code: 400, request id: ba2f14e9-46e6-11e8-82b9-cd1ba0815e92
```

6. What did you expect to happen?
scaling down and changing node type without errors

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

**Comment by zytek** [comment]
I guess you have a race between kops trying to delete instance that was just terminated by AWS ASG after scale-down event. You should wait till your ASG scales down to desired number of nodes before you do `rolling-update`.

One feature kops could implement is to NOT perform rolling-update when ASG is being updated by AWS, if this is reliably detectable via API.
