### ISSUE TITLE
Support for skipping docker portion of nodeup

### ISSUE THREAD

**Issue by byndcivilization** [kubernetes/kops#5087]
We are trying to implement GPU backed nodes on our cluster. The Kops hook provided for nividia-bootstrap is broken in that its missing a crucial docker-ce and nvidia-docker2 installation and configuration. I can bake these into an AMI, however nodeup is clobbering my docker configs. Is there a feature flag to turn off docker.service? Guidelines on developing custom dockerized hooks? I've gotten to a place where we are running a custom script that is baked in to the AMI after docker.service but it still seems to be getting clobbered. Can you point to a service that runs last that i can piggy back off of for timing?

`kops version - 1.8.1`

```kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by innovia** [comment]
@byndcivilization any workaround this - im stuck in this too
