### ISSUE TITLE
Feature request: Install/upgrade to Calico v3

### ISSUE THREAD

**Issue by tmjd** [kubernetes/kops#5101]
# FEATURE REQUEST

## New functionality

Calico has a version v3.x and I would like to be able to install or upgrade to it using kops.

## Context

The new version of Calico is using a new data model and has switched to using etcd v3 API instead of the v2, much of this feature will have to do with being able to support the two different versions of Calico in Kops and support migration of the datastore when possible.

## Design

To support Calico v2 and Calico v3 releases I plan to create a new flag in  `Spec.Networking.Calico` called `APIVersion`. If it is unset then Calico v2 manifests will be used, if it is set to `v3` then a new V3 manifest will be used, which I will also add.  If calico networking is selected when creating a cluster the APIVersion should be defaulted to v3, this will require defaulting the etcd version to a v3 series in that case.

There are many clusters deployed already and it would be good to support upgrades to the newer Calico version when possible.  This will only be supported with clusters using etcd v3 since there is not a current upgrade path from v2 to v3 in Kops for etcd.  To support this, I plan to add some specialized containers and a Job to the Calico manifest that will automatically do the datastore migration.

Along with the code changes a new doc page will be added that outlines these new fields and how to use them.  This includes how the migration should be done including any pre-checks to do, how to monitor the status of the migration, the functionality during the migration, and help in the case of failure.

### Questions I have

- Is there anything objectionable in this design?
  - Specifically is it ok to set the etcd server version to a v3 if calico is specified for networking when creating the cluster?
- Is there a way to validate the cluster spec, specifically around validating that if the proposed APIVersion is set for V3 that the etcd server version also is set to a V3 series?

**Comment by Mitrofanov** [comment]
+1
