### ISSUE TITLE
Status of the kops api server

### ISSUE THREAD

**Issue by gh0o0st** [kubernetes/kops#5111]
Hi guy,

I'm wondering what's the status of the kops api server? Is it production ready? 

I didn't find many doc related. I'm able to compile out the server, but how to set it up?

Any help would be grateful, thx

**Comment by Raffo** [comment]
I guess it makes sense to get some more info into that. I'm also wondering what it is going to be with kops and the development of the new cluster-api. 
Does anyone have more info to share? 

/remove-lifecycle stale
