### ISSUE TITLE
kubectl permission denied on kops cluster 

### ISSUE THREAD

**Issue by truyet** [kubernetes/kops#5114]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.9.0
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
v1.10.1
3. What cloud provider are you using?
AWS
4. What commands did you run?  What is the simplest way to reproduce this issue?
kops export kubecfg ${CLUSTER_NAME} --state=$KOPS_STATE_STORE
envsubst < deployment.yml > deployment-${CI_COMMIT_TAG}.yml
kubectl apply -f <(istioctl kube-inject -f deployment-${CI_COMMIT_TAG}.yml --includeIPRanges=${IP_RANGE})

5. What happened after the commands executed?
/bin/bash: line 87: /usr/local/bin/kubectl: Permission denied

6. What did you expect to happen?
Service created

**Comment by huang-jy** [comment]
`sudo chmod +x /usr/local/bin/kubctl`

**Comment by truyet** [comment]
I fixed it, thanks
