### ISSUE TITLE
ExpandPersistentVolumes/PersistentVolumeClaimResize Are Shown As Enabled But Are Not Working

### ISSUE THREAD

**Issue by amatzia** [kubernetes/kops#5124]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.9.0 (git-cccd71e67)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

"kops edit cluster "
to add the following features under specs.kubeAPIServer
"
kubeAPIServer:
    admissionControl:
    - PersistentVolumeClaimResize
    featureGates:
      ExpandPersistentVolumes: "true"
  kubeControllerManager:
    featureGates:
      ExpandPersistentVolumes: "true"
  kubelet:
    featureGates:
      ExpandPersistentVolumes: "true"
"

5. What happened after the commands executed?

running "kops update cluster" to get new config
shows:
                                 -   - Initializers
                                -   - NamespaceLifecycle
                                -   - LimitRanger
                                -   - ServiceAccount
                                -   - PersistentVolumeLabel
                                -   - DefaultStorageClass
                                -   - DefaultTolerationSeconds
                                -   - MutatingAdmissionWebhook
                                -   - ValidatingAdmissionWebhook
                                -   - NodeRestriction
                                +   - PersistentVolumeClaimResize
                                -   - ResourceQuota
and 
 +   featureGates:
 +     ExpandPersistentVolumes: "true"

6. What did you expect to happen?

for "allowVolumeExpansion: true" flag inside storageClass yamls to work 
but when describing the storage class "allowVolumeExpansion = [unset]"
and when editing it the line "allowVolumeExpansion: true" is gone
this feature cannot be used

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-05-09T11:31:26Z
  name: example.cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://k8s-workshop-kopsstatestore-1pse9bvbk5l0m/example.cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - PersistentVolumeClaimResize
    featureGates:
      ExpandPersistentVolumes: "true"
  kubeControllerManager:
    featureGates:
      ExpandPersistentVolumes: "true"
  kubelet:
    featureGates:
      ExpandPersistentVolumes: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterInternalName: api.internal.example.cluster.k8s.local
  masterPublicName: api.example.cluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  - cidr: 172.20.64.0/19
    name: us-west-2b
    type: Public
    zone: us-west-2b
  - cidr: 172.20.96.0/19
    name: us-west-2c
    type: Public
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-09T11:31:27Z
  labels:
    kops.k8s.io/cluster: example.cluster.k8s.local
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-09T11:31:27Z
  labels:
    kops.k8s.io/cluster: example.cluster.k8s.local
  name: master-us-west-2b
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-09T11:31:27Z
  labels:
    kops.k8s.io/cluster: example.cluster.k8s.local
  name: master-us-west-2c
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2c
  role: Master
  subnets:
  - us-west-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-09T11:31:27Z
  labels:
    kops.k8s.io/cluster: example.cluster.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.medium
  maxSize: 5
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  - us-west-2c

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

no other commands to run

9. Anything else do we need to know?

thats all :)

**Comment by josdotso** [comment]
@amatzia We're seeing something similar. Can you expound on how you fixed/addressed it?

**Comment by amatzia** [comment]
@josdotso 
Hi Joshua
after adding the following config to my kops config file

kubeAPIServer:
    admissionControl:
    - PersistentVolumeClaimResize
    featureGates:
      ExpandPersistentVolumes: "true"
  kubeControllerManager:
    featureGates:
      ExpandPersistentVolumes: "true"
    horizontalPodAutoscalerUseRestClients: false
  kubelet:
    featureGates:
      ExpandPersistentVolumes: "true"

i restarted the cluster (masters and nodes "  kops rolling-update cluster --yes") i still had an issue with expanding the volume. 
when checking the pvc "kubectl describe pvc <NAME>" i saw an error from AWS regarding permissions to expand volume so i added to all my masters (and nodes) and IAM role for ec2

ModifyVolume
ModifyVolumeAttribute

and that resolved the issue (note that you can only change a volume once every 6 hours in AWS)

**Comment by HerrmannHinz** [comment]
@amatzia mind formating your cluster.yml here in this issue so it can be read better? 
would be nice to have it more readable (and copy n paste ready ;) ) as reference.

**Comment by amatzia** [comment]
@HerrmannHinz sorry for the delay
here is the config (without our ip's and dns records)


apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-12-24T07:16:22Z
  name: 
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": [
                "ec2:DescribeVpcs",
                "elasticloadbalancing:AddTags",
                "elasticloadbalancing:CreateListener",
                "elasticloadbalancing:CreateTargetGroup",
                "elasticloadbalancing:DeleteListener",
                "elasticloadbalancing:DeleteTargetGroup",
                "elasticloadbalancing:DescribeListeners",
                "elasticloadbalancing:DescribeLoadBalancerPolicies",
                "elasticloadbalancing:DescribeTargetGroups",
                "elasticloadbalancing:DescribeTargetHealth",
                "elasticloadbalancing:ModifyListener",
                "elasticloadbalancing:ModifyTargetGroup",
                "elasticloadbalancing:RegisterTargets",
                "elasticloadbalancing:SetLoadBalancerPoliciesOfListener"
            ],
          "Resource": [
                "*"
            ]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": "elasticloadbalancing:*",
          "Resource": "*"
        },
        {
          "Effect": "Allow",
          "Action": "ec2:*",
          "Resource": "*"
        },
        {
          "Effect": "Allow",
          "Action": "elasticloadbalancing:*",
          "Resource": "*"
        },
        {
          "Effect": "Allow",
          "Action": ["route53:ChangeResourceRecordSets"],
          "Resource": ["arn:aws:route53:::hostedzone*"]
        },
        {
          "Effect": "Allow",
          "Action": ["route53:ListHostedZones", "route53:ListResourceRecordSets"],
          "Resource": ["*"]
        },
        {
          "Effect": "Allow",
          "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
                    ],
          "Resource":"*"
        }
      ]
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    disableSecurityGroupIngress: true
  cloudProvider: aws
  configBase: 
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - PersistentVolumeClaimResize
    featureGates:
      ExpandPersistentVolumes: "true"
  kubeControllerManager:
    featureGates:
      ExpandPersistentVolumes: "true"
    horizontalPodAutoscalerUseRestClients: false
  kubelet:
    featureGates:
      ExpandPersistentVolumes: "true"
  kubernetesApiAccess:
  - 
  kubernetesVersion: 1.10.0
  masterInternalName: 
  masterPublicName: 
  networkCIDR: 
  networking:
    calico:
      crossSubnet: true
  nonMasqueradeCIDR: 
  sshAccess:
  - 
  - 
  - 
  subnets:
  - cidr: 
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 
    name: us-east-1c
    type: Public
    zone: us-east-1c
    topology:
    dns:
    type: Public
    masters: public
    nodes: public
