### ISSUE TITLE
Kops should gracefully handle AWS credentials expiring during a command

### ISSUE THREAD

**Issue by geekofalltrades** [kubernetes/kops#5130]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

   1.9.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

   N/A

3. What cloud provider are you using?

   AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

   `kops update cluster --yes`

5. What happened after the commands executed?

   I ran a `kops update cluster --yes` using a set of temporary AWS credentials that I got by assuming a role. First, the command got stuck in a backoff listing autoscaling groups:

    ```
    I0502 20:56:18.110124     549 logging_retryer.go:60] Retryable error (Throttling: Rate exceeded
        status code: 400, request id: 428b027c-4e4b-11e8-875b-530c6f7e6e00) from autoscaling/DescribeLaunchConfigurations - will retry after delay of 528ms
    ```

   This happens every time we run Kops commands, because we have many InstanceGroups in our cluster. Shortly afterwards, the temporary AWS credentials I was using to run this command expired, and these log messages began appearing:

    ```
    I0502 20:56:45.095059     549 logging_retryer.go:60] Retryable error (ExpiredToken: The security token included in the request is expired
        status code: 403, request id: 52a6d8c1-4e4b-11e8-b0c4-c114eb337509) from autoscaling/DescribeLaunchConfigurations - will retry after delay of 1.216s
    ...
    I0502 20:56:45.216861     549 logging_retryer.go:60] Retryable error (RequestExpired: Request has expired.
        status code: 400, request id: 031ceeb0-c085-4a3d-b9d6-8ef05c796b1a) from ec2/DescribeImages - will retry after delay of 44ms
    ```

   These log lines are repeated MANY times. After 15 minutes (!) of this, the command finally failed with an error:

    ```
    error running tasks: deadline exceeded executing task LaunchConfiguration/servicekeyworker-fmd-qn8-d7p-rfb-7kc.pdx.hopcloud.extrahop.com. Example error: error listing AutoscalingLaunchConfigurations: ExpiredToken: The security token included in the request is expired
        status code: 403, request id: 2feef2b6-4e4c-11e8-8ea0-0d14e3719c5e
    ```

6. What did you expect to happen?

   kops should have gracefully errored out when the AWS credentials it was using expired.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

   N/A

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

   N/A

9. Anything else do we need to know?

   The temporary credentials being used to run this request were generated by the Hashicorp Vault [AWS STS AssumeRole](https://www.vaultproject.io/docs/secrets/aws/index.html#sts-assumerole) secrets backend.

**Comment by jeyglk** [comment]
Same issue, AWS credentials expired after one hour, during a `kops rolling-update` and after a few retries the command ended up failing.

**Comment by luispollo** [comment]
Same here. If it helps, I would like to add that, as far as I can see from the code, the credential provider would try to retrieve new credentials if expired, but if I update my `.aws/credentials` file with renewed credentials while kops is in that retry loop, it does not pick up the updated creds for some reason.

**Comment by michaelajr** [comment]
I think this is a fairly big issue that needs to be addressed. Rolling updates can take hours. We 1h tokens via STS for credentials. We get a new token in the background when needed. But Kops never loads it.
