### ISSUE TITLE
GPU for newer kubernetes versions

### ISSUE THREAD

**Issue by strin** [kubernetes/kops#5135]
It seems the GPU support for Kubernetes is stale: 1.7.2. For kubernets >= 1.8, GPUs are supported in a different way https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

**Comment by brunsgaard** [comment]
I am working on an installer for `nvidia-docker` that uses kops hooks.

A rough but working solution can be found in my kops fork.
https://github.com/brunsgaard/kops/tree/nvidia-docker-docs/hooks/nvidia-docker

A PR will arrive some time next week :) Hope you find it useful.

**Comment by brunsgaard** [comment]
Duplicate of #4591
