### ISSUE TITLE
information on etcd backups is wrong

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/kops#5147]
The information on how to backup the etcd cluster is wrong and dangerous (https://github.com/kubernetes/kops/blob/master/docs/etcd_backup.md)

If someone is to follow the steps from your document will have good backups only by luck. This method of snapshoting the etcd volumes will produce incorrect backups eventually.

And I know people that do the backups your way. Fortunately for them, they never test the backups. Ignorance is bliss.

**Comment by KernelPanicAUS** [comment]
@cristifalcas can you highlight the errors in the documentation?
What is the alternative practice?

**Comment by cristifalcas** [comment]
So correct way to backup is to use "etcdctl backup"

For example:

```
BACKUP_NAME=etcd_backup_$(date +%s).tgz
ETCD_DATA_DIR=/var/etcd/data # or /var/etcd/data-events
kubectl exec -t $ETCD_POD -n kube-system -- sh -c "rm -rf /backup && etcdctl backup --data-dir=${ETCD_DATA_DIR} --backup-dir=/backup && tar -czf ${BACKUP_NAME} /backup"
kubectl cp kube-system/$ETCD_POD:/${BACKUP_NAME} ./
```
