### ISSUE TITLE
Why is an SSH public key classified as a "secret?"

### ISSUE THREAD

**Issue by pseudometric** [kubernetes/kops#5149]
`kops` treats SSH public keys as a “secret.” Why? The public component of an asymmetric key pair is not a secret; it shouldn't be called or treated as one. This choice seems to have material consequences that could be avoided: for example, there's no reason why the SSH key specified by `kops create cluster --ssh-public-key` could not be in a cluster manifest for use by `kops create -f`, but currently it can't be because it's treated as a secret — so you have to run a separate `kops create secret` instead of just including the SSH public key as part of the cluster configuration.

**Comment by recollir** [comment]
According to https://github.com/recollir/kops/blob/master/docs/secrets.md it should be possible to pass the ssh public key via the cluster spec.

```
spec:
  publicKey: "ssh-rsa AAAAB3NzaC1 dev@devbox"
```
