### ISSUE TITLE
How to download 'nodeup' from alternative URL

### ISSUE THREAD

**Issue by pahud** [kubernetes/kops#5154]
Kops will download `nodeup` from `https://kubeupv2.s3.amazonaws.com/kops/1.9.0/linux/amd64/nodeup` by default.

How can I configure Kops to download it from my local mirror?

I've specified the following env vars:

```
export KOPS_BASE_URL=https://<MY_LOCAL_MIRROR_URL_PATH>
export NODEUP_URL=${KOPS_BASE_URL}linux/amd64/nodeup
```

But it looks like still download from `https://kubeupv2.s3.amazonaws.com/kops/1.9.0/linux/amd64/nodeup`

Thoughts?

**Comment by moh-abk** [comment]
Just started messing about with `kops` using `Terraform` and the `user_data` that gets put in the EC2 servers sets the url and hash. They aren't ENV vars from what I see.

```
NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.9.0/linux/amd64/nodeup
NODEUP_HASH=54ecae66a2b4e1409b36fc00b550f2501afedbfc
```

**Comment by pahud** [comment]
I can see this message from the kops create cluster


> W0514 09:55:17.496115   80014 urls.go:126] Using nodeup location from NODEUP_URL env var: "https://<MY_MIRROR_SITE>/kubeupv2/kops/1.9.0/linux/amd64/nodeup"

And this message is from  **NodeUpLocation()** in [urls.go](https://github.com/kubernetes/kops/blob/a52f8f9673dc920efb88da2cef3e9ea906fbccd7/upup/pkg/fi/cloudup/urls.go
):

But I still can't find why it still uses the default NODEUP_URL in the `User Data`
