### ISSUE TITLE
Cant setup addon kube-ingress-aws-controller

### ISSUE THREAD

**Issue by iBat** [kubernetes/kops#5159]
1. What `kops` version are you running? The command `kops version`, will display
 this information. 
Version 1.9.0 (git-cccd71e67)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

I tried to reproduce guide https://github.com/kubernetes/kops/tree/master/addons/kube-ingress-aws-controller
First trouble - creating security group.

```
$ aws ec2 describe-security-groups --group-names ingress.$KOPS_CLUSTER_NAME                               

An error occurred (InvalidGroup.NotFound) when calling the DescribeSecurityGroups operation: The security group 'ingress.domain.com' does not exist in default VPC 'vpc-xxxxxx'
```

This is because kubernetes uses different VPC. So I changed this commands to use specific VPC-ID.
Another trouble:

```
NAME                                           READY     STATUS             RESTARTS   AGE
kube-ingress-aws-controller-5959c8f9c7-4xrw6   0/1       CrashLoopBackOff   9          28m
skipper-ingress-d7mcd                          0/1       Running            0          25m
```

controller logs

```
2018/05/15 10:37:05 starting /bin/kube-ingress-aws-controller
2018/05/15 10:37:05 required security group was not found
```

skipper logs

```
[15/May/2018:11:22:10 +0000] "GET /kube-system/healthz HTTP/1.1" 404 10 "-" "kube-probe/1.9" 0 172.20.42.35:9999 - -
[APP]time="2018-05-15T11:22:12Z" level=error msg="failed to load all: request failed, status: 403, 403 Forbidden"
[APP]time="2018-05-15T11:22:12Z" level=error msg="error while receiveing initial data;request failed, status: 403, 403 Forbidden"
[APP]time="2018-05-15T11:22:15Z" level=error msg="failed to load all: request failed, status: 403, 403 Forbidden"
[APP]time="2018-05-15T11:22:15Z" level=error msg="error while receiveing initial data;request failed, status: 403, 403 Forbidden"
[APP]time="2018-05-15T11:22:18Z" level=error msg="failed to load all: request failed, status: 403, 403 Forbidden"
[APP]time="2018-05-15T11:22:18Z" level=error msg="error while receiveing initial data;request failed, status: 403, 403 Forbidden"
172.20.42.35 - - 
```

I believe controller looks for security group in the same way as in docs. And this is not work for me.

**Comment by trajakovic** [comment]
@iBat have you seen this post? [issue](https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/95#issuecomment-341488732)?

Try to add missing tag(s) to your `api-elb.<cluster-name>` via aws web console, and this should resolve `kube-ingress-aws-controller` error

**Comment by iBat** [comment]
Thx @trajakovic 

I solved my issue using https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/kops.md and https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/153
