### ISSUE TITLE
create cluster calculates invalid utility subnet size for AWS

### ISSUE THREAD

**Issue by rtwruck** [kubernetes/kops#5161]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.9.0 (git-cccd71e67)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?

aws

4. What commands did you run?  What is the simplest way to reproduce this issue?

kops create cluster mycluster \
--node-count 3 \
--zones eu-central-1a,eu-central-1b,eu-central-1c \
--networking weave \
--topology private \
--associate-public-ip=false \
--dns private \
--network-cidr 192.168.168.0/24 \
--state s3://mycluster

5. What happened after the commands executed?

I0515 18:45:08.144437   10441 create_cluster.go:1318] Using SSH public key: /home/ubuntu/.ssh/id_rsa.pub
I0515 18:45:08.807555   10441 create_cluster.go:472] Inferred --cloud=aws from zone "eu-central-1a"
I0515 18:45:09.779095   10441 subnets.go:184] Assigned CIDR 192.168.168.32/27 to subnet eu-central-1a
I0515 18:45:09.779206   10441 subnets.go:184] Assigned CIDR 192.168.168.64/27 to subnet eu-central-1b
I0515 18:45:09.779303   10441 subnets.go:184] Assigned CIDR 192.168.168.96/27 to subnet eu-central-1c
I0515 18:45:09.779382   10441 subnets.go:198] Assigned CIDR 192.168.168.0/30 to subnet utility-eu-central-1a
I0515 18:45:09.779467   10441 subnets.go:198] Assigned CIDR 192.168.168.4/30 to subnet utility-eu-central-1b
I0515 18:45:09.779537   10441 subnets.go:198] Assigned CIDR 192.168.168.8/30 to subnet utility-eu-central-1c

Subnets on AWS may not be smaller than /28.
When actually creating the cluster, this results in a loop with AWS response:
InvalidSubnet.Range: The CIDR '192.168.168.0/30' is invalid.

6. What did you expect to happen?

Utility subnets of at least /28

**Comment by mikepuglisi** [comment]
+1

**Comment by aswin020** [comment]
+1. 

Sample logs. 

W0818 16:46:26.190547   69384 executor.go:130] error running task "Subnet/utility-ap-southeast-1b.MYCLUSTER" (9m41s remaining to succeed): error creating subnet: InvalidSubnet.Range: The CIDR '192.168.0.4/30' is invalid.
	status code: 400, request id: 0926107f-d216-45f7-a34f-2c502dce40b9

W0818 16:46:26.190653   69384 executor.go:130] error running task "Subnet/utility-ap-southeast-1a.MYCLUSTER" (9m41s remaining to succeed): error creating subnet: InvalidSubnet.Range: The CIDR '192.168.0.0/30' is invalid.
	status code: 400, request id: d98e23ed-869d-4d43-88fb-6935ae50d747
