### ISSUE TITLE
daemonset-controller rolls back my calico upgrade

### ISSUE THREAD

**Issue by igorvpcleao** [kubernetes/kops#5162]
> 1. What `kops` version are you running? The command `kops version`, will display

Version 1.9.0

> 2. What Kubernetes version are you running? `kubectl version` will print the

 version if a cluster is running or provide the Kubernetes version specified as
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

> 3. What cloud provider are you using?

aws

> 4. What commands did you run?  What is the simplest way to reproduce this issue?

kubectl edit ds calico-node -n kube-system #updated calico image from v2.6.7 to v2.6.9

> 5. What happened after the commands executed?

Manifest gets updated, increasing its revision number; A deploy is triggered and pods start getting updated.
Manifest gets updated again (not by me), increasing its revision number one more time, but restoring the image to v2.6.7; Pods are rolled back to previous version.

> 6. What did you expect to happen?

daemonset to persist new image

> 9. Anything else do we need to know?

I can see daemonset-controller is the responsible for killing pods:

**logs from `kube-controller-manager`:**
```
I0515 20:16:13.342296       1 controller_utils.go:590] Controller calico-node deleting pod kube-system/calico-node-r4w6c
I0515 20:16:13.360236       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"calico-node", UID:"db50b3a1-b380-11e7-8861-0a2ad6e2b63e", APIVersion:"extensions", ResourceVersion:"109585617", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: calico-node-r4w6c
I0515 20:16:13.391796       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"calico-node", UID:"db50b3a1-b380-11e7-8861-0a2ad6e2b63e", APIVersion:"extensions", ResourceVersion:"109585634", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: calico-node-trdlg
I0515 20:16:14.997523       1 controller_utils.go:590] Controller calico-node deleting pod kube-system/calico-node-5srdh
I0515 20:16:15.016873       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"calico-node", UID:"db50b3a1-b380-11e7-8861-0a2ad6e2b63e", APIVersion:"extensions", ResourceVersion:"109585636", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: calico-node-5srdh
I0515 20:16:15.046187       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"calico-node", UID:"db50b3a1-b380-11e7-8861-0a2ad6e2b63e", APIVersion:"extensions", ResourceVersion:"109585636", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: calico-node-v9klt
E0515 20:16:15.054997       1 daemon_controller.go:265] kube-system/calico-node failed with : error storing status for daemon set &v1beta1.DaemonSet{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"calico-node", GenerateName:"", Namespace:"kube-system",
```

**kubectl get events:**
```
19m         19m          1         calico-node.152eedc776b68f6a                                DaemonSet                                               Normal    SuccessfulDelete        daemonset-controller                      Deleted pod: calico-node-vr9qb
19m         19m          1         calico-node.152eedc7db6fde34                                DaemonSet                                               Normal    SuccessfulDelete        daemonset-controller                      Deleted pod: calico-node-pknbk
19m         19m          1         calico-node.152eedc85a96b5e8                                DaemonSet                                               Normal    SuccessfulDelete        daemonset-controller                      Deleted pod: calico-node-q5h6z
19m         19m          1         calico-node.152eedc8e0d87ef9                                DaemonSet                                               Normal    SuccessfulDelete        daemonset-controller                      Deleted pod: calico-node-qwzv9
19m         19m          1         calico-node.152eedc929db5e85                                DaemonSet                                               Normal    SuccessfulDelete        daemonset-controller                      Deleted pod: calico-node-wntrh
13m         19m          3         calico-node.152eedca5528a575                                DaemonSet                                               Normal    SuccessfulDelete        daemonset-controller                      (combined from similar events): Deleted pod: calico-node-sz4qm
[...]
```

I'm wondering if there is something related to kops which may cause this issue.

**Comment by lkysow** [comment]
I think the `protokube` container continuously polls and applies the addons from the kops s3 bucket. You can see the calico ones here: https://github.com/kubernetes/kops/tree/master/upup/models/cloudup/resources/addons/networking.projectcalico.org.

For my setup when I was creating the cluster I overwrote the files in the s3 bucket after kops populated them so I could upgrade calico. Not sure if there's a better way to do it.

**Comment by igorvpcleao** [comment]
That's quite interesting. 
You're absolutely right. I just did the same and it now works.

Thanks, @lkysow.
