### ISSUE TITLE
ca.key on the master node has permissions 644 in /srv/kubernetes

### ISSUE THREAD

**Issue by gaganapplatix** [kubernetes/kops#5163]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

1.9.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

Create any kops cluster on aws.

5. What happened after the commands executed?

ssh to a master node

ls -l /srv/kubernetes/ca.key
-rw-r--r--. 1 root root 1675 May 16 00:01 /srv/kubernetes/ca.key

6. What did you expect to happen?

The permissions of /srv/kubernetes/ca.key should be 600

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

Not hugely relevant.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

Not relevant

9. Anything else do we need to know?

ca.key matches the key in s3 for the cluster ca

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

Change so /srv/kubernetes/ca.key has permissions 600

2. Feel free to provide a design supporting your feature request.

**Comment by rdrgmnzs** [comment]
This was fixed in the 1.10 release, PR #5196

/close
