### ISSUE TITLE
Kubedns 1.14.9 broke externalName services

### ISSUE THREAD

**Issue by ese** [kubernetes/kops#5165]
Kops version: 1.9.0

After updating to v1.14.9 with kops 1.9.0, externalName services are not resolving anymore. It is fixed in v1.14.10

https://github.com/kubernetes/dns/issues/224

**Comment by recollir** [comment]
This can be fixed manually with

```
kubectl set image deployment/kube-dns -n kube-system \
  kubedns=gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.10 \
  dnsmasq=gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.10 \
  sidecar=gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.10
```

and is already fixed in master: #5026
