### ISSUE TITLE
AWS: Cluster in the existing subnet of the second CIDR on VPС

### ISSUE THREAD

**Issue by VolodymyrCL** [kubernetes/kops#5174]
Hello,

I have a existing infrastructure in AWS - VPC and subnets. The VPC includes two CIDR
```
10.0.68.0/24
10.0.33.0/24
```

The VPC has a complex connections with the infrastructure of our partners (VPC peereng, VPN etc). Therefore, I want to use the existing CIDR, which is already integrated into the overall infrastructure.

10.0.68.0/24 is default CIDR for VPC, but this network have a low number of unused IPs.

I am trying to create a cluster on 10.0.33.0/24:

```
kops create cluster \
--name kube.dev.domain.net \
--dns private \
--dns-zone kube.dev.domain.net \
--zones us-east-1a \
--master-count 3 \
--master-size t2.medium \
--node-count 3 \
--node-size t2.medium \
--state s3://kube-kops \
--vpc vpc-id \
--network-cidr 10.0.33.0/24 \
--subnets subnet-id \
--admin-access 10.0.33.0/24 \
--ssh-access 10.0.33.0/24 \
--ssh-public-key /path/to/id_rsa.pub \
--yes
```

but I get the error
`W0516 12:02:40.640118 5575 executor.go:118] error running task "VPC/kube.dev.domain.net" (9m50s remaining to succeed): CIDR: Invalid value: "10.0.33.0/24": field is immutable: old="10.0.68.0/24" new="10.0.33.0/24"`

If I do not specify --network-cidr 10.0.33.0/24, I get error
`Spec.Subnets[0].CIDR: Invalid "10.0.33.0/24": Subnet "us-east-1a" had a CIDR "10.0.33.0/24" that was not a subnet of the NetworkCIDR "10.0.68.0/24"`

Is this configuration possible? If yes, where I make a mistake?

Thank you!

**Comment by huang-jy** [comment]
Have you considered _not_ specifying the CIDR but specifying the VPC of the one which has the CIDR you want to use?

**Comment by VolodymyrCL** [comment]
> Have you considered not specifying the CIDR but specifying the VPC of the one which has the CIDR you want to use?

Hello,

VPS consists of two CIDR
```
10.0.68.0/24 (default)
10.0.33.0/24
```

I want to use a non-default CIDR. If I do not specify --network-cidr 10.0.33.0/24, but specify VPC-ID and Subnet-ID (subnet is included in non-default CIDR 10.0.33.0/24), I get error
`Spec.Subnets[0].CIDR: Invalid "10.0.33.0/24": Subnet "us-east-1a" had a CIDR "10.0.33.0/24" that was not a subnet of the NetworkCIDR "10.0.68.0/24"`

**Comment by huang-jy** [comment]
So you have two CIDRs associated with the one VPC?

I suspect this could be the issue.

For example, my VPC has 10.10.0.0/16 and 10.20.0.0/16 CIDRs but the AWS CLI doesn't display the additional CIDRs:

````

**Comment by VolodymyrCL** [comment]
Hello,

> So you have two CIDRs associated with the one VPC?

Yes, I have two CIDRs associated with the one VPC. Command "aws ec2 --region us-east-1 describe-vpcs" displays such result

```
aws ec2 --region us-east-1 describe-vpcs --vpc-id VPC-ID --output json
{
    "Vpcs": [
        {
            "VpcId": "VPC-ID",
            "InstanceTenancy": "default",
            "Tags": [
                {
                    "Value": "Name of VPC ",
                    "Key": "Name"
                }
            ],
            "CidrBlockAssociationSet": [
                {
                    "AssociationId": "vpc-cidr-assoc-ID",
                    "CidrBlock": "10.0.68.0/24",
                    "CidrBlockState": {
                        "State": "associated"
                    }
                },
                {
                    "AssociationId": "vpc-cidr-assoc-ID",
                    "CidrBlock": "10.0.33.0/24",
                    "CidrBlockState": {
                        "State": "associated"
                    }
                }
            ],
            "State": "available",
            "DhcpOptionsId": "dopt-ID",
            "CidrBlock": "10.133.68.0/24",
            "IsDefault": false
        }
    ]
}
```

Probably kops uses the root CidrBlock parameter, not the subkey CidrBlockAssociationSet CidrBlock parameter.

**Comment by huang-jy** [comment]
Possible, I don't have a case myself where we used a double-associated VPC in production, or in test, so I haven't yet experienced this problem. I may give it a try when I next have an opportunity :+1:

**Comment by tbastos** [comment]
/remove-lifecycle stale

I have the exact same issue... can't use my existing VPC because my subnets are not in the primary CIDR block :(

**Comment by GMartinez-Sisti** [comment]
/remove-lifecycle stale

Hi! I'm having the same issue, and the same behaviour. I have a VPC with two IP ranges, I actually added the second range to accommodate the Kubernetes cluster. If I specify the default range in `network-cidr` and the second one in `additionalNetworkCIDRs`, the cluster will not bootstrap.

I pocked around the protokube container and I get an error where it's looking for resources in the default range, even though the masters and nodes are in the second one.

```json
{
  "CidrBlock": "10.200.0.0/23",
  "DhcpOptionsId": "dopt-xxxxxx",
  "State": "available",
  "VpcId": "vpc-0f7e56eec1xxxxxx",
  "InstanceTenancy": "default",
  "CidrBlockAssociationSet": [{
      "AssociationId": "vpc-cidr-assoc-xxxxxx",
      "CidrBlock": "10.200.0.0/23",
      "CidrBlockState": {
        "State": "associated"
      }
    },
    {
      "AssociationId": "vpc-cidr-assoc-xxxxxx",
      "CidrBlock": "10.200.20.0/23",
      "CidrBlockState": {
        "State": "associated"
      }
    }
  ],
  "IsDefault": false
}
```

**Comment by mi5guided** [comment]
I think the use of additionalNetworkCIDRs option solves this problem. 

See bottom of this issue:   https://github.com/kubernetes/kops/issues/5045
