### ISSUE TITLE
unable to ssh to Kubernetes nodes

### ISSUE THREAD

**Issue by sbisl** [kubernetes/kops#5183]
Unable to ssh to the kubernets cluster using the key which I provided while creating the cluster. I followed the issue #1876, and https://www.youtube.com/watch?v=PuNtfPWTp2g , still unable to resolve it. Can you please help me?

**kops version**
Version 1.9.0 (git-cccd71e67)

**kubectl version**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**cloud provider**
AWS
**Unable to shh 
root@ip-172-31-27-46:~# ssh admin@54.89.52.138
Permission denied (publickey)**

kops create cluster --name demo.k8s.local --zones us-east-1a --node-count 1 --node-size t2.xlarge --master-size t2.micro --yes

root@ip-172-31-27-46:~# kops get secrets --type sshpublickey admin
Using cluster from kubectl context: demo.k8s.local

TYPE            NAME    ID
SSHPublicKey    admin   74:a5:db:53:a7:ff:a4:97:22:bf:f2:c9:46:be:ed:c9

```
root@ip-172-31-27-46:~# kops delete secret --name demo.k8s.local sshpublickey admin
root@ip-172-31-27-46:~# kops create secret --name demo.k8s.local sshpublickey admin -i ~/.ssh/id_rsa.pub
root@ip-172-31-27-46:~# kops update cluster --yes

```
root@ip-172-31-27-46:~# kops get secrets --type sshpublickey admin
Using cluster from kubectl context: demo.k8s.local

TYPE            NAME    ID
SSHPublicKey    admin   74:a5:db:53:a7:ff:a4:97:22:bf:f2:c9:46:be:ed:c9

root@ip-172-31-27-46:~# ssh admin@54.89.52.138
Permission denied (publickey).

**Comment by sbisl** [comment]
Resolved

**Comment by Deniall** [comment]
Hey, did you find a fix or workaround for this? Cheers

**Comment by davoodece** [comment]
Hi all , I am facing same issue..Plz help me on this

ubuntu@ip-172-31-47-103:~$ kops version
Version 1.18.1 (git-453d7d96be)
ubuntu@ip-172-31-47-103:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
ubuntu@ip-172-31-47-103:~$ kops get secrets
Using cluster from kubectl context: myfirstcluster.k8s.local

TYPE            NAME                            ID
Keypair         apiserver-aggregator            6906870756980600052540834702
Keypair         apiserver-aggregator-ca         6906870745585074307343745552
Keypair         apiserver-proxy-client          6906870759887889296675705989
Keypair         ca                              6906870745197782195702414068
Keypair         etcd-clients-ca                 6906870749115024189705422631
Keypair         etcd-manager-ca-events          6906870749860958017607763062
Keypair         etcd-manager-ca-main            6906870743156363111210970230
Keypair         etcd-peers-ca-events            6906870747304553978991682742
Keypair         etcd-peers-ca-main              6906870750398044821475416098
Keypair         kops                            6906870760487770749245689529
Keypair         kube-controller-manager         6906870758549897822722605714
Keypair         kube-proxy                      6906870759427464905043081786
Keypair         kube-scheduler                  6906870760442155923285211855
Keypair         kubecfg                         6906870758068655111092208148
Keypair         kubelet                         6906870755907294482511936105
Keypair         kubelet-api                     6906870760608092489539594528
Keypair         master                          6906870808815597902685386786
SSHPublicKey    admin                           d0:27:6e:da:ed:a8:47:80:5a:4e:4e:60:3a:97:2b:ea
Secret          admin
Secret          kube
Secret          kube-proxy
Secret          kubelet
Secret          system:controller_manager
Secret          system:dns
Secret          system:logging
Secret          system:monitoring
Secret          system:scheduler
ubuntu@ip-172-31-47-103:~$ ssh -i ~/.ssh/id_rsa admin@35.154.181.194
admin@35.154.181.194: Permission denied (publickey).

**Comment by Deniall** [comment]
For me, what fixed it was sshing using the user for the specific system your node is running on. ie. if you are running CoreOS, the command/user you want is `ssh -i ~/.ssh/id_rsa core@35.154.181.194`. Ubuntu is different, debian is different again, etc. Hope that helps!
