### ISSUE TITLE
Cilium additional configuration

### ISSUE THREAD

**Issue by nebril** [kubernetes/kops#5201]
Current Cilium integration as a CNI plugin lacks some configuration options:

- [x] Cilium version (currently it's an older rc, it should be bumped to at least 1.0.3 and be made configurable
- [x] etcd tls configuration (provide the user with means to provide etcd secret via kops config)
- [x] all Cilium agent options as described here: http://docs.cilium.io/en/doc-1.0/cmdref/cilium-agent/ should be configurable from Kops

**Comment by tgraf** [comment]
@nebril Is this done?
