### ISSUE TITLE
Bastion volume size

### ISSUE THREAD

**Issue by Mosho1** [kubernetes/kops#5209]
1. Describe IN DETAIL the feature/behavior/change you would like to see.

I'd like to be able to control the size of the volume assigned to the bastion instance in kops. Also, is there a reason it needs as much as 32gb (the default value)?

**Comment by mikesplain** [comment]
Hi @Mosho1 you should be able to do what you want in by changing `rootVolumeSize: ` on the bastion instance group.  You can modify that by doing `kops edit ig bastion` or similar.

More details here:

https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#changing-the-root-volume-size-or-type

**Comment by lpf190** [comment]
@mikesplain this only for system volume ,what about https://github.com/kubernetes/kops/issues/4997
