### ISSUE TITLE
Support for --authentication-token-webhook in kubelet

### ISSUE THREAD

**Issue by igoratencompass** [kubernetes/kops#5212]
Same as in #5176, needed according to Prometheus docs.

**Comment by ihoegen** [comment]
I'll start working on that now

**Comment by ihoegen** [comment]
Hi @igoratencompass, I've created a PR regarding this. See #5231

**Comment by mikesplain** [comment]
Thanks @ihoegen closing.

**Comment by igoratencompass** [comment]
Thanks guys very much appreciated.

**Comment by david972** [comment]
@ihoegen it’s seems your PR concern API server not kubelet

**Comment by ihoegen-isp** [comment]
Fixed in https://github.com/kubernetes/kops/pull/5508, thanks

**Comment by ihoegen** [comment]
Fixed in #5508, thanks
