### ISSUE TITLE
Brew-installed zsh completions do not autoload

### ISSUE THREAD

**Issue by bdentino** [kubernetes/kops#5214]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.9.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
1.8.6

3. What cloud provider are you using?
N/A

4. What commands did you run?  What is the simplest way to reproduce this issue?
`brew install kops`

5. What happened after the commands executed?
kops autocompletions are installed as expected in `/usr/local/share/zsh/site-functions` but do not properly autoload.

6. What did you expect to happen?
kops autocompletions should be available when i open a new zsh session (using oh-my-zsh).

7. Please provide your cluster manifest.
N/A

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
N/A

9. Anything else do we need to know?
The fix for this is simple: add `#compdef kops` as the first line to the zsh completions, and `_complete kops 2>/dev/null` as the last line, following the pattern that kubectl uses for its own completions.

**Comment by ihoegen** [comment]
Hi @bdentino, I've opened a PR to implement this. See #5230
