### ISSUE TITLE
K8s API server address and Terraform

### ISSUE THREAD

**Issue by helloitsmyaccount** [kubernetes/kops#5215]
I've generated terraform templates via `kops` using this doc https://github.com/kubernetes/kops/blob/master/docs/terraform.md

```
$ kops create cluster ${KOPS_NAME} \
    --state $KOPS_STATE_STORE \
    --node-count 2 \
    --master-count 3 \
    --cloud aws \
    --topology private \
    --networking flannel \
    --out=. \
    --target=terraform
```
According to command above I am trying to create kubernetes with `private` topology and gossip-based (w/o normal external domain). Then I launched terraform:
```
$ terraform init
$ terraform apply
```
After that I am trying to check cluster status:

```
$ kops validate cluster
Using cluster from kubectl context: k8-cluster.k8s.local

Validating cluster k8-cluster.k8s.local

unexpected error during validation: error listing nodes: Get https://api.k8-cluster.k8s.local/api/v1/nodes: dial tcp: lookup api.k8-cluster.k8s.local on 8.8.8.8:53: no such host
```
This is because of wrong API address in `~/.kube/config`:
```
$ cat ~/.kube/config
...
    server: https://api.k8-cluster.k8s.local
...
```
I've tried to change this address to one of API ELB which I saw in AWS (https://api-k8-cluster-k8s-local-2g17hn-1534125689.eu-west-1.elb.amazonaws.com) but after I am getting:
```
$ kubectl get pods
```
```
Unable to connect to the server: x509: certificate is valid for api.internal.k8-cluster.k8s.local, api.k8-cluster.k8s.local, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not api-k8-cluster-k8s-local-2g17hn-1534125689.eu-west-1.elb.amazonaws.com
```
It's sad. Could someone have any hotfix or ideas?

**Comment by shashanksinha89** [comment]
I am facing the same issue as well.

**Comment by rdrgmnzs** [comment]
This is most likely caused by you using the `k8s.local` domain which triggers a gossip-based cluster as described in https://github.com/kubernetes/kops/blob/master/docs/aws.md which AFIK does not create DNS entries for your ELB and API servers.

The second error is because the SSL certs do not match `api-k8-cluster-k8s-local-2g17hn-1534125689.eu-west-1.elb.amazonaws.com`

**Comment by shashanksinha89** [comment]
@rdrgmnzs Agreed, there is a workaround which forces SSL certificate update for `gossip-based` cluster as well. Refer to this #2990.

@helloitsmyaccount this should solve your issue.

**Comment by helloitsmyaccount** [comment]
Thanks @shashanksinha89 you are right. That workaround is working well.

Better to close this issue as it is duplicate of #2990

**Comment by rdrgmnzs** [comment]
/close

Duplicates #2990
