### ISSUE TITLE
Can I change DNS Provider from kubedns to coredns in an existing cluster?

### ISSUE THREAD

**Issue by leeeboo** [kubernetes/kops#5224]
I found I can specific a dns provider when I creating a cluster in the docs

spec:
  kubeDNS:
    provider: CoreDNS

My question is:
I already have a cluster created by kops 1.9. How can I change the dnsprovider from kubedns to coredns?

Thanks!

**Comment by so0k** [comment]
coredns addon is not part of 1.9 release branch:

https://github.com/kubernetes/kops/tree/release-1.9/upup/models/cloudup/resources/addons

it is merged on master only: https://github.com/kubernetes/kops/tree/master/upup/models/cloudup/resources/addons

**Comment by mikesplain** [comment]
Yes, you can just edit the cluster, update cluster and coredns will start coming up. It will be behind the same service as kube-dns.  Then you can scale down kube-dns-autoscaler and kube-dns.

**Comment by leeeboo** [comment]
@mikesplain thanks!

**Comment by Sanjanare** [comment]
hi when i do kops edit cluster I get this 
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
-----------------
where should i place 
spec:
kubeDNS:
provider: CoreDNS

i use kops 1.10 version (new to k8s)

**Comment by Sanjanare** [comment]
I wanted to move from kube-dns to core-dns how can i add to the cluster to update with core-dns? ( iam  new to k8s please some one help me on this )
Thanks in advance
