### ISSUE TITLE
fileAssets and hooks not honored on Bastion roles

### ISSUE THREAD

**Issue by jaumann** [kubernetes/kops#5242]
KOPS VERSION
1.9.1

KUBERNETES VERSION
1.9.8

CLOUD PROVIDER
AWS

REPRO STEPS:
1. Set a fileAsset and hook in the cluster config and assign it to the Bastion, Node and Master roles
2. Deploy an IG with the Bastion Role
3. Deploy an IG with the Node Role
4. Deploy an IG with the Master Role

ACTUAL:
The bastion spins up, but no fileAssets are created and no hooks are issued. fileAssets and hooks are created just fine on the node and master IGs

EXPECTED:
The fileAsset would be created and the hook would be followed for the bastion, as it is on the node and master

CLUSTER MANIFEST: 
https://gist.github.com/jaumann/93a9aca4cf6fec8caa98498e7b8628e4

**Comment by mikesplain** [comment]
@jaumann Looks like that's skipped in the code unless you set `AdditionalUserData`. 

https://github.com/kubernetes/kops/blob/079989f8d48388a8de162cae48fa23a456542e5b/pkg/model/bootstrapscript.go#L95-L98

Can you try adding that to your bastion, to see if it helps? It may be something else, but thats an easy test

**Comment by ncgee** [comment]
Having the same issue (using 1.9.1 as well), adding `AdditionalUserData` does not have the desired effect unfortunately. For what it's worth, making any changes or updating the roles for an asset doesn't change the bastion launch configuration as indicated by terraform output.

**Comment by mikesimos** [comment]
/reopen
This should be fixed by #5856
Duplicate of  #3907

**Comment by tsuna** [comment]
Actually this isn't an exact dup of #3907 because looking at the PR in #5856 it seems that this is adding just support for defining hooks in the ig of the bastions. The cluster-wide fileAssets and hooks are still ignored for bastions from what I can tell.

**Comment by tsuna** [comment]
This seems to be related to `AWSNodeUpTemplate` not adding `nodeup.sh` on Bastion hosts since commit 6b38b2c3a64613f2d207767ad72c1b2f6d7277f2 (cc @duboisf).

**Comment by tsuna** [comment]
Looking at that commit a bit closer, I see that this wasn't working before anyway.

In any case this issue should be re-opened.  There is no PR currently that fixes it from what I can tell.

**Comment by jaumann** [comment]
/reopen

per @mikesimos and @tsuna. I'm no longer working with kops in my day job, but I hope this gets fixed for you all!
