### ISSUE TITLE
Add LogOpts to dockerconfig

### ISSUE THREAD

**Issue by scottbessler** [kubernetes/kops#526]
It would be very useful to be able to configure log-opts at a docker daemon level to ensure env variables (like HOSTNAME) end up in the log json.

**Comment by scottbessler** [comment]
(and I actually have whipped this change up if its useful at https://github.com/StrideSpark/kops/commit/9e1ad49fe8843a353b5ba206ae13e43d55f22fbc)

**Comment by chrislovecnm** [comment]
@scottbessler please submit a PR

**Comment by sstarcher** [comment]
@scottbessler any chance you can submit that as a PR

**Comment by chrislovecnm** [comment]
I think we may have a PR inbound for this
