### ISSUE TITLE
IAM Role tweak for end user flexibility

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#528]
I'm very happy that KOPS is tightening down the IAM roles.

However, could you add an exception for KOPS_STATE_STORE.  Instead of:

```
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::<KOPS_STATE_STORE>/<CLUSTER_NAME>",
        "arn:aws:s3:::<KOPS_STATE_STORE>/<CLUSTER_NAME>/*"
      ]
```

could you add:

```
        "arn:aws:s3:::<KOPS_STATE_STORE>/user/"
        "arn:aws:s3:::<KOPS_STATE_STORE>/user/*"
```

final version:

```
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::<KOPS_STATE_STORE>/<CLUSTER_NAME>",
        "arn:aws:s3:::<KOPS_STATE_STORE>/<CLUSTER_NAME>/*",
        "arn:aws:s3:::<KOPS_STATE_STORE>/user/",
        "arn:aws:s3:::<KOPS_STATE_STORE>/user/*"
      ]

```

so that there's a cubby hole in the profile where end users of kops might stash things of use (Kubernetes known user tokens, EIP IP allocations to shuffle, etc, etc)

**Comment by zapman449** [comment]
This is the master's IAM role to be clear.

**Comment by justinsb** [comment]
We have added an additional IAM role.  Is that sufficient, or would it more convenient also to have the user area?

The complexity with expanding the primary role is that I foresee that we will want to block most pods from accessing the node IAM role at all, using something like kube2iam.  But at that point, I wonder if we should simply define a separate IAM role anyway.

**Comment by chrislovecnm** [comment]
Closing - please reopen if needed
