### ISSUE TITLE
connection refused after starting a cluster

### ISSUE THREAD

**Issue by mgaruccio** [kubernetes/kops#5281]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
`Version 1.9.1 (git-ba77c9ca2)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
cluster is not accessible but it is trying to deploy 1.9.1

3. What cloud provider are you using?
GCE

4. What commands did you run?  What is the simplest way to reproduce this issue?
followed - https://github.com/kubernetes/kops/blob/master/docs/tutorial/gce.md

5. What happened after the commands executed?
Everything seemed to work but `kubectl get nodes` returns `The connection to the server xxx.xxx.xxx.xxx was refused`

6. What did you expect to happen?
expected a new simple cluster

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
➜ kops get --name simple.k8s.local -o yaml --state gs://kubernetes-clusters-garuccio/
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-06-06T04:06:46Z
  name: simple.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: gce
  configBase: gs://kubernetes-clusters-garuccio/simple.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east1-d
      name: d
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east1-d
      name: d
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.6
  masterPublicName: api.simple.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: k8s-cluster-206323
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: us-east1
    region: us-east1
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-06T04:06:47Z
  labels:
    kops.k8s.io/cluster: simple.k8s.local
  name: master-us-east1-d
spec:
  image: cos-cloud/cos-stable-64-10176-62-0
  machineType: n1-standard-1
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east1-d
  role: Master
  subnets:
  - us-east1
  zones:
  - us-east1-d

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-06T04:06:48Z
  labels:
    kops.k8s.io/cluster: simple.k8s.local
  name: nodes
spec:
  image: cos-cloud/cos-stable-64-10176-62-0
  machineType: n1-standard-2
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east1
  zones:
  - us-east1-d

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
gist - https://gist.github.com/mgaruccio/14233a8f8654160ccedab9589cdebd4a

9. Anything else do we need to know?
gcloud compute instances list shows the nodes and I am able to ssh into the master.  once there systemctl is showing that docker is not starting with the following error - `unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: storage-driver: (from flag: overlay, from file: overlay2)`

**Comment by antonsoroko** [comment]
Hi.
I had the same issue. As I can see this problem is caused by new `cos-cloud` images. I have reverted to `cos-cloud/cos-stable-60-9592-90-0` which does not have `/etc/docker/daemon.json`.

**Comment by azurewraith** [comment]
Confirmed also on GCE, switching the instancegroup images to `cos-cloud/cos-stable-60-9592-90-0` on both `master` and `nodes` resolved it for me...
