### ISSUE TITLE
Connect to AWS k8s cluster from another machine ?

### ISSUE THREAD

**Issue by kocoten1992** [kubernetes/kops#5288]
1. What `kops` version are you running? 
Version 1.9.1 (git-ba77c9ca2)
2. What Kubernetes version are you running? 
GitVersion:"v1.10.3"
3. What cloud provider are you using?
AWS
4. What commands did you run?  What is the simplest way to reproduce this issue?
kubectl -v 10 get pods
5. What happened after the commands executed?
```
I0607 17:48:06.487717    3600 loader.go:357] Config loaded from file /home/username/.kube/config
I0607 17:48:06.488485    3600 factory_object_mapping.go:83] Unable to get a discovery client to find server resources, falling back to hardcoded types: tls: failed to find any PEM data in certificate input
F0607 17:48:06.488939    3600 helpers.go:119] error: tls: failed to find any PEM data in certificate input
```
6. What did you expect to happen?
Show more detail, couldn't debug from here

9. Anything else do we need to know?
* I created a aws k8s cluster with kops using computer A
* Now I need to connect to that k8s cluster using computer B (to use ```kubectl```)

I tried this https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/ , not working and the error message doesn't help.

Could you show how to achieve that, and maybe more specific on error message too :) (which file was missing, etc...)

Thank you.

**Comment by gonzalez** [comment]
Looks like its having issues finding the certificates 
Check to make sure the files referenced in your kubeconfig exist on your local machine.
`3600 factory_object_mapping.go:83] Unable to get a discovery client to find server resources, falling back to hardcoded types: tls: failed to find any PEM data in certificate input
F0607 17:48:06.488939    3600 helpers.go:119] error: tls: failed to find any PEM data in certificate input
`

**Comment by kocoten1992** [comment]
@gonzalez OMG, on the first copy somehow ```certificate-authority-data``` field on .kube/config wasn't copy, I manually copy it, everything work now :face_with_head_bandage: .

Thank you @gonzalez :smile: .
