### ISSUE TITLE
Rolling update Master DNS issue

### ISSUE THREAD

**Issue by Reinkaos** [kubernetes/kops#5289]
Hey!

This is my first issue so sorry if it is already known or already captured, I couldn't see it when I was searching through the issues. 

1. kops version 1.9

2. Kubernetes 1.9.3

3. Cloud Provider: AWS

4. kops rolling-update cluster --yes

5. A rolling update was triggered but the DNS entries for the API and the internal API were not changed to point to the new node, so the cluster could not be validated and it did not carry on with updating until after the entries were manually updated. 

6. The rolling update to update the Route 53 DNS entries for the API (public and internal). 

Thanks!

Richard

**Comment by igorvpcleao** [comment]
Facing the same problem here. When I need to update my master I have to get its new public ip and manually change it on Route 53.
