### ISSUE TITLE
Support customizing LoadBalancer in Cluster.spec

### ISSUE THREAD

**Issue by tongda** [kubernetes/kops#5299]
According to the [code](https://github.com/kubernetes/kops/blob/1a4bd10097739edf1cbacd11c828670096259bee/pkg/model/awsmodel/api_loadbalancer.go#L115), by default, API LoadBalancer will listen on default Https port (443). However, in some places, such as China, 80 and 443 are forbidden from public internet until we put our information on record to government. But since the k8s cluster are mainly used as our internal cluster, we would prefer to use an alternative port instead of 443, such as 8888.

We have tested that setting balancer listener to port 8888 and forward to 443 of k8s apiserver could work. But every time we run `kops update cluster`, the k8s config will be modified to default port.

I suggest to add a field in cluster.spec like this:

```yaml
spec:
  api:
    loadBalancer:
      port: 8888
```

Then in the code of generating AWS ELB:

```
Listeners: map[string]*awstasks.LoadBalancerListener{
    lbSpec.Port: {InstancePort: 443},
}
```

**Comment by thedarkfalcon** [comment]
Lack of customisation of ELB in cluster.spec is extremely annoying.
Everyone of our clusters will always be running additional services on different ports, I would have liked to have been able to edit the cluster.spec to also allow access to these ports via the default load balancer without post hoc changes.

**Comment by tongda** [comment]
@justinsb Excuse me for bother you. Just wonder whether this feature could be considered. Thanks.

**Comment by mwocka** [comment]
@hakman could you take a look on this issue. It could be easy to fix.
