### ISSUE TITLE
Issues with Dep 

### ISSUE THREAD

**Issue by gambol99** [kubernetes/kops#5300]
Adding this as a reference .. when trying to update the dep I hit two issues 

a) `package vbom.ml/util: unrecognized import path "vbom.ml/util" (https fetch: Get https://vbom.ml/util?go-get=1: dial tcp: lookup vbom.ml on 8.8.4.4:53: read udp 172.22.85.132:58935->8.8.4.4:53: i/o timeout)` where the vbom.ml domain is not resolvable by certain dns providers 

To resolve the above I had to manually enter 
```shell
$ cat /etc/hosts | grep .ml
104.31.76.40    vbom.ml
```
b) The `bitbucket.org/ww/goautoneg` fails to download, though `dep` just hangs without giving an answer why. After doing a `go get bitbucket.org/ww/goautoneg` it's due to 

```shell
$ go get bitbucket.org/ww/goautoneg
go: missing Mercurial command. See https://golang.org/s/gogetcmd
package bitbucket.org/ww/goautoneg: exec: "hg": executable file not found in $PATH
```
I was resolved by installing mercurial ..

**Comment by idealhack** [comment]
Thanks, I ran to b) as well. It seems like this has to be fixed by dep.

ref: golang/dep#1643
