### ISSUE TITLE
CoreDNS not working on current master branch

### ISSUE THREAD

**Issue by quater** [kubernetes/kops#5314]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

       Version 1.9.0 (git-c64c167e7)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

       #  kubectl version
       Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?

       AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

       kops update cluster $CLUSTERNAME --yes --state s3://$BUCKETNAME

5. What happened after the commands executed?

       error building tasks: error remapping manifest addons/coredns.addons.k8s.io/k8s-1.6.yaml: error parsing yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this contex

6. What did you expect to happen?

      Expected the command to succeed and Kubernetes cluster being created with CoreDNS as default service discovery

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

CoreDNS was configured as documented with
https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md

       spec:
           kubeDNS:
               provider: CoreDNS

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

https://gist.github.com/quater/30998abde75940fc0d9698b8e98c1f2a

9. Anything else do we need to know?

I am aware that this is currently under development but expected the current state to work in Master branch.

**Comment by quater** [comment]
Looking at the commit history, I believe @rajansandeep could help?

**Comment by rajansandeep** [comment]
@quater thank you for catching this. 
Looks like there was an error in the CoreDNS deployment yaml.
I'll submit a PR shortly to fix this.
