### ISSUE TITLE
Use the kubedns provider: CoreDNS, save and report an error

### ISSUE THREAD

**Issue by ti-yoyo** [kubernetes/kops#5326]
kops version: Version 1.9.0 (git-06224f298)

kubeDNS:
    provider: CoreDNS
    replicas: 2
    serverIP: 100.64.0.10
  

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x510206]

goroutine 1 [running]:
net.networkNumberAndMask(0x0, 0xc420b367a8, 0x511296, 0xc4208a75d9, 0x2, 0xc4203de490, 0x10)
	/usr/local/go/src/net/ip.go:449 +0x26
net.(*IPNet).Contains(0x0, 0xc4203de490, 0x10, 0x10, 0x10)
	/usr/local/go/src/net/ip.go:473 +0x2f
k8s.io/kops/pkg/apis/kops/validation.ValidateCluster(0xc420179000, 0x4b00000000000000, 0x8)
	/usr/local/go/work/src/k8s.io/kops/pkg/apis/kops/validation/legacy.go:282 +0xa11
k8s.io/kops/upup/pkg/fi/cloudup.(*populateClusterSpec).run(0xc420b3a620, 0x524e220, 0xc420cf7dc0, 0xc4204b8000, 0xc4201791e0)
	/usr/local/go/work/src/k8s.io/kops/upup/pkg/fi/cloudup/populate_cluster_spec.go:88 +0x69
k8s.io/kops/upup/pkg/fi/cloudup.PopulateClusterSpec(0x524e220, 0xc420cf7dc0, 0xc420179000, 0xc4202eb440, 0x0, 0x0, 0x0)
	/usr/local/go/work/src/k8s.io/kops/upup/pkg/fi/cloudup/populate_cluster_spec.go:70 +0xa3
main.RunEditCluster(0xc420cf6fe0, 0xc420d17900, 0xc4202ac870, 0x1, 0x1, 0x5224060, 0xc42000e018, 0x549d070, 0x0, 0x0)
	/usr/local/go/work/src/k8s.io/kops/cmd/kops/edit_cluster.go:211 +0xce7
main.NewCmdEditCluster.func1(0xc420d17900, 0xc4202ac870, 0x1, 0x1)
	/usr/local/go/work/src/k8s.io/kops/cmd/kops/edit_cluster.go:71 +0x71
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc420d17900, 0xc4202ac810, 0x1, 0x1, 0xc420d17900, 0xc4202ac810)
	/usr/local/go/work/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:757 +0x2b9
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x546ba20, 0x549d000, 0x0, 0x0)
	/usr/local/go/work/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:843 +0x37e
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x546ba20, 0x549d070, 0x0)
	/usr/local/go/work/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.Execute()
	/usr/local/go/work/src/k8s.io/kops/cmd/kops/root.go:94 +0x9b
main.main()
	/usr/local/go/work/src/k8s.io/kops/cmd/kops/main.go:25 +0x20

**Comment by ihoegen** [comment]
```

**Comment by ihoegen** [comment]
Reformatted for readability 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x510206]

goroutine 1 [running]:
net.networkNumberAndMask(0x0, 0xc420b367a8, 0x511296, 0xc4208a75d9, 0x2, 0xc4203de490, 0x10)
/usr/local/go/src/net/ip.go:449 +0x26
net.(*IPNet).Contains(0x0, 0xc4203de490, 0x10, 0x10, 0x10)
/usr/local/go/src/net/ip.go:473 +0x2f
k8s.io/kops/pkg/apis/kops/validation.ValidateCluster(0xc420179000, 0x4b00000000000000, 0x8)
/usr/local/go/work/src/k8s.io/kops/pkg/apis/kops/validation/legacy.go:282 +0xa11
k8s.io/kops/upup/pkg/fi/cloudup.(*populateClusterSpec).run(0xc420b3a620, 0x524e220, 0xc420cf7dc0, 0xc4204b8000, 0xc4201791e0)
/usr/local/go/work/src/k8s.io/kops/upup/pkg/fi/cloudup/populate_cluster_spec.go:88 +0x69
k8s.io/kops/upup/pkg/fi/cloudup.PopulateClusterSpec(0x524e220, 0xc420cf7dc0, 0xc420179000, 0xc4202eb440, 0x0, 0x0, 0x0)
/usr/local/go/work/src/k8s.io/kops/upup/pkg/fi/cloudup/populate_cluster_spec.go:70 +0xa3
main.RunEditCluster(0xc420cf6fe0, 0xc420d17900, 0xc4202ac870, 0x1, 0x1, 0x5224060, 0xc42000e018, 0x549d070, 0x0, 0x0)
/usr/local/go/work/src/k8s.io/kops/cmd/kops/edit_cluster.go:211 +0xce7
main.NewCmdEditCluster.func1(0xc420d17900, 0xc4202ac870, 0x1, 0x1)
/usr/local/go/work/src/k8s.io/kops/cmd/kops/edit_cluster.go:71 +0x71
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc420d17900, 0xc4202ac810, 0x1, 0x1, 0xc420d17900, 0xc4202ac810)
/usr/local/go/work/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:757 +0x2b9
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x546ba20, 0x549d000, 0x0, 0x0)
/usr/local/go/work/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:843 +0x37e
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x546ba20, 0x549d070, 0x0)
/usr/local/go/work/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.Execute()
/usr/local/go/work/src/k8s.io/kops/cmd/kops/root.go:94 +0x9b
main.main()
/usr/local/go/work/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```

**Comment by subnova** [comment]
I think this occurs when serviceClusterIPRange has not been set.  So setting this field maybe a workaround.
