### ISSUE TITLE
kopeio-networking-agent doesn't run on nodes which have custom taints

### ISSUE THREAD

**Issue by njuettner** [kubernetes/kops#5329]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

```
kops 1.9.1
```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?

```
AWS
```

4. What commands did you run?  What is the simplest way to reproduce this issue?

```
kubectl get ds kopeio-networking-agent -o yaml -n kube-system
```

5. What happened after the commands executed?

It only tolerates running on kubernetes master nodes

```
...
 tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
...
```

6. What did you expect to happen?

I expect that this daemon should run on every node (incl. nodes with different taints).

9. Anything else do we need to know?

The problem is here:

https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.6.yaml#L38-L40

I would propose to change it to:

```
tolerations:
- operator: "Exists"
```

**Comment by justinsb** [comment]
Ooops - need to fix this!
