### ISSUE TITLE
Wrong cluster-cidr set with aws-vpc-routed-eni

### ISSUE THREAD

**Issue by lwr20** [kubernetes/kops#5337]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
```
Version 1.9.1 (git-ba77c9ca2)
```
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
`1.9.6`
3. What cloud provider are you using?
`aws`
4. What commands did you run?  What is the simplest way to reproduce this issue?
```
kops create cluster --cloud aws --state s3://mybucket --zones us-west-2a --networking amazon-vpc-routed-eni --node-count=2 --name lwr-test.k8s.local --yes
```
This bit is probably irrelevant, but once cluster came up, I updated it to use the latest amazon aws-vpc-cni plugin with:
```
kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.0/config/v1.0/aws-k8s-cni-calico.yaml
```
I then tried out network policy:
```
$kubectl create ns policy-demo
$kubectl run --namespace=policy-demo nginx --replicas=2 --image=nginx
$kubectl expose --namespace=policy-demo deployment nginx --port=80
$kubectl create -f - <<EOF
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-nginx
  namespace: policy-demo
spec:
  podSelector:
    matchLabels:
      run: nginx
  ingress:
    - from:
      - podSelector:
          matchLabels:
            run: access
EOF
$kubectl run --namespace=policy-demo access --rm -ti --image busybox /bin/sh
Waiting for pod policy-demo/access-472357175-y0m47 to be running, status is Pending, pod ready: false

If you don't see a command prompt, try pressing enter.

/ # wget -q --timeout=5 nginx -O -
```
5. What happened after the commands executed?
6. What did you expect to happen?
At this point instead of the "access" pod being able to contact the service as expected, I found that the `wget` would timeout about 50% of the time.

Getting tcpdump from the nodes, I see that the successful wgets were when the service directed the traffic to the pod on the same node as the "access" pod.  The failures were from when the service directed the traffic to the "nginx" pod on the other node (and kube-proxy was NATting the traffic, causing the network policy rule to drop the traffic).  This suggested kube-proxy config error to me. 

Looking at the yaml for the kube-proxy pods, I see that they all have `--cluster-cidr=172.20.128.0/17`.  Looking at the pods on my system, I see that they all have IPs in the 172.20.0.0/17 subnet.
```
$ kubectl get po -n policy-demo -o wide
NAME                      READY     STATUS    RESTARTS   AGE       IP              NODE
access-57dd55ff64-fj94j   1/1       Running   0          42m       172.20.43.0     ip-172-20-38-237.us-west-2.compute.internal
nginx-8586cf59-m6p2g      1/1       Running   0          42m       172.20.38.4     ip-172-20-38-237.us-west-2.compute.internal
nginx-8586cf59-ptlws      1/1       Running   0          42m       172.20.44.187   ip-172-20-58-128.us-west-2.compute.internal
```
I think this is wrong - those pod IPs need to be inside the cluster-cidr.  So either kops is configuring kube-proxy with the wrong cluster-cidr or the aws-vpc-routed-eni plugin is assigning pod IPs in the wrong cidr.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
$ kops get --name lwr-test.k8s.local --state=s3://mybucket  -o yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-06-15T14:53:43Z
  name: lwr-test.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://mybucket/lwr-test.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.6
  masterPublicName: api.lwr-test.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 172.20.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-15T14:53:43Z
  labels:
    kops.k8s.io/cluster: lwr-test.k8s.local
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-15T14:53:44Z
  labels:
    kops.k8s.io/cluster: lwr-test.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a

```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

I'll delete the cluster and get these now.

9. Anything else do we need to know?

**Comment by lwr20** [comment]
Output of create cluster with verbose logging:
https://gist.github.com/lwr20/0365480cf3398b64631045d7c085be42

**Comment by lwr20** [comment]
Rats.  Looks like I've raised a dupe of https://github.com/kubernetes/kops/issues/4674

**Comment by lwr20** [comment]
Found a workaround: simply override the clusterCIDR.

In my case that meant: Create the cluster data with `kops create`, then edit the config with `kops edit`.  Add 
```
  kubeControllerManager:
    clusterCIDR: 172.20.0.0/16
  kubeProxy:
    clusterCIDR: 172.20.0.0/16
```
to the `spec` section of the config, then run `kops update ... --yes` to actually create the cluster.

**Comment by spikecurtis** [comment]
I believe #5579 fixes this issue.
