### ISSUE TITLE
New logo has incorrect number of handles

### ISSUE THREAD

**Issue by Raffo** [kubernetes/kops#5342]
According to the Kubernetes tradition, the logo should have 7 handles and the new one has only 6. This is not a coincidence, but actually intended as explained [here](https://cloudplatform.googleblog.com/2016/07/from-Google-to-the-world-the-Kubernetes-origin-story.html). We should update the logo to have 7 to really be part of the Kubernetes ecosystem 😉

**Comment by kris-nova** [comment]
Could not agree enough with this one - (please don’t share this) but I’m actually pretty good with Gimp if anyone is interested in me taking a stab at mutating the new logo.

Any idea where we can get the original rendering?
