### ISSUE TITLE
How to enable "enable-aggregator-routing" in kube-apiserver

### ISSUE THREAD

**Issue by kostabr** [kubernetes/kops#5345]
Hi, 

Not sure if it's the correct place but will try it as well. 

I'm using kops 1.9 ( Version 1.9.0 (git-84c40f24b) ) and k8 1.9. on AWS.

I'm trying to find a way to enable the following kubeAPI flag "--enable-aggregator-routing=true". 

Checking the docs etc.. I tried via the cluster spec but it seems that its no supported, i couldn't find it in the godocs. 
when adding the cluster manifest and doing kops apply, update etc ... the flag is basically ignored. 

any ideas? 
what is the correct way to provide flags to the kops api?

Thanks in advancee

**Comment by gambol99** [comment]
hi @kostabr ... it would need to be added to the component config of the kube-apiserver https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L203-L339 .. what does this option provide out of interest?

**Comment by kostabr** [comment]
Hi @gambol99 , thanks for the quick answer.

long story short, on our cluster I see a lot of timeouts for requests to the api server ( no route to host etc ... ) and i do see the kube-apiserver spiking for cpu and the memory is high as well. 
The mentioned option can be route aggregator requests to endoints IP rather than cluster IP, so based 

[56430](https://github.com/kubernetes/kubernetes/issues/56430) there are similar reports and some users reported good results with enabling the option.

thanls
