### ISSUE TITLE
add support upgrade from (kube-up) 1.3 --> 1.4 kops

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kops#535]
Please add support for upgrading clusters created with kube-up 1.3.4 to use kops 1.4.

**Comment by dmcnaught** [comment]
Yes, should we follow the same instructions as for 1.2 to kops 1.3?
https://github.com/kubernetes/kops/blob/master/docs/upgrade_from_k8s_12.md
Thanks

**Comment by keglevich3** [comment]
IMO we should

**Comment by chrislovecnm** [comment]
@justinsb can you comment on this?  @kris-nova and myself are not familiar with the kube-up.sh import.

**Comment by justinsb** [comment]
Yes, it works from 1.3 as well.

The downside is that I think you have to build from master right now, as I think some bugs crept in (in particular that it will immediately reject the import attempt because the old name isn't a valid DNS name)

**Comment by justinsb** [comment]
That will be fixed when we do the next release though!

**Comment by justinsb** [comment]
Verified as working, with fixes in #1699

**Comment by justinsb** [comment]
Tested as working in the imminent kops 1.5.0

**Comment by chrislovecnm** [comment]
Closing - please open if needed
