### ISSUE TITLE
KOPS DNS issue in GCP 

### ISSUE THREAD

**Issue by dugwa** [kubernetes/kops#5355]
KOPS Version --> 1.9.1 (git-ba77c9ca2)
Kubernetes version  ---> v1.9.6
Cloud Provider ---> Google Compute Platform 

I tried to create a cluster with these commands 
kops create cluster \
        --name=my-domain-name.tld \
        --zones europe-west2-a \
        --state gs://bucket-name/ \
        --project=project-name\
        --node-count=2 \
        --cloud=gce \
        --yes
***please note that I have masked my personal details***

The commands executed successfully and intact I can see my VMs in GCP with no errors. I can also see the DNS records of the cluster with the placeholder address. 

However, when I run a kops validate cluster command I get this output 
INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-europe-west2-a	Master	n1-standard-1	1	1	europe-west2
nodes			Node	n1-standard-2	2	2	europe-west2

NODE STATUS
NAME	ROLE	READY

VALIDATION ERRORS
KIND	NAME		MESSAGE
dns	apiserver	Validation Failed

The dns-controller Kubernetes deployment has not updated the Kubernetes cluster's API DNS entry to the correct IP address.  The API DNS IP address is the placeholder address that kops creates: 203.0.113.123.  Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate.  The protokube container and dns-controller deployment logs may contain more diagnostic information.  Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to start.

Validation Failed

This cluster was created with google service account that has admin access to every resource so I expected the correct DNS entries to be created and the cluster to validate

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-06-20T09:32:19Z
  name: my-cluster-name
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: gce
  configBase: gs://my-bucknet-name/object-folder
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-europe-west2-a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-europe-west2-a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.6
  masterPublicName: api.my-domain-name
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: kops-207711
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: europe-west2
    region: europe-west2
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

**Comment by nivedhan-murugavel** [comment]
Hi @dugwa You need to wait for sometime. As mentioned in error, it will take sometime for cluster to be up and running

**Comment by dugwa** [comment]
@nivedhan-murugavel 

thanks for your reply but I have been waiting for the last 2 hours and still it as not validated
