### ISSUE TITLE
Docs misleading

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#536]
As reported on slack:

> it’s simply that under the heading "Other interesting modes:”, all of the flags bar —target are relevant to  “kops create cluster”, where as —target=terraform is used with kops update cluster

**Comment by itskingori** [comment]
@justinsb have a look at PR https://github.com/kubernetes/kops/pull/1763 ... which attempts to improve Terraform docs. I've done my best to make things clearer.

**Comment by chrislovecnm** [comment]
Closing due to comment above
