### ISSUE TITLE
risks of upgrading an existing cluster to AWS long resource IDs?

### ISSUE THREAD

**Issue by danielkrainas** [kubernetes/kops#5361]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

Cluster A: 1.7
Cluster B: 1.8

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Cluster A: 1.7
Cluster B: 1.8

3. What cloud provider are you using?

AWS

None of the other questions applied. I only wanted to know if anyone else has had experience migrating an existing AWS kops cluster to the new amazon long ID format and if so, were there any risks/pitfalls involved? Sorry if this isn't the forum for such a question. I can redirect.

**Comment by justinsb** [comment]
I'm not aware of anyone that has experienced any problems.

**Comment by danielkrainas** [comment]
For posterity, there was no interruption to service or anything noticeable during or after changing id formats.
