### ISSUE TITLE
Kops should provision nodes with docker-ce instead of docker-engine

### ISSUE THREAD

**Issue by wskinner** [kubernetes/kops#5368]
1. What `kops` version are you running? The command `kops version`, will display
 this information. 
Version 1.8.1 (git-94ef202)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
v1.8.11

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
I have created an instance group based on my custom AMI, and scaled that group to 1 using `kops edit ig`.

5. What happened after the commands executed?
The instance gets created, but nodeup doesn't complete. The reason is that my custom AMI has docker-ce, as this is a dependency for nvidia-docker2. Kops is trying to install docker-engine, which conflicts with docker-ce.
```Jun 22 02:27:35 ip-172-20-50-166 nodeup[1477]: W0622 02:27:35.179587    1477 executor.go:109] error running task "Package/docker-engine" (8759h59m58s remaining to succeed): error installing package "docker-engine": exit status 1: Select
Jun 22 02:27:35 ip-172-20-50-166 nodeup[1477]: dpkg: regarding .../nodeup/packages/docker-engine containing docker-engine:
Jun 22 02:27:35 ip-172-20-50-166 nodeup[1477]:  docker-ce conflicts with docker-engine
Jun 22 02:27:35 ip-172-20-50-166 nodeup[1477]:   docker-engine (version 1.13.1-0~debian-stretch) is to be installed.
Jun 22 02:27:35 ip-172-20-50-166 nodeup[1477]: dpkg: error processing archive /var/cache/nodeup/packages/docker-engine (--install):
Jun 22 02:27:35 ip-172-20-50-166 nodeup[1477]:  conflicting packages - not installing docker-engine
Jun 22 02:27:35 ip-172-20-50-166 nodeup[1477]: Errors were encountered while processing:
Jun 22 02:27:35 ip-172-20-50-166 nodeup[1477]:  /var/cache/nodeup/packages/docker-engine
```

6. What did you expect to happen?
Nodeup should either continue past this issue (treat it as a warning and not an error) or should provision with docker-ce by default, as docker-engine is deprecated.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
```apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-06-16T00:30:51Z
  name: staging2.my-cluster
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://my-cluster/staging2.my-cluster
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.11
  masterPublicName: api.staging2.my-cluster
  networkCIDR: 172.20.0.0/16
  networking:
    kuberouter: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-14T00:58:30Z
  labels:
    kops.k8s.io/cluster: staging2.my-cluster
  name: gpu-nodes2
spec:
  image: my-aws-account-id/debian-stretch-cuda9.2
  kubelet:
    featureGates:
      DevicePlugins: "true"
  machineType: p2.xlarge
  maxSize: 20
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: gpu-nodes2
  role: Node
  subnets:
  - us-west-2a
  taints:
  - engineml.com/needs-gpu=true:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-16T00:30:51Z
  labels:
    kops.k8s.io/cluster: staging2.my-cluster
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-16T00:30:51Z
  labels:
    kops.k8s.io/cluster: staging2.my-cluster
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by justinsb** [comment]
Each version of kubernetes is validated with a handful of docker versions.  Kubernetes 1.8 was validated with 1.11.2, 1.12.6, 1.13.1, and 17.03.2 according to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.8.md#external-dependencies

kops chose 1.13.1 for 1.8.  For 1.9 and higher though, we're using 17.03.2, so I think this should work.

We try to control the docker version carefully because there are often subtle bugs / differences in between the different versions.

**Comment by wskinner** [comment]
@justinsb is there any way to configure kops to skip installing docker? I would like to avoid upgrading my kubernetes version if possible. My current workaround is to provision a node with kops, then ssh into it and install docker-ce and nvidia-docker. Since my use case involves creating man clusters, this manual overhead can get annoying.
