### ISSUE TITLE
Easy way to configure CNI and/or weave

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#537]
Per the docs here: https://www.weave.works/weave-net-kubernetes-integration/

We should set network provider to CNI.

Either:

1) Add a CNI option to external

or 

2) Add a 'weave' option that also creates the daemonset

Or both!

**Comment by caseydavenport** [comment]
I'd throw my vote in for option 1), or similar.  Weave isn't the only networking option that uses `--network-plugin=cni` and can be installed via a DaemonSet (kope-routing, Calico, Canal) and there will certainly be more.  Additionally, the plan for kubenet is to move it _out_ of the kubelet into a CNI plugin, making `--network-plugin=cni` apply for kubenet as well.

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/pull/621 should solve this

**Comment by chrislovecnm** [comment]
Done with weave and kopeio-vxlan
