### ISSUE TITLE
Error from 1.10: "Unable to read bucket encryption policy"

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#5370]
When using an AWS bucket:

`Unable to read bucket encryption policy: will encrypt using AES256`

**Comment by mikesplain** [comment]
@justinsb I don't think this is an issue, we simply warn if there's no policy set here:

https://github.com/kubernetes/kops/blob/3489ea317e7fe705ccb7ebf55fe18c873fe9754e/util/pkg/vfs/s3context.go#L210

Any concerns?

**Comment by mikesplain** [comment]
Although now that I've ran it a few times, we throw that an awful lot. Maybe we should put a note in the release notes that we encrypt with AES256 unless an encryption policy is already defined?

**Comment by mikesplain** [comment]
This is actually showing up quite a bit so I've opened a PR above to reduce it's logging to debug.
