### ISSUE TITLE
efk addon v1.7.0 cannot work, elasticsearch cannot be started up because vm.max_map_count is too low

### ISSUE THREAD

**Issue by johnzheng1975** [kubernetes/kops#5372]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.8

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
1.9.5

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
```
kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/logging-elasticsearch/v1.7.0.yaml
```

5. What happened after the commands executed?
elasticsearch pod cannot be started up since below exception.
```
kubectl logs elasticsearch-logging-0 -n kube-system
```
```
[2018-06-22T10:42:07,532][INFO ][o.e.b.BootstrapChecks    ] [elasticsearch-logging-0] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```
6. What did you expect to happen?
EFK can be created successfully

**Comment by ipeacocks** [comment]
Hi, @johnzheng1975 
I've tried EFK addon and it works just fine. Which OS are you using for kubernetes hosts? How much memory do you have?

**Comment by johnzheng1975** [comment]
My k8s host is coreos. By default only 65530.  
virtual memory areas vm.max_map_count [65530]

**Comment by justinsb** [comment]
I wasn't able to reproduce this: I created a cluster with `kops create cluster cluster.example.com --zones us-east-1c  --image ami-f6ecac89`.  When I SSHed to the node it had the higher max_map_count:

```
> sysctl vm.max_map_count                                                                                                                                                                   
vm.max_map_count = 262144   
```

Which image are you running with?  Do you have any unusual options on your cluster creation?  Does `/etc/sysctl.d/99-k8s-general.conf` on your instances have the `max_map_count` line?  (`grep max_map /etc/sysctl.d/99-k8s-general.conf`)
