### ISSUE TITLE
1.4 + classic is broken; force upgrade to kubenet?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#538]
It seems that 1.4 + classic is broken: https://github.com/kubernetes/kubernetes/issues/33789

We should likely force an upgrade to kubenet when we upgrade to k8s 1.4, to prevent users having broken clusters.

**Comment by luxas** [comment]
This should be a top priority IMO, we might have removed the legacy networking as well in v1.5

**Comment by luxas** [comment]
Oops, seems like you've made the changes required, maybe just close this issue?

**Comment by chrislovecnm** [comment]
Closing.
