### ISSUE TITLE
error draining node Unknown controller kind Certificate

### ISSUE THREAD

**Issue by kostyrev** [kubernetes/kops#5383]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.9.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
`Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:35:40Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

- deploy cert-manager with [helm](https://cert-manager.readthedocs.io/en/latest/getting-started/2-installing.html#with-helm)
- issue certificate
- then try to perform rolling update of the cluser with draining enabled:
```
export KOPS_FEATURE_FLAGS="+DrainAndValidateRollingUpdate"
kops rolling-update cluster ${NAME} --yes
```

5. What happened after the commands executed?
```
I0626 19:34:06.360306    9180 instancegroups.go:157] Draining the node: "ip-10-0-215-34.ec2.internal".
node "ip-10-0-215-34.ec2.internal" cordoned
node "ip-10-0-215-34.ec2.internal" cordoned
error: unable to drain node "ip-10-0-215-34.ec2.internal", aborting command...

There are pending nodes to be drained:
 ip-10-0-215-34.ec2.internal

failed to drain node "ip-10-0-215-34.ec2.internal": error draining node: Unknown controller kind "Certificate": cm-acme-http-solver-g85cr, cm-acme-http-solver-g85cr
```

6. What did you expect to happen?
I expected it to perform a proper rolling restart

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

I think it's irrelevant in this situation

**Comment by bismarck** [comment]
This sounds like kubernetes/kubernetes#57049.  You may want to try updating your version of kubectl.

**Comment by kostyrev** [comment]
Doesn't look like it 'cause I've got
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-22T05:40:33Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by mikesplain** [comment]
I believe this will be fixed in the next version of kops, I saw a similar issue with CRDs not draining properly but the 1.10-alpha.1 and master fix this. Maybe give them a shot?  Number clients and dependencies were updated which I believe should help this issue.
