### ISSUE TITLE
Spot instances don't show up as K8s nodes

### ISSUE THREAD

**Issue by mkornacker** [kubernetes/kops#5385]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.9.0 (git-cccd71e67)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
kops create ig

with 

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.dev.leodata.io
  name: test-localmk1-exec-i291
spec:
  image: kope.io/k8s-1.8-debian-stretch-amd64-hvm-ebs-2018-02-08
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: test-localmk1-exec-i291
    leodata-cluster: test-localmk1-exec-i291
  role: Node
  rootVolumeSize: 21
  taints:
  - dedicated=test-localmk1-exec-i291:NoSchedule
  subnets:
  - us-west-2a
  maxPrice: "0.0464"

5. What happened after the commands executed?

The instance group gets created, I see the auto-scaling group in EC2 and the spot instance in EC2, but the node never makes it into the kubernetes cluster.

6. What did you expect to happen?
The node shows up in the kubernetes cluster.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-05-28T17:27:25Z
  name: us-west-2.dev.leodata.io
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": ["*"]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
            "Action": ["sts:AssumeRole"],
            "Resource": ["*"]
        }
      ]
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops.dev.leodata.io/us-west-2.dev.leodata.io
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterInternalName: api.internal.us-west-2.dev.leodata.io
  masterPublicName: api.us-west-2.dev.leodata.io
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: admin
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-31T19:06:38Z
  labels:
    kops.k8s.io/cluster: us-west-2.dev.leodata.io
  name: benchmarks
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: benchmarks
    leodata-cluster: benchmarks
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-west-2a
  taints:
  - dedicated=benchmarks:NoSchedule

.
.
.
(a bunch more instance groups, then the one with the spot price:)

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-27T01:52:18Z
  labels:
    kops.k8s.io/cluster: us-west-2.dev.leodata.io
  name: test-localmk1-exec-i291
spec:
  image: kope.io/k8s-1.8-debian-stretch-amd64-hvm-ebs-2018-02-08
  machineType: t2.medium
  maxPrice: "0.0464"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: test-localmk1-exec-i291
    leodata-cluster: test-localmk1-exec-i291
  role: Node
  rootVolumeSize: 21
  subnets:
  - us-west-2a
  taints:
  - dedicated=test-localmk1-exec-i291:NoSchedule

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

The output of kops update cluster --yes is ~1300 lines. Is there anything in particular from it that you want?

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by rekcah78** [comment]
Hi,
Your problem look like https://github.com/kubernetes/kubernetes/issues/57382
and is corrected in k8s 1.9.7

**Comment by mkornacker** [comment]
Good to hear.

If I were to run 'kops update cluster' right now, it would auto-upgrade from 1.9.3 to 1.9.6, ie, not pick up the required fix. Some questions:
a) given that we're running kops 1.9.0 right now (and the latest release appears to be 1.9.1), when will it auto-upgrade to 1.9.7 or beyond?
b) are there any downsides to doing a manual upgrade and setting the target version to 1.9.7? 
c) in terms of images, we're currently running kope.io/k8s-1.8-debian-stretch-amd64-hvm-ebs-2018-02-08 but the auto-upgrade will change this to kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11; we specifically chose stretch as opposed to jessie due to some problems with mounting EBS volumes as persistent volumes; is this also fixed in 1.9 jessie?
