### ISSUE TITLE
Unable to add additional options in componentconfig.go for kubelet

### ISSUE THREAD

**Issue by onyxet** [kubernetes/kops#5404]
1. KOPS: Version 1.9.1 (git-ba77c9ca2)
2. K8S: v1.9.6
3. AWS as provider

I want to add flag "authentication-token-webhook" to kubelet in my cluster. I found that in latest alpha version and in master branches they have that flag. But I'm using ver 1.9.1 which hasn't this flag. So I decided to add that flags in to pkg/apis/kops/componentconfig.go and pkg/apis/kops/v1alpha1/componentconfig.go and pkg/apis/kops/v1alpha2/componentconfig.go but after build I still don't have an ability to use this flag.
My api and kubelet configurations are:
`  kubeAPIServer:
    APIServerCount: 500
    auditLogMaxAge: 1
    auditLogMaxBackups: 5
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit-policy.conf
    authenticationTokenWebhook: true
    authorizationMode: RBAC
    authorizationRbacSuperUser: admin
    runtimeConfig:
      rbac.authorization.k8s.io/v1: "true"`

`  kubelet:
    AuthorizationMode: Webhook
    anonymousAuth: false
    enableCustomMetrics: true`
How can I add additional flag in to cluster configuration in right way?

**Comment by tsupertramp** [comment]
If you want to use authenticationTokenWebhook, this already works via kops 1.9.1 - Our company is using it together with guard - A doc how to use it for example with guard is sitting here: https://github.com/appscode/guard/blob/master/docs/setup/install-kops.md - So from my point of view you do not have to customize code and build your own kops binary.

**Comment by onyxet** [comment]
@tsupertramp Thank you for your advice. I just tried to repeat the same logic which is new version already using. I found that I need to change few files to generate new args for kube but still it doesn`t work.
I`m not sure that we`re talking about the same, cause I need this one.
https://github.com/kubernetes/kops/blob/c6e84ffd5508d5d591dd7da5ce4bbfd5860cc44e/pkg/apis/kops/componentconfig.go#L312
And as I could see it doesn`t implemented in 1.9.x ver of kops.
So I guess that I need a recipe for adding just this one option without "magic" :)

**Comment by tsupertramp** [comment]
@onyxet - Yeah you are right. My mistake. Sorry then i can not really help.

**Comment by geojaz** [comment]
@onyxet This sounds very reasonable- It looks like we should cherrypick https://github.com/kubernetes/kops/commit/8f916216872e039fa2fe441910e27b793442f17d#diff-42282c14ad3c398f60ffa89d5b6e4409 and release 1.9.2

**Comment by markine** [comment]
It looks like AuthenticationTokenWebhook support in newer kops releases is wrong. AuthenticationTokenWebhook should be listed under KubeletConfigSpec instead of kubeAPIServerConfig) as --authentication-token-webhook is a kubelet flag.

```
/usr/local/bin/kubelet --help
...
      --authentication-token-webhook                                                                              Use the TokenReview API to determine authentication for bearer tokens.
...
```

I'm trying to get a kops build environment set up so I could build and test a patch.

**Comment by onyxet** [comment]
Agreed with @markine . It's strange when we pass kubelet opts to api section
