### ISSUE TITLE
master nodes fail to attach etcd EBS volumes during rolling upgrade

### ISSUE THREAD

**Issue by harshal-shah** [kubernetes/kops#5410]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.9.1 (git-ba77c9ca2)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

GitVersion:"v1.9.8"

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

`kops rolling-update cluster production.mydomain.io --state s3://kops-s3-bucket`

5. What happened after the commands executed?

kops started a rolling upgrade on nodes.

6. What did you expect to happen?

We expected the rolling upgrade to complete without any downtime.
*What really happened:* 
Kops started rolling upgrade of master nodes (we have 3 masters), it terminated first master and started a new one, the new master was not able to mount EBS volumes of etcd (Due to API rate limiting by AWS). kops was unable to detect this problem and proceeded with rolling upgrade of the next master which faced the same problem (unable to mount etcd volume) and at that point we lost the cluster as etcd became unavailable. Kops still proceeded with the next master and we had a situation where all 3 masters were "running" on AWS console but none of them had etcd volumes mounted on them.

Another thing that we observed in syslog of nodes was that even when the volumes were "available" on AWS console, we were getting following error:

~~~
Jul  5 13:25:20 ip-172-24-102-238 docker[8538]: I0705 13:25:20.208044    8583 volume_mounter.go:255] Trying to mount master volume: "vol-0d86190f17f570d98"
Jul  5 13:25:20 ip-172-24-102-238 docker[8538]: W0705 13:25:20.208054    8583 volume_mounter.go:260] Error attaching volume "vol-0d86190f17f570d98": All devices in use
Jul  5 13:25:20 ip-172-24-102-238 docker[8538]: I0705 13:25:20.208073    8583 volume_mounter.go:274] Currently attached volumes: [{"ID":"vol-0f1b533a98788c1ab","LocalDevice":"/dev/xvdz","AttachedTo":"","Mountpoint":"","Status":"available","Info":{"Description":"vol-0f1b533a98788c1ab","EtcdClusters":[{"clusterKey":"main","nodeName":"c","nodeNames":["a","b","c"]}]}}]
~~~
Complete log is here : https://gist.github.com/harshal-shah/04b3038aea786e5e9d7a7d524091de96

We were able to resolve this by restarting master EC2 instances.
But our main concern is that the rolling upgrade failed to detect that the master node it recently upgraded was not healthy and moved on to upgrade next masters.

7. Please provide your cluster manifest.

~~~
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: production.mydomain.io
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect":"Allow",
          "Action":[
                    "autoscaling:DescribeAutoScalingGroups",
                    "autoscaling:DescribeAutoScalingInstances",
                    "autoscaling:DescribeLaunchConfigurations",
                    "autoscaling:DescribeTags",
                    "autoscaling:SetDesiredCapacity",
                    "autoscaling:TerminateInstanceInAutoScalingGroup",
                    "sts:AssumeRole"
                    ],
          "Resource":"*"
          }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole","ec2:DescribeRegions"],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Environment: Live
    Group: Kubernetes
    Squad: delta-force
    Tribe: Sioux
  cloudProvider: aws
  configBase: s3://kops-s3-bucket/production.mydomain.io
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  externalDns:
    watchIngress: true
  hooks:
  - before:
    - bootstrap-node.service
    execContainer:
      command:
      - sh
      - -c
      - chroot /rootfs docker login -u="kops_bootstrap_do_not_reuse" -p="REDACTED"
        quay.io
      image: busybox
    name: quay-login-config.service
  - before:
    - quay-logout-config.service
    execContainer:
      image: quay.io/hellofresh/kops-node-bootstrap
    name: bootstrap-node.service
    requires:
    - quay-login-config.service
  - execContainer:
      command:
      - sh
      - -c
      - chroot /rootfs docker logout quay.io
      image: busybox
    name: quay-logout-config.service
    requires:
    - bootstrap-node.service
  iam:
    legacy: true
  kubeAPIServer:
    authorizationRbacSuperUser: admin
    featureGates:
      CustomPodDNS: "true"
    runtimeConfig:
      batch/v2alpha1: "true"
  kubeDNS: {}
  kubelet:
    featureGates:
      CustomPodDNS: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.8
  masterInternalName: api.internal.production.mydomain.io
  masterPublicName: api.production.mydomain.io
  networkCIDR: 172.24.0.0/16
  networking:
    kuberouter: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  - cidr: 172.24.32.0/19
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.24.64.0/19
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.24.96.0/19
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.24.0.0/22
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.24.4.0/22
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.24.8.0/22
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  target:
    terraform:
      providerExtraConfig:
        alias: parent
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
~~~

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

**Comment by harshal-shah** [comment]
Can someone please assist with this? This caused a production outage for us.

**Comment by jrthrawny** [comment]
Did you run the rolling update with any additional flags for the timing/threshold interval between masters?

**Comment by harshal-shah** [comment]
Hey @jrthrawny 
We used the following command for our rolling update, we did not change timeouts between masters.

~~~
kops rolling-update cluster production.mydomain.io --state s3://kops-s3-bucket --yes
~~~

**Comment by geojaz** [comment]
@harshal-shah I'm really sorry that you ended up in this situation. It definitely sucks.

It doesn't sound like adjusting the timing between masters would have helped in this case, those activities are typically on the order of several minutes- rate limiting for aws usually happens when you hammer the API with requests over a few seconds. These EBS detach/attach sequences tend to be one of the most brittle things you can do with kubernetes on aws.

Which version were you upgrading from and what did you upgrade to? It seems like there may have been something going on before the logs begin on your attachment. Maybe something started spinning earlier in the process?

I'm not entirely sure why kops continued proceed with the update to the masters when the first one didn't come up healthy. We'll have to take a look at that...

**Comment by geojaz** [comment]
`blocks-next` to see if we're missing a failure condition that could be checked for. if we're in good shape, please close and remove tag.

**Comment by harshal-shah** [comment]
Hey @geojaz Thanks for your response. 
We understand that the AWS rate limiting was the primary cause for this problem and we are working on alleviating that problem.
We are using k8s version 1.9.8 and kops version 1.9.1.
We ran a rolling upgrade on our cluster due to some IAM changes but those are unrelated to the problem above.
Our main concern is that kops never detected missing etcd mounts on the first master and still allowed next master node to be drained, upgraded. As you said, the EBS attach / detach is very brittle, I think there should be a validation before a master node is considered healthy.

**Comment by juris** [comment]
Just want to throw my two cents here. I've faced the same issue couple of times. So for now I update masters one by one, and inspect etcd/kubernetes logs after each master group update:
```
$ kops rolling-update cluster f3.k8s.local --instance-group master-us-east-1a --yes
... wait and validate ...
$ kops rolling-update cluster f3.k8s.local --instance-group master-us-east-1b --yes
... wait and validate ...
$ kops rolling-update cluster f3.k8s.local --instance-group master-us-east-1c --yes
... wait and validate ...
```
Have not had any issues with this approach so far. Cheers!

**Comment by harshal-shah** [comment]
@juris Thank you. Yes, that procedure will surely help avoid any new issues. But having this fixed at kops level will be even better.

**Comment by johanneswuerbach** [comment]
@juris what are the things you are checking/ looking for? Can it be scripted?

**Comment by juris** [comment]
I'm checking that all the nodes report "Ready" status with `kubectl get nodes`.

Checking that both etcd clusters, etcd-server and etcd-server-events, are healthy: `kubectl exec -ti -n kube-system etcd-server-ip-10-113-105-174.ec2.internal etcdctl cluster-health`

Tailing logs from kube-system namespace pods on the new masters and looking for any error messages.

**Comment by dzoeteman** [comment]
I am able to reproduce this issue successfully using the following method:

1. Have a 3-master HA set-up
2. Update the kube version of the cluster, run `kops update cluster --yes` (do not do a `rolling-update` yet)
3. Change the tag in the IAM policy for AttachVolume, so it won't be able to attach
4. Do a `rolling-update` now
5. See that it continues the rolling-update past the first master, even though it never joins the cluster

What's interesting is that `kops validate cluster` actually does display the correct validation error: `machine "<instance id>" has not yet joined cluster`, yet the rolling-update just continues:

```
node "ip-<master 1 ip>.eu-west-1.compute.internal" drained
I0714 19:28:38.379667    3816 instancegroups.go:273] Stopping instance "i-<id>", node "ip-<master 1 ip>.eu-west-1.compute.internal", in group "master-eu-west-1a.<cluster>".
I0714 19:33:38.809455    3816 instancegroups.go:188] Validating the cluster.
I0714 19:33:40.314000    3816 instancegroups.go:249] Cluster validated.
I0714 19:33:41.322560    3816 instancegroups.go:157] Draining the node: "ip-<master 2 ip>.eu-west-1.compute.internal".
node "ip-<master 2 ip>.eu-west-1.compute.internal" cordoned
...
```

I'll try and have a look if I can find why this is happening.
