### ISSUE TITLE
iam role for extend pvc 

### ISSUE THREAD

**Issue by paokrab** [kubernetes/kops#5413]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.9.0 (git-cccd71e67)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
4.1 create resize volume storage class and create volume claim

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: gp2-resize
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
allowVolumeExpansion: true

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2-resize

4.2  edit size of pvc
   kubectl edit pvc test-claim

5. What happened after the commands executed?
 kubectl describe pvc test-claim
Name:          test-claim
Namespace:     default
StorageClass:  gp2-resize
Status:        Bound
Volume:        pvc-04c441e2-8053-11e8-b418-0689d13867fe
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/aws-ebs
Finalizers:    []
Capacity:      2Gi
Access Modes:  RWO
Events:
  Type     Reason              Age                From           Message
  ----     ------              ----               ----           -------
  Warning  VolumeResizeFailed  1m (x168 over 6h)  volume_expand  (combined from similar events): AWS modifyVolume failed for vol-0e93f6b21b8601675 with UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: 6f931dc1-be8f-41a3-b75a-adb37349f545

6. What did you expect to happen?
volume on aws size is increase.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
[k8s@ip-10-254-112-130 volume]$ kops get --name test-kubernetes.k8s.local -o yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-07-02T08:42:02Z
  name: test-kubernetes.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://test-kubernetes.k8s.local/test-kubernetes.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-ap-southeast-1a-1
      name: a-1
    - instanceGroup: master-ap-southeast-1b-1
      name: b-1
    - instanceGroup: master-ap-southeast-1a-2
      name: a-2
    name: main
  - etcdMembers:
    - instanceGroup: master-ap-southeast-1a-1
      name: a-1
    - instanceGroup: master-ap-southeast-1b-1
      name: b-1
    - instanceGroup: master-ap-southeast-1a-2
      name: a-2
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - PersistentVolumeClaimResize
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    featureGates:
      ExpandPersistentVolumes: "true"
  kubeControllerManager:
    featureGates:
      ExpandPersistentVolumes: "true"
  kubernetesApiAccess:
  - 10.1.2.0/24
  - 10.2.14.0/24
  - 10.254.112.130/32
  kubernetesVersion: 1.9.6
  masterInternalName: api.internal.test-kubernetes.k8s.local
  masterPublicName: api.test-kubernetes.k8s.local
  networkCIDR: 10.254.112.0/20
  networkID: vpc-xxxxxxxxxxxxxx
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.1.2.0/24
  - 10.2.14.0/24
  - 10.254.112.130/32
  subnets:
  - cidr: 10.254.116.0/24
    id: subnet-xxxxxxxxxxxxx
    name: ap-southeast-1a
    type: Private
    zone: ap-southeast-1a
  - cidr: 10.254.117.0/24
    id: subnet-xxxxxxxxxxx
    name: ap-southeast-1b
    type: Private
    zone: ap-southeast-1b
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-02T08:42:02Z
  labels:
    kops.k8s.io/cluster: test-kubernetes.k8s.local
  name: master-ap-southeast-1a-1
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      apt-get update
      apt-get upgrade -y
      sed -i s/debian.pool.ntp.org/amazon.pool.ntp.org/g /etc/ntp.conf
      echo "server 169.254.169.123 prefer iburst minpoll 3" >> /etc/ntp.conf
      service ntp restart
      cp -f /etc/localtime /etc/localtime.org
      cp -f /usr/share/zoneinfo/Asia/Bangkok /etc/localtime
    name: myscript.sh
    type: text/x-shellscript
  associatePublicIp: false
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-1a-1
  role: Master
  subnets:
  - ap-southeast-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-02T08:42:02Z
  labels:
    kops.k8s.io/cluster: test-kubernetes.k8s.local
  name: master-ap-southeast-1a-2
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      apt-get update
      apt-get upgrade
      sed -i s/debian.pool.ntp.org/amazon.pool.ntp.org/g /etc/ntp.conf
      echo "server 169.254.169.123 prefer iburst minpoll 3" >> /etc/ntp.conf
      service ntp restart
      cp -f /etc/localtime /etc/localtime.org
      cp -f /usr/share/zoneinfo/Asia/Bangkok /etc/localtime
    name: myscript.sh
    type: text/x-shellscript
  associatePublicIp: false
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-1a-2
  role: Master
  subnets:
  - ap-southeast-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-02T08:42:02Z
  labels:
    kops.k8s.io/cluster: test-kubernetes.k8s.local
  name: master-ap-southeast-1b-1
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      apt-get update
      apt-get upgrade
      sed -i s/debian.pool.ntp.org/amazon.pool.ntp.org/g /etc/ntp.conf
      echo "server 169.254.169.123 prefer iburst minpoll 3" >> /etc/ntp.conf
      service ntp restart
      cp -f /etc/localtime /etc/localtime.org
      cp -f /usr/share/zoneinfo/Asia/Bangkok /etc/localtime
    name: myscript.sh
    type: text/x-shellscript
  associatePublicIp: false
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-1b-1
  role: Master
  subnets:
  - ap-southeast-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-02T08:46:28Z
  labels:
    kops.k8s.io/cluster: test-kubernetes.k8s.local
  name: nodes-ap-southeast-1a
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      apt-get update
      apt-get upgrade -y
      echo "{" > /etc/docker/daemon.json
      echo "    " \"insecure-registries\":[\"10.248.224.123:18081\"] >> /etc/docker/daemon.json
      echo "}" >> /etc/docker/daemon.json
      sed -i s/debian.pool.ntp.org/amazon.pool.ntp.org/g /etc/ntp.conf
      echo "server 169.254.169.123 prefer iburst minpoll 3" >> /etc/ntp.conf
      service ntp restart
      cp -f /etc/localtime /etc/localtime.org
      cp -f /usr/share/zoneinfo/Asia/Bangkok /etc/localtime
    name: myscript.sh
    type: text/x-shellscript
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-southeast-1a
  role: Node
  subnets:
  - ap-southeast-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-02T08:47:03Z
  labels:
    kops.k8s.io/cluster: test-kubernetes.k8s.local
  name: nodes-ap-southeast-1b
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      apt-get update
      apt-get upgrade -y
      echo "{" > /etc/docker/daemon.json
      echo "    " \"insecure-registries\":[\"10.248.224.123:18081\"] >> /etc/docker/daemon.json
      echo "}" >> /etc/docker/daemon.json
      sed -i s/debian.pool.ntp.org/amazon.pool.ntp.org/g /etc/ntp.conf
      echo "server 169.254.169.123 prefer iburst minpoll 3" >> /etc/ntp.conf
      service ntp restart
      cp -f /etc/localtime /etc/localtime.org
      cp -f /usr/share/zoneinfo/Asia/Bangkok /etc/localtime
    name: myscript.sh
    type: text/x-shellscript
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-southeast-1b
  role: Node
  subnets:
  - ap-southeast-1b

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by KashifSaadat** [comment]
Hi @paokrab, thanks for raising an issue and sorry that you ran into this problem! I've raised PR #5416  to fix this.

For now to get around this problem whilst we wait for the PR to be merged and included in a release, you can include the following in your Cluster Spec:
```yaml
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["ec2:ModifyVolume"],
          "Resource": ["*"]
        }
      ]
```

**Comment by paokrab** [comment]
I have  added  additional policy to cluster as you recommend but still not working after increase 
size of pvc error when describe pvc is same. image below is policy that have created in IAM.


  Warning  VolumeResizeFailed     4m    volume_expand                error describing volume modification vol-086288c8ec42b3b36 with error listing volume modifictions : UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: f9528fde-7fac-4c54-9a08-4de4ed9bbc3b


Regards,
Paokrab


![image](https://user-images.githubusercontent.com/12736820/42422121-bee200e6-830a-11e8-9787-2aaa0953287a.png)

**Comment by paokrab** [comment]
Sorry @KashifSaadat it working now. It seem IAM role take sometime to effect.

**Comment by KashifSaadat** [comment]
No worries, good to hear! :)

**Comment by activeshadow** [comment]
FWIW, I also had to allow the `ec2:DescribeVolumesModifications` action in the additional master policy to avoid error events for the PVCs I expanded. I'm also 99% sure the Kubelet didn't actually expand the file system in the volume until I allowed this action (which, if true, would make sense since the Kubelet wouldn't know the volume resizing was done until the status of the volume modification could be read).

**Comment by KashifSaadat** [comment]
@activeshadow good spot, we'll want to fix that. I'll reopen for us to keep track and will push a fix in.

/reopen

**Comment by KashifSaadat** [comment]
Third time lucky!

/reopen
