### ISSUE TITLE
Boot sequence randomly fails

### ISSUE THREAD

**Issue by zuzzas** [kubernetes/kops#5423]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

```Version 1.9.0 (git-cccd71e67)```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.8", GitCommit:"2f73858c9e6ede659d6828fe5a1862a48034a0fd", GitTreeState:"clean", BuildDate:"2018-02-09T21:30:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.8", GitCommit:"2f73858c9e6ede659d6828fe5a1862a48034a0fd", GitTreeState:"clean", BuildDate:"2018-02-09T21:23:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

Scaled IG to any number of nodes. It pops randomly and unpredictably.

5. What happened after the commands executed?

Some nodes failed to register with apiserver.

6. What did you expect to happen?

I expect all nodes from scaled-up instance group to enter Ready state.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

[cluster-spec.txt](https://github.com/kubernetes/kops/files/2176230/cluster-spec.txt)

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

I haven't run any `kops` commands. The autoscaler unearthed the issue.

9. Anything else do we need to know?

Here is a full log from problematic node. You can see everything, including recurrent `kubelet.go:2094] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR`.

[node.log](https://github.com/kubernetes/kops/files/2176228/node.log)

**Comment by bhack** [comment]
I found the same with kops 1.9.2
