### ISSUE TITLE
DNS record for public API address not updated

### ISSUE THREAD

**Issue by fernandesnikhil** [kubernetes/kops#5442]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.9.1
1.9.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
1.9.3
1.9.9

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
Create cluster with `--networking amazon-vpc-routed-eni`.

5. What happened after the commands executed?
Cluster comes up, but the DNS record for the API is never updated. i.e. api.xxx.xxx
The records pointing to the internal IP addresses for components are updated correctly. i.e. `api.internal.xxx.xxx`, `etcd-b.internal.xxx.xxx` and `etcd-events-b.internal.xxx.xxx`.

In addition `validate` also detects the problem:
```
The dns-controller Kubernetes deployment has not updated the Kubernetes cluster's API DNS entry to the correct IP address.  The API DNS IP address is the placeholder address that kops creates: 203.0.113.123.  Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate.  The protokube container and dns-controller deployment logs may contain more diagnostic information.  Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to start.
```

6. What did you expect to happen?
The API DNS record is updated to resolve to the public IP address of a master node.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
https://gist.github.com/fernandesnikhil/8bb89f76976728f74d53b287420f4011

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
`kops create` and `kops update` logs for a cluster with this problem: https://gist.github.com/fernandesnikhil/caed532e79d08a81013f489ece89c561

9. Anything else do we need to know?
Tried with the following versions:
kops 1.9 and kubernetes 1.9.3
kops 1.9.1 and kubernetes 1.9.3, 1.9.9

DNS records are updated fine when using `--networking calico`

**Comment by tsuna** [comment]
I had a somewhat similar issue in #5437 after changing the EC2 instance type of the master.  Using kubenet for networking though.  So maybe the issue is independent of the type of networking you pick?

**Comment by DavideVi** [comment]
Same issue here and it's intermittent, sometimes it works, sometimes it doesn't, but most of the times it doesn't. 

Using AWS, Kops 1.9.1, Kubernetes 1.8.11 and the default kops cluster config (`kubenet` for networking).

**Comment by plrunner** [comment]
Same problem here using kops 1.10.0-beta and kubernetes 1.10.6.

**Comment by vkahawala** [comment]
Faced the same issue with kops 1.9.1 and Kubernetes version 1.9.10
After downgrading K8S to 1.9.9, it works find

**Comment by angegar** [comment]
Same issue with :
kubeVersion: 1.10.5
kopsVersion: 1.10.0


I receive the following error :

Validation Failed



`The dns-controller Kubernetes deployment has not updated the Kubernetes cluster's API DNS entry to the correct IP address.  The API DNS IP address is the placeholder address that kops creates: 203.0.113.123.  Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate.  The protokube container and dns-controller deployment logs may contain more diagnostic information.  Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to 
start.`

I have been waiting for hours ;)

**Comment by k** [comment]
I’v has this issue as well. I manually updated the DNS entry as a workaround for now.

**Comment by davidthornton** [comment]
Stuff like this happening in kops scares me and EKS is $0.2/hr... Hello @gcp!

**Comment by k** [comment]
Waiting for the DNS entry to update (however that happens) is quite long (the 5m timeout usually occurs during a rolling-update) and then waiting for DNS propagation takes time too.

What if kops put the master nodes behind a load balancer?

**Comment by antonlisovenko** [comment]
The same issue. Tried the following combinations:
k8sVersion: 1.11.0
kopsVersion: 1.10.0

k8sVersion: 1.11.0
kopsVersion: 1.11.0-beta.1

Tried to use calico networking but no luck - it's just stuck on `The dns-controller Kubernetes deployment has not updated the Kubernetes cluster's API DNS entry to the correct IP address`

**Comment by daraul** [comment]
Has this been resolved? What exactly is the work-around? I've also encountered this issue both with a k8s.local cluster and a named domain. Should I update my route 53 entries to point to the master node's public IP? 

It is scary that I can't rely on this to work out of the box as advertised, while it costs me money. :(

kubectl: 

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
kops: 
```
Version 1.10.0 (git-8b52ea6d1)
```

**Comment by jonigl** [comment]
same issue here!

**Comment by aisrael** [comment]
Just chiming in...

kubectl:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
```

kops:
```
Version 1.11.0
```

Command used
```
kops create cluster \
--name dev.k8s.mydomain.com \
--dns-zone ${KOPS_DNS_ZONE} \
--zones ap-southeast-1a \
--node-size t3.small \
--ssh-public-key ~/.ssh/aws-key.pub
```

**Comment by christianh814** [comment]
Just ran into this myself installing on GCE

```
$ kops version
Version 1.11.0 (git-2c2042465)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp 203.0.113.123:443: connect: no route to host
```

**Comment by hamza3202** [comment]
Facing this issue as well, The bastion's route53 record gets modified but api entry doesn't get modified.

**Comment by exNewbie** [comment]
same issue when I change instance type of node and master to **t2.nano**

**Comment by buzen247** [comment]
I think this applies to all server side  kubernetesVersion: 1.12.0 and above, version 1.11.0 in the cluster config works and kops 1.11 tend to work

**Comment by rafaeltuelho** [comment]
Yep! I can confirm that the latest stable kops release (`1.11.0`) only works with the kubernetes `1.11.0`. the kops and kubernetes Compatibility Matrix has to be strictly observed. For example to install kubernetes `1.14.x` you have to use kops `1.14.x - Alpha`

**Comment by srikiz** [comment]
I am facing the same issue with the latest master. If I check the master logs, I see something like this..
no kind "Keyset" is registered for version "kops.k8s.io/v1alpha2" in scheme "k8s.io/kops/pkg/kopscodecs/codecs.go:33

**Comment by srikiz** [comment]
I installed the release-1.12 branch and it seems to be working fine now. I also changed the AWS region from us-east-1a to us-east-1d

**Comment by kiranyedavalli** [comment]
My observation is that different combinations of kops and kubectl work for default node size. If we specify a custom node size none of the version combination is working for me. Not working = the api server's DNS is never propagated even thought the IP address changes in route 53.

**Comment by nodje** [comment]
Same issue here with `kops 1.15.0` and `kubectl v1.17.0` on AWS

can't even see any EC2 instance running on AWS console even though ` kops validate cluster` list the master and nodes

**Comment by acesir** [comment]
Running into the same issues with `kops 1.15` . kops validate lists the cluster, all nodes are up but the dns api resolution fails and of course all kubectl commands fail due to api being unreachable. 

With local cluster via gossip this works just fine but with public domain/dns it does not.

`The dns-controller Kubernetes deployment has not updated the Kubernetes cluster's API DNS entry to the correct IP address.  The API DNS IP address is the placeholder address that kops creates: 203.0.113.123.  Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate.  The protokube container and dns-controller deployment logs may contain more diagnostic information.  Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to start.`

**Comment by bjethwan** [comment]
I ran into this issue today then upgraded kops to version 1.16.0...but issue still persists....and strangely in my case when I ssh'ed into my master node...I didn't see the static pods running....the manifests under /etc/kubernetes/manifests/ looked fine though.

admin@ip-172-20-xx-xx:~$ sudo crictl ps
sudo: crictl: command not found
admin@ip-172-20-xx-xx:~$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by olemarkus** [comment]
Anyone experiencing this with kops 1.17?
I see some mentioned of awfully small instance types. This could cause some pods to be stuck pending because they don't fit on any nodes.

**Comment by prakashbabu01** [comment]
Have faced similar issue. Please follow below steps thoroughly, The issue should get resolved.
Root cause: kubectl version should be very close to the version of kops and Kerberos being chosen to install. 
Have worked with v 1.26.4 for all of them and it worked. 

below is the Kubernetes, kubectl, kops  version used and installed as binaries on Ubantu22.
https://github.com/kubernetes/kops/releases/tag/v1.26.4
$(curl -LO https://dl.k8s.io/release/v1.26.4/bin/linux/amd64/kubectl)
 wget https://github.com/kubernetes/kops/releases/download/v1.26.4/kops-linux-amd64
