### ISSUE TITLE
When will k8s 1.9.7, 1.10, or 1.11 be supported?

### ISSUE THREAD

**Issue by mkornacker** [kubernetes/kops#5444]
I'm just wondering what the upcoming release schedule looks like for stable releases.

I'm waiting for a fix for https://github.com/kubernetes/kubernetes/issues/57382 to materialize.

**Comment by sc250024** [comment]
@mkornacker You can always upgrade Kubernetes yourself following the `Manual Update` steps here: https://github.com/kubernetes/kops/blob/master/docs/upgrade.md too.

**Comment by mikesplain** [comment]
Hi @mkornacker, our compatibility matrix is located [here](https://github.com/kubernetes/kops#compatibility-matrix).  Any kops versoin (e.g. 1.9) works for that Kubernetes version or less (e.g. 1.9 works for 1.9.*, 1.8.*, 1.7.*,1.6.*).  We don't generally recommend earlier versions than that. 

Specific versions of k8s that we recommend are located in our stable and alpha channel files (see [here](https://github.com/kubernetes/kops/tree/master/channels)), but rest assured, we should be compatible with any supported minor version above.  

As far as 1.10 or further releases, we generally lag behind by 1 release. At the moment we're waiting on a beta to be cut (which should be imminent) and a major version for 1.10 should soon follow.  If you want to try 1.10, please feel free to test via the alpha but I would suggest waiting on prod till we release the final version.

Hope this helps!

**Comment by mkornacker** [comment]
Great, thanks for the clarification.

Just FYI, what made me hesitate with doing a manual upgrade was the fact that the auto-upgrade would only go to 1.9.6.
