### ISSUE TITLE
add support for Amazon m5d instances

### ISSUE THREAD

**Issue by gsstuart** [kubernetes/kops#5447]
kops version: Version 1.9.1 (git-ba77c9ca2)
k8s server version: v1.9.6
cloud provider: AWS

I'm trying to use Amazon `m5d.large` instances for a kops instance group, and receiving the following error:

`Invalid value: "m5d.large": machine type specified is invalid`

The expectation is that the instance group will be brought up successfully, with `m5d` instances.  It looks like these are not currently listed in `machine_types.go`; can support please be added?

**Comment by geojaz** [comment]
Thanks for the report @gsstuart - Those changes just landed in master (https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awsup/machine_types.go#L253), but we haven't cut the official release yet. This is currently included in the 1.10 alpha release, so if you want to help us test it out and need those m5d's today, that may help!

**Comment by gsstuart** [comment]
Great, thanks!  So far 1.10 alpha is working fine with `m5d` instances, and I'll report back if any issues arise.

I did notice some minor discrepancies in the ECU values listed for the `m5` and `m5d` instances in `machine_types.go` vs what I see on Amazon's EC2 page, although I'm assuming not much is done with those values... : )
