### ISSUE TITLE
Cluster autoscaler timeout when trying to run on master node

### ISSUE THREAD

**Issue by sc250024** [kubernetes/kops#5452]
**I originally posted this here: https://github.com/kubernetes/autoscaler/issues/1064**

Greetings,

I'm running `cluster-autoscaler` as part of a Kops cluster running on AWS. The problem is simple: when I run `cluster-autoscaler` on a regular node, it works fine, but when it's running on a master node, the pod times out, receives a `CrashLoopBackOff`, and then tries again to no avail. The following log message is the most applicable

```
F0715 16:55:30.458743       1 main.go:319] Failed to get nodes from apiserver: Get https://100.64.0.1:443/api/v1/nodes: dial tcp 100.64.0.1:443: i/o timeout
goroutine 1 [running]:
```

Kops version:  **1.9.1**
Kubernetes version: **1.9.6**
Cloud provider: **AWS**
Commands ran: **Followed the commands in the [Kops cluster-autoscaler documention](https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler)**
What happened after the commands executed?: **Pod starts, and then goes into a `CrashLoopBackOff` loops**
What did you expect to happen?: **The `cluster-autoscaler` app goes into its normal loop of checking if the ASG is in it's target node size.**

Extra notes:
- I'm using the Calico networking stack
- I'm using the [Kube2IAM](https://github.com/jtblin/kube2iam) project. Both the master and node IAM roles have the proper permissions to assume the role I provide in the annotation like so:

```yaml
annotations:
  iam.amazonaws.com/role: CompanyIamRole-ClusterAutoscalerEc2
```

Cluster manifest and full log output: https://gist.github.com/sc250024/81525c85f3cdfc60349b3bfdcce755af

**Comment by komljen** [comment]
I had the exact same issue and I fixed it by deleting the `calico-node` pod on the master node, then deleting auto-scaler pod. Autoscaler started fine after.

**Comment by prat0318** [comment]
I am thinking to use [cluster-autoscaler charts](https://github.com/helm/charts/tree/master/stable/cluster-autoscaler) but they don't have a taint of running only on `master` nodes, which kops autoscaler resource. So, i was wondering if there is a specific reason to run `cluster-autoscaler` on `master` nodes (instead of running them on `nodes`)? (Is it to prevent cluster-autoscaler running node itself to get removed by autoscaler?)

**Comment by sc250024** [comment]
@prat0318 You can use the chart, and run it on master. Put the following in your `values.yaml` file:

First, make the master node available for scheduling:

```yaml
tolerations:
  - effect: "NoSchedule"
    key: "node-role.kubernetes.io/master"
```

Optionally, you can run it **only** on master

```yaml
nodeSelector:
  kubernetes.io/role: "master"
```

**Comment by prat0318** [comment]
@sc250024 Thanks a lot, that worked. Still wondering if there is a benefit of running it on `master` nodes instead of regular worker nodes?

**Comment by sc250024** [comment]
@prat0318 It depends on your setup of course. I think the idea of running them on the master nodes is that the master nodes are more stable compared to the worker nodes. My worker nodes are all run on spot instances whereas the master nodes are dedicated.

If you're using EKS, AFAIK you can't schedule pods on the master nodes since they're not available to you. In that case, you can use the following `podAnnotation` to give the Cluster Autoscaler pods more priority:

```yaml
podAnnotations:
  scheduler.alpha.kubernetes.io/critical-pod: ""
```

**Comment by prat0318** [comment]
Thanks @sc250024 !
