### ISSUE TITLE
something like: kubectl explain

### ISSUE THREAD

**Issue by ms4720** [kubernetes/kops#5453]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

kops explain that behaves like kubectl explain

kubectl explain will walk you through the api/yaml and that would make writing a kops config much easier, list of all the options at a level and short help for each. 

2. Feel free to provide a design supporting your feature request.

**Comment by willchertoff** [comment]
I think this is a solid idea. There is a plethora of knowledge inside the [docs folder](https://github.com/kubernetes/kops/tree/master/docs), but it might be nice to implement this knowledge based in the cli.

**Comment by ms4720** [comment]
There is and finding the right piece I need right now is sometimes a problem for me.
