### ISSUE TITLE
1.10.alpha-1: nodes do not start because --require-kubeconfig is still supplied and is deprecated

### ISSUE THREAD

**Issue by dcowden** [kubernetes/kops#5459]
------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

**[mgarren-a@ip-172-25-48-245 ~]$ kops version
Version 1.10.0-alpha.1 (git-7f70266f5)*

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

**1.8.6, upgrading to 1.10.3**

3. What cloud provider are you using? **AWS**

4. What commands did you run?  What is the simplest way to reproduce this issue?

**kops upgrade**

5. What happened after the commands executed?

**upgrade completed successfully, but then nodes ( or masters ) would not start.**

6. What did you expect to happen?

**the nodes should start.**

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

Kubelet doesnt start, because the flag --require-kubeconfig is supplied, and it has been deprecated:

```
[root@ip-172-25-19-200 ~]# systemctl status kubelet -l
● kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; static; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-07-18 16:55:06 EDT; 394ms ago
     Docs: https://github.com/kubernetes/kubernetes
  Process: 28739 ExecStart=/usr/local/bin/kubelet $DAEMON_ARGS (code=exited, status=255)
 Main PID: 28739 (code=exited, status=255)
Jul 18 16:55:06 ip-172-25-19-200.colinx.com kubelet[28739]: --runtime-cgroups string                              Optional absolute name of cgroups to create and run the runtime in.
Jul 18 16:55:06 ip-172-25-19-200.colinx.com kubelet[28739]: --seccomp-profile-root string                         <Warning: Alpha feature> Directory path for seccomp profiles. (default "/var/lib/kubelet/seccomp")
Jul 18 16:55:06 ip-172-25-19-200.colinx.com kubelet[28739]: --stderrthreshold severity                            logs at or above this threshold go to stderr (default 2)
Jul 18 16:55:06 ip-172-25-19-200.colinx.com kubelet[28739]: -v, --v Level                                             log level for V logs
Jul 18 16:55:06 ip-172-25-19-200.colinx.com kubelet[28739]: --version version[=true]                              Print version information and quit
Jul 18 16:55:06 ip-172-25-19-200.colinx.com kubelet[28739]: --vmodule moduleSpec                                  comma-separated list of pattern=N settings for file-filtered logging
Jul 18 16:55:06 ip-172-25-19-200.colinx.com kubelet[28739]: --volume-plugin-dir string                            The full path of the directory in which to search for additional third party volume plugins (default "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/")
Jul 18 16:55:06 ip-172-25-19-200.colinx.com kubelet[28739]: F0718 16:55:06.724201   28739 server.go:145] unknown flag: --require-kubeconfig
Jul 18 16:55:06 ip-172-25-19-200.colinx.com systemd[1]: Unit kubelet.service entered failed state.
Jul 18 16:55:06 ip-172-25-19-200.colinx.com systemd[1]: kubelet.service failed.
```

Here are the daemon arguments:

`DAEMON_ARGS="--allow-privileged=true --cgroup-root=/ --cloud-provider=aws --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --enable-debugging-handlers=true --eviction-hard=memory.available<250Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5% --feature-gates=ExperimentalCriticalPodAnnotation=true --hostname-override=ip-172-25-19-200.colinx.com --kubeconfig=/var/lib/kubelet/kubeconfig --network-plugin=cni --node-labels=kops.k8s.io/instancegroup=nodes,kubernetes.io/role=node,node-role.kubernetes.io/node= --non-masquerade-cidr=100.64.0.0/10 --pod-infra-container-image=k8s.gcr.io/pause-amd64:3.0 --pod-manifest-path=/etc/kubernetes/manifests --register-schedulable=true --require-kubeconfig=true --v=3 --cloud-config=/etc/kubernetes/cloud.config --cni-bin-dir=/opt/cni/bin/ --cni-conf-dir=/etc/cni/net.d/"`

the flag ceased to be valid as of 1.10:  https://github.com/kubernetes/kubernetes/issues/41161

We verified that the nodes ( both a worker and a master ) started ok when we manually removed --require-kubeconfig=true from the DAEMON_ARGS.  

Of course this is just a temporary workaround, because automatically created notes will be broken.

**Comment by dcowden** [comment]
Resolved-- we found that we can simply remove this in the manifest.  It would be nice if kops removes it from the manifests when present, but manually removing it is fairly easily accomplished, so i think this is a low priority item.

**Comment by justinsb** [comment]
Sorry I missed this earlier.  I'm going to investigate, but can I confirm that you weren't actively passing `--require-kubeconfig` somehow - for example by specifying it in the kubelet options in your cluster manifest?  Or is that what you meant by "we can simply remove this in the manifest"?

**Comment by dcowden** [comment]
Our kops manifest (yaml) had the option in it from an earlier configuration, when it was not deprecated. As a result, it was passed to kubelet.

When we removed it from our kops manifest, it was no longer passed to kubelet.

The suggestion here is for kops to pro-actively remove the option from old manifests that have it in there, because failure to do so means kubelet wont start.

**Comment by justinsb** [comment]
Ah - that makes sense - thanks @dcowden 

This is the downside of these advanced overrides - you're at the mercy of raw kubernetes :-)  We try to build a layer of abstraction in kops that means we can translate intent into the flags, but when you're specifying flags directly (in the `kubeApiServer` block) it's hard for kops to know what to do.

I'm not sure that silently dropping the flag is great either, but I'm thinking we should probably make it a validation error - we don't necessarily want to rebuild all the apiserver validation, but we can certainly track removed flags without too much trouble!
