### ISSUE TITLE
kops update cluster with AWS_PROFILE behaves differently than using AWS env vars

### ISSUE THREAD

**Issue by cytopia** [kubernetes/kops#5465]
## 1. What `kops` version are you running?
```
$ kops version
Version 1.9.1 (git-ba77c9ca2)
```

## 2. What Kubernetes version are you running?
 a `kops` flag.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
## 3. What cloud provider are you using?
```
AWS
```

## 4. What commands did you run?  What is the simplest way to reproduce this issue?
I manage multiple AWS accounts and use *profiles* for that. Kops allows for using *profiles* instead of using environment variables. A profile configuration looks like this:

`~/.aws/config`
```
[profile testing]
region = eu-central-1
output = json
adfs_config.ssl_verification = True
adfs_config.role_arn = arn:aws:iam::123456789:role/AWS-testing
adfs_config.adfs_host = adfs.host.tld
adfs_config.adfs_user = first.last@comapny.tld
adfs_config.session_duration = 3600
```

### 4.1 Rollout with env vars

I am using [aws-export-profile](https://github.com/cytopia/aws-export-profile) to export the above listed profile into environment variables:
```
$(aws-export-profile testing)
```
After that I have the following variables available:
```
AWS_SECRET_ACCESS_KEY=xxxx
AWS_DELEGATION_TOKEN=xxxx
AWS_REGION=eu-central-1
AWS_ACCESS_KEY=xxx
AWS_SECRET_KEY=xxx
AWS_SESSION_TOKEN=xxx
AWS_ACCESS_KEY_ID=xxx
AWS_SECURITY_TOKEN=xxx
```
Now I can update my cluster via
```
kops update cluster --state s3://s3-bucket-name --name cluster-name.k8s.local
```
**This is all fine and does not show any changes.**

### 4.2 Rollout with profile

Now If I however use the `AWS_PROFILE` to tell kops which profile to use (instead of environment variables) like so:
```
AWS_PROFILE=testing kops update cluster --state s3://s3-bucket-name --name cluster-name.k8s.local
```
The following changes will appear:

```
Will modify resources:
  LaunchConfiguration/c4xlargea.cluster-name.k8s.local
        UserData
                                ...


                                - export AWS_REGION=eu-central-1


                                ...


  LaunchConfiguration/c4xlargeb.cluster-name.k8s.local
        UserData
                                ...


                                - export AWS_REGION=eu-central-1
```

## 6. What did you expect to happen?

* Do not remove the `export AWS_REGION=eu-central-1` from userdata (with AWS_PROFILE)
* Or do not add the `export AWS_REGION=eu-central-1` to userdata (without AWS_PROFILE)

## 7. Question

Why do both methods differ?

**Comment by justinsb** [comment]
Excellent observation - this is likely related to https://github.com/kubernetes/kops/pull/4483

**Comment by szeitlin** [comment]
If you have a default profile in your .aws config, and you are missing the correct region in the profile you want to use, it will fall back to the region of your default profile (the region where your account was originally created) _even if no region is specified for `[default]` in the config file_. 

One workaround for this is to remove the `[default]` profile from your config, and then you'll always get an error if you don't specify a region when you specify a profile that doesn't have one. 

I've found this to be a more intuitive (and safer) approach when you have multiple profiles in multiple regions.
