### ISSUE TITLE
External nodes added to cluster were deleted on cluster deletion

### ISSUE THREAD

**Issue by maver1ck** [kubernetes/kops#5482]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
v1.9.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag
v.1.9.6

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
I added external node (not provisioned by kops) to cluster.
Then I removed cluster.

5. What happened after the commands executed?
External nodes were deleted.

6. What did you expect to happen?
External nodes should stay alive.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?
Node added by:
- adding tag KubernetesCluster
- attach nodes IAM role
- attach node security group
- running nodeup script

**Comment by rdrgmnzs** [comment]
@maver1ck can you provide us with some information on how you added these external nodes to the pool. Could you also tell us how you provisioned these nodes?

**Comment by taylorshaulis** [comment]
+1 @rdrgmnzs comment... we need to know at least some information about the 'external' node.

Many times I have ran kops within AWS with instances not part of the cluster and kops never touched them

**Comment by maver1ck** [comment]
@rdrgmnzs 
Sorry for late answer.

Step to reproduce.
1) Create kops cluster (in my case 3 masters, 0 nodes)
2) Use kops to output terraform configuration `kops update cluster --yes --out $TEMPDIR --target=terraform`. 
3) Create external node (EC2 instance).
4) Add tag:  KubernetesCluster: $clustername to instance
5) Add this node to nodes.$clustername IAM role
6) Add this node to nodes.$clustername security group
7) Copy /etc/cni/net.d to this node (from master). I'm using canal, so this step is necessary. 
8 )Use `aws_launch_configuration_nodes.$clustername_user_data` from terraform output on the node to add it to kops cluster. 
9) That's all. Node is added to the pool.
----
Then
10) `kops delete cluster` is deleting this node

**Comment by taylorshaulis** [comment]
I tested and I can confirm the steps to reproduce do cause an external instance to be deleted.

I believe adding the tag KubernetesCluster: $clustername to the instance is causing this behavior.  Only with that tag correct does kops try to delete the instance.

@maver1ck if the external instance should persist the cluster can you try not adding the KubernetesCluster tag?  With the tag being set to the cluster your deleting, kops thinks that instance should be part of the delete.

**Comment by taylorshaulis** [comment]
That is indeed interesting

I believe kops is using the KubenetesCluster tag for asset tracking, that way when we are deleting a cluster we can simply look for all AWS items that have the KubernetesCluster tag.

I feel as though this is the desired behavior.  If we are deleting the cluster than anything claiming to be part of that cluster should be deleted.

Is there a strong reason to use an external instance instead of an instance within an auto scalling group?

**Comment by maver1ck** [comment]
For me yes - there are also provisioned from Ambari as HDFS clients - so I can use hostPath to pass HDFS configuration to apps on Kubernetes. 
(didn't find better way to connect k8s with hadoop)

So if this behavior is desired is it possible to "repair" validate command ?

**Comment by maver1ck** [comment]
@taylorshaulis Are you planning to do anything with this issue ?

**Comment by justinsb** [comment]
I wonder if a better way would be to "protect" the instances from deletion somehow.  We do have a notion of tags that indicate that resources are shared vs owned already, so possibly this might work - these nodes are effectively shared across clusters I guess (even if I think they could only exist in one cluster at once).

The cleaner solution might be to better figure out how to integrate HDFS, but if we respected a shared tag on instances and didn't delete them that might be an acceptable workaround.

`kops validate` does indeed use a slightly different way to detect instances - IIRC it works from the tagged auto-scaling groups on AWS.  We probably should have `kops validate` detect instances that have been manually added, for consistency with delete, except that I don't think manually adding instances is a very common use-case (?).

**Comment by maver1ck** [comment]
@justinsb 
Maybe I missed something. But why we need to label nodes to join it to cluster ?
Security group, IAM role and nodeup is not enough ?
