### ISSUE TITLE
Hash did not match for docker-ce_17.03.2 - Ubuntu - Xenial

### ISSUE THREAD

**Issue by IngJmCaicedo** [kubernetes/kops#5504]
** Kops version: 1.9.1
** Kubernetes version: 1.9.6
** Cloud provider: AWS

I'm trying to apply the terraform plan generated from the kubernetes.tf. I'm using Ubuntu on my instances: 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Looking at the journal on kops-configuration.service, I can see that it is failing when it compares the hash of the .deb file from Docker:
package.go:260] Installing package "docker-ce"
files.go:103] Hash did not match for "/var/cache/nodeup/packages/docker-ce": actual=sha1:da39a3ee5e6b4b0d3255bfef95601890afd80709 vs expected=sha1:4dcee1a05ec592e8a76e53e5b464ea43085a2849
http.go:77] Downloading "http://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.03.2~ce-0~ubuntu-xenial_amd64.deb"

When I do a curl to this URL I can see that is redirecting to https. I'm not sure if this is causing the Hash problem but I can see that there is an [open PR](https://github.com/kubernetes/kops/pull/5396) to change this to use HTTPS.

Am I the only one with this problem? I couldn't find any issue related apart from the PR.

**Comment by justinsb** [comment]
Ugh - this is not good.  I'm guessing that docker is forcing everyone to https, but we're not able to handle the redirect.

The hash "da39a3..." is the hash of an empty file.

**Comment by rata** [comment]
@IngJmCaicedo did you find the root cause of this?
