### ISSUE TITLE
QUESTION: Should we manually remove kube-dns after upgrading to coreDNS?

### ISSUE THREAD

**Issue by dcowden** [kubernetes/kops#5506]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
We used kops 1.10.0-beta.1 to upgrade our cluster, and used coreDNS provider.

CoreDNS is up and running. We noticed that the kube-dns service IP now points to coredns and to kube-dns.   

When will it migrate to coredns? Should we remove kube-dns ourself manually?

**Comment by mikesplain** [comment]
Hi @dcowden, yes we won't remove an existing kube-dns deployment as of yet.  Personally, I scale it and the kube-dns-autoscaler to zero, that way I can easily switch back if necessary.

**Comment by dcowden** [comment]
@mikesplain thanks. Yep, we figured, thanks. we'll do that!
