### ISSUE TITLE
EC2 Instances OutOfService after kops rolling-update

### ISSUE THREAD

**Issue by justinpaulson** [kubernetes/kops#5512]
I was upgrading a kubernetes deployment that has been active for close to a year without any updates.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.9.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Unable to connect to the server: EOF

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I was on kubernetesVersion 1.7.1
I ran...
`kops edit cluster`
Changed the kubernetesVersion to 1.11.1   (bold right?)
`kops update cluster`
`kops update cluster --yes`
`kops rolling-update cluster`
`kops rolling-update cluster --yes`

**5. What happened after the commands executed?**
The EC2 instances were restarted with new launch configurations. The autoscaling groups were properly connected. However, the api load balancer is showing the three master nodes as "OutOfService".  The only LoadBalancer that seems to have healthy instances is bastion.

**6. What did you expect to happen?**
I was hoping all the instances would come back up and properly connect with their load balancers.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-06-15T19:07:20Z
  name: REDACTED
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["autoscaling:*"],
          "Resource": ["*"]
        },
        {
          "Effect": "Allow",
          "Action": ["elasticfilesystem:*"],
          "Resource": ["*"]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["autoscaling:*"],
          "Resource": ["*"]
        },
        {
          "Effect": "Allow",
          "Action": ["elasticfilesystem:*"],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://REDACTED
  dnsZone: REDACTED
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    - instanceGroup: master-us-east-2b
      name: b
    - instanceGroup: master-us-east-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    - instanceGroup: master-us-east-2b
      name: b
    - instanceGroup: master-us-east-2c
      name: c
    name: events
  iam:
    legacy: true
  kubelet:
    enforceNodeAllocatable: pods
    evictionHard: memory.available<10%,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    kubeReserved:
      cpu: 200m
      memory: 100Mi
      storage: 1Gi
    kubeReservedCgroup: /kube-reserved
    systemReserved:
      cpu: 200m
      memory: 100Mi
      storage: 1Gi
    systemReservedCgroup: /system-reserved
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.1
  masterInternalName: api.internal.kube.REDACTED
  masterPublicName: api.kube.REDACTED
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-2a
    type: Private
    zone: us-east-2a
  - cidr: 172.20.64.0/19
    name: us-east-2b
    type: Private
    zone: us-east-2b
  - cidr: 172.20.96.0/19
    name: us-east-2c
    type: Private
    zone: us-east-2c
  - cidr: 172.20.0.0/22
    name: utility-us-east-2a
    type: Utility
    zone: us-east-2a
  - cidr: 172.20.4.0/22
    name: utility-us-east-2b
    type: Utility
    zone: us-east-2b
  - cidr: 172.20.8.0/22
    name: utility-us-east-2c
    type: Utility
    zone: us-east-2c
  topology:
    bastion:
      idleTimeoutSeconds: 3600
    dns:
      type: Public
    masters: private
    nodes: private
```

**9. Anything else do we need to know?**
Unable to access dashboard or get any information about the cluster with kubectl because API is not coming up.

**Comment by justinsb** [comment]
Are you able to SSH to the master (`kops toolbox dump -ojson | jq .instances` can show you the master IPs pretty easily)?  And when you do that, is apiserver (and lots more!) running in `sudo docker ps`?

Might be easiest to ping me on the kubernetes slack - I'm justinsb there as well..

**Comment by justinpaulson** [comment]
Sent message on Slack, thank you

**Comment by justinpaulson** [comment]
Our issue was kubelet not finding the reserved storage allocation and therefore not starting. I removed the two storage allocation lines from the manifest and this issue was resolved.
