### ISSUE TITLE
KOPS unable to create configuration file on DigitalOcean Spaces in 1.10.0 beta1

### ISSUE THREAD

**Issue by negrusti** [kubernetes/kops#5519]
kops create cluster --cloud=digitalocean --name=<cluster name> --image=ubuntu-16-04-x64 --networking=flannel --zones=ams3 --ssh-public-key=<public key>

error writing updated configuration: error writing Cluster "<cluster name>": error writing configuration file do://<bucket name>/<cluster name>/config: error writing do://<bucket name>/<cluster name>/config: InvalidArgument: Server Side Encryption with KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms
	status code: 400, request id: tx000000000000000222d53-005b58776e-9cb945-ams3a, host id: 

 Same command works fine on 1.9.2

**Comment by m-reda** [comment]
I manage to get around this error by removing this line [s3fs.go#L140](https://github.com/kubernetes/kops/blob/dc9154528f4ed796dab22f1a30e263ff708b5841/util/pkg/vfs/s3fs.go#L140)

**Comment by justinsb** [comment]
Sorry about the problem @negrusti and thanks for the hint @m-reda 

I think that #5625 should fix this!
