### ISSUE TITLE
dns-controller: shouldn't use ingress controller host ip for registering ingress service DNS name 

### ISSUE THREAD

**Issue by eghobo** [kubernetes/kops#552]
for each ingress service dns-controller create A record pointed to host where ingress controller running, there two issues with this approach
- if ingress controller controller is rescheduled, DNS record need to be updated
- if user run ELB upfront ingress controller, DNS record should be CNAME to ELB

@justinsb: also I think it shouldn't create DNS names automatically.

**Comment by andreychernih** [comment]
Stepped into this as well, it looks like it was fixed by https://github.com/kubernetes/kops/commit/e8ac74593bff980199d6b43e8557fe8d6972c3f0

**Comment by chrislovecnm** [comment]
Closing

**Comment by chrislovecnm** [comment]
Let me do this a bit better ;) Can we close this?

**Comment by chrislovecnm** [comment]
Closing
