### ISSUE TITLE
alternative CRI-shim / runtime support

### ISSUE THREAD

**Issue by egernst** [kubernetes/kops#5524]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Support for alternative runtimes, such as CRI-O and containerd.

**2. Feel free to provide a design supporting your feature request.**

**Comment by egernst** [comment]
I think this is still fresh, though perhaps it'll be easier if it has a PR associated with it to enable the changes.  Will put it on my to do list, though would love help here too.

/remove-lifecycle stale

**Comment by iamonkara** [comment]
This would be a nice feature to have. Seems like CRI-O uses the least resources.

**Comment by tuananh** [comment]
would love to see this implemented <3

**Comment by bcorijn** [comment]
So, I've been taking a look into this after discussing it at KubeCon EU with @mikesplain and @justinsb. It feels quite doable, as the whole docker bootstrapping is quite contained in nodeup, and only a handful of hardcoded, direct calls to the docker daemon throughout the codebase. Kubelet will also need a bit of extra configuration and maybe some other places, but it should be minimal.
The general structure of Docker bootstrapping can be easily re-used/ported to ContainerD from what I see.
However, the cluster spec at this moment doesn't really allow for any container runtime configuration. Either the DockerConfig is re-used to allow for specifying alternative runtimes (feels a bit dirty to me) or we add another high-level config element to specify runtimes and then run different builders in nodeup depending on what was used. Some advice on what would be the preferred path would be appreciated!

**Comment by ReillyProcentive** [comment]
FYI #7986 has been merged recently so expect containerd support in the relatively near future (kops 1.17 most likely)

**Comment by hakman** [comment]
> FYI #7986 has been merged recently so expect containerd support in the relatively near future (kops 1.17 most likely)

The target for containerd support is 1.18. It gives time to add docs, e2e tests and support for installing from the official tar.gz packages from cri-containerd. This way we can get the latest versions sooner and not depend just on what Docker packages.

There should be an alpha release soon though and feedback would be appreciated. Thanks for your interest on this topic!

**Comment by egeland** [comment]
Would 1.18 include support for CRI-O ?

**Comment by hakman** [comment]
I plan to add CRI-O support in 1.19 or 1.20, but would have to check first when would be a good time to do it.

**Comment by pierreozoux** [comment]
I'd recommend containerd over CRI-O.
This summer I investigated both.
My conclusion is that RedHat tools (buildah or crio) are not much supported on debian based system.

For instance, https://github.com/cri-o/cri-o/issues/2903

Also, looking at the ecosystem of maintainers of containerd, it looks like healthier (Alibaba, AWS, google, docker).

I dont use kops anymore those days, but I keep following it to see what decisions you take :) and this is just a kind advice.

**Comment by mr-rick** [comment]
are there any cri/o or containerd pull requests merged in yet?

**Comment by hakman** [comment]
> are there any cri/o or containerd pull requests merged in yet?

no

**Comment by hakman** [comment]
This request was partially satisfied by adding contained support in Kops 1.18.
I opened #9712 to track CRI-O support and discussions related to it.
/close
