### ISSUE TITLE
When deleting a cluster, kops ignores reclaim policy and deletes EBS volume disks even if reclaim policy is set to Retain

### ISSUE THREAD

**Issue by RomanKisilenko** [kubernetes/kops#5526]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.9.0 (git-324a2f5)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-12T22:24:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops delete cluster <name> --yes

**5. What happened after the commands executed?**
All cluster EBS volumes were deleted

**6. What did you expect to happen?**
Volumes created with Retain reclaim policy should be preserved

**Comment by rekcah78** [comment]
IMO, the policy "Retain" is proper to kubernetes, kops does not have to follow this rule.
Kubernetes do not flag the volume with the policy on the EBS, so how kops can know if he can or not delete the volume ?

**Comment by RomanKisilenko** [comment]
imho, kops is a piece of a larger kubernetes ecosystem which is expected to work nicely together b most users.

I believe a proper solution would be for kubernetes to tag volumes and then for kops to exclude them from being deleted.

**Comment by RomanKisilenko** [comment]
OK, I created a corresponding issue in kubernetes project: https://github.com/kubernetes/kubernetes/issues/66750
