### ISSUE TITLE
kops inclues files ending in .yml~ when given a directory to load templates from

### ISSUE THREAD

**Issue by ms4720** [kubernetes/kops#5528]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.10.0-beta.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

N/A

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops toolbox template --config=config/test.yml --template=cluster.yml --template=instance_groups/

**5. What happened after the commands executed?**

files ending in .yml~ were included in the build of the yml file

**6. What did you expect to happen?**

only files ending in .yml should be included in the template rendering or well-known editor extensions for backup files should be skipped 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
N/A

**9. Anything else do we need to know?**

**Comment by justinsb** [comment]
I checked what kubectl does, and it only processes these extensions:

`var FileExtensions = []string{".json", ".yaml", ".yml"}`

I guess we should do the same, though we'll need a big release note!

**Comment by justinsb** [comment]
Actually this just affects `kops toolbox template` and these are templates.  So I'm not sure about using the same list that kubectl uses - I could well imagine someone having a `.yaml.template` extension, for example.  So maybe we do just ignore well-known temp file (`*~`, but any others?)

(This is in our toolbox area, so the good news is that we don't have the same compatibility requirements - it's a more experimental area.  But it's still better not to break anyone!)

I wonder if we can detect the duplicate content somehow?  For example, make it an error if we have two clusters or two instancegroups named the same, which I'm guessing would happen...

Any input @gambol99 or @gwkunze - you're probably more familiar with this area of the code than I?

**Comment by ms4720** [comment]
If I remember correctly the docs said it was smart enough to add a .yml extension if it did not exist, implies that '.yml' is the proper file extension.  Personal opinion is to use a defined extension, say '.yml' or '.yml.tmpl' for example and document it.  Then check for that exact thing with good error messages.  

it should cover templates and snippets and will make the world a better place

I would like to take a shot at the pull if there is no issue, check files when you read them in and add the checks to append the proper extension and check again.

**Comment by ms4720** [comment]
One last point I disagree it is better to break people now and have a good fix, re: make and python tab problems.  This will be one hard visible fix that will eliminate a class of problems.  I Just finished my coffee so I am smarter now.   Thanks

**Comment by gwkunze** [comment]
In our use-case we only use a single file as the template source which ends in `.yaml.tpl` which we explicitly transform to a `.yaml` file so my experience here is limited.

From a cursory glance at the helm code – which I would say is closely related to `kops toolbox template` – it just loads everything from the `templates/` directory regardless of extension.

Assuming the generated files all still have the same extension, just making sure that `kops create -f` and `kops replace -f` only take yaml/yml/json files would be more in line with how kubectl behaves. It would still generate the files, just not use them.

**Comment by ms4720** [comment]
@gwkunze  if helm does that, I may open another ticket soon there too.  

My issue is this is going to cause problems for end users until it is fixed, pulling in different versions of a given chunk of code to introduce bugs silently, it is what happened to me.  Thankfully it blew up when I did a `kops apply -f file` in test but that is just getting lucky.  With the degree of damage kops can do to a cluster if given a bad and unluckily executable config file I do not think that a simple to do safety check is really anything but good long-term and right now.  the pain is that some things will break once hard.

I would be happy to do the patch, looks like everything can go in cmd/kops/toolbox_template.go:expandFiles line 238

I honestly do not really care what the extension is, just that it is a positive filter.  We can use '.go_bob' and I would be happy, '.{yml,yaml,json}.tmpl' might be better.

**Comment by ms4720** [comment]
@justinsb  I think files ending in '.tmpl' is a reasonable solution for what to load as a template and snippet.  Is this a patch the project is interested in?

**Comment by gwkunze** [comment]
Helm does it because it also applies the template to the `NOTES.txt` file. Similarly, I can imagine `kops toolbox template` potentially generating files not directly consumed by but containing documentation or configuration for other tools.

imho I think it should be (and is afaict) caught by the tools that actually have knowledge about the generated files and keep `kops toolbox template` essentially agnostic about the rest of the kops functionality keeping their concerns neatly separated. 

But at the same time I can understand the problem. But changing what it looks at might affect people who are already using the tool with unanticipated file extensions. How about instead making it respect either .gitignore or maybe a .kopsignore, maybe through a command-line option?

**Comment by ms4720** [comment]
@gwkunze   I understand your point, I am also seeing it as the grandchild of the make tab issue.  I see the .gitignore/.kopsignore still letting things in potentially and adding complexity to ongoing debugging.  

I could see a CLI switch to select the template extension with either a hard-coded default or an error generated if it is not set, also a lot simpler to do.  I think the CLI option is probably the best compromise with a reasonable documented default.

**Comment by gwkunze** [comment]
I believe helm has recently changed the behavior to have a whitelist of extensions it works on, so it makes some sense to copy that same behavior here.
