### ISSUE TITLE
AWS: Kops deleted api.* in route53 even though was not configured to use this subdomain

### ISSUE THREAD

**Issue by gregpardo** [kubernetes/kops#5531]
**1. Kops Version 1.9.1
**2. Kubernetes 1.10
**3. AWS
**4. kops create, kops edit, kops update, kops destroy
**5. 
kops uses api.mydomain.io by default. I edited m cluster to use kubernetes.mydomain.io. when i destroy the cluster it deletes the default api.mydomain.io even though I am not using it. This was quite an issue for us because we had an existing service configured to that in route53. 
**6. 
It should have deleted kubernetes.mydomain.io and not api.mydomain.io since that is how it was configured before updating with --yes.

**Comment by gregpardo** [comment]
Looks like there is an open TODO: here

https://github.com/kubernetes/kops/blob/86e8820a7e0bba521f897624d70ee4a20c5e75df/pkg/resources/aws/aws.go#L1589

**Comment by justinsb** [comment]
This is an issue, but I don't think we have time to tackle it in kops 1.10 (sorry!).  Tagging for 1.11.

**Comment by nareshku** [comment]
@justinsb I can take a look at this.

**Comment by justinsb** [comment]
Sorry for delay in getting to this one.  Ideally we wouldn't leak the old DNS name when masterPublicName is updated, but I also think first we should fix the fact that we are deleting a record we don't own.

So we shouldn't blindly delete `api.<clustername>`, but we should only do that if `masterPublicName` == `api.<clustername>`.

(If it came to it, I would also be OK with leaking the DNS record entirely when `masterPublicName` is not set, at least for a fix).
