### ISSUE TITLE
update from 1.3.6 to 1.3.8 failure

### ISSUE THREAD

**Issue by oO-Zam** [kubernetes/kops#554]
We just had a few crazy moment when I realized that KOPS update from 1.3.6 to 1.3.8 followed by a rolling-upgrade failed. or at least left the cluster in a non-working state for a very long time. 

Config:
metadata:
  creationTimestamp: "2016-09-08T19:17:56Z"
  name: k8s.zam.com
spec:
  adminAccess:
- 0.0.0.0/0
  cloudProvider: aws
  etcdClusters:
- etcdMembers:
  - name: us-east-1a
    zone: us-east-1a
  - name: us-east-1b
    zone: us-east-1b
  - name: us-east-1c
    zone: us-east-1c
    name: main
- etcdMembers:
  - name: us-east-1a
    zone: us-east-1a
  - name: us-east-1b
    zone: us-east-1b
  - name: us-east-1c
    zone: us-east-1c
    name: events
    kubernetesVersion: 1.3.6
    masterPublicName: api.k8s.zam.com
    networkCIDR: 172.16.0.0/16
    networking:
    classic: {}
    nonMasqueradeCIDR: 100.64.0.0/10
    zones:
- cidr: 172.16.32.0/19
  name: us-east-1a
- cidr: 172.16.64.0/19
  name: us-east-1b
- cidr: 172.16.96.0/19
  name: us-east-1c

After changing from 1.3.6 to 1.3.8 we did 

kops update cluster --yes

then 

kops rolling-update cluster --yes

after swapping the nodes, kubectl could not connect to the api server.

kubectl version --v=8
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
I0930 17:00:34.609428    3501 loader.go:327] Config loaded from file /Users/olivier/.kube/config
I0930 17:00:34.611842    3501 round_trippers.go:296] GET https://api.k8s.zam.com/api
I0930 17:00:34.611871    3501 round_trippers.go:303] Request Headers:
I0930 17:00:34.611875    3501 round_trippers.go:306]     Accept: application/json, _/_
I0930 17:00:34.611878    3501 round_trippers.go:306]     User-Agent: kubectl/v1.3.6 (darwin/amd64) kubernetes/ae4550c
I0930 17:00:34.611881    3501 round_trippers.go:306]     Authorization: Basic YWRtaW46UzJvUjFHenQ1WTV1RlliemtNTFlSWDZYODFockRSYUI=
I0930 17:00:34.884749    3501 round_trippers.go:321] Response Status:  in 272 milliseconds
I0930 17:00:34.884779    3501 round_trippers.go:324] Response Headers:
I0930 17:00:34.884916    3501 helpers.go:189] Connection error: Get https://api.k8s.zam.com/api: dial tcp 54.198.64.191:443: getsockopt: connection refused
F0930 17:00:34.885002    3501 helpers.go:108] The connection to the server api.k8s.zam.com was refused - did you specify the right host or port?

**Comment by chrislovecnm** [comment]
You find a resolution?

**Comment by justinsb** [comment]
Going to close this one, as I believe it is resolved - a rolling update of a non HA cluster does involve downtime, but we've made big progress here and have a bunch of improvements in 1.5
