### ISSUE TITLE
Is there a getting started guide for becoming a developer

### ISSUE THREAD

**Issue by ms4720** [kubernetes/kops#5548]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

A README.md in kops/hack about how to set up the dev env for someone who may not be the most up to speed golang and k8s dev.  I think it should contain:

- tools needed and how to install
- how to configure the tools for kops
- how to test the tools are configured 
- how to set up the git repo, including setting up upstream 

for:

- mac 
- linux
- windows 

the end product is a properly configured CLI env to contribute to kops

**2. Feel free to provide a design supporting your feature request.**

Help me write it up by providing the facts to make the story happen

**Comment by justinsb** [comment]
This is a good suggestion - we do have https://github.com/kubernetes/kops/blob/master/docs/development/adding_a_feature.md but that's likely horribly out of date...

**Comment by ms4720** [comment]
That assumes a much higher level of competence than I am talking about, even if it is current.

**Comment by bzuelke** [comment]
+1 to this. I think it would help out a lot. It's not impossible to learn by trial and error but could help in shrinking the time frame of actually getting to a point to contribute to the project.
