### ISSUE TITLE
GetAsgForInstance is not a valid IAM actions

### ISSUE THREAD

**Issue by chrisduong** [kubernetes/kops#5549]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

- KOPS version 1.9.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
- 1.9.6

**3. What cloud provider are you using?**
- AWS

I had recognized this complain from AWS IAM console. Please see the picture

<img width="900" alt="image" src="https://user-images.githubusercontent.com/1848882/43380797-0cc8ee5e-9405-11e8-843b-514a612c75ef.png">

**Comment by rekcah78** [comment]
@chrislovecnm can you explain that, it's normal ?

**Comment by justinsb** [comment]
Thanks for noticing & reporting this @chrisduong and @rekcah78 .  This is indeed not a real IAM permission.  It is a method in the autoscaler, but it is backed by a cache rather than by an AWS call, hence the error.

I submitted a PR to remove the permission in #5566
