### ISSUE TITLE
printers package shouldn't drag along all VFS provider dependencies

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kops#5551]
Including `k8s.io/kops/util/pkg/tables` in `eksctl` has introduced a bag of dependencies, including gophercloud and others. Those dependencies mostly got pulled in from `k8s.io/kops/util/pkg/vfs` via `k8s.io/kops/pkg/apis/kops`. There ought to be a way to avoid this. Perhaps we could separate out some packages into a different repo. Besides `k8s.io/kops/util/pkg/tables`, `eksctl` uses `k8s.io/kops/pkg/pki` and `k8s.io/kops/upup/pkg/fi/utils`.

**Comment by errordeveloper** [comment]
cc @chrislovecnm

**Comment by justinsb** [comment]
I refactored the package for cleaner package dependencies, primarily by allowing for you to register pretty-print functions.  That was what was causing the package dependency.  See #5565
