### ISSUE TITLE
The pod name is more than 63 characters, it is caused other issue

### ISSUE THREAD

**Issue by wwyhy** [kubernetes/kops#5554]
Hi,

I have setup a k8s cluster with kops v1.9.2. everything is working well. 

But when I run Rancher in this cluster, I got the error as below:

`2018/07/31 02:02:34 [ERROR] PodController kube-system/etcd-server-events-ip-10-230-60-77.ap-southeast-1.compute.internal [podHandler] failed with : Pod "etcd-server-events-ip-10-230-60-77.ap-southeast-1.compute.internal" is invalid: metadata.labels: Invalid value: "etcd-server-events-ip-10-200-60-77.ap-southeast-1.compute.internal": must be no more than 63 characters`

After checked the pod name is more than 63 characters, but the pod name is generated by Kops during cluster deployment. 
And I found that the limitation is defined by Kubernets. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

So is there any way to make the pod name short? Could somebody can help on this? 
I am not sure if it is safe or cause issue by modify the pod name with command "kubectl edit pod <name> -n kube-system" .

`[root@ip-10-230-240-254 ~]# kubectl get po --all-namespaces | awk '{print $2}'
NAME
cattle-7745d7d754-mxlpn
calico-kube-controllers-f6bc47f75-k49hz
calico-node-4qfpx
calico-node-5vwhd
calico-node-9slnv
calico-node-jd85c
calico-node-jvbf9
calico-node-kbtgg
dns-controller-88464b5c-p2vns
etcd-server-events-ip-10-230-60-77.ap-southeast-1.compute.internal
etcd-server-events-ip-10-230-79-84.ap-southeast-1.compute.internal
etcd-server-events-ip-10-230-99-174.ap-southeast-1.compute.internal
etcd-server-ip-10-230-60-77.ap-southeast-1.compute.internal
etcd-server-ip-10-230-79-84.ap-southeast-1.compute.internal
etcd-server-ip-10-230-99-174.ap-southeast-1.compute.internal
kube-apiserver-ip-10-230-60-77.ap-southeast-1.compute.internal
kube-apiserver-ip-10-230-79-84.ap-southeast-1.compute.internal
kube-apiserver-ip-10-230-99-174.ap-southeast-1.compute.internal
kube-controller-manager-ip-10-230-60-77.ap-southeast-1.compute.internal
kube-controller-manager-ip-10-230-79-84.ap-southeast-1.compute.internal
kube-controller-manager-ip-10-230-99-174.ap-southeast-1.compute.internal
kube-dns-756bfc7fdf-nlngs
kube-dns-756bfc7fdf-vp5zr
kube-dns-autoscaler-787d59df8f-m9zwl
kube-proxy-ip-10-230-115-143.ap-southeast-1.compute.internal
kube-proxy-ip-10-230-47-199.ap-southeast-1.compute.internal
kube-proxy-ip-10-230-60-77.ap-southeast-1.compute.internal
kube-proxy-ip-10-230-72-169.ap-southeast-1.compute.internal
kube-proxy-ip-10-230-79-84.ap-southeast-1.compute.internal
kube-proxy-ip-10-230-99-174.ap-southeast-1.compute.internal
kube-scheduler-ip-10-230-60-77.ap-southeast-1.compute.internal
kube-scheduler-ip-10-230-79-84.ap-southeast-1.compute.internal
kube-scheduler-ip-10-230-99-174.ap-southeast-1.compute.internal`

Thanks!

**Comment by wwyhy** [comment]
Or how to customize the EC2 hostname before deploy k8s cluster?
the hostname (ap-southeast-1.compute.internal) is too long.

**Comment by kimxogus** [comment]
how did you solve this issue?

**Comment by wwyhy** [comment]
> how did you solve this issue?

Change the DHCP option under VPC on AWS by customize the domain to short one（eg: ec2.local）.

**Comment by lionelliang** [comment]
I encountered the same problem and here is wayto modify ec2 linux hostname: https://aws.amazon.com/premiumsupport/knowledge-center/linux-static-hostname/
