### ISSUE TITLE
One security group per instancegroup

### ISSUE THREAD

**Issue by Hermain** [kubernetes/kops#5556]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

By default each instancegroup should have a its own security group with the same rules as the nodes security group.

Currently any additional instancegroup which is created with kops uses the nodes security group (on aws). Also the additionalSecurityGroups

If its important that all instancegroups (except master) share one security group such a security group could be used plus a specific security group which is specific to each instancegroup. However I don't think that would be necessary.

Motivation:
As issue #3698 describes, in order to change some security rules on a new instancegroup one would have to either create a cluster, add a security group (additionalSecurityGroups field) and run a rolling update, or create a VPC with a new security group and then use the additionalSecurityGroups field to add that group to the instancegroup.

Both are quite cumbersome instead it should be possible to simply create a cluster with all required instancegroups and then using the aws cli to alter the security group as desired.

**2. Feel free to provide a design supporting your feature request.**
It seems to me like this change would be relatively easy to implement and I would volunteer to implement it with some guidance (I am not familiar with the codebase and not familiar with go)

**Comment by justinsb** [comment]
This is interesting - can you explain the use case a bit more?  Is the idea that you have different instance groups which can access different AWS services (for example)?  Or that you have different instance groups that are exposing different services e.g. on a hostport?

**Comment by Hermain** [comment]
The latter.

I have my "normal" microservices running on the "default" instancegroup and I have a kafka cluster running on a separate instancegroup with the exact hardware I need for kafka brokers (thats the performance critical part of my app).

Since kafka does its own load-balancing theres no point to using aws load balancer or node ports (clumsy since I want to scale the number of kafka brokers without having to create more and more nodeport services)

Instead I use a hostport on all the kafka brokers.

My problem. Currently is a pain to expose that port only on the kafka instancegroup. Lazy users would instead leave the port open on all nodes which is not ideal

Am 13.08.2018 17:34 schrieb Justin Santa Barbara <notifications@github.com>:

This is interesting - can you explain the use case a bit more? Is the idea that you have different instance groups which can access different AWS services (for example)? Or that you have different instance groups that are exposing different services e.g. on a hostport?

**Comment by bzuelke** [comment]
I've actually been working on something similar to your use case. I need to essentially remove the default Nodes SG from other instance groups as the allow all egress isn't great for CIS. I'm looking to potentially have a PR soon that might help you here as well. You'd define IGSecurityGroups in the instancegroup Spec with the SG you want, by defining that, it will clear existing SG's from that instance group and replace it with the SG id you defined in the IG's Spec, and the additional SG's if those are defined as well. Just thought id chime in here as I noticed this issue in passing.

https://github.com/kubernetes/kops/issues/5564#issuecomment-423010021

**Comment by daviddyball** [comment]
I am 100% in favour of a per-instance-group automatically created security group... perhaps add to the `InstanceGroupSpec`:

```
spec:
  createUniqueSecurityGroup: true/false
  useDefaultNodeSecurityGroup: true/false
```

In my use-case, I have 3 node groups, `ci`, `staging` and `production`. We use `nodeSelector`s to put specific workloads on specific hosts. What would be nice is to end up with the following security groups after deployment:

```
nodes.k8s.example.com
ci.nodes.k8s.example.com
staging.nodes.k8s.example.com
production.nodes.k8s.example.com
```

In my specific use-case it would still be helpful to have each `InstanceGroup` still remain part of the default `nodes.k8s.example.com` security group, as this is useful for doing `bastion` <-> `nodes` security group rules.

**Comment by daviddyball** [comment]
I personally think this is still a good feature to have in Kops. @Hermain are you able to submit `/remove-lifecycle stale` to update this ticket?

**Comment by bzuelke** [comment]
So this is in at the very least kops 1.11-beta, this would essentially solve this issue and in my testing in my sandbox cluster it works for all of the instance groups I tested on. We also have a split out of specific nodes that need specific SG's for each and this seemed to do the trick. https://github.com/kubernetes/kops/blob/master/docs/security_groups.md

I've not yet tested this along with additionalSecurityGroups but don't see why it would be a problem to have both in place if that would be needed as well. 

The lifecycle override business I've not needed to do personally, but thought I'd chime in here.
