### ISSUE TITLE
CNI: aws-vpc-routed-eni yaml is NOT right in master(#5119) and 1.10.0-alpha.1

### ISSUE THREAD

**Issue by liwenwu-amazon** [kubernetes/kops#5568]
The following commit [Upgrade default Amazon VPC Networking image to v1.0.0](https://github.com/kubernetes/kops/commit/3610bf20d034503a15cafab28df6045adadf17e3) is not right.  

The [CNI 1.0.0 yaml](https://github.com/kubernetes/kops/commit/3610bf20d034503a15cafab28df6045adadf17e3) is compatible with CNI 0.1.1.    It will not work by just bumping the CNI docker image version

**Comment by liwenwu-amazon** [comment]
Both [CNI 1.0.0](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.0/aws-k8s-cni.yaml) AND [CNI 1.1.0](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.1/aws-k8s-cni.yaml) contains RBAC related config, whereas CNI 0.1.1 does NOT.

**Comment by ripta** [comment]
@liwenwu-amazon - The commit you linked to ([3610bf2](https://github.com/kubernetes/kops/commit/3610bf20d034503a15cafab28df6045adadf17e3)) is part of a larger PR #5119, which includes further commits that update the manifest.

I just double-checked, and couldn't find any missing RBAC objects. If you see any, I would love to fix that mistake.

**Comment by liwenwu-amazon** [comment]
@ripta thank you!  Looks good to me and I am closing this issue
