### ISSUE TITLE
kops should support using a VPC without an internet gateway in AWS.

### ISSUE THREAD

**Issue by josephspurrier** [kubernetes/kops#5569]
KOPS should support setting up Kubernetes when there is no internet gateway in AWS. Two scenarios are when a VPC only has Virtual Private Gateway (VGW) in AWS or when a VPC is peered with another VPC and you are using a router or a connection like an IPSEC tunnel to get out to the internet. Both of these are scenarios in production environments today, especially in large organizations where all traffic must exit at designated areas.

To resolve the error message, "InternetGateway for shared VPC was not found", I just commented out the error on this line:
https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awstasks/internetgateway.go#L143

Also, here are instructions on how to set up a VGW on in a VPC in AWS and connecting to another VPC using OpenSwan for any testing:
https://gist.github.com/josephspurrier/ea6079a995354b39c948d2ebbdae990f

I suggest adding a parameter that change the Internet Gateway error into only a warning to allow the installation to continue.

**Comment by geojaz** [comment]
@josephspurrier I think you're right- it's reasonable to want to avoid the gateway. This proposal has both gained and lost momentum a number of times. There are a couple PRs that seem to still be around, but without much action that address this: https://github.com/kubernetes/kops/pull/3031 and https://github.com/kubernetes/kops/pull/5141.

I'd like to see them get some attention so that the functionality makes it into a forthcoming release.

**Comment by pitthecat** [comment]
We are also facing the problem with error message "InternetGateway for shared VPC was not found". We are using Kubernetes in a private AWS VPC setup. We only have a VPN connection to the VPC. The VPN connection is used for the internet access so there is no need for an IGW.

**Comment by pitthecat** [comment]
A little workaround is the parameter "--lifecycle-overrides InternetGateway=Ignore" and you should get no error output

**Comment by oscarandreu** [comment]
> A little workaround is the parameter "--lifecycle-overrides InternetGateway=Ignore" and you should get no error output

Thanks :) TA guys are always efficient.

**Comment by ekevoo** [comment]
/remove-lifecycle stale

How is this helpful

**Comment by arontx** [comment]
> --lifecycle-overrides InternetGateway=Ignore

This did not work in my case, I am still getting the error `InternetGateway for shared VPC was not found`

**Comment by arontx** [comment]
/remove-lifecycle stale
  
  
  
 @     
  
  

  
  
>
