### ISSUE TITLE
kops get secrets $ACCOUNT -oplaintext , -oplaintext not documented

### ISSUE THREAD

**Issue by ms4720** [kubernetes/kops#5572]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.10.0-beta.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
N/A

**3. What cloud provider are you using?**
N/A

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops get secrets --help

**5. What happened after the commands executed?**

planetext was not documented as a valid output format

**6. What did you expect to happen?**

It should be documented in the help screen as a local output format 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
N/A

**9. Anything else do we need to know?**

**Comment by justinsb** [comment]
This is a good point - sadly it isn't totally trivial (to me) to know how to fix it, because `output` is a persistent flag defined on `kops get` that `kops get secret` inherits.  Will ponder / suggestions welcome!
