### ISSUE TITLE
Admin password in /svc/kubernetes/basic_auth.csv doesn't match s3://clustername/secrets/admin

### ISSUE THREAD

**Issue by shelbrudy** [kubernetes/kops#5583]
**1. What `kops` version are you running?**

1.9.0

**2. What Kubernetes version are you running?**

1.11.0

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I am trying to cycle the kops admin password and followed the instructions [here](https://github.com/kubernetes/kops/blob/master/docs/secrets.md#workaround-for-changing-secrets-with-type-secret). I generated a new password, converted it to base64, and made the change in s3://clustername/secrets/admin. I then terminated and respawned the master nodes.

**5. What happened after the commands executed?**

I ssh'd into a master node to check that the password located in /srv/kubernetes/basic_auth.csv matched that of the newly rotated admin password in s3://clustername/secrets/admin and it did not. It instead matched the password in s3://clustername/secretes/kube.

**6. What did you expect to happen?**

Expected it to match the password in s3://clustername/secrets/admin.

**Comment by byndcivilization** [comment]
Hi @justinsb do you have a sense of whether this will be addressed?
