### ISSUE TITLE
Kubedns allow changing DNS policy

### ISSUE THREAD

**Issue by vidhy** [kubernetes/kops#5592]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

When I check the cluster spec, the dnsPolicy of kubedns is not configurable (https://godoc.org/k8s.io/kops/pkg/apis/kops#KubeDNSConfig)

Would be better to have the dnsPolicy configurable so that i can set dnsPolicy as clusterFirst on setup.

**Comment by vidhy** [comment]
@chrisohaver i misunderstood the way it works. (I thought the dnsPolicy config on kubedns is at cluster level.)
so even when i have default dnspolicy,
- es.default.svc.cluster.local. will be resolved by kubedns (because of the suffix)
- google.com will be resolved by some upstream NS (inherited from node)

Am I right?

**Comment by chrisohaver** [comment]
Not exactly...
See https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ for the full definitions of dnsPolicies.

The **default** dnsPolicy will resolve _everything_ using the upstream servers inherited from the node.
The **clusterFirst** policy will resolve _everything_ using the cluster DNS IP (e.g. kube-dns cluster IP). ClusterFirst also uses a special domain search path, hence the name.

When you query `google.com.` from a pod that uses the clusterFirst policy, it will send the query to kube-dns, then kube-dns (using default policy) will forward the query to the upstream servers.
