### ISSUE TITLE
UnauthorizedOperation with kops create cluster while aws ec2 run-instances works

### ISSUE THREAD

**Issue by MKhere** [kubernetes/kops#5594]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.9.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster --cloud=aws --name=${KOPS_CLUSTER_NAME} --state=${KOPS_STATE_STORE} --zones=eu-central-1  --node-count=2 --node-size=t2.medium

**5. What happened after the commands executed?**
Command returns the following error:
I0810 14:34:04.519972   31885 create_cluster.go:1318] Using SSH public key: /Users/xyz/.ssh/id_rsa.pub

error populating configuration: Got an error while querying for valid regions (verify your AWS credentials?): UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 886972c2-122f-4cd1-8bda-3f4463963ccf

**6. What did you expect to happen?**
I expected the k8s cluster to be created in AWS

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
The cluster did not get created, the above command returns this error 
Cluster.kops "kubeflow.k8s.local" not found

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

➜  ~ kops create cluster --cloud=aws --name=${KOPS_CLUSTER_NAME} --state=${KOPS_STATE_STORE} --zones=eu-central-1  --node-count=2 --node-size=t2.medium -v10
I0810 14:36:56.545660   31912 create_cluster.go:1318] Using SSH public key: /Users/xyz/.ssh/id_rsa.pub
I0810 14:36:57.185933   31912 s3context.go:172] Found bucket "kubeflow-xyz-test" in region "eu-central-1"
I0810 14:36:57.186463   31912 s3fs.go:210] Reading file "s3://kubeflow-xyz-test/kubeflow.k8s.local/config"
I0810 14:36:57.291620   31912 channel.go:97] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I0810 14:36:57.291701   31912 channel.go:102] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I0810 14:36:57.291810   31912 context.go:159] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I0810 14:36:57.378694   31912 channel.go:111] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2018-03-11
      providerID: aws
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2018-03-11
      providerID: aws
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-03-11
      providerID: aws
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-03-11
      providerID: aws
      kubernetesVersion: ">=1.8.0 <1.9.0"
    - name: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
      providerID: aws
      kubernetesVersion: ">=1.9.0 <1.10.0"
    # Need stretch as default in 1.10 (for nvme)
    # BUT... this is causing the submit queue to block, so back to jessie temporarily: https://github.com/kubernetes/kubernetes/issues/56763
    - name: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
      providerID: aws
      kubernetesVersion: ">=1.10.0"
    - providerID: gce
      name: "cos-cloud/cos-stable-60-9592-90-0"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.10.0"
    recommendedVersion: 1.10.3
    requiredVersion: 1.10.0
  - range: ">=1.9.0"
    recommendedVersion: 1.9.8
    requiredVersion: 1.9.0
  - range: ">=1.8.0"
    recommendedVersion: 1.8.13
    requiredVersion: 1.8.0
  - range: ">=1.7.0"
    recommendedVersion: 1.7.16
    requiredVersion: 1.7.0
  - range: ">=1.6.0"
    recommendedVersion: 1.6.13
    requiredVersion: 1.6.0
  - range: ">=1.5.0"
    recommendedVersion: 1.5.8
    requiredVersion: 1.5.1
  - range: "<1.5.0"
    recommendedVersion: 1.4.12
    requiredVersion: 1.4.2
  kopsVersions:
  - range: ">=1.10.0-alpha.1"
    recommendedVersion: "1.10.0-beta.1"
    #requiredVersion: 1.10.0
    kubernetesVersion: 1.10.3
  - range: ">=1.9.0-alpha.1"
    recommendedVersion: 1.9.0
    #requiredVersion: 1.9.0
    kubernetesVersion: 1.9.8
  - range: ">=1.8.0-alpha.1"
    recommendedVersion: 1.8.1
    requiredVersion: 1.7.1
    kubernetesVersion: 1.8.13
  - range: ">=1.7.0-alpha.1"
    recommendedVersion: 1.8.1
    requiredVersion: 1.7.1
    kubernetesVersion: 1.7.16
  - range: ">=1.6.0-alpha.1"
    recommendedVersion: 1.8.1
    requiredVersion: 1.7.1
    kubernetesVersion: 1.6.13
  - range: ">=1.5.0-alpha1"
    recommendedVersion: 1.8.1
    requiredVersion: 1.7.1
    kubernetesVersion: 1.5.8
  - range: "<1.5.0"
    recommendedVersion: 1.8.1
    requiredVersion: 1.7.1
    kubernetesVersion: 1.4.12
I0810 14:36:57.378943   31912 channel.go:239] version range ">=1.10.0-alpha.1" does not apply to version "1.9.2"; skipping
I0810 14:36:57.380866   31912 create_cluster.go:879] networking mode=kubenet => {"kubenet":{}}
I0810 14:36:57.381878   31912 aws_utils.go:39] Querying EC2 for all valid regions

error populating configuration: Got an error while querying for valid regions (verify your AWS credentials?): UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 23eedf1c-1942-420d-9e47-5088836d0ba6
➜  ~

**9. Anything else do we need to know?**
Im following this blog to create the k8s cluster in AWS: https://medium.com/@amimahloof/running-gpu-enabled-instances-on-kubernetes-kops-aws-via-nvidia-device-plugin-cef527abea12

Im able to run my regular aws ec2 run-instances command and it successfully creates ec2 instances. So there is nothing fundamentally wrong with my authorizations, I believe.
This command works: aws ec2 run-instances --instance-type t2.medium --placement AvailabilityZone=eu-central-1c --count 2 --image-id ami-7c4f7097 --subnet-id subnet-0776eb61b36563d1a

**Comment by rifelpet** [comment]
@MKhere the kops command is failing because your AWS credentials do not have `ec2:DescribeRegions` permission. Double check that you have the [appropriate permissions to run Kops](https://github.com/kubernetes/kops/blob/master/docs/aws.md#setup-iam-user).
