### ISSUE TITLE
Question: Best way to sync dependencies with dep?

### ISSUE THREAD

**Issue by billpratt** [kubernetes/kops#5598]
I've tried numerous ways to run ```dep ensure``` on this project. It seems to consistently hang and never finish. Is there a specific dep version I should be using? What is the best way to sync dependencies in the vendor folder?

**Comment by billpratt** [comment]
After more digging I found that ```dep ensure``` hangs on trying to sync a Prometheus dependency ```bitbucket.org/ww/goautoneg``` by running ```git ls-remote```. This repo requires mercurial. After installing mercurial again I was able to proceed.

More info: https://github.com/prometheus/common/issues/17

**Comment by justinsb** [comment]
Yes - this is really frustrating - sorry!

I guess we could add a check for `hg` before syncing, but really that should be dep that does that!  And I think we're likely to adopt vgo in the nearish future.

There is a makefile target, `make dep-ensure` , which also does the required dance with `bazel run //:gazelle`.  We _could_ add the check for hg there I guess!
