### ISSUE TITLE
KOPS should not tag shared (pre created) subnets with "kubernetes.io/role/internal-elb" on cluster update.

### ISSUE THREAD

**Issue by mirnujAtom** [kubernetes/kops#5632]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
KOPS should not add control tags on pre created subnets on the cluster update.

What we are trying to do:
As described at Securing a Cluster document we tried move out master nodes from private subnet to dedicated masters subnets to limit network access to etcd. 
We wanted to use pre-creaetd subnets following steps described in run_in_existing_vpc.md document which says that it is our responsibility to set/update tags in shared VPC.
We set subnet type to Private. Subnets pre-created with correct tags: "kubernetes.io/cluster/k8s.company.tld=shared", "SubnetType"="Private" but without "kubernetes.io/role/internal-elb" since we do not want kubernetes to create application load balancers in the subnets meant for masters.
But if we run kops update it adds this tag, and k8s tries to create internal load balancers in these subnets which is unwanted behavior.

**2. Feel free to provide a design supporting your feature request.**

KOPS should honor pre defined tags or, perhaps, there should be a subnet type for masters with no tags like "kubernetes.io/role/internal-elb"

**Comment by codablock** [comment]
/reopen

Just ran across this same bug. I've pre-created VPCs and subnets and want to control by myself which subnets are used for internal ELBs. Kops is now overriding the tag "kubernetes.io/role/internal-elb" for my pre-created subnets.

**Comment by codablock** [comment]
@mirnujAtom I can't reopen this issue. Can you maybe do that?

**Comment by mirnujAtom** [comment]
/reopen

@codablock, let me try.

**Comment by olemarkus** [comment]
/remove-lifecycle rotten

This should not be too hard to fix. Will be happy to review a PR

**Comment by johngmyers** [comment]
This behavior can already be disabled by setting `cluster.spec.disableSubnetTags: true`.
/close
