### ISSUE TITLE
How to attach an EBS volume to nodes in an instancegroup.

### ISSUE THREAD

**Issue by leeeboo** [kubernetes/kops#5640]
I want to create a new IG for my cluster.
I need attach an EBS volume for each node in this IG.
How can I do that? THX!

**Comment by dzoeteman** [comment]
I don't think you can do this using kops. Especially as the EBS volume would be unique per node. Your best bet would be creating your own daemonset where it creates/attaches the volume to your node.

**Comment by leeeboo** [comment]
Thanks
