### ISSUE TITLE
Scaling down cluster nodes

### ISSUE THREAD

**Issue by montyz** [kubernetes/kops#5646]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
$ kops version
Version 1.9.0 (git-cccd71e67)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
1. `kubectl drain <node>` on a few nodes
2. `kubectl describe node <node>` to check that no pods are running on the nodes
3. update the instance type metadata via `kops replace -f admin/kops-edited-$NAME.yaml ; kops update cluster $NAME --yes` with these settings:

```
maxSize: 20
  minSize: 12
```

4. `kubectl delete node <node>` on the nodes I drained

**5. What happened after the commands executed?**

 `kubectl get nodes` shows that the nodes are no longer in the list. However, in AWS I see that the drained nodes are still up and running. If I terminate one of them via the AWS console, a new one is created. I notice in the AutoScalingGroup that the "desired" number is equal to the max, not the min.

Did I miss a step for shutting down the node after it is deleted?

I'm afraid that if I set desired lower in the AWS console, it will just start randomly terminating nodes instead of removing the nodes I drained.

**6. What did you expect to happen?**

I expected `kubectl delete node <node>` to terminate the AWS instance, and I expected the AWS scaling group would respect the minSize setting and not replace the terminated node.

**7. Please provide your cluster manifest. Execute
```
$ kops get --name $NAME -o yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: NAME
spec:
  additionalNetworkCIDRs:
  - 10.4.0.0/16
  - 10.5.0.0/16
  - 10.6.0.0/16
  additionalPolicies:
    bastion: |
      [
        {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams"
            ],
              "Resource": [
                "arn:aws:logs:*:*:*"
            ]
        }
      ]
    master: |
      [
        {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams"
            ],
              "Resource": [
                "arn:aws:logs:*:*:*"
            ]
        }
      ]
    node: |
      [
        {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams"
            ],
              "Resource": [
                "arn:aws:logs:*:*:*"
            ]
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    kubernetes.io/cluster/NAME: owned
  cloudProvider: aws
  configBase: s3://NAME/NAME
  egressProxy:
    excludes: .local
    httpProxy:
      host: XXX
      port: 3128
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - XXX
  kubernetesVersion: 1.9.9
  masterPublicName: api.NAME
  networkCIDR: 10.3.0.0/16
  networkID: vpc-1f8fea66
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - XXX
  subnets:
  - cidr: 10.4.0.0/24
    id: subnet-6fe64f24
    name: prod4a-private.us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 10.4.1.0/24
    id: subnet-9520acec
    name: prod4a-private.us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: 10.4.2.0/24
    id: subnet-d44f2f8e
    name: prod4a-private.us-west-2c
    type: Private
    zone: us-west-2c
  - cidr: 10.4.3.0/26
    id: subnet-0878d343
    name: prod4a-utility.us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 10.4.3.64/26
    id: subnet-26a22b5f
    name: prod4a-utility.us-west-2b
    type: Utility
    zone: us-west-2b
  - cidr: 10.4.3.128/26
    id: subnet-855e3cdf
    name: prod4a-utility.us-west-2c
    type: Utility
    zone: us-west-2c
  topology:
    bastion:
      bastionPublicName: bastion.NAME
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-16T19:18:47Z
  labels:
    group: jumpbox
    kops.k8s.io/cluster: NAME
  name: bastions
spec:
  image: 727799750006/name-k8s-node-acb6360-2018-08-06T18-58-59Z-encrypted
  machineType: c5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - prod4a-utility.us-west-2a
  - prod4a-utility.us-west-2b
  - prod4a-utility.us-west-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-16T19:18:46Z
  labels:
    kops.k8s.io/cluster: NAME
  name: master-us-west-2a
spec:
  associatePublicIp: false
  image: 727799750006/name-k8s-node-acb6360-2018-08-06T18-58-59Z-encrypted
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - prod4a-private.us-west-2a
  tenancy: dedicated

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-16T19:18:46Z
  labels:
    kops.k8s.io/cluster: NAME
  name: master-us-west-2b
spec:
  associatePublicIp: false
  image: 727799750006/name-k8s-node-acb6360-2018-08-06T18-58-59Z-encrypted
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b
  role: Master
  subnets:
  - prod4a-private.us-west-2b
  tenancy: dedicated

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-16T19:18:46Z
  labels:
    kops.k8s.io/cluster: NAME
  name: master-us-west-2c
spec:
  associatePublicIp: false
  image: 727799750006/name-k8s-node-acb6360-2018-08-06T18-58-59Z-encrypted
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2c
  role: Master
  subnets:
  - prod4a-private.us-west-2c
  tenancy: dedicated

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-16T19:18:47Z
  labels:
    kops.k8s.io/cluster: NAME
  name: nodes
spec:
  additionalSecurityGroups:
  - sg-67f9ac18
  - sg-3bf8ad44
  associatePublicIp: false
  image: 727799750006/name-k8s-node-acb6360-2018-08-06T18-58-59Z-encrypted
  machineType: r4.2xlarge
  maxSize: 20
  minSize: 12
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - prod4a-private.us-west-2a
  - prod4a-private.us-west-2b
  - prod4a-private.us-west-2c
  tenancy: dedicated
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Not sure that's relevant here.

**9. Anything else do we need to know?**

**Comment by justinsb** [comment]
It's a topic of some contention, but `kubectl delete node` only unregisters the node, it doesn't currently delete the AWS instance.

I think there's probably room for a controller which does delete instances which haven't registered as nodes or are otherwise unhealthy, but I don't know of one.

I normally get the aws instance id from `kubectl describe node` and terminate it directly using e.g. `aws ec2 terminate-instances`

**Comment by montyz** [comment]
My goal was to rescale my instance group to 1/2 the number of nodes on an instance type 2x bigger RAM & CPU. Naively I changed the instance type and cut min/max in half. 

I expected that during the rolling update kops would drain a node and launch a new one and repeat until the old nodes were gone and the new ones were up. 

Instead when `kops update cluster` was run, the AWS scaling group numbers got halved and AWS shut down half of my nodes immediately.

**Comment by montyz** [comment]
I also discovered that via the AWS Console's autoscaling screen, instances tab, I can detach a node and opt to not have it replaced. That will decrease the desired amount by one and detach the node. Then I can terminate it and it won't be replaced by a new node. Doing this after `kubectl delete node` seems to work the way I expect.

**Comment by huang-jy** [comment]
You don't need to drain directly using kops. Changing the instance group sizes down then doing the update will do the draining and deleting. At least in theory....

**Comment by montyz** [comment]
@huang-jy that is what I tried initially. I had 20 nodes of size m4.xlarge, updated the spec to be 10 nodes of m4.2xlarge. As soon as I updated the cluster, the autoscaling group killed 10 nodes at once, without draining them.

**Comment by montyz** [comment]
I updated 20->10 on max/min, I don't know how to set desired. I did not install the horizontal autoscaler, I thought it was automatically installed with kubernetes. Looking at https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ I don't see any specific installation instructions. Is there something I need to do to install this?

**Comment by huang-jy** [comment]
@montyz sorry, I was referring to autoscaling the nodes, not the pods. Horizonal pod autoscaler increases replicas to cope with demand. It's cluster autoscaler I was thinking of:

https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler

This will scale up/down nodes as needed by overall workload. You set a max/min and the addon decides whether to add or take away nodes as needed.

For example, I had my instance group set as min 1, max 10, and the same values set within the addon and it scales up when I hammer it with many cron jobs.

**Comment by mrballcb** [comment]
I just went through a cluster-autoscaler update on our systems, so I want to mention one additional fact: the cluster-autoscaler does not inherit or automatically detect the min:max settings from your cluster's node auto scaling group.  When you deploy the cluster-autoscaler, you must set the same min:max values in the cluster-autoscaler manifest or helm chart.  And if you change min:max in your nodes IG, you also need to change it in your cluster-autoscaler manifest or helm chart and redeploy that.

**Comment by huang-jy** [comment]
@mrballcb Correct, you have to make sure they are in line. Or a subset.

For example, I have min 1, max 10 on the instance group, but min 3, max 10 on the autoscaler.

This means that my cluster passes validation even if I only have 1 worker node, but the autoscaler will keep the desired at 3 minimum.
