### ISSUE TITLE
CoreDNS pods get OOM Killed

### ISSUE THREAD

**Issue by bcorijn** [kubernetes/kops#5652]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.10.5

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Change the cluster spec to provision CoreDNS as DNS provider

**5. What happened after the commands executed?**
Two coreDNS pods came up alongside my 4 old kubeDNS pods. I've been running it like this to evaluate how well it works. However, I'm seeing restarts on the coreDNS pods due to hitting the 170mb memory limit, which I believe is not configurable without manually editing the manifest? 

**6. What did you expect to happen?**
CoreDNS to have enough memory requests to run stable

**9. Anything else do we need to know?**
My workloads do a lot of DNS requests, but KubeDNS never really had memory issues (had other issues with it though). I could not really find any memory recommendations for CoreDNS.

**Comment by Pharb** [comment]
I'm running CoreDNS with kops 1.10.0 on AWS for 4 days now.

I'm not an expert on CoreDNS but the following Prometheus metric shows between 100.000 to 600.000 DNS requests per hour in my cluster.
`sum(increase(coredns_dns_request_count_total[1h]))`
The memory usage for a single CoreDNS pod never went above 20 MB and stays around 19 MB for my cluster.

@bcorijn Could you maybe share some numbers what you mean by "a lot of DNS requests"?

Maybe the memory limit for CoreDNS could be configurable? I'm not sure how the current 170 MB were decided.

**Comment by chrisohaver** [comment]
> not configurable without manually editing the manifest?

You can configure it by editing the coredns deployment.  Try bumping the limit up to 256.

> I'm not sure how the current 170 MB were decided.

It worked in tests at that value as a safe "one-size-fits-most" setting.  Though recently we have seen a couple of reports that it has been too small.  No explanation yet as to why this is case for a few, and not for most others. It's possible that this issue is under reported, since it's easy to increase the limit in the deployment.

**Comment by bcorijn** [comment]
@chrisohaver editing the deployment was what I was referring to, doable but not my preferred long-term solution.

I will try to get some usage metrics, but I've been having some prometheus troubles so it's a bit harder than I had hoped for. I can already attach a screenshot of the memory usage from Sysdig monitor, which goes far above the 20mb as you can see. I have just bumped the limit to 256 to see if it stabilises somewhere along the way. This is with `pods insecure`, changing that to verified makes the memory usage increase even faster.
![screen shot 2018-08-21 at 10 11 22](https://user-images.githubusercontent.com/22590657/44389326-d2e17300-a52a-11e8-881a-ab7245decb2d.png)

**Comment by bcorijn** [comment]
Okay, got prometheus back yesterday. So can answer a few more questions about the usage overnight.
@chrisohaver:
- What is the preferred way to measure QPS? Making sure we are talking about the same numbers.
- Around 120 services and 450 pods, bit of autoscaling going on but not much. The two services doing most of the DNS requests have the ndots options removed from their dns options using DNSConfig in the podspec. This had a noticeable effect in the past with KubeDNS, haven't checked what would happen if I re-enable that on CoreDNS

@Pharb 
See graph below, so I seem to be doing _quite_ a lot more if I understand the increase metric correctly? This is only the 4 CoreDNS pods, there's another 2 KubeDNS pods btw.
![screen shot 2018-08-23 at 10 30 16](https://user-images.githubusercontent.com/22590657/44514404-508ab780-a6c0-11e8-8cbf-311e1698a9a4.png)

**Comment by chrisohaver** [comment]
Thanks for the graphs!

@bcorijn, are you generating artificial DNS load?  That the cache size continually grows at a almost constant rate until it hits max capacity is unusual.  I'd expect that the slope would decay over time, as it more often start hitting cache entries that already exist. Or, are your cluster's dns queries of the nature that they are constantly changing over time (like reverse lookups of requests external client IPs)?

Familiarizing myself more with the implementation of cache plugin, CoreDNS's implementation is not memory optimized.  Entries are not evicted from cache until the maximum cache size is reached. If the set of unique query names made constantly increases, cache will constantly increase until maximum cache size is reached.

**Comment by chrisohaver** [comment]
@bcorijn, Thanks again for the data.  Based on this, I'm going to recommend a limit of 350MB.  This is due to the somewhat minimum allowed default cache size in CoreDNS.
 
There is an open PR (coredns/coredns#2030) to allow smaller cache sizes.  You can try building this PR and see if it helps if you specify a smaller cache.

**Comment by chrisohaver** [comment]
Regarding coredns/coredns#2030 ... hoping to get this into the coredns release asap...

**Comment by bcorijn** [comment]
@chrisohaver I am not generating artificial DNS load, but I do have quite a particular type of application load that generates a lot of unique DNS queries (we run a SEO website analysis tool, so we fetch a lot of external websites). 
I would have expected that the cache evicts entries based on their TTL, if that only happens when the cache is full then I can indeed understand where the load comes from! I looked into reducing the cache size, but noticed 130k was the minimum indeed, which felt a bit excessive to me. Happy to see a PR already open for it.

**Comment by bcorijn** [comment]
@chrisohaver: I took a look at the cache implementation and with the design choices of a large minimum cache-size and no eviction of old records, I would expect most long-running deployments doing "random" external DNS requests to run into this issue soon or later. I guess the speed and size at which I do DNS resolutions has just made it surface a lot faster.

While reducing the cache-size solves the total memory footprint, I must say it feels a bit counter-intuitive and inefficient resource-wise. I understand that this way probably performs better while querying (cfr https://github.com/coredns/coredns/issues/2035), it feels concerning that the TTL parameter is only used to evaluate if a cache hit is stale or not and nothing more, so you might even evict fresh records while there are 100k expired records in your cache. 

I have my TTL set to 30s as I know I do a lot of DNS resolution but they will almost always be in short bursts and not needed anymore after, I more or less expected the records to be removed once they expired. If anything some better documentations on the TTL and eviction strategy would be useful.

All in all, this issue probably would have been better in the CoreDNS repo and thanks for the help 👍

**Comment by chrisohaver** [comment]
> ... a particular type of application load that generates a lot of unique DNS queries

Ah cool, thanks, I like it when evidence fits the theory.  I was thinking unique names via client ip reverse lookups, but website analysis/crawling would do the same.

> feels a bit counter-intuitive and inefficient resource-wise

@bcorijn, Yes, as I understand, it's intentionally geared for CPU/speed efficiency, not memory efficiency.  Although, the high minimum cache size was probably not a completely intentional design decision (I suspect it was unintentionally changed during a refactor of the cache about a year ago).

Thanks again for the detailed report and data gathering!

**Comment by bcorijn** [comment]
Deployed 1.2.2 and behaves as expected!  Might tune my cache a bit more, but wanted to evaluate default behaviour first. Thanks again for the quick fix and release @chrisohaver and @miekg

![screen shot 2018-08-31 at 10 16 58](https://user-images.githubusercontent.com/22590657/44901234-15633680-ad07-11e8-92db-c40eb1cd51cb.png)

Not sure if I should already close this issue, as kops is still shipped with the 1.1.3 image and referring to the google container registry instead of the coredns dockerhub one (where the latest release is not available)?

**Comment by chrisohaver** [comment]
@bcorijn, Thanks for verifying and following up! And thanks agains for your help tracking this down.

CoreDNS 1.2.2 is available from google container registry now.

**Comment by bcorijn** [comment]
This can be closed a kops now includes this patched version I believe.
