### ISSUE TITLE
Provide terraform output of api ELB

### ISSUE THREAD

**Issue by gtmtech** [kubernetes/kops#5670]
Closely related to a lot of bugs already raised about split-horizon DNS and private topology, kops still has the glaring bug that when using `--dns private` and `--dns-zone` with a split-horizon route53 zone (ie public/private part), the api record for the ELB is created in the private and not the public route53 zone counterpart, rendering the entire cluster unavailable on bootstrap. The docs also do not seem to mention that --dns-zone is supposed to take a ZONE ID, and not a ZONE name when using split horizon dns, so that the dnscontroller.go part of nodeup does not get confused and fail to add the records for etcd on bootup of instances in the master auto-scaling-group.

One way that this would easily be able to be worked around, is if the kubernetes.tf terraform file contained a new "output" for the api "aws_elb" that was created. This would mean the user could reference the ELB to create a new record in the public route53zone counterpart and have the cluster bootstrap successfully. Because kops creates an elb name with 6 random letters each time, it is not possible to currently use a terraform datasource lookup to achieve this. 

Alternatively the bug could be fixed with the addition of a new flag --public-dns-zone so that the api record was created in the right place in the first instance.

**Comment by dusansusic** [comment]
It would be awesome if Bastion ELB has terrafrom output.

**Comment by chenrui333** [comment]
👍
