### ISSUE TITLE
Add support of new T3 family

### ISSUE THREAD

**Issue by wanghanlin** [kubernetes/kops#5680]
Feature request to add support of newly launched T3 family. [aws-blog-link](https://aws.amazon.com/blogs/aws/new-t3-instances-burstable-cost-effective-performance/)

**Comment by thedarkfalcon** [comment]
This would be **very** useful for me.  I have been waiting for support for T2 Unlimited (#4032) for a long time now, however as that has yet to be implemented within kops, T3 support would be a suitable replacement (as T3's all have the Unlimited functionality included by default).

**Comment by thedarkfalcon** [comment]
:D
Can't wait for next release.. literally.. might compile the code instead of waiting lol.

**Comment by thedarkfalcon** [comment]
@justinsb Bump for patch release :D

**Comment by jnicholls** [comment]
@justinsb I second the necessity for putting out a patch release with support for t3. I may get adventurous and compile a build with this support. I foolishly reserved some t3 instances thinking kops would support it, because why wouldn't it? Bit of a shock.

**Comment by jnicholls** [comment]
While I think your tone could be better @manojlds I agree with you that it would be good to rethink instance support and the ability to modify it dynamically either through a manifest file or something, rather than hardcoded into the binary.

**Comment by thedarkfalcon** [comment]
FYI 1.11.0-beta-1 was recently released
https://github.com/kubernetes/kops/releases/tag/1.11.0-beta.1

Although 1.11 still won't support dynamic instance types, it at least has t3 instance support.
https://github.com/kubernetes/kops/blob/1.11.0-beta.1/upup/pkg/fi/cloudup/awsup/machine_types.go

**Comment by lshahar** [comment]
there is ETA for this release?

**Comment by lshahar** [comment]
> FYI 1.11.0-beta-1 was recently released
> https://github.com/kubernetes/kops/releases/tag/1.11.0-beta.1
> 
> Although 1.11 still won't support dynamic instance types, it at least has t3 instance support.
> https://github.com/kubernetes/kops/blob/1.11.0-beta.1/upup/pkg/fi/cloudup/awsup/machine_types.go

There is ETA for the final version? or any workaround to use not supported types?

**Comment by thedarkfalcon** [comment]
@Ishahar the work around is to install the beta.
As for when the final release will be available, best I can say is to look at the previous release history for an estimate. Looks like 20-40 days between beta and official release.

https://github.com/kubernetes/kops/releases
