### ISSUE TITLE
Ability to change CoreDNS configuration

### ISSUE THREAD

**Issue by maver1ck** [kubernetes/kops#5685]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Right now CoreDNS configuration is created from template when only variable is  KubeDNS.Domain.
I'd like to change this configuration to use stubZones feature.

**2. Feel free to provide a design supporting your feature request.**

Maybe new fields in cluster.yaml could be an option ?

**Comment by cristian-radu** [comment]
Perhaps allow passing a user defined configmap for CoreDNS, since there are many configuration options available including plugins such as Route53 for example.
