### ISSUE TITLE
kube-dns setup is not up to date with upstream

### ISSUE THREAD

**Issue by Savar** [kubernetes/kops#5699]
**1. What `kops` version are you running?
1.9.2

**2. What Kubernetes version are you running?
 1.10.5

**3. What cloud provider are you using?**
AWS

Upstream the kube-dns pods have an AntiAffinity setting to prevent them running on the same host if possible:

https://github.com/kubernetes/kubernetes/pull/52193/files#diff-b63e78dfe53c93bc837a01957a137151

The kops version on the other hand does not contain that:

https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template

So in our case both kube-dns (not more needed traffic-wise) pods were running on the same host and a rolling update was simply kill a lot of stuff as DNS was temporarily down.

Is there any reason to not have the AntiAffinity setup merged back?

**Comment by Savar** [comment]
the same probably applies to the newer coredns variant

https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template

**Comment by rajansandeep** [comment]
@savar kube-dns and CoreDNS is up to date with upstream. The AntiAffinity was added and then reverted due to performance issues.
See https://github.com/kubernetes/kubernetes/pull/59357 and https://github.com/kubernetes/kubernetes/issues/54164

**Comment by Savar** [comment]
thanks.. I really hope the AntiAffinity performance problems will be solved as this is kind of an important feature
