### ISSUE TITLE
AWS CNI does not support taints

### ISSUE THREAD

**Issue by oded-dd** [kubernetes/kops#5709]
The kops yaml used for AWS CNI is incorrect, and should be replaced.

**Comment by oded-dd** [comment]
Any news about it? It is a blocker for working with taints

**Comment by xrl** [comment]
What config YAML are you using with Kops? You should use the issue template.

**Comment by rifelpet** [comment]
@oded-dd Can you confirm that #5654 addresses the issue? The fix is in the latest Kops 1.11 beta release.
