### ISSUE TITLE
Please cut a release for AWS t3. machine type support

### ISSUE THREAD

**Issue by macropin** [kubernetes/kops#5714]
Support for t3 machine types was added in ca3ad3de6a323b6f0b59d4a80884a8d58a7ceb69, but was not included in 1.10.0 release. Please consider cutting a release to add this capability.

**Comment by Pehesi97** [comment]
+1

**Comment by rainchei** [comment]
+1

**Comment by rifelpet** [comment]
1.11.0 stable has been released and supports T3 instance types. I'm going to go ahead and close this out. If you run into any problems using T3s with Kops 1.11.0 feel free to open a new issue.

/close
