### ISSUE TITLE
Route53 in a separate account

### ISSUE THREAD

**Issue by livingeek** [kubernetes/kops#5729]
Our AWS setup involves multiple accounts, and the domain name that we leverage for all of our services lives in one account while infra may live in a few others depending on it being production, testing, or dev.  While working with Kops I am unable to get a clean deployment running because the DNS is being added to a hosted zone in account A, but account B is where the zone route53 is sourcing from exists.  

I'd like to see the possibility to define multiple accounts when creating a cluster via Kops.  This would allow us to define that our DNS zone file lives in a separate account from where the cluster is being created, and we could create the DNS in account B while having our cluster infrastructure created in account A.  If possible it could simply be an ENV variable we could define such as AWS_DNS_PROFILE so that we can simply point to the profile already defined in our typical workflows.

**Comment by mrballcb** [comment]
We handle this exact scenario by delegating subzones in account A to hosted zones in account B.  Then our Kube stack in account B has an IAM role that allows external-dns to update records in hosted zones in account B.  When you do dig +trace, you see one extra hop for the dns delegated to the different servers.

To do the delegation, you just create a hosted zone in account B and get the 4 NS's.  Then in account A, you create an NS record for the subdomain with those 4 NS records in it.  Example:

```
example.com.   # hosted zone in account A
prod.example.com. IN NS (the 4 NS records for prod.example.com in account B)

prod.example.com.    # hosted zone in account B
```
Then you create *.prod.example.com records in your helm charts.

Note that this also can work for *.example.com records directly, but it's a little more manual work.  For example, the record *login.example.com*:

```
example.com.    # hosted zone in account A
login.example.com. IN NS (the 4 NS records for example.com in account B)

example.com.    # hosted zone in account B
```
Repeat that for each *.example.com record you want to create.

The first time I ever saw this I thought "there is no way this can work."  But in fact it does and works well.

There is also AWS IAM cross account delegation that could maybe be used for this same effect, but I have only ever done it once, and it was *NOT* Kube related nor even DNS (it was access to an S3 bucket).  YMMV

**Comment by livingeek** [comment]
After reading your comment went back and reread the docs and see that it says the same thing 🤦‍♂️  Thank you for making it more clear to me in your comment I really appreciate it.  If we ever run into each other I owe you a beverage of your choice.  Thanks again!
