### ISSUE TITLE
How to restore Kops config?

### ISSUE THREAD

**Issue by angapov** [kubernetes/kops#5735]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.9.1
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.10.4
**3. What cloud provider are you using?**
aws

I have accidentally deleted S3 bucket with Kops configuration. The cluster is up and running however I cannot scale it anymore. How can I restore or recreate Kops configuration from running cluster?

**Comment by chrisz100** [comment]
As far as I am concerned there is no way to reverse-engineer the kops configuration from the cluster itself. 
From what I know about S3 it is also impossible to retrieve a deleted S3 bucket. If you don't have a backup you probably need to create a new cluster or scale by editing the Autoscaling Groups directly on AWS.

**Comment by angapov** [comment]
Nevermind, I created configuration from running cluster manually. I though there is some faster way, but no.
