### ISSUE TITLE
Support for newer docker versions like 18.03

### ISSUE THREAD

**Issue by lnformer** [kubernetes/kops#5747]
I'm running currently Kops 1.10.0 with Kubernetes 1.10.5 and docker version 17.03 and I have encountered pods that stuck in Terminating state because of issues related to docker 17.03 which you can see here https://github.com/docker/for-linux/issues/1 and fixed in 18.03

**Comment by goodspark** [comment]
I'd like support for Docker server 18.09. I'm trying to use multi-stage builds in Docker on Jenkins on Kubernetes.

**Comment by tsuna** [comment]
/remove-lifecycle stale

There are bad bugs in 18.03/18.06, so having 18.09 would be great.
