### ISSUE TITLE
Use kops to setup kube cluster on AWS Lightsail

### ISSUE THREAD

**Issue by badoet** [kubernetes/kops#5749]
Is it possible to setup kube cluster using kops on AWS Lightsail?

this options is probably the most cost saving at the moment
and flexible at the same time, as we can leverage other AWS services

or it this capability is already supported?

**Comment by Macmee** [comment]
@ihoegen I wish I could use kubernetes on lightsail for the bandwidth savings. Bandwidth on EC2 is very expensive compared to lightsail.
