### ISSUE TITLE
Kubernetes images dowload urls used by KOPS - To be used white-listing in proxy

### ISSUE THREAD

**Issue by ab73863** [kubernetes/kops#5753]
Hi Team,

We are trying to set up the Kuberentes cluster within our enterprise and we are only allowed to outbound\egress from the EC2 instances by making the needed egress host names whitelisted in the proxy.

Could anyone please point to a documentation or guide by giving us the kuberentes and related image dowload url hostnames that can used in proxy for whitelisting so that KOPS can initiate the dowloading of images without any  #block.?

Regards
Arun

**Comment by xrl** [comment]
I would hop in to the failing ec2 instance and look at the logs. You'll find the bootstrap script has logs you can follow along.
