### ISSUE TITLE
The documentation for Running in a shared VPC isn't accurate

### ISSUE THREAD

**Issue by ckth** [kubernetes/kops#5754]
The documentation for" Running in a shared VPC":
https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md#shared-subnets
 doesn't appear to be correct.

Step 1 indicates that simply using --vpc  and --network-cidr is enough to use an existing VPC. It is not. Kops will still attempt to create new subnets rather than using existing subnets. Running the following:

`kops create cluster --master-zones=us-east-1a --zones=us-east-1a --topology=private --dns-zone=xxxxxxxxxxx --networking=calico --vpc=vpc-xxxxxxxxxx --topology=private --name=mycluster.example.com --state=s3://k8s-state --network-cidr=10.100.0.0/16  
`
will result in the following error:

`"InvalidSubnet.Conflict: The CIDR 'x.x.x.x/xx' conflicts with another subnet " 
`
Under "Advanced Options for Creating Clusters in Existing VPC" the documentation  states:

`"--vpc is optional when specifying --subnets."`

I don't find this to be true either. Leaving out the --vpc and specifying --subnets using:

`kops create cluster --master-zones=us-east-1a --zones=us-east-1a --topology=private --dns-zone=xxxxxxxx --networking=calico --topology=private name=mycluster.example.com  --state=s3://k8s-state --network-cidr=10.100.0.0/16  --subnets=subnet-xxxxxxxxxx
`
Results in the Error:

`"error describing VPC: error listing VPCs: InvalidVpcID.NotFound: The vpc ID '' does not exist"`

In fact it seems that specifying --vpc and --subnets are mutually exclusive. Running the following:

`kops create cluster --master-zones=us-east-1a --zones=us-east-1a --topology=private --dns-zone=xxxxxx --networking=calico --vpc=vpc-xxxxxxx --topology=private --name=mycluster.example.com --state=s3://k8s-state --network-cidr=10.100.0.0/16  --subnets=subnet-xxxxxxxxx`

will result in the following error:

```
spec: Invalid value: []kops.ClusterSubnetSpec{kops.ClusterSubnetSpec{Name:"us-east-1a", CIDR:"10.100.0.0/23", Zone:"us-east-1a", Region:"", ProviderID:"subnet-xxxxxxxx", 
Egress:"", Type:"Private", PublicIP:""}, kops.ClusterSubnetSpec{Name:"utility-us-east-1a", CIDR:"10.100.32.0/22", Zone:"us-east-1a", Region:"", ProviderID:"", Egress:"", Type:"Utility", PublicIP:""}}: cannot mix subnets with specified ID and unspecified ID
```
Additionally and inexplicably Kops is also trying to create subnet 10.100.32.0/22 despite using the --vpc and --subnets flags.

Lastly the documentation in this section also shows an environmental variable of:
`export SUBNET_IDS=$SUBNET_IDS `

However SUBNET_IDS plural is not actually defined anywhere. 

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.10

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Kubernetes isn't currently running due to the above.

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

The commands are listed inline above.

**5. What happened after the commands executed?**

They failed with error messages listed inline above.

**6. What did you expect to happen?**

I expected kops to successfully provision a new cluster into the existing(shared) VPC.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

I can't actually get a successful cluster to provision due to the above errors.

**Comment by ArcticSnowman** [comment]
```--vpc is optional when specifying --subnets. When creating a cluster with a private topology and shared subnets, the utility subnets should be specified similarly with --utility-subnets.
```

**Comment by Ralnoc** [comment]
/reopen
/remove-lifecycle rotten

This is still very much an issue. 
As detailed in the original issue, kops will not let you run the command if you do not specify `--vpc` for the AWS implementation for shared VPCs and shared subnets. However, if you specify `--subnets`, it adds some of the subnets specified, while also trying to automatically add ones it has identified and breaks with the `cannot mix subnets with specified ID and unspecified ID` error

**Comment by arontx** [comment]
Running into this exact issue with `cannot mix subnets with specified ID and unspecified ID` has anyone come up with a workaround or fix??

**Comment by wildk1w1** [comment]
Looking at the returned json showed kops was trying to create a utility subnet for every node subnet

I Found that passing the same node subnet list to the utility subnet worked around this issue.
where KOPS_SUBNETS = comma-separated list of AWS subnets you have set-up for the private networks.

**Comment by markeastwood1** [comment]
There are definitely issues here... why shouldn't I be able to specify and existing VPC and subnets to use... they were built with my CF templates that I don't want to change. The whole idea is to make this repeatable and automated. I'm peered with another VPC, I have the IGW and NAT gateway already and I have appropriate route tables for internet/net and the peer.

kops version = Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)

I was able to get past "spec.subnets[1].id: Forbidden: cannot mix subnets with specified ID and unspecified ID" only by using both --subnets and --utility_subnets with the same values. My current experiment is to specify only the private subnets.
