### ISSUE TITLE
Documentation Incorrect for Feature Gates

### ISSUE THREAD

**Issue by daviddyball** [kubernetes/kops#5765]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`1.9.0 (git-cccd71e67)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

`AWS`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

According to the [documentation](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md), enabling feature-gates is as simple as adding:

```
spec:
  kubelet:
    featureGates:
        SomeGateHere: "true"
```

However, in most cases the feature-gate needs to be enabled for the `kubeControllerManager` as well, which would have the spec look like this:

```
spec:
  kubelet:
    featureGates:
        SomeGateHere: "true"
  kubeControllerManager:
    featureGates:
        SomeGateHere: "true"
```

**5. What happened after the commands executed?**

The documentation not explaining that some feature-gates require multiple points of configuration meant that the requested feature-gate was never actually deployed.

**6. What did you expect to happen?**

The feature gate should have been deployed, but the documentation was misleading about feature-gate enabling.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Not 100% needed in the case as it's more guidance/documentation that is needed.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

**Comment by legal90** [comment]
This is still actual and may cost several hours waisted while looking for a reason why the feature gate doesn't work when you followed the documentation.

/remove-lifecycle stale
