### ISSUE TITLE
Unknown flag: --authorization-rbac-super-user

### ISSUE THREAD

**Issue by nutchalum** [kubernetes/kops#5766]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0 (git-8b52ea6d1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.11.3

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops edit cluster (from version 1.9.x to 1.11.3)
kops update cluster --yes
kops rolling update --yes

**5. What happened after the commands executed?**
kube-apiserver can't start with log
```
error: unknown flag: --authorization-rbac-super-user
```

**6. What did you expect to happen?**
kube-apiserver start successfully

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
kubeAPIServer:
    authorizationRbacSuperUser: admin
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I'm just trying to upgrade cluster (from 1.9.x to 1.11.3)

**Comment by geojaz** [comment]
Thanks for the report- A couple points here...

kubernetes 1.11 is not currently supported by kops 1.10. We are working on getting kops 1.11 alpha released asap, and at that point, we'd love to hear how your experience goes. 

Second, your report is a little sparse. so it's difficult to tell exactly what's going on, but upgrades in k8s, no matter which bootstrapping/management tool, seem to go smoother one minor release at a time. ie: 1.9->1.1, and then upgrade 1.10->1.11. Have you tried doing an upgrade with this flag to a 1.10.x version? 

If you could try this and turn on verbose logging `--v=10`, I would be interested to see what happens. And then if that works, it's worth trying to go to 1.11 with the verbose logging on still, and reporting your experience- good or bad. If it doesn't work and we have a clear problem statement/supporting evidence, it will help us get kops 1.11 released faster. 
Thanks!

**Comment by legal90** [comment]
The same issue: https://github.com/kubernetes/kops/issues/6046
