### ISSUE TITLE
Customize how node names are generated

### ISSUE THREAD

**Issue by miracle2k** [kubernetes/kops#5767]
Currently, the nodes I see in `kubectl get nodes` look like this:

```
ip-172-20-32-129.eu-west-2.compute.internal
```

I find those unhelpful. Here is how I see it:

First, the internal IP is used here, so to actually connect to a node, to get it's ip address, I have to use `-o wide`.

Second, I do not see the instance group. If I have a bunch of regular and one or two beefier machines, there is no way for me to see, for example in `kubectl top pods` which one is which.

Third, I see no information that I can even match with the instance list in the AWS UI. There, by default, I see: 

```
Name: ig-name-mydomain.org  
Instance-ID: i-0fa7abf3e7d6538a2
Public-DNS: ec2....4.eu-west-2.compute.amazonaw
```

So if I see an instance in the web UI, and I would like to do a `kubectl describe` on that node, I have to find the private dns name in the AWS UI.

Similarly, the reverse: I actually have to use the search feature to search for the private IP to find a node by the information given to me in the `kubectl get nodes` output.

Nothing impossible, but I feel the user experience would be so much nicer if the names actually meant something, and where human readable:

`igName-{1,2,3,4,...}`

or:

`igName-amazing-einstein`

or a different scheme. Whatever it is, I would like to see it match the `Name` column in the AWS instance list.

**Comment by miracle2k** [comment]
Looking into this, it seems that at least on AWS, it is currently impossible for a custom hostname to be specified due to a Kubernetes limitation:

https://github.com/kubernetes/kubernetes/issues/64659
https://github.com/kubernetes/website/pull/8873

It seems that until Kubernetes supports this, there is little we can do here.

**Comment by swarupdonepudi** [comment]
I would like to see the node names to be in the following format:

For etcd: <ip-xx-xx-xx-xx>.etcd.<cluster-domain>
For master nodes: <ip-xx-xx-xx-xx>.master.<cluster-domain>
For worker nodes: <ip-xx-xx-xx-xx>.worker.<cluster-domain>

Benefits of the above format:

1. Easy to identify the instance group etcd or master or a worker node
2. Easy to setup SSH access using wildcards in ~/.ssh/config file

**Comment by rocktavious** [comment]
I agree with @swarupdonepudi but for worker pool nodes i'd like to take the name from instance group definition and use that.  We run a few worker pools in each k8s kops cluster and knowing which nodes go with which workerpool is hard to decern unless you do  `kubectl get nodes --show-labels` but the main usecase we have is something like this `kubectl get pods -l app=ourapp -o wide` which prints out the node name the pod is running on (and it would be nice to look at the node node and know which worker pool it was in)

**Comment by tsupertramp** [comment]
I want to add that adding instance group into name would help in a lot of exporter cases e.g. https://github.com/google-cloud-tools/kube-eagle/ to identify on which instancegroup the container is running without the stress to make selects or anything like that.

It would allow a lot easier monitoring.

**Comment by rocktavious** [comment]
Bumping to keep alive - i really want this to become a thing as it would help out alot with larger more diverse clusters!

**Comment by pradeepnnv** [comment]
This feature would be really helpful.

**Comment by and3rson** [comment]
Bumping. Would love to give nodes nicer names.

**Comment by jasoares** [comment]
Bumping, would love to have this....

**Comment by shachar-ash** [comment]
Bumping, this feature would be amazing!

**Comment by jmcdonagh** [comment]
yea if the nodenames could begin with a user-specified prefix, that'd be great. simple use case is setting up your ssh config to use the bastion, you coud have Host prefix-* then the ProxyJump command to go through the bastion. ip-whatever default prefix is not great because you could have multiple clusters with that same prefix with different bastions.

**Comment by liuxunorg** [comment]
This feature would be really helpful.

**Comment by Tawmu** [comment]
Bumping to keep alive - would be very helpful.

**Comment by rocktavious** [comment]
+1

**Comment by paul-theorem** [comment]
I'd like to see this.

**Comment by shachar-ash** [comment]
This would be awesome!

**Comment by olemarkus** [comment]
Most of this has little to do with kops and more to do with k8s in itself.

In kops 1.19 we do have `kops get instances` that will provide some of the info requested above though.

**Comment by olemarkus** [comment]
Unless someone has an idea of what can be improved from the kOps side, I will close this one.

**Comment by olemarkus** [comment]
/remove-lifecycle stale
/close

Again: the node names comes from the k8s cloud provider and there is nothing kops can do to solve this.
