### ISSUE TITLE
Support metrics-server 0.3

### ISSUE THREAD

**Issue by amitsaha** [kubernetes/kops#5770]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

The current [metrics-server addon](https://github.com/kubernetes/kops/tree/master/addons/metrics-server) will need to support [v0.3.0](https://github.com/kubernetes-incubator/metrics-server/releases/tag/v0.3.0) of `metrics-server`. 

**2. Feel free to provide a design supporting your feature request.**

If I attempt to just upgrade the docker image in the addon YAML, the first error we get in the pod is: `
panic: unknown flag: --source`.  Removing that, the server starts correctly, but we get:

```
E0912 01:18:01.560447       1 manager.go:102] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:ip-172-16-94-217.ap-southeast-2.compute.internal: unable to fetch metrics from Kubelet ip-172-16-94-217.ap-southeast-2.compute.internal (ip-172-16-94-217.ap-southeast-2.compute.internal): Get https://ip-172-16-94-217.ap-southeast-2.compute.internal:10250/stats/summary/: x509: certificate signed by unknown authority, unable to fully scrape metrics from source kubelet_summary:ip-172-16-48-234.ap-southeast-2.compute.internal: unable to fetch metrics from Kubelet ip-172-16-48-234.ap-southeast-2.compute.internal (ip-172-16-48-234.ap-southeast-2.compute.internal): Get https://ip-172-16-48-234.ap-southeast-2.compute.internal:10250/stats/summary/: x509: certificate signed by unknown authority]
```

I am using `1.10` of kops and Kubernetes version `v1.10.7`.  I would be happy to look into this/create a PR, if I get some help.

**Comment by s1113950** [comment]
I got 0.3 to work in this way:
https://github.com/kubernetes/kubernetes/issues/44540#issuecomment-424508625

**Comment by itskingori** [comment]
See https://github.com/kubernetes/kops/pull/6201.
