### ISSUE TITLE
CoreDNS cache specification

### ISSUE THREAD

**Issue by mooneygr** [kubernetes/kops#5773]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
In Kops/K8s 1.9 kube-dns was the default, and it allowed the specification of CacheMaxSize to allow some customisation of the dnsmasq container/the DNS cache. 

With 1.10, making [Kube-DNS optional](https://github.com/kubernetes/kubernetes/pull/57113); and from 1.11 having CoreDNS be the [kubeadm default](https://kubernetes.io/blog/2018/07/10/coredns-ga-for-kubernetes-cluster-dns/), it feels like there should be some customization possbile of the [cache setting](https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template#L68) in the kops default template.

**2. Feel free to provide a design supporting your feature request.**
Since KubeDNS.Domain is already used in the CoreDNS template, it seems like it'd be feasible to add some new CoreDNS specific fields in the [KubeDNSConfig struct](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/cluster.go#L322). 

Seems like it would be ok to start with TTL and Zones being customisable; with future extension possible (if demand exists) to allow success, denial, and prefetch customizations later. 

Useful references [CoreDNS 1.2.1 cache spec](https://github.com/coredns/coredns.io/blob/2be83e89e5ccd1ca5dc3f469921c36b814791cf4/content/plugins/cache.md)

**Comment by maver1ck** [comment]
Maybe we can give possibility to set arbitrary CoreDNS config ?

https://github.com/kubernetes/kops/issues/5685
