### ISSUE TITLE
AWS CNI does not support jumbo packets

### ISSUE THREAD

**Issue by oded-dd** [kubernetes/kops#5778]
Working inside a VPC provide us the ability to work with jumbo packets, but the AWS cni does not support it under kops

**Comment by xrl** [comment]
Is what is the flag for the AWS CNI? Do you have a link to the CNI's documentation? Do you know if kops's model for the AWS CNI supports this option?

**Comment by oded-dd** [comment]
I have a link only to the github repo: https://github.com/aws/amazon-vpc-cni-k8s
