### ISSUE TITLE
Coreos instances on AWS not responding

### ISSUE THREAD

**Issue by oded-dd** [kubernetes/kops#5780]
We are using coreos `1800.7.0` on AWS using kops.

We have at least 5 instances every day which stop responding (instance is frozen, not answering to SSH) causing the containers running on the instance to fail with status ContainerCreating until we are stopping the instance.

Our kops version is 1.10.3
And the instances are AWS 5 series (m5, r5, c5)

**Comment by Rauno56** [comment]
Are you positive that those instances are not running out of memory? The symptoms sound the same.

**Comment by tavisma** [comment]
We are also using CoreOS without issue (1800.7.0 and now 1855.4.0)
1.10.7 kube though

**Comment by oded-dd** [comment]
We were experiencing the issue with 1800.7.0 though after upgrading to
1855.4.0 the issue seems to be resolved. We don't have an OOM issue as the
nodes are being monitored and no issue of that kind caused an alert.
