### ISSUE TITLE
etcd-manager roadmap is out of date

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#5782]
https://github.com/kubernetes/kops/blob/master/docs/etcd/roadmap.md

I wonder if we need to break out this roadmap individually right now. I think it may fit better in the root level Roadmap.

**Comment by palash25** [comment]
so this issue is about moving the contents of the etcd-manager roadmap to the root level ROADMAP.md file right @geojaz ?

I would like to be assigned to this if no one else is working on it.
