### ISSUE TITLE
Any luck with manually creating EC2 Spot Fleet ?

### ISSUE THREAD

**Issue by zytek** [kubernetes/kops#5797]
I'd like to ask if anyone had luck with overcoming #1784  and manually creating Spot Fleet using userdata from regular `kops`-created AutoScaling groups. From a quick glance I don't see why this would not work and I am willing to try to do this later this week. It seems that there is nothing instance-specific in userdata apart from NodeLabels. Correct me if I'm wrong. ;-)

Until #1784 is implemented I could live with a script/terraform config that would create Spot Fleets from regular ASGs to ease capacity planning.

**Comment by zytek** [comment]
I will answer myself: I have successfully created Spot Fleet by manually supplying userdata and tags configuration. This method is klunky and less flexible, but with some terraforming should do the job.

The main problem I wish to fix by using this is assuring capacity of our small clusters consisting of only spot instances.

**Comment by zytek** [comment]
@rverma-nikiai here it is - terraform manifest that created spot fleet: https://gist.github.com/zytek/d1e49e97c0ff1dcb965ab712351b035c

**Comment by rverma-nikiai** [comment]
@zytek Thanks for this, wondering if you got this working with cluster-autoscaler. Linking https://github.com/kubernetes/autoscaler/issues/838 may be relevant

**Comment by rverma-nikiai** [comment]
@zytek Thanks for insight.

**Comment by wanghanlin** [comment]
I think this should be resolved now by #6277 
/close
