### ISSUE TITLE
Docker build issues inside kubernetes pod

### ISSUE THREAD

**Issue by renuraj18** [kubernetes/kops#5800]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.9.1 (git-ba77c9ca2)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

While doing docker build inside node , its failing to get the package location due to dns issue

**5. What happened after the commands executed?**

Docker builds failing inside pods (jenkins kubernetes slave)

**6. What did you expect to happen?**

Docker build should pass

**Comment by chrisz100** [comment]
Do you have some log outputs on what is happening and when and where it fails? 
How is the cluster configured?
