### ISSUE TITLE
Incorrect root volume for AWS M5 Instances

### ISSUE THREAD

**Issue by irbull** [kubernetes/kops#5809]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.10.0`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:26Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops update cluster`

**5. What happened after the commands executed?**
This is my first experience with kops, so this could be me. But I followed the basic tutorial and then tried to increase the size of the nodes. I changed the `machineType` to `m5.2xlarge` and even set the 
`rootVolmeSize`

```
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: m5.2xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 200
```
After the cluster started, the `ephemeral-storage` was set to `7730616Ki` (about 8Gb) for each node.
```
Capacity:
 cpu:                8
 ephemeral-storage:  7730616Ki
 hugepages-2Mi:      0
 memory:             32132340Ki
 pods:               110
Allocatable:
 cpu:                8
 ephemeral-storage:  7124535694
 hugepages-2Mi:      0
 memory:             32029940Ki
 pods:               110
```

I was sure this was something I was doing wrong until I realized that if I changed to an `m4` style instance, then the ` ephemeral-storage` was set properly. It also appears that the correct size EBS Volume is being created, maybe just not mounted properly?

**6. What did you expect to happen?**
I expected about 200gb of `ephemeral-storage` (or the default 120gb if I didn't set `rootVolumeSize`)

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
I can do this, but I think I put the important parts above. Let me know if this would help.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
I can do this if you think it will help, but which commands? `edit`, `update`, `create`

**9. Anything else do we need to know?**
Nope! Other than this issue, the out-of-box experience with kops has been great!

**Comment by kimxogus** [comment]
For m5 and c5 instance types, you need to use stretch images `kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11`

**Comment by irbull** [comment]
Thanks. We can close this unless you think docs should be updated somewhere? Or do you think `kops` tooling should print some error/warning for cases like this? Maybe this is common knowledge, but as I said I was just getting started and managed to miss this.

**Comment by kimxogus** [comment]
I couldn't find docs related to this issue when I was having the same issue. I also think there should be some docs about this. Printing error/warning is also a good idea.

**Comment by andytom** [comment]
A check has been added (#5660) but I don't think it has been released yet.

**Comment by aranair** [comment]
is there a similar stretch image for k8s 1.8?
