### ISSUE TITLE
Master Role cannot call deregister backend on AWS NLBs

### ISSUE THREAD

**Issue by xrl** [kubernetes/kops#5816]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.10.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I ran `k -n nginx-ingress delete pod -l app=nginx-ingress` then I noticed my service was down and I looked at `k get events --all-namespaces` and saw:

```
                                       Warning   LoadBalancerUpdateFailed   service-controller                       (combined from similar events): Error updating load balancer with new hosts map[ip-10-43-171-84.ec2.internal:{} ip-10-43-168-151.ec2.internal:{}]: Error trying to deregister targets in target group: "AccessDenied: User: arn:aws:sts::SECRET:assumed-role/masters.kube.ids.com/i-08d7db36ff76fa503 is not authorized to perform: elasticloadbalancing:DeregisterTargets on resource: arn:aws:elasticloadbalancing:us-east-1:981810374974:targetgroup/k8s-tg-96131469a2caf-80-32000/ab5ad76f2a677122\n\tstatus code: 403, request id: 0ebc9d05-be16-11e8-8ed3-5be38192d6c2"
```

**5. What happened after the commands executed?**

I went and updated the role manually to see what would happen. It worked.

**6. What did you expect to happen?**

The master role should be sufficient for all ELB management.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by GMartinez-Sisti** [comment]
To fix this I added:

```yaml
---
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": "elasticloadbalancing:DeregisterTargets",
          "Resource": "*"
        }
      ]
```

**Comment by rajatjindal** [comment]
The fix for this was merged with https://github.com/kubernetes/kops/pull/5752. This can be closed.

cc @justinsb
