### ISSUE TITLE
Using etcd-manager causes apiserver crash loop at startup

### ISSUE THREAD

**Issue by coreypobrien** [kubernetes/kops#5833]
kops version: 1.10.0
k8s version: 1.10.8
cloud: aws

When using etcd-manager, the startup order is broken which causes the apiserver to crash loop while etcd starts. Previously the order was:

1. protokube handled mounting the etcd volumes
2. protokube started kubelet
3. kubelet started etcd and apiserver

With this order, etcd became available almost immediately so the apiserver was able to start correctly.

When using etcd-manager, the order is now
1. protokube starts kubelet
2. kubelet starts etcd-manager and apiserver
3. etcd-manager starts mounting volumes
4. apiserver crashes while waiting for etcd
5. etcd-manager finishes mounting volumes and starts etcd
6. apiserver starts

Because etcd-manager has a 1 minute sleep in the mounting loop and crash loop backoff increases, this leads to a noticeable increase in master startup times. When doing a rolling update, it is regularly long enough to cause kops to bail because server validation fails.

**Comment by coreypobrien** [comment]
I haven't rechecked this recently, but assuming this is still happening, is the solution here to find a way to force apiserver to wait for etcd to start? The simple thing would be an init container that waits for etcd. Thoughts?

**Comment by VihanAgarwal97** [comment]
/reopen
Having a similar issue, apiserver is stuck in a CrashLoop. Initially, the R53 entries weren't updated as mentioned [here](https://github.com/kopeio/etcd-manager/issues/126). I updated these but the apiserver is still crashing.

**Comment by nikiben** [comment]
Having the same issue...
