### ISSUE TITLE
Specify different subnets for internal, external LBs and nodes

### ISSUE THREAD

**Issue by llibicpep** [kubernetes/kops#5835]
Hi,

I have two subnets: internal and external. I want internal subnet to be used for all cluster nodes as well as for internal LBs. I want external subnet to be used for external public LBs. Is there a way to do that?

Currently I can see only one `--subnets` switch in the `kops create cluster`. These subnets getting the following tags:

```
kubernetes.io/cluster/<cluster-name>=shared
kubernetes.io/role/elb=1
kubernetes.io/role/internal-elb=1
```

I assume that these tags are used by k8s to pick up a subnet for internal or external LB based on `service.beta.kubernetes.io/aws-load-balancer-internal` annotation. I assume `kubernetes.io/cluster/<cluster-name>=shared` tag is used to pick up a subnet for the cluster nodes. If my assumptions correct, the question is - how do I tell kops to tag different subnets respectively with all three different tags?

**Comment by llibicpep** [comment]
Took me a while, but I found this https://github.com/kubernetes/kops/issues/5171
So it sounds like to get what I want, I need `--subnets=<my private subnets> --utility-subnets=<my public subnets> --topology=private --api-loadbalancer-type=internal`. I'm going to comment on #5171 that `--utility-subnets` definitely needs better documentation, would save me couple of hours. I think this issue may be closed (after someone review my conclusions are correct...).

**Comment by pulpbill** [comment]
+1 I'm spinning up a new cluster with kops and got:

`I1211 15:35:14.298098   10089 subnets.go:198] Assigned CIDR <nil> to subnet utility-us-east-1a

Spec.Subnets[1].CIDR: Invalid value: "<nil>": Subnet had an invalid CIDR`

With this issue I kind of get a better undestanding of what to do.
