### ISSUE TITLE
Ingress.. Node IAM not authorized to perform: acm:GetCertificate on resource: arn:aws:acm...

### ISSUE THREAD

**Issue by schogini** [kubernetes/kops#5840]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Followed
https://github.com/kubernetes/kops/blob/master/addons/kube-ingress-aws-controller/README.md

**5. What happened after the commands executed?**
kops validate cluster
Validating cluster cluster1......

INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-us-east-1a	Master	m3.medium	1	1	us-east-1a
nodes			Node	t2.medium	2	2	us-east-1a

NODE STATUS
NAME				ROLE	READY
ip-172-20-35-216.ec2.internal	node	True
ip-172-20-41-175.ec2.internal	node	True
ip-172-20-63-10.ec2.internal	master	True

VALIDATION ERRORS
KIND	NAME								MESSAGE
Pod	kube-system/kube-ingress-aws-controller-7d5f974b5f-7qk8b	kube-system pod "kube-ingress-aws-controller-7d5f974b5f-7qk8b" is not healthy
Pod	kube-system/skipper-ingress-ds5ch				kube-system pod "skipper-ingress-ds5ch" is not healthy
Pod	kube-system/skipper-ingress-l48q2				kube-system pod "skipper-ingress-l48q2" is not healthy

Validation Failed
**6. What did you expect to happen?**
Your cluster cluster1..... is ready
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
N/A
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
N/A
**9. Anything else do we need to know?**

kubectl -n kube-system logs kube-ingress-aws-controller-7d5f974b5f-7qk8b

2018/09/27 04:23:13 starting /bin/kube-ingress-aws-controller
2018/09/27 04:23:14 initial load of certificates failed: AccessDeniedException: User: arn:aws:sts::....:assumed-role/nodes.cluster1...../i-0e0bec210c9d9305f is not authorized to perform: acm:GetCertificate on resource: arn:aws:acm:us-east-......:certificate/......
	status code: 400, request id: 0d2398ab-c20d-11e8-9066-33d9da01fe2f

Yes, I checked the IAM nodes.. role to confirm that the Additional Policies are present - Present
I created a test instance and attached the role to confirm the error!
-------------- MY FIX -------------
Then I manually edited the IAM role added acm:*
Kops cluster validation succeeded
Then I kops edit cluster/kops update cluster --yes/kops rolling-update cluster --yes
And all OK...
-----------------------------------

This is for your information and making the needed correction.

Thanks!

**Comment by tavisma** [comment]
This may be a duplicate/similar to:
https://github.com/kubernetes/kops/issues/5532
