### ISSUE TITLE
Terraform Master Nodes API Certificate Should be Updated With ELB Alternate Name Automatically

### ISSUE THREAD

**Issue by teagy-cr** [kubernetes/kops#5848]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.10.3

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`
kops create cluster --cloud=aws --node-count=3 --node-size=t2.medium --zones=us-east-2a --state=s3://your_state_store_here --name=bug.k8s.local --target=terraform --out=./`
`terraform plan`
`terraform apply`

At this point your local kube config does not have the AWS ELB DNS name set as the server for the bug.k8s.local cluster. This is expected. So you can either update the cluster to get the recent ELB DNS name set as the server in your local config.
`kops update cluster bug.k8s.local --yes --state=s3://your_state_here`

Wait for the cluster to get created then run:
`kubectl get nodes`

You get an error complaining that the x509 certificate is invalid because it doesn't contain the ELB DNS name in the list of alternate names in the master API certificate. To fix this issue I had to run,

`kops rolling-update cluster bug.k8s.local --yes --force --cloudonly --instance-group-roles=Master --state=s3://your_state_here`

The update cluster command reissues the API certificate and the rolling update restarts the master nodes with the newly reissued certificate.

**5. What did you expect to happen?**
When running `terraform apply` I expected the master node certificates to automatically include the ELB DNS name as an alternate name.

**6. How can we resolve this?**
These steps of updating the cluster and rolling-update of master nodes is not necessary when it can all be captured in terraform. You can update the terraform userdata for the master nodes to depend on the aws_elb DNS attribute and update the userdata script to auto-update or create the master API certificate on the master nodes with those added alternate names. This will prevent people from having to restart master nodes to alleviate the issue.

**Comment by j00p34** [comment]
same as #2990
