### ISSUE TITLE
Kops does not expose etcd port for Prometheus scraping

### ISSUE THREAD

**Issue by michaelgeorgeattard** [kubernetes/kops#5852]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** 1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.** 1.10.7

**3. What cloud provider are you using?** AWS

I set up cluster on AWS with `--private` flag set to true.

AWS SecurityGroup created by Kops does not expose master port 4001 to nodes. This prevents Prometheus from scraping etcd status.

Is this intended behaviour? Is there a flag I can use to expost the port?

https://github.com/coreos/prometheus-operator/issues/1766

**Comment by gordonm** [comment]
Presumably this is a security measure, opening the port allows any pod in the cluster to make (potentially unauthenticated) etcd client connections [and get root access on your cluster](https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#securing-etcd-clusters).
