### ISSUE TITLE
Need a documentation to migrate a cluster between two AWS zone

### ISSUE THREAD

**Issue by Patafix** [kubernetes/kops#5866]
What is the procedure to migrate cluster on AWS to another zone, with zero down time?

**Comment by chrisz100** [comment]
Are we talking about Availability Zones or Regions? 
To another Availability Zone: Just create a second instancegroup, drain the old nodes and once all workloads are shifted delete your old instancegroup. 

Moving masters is more of a challence as they host etcd though. Here is some documentation on how to resize or move the etcd cluster: 
https://github.com/kubernetes/kops/blob/master/docs/single-to-multi-master.md
