### ISSUE TITLE
More cloud providers by leveraging existing Terraform providers?

### ISSUE THREAD

**Issue by kkimdev** [kubernetes/kops#5874]
This is more like a question, Terraform already supports tons of providers via plugins:

- https://www.terraform.io/docs/providers/type/major-index.html
- https://www.terraform.io/docs/providers/type/cloud-index.html
- https://github.com/terraform-providers

For example, Scaleway provider implements the API that manages all the resources:
- https://github.com/terraform-providers/terraform-provider-scaleway/blob/ddd65b73053546e8b22d6db06ebd71473e70dcb9/scaleway/provider.go
- https://github.com/terraform-providers/terraform-provider-scaleway/blob/ddd65b73053546e8b22d6db06ebd71473e70dcb9/scaleway/resource_server.go#L160

I'm not familiar with kops' codebase, but I wonder if we can leverage the Terraform cloud provider plugins by implementing plugin host glue, to streamline more provider support.

Personally I'd love to have a solid Kubernete solution on Scaleway and Hetzner.

**Comment by tuannvm** [comment]
@kkimdev you could take a look on this [simple kops provider](https://github.com/honestbee/devops-tools/pull/27) Right now it's only support cluster creation / deletion. Suggests are welcome!
