### ISSUE TITLE
Kops doesn't provide way to check if cluster creation completed

### ISSUE THREAD

**Issue by shrinandj** [kubernetes/kops#588]
Kops creates Kubernetes clusters asynchronously. So, when the _kops create cluster_ command completes, the cluster creation is fired but not completed. However, there is no other mechanism to check whether the async task for cluster creation has completed. This makes it difficult to use kops in automated deployments.

It will be good if kops provides an option to check if cluster creation (or any other async task) completed.

**Comment by jkemp101** [comment]
I agree this would be useful.  I'm in the middle of scripting automated deploys using kops.  If you need something now I am using the following Python code with `pykube` to confirm when all nodes have checked in.  You will have to tweak it for your particular situation:

```
    def wait_for_cluster(self):
        """Wait until we can confirm all nodes have registered with cluster."""

        api = pykube.HTTPClient(pykube.KubeConfig.from_file('~/.kube/config'))

        total_nodes = """Replace with the number of master + nodes"""
        logging.info('Waiting for %d nodes', total_nodes)
        logging.info('This can take several minutes to complete')
        while True:
            try:
                nodes = pykube.Node.objects(api)
                if len(nodes.all()) == 0:
                    logging.info('No nodes available yet')
                    time.sleep(10)
                elif len(nodes.all()) > 0 and len(nodes.all()) < total_nodes:
                    logging.info('Some nodes available: %d', len(nodes.all()))
                    time.sleep(2)
                elif len(nodes.all()) == total_nodes:
                    logging.info('All nodes available: %d', len(nodes.all()))
                    return
            except Exception, err:  #pylint: disable=W0703
                logging.info('Failed getting nodes')
                logging.info(err)
                time.sleep(10)

            time.sleep(2)
```

**Comment by chrislovecnm** [comment]
We are considering adding a validate function.  The create should exit and then the user could call validate.  cc: @kris-nova

**Comment by chrislovecnm** [comment]
This is work in progress.  The first PR is to help with upgrades, and then we will expose the features to the cli

**Comment by chrislovecnm** [comment]
Kops validate now does.
