### ISSUE TITLE
kops has silent requirement of ~/.ssh/id_rsa

### ISSUE THREAD

**Issue by Cloven** [kubernetes/kops#590]
kops complains and dies if the current user's ~/.ssh/id_rsa does not exist (presumably one created by ssh-keygen).  If the user has different names for her key(s) and/or uses DSA encryption instead, this will be perplexing.

Suggest that (a) whatever kops is using id_rsa for is documented, and (b) that the filename be a configurable option in a command line flag.

**Comment by mrichmon** [comment]
The command-line option `--ssh-public-key` for `kops create cluster` should address suggestion "b".

**Comment by Cloven** [comment]
aha!  Yep, thanks, missed that, appreciate it.

**Comment by chrislovecnm** [comment]
@Cloven can we close this?

**Comment by Cloven** [comment]
yes; would still like to understand (a), but that's just a documentation issue.
