### ISSUE TITLE
Why  KOPs for vsphere needs S3 bucket

### ISSUE THREAD

**Issue by indreshmishra** [kubernetes/kops#5912]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0 (git-8b52ea6d1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
I have enabled vsphere feature switch
**3. What cloud provider are you using?**
Vsphere
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster kubernetes.skydns.local  --cloud=vsphere --zones=vmware-zone --dns-zone=skydns.local --networking=flannel --vsphere-server=10.160.235.5 --vsphere-datacenter=VSAN-DC --vsphere-resource-pool=VSAN-Cluster --vsphere-datastore=vsanDatastore --dns private --vsphere-coredns-server=http://10.109.228.93:2379 --image="kops_ubuntu_16_04.ova"
**5. What happened after the commands executed?**
It is giving error as follows
State Store: Required value: Please set the --state flag or export KOPS_STATE_STORE.
A valid value follows the format s3://<bucket>.
A s3 bucket is required to store cluster state information.
**6. What did you expect to happen?**
I expect that if I am using vsphere as cloud provider, why it is needing me data stores of S3. , why it can not have option of either data store on vSphere or a local data store.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by chrisz100** [comment]
kops stores cluster information in manifests on a to be defined location. 
You have various options where to put it though:
https://github.com/kubernetes/kops/blob/master/util/pkg/vfs/context.go

**Comment by sdfaz** [comment]
if you are trying to keep everything local, deploy minio on the kubernetes cluster, and proxy all s3:// traffic to it.
https://github.com/helm/charts/tree/master/stable/minio
