### ISSUE TITLE
Stale systemd "Kubernetes transient mount" entries not cleaned up, leading to resource leaks, in particular increased  kubelet CPU and RSS resource usage from /sys/fs/cgroup scanning

### ISSUE THREAD

**Issue by jjo** [kubernetes/kops#5916]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.10.0 (git-8b52ea6d1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: v1.11.3
Server Version: v1.10.7

**3. What cloud provider are you using?**

AWS on Ubuntu Xenial nodes (fyi to have latest patches for sec vulnerabilities),
```
$ uname -a
Linux ip-x-x-x-x 4.4.0-1069-aws #79-Ubuntu SMP Mon Sep 24 15:01:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ dpkg-query -W systemd docker-ce |column -t
docker-ce  17.03.2~ce-0~ubuntu-xenial
systemd    229-4ubuntu21.4

```

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Running Kubernetes workloads with high Pod churn rate (CI in this particular
case) leads to orphaned `systemd` "Kubernetes transient mount" entries,
impacting `kubelet`'s CPU and RSS (on a node with ~100K-ish such stale
entries the kubelet was using ~5G RSS). FYI strace'ing the kubelet shows
a high rate of `/sys/fs/cgroup/*` scanning [1], I guess also for `/metrics` purpose
(as these high number of entries also get exposed there).

You can spot this by running [2] for these mounts, while not present in the
filesystem[3], similar issue re: corresponding cgroup entries [4] without
any tasks inside[5].

See [6] below for a workaround I'm using to avoid the need for node
reboots.

**5. What happened after the commands executed?**

Very high number of stale "Kubernetes transient mount" entries.

**6. What did you expect to happen?**

Although I don't know the internals of kubelet->systemd coupling,
I'd expect these number of entries to be in the same order of magnitude
as locally _current_ running containers (15~20 as shown by `docker ps`).

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Relevant excerpt:
```
  # See ongoing saga at https://github.com/kubernetes/kops/issues/3576,
  # in particular with the "storage" key
  kubelet:
    kubeReserved:
        cpu: "100m"
        memory: "192Mi"
    kubeReservedCgroup: "/kube-reserved"
    systemReserved:
        cpu: "100m"
        memory: "256Mi"
    systemReservedCgroup: "/system-reserved"
    enforceNodeAllocatable: "pods"
    runtimeCgroups: "/systemd/system.slice"
    kubeletCgroups: "/systemd/system.slice"
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

References from above:
* [1] kubelet strace excerpt
```
31189 18:04:51.291796 lstat("/sys/fs/cgroup/cpu,cpuacct/system.slice/run-r9c5ccbf3e3624216ac42ea4e02c012a2.scope/cpuacct.usage_percpu", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
31189 18:04:51.291848 lstat("/sys/fs/cgroup/cpu,cpuacct/system.slice/run-r9c5ccbf3e3624216ac42ea4e02c012a2.scope/tasks", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
31189 18:04:51.291898 lstat("/sys/fs/cgroup/cpu,cpuacct/system.slice/run-r9c5ccbf3e3624216ac42ea4e02c012a2.scope/cgroup.procs", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
```

* [2] showing the craze number of systemd mount entries for kubelet, a couple samples
```
# systemctl list-units --state=running|egrep -c Kubernetes.transient.mount
5277
# systemctl list-units --state=running|egrep Kubernetes.transient.mount|head -2
run-r0002080a075f42fca18f3dbbd6240291.scope    loaded active running Kubernetes transient mount for /var/lib/kubelet/pods/564a9f4e-cb8d-11e8-9fcb-0210299701b6/volumes/kubernetes.io~empty-dir/rpc
run-r00196cd2f1794358917115faac49cd69.scope    loaded active running Kubernetes transient mount for /var/lib/kubelet/pods/6c0bc704-c740-11e8-9fcb-0210299701b6/volumes/kubernetes.io~secret/default-token-0cp8w
```
* [3] ... but above entries not actually in the filesystem
```
# systemctl list-units --state=running|egrep Kubernetes.transient.mount|egrep -o /var/lib/kubelet/pods/.+ | xargs -I@ sh -c 'test -d @ || echo @'|wc -l
5277
```

* [4] same order of magnitude number of cgroups:
```
# find /sys/fs/cgroup/*/system.slice -name tasks | wc -l
6610
```
* [5] ... but only a subset of above cgroups holding running tasks (grep . to match for tasks file content ie pids):
```
# find /sys/fs/cgroup/*/system.slice -name tasks -print0|xargs -0 grep .|wc -l
464
```

* [6] **Workaround**: stop those systemd mounts not present in the filesystem
(the 1st and 3rd cmd below are the same just to show the affected numbers):
```
find /sys/fs/cgroup/*/system.slice -name tasks | wc -l
systemctl list-units --state=running| \
   sed -rn '/Kubernetes.transient.mount/s,(run-\S+).+(/var/lib/kubelet/pods/.+),\1 \2,p' | \
   xargs -r -l1 sh -c 'test -d $2 || echo $1' -- | \
   xargs -r -tl1 systemctl stop |& wc -l
find /sys/fs/cgroup/*/system.slice -name tasks | wc -l
```
* Note:
  * `sed` extracts systemd output to just be the `unit` ($1) and the `mountpoint` ($2)
  * 1st `xargs` filters it by `test -d $2 || echo $1`
  * 2nd `xargs` removes the entries ($1) one by one

* Example output numbers from above workaround (nodes w/~50days uptime):
  * Node w/high pod churn rate (fyi dedicated to CI): `20311 2331 1663`
  * Node w/"normal" workloads: `4986 428 1562`

**Comment by jjo** [comment]
FYI potentially matching bugs, although not 100% certain on either:

* https://github.com/kubernetes/kubernetes/issues/57345
  _Number of "loaded inactive dead" systemd transient mount units continues to grow_
  * note that in our case these are `loaded active running Kubernetes transient mount ...` rather
  * although bug is already closed as resolved, there's comments activity from a few days ago, someone
    suggesting: `You need to upgrade your systemd version to v237+ or patch current systemd
    with change from systemd PR 7811.` 
* https://github.com/kubernetes/kops/issues/4049
  _Kubelet 'failed to get cgroup stats for "/system.slice/kubelet.service"' error messages'_
  * it's related to our Kubelet cgroup settings, although not seeing that exact error in logs

**Comment by jjo** [comment]
This seems to actually be: kubernetes/kubernetes#64137, fwiw https://github.com/kubernetes/kubernetes/issues/64137#issuecomment-410860823 uses
the same hack we found to workaround it /cc @arapulido

**Comment by jraby** [comment]
We're seeing something similar here on nodes which run lots of relatively short living pods:

```
$ find /sys/fs/cgroup/*/system.slice -name tasks | wc -l
103910
```

This is on 1.10.6 and we're not running cronjobs, only regular pods that live for a few minutes.

In our case, they are all 'Active: active (running)'
```
● run-r318064e3bed94ccaae415af165b9ca22.scope - Kubernetes transient mount for /var/lib/kubelet/pods/78390927-c815-11e8-9a25-000c29720845/volumes/kubernetes.io~secret/default-token-99h2h
   Loaded: loaded
Transient: yes
  Drop-In: /run/systemd/system/run-r318064e3bed94ccaae415af165b9ca22.scope.d
           └─50-Description.conf
   Active: active (running) since Thu 2018-10-04 20:38:37 UTC; 1 weeks 5 days ago
    Tasks: 0
   Memory: 0B
      CPU: 4ms
```

And of course, the vast majority of them are for pods that do not exist anymore.

**Comment by jjo** [comment]
FYI after changing base image from ubuntu xenial[0] to debian stretch[1]
this issue was no more, our monitoring for these stale entries + cleanup
(which was always hovering above zero depending on Pods churn) went
down to flat zero.
[0] 099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180814
[1] 379101102735/debian-stretch-hvm-x86_64-gp2-2018-11-10-63975
