### ISSUE TITLE
calico-kube-controller pod does not mount /etc/hosts as intended

### ISSUE THREAD

**Issue by shrinandj** [kubernetes/kops#5934]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.10.7

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
- `kops create cluster`
- `kops update cluster --yes`

**5. What happened after the commands executed?**
* The cluster was running just fine. At a later point, it was found that pods were not able to communicate with each other using pod IPs.
* It turned out that one of the master nodes had been terminated and a new one was brought up by the ASG.
* The `calico-kube-controller` pod since then started throwing error about being unable to reach an etcd host.
* Looking at the `calico-kube-controller` pods' `/etc/hosts` file, it was found that the file had an entry for the old kubernetes master node (which was also running etcd).
* If you look at the `calico-kube-controller` pod spec, it turns out that it has a volume entry for `/etc/hosts` as a hostPath. However, this volume is not part of the volumeMounts.

**6. What did you expect to happen?**
`calico-kube-controller` should not throw errors if/when a master node terminates and a new one comes up. This might just work fine if the `/etc/hosts` file on the host is correctly mounted inside the pod.

**Comment by edlee2121** [comment]
Volume mount seems to be missing at:
https://github.com/kubernetes/kops/blob/6f1874a93a75efd8df694e2156818b55e5bf7e71/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template#L363

Even though the volume is defined at:
https://github.com/kubernetes/kops/blob/6f1874a93a75efd8df694e2156818b55e5bf7e71/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template#L369

**Comment by shrinandj** [comment]
I added the volume_mount at the appropriate place above. It works fine for new cluster creations. However, it does not upgrade the calico-kube-controllers deployment in existing clusters to volume_mount the /etc/hosts file :( ...
