### ISSUE TITLE
How to change the pod ip ranges?

### ISSUE THREAD

**Issue by owenhaynes** [kubernetes/kops#595]
I see that each node gets assigned a range of 100.96.0.0/24 100.96.1.0/24 etc. 
How do i change the ranges that get assigned to each node? can not see anything in the docs

**Comment by jkemp101test** [comment]
Here are the options I have used:

* Easiest is to use `kops edit cluster` after the `kops create cluster` to change the cidrs before you run `kops update cluster`
* If you are trying to automate the change I used a cheesy hack with sed by doing something like `export KUBE_EDITOR="sed -e 's#100\.64\.0\.0/10#$NON_MASQ_SUBNET#g; s#10\.0\.32\.0/19#$SUBNET1#g; s#10\.0\.64\.0/19#$SUBNET2#g; s#10\.0\.96\.0/19#$SUBNET3#g' -i ''"` and then running `kube edit cluster`
* Or you can manually manipulate the state files in S3 before running `kops update cluster`.  This is what I am doing now.

**Comment by justinsb** [comment]
@owenhaynes why are you trying to change the node ranges?  I'm not sure if you're asking about changing the /24, or the 100.96 etc...

**Comment by owenhaynes** [comment]
trying the change the 100.96, as is this not a public ip range?, and its clashing when joining two kube networks with vpn

**Comment by owenhaynes** [comment]
@jkemp101test that worked kube to delete the kubernetes svc and the kube-dns service to get things functioning again

**Comment by wangycc** [comment]
Did you find the way? I also want to change the private ip range

**Comment by chaosaffe** [comment]
Just as a note in case anyone else comes across this, 100.64.0.0/10 is assigned as [Shared Address Space](https://tools.ietf.org/html/rfc6598) and is _not_ a public block.

**Comment by alex-percayso** [comment]
I have two clusters and I am trying to change the pod IP ranges also, has anyone figured out how?

**Comment by bjethwan** [comment]
Does changing the cidr makes kops select something other 100.96 for the pod network?
