### ISSUE TITLE
kops behind corporate proxy

### ISSUE THREAD

**Issue by seanoreilly1973** [kubernetes/kops#5986]
Hi

Does kops have an option to skip tls verification? I am behind a corporate proxy that re-encrypts with a different cert. 

I am trying to install Istio in to my cluster following the pre-requisites at 
[https://github.com/kubernetes/kops/issues/new](https://github.com/kubernetes/kops/issues/new)

When I run kops update cluster I get the following error:

error reading channel "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable": error fetching "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable": Get https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable: x509: certificate signed by unknown authority

Has anyone found a way around this?

**Comment by drewib** [comment]
This is likely a different reason. If your corporate proxy is MITM every connection, you wouldn't be able to visit any HTTPS websites. Are you able to curl that URL from the CLI? If not, specify the proxy before calling kops `HTTP_PROXY=corporate kops ...`

**Comment by ArcticSnowman** [comment]
Why does KOPS need to download from github?   Can it do this offline?
