### ISSUE TITLE
rolling-update very slow

### ISSUE THREAD

**Issue by rbtcollins** [kubernetes/kops#5989]
As I understand it the current behaviour for rolling-update is:
```
for node in stale_nodes:
  drain(node)
  validate_stable()
  delete(node)
```
With the ASG taking care of spawning the new nodes.

This is very slow, particularly when pod disruption budgets are not being violated. (e.g. imagine we are configured so that the smallest scale-down of any workload has capacity for 2 disruptions without issues, but scales up with load, then kops could safely introduce 1 disruption at any time, but also potentially many more when the disruption budget hasn't been exceeded.

Now, you might say 'slow doesn't matter', but ops folk have to pay attention during this process, and when it exceeds attention windows - say an hour - that becomes a human factor problem.

I'm not sure what the right behaviour should be, but something like the following would be pretty much ideal for many of our use cases:
```
    asg.count = 2*len(stale_nodes)
    wait for *a* node to be up
    map(stale_nodes, cordon)
    while True:
        if drain_nonblocking(stale_nodes):
              break
    map(stale_nodes, delete)
```
where `drain_nonblocking` is something like this:
```
done = True
for node in stale_nodes:
  for pod in pods:
    if ((standalone(pod) or
        statefulset_highest_unmoved(pod) or
        daemonset/job(pod) or
        deployment_above_disruption_budget(pod)) and
        pod_can_be_rescheduled(pod)):
        delete(pod)
    else:
        done=False
return done
```

The idea being to induce as much disruption as the cluster is defined as tolerating, as rapidly as possible.

An obvious extension to this approach is a canary incrementally more aggressive rollout - first one node, then two, then four, 8, 16 etc until the entire cluster is being done.

kops 1.9.0 :).

Let me know if this would be considered for merging, we might see about putting something together.

**Comment by rbtcollins** [comment]
Sounds like we're saying much the same thing; the key question for me is how much room for experimentation kops will permit - no point putting experimental code forward if its not broadly interesting to the maintainers :)

**Comment by xulsitatirev** [comment]
@rbtcollins I totally sign in the point the rolling-update is super-slow.

I am not sure, you have the same thing in mind, but one of other possibilities is to temporary double-size the amount of nodes at auto-scaling-group and then... put it back to normal.
Auto-scaling-group removes the oldest nodes by default, as far as I know.

**Comment by BrianChristie** [comment]
See also these:
[Parallelize and improve rolling updates even more](https://github.com/kubernetes/kops/issues/1718) 

[Kops Rollout Strategies - WIP](https://github.com/kubernetes/kops/pull/4038)

[Post from Reactive Ops](https://medium.com/@reactiveops/the-reactiveops-bestest-kubernetes-cluster-upgrade-f7a7589b21fb) (nice GIF explanation)
