### ISSUE TITLE
operate a kops control loop

### ISSUE THREAD

**Issue by rbtcollins** [kubernetes/kops#6000]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

This is a fairly big suggestion. Rather than being a command line tool that we're having to build locking, verification etc around, it would be great if kops really were an API - with a control loop and controllers.

Specifically:
 - this would remove the current failure modes with half-rolled out updates when an admin machine goes to sleep, or a jenkins slave fails and is killed; instead the next reconciliation of the controller would detect the difference and resume rolling it out
 - scale-down would have a place in the design that isn't just 'update the ASG and hope' - see #5999 
 - out of band changes such as deletion of an ASG would be able to self heal

**2. Feel free to provide a design supporting your feature request.**

I can imagine a number of ways to do this. The simplest is probably to spawn a single node ASG with a micro instance on it in the same region as the cluster at the time its created, and have that run the control loop.

Another possible home for the control loop is the cluster autoscaler - or at least for *one* of the control loops (the ASG maintaining one) - it already has all the code for draining, dealing with different corner cases, scaling down safely etc. Even if we only moved that *one* function into a control loop (in the autoscaler), I think we'd have much less redundancy, and less change of violating PDB's due the autoscaler and kops fighting with each other

**Comment by BrianChristie** [comment]
You may want to take a look at the _Cluster-API:_
https://github.com/kubernetes-sigs/cluster-api

> The Cluster API is a Kubernetes project to bring declarative, Kubernetes-style APIs to cluster creation, configuration, and management. It provides optional, additive functionality on top of core Kubernetes.

As well as _kubeadm:_
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/

I think there's a few projects building tools around kubeadm and the cluster-api, but none that are widely used yet.
