### ISSUE TITLE
disable nopassword sudo access for admin user

### ISSUE THREAD

**Issue by kloia-hz-daas** [kubernetes/kops#6005]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.10.9

**3. What cloud provider are you using?**

AWS

**6. What did you expect to happen?**

kops default image shouldn't allow sudo commands for admin user. If an attacker somehow access the machine then attacker can do anything inside machine.

the image i am using:

`kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17`

**Comment by xulsitatirev** [comment]
I doubt this idea the idea to make it **default** configuration.

First of all, this is the only user you got. Hence it is definitely not recommended to use `root` user directly, this is the only, more-less reasonable, way to escalate your privileges into `root`.

You have many ways to handle your expectations.
* Build your own AMI.
* Reconfigure `ssh` with configuration management tool, like `ansible` or `saltstack`.
* Totally disable `ssh` and achieve immutability.

**Comment by cnuber** [comment]
You can also modify your node configuration by adding some additionalUserData in your instancegroup configuration like

  additionalUserData:
  - content: |
      #!/bin/sh
       sed 's/someconfig/someotherconfig/g' -i /etc/ssh/sshd_config
    name: ssh_script.sh
    type: text/x-shellscript

We do this on the fly upon node spin-up and it seems work pretty well without any additional config management software.
