### ISSUE TITLE
Is it possible to append a json dict to the iam roles that kops generates?

### ISSUE THREAD

**Issue by jrvanalstine** [kubernetes/kops#6007]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
I would like to simply append a dict to the node iam role statement. Is this already possible?
**2. Feel free to provide a design supporting your feature request.**

**Comment by rifelpet** [comment]
@jrvanalstine You can add [additional policies](https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#adding-additional-policies) to the IAM roles that Kops manages. Is that sufficient?
