### ISSUE TITLE
Support Service-Linked Roles on AWS

### ISSUE THREAD

**Issue by stanvit** [kubernetes/kops#6008]
AWS introduced [Service-LInked Roles](https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html) to Autoscaling Groups.

As per [this forum post](https://forums.aws.amazon.com/thread.jspa?threadID=277523), the introduction will affect people using KMS encrypted AMIs/Root volumes. According to the post, new Service-Linked Role must be created, KMS CMK's policies should be adjusted and Auto Scaling Groups configured to use the Role.

I see the feature as a new [`InstanceGroupSpec`](https://godoc.org/k8s.io/kops/pkg/apis/kops#InstanceGroupSpec) filed that translates into: 
- [`service_linked_role_arn`](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#service_linked_role_arn) Autoscaling Group attribute in Terraform
- [`ServiceLinkedRoleARN`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-autoscaling-autoscalinggroup-servicelinkedrolearn) property on `AWS::AutoScaling::AutoScalingGroup`s in CloudFormation
- Calling `SetServiceLinkedRoleARN()` in the [appropriate](https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#CreateAutoScalingGroupInput.SetServiceLinkedRoleARN) [places](https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#Group.SetServiceLinkedRoleARN)

**Comment by joel-custlabs** [comment]
Pinging this issue; this issue is blocking our deployments using encrypted AMI/root volumes. If this isn't supported in KOPS anymore, what are workarounds we can patch clusters deployed via kops with?

**Comment by stanvit** [comment]
@joel-custlabs we found two solutions for this problem:

1. As we're using Terraform for our Kops cluster provisioning, we placed a file called`kubernetes_override.tf` (anything ending with `_override.tf` would work) into the kops terraform output directory and added `aws_autoscaling_group` resource extension for every kops Instance Group we have:

```
resource "aws_autoscaling_group" "kops-terraform-asg-resource-name" {
  service_linked_role_arn = "arn:aws:iam::123123123123:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling_custom-role-suffix"
}
...
```

2. We didn't find this too scalable as we have to remember to edit this file and add new override for every new Instance Group we're going to have, so we ended up just giving CMK usage permissions to the standard Autoscaling Service Roles. This is the part from our Key Policy:

```json
{
            "Sid": "ASG may use the key",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::123123123123:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling",
                    "arn:aws:iam::123123123123:role/aws-service-role/spot.amazonaws.com/AWSServiceRoleForEC2Spot"
                ]
            },
            "Action": [
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:Encrypt",
                "kms:DescribeKey",
                "kms:Decrypt"
            ],
            "Resource": "*"
        },
        {
            "Sid": "ASG may attach resources",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::123123123123:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling",
                    "arn:aws:iam::123123123123:role/aws-service-role/spot.amazonaws.com/AWSServiceRoleForEC2Spot"
                ]
            },
            "Action": "kms:CreateGrant",
            "Resource": "*",
            "Condition": {
                "Bool": {
                    "kms:GrantIsForAWSResource": "true"
                }
            }
        }
```

That worked for us just fine, as the only Autoscaling Groups we have in that account are managed by the same Kops cluster anyway.
