### ISSUE TITLE
ELB OutOfService by NginX-Ingress-Controller

### ISSUE THREAD

**Issue by KazuyoshiUeno** [kubernetes/kops#6011]
I created my cluster which has One-Master and Two-Nodes in the same availability zone.
Basically, working good.

And the ELB which NginX-Ingress-Controller made is connecting these two nodes,
However one of these nodes is **OutOfService** , the another is good health

Of course, these two nodes are created by kops automatically.

So, I would like fix the node good health from ELB.
How should I do this ?

**Comment by satchinjoshi** [comment]
Yeap facing a similar issue, only one node is shown healthy.
