### ISSUE TITLE
Default Cooldown for ASG

### ISSUE THREAD

**Issue by mzupan** [kubernetes/kops#6029]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I see the following

https://github.com/kubernetes/kops/blob/af4df08b694e2a1f8814a7b3649060477be67c86/cloudmock/aws/mockautoscaling/group.go#L58

When I try to set that using `kops edit ig nodes` It seems to go away. I'm using the following version

`Version 1.10.0`

**2. Feel free to provide a design supporting your feature request.**

The default AWS cooldown is 5 minutes and we run a high traffic message queue trying to scale multiple nodes quickly and if there is a 5 minute cooldown that is too slow.

**Comment by emilingerslev** [comment]
I'm also looking for a way to set the Default Cooldown for the AWS Autoscaling Groups to something else than the 500s cooldown.

I think the actual place that should be changed is here: 

https://github.com/kubernetes/kops/blob/b1c446f8f34c13e27c4823b113fc87c7edb4f99c/upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go#L209-L213

and somewhere around here: 
https://github.com/kubernetes/kops/blob/b1c446f8f34c13e27c4823b113fc87c7edb4f99c/upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go#L253-L255

It also requires that the AutoscalingGroup below gets extended with a DefaultCooldown: https://github.com/kubernetes/kops/blob/b1c446f8f34c13e27c4823b113fc87c7edb4f99c/upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go#L38-L53

I'll consider looking into a PR for this.
