### ISSUE TITLE
offline cluster creation

### ISSUE THREAD

**Issue by sdfaz** [kubernetes/kops#6038]
It would be really handy to do have a '--offline' flag to the create, update, and rolling-update commands, with the goal being the ability to deploy kubernetes via kops on offline cloud-providers like, isolated openstack, isolated vsphere, aws-govcloud...

Maybe this could be accomplished by kops expecting the required binaries to be in the current working directory and throwing an error if something is missing, like a package dependency check.  
My current work-around is to identify all the binaries and docker images required to build via terraform and kops, host them in a local nexus repository.

So far I have identified the following as necessary to build the master and worker nodes via kops --target terraform.
https://kubeupv2.s3.amazonaws.com/kops/1.10.0/linux/amd64/nodeup
https://storage.googleapis.com/kubernetes-release/release/v1.10.6/bin/linux/amd64/kubelet
https://storage.googleapis.com/kubernetes-release/release/v1.10.6/bin/linux/amd64/kubectl
https://storage.googleapis.com/kubernetes-release/network-plugins/cni-plugins-amd64-v0.6.0.tgz
https://kubeupv2.s3.amazonaws.com/kops/1.10.0/linux/amd64/utils.tar.gz
https://kubeupv2.s3.amazonaws.com/kops/1.10.0/images/protokube.tar.gz

and I have identified these docker images as part of the full kops config
k8s.gcr.io/etcd:2.2.1
k8s.gcr.io/kube-apiserver:v1.10.6
k8s.gcr.io/kube-controller-manager:v1.10.6
k8s.gcr.io/kube-proxy:v1.10.6
k8s.gcr.io/kube-scheduler:v1.10.6
k8s.gcr.io/pause-amd64:3.0

**Comment by abdennour** [comment]
Any news?

**Comment by rwd5213** [comment]
Any update I am looking to do a complete offline install as well. For example all executables in S3 and those docker containers in a private registry. I know there is the mirror docker setting but does that apply to these images in the userdata as well?

**Comment by mward29** [comment]
bump
