### ISSUE TITLE
Error when passing in list of master-zones

### ISSUE THREAD

**Issue by snoby** [kubernetes/kops#604]
Running this command :
`kops --v=3 create cluster west.k.tropo.com --cloud=aws --zones=us-west-1a --kubernetes-version=1.4.0 --node-count=3 --master-zones=us-west-1a us-west-1b us-west-1c --node-size=t2.small --dns-zone=Z1N71K8UHPS27L --master-size=t2.large --ssh-public-key=~/.ssh/lab_no_password.pub`

Results in this error:
`expected a single <clustername> to be passed as an argument`
If I remove the argument : `--master-zones=us-west-1a us-west-1b us-west-1c`
The cluster builds and deploys fine.  Of course I don't have an HA master at this point.  I'm not sure if I'm using the tools wrong, but my reading of  the option  "master-zones" I think this is ok.  Maybe it's suppose to be delimited some how instead of spaces?

**Comment by brbbs** [comment]
Try using commas to delimit the master zones.

**Comment by snoby** [comment]
Yes, I tried that as well with the same result.

**Comment by brbbs** [comment]
What version of kops are you running? Using your command, I get the output:
```
$ kops --v=3 create cluster west.k.tropo.com --cloud=aws --zones=us-west-1a --kubernetes-version=1.4.0 --node-count=3 --master-zones=us-west-1a,us-west-1b,us-west-1c --node-size=t2.small --dns-zone=Z1N71K8UHPS27L --master-size=t2.large --ssh-public-key=REDACTED
I1006 15:27:59.435159   26128 context.go:140] Found bucket "brb-test-bucket" in region "us-east-1"
I1006 15:27:59.656031   26128 channel.go:53] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I1006 15:27:59.705833   26128 cluster.go:438] Computed CIDR for subnet in zone "us-west-1a" as "172.20.32.0/19"
I1006 15:27:59.705873   26128 cluster.go:381] Assigned CIDR 172.20.32.0/19 to zone us-west-1a

InstanceGroup "master-us-west-1b" is configured in "us-west-1b", but this is not configured as a Zone in the cluster
$ kops version
Version git-a09f3a9
```
Which is a different error that I assume can be fixed by modifying your value of `--zones`.

**Comment by snoby** [comment]
Version git-a09f3a9
But I think you uncovered the issue.  There can be NO SPACES even if you delimit with a comma.
Although the error message the was shown:
> InstanceGroup "master-us-west-1b" is configured in "us-west-1b", but this is not configured as a Zone in the cluster
I would think is still an issue.  Isn’t it the point for HA to have the masters in different availability zones?  Or is HA considered achieved when you have more than one master?


Matt Snoby
matt.snoby@icloud.com
678.462.0322

**Comment by brbbs** [comment]
I think it's that kops expects `--master-zones` to be a subset of `--zones`.

So you could run `kops --v=3 create cluster west.k.tropo.com --cloud=aws --zones=us-west-1a,us-west-1b,us-west-1c --kubernetes-version=1.4.0 --node-count=3 --master-zones=us-west-1a,us-west-1b,us-west-1c --node-size=t2.small --dns-zone=Z1N71K8UHPS27L --master-size=t2.large --ssh-public-key=~/.ssh/lab_no_password.pub` and get a HA config with 3 masters in us-west-1a,us-west-1b,us-west-1c and 3 worker nodes also in those zones.

**Comment by snoby** [comment]
@brbbs AHHHHHH,
Ok thanks!
:open_mouth:
