### ISSUE TITLE
Move from Kube DNS to Core DNS

### ISSUE THREAD

**Issue by Sanjanare** [kubernetes/kops#6044]
I wanted to move from kube-dns to core-dns how can i add to the cluster to update with core-dns? ( iam new to k8s please some one help me on this )
Thanks in advance

when i do kops edit cluster i see
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
-----------------
where should i add 
spec:
kubeDNS:
provider: CoreDNS

i use kops 1.10 version (new to k8s)

_Originally posted by @Sanjanare in https://github.com/kubernetes/kops/issues/5224#issuecomment-435975084_

**Comment by gkope** [comment]
Just follow this block on the doc and add it on your cluster yaml:
https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#kubedns
```yaml
spec:
  kubeDNS:
    provider: CoreDNS
```

**Comment by Sanjanare** [comment]
@gkope thank you so much, i have added to the yaml file and will do rolling update , do i need to delete anything on kube-dns? or it will be automatically replaced with core-dns? (i know this core-dns with the same name as kube-dns)

**Comment by Sanjanare** [comment]
worked please close the issue

**Comment by lucasreed** [comment]
> worked please close the issue
@Sanjanare 
Did you force a `rolling-update` or just a `update --yes` on your cluster.
