### ISSUE TITLE
EC2 AMD instance class support

### ISSUE THREAD

**Issue by saidmasoud** [kubernetes/kops#6052]
Please add support (if possible) for the new AMD instance types announced here: 

https://aws.amazon.com/blogs/aws/new-lower-cost-amd-powered-ec2-instances/

**Comment by rekcah78** [comment]
PR : https://github.com/kubernetes/kops/pull/6049

**Comment by richstokes** [comment]
Which releases of kops (will) support AMD instance types?

**Comment by saidmasoud** [comment]
@rekcah78 kops 1.11 was released, should this issue be closed?

**Comment by rekcah78** [comment]
Yes
