### ISSUE TITLE
Should validate for duplicated zone at API level

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#606]
If you're going through the API, you can do this: us-east-1c,us-east-1c

**Comment by justinsb** [comment]
Though it is caught on update: `Zones contained a duplicate value: us-east-1c`

**Comment by chrislovecnm** [comment]
What unit testing are we doing to validate that we have clean data sent through the api?

**Comment by chrislovecnm** [comment]
I am looking through issues to test against #1183

**Comment by chrislovecnm** [comment]
See https://github.com/kubernetes/kops/issues/1206 ~ The PR is in.  Who can test?

**Comment by justinsb** [comment]
This is now caught:

```
spec: Invalid value: [{"name":"us-east-1a","zone":"us-east-1a","cidr":"172.20.32.0/19","type":"Public"},{"name":"us-east-1a","zone":"us-east-1a","cidr":"172.20.64.0/19","type":"Public"},{"name":"us-east-1a","zone":"us-east-1a","cidr":"172.20.96.0/19","type":"Public"}]: subnets with duplicate name "us-east-1a" found
```
