### ISSUE TITLE
Reduce IAMFullAccess, not feasible in Enterprises

### ISSUE THREAD

**Issue by saryx123** [kubernetes/kops#6060]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
KOPS is very unlikely to require full IAM access, rather, a subset of privileges is used and should be assigned. This should also be reflected in the formal [https://github.com/kubernetes/kops/blob/master/docs/aws.md
](docu).

The existing state violates core security (least privilege) principle and introduces an attack surface an AWS account that is just unacceptable in security concerned organizations. A programmatic use of full IAM privileges = root/domain admin. Which is far more impactful in cloud environments. This can result in full operation wipeout with very few applicable controls.

This needs to be tackled if KOPS is to be a viable, enterprise grade solution.

**2. Feel free to provide a design supporting your feature request.**
KOPS is likely only using the following IAM and sts
sts:AssumeRole
iam:GetRole
iam:PassRole
iam:create-role

This list is for sure lacking and only knowledgeable individuals testing a restricted set of IAM privileges in effect can determine the absolute minimum.

**Comment by zytek** [comment]
Related: #1873
