### ISSUE TITLE
Add custom tolerations to kube-dns and kube-dns-autoscaler

### ISSUE THREAD

**Issue by pajel** [kubernetes/kops#6063]
kops version: 1.10.0
k8s version: 1.10.6
I want all my instance goups to have taints to prevent apps from different teams running on shared nodes. I can easily do that with kops and end up with instance groups and taints like this:

ig: devops taint: allowOnly=devops:NoSchedule
ig: team1 taint: allowOnly=team1:NoSchedule
ig: team2 taint: allowOnly=team2:NoSchedule

But the default kube-dns addon doesn't allow me to easily add tolerations to kube-dns and kube-dns-autoscaler pods, which makes the pods unschedulable in my cluster.
I could manually update the kube-dns yaml definition in S3, but I would have to do that after every cluster update/upgrade.

What is the best/easiest way to add tolerations to the default dns addon?
I can image a flag while running kops to work well. Or updating the cluster definition with "kops edit"?

**Comment by ahsan-storm** [comment]
@pajel did you get any solution for applying tolerations to kube-dns & kube-dns autoscaler

**Comment by pajel** [comment]
@ahsan-storm not really, I had to leave one instancegroup without any taint so kube-dns & kube-dns autoscaler were able to get scheduled.

**Comment by minkimipt** [comment]
I'd like to have it too, not only for kube-dns, but for all addons
