### ISSUE TITLE
Can the same master nodes be used to manage 2 or more clusters?

### ISSUE THREAD

**Issue by nrdufour** [kubernetes/kops#6070]
Hello,

Just wondering if the same master nodes can be used to manage 2 or more clusters.
Thanks,

Nicolas

**Comment by labria** [comment]
No, each cluster needs its own master nodes.
Is there a specific scenario you're thinking about? Usually having separate InstanceGroups and/or namespaces is good enough in terms of workload isolation. Otherwise, you would probably need to create and manage completely separate clusters

**Comment by nrdufour** [comment]
Yes that makes sense. Mostly about saving the costs of those master node boxes.
But since it's rather small and a silly question, no point doing that :)
Thanks for the response.
