### ISSUE TITLE
enable to receive jmx-metrics pn prometheus even after using scrape

### ISSUE THREAD

**Issue by Sanjanare** [kubernetes/kops#6071]
we have a java spring boot application running on kubernetes and wanted to get the heap metrics onto the prometheus we used annotation scrape but could not find a target on prometheus.
New to k8s please help !

**Comment by HagaiBarel** [comment]
This is really the wrong place to ask this, I recommend filing an issue at the Prometheus repos.

Depending on how you've set up your exporter, the relevant repos are:
* jmx-exporter - https://github.com/prometheus/jmx_exporter
* jave client - https://github.com/prometheus/client_java
