### ISSUE TITLE
Create NLB per InstanceGroup

### ISSUE THREAD

**Issue by oded-dd** [kubernetes/kops#6073]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
AWS has a limitation of Targets per Availability Zone per load balancer of 500.
As the master add all the nodes to the NLB it means that we are limited for 500 nodes per AZ by AWS design. The way to solve it is to add the nodes of specific ASG (specific instance group) to the NLB.

Today the only way to do it is to create the NLB manually and connect it to specific ASG.

It will be great if it is possible to add annotation which will limit the NLB to specific ASG

**Comment by edify42** [comment]
I think you should open a support ticket with AWS to increase the number of targets you want to attach to your ELB rather than doing a config work around. 

https://console.aws.amazon.com/support/v1#/case/create?issueType=service-limit-increase&limitType=service-code-elastic-load-balancers

**Comment by oded-dd** [comment]
@edify42 I tried it first. It seems that they have an hard limitation for that. Which basically means that if you have a cluster greater then 500 instances you will have the same issue.
