### ISSUE TITLE
Not able to launch dashboard

### ISSUE THREAD

**Issue by venkatasykam** [kubernetes/kops#6079]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** - Version 1.10.0 (git-8b52ea6d1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.** - GitVersion:"v1.12.2"

**3. What cloud provider are you using?** - AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?** - After I logged in with Admin & pwd, getting EOF, unreachable. (I have launched the DNS url from  kubectl cluster-info)

**5. What happened after the commands executed?** - After I logged in with Admin & pwd, getting EOF, unreachable.

**6. What did you expect to happen?** - successful login with Admin

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by venkatasykam** [comment]
instead of accessing localhost:8001, I am planning to access the dashboard thru master/node ip.

Is there any document step by step process(all the steps in single document) to access the dash board?

Document to access dashboard if the cluster setup using minikube/kubeadm/kops? 

I have gone thru many documents, but still cant able to access dashboard.

Could you please suggest me the steps to access dashboard?

**Comment by Zeka13** [comment]
same for me
