### ISSUE TITLE
Multiple master nodes are created by Kops on AWS

### ISSUE THREAD

**Issue by shrinandj** [kubernetes/kops#608]
The autoscaling group created by Kops for the Kubernetes master has a minimum and desired value of 3. As a result, there are 3 master nodes that get created. There are no knobs for controlling this.

It would be better to either have an option to configure the minimum and desired # of masters or maybe use 1 as the default and let users upgrade after the cluster is deployed.

**Comment by yissachar** [comment]
The ASG should not have a min/max/desired of 3. I've just started a cluster with kops and can confirm that it is 1 by default.

Can you share the command you ran?

**Comment by shrinandj** [comment]
Please see the command below. I was hoping to have 1 master and 3 minion nodes. Instead, I got 3 masters and 3 minion nodes. I suspect the 3 master nodes were brought up because the masters autoscaling group had a min and desired count of 3. Their tags show “k8s.io/role/master” is 1.

`kops create cluster --cloud=aws --zones=us-west-2a --dns-zone=my.local --node-count=3 --master-size=m3.large --node-size=m3.large --vpc=vpc-123123 --network-cidr=172.20.0.0/16 --ssh-public-key=/tmp/blah.pub my-new-cluster --yes
`

**Comment by shrinandj** [comment]
Not using the absolutely latest code, but not too old either. The last commit in my code is 6388a77fd454b154ea8faf4ee807e6dd4dd176c9 (Sep 28th). I can try the latest one too.

kops also has the "get instancegroups" option that shows the auto-scaling group name and min and max values. That did show 1 as the min and max values. But the AWS console showed me 3 instances in the master autoscaling group.

**Comment by yissachar** [comment]
Just to confirm, the result of `kops get ig` shows a min/max value of 1, while the ASG in AWS console shows a min/max of 3?

Can you also run `kops update` without the `--yes` to see if kops picks up this difference and wants to correct it?

**Comment by shrinandj** [comment]
I changed the min/max to 2 and ran kops update --yes and it did change it to 2.

**Comment by shrinandj** [comment]
My bad...

My installer changes the autoscaling group config and it landed up operating on on the wrote autoscaling group. Instead of changing the minion's autoscaling group, it was modifying the master :(
