### ISSUE TITLE
cluster stats are exposed on port 4194 without any authentication

### ISSUE THREAD

**Issue by kloia-hz-daas** [kubernetes/kops#6102]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops 1.10

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.10.0

**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kubectl exec -it $containername bash`

`curl http://PRIVATE_IP:4194/api/v2.0/spec?recursive=true`

**5. What happened after the commands executed?**

i see all cluster stats without any credentials

**6. What did you expect to happen?**

it should give authorization error.

**Comment by justinsb** [comment]
So this is the kubernetes configuration up until 1.11, where it was removed in   https://github.com/kubernetes/kubernetes/pull/63881 . As such this should be removed with the upgrade to 1.11.

As this would technically be a breaking change to remove it from 1.10, I think we should just fix this for >= 1.11 - it lets us focus on some of the active changes we should make for security.
