### ISSUE TITLE
kernel:unregister_netdevice on debian 4.4.148-k8s

### ISSUE THREAD

**Issue by tpolekhin** [kubernetes/kops#6103]
**1. What `kops` version are you running?**
```
kops version
Version 1.10.0
```

**2. What Kubernetes version are you running?**
```
kubectl version
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
```
Cloud: AWS
AMI ID: k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17 (ami-094be7cc0306aa98e)
uname: 4.4.148-k8s
```

Reference issue from kops: https://github.com/kubernetes/kops/issues/2901
Reference issue from kubernetes: https://github.com/kubernetes/kubernetes/issues/64743

A week after cluster provisioning we faced this issue:
```
kernel:unregister_netdevice: waiting for eth0 to become free. Usage count = 1
```
This https://github.com/kopeio/kubernetes-kernel/pull/8 should've fix that, but seems like it didn't :(

We have a bare metal cluster that was installed with kismatic and we also faced this issue there,
that was fixed by upgrading kernel version to `4.17.13-1.el7.elrepo.x86_64`

This also states that issue was resolved after upgrading kernel to `4.16.13`
https://github.com/kubernetes/kubernetes/issues/64743#issuecomment-436839647

**Comment by Freyert** [comment]
Our team also fixed this by:

1. Deploying a [Debian Stretch AMI](https://wiki.debian.org/Cloud/AmazonEC2Image/Stretch) into EC2.
2. Adding the `stretch-backports` repository to the VM.
3. Installed `linux-image-cloud-amd64` restarted.
4. Made an image off of the VM
5. Configured KOPS to use it.

Seems like a pretty common and serious issue with the 4.4 kernel though. Breaking lots of people.
