### ISSUE TITLE
kops fails with 'No Auth Provider found for name "oidc"'

### ISSUE THREAD

**Issue by msiuts** [kubernetes/kops#6107]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.10.0 (git-8b52ea6d1)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.9", GitCommit:"e6ab4ee54f71e7a403cc733534bab86fd959ecb7", GitTreeState:"clean", BuildDate:"2018-10-16T12:14:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.9", GitCommit:"e6ab4ee54f71e7a403cc733534bab86fd959ecb7", GitTreeState:"clean", BuildDate:"2018-10-16T12:01:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops validate cluster`

**5. What happened after the commands executed?**

```
Using cluster from kubectl context: XXX

Validating cluster XXX


Cannot build kubernetes api client for "XXX": No Auth Provider found for name "oidc"
```

**6. What did you expect to happen?**

No error and seeing the normal output.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

n/a

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

n/a/

**9. Anything else do we need to know?**

This is working with KOPS 1.9 and 1.11, since this seems to be fixed here:
https://github.com/kubernetes/kops/commit/217136039d61cc64c02c10f754a9239577e783b4

Would be great to have a 1.10 bugfix release and also it took some time to find the cause of the issue, so I thought it would be helpful to have an issue here.

**Comment by Typositoire** [comment]
I'm having the exact same issue and I'm sure this used to work.

**Comment by msiuts** [comment]
Closing this, since kops 1.11 is already released which also fixes this issue as described above.
