### ISSUE TITLE
Where to find compatible image names (AWS)?

### ISSUE THREAD

**Issue by richstokes** [kubernetes/kops#6131]
How does one know which image name is compatible with which AWS instance type? I'm probably being blind, but can't find this in the docs. Running into the NVME issue with later AWS instance types. kops upgrades don't seem to update this field, so presumably, we should manually research and update this if we wish to use a newer AWS instance type?

**Comment by richstokes** [comment]
I found this - https://github.com/kubernetes/kops/blob/master/channels/stable

Does this mean I need to be on kubernetesVersion: ">=1.11.0" before switching to the image that supports NVME (stretch)?

**Comment by syscll** [comment]
Ideally, yes, you'll need to be on Kubernetes >=1.11.0

You could manually set the image to use `stretch` in each of your instance groups, but I'm not 100% sure if this is recommended.

I am successfully running Kubernetes 1.10.9 across 6 cluster using the following image: `kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17`.

**Comment by richstokes** [comment]
Thanks. Do you know if kops will auto switch to using the `stretch` images after upgrading to 1.11?

**Comment by syscll** [comment]
No probs. I _think_ it should automatically upgrade to use the stretch image if you follow [this](https://github.com/kubernetes/kops/blob/master/docs/upgrade.md) process.

You can check by viewing the config of an instance group and looking at the image after performing `kops upgrade`.
