### ISSUE TITLE
error doing DNS lookup for NS records 

### ISSUE THREAD

**Issue by alexfrieden** [kubernetes/kops#6135]
kops create cluster --name=subdomain.example.com --cloud=aws --zones=us-east-1a --state=s3://my-cool-bucket
I1129 17:12:12.314630   32509 subnets.go:184] Assigned CIDR 172.20.32.0/19 to subnet us-east-1a
I1129 17:12:13.263118   32509 create_cluster.go:1351] Using SSH public key: /Users/afrieden/.ssh/id_rsa.pub
Previewing changes that will be made:

error doing DNS lookup for NS records for "example.com": lookup example.com on 10.40.1.6:53: no such host

I followed instructions from https://github.com/kubernetes/kops/blob/master/docs/aws.md and created my own domain that I used in place of example.com

Any idea how to fix?  Everything should be public

**Comment by Sanjanare** [comment]
@alexfrieden hey did u find the solution ?

**Comment by alexfrieden** [comment]
It just ended up being slow but eventually worked.  I think the recommendation of using the local gossip cluster should be highlighted as the simplest one.

**Comment by smaillns** [comment]
Typically the same issue, any other suggestions please

**Comment by AiswaryaM13** [comment]
how did you solve it?

**Comment by 1996Shubh** [comment]
sloution??

**Comment by alexfrieden** [comment]
Have you tried creating a gossip cluster? https://dzone.com/articles/creating-a-gossip-based-kubernetes-cluster-on-aws
