### ISSUE TITLE
Kops 1.11 beta1 is not using calico 3 (still using calico 2)

### ISSUE THREAD

**Issue by vietwow** [kubernetes/kops#6137]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops 1.11 beta1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.4

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kubectl -n kube-system describe po calico-node-7487k
and see the docker image version of calico is still old : Image: quay.io/calico/node:v2.6.9

**5. What happened after the commands executed?**

N/A

**6. What did you expect to happen?**

Docker image version of calico should be 3.x due to kops have already merged the pull request upgrade to calico 3 (https://github.com/kubernetes/kops/pull/5102 and https://github.com/kubernetes/kops/pull/6077).

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: xxxx
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    project: xxxx
    team: devops
  cloudProvider: aws
  configBase: s3://xxxx
  dnsZone: walletsl1.net
  etcdClusters:
  - etcdMembers:
    -
      encryptedVolume: True
      instanceGroup: master-ap-northeast-1a
      name: a
    -
      encryptedVolume: True
      instanceGroup: master-ap-northeast-1c
      name: c
    -
      encryptedVolume: True
      instanceGroup: master-ap-northeast-1d
      name: d
    name: main
  - etcdMembers:
    -
      encryptedVolume: True
      instanceGroup: master-ap-northeast-1a
      name: a
    -
      encryptedVolume: True
      instanceGroup: master-ap-northeast-1c
      name: c
    -
      encryptedVolume: True
      instanceGroup: master-ap-northeast-1d
      name: d
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:DescribeTags",
            "autoscaling:TerminateInstanceInAutoScalingGroup",
            "ecr:BatchCheckLayerAvailability",
            "ecr:BatchGetImage",
            "ecr:DescribeRepositories",
            "ecr:GetAuthorizationToken",
            "ecr:GetDownloadUrlForLayer",
            "ecr:GetRepositoryPolicy",
            "ecr:ListImages",
            "ecr:PutImage",
            "ecr:InitiateLayerUpload",
            "ecr:UploadLayerPart",
            "ecr:CompleteLayerUpload"
          ],
          "Resource": ["*"]
        }
      ]
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - ResourceQuota
    - LimitPodHardAntiAffinityTopology
    - PodNodeSelector
    - Priority
    - Initializers
    - NodeRestriction
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    oidcClientID: xxxx
    oidcIssuerURL: https://accounts.google.com
    oidcUsernameClaim: email
    featureGates:
      PodPriority: "true"
  kubeScheduler:
    featureGates:
      PodPriority: "true"
  kubelet:
    featureGates:
      PodPriority: "true"
      ExpandPersistentVolumes: "true"
      TaintNodesByCondition: "true"
    systemReserved:
      cpu: 100m
      ephemeral-storage: 1Gi
      memory: 500Mi
    systemReservedCgroup: /system-reserved
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.4
  masterInternalName: api.k8s-v2.walletsl1.net
  networkCIDR: 10.1.0.0/16
  networkID: vpc-xxxx
  networking:
    calico:
      crossSubnet: true
      prometheusMetricsEnabled: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by sergeohl** [comment]
Did you change your cluster configuration ?

You have to say than you want calico v3
`  networking:
    calico:
      majorVersion: v3`
