### ISSUE TITLE
Support of AWS a1.* instances (Arm-based)

### ISSUE THREAD

**Issue by styk-tv** [kubernetes/kops#6140]
With the a1.* instances being significantly cheaper, would it make sense at support of a1.* aws instances?

Type Spec:
https://aws.amazon.com/ec2/instance-types/a1/

**Comment by brandon-dacrib** [comment]
It looks like it is in master so we need to wait for a release or do a build yourself. https://github.com/kubernetes/kops/blob/b3a450119faf8678afa09d1fd76fdc2a9dec37d2/upup/pkg/fi/cloudup/awsup/machine_types.go

**Comment by dobesv** [comment]
Just because it was added to the list of instance types that exist doesn't mean anything will work on it.  Probably you need an OS image specifically built for ARM and all your docker containers will have to have ARM images.

**Comment by apjneeraj** [comment]
It does not work! cloud-init script fails due to exec error. I tried using arm based ubuntu ami.

> Aug  1 03:50:04 ip-172-2-96-123 cloud-init[2095]: == Downloaded https://kubeupv2.s3.amazonaws.com/kops/1.12.2/linux/amd64/nodeup (SHA1 = e7e49d1fff61badc2fff402e80858d081aa88a26) ==
Aug  1 03:50:04 ip-172-2-96-123 cloud-init[2095]: Running nodeup
Aug  1 03:50:04 ip-172-2-96-123 cloud-init[2095]: /var/lib/cloud/instance/scripts/part-001: line 133: ./nodeup: cannot execute binary file: Exec format error

**Comment by brandon-dacrib** [comment]
That binary is for x86-64. You need to acquire or build one for arm64 and then modify things to pull that. I would start by sorting out what process in the project is building that binary and then submitting a PR modifying that to build for both x86-64 + aarch64.

**Comment by hakman** [comment]
M6g, C6g, and R6g have been [announced](https://aws.amazon.com/about-aws/whats-new/2019/12/announcing-new-amazon-ec2-m6g-c6g-and-r6g-instances-powered-by-next-generation-arm-based-aws-graviton2-processors/) and looks like the performance is great:
https://www.anandtech.com/show/15578/cloud-clash-amazon-graviton2-arm-against-intel-and-amd/10

I will start experimenting with ARM support for Kops. Worker nodes should be pretty easy to configure.

/reopen

**Comment by jsleeio** [comment]
@hakman expect pain if you try to use the `imagebuilder`/`bootstrap-vz` tooling to build Debian Stretch ARM AMIs :-(

I tried this just after the `a1` instances were announced, and got as far as patching `bootstrap-vz` ... but got completely stuck on the bootloader config. If you're interested my abandoned changes are here:

https://github.com/jsleeio/bootstrap-vz/tree/arm64-support

(I use Packer now and recommend other people do the same!)
