### ISSUE TITLE
We have lost the KOPS_STATE_STORE message

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#615]
Failure to set a state store gives

`State store "" is not cloud-reachable - please use an S3 bucket`

**Comment by iherbmatt** [comment]
Did you find any resolution to this issue? I'm seeing it as well.

**Comment by johnyzhu** [comment]
me too T_T  Is there any solution?

**Comment by chrislovecnm** [comment]
Set your STATE_STORE :)  Either use the command line option or the env var.

**Comment by kris-nova** [comment]
This is big - I think kops needs

1. Better STATE_STORE output 
2. To be smarter on detecting STATE_STORE from other input

CC https://github.com/kubernetes/kops/issues/702

**Comment by justinsb** [comment]
@iherbmatt @johnyzhu wondering if you didn't find the instructions, or if they weren't sufficiently clear?

I think we probably need a very explicit step-by-step guide.

I'll also fix the error message though....

**Comment by kris-nova** [comment]
Closing - #808

**Comment by justinsb** [comment]
I'll open an issue for the need for a step-by-step tutorial...
