### ISSUE TITLE
"upgrade cluster" overriding stretch image selection

### ISSUE THREAD

**Issue by richstokes** [kubernetes/kops#6153]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
kops version
Version 1.10.0 (git-8b52ea6d1)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops upgrade cluster
ITEM                    PROPERTY        OLD                                                             NEW
InstanceGroup/nodes     Image           kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17        kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
```

I manually switched to the stretch image, since this supports NVME volumes used by the newer AWS instance types.

If I ran this command, kops would switch the cluster back to using jessie, which would break the cluster if running on new AWS instances with NVME volumes.

It feels like kops needs the logic to know that stretch is newer and has better compatibility with the running instance types than jessie.

**Comment by phynias** [comment]
need a work around for this as well, so we can upgrade off the vulnerable k8s version.

**Comment by richstokes** [comment]
The workaround seems to be to upgrade your kubernetes version via `kops edit cluster` then `kops update cluster` . This will bump the k8s version but keep everything else the same.
