### ISSUE TITLE
Feature: Kops should implement pre-deployment validation

### ISSUE THREAD

**Issue by RobertDiebels** [kubernetes/kops#6155]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Kops should:

- Check quotas and limits of cloud providers before it deploys any instances.
- Check if quotas and limits are reached during validation.

**Use-case**
I deployed several clusters to GCE using kops. All the clusters successfully deployed according to `kops create -f file1.yaml -f ... -f fileN.yaml`. However when I started deploying k8s-objects to the k8s-clusters one of my clusters showed an error message. This message was related to a Deployment failing to deploy due to scheduling/affinity issues.

Running `kops validate cluster` revealed that `Machine X machine X has not yet joined cluster`. So I thought something must have failed with the deployment and I re-deployed it. It failed again. Seeing as I had had no prior issues with kops up until this point I inspected GCE's quotas and saw that my `in-use IP-addresses` quota had been reached.

Pre-deployment validation would have caught this issue.

**Why should should Kops implement pre-deployment validation?**
Kops should be able to check this specific limit and others before deploying any instances. Since kops knows the sizes of instance-groups before deployment and the amount of IP-addresses required to deploy the cluster. The same could be said about other limits relating to instances. Such as static IP-addresses, possibly amount of cores (if instances type specs are known).

Kops should especially verify quotas and limits during regular validation. Seeing as the failure of a node to join the cluster due to non-existence (after reaching a cloud provider limit) should be a major validation factor.

**Applies to**
Only those limits which are affected by instances, instance-groups _deployed by kops_ during cluster creation. Any limits reached due to interaction with k8s should not be accounted for. For example the creation of a load-balancer that adds a new IP-address to the cloud-provider causing a related limit to be reached, should _not_ be accounted for

**Benefits**
This feature could potentially save people time and money since clusters would simply not be deployed if quotas would be reached after deployment. And allow them to request a limit-increase with their respective cloud-provider.

**Comment by RobertDiebels** [comment]
/remove-lifecycle stale 
If someone could take a look at this that would be great. @fejta

**Comment by ms4720** [comment]
this would make people very happy

**Comment by RobertDiebels** [comment]
Assuming no-one is looking at this.

/close
