### ISSUE TITLE
kube-router fails to come up because kubeconfig is a directory rather than a file

### ISSUE THREAD

**Issue by zostay** [kubernetes/kops#6169]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```kops update cluster --yes
kops rolling-update cluster --yes
```

**5. What happened after the commands executed?**

Each node that is taken down and restarted will restart normally except `kube-router` will fail to restart every time. 

The log for the kube-router pod will show something like this every time:

```% kubectl logs --namespace kube-system kube-router-wz2n2
I1205 17:39:18.598304       1 server.go:210] Running /usr/local/bin/kube-router version v0.1.0, built on 2018-03-19, go1.8.7
Failed to parse kube-router config: Failed to build configuration from CLI: Error loading config file "/var/lib/kube-router/kubeconfig": read /var/lib/kube-router/kubeconfig: is a directory
```

The solution is to login to each node and run:

```% sudo rmdir /var/lib/kube-router/kubeconfig && sudo touch /var/lib/kube-router/kubeconfig```

After that `kube-router` will eventually restart on it's own or I can delete the pods to force an immediate restart.

**6. What did you expect to happen?**

Restart without `kube-router` problems.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-07-14T17:04:41Z
  name: **redacted**
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect":"Allow",
          "Principal": "*",
          "Action":["s3:GetObject"],
          "Resource":["arn:aws:s3:::**redacted**/*"]
        }
      ]
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-state.**redacted**/**redacted**
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    name: events
  iam:
    legacy: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.11
  masterInternalName: api.internal.**redacted**
  masterPublicName: api.**redacted**
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-2a
    type: Public
    zone: us-east-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-07-14T17:04:41Z
  labels:
    kops.k8s.io/cluster: **redacted**
  name: master-us-east-2a
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: m4.large
  maxPrice: "0.100"
  maxSize: 2
  minSize: 1
  role: Master
  rootVolumeSize: 16
  subnets:
  - us-east-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-07-14T17:04:41Z
  labels:
    kops.k8s.io/cluster: **redacted**
  name: nodes
spec:
  additionalSecurityGroups:
  - sg-4499282f
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: m4.large
  maxPrice: "0.100"
  maxSize: 3
  minSize: 1
  role: Node
  rootVolumeSize: 16
  subnets:
  - us-east-2a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I assume I have a configuration problem since this doesn't seem to be a common problem, but I have no idea what it is.

**Comment by dhemeier** [comment]
Hey @zostay,

maybe some errors inside the Kubernetes-router Specs. I would Prüfer to try to diff the Kube-router deployment with the current official Kube-router repository. 

Some users with the same errors:
https://github.com/cloudnativelabs/kube-router/issues/329
https://github.com/cloudnativelabs/kube-router/issues/491
