### ISSUE TITLE
ELB SSL handshake broken in us-east-2

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#6181]
At least in us-east-2, with `--topology=private`, ELB reports master instances as being out of service when the health check is configured for SSL.  Manually changing to TCP fixes things immediately.

apiserver is logging `http: TLS handshake error from 172.20.1.222:38426: EOF` during the failed health checks.  It logs it with the TCP health-checks as well though!

Reported here: https://github.com/kubernetes/kops/issues/6172#issuecomment-445013291

I was able to reproduce in us-east-2

**Comment by justinsb** [comment]
Likely related to https://github.com/kubernetes/kops/commit/2accc73a724e287d0dd540856acae4382ed0263b

cc @johanneswuerbach 

Although honestly we should do a better health check anyway....

**Comment by justinsb** [comment]
(by better health check I mean one that actually checks the health of apiserver & etcd, not just whether or not apiserver is listening - this predates 2accc73)

**Comment by johanneswuerbach** [comment]
Strange, we run all our clusters in us-east-1 and eu-west-1 with Ping Target | SSL:443 and never experienced any issues.

**Comment by johanneswuerbach** [comment]
Maybe its caused by `--topology=private` and SSL checks actually doing more back-and-forth then plain TCP checks?

We had similar issues in the past with misconfigured security groups or route tables on one-side of the connection, which allowed to open a connection, but they stalled as responses never arrived.

**Comment by markine** [comment]
The us-east-1 vs us-east-2 contrast can be seen by using:

```
kops create cluster NAME --cloud aws --networking kopeio-vxlan --master-zones ZONES --zones ZONES --ssh-public-key KEY --master-size SIZE --master-volume-size SIZE --node-size SIZE --node-volume-size SIZE --node-count COUNT --output yaml --topology private --bastion --image AMI
```

and changing just the zones and the AMI (have to pick the AMI for the right zone). us-east-1 works, us-east-2 does not.

kops 1.10.0 (and kubernetes 1.10.11)

**Comment by alexander-semenets** [comment]
The same issue for our infrastructure. We have clusters provisioned with the same codebase in us-east-1 and us-east-2 and us-east-1 has ssl checks failed while the east-2 works well. Trying to investigate with AWS Support now.

**Comment by alexander-semenets** [comment]
I've just got a confirmation from AWS Support team that there was an issue with CLB update at us-east-2 region. The problem was fixed and CLB works great again at my env.
