### ISSUE TITLE
1 route_controller.go:117] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster

### ISSUE THREAD

**Issue by hbceylan** [kubernetes/kops#6184]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.9", GitCommit:"e6ab4ee54f71e7a403cc733534bab86fd959ecb7", GitTreeState:"clean", BuildDate:"2018-10-16T12:01:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

I have a single VPC in AWS and I have installed a K8s cluster via KOPS. It's okay **when the only one K8s** cluster. But I want to setup a few cluster in the **same VPC**. 

route table has below tags;
<img width="831" alt="screen shot 2018-12-08 at 13 19 34" src="https://user-images.githubusercontent.com/23728382/49684937-f802ed00-faeb-11e8-8723-41dc2e4fecf6.png">

**KubernetesCluster** tag is very important for **kube-controller**. When this tag is defined on aws **vpc,subnets** and **route table** the **kube-controller** modifiying the route tables with successfully as below;

<img width="1227" alt="screen shot 2018-12-08 at 13 07 51" src="https://user-images.githubusercontent.com/23728382/49684826-54650d00-faea-11e8-8143-eee2b3c33466.png">

BUT, when I install another K8s cluster with the **multiple KubernetesCluster tag value** as below;

<img width="1086" alt="screen shot 2018-12-08 at 13 43 51" src="https://user-images.githubusercontent.com/23728382/49685150-58475e00-faef-11e8-8caa-02ab1e078eb9.png">

I gives an error kube-controller gives below error;

`E1208 10:34:09.814832       1 route_controller.go:117] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster:k8s-.......cloud`

AND the route table cannot modifying via kube-scheduler..

SO how can I **create multiple cluster** with KOPS in AWS?

Thanks,

**Comment by kvishweshwar** [comment]
> **1. What `kops` version are you running? The command `kops version`, will display this information.**
> Version 1.10.0
> 
> **2. What Kubernetes version are you running? `kubectl version` will print the version if a cluster is running or provide the Kubernetes version specified as a `kops` flag.**
> 
> Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
> 
> Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.9", GitCommit:"e6ab4ee54f71e7a403cc733534bab86fd959ecb7", GitTreeState:"clean", BuildDate:"2018-10-16T12:01:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
> 
> **3. What cloud provider are you using?**
> AWS
> 
> I have a single VPC in AWS and I have installed a K8s cluster via KOPS. It's okay **when the only one K8s** cluster. But I want to setup a few cluster in the **same VPC**.
> 
> route table has below tags;
> <img alt="screen shot 2018-12-08 at 13 19 34" width="831" src="https://user-images.githubusercontent.com/23728382/49684937-f802ed00-faeb-11e8-8723-41dc2e4fecf6.png">
> 
> **KubernetesCluster** tag is very important for **kube-controller**. When this tag is defined on aws **vpc,subnets** and **route table** the **kube-controller** modifiying the route tables with successfully as below;
> 
> <img alt="screen shot 2018-12-08 at 13 07 51" width="1227" src="https://user-images.githubusercontent.com/23728382/49684826-54650d00-faea-11e8-8143-eee2b3c33466.png">
> 
> BUT, when I install another K8s cluster with the **multiple KubernetesCluster tag value** as below;
> 
> <img alt="screen shot 2018-12-08 at 13 43 51" width="1086" src="https://user-images.githubusercontent.com/23728382/49685150-58475e00-faef-11e8-8caa-02ab1e078eb9.png">
> 
> I gives an error kube-controller gives below error;
> 
> `E1208 10:34:09.814832 1 route_controller.go:117] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster:k8s-.......cloud`
> 
> AND the route table cannot modifying via kube-scheduler..
> 
> SO how can I **create multiple cluster** with KOPS in AWS?
> 
> Thanks,

Hello hbceylan,

is this resolved for you ?
If yes, can you please share any workaround ?

Thanks in advance !!

**Comment by hbceylan** [comment]
@kvishweshwar sorry but it was a long time ago and I don't remember the solution.
