### ISSUE TITLE
Couldn't create cluster using kops V1.11  on AWS

### ISSUE THREAD

**Issue by brianyiktaktsui** [kubernetes/kops#6187]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.11. 
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-04T07:48:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster $NAME \
  --zones=us-west-2a\
  --authorization RBAC \
  --master-size t2.large \
  --master-volume-size 100 \
  --node-size r5.large \
  --node-volume-size 100 \
  --node-count 1 \
  --yes
**5. What happened after the commands executed?**
I noticed that kops fail in v1.11.0 when excute the creation command but not in v1.10.0
**6. What did you expect to happen?**
v1.11.0 kops should works.

Thanks !!!.

**Comment by farrukh90** [comment]
hi @brianyiktaktsui  would you be able to send the snapshot? It works on my side.

**Comment by brianyiktaktsui** [comment]
Hey, sorry for my delayed reply. At the end I got my cluster running on the AWS with T2-xlarge. 

Have you considered reporting the user errors to kops directly?  My feeling is that most kops users (like me) usually ask questions in the GitHub when they need some really urgently fixed, and once I somehow can get the production server up and running I just don't want to touch it anymore. 

Thank you so much for all the hard work.
