### ISSUE TITLE
Please allow latest, coolest visualizations via Dashboard

### ISSUE THREAD

**Issue by aliakhtar** [kubernetes/kops#619]
Please do it so the visualizations described here: 

http://blog.kubernetes.io/2016/10/Production-Kubernetes-Dashboard-UI-1.4-improvements_3.html

can be shown on Kops clusters.

Also, if I try to run addons/dashboard 1.4, the dashboard goes down after being up for 10-15 mins, the deployment just gets deleted for some reason (no longer shows up in `kubectl get deployments --ns=kube-system` )

**Comment by ajohnstone** [comment]
These already work..  try the following...
```
make channels-gocode;
channels apply channel  kubernetes-dashboard --yes;
channels apply channel   monitoring-standalone --yes;
```

**Comment by aliakhtar** [comment]
@ajohnstone 

If I run the 1.1 version of the dashboard, that works fine. Only the 1.4 version gets deleted. I don't know why.

Also, I've run the above 2 commands before (heapster + dashboard) and I only saw the old style visualizations, didn't see the new style ones

**Comment by buildmaster** [comment]
I can attest that I get the same thing
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.4.0.yaml` starts the dashboard but after maybe 20 minutes the service disappears and nothing is listed in kubernetes.

sounds something along the lines of this: https://github.com/kubernetes/dashboard/issues/665 (but I don't know enough to attest that it's the same thing)

**Comment by aliakhtar** [comment]
@buildmaster  When it does work, do you see the visualizations at http://blog.kubernetes.io/2016/10/Production-Kubernetes-Dashboard-UI-1.4-improvements_3.html ? Because I still saw the old visualizations only

**Comment by buildmaster** [comment]
no graphs
![screenshot 2016-10-10 20 12 36](https://cloud.githubusercontent.com/assets/19946/19228912/fdee146c-8f25-11e6-87d0-8e96e2c6b29b.png)

**Comment by aliakhtar** [comment]
@buildmaster You have to add the add-on `monitoring-standalone/v1.2.0.yaml` to see the graphs.

**Comment by buildmaster** [comment]
well I was going to add that but dashboard went away again while I was browsing it
these calls were at most 2 mins apart and I'd done nothing in between
```
$ kubectl cluster-info
Kubernetes master is running at https://<redacted>
KubeDNS is running at https://<redatcted>/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://<redacted>/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
owen at Owens-MacBook-Pro in ~/Projects
$ kubectl cluster-info
Kubernetes master is running at https://<redacted>
KubeDNS is running at https://<redacted>/api/v1/proxy/namespaces/kube-system/services/kube-dns

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Comment by aliakhtar** [comment]
Yep, that's the same behavior i experienced

**Comment by buildmaster** [comment]
i took the YML from `https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.1.0.yaml` and modified the version numbers to 1.4 and it seems to be staying up, but it's no longer listed running `kubectl cluster-info`

**Comment by buildmaster** [comment]
![screenshot 2016-10-10 20 53 16](https://cloud.githubusercontent.com/assets/19946/19229655/a2d6c208-8f2b-11e6-81ee-43476546a87b.png)

**Comment by chrislovecnm** [comment]
Guys this really does not smell like a kops issue, can we close this ticket and open in the appropriate repo?

**Comment by mrichmon** [comment]
I experienced the same killing of the dashboard last week if I launched the dashboard using 'kubectl'. However, if I launch the dashboard using the channel tool, then the dashboard does not get killed.

**Comment by aliakhtar** [comment]
@chrislovecnm Lets open it in the other repo and keep this open too, please? Once we have this running on kops then we can close the ticket

**Comment by justinsb** [comment]
I think maybe this is related to kube-addons, a bash/python script which will delete resources that are tagged as `cluster-service`.  It runs every 5 minutes.

If you are running a newer version of kops (since 1.4.0 of kops) we have replaced it with the channels tool running embedded (indeed, this is why the channels tool was originally created).

If you update kops and `kops update` your cluster (which might require a `kops rolling-update cluster`), hopefully kube-addons goes away and this "just works".

This would also explain why some people see it and some people don't!

Note that the "stable" releases of kops are now on the `release` branch, not on master.  And I also just put up a binary release of 1.4.1 based on the release branch :-)

**Comment by buildmaster** [comment]
@justinsb that sounds like it might be my issues, thanks for the pointers (as I said I'm only just getting started so wasn't really able to diagnose myself). I've updated Kops to the latest release branch, and recreated the cluster. Then deployed the dashboard at 1.4 and everything seems to be staying alive now.

Massive Thanks for all the help and pointers! 👏

**Comment by aliakhtar** [comment]
@justinsb  Updated kops to 1.4.1, thanks.  There's an `addon.yaml` in addons/dashboard, and also a 1.4.yaml . Which of these needs to get applied?

**Comment by aliakhtar** [comment]
@buildmaster Are you able to see the newer visualizations now too? If so can you share which of the yaml files you created please?

**Comment by buildmaster** [comment]
@aliakhtar yep, I've got everything running as expected. Close the issue 😀 thanks everyone!

**Comment by aliakhtar** [comment]
@buildmaster Mind sharing your full yaml please? Also which dashboard yaml did you use?

**Comment by buildmaster** [comment]
the YML files are from here https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb the only one I modified was `influxdb-grafana-controller.yml` here: https://gist.github.com/buildmaster/27c255f4081bfb0e6a4c6da6717d8f39

I used `kubectl apply -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.4.0.yaml` for the dashboard

**Comment by aliakhtar** [comment]
Thanks.

So I'm doing the following:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.4.0.yaml

kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/grafana-service.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster-service.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/influxdb-service.yaml
kubectl apply -f https://gist.githubusercontent.com/aliakhtar/ceda67ada28bae0708f06bbd51a84b9c/raw/6ee75bc6c57d70afd9d9c64b89e6af07bc813926/influxdb-grafana-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster-controller.yaml
```

The dashboard has stayed up so far, but I'm not seeing any visualizations.

@buildmaster Did you create any files outside of the ones I listed above?

**Comment by aliakhtar** [comment]
Nevermind, I see them now. I suppose it just didn't have enough data before. Cool!

**Comment by rturk** [comment]
Found this issue, but this was closed in 2016. Can this be properly documented? Overall how can I install with Kops?

**Comment by matjam** [comment]
yeah, this is not particularly clear. @aliakhtar if we apply all of what you suggest, will things work? Or are there other steps?

**Comment by matjam** [comment]
This was one of many threads I came across searching for instructions on how to configure Kubernetes with the dashboard, if your instance didn't get built with it. In my case, I used Kops, so I needed to do the following:

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/influxdb.yaml
kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/grafana.yaml
kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml
kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.6.3.yaml
```

I hope this is useful for other people googling who are lost.
