### ISSUE TITLE
Supporting horizontal-pod-autoscaler-downscale-stabilization in kube-controller-manager.

### ISSUE THREAD

**Issue by chhsiao1981** [kubernetes/kops#6198]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

According to [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/options/hpacontroller.go) and [here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/), I would like to set the additional flag horizontal-pod-autoscaler-downscale-stabilization to kube-controller-manager

Looks like the feature-request is similar to #3602 but with different flag.

**2. Feel free to provide a design supporting your feature request.**

It would be awesome to have kube-controller-manager onto spec so Kops users can set flags to kube-controller-manager

**Comment by dozer47528** [comment]
Need this feature too.
