### ISSUE TITLE
networking set as external launches kubelet with kubenet option

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#620]
Launch a new cluster with this:

```console
kops \
  --state $KOPS_STATE_STORE \
  create cluster \
  --node-count 4 \
  --zones $ZONES \
  --master-zones $ZONES \
  --master-size m4.large \
  --node-size m4.large \
  --networking external \
  --yes \
  --name $NAME
```

Version:

```console
$ kops version
Version git-4bca0a3
```

The cluster launched, but `kubelet` is running with:

```console
 /usr/local/bin/kubelet --allow-privileged=true --api-servers=http://127.0.0.1:8080 --babysitdaemons=true --cgroup-root=docker --cloud-provider=aws --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --config=/etc/kubernetes/manifests --configure-cbr0=true --enable-debugging-handlers=true --hostname-override=ip-172-20-68-196.eu-west-1.compute.internal --network-plugin-mtu=9001 --network-plugin=kubenet --node-labels=kubernetes.io/role=master --non-masquerade-cidr=100.64.0.0/10 --pod-cidr=10.123.45.0/29 --reconcile-cidr=true --register-schedulable=false --v=2
```

I believe that we have an extra `kubenet` option running around.

The funny thing is that the weave daemonset does install and finds the nodes, but I would rather not take my chances and have the `--network-plugin=` set to `cni`.

**Comment by chrislovecnm** [comment]
I am working on a PR too fix this issue.  Two things that I am changing

``diff
diff --git a/upup/pkg/fi/cloudup/tagbuilder.go b/upup/pkg/fi/cloudup/tagbuilder.go
index dc4ed9d..5046d1d 100644
--- a/upup/pkg/fi/cloudup/tagbuilder.go
+++ b/upup/pkg/fi/cloudup/tagbuilder.go
@@ -21,7 +21,7 @@ func buildCloudupTags(cluster *api.Cluster) (map[string]struct{}, error) {
                tags["_networking_kubenet"] = struct{}{}
        } else if networking.External != nil {
                // external is based on kubenet
-               tags["_networking_kubenet"] = struct{}{}
+               // tags["_networking_kubenet"] = struct{}{}
                tags["_networking_external"] = struct{}{}
        } else {
                return nil, fmt.Errorf("No networking mode set")
```
Secondly adding the model files

```console
$ cat upup/models/config/components/kubelet/_networking_external/kubelet.external.options
Kubelet:
  NetworkPluginName: cni
  ReconcileCIDR: true
```

@justinsb let me know if I am off a bit, but I think this is how it is done :)

**Comment by justinsb** [comment]
Maybe create a new mode called CNI or Weave?  We can now automatically install e.g. a daemonset, so we could have `networking: weave {}` work out the box, and then extract the CNI commonalities.  And I can add the automatic daemonset installation if you tell me the daemonset, but it's done here: https://github.com/kubernetes/kops/tree/master/upup/models/cloudup/resources/addons

For external I had originally envisaged the kopeio-routing model, where kubernetes just sees a working networking fabric with each node having the PodCIDR.  I think I'd rather not break that for anyone that might be using it, just in case anyone is!

**Comment by chrislovecnm** [comment]
@justinsb already did https://github.com/kubernetes/kops/pull/621

Yah we need to look at addons as well.  It would be nice if that can be part of the config yaml.

**Comment by chrislovecnm** [comment]
This is DONE
