### ISSUE TITLE
I want to contribute to Kops

### ISSUE THREAD

**Issue by AlexB138** [kubernetes/kops#6205]
Let's talk about how people who want to contribute to the project can be effectively on boarded.

This issue emerged from conversations in the SIG AWS update at Kubecon. Several attendees, including myself, expressed interest in contributing and @justinsb asked me to raise the issue here.

What can we do as a group to start contributing?

**Comment by mikesplain** [comment]
YEEEEES! We're always happy to have more contributors! Besides the standard [contributing doc](https://github.com/kubernetes/kops/blob/master/CONTRIBUTING.md), you should poke around for issues that seem reasonable for you to take on.  You can also look for issues labeled as `good-starter-issue` to jump in on (we need to go through and label more).  Also feel free to ask on #kops-dev if you need help.

Hopefully this issue can turn into a good dumping ground of deets on how to get more involved!

**Comment by rifelpet** [comment]
I dont have permission to add `good-starter-issue` or `good-first-issue` labels, but skimming through open issues, these stand out to me as good opportunities:

### CLI

* #5967 - look in `cmd/kops/create_cluster.go`

### API additions

These are just adding new fields in the api specs that get converted into command line flags for the relevant components. Here are example PRs that add similar fields: #6171 #5890 

Also see [the dev documentation](./docs/development/api_updates.md) for specific instructions.
* #5826
* #6016
* #5803
* #5715

### Docs

Docs improvements are always appreciated! They can also reduce the volume of support questions in our slack channels 😄 I'm sure there are areas of our docs that are out-of-date outside of these issues, so a full pass through could certainly help.
* #5765
* #5754
* #5738

Also, if you run into issues getting your dev environment setup, improving the [development docs](https://github.com/kubernetes/kops/blob/master/docs/development/building.md) or commenting on #5548 / #2307 could help a ton.

Thanks for taking the initiative!
