### ISSUE TITLE
Release status exposure

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/kops#6206]
We've talked alot lately about recent releases (or  even lack there of).  We are well aware of this issue and talk about it during just about every office hour.  I'd like to figure out a way for us to better expose what's happening.  

To be clear, we cut final Kops releases when we consider them _production ready_.  We encourage you to test our alphas and betas, and to provide feedback on new versions of Kubernetes via issues and PRs. That being said, we haven't kept up our side of the deal... we need an easy way to summarize the current release status and provide our users with as much info as we can on the status of upcoming releases.

Since currently kops 1.11 is blocked by a Kubernetes patch that is not in k/kops, I'd like to propose we raise awareness somewhere in our github repo more effectively (which I hope to discuss here).

----
Options:
* More strictly follow and update [Milestones](https://github.com/kubernetes/kops/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.11)
* Create a centralized one stop source of release status: could be a file somewhere  like `docs/release_status.md` with the latest PRed update on our releases.

----
Other ideas are welcome but I think there could be real value to a status page or updated release note for now until we figure out the best location.  I'm happy to write and own a status page based on summaries of meetings and chats however I wanted to see other's thoughts prior to opening a PR.

Thanks!

**Comment by dzoeteman** [comment]
I think either way it's a good idea to follow/update milestones; it helps people get a general idea of how far the work on the update is, and also allows contributors wanting to help get an update over the finish line to quickly see what they can help with.

A doc would probably be a good option especially for cases like this (waiting for a Kubernetes patch). Just gotta make sure it stays up-to-date (the one problem with documentation; it's out of date as soon as you write it).

**Comment by blakebarnett** [comment]
I think one thing that would help people deal with the slow release is to have concurrent releases for stable, beta, and alpha.

I've been wanting to expand upon the concept of channels in the codebase for a long time, and I think this would help a lot with the communication problem as well because it will take the pressure off of doing a production-ready release, and the testing & alpha releases can happen much more frequently.

The issues preventing this mainly are around the release process being cumbersome and bottlenecked on @justinsb, or at least it used to be, it's been a while since I looked into it.

**Comment by joshphp** [comment]
A single doc that states the status of the upcoming release would be a great start, especially in cases like the present where the release is blocked by something upstream.

**Comment by ms4720** [comment]
A status doc would be great, RELEASE_STATUS.md would make life simpler

**Comment by willnewby** [comment]
As a user of kops with multiple clusters, running with @blakebarnett's idea of alpha/beta/stable release channels sounds super great to me. I can test alpha/beta releases in my sandbox/staging environments and if I really, really need the features in those channels before a stable release is cut with them then I can choose to push that to production.

**Comment by Patafix** [comment]
@mikesplain What is blocking the release of 1.11 ?

**Comment by geekofalltrades** [comment]
@Patafix, according to the #kops-dev Slack channel, it's https://github.com/kubernetes/kubernetes/pull/70154

**Comment by geekofalltrades** [comment]
>Issues go stale after 90d of inactivity.

That's really disheartening. Kubernetes 1.14 is in beta; 1.11 is about to be out of support.

**Comment by ms4720** [comment]
are there any alpha or beta releases for kops 1.12 and later?

**Comment by drewwells** [comment]
1.14 is released

**Comment by dictvm** [comment]
Is there any update on this?

**Comment by rifelpet** [comment]
[Kops 1.12 alpha was just released](https://github.com/kubernetes/kops/releases/tag/1.12.0-alpha.2).
