### ISSUE TITLE
when downsize the count node instance group, should like rolling update

### ISSUE THREAD

**Issue by rj03hou** [kubernetes/kops#6214]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
when downsize the count node instance group, should like rolling update

**2. Feel free to provide a design supporting your feature request.**
In aws, when user downsize the count of node instance group.
when user do kops update cluster --yes, we can do the following steps:
1.  we can make all the instance in  "Auto Scaling Groups" to be "Set Scale In Protection".
2.  we can choose one instance to cordon and drain from cluster and terminate by aws api.
3.  do step 2 until meet the user's request.
4.  update Auto Scaling Groups.
5.  relase all the "Set Scale In Protection".

if don't like this, when user downsize the count for node instance group, autoscale group terminate one instance immediately, and this may affect the service.(I have meet it.)

**Comment by grosser** [comment]
FYI we solved that by listening to the scale-down hook and then manually triggering a drain
