### ISSUE TITLE
 arn:aws:iam conflict in zhy&bjs

### ISSUE THREAD

**Issue by jansony1** [kubernetes/kops#6215]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I am trying to associate instance-profile to instance group according to this link :https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md in zhy&bjs region
```
spec:
  iam:
    profile: arn:aws:iam::1234567890108:instance-profile/kops-custom-node-role
```
while in zhy&bjs region it validate failed with

```
iam.Profile: Invalid value: "arn:aws-cn:iam::182335798701:instance-profile/Ec2FetchS3": Instance Group IAM Instance Profile must be a valid aws arn such as arn:aws:iam::123456789012:instance-profile/KopsExampleRole

``` 

**2. Feel free to provide a design supporting your feature request.**

Add a conditional router, while its in zhy&bjs region, it should start with "arn:aws-cn:iam" rather than " arn:aws:iam"

**Comment by rifelpet** [comment]
@ jansony1 Thanks for reporting this! This has been fixed and will be released in Kops 1.12
