### ISSUE TITLE
 Use existing AWS internal load balancer for exposing multiple Kubernetes services

### ISSUE THREAD

**Issue by sam0104** [kubernetes/kops#6217]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Use existing AWS internal load balancer for exposing multiple Kubernetes services
**2. Feel free to provide a design supporting your feature request.**
I am using Kubernetes deployed using KOPS in AWS. For exposing few services , I have couple of AWS internal load balancer for TCP ports like 22 , 389. These TCP ports can't be used in ingress-controller like Nginx. So for exposing these TCP ports for each deployment , I am using AWS LB. AWS has a limit on number of load balancers per region.

I am looking for a solution to use one aws internal load balancer for multiple services. For example : One AWS LB can use for port 22 , 80 , 389 and send traffic to internal Kubernetes POD using POD internal ports. Using this solution I can minimize my number of AWS LB and expose multiple services pointing to single LB. Any comments are appreciated .

Thanks Sas

**Comment by rajatjindal** [comment]
there is some info here, let us know if that is helpful or not:

https://github.com/kubernetes/ingress-nginx/blob/6eac5785ac2a92f9c658d9f06d97956ed9aed48b/docs/user-guide/exposing-tcp-udp-services.md
