### ISSUE TITLE
Role and Instance profile expected to be named the same, when pre-creating AWS IAM

### ISSUE THREAD

**Issue by PhilStevenson** [kubernetes/kops#6222]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.10.0`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-11-05T13:11:18Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}`

**3. What cloud provider are you using?**

Amazon Web Services

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Create a cluster with restricted deployment policy, this shows only the IAM permissions on the policy, all other permissions work:
```
{
  "Effect": "Allow",
  "Action": [
    "iam:GetInstanceProfile"
  ],
  "Resource": [
     "arn:aws:iam::4xxxxxxxxxx3:instance-profile/kops-kubernetes-nodes_instance-profile",
     "arn:aws:iam::4xxxxxxxxxx3:instance-profile/kops-kubernetes-masters_instance-profile",
     "arn:aws:iam::4xxxxxxxxxx3:instance-profile/kops-kubernetes-bastion_instance-profile"
  ]
},
{
  "Effect": "Allow",
  "Action": [
    "iam:GetRole",
    "iam:GetRolePolicy",
    "iam:PassRole"
  ],
  "Resource": [
     "arn:aws:iam::4xxxxxxxxxx3:role/kops-kubernetes-nodes_role",
     "arn:aws:iam::4xxxxxxxxxx3:role/kops-kubernetes-masters_role",
     "arn:aws:iam::4xxxxxxxxxx3:role/kops-kubernetes-bastion_role"
  ]
},
{
  "Effect": "Allow",
  "Action": [
    "iam:ListInstanceProfiles",
    "iam:ListRoles"
  ],
  "Resource": [
    "*"
  ]
},
```

each of the node groups have their respective instance profiles referenced:

```iam:
   profile: arn:aws:iam::4xxxxxxxxxx3:instance-profile/kops-kubernetes-nodes_instance-profile
```

Since we are using pre-created roles and instance profiles we have added `--lifecycle-overrides=IAMRole=ExistsAndWarnIfChanges,IAMRolePolicy=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges` to the KOPS execution.

**5. What happened after the commands executed?**

```
W1218 11:00:57.007707   45281 executor.go:130] error running task "IAMRole/kops-kubernetes-masters_instance-profile" (9m56s remaining to succeed): error getting role: AccessDenied: User: arn:aws:sts::4xxxxxxxxxx3:assumed-role/kops-deploy_role/kops-deploy is not authorized to perform: iam:GetRole on resource: role kops-kubernetes-masters_instance-profile
	status code: 403, request id: 318f8a3f-02b4-11e9-848d-25868f2e0f30
W1218 11:00:57.007748   45281 executor.go:130] error running task "IAMRole/kops-kubernetes-bastion_instance-profile" (9m56s remaining to succeed): error getting role: AccessDenied: User: arn:aws:sts::4xxxxxxxxxx3:assumed-role/kops-deploy_role/kops-deploy is not authorized to perform: iam:GetRole on resource: role kops-kubernetes-bastion_instance-profile
	status code: 403, request id: 31821c6b-02b4-11e9-ba85-5175b38f6b20
W1218 11:00:57.007766   45281 executor.go:130] error running task "IAMRole/kops-kubernetes-nodes_instance-profile" (9m56s remaining to succeed): error getting role: AccessDenied: User: arn:aws:sts::4xxxxxxxxxx3:assumed-role/kops-deploy_role/kops-deploy is not authorized to perform: iam:GetRole on resource: role kops-kubernetes-nodes_instance-profile
```

So access denied because KOPS tries to look up a role using the name of the instance profile specified, in order to get around this I have to add these 3 ARNs for role that do not need to exist:

```
"arn:aws:iam::4xxxxxxxxxx3:role/kops-kubernetes-nodes_instance-profile",
"arn:aws:iam::4xxxxxxxxxx3:role/kops-kubernetes-masters_instance-profile",
"arn:aws:iam::4xxxxxxxxxx3:role/kops-kubernetes-bastion_instance-profile"
```

This allows kops to look up the roles that do not exist and therefore doesn't fail

**6. What did you expect to happen?**

I expect it to get the role that is associated with the instance profile, and look that up instead of a role that might never exist.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by rifelpet** [comment]
@PhilStevenson you're right, ideally Kops could get the role assigned to the instance profile but it does indeed assume the same name. Normally this isn't an issue but if Kops' permissions are locked down so that it can't GetRole on the name it expects, it will fail. As a workaround can you try changing the lifecycle overrides for each of those IAM tasks from `ExistsAndWarnIfChanges` to `Ignore`? That should at least unblock you from those permission errors.

```
--lifecycle-overrides=IAMRole=Ignore,IAMRolePolicy=Ignore,IAMInstanceProfileRole=Ignore
```
