### ISSUE TITLE
Outdated docs for installation (command not found)

### ISSUE THREAD

**Issue by browne0** [kubernetes/kops#6223]
**1. What commands did you run?  What is the simplest way to reproduce this issue?**
I tried to run the installation script that's in the Readme for Linux.

```
curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
chmod +x kops-linux-amd64
sudo mv kops-linux-amd64 /usr/local/bin/kops
```
**2. What happened after the commands executed?**
I received this error message
`/usr/local/bin/kops: line 1: Not: command not found`

Which made me believe that the curl command was pointing to an outdated location.

**3. What did you expect to happen?**
I expected to download kops with no issues

**4. Anything else do we need to know?**
I was able to manually do it just doing a wget of the latest package - not sure how y'all want to approach this 😄

**Comment by felix-sony** [comment]
I'm getting the exact same problem as @browne0 on Ubuntu 16.04.
For me it seems to be caused by https://api.github.com/repos/kubernetes/kops/releases/latest being rate limited for my company's IP range.

**Comment by joshphp** [comment]
I wonder if it is just the fact that two calls are being made immediately one after the other that it can get rate limited.

**Comment by browne0** [comment]
Hmm, that would be interesting. If that's the issue, I don't think we can resolve that lol. 

I can close the issue if you agree!

**Comment by jonigl** [comment]
I have the same issue with the last version for linux (1.11.0). But if I use version 1.10.1 it's ok, so seems to be some problem with version 1.11.0

**Comment by GDUTKiller** [comment]
I think you haven't downloaded it yet.

**Comment by GDUTKiller** [comment]
I have the same problem as you. I found that I have not downloaded kops-linux-amd64 yet. I downloaded half of it and did the rest.

**Comment by bkimbrough88** [comment]
> I'm getting the exact same problem as @browne0 on Ubuntu 16.04.
> For me it seems to be caused by https://api.github.com/repos/kubernetes/kops/releases/latest being rate limited for my company's IP range.

Yep I ran into the same issue, only solution I found was finding the latest version by hand and putting that in the command instead of CURLing for it.

**Comment by domgreen** [comment]
I had the same experience as @bkimbrough88 ... `curl` resulted in the error:
```
/usr/local/bin/kops: line 1: Not: command not found
```

Downloading the release manually was fine.

**Comment by ravi5358** [comment]
Hi,

While i am entering kops create cluster command, getting kops command not found error. can you please help me 
![Kops command not found](https://user-images.githubusercontent.com/45412208/72458689-0c391380-37ef-11ea-941a-57a752d6100b.PNG)
