### ISSUE TITLE
Docker 17.06+ won't install on CentOS / RHEL / Amazon Linux due to unavailable dependency

### ISSUE THREAD

**Issue by bcorijn** [kubernetes/kops#6225]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Kops head shortly after the 1.11.beta release ( Version 1.11.0-alpha.1 (git-4806708) ), which included my PR https://github.com/kubernetes/kops/commit/4806708c3bd6e8876cfe466de51d2092ad59e71b
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.11.5
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Create a cluster, set docker version in cluster spec to anything higher than 17.06 (I tried 18.06 and 17.09 and use a RHEL / CentOS / Amazon Linux 2 AMI. (I personally use Amazon Linux 2)
As of 17.06 docker decided to use `container-selinux` as dependency instead of packaging in their own, so any version higher than that will show this issue.
If you don't even want to bother with kops, launching one of those AMI's and manually installing docker from an RPM also has this issue.
**5. What happened after the commands executed?**
Nodeup tries to install the higher docker version, but the instal fails with the following message:
```
Error: Package: docker-ce-18.06.1.ce-3.el7.x86_64 (/docker-ce-18.06.1.ce-3.el7.x86_64)
           Requires: container-selinux >= 2.9
```
Which is not present by default in these distros. Centos and RHEL offer it in their extras I believe (that you might need to enable), Amazon linux does not have it available. You can install it manually from http://mirror.centos.org/centos/7/extras/x86_64/Packages/ though. Installing docker through the extras channels in these distros does not require this step. 

Since Docker can't be installed, the cluster obviously does not come up.
**6. What did you expect to happen?**
Cluster comes up with the requested version of docker

**9. Anything else do we need to know?**
I did my PR mirroring what was already available for 17.09, not expecting any issues but didn't verify that 17.09 itself would work. I am not really sure how to handle this case since the dependency is not readily availably from yum and fixing it seems to depend on which distro you are using. 
Should I add a direct URL to the dependency (fixing the version, which is not ideal), bake this into the AMI (not very future proof either) or should this be solved somewhere else in nodeup? 

The install issue itself is a known issue outside of kops fwiw: https://stackoverflow.com/questions/45272827/docker-ce-on-rhel-requires-container-selinux-2-9

**Comment by xrl** [comment]
I'm trying to install docker 18.06.1 on my image, I got the nodeup to keep going by running:

```
yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.68-1.el7.noarch.rpm
```

and now I need to figure out how to put that in the kops bootstrapping system.

**Comment by bcorijn** [comment]
@xrl that indeed fixes it and is what this issue is about, but that fix is only for Amazon Linux and fixes the version of course. Getting a future proof way into kops is not all that easy I believe.
Most of the options provided by kops for user input are executed later on in the life cycle

**Comment by xrl** [comment]
I am going to test a kops hook off the cluster object:

```
spec:
  hooks:
  - name: install-dockers-prereq.service
    before:
      - kops-configuration.service
    roles: [Master]
    manifest: |
      [Unit]
      Description=Hack-Workaround: Download Docker Prerequisite Package
      [Service]
      Type=oneshot
      ExecStart=yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.68-1.el7.noarch.rpm
```

**Comment by bcorijn** [comment]
@xrl Any luck with that hook? I had though about hooks, but only considered container-hooks, which would of course fail. A systemd hook should work indeed and I'll be trying it out myself as well one of the next days.

**Comment by xrl** [comment]
@bcorijn I fixed it through code and building my own nodeup. So it's involved. You'll want these commits:

https://github.com/tureus/kops/commit/5ec896d31b90497c36d193ea47b6833d403c437b
https://github.com/tureus/kops/commit/bc84fd107e193a6ff72cb63b14c03bac5179d116

then you can go in to the kops project and do `make upload` with the right environmental variables set.

If that's useful perhaps I should turn it in to a PR 😄

**Comment by nareshku** [comment]
@xrl any plans on submitting this PR soon?

**Comment by xrl** [comment]
It turns out the Amazon Linux 2 did not solve any of my issues with AWS VPC CNI so I don't think I'll be supported this work. Please feel free to grab the commits and do with them as you wish, public domain on those two commits.

**Comment by nareshku** [comment]
@xrl I was able to create a cluster with Docker v18.06.1 on AWS Linux 2 with AWS VPC CNI. Here is the [PR](https://github.com/kubernetes/kops/pull/6338), can you please review?

**Comment by bcorijn** [comment]
Just as a closing note for anyone who might bump into this later: I tried to achieve this before the PR was merged by using hooks, but it just didn't seem possible to hook into the bootstrapping process before the docker install / nodeup. 
Thanks for the PR @nareshku to solve this!

**Comment by migueleliasweb** [comment]
I'm still having the same problem trying to install `18.06.03` in Amazon Linux.

By simulating the same steps as kops would I get the following result:
```
# docker ps
-bash: docker: command not found
# wget https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.06.3.ce-3.el7.x86_64.rpm
--2019-04-26 06:11:45--  https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.06.3.ce-3.el7.x86_64.rpm
Resolving download.docker.com (download.docker.com)... 13.35.146.103, 13.35.146.107, 13.35.146.113, ...
Connecting to download.docker.com (download.docker.com)|13.35.146.103|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42708244 (41M) [binary/octet-stream]
Saving to: ‘docker-ce-18.06.3.ce-3.el7.x86_64.rpm’

100%[=========================================================================================================================================================================>] 42,708,244  10.2MB/s   in 4.2s

2019-04-26 06:11:49 (9.77 MB/s) - ‘docker-ce-18.06.3.ce-3.el7.x86_64.rpm’ saved [42708244/42708244]

# yum install libtool-ltdl libseccomp libcgroup policycoreutils-python
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                                                                                                                  | 2.4 kB  00:00:00
Package libtool-ltdl-2.4.2-22.2.amzn2.0.2.x86_64 already installed and latest version
Package libseccomp-2.3.1-3.amzn2.0.3.x86_64 already installed and latest version
Package libcgroup-0.41-15.amzn2.x86_64 already installed and latest version
Package policycoreutils-python-2.5-22.amzn2.x86_64 already installed and latest version
Nothing to do
# rpm -i
.ansible/                              .cache/                                docker-ce-18.06.3.ce-3.el7.x86_64.rpm  .ssh/
# rpm -i docker-ce-18.06.3.ce-3.el7.x86_64.rpm
warning: docker-ce-18.06.3.ce-3.el7.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
error: Failed dependencies:
        container-selinux >= 2.9 is needed by docker-ce-18.06.3.ce-3.el7.x86_64
```
