### ISSUE TITLE
Cant receive metrics after set the params ` --authentication-token-webhook `

### ISSUE THREAD

**Issue by zyriuse75** [kubernetes/kops#6228]
hi folks 

I set the params` --authentication-token-webhook` in my file` /etc/systemd/system/kubelet.service.d/10-kubeadm.conf` for more [details ](https://gist.github.com/zyriuse75/d4b3ecc3e6c51ad4fb3f21117f6bfb4e) Unfortunately i dont receive any **metrics** . 

I have checked that the new parameters are taken 

```
systemctl daemon-reload
systemctl restart kubelet.service 
```

And everything [looking good](https://gist.github.com/zyriuse75/99e5d8d74972d32f83f9a3ce82d224e4)  

```
kubectl get hpa --namespace ns-svc-cas                                            
NAME      REFERENCE                   TARGETS                          MINPODS   MAXPODS   REPLICAS   AGE               
hpa-pod   Deployment/podInfoCasDpAp   <unknown>/100Mi, <unknown>/10%   1         4         0          1d   
```
 i try to understand why but I'm running out of options. :(

**Comment by rajatjindal** [comment]
can you check kubelet logs on the node where the pods are running

on my cluster running on AWS i run: journalctl -u kubelet and look for 'GET /stats/summary/'
