### ISSUE TITLE
etcd dns entries fall back to 203.0.113.123

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#6241]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.10

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.10.11

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Unknown.   Cluster stood up, dns entries eventually fail to the 203 address

**5. What happened after the commands executed?**
Cluster stood up correctly

**6. What did you expect to happen?**
DNS entries remain stable and point to the right etcd members

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
na?

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
na?

**9. Anything else do we need to know?**
Two different clusters with etcd DNS entries pointing to oblivion:

```bash
$ aws route53 list-resource-record-sets --hosted-zone-id $(aws route53 list-hosted-zones | jq -r ".HostedZones[] | select(.Name==\"prod.blah.com.\") | .Id")  | jq -r '.ResourceRecordSets[] | select(.Type=="A") | select(.Name | contains("etcd")) | .ResourceRecords[].Value + " " + .Name'
203.0.113.123 etcd--1a.internal.prod-blue-us-east-1.blah.com.
203.0.113.123 etcd--1b.internal.prod-blue-us-east-1.blah.com.
203.0.113.123 etcd--1d.internal.prod-blue-us-east-1.blah.com.
203.0.113.123 etcd-events--1a.internal.prod-blue-us-east-1.blah.com.
203.0.113.123 etcd-events--1b.internal.prod-blue-us-east-1.blah.com.
203.0.113.123 etcd-events--1d.internal.prod-blue-us-east-1.blah.com.
203.0.113.123 etcd--2a.internal.ukprod-blue-eu-west-2.blah.com.
203.0.113.123 etcd--2b.internal.ukprod-blue-eu-west-2.blah.com.
203.0.113.123 etcd--2c.internal.ukprod-blue-eu-west-2.blah.com.
203.0.113.123 etcd-events--2a.internal.ukprod-blue-eu-west-2.blah.com.
203.0.113.123 etcd-events--2b.internal.ukprod-blue-eu-west-2.blah.com.
203.0.113.123 etcd-events--2c.internal.ukprod-blue-eu-west-2.blah.com.
```

**Comment by zapman449** [comment]
I've seen this issue cause full-cluster-lockups since the etcd instances fail to converge to a cluster.  

Current work-around is building monitoring for the dns condition, and human intervention before the cluster can fail.

Cluster failure seems to be related to master node restart after all 3 etcd instances' DNS entry points to 203... .  Out of band fixing the DNS entries seems to resolve the issue in a few minutes.

To be clear the cluster failure is due to etcd (either events or main) going unresponsive due to lack of quorum.

**Comment by zapman449** [comment]
etcd version 3.1.12
etcd-manager is in play.

**Comment by aranair** [comment]
if you're on etcd-manager, it now creates /etc/hosts entries on the master nodes to resolve that I think
