### ISSUE TITLE
defaultCNIAsset hardcoded in apply_cluster.go

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#626]
https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/apply_cluster.go#L172 has a hard coded value for the CNI plugin.

**Comment by justinsb** [comment]
Correct ... I bumped https://github.com/kubernetes/kubernetes/issues/30338 to hope to get an answer on this

**Comment by chrislovecnm** [comment]
Where is kube-up installing it from?

**Comment by chrislovecnm** [comment]
It is still hardcoded, but we have a way to override it as well.
