### ISSUE TITLE
Can't delete cluster - NAT not found AWS

### ISSUE THREAD

**Issue by pulpbill** [kubernetes/kops#6306]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0 (git-8b52ea6d1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
This happens when trying to update/delete the cluster

**5. What happened after the commands executed?**
I0107 19:54:02.618454    8397 request_logger.go:45] AWS request: autoscaling/DescribeAutoScalingGroups
I0107 19:54:02.812764    8397 request_logger.go:45] AWS request: ec2/DescribeNatGateways
W0107 19:54:03.032646    8397 executor.go:130] error running task "ElasticIP/us-east-1a.my.domain" (9m56s remaining to succeed): error finding AssociatedNatGatewayRouteTable: error listing NatGateway %!q(*string=0xc42169eb08): NatGatewayNotFound: NAT gateway nat-083300682d9a0fa74 was not found
	status code: 400, request id: 8408a79d-1f8f-4886-83d9-ae0a26c1cc47
I0107 19:54:03.032738    8397 executor.go:103] Tasks: 98 done / 101 total; 1 can run
I0107 19:54:03.032828    8397 executor.go:178] Executing task "ElasticIP/us-east-1a.my.domain": *awstasks.ElasticIP {"Name":"us-east-1a.my.domain","Lifecycle":"Sync","ID":null,"PublicIP":null,"TagOnSubnet":null,"Tags":{"KubernetesCluster":"my.domain","Name":"us-east-1a.my.domain","kubernetes.io/cluster/my.domain":"owned"},"AssociatedNatGatewayRouteTable":{"Name":"private-us-east-1a.my.domain","Lifecycle":"Sync","ID":"rtb-089bd4ffc062a3b15","VPC":{"Name":"my.domain","Lifecycle":"Sync","ID":"vpc-0b638e55c11fc9021","CIDR":"172.10.0.0/16","EnableDNSHostnames":null,"EnableDNSSupport":true,"Shared":true,"Tags":null},"Shared":false,"Tags":{"KubernetesCluster":"my.domain","Name":"private-us-east-1a.my.domain","kubernetes.io/cluster/my.domain":"owned","kubernetes.io/kops/role":"private-us-east-1a"}}}
I0107 19:54:03.033039    8397 natgateway.go:205] trying to match NatGateway via RouteTable rtb-089bd4ffc062a3b15
I0107 19:54:03.033304    8397 request_logger.go:45] AWS request: ec2/DescribeRouteTables
I0107 19:54:03.741980    8397 request_logger.go:45] AWS request: ec2/DescribeNatGateways
W0107 19:54:03.981744    8397 executor.go:130] error running task "ElasticIP/us-east-1a.my.domain" (9m55s remaining to succeed): error finding AssociatedNatGatewayRouteTable: error listing NatGateway %!q(*string=0xc4217e8da8): NatGatewayNotFound: NAT gateway nat-083300682d9a0fa74 was not found
	status code: 400, request id: 3be6843a-38e2-4584-b2cd-b29f6a132d2d
I0107 19:54:03.981881    8397 executor.go:145] No progress made, sleeping before retrying 1 failed task(s)
I0107 19:54:13.982261    8397 executor.go:103] Tasks: 98 done / 101 total; 1 can run

**6. What did you expect to happen?**
To delete the cluster entirely

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-01-02T16:37:37Z
  name: my.domain
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://my.domain/my.domain
  dnsZone: my.domain
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.12
  masterPublicName: api.my.domain
  networkCIDR: 172.10.0.0/16
  networkID: vpc-0b638e55c11fc9021
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 172.10.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.10.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.10.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  topology:
    bastion:
      bastionPublicName: bastion.my.domain
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-01-02T16:37:38Z
  labels:
    kops.k8s.io/cluster: my.domain
  name: bastions
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-01-02T16:37:37Z
  labels:
    kops.k8s.io/cluster: my.domain
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  rootVolumeSize: 20
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-01-02T16:37:38Z
  labels:
    kops.k8s.io/cluster: my.domain
  name: nodes
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 40
  subnets:
  - us-east-1a

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I changed kubectl version and tried going back to the previous one, but nothing. (after seeing this issue) manually deleted subnets that wasn't at use but still. I can't delete this cluster so I can re create it.

**Comment by pulpbill** [comment]
Adding more output

**Comment by pulpbill** [comment]
At least, is there a file where I can edit what kops' looking at AWS so I can remove this object? I couldn't find at config/spec S3 files.

**Comment by maurya-m** [comment]
@pulpbill , i had the S3 bucket versioned , but still not able to update / delete the cluster.

**Comment by pulpbill** [comment]
@maurya-m sorry the delay, didn't try rolling back, deleted everything manually.

**Comment by pulpbill** [comment]
Now I can't create the cluster, same issue, tried with kops 1.9 - 10 - 11 - 12
Not only I couldn't create the cluster, now I can't delete it, and have to go to AWS console and manually delete everything. Delete/create S3 bucket and try again.

```
I0307 17:16:53.969708   28681 executor.go:133] No progress made, sleeping before retrying 3 failed task(s)
I0307 17:17:03.970028   28681 executor.go:91] Tasks: 127 done / 136 total; 3 can run
I0307 17:17:03.970150   28681 executor.go:166] Executing task "ElasticIP/us-east-1b.my.cluster": *awstasks.ElasticIP {"Name":"us-east-1b.my.cluster","Lifecycle":"Sync","ID":null,"PublicIP":null,"TagOnSubnet":null,"Tags":{"KubernetesCluster":"my.cluster","Name":"us-east-1b.my.cluster","kubernetes.io/cluster/my.cluster":"owned"},"AssociatedNatGatewayRouteTable":{"Name":"private-us-east-1b.my.cluster","Lifecycle":"Sync","ID":"rtb-069c09e7fb807fadd","VPC":{"Name":"my.cluster","Lifecycle":"Sync","ID":"vpc-0b703384042739d71","CIDR":"172.20.0.0/16","AdditionalCIDR":null,"EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":false,"Tags":{"KubernetesCluster":"my.cluster","Name":"my.cluster","kubernetes.io/cluster/my.cluster":"owned"}},"Shared":false,"Tags":{"KubernetesCluster":"my.cluster","Name":"private-us-east-1b.my.cluster","kubernetes.io/cluster/my.cluster":"owned","kubernetes.io/kops/role":"private-us-east-1b"}}}
I0307 17:17:03.970206   28681 executor.go:166] Executing task "ElasticIP/us-east-1a.my.cluster": *awstasks.ElasticIP {"Name":"us-east-1a.my.cluster","Lifecycle":"Sync","ID":null,"PublicIP":null,"TagOnSubnet":null,"Tags":{"KubernetesCluster":"my.cluster","Name":"us-east-1a.my.cluster","kubernetes.io/cluster/my.cluster":"owned"},"AssociatedNatGatewayRouteTable":{"Name":"private-us-east-1a.my.cluster","Lifecycle":"Sync","ID":"rtb-0cd2115fc77c2b6e1","VPC":{"Name":"my.cluster","Lifecycle":"Sync","ID":"vpc-0b703384042739d71","CIDR":"172.20.0.0/16","AdditionalCIDR":null,"EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":false,"Tags":{"KubernetesCluster":"my.cluster","Name":"my.cluster","kubernetes.io/cluster/my.cluster":"owned"}},"Shared":false,"Tags":{"KubernetesCluster":"my.cluster","Name":"private-us-east-1a.my.cluster","kubernetes.io/cluster/my.cluster":"owned","kubernetes.io/kops/role":"private-us-east-1a"}}}
I0307 17:17:03.970511   28681 natgateway.go:205] trying to match NatGateway via RouteTable rtb-0cd2115fc77c2b6e1
I0307 17:17:03.970213   28681 executor.go:166] Executing task "ElasticIP/us-east-1c.my.cluster": *awstasks.ElasticIP {"Name":"us-east-1c.my.cluster","Lifecycle":"Sync","ID":null,"PublicIP":null,"TagOnSubnet":null,"Tags":{"KubernetesCluster":"my.cluster","Name":"us-east-1c.my.cluster","kubernetes.io/cluster/my.cluster":"owned"},"AssociatedNatGatewayRouteTable":{"Name":"private-us-east-1c.my.cluster","Lifecycle":"Sync","ID":"rtb-000d80e54f02fb824","VPC":{"Name":"my.cluster","Lifecycle":"Sync","ID":"vpc-0b703384042739d71","CIDR":"172.20.0.0/16","AdditionalCIDR":null,"EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":false,"Tags":{"KubernetesCluster":"my.cluster","Name":"my.cluster","kubernetes.io/cluster/my.cluster":"owned"}},"Shared":false,"Tags":{"KubernetesCluster":"my.cluster","Name":"private-us-east-1c.my.cluster","kubernetes.io/cluster/my.cluster":"owned","kubernetes.io/kops/role":"private-us-east-1c"}}}
I0307 17:17:03.970626   28681 natgateway.go:205] trying to match NatGateway via RouteTable rtb-000d80e54f02fb824
I0307 17:17:03.970440   28681 natgateway.go:205] trying to match NatGateway via RouteTable rtb-069c09e7fb807fadd
I0307 17:17:03.970869   28681 request_logger.go:45] AWS request: ec2/DescribeRouteTables
I0307 17:17:03.971149   28681 request_logger.go:45] AWS request: ec2/DescribeRouteTables
I0307 17:17:03.970931   28681 request_logger.go:45] AWS request: ec2/DescribeRouteTables
I0307 17:17:04.146175   28681 request_logger.go:45] AWS request: ec2/DescribeNatGateways
I0307 17:17:04.152601   28681 natgateway.go:220] no NatGateway found in route table rtb-069c09e7fb807fadd
I0307 17:17:04.152663   28681 elastic_ip.go:90] AssociatedNatGatewayRouteTable not found
I0307 17:17:04.152821   28681 elastic_ip.go:237] Creating ElasticIP for VPC
I0307 17:17:04.152990   28681 request_logger.go:45] AWS request: ec2/AllocateAddress
I0307 17:17:04.320220   28681 request_logger.go:45] AWS request: ec2/DescribeNatGateways
W0307 17:17:04.682730   28681 executor.go:118] error running task "ElasticIP/us-east-1a.my.cluster" (9m22s remaining to succeed): error finding AssociatedNatGatewayRouteTable: error listing NatGateway %!q(*string=0xc4212d20e8): NatGatewayNotFound: NAT gateway nat-0d53dd199d9acfdbb was not found
	status code: 400, request id: 494ce862-7f72-4f8d-aecd-d519f4cadb5b
W0307 17:17:04.682896   28681 executor.go:118] error running task "ElasticIP/us-east-1c.my.cluster" (9m22s remaining to succeed): error finding AssociatedNatGatewayRouteTable: error listing NatGateway %!q(*string=0xc42132dc48): NatGatewayNotFound: NAT gateway nat-0274d61c82fd0d8f7 was not found
	status code: 400, request id: 9b11b85c-7d21-40e9-9677-c2f237f3a95a
W0307 17:17:04.682958   28681 executor.go:118] error running task "ElasticIP/us-east-1b.my.cluster" (9m22s remaining to succeed): error creating ElasticIP: AddressLimitExceeded: The maximum number of addresses has been reached.
	status code: 400, request id: 1d0cf6b2-8fcc-4890-ad74-4fc99f211588
I0307 17:17:04.683019   28681 executor.go:133] No progress made, sleeping before retrying 3 failed task(s)
 I0307 17:17:14.683383   28681 executor.go:91] Tasks: 127 done / 136 total; 3 can run
```

**Comment by pulpbill** [comment]
After anothe manual deletion of resources created by kops, the next try for a new cluster worked. 

kubectl version : 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```
kops version:
`Version 1.11.0 (git-2c2042465)`

There was obviously something stucked but since I deleted everything as usual, couldn't tell what it was. (I'm using kops 1.11)
