### ISSUE TITLE
Kops not working with new Gov Region us-gov-east-1

### ISSUE THREAD

**Issue by ekm1908** [kubernetes/kops#6325]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.11.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Kubernetes version: v1.11.x

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster --node-count=2 --node-size=t2.medium --zones=us-gov-east-1 --name=test1 

**5. What happened after the commands executed?**
error reading cluster configuration "test1": error reading s3://*******/test1/config: us-gov-east-1 is not a valid region
Please check that your region is formatted correctly (i.e. us-east-1)

**6. What did you expect to happen?**
Cluster creation

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
Not able to generate

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

kops create cluster --node-count=2 --node-size=t2.medium --zones=us-gov-east-1 --name=test1 -v 10
I0111 17:40:43.805616   19728 factory.go:68] state store s3://**********8

error reading cluster configuration "test1": error reading s3://********/test1/config: us-gov-east-1 is not a valid region
Please check that your region is formatted correctly (i.e. us-east-1)

**9. Anything else do we need to know?**

The region us-gov-east was addded recently. Works fine in us-gov-west.

**Comment by immesys** [comment]
Same problem for me. For latency reasons I need to be on the east coast in gov cloud, any chance this could be fixed?

**Comment by immesys** [comment]
I've built a custom kops that includes support for us-gov-east, and copied the kope.io k8s-1.11 image into govcloud (which is a pain) but the nodes don't start because they install their own kubernetes that doesn't recognize the region. Here are the logs from kops-configuration.service on a master node:

```
Jan 24 04:55:19 ip-172-20-126-73 nodeup[1139]: W0124 04:55:19.139194    1139 main.go:142] got error running nodeup (will retry in 30s): error loading Cluster "s3://pt-govcloud-east-dev/pt-govcloud-east-dev.k8s.local/cluster.spec": us-gov-east-1 is not a valid region
Jan 24 04:55:19 ip-172-20-126-73 nodeup[1139]: Please check that your region is formatted correctly (i.e. us-east-1)
```

I'm getting further down the rabbit hole but is there a way for me to get a custom version of kops/k8s on the nodes that kops creates?

**Comment by immesys** [comment]
For those who find this with the same problem as me, the solution for me was to follow the instructions in [here](https://github.com/kubernetes/kops/blob/master/docs/development/testing.md#running-the-kubernetes-e2e-test-suite) for testing a custom kops build. It involves uploading a nodeup that knows about us-gov-east-1 to s3 and getting kops to use that when creating a cluster.

I'll open a pull request with my changes to kops, they are quite minimal

**Comment by babilen5** [comment]
> I'll open a pull request with my changes to kops, they are quite minimal

Did you, by chance, get around to look into this?

**Comment by immesys** [comment]
The problem is that the patch needs to change vendored dependencies (AWS SDK and kubernetes), so despite being small, it's not really that feasible. Here is the patch:

A change to kubernetes itself. We need them to add this:
```
--- a/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/regions.go
+++ b/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/regions.go
@@ -45,6 +46,7 @@ var WellKnownRegions = [...]string{
        // these are not registered in many / most accounts
        "cn-north-1",
        "us-gov-west-1",
+       "us-gov-east-1",
 }
 
 // awsRegionsMutex protects awsRegions
```
Then, update AWS SDK to a newer version that includes govcloud.

Then just these lines:
```
/go/src/k8s.io/kops$ git diff pkg/
diff --git a/pkg/model/iam/iam_builder.go b/pkg/model/iam/iam_builder.go
index e3a7cb465..618bfbe91 100644
--- a/pkg/model/iam/iam_builder.go
+++ b/pkg/model/iam/iam_builder.go
@@ -261,6 +261,8 @@ func (b *PolicyBuilder) IAMPrefix() string {
                return "arn:aws-cn"
        case "us-gov-west-1":
                return "arn:aws-us-gov"
+       case "us-gov-east-1":
+               return "arn:aws-us-gov"
        default:
                return "arn:aws"
        }
/go/src/k8s.io/kops$ git diff upup/
diff --git a/upup/pkg/fi/cloud.go b/upup/pkg/fi/cloud.go
index 428380887..b64a49cdd 100644
--- a/upup/pkg/fi/cloud.go
+++ b/upup/pkg/fi/cloud.go
@@ -155,6 +155,10 @@ var zonesToCloud = map[string]kops.CloudProviderID{
        "us-gov-west-1a": kops.CloudProviderAWS,
        "us-gov-west-1b": kops.CloudProviderAWS,
 
+       "us-gov-east-1a": kops.CloudProviderAWS,
+       "us-gov-east-1b": kops.CloudProviderAWS,
+       "us-gov-east-1c": kops.CloudProviderAWS,
+
        // GCE
        "asia-east1-a": kops.CloudProviderGCE,
        "asia-east1-b": kops.CloudProviderGCE,
```

**Comment by immesys** [comment]
That line in kubernetes isn't present even in 1.14. Even if they added it, would they add it to old releases or just to a new release?
