### ISSUE TITLE
HTTP Wrapper for kops API

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#633]
With all of the work going into abstracting kops into a library (api).. Should we look at offering an HTTP(s) wrapper for the new lib/api?

I think it would be very benifecial to wrap the structs defined in [PR 632](https://github.com/kubernetes/kops/pull/632) in an HTTP layer - thoughts?

@justinsb @chrislovecnm

**Comment by justinsb** [comment]
Definitely.... in fact we're using a lot of the k8s API machinery.  The bit we aren't currently using is the apiserver (or the autogenerated clients), but we could enable that and have the same code run on a server, just like k8s.

I see two possible scenarios for that:

1) this could be a nice way to bring up k8s on the cloud.  "Somehow" bring up a control plane (e.g. an all in one image), and then run a kops-controller pod and start adding kops objects for your instance groups. 

2) kops could be run as GKE like service: you have one "master" kubernetes cluster in which the kops objects for the various clusters live, and then kops-controllers go and build the "child" clusters.  That "master" cluster could of course be built using kops in S3 mode.

The S3 mode vs k8s mode thing has been a bit of a pain at times, but it might turn out to be quite nice.  One of the biggest challenges of starting kubernetes is the need for the "pivot", where we somehow move from a "boostrap" cluster to a "full" cluster.  But I feel this is easier with S3 -> etcd (though this is only solving the bootstrap problem, it does't solve e.g. the kubelet upgrade problem.)

We shouldn't give up the S3/standalone CLI mode though.  But I think the same code can work on both - one of the reasons I've pushing more and more code to work through the client interface (which is supposed to look like a k8s client interface)

**Comment by kris-nova** [comment]
The way I had imagined this working when I was day-dreaming on the matter was : 

1. User checks out kops
2. User deploys a primitive k8s cluster via kops (CLI + S3)
3. `Kops` + `HTTP` is deployed to the newly created k8s cluster as a pod.
4. A user can now interact with kops via a traditional HTTP API.

I think this sparkles with **example number 2** that you had mentioned.

Now, as far as storing state in this example.. I think getting kops into `k8s mode` could prove to be invaluable. I don't think I need to sell anyone here on the value of running an application in k8s! However, like you said we **absolutely** need to continue to support CLI/S3. 

There obviously are quite a few patterns we could use to store data in different data stores, and swapping them out **should be** fairly trivial. Also, it sounds like a lot of the boiler plate is in place for an API server to interact with `kops`...  

So I think this leaves us with two main paradigms behind `kops` operating modes.

1. A **traditional** mode that is kops as we know it, with state in **S3**.
2. A **kubernetes** mode that is `kops` + `http`, with state in **etcd** running on k8s.

And I think we can (and probably should) support both modes.

Thoughts?

**Comment by Grillz** [comment]
This would be very beneficial to my teams development. Although I'm not sure I'm crazy about using both s3 and etcd as mentioned in method two. I see how that could logically be the simplest path, but I feel like the extra pieces complicates things. Perhaps there should be two modes: a way of bootstrapping it with etcd, or fallback to a default of just using s3.

**Comment by chrislovecnm** [comment]
And the question of the hour. Do we want to use k8s etcd or our own datastore?  

@Grillz we have the basic Causality Delima where we would not have a K8s server to host a kops microservice, and do not have an etcd data source when we are installing for the very first time.  After we have the first cluster, then we have a place to host a microservice.

**Comment by kris-nova** [comment]
Hey @Grillz, 

@chrislovecnm is right about the needing a cluster to deploy a microservice (that will then deploy more microservices and clusters...) 

Also I think it's important to note that with the two proposed modes (**traditional** and **kubernetes**) each would have it's own data store. Neither of them would ever be used at the same time to store kops data.

As far the question of the hour is concerned I think the starting point is to get kops to use the **existing etcd** datastore in kubernetes.. I know it's a gutsy move - but I think it's the easiest way in.

Thoughts?

**Comment by mrxinu** [comment]
This would be an excellent addition to the current functionality. The toughest sell for this tech, at least with my customers, is the maintenance overhead so being able to use an API in alongside the existing CLI/S3 option would really smooth things out. Kudos to @kris-nova for the suggestion and everyone else for chiming in! I'm excited to see how this pans out! 👍

**Comment by mrichmon** [comment]
What is the purpose of the simple k8s cluster? Would the proposed scenario be met with:

1. User launches stand-alone HTTP server exposing a kops API. (Using S3 for confit store)
2. User calls HTTP API to launch cluster.
3. Optional addon runs HTTP API server in a pod.

Ideally, the `kops` command could evolve to being a thin client that calls the API server.  An optional "--server=bootstrap" flag to indicate "launch the API server and call the API server".

**Comment by kris-nova** [comment]
@mrichmon 

My thoughts on the preliminary k8s cluster : 

1. Because we still would offer kops from the command line, deploying a cluster will be baked into kops already. It makes sense to just run kops in a pod on a cluster it already is creating.
2. As kops (and the kops HTTP API) would evolve we could start to see a need for other pods (IE: etcd to store state) building the service into a k8s cluster now allows us to grow and use other tools if we desire.
3. It allows for the user to start with 1 cluster and scale from there. A new user to kubernetes could deploy a cluster with the kops CLI, and not even run kops as a pod in the cluster at first. They can then scale out from there.

Running a standalone server in my mind is obviously a huge part of this design. I think the standalone server would be a first step, and the containerized approach would naturally follow. The user in theory could use **both** kops as a pod, and kops as a standalone server.

I think you hit the nail on the head with the evolution of `kops` to a thin API client. The only concern is we would need a way to elegantly handle **kops cli** vs **kops thin api client** we still need to support both. Maybe two commands? Maybe a flag?

**Comment by chrislovecnm** [comment]
So when we move to http deployment we are gonna have to think about state. We are gonna need a datastore, because we need to handle a use case when kops is upgrading a cluster, and gets shutdown and moved to another node. This is gonna be fun!

**Comment by chrislovecnm** [comment]
Heck I am wondering if it easier to launch a job now to upgrade cluster... Deep thoughts.

**Comment by kris-nova** [comment]
> We are gonna need a datastore, because we need to handle a use case when kops is upgrading a cluster, and gets shutdown and moved to another node

How does *etcd* not solve this? I guess I am confused what we would be missing in the upgrade scenario... also if this will be useful to another issue - can we point them together please? 

@chrislovecnm - obviously this is in response to your comments
