### ISSUE TITLE
update livenessProbe for api server

### ISSUE THREAD

**Issue by y-batsianouski** [kubernetes/kops#6331]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Hello!

Is it possible to manage /etc/kubernetes/manifests/kube-apiserver.manifest via cluster specification? We need to update livenessProbe  because default values isn't allows to start apiserver with "MutatingAdmissionWebhook" enabled on our clusters and currently we use user data script with sed for that.
Thank you!

**2. Feel free to provide a design supporting your feature request.**

Add possibility to define/patch parts of manifests of system kubernetes components.

**Comment by dobesv** [comment]
Could you describe the problem with `MutatingAdmissionHook` and what it has to do with the `livenessProbe` ?  Does it just make `apiserver` start too slowly?

**Comment by y-batsianouski** [comment]
@dobesv yes, exactly. It just make `apiserver` start too slowly.
