### ISSUE TITLE
metric-server and prometheus-operator v.0.26.0 addons conflicts with same APIService name

### ISSUE THREAD

**Issue by bzon** [kubernetes/kops#6335]
Please see https://github.com/kubernetes/kops/blob/0e323cc8967e09af5f91b696122a228ed7a64391/addons/metrics-server/v1.8.x.yaml#L86-L94 and https://github.com/kubernetes/kops/blob/0e323cc8967e09af5f91b696122a228ed7a64391/addons/prometheus-operator/v0.26.0.yaml#L14539-L14551 

kubectl applying both overwrites each APIService.

**Comment by dragosrosculete** [comment]
Is there any solution to this ?

**Comment by olemarkus** [comment]
I don't think any of these addons are well maintained. 
The metrics-server addon is also deprecated in kops 1.19 in favour of a maintained in-cluster addon.
