### ISSUE TITLE
kops update cluster with Terraform output doesn't update AMI in LC for ASG

### ISSUE THREAD

**Issue by nitrogear** [kubernetes/kops#6336]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
kops version: Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
(set kubernetesVersion: 1.11.6 from 1.10.12)
kops edit cluster
kops update cluster --out=./ --target=terraform
terraform plan
terraform apply
kops rolling-update cluster

**5. What happened after the commands executed?**
Launch configuration for autoscaling groups is updated, but AMI images are from old version kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17

**6. What did you expect to happen?**
Launch configuration is updated to use AMI kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17

**9. Anything else do we need to know?**
When upgrade finished kops upgrade still shows:
ITEM				PROPERTY	OLD							NEW
InstanceGroup/bastions		Image		kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17	kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
InstanceGroup/master-us-east-1a	Image		kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17	kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
InstanceGroup/master-us-east-1b	Image		kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17	kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
InstanceGroup/master-us-east-1c	Image		kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17	kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
InstanceGroup/nodes		Image		kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17	kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17

**Comment by shamil** [comment]
I guess you need to update images in the node groups before updating the cluster

**Comment by schollii** [comment]
@shamil Thanks, but this is not really a solution: we need a way of knowing which image file to use. The `kops create cluster` figures it out, so the functionality is already in the code. I've seen in another issue one person has an empty S3 bucket so they can use `kops create cluster` repeatedly, all that's needed is to edit one parameter in the resulting yaml file. Then `kops replace ...` would be sufficient. In any case this is a hack, although not as bad as looking up the image in the https://github.com/kubernetes/kops/blob/master/channels/stable file for the AMI. 

Note also we are trying to edit the yaml programmatically (using Python and/or sed), so even if we find re-invent the wheel to determine which AMI to use for the major/minor version of kops we want to use, running a `kops edit ig ...` command is a manual step that we would rather avoid. We would need something like `kops set ig ...` but the "set ig" command does not exist! 

I think the main issue here is that the k8s version -> AMI image file mapping is already in kops (specifically in `kops create cluster`), so there should be a way of changing spec.kubernetesVersion and have kops propagate the consequence of this to other items (like the IG).

**Comment by nitrogear** [comment]
@shamil I believe kops should take about that, because it does it if you run kops upgrade.
So I presume same behaviour should be if you use terraform

**Comment by rifelpet** [comment]
Have you tried just removing the `image:` field from the InstanceGroup spec? I believe Kops will populate the field itself with the "best" choice if it isn't set.

**Comment by nitrogear** [comment]
@rifelpet thank you, it worked. I removed image name from local `kops_cluster`.yaml, updated configuration on s3 with `kops replace -f kops_cluster.yaml` and after I run `kops update cluster --target=terraform` AMI image in LC for ASG was updated.
However it's still looks like a workaround rather than a solid solution. Also official documentation states that no other steps required to upgrade k8s cluster using terraform
https://github.com/kubernetes/kops/blob/master/docs/upgrade.md#terraform-users

**Comment by schollii** [comment]
Agreed this is only a workaround and at very least that page needs to list it. Better would be for kops to do automatically when spec.kubernetesVersion changes in any way via:
- kops edit
- kops set
- a new way to regenerate a yaml file (most intuitive options likely `kops create --override cluster ...` and `kops update --override cluster ...`)

**Comment by angegar** [comment]
I have the same issue, i modified the image in the manifest file then run apply then try update but nothing changed. I fear i will not be able to manage the AMI version with code but i will have to do it manually with the cli.

Why the spec.image field is not used ? Is it a bug ?
