### ISSUE TITLE
Error removing cluster for state store

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#634]
After deploying a new cluster and trying to delete, showing an error for an unknown file.

```
F1011 16:42:50.294185       6 delete_cluster.go:33] error removing cluster from state store: refusing to delete: unknown file found: s3://oscar-ai-k8s-dev/k8s-02.dev.aws-us-west-2.datapipe.io/addons/bootstrap-channel.yaml
```

With kops command

```
dkops delete cluster --state s3://oscar-ai-k8s-dev --name k8s-02.dev.aws-us-west-2.datapipe.io —yes
```

**Comment by kris-nova** [comment]
CC @chrislovecnm

**Comment by chrislovecnm** [comment]
This was s3 being pissy, not kops. The error message was odd, so I will keep it open.

**Comment by kris-nova** [comment]
If this is not relevant we should re-open another issue around the new problem.. yeah?

**Comment by alok87** [comment]
@chrislovecnm @kris-nova i am also getting this `kops 1.7.0`

**Comment by alok87** [comment]
Ok got it. This issue is not an issue after all. It happens when a incorrect `configBase` is defined in your cluster configuration. Fixing that will fix this issue.

**Comment by masterjeb** [comment]
@alok87 

So what is the right configBase? The entry in the file I created it with is `s3://blah-test-kops/`, and the command I ran was 
`kops delete cluster --name=k8s.blah-test.company.org --state=s3://blah-test-kops/ --yes` and I still get 
`error removing cluster from state store: refusing to delete: unknown file found: s3://blah-test-kops/k8s.blah-test.company.org/config`

What was your incorrect configuration, and what did you update it to?

**Comment by jbussdieker** [comment]
For anyone that finds this: configBase is not the same as `KOPS_STATE_STORE`

`configBase = $KOPS_STATE_STORE/$NAME`
