### ISSUE TITLE
Support additional kubelet flags in componentconfig 

### ISSUE THREAD

**Issue by silveryfu** [kubernetes/kops#6356]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Some kubelet flags listed here: 

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

..are seemingly not supported by kops: 

https://github.com/kubernetes/kops/blob/f5ce011fa036034e8b40d0dc94bc5bfc2419bc56/pkg/apis/kops/componentconfig.go

We found some are useful, e.g., --housekeeping-interval.

**2. Feel free to provide a design supporting your feature request.**

**Comment by nareshku** [comment]
good explanation about performance improvements with `--housekeeping-interval` option enabled.
https://github.com/kubernetes/kubernetes/issues/18044

**Comment by silveryfu** [comment]
@nareshku Are you suggesting that the decision of "having this flag enabled by default" should be made by kops and for all kops users? Excuse me but did you read this issue carefully?? :)

**Comment by CarpathianUA** [comment]
It will be useful to have the ability to configure a kubelet's housekeeping.

**Comment by integrii** [comment]
We have been having issues with Docker crashing due to [PLEG errors](https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.2.0/troubleshoot/docker_pods_overload.html).  The suggested mitigation is to increase the housekeeping interval described here.  Shame that this feature is not part of kops!

**Comment by jsonmp-k8** [comment]
Can this be enabled for the kubelet?

**Comment by rifelpet** [comment]
/reopen
This seems pretty straight forward and would be a good candidate for #9920
