### ISSUE TITLE
Provide way to create instance after delete in rolling update if ASG does not exist

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#6372]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I would like to call `CreateInstance` after `DeleteInstance` is called here https://github.com/kubernetes/kops/blob/master/pkg/instancegroups/instancegroups.go#L192 My goal here is to provide way to use rolling-update command in openstack which does not support ASGs. The kops rolling-update logic is heavily dependent to ASGs for instance in AWS. Rolling update will just delete the instance, and ASG will scale up nodes with newest configuration. This feature does not exist in all clouds.

**2. Feel free to provide a design supporting your feature request.**
I have tried to find way to do this. However, the most difficult part is how to provide startup scripts for new instance. I am thinking to add https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloud.go#L37 `CreateInstance` here. It should not affect providers which do have ASG, only those ones which do not have.

Is there sense? How we can pass userdata to createinstance? Or could we somehow call tasks from instancegroups.go?

**Comment by justinsb** [comment]
We discussed this a bit on slack.  I think it would be great to try to integrate the cluster-api for this - we're within striking distance.

But masters would still be a problem, so it might also just be easier to recreate instances directly... I'll poke around the code!
