### ISSUE TITLE
admission control plugins limited to 11?

### ISSUE THREAD

**Issue by ashic** [kubernetes/kops#6393]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.11.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.10.12

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

We have a cluster that's been through a few versions of kubernetes. We noticed that after the upgrade to 1.10.12 from 1.9.x, PodPresets stopped working. Upon investigating, we see that kops edit cluster shows the PodPreset admission control plugin, but kubectl get pod -oyaml doesn't show it in the api server pods. Upon further investigation, I see that switching the order of the admission control plugins in kops edit cluster is resulting in the last one getting cut. We specify the following 12 plugins:

And whichever is the last one, is not showing up in kubectl get pod -oyaml for the api server(s). 

**5. What happened after the commands executed?**
After applying the changes, the last admission control plugin isn't applying.

**6. What did you expect to happen?**
I expected all 12 to be in the api server's manifest.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-04-18T13:43:57Z
  name: abcd
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["cloudwatch:GetMetricData", "cloudwatch:GetMetricStatistics", "cloudwatch:ListMetrics"],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Company: MYCOMPANY
    CostCenter: "1234"
    DatadogMonitoringCostAccepted: "Yes"
    Environment: DEV
    Service: FOO
    User: THEDONALD
  cloudProvider: aws
  configBase: s3://bucket/cluster
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  iam:
    legacy: true
  kubeAPIServer:
    address: 127.0.0.1
    admissionControl:
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - PodPreset
    - ResourceQuota
    - PersistentVolumeLabel
    allowPrivileged: true
    anonymousAuth: false
    apiServerCount: 3
    authorizationMode: RBAC
    cloudProvider: aws
    etcdServers:
    - http://127.0.0.1:4001
    etcdServersOverrides:
    - /events#http://127.0.0.1:4002
    image: gcr.io/google_containers/kube-apiserver:v1.10.10
    insecurePort: 8080
    kubeletPreferredAddressTypes:
    - InternalIP
    - Hostname
    - ExternalIP
    logLevel: 2
    runtimeConfig:
      settings.k8s.io/v1alpha1: "true"
    securePort: 443
    serviceClusterIPRange: 100.64.0.0/13
    storageBackend: etcd2
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.12
  masterInternalName: api.internal.v2.mydomain.com
  masterPublicName: api.v2.mydomain.com
  networkCIDR: 10.10.10.0/23
  networkID: vpc-abcd1234
  networking:
    canal: {}
  nonMasqueradeCIDR: a.a.a.a/10
  sshAccess:
  - 10.0.0.0/8
  subnets:
  - cidr: c.i.d.r/26
    id: subnet-1234
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: c.i.d.r/26
    id: subnet-2345
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: c.i.d.r/26
    id: subnet-3456
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: c.i.d.r/26
    id: subnet-4567
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: c.i.d.r/26
    id: subnet-5678
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: c.i.d.r/26
    id: subnet-6789
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

I think steps are clearer:

1. Create cluster with the admission control specified above.
2. Check an apiServer node's admission control plugins. 
3. Edit cluster and reorder the plugins so a different one is at the bottom of the list. Apply. 
4. Check the apiServer's plugins. Whichever's bottom is cut.

**9. Anything else do we need to know?**
I haven't yet verified if I have 13 plugins if two get cut or not.

**Comment by ashic** [comment]
Right... so it seems to be limited to 11 for me, not just cutting the last one. For the following in the cluster spec

```
  kubeAPIServer:
    address: 127.0.0.1
    admissionControl:
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - PodPreset
    - ResourceQuota
    - PersistentVolumeLabel
    - NodeRestriction
    - PodTolerationRestriction
    allowPrivileged: true

```
I get the following admission controllers on the api-server:

```
--enable-admission-plugins=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,PodPreset,ResourceQuota,PersistentVolumeLabel
```

To save some parsing, that's 13 admission controllers in the spec, and 11 in the pod setting.

**Comment by amartorelli** [comment]
I think I had the same problem but reading the code I've found out that `admissionControl` is now deprecated.
Try using `enableAdmissionPlugins`, it worked for me.

**Comment by ashic** [comment]
Possibly have an update on this. I did the following:

1. Created a new 1.10+ cluster with kops. Checking the s3 state, it has 11 enableAdmissionPlugins entries. 
2. I added 13 admissionControl entries. If I do an edit cluster, I only see the 13 admissionControl entries. However, the state file in s3 as 13 admissionControl entries AND 11 enableAdmissionPlugins entries. When applying, it applies the FIRST 11 admissionControl entries. 
3. It appears if there's both admissionControl and enableAdmissionPlugins in the s3 state (which would be the case for a cluster upgraded from 1.9), edit cluster only shows the admissionControl entries in the yaml, but the s3 state has both. AND it applies the first length(enableAdmissionPlugins) number of admissionControl entries to the api server pods. 

I'm doing some more investigation on this today, and hopefully will be able to pinpoint the exact issue. I'll try:

1. Using both admissionControl and enableAdmissionPlugins with the same entries. 
2. Change enableAdmissionPlugins to (say) 8, and see if only the first 8 of admissionControl get applied. 

I'll report back my findings. 

@amartorelli if my theory is correct, just specifying enableAdmissionPlugins may not work, as admissionControl would have been in the s3 state from the 1.9 days of the cluster. Will need to see if it gets removed if I remove the node in edit cluster.

**Comment by ashic** [comment]
Update:

Having a 1.9 cluster with admissionControl entries, kops edit cluster-ing to 1.10 causes both admissionControl and a default enableAdmissionPlugin sections. kops edit cluister-ing that and changing admissionControl to enableAdmissionPlugin causes the s3 state to only have an enableAdmissionPlugin section, which rolls out correctly to the api servers. 

I've also tried the following:

Taken an 1.9 cluster with 13 admissionControl plugins. Updated it to 1.10, but added both admissionControl section (13 entries), and the default enableAdmissionPlugins entries (11). I then removed three enableAdmissionAdmissionPlugins entries. When applied, the apiServers for 8 top entries in admissionControl. 

So this is how it's working:

* If a cluster's spec has admissionControl entries in 1.9, those will get put into 1.10+ clusters.
* If a 1.9 cluster is upgraded to 1.10, kops WILL put in a default enableAdmissionPlugins entry with 11 default entries. 
* If both admissionControl and enableAdmissionPlugins are present, then the first length(enableAdmissionPlugins) entries from admissionControl will be applied to the apiServer. 


The solution is to use kops edit cluster, remove admissionControl, create an enableAdmissionPlugins section and apply the entries you want. Then a rolling upgrade to the masters will fix the apiServers and give them the correction admission plugins.

**Comment by ashic** [comment]
Ok.... got to the bottom of this. Thanks to @laithalissa for tracking this down. 

The offending code is https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/kube_apiserver.go#L337

```
copy(c.EnableAdmissionPlugins, c.AdmissionControl)
```

From the docs of copy (https://golang.org/pkg/builtin/#copy):

```
func copy(dst, src []Type) int

The copy built-in function copies elements from a source slice into a destination slice. (As a special case, it also will copy bytes from a string to a slice of bytes.) The source and destination may overlap. Copy returns the number of elements copied, which will be the minimum of len(src) and len(dst).
```

In our case, our destination is c.EnableAdmissionPlugins and the source is c.AdmissionControl. Since it's an upgraded cluster, c.EnableAdmissionPlugins has 11 entries, and our c.AdmissionControl has 13. It's keeping the minimum of the two lengths, and that's why the last two are getting culled.

**Comment by vainu-arto** [comment]
/remove-lifecycle stale

This bug is still confirmed to exist in the current codebase and has been tracked down to the actual line of code where the bug is. This should definitely be fixed instead of forgotten.

**Comment by laithalissa** [comment]
I was willing to do a patch, but I'm not super experienced in go, and I struggled to setup/run tests to verify my change.
