### ISSUE TITLE
Why not ELB Health Check for master ASGs ?

### ISSUE THREAD

**Issue by kalium99** [kubernetes/kops#6398]
It seems that my kops installation is using EC2 Health Checks for the master ASGs. 
I noticed this because the ELB was showing one of the master's (I have a 3 AZ HA setup) as being OutOfService, but the ASG was not terminating and creating a new one.

Just wondering if there's a good reason why the ASGs aren't set to use ELB Health Checks as opposed to EC2 ones ?

I'm using kops 1.10 (although I think I initially used 1.8 to create the cluster).

**Comment by mapdegree** [comment]
We are reviewing out ELB health checks as well soon after an availability zone failed. 

We have been advised by AWS not to rely on network when it comes to AZ failures and consider staying away from basic health checks (EC2 and LB health check). 

I would be very careful to impose any rules of termination on Masters holding ETCD for any outage that might occur. In production, if an outage is for hours and it is not a full service outage, you could get your Kubernetes ETCD into a mess. 

Having ETCD outside masters and tweaking ELB is what we will investigate in close future.

**Comment by kalium99** [comment]
Just for the record, the problem here is that the API may become un-responsive for whatever reason on the master (say, an OOM). 

If we could use an ELB healthcheck that checked the API (which is, after all what it is responsible for proxying) and then be able to cycle that machine out without any fear of repercussions with etcd (as per the point from @mapdegree) then that would seemingly add another layer of robustness to the API. I've personally seen all 3 of my masters go into 'OutOfService' and manual intervention is required to get the ELB serving traffic again.

This feature (here)[https://github.com/kubernetes/kops/issues/2216] would go someway to solving it (i.e having the option for a non-stacked etcd)
