### ISSUE TITLE
Can we clean up kops issues?

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#640]
I know this seems counter-productive to create an issue about cleaning up issues..

But we are now in 1.4.1 - Can we start to deprecate / consolidate any older issues that may have since been fixed / are no longer relevant? 

Maybe have a deprecation process? Or a `legacy` label?

Thoughts? @chrislovecnm @justinsb

**Comment by chrislovecnm** [comment]
Actually it doesn't. I would like to go through and pull everything back into backlog and start fresh. There is kanban for planning now in GitHub, use that and motor.

**Comment by kris-nova** [comment]
I think we should probably have someone own this process, and we should take all measures to preserve all data. *e.g. Nothing should be deleted, only disabled*

This also is a great topic to bring up at the next meeting..? Do we have those?

Issues will still be the source of generating work IMHO, I just want a dense and meaningful set of issues. 

Right?

**Comment by chrislovecnm** [comment]
Is this done?
