### ISSUE TITLE
Kops documentation improvements

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#641]
It looks like kops has evolved quite a bit since it's creation..

Wondering what the powers that be think about giving the README a once over in order to simplify things?

I think we can gain quite a bit from the community in demonstrating a simple and elegant explanation of kops.. Less is more in this case right?

I think we can defer a lot of the current README into specialized docs in the `/docs` directory.

**Comment by kris-nova** [comment]
Also I think we can do better than `kops deployment` for a repo one liner.. yeah?

**Comment by chrislovecnm** [comment]
We need to get @justinsb as an admin, because neither of us can edit that

**Comment by chrislovecnm** [comment]
Documentation improvements needed:

- Developer Guide
- CHANGES.md is out of date
- CONTRIBUTING
- README needs some TLC
- code of conduct?
- General refactor of docs directory

**Comment by chrislovecnm** [comment]
Now have a documentation tag ... yay

**Comment by chrislovecnm** [comment]
`kops get secrets kube --type secret -oplaintext` is deep in the droves of documentation.  Consolidate a cheat sheet / quick start guide
