### ISSUE TITLE
Cannot find etcd data directory

### ISSUE THREAD

**Issue by mapdegree** [kubernetes/kops#6412]
Hi,

When I logged onto the CoreOS on the Kubernetes cluster (version 1.11.7) using KOPS 1.11.0 on AWS I could not find any data files on the typical /var/lib/etcd directory. 

I searched the whole /var directory and could not find where the etcd data files are. 

My etcd 2.2.1 Docker container is running and Kubernetes cluster is healthy, just cannot find the etcd data dir I can backup up. 

Any ideas where it is? 

Thanks, 
Dejan

**Comment by zetaab** [comment]
the data directory is EBS volume itself, if you are running in amazon you could take snapshot from that volume. (I think it might be taking those automatically?)

You can list volumes in master `df -h` and I think you should be able to see that etcd volume if its running healthy

**Comment by mapdegree** [comment]
Would you know the name of the mounted file system? I will search again in the meantime.

**Comment by mitpwd** [comment]
I followed up after @mapdegree and could find the followin issue after installing etc-manager:

`W0129 16:12:17.422146    2355 mounter.go:79] unable to mount master volume: "device already mounted at /rootfs/mnt/master-vol-0a1402dc001c18295, but is /dev/nvme2n1 and we want /rootfs/dev/xvdu or /dev/xvdu"
I0129 16:12:17.422160    2355 boot.go:49] waiting for volumes`

df -hP returns
/dev/nvme1n1      20G  111M   19G   1% /mnt/master-vol-0e0ce49acd2d8b9b2
/dev/nvme2n1      20G  187M   19G   1% /mnt/master-vol-0a1402dc001c18295

We are losing confidence that it is possible to upgrade etcd v2 to 3.

**Comment by juris** [comment]
@mitpwd looks like you are using m5, c5, t3 or any other nitro-based instances. Try using something old fashioned t2, c4 or m4 types #4813.

In any case, I had the same issues with etcd-manager. Using t2 instance type solved volume mounting, but then I faced a different kind of fun #6376.

**Comment by mapdegree** [comment]
Issue resolved
