### ISSUE TITLE
scaling down the instance group does not have any effect

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#6417]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.6

**3. What cloud provider are you using?**

openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

- scale instancegroup up, for instance `kops edit ig --name clustername nodes` edit minsize to 5
- run `kops update cluster clustername --yes`

After this you should be able to see 5 nodes, then downscale
- scale instancegroup down, for instance `kops edit ig --name clustername nodes` edit minsize to 1
- run `kops update cluster clustername --yes`

**5. What happened after the commands executed?**

Machines are not scaled down

**6. What did you expect to happen?**

I except that if I specify minsize to one and run update cluster, it should remove machines that is not needed.

/sig openstack
/kind bug

**Comment by zetaab** [comment]
I am thinking that should we check here https://github.com/kubernetes/kops/blob/master/pkg/model/openstackmodel/servergroup.go#L74 how many servers do we have in openstack servergroup? if there is Members more than MinSize it should delete instances? Create new deleteinstance task or how it should work?

**Comment by drekle** [comment]
https://github.com/kubernetes/kops/pull/6385 is useful here as you've implemented delete instance.  I believe the existing server group task should find the server group, with members which represent the UUID of a server, and can be removed only if they are over `MaxSize` imo.  I believe and autoscaler should do any logic determining whether or not the instances over `MinSize` are needed or not, as it has greater visibility about the pods in a cluster.

Ill try to pick this up if we can get the aws pull test to pass.

**Comment by drekle** [comment]
@zetaab I believe this is resolved?
