### ISSUE TITLE
kube-scheduler and kube-controllermanager not coming up in 1.4.1 

### ISSUE THREAD

**Issue by praoreo** [kubernetes/kops#642]
Hi,

I am trying to upgrade my lab from kubernetes 1.3.6 to 1.4.1. After copying the latest kube-scheduler and kube-controllermanager binary I am not able to start the process as it says "unable to build config from flags: invalid configuration: no configuration has been provided"

```
root# /opt/bin/kube-scheduler --logtostderr=true --leader-elect=true --kubeconfig=/var/lib/kube-scheduler/kubeconfig/config
E1013 12:47:37.395646   39876 server.go:79] unable to build config from flags: invalid configuration: no configuration has been provided
root@tbserver11:/home/tbserver11/Kubernetes_1.4.1/kubernetes/server/bin#

root@tbserver11:/home/tbserver11/Kubernetes_1.4.1/kubernetes/server/bin# /opt/bin/kube-controller-manager --logtostderr=true --leader-elect=true --kubeconfig=/var/lib/kube-controller-manager/config --node-monitor-period=1s --node-monitor-grace-period=5s --pod-eviction-timeout=50ms
invalid configuration: no configuration has been provided

```

I have a valid kubeconfig file at "/var/lib/kube-scheduler/kubeconfig/config" and "/var/lib/kube-controller-manager/config". Also, the same was working fine using 1.3.6 binaries. 

Following commands were used to generate the kubeconfig 
```

./kubectl config set-cluster mykubecluster --server=https://<IP>:8081 --insecure-skip-tls-verify=true
 ./kubectl config unset clusters
 ./kubectl config set-cluster mykubecluster --certificate-authority=<Path>/ca.crt --embed-certs=true --server=https:// <IP>:8081
```

Is this a known issue in latest release? Is their any work around for the same?

**Comment by praoreo** [comment]
@justinsb 
Is this issue same as https://github.com/kubernetes/kops/issues/463
I am facing same issue while starting kube-controller-manager as well.

**Comment by justinsb** [comment]
@praoreo this doesn't like you installed using kops?   If so I would suggest opening an issue in https://github.com/kubernetes/kubernetes

Going to close, but if this is kops, please reopen
