### ISSUE TITLE
latest ubuntu amis cause kops cluster update to error on AutoscalingLaunchConfiguration: InvalidParameter

### ISSUE THREAD

**Issue by hollowimage** [kubernetes/kops#6428]
Seems the latest ubuntu amis are causing issues with kops and autoscaling group updates on `kops update cluster`
Last known working version:
`099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180912`

versions i tried:
`099720109477/ubuntu/images/ubuntu-xenial-16.04-amd64-server-20181218`
`099720109477/ubuntu/images/ubuntu-xenial-16.04-amd64-server-20190122.1`

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update cluster --yes

**5. What happened after the commands executed?**
```
error creating AutoscalingLaunchConfiguration: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, CreateLaunchConfigurationInput.BlockDeviceMappings[0].DeviceName.
```

**6. What did you expect to happen?**
kops cluster gets updated

**Comment by hollowimage** [comment]
i guess the difference here is before i tried using `hvm-ssd` amis -- maybe im missing something here, but what's the difference? 

If there are constraints one way or another, i think https://github.com/kubernetes/kops/blob/master/docs/images.md should clarify the requirements a bit.

**Comment by PaulVanStaden** [comment]
I am getting the same error when trying to use those latest images. What details should I submit to aid the investigation?
