### ISSUE TITLE
Enable Travis CI builds

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#643]
This is moving https://github.com/kubernetes/kubernetes/issues/34737 over to the kops repo.

@spxtr we are not able to enable travisci builds on this repo. We do not see the admin tab in GitHub, and cannot configure webhooks for the project. Can someone assist or grant us the Admin Permissions?  Who is your backup on this repo as an admin?  Thanks a ton!

Thanks @ixdy for your help.

**Comment by spxtr** [comment]
I added it.

**Comment by chrislovecnm** [comment]
@spxtr ~ much thanks Joe.  Who is your backup for all things admin?

**Comment by spxtr** [comment]
https://github.com/kubernetes/kops/pull/638 looks like it's working. Anyone who is an owner of the kubernetes org can do this, but you should get a couple admins for this repo specifically.

**Comment by ixdy** [comment]
To elaborate on what @spxtr said:
* the list of owners in the kubernetes org can be found [here].(https://github.com/orgs/kubernetes/people?utf8=%E2%9C%93&query=%20role%3Aowner)
* several of the repos have [-admin teams](https://github.com/orgs/kubernetes/teams?utf8=%E2%9C%93&query=admin) which give admin access to those repos. I'm not sure what the policy is for creating these teams.

**Comment by chrislovecnm** [comment]
Let me close this out and open another issue for admin stuff

**Comment by chrislovecnm** [comment]
closing thanks @spxtr
