### ISSUE TITLE
unknown flag: --override

### ISSUE THREAD

**Issue by bjethwan** [kubernetes/kops#6430]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

kubernetesVersion: 1.11.6

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create cluster 
http://docs.cilium.io/en/stable/kubernetes/install/kops

**5. What happened after the commands executed?**

unknown flag: --override

**6. What did you expect to happen?**
etcd version would have been set as given in the --override

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

[a-issue.zip](https://github.com/kubernetes/kops/files/2820553/a-issue.zip)

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I think it's a regression issue.

There's no other way to set the etcd version.

kops create cluster --help | grep etcd
      --encrypt-etcd-storage             Generate key in aws kms and use it for encrypt etcd volumes

$ kops create cluster --name hidden \
> --cloud=aws \
> --node-count=1 \
> --node-size=t2.medium \
> --master-size=t2.medium \
> --networking cilium \
> --vpc=hidden \
> --subnets=hidden \
> --zones="ap-south-1a" \
> --dns-zone=ap-south-1.bj-cloud.info \
> --state=hidden

Spec.EtcdClusters[0].Version: Invalid value: "2.2.1": minimal version required is 3.1.0

**Comment by scottbot34** [comment]
I ran into this as well. Try doing this first: 
`export KOPS_FEATURE_FLAGS=SpecOverrideFlag`

and then add this to your kops create parameters: 
`--override "cluster.spec.etcdClusters[*].version=3.1.11"`
