### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by NikTJ777** [kubernetes/kops#6435]
I need to provision *some* nodes in my cluster with large external disks (think database or similar).

If I create my cluster in AWS, I can add `volumes` and `volumeMounts` entries to the instanceGroup YAML.
- And presumably, if I create a special instanceGroup for just those nodes that should have the additional storage, then this approach is all I need.

However, I don't believe there is any equivalent support built in for GCE or Azure.

Q1: Is there any near-term work happening to support `volumes` and `volumeMounts` for GCE and Azure?

Failing that, I need to create some form of workaround either by adding `user_data` to one or more `YAML` files, or possibly generating `terraform` scripts and editing those.

Q2: Is there any way to modify the generated `YAML` files to cause `kops` to create additional persistent disks in GCE and Azure - and connect them to the node instances?
If so - then presumably I could use those features and then add `user_data` to `partition, format and mount` those disks.

Q3: If there is no way to do this  in the `YAML`, then I could try `kops --target terraform` and edit the terraform files.
From a quick scan of those, it seems it would be relatively simple to add the creation of the persistent disks to the `kubernetes.tf` terraform file - and presumably connect them to the correct nodes instances.
But what would be the best way to include instructions to `partition, format, and mount` those disks?

* should that be done with a script for terraform
* or would that be better included as `user_data` in a `YAML` file somewhere?

Q4: can I use a combination of `kops --dry-run` to create YAML *plus* `kops --target terraform` to generate terraform scripts; edit both, and then use `terraform` and/or `kops` (??) to provision the results using a combination of those generated files?

Is there any documentation on the interrelationships between `kops`, `gcloud`, kops `YAML` files and `terraform`?

**Comment by timothyclarke** [comment]
I'm not exactly sure what / how you're trying to achieve adding the storage.
An approach for I've taken for something similar was an instance group restricted to a single AZ, and then a storage class restricted to the same AZ. The storage class makes use of ebs, where a larger host volume will probably be lost when the instance is recycled (without additional config)

With per AZ instance group and storage class you can them either use them directly (and risk outage if that AZ goes down) or layer with something like ceph (or one of the many other storage solutions) to provide storage to the cluster as a whole.

**Comment by Sturgelose** [comment]
Isn't there any reason to load the volumes as, for example, EBS volumes instead of defining this in the instance groups?

I guess you should be able to create Stateful Sets, where you attach a volume to that pod. Using a Stateful Set allows you to always use the same k8s volume underneath even if you change between nodes. Otherwise, you would be forced to use always the same node.

In AWS you can use EBS volumnes, and in GCE/Azure I'm sure you can use other similar volumes.
