### ISSUE TITLE
Improve documentation for containerProxy and registryMirrors

### ISSUE THREAD

**Issue by zystem** [kubernetes/kops#6440]
In https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md there are two parameters
1) https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#containerproxy
2) https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#registrymirrors
regarding its documentation both to do the same - enable docker images caching.

The proposition is to add info about what is the difference between these parameters and preferred use cases there to use first and second.

**Comment by messiahUA** [comment]
stumbled on this and I agree this requires clarification...

**Comment by johngmyers** [comment]
https://kops.sigs.k8s.io/operations/asset-repository/#configuring-a-local-image-repository states

> They both do essentially the same thing, but `containerRegistry` avoids using / characters in the local image names.

What further clarification is needed?

**Comment by hakman** [comment]
> What further clarification is needed?

1. Mention ECR for containerRegistry
2. Add examples at the end for `get assets` with both proxy and registry.

**Comment by johngmyers** [comment]
And I thought `containerRegistry` was for docker.io. I'm not quite sure it's on us to document which registries don't like `/` characters.

**Comment by messiahUA** [comment]
> https://kops.sigs.k8s.io/operations/asset-repository/#configuring-a-local-image-repository states

this one covers only spec.assets, but there is also https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#registry-mirrors
