### ISSUE TITLE
Upgrading to kubernetes 1.11 with enableCustomMetrics failes

### ISSUE THREAD

**Issue by sciffer** [kubernetes/kops#6449]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.11.0 (git-2c2042465)
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.10.12
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops upgrade cluster --yes
kops update cluster --yes
kops rolling-update cluster --yes
**5. What happened after the commands executed?**
A master was emptied and brought down and a new master tried to start and failed(failing the whole deployment)
**6. What did you expect to happen?**
To just upgrade or at least let me know that I have to remove a flag due to it being deprecated(and blocking the upgrade till I do so)
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-12-21T17:10:41Z
  name: k8s.acme.io
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "sqs:*",
            "acm:DescribeCertificate",
            "acm:ListCertificates",
            "acm:GetCertificate",
            "ec2:AuthorizeSecurityGroupIngress",
            "ec2:CreateSecurityGroup",
            "ec2:CreateTags",
            "ec2:DeleteTags",
            "ec2:DeleteSecurityGroup",
            "ec2:DescribeAccountAttributes",
            "ec2:DescribeAddresses",
            "ec2:DescribeInstances",
            "ec2:DescribeInstanceStatus",
            "ec2:DescribeInternetGateways",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeSubnets",
            "ec2:DescribeTags",
            "ec2:DescribeVpcs",
            "ec2:ModifyInstanceAttribute",
            "ec2:ModifyNetworkInterfaceAttribute",
            "ec2:RevokeSecurityGroupIngress",
            "elasticloadbalancing:AddTags",
            "elasticloadbalancing:CreateListener",
            "elasticloadbalancing:CreateLoadBalancer",
            "elasticloadbalancing:CreateRule",
            "elasticloadbalancing:CreateTargetGroup",
            "elasticloadbalancing:DeleteListener",
            "elasticloadbalancing:DeleteLoadBalancer",
            "elasticloadbalancing:DeleteRule",
            "elasticloadbalancing:DeleteTargetGroup",
            "elasticloadbalancing:DeregisterTargets",
            "elasticloadbalancing:DescribeListeners",
            "elasticloadbalancing:DescribeLoadBalancers",
            "elasticloadbalancing:DescribeLoadBalancerAttributes",
            "elasticloadbalancing:DescribeRules",
            "elasticloadbalancing:DescribeSSLPolicies",
            "elasticloadbalancing:DescribeTags",
            "elasticloadbalancing:DescribeTargetGroups",
            "elasticloadbalancing:DescribeTargetGroupAttributes",
            "elasticloadbalancing:DescribeTargetHealth",
            "elasticloadbalancing:ModifyListener",
            "elasticloadbalancing:ModifyLoadBalancerAttributes",
            "elasticloadbalancing:ModifyRule",
            "elasticloadbalancing:ModifyTargetGroup",
            "elasticloadbalancing:ModifyTargetGroupAttributes",
            "elasticloadbalancing:RegisterTargets",
            "elasticloadbalancing:RemoveTags",
            "elasticloadbalancing:SetIpAddressType",
            "elasticloadbalancing:SetSecurityGroups",
            "elasticloadbalancing:SetSubnets",
            "elasticloadbalancing:SetWebACL",
            "iam:CreateServiceLinkedRole",
            "iam:GetServerCertificate",
            "iam:ListServerCertificates",
            "waf-regional:GetWebACLForResource",
            "waf-regional:GetWebACL",
            "waf-regional:AssociateWebACL",
            "waf-regional:DisassociateWebACL",
            "tag:GetResources",
            "tag:TagResources",
            "waf:GetWebACL"
          ],
          "Resource": ["*"]
        }
      ]
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    disableSecurityGroupIngress: true
  cloudProvider: aws
  configBase: s3://config.k8s.acme.io/k8s.acme.io
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1d
      name: d
    - instanceGroup: master-us-east-1e
      name: e
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1d
      name: d
    - instanceGroup: master-us-east-1e
      name: e
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: true
  kubeDNS:
    provider: CoreDNS
  kubelet:
    enableCustomMetrics: true
  kubernetesApiAccess:
  - x.y.z.n/16
  - x.y.z.2/32
  - x.y.z.1/32
  kubernetesVersion: 1.10.11
  masterInternalName: api.internal.k8s.acme.io
  masterPublicName: api.k8s.acme.io
  networkCIDR: x.0.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: x.y.0.0/16
  sshAccess:
  - x.y.z.2/32
  - x.y.z.1/32
  subnets:
  - cidr: x.x.n.0/24
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: x.x.z.0/24
    name: us-east-1c
    type: Public
    zone: us-east-1c
  - cidr: x.x.y.0/24
    name: us-east-1d
    type: Public
    zone: us-east-1d
  - cidr: x.x.x.0/24
    name: us-east-1e
    type: Public
    zone: us-east-1e
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
Not relevant as I found the problem, the logs showed that kubelet is failing to start due to the parameter --enableCustomMetrics true , which seems to be a deprecated parameter - therefore has to be removed
**9. Anything else do we need to know?**
It's all mentioned above, such issues should not occur and as part of the upgrade process of kops, kops must verify that non of the used featured have been deprecated or renamed to avoid failing the upgrade process.

**Comment by rltvty** [comment]
Per this: https://github.com/kubernetes/kubernetes/pull/52706 this flag hasn't been used anywhere in code for quite some time.  But recently the kubelet dropped support for it completely.

**Comment by jurgenweber** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#removed-deprecations

**Comment by myspotontheweb** [comment]
The kops HPA docs [were updated](https://github.com/kubernetes/kops/commit/e9fecb2116ac5690728e37008cd807df899bc22b#diff-5f94e11a63f599ff3bfc3b2720302839) to state that ```--enable-custom-metrics``` flag [was removed in v1.11](https://github.com/kubernetes/kops/blob/master/docs/horizontal_pod_autoscaling.md#support-for-custom-metrics)

**Comment by sciffer** [comment]
Guys, I saw that it got deprecated after trying to upgrade and failed, there was no way to know that this will hang the upgrade beyond searching the logs of the different components(till I found the message).
We should fix that so that other users will avoid the need to go through what I did.
Similar to the way you alert users that Anonymous authentication is enabled, you should do the same with the deprecated feature if it is enabled (when upgrading to 1.11+) and block the upgrade or remove the feature.
The feature was set by me previously in older config using the kops cluster config (@myspotontheweb not sure what you mean about how kops can detect it).
