### ISSUE TITLE
Unable to delete AWS Security Groups

### ISSUE THREAD

**Issue by eroji** [kubernetes/kops#6454]
I have an old Kubernetes cluster that had been created with kops 1.8.1 in AWS which I am now working on removing. However, I had lost the config for kops to destroy the cluster so I went ahead to manually remove them out of AWS Console. However, there are 4 security groups that kops had created which refuses to delete because there is some sort of dependency existing that for the life of me I cannot figure out. Attempting to remove these groups using AWS CLI also results in the same error.

From EC2 section
![image](https://user-images.githubusercontent.com/13228540/52441151-cc44b900-2ad4-11e9-8c14-0dd147296f76.png)

From VPC section
![image](https://user-images.githubusercontent.com/13228540/52441217-f26a5900-2ad4-11e9-8712-1733dee81a36.png)

From AWS CLI
`An error occurred (DependencyViolation) when calling the DeleteSecurityGroup operation: resource sg-38692047 has a dependent object`

**Comment by rifelpet** [comment]
You can paste the security group IDs in the the search bar of the Network Interfaces page in the EC2 section to see which resources are still using the security groups. Once those resources are deleted, the security groups should be deletable as well.

**Comment by eroji** [comment]
I had deleted the network interfaces already. If I go search for the groups again in the network interfaces page, nothing shows up.

![image](https://user-images.githubusercontent.com/13228540/52451349-73384d80-2af3-11e9-8de5-f3d8c513c34f.png)

**Comment by rifelpet** [comment]
Looking at the EC2 error message, it sounds like you have rules in your security groups that reference each other. Try clearing out each groups’ rules and then deleting them again.

This shouldn’t be the normal behavior though, do you know if you modified the security group rules after Kops created them?

**Comment by eroji** [comment]
> Looking at the EC2 error message, it sounds like you have rules in your security groups that reference each other. Try clearing out each groups’ rules and then deleting them again.
> 
> This shouldn’t be the normal behavior though, do you know if you modified the security group rules after Kops created them?

Looks like that did the trick. Thank you. I honestly am not sure why they were referencing each other. I don't recall ever editing them manually.
