### ISSUE TITLE
pull-kops-e2e-kubernetes-aws test broken

### ISSUE THREAD

**Issue by integrii** [kubernetes/kops#6456]
Looks like _every_ PR is failing on the `pull-kops-e2e-kubernetes-aws` test.  Even things that just change an `OWNERS` file like this PR:  https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kops/6450/pull-kops-e2e-kubernetes-aws/8610/

The error in this particular case is below.  Can someone who has access to these pipeline creds and the AWS account check it out?

```
error reading cluster configuration "e2e-8610-ff1eb.test-cncf-aws.k8s.io": error reading s3://k8s-kops-prow/e2e-8610-ff1eb.test-cncf-aws.k8s.io/config: Unable to list AWS regions: AuthFailure: AWS was not able to validate the provided access credentials
```

**Comment by integrii** [comment]
![image](https://user-images.githubusercontent.com/98695/52509554-7d1e8700-2bad-11e9-93d3-4f1d26fe1976.png)

**Comment by justinsb** [comment]
Yes, and to use more words than I did on slack - there was just a mixup, and I understand that AWS has now added more credits, and the account is just being re-enabled now.  We could switch our tests to just run hourly or similar - we do have test signal via our non-integration tests...

**Comment by integrii** [comment]
Just tried this today on a PR I have open and hit this.  Related?

`W0212 20:42:48.912] error populating configuration: error querying for valid AZs in "eu-west-2" - verify your AWS credentials.  Error: OptInRequired: You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe.`
