### ISSUE TITLE
k8s-1.4 AWS AMI image issues with missing linux headers

### ISSUE THREAD

**Issue by bassco** [kubernetes/kops#646]
We recently upgraded our cluster from v1.3.5 to v.1.4.0 which changed the default AMI version from 8s-1.3-debian-jessie-amd64-hvm-ebs-2016-06-18 - ami-aa029cd9, to use k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-09-30 - ami-d35a1ca0

This caused the following fallout:

The logging from our containers to https://www.papertrailapp.com/ stopped working.

Work around: Add "--poll" cli option to the remote_syslog2 logging script in our containers using papertrail.

Additionally, our sysdig agent privileged containers refused to start due to the lack of kernel headers on the new AMI.

So, the questions are, why the change in behaviour that is breaking backward compatibility of existing stacks?

Why the change in behaviour with inotify?
Removal of kernel headers?

There maybe other issues to, but these are what we have come across at the moment.

**Comment by chrislovecnm** [comment]
@bassco thanks for letting us know.  The new ami is with the LST kernel, which resolved a docker issue, and we probably need to include the kernel headers as well.

How is `inotify` acting differently?  Is this a K8s issue or a ami issue?

**Comment by bassco** [comment]
@chrislovecnm I think the inotify is a by-product of the fs driver changing from aufs to overlayfs or devicemapper. Aufs is no longer supported in the 4.4.23 kernel. The only other notify difference between the older 3.16 and 4.4.23-k8s kernel is that # CONFIG_FANOTIFY_ACCESS_PERMISSIONS is not set in the new kernel.

I still have to research what this kernel option is for as it seems to be very similar to inotify behaviour.

I have been chatting to @justinsb on the kubernetes-dev slack channel. I will create a pull request on the kopeio/kubernetes-kernel repo and reference this issue as fixed from there.

**Comment by chrislovecnm** [comment]
@bassco thanks! Please cc' me on the issue, as we need to update our kernel on our ami as well.

**Comment by bassco** [comment]
@chrislovecnm the CONFIG_FANOTIFY_ACCESS_PERMISSIONS is not set on the older AMI 1.3. I was on the bastion and not on the 1.3 AMI when I "found" the difference. Apologies for that.

**Comment by chrislovecnm** [comment]
No worries. Are we just missing the headers?

**Comment by bassco** [comment]
@chrislovecnm Yes, just the headers. https://github.com/kopeio/kubernetes-kernel/pull/2 and https://github.com/kubernetes/kube-deploy/pull/248 will resolve the missing kernel headers.

**Comment by justinsb** [comment]
A new image is available @bassco: `kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-18`.  It has 4.4.25, with headers installed using your metapackage (thanks).

It isn't yet tagged as the stable image, but the only thing really stopping me from doing so is getting a "this works with sysdig" from you :-)  (you should be able to try it by editing your instance groups with `kops edit ig`, then `kops update cluster`, then probably `kops rolling-update`; you could also create a new cluster and specify the `--image` flag).

Also if you have any other ideas on the inotify issue, let me know!

**Comment by bassco** [comment]
@justinsb the new ami-aa1b54d9 AWS AMI is working great, in that our sysdig-agent DS is running without a glitch.

I am unable to verify the papertrailapp.com inotify issue, as that service only runs in prod.

**Comment by WillPlatnick** [comment]
Working fine here too. Can this be closed?

**Comment by chrislovecnm** [comment]
Done

**Comment by chrislovecnm** [comment]
Let me know if I need to re-open :)
