### ISSUE TITLE
Unable to use a local filesystem state store

### ISSUE THREAD

**Issue by ari-becker** [kubernetes/kops#6463]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`1.11.0`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

N/A

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster --state 'file:///tmp/kops-state' --zones us-east-1a foo.cluster.k8s.local
```

**5. What happened after the commands executed?**

```
State Store: Invalid value: "file:///tmp/kops-state": Unable to read state store.
Please use a valid state store when setting --state or KOPS_STATE_STORE env var.
For example, a valid value follows the format s3://<bucket>.
Trailing slash will be trimmed.
```

Issue is caused by [`vfs.IsClusterReadable` returning false for all filesystem state storage](https://github.com/kubernetes/kops/blob/894371395838751c830d34a51143227b2ca64006/util/pkg/vfs/vfs.go#L115) as called by [`factory.Clientset`](https://github.com/kubernetes/kops/blob/894371395838751c830d34a51143227b2ca64006/cmd/kops/util/factory.go#L109)

**6. What did you expect to happen?**

Not to get an error about being unable to read the state store.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Irrelevant

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

```
I0213 14:25:54.779621   34407 factory.go:68] state store file:///tmp/kops-state

State Store: Invalid value: "file:///tmp/kops-state": Unable to read state store.
Please use a valid state store when setting --state or KOPS_STATE_STORE env var.
For example, a valid value follows the format s3://<bucket>.
Trailing slash will be trimmed.
```

**9. Anything else do we need to know?**

The documentation [specifically claims that local filesystem state storage is supported with the `file://` protocol](https://github.com/kubernetes/kops/blob/894371395838751c830d34a51143227b2ca64006/docs/state.md#L13).

The bug was triggered when attempting to build a CI workflow around:

1. sync remote S3 state bucket to a local directory
2. change `.spec.configBase` to refer to the local directory
3. run `kops replace -f <candidate.yaml> --state file:///path/to/local/state/dir`
4. run `kops update cluster <cluster_name> --state file:///path/to/local/state/dir`

In a CI workflow, this would allow us to preview (for example, during a pull request) how a `kops update cluster` would run, without touching the actual remote S3 state bucket (from running `kops replace`).

**Comment by ari-becker** [comment]
Found the [PR](https://github.com/kubernetes/kops/pull/5931) that introduced the documentation that claimed that filesystem state stores were supported. Before that, code and documentation were in sync about filesystem state stores being unsupported.

Are filesystem state stores supported or not?

**Comment by jgdef-tulip** [comment]
I've hit the same issue w/ kops version Version `1.11.1 (git-0f2aa8d30)`

**Comment by lieut-data** [comment]
Also running into this issue, whilst trying to wrap kops as part of a larger deployment tool.

**Comment by berendt** [comment]
Tested with version 1.14.0-alpha.1 (git-ab68aa2d2). It doesn't work there either.

**Comment by caioaao** [comment]
Reproduced in `1.12.1 (git-e1c317f9c)`

**Comment by jayunit100** [comment]
So, kops state local doesnt work ? i dont see any instructions on how to use it (i.e. should i make a directory or will it mkdir -p for me..)

**Comment by joshuaganger** [comment]
Issue still present in 1.12.2

`[root@kube1 tmp]# kops version
Version 1.12.2 (git-3fc9bc486)
[root@kube1 tmp]# kops upgrade cluster localhost --state=file:///tmp/test

State Store: Invalid value: "file:///tmp/test": Unable to read state store.
Please use a valid state store when setting --state or KOPS_STATE_STORE env var.
For example, a valid value follows the format s3://<bucket>.
Trailing slash will be trimmed.
`

**Comment by qrilka** [comment]
The docs https://github.com/kubernetes/kops/blob/master/docs/state.md list many supported state stores but the source code looks like SSH, local FS and MemFS are explicitly not allowed

**Comment by elephant3** [comment]
Same in kops 1.14.0

**Comment by sbuvaneshkumar** [comment]
Facing same issue with kops version 1.17.0-alpha.1 (git-501baf7e5)
```
அ  ~/linuxacademy/eks/autoscaling kops create cluster --zones us-east-1a --name=test --state=file:///home/bsivasub/test/ --dns-zone=cmcloudlab1538.info --target terraform --out=.   

State Store: Invalid value: "file:///home/bsivasub/test": Unable to read state store.
Please use a valid state store when setting --state or KOPS_STATE_STORE env var.
For example, a valid value follows the format s3://<bucket>.
Trailing slash will be trimmed.

அ  ~/linuxacademy/eks/autoscaling file /home/bsivasub/test/
/home/bsivasub/test/: directory

அ  ~/linuxacademy/eks/autoscaling kops create cluster --zones us-east-1a --name=test --state=file:///home/bsivasub/test/ter --dns-zone=cmcloudlab1538.info --target terraform --out=.

State Store: Invalid value: "file:///home/bsivasub/test/ter": Unable to read state store.
Please use a valid state store when setting --state or KOPS_STATE_STORE env var.
For example, a valid value follows the format s3://<bucket>.
Trailing slash will be trimmed.

அ  ~/linuxacademy/eks/autoscaling file /home/bsivasub/test/ter
/home/bsivasub/test/ter: empty
```

**Comment by danielmittelman** [comment]
Same in kops 1.15.0

**Comment by pablolibo** [comment]
Same in kops 1.16.0

**Comment by olemarkus** [comment]
This feature is due for 1.17

**Comment by meabed** [comment]
its been a year guys - can someone fix this please! thanks

**Comment by olemarkus** [comment]
This feature is due for 1.17

**Comment by hakman** [comment]
> This feature is due for 1.17

And can be tested in the 1.17.0-beta.2 release.
https://github.com/kubernetes/kops/releases/tag/v1.17.0-beta.2
