### ISSUE TITLE
Support kubelet live reconfiguration with dynamic-config-dir flag

### ISSUE THREAD

**Issue by nelvadas** [kubernetes/kops#6464]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
With the current version , it is not possible to add all kubelet flags especially the dynamic-config-dir where kubelet pull its configuration from configmap in the cluster.

**2. Feel free to provide a design supporting your feature request.**
https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha1/componentconfig.go

**Comment by chotiwat** [comment]
I opened a PR for this at #7698
