### ISSUE TITLE
expose metrics-bind-address configuration for kube-proxy

### ISSUE THREAD

**Issue by vivekgarg20** [kubernetes/kops#6472]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
We are trying to scrape kube-proxy metrics but unable to do same with KOPS built cluster.
We figured out it is because of default metrics bind address is 127.0.0.1. 
As per K8S documentation it is possible to change default bind address to 0.0.0.0.
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/

It seems KOPS does not expose this configuration. 
**2. Feel free to provide a design supporting your feature request.**
It is straightforward as we need to expose metrics-bind-address configuration. I can submit a PR if required.

**Comment by vivekgarg20** [comment]
Thanks @gambol99

**Comment by demisx** [comment]
Would be nice to see this happen. Need this for prometheus operator.

**Comment by demisx** [comment]
Sorry, didn't realize this was added already with the PR. I am just having hard time finding an example of usage.

**Comment by demisx** [comment]
Can you guys please tell me how I can edit or create a new kops cluster with `metrics-bind-address=0.0.0.0`? Where do I set this? I tried passing the `--metrics-bind-address=0.0.0.0` flag to `kops create cluster`, but it does not understand it. Thank you!

**Comment by ivnilv** [comment]
> Can you guys please tell me how I can edit or create a new kops cluster with `metrics-bind-address=0.0.0.0`? Where do I set this? I tried passing the `--metrics-bind-address=0.0.0.0` flag to `kops create cluster`, but it does not understand it. Thank you!

For those who still need it, I managed to change the metrics bind address from 127.0.0.1 to 0.0.0.0 by putting the following in my [cluster spec](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md):

```
...
  kubeProxy:
    metricsBindAddress: 0.0.0.0
...
```
Then, did a `kops update cluster` followed by a rolling-update and and finally Prometheus was able to scrape the kube-proxy metrics 🎉

**Comment by demisx** [comment]
@ivnilv Thank you! This worked.
