### ISSUE TITLE
kop create cluster - error populating configuration: error querying for valid AZs in "eu-west-3"

### ISSUE THREAD

**Issue by ChambreNoire** [kubernetes/kops#6473]
**1. kops version : Version 1.11.0 (git-2c2042465)**

**2. Kubernetes version : 1.13**

**3. Cloud provider : AWS**

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

- Created 'kops' IAM user with AdministratorAccess
- Created 'kops-state-190215-1' S3 Bucket with region "EU Paris"
- Configured k8s.awebster.fr subdomain NS
- 'aws configure' with 'kops' secrets
- 'kops create cluster --name=k8s.awebster.me --state=s3://kops-state-190215-1 --zones=eu-west-3a --node-count=2 --node-size=t2.micro --master-size=t2.micro --dns-zone=k8s.awebster.me --cloud aws'

**5. What happened after the commands executed?**

error populating configuration: error querying for valid AZs in "eu-west-3" - verify your AWS credentials.  Error: AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: 2d099ba7-e29b-4e2f-82f7-ff2119d9faf3

**6. What did you expect to happen?**

Expected the S3 bucket to be populated with the manifest etc.

**9. Anything else do we need to know?**

I tried adding the following s3 bucket policy to (as seen elsewhere online). No change.

{
    "Version": "2012-10-17",
    "Id": "Policy1550240631316",
    "Statement": [
        {
            "Sid": "Stmt1550240628884",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::809593411167:user/kops"
            },
            "Action": "s3:GetBucketLocation",
            "Resource": "arn:aws:s3:::kops-state-190215-1"
        }
    ]
}

**Comment by joaomlopes** [comment]
Having the same issue here, have you managed to solve it?

**Comment by aykutyararbas** [comment]
Same here.

kops create cluster --zones=us-east-1c unnnnnn  --state s3:/mmmmmm.
   8596 create_cluster.go:480] Inferred --cloud=aws from zone "us-east-1c"

error populating configuration: **error querying for valid AZs in "us-east-1"** - verify your AWS credentials.  Error: UnauthorizedOperation: You are not authorized to perform this operation.

**Comment by bmoby** [comment]
Same issue. Please help

**Comment by fdmsantos** [comment]
You need to add ec2 DescribeAvailabilityZones permission to your policy.
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DescribeAvailabilityZones",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeAvailabilityZones"
            ],
            "Resource": "*"
        }
    ]
}

**Comment by marcindulak** [comment]
Check and adjust the `date` on the host running kops.

**Comment by ghassen1khalil** [comment]
I'm always getting the same issue as you guys .. what's the found the solution please ?

**Comment by scallopboat** [comment]
FWIW for anyone still facing this issue.  I ended up upgrading the aws cli to v2, and it started working.  Still not sure what the root cause is.
