### ISSUE TITLE
Kops support for detecting existing CIDRs in cloud providers

### ISSUE THREAD

**Issue by nzoueidi** [kubernetes/kops#6475]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
When you execute `kops create` on a cloud provider (e.g AWS). It creates automatically CIDRs for your subnets. It would be good to automatically detect if the targeted VPC contains already subnets or not rather than manually modifying the kops configuration using `kops edit`. 

I see that there some similar bugs/features closed, thus why I opened this one and I am interested to implement this feature :).

**Comment by timothyclarke** [comment]
Is this just an auto-detect version of `--network-cidr` or am I missing something?

How would you expect it to work with `kops delete cluster` should the pre-existing subnets and vpc's be destroyed as is the current case ?

**Comment by nzoueidi** [comment]
@timothyclarke if you try to create a k8s cluster w/ kops. If you passed by the argument `--network-cidr` it will always create another range(s) for your subnet(s). The case am talking about is to auto-detect the existing subnets. If they do not exist, then it is okay to create a random range(s). 

For the `kops delete cluster`, it is a good point. We can add an extra argument 
(e.g: `--destroy-everything=true/false` ) specifies if we want to fully destroy the vpc and its components.

**Comment by nzoueidi** [comment]
Again, this issue is still happening for the latest version of Kops.

**Comment by nzoueidi** [comment]
Looks like with newer version of Kops, I could not reproduce that. 

/close
