### ISSUE TITLE
Support for autoscaling/v2beta2

### ISSUE THREAD

**Issue by rajeshkodali** [kubernetes/kops#6481]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Does Kops 1.11 support autoscaling/v2beta2 Logs from kube-api-serverlog shows 

error: group version autoscaling/v2beta2 that has not been registered

**2. Feel free to provide a design supporting your feature request.**

**Comment by Globegitter** [comment]
I was just looking into the same thing and it does not seem to be the case. I can not even find documentation in kubernetes on how to activate it. Would be great to have support for this.

**Comment by gianrubio** [comment]
`Autoscaling/v2beta2` can be enabled only k8s 1.12, more info on k8s [1.12 release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#new-features) 

> Autoscaling/v2beta2 and custom_metrics/v1beta2 have been introduced, which implement metric selectors for Object and Pods metrics, as well as allowing AverageValue targets on Objects, similar to External metrics. (#64097, damemi) Courtesy of SIG API Machinery, SIG Architecture, SIG Autoscaling, SIG CLI, and SIG Testing
