### ISSUE TITLE
How to change subnet from public to private without causing downtime?

### ISSUE THREAD

**Issue by Justluckyg** [kubernetes/kops#6495]
Hello All,

I just have a question which I cant find the answer anywhere.

I have created a kops cluster and selected public for my master and my nodes. Now we have a client that needs to whitelist our IP. Currently 0.0.0.0/0 traffic is pointed to IGW. If i change it to use NATGW, i wont be able reach our API via Kubectl as the instances have public ip. In that sense, what is the easiest way to convert my kops cluster from public to private with less downtime? is it as easy just doing `kops edit cluster mycluster.cluster.io` and `kops update cluster mycluster.cluster.io`  and change all public to private? do i need to update any dns record? thanks!

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0 (git-8b52ea6d1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
N/A
**5. What happened after the commands executed?**
N/A
**6. What did you expect to happen?**
N/A

**Comment by zetaab** [comment]
I would create new cluster(s) and test possible options. Then you can see is there downtime or not. I would say there is downtime

**Comment by flmmartins** [comment]
It would be nice to see the outcome of this ^^
