### ISSUE TITLE
Use a dedicated etcd cluster for Cilium CNI

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kops#6496]
Since Kops is locking down etcd with version 1.12, Cilium should start using a dedicated etcd cluster. One option is to use the cilium-etcd-operator that ships with Cilium 1.4. Example resources for provisioning this can be found here: https://github.com/cilium/cilium/tree/master/examples/kubernetes/1.11

**Comment by so0k** [comment]
the bundled addon is also still using cilium 1.0-stable instead of 1.4

**Comment by Globegitter** [comment]
Yep would be great to have a working solution for the upcoming 1.12 that works with more than just "small" clusters. cc @nebril

**Comment by olemarkus** [comment]
The way forward would be to add cilium-etcd-operator to the ciliumkops add-on. The problem is that during cluster creation, only master nodes are available. And cilium-etcd-operator and the pods that they spawn currently don't have the tolerations necessary for them to be scheduled on master nodes. So that has to be added before anything can be done on the kops side.

For new clusters using etcd-manager, it won't be possible to use cilium at all because cilium running on normal nodes won't be able to talk to kops etcd anymore.

For existing clusters, we have managed to migrate to using cilium-etcd-operator just fine as then they can just be scheduled on normal nodes and we change the cilium k/v store before switching to etcd-manager.

**Comment by Globegitter** [comment]
Ah that is good to know @olemarkus and you are not experiencing any of the performance/scalibility/reliability issue sthat @so0k is referring to?

And the tolerations issue is https://github.com/cilium/cilium-etcd-operator/issues/42 I presume?

**Comment by Globegitter** [comment]
Just had a chat with @tgraf and with cilium 1.6 there will also be CRD support: https://github.com/cilium/cilium/pull/7573 which would make it possible to run without etcd when the cluster is below a certain size.

**Comment by olemarkus** [comment]
> Ah that is good to know @olemarkus and you are not experiencing any of the performance/scalibility/reliability issue sthat @so0k is referring to?

Performance-wise it should be more than enough. This is also what cilium use for scalability testing, I think.

Reliability ... we have seen etcd cluster has been recreated during rolling updates.This has been improving quite a bit though.

> 
> And the tolerations issue is [cilium/cilium-etcd-operator#42](https://github.com/cilium/cilium-etcd-operator/issues/42) I presume?

Yes.

**Comment by tushar00jain** [comment]
I tried installing cilium with etcd operator manually using `networking: CNI`, is there any downside to this? I hops cilium will provide an easy migration from etcd operator to CRDs though

**Comment by olemarkus** [comment]
Given that virtually no resources match the ones that kops create anymore, I think it makes sense to set `networking: cni`. Have done the same to some of our clusters.

That will also ensure kops does not override these resources unexpectedly in the future.

**Comment by olemarkus** [comment]
https://github.com/kubernetes/kops/pull/7474
