### ISSUE TITLE
Kubernetes with Calico on GCP 

### ISSUE THREAD

**Issue by sekhar-searce** [kubernetes/kops#6498]
Kops Version :- 1.11.0
Kubernetes Version :- 1.11.6
Cloud Provider :- GCP

gcloud compute networks create kube-test --project=project-name --subnet-mode=auto

kops create cluster \
  --kubernetes-version=1.11.6 \
  --zones asia-south1-b \
  --master-zones asia-south1-b \
  --image ubuntu-os-cloud/ubuntu-1604-xenial-v20190112  \
  --master-size n1-standard-2 \
  --node-size n1-standard-2 \
  --vpc=kube-test \
  --networking=calico \
  --project=project-name \
  testing.k8s.local

kops update cluster testing.k8s.local --yes

We are trying the above command and cluster is not spinning up. Can somebody tried this in GCP.

**Comment by suneeta-mall** [comment]
@sekhar-searce I am trying to setup K8s 1.12.7 on GCP with a CNI plugin preferably calico/flannel .. but I see the installation of cni goes into crash loop with error:
```"Error": "error while creating mount source path '/opt/cni/bin': mkdir /opt/cni: read-only file system",```
Something thats been mentioned in cilium issue as well [here](https://github.com/cilium/cilium/issues/4794) 

Did you manage to make any progress on your provisioning of cluster on GCP?

**Comment by ryaneorth** [comment]
@sekhar-searce are you still experiencing this issue? I am also seeing the same issue with calico and GCP. Deploying a k8s cluster to AWS via kops using calico for networking works as expected. As far as I can tell, this seems to be an issue with the combination of kops/calico/gcp.
