### ISSUE TITLE
Make CoreDNS the default DNS in Kops

### ISSUE THREAD

**Issue by rajansandeep** [kubernetes/kops#6500]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Currently, kube-dns is the default DNS in Kops. Would like to move the default to CoreDNS as it is in upstream Kubernetes.

**Comment by joshbranham** [comment]
I agree it makes sense for the default to be CoreDNS if that is the case in upstream Kubernetes. Anyone aware of work done already to attempt and implement this?

**Comment by olemarkus** [comment]
It is just a matter of changing defaults for the dns provider, I guess. Perhaps some docs on deleting kube-dns after the upgrade
