### ISSUE TITLE
More than one vendor directory - some with more than one copy of the same dependency

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#651]
It looks like we have a **vendor** and **_vendor** directory for the project. Is this intentional? Or should we consolidate these?

Also I noticed there are a few duplicated dependencies in the project, is this also intentional? Can we clean this up?

[**_vendor** with git submodules - spf13](https://github.com/kubernetes/kops/tree/master/vendor/github.com/spf13)

[**vendor** with included dependencies - spf13](https://github.com/kubernetes/kops/tree/master/vendor/github.com/spf13)

**Comment by chrislovecnm** [comment]
What do you recommend?

**Comment by kris-nova** [comment]
Send out a PR that :

- consolidates **all** dependencies into `vendor` 
- removes `_vendor` directory
- repoints all imports to the new `vendor` directory

Obviously we want to validate tests with this new release

**Comment by chrislovecnm** [comment]
Do it.

**Comment by kris-nova** [comment]
Labels and assign to me please :)

**Comment by chrislovecnm** [comment]
Done ;)

**Comment by justinsb** [comment]
I'll add a document for this.  It's deliberate, and it's subtle.

**Comment by justinsb** [comment]
Added #656, going to try to assign to you kris-nova, but having a little trouble doing so (github permissions).

**Comment by chrislovecnm** [comment]
Openned an issue about not being able to assign tasks to @kris-nova

**Comment by kris-nova** [comment]
Closing https://github.com/kubernetes/kops/pull/656
