### ISSUE TITLE
Adding GuestAccelerators to InstanceTemplate

### ISSUE THREAD

**Issue by harishsearce** [kubernetes/kops#6517]
As per steps mentioned to add GuestAccelerators #4277 

@chrislovecnm @roberthbailey i tried to add GuestAccelerators as suggested i.e:

* we need a new field in the instance group spec. Documentation https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md for how to add a field.
* follow @roberthbailey's instructions and add the `GuestAccelerators` I think in here https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go

As robert mentioned "So this is a field that kops would need to set when creating the instance template via some config exposed to the user in the kops api" where does this changes needs to be done in kops api?

If you could help on this, it would be great, i can raise PR once i am through.

FYI: i had added fields to the api by following steps mentioned in 1. https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md
GuestAccelerators []*AcceleratorConfig
I could see the updates in IG spec getting reflected with the changes but nothing happening:

Steps i followed:

* Add new field in the the api
* Following changes done in kops/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go:
  ** Added GuestAccelerators []*AcceleratorConfig in type InstanceTemplate struct
  ** And added
  type AcceleratorConfig struct {
  // AcceleratorCount: The number of the guest accelerator cards exposed
  // to this instance.
  AcceleratorCount int64 `json:"acceleratorCount,omitempty"`
  // AcceleratorType: Full or partial URL of the accelerator type resource
  // to attach to this instance. If you are creating an instance template,
  // specify only the accelerator name.
  AcceleratorType string `json:"acceleratorType,omitempty"`
  }
* make apimachinery && make

**Comment by harishsearce** [comment]
Hi team,

Any help would be appreciated.

Awaiting for your positive response!

**Comment by harishsearce** [comment]
@chrislovecnm i was able to provision GPU accelerators on GCE by doing some modification in the source code, I would like to raise a PR against it.

I have gone through [contributing](https://github.com/kubernetes/kops/blob/master/CONTRIBUTING.md) section

Please do let me know how can i go ahead on this.

**Comment by lime008** [comment]
Any news on this? Also if you @harishsearce have something working could you provide a link to a fork where this is implemented?

**Comment by olemarkus** [comment]
This is an old closed issue. I suggest creating a new one or reaching out on slack if you have questions.

**Comment by harishsearce** [comment]
@lime008 - Please find the forked version which helps to add GuestAccelerators to InstanceTemplate: https://github.com/searce-engineering/kops
