### ISSUE TITLE
Update README and project name

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#652]
Add Travis and [![Go Report Card](https://goreportcard.com/badge/k8s.io/kops)](https://goreportcard.com/report/k8s.io/kops) tags.

What should the project title be?

We need to write a omg we are seriously awesome paragraph as well.

**Comment by chrislovecnm** [comment]
Also add the info that @kris-nova did about slack

**Comment by kris-nova** [comment]
**Title:** A tool used to deploy, manage, and support kubernetes clusters.

**Comment by kris-nova** [comment]
@chrislovecnm - The title has been updated, can we close this and defer the remaining work here to https://github.com/kubernetes/kops/issues/641 ?

**Comment by chrislovecnm** [comment]
Be good to update the readme as well ;)

**Comment by kris-nova** [comment]
Closed with https://github.com/kubernetes/kops/pull/717
