### ISSUE TITLE
Could not create instance VPCIdNotSpecified: No default VPC for this user 	status code: 400, request id: 9fce1021-f6fe-4a50-a3ab-527f40d87940  Process finished with exit code 0

### ISSUE THREAD

**Issue by Nikjz** [kubernetes/kops#6528]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

**3. What cloud provider are you using?**

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by chrisz100** [comment]
/area aws

@Nikjz Can you please provide more information like what command you used to create this cluster?

**Comment by Nikjz** [comment]
Hey,

I used to the "https://github.com/kubernetes/kops/blob/master/cmd/kops/create_cluster.go" cocde to create a cluster in AWS. But, I am not able to import " k8s.io/kubernetes/pkg/kubectl/cmd/templates" and it gives the following error. error - 

![capture](https://user-images.githubusercontent.com/43389713/53348551-3ccb4280-38e9-11e9-9a46-03a4a08cf69e.PNG)


Could you please provide some help for the above
