### ISSUE TITLE
kops replace -f does not handle CRLF line endings correctly

### ISSUE THREAD

**Issue by pallewann** [kubernetes/kops#6532]
kops replace -f <file> does not update the instance groups when I change min / max nodes in the file. 

Looking into the kops source code I can see that "kops create -f" uses this code to split into sections:
  sections := bytes.Split(bytes.Replace(contents, []byte("\r\n"), []byte("\n"), -1), []byte("\n---\n"))
That line of code first converts CRLF to LF and then splits into sections.

"kops replace -f" and "kops delete -f" does not perform the CRLF to LF conversion:
  sections := bytes.Split(contents, []byte("\n---\n"))

I can workaround it using sed to convert CRLF to LF: sed -i 's/\r//g' <file> . 
I propose that replace.go and delete.go are updated with the same workaround as in create.go.

Related bugs:
#2430
#2243

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops replace -f <file>
1. Create a cluster from a cluster specification file using kops create -f <file> . The file must have CRLF line endings. 
2. Modify the cluster specification file, e.g. the instance group auto scaling min/max, and save the file.
3. Replace the cluster spec using kops replace -f <file> .
4. Update the cluster.
5. Using "kops edit ig nodes" I see that the cluster was not updated. 

**5. What happened after the commands executed?**
Nothing, the command had no effect

**6. What did you expect to happen?**
I expected the min and max number of nodes in the cluster to be updated.

**9. Anything else do we need to know?**
I am running kops in Windows subsystem for Linux on Windows 10 (Version 1803, OS Build 17134.590)

**Comment by gtrafimenkov** [comment]
I would like to work on this issue.  Assign it to me if possible.
