### ISSUE TITLE
openstack instances are not spread equally to AZs

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#6533]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I would like to see that instances are spread equally between zones. Now the situation is that all masters are also located in same zone. We have three zones `zone-1`, `zone-2` and `zone-3`. However, all of the instances are located in same zone after cluster creation
![screenshot 2019-02-26 at 9 25 09](https://user-images.githubusercontent.com/22482503/53394611-77e07b00-39a8-11e9-93ee-7412f5830ca8.png)

**2. Feel free to provide a design supporting your feature request.**

Because openstack servergroups does not support AZs, we should use schedulerhints when launching instances itself. 

/sig openstack

**Comment by drekle** [comment]
@zetaab can this close?

**Comment by zetaab** [comment]
Yes its merged
