### ISSUE TITLE
Unable to assign tasks

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#658]
I am unable to assign a task to @kris-nova for instance. Does she need to be a k8s member?

cc: @bgrant0607 @thockin

**Comment by chrislovecnm** [comment]
Sorry to bug u guys again on this :(

**Comment by chrislovecnm** [comment]
cc @justinsb

**Comment by kris-nova** [comment]
Referenced here https://github.com/kubernetes/kops/pull/656 as well.. Please please please <3

**Comment by bgrant0607** [comment]
@chrislovecnm 

(a) Please read github help, ask on slack, and raise these kinds of issues on kubernetes-wg-contribex. 

(b) Yes, one needs to be a member of the org.

@kris-nova What are your contributions so far?

**Comment by kris-nova** [comment]
@bgrant0607 -

Just getting started with k8s - but I am helping to [organize sig-aws](https://github.com/kubernetes/community/tree/master/sig-aws), also I have been helping out with [PRs/issues for kops](https://github.com/kubernetes/kops/issues?utf8=%E2%9C%93&q=kris-nova).

**Comment by chrislovecnm** [comment]
@bgrant0607 again it was Github wigging out, the timing coincided with the group change, so I thought that something may have changed.  Again, always appreciated!  Next time I will bug peeps on slack first.
