### ISSUE TITLE
Instance group is being deleted immediately without --yes option

### ISSUE THREAD

**Issue by nhamlh** [kubernetes/kops#6581]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.11.1
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.11.6
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops delete ig nodes
**5. What happened after the commands executed?**
Cloud resources is being deleted immediately without `--yes` option
**6. What did you expect to happen?**
It's supposed to apply this action later when I review my changes again before confirming the action
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by nareshku** [comment]
@nhamlh kops does prompt for confirmation if you do not specify `--yes`
```
kops delete ig test-ig
Using cluster from kubectl context: naresh-kops-upgrade.cluster.k8s.local

Do you really want to delete instance group "test-ig"? This action cannot be undone. (y/N)
```

Are you expecting it to just print the name of the IG going to be deleted and exit?

**Comment by nhamlh** [comment]
@nareshku I'm using kops in conjunction with terraform. I didn't specify `--yes` option to apply changes within kops itself but I wanted to generate terraform configuration, hence there's no confirmation prompted.
