### ISSUE TITLE
Mixed Instance Configuration Launches Normal ASG

### ISSUE THREAD

**Issue by jibsonline** [kubernetes/kops#6582]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.10.0

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I created a new Instance group with below configuration

```
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: my.cluster.com
  name: pre-prod-nodes-mixed
spec:
  associatePublicIp: false
  cloudLabels:
    role: compute
    APPLICATIONROLE: PM_PRE_PRODUCTION_K8S_WORKER_MIXED_NODES
  image: coreos.com/CoreOS-stable-1911.4.0-hvm
  machineType: m4.large
  maxSize: 5
  minSize: 2
  role: Node
  # add the mixed instance here
  mixedInstancesPolicy:
    instances:
    - m5.large
    - m5.xlarge
    - t2.medium
    onDemandAboveBase: 0
    spotInstancePools: 3
  subnets:
  - ap-south-1a
  - ap-south-1b
```

**5. What happened after the commands executed?**

A normal Instance group was created with below spec

```apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-05T16:52:22Z
  labels:
    kops.k8s.io/cluster: my.cluster.com
  name: pre-prod-nodes-mixed
spec:
  associatePublicIp: false
  cloudLabels:
    APPLICATIONROLE: PM_PRE_PRODUCTION_K8S_WORKER_MIXED_NODES
    role: compute
  image: coreos.com/CoreOS-stable-1911.4.0-hvm
  machineType: m4.large
  maxSize: 5
  minSize: 2
  role: Node
  subnets:
  - ap-south-1a
  - ap-south-1b```

**6. What did you expect to happen?**

A instance group with mixed instances

**7. Please provide your cluster manifest. Execute


```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: my.cluster.com
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:TerminateInstanceInAutoScalingGroup"
          ],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      idleTimeoutSeconds: 300
      type: Internal
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudConfig:
    disableSecurityGroupIngress: true
    elbSecurityGroup: sg-074da56aee772f87c
  cloudLabels:
    APPLICATIONENV: PRE_PRODUCTION
    BUSINESSUNIT: PM
    OWNEREMAIL: DEVOPS@PAYTMMONEY.COM
  cloudProvider: aws
  clusterDNSDomain: cluster.local
  configBase: s3://cluster-envuction-kubernetes-states/my.cluster.com
  configStore: s3://cluster-envuction-kubernetes-states/my.cluster.com
  dnsZone: HDDWDLWD
  docker:
    bridge: ""
    ipMasq: false
    ipTables: false
    logDriver: json-file
    logLevel: warn
    logOpt:
    - max-size=10m
    - max-file=5
    storage: overlay,aufs
    version: 17.03.2
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: env-master-ap-south-1a-1
      name: a-1
      volumeSize: 30
    - encryptedVolume: true
      instanceGroup: env-master-ap-south-1b-1
      name: b-1
      volumeSize: 30
    - encryptedVolume: true
      instanceGroup: env-master-ap-south-1a-2
      name: a-2
      volumeSize: 30
    image: k8s.gcr.io/etcd:3.2.17
    name: main
    version: 3.2.17
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: env-master-ap-south-1a-1
      name: a-1
      volumeSize: 30
    - encryptedVolume: true
      instanceGroup: env-master-ap-south-1b-1
      name: b-1
      volumeSize: 30
    - encryptedVolume: true
      instanceGroup: env-master-ap-south-1a-2
      name: a-2
      volumeSize: 30
    image: k8s.gcr.io/etcd:3.2.17
    name: events
    version: 3.2.17
  iam:
    allowContainerRegistry: true
    legacy: false
  keyStore: s3://cluster-envuction-kubernetes-states/my.cluster.com/pki
  kubeAPIServer:
    address: 127.0.0.1
    admissionControl:
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    - PersistentVolumeClaimResize
    - PersistentVolumeLabel
    allowPrivileged: true
    anonymousAuth: false
    apiServerCount: 3
    auditLogFormat: json
    authorizationMode: AlwaysAllow
    cloudProvider: aws
    etcdQuorumRead: false
    etcdServers:
    - http://127.0.0.1:4001
    etcdServersOverrides:
    - /events#http://127.0.0.1:4002
    featureGates:
      ExpandPersistentVolumes: "true"
    image: k8s.gcr.io/kube-apiserver:v1.10.0
    insecurePort: 8080
    kubeletPreferredAddressTypes:
    - InternalIP
    - Hostname
    - ExternalIP
    logLevel: 2
    maxRequestsInflight: 1000
    requestheaderAllowedNames:
    - aggregator
    requestheaderExtraHeaderPrefixes:
    - X-Remote-Extra-
    requestheaderGroupHeaders:
    - X-Remote-Group
    requestheaderUsernameHeaders:
    - X-Remote-User
    securePort: 443
    serviceClusterIPRange: 100.64.0.0/13
    storageBackend: etcd3
  kubeControllerManager:
    allocateNodeCIDRs: true
    attachDetachReconcileSyncPeriod: 1m0s
    cloudProvider: aws
    clusterCIDR: 100.96.0.0/11
    clusterName: my.cluster.com
    configureCloudRoutes: false
    featureGates:
      ExpandPersistentVolumes: "true"
    horizontalPodAutoscalerDownscaleDelay: 5m0s
    horizontalPodAutoscalerSyncPeriod: 15s
    horizontalPodAutoscalerUpscaleDelay: 3m0s
    image: k8s.gcr.io/kube-controller-manager:v1.10.0
    leaderElection:
      leaderElect: true
    logLevel: 2
    useServiceAccountCredentials: true
  kubeDNS:
    cacheMaxConcurrent: 150
    cacheMaxSize: 1000
    domain: cluster.local
    replicas: 2
    serverIP: 100.64.0.10
  kubeProxy:
    clusterCIDR: 100.96.0.0/11
    cpuRequest: 100m
    hostnameOverride: '@aws'
    image: k8s.gcr.io/kube-proxy:v1.10.0
    logLevel: 2
  kubeScheduler:
    image: k8s.gcr.io/kube-scheduler:v1.10.0
    leaderElection:
      leaderElect: true
    logLevel: 2
  kubelet:
    allowPrivileged: true
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableCustomMetrics: true
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    featureGates:
      ExpandPersistentVolumes: "true"
      ExperimentalCriticalPodAnnotation: "true"
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: k8s.gcr.io/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
  kubernetesApiAccess:
  - 172.20.0.0/16
  kubernetesVersion: 1.10.0
  masterInternalName: api.internal.my.cluster.com
  masterKubelet:
    allowPrivileged: true
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableCustomMetrics: true
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    featureGates:
      ExpandPersistentVolumes: "true"
      ExperimentalCriticalPodAnnotation: "true"
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: k8s.gcr.io/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
    registerSchedulable: false
  masterPublicName: master.my.cluster.com
  networkCIDR: 172.20.0.0/16
  networkID: vpc-0098c22a411e0cf0d
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  secretStore: s3://cluster-envuction-kubernetes-states/my.cluster.com/secrets
  serviceClusterIPRange: 100.64.0.0/13
  sshAccess:
  - 172.20.0.0/16
  sshKeyName: cluster-env
  subnets:
  - cidr: 172.20.3.0/24
    egress: nat-0e427d89a424588f6
    id: subnet-04f097f16fc9b0546
    name: ap-south-1a
    type: Private
    zone: ap-south-1a
  - cidr: 172.20.4.0/24
    egress: nat-0e427d89a424588f6
    id: subnet-06ca6f7f649449f60
    name: ap-south-1b
    type: Private
    zone: ap-south-1b
  - cidr: 172.20.1.0/24
    id: subnet-0ab04bbc1148c7ced
    name: utility-ap-south-1a
    type: Utility
    zone: ap-south-1a
  - cidr: 172.20.2.0/24
    id: subnet-0d4cae112aabecfae
    name: utility-ap-south-1b
    type: Utility
    zone: ap-south-1b
  topology:
    bastion:
      bastionPublicName: bastion.my.cluster.com
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-04T06:13:10Z
  labels:
    kops.k8s.io/cluster: my.cluster.com
  name: env-bastions
spec:
  additionalSecurityGroups:
  - sg-0f058c4248d0f5865
  image: 656952484900/k8s-ami-v2
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: env-bastions
  role: Bastion
  subnets:
  - utility-ap-south-1a
  - utility-ap-south-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-04T06:13:10Z
  labels:
    kops.k8s.io/cluster: my.cluster.com
  name: env-master-ap-south-1a-1
spec:
  additionalSecurityGroups:
  - sg-0f058c4248d0f5865
  associatePublicIp: false
  cloudLabels:
    APPLICATIONROLE: PM_PRE_PRODUCTION_K8S_MASTER_NODES
  image: 656952484900/k8s-ami-v9
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: env-master-ap-south-1a-1
  role: Master
  rootVolumeSize: 100
  subnets:
  - ap-south-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-16T12:36:29Z
  labels:
    kops.k8s.io/cluster: my.cluster.com
  name: env-master-ap-south-1a-2
spec:
  additionalSecurityGroups:
  - sg-0f058c4248d0f5865
  associatePublicIp: false
  cloudLabels:
    APPLICATIONROLE: PM_PRE_PRODUCTION_K8S_MASTER_NODES
  image: 656952484900/k8s-ami-v9
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: env-master-ap-south-1a-2
  role: Master
  rootVolumeSize: 100
  subnets:
  - ap-south-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-16T12:36:29Z
  labels:
    kops.k8s.io/cluster: my.cluster.com
  name: env-master-ap-south-1b-1
spec:
  additionalSecurityGroups:
  - sg-0f058c4248d0f5865
  associatePublicIp: false
  cloudLabels:
    APPLICATIONROLE: PM_PRE_PRODUCTION_K8S_MASTER_NODES
  image: 656952484900/k8s-ami-v9
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: env-master-ap-south-1b-1
  role: Master
  rootVolumeOptimization: false
  rootVolumeSize: 100
  subnets:
  - ap-south-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-16T12:36:29Z
  labels:
    kops.k8s.io/cluster: my.cluster.com
  name: env-nodes
spec:
  additionalSecurityGroups:
  - sg-0f058c4248d0f5865
  associatePublicIp: false
  cloudLabels:
    APPLICATIONROLE: PM_PRE_PRODUCTION_K8S_WORKER_NODES
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: c5.xlarge
  maxSize: 6
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: env-nodes
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 200
  subnets:
  - ap-south-1a
  - ap-south-1b
  suspendProcesses:
  - AZRebalance

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-05T16:52:22Z
  labels:
    kops.k8s.io/cluster: my.cluster.com
  name: env-nodes-mixed
spec:
  associatePublicIp: false
  cloudLabels:
    APPLICATIONROLE: PM_PRE_PRODUCTION_K8S_WORKER_MIXED_NODES
    role: compute
  image: coreos.com/CoreOS-stable-1911.4.0-hvm
  machineType: m4.large
  maxSize: 5
  minSize: 2
  role: Node
  subnets:
  - ap-south-1a
  - ap-south-1b
```

**Comment by rjanovski** [comment]
mixed instance IG is currently only available in master branch. 
1.11.1 (latest release) doesn't have it, so kops ignore your mixedInstancePolicy section.

**Comment by rjanovski** [comment]
and issue #6577 is preventing from using the master at the moment.
