### ISSUE TITLE
Install kpos in Openstack

### ISSUE THREAD

**Issue by mahm1846** [kubernetes/kops#6584]
Hi, 
I am trying to install the kops in our private **OpenStack** Cloud with **docker**. 
I have followed the command in the link: https://github.com/kubernetes/kops/blob/master/docs/tutorial/openstack.md

However, it has following errors have occurred.
1) command says the "--os-ext-net" and "--etcd-storage-type" are not supported.
2) Command also ask for "~/.openstack/config" file.

Can someone please explain how to resolve those issues for openstack? 

Thanks 
Maruf

**Comment by drekle** [comment]
Hi @mahm1846 did you by chance forget to set `KOPS_FEATURE_FLAGS="AlphaAllowOpenStack"`?  This would be the only condition there I can see point 1 you've made to trigger.

Also 2 may occur if you have not sourced your openstack rc file or if your cluster `--name` does not end in `.k8s.local` as we currently have not battle tested designate.

**Comment by mahm1846** [comment]
Hi Drekle,

Thank you very much for the reply. Sorry, I couldn't reply earlier, it was long weekend in AU. 
I definitely set KOPS_FEATURE_FLAGS="AlphaAllowOpenStack", but still the same problem.
Thanks,
Maruf

**Comment by zetaab** [comment]
are you compiling kops binary yourself? these changes are not in any release yet.

**Comment by mahm1846** [comment]
I tried to compile kops from the source and got following error. 

$~/kops/src/k8s.io/kops$ make
cd /home/ubuntu/kops/src/k8s.io/kops; /home/ubuntu/kops/src/k8s.io/kops/.build/local/go-bindata -o upup/models/bindata.go -pkg models -ignore="\\.DS_Store" -ignore="bindata\\.go" -ignore="vfs\\.go" -prefix upup/models/ upup/models/...
go install   -ldflags=all="-X k8s.io/kops.Version=1.12.0-alpha.1 -X k8s.io/kops.GitVersion=3b907c81e " k8s.io/kops/cmd/kops/
# k8s.io/kops/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go:287:33: error: reference to undefined name ‘NewAlphaFeatureGate’
  cloudConfig.AlphaFeatureGate = NewAlphaFeatureGate([]string{})
                                 ^
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go:309:34: error: reference to undefined name ‘NewAlphaFeatureGate’
   cloudConfig.AlphaFeatureGate = NewAlphaFeatureGate(configFile.Global.AlphaFeatures)
                                  ^
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go:152:20: error: use of undefined type ‘AlphaFeatureGate’
  AlphaFeatureGate *AlphaFeatureGate
                    ^
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_addresses.go:188:26: error: reference to field ‘Enabled’ in object which has no fields or methods
  if !gce.AlphaFeatureGate.Enabled(AlphaFeatureNetworkTiers) {
                          ^
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_addresses.go:188:35: error: reference to undefined name ‘AlphaFeatureNetworkTiers’
  if !gce.AlphaFeatureGate.Enabled(AlphaFeatureNetworkTiers) {
                                   ^
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_forwardingrule.go:154:26: error: reference to field ‘Enabled’ in object which has no fields or methods
  if !gce.AlphaFeatureGate.Enabled(AlphaFeatureNetworkTiers) {
                          ^
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_forwardingrule.go:154:35: error: reference to undefined name ‘AlphaFeatureNetworkTiers’
  if !gce.AlphaFeatureGate.Enabled(AlphaFeatureNetworkTiers) {
                                   ^
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go:79:25: error: reference to field ‘Enabled’ in object which has no fields or methods
  if gce.AlphaFeatureGate.Enabled(AlphaFeatureNetworkTiers) {
                         ^
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go:79:34: error: reference to undefined name ‘AlphaFeatureNetworkTiers’
  if gce.AlphaFeatureGate.Enabled(AlphaFeatureNetworkTiers) {
                                  ^
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go:1058:26: error: reference to field ‘Enabled’ in object which has no fields or methods
  if !gce.AlphaFeatureGate.Enabled(AlphaFeatureNetworkTiers) {
                          ^
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go:1058:35: error: reference to undefined name ‘AlphaFeatureNetworkTiers’
  if !gce.AlphaFeatureGate.Enabled(AlphaFeatureNetworkTiers) {
                                   ^
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go:152:20: error: use of undefined type ‘AlphaFeatureGate’
  AlphaFeatureGate *AlphaFeatureGate
                    ^
(null):0: confused by earlier errors, bailing out
Makefile:136: recipe for target 'kops-install' failed
make: *** [kops-install] Error 2

**Comment by drekle** [comment]
Sorry about the delayed responses.  I am having some issue filtering out emails.  Mitaka is end of life but I am not sure that is the problem here.
https://releases.openstack.org/

I briefly remember seeing a similar issue as this with a devstack deployment.  Are you capable of listing loadbalancers with the neutron client?  `neutron lbaas-loadbalancer-list`

**Comment by mahm1846** [comment]
Hi Derek,

No problem. I made a mistake, we are using Ocata. We are hoping to upgrade soon.

The output from the command is


~$ neutron lbaas-loadbalancer-list

neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.

The resource could not be found.<br /><br />




Neutron server returns request_ids: ['req-$


Looks like load balancer is not working for our cloud. Is this the main problem?


Thanks,

Maruf

________________________________

**Comment by zetaab** [comment]
you must have either old neutron lbaasv2 or newer octavia loadbalancer in your cloud. Command for neutron lbaas was that `neutron lbaas-loadbalancer-list` and for octavia the command is `openstack loadbalancer list`. If none of those commands works, then the cloud is not good enough for kops
