### ISSUE TITLE
nodeup: Did not find docker package for xenial amd64 18.06.3

### ISSUE THREAD

**Issue by ChristopherHanson** [kubernetes/kops#6585]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`1.11.1`

**3. What cloud provider are you using?**

AWS

**4. What is the simplest way to reproduce this issue?**

Create a cluster on AWS on ubuntu 16.04 (ami-0ad16744583f21877 in us-west-1) without specifying the Docker version in the cluster config.

**5. What happened after the commands executed?**

Docker is _not_ installed on cluster ubuntu 16.04 cluster nodes and the cluster fails to start; journalctl on the nodes reports:

```
Mar 05 23:16:21 ip-10-0-16-11 nodeup[1819]: W0305 23:16:21.306809    1819 docker.go:860] Did not find docker package for xenial amd64 18.06.3
```

**6. What did you expect to happen?**

kops should install Docker 18.06.3 by default on all cluster nodes

**9. Anything else do we need to know?**

Setting a docker version to the previous release in the cluster config build the cluster successfully:

```
spec:
  docker:
    version: 18.06.2
```

**Comment by bhvishal9** [comment]
Was it fixed? We are still getting this issue on kops Version 1.12.0-beta.1.

**Comment by apjneeraj** [comment]
we have the same issue while upgrading cluster from 1.11.x to 1.12.x with kops 1.12.0-beta.2. 

> systemd[1]: Started Kubernetes Protokube Service.
-- Subject: Unit protokube.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit protokube.service has finished starting up.
--
-- The start-up result is done.
May 08 19:16:29 ip-172-5-61-100 systemd[13490]: protokube.service: Failed at step EXEC spawning /usr/bin/docker: No such file or directory
-- Subject: Process /usr/bin/docker could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

**Comment by ChristopherHanson** [comment]
Does the workaround of setting the docker and version keys in the cluster config work for either of you? That is essentially how we "solved" the issue, e.g.:

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: example-cluster
spec:
  docker:
    version: 18.06.2
```

Not sure we've tried anything beyond 18.06.2 at this point though.

**Comment by adammw** [comment]
18.06.3 seems only to be defined for Ubuntu Bionic (18.04), not Ubuntu Xenial (16.04), even though there are packages for it on the Docker download site.

https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/docker.go
