### ISSUE TITLE
kube api not on 443

### ISSUE THREAD

**Issue by LisaFournet8** [kubernetes/kops#6589]
Hi,

Is there a way to deploy a cluster with kube-apiserver listening on another port than 443? In other terms is there a cluster spec that can be added so that the --secure-port flag in kube-apiserver.manifest is not 443?

I'd like to deploy an nginx ingress controller on a master, but I can't because port 443 is already used by the kube api.

Thanks

**Comment by MMeent** [comment]
I believe this is available in the `ClusterSpec`: you can set `.spec.kubeAPIServer.securePort`, which should translate to the `--secure-port` flag. 

Note: I have not explicitly tested this.
