### ISSUE TITLE
Go deps tooling

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#659]
Per https://github.com/kubernetes/kops/pull/656 we are doing deps sorta by hand.

Asses using either glide or godeps for this project.

**Comment by chrislovecnm** [comment]
@kris-nova once cstone comes up with a recommendation we should demo it for @justinsb

**Comment by justinsb** [comment]
Look forward to seeing that ;-)

**Comment by kris-nova** [comment]
Okay great - will put together a good side-by-side - yay dependency management in Go

**Comment by chrislovecnm** [comment]
@JuJu227 I know that you will probably be looking at glide or godeps for us internally.  Would be good to share what we figure out, if we can improve this project.

**Comment by chrislovecnm** [comment]
Here is the answer the mothership is moving to glide https://github.com/kubernetes/kubernetes/pull/24202

**Comment by justinsb** [comment]
That's not how I read it @chrislovecnm .. ;-)  Commented there - hopefully we'll get some clarity.

**Comment by chrislovecnm** [comment]
Lol - sounds good. No rush

**Comment by chrislovecnm** [comment]
Closing
