### ISSUE TITLE
Upgrade to kops 1.11.1 - node can't find /pki/issued/etcd-manager-ca-main/keyset.yaml

### ISSUE THREAD

**Issue by juniorz** [kubernetes/kops#6600]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.11.1 (git-0f2aa8d30)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:32:00Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

$ kops update cluster --yes
$ kops rolling-update cluster --instance-group master-us-east-1a --yes

**5. What happened after the commands executed?**

The new master node does not join the cluster

**6. What did you expect to happen?**

The new master node to join the cluster

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

system log for the new node (from kops 1.11.1) has the following lines

```
Mar 08 15:28:46 ip-10-107-2-156 nodeup[786]: I0308 15:28:46.204024     786 s3fs.go:220] Reading file "s3://<bucket>/<cluster>/pki/issued/etcd-manager-ca-main/keyset.yaml"
Mar 08 15:28:46 ip-10-107-2-156 nodeup[786]: W0308 15:28:46.208467     786 main.go:142] got error running nodeup (will retry in 30s): error building loader: error in 'FindCert' attempting to load cert "etcd-manager-ca-main": unable to read bundle "s3://<bucket>/<cluster>/pki/issued/etcd-manager-ca-main/keyset.yaml": error fetching s3://<bucket>/<cluster>/pki/issued/etcd-manager-ca-main/keyset.yaml: AccessDenied: Access Denied
```

But there is no such line `Reading file "s3://<bucket>/<cluster>/pki/issued/etcd-manager-ca-main/keyset.yaml"` on the system log for the existing master node (from kops 1.11.0).

In fact, the prefix `/pki/issued/etcd-manager-ca-main/` does not have any object.

```
aws s3 ls s3://<bucket>/<cluster>/pki/issued/
                           PRE apiserver-aggregator-ca/
                           PRE apiserver-aggregator/
                           PRE apiserver-proxy-client/
                           PRE ca/
                           PRE kops/
                           PRE kube-controller-manager/
                           PRE kube-proxy/
                           PRE kube-scheduler/
                           PRE kubecfg/
                           PRE kubelet-api/
                           PRE kubelet/
                           PRE master/
```

Other relevant log lines from the failing node:

```
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: I0308 14:11:05.371878     786 protokube.go:253] no EtcdManifests; protokube will manage etcd
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: I0308 14:11:05.371900     786 build_flags.go:50] ignoring non-field:
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: I0308 14:11:05.371908     786 build_flags.go:50] ignoring non-field:
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: I0308 14:11:05.371917     786 build_flags.go:50] ignoring non-field: .ApplyTaints
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: I0308 14:11:05.371961     786 build_flags.go:50] ignoring non-field: .TLSAuth
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: I0308 14:11:05.371997     786 convenience.go:70] proxies is == nil, returning empty list
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: I0308 14:11:05.372022     786 protokube.go:150] Built service manifest "protokube"
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: [Unit]
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: Description=Kubernetes Protokube Service
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: Documentation=https://github.com/kubernetes/kops
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: [Service]
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: ExecStartPre=/bin/true
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: ExecStart=/usr/bin/docker run -v /:/rootfs/ -v /var/run/dbus:/var/run/dbus -v /run/systemd:/run/systemd -v /usr/local/bin:/opt/kops/bin:ro --env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/b
in:/opt/kops/bin --net=host --pid=host --privileged --env KUBECONFIG=/rootfs/var/lib/kops/kubeconfig  -e 'AWS_REGION=us-east-1'  protokube:1.11.1 /usr/bin/protokube --channels=s3://<bucket>/<cluster>/addons/bootstrap-chann
el.yaml --cloud=aws --containerized=true --dns-internal-suffix=.internal.<cluster> --dns=aws-route53 --etcd-image=k8s.gcr.io/etcd:2.2.1 --initialize-rbac=true --manage-etcd=true --master=true --v=4 --zone=*/ZBJ51L2QOMR9A
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: Restart=always
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: RestartSec=2s
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: StartLimitInterval=0
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: [Install]
Mar 08 14:11:05 ip-10-107-2-156 nodeup[786]: WantedBy=multi-user.target
```

**Comment by justin-lau** [comment]
I think this is caused by #6311.

I tried upgrading on a testing environment from kops v1.11.0 and k8s v1.11.6, and have run into the same problem. After that I upgraded other environments with the following steps and they went well:

1. `kops upgrade cluster`

2. **Important:** before applying the update, make sure the etcd version is pinned to `2.2.1`: `kops set cluster cluster.spec.etcdClusters[*].version=2.2.1`

3. I have further added `cluster.spec.etcdClusters[*].provider=Manager` to remind our fellow DevOps about the change, and also manually set `kubernetesVersion=1.11.8` (default to 1.11.7 with kops v1.11.1).

4. Continue as usual: `kops update cluster` then `kops rolling-update cluster`

**Comment by JamesMura** [comment]
I think we figured out what was causing this issue, we have a very restrictive bucket policy on the `s3 bucket` for the `kops config` for the cluster causing it to throw a `403` status codes for access to folders that do not exist e,g `/pki/issued/etcd-manager-ca-main/keyset.yaml`, such that the `EtcdManagerTLSBuilder` gets an error [here](https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/etcd_manager_tls.go#L82) rather than getting a 404 (thus the nil [here](https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/etcd_manager_tls.go#L91))
