### ISSUE TITLE
kops unable to access public ssh key that it should have access to 

### ISSUE THREAD

**Issue by rschoenbeck** [kubernetes/kops#6603]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.11.1 (git-cb8143c)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.13.4

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

1. Launch an Ubuntu 18.04 EC2 instance
2. install kubectl and kops via snap
3. kops create cluster --name [name] --zones [your availability zone]
4. ssh-keygen in ssh directory
5. chmod 644 on id_rsa.pub -- or even more permissive options if you want, same result
6. kops create secret --name [name]l sshpublickey admin -i ~/.ssh/id_rsa.pub

**5. What happened after the commands executed?**
```error reading SSH public key /home/ubuntu/.ssh/id_rsa.pub: open /home/ubuntu/.ssh/id_rsa.pub: permission denied```

**6. What did you expect to happen?**
I expected the secret to be successfully added.
Also checked ownership + permissions levels of file + .ssh directory; no amount of permissiveness mattered

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-03-10T21:44:55Z
  name: airflow.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: [s3 bucket]
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.7
  masterPublicName: api.airflow.k8s.local
  networkCIDR: [redacted]
  networking:
    kubenet: {}
  nonMasqueradeCIDR: [redacted]
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: [redacted]
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-10T21:44:55Z
  labels:
    kops.k8s.io/cluster: airflow.k8s.local
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-10T21:44:55Z
  labels:
    kops.k8s.io/cluster: airflow.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
I0310 21:52:09.760161   15853 factory.go:68] state store s3://[bucket]
I0310 21:52:10.191870   15853 s3context.go:194] found bucket in region "us-west-2"
I0310 21:52:10.192066   15853 s3fs.go:220] Reading file "s3://[bucket]/airflow.k8s.local/config"

error reading SSH public key /home/ubuntu/.ssh/id_rsa.pub: open /home/ubuntu/.ssh/id_rsa.pub: permission denied
```

**9. Anything else do we need to know?**

**Comment by brobert83** [comment]
I had the same problem, looking at the code where that error message comes everything looks ok https://github.com/kubernetes/kops/blob/release-1.11/cmd/kops/create_secret_sshpublickey.go 

so I tried moving the key file in the same dir where I executed the command, and it worked, don't ask me why

```
 kops create secret --state s3://<<my bucket>> --name <<my cluster>> sshpublickey admin -i id_rsa.pub
```

**Comment by hynespm** [comment]
This issue still remains. I am using version Version 1.17.0-beta.1 (git-32af4ed9b)

**Comment by niconavarrete** [comment]
moving .pub file to  ~ instead of ~.ssh/  and kops finds the file but it fails to find .kube/config ... so i may assumes it's some kind of other problem not related to kops (maybe snap or whatever)

**Comment by sirinibin** [comment]
Solution:

```
Move ~/.ssh/id_rsa.pub to ~
cp ~/.ssh/id_rsa.pub ~
cd ~
```
```
kops create cluster --cloud=aws --zones=us-east-2c --name=demo.k8s.startuptech.uk --dns-zone=startuptech.uk --dns=private --ssh-public-key=id_rsa.pub
```

**Comment by femiog** [comment]
This is permission issue. For AWS, go back your console and create some of these roles 
AdministrativeAccess, 
AmazonEC2FullAccess 
IAMFullAccess 
then attach the roles to your EC2 instance to give it privilege permissions needed to make API to your aws resource. I did this, and re-ran the command " kops create secret --name ${NAME} sshpublickey admin -i ~/.ssh/{insert your file name} "and it worked.
