### ISSUE TITLE
CoreOS image failes when adding LimitMEMLOCK=infinity using User-Data

### ISSUE THREAD

**Issue by oded-dd** [kubernetes/kops#6606]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.11.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:35:19Z", GoVersion:"go1.12",
Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Span a new instancegroup from a file

**5. What happened after the commands executed?**
The related instance is unable to start

**6. What did you expect to happen?**
The instance restarting and is not added to the cluster

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-12T03:47:59Z
  labels:
    kops.k8s.io/cluster: test.cluster.k8s.local
  name: test
spec:
  additionalUserData:
  - content: |
      coreos:
        units:
          - name: "docker.service"
            drop-ins:
              - name: "30-increase-ulimit.conf"
                content: |
                  [Service]
                  LimitMEMLOCK=infinity
    name: increase-ulimit.conf
    type: text/cloud-config
  cloudLabels:
    Env: test
    Role: test
  iam:
    profile: arn:aws:iam::625240141681:instance-profile/kops/staging.cluster.k8s.local/instance-profiles/node/role_node
  image: 595879546273/CoreOS-stable-2023.4.0-hvm
  machineType: r5.large
  maxPrice: "0.045"
  maxSize: 1
  minSize: 1
  nodeLabels:
    cluster: "1"
    kops.k8s.io/instancegroup: test
    role: test
    service: test
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=test:NoSchedule

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
It works when I span a physical machine and run it

**Comment by oded-dd** [comment]
Can someone please help?

**Comment by rochacon** [comment]
@oded-dd CoreOS images does not support the `additionalUserData` field, this is a limitation of CoreOS cloud-init support. You must use the `fileAssets` or `hooks` fields to achieve similar behavior.

**Comment by oded-dd** [comment]
Thank you for your response,

Can you guide me on how it can be done?
