### ISSUE TITLE
Protokube has sustained cpu usage above 100%

### ISSUE THREAD

**Issue by sheldonkwok** [kubernetes/kops#6610]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.11.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.11.7

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

We're running top on the node and protokube is consistently bursting over 100%

Are there any leads to what could be causing high cpu usage? I'm not sure what else to report this since we're not running any kops commands.

**Comment by justinsb** [comment]
Does it coincide with anything in the logs?  (`journalctl -fu protokube`)  Is there anything "unusual" about your configuration - any less common options you're running?

**Comment by sheldonkwok** [comment]
It's mostly logs like 
`error during connection attempt: dial tcp4 0.0.0.0:0->10.88.69.183:3999: connect: connection timed out`

I've been looking into where it's getting these cached old ip addresses but wasn't sure if that was related to the CPU.

**Comment by sheldonkwok** [comment]
A lot of these timed out connections are targeting machines that were removed several days ago.

**Comment by sheldonkwok** [comment]
We figured out it was due to having hundreds of nodes with the protokube mesh. Switching to dns based discovery solved. Had to create a new cluster though.
