### ISSUE TITLE
Ability to specify priorityClassName in kops managed manifests

### ISSUE THREAD

**Issue by d-shi** [kubernetes/kops#6615]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
I'm not sure if this already supported or not, but was unable to find it in the docs or previous github issues. I'd like to be able to specify `priorityClassName` in the manifests generated by kops, such as kube-proxy, since pod priority is enabled by default in 1.11 and the rescheduler is deprecated. Is there a way to specify it in `cluster.spec`?
**2. Feel free to provide a design supporting your feature request.**
If it is not already supported, being able to specify it under `spec.kubeProxy` in `cluster.spec` would be good.

**Comment by olemarkus** [comment]
We would also love for this to be supported
