### ISSUE TITLE
Set roadmap for 1.5 and 1.6 releases

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#663]
Starting with this issue, but we need to start working on a roadmap for 1.5 and 1.6 releases.  Please comment on your current needs, and we will get it into a PR for a roadmap.  We will host a meetup to discuss and prioritize.

Here is the list for our first meeting:
1. ~~Private networking https://github.com/kubernetes/kops/issues/428~~ complete
2. Improve upgrades https://github.com/kubernetes/kops/issues/489 https://github.com/kubernetes/kops/issues/37 https://github.com/kubernetes/kops/issues/313 started
3. ~~CNI Networks https://github.com/kubernetes/kops/pull/621~~ complete
4. Backups and Recovery https://github.com/kubernetes/kops/issues/297 https://github.com/kubernetes/kops/issues/366
5. Improve Documentation ~~https://github.com/kubernetes/kops/issues/652~~ complete
6. ~~Improve unit testing~~ started
7. ~~Implement e2e testing harness~~ started
8. Code organization and cleanup
9. HTTP API mode - https://github.com/kubernetes/kops/issues/633
10. Improve YAML and API examples
11. ~~Setup and start using Kanban with Github~~
12. ~~Cluster Validate~~ https://github.com/kubernetes/kops/issues/588 - in but has a couple of bugs
13. Protect nodes / masters from deletion.
14. API auth-mode https://github.com/kubernetes/kops/issues/312
15. Self hosting resources https://github.com/kubernetes/kops/issues/715 https://github.com/kubernetes/kops/issues/601
16. Explicit AWS support by Kubernetes in 1.5, utilizing kops.  This encompasses more work outside this repo as well.
17. Custom tags https://github.com/kubernetes/kops/issues/729
18. ~~Process improvements, tags, PRs, the way we do stuff~~ completed
19. ~~@k8s-bot use em~~ completed
20. clean house / issues https://github.com/kubernetes/kops/issues/640
21. more demos and examples
22. ETC and other hardening https://github.com/kubernetes/kops/issues/230 https://github.com/kubernetes/kops/issues/376
23. Plugins model - kops allows for plugins
24. SSL improvements - bring your own keys https://github.com/kubernetes/kops/issues/530
25. Terminate API servers with ELB https://github.com/kubernetes/kops/issues/234
26. 1.4 / 1.5 features https://github.com/kubernetes/kops/issues/356
27. Remove addons manager, or replace as a plugin https://github.com/kubernetes/kops/issues/385
28. Autoscaling https://github.com/kubernetes/kops/issues/531
29. ~~Sizing of masters and nodes https://github.com/kubernetes/kops/issues/728~~ pretty sure this is done

**Comment by chrislovecnm** [comment]
Pretty easy request https://github.com/kubernetes/kops/issues

**Comment by jkemp101** [comment]
+1 Backups/recovery and just general disaster recovery

I would also like to see #312 added to the list to include one/both of the authorizations modes.

**Comment by chrislovecnm** [comment]
@zmerlynn any ideas?

**Comment by chrislovecnm** [comment]
@jkemp101 we already have an engineer working through the steps, and it is his desire to drop that in.

**Comment by chrislovecnm** [comment]
@jkemp101 https://github.com/kubernetes/kops/issues/312 is important to us as well as we are looking at multi-homing :rimshot

**Comment by chrislovecnm** [comment]
cc: @JuJu227 @faraazkhan

**Comment by zmerlynn** [comment]
We'd like to see explicit AWS support by Kubernetes in 1.5. In order to do that, there's a few more pieces of developer efficiency that need to be done:
* PR builder for the `kops` repo
* PR builder on the `kubernetes` repo
* Submit queue blocking build

**Comment by chrislovecnm** [comment]
Another one https://github.com/kubernetes/kops/issues/729 tags!!!

**Comment by kris-nova** [comment]
Would like to get https://github.com/kubernetes/kops/issues/640 in there tomorrow as well..

**Comment by kris-nova** [comment]
Also - would it be prudent to get issues created for the topics listed above without issues? I think it would.. @chrislovecnm thoughts?

**Comment by kris-nova** [comment]
Integration Tests? https://github.com/kubernetes/kops/issues/731

**Comment by chrislovecnm** [comment]
See Zach's comments above

**Comment by chrislovecnm** [comment]
Yaml examples and demos, @brandoncole mentioned that

**Comment by chrislovecnm** [comment]
Image road map, ami's

**Comment by kris-nova** [comment]
# Labels and Milestones

Can we start using them more? I added some new labels I would like to start using for PRs.. 

But more importantly.. milestones, and what are the thoughts there?

**Comment by chrislovecnm** [comment]
@kris-nova we need process improvements.  As we talked using github kanban is duplicated work for the Datapipe folks.

**Comment by chrislovecnm** [comment]
Another one https://github.com/kubernetes/kops/issues/471

**Comment by logicaleak** [comment]
Item 28 seems very critical to me. Absence of this feature forces us to have all the nodes k8s needs up and running, which means we have to pay for them even if we dont have traffic. Am I missing something, or with the current condition, it is very inefficient to have k8s up in aws ? Can someone enlighten me?

**Comment by yissachar** [comment]
@logicaleak It's not clear that this is something that kops needs to support vs you adding manually. See https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler for how to add it to your cluster. It's possible that in the future kops supports easy setup via a flag, but there doesn't seem to be anything stopping you from adding it yourself.

**Comment by nicolasbelanger** [comment]
+1 for Improve upgrades #489 #37 #313

**Comment by rcruzper** [comment]
It would be great if kops could manage (add/remove) addons installed on master when the cluster is created #493

**Comment by kris-nova** [comment]
@chrislovecnm @justinsb can we take this list and give this a once over? We have new versioning, and some of this needs to be updated

**Comment by chrislovecnm** [comment]
updated

**Comment by kris-nova** [comment]
@chrislovecnm - Can we update the title too? I think these versions are no longer targeted

**Comment by MilanDasek** [comment]
Guys,

I would like to ask when you plan to release kops compatible with kubernetes 1.6 (March 22nd)?
We would like to upgrade our cluster from 1.5.2 to 1.6

Thank you 

Milan
