### ISSUE TITLE
Openstack security groups needs to be open for loadbalancers

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#6631]
**1. What `kops` version are you running?** master

**2. What Kubernetes version are you running?** 1.11.7

**3. What cloud provider are you using?** openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Normal kops create cluster and after that create service with type: loadbalancer

**5. What happened after the commands executed?**
Everything is created correctly. However, the sec group in nodes is closed

So I created new cluster with newest master, everything works fine. However, when I create ingress controller and service type: loadbalancer to it. The lbaas cannot connect my nginx controller. I opened `ALL TCP` from `0.0.0.0/0` node security group and it started to work. 

@drekle do you have idea what ports we need really open? I suggest that we open those automatically when creating firewall rules. In future we should consider to start using https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L114 and I am going to make PR about that boolean flag.

/sig openstack
/kind bug
/cc @drekle

**Comment by drekle** [comment]
I believe the ingress for the node port created by the loadbalancer needs to be open to the loadbalancer port, however this is what I believe manage-security-groups is intended to do.  Openstack might assign the default security group to the load balancer port by default.
