### ISSUE TITLE
kops Certified Kubernetes status is about to expire

### ISSUE THREAD

**Issue by dankohn** [kubernetes/kops#6639]
Hello Kubernetes Kops Project team,

We’re very pleased that your product was included in our v1.10 Certified Kubernetes offerings. However, unless you have acquired a newer certification for your product, kops, your Kubernetes v1.10 certification will expire on March 27, 2019.  

As stated in Certified Kubernetes Conformance Program – [Terms and Conditions](https://github.com/cncf/k8s-conformance/blob/master/terms-conditions/Certified_Kubernetes_Terms.md#qualifying-offerings-and-self-testing), a Participant’s permission to use the Certified Kubernetes Marks and Participant Kubernetes Combinations with its Qualifying Offerings is time-limited. The Certified Kubernetes Marks and Participant Kubernetes Combinations may be used with a Qualifying Offering for a particular version of Kubernetes (e.g., Kubernetes x.y) until the later of:
12 months after the release date of Kubernetes x.y, or

9 months after the release date of the next minor release (e.g., Kubernetes x.y+1)

1.10.0 was released on March 26, 2018
https://github.com/kubernetes/kubernetes/releases/tag/v1.10.0

1.11.0 was released on June 27, 2018
https://github.com/kubernetes/kubernetes/releases/tag/v1.11.0

Therefore, the later of the two is March 27, 2019.

Please make sure to certify your product for Kubernetes v1.11, v1.12, or v1.13 prior to March 27, in order to have your v1.10 certification remain in effect.  Please note that once Kubernetes v1.14 is released in late March, we will only be able to accept v1.12, v1.13, or v1.14 results. We will not be certifying for v1.11 after v1.14 is released, per these guidelines.  

To view all Certified Kubernetes Distributions & Platforms, please follow this link:
https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es

If you have any questions, please don’t hesitate to reach out.

Cc @justinsb  @taylorwaggoner

**Comment by chrisz100** [comment]
/assign 

I'll upload it later today, thank you for the reminder @dankohn !

**Comment by chrisz100** [comment]
All done, thanks to everyone involved! 
/close
