### ISSUE TITLE
Kops builds are failing - maybe missing/invalid creds?

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#664]
The kops build has been failing for some time now. Can we look into what is going on and possibly get a solution out?

Example failure : 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kops-build/133

@zmerlynn maybe you can shed some light here?

**Comment by zmerlynn** [comment]
Well, crap. Sorry for not noticing it, that build isn't emailing me. I'll fix that part, too.

**Comment by chrislovecnm** [comment]
@zmerlynn thanks amigo!

**Comment by zmerlynn** [comment]
I "fixed" this by adding `661044217466-compute@developer.gserviceaccount.com:W` to the gs://kops-ci bucket. I think there's a real issue here, though: That service account should now be deletable from `gs://kubernetes-release-dev` as well, but, if I'm looking at all the permissions groups correctly, it looks like any attempt to do that would suffer a similar fate to this. The `kops-build` job very clearly activates `kubekins@kubernetes-jenkins.iam.gserviceaccount.com`, but (possibly because it's running in a container?) the job can't upload to GCS using those creds.

cc @kubernetes/test-infra-maintainers

**Comment by zmerlynn** [comment]
For reference, here are the last two builds. The only difference between these is that, behind the scenes, I did:
```
gsutil acl ch -u 661044217466-compute@developer.gserviceaccount.com:W gs://kops-ci
```

Success: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kops-build/135
Fail: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kops-build/134

**Comment by ixdy** [comment]
@spxtr

**Comment by zmerlynn** [comment]
FWIW, this entirely could be a difference in `kops-build` vs `kubernetes-build`, but I've been looking over each and I don't see what that would be (except for minor differences in `workspace-cleanup`).

**Comment by zmerlynn** [comment]
Yeah, I logged auth info in #667 and the service account isn't active at all:
```
gcloud auth list
Credentialed Accounts:
 - 661044217466-compute@developer.gserviceaccount.com ACTIVE
To set the active account, run:
    $ gcloud config set account `ACCOUNT`
```

**Comment by zmerlynn** [comment]
I think I know what's going on:

```[kops-build] $ /bin/bash -xe /tmp/hudson896273924496026422.sh
+ export HOME=/var/lib/jenkins/workspace/kops-build
+ HOME=/var/lib/jenkins/workspace/kops-build
+ export CLOUDSDK_CONFIG=/var/lib/jenkins/workspace/kops-build/.config/gcloud
+ CLOUDSDK_CONFIG=/var/lib/jenkins/workspace/kops-build/.config/gcloud
+ gcloud auth activate-service-account '--key-file=/var/lib/jenkins/workspace/kops-build@tmp/secretFiles/1517ed9c-4266-43ba-ba8a-4b3be62690b1/Kubernetes Jenkins Builds-2768d85b19b4.json'
Activated service account credentials for: [kubekins@kubernetes-jenkins.iam.gserviceaccount.com]
[kops-build] $ /bin/bash -xe /tmp/hudson974965852073779520.sh
+ export GCS_LOCATION=gs://kops-ci/bin
+ GCS_LOCATION=gs://kops-ci/bin
+ timeout -k 15m 20m make gcs-publish-ci
```

The `CLOUDSDK_CONFIG` export here is useless, since it immediately swaps shells. Put up #669 to confirm.

**Comment by zmerlynn** [comment]
Yeah, confirmed:
```
== Logging gcloud info ==
Google Cloud SDK [130.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.9 (default, Jun 29 2016, 13:08:31)  [GCC 4.9.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/usr/lib/google-cloud-sdk]
Installed Components:
  core: [2016.10.07]
  core-nix: [2016.10.07]
  gcloud: []
  gsutil-nix: [4.21]
  beta: [2016.10.07]
  gsutil: [4.21]
  bq: [2.0.24]
  alpha: [2016.10.07]
  bq-nix: [2.0.24]
System PATH: [/usr/local/bin:/usr/bin:/bin:/usr/games]
Cloud SDK on PATH: [False]

Installation Properties: [/usr/lib/google-cloud-sdk/properties]
User Config Directory: [/home/jenkins/.config/gcloud]
Active Configuration Name: [default]
Active Configuration Path: [/home/jenkins/.config/gcloud/configurations/config_default]

Account: [661044217466-compute@developer.gserviceaccount.com]
Project: [kubernetes-jenkins]

Current Properties:
  [core]
    project: [kubernetes-jenkins]
    account: [661044217466-compute@developer.gserviceaccount.com]
    disable_usage_reporting: [True]

Logs Directory: [/home/jenkins/.config/gcloud/logs]
Last Log File: [/home/jenkins/.config/gcloud/logs/2016.09.27/19.18.11.206222.log]
```
