### ISSUE TITLE
Sync config with S3

### ISSUE THREAD

**Issue by ajouve** [kubernetes/kops#6653]
Hi,

I made this tutorial https://github.com/kubernetes/kops/blob/master/docs/aws.md and my cluster is working perfectly 

I only have one issue, in case of backup.
The tutorial ask to create a bucket like s3://prefix-example-com-state-store to push the config.
I have the bucket, aws-cli can access it.
But the bucket is empty

I am running 

```bash
kops edit cluster ${NAME}
```

```bash
kops update cluster ${NAME} --yes
```

```bash
kops edit ig nodes
```

But none of them is pushing any file into my bucket, everything seems to be managed in local 
The issue could be that my cluster name is `myname.k8s.local` is there any way to update it ?

Kind regards

**Comment by Smirl** [comment]
Hello, I might be able to help.

The way `kops` works is to update the config in the state store when you run `create`, `replace`, or `edit`. The `kops update` command then modifies the cloud resources (think launch configurations, etc.). `kops rolling-update cluster` will terminate instances in order so they pick up the new changes. When they start, they read the cluster config, certificates, addons, etc. from the state store.

Therefore, the state store that you cluster is pointing at must have good config. You can see the state store your cluster is pointing at in the cluster config file under `spec.configBase`.

When you run kops commands ensure that you have the environment variable `KOPS_STATE_STORE` set to your s3 bucket, or pass `--state s3://bucket-name` with every command.

Hope this helps you work with `kops`.
