### ISSUE TITLE
Addons are not removed from cluster when removed from Cluster template

### ISSUE THREAD

**Issue by andre-taveira** [kubernetes/kops#6656]
**1. What kops version are you running?**
Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running?**
1.11.6

**3. What cloud provider are you using?**
aws

**4. What commands did you run? What is the simplest way to reproduce this issue?**

I create a cluster from template file specifying these addons:

```
spec:
  addons:
    - manifest: kubernetes-dashboard
    - manifest: metrics-server
```

The cluster is created from a script I created using these commands:

```
        log "[1/3] Creating Cluster from from "$2" "
        generate_keys
        kops create -f "$2"
        log "[2/3] Deploying SSH access keys..."
        kops create secret --name "${NAME}" sshpublickey admin -i "${NAME}.pub"
        log "[3/3] Updating cluster state..."
        kops update cluster "${NAME}" --yes
```

The cluster is created successfully with the related addons. Later on I added another addon (- manifest: prometheus-operator) and updated the cluster using the cluster template:

```
        kops replace -f $2
        kops update cluster ${NAME} --yes
        health_check
        log "Running Rolling Update against cluster - ${NAME}"
        kops rolling-update cluster ${NAME} --master-interval=2m --yes
```
On the final step I removed the last addon i added (prometheus) and apply the same update commands from above.

5. What happened after the commands executed?

After removing the addon and applying the rolling update the addon is not removed.

**Anyone with a similar experience ? Is this a limitation from Kops ?**

**Comment by rifelpet** [comment]
Related: #5697
