### ISSUE TITLE
Deleting a cluster should delete the kubectl context for the cluster

### ISSUE THREAD

**Issue by mrichmon** [kubernetes/kops#666]
I have multiple kops managed clusters. When I delete a cluster using "kops delete cluster", it should clean up kubectl by removing the kubectl context for the deleted cluster.

**Comment by chrislovecnm** [comment]
@mrichmon I am really trying not to make a comment about the issue number.  I will add this to our roadmap issue

**Comment by mrichmon** [comment]
@chrislovecnm Heh. This issue number was a missed opportunity.

**Comment by kris-nova** [comment]
@chrislovecnm - Are we tracking the roadmap anywhere?

**Comment by yissachar** [comment]
I believe https://github.com/kubernetes/kops/issues/287 is the same issue.

**Comment by chrislovecnm** [comment]
@mrichmon closing in favor of the other number ;)
