### ISSUE TITLE
Clarify DNS usage

### ISSUE THREAD

**Issue by trondhindenes** [kubernetes/kops#6661]
We're working on transitioning from a homegrown Kubernetes provisioning system to Kops. In the documentation https://github.com/kubernetes/kops/blob/master/docs/aws.md#configure-dns there isn't any description of what DNS is used for. Is this for auto-publishing ingresses, or is DNS used for worker-to-worker and controlplane-to-node name resolution in the cluster?

There is a mention of "gossip-based cluster", but I can't find any definition for that.

I'm unable to make the right design decisions based on the current documentation.

**Comment by olemarkus** [comment]
DNS is primarily used for nodes to discover the masters. There are some details about gossip discovery explained here https://github.com/kubernetes/kops/issues/2858#issuecomment-315422011

**Comment by tomekit** [comment]
Having similar problem with lack of clarity regarding DNS/Route53.
Given that I run gossip-based cluster and want to expose IP's of my nodes (I am using Cluster IP Ingress) over Route 53.
What component should I use?
