### ISSUE TITLE
Cannot create a Persistent Volume Claim in Centos 7 (unable to find root CA certificates)

### ISSUE THREAD

**Issue by austinmoore-** [kubernetes/kops#668]
With Centos 7, I am unable to create a Persistent Volume Claim because kube-controller-manager (I think) cannot find system roots. 

```
$ kubectl describe pvc
Name:       jenkins-home
Namespace:  default
Status:     Pending
Volume:
Labels:     <none>
Capacity:
Access Modes:
Events:
  FirstSeen LastSeen    Count   From                SubObjectPath   Type        Reason          Message
  --------- --------    -----   ----                -------------   --------    ------          -------
  14s       14s     1   {persistentvolume-controller }          Warning     ProvisioningFailed  Error creating provisioned PV object for claim default/jenkins-home: persistentvolumes "pvc-e0171502-94ab-11e6-81f0-0a633eeb4905" is forbidden: error querying AWS EBS volume aws://us-west-2b/vol-4eb525c6: error finding instance i-2649d23e: error listing AWS instances: RequestError: send request failed
caused by: Post https://ec2.us-west-2.amazonaws.com/: x509: failed to load system roots and no roots provided. Deleting the volume.
```

On Centos 7, the root CA certificates are installed in the `/etc/pki/tls/certs` directory. `/etc/ssl/certs` is symlinked to this directory. Inside that directory there is a `ca-bundle.crt` and a `ca-bundle.trust.crt`.

If I `exec` into the kube-controller-manager container, I am able to see the certs under that directory. On the host, I am able to successfully run `openssl s_client -connect ec2.us-west-2.amazonaws.com:443` and see that it connects.

Last I checked, creating a Persistent Volume Claim works on the Debian "jessie" image that kops uses by default.

I was hoping to pinpoint the problem before opening an issue, but I can't find anything. I'm not even sure why kube-controller-manager is struggling to find the system CA roots when they exist within the container.

Looking for some help. Thanks!

_Also, if this is an issue with Kubernetes rather than kops, I'll be happy to move the issue. I opened it here first because because AFAIK nodeup is what drops the manifests and starts up kube-controller-manager._

**Comment by justinsb** [comment]
It's definitely a kops issue... it's to do with the paths for the CA certificates an mounting them.  I actually thought this was fixed - I'll track down the change!

**Comment by austinmoore-** [comment]
Thanks!

**Comment by justinsb** [comment]
Sorry it took me so long to get to this.  The issue is the apiserver calls out to the AWS API in one place - when labelling a volume with zone information.  But apiserver didn't have /etc/pki/ca-trust mounted - I think I removed it before we were targeting RHEL/CentOS.
