### ISSUE TITLE
Support Matrix

### ISSUE THREAD

**Issue by Sluggerman** [kubernetes/kops#6683]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Documentation request!
Not sure if this already exists, at least I could not find it within Kops docs, but I am after some sort of support/compatibility matrix with combination of supported versions for different building blocks for Kops
**2. Feel free to provide a design supporting your feature request.**
So I would suggest starting off with something like (in context of AWS):
|| KOPS VERSION || K8S VERSION || ETCD VERSION || CNI || CNI VERSION || EC2 AMI || EC2 TYPE ||

**Comment by peturgq** [comment]
I also think this is a crucial missing component of the kops documentation.

**Comment by mikesplain** [comment]
This exists [here](https://kops.sigs.k8s.io/welcome/releases/#compatibility-matrix) and on our readme. 

Thanks!

/close
