### ISSUE TITLE
KOPS 1.12.alpha2 etcd-manager bug

### ISSUE THREAD

**Issue by granular-ryanbonham** [kubernetes/kops#6699]
I upgraded out test cluster with kops 1.12-alpha2 yesterday. We are running K8s 1.12.6, which is same version we were running with kops 1.11.

Today i went to upgrade K8s to 1.12.7, when i applied the change and the cluster started to roll the first master that rolled, master-us-east-1d.masters.XXXX.com,  it will not come online. Looking at logs I see the following in the etcd main logs on the new master

"2019-03-28 16:21:31.388268 W | rafthttp: health check for peer 903e90f54424945d could not connect: EOF\n"

That peer is the etcd master node. when i look at the logs from that etcd node i see the following. 

etcdmain: rejected connection from \"10.39.20.132:34154\" (error \"tls: \\\"10.39.20.132\\\" does not match any of DNSNames [\\\"etcd-d.internal.XXXX.com\\\"] (lookup etcd-d.interna.XXXX.com on 10.39.0.2:53: no such host)\", ServerName \"etcd-b.internal.XXXX.com\", IPAddresses [\"127.0.0.1\"], DNSNames [\"etcd-d.internal.XXXX.com\"])\n","stream":"stdout","time":"2019-03-28T16:23:52.636085472Z"}

**Comment by mikesplain** [comment]
Thanks @granular-ryanbonham! Can you try 1.12.0-alpha.3? I'm still running into some issues with it but it worked much better for me.

**Comment by granular-ryanbonham** [comment]
Have not been able to duplicate in alpha3.

**Comment by granular-ryanbonham** [comment]
@justinsb Hitting this with upgrade from beta 1 to beta 2. 1 kops master (running 3 masters) is terminated as part of rolling update. When it comes back online it is not able to join cluster. 

ETCD Master shows....

{"log":"2019-04-15 17:33:52.856263 I | etcdmain: rejected connection from \"10.39.14.199:33868\" (error \"tls: \\\"10.39.14.199\\\" does not match any of DNSNames [\\\"etcd-b.internal.cluster.XXX.com\\\"] (lookup etcd-b.internal.cluster.XXX.com on 10.39.0.2:53: no such host)\", ServerName \"etcd-d.internal.cluster.XXX.com\", IPAddresses [\"127.0.0.1\"], DNSNames [\"etcd-b.internal.cluster.XXX.com\"])\n","stream":"stdout","time":"2019-04-15T17:33:52.859214369Z"}

**Comment by granular-ryanbonham** [comment]
Caused by corrupted /etc/hosts file. 

This PR to etcd-manager should fix and ensure we only write valid files... 

https://github.com/kopeio/etcd-manager/pull/199

**Comment by jhlav** [comment]
Based on the latest commits to master here and in etcd-manager, this can be closed, right?  @justinsb

**Comment by granular-ryanbonham** [comment]
Closing, this has been fixed for 1.12.0.
