### ISSUE TITLE
Import Cluster not working with HA master

### ISSUE THREAD

**Issue by kilpatty** [kubernetes/kops#67]
Currently I believe that Import Cluster is not working with HA masters.
Command: kops import cluster --v=8 --region=us-west-2 --name=${NAME} --state=${KOPS_STATE_STORE}
Output: 
`I0706 12:06:36.953211   71665 context.go:131] Found bucket "redacted" in region "us-west-2"
I0706 12:06:37.689813   71665 s3fs.go:169] Listed files in s3://redacted/redacted/pki/issued/ca: [s3://redacted/redacted/pki/issued/ca/6303889741236192579705609245.crt]
I0706 12:06:37.689862   71665 s3fs.go:120] Reading file "s3://redacted/redacted/pki/issued/ca/6303889741236192579705609245.crt"
I0706 12:06:37.764648   71665 ca.go:288] Parsing pem block: "CERTIFICATE"
I0706 12:06:37.815254   71665 s3fs.go:169] Listed files in s3://redacted/redacted/pki/private/ca: [s3://redacted/redacted/pki/private/ca/6303889741236192579705609245.key]
I0706 12:06:37.815298   71665 s3fs.go:120] Reading file "s3://redacted/redacted/pki/private/ca/6303889741236192579705609245.key"
I0706 12:06:37.888631   71665 ca.go:306] Parsing pem block: "RSA PRIVATE KEY"
I0706 12:06:37.890916   71665 import_cluster.go:499] Querying EC2 instances
F0706 12:06:38.134138   71665 import_cluster.go:26] could not find master node`

**Comment by Skilgarriff** [comment]
Confusion on wording of commands - This is working as intended.

**Comment by YoniTapingo** [comment]
@kilpatty Could you please elaborate on what the confusion was? i'm hitting the same issue.
