### ISSUE TITLE
How can I change the default internal dns suffix of cluster.local?

### ISSUE THREAD

**Issue by bjethwan** [kubernetes/kops#6715]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:40:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster

**5. What happened after the commands executed?**
cluster got created but "kops create cluster --help" didn't tell any option to change the default cluster.local

**9. Anything else do we need to know?**
I am using CoreDNS

**Comment by justinsb** [comment]
Honestly, I don't know how well tested it is.  But `kops create cluster` creates the kubernetes objects (cluster, instancegroups) but doesn't create the cloud objects themselves.  So after you do `kops create cluster` and before you do `kops update cluster` you can `kops edit cluster` to set more fields.  

Then there is an option `clusterDNSDomain` which defaults to `cluster.local` but which you could set to an alternative value.  https://github.com/kubernetes/kops/blob/017c5ef15a7160f697e9d56c0bcaa2b8a6ec3380/pkg/apis/kops/cluster.go#L100

It isn't really documented so it won't be very heavily tested; it is a string field that is immediately underneath `spec`.

A tip: If you want to see the cluster with all the default values set, you can use `-full`.  For example `kops get cluster --full -oyaml example.k8s.local`.  That may be handy for verification at least.

**Comment by lshahar** [comment]
Someone has tested the changing of cluster suffix after the cluster is up and running? 
There is any way to create the cluster with customer suffix?
