### ISSUE TITLE
"kops create cluster --cloud=aws --dns ${var.kops_dns_mode} --authorization RBAC --networking ${var.kubernetes_networking} --zones=${join(",", data.aws_availability_zones.available.names)} --node-count=${var.node_asg_desired} --master-zones=${local.master_azs}--node-count=3 --node-size=t2.medium --master-size=t2.medium --bastion=true --topology private --target=terraform --api-loadbalancer-type=public --vpc=${var.vpc_id} --state=s3://${var.kops_s3_bucket_id} --kubernetes-version ${var.kubernetes_version} ${local.cluster_fqdn}"   } cluster cannot span multiple regions .

### ISSUE THREAD

**Issue by bhagyashreemohan** [kubernetes/kops#6716]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

**3. What cloud provider are you using?**

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by bhagyashreemohan** [comment]
resource "aws_key_pair" "terraform_ec2_key"{
key_name ="default-key"
public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxrDp2gL7dKurR1Ts2sS8U937tJX4nUTo9aHKwAUvwPcNnnh24wxpoWfreh9EOp9TtbuYIBUyIPvwkML+lUca9Xn857piYg2hqbj6KgsY3HxliAvN0eo158RYZMacabrlNK6YUSk69JqsilfOVgSqbjRoZHZ6K95Feh7jwtl43YUaN2azQk5XV+tGvyn2KZSgJ1oWnCAcXyA1dywTMoQhQ5XIQk3OeYMsY/5+e+Q6S6+wAJ/4qu2ZpCzFpuIkQSKp9l+QBNj4MvDg4X7LkaIuBNt11gy62cYruMqGfxlT+RPecm/G7vDNmycWZHMQgxjlVcfKlD/q5bob8QLpucv1N ec2-user@ip-172-31-0-157.us-west-1.compute.internal"
}
resource "null_resource" "check_kops_version" {
  provisioner "local-exec" {
    command = "kops version | grep -q ${local.supported_kops_version} || echo 'Unsupported kops version. Version ${local.supported_kops_version} must be used'"
  }
}

resource "null_resource" "create_cluster" {
  depends_on = ["null_resource.check_kops_version"]

  provisioner "local-exec" {
    command = "kops create cluster --cloud=aws --dns ${var.kops_dns_mode} --authorization RBAC --networking ${var.kubernetes_networking} --zones=${join(",", data.aws_availability_zones.available.names)} --node-count=${var.node_asg_desired} --master-zones=${local.master_azs}--node-count=3 --node-size=t2.medium --master-size=t2.medium --bastion=true --topology private --target=terraform --api-loadbalancer-type=public --vpc=${var.vpc_id} --state=s3://${var.kops_s3_bucket_id} --kubernetes-version ${var.kubernetes_version} ${local.cluster_fqdn}"
  }

  provisioner "local-exec" {
    when    = "destroy"
    command = "kops delete cluster --yes --state=s3://${var.kops_s3_bucket_id} --unregister ${local.cluster_fqdn}"
  }
}

resource "null_resource" "delete_tf_files" {
  depends_on = ["null_resource.create_cluster"]

  provisioner "local-exec" {
    command = "rm -rf out"
  }
}
~
~

**Comment by justinsb** [comment]
Which zones are you trying to run in?  It sounds like you're trying to run in zones from more than one region, which we block.  It's theoretically possible, but kubernetes really assumes that the nodes are not "too far" away from each other (e.g. it isn't particularly topology aware when it comes to networking, though see e.g. https://github.com/kubernetes/enhancements/pull/640 for work on this)

**Comment by bhagyashreemohan** [comment]
I run in us east 1 with same AZ but it's not picking up with terraform
