### ISSUE TITLE
reload `aws-iam-authenticator` process when `ConfigMap` update

### ISSUE THREAD

**Issue by eng-parthesh** [kubernetes/kops#6729]
### Issue
When we update the `ConfigMap` then we have to do the manually deletion of the pod.

### Solution
add extra container which look for change into `ConfigMap` and reload the config.

**Comment by eng-parthesh** [comment]
sig/bug

**Comment by rdrgmnzs** [comment]
Hi @eng-parthesh, for this one I think you should open a bug with https://github.com/kubernetes-sigs/aws-iam-authenticator the application it self should support hot reloading of the config. Having something external trying to force a reload would add quite a bit of complexity and would be very error prone.
