### ISSUE TITLE
kops cannot locate s3 bucket [us-east-2]

### ISSUE THREAD

**Issue by ajs11174** [kubernetes/kops#6738]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.11.1 (git-0f2aa8d30)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client: 1.13.4
Server not currently running

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops edit ig nodes -v 10

**5. What happened after the commands executed?**

an error message that says that kops is unable to list AWS regions

**6. What did you expect to happen?**

I expected that I would be able to edit the number of instances in my IG

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Unfortunately, kops cannot access the s3 bucket (I get the same error).

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
:white_check_mark:

**9. Anything else do we need to know?**

1. My `KOPS_STATE_STORE` is located in AWS region us-east-2
2. I have been learning kubernetes and have been completely shutting down the cluster at night by editing the number of instances in each IG to 0. 
3. Running commands from ubuntu on windows and kops has worked perfectly for the past month. 
4. Here is the output from the command
```shell
root@DESKTOP:~/.kube# kops edit ig nodes -v 10

I0405 22:42:17.651545    1532 loader.go:359] Config loaded from file /root/.kube/config
Using cluster from kubectl context: cluster.mysite.com

I0405 22:42:17.652279    1532 factory.go:68] state store s3://my-state-store
I0405 22:42:17.655118    1532 s3context.go:175] unable to get bucket location from region "us-east-1"; scanning all regions: RequestError: send request failed
caused by: Get https://s3.amazonaws.com/my-state-store?location=: dial tcp: i/o timeout
```

**Comment by ajs11174** [comment]
Update. I tried again this morning and everything seems to be working as expected. I was able to make changes to my cluster and update it. Is it possible this is an issue with AWS?

**Comment by justinsb** [comment]
This does sound like an issue with either AWS or with your DNS / network connection, based on `Get https://s3.amazonaws.com/my-state-store?location=: dial tcp: i/o timeout`

Did this happen repeatedly or did it just happen once?

**Comment by ajs11174** [comment]
This happened repeatedly over the course of several hours until I gave up and then it started working the next day. I do agree that this is likely not an issue with kops as it is now working and I haven't changed my kops installation.
