### ISSUE TITLE
Kops 1.10 can not set etcd provider for etcd-manager, getting unhandled field

### ISSUE THREAD

**Issue by igoratencompass** [kubernetes/kops#6749]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.1 (git-a67edea6d)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.10.10

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Following https://github.com/kubernetes/kops/blob/master/docs/etcd/manager.md I get the error below:
```
$ export KOPS_FEATURE_FLAGS=SpecOverrideFlag
$ kops set cluster cluster.spec.etcdClusters[*].provider=Manager
Using cluster from kubectl context: blabla

unhandled field: "cluster.spec.etcdClusters[*].provider=Manager"
```

**5. What happened after the commands executed?**

**6. What did you expect to happen?**
The setting `provider: Manager` to get added to the etcd yaml

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
$ kops -v 10 set cluster cluster.spec.etcdClusters[*].provider=Manager --name=cluster
I0408 10:11:06.101361   18147 factory.go:68] state store s3://bucket
I0408 10:11:07.257072   18147 s3context.go:198] Checking default bucket encryption "bucket"
I0408 10:11:07.257114   18147 s3context.go:203] Calling S3 GetBucketEncryption Bucket="bucket"
I0408 10:11:08.651661   18147 s3context.go:210] Unable to read bucket encryption policy: will encrypt using AES256
I0408 10:11:08.652139   18147 s3context.go:182] Found bucket "bucket" in region "eu-west-1" with default encryption set to false
I0408 10:11:08.652168   18147 s3fs.go:219] Reading file "s3://bucket/cluster/config"
I0408 10:11:09.031622   18147 s3fs.go:256] Listing objects in S3 bucket "bucket" with prefix "cluster/instancegroup/"
I0408 10:11:09.444928   18147 s3fs.go:284] Listed files in s3://bucket/cluster/instancegroup: [s3://bucket/cluster/instancegroup/master-eu-west-1a s3://bucket/cluster/instancegroup/master-eu-west-1b s3://bucket/cluster/instancegroup/master-eu-west-1c s3://bucket/cluster/instancegroup/nodes]
I0408 10:11:09.445019   18147 s3fs.go:219] Reading file "s3://bucket/cluster/instancegroup/master-eu-west-1a"
I0408 10:11:09.874782   18147 s3fs.go:219] Reading file "s3://bucket/cluster/instancegroup/master-eu-west-1b"
I0408 10:11:10.223352   18147 s3fs.go:219] Reading file "s3://bucket/cluster/instancegroup/master-eu-west-1c"
I0408 10:11:10.580904   18147 s3fs.go:219] Reading file "s3://bucket/cluster/instancegroup/nodes"

unhandled field: "cluster.spec.etcdClusters[*].provider=Manager"
```
**9. Anything else do we need to know?**
In case this should work with newer kops and/or k8s versions please update the etcd-manager page accordingly.

**Comment by zemek** [comment]
seems like it's different for 1.10
https://github.com/kubernetes/kops/blob/release-1.10/docs/etcd/manager.md

```
# Enable etcd-manager
kops set cluster cluster.spec.etcdClusters[*].manager.image=kopeio/etcd-manager:latest
```

**Comment by igoratencompass** [comment]
Thanks @zemek I have missed that doco.
