### ISSUE TITLE
Rolling Update not rolling spot instances

### ISSUE THREAD

**Issue by granular-ryanbonham** [kubernetes/kops#6751]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops-1.12-beta.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.12.7

**3. What cloud provider are you using?**

AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops rolling-update cluster

**5. What happened after the commands executed?**

On Demand Instances were rolled, but spot instances were not.

**6. What did you expect to happen?**

All Instances to roll

**9. Anything else do we need to know?**

Had previously migrated cluster to use Mixed Instance Policy using a custom build of kops 1.12 alpha 3 including PR https://github.com/kubernetes/kops/pull/6732.

After release of beta 3, i updated cluster. Terraform plan shows changes to each IGs aws_launch_template. However The rolling-update output shows only some of the instnaces per IG need updates. 

2019-04-08 00:34:39 ip-10-39-253-74 K8ClusterLaunch[1435] INFO NAME			STATUS		NEEDUPDATE	READY	MIN	MAX	NODES
master-us-east-1b	NeedsUpdate	1		0	1	1	1
master-us-east-1c	NeedsUpdate	1		0	1	1	1
master-us-east-1d	NeedsUpdate	1		0	1	1	1
nodes			Ready		0		0	0	0	0
nodes-us-east-1b	Ready		0		2	2	100	2
nodes-us-east-1c	NeedsUpdate	1		1	2	100	2
nodes-us-east-1d	NeedsUpdate	1		1	2	100	2

The nodes that did not update are all spot instances. 

I think the issues may be that findAutoscalingGroupLaunchConfiguration() is only comparing LaunchTemplateName and needs to also compare Version.

**Comment by granular-ryanbonham** [comment]
@justinsb  @rdrgmnzs   This should probably block next beta/final 1.12

**Comment by nickshatilo** [comment]
@granular-ryanbonham I am getting the same issue.

**Comment by justinsb** [comment]
Did #6753 end up fixing this issue @granular-ryanbonham ?

**Comment by granular-ryanbonham** [comment]
yes. This is fixed and was cherry picked into 1.12. Mixed Instance Policies with terraform output is working well. I have tested migrating to mixed instance policies and migrating back off.

**Comment by justinsb** [comment]
Great - will close this, and release 1.12.0-beta.2 :-)
