### ISSUE TITLE
can't act as leader for unknown etcd version "3.2.26" kops 1.12.0-beta.1

### ISSUE THREAD

**Issue by den-is** [kubernetes/kops#6756]
AWS
kops 1.12.0-beta.1
k8s 1.12.7

that is sad that max supported version of etcd by that "etcd-manager" is 3.2.24.
https://github.com/kopeio/etcd-manager/blob/master/images/BUILD#L48

kops 1.11 was working fine with 3.2.26 which is in official k8s registry
https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/etcd?gcrImageListsize=30

I sincerely want to urge you to upgrade max supported version of that vital and crucial component of k8s to 3.2.26!

etcd-manager seems to be really constraining and hardcoded solution. Even though I of course appreciate hard work which was done to make this project real.

Output from etcd-manager main container:
```
W0408 19:27:44.357914    6785 controller.go:1008] we don't support etcd version requested, won't assume forward compatability: member_count:3 etcd_version:"3.2.26"
W0408 19:27:44.357939    6785 controller.go:149] unexpected error running etcd cluster reconciliation loop: can't act as leader for unknown etcd version "3.2.26"
```

P.S.: Not saying that I'm ready to run my cluster on v3.3 branch of etcd (same as on my on-prem clusters)

**Comment by mazzy89** [comment]
Same here. I've run etcd 3.3.10 and unfortunately I can't run etcd-manager so I had to use the `Legacy` configuration. Not sure if we create a bundle with etcd binaries for 3.x, etcd-manager will work smooth. We need the advice

**Comment by mazzy89** [comment]
Could you advice here @justinsb please?

**Comment by tavisma** [comment]
We've also deployed all our clusters with 3.2.26 so this would be an issue when we go to upgrade to the new kops

**Comment by Deshke** [comment]
any progres?
