### ISSUE TITLE
Add access logs config to bastion elb

### ISSUE THREAD

**Issue by romoy** [kubernetes/kops#6761]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
For the bastion elb, add the ability to configure the access log s3 bucket.

**2. Feel free to provide a design supporting your feature request.**
I would follow the same pattern that expose the idleTimeout in the cluster spec.

**Comment by msiuts** [comment]
That would be great for all ELBs managed by kops imho. Or did I miss this feature?
