### ISSUE TITLE
Tag all AWS resources with kubernetes.io/cluster tag

### ISSUE THREAD

**Issue by Nuru** [kubernetes/kops#6775]
It is possible that this feature was already approved and this is a bug fix request, but on the chance that this was intended behavior, I am filing this as a feature request.

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
In #4035 `kops` got started on a path of tagging everything, but do so using the old `KubernetesCluster` tag.

Starting in 2016, kubernetes moved away from using the `KubernetesCluster` tag to tag resources on AWS to using a tag that included the cluster name in the tag name, and using the value to indicate whether the resource was owned by the cluster or shared, e.g. `"kubernetes.io/cluster/clustername.example.com" = "owned"` See https://github.com/kubernetes/kubernetes/issues/35052 among others. This was, in part, to allow multiple clusters to tag the same resource without conflict. 

Currently (version 1.12.0-beta.1) `kops` is tagging most things with the `kubernetes.io/cluster` tag, but not everything. While there is disagreement about when to tag shared resources (See #6771), can we at least agree that whenever `kops` does tag resources, it should use the current tag naming convention?

Example: AWS EC2 instances are tagged with tags named `KubernetesCluster` but not with `kubernetes.io/cluster/<clustername> = "owned"`. 

_Almost_ everything is getting the `kubernetes.io/cluster` tag, so please close the gap and make it officially easy to find resources by cluster by always using the same tag.

**Comment by zetaab** [comment]
all resources does not support tags, for instance route53 records.

**Comment by Nuru** [comment]
@zetaab Of course I am not suggesting that `kops` tag resources that cannot be tagged. AFAIK `kops` is tagging all resources it creates that can be tagged, but not necessarily with the `kubernetes.io/cluster`. My request is 2 part:
1. Ensure that all resources that are currently being tagged are tagged with the `kubernetes.io/cluster` tag.
1. For all resources that can be tagged and are considered by `kops` as part of the cluster or cluster infrastructure, tag them with the `kubernetes.io/cluster` tag.

Neither of the above are being done today. I believe request (1) is uncontroversial and is only not being done due to some kind of oversight. I know request (2) is controversial, but I think it should be the default, with an option to disable tags for shared resources for those who prefer that.

**Comment by Nuru** [comment]
Even still in `kops` 1.14.0, EC2 instances are being tagged with `KubernetesCluster` and not with "kubernetes.io/cluster/clustername.example.com" = "owned".

/remove-lifecycle stale

**Comment by jrcasso** [comment]
This issue should now be closed; resources are now being tagged per @Nuru's request.

**Comment by olemarkus** [comment]
Thanks for that reminder
