### ISSUE TITLE
kops should remove `Initializers` for kubernetes version greater than 1.10

### ISSUE THREAD

**Issue by bilalyasar** [kubernetes/kops#6782]
as i can see from here https://github.com/kubernetes/kops/blob/master/pkg/model/components/apiserver.go#L260
kops uses `Initializers` , but kubernetes 1.10 doesn't have this flag:

https://github.com/kubernetes/kubernetes/blob/v1.10.0/cmd/kubeadm/app/phases/controlplane/manifests.go#L48

Kubernetes removed `Initializers` with this pull request: https://github.com/kubernetes/kubernetes/pull/58428/files

kops also shouldn't usee this flag for 1.10.

currently i am getting following errors in my kube-audit logs:

```
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2019-04-15T14:10:10Z"},"level":"Request","timestamp":"2019-04-
15T14:10:10Z","auditID":"8d49bb25-87a2-4e44-a2e6-
b4216fb2191f","stage":"ResponseComplete","requestURI":"/apis/admissionregistration.k8s.io
/v1alpha1/initializerconfigurations","verb":"list","user":
{"username":"system:apiserver","uid":"1b4cdf28-65b7-42ba-a541-
61db4acd853c","groups":["system:masters"]},"sourceIPs":["127.0.0.1"],"objectRef":
{"resource":"initializerconfigurations","apiGroup":"admissionregistration.k8s.io","apiVersion":"v1alpha1"},"responseStatus":{"kind":"Status","apiVersion":"v1","metadata":
{},"status":"Failure","message":"the server could not find the requested 
resource","reason":"NotFound","details":{},"code":404},"requestReceivedTimestamp":"2019-04-15T14:10:10.328233Z","stageTimestamp":"2019-04-15T14:10:10.328470Z"}
```

**Comment by benmoss** [comment]
With 1.14.1 I am getting `error: enable-admission-plugins plugin "Initializers" is unknown`

**Comment by benmoss** [comment]
I think this was already done here: https://github.com/kubernetes/kops/pull/6350. Just need to upgrade to 1.12 or greater, unfortunately there's not been a stable release for a while it seems
