### ISSUE TITLE
Enable proxy-protocol on kube-apiserver load balancer

### ISSUE THREAD

**Issue by michalschott** [kubernetes/kops#6792]
Currently when enabling audit logs for kube-apiserver sourceIP address matches LB internal address. IMHO would be much better to see proper client IP address.

Proxy-protocol should be enabled by default.

**Comment by zetaab** [comment]
@michalschott does kube-apiserver support proxy protocol? at least I cannot find that option from documentation https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Comment by michalschott** [comment]
@zetaab you might be right. for a reference, I've opened feature request in [kubernetes repo](https://github.com/kubernetes/kubernetes/issues/76928).
