### ISSUE TITLE
Kops planning

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#680]
Just a simple feature request.. for the devs..

Can we start to formalize a kops planning **something**?

Be it a weekly call, or a time we agree to be in slack together, really whatever, etc.. 

Just a venue with some structure that allows us to address outstanding issues/blockers.. 

Thoughts?

**Comment by kris-nova** [comment]
Example agenda item : https://github.com/kubernetes/kops/issues/640

Just general house cleaning / planning / agenda for all the kops things

**Comment by chrislovecnm** [comment]
@kris-nova reopening this :) We need to get this going.

**Comment by kris-nova** [comment]
I figured we would address it on our first call - but happy to see it here too!

**Comment by chrislovecnm** [comment]
Our first call is still not set ... we need to set that up for next week some time.

**Comment by kris-nova** [comment]
Who all needs to be on the call? I can handle organizing it.

**Comment by chrislovecnm** [comment]
Open call.  @justinsb is required.  Like to get as many of the people that are active in issues on the call.

**Comment by kris-nova** [comment]
I will set up a time for next week that works for at least the three of us, and announce the time to everyone else. I will mention everyone I find in the issues. 

Sound good?

**Comment by chrislovecnm** [comment]
Rest of our team maybe as well

**Comment by kris-nova** [comment]
The planning meeting is next [Thursday the 27th at 11am PDT](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=OGJnZHNkc25iNmwyMHBuZzlqYXZlZzZhbjQgbml2ZW5seS5jb21fanMxMmF0Yms1dTlkNXBibnZtdWMzcGt2cGtAZw&tmsrc=nivenly.com_js12atbk5u9d5pbnvmuc3pkvpk%40group.calendar.google.com)

We will be meeting on [zoom](https://zoom.us/my/k8ssigaws).

Starting to tag people now, feel free to add anyone I miss :) 

@justinsb @chrislovecnm @zmerlynn @JuJu227 @austinmoore- @mrichmon @tazjin
