### ISSUE TITLE
metrics server addon is missing addon.yaml file

### ISSUE THREAD

**Issue by drewwells** [kubernetes/kops#6818]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.11.1
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.11.9
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster

Added the following to my cluster spec
```
 spec:
  addons:
  - manifest: metrics-server
    version: v1.8.x
```

**5. What happened after the commands executed?**
only addons running as part of cluster creation
**6. What did you expect to happen?**
metrics-server yaml is applied
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

```
error loading channel "https://raw.githubusercontent.com/kubernetes/kops/master/addons/metrics-server/addon.yaml": error reading addons from "https://raw.githubusercontent.com/kubernetes/kops/master/addons/metrics-server/addon.yaml": file does not exist
I0423 17:56:36.997746    2183 channels.go:34] apply channel output was: I0423 17:56:29.422229    6308 addons.go:38] Loading addons channel from "https://raw.githubusercontent.com/kubernetes/kops/master/addons/metrics-server/addon.yaml"
I0423 17:56:29.422291    6308 context.go:159] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/addons/metrics-server/addon.yaml
```

**9. Anything else do we need to know?**
Is metrics server intended to be installed as an addon? This would be convenient since it's non-intuitive on what flags are required to install this as a separate yaml/chart.

**Comment by drewwells** [comment]
This is where the addon file should be available https://raw.githubusercontent.com/kubernetes/kops/master/addons/metrics-server/addon.yaml

**Comment by shkrid** [comment]
Any updates?

**Comment by JthenG9** [comment]
I have hit this issue as well, should we just add this addon to our custom s3 bucket?
