### ISSUE TITLE
Kubernetes cluster validation is failing all the time if i use AMI (RHEL-7.2_HVM-20161025-x86_64-1-Hourly2-GP2) for master & node

### ISSUE THREAD

**Issue by abburi5992** [kubernetes/kops#6831]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.11.1 (git-0f2aa8d30)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp 203.0.113.123:443: i/o timeout

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
- I created the cluster using this command:
kops create cluster --node-count=1 --cloud=aws --zones=us-east-1c --name=xx.xx.xx.in --dns-zone=xy.in --dns private
- After that i edited Master and Node instance groups using kops edit to change Image location to RHEL
kops edit ig --name=xx.xx.xx.in nodes
kops edit ig --name=xx.xx.xx.in master-us-east-1c

**Updated Image location:**
image: redhat.com/RHEL-7.2_HVM-20161025-x86_64-1-Hourly2-GP2
- Started cluster creation using this command.
kops update cluster xx.xx.xx.in --yes
-Waiting more than a hour for cluster validation. Here the error message that i got.
kops validate cluster
Using cluster from kubectl context: xx.xx.xx.in

Validating cluster xx.xx.xx.in

INSTANCE GROUPS
NAME                    ROLE    MACHINETYPE     MIN     MAX     SUBNETS
master-us-east-1c       Master  m3.medium       1       1       us-east-1c
nodes                   Node    t2.medium       1       1       us-east-1c

NODE STATUS
NAME    ROLE    READY

VALIDATION ERRORS
KIND    NAME            MESSAGE
dns     apiserver       Validation Failed

The dns-controller Kubernetes deployment has not updated the Kubernetes cluster's API DNS entry to the correct IP address.  The API DNS IP address is the placeholder address that kops creates: 203.0.113.123.  Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate.  The protokube container and dns-controller deployment logs may contain more diagnostic information.  Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to start.

Validation Failed

**5. What happened after the commands executed?**

I got this error when i executed this command: kops validate cluster
kops validate cluster
Using cluster from kubectl context: xx.xx.xx.in

Validating cluster xx.xx.xx.in

INSTANCE GROUPS
NAME                    ROLE    MACHINETYPE     MIN     MAX     SUBNETS
master-us-east-1c       Master  m3.medium       1       1       us-east-1c
nodes                   Node    t2.medium       1       1       us-east-1c

NODE STATUS
NAME    ROLE    READY

VALIDATION ERRORS
KIND    NAME            MESSAGE
dns     apiserver       Validation Failed

The dns-controller Kubernetes deployment has not updated the Kubernetes cluster's API DNS entry to the correct IP address.  The API DNS IP address is the placeholder address that kops creates: 203.0.113.123.  Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate.  The protokube container and dns-controller deployment logs may contain more diagnostic information.  Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to start.

Validation Failed

**6. What did you expect to happen?**
I am expecting it to succeed cluster validation

**Comment by AraNaldinho** [comment]
I am facing a similar issue, I am using RHEL 7.3 image.
Please help to resolve this.
