### ISSUE TITLE
NTP Service is not auto restarting in nodes provisioned using kops default ami

### ISSUE THREAD

**Issue by alok87** [kubernetes/kops#6834]
**NODE AMI - `kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17`**

1. What `kops` version are you running? The command `kops version`, will display
 this information.

```
$ kops version
Version 1.11.0 (git-2c2042465)
```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
Not sure how to reproduce this, but a lot of our nodes have ntp service in stopped state

5. What did you expect to happen?
I expected NTP to auto restart instead of manually restarting it.

**Comment by ssro** [comment]
Hi @alok87
Do you have any information about ntpd process in `/var/log/messages` and/or `/var/log/syslog`?

**Comment by alok87** [comment]
@ssro I have not checked it, but i was hoping it would restart on its own.
