### ISSUE TITLE
Use Operators to run cluster-addons

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#6851]
Similar to how CRDs unlocked use of cluster-api controllers, when we are using the bundle we should be able to move more logic to cluster addon operators.  This would replace our use of channels, and would allow addon updates or reconfigurations without using the kops CLI.

We also have some issues where changing options on an addon does not necessarily cause it be reconfigured; operators would address this also.

**Comment by mazzy89** [comment]
Now that CRDs are coming out, there is any intention to build an operator around it in order to create kops clusters with it?
