### ISSUE TITLE
Should docker load image task depend on docker

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#686]
From slack...

There's also this trail in `/var/log/cloud-init-output.log`, which looks innocuous:
```W1018 17:41:00.315232     694 service.go:55] Unhandled type name in Service::GetDependencies: "*LoadImageTask"
W1018 17:41:00.315251     694 service.go:55] Unhandled type name in Service::GetDependencies: "*LoadImageTask"
W1018 17:41:00.315285     694 service.go:55] Unhandled type name in Service::GetDependencies: "*LoadImageTask"
```

... however, we might want to make `LoadImageTask` dependent on `docker-engine`? I can't tell exactly what's going on here, or why we didn't load (dropped error? checking code in a sec), but that's what I'm seeing.

**Comment by chrislovecnm** [comment]
Should be fixed in master
