### ISSUE TITLE
how to debug kops hooks?

### ISSUE THREAD

**Issue by hhuuggoo** [kubernetes/kops#6869]
I'm attempting to modify the kops nvidia-device-plugin to use cuda 10.1, but something isn't working.  What's the best way to diagnose this? Is there a way to get logs from the hook?

Thanks

**Comment by mikesplain** [comment]
In general, the debug flow for anything on instances is to ssh into the instance and look at the logs.  If you are using the default image, you can easily look at all logs in the journal `journalctl`.  You should look for logs from our component `nodeup` which should include the hook phase of startup. Hope this helps!

**Comment by hhuuggoo** [comment]
That does help thanks!  My cluster was set to private and I dind't setup a bastion, so it was tricky.  I provisoned a test cluster and was able to work on #6881
