### ISSUE TITLE
Toolbox convert-imported doesn't support --dns-zone flag

### ISSUE THREAD

**Issue by adambkaplan** [kubernetes/kops#687]
Our primary domain for development servers has both a public and private hosted zone. When trying to convert an imported cluster inside said domain, it gave the following errors:

```
$ kops toolbox convert-imported --newname ${NAME_2} --name ${OLD_NAME}

Error determining default DNS zone; please specify --dns-zone: Found multiple hosted zones matching cluster ".my-cluster.my-domain.com"; please specify the ID of the zone to use
$ kops toolbox convert-imported --newname ${NAME_2} --name ${OLD_NAME} --dns-zone <myDNSzone>
Error: unknown flag: --dns-zone
```

**Comment by justinsb** [comment]
I think a workaround for this should be to edit the old cluster before doing `kops toolbox convert-imported` and add a `dnsZone: <zoneid>` field under `spec`.

If anyone hits this, please ping me so we can figure out if this does indeed work!  I'll try to get to it though...
