### ISSUE TITLE
Get different labels to Nodes/Masters ASGs

### ISSUE THREAD

**Issue by rralcala** [kubernetes/kops#6894]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
In our case it would be nice to be able to choose where the CloudLabels (or another new type) go, as in, to the asg only, to the master or to the nodes, based on how the terraform code is rendered it looks like it's possible, but I wanted to know if you're interested, and how it could be achieved.
I've seen these question in a related issue, so here are some answers based on my initial thought.

what happens when something fails
It depends on what failed, but since the labels live in the ASG it should either launch or not.
what happens when a new node is added
It will get the tag from the asg if propagate_on_launch is set to true.
what happens when a node fails
Not affected by this.
what happens with a rolling update
It will get the tag from the asg if propagate_on_launch is set to true.
**2. Feel free to provide a design supporting your feature request.**
The idea I have is just to be able to choose to which of the asgs the tags go (master or node only) and also to choose where propagate_on_launch is set to true or not.
But, I'm new to this project, so this is just an example proposal.

Similar issues:
https://github.com/kubernetes/kops/issues/1184
https://github.com/kubernetes/kops/issues/5247

**Comment by rifelpet** [comment]
@rralcala You can define cloudLabels per instance group (ASG) in addition to the entire cluster. Just like the `Cluster` type has `cloudLabels` field, the `InstanceGroup` type has one as well:

https://godoc.org/k8s.io/kops/pkg/apis/kops#InstanceGroupSpec

This means you should be able to define your AWS tags in the master InstanceGroups separate from the AWS tags in the node InstanceGroups. You can use `kops edit cluster $CLUSTER_NAME` to get update the cloudLabels on the Cluster, and `kops edit ig --name $CLUSTER_NAME $INSTANCEGROUP_NAME` to update cloudLabels on each instance group.

**Comment by rralcala** [comment]
Is there a way to have cloud labels on the asg that won't get propagated to the instances?

**Comment by rifelpet** [comment]
I don't believe Kops supports that right now. All references to `PropagateAtLaunch` are hardcoded to `true`:

https://github.com/kubernetes/kops/blob/621fcb6bb7381ad85ae383e9d07d65dd5decff29/upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go#L498-L512

**Comment by rralcala** [comment]
Do you think I can make this issue (or a new one) about propagation only? In our use case we have tags that we'd like to have only on the auto scaling groups, also Thanks for pointing how to make IG specific tags!!

**Comment by rifelpet** [comment]
Feel free to close this issue out and open a new feature request issue that requests non-propagating ASG tags 👍
