### ISSUE TITLE
Running `kops import` against cluster with custom subnet will fail

### ISSUE THREAD

**Issue by thenayr** [kubernetes/kops#69]
**Description:**

Attempted to run the `kops import` command against a cluster created via `kube-up.sh` that was given an existing `subnet_id` during creation.   `kops import` fails with the following:

```
I0706 09:38:30.361037   62744 import_cluster.go:78] Found master: "i-xxxxxxx"
F0706 09:38:30.660197   62744 import_cluster.go:26] cannot find subnet "subnet-xxxxxx"
```

This is because `kube-up` will not tag an existing subnet with the `KubernetesCluster` tag if you give it a custom subnet_id on creation.

**Resolution** 

Manually tagging the subnet with `KubernetesCluster` tag, then running `kops import` command will resolve the issue.

**Comment by justinsb** [comment]
We have a better error message, going to push this to the 1.3.2 milestone.

**Comment by abkaplan07** [comment]
Can verify - error message appeared when running kops import on our 1.2 Kubernetes cluster. Very clear and easy to resolve via AWS console.

**Comment by justinsb** [comment]
Thanks for the suggestion on the workaround @thenayr and for the confirmation @adambkaplan .  I don't think we have a _better_ fix, so I'm going to close.  If we come up with something better we can reopen!
