### ISSUE TITLE
Allow kops to generate kube-scheduler config flags.

### ISSUE THREAD

**Issue by rralcala** [kubernetes/kops#6942]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Based on https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/ there are several flags on deprecation path, so adding support for them right now doesn't feel like the right course of action.
This request is to have kops generate the kube-scheduler config file on the node, where these flags are supported so that someone who wants to have a higher qps limit for example, can do.

Currently that flag for example is not supported by kops.
**2. Feel free to provide a design supporting your feature request.**
This feature will allow the user to set the custom kube-scheduler parameters via the kops's config or set_cluster, and those will make kops generate the config file on the node instead of using arguments when kube-scheduler runs.

**Comment by ckcd** [comment]
Agree!! i also need this feature in kops 1.12.

**Comment by rralcala** [comment]
This was addressed in https://github.com/kubernetes/kops/pull/8407
