### ISSUE TITLE
Make gofmt has invalid arguments for mac

### ISSUE THREAD

**Issue by drekle** [kubernetes/kops#6955]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
master

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
make gofmt
```

**5. What happened after the commands executed?**
```
find -name "*.go" | grep -v vendor | xargs bazel run //:gofmt -- -w -s
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```
**6. What did you expect to happen?**
make gofmt finds all go files to pass to gofmt

**9. Anything else do we need to know?**
https://github.com/kubernetes/kops/pull/6954

**Comment by granular-ryanbonham** [comment]
/close 
This has been merge to master
