### ISSUE TITLE
Flannel fails for 30 sec on a new node.

### ISSUE THREAD

**Issue by vaibhavrtk** [kubernetes/kops#6970]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.12.0-beta.2 (git-d1453d22a)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What happened after the commands executed?**
--

**5. What did you expect to happen?**
Flannel should not fail on new node.

Basically kubelet brings up Flannel first as a cni plugin:
`May 11 09:09:53 ip-10-64-115-106 kubelet[2470]: I0511 09:09:53.169902    2470 kube_docker_client.go:348] Stop pulling image "quay.io/coreos/flannel:v0.11.0-amd64": "Status: Downloaded newer image for quay
.io/coreos/flannel:v0.11.0-amd64"`

Flannel Log
After that Flannel starts
`I0511 09:09:54.257670       1 main.go:514] Determining IP address of default interface
I0511 09:09:54.257876       1 main.go:527] Using interface with name eth0 and address 10.64.115.106
I0511 09:09:54.257892       1 main.go:544] Defaulting external address to interface address (10.64.115.106)`

Kubelet Log
Then kubelet brings Kube-proxy after flannel
 `I0514 **09:09:57.439582**    2442 kubelet.go:1883] SyncLoop (ADD, "api"): "kube-proxy-monitoring-rj4b7_monitoring(c7ca6603-7628-11e9-be5e-063eddb97546)"`

Flannel Log
Mean while Flannel tried to connect to Kube api and fails, because kube proxy hadn't created ip table rules when flannel pod was created and flannel only works once flannel pod is restarted(takes around 30 sec, in this time kube-proxy has created IP table rules to connect to kubernetes api service)
`E0511 **09:10:24.258753**       1 main.go:241] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-hjs55': Get https://100.64.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-hjs55: dial tcp 100.64.0.1:443: i/o timeout`

This seems like a chicken and egg problem where kube-proxy is dependent on flannel and vice-versa. But we can reduce the time to start flannel as other pods keep on failing before flannel starts.

**Comment by vivekgarg20** [comment]
We are also hitting same issue randomly. Looks like a race condition. Still debugging, I will update with more information soon.
