### ISSUE TITLE
Unknown flag "--etcd-storage-type" 

### ISSUE THREAD

**Issue by prankul88** [kubernetes/kops#6971]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.11.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Unknown

**3. What cloud provider are you using?**
Openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I followed openstack cloud provider installation guide (https://github.com/kubernetes/kops/blob/master/docs/tutorial/openstack.md). 
I san command,
`kops create cluster   --cloud openstack   --name=my-cluster.k8s.local   --state ${KOPS_STATE_STORE}   --zones nova   --network-cidr 10.0.0.0/24   --image coreos   --master-count=3   --node-count=1  --node-size m1.tiny --master-size m1.small  --etcd-storage-type ceph --api-loadbalancer-type public   --topology private   --bastion   --ssh-public-key ~/.ssh/id_rsa.pub   --networking weave` 

**5. What happened after the commands executed?**
Gives error 

> unknown flag: --etcd-storage-type

**6. What did you expect to happen?**
Cluster setup.
I rechecked the same command on kops v1.12(beta), and it worked fine.
So maybe a note stating the need of 'kops >1.11' at the above link would be helpful

**7. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

/sig openstack

**Comment by drekle** [comment]
@prankul88 is this resolved?

**Comment by prankul88** [comment]
@drekle Yes I have pushed a PR for the same. Closing the issue. Thanks
