### ISSUE TITLE
Fail to start etcd-manager for cluster in eu-north

### ISSUE THREAD

**Issue by pliljenberg** [kubernetes/kops#6998]
Tried to create cluster on eu-north with kops 1.12.0 using:

`kops create cluster --state s3://292662267961-k8s.local-eu-north-1-kops-storage --zones eu-north-1a --master-size t3.small --node-size t3.small --name test2.k8s.local` 

All resources on AWS is created but the cluster isn't starting correctly.
Looking at the logs on the master node I can see that the docker images for `etcd-manager` fails with:

> I0516 13:20:39.596608    3806 s3context.go:164] got region from metadata: "eu-north-1"
W0516 13:20:39.596655    3806 controller.go:149] unexpected error running etcd cluster reconciliation loop: error refreshing control store after leadership cha
nge: error reading s3://292662267961-k8s.local-eu-north-1-kops-storage/test2.k8s.local/backups/etcd/events/control: eu-north-1 is not a valid region
Please check that your region is formatted correctly (e.g. us-east-1)
 
So it would seem that even though kops supports the eu-north region the etcd-manager isn't?
I guess a simple update of the `aws-sdk` component in `etcd-manager` should solve this?

**Comment by justinsb** [comment]
Ah - great call - and you're absolutely right!  I'll do that right now!

**Comment by pliljenberg** [comment]
Nice and quick job @justinsb 👍 
Tried the new release of etc-manager by changing the `/etc/kubernetes//manifests/etcd-main.manifest` file and restarting the etcd-manager docker container.
Got the following error instead:

> F0516 19:43:03.182597       1 storage_decorator.go:57] Unable to create storage backend: config (&{etcd3 /registry [https://127.0.0.1:4002] /etc/kubernetes/pki
/kube-apiserver/etcd-client.key /etc/kubernetes/pki/kube-apiserver/etcd-client.crt /etc/kubernetes/pki/kube-apiserver/etcd-ca.crt true true 1000 {0xc420457170
0xc420457200} <nil> 5m0s 1m0s}), err (dial tcp 127.0.0.1:4002: connect: connection refused)

Not sure if the problem is from the old version being started before or not..

**Comment by justinsb** [comment]
I believe that is from kube-apiserver, and it's essentially saying that it can't connect to etcd.  It is failing to connect to 4002, which is etcd-events, so maybe you also need to update etcd-events.manifest?

Otherwise, there should be some info in `/var/log/etcd-events.logs`

We should be able to cut 1.12.1 soon - just waiting on LGTMs on a few cherry-picks!

**Comment by pliljenberg** [comment]
Ah, of course! 
Looks like its working fine after that!

**Comment by nleib** [comment]
> I believe that is from kube-apiserver, and it's essentially saying that it can't connect to etcd. It is failing to connect to 4002, which is etcd-events, so maybe you also need to update etcd-events.manifest?
> 
> Otherwise, there should be some info in `/var/log/etcd-events.logs`
> 
> We should be able to cut 1.12.1 soon - just waiting on LGTMs on a few cherry-picks!

I have the same issue, what did you change in the manifests for it to work?
