### ISSUE TITLE
kubelet not configured to autostart on reboot

### ISSUE THREAD

**Issue by stonith** [kubernetes/kops#70]
A reboot of a kops created instance doesn't seem to have the kubelet setup to autostart.

**Comment by justinsb** [comment]
This is now fixed.  The easiest way to pick up the latest code is simply to shut down the instance; it will be restarted by the ASG and will pick up the latest code (as we haven't yet cut a release)

Probably though I'll be going through and making a few more fixes, and then cutting a release soon and so we'll have a more controlled way of knowing when the code is out of date.
