### ISSUE TITLE
Remove configure cbr0 options

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#700]
Keep track of this impacts kops https://github.com/kubernetes/kubernetes/pull/34906

**Comment by chrislovecnm** [comment]
This may also remove classic networking mode in k8s.

**Comment by zmerlynn** [comment]
I believe this ruined the `updown` test, and if it a PR builder (which is my goal when the tag leaks disappear),

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws-updown/2851 manages to create a cluster, https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws-updown/2852 doesn't.

**Comment by luxas** [comment]
Is this all fixed now? kops isn't using the old mode anywhere at HEAD?

Also be beware that `reconcile-cidr` probably will be removed in v1.5 as well

**Comment by zmerlynn** [comment]
@luxas: I believe so, yeah.
