### ISSUE TITLE
Misleading cluster edit suggestion 

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#702]
After creating a new cluster

```
Cluster configuration has been created.

Suggestions:
 * list clusters with: kops get cluster
 * edit this cluster with: kops edit cluster kris-private-networking.us-west-2.datapipe.io
 * edit your node instance group: kops edit ig --name=kris-private-networking.us-west-2.datapipe.io nodes
 * edit your master instance group: kops edit ig --name=kris-private-networking.us-west-2.datapipe.io master-us-west-2a
```

Now trying to run the suggested command

```
$ kops edit cluster kris-private-networking.us-west-2.datapipe.io

RegistryPath: Required value
```

Kops yells about a missing RegistryPath

**Comment by kris-nova** [comment]
Workaround : 

Add the `--state` flag

```kops edit cluster kris-private-networking.us-west-2.datapipe.io --state s3://kris-private-networking```

**Comment by justinsb** [comment]
Ah, interesting point... I think if the user specified the `--state` flag, we should probably plumb that through.  We should also encourage them to `export KOPS_STATE_STORE=<registry>` as well :-)

As to whether you want to detect someone using the wrong editor and encourage them to set a better one in their bash profile ... I'll leave that up to you ;-)

**Comment by chrislovecnm** [comment]
I think this is fixed ... can anyone confirm?

/assign
