### ISSUE TITLE
Problem installing kops using openstack cloud provider

### ISSUE THREAD

**Issue by prankul88** [kubernetes/kops#7021]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.12.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Version 1.14

**3. What cloud provider are you using?**
OpenStack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops create cluster --cloud openstack --name my-cluster-k8s.local --state ${KOPS_STATE_STORE} --zones nova --network-cidr 10.0.0.0/24 --image coreos --master-count=3 --node-count=1 --node-size m1.tiny --master-size m1.small --etcd-storage-type lvmdriver-1 --api-loadbalancer-type public --topology private --bastion --ssh-public-key ~/.ssh/id_rsa.pub --networking weave --os-ext-network public`

**5. What happened after the commands executed?**
gave error unknown flag --os-ext-net

**6. Anything else do we need to know?**

I am following [https://github.com/kubernetes/kops/blob/master/docs/tutorial/openstack.md](url)
Installed openstack through devstack and sourced openrc file

What I did? 

1. If I remove the flag "--os-ext-net" from the above command
    I get an error 

> error populating configuration: error loading config file: open /opt/stack/.openstack/config: no such file or directory

I searched the previous conversations and landed on issue [https://github.com/kubernetes/kops/issues/6520](url) and pr [https://github.com/kubernetes/kops/pull/6480](url)

From there I got to know that there were two ways of authenticating ; one of them was through conf file which had some problems and so removed (kindly correct me if wrong) ; other way I am not sure of.

2. If I retain "--os-ext-net" 
   I get an error

>unknown flag: --os-ext-network

I am new to this project and so any kind of inputs would be very helpful.

**Comment by loqutus** [comment]
i have the same problem

**Comment by loqutus** [comment]
its KOPS_FEATURE_FLAGS="AlphaAllowOpenstack", not AlphaAllowOpenStack as in documentation

**Comment by prankul88** [comment]
@loqutus Thanks for replying. It ran successfully with the above changes mentioned.
Will push a PR soon to initiate the changes.

**Comment by poothia** [comment]
i think this issue can be closed.

**Comment by prankul88** [comment]
Sure I am closing the issue.
