### ISSUE TITLE
Support VPC Peering with multiple CIDRs in AWS

### ISSUE THREAD

**Issue by Timboo89** [kubernetes/kops#7044]
Kops version: 1.11.0
Kubernetes Version: 1.11.8

Hi,

I recently tried to create a K8s cluster spread over 2 VPCs in one AWS account. 
I started with simply creating the 2 VPCs and peering them. I will only paste the important code here, to not have a too long post.
https://www.codepile.net/pile/Q3Y8EBJA
/module/vpc https://www.codepile.net/pile/n0npK46y

Afterwards I got kops to create a basic cluster with terraform output and edited some stuff using kops edit.
```
kops create cluster \
--name=<CLUSTERNAME> \
--state=s3://<MY_BUCKET> \
--dns-zone=<DNS_ZONE> \
--cloud=aws \
--authorization AlwaysAllow \
--api-loadbalancer-type public \
--channel stable \
--kubernetes-version 1.11.8 \
--master-public-name api.k8s.sandbox.stormreply.cloud \
--zones eu-west-3a \
--out=. --target=terraform
```

After several kops edits, this is the terraform output:
https://www.codepile.net/pile/WLVMX4OA

Now I simply copied all node creations to use also the second vpc and added the necessary security groups and rules. So this is the terraform code I used to deploy it:
https://www.codepile.net/pile/knNkJPd2

In the end the cluster just started all nodes were ready and I started celebrating. After some tests I encountered the problem that pods in VPC A were not able to communicate with pods in VPC B and vice versa. In particular I encountered this already with kube-dns. If the primary kube-dns pod was in VPC A, pods in VPC B could not do any DNS resolution, but pods in VPC A were and vice versa.

What I did suspect:
The virtual network of Kubernetes should just be able to communicate through VPC peering since the instances are able to communicate with each other and the CIDR blocks were not overlapping.

Questions:
1) Any suggestions on how to solve this?
2) Why does Kops only support CIDR blocks in ONE VPC? What's the difference in having multiple VPCs with multiple CIDR?

Thanks

**Comment by KristianWindsor** [comment]
I am also having this issue. Regular EC2 instances within the VPC can communicate with the other VPC, but pods are not able to. I can't for the life of me figure this out.
