### ISSUE TITLE
Cilium with etcd-manager does not work

### ISSUE THREAD

**Issue by austinmoore-** [kubernetes/kops#7046]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.12.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.12.8

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create cluster --networking cilium --override "cluster.spec.etcdClusters[*].version=3.2.24" <account-specific-options>
kops update cluster <name> --yes
```
**5. What happened after the commands executed?**
Once the cluster is up and running, the Cilium pods are in a CrashLoopBackoff because they cannot find the [TLS certs needed](https://github.com/kubernetes/kops/blob/93988d8fdd8e024fef0204e4e441823320d3886a/upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template#L16) to connect to etcd. I think normally these are created by kops under the `pki/issued/calico-client` directory in the cluster's S3 bucket but [when using etcd-manager it isn't created](https://github.com/kubernetes/kops/blob/93988d8fdd8e024fef0204e4e441823320d3886a/nodeup/pkg/model/etcd_tls.go#L35).

```
# kubectl logs cilium-x46cd -n kube-system
level=info msg="     _ _ _"
level=info msg=" ___|_| |_|_ _ _____"
level=info msg="|  _| | | | | |     |"
level=info msg="|___|_|_|_|___|_|_|_|"
level=info msg="Cilium 1.0.6 b115746 2018-09-17T10:18:11+02:00 go version go1.9 linux/amd64"
level=info msg="cilium-envoy  version: b115746757694b19b67067c0b19d4a665402ef5b/1.7.0-dev/Modified/RELEASE"
level=info msg="clang (3.8.1) and kernel (4.14.106) versions: OK!"
level=info msg="linking environment: OK!"
level=info msg="bpf_requirements check: OK!"
level=warning msg="BPF filesystem is going to be mounted automatically in /run/cilium/bpffs. However, it probably means that Cilium is running inside container and BPFFS is not mounted on the host. for more information, see: https://cilium.link/err-bpf-mount"
level=info msg="Mounted BPF filesystem /run/cilium/bpffs"
level=fatal msg="Unable to setup kvstore" address= error="open /var/lib/etcd-secrets/calico-client.pem: no such file or directory" kvstore=etcd
```

**6. What did you expect to happen?**
The Cilium pods start up without issue because they have the certs needed to connect to etcd.

The same might be true for Calico, but I haven't tried it.

**Comment by olemarkus** [comment]
Relates to #6496 

We had to migrate our cillium setups to use the cilium-etcd-operator. Works quite well for existing clusters, but not for new ones due to https://github.com/cilium/cilium-etcd-operator/issues/42

For new clusters one first has to provision the cluster in legacy mode, then migrate to cilium-etcd-operator, then switch to etcd-manager.

Calico use CRDs now, so they are not affected. Cilium will also support CRD for smaller clusters as of 1.6.

**Comment by michaelajr** [comment]
Hoping this gets prioritized. Thanks for the work around @olemarkus

**Comment by olemarkus** [comment]
We kinda gave up on kops managing this now.

What we did is to change networking in the cluster spec from cilium to cni. This means that cilium is no longer handled by kops, but that you have to manage the daemonset yourself. But this is basically a matter of running something like this:
```kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/1.12/cilium-cm.yaml
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/1.12/cilium-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/1.12/cilium-ds.yaml
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/1.12/cilium-operator-sa.yaml
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/1.12/cilium-operator.yaml
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/1.12/cilium-etcd-operator-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/1.12/cilium-etcd-operator-sa.yaml
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/1.12/cilium-etcd-operator.yaml
```

We don't get tons from this being handled by kops really, so I wonder if the best solution is to just drop direct managed cilium support unless there is any commitment to actively support it.

**Comment by so0k** [comment]
With latest release Cilium doesn’t require store anymore - https://cilium.io/blog/2019/08/20/cilium-16/

**Comment by olemarkus** [comment]
I think the whole addon needs to be redone though. But it shouldn't be too hard. Just take the helm templates that Cilium provides and make the relevant values configurable through the cluster spec

**Comment by olemarkus** [comment]
Working on a fix here: https://github.com/kubernetes/kops/pull/7474
