### ISSUE TITLE
parse error near `)' in bash & zsh

### ISSUE THREAD

**Issue by subhranildey** [kubernetes/kops#7048]
`curl -Lo kops https://github.com/kubernetes/kops/releases/download/$\(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-darwin-amd64`

zsh: parse error near `)'

bash: syntax error near unexpected token `)'

**Comment by itmecho** [comment]
@subhranildey Looks like you've escaped the opening `(` and not the closing one?

**Comment by granular-ryanbonham** [comment]
@subhranildey Did this resolve your issue?

**Comment by rashthedude** [comment]
I'm also having the same issue

**Comment by rashthedude** [comment]
@itmecho the suggestion above doesn't seem to fix the problem at hand. Another suggestion maybe?

**Comment by itmecho** [comment]
Can you give a bit more context? What OS are you on? Are you pasting that command directly into a terminal?

**Comment by rashthedude** [comment]
I'm on Ubuntu and yes I'm copying and pasting it directly on to the terminal.

**Comment by itmecho** [comment]
Can you try this?

```
curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-darwin-amd64
```

**Comment by itmecho** [comment]
Sorry, that's for the Darwin binary!

Change the last part to `kops-linux-amd64 `

**Comment by rashthedude** [comment]
I'm receiving still the same error @itmecho

**Comment by itmecho** [comment]
Hmm, what do you get when you just run this part?

```
curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4
```

**Comment by rashthedude** [comment]
Output: `1.12.1`

**Comment by itmecho** [comment]
Ok, can you either screenshot or copy paste from your terminal with you running the command and getting the output with the error?

**Comment by rashthedude** [comment]
`➜  coding curl -Lo kops https://github.com/kubernetes/kops/releases/download/$\(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64

zsh: parse error near `)'
➜  coding 

`

**Comment by itmecho** [comment]
Looks like you've still got the `\` in there. That's definitely causing the issue. Take it out and you won't get the error

**Comment by rashthedude** [comment]
Sweet that's working now. Much appreciated @itmecho you are a hero.

**Comment by subhranildey** [comment]
`curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
`

This should be added in documentation 
Thanks @itmecho
