### ISSUE TITLE
Openstack rolling update always reports NeedsUpdate

### ISSUE THREAD

**Issue by drekle** [kubernetes/kops#7056]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.14.0-alpha.1
Version 1.13.0-alpha.1
Version 1.13.0-alpha.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
/sig openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops rolling-update cluster`

**5. What happened after the commands executed?**
Everything reports NeedsUpdate

**6. What did you expect to happen?**
Updates are required if there is a difference between the declare state and the observed state

**7. Please provide your cluster manifest. Execute
n/a
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
n/a
**9. Anything else do we need to know?**
https://github.com/kubernetes/kops/pull/7050
/assign

**Comment by bzuelke** [comment]
I've found this also on AWS, not just openstack. I've upgraded from 1.11 -> 1.12 (kops/k8s) and ran into this. I'm also using the launch templates with mixed instance types, Not sure if that has something to do with this since it's so new. That and also opted in to etcd-manager. Not sure if that helps here but this is a pretty big bummer to have happen.
