### ISSUE TITLE
could not find Image for "kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17"

### ISSUE THREAD

**Issue by HcwXd** [kubernetes/kops#7073]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.12.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster \
--name=example.com \
--state=s3://example.com \
--zones=eu-north-1a \
--master-size=t3.medium \
--node-size=t3.nano \
--node-count=2 \
--cloud=aws \
```

```
kops update cluster example.com --state=s3://example.com --yes
```

**5. What happened after the commands executed?**

```
error running task "LaunchConfiguration/master-eu-north-1a.masters.handover-lab2.chocolabs.com" (9m53s remaining to succeed): could not find Image for "kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17"
```

**6. How to fix this error?**

I fix this error by

1.  Find an available image in the region

```
aws ec2 describe-images --owner 383156758163 --filters 'Name=name,Values=k8s--debian-stretch' --region eu-north-1 | grep debian-stretch-amd64
```

It shows
```
"ImageLocation": "383156758163/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-14",
"Name": "k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-14",
"ImageLocation": "383156758163/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13",
"Name": "k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13",
```

2. Specify the image when creating

```
kops create cluster \
--name=example.com \
--state=s3://example.com \
--zones=eu-north-1a \
--master-size=t3.medium \
--node-size=t3.nano \
--node-count=2 \
--cloud=aws \
--image=383156758163/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-14
```

Hope it helps those who encounter the same error.

**Comment by fangnaichao** [comment]
I can not find any Images owned by 383156758163 in ap-east-1 region .

**Comment by zfogg** [comment]
+1

**Comment by denlcy** [comment]
Hi, zfogg

Could you please share the way for making the image? Since the kops.channel how change to use this image, kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21. And I have no idea where can I get this one and put it in AWS AMI

Please advice, thanks

**Comment by zfogg** [comment]
@denlcy sorry i don't think i kept the code to generate that. can close this i guess, it's stale
