### ISSUE TITLE
Migrating from single to multi-master tutorial is broken

### ISSUE THREAD

**Issue by astrieanna** [kubernetes/kops#7076]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.12.1 (git-e1c317f9c)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.12.7

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Everything went fine until we got to the [tutorial's 3a](https://github.com/kubernetes/kops/blob/master/docs/single-to-multi-master.md) with:
```
kubectl --namespace=kube-system exec etcd-server-ip-172-20-36-161.ec2.internal -- etcdctl member add etcd-<availability-zone2-name> http://etcd-<availability-zone2-name>.internal.example.com:2380
```

**5. What happened after the commands executed?**
* There is no pod by that exact name -- the pod we picked as most similar is `etcd-manager-main-ip-...` (with the extra `-main`).
* There is no etcdctl on the path in that pod -- we used `ps` to find the `etcd` version and tried to continue with `/opt/etcd-v3.2.24-linux-amd64/etcdctl`.
* It was unable to communicate, erroring with `malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"` -- we then assumed it needed to be TLS, trying to add `--endpoints https://...` and find client credentials.
* There are no client certs (just the `etcd-clients-ca.*` client CA files) in `/etc/kubernetes/pki/etcd-manager`.
* At this point we felt like we diverged quite a bit from the tutorial, so we stopped experimenting and are looking for help :)

**6. What did you expect to happen?**
The tutorial to work.

**9. Anything else do we need to know?**
This was a freshly deployed single-master cluster.

**Comment by granular-ryanbonham** [comment]
The document is defiantly out of date. We have done this migration a number of time now, and have some scripts/docs to help.  I will take this on as an action item, and get the tutorial updated.

/assign @granular-ryanbonham

**Comment by granular-ryanbonham** [comment]
@astrieanna Leah, let me know if the updated docs in the linked PR help you out.. Feel free to comment on the PR if you have any questions or run into issues.

**Comment by rayh** [comment]
Any update on this?
