### ISSUE TITLE
Metrics-server: How to configure TLS authentication instead of using `--kubelet-insecure-tls`?

### ISSUE THREAD

**Issue by ftclausen** [kubernetes/kops#7083]
I was reading the [HPA doc](https://github.com/kubernetes/kops/blob/master/docs/horizontal_pod_autoscaling.md) with interest and, indeed, that does correspond to what [I had to do](https://ftclausen.github.io/general/setting_up_k8s_with_metrics_server/) on a manually installed learning cluster. 

However the Kops HPA doc only describes one half of the equation. The metrics-server reference YAML deployment spec uses `--kubelet-insecure-tls` which bypasses all trust set up.

It is unclear to me how you go about doing the following tasks with Kops:

- Access the aggregator CA + key to sign a new keypair for the metrics-server
- Where to put this new keypair
- How best to modify the metrics-server startup arguments to use this keypair as well as specify the CA cert

**Comment by ftclausen** [comment]
I see now that, at least in our situation, we're using Webhook auth so certificates do not come into play.

**Comment by ashish235** [comment]
@ftclausen but how did you configure the metric server to work with webhook auth and not certs?

**Comment by agilgur5** [comment]
You can configure webhook auth following the config in https://github.com/kubernetes/kops/issues/7200:

```yaml
kubelet:
  authenticationTokenWebhook: true
  authorizationMode: Webhook
```

But this is for auth; without this `metrics-server` gets `401 Unauthorized`.

`--kubelet-insecure-tls` isn't to get around auth, it's to skip verification of the TLS cert that the `kubelet` presents. With token auth but without `--kubelet-insecure-tls` one gets:

```bash
manager.go ... x509: certificate signed by unknown authority, unable to fully scrape metrics from source
```

The inverse of `--kubelet-insecure-tls` seems to be `--kubelet-certificate-authority` but this doesn't seem to work no matter what I do. I've described this in detail at https://github.com/kubernetes-sigs/metrics-server/issues/541 where I've listed a bunch of different options I tried.

It also seems like #6879 addresses this and the `--kubelet-certificate-authority` flag. I've [commented there](https://github.com/kubernetes/kops/issues/6879#issuecomment-642966333) as well

**Comment by jmcdonagh** [comment]
+1 for fixing this, I didn;t realize you still needed insecure tls to get this working, just discovered it while wrapping up a new cluster build.

**Comment by olemarkus** [comment]
Duplicate of #6879 
Would like to find a solution for this that actually increases security, but not necessarily that easy.
