### ISSUE TITLE
unexpected error during validation: error listing nodes: Get https://....: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by vinay2107** [kubernetes/kops#7095]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.12.1 (git-e1c317f9c)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client - v1.14.1
Server - 1.12.8 (found it from `kops edit cluster`)
**3. What cloud provider are you using?**
aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster --zones=eu-central-1a eucentral1.k8s.example.com (replaced my domain name with example.com, rest is same)
kops update cluster --name eucentral1.k8s.example.com --yes
**5. What happened after the commands executed?**
After running update for first time, I could run kops validate cluster and was able to list other resources but after 20 mnts when I try to list resources or validate I get this error

Validating cluster eucentral1.k8s.example.com

unexpected error during validation: error listing nodes: Get https://api.eucentral1.k8s.example.com/api/v1/nodes: x509: certificate signed by unknown authority

**6. What did you expect to happen?**
Work as normal, interact with the api-server
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
`apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-06-05T09:20:33Z
  name: eucentral1.k8s.example.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://clusters.k8s.example.com/eucentral1.k8s.example.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.8
  masterPublicName: api.eucentral1.k8s.example.com
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-06-05T09:20:33Z
  labels:
    kops.k8s.io/cluster: eucentral1.k8s.example.com
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-06-05T09:20:33Z
  labels:
    kops.k8s.io/cluster: eucentral1.k8s.example.com
  name: nodes
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
`
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
`I0605 13:51:58.131921   22170 loader.go:359] Config loaded from file /home/evenvin/.kube/config
Using cluster from kubectl context: eucentral1.k8s.example.com

I0605 13:51:58.131973   22170 factory.go:68] state store s3://clusters.k8s.example.com
I0605 13:51:58.132002   22170 s3context.go:325] unable to read /sys/devices/virtual/dmi/id/product_uuid, assuming not running on EC2: open /sys/devices/virtual/dmi/id/product_uuid: permission denied
I0605 13:51:58.132011   22170 s3context.go:170] defaulting region to "us-east-1"
I0605 13:51:58.896465   22170 s3context.go:210] found bucket in region "eu-central-1"
I0605 13:51:58.896711   22170 s3fs.go:220] Reading file "s3://clusters.k8s.example.com/eucentral1.k8s.example.com/config"
I0605 13:51:59.301482   22170 s3fs.go:257] Listing objects in S3 bucket "clusters.k8s.example.com" with prefix "eucentral1.k8s.example.com/instancegroup/"
I0605 13:51:59.346269   22170 s3fs.go:285] Listed files in s3://clusters.k8s.example.com/eucentral1.k8s.example.com/instancegroup: [s3://clusters.k8s.example.com/eucentral1.k8s.example.com/instancegroup/master-eu-central-1a s3://clusters.k8s.example.com/eucentral1.k8s.example.com/instancegroup/nodes]
I0605 13:51:59.346345   22170 s3fs.go:220] Reading file "s3://clusters.k8s.example.com/eucentral1.k8s.example.com/instancegroup/master-eu-central-1a"
I0605 13:51:59.389736   22170 s3fs.go:220] Reading file "s3://clusters.k8s.example.com/eucentral1.k8s.example.com/instancegroup/nodes"
Validating cluster eucentral1.k8s.example.com

I0605 13:51:59.443683   22170 validate_cluster.go:110] instance group: kops.InstanceGroupSpec{Role:"Master", Image:"kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13", MinSize:(*int32)(0xc420fff00c), MaxSize:(*int32)(0xc420fff000), MachineType:"m3.medium", RootVolumeSize:(*int32)(nil), RootVolumeType:(*string)(nil), RootVolumeIops:(*int32)(nil), RootVolumeOptimization:(*bool)(nil), Volumes:[]*kops.VolumeSpec(nil), VolumeMounts:[]*kops.VolumeMountSpec(nil), Subnets:[]string{"eu-central-1a"}, Zones:[]string(nil), Hooks:[]kops.HookSpec(nil), MaxPrice:(*string)(nil), AssociatePublicIP:(*bool)(nil), AdditionalSecurityGroups:[]string(nil), CloudLabels:map[string]string(nil), NodeLabels:map[string]string{"kops.k8s.io/instancegroup":"master-eu-central-1a"}, FileAssets:[]kops.FileAssetSpec(nil), Tenancy:"", Kubelet:(*kops.KubeletConfigSpec)(nil), Taints:[]string(nil), MixedInstancesPolicy:(*kops.MixedInstancesPolicySpec)(nil), AdditionalUserData:[]kops.UserData(nil), SuspendProcesses:[]string(nil), ExternalLoadBalancers:[]kops.LoadBalancer(nil), DetailedInstanceMonitoring:(*bool)(nil), IAM:(*kops.IAMProfileSpec)(nil), SecurityGroupOverride:(*string)(nil)}

I0605 13:51:59.443804   22170 validate_cluster.go:110] instance group: kops.InstanceGroupSpec{Role:"Node", Image:"kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13", MinSize:(*int32)(0xc420fea75c), MaxSize:(*int32)(0xc420fea750), MachineType:"t2.medium", RootVolumeSize:(*int32)(nil), RootVolumeType:(*string)(nil), RootVolumeIops:(*int32)(nil), RootVolumeOptimization:(*bool)(nil), Volumes:[]*kops.VolumeSpec(nil), VolumeMounts:[]*kops.VolumeMountSpec(nil), Subnets:[]string{"eu-central-1a"}, Zones:[]string(nil), Hooks:[]kops.HookSpec(nil), MaxPrice:(*string)(nil), AssociatePublicIP:(*bool)(nil), AdditionalSecurityGroups:[]string(nil), CloudLabels:map[string]string(nil), NodeLabels:map[string]string{"kops.k8s.io/instancegroup":"nodes"}, FileAssets:[]kops.FileAssetSpec(nil), Tenancy:"", Kubelet:(*kops.KubeletConfigSpec)(nil), Taints:[]string(nil), MixedInstancesPolicy:(*kops.MixedInstancesPolicySpec)(nil), AdditionalUserData:[]kops.UserData(nil), SuspendProcesses:[]string(nil), ExternalLoadBalancers:[]kops.LoadBalancer(nil), DetailedInstanceMonitoring:(*bool)(nil), IAM:(*kops.IAMProfileSpec)(nil), SecurityGroupOverride:(*string)(nil)}

I0605 13:51:59.446211   22170 loader.go:359] Config loaded from file /home/evenvin/.kube/config
I0605 13:51:59.450734   22170 loader.go:359] Config loaded from file /home/evenvin/.kube/config
I0605 13:51:59.472217   22170 aws_cloud.go:1212] Querying EC2 for all valid zones in region "eu-central-1"
I0605 13:51:59.472479   22170 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
I0605 13:51:59.674976   22170 round_trippers.go:386] curl -k -v -XGET  -H "User-Agent: kops/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Basic YWRtaW46NjhPS2dVTEFuMk1UbjVtaXRLSVA5MjFYVm12TkxSSXg=" -H "Accept: application/json, */*" 'https://api.eucentral1.k8s.example.com/api/v1/nodes'
I0605 13:51:59.776725   22170 round_trippers.go:405] GET https://api.eucentral1.k8s.example.com/api/v1/nodes  in 101 milliseconds
I0605 13:51:59.776772   22170 round_trippers.go:411] Response Headers:

unexpected error during validation: error listing nodes: Get https://api.eucentral1.k8s.example.com/api/v1/nodes: x509: certificate signed by unknown authority
`
**9. Anything else do we need to know?**
Using Public Domain

**Comment by vinay2107** [comment]
SOLVED: "If you're using self-signed certificate and --insecure-skip-tls-verify=true doesn't work, there is a chance that your network doesn't allow unsecure self signed cert. Try doing it over a VPN."

**Comment by parsh96** [comment]
> SOLVED: "If you're using self-signed certificate and --insecure-skip-tls-verify=true doesn't work, there is a chance that your network doesn't allow unsecure self signed cert. Try doing it over a VPN."

I am also trying to create a cluster using kops can you help me out 
following issue i am facing :-
[vagrant@localhost ~]$ kops validate cluster --state "s3://kops-pasha" --name tibco.in
Validating cluster tibco.in


unexpected error during validation: error listing nodes: Get https://api.tibco.in/api/v1/nodes: dial tcp 199.59.242.151:443: i/o timeout
