### ISSUE TITLE
Kops cannot create cluster in AWS with different subnet ranges.

### ISSUE THREAD

**Issue by usvgmani** [kubernetes/kops#7098]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Kop version 1.12.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specific.**

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:56:40Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster k8s-ops-cluster.k8s.local --cloud=aws --node-count=3 --zones=$ZONES --node-size=$NODE_SIZE --master-size=$MASTER_SIZE --master-zones=$MASTERZONES --networking=calico --topology=private --vpc=vpc-xxxx --subnets="subnet-xxx,subnet-yyy"

**5. What happened after the commands executed?**
spec.Subnets[1].CIDR: Invalid value: "100.64.128.0/18": Subnet "us-east-1c" had a CIDR "100.64.128.0/18" that was not a subnet of the NetworkCIDR "10.242.64.0/21"

**6. What did you expect to happen?**
Cluster created across 2 different subnets with different CIDR ranges.

We have a VPC in aws whose CIDR range is extended and would like the cluster to span these different ranges.

**Comment by rdrgmnzs** [comment]
Hi @usvgmani have you tried adding the additional CIDR blocks to the spec as per https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md#vpc-with-multiple-cidrs ?

**Comment by usvgmani** [comment]
No I have not tried.. let me check and get back, thanks

**Comment by rdrgmnzs** [comment]
Hi @usvgmani did that work for you?
