### ISSUE TITLE
Given a pool of Elastic IPs, provision them to Ingress Controllers

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#71]
Basic use case: Some customers require whitelisting IP Addresses in order to access a service. This precludes the ability to leverage ELBs or similar.  

Suggested implementation: Admin provides a pre-existing list of EIP Allocations, The controller should then label the nodes which receive these EIPs and then associate the EIPs with those nodes.

Then the admins/developers can target jobs at those labels.

Ideally, several pools of EIPs should be possible, with a unique label per EIP Pool.

**Comment by aledbf** [comment]
@zapman449 did you check the [whitelist example](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/whitelist/README.md) in the nginx ingress controller. It allows you to set the IP or network ranges per Ingress

**Comment by blakebarnett** [comment]
This looks like it's addressed with the ingress controller whitelisting, please re-open if needed

**Comment by muenchdo** [comment]
I don't think this is addressed by ingress controller whitelisting. If I understand correctly, @zapman449 wants to associate nodes with EIPs, so customers can whitelist those IPs in their *outgoing* firewalls to allow a connection to the cluster.

**Comment by zapman449** [comment]
In AWS the more appropriate solution is to bring the nodes ASG into one or more target groups, and then front the target group with an NLB.

With the above, I believe this issue is moot.
