### ISSUE TITLE
Client.UnauthorizedOperation in CloudTrail logs - due to "DescribeTags" call

### ISSUE THREAD

**Issue by richstokes** [kubernetes/kops#7110]
kops provisioned nodes are repeatedly trying to make the 'DescribeTags' call - however this is not included as part of the IAM role. Is this intentional?

**Comment by mgarstecki** [comment]
Seconded, I see the same behavior on my clusters, has anyone diagnosed if this is due to a Kops-deployed component, or if it's some add-on ?

**Comment by mgarstecki** [comment]
After investigation, I linked the problem to the Datadog agent I have in my clusters.
