### ISSUE TITLE
kube-dns and kube-dns-autoscaler in pending status when the cluster is up

### ISSUE THREAD

**Issue by vlinx** [kubernetes/kops#7128]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
$ kops version
Version 1.12.1 (git-e1c317f9c)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
$ kops validate cluster

**5. What happened after the commands executed?**
right after kops cluster been created
$ kops validate cluster
will alway fails with the following error

module.kubernetes.null_resource.kops_cluster (local-exec): VALIDATION ERRORS
module.kubernetes.null_resource.kops_cluster (local-exec): KIND	NAME							MESSAGE
module.kubernetes.null_resource.kops_cluster (local-exec): Pod	kube-system/kube-dns-6b4f4b544c-jgm2m			kube-system pod "kube-dns-6b4f4b544c-jgm2m" is pending
module.kubernetes.null_resource.kops_cluster (local-exec): Pod	kube-system/kube-dns-autoscaler-6b658bd4d5-5zqfq	kube-system pod "kube-dns-autoscaler-6b658bd4d5-5zqfq" is pending

**6. What did you expect to happen?**
Successful validation
There is no such problem with the previous version kops 1.11.1

**Comment by elisiano** [comment]
I've noticed the same (while doing 1.12 upgrades).
After further debugging I noticed that there are multiple replicasets trying to spinup pods so they keep stepping on each other toes.
I tried deleting the replicasets but somehow they get recreated (I was unable to pinpoint which component was recreating them). For this test I scaled down the kube-dns-autoscaler to 0 replicas.

**Comment by marutinandanpandya** [comment]
Still getting the error. Tried creating a new cluster and failing 
```
MacBook-Pro-2:doks-monitoring maruti_nandan$ kops version
Version 1.15.0 (git-9992b4055)
MacBook-Pro-2:doks-monitoring maruti_nandan$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
MacBook-Pro-2:doks-monitoring maruti_nandan$ kops validate cluster --name <XXXX>
Validating cluster <XXXX>

INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-ap-south-1b	Master	t3.micro	1	1	ap-south-1b
nodes			Node	t2.medium	2	2	ap-south-1b

NODE STATUS
NAME						ROLE	READY
ip-172-32-55-170.ap-south-1.compute.internal	master	True

VALIDATION ERRORS
KIND	NAME							MESSAGE
Machine	i-04400166aeac09d84					machine "i-04400166aeac09d84" has not yet joined cluster
Machine	i-0e9f65b682887a7d2					machine "i-0e9f65b682887a7d2" has not yet joined cluster
Pod	kube-system/kube-dns-5fdb85bb5b-dtrn9			kube-system pod "kube-dns-5fdb85bb5b-dtrn9" is pending
Pod	kube-system/kube-dns-autoscaler-577b4774b5-fl6gw	kube-system pod "kube-dns-autoscaler-577b4774b5-fl6gw" is pending

Validation Failed
```

**Comment by Overbryd** [comment]
I had to manually update the `kube-dns` deployment with a toleration to run on the `master` node:

```
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: Exists
        effect: NoSchedule
```
