### ISSUE TITLE
Add RHEL 8 support to kops (GA May 7, 2019)

### ISSUE THREAD

**Issue by neoakris** [kubernetes/kops#7129]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
RHEL8 achieved GA May 7, 2019
https://developers.redhat.com/blog/2019/05/07/red-hat-enterprise-linux-8-now-generally-available/
I'd like to see kops upstream add support for it.

**2. Feel free to provide a design supporting your feature request.**
@cassandracomar added support on https://github.com/VibrentHealth/kops/tree/rhel8
I was able to build kops off that branch, use an overridden KOPS_BASE_URL env var + custom binary + custom RHEL8 AMI (se linux disabled) in instancegroups.yaml  to successfully get a RHEL8 cluster provisioned with kops.  

I'd like to see the change get merged into release-1.13 so we wouldn't need to use custom kops in the future when 1.13 gets released. 

------
Update: 
No mention of it in the release notes of kops 1.13.0 (hopefully a patch version will include it.)
It has been cherry picked into kops 1.14.0, so maybe it'll be in 1.14.0-alpha.4 or higher

**Comment by neoakris** [comment]
PR https://github.com/kubernetes/kops/pull/7130

**Comment by rifelpet** [comment]
/reopen
/remove-lifecycle rotten

@hakman has been working on adding support. We now have end-to-end tests for RHEL 8 as well

https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-rhel-8

**Comment by hakman** [comment]
This was fixed by https://github.com/kubernetes/kops/pull/8164 and will be available in Kops 1.18.
RHEL uses iptables NFT only, which is only supported in Kubernetes 1.17+.

Backporting will not be possible due to dependencies on other fixes.
