### ISSUE TITLE
Error deleting resources: resource not found

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#7136]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.** 1.14.1

**3. What cloud provider are you using?** openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops delete cluster foo --yes

**5. What happened after the commands executed?**

it started to delete things. However, it did not complete because:

```
FloatingIP:f001bc42-1914-4a9a-8a85-0e539b2016df	error deleting resources, will retry: Failed to delete L3 floating ip f001bc42-1914-4a9a-8a85-0e539b2016df: Resource not found
I0612 07:39:39.226575      36 context.go:231] hit maximum retries 5 with error Failed to delete L3 floating ip f001bc42-1914-4a9a-8a85-0e539b2016df: Resource not found
```

**6. What did you expect to happen?**

We should ignore error if it returns "Resource not found" - that is the state what we want when deleting resources.

/sig openstack

**Comment by ppcololo** [comment]
/remove-lifecycle stale
same error
