### ISSUE TITLE
Couldn't find key etcd_endpoints in ConfigMap kube-system/calico-config

### ISSUE THREAD

**Issue by acarsercan** [kubernetes/kops#7140]
`**1.` What `kops` version are you running? The command `kops version`, will display
 this information.**
kops 1.12.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Upgrading from v1.11.10 to 1.12.8

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops rolling-update cluster --cloudonly --master-interval=1s --node-interval=1s --yes`

**5. What happened after the commands executed?**

master not healthy after update, stopping rolling-update: "error validating cluster after removing a node: cluster did not validate within a duration of \"5m0s\""

**6. What did you expect to happen?**

Validation to complete successfully

**9. Anything else do we need to know?**

I clearly messed up the upgrade from v1.11.10 to 1.12.8

I originally ran

```kops upgrade...
   kops update...
   kops rolling-update cluster --yes
```

Above failed on first master with
`master not healthy after update, stopping rolling-update: "error validating cluster after removing a node: cluster did not validate within a duration of \"5m0s\""`

Validation failing due to
`Pod	kube-system/calico-complete-upgrade-v331-mz6z9	kube-system pod "calico-complete-upgrade-v331-mz6z9" is pending`

`  Warning  Failed          XXXXX Error: Couldn't find key etcd_endpoints in ConfigMap kube-system/calico-config`

I then ran the following as per offical docs
```kops rolling-update cluster --cloudonly --master-interval=1s --node-interval=1s --yes```

Which upgraded all the nodes but the validation is still a failure due to error above.

Can I terminate the master the which originally failed?

Any help is appreciated

**Comment by juris** [comment]
Got the same issue when upgrading from 1.11.10 to 1.12.9 with kops 1.12.2. First master upgraded without issues. This one happened during second master upgrade.

**Comment by GMartinez-Sisti** [comment]
I had to force rollout all the masters twice when upgrading from 1.11.9 to 1.12.9. This happened in two separate clusters. But only in one the calico-complete-upgrade failed.

Both of them are working fine, and I can't find any evidence of problems, either with etcd 3.x or calico.

**Comment by grv231** [comment]
Just encountered the same issue while upgrading the cluster from 1.12.8 to 1.12.10. In calico-configmap, I dont see any etcd endpoints after update/rolling-update on both master/nodes. ANy solution to this problem?

**Comment by GMartinez-Sisti** [comment]
@grv I was able to fix that by doing another rollout. That will finish the upgrade hopefully.

**Comment by grv231** [comment]
Strange issue. I tried to do a force rolling update, didn't work. So I went ahead and manually changed the **calico-config.yaml** file in kube-system namespace to include etcd_endpoints (which included adding/removing some stuff), that worked in my case

**Comment by cn-5p1ke** [comment]
@grv231 What exactly have you added? Could you show, please configmap?

**Comment by grv231** [comment]
I still dont think the errors for me are 100% resolved, but I was able to validate the cluster in that given time. PS, I didnt have RBAC enabled on this test cluster

In my case, I manually added the field `etcd_endpoints` in the configmap and also changed the `last-applied-configuration`, which was a pain. I was able to get the `calico-kube-controllers` pod working at that given time (which was in failed/pending state) due to which my cluster was not getting validated.

However, I still see differences between my other clusters compared to this one. For example, I see:

- Pods - `etcd-manager-events-ip` in test cluster
- Pods - `etcd-server-events-ip` in other clusters. 
- Moreover, I dont see `etcd-server-ip` pods at all in test cluster at all

Cluster seem to be running okay for now (inter pod communication), but I believe I will have to troubleshoot something real soon.

**Comment by cn-5p1ke** [comment]
@grv231 Got it, thanks!

**Comment by grv231** [comment]
I will keep this thread posted, would be doing some testing on this to see where things might be going wrong

**Comment by grv231** [comment]
Just so you know, there was a separate issue raised in KOPS similar to this. You can check it (here)[https://github.com/kubernetes/kops/issues/7093]. I followed the steps and was able to resolve it.

Basically the deployment for `calico-kube-controllers` has to be scaled down to 0 as now the functionality is in-built in _calico-node_. Is this the right solution? Not sure

**Comment by grv231** [comment]
@cn-5p1ke I think this issue can be **closed**. The solution for this is to move the version to 1.13. I recently did and was able to resolve all the issues as there has been a PR fix for this in the 1.13 version.
