### ISSUE TITLE
alternative to kops gpu hook?

### ISSUE THREAD

**Issue by hhuuggoo** [kubernetes/kops#7147]
Just a question:

I understand that this basically installs nvidia device drivers because kops can't ship an ami that has nvidia drivers (for legal reasons)

https://github.com/kubernetes/kops/blob/master/hooks/nvidia-device-plugin/image/files/nvidia-device-plugin.sh

Is a feasible alternative for users to build their own AMIs with nvidia drivers, and thus not need the hook?

Thanks!

**Comment by rdrgmnzs** [comment]
Hi @hhuuggoo yep, that is completely feasible. In fact I do so for private use.

**Comment by hhuuggoo** [comment]
@rdrgmnzs thanks!
