### ISSUE TITLE
Does Kops support --topology private in GCP?

### ISSUE THREAD

**Issue by amruthapbhat** [kubernetes/kops#7156]
Hi,

I tried creating a cluster in GCP using the KOPS create command and wanted to create it in a private topology, the instances got created but the master and nodes had a public IP assigned to it.

Could you please let me know how i could create a cluster in GCP under private topology.

**Comment by thecloudgeek** [comment]
bump....same here....couldn't find an option to do that on my end.

**Comment by amruthapbhat** [comment]
any update on this please?
