### ISSUE TITLE
Persistent volume for Prometheus operator?

### ISSUE THREAD

**Issue by ashishxooa** [kubernetes/kops#7159]
The prometheus add-on is great to install prometheus operator on the Kubernetes cluster. However I am not able to persist the prometheus data in a persistent volume which would be very much recommended for a production setup. How can we do that easily without modifying the entire yaml ? 

Also how do I modify some basic configuration in the Prometheus like scrape duration, retention period etc. 

Regards,
Ashish

**Comment by ashish235** [comment]
Can anyone please help me with this?
