### ISSUE TITLE
Custom Pod Labels on K8s Components

### ISSUE THREAD

**Issue by gregbacchus** [kubernetes/kops#7168]
It would be very useful to be able to provide additional pod labels for the kubernetes components (e.g. KubeControllerManager and KubeScheduler) in the cluster configuration.

I see there was an earlier issue for changing a label from e.g. `app: kube-scheduler` to `k8s-app: kube-scheduler`. For working with the **prometheus-operator**, the label needs to be `component: kube-scheduler`. Unfortunately, due to how the helm value merging works, I don't believe that it's possible to change that requirement. So therefore I figured that being able to add my own labels to the components would be a good solution for this... and most likely very useful for others in the future as well.

**Comment by youwalther65** [comment]
@gregbacchus  kube-prometheus-stack Helm chart now provides a way to modify the services it creates:
```shell
$ cat values-kops.yaml
...
## Component scraping kube scheduler
##
kubeScheduler:
  enabled: true
  ## If using kubeScheduler.endpoints only the port and targetPort are used
  ##
  service:
    enabled: true
    selector:
      k8s-app: kube-scheduler
## Component scraping the kube controller manager
##
kubeControllerManager:
  enabled: true
  ## If using kubeControllerManager.endpoints only the port and targetPort are used
  ##
  service:
    enabled: true
    selector:
      k8s-app: kube-controller-manager
´´´
