### ISSUE TITLE
Mixed Instance Policy Rebalancing 

### ISSUE THREAD

**Issue by granular-ryanbonham** [kubernetes/kops#7173]
With kops 1.12.1 we have a gap in our support of Mixed Instance Policies. Currently when the cluster autoscaler scales down an instance, this can cause the instance group to no longer meet the mix of instance lifecycles (on-demand vs spot) as defined in the mixed instance policy.

AWS will see this and issue a re-balance which will scale out and add the correct instance lifecycle then scale in one that is the wrong instance lifecycle.  Because this scale in  action is triggered by AWS and not the cluster autoscaler it will occur without a drain on the node, cause pods to SIGTERM and cause traffic interruption. If corends is on the node, this can cause DNS lookup failures on the cluster.

There are two solutions. Both solutions have been vetted with AWS Support. Solution 1 has been tested and we are currently using.

1. We can add support for setting the "new-instances-protected-from-scale-in" flag on the asg. By setting this protection, AWS will not attempt to re balance the nodes via scale-in and will only attempt to balance during cluster initiated scale-outs.

**PROS**

- Simple solution
- Prevents extra scale-in scale-out events

**CONS**
- Can lead to a imbalance of instance lifecycles from what the user defined in the mixed instance policy.

2. We can add support for setting the ASGs Lifecycle hooks, and then the users can run something like https://github.com/logicmonitor/k8s-asg-lifecycle-manager

**PROS**
- Maintains correct balance of instance lifecycles. 

**CONS**
- More node scale in scale-outs that may mean more pod disruption.
- More complex setup

**Proposal**

We improve documentation around this re balancing behavior for kops users and support either option by implementing both the ability to set instance protection and lifecycle hooks on the ASG.
:

**Comment by chrisz100** [comment]
I am in favor of the first way.

**Comment by mikesplain** [comment]
Thanks for the writeup @granular-ryanbonham, much appreciated.  

I agree, I think the first idea is easy enough to add (I'll work up a PR since Ryan is busy).
