### ISSUE TITLE
Could not retrieve location for AWS bucket

### ISSUE THREAD

**Issue by markAcomm** [kubernetes/kops#7175]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.12.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.10

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
AWS_PROFILE=kops kops create cluster ${NAME} --state="${KOPS_STATE_STORE}"  --master-count 1 --master-size t3.medium --node-count 2 --node-size t3.small --zones ${ZONES} --topology private --networking weave --admin-access 10.1.0.0/16  --out=. --target=terraform -v 100

**5. What happened after the commands executed?**
error reading cluster configuration "dev.supply_chain.k8.local": error reading s3://bucket-name /dev.supply_chain.k8.local/config: Could not retrieve location for AWS bucket <bucket-name>

**6. What did you expect to happen?**
I expect a set of Terraform plans and KOPS data configurations to be produced

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

did not get far enough to product a cluster manifest

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

```
I0621 14:29:25.565091   35148 factory.go:68] state store s3://bucket-name 
I0621 14:29:25.941044   35148 s3context.go:191] unable to get bucket location from region "ap-southeast-1"; scanning all regions: InvalidBucketName: The specified bucket is not valid.
	status code: 400, request id: F38997C151238BA0, host id: /sBQRuxQPE9yufw7qOvCPG2TZlS37Uz0MfiMpq7VvUgBO6X6loq7VMhG4+lqIQ0avBHAWpiFeok=
I0621 14:29:26.158314   35148 s3context.go:294] Querying S3 for bucket location for bucket-name 
I0621 14:29:26.158841   35148 s3context.go:299] Doing GetBucketLocation in "eu-west-2"
I0621 14:29:26.158863   35148 s3context.go:299] Doing GetBucketLocation in "ap-south-1"
I0621 14:29:26.159342   35148 s3context.go:299] Doing GetBucketLocation in "ap-southeast-2"
I0621 14:29:26.159458   35148 s3context.go:299] Doing GetBucketLocation in "us-west-1"
I0621 14:29:26.159260   35148 s3context.go:299] Doing GetBucketLocation in "eu-west-1"
I0621 14:29:26.159413   35148 s3context.go:299] Doing GetBucketLocation in "us-east-1"
I0621 14:29:26.158887   35148 s3context.go:299] Doing GetBucketLocation in "sa-east-1"
I0621 14:29:26.159296   35148 s3context.go:299] Doing GetBucketLocation in "ca-central-1"
I0621 14:29:26.159324   35148 s3context.go:299] Doing GetBucketLocation in "ap-southeast-1"
I0621 14:29:26.159321   35148 s3context.go:299] Doing GetBucketLocation in "ap-northeast-2"
I0621 14:29:26.159385   35148 s3context.go:299] Doing GetBucketLocation in "ap-northeast-1"
I0621 14:29:26.159384   35148 s3context.go:299] Doing GetBucketLocation in "eu-north-1"
I0621 14:29:26.159442   35148 s3context.go:299] Doing GetBucketLocation in "us-east-2"
I0621 14:29:26.159446   35148 s3context.go:299] Doing GetBucketLocation in "eu-central-1"
I0621 14:29:26.158854   35148 s3context.go:299] Doing GetBucketLocation in "us-west-2"
I0621 14:29:26.159017   35148 s3context.go:299] Doing GetBucketLocation in "eu-west-3"

```
**9. Anything else do we need to know?**
I have tried a large number of different permutations including putting all AWS parameters into environment variables. The bucket is in the same account as the IAM account. I even tried moving the bucket to us-east-1 to remove any LocationConstraint issues. None of it worked. However, running the command: 
aws s3api get-bucket-location --bucket bucket-name --profile=kops
returns:
```
{
    "LocationConstraint": "ap-southeast-1"
}
```
Which I believe is the correct response. So, the only conclusion I can come to is that the kops GetBucketLocation command does not seem to work (at least in my context)

**Comment by markAcomm** [comment]
For anyone coming across this.

I managed to get past this issue by opening up a new terminal window, stripping away any assumptions about credentials or config shared files and passing everything in by environments variables. Specifically: AWS_REGION,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY and all kops named objects were explicitly named on the command line. This is not really a sustainable approach for my environment, but managed to get me moving forward. I firmly believe I likely have something wrong with my configs that is incompatible with what kops expects, but have not found the smoking gun yet so that others might speed up their troubleshooting.

I regularly use Terraform (another Golang-based app that uses AWS APIs and stores state in an S3 bucket) heavily and my machine config works pretty well with that. If I do figure out what was wrong, I will try to update it here for others.

**Comment by lmansur** [comment]
In my case, I had `AWS_ACCESS_KEY` and `AWS_SECRET_KEY` set in the environment with credentials for a different account. 

`unset AWS_ACCESS_KEY AWS_SECRET_KEY` then `export AWS_PROFILE=my-profile` worked for me.

**Comment by nabinbhusal80** [comment]
I did 
`export AWS_PROFILE=my_profile`
It resolved for me
