### ISSUE TITLE
Supporting spot blocks instances for 1 to 6 hours

### ISSUE THREAD

**Issue by fribourgpierre** [kubernetes/kops#7190]
**General**
AWS provides a way to guarantee that a spot instance won't be killed for a certain amount of time: spot blocks. It allows to block a spot instance for at least 1 to 6 hours and make sure a computation that is time related will go to the end.

**Current state**
Currently it seems that we can't manage spot blocks through kops.

**Feature request**
Would be nice to have a way to declare such instances using kops.

**Comment by nhoughto** [comment]
We wrote this as a workaround, isnt perfect but gets the job done

https://github.com/bsycorp/spot-keeper
