### ISSUE TITLE
coreos cloudinit supoport

### ISSUE THREAD

**Issue by Deshke** [kubernetes/kops#7213]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

as a operator i would like to use coreOS images, but the current cloudInit implementation does not allow for image/OS specific overwrites 

current state is that the bash cloud init script has only legacy support within coreOS but the spot fleet setup breaks that. coreOS uses a yaml description of the configuration 

https://coreos.com/os/docs/latest/cloud-config.html

a general overwrite option for the userdata may be useful

**Comment by mazzy89** [comment]
I'd recommend here to think about Ignition rather than cloud-init since it is not anymore under active development as stated in the official documentation

> NOTE: coreos-cloudinit is no longer under active development and has been superseded by Ignition. For more information about the recommended tools for provisioning Container Linux, refer to the provisioning documentation.

**Comment by sekka1** [comment]
I am running into this issue when using CoreOS with the Spot Fleet options also.
