### ISSUE TITLE
kops v1.12.1 still shipped with vulnerable docker-ce?

### ISSUE THREAD

**Issue by jeffrichiefs** [kubernetes/kops#7216]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.12.1
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`docker version`
**5. What happened after the commands executed?**
admin@ip-172-31-123-76:~$ docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false

**6. What did you expect to happen?**
`docker-ce` to be a non-vulnerable version

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

[jrichie@jrichie-mbp] : ~/workspace ✕  kops get --name aix-staging.k8s.local -o yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-03-13T17:09:42Z
  name: xxxxx
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: xxxx
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.7
  masterInternalName: xxxx
  masterPublicName: xxxxx
  networkCIDR: 172.31.0.0/16
  networkID: vpc-xxxxx
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.31.32.0/19
    name: us-east-2a
    type: Public
    zone: us-east-2a
  - cidr: 172.31.64.0/19
    name: us-east-2b
    type: Public
    zone: us-east-2b
  - cidr: 172.31.96.0/19
    name: us-east-2c
    type: Public
    zone: us-east-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-13T17:09:42Z
  labels:
    kops.k8s.io/cluster: xxxx
  name: master-us-east-2a
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
  machineType: m4.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2a
  role: Master
  subnets:
  - us-east-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-13T17:09:42Z
  labels:
    kops.k8s.io/cluster: xxx
  name: nodes
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
  machineType: m4.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-2a
  - us-east-2b
  - us-east-2c

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by alexfrancavilla** [comment]
Docker 18.09.3 is available and can be deployed by setting the version in your cluster spec (e.g. `kops edit cluster ${NAME}`).

I don't know why the default version is not been updated as well, though here is the official merge request with tips on how to specify the version correctly: https://github.com/kubernetes/kops/pull/6347#issuecomment-484603123

**Comment by jeffrichiefs** [comment]
Thanks @alexfrancavilla !

I think this is a big issue - every cluster being created with kops is running a vulnerable version of Docker.

**Comment by dignajar** [comment]
Hi,
for Centos the latest version supported is `18.06.3` ?

I tried to update the Kops manifest and apply the changes but broken the cluster, is like is not installed the docker engine.

Kops manifest:
```
  docker:
    version: 18.09.3
```

Logs from the master node after the update.
```
-- The start-up result is done.
Jul 22 09:38:14 ip-172-<>.node. systemd[13562]: Failed at step EXEC spawning /usr/bin/docker: No such file or directory
-- Subject: Process /usr/bin/docker could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
```

**Comment by hakman** [comment]
@jeffrichiefs I think this is fixed by https://github.com/kubernetes/kops/pull/7860.
