### ISSUE TITLE
Cross compiling / building

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#722]
I am **very** reluctant to bring this up, but wondering if we have any plans to support our PC friends?

IE: [Cross compiling](https://github.com/golang/go/wiki/WindowsCrossCompiling) for Windows..

... Or any other platforms?

<img width="206" alt="screen shot 2016-10-25 at 12 58 51 am" src="https://cloud.githubusercontent.com/assets/13757818/19675986/d241fa98-9a4e-11e6-8c92-d274714b1db1.png">

**Comment by chrislovecnm** [comment]
RUN ... no good point.  We need to figure it out

**Comment by yissachar** [comment]
I've started trying to get this to work on my Windows environment which as MsysGit installed.

Issues encountered so far:

1. We [assume](https://github.com/kubernetes/kops/blob/master/Makefile#L24) Unix style env vars separated by `:`. In Windows they are separated by `;`.
2. No [sha1sum](https://github.com/kubernetes/kops/blob/master/Makefile#L67-L71) executable exists. I've created #1924 since we shouldn't really require sha1sum to always exist, only if you are running a command that needs it.
3. Once the above two issues were dealt with I ran into the following:

```
$ make
go build  -ldflags "" -o c:/Users/yissachar/go//bin/go-bindata k8s.io/kops/vendor/github.com/jteeuwen/go-bindata/go-bindata
cd c:/Users/yissachar/go//src/k8s.io/kops; c:/Users/yissachar/go//bin/go-bindata -o upup/models/bindata.go -pkg models -ignore="\\.DS_Store" -ignore="bindata\\.go" -ignore="vfs\\.go" -prefix upup/models/ upup/models/...
cd c:/Users/yissachar/go//src/k8s.io/kops; c:/Users/yissachar/go//bin/go-bindata -o federation/model/bindata.go -pkg model -ignore="\\.DS_Store" -ignore="bindata\\.go" -prefix federation/model/ federation/model/...
go install  -ldflags "-X k8s.io/kops.Version=1.5.1 -X k8s.io/kops.GitVersion=069a917 " k8s.io/kops/cmd/kops/...
vendor\github.com\docker\docker\pkg\term\windows\ansi_reader.go:14:2: cannot find package "github.com/Azure/go-ansiterm" in any of:
        c:\Users\yissachar\go\src\k8s.io\kops\vendor\github.com\Azure\go-ansiterm (vendor tree)
        c:\Go\src\github.com\Azure\go-ansiterm (from $GOROOT)
        c:\Users\yissachar\go\src\github.com\Azure\go-ansiterm (from $GOPATH)
vendor\github.com\docker\docker\pkg\term\term_windows.go:11:2: cannot find package "github.com/Azure/go-ansiterm/winterm" in any of:
        c:\Users\yissachar\go\src\k8s.io\kops\vendor\github.com\Azure\go-ansiterm\winterm (vendor tree)
        c:\Go\src\github.com\Azure\go-ansiterm\winterm (from $GOROOT)
        c:\Users\yissachar\go\src\github.com\Azure\go-ansiterm\winterm (from $GOPATH)
vendor\github.com\spf13\cobra\command_win.go:9:2: cannot find package "github.com/inconshreveable/mousetrap" in any of:
        c:\Users\yissachar\go\src\k8s.io\kops\vendor\github.com\inconshreveable\mousetrap (vendor tree)
        c:\Go\src\github.com\inconshreveable\mousetrap (from $GOROOT)
        c:\Users\yissachar\go\src\github.com\inconshreveable\mousetrap (from $GOPATH)
c:\Program Files (x86)\Grep\usr\local\wbin\make.exe: *** [kops] Error 1
```

Any ideas on how to procede?

**Comment by justinsb** [comment]
For the separator, I don't know make well enough.  We could maybe override GOPATH as well, as we don't really need it, but I worry that would cause more edge-cases.  Another option is to build for Windows, but not build _on_ Windows.  This is how we produce the MacOS binary, for example.

To add the 3 missing dependencies:
https://github.com/kubernetes/kops/blob/master/docs/development/dependencies.md

Although we can probably start thinking about looking at the official go dep tool now.

**Comment by yissachar** [comment]
Ah, I guess these dependencies are platform specific? I think that's what was confusing me. I was wondering why there were no issues with the dependencies on other platforms.

In any case, there were other issues with more missing commands, so for now I've taken the path of least resistance and am using the Linux Subsystem for Windows instead.

**Comment by shavo007** [comment]
lucky you @yissachar . im on windows 7!!

get issue when checking out repo:

```
 git checkout release
fatal: cannot create directory at 'vendor/github.com/docker/distribution/contrib/docker-integration/generated_certs.d/localregistry:5440': Invalid argument


```

**Comment by msnelling** [comment]
@shavo007 Getting the same issue, did you make any progress?

**Comment by shavo007** [comment]
Give up on windows! I run in Ubuntu VM at work or my Mac at home.

**Comment by justinliew** [comment]
The issue I'm seeing on Windows (Win10+WSL) is with the docker distribution:

`fatal: cannot create directory at 'vendor/github.com/docker/distribution/contrib/docker-integration/generated_certs.d/localregistry:5440': Invalid argument`

It looks like they fixed this here: https://github.com/docker/distribution/pull/1716 by generating the certs for the integration tests. Is this something we can update to better support Windows users?

**Comment by chrislovecnm** [comment]
@justinliew more context please

**Comment by justinliew** [comment]
If I run `git checkout release` (or `go get -d k8s.io/kop`) I eventually get the message above. Specifically I think it doesn't like the : in the path.

The docker project fixed this (see PR link in my previous message) by generating these files rather than requiring they be checked out.

This is Windows 10, with WSL (Windows Subsystem for Linux).

**Comment by chrislovecnm** [comment]
I have kops.exe compiling on osx for windows.  If someone wants to take a test drive :) https://github.com/kubernetes/kops/pull/3770

**Comment by duizendnegen** [comment]
I'd be happy to take it for a test drive @chrislovecnm - I couldn't find the binary attached to the last release, should I look somewhere else?

**Comment by chrislovecnm** [comment]
@duizendnegen you have to build the binary yourself off of master
