### ISSUE TITLE
Support Microk8s?

### ISSUE THREAD

**Issue by PhilAndrew** [kubernetes/kops#7220]
I would like to try out kops in a single computer environment before I deploy it to Amazon, it would be useful to be able to use Microk8s with Kops but I do not see any documentation on how to do that.

Would this be easy to do with changes to configuration values? or it needs more work?

**Comment by RyzeNGrind** [comment]
Hi I am also interested in hearing about support for MicroK8s with KOps. Any updates on this? Anything we can do to contribute to get this started?

**Comment by olemarkus** [comment]
Sorry no one replied to this one. This issue is closed though. Can you create a new issue where you describe the motivation for this?
