### ISSUE TITLE
CloudProvider "openstack" not supported with etcd-manager

### ISSUE THREAD

**Issue by daniel-yavorovich** [kubernetes/kops#7227]
Hi!

I have some troubles with deploy Kubernetes into OpenStack using Kops.

**Kops Version**: 1.14.0-alpha.1 (git-c9866fb)

**Kubectl Client Version**: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Cloud provider**: OpenStack

**Kops create cluster command and  debug output**: https://gist.github.com/daniel-yavorovich/bb17d39b0ef36b7e8429061e5cc740e3

Kops can't create cluster, because etcdmanager looks like [does not support](https://github.com/kubernetes/kops/blob/master/pkg/model/components/etcdmanager/model.go#L362) openstack cloud provider.

**Kops Cluster manifest:** https://gist.github.com/daniel-yavorovich/d243e5a5f1d7c53758b6c6cd7ea1653e

Also I have attached volume types list:

```]$ openstack volume type list
+--------------------------------------+------+-----------+
| ID                                   | Name | Is Public |
+--------------------------------------+------+-----------+
| 1d465f4b-94c3-4ccc-889d-94e2e65822b3 | rbd1 | True      |
+--------------------------------------+------+-----------+
```

I checked several kops versions - from stable to the master branch.
I also checked version 0.12.0, but everywhere etcdmanager looks without the support of the openstack cloud provider.

Is there some kind of kops branch in which there is full openstack support? if not, when is it planned?

Thank you.

/sig openstack

**Comment by drekle** [comment]
Hey @daniel-yavorovich,

Sorry for the delayed reply.  While this was not supported we have been able to deploy clusters with the `Legacy` provider in the etcdCluster section in a cluster config
```
  etcdClusters:
  - cpuRequest: 200m
     name: main
     provider: Legacy
```

However support for etcd-manager has recently merged.  Perhaps @zetaab can speak to it.

Thanks

**Comment by styk-tv** [comment]
@zetaab any input please?

**Comment by zetaab** [comment]
etcd-manager support is added to 1.14.0-beta.2 release. Alpha does not have OpenStack etcd-manager support

**Comment by styk-tv** [comment]
@zetaab thank you for confirming here.

**Comment by zetaab** [comment]
@daniel-yavorovich can you close this ticket

**Comment by daniel-yavorovich** [comment]
Thank you so much!
