### ISSUE TITLE
go fmt && go vet

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#723]
Can we add `go fmt` and `go vet` to our travis CI builds?

If either commands need attention, can we fail the build?

I am secretly hoping this _encourages_ us to get these into our `make` targets

**Comment by chrislovecnm** [comment]
Do it ;)

**Comment by justinsb** [comment]
Please do :-).  We do have a makefile target `make gofmt` that will apply gofmt, but I don't think we enforce.

I thought `go vet` was in our CI, but if not :+1:

**Comment by chrislovecnm** [comment]
oh and we need a linter ... imports are all funky monkey.  Funky Monkey == not in Goimports format

@JuJu227 what did you end up using?

**Comment by JuJu227** [comment]
I personally like https://github.com/golang/lint for the linter. However, I would actually go a step beyond gofmt and move towards goimports. It's basically  a superset of gofmt but it also cleans up formats the imports in the correct manner.

**Comment by chrislovecnm** [comment]
Did we do this?

**Comment by chrislovecnm** [comment]
We still need format, but vet is working

**Comment by chrislovecnm** [comment]
already done :)
