### ISSUE TITLE
Update CNI plugin to 07a8a28637e97b22eb8dfe710eeae1344f69d16e

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#724]
User jkemp on slack found an issue with the version of CNI we are using (it assigned .255), and @dcbw pointed out we are using an older CNI plugin.

The current CNI plugin in kube-up/salt is 07a8a28637e97b22eb8dfe710eeae1344f69d16e.  That corresponds to a git sha: https://github.com/containernetworking/cni/commit/07a8a28637e97b22eb8dfe710eeae1344f69d16e

We should probably update the hard-coded version we are using, and make this a parameter (which can also be updated by kops upgrade).
- [x] Update hard-coded version
- [ ] Make this a parameter
- [ ] Have kops upgrade update this

**Comment by chrislovecnm** [comment]
@JuJu227 this is low hanging fruit btw.  To do the initial update.

**Comment by justinsb** [comment]
cf https://github.com/kubernetes/kubernetes/issues/30338
https://github.com/kubernetes/kops/issues/626

**Comment by chrislovecnm** [comment]
Please update this on what #730 did :)

**Comment by justinsb** [comment]
We updated this, and there's a magic env var.  Further progress is dependent on CNI figuring out packaging.
