### ISSUE TITLE
kubectl command: Unable to connect to the server: EOF

### ISSUE THREAD

**Issue by ajouve** [kubernetes/kops#7245]
I have a kubernete server running for months on AWS installed with kops 1.11.0.

I do not know why when I am running a `kubectl` command to my server from my deploy pipeline or my local computer I have 

```
Unable to connect to the server: EOF
```

All my services seems to work well

The read operations are on the master

nodes versions: 1.11.7
master version: 1.11.6

I can ssh into my master but no idea of command I can run to help

The cluster is running since five monthes without problems and since two days I have the issue. 

On my elb view, the master ec2 instance is `OutOfService `

**Comment by xfangfang** [comment]
I meet the same problem. (I am new to k8s) 
Do you solve this?

**Comment by ajouve** [comment]
@xfangfang yes my api container was down on the master, 

I did not restore it the good way, i destroyed everything trying to restore it, if something can give us the good practice

Running `docker ps` on my master I has 0 containers running

**Comment by xfangfang** [comment]
@ajouve 
You can go to **master:/var/log** to see the logs. **daemon.log** help me a lot.
I found that the main reason for the problem was that I couldn't download some files in China.
And I solved this by :
1. build an AWS ami with docker and docker image below.

```
images=( etcd-amd64:3.2.24 pause-amd64:3.0 kubernetes-dashboard-amd64:v1.10.1 k8s-dns-sidecar-amd64:1.14.13 k8s-dns-kube-dns-amd64:1.14.13
k8s-dns-dnsmasq-nanny-amd64:1.14.13 cluster-autoscaler:v1.12.0 cluster-proportional-autoscaler-amd64:1.4.0)
for image in ${images[@]} ; do
  sudo docker pull gcr.azk8s.cn/google_containers/$image
  sudo docker tag gcr.azk8s.cn/google_containers/$image k8s.gcr.io/$image
  sudo docker rmi gcr.azk8s.cn/google_containers/$image
done
sudo docker tag  k8s.gcr.io/pause-amd64:3.0 gcr.io/google_containers/pause:3.0
images=(kubernetes-helm/tiller:v2.14.1 )
for image in ${images[@]} ; do
  sudo docker pull gcr.azk8s.cn/$image
  sudo docker tag gcr.azk8s.cn/$image gcr.io/$image
  sudo docker rmi gcr.azk8s.cn/$image
done
images=(kopeio/etcd-manager:3.0.20190516  kope/dns-controller:1.12.0 weaveworks/weave-npc:2.5.1 weaveworks/weave-kube:2.5.1)
for image in ${images[@]} ; do
  sudo docker pull $image
done
```

2. upload some file to s3. [aws-china.md#offline-mode](https://github.com/kubernetes/kops/blob/master/docs/aws-china.md#offline-mode)
I use :
`KUBERNETES_VERSION=v1.12.8 `
` KOPS_VERSION=1.12.2`

This works fine in china. And it's faster.
