### ISSUE TITLE
migration of k8s cluster from 1.10.11 to 1.12.10 failed behind proxy

### ISSUE THREAD

**Issue by kushalgangan** [kubernetes/kops#7250]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
**1.12.2**

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
**1.12.10**

**3. What cloud provider are you using?**
**AWS**
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops rolling-update cluster <cluster_name> --yes
**5. What happened after the commands executed?**

**unexpected error during validation: error listing nodes: Get https://api-cemo-instance-k12-dev-pfm6pg-4567902526.eu-central-1.elb.amazonaws.com/api/v1/nodes: EOF** 

**6. What did you expect to happen?**

we are migrating k8s from 1.10.11 to 1.12.10 behind squid proxy, the upgrade went successful when cluster is provisioned without proxy.
we are getting below issue in etcd-events pod :
```
I0715 08:41:47.429156   22959 volumes.go:85] AWS API Request: ec2/DescribeVolumes
W0715 08:42:17.429570   22959 boot.go:44] error during attempt to bootstrap (will sleep and retry): unable to attach master volumes: error querying for EC2 volumes: RequestError: send request failed
caused by: Post https://ec2.eu-central-1.amazonaws.com/: dial tcp 54.239.55.155:443: i/o timeout
```

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
[cluster-yaml.log](https://github.com/kubernetes/kops/files/3391704/cluster-yaml.log)

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by dignajar** [comment]
Yeap, same problem here. https://github.com/kubernetes/kops/issues/7228

**Comment by Artiax** [comment]
As a workaround you should be able to use the EC2 VPC Endpoint which has solved the issue for us.
