### ISSUE TITLE
Default master size is too small

### ISSUE THREAD

**Issue by robinpercy** [kubernetes/kops#728]
As per my slack conversation with @justinsb and @chrislovecnm. The current default master size of m3.medium only has a single core, which is insufficient for scheduling a CNI provider DS on the master. 

The telltale symptom is that weave-net claims to install correctly, but is schedule for 0 nodes:

> $kubectl create -f  https://git.io/weave-kube
> daemonset "weave-net" created
> $ kubectl describe ds --all-namespaces
> Name:    weave-net
> Image(s):   weaveworks/weave-kube:1.7.2,weaveworks/weave-npc:1.7.2
> Selector:   name=weave-net
> Node-Selector: <none>
> Labels:     name=weave-net
> Desired Number of Nodes Scheduled: 0
> Current Number of Nodes Scheduled: 0
> Number of Nodes Misscheduled: 0
> Pods Status:   0 Running / 0 Waiting / 0 Succeeded / 0 Failed

As per justinsb, the workaround is to scale down one of the bigger pods on the master by reducing the number of CPU requests in /etc/kubernetes/manifests.  

Suggested fixes discussed were to either have Kops do the scaling down of pods, change the default master size, and/or give a warning when the master is too small)

Link to the original convo: https://kubernetes.slack.com/archives/sig-aws/p1477438810008524

**Comment by chrislovecnm** [comment]
So the master size is a bit too small period, if we cannot install 1 ds on it...

**Comment by chrislovecnm** [comment]
We gotta do initial sizing docs, may as well do them here

**Comment by justinsb** [comment]
An m3.medium _should_ be plenty big enough.  We are likely just over-requesting CPU allocation.

**Comment by justinsb** [comment]
This was due to over-requesting CPU, not due to an actual lack of CPU.  This should be fixed in kops 1.4.4 (I believe), but is definitely working fine on the current master branch.

**Comment by justinsb** [comment]
I've tested with single-CPU masters, even small t2 instances.  The master is slow, but it typically works in the end.  Our recommended sizes remain unchanged, but people can use t2 instances :-)

Closing, but please reopen if not fixed using kops 1.5.0 beta1 or later.
