### ISSUE TITLE
official kope.io images in China regions(cn-north-1 and cn-northwest-1)?

### ISSUE THREAD

**Issue by pahud** [kubernetes/kops#7294]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Kops default platform images are published as the `kope.io` alias which is described here
https://github.com/kubernetes/kops/blob/master/docs/images.md#debian

However, we can't find any default platform images in China regions(`cn-north-1` and `cn-northwest-1`) and we have no clue which one is the official account.

**2. Feel free to provide a design supporting your feature request.**

To publish the official platform images to `cn-north-1` and `cn-northwest-1` as well.

**Comment by 5m1** [comment]
As long as more and more end users would like to setup k8s clusters by using kops on AWS China, please kindly support these users to have a published platform images on AWS China, thanks!

**Comment by jecnua** [comment]
Still valid. Please reopen.

**Comment by Wayne-Shen** [comment]
please publish official images on AWS China

**Comment by jecnua** [comment]
Should not lifecycle/rotten and lifecycle/stale be removed when people comment. Ticket still valid and needed. Please don't close our of "inactivity".

**Comment by hakman** [comment]
@rifelpet Considering that starting with Kops 1.18, the default image is the official Ubuntu 20.04 image, is this still needed?
https://github.com/kubernetes/kops/blob/master/channels/stable#L47-L49

**Comment by rifelpet** [comment]
I agree this is no longer needed now that we default to official Ubuntu AMIs.
/close
