### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#731]
I remember someone mentioning that we have a Google budget and AWS access somewhere...

Should we look at integration tests for the next release? Will bring it up in the meeting, but here is the issue to track the work.

**Comment by chrislovecnm** [comment]
https://github.com/zmerlynn Is the man. He is on vacation so will not be on the call tomorrow

**Comment by chrislovecnm** [comment]
And he already has notes in the roadmap... Please close ;)
