### ISSUE TITLE
Error launching editor: unable to launch the editor "vim"

### ISSUE THREAD

**Issue by tasinet** [kubernetes/kops#7318]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.11.1 (git-cb8143c)
Installed via snap on a 5.1.16 kernel Ubuntu

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client: v1.15.1
Server: v1.9.3

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

When I attempt to edit anything:
```
$ kops edit cluster $mycluster

error launching editor: unable to launch the editor "vim"
```
**5. What happened after the commands executed?**

error

**6. What did you expect to happen?**

not error

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

https://gist.github.com/tasinet/8f8d596e62866cf14f6fd3e806a59efd

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

```$ kops edit cluster $mycluster -v 10
I0724 18:27:26.160916   29354 factory.go:68] state store s3://staging-state
I0724 18:27:26.663956   29354 s3context.go:194] found bucket in region "eu-west-1"
I0724 18:27:26.664142   29354 s3fs.go:220] Reading file "s3://staging-state/$mycluster/config"
I0724 18:27:26.819945   29354 s3fs.go:257] Listing objects in S3 bucket "staging-state" with prefix "$mycluster/instancegroup/"
I0724 18:27:26.943853   29354 s3fs.go:285] Listed files in s3://staging-state/$mycluster/instancegroup: [s3://staging-state/$mycluster/instancegroup/master-eu-west-1a s3://staging-state/$mycluster/instancegroup/nodes]
I0724 18:27:26.943946   29354 s3fs.go:220] Reading file "s3://staging-state/$mycluster/instancegroup/master-eu-west-1a"
I0724 18:27:26.988747   29354 s3fs.go:220] Reading file "s3://staging-state/$mycluster/instancegroup/nodes"
I0724 18:27:27.059844   29354 editor.go:127] Opening file with editor [vim /tmp/kops-edit-fl6phyaml]

error launching editor: unable to launch the editor "vim"
```

**9. Anything else do we need to know?**

Fails with other $EDITOR values as well:

```$ EDITOR=nano kops edit cluster $mycluster
error launching editor: unable to launch the editor "nano"
```

absolute paths in $EDITOR didn't have any effect:
```$ EDITOR=/usr/bin/vim kops edit cluster $mycluster
error launching editor: there was a problem with the editor "/usr/bin/vim"
```

`which vim` and `which nano` return `/usr/bin/vim` and `/bin/nano`, which are in $PATH and executable.

~Probably unrelated, but my own machine (not part of this or any cluster) is somewhy running Kubelet, which is in a spawn loop.~ Removed it; no change.

**Comment by tasinet** [comment]
:thinking: I'm wondering if the temp file is created correctly:

```
# ----8<---- #
I0725 10:33:52.377136    8676 editor.go:127] Opening file with editor [vim /tmp/kops-edit-p6w9xyaml]

error launching editor: unable to launch the editor "vim"
$ ls /tmp/kops*
ls: cannot access '/tmp/kops*': No such file or directory
$ sudo find /tmp/*kops*
/tmp/snap.kops
/tmp/snap.kops/tmp
/tmp/snap.kops/tmp/kops-edit-p6w9xyaml
```

Is it possible that snap is meant to chroot to /tmp/snap.kops but that isn't working somehow? Any thoughts on debugging this?

**Comment by tasinet** [comment]
Tried changing the permissions under /tmp/snap.kops to my user. No change.

```
$ cd /tmp
$ ls -ld snap.kops/{.,**}
drwx------ 3 $USER $USER 4096 Jul 29 10:23 snap.kops/./
drwxrwxrwt 2 $USER $USER 4096 Jul 29 10:23 snap.kops/tmp/
-rw------- 1 $USER $USER 1251 Jul 29 10:23 snap.kops/tmp/kops-edit-bpmm2yaml
-rw------- 1 $USER $USER 1251 Jul 29 10:23 snap.kops/tmp/kops-edit-e40dnyaml
```

**Comment by nvanheuverzwijn** [comment]
Can you edit kubernetes object in your cluster with 'kubectl edit object' ? The source code related to your error seems to be using kubectl editor library.
Your problem seems to point more on your environment setup than kops itself.

**Comment by nvanheuverzwijn** [comment]
Relevant part of the code
```go
		edited, file, err = editor.LaunchTempFile(fmt.Sprintf("%s-edit-", filepath.Base(os.Args[0])), ext, buf)
		if err != nil {
			return preservedFile(fmt.Errorf("error launching editor: %v", err), results.file, out)
		}
```
what LaunchTempFile does
```go
	f, err := tempFile(prefix, suffix)
	if err != nil {
		return nil, "", err
	}
	defer f.Close()
	path := f.Name()
	if _, err := io.Copy(f, r); err != nil {
		os.Remove(path)
		return nil, path, err
	}
	// This file descriptor needs to close so the next process (Launch) can claim it.
	f.Close()
	if err := e.Launch(path); err != nil {
		return nil, path, err
	}
	bytes, err := ioutil.ReadFile(path)
	return bytes, path, err
```
what e.Launch does
```go
	if err := (term.TTY{In: os.Stdin, TryDev: true}).Safe(cmd.Run); err != nil {
		if err, ok := err.(*exec.Error); ok {
			if err.Err == exec.ErrNotFound {
				return fmt.Errorf("unable to launch the editor %q", strings.Join(e.Args, " "))
			}
		}
		return fmt.Errorf("there was a problem with the editor %q", strings.Join(e.Args, " "))
	}
```

Most likely, vim is either not installed or the path to your executable is unreachable.

Try setting EDITOR variable to the full executable path rather than just 'vim' i.e `export EDITOR=/usr/bin/vim` or `export KUBE_EDITOR=/usr/bin/vim`. Obviously, make sue /usr/bin/vim works !

Also, make sure you don't have an alias on kops that would overwrite something related to EDITOT variable. Try using full path to avoid using alias.

**Comment by tasinet** [comment]
For anyone else running into this, it was related to snap. Uninstalling the snap version and installing kops manually worked.

@nvanheuverzwijn Thank you for your effort. I missed this notification when it happened.

**Comment by elgamal2020** [comment]
Thanks @tasinet for putting the solution 
for anyone running the issue , Please install it from
