### ISSUE TITLE
Question: Is it really OK to use "100.96.0.0/11" as pod CIDR?

### ISSUE THREAD

**Issue by simnalamburt** [kubernetes/kops#7325]
As all know, Kops has been used 100.96.0.0/11 as default pod CIDR range for a long time.

100.96.0.0/11 is part of 100.64.0.0/10, which is a dedicated space for carrier-grade NAT deployment. And I'm afraid that range shouldn't be used as ordinary private IP according to [RFC6598]:

> Shared Address Space is distinct from RFC 1918 private address space because it is intended for use on Service Provider networks.

> In particular, Shared Address Space can only be used in Service Provider networks or on routing equipment that is able to do address translation across router interfaces when the addresses are identical on two different interfaces.

And many people seem to be concerned about using 100.64.0.0/10 as a private IP address.

> This address block should not be used on private networks or on the public Internet: it is intended only for use within carrier networks.
>
> ["Private network", Wikipedia](https://en.wikipedia.org/w/index.php?title=Private_network&oldid=907939623#Dedicated_space_for_carrier-grade_NAT_deployment)

> Andrew sent me the following question: “I'm pushing to start a conversation about IPv6 in my organization, but meanwhile I've no RFC 1918 space left. What's your take on 100.64.0.0/10 - it's seems like this is available for RFC 1918 purposes, even if not intentionally?”
>
> Short answer: Don’t even think about that!
>
> ["Can I Use Shared (RFC 6598) IPv4 Address Space Within My Network?"](https://blog.ipspace.net/2013/08/can-i-use-shared-rfc-6598-ipv4-address.html?m=1)

I'm becoming more unsure if it's OK to use 100.96.0.0/11 as pod CIDR. There was no serious issue but it seems to misuse. Is it OK to use "100.96.0.0/11" as pod CIDR?

[RFC6598]: https://tools.ietf.org/html/rfc6598

**Comment by justinsb** [comment]
It seems fine for a kubernetes overlay and has avoided conflicts with the VPC CIDRs; if you're uncomfortable you can choose a different range.

If you're using 100.64.0.0/10 on your node network e.g. AWS VPC you'll need to choose a different range.

But, the overlay traffic IPs should only be visible to the Nodes, so the potential for confusion is pretty bounded.  In this regard, this actually feels like the exact same problem as CG-NAT - we have a use case involving isolated traffic, where we don't want to overlap with the RFC1918 blocks.  I see Kubernetes as the "carrier" here, running an isolated network.

We can open it to the wisdom of the crowds though: has anyone encountered a problem (other than if the nodes themselves having 100.64.0.0/10 IPs)?

**Comment by jhohertz** [comment]
Never seen any issues. As the range is private to the cluster, and any traffic that exits gets a NAT to another range, so even if someone on a CGN-based network reaches to a cluster, there will be no conflict.

I guess if you were on an uplink behind a CGN running on metal, you could run into conflicts due to overlap, but CGN is really for mass-residential networks, not cloud providers, so it's not terribly likely you'll run into that.

That said, I certainly did a double-take when I first saw this range being used as well. :smile:

**Comment by simnalamburt** [comment]
Thanks for the explanation. I think it's a well-thought-out decision, so I hope this is documented somewhere.

**Comment by simnalamburt** [comment]
Closing since "100.96.0.0/11" is OK
