### ISSUE TITLE
KOPS weave networking add NO_MASQ_LOCAL

### ISSUE THREAD

**Issue by denmaddog** [kubernetes/kops#7327]
** This is a FEATURE REQUEST**

why: When installing k8s with KOPS and networking set to weave, there is no way to add option NO_MASQ_LOCAL, in order to preserve source IP on pods.
what: Add possibility for this option to be added via KOPS
Cloud provider: AWS
Installation method: KOPS

Versions:
$ weave version: 2.5.1
$ docker version: 18.06.3-ce
$ uname -a: Linux ip-10-11-1-71 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
$ kubectl version: Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T16:08:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:40:54Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

/sig networking
/sig weave

**Comment by mariusv** [comment]
If you run `kops 1.12` then you can either edit the cluster config and add:
```
networking:
    weave:
      mtu: 8912
      nomasqlocal: 1
```
