### ISSUE TITLE
Stale PRs

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#733]
Can we come up with a deadline for open and stale PRs?

I think we add it to the repo, and reference it upon closing a stale PR. Of course they can always be reopened - but in a name of keeping the queue clean I think it's fair to set a reasonable expiration date.. and close PRs with no movement..

Thoughts on our deadline? 15 days? 30 days?

**Comment by chrislovecnm** [comment]
Nope ... PRs stay open forever in k8s. Stale are 20 ish days. We need the bots. @justinsb who is @k8s-bot guru?

**Comment by chrislovecnm** [comment]
Closing
