### ISSUE TITLE
Access to AWS pods as root from docker deamon

### ISSUE THREAD

**Issue by dragan979** [kubernetes/kops#7334]
I created Kubernetes cluster with kops (on AWS), and i want to access to one of my nodes as a root.According to[ this post](https://stackoverflow.com/questions/42793382/exec-commands-on-kubernetes-pods-with-root-access), it's possible only with Docker command. When i type docker ps -a i'm getting nothing. When i was using minikube i solved this issue with `minikube docker-env` and from output i just copied last line into new CMD line `@FOR /f "tokens=*" %i IN ('minikube docker-env') DO @%i` (I'm using Widnows 10) and using above procedure, after typing `docker image ls` i was able to see all minikube pods. Is there any way to do the same: to expose all kops pods to docker service, so when i type `docker image ls `i can see/connect to all pods created with kops with docker command, or is there any kubectl command for this ?

**Comment by nvanheuverzwijn** [comment]
If you created your cluster with a bastion host, you won't be able to reach the nodes' docker daemon. If this is the case, you either need to ssh to the bastion then ssh to a node OR ssh tunnel into your bastion and reach the docker daemon from there.

[you]-ssh->[bastion]-ssh->[node]

Remember that there are multiple nodes which mean multiple docker daemon. It is not recommended to manage the nodes docker daemon directly or change it's state without using kubectl unless you are experimenting stuff.

If you only need to access a shell to a pod, you can simply do `kubectl exec -it PODNAME /bin/sh`. If it doesn't work, it means that the pod does not have a shell installed .

**Comment by dragan979** [comment]
Ok, thanks
