### ISSUE TITLE
Autogen needs to include k8s headers

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#734]
As it stands `make codegen` will clobber the legal k8s headers.. we need a PR to fix this :)

**Comment by chrislovecnm** [comment]
We also need it to be checked in the ci Travis build with the python script in hacks

**Comment by justinsb** [comment]
Which headers are we talking about?

**Comment by kris-nova** [comment]
@justinsb https://github.com/kubernetes/kops/blob/master/doc.go#L1-L15
