### ISSUE TITLE
Feature request: compatibility with gVisor

### ISSUE THREAD

**Issue by thomasjm** [kubernetes/kops#7342]
I would love to be able to spin up a cluster with `kops` that has support for [gVisor](https://gvisor.dev) for security.

gVisor's [kubernetes integration page](https://gvisor.dev/docs/user_guide/kubernetes/) shows that the only production mode option is as a plugin to `containerd`.

I know that the only supported container runtime right now is Docker, and Docker runs against some version of `containerd`. So theoretically maybe I can go through the steps of the [gVisor installation](https://github.com/google/gvisor-containerd-shim/blob/master/docs/untrusted-workload-quickstart.md) and set up `gvisor-containerd-shim` and `runsc` as they describe? Perhaps using some of the techniques in the [Docker runtime execution options docs](https://docs.docker.com/engine/reference/commandline/dockerd/#docker-runtime-execution-options). 

Please correct me if I'm wrong, but it seems like the next step would be to create an [image](https://github.com/kubernetes/kops/blob/master/docs/images.md) based on these modifications and start a cluster with it.

Or is it necessary to wait for explicit support for alternative runtimes in #5524 before this is likely to work? Thanks!

**Comment by jecnua** [comment]
Still valid. Please remove stale flag.

**Comment by jecnua** [comment]
Was my comment ignored? Noice, no worry I am gonna recreate the same ISSUE. Gotta love stale bots :)
