### ISSUE TITLE
Signal Prometheus to scrape etcd

### ISSUE THREAD

**Issue by billyshambrook** [kubernetes/kops#736]
Prometheus can auto discover services to scrape by adding annotations to the pod manifest. Would there be a way of adding arbitrary annotations to the etcd manifest? Falling that, what do you think about just adding it so if people are using Prometheus it just works?

The annotations are described here - https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L73

**Comment by justinsb** [comment]
We should put the annotations on there I think.   As you say, if people aren't using prometheus it won't matter.

My only concern would be whether there is a use case for having prometheus _not_ scrape etcd.  But I think having the visibility is more important.

**Comment by justinsb** [comment]
I think these were added by https://github.com/kubernetes/kops/pull/1314

So this should be fixed in alpha4 (if it's not already fixed in alpha3!)

**Comment by justinsb** [comment]
Believe these annotations are in place if you use kops 1.5.0 beta1 or later - thanks!  Closing, but please comment / reopen if these aren't right?

**Comment by FrederikNS** [comment]
We're running a kops/kubernetes cluster, kops is 1.5.3 and kubernetes is 1.5.2. We have been trying to get our prometheus installation to scrape data from etcd, and stumbled upon this issue.
We do not see the annotation on the etcd pod, but our cluster also predates kops 1.5 and kubernetes 1.5, so is the annotation only added on new clusters?

**Comment by ebbeelsborg** [comment]
It looks to me like the changes merged into master ensure labels such as "k8s-app: etcd-server" on the relevant pod manifests. We do see those after upgrading to kops 1.5.3 so that's dandy. No (Prometheus) annotations though. So, how are those labels meant to yield the requested annotations (automatically)? Should one perhaps create a Service decorated with the desired Prometheus annotations in front of etcd (since one cannot/should not, AFAIK, directly augment the etcd-server pod manifest)? Any hint is appreciated, thanks. @justinsb

**Comment by QuinnBast** [comment]
I am running etcd:3.5.3-0 and it seems this has regressed. There are no `k8s-app` labels on the etcd pods as in the MR that was linked. But I have to agree with ebbeelsborg, how are those labels from that MR supposed to work with prometheus?

I was expecting something like

```
prometheus.io/scrape: "true"
prometheus.io/port: "2381"
```

But these don't exist.

I would throw a Service in front of my etcd pods to expose the metrics but that would only expose one of them - I'd need 3 services, one for each etcd instance. Maybe this is the way to go?

[Etcd has documentation on how to do this](https://etcd.io/docs/v3.1/op-guide/monitoring/#prometheus) but this is specific to a single cluster and I'd rather a more robust way to do it that doesn't break when your IP changes.
