### ISSUE TITLE
Silent failures if nodeup stalls

### ISSUE THREAD

**Issue by brandoncole** [kubernetes/kops#737]
There are scenarios where AMI's have issues on AWS which cause `nodeup` to hang indefinitely with a sequence like this:

```
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
I1027 14:39:28.492837    2424 executor.go:98] No progress made, sleeping before retrying failed tasks
I1027 14:39:38.493028    2424 executor.go:68] Tasks: 43 done / 63 total; 1 can run
I1027 14:39:38.493091    2424 executor.go:138] Executing task "UpdatePackages": UpdatePackages
I1027 14:39:38.493132    2424 reflect.go:40] Calling method Find on *nodetasks.UpdatePackages
I1027 14:39:38.493170    2424 reflect.go:40] Calling method CheckChanges on *nodetasks.UpdatePackages
I1027 14:39:38.493194    2424 update_packages.go:60] running command [apt-get update]
W1027 14:39:43.183696    2424 executor.go:84] error running task "UpdatePackages": error update packages: exit status 100: Hit http://cloudfront.debian.net jessie-backports InRelease
```

In this case the cluster never comes up, the Route53 records never get created and it's in an endless loop.  It would be nice if we could have something like a `--wait` flag for `kops` so that wait loops in the calling shell aren't necessary.

@chrislovecnm would love to hear your comments.

**Comment by justinsb** [comment]
Having a `wait` command would be great, I agree.

Here what is the root cause of the problem?  apt-get got confused?  In the past I have detected that and run the repair command, but I was hoping we wouldn't need it...

**Comment by brandoncole** [comment]
I just noticed this issue too - #588 which is very similar

**Comment by chrislovecnm** [comment]
I ran into this with our image, and have not time to diagnose. We should have the wait command, and a timeout. 

Stability
