### ISSUE TITLE
Cluster created via kops not showing up in GKE console

### ISSUE THREAD

**Issue by kumarlalapet** [kubernetes/kops#7375]
Kops version - 1.13.0

kubectl version

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider - GCP

Just followed the tutorial at https://github.com/kubernetes/kops/blob/master/docs/tutorial/gce.md

Went to GCP console to see the cluster created in Kubernetes Engine section. My cluster did not show up. However kops validate cluster command works and able to see the vm instances in the container engine section.

Is this valid?

**Comment by mamoit** [comment]
kops does not rely on GKE, the cluster will not show up on the GKE console.
it is composed of an ensemble of instances.
if you want to use GKE you don't really need kops, as both serve the same final goal, create and manage a kubernetes server.
