### ISSUE TITLE
Debian buster iptables not compatible with k8s

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#7379]
Debian buster has iptables 1.8.2 (nftables) which is too new for k8s. https://github.com/kubernetes/kubernetes/issues/71305. It means that kube-proxy does not work which leads to situation that cluster does not work.

Temporary solution is available here https://github.com/kubernetes/kubernetes/issues/71305#issuecomment-509394152 after running those commands I can run kops cluster fine with debian buster.

This is not yet critical bug, but we should find solution for this quite fast (before buster images are uploaded to AWS). 

/kind bug

**Comment by zetaab** [comment]
@justinsb @mikesplain  do you have idea what is correct place to insert those 4 commands?

**Comment by justinsb** [comment]
Goodness!  Thanks for drawing attention to it.

I don't mean to discount the importance of fixing this, but is this something that we need to fix prior to releasing kops versions?  I agree we should fix it, but it's not obvious what the right fix is (though I'm pondering your PR - thank you for that!)

**Comment by zetaab** [comment]
Not maybe prior releasing kops versions but before releasing buster k8s base image :)

**Comment by rkojedzinszky** [comment]
Just to add one thing here. Maybe iptables in buster is buggy. According to documentation, -C to iptables is used to check if a rule exists. That is similar what kubelet:

```
# iptables -N KUBE-FIREWALL
# iptables -A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 5 -j DROP
```
And later check if rule exists:
```
# iptables -C KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 5 -j DROP
iptables: Bad rule (does a matching rule exist in that chain?).
```

This of course works with older iptables. And simpler rules also work with 1.8.2.
