### ISSUE TITLE
Kubernetes master also shows up as a minion

### ISSUE THREAD

**Issue by shrinandj** [kubernetes/kops#739]
I deployed a k8s cluster on AWS with kops. One of differences I'm seeing between this and another cluster brought up using kube-up is that the k8s master also shows up as a node in the kops cluster. Wonder if this is intentional. The master has it's own ASG, can have different resources (cpu, mem) than other nodes and the networking can be setup differently for nodes and master. Therefore, there should at least be an option for whether the k8s master should also show up as a node in the cluster.

**Comment by shrinandj** [comment]
In my case, I see that pods on the nodes are getting IPs 100.96.A.B. But the master is not on the same network. So anything scheduled on the master can't reach IPs in the 100.96* range and fail.

**Comment by Shrugs** [comment]
Starting with 1.4, kops uses taints to make the master node unschedulable. If you `kubectl describe nodes | grep Taints` and search for `Taints:`, one of them should have `dedicated=master:NoSchedule`, meaning non-system pods won't be scheduled on it. It does have the unfortunate side effect that you can't easily tell which node is master when running `kubectl get nodes`.

**Comment by shrinandj** [comment]
Great. I see that in my 1.4.3 cluster, the master is "tainted" as described above.

**Comment by Shrugs** [comment]
Agreed, that'd be cool. In this case those feature are kubernetes-level, so you should open an issue on `kubernetes/lkubernetes` to add it.

**Comment by chrislovecnm** [comment]
@shrinandj dude

| Great. I see that in my 1.4.3 cluster, the master is "tainted" as described above.

| it will be good to either (i) make output of "get nodes" mention that node will run user pods or not or (ii) filter the output to not include non-schedulable nodes (with a "-a" option to show all).

dude I missed the -a  ... victory

**Comment by justinsb** [comment]
I see you opened #743, which is great for targeting daemonsets until we get some of the fixes.

We have upstream issues for the underlying networking bug, we also have an issue for kubectl being unhelpful with a tainted master.
