### ISSUE TITLE
add the ability to enable dynamic audit configuration for the API server

### ISSUE THREAD

**Issue by mmerrill3** [kubernetes/kops#7392]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
It would be great to be able to enable the dynamic auditing capability in the kubernetes API server if k8s version >= 1.13 is used

https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#dynamic-backend

Thursday August 8
**2. Feel free to provide a design supporting your feature request.**

**Comment by mstemm** [comment]
+1

**Comment by kris-nova** [comment]
+1

**Comment by mmerrill3** [comment]
Merged
