### ISSUE TITLE
Unable upgrade aws cni from 1.3.0 to v1.5.2

### ISSUE THREAD

**Issue by moruikang** [kubernetes/kops#7399]
I create kubernetes 1.11.6 cluster in aws with kops, and use aws vpc cni.
but when i upgrading aws vpc cni from 1.3.0 to v1.5.3 or other version
`kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2`
amazon-k8s-cni:1.3.0

`kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.5/config/v1.5/aws-k8s-cni.yaml`
After a few seconds it Automatic rollback to 1.3.0
`kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2`
amazon-k8s-cni:1.3.0

how can i upgrade my cni version？

**Comment by tvi** [comment]
Hi,
kops is using channels binary which continuously applies manifest in channel.yaml typically located in s3://<kopsstatebucket>/<clustername>/addons.
I suspect when you kubectl apply, channels will override you change.
You can either:
a) override CNI version in addons
b) create custom channels that overrides CNI version.
This is source of truth for generated channels file:
https://github.com/kubernetes/kops/tree/master/upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni
As you can see kops enables cni 1.15 from k8s version 1.12
