### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#740]
~~https://github.com/kubernetes/helm/blob/master/code-of-conduct.md~~

we need that here

**Comment by chrislovecnm** [comment]
actually that is the wrong one ... https://github.com/kubernetes/kubernetes/blob/master/code-of-conduct.md

**Comment by kris-nova** [comment]
@chrislovecnm - Assigning to you - can you get a PR out please?

**Comment by chrislovecnm** [comment]
Opps

**Comment by chrislovecnm** [comment]
Closing
