### ISSUE TITLE
Support for Capacity-Optimized Spot Instance Allocation Strategy

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/kops#7401]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Support the newly announced `Capacity-Optimized` spot instance allocation strategy.

See: https://aws.amazon.com/about-aws/whats-new/2019/08/new-capacity-optimized-allocation-strategy-for-provisioning-amazon-ec2-spot-instances/

**2. Feel free to provide a design supporting your feature request.**
N/A

Plan to raise a PR to support this today or tomorrow.

**Comment by coufalja** [comment]
Are there any plans to include this in some minor release of 1.14 or 1.15?

**Comment by gjtempleton** [comment]
My feeling as per the [cherry-pick guidelines](https://kops.sigs.k8s.io/development/proposing-a-cherry-pick/) would be that this falls under new functionality and shouldn't be cherry-picked back as far as 1.15 due to it having hit GA now. I've raised #8134 and #8133 to get it into 1.16+ given the current alpha state of those releases.
