### ISSUE TITLE
should we use the bots

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#741]
should we use the k8s bots?

**Comment by kris-nova** [comment]
Context? Use what bots for what purpose?

**Comment by chrislovecnm** [comment]
K8s project has @k8s-bot - it does a lot in k8s.  It is not used outside of K8s /kubernetes/kubernetes, leads of google have talked about it being used.  I do not know if it is ready for us, but if it is, it can help.  We need to determine if it can help or get in the way.

@zmerlynn I am assigning this to you.

**Comment by chrislovecnm** [comment]
@zmerlynn you will get a few items, ping me when you are back so that I can coordinate with you.  We have not talked about this item, but I am guessing you can close this or re-assign it in about a 5 min discussion.

**Comment by chrislovecnm** [comment]
Closing because of this issue https://github.com/kubernetes/test-infra/issues/939 / we are pretty close to where we are auto merging.

**Comment by zmerlynn** [comment]
Actually closing!
