### ISSUE TITLE
unexpected error during validation: error listing nodes: Get https://api.cluster.tibco.in/api/v1/nodes: dial tcp 199.59.242.151:443: i/o timeout

### ISSUE THREAD

**Issue by parsh96** [kubernetes/kops#7438]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.12.2 (git-3fc9bc486)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

As per documentation, create a Route 53 hosted zone and an s3 bucket.
aws-vault exec tibco -- kops create cluster \
       --state "s3://kops-pasha" \
       --zones "us-east-1d,us-east-1f"  \
       --master-count 3 \
       --master-size=t2.micro \
       --node-count 2 \
       --node-size=t2.micro \
       --name tibco.in \
       --yes

**5. What happened after the commands executed?**

when executed the kops create cluster it was able to provision ec2 instances on aws but i was not able to validate the cluster with below error
\[vagrant@localhost \~\]$ aws-vault exec tibco -- kops validate cluster --state=s3://kops-tibco Enter passphrase to unlock /home/vagrant/.awsvault/keys/: Using cluster from kubectl context: cluster.tibco.in

Validating cluster cluster.tibco.in

unexpected error during validation: error listing nodes: Get https://api.cluster.tibco.in/api/v1/nodes: dial tcp 199.59.242.151:443: i/o timeout

**6. What did you expect to happen?**

I should be able to use the kops created cluster.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

only difference from documentation was aws-vault usage .

**Comment by rajatjindal** [comment]
can you please login to the master nodes and check /var/log/syslog and /var/log/kube-apiserver.log

**Comment by dhemeier** [comment]
Hey @parsh96,

the problem is mostly the low resources on t2.micro instances. The masters are not starting fast enough for the 10 min (if i remember correctly) timeout. Wait simply a little bit longer and try to manually  get nodes: `kubectl get nodes`

But please use minimum t2.medium (or t3.medium) for your masters, maybe the resources are so low, that the master cannot start. As @rajatjindal suggested, look directly on the logs on the master. You can also try to reach the api directly over the master (kubectl is available there).

**Comment by maurya-m** [comment]
@parsh96 , @dhemeier , any resolution on this? i am using c4.large as my master, also i noticed the elb healthcheck is failing as result the master instance is OutofService. 

My current configuration : 
kops - 1.14.0
k8s - 1.14.6
Nodes - 3

Any clues what to check , have looked at the SG, routables, . Not sure if something else is missing? 

(Note: had to recreate the cluster by manually deleting the bucket data & resources)  

thanks, please let me know there is other ways to diagnose what may be incorrect.

**Comment by dhemeier** [comment]
Hey @maurya-m,

what say the master components directly on the master. Could you please ssh into and show the logs there? For the kuebelet logs use `journalctl -u kubelet`, for the other components simply `docker ps -a` / `docker logs`. Maybe directly on the master the `kubectl` are working...

**Comment by maurya-m** [comment]
@dhemeier , quick update, i wanted to give final shot at it before winding up today, deleted the cluster, deleted the bucket completely ( not just the object inside it) and then created back the cluster , this time around it got created with no issues. Also deployed bastion server this time around to ssh into the master (private) , but i did not need to , as the cluster validated as ready!! not sure if the bastion host opened some SG rules?

I was creating my cluster using this command below:
kops create cluster --node-count=${CLUSTER_NODE_COUNT} --node-size=${CLUSTER_NODE_SIZE} --zones=${AWS_ZONES} --name=${KOPS_CLUSTER_NAME} --networking amazon-vpc-routed-eni --topology private

**Comment by dhemeier** [comment]
@maurya-m that sounds great! Maybe some old data was the reason for the unreachable cluster. Keep in mind, you can scale the bastion to zero and only start it if you need to ssh into master/nodes.

**Comment by etwillbefine** [comment]
Having the same issue. Pods remain in `ContainerCreating` state. Maybe related: https://github.com/kubernetes/kops/issues/8224

**Comment by chnaveen112** [comment]
after shutdown and restart the my laptop ,when trying to execute this command ,kubectl get nodes ,am facing this error.where i need to check

The connection to the server api.democluster.com was refused - did you specify the right host or port?

**Comment by MoShitrit** [comment]
@chnaveen112 this should probably deserve a new issue with all the relevant info, or you can probably reach out on [#kops-users](https://kubernetes.slack.com/archives/C3QUFP0QM) Slack channel to get more immediate help.
Thanks!

**Comment by kaelzhang** [comment]
> Hey @parsh96,
> 
> the problem is mostly the low resources on t2.micro instances. The masters are not starting fast enough for the 10 min (if i remember correctly) timeout. Wait simply a little bit longer and try to manually get nodes: `kubectl get nodes`
> 
> But please use minimum t2.medium (or t3.medium) for your masters, maybe the resources are so low, that the master cannot start. As @rajatjindal suggested, look directly on the logs on the master. You can also try to reach the api directly over the master (kubectl is available there).

Exactly the same issue for me which is related to t2.micro instances.

It takes much longer for the master node to start.
