### ISSUE TITLE
Revisit kops models

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#744]
Myself and @justinsb have been talking about a future where kops no longer has YAML model files, but rather implements the tasks in code.

Opening a task for feedback and to track a potentially large refactor.

**Comment by kris-nova** [comment]
This might be a missed candidate for 1.5 - this is a huge win for kops - and with the extra help we are getting... this might be remarkably beneficial

**Comment by chrislovecnm** [comment]
So this is a HUGE refactor.  We have to have e2e harness, and MAJOR unit tests in place.  There be BIG dragons....  Really big dragons here.

**Comment by kris-nova** [comment]
We know - but its a necessary evil - and we need to start discussions on this

**Comment by chrislovecnm** [comment]
We have PR inbound thay may help with this ... I am looking through issues to test against #1183 - no promises but we need to test.

@kris-nova comments?

**Comment by kris-nova** [comment]
Closed with #1183
