### ISSUE TITLE
1.14.0.beta.1 missing files from github

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#7453]
1.14.0.beta.1 is missing files from github, this leads to situation that machines cannot be rolling updated (new machines cannot be started because of missing files):

```
Aug 22 13:00:18 ip-172-20-63-214 cloud-init[566]: == nodeup node config starting ==
Aug 22 13:00:18 ip-172-20-63-214 cloud-init[566]: Downloading nodeup (https://github.com/kubernetes/kops/releases/download/1.14.0-beta.1/linux-amd64-nodeup https://kubeupv2.s3.amazonaws.com/kops/1.14.0-beta.1/linux/amd64/nodeup)
Aug 22 13:00:18 ip-172-20-63-214 cloud-init[566]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Aug 22 13:00:18 ip-172-20-63-214 cloud-init[566]:                                  Dload  Upload   Total   Spent    Left  Speed
Aug 22 13:00:19 ip-172-20-63-214 cloud-init[566]: [237B blob data]
Aug 22 13:00:19 ip-172-20-63-214 cloud-init[566]: curl: (22) The requested URL returned error: 404 Not Found
Aug 22 13:00:19 ip-172-20-63-214 cloud-init[566]: == Failed to curl https://github.com/kubernetes/kops/releases/download/1.14.0-beta.1/linux-amd64-nodeup. Retrying. ==
Aug 22 13:00:19 ip-172-20-63-214 cloud-init[566]: All downloads failed; sleeping before retrying
Aug 22 13:00:46 ip-172-20-63-214 dhclient[385]: XMT: Solicit on eth0, interval 66510ms.
Aug 22 13:01:19 ip-172-20-63-214 cloud-init[566]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Aug 22 13:01:19 ip-172-20-63-214 cloud-init[566]:                                  Dload  Upload   Total   Spent    Left  Speed
Aug 22 13:01:19 ip-172-20-63-214 cloud-init[566]: [158B blob data]
Aug 22 13:01:19 ip-172-20-63-214 cloud-init[566]: curl: (22) The requested URL returned error: 404 Not Found
Aug 22 13:01:19 ip-172-20-63-214 cloud-init[566]: == Failed to curl https://github.com/kubernetes/kops/releases/download/1.14.0-beta.1/linux-amd64-nodeup. Retrying. ==
```

I think the retry behaviour was fixed already in https://github.com/kubernetes/kops/pull/7447 

However, now there is broken release in github. Could you @justinsb choose which option is the best 1) upload missing files to github 2) make new release which contains also nodeup fix? (and maybe delete beta.1 because it does not work?)

I am asking this because I broke already 2 clusters :)

/kind bug

**Comment by justinsb** [comment]
Sorry @zetaab ... I realized that I hadn't tested the nodeup behaviour because when we test we override nodeup to use a custom URL (even in e2e).  I pulled it down pretty fast, but not fast enough - sorry :-(

I'm trying to do a beta.2 now - I think that's the best option.  I could also make beta.1 available at the same time if it would help you, but I think beta.1 is just broken...

**Comment by justinsb** [comment]
I uploaded 1.14.0-beta.2 which looks good.  Sorry about that.  Do you think I should upload beta.1 even though it's broken anyway, whether the files are on github or not (because of #7448)

**Comment by zetaab** [comment]
In my opinion beta1 should be either removed completely or then upload files. Maybe I say you could upload those files? Then it does not look weird that if we jumped to beta.2 without using beta 1
