### ISSUE TITLE
Override default security group rules when creating a cluster with amazon-vpc-routed-eni networking

### ISSUE THREAD

**Issue by MoShitrit** [kubernetes/kops#7458]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Created a cluster with `amazon-vpc-routed-eni` as the networking component. 
After doing so, I found that pods running on node are able to hit the `etcd` api directly, which isn't the case on our current clusters running `weave`. After investigating, I found that the masters security group had a rule allowing `All Traffic - ALL - ALL` from the `nodes` security group, while with `weave` that rule doesn't exist (there's a more broken down one which doesn't expose the `etcd` ports).
Looking at the codebase- I found this:
https://github.com/kubernetes/kops/blob/master/pkg/model/firewall.go#L337
Can we somehow configure `kops` _not_ to create this rule if we don't want it to? We are looking to keep `etcd` secure and not accessible to the nodes unless through the k8s api itself. 

**2. Feel free to provide a design supporting your feature request.**
I suppose a simple flag to the cluster creation, or a key-value pair under the `networking` stanza in the `clusterSpec` should be perfect for allowing us to override this configuration. 

Thanks!!

**Comment by mshepet** [comment]
I'm running into the same issue! Would it be possible to override the Security Group configuration in the spec?
