### ISSUE TITLE
NodeLocal DNSCache

### ISSUE THREAD

**Issue by cdobbyn** [kubernetes/kops#7459]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
We should be able to deploy the new NodeLocal DNSCache config as described here and this should be enabled by default.
https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

This allows for a significant reduction in DNS traffic through the cluster.

**2. Feel free to provide a design supporting your feature request.**
There should be an option (which defaults to true):
```
spec:
  kubeDNS:
    nodelocaldns: true
```

Enabling this changes the `--cluster-dns` setting and deploys the following (with settings injected):
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml

Disabling this would remove all related resources and change the --cluster-dns kubelet setting appropriately..

**Comment by cdobbyn** [comment]
Modified my request as this config appears to be possible to implement today with the tools available.

For those of you who want to use this feature today, here are the instructions I used (based on my understanding of the problem). Use at your own risk:

Download this file and replace the following values:
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml
 - `__PILLAR__DNS__DOMAIN__` with `cluster.local`
 - `__PILLAR__LOCAL__DNS__` with `169.254.20.10`
 - `__PILLAR__DNS__SERVER__` with `100.64.0.10`
    - this is directly related to your `nonMasqueradeCIDR` value in kops.

Deploy:
`kubectl apply -f nodelocaldns.yaml`

Enable the feature flag to tell kops to not validate the cluster DNS.
`export KOPS_FEATURE_FLAGS="+ExperimentalClusterDNS" && kops edit cluster`

Set the clusterDNS to the local node dns server ip (by default it's pointing at `100.64.0.10`).
```
spec:
  kubelet:
    clusterDNS: 169.254.20.10
```

**Comment by alok87** [comment]
@justinsb how can we use this feature with kops 1.15 ? Is there a plan to integrate this?

**Comment by alok87** [comment]
@justinsb Can i work on the implementation? ✋

**Comment by olemarkus** [comment]
@justinsb I was looking into implementing this too. Any reason to use an operator for this now? It seems straightforward enough to implement using simple manifests.

**Comment by austinorth** [comment]
This would make this feature way easier to turn on and off for my team when testing in our current workflow.

**Comment by BobbyJohansen** [comment]
I agree this seems like kubernetes core is heading this direction. This could be very helpful

**Comment by BobbyJohansen** [comment]
@justinsb Is there any progress on this?

**Comment by alok87** [comment]
@cdobbyn What should be the values for `__PILLAR__UPSTREAM__SERVERS__` and `__PILLAR__CLUSTER__DNS__` in the latest yaml https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml

**Comment by austinorth** [comment]
@alok87 I actually had a brief conversation with the maintainer about this here: https://github.com/kubernetes/kubernetes/commit/1819c2ea9b2c3b880402826e4f9044456a782a2d In response, he updated the documentation [here](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns#nodelocaldns-addon-template).
So those two values, as mentioned in the documentation, are automatically set by the container image [here](https://github.com/kubernetes/dns/blob/master/cmd/node-cache/app/configmap.go#L67). So you can actually leave `__PILLAR__UPSTREAM__SERVERS__`   and `__PILLAR__CLUSTER__DNS__` there _as is_, not replacing them with values, and those values will be inserted into the yaml by the container itself. I was able to get it working with the default Kops setup once I understood this nuance. Hope that helps! :hugs:

**Comment by alok87** [comment]
Thanks a lot @austbot

**Comment by mazzy89** [comment]
Despite some values are fulfilled automatically, for some like ones below are still needed

`__PILLAR__DNS__SERVER__` - set to kube-dns service IP.
`__PILLAR__LOCAL__DNS__ `- set to the link-local IP(169.254.20.10 by default).
`__PILLAR__DNS__DOMAIN__` - set to the cluster domain(cluster.local by default).

These have to be fetched up and replaced so this is why an approach like the one recommended by @justinsb seems more feasible here.

Not sure @austinorth how you have approached here the problem of fetching those values and replacing them in the manifest.

**Comment by mazzy89** [comment]
Taking ownership of this. Slack reference https://kubernetes.slack.com/archives/C8MKE2G5P/p1584349567098900

I'll wire a PR by adding the node local dns as a classical addon. Spoke abou this with @olemarkus  and seems all fine.

**Comment by austinorth** [comment]
@mazzy89 YESSS! So glad to hear! We didn't see much improvement in our test cluster after implementing due to an unrelated issue, so I ended up just punting on rolling out Node Local to shift my focus elsewhere. I had just been setting those values with a script I wrote to test :sweat_drops:. So excited that this will be integrated into Kops tho; this will make things _way_ easier!

**Comment by mazzy89** [comment]
Wired a PR here https://github.com/kubernetes/kops/pull/8780
