### ISSUE TITLE
Docker 18.09.3 for Centos

### ISSUE THREAD

**Issue by CarpathianUA** [kubernetes/kops#7463]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.13.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.13.9

**3. What cloud provider are you using?**
AWS

According to that PR (merged) https://github.com/kubernetes/kops/pull/6347 there is no possibility to use Docker 18.09.3 with RedHat-based distros. Is it true?

Appreciate your help!

**Comment by marsavela** [comment]
As per https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/docker.go#L664 you have 18.09.3 only for `Debian Stretch`. I stumbled upon this because I am using Ubuntu and I also need it. 🤕

Let's see if I have time to at least test it for my Xenial needs.

**Comment by CarpathianUA** [comment]
Yes, exactly @marsavela 
I also mentioned that. Anf it really confusing me as well :)

**Comment by marsavela** [comment]
@CarpathianUA May I ask why are you looking for `18.09.3` in particular?
You can find higher versions at https://download.docker.com/linux/centos/7/x86_64/stable/Packages/

I just did some testing with 18.09.9 in Xenial and worked as expected. I don't know if I should send a PR though. 😕

**Comment by marsavela** [comment]
@CarpathianUA would be great if you can compile it and test it as well. Maybe we can ping some owners to know if PRs would be a good idea... According to [the guidelines](/kubernetes/kops/blob/master/CONTRIBUTING.md#contributing-a-patch) the repo owners would need to approve this. 🙄

Pinging @mikesplain since he's the one that merged the previous PR #6347

**Comment by marsavela** [comment]
Bumping this back up. Maybe we can get an approval. I already have a branch for Ubuntu...

https://github.com/marsavela/kops/tree/docker-18.09.9

Adding @drekle as well.
