### ISSUE TITLE
Openstack block device mapping support

### ISSUE THREAD

**Issue by Teodor96** [kubernetes/kops#7486]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
In our openstack installation we can't have flavours with root disk. The root disk is defined by the image at the time of creation of the instance and is mounted at the root at the time of creation. To support that in kops we can include the `block_device_mapping_v2` options when creating an instance.

**2. Feel free to provide a design supporting your feature request.**
As an initial iteration we can have it as an on/off option on the instance group definitions. The options for the values needed by the `block_device_mapping_v2` can be gathered from the image.

```json
{
  "boot_index": "0",  # set to 0 always
  "delete_on_termination": true, # set to true always
  "destination_type": "volume", # set to volume 
  "device_name": "vda", # I believe we can default it to vda
  "source_type": "image", # Will always be image
  "uuid": "", # The id of the image
  "volume_size": 20
}
```

`volume_size` as a proof we can default it to the minimum size defined by the image and add it as an option later on.

I would add the option on the instance group as follows.

```yaml
spec:
  osVolumeBoot:
    enabled: true
```

**Comment by zetaab** [comment]
for me this sounds okay, feel free to make PR and verify it in your environment.
