### ISSUE TITLE
Heapster is not able to communicate to node because of SG

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#749]
- heapster is not able to make an http call into kubelet running on the node that heapster is deployed to

Heapster is not able to run on one of your clusters, we have not attempted to recreate with 1.4.4 and kops master

**Comment by justinsb** [comment]
We locked down ports, but explicitly allow 4194.  Closing, but if this is an issue with kops 1.5.0 beta1 or later please reopen.
