### ISSUE TITLE
broken on kubernetes at HEAD due to --node-labels

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kops#7494]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** 

https://storage.googleapis.com/kops-ci/bin/1.14.0-alpha.2+3b0af771e I _think_

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

HEAD of Kubernetes master.

**3. What cloud provider are you using?** AWS, but this applies to all of them.

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops create cluster --name e2e-kops-aws.test-cncf-aws.k8s.io --ssh-public-key /workspace/.ssh/kube_aws_rsa.pub --node-count 4 --node-volume-size 48 --master-volume-size 48 --master-count 1 --zones us-west-1a --master-size c4.large --kubernetes-version https://storage.googleapis.com/kubernetes-release-dev/ci/v1.17.0-alpha.0.1057+0ff92e36f2800b --admin-access 34.68.241.10/32 --cloud aws --override cluster.spec.nodePortAccess=34.68.241.10/32`

AFAICT creating any cluster against a kubernetes master branch build will see this.

**5. What happened after the commands executed?** Cluster creation failed.

`F0830 17:37:47.356585    2825 server.go:184] unknown 'kubernetes.io' or 'k8s.io' labels specified with --node-labels: [kops.k8s.io/instancegroup kubernetes.io/role node-role.kubernetes.io/master]
--node-labels in the 'kubernetes.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set (beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os, failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone, failure-domain.kubernetes.io/region, failure-domain.kubernetes.io/zone, kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/instance-type, kubernetes.io/os)`

**6. What did you expect to happen?** 

We should use allowed node-labels or resolve this upstream.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

N/A this is running in Kubernetes CI. I can't run commands against it. The config etc. comes from kubetest.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A this is running in Kubernetes CI. Logs here https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/1167562732979884033

**9. Anything else do we need to know?**

cc @justinsb

**Comment by leakingtapan** [comment]
Any plan to fix this? I would be happy to help if there is any directions

**Comment by DenysMorgun** [comment]
Is there any workaround for this issue? Have the same on my master's kubelet

**Comment by rifelpet** [comment]
HEAD is now working with the help of the new kops-controller deployment. testgrid shows E2E jobs have been mostly successful and no longer experiencing the --node-labels issue.

/close

**Comment by BenTheElder** [comment]
Thanks!
