### ISSUE TITLE
When we should use --cloudonly flag?

### ISSUE THREAD

**Issue by Aracki** [kubernetes/kops#7507]
A lot of people when doing `kops rolling-update` they add `--cloudonly` flag.

The only description of that flag we can find in manual page is:
```
--cloudonly [Perform rolling update without confirming progress with k8s]
```

When we should use it and vice versa? And why it is even called `cloudonly`?

**Comment by zetaab** [comment]
cloudonly means that rolling update is not calling kubernetes api and verify kubernetes cluster status between the instance upgrade. Instead it will call only cloudprovider apis, for instance AWS apis to do the upgrade.

**Comment by Aracki** [comment]
Thanks 👍
