### ISSUE TITLE
m5.8xlarge not recognized

### ISSUE THREAD

**Issue by photoszzt** [kubernetes/kops#7513]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.12.3
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.12.10
**3. What cloud provider are you using?**
aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
change machine type to m5.8xlarge with "kops edit ig nodes" then "kops update cluster"

**5. What happened after the commands executed?**
nodes.spec.machineType: Invalid value: "m5.8xlarge": machine type specified is invalid
But such machine type exists

**6. What did you expect to happen?**
It accepts the machine type change. 
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by dzoeteman** [comment]
Seems like the instance type has been added in #7195 - but it hasn't gotten into a release yet. Maybe this is one to cherrypick into 1.14?

**Comment by mikesplain** [comment]
@photoszzt, @dzoeteman is correct. AWS resources unfortunately have to be hard coded into Kops at the moment and are tied to releases.  We do our best to keep released versions as up to date as possible but I would suggest upgrading to 1.13.

I'm going to close this but feel free to reopen if you discover a bug here.

Thanks!
