### ISSUE TITLE
Unable to create cluster - kops needs openstack config file

### ISSUE THREAD

**Issue by rs26f** [kubernetes/kops#7516]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.13.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.13.0

**3. What cloud provider are you using?**
Openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster \                                                                                                                                                              
  --cloud openstack \               
  --name xxx-cluster.k8s.local \
  --state ${KOPS_STATE_STORE} \
  --zones xxx \              
  --network-cidr xxx.0.0.0/24 \        
  --image Custom-Ubuntu-18 \
  --master-count=1 \
  --node-count=1 \             
  --node-size cp1.c2.m4g.d100g\  
  --master-size cp1.c2.m4g.d100g\
  --etcd-storage-type s3 \        
  --api-loadbalancer-type public \
  --topology private \
  --bastion \                                                                                                                                       
  --ssh-public-key ~/.ssh/key \
  --networking weave \
  --os-ext-net rs-test-network -v 10 --kubernetes-version 1.13                                                                                                                          

**5. What happened after the commands executed?**
Gives an error: "no such file or directory"

**6. What did you expect to happen?**
Cluster to be created.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
I0903 16:23:10.617192   73904 create_cluster.go:1486] Using SSH public key: /Users/rs/.ssh/KEY
I0903 16:23:10.617590   73904 factory.go:68] state store swift://rs-test-bucket
W0903 16:23:10.617653   73904 swiftfs.go:138] Could not initialize swift from environment: Missing one of the following environment variables [OS_USERID, OS_USERNAME]
I0903 16:23:10.618082   73904 swiftfs.go:109] using openstack config found in /Users/rs/.openstack/config

error building path for "swift://rs-test-bucket": error loading config file: open /Users/rs/.openstack/config: no such file or directory

**9. Anything else do we need to know?**
Openstack access is configured. KOPS state store is set.
Looked at this: https://github.com/kubernetes/kops/issues/7021 and a few other tickets, problems still persists.

**Comment by zetaab** [comment]
you need to export openstack environment credentials. Config file is not supported anymore. https://github.com/kubernetes/kops/blob/release-1.13/docs/tutorial/openstack.md#source-your-openstack-rc

Like the error says it cannot find env variable called `OS_USERNAME` - which could mean that your env variables are not exported correctly.

**Comment by rakeshsehgal1** [comment]
I did export (ran the script from openstack) to before running this. As I am using OS_AUTH_TOKEN the script unsets OS_USERNAME
`  # unset all values not needed for token auth
    unset OS_USER_DOMAIN_NAME
    unset OS_USERNAME
    unset OS_PROJECT_DOMAIN_ID
    unset OS_PROJECT_NAME
`
When I googled around got to https://github.com/gophercloud/gophercloud/blob/master/openstack/auth_env.go#L98
(from: https://github.com/kubernetes/kops/blob/master/util/pkg/vfs/swiftfs.go)
where the condition check on both userid and username which is consistent with what you said.

If I set OS_USERNAME, I then have to set OS_PASSWORD (tried that) but what I want it to do it just use OS_AUTH_TOKEN.

**Comment by zetaab** [comment]
yeah it might be that current solution does not support tokens
