### ISSUE TITLE
Document yaml and have yaml examples

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#752]
- document all possible options for CRUD, for clusters.

@justinsb you mentioned that we can get the yaml from a get?

**Comment by dwradcliffe** [comment]
I tried `-f cluster.yml` but it didn't like that. Also looked at the code but couldn't find where this was supported.

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/blob/master/cmd/kops/create.go#L44 for instance.  Has not been released yet, os you have to build off of master

**Comment by dwradcliffe** [comment]
Ah, it's on the create command but not create subcomands.

Now:
`error: error parsing file "template.yml": no kind "Cluster" is registered for version "v1alpha1"`

**Comment by chrislovecnm** [comment]
Command show the beautiful yaml :)

`kops get cluster --name $NAME -o yaml --full`

**Comment by kenden** [comment]
Doesn't it need:
`kops get instancegroups --state s3://bucket_name/ --name k8s.redacted.net -o yaml` 
also?

**Comment by chrislovecnm** [comment]
Closing due to #2795

**Comment by rdkr** [comment]
Link to docs: [docs/manifests_and_customizing_via_api.md](https://github.com/kubernetes/kops/blob/master/docs/manifests_and_customizing_via_api.md)
