### ISSUE TITLE
CNCF Kubernetes Conformance Certification - kops

### ISSUE THREAD

**Issue by taylorwaggoner** [kubernetes/kops#7523]
@justinsb 

We are very pleased that your product was included in our v1.12 Certified Kubernetes offerings. However, unless you have acquired a newer certification for your product, kops, your Kubernetes v1.12 certification will expire on September 27, 2019.  Your v1.10 and v1.11 certifications will expire as well.

As stated in [Certified Kubernetes Conformance Program](https://github.com/cncf/k8s-conformance/blob/master/terms-conditions/Certified_Kubernetes_Terms.md#qualifying-offerings-and-self-testing) – Terms and Conditions, a Participant’s permission to use the Certified Kubernetes Marks and Participant Kubernetes Combinations with its Qualifying Offerings is time-limited. The Certified Kubernetes Marks and Participant Kubernetes Combinations may be used with a Qualifying Offering for a particular version of Kubernetes (e.g., Kubernetes x.y) until the later of:
12 months after the release date of Kubernetes x.y, or

9 months after the release date of the next minor release (e.g., Kubernetes x.y+1)
v1.12.0 was released on September 27, 2018
[https://github.com/kubernetes/kubernetes/releases/tag/v1.11.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.11.0
)
v1.13.0 was released on December 3, 2018
[https://github.com/kubernetes/kubernetes/releases/tag/v1.12.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.12.0)

Therefore, the expiration date for v1.12 is September 27, 2019.

Please make sure to certify your product for Kubernetes v1.13, v1.14, or v1.15 prior to September 27, in order to have your v1.12 certification remain in effect.  Please note that once Kubernetes v1.16 is released in mid-September, we will only be able to accept v1.14, v1.15, or v1.16 results. We will not be certifying for v1.13 after v1.16 is released, [per these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-versions-of-kubernetes-can-be-certified).  

To view all Certified Kubernetes Distributions & Platforms, please follow this link:
[https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es](https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es)

If you have any questions, please don’t hesitate to reach out to conformance@cncf.io!
Thanks!

**Comment by mikesplain** [comment]
Thanks for the reminder @taylorwaggoner! We will make sure we're verified for 1.13 and 1.14 asap!

**Comment by mikesplain** [comment]
1.13 submitted: https://github.com/cncf/k8s-conformance/pull/707

Thanks for the reminder!

**Comment by mikesplain** [comment]
1.14 submitted: https://github.com/cncf/k8s-conformance/pull/708

**Comment by taylorwaggoner** [comment]
Thank you!
