### ISSUE TITLE
Certificate not updated when adding the load balancer

### ISSUE THREAD

**Issue by dturczanski** [kubernetes/kops#7530]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.13.0 (git-be5fb9019)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I created the cluster with the load balancer. Then updated the cluster to use the DNS api. Then updated the cluster to have the load balancer again.

**5. What happened after the commands executed?**
The certificate doesn't contain the ELB DNS name and I can't use the ELB in my kubectl config to connect. I'm getting ```Unable to connect to the server: x509: certificate is valid for api.internal.kops01.k8s.local, api.kops01.k8s.local, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not api-kops01-k8s-local-d5qhke-1604927758.us-west-2.elb.amazonaws.com```

**6. What did you expect to happen?**
Certificate updated wtih ELB dns name during the cluster update.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-09-06T15:48:09Z
  generation: 2
  name: kops01.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://digitaltoucan-kops01/kops01.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.10
  masterInternalName: api.internal.kops01.k8s.local
  masterPublicName: api.kops01.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  - cidr: 172.20.64.0/19
    name: us-west-2b
    type: Public
    zone: us-west-2b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-09-06T15:48:09Z
  generation: 1
  labels:
    kops.k8s.io/cluster: kops01.k8s.local
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-09-06T15:48:09Z
  generation: 1
  labels:
    kops.k8s.io/cluster: kops01.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: t3a.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
```

**Comment by joshbranham** [comment]
See [here](https://github.com/kubernetes/kops/blob/a8a1f7e33d6aa362a19a9f6cbcb5bd2f57aa7849/docs/apireference/build/documents/_generated_cluster_v1alpha2_kops_concept.md#clusterspec-v1alpha2-kops) on adding `additionalSans` to the API server cert. I would recommend creating an CNAME to your ELB DNS name and adding that DNS name to `additionalSans`

`my-cluster.my-dns.com >  api-kops01-k8s-local-d5qhke-1604927758.us-west-2.elb.amazonaws.com`

```bash
additionalSans:
  - my-cluster.my-dns.com
