### ISSUE TITLE
PVC Not being mounted correctly after a cluster upgrade from 1.4.0 to 1.4.3

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kops#755]
Hi!

Yesterday I upgraded my cluster from 1.4.0 to 1.4.3 using kops and after that 2 PVCs started behaving in a strange way, the pods depending on then would start but keep in CrashLoopBackoff because the mounted volumes did not contain any data inside like all the data from the PVCs was lost. I then sshed to the instance and the EBS volume was not mounted anywhere, I mounted it manually and all the data was there (thanks god)

**Comment by chrislovecnm** [comment]
Upgrades needs tlc, I would not be surprised that this happened. Have not recreated this, but will test ;)

**Comment by felipejfc** [comment]
I tried to terminate the instance but I'm having the same issue with the new one generated by the autoscaling group :/

**Comment by felipejfc** [comment]
@justinsb @chrislovecnm maybe this is related to this issue: https://github.com/kubernetes/kubernetes/pull/33616
?

**Comment by felipejfc** [comment]
Ok, I have more info, the volume were being mounted inside the Pod! It seems that the problem was because all the files inside the mounted volume were with the wrong permissions!
All the files were owned by messagebus:ssh when they should be owned by jenkins:jenkins, is it possible that kubernetes changed the permissions of the files inside the PV?

**Comment by chrislovecnm** [comment]
@felipejfc have not seen that one before.  I am guessing that the user and group id's have changed.

**Comment by justinsb** [comment]
@felipejfc I'm not entirely sure what the current state of user mapping is, to be honest.  Can you open the issue (as you have narrowed it down in https://github.com/kubernetes/kops/issues/755#issuecomment-257287109) in kubernetes/kubernetes.  i.e. that you have a jenkins pod with a PV, files were owned by jenkins, but after an upgrade files were owned by messagebus:ssh.  Hopefully people there will help us figure it out, and figure out the correct workaround.

I'm betting the workaround will be to run `chown -R jenkins /var/lib/jenkins` or something, but we'll see..

Moving to 1.5.1 in the meantime.

**Comment by chrislovecnm** [comment]
Any update on this?
