### ISSUE TITLE
KubeDNS priority

### ISSUE THREAD

**Issue by snelson-pp** [kubernetes/kops#7556]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Currently, kube-dns deployed by kops doesn't specify a pod priority. I'd like to be able to specify a priority for all kube-dns pods. Ideally I'd like to have it default to system-cluster-critical.

**2. Feel free to provide a design supporting your feature request.**

There should be an option:

```
spec:
  kubeDNS:
    priorityClassName: system-cluster-critical
```
which would pass on the priorityClassName to kubeDNS pods.

**Comment by joshbranham** [comment]
Can you provide more details on `kops` and `kubernetes` versions @snelson-pp ?

Going to check some clusters later but I believe this is covered upstream by `kubernetes/kubernetes` for all master components: https://github.com/kubernetes/kubernetes/pull/73857

**Comment by snelson-pp** [comment]
We're running kubernetes 1.13, kops 1.13.

**Comment by snelson-pp** [comment]
Apparently I was mistaken. Closing.
