### ISSUE TITLE
setting bridgeIP to 172.x.x.x does not work

### ISSUE THREAD

**Issue by mwtzzz** [kubernetes/kops#7558]
1. Version 1.12.2

2. Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0"

3. AWS

If I include a docker bridgeIP CIDR of 172.x.x.x, the new cluster hangs on the placeholder api and never gets past it. But if I put something other than a 172.x.x.x it works fine. 

Does not work:
spec:
  docker:
    bridgeIP: 172.15.0.0/16

Works:
spec:
  docker:
    bridgeIP: 192.168.5.1/24

5. kops validate cluster hangs forever at the placeholder api.

6. I expect 172.x.x.x to work as long it doesn't overlap the network-CIDR of the cluster.

**Comment by cheeseandcereal** [comment]
172.15.0.0/16 is not a reserved private CIDR

https://en.wikipedia.org/wiki/Private_network

The IP space that is private for 172.x.x.x is only 172.16.0.0/20
(aka 172.16.0.0 - 172.31.255.255)
