### ISSUE TITLE
https://api.github.com/repos/kubernetes/kops/releases/latest missing 1.13 release

### ISSUE THREAD

**Issue by ryan-dyer-sp** [kubernetes/kops#7563]
1.13 shows up as being released in the Releases tag, but its not showing up in https://api.github.com/repos/kubernetes/kops/releases/latest

Ttried updating kops to 1.13 via 
```
curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
chmod +x kops-linux-amd64
sudo mv kops-linux-amd64 /usr/local/bin/kops
```
as instructed on home page and just getting the latest 1.12 version.

**Comment by joshbranham** [comment]
Yeah this looks to be because `1.12.3` was pushed and adopted the `Latest Release` tag. Not sure the best way around that though.

**Comment by mikesplain** [comment]
Unfortunately in GitHub latest ==literally most recent tag. Therefore if an old branch gets tagged after the most recent branch we can run into cases like this. 

Please just substitute the version you would like.
