### ISSUE TITLE
kops not working in us-gov-east-1

### ISSUE THREAD

**Issue by ibrf** [kubernetes/kops#7564]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.15.0-alpha.1 (git-8087994ac)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.1

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create cluster test.k8s.local  --kubernetes-version 1.11.1 --node-count 1 --vpc vpc-0123456789 --zones us-gov-east-1a

**5. What happened after the commands executed?**

unable to infer CloudProvider from Zones (is there a typo in --zones?)

**6. What did you expect to happen?**

A cluster to launch in us-gov-east-1

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

tac-ml-rfinch:kops_stuff rfinch$ cat tmp.out
I0911 11:04:29.626221   52553 factory.go:68] state store s3://kop-state-store-test
I0911 11:04:30.184419   52553 s3context.go:210] found bucket in region "us-gov-east-1"
I0911 11:04:30.184509   52553 s3fs.go:220] Reading file "s3://kop-state-store-test/test.k8s.local/config"
I0911 11:04:30.636408   52553 channel.go:99] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I0911 11:04:30.636503   52553 channel.go:104] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I0911 11:04:30.636561   52553 context.go:177] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I0911 11:04:30.786340   52553 channel.go:113] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.8.0 <1.9.0"
    - name: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.9.0 <1.10.0"
    - name: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.10.0 <1.11.0"
    # Stretch is the default for 1.11 (for nvme)
    - name: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.11.0 <1.12.0"
    - name: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
      providerID: aws
      kubernetesVersion: ">=1.12.0"
    - providerID: gce
      name: "cos-cloud/cos-stable-65-10323-99-0"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.15.0"
    recommendedVersion: 1.15.3
    requiredVersion: 1.15.0
  - range: ">=1.14.0"
    recommendedVersion: 1.14.6
    requiredVersion: 1.14.0
  - range: ">=1.13.0"
    recommendedVersion: 1.13.10
    requiredVersion: 1.13.0
  - range: ">=1.12.0"
    recommendedVersion: 1.12.10
    requiredVersion: 1.12.0
  - range: ">=1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.0
  - range: ">=1.10.0"
    recommendedVersion: 1.10.13
    requiredVersion: 1.10.0
  - range: ">=1.9.0"
    recommendedVersion: 1.9.11
    requiredVersion: 1.9.0
  - range: ">=1.8.0"
    recommendedVersion: 1.8.15
    requiredVersion: 1.8.0
  - range: ">=1.7.0"
    recommendedVersion: 1.7.16
    requiredVersion: 1.7.0
  - range: ">=1.6.0"
    recommendedVersion: 1.6.13
    requiredVersion: 1.6.0
  - range: ">=1.5.0"
    recommendedVersion: 1.5.8
    requiredVersion: 1.5.1
  - range: "<1.5.0"
    recommendedVersion: 1.4.12
    requiredVersion: 1.4.2
  kopsVersions:
  - range: ">=1.15.0-alpha.1"
    #recommendedVersion: "1.14.0"
    #requiredVersion: 1.14.0
    kubernetesVersion: 1.15.3
  - range: ">=1.14.0-alpha.1"
    #recommendedVersion: "1.14.0"
    #requiredVersion: 1.14.0
    kubernetesVersion: 1.14.6
  - range: ">=1.13.0-alpha.1"
    #recommendedVersion: "1.13.0"
    #requiredVersion: 1.13.0
    kubernetesVersion: 1.13.10
  - range: ">=1.12.0-alpha.1"
    recommendedVersion: "1.12.1"
    #requiredVersion: 1.12.0
    kubernetesVersion: 1.12.10
  - range: ">=1.11.0-alpha.1"
    #recommendedVersion: "1.11.0"
    #requiredVersion: 1.11.0
    kubernetesVersion: 1.11.10
  - range: ">=1.10.0-alpha.1"
    recommendedVersion: "1.10.0"
    #requiredVersion: 1.10.0
    kubernetesVersion: 1.10.13
  - range: ">=1.9.0-alpha.1"
    recommendedVersion: 1.9.2
    #requiredVersion: 1.9.0
    kubernetesVersion: 1.9.11
  - range: ">=1.8.0-alpha.1"
    recommendedVersion: 1.8.1
    requiredVersion: 1.7.1
    kubernetesVersion: 1.8.15
  - range: ">=1.7.0-alpha.1"
    recommendedVersion: 1.8.1
    requiredVersion: 1.7.1
    kubernetesVersion: 1.7.16
  - range: ">=1.6.0-alpha.1"
    recommendedVersion: 1.8.1
    requiredVersion: 1.7.1
    kubernetesVersion: 1.6.13
  - range: ">=1.5.0-alpha1"
    recommendedVersion: 1.8.1
    requiredVersion: 1.7.1
    kubernetesVersion: 1.5.8
  - range: "<1.5.0"
    recommendedVersion: 1.8.1
    requiredVersion: 1.7.1
    kubernetesVersion: 1.4.12

unable to infer CloudProvider from Zones (is there a typo in --zones?)
**9. Anything else do we need to know?**

I'm submitting a pull request to fix this

**Comment by finchr** [comment]
Fix has been merged
/close
