### ISSUE TITLE
support --horizontal-pod-autoscaler-downscale-stabilization

### ISSUE THREAD

**Issue by nporsche** [kubernetes/kops#7570]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Starting from kubernetes v1.12, a new algorithmic update removes the need for the upscale delay.
--horizontal-pod-autoscaler-downscale-stabilization: The value for this option is a duration that specifies how long the autoscaler has to wait before another downscale operation can be performed after the current one has completed. The default value is 5 minutes (5m0s).

this is super important for our business. Is it possible Kops team can support recently?

**2. Feel free to provide a design supporting your feature request.**
Should be similar with https://github.com/kubernetes/kops/pull/3673

**Comment by mikesplain** [comment]
Hi @nporsche, I don't think we'll be doing any more 1.12 releases since we do our best to be backwards compatible.  I've opened cherry-picks to 1.14 and 1.15 since they are our upcoming releases.
