### ISSUE TITLE
kops create -f always requires --state flag and ignores configBase in config file

### ISSUE THREAD

**Issue by voroniys** [kubernetes/kops#7576]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.12.3 (git-e55205471)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

irrelevant

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
 kops create -f config.yaml

**5. What happened after the commands executed?**
```
error: State Store: Required value: Please set the --state flag or export KOPS_STATE_STORE.
For example, a valid value follows the format s3://<bucket>.
You can find the supported stores in https://github.com/kubernetes/kops/blob/master/docs/state.md.
```
The error happens despite `configBase` setting present in the config file.

**6. What did you expect to happen?**

I would expect that with command `kops create -f config.yaml` kops will take all the data from config.yaml and don't need any additional  flags and/or environment variables.

**Comment by prksu** [comment]
hi @voroniys `-f` is used for the filename to use to create the resource, not for kops config. if you want to specify kops config file, you can use `--config` flag. 
kops config and resource/api manifest configuration is something different.
