### ISSUE TITLE
Error creating Flexvolume plugin from directory

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#7592]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops 1.15.0-alpha1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.15.3

**3. What cloud provider are you using?**
openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
created new cluster using kops create cluster

**5. What happened after the commands executed?**
I see lot of spam (and it really spams a LOT) in my kube-controller-manager logs:

```
E0913 21:02:51.079994       1 plugins.go:746] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: invalid character '/' after top-level value
E0913 21:02:51.082568       1 driver-call.go:267] Failed to unmarshal output for command: init, output: "2019/09/13 21:02:51 Unix syslog delivery error\n", error: invalid character '/' after top-level value
W0913 21:02:51.082584       1 driver-call.go:150] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: exit status 1, output: "2019/09/13 21:02:51 Unix syslog delivery error\n"
E0913 21:02:51.082689       1 plugins.go:746] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: invalid character '/' after top-level value
E0913 21:02:51.085434       1 driver-call.go:267] Failed to unmarshal output for command: init, output: "2019/09/13 21:02:51 Unix syslog delivery error\n", error: invalid character '/' after top-level value
W0913 21:02:51.085449       1 driver-call.go:150] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: exit status 1, output: "2019/09/13 21:02:51 Unix syslog delivery error\n"
```

**6. What did you expect to happen?**
I expect that we do not add flexvolume things to all distros (this is needed only in coreos?). I am running debian buster

I think this issue is coming from PR https://github.com/kubernetes/kops/pull/6874 @kellanburket do you have idea?

/kind bug

**Comment by zetaab** [comment]
cc @KashifSaadat

**Comment by mazzy89** [comment]
I'm trying to tackle this issue here https://github.com/kubernetes/kops/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+flatcar

**Comment by mazzy89** [comment]
At the moment the support for distros containers-friendly is broken due to this directory loaded in Calico

**Comment by justinsb** [comment]
The upstream issue seems to be this one: https://github.com/projectcalico/pod2daemon/issues/20

Looks like it wasn't backported to calico 3.8 (yet).  We may have to live with it for 1.14.

**Comment by justinsb** [comment]
I _think_ we might get away with just updating the pod2daemon image, as the only significant change in between is https://github.com/projectcalico/pod2daemon/pull/21 .  Proposing that in #7689, though not sure whether we should do it for 1.14.0.  I'm leaning yes.
