### ISSUE TITLE
Validate addons 

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#7599]
Perhaps I'm missing something, but it looks like we don't have an obvious standard for verifying addons. When folks submit patches like https://github.com/kubernetes/kops/pull/7598 it would be nice to have some way to validate that their changes at least don't blow up the system.

It looks like we're doing some validation on the bootstrap/system-addons in the cloudup tests. But I think these are just checking inputs vs expected manifest outputs. Would it be worth running through addon scenarios during e2e tests? Not sure

**Comment by rifelpet** [comment]
I agree it would be nice to test our addons in the e2e tests. I'm not sure how you could best validate that they work correctly, perhaps as a starting point we could just make sure their pods aren't in a crash loop?

**Comment by olemarkus** [comment]
The next best thing would be to run the manifests through some OPA rules such as deprek8-
