### ISSUE TITLE
Calico - Ability to Enable Master Nodes as BGP Route Reflectors

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/kops#7604]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

This issue is a follow-up to #7158 to further increase the scalability of the Calico CNI option.

Allow users to enable BGP Route Reflectors in Calico as per https://docs.projectcalico.org/v3.9/getting-started/kubernetes/hardway/configure-bgp-peering to reduce the amount of BGP peering sessions required in the cluster at scale and disable the full mesh behaviour used by default.

Calico now (as of >=v3.3.0) has moved Route Reflector support into the `calico/node` container which we already use so this doesn't need to deploy the standalone `calico/routereflector` containers anymore which should hopefully make this easier.

**2. Feel free to provide a design supporting your feature request.**
_Currently WIP - still sketching out how to achieve this properly - any feedback/ideas welcomed_

What enabling this would look like to the user:

```
...
networking:
  calico:
    crossSubnet: true
    bgpRouteReflectors: true
...
```

This would then modify the Calico nodes which were masters to perform as RouteReflectors and create the required BGP Peer calico

**Still to figure out:** 
* How to reliably modify the calico node entries for the master nodes - the documentation recommends performing this through `calicoctl`
* What the impact is of enabling this on a running cluster

**Comment by gjtempleton** [comment]
FWIW I'm unlikely to pick this work up in the near future given we've moved from using Calico to a different CNI internally so this is no longer a priority for me.

**Comment by olemarkus** [comment]
This feature request has been around for some time. Unfortunately, we would require someone to contribute this. But we are happy to review a PR.
