### ISSUE TITLE
Critical pod annotation - used by kube-proxy - is now deprecated

### ISSUE THREAD

**Issue by pracucci** [kubernetes/kops#7605]
The special pod annotation `scheduler.alpha.kubernetes.io/critical-pod` - used by `kube-proxy` run by `kops` (via static manifest file) - has been [deprecated in Kubernetes `1.13`](https://github.com/kubernetes/kubernetes/pull/70298) and we should stop using it in `kops`.

As a side note, there's another issue open https://github.com/kubernetes/kops/issues/6527 discussing the option to run `kube-proxy` as a DaemonSet.

**Comment by pracucci** [comment]
Should we switch to `system-node-critical` priority class, which - [starting from Kubernetes 1.12](https://github.com/kubernetes/kubernetes/pull/74222) - won't get evicted upon node pressure?

**Comment by mmerrill3** [comment]
Regarding backwards compatibility, the old annotation would need to set for existing k8s versions that are < 1.10 (https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/)
