### ISSUE TITLE
Automatically configure subdomain for Route53/Route53 case

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#762]
We can automatically configure NS records for a subdomain in the route53/route53 case.

We should maybe do this.  Or maybe just beef up the documentation.  Maybe even have a video!

**Comment by PendletonJones** [comment]
Even if the process ends up being tedious to automate or people don't have time or something, the section of the kubernetes documentation where they walk you through setting up with kops could benefit from some clarification.
 
In particular it would be very helpful if the following passage were more clear about the fact that you *copy* the NS records created automatically in the hosted zone for the subdomain into the records located in the hosted zone for the parent domain. When you create a hosted zone AWS will not copy these automatically for you as @justinsb educated me earlier. might also be worth mentioning troubling shooting, such as "is your hosted zone accidentally private?"


> You must then set up your NS records in the parent domain, so that records in the domain will resolve. Here, you would create NS records in example.com for dev. If it is a root domain name you would configure the NS records at your domain registrar (e.g. example.com would need to be configured where you bought example.com).
This step is easy to mess up (it is the #1 cause of problems!) You can double-check that your cluster is configured correctly if you have the dig tool by running:
dig NS dev.example.com
You should see the 4 NS records that Route53 assigned your hosted zone.

http://kubernetes.io/docs/getting-started-guides/kops/

**Comment by justinsb** [comment]
I think there are doc changes that are low-hanging fruit here...
