### ISSUE TITLE
Docs Refactor

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/kops#7636]
We've had a number of attempts to refactor our docs into a docs site over the past few years and I'm hoping we can finally get this done soon.  This issue will represent the core refactor, started in #5085.

The major refactor and movement is currently taking place in #7593 

Outstanding issues I would like to address once that merges:

- [] ~Getting an actual site live on github pages~
- [x] Getting the site live on netlify: https://kops.sigs.k8s.io/
- [ ] Reduce spread and duplication of docs 
  - There are quite a few docs that are similar and spread out, many were also not include in the mkdocs site yet out of sheer quantity.  In order to keep #7593 manageable I decided not to be too aggressive on the cleanup.  I think smaller PRs will help us solve this as we go.
  - Feel free to propose changes in the form of PRs and assign them to me, ideas always welcome!
- [x] Breaking down the kops README.md to be smaller with links to subpages in docs.
- [ ] Convert `docs/index.md` and `docs/README.md` to sym link of README.md.
- [ ] Maybe eventually turn strict checking back on, disabling strict check in mkdocs allows docs to exist in the docs folder without being on the github site while we figure out where to organize them.
- [ ] Update video and architecture diagrams

**Comment by mikesplain** [comment]
Based on https://github.com/kubernetes/community/issues/3454, we can request a netlify site setup and work with Sig-docs to setup.  This is likely the best bet for us!

**Comment by mrbobbytables** [comment]
/unassign

woops, meant to assign the k/org issue...too many tabs open
