### ISSUE TITLE
error populating configuration: error getting section of Designate: section 'Designate' does not exist

### ISSUE THREAD

**Issue by pawanku2** [kubernetes/kops#7637]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
kops version
Version 1.14.0-beta.2 (git-783f627ac)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
openstack
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster --cloud=openstack --name=pawan.k8s.cloud.schwarz --state=${KOPS_STATE_STORE} --zones=dea --network-cidr="11.0.0.0/24" --image="ubuntu:xenial" --master-count=1 --node-count=1 --node-size="c1.1" --master-size="c1.2" --etcd-storage-type="standard-iops" --api-loadbalancer-type public --topology=private --bastion --ssh-public-key="~/.ssh/id_rsa.pub" --networking=weave --os-ext-net=floating-net --os-dns-servers=193.148.160.10 -v 10
**5. What happened after the commands executed?**

**6. What did you expect to happen?**
I0920 08:22:15.046606   30712 channel.go:239] version range ">=1.15.0-alpha.1" does not apply to version "1.14.0-beta.2"; skipping
I0920 08:22:15.046757   30712 create_cluster.go:1031] networking mode=weave => {"weave":{}}
I0920 08:22:15.046898   30712 cloud.go:329] authenticating to keystone
I0920 08:22:15.429795   30712 swiftfs.go:109] using openstack config found in /root/.openstack/config

error populating configuration: error getting section of Designate: section 'Designate' does not exist

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
kops get --name pawan.k8s.cloud.schwarz

Cluster.kops "pawan.k8s.cloud.schwarz" not found

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
root@kops:~# kops create cluster --cloud=openstack --name=pawan.k8s.cloud.schwarz --state=${KOPS_STATE_STORE} --zones=dea --network-cidr="11.0.0.0/24" --image="ubuntu:xenial" --master-count=1 --node-count=1 --node-size="c1.1" --master-size="c1.2" --etcd-storage-type="standard-iops" --api-loadbalancer-type public --topology=private --bastion --ssh-public-key="~/.ssh/id_rsa.pub" --networking=weave --os-ext-net=floating-net --os-dns-servers=193.148.160.10 -v 10
I0920 08:36:23.346510    2556 create_cluster.go:1486] Using SSH public key: /root/.ssh/id_rsa.pub
I0920 08:36:23.346680    2556 factory.go:68] state store swift://testpawancon
I0920 08:36:23.346878    2556 swiftfs.go:66] authenticating to keystone
I0920 08:36:24.053732    2556 swiftfs.go:418] Reading file "swift://testpawancon/pawan.k8s.cloud.schwarz/config"
I0920 08:36:24.267263    2556 channel.go:97] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I0920 08:36:24.267306    2556 channel.go:102] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I0920 08:36:24.267360    2556 context.go:159] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I0920 08:36:24.509755    2556 channel.go:111] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.8.0 <1.9.0"
    - name: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.9.0 <1.10.0"
    - name: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.10.0 <1.11.0"
    # Stretch is the default for 1.11 (for nvme)
    - name: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2019-08-16
      providerID: aws
      kubernetesVersion: ">=1.11.0 <1.12.0"
    - name: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-08-16
      providerID: aws
      kubernetesVersion: ">=1.12.0 <1.13.0"
    - name: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
      providerID: aws
      kubernetesVersion: ">=1.13.0 <1.14.0"
    - name: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
      providerID: aws
      kubernetesVersion: ">=1.14.0"
    - providerID: gce
      name: "cos-cloud/cos-stable-65-10323-99-0"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.15.0"
    recommendedVersion: 1.15.3
    requiredVersion: 1.15.0
  - range: ">=1.14.0"
    recommendedVersion: 1.14.6
    requiredVersion: 1.14.0
  - range: ">=1.13.0"
    recommendedVersion: 1.13.10
    requiredVersion: 1.13.0
  - range: ">=1.12.0"
    recommendedVersion: 1.12.10
    requiredVersion: 1.12.0
  - range: ">=1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.0
  - range: "<1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.10
  kopsVersions:
  - range: ">=1.15.0-alpha.1"
    #recommendedVersion: "1.14.0"
    #requiredVersion: 1.14.0
    kubernetesVersion: 1.15.3
  - range: ">=1.14.0-alpha.1"
    #recommendedVersion: "1.14.0"
    #requiredVersion: 1.14.0
    kubernetesVersion: 1.14.6
  - range: ">=1.13.0-alpha.1"
    #recommendedVersion: "1.13.0"
    #requiredVersion: 1.13.0
    kubernetesVersion: 1.13.10
  - range: ">=1.12.0-alpha.1"
    recommendedVersion: "1.12.1"
    #requiredVersion: 1.12.0
    kubernetesVersion: 1.12.10
  - range: ">=1.11.0-alpha.1"
    #recommendedVersion: "1.11.1"
    #requiredVersion: 1.11.0
    kubernetesVersion: 1.11.10
  - range: "<1.11.0-alpha.1"
    recommendedVersion: "1.10.1"
    #requiredVersion: 1.10.0
    kubernetesVersion: 1.11.10
I0920 08:36:24.510211    2556 channel.go:239] version range ">=1.15.0-alpha.1" does not apply to version "1.14.0-beta.2"; skipping
I0920 08:36:24.510406    2556 create_cluster.go:1031] networking mode=weave => {"weave":{}}
I0920 08:36:24.510560    2556 cloud.go:329] authenticating to keystone
I0920 08:36:24.984250    2556 swiftfs.go:109] using openstack config found in /root/.openstack/config

error populating configuration: error getting section of Designate: section 'Designate' does not exist

**9. Anything else do we need to know?**
Cluster to be created

**Comment by zetaab** [comment]
It seems that you do not have designate service installed in your openstack. It means that you need to use gossip dns named. So use cluster name `<placeholder>.k8s.local`

**Comment by pawanku2** [comment]
Thanks Zetaab. Yes after making it local it worked  but now get stuck in some other error.

######################################################################
 Executing task "LB/api.pawan.k8s.local": *openstacktasks.LB {"ID":null,"Name":"api.pawan.k8s.local","Subnet":"dea.pawan.k8s.local","VipSubnet":null,"Lifecycle":"Sync","PortID":null,"SecurityGroup":{"ID":null,"Name":"api.pawan.k8s.local","Description":null,"Lifecycle":"Sync"}}
W0923 07:46:49.206028   27862 executor.go:130] error running task "LB/api.pawan.k8s.local" (6m6s remaining to succeed): Failed to retrieve loadbalancers for name api.pawan.k8s.local: Resource not found
I0923 07:46:49.206087   27862 executor.go:145] No progress made, sleeping before retrying 1 failed task(s)
I0923 07:46:59.206362   27862 executor.go:103] Tasks: 109 done / 118 total; 1 can run
#####################################################################
Command I shave use:

kops create cluster --cloud=openstack --name=pawan.k8s.local --state=${KOPS_STATE_STORE} --zones=dea --network-cidr="11.0.0.0/24" --image="ubuntu:xenial" --master-count=3 --node-count=3 --node-size="c1.1" --master-size="c1.2" --etcd-storage-type="standard-iops"  --topology=private --bastion --ssh-public-key="~/.ssh/id_rsa.pub" --networking=calico --os-ext-net=floating-net  -v 10

I am running this command under openstack  user account which having member role. I am not able to see loadbalancer in my openstack dashboard also.
 My cluster info :
 kops get --name pawan.k8s.local
Cluster
NAME            CLOUD           ZONES
pawan.k8s.local openstack       dea

Instance Groups
NAME            ROLE    MACHINETYPE     MIN     MAX     ZONES
bastions        Bastion m1.amphora      1       1       dea
master-dea-1    Master  c1.2            1       1       dea
master-dea-2    Master  c1.2            1       1       dea
master-dea-3    Master  c1.2            1       1       dea
nodes           Node    c1.1            3       3       dea


kubectl get nodes
NAME   STATUS   ROLES    AGE   VERSION
kops   Ready    <none>   3d    v1.14.6



Is loadbalanecer  important ? In the get nodes I don't see master and minion. and no new vm created? 
Can you please give some guidance what exactly happening?  and what I need to do next?

**Comment by zetaab** [comment]
https://github.com/kubernetes/kops/blob/master/docs/tutorial/openstack.md#using-openstack-without-lbaas but I think you need to update 1.15 alpha. 1.14 does not contain those lbaas changes

**Comment by pawanku2** [comment]
Thanks with 1.15 alpha that error gone. After complete of everything I saw the output :

I0923 10:59:16.467968   23040 context.go:91] deleting temp dir: "/tmp/deploy916696518"
Must specify --yes to apply changes

Cluster configuration has been created.

Suggestions:
 * list clusters with: kops get cluster
 * edit this cluster with: kops edit cluster pawan.k8s.local
 * edit your node instance group: kops edit ig --name=pawan.k8s.local nodes
 * edit your master instance group: kops edit ig --name=pawan.k8s.local master-dea-1

Finally configure your cluster with: kops update cluster --name pawan.k8s.local --yes
#######################################################################

kops get cluster

no clusters found

I see some files get created on my swift container.

cluster.spec
config
instancegroup folder
pki folder

But no backup folder, No openstack VM.


I am not sure whether its done or i have to do something more?
Can you please provide your input, what i need to do next?

**Comment by zetaab** [comment]
Did you read the text? So you need to write `kops update cluster --name pawan.k8s.local --yes`

**Comment by pawanku2** [comment]
Thanks I could able to proceed further . Now VMs get created and get "kops get cluster" I could see the name of cluster but still got one error :

W0924 08:56:11.192706     452 executor.go:130] error running task "Instance/bastions-1-pawan-k8s-local" (2m45s remaining to succeed): Error creating instance: error creating server {{{bastions-1-pawan-k8s-local  xenial  m1.amphora [] [] dea [{ bddf1d69-1d16-4981-9643-899c6b434eac }] map[KopsInstanceGroup:bastions KopsRole:Bastion cluster_generation:0 ig_generation:0 k8s:pawan.k8s.local] [] <nil>    0xc000ba22d0 []} kubernetes-pawan-k8s-local-2e_76_14_de_10_cd_e2_a5_e9_8e_c8_f3_c0_66_66_5a} 0xc0010c4500}: Bad request with: [POST https://platform.cloud.schwarz:8774/v2.1/servers], error message: {"badRequest": {"message": "Flavor's disk is too small for requested image. Flavor disk is 2147483648 bytes, image is 2361393152 bytes.", "code": 400}}

when i check the openstack flavor list
                                                                                |  RAM | DISK |            | VCPU |
| osAyv1W3z2TU5D6h                     | m1.amphora |  1024 |    2    |         0 |     1    | True      |

Is it because of m1.amphora flavor having disk size 2GB?  if yes then why it is going to create amphora VM even though i left the loadbalancer parameter blank like  --api-loadbalancer-type=""?

Is anything i am missing in the configuration . 

kops create cluster --cloud=openstack --name=pawan.k8s.local --state=${KOPS_STATE_STORE} --zones=dea --network-cidr="11.0.0.0/24" --image="xenial" --master-count=3 --node-count=3 --node-size="r1.2" --master-size="r1.2" --etcd-storage-type="standard-iops"  --topology=private --bastion --ssh-public-key="~/.ssh/id_rsa.pub" --networking=calico --os-dns-servers=8.8.8.8,8.8.4.4 --api-loadbalancer-type="" --os-ext-net=floating-net  -v 10
