### ISSUE TITLE
New G4 AWS GPU instance support in nvidia-plugin

### ISSUE THREAD

**Issue by danigosa** [kubernetes/kops#7664]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Support for newest low-cost G4 AWS instances

**2. Feel free to provide a design supporting your feature request.**

https://aws.amazon.com/ec2/instance-types/g4/

**Comment by jhkimac** [comment]
I think nvidia's new gpu operator release will be able to replace nvidia-plugin

https://github.com/NVIDIA/gpu-operator

**Comment by nik13** [comment]
are G4 now supported? I'm not able to use them in cluster. It showing me pending status for the pod.
