### ISSUE TITLE
How to seamlessly perform upgrades in Kubernetes (Skip Minor versions)

### ISSUE THREAD

**Issue by ravvereddy** [kubernetes/kops#7673]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
We are using Kops production ready kubernetes cluster version 1.10.11. We would like to upgrade the cluster from 1.10.11 to the latest stable version i.e 1.13.11 which is not recommended as we are skipping couple of minor version, according to kubernetes doc its recommended to upgrade one minor version at a time. But we have almost 7 Kubernetes clusters out of which 4 are production and if we have to perform this upgrades across all the 7 clusters with a minimal downtime its quite complicated task. We are looking at the community for any help how can we make this upgrade seamless.

There are couple of options which we have tried out.

1. Blue/Greed Upgrade Model  
Create a new cluster within the Same VPC as that of old cluster with the latest kops v1.13.1 and kube v1.13.11 and deploy the apps on new cluster and perform all sanity checks and once all sanity checks are passed do the DNS Cutover and give some Soak time say for 1 week and if no issues are reported we decommission the old cluster.
2. Rolling Upgrade
If at all we have to perform the rolling upgrade across all the 7 clusters, migrate one minor version at a time we may need to perform this for around say 3 * 7 = 21 time which is a time consuming process and we dont want to take this approach, however going further we can go with this approach once we are at the latest version say v1.13.11 or 1.14.0.  

**2. Feel free to provide a design supporting your feature request.**
Any help/recommendation to make this upgrade seamless is appreciated. Going further if we can have some sort of automation which we could think of for both the approached will help lots of user who have a Kops based Production Ready Kubernetes clusters.

Automate the Cluster Upgrader 1.10.x to 1.14.x -> how can we upgrade to the most stable version irrespective of how many no of minor version with min downtime or with zero downtime.
 
Automate the cluster upgrade 1.13.x to 1.14.x -> Rolling upgrade  with min downtime or with zero downtime.

Thanks and Regards
Ravve

**Comment by dhemeier** [comment]
Hey @ravvereddy,

you already read the correct part of the Kubernetes documentation. Please try to upgrade one minor version at a time. I would say the initial problem is not the kops/kubernetes upgrade design, the question is why are you currently running on version 1.10.x and not upgraded in the last months / as soon as new versions are available and stable?

To resolve your outdated state you can do one of the two suggested ways you already mentioned. Which way exactly depends on your configuration. For example, if you use deployments and applications with support horizontal scaling, you can safely do a rolling upgrade without downtime (have always i.e. 2 instances running on different nodes).

Suggestions: Update your cluster configuration without a rolling update to the nodes (only to masters) and create new node groups with the new Kubernetes version. Then you have two node groups (1.10.X -> current workload, 1.11.X -> new and fresh). By draining/moving the deployments to the new version you can upgrade your applications and monitor it. If all works well, complete the upgrade. The way of creating a complete new cluster sounds a little bit more complicated (storage, dns, restore data, ...) and when you had an error, you can only rollback with i.e 24 hours "downtime" (DNS Caching and so on).

Hope that helps you a little. 
If you have questions on how to exactly to this, feel free to contact me.

Dennis
