### ISSUE TITLE
link linter for docs

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#771]
K8s and other projects have a linter that checks the links on markdown documents.

**Comment by justinsb** [comment]
I feel like we could collect these into an issue which is essentially "if kubernetes is going to be multi-repo, we have to figure out how not to copy and paste a bunch of infrastructure between projects."

Also, these should be run by k8s-the-group, using k8s-the-system, in Jobs that run in parallel :-)  Or in Bazel...
