### ISSUE TITLE
Question: Manually Down/Up Scaling Nodes & Master.

### ISSUE THREAD

**Issue by flmmartins** [kubernetes/kops#7739]
Hello All,

Before adding autoscaling with cluster I would like to know how to manually scale a node/master up and down.

Reading the documentation and Googling around I was a bit confused with minSize/maxSize and what they exactly mean. 

Can you confirm these are correct:

1. To scale up during peak hours: I would have to edit the instance group and change the maxSize value and then do an update but I would not have to do rolling update according to instance groups docs. Is that correct?
 
2. To scale down after peak hours. Edit Instance Group to maxSize less than before. Do an Update and Rolling-Update. Assuming this is correct will this drain my nodes and make a soft scale down?

3. To scale up/down and maintain that way: Edit the minSize and do updates and rolling updates (this last one only if you scale down). Is that correct?

**Comment by mitch000001** [comment]
Hi, my understanding and observations of scaling the cluster are as follows:
1. Only minSize is actually scaling the cluster. I.e. when you want to upscale the cluster, change minSize and maxSize to the new values.
2. To downscale, change the values of both fields back to where they were.

One note though: we're running on Openstack, so if you have a different cloud provider this could be different.

**Comment by flmmartins** [comment]
So I did some play around with minSize. I decrease it by I left MaxSize untouched and something went crazy with Autoscaling: https://github.com/kubernetes/kops/issues/7861

So I guess when downscaling you need to change both numbers as pointed by @mitch000001 

I guess to upscale you need only to tweak min (assuming max is bigger then min course)

**Comment by flmmartins** [comment]
So in the end there's no way to control the Desired Number in AWS unless you use Autoscaling.

More here: https://github.com/kubernetes/kops/issues/8786
