### ISSUE TITLE
e2e failure: Kubernetes Dashboard should check that the kubernetes-dashboard instance

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#774]
See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws/1/#k8sio-kubernetes-dashboard-should-check-that-the-kubernetes-dashboard-instance-is-alive

This one has an obvious cause: `kops` doesn't launch the dashboard by default, `kube-up.sh` does.

**Comment by chrislovecnm** [comment]
Lol

**Comment by chrislovecnm** [comment]
@zmerlynn to be clear at this time we don't want `kops` to install anything but the components needed to bootstrap k8s.  Dashboard is NOT required 🙊

**Comment by kris-nova** [comment]
Another use case for extending kops 

https://github.com/kubernetes/kops/issues/791
https://github.com/kubernetes/kops/issues/789

**Comment by MichaelJCole** [comment]
@chrislovecnm I get that.  Also, it would be worth documenting as the dashboard is a great feature of kubernetes.  Here are my notes:

```
# Start Cluster
kops update cluster cluster.stage.example.io --yes

# Test (this needs awhile to start up)
kubectl get nodes --show-labels

# Deploy dashboard
kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml

# Login to web dashboard.   Get password from console.
kubectl config view
sensible-browser https://api.cluster.stage.example.io/ui/
```

**Comment by chrislovecnm** [comment]
I am thinking about baking in the dashboard ... Thoughts?
