### ISSUE TITLE
kops update cluster insists I use unknown flag --dns-zone

### ISSUE THREAD

**Issue by mabushey** [kubernetes/kops#7741]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.13.0 (git-be5fb9019)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Would like to run `kubernetesVersion: 1.13.10`

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
✗  kops update cluster --name=k8s-blue.example.com --state=s3://example.com-k8s                                                                                                                                         
I1004 02:19:23.075332   14928 dns.go:73] Found multiple DNS Zones matching "k8s-blue.example.com", please specify --dns-zone=<id> to indicate the one you want                                                                                
I1004 02:19:23.075360   14928 dns.go:76]        --dns-zone=Z3MR418LYRxxxx                                  
I1004 02:19:23.075368   14928 dns.go:76]        --dns-zone=Z3IH7O2VL6xxxx                                                                                               
I1004 02:19:23.075390   14928 dns.go:76]        --dns-zone=Z3D08031HCxxxx                                                                          
I1004 02:19:23.075402   14928 dns.go:76]        --dns-zone=Z2IJEAMDOWxxxx                                                                              
I1004 02:19:23.075415   14928 dns.go:76]        --dns-zone=Z3BGLQBSIPxxxx                                                                                        
I1004 02:19:23.075427   14928 dns.go:76]        --dns-zone=Z349SLFJ32xxxx                                                                                        
I1004 02:19:23.075440   14928 dns.go:76]        --dns-zone=ZDAWX0K0Wxxxx                                                                                              
I1004 02:19:23.075453   14928 dns.go:76]        --dns-zone=Z2P3NJ23RPxxxx                                                                                                                
I1004 02:19:23.075467   14928 dns.go:76]        --dns-zone=Z14MHY0O4Xxxxx
I1004 02:19:23.075489   14928 dns.go:76]        --dns-zone=Z2LJ7Z34CDxxxx
I1004 02:19:23.075502   14928 dns.go:76]        --dns-zone=Z3KL7SS20Kxxxx
I1004 02:19:23.075515   14928 dns.go:76]        --dns-zone=Z25WCSSSLxxxx
I1004 02:19:23.075528   14928 dns.go:76]        --dns-zone=Z2H7L7HKRMxxxx
I1004 02:19:23.075540   14928 dns.go:76]        --dns-zone=Z2BCGMAXBBxxxx
I1004 02:19:23.075553   14928 dns.go:76]        --dns-zone=Z1MFIPCGNHxxxx
I1004 02:19:23.075567   14928 dns.go:76]        --dns-zone=Z2FIJ44ZMExxxx
I1004 02:19:23.075583   14928 dns.go:76]        --dns-zone=Z1LIQ2LPMLxxxx
I1004 02:19:23.075596   14928 dns.go:76]        --dns-zone=Z2BR8GJ1WKxxxx
I1004 02:19:23.075609   14928 dns.go:76]        --dns-zone=ZQ1ND8K5Zxxxx
I1004 02:19:23.075622   14928 dns.go:76]        --dns-zone=Z3HPZ4GS6Sxxxx
I1004 02:19:23.075634   14928 dns.go:76]        --dns-zone=ZYKCTHXAAxxxx
I1004 02:19:23.075647   14928 dns.go:76]        --dns-zone=Z2VOXRU3G4xxxx
I1004 02:19:23.075660   14928 dns.go:76]        --dns-zone=Z2RLQF8YGDxxxx

✗  kops update cluster --name=k8s-blue.example.com --state=s3://example.com-k8s --dns-zone=Z2RLQF8YGDxxxx                        
Error: unknown flag: --dns-zone
Usage:
  kops update cluster [flags]
...
```

**5. What happened after the commands executed?**
It insists I use a flag (--dns-zone) that it doesn't know about.

**6. What did you expect to happen?**
It to work the first time without it listing every zone in AWS my company uses, the vast majority of which have nothing to do with Kops/K8s.

**Comment by mabushey** [comment]
Ahh it wants --dns-zone back in the `kops create cluster` declaration. It really should give the error at `kops create cluster`, or at least say that's where `--dns-zone` is to be used.

**Comment by timothyclarke** [comment]
I'm encountering this issue as well I used `--dns-zone` in my create cluster syntax. 
In my case I have 1 AWS account. in the same region I have 2 clusters each in their own VPC.
I'm using Terraform to prep the VPC and create the various subnets as the default subnet sizes don't work for us.

Each cluster is created with the following

```
  kops create cluster --state "s3://${KUBERNETES_S3_BUCKET}" \
    --cloud aws \
    --vpc ${K8S_VPC_ID} \
    --subnets ${K8S_SUBNETS} \
    --zones ${K8S_ZONES} \
    --utility-subnets ${K8S_UTILITY_SUBNETS} \
    --topology private \
    --master-count 3 \
    --master-size t2.medium \
    --node-count 2 \
    --node-size r5.xlarge \
    --networking calico \
    --ssh-public-key="terraform/${ENV}_key.pub" \
    --bastion=true \
    --dry-run \
    --dns-zone ${ENV}.${BRAND_NAME}.example.com \
    --encrypt-etcd-storage \
    --cloud-labels "BrandName=${BRAND_NAME},HostType=k8s,TargetEnvironment=${ENV},billing=${BRAND_NAME},environment=${ENV},k8s.io/cluster-autoscaler/${ENV}.${BRAND_NAME}.example.com=owned" \
    -o yaml ${KUBE_NAME} > terraform/${KUBE_NAME}.yaml
```
We ran the resulting yaml through a python script to splice in additional policies (for external-dns) and modify the `Nodes` instance group into a mixed instance policy before then using update to apply the cluster config and so create the cluster. 
Each cluster has it's own s3 bucket for terraform state and kops state
The above has been working quite happy for us for some time and now we've gone back up update the first cluster we're getting the same error as the original poster.
When I look at the DNS zones there is only one that matches the zone I provided. The rest are other zones

**Comment by mabushey** [comment]
@timothyclarke 
> This may be triggered by a zone with the same name in route 53

That's exactly what my problem was, Terraform generated a new zone when the existing zone should have been imported into the Terraform state instead. Not really sure why AWS even allows multiple zones for the same name. I added to my docs to run this before the `kops create cluster`: 
`aws route53 list-hosted-zones-by-name --dns-name $NAME | jq '.HostedZones[] | select(.Name == "'${NAME}'.")'` to verify I have one zone.

**Comment by timothyclarke** [comment]
/remove-lifecycle stale
@mabushey   
> Not really sure why AWS even allows multiple zones for the same name

Lots of good and bad reasons for this, all of which is out of scope. I could have both internal and external versions of the same subdomain. Depending on how strict the multiple zone restriction I could possibly use it as denial of service. If I create a zone `example.com` then no one else could use that domain (zone can only exist once across all of aws) 
We just need KOPS to handle it I can see the follwing options
1) Either by DNS lookup. Going to root nameservers and down
2) All us to use the `--dns-zone` flag
3a) `kops create cluster` should validate that it is not creating a duplicate zone in the same account (that's how it happened to me)
3b) Documentation:  As well as 3a, This is known & not supported. It will generate an error and you will need to remove one of the zones. 

I cannot remember if my example had terraform create the zone so at 3a it should have thrown the error and prevented me from creating the second cluster
