### ISSUE TITLE
Will you support Azure?

### ISSUE THREAD

**Issue by teochenglim** [kubernetes/kops#7742]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Can you support Azure?

**2. Feel free to provide a design supporting your feature request.**

```shell
kops create cluster --cloud azure

```

**Comment by Bessonov** [comment]
Happy new year!

**Comment by ebcarty** [comment]
Seems to be a replica of Issue #3957 .

Propose to close this issue.

**Comment by rifelpet** [comment]
Agreed, it is best to consolidate discussion to that issue

/close
