### ISSUE TITLE
Unsupported argument locals, on terraform plan

### ISSUE THREAD

**Issue by blackcheshire13** [kubernetes/kops#7743]
kops version 1.14.0
 terraform  version 0.12.9
 cloud provider aws
 kubectl version 1.15.0
 
After commands 
kops update cluster \
  --out=. \
  --target=terraform \
  --state ${STATE} \
  --name ${CLUSTER_NAME}
kops generate file kubernetes.tf without errors and warnings , next step 
terraform init - OK
terraform plan - generate next errors:
```
Error: Unsupported argument

  on kubernetes.tf line 1:
   1: locals = {

An argument named "locals" is not expected here. Did you mean to define a
block of type "locals"?
```
```
Error: Unsupported argument

  on kubernetes.tf line 594:
 594: terraform = {

An argument named "terraform" is not expected here. Did you mean to define a
block of type "terraform"?

```
And many errors with type Attribute redefined
```
tag = {

The argument "tag" was already set at kubernetes.tf:200,3-6. Each argument may
be set only once.
```
Please help, maybe i use wrong version terraform? What version terraform need?

**Comment by blackcheshire13** [comment]
Yees, i use wrong version terraform)) Please write on main page - https://github.com/kubernetes/kops/blob/master/docs/terraform.md
KOPS NOT SUPPORTED TERRAFORM > 0.11

**Comment by jiraguha** [comment]
Hey guys,
I have the same issue. What should be done?
Downgrading terraform? Or you will make moves with Kops to make it work with the latest terraform apis?
Thx

**Comment by fred-vogt** [comment]
This is being worked on in #7052 

For now one possible workaround:
*  post-process the kops terraform output and use `terraform 0.12upgrade` to fixup the block assignments

## Details
If kops is creating the default route you'll need to change the resource name to be terraform-12 compliant:
```hcl
resource "aws_route" "0-0-0-0--0" {
  route_table_id         = "${aws_route_table...}"
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = "${aws_internet_gateway...}"
}
```
=&gt;
```hcl
resource "aws_route" "default-0-0-0-0--0" {
  route_table_id         = "${aws_route_table...}"
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = "${aws_internet_gateway...}"
}
```

Same for any additional CIDR-blocks:
```hcl
resource "aws_vpc_ipv4_cidr_block_association" "10-1-0-0--16" {
  vpc_id     = "${aws_vpc....}"
  cidr_block = "10.1.0.0/16"
}
```
=&gt;
```hcl
resource "aws_vpc_ipv4_cidr_block_association" "vpc-cidr-block-10-1-0-0--16" {
  vpc_id     = "${aws_vpc....}"
  cidr_block = "10.1.0.0/16"
}
```

**Comment by smaillns** [comment]
> kops version 1.14.0
> terraform version 0.12.9
> cloud provider aws
> kubectl version 1.15.0
> 
> After commands
> kops update cluster
> --out=.
> --target=terraform
> --state ${STATE}
> --name ${CLUSTER_NAME}
> kops generate file kubernetes.tf without errors and warnings , next step
> terraform init - OK
> terraform plan - generate next errors:
> 
> ```
> Error: Unsupported argument
> 
>   on kubernetes.tf line 1:
>    1: locals = {
> 
> An argument named "locals" is not expected here. Did you mean to define a
> block of type "locals"?
> ```
> 
> ```
> Error: Unsupported argument
> 
>   on kubernetes.tf line 594:
>  594: terraform = {
> 
> An argument named "terraform" is not expected here. Did you mean to define a
> block of type "terraform"?
> ```
> 
> And many errors with type Attribute redefined
> 
> ```
> tag = {
> 
> The argument "tag" was already set at kubernetes.tf:200,3-6. Each argument may
> be set only once.
> ```
> 
> Please help, maybe i use wrong version terraform? What version terraform need?

Having the same problem, did you find a consistent solution ?

**Comment by rifelpet** [comment]
Terraform support has been added in #8825 and will be a part of the next Kops 1.18 release
/close
