### ISSUE TITLE
e2e failure: Services should be able to create a functioning NodePort service

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#775]
See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws/1/#k8sio-services-should-be-able-to-create-a-functioning-nodeport-service

This one is because we're not doing any of the stuff in [`test-setup`](https://github.com/kubernetes/kubernetes/blob/712d3d2cd3abe3bf862f813c0969f04d2454afb2/cluster/aws/util.sh#L1558) for `kops` e2e.

**Comment by chrislovecnm** [comment]
@zmerlynn status on this?

**Comment by justinsb** [comment]
I believe this is still an issue, but we believe it is because we aren't opening ports in the kops e2e setup, rather than an actual kops issue.  Bumping to 1.5.1
