### ISSUE TITLE
Need to reduce cpu requests on master

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#776]
We don't have enough CPU left for a weave/calico daemonset.

Compounded by kubernetes/kubernetes#31369 when using a machine with a single core.

**Comment by chrislovecnm** [comment]
So a couple of choices. First if we are installing cni, we can lower the CPU weave. Secondly which items are sized too large??

**Comment by chrislovecnm** [comment]
Initially going to address this via docs. You need to consider you master size not blindly ;)
