### ISSUE TITLE
Toolbox template won't work unless kubecfg context is set.

### ISSUE THREAD

**Issue by NeoTech** [kubernetes/kops#7763]
I think this could classify as a bug i found while i was setting up kops clusters through a CI build pipeline.. Basically if you dont have a .kube/config with a valid context in it, the `toolbox template` sub commands would not work properly generating the outputted template i needed for creating the cluster in the first place.

> kops version
Version 1.14.0 (git-d5078612f)

For reproducing:
> cat /dev/null > ~/.kube/config
> kops toolbox template --template kops/cluster-template.yaml --values data/values/values.yaml --snippets data/snippets --format-yaml > cluster.yaml
W1010 00:14:20.867704  391884 root.go:251] no context set in kubecfg

// Sets random backup config for any other cluster.
> export KUBECONFIG=~/config-backups/config.titus
> kops toolbox template --template kops/cluster-template.yaml --values data/values/values.yaml --snippets data/snippets --format-yaml > cluster.yaml
Using cluster from kubectl context: cluster/titus-noise

**Comment by perezjasonr** [comment]
I also ran into this. It seems like a common use-case, if not the main use-case to use the toolbox template feature set to make a cluster in the first place so "no context set in kubecfg" feels strange. is there a way around this?
