### ISSUE TITLE
KOPS kubeAPIServer insecurePort partially ignored

### ISSUE THREAD

**Issue by wizard580** [kubernetes/kops#7766]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.13.2 (git-7cfcf8261)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.13.10

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster, kops edit cluster to set `spec.kubeAPIServer.insecurePort: 8888`

**5. What happened after the commands executed?**
cluster up and running, kube-apiserver started with correct param `--insecure-port=8888` but pods port array contains port 8080 with name "local"

**6. What did you expect to happen?**
pods port array contains port 8888 with name "local"

...

**9. Anything else do we need to know?**
If I do not specify "spec.kubeAPIServer.insecurePort" then it defaults to 8080 and pod manifest looks correct to me.

I think issues is here: `https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/kube_apiserver.go#L415`
Line 415 and 416.  
Will changing hardcoded values from "8080" to "b.Cluster.Spec.KubeAPIServer.InsecurePort" fix this?

Please correct me if I'm wrong.

**Comment by tioxy** [comment]
Hi @wizard580 :smile: 

It seems that you are right!
I was checking if probing was also hardcoded, but it isn't.

https://github.com/kubernetes/kops/blob/0dec2cf6d02599b370c6f285e5a6d8daa51d6398/nodeup/pkg/model/kube_apiserver.go#L384-L385

**Comment by wizard580** [comment]
ping

**Comment by wizard580** [comment]
no news?

**Comment by wizard580** [comment]
ping

**Comment by lrodorigo** [comment]
There's a quick way to fix this (e.g. by rebuiling only API machinery), in order to apply the fix ASAP ?
