### ISSUE TITLE
HA cluster creation with 3 masters, only 1 is joining successfully

### ISSUE THREAD

**Issue by vivekpd15** [kubernetes/kops#7767]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.14.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster \
    --node-count 4 \
    --zones us-west-2a,us-west-2b,us-west-2c,us-west-2d \
    --master-count 3 \
    --master-zones us-west-2a,us-west-2b,us-west-2c \
    --node-size t2.large \
    --master-size m3.medium \
    --topology public \
    --networking weave \
    --cloud-labels "Deployment=Production,Team=Vivek" \
    --state s3://kops-cluster \
    --name cluster.vivek.com

**5. What happened after the commands executed?**
Cluster started, 1 of the masters and all other nodes joined. Other 2 masters didn't join.

**6. What did you expect to happen?**
All 3 masters to join the cluster

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-10-05T13:35:42Z
  generation: 1
  name: cluster.vivek.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Deployment: Production
    Team: Vivek
  cloudProvider: aws
  configBase: s3://kops-cluster/cluster.vivek.com
  encryptionConfig: true
  etcdClusters:
  - enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
      volumeIops: 120
      volumeSize: 8
      volumeType: io1
    name: main
  - enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
      volumeIops: 120
      volumeSize: 8
      volumeType: io1
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    cloudProvider: aws
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.14.6
  masterInternalName: api.internal.cluster.vivek.com
  masterPublicName: api.cluster.vivek.com
  networkCIDR: 172.20.0.0/16
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  - cidr: 172.20.64.0/19
    name: us-west-2b
    type: Public
    zone: us-west-2b
  - cidr: 172.20.96.0/19
    name: us-west-2c
    type: Public
    zone: us-west-2c
  - cidr: 172.20.128.0/19
    name: us-west-2d
    type: Public
    zone: us-west-2d
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-10-05T13:35:43Z
  generation: 1
  labels:
    kops.k8s.io/cluster: cluster.vivek.com
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m3.medium
  maxPrice: "0.008"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-10-05T13:35:43Z
  generation: 1
  labels:
    kops.k8s.io/cluster: cluster.vivek.com
  name: master-us-west-2b
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m3.medium
  maxPrice: "0.008"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-10-05T13:35:44Z
  generation: 1
  labels:
    kops.k8s.io/cluster: cluster.vivek.com
  name: master-us-west-2c
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m3.medium
  maxPrice: "0.008"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2c
  role: Master
  subnets:
  - us-west-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-10-05T13:35:44Z
  generation: 1
  labels:
    basic: enabled
    kops.k8s.io/cluster: cluster.vivek.com
  name: nodes
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t2.large
  maxPrice: "0.06"
  maxSize: 8
  minSize: 4
  nodeLabels:
    basic: enabled
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  - us-west-2d

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by vivekpd15** [comment]
Hey guys, any help would be much appreciated here. I am still stuck on this. Is there a problem with the 1.14.0 release?

**Comment by grem11n** [comment]
You have only one `master` group specified in etcd members and etcd events.
Try to add other other `master` groups there
