### ISSUE TITLE
go get k8s.io/kops gives old v1.11.0 version

### ISSUE THREAD

**Issue by povils** [kubernetes/kops#7768]
When I try to install kops module with `go get k8s.io/kops` I would expect it to be the latest version(v1.14.0 ?). But even when I want to specify it, go modules is not able to find it.

**Comment by rifelpet** [comment]
This has been fixed with the most recent stable release 1.15.1. The issue was that the git tags werent prefixed with `v`.  `go get k8s.io/kops` now defaults to the latest stable release as expected.

/close
