### ISSUE TITLE
kops installing docker (18.09.03) even though right version is already install in the machine

### ISSUE THREAD

**Issue by Deepak1100** [kubernetes/kops#7769]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
kops version
Version 1.13.2 (git-7cfcf8261)
```
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`1.12.10`
**3. What cloud provider are you using?**
`AWS`
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Just use following kops image `k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-08-16`  and install docker from kops-configuration or manually and restart kops-configuration.
you will see following logs

```
Oct 10 11:01:28 ip-10-39-41-44 nodeup[1128]: I1010 11:01:28.064708    1128 executor.go:178] Executing task "Package/docker-ce": Package: docker-ce
Oct 10 11:01:28 ip-10-39-41-44 nodeup[1128]: I1010 11:01:28.064741    1128 package.go:142] Listing installed packages: dpkg-query -f ${db:Status-Abbrev}${Version}\n -W docker-ce
Oct 10 11:01:28 ip-10-39-41-44 nodeup[1128]: I1010 11:01:28.070178    1128 changes.go:81] Field changed "Version" actual="5:18.09.3~3-0~debian-stretch" expected="18.09.3~3-0~debian-stretch"
Oct 10 11:01:28 ip-10-39-41-44 nodeup[1128]: I1010 11:01:28.070199    1128 changes.go:81] Field changed "Source" actual="<nil>" expected="https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_18.09.3~3-0~debia
n-stretch_amd64.deb"
```
```
dpkg-query  -W docker-ce
docker-ce	5:18.09.3~3-0~debian-stretch
```
after running kops-configuration i see version as above. so i think prefix keyworkd `5` is missing

**6. What did you expect to happen?**
it should not  install docker if its already install

**Comment by vanakema** [comment]
I believe the concerns noted in this issue have been addressed in #6957
