### ISSUE TITLE
Should automatically install cni manifest

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#777]
Just like we do dns-controller, as otherwise we have to SSH to the master

**Comment by chrislovecnm** [comment]
Can we do this via addons or do we need another enntrypoint?

**Comment by chrislovecnm** [comment]
@razic all yours!

What we talked about

1. add the networking options to actually vendors that are supported
2. leave cni option to leave an option open to install something that is not tested
3. create a new weave option
4. include weave daemonset in the bootstrap addons section as optional (go template)
5. make the weave option include the the weave daemonset on install

Questions?

**Comment by kris-nova** [comment]
1. Version our manifests by vendor 

```
├─ /vendorDir
├────/vendorManifest1.1
├────/vendorManifest1.2
```

2. Can we get a write up on design/proposed approach in the WIP PR

**Comment by chrislovecnm** [comment]
@bboreham this is the ticket that I mentioned.  @razic is going to be taking a stab at it, and basically, we will be moving the weave ds into the source model.  Have some other issues which I have not gotten a chance to test again, but I am guessing most of them are around known CNI issues with K8s.

**Comment by kris-nova** [comment]
Starting on this now

**Comment by chrislovecnm** [comment]
`./upup/models/cloudup/resources/addons/bootstrap-channel.yaml` is the droid you are looking for

**Comment by chrislovecnm** [comment]
Closing this now.
