### ISSUE TITLE
Weave problems at ~ 125 nodes

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#779]
At 125 nodes running the guestbook app, started seeing this error:

```
E1020 03:58:52.832357       5 endpoints_controller.go:514] Endpoints "guestbook" is invalid: [subsets[0].addresses[52].nodeName: Forbidden: Cannot change NodeName for 10.38.0.1 to ip-172-20-92-169.ec2.internal, subsets[0].addresses[97].nodeName: Forbidden: Cannot change NodeName for 10.42.128.1 to ip-172-20-91-115.ec2.internal]
```

**Comment by chrislovecnm** [comment]
This was the same problem that you where probably trying to solve wit sig networking. That exception that you where discussing. I wills check with the weave folks.

**Comment by chrislovecnm** [comment]
Will investigate more

**Comment by rdtr** [comment]
Although I do not use kops and manually deployed k8s cluster by using CoreOS's way, I'm currently seeing the exactly same error message.

`E1101 15:47:49.843097       1 endpoints_controller.go:513] Endpoints "node-exporter" is invalid: [subsets[0].addresses[0].nodeName: Forbidden: Cannot change NodeName for 172.18.64.5 to ip-172-18-64-5.ec2.internal, subsets[0].addresses[1].nodeName: Forbidden: Cannot change NodeName for 172.18.64.6 to ip-172-18-64-6.ec2.internal, subsets[0].addresses[2].nodeName: Forbidden: Cannot change NodeName for 172.18.80.5 to ip-172-18-80-5.ec2.internal, subsets[0].addresses[3].nodeName: Forbidden: Cannot change NodeName for 172.18.80.6 to ip-172-18-80-6.ec2.internal, subsets[0].addresses[4].nodeName: Forbidden: Cannot change NodeName for 172.18.96.6 to ip-172-18-96-6.ec2.internal]`

By default, aws-provider has not been activated and I manually turn it on recently, but not sure it's related. I use Flannel, not Waeve. I have just 5 nodes, 2 masters and 3 workers.

**Comment by chrislovecnm** [comment]
We are having more problems with Weave btw.  Seems that we have dup networks as well.

**Comment by kris-nova** [comment]
Do we need to loop in the Weave gang?

**Comment by chrislovecnm** [comment]
Nope, this needs to be retested, but it is probably was fixed last week with the new image. We where missing ethtool in the image

**Comment by justinsb** [comment]
Closing as believed fixed; we can reopen if reoccurs
