### ISSUE TITLE
The API DNS IP address (203.0.113.123) is the placeholder address is not replaced, validation fails

### ISSUE THREAD

**Issue by anravi** [kubernetes/kops#7790]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.14.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops validate cluster

**5. What happened after the commands executed?**

`INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-us-west-2b	Master	m3.medium	1	1	us-west-2b
nodes			Node	t2.medium	2	2	us-west-2b

NODE STATUS
NAME	ROLE	READY

VALIDATION ERRORS
KIND	NAME		MESSAGE
dns	apiserver	Validation Failed

The dns-controller Kubernetes deployment has not updated the Kubernetes cluster's API DNS entry to the correct IP address.  The API DNS IP address is the placeholder address that kops creates: 203.0.113.123.  Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate.  The protokube container and dns-controller deployment logs may contain more diagnostic information.  Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to start.
`

Validation Failed
**6. What did you expect to happen?**
validation should pass

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-10-14T18:14:11Z
  name: example.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://example.com/example.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west-2b
      name: b
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west-2b
      name: b
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.14.6
  masterPublicName: example.com
  networkCIDR: x.x.x.x/16
  networkID: vpc-xyz
  networking:
    kubenet: {}
  nonMasqueradeCIDR: x.x.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: x.x.x.x/24
    id: subnet-xyz
    name: us-west-2b
    type: Public
    zone: us-west-2b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-10-14T18:14:11Z
  labels:
    kops.k8s.io/cluster: example.com
  name: master-us-west-2b
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-10-14T18:14:11Z
  labels:
    kops.k8s.io/cluster: example.com
  name: nodes
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2b

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

dig ns example.com works fine returns 4 NS servers.

aws s3 ls example.com/example.com/
                           PRE addons/
                           PRE backups/
                           PRE instancegroup/
                           PRE manifests/
                           PRE pki/
                           PRE secrets/
2019-10-14 14:16:56       5401 cluster.spec
2019-10-14 14:14:12       1143 config

route53

api .example.com.   203.0.113.123
api.internal.example.com.   203.0.113.123

**Comment by S-Collison** [comment]
I'm seeing a similar issue with dns-controller. Have you checked dns-controller logs for route53 errors, specifically an InvalidChangeBatch error?
