### ISSUE TITLE
[Help] Clean up  static check failures 

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/kops#7800]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
There are many packages that can't pass the static check and we need to clean them up even though hack/verify-staticcheck.sh exsits in the kops.
Step 1: Remove some packages(related packages) from the list in https://github.com/kubernetes/kops/blob/master/hack/.staticcheck_failures , 
Step 2: Run hack/verify-staticcheck.sh and look at outputs from console
Step 3: Fix them to ensure that  hack/verify-staticcheck.sh runs cleanly
Step 4: Run hack/verify-bazel.sh  and hack/verify-gofmt.sh  to make sure that you fix any problems with bazel or gofmt.
Step 5: How to make prs?
* For existing contributor,make sure there lists are up to date.
* advice title begins with staticchek: 
* Don't use Fixes: #7800 which will shut down the issue,just use Ref:#7800
* example for description
```
https://github.com/kubernetes/kops/pull/8203#issue-356845565
```
Attention: if you have any questions
read this https://github.com/kubernetes/kops/blob/master/docs/development/vendoring.md

**Comment by rendhalver** [comment]
I am interested in getting started helping out with kops.
How much of this is left to do?

**Comment by rifelpet** [comment]
Thanks for volunteering! Most of the staticcheck issues have been addressed but you can certainly check the remaining issues in hack/.staticcheck_failures for the remaining ones, besides the PR listed above that is currently open.

I'm adding an additional check in #8328 similar to staticcheck but for shell scripts: [shellcheck](https://github.com/koalaman/shellcheck). Feel free to check it out and start fixing some of the reported issues.

**Comment by rendhalver** [comment]
Awesome. Thanks for the pointer @rifelpet!
I will see what I can work out.

**Comment by rendhalver** [comment]
Hrm. There's only one entry in hack/.staticcheck_failures and it looks like #7839 fixes at least some of those.
I will see I can what I can do to help out with the shellcheck fixes. :)

**Comment by rifelpet** [comment]
all the staticcheck failures have been fixed. good job everyone
/close
