### ISSUE TITLE
Avoid large cluster instability because of protokube?

### ISSUE THREAD

**Issue by shrinandj** [kubernetes/kops#7813]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.12.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.14.6

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster
kops update cluster --yes

**5. What happened after the commands executed?**
Cluster comes up fine. But after months of being in use and the number of nodes > 300, the cluster nodes show instability. More later...

**6. What did you expect to happen?**
Cluster should be up and running just fine.

---

Gossip based Kubernetes clusters setup on AWS have been working great in our environment. As more and more applications have been running on these clusters, the size of the cluster has increased. At one point, when the cluster has > 300 nodes, problems with protokube have been observed. Specifically:

- Protokube starts using a large amount of CPU (1 core)
- Network connections on each node goes very high
- Sometimes, this seems to be causing node level reboots (it’s been hard to pin-point protokube to be the root cause though).
- The dns-controller pod takes up large amount of CPI (1 core)

The explanations for what protokube is used for are [here](https://github.com/kubernetes/kops/issues/2858#issuecomment-315422011) and [here](https://github.com/kubernetes/kops/blob/master/docs/development/gossip.md)

In order to avoid running into the above problems, could we explore the idea of:
- Stopping the protokube service once a node is successfully up and running (and is part of the cluster)?
- Not running dns-controller

Here are some specifics of our setup:

- Bastion nodes are not part of the Kubernetes cluster
- Only rolling upgrades of the master nodes are done using kops. For worker nodes, we use Keiko’s upgrade-manager.
- We do not use dns-controller (use external-dns instead and that too only for Ingress and Service objects)

What do you'll think?

**Comment by rifelpet** [comment]
There has been some work done recently to improve the scalability of protokube and dns-controller in gossip-based clusters:

https://github.com/kubernetes/kops/pull/7521

If your issues sound similar to the issues linked in that PR, it might be worth testing out the new implementation if you are able. It will be released in Kops 1.16.

**Comment by shrinandj** [comment]
Thanks for the pointer to the newer implementation.

However, while we test the new code, is it possible to avoid running
protokube at all as suggested?

**Comment by shrinandj** [comment]
Protokube on the master nodes is required for mounting the appropriate etcd volumes.
Protoube on the master and worker nodes is required for populating the /etc/hosts file with the names of the masters and etcd endpoints. So, when a master nodes dies and a new one comes up, protokube on all nodes will update the /etc/hosts file to populate the ip and name of the new master node.

Seems like it may not be straightforward to get away from protokube.
