### ISSUE TITLE
Kops should stop updating AWS VPC CNI config after bootstrapping

### ISSUE THREAD

**Issue by xrl** [kubernetes/kops#7821]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.14.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.12.10

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I am doing a `replace` and `update` to synchronize YAML config to the kops config.

```
kops replace cluster --force -f kube-dev.yaml
kops update cluster --name=kube-dev
kops update cluster --name=kube-dev --yes
```

**5. What happened after the commands executed?**

The AWS VPC CNI `aws-node` daemonset is reconfigured and it loses the important extra config I have added:

```
            - name: WARM_IP_TARGET
              value: "1"
            - name: WARM_ENI_TARGET
              value: "0"
```

these are important for my small VPC running a small subnet, carved out by my larger enterprise environment. I only have a `/23` to work with.

**6. What did you expect to happen?**

It'd be nice if running kops didn't reconfigure my networking stack. When the reconfiguration kicks in, it automatically restarts all the pods and my IP usage skyrockets.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-03-26T00:00:00Z
  name: kube-dev.meow.io
spec:
  docker:
    version: "18.06.2"
  kubeAPIServer:
    runtimeConfig:
      admissionregistration.k8s.io/v1alpha1: "true"
  api:
    loadBalancer:
      type: Internal
      idleTimeoutSeconds: 1800 # 30 minutes
  authorization:
    rbac: {}
  authentication:
    aws: {}
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["s3:ListObjects"],
          "Resource": ["arn:aws:s3:::ids-dev-kops/kube-dev.interactivedatastore.viasat.io/*"]
        },
        {
          "Effect": "Allow",
          "Action": ["elasticloadbalancing:DeregisterTargets"],
          "Resource": ["arn:aws:elasticloadbalancing:us-west-2:539703851677:targetgroup/*"]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "ec2:CreateNetworkInterface",
            "ec2:AttachNetworkInterface",
            "ec2:DeleteNetworkInterface",
            "ec2:DetachNetworkInterface",
            "ec2:DescribeNetworkInterfaces",
            "ec2:DescribeInstances",
            "ec2:ModifyNetworkInterfaceAttribute",
            "ec2:AssignPrivateIpAddresses",
            "ec2:UnassignPrivateIpAddresses"
          ],
          "Resource": ["*"]
        },
        {
          "Effect": "Allow",
          "Action": [
            "ec2:CreateTags"
          ],
          "Resource": [
            "arn:aws:ec2:*:*:network-interface/*"
          ]
        }
      ]
  channel: stable
  cloudProvider: aws
  configBase: s3://ids-dev-kops/kube-dev.meow.io
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2c
      name: c
    name: main
    enableEtcdTLS: true
    version: 3.2.24
  - etcdMembers:
    - instanceGroup: master-us-west-2c
      name: c
    name: events
    enableEtcdTLS: true
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.12
  masterPublicname: api.kube-dev.meow.io
  networkCIDR: 10.43.202.0/23
  networkID: vpc-0b94766c8a8c871a4
  networking:
    amazonvpc:
      imageName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.5.3
  nonMasqueradeCIDR: 10.43.202.0/23
  serviceClusterIPRange: 10.43.202.0/23
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.43.202.0/23
    id: subnet-03fa682131e608935
    name: us-west-2c
    type: Private
    zone: us-west-2c
    egress: External
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by dezmodue** [comment]
Hi, we run the same CNI plugin and I have been looking at adding support for passing arbitrary environmental variables through the cluster spec, this way you could add the configuration directly in kops rather than having to configure it separately. Would you be interested in this feature? To the maintainers, would this be acceptable?
