### ISSUE TITLE
Clean up outside collaborators

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/kops#7845]
Hey there @kubernetes/kops-admins ,

One of the github-admins here. -- We have a [longstanding issue] on cleaning up outside collaborators, and are now actively planning on removing them on December 1st.

At this point, people that are actively contributing to the Kubernetes project should be promoted to [org members][mem], and any repo specific permissions should be managed through their associated configuration in [kubernetes/org].

With that in mind, the following people are listed as outside collaborators:

- @blakebarnett 
- @kenden 

Of those, @blakebarnett  has been active and I'd encourage [applying for org membership][mem].

@kenden has been inactive (<5 [devstats] recorded contributions in the past year across all Kubernetes orgs), and I'd opt for removal from direct repo permissions. 

Just a general reminder, not having direct permissions **does not stop** folk from contributing. It just means they'd have less permissions (would need  `/ok-to-test` on PRs etc).

If you have any questions or comments, please don't hesitate to ask in here or feel free to poke me in slack 👍 

Thanks!

Assigning to kops admins:
/assign @justinb @mikedanese @zmerlynn 

/sig contributor-experience
/priority important-soon

[longstanding issue]: https://github.com/kubernetes/community/issues/3178
[mem]: https://github.com/kubernetes/community/blob/master/community-membership.md#member
[kubernetes/org]: https://github.com/kubernetes/org
[devstats]: https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All

**Comment by mrbobbytables** [comment]
woops -- misspelled justinsb adding below:
/assign @justinsb

**Comment by blakebarnett** [comment]
Thanks for the reminder, I’ll apply tomorrow!

--
-Blake

**Comment by mrbobbytables** [comment]
Awesome, thanks!

**Comment by mrbobbytables** [comment]
Permissions have been cleaned up, @blakebarnett @kenden -- Please go ahead and file for [org membership](https://github.com/kubernetes/community/blob/master/community-membership.md#member) and we can pursue adding you the appropriate groups for repo permissions 👍 

If you have any questions, please don't hesitate to reopen or ping me on slack.

Thanks!
/close
