### ISSUE TITLE
horizontal_pod_autoscaling.md guide looks unmantained

### ISSUE THREAD

**Issue by fvasco** [kubernetes/kops#7851]
The page https://github.com/kubernetes/kops/blob/master/docs/horizontal_pod_autoscaling.md refers to old kops/kubernetes versions and external links are broken.

How to properly configure the autoscaler?
Will the page updated?

**Comment by dmcnaught** [comment]
Here is a ticket I opened a while back which has lots of info about the HPA.
I still configure the same way: 
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/metrics-server/v1.8.x.yaml`
https://github.com/kubernetes/kops/issues/5033

**Comment by fvasco** [comment]
Thank you @dmcnaught for your interesting,
I launched the suggested command but I get th error

```
$ kubectl top node
error: metrics not available yet
```

I found in the log many of: `unable to fully scrape metrics from source kubelet_summary:ip-172-1-2-3.ec2.internal: unable to fetch metrics from Kubelet ip-172-1-2-3.ec2.internal (172.1.2.3): request failed - "401 Unauthorized", response: "Unauthorized"`

**Comment by dmcnaught** [comment]
@fvasco Did you set these three settings for the kubelet?
https://github.com/kubernetes-sigs/metrics-server/issues/212#issuecomment-459321884
