### ISSUE TITLE
r5n instance type support

### ISSUE THREAD

**Issue by ju187** [kubernetes/kops#7858]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Support r5n type instance
**2. Feel free to provide a design supporting your feature request.**

**Comment by salavessa** [comment]
Please also include **m5n**, **m5dn** and **r5dn** in addition to requested **r5n**: https://aws.amazon.com/about-aws/whats-new/2019/10/introducing-amazon-ec2-m5n-m5dn-r5n-and-r5dn-instances-featuring-100-gbps-of-network-bandwidth/
Thanks!

**Comment by rifelpet** [comment]
Kops 1.15.0 was just released with support for these new instance types. Let us know if you run into any issues using them!

https://github.com/kubernetes/kops/pull/7947

/close
