### ISSUE TITLE
Relax VPC DNS requirements for 1.5

### ISSUE THREAD

**Issue by austinmoore-** [kubernetes/kops#786]
kops (and Kubernetes) require that the "DNS resolution" and "DNS hostnames" options be enabled on a VPC. If Kubernetes 1.5 has this requirement relaxed, kops should should relax the requirement as well. I do think there should still be a warning of some kind though. There should also probably be a section about when to disable these options in the [running in existing VPC](https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md) docs.

**Comment by chrislovecnm** [comment]
Should ... please explain.  I like stuff that works... aka DNS.  Call me old school :)  How does this work in GCE??  We are going to support more than one cloud shortly.

**Comment by yissachar** [comment]
See also https://github.com/kubernetes/kops/issues/786

**Comment by austinmoore-** [comment]
These options are Amazon VPC specific. I should have been more clear about that in the OP. These options are enforced [here](https://github.com/kubernetes/kops/blob/v1.4.1/upup/pkg/fi/cloudup/awstasks/vpc.go#L112) which is under `awstasks`.

I'm not very familiar with GCE, but it's my understanding that GCE instances always have a FQDN so there are no similar options. I am not seeing any similar restrictions in [`gcetasks`](https://github.com/kubernetes/kops/tree/v1.4.1/upup/pkg/fi/cloudup/gcetasks).

I am not saying that Kubernetes shouldn't rely on DNS. I also like DNS :) But when these options are enabled, the Amazon VPC has an [Amazon DNS server](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html?shortFooter=true#AmazonDNS). I don't think kops should require its the use of Amazon's DNS server.

For example, in my situation we use the VPC's DHCP Options Set to point to a private name server, and create instances with domain names that can be resolved by that name server. The instances have resolvable hostnames, but I am still required to enable Amazon's DNS server.

@justinsb mentioned that looks like Kubernetes 1.5 will no longer require Amazon's VPCs to have these options enabled. If that is the case, then kops should remove the requirement as well. When/if that requirement is removed, I do think there should be a warning at cluster creation time, and documentation about when to disable these options.

**Comment by austinmoore-** [comment]
@yissachar Wrong issue? :)

**Comment by yissachar** [comment]
Uhh, oops, meant https://github.com/kubernetes/kops/issues/399

**Comment by justinsb** [comment]
Unsure whether we can get this into kops 1.5.0 or whether it'll have to wait until 1.5.1... but hopefully

**Comment by justinsb** [comment]
It looks like we can turn off EnableDNSHostnames with 1.5.0 - this we'll do automatically.

I'm less sure about EnableDNSSupport in general, so I'm creating a feature flag for now: `VPCSkipEnableDNSSupport`.  If you `export KOPS_FEATURE_FLAGS=VPCSkipEnableDNSSupport` we'll skip the test on shared VPCs.

This is in PR #1673

**Comment by austinmoore-** [comment]
Awesome! Thanks a ton Justin!

**Comment by justinsb** [comment]
Just opened #1713 - the VPCSkipEnableDNSSupport feature flag should default false, not true!  (i.e. by default, we should still continue to require it, unless you specify the feature flag)
