### ISSUE TITLE
AdmissionControlConfigFile yaml entry doesn't work

### ISSUE THREAD

**Issue by perezjasonr** [kubernetes/kops#7862]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.13.0 (git-be5fb9019)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

 kubernetesVersion: 1.13.11

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

run a kops create -f file.yaml with the following entry in your manifest under kubeAPIServer:

admissionControlConfigFile: /path/to/admission-configuration.yaml

**5. What happened after the commands executed?**

cluster creation was attempted, but the arg does not seem to have shown up:

I1031 14:56:49.384809       1 flags.go:33] FLAG: --admission-control-config-file=""

this caused one of my admission controllers to error because it relied on the contents of this config file:

Error: failed to initialize admission: couldn't init admission plugin "EventRateLimit": limits: Invalid value: []e                    ventratelimit.Limit(nil): must not be empty

Ive specified paths in other areas of the cluster manifest and it showed up just fine using identical syntax for example:

auditLogPath: /var/log/kube-apiserver-audit.log
auditPolicyFile: /srv/kubernetes/audit.yaml

both show up as expected. I'm not sure why this one results in an empty string but i expected the same result.

**6. What did you expect to happen?**

I expected --admission-control-config-file="" to instead be populated with what i put based on the description:

// AdmissionControlConfigFile is the location of the admission-control-config-file
    AdmissionControlConfigFile string `json:"admissionControlConfigFile,omitempty" flag:"admission-control-config-file"`

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

`
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: <removed>
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: <removed>
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  docker:
    ipTables: true
  kubeAPIServer:
    admissionControl:
    - AlwaysPullImages
    - DenyEscalatingExec
    - NamespaceLifecycle
    - ServiceAccount
    - NodeRestriction
    - EventRateLimit
    - Initializers
    - MutatingAdmissionWebhook
    - LimitRanger
    - PersistentVolumeLabel
    - DefaultStorageClass
    - ResourceQuota
    - DefaultTolerationSeconds
    - ValidatingAdmissionWebhook
    admissionControlConfigFile: /srv/kubernetes/admission-configuration.yaml
    auditLogMaxAge: 30
    auditLogMaxBackups: 10
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit.yaml
    disableBasicAuth: true
    enableBootstrapTokenAuth: true
    tlsCipherSuites: ["TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305","TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384","TLS_RSA_WITH_AES_256_GCM_SHA384","TLS_RSA_WITH_AES_128_GCM_SHA256"]
  fileAssets:
  - name: event-configuration
    path: /srv/kubernetes/eventconfig.yaml
    roles: [Master]
    content: |
      apiVersion: eventratelimit.admission.k8s.io/v1alpha1
      kind: Configuration
      limits:
      - type: Namespace
        qps: 50
        burst: 100
        cacheSize: 2000
      - type: User
        qps: 10
        burst: 50
  - name: admission-configuration
    path: /srv/kubernetes/admission-configuration.yaml
    roles: [Master]
    content: |
      apiVersion: apiserver.k8s.io/v1alpha1
      kind: AdmissionConfiguration
      plugins:
      - name: EventRateLimit
        path: /srv/kubernetes/eventconfig.yaml
  <removed other file asssets not relevant>

  kubeControllerManager:
    featureGates:
      RotateKubeletServerCertificate: "true"
    controllers:
    - "*"
    - tokencleaner
  kubelet:
    anonymousAuth: false
    authorizationMode: Webhook
    authenticationTokenWebhook: true
    featureGates:
      RotateKubeletServerCertificate: "true"
    readOnlyPort: 0
    tlsCipherSuites: ["TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305","TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384","TLS_RSA_WITH_AES_256_GCM_SHA384","TLS_RSA_WITH_AES_128_GCM_SHA256"]
    streamingConnectionIdleTimeout: 5m
  nodeAuthorization:
    nodeAuthorizer: {}
  hooks:
    <removed because its long and not relevant>

  kubernetesApiAccess:
  - 172.30.0.0/16
  kubernetesVersion: 1.13.11
  masterPublicName: <removed>
  networkCIDR: 172.30.0.0/16
  networkID: <removed>
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 172.30.0.0/16
  subnets:
  - cidr: 172.30.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.30.64.0/19
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.30.96.0/19
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.30.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.30.4.0/22
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.30.8.0/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---
<theres nothing special in the instanceGroup section, so removing>

`

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

the cluster creation goes through. its the api pod itself that has errors which i provided above.

**9. Anything else do we need to know?**

just in case, according to k8s documentation, here is why im doing what im doing in the first place:
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#eventratelimit

there are also other admission controllers that need this arg so if it doesn't work thats going to be a big problem for alot of these.

**Comment by olemarkus** [comment]
This feature was added in kops 1.14. If you upgrade, it should work. We make use of this.

**Comment by perezjasonr** [comment]
Ah ok. we were gonna start trying out 1.14 anyways. glad to know its not an actual bug.
