### ISSUE TITLE
Use kops to setup k8s cluster in AWS China region to use the Route 53 DNS

### ISSUE THREAD

**Issue by liangruibupt** [kubernetes/kops#7871]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Now Route 53 can be preview on AWS China region, but whitelist user can not directly use the it. Because below code do not specify the Region and Endpoint for new Route 53 instance
https://github.com/kubernetes/kops/blob/f9f80f0b26e718e87c08716a2d4f9a7eaf3a2964/dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go#L60

**2. Feel free to provide a design supporting your feature request.**
1. aws.NewConfig() can specify region and endpoint, for example:
aws.NewConfig().WithRegion("cn-northwest-1").WithEndpoint(route53.amazonaws.com.cn)

2. Update the below guide to add route 53 support in AWS China region
https://github.com/kubernetes/kops/blob/cb66ae7af90f3af0cafea47706fa622c68e9eca9/docs/aws-china.md

**Comment by liangruibupt** [comment]
any update ?

**Comment by jecnua** [comment]
Still valid, please remove the label stale.
