### ISSUE TITLE
What is necessary infra to create a cluster with private DNS zone in AWS?

### ISSUE THREAD

**Issue by Magicloud** [kubernetes/kops#7889]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.14.0 (git-d5078612f)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-29T18:43:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`

**3. What cloud provider are you using?**
`AWS`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
A) Create infra with terraform:
```
provider "aws" {
  region = "eu-west-2"
}

resource "aws_s3_bucket" "state" {
  bucket = "k8s-test"
}

resource "aws_vpc" "vpc" {
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true
}

resource "aws_internet_gateway" "igw" {
  vpc_id = aws_vpc.vpc.id
}

resource "aws_route53_zone" "private" {
  name = "k8s-test.xyz"
  vpc {
    vpc_id = aws_vpc.vpc.id
  }
}

output "dns" {
  value = aws_route53_zone.private.id
}

output "vpc" {
  value = aws_vpc.vpc.id
}
```
B) Run `kops create cluster --cloud=aws --zones eu-west-2a --master-zones eu-west-2a --dns-zone Z3MEO2G73MM1Z8 --vpc vpc-05f5c2b1228fe996c --dns private --state s3://k8s-test --name demo.k8s-test.xyz -y`

**5. What happened after the commands executed?**
```
I1107 03:07:50.191614  950927 executor.go:103] Tasks: 80 done / 83 total; 1 can run
W1107 03:07:50.685370  950927 executor.go:130] error running task "DNSZone/Z3MEO2G73MM1Z8" (9m24s remaining to succeed): error creating DNS HostedZone "": InvalidParameter: 1 validation error(s) found.
- missing required field, CreateHostedZoneInput.Name.
I1107 03:07:50.685410  950927 executor.go:145] No progress made, sleeping before retrying 1 failed task(s)
```

**6. What did you expect to happen?**
`Create a basic cluster.`

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-11-06T19:24:45Z
  name: k8s-test.xyz
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://k8s-test/k8s-test.xyz
  dnsZone: Z3MEO2G73MM1Z8
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.14.6
  masterPublicName: api.k8s-test.xyz
  networkCIDR: 10.0.0.0/16
  networkID: vpc-05f5c2b1228fe996c
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.32.0/19
    name: eu-west-2a
    type: Public
    zone: eu-west-2a
  topology:
    dns:
      type: Private
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-06T19:24:48Z
  labels:
    kops.k8s.io/cluster: k8s-test.xyz
  name: master-eu-west-2a
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: c4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-2a
  role: Master
  subnets:
  - eu-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-06T19:24:49Z
  labels:
    kops.k8s.io/cluster: k8s-test.xyz
  name: nodes
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-2a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

The log is very long. This is just the part around error, which repeats.
```
I1107 03:33:30.610750  952580 executor.go:103] Tasks: 80 done / 83 total; 1 can run
I1107 03:33:30.610803  952580 executor.go:178] Executing task "DNSZone/Z3MEO2G73MM1Z8": *awstasks.DNSZone {"Name":"Z3MEO2G73MM1Z8","Lifecycle":"Sync","DNSName":null,"ZoneID":"Z3MEO2G73MM1Z8","Private":true,"PrivateVPC":{"Name":"k8s-test.xyz","Lifecycle":"Sync","ID":"vpc-05f5c2b1228fe996c","CIDR":"10.0.0.0/16","EnableDNSHostnames":null,"EnableDNSSupport":true,"Shared":true,"Tags":null}}
I1107 03:33:30.611039  952580 request_logger.go:45] AWS request: route53/GetHostedZone
I1107 03:33:32.222224  952580 dnszone.go:190] Creating Route53 HostedZone with Name ""
W1107 03:33:32.222330  952580 executor.go:130] error running task "DNSZone/Z3MEO2G73MM1Z8" (8m54s remaining to succeed): error creating DNS HostedZone "": InvalidParameter: 1 validation error(s) found.
- missing required field, CreateHostedZoneInput.Name.
I1107 03:33:32.222350  952580 executor.go:145] No progress made, sleeping before retrying 1 failed task(s)
```

**9. Anything else do we need to know?**
`No`

**Comment by Magicloud** [comment]
Also, in the verbose log, the `EnableDNSHostnames` of my VPC is null, which actually is true. Not sure if related.

**Comment by tejasrao97** [comment]
Hi can you tell me how to create a clsuter with DNS zone set to public

**Comment by Magicloud** [comment]
@tejasrao97 The key is to run `kops` on the host that can solve the DNS zone.

**Comment by lazzarello** [comment]
Hit this issue with Govcloud private DNS zones which is the only option in that region. Worked out how to do it. Current master branch of kops cannot successfully create a multi-master cluster with private DNS in the Govcloud region.

**Comment by olemarkus** [comment]
The typical way of solving things like govcloud is to use gossip: https://kops.sigs.k8s.io/gossip/
Private DNS is described here: https://kops.sigs.k8s.io/getting_started/aws/#using-publicprivate-dns-kops-15
