### ISSUE TITLE
Support for adding user snippets to the user-data -- Perhaps a systemd unit abstraction ? 

### ISSUE THREAD

**Issue by hsyed** [kubernetes/kops#789]
My current use case is to mount an EFS drive on all cluster nodes. Perhaps there is support for doing this with DaemonSets -- or there is some other k8s mechanism for it. Regardless it would be nice if we could have abstractions for just verbatim appending user supplied chunks of data to the user-data scripts. 

It would be fantastic if we could get some support at the level of coreos cloud-config minus the open ended and easy-to-get wrong nature of cloud-init and cloud-config. 

An abstraction for supplying a directory with systemd unit files would be fantastic -- perhaps the abstraction could be made drop-in aware somehow ? All the operating systems under consideration have first class systemd support so it seems a clean and logical approach for user extension.

**Comment by chrislovecnm** [comment]
We are installing the base install.  Bare bones.  If you need CM after the fact.  I encourage you to do that.

**Comment by kris-nova** [comment]
Pointing https://github.com/kubernetes/kops/issues/791 and https://github.com/kubernetes/kops/issues/789 to each other..

More use cases for extending kops

**Comment by justinsb** [comment]
Daemonsets are the "k8s systemd unit file", so I think if we're going to support some extension mechanism, we should prefer that.

That said, I think we've agreed to support a post-boot shell-script or similar.  Every time you use it an angel will lose its wings, but there will be that mechanism also.

**Comment by mdbishop** [comment]
Just wanted to add a vote for this.  Our use case it to add system monitoring which is "unsupported"  at this time running containerized so we'd like to have the agent install itself once a node is turned up.  Especially with spot or preemptible's, taking this on as a one-off is untenable.  

I'd be quite happy with nothing fancy -- just a bash script that could run after all the other init scripts have completed would be all I'd need.  If folks had requirements more involved, the script could drop in a chef agent for instance, and (with all the caveats about not clobbering the carefully written k8s scripts) be good to go.

**Comment by sellers** [comment]
Being able to inject into the cloud-init user data would be helpful for being able to modify the results of the LC w/o having to build a custom AMI.

**Comment by KashifSaadat** [comment]
I believe this is covered by the implementation of Hooks (https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#hooks), but otherwise extension of the user-data scripts may be covered in PR #3633.
