### ISSUE TITLE
Add support for CUDA 10.0

### ISSUE THREAD

**Issue by chilland** [kubernetes/kops#7911]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
The `nvidia-device-plugin` currently only supports bootstrapping nodes with CUDA 9.1. Newer versions of Tensorflow require CUDA 10.0. Add the option to bootstrap nodes with 9.1 or 10.0

**2. Feel free to provide a design supporting your feature request.**
This could be implemented to support other versions of NVIDIA and CUDA drivers based on the selected Docker image for the hook.

**Comment by valayDave** [comment]
@chilland : https://github.com/NVIDIA/k8s-device-plugin/issues/139#issuecomment-602117608 . To Support Cuda 10.1, KOPS Needs to support NVIDIA Container Toolkit. The NVIDIA K8s plugin currently doesn't support the container Toolkit. The current KOPS NVIDIA Plugin is based on nvidia-docker2.
