### ISSUE TITLE
TF support

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#793]
I know we have it ... people talk about if we keep it.  GO

**Comment by chrislovecnm** [comment]
@justinsb thoughts?  Just concerned that if we don't have a testing framework this will slow down testing cycles.  I kinda like it ... kinda don't.  Thoughts?

**Comment by chrislovecnm** [comment]
@kris-nova ping :)

**Comment by kris-nova** [comment]
@chrislovecnm - This is a huge deal.. Can we clean this issue up and give it a little more context?

It would be great if we could see : 

1. Why we are using Terraform targets in the first place
2. Why it would be wise to continue/stop supporting the target
3. Open questions to the community
4. Any data on current users

**Comment by callmeradical** [comment]
As a Kops user, I really like the output to terraform. I think it becomes less of a blackbox and makes it easy to customize what Kops is launching. Most of our other infrastructure is managed via terraform and it eases the learning curve a little bit.

**Comment by justinsb** [comment]
I think we should keep it; though we probably need more of an explanation of the limitations and how to work with it.  Specifically:

* That we still generate some files in S3 directly
* That you probably want to continue to make changes through kops, even if you export to TF
* If you want to make your own changes, you can do that using git and branches
* But you probably should ask us to build the feature into kops
* That you should not delete your cluster from kops

**Comment by hsyed** [comment]
I use terraform for all sorts of things. I have peering connections, public / private subnets and an EFS drive to name a few. I have tweaked a lot over the past few weeks to get a nearly working 3x ha solution. Weavenet is unstable for me.

Having peeked a bit under the covers I wonder why it isnt the only way of bootstrapping a cluster most of the magic occurs in nodeup and protokube.

**Comment by billyshambrook** [comment]
TF support is a key feature for why we chose KOPS, as we have a CD pipeline setup to deploy infra changes using Terraform.

We can integrate KOPS into our pipeline by running the KOPS CLI manually to design the changes, then output the TF config and add that to our infra TF repo which runs through our pipeline to apply the changes to the various environments.

Another added benefit of this feature was that we were able to hack at the terraform output to get the KOPS kubernetes cluster working within a private network topology... however soon we will be able to stop these shenanigans!! :)

**Comment by chrislovecnm** [comment]
Cool... Thanks for the feedback.  We need to get more testing around it!!!

**Comment by chrislovecnm** [comment]
Another reason to keep TF https://github.com/kubernetes/kops/issues/172 - people can generate good solid server layout then make modifications that they need.

**Comment by chrislovecnm** [comment]
Thanks folks ... GREAT feedback.  Support is here to stay :)  @justinsb do you have TF support for gcloud?

Closing.
