### ISSUE TITLE
Make etcd-manager LogVerbosity configurable 

### ISSUE THREAD

**Issue by elblivion** [kubernetes/kops#7946]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

etcd-manager's `LogVerbosity` is currently hard-coded and we can't opt-out of very noisy logging: https://github.com/kubernetes/kops/blob/baa5ae3934139aecaf1d0a55620bcb02e617a1a4/pkg/model/components/etcdmanager/model.go#L341

Before etcd-manager:

* The etcd-server container stdout was very minimal, less than 5 messages an hour about snapshots.
* etcd logged more verbosely to etcd.log, which is picked up in standard Fluentd logging pipelines.

With etcd-manager we see an explosion in logging to stdout (all the etcd log output plus etcd-manager's own logging), and duplicate because of our Fluentd picking up etcd.log. We can and will stop importing the hosts' etcd.log into our logging pipeline, but we lack a way of telling etcd-manager to be less verbose. 

This has led to two orders of magnitude more log volume for this component.

**2. Feel free to provide a design supporting your feature request.**

Something like this in the cluster.spec would feel similar to other components managed by Kops: 
```
  etcdManager:
    LogLevel: N
```

**Comment by rifelpet** [comment]
Kops 1.18 will support setting environment variables for etcd (#8402), so you should be able to set the `ETCD_LOG_LEVEL` env var. see the example [here](https://github.com/kubernetes/kops/blob/b129a83638f9c51a3981d907741ed65efc955ff1/pkg/model/components/etcdmanager/tests/overwrite_settings/cluster.yaml#L17-L20)

**Comment by olemarkus** [comment]
Looks like we can close this one
/close
