### ISSUE TITLE
Cluster Spec YAML Beautification 

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#795]
# So there is an **old school** sysadmin in me yet 

But I am wondering if it would be prudent to clean up (beautify) the cluster spec YAML that is stored in the STATE_STORE.

## 1 - Directive descriptions from code

My first thought was to have the API documentation (in code) populate as YAML comments in the state.

So..

```
// The version of kubernetes to install (optional, and can be a "spec" like stable)
KubernetesVersion     string `json:"kubernetesVersion,omitempty"`
```

(in go) would translate to

```
# The version of kubernetes to install (optional, and can be a "spec" like stable)
kubernetesVersion: 1.4.3
```

(in yaml)

## 2 Default value definitions

Another big win could be calling out default values, for example

A lack of `updatePolicy` in the cluster spec denotes `updatePolicy: missing`

I think we should call that out in the cluster spec as well. For 2 reasons..

1. We are processing it as such, so having it defined seems meaningful
2. I can't tell you how many times I have set `upgradePolicy: external` only to find a mis configured cluster

These are examples - but I think the feature(s) here are now obvious

**Comment by chrislovecnm** [comment]
Does it have the api version on it??  I think that is SUPER important.

**Comment by kris-nova** [comment]
To give some clarity on @chrislovecnm's comment

We are looking at the YAML file housing the kops version, and current kops API version in the cluster spec as comments... 

I smell a nice shiny header :)

**Comment by kris-nova** [comment]
Just throwing this out there... 

```
 _                   
| | _____  _ __  ___     Kubernetes Operations
| |/ / _ \| '_ \/ __|    Production Grade K8s Installation, Upgrades, and Management
|   < (_) | |_) \__ \    v1.5.0
|_|\_\___/| .__/|___/    v1alpha1
          |_|        
```

**Comment by chrislovecnm** [comment]
Yaml butificatikn would need to be supported upstream API tooling as we are reusing base kubernetes API machinery code.

Not sure this is feasible, can we close?

**Comment by chrislovecnm** [comment]
Closing
