### ISSUE TITLE
DO: etcd-manager volume and droplet tag key never match 

### ISSUE THREAD

**Issue by prksu** [kubernetes/kops#7956]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Version 1.16.0-alpha.1 (git-64f3eaa91) / HEAD
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
```

**3. What cloud provider are you using?**

```
Digitalocean
```

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

create single master kops cluster on digitalocean with region suffix other than 1 eg: nyc3,sfo2

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

etcd-manager should matching volume and droplet tag key

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

on digitalocean provider with etcd-manager, kops create do-volume with `k8s-index` tag based on `EtcdMemberSpec.Name` which trimmed and leaving only one character from the end of the actual name. So the `k8s-index` will be given value based on the end of region name `eg: k8s-index:3` (if using region nyc3) when the cluster with `masterCount` less or equal with `masterZones`. because kops not gives a number suffix in the cluster name in this condition.
unfortunately, the droplet created with a `k8s-index` tag based on an increment of `masterIndexCount`. so in the single master, kops will give `k8s-index:1` tag for the droplet.
AFAIK this is the problem in this case.

fyi @srikiz

**Comment by srikiz** [comment]
good catch @prksu - I'll fix it sometime next week.
FYI - @timoreimann

**Comment by prksu** [comment]
@srikiz nice to help to support kops for DO.

**Comment by srikiz** [comment]
Implementation PR - https://github.com/kubernetes/kops/pull/8002

**Comment by srikiz** [comment]
Closing this issue since the changes are merged to master.

**Comment by prksu** [comment]
/close 
thanks @srikiz
