### ISSUE TITLE
KubeCon 2019 User Feedback: Reduce pods bounces durring rolling updates.

### ISSUE THREAD

**Issue by granular-ryanbonham** [kubernetes/kops#7958]
**1. During rolling updates pods can get rescheduled onto nodes that still need to be updated, causing pods to get reshuffled multiple times. This is disruptive for things like ingress gateways.

**2. Possible solution, would bee that we cordon nodes prior starting the rolling upgrade.

**Comment by zetaab** [comment]
if we cordon all nodes before starting rolling update, there is quite high downtime for pods in first node. It means that those pods will wait until new node comes up. So something like 3-5minutes, in my opinion not good solution

**Comment by johngmyers** [comment]
@zetaab You could have the overprovision pods absorb the impact or you could surge.

I happen to have implemented CordonAllNeedUpdate last night.

**Comment by zetaab** [comment]
@johngmyers people might have pods which needs to be up and running all the time and those cannot have many replicas. It is quite long time for that kind of pod to be down for 3-5mins

**Comment by johngmyers** [comment]
@zetaab Which is why I made CordonAllNeedUpdate a per-instancegroup option.

Your other option is surging, which I mentioned. But that is a different feature, which I also plan to address, but later.
