### ISSUE TITLE
Pretty pictures in documentation

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#796]
Me love some pictures http://blog.couchbase.com/2016/november/multimaster-kubernetes-cluster-amazon-kops.  Would some stuff like this be helpful??

**Comment by kris-nova** [comment]
I think this is a bigger task TBH - which is `tutorials` 

I think kops should offer a `tutorials` section that attempts to go through a few commonly used cluster deployment scenarios in the same fashion that your wonderful link does.. Pretty pictures and all..

This could be a big part of 1.5

**Comment by chrislovecnm** [comment]
Closing we have some
