### ISSUE TITLE
Allow additionalUserData to run before any kops scripts

### ISSUE THREAD

**Issue by TC-robV** [kubernetes/kops#7960]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
It would be really helpful if the additionalUserData we set can have the option to run before or after the nodeup script.

**Comment by zetaab** [comment]
@TC-robV are you sure that instancegroup additionaluserdata is not doing that already? No idea is that executed enough early that you want. Anyways I am using it with tasks that is needed to be in place before it will execute any cloud tasks

**Comment by TC-robV** [comment]
as far as i can see it happens well after. if i hop on a newly created box the second it comes up i can see the nodeup script running already, and my additional script doesn't run until after that ends.

**Comment by rifelpet** [comment]
Can you describe what you're trying to achieve and why it needs to be done before nodeup runs?
