### ISSUE TITLE
README install instructions

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#797]
We need a bit better instructions for install in README.md.  Probably steal / model / reuse `helm`'s shell script.  Also we need to list that `kubectl` is required.

**Comment by chrislovecnm** [comment]
Also @kris-nova that demo gif is so completely awesome, but you did not actually create a cluster :P  Thoughts?

**Comment by kris-nova** [comment]
Nope - I sure didn't! 

But my original goal of getting a GIF out there so we can discuss how to make it better seems to be working..

What do we want to see here? 

Ideas:

1. Single command k8s install
2. Elegant create/edit/update flow

Thoughts?

**Comment by kris-nova** [comment]
Lets hit this tomorrow on our call - once I have the commands I can record it and get it out

.. Also I want to spritz up my `emacs` a bit before recording <3
