### ISSUE TITLE
Protokube automatically updates software installed from channels

### ISSUE THREAD

**Issue by stevenjm** [kubernetes/kops#7970]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.14.1 (git-b7c25f9a9)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"archive", BuildDate:"2019-09-21T09:43:39Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:40:54Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops update cluster --target cloudformation --out /tmp` using kops 1.14.1, on a cluster using weave for networking that was last updated with kops 1.12.3.

**5. What happened after the commands executed?**

Kops uploaded a new version of the bootstrap channel which included an update to the weave add-on. Protokube noticed this update and immediately installed the new version of weave.

This is compounded by https://github.com/kubernetes/kops/issues/7971. The two issues combined resulted in a cluster-wide rolling restart of weave, which caused a brief but visible network interruption on each node.

**6. What did you expect to happen?**

I would not expect any changes to be applied to the running cluster until I ask kops to perform a rolling update.

For some more context, our cluster update process is:

1. Use kops to generate a new CloudFormation template.
1. Modify the template with local additions.
1. Generate a CloudFormation changeset.
1. Validate the changeset. This is semi-automated; some simple changes are allowed to proceed automatically, while anything else requires manual approval.
1. Execute the changeset.
1. Perform a rolling update on the cluster with kops.

Prior to applying the changeset, we do not want any changes to be applied to the cluster. Kops uploads the new bootstrap channel during the first step of this process, which is pulled within 60 seconds by protokube.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

https://gist.github.com/stevenjm/c7eccd8b3fc20c675df61dfa3d6e9ecc

**9. Anything else do we need to know?**

This appears to be an intended feature of protokube, which I find strange:

https://github.com/kubernetes/kops/blob/1.14.1/protokube/pkg/protokube/kube_boot.go#L95-L104
https://github.com/kubernetes/kops/blob/1.14.1/protokube/pkg/protokube/kube_boot.go#L155-L159

Is there any reason to apply a channel more than once per protokube invocation?

If not, a simple solution would be to provide a checksum of at least the bootstrap channel in the instance user data. The last applied checksum could be stored somewhere in the cluster metadata (as a ConfigMap, perhaps?), and protokube could only apply the channel when the checksum changes.

This idea would need some care in the implementation to ensure that masters don't fight over which version to apply in the middle of a rolling update, but I think the principle is sound.

**Comment by olemarkus** [comment]
At the moment this is really the only way for kops to "safely" update things like the CNI DS. Kops will for example not be able to detect if nodes need updates by looking at the DS.

It isn't impossible to improve this, but we'd need some help implementing it.
