### ISSUE TITLE
Make terraform code reusable

### ISSUE THREAD

**Issue by jniebuhr** [kubernetes/kops#7977]
We are currently trying to integrate kops with our existing terraform code and I'd like to propose some changes.

When exporting your kops cluster to terraform, kops will generate some data files and a single kubernetes.tf. This kubernetes.tf file contains a lot of values for that specific cluster and even puts the cluster name in the resource names. 
Because of that, it would be hard to put that code into a module suitable for multiple environments and still do upgrades / config changes since everyone would need to know what variable in the kops config effects the terraform code.

I'd like to propose generating a configurable terraform module (or even just using a static one from github) and having terraform generate a `tfvars` file for it as well as the data files. Inspiration could be taken from https://github.com/terraform-aws-modules/terraform-aws-eks which allows configuration of multiple instance groups etc.

When you're changing or upgrading your cluster then, you'd just update the module version, export a new tfvars file and you're set.

**Comment by rifelpet** [comment]
I like this idea! we could parameterize the cluster name anywhere it is used in the generated terraform code with a `var.cluster_name` and then define its value in a separate tfvars file that can easily be swapped out. We're working on upgrading the syntax to tf 0.12, once we understand the scope of what is required for that i think we could definitely tackle this.
