### ISSUE TITLE
Update the version of aws-sdk-go to be above v1.3.0?

### ISSUE THREAD

**Issue by yancl** [kubernetes/kops#799]
During the use of the latest release branch, I found the aws-sdk-go repos version is v1.2.7, which
does not read the ~/.aws/config, that will cause problem in china region like following:
```
error getting location for S3 bucket "xxxx": InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records
```

if the aws-sdk-go lib can read the ~/.aws/config, it will know that we are in `cn-north-1` region and access the right S3 service.

So will you please update the dependency of aws-sdk-go to be above v1.3.0 ?

```
https://github.com/aws/aws-sdk-go/releases/tag/v1.3.0
Adds support for shared config file (~/.aws/config)
```

**Comment by chrislovecnm** [comment]
@yancl thanks ... will look at what it will take to upgrade.

**Comment by nelson9087** [comment]
I tried out this branch using our govcloud aws account.  It wouldn't work until I changed the two references with hardcoded regions to not set the region.  
```
code that looks like this:
  config := aws.NewConfig().WithRegion(region)
changed to: 
  config := aws.NewConfig()
```

```
upup/pkg/fi/cloudup/awsup/aws_utils.go:41
util/pkg/vfs/s3context.go:47
```

Also, had to set the environment variable 
`AWS_SDK_LOAD_CONFIG=1`

If the region is specified in code (as it was before changing it as mentioned above), it always overrides the config AWS_SDK_LOAD_CONFIG or the AWS_REGION environment variables: https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html )

But after that, I ran into this issue with Route 53 and the fact that it's not available in govcloud:   #172 

error listing DNS zones: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: ....

**Comment by yancl** [comment]
@nelson9087   you are right, when i first run into the problem, i think it was only the current version aws-sdk-go the kops referenced that does not read the `~/.aws/config`  cause the problem, but after i run the higher version aws-sdk-go, it can not work as aspect. then after i make changes to the **hard coded** code you mentioned, it works fine with s3 operations.

So maybe we should also change the **two** hard coded `config := aws.NewConfig().WithRegion("us-east-1")` to be with ENV?

**Comment by chrislovecnm** [comment]
@yancl so if you have a different issue please open a separate issue :)  @justinsb has a PR in for the API upgrade.  Just double checking a couple of things with him.

**Comment by yancl** [comment]
@chrislovecnm ok, thanks:)
