### ISSUE TITLE
aws vpc cni plugin is missing in 1.15

### ISSUE THREAD

**Issue by Deshke** [kubernetes/kops#7990]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops version
Version 1.15.0 (git-9992b4055)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.15.6

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops update cluster -> 1.15.6

**5. What happened after the commands executed?**

the aws vpc cni binary is missing

```
ip-172-20-99-92 ~ # find /opt/
/opt/
/opt/kubernetes
/opt/kubernetes/bin
/opt/kubernetes/bin/socat
/opt/kubernetes/bin/kubelet
/opt/kubernetes/bin/conntrack
/opt/bin
/opt/bin/kubectl
/opt/cni
/opt/cni/bin
/opt/cni/bin/loopback
/opt/cni/bin/portmap
/opt/cni/bin/ptp
/opt/cni/bin/flannel
/opt/cni/bin/host-local
/opt/cni/bin/bridge

```

**6. What did you expect to happen?**

working vpc cni

**Comment by Deshke** [comment]
after more testing, this occurs if you would upgrade the master nodes with the `-cloudonly` flag and the new 60s interval - somehow the masters get stuck and will not load the AWS VPC CNI plugin. 

Rolling the master nodes with a 180s interval somehow prevents this from happening, the plugin gets loaded after about 120s into the kubelet running.

**Comment by vvbogdanov87** [comment]
Probably related to #8137 
I don't use `--cloudonly` flag and still don't see some binaries under `/opt/cni/bin`

**Comment by olemarkus** [comment]
I assume this is no longer an issue. If so, let me know and I will reopen
