### ISSUE TITLE
Add concurrent-[resource]-sync options to KubeControllerManagerConfig

### ISSUE THREAD

**Issue by millerick** [kubernetes/kops#7991]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/ lists out many different command line options to tune the number of concurrent syncs by the manager for a particular resource type on the cluster.  Currently these settings cannot be managed while using Kops (or so I believe from my basic understanding of the code).  Being able to set these parameters is very important for managing a cluster that quickly churns through deployments, etc.
**2. Feel free to provide a design supporting your feature request.**

**Comment by rifelpet** [comment]
#7600 adds these, I'll see if we can get it merged soon
