### ISSUE TITLE
cannot create SSH public key

### ISSUE THREAD

**Issue by jting111** [kubernetes/kops#7994]
Hi, I'm unable to create an SSH public key, in the context of updating my kops/kubernetes cluster.  The cluster is technically "created", but it's not up and running yet.  The problem is, when I try to create an SSH public key, the kops tool wants to read the existing key, which does not make sense.  I tried to "touch" the id_rsa.pub file, but no good either.

Upon generating my cluster manifest, I noticed my configBase looks weird.  I read a related post saying how someone had a similar error until they cleared the configBase part after the domain name.  I'll try that next.

My kops version on an Ubuntu variant.
Version 1.16.0-alpha.2 (git-dfaf0b633)

My Kubernetes version:
kubectl version - GitVersion:"1.16.0"

Cloud provider is AWS.

Here are the command I ran:
# I created my cluster, but got error that I need to create SSH public key
$ kops create cluster --zones=us-east-2b useast2.mydomain.com
I1122 09:49:16.610619   28582 create_cluster.go:562] Inferred --cloud=aws from zone "us-east-2b"
I1122 09:49:17.344487   28582 subnets.go:184] Assigned CIDR xxx.xx.xx.x/xx to subnet us-east-2b
Previewing changes that will be made:

SSH public key must be specified when running with AWS (create with `kops create secret --name useast2.mydomain.com sshpublickey admin -i ~/.ssh/id_rsa.pub`)

==
# I ignored creation of SSH key, and was reminded to create it
$ kops update cluster useast2.mydomain.com --yes

SSH public key must be specified when running with AWS (create with `kops create secret --name useast2.mydomain.com sshpublickey admin -i ~/.ssh/id_rsa.pub`)
$ 

==
# I ran the SSH public key creation command exactly as prescribed, and got an error indicating there's no public key
$ kops create secret sshpublickey --name useast2.mydomain.com admin -i ~/.ssh/id_rsa.pub
error reading SSH public key /home/jeff/.ssh/id_rsa.pub: open /home/jeff/.ssh/id_rsa.pub: no such file or directory
$ 

==
# I reran the SSH public key creation command using the syntax that I believe is correct, and got the same error indicating there's no public key
$ kops create secret sshpublickey admin -i ~/.ssh/id_rsa.pub --name useast2.mydomain.com --state s3://clusters.mydomain.com
--state s3://clusters.mydomain.com
error reading SSH public key /home/jeff/.ssh/id_rsa.pub: open /home/jeff/.ssh/id_rsa.pub: no such file or directory

I expected an SSH public key to be generated, instead of complaining there is not one already.  Correct, there isn't one, that's why I'm trying to create one.

Here's the cluster manifest, with my true domain and IP addresses masked:

$ kops get --name useast2.mydomain.com -o yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-11-22T14:49:18Z"
  name: useast2.mydomain.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://clusters.mydomain.com/useast2.mydomain.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-2b
      name: b
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-2b
      name: b
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.2
  masterPublicName: api.useast2.mydomain.com
  networkCIDR: xxx.xx.x.x/xx
  networking:
    kubenet: {}
  nonMasqueradeCIDR: xxx.xx.x.x/xx
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: xxx.xx.xx.x/xx
    name: us-east-2b
    type: Public
    zone: us-east-2b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-22T14:49:18Z"
  labels:
    kops.k8s.io/cluster: useast2.mydomain.com
  name: master-us-east-2b
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: c4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2b
  role: Master
  subnets:
  - us-east-2b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-22T14:49:19Z"
  labels:
    kops.k8s.io/cluster: useast2.mydomain.com
  name: nodes
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-2b
$

**Comment by bruxochico** [comment]
Use the "ssh-keygen" command to create the key, followed by the permission for the public key using the command below:
$ chmod 750 id_rsa.pub and run the command again : 

$ kops create secret --name useast2.mydomain.com sshpublickey admin -i ~/.ssh/id_rsa.pub

**Comment by jting111** [comment]
That worked!  Thanks, @bruxochico !

Question now is whether Kops should have said that, or is that assumed knowledge for the user?  I'll close the issue if it's the latter.

Also, I did not need add the "execute" permission.
