### ISSUE TITLE
kops import: Support kops created clusters

### ISSUE THREAD

**Issue by austinmoore-** [kubernetes/kops#801]
`kops import` is intended for use with clusters created with kube-up. If it could support kops created clusters as well, when paired with Terraform (or other output format someday) it could become a great way to ensure cluster infrastructure can be completely rebuilt from scratch.

**Comment by chrislovecnm** [comment]
> completely rebuilt from scratch

What do you mean?

**Comment by austinmoore-** [comment]
I'm imagining a worst case scenario where all cloud resources are destroyed. While unlikely, it is important to be capable of completely recovering from such a scenario. Describing infrastructure as code is a great way to do this, and the Terraform support in kops can provide this. However, since everything is gone - including the kops state store in S3 - the cluster created with TF cannot be managed by kops. If kops could import that cluster, then the reproducible infrastructure is complete.

I did some testing since posting this yesterday, and recovering from such a scenario in this way would actually prove to be quite difficult. The instances depend on resources in the state store, so if they're not there nodeup can't complete. Plus things like secrets would have to be recreated.

I would much rather have a way to pass `config`, `instancegroups/nodes`, etc. to kops on the command line for it to use. Then I could version control those files and rebuild the cluster through Jenkins, or a script. I want to remove the need for humans to edit files to rebuild a cluster. I think @justinsb told me yesterday that this is planned at some point.

Also, @justinsb asked me to open this issue when I was discussing this yesterday. He claimed it could be very powerful. He may have some other use cases in mind. I was pretty much only thinking of a way to rebuild the cluster.
