### ISSUE TITLE
Allow to use additional security group to Bastion ELB (AWS)

### ISSUE THREAD

**Issue by jecnua** [kubernetes/kops#8013]
Hi,

We would like to add an additional security group to the Bastion ELB (AWS).
The following tickets were created on the topic and closed by the damn lifecycle bot (one of them reopened many times, thank you @-kaazoo) but never solved.

- https://github.com/kubernetes/kops/issues/2177
- https://github.com/kubernetes/kops/issues/3350
- https://github.com/kubernetes/kops/issues/6697
- https://github.com/kubernetes/kops/issues/3937

Please read all of them.
sshAccess is not what this ticket is about.
AdditionalSecurityGroups is not what this ticket is about (https://github.com/kubernetes/kops/issues/3937#issuecomment-370851649).

The tickets I listed and comments on it list enough use-cases, so we can avoid going through them again here. People is also bumping closed ticket to raise this issue and it's clearly something that should not happen.

I want to say beforehand: I know people can do PR (me included) but that is not the point of this ticket. I also don't want to force anybody in the KOPS dev team to work on an issue that they may not think is a priority. I just want to ask you guys to protect a ticket about a functionality that some people need from being created again and again and allow people to bump it up to track the requests. Thank you for all your work on KOPS. It's a tool we use extensively and we found it really useful.

**Comment by jecnua** [comment]
Still valid, please remove stale label.

**Comment by jecnua** [comment]
Stale label still present. Please remove.

**Comment by nvanheuverzwijn** [comment]
@jecnua Hi, can you take a look at #8921 ? I think it resolves your problem.

**Comment by jecnua** [comment]
Hi @nvanheuverzwijn. Yes the PR looks like it solved the issue. Thank you so much for it, really appreciated :)
