### ISSUE TITLE
Kops vs Kubo

### ISSUE THREAD

**Issue by GregoryVds** [kubernetes/kops#8034]
Hi all,

I am currently hesitating between Kops and Bosh+Kubo to manage my cluster. I am interested in your take in this: what are the pro ans cons of Kops vs a solution like Bosh+Kubo?

To give some context, I will be deploying a VNF on OpenStack (and vSphere later). I am thus using CNI-Genie for the network and I need a custom kernel (which would require me to build my own Bosh stemcell). 

Apologies if the question is too broad, I can move to Slack if needed.
I posted it here as I thought it might be useful to others.

Thanks,
Gregory

**Comment by zetaab** [comment]
I think there are quite less amount of people who have used Bosh+kubo. It might be difficult to find any comparison to that question.

But you are talking about openstack and vsphere here, vsphere is not really supported by kops. There is some code, but its not in level where it should be. If your plan is to use vsphere later, the vsphere kops support is not going to be there before kops cluster-api support.

**Comment by GregoryVds** [comment]
@zetaab Thanks for your quick answer.

Indeed, my biggest worry about Bosh+Kubo is that the community seems really small and not very active compared to Kops. Also, it does not seem to be going in the same direction as the Kubernetes community (with all the cluster-api work).

> If your plan is to use vsphere later, the vsphere kops support is not going to be there before kops cluster-api support.

Good to know for vSphere, I saw support was in alpha and was (wrongly) assuming if would move to beta in the near future. I assume the plan is to somehow reuse cluster-api-provider-vsphere before going any further on the vSphere integration? Is that correct? Any idea what would be the timeline for that (very roughly)?

I was also wondering how Kops handles the self-healing of the cluster. In Bosh you have this runtime component doing periodic health-checks on the VMs. As I understand it, Kops currently does have any any run-time component. Is that correct? If yes, then how does Kops handles self-healing? Does it rely on the cloud to do that? (I don't think OpenStack provides this, AWS probably does but I am not familiar with AWS). In the future, with cluster-API work, will Kops have a run-time controller doing that work?
