### ISSUE TITLE
Add support to me-south-1 (Bahrain)

### ISSUE THREAD

**Issue by mangokingTW** [kubernetes/kops#8037]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
AWS has a new region me-south-1 at 7/29.
But the aws-sdk used by kops is too old and can't deploy on this region.

**2. Feel free to provide a design supporting your feature request.**

**Comment by gjtempleton** [comment]
Where are you seeing this failing and which version of Kops are you running?

As far as I can see most of the required functionality was implemented in the v1.21.7 release of the SDK: https://github.com/aws/aws-sdk-go/pull/2720
with a minor R53 addition as of v1.21.8 https://github.com/aws/aws-sdk-go/pull/2722

The head is already using v1.23.0 as of https://github.com/kubernetes/kops/pull/7404 and this made it into the 1.15 release branch.

**Comment by mangokingTW** [comment]
Sorry, I just found the root cause is on etcd-manager.
