### ISSUE TITLE
Details links on Prow checks point to deprecated interface

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#8063]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Not applicable.

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Not applicable.

**3. What cloud provider are you using?**

Not applicable.

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Navigate to a pull request on the kubernetes/kops repo. Scroll down to one of the checks that is run on Prow, such as "pull-kops-bazel-build". Click on the "Details" link.

**5. What happened after the commands executed?**

Went to a page that had a message at the top:

> The old job viewer has been deprecated. If you need it, please contact #sig-testing on Slack. 

**6. What did you expect to happen?**

Go to an interface that is currently maintained.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Not applicable.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Not applicable.

**9. Anything else do we need to know?**

**Comment by rifelpet** [comment]
I believe that message implies that the Kops jobs are using the "new" job viewer and to contact them if one needs to access the old job viewer. The [prior announcement wording might help explain](https://github.com/kubernetes/test-infra/commit/5e5e630377e9a48fc672b3ce8ab1c4d4b5465e3f). Seeing as the announcement is owned by the test-infra repo, it might make sense to open an issue there.

**Comment by johngmyers** [comment]
That's really confusing wording. It implies that the page being viewed is deprecated.
