### ISSUE TITLE
AZURE Soport

### ISSUE THREAD

**Issue by vafecitos** [kubernetes/kops#8087]
Dear, I would like to know if it is feasible to be able to implement ingration with AZURE, in turn we are willing to finance the development of the implication, I would like to know how we can coordinate and if it is viable, thank you very much.

**Comment by ebcarty** [comment]
May want to comment and see the thread for #3957 - Azure Support.

Propose to close this issue in the mean time.

**Comment by rifelpet** [comment]
Agreed, it is best to consolidate discussion to that issue

/close
