### ISSUE TITLE
single to multi-master docs suggest you can add etcdCluster memebers but Kops 1.16.0-alpha.2 says no

### ISSUE THREAD

**Issue by rayh** [kubernetes/kops#8091]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.16.0-alpha.2 (git-dfaf0b633)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
changed cluster config from:
```
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-ap-southeast-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-ap-southeast-2c
      name: c
    name: events
```
to 
```
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-ap-southeast-2a
      name: a
    - instanceGroup: master-ap-southeast-2b
      name: b
    - instanceGroup: master-ap-southeast-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-ap-southeast-2a
      name: a
    - instanceGroup: master-ap-southeast-2b
      name: b
    - instanceGroup: master-ap-southeast-2c
      name: c
    name: events
```

and then ran:

`kops replace -f kops/all.yaml -v 9`

**5. What happened after the commands executed?**
```
F1211 13:29:14.215685   50042 helpers.go:114] error: error replacing cluster: [spec.etcdClusters[main].Members[a]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[main].Members[b]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[events].Members[a]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[events].Members[b]: Forbidden: EtcdCluster members cannot be added]
```

**6. What did you expect to happen?**
According to the [single to multi-master docs ](https://github.com/kubernetes/kops/blob/master/docs/single-to-multi-master.md), this should work

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
+ kops-darwin-amd64 replace -f kops/all.yaml --force -v 10
I1211 13:47:51.384480   50298 factory.go:68] state store s3://clusters.dev.aws.eliiza.com.au
I1211 13:47:51.414782   50298 aws_cloud.go:1229] Querying EC2 for all valid zones in region "ap-southeast-2"
I1211 13:47:51.418868   50298 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
I1211 13:47:51.735982   50298 status.go:57] Querying AWS for etcd volumes
I1211 13:47:51.736336   50298 status.go:68] Listing EC2 Volumes
I1211 13:47:51.737796   50298 request_logger.go:45] AWS request: ec2/DescribeVolumes
I1211 13:47:52.019957   50298 status.go:40] Cluster status (from cloud): {"etcdClusters":[{"name":"events","etcdMembers":[{"name":"c","volumeId":"vol-081ebb8a13282b8b9"}]},{"name":"main","etcdMembers":[{"name":"c","volumeId":"vol-04b8919810e8a37e7"}]}]}
I1211 13:47:52.180694   50298 s3context.go:210] found bucket in region "us-east-1"
I1211 13:47:52.181117   50298 s3fs.go:220] Reading file "s3://clusters.dev.aws.eliiza.com.au/sydney.k8s.aws.eliiza.com.au/config"
I1211 13:47:53.199843   50298 s3fs.go:220] Reading file "s3://clusters.dev.aws.eliiza.com.au/sydney.k8s.aws.eliiza.com.au/config"
F1211 13:47:53.458748   50298 helpers.go:114] error: error replacing cluster: [spec.etcdClusters[events].Members[a]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[events].Members[b]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[main].Members[b]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[main].Members[a]: Forbidden: EtcdCluster members cannot be added]
```

**9. Anything else do we need to know?**

**Comment by rayh** [comment]
This line seems quite explicit about disallowing addition of new etcdCluster members:

https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/validation/cluster.go#L96

**Comment by rayh** [comment]
Seems the documentation was updated in august by @mccare - could you shed some light on this?

https://github.com/kubernetes/kops/commit/827ef30c77bd252da0aa2b5979c734304244cd7c

**Comment by mccare** [comment]
When I wrote the docs, I've followed the steps outlined to move my single master setup to a multi master setup (version 0.12 just after etcdmanager was introduced).

Right now, I've just tried them out as outlined on a test cluster, but I get the same error you get. (Cannot add etcdMembers). Maybe @justinsb could clarify on how to go from single master to multi master if the etcd members cannot be updated. I would update the docs then.

**Comment by rayh** [comment]
Ah, I could have perhaps downgraded to 0.12 if I hadn't upgraded the cluster API version to apiVersion: kops/v1alpha2 so I could use the g4dn instances types in AWS 🤦‍♂

**Comment by mccare** [comment]
I've just commented out the lines for the validation check, create a single master cluster and moved it to a multi master cluster. Worked for my small use case.

**Comment by rayh** [comment]
@mccare Do you have a mac binary build of kops to hand?  I'm struggling to build it locally

**Comment by mccare** [comment]
Local build is pretty easy, brew install go. Checkout kops in ~/go/src/k8s.io/kops and then make. It will build the binary into ~/go/bin. I have a binary but too big to share it here.

**Comment by mohammadasim** [comment]
I am facing exactly the same issue. I followed the documentation [https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md](url) but when I save the cluster YAML file and save it I get the following error.
`[spec.etcdClusters[main].Members[b]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[main].Members[c]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[events].Members[b]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[events].Members[c]: Forbidden: EtcdCluster members cannot be added]`
kops version `Version 1.16.0`
kubectl version
`Client Version: v1.15.7
Server Version: v1.16.7`

**Comment by michaelajr** [comment]
Yeah. Same here. Kinda need this.

**Comment by anoopmaurya** [comment]
@rayh 
I'm also facinig the same issue Is there any solution for it, 
I can see that [branch](https://github.com/mccare/kops/tree/kops-single-master-upgrade) has been removed by @mccare in which he commented out the validation.

**Comment by olemarkus** [comment]
The fix is in, but not released in a stable version yet

**Comment by fvasco** [comment]
I got the same error on `1.17.1 (git-4dfd4779fe)`

~~~
I0723 12:58:44.719765   24157 factory.go:68] state store s3://kops-example
I0723 12:58:44.731636   24157 aws_cloud.go:1246] Querying EC2 for all valid zones in region "us-east-1"
I0723 12:58:44.731853   24157 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
I0723 12:58:45.376652   24157 status.go:57] Querying AWS for etcd volumes
I0723 12:58:45.376840   24157 status.go:68] Listing EC2 Volumes
I0723 12:58:45.377068   24157 request_logger.go:45] AWS request: ec2/DescribeVolumes
I0723 12:58:45.601825   24157 status.go:40] Cluster status (from cloud): {"etcdClusters":[{"name":"events","etcdMembers":[{"name":"a","volumeId":"vol-xxx"}]},{"name":"main","etcdMembers":[{"name":"a","volumeId":"vol-xxx"}]}]}
I0723 12:58:45.601939   24157 s3context.go:325] unable to read /sys/devices/virtual/dmi/id/product_uuid, assuming not running on EC2: open /sys/devices/virtual/dmi/id/product_uuid: permission denied
I0723 12:58:45.601960   24157 s3context.go:170] defaulting region to "us-east-1"
I0723 12:58:46.132841   24157 s3context.go:210] found bucket in region "us-east-1"
I0723 12:58:46.132931   24157 s3fs.go:284] Reading file "s3://kops-example/devops.example.com/config"
I0723 12:58:46.574146   24157 s3fs.go:284] Reading file "s3://kops-example/devops.example.com/config"
F0723 12:58:46.690689   24157 helpers.go:114] error: error replacing cluster: [spec.etcdClusters[main].Members[e]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[main].Members[c]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[events].Members[c]: Forbidden: EtcdCluster members cannot be added, spec.etcdClusters[events].Members[e]: Forbidden: EtcdCluster members cannot be added]
~~~

Is this issue still present?

**Comment by abhi1git** [comment]
@olemarkus  Can you please let us know whether this fix is now released in a stable version ? If yes, what is the version number.
TIA.

> The fix is in, but not released in a stable version yet

**Comment by olemarkus** [comment]
It was released in 1.18.0

**Comment by abhi1git** [comment]
Thanks @olemarkus Can you please help me with one more doubt.
I am currently using kops version 1.17.0 and Kubernetes cluster version 1.16.9

Is it ok to update kops directly to 1.18.0 and follow the steps mentioned [here](https://kops.sigs.k8s.io/single-to-multi-master/) ? Will this impact my cluster due to kops version upgrade ?

**Comment by olemarkus** [comment]
In theory you should be able to just follow those steps and implicitly upgrade the cluster as part of expanding the control plane
