### ISSUE TITLE
Would be safest to delete the /etc/kubernetes/manifests before mounting disk

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#81]
We have a symlink from /etc/kubernetes/manifests to a manifest on the volume, to avoid the race in #73.

But once the mount the volume, it is possible that a different manifest exists, and the symlink then resolves.

It would be safer to delete the symlink before mounting the volume.  Another option would be to use a UUID in the mount path.

I'm not sure this actually matters much, because the manifest shouldn't be changing anyway.  But we should probably fix to prevent future issues.

**Comment by blakebarnett** [comment]
Should we bump this again or just close it?  Seems to not be causing issues.

**Comment by chrislovecnm** [comment]
Closing
