### ISSUE TITLE
1.16 Conformance test

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/kops#8129]
We're currently not passing [k8s conformance](https://github.com/cncf/k8s-conformance/blob/master/instructions.md) tests for 1.16.

Proceedure:
```
# Run from the latest on release-1.16 branch, however, this method requires uploading your own nodeup and protokube to s3
# Generally we would run this with alpha or beta releases
bazel run //cmd/kops create cluster test.k8s.local -- --zones us-east-2a
bazel run //cmd/kops update cluster -- --yes --name test.k8s.local
sonobuoy run --mode=certified-conformance
```

Failures:
```
[Fail] [sig-network] Services [It] should be able to create a functioning NodePort service [Conformance] 
/workspace/anago-v1.16.3-beta.0.56+b3cbbae08ec52a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/service/jig.go:821

[Fail] [sig-network] Services [It] should be able to change the type from ExternalName to NodePort [Conformance] 
/workspace/anago-v1.16.3-beta.0.56+b3cbbae08ec52a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/service/jig.go:821
```
Full [e2e.log](https://github.com/kubernetes/kops/files/3970029/e2e.log)

I've done a number of tests with other networking settings but have been unable to figure it out.

**Comment by rifelpet** [comment]
Is this related to the e2e failures that we were seeing a while ago? The test client was trying to reach the node port directly which meant we needed to open up security group access.  It might be as simple as adding this flag to the create cluster command:

https://github.com/kubernetes/test-infra/pull/14731

**Comment by mikesplain** [comment]
Ahh yes good point! We can probably just add that as a step to the Kops test. I’ll give that a shot and report back. Thanks!

**Comment by mikesplain** [comment]
Thanks @rifelpet, that worked!  I'll update our docs as well but for now 1.16 conformance submitted:

https://github.com/cncf/k8s-conformance/pull/802

I'll do 1.17 soon as well. For now I'll close this since we have a work around.

/close

**Comment by basu-ntnx** [comment]
@mikesplain : Is that a flag to API server? I am facing the same issue on 1.16.6 and  Sonobuoy Version: v0.17.2.

**Comment by basu-ntnx** [comment]
@mikesplain :
[Fail] [sig-network] Services [It] should be able to change the type from ExternalName to NodePort [Conformance]
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/service/jig.go:821

[Fail] [sig-network] Services [It] should be able to change the type from ExternalName to ClusterIP [Conformance]

**Comment by kciredor** [comment]
@mikesplain just hit this one as well and I understand there's a workaround.

Why has this issue been closed when kops create does not result in a compliant cluster without having to specify the override manually?
