### ISSUE TITLE
One of the master node is not getting registered after cluster restoration from s3 bucket

### ISSUE THREAD

**Issue by tsahoo** [kubernetes/kops#8137]
1.kops version
Version 1.13.2 
2.Kubernetes version
v1.13.11
3.Cloud provider
AWS
---------------------------------------
4.Need help on below issues.
Recently we recovered our kops cluster from S3 bucket.  Cluster is up and running fine after recover.**(our kops  version 1.13.2 and k8s  version 1.13.11**)
We have 3 master nodes,But one of the master node is not registering to the cluster. Below are the logs and observations on the unregistered master node:
**1.kube api server container is getting restarted. Below is error log:**

I1217 05:52:45.462959       1 server.go:146] Version: v1.13.11
W1217 05:52:46.219752       1 admission.go:78] PersistentVolumeLabel admission controller is deprecated. Please remove this controller from your configuration files and scripts.
I1217 05:52:46.220234       1 plugins.go:158] Loaded 10 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,PersistentVolumeLabel,DefaultStorageClass,MutatingAdmissionWebhook.
I1217 05:52:46.220254       1 plugins.go:161] Loaded 6 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,ResourceQuota.
W1217 05:52:46.220643       1 admission.go:78] PersistentVolumeLabel admission controller is deprecated. Please remove this controller from your configuration files and scripts.
I1217 05:52:46.221085       1 plugins.go:158] Loaded 10 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,PersistentVolumeLabel,DefaultStorageClass,MutatingAdmissionWebhook.
I1217 05:52:46.221104       1 plugins.go:161] Loaded 6 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,ResourceQuota.
I1217 05:52:46.231890       1 store.go:1414] Monitoring customresourcedefinitions.apiextensions.k8s.io count at <storage-prefix>//apiextensions.k8s.io/customresourcedefinitions
I1217 05:52:46.262742       1 master.go:228] Using reconciler: lease
I1217 05:52:46.281798       1 store.go:1414] Monitoring podtemplates count at <storage-prefix>//podtemplates
F1217 05:53:06.282546       1 storage_decorator.go:57] **Unable to create storage backend: config (&{etcd3 /registry [https://127.0.0.1:4002] /etc/kubernetes/pki/kube-apiserver/etcd-client.key /etc/kubernetes/pki/kube-apiserver/etcd-client.crt /etc/kubernetes/pki/kube-apiserver/etcd-ca.crt true {0xc00079eab0 0xc00079eb40} <nil> 5m0s 1m0s}), err (context deadline exceeded)**

2.Below is the error etcd Event  log

**rafthttp: request sent was ignored (cluster ID mismatch: peer[******]=******, local=********)**

3.Below is the kubelet status log

 kubelet[5450]: W1217 07:22:25.726994    5450 cni.go:203] **Unable to update cni config: No networks found in /etc/cni/net.d/
 kubelet[5450]: E1217 07:22:25.727129    5450 kubelet.go:2194] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized**
**kubelet[5450]: E1217 07:24:08.677946    5450 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://127.0.0.1/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:443: connect: connection refused**
**we use calico for networking.**
Need quick help on this.

**Comment by tsahoo** [comment]
@justinsb Could you please look into this issue.

**Comment by tsahoo** [comment]
Any update on this?

**Comment by geojaz** [comment]
@tsahoo Could you pls share a sanitized version of your cluster spec? Also, it looks like you're running a fairly old version of kops. Would you be able to update to the latest release? I would guess that you'll be more likely to get a useful response if you'll try to sync your release up with us.

**Comment by tsahoo** [comment]
@geojaz Below is the cluster spec:
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Team: DevOps
  cloudProvider: aws
  configBase: s3 bucket
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    - instanceGroup: master-us-east-2b
      name: b
    - instanceGroup: master-us-east-2c
      name: c
    name: main
    provider: Manager
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    - instanceGroup: master-us-east-2b
      name: b
    - instanceGroup: master-us-east-2c
      name: c
    name: events
    provider: Manager
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.11
  masterInternalName: 
  masterPublicName: 
  networkCIDR: 
  networking:
    calico: {}
  nonMasqueradeCIDR: 
  sshAccess:
  - 
  subnets:
  - cidr: 
    name: us-east-2a
    type: Private
    zone: us-east-2a
  - cidr: 
    name: us-east-2b
    type: Private
    zone: us-east-2b
  - cidr: 
    name: us-east-2c
    type: Private
    zone: us-east-2c
  - cidr: 
    name: utility-us-east-2a
    type: Utility
    zone: us-east-2a
  - cidr: 
    name: utility-us-east-2b
    type: Utility
    zone: us-east-2b
  - cidr: 
    name: utility-us-east-2c
    type: Utility
    zone: us-east-2c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

**Comment by vvbogdanov87** [comment]
The same when I upgraded from 1.14 to 1.15 today. Master failed to start.
The new master:
```
admin@ip-*-*-*-*:~$ sudo ls -al /etc/cni/net.d/
total 8
drw-r--r-- 2 root root 4096 Jan 10 04:11 .
drwxr-xr-x 3 root root 4096 Jan 10 04:11 ..
```
The old one:
```
admin@ip-*-*-*-*:~$ sudo ls -al /etc/cni/net.d/
total 16
drw-r--r-- 2 root root 4096 Jan  7 05:36 .
drwxr-xr-x 3 root root 4096 Nov 19 02:15 ..
-rw-r--r-- 1 root root  595 Jan  7 05:36 10-canal.conflist
-rw------- 1 root root 2570 Jan  7 05:36 calico-kubeconfig
```

**Comment by vvbogdanov87** [comment]
several warnings in nodeup log
```
Jan 10 04:11:19 ip-10-63-128-208 nodeup[964]: W0110 04:11:19.821209     964 assetstore.go:203] error downloading url "https://artifacts.k8s.io/binaries/
kops/1.15.0/linux/amd64/utils.tar.gz": error response from "https://artifacts.k8s.io/binaries/kops/1.15.0/linux/amd64/utils.tar.gz": HTTP 404
...
Jan 10 04:11:22 ip-10-63-128-208 nodeup[964]: W0110 04:11:22.816090     964 file.go:92] Unable to find task "user/admin"
Jan 10 04:11:22 ip-10-63-128-208 nodeup[964]: W0110 04:11:22.816403     964 file.go:92] Unable to find task "user/admin"
...
Jan 10 04:11:46 ip-10-63-128-208 nodeup[964]: W0110 04:11:46.361022     964 load_image.go:63] LoadImageTask checking if image present not yet implemente
d
...
Jan 10 04:11:46 ip-10-63-128-208 nodeup[964]: W0110 04:11:46.528497     964 load_image.go:93] error downloading url "https://artifacts.k8s.io/binaries/k
ops/1.15.0/images/protokube.tar.gz": error response from "https://artifacts.k8s.io/binaries/kops/1.15.0/images/protokube.tar.gz": HTTP 404
```
