### ISSUE TITLE
Proposal: Have new multi-zone AWS clusters create node instance groups per zone

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#8152]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Currently `kops create cluster --zones us-east-1a,us-east-1b,us-east-1c` will create a single instance group (autoscaling group) that spans all 3 zones. This is problematic for autoscaling because any autoscaler can't choose which zone a new instance will be launched in. This impacts pod scheduling for StatefulSets that use EBS Volumes as well as various affinity/antiaffinity rules. 

We can avoid these limitations by having new clusters create 3 instance groups, one for each zone. Kops users often discover these limitations after having created the cluster and adjust their InstanceGroups as described, so if we can address it automatically, it is one less hurdle for them to deal with.

This would only impact the `kops create cluster` command. Anyone providing InstanceGroup manifests directly would be unaffected.

The downside of this is that there are more AWS resources which may be overwhelming for new users experimenting with Kops.

I dont know if other cloud providers have similar limitations but we could extend this to other clouds if appropriate.

**Comment by johngmyers** [comment]
We tend to put StatefulSets in application-specific instancegroups, leaving "nodes" for stateless workloads. But it'd be easy enough to have our automation customize this back if we wanted to.

I wonder if we'd want to either add an abstraction for a related set of nodes instancegroups or extend the "instancegroup role" abstraction to permit user-defined roles.

**Comment by MMeent** [comment]
Another point for multiple ASGs: AWS ASGs spanning multiple zones are auto-balancing, meaning that if your nodes are not evenly balanced across AZs (e.g. through downscaling of empty nodes in one zone) some of your nodes may be killed by aws to ~be moved~ have another node start up in another AZ. This is documented behaviour of ASGs, but also probably not something a new user would want to experience.

I am for making the default for` --zones=<multiple-zones>` create 1 ASG per zone instead of creating one ASG spread over multiple zones

**Comment by olemarkus** [comment]
@rifelpet I think it is worth doing this. We use ASG per AZ ever since the autoscaling failure in eu-central-1 some time ago. That affected ASG scaling events in any ASG that spanned the affected AZ.

**Comment by rifelpet** [comment]
I think a PR would be pretty straight forward, mostly touching this logic:

https://github.com/kubernetes/kops/blob/80e1da9dd2cce66f7db8c7b5056baff4f340bf76/cmd/kops/create_cluster.go#L821-L842

Perhaps its worth bringing this up at the next office hours to get any more feedback and then move forward?

**Comment by olemarkus** [comment]
Sounds like a good idea.

**Comment by MoShitrit** [comment]
Yep, agree it's worth doing.
We also have one IG per AZ, as this is a recommendation on cluster-autoscaler for our setup.
Having kops manage that for us would be great!
