### ISSUE TITLE
Openstack - PVCs are not mounting to the nodes because of node affinity.

### ISSUE THREAD

**Issue by raviranjithkumar** [kubernetes/kops#8167]
kops version: 1.15
Kubernetes version:1.15.7
Cloud provider: Openstack
Task: Need to deploy a stateful application

Issue:
When i do the dynamic provision of PVs, the Pvs are getting created with the node affinity which consists of the availability zone of the storage which is nova. The instances are running different availability zones, that results the issue in attaching the pvs to the nodes for scheduling the pods.

Let me know how i can resolve this issue.

**Comment by zetaab** [comment]
You need to use ignore volume az option
