### ISSUE TITLE
CNI pod shows 0/1 status(readinessProbe failed) after kops up gradation of 1.13.

### ISSUE THREAD

**Issue by tsahoo** [kubernetes/kops#8174]
1.kops version: 1.13.2
2. Kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
3.Cloud- AWS
4.Command
kubectl get pods -n kube-system |grep calico
---------
After upgrading the kops to 1.13, we found out calico pod is showing 0/1 status. Below are the error logs:
1.After describing the pod its showing readinessProbe failed.
2.Readiness probe failed: calico / node is not ready: BIRD is not ready: BGP not established with (nodes ips) [INFO] [127] health.go 156: Number of node (s) with BGP peering established = 7
3.
calico/node is not ready: BIRD is not ready: BGP not established.
**Calico version : 3.7.4  Image (quay.io/calico/node:v3.7.4)**
**Cni version : 3.7.4 (image: quay.io/calico/cni:v3.7.4)**
4.Below are the status inside the calico pod:
 netstat -tunlp |grep 179
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      125/bird

 ps -ef |grep calico
root        48    47  0 12:34 ?        00:01:07 calico-node -confd
root        51    44  1 12:34 ?        00:01:55 calico-node -felix
root       124    46  0 12:34 ?        00:00:00 bird6 -R -s /var/run/calico/bird6.ctl -d -c /etc/calico/confd/config/bird6.cfg
root       125    45  0 12:34 ?        00:00:01 bird -R -s /var/run/calico/bird.ctl -d -c /etc/calico/confd/config/bird.cfg
root     13015 12835  0 14:45 pts/0    00:00:00 grep calico
![image](https://user-images.githubusercontent.com/40820220/71310251-ef036600-2437-11ea-8b63-e295a3dbc5d2.png)

Please help on the this issue as a prority.

**Comment by tsahoo** [comment]
@justinsb Could you please look into this issue.

**Comment by tsahoo** [comment]
Any update on this?

**Comment by olemarkus** [comment]
I assume this happened only on that one upgrade. If it happens on newest version of kops, let me know.
