### ISSUE TITLE
Specify different Route Table for subnet kops creates

### ISSUE THREAD

**Issue by ryan109** [kubernetes/kops#8178]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Apologies if this is already possible and I've missed the documentation on it.

*Background:*
I built a cluster and allowed kops to create a lot of the default infrastructure around it, including the subnets/VPC. When it created the 3 subnets in the separate AZs it only created 1 routeTable between them, which is fine. The configuration of our internal networking requires that I need a different route table attached to each subnet, I have created the new tables and connected them manually through the console - which achieved the network state I was looking for.

*Problem:*
Now when I do anything using `kops update cluster` it will not have registered the changed tables as the state was never stored by kops, so updates to the cluster end up reconnecting the original single route table across all 3 subnets. Obviously I could just add it again through the console but this isn't sustainable.

Is it possible to specify routeTable under subnet configuration and I've missed the documentation? Something along the lines of:
```
  - cidr: X.X.X.X/16
    name: eu-west-1a
    zone: eu-west-1a
    routeTable: rtb-X
```
Currently `routeTable` isn't recognised.

**2. Feel free to provide a design supporting your feature request.**
Add the ability to specify a `routeTable` field per subnet.

**Comment by ryan109** [comment]
Would anyone be able to confirm that changing the routeTable is a current limitation of KOPs?

/help

**Comment by pryan-branch** [comment]
Currently having this issue too and would like to know

**Comment by amitach** [comment]
Have the exact same issue and would like to know if this is in the pipeline.

**Comment by olemarkus** [comment]
We used to have this issue, but later opted for reusing the same subnet across all our clusters. For us, subnets didn't add any extra isolation anyway. It is not really something any of us are looking at at the moment.

/kind feature
