### ISSUE TITLE
I need a mirrored version that supports the Middle East  （Update aws-sdk-go #282）

### ISSUE THREAD

**Issue by xulikai** [kubernetes/kops#8187]
I see that you have incorporated the latest code here（Update aws-sdk-go #282）, but have not released a new mirror version.
so,Could you release the latest mirrored version that supports the me-south-1 region

**Comment by gjtempleton** [comment]
What command are you trying to run, what error message are you seeing and which versions are you running of both kops and kubernetes?

I believe kops should have an up to date version of the aws-go-sdk that supports `me-south-1` as of https://github.com/kubernetes/kops/pull/7404

**Comment by xulikai** [comment]
thanks , I have found the relevant image and deployed it successfully 
I used version 15.0 for Kops and version 15.6 for k8s. I found that there was no image I needed in the public image of me-south-1. I manually modified the version of etcd manager in other areas and re typed a image to upload to me-south-1
