### ISSUE TITLE
error running task "RouteTable/myfirstcluster.k8s.local"

### ISSUE THREAD

**Issue by luntzel** [kubernetes/kops#8240]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.15.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.17.0

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops update cluster --name myfirstcluster.k8s.local --yes

**5. What happened after the commands executed?**

lots of: 

W1231 12:20:23.012869   82822 executor.go:130] error running task "RouteTable/myfirstcluster.k8s.local" (7m5s remaining to succeed): error creating RouteTable: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx

There is a route table created however 

**6. What did you expect to happen?**

The command should not return retrying errors 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-12-31T20:17:09Z"
  name: myfirstcluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://xxx-xxx-xxx-xxx/myfirstcluster.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.6
  masterPublicName: api.myfirstcluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-12-31T20:17:09Z"
  labels:
    kops.k8s.io/cluster: myfirstcluster.k8s.local
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-12-31T20:17:10Z"
  labels:
    kops.k8s.io/cluster: myfirstcluster.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

I1231 12:31:41.456517   83015 executor.go:103] Tasks: 88 done / 91 total; 1 can run
I1231 12:31:41.456601   83015 executor.go:178] Executing task "RouteTable/myfirstcluster.k8s.local": *awstasks.RouteTable {"Name":"myfirstcluster.k8s.local","Lifecycle":"Sync","ID":null,"VPC":{"Name":"myfirstcluster.k8s.local","Lifecycle":"Sync","ID":"vpc-0669d9abdaffb18d2","CIDR":"172.20.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":false,"Tags":{"KubernetesCluster":"myfirstcluster.k8s.local","Name":"myfirstcluster.k8s.local","kubernetes.io/cluster/myfirstcluster.k8s.local":"owned"}},"Shared":false,"Tags":{"KubernetesCluster":"myfirstcluster.k8s.local","Name":"myfirstcluster.k8s.local","kubernetes.io/cluster/myfirstcluster.k8s.local":"owned","kubernetes.io/kops/role":"public"}}
I1231 12:31:41.456782   83015 request_logger.go:45] AWS request: ec2/DescribeRouteTables
I1231 12:31:41.757939   83015 request_logger.go:45] AWS request: ec2/DescribeRouteTables
I1231 12:31:41.835045   83015 routetable.go:174] Creating RouteTable with VPC: "vpc-0669d9abdaffb18d2"
I1231 12:31:41.835159   83015 request_logger.go:45] AWS request: ec2/CreateRouteTable
W1231 12:31:41.912244   83015 executor.go:130] error running task "RouteTable/myfirstcluster.k8s.local" (8m44s remaining to succeed): error creating RouteTable: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 87164543-6fd9-4265-8d3a-86aa0dbf98c8
I1231 12:31:41.912278   83015 executor.go:145] No progress made, sleeping before retrying 1 failed task(s)

**9. Anything else do we need to know?**

**Comment by rifelpet** [comment]
Can you post the IAM policy that your AWS credentials run with? It seems like the credentials used when running the `kops` binary do not have certain `ec2:*` permissions

**Comment by luntzel** [comment]
Oh you're right - another policy is denying CreateRouteTable despite my kops group having AmazonEC2FullAccess. Closing this. Thank you
