### ISSUE TITLE
Import package aliases are not uniform.

### ISSUE THREAD

**Issue by yuxiaobo96** [kubernetes/kops#8244]
In kops, there are some import package aliases are not uniform.
For `"k8s.io/kops/pkg/apis/kops"`, there are several aliases:
```go
"k8s.io/kops/pkg/apis/kops"
kops "k8s.io/kops/pkg/apis/kops"
api "k8s.io/kops/pkg/apis/kops"
kopsapi "k8s.io/kops/pkg/apis/kops"
```
For `"k8s.io/apimachinery/pkg/apis/meta/v1"`, there are several aliases:
```go
v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
```
Therefore, I suggest to update:
`"k8s.io/kops/pkg/apis/kops"` -> `kopsapi "k8s.io/kops/pkg/apis/kops"`
`v1 "k8s.io/apimachinery/pkg/apis/meta/v1"` -> `metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"`

**Comment by yuxiaobo96** [comment]
/cc @hakman 
/cc @rifelpet 
Please give some suggestions.

**Comment by tanjunchen** [comment]
Good suggestion.why not?

**Comment by tomesm** [comment]
Hi, can I also participate. I am a newbie and this seems to be a task which I could manage. I have already signed the CLA.

I am not sure if I can open the PR and reference it to this issue without asking thats why I am asking here in advance :)

**Comment by rifelpet** [comment]
I think the open PR #8256 might be addressing the remaining imports mentioned in this issue but if you find other imports with similar inconsistencies feel free to mention them here and open a PR :)

**Comment by tomesm** [comment]
@rifelpet Actually, there are lots of such files:

> cmd/kops/create_ig.go
cmd/kops/export_kubecfg.go
cmd/kops/get_cluster.go
cmd/kops/rollingupdatecluster.go
cmd/kops/delete_cluster.go
cmd/kops/upgrade_cluster.go
cmd/kops/validate_cluster.go
upup/pkg/fi/cloudup/loader.go
upup/pkg/fi/cloudup/spec_builder.go
upup/pkg/fi/cloudup/networking.go
pkg/model/components/containerd_test.go
upup/pkg/fi/cloudup/deepvalidate_test.go
upup/pkg/fi/cloudup/populatecluster_test.go
upup/pkg/fi/cloudup/populate_cluster_spec.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
upup/pkg/fi/cloudup/populateinstancegroup_test.go

And the above are only `api -> kopsapi `:) I have corrected all of them and will open the PR and start searching for `v1 -> metav1` files.
