### ISSUE TITLE
Can't activate TTLAfterFinished feature gate

### ISSUE THREAD

**Issue by demisx** [kubernetes/kops#8267]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.15.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
$ kops edit cluster
---
(add this in vi)
kubelet:
    ...
    featureGates:
      TTLAfterFinished: "true"
$ kops update cluster prod.dimaslist.org --yes
$ kops rolling-update cluster --yes
```

**5. What happened after the commands executed?**

A completed  K8S job with `spec.ttlSecondsAfterFinished=120` isn't being auto-deleted. It sticks around like before. I am not sure if I enabled this feature properly. I've followed these instructions https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#feature-gates

**6. What did you expect to happen?**

A completed  K8S job with `spec.ttlSecondsAfterFinished=120` will be automatically removed after 2 mins. 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

[cluster.yaml.txt](https://github.com/kubernetes/kops/files/4022095/cluster.yaml.txt)

**Comment by rifelpet** [comment]
[The docs](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) for that feature gate mention it needs to be added to both kube-apiserver and kube-controller-manager. Looking at your spec you've added it to kubelet. The cluster spec supports adding featureGates to kube-apiserver and kube-controller-manager as well, so can you try that?

```yaml
spec:
  kubeControllerManager:
    featureGates:
      TTLAfterFinished: "true"
  kubeAPIServer:
    featureGates:
      TTLAfterFinished: "true"
```

**Comment by demisx** [comment]
@rifelpet You are exactly right! Somehow, I missed that line. It's working as expected now!
