### ISSUE TITLE
Add default ssh users

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#828]
At least to the docs.  Maybe to the recommended commands as well (but this would mean "knowing" what type of image it was).

debian: admin
ubuntu: ubuntu
rhel: ec2-user
centos: ?

**Comment by austinmoore-** [comment]
The [official Centos AMI](https://aws.amazon.com/marketplace/pp/B00O7WM7QW) uses `centos`.

**Comment by justinsb** [comment]
Thanks @austinmoore... Wasn't sure when I was writing the issue!
