### ISSUE TITLE
Error while creating a cluster with existing VPC

### ISSUE THREAD

**Issue by MohamedMSaeed** [kubernetes/kops#8287]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.15.0

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create cluster -v 1 \
    --zones "us-west-1a,us-west-1c" \
    --master-size "t2.medium" \
    --node-size "t2.medium" \
    --node-count "3" \
    --name "${KOPS_CLUSTER_NAME}" \
    --vpc "VPC-ID"  \
    --yes
```

**5. What happened after the commands executed?**
```
W0108 10:42:22.689864   12369 executor.go:130] error running task "Subnet/us-west-1c.k8.test.com" (22s remaining to succeed): error creating subnet: InvalidSubnet.Conflict: The CIDR '172.20.64.0/19' conflicts with another subnet
	status code: 400, request id: e39ba695-6833-4f46-ad6d-9968e1b5b741
W0108 10:42:22.689907   12369 executor.go:130] error running task "Subnet/us-west-1a.k8.test.com" (22s remaining to succeed): error creating subnet: InvalidSubnet.Conflict: The CIDR '172.20.32.0/19' conflicts with another subnet
	status code: 400, request id: 3bbc0182-a603-4401-afaf-041e3d0639d4
```
**6. What did you expect to happen?**

I know that this error is because Kops is trying to create subnets using CIDR which is already taken. 
Also, I know that to solve this problem I need to use ``` kops edit cluster``` and edit the CIDR. 

The problem is I'm trying to create the cluster automatically without any human interaction. Is there any way to tell Kops to use other CIDR range when it fails to create subnet? Especially I noticed that it uses the same CIDR each time.

**Comment by ngoyal16** [comment]
you can use SUBNET_CIDR env varaible to define another subnet cidr. this way you don't need to edit file. it will auotmatically add given cidr

**Comment by MohamedMSaeed** [comment]
I tried to use SUBNET_CIDR but it didn't work. Can you please tell me how can I use it? There is no option in kops create cluster using SUBNET_CIDR.

**Comment by ngoyal16** [comment]
export VPC_ID=vpc-XXX # replace with your VPC id
export SUBNET_ID=subnet-XXX # replace with your subnet id
export SUBNET_CIDR=10.4.0.0/20 # replace with your subnet CIDR

export SUBNET_IDS=subnet-XXX # replace with your comma separated subnet ids

kops create cluster ${CLUSTER_NAME} \
  --vpc=${VPC_ID} \
  --subnets=${SUBNET_IDS} \
  --zones=ap-south-1a \
  --cloud-labels="Environment=Development" \
  --networking calico

**Comment by MohamedMSaeed** [comment]
@ngoyal16 I believe that is the problem, I have to create the subnets myself and provide ids to kops. 
What I need is to find a way to tell kops to create the subnets itself but if the subnet CIDR was taken, use another CIDR.
