### ISSUE TITLE
AWS: KOPS created AutoScalingGroups use EC2 health check type with 0 second grace period

### ISSUE THREAD

**Issue by nhoughto** [kubernetes/kops#8292]
Looking at the code and api specs I can't see a way to configure  KOPS to create the KOPS managed ASGs in AWS with ELB health checks.

We have a 3 master setup with a 1 instance group of nodes and all 4 ASGs created by KOPS are configured with `EC2` health check type with 0 second grace period.

Our naive understanding is that this means that if a ec2 instance becomes unhealthy because kubelet dies (or is never healthy to start with) then it will never be destroy and recreated by the ASG, we assumed there would be an option for configuring an ELB health check type that could then check via HTTP if kubelet on the ec2 instance was healthy, but that doesn't seem to be the case?

Looking here:
https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md
https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/instancegroup.go

**Comment by olemarkus** [comment]
Which ELB would you add to that? Only masters have ELBs provisioned by kops.

**Comment by nhoughto** [comment]
Configurable? I see there is an externalLoadBalancer property so that elb? If that doesn’t work a separate property?

**Comment by rifelpet** [comment]
Typically Kops users solve this with [cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) which will terminate EC2 instances in an ASG under a variety of conditions.

**Comment by nhoughto** [comment]
yeah i can see how that would work, autoscaler would terminate the instance because its not taking workload. That doesn't help a cluster that is static / doesnt scale though.

I'm surprised that there doesn't seem to be an obvious answer to this? I thought for sure I missed something, how can the idiomatic way to stand up a cluster in KOPS not actually healthcheck the EC2 instances it starts? very surprising.

**Comment by olemarkus** [comment]
I am thinking the problem is valid, but the solution is not. One needs something a bit more k8s native than just what EC2 health checks does. Maybe a feature of kops controller could be to do something like this: https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-repair

**Comment by mausch** [comment]
https://github.com/kubernetes/kops/issues/4147

**Comment by olemarkus** [comment]
I don't think there is much more to do here. Kops uses the EC2 health checks and there isn't much more that is offered directly from AWS.

/close

**Comment by akloss-cibo** [comment]
@olemarkus the other thing directly offered from AWS is balancer health checks... it would be pretty convenient to be able to reuse the existing AWS infrastructure for monitoring instance health rather than building something proprietary.  It would be possible for kops to grow a monitoring feature too, which would be fine too.  It would be nice to _not_ have to build my own instance monitoring, one way or another.

**Comment by olemarkus** [comment]
As mentioned in that doc I just posted, a node that is unresponsive will be tainted as Unreachable, and after a configurable amount of time, all Pods (except those managed by a StatefulSet) will be evicted. This means all Pods will be removed from the failed node. CAS will scale up a replacement node if needed. CAS may terminate the instance if it meets all the other conditions for termination.
