### ISSUE TITLE
Fail to start etcd-manager for cluster in me-south-1

### ISSUE THREAD

**Issue by davis-x** [kubernetes/kops#8295]
Tried to create cluster on me-south-1 (this region is very new) with kops 1.15.0 using:
All resources on AWS is created but the cluster isn't starting correctly.
Looking at the logs on the master node I can see that the docker images for etcd-manager fails with:
```
unexpected error running etcd cluster reconciliation loop: 
error refreshing control store after leadership change: 
error reading s3://<state-store>/<cluster-name>/backups/etcd/main/control/backups/etcd/main/control: 
me-south-1 is not a valid region\n
```

This issue appears to be identical to https://github.com/kubernetes/kops/issues/6998 which makes me think that (according to that ticket) 
"I guess a simple update of the aws-sdk component in etcd-manager should solve this?"

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.15.0 (git-9992b4055)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
 1.13.12

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I created a cluster in me-south-1 and looked at the logs on the master node. 

**5. What happened after the commands executed?**
The cluster comes up, but etcd fails to start. Similar to https://github.com/kubernetes/kops/issues/6998 the etcd-manager logs spit out 
```
{"log":"W0109 14:22:19.720656    3851 controller.go:149] unexpected error running etcd cluster reconciliation loop: error refreshing control store after leadership change: 

error reading s3://<state-store>/<cluster-name>/backups/etcd/main/control: me-south-1 is not a valid region\n","stream":"stdout","time":"2020-01-09T14:22:19.72074147Z"}
```

**6. What did you expect to happen?**
I expected etcd to start correctly. 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by mmerrill3** [comment]
the latest etcd-manager has an updated aws-sdk:
The merge is here:
https://github.com/kopeio/etcd-manager/pull/282

**Comment by rifelpet** [comment]
The version of etcd-manager bundled with Kops 1.16.2 and 1.17.0 supports me-south-1.
If you still encounter etcd issues in that region feel free to reopen this.

/close
