### ISSUE TITLE
Change hard coded param that breaks on some aws region?

### ISSUE THREAD

**Issue by yancl** [kubernetes/kops#830]
Hi, I found that the following code related with the `us-east-1` does not work in cn-north-1 region, will you please make a change on it? thanks.

```
//upup/pkg/fi/cloudup/awsup/aws_utils.go
35 // ValidateRegion checks that an AWS region name is valid
 36 func ValidateRegion(region string) error {
 37     if allRegions == nil {
 38         glog.V(2).Infof("Querying EC2 for all valid regions")
 39
 40         request := &ec2.DescribeRegionsInput{}
 41         config := aws.NewConfig().WithRegion("us-east-1")
```

```
util/pkg/vfs/s3context.go
57 func (s *S3Context) getRegionForBucket(bucket string) (string, error) {
 58     region := func() string {
 59         s.mutex.Lock()
 60         defer s.mutex.Unlock()
 61         return s.bucketLocations[bucket]
 62     }()
 63
 64     if region != "" {
 65         return region, nil
 66     }
 67
 68     // Probe to find correct region for bucket
 69     s3Client, err := s.getClient("us-east-1")
```

**Comment by austinmoore-** [comment]
Chiming in with some info about the China AWS region. Most, if not all, of the AWS products in China are completely isolated from the rest of the AWS regions. Services like S3 that operate across regions will require special use cases just for the China region.

I suggest that clients are created using the region specified in the user's `~/.aws/config`. I know that in the Python AWS package, it will pull in the region automatically if not specified. Can we do something similar here?

**Comment by yancl** [comment]
@austinmoore,  yes, you are right, we should use `~/.aws/config` whenever possible to make it clear.  but as you can see the comments from @nelson9087 at here #799, the hard code `us-east-1` override the config from `~/.aws/config`, i think that is the problem i want to point out:)

**Comment by yancl** [comment]
see PR https://github.com/kubernetes/kops/pull/961
