### ISSUE TITLE
not able to use kubernets-dashboard on kops cluster

### ISSUE THREAD

**Issue by ngoyal16** [kubernetes/kops#8301]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** : 1.15

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.** : 1.15

**3. What cloud provider are you using?** : AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml

after that i took master instance ip.

https://INSTANCE_IP/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

**5. What happened after the commands executed?**

Error: 'dial tcp 100.96.2.2:8443: i/o timeout'
Trying to reach: 'https://100.96.2.2:8443/'

**6. What did you expect to happen?**

should open the kubernet dashboard

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-01-09T17:31:02Z"
  generation: 1
  name: k8s-dev.example.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Environment: Development
  cloudProvider: aws
  configBase: s3://example-k8s-state-store/k8s-dev.example.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.6
  masterInternalName: api.internal.k8s-dev.example.com
  masterPublicName: api.k8s-dev.example.com
  networkCIDR: 10.4.0.0/16
  networkID: vpc-ID
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.4.0.0/20
    id: subnet-ID
    name: ap-south-1a
    type: Public
    zone: ap-south-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-01-09T17:31:03Z"
  labels:
    kops.k8s.io/cluster: k8s-dev.example.com
  name: master-ap-south-1a
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: c4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-south-1a
  role: Master
  subnets:
  - ap-south-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-01-09T17:31:03Z"
  labels:
    kops.k8s.io/cluster: k8s-dev.example.com
  name: nodes
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-south-1a

**Comment by pradeepnnv** [comment]
@ngoyal16 , Is `100.96.2.2` your master ip address? 
Based on your `nonMasqueradeCIDR: 100.64.0.0/10` from kops cluster.yaml, that ip seems like it's a Kube internal ip. 

Have you tried this? https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#accessing-the-dashboard-ui
