### ISSUE TITLE
Support custom AWS IAM credentials for kops-controller

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#8306]
kops-controller is a new component introduced for k8s 1.16+ clusters. It runs on the master nodes and interacts with the cloud provider. For AWS it uses the EC2 instance's instance profile to get credentials using the instance metadata service.

Often users have access to the instance profile locked down so that pods cannot use its credentials and instead require a more explicit method.

Kube2iam for example has a `--default-role` which it will use when intercepting requests for instance profile credentials from a pod that does not have a role-arn annotation. We use this with a permission-less role, so that pods without an annotation behave similar to EC2 instances without an instance profile. This behavior cannot easily be restricted to certain namespaces (in order to whitelist kube-system) or certain nodes (in order to whitelist the masters). This setup will break kops-controller.

I'm proposing that Kops supports specifying annotations on the kops-controller pods so that we can provide it a role-arn to be recognized by kube2iam and other pod identity solutions. This would be exposed through an API field in the ClusterSpec - exact path TBD.

**Comment by rifelpet** [comment]
It will also help to document the exact AWS permissions required, for users providing their own IAM role. I believe it is just [ec2:DescribeInstances](https://github.com/kubernetes/kops/blob/ebd7a29612cd47a7613870621c23f93e29a10965/pkg/nodeidentity/aws/identify.go#L120).

**Comment by joshbranham** [comment]
So the `kops-controller` just runs on Masters, and needs to read tags or also put tags?

**Comment by rifelpet** [comment]
Currently it just reads the EC2 instance tags. That may change as we add more functionality to the controller though.

**Comment by rifelpet** [comment]
@justinsb i forgot to mention this yesterday, any thought on this? I was thinking of a podAnnotations field for kops-controller in the cluster spec but I wasn’t sure where it would go exactly

**Comment by johngmyers** [comment]
For kiam, we could just bake in the `iam.amazonaws.com/role` annotation directly. That could also serve as the documentation of what is needed. Kube2iam would seem to require either custom annotations or IAM role creation.

**Comment by mazzy89** [comment]
Would this bind kops too much to use external toolings like `kiam` or `kube2iam`? Couldn't we adopt an approach more like the cloud controller manager?

**Comment by rifelpet** [comment]
After more investigation, it turns out that kube2iam doesn't intercept instance metadata requests for pods with `hostNetwork: true`. [kops-controller does use hostNetwork true](https://github.com/kubernetes/kops/blob/f8915dca9bc43ef98d2690d92bf21d14e409e475/upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template#L45) so this may not be an issue after all.

I don't use kiam so I can't confirm whether it behaves the same way, but if someone else can confirm that then we could close this issue out.

**Comment by johngmyers** [comment]
Kiam behaves the same way, per uswitch/kiam#119

**Comment by rifelpet** [comment]
great, sounds like this is safe to close then. one less 1.16 blocker.
/close
