### ISSUE TITLE
CoreDNS v1.3.1 emptyDir workaround blocks node draining

### ISSUE THREAD

**Issue by antoinedeschenes** [kubernetes/kops#8309]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.15.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.15.6

The emptyDir volume used in fix #7492 prevents cluster-autoscaler from evicting some nodes. Default behavior is to skip draining of nodes using emptyDir volumes.

We've identified a few workarounds:
- Remove CoreDNS emptyDir volume, which requires a CoreDNS update (#7883)
- Allow custom annotations on the CoreDNS pod, allowing us to add annotation `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"` (not possible with the current template)
- Setting `"skip-nodes-with-local-storage=false"` on the Cluster Autoscaler.

**Comment by johngmyers** [comment]
People run Cluster Autoscaler without `skip-nodes-with-local-storage=false`?

**Comment by phspagiari** [comment]
[Based on this comment](https://github.com/kubernetes/kops/pull/8333#issuecomment-574305925) I think the best option is to bump CoreDNS to 1.6.6 and cherry-pick it to kops v1.15.1. The `emptyDir` is really a workaround and should be removed soon as possible, bumping CoreDNS really solves the problem.
