### ISSUE TITLE
Empty DOCKER_OPTIONS when using Ubuntu 16.04 official AMI 

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kops#831]
Empty DOCKER_OPTIONS when using Ubuntu 16.04 official AMI .

"sudo systemctl reload-or-restart docker" is fixing the problem

**Comment by chrislovecnm** [comment]
@keglevich3 you specifying the ami version?

**Comment by keglevich3** [comment]
Yes I executed this command:

kops create cluster --cloud=aws --kubernetes-version=1.4.5 --zones=eu-central-1a,eu-central-1b --master-zones=eu-central-1a \
--node-size=m4.large --node-count=4 --master-size=m4.large --vpc=vpc-111111d --network-cidr=172.22.0.0/16 --image=ami-8504fdea \
--name=some.domain

**Comment by justinsb** [comment]
I think this is fixed with kops 1.5.0 beta1 and above, even without #1122 - I haven't been able to reproduce it.  Closing, but please reopen or comment if you hit it again.
