### ISSUE TITLE
Add etcd 3.4.3 to etcd manager for kubernetes 1.17

### ISSUE THREAD

**Issue by mmerrill3** [kubernetes/kops#8310]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
The upstream k8s project, for k8s 1.17, is using [etcd version 3.4.3](https://github.com/kubernetes/kubernetes/pull/84329) as the default etcd server image

**2. Feel free to provide a design supporting your feature request.**
Add the ability to select etcd version 3.4.3 in etcd-manager, and default to 3.4.3 for fresh installs with k8s 1.17

**Comment by mmerrill3** [comment]
First step is over in etcd-manager: https://github.com/kopeio/etcd-manager/pull/292

**Comment by justinsb** [comment]
Thanks for the contribution to etcd-manager!  I've merged your PR, and we have a new release of etcd-manager that includes it: `3.0.20200116`
