### ISSUE TITLE
Fix version tags, etc., for v1.6

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#833]
c.f. #832 - right now we only have `_k8s_1_5` tags, but we're not generating `_k8s_1_6` (and it might be good just to fall back to the 1.5 tag in that case, like it's doing)

**Comment by justinsb** [comment]
I kinda hope we can get rid of most of these tags, preferring code instead.  We'll see how we do :-)

**Comment by chrislovecnm** [comment]
@justinsb I am closing this as we are in the process of removing all of this stuff ...
