### ISSUE TITLE
Unable to import kops with go modules

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#8335]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

v1.15.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Not applicable

**3. What cloud provider are you using?**

Not applicable

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
GO111MODULES=on go get k8s.io/kops@1.15.0 
```

**5. What happened after the commands executed?**

```
go: finding k8s.io 1.15.0
go: finding k8s.io/kops 1.15.0
go get: k8s.io/kops@v1.4.2-0.20191120011744-9992b4055733 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**6. What did you expect to happen?**

Import kops 1.15.0 into current project

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Not applicable

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Not applicable

**9. Anything else do we need to know?**

Ref kubernetes/kubernetes#81878

**Comment by johngmyers** [comment]
Changing the `replace` directives in the kops `go.mod` to `require` didn't work, as the transitive dependencies would still refer to `v0.0.0`.

What did work is copying all the `replace` directives in the kops `go.mod` (except `k8s.io/kubernetes`) into my importing `go.mod`.

**Comment by johngmyers** [comment]
I don't think there's anything for kops to do here, other than the existing effort to move away from direct k/k dependencies.

**Comment by andrewstuart** [comment]
FWIW you can get around this by copying the huge replace block in kops' go.mod into your own.

e.g.

https://github.com/kubernetes/kops/blob/04d36d7d92c72601efd918877fc180c846129ffb/go.mod#L7-L49
