### ISSUE TITLE
Cleanup cloudup _master_* tags

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#835]
After the new topology feature is implemented into kops - as a clean up effort I would like to port the `_master_*` YAML implementation into the `topologies` directory. 

I would also like this feature to be complete with a full YAML clean up / documentation 
As well as unit tests for the masters (if not already in the topology PR)

#694

**Comment by kris-nova** [comment]
This might go away with #744

**Comment by chrislovecnm** [comment]
We have PR inbound thay may help with this ... I am looking through issues to test against #1183 

Does this help?

**Comment by chrislovecnm** [comment]
@kris-nova was enough done in #1183?

**Comment by kris-nova** [comment]
Oh yes - this is long gone
