### ISSUE TITLE
stretch image does not join the cluster

### ISSUE THREAD

**Issue by lironrisk** [kubernetes/kops#8382]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

kubectl version

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I created a new instance group that uses the ami:
kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2019-09-26

kops update cluster
kops validate cluster

**5. What happened after the commands executed?**

the instance group has been created, but the node did not join the cluster.

**6. What did you expect to happen?**

the node to join the cluster.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-12-24T14:42:00Z
  name: XXX
spec:
  DisableSubnetTags: true
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["s3:Get*"],
          "Resource": ["arn:aws:s3:::XXX/common/authorized_keys/default/*"]
        },
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": ["*"]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["s3:Get*"],
          "Resource": ["arn:aws:s3:::XXX/common/authorized_keys/default/*"]
        }
      ]
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: XXX
  dnsZone: XXX
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
    version: 3.3.10
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
    version: 3.3.10
  fileAssets:
  XXX
  hooks:
  XXX
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit.yaml
    oidcClientID: XXX
    oidcGroupsClaim: groups
    oidcGroupsPrefix: 'okta:'
    oidcIssuerURL: XXX
    oidcUsernameClaim: preferred_username
    oidcUsernamePrefix: 'okta:'
    runtimeConfig:
      admissionregistration.k8s.io/v1alpha1: "true"
  kubeControllerManager:
    horizontalPodAutoscalerDownscaleDelay: 5m0s
    horizontalPodAutoscalerSyncPeriod: 15s
    horizontalPodAutoscalerUpscaleDelay: 3m0s
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cloudProvider: aws
    imageGCHighThresholdPercent: 80
    imageGCLowThresholdPercent: 65
    kubeReserved:
      cpu: 500m
      ephemeral-storage: 1Gi
      memory: 2Gi
    kubeReservedCgroup: /kube-reserved.slice
    systemReserved:
      cpu: 300m
      ephemeral-storage: 1Gi
      memory: 1Gi
    systemReservedCgroup: /system.slice
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.10
  masterInternalName: XXX
  masterPublicName: XXX
  networkCIDR: XXX
  networkID: XXX
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: XXX
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: XXX
  subnets:
  XXX
  
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

when running kops validate cluster, The following error appears:

machine X has not yet joined cluster

**9. Anything else do we need to know?**

if I'm using debian jessie image it works

vim daemon.log on the machine shows:
nodeup[2890] W0120 2890 executor.go:130] error running task "Package/nfs-common" (2m36s remaining to succeed): error installing package "nfs-common": exit status 100: Reading package lists...

nodeup[2890] W0120 2890 executor.go:130] error running task "Package/etables" (2m36s remaining to succeed): error installing package "etables": exit status 100: Reading package lists...

Thanks!

**Comment by olemarkus** [comment]
The error says that it failed installng etables? I don't recall any such issue, but shouldn't that have been ebtables?

I would perhaps try a newer kops version if this bug is to be resolved. Another kops 1.11 version is very unlikely to happen should this be caused by a bug.

**Comment by lironrisk** [comment]
@olemarkus thank you for your answer. Indeed installing etables & conntrack on the machine by myself with --allow-unauthenticated flag made the node join the cluster. But I still do not understand why it happens and what kops version should resolve this, as I don't see any mention about it on the documentation not the change log.

**Comment by olemarkus** [comment]
You may have a typo in that package name there. It should be ebtables, not etables (note the missing b). Not sure if that install command prevents the node process from starting though. ebtables is anyways already installed on the AMIs so no need to install it by hand again.

You can have a look at `journalctl -u kubelet` for clues why the kubelet is not joining

**Comment by lironrisk** [comment]
I fixed my typo, thanks. Kubelet does not even exists if ebtables is not installed, and the fact it is not installed when the instance is running is exactly the issue. But I still do not understand what makes it have installation issues.

**Comment by olemarkus** [comment]
ebtables is installed by kops nodeup. kubelet is downloaded and started by the same component. I would look at the logs for why that is not starting properly.

**Comment by lironrisk** [comment]
there are no logs except it fails to install it because there was no --allow-unauthenticated flag

**Comment by olemarkus** [comment]
The `--allow-unauthenticated` definitely exists on the apt-get bin available in the image. Cannot really say why this fails for you. I know that image works with kops 1.15 that we are using

**Comment by Nyefan** [comment]
This also happens intermittently for us:

`kops version`
`1.14.1`

`kubernetes version`
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}```

`cloud provider`
AWS

`ami`
`kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17`


I'm curious what you mean by:

"The `--allow-unauthenticated` definitely exists on the apt-get bin available in the image."

Does this mean I should be able to install the failing packages, `ebconfig` and `conntrack`, by sshing into the instance and running `apt update && apt install -y ebconfig conntrack` without manually including the `--allow-unauthenticated` flag?  Because if that is the case, then new instances we bring up in `ap-south-1` do not have this property.  Once I install those two packages using `apt ... --allow-unauthenticated`, the node does join the cluster.  

One probably unrelated note - attempting to `apt install strace` on the affected nodes results in a 502 error:

```
Err:1 http://cloudfront.debian.net/debian stretch/main amd64 strace amd64 4.15-2
  502  Bad Gateway [IP: 13.227.141.67 80]
E: Failed to fetch http://cloudfront.debian.net/debian/pool/main/s/strace/strace_4.15-2_amd64.deb  502  Bad Gateway [IP: 13.227.141.67 80]
```

The only reason I bring this up is because I always get a 502 from the affected nodes for this particular package, but I cannot replicate this on any other nodes in any other region.

**Comment by olemarkus** [comment]
@Nyefan this sounds more like an issue with a particular debian mirror. I don't think kops can do that much here.
Make sure you are using the latest images though.

**Comment by krish512** [comment]
Manually changing the distributions from cloudfront to deb.debian works

`cloudfront.debian.net/debian` changed to `deb.debian.org/debian`

Can this be done using kops config? Currently we have to manually do this on every node

**Comment by olemarkus** [comment]
Probably not directly, as far as I know. But you can use a hook for that: https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#hooks

**Comment by marcindulak** [comment]
A similar problem on an old k8s v1.10.6, it uses AMI `k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17 (ami-09b955ecb52ae9bcf)`

```
apt-get update | grep E
E: Release file for http://cloudfront.debian.net/debian/dists/jessie-backports/InRelease is expired (invalid since 421d 13h 3min 11s). Updates for this repository will not be applied.
cat /etc/*release | grep VERSION=
VERSION="8 (jessie)
```

A manual fix https://unix.stackexchange.com/questions/2544/how-to-work-around-release-file-expired-problem-on-a-local-mirror helps

```
apt-get -o Acquire::Check-Valid-Until=false update
```

**Comment by marcindulak** [comment]
Shouldn't ebtables be part of the image? https://github.com/kubernetes/kops/issues/1711

**Comment by marcindulak** [comment]
> Shouldn't ebtables be part of the image? #1711

@olemarkus

**Comment by olemarkus** [comment]
I don't think it is part of the image. It is installed by kops on boot.

**Comment by marcindulak** [comment]
According to https://github.com/kubernetes/kops/issues/1711#issuecomment-276841603 ebtables should be part of the image.

@justinsb  writes there ```We'll get it into the next image also, to skip the need to download it```

**Comment by marcindulak** [comment]
Is using hooks even feasible in order to modify apt repositories before nodeup is run https://github.com/kubernetes/kops/issues/387? @olemarkus

**Comment by marcindulak** [comment]
Actually as per comment in the above issue, `additionalUserData` may help

```
spec:
  additionalUserData:
  - name: apt-sources-backports-remove.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      /bin/rm -f /etc/apt/sources.list.d/backports.list
      /usr/bin/apt-get update
```

**Comment by weisjohn** [comment]
@marcindulak in my experience, the cloud-init scripts configured through `additionalUserData` run _after_ nodeup

**Comment by marcindulak** [comment]
https://github.com/kubernetes/kops/issues/9441
