### ISSUE TITLE
OpenStack: Octavia loadbalancer requires ".AllowedCIDRs" instead of Security Group

### ISSUE THREAD

**Issue by kciredor** [kubernetes/kops#8383]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Kops 1.15 - 1.17 alpha

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Default included Kubernetes versions

**3. What cloud provider are you using?**

OpenStack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create cluster --os-octavia=true, kops update cluster --yes

**5. What happened after the commands executed?**

Cluster becomes healthy. Whatever I add/remove from the API (loadbalancer masters) group it does not matter: everything go's through.

**6. What did you expect to happen?**

Security Group Rules should be honored.

**9. Anything else do we need to know?**

I rolled out multiple kops versions on multiple OpenStack providers, each resulting in the same wrong behaviour (no security on API LB).

**Comment by kciredor** [comment]
Update: it appears the non-existing ID does exist, my provider was willing to look into the mysql database.

It belongs to the actual loadbalancer in their 'internals project'. Like many OpenStack providers they have a way to make everything HA, for loadbalancers: 2 vm's + vrrp doing the real work. The loadbalancer I can see in my project is a placeholder.

None of this should matter, but interestingly kops sees the actual/hidden loadbalancer setup from the other project and it's security group id instead of the placeholder from my project which is the only one it should see using e.g. openstack loadbalancer list and openstack security group list.

Not sure how to proceed here. Could it be gophercloud having not enough filters? Anyone?

**Comment by kciredor** [comment]
Tried on another provider to ensure it's not provider specific: exact same issue occurs, a mismatch between the LB and SG where the LB is hooked up to a SG from another project that makes the LB highly available, instead of the actual SG in LB's own project.

**Comment by kciredor** [comment]
Looks like the right way to do whitelisting with Octavia, starting with OpenStack Train release, is this:

https://github.com/kubernetes/cloud-provider-openstack/pull/837/files

(ACL CIDR's)

**Comment by kciredor** [comment]
This has to be fixed in kube-controller-manager, or better: use the (already fixed) external cloud controller manager.

**Comment by zetaab** [comment]
I do not have currently environment where I could fix this, still running older versions of OpenStack

**Comment by kciredor** [comment]
Hi @zetaab, thanks, I understand. How about I give you access to my OpenStack project? We could use for example keybase to share openrc.sh.

**Comment by zetaab** [comment]
I am currently installing devstack, lets see can I code with that. At least I did initial octavia code with that
