### ISSUE TITLE
Upgrading public to private topology

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#839]
According to some excellent feedback from @MrTrustor on https://github.com/kubernetes/kops/pull/694#issuecomment-258684636

We will need to tighten up our support for the upgrade path from public to private topologies. 

This is probably a high visibility and highly used feature that will need to be expedited.

**Comment by chrislovecnm** [comment]
So the elephant in the room is can we migrate from public to private networking. I would say initially that we do not support it, and we scope if and how it will work. The premise that I have it built on we don't want down time, if we can help it.

Not saying that it cannot be done, I am saying that we want to do it well.

**Comment by kris-nova** [comment]
Wondering if this is still a priority for

**Comment by ese** [comment]
@kris-nova Is it intended don't support this kind of upgrade?

**Comment by justinsb** [comment]
It looks like we closed this simply because we weren't going to do it in v1.  I'm reopening and marking it for consideration in 1.5.1

**Comment by chrislovecnm** [comment]
@justinsb is this supported now?

**Comment by olvesh** [comment]
I did a little writeup of my progress here: 
https://gist.github.com/olvesh/c63b3490a885b4f2054847abe9c41bd2

Not without downtime though, and I have a few snags left still that I am unsure if is a consequence of the switch. But if it helps in some way please us it for what you want.

**Comment by mateuszkwiatkowski** [comment]
I can confirm that @olvesh's solution works. The only difference in my setup is that I use calico instead of weave networking.

**Comment by chrislovecnm** [comment]
Can someone write this up?

**Comment by chrislovecnm** [comment]
Aka drop this into documentation?

**Comment by olvesh** [comment]
I guess it needs to be reformatted somewhat to fit the documentation format? Or would a copy-paste with small adjustments be enough?

Don't know if I will have the time to do a writeup in the near future but I can try to make something of it. Where would it be best to put it?

**Comment by chrislovecnm** [comment]
@olvesh let's iterate, best to get it in, and then make it pretty.
