### ISSUE TITLE
Logging into any master should allow you to use 'etcdctl' without so many mandatory switches

### ISSUE THREAD

**Issue by jmcdonagh** [kubernetes/kops#8400]
Etcd is pretty solid for me so I am not dealing with it directly too often. I suspect that for a lot of people, this is also true. So when I went to simply access it today to troubleshoot an apparent outage, I wasted an embarrassing amount of time straightening out how to access it.

I figured out pretty quickly that one specific node had some bad data from just looking at system logs. So, in theory I should just be able to remove the bad node from the cluster, and that's it... but I have to remember a bunch of things to even use etcdctl:

which port out of the handful defined is it that I connect to?
what is the hostname convention?
what is the list of endpoints?
what is the name of that switch i need to set the api to 3?

After I waste time deducing that stuff, googling etc, I try to go into the etcd-manager pod to run these commands because etcdctl is not installed on the underlying node, but it is in the pod. However, inside the pod, the PKI files in /etc/kubernetes/pki are different than the underlying host. So I wasted tons of time trying to troubleshoot various certificate errors, until I decided to go back to the host. 

At that point I locate the container's FS so I can execute etcdctl on the host, then pass in the proper combo of x509 switches and endpoint and I'm able to fix the issue with one 'remove' command.

I probably made some bonehead mistakes along the way, but the docs are light on this and it is confusing as hell that you need to do this from the underlying host even though etcdctl is only installed in the etcd manager pods. Also, in the heat of an outage, dealing with administrative access issues is infuriating. You've still got an actual problem to fix after!

**2. Feel free to provide a design supporting your feature request.**

The version of etcd running on your cluster should be available to masters in /opt like it is for the etcd manager containers. etcdctl takes in several environment variables, which could be added to the system wide shell profile, thus completely solving the issue of what switches to pass. I could just add this custom to my boxes, and I probably will... but I really feel like this would be a really nice thing to have built in to kops.

**Comment by brunomassaini** [comment]
would you mind elaborating the steps you did?
that would be a first step since we can have it documented already

**Comment by jmcdonagh** [comment]
> would you mind elaborating the steps you did?
> that would be a first step since we can have it documented already

Hi Bruno, thanks for the response... I honestly don't even have the history access to that box anymore. My time is extremely tight these days but I will be at some point trying to put together a little script or bash function helper for this RSN and I will get back to you

**Comment by sdarwin** [comment]
After also hitting the issue, I wrote some instructions... (see pull request above).

**Comment by jmcdonagh** [comment]
I see the instructions were merged above, thanks a lot!!
