### ISSUE TITLE
Deploy k8s on aws spot instances

### ISSUE THREAD

**Issue by georgio-sd** [kubernetes/kops#8401]
I am wondering if it's possible to deploy k8s with kops fully on aws spot instances? I mean master and worker nodes.  Has anybody done that? Did it work?

**Comment by argoyle** [comment]
I do and it works without any problems at all. Love kops and the rolling updates. ❤️

**Comment by georgio-sd** [comment]
Cool, thanks for the answer. Could you tell me how HA works in this case? For example, amazon had notified you that in 2 minutes it would terminate one of your master node spot instances and then terminated it. How does it work from cluster perspective? What does cluster do to handle the situation? Could you go into details and explain it?

**Comment by argoyle** [comment]
Usually it just terminates the instance and then the ASG spins up a new one. Hopefully there is a new one available. 😄

**Comment by georgio-sd** [comment]
Ok, I just need to try it to understand :)
