### ISSUE TITLE
kops wants to delete keypair it does not own based on prefix

### ISSUE THREAD

**Issue by kzap** [kubernetes/kops#8403]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.11.1 all the way up to 1.17.0.alpha.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.15.7

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops delete cluster --name "cluster.mydomain.com"

**5. What happened after the commands executed?**
It wanted to delete the keypair of another cluster named `cluster.mydomain.com-002.k8s.local`
```sh
keypair			kubernetes.cluster.mydomain.com-002.k8s.local-1f:a5:25:54:71:e4:a2:9f:5b:7f:82:65:24:2c:76:3d
keypair			kubernetes.cluster.mydomain.com-ce:02:c6:90:96:b3:2f:de:03:90:9b:56:cc:de:16:54
```

**6. What did you expect to happen?**
For it to only delete `keypair			kubernetes.cluster.mydomain.com`

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
kops flags keypairs which start with `kubernetes.clusterName-` meaning if you have 2 clusters with similar names, you will get affected.
The method could atleast check for the last `-` assuming a AWS keypair follows the convention of `NAME-fingerprint`. Things like this should really be stored in state.
https://github.com/kubernetes/kops/blob/c323819e6480d71bad8d21184516e3162eaeca8f/pkg/resources/aws/aws.go#L715-L717

**Comment by rifelpet** [comment]
/remove-lifecycle rotten
AWS Keypairs now support tagging so Kops could probably rely on tags rather than name prefixes. The change would likely be minimal, mostly in [this area of code](https://github.com/kubernetes/kops/blob/00b3951069bcdf35fad97474d6c32b2b17cd702b/upup/pkg/fi/cloudup/awstasks/sshkey.go#L56)
