### ISSUE TITLE
 x509: certificate is valid for 100.64.0.1, 127.0.0.1, not 172.20.86.175

### ISSUE THREAD

**Issue by prageethw** [kubernetes/kops#8409]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.15.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"clean", BuildDate:"2019-08-05T09:14:29Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Occurs when Prometheus scrape K8s API with  insecure_skip_verify=false
**5. What happened after the commands executed?**
Prometheus can't get api server scrapes.
**6. What did you expect to happen?**
Prometheus should be able to get these stats
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: test.co.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  authentication:
    aws: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://test.co.k8s.local-1580027149/test.co.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: v1.13.9
  masterPublicName: api.test.co.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-2a
    type: Public
    zone: us-east-2a
  - cidr: 172.20.64.0/19
    name: us-east-2b
    type: Public
    zone: us-east-2b
  - cidr: 172.20.96.0/19
    name: us-east-2c
    type: Public
    zone: us-east-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: test.co.k8s.local
  name: master-us-east-2a
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2a
  role: Master
  subnets:
  - us-east-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: test.co.k8s.local
  name: master-us-east-2b
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2b
  role: Master
  subnets:
  - us-east-2b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: test.co.k8s.local
  name: master-us-east-2c
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2c
  role: Master
  subnets:
  - us-east-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: test.co.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t3.medium
  maxSize: 10
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/test.co.k8s.local: "true"
    kubernetes.io/cluster/test.co.k8s.local: "true"
  subnets:
  - us-east-2a
  - us-east-2b
  - us-east-2c

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by prageethw** [comment]
btw my nodes get ip 172 range as below

ip-172-20-125-121.us-east-2.compute.internal   Ready    master   106m   v1.13.9
ip-172-20-41-84.us-east-2.compute.internal     Ready    node     114m   v1.13.9
ip-172-20-45-70.us-east-2.compute.internal     Ready    master   106m   v1.13.9
ip-172-20-86-175.us-east-2.compute.internal    Ready    master   105m   v1.13.9
ip-172-20-89-183.us-east-2.compute.internal    Ready    node     114m   v1.13.9

**Comment by prageethw** [comment]
adding server name as Kubernetes solved this issue in Prometheus config. closing therefore

```
    # scrape config for API servers
    - job_name: 'kubernetes-apiservers'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - default
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        **server_name: kubernetes**
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: kubernetes;https
```

**Comment by sharoncr1** [comment]
@prageethw Thanks.. That worked like charm. Btw, Can you explain a bit on the solution?
