### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by aojea** [kubernetes/kops#8432]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

With the graduation from IPv6 to beta in Kubernetes https://github.com/kubernetes/enhancements/issues/508#issuecomment-574126795
the project has a CI that tests conformance and e2e in a synthetic environment with KIND.

This guarantees a minimum of quality and reduces the risk of regression, however, it needs more user validation. In order to achieve this is important that the lifecycle projects support it allowing users to deploy IPv6 Kubernetes clusters.

**2. Feel free to provide a design supporting your feature request.**

As of today, only 2 cloud providers support IPv6, since AWS is the more mature one and Azure is working on supporting IPv6 with its cluster management tool it's reasonable to implement IPv6 first in AWS and iterate over it.

I have done a sketch of an API implementation for AWS for the cluster-API project
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1370

The setup of the infrastructure, VMs, VPCs, ... is working, the missing part is the configuration of the Kubernetes components.

In order to configure IPv6 in Kubernetes you just have to configure the components with IPv6 addresses, which is not an opt-in feature.

**Comment by johngmyers** [comment]
It would be helpful to distinguish between dual stack versus v6-only. I presume you mean the former, as AWS doesn't support the latter.

**Comment by aojea** [comment]
Right, sorry, this is a bit confusing.

Let me give some context, dual-stack is still alpha in k8s, but IPv6 has improved a lot and the goal is to graduate it to beta with 1.18. In order to move Ipv6 to GA it needs more user validation, and the best way is making it accessible to users, hence this request.

If the infra where the cluster is running is dual-stack, like in AWS,  the cluster can be IPv4 only, IPv6 only or dual-stack, it will just use the IP family he has configured. I mean, IPv6 only can run over a dual-stack infrastructure, but no the other way around.

**Comment by olemarkus** [comment]
Would be interesting to support ipv6 with kops, but provisioning VPC/subnet with ipv6 is somewhat painful to do with the way kops works.

**Comment by fvasco** [comment]
A first step might be to support IPv6 on already IPv6 configured subnet (my case).

**Comment by hakman** [comment]
This seems to be a recurring request and may be worth some attention.
@olemarkus @rifelpet I thing you did some thinking on this topic, maybe you can share your thoughts.
/reopen
/remove-lifecycle rotten
/lifecycle frozen

**Comment by olemarkus** [comment]
Adding support for ipv6 for pre-provisioned subnets is a good start. I have not looked much into exactly how that works and the docs were somewhat lacking in this area.

**Comment by Deepak1100** [comment]
we also needed ipv6 support for external load balancer on AWS. as its requirement for many compliances. 
we used kops managed AWS VPC so we cannot just enable ipv6 on AWS vpc else kops terraform code will block.

that said, I will try to add it in kops for AWS, terraform this week.
but terraform AWS only support `assign_generated_ipv6_cidr_block` so we will not know the ipv6 series in advance but we can create a subnet based on auto_assigned_ipv6 as it is always /56 and subnet has to be always /64.

**Comment by aojea** [comment]
dual stack is beta in 1.22, maybe is a better intermediate step.
I have deployed it with kubeadm and cloudformation, https://github.com/aojea/k8s-aws-ipv6#creating-the-cluster-with-kubeadm just  FYI, I don't know if that can help

**Comment by hakman** [comment]
Nice. Thanks for the tip @aojea.

**Comment by hakman** [comment]
Initial support for configuring IPv6 with AWS was merged today in https://github.com/kubernetes/kops/pull/11442. More PRs will follow to address remaining issues.

At the moment, the IPv6 feature configures the following AWS components:
* VPC:
  * always requests the IPv6 CIDR from AWS
  * cannot be disabled
* Routes:
  * always creates the default IPv6 route (for public topologies)
* Security Group:
  * always allows IPv6 egress
  * adds / removes entries based on `spec.kubernetesApiAccess` and `spec.sshAccess`
* Subnets:
  * users can assign / remove an IPV6 CIDR (but cannot change it)
* Launch Templates:
  * IPv6 addresses are assigned to instances based on subnet setting, which allows marking instances as needing update

TODO:
- [ ] docs, docs, docs, ... 😄 
- [ ] allow configuring Kubernetes IPv4/IPv6 dual-stack:
  * https://kubernetes.io/docs/concepts/services-networking/dual-stack
- [ ] set subnet CIDR based on VPC CIDR on cluster creation:
  * https://www.terraform.io/docs/language/functions/cidrsubnet.html
  * https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-cidr.html
- [ ] allow setting API NLB to dual-stack
- [ ] create Egress-only Internet Gateway for private topologies

**Comment by johngmyers** [comment]
I recommend declaring dual-stack as out of scope. If we do it at all it should be a separate ticket.

The entire point of IPv6 is to not assign IPv4 addresses to things. We should be targeting a topology where the private and cluster networks are IPv6-only and dual-stack, if it exists at all, is only at the node level in the utility subnets, for cluster ingress and egress.

I would suggest as a work item:

[ ] Cluster-level setting for IPv6-only cluster network.

**Comment by aojea** [comment]
> I recommend declaring dual-stack as out of scope. If we do it at all it should be a separate ticket.

totally agree

**Comment by olemarkus** [comment]
Specifically, it is ipv6-only with masq. At least on AWS, which only allows for single-IP ENI IPs, doing globally routable IPv6 is not feasible.

**Comment by hakman** [comment]
I also agree. This is why I didn't add any extra options or tried to modify validation to allow "," separated dual-stack addresses.

**Comment by johngmyers** [comment]
@olemarkus assuming one runs the CNI in ENI mode, why would single-IP ENI IPs make globally routable IPv6 not feasible?

**Comment by olemarkus** [comment]
As far as I know none of the CNIs that supports ENIs support those with ipv6 addresses.

**Comment by johngmyers** [comment]
Well, we've already generated a PR to cloud-provider-aws. It's likely we'd generate issues or PRs for CNIs.

There is significant value in doing non-masq and we should keep that in scope.

**Comment by johngmyers** [comment]
For comparison, the AWS public containers roadmap claims as of last October to be working on IPv6-only pods with nodes getting /80 blocks.

The AWS VPC CNI has slow-moving, draft PRs adding dual-stack.

Cilium 1.10 added some dual-stack support to some existing IPv6 support. It isn't clear what relevance, if any, that has to their ENI mode.

**Comment by johngmyers** [comment]
It seems to me that masq or not is a function of the CNI. Neither should be out of scope.

I do think that IPv6-only clusters in managed VPCs should default the ClusterCIDR to a chunk allocated out of the VPC's IPv6 allocation.

**Comment by olemarkus** [comment]
I think the way to go is that NodeController in CCM should both provision ENI with address blocks _and_ assign kubelet that block. IIRC there is this "IPAMFromCloud" mode that CCM can run in. That way CNIs doesn't have to do anything special. Just rely on the Kubernetes IPAM for Pods.

**Comment by johngmyers** [comment]
[ ] Terraform support for cidrsubnet()

**Comment by johngmyers** [comment]
Status:

Basic cluster network is working with Calico and Cilium in vxlan mode. Unfortunately, no CNIs currently support IPv6 egress without NAT. Waiting for kubernetes/cloud-provider-aws#230 to be merged and released and for some CNI to support it. We hope for AWS to support attaching a whole IPv6 CIDR ENI.

Per Office Hours discussion, not defaulting the `PodCIDR` at this time. This is effectively blocked until we can egress IPv6 without NAT.

In order to get in-cluster DNS working, we want to run coredns on host network with a high port. That would allow it to take requests on IPv6 and forward them to upstream resolvers on IPv4.

**Comment by hakman** [comment]
Periodic e2e test is available now using Calico CNI: https://testgrid.k8s.io/kops-misc#kops-grid-scenario-ipv6

Most issues should be fixed when AWS CCM will support IPv6:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-scenario-ipv6/1406486530179993600
```
Summarizing 10 Failures:
[Fail] [sig-auth] ServiceAccounts [It] ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance] 
[Fail] [sig-network] Services [It] should have session affinity timeout work for NodePort service [LinuxOnly] [Conformance] 
[Panic!] [sig-network] Conntrack [BeforeEach] should be able to preserve UDP traffic when server pod cycles for a NodePort service 
[Panic!] [sig-network] KubeProxy [It] should set TCP CLOSE_WAIT timeout [Privileged] 
[Panic!] [sig-network] Conntrack [BeforeEach] should be able to preserve UDP traffic when server pod cycles for a ClusterIP service 
[Fail] [sig-network] Services [It] should have session affinity work for NodePort service [LinuxOnly] [Conformance] 
[Fail] [sig-network] HostPort [It] validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance] 
[Panic!] [sig-network] Conntrack [BeforeEach] should drop INVALID conntrack entries 
[Fail] [sig-network] Services [It] should be able to switch session affinity for NodePort service [LinuxOnly] [Conformance] 
[Fail] [sig-apps] Deployment [It] should not disrupt a cloud load-balancer's connectivity during rollout 
Ran 754 of 5771 Specs in 1360.818 seconds
FAIL! -- 744 Passed | 10 Failed | 0 Pending | 5017 Skipped
```

**Comment by aojea** [comment]
> Most issues should be fixed when AWS CCM will support IPv6 and will provide k8s with the IPv6 addresses for the node:

are those the cause of the panics on the tests?

```
Panic: runtime error: index out of range [0] with length 0
```

It seems the test fail to find the NodeIPs
```go
		ips = e2enode.GetAddressesByTypeAndFamily(&nodes.Items[1], v1.NodeInternalIP, family)

		serverNodeInfo = nodeInfo{
			name:   nodes.Items[1].Name,
			nodeIP: ips[0],
		}
```

**Comment by hakman** [comment]
@aojea Yes, those are the causes or panics in tests, because tests look for internal IPs with IPv6 family, which are not yet returned by CCM and `ips[0]` does not exist. Not sure if panic is the way to go here though.
There is still the Q if something has to be done about `--node-ip=::` on kubelet side, that we discussed about some weeks ago, but would like to see first how things change once CCM is released with IPv6 support.

**Comment by hakman** [comment]
@aojea I went ahead and built CCM with my fix and can see that things look better. Just 4 tests are failing conformance, of which only we can ignore the OIDC one for now.
```
Summarizing 4 Failures:
[Fail] [sig-auth] ServiceAccounts [It] ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance] 
[Fail] [sig-network] Services [It] should have session affinity timeout work for NodePort service [LinuxOnly] [Conformance] 
[Fail] [sig-network] Services [It] should have session affinity work for NodePort service [LinuxOnly] [Conformance] 
[Fail] [sig-network] Services [It] should be able to switch session affinity for NodePort service [LinuxOnly] [Conformance] 
Ran 329 of 6404 Specs in 532.093 seconds
FAIL! -- 325 Passed | 4 Failed | 0 Pending | 6075 Skipped
```

All other failing tests are related to session affinity for NodePort services.
To me, it seems that the tests try to connect to the IPv4 address of the node which would obviously fail, as the service has only IPv6 endpoints. I would guess  related to the fact that node addresses are collected without checking for IP family and seems very similar to https://github.com/kubernetes/kubernetes/pull/96122.
https://github.com/kubernetes/kubernetes/blob/413ac5db56c0b9171155566d3d034370b89ff2c7/test/e2e/network/service.go#L2576

Any thoughts?

**Comment by aojea** [comment]
The session affinity test should be fixed with https://github.com/kubernetes/kubernetes/pull/103180/commits

The ServiceAccountIssuerDiscovery has some expectactions in hostnames and IPs that Jordan explains here 
https://github.com/kubernetes/kubernetes/pull/100569#discussion_r601845856

**Comment by hakman** [comment]
Cool, thanks @aojea!
😄

**Comment by hakman** [comment]
Good news, kOps is passing Conformance tests now! 🎉 
Bad new, cluster can only be started intermittently because of [timeouts while downloading](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/11874/pull-kops-e2e-ipv6-conformance/1409114193918955520/artifacts/ip-172-20-36-219.eu-west-2.compute.internal/kops-configuration.log) the binaries.

@aojea Are you aware of some tweaks or general issues with IPv6 on AWS that could cause the above timeouts? Any thoughts on how to debug it?

**Comment by olemarkus** [comment]
It is seems specific to golang net. I believe we don't see this when using curl/wget.

**Comment by aojea** [comment]
> @aojea Are you aware of some tweaks or general issues with IPv6 on AWS that could cause the above timeouts? Any thoughts on how to debug it?

> It is seems specific to golang net. I believe we don't see this when using curl/wget.

can you link me to the code that performs those downloads?

**Comment by hakman** [comment]
> can you link me to the code that performs those downloads?

Sure, this is the download function:
https://github.com/kubernetes/kops/blob/97869057129b30ea284c3ed1bdf1db36e752701d/upup/pkg/fi/http.go#L66

**Comment by aojea** [comment]
> > can you link me to the code that performs those downloads?
> 
> Sure, this is the download function:
> https://github.com/kubernetes/kops/blob/97869057129b30ea284c3ed1bdf1db36e752701d/upup/pkg/fi/http.go#L66

This stops the download after 2 minutes, doesn't take into account if it is in progress

https://github.com/kubernetes/kops/blob/97869057129b30ea284c3ed1bdf1db36e752701d/upup/pkg/fi/http.go#L80-L83

I think that this will make it
https://github.com/kubernetes/kops/pull/11884
http timeouts are hard to get correct, it will be better to test this problem before merging with my PR

**Comment by johngmyers** [comment]
Not performing the following tasks:

* allow configuring Kubernetes IPv4/IPv6 dual-stack: 
** Ruled as out of scope
* CloudFormation support for cidrsubnet()
** What's this "CloudFormation" you speak of? :-)

**Comment by aojea** [comment]
Thanks folks , it was a long run but we made it 👏

**Comment by hakman** [comment]
> Thanks folks , it was a long run but we made it 👏

I bet that now you'll open an issue that it doesn't work on GCE 🤣
