### ISSUE TITLE
OpenStack external Cloud Controller Manager - How does it work?

### ISSUE THREAD

**Issue by kciredor** [kubernetes/kops#8434]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.15

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.15 defaults to Kubernetes 1.15

**3. What cloud provider are you using?**

OpenStack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

1. kops create cluster
2. kops edit cluster according to https://github.com/kubernetes/kops/blob/master/docs/getting_started/openstack.md#using-external-cloud-controller-manager
3. kops update cluster --yes

**5. What happened after the commands executed?**

Nodes do not get out of NotReady state.

**6. What did you expect to happen?**

A new cluster becoming Healthy.

**9. Anything else do we need to know?**

After all master/worker nodes sticking with NotReady taints, I've tried the following:

1. kubectl apply -f cloud-controller-manager-roles.yaml
2. cloud-controller-manager-role-bindings.yaml
3. openstack-cloud-controller-manager-ds.yaml (this file needs an edit for the CCM to accept the NotReady taint on master nodes)

The pods belonging to the DaemonSet become healthy. Waiting for half an hour, nothing changed, the nodes are still NotReady.

Alternatively instead of spec.cloudControllerManager: {} I have also tried spec.cloudControllerManager.image: docker.io/k8scloudprovider/openstack-cloud-controller-manager:latest

In this case kubectl get pods --all-namespaces does not show me any sign of a CCM running and the nodes stick with NotReady as well.

**Comment by kciredor** [comment]
Perhaps @zetaab could you be of assistance here? I think I've seen you committing support for external CCM with OpenStack in Kops :-)

**Comment by zetaab** [comment]
@kciredor 1.15 does not contain PR https://github.com/kubernetes/kops/pull/7773 so you need still use different instructions. Those instructions works starting from any version from 1.16

**Comment by kciredor** [comment]
Thanks! I have now tried:

export KOPS_FEATURE_FLAGS=EnableExternalCloudController

- kops 1.15 (image: coreos) + spec.cloudControllerManager.image: docker.io/k8scloudprovider/openstack-cloud-controller-manager:1.13.1 (and .logLevel: 2)
- kops 1.16 (image: coreos) + spec.cloudControllerManager: {}
- kops 1.17 (image: coreos) + spec.cloudControllerManager: {}

1.15: kubectl get nodes stays empty, kubectl get pods -A only dns-controller/kube-dns/kube-dns-autoscaler (Pending)
1.16/1.17: I can see the openstack-cloud-controller running, but node.cloudprovider.kubernetes.io/uninitialized taint is never removed / deployment is stuck. Also I had to manually apply k8s-1.13.yaml, it was not being applied by Kops for me.

What am I missing here?

(BTW: kops 1.16a and 1.17a currently do not provide healthy openstack clusters, provisioning seems to stall lateron in the deployment without setting external CCM)

**Comment by zetaab** [comment]
difficult to say what is going wrong. Could you check logfiles from masters? If it is not applied there is maybe some error.

**Comment by kciredor** [comment]
With 1.15 kubectl get nodes is returning an empty list. The openstack-cloud-controller daemonset is on a desired state of 0 pods. Deadlock?

Not sure trying 1.16 or 1.17 will help, because both do not become healthy with OpenStack (same config as 1.15, even without ext CCM).

**Comment by kciredor** [comment]
FYI, 1.16 debugging without ext CCM: https://github.com/kubernetes/kops/issues/8469

**Comment by kciredor** [comment]
Working example by @zetaab in https://github.com/kubernetes/kops/issues/8469, closing this one.
