### ISSUE TITLE
cluster unstable after a major version upgrade

### ISSUE THREAD

**Issue by cnw004** [kubernetes/kops#8435]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```Version 1.12.1 (git-e1c317f9c)```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}```
```Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:40:54Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
1. `kops upgrade cluster`
2. `kops upgrade cluster --yes`
3. `kops update cluster`
4. `kops update cluster --yes`
5. `kops rolling-update cluster`
6. `kops rolling-update cluster --yes`

**5. What happened after the commands executed?**
The cluster was successfully upgraded. I went from version 1.11.6 to version 1.12.10. However, the nodes get into a "Not Ready" state every so often. The cluster is completely unstable.

e.g.
NAME                            STATUS     ROLES    AGE     VERSION
ip-10-40-100-100.ec2.internal   Ready      master   16h     v1.12.10
ip-10-40-100-113.ec2.internal   NotReady   node     16h     v1.12.10
ip-10-40-100-84.ec2.internal    Ready      node     4h28m   v1.12.10

**6. What did you expect to happen?**
After the upgrade, I expect the cluster to be stable and the nodes to remain in a Ready state unless acted on by some other force that would cause them to break.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2020-01-28T20:51:08Z
  name: REDACTED
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: REDACTED
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: main
    version: 3.2.24
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.10
  masterPublicName: REDACTED
  networkCIDR: 10.40.0.0/16
  networkID: REDACTED
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.40.100.0/24
    id: REDACTED
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.40.101.0/24
    id: REDACTED
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2020-01-28T20:51:08Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-us-east-1a
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2020-01-28T20:51:08Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: nodes
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
The issue is not with the commands run, this will not be useful.

**9. Anything else do we need to know?**
No.

**Comment by olemarkus** [comment]
Can you roll the cluster with a new version of kops (don't have to change k8s version).
If there is a bug in kops it is unlikely that it will be fixed for a version that far behind.
