### ISSUE TITLE
Handle pending delete better

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#844]
Seen in https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws/881/build-log.txt:

```
W1108 04:36:57.023425     647 executor.go:100] error running task "autoscalingGroup/nodes.e2e-kops-aws.test-aws.k8s.io": error updating AutoscalingGroup: ValidationError: The AutoScaling group may not be modified while it is pending delete
	status code: 400, request id: 09345301-a5b0-11e6-9249-0f2cc0b76154
```

Alternately, don't just fire & forget the deletion of the ASG?

**Comment by chrislovecnm** [comment]
@zmerlynn in order to not get in your way... Can you assign to yourself, and let us know that you are keeping track of your tasks.  Or if you need assistance, please reach out.  I am sure you are already, but wanted to offer the olive branch.

**Comment by zmerlynn** [comment]
@chrislovecnm: Do we have a help-wanted label? I'm filing bugs for what I can see, and I definitely poke at failures, but I could use help.

**Comment by kris-nova** [comment]
@zmerlynn - we do now :)
