### ISSUE TITLE
instancegroup was listed, but then not found "nodes"

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#845]
Seen in https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws/851/build-log.txt and https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws/852/build-log.txt:

```
2016/11/07 19:40:54 e2e.go:722: Running: kops update

instancegroup was listed, but then not found "nodes"
```

**Comment by zmerlynn** [comment]
If I'm understanding this code correctly, it looks like the equivalent of `aws s3 ls s3://$STATE_STORE/$CLUSTER/instancegroup/` found the `nodes` entry, but then a subsequent attempt to fetch `s3://$STATE_STORE/$CLUSTER/instancegroup/nodes` didn't find it. S3 eventual consistency biting us?

**Comment by chrislovecnm** [comment]
@kris-nova any ideas?

@zmerlynn can you reproduce or are we flaky?  I have been waiting to write that sentence for months.  I know I am a flake, but is the test a flake?

**Comment by zmerlynn** [comment]
@chrislovecnm: I saw it twice and then it disappeared.

My best guess is that this was a weird read-after-write inconsistency with S3, and we should probably do the write then poll to verify it landed. But according to [the docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel), all regions should have read-after-write. One thing I don't quite understand in the docs is "The caveat is that if you make a HEAD or GET request to the key name (to find if the object exists) before creating the object, Amazon S3 provides eventual consistency for read-after-write." Is that implying if you probe a key, write, then read, it's not read-after-write consistent?

Anyways, that's my only guess for how this could happen given the code.

**Comment by zmerlynn** [comment]
Here's another variant: (from [kops-aws #1865](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/1865?log#log)):
```
I0104 07:43:24.223] Cluster configuration has been created.
I0104 07:43:24.223] 
I0104 07:43:24.223] Suggestions:
I0104 07:43:24.224]  * list clusters with: kops get cluster
I0104 07:43:24.224]  * edit this cluster with: kops edit cluster e2e-kops-aws.test-aws.k8s.io
I0104 07:43:24.224]  * edit your node instance group: kops edit ig --name=e2e-kops-aws.test-aws.k8s.io nodes
I0104 07:43:24.224]  * edit your master instance group: kops edit ig --name=e2e-kops-aws.test-aws.k8s.io master-us-west-2a
I0104 07:43:24.224] 
I0104 07:43:24.224] Finally configure your cluster with: kops update cluster e2e-kops-aws.test-aws.k8s.io --yes
I0104 07:43:24.225] 
W0104 07:43:24.723] 
W0104 07:43:24.724] cluster "e2e-kops-aws.test-aws.k8s.io" not found
W0104 07:43:24.726] 2017/01/04 07:43:24 e2e.go:948: Step '/workspace/kops update cluster e2e-kops-aws.test-aws.k8s.io --yes' finished in 532.612617ms
```
