### ISSUE TITLE
CNI Improvement: Cilium KV-Store Backed Cluster Support

### ISSUE THREAD

**Issue by daviddyball** [kubernetes/kops#8465]
As of Cilium 1.6 deployments of Cilium default to using the Kubernetes CRD mechanism for storing Cilium primitives, where it previously required it's own etcd or Consul storage engine.

The only option currently configured in the Cilium manifest template is CRD-backed storage. I'd like to propose the ability to support both mechanisms should the end user desire it.

The thinking would be to change the Cilium Networking Spec to include a few options to generate alternate manifests for Kops to deploy the KV-store backed Cilium agents.

Initial discussion was posed in [this ticket](https://github.com/kubernetes/kops/pull/8445)

**Comment by olemarkus** [comment]
The changes necessary to support etcd should be fairly trivial. I wouldn't recommend adding manifests to handle the KV stores by kops though, but rather assume that they exists around the same time as the cluster comes up. If one really wants the benefits of running with KV stores, the etcd cluster should live outside of the cluster.

**Comment by johngmyers** [comment]
We run with an in-cluster KV store. I don't see what the benefits of having that out of cluster would be to outweigh the additional management cost.

**Comment by olemarkus** [comment]
If you use etcd only as kv store for agent state, it is not a problem to have etcd in the cluster. But if you also use it for storing identities you do get a chicken/egg issue with how to provision the kv store without the cni being able to assign ips.

**Comment by johngmyers** [comment]
The KV store runs on host network, so doesn't rely on the CNI that is using it.

**Comment by olemarkus** [comment]
That would work too :)
I guess my point is just that kops shouldn't provision etcd in this case.
Provisioning cilium-etcd-operator could be an idea when etcd is only used for state sync.

**Comment by olemarkus** [comment]
Since kops is supposed to be production ready and such, I can see us managing the setup described here: https://docs.cilium.io/en/v1.6/gettingstarted/k8s-install-etcd-operator/

Could even make that default.

> The identity allocation remains to be CRD-based which means that etcd remains an optional component to improve scalability. Failures in providing etcd will not be critical to the availability of Cilium but will reduce the efficacy of state propagation. This allows the managed etcd to recover while depending on Cilium itself to provide connectivity and security.

Shouldn't be too complex to add either.

For completeness: before fixing the kops support for cilium, we did run 1.5.x with cilium-etcd-operator where etcd was also used for identity allocation. It is not something I would like to do again.

**Comment by daviddyball** [comment]
@olemarkus This was my preferred option as well. Eventually I am going to be configuring a cluster-mesh and need etcd for that use-case. My main goal will be to implement the managed-etcd, but if I can support external etcd as well then I'll throw that in too

**Comment by olemarkus** [comment]
It should be fairly easy. I think you can pretty much copy the relevant part of the cilium template https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/charts/config/templates/configmap.yaml#L7

**Comment by johngmyers** [comment]
That is the mode we'd like to move to, once we get a working 1.6.x cilium-operator that we can upgrade to.

**Comment by olemarkus** [comment]
@daviddyball will you put together a PR?

**Comment by daviddyball** [comment]
Yep, I'm happy to work on this. I can't give any firm ETA though due to unforeseen circumstances

**Comment by olemarkus** [comment]
I can get this done in fairly short amount of time. But I have a couple of cilium PRs already that needs to go in first
