### ISSUE TITLE
OpenStack: Kops 1.16+: CoreOS not healthy anymore, Debian image needs customization

### ISSUE THREAD

**Issue by kciredor** [kubernetes/kops#8469]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.16 beta 1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.16.4

**3. What cloud provider are you using?**

OpenStack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kubectl create cluster / update cluster --yes

**5. What happened after the commands executed?**

After a while deployment is frozen. Pods like dns-controller are waiting for master nodes to get the "node-role.kubernetes.io/master=" label.

**6. What did you expect to happen?**

Master should have this label by now, especially considering they've already been tainted as well with node-role.kubernetes.io/master:NoSchedule.

**9. Anything else do we need to know?**

Manually adding the label to a master node made the pods schedule, the worker nodes join the cluster and everything becoming healthy very fast.

EDIT 2020-02-06: Using CoreOS. Updated the issue title. See below for working Debian example, which does need manual fixes though for the default OpenStack images.

**Comment by zetaab** [comment]
source ~/Downloads/sose-test3-openrc.sh
export OS_DOMAIN_NAME=foobar
export S3_ACCESS_KEY_ID=yyy
export S3_SECRET_ACCESS_KEY=zzzz
export KOPS_STATE_STORE=do://zetaab
export S3_ENDPOINT=https://foobar.com
export KOPS_FEATURE_FLAGS=EnableExternalCloudController

~/go/bin/kops create cluster \
  --cloud openstack \
  --name exttest.k8s.local \
  --state ${KOPS_STATE_STORE} \
  --zones zone-1 \
  --network-cidr 10.1.0.0/16 \
  --image debian-10-161019-devops \
  --master-count=3 \
  --node-count=2 \
  --node-size m1.medium \
  --master-size m1.medium \
  --etcd-storage-type solidfire \
  --topology private \
  --bastion \
  --networking calico \
  --api-loadbalancer-type public \
  --os-kubelet-ignore-az=true \
  --os-ext-net int-net \
  --os-octavia=true

~/go/bin/kops edit cluster exttest.k8s.local

add following to config and save:
```
  cloudControllerManager: {}
```

~/go/bin/kops update cluster exttest.k8s.local --yes

after 6 minutes:

```
kubectl get nodes
NAME                                  STATUS   ROLES    AGE    VERSION
master-zone-1-1-1-exttest-k8s-local   Ready    master   109s   v1.17.0
master-zone-1-2-1-exttest-k8s-local   Ready    master   111s   v1.17.0
master-zone-1-3-1-exttest-k8s-local   Ready    master   108s   v1.17.0
nodes-1-exttest-k8s-local             Ready    node     25s    v1.17.0
nodes-2-exttest-k8s-local             Ready    node     25s    v1.17.0

kubectl get pods --all-namespaces
NAMESPACE     NAME                                                          READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-8b55685cc-qq58b                       1/1     Running   0          116s
kube-system   calico-node-fk7dc                                             1/1     Running   0          115s
kube-system   calico-node-kml22                                             1/1     Running   0          46s
kube-system   calico-node-n66sz                                             1/1     Running   0          115s
kube-system   calico-node-qtvpq                                             1/1     Running   0          46s
kube-system   calico-node-wc95c                                             1/1     Running   0          116s
kube-system   dns-controller-546589d746-z5cns                               1/1     Running   0          116s
kube-system   etcd-manager-events-master-zone-1-1-1-exttest-k8s-local       1/1     Running   0          2m
kube-system   etcd-manager-events-master-zone-1-2-1-exttest-k8s-local       1/1     Running   0          70s
kube-system   etcd-manager-events-master-zone-1-3-1-exttest-k8s-local       1/1     Running   0          58s
kube-system   etcd-manager-main-master-zone-1-1-1-exttest-k8s-local         1/1     Running   0          114s
kube-system   etcd-manager-main-master-zone-1-2-1-exttest-k8s-local         1/1     Running   0          55s
kube-system   etcd-manager-main-master-zone-1-3-1-exttest-k8s-local         1/1     Running   0          55s
kube-system   kops-controller-gsts6                                         1/1     Running   0          100s
kube-system   kops-controller-lbfj4                                         1/1     Running   0          87s
kube-system   kops-controller-sm89w                                         1/1     Running   0          85s
kube-system   kube-apiserver-master-zone-1-1-1-exttest-k8s-local            1/1     Running   3          62s
kube-system   kube-apiserver-master-zone-1-2-1-exttest-k8s-local            1/1     Running   3          51s
kube-system   kube-apiserver-master-zone-1-3-1-exttest-k8s-local            1/1     Running   4          60s
kube-system   kube-controller-manager-master-zone-1-1-1-exttest-k8s-local   1/1     Running   0          111s
kube-system   kube-controller-manager-master-zone-1-2-1-exttest-k8s-local   1/1     Running   0          53s
kube-system   kube-controller-manager-master-zone-1-3-1-exttest-k8s-local   1/1     Running   0          55s
kube-system   kube-dns-autoscaler-66b775459-zpd99                           1/1     Running   0          116s
kube-system   kube-dns-bb55d6458-l6j5m                                      3/3     Running   0          14s
kube-system   kube-dns-bb55d6458-mkh58                                      3/3     Running   0          116s
kube-system   kube-proxy-master-zone-1-1-1-exttest-k8s-local                1/1     Running   0          107s
kube-system   kube-proxy-master-zone-1-2-1-exttest-k8s-local                1/1     Running   0          61s
kube-system   kube-proxy-master-zone-1-3-1-exttest-k8s-local                1/1     Running   0          54s
kube-system   kube-scheduler-master-zone-1-1-1-exttest-k8s-local            1/1     Running   0          111s
kube-system   kube-scheduler-master-zone-1-2-1-exttest-k8s-local            1/1     Running   0          45s
kube-system   kube-scheduler-master-zone-1-3-1-exttest-k8s-local            1/1     Running   0          59s
kube-system   openstack-cloud-provider-5hbb9                                1/1     Running   0          116s
kube-system   openstack-cloud-provider-c62j9                                1/1     Running   0          85s
kube-system   openstack-cloud-provider-qzqnr                                1/1     Running   0          87s
```

**Comment by zetaab** [comment]
I added all commands that I am executing in clean terminal to get new working cluster with external cloudprovider. For me it sounds that your cluster provisioning is not working correctly if taints are not working. Could you please check your hosts file in master? Also please print kubectl get pods --all-namespace

**Comment by kciredor** [comment]
Interesting, you are using a debian image. I've been using CoreOS which was succesful with 1.15.x and not anymore with 1.16.x and up.

Using a debian image my 1.16.x cluster became healthy (have not tried with external CCM yet though). Got my image directly from x

Needed two apply two changes for debian to work:
1. https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#booting-from-a-volume-in-openstack -> default debian image size is 2gb which runs out of diskspace loading protokube into docker
2. swap is enabled by default and kubelet refuses to run, so on all nodes - after kops update cluster --yes - I had to edit /usr/lib/systemd/system/kubelet.service and add --fail-swap-on=false followed by a systemctl daemon-reload

To me this could mean two things:
- You have sourced your debian image from a better place without these issues.
- Debian has been tested with OpenStack + Kops 1.16+, but CoreOS has not been tested.

Am I moving into the right direction here?

**Comment by kciredor** [comment]
core@master-amsterdam1-1-1-dvdev2-k8s-local ~ $ cat /etc/hosts
# /etc/hosts: Local Host Database
#
# This file describes a number of aliases-to-address mappings for the for
# local hosts that share this file.
#
# The format of lines in this file is:
#
# IP_ADDRESS    canonical_hostname      [aliases...]
#
#The fields can be separated by any number of spaces or tabs.
#
# In the presence of the domain name service or NIS, this file may not be
# consulted at all; see /etc/host.conf for the resolution order.
#

# IPv4 and IPv6 localhost aliases
127.0.0.1       localhost
::1             localhost

#
# Imaginary network.
#10.0.0.2               myname
#10.0.0.3               myfriend
#
# According to RFC 1918, you can use the following IP networks for private
# nets which will never be connected to the Internet:
#
#       10.0.0.0        -   10.255.255.255
#       172.16.0.0      -   172.31.255.255
#       192.168.0.0     -   192.168.255.255
#
# In case you want to be able to connect directly to the Internet (i.e. not
# behind a NAT, ADSL router, etc...), you need real official assigned
# numbers.  Do not try to invent your own network numbers but instead get one
# from your network provider (if any) or from your regional registry (ARIN,
# APNIC, LACNIC, RIPE NCC, or AfriNIC.)
#






# Begin host entries managed by kops - do not edit
# End host entries managed by kops

# Begin host entries managed by etcd-manager[etcd] - do not edit
10.2.32.3       etcd-2.internal.dvdev2.k8s.local
10.2.32.6       etcd-3.internal.dvdev2.k8s.local
10.2.32.8       etcd-1.internal.dvdev2.k8s.local
# End host entries managed by etcd-manager[etcd]

# Begin host entries managed by etcd-manager[etcd-events] - do not edit
10.2.32.3       etcd-events-1.internal.dvdev2.k8s.local
10.2.32.6       etcd-events-2.internal.dvdev2.k8s.local
10.2.32.8       etcd-events-3.internal.dvdev2.k8s.local
# End host entries managed by etcd-manager[etcd-events]

**Comment by kciredor** [comment]
```
Validating cluster dvdev2.k8s.local

INSTANCE GROUPS
NAME                    ROLE    MACHINETYPE     MIN     MAX     SUBNETS
bastions                Bastion custom-1-1024   1       1       utility-amsterdam1
master-amsterdam1-1     Master  VDC-4           1       1       amsterdam1
master-amsterdam1-2     Master  VDC-4           1       1       amsterdam1
master-amsterdam1-3     Master  VDC-4           1       1       amsterdam1
nodes                   Node    VDC-4           3       3       amsterdam1

NODE STATUS
NAME                                    ROLE    READY
master-amsterdam1-1-1-dvdev2-k8s-local  node    True
master-amsterdam1-2-1-dvdev2-k8s-local  node    True
master-amsterdam1-3-1-dvdev2-k8s-local  node    True

VALIDATION ERRORS
KIND    NAME                                                    MESSAGE
Machine 723f60e9-ac1f-4d8e-9997-c64e1757644a                    machine "723f60e9-ac1f-4d8e-9997-c64e1757644a" has not yet joined cluster
Machine 7b79313d-3e66-4ceb-b811-a4fad1290f34                    machine "7b79313d-3e66-4ceb-b811-a4fad1290f34" has not yet joined cluster
Machine c2e26c49-0ddc-4785-b7a0-fa5dbf66ef0d                    machine "c2e26c49-0ddc-4785-b7a0-fa5dbf66ef0d" has not yet joined cluster
Pod     kube-system/dns-controller-7b86446756-tkpjz             kube-system pod "dns-controller-7b86446756-tkpjz" is pending
Pod     kube-system/kube-dns-autoscaler-594dcb44b5-js7vl        kube-system pod "kube-dns-autoscaler-594dcb44b5-js7vl" is pending
Pod     kube-system/kube-dns-b84c667f4-qpj5z                    kube-system pod "kube-dns-b84c667f4-qpj5z" is pending

Validation Failed
```

**Comment by kciredor** [comment]
```
kubectl get pods -A
NAMESPACE     NAME                                                             READY   STATUS    RESTARTS   AGE
kube-system   dns-controller-7b86446756-tkpjz                                  0/1     Pending   0          18m
kube-system   etcd-manager-events-master-amsterdam1-1-1-dvdev2-k8s-local       1/1     Running   1          17m
kube-system   etcd-manager-events-master-amsterdam1-2-1-dvdev2-k8s-local       1/1     Running   1          8m18s
kube-system   etcd-manager-events-master-amsterdam1-3-1-dvdev2-k8s-local       1/1     Running   1          18m
kube-system   etcd-manager-main-master-amsterdam1-1-1-dvdev2-k8s-local         1/1     Running   1          17m
kube-system   etcd-manager-main-master-amsterdam1-2-1-dvdev2-k8s-local         1/1     Running   1          8m29s
kube-system   etcd-manager-main-master-amsterdam1-3-1-dvdev2-k8s-local         1/1     Running   1          18m
kube-system   kube-apiserver-master-amsterdam1-1-1-dvdev2-k8s-local            1/1     Running   4          18m
kube-system   kube-apiserver-master-amsterdam1-2-1-dvdev2-k8s-local            1/1     Running   9          8m34s
kube-system   kube-apiserver-master-amsterdam1-3-1-dvdev2-k8s-local            1/1     Running   5          17m
kube-system   kube-controller-manager-master-amsterdam1-1-1-dvdev2-k8s-local   1/1     Running   1          18m
kube-system   kube-controller-manager-master-amsterdam1-2-1-dvdev2-k8s-local   1/1     Running   1          8m37s
kube-system   kube-controller-manager-master-amsterdam1-3-1-dvdev2-k8s-local   1/1     Running   1          18m
kube-system   kube-dns-autoscaler-594dcb44b5-js7vl                             0/1     Pending   0          18m
kube-system   kube-dns-b84c667f4-qpj5z                                         0/3     Pending   0          18m
kube-system   kube-proxy-master-amsterdam1-1-1-dvdev2-k8s-local                1/1     Running   1          17m
kube-system   kube-proxy-master-amsterdam1-2-1-dvdev2-k8s-local                1/1     Running   1          8m39s
kube-system   kube-proxy-master-amsterdam1-3-1-dvdev2-k8s-local                1/1     Running   1          18m
kube-system   kube-scheduler-master-amsterdam1-1-1-dvdev2-k8s-local            1/1     Running   1          17m
kube-system   kube-scheduler-master-amsterdam1-2-1-dvdev2-k8s-local            1/1     Running   1          8m22s
kube-system   kube-scheduler-master-amsterdam1-3-1-dvdev2-k8s-local            1/1     Running   1          18m
kube-system   weave-net-7r9qv                                                  2/2     Running   0          9m40s
kube-system   weave-net-b22tj                                                  2/2     Running   3          18m
kube-system   weave-net-zhxvq                                                  2/2     Running   3          18m
```

**Comment by zetaab** [comment]
There are big issues currently with coreos kops support itself. I do not know does it even work in any other cloud

**Comment by kciredor** [comment]
Wish I knew, haha! With kops 1.15 CoreOS is fine... Did you create a custom debian image?

**Comment by zetaab** [comment]
Default debian works fine. We are running falco so we have customized that part

**Comment by kciredor** [comment]
Unfortunately both Debian 9 (stretch) and 10 default provided OpenStack image are swap enabled. So this looks like CoreOS is not properly supported anymore and Debian needs custom images...

**Comment by kciredor** [comment]
To get default Debian installs working, you can add a custom cloud init script to your instance group definitions running something like swapoff -a and sed -i "/swap/d" /etc/fstab.

Also you can add usage of OpenStack cinder volumes and their respective sizes to the instance group definitions.

Closing for now.
