### ISSUE TITLE
New Website

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#847]
@chrislovecnm needs to touch base with CNCF to check guidelines on a website

@kris-nova needs to come up with a framework to store website content in the repository

All PRs will need to push documentation changes with the feature

@justinsb needs to think about what the tutorial / example / documentation should contain

**Comment by chrislovecnm** [comment]
@sarahnovotny we have an interesting question.  We would like to have a kops website.  I checked with CNCF folks, and did not seem to be a challenge, but would like to coordinate with the community.  We are breaking apart core for kubernetes/kubernetes, and I think this would be a good prototype of how to scale documentation velocity.  I chatted with Brain Grant, who I am not tagging, for a reason.  Who do you want me to work with to prototype this?

**Comment by chrislovecnm** [comment]
bump @sarahnovotny :)

**Comment by kris-nova** [comment]
Let's handle this older issue here https://github.com/kubernetes/kops/issues/1583
