### ISSUE TITLE
coredns-autoscaler has priority = 0

### ISSUE THREAD

**Issue by ari-becker** [kubernetes/kops#8471]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`1.15.0`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`1.15.6`

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kubectl -n kube-system get pod/$(kubectl -n kube-system get pods | grep '^coredns-autoscaler-' | awk '{print $1}') -ojson | jq '.spec.priority'`

**5. What happened after the commands executed?**

Output: `0`

**6. What did you expect to happen?**

A high number (larger than 1 billion, like other system pods)

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

The relevant section:
```
spec:
  kubeDNS:
    provider: CoreDNS
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
N/A

**9. Anything else do we need to know?**

Setting the `coredns-autoscaler` to have a priority of zero is deeply problematic as it can lead to scenarios where the autoscaler is never scheduled. For example:

* A cluster using `cluster-autoscaler` with the [`--expendable-pods-priority-cutoff` flag](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-cluster-autoscaler-work-with-pod-priority-and-preemption) set higher than `0` may preempt the `coredns-autoscaler` and refuse to schedule the autoscaler in efficient clusters.
* Scheduling many high-priority pods can cause the Kubernetes scheduler to delay scheduling the `cluster-autoscaler` pod, for as long as the `cluster-autoscaler` pod has a lower priority than other pods requesting to be scheduled. This is highly likely in certain scenarios since the the `cluster-autoscaler` pod's priority is zero, and lead to livelocking the `cluster-autoscaler` pod.

I consider this to be a bug not insofar as much as the priority being zero (after all, it's not a problematic value in simple clusters without `PriorityClasses`, and the odds of a pod whose resource requests are `cpu: 20m` and `memory: 10Mi` being unable to schedule are pretty slim) but that a) this violates the principle of least surprise and b) I can't change it from the `cluster.yaml` (which is important to me as it pertains to how the initial deployment is created before a new, automatically-created cluster can be validated for the first time).

**Comment by johngmyers** [comment]
In kops 1.15, `coredns-autoscaler` has a `scheduler.alpha.kubernetes.io/critical-pod` annotation, which should suffice. In kops 1.16, it will have a `priorityClassName: system-cluster-critical`.

**Comment by ari-becker** [comment]
/close
fixed in 1.16
