### ISSUE TITLE
CoreOS End-of-Life Announced. Kops should Consider Alternatives

### ISSUE THREAD

**Issue by daviddyball** [kubernetes/kops#8476]
As noted [here](https://coreos.com/os/eol/) CoreOS is being end-of-life'd. The replacement, Fedora CoreOS, is not yet ready for production use, so efforts should probably be mate to provide an upgrade/migration path for existing CoreOS users to migrate their clusters to another host OS.

[Flatcar Container Linux](https://flatcar-linux.org/) is a friendly-fork of CoreOS, but has been operating independently of CoreOS for some time now. Perhaps efforts can be made to support Flatcar AMIs for Kops deployments?

**Comment by tuapuikia** [comment]
kops > 1.14 already support Flatcar distro. https://github.com/kubernetes/kops/blob/release-1.14/nodeup/pkg/model/docker.go#L843

**Comment by tuapuikia** [comment]
Seem like it broken on kops 1.17
`./nodeup --install-systemd-unit --conf=./kube_env.yaml
nodeup version 1.17.0-alpha.1 (git-501baf7e5)
F0206 05:08:29.155682    1806 distribution.go:96] unknown distribution: flatcar`

**Comment by daviddyball** [comment]
@tuapuikia Apologies, hadn't checked `images.md` to see what was already supported. I'll close this for now, but feel free to open a separate issue for Flatcar on `1.17.0-alpha-1` :+1:

**Comment by tuapuikia** [comment]
The problem have been fixed in 1.17.0-alpha-2. Nodeup able to detect flatcar correctly now.

`https://github.com/kubernetes/kops/blob/5db135e3bd4e66e1c5e9301914fc7c33eed7f4a7/nodeup/pkg/distros/distribution.go#L123`

**Comment by rifelpet** [comment]
I think it is worth discussing how Kops should handle the EOL of CoreOS. Kops can try to print a warning if certain images are used but if people are using custom AMIs built off of CoreOS, the `kops` binary won't know the distribution, only `nodeup` does. Thoughts on if/how we should surface a warning to users?

/reopen

**Comment by johngmyers** [comment]
Support for CoreOS has been removed and Flatcar added.
/close
