### ISSUE TITLE
kops can't use credentials generated by aws sso (#aws configure sso)

### ISSUE THREAD

**Issue by atifrasheed79** [kubernetes/kops#8481]
Hi, 

Can someone please confirm if kops can read credentials generated by aws sso? (aws2 cli, #aws2 configure sso) or I have to create an access key and secret to make it work? My AWS CLI is working fine but when I try kops it seems like it's not able to load my aws profile. 

Thanks,
Atif

```
$ kops -v10 get cluster
I0206 17:46:43.037479   93514 factory.go:68] state store s3://xxx-xx-xxxx-xx
I0206 17:46:43.037533   93514 s3context.go:338] GOOS="darwin", assuming not running on EC2
I0206 17:46:43.037544   93514 s3context.go:170] defaulting region to "us-east-1"
I0206 17:46:48.423699   93514 s3context.go:191] unable to get bucket location from region "us-east-1"; scanning all regions: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, xxxxxxxxx.
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/iam/security-credentials/: dial tcp 169.254.169.254:80: connect: host is down
```

**Comment by Neomek** [comment]
I vote for this feature or steps which are need to set up...

**Comment by olemarkus** [comment]
I _think_ this is only about the features of the AWS SDK. 
It may work in newer kops, if not I could have a look if I can set up AWS SSO

**Comment by scp7** [comment]
Have a look at aws2-wrap2 which is a wrapper for executing a command with AWS CLI v2 and SSO. https://pypi.org/project/aws2-wrap2/

I was able to use Kops and AWS SSO with this.

**Comment by geekofalltrades** [comment]
/remove-lifecycle stale

We are hoping to move to AWS SSO for CLI, and this is a blocker, wrapper notwithstanding.

**Comment by olemarkus** [comment]
So AWS SSO is currently not available for the accounts I have for testing kops, nor can it be enabled. I am happy to review a PR though.

**Comment by jetersen** [comment]
looking at how aws2-wrap2 does it.
Seems that it should be fairly simple to add support for SSO cache fetching.

https://github.com/bigwheel/aws2-wrap/blob/da71fc4e00529497e66b5b0e33b3e83118a90a5d/aws2wrap/__init__.py#L79-L89

**Comment by jetersen** [comment]
Ah, aws-sdk-go necessary functions: https://docs.aws.amazon.com/sdk-for-go/api/service/sso/

**Comment by jetersen** [comment]
https://github.com/aws/aws-sdk-go/issues/3186 is the main issue to be solved 😓

A better workaround for the time being https://github.com/benkehoe/aws-sso-credential-process

**Comment by olemarkus** [comment]
I have reached out to AWS to look into that particular issue as this has become important to my employer. Will probably not be ready for 1.19, but kops 1.20 will support AWS SSO is one way or another.

**Comment by urz9999** [comment]
In case like this one or other similar cases where AWS SSO result in incompatibilities with your library and you don't want to play with workarounds or complicated fixes, maybe you can give a try to our open-source project: [https://github.com/Noovolari/leapp](https://github.com/Noovolari/leapp). It deals with AWS SSO authentication and accounts/roles retrieval then it creates short-lived temporary credentials in .aws/credentials to maximize compatibility with third party tools / sdks.

**Comment by rifelpet** [comment]
I believe this should be addressed by https://github.com/kubernetes/kops/pull/10682 if someone could test with a custom kops build off of master that would be much appreciated!

**Comment by jetersen** [comment]
How to get a kops bin off the master without manually building it?
What are the chances for back porting this to 1.18.x?

**Comment by jetersen** [comment]
@rifelpet I simply downloaded the latest 1.21.0-alpha.1

Sadly it does not work.
I also tried using `AWS_PROFILE` to no avail.
```bash
$ ./kops-linux-amd64 get --name k8s.aws-euc1.company.io
error reading cluster configuration "k8s.aws-euc1.company.io": error reading s3://clusters.company.io/k8s.aws-euc1.company.io/config: Unable to list AWS regions: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by olemarkus** [comment]
Can you try to run `export AWS_SDK_LOAD_CONFIG=1` and re-run the `kops` commands?

**Comment by jim-barber-he** [comment]
After running `aws sso login` and running kops without the `AWS_SDK_LOAD_CONFIG` env var set it fails like so:
```
$ kops-v1.20.0 get cluster
I0428 11:35:38.004732   25784 featureflag.go:165] FeatureFlag "ExperimentalClusterDNS"=true
I0428 11:35:38.004810   25784 featureflag.go:165] FeatureFlag "SpecOverrideFlag"=true

error reading state store: Unable to list AWS regions: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, hetest.
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
But setting that env var gets it to work:
```
$ AWS_SDK_LOAD_CONFIG=1 kops-v1.20.0 get cluster
I0428 11:35:17.998359   25709 featureflag.go:165] FeatureFlag "ExperimentalClusterDNS"=true
I0428 11:35:17.998426   25709 featureflag.go:165] FeatureFlag "SpecOverrideFlag"=true
NAME		CLOUD	ZONES
test1.he0.io	aws	ap-southeast-2a,ap-southeast-2b,ap-southeast-2c
test3.he0.io	aws	ap-southeast-2a,ap-southeast-2b,ap-southeast-2c
```

**Comment by jetersen** [comment]
@olemarkus I missed your message 😅 But with v1.20.0 I can confirm with AWS_SDK_LOAD_CONFIG everything works.

**Comment by olemarkus** [comment]
Thanks for confirming. I think we can close this one now then. 
/close

**Comment by ostavnaas** [comment]
Just in case anyone else struggle to get it to work. I needed to remove `~/.aws/credentials` as it contained expired keys from previous way of authenticate (in same section [default]

**Comment by s1mpr0ve** [comment]
> Can you try to run `export AWS_SDK_LOAD_CONFIG=1` and re-run the `kops` commands?

After being lost in the void, I came to this post, and it resolved my problem. Thanks
