### ISSUE TITLE
How do I add EC2 instance (created by different AWS account) as node to kubernetes cluster  

### ISSUE THREAD

**Issue by Shubham-koli** [kubernetes/kops#8483]
I want to add the EC2 instance (Created by **different AWS account**) as nodes to the Kubernetes cluster created via kops. I have a use case where people can come and donate ec2 instances created and managed by them (different AWS account) and I will be using them as nodes in my Kubernetes cluster. VPC might be a problem but let's consider my Kubernetes cluster is open to all traffic.
EC2 instances are in the same region.
how do I achieve this? any kind of help is greatly appreciated.

**Comment by johngmyers** [comment]
I think this is definitely out of scope of what kops is trying to achieve.

**Comment by Shubham-koli** [comment]
oh okay. do you know how can I achieve this?

**Comment by johngmyers** [comment]
That would be something that someone would have to design out. The security implications of such a scheme seem dire.
