### ISSUE TITLE
Update docker version or make it configurable

### ISSUE THREAD

**Issue by OleksandrBerezianskyi** [kubernetes/kops#849]
The current version of docker is 1.11.2. We face the the problem described in https://github.com/kubernetes/kubernetes/issues/32304. Can we please either update a docker version to 1.12.+ or make it configurable?

**Comment by chrislovecnm** [comment]
@justinsb are we going to encounter other issues with 1.12?  Also, what do we need for k8s 1.5? Should we two birds one stone with this issue?

**Comment by stevezau** [comment]
any progress here?

**Comment by chrislovecnm** [comment]
We need to bump the version for k8s 1.5.  That will be out shortly.

**Comment by chrislovecnm** [comment]
We have PR inbound thay may help with this ... I am looking through issues to test against #1183 - no promises but we need to test.

**Comment by chrislovecnm** [comment]
@justinsb was this addressed by #1183?

**Comment by justinsb** [comment]
No, but it is addressed by #1209

**Comment by justinsb** [comment]
Note that we deliberately make this option non-trivial to find ... the supported configurations are kubernetes 1.3/1.4 with docker 1.11.2, and k8s 1.5 with docker 1.12.1 or 1.12.3.  Anything else is likely to be troublesome.
