### ISSUE TITLE
terraform destroy not removing api.internal record from route53

### ISSUE THREAD

**Issue by linecolumn** [kubernetes/kops#8507]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.17.0-alpha.2 (git-5db135e3b)

tried with 1.16.* too

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.17.2

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

1. create cluster.yaml with kops and export it to terraform
2. create cluster with `terraform apply` 
3. validate that cluster is up with `kops validate`
4. destroy cluster with `terraform destroy`
5. issue `kops delete cluster`
6. every time there is one route53-record (api.internal) not removing and not destroyed after `terraform destroy` which is then deleted after `kops delete cluster`

```
# kops delete cluster --name c1.cluster.com --yes
TYPE		NAME				ID
route53-record	api.internal.c1.cluster.com.	Z2CN2GLMNR0JJ0/api.internal.c1.cluster.com.
route53-record:Z2CN2GLMNR0JJ0/api.internal.c1.cluster.com.	ok
```

Expected behaviour is that `terraform destroy` removes route53-record	api.internal.c1.cluster.com.

**Comment by johngmyers** [comment]
This is because that record is created by dns-controller, not Terraform.
