### ISSUE TITLE
Deploying clusters in their own AWS accounts

### ISSUE THREAD

**Issue by itmecho** [kubernetes/kops#8529]
I'm trying to deploy kops managed clusters in their own AWS account, one each for development, test, and production. The issue I will run into is that the the clusters won't be able to update the route53 records as the `company.network` private hosted zone is managed in a separate AWS account. The cluster DNS will have the following format:

    {env}.{version}.app.company.network

I have a work around where I create a hosted zone for the cluster domain in the cluster AWS account and then create an NS record in the master account for the cluster domain to delegate access. However, this involves applying the terraform config in 2 stages, the first creates the VPC and private hosted zone, then runs the `kops update cluster ... --target terraform` command, then terraform apply again. It has to be done in 2 stages because kops gives me this error if I try to run the `kops update cluster` command before creating the cluster hosted zone:

    W0211 17:09:01.414261  180541 executor.go:130] error running task "DNSZone/development.v3.app.company.network" (9m59s remaining to succeed): Creation of Route53 hosted zones is not supported for terraform

Hopefully I've explained the issue well enough!

**Comment by robinpercy** [comment]
Thanks for the report @itmecho. 

This is deliberate behaviour to avoid ambiguity in who created the Hosted Zone. See the helpfully descriptive comment here: https://github.com/kubernetes/kops/blame/298f79659a2bd9c1d6548c6c95b335b5e29e6466/upup/pkg/fi/cloudup/awstasks/dnszone.go#L284

However, Terraform's support for unmanaged resources has improved since that implementation.  So maybe it's worth revisiting.

Are you wanting the generated Terraform to take care of creating the hosted zone for you, or something more nuanced?

**Comment by itmecho** [comment]
Ah that makes sense. Thanks!

In my use case, that would solve the problem. If kops can generate the terraform output for creating the hosted zone for the cluster, I can manually create the NS record in the top level hosted zone by adding some extra terraform config to our overrides before running it. 

Maybe having a bool config value like `spec.dnsZoneCreate` or `spec.topology.dns.zone.managed` which defaults to false would be a backwards compatible way of handling it? I recognise that our implementation is more of an edge case.

**Comment by hingstarne** [comment]
You could try to use an IAM role in your terraform aws profile. This role you could grant rights in the hosted zone. That's the way we handle that chicken and egg issue.


Snippet of the credentials file
```
[terraform]
role_arn = arn:aws:iam::xxxxxxxx:role/myAdminRole
source_profile = profile_which_can_assume_the_role
region = my_region
```
