### ISSUE TITLE
K8s services exposed as a ELB include the master nodes.

### ISSUE THREAD

**Issue by ajohnstone** [kubernetes/kops#853]
An AWS service exposes the master nodes in the ELB instance list for nodes to route to the underlying pods.
However I do not want to expose the master nodes to proxy traffic to the correct nodes, how can you remove them from the instances listed in the ELBs?

An example...

```
AWS_PROFILE=photobox-test;
ELB_NAME=$(kubectl --namespace=development --context=xxx.photobox.com get svc -owide | awk '/smash-website-int/ {print $3}' | awk -F '-' '{print $2}');
aws --profile=${AWS_PROFILE} elb describe-load-balancers --load-balancer=$ELB_NAME --query='LoadBalancerDescriptions[].Instances' --output=text | \
    xargs -n1 aws --profile=${AWS_PROFILE} ec2 describe-instances --instance-ids | \
    jq -r '.Reservations[].Instances[] | .InstanceId as $instance_id | .Tags[] | select(.Key == "k8s.io/role/master" or .Key == "k8s.io/role/node") | $instance_id + " - " + .Key';
    

i-02af58e9a40043488 - k8s.io/role/node
i-0383115dc2adf6592 - k8s.io/role/master
i-046d905e5cbf0aecf - k8s.io/role/master
i-0534cc233b650b7b1 - k8s.io/role/node
i-0931046e7f4f054c6 - k8s.io/role/node
i-0aee7e64a613cd073 - k8s.io/role/node
i-0b4071a806834b631 - k8s.io/role/master
i-0f5acd071bc656d55 - k8s.io/role/node
```

**Comment by chrislovecnm** [comment]
> An AWS service exposes the master nodes in the ELB instance list for nodes to route to the underlying pods.
> However I do not want to expose the master nodes to proxy traffic to the correct nodes, how can you remove them from the instances listed in the ELBs?

So this actually smells like a how to use k8s question.

What are you trying to do with your services?  There are three different types of services in K8s, and also ingress.

**Comment by shamil** [comment]
@ajohnstone,

@justinsb already mentioned about this in #639, this is due to `kops` configures the masters with `taints`. 
As for kubernetes `1.4` taints with `NoSchedule` will avoid scheduling pods on master, but `NodePort` will still be exposed and will be configured in LoadBalancers, e.g ELBs. There is already an issue tracked in `kubernetes` project https://github.com/kubernetes/kubernetes/pull/35902

**Comment by mfornasa** [comment]
Linked issue https://github.com/kubernetes/kubernetes/issues/33884 has been closed, but I am not able to follow that thread, as the fix seems to be related to 1.6, while this issue is preexistent. 
Any info on how to fix this in kops?

**Comment by jkemp101** [comment]
I need to deal with this issue also.  I'm running k8s 1.4.8 built with kops 1.4.2ish.  Can we just mark the masters `unschedulable` to restore the ability to detect a master by that attribute?  Will that keep them out of the ELBs?

**Comment by mfornasa** [comment]
@justinsb is that solved for some 1.5.x version, or there is a suitable workaround?

**Comment by renewooller** [comment]
Not on AWS it seems. On GCP apparently you can use OnlyLocal, I haven't checked this however.

**Comment by justinsb** [comment]
Sorry - we backported this to k8s 1.6.3, but not to 1.5.  Even then, there's another fix that looks like it has to land also (see the discussion at https://github.com/kubernetes/kubernetes/issues/33884#issuecomment-307671386), and that hasn't merged yet, so it hasn't yet even been proposed for a backport.

**Comment by chrislovecnm** [comment]
This is an upstream issue
