### ISSUE TITLE
Changing default admin password in kops kubeconfig file

### ISSUE THREAD

**Issue by tvgua** [kubernetes/kops#8534]
hey guys, I have multiple clusters created with KOPS, and there are no options how i can change default admin user password that i can find in my kubeconfig file after creation. How that default account password can be changed or even disabled? changing kube secret inside s3 secrets dir and rolling update of cluster does not help and i even broke one of master nodes after doing that.

Thanks for help

**Comment by olemarkus** [comment]
Have you read this one? https://kops.sigs.k8s.io/rotate-secrets/
