### ISSUE TITLE
Enable the usage of --kubelet-certificate-authority  in kube-apiserver 

### ISSUE THREAD

**Issue by Nilubkal** [kubernetes/kops#8546]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

It seems that i cannot pass the flag --kubelet-certificate-authority to the kube-apiserver when using a template to create the cluster. In the https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go there is no such option ?

**Comment by rifelpet** [comment]
You're correct, it appears that we dont expose that field through the Kops API. It should be pretty straight forward to add if someone is willing to add it. here's an example PR: https://github.com/kubernetes/kops/pull/7109, simply add the field to each of the componentconfig.go files and run `make apimachinery crds` to update some generated files.

**Comment by robinpercy** [comment]
/assign

I'll take this one. I need to re-familliarize myself with the build process anyway :)

**Comment by tanjunchen** [comment]
@robinpercy  Any progress？
