### ISSUE TITLE
kops v1.15 storage-aws.addons conflicting with user-defined StorageClass

### ISSUE THREAD

**Issue by gsstuart** [kubernetes/kops#8554]
Hi all, we recently upgraded from kops/k8s v1.13 to v.1.14/15, and noticed some new error messages showing up on the masters (`/var/log/messages`):
```
The StorageClass "gp2" is invalid: parameters: Forbidden: updates to parameters are forbidden.
Error: error updating "storage-aws.addons.k8s.io": error applying update from "s3://KOPS-BUCKET/addons/storage-aws.addons.k8s.io/v1.15.0.yaml": error running kubectl
error updating "storage-aws.addons.k8s.io": error applying update from "s3://KOPS-BUCKET/addons/storage-aws.addons.k8s.io/v1.15.0.yaml": error running kubectl
```
These errors are repeated about once a minute, and seem to be happening because we already have a StorageClass defined with the name `gp2`, and kops is trying to create an SC with the same name.  I can make the error go away by deleting our StorageClass, letting the addons do their thing, and then deleting/re-creating our `gp2` StorageClass, but was wondering if anyone had suggestions about a better way to handle this?  

Is this going to happen every time we upgrade now? : )  I suppose we could just rename our StorageClass to something else, but, that would require other changes in our environment.

Thanks!

**Comment by johngmyers** [comment]
The kops storage-aws addon indeed creates a `StorageClass` named `gp2`. That's not going to be able to be changed at this point.

**Comment by gsstuart** [comment]
Gotcha, thanks for the clarification... we'll adjust!
