### ISSUE TITLE
Unable to deploy 1.5 version

### ISSUE THREAD

**Issue by roeyazroel** [kubernetes/kops#856]
Hi,

I want to deploy v1.5.0-alpha.2 using the --kubernetes-version parameter on aws.

It seems that some command kubelet flags are not up to date:
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: unknown flag: --configure-cbr0
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: Usage of /usr/local/bin/kubelet:
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --address ip                                              The IP address for the Kubelet to serve on (set to 0.0.0.0 for all interfaces) (default 0.0.0.0)
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --allow-privileged                                        If true, allow containers to request privileged mode. [default=false]
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --alsologtostderr                                         log to standard error as well as files
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --anonymous-auth                                          Enables anonymous requests to the Kubelet server. Requests that are not rejected by another authentication method are treated as anonymous requests. Anonymous requests have a username of system:anonymous, and a group name of system:unauthenticated. (default true)
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --application-metrics-count-limit int                     Max number of application metrics to store (per container) (default 100)
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --authentication-token-webhook                            Use the TokenReview API to determine authentication for bearer tokens.
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --authentication-token-webhook-cache-ttl duration         The duration to cache responses from the webhook token authenticator. (default 2m0s)
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --authorization-mode string                               Authorization mode for Kubelet server. Valid options are AlwaysAllow or Webhook. Webhook mode uses the SubjectAccessReview API to determine authorization. (default "AlwaysAllow")

and this is in loop for over 30m in the daemon.log on one of the master nodes.

Thanks,
Roey

**Comment by roeyazroel** [comment]
Update: I'm not able to deploy 1.5.0-alpha.2

It seems that some command kubelet flags are not up to date:
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: unknown flag: --configure-cbr0
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: Usage of /usr/local/bin/kubelet:
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --address ip                                              The IP address for the Kubelet to serve on (set to 0.0.0.0 for all interfaces) (default 0.0.0.0)
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --allow-privileged                                        If true, allow containers to request privileged mode. [default=false]
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --alsologtostderr                                         log to standard error as well as files
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --anonymous-auth                                          Enables anonymous requests to the Kubelet server. Requests that are not rejected by another authentication method are treated as anonymous requests. Anonymous requests have a username of system:anonymous, and a group name of system:unauthenticated. (default true)
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --application-metrics-count-limit int                     Max number of application metrics to store (per container) (default 100)
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --authentication-token-webhook                            Use the TokenReview API to determine authentication for bearer tokens.
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --authentication-token-webhook-cache-ttl duration         The duration to cache responses from the webhook token authenticator. (default 2m0s)
Nov 10 08:03:10 ip-172-166-181-126 kubelet[3376]: --authorization-mode string                               Authorization mode for Kubelet server. Valid options are AlwaysAllow or Webhook. Webhook mode uses the SubjectAccessReview API to determine authorization. (default "AlwaysAllow")

and this is in loop for over 30m in the daemon.log on one of the master nodes.

Roey

**Comment by chrislovecnm** [comment]
1.5 is not supported yet.  There is an issue open. Finding the issue

**Comment by chrislovecnm** [comment]
Added to our umbrella issue list: https://github.com/kubernetes/kops/issues/1206

**Comment by justinsb** [comment]
This should be fixed in 1.4.4 and on the master branch (which will become 1.5).

OK to close?

**Comment by snarlysodboxer** [comment]
@justinsb i tried kops 1.4.4 with k8s 1.5.X and still got deprecated kubelet flags errors. (not warnings, it fails.) sorry, don't have the error messages around at the moment...

**Comment by justinsb** [comment]
This should definitely be fixed in 1.4.4 (not only on the master branch).  We'll have to look again.

**Comment by justinsb** [comment]
This should be fixed by #1287 on the master branch.

**Comment by snarlysodboxer** [comment]
@justinsb i don't know why it didn't work before, perhaps because i tried a 1.5 beta.

i just tried kops 1.4.4 with k8s version 1.5.1 and it worked well. thanks!

**Comment by chrislovecnm** [comment]
Closing
