### ISSUE TITLE
Migrating Control Plane to EKS?

### ISSUE THREAD

**Issue by Freyert** [kubernetes/kops#8560]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
I'm beginning a conversation/exploration into what it takes to migrate as seamlessly as possible from personally managed control plane to EKS managed control plane.

I imagine this is largely a data migration from personally managed to EKS managed, but there are perhaps several roadblocks to consider such as:

1. Migrating ownership of Cloud Resources
   + Loadbalancers
   + Persistent Storage
   + IAM roles
2. Cluster RBAC
3. Unkown Cluster differences

I've done some googling and no one seems to have investigated or explained this process in great depth if they have tried it at all. I figured opening this up to the thousand eyes as early as I possibly could would help to illuminate issues that might not occur to myself.

Articles I have encountered relating to this migration:

* [_Migrating from Self-Managed Kubernetes to AWS EKS Using Terraform at Blue Matador_](https://www.infoq.com/news/2019/06/eks-migration-bluematador/)
   > Very vague. Does not discuss migrating data or permissions at all. Its mostly about how they used terraform.

**Comment by robinpercy** [comment]
Hey @Freyert. I may be misunderstanding what you mean by "migrating the control plane" but EKS has some very specific constraints on how self-managed nodes are initialized in the cluster. So, you're not going to be able to migrate without also rebuilding the node pools. 

Have you looked at a solution like Velero? https://github.com/vmware-tanzu/velero

**Comment by Freyert** [comment]
@robinpercy I have checked out velero, but it looks we're going to have too setup up some kind of multi-cluster mesh and migrate services one at a time.

**Comment by olemarkus** [comment]
Given the limitations of EKS, this is probably not ever going to be possible. If one wants to migrate one probably have to do this through DNS/ELBs etc.

Anyways out of the scope of what Kops can offer.
/close
