### ISSUE TITLE
Kops deployments to US-EAST-2

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#858]
Kubernetes doesn't run in US-EAST-2
Kops can deploy resources in US-EAST-2

That is a major problem for users not aware of the US-EAST-2 restriction with kubernetes. We should have the kops validation catch this, and fail to deploy erroneous infrastructure

CC @jmound

**Comment by shrabok-surge** [comment]
@kris-nova Is there any clarity or information regarding kubernetes not running in us-east? Is that AWS or GCE?

**Comment by kris-nova** [comment]
Its a known issue https://github.com/kubernetes/kubernetes/pull/35013 

I think the scope of this work is more in line with supporting a kops feature for `unsupported regions` in AWS.. With it's first and temporary use case being `us-east-2`

**Comment by shrabok-surge** [comment]
Thanks for the clarification @kris-nova

**Comment by chrislovecnm** [comment]
It will be supported in the next k8s release

**Comment by kris-nova** [comment]
Great news @chrislovecnm - I still would like to see kops support this a little more gracefully

Right now it allows the user to *attempt* to create resources in the region.. and that is bad.. I think the right approach is to define a list of *supported* regions for kops (the regions we know work today) and have kops yell at the user if they try to use one that isn't in the list.

After support for a new region is built in - we can amend the list

**Comment by chrislovecnm** [comment]
@justinsb any idea what is up with this??

**Comment by chrislovecnm** [comment]
us-east-2 does not work with 1.4.6 and 1.5 beta 1

**Comment by chrislovecnm** [comment]
Closing this should be fixed

**Comment by inazrabuu** [comment]
I tried to create a cluster in ap-southeast-1 with kops, it returned:

unable to infer CloudProvider from Zones (is there a typo in --zones?)

does kubernetes not supported in that region?

**Comment by justinsb** [comment]
@inazrabuu you have to specify zones, not regions - i.e. `--zones ap-southeast-1a`, not `--zones ap-southeast-1`

**Comment by inazrabuu** [comment]
@justinsb you are right, I did that last night and it worked. Forgot to update here.
