### ISSUE TITLE
Create Kubernetes cluster in existing private subnet

### ISSUE THREAD

**Issue by rewilliams1** [kubernetes/kops#8596]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.15.2 (git-ad595825a)
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"17",
**3. What cloud provider are you using?**
aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster --cloud=aws --zones=us-east-1b,us-east-1c --name=${CLUSTER_NAME} --dns-zone=${DNS_NAME} --dns=private --topology=private --vpc=${VPC_ID} --subnets=${SUBNET_ID2},${SUBNET_ID1} --networking=weave

**5. What happened after the commands executed?**
spec.subnets: Invalid value: 
[]kops.ClusterSubnetSpec{kops.ClusterSubnetSpec{Name:"us-east-1b", CIDR:"10.0.1.0/24", Zone:"us-east-1b", Region:"", ProviderID:"subnet-dfadfasdfadsfd", Egress:"", Type:"Private", PublicIP:""}, kops.ClusterSubnetSpec{Name:"us-east-1c", CIDR:"10.0.2.0/24", Zone:"us-east-1c", Region:"", ProviderID:"subnet-dfadsfdsfdsf", Egress:"", Type:"Private", PublicIP:""}, kops.ClusterSubnetSpec{Name:"utility-us-east-1b", CIDR:"10.0.32.0/22", Zone:"us-east-1b", Region:"", ProviderID:"", Egress:"", Type:"Utility", PublicIP:""}, kops.ClusterSubnetSpec{Name:"utility-us-east-1c", CIDR:"10.0.36.0/22", Zone:"us-east-1c", Region:"", ProviderID:"", Egress:"", Type:"Utility", PublicIP:""}}: cannot mix subnets with specified ID and unspecified ID

**6. What did you expect to happen?**
Cluster to be created in existing VPC using existing subnets
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by rewilliams1** [comment]
This is the config I use to try to update the existing cluster. 
`  subnets:
  - cidr: 10.0.1.0/24
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.0.3.0/24
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.0.2.0/24
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.0.4.0/24
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c`

I get the following error message:
	status code: 400, request id: 1232e061-d8c5-44ba-bcc6-8c4531cb0489
W0220 17:11:45.347765    3593 executor.go:130] error running task "Subnet/us-east-1b.k8s.firemon.local" (9m28s remaining to succeed): error creating subnet: InvalidSubnet.Conflict: The CIDR '10.0.1.0/24' conflicts with another subnet
	status code: 400, request id: 7f07785c-dbff-480e-8b21-90eb2f51f8e6
W0220 17:11:45.347926    3593 executor.go:130] error running task "Subnet/utility-us-east-1c.k8s.firemon.local" (9m28s remaining to succeed): error creating subnet: InvalidSubnet.Conflict: The CIDR '10.0.4.0/24' conflicts with another subnet

**Comment by olemarkus** [comment]
You need to explicitly set subnet id on both clusters so that kops set the correct tags on the them.

**Comment by rewilliams1** [comment]
I set the two subnet-id's when I was creating the cluster. Where else should these values be set?

**Comment by olemarkus** [comment]
If the subnets were created with the first cluster, you need to add the IDs there as well, then run update. That will cause kops to change the subnet tags to be shared instead of owned.

**Comment by olemarkus** [comment]
Anything more left in this issue, or can it be closed?
