### ISSUE TITLE
Provide prebaked custom AMI without user_data

### ISSUE THREAD

**Issue by povils** [kubernetes/kops#8597]
Is it possible to provide my own AWS AMI with all preinstalled and configured dependencies and don't rely on user_data?

Simple use case:
Due to regulatory reasons all traffic has to stay inside VPC which user_data by fetching all these binaries is violating.

**Comment by rdrgmnzs** [comment]
@povils one way to get around this that we use, is that we build the binaries internally and host them in our own S3 bucket. You can then configure the user_data script to pull from your internal S3 bucket instead.

**Comment by povils** [comment]
Thank for the response! How do you override user_data provided by kops? The only option I could find was additionalUserData but that's not what I want because it just appends to kops user_data

**Comment by olemarkus** [comment]
Using your own binaries would be very similar to the process described here https://github.com/kubernetes/kops/blob/master/docs/development/adding_a_feature.md#testing

**Comment by povils** [comment]
@olemarkus thanks for the response but as I understand it just overrides nodeup url? What I'm trying to achieve is to have all binaries already baked in AMI and have no network I/O in user data

**Comment by olemarkus** [comment]
It will allow you to ensure no traffic goes out of your AWS account.

Avoiding any downloads whatsoever could be technically possible, I guess. You could have kops create cloudformation templates and then remove those parts of the cloudinit.

**Comment by olemarkus** [comment]
Worth to mention these configs. https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#assets
There is also an undocumented `FileRepository`
https://godoc.org/k8s.io/kops/pkg/apis/kops#Assets
