### ISSUE TITLE
Unable to attach external IAM Policy

### ISSUE THREAD

**Issue by richstokes** [kubernetes/kops#8621]
Following this doc:
 https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#adding-external-policies

I add the lines via `kops edit cluster` and get 
```
# Found fields that are not recognized
# ...
#         name: c
#       name: events
# +   externalPolicies:
# +     node:
# +     - arn:aws:iam::aws:policy/PolicyNamehere
```

I am adding this under `spec:`
```
  externalPolicies:
    node:
    - arn:aws:iam::aws:policy/PolicyNamehere
```

```
kops version
Version 1.14.
```
(also tried on latest build - same behavior)

AWS-Based cluster

**Comment by rifelpet** [comment]
Hi @richstokes, that feature was only recently added and will be in Kops 1.18: https://github.com/kubernetes/kops/pull/7837 we may backport it to Kops 1.17 but I'm afraid you'll have to wait a bit until you can use this feature.

When you say you tried on latest build, what was the exact Kops version that you used? If you compile it yourself from master, that should work.

**Comment by richstokes** [comment]
Sorry, by build I meant latest release (which is 1.15.2 via brew) - but thats OK, I can attach these manually for now and will revisit once we are on >1.18.0

Thanks

**Comment by olemarkus** [comment]
I guess this one can just be closed now.
/close
