### ISSUE TITLE
unable to create a kops cluster configuration for GCE using Private topology

### ISSUE THREAD

**Issue by mehercharan** [kubernetes/kops#8626]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.15.2 (git-ad595825a)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
N/A . Did not specify any Kubernetes version

**3. What cloud provider are you using?**

GCE

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

 kops create cluster airflow-test.k8s.local  --zones us-central1-b --state ${KOPS_STATE_STORE}/ --project=${PROJECT} --vpc=vpcnet-shared-prod-01  --node-count 3  --networking flannel  --subnets=${SUBNET} --dns=private --topology private

**5. What happened after the commands executed?**
I0225 00:05:38.462787   29873 create_cluster.go:517] Inferred --cloud=gce from zone "us-central1-b"
I0225 00:05:38.462888   29873 gce_cloud.go:125] Will load GOOGLE_APPLICATION_CREDENTIALS from xxxxxxxx

spec.Subnets[1].Region: Required value: region must be specified for GCE subnets

**6. What did you expect to happen?**
Cluster configuration should be created

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
Not created

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

I0225 00:08:27.545542   30036 gsfs.go:231] Reading file "gs://kubernetes1-dev/airflow-test1.k8s.local/config"
I0225 00:08:28.304112   30036 channel.go:99] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I0225 00:08:28.304174   30036 channel.go:104] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I0225 00:08:28.304209   30036 context.go:177] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I0225 00:08:28.428804   30036 channel.go:113] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.8.0 <1.9.0"
    - name: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.9.0 <1.10.0"
    - name: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.10.0 <1.11.0"
    # Stretch is the default for 1.11 (for nvme)
    - name: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-01-17
      providerID: aws
      kubernetesVersion: ">=1.11.0 <1.12.0"
    - name: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2020-01-17
      providerID: aws
      kubernetesVersion: ">=1.12.0 <1.13.0"
    - name: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2020-01-17
      providerID: aws
      kubernetesVersion: ">=1.13.0 <1.14.0"
    - name: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2020-01-17
      providerID: aws
      kubernetesVersion: ">=1.14.0 <1.15.0"
    - name: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-01-17
      providerID: aws
      kubernetesVersion: ">=1.15.0 <1.16.0"
    - name: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
      providerID: aws
      kubernetesVersion: ">=1.16.0 <1.17.0"
    - name: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
      providerID: aws
      kubernetesVersion: ">=1.17.0"
    - providerID: gce
      kubernetesVersion: "<1.16.0-alpha.1"
      name: "cos-cloud/cos-stable-65-10323-99-0"
    - providerID: gce
      kubernetesVersion: ">=1.16.0-alpha.1"
      name: "cos-cloud/cos-stable-77-12371-114-0"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.17.0"
    recommendedVersion: 1.17.2
    requiredVersion: 1.17.0
  - range: ">=1.16.0"
    recommendedVersion: 1.16.6
    requiredVersion: 1.16.0
  - range: ">=1.15.0"
    recommendedVersion: 1.15.9
    requiredVersion: 1.15.0
  - range: ">=1.14.0"
    recommendedVersion: 1.14.10
    requiredVersion: 1.14.0
  - range: ">=1.13.0"
    recommendedVersion: 1.13.12
    requiredVersion: 1.13.0
  - range: ">=1.12.0"
    recommendedVersion: 1.12.10
    requiredVersion: 1.12.0
  - range: ">=1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.0
  - range: "<1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.10
  kopsVersions:
  - range: ">=1.17.0-alpha.1"
    #recommendedVersion: "1.17.0"
    #requiredVersion: 1.17.0
    kubernetesVersion: 1.17.2
  - range: ">=1.16.0-alpha.1"
    #recommendedVersion: "1.16.0"
    #requiredVersion: 1.16.0
    kubernetesVersion: 1.16.6
  - range: ">=1.15.0-alpha.1"
    #recommendedVersion: "1.15.0"
    #requiredVersion: 1.15.0
    kubernetesVersion: 1.15.9
  - range: ">=1.14.0-alpha.1"
    #recommendedVersion: "1.14.0"
    #requiredVersion: 1.14.0
    kubernetesVersion: 1.14.10
  - range: ">=1.13.0-alpha.1"
    #recommendedVersion: "1.13.0"
    #requiredVersion: 1.13.0
    kubernetesVersion: 1.13.12
  - range: ">=1.12.0-alpha.1"
    recommendedVersion: "1.12.1"
    #requiredVersion: 1.12.0
    kubernetesVersion: 1.12.10
  - range: ">=1.11.0-alpha.1"
    recommendedVersion: "1.11.1"
    #requiredVersion: 1.11.0
    kubernetesVersion: 1.11.10
  - range: "<1.11.0-alpha.1"
    recommendedVersion: "1.11.1"
    #requiredVersion: 1.10.0
    kubernetesVersion: 1.11.10
I0225 00:08:28.429032   30036 channel.go:241] version range ">=1.17.0-alpha.1" does not apply to version "1.15.2"; skipping
I0225 00:08:28.429075   30036 channel.go:241] version range ">=1.16.0-alpha.1" does not apply to version "1.15.2"; skipping
I0225 00:08:28.429135   30036 create_cluster.go:517] Inferred --cloud=gce from zone "us-central1-b"
I0225 00:08:28.429195   30036 create_cluster.go:1018] networking mode=flannel => {"flannel":{"backend":"vxlan"}}
I0225 00:08:28.429246   30036 gce_cloud.go:125] Will load GOOGLE_APPLICATION_CREDENTIALS from xxxxxxxxxx
I0225 00:08:28.675606   30036 gce_cloud.go:160] running with GCE credentials: email=, scope=https://www.googleapis.com/auth/cloud-platform
I0225 00:08:28.675668   30036 defaults.go:224] Not setting up Proxy Excludes

spec.Subnets[1].Region: Required value: region must be specified for GCE subnets

**9. Anything else do we need to know?**
No

**Comment by mehercharan** [comment]
can some please comment if this feature of creating a private network instead of public ip for master and worker nodes is supported for GCP using KOPS?

**Comment by geojaz** [comment]
Hey @mehercharan - I've been doing some work with kops/GCE to get it up to speed and more on par with AWS/other cloud providers, but we have a long ways to go. My guess is that kops GCE is unlikely to support private clusters right now, but I'll have to do some investigation to see. I wouldn't be that surprised if you could get kops to work with GCE in private mode if you did some networking configuration around the edges. So TBD on the question you asked.

However, you did spot a bug. I read through your logs and also tried this out myself, and kops is erroring out in a way that it should not be. There currently is no way to specific the region for a GCE subnet which the error clearly wants. I took a look at the code that's raising this error, and I think it's wrong. Nice spot! I'll have to dig into this a little bit more closely and get a patch in for it. Unfortunately like I said, I'm not sure that fixing this bug will make private topology on GCE a simple exercise, but we should put in our roadmap and get it going.

**Comment by geojaz** [comment]
Bug: Kops ends up in a state where you have subnets with no regions when using private topology on GCE. It seems to happen whether you're trying to reuse an existing VPC or not.  https://github.com/kubernetes/kops/blob/632b426bdfc2bd3566c6bc5a690fa1c4022d736d/upup/pkg/fi/cloudup/utils.go#L46-L53 

```
kops create cluster --state=gs://kops-dev-12345 --name eric.k8s.local --zones us-central1-c --project kops-test-123 --vpc default --topology private --networking flannel 
```

**Comment by geojaz** [comment]
This is actually pretty complicated due to some assumptions that we make about the network in GCP. I think we would like to support private topologies in GCE, but we have some work to do before we get there.

**Comment by mehercharan** [comment]
Thanks @geojaz

**Comment by MoShitrit** [comment]
Hey @geojaz !
Did you happen to make any progress on that end?
I just now tried to create a cluster on GCP using the below flags and got that error:

```
$ kops create cluster test-kops.k8s.local --zones=us-east4-a --state ${KOPS_STATE_STORE} --project=${PROJECT} --networking cilium --bastion --topology private
I0825 15:59:06.554962   59974 create_cluster.go:562] Inferred --cloud=gce from zone "us-east4-a"

spec.Subnets[1].Region: Required value: region must be specified for GCE subnets
```

Generally- how far are we from saying that kops is a good option to build production grade k8s clusters on GCE?

**Comment by shamil** [comment]
I'm interested to know as well. Would love to migrate out from GKE

**Comment by rifelpet** [comment]
@MoShitrit which version of kops was that and can you run it with `-v 9` ?

**Comment by MoShitrit** [comment]
```
$ kops version
Version 1.17.1

$ kops create cluster test-kops.k8s.local --zones=us-east4-a --state ${KOPS_STATE_STORE} --project=${PROJECT} --networking cilium --bastion --topology private -v9
I0825 20:05:46.574284    3600 factory.go:68] state store gs://kops-test
I0825 20:05:46.577066    3600 gsfs.go:235] Reading file "gs://kops-test/test-kops.k8s.local/config"
I0825 20:05:46.931039    3600 channel.go:99] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I0825 20:05:46.931069    3600 channel.go:104] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I0825 20:05:46.931088    3600 context.go:179] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I0825 20:05:46.992067    3600 channel.go:113] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.8.0 <1.9.0"
    - name: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.9.0 <1.10.0"
    - name: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.10.0 <1.11.0"
    # Stretch is the default for 1.11 (for nvme)
    - name: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-07-20
      providerID: aws
      kubernetesVersion: ">=1.11.0 <1.12.0"
    - name: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2020-07-20
      providerID: aws
      kubernetesVersion: ">=1.12.0 <1.13.0"
    - name: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2020-07-20
      providerID: aws
      kubernetesVersion: ">=1.13.0 <1.14.0"
    - name: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2020-07-20
      providerID: aws
      kubernetesVersion: ">=1.14.0 <1.15.0"
    - name: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-07-20
      providerID: aws
      kubernetesVersion: ">=1.15.0 <1.16.0"
    - name: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-07-20
      providerID: aws
      kubernetesVersion: ">=1.16.0 <1.17.0"
    - name: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
      providerID: aws
      kubernetesVersion: ">=1.17.0 <1.18.0"
    - name: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
      providerID: aws
      kubernetesVersion: ">=1.18.0"
    - providerID: gce
      kubernetesVersion: "<1.16.0-alpha.1"
      name: "cos-cloud/cos-stable-65-10323-99-0"
    - providerID: gce
      kubernetesVersion: ">=1.16.0-alpha.1"
      name: "cos-cloud/cos-stable-77-12371-114-0"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.18.0"
    recommendedVersion: 1.18.8
    requiredVersion: 1.18.0
  - range: ">=1.17.0"
    recommendedVersion: 1.17.11
    requiredVersion: 1.17.0
  - range: ">=1.16.0"
    recommendedVersion: 1.16.14
    requiredVersion: 1.16.0
  - range: ">=1.15.0"
    recommendedVersion: 1.15.12
    requiredVersion: 1.15.0
  - range: ">=1.14.0"
    recommendedVersion: 1.14.10
    requiredVersion: 1.14.0
  - range: ">=1.13.0"
    recommendedVersion: 1.13.12
    requiredVersion: 1.13.0
  - range: ">=1.12.0"
    recommendedVersion: 1.12.10
    requiredVersion: 1.12.0
  - range: ">=1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.0
  - range: "<1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.10
  kopsVersions:
  - range: ">=1.19.0-alpha.1"
    #recommendedVersion: "1.19.0-alpha.1"
    #requiredVersion: 1.19.0
    kubernetesVersion: 1.19.0-rc.1
  - range: ">=1.18.0-alpha.1"
    recommendedVersion: "1.18.0"
    #requiredVersion: 1.18.0
    kubernetesVersion: 1.18.8
  - range: ">=1.17.0-alpha.1"
    recommendedVersion: "1.17.1"
    #requiredVersion: 1.17.0
    kubernetesVersion: 1.17.11
  - range: ">=1.16.0-alpha.1"
    recommendedVersion: "1.16.4"
    #requiredVersion: 1.16.0
    kubernetesVersion: 1.16.14
  - range: ">=1.15.0-alpha.1"
    recommendedVersion: "1.15.3"
    #requiredVersion: 1.15.0
    kubernetesVersion: 1.15.12
  - range: ">=1.14.0-alpha.1"
    #recommendedVersion: "1.14.0"
    #requiredVersion: 1.14.0
    kubernetesVersion: 1.14.10
  - range: ">=1.13.0-alpha.1"
    #recommendedVersion: "1.13.0"
    #requiredVersion: 1.13.0
    kubernetesVersion: 1.13.12
  - range: ">=1.12.0-alpha.1"
    recommendedVersion: "1.12.1"
    #requiredVersion: 1.12.0
    kubernetesVersion: 1.12.10
  - range: ">=1.11.0-alpha.1"
    recommendedVersion: "1.11.1"
    #requiredVersion: 1.11.0
    kubernetesVersion: 1.11.10
  - range: "<1.11.0-alpha.1"
    recommendedVersion: "1.11.1"
    #requiredVersion: 1.10.0
    kubernetesVersion: 1.11.10
I0825 20:05:46.993731    3600 channel.go:237] version range ">=1.19.0-alpha.1" does not apply to version "1.17.1"; skipping
I0825 20:05:46.993772    3600 channel.go:237] version range ">=1.18.0-alpha.1" does not apply to version "1.17.1"; skipping
I0825 20:05:46.994115    3600 create_cluster.go:562] Inferred --cloud=gce from zone "us-east4-a"
I0825 20:05:46.994333    3600 create_cluster.go:1052] networking mode=cilium => {"cilium":{"enableipv6":false,"enableipv4":false,"monitorAggregation":"","bpfCTGlobalTCPMax":0,"bpfCTGlobalAnyMax":0,"preallocateBPFMaps":false,"sidecarIstioProxyImage":"","clusterName":"","toFqdnsEnablePoller":false,"IPTablesRulesNoinstall":false,"autoDirectNodeRoutes":false,"enableNodePort":false,"enableRemoteNodeIdentity":false,"removeCbrBridge":false,"restartPods":false,"reconfigureKubelet":false,"nodeInitBootstrapFile":"","cniBinPath":""}}
I0825 20:05:47.118146    3600 gce_cloud.go:159] running with GCE credentials: email=***@***.com, scope=openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/accounts.reauth
I0825 20:05:47.118550    3600 defaults.go:224] Not setting up Proxy Excludes

spec.Subnets[1].Region: Required value: region must be specified for GCE subnets
```

@rifelpet ⬆️

**Comment by rifelpet** [comment]
@MoShitrit I have a fix in https://github.com/kubernetes/kops/pull/9815. I was able to repro your issue and can now create a dryrun yaml manifest for a private topology GCE cluster. I haven't tested the remainder of the cluster creation process though.

**Comment by MoShitrit** [comment]
Perfect! 
I'll try to build kops from master later today and let you know if it works.
Thanks for the quick fix @rifelpet !

**Comment by MoShitrit** [comment]
OK, got another issue now:
Ran this:
```
~/src/kubernetes/kops/bin/kops create cluster test-kops.k8s.local --zones=us-east4-a --state ${KOPS_STATE_STORE} --project=${PROJECT} --networking cilium --bastion --topology private -v9
```
And got this error (eventually, there was a ton of output so I took the one that seems most relevant):
```
I0826 10:24:14.249626   11681 gce_cloud.go:217] fetching project "test-kops-gce" from compute API
I0826 10:24:14.452651   11681 autoscalinggroup.go:143] VMs using Service Account: default
I0826 10:24:14.452667   11681 autoscalinggroup.go:151] gsa: default
I0826 10:24:14.452677   11681 task.go:102] testing task "InstanceTemplate"
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
k8s.io/kops/pkg/model/gcemodel.(*AutoscalingGroupModelBuilder).Build(0xc00030b9a0, 0xc001121e50, 0x0, 0x0)
	/Users/mosheshitrit/src/kubernetes/kops/src/k8s.io/kops/pkg/model/gcemodel/autoscalinggroup.go:195 +0x1ee1
k8s.io/kops/upup/pkg/fi/cloudup.(*Loader).BuildTasks(0xc000bb1780, 0x5446200, 0xc000a4fb20, 0xc000cfc2c0, 0xc00093b470, 0xc000aea9c0, 0x9, 0x12, 0x0)
	/Users/mosheshitrit/src/kubernetes/kops/src/k8s.io/kops/upup/pkg/fi/cloudup/loader.go:137 +0x2be
k8s.io/kops/upup/pkg/fi/cloudup.(*ApplyClusterCmd).Run(0xc0009ea0b0, 0x53e42c0, 0xc0000f2010, 0x0, 0x0)
	/Users/mosheshitrit/src/kubernetes/kops/src/k8s.io/kops/upup/pkg/fi/cloudup/apply_cluster.go:689 +0x1d1a
main.RunUpdateCluster(0x53e42c0, 0xc0000f2010, 0xc0009b2ca0, 0x7ffeefbff7c8, 0x13, 0x537ea80, 0xc0000ee008, 0xc00043a510, 0x0, 0x0, ...)
	/Users/mosheshitrit/src/kubernetes/kops/src/k8s.io/kops/cmd/kops/update_cluster.go:274 +0x623
main.RunCreateCluster(0x53e42c0, 0xc0000f2010, 0xc0009b2ca0, 0x537ea80, 0xc0000ee008, 0xc0005c2800, 0xc0004d4e00, 0xc0009a1d20)
	/Users/mosheshitrit/src/kubernetes/kops/src/k8s.io/kops/cmd/kops/create_cluster.go:619 +0x1a73
main.NewCmdCreateCluster.func1(0xc000466b00, 0xc0002c4370, 0x1, 0xb)
	/Users/mosheshitrit/src/kubernetes/kops/src/k8s.io/kops/cmd/kops/create_cluster.go:192 +0x188
github.com/spf13/cobra.(*Command).execute(0xc000466b00, 0xc0002c42c0, 0xb, 0xb, 0xc000466b00, 0xc0002c42c0)
	/Users/mosheshitrit/src/kubernetes/kops/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x7547500, 0x757d9c0, 0x0, 0x0)
	/Users/mosheshitrit/src/kubernetes/kops/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mosheshitrit/src/kubernetes/kops/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.Execute()
	/Users/mosheshitrit/src/kubernetes/kops/src/k8s.io/kops/cmd/kops/root.go:96 +0x8f
main.main()
	/Users/mosheshitrit/src/kubernetes/kops/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```

**Comment by MoShitrit** [comment]
@rifelpet ⬆️

**Comment by rifelpet** [comment]
@MoShitrit can you give this fix a shot: https://github.com/kubernetes/kops/pull/9827

I was able to successfully run your kops create cluster command.

**Comment by MoShitrit** [comment]
@rifelpet that worked!
The cluster is now spinning up, fingers crossed that everything's going to work.
I LGTMd the PR since I confirmed it solved my issue.
I'll keep you posted.
Thanks a lot!! 😄

**Comment by MoShitrit** [comment]
@rifelpet 
OK the cluster started, however I've found two issues so far:
1. The master and nodes were created with public IPs, even though I marked the topology as private.
2. The bastion didn't have a load balancer created (I expected to see one created, same as aws) - is that intentional? 

Also as a side note, I tried to change the api load balancer type from `Public` to `Internal`, but got an error that it's not supported on GCE yet - is that in the roadmap?

Thanks!

**Comment by rifelpet** [comment]
/reopen

I have very minimal experience with GCE so I don't know how helpful I will be in implementing some of these fixes, but they all seem like reasonable changes to make. If someone is willing to open PRs for them I'll be happy to review them.

* From a brief reading of the compute docs, it seems like we may want to not add [this AccessConfig](https://github.com/kubernetes/kops/blob/93f7a5d9cff7d93621a8b80079d80a7de2fe37f0/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go#L254-L259) to the instance template if we want the instance to be private. I'm not sure how we determine that though because in AWS its based on the subnet being public or private, so we might need to add a new field to instance template and connect it from the gcemodel [here](https://github.com/kubernetes/kops/blob/93f7a5d9cff7d93621a8b80079d80a7de2fe37f0/pkg/model/gcemodel/autoscalinggroup.go#L74-L98) based on the topology of the cluster (the ClusterSpec is available in the model for reference)

 * Adding a bastion LB should be pretty straight forward. It would require a new model like [this aws one](https://github.com/kubernetes/kops/blob/ea3e974d81f40a2e7c554f36332a8aa2bccc5c19/pkg/model/bastion.go#L204-L264) but in `pkg/model/gcemodel/` and load the model [like this](https://github.com/kubernetes/kops/blob/e1d5ae889686fd71301250973cdf370281c3c369/upup/pkg/fi/cloudup/apply_cluster.go#L507)

* for an internal load balancer (or forwarding address rather) it should just be a matter of setting the AddressType field [here](https://github.com/kubernetes/kops/blob/93f7a5d9cff7d93621a8b80079d80a7de2fe37f0/upup/pkg/fi/cloudup/gcetasks/address.go#L131-L135) to `INTERNAL` also using a new field in that Address task type, setting that field from [here](https://github.com/kubernetes/kops/blob/ea3e974d81f40a2e7c554f36332a8aa2bccc5c19/pkg/model/gcemodel/api_loadbalancer.go#L63-L65) where the cluster spec's api load balancer access fields can be referenced.

I hope this helps, if this is overwhelming I might be able to get to it soon but wont be able to test it so I'll need to rely on someone else for that :)

**Comment by MoShitrit** [comment]
Thanks for all that info @rifelpet!
I'd love to try and tackle that, but given that I don't have _that_ much free time, I'm not sure how long it could take for me to figure everything out, so in the meantime if anyone else can take a stab it- please do 😄 
As far as testing goes- I can definitely help with that. We have an account already set up and we are trying to get a private cluster up in GCP anyway- so that would be ideal for us.
If I'll be able to find some time and get to work on it soon, I'll let you know.

**Comment by DmyMi** [comment]
Hello, tried to run
```
kops create cluster \
    --name ${NAME} \
    --state ${KOPS_STATE_STORE} \
    --node-count 3 \
    --master-count=3 \
    --zones europe-west3-a,europe-west3-b,europe-west3-c \
    --master-zones europe-west3-a,europe-west3-b,europe-west3-c \
    --node-size e2-small \
    --master-size e2-small \
    --master-volume-size=20 \
    --node-volume-size=20 \
    --subnets europe-west3 \
    --utility-subnets europe-west3 \
    --vpc default \
    --cloud=gce \
    --networking calico \
    --topology private
```
with kops 1.18.2 and still got the same error:
spec.subnets[1].region: Required value: region must be specified for GCE subnets
