### ISSUE TITLE
Specify etcd-manager version in kops config

### ISSUE THREAD

**Issue by carpenterm** [kubernetes/kops#8627]
We need to rebuild etcd-manager in order to remove critical vulnerabilities in the publicly released images for security and compliance reasons. Having the tag hard coded in the kops code makes this really difficult to do well, as we have to use the same tag each time which leads to a lot of confusion around what has/hasn't been pushed, or we need to rebuild kops every time we update the code which is impractical.

Being able to specify the etcd-manager image tag in the kops configuration file would solve this.

**Comment by zetaab** [comment]
you can override etcd-manager with ENV variable AFAIK

**Comment by carpenterm** [comment]
Excellent, that's exactly what I was after - thank you!
