### ISSUE TITLE
Backport Launch Template Volume Tagging

### ISSUE THREAD

**Issue by john-delivuk** [kubernetes/kops#8664]
Volume tagging in launch templates has been a requested feature for [years](https://github.com/kubernetes/kops/issues/3358), and a simple change. It would be ideal if we could backport the [changes](https://github.com/kubernetes/kops/commit/4b33efedaa9afb0e246fa8424dae93b0ce9de492) to some of the more recent kops versions like 1.16, 1.17.

**Comment by rifelpet** [comment]
Hi @john-delivuk I just opened a cherry-pick for that change into 1.17: https://github.com/kubernetes/kops/pull/8665 so once it is merged it will be a part of the next Kops 1.17 release.

**Comment by john-delivuk** [comment]
Any objection to doing 1.16.1 as well :)

**Comment by hakman** [comment]
I cherrypicked the minimum set of fixes for the direct target to 1.16 https://github.com/kubernetes/kops/pull/8806 and 1.17 https://github.com/kubernetes/kops/pull/8805.

Terraform, CloudFormation or any of the other fixes would mean bigger changes that should be tested in 1.18 beta when available.

**Comment by hakman** [comment]
Both backports are now merged.
/close
