### ISSUE TITLE
Etcd fails to mount volumes for second cluster created in Digitalocean

### ISSUE THREAD

**Issue by miron9** [kubernetes/kops#8689]
**1. What `kops` version are you running?
Version 1.15.2 (git-ad595825a)

**2. What Kubernetes version are you running?
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-12T13:43:46Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
Digitalocean

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster --cloud=digitalocean --name=test1.dev.sfo1.do.services.example.com --zones=fra1 --ssh-public-key=~/.ssh/id_rsa.pub --node-count=1 --master-count=1 --image=ubuntu-18-04-x64 --state=do://test1.dev.sfo1-state-store --networking=calico --yes
**5. What happened after the commands executed?**

**6. What did you expect to happen?**
kube-apiserver start and serve requests

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
https://gist.github.com/miron9/e4a28dcdb34b3f6ee8825c35b6d5a515#file-kops-v10-out-txt

**9. Anything else do we need to know?**
By a quick scan of logs it seems to be missing (at least in logs) name of the cluster for which the volume is being serched.
This is an excerpt of etcd.log from master node:

I0306 12:27:27.246529    7097 mounter.go:302] Currently attached volumes: [0xc00011e000]
I0306 12:27:27.246689    7097 mounter.go:64] Master volume "dedb4daf-5fa1-11ea-b120-0a58ac14d078" is attached at "/dev/disk/by-id/scsi-0DO_Volume_kops-1-etcd-main-test1-dev-fra1-do-services-example-com"
I0306 12:27:27.246924    7097 mounter.go:78] Doing safe-format-and-mount of /dev/disk/by-id/scsi-0DO_Volume_kops-1-etcd-main-test1-dev-fra1-do-services-example-com to /mnt/master-dedb4daf-5fa1-11ea-b120-0a58ac14d078
W0306 12:27:27.247226    7097 mounter.go:82] unable to mount master volume: "error checking for device \"/dev/disk/by-id/scsi-0DO_Volume_kops-1-etcd-main-test1-dev-fra1-do-services-example-com\": stat /rootfs/dev/disk/by-id/scsi-0DO_Volume_kops-1-etcd-main-test1-dev-fra1-do-services-example-com: no such file or directory"
I0306 12:27:27.247471    7097 boot.go:49] waiting for volumes
I0306 12:28:27.775386    7097 volumes.go:139] Iterating DO Volume with name=kops-1-etcd-events-test1-dev-fra1-do-services-example-com and ID=df08089b-5fa1-11ea-9736-0a58ac14d0d9
I0306 12:28:27.775409    7097 volumes.go:139] Iterating DO Volume with name=kops-1-etcd-events-test1-dev-sfo1-do-services-example-com and ID=e2a551b1-5fa1-11ea-9e33-0a58ac14d123
I0306 12:28:27.775413    7097 volumes.go:139] Iterating DO Volume with name=kops-1-etcd-main-test1-dev-fra1-do-services-example-com and ID=dedb4daf-5fa1-11ea-b120-0a58ac14d078
I0306 12:28:27.775418    7097 volumes.go:164] Found a matching nameTag=etcdCluster-main for cluster key=main with etcd cluster name = etcd and k8s cluster name=
I0306 12:28:27.775425    7097 volumes.go:179] Matching DO Volume found with name=kops-1-etcd-main-test1-dev-fra1-do-services-example-com ID=dedb4daf-5fa1-11ea-b120-0a58ac14d078 etcdname=etcd-main mountname=master-dedb4daf-5fa1-11ea-b120-0a58ac14d078
I0306 12:28:27.775429    7097 volumes.go:139] Iterating DO Volume with name=kops-1-etcd-main-test1-dev-sfo1-do-services-example-com and ID=e2c2a49e-5fa1-11ea-b120-0a58ac14d078
I0306 12:28:27.775440    7097 volumes.go:164] Found a matching nameTag=etcdCluster-main for cluster key=main with etcd cluster name = etcd and k8s cluster name=
I0306 12:28:27.775444    7097 volumes.go:179] Matching DO Volume found with name=kops-1-etcd-main-test1-dev-sfo1-do-services-example-com ID=e2c2a49e-5fa1-11ea-b120-0a58ac14d078 etcdname=etcd-main mountname=master-e2c2a49e-5fa1-11ea-b120-0a58ac14d078
I0306 12:28:27.775451    7097 mounter.go:302] Currently attached volumes: [0xc00011e000]
I0306 12:28:27.775458    7097 mounter.go:64] Master volume "dedb4daf-5fa1-11ea-b120-0a58ac14d078" is attached at "/dev/disk/by-id/scsi-0DO_Volume_kops-1-etcd-main-test1-dev-fra1-do-services-example-com"
I0306 12:28:27.775496    7097 mounter.go:78] Doing safe-format-and-mount of /dev/disk/by-id/scsi-0DO_Volume_kops-1-etcd-main-test1-dev-fra1-do-services-example-com to /mnt/master-dedb4daf-5fa1-11ea-b120-0a58ac14d078
W0306 12:28:27.775515    7097 mounter.go:82] unable to mount master volume: "error checking for device \"/dev/disk/by-id/scsi-0DO_Volume_kops-1-etcd-main-test1-dev-fra1-do-services-example-com\": stat /rootfs/dev/disk/by-id/scsi-0DO_Volume_kops-1-etcd-main-test1-dev-fra1-do-services-example-com: no such file or directory"
I0306 12:28:27.775527    7097 boot.go:49] waiting for volumes

**Comment by zetaab** [comment]
@srikiz could you help here? This looks like etcd-manager issue (maybe also kops configuration issue)

**Comment by srikiz** [comment]
@miron9 - may I know if you are still seeing this issue? Which version of KOPS are you using?

**Comment by miron9** [comment]
> @miron9 - may I know if you are still seeing this issue? Can you try with the latest KOPS version v1.17?

Really sorry but I had to get this DigitalOcena cluster working and so had to move to managed service. The version was1.15.2 as in bug report.
Kind regards

**Comment by srikiz** [comment]
I tried this with the same version (v1.15.2) in both fra1 and tor1 regions and it seems to be working as expected. Unable to reproduce it, good to close the issue.

```
./kops version
Version 1.15.2 (git-ad595825a)
```

```
$ kubectl get nodes -o wide
NAME         STATUS   ROLES    AGE   VERSION    INTERNAL-IP   EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
10.114.0.2   Ready    master   27m   v1.15.12   10.114.0.2    **********    Ubuntu 18.04.3 LTS   4.15.0-66-generic   docker://18.6.3
10.114.0.3   Ready    node     25m   v1.15.12   10.114.0.3    **********   Ubuntu 18.04.3 LTS   4.15.0-66-generic   docker://18.6.3
$ kubectl get nodes -o wide --show-labels
NAME         STATUS   ROLES    AGE   VERSION    INTERNAL-IP   EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME   LABELS
10.114.0.2   Ready    master   27m   v1.15.12   10.114.0.2    ************   Ubuntu 18.04.3 LTS   4.15.0-66-generic   docker://18.6.3     beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=s-2vcpu-2gb,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=fra1,kops.k8s.io/instancegroup=master-fra1,kubernetes.io/arch=amd64,kubernetes.io/hostname=10.114.0.2,kubernetes.io/os=linux,kubernetes.io/role=master,node-role.kubernetes.io/master=
10.114.0.3   Ready    node     26m   v1.15.12   10.114.0.3    ************   Ubuntu 18.04.3 LTS   4.15.0-66-generic   docker://18.6.3     beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=s-2vcpu-4gb,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=fra1,kops.k8s.io/instancegroup=nodes,kubernetes.io/arch=amd64,kubernetes.io/hostname=10.114.0.3,kubernetes.io/os=linux,kubernetes.io/role=node,node-role.kubernetes.io/node=
 

```

**Comment by srikiz** [comment]
FYI @miron9 @timoreimann
