### ISSUE TITLE
Add a get bastion call for a cluster

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#869]
In private networking we need a way to get the ELB for the bastion server.

**Comment by kris-nova** [comment]
@alok87 Let me know if you have any questions with this feature..

Cheers!

**Comment by chrislovecnm** [comment]
I am on the fence about this feature btw. We don't have a get call for non private servers ...

**Comment by kris-nova** [comment]
I am wondering if https://github.com/kubernetes/kops/pull/906 could address this concern? I am leaning more and more **away** from this feature TBH..

**Comment by justinsb** [comment]
We now have a DNS name.  I believe that is sufficient?  We also have `kops toolbox dump` which I think dumps ELBs, though we need to start making it more queryable.

Closing, but do reopen / comment / open a new issue if we figure out something that is missing.
