### ISSUE TITLE
Getting timeouts attaching pvc volumes

### ISSUE THREAD

**Issue by aliakhtar** [kubernetes/kops#872]
I have a petset that creates 3 replicas.

Everything has been running fine for weeks, however today when I ran `kubectl get po` i saw that one of the 3 replicas had been restarted:

```
cassandra-0                      1/1       Running             0          32d
cassandra-1                      1/1       Running             1          32d
cassandra-2                      0/1       ContainerCreating   0          11h
```

The pods -0 and -1 have both been up for 32d but -2 has been restarted.

1) Is it possible to find out why -2 was restarted? `kubectl logs cassandra-2 -p` gives `Error from server: previous terminated container "cassandra" in pod "cassandra-2" not found`

2) When I describe this container, I see:

```
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----					-------------	--------	------		-------
  11h		11s		302	{kubelet ip-172-20-36-9.ec2.internal}			Warning		FailedMount	Unable to mount volumes for pod "cassandra-2_default(de4f224a-a86d-11e6-acb4-128cd88b1fb6)": timeout expired waiting for volumes to attach/mount for pod "cassandra-2"/"default". list of unattached/unmounted volumes=[cassandra-data]
  11h		11s		302	{kubelet ip-172-20-36-9.ec2.internal}			Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "cassandra-2"/"default". list of unattached/unmounted volumes=[cassandra-data]
```

Any ideas what to do here?

**Comment by chrislovecnm** [comment]
So this is not smell like a kops issue, and I recommend that you file an issue in the main repo, or reach out on slack to #kubernetes-users channel. Slack is probably your best option.
