### ISSUE TITLE
Support Bottlerocket In AWS

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#8723]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

AWS just announced a new container-focused Linux distribution. We should consider adding support for it in Kops

https://aws.amazon.com/bottlerocket/

**2. Feel free to provide a design supporting your feature request.**

**Comment by jmcdonagh** [comment]
This would be great

**Comment by rifelpet** [comment]
/remove-lifecycle stale

I'm picking this back up and getting the PR ready for testing again. The current blocker is that because bottlerocket's node bootstrapping relies on the CSR flow, we need a controller to approve the CSRs for kubelet server certificates which [can't be auto-approved](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#certificate-rotation) in core components.

**Comment by oded-dd** [comment]
This PR is really important for us. Can it be merged?

**Comment by olemarkus** [comment]
This is far from a working state. I would be interested in why this is important to you.

The main challenge is how we can support kops features on a distro we cannot really configure/install things on.

**Comment by olemarkus** [comment]
Why would it be problematic? Can you elaborate?

**Comment by oded-dd** [comment]
bottlerocket supports FIPS 140-2. This is a security standard which becomes more and more common and is a requirement for SaaS providers (like us) by many customers (mostly Enterprise). bottlerocket also is about to become the official image used by AWS instead of Amazon linux2.

**Comment by olemarkus** [comment]
I don't feel you are answering the question. The default kOps image is Ubuntu LTS, which is also FIPS 140-2 certified.
Why would also the kOps project care about what image EKS is using? EKS has always had the strategy of using EKS specific images, while kOps project has moved away from that. You may also conflate "default" with "supported". I doubt AL2 or ubuntu images for EKS is going away either. There are too many companies needing more customisation than what bottlerocket allows for.

**Comment by drpdishant** [comment]
@olemarkus I am fan of bottlerocket or AWS, but I think supporting Container Linux for Kubernetes Instances has advantage in terms of resource utilization, and startup and upgrade times for Cluster. I have been using both bottlerocket and AL2 images, and have been seeing significant difference in resource footprints of nodes. The same cluster which would run around 10+ nodes with AL2 Image, would run just 5 nodes. Reducing the cost significantly. I agree with you that container linux limits the customization, but for those who don't need that, container linux makes sense.   If not bottlerocket, there are options available such as RancherOS, Fedora Core OS etc.

**Comment by olemarkus** [comment]
We don't use Ubuntu to support customization as such. We need an OS where we can install the necessary software. This is not possible on Bottlerocket.

While AL2 may be a bit heavy, the Ubuntu minimal server images are lighter, and we also support Flatcar.
