### ISSUE TITLE
Adding disk space to a cluster - Questions

### ISSUE THREAD

**Issue by aliakhtar** [kubernetes/kops#873]
1) When I do `kops edit ig nodes`, I don't see any field there for editing the storage / disk space of the cluster. Which field do I need to add to change the disk space? Perhaps this should be documented somewhere.

2) How can I edit this using a saner editor than whichever editor this opens, which does not respond to ctrl + c? nano will be fine.

3) After I do this, I understand that this will restart the cluster and recreate all the deployments. What will this do for the pvcs? I've had terrible issues with deployments failing because pvcs were still attached or were getting timeouts.

Can I be confident that after doing this, I will not get failed deployments due to pvcs still being attached or getting other pvc timeouts? 

My cluster is on AWS.

**Comment by chrislovecnm** [comment]
PVC timeouts have nothing to do with base disk size of a node / minion. 

Yes we need to document how to change disk sizing, and how the default editor works.

**Comment by aliakhtar** [comment]
Can you answer the questions for now?

**Comment by chrislovecnm** [comment]
Would have answered if I had the answer off of the top of my head

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#changing-the-root-volume-size-or-type I assume is the droid you are looking for?  

Now ... time for a customer service survey 😀 

1. How can we organize the docs better?  
2. What would have stopped you from opening an issue?

Now for an ask

Can you help us with any of your recommendations?  I understand if the answer is no, but please do share how to improve.

**Comment by aliakhtar** [comment]
I actually did see that link before, I read it more carefully again and saw the `rootVolumeSize` option, so that one's on me not RTFMing properly, sorry. (I'm guessing the size given is in GB)

How can I use nano editor to edit the ig, and, what will this exactly do - will it restart all deployments? Will it correctly assign my pvc to their deployments?

I'll be happy to send a PR to the docs w/ answers to these questions added once I get them answered.

**Comment by justinsb** [comment]
If you `export EDITOR` you change the editor, same as git or kubectl.

When you `kops rolling-update`, all your instances will be terminated, and new ones will be launched with bigger root volumes.  PVs & PVCs are completely unrelated, and should reattach to the new nodes once the pods are scheduled.

**Comment by chrislovecnm** [comment]
Thanks for the offer of update by the docs!

**Comment by chrislovecnm** [comment]
Closing as we have the docs
