### ISSUE TITLE
Using Flannel as a CNI provider

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#876]
Until this gets resolved, we cannot use the provider https://github.com/coreos/flannel/issues/545

**Comment by hsyed** [comment]
When I gave the flannel addon a try -- kind of froze the cluster if I can remember correctly -- it also refused to uninstall. By this I mean I removed the daemonset manifest but the pods would not die even if I tried to kill them individually.

**Comment by chrislovecnm** [comment]
Not ready IMHO.

**Comment by chrislovecnm** [comment]
I am going to close this out. At this point flannel does not support a ds install.
