### ISSUE TITLE
unexpected error during validation: error listing nodes: Get https://api.xxxx.xxxx.xxx.xx/api/v1/nodes: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by smaillns** [kubernetes/kops#8765]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.16.0
**2. What Kubernetes version are you running?**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c1
2ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"d
arwin/amd64"}
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops validate cluster
**5. What happened after the commands executed?**
Validating cluster clustername.xxxx.xxxx.xx
unexpected error during validation: error listing nodes: Get https://api.xxxxxx.xxxx.xxxx.xx/api/v1/nodes: net/http: TLS handshake timeout
**6. What did you expect to happen?**
Validating cluster
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` **

> apiVersion: kops.k8s.io/v1alpha2
> kind: Cluster
> metadata:
>   creationTimestamp: "2020-03-17T19:01:02Z"
>   name: clustername.xxxxx.xxxxx.xx
> spec:
>   api:
>     loadBalancer:
>       type: Public
>   authorization:
>     rbac: {}
>   channel: stable
>   cloudProvider: aws
>   configBase: s3://xxxxxx-kops-bucket/clustername.xxxxx.xxxxx.xx
>   dnsZone: kops.ucci.uk
>   etcdClusters:
>   - cpuRequest: 200m
>     etcdMembers:
>     - instanceGroup: master-eu-west-3a
>       name: a
>     memoryRequest: 100Mi
>     name: main
>     version: 3.2.24
>   - cpuRequest: 100m
>     etcdMembers:
>     - instanceGroup: master-eu-west-3a
>       name: a
>     memoryRequest: 100Mi
>     name: events
>     version: 3.2.24
>   iam:
>     allowContainerRegistry: true
>     legacy: false
>   kubelet:
>     anonymousAuth: false
>   kubernetesApiAccess:
>   - 0.0.0.0/0
>   kubernetesVersion: 1.16.7
>   masterPublicName: api.clustername.xxxxx.xxxxx.xx
>   networkCIDR: 172.20.0.0/16
>   networking:
>     calico:
>       majorVersion: v3
>   nonMasqueradeCIDR: 100.64.0.0/10
>   sshAccess:
>   - 0.0.0.0/0
>   subnets:
>   - cidr: 172.20.32.0/19
>     name: eu-west-3a
>     type: Private
>     zone: eu-west-3a
>   - cidr: 172.20.0.0/22
>     name: utility-eu-west-3a
>     type: Utility
>     zone: eu-west-3a
>   topology:
>     bastion:
>       bastionPublicName: bastion.clustername.xxxxx.xxxxx.xx
>     dns:
>       type: Public
>     masters: private
>     nodes: private
> 
> ---
> 
> apiVersion: kops.k8s.io/v1alpha2
> kind: InstanceGroup
> metadata:
>   creationTimestamp: "2020-03-17T19:01:03Z"
>   labels:
>     kops.k8s.io/cluster: clustername.xxxxx.xxxxx.xx
>   name: bastions
> spec:
>   image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
>   machineType: t2.micro
>   maxSize: 1
>   minSize: 1
>   nodeLabels:
>     kops.k8s.io/instancegroup: bastions
>   role: Bastion
>   subnets:
>   - utility-eu-west-3a
> 
> ---
> 
> apiVersion: kops.k8s.io/v1alpha2
> kind: InstanceGroup
> metadata:
>   creationTimestamp: "2020-03-17T19:01:03Z"
>   labels:
>     kops.k8s.io/cluster: clustername.xxxxx.xxxxx.xx
>   name: master-eu-west-3a
> spec:
>   image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
>   machineType: t2.micro
>   maxSize: 1
>   minSize: 1
>   nodeLabels:
>     kops.k8s.io/instancegroup: master-eu-west-3a
>   role: Master
>   subnets:
>   - eu-west-3a
> 
> ---
> 
> apiVersion: kops.k8s.io/v1alpha2
> kind: InstanceGroup
> metadata:
>   creationTimestamp: "2020-03-17T19:01:03Z"
>   labels:
>     kops.k8s.io/cluster: clustername.xxxxx.xxxxx.xx
>   name: nodes
> spec:
>   image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
>   machineType: t2.micro
>   maxSize: 2
>   minSize: 2
>   nodeLabels:
>     kops.k8s.io/instancegroup: nodes
>   role: Node
>   subnets:
>   - eu-west-3a

**9. Anything else do we need to know?**
Just after creating the kops cluster the command work well, but after a period of time it gives this issue. Note that **kubect get nodes**  gives the following error message too `Unable to connect to the server: EOF`

**Comment by olemarkus** [comment]
Did this get resolved? As far as I can tell there is nothing specifically wrong in that cluster setup.
