### ISSUE TITLE
Certificate renewal

### ISSUE THREAD

**Issue by fmmatthewzeemann** [kubernetes/kops#8774]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Add option to kops that renews certificates during an upgrade similar to kubeadm which can renew all the certificates during control plane upgrade.

**2. Feel free to provide a design supporting your feature request.**
Add option `--certificate-renewal` to perform renewal of certificates when upgrading the cluster (hopefully with no service downtime on workers).

```
kops upgrade cluster kubernetes-cluster.example.com --yes --state=s3://kops-state-1234 --certificate-renewal=true
```

**Comment by olemarkus** [comment]
So at least kube apiserver and admin certs now rotate more frequently (by default). There will most likely be more work on this for the other certs in the coming kops versions.
/remove-lifecycle stale

**Comment by johngmyers** [comment]
Actually, all the client and server certificates rotate on node replacement for k8s 1.19+ on AWS.

**Comment by olemarkus** [comment]
/remove-lifecycle rotten

I also have #10516 that should fix the CA cert

**Comment by johngmyers** [comment]
CA rotation is functional and documented in 1.22. The remaining work is to get rolling update to mark worker nodes as NeedsUpdate in all cases following the promotion of a new CA.
