### ISSUE TITLE
kops creating POD sucsussfully but not node  

### ISSUE THREAD

**Issue by SHUFIL** [kubernetes/kops#8778]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.14.0
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.14

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
install metric-server and deployment with autoscling
**5. What happened after the commands executed?**
scaling only POD not node
**6. What did you expect to happen?**
Need to scal node if we get Insufficient cpu error
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by SHUFIL** [comment]
I have successfully created new POD using by autocaling as per the load, but all the pod is creating in same node, so i getting below error.

`1 Insufficient cpu, 1 node(s) had taints that the pod didn't tolerate`
How to resole this issue, what is best practise ?, as per this error we all knows it is needed one more instace for starting the new pod.

**Comment by olemarkus** [comment]
This is outside of the scope of kops, so closing this one.
Have a look at https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler for how to dynamically change cluster size based on changing resource requirements.

/close
