### ISSUE TITLE
kops: Very slow internal networking with timeouts on AWS C2

### ISSUE THREAD

**Issue by nlykkei** [kubernetes/kops#8781]
**0. Problem.**

I'm learning Kubernetes using `kops` on AWS C2. I've configured a small cluster, consisting of a single master node and two worker nodes, using the official `kops` documentation on how to set up a cluster on AWS.

Since I'm using `kops` 1.16.0, I've configured the cluster using gossip DNS.

Inter-pod networking is very slow with timeouts all the time. DNS is barely functional, and `netcat` connections between pods either timeout or take very long to succeed. Also, NodePort services timeout most of the time, when connection from outside the cluster.

I'm only running six pods and a single service, so I don't expect my C2 instances to be too small? Also, I don't think gossip DNS may be the problem, since networking fails using IP addresses too.

How can I configure the cluster to make networking functional without timeouts or lag?

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.16.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.15

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create cluster --cloud=aws --state=s3://ctf.k8s.io --master-count=1 --master-size=t3a.micro --node-count=2 --node-size=t3a.micro --zones=eu-central-1c --associate-public-ip=true --ssh-public-key=id_rsa.pub --vpc=vpc-0ee6b4bf9e8faaf23 --subnets=subnet-0d1019cf8f9344bd5 --name=ctf.k8s.local --yes

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-03-21T19:01:25Z"
  name: ctf.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://ctf.k8s.io/ctf.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.7
  masterPublicName: api.ctf.k8s.local
  networkCIDR: 172.30.0.0/16
  networkID: vpc-0ee6b4bf9e8faaf23
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.30.0.0/16
    id: subnet-0d1019cf8f9344bd5
    name: eu-central-1c
    type: Public
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-21T19:01:26Z"
  labels:
    kops.k8s.io/cluster: ctf.k8s.local
  name: master-eu-central-1c
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3a.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  subnets:
  - eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-21T19:01:26Z"
  labels:
    kops.k8s.io/cluster: ctf.k8s.local
  name: nodes
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3a.micro
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1c

**Comment by hakman** [comment]
Hi @nlykkei. I think you meant AWS EC2.

The `t3a.micro` instances are extremely small, especially for masters. AMD instances are also slower. I would recommend to use `t3.medium` at least and retry. Also replace `kubenet` with `calico` or some other network plugin.

That being said, if this doesn't work or you want to stick with `t3a.micro`, you should take a look at https://k3s.io.

**Comment by nlykkei** [comment]
Thank you @hakman.
Can you say, why you want me to replace `kubetnet` with `calico`?
In my case, I resolved the performance issue by letting `kops` configure and use its own VPC and subnet by removing the following lines from the command:
`--vpc=vpc-0ee6b4bf9e8faaf23 --subnets=subnet-0d1019cf8f9344bd5`
Do you have any idea, why using existing VPC and subnet might slow down `kops` so drastically?

**Comment by hakman** [comment]
Kubenet is a very basic network plugin and usually harder to debug what happens with it:
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#kubenet

Glad you managed to solve your issue. Using an existing VPC and subnet is not slow in general. It is quite used in production setups. My guess is that the subnet you used was somehow miss-configured.

**Comment by olemarkus** [comment]
Using existing subnet with the kubenet cni is not a good idea since kubenet modifies the subnet route tables directly. Could be that your problems comes from that. If you want to reuse subnets, you definitely want to go for one of the other CNIs.

**Comment by nlykkei** [comment]
But why don’t it work, if kubenet is able to modify the subnet route
tables? Then the routes should work?

Indeed, it worked fine, when using a new subnet.

**Comment by olemarkus** [comment]
It is hard to say without knowing more details. But ...
* Kubenet has its requirement to how the subnet is configured
* Kubernetes has other requirements, especially wrt tags and such to understand where to put load balancers etc.

Kubenet does anyways not support shared subnets. Nor does it support private subnets, something that I would recommend for a production setup.

**Comment by nlykkei** [comment]
In my case, kubenet was deployed to an existing subnet with lots of other
VMs.

Why do you mention that Kubernetes has other requirements? Don’t you mean
kops? Kubenetes by default has no requirements wrt. labels (tags?)

**Comment by olemarkus** [comment]
tags. E.g the subnet used for ELBs need `kubernetes.io/role/elb`. Kops do need some tags when kops is managing the subnet, but not when you provide it an existing one (although kops will add tags to it too).

**Comment by ksummersill** [comment]
I am really curious about this. I am getting timeout (503/504) errors within my API Gateway when i am trying to hit a domain. I know the deployments and services are good. However i did create my cluster with Calico, Gossip DNS, and i did specify a VPC ID. So i how can i troubleshoot this on AWS?

**Comment by olemarkus** [comment]
If the cluster is fine, this is probably not a kops issue. You should check API gateway logs etc to see what is going on. If something related to kops was the culprit, you'd see general connectivity issues, dns lookup issues etc. Hard to do any kind of debugging here without more knowledge about the cluster, what is running there and how your components are set up.
