### ISSUE TITLE
Enable anonymous authentication for kube-apiserver

### ISSUE THREAD

**Issue by nlykkei** [kubernetes/kops#8784]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I want to enable anonymous authentication for the `kube-apiserver`, i.e. provide an option of `--anonymous-auth=true`

Currently, the `kube-apiserver` runs as follows:

`/usr/local/bin/kube-apiserver --allow-privileged=true --anonymous-auth=false --apiserver-count=1 --authorization-mode=RBAC --basic-auth-file=/srv/kubernetes/basic_auth.csv --bind-address=0.0.0.0 --client-ca-file=/srv/kubernetes/ca.crt`

How can I enable anonymous authentication for `kube-apiserver`?

**Comment by olemarkus** [comment]
You can read about this here: https://kops.sigs.k8s.io/security/#kubelet-api
