### ISSUE TITLE
Control the Desired Number of Machines in Auto Scaling in Kops

### ISSUE THREAD

**Issue by flmmartins** [kubernetes/kops#8786]
Hello all,

Recently I wanted to downscale my cluster.

**Current State in AWS Scaling**
Desired number of nodes: 3
Min number of nodes: 3
Max number of nodes: 3

**What I wanted to do**
Desired number of nodes: 2
Min number of nodes: 2
Max number of nodes: 3

I wanted to bring down the Min & Desired. So I edit my IG to MinSize: 2, MaxSize: 3 and configured the below

**What Kops did after I edited minSize to 2**
Desired number of nodes: 3
Min number of nodes: 2
Max number of nodes: 3

As you can see it doesn't change the Desired number of machines in AWS.

Can we add a variable to also reflect the Desired Number?

Thanks,

**Comment by olemarkus** [comment]
The desired number shouldn't be changed by kops. Usually one use things like cluster autoscaler to set that property.

**Comment by flmmartins** [comment]
Yes, true. We want to set this up but decided to give a test with manual scaling first.

**Comment by olemarkus** [comment]
Anything outside of kops can change this flag though. For example by just using the AWS API/CLI/Console directly.

**Comment by olemarkus** [comment]
Closing since this is out of the scope for kops
/close
