### ISSUE TITLE
Weave issues with '--topology private'

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#879]
Hi, all we are experiencing issues with routing and bridging where we are see CPUs that are pegged.  I will get more information on Monday, but literally networking loops are causing CPUs spiked at 100%

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/issues/903

**Comment by bboreham** [comment]
I think we understand the chain of causes for this now:

1. Your machines do not have `ethtool`.  This is noted as a requirement [here](https://github.com/kubernetes/kubernetes/issues/26093)
2. An [unfortunate feature of `kubelet`](https://github.com/kubernetes/kubernetes/issues/19766) then sets hairpin mode on every interface it can see
3. Weave Net sees packets looped round which it isn't expecting.
4. Weave Net creates flow rules that cause more loops https://github.com/weaveworks/weave/issues/2650

Breaking the chain at step 1 and rebooting everything will probably make your problem go away.

**Comment by luxas** [comment]
I actually think https://github.com/kubernetes/kubernetes/pull/30356 will fix this, but waiting on review/full approval

**Comment by bboreham** [comment]
@luxas indeed, the chain can be broken at any step; I was merely picking on the one that @chrislovecnm could deploy fastest.

**Comment by chrislovecnm** [comment]
Closing this out
