### ISSUE TITLE
Did not find API endpoint for gossip hostname; may not be able to reach cluster

### ISSUE THREAD

**Issue by pawanvivekananda** [kubernetes/kops#8791]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.16.0 (git-4b0e62b82)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server api.parrotvpn.com was refused - did you specify the right host or port?

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster \
--state=${KOPS_STATE_STORE} \
--node-count=3 \
--master-size=t3.large \
--node-size=t3.large \
--zones=ap-south-1a \
--name=${KOPS_CLUSTER_NAME} \
--dns private \
--master-count 1 \
--vpc=vpc-0f0cde6701c3a2ef5 \
--associate-public-ip=false \
--subnets subnet-02f3d5d8ac851f4dd

kops update cluster --yes

**5. What happened after the commands executed?**
I0325 02:31:49.431753   28990 dns.go:94] Private DNS: skipping DNS validation
I0325 02:31:49.778336   28990 executor.go:103] Tasks: 0 done / 82 total; 43 can run
I0325 02:31:50.496050   28990 vfs_castore.go:729] Issuing new certificate: "etcd-peers-ca-main"
I0325 02:31:50.744211   28990 vfs_castore.go:729] Issuing new certificate: "etcd-peers-ca-events"
I0325 02:31:51.175408   28990 vfs_castore.go:729] Issuing new certificate: "etcd-manager-ca-events"
I0325 02:31:51.273814   28990 vfs_castore.go:729] Issuing new certificate: "ca"
I0325 02:31:51.797945   28990 vfs_castore.go:729] Issuing new certificate: "etcd-clients-ca"
I0325 02:31:51.895361   28990 vfs_castore.go:729] Issuing new certificate: "apiserver-aggregator-ca"
I0325 02:31:52.088246   28990 vfs_castore.go:729] Issuing new certificate: "etcd-manager-ca-main"
I0325 02:31:52.244744   28990 executor.go:103] Tasks: 43 done / 82 total; 21 can run
I0325 02:31:53.410797   28990 vfs_castore.go:729] Issuing new certificate: "kops"
I0325 02:31:53.682337   28990 vfs_castore.go:729] Issuing new certificate: "kubecfg"
I0325 02:31:53.780679   28990 vfs_castore.go:729] Issuing new certificate: "apiserver-aggregator"
I0325 02:31:53.976148   28990 vfs_castore.go:729] Issuing new certificate: "master"
I0325 02:31:54.514294   28990 vfs_castore.go:729] Issuing new certificate: "kubelet-api"
I0325 02:31:54.738267   28990 vfs_castore.go:729] Issuing new certificate: "apiserver-proxy-client"
I0325 02:31:55.240618   28990 vfs_castore.go:729] Issuing new certificate: "kubelet"
I0325 02:31:55.301603   28990 vfs_castore.go:729] Issuing new certificate: "kube-scheduler"
I0325 02:31:55.699079   28990 vfs_castore.go:729] Issuing new certificate: "kube-controller-manager"
I0325 02:31:55.857103   28990 vfs_castore.go:729] Issuing new certificate: "kube-proxy"
I0325 02:31:56.001447   28990 executor.go:103] Tasks: 64 done / 82 total; 16 can run
I0325 02:31:56.153916   28990 launchconfiguration.go:375] waiting for IAM instance profile "masters.parrotvpn.com" to be ready
I0325 02:31:56.158099   28990 launchconfiguration.go:375] waiting for IAM instance profile "nodes.parrotvpn.com" to be ready
I0325 02:32:06.451764   28990 executor.go:103] Tasks: 80 done / 82 total; 2 can run
I0325 02:32:06.956555   28990 executor.go:103] Tasks: 82 done / 82 total; 0 can run
I0325 02:32:06.956880   28990 dns.go:155] Pre-creating DNS records
I0325 02:32:08.621995   28990 update_cluster.go:305] Exporting kubecfg for cluster
W0325 02:32:08.672511   28990 create_kubecfg.go:76] Did not find API endpoint for gossip hostname; may not be able to reach cluster
kops has set your kubectl context to parrotvpn.com

Cluster is starting.  It should be ready in a few minutes.

Suggestions:
 * validate cluster: kops validate cluster
 * list nodes: kubectl get nodes --show-labels
 * ssh to the master: ssh -i ~/.ssh/id_rsa admin@api.parrotvpn.com
 * the admin user is specific to Debian. If not using Debian please use the appropriate user based on your OS.
 * read about installing addons at: https://github.com/kubernetes/kops/blob/master/docs/operations/addons.md.

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-03-25T02:31:31Z"
  name: parrotvpn.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://parrot-kops-state-store/parrotvpn.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.7
  masterPublicName: api.parrotvpn.com
  networkCIDR: 10.0.0.0/16
  networkID: vpc-0f0cde6701c3a2ef5
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.0.0/24
    id: subnet-02f3d5d8ac851f4dd
    name: ap-south-1a
    type: Public
    zone: ap-south-1a
  topology:
    dns:
      type: Private
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-25T02:31:31Z"
  labels:
    kops.k8s.io/cluster: parrotvpn.com
  name: master-ap-south-1a
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-south-1a
  role: Master
  subnets:
  - ap-south-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-25T02:31:31Z"
  labels:
    kops.k8s.io/cluster: parrotvpn.com
  name: nodes
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-south-1a

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I have updated route53 dns with api.parrotvpn.com with master node ip address since it was not getting updated.

When i ssh to master,  
netstat  -ntpl

(No info could be read for "-p": geteuid()=1000 but you should be root.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::111                  :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   

I dont see any process running

**Comment by nirupbbnk** [comment]
In Route53 service check record "api.internal.<cluster Name>" weather it is pointed to master IP.

**Comment by huanggze** [comment]
Hi, @pawanvivekananda did u manage to solve it? i just have the error message when export kubeconfig after installing my cluster on aws.

**Comment by Gavin-github-user** [comment]
What is the root cause, and what is the solution? 
We are facing the same problem when using Kops to create cluster on AWS.

**Comment by StanForever** [comment]
Facing the same issue with cluster created via kops on AWS. Could someone post solution to this if they've found it? TIA!

**Comment by Baquir05** [comment]
Facing the same issue? What's the solution?
