### ISSUE TITLE
OpenStack: Add support for clouds.yaml for Swift state store

### ISSUE THREAD

**Issue by MPV** [kubernetes/kops#8793]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Most OpenStack clients support authenticating via either `OS_*` environment variables (often sourced from an `openrc` file), **_or via a `clouds.yaml` file_**.

The latter also supports defining multiple OpenStack clouds and/or regions in the same file. 

However since Kops implements the older authentication method from gophercloud (`gophercloud.AuthOptions`), it doesn't yet/automatically support newer auth methods that the newer `clientconfig.AuthOptions` supports.

I'm suggesting we simply switch to this newer authentication method from gophercloud that supports both `openrc` and `clouds.yaml`.

This openstack spec describes a bit more about the ongoing change from `openrc` to `clouds.yaml`: https://github.com/openstack/openstack-specs/blob/master/specs/clouds-yaml-support.rst

**2. Feel free to provide a design supporting your feature request.**

Today [we use `gophercloud.AuthOptions`](https://github.com/kubernetes/kops/blob/b2d90fd2c0e466a48ff5ebbfca472564f21b21a7/util/pkg/vfs/swiftfs.go#L168) in `util/pkg/vfs/swiftfs.go`, but my thinking is that we could switch to use [`clientconfig.ClientOpts`](https://github.com/gophercloud/utils/blob/9864b6f/openstack/clientconfig/requests.go#L39-L76) or [`clientconfig.AuthOptions`](https://github.com/gophercloud/utils/blob/9864b6f/openstack/clientconfig/requests.go#L318-L377) instead (and get support for this newer auth method).

See more about how gophercloud did this switch here: https://github.com/gophercloud/gophercloud/issues/252#issuecomment-381300656

Here's gophercloud's documentation mentioning that `clientconfig` now is the recommended way for all authentication purposes: https://pkg.go.dev/github.com/gophercloud/gophercloud?tab=doc

Here's examples of how to use clientconfig: https://pkg.go.dev/github.com/gophercloud/utils/openstack/clientconfig?tab=doc

Here's an example of how the Terraform implementation does this: https://github.com/gophercloud/utils/blob/9864b6f1f12fbbad1665b34cc1022035ae86f334/terraform/auth/config.go#L94-L151

**3. Other notes**

I believe fixing this might also help alleviate [some issues with unclear usage of `OS_*DOMAIN*` variables](https://github.com/kubernetes/kops/issues/7921#issuecomment-570701080) since [`gophercloud/utils` covers this](https://github.com/gophercloud/utils/issues/76#issuecomment-457818971) as seen [in the code here](https://github.com/gophercloud/utils/blob/9864b6f/openstack/clientconfig/requests.go#L637-L647).

For reference, I've also discovered that Kops seems to implement its own kind of not-so-documented `~/.openstack/config` configuration file ([documentation](https://github.com/kubernetes/kops/pull/6480/files), [implementation](https://github.com/kubernetes/kops/blob/3e33ac7/util/pkg/vfs/swiftfs.go#L97-L111)), but so far I assume that `clouds.yaml` doesn't fully replace that functionality.

**Comment by MPV** [comment]
Curious about your input on this @zetaab 😊

**Comment by zetaab** [comment]
Sounds good

**Comment by MPV** [comment]
I had a desire to also provide a pull request for the change, but I'm afraid my golang (go modules etc) skills aren't yet up to the task (although I saw how you did upgrade gophercloud in https://github.com/kubernetes/kops/commit/769c02f87c4959befda03e93311b200a4d813749). 

Also not sure how to test the change properly, or what kind of automated test coverage there is for `kops` + OpenStack here.

**Comment by zetaab** [comment]
deps are going to be updated in https://github.com/kubernetes/kops/pull/8884

**Comment by MPV** [comment]
@zetaab Would we maybe want/need to add https://github.com/gophercloud/utils too?

So [`gophercloud/utils/openstack/clientconfig`](https://github.com/gophercloud/utils/blob/9864b6f1f12fbbad1665b34cc1022035ae86f334/terraform/auth/config.go#L15) could be used (for the above).

**Comment by MPV** [comment]
I stopped using Kops for my OpenStack clusters, so you won’t see me creating a PR for this. I’ll leave this open in case anyone else finds this and doesn’t mind fixing this.
