### ISSUE TITLE
multiple clusters in same VPC cleanup challenge.

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#88]
Steps to reproduce:

```
kops create cluster --name=us-east-1a.domain.com -zones=us-east-1a
kops create cluster --name=us-east-1b.domain.com -zones=us-east-1b --network-cidr=172.20.0.0/16 --vpc=${VPC_ID_FROM_PREVIOUS}
# remove KubernetesCluster tag from VPC
kops delete cluster --name=us-east-1b.domain.com -zones=us-east-1b --yes
kops delete cluster --name=us-east-1a.domain.com -zones=us-east-1a --yes
```

Expected results: cluster us-east-1b and us-east-1a deleted, VPC still exists (would need manual deletion)
Found results: 1b deleted fine. 1a failed to delete due to dhcp_options still being in use:

```
dhcp-options:dopt-0e56a26a  still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
    dhcp-options:dopt-0e56a26a
```

Manually deleting the VPC works fine.

**Comment by zapman449** [comment]
Suggestion: Either amend the docs to say 'untag DHCP_Options too` or better, if the VPC doesn't have the tag, don't attempt to nuke the options.

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by blakebarnett** [comment]
re-open if needed.
