### ISSUE TITLE
multiple errors for terraform output

### ISSUE THREAD

**Issue by rfc2119** [kubernetes/kops#8814]
**1. `kops` version**
Version 1.18.0-alpha.2 (git-9b9615bf5)

**2. Kubernetes version**
> Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
U

**3. Cloud provider**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I was trying to create a local demo cluster using the command
```
kops create cluster \
    --name $NAME \
    --master-count 3 \
    --node-count 1 \
    --node-size t3a.medium \
    --master-size t3a.medium \
    --zones $ZONES \
    --master-zones $ZONES \
    --ssh-public-key "$KEY.pub" \
    --networking kubenet \
    --kubernetes-version v1.14.8 \
    --state "s3://$KOPS_STATE_BUCKET" \
    --out . \
    --target terraform
```
However, when terraform (`v0.12.24`, `provider.aws v2.55.0`) looked at the file _kubernetes.tf_, it had spit out many errors. Briefly,
1. redefinition of the attribute `tag`:
```
Error: Attribute redefined
                                                                                           
  on kubernetes.tf line 250, in resource "aws_autoscaling_group" "nodes-cluster-k8s-local":
 250:   tag = {
                                                                                           
The argument "tag" was already set at kubernetes.tf:238,3-6. Each argument may be set only once. 
```
2. the `terraform` block is treated as an argument
```
Error: Unsupported argument

  on kubernetes.tf line 805:
 805: terraform = {

An argument named "terraform" is not expected here. Did you mean to define a block of type "terraform"?
```
3. same as above for `locals` ?
```
Error: Unsupported argument                                                                 
                                                                                           
  on kubernetes.tf line 1:                                                    
   1: locals = {                                                                           
                                                                              
An argument named "locals" is not expected here. Did you mean to define a block of type "locals"?
```
4. finally, the following is a deprecation warning which can be easily removed by hand:
```    
Warning: Interpolation-only expressions are deprecated                                      
                                                                                            
  on kubernetes.tf line 94, in resource "aws_autoscaling_attachment" "master-ap-northeast-2a
-masters-cluster-k8s-local":                                                                
  94:   elb                    = "${aws_elb.api-cluster-k8s-local.id}"                     
                                                                                            
Terraform 0.11 and earlier required all non-constant expressions to be provided via interpolation syntax, but this pattern is now deprecated. To silence this warning, remove the "${ sequence from the start and the }" sequence from the end of this expression, leaving just the inner expression.  
```
**5. What happened after the commands executed?**

**6. What did you expect to happen?**
on `terraform plan`, terraform should not error

** 7. Cluster manifest **
see this [paste](https://dpaste.org/R2gq)

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I've managed to get terraform running by selecting JSON as output format for terraform. It didn't complain from _kubernetes.tf.json_ file

**Comment by rifelpet** [comment]
Terraform 0.12 support is being added in #7052 so feel free to follow that issue for updates. The JSON output feature flag will work for now but the native .tf support will be added in Kops 1.19.

/close
