### ISSUE TITLE
Kops delete cluster command should provide lifecycle-overrides option

### ISSUE THREAD

**Issue by tobernguyen** [kubernetes/kops#8823]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.17.0-beta.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I created a cluster using existing AWS Instance Profiles (https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#use-existing-aws-instance-profiles)

```
kops update cluster ${CLUSTER_NAME} --yes --lifecycle-overrides IAMRole=ExistsAndWarnIfChanges,IAMRolePolicy=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges
```

Then I tried to delete the cluster:
```
kops delete cluster --name $CLUSTER_NAME --yes
```

**5. What happened after the commands executed?**
The `kops delete cluster` command tries to delete the attached AWS Instance Profiles, IAM Roles, and IAM Policies which were managed outside kops (it were provisioned by Terraform in our project).

**6. What did you expect to happen?**
`kops delete cluster` should provide `lifecycle-overrides` option like `kops update` command so we tell kops to not delete AWS Instance Profiles, IAM Roles, and Policies.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
I don't think this is needed

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
I don't think this is needed

**9. Anything else do we need to know?**
No

**Comment by rifelpet** [comment]
/kind feature

I agree this is a gap in Kops' ability to support scenarios in which lifecycle overrides are intended.

**Comment by aramhakobyan** [comment]
+1

**Comment by aramhakobyan** [comment]
+

**Comment by h3poteto** [comment]
I can reproduce this using master `git-3eacde0212`.
At the moment, kops delete only Instance Profiles that match [this expression](https://github.com/h3poteto/kops/blob/f3f131f7453b62f5ec42ea32fa8ceec20d9e3eae/pkg/resources/aws/aws.go#L2020-L2022). Deletion of IAM Roles is [similar condition](https://github.com/h3poteto/kops/blob/f3f131f7453b62f5ec42ea32fa8ceec20d9e3eae/pkg/resources/aws/aws.go#L1942-L1944). So if I provide `masters.$CLUSTER_NAME` and `nodes.$CLUSTER_NAME` as existing Instance Profile, it will be deleted when delete cluster.

**Comment by h3poteto** [comment]
I will take this issue.

/assign

**Comment by johngmyers** [comment]
#11497 changes the logic for deleting IAM Roles from using name to using ownership tags. A similar change could be made for Instance Profiles.

**Comment by h3poteto** [comment]
@johngmyers Nice changes. #11497  will resolve a part of this issue.

>  A similar change could be made for Instance Profiles.

It's good.
But this issue proposes `lifecycle-overrides` option, which do you think is the better way?

**Comment by johngmyers** [comment]
@h3poteto I'm struggling to understand what a lifecycle-overrides option to a `delete cluster` command would mean, especially in the general case. Would we need to support giving the `--phase` flag to `delete cluster`? With which combination of flags would we want to remove the cluster from the state store?

**Comment by h3poteto** [comment]
@johngmyers I was expecting something like...
For example when I execute `kops delete cluster --lifecycle-overrides IAMRoles=Ignore`, kops deletes the cluster leaving only IAMRole. More specifically, when that option was specified, kops skips [these actions](https://github.com/kubernetes/kops/blob/d906f8312196dcac6e3c7784948f06e1b832df1b/pkg/resources/aws/aws.go#L84) in delete cluster command. 

I'm sorry, I don't know about `--phase` flag. Could you please tell me what the flag specifies?

**Comment by johngmyers** [comment]
@h3poteto perhaps you could look it up in the documentation?

**Comment by h3poteto** [comment]
@johanhubens Is this https://kops.sigs.k8s.io/cli/kops_update_cluster/#options ?

>  --phase string                  Subset of tasks to run: assets, cluster, network, security

This option is similar I expected.

**Comment by h3poteto** [comment]
I think that your suggestion

>  A similar change could be made for Instance Profiles.

is good idea. 
We can delete Instance Profiles using ownership tags with the same logic as #11497 . If it can be implemented, I think that those options are unnecessary.

**Comment by h3poteto** [comment]
I think this issue has already been resolved, so we can close this.
