### ISSUE TITLE
Exclude resources when deleting a cluster

### ISSUE THREAD

**Issue by ThelonKarrde** [kubernetes/kops#8838]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Could you please add an option to exclude some resources when you removing clusters?

Use case example:
When you need to recreate/migrate clusters, sometimes you need to leave in place IP addresses / NatGW or any other pieces of infrastructure. However, for now, the only possible way to do so is to unregister the cluster and then remove manually all resources except which you want to leave in place.

**Comment by olemarkus** [comment]
In many cases you can refer to existing resources when creating clusters, including things like subnets and gateways. To avoid kops removing something, you can remove the tags of these resources. See for example https://kops.sigs.k8s.io/run_in_existing_vpc/#shared-nat-egress

**Comment by ThelonKarrde** [comment]
Thanks!

**Comment by olemarkus** [comment]
IAM roles doesn't use tags for ownership. Tagging roles is relatively new, so we cannot necessarily rely on it.
