### ISSUE TITLE
Default to iptables legacy mode for distros with iptables 1.8+

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#8843]
Distros that package iptables 1.8+ contain 2 flavours of iptables Legacy and [NFT](https://wiki.nftables.org/wiki-nftables/index.php/Moving_from_iptables_to_nftables).

This was previously discussed in other issues also, so it's not new, but mostly a compilation of ideas and trying to move forward now that Kops 1.17 is close to release.
https://github.com/kubernetes/kops/issues/7379
https://github.com/kubernetes/kops/pull/7381

Kubernetes and the ecosystem have some auto-detection of what iptables backend is used but it is based on some other service already writing rules to one of the Legacy or NFT tables.
https://github.com/kubernetes/kubernetes/blob/master/build/debian-iptables/iptables-wrapper#L19-L21

Docker and Kubelet add iptables rules before the proxy and the network plugin get to detect what flavour to use. They do not get to decide or detect anything, but use the iptables flavour set as alternative.
There are 2 ways to set alternatives in Kops:
* additional user data
* nodeup

NodeUp wold be preferred way to set the default iptables flavour but has a big downside. It may start after Docker and, at that time, changing the default would generate issues. Having rules in both Legacy and NFT **could lead to unexpected results**.
This could still be possible by disabling Docker and containerd on boot in the default images.
https://github.com/kubernetes-sigs/image-builder/issues/128
https://github.com/kubernetes-sigs/image-builder/pull/199

One other thing to consider is that using NFT may be slower than Legacy. I did not test it but the Calico guys did:
https://youtu.be/KHMnC3kj3Js?t=771

My proposal would be to add a small script in the NodeUp firewall and try to set the default iptables flavour to Legacy. In case there are already other rules (for whatever reason) try to set it to the flavour with most rules. In many ways, this would be similar to the `iptables-wrapper` script does.

**Comment by olemarkus** [comment]
I absolutely agree that trying to do this in nodeup is best.
From what we found, a pre-installed could have a race condition with nodeup and install its rules in the nft tables. If docker was disabled on boot in the kopeio iages and brought up by nodeup, it would solve this issue.

**Comment by hakman** [comment]
I submitted a PR to disable Docker and containerd by default. This should make it possible to use NodeUp for this now.

**Comment by hakman** [comment]
This is no longer relevant as Kops is moving to Ubuntu 20.04 as default for the foreseeable future.
Ref: #9163
