### ISSUE TITLE
Kops fails to mount etcd volume for k8s 1.10 and 1.11 

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#8908]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
latest master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.10 or 1.11

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
n/a

**5. What happened after the commands executed?**
n/a

**6. What did you expect to happen?**
Cluster should start and run e2e

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
n/a

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-k8s-1-11/1249398784325062656/artifacts/3.8.78.27/protokube.log

**9. Anything else do we need to know?**
This seems to be related to https://github.com/kubernetes/kops/pull/8879.
The error seems to be:
```
W0412 18:12:27.646560    3634 volume_mounter.go:79] unable to mount master volume: "error formatting and mounting disk \"/dev/xvdu\" on \"/mnt/master-vol-00b718c718950ef02\": MountSensitive not implemented for containerized mounter"
```

**Comment by justinsb** [comment]
Thanks for fixing this @hakman .. I think #8939 should be sufficient!
