### ISSUE TITLE
Removing a specific node and the associated EC2 instance from an instance group

### ISSUE THREAD

**Issue by cw75** [kubernetes/kops#8915]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.15.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.15.3

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kubectl drain <node-name> --ignore-daemonsets --delete-local-data`
`kubectl drain <node-name> --ignore-daemonsets --delete-local-data`
`kops edit ig nodes # setting the min and max to <previous value - 1>`
`kubectl delete node <node-name>`
`kops update cluster --yes`

**5. What happened after the commands executed?**

"node-name" was successfully deleted, but an EC2 instance that is not associated with the node got terminated. As a result, `kops validate cluster` keeps failing saying "machine "node-name" has not yet joined cluster" (if the correct EC2 instance is terminated, the validation process will ignore the terminating node and the validation should succeed).

**6. What did you expect to happen?**

I expect that when running `kops update cluster --yes`, the EC2 instance that's associated with "node-name" to be terminated rather than some other random EC2 instances within my instance group.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-04-15T05:12:42Z"
  name: xxx
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://1-xxx/xxx
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.10
  masterPublicName: api.xxx
  networkCIDR: 172.20.0.0/16
  networking:
    kuberouter: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-15T05:32:25Z"
  labels:
    kops.k8s.io/cluster: xxx
  name: benchmark-instances
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.2xlarge
  maxSize: 0
  minSize: 0
  nodeLabels:
    role: benchmark
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-15T05:24:51Z"
  labels:
    kops.k8s.io/cluster: xxx
  name: ebs-instances
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: r4.large
  maxSize: 0
  minSize: 0
  nodeLabels:
    role: ebs
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-east-1a
  volumeMounts:
  - device: /dev/xvdb
    filesystem: ext4
    path: /ebs/ebs_0
  - device: /dev/xvdc
    filesystem: ext4
    path: /ebs/ebs_1
  - device: /dev/xvdd
    filesystem: ext4
    path: /ebs/ebs_2
  - device: /dev/xvde
    filesystem: ext4
    path: /ebs/ebs_3
  volumes:
  - device: /dev/xvdb
    encrypted: false
    size: 64
    type: gp2
  - device: /dev/xvdc
    encrypted: false
    size: 64
    type: gp2
  - device: /dev/xvdd
    encrypted: false
    size: 64
    type: gp2
  - device: /dev/xvde
    encrypted: false
    size: 64
    type: gp2

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-15T05:36:05Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: xxx
  name: function-instances
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: c5.2xlarge
  maxSize: 10
  minSize: 10
  nodeLabels:
    role: function
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-15T05:12:42Z"
  labels:
    kops.k8s.io/cluster: xxx
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c4.2xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-15T05:24:47Z"
  labels:
    kops.k8s.io/cluster: xxx
  name: memory-instances
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: r4.2xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    role: memory
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-15T05:12:44Z"
  labels:
    kops.k8s.io/cluster: xxx
  name: misc-instances
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    role: general
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-15T05:21:02Z"
  labels:
    kops.k8s.io/cluster: xxx
  name: routing-instances
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: r4.2xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    role: routing
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-15T05:27:08Z"
  labels:
    kops.k8s.io/cluster: xxx
  name: scheduler-instances
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: c5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    role: scheduler
  role: Node
  rootVolumeSize: 32
  subnets:
  - us-east-1a

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by olemarkus** [comment]
Basically, never run `kubectl delete node` unless you know what you are doing. In order to restore this, you have to delete the missing node using the aws api/console.

**Comment by cw75** [comment]
Thanks for your reply @olemarkus . Are you saying instead of running `kubectl delete node`, I should just remove the ec2 instance associated with the node directly using the aws api? If so, after I deleted the ec2 instance, do I also need to run `kops edit ig nodes # setting the min and max to <previous value - 1>` and `kops update cluster --yes`?

**Comment by olemarkus** [comment]
No. Just use the aws API to remove the node you removed from k8s using `kubectl delete node`.

What is it that you tried to achieve with running that command?

**Comment by cw75** [comment]
@olemarkus  Oh, since I'm using one instance group for all these nodes, I need to run `kops edit ig nodes` to change the MIN_COUNT and MAX_COUNT to <previous value - 1> and run `kops update cluster --yes` so that the cluster knows it is expecting to have 1 node less so that it won't autoscale by adding 1 extra node that I just deleted. I found that manually deleting ec2 instance leads to `kops validate cluster` failure though, as it doesn't seem to be detecting the fact that I removed the ec2 instance.

**Comment by olemarkus** [comment]
If you want to delete a very specific node, you can detach it from the AWS ASG, then set the ASG desired flag to current - 1. This is what cluster autoscalers do in order to delete specific nodes. You don't need to change the max/min count of the IG.

**Comment by cw75** [comment]
@olemarkus I ended up still having to change MIN and MAX count but detaching the node from ASG seems to work. Thanks a lot for your help!
