### ISSUE TITLE
Rotate cluster admin password steps

### ISSUE THREAD

**Issue by strangeminds** [kubernetes/kops#8919]
We have had one of our cluster admins leave and for our security and to remove their responsibility in case something happens to our clusters, we want to rotate the cluster password.  Reviewing the kops project documentation I've been able to successfully rotate the cluster password on a test cluster.  Though it seems to take a few steps and before I started on our production clusters, I wanted to check and see if I'm missing anything?

<https://github.com/kubernetes/kops/blob/master/docs/secrets.md#workaround-for-changing-secrets-with-type-secret>

This is our procedure to rotate the cluster password:

- Download the `kube` file from our kops S3 bucket - s3://kopsbucket/clustername/secrets/kube
- Generate a new kube password and base64.  I use `pwgen` to keep it simple and random.

```
pwgen 32 -1
echo -n new32characterpassword | base64
```

- Edit the `kube` file and set the new base64 password.

`{"Data":"new32characterpasswordbase64="}`

- Upload the updated `kube` file back to the S3 bucket.
- Check that kops sees the new secret.

`kops get secrets kube -oplaintext --name=clustername --state=s3://kopsbucket`

- Perform rolling-update on our cluster.

`kops rolling-update cluster --name=clustername --state=s3://kopsbucket --yes --force`

- Watching the rolling-update and we will see the `Unauthorized` start to be reported.

```
instancegroups.go:261] Cluster did not validate, will try again in "30s" until duration "15m0s" expires: error listing nodes: Get https://cluster/api/v1/nodes: EOF.
instancegroups.go:261] Cluster did not validate, will try again in "30s" until duration "15m0s" expires: error listing nodes: Unauthorized.
```

- At this time, change the password in your local `~/.kube/config`

```
- cluster:
    server: https://clustername
  name: clustername
...
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    password: new32characterpassword
    username: admin
```

- Verify the change with `kubectl config view --minify`

- Then the only way I found to continue was to `control+c` the rolling-update and start again.

`kops rolling-update cluster --name=clustername --state=s3://kopsbucket --yes --force`

**Question:** Does anyone have a better method or find an issue on how I rotated the cluster password?

**Question:** When I rotate cluster admin password, does it have to be the whole cluster or can I just rotate the masters?  I tried in on a test cluster once with `--instance-group master-us-region-1a` and it seemed to work fine, but I assume the nodes also need to be updated?

Thank you!

**Comment by olemarkus** [comment]
It is not that simple, unfortunately. If you exposed the admin user, it is probably more than just the password that could be compromised. You would need to follow this guide to rotate everything https://kops.sigs.k8s.io/rotate-secrets/

**Comment by strangeminds** [comment]
Thanks for the feedback @olemarkus 
I'll run some tests using that page.

**Comment by olemarkus** [comment]
Coincidentally, I am doing updates to that page. You may want to have a look at https://github.com/kubernetes/kops/pull/8948

**Comment by strangeminds** [comment]
That answers most of my questions.  I followed the page on a test cluster and it worked great.

Thank you!
