### ISSUE TITLE
Allow AWS EBS Volume customisations when creating clusters

### ISSUE THREAD

**Issue by Henry-Asante** [kubernetes/kops#8927]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

- I would like to set AWS EBS Volumes whiles creating clusters with Kubernetes Kops. The defaults set huge chunks of memory size, which are mostly not utilized. 
- Also, I have to pay for them, whiles not in use, I do not understand this.

**2. Feel free to provide a design supporting your feature request.**

- Since from AWS UI, we have the option to set the volume, size. I found this option quite simple to use in setting the master and slave nodes.

        --master-count 3 \
        --master-size=t2.micro \
        **--master-volume-size 5 \**
        --node-count 2 \
        --node-size=t2.micro \
        **--node-volume-size 5 \**

**Comment by hakman** [comment]
Unless I am missing something this has been an option for a very long time https://github.com/kubernetes/kops/pull/2684:
```sh
> kops create cluster --help | grep volume-size
      --master-volume-size int32         Set instance volume size (in GB) for masters
      --node-volume-size int32           Set instance volume size (in GB) for nodes
```
