### ISSUE TITLE
Feature Request: --full for kops get instancegroups

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#895]
`kops get cluster --o yaml --full` is awesome. See everything implied or inferred in the full kops spec.

kops should add `--full` to `kops get instancegroup <name> -o yaml` for the same reason.

**Comment by chrislovecnm** [comment]
I think this is a duplicate actually.  And yes we need this!

**Comment by jsenon** [comment]
Don't understand well, what kind of information we have to see with `kops get instancegroup <name> -o yaml --full`?
