### ISSUE TITLE
Require clusters use RBAC

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#8956]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Kops 1.16 includes kops-controller which uses a Role and ClusterRole, I see little benefit in continuing to support non-RBAC clusters. I dont know how feasible it would be to run kops-controller without RBAC enabled, or run a kops cluster without kops-controller (I dont think this is even possible to disable kops-controller without manually deleting the daemonset. While I suppose one could live without it's node labeling, eventually kops-controller will do more so it will become more essential to a functioning cluster).

We should consider deprecating and eventually removing support for non-RBAC clusters.

**Comment by olemarkus** [comment]
/remove-lifecycle stale
100%. Can we just add this to the 1.18 release notes?
