### ISSUE TITLE
kops 1.16.1 release shasum has changed

### ISSUE THREAD

**Issue by iMichka** [kubernetes/kops#8973]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Not applicable / 1.16.1 ?

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Not applicable

**3. What cloud provider are you using?**

Not applicable

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Not applicable

**5. What happened after the commands executed?**

Not applicable

**6. What did you expect to happen?**

Not applicable

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Not applicable

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Not applicable

**9. Anything else do we need to know?**

Hi. Homebrew maintainer here (https://github.com/Homebrew)

We noticed that the shasum of the 1.16.1 release has been changed.

I was unsure if I should open a security issue, as somebody might have had access to your GitHub and is moving tags around, which might be malicious activity. Or this is a more "retag", as some projects sometimes do, and should not be done (I do believe the latter has happened).

Anyway, this has serious security implications for the software we deliver to our users. Can you please check this as soon as possible? Thanks.

https://github.com/kubernetes/kops/archive/1.16.1.tar.gz, sha256:
Expected:720054de39fbb270397558a2eb47a8f4cbbfcacb9f792857c77d2cb32f56f764
Actual: 16e2a04e5c55c5bf587c42ce575c9bc571530aa11f81cf30611a84d96cbd7924

**Comment by mikesplain** [comment]
Thanks for reaching out @iMichka!

It looks like this is the original PR? https://github.com/Homebrew/homebrew-core/pull/53611

I don't believe our sha256 has changed but this is something we'll take a look at.  It looks like the PR wasn't created with brew-bump-pr.  Is it possible the wrong sha256 was used? (I assume no because your build wouldn't have passed at that point?)

**Comment by iMichka** [comment]
Yes, this was the original PR. I noticed the change about 11 hours later, when I did the Linux build.
The CI will download the archive for the build, and check the shasum with the one provided by the git change. So the value definitively changed at some point.

We do not have the initial file anymore, else we could do a diff between both tar files

**Comment by Bo98** [comment]
This also affected Alpine Linux.

It also affected the 1.16.0 tag. I compared the original and modified archive and found one difference:

<img width="1222" alt="Screenshot 2020-04-24 at 22 07 18" src="https://user-images.githubusercontent.com/1190754/80257214-4c265700-8678-11ea-9ec7-74066204df05.png">

The short form `%h` isn't documented to be or guaranteed to be any particular length. It seems that this length did change.

Either the long form `%H` should be used or a static source archive should be uploaded to the GitHub release. GitHub auto-generated tarballs are dynamically generated, so it depends on the version of Git in use at the time.
