### ISSUE TITLE
Error reading cluster configuration: Cluster.kops.k8s.io "cluster.app.com" not found

### ISSUE THREAD

**Issue by Henry-Asante** [kubernetes/kops#8976]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.16.0 (git-4b0e62b82)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: dial tcp 34.229.22.26:443: i/o timeout

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops delete cluster cluster.app.com

error reading cluster configuration: Cluster.kops.k8s.io "cluster.app.com" not found

**5. What happened after the commands executed?**
It stuck for a while and then it gave me an error

**6. What did you expect to happen?**
That kops deletes it successfully

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by olemarkus** [comment]
Did you run this against the correct state store?
Deletions of clusters normally works, so would have to know more details to help any further.
