### ISSUE TITLE
Kops v1.16.1 and `kops get --name $NAME -o yaml` incorrect parse

### ISSUE THREAD

**Issue by dignajar** [kubernetes/kops#8981]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.16.1
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops get --name $NAME -o yaml
```

**5. What happened after the commands executed?**
After the update, the YAML file is not correctly parsed when I get it.

```
  additionalUserData:
  - content: "bootcmd:\n  - mkdir -p /var/cache/nodeup/packages
```

**6. What did you expect to happen?**
```
additionalUserData:
    - content: |
        bootcmd:
          - mkdir -p /var/cache/nodeup/packages
```

**Comment by olemarkus** [comment]
This is something that happens when parsing yaml that has trailing characters such as space. Look at the file you gave as input and see if there was anything like that there.

**Comment by dignajar** [comment]
Thank you, was the trailing whitespaces.
