### ISSUE TITLE
Hetzner Cloud Support

### ISSUE THREAD

**Issue by nekinie** [kubernetes/kops#8983]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Utilize kops to deploy and manage Kubernetes clusters on [Hetzner Cloud](https://www.hetzner.com/cloud), also known has hcloud.

**2. Feel free to provide a design supporting your feature request.**

Hetzner provide an official Go library: https://github.com/hetznercloud/hcloud-go

**Comment by robertwe** [comment]
I would love to see it moving forward +1

**Comment by nekinie** [comment]
I have some work ongoing for it in the background, will start pushing my work into a branch a little later today

**Comment by JWDobken** [comment]
hee @nekinie what is the status of your work?

**Comment by tomekit** [comment]
I would love to try out kops on Hetzner Cloud. Is this something in progress or ditched?

**Comment by olemarkus** [comment]
I don't think there is much point in trying to reopen this. If one wants support, one would have to provide PRs.

**Comment by bokysan** [comment]
Seems so, yeah. :-/

**Comment by olemarkus** [comment]
What you can do is to ask Hetzner to sponsor this. That is what many of the other cloud providers has done. DO especially, as of late

**Comment by hakman** [comment]
This is mostly done and available for testing and feedback. That can be done as separate issues if needed.
