### ISSUE TITLE
add CI support for Github Actions

### ISSUE THREAD

**Issue by irons** [kubernetes/kops#8984]
On the Apr 24 office hours call, @justinsb expressed an interest in Github Actions over Travis. I have a working implementation and wanted to confirm the desired scope. 

What I've got now is:

* ubuntu-18.04 and macOS-10.15, each running `make nodeup examples test`, under go 1.13.x and go 1.14.x
* ubuntu-18.04, running what's currently `make travis-ci`, under go 1.13.x and go 1.14.x
* rename `travis-ci` target to `github-actions`
* update CI badges in EN and ES readmes

Once I worked out syntax issues, these six jobs ran concurrently in a little over eight minutes.

Uncertainties:

* The travis configuration only runs `make travis-ci` on linux (both travis and github disallow docker on macOS, so this target would fail there), and only under go 1.13. Should this be carried over as-is?
* Should travis.yml be removed as part of this PR, or as a subsequent step?
* Is Windows worth looking at?

I appreciate the opportunity to try out Actions, which was more polished than I expected. Thanks for all the work on kops.

**Comment by hakman** [comment]
Hi @irons. Thanks for looking into Github Actions for Kops and dong this research.

The following should be done in a subsequent PR, once we have the time to compare Github Actions with Travis:
* rename `travis-ci` target to `github-actions`
* update CI badges in EN and ES readmes

Regarding the uncertainties:
* `make travis-ci` does some OS independent check so should be done only on Linux with GO 1.13
* `travis.yml` should not be removed yet
* Windows is beyond the scope of this and should be ignored for now

There is a plan to add Linux support for ARM64. Would it be any issue to add such a target later?

**Comment by irons** [comment]
Thanks for the feedback. I'll turn it around in a PR tomorrow morning.

The environments currently supported by Github Actions are [detailed here](https://github.com/actions/virtual-environments/). They're not acknowledging anything specific to ARM64, and [until Azure supports it](https://github.com/microsoft/azure-pipelines-agent/issues/1911), Github probably won't. ARM is also [not yet supported for self-hosted runners](https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#supported-operating-systems-for-self-hosted-runners), unfortunately. Travis's alpha support for ARM64 might be the best option for the time being — I don't imagine virtualizing on top of amd64 holds much appeal.

**Comment by hakman** [comment]
There could also be a mixed scenario where some jobs are also run in Travis as optional.
I am pretty sure everyone will want to start adding some ARM stuff at some point, at least to have some cheaper alternative to Intel.
