### ISSUE TITLE
1.16.1 After upgrading image on nodes cluster becomes unstable.

### ISSUE THREAD

**Issue by mprzygrodzki** [kubernetes/kops#8995]
I've recently upgraded kops from version 1.15.2 to 1.16.1. Cluster upgrade went well, but after upgrading node images from **kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16** to **kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17** nodes becomes totally unstable and they're randomly disconnecting from cluster and have status NotReady for some period of time. I was using Weave as networking provider and weave pods were randomly restarting so i've changed networking to calico but issue persist. I had to manually change images on each IG back to **kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16** and after this cluster and nodes become stable again. Does anyone observed similar issue ? I've tried also different newer images but that didn't helped and i would like to update everything and expect it's working as it should, haven't got any idea where else should I look for problems in this case.

**1. What kops version are you running? The command kops version, will display
this information.**

Version 1.16.1

**2. What Kubernetes version are you running? kubectl version will print the
version if a cluster is running or provide the Kubernetes version specified as
a kops flag.**

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run? What is the simplest way to reproduce this issue?**

kops upgrade cluster

**5. What happened after the commands executed?**

Nodes are randomly disconnecting from cluster.

**6. What did you expect to happen?**

Upgraded cluster.

**7. Please provide your cluster manifest. Execute
kops get --name my.example.com -o yaml to display your cluster manifest.
You may want to remove your cluster name and other sensitive information.**

apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-01-08T09:22:53Z"
  generation: 24
  name: k8s.xxx.com
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Name: staging-k8s-master
  cloudProvider: aws
  configBase: s3://clusters.k8s.xxx.com/k8s.xxx.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
      volumeSize: 5
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
      volumeSize: 5
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    featureGates:
      PodPriority: "true"
  kubernetesApiAccess:
  - 8.8.8.8
  kubernetesVersion: 1.16.8
  masterInternalName: api.internal.k8s.xxx.com
  masterPublicName: api.k8s.xxx.com
  networkCIDR: 172.30.0.0/16
  networkID: vpc-9b5838f0
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 8.8.8.8
  subnets:
  - cidr: 172.30.32.0/19
    id: subnet-b6xxxxx
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.30.0.0/22
    id: subnet-4dxxxxx
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-01-08T10:16:30Z"
  generation: 10
  labels:
    kops.k8s.io/cluster: k8s.xxx.com
  name: concourse-nodes
spec:
  cloudLabels:
    owner: devops
    service: concourse
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m5.2xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    xxxxxx.com/application: concourse
    xxxxxx.com/instance-role: memory
    kops.k8s.io/instancegroup: concourse-nodes
  role: Node
  rootVolumeOptimization: true
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-03-12T09:55:05Z"
  generation: 12
  labels:
    kops.k8s.io/cluster: k8s.xxx.com
  name: elasticsearch
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: r5n.large
  maxPrice: "0.100"
  maxSize: 3
  minSize: 3
  nodeLabels:
    xxxxxx.com/application: elasticsearch
    kops.k8s.io/instancegroup: elasticsearch
  role: Node
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-01-08T09:22:53Z"
  generation: 8
  labels:
    kops.k8s.io/cluster: k8s.xxx.com
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m5d.large
  maxPrice: "0.092"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  rootVolumeSize: 20
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-01-08T10:17:33Z"
  generation: 15
  labels:
    kops.k8s.io/cluster: k8s.xxx.com
  name: monitoring-nodes
spec:
  cloudLabels:
    owner: devops
    service: monitoring
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: r5.xlarge
  maxPrice: "0.801"
  maxSize: 1
  minSize: 1
  nodeLabels:
    xxxxxx.com/application: monitoring
    kops.k8s.io/instancegroup: monitoring-nodes
  role: Node
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-01-08T09:22:53Z"
  generation: 12
  labels:
    kops.k8s.io/cluster: k8s.xxx.com
  name: nodes
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m5d.large
  maxPrice: "0.048"
  maxSize: 4
  minSize: 4
  nodeLabels:
    xxxxxx.com/application: staging
    xxxxxx.com/instance-role: generic
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-01-15T09:28:48Z"
  generation: 9
  labels:
    kops.k8s.io/cluster: k8s.xxx.com
  name: nodes-test
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t3.2xlarge
  maxPrice: "0.501"
  maxSize: 1
  minSize: 1
  nodeLabels:
    xxxxxx.com/application: test
    xxxxxx.com/instance-role: generic
    kops.k8s.io/instancegroup: nodes-test
  role: Node
  subnets:
  - eu-central-1a

**Comment by MoShitrit** [comment]
I _think_ we started seeing the same issue as well.
We upgraded two clusters in prod over the weekend from 1.15 to 1.16 using `kops-1.16.1` and our monitoring systems started throwing sporadic alerts about a large amount of nodes failing `kubelet` healthchecks. We haven't been able to triage it down yet, but seeing this issue make me worry that it _could_ be a problem with the image. We're also using `kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17` after the upgrade.

**Comment by MoShitrit** [comment]
@mprzygrodzki we're suspecting Docker to be the culprit.
I was suggested to try and set it manually to `19.03.4` through `cluster.spec` 
(add this field to `spec`):
```
  docker:
    version: 19.03.4
```
Can you try that on your end as well to see if it helps?

**Comment by mprzygrodzki** [comment]
@MoShitrit thank for the tip, i will check it for sure but have to get some maintenance window to perform this action.

**Comment by mprzygrodzki** [comment]
@MoShitrit unfortunatelly updating docker doesn't helped. Still pods related to networking are being randomly restarted. I've made also some more investigation, create new cluster with 1 master and 2 worker nodes from scratch on the older image with kubernetes 1.15.10 image - then performed kops upgrade and everything was working as expected, didnt seen any restarts or node disconnected status.. very weird.

Sample outputs:

```
➜  utils git:(master) ✗ kb get pods -o wide | grep calico
calico-kube-controllers-68b7df9f67-9ngzn                                1/1     Running   0          39m     100.116.226.4     ip-172-30-36-81.eu-central-1.compute.internal    <none>           <none>
calico-node-2ktqq                                                       1/1     Running   1          43m     172.30.36.81      ip-172-30-36-81.eu-central-1.compute.internal    <none>           <none>
calico-node-95lk4                                                       1/1     Running   1          28m     172.30.35.243     ip-172-30-35-243.eu-central-1.compute.internal   <none>           <none>
calico-node-fb2xq                                                       0/1     Running   1          9m46s   172.30.41.159     ip-172-30-41-159.eu-central-1.compute.internal   <none>           <none>
calico-node-gljnm                                                       1/1     Running   1          30m     172.30.52.134     ip-172-30-52-134.eu-central-1.compute.internal   <none>           <none>
calico-node-hnrcq                                                       0/1     Running   4          18m     172.30.62.191     ip-172-30-62-191.eu-central-1.compute.internal   <none>           <none>
calico-node-l5vsh                                                       0/1     Error     0          7m17s   172.30.48.209     ip-172-30-48-209.eu-central-1.compute.internal   <none>           <none>
calico-node-ndd9v                                                       1/1     Running   3          16m     172.30.45.88      ip-172-30-45-88.eu-central-1.compute.internal    <none>           <none>
calico-node-wxwl9                                                       0/1     Running   2          16m     172.30.42.206     ip-172-30-42-206.eu-central-1.compute.internal   <none>           <none>
calico-node-zbsd6                                                       1/1     Running   1          7m16s   172.30.40.103     ip-172-30-40-103.eu-central-1.compute.internal   <none>           <none>
➜  utils git:(master) ✗ kb get pods -o wide | grep calico
calico-kube-controllers-68b7df9f67-9ngzn                                1/1     Running   0          39m     100.116.226.4     ip-172-30-36-81.eu-central-1.compute.internal    <none>           <none>
calico-node-2ktqq                                                       1/1     Running   1          43m     172.30.36.81      ip-172-30-36-81.eu-central-1.compute.internal    <none>           <none>
calico-node-95lk4                                                       1/1     Running   1          28m     172.30.35.243     ip-172-30-35-243.eu-central-1.compute.internal   <none>           <none>
calico-node-fb2xq                                                       1/1     Running   1          9m56s   172.30.41.159     ip-172-30-41-159.eu-central-1.compute.internal   <none>           <none>
calico-node-gljnm                                                       1/1     Running   1          30m     172.30.52.134     ip-172-30-52-134.eu-central-1.compute.internal   <none>           <none>
calico-node-hnrcq                                                       0/1     Running   4          18m     172.30.62.191     ip-172-30-62-191.eu-central-1.compute.internal   <none>           <none>
calico-node-l5vsh                                                       0/1     Running   1          7m27s   172.30.48.209     ip-172-30-48-209.eu-central-1.compute.internal   <none>           <none>
calico-node-ndd9v                                                       1/1     Running   3          16m     172.30.45.88      ip-172-30-45-88.eu-central-1.compute.internal    <none>           <none>
calico-node-wxwl9                                                       1/1     Running   2          16m     172.30.42.206     ip-172-30-42-206.eu-central-1.compute.internal   <none>           <none>
calico-node-zbsd6                                                       1/1     Running   1          7m26s   172.30.40.103     ip-172-30-40-103.eu-central-1.compute.internal   <none>           <none>
➜  utils git:(master) ✗ kb get nodes -o wide
NAME                                             STATUS   ROLES    AGE     VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION   CONTAINER-RUNTIME
ip-172-30-35-243.eu-central-1.compute.internal   Ready    node     28m     v1.16.8   172.30.35.243   <none>        Debian GNU/Linux 9 (stretch)   4.9.0-11-amd64   docker://19.3.4
ip-172-30-36-81.eu-central-1.compute.internal    Ready    master   43m     v1.16.8   172.30.36.81    <none>        Debian GNU/Linux 9 (stretch)   4.9.0-11-amd64   docker://19.3.4
ip-172-30-40-103.eu-central-1.compute.internal   Ready    node     7m37s   v1.16.8   172.30.40.103   <none>        Debian GNU/Linux 9 (stretch)   4.9.0-11-amd64   docker://19.3.4
ip-172-30-41-159.eu-central-1.compute.internal   Ready    node     10m     v1.16.8   172.30.41.159   <none>        Debian GNU/Linux 9 (stretch)   4.9.0-11-amd64   docker://19.3.4
ip-172-30-42-206.eu-central-1.compute.internal   Ready    node     16m     v1.16.8   172.30.42.206   <none>        Debian GNU/Linux 9 (stretch)   4.9.0-11-amd64   docker://19.3.4
ip-172-30-45-88.eu-central-1.compute.internal    Ready    node     16m     v1.16.8   172.30.45.88    <none>        Debian GNU/Linux 9 (stretch)   4.9.0-11-amd64   docker://19.3.4
ip-172-30-48-209.eu-central-1.compute.internal   Ready    node     7m38s   v1.16.8   172.30.48.209   <none>        Debian GNU/Linux 9 (stretch)   4.9.0-11-amd64   docker://19.3.4
ip-172-30-52-134.eu-central-1.compute.internal   Ready    node     30m     v1.16.8   172.30.52.134   <none>        Debian GNU/Linux 9 (stretch)   4.9.0-11-amd64   docker://19.3.4
ip-172-30-62-191.eu-central-1.compute.internal   Ready    node     18m     v1.16.8   172.30.62.191   <none>        Debian GNU/Linux 9 (stretch)   4.9.0-11-amd64   docker://19.3.4
```

**Comment by MoShitrit** [comment]
Thanks for the update @mprzygrodzki 
So after all, seems like it's not the same issue we're having.
For us it ended up being datadog agent throwing false alarms about kubelet failing healthcheck while they're being scaled down by cluster-autoscaler.
Curious, when you grab the logs from one of these crashing pods (i.e. `calico-node-l5vsh`) - does it show anything useful?
