### ISSUE TITLE
Retry 500s

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#900]
See [1389](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws/1389/) (failed teardown) and [1390](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws/1390/) (failed cluster up).

**Comment by zmerlynn** [comment]
Discussion here: http://docs.aws.amazon.com/general/latest/gr/api-retries.html. I'm guessing we never override (`cfg.MaxRetries`)[https://github.com/aws/aws-sdk-go/blob/83dcb597bed3dd7ad629b65a0f3658bc9169621f/aws/client/client.go#L52] and that it's relatively straightforward to fix this.

**Comment by zmerlynn** [comment]
Actually, it looks like I'll need to fix this to get the PR builder working, too - we don't retry enough to get around `RequestLimitExceeded` errors from multiple instances of `kops` abusing the API.

**Comment by chrislovecnm** [comment]
yah .. we are seeing stalling when you hit limits
