### ISSUE TITLE
kops update cluster error for externalPolicies

### ISSUE THREAD

**Issue by ysaakpr** [kubernetes/kops#9000]
I am unable to save the `kops edit cluster` while saving with externalPolicies
Its keep giving `Found fields that are not recognized`. I am able to update many other fields, like additionalPolicies etc. But only this setting is failing.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.14.0 (git-d5078612f)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops edit cluster
**5. What happened after the commands executed?**
I added external policies as specified
**6. What did you expect to happen?**
To add external policies to the existing node roles and master roles

**Comment by hakman** [comment]
`externalPolicies` will be available in Kops 1.18.
https://github.com/kubernetes/kops/pull/7837

**Comment by ysaakpr** [comment]
Are there any chance this to be backported to 1.14, or 1.16 since most of the userbase is still not moved out from kops 1.12

**Comment by ysaakpr** [comment]
It's my bad, I meant to say the Kubernetes version, not the kops version. And yeah, as you said i can anyways use kops 1.17 to manage k8s 1.14
