### ISSUE TITLE
Support for new af-south-1 Africa (Cape Town) region

### ISSUE THREAD

**Issue by bearnard** [kubernetes/kops#9012]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Support for new `af-south-1` `Africa (Cape Town)` region

**2. Feel free to provide a design supporting your feature request.**
Will this happen automatically when aws-sdk-go is bumped to a version that supports af-south-1,
or is there a bit more to the process of adding region support?
I see https://github.com/aws/aws-sdk-go/issues/3277 was resolved by `v1.30.12`

**Comment by rifelpet** [comment]
Updating the aws-sdk-go vendoring as well as https://github.com/kubernetes/kops/blob/7c3b8546d03c414ae0ea898aeabd2a14c0a8a9a7/upup/pkg/fi/cloud.go should be all that is required in this repo. [etcd-manager](https://github.com/kopeio/etcd-manager) will also need a vendoring update

**Comment by rifelpet** [comment]
aws-sdk-go v1.30.16 also includes eu-south-1 which was announced today, so we should upgrade to that and add support for both new regions.

**Comment by MoShitrit** [comment]
Will do @rifelpet !
