### ISSUE TITLE
Update developer script with these steps

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#903]
1. get dns in route53
2. create s3 buckets
3. run script
4. find bastion to ssh into
5. your pem will be the access token
6. user is admin, and the default is debian
7. set zones appropriately, you need 3 zones in a region for HA

**Comment by bboreham** [comment]
I needed one extra hint: to look in "Load Balancers" in the console to find the bastion's external identity.

**Comment by kris-nova** [comment]
Ah yes - that probably should be given a little more attention.. 

And also I just wanted to call out that the **hack** shell scripts are useful for prototyping, but I don't think we should **ever** rely on one of these in a release.. if there is logic in these scripts that we are finding useful that is a sign that it needs to be built into kops IMHO

Thoughts?

**Comment by chrislovecnm** [comment]
Hack is hack ;) I agree

**Comment by justinsb** [comment]
Are you going to send a PR @chrislovecnm ?

**Comment by chrislovecnm** [comment]
When I have time ;)
