### ISSUE TITLE
"No more IP addresses available on network",  "IpAddressGenerationFailure"

### ISSUE THREAD

**Issue by diego-lugones** [kubernetes/kops#9060]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.16.0 (git-4b0e62b82)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
  "kubernetesVersion": "1.16.9",

**3. What cloud provider are you using?**
Openstack Rocky

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
First:
kops create cluster   --cloud openstack   --name my.k8s.local   --state ${KOPS_STATE_STORE}   --zones nova   --network-cidr 10.0.0.0/24   --image ubuntu-server-1604LTS   --master-count=1   --node-count=2   --node-size m1.large   --master-size m1.large   --etcd-storage-type iscsi   --api-loadbalancer-type public   --topology private   --bastion   --ssh-public-key ~/.ssh/docker.pub   --networking weave   --os-ext-net public   --v 10  >logs/create_log 2>&1

Second:
kops update cluster --name my.k8s.local --yes --v 10 >logs/run_log 2>&1

**5. What happened after the commands executed?**
The fist command yields no error

During the second command, when creating the cluster the installation cannot create ports. 

0504 18:17:54.754279    2544 port.go:162] Creating Port with name: "port-bastions-1-my-k8s-local"
I0504 18:17:54.771237    2544 routerinterface.go:126] Creating RouterInterface for router:2fcc52c9-31d3-4f61-a0a6-48735d73ffe7 and subnet:18cecc91-79eb-48cd-9843-50bf92c34ba4
I0504 18:17:54.778060    2544 port.go:162] Creating Port with name: "port-nodes-1-my-k8s-local"
I0504 18:17:54.801820    2544 port.go:162] Creating Port with name: "port-nodes-2-my-k8s-local"
I0504 18:17:55.628475    2544 context.go:247] retrying after error error creating port: Expected HTTP response code [] when accessing [POST http://13x.8x.x.11:9696/v2.0/ports], but got 409 instead
{"NeutronError": {"message": "No more IP addresses available on network 512dd907-7530-42c4-a33f-cd5f9b111c77.", "type": "IpAddressGenerationFailure", "detail": ""}}
I0504 18:17:55.709694    2544 routerinterface.go:126] Creating RouterInterface for router:2fcc52c9-31d3-4f61-a0a6-48735d73ffe7 and subnet:9fff3866-6b41-4328-b44e-dbd9f2590b78
I0504 18:17:55.921270    2544 port.go:162] Creating Port with name: "port-master-nova-1-my-k8s-local"
I0504 18:17:56.807910    2544 port.go:181] Creating a new Openstack port, id=5fe150a9-f3a6-433e-bf3c-78f774b3a428
I0504 18:17:57.272876    2544 port.go:181] Creating a new Openstack port, id=ce8462ed-d403-4fc2-a936-f38b63d9f57b
I0504 18:17:57.555426    2544 context.go:247] retrying after error error creating port: Expected HTTP response code [] when accessing [POST http://13x.8x.x.11:9696/v2.0/ports], but got 409 instead
{"NeutronError": {"message": "No more IP addresses available on network 512dd907-7530-42c4-a33f-cd5f9b111c77.", "type": "IpAddressGenerationFailure", "detail": ""}}
I0504 18:17:57.658010    2544 routerinterface.go:135] Creating a new Openstack router interface, id=8f378962-0109-4b24-9569-0470431e665f
I0504 18:17:58.171828    2544 port.go:181] Creating a new Openstack port, id=523c1aaf-1831-4b27-8633-e1e5ab79a4b6
I0504 18:17:58.364432    2544 routerinterface.go:135] Creating a new Openstack router interface, id=5f960058-f238-4100-ace1-e661bc55ca00
I0504 18:17:59.896446    2544 context.go:247] retrying after error error creating port: Expected HTTP response code [] when accessing [POST http://13x.8x.x.11:9696/v2.0/ports], but got 409 instead
{"NeutronError": {"message": "No more IP addresses available on network 512dd907-7530-42c4-a33f-cd5f9b111c77.", "type": "IpAddressGenerationFailure", "detail": ""}}
I0504 18:18:02.973623    2544 context.go:247] retrying after error error creating port: Expected HTTP response code [] when accessing [POST http://13x.8x.x.11:9696/v2.0/ports], but got 409 instead
{"NeutronError": {"message": "No more IP addresses available on network 512dd907-7530-42c4-a33f-cd5f9b111c77.", "type": "IpAddressGenerationFailure", "detail": ""}}
I0504 18:18:08.433735    2544 context.go:251] hit maximum retries 5 with error error creating port: Expected HTTP response code [] when accessing [POST http://13x.8x.x.11:9696/v2.0/ports], but got 409 instead
{"NeutronError": {"message": "No more IP addresses available on network 512dd907-7530-42c4-a33f-cd5f9b111c77.", "type": "IpAddressGenerationFailure", "detail": ""}}
W0504 18:18:08.434061    2544 executor.go:128] error running task "Port/port-bastions-1-my-k8s-local" (9m45s remaining to succeed): Error creating port: error creating port: Expected HTTP response code [] when accessing [POST http://13x.8x.x.11:9696/v2.0/ports], but got 409 instead
{"NeutronError": {"message": "No more IP addresses available on network 512dd907-7530-42c4-a33f-cd5f9b111c77.", "type": "IpAddressGenerationFailure", "detail": ""}}
I0504 18:18:08.434258    2544 executor.go:103] Tasks: 105 done / 117 total; 1 can run

However, setting Debug to true in neutron, the real problem seems to be that device_id is not set yet:

16358:2020-05-04 18:26:18.518 23089 DEBUG neutron.notifiers.nova [req-affebe39-0d13-4b37-ad78-6cb7c33e78ff 643d76ceecc142bcb46348d23d50f364 60938f1ed8f04ca496a0ab036d2ce46d - default default] device_id is not set on port fff9d9dd-1a3a-4f32-906b-3035ba8e0f11 yet. _can_notify /usr/lib/python2.7/site-packages/neutron/notifiers/nova.py:170

If I do a neutron port-show, indeed device_id is blank. I see instanceGroups but no Instances deployed.

**6. What did you expect to happen?**
I checked neutron quotas and see not limit in the number of ports per betwork. I expected kops to create the router and networks (which indeed does happen) and create all ports

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

https://gist.github.com/diego-lugones/5a3b872b9c05aaa5fd1bc2dc2f7cbfb3#file-create_log

https://gist.github.com/diego-lugones/5a3b872b9c05aaa5fd1bc2dc2f7cbfb3#file-run_log

**9. Anything else do we need to know?**
I am using neutron lbaasV2

**Comment by zetaab** [comment]
this is not kops problem, it is problem in your OpenStack. Please contact your OpenStack environment admins and copy paste that error to them

**Comment by diego-lugones** [comment]
I use kops create cluster   --cloud openstack  ... with  --network-cidr 10.0.0.0/24 as suggested in the Getting Started guide.

With that, kops creates one network 'my.k8s.local' with two subnets

One with 32 hosts, name "nova.my.k8s.local":
--> allocation_pools  | 10.0.0.34-10.0.0.62               
-->  cidr              | 10.0.0.32/27

The other  "utility-nova.my.k8s.local":
--> allocation_pools  | 10.0.0.2-10.0.0.2                    
--> cidr              | 10.0.0.0/30                          

In the later, kops has defined only one IP in the allocation pool (10.0.0.2-10.0.0.2) but tries to create more ports - which gives the error. 

Am I using the wrong network cidr as parameter? Why does kops create utility-nova.my.k8s.local with only one IP? is this expected behavior?

Thanks!

**Comment by diego-lugones** [comment]
I have edited the utility-nova.my.k8s.local network cidr with  kops edit cluster my.k8s.local
I changed from 10.0.0.0/30 to 10.0.0.0/28 to enable more addresses and it worked.
