### ISSUE TITLE
zsh completion bad math expression error

### ISSUE THREAD

**Issue by doczico** [kubernetes/kops#9066]
Dear awesome team,
Small but annoying issue with zsh completion.
when trying to complete the command kops edit / kops create and probably others 
the following error is thrown 
```
_kops_edit:11: bad math expression: operand expected at `"ig"'
_kops_edit:11: bad math expression: operand expected at `"ig"'
```

zsh : zsh 5.7.1 (x86_64-ubuntu-linux-gnu) + oh_my_zsh

kops: Version 1.16.1 (git-d1b07f7fd6)

Thank you very much for the work done !
Awesome

**Comment by olemarkus** [comment]
The code around zsh completion is ... interesting. I'll have a look, but it will take a while
/assign
