### ISSUE TITLE
Add support for disable-attach-detach-reconcile-sync flag in kube-controller-manager

### ISSUE THREAD

**Issue by andersosthus** [kubernetes/kops#9067]
kubernetes/kubernetes#39551 added two flags to control the attach-detach reconcile sync in kube-controller-manager, `attach-detach-reconcile-sync-period` and `disable-attach-detach-reconcile-sync`, but only one of them got added to Kops in #1465.

We currently have the need to set `disable-attach-detach-reconcile-sync`, so I suggest adding `disable-attach-detach-reconcile-sync` as an option alongside `attach-detach-reconcile-sync-period` to Kops.

I can contribute the changes needed, if this sounds ok.

**Comment by rifelpet** [comment]
Yes, feel free to open a PR! [heres](https://github.com/kubernetes/kops/pull/8833/files) an example of a similar PR you can use as a reference. Essentially the field is added to `pkg/apis/kops/v1alpha2/componentconfig.go` and `pkg/apis/kops/componentconfig.go` and then you need to run `make apimachinery crds`.
