### ISSUE TITLE
S3 bucket object ACL should be configurable

### ISSUE THREAD

**Issue by tazjin** [kubernetes/kops#907]
Relates somewhat to #435 because it's also a necessity for cross-account buckets.

Basically kops should set one of the canned ACLs on objects it creates in S3 buckets, such as `bucket-owner-full-control` - otherwise in the cross-account situation you can have a bucket with files that aren't accessible by the bucket owner (thanks Amazon).

**Comment by chrislovecnm** [comment]
You able to knock this out?

**Comment by tazjin** [comment]
Able to, yes, we'll see about time though :)

**Comment by chrislovecnm** [comment]
SGTM

**Comment by tazjin** [comment]
I have some time for this and the other related issue now.

Both of these options are S3-specific and rather niche, so maybe it's enough to do them as env-vars that only get read in the VFS context initialisation.

**Comment by chrislovecnm** [comment]
few thoughts:

- we need versioning turned on
- we need the option to create the initial bucket
- we need the option to create the IAM role for the bucket

Thoughts?  It has to run on create, so command line switch would be my recommendation.  I am not a fan of ENV vars :)
