### ISSUE TITLE
`nodeup` removes previously installed docker version even if it is higher then installed

### ISSUE THREAD

**Issue by OleksandrBerezianskyi** [kubernetes/kops#908]
Our AMI includes docker version 1.12.3 but the nodeup uninstalls it and installs docker version 1.11.2. This is one of the reasons why we want #387 to be implemented

**Comment by chrislovecnm** [comment]
@OleksandrBerezianskyi thanks, btw happy to take PRs.

**Comment by justinsb** [comment]
This is correct actually ... but ...  in kops 1.5, you can now specify the docker version to be installed.

The "acceptable" choices (i.e. the ones that are tested with k8s 1.5) are 1.12.3 and 1.12.1, but I expect other people will add more options.
