### ISSUE TITLE
warn/fail if KOPS_STATE_STORE is not a s3 bucket

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#91]
import, for example, will accept a local state store `export KOPS_STATE_STORE=somedir`

But this isn't really what people want; you can't then create a cluster from there (currently).

We should probably block or warn people that do this.

**Comment by vreon** [comment]
> But this isn't really what people want

I want this! :smile: I mean, someday. We're looking to keep cluster descriptions in version control, and using a local dir as a state store would be pretty helpful there.

**Comment by justinsb** [comment]
True @vreon - that is valid :-)  The most pressing problem right now is that KOPS_STATE_STORE is also referenced by the cluster, to bootstrap the configuration, and thus it won't work if it is a local directory.

Two options I think:

1. Let the bootstrap location be separate from KOPS_STATE_STORE.  This will be important so that you can have clusters in GCE & AWS with one state store, for example
2. Make it easy/transparent to export/mirror the state store to a local directory, for management with git.

And most likely both will be needed!

**Comment by justinsb** [comment]
#323 will address the basic issue here; going to move further resolution to the next milestone

**Comment by chrislovecnm** [comment]
Closing this since state store can be gs or s3. Warnings are pretty good now
