### ISSUE TITLE
Multiple vendor directories

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kops#910]
I'm new to golang, so I'm curious why kops has both `vendor/` and `_vendor/` ? Is one of these directories from a pin/legacy/alt go dependency manager?

**Comment by justinsb** [comment]
Hi @mcandre.

Docs on it are here: https://github.com/kubernetes/kops/blob/master/docs/development/dependencies.md

Long-term, we'll likely move either to bazel or whatever the "official" go solution turns out to be.

This is probably a dup of #651

**Comment by chrislovecnm** [comment]
Closing
