### ISSUE TITLE
Vendor dependencies by git:// URLs

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kops#911]
Some of the dependencies are registered in git submodules with https:// URLs, which can cause connectivity problems. Could we use git:// URLs instead?

**Comment by justinsb** [comment]
Not sure why https would cause more problems - I would have guessed the other way round.

You also don't _need_ to fetch the submodules.  You can just git clone into the right place ($GOPATH/k8s.io/kops) and things will work from the vendor dir.  You only need to update the submodules if you're updating a dependency.

**Comment by chrislovecnm** [comment]
Still a problem? Closing
