### ISSUE TITLE
Install kops with Homebrew

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kops#912]
Could kops be published to http://brew.sh ?

**Comment by chrislovecnm** [comment]
Sure. Happy to if you want to maintain it ;)

**Comment by kris-nova** [comment]
I think this would be a **fabulous** addition to the tool, and would get more people in the door.

I think there are 2 big pieces we need to address for this

## What version to we push to homebrew?

Obviously we want a long term release up there, but we will need to update it (often) so ideally we would have some process in place to repeat this as we release new versions / patches.. 

I am okay with wiki-scripting the process for now - and building out into something a little more elegant in the future

## How does this affect our support?

Pushing a static release out to the homebrew repo's is great, as long as there are no bugs :) We need to push meaningful releases out to the community, but we shouldn't release buggy code. So we need to come up with a way to support these releases

+1 from me

**Comment by WillPlatnick** [comment]
@kris-nova I've never made a Homebrew manifest before, but I'd love to work on this one. We use kops at $job and I'd love to give back a little to a project that has helped me out tremendously.

**Comment by chrislovecnm** [comment]
Thanks would be awesome!!!

**Comment by WillPlatnick** [comment]
Full disclosure: I have no idea what I'm doing.

but...

I have a PR for the 1.4.1 release in at Homebrew - https://github.com/Homebrew/homebrew-core/pull/7193

It could use a much better test than 'kops version'. Thoughts?

I'll put the formula and some documentation together in a PR to better incorporate this into the release process once it gets past Homebrew.

**Comment by WillPlatnick** [comment]
OK, PR has been accepted and kops is now in brew. I'll update the install docs, but where should the release documentation and the brew formula go?

**Comment by kris-nova** [comment]
@WillPlatnick 

I think this is important enough to merit a change `README.md` under [#installation](https://github.com/kubernetes/kops#installation) as well as a more detailed bit of documentation on how we make changes, the release process, etc in `/doc`

Ideally we should have everything we need to make changes to the formula in homebrew right here in our kops documentation..

I think a good spot for the formula things would be `/hack/homebrew/<here>`

**Comment by WillPlatnick** [comment]
@kris-nova - First attempt at documentation is at https://github.com/kubernetes/kops/pull/989

**Comment by mcandre** [comment]
LGTM
