### ISSUE TITLE
Offer a release/build for master:head

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kops#913]
Consider using the master branch as the release branch, so that fewer steps are required for users to build kops.

**Comment by chrislovecnm** [comment]
It is one more step, and unusual to do? @justinsb I say no, how say u?

**Comment by kris-nova** [comment]
So I think this is derived from the public nodeup being hosted according to the last **release** and not offering one for **master**

I think if we could figure out a clever way to get an **experimental** build out there for **MASTER:HEAD** for users that would be helpful..

Also this is probably another great opportunity to harden our code base.. 

+1 from me on having an **experimental** or **alpha** something or other in place for users to test **master** easily

Not critical - but would be nice

**Comment by WillPlatnick** [comment]
@mcandre You can now install HEAD via Homebrew, PR for docs is at https://github.com/kubernetes/kops/pull/989

Does this close your ticket?

**Comment by mcandre** [comment]
@WillPlatnick Awesome!
