### ISSUE TITLE
Ability to use custom calico image

### ISSUE THREAD

**Issue by f-ld** [kubernetes/kops#9145]
It appears from crd:
https://github.com/kubernetes/kops/blob/e4ca5a000df589e33a849ee41f8d2ec3f6baeed4/k8s/crds/kops.k8s.io_clusters.yaml#L2629-L2696

and code: https://github.com/kubernetes/kops/blob/5738ffab1387e49486f72494e2effc249b16a587/pkg/apis/kops/networking.go#L102-L136)

that it is not possible to specify a custom calico image.

But today quay.io got a major outage being unavailable for multiple hours, see https://status.quay.io/incidents/kw2627bsdwd9

During that time, it was impossible to do upscaling of new nodes and follow the traffic evolution.
Having the ability to enforce a custom image for Calico (without having to edit the daemonset manually) would be helpful.

Note : I think this should be added to all maintained versions of kops

**Comment by johngmyers** [comment]
The local registry use case would require more images to be replaced than just the networking providers. The kops asset phase and assets.containerRegistry would address that case.

**Comment by povils** [comment]
@johngmyers thanks for info! just not to confirm containerRegistry would allow us to specify our custom registry for all kops used images in one place? Like networking, protokube, cluster-autoscaler, spotinst and so on?

**Comment by johngmyers** [comment]
I don't know about the non-bootstrap addons, but yes to everything installed by `kops update cluster`.

**Comment by f-ld** [comment]
Ok, sorry, I missed that piece in the doc.

For whoever landing here with the same question, have a look to [the spec > assets > containerRegistry in the cluster spec](https://github.com/kubernetes/kops/blob/6830cf6d44004cfaa26b3037b28b118dcc9d7417/docs/cluster_spec.md#containerregistry)

Closing this ticket then
