### ISSUE TITLE
Allow specifying container images for cluster networking providers

### ISSUE THREAD

**Issue by jeffb4** [kubernetes/kops#9146]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I would like to specify custom images for cluster networking providers. Particularly Flannel in my case.

I locally host images in a registry and limit host access to that registry, so reaching out to quay.io is problematic for me.

**2. Feel free to provide a design supporting your feature request.**

**Comment by jeffb4** [comment]
Related to #9145

**Comment by jeffb4** [comment]
Required for #9143

**Comment by johngmyers** [comment]
The local registry use case would require more images to be replaced than just the networking providers. The kops asset phase and `assets.containerRegistry` would address that case.
