### ISSUE TITLE
Make the k8s binary path consumed from S3

### ISSUE THREAD

**Issue by keglevich3** [kubernetes/kops#915]
The motivation:
Some enterprise won't allow the k8s binary to be download from google on each node-up, I believe that consuming the binary from S3 should be much faster (I think since they should be located on the same region)  and more secured (Due to VPC endpoint).

**Comment by yissachar** [comment]
See https://github.com/kubernetes/kops/issues/715

**Comment by zmerlynn** [comment]
We could start syncing releases to S3 as well. We (Google) are running release syncers to other GCS regions - I don't think it would be that hard to setup a sync to S3 as well.

**Comment by chrislovecnm** [comment]
This is a duplicate ... closing
