### ISSUE TITLE
Getting "Error appending tag to subnet" error after upgrading kops

### ISSUE THREAD

**Issue by mobilego** [kubernetes/kops#9158]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.16.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.16.9
**3. What cloud provider are you using?**
OpenStack 
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Upgraded kops from 1.15.0 to 1.16.2 and ran kops update cluster --yes to use external cloud controller manager. 
**5. What happened after the commands executed?**
Getting the error below
W0521 11:59:40.167103   31906 executor.go:128] error running task "Subnet/utility-cloud-*" (0s remaining to succeed): Error appending tag to subnet: error appending tag ****: Resource not found

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by johngmyers** [comment]
Does that subnet exist? Please provide your redacted cluster manifest and verbose logs.

**Comment by pfisterer** [comment]
@mobilego did you solve the issue? I've got the same error message.

**Comment by pfisterer** [comment]
@johanhubens this is an excerpt from the logs:

```console
$ kops update cluster --name bla.k8s.local --yes
I0614 20:53:37.892679    2341 s3context.go:92] Found S3_ENDPOINT="http://XXXXX", using as non-AWS S3 backend
I0614 20:53:40.864126    2341 apply_cluster.go:562] Gossip DNS: skipping DNS validation
I0614 20:53:41.793079    2341 executor.go:103] Tasks: 0 done / 114 total; 48 can run
I0614 20:53:43.099692    2341 executor.go:103] Tasks: 48 done / 114 total; 47 can run
I0614 20:53:48.963034    2341 context.go:251] hit maximum retries 4 with error error appending tag bla.k8s.local: Resource not found
I0614 20:53:48.977548    2341 context.go:251] hit maximum retries 4 with error error appending tag bla.k8s.local: Resource not found
W0614 20:53:50.895741    2341 executor.go:128] error running task "Subnet/utility-nova.bla.k8s.local" (9m52s remaining to succeed): Error appending tag to subnet: error appending tag bla.k8s.local: Resource not found
W0614 20:53:50.895804    2341 executor.go:128] error running task "Subnet/nova.bla.k8s.local" (9m52s remaining to succeed): Error appending tag to subnet: error appending tag bla.k8s.local: Resource not found
```

**Comment by pfisterer** [comment]
@johngmyers in my case, the subnet exists. do you need additional information?

**Comment by johngmyers** [comment]
Looking at the code, it creates the subnet then goes into a retry/backoff loop trying to tag it. It looks like openstack took longer for the created subnet to be taggable than the kops backoff loop was willing to wait.

**Comment by pfisterer** [comment]
@johngmyers Thank you. Is there any way either to increase the timeout or to manually add those tags so that it can continue?

**Comment by pfisterer** [comment]
Looking at the logs, it says `Resource not found`. However, the networks do exist and I can manually create instances within those networks.

```console
I0702 09:23:52.597386   78377 context.go:251] hit maximum retries 4 with error error appending tag bla.k8s.local: Resource not found
W0702 09:23:52.597455   78377 executor.go:128] error running task "Subnet/utility-nova.bla.k8s.local" (3m39s remaining to succeed): Error appending tag to subnet: error appending tag bla.k8s.local: Resource not found
W0702 09:23:52.597487   78377 executor.go:128] error running task "Subnet/nova.bla.k8s.local" (3m39s remaining to succeed): Error appending tag to subnet: error appending tag bla.k8s.local: Resource not found
I0702 09:23:52.597505   78377 executor.go:143] No progress made, sleeping before retrying 2 failed task(s)
```

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/302635/86329302-3e77e980-bc46-11ea-9362-466845ad8a92.png">

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/302635/86329332-4899e800-bc46-11ea-8cd1-8a8ca0588afa.png">

**Comment by johngmyers** [comment]
It looks like the timeouts would have to be increased in code. One oddity is that it is using the read backoff strategy when it would seem to be more appropriate to use the write backoff strategy.

https://github.com/kubernetes/kops/blob/5e3b94ae17c1a2cea2c21098ba1ee79eb910a470/upup/pkg/fi/cloudup/openstack/network.go#L32

**Comment by pfisterer** [comment]
I can volunteer to test any updated code but I'm not (yet) fluent in go.

**Comment by johngmyers** [comment]
@olemarkus since you're in the Openstack code, care to look at using the write backoff strategy when tagging?

**Comment by olemarkus** [comment]
Yep. I ran into a similar error myself.

/assign

**Comment by olemarkus** [comment]
Can you see if master has resolved this? The readbackoff duration has been increased quite a bit. Might be that the readbackoff is used because the function has to wait for the subnet to be created and enter ready state before writing. Since readbackoff is a lot longer than writebackoff it at least doesn't make sense to change them now.

**Comment by phchoi** [comment]
Looks like the issue is still with version kops 1.18.1 ?

**Comment by olemarkus** [comment]
That is expected. The changes done to openstack was rather extensive, so it will not be backported. You can test the latest kops 1.10 alpha version
