### ISSUE TITLE
Debian 10 (Buster) or Ubuntu 20.04 (Focal)

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#9163]
Debian 9 (Stretch) is pretty old and will be replaced as base for the default image in Kops 1.18.

Debian 10 (Buster):
* Linux kernel 4.19
* more tested in the Kubernetes world
* natural upgrade from Debian 9
* defaults to iptables NFT (not supported by most CNI plugins)

Ubuntu 20.04 (Focal):
* Linux kernel 5.4
* has fixes for all known kernel bugs at this time (including conntrack ones)
* defaults to iptables Legacy (supported by most CNI plugins)
* very similar to Debian, so most custom hooks and user scripts should still work

There may be some other considerations that I am missing. If so, please add a commoent.

For those interested, plase add a vote:
❤️   - Debian 10 (Buster)
🚀 - Ubuntu 20.04 (Focal)

**Comment by olemarkus** [comment]
With buster we have to maintain our own build to default to legacy iptables, while with focal, we can just use a vanilla AMI. That tilts it in favour of focal from my side.

**Comment by mariusv** [comment]
From my point of view this `has fixes for all known kernel bugs at this time (including conntrack ones)` makes a huge difference for most of the people.

**Comment by kzap** [comment]
Focal for us, most important are the fixes, rather than keeping on the same distribution

**Comment by fred-vogt** [comment]
It would be great to have the default, weill tested kops image be ubuntu 20.04.

A lot of shops will be using this as their base server image soon anyways.

Used kops with ubuntu 16.04, 18.04 previously.
* The only issue I've had with ubuntu 18.04 was [systemd-resolvd - coreDNS loop](https://github.com/kubernetes/kops/pull/8353`)

**Comment by hakman** [comment]
Thanks everyone for the feedback and for voting.
Ubuntu 20.04 will be the default image in Kops starting with v1.18.

**Comment by mikesplainsonos** [comment]
I feel like an idiot. I couldn't ssh into a test cluster. Turns out it's due to this (debian -> ubuntu = admin -> ubuntu user, duh).

Maybe we should add a release note highlighting this @hakman? Thanks for doing this!

**Comment by mikesplain** [comment]
I feel like an idiot. I couldn't ssh into a test cluster. Turns out it's due to this (debian -> ubuntu = admin -> ubuntu user, duh).

Maybe we should add a release note highlighting this @hakman? Thanks for doing this!

**Comment by MoShitrit** [comment]
That's a great point @mikesplain !
Yeah, I definitely vote for adding that highlight. Otherwise we'll probably see issues coming up from confused users 😄

**Comment by hakman** [comment]
Wanted to first get this all working first. Release notes are on the way :).

**Comment by MoShitrit** [comment]
Thanks, @hakman !! 😄
