### ISSUE TITLE
Remove vsphere support

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kops#9166]
(Almost) all of the code related to vsphere was added in #2401. After that most changes were to keep things compiling. It has always lived behind a feature flag and it requires a lot of hacks to get running.

I don't see this going anywhere, especially now that VMWare is pushing Tanzu for all it's worth. So I suggest we just punt it.

**Comment by rifelpet** [comment]
Git blame points me to these folks:
@SandeepPissay @abrarshivani @prashima @alrs

Would any of you be willing to help Kops' vSphere support move forward or should we go ahead and remove it?

**Comment by SandeepPissay** [comment]
@rifelpet I dont think anyone from VMware is maintaining this code. Please go ahead and remove it if nobody volunteers. Thanks!
