### ISSUE TITLE
Guide for supporting additional clouds?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kops#92]
Is there a rundown on what one would need to add to support another public cloud? Say for example, Azure?

**Comment by apobbati** [comment]
I'd be interested in contributing something for this issue. Any guides?

**Comment by chrislovecnm** [comment]
@colemickens actually want to look at Azure and other providers in possibly 1.6 or 1.7

**Comment by colemickens** [comment]
Is this still not part of the "Future"?

**Comment by kris-nova** [comment]
There is a guide [here](https://github.com/kubernetes/kops/blob/master/docs/development/how_it_works.md) that touches on things needed to support new clouds..

We are looking at the following in 1.6 (See PR [here](https://t.co/WnGUxpf8NC))

 - Bare metal
 - GCE

We have a hunch we will be seeing support for VMware in the future
We have a hunch we will be seeing support for Azure in the future

I can expand on either of those if needed! Let me know!

**Comment by kris-nova** [comment]
On that note, is this issue safe to close now?

**Comment by colemickens** [comment]
Looks like it! Thank you @kris-nova !
