### ISSUE TITLE
Issues before release

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#923]
Tracks issues and tasks before release

1. Update image to new version
2. Upgrade default k8s version
3. ~Check that pod do not deploy to master~ done 
4. ~Get limits PR in~ ~ done
5. Get helm PR in
6. Improve release process
  - sha on binaries on releases tab
  - deploy protokube
  - deploy dnscontroller
7. TF support for private topo
8. Bastion ssh -A with private topo
9. Fix #859 / #866

**Comment by chrislovecnm** [comment]
image is update to date but channels needs to be updated with:
k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-11-16

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/pull/974 Completed work on limits

**Comment by chrislovecnm** [comment]
What else do we need to get straight before cutting another release?

**Comment by zmerlynn** [comment]
I'd like to see #859 / #866 fixed, and I'm working on part of that now.

**Comment by kris-nova** [comment]
I want to get the Bastion `ssh -A` fix in - that is driving me NUTS

**Comment by chrislovecnm** [comment]
Once we have an agreement on what we need to do, I will update the milestones for a 1.4.6 or a 1.4.7 release. Depends on the version of k8s that we drop the kops release against.

**Comment by chrislovecnm** [comment]
Closing this because it is now in a 1.4.6 milestone.
