### ISSUE TITLE
Calico Typha doesn't tolerate masters taint

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#9240]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.16.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.15.12

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Bring up a cluster with default node taints (for example for node-readiness initialization)

**5. What happened after the commands executed?**
The cluster won't come up because typha can't tolerate taints for any nodes, so calico-node is broken.

**6. What did you expect to happen?**
Typha should tolerate the same taints calico-node does:
https://github.com/kubernetes/kops/blob/3ab974f680dd447218def6ac5ff850efcd24dcc1/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template#L572

This needs to include the ones from calico-node:
https://github.com/kubernetes/kops/blob/3ab974f680dd447218def6ac5ff850efcd24dcc1/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template#L678-L686

**Comment by seh** [comment]
While we're here, can we consider having Typha only _prefer_ running on the masters, but not require it, per my https://github.com/gjtempleton/kops/commit/a806f10b4ed551fb960ee6bdb4ea8bf2c7029c8b#r40786198?

**Comment by hakman** [comment]
@seh Please create a separate issue and we can discuss this there.

**Comment by seh** [comment]
Please see #9608.

**Comment by hakman** [comment]
This should be fixed in Kops 1.17 and 1.18. Please reopen if not the case.
/close
