### ISSUE TITLE
rolling-update does not detect all changes

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#925]
If a change is purely in the nodeup config, or purely in the S3 configuration files, we don't detect it as part of rolling-update.  This happens because the rolling-update heuristic currently only looks at the launch configuration.

Two options I can think of here (which are not mutually exclusive):

1) Have a way to apply those changes dynamically (i.e. re-run nodeup), and do so from rolling-update.
2) Bake a hash of the configuration into the launch configuration, so that the simple test works.  This does mean a full update is always required, and if we do the first option it'll then be inaccurate.

**Comment by chrislovecnm** [comment]
We should have fixed this in master.  Closing
