### ISSUE TITLE
Support creating cluster without any kind of public internet requirement

### ISSUE THREAD

**Issue by garo** [kubernetes/kops#926]
Currently kops requires downloading resources from public internet. We should also support use cases where cluster is provisioned into a VPC which does not have any kind of public access, but simply just a vpn access to another internal network.

**Comment by chrislovecnm** [comment]
This is a duplicate, we already have an issue for this

**Comment by yissachar** [comment]
https://github.com/kubernetes/kops/issues/715

**Comment by chrislovecnm** [comment]
Closing :)  Thanks @yissachar was on mobile.
