### ISSUE TITLE
Pods responding just on the node they are running in

### ISSUE THREAD

**Issue by gcis** [kubernetes/kops#927]
I have a created a cluster and everything seems fine, but when I deploy an app I won't be able to target every node on the nodeport and get response from the app, i will only get response if I target the node in which the app is deployed

**Comment by chrislovecnm** [comment]
Can you deploy one of the example apps from Kubernetes? Has this app worked before?

**Comment by justinsb** [comment]
@gcis which networking mode are you using?  (If you aren't sure, you can see the configuration using `kops get cluster <name> -oyaml`)

**Comment by gcis** [comment]
I'm using kubenet

**Comment by justinsb** [comment]
Can you give an example of the commands you're trying to run that are failing?  This is unexpected, and we would expect to see more failures in this case

**Comment by seankeeneycat** [comment]
Did anybody find a solution to this? Think we have the same issue.

**Comment by chrislovecnm** [comment]
@seankeeneycat same question as what @justinsb asked

**Comment by seankeeneycat** [comment]
Apologies - this is using calico.

**Comment by blakebarnett** [comment]
This sounds like `crossSubnet` mode turned on without https://github.com/ottoyiu/k8s-ec2-srcdst working (assuming the nodes are in different AZs/subnets).

**Comment by blakebarnett** [comment]
No idea what it would be with kubenet, probably a problem with the way the Route Tables are configured?

**Comment by caseydavenport** [comment]
Sounds a lot like this one: https://github.com/kubernetes/kubernetes/issues/58908

Could you check a couple of things?
- Version of docker installed on the nodes
- The version of kubernetes

If kubernetes >= v1.9
- The value passed to the kube-proxy for `--cluster-cidr`
- The value passed to the controller-manager for `--cluster-cidr` (for kubenet, @gcis )
- The IP pool that Calico is using (For the Calico install scenario, @seankeeneycat )

**Comment by Bessonov** [comment]
Experience same problem with [this setup](https://github.com/ecomm-integration-ballerina/kubernetes-cluster/blob/master/Vagrantfile).  Checked [CALICO_IPV4POOL_CIDR: 172.16.0.0/16](https://github.com/ecomm-integration-ballerina/kubernetes-cluster/blob/master/calico/calico.yaml#L230) and [--pod-network-cidr=172.16.0.0/16](https://github.com/ecomm-integration-ballerina/kubernetes-cluster/blob/master/Vagrantfile#L78). This happens after some days with multiple apply/delete and I can test it. Therefore /reopen .
