### ISSUE TITLE
New version of kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs image needed due to AddTrust cert expiration problem

### ISSUE THREAD

**Issue by darose** [kubernetes/kops#9290]
As you may have heard, there's a major issue going around recently whereby a root cert ("AddTrust External CA Root") has expired, and is causing many problems with clients that verify SSL certs that have that root in the chain.  (See https://www.agwa.name/blog/post/fixing_the_addtrust_root_expiration)  For many SSL clients (such as most browsers) this is not an issue, as they have removed that root cert from their list of trusted ca certs.

However, a number of other SSL client apps (such as curl) rely on the cert chain embedded into the OS, and if the expired AddTrust cert is still in the list of trusted certs, then SSL verification will fail on any site whose cert has that root cert in its chain.  This is the current state of affairs on the kops images of debian stretch, such as kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2020-01-17

```
admin@ip-10-184-237-182:~$ curl -v https://reputation.com > /dev/null
...
* SSL certificate problem: certificate has expired
...
```

```
admin@ip-10-184-237-182:~$ curl -vk https://reputation.com > /dev/null
...
* Server certificate:
*  subject: C=US; postalCode=94063; ST=California; L=Redwood City; street=1400A Seaport Blvd Suite 401; postOfficeBox=94063; O=Reputation.com, Inc; OU=Site Operations; OU=Multi-Domain SSL; CN=reputation.com
*  start date: Jun 10 00:00:00 2019 GMT
*  expire date: Aug  8 23:59:59 2021 GMT
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Organization Validation Secure Server CA
*  SSL certificate verify result: certificate has expired (10), continuing anyway.
...
```

This bug has recently been fixed in Debian (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961907) and the fix has been back-ported to Debian stretch in package ca-certificates version 20200601~deb9u1.

However, until a new version of the kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs image gets generated which contains this updated version of the package, any kops kubernetes node that is based on one of these images (and any containers running on them) will suffer from this expired root cert issue.

Any idea how soon it might be possible to get a new version of the image generated that includes the updated version of the ca-certificates package?

**Comment by darose** [comment]
Any thoughts on when it might be possible to release an updated image for this issue?

**Comment by olemarkus** [comment]
If only 1.14 is affected, this won't be fixed and you need to upgrade to latest stable kops.

**Comment by darose** [comment]
It does not appear that there are images available for any version of Kops that include the fix for this issue.  The most recent versions of all the Kops images appear to be from January (see attached).  But the fix was only released for Debian stretch in June.  (See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961907)

![Screenshot_2020-06-24_16-29-13](https://user-images.githubusercontent.com/507237/85624705-4fb66a00-b638-11ea-9e73-e92c9a0800e8.png)

**Comment by johngmyers** [comment]
@olemarkus the images are tied to k8s version through the channel, not to the kops version.

**Comment by olemarkus** [comment]
I was a bit short there. I was actually thinking of newer version of kops that runs updates on boot. Older versions of kops have automated updates, but it takes up to a day for the updates to trigger.

**Comment by johngmyers** [comment]
@olemarkus if you're thinking of #8635, that isn't in a stable release yet. And it probably wouldn't upgrade the CA certificates package as that one isn't explicitly installed by nodeup.

But do any of the sites that kops or Kubernetes pulls from using the OS trust store use an AddTrust cert?

**Comment by olemarkus** [comment]
Ah you are right. My mistake.
1.17 supports Ubuntu 20.04, so that may be an option then.

**Comment by darose** [comment]
Any thoughts on when it might be possible for this issue to get addressed?

**Comment by johngmyers** [comment]
I don't see an indication here of an actual problem. Which site that kops or Kubernetes pulls from using the OS trust store uses an AddTrust certificate?

**Comment by darose** [comment]
Well, first off, it's not necessarily who uses an AddTrust cert.  It's who uses a cert that has AddTrust as the root on its cert chain.  My understanding is that there's a large number of cert issuers and certs that fit into that category.

Also the question isn't really "are there any sites that kops or Kubernetes pulls from that use such a cert".  If that root cert is present on a machine, then *any* code running on that machine - i.e., kops, kubernetes, or any random user container - that is validating an SSL cert will erroneously flag as expired any cert that has AddTrust as the root of the chain.  Or in other words, any random container could wind up getting SSL expiration false positives.  Seems to me like that could be a problem.

**Comment by johngmyers** [comment]
I believe your understanding is incorrect. Only code using the node's OS-level trust store would have a problem. Code running in containers would use the trust store that is in the container, not the host OS's trust store.

**Comment by darose** [comment]
I've certainly been wrong before.  :-)  But to the best of my knowledge I'm not this time.

Yes, if a container happens to bundle in a trust store, then the container will use that.  However, in my experience, most containers don't bundle that.  And when our team looked into this a while back, we found that if a container didn't bundle that in, then any SSL cert verification was done via the underlying OS.  Which would result in what I described above - any random container could wind up getting SSL expiration false positives.

I was going to verify all of this and paste my output here.  But unfortunately I've lost my ability to test this.  The site that we were previously using to verify this issue (https://reputation.com) seems like it has since fixed their cert, and I was not able to find another site that uses the old cert verification chain.

That all said, I guess this would no longer be an issue if newer AMI's that you guys build for Debian include the fix in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961907

Thoughts?

**Comment by johngmyers** [comment]
I don't think we're planning on building newer Debian AMIs.

In my experience, if a Kubernetes container doesn't bundle a trust bundle then the container doesn't have a trust bundle to use. To use the underlying OS's bundle it would have to explicitly mount it using a `hostPath` volume.

**Comment by darose** [comment]
Again, that wasn't our experience when we tested this.  I'm not sure exactly how/why (and I no longer have the ability to test this) but when we would issue a curl command to an https site from inside a container it appeared that curl was accessing some library on the underlying host OS (which seemed to be using the host's root certs) in order verify if the site's cert was valid.

That said, if you've made up your mind that this is not something you want to address, there's not really much more to discuss and you might as well close this ticket.

It's possible that this could ultimately be a moot point anyway at this point, as many sites whose certs were affected by this issue back in June have probably fixed their issue by upgrading their cert.
