### ISSUE TITLE
bring-up speed: switch to busybox for protokube, dns-controller images

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#933]
If we make the images smaller, bring up will be faster

**Comment by chrislovecnm** [comment]
Would it make sense to not use protokube? Pull that code into nodeup?

**Comment by chrislovecnm** [comment]
Also alpine or busybox??

**Comment by chrislovecnm** [comment]
Closing because of bazel and the standard kubernetes/kubernetes image
