### ISSUE TITLE
How can I download binary kops version 1.15.3?

### ISSUE THREAD

**Issue by PradeepKC** [kubernetes/kops#9339]
**1. What `kops` version are you running? 
 kops version
Version 1.10.0 (git-8b52ea6d1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.12", GitCommit:"c757b93cf034d49af3a3b8ecee3b9639a7a11df7", GitTreeState:"clean", BuildDate:"2018-12-19T11:04:29Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Cannot download binary kops version 1.15.3

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by MoShitrit** [comment]
@PradeepKC you can find them here
https://github.com/kubernetes/kops/releases/tag/v1.15.3
/close

**Comment by PradeepKC** [comment]
Thanks. I am sure I tried that location just few hours ago. It works. Thanks for quick reply.

**Comment by MoShitrit** [comment]
No worries!
I think you might've tried this one - https://github.com/kubernetes/kops/releases/tag/1.15.3 (notice that the version isn't prefixed with `v`). This one doesn't have the binaries.
Starting kops 1.18 - this isn't going to be separated anymore so there will be just one place to look per version.
