### ISSUE TITLE
Add support to pass endpointReconcilerType to apiserver

### ISSUE THREAD

**Issue by feniix** [kubernetes/kops#9353]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

This is related to this issue: https://github.com/kubernetes/kops/issues/9327

From the documentation in https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

```
--endpoint-reconciler-type string     Default: "lease"
       Use an endpoint reconciler (master-count, lease, none)
```

but what is shown below is not a valid setting in the cluster.yaml
```
diff --git i/cluster.yaml w/cluster.yaml
index e7e8484..886c877 100644
--- i/cluster.yaml
+++ w/cluster.yaml
@@ -98,6 +98,7 @@ spec:
     auditLogMaxSize: 100
     auditLogPath: /var/log/kube-apiserver-audit.log
     auditPolicyFile: /srv/kubernetes/audit.yaml
+   endpointReconcilerType: master-count
     runtimeConfig:
       admissionregistration.k8s.io/v1beta1: "true"
   kubeDNS:
```

*It'd be nice to support that kube apiserver flag in the cluster config*

**2. Feel free to provide a design supporting your feature request.**

**Comment by olemarkus** [comment]
I can see how this makes sense on single-master clusters, but would be very unfortunate on multi-master ones. An idea could be that kops sets `endpoint-reconcilier-type` to `master-count` on single-master setups.

**Comment by feniix** [comment]
> I can see how this makes sense on single-master clusters, but would be very unfortunate on multi-master ones. An idea could be that kops sets `endpoint-reconcilier-type` to `master-count` on single-master setups.

why not keep `lease` as the default but allow for changing it? or maybe set `master-count` as the default for single master installs but allow for reconfiguration in case someone wants to make a change ?
