### ISSUE TITLE
Removing baremetal cloud provider

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kops#9357]
Following #9166, does anyone mind removing baremetal? Looks like some basic work was done on this about three years ago, but that it was never completed. Later commits are more about general changes to cloud provides.

@justinsb any plans on doing more work on this? With where kops is today, a baremetal provider perhaps overlaps more than usual with kubeadm.

**Comment by johngmyers** [comment]
I have a pending PR for this.
