### ISSUE TITLE
Add a Prometheus Exporter?

### ISSUE THREAD

**Issue by ari-becker** [kubernetes/kops#9370]
We'd like the ability to run the `kops` binary in a Prometheus metrics exporter mode, which starts a web server exposing a `/metrics` path that includes the following metrics:

* Whether or not a rolling update is required
* Break down instance groups, providing metrics for the current number of nodes in the instance group, the number of nodes that are ready, the number of nodes that need an update, the minimum size of the instance group, the maximum size of the instance group
* A metric that exposes `kops validate cluster`, i.e. whether or not the cluster is healthy.

**Comment by dntosas** [comment]
such supportive functions could also be part of `kops-controller` deployment (?)

**Comment by olemarkus** [comment]
I was wondering if the intention was to have kops expose this for all clusters in the statestore or if one wants one exporter instance per cluster.
For the latter, I agree that kops-controller seems like the place to put this.

**Comment by ari-becker** [comment]
I think that having one exporter instance per cluster is probably simpler and more performant. I'm very used to running `kops --state s3://foo --name bar rolling-update cluster` so being able to simply run `kops --state s3://foo --name bar prometheus-metrics-exporter` seems, at least to me, more or less self-explanatory.

`kops-controller` may be the correct place to put this, but there may be unintended security and networking consequences. Effectively, if it's possible to run `kops --state s3://foo --name bar prometheus-metrics-exporter`, then the metrics are generated and collected from outside the cluster, and the cluster itself needs only expose the Kubernetes API server. Running it as part of the `kops-controller` introduces a subtle change - the port which exposes the metrics endpoint must also be opened (with subsequent ramifications for opening up security groups etc., and may not be desirable for users with public API servers), and the accessibility of the cluster through the load balancer fronting the API server (implicitly checked by `kops validate cluster`) doesn't work the same way if the validation check is run from inside the cluster.

**Comment by olemarkus** [comment]
There are many compontents that kops deploys that has prometheus metrics. In order to get to these you need an in-cluster prometheus running. I don't think the metrics mentioned here need to be exposed any differently.
Arguably, the security is improved by going through kops controller as the kops-controller runs on master and have all the access it needs to both K8s API and AWS. Running from outside of the cluster means that whatever is running the job needs similar access as an operator.

Won't have time to work on this at the moment, but always happy to review a PR.

**Comment by h3poteto** [comment]
I can probably add it as part of `kops-controller`, but is that OK?
If it is OK, I will take this issue.

**Comment by ari-becker** [comment]
@h3poteto yeah, that would be great!
