### ISSUE TITLE
Changing etcd volume sizes ?

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/kops#9381]
Is this possible to change etcd volume size for an existing cluster ?
I see in the docs it's not possible out of the box but i wonder if there is a workaround for this.

This is for a multimaster cluster.
What happens if i change the volume size in the spec then terminate the master instances one by one, deleting the etcd volumes ?
Will this recreate the volumes with the new size and sync from other masters ?

Thanks

**Comment by jsonmp-k8** [comment]
I think changing the volume type and size for etcd is not supported in KOPS

**Comment by eddycharly** [comment]
Yeah, definitely. I had to do it manually.
Closing the issue.
