### ISSUE TITLE
Add spot label

### ISSUE THREAD

**Issue by oded-dd** [kubernetes/kops#9383]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
I would like to be able to monitor the number of spot instances running inside the cluster without using the AWS SDK.

The way I expect to do it is by using `kube-state-metrics` which exposes the nodes labels. 
Today I have no label indicating the node is a spot, while the information exists in AWS under node description `lifecycle`

**2. Feel free to provide a design supporting your feature request.**

**Comment by rifelpet** [comment]
Kops 1.17 automatically labels spot instances with `node-role.kubernetes.io/spot-worker=true`, are you using Kops 1.17?

**Comment by oded-dd** [comment]
@rifelpet Yes.

**Comment by johngmyers** [comment]
That feature was backed out of 1.17. It is in 1.18.

**Comment by hakman** [comment]
Should we add it back in? I think we rushed a bit with that revert.

**Comment by johngmyers** [comment]
The feature will go out with 1.18. I'm not so sure about backporting.

**Comment by olemarkus** [comment]
This one has been implemented, so we can close this now
/close
