### ISSUE TITLE
windows system: unable to connect to server EOF

### ISSUE THREAD

**Issue by MichelleZ** [kubernetes/kops#9388]
kubectl get pods or kubectl get namespaces

![image](https://user-images.githubusercontent.com/10205478/84970628-a9f18f80-b14d-11ea-8d57-eec60457c2e4.png)

![image](https://user-images.githubusercontent.com/10205478/84970657-b83fab80-b14d-11ea-8714-267fb4a0263e.png)

os: win10 pro

Docker desktop:
![image](https://user-images.githubusercontent.com/10205478/84970792-f9d05680-b14d-11ea-8adb-de427f94eba5.png)

Pls help check the reason, Thank you

**Comment by MichelleZ** [comment]
D6691544-8189-4359-9323-4F7934CAFFA5/20200618021549

**Comment by olemarkus** [comment]
I am guessing this is not related to the kops project. You may want to ask for help from your k8s provider.

**Comment by vnextcoder** [comment]
Looks like you should select right cluster in context menu of your docker desktop. Anyways Kops is not compatible with docker desktop
