### ISSUE TITLE
Links on kops.sigs.k8s.io are white on white background

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#9405]
The Kops docs site https://kops.sigs.k8s.io has invisible links.
My guess is that it's related to https://github.com/kubernetes/kops/pull/9393.

/assign @mikesplain 
/cc @rifelpet

**Comment by mikesplain** [comment]
Good eye. I’ll take a look

**Comment by hakman** [comment]
Was reported in Slack. I am just the messenger :). Thanks @hogepodge !

**Comment by hogepodge** [comment]
That was fast. Thanks everyone! 🥇
