### ISSUE TITLE
Kops 1.17.0 - Fails on creating SG's in AWS

### ISSUE THREAD

**Issue by mprzygrodzki** [kubernetes/kops#9440]
I've recently upgraded kops from version 1.16.1 to 1.17 and when i'm running command to update cluster i'm receiving error about duplicated security groups as cluster is running in AWS. For previous updates following errors never occured and i haven't found related issue so far, can anyone advice me what's wrong ?

`➜  utils git:(master) ✗ kops update cluster --yes
W0624 23:01:05.177272   72254 firewall.go:250] Opening etcd port on masters for access from the nodes, for calico.  This is unsafe in untrusted environments.
I0624 23:01:07.697492   72254 executor.go:103] Tasks: 0 done / 134 total; 49 can run
I0624 23:01:08.800461   72254 executor.go:103] Tasks: 49 done / 134 total; 24 can run
W0624 23:01:09.512824   72254 executor.go:128] error running task "SecurityGroup/api-elb.staging.xxx.com" (9m59s remaining to succeed): error creating SecurityGroup: InvalidGroup.Duplicate: The security group 'api-elb.staging.xxx.com' already exists for VPC 'vpc-xxxxxxx'
	status code: 400, request id: 7d75b953-f1bb-4945-9387-1e728773e6ca
W0624 23:01:09.512863   72254 executor.go:128] error running task "SecurityGroup/masters.staging.xxx.com" (9m59s remaining to succeed): error creating SecurityGroup: InvalidGroup.Duplicate: The security group 'masters.staging.xxx.com' already exists for VPC 'vpc-xxxxxx'
	status code: 400, request id: c404f898-6b1a-45a9-9103-66f7fee2c232
W0624 23:01:09.512883   72254 executor.go:128] error running task "SecurityGroup/nodes.staging.xxx.com" (9m59s remaining to succeed): error creating SecurityGroup: InvalidGroup.Duplicate: The security group 'nodes.staging.xxx.com' already exists for VPC 'vpc-xxxxxx'
	status code: 400, request id: bda9d5e0-7bc6-4ca8-ac90-66aa40892d09
I0624 23:01:09.512990   72254 executor.go:103] Tasks: 70 done / 134 total; 3 can run`

**1. What kops version are you running? The command kops version, will display
this information.**

Version 1.17.0

**2. What Kubernetes version are you running? kubectl version will print the
version if a cluster is running or provide the Kubernetes version specified as
a kops flag.**

1.17.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run? What is the simplest way to reproduce this issue?**

kops update cluster --yes

**5. What happened after the commands executed?**

Nodes are randomly disconnecting from cluster.

**6. What did you expect to happen?**

Upgraded cluster.

**Comment by tonyjchong** [comment]
I just ran into this same issue. If you changed the `Name` of the security group, you will run into this error. Try changing the `Name` back to the `Security Group Name`.

**Comment by mprzygrodzki** [comment]
@tonyjchong - thanks for the tip.. will check this out.
