### ISSUE TITLE
Private topology: cluster sometimes fails to come up with weave, and cni

### ISSUE THREAD

**Issue by lewistuff** [kubernetes/kops#945]
Just spun up a few clusters, and briefly discussed my results with @kris-nova. @chrislovecnm.

**Attempt 1. CNI**
With CNI I was unable to get it functioning. Core services failed to start on the master, only the `kube-scheduler` was running. `kube-proxy` was running on the nodes, but that was all.
> kops create cluster \
  --state $KOPS_STATE_STORE \
  --node-count 2 \
  --zones eu-west-1a,eu-west-1b \
  --master-zones eu-west-1a \
  --cloud aws \
  --node-size t2.medium \
  --master-size m3.large \
  --topology private \
  --networking cni \
  --ssh-public-key=$PUB_KEY \
  -v 10 \
  $CLUSTER_NAME \
  —yes

**Attempt 2. Weave**
The cluster was not installed, simply the infrastructure was setup. There were no docker images present on the hosts, and no containers running.
> kops create cluster \
  --state $KOPS_STATE_STORE \
  --node-count 2 \
  --zones eu-west-1a,eu-west-1b \
  --master-zones eu-west-1a \
  --cloud aws \
  --node-size t2.medium \
  --master-size m3.large \
  --topology private \
  --networking weave \
  --ssh-public-key=$PUB_KEY \
  -v 10 \
  $CLUSTER_NAME \
  —yes

**Attempt 3. Weave** 
[same command as above] 
This attempt succeeded and all services came up as expected. The cluster was fully operational.

**Comment by chrislovecnm** [comment]
Are u using the nodeup on master? Look at the dev build script in hack/

**Comment by chrislovecnm** [comment]
I assume that you are building from master :)

**Comment by lewistuff** [comment]
1. Correct @chrislovecnm I'm building the latest from master - should have mentioned.
2. I wasn't using nodeup explicitly, just `create cluster`. I'll take a look. 
3. Possibly a resource issue, but I didn't see anything indicating this. I can bump, and try again.

**Comment by chrislovecnm** [comment]
@lewistuff please use the build script under hack directory, and test with that. I am guessing that your tests are failing, because you are not using nodeup off of master. Nodeup is a binary that is d/l by the nodes and masters from s3. The dev script will compile a custom version of nodeup that will be used during the deployments.

**Comment by chrislovecnm** [comment]
And another note :) we need ethtool on the image for weave to work. We will be cutting a new public image this week. Working through the bugs ;) thanks for your patience.

**Comment by chrislovecnm** [comment]
We have PR inbound thay may help with this ... I am looking through issues to test against #1183 - no promises but we need to test.

**Comment by chrislovecnm** [comment]
See https://github.com/kubernetes/kops/issues/1206 ~ The PR is in.  Who can test?

**Comment by justinsb** [comment]
So we think this was ethtool @chrislovecnm ?

**Comment by justinsb** [comment]
Closing; please comment / reopen if not fixed.
