### ISSUE TITLE
Control `--create-kube-config` with an environment variable or invert its default

### ISSUE THREAD

**Issue by geekofalltrades** [kubernetes/kops#9466]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Our cluster uses an SSO solution in the kubeconfig for authentication to the cluster. Having Kops overwrite our kubeconfig every time we run `kops update cluster` is not helpful. It clobbers our working config, replacing it with a non-working config, and it installs admin-level credentials on developer desktops, which we would rather not distribute.

It's easy to forget to pass `--create-kube-config=false`, and so we do this fairly frequently on accident.

If we could control this behavior with an environment variable, we could all set it in .bashrc and forget about it.

Even better, if this flag's default could be inverted to false, `kops update cluster` would no longer have unrelated side effects on the developer's system. It could also be removed entirely, so that developers have to do it explicitly with `kops export kubecfg` (do one thing and do it well).

**2. Feel free to provide a design supporting your feature request.**

**Comment by olemarkus** [comment]
100%.
This one is a duplicate of sorts to #8017 and will be fixed by #9280

**Comment by olemarkus** [comment]
Already merged to master.
/close
