### ISSUE TITLE
Reference - kops/docs/instance_groups.md

### ISSUE THREAD

**Issue by kavicse87** [kubernetes/kops#9486]
**1. for capacity optimized strategy  is there any interruption handler for the worker nodes to drain and move the workloads to other available nodes when the interruption occurs. The given time is less than 2 minutes.

**2. What is the recommendation for using on demand and spot combination in the capacity optimized strategy. Any sample examples that you can share would be helpful. To test this approach in our dev clusters.

**Comment by kavicse87** [comment]
Any update / advise on this would be much helpful.

**Comment by johngmyers** [comment]
#7119 is the feature request to drain nodes when they are terminated.
