### ISSUE TITLE
subnet have the same zone

### ISSUE THREAD

**Issue by Sami-svmx** [kubernetes/kops#9489]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.17.0 (git-a17511e6dd)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: v1.18.5

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I have a VPC and subnets created and available in AWS. The subnets are divided into 6 (3 subnets(AZ1,AZ2,AZ3) for Application and 3 subnets(AZ1,AZ2,AZ3) for DB/Cache). 

subnet-11111111 & subnet-4444444 are from same Zone
subnet-22222222 & subnet-5555555 are from same Zone
subnet-33333333 & subnet-6666666 are from same Zone

When i ran the below command it gives me error

SUBNET_IDS="subnet-11111111,subnet-22222222,subnet-3333333,subnet-4444444,subnet-5555555,subnet-66666666"
kops create cluster --v=$VERBOSE \
                --cloud $CLOUD_PROVIDER \
                --master-count $MASTER_COUNT \
                --master-size $MASTER_SIZE \
                --master-zones $MASTER_ZONES \
                --zones $NODE_ZONES \
                --name=$SUBDOMAIN_NAME \
                --dns $DNS_HOSTED_ZONE \
                --ssh-public-key $SSH_PUBLIC_KEY \
                --networking $NETWORKING_MODE \
                --topology $CLUSTER_TOPOLOGY \
                --vpc $VPC_ID \
                --subnets $SUBNET_IDS \
                --utility-subnets $UTILITY_SUBNETS \
                --cloud-labels "$LABELS" \
                --kubernetes-version $KUBE_VERSION \
                --yes

**5. What happened after the commands executed?**

Error: subnet subnet-11111111 and subnet-44444444 have the same zone

**6. What did you expect to happen?**

I would like kops to accept multiple subnets from same availability zone. Please let me know if there is any other alternate way to attain this.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by johngmyers** [comment]
Kops does not currently support this. It only has the concept of allocating things out of a singular subnet for a zone.

**Comment by Sami-svmx** [comment]
> Kops does not currently support this. It only has the concept of allocating things out of a singular subnet for a zone.

**Comment by Sami-svmx** [comment]
@johngmyers thanks for the info. Any chance of including this feature in near future?

**Comment by johngmyers** [comment]
It seems unlikely; I don't know of anyone working on such a thing. It would immediately bring up the problem of which of several possible subnets to use for assignments to new things.

**Comment by olemarkus** [comment]
What is the use case for this? Maybe there are other solutions

**Comment by rdrgmnzs** [comment]
If I remember correctly one of the issues here is that the ELB used by the masters only supports 1 subnet per zone.

**Comment by Sami-svmx** [comment]
@olemarkus i am already exploring network policies to isolate traffic. However it would be great to do subnet level separation ex: Bigger subnet - Application 1, Smaller subnet - Application 2, Smaller Subnet - Database 2. 
     
@rdrgmnzs I will give it a try adding more subnets to same zone after cluster creation.

**Comment by johngmyers** [comment]
Looking at the cluster creation code, the issue appears to be what to name the subnets that are specified by the `--subnets` switch of `kops create cluster`. Currently it gives them the same name as the zone they're in, but that only works if there's one subnet per zone.

**Comment by hakman** [comment]
Wouldn't this be a case where one would use `kops create -f cluster.yaml`?

**Comment by vmasule** [comment]
> If I remember correctly one of the issues here is that the ELB used by the masters only supports 1 subnet per zone.
> 
> However once a cluster is created, I believe you should be able to add more subnets in the same zone to the cluster. You just won’t be able to create masters in those subnets

@rdrgmnzs  How to add additional subnets after cluster created for existing VPC? If there any documentation please share? Thanks.
