### ISSUE TITLE
Failed to download kops-controller while passing KOPS_BASE_URL as env variable

### ISSUE THREAD

**Issue by amitbitcse** [kubernetes/kops#9507]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.17.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.17.6

**3. What cloud provider are you using?**
AWS

I am using Nexus as a proxy repo https://kubeupv2.s3.amazonaws.com/kops

In v1.17.0, if I provide KOPS_BASE_URL as env variable, kops-controller.tar.gz, dns-controller.tar.gz and kube-apiserver-healthcheck.tar.gz fail to download as per below code.

https://github.com/kubernetes/kops/blob/v1.17.0/upup/pkg/fi/cloudup/apply_cluster.go#L1344

Is these another repo where I can find these image tars?
Or, these image tars should be present in the kops repo?

**Comment by hakman** [comment]
You can find the images in DockerHub:
https://hub.docker.com/r/kope/dns-controller/tags?page=1&ordering=last_updated
https://hub.docker.com/r/kope/kops-controller/tags?page=1&ordering=last_updated
https://hub.docker.com/r/kope/kube-apiserver-healthcheck/tags?page=1&ordering=last_updated

**Comment by amitbitcse** [comment]
Thanks @hakman 
For now, I am taking your suggested approach to create tars from docker images and published it to a Nexus repo (type: Hosted)

Created a Group repo in Nexus with two member repositories
1) custom hosted repo (with tars which are missing missing in S3)
2) proxy repo pointing to https://kubeupv2.s3.amazonaws.com/kops

Using this new Nexus group type repo as KOPS_BASE_URL

**Comment by xrl** [comment]
I am hitting this issue as well. I'm not very familiar with docker tar.gz bundles, is this as simple as:

```
docker pull kope/dns-controller:1.17.1
docker save kope/dns-controller:1.17.1 -o dns-controller.tar.gz
aws s3 cp dns-controller.tar.gz s3://my-bucket/some/path/dns-controller.tar.gz
```

**Comment by hakman** [comment]
You should be able to do the following now and all 
```bash
export KOPS_BASE_URL =https://storage.googleapis.com/k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b
```

Where `09ed4c7e0b` is a git commit https://github.com/kubernetes/kops/commit/09ed4c7e0b4aee9d25460e7c6195fc5e44d5e9ee:
```
$ gsutil ls "gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/*" 

gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/darwin/:
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/darwin/amd64/

gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/:
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/dns-controller.tar.gz
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/dns-controller.tar.gz.sha1
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/dns-controller.tar.gz.sha256
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/kops-controller.tar.gz
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/kops-controller.tar.gz.sha1
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/kops-controller.tar.gz.sha256
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/kube-apiserver-healthcheck.tar.gz
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/kube-apiserver-healthcheck.tar.gz.sha256
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/protokube.tar.gz
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/protokube.tar.gz.sha1
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/images/protokube.tar.gz.sha256

gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/linux/:
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/linux/amd64/

gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/windows/:
gs://k8s-staging-kops/kops/releases/1.18.1+09ed4c7e0b/windows/amd64/
```

**Comment by xrl** [comment]
I'm running on kops 1.17 for now, but I will keep this in mind, thanks!

**Comment by xrl** [comment]
This might help someone else trying to patch these tar.gz's in to their older kops version custom builds:

```
mkdir -p temp-docker-images; cd temp-docker-images; \
        for COMPONENT in dns-controller kops-controller kube-apiserver-healthcheck; do \
          docker pull kope/$COMPONENT:$VERSION; \
          docker save kope/$COMPONENT:$VERSION -o $COMPONENT.tar.gz; \
          sha1sum $COMPONENT.tar.gz | cut -d ' ' -f 1 > $COMPONENT.tar.gz.sha1; \
          sha256sum $COMPONENT.tar.gz | cut -d ' ' -f 1 > $COMPONENT.tar.gz.sha256; \
        done; \
        cd ..; \
        aws s3 sync --acl public-read --no-progress temp-docker-images/ ${S3_BUCKET}kops/$VERSION/images/
```

where those variables look like:

```
      VERSION: 1.17.1 # required by "make upload"
      S3_BUCKET: s3://my-bucket/drone-build/ # required by "make upload"
```
