### ISSUE TITLE
protokube is not installed on every node

### ISSUE THREAD

**Issue by aslobodskoy-fiksu** [kubernetes/kops#9523]
1. Version 1.16.4 (git-469984634f)

2. $ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"f3add640dbcd4f3c33a7749f38baaac0b3fe810d", GitTreeState:"clean", BuildDate:"2020-05-20T13:51:56Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

3. AWS

4. /var/log/syslog:Jul  8 07:52:38 ip-172-18-117-196 bash[3213]: Failed to stop protokube.service: Unit protokube.service not loaded.
because of
/var/log/daemon.log:Jul  8 07:50:15 ip-172-18-117-196 nodeup[891]: I0708 07:50:15.714930     891 protokube.go:54] skipping the provisioning of protokube on the nodes

**Comment by hakman** [comment]
Please check if this was fixed in 1.17.
