### ISSUE TITLE
Kops master branch: multiple masters fail to cluster together

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#9531]
When there are multiple master nodes, the API servers fail to cluster together and worker nodes fail to register.

The second api-server fails with:

```
W0708 19:38:50.391903       1 lease.go:224] Resetting endpoints for master service "kubernetes" to [172.20.40.133 172.20.70.113]
I0708 19:38:50.392785       1 controller.go:606] quota admission added evaluator for: endpoints
I0708 19:38:50.399710       1 controller.go:606] quota admission added evaluator for: endpointslices.discovery.k8s.io
I0708 19:38:56.175853       1 controller.go:606] quota admission added evaluator for: leases.coordination.k8s.io
I0708 19:39:42.672783       1 controller.go:606] quota admission added evaluator for: serviceaccounts
E0708 19:39:43.684332       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]
E0708 19:39:43.692574       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]
```

This appears to have been caused by #9354, which changed from using a single, ten-year TLS server certificate to per-node TLS server certificates with shorter lifetimes.

Initial investigation suggests that this is caused by kops configuring kube-controller-manager to reuse the api-server's TLS private key as the service account private key. Now that the nodes have different TLS private keys, service tokens created on one master node would not be recognized on the other master nodes.

**Comment by johngmyers** [comment]
It seems a bad idea to reuse the TLS private key for signing service account tokens. Those are two entirely different purposes.

I believe we should have kops provision a separate private key out of cloudup for service account tokens. On upgrade from older kops versions it should pick up the old TLS server private key.

**Comment by fred-vogt** [comment]
@johngmyers - In typical "lurker" fashion I have to ask - a workaround on master would be using:
https://kubernetes-kops.netlify.app/operations/service_account_token_volumes/  ?

I'm using this for testing IAM Roles for Service Accounts.
So I'm already not re-using the TLS key for signing service account tokens correct ?

**Comment by johngmyers** [comment]
Those projected service account tokens are signed with the reused TLS key.
