### ISSUE TITLE
hack/dev-build.sh unable to use

### ISSUE THREAD

**Issue by razic** [kubernetes/kops#955]
hey i am trying to use the `hack/dev-build.sh` to build my cluster but at the end of the logs i'm getting:

```bash
error running tasks: did not make any progress executing task.  Example error: could not find Image for "k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-11-16"
```

**Comment by chrislovecnm** [comment]
We need a new image cut.  Thought that I made that image public... Opps

**Comment by chrislovecnm** [comment]
This needs to be merged as well https://github.com/kubernetes/kube-deploy/pull/258

**Comment by chrislovecnm** [comment]
You can use the above changes to make a new image that will function with weave.

**Comment by razic** [comment]
tried running image build but no matter what i do it won't run successfully. i've created an issue here. maybe you can shed some light?

https://github.com/kubernetes/kube-deploy/issues/259

**Comment by chrislovecnm** [comment]
I am seeing that the ami `k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-11-16` is listed as public.  Can you find it in the console?

**Comment by razic** [comment]
I do see the image now. Gonna try again.

**Comment by razic** [comment]
@chrislovecnm Even though I see the image in the public images on AWS console, I'm getting the same error.

FWIW I'm trying to run my cluster in `us-west-2` not sure if that makes any difference?

Any other ideas?

**Comment by chrislovecnm** [comment]
@justinsb needs to rebuild the image and we need to tweak some of the kops code to not just look for kopeio images ;)

**Comment by razic** [comment]
okay, i changed the title here because the script has since been changed but, i'm still having issues. 

cluster is failing to come up... in the cloud init logs i see this:

```
== Failed to download https://viralkitty-kops-dev.amazonaws.com/kops/git-9cf2826/linux/amd64/nodeup.sha1. Retrying. ==
All downloads failed; sleeping before retrying
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 6 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 3 retries left.
```

**Comment by razic** [comment]
https://github.com/kubernetes/kops/pull/1127 should fix it

**Comment by kris-nova** [comment]
@razic - #1127 was merged, and..?

**Comment by justinsb** [comment]
This is fixed, right?  OK to close?

**Comment by chrislovecnm** [comment]
👍
