### ISSUE TITLE
Binary releases for arm64

### ISSUE THREAD

**Issue by odidev** [kubernetes/kops#9550]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Hi team, 

There are already binary being released for x86 platform, is there any plan to release for arm64 platform as well.

**2. Feel free to provide a design supporting your feature request.**

I would like to contribute to the binary release. Would you tell the process to be followed for the binary release process for arm64?

**Comment by olemarkus** [comment]
Kops 1.19 has arm binaries: https://github.com/kubernetes/kops/releases/tag/v1.19.0-alpha.1
Note that arm64 is not supported for master nodes at the moment, and there are known issues with various AWS instance types and AMIs beyond our control. For example ubuntu 20.04 on c6g instances.

**Comment by AGSaidi** [comment]
What is the ubuntu 20.04 issue?

**Comment by hakman** [comment]
CloudInit script are not run during first boot.

**Comment by davdunc** [comment]
> What is the ubuntu 20.04 issue?

I think @olemarkus is referring to the failure to https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1885973 That's fixed in the most recent dailies and on track for stable in the short term.

**Comment by hakman** [comment]
I just tested with `099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20200701` and seems to be working fine.
Thanks for the link @davdunc.

**Comment by odidev** [comment]
May I know when are you planning on releasing arm64 binaries for the master node?

**Comment by hakman** [comment]
Should be part of the 1.19 release in 1-2 months.

**Comment by hakman** [comment]
This is done. All binaries are released.
/close
