### ISSUE TITLE
error from server (internalerror): an error on the server ("") has prevented the request from succeeding

### ISSUE THREAD

**Issue by FahimaGold** [kubernetes/kops#9569]
I'm using kops 1.15.0 and kubectl v1.18.0

I'm trying to create a cluster on aws, it is created. However, whenever I try to run `kubectl get nodes` or any other command related to `kubectl` I get this error "error from server (internalerror): an error on the server ("") has prevented the request from succeeding"

I'm using Gossip-based cluster

**Comment by hakman** [comment]
Kops 1.15.0 is no longer supported. Please use the latest version.
Also, when you open an issue, please follow the template.
/close

**Comment by FahimaGold** [comment]
Indeed.The problem was due to kops version. Changed the version to 1.17.1 and it worked. thanks
