### ISSUE TITLE
feature request: kops operator

### ISSUE THREAD

**Issue by ludydoo** [kubernetes/kops#9570]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

**Kops Operator**. I'd like to be able to provision kops resources using standard k8s yaml files. It would be great if kops could be running inside a k8s cluster, as an operator, and be able to provision resources declared with custom CRDs, such as Clusters or InstanceGroups. so `kubectl get clusters`, `kubectl get instancegroups`, etc.  

In our case, we'd like kops to be able to manage **the cluster it created**. We would like to be able to run performance tests on our software in an automated manner. We developed an operator that deploys our software using our own CRDs. Somethimes, we need to provision dedicated hardware for performance test reasons. (eg. run dedicated 4 x m5.4xlarge nodes for a release performance test). Our operator could create Kops CRDs, which would then be handled by the kops operator itself, also with automatic garbage collection, finalizers, etc.

**Comment by ari-becker** [comment]
@ludydoo you may be interested in https://github.com/kubernetes-sigs/cluster-api 
From what I understand, the long-term vision is that `kops` turns into a binary used to bootstrap a control cluster, and then the Cluster API is used to handle day-to-day operations. But the Cluster API is still under heavy development.
