### ISSUE TITLE
FlatcarLinux with Kops 1.17.0/1 wrong Flexvolume Path

### ISSUE THREAD

**Issue by J-Ha** [kubernetes/kops#9571]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.17.1
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.17.8
**3. What cloud provider are you using?**
AWS

KOPS 1.17.0 or 1.17.1 does not bootstrap a cluster with the right flexvolume path.
CNI: Canal
OS: Flatcar Container Linux by Kinvolk 2512.2.1 (Oklo)

` MountVolume.SetUp failed for volume "flexvol-driver-host" : mkdir /usr/libexec/kubernetes: read-only file system`

**Comment by hakman** [comment]
Please attach the cluster spec.

**Comment by J-Ha** [comment]
`apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-07-14T11:32:17Z"
  name: xxxx.eu-west-1.xxxx.io
spec:
  api:
    loadBalancer:
      crossZoneLoadBalancing: false
      type: Public
  assets:
    containerProxy: docker.repo.xxxx.xx
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Env: test
    Name: xxxx.eu-west-1.xxxx.io
    Owner: Karma Team.
    Team: Karma
  cloudProvider: aws
  clusterDNSDomain: cluster.local
  configBase: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io
  configStore: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io
  dnsZone: xxxxxxxxxxxx
  docker:
    ipMasq: false
    ipTables: false
    logDriver: json-file
    logLevel: warn
    logOpt:
    - max-size=10m
    - max-file=5
    storage: overlay2,overlay,aufs
    version: 19.03.11
  encryptionConfig: true
  etcdClusters:
  - backups:
      backupStore: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io/backups/etcd/main
    enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    manager: {}
    name: main
    provider: Manager
    version: 3.4.3
  - backups:
      backupStore: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io/backups/etcd/events
    enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    manager: {}
    name: events
    provider: Manager
    version: 3.4.3
  iam:
    allowContainerRegistry: true
    legacy: false
  keyStore: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io/pki
  kubeAPIServer:
    allowPrivileged: true
    anonymousAuth: false
    apiServerCount: 3
    authorizationMode: RBAC
    bindAddress: 0.0.0.0
    cloudProvider: aws
    enableAdmissionPlugins:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - TaintNodesByCondition
    - Priority
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - PersistentVolumeClaimResize
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    - StorageObjectInUseProtection
    - PodSecurityPolicy
    etcdServers:
    - http://127.0.0.1:4001
    etcdServersOverrides:
    - /events#http://127.0.0.1:4002
    image: docker.repo.xxxx.xx/kube-apiserver:v1.17.8
    insecureBindAddress: 127.0.0.1
    kubeletPreferredAddressTypes:
    - InternalIP
    - Hostname
    - ExternalIP
    logLevel: 2
    oidcClientID: kubernetes
    oidcGroupsClaim: groups
    oidcGroupsPrefix: 'oidc:'
    oidcIssuerURL: https://xxxx.eu-west-1.xxxx.io/keycloak/realms/kubernetes
    oidcUsernameClaim: sub
    oidcUsernamePrefix: 'oidc:'
    requestheaderAllowedNames:
    - aggregator
    requestheaderExtraHeaderPrefixes:
    - X-Remote-Extra-
    requestheaderGroupHeaders:
    - X-Remote-Group
    requestheaderUsernameHeaders:
    - X-Remote-User
    securePort: 443
    serviceClusterIPRange: 100.64.0.0/13
    storageBackend: etcd3
  kubeControllerManager:
    allocateNodeCIDRs: true
    attachDetachReconcileSyncPeriod: 1m0s
    cloudProvider: aws
    clusterCIDR: 100.96.0.0/11
    clusterName: xxxx.eu-west-1.xxxx.io
    configureCloudRoutes: false
    image: docker.repo.xxxx.xx/kube-controller-manager:v1.17.8
    leaderElection:
      leaderElect: true
    logLevel: 2
    useServiceAccountCredentials: true
  kubeDNS:
    cacheMaxConcurrent: 150
    cacheMaxSize: 1000
    cpuRequest: 100m
    domain: cluster.local
    memoryLimit: 170Mi
    memoryRequest: 70Mi
    provider: CoreDNS
    replicas: 2
    serverIP: 100.64.0.10
  kubeProxy:
    clusterCIDR: 100.96.0.0/11
    cpuRequest: 100m
    hostnameOverride: '@aws'
    image: docker.repo.xxxx.xx/kube-proxy:v1.17.8
    logLevel: 2
  kubeScheduler:
    image: docker.repo.xxxx.xx/kube-scheduler:v1.17.8
    leaderElection:
      leaderElect: true
    logLevel: 2
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: docker.repo.xxxx.xx/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
  kubernetesApiAccess:
  - 217.110.227.178/32
  - 10.0.0.0/8
  - 52.16.33.168/32
  - 54.72.107.34/32
  - 54.76.158.54/32
  kubernetesVersion: 1.17.8
  masterInternalName: api.internal.xxxx.eu-west-1.xxxx.io
  masterKubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: docker.repo.xxxx.xx/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
    registerSchedulable: false
  masterPublicName: api.xxxx.eu-west-1.xxxx.io
  networkCIDR: 172.20.0.0/16
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  secretStore: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io/secrets
  serviceClusterIPRange: 100.64.0.0/13
  sshAccess:
  - 217.110.227.178/32
  - 10.0.0.0/8
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.20.64.0/19
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.20.96.0/19
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.20.0.0/22
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.20.4.0/22
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.20.8.0/22
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
  updatePolicy: external
`

**Comment by J-Ha** [comment]
```kind: Cluster
metadata:
  creationTimestamp: "2020-07-14T11:32:17Z"
  name: xxxx.eu-west-1.xxxx.io
spec:
  api:
    loadBalancer:
      crossZoneLoadBalancing: false
      type: Public
  assets:
    containerProxy: docker.repo.xxxx.xx
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Env: test
    Name: xxxx.eu-west-1.xxxx.io
    Owner: Karma Team.
    Team: Karma
  cloudProvider: aws
  clusterDNSDomain: cluster.local
  configBase: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io
  configStore: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io
  dnsZone: xxxxxxxxxxxx
  docker:
    ipMasq: false
    ipTables: false
    logDriver: json-file
    logLevel: warn
    logOpt:
    - max-size=10m
    - max-file=5
    storage: overlay2,overlay,aufs
    version: 19.03.11
  encryptionConfig: true
  etcdClusters:
  - backups:
      backupStore: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io/backups/etcd/main
    enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    manager: {}
    name: main
    provider: Manager
    version: 3.4.3
  - backups:
      backupStore: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io/backups/etcd/events
    enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    manager: {}
    name: events
    provider: Manager
    version: 3.4.3
  iam:
    allowContainerRegistry: true
    legacy: false
  keyStore: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io/pki
  kubeAPIServer:
    allowPrivileged: true
    anonymousAuth: false
    apiServerCount: 3
    authorizationMode: RBAC
    bindAddress: 0.0.0.0
    cloudProvider: aws
    enableAdmissionPlugins:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - TaintNodesByCondition
    - Priority
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - PersistentVolumeClaimResize
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    - StorageObjectInUseProtection
    - PodSecurityPolicy
    etcdServers:
    - http://127.0.0.1:4001
    etcdServersOverrides:
    - /events#http://127.0.0.1:4002
    image: docker.repo.xxxx.xx/kube-apiserver:v1.17.8
    insecureBindAddress: 127.0.0.1
    kubeletPreferredAddressTypes:
    - InternalIP
    - Hostname
    - ExternalIP
    logLevel: 2
    oidcClientID: kubernetes
    oidcGroupsClaim: groups
    oidcGroupsPrefix: 'oidc:'
    oidcIssuerURL: https://xxxx.eu-west-1.xxxx.io/keycloak/realms/kubernetes
    oidcUsernameClaim: sub
    oidcUsernamePrefix: 'oidc:'
    requestheaderAllowedNames:
    - aggregator
    requestheaderExtraHeaderPrefixes:
    - X-Remote-Extra-
    requestheaderGroupHeaders:
    - X-Remote-Group
    requestheaderUsernameHeaders:
    - X-Remote-User
    securePort: 443
    serviceClusterIPRange: 100.64.0.0/13
    storageBackend: etcd3
  kubeControllerManager:
    allocateNodeCIDRs: true
    attachDetachReconcileSyncPeriod: 1m0s
    cloudProvider: aws
    clusterCIDR: 100.96.0.0/11
    clusterName: xxxx.eu-west-1.xxxx.io
    configureCloudRoutes: false
    image: docker.repo.xxxx.xx/kube-controller-manager:v1.17.8
    leaderElection:
      leaderElect: true
    logLevel: 2
    useServiceAccountCredentials: true
  kubeDNS:
    cacheMaxConcurrent: 150
    cacheMaxSize: 1000
    cpuRequest: 100m
    domain: cluster.local
    memoryLimit: 170Mi
    memoryRequest: 70Mi
    provider: CoreDNS
    replicas: 2
    serverIP: 100.64.0.10
  kubeProxy:
    clusterCIDR: 100.96.0.0/11
    cpuRequest: 100m
    hostnameOverride: '@aws'
    image: docker.repo.xxxx.xx/kube-proxy:v1.17.8
    logLevel: 2
  kubeScheduler:
    image: docker.repo.xxxx.xx/kube-scheduler:v1.17.8
    leaderElection:
      leaderElect: true
    logLevel: 2
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: docker.repo.xxxx.xx/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
  kubernetesApiAccess:
  - 10.0.0.0/8
  kubernetesVersion: 1.17.8
  masterInternalName: api.internal.xxxx.eu-west-1.xxxx.io
  masterKubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: docker.repo.xxxx.xx/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
    registerSchedulable: false
  masterPublicName: api.xxxx.eu-west-1.xxxx.io
  networkCIDR: 172.20.0.0/16
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  secretStore: s3://xxxx-eu-west-1-xxxx-io/xxxx.eu-west-1.xxxx.io/secrets
  serviceClusterIPRange: 100.64.0.0/13
  sshAccess:
  - 10.0.0.0/8
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.20.64.0/19
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.20.96.0/19
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.20.0.0/22
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.20.4.0/22
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.20.8.0/22
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
  updatePolicy: external```

**Comment by hakman** [comment]
Thanks. Also the instance group part.

**Comment by J-Ha** [comment]
```apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-14T11:32:18Z"
  labels:
    kops.k8s.io/cluster: xxxx.eu-west-1.xxxx.io
  name: bastions
spec:
  associatePublicIp: true
  image: ami-e4515e0e
  machineType: t3a.nano
  maxSize: 1
  minSize: 1
  role: Bastion
  rootVolumeSize: 10
  subnets:
  - utility-eu-west-1a
  - utility-eu-west-1b
  - utility-eu-west-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-14T11:32:18Z"
  labels:
    kops.k8s.io/cluster: xxxx.eu-west-1.xxxx.io
  name: master-eu-west-1a
spec:
  image: ami-08738afa3d25a1196
  machineType: m5a.large
  maxPrice: "0.07"
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - m5a.large
    - m5.large
    - m4.large
    - m5ad.large
    - m5d.large
    - r5a.large
    onDemandAboveBase: 0
    spotInstancePools: 3
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-14T11:32:18Z"
  labels:
    kops.k8s.io/cluster: xxxx.eu-west-1.xxxx.io
  name: master-eu-west-1b
spec:
  image: ami-08738afa3d25a1196
  machineType: m5a.large
  maxPrice: "0.07"
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - m5a.large
    - m5.large
    - m4.large
    - m5ad.large
    - m5d.large
    - r5a.large
    onDemandAboveBase: 0
    spotInstancePools: 3
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b
  role: Master
  subnets:
  - eu-west-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-14T11:32:18Z"
  labels:
    kops.k8s.io/cluster: xxxx.eu-west-1.xxxx.io
  name: master-eu-west-1c
spec:
  image: ami-08738afa3d25a1196
  machineType: m5a.large
  maxPrice: "0.07"
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - m5a.large
    - m5.large
    - m4.large
    - m5ad.large
    - m5d.large
    - r5a.large
    onDemandAboveBase: 0
    spotInstancePools: 3
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  role: Master
  subnets:
  - eu-west-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-14T11:32:18Z"
  labels:
    kops.k8s.io/cluster: xxxx.eu-west-1.xxxx.io
  name: nodes-eu-west-1a
spec:
  image: ami-08738afa3d25a1196
  machineType: m5a.4xlarge
  maxPrice: "0.50"
  maxSize: 30
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - m5a.4xlarge
    - m5.4xlarge
    - m4.4xlarge
    - m5ad.4xlarge
    - m5d.4xlarge
    - r5a.4xlarge
    - h1.4xlarge
    - m5n.4xlarge
    onDemandAboveBase: 0
    spotInstancePools: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 100
  subnets:
  - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-14T11:32:18Z"
  labels:
    kops.k8s.io/cluster: xxxx.eu-west-1.xxxx.io
  name: nodes-eu-west-1b
spec:
  image: ami-08738afa3d25a1196
  machineType: m5a.4xlarge
  maxPrice: "0.50"
  maxSize: 30
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - m5a.4xlarge
    - m5.4xlarge
    - m4.4xlarge
    - m5ad.4xlarge
    - m5d.4xlarge
    - r5a.4xlarge
    - h1.4xlarge
    - m5n.4xlarge
    onDemandAboveBase: 0
    spotInstancePools: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 100
  subnets:
  - eu-west-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-14T11:32:18Z"
  labels:
    kops.k8s.io/cluster: xxxx.eu-west-1.xxxx.io
  name: nodes-eu-west-1c
spec:
  image: ami-08738afa3d25a1196
  machineType: m5a.4xlarge
  maxPrice: "0.50"
  maxSize: 30
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - m5a.4xlarge
    - m5.4xlarge
    - m4.4xlarge
    - m5ad.4xlarge
    - m5d.4xlarge
    - r5a.4xlarge
    - h1.4xlarge
    - m5n.4xlarge
    onDemandAboveBase: 0
    spotInstancePools: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 100
  subnets:
  - eu-west-1c
```

**Comment by hakman** [comment]
Please specify the image with name instead of AMI and retry:
```yaml
spec:
  image: flatcar/Flatcar-stable-2512.2.1-hvm
```

**Comment by hakman** [comment]
For reference: https://github.com/kubernetes/kops/pull/8062

**Comment by J-Ha** [comment]
seems to solve the issue, i was taking a look into the code. 
It should read the /etc/os-release to get the OS Type. so it should not care about ami or fully qualified image name?

https://github.com/kubernetes/kops/blob/v1.17.1/nodeup/pkg/model/kube_controller_manager.go#L169

**Comment by hakman** [comment]
How would you read `/etc/os-release` before the node even exists?
Also, this sets a value in a DaemonSet, which is cluster wide. Cannot set per node values there.

**Comment by J-Ha** [comment]
to identify the HostOS should be a preKubernetes step.
to setup the FlexVol should be a step that is initialized in while the kuberntes bootstrap.
it was working the last 2 years with the AMI from CoreOs and even until KOPS 1.16.

but anyways, this is working for now. thanks

**Comment by hakman** [comment]
There are some differences in what you expect and how Kops actually works, with some reason behind them. At the moment, when the Calico/Canal manifest is created there is no way to know what OS will be started on nodes and if all nodes are the same. It is up to the operator to configure the correct k8s plugin dir via the `spec.kubelet.volumePluginDirectory` option
In any case, I doubt anyone will spend time to find a better fix just for CoreOS/FlatCar. 

This broke because of changes in Calico/CoreOS, not Kops, and has been like this for more than 1 year, including in Kops 1.16:
https://docs.projectcalico.org/reference/faq#are-the-calico-manifests-compatible-with-coreos
