### ISSUE TITLE
Kops delete cluster on AWS could not finish successfully 

### ISSUE THREAD

**Issue by yingxia2020** [kubernetes/kops#9578]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
$ kops version
Version 1.17.1 (git-4dfd4779fe)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Not related. 

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
$ kops delete cluster --name ${KOPS_CLUSTER_NAME} --yes
kops create cluster -> kops update cluster -> kops validate cluster -> kops delete cluster

**5. What happened after the commands executed?**
It keeps looping for a long time, could not finish the deletion by itself.

iam-role:nodes.krzys.k8s.local  error deleting resources, will retry: error deleting IAM role "nodes.krzys.k8s.local": DeleteConflict: Cannot delete entity, must detach all policies first.
        status code: 409, request id: dc83049e-3744-4e82-ad20-a712d8082ff5
iam-role:masters.krzys.k8s.local        error deleting resources, will retry: error deleting IAM role "masters.krzys.k8s.local": DeleteConflict: Cannot delete entity, must detach all policies first.
        status code: 409, request id: 19e590c3-83f3-400e-a1cd-788be3d35aee
vpc:vpc-0d4d613d4a27a8b27       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        vpc:vpc-0d4d613d4a27a8b27
        iam-role:nodes.krzys.k8s.local
        iam-role:masters.krzys.k8s.local
        dhcp-options:dopt-0087a99ff66e7b85f
iam-role:masters.krzys.k8s.local        error deleting resources, will retry: error deleting IAM role "masters.krzys.k8s.local": DeleteConflict: Cannot delete entity, must detach all policies first.
        status code: 409, request id: 4d57b0b2-1d69-41ab-85a4-f87d5fc78a0e
iam-role:nodes.krzys.k8s.local  error deleting resources, will retry: error deleting IAM role "nodes.krzys.k8s.local": DeleteConflict: Cannot delete entity, must detach all policies first.
        status code: 409, request id: 20349b44-6b71-44a0-820d-31e7207d1837
vpc:vpc-0d4d613d4a27a8b27       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        dhcp-options:dopt-0087a99ff66e7b85f
        vpc:vpc-0d4d613d4a27a8b27
        iam-role:nodes.krzys.k8s.local
        iam-role:masters.krzys.k8s.local
......
......        
vpc:vpc-0d4d613d4a27a8b27       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        vpc:vpc-0d4d613d4a27a8b27
        dhcp-options:dopt-0087a99ff66e7b85f
vpc:vpc-0d4d613d4a27a8b27       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        dhcp-options:dopt-0087a99ff66e7b85f
        vpc:vpc-0d4d613d4a27a8b27
......                                                                                <-- I go to AWS console and delete the VPC myself, no dependencies found
vpc:vpc-0d4d613d4a27a8b27       ok
dhcp-options:dopt-0087a99ff66e7b85f     ok
Deleted kubectl config for krzys.k8s.local

**6. What did you expect to happen?**
Delete without errors

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
It happens recently, did not see the problem before. I also upgrade KOPS version from 1.16.0 to 1.17.1, still the same thing.
Have to delete both role policies and VPC manually now for the "kops delete cluster" to finish running.

The 3 policies attached to both of the cluster roles are:
$ CloudWatchAgentServerPolicy
$ AmazonSSMManagedInstanceCore
$ AmazonSSMDirectoryServiceAccess

**Comment by yingxia2020** [comment]
I just tried with the newest version: v1.19.0-alpha.1, the first problem is fixed (better cherry pick to older KOPs versions) and the second problem, vpc created for the cluster could not get deleted, still exist.

I0716 12:19:12.143330    3824 errors.go:32] unexpected aws error code: "InvalidVolume.NotFound"
volume:vol-0a5c8f48f0a566199    ok
subnet:subnet-0181434e9271ad60d ok
security-group:sg-0101ef7bfb265adaf     ok
internet-gateway:igw-0f2e43c5ab95d0bb6  ok
route-table:rtb-01a680b976ff6157e       ok
vpc:vpc-0548a7d959f7f206f       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        dhcp-options:dopt-02f4c6d4ed9ce64a3
        vpc:vpc-0548a7d959f7f206f
vpc:vpc-0548a7d959f7f206f       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        vpc:vpc-0548a7d959f7f206f
        dhcp-options:dopt-02f4c6d4ed9ce64a3
vpc:vpc-0548a7d959f7f206f       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        vpc:vpc-0548a7d959f7f206f
        dhcp-options:dopt-02f4c6d4ed9ce64a3

**Comment by hakman** [comment]
Thanks for reporting this, but I think you missed some of the steps when creating the issue, which most likely would help reproduce the problem. Please provide all the steps and changes to the cluster spec.

**Comment by yingxia2020** [comment]
Inside .bashrc file:
# for AWS kops
export bucket_name=XXX-kops-state-store
export KOPS_CLUSTER_NAME=XXX.k8s.local
export KOPS_STATE_STORE=s3://${bucket_name}
export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)

   47  kops create cluster --master-count=1 --node-count=1 --node-size=m5.xlarge --zones=us-west-2a --name=${KOPS_CLUSTER_NAME}
   48  kops describe secret
   49  kops update cluster --name ${KOPS_CLUSTER_NAME} --yes
   50  kops delete cluster --name ${KOPS_CLUSTER_NAME} --yes

We have been using KOPs to create and tear down k8s clusters on AWS with the steps like shown above. Seems AWS make some changes themselves recently. It is very easy to reproduce the problem.

**Comment by hakman** [comment]
I am asking because it is *very* strange. We are running frequent tests that are doing pretty much the same thing:
https://testgrid.k8s.io/kops-versions#kops-aws-k8s-latest
```bash
kops create cluster --name e2e-kops-aws-k8s-latest.test-cncf-aws.k8s.io \
    --ssh-public-key /workspace/.ssh/kube_aws_rsa.pub \
    --node-count 4 --node-volume-size 48 --master-volume-size 48 --master-count 1 \
    --zones eu-west-2a --master-size c5.large \
    --kubernetes-version https://storage.googleapis.com/kubernetes-release-dev/ci/v1.19.0-beta.2.607+4c853bb28f57f8 \
    --admin-access 35.193.58.157/32 --cloud aws --override cluster.spec.nodePortAccess=0.0.0.0/0 \
    --yes
```

This is why this is a bit strange...

**Comment by hakman** [comment]
One small difference is that we use `kops validate cluster` to make sure that all resources are up and running, but seems unlikely.
Also, there is no mention in the Kops code about those policies:
```
CloudWatchAgentServerPolicy
AmazonSSMManagedInstanceCore
AmazonSSMDirectoryServiceAccess
```

**Comment by yingxia2020** [comment]
I first use releases 1.16.0, 1.17.1, it has both 3 policies and VPC problems

The latest build I got to test is v1.19.0-alpha.1, it does not have the 3 policies issue already, only has VPC problem.
CloudWatchAgentServerPolicy
AmazonSSMManagedInstanceCore
AmazonSSMDirectoryServiceAccess

 I could see your daily test is v1.19.0-beta.2, maybe that problem is fixed very recently already?

**Comment by hakman** [comment]
I don't think it's fixed, but it's very simple to try:
```bash
wget https://storage.googleapis.com/kops-ci/bin/1.19.0-alpha.2+9d675e3f5c/linux/amd64/kops
export KOPS_BASE_URL=https://storage.googleapis.com/kops-ci/bin/1.19.0-alpha.2+9d675e3f5c
./kops create ...
...
```

**Comment by yingxia2020** [comment]
I just run with the link you gave me 1.19.0-alpha.2, still only VPC could not get deleted. It has to be deleted from AWS CLI or console manually.

volume:vol-091f75fd3a5bcbbb4    still has dependencies, will retry
volume:vol-0f1c4dff002679202    ok
volume:vol-0f89365639ae0af8d    ok
subnet:subnet-09f185ab6b2ef40c8 still has dependencies, will retry
internet-gateway:igw-09526afac85278b6a  still has dependencies, will retry
security-group:sg-0ff4a1493d370e47b     still has dependencies, will retry
security-group:sg-06b7c616c3459b54b     ok
I0717 00:11:34.351232   20361 errors.go:32] unexpected aws error code: "InvalidVolume.NotFound"
volume:vol-056182dfecb875ef8    ok
Not all resources deleted; waiting before reattempting deletion
        route-table:rtb-0dee7a117a8383a43
        subnet:subnet-09f185ab6b2ef40c8
        security-group:sg-0ff4a1493d370e47b
        vpc:vpc-0e1746e4535a4545a
        internet-gateway:igw-09526afac85278b6a
        dhcp-options:dopt-0534341dd6b670ddb
        volume:vol-091f75fd3a5bcbbb4
I0717 00:11:44.613180   20361 errors.go:32] unexpected aws error code: "InvalidVolume.NotFound"
volume:vol-091f75fd3a5bcbbb4    ok
subnet:subnet-09f185ab6b2ef40c8 ok
security-group:sg-0ff4a1493d370e47b     ok
internet-gateway:igw-09526afac85278b6a  ok
route-table:rtb-0dee7a117a8383a43       ok
vpc:vpc-0e1746e4535a4545a       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        vpc:vpc-0e1746e4535a4545a
        dhcp-options:dopt-0534341dd6b670ddb
vpc:vpc-0e1746e4535a4545a       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        dhcp-options:dopt-0534341dd6b670ddb
        vpc:vpc-0e1746e4535a4545a
vpc:vpc-0e1746e4535a4545a       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        vpc:vpc-0e1746e4535a4545a
        dhcp-options:dopt-0534341dd6b670ddb
vpc:vpc-0e1746e4535a4545a       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        dhcp-options:dopt-0534341dd6b670ddb
        vpc:vpc-0e1746e4535a4545a
vpc:vpc-0e1746e4535a4545a       still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
        dhcp-options:dopt-0534341dd6b670ddb
        vpc:vpc-0e1746e4535a4545a
......

**Comment by hakman** [comment]
Maybe you can find out what exactly is the dependency. As you can see, this seems to be somehow related the AWS account your are using.

**Comment by yingxia2020** [comment]
When I delete from AWS console, there are no dependencies found for that VPC, it could be deleted right away.

Those IAM permission are also set from day one:
AmazonEC2FullAccess
AmazonRoute53FullAccess
AmazonS3FullAccess
IAMFullAccess
AmazonVPCFullAccess

**Comment by hakman** [comment]
This has nothing to do with the IAM permissions set by Kops.
There are some hanging resources in that VPC that Kops is not seeing and keep it from being deleted.
Kops is deleting only resources that it owns, to prevent accidental deletion in shared envs.

As I said before, this is only happening in your environment, so there is something special about it that only you can identify.

**Comment by hakman** [comment]
I added some extra logging around the deleted resources to get an idea what is the resource that cannot be deleted.
If you don't mind, could you try again with this new build?
```bash
$ wget https://storage.googleapis.com/kops-ci/bin/1.19.0-alpha.2+90ec586ef3/linux/amd64/kops
$ export KOPS_BASE_URL=https://storage.googleapis.com/kops-ci/bin/1.19.0-alpha.2+90ec586ef3
$ ./kops create ...
$ ...
```

**Comment by yingxia2020** [comment]
Thanks a lot for the efforts. Just run with your build, not much useful information found.
......
Not all resources deleted; waiting before reattempting deletion
        vpc:vpc-05ceaf96248cd6c15
        route-table:rtb-001da1aab28549ac3
        security-group:sg-0cb90df159305009e
        volume:vol-02894c52bca090ec2
        subnet:subnet-004d231621ed66b89
        dhcp-options:dopt-0a57eb9647d621f2e
I0720 10:16:12.236166   12747 errors.go:32] unexpected aws error code: "InvalidVolume.NotFound"
volume:vol-02894c52bca090ec2    ok
subnet:subnet-004d231621ed66b89 ok
security-group:sg-0cb90df159305009e     ok
route-table:rtb-001da1aab28549ac3       ok
vpc:vpc-05ceaf96248cd6c15       still has dependencies, will retry: DependencyViolation: The vpc 'vpc-05ceaf96248cd6c15' has dependencies and cannot be deleted.
        status code: 400, request id: 7afaf8a8-3ed3-4936-99f5-a9392c18129e
Not all resources deleted; waiting before reattempting deletion
        dhcp-options:dopt-0a57eb9647d621f2e
        vpc:vpc-05ceaf96248cd6c15
vpc:vpc-05ceaf96248cd6c15       still has dependencies, will retry: DependencyViolation: The vpc 'vpc-05ceaf96248cd6c15' has dependencies and cannot be deleted.
        status code: 400, request id: 55e47a11-20ce-4317-a50d-d72a04b0cd3a
Not all resources deleted; waiting before reattempting deletion
        dhcp-options:dopt-0a57eb9647d621f2e
        vpc:vpc-05ceaf96248cd6c15
vpc:vpc-05ceaf96248cd6c15       still has dependencies, will retry: DependencyViolation: The vpc 'vpc-05ceaf96248cd6c15' has dependencies and cannot be deleted.
        status code: 400, request id: ee5d13a3-48b1-462d-8a6b-695a7de8a50f
Not all resources deleted; waiting before reattempting deletion
        vpc:vpc-05ceaf96248cd6c15
        dhcp-options:dopt-0a57eb9647d621f2e

**Comment by hakman** [comment]
Happens sometimes. Could you also try this guide, mostly to see what are those deps?
https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-dependency-error-delete-vpc/

**Comment by yingxia2020** [comment]
Thanks for the info, I did see the following when I run the commands recommended in that page:

$ aws ec2 describe-route-tables --filters 'Name=vpc-id,Values='$vpc | grep RouteTableId
            "RouteTableId": "rtb-08bbfb1a81d4acc04"
            "RouteTableId": "rtb-08bbfb1a81d4acc04",

awsuser@t-ProLiant-DL380-Gen9:~$ aws ec2 describe-network-acls --filters 'Name=vpc-id,Values='$vpc | grep NetworkAclId
            "NetworkAclId": "acl-0f57f7e4f2e85cf9a",

$ aws ec2 describe-security-groups --filters 'Name=vpc-id,Values='$vpc | grep GroupId
            "GroupId": "sg-050095ba24851b11f"
            "GroupId": "sg-050095ba24851b11f"
            "GroupId": "sg-0bdd595eb8bbe9259"

**Comment by hakman** [comment]
Could you check the origin of each of these resources? Maybe there is some clue what created them in tags.

**Comment by yingxia2020** [comment]
All the other resources do not have TAGs except this one

"GroupId": "sg-0bdd595eb8bbe9259"    description: FMS managed security group.

Kep                Value
FMManaged | 14033522-6e44-4847-bb2e-c3833b1ac9ef
fms-policy-name | SecurityGroupsCommonsPolicy

**Comment by hakman** [comment]
I think you can try deleting "sg-0bdd595eb8bbe9259" manually to confirm that this is the thing that is blocking the "cluster delete".
I guess you should know more about Firewall Manager and how to control it. If you can add a tag like `kubernetes.io/cluster/<CLUSTER_NAME>: owned`, Kops should know to delete it.

**Comment by yingxia2020** [comment]
Thanks, that seems to be the root cause, I add that tag and rerun kops delete, it could delete without any problems.

**Comment by hakman** [comment]
👍

**Comment by yingxia2020** [comment]
To use AWS firewall manager
1.  Your account must be a member of an organization in the AWS Organizations service
2.  Set the AWS Firewall Manager administrator account

My account happens to be an organization account but I do not have admin account. Our admin may created a common security group and applied to all the organization accounts. So all the newly created VPC will be attached with that common security group. Right now I could not see it or modify the rules. It will be perfect if kops could ignore this specially created security group when delete VPC. 

https://docs.aws.amazon.com/waf/latest/developerguide/create-policy.html#creating-firewall-manager-policy-common-security-group

**Comment by hakman** [comment]
At the moment, Kops can only delete resources tagged as described above. I created an issue to debate how address this with others, but that will take time.
The logic is a bit complicate and there is no quick solution from Kops side. I would suggest to contact your org admin and see if you can find a solution together.

**Comment by yingxia2020** [comment]
Sure, no problem, thanks for the suggestions.

I did contact our IT department for the help already. Should I close this issue now?

**Comment by hakman** [comment]
Thanks for the update.
Yes, I think the issue can be closed now. Any discussion regarding a possible fix will be done in the new issue, in case you want to follow.
