### ISSUE TITLE
Using AWS ALB instead of ELB for kubernetes API server

### ISSUE THREAD

**Issue by mohammadasim** [kubernetes/kops#9586]
I wanted to protect our API server with AWS WAF. However, AWS WAF only works with AWS ALB. I searched a way to configure kops to replace the current ELB with the new generation AWS ALB but couldn't find any resource on that. The question is, can we configure kops to provision an AWS ALB instead of AWS ELB when creating a kubernetes cluster and is there a way to migrate the current ELB to ALB using kops? If these features are not part of kops is there a way to add these features?

Thanks,

**Comment by hakman** [comment]
At the moment, this is not possible. There is an effort in https://github.com/kubernetes/kops/pull/9011 to add support for NLB.

Both ALB and NLB have various inconveniences compared to Classic ELB:
* ALB requires at least 2 AZs
* NLB cannot handle internal traffic from same node

**Comment by rifelpet** [comment]
With basic auth support being removed in Kubernetes 1.19, there would be no way for the cluster admin credentials generated by `kops export kubecfg` to work with a load balancer that only offers HTTP and HTTPS listeners. kops's admin credentials use client certificate authentication which requires a TCP listener, therefore I don't see ALB support as feasible.

Kops 1.19 will include NLB support so those looking to move away from classic load balancers will have the option to do so. In fact the most recent Kops 1.19 beta release includes support for NLBs and ACM certificates and any feedback would be much appreciated.

/close
