### ISSUE TITLE
Should they use RWMutex?

### ISSUE THREAD

**Issue by dddddai** [kubernetes/kops#9588]
There are some places where we could use RWMutex instead of Mutex to avoid the contetion between readings.

For example:
https://github.com/kubernetes/kops/blob/856d5815a3159ef27f3c143ff02bfd26eb16d662/cloudmock/aws/mockec2/internetgateways.go#L43-L52
https://github.com/kubernetes/kops/blob/856d5815a3159ef27f3c143ff02bfd26eb16d662/cloudmock/aws/mockec2/subnets.go#L47-L56
https://github.com/kubernetes/kops/blob/b6c849cfb7263c04129dded841888bb645a03b39/cloudmock/aws/mockiam/iamrole.go#L82-L104

**Comment by johngmyers** [comment]
I think finely tuning the multithreading performance of the mock libraries is perhaps not the best area to spend effort on.
