### ISSUE TITLE
allocate-node-cidrs=true and AWS CNI

### ISSUE THREAD

**Issue by ltagliamonte-dd** [kubernetes/kops#9591]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.17.0
```
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
```
AWS with AWS CNI as network overlay
```

From a log search i stumbled upon the following repeating error log in my controller-mananger:
```
I0717 16:39:44.076503       1 event.go:274] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-172-30-72-118.us-west-2.compute.internal", UID:"aba054cf-1e85-4bdb-aef0-c4197839af77", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'CIDRNotAvailable' Node ip-172-30-72-118.us-west-2.compute.internal status is now: CIDRNotAvailable
I0717 16:39:44.091602       1 controller_utils.go:179] Recording status change CIDRNotAvailable event message for node ip-172-30-99-210.us-west-2.compute.internal
E0717 16:39:44.091632       1 controller_utils.go:254] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
```

After a bit of investigation i think that this error message is caused by `--allocate-node-cidrs="true"` in my controller manager configuration.

my `--cluster-cidr=` uses a /17 and the `--node-cidr-mask-size="24"` so after 128 nodes this error will show up.

From the kubernetes [doc](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#kubenet) this flag should be used only by the `Kubenet network mode` and it should be to false for all the other CNIs. (please correct me if I'm wrong)

Is what i gathered correct?
Is it safe to turn off this flag? Does KOPS allows to do it? Shouldn’t KOPS set this to false when something different from Kubenetes network mode is used?

**Comment by ltagliamonte-dd** [comment]
@justinsb @hakman @johngmyers any idea? (pinging you because you are the main contributors to this repo)

**Comment by hakman** [comment]
@ltagliamonte-dd Sorry, but I am not very familiar with this. I doubt `--allocate-node-cidrs="true"` is needed only for Kubenet, as it is part of the instructions for some other network plugins: https://docs.cilium.io/en/v1.8/gettingstarted/requirements_intro/.

I think you can easily disable and tweak the above flags with Kops and see if you find a working config. Also, you may want to try asking about this in the `#kops-users` Slack channel.

**Comment by ltagliamonte-dd** [comment]
reposted the issue on the kops slack channel:
https://kubernetes.slack.com/archives/C3QUFP0QM/p1596050352168200
solved by setting `allocateNodeCIDRs: false`

**Comment by hakman** [comment]
👍
