### ISSUE TITLE
Improve E2E test coverage

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#9598]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Kops has many periodic prow jobs that run the kubernetes e2e suite against various combinations of k8s versions, OS, CNI, cloud provider, and cpu architecture.

However there is a lot of kops functionality not covered by e2e tests:

- Upgrading & downgrading Kops
- Upgrading & downgrading Kubernetes / etcd / CNI providers
- Applying & upgrading & downgrading all of the miscelaneous "bootstrapchannelbuilder" manifests
- Terraform & Cloudformation targets
- Rolling Updates
- Almost all feature flags
- Many API fields that aren't settable via `kops create cluster`, requiring a manifest file and `kops replace -f`

Adding test coverage for these scenarios would require significant changes to kubetest (our e2e runner) which is in [maintenance mode](https://github.com/kubernetes/test-infra/tree/master/kubetest#deprecation-notice) so I'm proposing that we reevaluate how we run our e2e jobs. https://github.com/kubernetes/kops/pull/8605 was open as an experiment but I think we should settle on a design proposal before we merge anything.
 

The kubetest logic that we currently use involves:

1. download or build the appropriate kops version
2. download and extract the appropriate k8s version
3. choose a region
4. run the `kops create cluster` with the appropriate flags and wait for validation to pass
5. download and run the appropriate k/k e2e test suite
6. dump node logs and troubleshooting info
7. tear down the cluster
8. publish the kops "version marker" if applicable

Of the above steps, less than half are also used by other projects. In order to cover the areas mentioned above we would need to add a significant amount of kops-specific testing logic. I'm wondering if it makes more sense to have our test runner code live in the kops repo rather than test-infra. We could consider vendoring the necessary kubetest (or kubetest2) logic for some of the above steps, but keeping most of the development in the kops repo allows us to iterate faster by not requiring approvals from outside our OWNERS. It also reduces potential impact or compromises necessary for a "shared" tool like kubetest2.

**2. Feel free to provide a design supporting your feature request.**

Some concerns:
* Do we continue to use go for consistency? It would allow us to vendor certain logic from test-infra. If we choose a different language or technology like Jupyter it would involve additional effort to get working in prow jobs.
* Does each job compile the runner code each time or do we publish a runner artifact/image similar to our existing kops version markers?

Anyone have any other thoughts or suggestions?

**Comment by johngmyers** [comment]
I don't know Jupyter and can't tell what advantages it brings as an e2e framework, much less whether those advantages are worth the cost to contributors of having to learn a completely new framework.

**Comment by hakman** [comment]
I would say that most important at the moment would be to test Kubernetes upgrades, which would also mean rolling upgrade and maybe network plugin upgrades, depending on how cluster is created.
This may be a pretty small change in kubetest.
Also, may be worth a try to add one of us in the OWNERS file for kubetest.

**Comment by johngmyers** [comment]
I envision a basic upgrade test as:

* Deploy X and wait for it to validate (as in current tests)
* Call `kops set cluster` to request Y
* Run `kops update cluster --yes`
* Run `kops rolling-update cluster --yes` and verify it completes.
* Maybe verify that `kops rolling-update cluster` doesn't find any NeedUpdate nodes.
* Run some subset of the e2e tests.

If we want to test upgrading kops we would need some way of having the initial deployment use a different kops version. The first kops would be an official build, the second the CI-built version. If testing downgrade, reverse that.

I can't think of a good way to have the test assert the upgrade is not disruptive.

**Comment by rifelpet** [comment]
Those steps sound reasonable to me for an upgrade / rolling-update test.

sig-testing has been pretty adamant about kubetest being maintenance-only. Supporting those steps would involve supporting a secondary kops version to for certain commands as well as additional kops commands to be shelled out. I'm not sure if they'd be receptive to adding that much "feature work" to kubetest.

Also since the kubetest project is rather flat (all kops code lives in the same package as all the other code) I dont know if they'd be willing to add us as an OWNER. Perhaps we could move the kops code to its own directory but that might be complex and against the spirit of maintenance-only as well :/ This is why I was leaning towards having the e2e tests live in the kops repo.

**Comment by johngmyers** [comment]
I would agree with moving the e2e runner into the kops repo

**Comment by olemarkus** [comment]
I think that running the full e2e suites on various configurations should still be done with kubetest. Seems a bit much to roll our own there. Looks like kubetest2 has a package per provider for spinning up the cluster, so maybe we can be OWNER there. I think a must is that we can feed kops spec files rather than relying only on flags though.

When it comes to upgrading/rolling-update tests, I don't think we need to do a full e2e run afterwards. Here we are probably good if we just end up with a valid cluster.

**Comment by hakman** [comment]
@olemarkus I ended up with 2 valid clusters in the last week and both were not working correctly...

**Comment by olemarkus** [comment]
To some extent a different problem. I think our cluster validation is a bit weak. I had a valid cluster with the pod networking completely broken a few days ago (vxlan being firewalled). kube-system only have privileged hostnetwork pods, or pods that do not really have health checks (kops-controller).
I have been contemplating having a sort of health check pod that e.g pings wellknown servers, hits the kube api (maybe both api.internal, api, and kubernetes.default) etc and fails its own health check based on that.

**Comment by johngmyers** [comment]
Cluster validation is not intended to be an e2e test. It's basically to detect when a cluster is not ready to take further disruption.

An upgrade test should run a minimal "smoke test" set of the e2e tests. Is the "updown" set usable for this?

**Comment by hakman** [comment]
> An upgrade test should run a minimal "smoke test" set of the e2e tests. Is the "updown" set usable for this?

I would vote for the networking tests. At least the fast ones.

**Comment by rifelpet** [comment]
It looks like kubetest2 is now its own repo: https://github.com/kubernetes-sigs/kubetest2

It's organized by "deployer" so if we were to use that repo we would probably get a `kubetest2-kops` directory. Whether we could be added to that directory's OWNERS is a different question.

Another option would be to vendor kubetest2's pkg directory which has the bulk of the logic (most of the numbered list from I mentioned above).

I think its certainly worth asking sig-testing if they'd allow us to be approvers for a kubetest2-kops directory.

**Comment by rifelpet** [comment]
/remove-lifecycle rottena

this is in progress with the kubetest2 efforts
