### ISSUE TITLE
Docker-CE Version issue with latest KOPS AWS AMI.

### ISSUE THREAD

**Issue by shahamit2** [kubernetes/kops#9601]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.17.0 and 1.17.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.17.8 and 1.17.9

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops/v1alpha2 object is defined and being created for each env based on values passed through Ansible.

**5. What happened after the commands executed?**
ELB is not registering Master.  Console log on master node shows below message.
Execute command: /var/cache/kubernetes-install/nodeup --conf=/var/cache/kubernetes-install/kube_env.yaml --v=8
Error Message: stderr: 'error: error creating cluster: spec.docker.version: Unsupported value: "19.03.12": supported values: "17.03.2", "17.09.0", "18.03.1", "18.06.1", "18.06.2", "18.06.3", "18.09.3", "18.09.9", "19.03.4", "19.03.8", "19.03.11"'

AMIs in us-west-2 region: -
k28s-1.17.9-kops-1.17.1-debian-buster-amd64-hvm-202007170947 :: ami-0b6be61befe224a1b
k28s-1.17.8-kops-1.17.1-debian-buster-amd64-hvm-202007061103 :: ami-02f065bc881daef1b
k28s-1.17.8-kops-1.17.1-debian-buster-amd64-hvm-202007060721 :: ami-04a109f1a09c7c52f
k28s-1.17.8-kops-1.17.1-debian-buster-amd64-hvm-202007060659 :: ami-072a0f00b6b655393
k28s-1.17.8-kops-1.17.0-debian-buster-amd64-hvm-202007010746 :: ami-01c9a0a4c0de19197

Below AMI in us-west-2 region has different default docker-ce version installed.
k28s-1.17.8-kops-1.17.0-debian-buster-amd64-hvm-202006271839 :: ami-08d2225eb407971d6
default docker version: 19.03.8, build afacb8b7f0
Error Message: I0720 09:54:03.268951 3971 changes.go:81] Field changed "Version" actual="5:19.03.8~3-0~debian-buster"
expected="19.03.4~3-0~debian-buster"

**6. What did you expect to happen?**
AMI should have compatible version of docker-ce installed .

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
Not available.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
[console_output_5.txt](https://github.com/kubernetes/kops/files/4946978/console_output_5.txt)

**9. Anything else do we need to know?**
[console_output_4.txt](https://github.com/kubernetes/kops/files/4946979/console_output_4.txt)

**Comment by hakman** [comment]
Sorry to see that you have issues, but, in order to help you, you would have to provide the info required in the ticket, like cluster spec. Other than that:
1. It is 100% correct, Docker *19.03.12* is not supported at the moment, latest supported version is *19.03.11*.
2. The images that you are using seem to be custom and you should contact the person maintaining them for compatibility info.

**Comment by shahamit2** [comment]
@hakman Thanks for quick review and confirmation. I think both your points helps with path forward and checking now how to find and reach out to maintainer of the custom image.

**Comment by shahamit2** [comment]
Final comment for FYI: I could not find the forum to reach out to community. But issue is certainly due to pre-installed higher docker version in AMI.

**Comment by hakman** [comment]
Thanks for the update @shahamit2.
Not sure what the reason was for using a custom image, but maybe you can try moving to an official Debian or Ubuntu one.
We have regular tests on those and should have no problems.

**Comment by shahamit2** [comment]
Thank you @hakman for information. I think I will start with what you have suggested.

**Comment by hakman** [comment]
👍
