### ISSUE TITLE
Security groups not assigned to clusters created using LaunchConfigurations

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#9602]
The periodic e2e tests for LaunchConfigurations is failing:
https://testgrid.k8s.io/kops-misc#kops-aws-launchconfigurations

The reason is that the SecurityGroups are not assigned correctly when the cluster is created:
```bash
$ KOPS_FEATURE_FLAGS=-EnableLaunchTemplates .build/local/kops create cluster --name k8s.test.com \
    --ssh-public-key ~/.ssh/id_rsa.pub \
    --node-count 1 --node-volume-size 10 --master-volume-size 10 --master-count 1 \
    --zones eu-central-1a --kubernetes-version 1.18.6 --cloud aws --yes

$ KOPS_FEATURE_FLAGS=-EnableLaunchTemplates .build/local/kops update cluster --name k8s.test.com
...
Will modify resources:
  LaunchConfiguration/master-eu-central-1a.masters.k8s.test.com
  	SecurityGroups      	 [] -> [name:masters.k8s.test.com id:sg-0de44e63565cdac56]

  LaunchConfiguration/nodes-eu-central-1a.k8s-test.test.com
  	SecurityGroups      	 [] -> [name:nodes.k8s.test.com id:sg-0d0a8fb4f6cf3b344]

```

**Comment by johngmyers** [comment]
I'm not able to reproduce this. Could you provide verbose logs?

I do notice that the nodes launchconfiguration has an unexpected name. Normally I'd expect the launchconfiguration name to be suffixed by the cluster name.

The periodic e2e is flaky but not consistently failing. Frequently the test runner is not able to connect to some or all of the instances.

**Comment by hakman** [comment]
> The periodic e2e is flaky but not consistently failing. Frequently the test runner is not able to connect to some or all of the instances.

This happens because of the security group assignment. If I assign it manually, it works.

> I do notice that the nodes launchconfiguration in the initial description has an unexpected name. Normally I'd expect the launchconfiguration name to be suffixed by the cluster name.

Probably me redacting stuff...

**Comment by johngmyers** [comment]
I create a cluster and the subsequent update returns `No changes need to be applied`.

**Comment by johngmyers** [comment]
Looks like this might have been introduced by 87446f88940e7ed0d81e60128a56f0984b5c9a5c. By adding an explicit `GetDependencies` it lost the implicit dependencies found by reflection.  So probably doesn't affect 1.18

**Comment by hakman** [comment]
👍

**Comment by hakman** [comment]
I will do a few tests with 1.18 just to be sure, but seems to be pretty stable from what I tested until now.
