### ISSUE TITLE
Clusters created with Kubernetes 1.14 don't start

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#9604]
After latest bulk of merges, clusters fail to start for Kubernetes 1.11 - 1.14 and periodic tests fail:
https://testgrid.k8s.io/kops-versions#kops-aws-k8s-1.14

/cc @rifelpet @johngmyers

**Comment by rifelpet** [comment]
from the job output:
```
2020/07/20 14:44:17 process.go:153: Running: kubectl get nodes -ojson
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

That looks like the kubeconfig file is not being set properly. Is there a reason https://github.com/kubernetes/test-infra/pull/18373 was closed?

**Comment by hakman** [comment]
@rifelpet "admin" user is added automatically when "create cluster --yes" is used, that's why I closed it.

**Comment by johngmyers** [comment]
But the tests are doing `create cluster` without `--yes`. In that case no kubecfg is created.

**Comment by hakman** [comment]
@johngmyers you are partially correct. Tests for 1.15+ are run with a newer version of `kubetest` that creates a cluster with `--yes`. Older tests seem to run an earlier version that runs `update cluster --yes`.
Maybe we should just move all tests to latest `kubekins-e2e` image?
