### ISSUE TITLE
Use OpenStack external cloud controller by default

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#9619]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

in-tree legacy OpenStack cloudprovider is deprecated. This is used by default currently in kops. The recommended action is to move to use external cloud controller manager (external ccm)

**2. Feel free to provide a design supporting your feature request.**

when creating kops cluster using OpenStack we need to do currently following if we want use external ccm:

0) `export KOPS_FEATURE_FLAGS=EnableExternalCloudController`
1) kops create cluster ...
2) kops edit cluster
3) add following to spec:
```
cloudControllerManager: {}
```
4) kops update cluster like usually

So we need somehow add that spec modification automatically to OpenStack clusters

**Comment by chrislovecnm** [comment]
> So we need somehow add that spec modification automatically to OpenStack clusters

Can you creat the cluster using a yaml definition file to add that automatically? kops create -f ./my-cluster.yaml

**Comment by olemarkus** [comment]
The approach in #9625 looks good to me. For those who use cluster specs, we either have to respect what is in the spec or make the spec fail validation.
Technically, one can add the object in defaults.go, but I find the user experience around that to be quite confusing.

**Comment by olemarkus** [comment]
@zetaab now you can probably just set `cloudControllerManager: {}` in `components.openstack.go`. This would then default on both new and old clusters. You wouldn't have a way of disabling the external CCM, but we probably shouldn't support this either.
If we wanted to, we'd have to add an `Enabled` flag to the CCM spec.

**Comment by zetaab** [comment]
@olemarkus that sounds great if that works
