### ISSUE TITLE
Delete all dependencies when VPC is "owned"

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#9624]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

There are management tools that are used to manage access or resources at organisation level.
In some cases, these tools add extra security groups to the VPC and makes it impossible for `kops delete cluster` to finish the job. It is the case of AWS Firewall Manager, as described in https://github.com/kubernetes/kops/issues/9578#issuecomment-661264659.

**2. Feel free to provide a design supporting your feature request.**

Seems reasonable to assume that all security groups should be deleted in case the VPC is not shared (has the "owned" tag).
This should be done for all VPC dependencies that prevent its deletion.

**Comment by rifelpet** [comment]
the amazonvpc CNI will occasionally run into this issue as well:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-cni-amazon-vpc/1288078416746123264

my guess is that there are orphaned ENIs using a security group, causing the security group deletion to fail. We should extend the logic proposed in this issue to also apply to extra ENIs in the VPC when the VPC is being deleted.
