### ISSUE TITLE
unexpected error during validation: error listing nodes: Get https://api.cluster.aws-good.com/api/v1/nodes: EOF

### ISSUE THREAD

**Issue by mayankparekh** [kubernetes/kops#9631]
Hello All,

I am getting this error when I create the cluster, I can see the master and nodes created and also the load balancer, but the instance does not attached to the load balancer, it remains out of service.

I can also see the volumes got create for master instance but they do not attached.

$ kops version
Version 1.16.0-patch.1 (git-d4b865a5d)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-10T21:53:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding

**Comment by hakman** [comment]
Please provide the necessary information as described in the issue template. Without this, it is almost impossible to provide any help.
https://github.com/kubernetes/kops/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
