### ISSUE TITLE
Improve tagging story on AWS

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#9640]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Over time, AWS has added support for tagging certain resource types, as well as added support for tagging them in their Create call rather than with a separate `CreateTags` call.

For more info see these [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-resources)

One benefit of using "Tag on create" is to support finer grained IAM policies for the credentials used to run the kops cli. For example, one could restrict the policy to only create resources with certain tags to follow the security principle of least privilege.

The following table outlines Kops' tagging usage of relevant AWS resources. With this information we should be able to define a more restricted policy than what is documented [here](https://kops.sigs.k8s.io/getting_started/aws/#setup-iam-user). Perhaps on a separate page under Security or Advanced, to keep the getting started guide simple.

✅ - Implemented in Kops
⭕️ - Supported by AWS but not implemented in Kops
❌ - Not supported by AWS

| Resource Type | Tagging | Tag-on-create | IAM Policy condition support |
| - | - | - | - |
| AutoScalingGroup  |✅ |✅ |⭕️ |
| DHCP Options |✅ |✅ |⭕️ |
| Route53 Hosted Zone |⭕️ |❌ |❌ |
| EBS Volume |✅ |✅ |⭕️ |
| Elastic IP |✅ |✅ |⭕️ |
| IAM Instance Profile |✅ |✅ |⭕️ |
| IAM OIDC Provider |✅ |✅ |⭕️ |
| IAM Role |✅ |✅ |⭕️ |
| IAM Policy |❌ |❌ |❌ |
| Internet Gateway |✅ |✅ |⭕️ |
| LaunchTemplate |✅ |✅ |⭕️ |
| ELB |✅ |⭕️ |❌ |
| NAT Gateway |✅ |✅ |⭕️ |
| RouteTable |✅ |✅ |⭕️ |
| Security Group |✅ |✅ |⭕️ |
| SSH Key |✅ |✅ |⭕️ |
| Subnet |✅ |✅ |⭕️ |
| VPC |✅ |✅ |⭕️ |

I left off these resources from our awstasks package because I don't see AWS ever adding tagging support: Route53 Record, Route, Security Group Rule, and any attachments or associations.

Any ⭕️ are tasks we could work on. 

~~UPDATE: well I'm a bit bummed out by the lack of policy condition support which means the more restrictive IAM policy won't be much different, but hopefully it will get better soon.~~

**Comment by rifelpet** [comment]
/remove-lifecycle stale

I reviewed the condition keys available for API actions [here](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html) and there is much better coverage of resource tags for EC2. I think it would be feasible to create a locked down IAM policy that has per-cluster permissions for the kops CLI and add it to the getting started documentation.

**Comment by olemarkus** [comment]
/remove-lifecycle stale

This has improved a lot lately
