### ISSUE TITLE
Add flag to skip the NTP task in NodeUp

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#9661]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

There are case in which operators don't want the settings provided by Kops and there are easy ways to include it in the base image or do something similar via hooks. One of the cases is: https://github.com/kubernetes/kops/issues/9307#issuecomment-643766267.

**2. Feel free to provide a design supporting your feature request.**

Main question is what flag to use for that:
* skipInstall - as for docker
* disabled
* unmanaged
* ...

**Comment by johngmyers** [comment]
Generally, I'd prefer we consistently use either `enabled: false` or `enableFoo: false`.

**Comment by hakman** [comment]
> Generally, I'd prefer we consistently use either `enabled: false` or `enableFoo: false`.

Good point, but `enabled` implies management of some sort, so operators might expect `enabled: false` to disable `Foo`.
