### ISSUE TITLE
v1.18.0 AMI

### ISSUE THREAD

**Issue by lee5i3** [kubernetes/kops#9680]
kops v1.18.0

We use to be using the AMI: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20

We are looking to upgrade to 1.18.0 but it shows using an AMI: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716

This looks like a mistake as its using someones AWS account id, was this correct?

**Comment by johngmyers** [comment]
That is correct.
/close

**Comment by rifelpet** [comment]
To add further context, that account ID is the official ubuntu account: https://help.ubuntu.com/community/EC2StartersGuide#Official_Ubuntu_Cloud_Guest_Amazon_Machine_Images_.28AMIs.29 Further, you can use the AMI Locator on that page to confirm the AMI ID kops is assigning matches one of the official AMIs mentioned on the ubuntu website.
