### ISSUE TITLE
Docker containers created by docker commands in latest ami images can not reach internet

### ISSUE THREAD

**Issue by kimxogus** [kubernetes/kops#9688]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.18.0`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
run `kops upgrade cluster --yes` after update kops from `1.17.1` to `1.18.0`

**5. What happened after the commands executed?**
Docker containers in nodes created by docker commands cannot reach internet.
- In node shell or k8s pod using dind image(using `/var/run/docker.sock` host path socket volume)
```bash
ubuntu@ip-10-10-101-62:~$ sudo docker run --rm alpine ping 8.8.8.8
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
df20fa9351a1: Already exists
Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
Status: Downloaded newer image for alpine:latest
PING 8.8.8.8 (8.8.8.8): 56 data bytes
^C
--- 8.8.8.8 ping statistics ---
17 packets transmitted, 0 packets received, 100% packet loss
```

- With `--network=host`, container can reach internet.
```bash
ubuntu@ip-10-10-101-62:~$ sudo docker run --network=host --rm alpine ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=104 time=26.942 ms
64 bytes from 8.8.8.8: seq=1 ttl=104 time=26.744 ms
^C64 bytes from 8.8.8.8: seq=2 ttl=104 time=26.980 ms

--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 26.744/26.888/26.980 ms
```
This only happens with latest ami images(tested both `099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716`, `kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20`). After reverting ami image to `kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17`, the issue was gone.

**6. What did you expect to happen?**
Docker containers created by docker commands. This could be critical to some workloads like ci pipeline in k8s which build docker images. Without `--network=host` or old ami images, internet connecting commands like `apk update` or `apk add` doesn't work.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

As this issue was gone after downgraded to `kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17`, it seems that some change caused this issue. so my cluster manifest doesn't look needed.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I also tried re-enabling `docker.healthCheck` to `true`(which is disabled by default in 1.18), it didn't help.

**Comment by linecolumn** [comment]
I have use case for running docker command from the pod, bottom line is that following worked up to KOPS v1.17.1, and stopped with KOPS v1.18 (same AMI)

Executing on workers:
```
worker kops v1.17 # docker run -ti alpine ping google.com
PING google.com (172.217.7.206): 56 data bytes
64 bytes from 172.217.7.206: seq=0 ttl=112 time=0.699 ms
64 bytes from 172.217.7.206: seq=1 ttl=112 time=0.662 ms
```

But, when using KOPS v1.18, this is not working:

```
worker kops v1.18 # docker run -ti alpine ping google.com
ping: bad address 'google.com'
```

Same HostOS - Focal  (tried with Buster), using same Kubernetes version (v1.17.9), etc. The only difference between working and non-working cases is KOPS major version. containerRuntime is docker, default.

This prevents me to upgrade to KOPS v1.18 and keep everything up2date.

Also, do note that adding --network host to above docker command fixes issue but I can't use it due other things.

**Comment by hakman** [comment]
Historically, the recommended way of running Docker for Kubernetes was with `--ip-masq=false --iptables=false`, most likely because kube-proxy and the network plugins also add changes to iptables and order really matters. There may be other implications, like security. Most of these interoperability issues may have been fixed now, but I cannot say if best to enable or disable those options.

In Kops 1.17 and older, Docker is started before Kops has a chance to set `--ip-masq=false --iptables=false` and so, the iptables rules are created. Rebooting the instance will remove those rules and you will see the same error you are seeing with Kops 1.18. You can also compare the output of `iptables-save` before and after the reboot.
Kops 1.18 changes the way Docker is installed and, without intention, fixes this unnoticed race condition.

Fast forward to solution, adding these in the cluster config should bring back the previous behaviour:
```yaml
  docker:
    ipMasq: true
    ipTables: true
```

Warning:
Kubernetes itself works without these setting and all tests pass without any issues. The only thing broken is Docker Engine, which is just a tool for running Kubernetes in this scenario. Enable these options only if needed.

**Comment by kimxogus** [comment]
@hakman  Thank you, setting `ipMasq: true` and `ipTables: true` resolved this issue for me.
I tried to apply these setting only to ci instance group but `.spec.docker` per each instance group doesn't seem to be applied, so I set them in cluster config, is this normal?

**Comment by hakman** [comment]
Cool! Thanks for confirming it's working.
For now, container runtime settings are only cluster wide.

**Comment by kimxogus** [comment]
Thank you 👍 
It would be great container runtime settings to be available in instance group setting.

**Comment by hakman** [comment]
Please add an issue for that and I will see what can be done.
