### ISSUE TITLE
Documentation Overview 

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#969]
Right now the Kops project is growing very quickly. As an attempt to put our best foot forward we would like to give our documentation a few iterations from an outside source.

This issue covers grammatical, and technical concerns within our documentation. Another proposal after this initial once over will scope out documentation structure and moving forward.

CC @evildandelioms

**Comment by WillPlatnick** [comment]
Count me in. Was just coming over to issues to put in an issue about creating a document that goes over how kops works and how it sets everything up.

**Comment by chrislovecnm** [comment]
Closing we have readme
