### ISSUE TITLE
Kops 1.18.0 - can't upgrade K8s to 1.18.6, update brakes IAM roles.

### ISSUE THREAD

**Issue by mprzygrodzki** [kubernetes/kops#9694]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.18.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.18.6

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops upgrade cluster --yes
kops update cluster --yes
kops rolling-update cluster --yes --instance-group master-eu-central-1a

**5. What happened after the commands executed?**

I've update kops from 1.17.2 to 1.18.0 - At first line i've discovered that all my custom policies attached to IAM roles for master/nodes we're removed - that didn't happen before. I've a lot of EC2 volumes attached to the pods, and after update i wasnt able to attach them back again due to error with authorization - i've resolved that by manually adding Tags to each EC2 volume with KubernetesCluster : MyClusterName.

I believe therefore master can't spin up correctly pods due to some security issues, there only protokube pod starting but it's unable to start, can't provide logs right now.

Anyway, reverting Kubernetes to 1.17.9 works fine, but again using command "kops update cluster" my IAM roles are broken.

**6. What did you expect to happen?**

Clean cluster upgrade.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

`apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-01-08T09:22:53Z"
  generation: 38
  name: staging.xxx.com
spec:
  api:
    loadBalancer:
      securityGroupOverride: sg-0acd7f18bf388fa87
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Name: staging-k8s-master
  cloudProvider: aws
  configBase: s3://clusters.staging.xxx.com/staging.xxx.com
  docker:
    version: 19.03.11
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
      volumeSize: 5
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
      volumeSize: 5
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    runtimeConfig:
      apps/v1beta1: "true"
      apps/v1beta2: "true"
      extensions/v1beta1/daemonsets: "true"
      extensions/v1beta1/deployments: "true"
      extensions/v1beta1/networkpolicies: "true"
      extensions/v1beta1/podsecuritypolicies: "true"
      extensions/v1beta1/replicasets: "true"
  kubeDNS:
    provider: CoreDNS
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    featureGates:
      PodPriority: "true"
  kubernetesApiAccess:
    < removed >
  kubernetesVersion: 1.17.9
  masterInternalName: api.internal.staging.xxx.com
  masterPublicName: api.staging.xxx.com
  networkCIDR: 172.30.0.0/16
  networkID: vpc-9b5838f0
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    < removed >
  subnets:
  - cidr: 172.30.32.0/19
    id: subnet-b61c46dd
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.30.0.0/22
    id: subnet-4d1c4626
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private`

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by rifelpet** [comment]
Can you include a redacted output of `kops update cluster` ? I'd like to see the changes being reported around EBS and IAM resources.
