### ISSUE TITLE
Missing cli options for kube-controller-manager and kube-scheduler

### ISSUE THREAD

**Issue by a8j8i8t8** [kubernetes/kops#9695]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`1.18.0`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`1.18.6`

**3. What cloud provider are you using?**
`aws`

**9. Anything else do we need to know?**
Kops doesn't provide a way to start kube-controller-manager and kube-scheduler with following options.
```
--authentication-kubeconfig
--authorization-kubeconfig
```

**Comment by rifelpet** [comment]
Adding support for these should just be a matter of adding the two fields to each of the KubeControllerManagerConfig and KubeSchedulerConfig types in the kops API and running `make apimachinery crds`. It needs to be in both the unversioned and versioned APIs:

https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go

https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/componentconfig.go

This is straight forward enough that I labeled it as good first issue in case anyone is interested in taking it on.

**Comment by Evalle** [comment]
I think I can take care of this issue
/assign

**Comment by dmcnaught** [comment]
I can't seem to set the options in kops 1.19.1
```yaml
kubeControllerManager:
  authenticationKubeconfig: /var/lib/kube-controller-manager/kubeconfig
  authorizationKubeconfig: /var/lib/kube-controller-manager/kubeconfig
kubeScheduler:
  authenticationKubeconfig: /var/lib/kube-scheduler/kubeconfig
  authorizationKubeconfig: /var/lib/kube-scheduler/kubeconfig```
