### ISSUE TITLE
Can't reach kube-dns service from pod on master

### ISSUE THREAD

**Issue by sweber83** [kubernetes/kops#970]
We tried to deploy a fluentd Daemonset on a Cluster that we setup with kops.
On the nodes everything is working fine, but on the master fluentd can't resolve any dns names.
I investigated further and noticed that from the fluentd pod one can't reach any kubernetes services.

I'm not really sure if this ist a kops or kubernetes issue.

**Comment by WillPlatnick** [comment]
I believe the problem was fixed in kubernetes and is scheduled for the 1.5 release. Issue can be found at https://github.com/kubernetes/kubernetes/pull/35526

**Comment by jkemp101** [comment]
I have the same issue but run my logging off cluster.  So for now I am using `hostNetwork: true` for fluentd so the master pods can communicate with my logging infrastructure.

**Comment by sweber83** [comment]
Thanks for your answers.
We solved the issue using `dnsPolicy: Default` so we get the same resolv.conf as on the host.
In our use case, fluentd doesn't really need to talk to other cluster services.

**Comment by justinsb** [comment]
I think this is fixed with kops 1.5.0 beta1 or above, and k8s 1.5.

If not though, please do comment / reopen.

**Comment by r4j4h** [comment]
Just to follow up for anyone, it may not even be fixed till 1.6 :(

https://github.com/kubernetes/kubernetes/pull/29378

If I am wrong and 1.5 did work for you sweber please let me know

**Comment by justinsb** [comment]
So you're right @r4j4h ... if you are running with hostNetwork, you need to specify `dnsPolicy: ClusterFirstWithHostNet` and that is only supported from 1.6 on.  If you're not running with hostNetwork though, this should "just work.
