### ISSUE TITLE
Decide on a channels update policy for AMIs

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#9705]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

When Kops used to default to the custom Debian AMIs we would bump the alpha channel anytime we built a new AMI. Now that Kops defaults to the official Ubuntu AMIs we are more disconnected from the AMI release process - we don't have the same "reminder" to update the alpha channel that we used to. We should decide on a schedule or strategy for updating the alpha channel with new Ubuntu AMIs.

Their releases don't appear to be on a regular schedule:
<img width="436" alt="Screen Shot 2020-08-07 at 9 37 00 AM" src="https://user-images.githubusercontent.com/1455650/89656698-8d422000-d891-11ea-9c9c-254025f6b3c3.png">

**2. Feel free to provide a design supporting your feature request.**

I have a few ideas, some require more effort than others

* Assume that someone will notice that the channels aren't up to date and open PRs to update them ad-hoc (this is where we are now)
* We continue our original pattern of having an agenda item each office hours, but instead we check for new AMIs rather than propose new AMI builds
* Use some sort of notification tool or automation that bumps the channels files anytime new AMIs are published

Note that whatever we decide could apply to the GCE AMIs as well.

**Comment by hakman** [comment]
At the very least, Ubuntu images should be bumped together with the new Kubernetes versions.

**Comment by hakman** [comment]
At the moment, all AMI updates are done at the same time with the patch releases for k8s and use images that are also available for AWS GovCloud and AWS China. Thanks @MoShitrit for taking care of this chore.
@rifelpet is this an acceptable solution to this issue?

**Comment by rifelpet** [comment]
I think the process should be documented for others to follow in the future as well. Even just comments in the channels files might be acceptable.

**Comment by MoShitrit** [comment]
Hey guys,
Glad to help however I can!
I can take the documentation task upon myself as well.
Which section of the docs would it fall under? My gut tells me it should go as a new section under `Development`, even though it's not really _Development_ per-se. Perhaps it's worth renaming this section to `Contribute`?
I can take a first stab at creating the branch and PR and we can kick off the discussion there.

**Comment by rifelpet** [comment]
We have a few pages that are essentially instructions for contributors to follow when performing certain tasks periodically:
* https://kops.sigs.k8s.io/development/new_kubernetes_version/
* https://kops.sigs.k8s.io/development/release/
* https://kops.sigs.k8s.io/development/homebrew/

Maybe it makes sense to group them together separately from other generic instructions regarding development environments or how to contribute certain changes?

**Comment by MoShitrit** [comment]
Yep, agreed!
OK cool, I'll take point on that documentation change and kick off a PR so we can continue the discussion there.
