### ISSUE TITLE
Not possible to open up master nodes to ELB and remove label `node-role.kubernetes.io/master`

### ISSUE THREAD

**Issue by BouweCeunen** [kubernetes/kops#9706]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.17.1 (git-4dfd4779fe)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Removing master label should make the node eligible as candidate nodes for the ELB.

```kubectl label node <node_name> node-role.kubernetes.io/master-```

**5. What happened after the commands executed?**
Labels were updated.

**6. What did you expect to happen?**
That label `node-role.kubernetes.io/master=` should be gone. Is it possible that Kubernetes that had been set up with Kops replaces this label after it has been removed?

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
/
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
/

**9. Anything else do we need to know?**
I would like to do a one node setup with kops. I can add the master node to the loadbalancer and change the Security Group settings, but each reboot will remove the master node again from the loadbalancer.

**Comment by johngmyers** [comment]
That label identifies masters and it is not possible to keep kops from labeling masters so.

If you want masters to be targets of your ELB then you need to configure your ELB to include them.

**Comment by BouweCeunen** [comment]
What exactly triggers the node to re-add the label once I remove it, is that kops related? Because that label is present, each reboot of a node will automatically remove the master from the ELB again I presume.

**Comment by johngmyers** [comment]
`kops-controller` is responsible for labeling nodes as of kops 1.16
