### ISSUE TITLE
Have kops ensure the correct rules for the master/node security groups

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kops#9716]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Right now, kops does not clean up old security group rules or rules added manually. There is no reason why kops shouldn't do this since we support adding additional security groups to be used for whatever other purposes.

**2. Feel free to provide a design supporting your feature request.**

The larger, but perhaps better way of solving this is to make security group rules a property of the securitygroup task. Then `Find()` can just get the current set of rules and ensure they match expected. There are some rule deletions that take place there already, for example if one enable bastions. But there is very specific logic around those few ports.

The more direct way of doing this is implement deletions in the securitygrouprule task. E.g add a Delete property to the task, create a task for every existing rule in the security group. If not an identical rule is created in `firewall.go`, set the Deletion property to true. Then one could also remove the `FindDeletions` logic for rules in the securitygroup task. 

Any thoughts?

**Comment by olemarkus** [comment]
Worth mentioning that a big motivation for me is to consolidate how we define rules for each cloud provider. Openstack creates radically different rules from AWS without there being any particular reason to.

**Comment by johngmyers** [comment]
Seems reasonable.
