### ISSUE TITLE
Documentation about base images

### ISSUE THREAD

**Issue by MichaelJDrK** [kubernetes/kops#9727]
Currently, it's documented which base images are supported: https://kops.sigs.k8s.io/operations/images/

There are some open questions, which should be added to / clarified in the documentation:
- Are there any requirements to a base image (preinstalled packages etc)? There is/was a kope.io default image with some adjustments. What does this mean? If stock images are supported, these adjustments are optional? Could I make my own image with these adjustments, e.g. based on Ubuntu 20.04?

- What about (security) updates? This is an important topic, but I bet the majority of the users ignore it completely. Does kops handle upgrades? Does the user have to handle upgrades (If yes - how)? Are you just expected to use the latest base image and rely on an appropriate update frequency? What exactly do I have to do that my (imaginary) 100 nodes cluster has always the latest patches?

**Comment by johngmyers** [comment]
That document needs to be updated to reflect that kops 1.18+ use a stock Ubuntu base.
