### ISSUE TITLE
Ability to remove client-ca-file and token-auth-file authentication methods from api server

### ISSUE THREAD

**Issue by f-ld** [kubernetes/kops#9729]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I am using kubernetes 1.16.9 (well, still some clusters to update from 1.14.x) and should soon migrate to 1.17.x. All deployed on AWS.
I have seen that on 1.18/1.19 there are many changes to come regarding historical auth methods being removed.

In the mean time I have configured [auth via AWS IAM authenticator](https://aws.amazon.com/blogs/opensource/deploying-aws-iam-authenticator-kubernetes-kops/) and it is working fine.

Now I am trying to remove other auth methods to avoid other external accesses to the API server.
I did disable basic auth (See https://github.com/kubernetes/kops/issues/290 ) but can still run requests with credentials obtained using `kops export kubeconfig`.
Looking to [API server doc regarding auth](https://kubernetes.io/docs/reference/access-authn-authz/authentication/) I understand that the reason is either regarding certificates or auth tokens. And it seems there is no way to disable them, am I right?

I even tried this in my cluster conf:
```
spec:
  kubeAPIServer:
    disableBasicAuth: true
    clientCAFile: /dev/null
    tokenAuthFile: /dev/null
```
but the last two do not change the apiserver command line.

**2. Feel free to provide a design supporting your feature request.**

Add some keys to config to remove `--token-auth-file=` and `--client-ca-file` parameters from api server command line (assuming, if not wrong, this would disable those auth methods achieving what I expect without further problems).

**Comment by johngmyers** [comment]
There is no way to disable use of token auth prior to Kubernetes 1.18. You could use `kops delete secret secret` to delete all the valid tokens, though.

You cannot disable client certificate authentication. The cluster will not function without it.
