### ISSUE TITLE
kops drain node

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#975]
Kops needs to be able to drain a node, and it would be good for it to handle petsets as well. As well as other alpha components such as scheduled jobs.

Not sure if this will be exposed from the cli, but we need this functionality to improve upgrades and updates.

**Comment by chrislovecnm** [comment]
This is code that is in the master branch, and it should drain petsets as well.  That is the reason that we don't use kubectl drain, as it rarely supports alpha components.  This code may change it in 1.5, but till then, we need to drain via code in kops.  Also, this needs to be tested with a master, as I am uncertain that it will take etcd offline.

Here is the code example https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/drain.go

**Comment by zytek** [comment]
What about node draining as a lifecycle hook in AutoScalingGroup ?

**Comment by chrislovecnm** [comment]
Implemented - closing
