### ISSUE TITLE
Create spread placement group for control plane 

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#9763]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

On AWS, kops should create a spread placement group for the control plane so that AWS does not schedule multiple control plane instances on the same underlying hardware.

**2. Feel free to provide a design supporting your feature request.**

This can have applicability to instance groups other than for the control plane, so it would be good to expose the feature for other instance groups as well.

I propose a new field in `InstanceGroupSpec`: `SpreadGroup *string `json:"spreadGroup,omitempty"`.
It seems possible that other cloud providers could implement their equivalents to this concept.

Multiple instance groups can share the same spread group. Kops will create and own all spread placement groups taken from the union of spread group names for all instance groups. Kops will include the name of the cluster in the name of the spread placement group so that multiple clusters in the account will not interact with each other. Kops will then arrange for all instances in the instance group to be placed in the spread placement group specified in the instance group spec.

Furthermore, when creating new clusters kops will set the `spreadGroup` field of the control plane instance groups to `"control-plane"`.

**Comment by krangerich** [comment]
A usual control plane consists of three master nodes, each in a different availability zone. Different availability zones in AWS are represented by different data centers, physically some kilometers away from each other . If you don't run edge cases like 5 or 7 masters, it's impossible that multiple control plane instances are on the same hardware.

For workloads you can use topologySpreadConstraints to spread replicas across availability zones: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

**Comment by johngmyers** [comment]
There was a problem report somewhere where someone lost two of three control nodes because they had been scheduled onto the same underlying hardware.
