### ISSUE TITLE
update kops ami

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#977]
We need https://github.com/kubernetes/kube-deploy/pull/258 merged, and we need @justinsb to push a new image.

**Comment by chrislovecnm** [comment]
@justinsb do you just want a PR for ethtool? We have a chef setup to build an image for us, so I can back out my other changes.

**Comment by kris-nova** [comment]
This is **critical** for https://github.com/kubernetes/kops/milestone/1

Update on this gentlemen? We would like this next week if at all possible

**Comment by justinsb** [comment]
There's an image available - it's 12-05 or 12-06 IIRC

**Comment by kris-nova** [comment]
Do we have a link?

**Comment by justinsb** [comment]
I believe this is done - the image is in the alpha channel.  Closing; reopen (or new issue) if needed!
