### ISSUE TITLE
Problems bringing up a 1.18.x cluster

### ISSUE THREAD

**Issue by scottrangerio** [kubernetes/kops#9785]
Hey all 👋 

I'm currently having an issue with a 1.18.x cluster. I'm not sure if this is a feature or a bug, as this used to work up until 1.18, but the change could be intentional in which case this could be a feature.

We currently run 2x kubernetes clusters in AWS (with spot inst elastic groups) using kops for both (a qa cluster and a prod cluster). I recently upgraded our qa cluster to 1.18.x which is when this issue started happening.

Our QA cluster is a single master cluster. In order to reduce our daily costs, we only run our QA cluster for ~10 hours a day. At the end of the working day, we set the replica count for masters and nodes to 0 using scheduled tasks on the spot inst elastic group. In the morning, before the working day starts, we bump up the replica counts to essentially turn the cluster on. This allows us to save some money on EC2 running costs.

Whats started happening is when I get in, the instances exist in EC2 but the cluster isn't up and running. In order to overcome this at the moment, I SSH onto the single master node and do a `sudo systemctl restart kubelet` as the kubelet isn't running. Once the kubelet is running, I also have to do a `kubectl label node $node node-role.kubernetes.io/master=""` in order to mark that node as a master. Once I've done these two steps, the cluster starts to come up. Worker nodes join and pods get scheduled.

What I think is happening (although not certain), is a chicken and egg style problem. If I understand it correctly, node labels are now handled via the `kops-controller`, which only runs on master nodes. In order for our single master to get the label of master, it needs to run the `kops-controller`, which it can't do because it doesn't have the master label.

My main question is whether the above assumption is correct / makes sense, and if so is there anything that can be done to make this use-case possible or whether this is an edge case and I'd be better off writing some kind or scheduled script to automate the above commands?

I'm not really sure what other info would be useful, but I'm happy to add anything that might help.

Thanks!

**Comment by hakman** [comment]
Hey @scottrangerio. To my knowledge there are no issues with running 1.18 clusters either single or multi master.
Would you mind posting the redacted cluster spec requested in the issue template to be able to try and reproduce this.
https://raw.githubusercontent.com/kubernetes/kops/master/.github/ISSUE_TEMPLATE/bug_report.md

Also, as an idea, you should check the logs on the node to see what happens with the `kops-configuration` servrice.

**Comment by scottrangerio** [comment]
Apologies. I should of followed the template but I was being lazy.

That said, it would seem I was a little too hasty to suspect the new kops version. I did some more looking around on the master this morning and have identified a the cause of my issue (operator error on my part).

With that, I'm closing this. Sorry for the time wasting!

**Comment by hakman** [comment]
No worries. Thanks for the update!
