### ISSUE TITLE
api endpoint times out

### ISSUE THREAD

**Issue by tetrohed** [kubernetes/kops#9810]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.18.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kubectl get cluster-info

**5. What happened after the commands executed?**
error listing nodes in cluster: Get "https://api.k8s-dev.scalara.de/api/v1/nodes": dial tcp 52.28.177.141:443: i/o timeout

**6. What did you expect to happen?**
get a list of nodes

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: k8s-dev.scalara.de
spec:
  api:
    loadBalancer:
      additionalSecurityGroups:
      - sg-030a5c526c184597a
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://087406001579-dev-kops-state/k8s-dev.scalara.de
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master
      name: master
    name: main
  - etcdMembers:
    - instanceGroup: master
      name: master
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesVersion: 1.18.8
  masterPublicName: api.k8s-dev.scalara.de
  networkCIDR: 10.0.0.0/16
  networkID: vpc-03112b2c890620c31
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  - id: subnet-0857d32690bb19373
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - egress: nat-09b21d8b4b1d3dd36
    id: subnet-05bf95ec12e0f760f
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s-dev.scalara.de
  name: master
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  kubernetesVersion: 1.18.8
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-central-1a
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s-dev.scalara.de
  name: nodes
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  kubernetesVersion: 1.18.8
  machineType: t3.small
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - eu-central-1a

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
I0825 09:23:42.696929    4398 loader.go:375] Config loaded from file:  /Users/armin/.kube/config
I0825 09:23:42.697510    4398 round_trippers.go:423] curl -k -v -XGET  -H "User-Agent: kubectl/v1.16.6 (darwin/amd64) kubernetes/e7f962b" -H "Accept: application/json, */*" 'https://api.k8s-dev.scalara.de/api?timeout=32s'
I0825 09:24:12.698706    4398 round_trippers.go:443] GET https://api.k8s-dev.scalara.de/api?timeout=32s  in 30001 milliseconds
I0825 09:24:12.698723    4398 round_trippers.go:449] Response Headers:
I0825 09:24:12.698795    4398 cached_discovery.go:121] skipped caching discovery info due to Get https://api.k8s-dev.scalara.de/api?timeout=32s: dial tcp 18.185.218.188:443: i/o timeout
I0825 09:24:12.699045    4398 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.16.6 (darwin/amd64) kubernetes/e7f962b" 'https://api.k8s-dev.scalara.de/api?timeout=32s'
I0825 09:24:42.703983    4398 round_trippers.go:443] GET https://api.k8s-dev.scalara.de/api?timeout=32s  in 30004 milliseconds
I0825 09:24:42.703997    4398 round_trippers.go:449] Response Headers:
I0825 09:24:42.704020    4398 cached_discovery.go:121] skipped caching discovery info due to Get https://api.k8s-dev.scalara.de/api?timeout=32s: dial tcp 18.185.218.188:443: i/o timeout
I0825 09:24:42.705971    4398 shortcut.go:89] Error loading discovery information: Get https://api.k8s-dev.scalara.de/api?timeout=32s: dial tcp 18.185.218.188:443: i/o timeout
I0825 09:24:42.706052    4398 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.16.6 (darwin/amd64) kubernetes/e7f962b" 'https://api.k8s-dev.scalara.de/api?timeout=32s'
I0825 09:25:12.706215    4398 round_trippers.go:443] GET https://api.k8s-dev.scalara.de/api?timeout=32s  in 30000 milliseconds
I0825 09:25:12.706251    4398 round_trippers.go:449] Response Headers:
I0825 09:25:12.706283    4398 cached_discovery.go:121] skipped caching discovery info due to Get https://api.k8s-dev.scalara.de/api?timeout=32s: dial tcp 18.185.218.188:443: i/o timeout
I0825 09:25:12.706412    4398 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.16.6 (darwin/amd64) kubernetes/e7f962b" 'https://api.k8s-dev.scalara.de/api?timeout=32s'
I0825 09:25:42.709713    4398 round_trippers.go:443] GET https://api.k8s-dev.scalara.de/api?timeout=32s  in 30003 milliseconds
I0825 09:25:42.709740    4398 round_trippers.go:449] Response Headers:
I0825 09:25:42.709780    4398 cached_discovery.go:121] skipped caching discovery info due to Get https://api.k8s-dev.scalara.de/api?timeout=32s: dial tcp 18.185.218.188:443: i/o timeout
I0825 09:25:42.709955    4398 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.16.6 (darwin/amd64) kubernetes/e7f962b" 'https://api.k8s-dev.scalara.de/api?timeout=32s'
I0825 09:26:12.712980    4398 round_trippers.go:443] GET https://api.k8s-dev.scalara.de/api?timeout=32s  in 30003 milliseconds
I0825 09:26:12.713005    4398 round_trippers.go:449] Response Headers:
I0825 09:26:12.713033    4398 cached_discovery.go:121] skipped caching discovery info due to Get https://api.k8s-dev.scalara.de/api?timeout=32s: dial tcp 52.28.177.141:443: i/o timeout
I0825 09:26:12.713117    4398 helpers.go:217] Connection error: Get https://api.k8s-dev.scalara.de/api?timeout=32s: dial tcp 52.28.177.141:443: i/o timeout
F0825 09:26:12.713139    4398 helpers.go:114] Unable to connect to the server: dial tcp 52.28.177.141:443: i/o timeout
```

**9. Anything else do we need to know?**
the dns is setup correctly: running `dig NS k8s-dev.scalara.de`
```
k8s-dev.scalara.de.     130     IN      NS      ns-1030.awsdns-00.org.
k8s-dev.scalara.de.     130     IN      NS      ns-1946.awsdns-51.co.uk.
k8s-dev.scalara.de.     130     IN      NS      ns-386.awsdns-48.com.
k8s-dev.scalara.de.     130     IN      NS      ns-575.awsdns-07.net.
```

**Comment by olemarkus** [comment]
One immediate thing that pops out for me is the t3.small instance type. You need at least t3.medium to schedule the necessary workload. This shouldn't prevent the API from working through.

Next step in debugging this is to have a look at the kube-apiserver logs on the server to see if you see any issues.

**Comment by tetrohed** [comment]
@olemarkus thanks for the answer, I just saw the listener on my AWS elb, might the lacking SSL causing the issue? 
![image](https://user-images.githubusercontent.com/7670039/91146444-3329c300-e6b7-11ea-854d-4dfb871deb8b.png)

must say, A bit of white spots on my side, when it comes to certificates

**Comment by tetrohed** [comment]
@olemarkus btw since the master instance in behind the load balancer (which is well unreachable) how can I connect to the master node?

**Comment by olemarkus** [comment]
It is the API server itself that terminates SSL in this case, so your config is correct.
If you don't have a routable internal network (VPN or DX) you need to add a bastion server to reach the nodes: https://kops.sigs.k8s.io/bastion/

**Comment by tetrohed** [comment]
trying to deploy a bastion, but the rolling update does not spin up the machines 

Using cluster from kubectl context: k8s-dev.scalara.de

NAME            STATUS  NEEDUPDATE      READY   MIN     TARGET  MAX
bastions        Ready   0               0       1       1       1
master          Ready   0               1       1       1       1
nodes           Ready   0               2       2       2       2

No rolling-update required.

**Comment by olemarkus** [comment]
The bastion didn't exist, so no need to roll anything. it should already be available

**Comment by tetrohed** [comment]
ah I understand, it is basically a load balancer.
unfortunately this one behaves the same as the other LB though, trying to ssh times out 
```ssh: connect to host bastion-k8s-dev-scalara-d-qcubto-720098057.eu-central-1.elb.amazonaws.com port 22: Operation timed out
```

**Comment by olemarkus** [comment]
Can you check the security groups for the LB? there may be organisational policies or something that blocks ssh access to the LB.

**Comment by tetrohed** [comment]
![image](https://user-images.githubusercontent.com/7670039/91154421-cd8f0400-e6c1-11ea-9c2e-90f9dae50002.png)

**Comment by olemarkus** [comment]
`kops update cluster` say anything about adding these rules again? There should definitely be inbound rules.

**Comment by tetrohed** [comment]
deleted the cluster and recreated it, here is the output:

```
W0825 11:54:45.239846   11052 external_access.go:39] KubernetesAPIAccess is empty
W0825 11:54:45.239929   11052 external_access.go:43] SSHAccess is empty
I0825 11:54:45.780976   11052 executor.go:103] Tasks: 0 done / 108 total; 49 can run
I0825 11:54:46.123935   11052 vfs_castore.go:590] Issuing new certificate: "etcd-manager-ca-events"
I0825 11:54:46.138066   11052 vfs_castore.go:590] Issuing new certificate: "etcd-manager-ca-main"
I0825 11:54:46.144018   11052 vfs_castore.go:590] Issuing new certificate: "ca"
I0825 11:54:46.220006   11052 vfs_castore.go:590] Issuing new certificate: "etcd-clients-ca"
I0825 11:54:46.243061   11052 vfs_castore.go:590] Issuing new certificate: "etcd-peers-ca-main"
I0825 11:54:46.250608   11052 vfs_castore.go:590] Issuing new certificate: "apiserver-aggregator-ca"
I0825 11:54:46.507482   11052 vfs_castore.go:590] Issuing new certificate: "etcd-peers-ca-events"
I0825 11:54:46.777370   11052 executor.go:103] Tasks: 49 done / 108 total; 32 can run
I0825 11:54:47.196189   11052 vfs_castore.go:590] Issuing new certificate: "master"
I0825 11:54:47.200514   11052 vfs_castore.go:590] Issuing new certificate: "kube-proxy"
I0825 11:54:47.253942   11052 vfs_castore.go:590] Issuing new certificate: "kubelet"
I0825 11:54:47.258261   11052 vfs_castore.go:590] Issuing new certificate: "kube-controller-manager"
I0825 11:54:47.279814   11052 vfs_castore.go:590] Issuing new certificate: "kubecfg"
I0825 11:54:47.317412   11052 vfs_castore.go:590] Issuing new certificate: "apiserver-aggregator"
I0825 11:54:47.319823   11052 vfs_castore.go:590] Issuing new certificate: "kube-scheduler"
I0825 11:54:47.333203   11052 vfs_castore.go:590] Issuing new certificate: "apiserver-proxy-client"
I0825 11:54:47.347714   11052 vfs_castore.go:590] Issuing new certificate: "kubelet-api"
I0825 11:54:47.399625   11052 vfs_castore.go:590] Issuing new certificate: "kops"
I0825 11:54:47.736964   11052 executor.go:103] Tasks: 81 done / 108 total; 21 can run
I0825 11:54:48.114187   11052 launchconfiguration.go:375] waiting for IAM instance profile "bastions.k8s-dev.scalara.de" to be ready
I0825 11:54:48.170783   11052 launchconfiguration.go:375] waiting for IAM instance profile "nodes.k8s-dev.scalara.de" to be ready
I0825 11:54:48.252513   11052 launchconfiguration.go:375] waiting for IAM instance profile "masters.k8s-dev.scalara.de" to be ready
I0825 11:54:58.627851   11052 executor.go:103] Tasks: 102 done / 108 total; 4 can run
I0825 11:54:59.621644   11052 executor.go:103] Tasks: 106 done / 108 total; 2 can run
I0825 11:54:59.944560   11052 executor.go:103] Tasks: 108 done / 108 total; 0 can run
I0825 11:54:59.944588   11052 dns.go:156] Pre-creating DNS records
I0825 11:55:01.078480   11052 update_cluster.go:308] Exporting kubecfg for cluster
kops has set your kubectl context to k8s-dev.scalara.de
```

the security group for bastion has an SSH rule on 22 but the bastion-elb does not have any rule

**Comment by tetrohed** [comment]
ok tried everything again, now if I manually set an inbound rule on the bastion instance, I can ssh into it, this should point to the fact that the load balancers are not reachable. 

examining the load balancers tells me that the they are in the public subnet of my vpc and those subnets have route tables that do have an internet gateway

**Comment by tetrohed** [comment]
another question in this regard: does api-elb security group suppose to have inbound rules?

**Comment by tetrohed** [comment]
after manually adding the https 443 on 0.0.0.0 to inbound rules,  I can validate the cluster, but I am guessing this is not the correct way to fix the issue? any help would be appreciated

**Comment by hakman** [comment]
I have a "feeling" that SGs are not updated, just recreated. In case something went wrong when the cluster was created, maybe they are not updated. Can you check it it's correctly recreated if you delete it?

**Comment by tetrohed** [comment]
@hakman you mean delete it from aws console? that would mean I have to delete my network interfaces and other associated sgs as well

**Comment by hakman** [comment]
I meant the one for the api-elb. That one should be easy to remove.

**Comment by tetrohed** [comment]
not really, I have two network interfaces and another sg showing up when I do remove action on it

**Comment by lundbird** [comment]
@tetrohed I recently had this issue when creating a cluster using kops 1.18. For me my bastion hosts and apiserver were unreachable because kops updated the autoscaling groups of the bastions and masters to remove their association to their loadbalancers. I fixed this by manually adding the loadbalancers back into the autoscaling group.
![Screen Shot 2020-09-02 at 08 47 47](https://user-images.githubusercontent.com/34074700/91991846-0b5ede80-ecf9-11ea-8d2c-5215714f1006.png)

**Comment by tetrohed** [comment]
@lundbird This is what I ended up doing. 

I think I was missing a big part of the picture. And that was my VPC(terraform generated) and the fact that my cluster was living inside of it without having any ingress on VPC. After I added a load balancer, everything went smoothly.
