### ISSUE TITLE
Clean-up the milestones

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#982]
@justinsb if you feel like it, please cleanup the old milestones, or delete them ;)

I will remove them in a couple of weeks, if you do not get around to them.  Let me know if you want to keep them.

**Comment by justinsb** [comment]
Not sure what you mean by clean them up @chrislovecnm ?  I don't think we should delete them; that will lose all the information that is in them.  We can rename them or change the due dates.

**Comment by chrislovecnm** [comment]
This is done :)
