### ISSUE TITLE
Add office hours for other time zones 

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#9833]
There is interest in hosting more office hours calls in timezones that are more compatible with others. I created a doodle poll with what I think might work but I'm happy to add other times

The poll uses specific dates but we can treat it as a general time of week that we'll use biweekly. I'll set an informal deadline of 2 weeks from today at which point we can make a decision if and when to schedule the additional office hours.

https://doodle.com/poll/vgue5aqzaq5rgeaf

/cc @olemarkus @dezmodue  @zetaab and anyone else that would like to join :)

**Comment by johngmyers** [comment]
I would support moving the 9am Pacific call to a different weekday in order to move it out of the European weekend.

While I'm not sure I want to sign up for it, 6am Pacific is more practical for me than 7am or 8am. The former means getting up early, the latter requires rearranging the entire household's schedule.

**Comment by hakman** [comment]
I would would also support moving the call to a different day and time as follows:
* Mon or Fri only after 8 AM PST
* Tue-Thu at any time

**Comment by olemarkus** [comment]
* Friday's I am not available after 5 AM PST
* Other days I have a hard stop at 7 AM, but I occasionally have meetings with people in PST time then too.
* Can also usually do Mon-Thurs after 10 AM

**Comment by hakman** [comment]
Btw, I don't mind the call being weekly either.

**Comment by rdrgmnzs** [comment]
I'm ok with changing it to another day of the week or to a later time.

Anything earlier than 9AM PST would be difficult to make as that is commuting time.

**Comment by rifelpet** [comment]
We discussed the doodle poll results and decided to have our first additional office hours session on Thursday October 1st at 9am US/Eastern time / 1PM UTC. The intent will be to initially focus on supporting those interested in contributing for hacktoberfest but we can continue to triage issues, bring visibility to PRs, and clarify release statuses as necessary. We'll probably try some of the other popular timeslots throughout October and perhaps settle on one that works best for everyone going forward after hacktoberfest.

We'll see you there :)

**Comment by olemarkus** [comment]
Right on top of a recurring meeting at work :) but I can join for the second half (hopefully earlier).

**Comment by olemarkus** [comment]
/remove-lifecycle rotten
/close

We have regular office hours at a EU-friendly time now

**Comment by hakman** [comment]
@olemarkus maybe we should add an entry in the docs for the EU hours.

**Comment by olemarkus** [comment]
I can add something like that.

Where do we publish the EU time? Slack? Office hours meeting notes?

**Comment by hakman** [comment]
I think here https://github.com/kubernetes/kops/blob/master/docs/welcome/office_hours.md

**Comment by olemarkus** [comment]
The EU slot doesn't have a regular time. I was more wondering where they would look for the time and date of the next EU slot.
