### ISSUE TITLE
Log error when no EBS volumes found

### ISSUE THREAD

**Issue by retrohacker** [kubernetes/kops#984]
When the master node fails to find the backing etcd nodes, it silently fails after

```
AWS API Request: ec2/DescribeVolumes
```

Providing extra context at this point would be helpful. I.E. the contents of [`request *ec2.DescribeVolumesInput`](https://github.com/kubernetes/kops/blob/v1.4.1/protokube/pkg/protokube/aws_volume.go#L153)

For higher levels of verbosity, perhaps listing all of the volumes that can be seen along with their tags would be useful? I.E. when no matching volumes are found, re-run [`findVolumes`](https://github.com/kubernetes/kops/blob/v1.4.1/protokube/pkg/protokube/aws_volume.go#L153) without filters and then return something like:

```
I1123 21:15:07.523308      34 aws_volume.go:55] Found volumes:
Name: vol-4b17f8e2
Tags:
  - k8s.io/role/master: 1
...
```

This would help users to trace EBS problems back to the cause. For higher levels of verbosity, this should be enough context to determine if the proper tags are't being set or if IAM permissions are preventing the host from querying the account's EBS volumes.

**Comment by justinsb** [comment]
Interesting.  What was the cause, in your case @retrohacker ?

**Comment by retrohacker** [comment]
@justinsb haven't tracked down the cause yet, had to switch to something else. Still plan on circling back.

`gdb` is showing that [`p`](https://github.com/kubernetes/kops/blob/v1.4.1/protokube/pkg/protokube/aws_volume.go#L156) is empty in the response. Using the same filters from `request` via the `aws` cli on the master EC2 node returns the proper EBS volumes.

**Comment by retrohacker** [comment]
That being said, getting to the point where I knew that no volumes were being returned to protokube was ~15 hours worth of debugging. (it's possible I'm missing something in logs that should have shown this, or that I have the wrong log levels set)

The problem manifests itself as no Route53 entries being set. Had to work back from there to determine what failed. `cat /var/log/cloud-init.output | less` and `docker ps -aq | xargs docker log` on the master node was where I started. Took me a long time to get from that to determining protokube hadn't found volumes since it doesn't log an error.
