### ISSUE TITLE
Rotating kube secret does not remove access from existing users

### ISSUE THREAD

**Issue by stylianosrigas** [kubernetes/kops#9844]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
kops 1.17
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
```

**3. What cloud provider are you using?**

```
AWS
```

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
- Get the kube secret from S3 bucket 
- Create a new base64 secret and push it back to S3
- Verify that password is updated running `kops get secrets kube -oplaintext --name=clustername --state=s3://kopsbucket`
- Do a rolling update of the cluster running `kops rolling-update cluster --name=clustername --state=s3://kopsbucket --yes --force`
- Rolling update runs successfully
```

**5. What happened after the commands executed?**

```
- Users that previously exported the kubeconfig can still run kubectl commands although the kube password was rotated.
```

**6. What did you expect to happen?**

```
- Users that did not run kube export again to get the new config should not have access to the cluster
```

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by olemarkus** [comment]
You need to revoke the cluster CA certificate for the exported credentials to stop working.
See https://kops.sigs.k8s.io/rotate-secrets/

**Comment by stylianosrigas** [comment]
@olemarkus thanks for the reply, I have been following the steps to rotate the secrets and in step https://kops.sigs.k8s.io/rotate-secrets/#recreate-all-service-accounts I am getting the following error:
```
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```
Have you seen that before?

**Comment by olemarkus** [comment]
Where are you getting this one from? I suppose any component will yield that error until it is using certs signed by the new CA.

**Comment by stylianosrigas** [comment]
Getting this when trying to run the `NS=`kubectl get namespaces -o 'jsonpath={.items[*].metadata.name}'``. Basically in any kubectl command.

**Comment by olemarkus** [comment]
Have you exported the new credentials?

**Comment by stylianosrigas** [comment]
Yeap and when trying to run kubectl locally getting the same error.

**Comment by olemarkus** [comment]
Then most likely the API servers are not using new certs yet.
