### ISSUE TITLE
when installing cluster error is coming

### ISSUE THREAD

**Issue by vivekananda49** [kubernetes/kops#9848]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

**2. Feel free to provide a design supporting your feature request.**
kops create cluster --name=practiceaws.xyz --state=s3://practiceaws.xyz --zones=ap-south-1 --node-count=2 --node-size=t2.micro --master-size=t2.micre --zones=practiceaws.xyz

unable to infer CloudProvider from Zones (is there a typo in --zones?)
[root@ip-172-31-40-61 ~]# ^C

**Comment by hakman** [comment]
@vivekananda49 `--zones` refers to the cloud provider AZs in which to setup the cluster. Please check the docs for more info:
https://github.com/kubernetes/kops/blob/master/docs/cli/kops_create_cluster.md
/close
