### ISSUE TITLE
Hardened Debian Stretch AMIs for SOC 2 Type 2 Compliance

### ISSUE THREAD

**Issue by lsc21** [kubernetes/kops#9854]
Our organization is currently running `kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-07-20` AMIs in staging and production with no problem. However, our production environment is undergoing a SOC2 audit, and the consultants are asking what steps we take to harden the `kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-07-20` AMI we currently use. Are there best practices around AMI or OS hardening that we should follow?

**Comment by olemarkus** [comment]
kOps does not provide any specific hardening best practices. We now use the ubuntu AMIs and they are generally safe already. Additional hardening would typically be applied to the cluster itself. Things like PodSecurityPolicys, SecurityContexts etc.
