### ISSUE TITLE
"kops get ig" prints incorrect max value

### ISSUE THREAD

**Issue by ebbeelsborg** [kubernetes/kops#986]
Is this a BUG REPORT or FEATURE REQUEST? (choose one): BUG REPORT

Kubernetes version (use kubectl version): 
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:20:04Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

Environment:

    Cloud provider or hardware configuration: AWS
    OS (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
    Kernel (e.g. uname -a): Linux system76 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    Install tools: ?
    Others: N/A

What happened: kops does not report the correct max value for "kops get ig". For instance:
$ kops get ig nodes
Using cluster from kubectl context: <my-context>

NAME	ROLE	MACHINETYPE	MIN	MAX	  ZONES
nodes	Node	c4.2xlarge	        2	2	  eu-west-1a,eu-west-1b,eu-west-1c

$ kops edit ig nodes
metadata:
  creationTimestamp: "2016-11-03T14:55:43Z"
  name: nodes
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21
  machineType: c4.2xlarge
  maxSize: 3
  minSize: 2
  role: Node
  rootVolumeSize: 100
  zones:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c

Clearly, the max value is 3, not 2.

What you expected to happen: "kops get ig" should print the values min=2 and max=3.

How to reproduce it (as minimally and precisely as possible): Set the 'nodes' config to the example above and run "kops get ig".

Anything else do we need to know: kops uses the correct values when updating so it's just a matter of printing the correct max value. Not a big deal but still a bug.

**Comment by chrislovecnm** [comment]
Kops version?

**Comment by ebbeelsborg** [comment]
1.4.1

**Comment by yissachar** [comment]
I wonder why this would happen :)

https://github.com/kubernetes/kops/blob/master/cmd/kops/get_instancegroups.go#L115

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/issues/708 should fix that

**Comment by chrislovecnm** [comment]
@justinsb SGTM ... fixed it in my node validation PR as well :)
