### ISSUE TITLE
Preserve old kope docker images

### ISSUE THREAD

**Issue by marcindulak** [kubernetes/kops#9861]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Docker [announced](https://www.docker.com/pricing/resource-consumption-updates) that starting from November 1st 2020

```
If an image has not been pulled or pushed within 6 months, the image will be
marked “inactive.” Any images that are marked as “inactive” will be scheduled for
deletion. Only accounts that are on the Free individual or organization plans will be
subject to image retention limits. 
```

This may affect the images from https://hub.docker.com/u/kope, and it would be great if the old images can be preserved.

**2. Feel free to provide a design supporting your feature request.**

```
If you have a Free account, you can easily upgrade to a Pro or Team account
starting at $5 per month with an annual plan.
```

**Comment by hakman** [comment]
The _kope_ account is already a paid account, so everything should be fine from this point of view for now.
