### ISSUE TITLE
Feature flags for kops

### ISSUE THREAD

**Issue by kesor** [kubernetes/kops#9866]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

It would be beneficial when/if new features added to `kops` have the possibility to be avoided or turned off. For example, we would like to upgrade our clusters and kops to version 1.18; But for some reason the recent feature introduced in 1.18 for "AWS ExternalPolicies" is causing fatal errors during `kops update cluster`. If there is a way to turn this feature off, other than forking the project and rewriting/recompiling the code - it would be useful to help with business outcome delays and frustration from users of kops.

**2. Feel free to provide a design supporting your feature request.**

Make sure that every new feature introduced demands not just tests, but also a feature flag that allows to shut this feature off. Similar to how Lifecycle hooks are implemented today, but more granular.

Example code diff that demonstrates how it should look like
```diff
diff --git i/pkg/model/iam.go w/pkg/model/iam.go
index a18e6..c69f2 100644
--- i/pkg/model/iam.go
+++ w/pkg/model/iam.go
@@ -166,13 +166,11 @@ func (b *IAMModelBuilder) buildIAMTasks(igRole kops.InstanceGroupRole, iamName s
                }

                // Create External Policy tasks
-               {
+               if fi.FeatureFlags.ExternalPolicies && b.Cluster.Spec.ExternalPolicies != nil {
                        var externalPolicies []string

-                       if b.Cluster.Spec.ExternalPolicies != nil {
-                               p := *(b.Cluster.Spec.ExternalPolicies)
-                               externalPolicies = append(externalPolicies, p[strings.ToLower(string(igRole))]...)
-                       }
+                       p := *(b.Cluster.Spec.ExternalPolicies)
+                       externalPolicies = append(externalPolicies, p[strings.ToLower(string(igRole))]...)

                        name := fmt.Sprintf("%s-policyoverride", strings.ToLower(string(igRole)))
                        t := &awstasks.IAMRolePolicy{
```

**Comment by hakman** [comment]
Hi @kesor. First of all, thanks for the feedback. I understand your pain and I sympathise. One of the reasons that made me start contributing to kops was to fix the issues that were important for my use case.

That being said, there are almost [600 PRs](https://github.com/kubernetes/kops/milestone/27?closed=1) that went into kops v1.18.0 and very few issues were reported until now. It is impossible to catch every bug or add flags everywhere. Flags are added for larger features, but that decision is on a case by case base.

If you want to be 100% sure that a release works for your particular use case, my suggestion would be to allocate some time to test the beta releases and create issues when you notice that things are broken. I think in the past year the maintainers have been quite active in fixing such issues or at least providing workarounds.

**Comment by olemarkus** [comment]
I can only agree with @hakman here. Further, adding flags into the kops code is not always straightforward and it is easy to miss code paths that should be covered by a flag or get the flag wrong without doing a full copy of larger portions of the code.

In addition to test betas, where in your case we'd do a release blocking bug I think, contributing tests for your specific case would also be most helpful.

**Comment by johngmyers** [comment]
The proposal seems impractical. More complexity is likely to lead to more bugs. If there is an error in implementing the case where a new feature isn't used, what's to say there wouldn't also be an error in the case where it's disabled by feature flag?
