### ISSUE TITLE
Exclude nodes from load balancer 

### ISSUE THREAD

**Issue by rollerd** [kubernetes/kops#9870]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Kubernetes provides a featuregate called ServiceNodeExclusion that will exclude nodes that are labelled with:

```
alpha.service-controller.kubernetes.io/exclude-balancer
node.kubernetes.io/exclude-from-external-load-balancers
```
from being added to the cloud-provider load balancer. It seems that this will not work with kops because if I'm understanding correctly, the ASG configuration is adding new instances to the LB as they come up. It would be great if there were a way to either have kops respect this featureGate or if there were an instance group role for service nodes so that any instances that came up in that group would not automatically be added to the load balancer.

**Comment by olemarkus** [comment]
Which load balancer is "the load balancer" you refer to here? The only load balancer kops creates is the one for the master API. The ones created by a service resource are managed by the actual cloud providers (aws cloud controller manager, openstack CCM etc)

**Comment by olemarkus** [comment]
Worth to mention that kops lets you enable/disable any k8s feature flag.

**Comment by rollerd** [comment]
@olemarkus You're absolutely correct. I was generalizing the creation of the API LB to the service LB. Thanks for the quick response!
