### ISSUE TITLE
KOPS Changing the name of my exisiting AWS Key Pair

### ISSUE THREAD

**Issue by iamaverrick** [kubernetes/kops#9875]
we are using Terraform v0.12.29 also have tried V0.13 to manage our production environment on aws. On top of that we are also using KOPS Version 1.18.0 (git-698bf974d8) to deploy terraform outputs. my current issue is when i generate the terraform outputs KOPS is rename the AWS Key pair for some reason instead of using the provided name of the key pair. we want to use are our key pair name, and keys but im not sure if this is an issue with the new versions because i didn't have this issue with previous terraform nor kops versions.

my configuration is as follows:

```
output "kops_create_cluster" {
  value = <<EOF
      kops create cluster\
      --name=k8s.${var.domain}\
      --state=s3://kops.${var.domain}\
      --cloud=${var.kops_cloud}\
      --kubernetes-version=${var.kops_k8s_version}\
      --cloud-labels="${var.kops_cloud_labels}"\
      --dns-zone=${var.zone_id}\
      --encrypt-etcd-storage=${var.kops_encrypt_etcd_storage}\
      --master-count=${var.kops_master_count}\
      --master-size=${var.kops_master_size}\
      --master-zones=${data.terraform_remote_state.vpc.outputs.azs[1]},${data.terraform_remote_state.vpc.outputs.azs[2]},${data.terraform_remote_state.vpc.outputs.azs[3]}\
      --master-security-groups=${data.terraform_remote_state.sg.outputs.web_sg_id},${data.terraform_remote_state.sg.outputs.k8s_api_sg_id}\
      --master-volume-size=${var.kops_master_volume_size}\
      --networking=${var.kops_networking}\
      --node-security-groups=${data.terraform_remote_state.sg.outputs.web_sg_id},${data.terraform_remote_state.sg.outputs.k8s_api_sg_id}\
      --node-count=${var.kops_node_count}\
      --node-size=${var.kops_node_size}\
      --zones=${data.terraform_remote_state.vpc.outputs.azs[1]},${data.terraform_remote_state.vpc.outputs.azs[2]},${data.terraform_remote_state.vpc.outputs.azs[3]}\
      --topology=${var.kops_topology}\
      --utility-subnets=${data.terraform_remote_state.vpc.outputs.public_subnets[1]},${data.terraform_remote_state.vpc.outputs.public_subnets[2]},${data.terraform_remote_state.vpc.outputs.public_subnets[3]}\
      --subnets=${data.terraform_remote_state.vpc.outputs.private_subnets[1]},${data.terraform_remote_state.vpc.outputs.private_subnets[2]},${data.terraform_remote_state.vpc.outputs.private_subnets[3]}\
      --ssh-public-key=${data.terraform_remote_state.key_pair.outputs.k8s_key_public_key_filename}\
      --yes\
      --vpc=${data.terraform_remote_state.vpc.outputs.vpc_id}\
      --out=${var.kops_output_dir}\
      --target=${var.kops_target}
EOF

}
```

the name of the key pair is something like i.g key.pub
kops is changing it to kubernetes.k8s.company.com-finger-printsss

is anybody having the same issue or can somebody reproduce thanks in advance 

**Reasons why** 

Reasons why i suspect its kops change the name is because when i cd into the location output folder a folder is created called data and in that file all the information is located in regards to the output. updated name of the key pair is located their

**Comment by rifelpet** [comment]
What is the exact value of `data.terraform_remote_state.key_pair.outputs.k8s_key_public_key_filename`? And can you run `kops get cluster --name $clustername -o yaml` ? I'd like to see the value of `sshKeyName`
