### ISSUE TITLE
Upgrade Kubernetes to Master

### ISSUE THREAD

**Issue by brunoalano** [kubernetes/kops#988]
Hi,

I need to update the Kubernetes to the master repo, because the ScheduledJob has an issue that's solved in this issue:
https://github.com/kubernetes/kubernetes/pull/36812
https://github.com/kubernetes/kubernetes/pull/36883

How can I do that? I already checked the upgrade section in docs, but it asks for a specific version.

**Comment by chrislovecnm** [comment]
May want to look at how we are doing e2e testing on core https://github.com/kubernetes/kops/blob/master/e2e/runtests.sh may give u some insite. Off the top of my head I am unsure.

**Comment by chrislovecnm** [comment]
@zmerlynn / @justinsb any insite?

**Comment by brunoalano** [comment]
Just change the `kubernetesVersion` to some release Kubernetes Release version work's

**Comment by chrislovecnm** [comment]
@brunoalano he wants master, not a release

**Comment by justinsb** [comment]
You can run from any kubernetes build, even a CI build: https://github.com/kubernetes/kops/blob/master/docs/testing.md#ci-kubernetes-build

You can build and upload yourself: https://github.com/kubernetes/kops/blob/master/docs/testing.md#uploading-a-custom-build

However, I typically find it easier to use a CI build.  The challenge is finding the URL to it though.  The CI section has an example, and if you look at the logs for a CI build you can typically see the URL it is downloading from.  I believe they aren't valid forever though...

**Comment by justinsb** [comment]
I suspect your best bet is going to be to wait for it to be in a 1.5 beta build, or in a 1.4 backport.

**Comment by zmerlynn** [comment]
@chrislovecnm: Actually, the (Google) Jenkins infrastructure is using a different script in the test infra repo. 
I need to update https://github.com/kubernetes/kops/blob/master/docs/testing.md

@justinsb / @brunoalano: If you need the latest `master` k8s build, do this: Go here: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-build/, find the latest (green) build, (e.g. (13708)[https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-build/13708/]), read the "Version" header at the top.

**Comment by chrislovecnm** [comment]
@brunoalano can we close this?

**Comment by brunoalano** [comment]
@chrislovecnm Yes

**Comment by kris-nova** [comment]
Thanks for the help everyone
