### ISSUE TITLE
verbose logging of featureflags

### ISSUE THREAD

**Issue by rajatjindal** [kubernetes/kops#9886]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.18.0 (git-698bf974d8)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

N/A

**3. What cloud provider are you using?**
N/A

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

export KOPS_FEATURE_FLAGS=SpecOverrideFlag
kops version 

**5. What happened after the commands executed?**

```
$ kops version
I0908 18:58:31.335642   31105 featureflag.go:154] FeatureFlag "SpecOverrideFlag"=true
Version 1.18.0 (git-698bf974d8)
```
**6. What did you expect to happen?**

just print the version information

```
$ kops version
Version 1.18.0 (git-698bf974d8)
```

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A
**9. Anything else do we need to know?**

This msg is printed everytime any kops command is executed.

**Comment by rajatjindal** [comment]
I noticed that only change done there was to change from glog.Info to klog.Info, but for some reason it was not printed earlier but with one of the latest version we started to note it happen.

also we run multiple kops commands for setting up the cluster, and therefore it seems a little more verbose. 

do you think we can set log level for this msg to something higher?

**Comment by olemarkus** [comment]
Kops featureflags mostly guards very experimental code paths, so I prefer that it is always outputted to ensure I know that feature flags have been set.  It is only one log line per command, which isn't that much noise.

**Comment by rajatjindal** [comment]
hey @olemarkus 

thanks for taking out time to reply. 

I understand. will close the issue.

Thanks

**Comment by rajatjindal** [comment]
hey @olemarkus 

I am thinking about reopening this issue. The prob we are running into is that we consume the o/p of kops command(s) in our code, and decode that to e.g. cluster-spec, and now we are running into decoding problems.

what do you think?

**Comment by olemarkus** [comment]
Logs go into stderr and shouldn't be consumed like that in such a way.

**Comment by rajatjindal** [comment]
thank you for the quick reply. I did verified stdout/stderr thing, but didn't realized i was verifying it within my wrapper (where i was using cmd.CombinedOutput). 

i changed it to use different buffers for stdout and stderr, and that fixed it.

thanks a lot for quick reply.
