### ISSUE TITLE
etcd-manager restore enters infinite loop if ETCD_LISTEN_METRICS_URLS configured in manager

### ISSUE THREAD

**Issue by cjbehm** [kubernetes/kops#9887]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops 1.18.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

k8s 1.18.8

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

etcd-manager <path> restore-backup <name>

**5. What happened after the commands executed?**

The restore process begins as expected, however, it appears to launch an etcd process to perform the restore which inherits the ETCD_LISTEN_METRICS_URLS (and other) manager environment variables.

This creates a port allocation conflict, which causes the restore job/task to fail and then the process repeats, looping forever.

**6. What did you expect to happen?**

The restore process to complete normally without having to modify the cluster configuration.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

This is the relevant information from the kops configuration. Removing this block allowed the restore to succeed
```yaml
    manager:
      env:
      - name: ETCD_LISTEN_METRICS_URLS
        value: http://0.0.0.0:8081
      - name: ETCD_METRICS
        value: basic
```

I'm not sure whether kops or etcd-manager ultimately owns this particular scenario, but starting here because it was the kops-based configuration being passed to etcd-manager that had to be changed in order for the restore to work.

**Comment by cjbehm** [comment]
No comments/questions/feedback? This is a condition that I'm sure doesn't come up every day, but when it does hit it's not obvious and it's during a likely stressful time.

**Comment by rifelpet** [comment]
What you describe makes sense, etcd-manager is passing all of the env vars to the child etcd processes so if there is a specific env var like LISTEN_METRICS_URLS that can only be specified by one etcd process at a time, we would definitely run into issues like this.

etcd-manager does have its own repo so you may want to file an issue here: https://github.com/kopeio/etcd-manager

**Comment by amoskyler** [comment]
I just ran into this issue but in a slightly different context. It would appear that adding this configuration into an existing cluster and then rolling a master node causes the kubeapi to loop perpetually and fail to re-join the cluster.

**Comment by miguelbernadi** [comment]
I just got a similar issue on AWS with kops 1.18.2 where enabling this feature makes the apiserver to stop responding entirely. Times out in the TLS handshake. The only fix I found so far is to revert the config change and terminate a master to get the cluster running again, which seems less than ideal.

**Comment by ReillyTevera** [comment]
FYI as far as I can tell this has been fixed in etcd-manager by this commit: https://github.com/kopeio/etcd-manager/commit/c781d9c7112469aa198ce27abcad243b52c0d639 (which is present in etcd-manager 3.0.20210228 and should be in future versions of kops).
