### ISSUE TITLE
dns-controller multiple zone mapping via kops cluster spec

### ISSUE THREAD

**Issue by antoinedeschenes** [kubernetes/kops#9888]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
I have the following error in dns-controller:
`Found multiple hosted zones matching cluster Z...; please specify the ID of the zone to use`

I need to add multiple --zone flags to the dns-controller deployment (multiple public+private dns zones), however this can't be done using the kops cluster spec, since the only DNS zone that can be specified is the cluster DNS zone:
`https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/template_functions.go#L360`

**2. Feel free to provide a design supporting your feature request.**

-Allow some extra args on dns-controller
-Allow a DNS mapping in the yaml config

**Comment by olemarkus** [comment]
Are you using split horizon for the cluster DNS? DNS-controller only handles a few records and there shouldn't be any need for multiple zones for those. Maybe you can explain what it is you are trying to achieve?

**Comment by xoxbet** [comment]
I have the same in dns-controller logs when using split horizon DNS for one of our domains.
We are running on AWS and the idea was to save data transfer costs while accessing our container registry from cluster within the same VPC.

**Comment by olemarkus** [comment]
You should use a dedicated hosted zone for kops though. Not mix it with things that are running outside of the cluster. See https://kops.sigs.k8s.io/getting_started/aws/#scenario-1b-a-subdomain-under-a-domain-purchasedhosted-via-aws

**Comment by antoinedeschenes** [comment]
The kops cluster itself is running with it's own dedicated zone, however dns-controller autodiscovers all other route53 zones in the account including some zones which are registered both as private and public, which triggers the error message.

Now since dns-controller also supports the `dns.alpha.kubernetes.io/external` annotation on services and can watch ingresses, allowing the kops config to set multiple `--zone` args to dns-controller would let it know which zone ID it should try to manage.
