### ISSUE TITLE
Generated terraform code incompatible with terraform aws provider >= 3

### ISSUE THREAD

**Issue by pascal-hofmann** [kubernetes/kops#9891]
**1. What `kops` version are you running?**
>Version 1.18.0

**2. What Kubernetes version are you running?**
>Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
>Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
> AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops create cluster […] --target terraform` and applying twice with terraform aws provider >= 3.

**5. What happened after the commands executed?**
terraform code that was generated was causing issues with terraform aws provider version >= 3.

terraform wanted to remove the `aws_autoscaling_attachment` from `aws_autoscaling_group` for the masters, because 
`lifecycle {
    ignore_changes = [load_balancers, target_group_arns]
  }`

is missing from the generated terraform code for the `aws_autoscaling_group`. See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_autoscaling_group

**6. What did you expect to happen?**
terraform code should make no issues with terraform aws provider version >= 3

**7. Please provide your cluster manifest.**

Irrelevant.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.**
Irrelevant.

**9. Anything else do we need to know?**
No.

**Comment by karancode** [comment]
I am facing this same issue with below versions:
```
kops: Version 1.18.2 (git-84495481e4)
Terraform v0.12.16
terraform  provider "aws" (hashicorp/aws) 3.21.0.
```

Using provider version `v2.51.0` solves the issue.
Is it fixed in later version of kops ?
