### ISSUE TITLE
PV creation fails on openstack

### ISSUE THREAD

**Issue by vasuarv** [kubernetes/kops#9893]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.18.0 (git-698bf974d8)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.19.0

**3. What cloud provider are you using?**
openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster --cloud openstack \
     	--name my-cluster.k8s.local   \
	--state ${KOPS_STATE_STORE} \
     	--zones nova \
     	--network-cidr 10.0.0.0/24 \
      	--image Ubuntu-20.04-focal \
      	--master-count=1 \
      	--node-count=1 \
      	--node-size 8124120 \
      	--master-size 8124120 \
        --etcd-storage-type default \
      	--topology private \
      	--bastion \
      	--networking calico \
      	--api-loadbalancer-type public \
    	--ssh-public-key ~/sshkey.pub \
     	--os-ext-net ext-net-vlan52 \
        --os-kubelet-ignore-az=true 	

**5. What happened after the commands executed?**
The VMs get created on openstack, but the creation of the Persistent Volume fails with the following error message:

W0908 09:56:31.548562   10816 executor.go:128] error running task "Volume/a.etcd-main.my-cluster.k8s.local" (37s remaining to succeed): error creating PersistentVolume: error creating volume {20 nova   map[KubernetesCluster:my-cluster.k8s.local k8s.io/etcd/main:a/a k8s.io/role/master:1] a.etcd-main.my-cluster.k8s.local      default false}: Resource not found

**6. What did you expect to happen?**
The k8s cluster comes up 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-09-08T16:46:21Z"
  name: my-cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v3
        ignore-volume-az: true
      loadbalancer:
        floatingNetwork: ext-net-vlan52
        floatingNetworkID: d286fe57-c256-4686-b00f-d45fe8d4eebe
        method: ROUND_ROBIN
        provider: haproxy
        useOctavia: false
      monitor:
        delay: 1m
        maxRetries: 3
        timeout: 30s
      router:
        externalNetwork: ext-net-vlan52
  cloudProvider: openstack
  configBase: swift://ois/my-cluster.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-nova
      name: a
      volumeType: default
    memoryRequest: 100Mi
    name: main
    version: 3.2.24
iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.8
  masterPublicName: api.my-cluster.k8s.local
  networkCIDR: 10.0.0.0/24
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.0.32/27
    name: nova
    type: Private
    zone: nova
  - cidr: 10.0.0.0/30
    name: utility-nova
    type: Utility
    zone: nova
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
error running tasks: deadline exceeded executing task Volume/a.etcd-events.my-cluster.k8s.local. Example error: error creating PersistentVolume: error creating volume {20 nova   map[KubernetesCluster:my-cluster.k8s.local k8s.io/etcd/events:a/a k8s.io/role/master:1] a.etcd-events.my-cluster.k8s.local      default false}: Resource not found
```
**9. Anything else do we need to know?**
This is being run against an openstack cluster where kubespray seems to work. I am trying this out to evaluate if this is a better option, as it seems to offer a few more options out of the box.

**Comment by olemarkus** [comment]
From the looks of it, the create volume API call returns 404. Unfortunately not that easy to figure out what is missing, but it could be for example that the `default` block storage type doesn't exist or the given cinder availability zone.

**Comment by olemarkus** [comment]
I was able to recreate this issue in two ways, as I suspected:
* If `volumeType` is `default` instead of `rdb-volumes`. `openstack volume type list` will give you the correct value for this.
* If I left out `override-volume-az: nova`. `openstack availability zone list --volume` will give the right value here. Default is to reuse the nova AZs. But then I see you also have `ignore-volume-az: true`.

Apologies the errors here are not that straightforward, but by inspecting the block volume API, I see that we actually get anything more than "Resource not found" so we don't have much to go on either.

I will have a look if we can do some validation around actually checking the given zone and volume types exist. I am also not 100% sure that `ignore-volume-az` without `override-volume-az` has a defined behaviour. It at least didn't work for me.

/kind bug
/area provider/openstack

**Comment by vasuarv** [comment]
I believe that I tried the tests with and without the ignore-volume-az flag set, with the same result. I can retry that again and confirm.

In my case the openstack volume type list command doesn't return anything. Since I am not the admin on the openstack cluster, I was also not able to create volume type. I can try it again with rdb-volumes and see if that makes any difference. 
I can create a volume via the openstack-cli. 
```
openstack volume create --size 1 test
+---------------------+------------------------------------------------------------------+
| Field               | Value                                                            |
+---------------------+------------------------------------------------------------------+
| attachments         | []                                                               |
| availability_zone   | nova                                                             |
| bootable            | false                                                            |
| consistencygroup_id | None                                                             |
| created_at          | 2020-09-09T08:15:46.000000                                       |
| description         | None                                                             |
| encrypted           | False                                                            |
| id                  | dfe7c984-a0b2-4ce2-bcbe-cfea173e0460                             |
| multiattach         | False                                                            |
| name                | test                                                             |
| properties          |                                                                  |
| replication_status  | None                                                             |
| size                | 1                                                                |
| snapshot_id         | None                                                             |
| source_volid        | None                                                             |
| status              | creating                                                         |
| type                | None                                                             |
| updated_at          | None                                                             |
+---------------------+------------------------------------------------------------------+
```
I also noticed that in the kubespray case the default behavior seems to be to not create the persistent volume at all.

**Comment by olemarkus** [comment]
Kops uses persistent volumes so that etcd survive re-creating the master nodes. 

My guess is that you want `override-volume-az: nova`. Especially if `openstack availability zone list --compute` shows something else than `nova`.

I have no idea what to do when type is None. I see that the cinder CSI plugin also sets "None" for the volumes it creates.
Not sure why we require `storage-type` to be set either. Maybe that is a constraint that can be relaxed since it doesn't look like OS requires it.

**Comment by vasuarv** [comment]
The availability zone does show up nova.
```
$ openstack availability zone list --compute
+-----------+-------------+
| Zone Name | Zone Status |
+-----------+-------------+
| nova      | available   |
+-----------+-------------+
```
I vote for relaxing the constraint. I'd be happy to test out the change if you have a patch that you'd like me to try locally.

**Comment by olemarkus** [comment]
Have a look at https://github.com/kubernetes/kops/pull/9907
