### ISSUE TITLE
Worker nodes fail to join cluster in HA mode

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#9896]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.19.0-alpha.4+3527d32b26

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Check the e2e test for HA : https://testgrid.k8s.io/kops-misc#kops-aws-ha-euwest1

**5. What happened after the commands executed?**

n/a

**6. What did you expect to happen?**

n/a

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

n/a

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

n/a

**9. Anything else do we need to know?**

Section from [kops-configuration.log](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-misc-ha-euwest1/1298692524445011971/artifacts/176.34.156.88/kops-configuration.log):
```
I0908 20:02:32.407120    5817 executor.go:103] Tasks: 69 done / 85 total; 1 can run
I0908 20:02:32.407137    5817 executor.go:178] Executing task "BootstrapClient/BootstrapClient": BootstrapClient
W0908 20:02:32.409614    5817 executor.go:131] error running task "BootstrapClient/BootstrapClient" (9m49s remaining to succeed):
Post "https://api.internal.e2e-kops-aws-ha-euwest1.k8s.local:3992/bootstrap":
dial tcp: lookup api.internal.e2e-kops-aws-ha-euwest1.k8s.local on 127.0.0.53:53: server misbehaving
I0908 20:02:32.409643    5817 executor.go:147] No progress made, sleeping before retrying 1 task(s)
I0908 20:02:42.409809    5817 executor.go:103] Tasks: 69 done / 85 total; 1 can run
```

**Comment by hakman** [comment]
PRs merged on 2020-08-26 when the issue first appeared:
https://github.com/kubernetes/kops/pulls?q=is%3Apr+closed%3A2020-08-26+milestone%3Av1.19
/cc @johngmyers @justinsb

**Comment by johngmyers** [comment]
I think that error means that DNS is returning SERVFAIL.

**Comment by hakman** [comment]
Is it expected for the domain to be `.local` in this case?

**Comment by hakman** [comment]
This implies that for Protokube should be started for this DNS name to work, but Protokube usually starts last:
```
W0909 03:59:12.292641    1878 protokube.go:454] MasterInternalName
"api.internal.e2e-kops-aws-ha-euwest1.k8s.local" implies gossip DNS
```

**Comment by johngmyers** [comment]
`ProtokubeBuilder` creates a `Service` nodetask to create the systemd unit for protokube. `Service.GetDependencies()` causes every `Service` to have a blanket dependency on most nodetask types. Many of those will transitively depend on `BootstrapClient`.

Does protokube actually depend on the other nodetasks? Can we carve out an exception for it, at least on worker nodes?

**Comment by hakman** [comment]
Protokube itself is not the real problem, but the `LoadImageTask` which requires 'Service/Docker` or `Service/containerd` to be running to be able to load the image.
If `Service/Docker` doesn't actually require anything provided by `BootstrapClient` or its friends, we could try setting some exceptions.
