### ISSUE TITLE
etcd-manager and kops release/development process

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kops#9898]
For openstack, I added a PR to kops nudging users to use application credentials. That also required a corresponding change in etcd-manager for volume mounts, which I also did a PR for. Both PRs got accepted, but when kops alpha 3 was released, it was still referring to old etcd-manager. etcd-manager has actually not had a release with the given PR either.
This leaves any user following the nudge with broken masters.

We also have a number of issues open where users are confused about the circular dependency of kops and etcd-manager. 

I think it is worth looking into if 
a) approvers/reviewers of kops should have maintainer privileges in etcd-manager (or adopt various bots to achieve the same effect) to help out with keeping etcd-manager and kops (even alphas) in sync 
b) etcd-manager should fold into the kops monorepos and be released alongside kops.

I appreciate that b) will mean etcd-manager will no longer be seen as a standalone software with use cases outside of kops.

/cc @justinsb

**Comment by hakman** [comment]
@justinsb just managed to add `etcd-manager` to https://github.com/kubernetes-sigs/etcdadm/tree/master/etcd-manager, which is great news. This should make things much simpler.

**Comment by olemarkus** [comment]
Ah that is cool. Almost like a) then. Very curious what the plan for the mentioned convergence is.
