### ISSUE TITLE
No version when installing with Homebrew

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#991]
When installing kops from Homebrew, there is no version displayed.

```
Goddess-Of-Production:~ kris$ brew install kops
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
libmongoc
==> Updated Formulae
afflib          gflags          haproxy         noti            pugixml
checkstyle      gitbucket       imapfilter      nss             rocksdb
folly           gjstest         mikutter        osquery         srclib
fzf             glog            nghttp2         prometheus      supersonic

==> Installing dependencies for kops: kubernetes-cli
==> Installing kops dependency: kubernetes-cli
==> Downloading https://homebrew.bintray.com/bottles/kubernetes-cli-1.4.6.el_cap
######################################################################## 100.0%
==> Pouring kubernetes-cli-1.4.6.el_capitan.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/kubectl
Target /usr/local/bin/kubectl
already exists. You may want to remove it:
  rm '/usr/local/bin/kubectl'

To force the link and overwrite all conflicting files:
  brew link --overwrite kubernetes-cli

To list all files that would be deleted:
  brew link --overwrite --dry-run kubernetes-cli

Possible conflicting files are:
/usr/local/bin/kubectl
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/kubernetes-cli/1.4.6: 7 files, 60.8M
==> Installing kops
==> Downloading https://homebrew.bintray.com/bottles/kops-1.4.1.el_capitan.bottl
######################################################################## 100.0%
==> Pouring kops-1.4.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/kops/1.4.1: 3 files, 62.8M
Goddess-Of-Production:~ kris$ which kops
/usr/local/bin/kops
Goddess-Of-Production:~ kris$ kops version
Version git-
```

**Comment by chrislovecnm** [comment]
@WillPlatnick any ideas?

**Comment by WillPlatnick** [comment]
I am out of town but may have some time at the hotel room tonight to see how kops grabs the version. 






On Wed, Nov 30, 2016 at 3:41 PM -0600, "Chris Love" <notifications@github.com> wrote:












@WillPlatnick any ideas?

**Comment by chrislovecnm** [comment]
Thanks!

**Comment by WillPlatnick** [comment]
Figured out how to get the stable version in there, will work on getting the master rev in there later and then submit a PR to update our formula in the repo. I'm thinking we'll hold off on updating it until the next release as I don't think the Homebrew moderators like to do revisions for something trivial like this.

**Comment by WillPlatnick** [comment]
@kris-nova So...this is weird, but I can no longer replicate the issue across 3 different machines, 1 which never installed kops. There was a homebrew update in between I think, so that may have had something to do with it.

Can you run brew uninstall kops && brew update && brew install --HEAD kops and then run kops version to see if is showing correctly?

**Comment by WillPlatnick** [comment]
@kris-nova If it didn't work, can you run ```brew list``` so I can look for differences?

**Comment by WillPlatnick** [comment]
Nevermind @kris-nova, I see you didn't install from --HEAD. I believe these should satisfy this ticket.

PR with Homebrew is in at https://github.com/Homebrew/homebrew-core/pull/7476

Updated https://github.com/kubernetes/kops/pull/989 and squashed commits to update our formula and docs.

**Comment by chrislovecnm** [comment]
@WillPlatnick close?
