### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fnpanic** [kubernetes/kops#9912]
Hello,

i wanted to try Kops with Openstack Stein without loadbalancer and octavia.

My commandline looks like this:

`export KOPS_STATE_STORE=swift://kops

kops create cluster \
  --cloud openstack \
  --name my-cluster.k8s.local \
  --state ${KOPS_STATE_STORE} \
  --zones nova \
  --network-cidr 172.0.0.0/24 \
  --image "Linux Ubuntu Bionic 18.04 basic" \
  --master-count=3 \
  --node-count=2 \
  --node-size normal.2.2G.50GB \
  --master-size normal.2.2G.50GB \
  --etcd-storage-type RBD \
  --api-loadbalancer-type="" \
  --os-octavia=False \
  --topology private \
  --bastion \
  --ssh-public-key ~/.ssh/id_rsa.pub \
  --networking weave \
  --os-ext-net Access \
  -v 10`

Unfortunately this leads to panic and a runtime error. The host from which i run this is a ubuntu 18.04. The Kops version is  1.18.1 (git-453d7d96be). Adding -v 10 did not help me with debugging this.

`0910 20:39:06.797349    1442 bootstrapchannelbuilder.go:85] hash aa126e872270f046384926121d1f6beee982f28e
I0910 20:39:06.798241    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798259    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798268    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798275    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798281    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798293    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798303    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798309    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798316    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798325    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798342    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798353    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.798362    1442 task.go:102] testing task "Secret"
I0910 20:39:06.798369    1442 task.go:102] testing task "Secret"
I0910 20:39:06.798379    1442 task.go:102] testing task "Secret"
I0910 20:39:06.798396    1442 task.go:102] testing task "Secret"
I0910 20:39:06.798403    1442 task.go:102] testing task "Secret"
I0910 20:39:06.798413    1442 task.go:102] testing task "Secret"
I0910 20:39:06.798419    1442 task.go:102] testing task "Secret"
I0910 20:39:06.798425    1442 task.go:102] testing task "Secret"
I0910 20:39:06.798431    1442 task.go:102] testing task "Secret"
I0910 20:39:06.798448    1442 task.go:102] testing task "MirrorSecrets"
I0910 20:39:06.798458    1442 task.go:102] testing task "MirrorKeystore"
I0910 20:39:06.806465    1442 task.go:102] testing task "ManagedFile"
I0910 20:39:06.806695    1442 build_flags.go:49] ignoring non-field:
I0910 20:39:06.806714    1442 build_flags.go:49] ignoring non-field:
I0910 20:39:06.806762    1442 proxy.go:30] proxies is == nil, returning empty list
I0910 20:39:06.807257    1442 task.go:102] testing task "ManagedFile"
I0910 20:39:06.807289    1442 task.go:102] testing task "ManagedFile"
I0910 20:39:06.807301    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.807308    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.807316    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.807508    1442 build_flags.go:49] ignoring non-field:
I0910 20:39:06.807525    1442 build_flags.go:49] ignoring non-field:
I0910 20:39:06.807565    1442 proxy.go:30] proxies is == nil, returning empty list
I0910 20:39:06.808043    1442 task.go:102] testing task "ManagedFile"
I0910 20:39:06.808062    1442 task.go:102] testing task "ManagedFile"
I0910 20:39:06.808072    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.808078    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.808085    1442 task.go:102] testing task "Keypair"
I0910 20:39:06.808100    1442 task.go:75] EnsureTask ignoring identical
I0910 20:39:06.808116    1442 task.go:102] testing task "Volume"
I0910 20:39:06.808129    1442 task.go:102] testing task "Volume"
I0910 20:39:06.808146    1442 task.go:102] testing task "Network"
I0910 20:39:06.808168    1442 task.go:102] testing task "Subnet"
I0910 20:39:06.808178    1442 task.go:102] testing task "RouterInterface"
I0910 20:39:06.808188    1442 task.go:102] testing task "Subnet"
I0910 20:39:06.808196    1442 task.go:102] testing task "RouterInterface"
I0910 20:39:06.808204    1442 task.go:102] testing task "Router"
I0910 20:39:06.808237    1442 task.go:102] testing task "SSHKey"
I0910 20:39:06.808285    1442 cloud.go:351] authenticating to keystone
I0910 20:39:06.852758    1442 cloud.go:470] Openstack disabled loadbalancer support
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2c54466]

goroutine 1 [running]:
github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions.listURL(0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/gophercloud/gophercloud@v0.9.0/openstack/loadbalancer/v2/apiversions/urls.go:11 +0x26
github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions.List(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/gophercloud/gophercloud@v0.9.0/openstack/loadbalancer/v2/apiversions/requests.go:10 +0x5b
k8s.io/cloud-provider-openstack/pkg/util/openstack.getOctaviaVersion(0x0, 0x120, 0x3841460, 0x81c9b498af254201, 0xc0009b4fc0)
        /go/pkg/mod/k8s.io/cloud-provider-openstack@v1.17.0/pkg/util/openstack/loadbalancer.go:55 +0x5a
k8s.io/cloud-provider-openstack/pkg/util/openstack.IsOctaviaFeatureSupported(0x0, 0x1, 0x44521e0)
        /go/pkg/mod/k8s.io/cloud-provider-openstack@v1.17.0/pkg/util/openstack/loadbalancer.go:78 +0x2f
k8s.io/kops/pkg/model/openstackmodel.(*OpenstackModelContext).UseVIPACL(0xc0000d6458, 0xc000b0fa00)
        /go/src/k8s.io/kops/pkg/model/openstackmodel/context.go:42 +0x173
k8s.io/kops/pkg/model/openstackmodel.(*FirewallModelBuilder).Build(0xc000c327a0, 0xc000bbc910, 0x0, 0x0)
        /go/src/k8s.io/kops/pkg/model/openstackmodel/firewall.go:484 +0x8e4
k8s.io/kops/upup/pkg/fi/cloudup.(*Loader).BuildTasks(0xc0002b8700, 0x4411f00, 0xc000b9c320, 0xc000c327b0, 0x1, 0x1, 0xc0006f84d0, 0xc000cea5c0, 0xc000b94750, 0x0, ...)
        /go/src/k8s.io/kops/upup/pkg/fi/cloudup/loader.go:177 +0x448
k8s.io/kops/upup/pkg/fi/cloudup.(*ApplyClusterCmd).Run(0xc000cb8000, 0x43b59a0, 0xc0000e4008, 0x0, 0x0)
        /go/src/k8s.io/kops/upup/pkg/fi/cloudup/apply_cluster.go:809 +0x1fdc
main.RunUpdateCluster(0x43b59a0, 0xc0000e4008, 0xc0002f5060, 0x7ffd10be953b, 0x14, 0x4356d20, 0xc0000d6008, 0xc0003e1320, 0x0, 0x0, ...)
        /go/src/k8s.io/kops/cmd/kops/update_cluster.go:274 +0x9ba
main.RunCreateCluster(0x43b59a0, 0xc0000e4008, 0xc0002f5060, 0x4356d20, 0xc0000d6008, 0xc00039dc00, 0xc0001ab700, 0xc0007f9d20)
        /go/src/k8s.io/kops/cmd/kops/create_cluster.go:1357 +0x3720
main.NewCmdCreateCluster.func1(0xc000295400, 0xc0001a5c00, 0x0, 0x20)
        /go/src/k8s.io/kops/cmd/kops/create_cluster.go:274 +0x188
github.com/spf13/cobra.(*Command).execute(0xc000295400, 0xc0001a5a00, 0x20, 0x20, 0xc000295400, 0xc0001a5a00)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x61e3f80, 0x6220128, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.Execute()
        /go/src/k8s.io/kops/cmd/kops/root.go:96 +0x8f
main.main()
        /go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
`

**Comment by olemarkus** [comment]
Is there any chance you can try kops 1.19 alpha 3? We have done a lot of cleanup in this area and if I remember correctly, this bug was fixed as part of that.

**Comment by fnpanic** [comment]
@olemarkus Sure! I can try it with the same config. Will do this ASAP and report back.

**Comment by fnpanic** [comment]
Quick update

I tried the same cluster create with version Version 1.19.0-alpha.3 (git-9cb6797f6781bfa0e40758e84d26bf947824e281) and it worked!

Thank you very much!

**Comment by olemarkus** [comment]
Good to know.
Closing this one out then

/close
