### ISSUE TITLE
IG

### ISSUE THREAD

**Issue by kaviarasan-ex2** [kubernetes/kops#9914]
Hi,

I've updated the IG with maxPrice: "0.143" for spot instances. But If I want to set it back to default to on demand price I'm not able to do.. I've deleted this key value in the IG but that's not updating in the autoscaling group. Can you please advise on this..

**Comment by hakman** [comment]
@kaviarasan-ex2 Please use the bug report template to update the issue description:
https://raw.githubusercontent.com/kubernetes/kops/master/.github/ISSUE_TEMPLATE/bug_report.md
