### ISSUE TITLE
encryption/KMS required on radosgw s3

### ISSUE THREAD

**Issue by fnpanic** [kubernetes/kops#9926]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.19.0-alpha.3 (git-9cb6797f6781bfa0e40758e84d26bf947824e281)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.18.8

**3. What cloud provider are you using?**
Openstack Stein

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster \
  --cloud openstack \
  --name my-cluster.k8s.local \
  --state ${KOPS_STATE_STORE} \
  --zones fra6 \
  --network-cidr 172.0.0.0/24 \
  --image "Linux Ubuntu Bionic 18.04 basic" \
  --master-count=3 \
  --node-count=2 \
  --node-size kubeflavor \
  --master-size kubeflavor \
  --etcd-storage-type RBD \
  --api-loadbalancer-type="" \
  --os-octavia=False \
  --topology public \
  --ssh-public-key ~/.ssh/id_rsa.pub \
  --networking weave \
  --os-ext-net DMZ \
  --kubernetes-version v1.18.8 \

**5. What happened after the commands executed?**
I0912 08:59:07.637119    7605 create_cluster.go:688] Using SSH public key: /root/.ssh/id_rsa.pub
I0912 08:59:07.637350    7605 s3context.go:92] Found S3_ENDPOINT="https://s3.internal.local", using as non-AWS S3 backend
W0912 08:59:07.733523    7605 new_cluster.go:654] Running with masters in the same AZs; redundancy will be reduced
I0912 08:59:07.788884    7605 subnets.go:184] Assigned CIDR 172.0.0.32/27 to subnet fra

error writing updated configuration: error writing Cluster "my-cluster.k8s.local": error writing configuration file s3://kops/my-cluster.k8s.local/config: error writing s3://kops/my-cluster.k8s.local/config: InvalidArgument: Server Side Encryption with KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms
        status code: 400, request id: tx0000000000000259fc219-005f5c8ddf-65f841a-default, host id:

**6. What did you expect to happen?**
that the config is written to S3. The bucket is created upfront and uses host style access. S3cmd works flawless.

variables set:
export KOPS_STATE_STORE=s3://kops
export S3_ENDPOINT=https://s3.internal.local
export S3_REGION=US
export S3_ACCESS_KEY_ID=key
export S3_SECRET_ACCESS_KEY=secret

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

none yet

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.*
I0912 09:06:41.872512    7625 s3fs.go:290] Reading file "s3://kops/my-cluster.k8s.local/config"
I0912 09:06:41.880880    7625 s3fs.go:199] Writing file "s3://kops/my-cluster.k8s.local/config"
I0912 09:06:41.881002    7625 s3context.go:238] Checking default bucket encryption for "kops"
I0912 09:06:41.881092    7625 s3context.go:243] Calling S3 GetBucketEncryption Bucket="kops"
I0912 09:06:41.888504    7625 s3context.go:263] bucket "kops" has default encryption set to false
I0912 09:06:41.888633    7625 s3fs.go:237] Calling S3 PutObject Bucket="kops" Key="my-cluster.k8s.local/config" SSE="AES256" ACL=""

error writing updated configuration: error writing Cluster "my-cluster.k8s.local": error writing configuration file s3://kops/my-cluster.k8s.local/config: error writing s3://kops/my-cluster.k8s.local/config: InvalidArgument: Server Side Encryption with KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms
        status code: 400, request id: tx0000000000000259fd490-005f5c8fa5-65f841a-default, host id:

**9. Anything else do we need to know?**
it looks like kops knows that there is no encryption but still wants to use it.

**Comment by olemarkus** [comment]
When kops detects a cluster without default encryption it falls back to SSE AES. Not sure one can configure oneself out of this now. Probably another capability we should autodetect.

Unfortunately I don't think I can easily get RADOS going, but I can see if I can simulate something similar.

/kind bug
/area provider/openstack

**Comment by fnpanic** [comment]
Thanks for the feedback. I think there are several self hosted S3 systems and they all do not come with encyption on by default like minio for example.

Allowing to go without encryption would be a workaround if this is possible in the libary you are using.

**Comment by olemarkus** [comment]
This may sound a bit funny, but could you try changing scheme from `s3://` to `do://`.

Looks like `do://` path is the same as `s3://`, but has SSE disabled.

Need to have some more thinking on how to solve this meanwhile. Maybe introduce a query string or something.

**Comment by fnpanic** [comment]
Woot!

Awesome. The workaround works and creates the config flawlessly!
Thanks.

I guess this needs just a PR for the docs?
