### ISSUE TITLE
Running kops inside pod causes timeout

### ISSUE THREAD

**Issue by ysaakpr** [kubernetes/kops#9930]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
$ kops version
Version 1.18.0 (git-698bf974d8)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update cluster

**5. What happened after the commands executed?**
caused by: Put http://169.254.169.254/latest/api/token: net/http: request canceled (Client.Timeout exceeded while awaiting headers)) from ec2metadata/GetToken - will retry after delay of 11.062472704s
I0913 15:54:33.826303      49 logging_retryer.go:60] Retryable error (RequestError: send request failed
caused by: Put http://169.254.169.254/latest/api/token: net/http: request canceled (Client.Timeout exceeded while awaiting headers)) from ec2metadata/GetToken - will retry after delay of 17.762705408s
I0913 15:54:52.589421      49 logging_retryer.go:60] Retryable error (RequestError: send request failed
caused by: Put http://169.254.169.254/latest/api/token: net/http: request canceled (Client.Timeout exceeded while awaiting headers)) from ec2metadata/GetToken - will retry after delay of 55.75020544s
I0913 15:55:49.339999      49 logging_retryer.go:60] Retryable error (RequestError: send request failed
caused by: Put http://169.254.169.254/latest/api/token: net/http: request canceled (Client.Timeout exceeded while awaiting headers)) from ec2metadata/GetToken - will retry after delay of 1m57.064804352s

**6. What did you expect to happen?**
No timeouts

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Related to https://github.com/aws/aws-sdk-go/issues/2972

**Comment by olemarkus** [comment]
This issue has very little information to go on. Could you add more info about what you are trying to do and where you see those errors?

**Comment by ysaakpr** [comment]
I am running kops cmd inside a docker in a kops managed k8s cluster. I am running it's as part of an automation, and in which i try to add a new instance group and do `kops cluster update --yes`. But that causes the error mentioned above
> caused by: Put http://169.254.169.254/latest/api/token: net/http: request canceled (Client.Timeout exceeded while awaiting headers)) from ec2metadata/GetToken - will retry after delay of 11.062472704s
I0913 15:54:33.826303 49 logging_retryer.go:60] Retryable error (RequestError: send request failed
caused by: Put http://169.254.169.254/latest/api/token: net/http: request canceled (Client.Timeout exceeded while awaiting headers)) from ec2metadata/GetToken - will retry after delay of 17.762705408s
I0913 15:54:52.589421 49 logging_retryer.go:60] Retryable error (RequestError: send request failed
caused by: Put http://169.254.169.254/latest/api/token: net/http: request canceled (Client.Timeout exceeded while awaiting headers)) from ec2metadata/GetToken - will retry after delay of 55.75020544s
I0913 15:55:49.339999 49 logging_retryer.go:60] Retryable error (RequestError: send request failed
caused by: Put http://169.254.169.254/latest/api/token: net/http: request canceled (Client.Timeout exceeded while awaiting headers)) from ec2metadata/GetToken - will retry after delay of 1m57.064804352s

When researched, its mostly due to aws/aws-sdk-go#2972, but not sure how to fix it for big cluster.

**Comment by olemarkus** [comment]
By the looks of it, the metadata api is unavailable, so kops cannot assume a role. Maybe you are running kiam or using another means for firewalling the metadata API?

**Comment by hakman** [comment]
If you are running the kops binary inside a docker container inside a kops cluster created with v1.18.x, you may need to do this:
https://kops.sigs.k8s.io/cluster_spec/#networking

**Comment by ysaakpr** [comment]
> In order for containers started with docker run instead of Kubernetes to have network and internet access you need to enable the necessary iptables rules:

Little bit confused on this. This is mostly to bridging host network if you are running inside docker ran by docker run, instead of k8s. But ii am running inside k8s. I have internet access. But this is looks something else on hope count setup(aws/aws-sdk-go#2972) recently launched by ec2 metadata. 

I have other docker services which call aws apis running in the same cluster, and none of them has any issue. only kops keep getting this error.

**Comment by hakman** [comment]
Maybe you can exec into that pod and see if a curl command works.
