### ISSUE TITLE
Use SIG recommended labels for pods and services in cluster

### ISSUE THREAD

**Issue by danylohetmantsev** [kubernetes/kops#9939]
I would like to see a usage of recommended labels in metadata of pods provisioned by kops. (etcd, kube-proxy, kube-apiservice, kube-controller-manager, core-dns etc.)

Here is the official documentation link about recommended labels and their usage: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by danylohetmantsev** [comment]
As i see, it could be implemented in go-templates, at least for some of the components.

**Comment by olemarkus** [comment]
In most cases you can easily add a PR for those. There are some cases that involves label selectors and such where it may be painful to remove any labels though.
