### ISSUE TITLE
Bazel build fails for version 1.18

### ISSUE THREAD

**Issue by mat285** [kubernetes/kops#9947]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.16.4

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.15.7

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`make clean`

`make bazel-version-dist`

**5. What happened after the commands executed?**
ERROR: /private/var/tmp/_bazel_user/457f1b8383c79466c3b59e3e93219b00/external/io_bazel_rules_docker/container/BUILD:85:11: no such package '@bazel_tools//third_party/py/gflags': BUILD file not found in directory 'third_party/py/gflags' of external repository @bazel_tools. Add a BUILD file to a directory to mark it as a package. and referenced by '@io_bazel_rules_docker//container:build_tar_lib'
ERROR: Analysis of target '//cmd/kops-controller:image-bundle.tar' failed; build aborted: Analysis failed
INFO: Elapsed time: 12.777s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (29 packages loaded, 6860 targets configured)
    Fetching @com_github_pkg_errors; Restarting. 12s
    Fetching @bazel_gazelle_go_repository_tools; fetching 11s
    Fetching @com_github_google_go_containerregistry; Restarting. 11s
make: *** [bazel-kops-controller-export] Error 1

**6. What did you expect to happen?**
Bazel build should succeed without errors

**7. Please provide your cluster manifest.

N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

This fails on versions up to 1.18.1

**Comment by olemarkus** [comment]
Looks like you have the wrong version of bazel. Recommend using https://github.com/bazelbuild/bazelisk, which will automatically download and use the correct version.

**Comment by mat285** [comment]
Using bazelisk still gives the same error. I've tried a couple different bazel versions too with no luck. Seems like it's an issue with the `rules_docker` package

**Comment by hakman** [comment]
I think Bazel version for 1.18 should be 2.2.0.
https://github.com/kubernetes/kops/blob/release-1.18/.bazelversion

**Comment by mat285** [comment]
I'm trying to build version 1.16.4, any advice on the version there?

**Comment by hakman** [comment]
I think should work with 2.2.0 also.
