### ISSUE TITLE
1.19-alpha4 missing nodeup in bucket

### ISSUE THREAD

**Issue by fnpanic** [kubernetes/kops#9955]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.19.0-alpha.4 (git-ecac8c5f142ae3df9c29f3195c5bd3e67645d38e)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
cluster did not build

**3. What cloud provider are you using?**
openstack 

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster \
  --cloud openstack \
  --name my-cluster.k8s.local \
  --state ${KOPS_STATE_STORE} \
  --zones fra6 \
  --network-cidr 172.0.0.0/24 \
  --image "Linux Ubuntu Bionic 18.04 basic - virtio-blk" \
  --master-count=3 \
  --node-count=2 \
  --node-size kubeflavor \
  --master-size kubeflavor \
  --etcd-storage-type RBD \
  --api-loadbalancer-type="" \
  --os-octavia=False \
  --topology public \
  --ssh-public-key ~/.ssh/id_rsa.pub \
  --networking weave \
  --os-ext-net DMZ \
  --kubernetes-version v1.19.1

**5. What happened after the commands executed?**
I0916 21:05:22.152799   16097 create_cluster.go:706] Using SSH public key: /root/.ssh/id_rsa.pub
I0916 21:05:22.153093   16097 s3context.go:92] Found S3_ENDPOINT="https://s3-de01.cgm.hosting", using as non-AWS S3 backend
W0916 21:05:22.245032   16097 new_cluster.go:654] Running with masters in the same AZs; redundancy will be reduced
I0916 21:05:22.296634   16097 subnets.go:184] Assigned CIDR 172.0.0.32/27 to subnet fra6
Previewing changes that will be made:

cannot determine hash for "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup" (have you specified a valid file location?)

**6. What did you expect to happen?**
the cluster config gets created

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

not created

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
I0916 21:09:04.414171   16126 channel.go:153] VersionRecommendationSpec does not specify RecommendedVersion
I0916 21:09:04.414240   16126 channel.go:191] VersionRecommendationSpec does not specify RequiredVersion
I0916 21:09:04.414288   16126 channel.go:146] RecommendedVersion="1.18.8", Have="1.19.1".  No upgrade needed.
I0916 21:09:04.414347   16126 channel.go:184] RequiredVersion="1.18.0", Have="1.19.1".  No upgrade needed.
I0916 21:09:04.414406   16126 s3fs.go:290] Reading file "do://kops/my-cluster.k8s.local/kops-version.txt"
I0916 21:09:04.416566   16126 clientset.go:103] Using keystore path: "do://kops/my-cluster.k8s.local/pki"
I0916 21:09:04.416595   16126 s3fs.go:290] Reading file "do://kops/my-cluster.k8s.local/clusteraddons/default"
I0916 21:09:04.419836   16126 context.go:211] Performing HTTP request: GET https://storage.googleapis.com/kubernetes-release/release/v1.19.1/bin/linux/amd64/kubelet.sha256
I0916 21:09:04.681764   16126 builder.go:326] Found hash "2ca2a3104d4cce26db128e3a0b7a042385df4f2c51bdbe740e067fdfaa2fcdd1" for "https://storage.googleapis.com/kubernetes-release/release/v1.19.1/bin/linux/amd64/kubelet"
I0916 21:09:04.681882   16126 builder.go:243] adding file: &{DownloadURL:https://storage.googleapis.com/kubernetes-release/release/v1.19.1/bin/linux/amd64/kubelet CanonicalURL:<nil> SHAValue:2ca2a3104d4cce26db128e3a0b7a042385df4f2c51bdbe740e067fdfaa2fcdd1}
I0916 21:09:04.682011   16126 context.go:211] Performing HTTP request: GET https://storage.googleapis.com/kubernetes-release/release/v1.19.1/bin/linux/amd64/kubectl.sha256
I0916 21:09:04.933804   16126 builder.go:326] Found hash "da4de99d4e713ba0c0a5ef6efe1806fb09c41937968ad9da5c5f74b79b3b38f5" for "https://storage.googleapis.com/kubernetes-release/release/v1.19.1/bin/linux/amd64/kubectl"
I0916 21:09:04.933984   16126 builder.go:243] adding file: &{DownloadURL:https://storage.googleapis.com/kubernetes-release/release/v1.19.1/bin/linux/amd64/kubectl CanonicalURL:<nil> SHAValue:da4de99d4e713ba0c0a5ef6efe1806fb09c41937968ad9da5c5f74b79b3b38f5}
I0916 21:09:04.934176   16126 networking.go:100] Adding default ARM64 CNI plugin binaries asset: https://storage.googleapis.com/k8s-artifacts-cni/release/v0.8.6/cni-plugins-linux-amd64-v0.8.6.tgz
I0916 21:09:04.934263   16126 context.go:211] Performing HTTP request: GET https://storage.googleapis.com/k8s-artifacts-cni/release/v0.8.6/cni-plugins-linux-amd64-v0.8.6.tgz.sha256
I0916 21:09:05.069080   16126 builder.go:326] Found hash "994fbfcdbb2eedcfa87e48d8edb9bb365f4e2747a7e47658482556c12fd9b2f5  cni-plugins-linux-amd64-v0.8.6.tgz" for "https://storage.googleapis.com/k8s-artifacts-cni/release/v0.8.6/cni-plugins-linux-amd64-v0.8.6.tgz"
I0916 21:09:05.069273   16126 builder.go:243] adding file: &{DownloadURL:https://storage.googleapis.com/k8s-artifacts-cni/release/v0.8.6/cni-plugins-linux-amd64-v0.8.6.tgz CanonicalURL:<nil> SHAValue:994fbfcdbb2eedcfa87e48d8edb9bb365f4e2747a7e47658482556c12fd9b2f5}
I0916 21:09:05.069422   16126 urls.go:91] Using default base url: "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/"
I0916 21:09:05.069502   16126 context.go:211] Performing HTTP request: GET https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha256
I0916 21:09:05.498982   16126 builder.go:319] unable to read new sha256 hash file (is this an older/unsupported kubernetes release?) "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha256": unexpected response code "403 Forbidden" for "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha256": <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>ADCED81D4C6ABA03</RequestId><HostId>PVowvX68IEhaDdpPrbGKEgf7h/XjekVq80W5H06rl2fzzrnooNFcCtoUOYoYfANxwlv1o9yxcfk=</HostId></Error>
I0916 21:09:05.499033   16126 context.go:211] Performing HTTP request: GET https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha1
I0916 21:09:05.604760   16126 builder.go:321] unable to read hash file "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha1": unexpected response code "403 Forbidden" for "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha1": <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>CGFN8WBSFP7Y8W2T</RequestId><HostId>RWy8cngr+tdrmVYJVt1szamLYhDT0truTOKNseq/7KHTa/5kD6VW4J6z/kf310fXaJGyLuJO3TA=</HostId></Error>
I0916 21:09:05.605089   16126 context.go:211] Performing HTTP request: GET https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha256
I0916 21:09:05.712621   16126 builder.go:319] unable to read new sha256 hash file (is this an older/unsupported kubernetes release?) "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha256": unexpected response code "403 Forbidden" for "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha256": <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>EA424260D9FD7E45</RequestId><HostId>r9G6hYl8RCT1p7UmgX1qkyXltO16TMBaoy4mwzQOBk35ZFKYM+2uIhD9YmkitNqbeNSNJ8EH/H4=</HostId></Error>
I0916 21:09:05.712889   16126 context.go:211] Performing HTTP request: GET https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha1
I0916 21:09:05.818108   16126 builder.go:321] unable to read hash file "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha1": unexpected response code "403 Forbidden" for "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha1": <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E4A516FEF754DAD1</RequestId><HostId>zNUdZ/sQRgqDicn1A3RnTmh6+C9C787oRPauGa1RuxfYBHgbZ7VMzQRDOv2LKdtkp26N+PfXtew=</HostId></Error>
I0916 21:09:05.818188   16126 context.go:211] Performing HTTP request: GET https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha256
I0916 21:09:05.925060   16126 builder.go:319] unable to read new sha256 hash file (is this an older/unsupported kubernetes release?) "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha256": unexpected response code "403 Forbidden" for "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha256": <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>6F6214339620380F</RequestId><HostId>34e4SC1qBXcnbnd9LNFuFoLX4pwcUYncVzQbp/5biPbABQdCEM7qZrO0HQRGnE85pGc8pZmw4rM=</HostId></Error>
I0916 21:09:05.925130   16126 context.go:211] Performing HTTP request: GET https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha1
I0916 21:09:06.029801   16126 builder.go:321] unable to read hash file "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha1": unexpected response code "403 Forbidden" for "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup.sha1": <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>9B249418EDAE995D</RequestId><HostId>2G7mDC+TnqLWen2bgYQJbm4Ds8sL8FrUDXAjtZ9rlOLTdsHN8ZWoiL54VPbNihp6Sy/HNWpv54M=</HostId></Error>

cannot determine hash for "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup" (have you specified a valid file location?)

**9. Anything else do we need to know?**
nope

**Comment by fnpanic** [comment]
mark this duplicate with #9951 sorry.

**Comment by hakman** [comment]
@fnpanic this workaround should help: https://github.com/kubernetes/kops/issues/9951#issuecomment-694021460.
