### ISSUE TITLE
OpenStack kops-controller (re)auth problem part 2 (Swift)

### ISSUE THREAD

**Issue by kciredor** [kubernetes/kops#9956]
Kops version 1.17.2 (latest 1.17 release) running Kubernetes 1.17.11 on OpenStack .

Unfortunately the fix that was merged here https://github.com/kubernetes/kops/pull/8862 did not entirely solve the kops-controller token expiry issue.

Repeating my previous comment here for clarity:

gophercloud ReAuth default false... I mean... 👎 Now it's fixed for etcd-controller and supposedly for kops-controller but these are the logs many times per minute:

E0915 08:48:02.481845 1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="unable to load cluster object for node nodes-4-xxx-k8s-local: error loading Cluster "swift://xxx/xxx.k8s.local/cluster.spec": error reading swift://xxx/xxx.k8s.local/cluster.spec: Authentication failed" "controller"="node" "request"={"Namespace":"","Name":"nodes-4-xxx-k8s-local"}

**Comment by zetaab** [comment]
https://github.com/kubernetes/kops/pull/9842

**Comment by kciredor** [comment]
Thanks @zetaab, I was positive 1.17.2 had this merged as well but I was wrong ;-) Will test with 1.18.x asap.

**Comment by kciredor** [comment]
Just tested with kops 1.18.2 and I'm afraid etcd-manager backups are not coming in after 60 minutes, @zetaab. Reauth issue still there.

(On the other hand: kops-controller reconcile loop has indeed been fixed which is great)
