### ISSUE TITLE
Add configuration keys for Annotations to Cluster resources.

### ISSUE THREAD

**Issue by iusergii** [kubernetes/kops#9960]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
It would be nice to have an option to add custom annotations to the Cluster Control Plane resources.  We lack this for configuration:
* Monitoring 
* Logs dissect

**Comment by FrederikNS** [comment]
We could also really use this feature.

We run kops with flatcar linux, and have the flatcar-update-operator installed to restart the nodes when the update is ready.

This works well on on-demand nodes, but less well on spot-instances and auto-scaling nodes as they come and go. Therefore we would like to set the `flatcar-linux-update.v1.flatcar-linux.net/reboot-paused` annotation on spot and autoscaled instances, which will make the update operator avoid rebooting those nodes.

**Comment by olemarkus** [comment]
Most likely this is something that kops-controller would be able to set. This is the component that is setting labels today.
It should not be too hard to implement, so if you want to do a PR, I would be happy to review.
