### ISSUE TITLE
change api server livenessProbe toi livez from healthz

### ISSUE THREAD

**Issue by grosser** [kubernetes/kops#9977]
https://kubernetes.io/docs/reference/using-api/health-checks/#api-endpoints-for-health says that healthz is deprecated, so it would be nice to stop using it ... not sure how much work that is though.
Not producing any issues, just saw that while reading the docs.

**Comment by mmerrill3** [comment]
@grosser I see two areas of change.  One is the addition of new arguments to the API server to configure settings for livez.  This includes adding new yaml configuration for the APIServer and implementing the options at the command line for the appropriate k8s version.  This would be updates to API protocolbuffers for kops, documentation, and changing the task to create the API server's launch options.  Testing as well.
The other is the changes in the health check sidecar that is used by kops (https://github.com/kubernetes/kops/pull/9069) so it can pass through livez requests.

I think it would be a medium/large effort.

**Comment by mmerrill3** [comment]
The sidecar will pass through requests to livez from the PR: (#9069)

Are you aiming to be able to set configuration for the livez check in the api server, like --livez-grace-period?

**Comment by grosser** [comment]
wow thx for the info ... I'd say that's more work then I hoped for ... so let's let this sit until the endpoint actually goes away :)
