### ISSUE TITLE
aws getting started docs no client side encryption

### ISSUE THREAD

**Issue by CrossRoast** [kubernetes/kops#9978]
The getting started docs for the AWS cloud provider seem to suggest that kops uses client side encryption when it's unable to verify encryption configuration of the state store S3 bucket. Instead, I see from the source code that kops asks S3 to use the default AES256 server side encryption.

**Comment by olemarkus** [comment]
Thanks for reporting this. Is there any chance you could contribute a pull request amending this?

**Comment by CrossRoast** [comment]
Sure, linked the pull request. Would a client side encryption feature be desired in the future?
