### ISSUE TITLE
Change TerminatedPodGcThreshold Setting

### ISSUE THREAD

**Issue by brunoalano** [kubernetes/kops#998]
How it's possible to change the `TerminatedPodGcThreshold` setting [1]?

[1]https://github.com/kubernetes/kops/blob/f6d1c33ccad5de7998de87eae6e1b6ecd3306ea0/pkg/apis/kops/v1alpha1/cluster.go#L196

**Comment by chrislovecnm** [comment]
Not built in yet.  If you want to add a new feature, you can check out https://github.com/kubernetes/kops/blob/master/docs/adding_a_feature.md

**Comment by brunoalano** [comment]
@chrislovecnm No problem, I can contribute. But you can just point where should I begin? I'm not familiar with Kubernetes neither Docker, I'm only a data scientist that use them to deployment

**Comment by chrislovecnm** [comment]
go?  The above guide gives you a good layout of what to do.  I am not even sure which component gets the value.  We are going to have office hours next Friday, or we can talk about it in the PR.  Your choice.

**Comment by kris-nova** [comment]
@brunoalano you can find more information on how to track us down, and about our office hours [here](https://github.com/kubernetes/kops#getting-involved)

Office hours are an open call that we have, when we help people get started in the code base, and help get issues through the development process.

Also if you just need a quick pointer you can DM me on slack - I am there all the time

Hope this help!

**Comment by alex88** [comment]
I've seen this has been merged, but where do I set that in the cluster config?

**Comment by minkimipt** [comment]
this can always be retrieved from the CRD:
https://github.com/kubernetes/kops/blob/165ad24b0d1ba24e5e97d662fc5280f48921d91b/k8s/crds/kops.k8s.io_clusters.yaml#L2261
