### ISSUE TITLE
Surge during rolling update does not work for mixed instances Auto Scaling Groups

### ISSUE THREAD

**Issue by paalkr** [kubernetes/kops#9983]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.18.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.17.11

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Create an instance group with `spec.mixedInstancesPolicy` and add `rollingUpdate `either to the cluster spec or IG spec.
```
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
```
Then execute `kops rolling-update cluster --instance-group <IG-name> --yes` .

**5. What happened after the commands executed?**
Replacing nodes follows the old pattern, where one instance is "cordoned" and removed before a replacing instance is created.

**6. What did you expect to happen?**
That a replacing instance was first created and added to the cluster, before a instance is removed.

**9. Anything else do we need to know?**
The feature was introduced in https://github.com/kubernetes/kops/pull/8313

**Comment by olemarkus** [comment]
Thanks for reporting this.
I can reproduce this on kops 1.18, but seems to have been fixed in kops 1.19.

**Comment by paalkr** [comment]
Thanks for confirm the issue. It does seem a little inconsistent. Some of my AGSs with Mixed instances seems to behave as expected, and some don't. I cannot pinpoint anything that indicates why some work.

**Comment by paalkr** [comment]
Actually, it looks like the first instance in the rolling-update cycle is detached and replaced as expected, but the next instances are just terminated and then replaced.
![image](https://user-images.githubusercontent.com/9726307/94194756-688e2000-feb2-11ea-9d6f-db83acb2310b.png)

**Comment by olemarkus** [comment]
There is something very interesting going on here. I have an IG with instance a, b, c
* It detaches a
* waits for new node d
* d joins and cluster validates
* kops terminates instance c
* kops goes into "did not have enough nodes 2 vs 3"
* a remains detached

Looks like kops struggle to find the correct node to terminate.

**Comment by paalkr** [comment]
I experience a similar behavior, except that a actually gets terminated.

**Comment by olemarkus** [comment]
![image](https://user-images.githubusercontent.com/77034/94232818-1aefd280-ff07-11ea-95d4-a352e821306a.png)

This is what I got.

**Comment by paalkr** [comment]
I think you are right, the reason why it only work for the first instance, is because kops delete a random instance in the AGS not the detached instance.

**Comment by paalkr** [comment]
The problem is for sure that kops drains and terminates the wrong node. Look at the logs and timeline below
First kops detach instance
`ip-10-4-218-230.eu-north-1.compute.internal`
AWS adds a replacement instance `i-0dbc24d5b2ca10afb (ip-10-4-210-42.eu-north-1.compute.internal)`
Then later kops terminates
`ip-10-4-143-1.eu-north-1.compute.internal` which is still part of the AGS

```
NAME    STATUS          NEEDUPDATE      READY   MIN     TARGET  MAX     NODES
spot    NeedsUpdate     3               0       3       3       20      3
I0925 10:56:37.517321   12153 instancegroups.go:383] Validating the cluster.
I0925 10:56:38.272271   12153 instancegroups.go:416] Cluster validated.
I0925 10:56:38.272313   12153 instancegroups.go:282] Tainting 3 nodes in "spot" instancegroup.
I0925 10:56:38.354695   12153 instancegroups.go:462] Detaching instance "i-0fc880572b75e5597", node "ip-10-4-218-230.eu-north-1.compute.internal", in group "spot.k8s11.gdo.aws".
I0925 10:56:38.718319   12153 instancegroups.go:143] waiting for 15s after detaching instance
I0925 10:56:53.718748   12153 instancegroups.go:383] Validating the cluster.
I0925 10:56:54.760119   12153 instancegroups.go:419] Cluster validated; revalidating in 10s to make sure it does not flap.
I0925 10:57:05.762976   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 10:57:36.574815   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 10:58:07.481210   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 10:58:38.303350   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 10:59:09.179861   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 10:59:39.938961   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 11:00:10.905673   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 11:00:41.832862   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 11:01:12.731063   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 11:01:43.542426   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 11:02:14.439098   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 11:02:45.312543   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": machine "i-0dbc24d5b2ca10afb" has not yet joined cluster.
I0925 11:03:16.308246   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": node "ip-10-4-210-42.eu-north-1.compute.internal" is not ready, system-node-critical pod "kube-flannel-ds-vf6jf" is pending, system-node-critical pod "kube-node-drainer-ds-phb2p" is pending.
I0925 11:03:47.095652   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": system-node-critical pod "kube-node-drainer-ds-phb2p" is pending.
I0925 11:04:17.975899   12153 instancegroups.go:419] Cluster validated; revalidating in 10s to make sure it does not flap.
I0925 11:04:28.780077   12153 instancegroups.go:416] Cluster validated.
I0925 11:04:28.780138   12153 instancegroups.go:340] Draining the node: "ip-10-4-143-1.eu-north-1.compute.internal".
WARNING: ignoring DaemonSet-managed Pods: kube-loki/promtail-m6lnj, kube-monitoring/monitoring-prometheus-node-exporter-jnbdd, kube-system/kiam-agent-zvrfs, kube-system/kube-flannel-ds-h55lh, kube-system/kube-node-drainer-ds-sv7xl, rook-ceph/csi-cephfsplugin-fmkxr, rook-ceph/csi-rbdplugin-k6bbn
evicting pod kube-nginx-ingress-controller/ingress-nginx-internal-7c655db6f6-2qhv7
evicting pod kube-system/reloader-reloader-85cd94758d-mxc7w
evicting pod kube-system/coredns-54ffc8b995-zfvzb
evicting pod kube-system/coredns-autoscaler-845866d655-ntmjw
evicting pod rook-ceph/rook-ceph-mds-r2-fs-b-9d79b8c49-kpdsw
evicting pod kube-loki/ingester-0
evicting pod kube-monitoring/prometheus-prometheus-prometheus-0
evicting pod kube-system/metrics-server-5666fb4cc8-8w9xc
evicting pod kube-postgres-operator/postgres-operator-54cf75c885-8s5ht
evicting pod kube-monitoring/monitoring-kube-state-metrics-5f4d9ddc46-fwkt8
evicting pod kube-nginx-ingress-controller/ingress-nginx-d6b945fc6-wfwts
evicting pod rook-ceph/rook-ceph-mds-r2-fs-e-6568fc6fdc-xk2sw
evicting pod kube-cert-manager/cert-manager-b9666547c-75dfp
evicting pod rook-ceph/rook-ceph-crashcollector-596624a1a8567fd4fc29d050a040259f-96sq9
evicting pod kube-cert-manager/cert-manager-webhook-75bd7d8ccb-m4tkx
evicting pod kube-build-agents/gdo-build-agent-59bfdff6d7-fpn8h
evicting pod kube-loki/distributor-65b6c8cf69-rksmp
evicting pod rook-ceph/rook-ceph-mds-r2-fs-f-5688bf69d9-9gcr9
evicting pod rook-ceph/rook-ceph-mon-c-8c5476bdc-plx7h
I0925 11:04:30.026195   12153 request.go:621] Throttling request took 1.000119s, request: POST:https://api.k8s11.gdo.aws/api/v1/namespaces/rook-ceph/pods/rook-ceph-mds-r2-fs-e-6568fc6fdc-xk2sw/eviction
I0925 11:04:40.082408   12153 request.go:621] Throttling request took 3.5801742s, request: GET:https://api.k8s11.gdo.aws/api/v1/namespaces/kube-system/pods/coredns-54ffc8b995-zfvzb
I0925 11:05:01.142589   12153 instancegroups.go:546] Waiting for 5s for pods to stabilize after draining.
I0925 11:05:06.142892   12153 instancegroups.go:359] deleting node "ip-10-4-143-1.eu-north-1.compute.internal" from kubernetes
I0925 11:05:06.184614   12153 instancegroups.go:486] Stopping instance "i-05c6e118319f6d8e1", node "ip-10-4-143-1.eu-north-1.compute.internal", in group "spot.k8s11.gdo.aws" (this may take a while).
I0925 11:05:06.350939   12153 instancegroups.go:372] waiting for 15s after terminating instance
I0925 11:05:21.351156   12153 instancegroups.go:383] Validating the cluster.
W0925 11:05:22.012010   12153 aws_cloud.go:757] ignoring instance as it is terminating: i-05c6e118319f6d8e1 in autoscaling group: spot.k8s11.gdo.aws
I0925 11:05:22.349933   12153 instancegroups.go:440] Cluster did not pass validation, will retry in "30s": InstanceGroup "spot" did not have enough nodes 2 vs 3.
...
```

**Comment by olemarkus** [comment]
@johngmyers could you have a look here? This happens very consistently, and when I look at the code, it seems like we first sort nodes by attached/detached, then detach from the end of the node list, but terminate from the front of it.

**Comment by johngmyers** [comment]
Rolling update is indeed supposed to terminate the detached instances last. When c gets terminated the ASG is supposed to create a new instance to replace it.

**Comment by olemarkus** [comment]
Yeah that makes sense. No point in keep terminating and detaching.

**Comment by paalkr** [comment]
Ahh, ok. That make sense. So for an ASG with three nodes (`a`,`b` and `c`) it would be like this

kops detaches `a` from the ASG, but do not drained nor remove `a` from the k8s cluster.
ASG adds `d` to replace `a`
kops wait for `d` to join
kops drains `b`, most pods are probably moved to `d`, but some pods might end up at `c` or `a` if there is free capacity
kops terminates and removes `b`  from the k8s cluster
ASG add `e` to replace `b`
kops wait for `e` to join
kops drains `c`, most pods are probably moved to `e`, but some pods might end up at `d` or `a` if there is free capacity
kops terminate and `c` from the k8s cluster
ASG add `f` to replace `c`
kops wait for `f` to join
kops drains `a`, most pods are probably moved to `f`, but some pods might end up at `d` or `e` if there is free capacity

Anything I missed?

**Comment by johngmyers** [comment]
As mentioned in [the documentation](https://kops.sigs.k8s.io/operations/rolling-update/), there's a soft taint placed on a, b, and c to encourage the scheduler to not move pods there.

So can this be closed Working As Designed?

**Comment by johngmyers** [comment]
Also, `maxSurge: 1` is the default for worker IGs on AWS.

Try `maxSurge: "100%"` sometime. It's a blast. Just make sure you have `PodDisruptionBudget`s in place.

**Comment by paalkr** [comment]
Thanks for clearing up my misunderstanding. Yes, I will close this
