### ISSUE TITLE
Too many bootstrap tokens prohibits nodes from joining cluster

### ISSUE THREAD

**Issue by eli-rh** [kubernetes/kops#9987]
**1. What kops version are you running? The command kops version, will display
this information.**

1.16

**2. What Kubernetes version are you running? kubectl version will print the
version if a cluster is running or provide the Kubernetes version specified as
a kops flag.**

1.16

**3. What cloud provider are you using?**

AWS

**4. What commands did you run? What is the simplest way to reproduce this issue?**

The issue arose when attempting to scale our cluster up; specifically, when a newly-provisioned node tried to join the cluster. 

**5. What happened after the commands executed?**

The newly-provisioned node attempted to acquire a node bootstrap token. (https://github.com/kubernetes/kops/blob/master/node-authorizer/pkg/server/admission.go#L148)

The token creation was successful, but the verification that the random token did not already exist failed due to a timeout. The `hasToken` function performs a list operation, using the token name as a label. The timeout for this list operation is 2 seconds (https://github.com/kubernetes/kops/blob/master/node-authorizer/pkg/server/admission.go#L154). When there are a lot of existing bootstrap tokens (for our cluster, greater than around 5k), this list operation takes more than 2 seconds, the token creation fails, and the entire operation retries 5 seconds later. This causes a feedback loop where more and more tokens get generated.

Trace:
{"level":"info","ts":1599849922.7042906,"caller":"client/client.go:39","msg":"attempting to acquire a node bootstrap configuration","timeout":20,"authorizer":"aws","kubeapi-url":<REDACTED>,"kubeconfig":"/var/lib/kubelet/bootstrap-kubeconfig","registration-url":<REDACTED>}
Sep 11 18:45:32 ip-10-20-167-234 docker[27717]: {"level":"error","ts":1599849932.707042,"caller":"client/client.go:69","msg":"failed to request bootstrap token from node authorizer service","error":"Post <REDACTED>: net/http: request canceled (Client.Timeout exceeded while awaiting headers)","stacktrace":"k8s.io/kops/node-authorizer/pkg/client.New.func1\n\t/home/jest/go/src/k8s.io/kops/node-authorizer/pkg/client/client.go:69\nk8s.io/kops/node-authorizer/pkg/utils.Retry\n\t/home/jest/go/src/k8s.io/kops/node-authorizer/pkg/utils/retry.go:35\nk8s.io/kops/node-authorizer/pkg/client.New\n\t/home/jest/go/src/k8s.io/kops/node-authorizer/pkg/client/client.go:66\nmain.actionClientCommand\n\t/home/jest/go/src/k8s.io/kops/node-authorizer/cmd/node-authorizer/client.go:93\nmain.addClientCommand.func1\n\t/home/jest/go/src/k8s.io/kops/node-authorizer/cmd/node-authorizer/client.go:86\nk8s.io/kops/vendor/github.com/urfave/cli.HandleAction\n\t/home/jest/go/src/k8s.io/kops/vendor/github.com/urfave/cli/app.go:490\nk8s.io/kops/vendor/github.com/urfave/cli.Command.Run\n\t/home/jest/go/src/k8s.io/kops/vendor/github.com/urfave/cli/command.go:210\nk8s.io/kops/vendor/github.com/urfave/cli.(*App).Run\n\t/home/jest/go/src/k8s.io/kops/vendor/github.com/urfave/cli/app.go:255\nmain.main\n\t/home/jest/go/src/k8s.io/kops/node-authorizer/cmd/node-authorizer/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}

The fix is to manually delete all the bootstrap tokens. This stops the timeout, allows the node to get a new token, and then the node can join the cluster.

Questions about this:
- Why are tokens randomly generated, and not based on a node ID? It seems like if tokens were based on a unique node ID rather than a purely random uuid, it would not be necessary to check whether the token already exists. Further, it would be easy to re-use a non-expired bootstrap token, as it would correspond directly to the node 

- Why does `hasToken` perform a list operation instead of a get operation? Since the list searches on a unique label and limits the responses to one, it is effectively a costly get operation that can potentially lead to this feedback loop.

- Why is the default token retention period so long? A bootstrap token should not need to exist after a node has joined the cluster. We experienced many leaked tokens because we scale our k8s cluster heavily on a daily basis, which led to this issue.

**7. Anything else do we need to know?**

This does not appear to have been fixed as of version 1.18.

/kind bug

@uruddarraju

**Comment by johngmyers** [comment]
Node-authorizer will no longer be used for AWS as of kops 1.19. There will be a new mechanism for authorizing nodes that doesn't use bootstrap tokens.

**Comment by eli-rh** [comment]
Thanks.
