### ISSUE TITLE
Cluster-from-kubeconfig relies on us generating a kubeconfig; do we want to do that

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#9990]
Q: How important is the "default cluster from kubeconfig" behaviour to user experience?  Should we try to reinstate that behaviour by exporting kubeconfig by default?

**Background**

Historically, we used the current cluster in kubeconfig to make specifying the cluster name optional for most commands, making the flow a little easier.

Recently we've started not exporting the kubeconfig by default (though you can pass an `--admin` flag) which means that the cluster name must be specified on every command.

We did this for security, because kubeconfig previously contained non-expiring credentials.

Recently we introduced experimental support for automatically getting a short-lived credential by having kops generate the credential when the current credential had expired.  We could therefore safely export a kubeconfig by default again (from a security point of view), except that this functionality is relatively new and not particularly widely tested.

**Comment by olemarkus** [comment]
@justinsb guess this can be closed now?

Just running `kops export kubecfg --admin` also works, defaulting to the current context

/remove-lifecycle rotte

**Comment by olemarkus** [comment]
I think we have more or less solved this one now

/close
/remove-lifecycle stale
