### ISSUE TITLE
LoadBalancer task always run during cluster update

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#9992]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
$ kops update cluster

...
  LoadBalancer/api.<cluster_name>
  	ForAPIServer        	 false -> true
...
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Version 1.19.0-alpha.4 

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
$ kops update cluster
```

**5. What happened after the commands executed?**

n/a

**6. What did you expect to happen?**

I would expect the task to only run once, not on every update.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

n/a

**9. Anything else do we need to know?**

/cc @johngmyers @justinsb

**Comment by rifelpet** [comment]
Independent of this specific bug, I was thinking it would be useful to perform various API changes and confirm that a second `update cluster` doesn't report any changes. We do something similar in the [lifecycle integration tests](https://github.com/kubernetes/kops/blob/d9b99fccca70ba01882765746f0c732a7f7e1e19/cmd/kops/lifecycle_integration_test.go#L196-L203) but that's only for cluster creation. If we could set/unset every optional field in ClusterSpec and InstanceGroupSpec, that would give us a lot more coverage into related bugs and gaps in reconciliation logic for cloud providers. Maybe I'll spin this off into a separate issue.

**Comment by rifelpet** [comment]
Looks related to https://github.com/kubernetes/kops/pull/9450/files

We probably need to be setting `ForAPIServer` in `awstasks`' [LoadBalancer.Find()](https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awstasks/load_balancer.go#L282)

**Comment by rifelpet** [comment]
@hakman can this be closed out?

**Comment by hakman** [comment]
I think so.
/close
