### ISSUE TITLE
add hostPort support to Cilium

### ISSUE THREAD

**Issue by nustiueudinastea** [kubernetes/kops#9999]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

At the moment kops does not enable the hostPort functionality supported by Cilium. This means that a default kops installation using Cilium does not support hostPorts. 

**2. Feel free to provide a design supporting your feature request.**

In order to enable this, kops needs to set the `enable-host-port` configuration parameter in the Cilium configmap, which can be found [here](https://github.com/cilium/cilium/blob/758539bb0d7dec2ac4095cf4bf07ad21183fc647/install/kubernetes/cilium/charts/config/templates/configmap.yaml#L459).

**Comment by olemarkus** [comment]
Can you elaborate on why you need to configure this one?

**Comment by nustiueudinastea** [comment]
Hi @olemarkus , hostPort functionality seems to me like fundamental functionality for any Kubernetes cluster. In case this requirement is rarely requested and I am in the minority, I can definitely accept that and do a custom installation of Cilium. Thanks!

**Comment by olemarkus** [comment]
`--enable-host-port` is defaults to on though.

**Comment by nustiueudinastea** [comment]
Ok got it. I only looked at the Cilium configmap and noticed that `enable-host-port` does not appear there and I assumed its disabled. Also hostPort functionality doesn't work on the default kops + Cilium installation so I assumed the missing configmap entry is the culprit. I will close this. Thanks for your time @olemarkus !

**Comment by olemarkus** [comment]
We are using HostPort quite a bit without any problems. It may depend on other configurations of your cluster maybe.

**Comment by nustiueudinastea** [comment]
I was using kops 1.18.1 and looking at the cilium pod logs I couldn't see param `enable-host-port` being added. I am now trying with kops 1.19.0-alpha4 to see if this makes a difference. It is possible that I am doing something else wrong but I can't figure out what.

**Comment by olemarkus** [comment]
Think you are mixing the defaults of the cilium helm chart with the defaults of the cilium agent.

**Comment by olemarkus** [comment]
Worth to mention that for kops 1.19, we are using cilium's own hostport implementation in BPF by default and you definitely don't want to enable the cni chain.

**Comment by nustiueudinastea** [comment]
I confirm that kops 1.19 alpha4 works. Perhaps for the 1.18 deployment I didnt enable the portmap chaining, but I never figured out with certainty what I did wrong. Thanks!
